### PR TITLE
test: deflake TestRecycleSlices test

### LINKED ISSUE #93449: TestRecycleSlices/1_to_create_and_1_to_delete_for_each_IP_family is flaking
```
--- FAIL: TestRecycleSlices (0.01s)
    --- PASS: TestRecycleSlices/Empty_slices (0.00s)
    --- PASS: TestRecycleSlices/1_to_create_and_1_to_delete (0.00s)
    --- PASS: TestRecycleSlices/1_to_create,_update,_and_delete (0.00s)
    --- PASS: TestRecycleSlices/2_to_create_and_1_to_delete (0.00s)
    --- PASS: TestRecycleSlices/1_to_create_and_2_to_delete (0.00s)
    --- FAIL: TestRecycleSlices/1_to_create_and_1_to_delete_for_each_IP_family (0.00s)
    --- PASS: TestRecycleSlices/1_to_create_and_1_to_delete,_wrong_IP_family (0.00s)
```

seen in the PR updating to go1.15, but this unit test should not be flaky

/assign @robscott

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:

sorts the endpoint slices by name in test `TestRecycleSlices`

**Which issue(s) this PR fixes**:

Fixes #93449 

**Special notes for your reviewer**:

ref: https://github.com/kubernetes/kubernetes/issues/93449#issuecomment-663940310

> @liggitt: looks like toCreateByAddrType is a map which doesn't have a defined iteration order, so the address family order of toUpdate is not well-defined
> https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpointslicemirroring/reconciler_helpers.go#L108

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/endpointslicemirroring/reconciler_helpers_test.go [hunk 1]
```diff
@@ -138,6 +139,13 @@ func expectEqualSlices(t *testing.T, actual, expected []*discovery.EndpointSlice
 		t.Fatalf("Expected %d EndpointSlices, got %d: %v", len(expected), len(actual), actual)
 	}
 
+	sort.Slice(actual, func(i, j int) bool {
+		return actual[i].Name < actual[j].Name
+	})
```
Comment (liggitt) [inline pkg/controller/endpointslicemirroring/reconciler_helpers_test.go:144]: suggest moving this to line 127 and sorting `t.startingSlices.{toCreate,toUpdate,toDelete}`, and avoiding mutating expectedSlices (we can put those in sorted order in the test setup)

File: pkg/controller/endpointslicemirroring/reconciler_helpers_test.go [hunk 2]
```diff
@@ -138,6 +139,13 @@ func expectEqualSlices(t *testing.T, actual, expected []*discovery.EndpointSlice
...
+	sort.Slice(expected, func(i, j int) bool {
+		return expected[i].Name < expected[j].Name
+	})
+
```
Comment (liggitt) [inline pkg/controller/endpointslicemirroring/reconciler_helpers_test.go:148]: suggest dropping this bit
