### PR TITLE
Do not error log CRI stats for not cached partitions

### LINKED ISSUE #94825: CRI getFsInfo logs errors for valid filesystems mounted after kubelet start
**What happened**:

New overlay filesystems created for Pods after kubelet start trigger repeated error messages. For example:

```
cri_stats_provider.go:375] Failed to get the info of the filesystem with mountpoint "/var/lib/containers/storage/overlay/2243263dc8ba6c55d8867d3e47bcaaa145d15f0ace19420824d639d86defe2e3/merged": failed to get device for dir "/var/lib/containers/storage/overlay/2243263dc8ba6c55d8867d3e47bcaaa145d15f0ace19420824d639d86defe2e3/merged": could not find device with major: 0, minor: 83 in cached partitions map.
```

Error messages are logged every 10 seconds for every filesystem created after kubelet start. For large kubelet nodes, this issue creates an excessive amount of error logs.

**What you expected to happen**:

New overlay filesystems created for Pods after kubelet start should not log error messages.

**How to reproduce it (as minimally and precisely as possible)**:

Use cri_stats_provider with cri-o and configure overlay storage. UsingLegacyCadvisorStats() needs to return false per https://github.com/cri-o/cri-o/pull/3054 for cri_stats_provider to be used. Start with an empty /var/lib/containers/storage and schedule Pods on the node.

**Anything else we need to know?**:

As part of https://github.com/kubernetes/kubernetes/pull/59475, cadvisor.GetFsInfoByFsUUID() was changed to cadvisor.GetDirFsInfo() in getFsInfo(); however, the test for cadvisorfs.ErrNoSuchDevice was not modified, changing how getFsInfo() handles a cache miss from cadvisor. 

cadvisor caches UUIDs/partitions/mounts on kubelet start and the cache is never refreshed. Given that it's expected that getFsInfo() will fail to retrieve data from cadvisor (see comments in ImageFsStats() and https://github.com/kubernetes/heapster/issues/1793), this condition should not be logged as an error. Alternatively, cadvisor fs could be modified to refresh on cache miss enabling getFsInfo() to return data on these filesystems.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6
- CRI: CRI-O

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We do not have any cached partitions available on Kubelet start with an
empty container storage in CRI-O. This means that the error log message
is not actually an error and more an information.

This means we now pre-filter those cases and do not `klog.ErrorS` any
more. This helps to avoid log spamming in huge clusters.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/94825

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
Changed kubelet logs from error to info for uncached partitions when using CRI stats provider
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL :)

**Review by ehashman — COMMENTED** [review]
/lgtm

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 1]
```diff
@@ -363,7 +364,10 @@ func (p *criStatsProvider) getFsInfo(fsID *runtimeapi.FilesystemIdentifier) *cad
 	fsInfo, err := p.cadvisor.GetDirFsInfo(mountpoint)
 	if err != nil {
 		msg := "Failed to get the info of the filesystem with mountpoint"
-		if err == cadvisorfs.ErrNoSuchDevice {
+		noDataFound := errors.Is(err, memory.ErrDataNotFound) ||
+			// from: https://github.com/kubernetes/kubernetes/blob/cf3374e/vendor/github.com/google/cadvisor/fs/fs.go#L593
+			strings.HasSuffix(err.Error(), "in cached partitions map")
```
Comment (mrunalp) [inline pkg/kubelet/stats/cri_stats_provider.go:369]: Does it make sense to return a custom error from cadvisor for this?

Comment (saschagrunert) [reply pkg/kubelet/stats/cri_stats_provider.go:369]: I think so. I proposed the change at https://github.com/google/cadvisor/pull/2859

We may wanna switch as follow-up to that type to unblock this PR?

**Comment by ehashman** [comment]
/lgtm cancel

while waiting on Mrunal's requested changes

**Comment by saschagrunert** [comment]
> while waiting on Mrunal's requested changes

I'd say we follow-up with those changes after cadvisor has released a final version which includes the fix to unblock this PR. WDYT @mrunalp

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 1 above)
Comment (ehashman) [reply pkg/kubelet/stats/cri_stats_provider.go:369]: That has merged, can we update?

Comment (saschagrunert) [reply pkg/kubelet/stats/cri_stats_provider.go]: Yes, changed to validate the error from cadvisor.

Comment (saschagrunert) [reply pkg/kubelet/stats/cri_stats_provider.go]: Ugh, we have to move the error into a place without build constraints. Following-up in https://github.com/google/cadvisor/pull/3018

**Comment by karlhjm** [comment]
你好！我已经收到你的邮件！

**Comment by saschagrunert** [comment]
Requires a new cadvisor 0.4x.y release after https://github.com/google/cadvisor/pull/3018 got merged.

**Comment by saschagrunert** [comment]
This seems to be ready now, PTAL @mrunalp @ehashman

**Comment by saschagrunert** [comment]
@dashpole please take a look, too :)

**Comment by dashpole** [comment]
Won't the kubelet be missing filesystem metrics when this is the case?  Should we prioritize refreshing the cached partitions map instead of lowering the verbosity of the error message?

**Comment by pacoxu** [comment]
/cc @haircommander  @bobbypage 

> Won't the kubelet be missing filesystem metrics when this is the case? Should we prioritize refreshing the cached partitions map instead of lowering the verbosity of the error message?

This will constantly be called. @saschagrunert  The cached partitions map will be updated later after kubelet/cadvisor start for seconds.

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 2]
```diff
@@ -449,7 +450,9 @@ func (p *criStatsProvider) getFsInfo(fsID *runtimeapi.FilesystemIdentifier) *cad
 	fsInfo, err := p.cadvisor.GetDirFsInfo(mountpoint)
 	if err != nil {
 		msg := "Failed to get the info of the filesystem with mountpoint"
-		if err == cadvisorfs.ErrNoSuchDevice {
+		if err == cadvisorfs.ErrNoSuchDevice ||
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/stats/cri_stats_provider.go:453]: nit: should this also be the `errors.Is(` instead of equal?

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 3]
```diff
@@ -449,7 +450,9 @@ func (p *criStatsProvider) getFsInfo(fsID *runtimeapi.FilesystemIdentifier) *cad
...
+			errors.Is(err, cadvisorfs.ErrDeviceNotInPartitionsMap) ||
+			errors.Is(err, cadvisormemory.ErrDataNotFound) {
 			klog.V(2).InfoS(msg, "mountpoint", mountpoint, "err", err)
 		} else {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/stats/cri_stats_provider.go:457]: not to this PR. If this is used by GC, we will return no error in this case. So GC will assume 0 capacity and will fail with the message that there is a zero capacity instead of the error that we can return from here. Would it make sense to bubble this error up?

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 2 above)
Comment (saschagrunert) [reply pkg/kubelet/stats/cri_stats_provider.go:453]: Yep this should work, changed as suggested :+1:

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 3 above)
Comment (saschagrunert) [reply pkg/kubelet/stats/cri_stats_provider.go:457]: Hm, I can follow-up on this in another PR. I think this would require more intense testing.

**Comment by pacoxu** [comment]
/kind bug
it seems to be a bug of log level.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

@mrunalp can you please look if there are any implications of this.

**Review by marquiz — COMMENTED** [review]
lgtm

/assign @mrunalp

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 3 above)
Comment (dims) [reply pkg/kubelet/stats/cri_stats_provider.go:457]: ack on another follow up sascha. let me land this one
