### PR TITLE
Skip unused volumes in VolumeManager

### LINKED ISSUE #76044: Block PV may be mounted if kubelet feature gate disabled
@msau42 you may remember you had a concern that if we made BlockVolume default in 1.13 there could be issues with version skewed clusters where kubelets with the feature gate still off could format block volumes if a pod was started/restarted, potentially deleting data that was there. (see https://github.com/kubernetes/kubernetes/pull/65829#issuecomment-432378975). I concluded it wasn't possible but I'm convinced now that's wrong.

It's true that kubelet won't mount `volumeDevices` volumes into the pod, which is what the downgrade test I added checked, but the issue is:
- If the feature gate is off kubelet will add everything in spec.volumes to desired state of world* regardless of whether it is in volumeDevices/volumeMounts/neither. This means it will call MountVolume on a block volume! https://github.com/kubernetes/kubernetes/blob/b1829dff0b2d001ef3c70dffc844ad4cc852b1c1/pkg/volume/util/operationexecutor/operation_executor.go#L726

Only if the feature gate is on will kubelet check spec.volumes against volumeMounts/volumeDevices. It will add every volume in spec.volumes desired state of world* unless either a) it is a BlockVolume and present in volumeMounts or b) it is a Filesystem volume and present in volumeDevices, i.e. there is a mismatch. So it will still mount/map things even if there is no respective volumeMount/volumeDevice but it will error if there is a mismatch.

TODO:
- Update the downgrade test to not only check that nothing is mounted in the pod but also that nothing is mounted to the node at all, i.e. to the pod volume directory under /var/lib/kubelet (how to do that is TBD)

- Whether the feature gate is on/off, don't add volumes desired state of world* that are not in any volumeDevices/volumeMounts at all. So if the feature gate is off, kubelet won't add any block volumes in volume.spec because it won't check volumeDevices and the block volume won't be present in volumeMounts. This is what I thought happened. It should happen anyway because what's the point of mounting a volume if it is not going to be consumed by the pod?

~- Add a safeguard to MountVolume even if feature gate is off. I've heard feature gate off is supposed to mean 'don't run any code related to the feature' but I think an exception to read the VolumeMode field would be okay here?~ not reliable, pod may not have field at all

The fix should be cherry-picked to 1.11 & 1.12

### PR DESCRIPTION
**Pull request by jsafrane**
DesiredStateOfWorldPopulator should skip a volume that is not used in any pod. "Used" means either mounted (via volumeMounts) or used as raw block device (via volumeDevices) in a container in the pod.

Especially when block feature is disabled, a block volume must not get into DesiredStateOfWorld, because it would be formatted and mounted there, potentially overwriting any existing raw block data.

/kind bug
Fixes #76044

**Does this PR introduce a user-facing change?**:

```release-note
Volumes specified in a pod but not used in it are no longer unnecessarily formatted, mounted and reported in `node.status.volumesInUse`.
```

**Change of Kubernetes behavior**
Previously, all volumes were reported in `node.status.volumesInUse` and they were mounted / mapped as raw block devices in kubelet. With this PR, only the volumes that are actually used will be reported there and mounted/mapped. In most cases this won't make a difference (why would anyone put a volume to a pod and then not use it in any container?)

cc: @wongma7 @msau42 @bertinatto

### CODE REVIEW

**Comment by wongma7** [comment]
My old attempt to fix this looks extremely convoluted... What happens in kubelet-side WaitForAttachAndMount since it also reads spec.volumes? https://github.com/kubernetes/kubernetes/blob/b409073e99695ea35642a8194b9285ac12fd0cf8/pkg/kubelet/volumemanager/volume_manager.go#L440

**Comment by mattjmcnaughton** [comment]
I believe that the `pull-kubernetes-bazel-test` failure is legit:

```
 --- FAIL: TestGetMountedVolumesForPodAndGetVolumesInUse (123.00s)
    volume_manager_test.go:80: Expected success: unmounted volumes=[vol1], unattached volumes=[vol1]: timed out waiting for the condition 
```

My guess is that the other failures are flake... retesting them now to verify.

/test pull-kubernetes-integration
/test pull-kubernetes-kubemark-e2e-gce-big
/test pull-kubernetes-kubemark-e2e-gce-csi-serial

**Comment by wongma7** [comment]
Yes, test failure is legit, @jsafrane volumemanager needs some kind of fix as well since it gets list of volumes to wait for from spec.volumes instead of desired state. I'm sure you can fix it in a nicer way than I did.

**Comment by jsafrane** [comment]
> volumemanager needs some kind of fix as well since it gets list of volumes to wait for from spec.volumes instead of desired state. I'm sure you can fix it in a nicer way than I did.

You're right, I reworked `getExpectedVolumes` a bit. I used the simplest solution I could think of, not sure it's nicer.

In addition, I moved most of the code to `processPodVolumes()`, the code got a bit cleaner, but then  I needed to pass fake `BlockVolumePathHandler` to `NewVolumeManager` for unit tests, so the PR grew a lot...

/hold
* Missing e2e test with unused volume
* Squash the commits

**Comment by jsafrane** [comment]
@wongma7, can you please take a look at the current status? I'll squash the commits if this is the way to go.

I could not find any elegant way how to e2e test this. From storage test I can't get the global mount directory or name to check in `node.status.volumesInUse` easily. I *could* compare `volumesInUse` before and after a test pod was created, but that 1) would imply `[Serial]`, 2) it's quite ugly and 3) I am not sure it would work for all plugins. Any ideas?

**Comment by wongma7** [comment]
IMO it doesn't need to work for all plugins. Maybe just gcepd, e.g. https://github.com/kubernetes/kubernetes/blob/1addcf471519dde12667832980201785f6c2628a/test/e2e/storage/pd.go#L616 .

Initially I was thinking to ssh into the node and parse the mounts. Then you could e.g. make sure that the test pod UID has 0 mounts.

File: pkg/kubelet/volumemanager/volume_manager.go [hunk 1]
```diff
@@ -435,13 +438,24 @@ func filterUnmountedVolumes(mountedVolumes sets.String, expectedVolumes []string
 // getExpectedVolumes returns a list of volumes that must be mounted in order to
 // consider the volume setup step for this pod satisfied.
 func getExpectedVolumes(pod *v1.Pod) []string {
-	expectedVolumes := []string{}
+	expectedVolumes := sets.NewString()
 
-	for _, podVolume := range pod.Spec.Volumes {
-		expectedVolumes = append(expectedVolumes, podVolume.Name)
+	for _, container := range pod.Spec.Containers {
```
Comment (wongma7) [inline pkg/kubelet/volumemanager/volume_manager.go]: what about initContainers?

File: pkg/kubelet/volumemanager/volume_manager_test.go [hunk 2]
```diff
@@ -51,45 +54,103 @@ const (
...
+			disableBlockFeature: true,
+			expectMount:         false,
+			expectError:         false,
+		},
+		{
+			name:        "mismatched volume",
+			pvMode:      v1.PersistentVolumeBlock,
+			podMode:     v1.PersistentVolumeFilesystem,
+			expectMount: false,
+			expectError: true,
```
Comment (wongma7) [inline pkg/kubelet/volumemanager/volume_manager_test.go]: where does the error come from, is it a timeout or won't `expectedVolumes` have len 0?

File: pkg/kubelet/volumemanager/volume_manager.go (hunk 1 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager.go]: Good catch!

I copied the code from VolumeManager and it observes only `.containers`, not `.initContainers`. Filed #81343. I think the best would be to fix `makeVolumeMap` in #81343 first (to have a small patch), backport it everywhere and then move it to `pkg/volume/utils` that will be used also here.

Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager.go]: Wrote too early, the issue is reproducible only in this PR.

I extracted `GetPodVolumeNames` and used it consistently in VolumeManager and DSWP.

File: pkg/kubelet/volumemanager/volume_manager_test.go (hunk 2 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager_test.go]: It's not timeout, DSWP has stored error into DSW and `WaitForAttachAndMount` asynchronously picked it up within ~`podAttachAndMountRetryInterval` (300ms)

**Comment by jsafrane** [comment]
> Initially I was thinking to ssh into the node and parse the mounts. Then you could e.g. make sure that the test pod UID has 0 (non secret/token etc.)* mounts.

Ha, we mount unused volumes even to pod directory. I can test that.

**Comment by jsafrane** [comment]
Added e2e test. Now it should be complete.

**Comment by jsafrane** [comment]
e2e test added, commits squashed a bit
/hold cancel

File: pkg/volume/util/util.go [hunk 3]
```diff
@@ -548,3 +548,31 @@ func IsLocalEphemeralVolume(volume v1.Volume) bool {
...
 		volume.ConfigMap != nil || volume.DownwardAPI != nil
 }
+
+// GetPodVolumeNames returns names of volumes that are used in a pod,
+// either as filesystem mount or raw block device.
+func GetPodVolumeNames(pod *v1.Pod) (mounts sets.String, devices sets.String) {
+	mounts = sets.NewString()
+	devices = sets.NewString()
+
+	addContainerVolumes(pod.Spec.Containers, mounts, devices)
```
Comment (msau42) [inline pkg/volume/util/util.go]: This may need to be updated again after https://github.com/kubernetes/kubernetes/pull/59484

**Comment by wongma7** [comment]
/lgtm
beautiful!

**Comment by jsafrane** [comment]
/assign @tallclair @derekwaynecarr 
for approval from node point of view

Note that there is a small behavior change - before this PR, kubelet mounted / mapped as raw block everything that was in `pod.spec.volumes`, now it mounts / maps only things that are in `pod.spec.containers[*].volumeMounts` / `volumeDevices`.

**Comment by derekwaynecarr** [comment]
kubelet changes lgtm.

/lgtm
/approve
