### PR TITLE
AllocateOrOccupyCIDR returs quickly

### LINKED ISSUE #26511: Node controller can evict healthy pods in large clusters few minutes after startup (failing load.go e2e test)
There were a couple of flakes, that finished with the error like this one:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:182 creating rc
load-small-rc-4196 Expected error: <*errors.errorString | 0xc8217c0eb0>: { s: "Number of reported pods
for load-small-rc-4196 changed: 4 vs 5", } Number of reported pods for load-small-rc-4196 changed: 4 vs
5 not to have occurred
```

This particular error come from:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1183/

### PR DESCRIPTION
**Pull request by gmarek**
Fix #26511.

AllocateOrOccupy is called before adding a Node to NCs cache. It turns out that sending an update to API server can take too long which will make NC think that given Node does not exist and all Pods from it will be removed.

The fix is to move the long part of the call (updating NodeSpec) to a separate go-routine. To prevent overloading the server and huge number of retries we limit the number of concurrent Update calls.

cc @zmerlynn @davidopp

### CODE REVIEW

File: pkg/controller/node/nodecontroller.go [hunk 1]
```diff
@@ -340,6 +351,24 @@ func (nc *NodeController) Run(period time.Duration) {
...
 	go wait.Until(nc.cleanupOrphanedPods, 30*time.Second, wait.NeverStop)
+
+	for i := 0; i < cidrUpdateWorkers; i++ {
+		go func(stopChan <-chan struct{}) {
+			for {
+				select {
+				case workItem, ok := <-nc.nodeCIDRUpdateChannel:
+					if !ok {
+						glog.Warning("NodeCIDRUpdateChannel read returned false.")
+						break
```
Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: return

File: pkg/controller/node/nodecontroller.go [hunk 2]
```diff
@@ -340,6 +351,24 @@ func (nc *NodeController) Run(period time.Duration) {
...
+					}
+					nc.updateCIDRAllocation(workItem)
+				case <-stopChan:
+					glog.Warning("StopChannel is closed.")
```
Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: This shouldn't be warning - if someone is explicitly closing stopChan, we shouldn't log it as warning.

File: pkg/controller/node/nodecontroller.go [hunk 3]
```diff
@@ -352,11 +381,34 @@ func (nc *NodeController) filterOutServiceRange() {
...
 }
 
+func (nc *NodeController) updateCIDRAllocation(data nodeAndCIDR) {
+	var err error
+	var node *api.Node
+	for rep := 0; rep < podCIDRUpdateRetry; rep++ {
+		node, err = nc.kubeClient.Core().Nodes().Get(data.nodeName)
+		if err != nil {
+			glog.Errorf("Failed while getting node %v to retry updating Node.Spec.PodCIDR: %v", data.nodeName, err)
+			break
```
Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: If we are retrying anyway, I would change to "continue" here.

Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: This can potentially be some transient error.

**Comment by wojtek-t** [comment]
Few minor comments. Generally LGTM

File: pkg/controller/node/nodecontroller.go (hunk 1 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller.go]: Done.

File: pkg/controller/node/nodecontroller.go (hunk 2 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller.go]: Done.

File: pkg/controller/node/nodecontroller.go (hunk 3 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller.go]: Done.

**Comment by wojtek-t** [comment]
LGTM - thanks!
