### PR TITLE
aws: fixes ELB creation with multiple subnets per AZ

### LINKED ISSUE #12381: AWS elb creation fails when there are multiple subnets in one AZ
I am trying to launch an ELB with kubernetes from cloudformation. I created the VPC, named it *kubernetes-vpc*, then,  I created the subnets.

I need the RDS instance for a CI environment, so finally, I launched the RDS instance and the RDS wizard, with my consent, created a new subnet in an availability zone used by another subnet inside *kubernetes-vpc*.

This is the error message I get when the controller manager tries to attach the instances to the ELB.

```
kube-controller-manager[2132]: E0806 02:44:42.322509    2132 servicecontroller.go:173]
Failed to process service delta.
Retrying: failed to create external load balancer for service default/mycustomservice:
InvalidConfigurationRequest: ELB cannot be attached to multiple subnets in the same AZ.
```

The docs should warn about creating multiple subnets in the same availability zone inside kubernetes-vpc or group the AZs before giving their names to the controller manager.

### PR DESCRIPTION
**Pull request by simonswine**
Only takes the first available subnet in a AZ, ignore other subnets
and log warning about this.

Removes AWS region comparison for subnet AZs. A VPC is only in a single
AWS region.

Fixes #12381

### CODE REVIEW

**Comment by simonswine** [comment]
Hi everyone,

as far as I can see it the issue here is nothing related to this PR. I see other PR with the same test failing:

> k8s.io/kubernetes/test/integration / integration / TestPersistentVolumeClaimBinder

Can you confirm that?

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -1590,6 +1590,37 @@ func (s *AWSCloud) createTags(request *ec2.CreateTagsInput) (*ec2.CreateTagsOutp
...
+	filters = s.addFilters(filters)
+	request.Filters = filters
+
+	subnets, err := s.ec2.DescribeSubnets(request)
+	if err != nil {
+		glog.Error("error describing subnets: ", err)
+		return nil, err
+	}
+
+	availabilityZones := make(map[string]bool)
```
Comment (brendandburns) [inline pkg/cloudprovider/providers/aws/aws.go]: please use `pkg/util/set/String` for string sets.

**Comment by brendandburns** [comment]
one minor nit.

**Comment by simonswine** [comment]
@brendandburns The az check is using the string sets package now. Sorry for the delay. You can blame Oktoberfest for that :laughing:

**Comment by brendandburns** [comment]
LGTM, thanks for the PR.
