### PR TITLE
Ensure /etc/hosts has a header always - Fix conformance test

### LINKED ISSUE #60938: Test fails in DIND enviroment - "KubeletManagedEtcHosts should test kubelet managed /etc/hosts file"
Please see the following job:
https://k8s-testgrid.appspot.com/sig-testing-misc#ci-kubernetes-local-e2e

Specifically output from one of the jobs:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-local-e2e/373#k8sio-kubeletmanagedetchosts-should-test-kubelet-managed-etchosts-file-conformance

This happens in our CI environment where we use a container to both start local-up-cluster and run e2e test (same container). 

The container started by the CI is already a managed one and hence has the "# Kubernetes-managed hosts file.\n". When we run the test, we just pick up the contents of that /etc/hosts when we launch containers that use HostNetwork. So when the e2e test looks into the nested container it finds the string and fails.

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

We need to be able to tell if an /etc/hosts in a container has been touched by kubernetes or not (whether we use the host network or not).

We have 2 scenarios where we copy /etc/hosts
- with host network (we just copy the /etc/hosts from node)
- without host network (create a fresh /etc/hosts from pod info)

We are having trouble figuring out whether a /etc/hosts in a
pod/container has been "fixed-up" or not. And whether we used
host network or a fresh /etc/hosts in the various ways we start
up the tests which are:

- VM/box against a remote cluster
- As a container inside the k8s cluster
- DIND scenario in CI where test runs inside a managed container

Please see previous mis-guided attempt to fix this problem at
ba20e63446815f8bcab4fc4c6e07eab2e2a9e121 In this commit we revert
the code from there as well.

So we should make sure:
- we always add a header if we touched the file
- we add slightly different headers so we can figure out if we used the
  host network or not.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60938

**Special notes for your reviewer**:
Also see
- https://github.com/kubernetes/kubernetes/pull/61405
- https://github.com/kubernetes/kubernetes/pull/60939
- https://github.com/kubernetes/kubernetes/issues/60938

**Release note**:

```release-note
Rework Kubelet set `/etc/hosts` behavior to fix conformance testability
```

### CODE REVIEW

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -356,6 +361,7 @@ func nodeHostsFileContent(hostsFilePath string, hostAliases []v1.HostAlias) ([]b
 	if err != nil {
 		return nil, err
 	}
+	hostsFileContent = append([]byte(managedHostsHeaderWithHostNetwork), hostsFileContent...)
```
Comment (liggitt) [inline pkg/kubelet/kubelet_pods.go]: it's a little confusing to prepend managedHostsHeaderWithHostNetwork this way... would read better if that was set first in the function and every change was an append (switching to the buffer.Write...() approach used in managedHostsFileContent would probably make sense)

File: test/e2e/common/kubelet_etc_hosts.go [hunk 2]
```diff
@@ -62,58 +62,39 @@ var _ = framework.KubeDescribe("KubeletManagedEtcHosts", func() {
...
-	assertManagedStatus(config, etcHostsPodName, true, "busybox-1")
-	assertManagedStatus(config, etcHostsPodName, true, "busybox-2")
+	assertManagedStatus(config, etcHostsPodName, true, "busybox-1", true)
+	assertManagedStatus(config, etcHostsPodName, true, "busybox-2", true)
 
-	By("Verifying /etc/hosts of container is not kubelet-managed since container specifies /etc/hosts mount")
-	assertManagedStatus(config, etcHostsPodName, false, "busybox-3")
+	// Check if local /etc/hosts has a managed by kubernetes header
+	headerPresent := false
+	if data, err := ioutil.ReadFile("/etc/hosts"); err == nil {
```
Comment (liggitt) [inline test/e2e/common/kubelet_etc_hosts.go]: this only works if the test is run on the same machine as the one containing this file, right? it seems like a better test would be to mount /etc/hosts in two locations in the pod (e.g. /etc/hosts and /etc-hosts-test) and make sure they were equal as seen by the pod (e.g. nothing special was done to the /etc/hosts mount)

File: test/e2e/common/kubelet_etc_hosts.go [hunk 3]
```diff
@@ -62,58 +62,39 @@ var _ = framework.KubeDescribe("KubeletManagedEtcHosts", func() {
...
+		headerPresent = strings.HasPrefix(string(data), etcHostsKubernetesManaged)
+	}
+
+	if !headerPresent {
```
Comment (liggitt) [inline test/e2e/common/kubelet_etc_hosts.go]: I don't think making this conditional on the content of a local file works

**Comment by dims** [comment]
@liggitt this is ready now. PTAL

**Comment by liggitt** [comment]
/lgtm
Has this been tested on windows or is the test skipped?

**Comment by dims** [comment]
@m1093782566 @thockin Can you please take a look? Fixing this will give us a all-green conformance ci/pull jobs using local-up-cluster.sh (https://k8s-testgrid.appspot.com/sig-testing-misc#ci-kubernetes-local-e2e)

File: test/e2e/common/kubelet_etc_hosts.go [hunk 4]
```diff
@@ -163,8 +140,8 @@ func assertManagedStatus(
 	}
 }
 
-func (config *KubeletManagedHostConfig) getEtcHostsContent(podName, containerName string) string {
-	return config.f.ExecCommandInContainer(podName, containerName, "cat", "/etc/hosts")
+func (config *KubeletManagedHostConfig) getFileContents(podName, containerName string, path string) string {
```
Comment (dixudx) [inline test/e2e/common/kubelet_etc_hosts.go]: `containerName` and `path` are both `string`. No need to have an extra type declaration.

File: test/e2e/common/kubelet_etc_hosts.go [hunk 5]
```diff
@@ -137,16 +106,24 @@ func assertManagedStatus(
 	etcHostsContent := ""
 
 	for startTime := time.Now(); time.Since(startTime) < retryTimeout; {
-		etcHostsContent = config.getEtcHostsContent(podName, name)
-		isManaged := strings.Contains(etcHostsContent, etcHostsPartialContent)
-
-		if expectedIsManaged == isManaged {
-			return
+		etcHostsContent = config.getFileContents(podName, name, "/etc/hosts")
+		etcHostsOriginalContent := config.getFileContents(podName, name, "/etc/hosts-original")
```
Comment (dixudx) [inline test/e2e/common/kubelet_etc_hosts.go]: Shall we declare these two filepath as const variables for better maintenance?

**Review by dixudx — COMMENTED** [review]
Two nits. Others lgtm.

File: test/e2e/common/kubelet_etc_hosts.go (hunk 4 above)
Comment (dims) [reply test/e2e/common/kubelet_etc_hosts.go]: Done

File: test/e2e/common/kubelet_etc_hosts.go (hunk 5 above)
Comment (dims) [reply test/e2e/common/kubelet_etc_hosts.go]: Done

**Comment by dims** [comment]
@Random-Liu @dchen1107 @derekwaynecarr @tallclair @vishh @yujuhong @kubernetes/sig-node-pr-reviews Can someone in sig-node please approve?
