### PR TITLE
Replaces path.Operation with filepath.Operation

### LINKED ISSUE #110600: path functions not working as intended on Windows
### What happened?

The ``path`` module has a few different functions: Clean, Split, Join, Ext, Dir, Base, IsAbs. These functions do not take into account the OS-specific path separator, meaning that they won't behave as intended on Windows. The ``path`` should not be used for file paths.

For example, Dir is supposed to return all but the last element of the path. For the path ``C:\some\dir\somewhere``, it is supposed to return ``C:\some\dir\``, however, it returns ``.``.

### What did you expect to happen?

Instead of these functions, the ones in ``filepath`` should be used instead.

### How can we reproduce it (as minimally and precisely as possible)?

Example:

```
package main

import (
	"fmt"
	"path"
	"path/filepath"
)

func main() {
	fmt.Println("Comparing path.Operation\t to\t filepath.Operation on Windows.\n")

	// Clean should remove duplicate slashes and evaluate the ..
	folder := `C:\\some\dir\\\\somewhere\\..\`
	fmt.Printf("Clean: %s \t\t %s\n", path.Clean(folder), filepath.Clean(folder))

	// Split should give us the base folder and the file.
	file := `C:\\some\dir\\somewhere.txt`
	dir1, f1 := path.Split(file)
	dir2, f2 := filepath.Split(file)
	fmt.Printf("Split: %s, %s \t\t %s, %s\n", dir1, f1, dir2, f2)

	// Join should use the oS-specific path separator.
	fmt.Printf("Join: %s \t\t %s\n", path.Join(file, "foo"), filepath.Join(file, "foo"))

	// Ext should give us the file extension.
	fmt.Printf("Ext: %s \t\t %s\n", path.Ext(file), filepath.Ext(file))

	// Base should return the last element of the path.
	fmt.Printf("Base: %s \t\t %s\n", path.Base(file), filepath.Base(file))

	// Dir should return all but the last element of the path.
	fmt.Printf("Dir: %s \t\t %s\n", path.Dir(file), filepath.Dir(file))

	// IsAbs should return True in this case, as it is an absolute path.
	fmt.Printf("IsAbs: %t \t\t %t\n", path.IsAbs(file), filepath.IsAbs(file))
}
```

```
PS C:\> go version
go version go1.18.2 windows/amd64

PS C:\> go run .\pather_windows.go
Comparing path.Operation         to      filepath.Operation on Windows.

Clean: C:\\some\dir\\\\somewhere\\..\            C:\some\dir
Split: , C:\\some\dir\\somewhere.txt             C:\\some\dir\\, somewhere.txt
Join: C:\\some\dir\\somewhere.txt/foo            C:\some\dir\somewhere.txt\foo
Ext: .txt                .txt
Base: C:\\some\dir\\somewhere.txt                somewhere.txt
Dir: .           C:\\some\dir\
IsAbs: false             true
```

### Anything else we need to know?

/sig windows

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug

/sig windows
/priority important-soon
/milestone v1.25

#### What this PR does / why we need it:

The path module has a few different functions: Clean, Split, Join, Ext, Dir, Base, IsAbs. These functions do not take into account the OS-specific path separator, meaning that they won't behave as intended on Windows.

For example, Dir is supposed to return all but the last element of the path. For the path ``C:\some\dir\somewhere``, it is supposed to return ``C:\some\dir\``, however, it returns ``.``.

Instead of these functions, the ones in filepath should be used instead.

#### Which issue(s) this PR fixes:

Fixes #110600

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -954,7 +953,7 @@ func validateNFSVolumeSource(nfs *core.NFSVolumeSource, fldPath *field.Path) fie
 	if len(nfs.Path) == 0 {
 		allErrs = append(allErrs, field.Required(fldPath.Child("path"), ""))
 	}
-	if !path.IsAbs(nfs.Path) {
+	if !filepath.IsAbs(nfs.Path) {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:956]: /hold

all of the API validation changes should not use filepath... we don't want API validation to depend on the OS the server is running on

File: staging/src/k8s.io/kubectl/pkg/util/util.go [hunk 2]
```diff
@@ -62,7 +61,7 @@ func ParseFileSource(source string) (keyName, filePath string, err error) {
 	numSeparators := strings.Count(source, "=")
 	switch {
 	case numSeparators == 0:
-		return path.Base(filepath.ToSlash(source)), source, nil
```
Comment (liggitt) [inline staging/src/k8s.io/kubectl/pkg/util/util.go:65]: revert this... filepath.ToSlash ensures the path is using /, so path.Base works properly

File: staging/src/k8s.io/kubectl/pkg/cmd/cp/filespec.go [hunk 3]
```diff
@@ -98,19 +97,19 @@ func (p remotePath) String() string {
...
 
 func (p remotePath) Clean() remotePath {
-	return newRemotePath(path.Clean(p.file))
+	return newRemotePath(filepath.Clean(p.file))
 }
 
 func (p remotePath) Join(elem pathSpec) remotePath {
-	return newRemotePath(path.Join(p.file, elem.String()))
+	return newRemotePath(filepath.Join(p.file, elem.String()))
 }
```
Comment (liggitt) [inline staging/src/k8s.io/kubectl/pkg/cmd/cp/filespec.go:113]: cc @soltysh 

I'm pretty sure this change is incorrect... xref https://github.com/kubernetes/kubernetes/pull/94165 ... this is constructing remote paths to be interpreted inside a container, right? if so, the OS kubectl is running on isn't really relevant?

File: pkg/volume/util/atomic_writer.go [hunk 4]
```diff
@@ -256,7 +255,7 @@ func validatePath(targetPath string) error {
 	if targetPath == "" {
 		return fmt.Errorf("invalid path: must not be empty: %q", targetPath)
 	}
-	if path.IsAbs(targetPath) {
+	if filepath.IsAbs(targetPath) {
```
Comment (liggitt) [inline pkg/volume/util/atomic_writer.go:258]: does this break on windows when presented with paths specified in the API, which will always started with `/`?

File: staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go [hunk 5]
```diff
@@ -137,7 +137,7 @@ func newETCD3HealthCheck(c storagebackend.Config, stopCh <-chan struct{}) (func(
 		ctx, cancel := context.WithTimeout(context.Background(), healthcheckTimeout)
 		defer cancel()
 		// See https://github.com/etcd-io/etcd/blob/c57f8b3af865d1b531b979889c602ba14377420e/etcdctl/ctlv3/command/ep_command.go#L118
-		_, err := client.Get(ctx, path.Join("/", c.Prefix, "health"))
+		_, err := client.Get(ctx, filepath.Join("/", c.Prefix, "health"))
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go:140]: revert this, this is not a filepath, but a keypath within etcd

File: pkg/routes/logs.go [hunk 6]
```diff
@@ -43,7 +43,7 @@ func (l Logs) Install(c *restful.Container) {
 
 func logFileHandler(req *restful.Request, resp *restful.Response) {
 	logdir := "/var/log"
-	actual := path.Join(logdir, req.PathParameter("logpath"))
+	actual := filepath.Join(logdir, req.PathParameter("logpath"))
```
Comment (liggitt) [inline pkg/routes/logs.go:46]: does this do the right thing on windows when joining a base path of `/var/log`?

File: pkg/kubelet/custommetrics/custom_metrics.go [hunk 7]
```diff
@@ -38,9 +38,9 @@ func GetCAdvisorCustomMetricsDefinitionPath(container *v1.Container) (*string, e
 	// mounted as a volume. Custom Metrics definition is expected to be in "definition.json".
 	if container.VolumeMounts != nil {
 		for _, volumeMount := range container.VolumeMounts {
-			if path.Clean(volumeMount.MountPath) == path.Clean(CustomMetricsDefinitionDir) {
+			if filepath.Clean(volumeMount.MountPath) == filepath.Clean(CustomMetricsDefinitionDir) {
```
Comment (liggitt) [inline pkg/kubelet/custommetrics/custom_metrics.go:41]: does this do the right thing when presented with `/`-delimited mount paths from API data?

File: staging/src/k8s.io/code-generator/cmd/applyconfiguration-gen/args/args.go [hunk 8]
```diff
@@ -57,7 +57,7 @@ func NewDefaults() (*args.GeneratorArgs, *CustomArgs) {
 	genericArgs.CustomArgs = customArgs
 
 	if pkg := codegenutil.CurrentPackage(); len(pkg) != 0 {
-		genericArgs.OutputPackagePath = path.Join(pkg, "pkg/client/applyconfigurations")
+		genericArgs.OutputPackagePath = filepath.Join(pkg, "pkg/client/applyconfigurations")
```
Comment (liggitt) [inline staging/src/k8s.io/code-generator/cmd/applyconfiguration-gen/args/args.go:60]: a lot of the changes in the files in code-generator are computing packages, so should still use path, not filepath

**Comment by markyjackson-taulia** [comment]
Hi @claudiubelu My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

File: pkg/kubelet/cm/cgroup_manager_linux.go [hunk 9]
```diff
@@ -79,7 +78,7 @@ func unescapeSystemdCgroupName(part string) string {
 // For example, the name {"kubepods", "burstable", "pod1234-abcd-5678-efgh"} becomes
 // "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1234_abcd_5678_efgh.slice"
 // This function always expands the systemd name into the cgroupfs form. If only
-// the last part is needed, use path.Base(...) on it to discard the rest.
+// the last part is needed, use filepath.Base(...) on it to discard the rest.
```
Comment (fromanirh) [inline pkg/kubelet/cm/cgroup_manager_linux.go:81]: I agree with the general intent of the patch, but I wonder if we should use OS-independent functions in a OS-dependent source code.

File: pkg/kubelet/cm/cgroup_manager_linux_test.go [hunk 10]
```diff
@@ -88,7 +88,7 @@ func TestCgroupNameToSystemdBasename(t *testing.T) {
 		},
 	}
 	for _, testCase := range testCases {
-		if actual := path.Base(testCase.input.ToSystemd()); actual != testCase.expected {
+		if actual := filepath.Base(testCase.input.ToSystemd()); actual != testCase.expected {
```
Comment (fromanirh) [inline pkg/kubelet/cm/cgroup_manager_linux_test.go:91]: same, AFAIK we don't nor we will have cgroups on systems != linux

**Comment by markyjackson-taulia** [comment]
Hi @claudiubelu My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

File: pkg/kubelet/cm/cgroup_manager_linux.go (hunk 9 above)
Comment (claudiubelu) [reply pkg/kubelet/cm/cgroup_manager_linux.go:81]: Fair enough, will ignore these for the Linux only code.

File: pkg/kubelet/cm/cgroup_manager_linux_test.go (hunk 10 above)
Comment (claudiubelu) [reply pkg/kubelet/cm/cgroup_manager_linux_test.go:91]: Done

File: staging/src/k8s.io/kubectl/pkg/util/util.go (hunk 2 above)
Comment (claudiubelu) [reply staging/src/k8s.io/kubectl/pkg/util/util.go:65]: Done

File: pkg/kubelet/custommetrics/custom_metrics.go (hunk 7 above)
Comment (claudiubelu) [reply pkg/kubelet/custommetrics/custom_metrics.go:41]: Reverted until I have more concrete information on this.

File: staging/src/k8s.io/kubectl/pkg/cmd/cp/filespec.go (hunk 3 above)
Comment (claudiubelu) [reply staging/src/k8s.io/kubectl/pkg/cmd/cp/filespec.go:113]: Indeed, ``newRemotePath`` will replace ``\`` to ``/`` anyways.

**Comment by claudiubelu** [comment]
> Hi @claudiubelu My name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Just checking in to see if this is still on track for k8s 1.25?

Yes.

**Comment by dims** [comment]
way past test freeze
/milestone clear

**Comment by aramase** [comment]
> /assign @andrewsykim, dchen1107, sttts, xing-yang

/assign andrewsykim dchen1107 sttts xing-yang

**Comment by tallclair** [comment]
It's difficult to review (and get approval) on such a large PR. I'd suggest splitting this into several smaller PRs. From a quick read of the file list, a kubelet PR and storage PR might be a sensible breakdown.

File: pkg/volume/awsebs/attacher.go [hunk 11]
```diff
@@ -277,7 +276,7 @@ func (plugin *awsElasticBlockStorePlugin) NewDeviceUnmounter() (volume.DeviceUnm
 }
 
 func (detacher *awsElasticBlockStoreDetacher) Detach(volumeName string, nodeName types.NodeName) error {
-	volumeID := aws.KubernetesVolumeID(path.Base(volumeName))
+	volumeID := aws.KubernetesVolumeID(filepath.Base(volumeName))
```
[the remark this answers is not in the document]
Comment (claudiubelu) [reply pkg/volume/awsebs/attacher.go:279]: Looking at the unit tests for this, ``Detach`` is called with a mount path: https://github.com/kubernetes/kubernetes/blob/a497c56c33aca254e69513fcd46c0c76c8fadcab/pkg/volume/awsebs/attacher_test.go#L116 .

Looking at ``filepath.Base``, this should be a safe change in the first place: https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/path/filepath/path.go;l=564 . Basically, it will strip the trailing slashes, strip the volume name (for Windows), and slice the base after the right-most slash (determined by ``os.IsPathSeparator``, which on Linux it's going to check for ``/``, while for Windows it's going to check for both ``/`` and ``\``). So, for Linux, this is a noop change, while enabling Windows paths to work here as well. The base can still be obtained on Windows even if it's an URL:

```
package main

import (
    "fmt"
    "path/filepath"
)

func main() {
    url := "http://foo.foo/something&other"
    fmt.Printf("Url: %s, Base: %s\n", url, filepath.Base(url))
}
```

Result:

```
PS C:\workspace> go run pather.go
Url: http://foo.foo/something&other, Base: something&other
```

File: pkg/volume/gcepd/attacher.go [hunk 12]
```diff
@@ -365,7 +364,7 @@ func (plugin *gcePersistentDiskPlugin) NewDeviceUnmounter() (volume.DeviceUnmoun
 // Callers are responsible for thread safety between concurrent attach and detach
 // operations.
 func (detacher *gcePersistentDiskDetacher) Detach(volumeName string, nodeName types.NodeName) error {
-	pdName := path.Base(volumeName)
+	pdName := filepath.Base(volumeName)
```
[the remark this answers is not in the document]
Comment (claudiubelu) [reply pkg/volume/gcepd/attacher.go:367]: In the tests, this is called with ``diskName := "disk"``. Not sure if it's a file path or URL.

**Comment by claudiubelu** [comment]
> It's difficult to review (and get approval) on such a large PR. I'd suggest splitting this into several smaller PRs. From a quick read of the file list, a kubelet PR and storage PR might be a sensible breakdown.

I've split this into 2 PRs, including this one, and: https://github.com/kubernetes/kubernetes/pull/113255 and https://github.com/kubernetes/kubernetes/pull/113257

File: pkg/security/apparmor/validate.go [hunk 13]
```diff
@@ -133,7 +133,7 @@ func getAppArmorFS() (string, error) {
 			continue
 		}
 		if fields[2] == "securityfs" {
-			appArmorFS := path.Join(fields[1], "apparmor")
+			appArmorFS := filepath.Join(fields[1], "apparmor")
```
Comment (liggitt) [inline pkg/security/apparmor/validate.go:136]: I was going to check if the returned path is used in ways that would make different slashes unsafe, but weirdly, it doesn't look like the returned path is used... cc @tallclair for general apparmor oversight

File: pkg/util/removeall/removeall_test.go [hunk 14]
```diff
@@ -236,11 +236,11 @@ func TestRemoveDirsOneFilesystem(t *testing.T) {
 		for _, item := range test.items {
 			if strings.HasSuffix(item, "/") {
 				item = strings.TrimRight(item, "/")
-				if err = os.Mkdir(path.Join(tmpDir, item), 0777); err != nil {
+				if err = os.Mkdir(filepath.Join(tmpDir, item), 0777); err != nil {
```
Comment (liggitt) [inline pkg/util/removeall/removeall_test.go:239]: the test items all use `/`... does filepath.Join translate that to `\` on windows or do we end up with mixed slashes?

File: pkg/volume/awsebs/attacher.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/volume/awsebs/attacher.go:279]: It's unclear to me whether that unit test is correct, and if volumeName is expected/allowed to be a file path

This function is called from https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/util/operationexecutor/operation_generator.go#L500

volumeName is set by one of:

1. https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/util/operationexecutor/operation_generator.go#L464-L465

    * the awsebs implementation of GetVolumeName pulls from the API field: https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/awsebs/aws_ebs.go#L77-L84 https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/awsebs/aws_ebs.go#L240-L247

    * The API field does not document its format, and is not validated: https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/staging/src/k8s.io/api/core/v1/types.go#L1123-L1126

2. https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/util/operationexecutor/operation_generator.go#L470-L473

    * this path requires SplitUniqueName requires VolumeName to be in the format `plugin_namespace/plugin/volume_name` https://github.com/kubernetes/kubernetes/blob/256ade5aa49aa96bbb6bc5fb78a6bdd518eebae4/pkg/volume/util/util.go#L381-L393

File: pkg/volume/util/util_windows.go [hunk 15]
```diff
@@ -0,0 +1,30 @@
...
+package util
+
+import (
+	"path/filepath"
+)
+
+func isAbs(path string) bool {
+	// on Windows, filepath.IsAbs will not return True for paths prefixed with a slash, even
+	// though they can be used as absolute paths (https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats).
+	return filepath.IsAbs(path) || (len(path) > 0 && (path[0] == '\\' || path[0] == '/'))
```
Comment (liggitt) [inline pkg/volume/util/util_windows.go:29]: why do we want to relax atomic writer to also permit leading `\` or drive letters for atomic writer on Windows? if `/`-prefixed paths work on windows (and according to this doc link, they do?) can we keep atomic writer consistently using `/`-prefixed paths? all the API-specified relative path mount points are required to be specified that way.

File: pkg/volume/util/hostutil/hostutil_windows.go [hunk 16]
```diff
@@ -68,7 +67,7 @@ func getDeviceNameFromMount(mounter mount.Interface, mountPath, pluginMountDir s
 		}
 	}
 
-	return path.Base(mountPath), nil
+	return filepath.Base(mountPath), nil
```
Comment (liggitt) [inline pkg/volume/util/hostutil/hostutil_windows.go:70]: does this split both on `/` and `\`?

File: pkg/volume/util/atomic_writer.go [hunk 17]
```diff
@@ -260,7 +259,7 @@ func validatePath(targetPath string) error {
 	if targetPath == "" {
 		return fmt.Errorf("invalid path: must not be empty: %q", targetPath)
 	}
-	if path.IsAbs(targetPath) {
+	if isAbs(targetPath) {
```
Comment (liggitt) [inline pkg/volume/util/atomic_writer.go:262]: see the question in the windows impl, I'm not sure why we want to relax this

File: pkg/security/apparmor/validate.go (hunk 13 above)
Comment (tallclair) [reply pkg/security/apparmor/validate.go:136]: apparmor is only used on linux, so this doesn't really matter here. But this is a file path, so this change here seems appropriate.

@liggitt I didn't understand your comment. This path `appArmorFS` is used in the following line to check whether the path exists.

Comment (tallclair) [reply pkg/security/apparmor/validate.go:136]: Ah, got it. Yeah, looks like the usage was removed in https://github.com/kubernetes/kubernetes/pull/97966.

This is still a proxy for whether AppArmor is enabled on the cluster, but we're checking `apparmor.IsEnabled()` directly, so I think the we can just remove this function entirely. :+1:

**Comment by sowmyav27** [comment]
@claudiubelu Hi, I am part of Bug Triage Shadow team for k8s 1.27 release. I wanted to confirm this PR is on track for 1.27 Release?

File: pkg/security/apparmor/validate.go (hunk 13 above)
Comment (SergeyKanzhelev) [reply pkg/security/apparmor/validate.go:136]: Filed "help wanted" issue: https://github.com/kubernetes/kubernetes/issues/115741

**Comment by sowmyav27** [comment]
@claudiubelu @xing-yang @tallclair @andrewsykim @jingxu97 @dchen1107 @mauriciopoppe , I am part of Bug Triage Shadow team for k8s 1.27 release. Can you please confirm if this PR is on track for 1.27 Release?

**Comment by bart0sh** [comment]
@claudiubelu please, rebase this PR, thanks.

File: pkg/volume/awsebs/attacher.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (claudiubelu) [reply pkg/volume/awsebs/attacher.go:278]: No longer applies, ``pkg/volume/awsebs`` no longer exists.

File: pkg/volume/gcepd/attacher.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (claudiubelu) [reply pkg/volume/gcepd/attacher.go:367]: Nonetheless, using ``filepath.Base`` should be fine.

- for Linux, ``path.Base`` and ``filepath.Base`` will work the same: for ``/any/path/to/file`` will return ``file``.
- for Windows, ``path.Base`` can only handle the ``/any/path/to/file`` case (returning ``file``), while ``filepath.Base`` will handle both ``/any/path/to/file`` and ``:\\any\\path\\to\\file`` cases (returning ``file``). This is due to how ``filepath.Base`` works (https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/path/filepath/path.go;l=615), relying on [IsPathSeparator](https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/os/path_unix.go;drc=70f98a251efdbfd619c4ff466a43da299ad04752;l=15) to check whether a character is a ``/`` or a ``\``.

File: pkg/volume/util/atomic_writer.go (hunk 17 above)
Comment (claudiubelu) [reply pkg/volume/util/atomic_writer.go:262]: Removed, will treat this scenario in a separate PR: https://github.com/kubernetes/kubernetes/pull/112566

File: pkg/volume/util/util_windows.go (hunk 15 above)
Comment (claudiubelu) [reply pkg/volume/util/util_windows.go:29]: ditto.

File: pkg/routes/logs.go (hunk 6 above)
Comment (liggitt) [reply pkg/routes/logs.go:45]: a couple more questions:
* does http.ServeFile handle backslashed paths correctly?
* what does filepath.Join do when logdir and req.PathParameter("logpath") contain a mix of forward-slash and backslash separators?

**Comment by hailkomputer** [comment]
Hello! Bug triage team shadow here. I want to check the status. The code freeze is starting [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496) (about three weeks from now), and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.28, is it still planned for this release?

**Comment by claudiubelu** [comment]
> Hi! Bug triage team shadow here.
> 
> We are currently in Week 9 of the v1.28 release cycle, and the code freeze is happening next week (Week 10) at [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496)
> 
> Please ensure all necessary contributions are made before the deadline if the PR still targets v1.28.
> 
> Let me know if you need any assistance.

Simply waiting for reviews / approval at this point.

**Comment by aravindhp** [comment]
@kubernetes/sig-storage-pr-reviews please review when you get the chance. Thanks!

**Comment by jsafrane** [comment]
/approve
`pkg/util` and `pkg/volume` changes

**Comment by aravindhp** [comment]
@deads2k please review when you get the chance. sig-windows is hoping to have this merged for 1.28.

File: pkg/routes/logs.go (hunk 6 above)
Comment (aravindhp) [reply pkg/routes/logs.go:45]: @claudiubelu please address this

**Comment by bart0sh** [comment]
@claudiubelu The PR looks good to me. Please, address [this comment](https://github.com/kubernetes/kubernetes/pull/110601/files#r1161694458) and we're good to go.

File: pkg/routes/logs.go (hunk 6 above)
Comment (claudiubelu) [reply pkg/routes/logs.go:45]: Looking through ``http.ServeFile``'s code, it seems that there are some explicit checks for `/`, including for `/index.html`. Removed this change.

**Comment by jsafrane** [comment]
/hold cancel

I'm removing @liggitt's hold, this PR was updated not to change validation.go
