### PR TITLE
Differentiate build process for non-amd platforms

### LINKED ISSUE #81920: image tags is not correctly defined on arm paltform
**What happened**:
some of base images support multi-arch,  if no platform specified, the image pulled will actually reflect where the operation is performed, current implementation always assume the default platform is amd64 which make the tags is not correctly defined.

for example,

on arm64 platform, here is what I got after build the image of ipc-utils, 
```
# docker inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
...
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 9732491,
        "VirtualSize": 9732491,
        "GraphDriver": {
  ...
```

**What you expected to happen**:
tag should be defined correctly

**How to reproduce it (as minimally and precisely as possible)**:
on arm64 platform, 
```
cd /test/images.
make all WHAT=ipc-utils
docker image ls | grep ipc-utils
docker image inspect gcr.io/kubernetes-e2e-test-images/ipc-utils-amd64:1.0
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration: all arch except x86 
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #82775: reset `binfmt_misc` is needn't when build arm images on arm platform
**What happened**:
when building images on non-amd platform, arm64 for example, and the target image is arm64 too, the code still reset `binfmt_misc`.

**What you expected to happen**:
There is no need to reset anything, the shell code is purely for amd64 and haven't considered the non-amd platforms.

**How to reproduce it (as minimally and precisely as possible)**:
on any platform other than amd, 
cd  test/images
build all WHAT=echoserver (or any image under the dir)

when coming to image which is exactly the same as the build machine, following is seen from console
```
Building image for volume/iscsi ARCH: arm64...
/go/src/k8s.io/kubernetes/_tmp/test-images-build.E7S3Oc /go/src/k8s.io/kubernetes/test/images
Registering qemu-*-static binaries in the kernel
Setting /usr/bin/qemu-i386-static as binfmt interpreter for i386
sh: echo: I/O error
Setting /usr/bin/qemu-i386-static as binfmt interpreter for i486
sh: echo: I/O error
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32p
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
- reset `binfmt_misc` is needn't when the building platform is non-amd64 and the
target arch is the same as building platform

- non-amd64 platform doesn't supported cross-build well, and there is no binary of
`qemu-user-static` able to do that, and thus skip the cross-build on non-amd64
platform.

Here is what it looks like for apparmor-loader build on ARM64.
```# make all WHAT=apparmor-loader
./image-util.sh build apparmor-loader
Building image for apparmor-loader OS/ARCH: linux/amd64...
make[1]: Entering directory '/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
go: downloading k8s.io/klog v1.0.0
go: extracting k8s.io/klog v1.0.0
go: finding k8s.io/klog v1.0.0
make[1]: Leaving directory '/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
/go/src/k8s.io/kubernetes/_tmp/test-images-build.g6iRGF /go/src/k8s.io/kubernetes/test/images
skip cross-build amd64 on non-supported platform aarch64.
...
Building image for apparmor-loader OS/ARCH: linux/arm64...
make[1]: Entering directory '/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
...
Successfully built efc23c2ab906
Successfully tagged gcr.io/kubernetes-e2e-test-images/apparmor-loader:1.1-linux-arm64
```

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #82775
Fixes #81920
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chendave** [comment]
cc @BenTheElder  @mkumatag @dims

**Comment by BenTheElder** [comment]
sorry I'm behind on reviews
/ok-to-test

**Comment by BenTheElder** [comment]
broadly the idea SGTM
cc @cblecker @dims

**Comment by chendave** [comment]
@BenTheElder Thanks for picking this up.

**Comment by mkumatag** [comment]
> broadly the idea SGTM
> cc @cblecker @dims

+1, will review once I get some time over the weekend, need good amount of testing as well.

**Comment by chendave** [comment]
@mkumatag  thanks for your time on this.

**Comment by chendave** [comment]
poke @mkumatag , could you take a look at this pls?

**Comment by mkumatag** [comment]
> poke @mkumatag , could you take a look at this pls?

well,! I'm busy today, I will take a look in the next couple of days!

File: test/images/image-util.sh [hunk 1]
```diff
@@ -49,57 +75,78 @@ build() {
...
-
-    docker build --pull -t "${REGISTRY}/${IMAGE}-${arch}:${TAG}" .
-
-    popd
-  done
+        docker build --pull -t "${REGISTRY}/${IMAGE}-${arch}:${TAG}" .
+        popd
+      done
+      ;;
+    arm*|aarch*)
```
Comment (mkumatag) [inline test/images/image-util.sh]: All the non-amd64 code is same, I'm wondering whether we club all non-amd64 code into one!

File: test/images/image-util.sh [hunk 2]
```diff
@@ -49,57 +75,78 @@ build() {
...
+          # Cross build on non-amd server is not supported, build native image only
+          ${SED} -i "/CROSS_BUILD_/d" Dockerfile
+          # image tag
+          TAG=$(<VERSION)
+          docker build --pull -t "${REGISTRY}/${IMAGE}-${arch}:${TAG}" .
+          popd
+        fi
+      done
+      ;;
+    powerpc*|ppc*)
```
Comment (mkumatag) [inline test/images/image-util.sh]: just `ppc64le` is good enough.

**Review by mkumatag — CHANGES_REQUESTED** [review]

File: test/images/image-util.sh (hunk 2 above)
Comment (chendave) [reply test/images/image-util.sh]: possible value is  `ppc`, `ppc64`, `ppc64le` I think

File: test/images/image-util.sh [hunk 3]
```diff
@@ -38,6 +38,32 @@ getBaseImage() {
   grep "${arch}=" BASEIMAGE | cut -d= -f2
 }
 
+
```
[the remark this answers is not in the document]
Comment (chendave) [reply test/images/image-util.sh]: Nice catch!

File: test/images/image-util.sh (hunk 1 above)
Comment (chendave) [reply test/images/image-util.sh]: agreed!

File: test/images/image-util.sh (hunk 2 above)
Comment (mkumatag) [reply test/images/image-util.sh]: well, docker is supported only on `ppc64le` value, rest all unsupported.

Comment (chendave) [reply test/images/image-util.sh]: thanks, I changed this to match with ppc*.

File: test/images/image-util.sh (hunk 1 above)
Comment (chendave) [reply test/images/image-util.sh]: consolidated some command code into a separate method.

File: test/images/image-util.sh (hunk 2 above)
Comment (chendave) [reply test/images/image-util.sh]: update it again to exactly match with `ppc64le`.

**Comment by chendave** [comment]
@mkumatag all comments addressed, could you pls take another look? thank you!

**Comment by listx** [comment]
Can you rebase?

**Comment by chendave** [comment]
ping @listx for review, thanks

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
I'm not inclined to try and land this as part of v1.19 unless there is a pressing reason to do so

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
Please don't freeze PR's.  Do you intend to move forward on this in v1.21? If so, add it to that milestone

**Comment by spiffxp** [comment]
needs-rebase, image-util.sh has been through a few changes since this was opened

/milestone v1.21
on behalf of @chendave 
/cc @BenTheElder @cblecker 
/cc @dims @hasheddan 
since this maybe relates to supported platfforms

**Comment by dims** [comment]
@chendave please rebase and we'll look again?

**Comment by chendave** [comment]
> @chendave please rebase and we'll look again?
Done

File: test/images/image-util.sh [hunk 4]
```diff
@@ -140,24 +140,36 @@ build() {
...
-        # Register qemu-*-static for all supported processors except the current one
-        echo "Registering qemu-*-static binaries in the kernel"
-        local sudo=""
-        if [[ $(id -u) != 0 ]]; then
-          sudo=sudo
+    # Only the cross-build on x86 is guaranteed by far, other arches like aarch64 doesn't support cross-build
+    # thus, there is no need to tackle a disability feature on those platforms, and also help to prevent from
+    # ending up a wrong image tag on non-amd64 platforms.
+    build_arch=$(uname -m)
+    if [[ ${build_arch} = "x86_64" ]]; then
```
Comment (joakimr-axis) [inline test/images/image-util.sh:147]: No need for double quotes on static strings, better with single (or no) quotes.
```shell
if [[ ${build_arch} = 'x86_64' ]]; then
```

File: test/images/image-util.sh [hunk 5]
```diff
@@ -140,24 +140,36 @@ build() {
...
+        # copy the qemu-*-static binary to docker image to build the multi architecture image on x86 platform
+        if grep -q "CROSS_BUILD_" Dockerfile; then
+          if [[ "${arch}" == "amd64" ]]; then
```
Comment (joakimr-axis) [inline test/images/image-util.sh:150]: Better use `=` instead of `==` since they are equal in bash (but `=` is POSIX). Also same thing with the quotes for the static string. Suggestion:
```shell
if [[ "${arch}" = 'amd64' ]]; then
```

File: test/images/image-util.sh [hunk 6]
```diff
@@ -140,24 +140,36 @@ build() {
...
+            ${SED} -i "/CROSS_BUILD_/d" Dockerfile
```
Comment (joakimr-axis) [inline test/images/image-util.sh:151]: If the the value of `${SED}` contains a whitespace, this line will fail. Also, `/CROSS_BUILD_/d` is a static string, isn't it? Suggestion:
```shell
"${SED}" -i '/CROSS_BUILD_/d' Dockerfile
```

File: test/images/image-util.sh [hunk 7]
```diff
@@ -140,24 +140,36 @@ build() {
...
-        local sudo=""
-        if [[ $(id -u) != 0 ]]; then
-          sudo=sudo
+    # Only the cross-build on x86 is guaranteed by far, other arches like aarch64 doesn't support cross-build
+    # thus, there is no need to tackle a disability feature on those platforms, and also help to prevent from
+    # ending up a wrong image tag on non-amd64 platforms.
+    build_arch=$(uname -m)
+    if [[ ${build_arch} = "x86_64" ]]; then
+        # copy the qemu-*-static binary to docker image to build the multi architecture image on x86 platform
+        if grep -q "CROSS_BUILD_" Dockerfile; then
```
Comment (joakimr-axis) [inline test/images/image-util.sh:149]: Better use single quotes for the static string to clearly show it is not `"$CROSS_BUILD_"` with a typo
```shell
if grep -q 'CROSS_BUILD_' Dockerfile; then
```

File: test/images/image-util.sh [hunk 8]
```diff
@@ -140,24 +140,36 @@ build() {
...
+          if [[ "${arch}" == "amd64" ]]; then
+            ${SED} -i "/CROSS_BUILD_/d" Dockerfile
+          else
+            ${SED} -i "s|QEMUARCH|${QEMUARCHS[$arch]}|g" Dockerfile
```
Comment (joakimr-axis) [inline test/images/image-util.sh:153]: Same here with handling whitespaces for `${SED}"`:
```shell
"${SED}" -i "s|QEMUARCH|${QEMUARCHS[$arch]}|g" Dockerfile
```

File: test/images/image-util.sh [hunk 9]
```diff
@@ -140,24 +140,36 @@ build() {
...
+            # Register qemu-*-static for all supported processors except the current one
+            echo "Registering qemu-*-static binaries in the kernel"
```
Comment (joakimr-axis) [inline test/images/image-util.sh:155]: Suggesting
```shell
echo 'Registering qemu-*-static binaries in the kernel'
```
since nothing is to be expanded.

File: test/images/image-util.sh [hunk 10]
```diff
@@ -140,24 +140,36 @@ build() {
...
+            local sudo=""
```
Comment (joakimr-axis) [inline test/images/image-util.sh:156]: No need for the `""`. Either
```shell
local sudo
```
or
```shell
local sudo=''
```
will do the trick.

File: test/images/image-util.sh [hunk 11]
```diff
@@ -140,24 +140,36 @@ build() {
...
+            if [[ $(id -u) != 0 ]]; then
```
Comment (joakimr-axis) [inline test/images/image-util.sh:157]: Use `-ne` for numerical comparisons (`!=` is a string comparison):
```shell
if [[ $(id -u) -ne 0 ]]; then
```

File: test/images/image-util.sh [hunk 12]
```diff
@@ -140,24 +140,36 @@ build() {
...
+	          sudo=sudo
+            fi
+            ${sudo} "${KUBE_ROOT}/third_party/multiarch/qemu-user-static/register/register.sh" --reset -p yes
+            curl -sSL https://github.com/multiarch/qemu-user-static/releases/download/"${QEMUVERSION}"/x86_64_qemu-"${QEMUARCHS[$arch]}"-static.tar.gz | tar -xz -C "${temp_dir}"
+            # Ensure we don't get surprised by umask settings
+            chmod 0755 "${temp_dir}/qemu-${QEMUARCHS[$arch]}-static"
+            ${SED} -i "s/CROSS_BUILD_//g" Dockerfile
```
Comment (joakimr-axis) [inline test/images/image-util.sh:164]: Suggestion:
```shell
"${SED}" -i 's/CROSS_BUILD_//g' Dockerfile
```

File: test/images/image-util.sh [hunk 13]
```diff
@@ -140,24 +140,36 @@ build() {
...
-        # Ensure we don't get surprised by umask settings
-        chmod 0755 "${temp_dir}/qemu-${QEMUARCHS[$arch]}-static"
-        ${SED} -i "s/CROSS_BUILD_//g" Dockerfile
-      fi
+    elif [[ "${QEMUARCHS[$arch]}" != "${build_arch}" ]]; then
+		echo "skip cross-build $arch on non-supported platform ${build_arch}."
+		popd
+        continue
+    else
+        ${SED} -i "/CROSS_BUILD_/d" Dockerfile
```
Comment (joakimr-axis) [inline test/images/image-util.sh:172]: Suggestion:
```shell
"${SED}" -i '/CROSS_BUILD_/d' Dockerfile
```

File: test/images/image-util.sh (hunk 4 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 5 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 6 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 7 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 8 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 9 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 10 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 11 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 12 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

File: test/images/image-util.sh (hunk 13 above)
Comment (chendave) [reply test/images/image-util.sh]: Done

**Comment by chendave** [comment]
@joakimr-axis thanks for the review, all fixed, PTAL again?

**Comment by joakimr-axis** [comment]
> @joakimr-axis thanks for the review, all fixed, PTAL again?

Looks really nice now, IMO!

**Comment by dims** [comment]
verified that this works! here's the log:
<details>
```
ubuntu@ip-172-31-81-16:~/go/src/k8s.io/kubernetes/test/images$ make WHAT=apparmor-loader
./image-util.sh build apparmor-loader "docker"
Building image for apparmor-loader OS/ARCH: linux/amd64...
make[1]: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
Unable to find image 'golang:1.15.7' locally
1.15.7: Pulling from library/golang
6e5587ff5efa: Already exists
439dbbb05ea0: Already exists
3b89c8b4e5b2: Already exists
4a53f70a43c3: Already exists
d56052def468: Already exists
0371b45dab95: Already exists
d81d5ca3d230: Already exists
Digest: sha256:c161abf0cde3969e05f6914a86cab804b2b0df515f4ff9570475b25547ba7959
Status: Downloaded newer image for golang:1.15.7
make[1]: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
~/go/src/k8s.io/kubernetes/_tmp/test-images-build.X4kmL8 ~/go/src/k8s.io/kubernetes/test/images
skip cross-build amd64 on non-supported platform aarch64.
~/go/src/k8s.io/kubernetes/test/images
Building image for apparmor-loader OS/ARCH: linux/arm...
make[1]: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
make[1]: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
~/go/src/k8s.io/kubernetes/_tmp/test-images-build.UmKtdN ~/go/src/k8s.io/kubernetes/test/images
skip cross-build arm on non-supported platform aarch64.
~/go/src/k8s.io/kubernetes/test/images
Building image for apparmor-loader OS/ARCH: linux/arm64...
make[1]: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
make[1]: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
~/go/src/k8s.io/kubernetes/_tmp/test-images-build.zU1Lsj ~/go/src/k8s.io/kubernetes/test/images
#1 [internal] load build definition from Dockerfile
#1 sha256:7c4699ae537131bb0f2c400d16759e5047cca38947fd03a15438b5132a32597d
#1 transferring dockerfile: 1.02kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:8c68f4a7464b8841954974b816960c33ed1f036c5d10042bd8552f42c95de2ac
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/arm64v8/alpine:3.8
#3 sha256:b7d89063be271a1a2b059b7075ff01a4c587be4d21506d6af2b491566145b0ed
#3 DONE 0.4s

#6 [internal] load build context
#6 sha256:d9a7cf7b351564b69bf9c40cc1de9afc7d6c80c6f6b95b686d3c75b9050efbcd
#6 transferring context: 2.07MB 0.1s done
#6 DONE 0.1s

#4 [1/3] FROM docker.io/arm64v8/alpine:3.8@sha256:e802987f152d7826cf929ad4999fb3bb956ce7a30966aeb46c749f9120eaf22c
#4 sha256:24f3a7ff9a87ea1fb3fb3f83e192387ed885bc1d792452c6118fb8f701ece51c
#4 resolve docker.io/arm64v8/alpine:3.8@sha256:e802987f152d7826cf929ad4999fb3bb956ce7a30966aeb46c749f9120eaf22c done
#4 sha256:e802987f152d7826cf929ad4999fb3bb956ce7a30966aeb46c749f9120eaf22c 528B / 528B done
#4 sha256:b22edbe95d11980cbd47579189e8e6382dbb39629ca636f2a3b2741fae23bf1d 1.51kB / 1.51kB done
#4 sha256:788aef77d06ba65af872cf0c2da5b49362f6c05a5c8d1f8ceb4fd8b070e56876 2.10MB / 2.10MB 0.1s done
#4 extracting sha256:788aef77d06ba65af872cf0c2da5b49362f6c05a5c8d1f8ceb4fd8b070e56876 0.1s done
#4 DONE 0.2s

#5 [2/3] RUN apk add apparmor libapparmor --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ --allow-untrusted &&     apk add --no-cache musl>1.1.20 --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/
#5 sha256:081c3b71e868ada219469ec8783caff6932f1a8d69cd77bbc74c1e78dc405fd8
#5 0.221 fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/aarch64/APKINDEX.tar.gz
#5 0.354 fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/aarch64/APKINDEX.tar.gz
#5 0.491 fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/aarch64/APKINDEX.tar.gz
#5 0.657 (1/9) Installing ncurses-terminfo-base (6.1_p20180818-r1)
#5 0.667 (2/9) Installing ncurses-terminfo (6.1_p20180818-r1)
#5 0.823 (3/9) Installing ncurses-libs (6.1_p20180818-r1)
#5 0.830 (4/9) Installing readline (7.0.003-r0)
#5 0.836 (5/9) Installing bash (4.4.19-r1)
#5 0.855 Executing bash-4.4.19-r1.post-install
#5 0.857 (6/9) Installing libintl (0.19.8.1-r2)
#5 0.867 (7/9) Installing apparmor (2.13.4-r0)
#5 1.269 (8/9) Installing sed (4.4-r2)
#5 1.280 (9/9) Installing libapparmor (2.13.4-r0)
#5 1.451 Executing busybox-1.28.4-r3.trigger
#5 1.456 OK: 14 MiB in 22 packages
#5 1.490 fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
#5 1.621 fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/aarch64/APKINDEX.tar.gz
#5 1.674 fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/aarch64/APKINDEX.tar.gz
#5 1.759 (1/2) Upgrading musl (1.1.19-r11 -> 1.2.2-r1)
#5 1.778 (2/2) Upgrading musl-utils (1.1.19-r11 -> 1.2.2-r1)
#5 1.790 Executing busybox-1.28.4-r3.trigger
#5 1.793 OK: 14 MiB in 22 packages
#5 DONE 2.0s

#7 [3/3] ADD loader /usr/bin/loader
#7 sha256:4cec41f83d234b0aa4fd59ba93052992378d07358ce36254f65b4e6ad0a253b1
#7 DONE 0.1s

#8 exporting to image
#8 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#8 exporting layers
#8 exporting layers 0.3s done
#8 writing image sha256:c2954f52051d8a05353a59c559e3199442ea903a2dc54ccc1dde9fe13010e2f7 done
#8 naming to gcr.io/kubernetes-e2e-test-images/apparmor-loader:1.3-linux-arm64 done
#8 DONE 0.3s
~/go/src/k8s.io/kubernetes/test/images
Building image for apparmor-loader OS/ARCH: linux/ppc64le...
make[1]: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
../image-util.sh bin loader
make[1]: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes/test/images/apparmor-loader'
~/go/src/k8s.io/kubernetes/_tmp/test-images-build.gBZZ9I ~/go/src/k8s.io/kubernetes/test/images
skip cross-build ppc64le on non-supported platform aarch64.
~/go/src/k8s.io/kubernetes/test/images



ubuntu@ip-172-31-81-16:~/go/src/k8s.io/kubernetes/test/images$ uname -a
Linux ip-172-31-81-16 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:53:31 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux



ubuntu@ip-172-31-81-16:~/go/src/k8s.io/kubernetes/test/images$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

**Comment by pacoxu** [comment]
/test pull-kubernetes-e2e-kind
open #99252 for the volume flake

**Comment by chendave** [comment]
@dims  thanks for verifying this PR, it's great to see this got merged eventually and release me from this long standing changing request.
