### PR TITLE
[Kubeadm]: Fix CoreDNS migration logic

### LINKED ISSUE #96833: kubeadm upgrade (v1.19+) does not retain coredns configmap
**What happened**:
`kubeadm upgrade apply -y v1.19.3` does not retaining coredns configmap

```
...
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
[dryrun] Resource name: "coredns"
[dryrun] Returning faked GET response:
	apiVersion: v1
	data:
	  Corefile: |
	    consul {
	        errors
	        forward . 10.106.96.16:8600 10.106.96.17:8600 10.106.96.18:8600
	        loadbalance
	        cache 5
	        reload
	    }
...
[dryrun] Would perform action CREATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  Corefile: |
	    .:53 {
	        errors
	        health {
	           lameduck 5s
	        }
	        ready
	        kubernetes cluster.local in-addr.arpa ip6.arpa {
	           pods insecure
	           fallthrough in-addr.arpa ip6.arpa
	           ttl 30
	        }
	        prometheus :9153
	        forward . /etc/resolv.conf {
	           max_concurrent 1000
	        }
	        cache 30
	        loop
	        reload
	        loadbalance
	    }
	kind: ConfigMap
	metadata:
	  creationTimestamp: null
	  name: coredns
	  namespace: kube-system
...
```
using v1.19.4 makes no difference

**What you expected to happen**:

`kubeadm upgrade apply` should  follow documentation and retain coredns configmap

**How to reproduce it (as minimally and precisely as possible)**:
upgrading from v1.18.6 to v1.19.3

**Anything else we need to know?**:
`kubeadm upgrade apply -y v1.18.12` works like a charm

```
[dryrun] Resource name: "coredns"
[dryrun] Attached patch:
	{"spec":{"template":{"spec":{"volumes":[{"name": "config-volume", "configMap":{"name": "coredns", "items":[{"key": "Corefile-backup", "path": "Corefile-backup"}]}}]}}}}
W1124 12:32:32.521106   19721 dns.go:282] the CoreDNS Configuration was not migrated: unable to migrate CoreDNS ConfigMap: start version '1.7.0' not supported. The existing CoreDNS Corefile configuration has been retained.
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
...
[dryrun] Would perform action UPDATE on resource "configmaps" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  Corefile: |
	    consul {
	        errors
	        forward . 10.106.96.16:8600 10.106.96.17:8600 10.106.96.18:8600
	        loadbalance
	        cache 5
	        reload
	    }
...
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 4.20.13-1.el7.elrepo.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
As stated in https://github.com/kubernetes/kubernetes/issues/96833#issuecomment-736076870, this PR fixes the logic around migrating the CoreDNS Corefile. I've added extensive tests to ensure all scenarios are covered.

**Which issue(s) this PR fixes**:

Fixes #96833 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: Fixes a kubeadm upgrade bug that could cause a custom CoreDNS configuration to be replaced with the default.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/phases/addons/dns/dns.go [hunk 1]
```diff
@@ -279,7 +279,13 @@ func createCoreDNSAddon(deploymentBytes, serviceBytes, configBytes []byte, clien
...
 	canMigrateCorefile := true
 
-	if corefileMigrationRequired {
+	if corefile == "" || migration.Default("", corefile) {
+		// If the Corefile is empty or default, the latest default Corefile will be applied
+		if err := apiclient.CreateOrUpdateConfigMap(client, coreDNSConfigMap); err != nil {
+			return err
+		}
+	} else if corefileMigrationRequired {
+		//If migration is required, try and migrate the Corefile
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/addons/dns/dns.go:288]: nit: missing space after `//`

**Review by neolit123 — COMMENTED** [review]
thanks @rajansandeep added one minor nit.
should this be backported and to which releases?

/approve

**Review by chrisohaver — APPROVED** [review]

**Comment by neolit123** [comment]
> NONE

we should add a release note here, e.g.:

> kubeadm: fix a bug related to the detection if CoreDNS Corefile migration is required

(please, adjust as see fit)

**Comment by rajansandeep** [comment]
> should this be backported and to which releases?

@neolit123, I think this should be backported to 1.19

**Comment by neolit123** [comment]
> Fixes a kubeadm upgrade bug that could cause a custom CoreDNS configuration to be replaced with the default.

please prefix the release note with `kubeadm: ...`

> kubeadm: fixes an upgrade bug that could cause a custom CoreDNS configuration to be replaced with the default.

> @neolit123, I think this should be backported to 1.19

ok, we can backport after this PR merges.

**Review by yagonobre — COMMENTED** [review]
Thanks!
/lgtm

**Comment by yagonobre** [comment]
/hold
just to let @neolit123 lgtm as well

**Review by chrisohaver — APPROVED** [review]

**Comment by neolit123** [comment]
/hold cancel
should i sent the cherry pick for 1.19 @rajansandeep ?

**Comment by rajansandeep** [comment]
> should i sent the cherry pick for 1.19 @rajansandeep ?

I can send the cherry-pick. Do we have to wait for this PR to merge or I can send the cherry-pick now itself.

**Comment by neolit123** [comment]
> I can send the cherry-pick. Do we have to wait for this PR to merge or I can send the cherry-pick now itself.

ok, should be possible to send before merge too.

**Comment by pacoxu** [comment]
https://github.com/coredns/corefile-migration/blob/master/README.md#example-kubernetes-cluster-managemnt-tool-usage

I read the migration corefile suggestion. The only thing that kubeadm doesn't check here after this pr， is “unsupported plugins”. 

👍

**Comment by pacoxu** [comment]
still timeout
/retest

**Comment by chrisohaver** [comment]
> https://github.com/coredns/corefile-migration/blob/master/README.md#example-kubernetes-cluster-managemnt-tool-usage
> 
> I read the migration corefile suggestion. The only thing that kubeadm doesn't check here after this pr， is “unsupported plugins”.
> 
> 👍

IIRC, the original concept was to check for unsupported at preflight, so no need to check at this part. Don’t know if that has changed. Perhaps it’s worth adding a code comment here.

**Comment by neolit123** [comment]
the failing tests in `pull-kubernetes-e2e-gce-ubuntu-containerd` are a known problem:
https://github.com/kubernetes/kubernetes/issues/97002

**Comment by bai** [comment]
> /priority important-soon
> /milestone v1.20
> /triage accepted

Hey there, just wanted to mention that this was after test freeze and the branch cut. If you’d like this in 1.20, it needs to be cherry picked and the release is tomorrow so this probably won’t make it until 1.20.1.

**Comment by neolit123** [comment]
oh well,
@rajansandeep would you like to cherry pick this to the release-1.20 branch?

**Comment by neolit123** [comment]
i've sent the cherry pick here:
https://github.com/kubernetes/kubernetes/pull/97106
