### PR TITLE
Log invalid scheduler-policy input instead of panic

### LINKED ISSUE #99306: kube-schduler scheduler-policy incorrect values cause panic
#### What happened:
Trying to deploy Kubernetes 1.20.4 using Kops 1.20.0-alpha.2 and seeing a bunch of panic messages in the logs for `kube-scheduler`.

#### What you expected to happen:
Logged warnings that don't crash the `kube-scheduler` pod.

#### How to reproduce it (as minimally and precisely as possible):
Deploy Kubernetes 1.20.4 with the following command line arguments for `kube-scheduler` and the following `scheduler-policy` configmap.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler-ip-172-31-176-242.ec2.internal
  namespace: kube-system
spec:
  containers:
  - args:
    - --authentication-kubeconfig=/var/lib/kube-scheduler/kubeconfig
    - --authorization-kubeconfig=/var/lib/kube-scheduler/kubeconfig
    - --kubeconfig=/var/lib/kube-scheduler/kubeconfig
    - --config=/var/lib/kube-scheduler/config.yaml
    - --leader-elect=true
    - --policy-configmap-namespace=kube-system
    - --policy-configmap=scheduler-policy
    - --v=5
    - --logtostderr=false
    - --alsologtostderr
    - --log-file=/var/log/kube-scheduler.log
    command:
    - /usr/local/bin/kube-scheduler
    image: k8s.gcr.io/kube-scheduler:v1.20.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/kube-scheduler
      name: varlibkubescheduler
      readOnly: true
    - mountPath: /var/log/kube-scheduler.log
      name: logfile
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: ip-172-31-176-242.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /var/lib/kube-scheduler
      type: ""
    name: varlibkubescheduler
  - hostPath:
      path: /var/log/kube-scheduler.log
      type: ""
    name: logfile
```

```
apiVersion: v1                                                                                                                                                                                                                                              
kind: ConfigMap
metadata:
  name: scheduler-policy
  namespace: kube-system
data:                                                                                                                                                                                                                                                       
  policy.cfg: |-                                                                                                                                                                                                                                            
    {                                                                                                                                                                                                                                                       
      "kind" : "Policy",
      "apiVersion" : "v1",
      "predicates" : [
        {"name": "PodFitsHostPorts"},
        {"name": "PodFitsResources"},
        {"name": "MatchNodeSelector"},
        {"name": "NoVolumeZoneConflict"},
        {"name": "NoDiskConflict"},
        {"name": "PodToleratesNodeTaints"},
        {"name": "CheckVolumeBinding"}
      ],
      "priorities" : [
        {"weight": 1, "name": "SelectorSpreadPriority"},
        {"weight": 1, "name": "InterPodAffinityPriority"},
        {"weight": 1, "name": "LeastRequestedPriority"},
        {"weight": 1, "name": "MostRequestedPriority"},
        {"weight": 1, "name": "BalancedResourceAllocation"},
        {"weight": 1, "name": "NodePreferAvoidPodsPriority"},
        {"weight": 1, "name": "NodeAffinityPriority"},
        {"weight": 1, "name": "TaintTolerationPriority"},
        {"weight": 1, "name": "ImageLocalityPriority"},
        {"weight": 1, "name": "ServiceSpreadingPriority"},
        {"weight": 1, "name": "EvenPodsSpreadPriority"}
      ],
      "hardPodAffinitySymmetricWeight" : 1
    }
```

This should *work*; Now try adding `CheckNodeMemoryPressure` that is mentioned in the documentation to the list of predicates and see it fail. (https://kubernetes.io/docs/reference/scheduling/policies/)

#### Anything else we need to know?:
The panic looks like this
```
I0222 14:33:34.069143       1 requestheader_controller.go:244] Loaded a new request header values for RequestHeaderAuthRequestController                                                                                                                    
I0222 14:33:34.090608       1 factory.go:210] Creating scheduler from configuration: {{ } [{PodFitsHostPorts <nil>} {PodFitsResources <nil>} {MatchNodeSelector <nil>} {NoVolumeZoneConflict <nil>} {NoDiskConflict <nil>} {PodToleratesNodeTaints <nil>} {C
heckVolumeBinding <nil>}] [{SelectorSpreadPriority 1 <nil>} {InterPodAffinityPriority 1 <nil>} {LeastRequestedPriority 1 <nil>} {MostRequestedPriority 1 <nil>} {RequestedToCapacityRatioPriority 1 <nil>} {BalancedResourceAllocation 1 <nil>} {NodePreferA
voidPodsPriority 1 <nil>} {NodeAffinityPriority 1 <nil>} {TaintTolerationPriority 1 <nil>} {ImageLocalityPriority 1 <nil>} {ServiceSpreadingPriority 1 <nil>} {EvenPodsSpreadPriority 1 <nil>}] [] 1 false}                                                 
I0222 14:33:34.090664       1 factory.go:223] Registering predicate: PodFitsHostPorts                                                                                                                                                                       
I0222 14:33:34.090675       1 legacy_registry.go:560] Predicate type PodFitsHostPorts already registered, reusing.                                                                                                                                          
I0222 14:33:34.090679       1 factory.go:223] Registering predicate: PodFitsResources                                                                                                                                                                       
I0222 14:33:34.090682       1 legacy_registry.go:560] Predicate type PodFitsResources already registered, reusing.                                                                                                                                          I0222 14:33:34.090686       1 factory.go:223] Registering predicate: MatchNodeSelector                                                                                                                                                                      I0222 14:33:34.090689       1 legacy_registry.go:560] Predicate type MatchNodeSelector already registered, reusing.                                                                                                                                         I0222 14:33:34.090692       1 factory.go:223] Registering predicate: NoVolumeZoneConflict                                                                                                                                                                   I0222 14:33:34.090695       1 legacy_registry.go:560] Predicate type NoVolumeZoneConflict already registered, reusing.                                                                                                                                      I0222 14:33:34.090698       1 factory.go:223] Registering predicate: NoDiskConflict                                                                                                                                                                         
I0222 14:33:34.090701       1 legacy_registry.go:560] Predicate type NoDiskConflict already registered, reusing.                                                                                                                                            
I0222 14:33:34.090706       1 factory.go:223] Registering predicate: PodToleratesNodeTaints                                                                                                                                                                 
I0222 14:33:34.090710       1 legacy_registry.go:560] Predicate type PodToleratesNodeTaints already registered, reusing.                                                                                                                                    
I0222 14:33:34.090713       1 factory.go:223] Registering predicate: CheckVolumeBinding                                                                                                                                                                     
I0222 14:33:34.090716       1 legacy_registry.go:560] Predicate type CheckVolumeBinding already registered, reusing.                                                                                                                                        
I0222 14:33:34.090722       1 factory.go:238] Registering priority: SelectorSpreadPriority                                                                                                                                                                  
I0222 14:33:34.090733       1 legacy_registry.go:615] Priority type SelectorSpreadPriority already registered, reusing.                                                                                                                                     
I0222 14:33:34.090758       1 factory.go:238] Registering priority: InterPodAffinityPriority                                                                                                                                                                
I0222 14:33:34.090762       1 legacy_registry.go:615] Priority type InterPodAffinityPriority already registered, reusing.                                                                                                                                   
I0222 14:33:34.090766       1 factory.go:238] Registering priority: LeastRequestedPriority                                                                                                                                                                  
I0222 14:33:34.090769       1 legacy_registry.go:615] Priority type LeastRequestedPriority already registered, reusing.                                                                                                                                     I0222 14:33:34.090773       1 factory.go:238] Registering priority: MostRequestedPriority                                                                                                                                                                   I0222 14:33:34.090776       1 legacy_registry.go:615] Priority type MostRequestedPriority already registered, reusing.                                                                                                                                      I0222 14:33:34.090779       1 factory.go:238] Registering priority: RequestedToCapacityRatioPriority                                                                                                                                                        F0222 14:33:34.090783       1 legacy_registry.go:624] Invalid configuration: Priority type not found for "RequestedToCapacityRatioPriority"                                                                                                                 goroutine 1 [running]:                                                                                                                                                                                                                                      
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000410c01, 0xc000266160, 0x8c, 0xa7)                                                                                                                                                                      
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9                                                                                                                               
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2dc7a40, 0xc000000003, 0x0, 0x0, 0xc000036850, 0x2ce6b75, 0x12, 0x270, 0x0)                                                                                                                    
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b                                                                                                                               
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2dc7a40, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1de47b3, 0x35, 0xc00093ec80, 0x1, ...)                                                                                                            
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191                                                                                                                               
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)                                                                                                                                                                                                         
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502                                                                                                                                     
k8s.io/kubernetes/pkg/scheduler/framework/plugins.(*LegacyRegistry).ProcessPriorityPolicy(0xc000946180, 0xc00090abe0, 0x20, 0x1, 0x0, 0xc000b9f780, 0x1da91c1, 0x18)                                                                                        
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/legacy_registry.go:624 +0x7a5                                                                                                          
k8s.io/kubernetes/pkg/scheduler.(*Configurator).createFromConfig(0xc000b9faa0, 0x0, 0x0, 0x0, 0x0, 0xc00011fbc0, 0x7, 0x8, 0xc000920000, 0xc, ...)                                                                                                          
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/factory.go:239 +0x538                                                                                                                                    
k8s.io/kubernetes/pkg/scheduler.New(0x2041620, 0xc00033c000, 0x203c640, 0xc0003af1d0, 0xc000bca8b0, 0xc0005b2660, 0xc000b9fc30, 0x9, 0x9, 0x1b8cd00, ...)                                                                                                   
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:259 +0x458                                                                                                                                  
k8s.io/kubernetes/cmd/kube-scheduler/app.Setup(0x2018040, 0xc0004d0e00, 0xc000297860, 0x0, 0x0, 0x0, 0x47, 0x47, 0x47, 0x46)  
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:322 +0x50f                                                                                                                            
k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand(0xc0006dc840, 0xc000297860, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                                                                                    
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:127 +0xea                                                                                                                             
k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc0006dc840, 0xc000243ad0, 0x0, 0xb)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:81 +0x53 
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006dc840, 0xc00011e0d0, 0xb, 0xb, 0xc0006dc840, 0xc00011e0d0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006dc840, 0x1e6e840, 0x0, 0xc0006dc840)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-scheduler/scheduler.go:46 +0x112
goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2dc7a40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 116 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000380840)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xac
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x135

goroutine 118 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000380a20)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xac
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x135

goroutine 117 [select]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0003809c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:231 +0x405
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:68 +0x185

goroutine 48 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:188 +0xbf
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*metricsRecorder).run(0xc000683aa0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:88 +0x3f
created by k8s.io/kubernetes/pkg/scheduler/framework/runtime.newMetricsRecorder
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:60 +0x108

goroutine 105 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1e6e900, 0x1fcd2a0, 0xc000594420, 0x1, 0xc0001140c0) 
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1e6e900, 0x12a05f200, 0x0, 0x1, 0xc0001140c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x1e6e900, 0x12a05f200)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

goroutine 119 [select]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000380c00)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:231 +0x405
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:68 +0x185

goroutine 120 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000380cc0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xac
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x135

goroutine 121 [select]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000380e40)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:231 +0x405
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:68 +0x185

goroutine 127 [IO wait]:
internal/poll.runtime_pollWait(0x7f974b4a0378, 0x72, 0x1fcfc20) 
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000593118, 0x72, 0x1fcfc00, 0x2d2a6b8, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000593100, 0xc000bd8000, 0xc66, 0xc66, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000593100, 0xc000bd8000, 0xc66, 0xc66, 0x203000, 0x6583bb, 0xc00040e860)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e118, 0xc000bd8000, 0xc66, 0xc66, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0004c67a0, 0xc000bd8000, 0xc66, 0xc66, 0xb6f, 0xc61, 0xc000a90708)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00040e980, 0x1fcb560, 0xc0004c67a0, 0x40b8c5, 0x1b381a0, 0x1d10620)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00040e700, 0x1fcde40, 0xc00000e118, 0x5, 0xc00000e118, 0xb5e)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00040e700, 0x0, 0x0, 0xc0004c6720)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00040e700, 0xc00088f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000880960, 0xc000bf81f8, 0x9, 0x9, 0xc000881500, 0xc000a90d18, 0x1e6f300)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1fcb3c0, 0xc000880960, 0xc000bf81f8, 0x9, 0x9, 0x9, 0xc000bcb090, 0xc000116040, 0x0)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader(0xc000bf81f8, 0x9, 0x9, 0x1fcb3c0, 0xc000880960, 0x0, 0x0, 0xc000bc9e30, 0xc000a90dd0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x89
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc000bf81c0, 0xc000bc9e30, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000a90fa8, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1819 +0xd8
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000503500)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1741 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:705 +0x6c5

```

#### Environment:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Kops deployment on AWS

- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Kernel (e.g. `uname -a`):
```
Linux ip-172-31-176-242 5.4.0-1035-aws #37-Ubuntu SMP Wed Jan 6 21:01:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
```
$ kops version
Version 1.20.0-alpha.2 (git-66d61)
```

### PR DESCRIPTION
**Pull request by tanjing2020**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Logged warnings that don't crash the kube-scheduler pod.

#### Which issue(s) this PR fixes:

Fixes #99306

```
=== RUN   TestCreateFromConfig
=== RUN   TestCreateFromConfig/policy_with_unspecified_predicates_or_priorities_uses_default
=== RUN   TestCreateFromConfig/policy_with_arguments
=== RUN   TestCreateFromConfig/policy_with_HardPodAffinitySymmetricWeight_argument
=== RUN   TestCreateFromConfig/policy_with_illegal_arguments
E0303 11:28:37.788222   10956 legacy_registry.go:636] "Invalid configuration" err="priority type not found" policy={Name:RequestedToCapacityRatioPriority Weight:2 Argument:<nil>}
E0303 11:28:37.803846   10956 factory.go:249] "Get priority policy failed" err="priority type not found" priority={Name:RequestedToCapacityRatioPriority Weight:2 Argument:<nil>} args=&{Weight:0 NodeLabelArgs:<nil> RequestedToCapacityRatioArgs:<nil> ServiceAffinityArgs:&TypeMeta{Kind:,APIVersion:,} NodeResourcesFitArgs:<nil> InterPodAffinityArgs:<nil>}
--- PASS: TestCreateFromConfig (0.02s)
    --- PASS: TestCreateFromConfig/policy_with_unspecified_predicates_or_priorities_uses_default (0.00s)
    --- PASS: TestCreateFromConfig/policy_with_arguments (0.00s)
    --- PASS: TestCreateFromConfig/policy_with_HardPodAffinitySymmetricWeight_argument (0.00s)
    --- PASS: TestCreateFromConfig/policy_with_illegal_arguments (0.02s)
PASS
ok  	k8s.io/kubernetes/pkg/scheduler	0.119s
```
#### Does this PR introduce a user-facing change?

```
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/ok-to-test
👍

File: pkg/scheduler/factory.go [hunk 1]
```diff
@@ -221,7 +221,13 @@ func (c *Configurator) createFromConfig(policy schedulerapi.Policy) (*Scheduler,
 	} else {
 		for _, predicate := range policy.Predicates {
 			klog.V(2).InfoS("Registering predicate", "predicate", predicate.Name)
-			predicateKeys.Insert(lr.ProcessPredicatePolicy(predicate, args))
+			predicateName, err := lr.ProcessPredicatePolicy(predicate, args)
+			if err == nil {
+				predicateKeys.Insert(predicateName)
+			} else {
+				klog.ErrorS(err, "Get predicate policy failed", "predicate", predicate, "args", args)
```
Comment (alculquicondor) [inline pkg/scheduler/factory.go:228]: do not just log, return the error

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 2]
```diff
@@ -699,12 +712,14 @@ func validatePredicateOrDie(predicate config.PredicatePolicy) {
...
-			klog.Fatalf("Exactly 1 predicate argument is required, numArgs: %v, Predicate: %s", numArgs, predicate.Name)
+			err := errors.New("exactly 1 predicate argument is required")
+			klog.ErrorS(err, "Check predicate parameter failed", "numArgs", numArgs, "predicate", predicate)
 		}
 	}
+	return nil
 }
 
-func validatePriorityOrDie(priority config.PriorityPolicy) {
+func validatePriorityOrDie(priority config.PriorityPolicy) error {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:722]: remove `orDie` since we don't panic anymore.

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 3]
```diff
@@ -686,10 +699,10 @@ func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, co
 		priorityName = noderesources.RequestedToCapacityRatioName
 	}
 
-	return priorityName
+	return priorityName, nil
 }
 
-func validatePredicateOrDie(predicate config.PredicatePolicy) {
+func validatePredicateOrDie(predicate config.PredicatePolicy) error {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:705]: remove `OrDie`

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 4]
```diff
@@ -597,13 +604,17 @@ func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy,
...
 
 // ProcessPriorityPolicy given a PriorityPolicy, return the plugin name implementing the priority and update
 // the ConfigProducerArgs if necessary.
-func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, configProducerArgs *ConfigProducerArgs) string {
-	validatePriorityOrDie(policy)
+func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, configProducerArgs *ConfigProducerArgs) (string, error) {
+	err := validatePriorityOrDie(policy)
+	if err != nil {
+		klog.ErrorS(err, "Get illegal priority parameter", "policy", policy)
+		return "", nil
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:616]:
```suggestion
		return "", err
```

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 5]
```diff
@@ -546,8 +547,12 @@ func appendToPluginSet(set config.PluginSet, name string, weight *int32) config.
 
 // ProcessPredicatePolicy given a PredicatePolicy, return the plugin name implementing the predicate and update
 // the ConfigProducerArgs if necessary.
-func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy, pluginArgs *ConfigProducerArgs) string {
-	validatePredicateOrDie(policy)
+func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy, pluginArgs *ConfigProducerArgs) (string, error) {
+	err := validatePredicateOrDie(policy)
+	if err != nil {
+		klog.ErrorS(err, "Get illegal predicate parameter", "policy", policy)
+		return "", nil
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:554]:
```suggestion
return "", err
```

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 6]
```diff
@@ -558,12 +563,14 @@ func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy,
...
-		return predicateName
+		return predicateName, nil
 	}
 
 	if policy.Argument == nil || (policy.Argument.ServiceAffinity == nil &&
 		policy.Argument.LabelsPresence == nil) {
-		klog.Fatalf("Invalid configuration: Predicate type not found for %q", policy.Name)
+		err := errors.New("predicate type not found")
+		klog.ErrorS(err, "Invalid configuration", "policy", policy)
+		return "", nil
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:573]:
```suggestion
return err
```

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 7]
```diff
@@ -613,15 +624,17 @@ func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, co
...
 
 	// generate the priority function, if a custom priority is requested
 	if policy.Argument == nil ||
 		(policy.Argument.ServiceAntiAffinity == nil &&
 			policy.Argument.RequestedToCapacityRatioArguments == nil &&
 			policy.Argument.LabelPreference == nil) {
-		klog.Fatalf("Invalid configuration: Priority type not found for %q", priorityName)
+		err := errors.New("priority type not found")
+		klog.ErrorS(err, "Invalid configuration", "policy", policy)
+		return "", err
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:637]:
```suggestion
return "", errors.New("priority type not found for %q", priorityName)
```

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 8]
```diff
@@ -699,12 +712,14 @@ func validatePredicateOrDie(predicate config.PredicatePolicy) {
 			numArgs++
 		}
 		if numArgs != 1 {
-			klog.Fatalf("Exactly 1 predicate argument is required, numArgs: %v, Predicate: %s", numArgs, predicate.Name)
+			err := errors.New("exactly 1 predicate argument is required")
+			klog.ErrorS(err, "Check predicate parameter failed", "numArgs", numArgs, "predicate", predicate)
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:716]:
```suggestion
  return fmt.Errorf("exactly 1 predicate argument is required for predicate %q; got %v", predicate, numArgs)
```

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 9]
```diff
@@ -717,7 +732,9 @@ func validatePriorityOrDie(priority config.PriorityPolicy) {
 			numArgs++
 		}
 		if numArgs != 1 {
-			klog.Fatalf("Exactly 1 priority argument is required, numArgs: %v, Priority: %s", numArgs, priority.Name)
+			err := errors.New("exactly 1 priority argument is required")
+			klog.ErrorS(err, "Check priority parameter failed", "numArgs", numArgs, "priority", priority)
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:736]:
```suggestion
  return fmt.Errorf("exactly 1 priority argument is required for priority %q; got %v", priority, numArgs)
```

File: pkg/scheduler/factory.go [hunk 10]
```diff
@@ -221,7 +221,14 @@ func (c *Configurator) createFromConfig(policy schedulerapi.Policy) (*Scheduler,
...
 		for _, predicate := range policy.Predicates {
 			klog.V(2).InfoS("Registering predicate", "predicate", predicate.Name)
-			predicateKeys.Insert(lr.ProcessPredicatePolicy(predicate, args))
+			predicateName, err := lr.ProcessPredicatePolicy(predicate, args)
+			if err == nil {
+				predicateKeys.Insert(predicateName)
+			} else {
+				klog.ErrorS(err, "Invalid predicate policy configuration", "predicate", predicate, "args", args)
+				return nil, err
+			}
```
Comment (ahg-g) [inline pkg/scheduler/factory.go:230]:
```suggestion
			if err != nil {
				return nil, err
			}
                        predicateKeys.Insert(predicateName)			
```

File: pkg/scheduler/factory.go [hunk 11]
```diff
@@ -236,7 +243,13 @@ func (c *Configurator) createFromConfig(policy schedulerapi.Policy) (*Scheduler,
...
 			}
 			klog.V(2).InfoS("Registering priority", "priority", priority.Name)
-			priorityKeys[lr.ProcessPriorityPolicy(priority, args)] = priority.Weight
+			priorityName, err := lr.ProcessPriorityPolicy(priority, args)
+			if err == nil {
+				priorityKeys[priorityName] = priority.Weight
+			} else {
+				klog.ErrorS(err, "Invalid priority policy configuration", "priority", priority, "args", args)
+				return nil, err
+			}
```
Comment (ahg-g) [inline pkg/scheduler/factory.go:252]:
```suggestion
			if err != nil {
				return nil, err
			}
			priorityKeys[priorityName] = priority.Weight	
```

File: pkg/scheduler/factory_test.go [hunk 12]
```diff
@@ -205,6 +207,7 @@ func TestCreateFromConfig(t *testing.T) {
 				PreBind: schedulerapi.PluginSet{Enabled: []schedulerapi.Plugin{{Name: "VolumeBinding"}}},
 				Bind:    schedulerapi.PluginSet{Enabled: []schedulerapi.Plugin{{Name: "DefaultBinder"}}},
 			},
+			wantErr: "",
```
Comment (ahg-g) [inline pkg/scheduler/factory_test.go:210]: no need to explicitly set this, the default is empty string. ditto in the other places below.

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 13]
```diff
@@ -546,8 +546,12 @@ func appendToPluginSet(set config.PluginSet, name string, weight *int32) config.
 
 // ProcessPredicatePolicy given a PredicatePolicy, return the plugin name implementing the predicate and update
 // the ConfigProducerArgs if necessary.
-func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy, pluginArgs *ConfigProducerArgs) string {
-	validatePredicateOrDie(policy)
+func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy, pluginArgs *ConfigProducerArgs) (string, error) {
+	err := validatePredicate(policy)
+	if err != nil {
+		klog.ErrorS(err, "Invalid configuration", "policy", policy)
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:552]: no need for this, the error will bubble up and will eventually get logged.

File: pkg/scheduler/framework/plugins/legacy_registry.go [hunk 14]
```diff
@@ -597,13 +601,17 @@ func (lr *LegacyRegistry) ProcessPredicatePolicy(policy config.PredicatePolicy,
...
 }
 
 // ProcessPriorityPolicy given a PriorityPolicy, return the plugin name implementing the priority and update
 // the ConfigProducerArgs if necessary.
-func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, configProducerArgs *ConfigProducerArgs) string {
-	validatePriorityOrDie(policy)
+func (lr *LegacyRegistry) ProcessPriorityPolicy(policy config.PriorityPolicy, configProducerArgs *ConfigProducerArgs) (string, error) {
+	err := validatePriority(policy)
+	if err != nil {
+		klog.ErrorS(err, "Invalid configuration", "policy", policy)
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/legacy_registry.go:612]: ditto, remove this.

File: pkg/scheduler/factory_test.go [hunk 15]
```diff
@@ -402,9 +420,10 @@ func TestCreateFromConfig(t *testing.T) {
 					}
 				}),
 			)
-
 			if err != nil {
-				t.Fatalf("Error constructing: %v", err)
+				if !strings.Contains(err.Error(), tc.wantErr) {
```
Comment (alculquicondor) [inline pkg/scheduler/factory_test.go:424]: Not the best practice to compare error strings.

Please do a follow up where you use `cmp.Equal`

**Review by alculquicondor — COMMENTED** [review]
/lgtm
