### PR TITLE
Fix `startupProbe` behaviour changed

### LINKED ISSUE #101064: `startupProbe` behaviour changed in v1.21.0
#### What happened:

We detected `startupProbe` behavior change in v1.21.0

Example:
POD has `startupProbe` and `livenessProbe` for some containers

**Behavior in v1.20.5:**
1. POD starts
2. startupProbe applied
3. if startupProbe success, then start checks for livenessProbe
4. POD working
5. livenessProbe failed
6. container restarted
7. **startupProbe applied**
8. if startupProbe success, then start checks for livenessProbe
9. POD working

**Behavior in v1.21.0:**
1. POD starts
2. startupProbe applied
3. if startupProbe success, then start checks for livenessProbe
4. POD working
5. livenessProbe failed
6. container restarted
7. livenessProbe applied, **startupProbe skipped**
8. POD not ready yet, killed by liveness check
9. POD in restart loop

So, in v1.21 `startupProbe` is applied to "fresh" starts only and not used when container restarted.

#### What you expected to happen:
There is not mentions in changelog that behavior of the `startupProbe` is changed.
 `startupProbe` should run on container restarts also. 

#### How to reproduce it (as minimally and precisely as possible):
1. Create POD with `startupProbe` and `livenessProbe` 
2. Make `livenessProbe`  fail
3. Check that `startupProbe` doesn't apply after container restart
#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: baremetal

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
After the container restarts, `startupProbe` will no longer be executed, behaviour changed by #98571 !

#### Which issue(s) this PR fixes:

Fixes #101064

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression in 1.21 where startupProbe stopped working after a container's first restart
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by wzshiming** [comment]
/cc @matthyx  
`startupProbe` behaviour changed by #98571

**Comment by matthyx** [comment]
/hold
It's a bit more complicated... you cannot simply keep on running startupProbe, this is wasteful.

**Comment by wzshiming** [comment]
> /hold
> It's a bit more complicated... you cannot simply keep on running startupProbe, this is wasteful.

This will only be executed once when restarting

**Comment by matthyx** [comment]
> > /hold
> > It's a bit more complicated... you cannot simply keep on running startupProbe, this is wasteful.
> 
> This will only be executed once when restarting

Right, sorry I read too fast on my phone...
/lgtm
/triage accepted
/priority important-soon

**Comment by matthyx** [comment]
/cc @SergeyKanzhelev 
I think you were right Sergey, I completely forgot about restart when changing this bool...

File: pkg/kubelet/prober/worker.go [hunk 1]
```diff
@@ -251,7 +251,7 @@ func (w *worker) doProbe() (keepGoing bool) {
 	if c.Started != nil && *c.Started {
 		// Stop probing for startup once container has started.
 		if w.probeType == startup {
-			return false
+			return true
```
Comment (ehashman) [inline pkg/kubelet/prober/worker.go:254]: Is the comment still true?

Comment (wzshiming) [reply pkg/kubelet/prober/worker.go:254]: Yeah.  Revert #98571 https://github.com/kubernetes/kubernetes/pull/98571/files#diff-37568d7080a94147e978aa46a84cf8c6a4493b6e79030f787df268cb7dc8ba2aR247

Comment (matthyx) [reply pkg/kubelet/prober/worker.go:254]: Yes, it is still valid, since the return value tells the controller to keep running, but by returning early we skip the actual probe run.

File: pkg/kubelet/prober/worker.go [hunk 2]
```diff
@@ -251,7 +251,7 @@ func (w *worker) doProbe() (keepGoing bool) {
 	if c.Started != nil && *c.Started {
 		// Stop probing for startup once container has started.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:252]: please update comment to indicate that we keep it running to make sure it will work for restarted container

**Comment by sftim** [comment]
I suggest this revised changelog message:
```
Fix a bug where startupProbe stopped working after a container's first restart
```

**Comment by matthyx** [comment]
@wzshiming we also need to check whether this needs cherry picking on support branches...

**Comment by wzshiming** [comment]
> @wzshiming we also need to check whether this needs cherry picking on support branches...

Yes, `1.21` `1.20` `1.19` `1.18` need this PR, we can merge this PR first, and then cherry-picking

File: pkg/kubelet/prober/worker_test.go [hunk 3]
```diff
@@ -508,6 +502,6 @@ func TestStartupProbeDisabledByStarted(t *testing.T) {
 	// startupProbe fails, but is disabled
 	m.prober.exec = fakeExecProber{probe.Failure, nil}
 	msg = "Started, probe failure, result success"
-	expectStop(t, w, w.doProbe(), msg)
+	expectContinue(t, w, w.doProbe(), msg)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker_test.go:505]: if this was so easy to miss, does it deserve a real e2e test for actual restarting container?

Comment (matthyx) [reply pkg/kubelet/prober/worker_test.go:505]: Probably... I think the main issue was that I mixed up pod lifecycle and container lifecycle while coding, and then tried too hard to convince you and Elena :-(
The worst is that we went GA in 1.20 and the cherry-pick broke the probe in the latest 1.20 patch release...

Comment (ehashman) [reply pkg/kubelet/prober/worker_test.go:505]: Let's add an e2e in a followup.

**Review by ehashman — APPROVED** [review]
/lgtm
/hold cancel
