### PR TITLE
Remove check for CSI driver running on node for CSI migration attach operations

### LINKED ISSUE #115297: CSI migration race condition can cause unexpected detach and data loss
### What happened?

After the cluster was updated to enable PD CSI Driver, there was a race condition where AD Controller (kube-controller-manager) started to [populate the desired state of world](https://github.com/kubernetes/kubernetes/blob/dc2898b20c6bd9602ae1c3b51333e2e4640ed249/pkg/controller/volume/attachdetach/attach_detach_controller.go#L438-L447) BEFORE the PD CSI Driver was up, thus AD Controller gave us the error 

```
Error creating spec for volume "elasticsearch", pod "XXX"/"elasticsearch-0": error performing CSI migration checks and translation for PVC "dXX"/"elasticsearch-elasticsearch-0": in-tree plugin kubernetes.io/gce-pd is migrated on node gke-stage-XXXXX but driver pd.csi.storage.gke.io is not installed.
```

Then AD Controller triggered the disk detach because the disk/volume was not populated in the desired state of world.

Unfortunately the disk was in use during this detach and got corrupted.

### What did you expect to happen?

Since cluster upgrades can cause the controller manager and CSI drivers to start at different times, the AD controller needs to be more conservative when detaching

### How can we reproduce it (as minimally and precisely as possible)?

We have not been able to reproduce this, it came up from a customer.

### Anything else we need to know?

/sig storage
/assign @mattcary

### Kubernetes version

<details>
k8s 1.23, CSI migration enabled
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fix CSI migration race condition that can cause unexpected detach and data loss

#### Which issue(s) this PR fixes:
Fixes #115297

#### Does this PR introduce a user-facing change?
```release-note
Fix an issue where a CSI migrated volume may be prematurely detached when the CSI driver is not running on the node.
If CSI migration is enabled on the node, even the csi-driver is not up and ready, we will still add this volume to DSW.
```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/util/util.go [hunk 1]
```diff
@@ -377,14 +377,16 @@ func isCSIMigrationSupportedOnNode(nodeName types.NodeName, spec *volume.Spec, v
...
+
 		for _, driver := range csiNode.Spec.Drivers {
 			if driver.Name == driverName {
 				installed = true
 				break
 			}
 		}
 		if !installed {
-			return true, fmt.Errorf("in-tree plugin %s is migrated on node %s but driver %s is not installed", pluginName, string(nodeName), driverName)
+			klog.V(4).Infof("in-tree plugin %s is migrated on node %s but driver %s is not installed", pluginName, string(nodeName), driverName)
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util.go:388]: I think we can just remove the entire section from L374. It also avoids one more potential error at L376.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 2]
```diff
@@ -0,0 +1,316 @@
...
+	default:
+		// The volume is not mounted nor mapped
+	}
+	pv := &v1.PersistentVolume{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: "pvA",
+		},
+		Spec: v1.PersistentVolumeSpec{
+			PersistentVolumeSource: v1.PersistentVolumeSource{
+				RBD: &v1.RBDPersistentVolumeSource{
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:291]: Is this used anywhere? It looks like your test case examples are using hostpath and gce volume types.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 3]
```diff
@@ -0,0 +1,316 @@
...
+	var (
+		dirOrCreate = v1.HostPathType(v1.HostPathDirectoryOrCreate)
+		nodeName    = kubetypes.NodeName(testNodeName)
+		hostPath    = &v1.HostPathVolumeSource{
+			Path: socketPath,
+			Type: &dirOrCreate,
+		}
+		objectReference = v1.ObjectReference{Namespace: "claimrefns", Name: "test-pvc"}
+
+		volumeExampe = v1.Volume{
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:58]: I think it's easier to read and understand the test case when the comparison objects are defined in the table.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 4]
```diff
@@ -0,0 +1,316 @@
...
+						ReadOnly:     false,
+						VolumeAttributes: map[string]string{"partition": ""},
+					},
+				},
+				ClaimRef: &objectReference,
+			},
+		}
+	)
+
+	tmpDir, err := utiltesting.MkTmpdir("csi-test")
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:93]: Is the test case reading/writing any files? Do we need this?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 5]
```diff
@@ -0,0 +1,316 @@
...
+	if err != nil {
+		t.Fatalf("can't make a temp dir: %v", err)
+	}
+	defer os.RemoveAll(tmpDir)
+
+	csiTranslator := csitrans.New()
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:99]: All the initialization should be done per test case because they could be run in parallel. You could put these into a "setup()" function for better readability.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 6]
```diff
@@ -0,0 +1,316 @@
...
+		}
+		objectReference = v1.ObjectReference{Namespace: "claimrefns", Name: "test-pvc"}
+
+		volumeExampe = v1.Volume{
+			Name: volumeName,
+			VolumeSource: v1.VolumeSource{
+				HostPath: hostPath,
+			},
+		}
+		volumeExampeWithCSI = v1.Volume{
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:64]: typo should be "example"

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 7]
```diff
@@ -0,0 +1,316 @@
...
+			},
+			enableCSIMigration:   true,
+			wantPersistentVolume: persistentVolumeExampeWithCSI,
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.desc, func(t *testing.T) {
+			actualSpec, _ := CreateVolumeSpec(test.podVolume, test.pod, nodeName, plugMgr, pvcLister, pvLister, intreeToCSITranslator, csiTranslator)
+			if test.enableCSIMigration {
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:209]: I think you could check on `wantVolume` or `wantPersistentVolume` being set instead of needing this extra parameter.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 8]
```diff
@@ -0,0 +1,316 @@
...
+		{
+			ObjectMeta: metav1.ObjectMeta{Name: "test-pvc", Namespace: "default"},
+			Spec:       v1.PersistentVolumeClaimSpec{VolumeName: volumeName},
+			Status: v1.PersistentVolumeClaimStatus{
+				Phase: v1.ClaimBound,
+			},
+		},
+	}
+
+	tests := []struct {
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:149]: It looks like the two test cases you have appear to be 1) inline volume type that does not support csi migration 2) PV type that supports csi migration.

I think it would be good to add a few more test cases:
- Inline volume type that supports csi migration
- PV type that does not support csi migration
- CSINode object does not exist for a volume type that supports csi migration

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 4 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:93]: The test setup func volumetest.NewFakeAttachDetachVolumeHostWithCSINodeName(...) requires to have this tmpDir so I just set it to a value.

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 7 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:209]: You mean compare them to an empty struct by using cmp or reflect?

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 2 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:291]: This is a random pv created for fake.NewSimpleClientset() set up.

Comment (msau42) [reply pkg/controller/volume/attachdetach/util/util_test.go:291]: It looks like the function can take in an arbitrary set of objects: https://github.com/kubernetes/kubernetes/blob/1b141f021935910a9b937cc4e2469cbc8c098967/staging/src/k8s.io/client-go/kubernetes/fake/clientset_generated.go#L134

So I would only initialize it with objects you need.

Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:291]: I removed the whole setup for now.

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 7 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:209]: I did this ``!reflect.DeepEqual(emptyVolume, test.wantPersistentVolume)``, feels weird to me but it reduce one param in the test struct.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 9]
```diff
@@ -0,0 +1,369 @@
...
+	wantErrorMessage     string
+}
+
+func Test_CreateVolumeSpec(t *testing.T) {
+	for _, test := range []vaTest{
+		{
+			desc:           "inline volume type that does not support csi migration",
+			seupNodeName:   testNodeName,
+			createNodeName: nodeName,
+			podVolume:      volumeExample,
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:115]: it looks like `podVolume` is already included in `pod`. Can we get rid of `podVolume`?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 10]
```diff
@@ -0,0 +1,369 @@
...
+	wantVolume           v1.Volume
+	wantPersistentVolume v1.PersistentVolume
+	wantErrorMessage     string
+}
+
+func Test_CreateVolumeSpec(t *testing.T) {
+	for _, test := range []vaTest{
+		{
+			desc:           "inline volume type that does not support csi migration",
+			seupNodeName:   testNodeName,
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:113]: This looks like the same value for all test cases. Can we remove this argument?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 11]
```diff
@@ -0,0 +1,369 @@
...
+					Volumes: []v1.Volume{
+						{
+							VolumeSource: v1.VolumeSource{
+								HostPath: hostPath,
+							},
+						},
+					},
+				},
+			},
+			wantVolume: volumeExample,
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:131]: can you put the definition inline with the test case?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 12]
```diff
@@ -0,0 +1,369 @@
...
+		},
+		{
+			desc:           "inline volume type that supports csi migration",
+			seupNodeName:   testNodeName,
+			createNodeName: nodeName,
+			podVolume: v1.Volume{
+				Name: volumeName,
+				VolumeSource: v1.VolumeSource{
+					CSI: &v1.CSIVolumeSource{
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:140]: this should be an intree volume type like `GCEPersistentDisk`, instead of using `CSI` directly

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 13]
```diff
@@ -0,0 +1,369 @@
...
+			pod: &v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{
+					Name:      "kube-apiserver",
+					Namespace: "default",
+				},
+				Spec: v1.PodSpec{
+					Volumes: []v1.Volume{
+						{
+							VolumeSource: v1.VolumeSource{
+								HostPath: hostPath,
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:193]: remove HostPath. A VolumeSource can only have one type.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 14]
```diff
@@ -0,0 +1,369 @@
...
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:229]: Remove Hostpath

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 15]
```diff
@@ -0,0 +1,369 @@
...
+					ScaleIO: &v1.ScaleIOPersistentVolumeSource{},
+				},
+				ClaimRef: &objectReference2,
+			},
+		},
+	}
+
+	pvcLister := fakeframework.PersistentVolumeClaimLister{
+		{
+			ObjectMeta: metav1.ObjectMeta{Name: "test-pvc", Namespace: "default"},
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:353]: the pvc names are a little confusing. Can you have a more description name like "migrated-pvc", "non-migrated-pvc"?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 16]
```diff
@@ -0,0 +1,369 @@
...
+		},
+	} {
+		t.Run(test.desc, func(t *testing.T) {
+			plugMgr, intreeToCSITranslator, csiTranslator, pvLister, pvcLister := setup(test.seupNodeName, t)
+			actualSpec, err := CreateVolumeSpec(test.podVolume, test.pod, test.createNodeName, plugMgr, pvcLister, pvLister, intreeToCSITranslator, csiTranslator)
+
+			if (len(test.wantErrorMessage) > 0 && err == nil) || (err != nil && !strings.Contains(err.Error(), test.wantErrorMessage)) {
+				t.Errorf("got err %v, want err with message %v", err, test.wantErrorMessage)
+			}
+			if !reflect.DeepEqual(emptyPersistentVolume, test.wantPersistentVolume) {
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:275]: I think you can just make the `want*` variables pointers, and then you can do comparisions without this check.

Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:275]: There is struct within a struct, that is why the comparison == did not work.

Comment (msau42) [reply pkg/controller/volume/attachdetach/util/util_test.go:275]: yes you still need deep equal but I think you could eliminate the top level comparison on an empty struct if you used pointers.

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 12 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go]: How should the return spec of this look like? Is it a CSIVolumeSource?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 17]
```diff
@@ -0,0 +1,344 @@
...
+				t.Errorf("got err %v, want err with message %v", err, test.wantErrorMessage)
+			}
+			if test.wantPersistentVolume != nil {
+				gotVolumeWithCSIMigration := *actualSpec.PersistentVolume
+				if gotVolumeWithCSIMigration.Name != test.wantPersistentVolume.Name {
+					t.Errorf("got volume name is %v, want volume name is %v", gotVolumeWithCSIMigration.Name, test.wantPersistentVolume.Name)
+
+				}
+				if !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec, test.wantPersistentVolume.Spec) {
+					if gotVolumeWithCSIMigration.Spec.CSI != nil && !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.PersistentVolumeSource.CSI) {
```
Comment (sunnylovestiramisu) [inline pkg/controller/volume/attachdetach/util/util_test.go:252]: Here is this doing something weird? gotVolumeWithCSIMigration.Spec.CSI has the value I want to verify but it is not in gotVolumeWithCSIMigration.Spec.PersistentVolumeSource.CSI

Comment (msau42) [reply pkg/controller/volume/attachdetach/util/util_test.go:252]: Can you remove the `PersistentVolumeSource`? I believe when you reference promoted fields, you don't specify the type name:
https://www.geeksforgeeks.org/promoted-fields-in-golang-structure/

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 18]
```diff
@@ -0,0 +1,344 @@
...
+	} {
+		t.Run(test.desc, func(t *testing.T) {
+			plugMgr, intreeToCSITranslator, csiTranslator, pvLister, pvcLister := setup(testNodeName, t)
+			actualSpec, err := CreateVolumeSpec(test.pod.Spec.Volumes[0], test.pod, test.createNodeName, plugMgr, pvcLister, pvLister, intreeToCSITranslator, csiTranslator)
+
+			if (len(test.wantErrorMessage) > 0 && err == nil) || (err != nil && !strings.Contains(err.Error(), test.wantErrorMessage)) {
+				t.Errorf("got err %v, want err with message %v", err, test.wantErrorMessage)
+			}
+			if test.wantPersistentVolume != nil {
+				gotVolumeWithCSIMigration := *actualSpec.PersistentVolume
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:246]: check for nil actualSpec

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 17 above)
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:252]: Do you need this inner check? The higher level `spec` comparison should cover this right?

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 19]
```diff
@@ -0,0 +1,344 @@
...
+					if gotVolumeWithCSIMigration.Spec.CSI != nil && !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.PersistentVolumeSource.CSI) {
+						t.Errorf("got volume.Spec.CSI %v, want.Spec.CSI %v", gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.CSI)
+					}
+					if gotVolumeWithCSIMigration.Spec.CSI == nil {
+						t.Errorf("got volume.Spec %v, want.Spec %v", gotVolumeWithCSIMigration, test.wantPersistentVolume)
+					}
+				}
+			}
+			if test.wantVolume != nil {
+				gotVolume := *actualSpec.Volume
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:261]: nil check

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 20]
```diff
@@ -0,0 +1,344 @@
...
+	"k8s.io/client-go/kubernetes/fake"
+	utiltesting "k8s.io/client-go/util/testing"
+	"k8s.io/kubernetes/pkg/volume"
+	volumetest "k8s.io/kubernetes/pkg/volume/testing"
+)
+
+const (
+	testHostName = "test-hostname"
+	socketPath   = "/var/run/kmsplugin"
+	volumeName   = "volume-name"
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:45]: Maybe also name the variable "migratedVolume", "nonMigratedVolume" to easily match with the pvcs.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 21]
```diff
@@ -0,0 +1,344 @@
...
+)
+
+var (
+	dirOrCreate = v1.HostPathType(v1.HostPathDirectoryOrCreate)
+	nodeName    = kubetypes.NodeName(testNodeName)
+	hostPath    = &v1.HostPathVolumeSource{
+		Path: socketPath,
+		Type: &dirOrCreate,
+	}
+	objectReference  = v1.ObjectReference{Namespace: "default", Name: "migrated-pvc"}
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:57]: Also add migrated/nonMigrated to the variable names.

**Comment by msau42** [comment]
Can you update the title to reflect what the fix is doing? ie "Remove check for CSI driver running on node for CSI migration attach operations".

And maybe phrase the release note to describe the symptom that users experience, for example "Fix an issue where a CSI migrated volume may be prematurely detached when the CSI driver is not running on the node".

File: pkg/controller/volume/attachdetach/util/util_test.go (hunk 17 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:252]: For other test cases they have gotVolumeWithCSIMigration.Spec.CSI == nil, so they should skip this check.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 22]
```diff
@@ -0,0 +1,348 @@
...
+			if actualSpec == nil && (test.wantPersistentVolume != nil || test.wantVolume != nil) {
+				t.Errorf("got volume spec is nil")
+			}
+
+			if (len(test.wantErrorMessage) > 0 && err == nil) || (err != nil && !strings.Contains(err.Error(), test.wantErrorMessage)) {
+				t.Errorf("got err %v, want err with message %v", err, test.wantErrorMessage)
+			}
+
+			if test.wantPersistentVolume != nil {
+				gotVolumeWithCSIMigration := *actualSpec.PersistentVolume
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:251]: actualSpec.PersistentVolume and Volume also need nil checks.

File: pkg/controller/volume/attachdetach/util/util_test.go [hunk 23]
```diff
@@ -0,0 +1,348 @@
...
+				if gotVolumeWithCSIMigration.Name != test.wantPersistentVolume.Name {
+					t.Errorf("got volume name is %v, want volume name is %v", gotVolumeWithCSIMigration.Name, test.wantPersistentVolume.Name)
+
+				}
+				if !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec, test.wantPersistentVolume.Spec) {
+					if !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.CSI) {
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/util/util_test.go:257]: I still think this inner layer of checks is not needed.

You can use `cmp.Diff` make it easier to debug failures. 
```
                                if !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec, test.wantPersistentVolume.Spec) {
-                                       if !reflect.DeepEqual(gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.CSI) {
-                                               t.Errorf("got volume.Spec.CSI %v, want.Spec.CSI %v", gotVolumeWithCSIMigration.Spec.CSI, test.wantPersistentVolume.Spec.CSI)
-                                       }
-                                       if gotVolumeWithCSIMigration.Spec.CSI == nil {
-                                               t.Errorf("got volume.Spec %v, want.Spec %v", gotVolumeWithCSIMigration, test.wantPersistentVolume)
-                                       }
+                                       t.Errorf("unexpected volume spec got/want diff\n%s", cmp.Diff(gotVolumeWithCSIMigration.Spec, test.wantPersistentVolume.Spec))
                                }
```

Here's what I found:
```
--- FAIL: Test_CreateVolumeSpec (0.00s)
    --- FAIL: Test_CreateVolumeSpec/inline_volume_type_that_supports_csi_migration (0.00s)
        util_test.go:258: unexpected volume spec got/want diff
              v1.PersistentVolumeSpec{
                Capacity:                      nil,
                PersistentVolumeSource:        {CSI: &{Driver: "pd.csi.storage.gke.io", VolumeHandle: "projects/UNSPECIFIED/zones/UNSPECIFIED/disks/test-disk", FSType: "ext4", VolumeAttributes: {"partition": ""}, ...}},
            -   AccessModes:                   []v1.PersistentVolumeAccessMode{"ReadWriteOnce"},
            +   AccessModes:                   nil,
                ClaimRef:                      nil,
                PersistentVolumeReclaimPolicy: "",
                StorageClassName:              "",
                MountOptions:                  nil,
            -   VolumeMode:                    &"Filesystem",
            +   VolumeMode:                    nil,
                NodeAffinity:                  nil,
              }
FAIL
```

Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/util/util_test.go:257]: We need the inner check because deepEqual cannot tell the promoted structure. reflect.DeepEqual(gotVolumeWithCSIMigration.Spec, test.wantPersistentVolume.Spec) is false when the inner structure is gotVolumeWithCSIMigration.Spec.CSI and test.wantPersistentVolume.Spec.PersistentVolumeSource.CSI even when it is equal.

**Comment by msau42** [comment]
The change LGTM but I would like to see a run of the CSI Migration test suite since this change is only exercised in that code path.

**Comment by sunnylovestiramisu** [comment]
I did ``kubetest --up``, and then run the ``deploy/kubernetes/deploy-driver.sh`` in pd csi, and then run ``kubetest --test --test_args="--ginkgo.focus=gcepd --enabled-volume-drivers=gcepd"`` on the master branch change of both k/k and pd-csi-driver. 

The test failed with 
```
[FAILED] PVC Create API error: PersistentVolumeClaim "gcepd5cqd8" is invalid: spec.accessModes: Unsupported value: "ReadWriteOncePod": supported values: "ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce"
  In [It] at: test/e2e/storage/framework/volume_resource.go:307 
```

**Comment by msau42** [comment]
ReadWriteOncePod failure is expected because that is an alpha feature that is not enabled by default. The ephemeral test may need some more followup investigation, but I think the passing tests are sufficient enough to get confidence in the fix.
