### PR TITLE
Fix node conformance tests with fake registry

### LINKED ISSUE #130271: Kubelet's e2e tests need a new mechanism for private image pull tests
### What happened?

Current private image pull e2e tests for kubelet rely on hardcoded credentials to a public repo that is getting decommissioned as a part of https://github.com/kubernetes/k8s.io/issues/1469. These tests will permafail once that happens.

### What did you expect to happen?

The tests should be written in such a way that they don't depend on external infrastructure. A possible solution might be to stand up an in-cluster registry and populate it with the necessary images.

### How can we reproduce it (as minimally and precisely as possible)?

Wait for https://github.com/kubernetes/k8s.io/issues/1469 to finish and try running some of the tests that rely on the secret from https://github.com/kubernetes/kubernetes/blob/bdc15f9e19c9331fff685ea4ea264f07605a1fcb/test/e2e/common/node/runtime.go#L284-L291 like the `ImageCredentialProvider` tests.

**Node conformance** test `[sig-node] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]` is among those that will be affected.

### Anything else we need to know?

Raised by @BenTheElder in a couple places, like https://github.com/kubernetes/kubernetes/pull/128372#discussion_r1918965807

### Kubernetes version

<details>
all supported
</details>

### Cloud provider

<details>
irrelevant
</details>

### OS version

<details>

```console
--
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by stlaz**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:
This PR brings back node conformance tests that were removed in https://github.com/kubernetes/kubernetes/pull/133262

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/130271

#### Special notes for your reviewer:
The test run:
1. run the agnhost fake registry in a deployment
    1a. the registry pods use HostIP as localhost registries are trusted by containerd for insecure comms
2. label the nodes the registries run on (=> needs Serialized for these tests because of cluster-global side effects)
3. run a Pod with node selector on these nodes, the Pod has a container that requests `localhost:5000/pause` image
4. clean the labels from the nodes

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/runtime_conformance_test.go [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+						phase, err := container.GetPhase(ctx)
+						if err != nil {
+							return fmt.Errorf("failed to get pod phase: %w", err)
+						}
+						if phase != testCase.phase {
+							return fmt.Errorf("expected pod phase: %q, got: %q", testCase.phase, phase)
+						}
+						return nil
+					}
+					// The image registry is not stable, which sometimes causes the test to fail. Add retry mechanism to make this
```
Comment (drjackild) [inline test/e2e_node/runtime_conformance_test.go]: I'm not sure, is this relevant now or not, as we're using local registry instead of a cloud one.

Comment (stlaz) [reply test/e2e_node/runtime_conformance_test.go]: I would probably still leave it here

**Comment by stlaz** [comment]
/test pull-kubernetes-node-e2e-containerd
interesting, maybe a flake? Looks like the creds were missing for the pull

edit: it was a bug, the config file got deleted early

File: test/e2e/framework/registry/registry.go [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+			"auth": "%s"
+		}
+	}
+}`
+	user1creds                = "dXNlcjpwYXNzd29yZA==" // user:password
+	registryNodeSelectorValue = "kube-e2e-test-registry"
+)
+
+// SetupRegistry runs the `fake-registry-server --private` from the agnhost image.
+// The registry is run with HostPort 5000 exposed in order to allow locally-scheduled
```
Comment (haircommander) [inline test/e2e/framework/registry/registry.go:49]: can we have the registry address returned as a part of SetupRegistry? it feels weird to me the callers are hardcoding it

File: test/e2e/framework/registry/registry.go [hunk 3]
```diff
@@ -0,0 +1,212 @@
...
+	podNodes := make([]string, 0, len(pods.Items))
+	for _, pod := range pods.Items {
+		podNodes = append(podNodes, pod.Spec.NodeName)
+	}
+
+	return podNodes, nil
+}
+
+func podManifest(podTestLabel string) (*v1.Pod, error) {
+	pod, err := test.GetMinimalValidLinuxPod(api.LevelRestricted, api.MajorMinorVersion(1, 22))
```
Comment (haircommander) [inline test/e2e/framework/registry/registry.go]: any issue calling GetMinimalValidLinuxPod when this file isn't linux only?

File: test/e2e_node/runtime_conformance_test.go (hunk 1 above)
Comment (haircommander) [reply test/e2e_node/runtime_conformance_test.go]: tbh it adds a decent amount of code and if the local registry is unstable something is wrong there. I would remove this

File: test/e2e/common/node/runtime.go [hunk 4]
```diff
@@ -36,7 +41,7 @@ import (
 
 var _ = SIGDescribe("Container Runtime", func() {
 	f := framework.NewDefaultFramework("container-runtime")
-	f.NamespacePodSecurityLevel = admissionapi.LevelBaseline
+	f.NamespacePodSecurityLevel = admissionapi.LevelPrivileged // custom registry pods need HostPorts
```
Comment (haircommander) [inline test/e2e/common/node/runtime.go:43]: eventually I wonder if the custom registry can be setup as part of suite setup and reused for the tests that need it. there aren't enough tests yet so i don't think it's required but something to think about when designing the functions maybe?

File: test/e2e/framework/registry/registry.go (hunk 2 above)
Comment (stlaz) [reply test/e2e/framework/registry/registry.go:49]: It is currently a constant, but we can return it as such, yeah.

File: test/e2e/framework/registry/registry.go (hunk 3 above)
Comment (stlaz) [reply test/e2e/framework/registry/registry.go]: I am not sure what the actual result is when it's stripped off os-specific security context fields, but that's probably not an issue since we need privileged pods in the end because of the host ports.
I'll change this to non-OS specific minimal pod.

File: test/e2e/common/node/runtime.go (hunk 4 above)
Comment (stlaz) [reply test/e2e/common/node/runtime.go:43]: My original idea was to set it up so that there is the smallest amount of side effects between the tests. Even though now that we need to make the suite serial, it may not matter as much.
On the other hand, you need a properly setup framework with proper context to create a registry for your test, and ginkgo won't let you get those easily before the test starts being handled.

Some other considerations for the future - we may need to set up different registries (different ports?) or have a way for the fake registry to serve the same image under different aliases in order to test things like https://github.com/kubernetes/enhancements/issues/2535. Or perhaps we could clean up the `localhost:5000/pause` image from the nodes after each test is run with a privileged container.
Those are, however, issues to be solved in a future follow-up I think. CCing @aramase as an fyi on the list of above ideas.

**Comment by stlaz** [comment]
/retest
odd, checking if persistent

**Comment by BenTheElder** [comment]
> label the nodes the registries run on (=> needs Serialized for these tests because of cluster-global side effects)

Could we skip this and simply select those nodes by name in the test pod?

Or use a clusterIP service?

**Comment by stlaz** [comment]
> Could we skip this and simply select those nodes by name in the test pod?

We could. The current design delegates the work to scheduler in case any of the nodes were too busy to handle an additional container (should we consider deploying more than one registry).

> Or use a clusterIP service?

Not without having to configure the container runtime running on the node.

**Comment by SergeyKanzhelev** [comment]
@stlaz what is the status of this? My understanding is that the only un0answered comment is from @haircommander on the need for retry logic

File: test/e2e/common/node/runtime.go [hunk 5]
```diff
@@ -254,28 +258,53 @@ while true; do sleep 1; done
 			})
 		})
 
-		ginkgo.Context("when running a container with a new image", func() {
+		framework.Context("when running a container with a new image", framework.WithSerial(), func() {
```
Comment (SergeyKanzhelev) [inline test/e2e/common/node/runtime.go:261]: why is it serial? Can we instantiate a new registry for each test?

Comment (stlaz) [reply test/e2e/common/node/runtime.go:261]: We are instantiating a new registry for each test but we're labelling nodes. Since nodes are a cluster resource, I consider this to be a cluster-wide side effect and thus I labelled the test as serial.

Comment (BenTheElder) [reply test/e2e/common/node/runtime.go:261]: We moved from labeling nodes to running a daemonset, but it still probably needs to be serial to avoid resource conflicts due to the daemonset(s). 

We are assuming that if we run in serial the daemonset + some trivial image pull test pod will fit on any node and therefore do not have to take special care about waht node the test pod runs on.

In practice this probably works without serial, but it's harder to guarantee we won't have resource conflicts etc ..... I think the other daemonset tests are Serial

File: test/e2e/common/node/runtime.go (hunk 4 above)
Comment (drjackild) [reply test/e2e/common/node/runtime.go:43]: Btw, we already have a way to serve the same image under different aliases. You can add an image and an alias for it in [images.txt](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/fakeregistryserver/images.txt)

File: test/e2e/framework/registry/registry.go (hunk 2 above)
Comment (BenTheElder) [reply test/e2e/framework/registry/registry.go:49]: this thread is stale now?

File: test/images/.permitted-images [hunk 6]
```diff
@@ -3,7 +3,6 @@
 # We are aiming to consolidate on: registry.k8s.io/e2e-test-images/agnhost
 # The sources for which are in test/images/agnhost.
 # If agnhost is missing functionality for your tests, please reach out to SIG Testing.
-gcr.io/authenticated-image-pulling/alpine
```
Comment (BenTheElder) [inline test/images/.permitted-images:6]: 🎉

File: test/images/.permitted-images [hunk 7]
```diff
@@ -3,7 +3,6 @@
...
 gcr.io/k8s-authenticated-test/agnhost
```
Comment (BenTheElder) [inline test/images/.permitted-images:10]: TODO 😅

File: test/utils/image/manifest.go [hunk 8]
```diff
@@ -129,17 +128,12 @@ func readFromURL(url string, writer io.Writer) error {
...
-		// Eliminate GcAuthenticatedRegistry.
-		GcAuthenticatedRegistry: "gcr.io/authenticated-image-pulling",
-		PromoterE2eRegistry:     "registry.k8s.io/e2e-test-images",
-		BuildImageRegistry:      "registry.k8s.io/build-image",
-		InvalidRegistry:         "invalid.registry.k8s.io/invalid",
-		GcEtcdRegistry:          "registry.k8s.io",
-		GcRegistry:              "registry.k8s.io",
-		SigStorageRegistry:      "registry.k8s.io/sig-storage",
-		// TODO: https://github.com/kubernetes/kubernetes/issues/130271
-		// Eliminate PrivateRegistry.
```
Comment (BenTheElder) [inline test/utils/image/manifest.go:142]: This TODO still remains? The TODO above does not.

File: test/e2e/common/node/runtime.go [hunk 9]
```diff
@@ -254,28 +258,50 @@ while true; do sleep 1; done
...
+
+				registryAddress, _, err = e2eregistry.SetupRegistry(ctx, f, false)
+				framework.ExpectNoError(err)
+			})
+
+			ginkgo.AfterEach(func(ctx context.Context) {
+				if len(registryAddress) == 0 {
+					return
+				}
+				f.DeleteNamespace(ctx, f.Namespace.Name) // we need to wait for the registry to be removed and so we need to delete the whole NS early (before the actual cleanup)
```
Comment (BenTheElder) [inline test/e2e/common/node/runtime.go]: @pohly I know you've done some work in the e2e framework around this sort of thing, suggestions?

**Review by BenTheElder — COMMENTED** [review]
Thank you for working on this!
The overall approach LGTM, some minor comments.

As we discussed in slack I hope in the future we can use  https://github.com/kubernetes/kubernetes/issues/132955 to avoid the daemonset and serial ... but it's not clearly agreed yet and unclear when we'd have this functionality even if it was.

File: test/images/.permitted-images (hunk 7 above)
Comment (stlaz) [reply test/images/.permitted-images:10]: Added a TODO, I'll have a look what can be done here, though I would address that in a follow up.

File: test/utils/image/manifest.go (hunk 8 above)
Comment (stlaz) [reply test/utils/image/manifest.go:142]: Brought back the TODO comment

File: test/e2e/common/node/runtime.go (hunk 9 above)
Comment (stlaz) [reply test/e2e/common/node/runtime.go]: The framework's `AfterEach()` does not wait for the namespaces to be deleted which could cause failures deploying the registry because of nodeport reuse.

Comment (pohly) [reply test/e2e/common/node/runtime.go]: `AfterEach` is not a good way to clean up after a test. It always gets called and then needs to figure out what really needs to be done. That's probably why you added the `if len(registryAddress) == 0` check.

A better solution is to call `ginkgo.DeferCleanup(func (ctx context.Context) {....})` directly after the code which causes the need to cleanup. The callback then only runs if needed. Be careful to request a new context, the one from BeforeEach will be canceled when the callback executes.

In this case it could go after the `framework.ExpectNoError(err)`. Inside `e2eregistry.SetupRegistry` is probably not the right place for such a workaround.

File: test/e2e/common/node/runtime.go [hunk 10]
```diff
@@ -254,28 +258,47 @@ while true; do sleep 1; done
...
+			var registryAddress string
+			ginkgo.BeforeEach(func(ctx context.Context) {
+				var err error
+
+				registryAddress, _, err = e2eregistry.SetupRegistry(ctx, f, false)
+				framework.ExpectNoError(err)
+				// we need to wait for the registry to be removed and so we need to delete the whole NS ourselves
+				ginkgo.DeferCleanup(func(ctx context.Context) {
+					f.DeleteNamespace(ctx, f.Namespace.Name)
+				})
```
Comment (pohly) [inline test/e2e/common/node/runtime.go:271]: This looks good to me now.
