### PR TITLE
Fix pod object update that may cause data race

### LINKED ISSUE #116694: Mutation of a cached object in kubelet through in place resizing of pods
### What happened?

https://github.com/kubernetes/kubernetes/blob/76d351065e504e23b7962158ef0e9067b6bd96ed/pkg/kubelet/kubelet.go#L2682

mutates the pod object in place (vs creating a copy first).  That's illegal and can cause data races or potentially panics (the panic is unlikely here but I can't rule it out).

This line should be:

```
pod = updatedPod
...
kl.podManager.UpdatePod(pod)
```

This should be fixed because we might serialize the object in the middle of this from somewhere else and if the object changes midway the protobuf object we create may not be valid, leading to panics in kubelets with this gate turned on.

/sig node
/priority critical-urgent
/kind bug
/assign @vinaykul 

### What did you expect to happen?

No mutation of pod objects from within `Sync*Pod` methods (in fact no mutation of `pod` should occur in most loops).

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by vinaykul**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #116694 

#### Does this PR introduce a user-facing change? no

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @smarterclayton

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/milestone v1.27

Applying the milestone as this seems to be blocking the alpha feature and we still have an exception

**Comment by SergeyKanzhelev** [comment]
/sig node
/priority critical-urgent
/kind bug
/triage accepted

(from the linked bug)

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2700,14 +2700,16 @@ func (kl *Kubelet) handlePodResourcesResize(pod *v1.Pod) {
...
+		pod = updatedPod
 	}
 	if resizeStatus != "" {
 		// Save resize decision to checkpoint
 		if err := kl.statusManager.SetPodResizeStatus(pod.UID, resizeStatus); err != nil {
 			//TODO(vinaykul,InPlacePodVerticalScaling): Can we recover from this in some way? Investigate
 			klog.ErrorS(err, "SetPodResizeStatus failed", "pod", klog.KObj(pod))
+			return
 		}
 		pod.Status.Resize = resizeStatus
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet.go:2714]: Looking at this comment: https://github.com/kubernetes/kubernetes/pull/116706#discussion_r1140217546

`pod` is now a reference to `updatedPod` so this operates on the `pod`'s copy. Should not cause a race

Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go:2714]: maybe from code cleanless perspective keep the `updatedPod`instead of `pod` being used all the way to the `kl.podManager.UpdatePod(pod)`.

Comment (liggitt) [reply pkg/kubelet/kubelet.go:2714]: is fit ever false when resizeStatus is non-empty? if so, we'll miss the `pod = updatedPod` assignment and this will still mutate the original pod here, right?

Comment (liggitt) [reply pkg/kubelet/kubelet.go:2714]: it looks like there are return paths from canResizePod that would lead us to mutate the original pod here:

```
return false, nil, v1.PodResizeStatusInfeasible
...
return false, nil, v1.PodResizeStatusDeferred
```

Comment (vinaykul) [reply pkg/kubelet/kubelet.go]: Fixed. PTAL, thankx

**Review by spatecon — APPROVED** [review]

**Comment by cici37** [comment]
This Issue/PR has been marked as release blocker. Please have the PR merged by eod today otherwise the feature has to be reverted. For the Issue/PR owner: please have a revert/feature disable PR open today in case the fix failed to get in. Thank you! See the [announcement here](https://groups.google.com/a/kubernetes.io/g/dev/c/yzSvdfk8mo8)

-- Kubernetes 1.27 release manager

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -2695,24 +2695,28 @@ func (kl *Kubelet) handlePodResourcesResize(pod *v1.Pod) {
...
+			klog.ErrorS(err, "SetPodResizeStatus failed", "pod", klog.KObj(updatedPod))
+			return
 		}
-		pod.Status.Resize = resizeStatus
+		updatedPod.Status.Resize = resizeStatus
 	}
-	kl.podManager.UpdatePod(pod)
-	kl.statusManager.SetPodStatus(pod, pod.Status)
+	kl.podManager.UpdatePod(updatedPod)
+	kl.statusManager.SetPodStatus(updatedPod, updatedPod.Status)
```
[the remark this answers is not in the document]
Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2719]: I have modified the code to return updated pod, it looks like a fairly safe change for now. PTAL.
The implementation does not rely on quick propagation, but it is desired.

My initial approach in the KEP was to not do this in SyncPod at all and do this in [HandlePodUpdates coupled with event-based retries for Deferred resizes](https://github.com/kubernetes/enhancements/pull/686#issuecomment-490629494) (e.g. revisit Deferred resizes upon deletion. IMHO it makes sense here because there is fair chance a resize try will be successful upon after other resource-using pods departed the node vs periodic retries). IIRC there were concerns about the reliability and it was conventional/accepted for K8s to retry even when it may not change the result. We also discussed this point [during early reviews](https://github.com/kubernetes/kubernetes/pull/102884#discussion_r663160060) but opted to have a beta TODO to focus on this change, tracking issue https://github.com/kubernetes/kubernetes/issues/109547

What are your thoughts on my initial suggested approach (HandlePodUpdates + event based retries)?

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

With the caveat discussed: https://kubernetes.slack.com/archives/C0BP8PW9G/p1679443165418009

File: pkg/kubelet/kubelet.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go:2719]: Filed https://github.com/kubernetes/kubernetes/issues/116826 for addressing in the next version

[the remark this answers is not in the document]
Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2719]: > That is the root of my concern here is that you can't use podManager as a store of temporary state (the kubelet uses it as a cache of upstream sources of truth). If you need to create a store of truth for "changes that have been requested AND accepted by the kubelet" we need to create a new map to hold them, which probably involves designing this into the state model of the kubelet as I mentioned.
> 

Yes, I plan to revisit computePodResizeAction for this purpose. Another possibility is to borrow from the [original implementation of the initially approved KEP](https://github.com/kubernetes/kubernetes/pull/92127) and patch the PodStatus and proceed only upon successful patch but that has the downside of an additional call to the API server, which could get rate-limited.

**Comment by dims** [comment]
/approve

Looks like we have enough for alpha and there is a feature gate to protect things. thanks @SergeyKanzhelev for opening up a follow up issue.
