### PR TITLE
Fix issue in kubelet getMountedVolumePathListFromDisk

### LINKED ISSUE #74650: Invalid path to check in volume existence test for CSI volumes
In [`Kubelet.getMountedVolumePathListFromDisk`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/kubelet/kubelet_getters.go#L307) and [`operationExecutor.CheckVolumeExistenceOperation`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/volume/util/operationexecutor/operation_executor.go#L900), we check mount on first level directory in pod volume directories. 

It is true for many volume plugins, but not for CSI plugin which [mounts on sub-directory `mount`](https://github.com/kubernetes/kubernetes/blob/076af3d1b5cc1c368dd00f64ceefda8a87c1dfc7/pkg/volume/csi/csi_mounter.go#L75).

cc @msau42

### PR DESCRIPTION
**Pull request by jingxu97**
This PR fixes issue #74650. It adds the extra check for /mount dir under
pod volume dir. It also adds the unit test for this function

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74650

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42

File: pkg/kubelet/kubelet_getters.go [hunk 1]
```diff
@@ -331,6 +331,20 @@ func (kl *Kubelet) getMountedVolumePathListFromDisk(podUID types.UID) ([]string,
...
+
+		// This is a temporary solution for checking CSI mount path due to the extra "/mount".
+		// For CSI volumes, csiMountVolumePath is the right path to check.
+		// For volumes that are not CSI type, if this mount check returns true,
+		// it is ok to added to mountedVolumes because it also means that there are volumes exist and
+		// it is not safe to delete pod yet.
+		// We might remove this checking mount point as a condition before deleting pods since it is
+		// not reliable and the condition might be different for different types of volumes. But it first requires
+		// a reliable way to clean up volume dir. See discussion in issue #74650
+		csiMountVolumePath := filepath.Join(volumePath, "/mount")
```
Comment (msau42) [inline pkg/kubelet/kubelet_getters.go]: I think we should do this only if the volumePath is for a csi volume. We should avoid peeking into regular volume data as much as possible. 

Also add a comment that this check is still problematic for csi volumes that either: 1) don't mount or 2) bind mount in the rootfs

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by jingxu97** [comment]
@msau, comments are addressed. PTAL.

File: pkg/kubelet/kubelet_getters.go [hunk 2]
```diff
@@ -310,8 +312,23 @@ func (kl *Kubelet) getPodVolumePathListFromDisk(podUID types.UID) ([]string, err
...
+			for _, volumeDir := range volumeDirs {
+				volumes = append(volumes, filepath.Join(volumePluginPath, volumeDir))
+			}
+		} else {
+			// For CSI volumes, the mounted volume path has an extra sub path "/mount", so also add it
+			// to the list if the mounted path exists.
+			for _, volumeDir := range volumeDirs {
+				path := filepath.Join(volumePluginPath, volumeDir)
+				volumes = append(volumes, path)
+				csimountpath := filepath.Join(path, "/mount")
```
Comment (msau42) [inline pkg/kubelet/kubelet_getters.go]: Can we reuse the logic in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L84? Maybe pull it out into a public function?

File: pkg/kubelet/kubelet_getters.go [hunk 3]
```diff
@@ -310,8 +312,23 @@ func (kl *Kubelet) getPodVolumePathListFromDisk(podUID types.UID) ([]string, err
...
+		if unescapePluginName != csi.CSIPluginName {
+			for _, volumeDir := range volumeDirs {
+				volumes = append(volumes, filepath.Join(volumePluginPath, volumeDir))
+			}
+		} else {
+			// For CSI volumes, the mounted volume path has an extra sub path "/mount", so also add it
+			// to the list if the mounted path exists.
+			for _, volumeDir := range volumeDirs {
+				path := filepath.Join(volumePluginPath, volumeDir)
+				volumes = append(volumes, path)
```
Comment (msau42) [inline pkg/kubelet/kubelet_getters.go]: Why do we append this path? Then we're going to have double the entries right?

File: pkg/kubelet/kubelet_getters.go (hunk 2 above)
Comment (msau42) [reply pkg/kubelet/kubelet_getters.go]: Actually would it be possible to use mounter.GetPath() here for all plugins? Then we don't need plugin-specific logic.

File: pkg/kubelet/kubelet_getters.go (hunk 3 above)
Comment (jingxu97) [reply pkg/kubelet/kubelet_getters.go]: should remove it.

File: pkg/kubelet/kubelet_getters.go (hunk 2 above)
Comment (jingxu97) [reply pkg/kubelet/kubelet_getters.go]: to get a new mounter, it requires volume spec, and pod id etc. It will need go through the volume spec reconstruction, which is not very easy... I think.

**Comment by jingxu97** [comment]
@msau, comments are addressed. PTAL.

File: pkg/kubelet/kubelet_getters.go (hunk 2 above)
Comment (msau42) [reply pkg/kubelet/kubelet_getters.go]: Can we make a helper function out of https://github.com/kubernetes/kubernetes/blob/468af72a1547fe6c51c6f095206c1df981f8ae7a/pkg/volume/csi/csi_mounter.go#L84 that doesn't depend on mounter so that we don't have two places that define the path?

Comment (jingxu97) [reply pkg/kubelet/kubelet_getters.go:326]: where will the helper function be placed?
right now, the logic is depending on the plugin name, we define the path differently. You mean we have a helper function to contain this logic?

Comment (jingxu97) [reply pkg/kubelet/kubelet_getters.go]: ok, I made a helper function in csi_util.go. PTAL

**Comment by jingxu97** [comment]
@msau42 PTAL

**Comment by jsafrane** [comment]
Lgtm as temporary workaround, however, the final solution should include https://github.com/kubernetes/kubernetes/pull/88759 too. As mentioned here, not all CSI volumes are mounts. Just presence of the volume directory indicates that the CSI volume plugin did not finish its cleanup and TearDown / NodeUnpublish should be called. The orphan pod cleaner should not check for mounts at all.
