### PR TITLE
multiple IPv6/dual-stack endpoint fixes

### LINKED ISSUE #92965: [Failing Test] kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel)
**Which jobs are failing**:

`kind-ipv6-master-parallel (ci-kubernetes-kind-ipv6-e2e-parallel)`

**Which test(s) are failing**:

`[sig-network] Services should create endpoints for unready pods` is failing consistently.

**Since when has it been failing**:

`07-09-2020 11:39 CDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel

**Reason for failure**:

```
test/e2e/network/service.go:1979
Jul 10 05:27:25.533: expected un-ready endpoint for Service slow-terminating-unready-pod within 5m0s, stdout: 
test/e2e/network/service.go:2061
```

**Anything else we need to know**:

/cc @kubernetes/ci-signal 
/sig network
/priority critical-urgent
/milestone v1.19

### PR DESCRIPTION
**Pull request by danwinship**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes two problems with endpoints in dual-stack and single-stack IPv6 clusters:
1. Fixes #92965; EndpointSliceController was only looking at IPv4 Pod IPs during Pod updates, so it wouldn't notice when a Pod went from having no IPs to having only an IPv6 IP. (May also fix some other problems where certain Pod updates were not noticed in one or both controllers, because of the odd way they were trying to figure out whether a Pod update would result in Endpoint updates. Eg, neither controller would notice if a pod went from single-stack to dual-stack, though it's possible that never happens in practice.)
2. EndpointController now allows headless services to have IPv6 endpoints in single-stack IPv6 and dual stack clusters, as long as they specify `ipFamily: IPv6`. (EndpointSliceController already allowed this.)

However, this preserves the existing behavior (in both controllers) that "legacy" headless services (with no `IPFamily` set) are treated as IPv4-only in all clusters when `IPv6DualStack` is enabled. (Even if the cluster is single-stack IPv6.) ~I had thought we could fix this easily because I thought kube-controller-manager knew the service CIDR(s). But in fact, it usually doesn't; kcm has a `--service-cluster-ip-range` argument, but you only need to specify it if (a) you are using `--allocate-node-cidrs` and (b) your service CIDR is _inside_ the cluster CIDR so you need the Node CIDR allocator to skip over that range. (Srsly???). So anyway, most kcm's are not going to know what the default service CIDR is.~

~There is another approach we could take, which is to take advantage of the fact that the endpoint controller will, shortly after startup, learn whether `kubernetes.default` is IPv4 or IPv6, which is the same as learning whether the default service CIDR is IPv4 or IPv6. But I think we'd need to rearrange the code to ensure that we find that out before queuing any other updates, since if we got an informer notification for a legacy headless service before we got a notification for `kubernetes.default`, we wouldn't be able to process it yet.~

Given that 1.20 will fix the behavior of headless dual-stack services, it's not worth going to any further effort to improve things in 1.19.

Fixes #92965

**Does this PR introduce a user-facing change?**:
```release-note
Fixed the EndpointSliceController to correctly create endpoints for IPv6-only pods.

Fixed the EndpointController to allow IPv6 headless services, if the IPv6DualStack
feature gate is enabled, by specifying `ipFamily: IPv6` on the service. (This already
worked with the EndpointSliceController.)
```

/sig network
/priority important-soon

### CODE REVIEW

File: pkg/controller/util/endpoint/controller_utils.go [hunk 1]
```diff
@@ -164,27 +164,39 @@ func PodChanged(oldPod, newPod *v1.Pod, endpointChanged EndpointsMatch) (bool, b
 		labelsChanged = true
 	}
 
-	// If the pod's deletion timestamp is set, remove endpoint from ready address.
-	if newPod.DeletionTimestamp != oldPod.DeletionTimestamp {
+	// If the pod's deletion timestamp has been set, remove endpoint from ready address.
+	if oldPod.DeletionTimestamp == nil && newPod.DeletionTimestamp != nil {
```
Comment (aojea) [inline pkg/controller/util/endpoint/controller_utils.go:168]: just curious, it may happen that the old pod has DeletionTimestamp != nil and the new pod nil?

File: pkg/controller/util/endpoint/controller_utils.go [hunk 2]
```diff
@@ -164,27 +164,39 @@ func PodChanged(oldPod, newPod *v1.Pod, endpointChanged EndpointsMatch) (bool, b
...
 	// So for the purposes of an endpoint, a readiness change on a pod
 	// means we have a changed pod.
 	if podutil.IsPodReady(oldPod) != podutil.IsPodReady(newPod) {
 		return true, labelsChanged
 	}
-	// Convert the pod to an Endpoint, clear inert fields,
-	// and see if they are the same.
-	// TODO: Add a watcher for node changes separate from this
-	// We don't want to trigger multiple syncs at a pod level when a node changes
-	return endpointChanged(newPod, oldPod), labelsChanged
```
Comment (aojea) [inline pkg/controller/util/endpoint/controller_utils.go:182]: This was comparing the whole v1.EndpointAddress object but the `TargetRef.ResourceVersion` field, is it safe to compare only the IPs now?

File: pkg/controller/endpointslice/utils.go [hunk 3]
```diff
@@ -133,20 +120,14 @@ func getEndpointAddresses(podStatus corev1.PodStatus, service *corev1.Service) [
 
 	for _, podIP := range podStatus.PodIPs {
 		isIPv6PodIP := utilnet.IsIPv6String(podIP.IP)
-		if isIPv6PodIP == isIPv6Service(service) {
+		if isIPv6PodIP == endpointutil.IsIPv6Service(service) {
```
Comment (aojea) [inline pkg/controller/endpointslice/utils.go:123]: nit, who should have the helper functions, the endpoint or the endpointslice, the former will be deprecated by the later, right?

**Comment by aojea** [comment]
/retest
it  LGTM , minor questions only

File: pkg/controller/util/endpoint/controller_utils.go (hunk 1 above)
Comment (danwinship) [reply pkg/controller/util/endpoint/controller_utils.go:168]: No, that would imply that the pod had been un-deleted.
(FWIW, I only changed this because it meant that otherwise testing deletion had to be the last test in `Test_podChanged`, which was confusing. It could be fixed in other ways. But I believe this change is correct.)

File: pkg/controller/endpointslice/utils.go (hunk 3 above)
Comment (danwinship) [reply pkg/controller/endpointslice/utils.go:123]: `endpointutil` is shared by both

**Comment by aojea** [comment]
/test all
this will test with endpoinslices enabled by default

**Comment by aojea** [comment]
@danwinship can you update the description mentioning that this fix
https://github.com/kubernetes/kubernetes/issues/92965
The ipv6 test is working with this PR
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/91399/pull-kubernetes-e2e-kind-ipv6/1283424645415964672

**Review by hasheddan — COMMENTED** [review]
/milestone v1.19

File: pkg/controller/endpoint/endpoints_controller.go [hunk 4]
```diff
@@ -213,64 +212,43 @@ func (e *EndpointController) addPod(obj interface{}) {
...
-				NodeName: &pod.Spec.NodeName,
-				TargetRef: &v1.ObjectReference{
-					Kind:            "Pod",
-					Namespace:       pod.ObjectMeta.Namespace,
-					Name:            pod.ObjectMeta.Name,
-					UID:             pod.ObjectMeta.UID,
-					ResourceVersion: pod.ObjectMeta.ResourceVersion,
-				}}, nil
+		// In a legacy cluster, the pod IP is guaranteed to be usable
+		endpointIP = pod.Status.PodIP
```
Comment (robscott) [inline pkg/controller/endpoint/endpoints_controller.go:219]: Well done, this is a great simplification.

File: pkg/controller/endpoint/endpoints_controller_test.go [hunk 5]
```diff
@@ -1102,97 +1106,219 @@ func TestShouldPodBeInEndpoints(t *testing.T) {
...
-		expectError        bool
-		enableDualStackPod bool
+		name string
+
+		enableDualStack bool
+		ipFamilies      []v1.IPFamily
 
 		service v1.Service
+
+		expectedEndPointFamily v1.IPFamily
```
Comment (robscott) [inline pkg/controller/endpoint/endpoints_controller_test.go:1122]: Nit: Usually we would use `Endpoint` not `EndPoint`

File: pkg/controller/util/endpoint/controller_utils_test.go [hunk 6]
```diff
@@ -499,3 +499,165 @@ func BenchmarkGetPodServiceMemberships(b *testing.B) {
 		}
 	}
 }
+
+func Test_podChanged(t *testing.T) {
```
Comment (robscott) [inline pkg/controller/util/endpoint/controller_utils_test.go:503]: I think this function might be easier to understand and less error prone if it used test cases and a modifier function like https://github.com/kubernetes/kubernetes/pull/93089. I know I ran into some significant bugs in the previous test implementation like this where things were passing for reasons that were not intended.

File: pkg/controller/util/endpoint/controller_utils.go [hunk 7]
```diff
@@ -164,27 +164,39 @@ func PodChanged(oldPod, newPod *v1.Pod, endpointChanged EndpointsMatch) (bool, b
...
+
+	// Check if the pod IPs have changed
+	if len(oldPod.Status.PodIPs) != len(newPod.Status.PodIPs) {
+		return true, labelsChanged
+	}
+	for i := range oldPod.Status.PodIPs {
+		if oldPod.Status.PodIPs[i].IP != newPod.Status.PodIPs[i].IP {
+			return true, labelsChanged
+		}
+	}
```
Comment (robscott) [inline pkg/controller/util/endpoint/controller_utils.go:188]: This has the unfortunate consequence of triggering a resync for a IPv4 Service if a Pod's IPv6 address changes. Is there anyway we could avoid that without having access to the Service? I'm thinking this would be a relatively rare occurrence so probably not be a big deal.

**Review by robscott — COMMENTED** [review]
Thanks for your work on this! There's a lot of great cleanup and simplification here. Given the increased scope of this PR I think you'll want to update the release note, commit message, and PR title.

File: pkg/controller/util/endpoint/controller_utils.go (hunk 7 above)
Comment (aojea) [reply pkg/controller/util/endpoint/controller_utils.go:188]: indeed it should not be a normal behavior that a pod  changes only one IP, maybe the pod restarts and acquires the same for one family and not for the other? nevertheless it seems safer to resync than trying to optimize

**Comment by hasheddan** [comment]
@danwinship @robscott @aojea any updates on progress here?

**Comment by robscott** [comment]
Thanks!

/lgtm
/assign @freehan

**Comment by hasheddan** [comment]
`pull-kubernetes-e2e-gce-device-plugin-gpu` is not required so we just need approval here

/cc @thockin @bowei

File: pkg/controller/util/endpoint/controller_utils.go (hunk 1 above)
Comment (danwinship) [reply pkg/controller/util/endpoint/controller_utils.go]: (Rob's suggestion to rewrite the test with a modify func ended up making this moot, so I reverted this change.)
