### PR TITLE
Fix SchedulerPredictes resources test

### LINKED ISSUE #27115: [k8s.io] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance] {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1455/

Failed: [k8s.io] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:372
Not scheduled Pods: []api.Pod(nil)
Expected
    <int>: 0
to equal
    <int>: 1
```

### PR DESCRIPTION
**Pull request by gmarek**
Fix #27115 (the part that's not a dupe).

cc @fejta

### CODE REVIEW

File: test/e2e/scheduler_predicates.go [hunk 1]
```diff
@@ -297,7 +297,7 @@ var _ = framework.KubeDescribe("SchedulerPredicates [Serial]", func() {
 		framework.ExpectNoError(err)
 		for _, pod := range pods.Items {
 			_, found := nodeToCapacityMap[pod.Spec.NodeName]
-			if found && pod.Status.Phase == api.PodRunning {
+			if found && pod.Status.Phase != api.PodSucceeded && pod.Status.Phase != api.PodFailed {
```
Comment (wojtek-t) [inline test/e2e/scheduler_predicates.go]: How does it fix the problem? In what state the pod was so that it helps? Was it pending?

Comment (gmarek) [inline test/e2e/scheduler_predicates.go]: It was pending. The problem was that after reboot test static Pods for fluentd and kube-proxy were created, but weren't running before the test started, so it didn't accounted resources allocated for them.

**Comment by wojtek-t** [comment]
LGTM - thanks
