### PR TITLE
kubelet: Handle UID reuse in pod worker

### LINKED ISSUE #104648: 1.22 regression: removing and recreating static pod manifest leaves pod in error state
#### What happened:

* Started a 1.22 cluster
* Added a static pod manifest
* Observed the pod run successfully
* Removed and recreated the pod manifest
* Observed the pod enter an error state and never restart successfully

#### What you expected to happen:

For the pod to be re-run successfully (as in previous releases)

#### How to reproduce it (as minimally and precisely as possible):

```
# start a cluster
hack/local-up-cluster.sh

# create a static pod
echo '
kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo $RANDOM; sleep 100000"]
' > mypod.yaml

sudo cp mypod.yaml /var/run/kubernetes/static-pods/

# wait until the pod is running
watch kubectl get pods -n default

# remove and recreate the static pod
sudo rm /var/run/kubernetes/static-pods/mypod.yaml
sudo cp mypod.yaml /var/run/kubernetes/static-pods/

# observe the pod remain in an error state
watch kubectl get pods -n default
```

#### Anything else we need to know?:

Bisected to 3eadd1a9ead7a009a9abfbd603a5efd0560473cc (https://github.com/kubernetes/kubernetes/pull/102344)

Broken in 1.22, works in 1.21 and previous versions.

/sig node
cc @smarterclayton @bobbypage @rphillips

### PR DESCRIPTION
**Pull request by smarterclayton**
If a pod is killed (no longer wanted) and then a subsequent create/add/update event is seen in the pod worker, assume that a pod UID was reused (as it could be in static pods) and have the next SyncKnownPods after the pod terminates remove the worker history so that the config loop can restart the static pod, as well as return to the caller the fact that this termination was not final.
    

1. If the pod worker sees updates KILL -> CREATE it sets a flag on the worker status restartRequested = true
2. When SyncKnownPods runs it reports any terminated worker with that flag as TemporarilyTerminatedWork
3. The pod housekeeping loop (which reconciles the pod worker with the config state) checks to see which pods were terminated but may need restart (TemporarilyTerminatedWork) during the sync, and starts them if they are not terminal (aka desired and admitted)

A pod that restarts this way will wait at most housekeeping loop period (2s) between being terminated and starting again.

/kind bug
/sig node

Fixes #104648

TODO:
* [ ] verifying this fixes the race

```release-note
Fix a 1.22 regression when a static pod file is deleted and recreated while using a fixed UID, the pod was not properly restarted.
```

```docs

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
In theory this fixes the problem but you have to wait for a reconcile loop of ~90s.  A slightly more complex impl might queue the next pod.  I'll take a look at that.

Ideally SyncKnownPods would be able to restart workers, but SyncKnownPods doesn't get passed "the pods the pod wokrer should know about" today.  It needs to be "the admitted pods that should be running" which is a subset of what is in the pod manager.

**Comment by smarterclayton** [comment]
Ok, after thinking through this some more I'm fairly convinced this is safe.  Builds on top of #104817 (which renames a bit of the admission logic):

1. If the pod worker sees updates `KILL -> CREATE` it sets a flag on the worker status `restartRequested = true`
2. When `SyncKnownPods` runs it reports any terminated worker with that flag as `TemporarilyTerminatedWork`
3. The pod housekeeping loop (which reconciles the pod worker with the config state) checks to see which pods were terminated but may need restart during the sync, and starts them if they are not terminal (aka desired and admitted)

A pod that restarts this way will wait at most `housekeeping loop period` (2s) between being terminated and starting again.

File: pkg/kubelet/pod_workers.go [hunk 1]
```diff
@@ -977,12 +999,16 @@ func (p *podWorkers) SyncKnownPods(desiredPods []*v1.Pod) map[types.UID]PodWorkT
 
 	p.podsSynced = true
 	for uid, status := range p.podSyncStatuses {
-		if _, exists := known[uid]; !exists {
+		if _, exists := known[uid]; !exists || status.restartRequested {
```
Comment (249043822) [inline pkg/kubelet/pod_workers.go:1002]: Is it safe to removeTerminatedWorker here while status.restartRequested being set? After removeTerminatedWorker, the new podworker would be run, but the old podworker can be still in terminating, two goroutines may share the data struct like p.podUpdates[uid] and p.lastUndeliveredWorkUpdate[pod.UID].  I'm afraid there may be hidden deadlocks

Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:1002]: removeTerminatedWorker only removes if the worker is actually terminated.

**Comment by rphillips** [comment]
The containerStatus is going into Waiting state. We need to modify checkMirrorPodRunning to see if it's waiting and try again.

https://github.com/kubernetes/kubernetes/blob/5d7cda1e6b438d9f4becd53c9a812f4f859c2724/test/e2e_node/mirror_pod_test.go#L251

**Comment by rphillips** [comment]
Locally testing:
```
diff --git a/test/e2e_node/mirror_pod_test.go b/test/e2e_node/mirror_pod_test.go
index 99262fdf3b6..759eb63552b 100644
--- a/test/e2e_node/mirror_pod_test.go
+++ b/test/e2e_node/mirror_pod_test.go
@@ -30,6 +30,7 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/types"
 	"k8s.io/apimachinery/pkg/util/uuid"
+	"k8s.io/apimachinery/pkg/util/wait"
 	clientset "k8s.io/client-go/kubernetes"
 	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
 	"k8s.io/kubernetes/test/e2e/framework"
@@ -240,17 +241,29 @@ func checkMirrorPodDisappear(cl clientset.Interface, name, namespace string) err
 }
 
 func checkMirrorPodRunning(cl clientset.Interface, name, namespace string) error {
-	pod, err := cl.CoreV1().Pods(namespace).Get(context.TODO(), name, metav1.GetOptions{})
-	if err != nil {
-		return fmt.Errorf("expected the mirror pod %q to appear: %v", name, err)
-	}
-	if pod.Status.Phase != v1.PodRunning {
-		return fmt.Errorf("expected the mirror pod %q to be running, got %q", name, pod.Status.Phase)
-	}
-	for i := range pod.Status.ContainerStatuses {
-		if pod.Status.ContainerStatuses[i].State.Running == nil {
-			return fmt.Errorf("expected the mirror pod %q with container %q to be running", name, pod.Status.ContainerStatuses[i].Name)
+	var pod *v1.Pod
+	var err error
+	err = wait.PollImmediate(2*time.Second, 2*time.Minute, func() (bool, error) {
+		pod, err = cl.CoreV1().Pods(namespace).Get(context.TODO(), name, metav1.GetOptions{})
+		if err != nil {
+			return false, fmt.Errorf("expected the mirror pod %q to appear: %v", name, err)
+		}
+		if pod.Status.Phase != v1.PodRunning {
+			return false, fmt.Errorf("expected the mirror pod %q to be running, got %q", name, pod.Status.Phase)
+		}
+		for i := range pod.Status.ContainerStatuses {
+			if pod.Status.ContainerStatuses[i].State.Waiting != nil {
+				// retry if pod is in waiting state
+				return false, nil
+			}
+			if pod.Status.ContainerStatuses[i].State.Running == nil {
+				return false, fmt.Errorf("expected the mirror pod %q with container %q to be running", name, pod.Status.ContainerStatuses[i].Name)
+			}
 		}
+		return true, nil
+	})
+	if err != nil {
+		return err
 	}
 	return validateMirrorPod(cl, pod)
 }
```

**Comment by rphillips** [comment]
Looks like it works locally. @smarterclayton there is a github patch [here](https://github.com/kubernetes/kubernetes/commit/39197b4ee025260296a51d0af94e2086187010e2), or you can copy in my change.

**Comment by ehashman** [comment]
/hold

to prevent accidental merging, want to give @Random-Liu a chance to review

File: pkg/kubelet/pod_workers.go [hunk 2]
```diff
@@ -99,6 +99,10 @@ const (
 	// TerminatedPodWork indicates the pod is stopped, can have no more running
 	// containers, and any foreground cleanup can be executed.
 	TerminatedPodWork
+	// TemporarilyTerminatedPodWork is the same as TerminatedPodWork, but indicates
+	// that a create update was delivered AFTER the pod was terminated, indicating
+	// that the pod may have been recreated with the same UID.
+	TemporarilyTerminatedPodWork
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:105]: Comment above on L89 needs to be updated... I find this name a little confusing, given the context in which this happens perhaps "RecreatePodWork" or "RestartedPodWork" would be better?

File: test/e2e_node/mirror_pod_test.go [hunk 3]
```diff
@@ -133,6 +134,60 @@ var _ = SIGDescribe("MirrorPod", func() {
...
+			framework.ExpectNoError(err)
+
+			ginkgo.By("recreate the file")
+			err = createStaticPod(podPath, staticPodName, ns,
+				imageutils.GetE2EImage(imageutils.Nginx), v1.RestartPolicyAlways)
+			framework.ExpectNoError(err)
+
+			ginkgo.By("mirror pod should restart with count 1")
+			gomega.Eventually(func() error {
+				return checkMirrorPodRunningWithRestartCount(2*time.Second, 2*time.Minute, f.ClientSet, mirrorPodName, ns, 1)
```
Comment (ehashman) [inline test/e2e_node/mirror_pod_test.go:179]: I don't think we need to wait for 2 minutes for the test to time out @rphillips, I consistently saw the failure after ~30s (maybe a minute would be safer)

This is a nit though

**Review by ehashman — COMMENTED** [review]
Generally LGTM, left a couple small comments

**Comment by ehashman** [comment]
Data in https://github.com/kubernetes/kubernetes/pull/104924 and https://github.com/kubernetes/kubernetes/pull/104919 looks good, I'm comfortable with merging. Still working on adding one more test case for a manually set UID, we could merge that after.

File: pkg/kubelet/pod_workers.go (hunk 2 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:105]: There is no guarantee of restart though, and technically to the kubelet is a different pod (so it's not a restart).  RecreatePodWork feels like it is implying that the pod worker wants to restart the pod.  `TerminatedWithRecreatePodWork` might be clearer.  I want to preserve that the pod is definitely stopped at the moment and will not restart without intervention.  This enum is a bit tricky though - I might create another enum that is similar but clearer.

**Comment by smarterclayton** [comment]
/retest

I'll bundle elana's review comments along with the next push (waiting for other comments)

**Comment by rphillips** [comment]
@smarterclayton the node-kubelet-serial job is broken; it is not blocking this PR.

File: test/e2e_node/mirror_pod_test.go [hunk 4]
```diff
@@ -133,6 +134,60 @@ var _ = SIGDescribe("MirrorPod", func() {
...
+	ginkgo.Context("when create a mirror pod without changes ", func() {
+		var ns, podPath, staticPodName, mirrorPodName string
+		ginkgo.BeforeEach(func() {
+		})
+		/*
+			Release: v1.23
+			Testname: Mirror Pod, recreate
+			Description: When a static pod's manifest is removed and readded, the mirror pod MUST successfully recreate. Create the static pod, verify it is running, remove its manifest and then add it back, and verify the static pod runs again.
+		*/
+		ginkgo.It("should successfully recreate when file is removed and recreated [NodeConformance]", func() {
```
Comment (gjkim42) [inline test/e2e_node/mirror_pod_test.go:152]: What happens if the config file is removed out and recreated multiple times in rapid succession?
Do we need to test that?

Comment (rphillips) [reply test/e2e_node/mirror_pod_test.go:152]: I put a loop around the create/delete of the static pod locally and it works. We can followup with a separate PR to increase the test coverage.

File: pkg/kubelet/kubelet_pods.go [hunk 5]
```diff
@@ -1171,6 +1188,32 @@ func (kl *Kubelet) HandlePodCleanups() error {
...
+
+	// If two pods with the same UID are observed in rapid succession, we need to
+	// resynchronize the pod worker after the first pod completes and decide whether
+	// to restart the pod. This happens last to avoid confusing the desired state
+	// in other components and to increase the likelihood transient OS failures during
+	// container start are mitigated. In general only static pods will ever reuse UIDs
+	// since the apiserver uses randomly generated UUIDv4 UIDs with a very low
+	// probability of collision.
+	for uid := range restartablePods {
+		pod, ok := allPodsByUID[uid]
```
Comment (derekwaynecarr) [inline pkg/kubelet/kubelet_pods.go:1200]: i am trying to work this logic backward.  in this scenario, we have `workingPods` list that contains two discrete pods with the same uid, right?  we then map pods by uid in the `allPodsByUID` list, but it's not clear which pod in the `workingPods` list wins in that mapping, right?  am i missing something?

File: pkg/kubelet/kubelet_pods.go [hunk 6]
```diff
@@ -1171,6 +1188,32 @@ func (kl *Kubelet) HandlePodCleanups() error {
...
+			continue
+		}
+		if kl.isAdmittedPodTerminal(pod) {
+			klog.V(3).InfoS("Pod is restartable after termination due to UID reuse, but pod phase is terminal", "pod", klog.KObj(pod), "podUID", pod.UID)
+			continue
+		}
+		start := kl.clock.Now()
+		mirrorPod, _ := kl.podManager.GetMirrorPodByPod(pod)
+		klog.V(3).InfoS("Pod is restartable after termination due to UID reuse", "pod", klog.KObj(pod), "podUID", pod.UID)
+		kl.dispatchWork(pod, kubetypes.SyncPodCreate, mirrorPod, start)
```
Comment (derekwaynecarr) [inline pkg/kubelet/kubelet_pods.go:1211]: this basically recreates the HandlePodAdditions work, can we have the shared piece call to a common internal helper?

File: pkg/kubelet/pod_workers.go [hunk 7]
```diff
@@ -254,6 +274,11 @@ type podSyncStatus struct {
 	// to remove the pod. A terminal pod (Succeeded/Failed) will have
 	// termination status until the pod is deleted.
 	finished bool
+	// restartRequested is true if the pod worker was informed the pod is
+	// expected to exist (update type of create, update, or sync) after
+	// it has been killed. When known pods are synced, any pod that is
+	// terminated and has restartRequested will have its history cleared.
+	restartRequested bool
```
Comment (derekwaynecarr) [inline pkg/kubelet/pod_workers.go:281]: i understand the approach taken here, i am wondering if its better to make config sources pod worker aware?    for example, could the config source peek at the list of pod workers and know there is a pod with a conflicting uid and wait at that moment to dispatch the HandlePodAddition until the pod worker was known terminal.

File: pkg/kubelet/pod_workers.go [hunk 8]
```diff
@@ -514,6 +539,19 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
...
 	}
 
+	// if an update is received that implies the pod should be running, but we are already terminating a pod by
+	// that UID, assume that two pods with the same UID were created in close temporal proximity (usually static
+	// pod but it's possible for an apiserver to extremely rarely do something similar) - flag the sync status
+	// to indicate that after the pod terminates it should be reset to "not running" to allow a subsequent add/update
+	// to start the pod worker again
+	if status.IsTerminationRequested() {
+		if options.UpdateType == kubetypes.SyncPodCreate {
+			status.restartRequested = true
```
Comment (derekwaynecarr) [inline pkg/kubelet/pod_workers.go:549]: does this ever need to transition back to false?

File: pkg/kubelet/pod_workers.go (hunk 1 above)
Comment (derekwaynecarr) [reply pkg/kubelet/pod_workers.go:1018]: so the restartRequested knob on status will ensure that the worker is terminated, and the status mapping is then cleared for that pod uid, so restartRequested is a one-way flag and we dont need to reset state on it ever.  ignore my earlier comment/question.

File: pkg/kubelet/pod_workers.go (hunk 2 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go]: In the latest commit.

**Review by derekwaynecarr — COMMENTED** [review]
I have a question about the workingPods -> allPodsByUID case, but will investigate that myself a little more deeply.  I do wonder if an alternative approach of letting the config source peek into the list of pods under management by uid would be simpler.  If we had an existing pod under management with a conflicting UID observed during HandlePodAddition, we could possibly have sent back a conflict that would result in basically asking it to requeue at a later time?

File: pkg/kubelet/kubelet_pods.go (hunk 5 above)
Comment (derekwaynecarr) [reply pkg/kubelet/kubelet_pods.go:1200]: ignore my comment here, the HandlePodAdditions step will result in the most recent static pod being present in the pod manager for that uid.

File: pkg/kubelet/kubelet_pods.go (hunk 6 above)
Comment (derekwaynecarr) [reply pkg/kubelet/kubelet_pods.go:1211]: spoke with @smarterclayton about the alternative option of having HandlePodAdditions send back a conflict response when it gets an Add event for a pod that exists under management with the same uid.  There are other complications around that flow for how to best handle requeue that I don't want to block this PR around versus getting back to a functional state.  I think this is my only nit that would like to address so that `HandlePodAdditions` and this area delegate to a common code path that couples dispatchWork and probes together.

Comment (smarterclayton) [reply pkg/kubelet/kubelet_pods.go:1211]: I would say that the pod worker owns "what is the kubelet doing" and HandlePodAdditions is delivering incremental changes to the pod worker, so I was going to try to minimize what HandlePodAddition does (for better or worse, pod housekeeping is the resync between desired state and actual state).  I *think* that any code that would need to be shared by handle pod addition (which controls admission) and housekeeping (which controls resync of the various loops) should instead live in pod worker, since pod worker owns pod lifecycle.  The probe manager was the only code today, and I wanted to move probe manager addition under pod worker, not outside.  Having a shared function there would actually confuse things a bit more - because I want there to be no shared "make the stuff aware of the start of a pod" (that's pod worker's job)

Comment (derekwaynecarr) [reply pkg/kubelet/kubelet_pods.go:1211]: fair enough.

**Review by derekwaynecarr — COMMENTED** [review]
/lgtm
/approve

**Comment by rphillips** [comment]
TestCustomResourceCascadingDeletion flake in pull-kubernetes-integration

/test pull-kubernetes-integration
