### PR TITLE
Convert resource group name in Azure provider ID to lower cases

### LINKED ISSUE #71994: Azure node providerID for VMSS instances has inconsistent case
**What happened**:

```
sylvain@ubuntu-1604-dev:~/gopath/src/k8s.io/autoscaler/cluster-autoscaler[azure-zones]$ kubectl --context=k8s1-euw-sandbox --namespace=kube-system get nodes -o json | jq .items[].spec.providerID
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/K8S1-EUW-SANDBOX-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s1-euw-sandbox-agentzone3-vmss/virtualMachines/68"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-0"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-1"
"azure:///subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/k8s1-EUW-sandbox-RG/providers/Microsoft.Compute/virtualMachines/k8s1-euw-sandbox-master-2"
```

**What you expected to happen**:

I expected the porviderID of my `virtualMachineScaleSets` instance to have the resourceGroups part in the same case as the `virtualMachines`, i.e.: `K8S1-EUW-SANDBOX-RG` -> `k8s1-EUW-sandbox-RG`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

This inconsistency breaks the cluster-autoscaler.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.2
- Cloud provider or hardware configuration: Azure

/kind bug

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

The resource group name in Azure VM's ID may be in different cases from time to time. This would cause the node's providerID are also in different cases.

While it's still working, this different cases issue may introduce troubles for external components that are dpending on providerID (e.g. cluster autoscaler).

This PR converts the resource group name in Azure provider ID to lower cases, so that all nodes' providerID are still in same cases in such case.

**Which issue(s) this PR fixes**:

Fixes #71994

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The resource group name in Azure providerID is not converted to lower cases.
```

/sig azure
/kind bug
/priority critical-urgent
/milestone v1.14

### CODE REVIEW

File: pkg/cloudprovider/providers/azure/azure_standard.go [hunk 1]
```diff
@@ -339,7 +339,14 @@ func (as *availabilitySet) GetInstanceIDByNodeName(name string) (string, error)
 			return "", err
 		}
 	}
-	return *machine.ID, nil
+
+	resourceID := *machine.ID
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_standard.go]: what about write like this:
```
return convertResourceGroupNameToLower(*machine.ID)
```

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 2]
```diff
@@ -185,7 +185,13 @@ func (ss *scaleSet) GetInstanceIDByNodeName(name string) (string, error) {
 		return "", err
 	}
 
-	return *vm.ID, nil
+	resourceID := *vm.ID
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]:
```
return convertResourceGroupNameToLower(*vm.ID)
```

File: pkg/cloudprovider/providers/azure/azure_wrap.go [hunk 3]
```diff
@@ -303,3 +304,14 @@ func (az *Cloud) IsNodeUnmanaged(nodeName string) (bool, error) {
 func (az *Cloud) IsNodeUnmanagedByProviderID(providerID string) bool {
 	return !azureNodeProviderIDRE.Match([]byte(providerID))
 }
+
+// convertResourceGroupNameToLower converts the resource group name in the resource ID to be lowered.
+func convertResourceGroupNameToLower(resourceID string) (string, error) {
+	matches := azureResourceGroupNameRE.FindStringSubmatch(resourceID)
+	if len(matches) != 2 {
+		return "", fmt.Errorf("%q isn't in Azure resource ID format", resourceID)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_wrap.go]: also print out the correct format as `azureResourceGroupNameRE`

File: pkg/cloudprovider/providers/azure/azure_standard.go [hunk 4]
```diff
@@ -70,7 +70,7 @@ func (az *Cloud) getStandardMachineID(resourceGroup, machineName string) string
 	return fmt.Sprintf(
 		machineIDTemplate,
 		az.SubscriptionID,
-		resourceGroup,
+		strings.ToLower(resourceGroup),
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_standard.go]: what about the below function, are you going to convert to lower case?
```
func (az *Cloud) getAvailabilitySetID(resourceGroup, availabilitySetName string) string {
	return fmt.Sprintf(
		availabilitySetIDTemplate,
		az.SubscriptionID,
		resourceGroup,
		availabilitySetName)
}
```

**Review by andyzhangx — COMMENTED** [review]
there are other functions like `getFrontendIPConfigID`, `getBackendPoolID`, especially `getFrontendIPConfigID` func since `az.ResourceGroup` is read from `azure.json` config file, it's controlled by user config, could be upper case.
```
func (az *Cloud) getFrontendIPConfigID(lbName, fipConfigName string) string {
	return fmt.Sprintf(
		frontendIPConfigIDTemplate,
		az.SubscriptionID,
		az.ResourceGroup,
		lbName,
		fipConfigName)
}
```

**Comment by feiskyer** [comment]
> there are other functions like getFrontendIPConfigID, getBackendPoolID, especially getFrontendIPConfigID func since az.ResourceGroup is read from azure.json config file, it's controlled by user config, could be upper case.

Other IDs are used only internally, hence it's ok of any cases. Only exposed providerID is required for conversion.

File: pkg/cloudprovider/providers/azure/azure_standard.go (hunk 4 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_standard.go]: Conversion is not needed for other IDs, only providerID should be handled.

File: pkg/cloudprovider/providers/azure/azure_standard.go (hunk 1 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_standard.go]: let's add a log here for clear

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 2 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: add an error log here

Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: then add this log into function `convertResourceGroupNameToLower`?

**Review by andyzhangx — APPROVED** [review]
/lgtm
