### PR TITLE
Ensure kubernetes master is properly tainted in GCE.

### LINKED ISSUE #78147: GCE master missing master taint.
**What happened**:
Created a daemonset ala https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ but missing the master toleration. The created pods are running on every node, including the master. 

**What you expected to happen**:
Lacking the master toleration, I would expect there to be no pod from the daemonset running on the master. Realized the master Node is missing the master taint.

**How to reproduce it (as minimally and precisely as possible)**:
Created a daemonset on GCE with no tolerations. (You may need to set the priorityClassName: system-cluster-critical)

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cheftako**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ensures that the node-role.kubernetes.io/master taint is applied to the master with NoSchedule.

**Which issue(s) this PR fixes**: 
Fixes #78147

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Ensures that the node-role.kubernetes.io/master taint is applied to the master with NoSchedule on GCE.
```

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -742,6 +742,7 @@ function construct-linux-kubelet-flags {
 
   if [[ "${master}" == "true" ]]; then
     flags+=" ${MASTER_KUBELET_TEST_ARGS:-}"
+    flags+=" --register-with-taints=node-role.kubernetes.io/master=:NoSchedule"
```
Comment (mtaufen) [inline cluster/gce/util.sh]: This should probably be in the if statement just below, since it doesn't make sense to add the taints unless we're using a registered kubelet for the control plane.

Comment (cheftako) [reply cluster/gce/util.sh]: Fixed

File: cluster/gce/util.sh [hunk 2]
```diff
@@ -746,6 +746,7 @@ function construct-linux-kubelet-flags {
       #TODO(mikedanese): allow static pods to start before creating a client
       #flags+=" --bootstrap-kubeconfig=/var/lib/kubelet/bootstrap-kubeconfig"
       #flags+=" --kubeconfig=/var/lib/kubelet/kubeconfig"
+      flags+=" --register-with-taints=node-role.kubernetes.io/master=:NoSchedule"
```
Comment (mtaufen) [inline cluster/gce/util.sh]: I think it should just be `flags+=" --register-with-taints=node-role.kubernetes.io/master:NoSchedule"` (omit the final equals sign, just `:` instead of `=:`).

Comment (mtaufen) [reply cluster/gce/util.sh]: Oh nevermind, you have an empty value. That's confusing lol.
