### PR TITLE
Removed taint check as DaemonSet tolerates default taints. 

### LINKED ISSUE #68857: Failing Test : [sig-apps] daemonset-upgrade
### Failing Job
---
[sig-release-master-upgrade multiple upgrade/downgrade tests](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#Summary)

### Gubernator Logs
---
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-master/1776
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4923
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2477
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/944
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster-parallel/4244
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1661

### Error
---
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:203
May 9 15:57:39.163: Unexpected no endpoints return
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:213

### Triage
---
This feels similar to issues resolved in master over the past weeks by SIG Autoscaling around HPA and metrics server.  Could it be that something needs backported, perhaps the use of the new metrics server image?  Or is there a latent and genuine incompatibility here?

It wasn't pursued aggressively previously as the symptom overlapped with multiple other ones being worked in master.  Now that they're resolved and this issue has persisted, this is likely a release blocker.

/kind bug
/priority failing-test
/priority critical-urgent
/sig apps
@kubernetes/sig-apps-bugs 
@kubernetes/sig-autoscaling-bugs 
/assign @mattfarina 
/cc @prydonius @kow3ns 
/milestone v1.12

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68857 

**Release note**:
```release-note
None
```

### CODE REVIEW

File: test/e2e/upgrades/apps/daemonsets.go [hunk 1]
```diff
@@ -118,22 +122,49 @@ func (t *DaemonSetUpgradeTest) validateRunningDaemonSet(f *framework.Framework)
...
-		if len(node.Spec.Taints) == 0 {
-			nodeNames = append(nodeNames, node.Name)
-		} else {
-			framework.Logf("Node %v not expected to have DaemonSet pod, has taints %v", node.Name, node.Spec.Taints)
+		if !canScheduleOnNode(node, ds) {
+			framework.Logf("DaemonSet pods can't schedule to node %s, skip checking this node", node.Name)
+			continue
 		}
+
+		nodeNames = append(nodeNames, node.Name)
```
Comment (timothysc) [inline test/e2e/upgrades/apps/daemonsets.go]: b/c e2e's can be run in the wild w/varying policy shouldn't there be a check for >=1 node otherwise error?

File: test/e2e/upgrades/apps/daemonsets.go [hunk 2]
```diff
@@ -118,22 +122,49 @@ func (t *DaemonSetUpgradeTest) validateRunningDaemonSet(f *framework.Framework)
...
+	return newPod
+}
+
+func canScheduleOnNode(node v1.Node, ds *extensions.DaemonSet) bool {
+	newPod := newPod(ds, node.Name)
+	nodeInfo := schedulercache.NewNodeInfo()
+	nodeInfo.SetNode(&node)
+	fit, _, err := daemon.Predicates(newPod, nodeInfo)
+	if err != nil {
+		framework.Failf("Can't test DaemonSet predicates for node %s: %v", node.Name, err)
```
Comment (neolit123) [inline test/e2e/upgrades/apps/daemonsets.go]: `Failf()` should start with lowercase.

**Review by janetkuo — COMMENTED** [review]
From discussion with @enisoc we both agree that upgrade tests are meant for making sure user expectations are met after upgrades. Therefore, upgrade tests should avoid including implementation details such as `Predicates()`. 

IIRC DaemonSet tolerates all default taints added to the clusters. Therefore, instead of checking `len(taints)`, we could just check if DaemonSet pods are scheduled on all nodes. 

This test might be broken in some special test environments, if nodes are tainted in a way that DaemonSet won't schedule pods on them. We could hard-code a list of taints that DaemonSet won't schedule on nodes and give clear error message when the test fails, to indicate that the failure might be related to test setup of node taints.

File: test/e2e/upgrades/apps/daemonsets.go [hunk 3]
```diff
@@ -126,11 +126,8 @@ func checkRunningOnAllNodes(f *framework.Framework, namespace string, selector m
 
 	nodeNames := make([]string, 0)
 	for _, node := range nodeList.Items {
-		if len(node.Spec.Taints) == 0 {
-			nodeNames = append(nodeNames, node.Name)
-		} else {
-			framework.Logf("Node %v not expected to have DaemonSet pod, has taints %v", node.Name, node.Spec.Taints)
-		}
+		// DaemonSet Pods are expected to run on all the nodes in e2e.
+		nodeNames = append(nodeNames, node.Name)
```
Comment (janetkuo) [inline test/e2e/upgrades/apps/daemonsets.go]: Would you also print node taints when the test fails?

**Review by janetkuo — APPROVED** [review]

File: test/e2e/upgrades/apps/daemonsets.go (hunk 3 above)
Comment (k82cn) [reply test/e2e/upgrades/apps/daemonsets.go]: done, give log when we ignore taints on nodes.

**Review by timothysc — APPROVED** [review]
/lgtm

File: test/e2e/upgrades/apps/daemonsets.go [hunk 4]
```diff
@@ -126,11 +126,11 @@ func checkRunningOnAllNodes(f *framework.Framework, namespace string, selector m
...
 	for _, node := range nodeList.Items {
-		if len(node.Spec.Taints) == 0 {
-			nodeNames = append(nodeNames, node.Name)
-		} else {
-			framework.Logf("Node %v not expected to have DaemonSet pod, has taints %v", node.Name, node.Spec.Taints)
+		if len(node.Spec.Taints) != 0 {
+			framework.Logf("Ignore taints %v on Node %v for DaemonSet Pod.", node.Spec.Taints, node.Name)
 		}
+		// DaemonSet Pods are expected to run on all the nodes in e2e.
+		nodeNames = append(nodeNames, node.Name)
```
Comment (krmayankk) [inline test/e2e/upgrades/apps/daemonsets.go]: Is this specific to e2e or are daemonsets pods designed to not tolerate any taints

Comment (k82cn) [reply test/e2e/upgrades/apps/daemonsets.go]: specific to e2e which only add default taints.
