### PR TITLE
Do not create endpoints for Services of type ExternalName

### LINKED ISSUE #105986: ExternalName Services should not autogenerate endpoints based on selectors
Ref: https://github.com/kubernetes/kubernetes/issues/105733#issuecomment-946863322

> The IP of the endpoint is autogenerated by matching the pods used by the label selector, however,  I don't know if we should autogenerate endpoints for services with type `ExternalName` cc: @thockin @robscott 

To reproduce it, just apply the following manifest https://gist.github.com/aojea/a7744cd5d664e1516bf5d6b05f1787c8
to create a pod and a Service Type Externalname with a selector matching hte pod
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mydomainfortest
  namespace: default
spec:
  externalName: www.google.com
  type: ExternalName
  selector:
    app: myapp
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: myapp
spec:
  containers:
    - name: web
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```

```bash
$kubectl apply -f https://gist.githubusercontent.com/aojea/a7744cd5d664e1516bf5d6b05f1787c8/raw/d9a1c99f78b2ab39987231ab590ea2adca580452/external_name_selector.yaml
service/mydomainfortest created
pod/testpod created

$ kubectl get pods
NAME      READY   STATUS    RESTARTS   AGE
testpod   1/1     Running   0          26s

$ kubectl get service
NAME              TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)   AGE
kubernetes        ClusterIP      10.96.0.1    <none>           443/TCP   99s
mydomainfortest   ExternalName   <none>       www.google.com   <none>    30s

$ kubectl get endpoints
NAME              ENDPOINTS         AGE
kubernetes        172.18.0.2:6443   104s
mydomainfortest   <none>            35s  <----------------

$ kubectl get endpointslices
NAME                    ADDRESSTYPE   PORTS     ENDPOINTS    AGE
kubernetes              IPv4          6443      172.18.0.2   4m56s
mydomainfortest-gzfnp   IPv6          <unset>   <unset>      3m47s
mydomainfortest-llds5   IPv4          <unset>   10.244.0.5   3m47s

```

### PR DESCRIPTION
**Pull request by panslava**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Service of type ExternalName should not create endpoints. Before, endpoints were created with "headless" label, and after switching to clusterIP service was not working, because endpoint was already created with headless label and kube-proxy were not creating iptable rule for it

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/105986

#### Does this PR introduce a user-facing change?

```release-note
Don't create endpoints for Service of type ExternalName.
```

/assign aojea

### CODE REVIEW

File: test/integration/endpoints/endpoints_test.go [hunk 1]
```diff
@@ -158,6 +158,106 @@ func TestEndpointUpdates(t *testing.T) {
...
+	svc := newExternalNameService(ns.Name, "foo1")
+	svc1, err := client.CoreV1().Services(ns.Name).Create(ctx, svc, metav1.CreateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to create service %s: %v", svc.Name, err)
+	}
+
+	endpoints, err := client.CoreV1().Endpoints(ns.Name).Get(ctx, svc.Name, metav1.GetOptions{})
+	if err == nil {
+		t.Errorf("expected no endpoints for externalName service, got: %v", endpoints)
+	}
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:236]: Endpoint generation is async, so this can be racy, it can be created after this check.
you have to wait for sometime in a wait.Poll loop to be sure

**Comment by aojea** [comment]
overall LGTM, the integration test need a small change to avoid races

/assign @robscott

File: test/integration/endpoints/endpoints_test.go [hunk 2]
```diff
@@ -158,6 +158,110 @@ func TestEndpointUpdates(t *testing.T) {
...
+
+	// Create an ExternalName service associated to the pod
+	svc := newExternalNameService(ns.Name, "foo1")
+	svc1, err := client.CoreV1().Services(ns.Name).Create(ctx, svc, metav1.CreateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to create service %s: %v", svc.Name, err)
+	}
+
+	_ = wait.PollImmediate(1*time.Second, wait.ForeverTestTimeout, func() (bool, error) {
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:233]:
```suggestion
	err = wait.PollImmediate(1*time.Second, 10*time.Second, func() (bool, error) {
```

File: test/integration/endpoints/endpoints_test.go [hunk 3]
```diff
@@ -158,6 +158,110 @@ func TestEndpointUpdates(t *testing.T) {
...
+		endpoints, err := client.CoreV1().Endpoints(ns.Name).Get(ctx, svc.Name, metav1.GetOptions{})
+		if err == nil {
+			t.Errorf("expected no endpoints for externalName service, got: %v", endpoints)
+			return true, nil
+		}
+		return false, nil
+	})
+
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:241]:
```suggestion
if err == nil {
     t.Errorf("expected error waiting for endpoints")
}
```

File: test/integration/endpoints/endpoints_test.go (hunk 2 above)
Comment (panslava) [reply test/integration/endpoints/endpoints_test.go:233]: Thanks, good suggestion, fixed!

File: test/integration/endpoints/endpoints_test.go (hunk 3 above)
Comment (panslava) [reply test/integration/endpoints/endpoints_test.go:244]: Thanks, good suggestion, fixed!

**Comment by aojea** [comment]
/lgtm
@robscott or @thockin for final approval

File: pkg/controller/endpointslice/endpointslice_controller.go [hunk 4]
```diff
@@ -328,6 +328,12 @@ func (c *Controller) syncService(key string) error {
 		return nil
 	}
 
+	if service.Spec.Type == v1.ServiceTypeExternalName {
+		// services with Type ExternalName receive no endpoints from this controller;
+		// Ref: https://issues.k8s.io/105986
+		return nil
+	}
```
Comment (robscott) [inline pkg/controller/endpointslice/endpointslice_controller.go:335]: If a Service transitions from a different type like ClusterIP to ExternalName, this will not do anything to clean up any existing EndpointSlices. Is that what we want?

File: pkg/controller/endpoint/endpoints_controller.go [hunk 5]
```diff
@@ -378,6 +378,12 @@ func (e *Controller) syncService(ctx context.Context, key string) error {
 		return nil
 	}
 
+	if service.Spec.Type == v1.ServiceTypeExternalName {
+		// services with Type ExternalName receive no endpoints from this controller;
+		// Ref: https://issues.k8s.io/105986
+		return nil
+	}
```
Comment (robscott) [inline pkg/controller/endpoint/endpoints_controller.go:385]: I believe this would also not result in Endpoints getting cleaned up after a Service type changes, not sure if that's what we want.

**Review by robscott — COMMENTED** [review]
Thanks @panslava! This seems like a good improvement, just want to clarify if we also want to clean up any leftover Endpoints/EndpointSlices when this happens.

File: pkg/controller/endpointslice/endpointslice_controller.go (hunk 4 above)
Comment (panslava) [reply pkg/controller/endpointslice/endpointslice_controller.go:335]: You are right, we decided not to introduce deletion in this pr, cause we thought it can be controversial 

So yes, ClusterIP -> ExternalName will result in having leftover endpoints and endpointSlices...

File: pkg/controller/endpoint/endpoints_controller.go (hunk 5 above)
Comment (panslava) [reply pkg/controller/endpoint/endpoints_controller.go:385]: Replied in the other comment

File: pkg/controller/endpointslice/endpointslice_controller.go (hunk 4 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go:335]: Makes sense, thanks!

**Comment by robscott** [comment]
Thanks @panslava!

/approve

**Comment by aojea** [comment]
/approve

Thanks
