### PR TITLE
Fix FibreChannel volume plugin corrupting filesystem on detach

### LINKED ISSUE #97014: Fibre channel volume plugin corrupts volumes on detach
**What happened**:
When a pod that uses a multipath Fibre Channel (FC) volume is deleted, the volume gets sometimes corrupted:

```
[ 6489.218162] XFS (dm-152): Metadata CRC error detected at xfs_inobt_read_verify+0x79/0xb0 [xfs], xfs_inobt block 0x18
[ 6489.218456] XFS (dm-152): metadata I/O error: block 0x18 ("xfs_trans_read_buf_map") error 74 numblks 8
[ 6489.222223] XFS (dm-152): Metadata CRC error detected at xfs_inobt_read_verify+0x79/0xb0 [xfs], xfs_inobt block 0x18
[ 6489.222589] XFS (dm-152): metadata I/O error: block 0x18 ("xfs_trans_read_buf_map") error 74 numblks 8
[ 6489.222890] XFS (dm-152): Metadata CRC error detected at xfs_inobt_read_verify+0x79/0xb0 [xfs], xfs_inobt block 0x18
[ 6489.223154] XFS (dm-152): metadata I/O error: block 0x18 ("xfs_trans_read_buf_map") error 74 numblks 8
[ 6489.505911] XFS (dm-152): Internal error XFS_WANT_CORRUPTED_GOTO at line 1637 of file fs/xfs/libxfs/xfs_alloc.c. Caller xfs_free_extent+0xaa/0x140 [xfs]
[ 6489.506006] [<ffffffffc03a13db>] xfs_error_report+0x3b/0x40 [xfs]
```

**What you expected to happen**:
No filesystem corruption.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up multipath FC volume + its PV+PVC.
2. Use it in a pod that "aggressively" writes to it (`dd if=/dev/random of=/mnt/the-mounted-volume/foo`)
3. Delete the pod.
4. Start the pod again.
-> sometimes the volume is corrupted.

**Anything else we need to know?**:
Red Hat recommends to flush/delete the multipath device before deleting its individual paths (`multipath -f`): https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/removing_devices

iSCSI volume plugin already does so: https://github.com/kubernetes/kubernetes/blob/fbe5daed7380ae640c2c6e66530593e3de67ce4b/pkg/volume/iscsi/iscsi_util.go#L559
We need to do the same in FC plugin too.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.beta2
- OS (e.g: `cat /etc/os-release`): "CentOS Linux 7 (Core)"
- Kernel (e.g. `uname -a`): 3.10.0-957.12.2.el7.x86_64
- Install tools: local-up-cluster.sh is enough

### PR DESCRIPTION
**Pull request by jsafrane**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
FibreChannel volume plugin misses one important step when removing a device: `multipath -f`, that flushes all multipath buffers to its individual paths. Without it, a filesystem on the device may get corrupted.

Calling `multipath -f` is easy, however, the patch grew a bit by passing all the necessary interfaces down to fc_util.go. The structure copies iscsi_util.go

See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/removing_devices for details.

**Which issue(s) this PR fixes**:

Fixes #97014

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed FibreChannel volume plugin corrupting filesystems on detach of multipath volumes.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/volume/fc/fc_util.go [hunk 1]
```diff
@@ -373,6 +380,15 @@ func (util *fcUtil) DetachBlockFCDisk(c fcDiskUnmapper, mapPath, devicePath stri
 	return nil
 }
 
+func (util *fcUtil) deleteMultipathDevice(exec utilexec.Interface, dmDevice string) error {
+	out, err := exec.Command("multipath", "-f", dmDevice).CombinedOutput()
+	if err != nil {
+		return fmt.Errorf("failed to flush multipath device %s: %s\n%s", dmDevice, err, string(out))
```
Comment (jingxu97) [inline pkg/volume/fc/fc_util.go:386]: just want to confirm whether in certain cases, it should continue instead of return error (e.g., the error means device no longer exist?)

Comment (jsafrane) [reply pkg/volume/fc/fc_util.go:386]: Good catch! That's why iscsi volume plugin ignores the error code...

Comment (jsafrane) [reply pkg/volume/fc/fc_util.go:386]: If the device is missing:

* Filesystem volumes: operation_generator.go will stop with "The path isn't device path or doesn't exist. Skip checking device path: /dev/dm-0" and it won't call volume plugin at all. Therefore, if the multipath device is removed, but the individual paths are still there, nothing will remove them.

* Block volumes: if the device is missing, the next `DetachBlockFCDisk` will stop in `checkPathExists`, if not earlier in `operation_generator.go` (did not test it).
https://github.com/kubernetes/kubernetes/blob/6f8bdb7cc1e28585edb5d47212ffb4d0ab3bf546/pkg/volume/fc/fc_util.go#L301

iscsi volume plugin actually ignores the error code from "multipath -f", continuing deleting the device paths. Which may result in volume corruption, if the multipath device still exists.. Now is the question what is actually correct - try to remove the individual paths to fully detach the devices and risk corruption OR do not remove the paths at all? The paths should just sit in /dev, not used by anything.

My gut feeling is to copy iscsi approach and ignore the exit code.

Comment (rootfs) [reply pkg/volume/fc/fc_util.go:386]: according to manpage
`-f     Flush (remove) a multipath device map specified as parameter, if unused.`

So if `multipath -f` fails, there is a good chance the device is still being used and removing it could cause data corruption. In this sense, the implementation in iscsi is indeed risky.

Comment (rootfs) [inline pkg/volume/fc/fc_util.go:386]: nit: 
```go
return fmt.Errorf("failed to flush multipath device %s: %v\n%s", dmDevice, err, string(out))
```

Comment (jsafrane) [reply pkg/volume/fc/fc_util.go:386]: No, `%s` is fine for `errror` type.

File: pkg/volume/fc/fc_util.go [hunk 2]
```diff
@@ -354,6 +358,9 @@ func (util *fcUtil) DetachBlockFCDisk(c fcDiskUnmapper, mapPath, devicePath stri
 	if len(dm) != 0 {
```
Comment (gnufied) [inline pkg/volume/fc/fc_util.go:358]: Same link - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/removing_devices#:~:text=Run%20multipath%20%2Dl%20command%20to,to%20remove%20the%20multipath%20device. recommends that for raw block devices we should call ` blockdev --flushbufs device`  before removing the device. Should we do that as well?

Comment (jsafrane) [reply pkg/volume/fc/fc_util.go:369]: Added as a separate commit.
BTW, we should refactor FC and iSCSI to use the same flush / device deletion. But that's for a separate PR.

Comment (gnufied) [reply pkg/volume/fc/fc_util.go:369]: yeah lets file that as a separate issue I think.
