### PR TITLE
Honor disabled LocalStorageCapacityIsolation in scheduling

### LINKED ISSUE #96083: Ephemeral storage requests on initContainers can cause pod to be unschedulable
**What happened**:

In a v1.18 cluster with the LocalStorageCapacityIsolation feature gate disabled setting an ephemeral-storage request or limit causes the pod to be unschedulable:
`Warning  FailedScheduling  56s (x3 over 119s)  default-scheduler  0/3 nodes are available: 3 Insufficient ephemeral-storage.`

If the ephemeral-storage request is removed the pod is scheduled.

This behavior exists in v1.19 and a recent v1.20 build.

**What you expected to happen**:

In previous releases such pods are scheduled.  I expect that any ephemeral-storage limit is not enforced.

**How to reproduce it (as minimally and precisely as possible)**:

Disable the LocalStorageCapacityIsolation feature guide by adding `--feature-gates=LocalStorageCapacityIsolation=false` to the kube-scheduler.

Create a pod like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        ephemeral-storage: 1024M
      limits:
        ephemeral-storage: 1024M
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "echo waiting for myservice; sleep 7;"]
    resources:
      requests:
        cpu: 500m
        ephemeral-storage: 2M
```

**Anything else we need to know?**:

The problem was originally seen after moving from IBM Cloud Red Hat OpenShift v4.4 to v4.5.  Pods that worked in 4.4 (Kubernetes v1.17) remained in a Pending state in OpenShift v4.5 (Kubernetes 1.18).  We discovered that the IBM Cloud OpenShift service has the LocalStorageCapacityIsolation feature-gate disabled while Red Hat has enabled the feature.  We then replicated the behavior with a plain Kubernetes cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.10, v1.19.3, v1.20.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:

This PR assures disabled `LocalStorageCapacityIsolation` featuregate is honored during scheduling.

When asserting whether a pod's request is satisfied, scheduler logic missed checking if the feature gate is enabled for initContainers. Which is reported in issue #96083.

**Which issue(s) this PR fixes**:

Fixes #96083

**Special notes for your reviewer**:

This fix should be back-ported to 1.18 and 1.19.

**Does this PR introduce a user-facing change?**:

```release-note
Fixes a regression in 1.18+ so a disabled `LocalStorageCapacityIsolation` feature gate is honored during scheduling.
```

### CODE REVIEW

**Comment by soulxu** [comment]
looks good to me

File: pkg/scheduler/framework/plugins/noderesources/fit.go [hunk 1]
```diff
@@ -266,7 +266,8 @@ func fitsRequest(podRequest *preFilterState, nodeInfo *framework.NodeInfo, ignor
 			nodeInfo.Allocatable.Memory,
 		})
 	}
-	if nodeInfo.Allocatable.EphemeralStorage < podRequest.EphemeralStorage+nodeInfo.Requested.EphemeralStorage {
+	if utilfeature.DefaultFeatureGate.Enabled(features.LocalStorageCapacityIsolation) &&
+		nodeInfo.Allocatable.EphemeralStorage < podRequest.EphemeralStorage+nodeInfo.Requested.EphemeralStorage {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/noderesources/fit.go:270]: I am not sure I am following, if the feature is disabled, shouldn't `podRequest.EphemeralStorage+nodeInfo.Requested.EphemeralStorage` be always equal to 0? and if it is 0, then it will never be larger than `nodeInfo.Allocatable.EphemeralStorage`, right? what am I missing?

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/noderesources/fit.go:270]: @ahg-g you're right. This shouldn't be the root cause. I will dig out more.

**Comment by Huang-Wei** [comment]
/hold
to find the real root cause.

**Comment by Huang-Wei** [comment]
/hold cancel

We missed the feature gate check during looping over initContainers: max_resource(sum_pod, any_init_container). (L156 below)

https://github.com/kubernetes/kubernetes/blob/95c56ada4b5734c3ddc6c949da6e6db5050c3624/pkg/scheduler/framework/plugins/noderesources/fit.go#L155-L157

@ahg-g PTAL.

File: pkg/scheduler/framework/types.go [hunk 2]
```diff
@@ -390,6 +390,9 @@ func (r *Resource) SetMaxResource(rl v1.ResourceList) {
 				r.MilliCPU = cpu
 			}
 		case v1.ResourceEphemeralStorage:
+			if !utilfeature.DefaultFeatureGate.Enabled(features.LocalStorageCapacityIsolation) {
+				continue
+			}
 			if ephemeralStorage := rQuantity.Value(); ephemeralStorage > r.EphemeralStorage {
 				r.EphemeralStorage = ephemeralStorage
 			}
```
Comment (ahg-g) [inline pkg/scheduler/framework/types.go:398]: can we do it like the default case below:

```
if utilfeature.DefaultFeatureGate.Enabled(features.LocalStorageCapacityIsolation) {
  if ephemeralStorage := rQuantity.Value(); ephemeralStorage > r.EphemeralStorage {
    r.EphemeralStorage = ephemeralStorage
  }
}
```

Comment (Huang-Wei) [reply pkg/scheduler/framework/types.go:398]: ok, to keep the style consistent
