### PR TITLE
Remove missing extended resources from init containers

### LINKED ISSUE #124255: removeMissingExtendedResources() did not remove unknown extension resources from InitContainer
### What happened?

The function removeMissingExtendedResources() located at pkg/kubelet/lifecycle/predicate.go:217, is designed to remove any extended resources from a container’s requests that are not found in nodeInfo.Allocatable before the pod is admitted. This is necessary to support cluster-level resources, which are extended resources that are unknown to nodes.
However, this function only removes missingExtendedResources from the container’s requests, and does not process the requests of initContainers. This could lead to issues, as initContainers might request resources that do not exist on the node, which could result in the pod failing to be admitted or other unforeseen issues. As such, it may be necessary to refine the removeMissingExtendedResources() function to also handle initContainer’s requests.

### What did you expect to happen?

Refine the removeMissingExtendedResources() function to also handle initContainer’s requests.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod that requests cluster-level extended resources in both the container and InitContainer.

### Anything else we need to know?

_No response_

### Kubernetes version

The problem persists in the latest version.

### Cloud provider

-

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by panoswoo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The function removeMissingExtendedResources() located at pkg/kubelet/lifecycle/predicate.go:217, is designed to remove any extended resources from a container’s requests that are not found in nodeInfo.Allocatable before the pod is admitted. 
This is necessary to support cluster-level resources, which are extended resources that are unknown to nodes.
However, this function only removes missingExtendedResources from the container’s requests, and does not process the requests of initContainers. 
This could lead to issues, as initContainers might request resources that do not exist on the node, which could result in the pod failing to be admitted or other unforeseen issues. 

#### Which issue(s) this PR fixes:

Fixes #124255  

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/lifecycle/predicate.go [hunk 1]
```diff
@@ -230,6 +230,17 @@ func removeMissingExtendedResources(pod *v1.Pod, nodeInfo *schedulerframework.No
 			podCopy.Spec.Containers[i].Resources.Requests[rName] = rQuant
 		}
 	}
+	for i, c := range pod.Spec.InitContainers {
+		podCopy.Spec.InitContainers[i].Resources.Requests = make(v1.ResourceList)
```
Comment (haircommander) [inline pkg/kubelet/lifecycle/predicate.go:234]: should this be done for EphemeralContainers too?

Comment (panoswoo) [reply pkg/kubelet/lifecycle/predicate.go:234]: I think that seems unnecessary because EphemeralContainers  are not allowed to set resources.
[what-is-an-ephemeral-container](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/#what-is-an-ephemeral-container)

Comment (haircommander) [reply pkg/kubelet/lifecycle/predicate.go:234]: great point!

**Comment by haircommander** [comment]
/ok-to-test
/triage accepted
/priority important-longterm

LGTM, let's see how tests feel but this seems like a straight forward fix

**Comment by panoswoo** [comment]
> /ok-to-test
> 
> /triage accepted
> 
> /priority important-longterm
> 
> 
> 
> LGTM, let's see how tests feel but this seems like a straight forward fix

Tests are all good, lgtm plz :)

File: pkg/kubelet/lifecycle/predicate.go [hunk 2]
```diff
@@ -230,6 +230,17 @@ func removeMissingExtendedResources(pod *v1.Pod, nodeInfo *schedulerframework.No
...
+		for rName, rQuant := range c.Resources.Requests {
+			if v1helper.IsExtendedResourceName(rName) {
+				if _, found := nodeInfo.Allocatable.ScalarResources[rName]; !found {
+					continue
+				}
+			}
+			podCopy.Spec.InitContainers[i].Resources.Requests[rName] = rQuant
+		}
+	}
```
Comment (bart0sh) [inline pkg/kubelet/lifecycle/predicate.go:243]: This code looks almost identical to the code above. Would it be possible to avoid duplication somehow?

Comment (panoswoo) [reply pkg/kubelet/lifecycle/predicate.go:243]: I’ll extract the duplicate code into a new function. Should I add this code to a new commit or just amend the existing one?

Comment (fulviodenza) [reply pkg/kubelet/lifecycle/predicate.go:243]: I would propose this to not replicate the code:
```
func removeMissingExtendedResources(pod *v1.Pod, nodeInfo *schedulerframework.NodeInfo) *v1.Pod {
	podCopy := pod.DeepCopy()
	updateResourceRequests := func(containers []v1.Container) []v1.Container {
		for i, container := range containers {
			// We only handle requests in Requests but not Limits because the
			// PodFitsResources predicate, to which the result pod will be passed,
			// does not use Limits.
			container.Resources.Requests = filterExtendedResources(container.Resources.Requests, nodeInfo)
			containers[i] = container
		}
		return containers
	}

	podCopy.Spec.Containers = updateResourceRequests(podCopy.Spec.Containers)
	podCopy.Spec.InitContainers = updateResourceRequests(podCopy.Spec.InitContainers)

	return podCopy
}

func filterExtendedResources(requests v1.ResourceList, nodeInfo *schedulerframework.NodeInfo) v1.ResourceList {
	filteredRequests := make(v1.ResourceList)
	for rName, rQuant := range requests {
		if v1helper.IsExtendedResourceName(rName) {
			if _, found := nodeInfo.Allocatable.ScalarResources[rName]; !found {
				continue
			}
		}
		filteredRequests[rName] = rQuant
	}
	return filteredRequests
}
```

Comment (panoswoo) [reply pkg/kubelet/lifecycle/predicate.go:243]: nice suggestion, I plan to modify it like this:
```go
func removeMissingExtendedResources(pod *v1.Pod, nodeInfo *schedulerframework.NodeInfo) *v1.Pod {
	filterExtendedResources := func(containers []v1.Container) {
		for i, c := range containers {
			// We only handle requests in Requests but not Limits because the
			// PodFitsResources predicate, to which the result pod will be passed,
			// does not use Limits.
			filteredResources := make(v1.ResourceList)
			for rName, rQuant := range c.Resources.Requests {
				if v1helper.IsExtendedResourceName(rName) {
					if _, found := nodeInfo.Allocatable.ScalarResources[rName]; !found {
						continue
					}
				}
				filteredResources[rName] = rQuant
			}
			containers[i].Resources.Requests = filteredResources
		}
	}
	podCopy := pod.DeepCopy()
	filterExtendedResources(podCopy.Spec.Containers)
	filterExtendedResources(podCopy.Spec.InitContainers)
	return podCopy
}
```

Comment (bart0sh) [reply pkg/kubelet/lifecycle/predicate.go:234]: /lgtm

**Comment by bart0sh** [comment]
/assign @mrunalp @derekwaynecarr @dchen1107 
for approval

**Comment by panoswoo** [comment]
@mrunalp @derekwaynecarr @dchen1107 PTAL~

**Comment by dims** [comment]
@mrunalp @derekwaynecarr @SergeyKanzhelev poke!

**Review by mrunalp — APPROVED** [review]
