### PR TITLE
Do not log errors when ServiceHealthServer is closed normally

### LINKED ISSUE #114723: Deleting LoadBalancer Services with Local ExternalTrafficPolicy always generated errors in kube-proxy log
### What happened?

When a LoadBalancer Service with Local ExternalTrafficPolicy was deleted normally, an error log "use of closed network connection" was always generated in kube-proxy log, which confused people that there was something wrong:
```
I1228 13:20:27.757127       1 server.go:432] "Using lenient decoding as strict decoding failed" err="strict decoding error: unknown field \"udpIdleTimeout\""
W1228 13:20:27.757263       1 feature_gate.go:241] Setting GA feature gate NetworkPolicyEndPort=true. It will be removed in a future release.
W1228 13:20:27.757371       1 feature_gate.go:241] Setting GA feature gate NetworkPolicyEndPort=true. It will be removed in a future release.
I1228 13:20:27.780279       1 node.go:163] Successfully retrieved node IP: 172.18.0.3
I1228 13:20:27.780315       1 server_others.go:109] "Detected node IP" address="172.18.0.3"
I1228 13:20:27.850273       1 server_others.go:176] "Using iptables Proxier"
I1228 13:20:27.850352       1 server_others.go:183] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I1228 13:20:27.850399       1 server_others.go:184] "Creating dualStackProxier for iptables"
I1228 13:20:27.850531       1 proxier.go:242] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses"
I1228 13:20:27.851789       1 server.go:655] "Version info" version="v1.26.0"
I1228 13:20:27.851829       1 server.go:657] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I1228 13:20:27.853467       1 config.go:226] "Starting endpoint slice config controller"
I1228 13:20:27.853557       1 shared_informer.go:273] Waiting for caches to sync for endpoint slice config
I1228 13:20:27.853574       1 config.go:444] "Starting node config controller"
I1228 13:20:27.853598       1 shared_informer.go:273] Waiting for caches to sync for node config
I1228 13:20:27.853621       1 config.go:317] "Starting service config controller"
I1228 13:20:27.853672       1 shared_informer.go:273] Waiting for caches to sync for service config
I1228 13:20:27.953858       1 shared_informer.go:280] Caches are synced for endpoint slice config
I1228 13:20:27.953945       1 shared_informer.go:280] Caches are synced for service config
I1228 13:20:27.954103       1 shared_informer.go:280] Caches are synced for node config
E1228 13:24:08.428749       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:31751: use of closed network connection" service="default/lb-svc"
E1228 13:24:11.723008       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:31582: use of closed network connection" service="default/lb-svc"
E1228 13:24:13.944425       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:31496: use of closed network connection" service="default/lb-svc"
E1228 13:24:16.809817       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:31587: use of closed network connection" service="default/lb-svc"
E1228 13:24:19.013504       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:32663: use of closed network connection" service="default/lb-svc"
E1228 13:24:21.636633       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:31320: use of closed network connection" service="default/lb-svc"
E1228 13:24:23.851625       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:30131: use of closed network connection" service="default/lb-svc"
E1228 13:24:25.402015       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:30251: use of closed network connection" service="default/lb-svc"
E1228 13:24:28.725379       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:30503: use of closed network connection" service="default/lb-svc"
E1228 13:24:30.971488       1 service_health.go:187] "Healthcheck closed" err="accept tcp [::]:30742: use of closed network connection" service="default/lb-svc"
```

### What did you expect to happen?

Do not generate error log when it's expected.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a LoadBalancer Service with Local ExternalTrafficPolicy
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
  name: lb-svc
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    targetPort: api
  selector:
    app: test
  type: LoadBalancer
EOF
```

2. Delete it
```
kubectl delete svc lb-svc
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

v1.26.0

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Server.Serve() always returns a non-nil error. If it exits because the http server is closed, it will return ErrServerClosed. To differentiate the error, this patch changes to close the http server instead of the listener when the Service is deleted. Closing http server automatically closes the listener, there is no need to cache the listeners any more.

#### Which issue(s) this PR fixes:

Fixes #114723

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/healthcheck/service_health.go [hunk 1]
```diff
@@ -183,7 +183,7 @@ func (hcI *hcInstance) listenAndServeAll(hcs *server) error {
 		go func(hcI *hcInstance, listener net.Listener, httpSrv httpServer) {
 			// Serve() will exit when the listener is closed.
 			klog.V(3).InfoS("Starting goroutine for healthcheck", "service", hcI.nsn, "address", listener.Addr())
-			if err := httpSrv.Serve(listener); err != nil {
+			if err := httpSrv.Serve(listener); err != nil && !strings.Contains(err.Error(), "use of closed network connection") {
```
Comment (danwinship) [inline pkg/proxy/healthcheck/service_health.go:186]: It's not good to check for specific error text. Is there some other way to do this?
(IIRC in one of these situations you can call two separate methods instead of one, and the first one can return a (valid) error but the second one doesn't.)

**Comment by aojea** [comment]
can not be solved using graceful shutdown https://penkovski.com/post/golang-http-graceful-shutdown/ ?

File: pkg/proxy/healthcheck/service_health.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/healthcheck/service_health.go:186]: yeah, in another angle, is this even an error log message or an informative one?

Comment (tnqn) [reply pkg/proxy/healthcheck/service_health.go:186]: > It's not good to check for specific error text. Is there some other way to do this?

It could return `http.ErrServerClosed` but we need to change to close the http server, instead of the listener.

> (IIRC in one of these situations you can call two separate methods instead of one, and the first one can return a (valid) error but the second one doesn't.)

I don't find the two separate methods, did you mean `ListenAndServe` vs. `net.Listen() + Serve()`? If yes, the original code already did so.

> yeah, in another angle, is this even an error log message or an informative one?

I guess this is meant for error message as there is an informative one in next line: https://github.com/kubernetes/kubernetes/blob/7eb9a75bf914428e7579d2497722f71be3ef1812/pkg/proxy/healthcheck/service_health.go#L190

I have updated the patch to close the server and check error in a more graceful way, PTAL.

**Comment by tnqn** [comment]
> can not be solved using graceful shutdown https://penkovski.com/post/golang-http-graceful-shutdown/ ?

I have updated the patch to close the server and check error in a more graceful way, PTAL.

File: pkg/proxy/healthcheck/service_health.go [hunk 2]
```diff
@@ -199,9 +196,9 @@ func (hcI *hcInstance) listenAndServeAll(hcs *server) error {
 
 func (hcI *hcInstance) closeAll() error {
 	errors := []error{}
-	for _, listener := range hcI.listeners {
-		if err := listener.Close(); err != nil {
-			klog.ErrorS(err, "Error closing listener for health check service", "service", hcI.nsn, "address", listener.Addr())
+	for _, server := range hcI.httpServers {
+		if err := server.Close(); err != nil {
```
Comment (aojea) [inline pkg/proxy/healthcheck/service_health.go:200]: don't you want to check for `err != http.ErrServerClosed` here too?

Comment (tnqn) [reply pkg/proxy/healthcheck/service_health.go:200]: No, `Close` returns error returned from closing the Server's underlying listeners. It should be nil for normal case, and can never be `ErrServerClosed`.

**Comment by tnqn** [comment]
@danwinship Could you take another look?  Please let me know if you have any further comments.
