### PR TITLE
Registering a serviceErrorHandler with go-restful to always return JSON responses

### LINKED ISSUE #4347: go-restful is emitting less helpful errors than resthandler
If go-restful detects a particular method is not allowed, it will return this error:
```
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8

405: Method Not Allowed
```

That is preventing useful methods that resthandler would generate from making it to the client. Expected response:
```
HTTP/1.1 405 Method Not Allowed
Content-Type: application/json

{
  "kind": "Status",
  "creationTimestamp": null,
  "apiVersion": "v1beta3",
  "status": "Failure",
  "message": "update is not supported on resources of kind event",
  "reason": "InternalError",
  "details": {
    "kind": "event"
  },
  "code": 405
}
```

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/4347, https://github.com/GoogleCloudPlatform/kubernetes/issues/1990 and https://github.com/GoogleCloudPlatform/kubernetes/issues/6153

This is required to return Json errors instead of plain text.

Running 
`$curl -X PUT -i http://localhost:8085/api/v1beta3/redirect/namespaces/default/services/kubernetes` with this change gives the following output:

```
HTTP/1.1 405 Method Not Allowed
Content-Type: application/json
Content-Length: 234

{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server does not allow this method on the requested resource",
  "reason": "MethodNotAllowed",
  "details": {},
  "code": 405
}
```

instead of the previous response:

```
HTTP/1.1 405 Method Not Allowed
Content-Length: 23
Content-Type: text/plain; charset=utf-8

405: Method Not Allowed
```

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

File: pkg/apiserver/apiserver.go [hunk 1]
```diff
@@ -168,6 +170,14 @@ func InstallLogsSupport(mux Mux) {
 	mux.Handle("/logs/", http.StripPrefix("/logs/", http.FileServer(http.Dir("/var/log/"))))
 }
 
+func InstallServiceErrorHandler(container *restful.Container) {
+	container.ServiceErrorHandler(serviceErrorHandler)
```
Comment (bgrant0607) [inline pkg/apiserver/apiserver.go]: Cool! When was this added?

File: pkg/api/errors/errors.go [hunk 2]
```diff
@@ -297,6 +297,17 @@ func NewGenericServerResponse(code int, verb, kind, name, serverMessage string,
...
+	var causes []api.StatusCause
+	if isUnexpectedResponse {
+		causes = []api.StatusCause{
+			{
+				Type:    api.CauseTypeUnexpectedServerResponse,
+				Message: serverMessage,
+			},
+		}
+	} else {
+		causes = nil
```
Comment (bgrant0607) [inline pkg/api/errors/errors.go]: When will this happen?

Comment (bgrant0607) [inline pkg/api/errors/errors.go]: I see where unexpected is set to false below. I'm more asking whether some cause is (or could be) meaningful for go-restful-produced errors.

File: pkg/apiserver/apiserver.go (hunk 1 above)
Comment (nikhiljindal) [inline pkg/apiserver/apiserver.go]: https://github.com/emicklei/go-restful/pull/181

File: pkg/apiserver/apiserver.go [hunk 3]
```diff
@@ -168,6 +170,14 @@ func InstallLogsSupport(mux Mux) {
...
+}
+
+func serviceErrorHandler(serviceErr restful.ServiceError, response *restful.Response) {
+	errorJSON(apierrors.NewGenericServerResponse(serviceErr.Code, "", "", "", "", 0, false), latest.Codec, response)
```
Comment (nikhiljindal) [inline pkg/apiserver/apiserver.go]: Note that we are using latest.Codec here, irrespective of the version for which the request was. (Thats because we do not have access to request here)
This can lead to situations like https://github.com/GoogleCloudPlatform/kubernetes/issues/6876, where users request a v1beta1 url and we will reply with v1beta3 status.

Comment (bgrant0607) [inline pkg/apiserver/apiserver.go]: We'll also want to extract the api version from the path, if possible, falling back to the default version only if the path prefix is totally broken, but it's ok to punt that to the more general issue of sending status using the proper version.

File: pkg/api/errors/errors.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/api/errors/errors.go]: Couldnt think of a cause to add. The current ones are specific to field value validation: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L1496
Feel free to suggest, if you have something in mind.

Comment (bgrant0607) [inline pkg/api/errors/errors.go]: go-restful will return 404 when the path isn't registered? We could create a cause for that, to distinguish it from a proper path but no object.

go-restful will return 405 when the path is registered, but the verb is not? That error is perhaps specific enough without a cause.

Comment (bgrant0607) [inline pkg/api/errors/errors.go]: 406 and 415 probably/maybe don't need causes, either, at least for now.

**Comment by bgrant0607** [comment]
Failed auth_test.

**Comment by bgrant0607** [comment]
Status code isn't getting set correctly in the header.

**Comment by bgrant0607** [comment]
I don't think this fixes #1990. We still propagate some etcd errors directly:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/errors/etcd/etcd.go#L37

File: pkg/api/errors/errors.go (hunk 2 above)
Comment (bgrant0607) [inline pkg/api/errors/errors.go]: How about PathInvalid as cause for 404s from go-restful and DoesNotExist for 404s from etcd (i.e., the cause reported by NewNotFound)?

File: pkg/apiserver/apiserver.go (hunk 3 above)
Comment (nikhiljindal) [inline pkg/apiserver/apiserver.go]: Added a TODO

File: pkg/api/errors/errors.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/api/errors/errors.go]: Yes NewNotFound is different: https://github.com/GoogleCloudPlatform/kubernetes/blob/3565a0861c62a827fc6112968262c75c8c59d5d1/pkg/api/errors/errors.go#L91
It has a bit more details.
Example output from NewNotFound:
```
$curl -X GET -i http://localhost:8082/api/v1beta3/namespaces/default/services/kube
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Thu, 16 Apr 2015 22:06:17 GMT
Content-Length: 232

{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "service \"kube\" not found",
  "reason": "NotFound",
  "details": {
    "id": "kube",
    "kind": "service"
  },
  "code": 404
}
```

Example output from go-restful 404:
```
curl -X GET -i http://localhost:8082/api/v1beta3/redirect/namespaces/default/servfds/fdsfsd
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Thu, 16 Apr 2015 22:07:41 GMT
Content-Length: 211

{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}
```

**Comment by nikhiljindal** [comment]
The auth_test was failing because I was passing restful.Response instead of passing restful.ResponseWriter to errorJson.
Tests should pass now.

**Comment by nikhiljindal** [comment]
Ready for a look again.

File: pkg/api/errors/errors.go (hunk 2 above)
Comment (bgrant0607) [inline pkg/api/errors/errors.go]: Not the greatest, but ok.

**Comment by bgrant0607** [comment]
LGTM
