### PR TITLE
kubeadm: Fix `upgrade plan` for air-gapped setups

### LINKED ISSUE #2274: upgrade plan with a version has stopped working on 1.19.0
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
1.19.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):
1.18.8
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 20.04.01
- **Kernel** (e.g. `uname -a`):
Linux srv-ms9ld 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

The upgrade plan failed when you specify a version. 

```
$ sudo kubeadm upgrade plan 1.19.0
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.18.8
[upgrade/versions] kubeadm version: v1.19.0
[upgrade/versions] Latest stable version: 1.19.0
[upgrade/versions] Latest version in the v1.18 series: 1.19.0

[upgrade/versions] FATAL: configmaps "kubelet-config-1.19" not found
To see the stack trace of this error execute with --v=5 or higher
```

## What you expected to happen?

upgrade plan should work with a specified version as it does without a version. 
## How to reproduce it (as minimally and precisely as possible)?

As above. 

## Anything else we need to know?

upgrade plan without a version picks up the latest version in the 1.18 series correctly and generates a plan as expected.

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind bug
/kind regression

**What this PR does / why we need it**:

A bug was discovered in the `enforceRequirements` func for `upgrade plan`.
If a command line argument that specifies the target Kubernetes version is
supplied, the returned `ClusterConfiguration` by `enforceRequirements` will
have its `KubernetesVersion` field set to the new version.
If no version was specified, the returned `KubernetesVersion` points to the
currently installed one.

This remained undetected for a couple of reasons
- It's only `upgrade plan` that allows for the version command line argument to
  be optional (in `upgrade plan` it's mandatory)
- Prior to 1.19, the implementation of `upgrade plan` did not make use of the
  `KubernetesVersion` returned by `enforceRequirements`.

`upgrade plan` supports this optional command line argument to enable
air-gapped setups (as not specifying a version on the command line will end up
looking for the latest version over the Interned).

Hence, the only option is to make `enforceRequirements` consistent in the
`upgrade plan` case and always return the currently installed version in the
`KubernetesVersion` field.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#2274

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-soon
/assign @fabriziopandini @neolit123

**Does this PR introduce a user-facing change?**:

```release-note
Fix a regression in 1.19 where kubeadm bails out with a fatal error when an optional version command line argument is supplied to the "kubeadm upgrade plan" command
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/upgrade/common.go [hunk 1]
```diff
@@ -185,7 +185,15 @@ func enforceRequirements(flags *applyPlanFlags, args []string, dryRun bool, upgr
...
 		newK8sVersion = args[0]
-		cfg.KubernetesVersion = newK8sVersion
+		if upgradeApply {
+			// The `upgrade apply` version always overwrites the KubernetesVersion in the returned cfg with the target
+			// version. While this is not the same for `upgrade plan` where the KubernetesVersion should be the old
+			// one (because the call to getComponentConfigVersionStates requires the currently installed version).
+			// This also makes the KubernetesVersion value returned for `upgrade plan` consistent as that command
+			// allows to not specify a target version in which case KubernetesVersion will always hold the currently
+			// installed one.
+			cfg.KubernetesVersion = newK8sVersion
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/upgrade/common.go:195]: Just to double check. After this change, if the user passes to plan 1.19.2, while the cluster version is at 1.19.1, would the table for control plane component upgrade still print .2 as the planned upgrade target?

Comment (rosti) [reply cmd/kubeadm/app/cmd/upgrade/common.go:195]: Yes. The tables are generated using the version getter (initialized at the return of this func with the value of `newK8sVersion`).

Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/common.go:195]: Ok thanks!

**Comment by neolit123** [comment]
/lgtm
Do you have time to cherry pick for 1.19?
