### PR TITLE
Fixing missing swagger spec for apis/extensions

### LINKED ISSUE #16687: Swagger spec: missing ApiDeclaration for /apis/extensions
Loading `/swaggerapi/apis/extensions/` returns `ApiDeclaration not found`
Looking at the code `/swaggerapi/apis/extensions/` is registered in the same way as `/swaggerapi/apis/` which works fine.
So not sure why is this broken.

@caesarxuchao

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/16687

The only difference between /apis/extensions and other paths (such as /apis) was "/" at the end. I tried removing it and that fixed the issue :)

cc @bgrant0607 @caesarxuchao @lavalamp

### CODE REVIEW

File: pkg/master/master.go [hunk 1]
```diff
@@ -672,7 +672,7 @@ func (m *Master) init(c *Config) {
 			Versions:         expAPIVersions,
 			PreferredVersion: unversioned.GroupVersion{GroupVersion: storageVersion, Version: apiutil.GetVersion(storageVersion)},
 		}
-		apiserver.AddGroupWebService(m.handlerContainer, c.APIGroupPrefix+"/"+latest.GroupOrDie("extensions").Group+"/", group)
+		apiserver.AddGroupWebService(m.handlerContainer, c.APIGroupPrefix+"/"+latest.GroupOrDie("extensions").Group, group)
```
Comment (caesarxuchao) [inline pkg/master/master.go]: @nikhiljindal, this seems unrelated to /swaggerapi/...? This should only affect /apis/extensions/ ?

**Comment by bgrant0607** [comment]
Why was the "/" there?

File: pkg/master/master.go (hunk 1 above)
Comment (nikhiljindal) [inline pkg/master/master.go]: `/swaggerapi` is auto generated.
`/swaggerapi/apis/extensions/` was returning `ApiDeclaration not found`. This change fixes that

**Comment by nikhiljindal** [comment]
@bgrant0607 I dont think that there was a specific reason.
@caesarxuchao can correct me if there was, since he wrote that code.

File: pkg/master/master.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/master/master.go]: I see. Maybe go-restful requires there's no trailing "/". Could you double check /apis/extensions/ and /apis/extensions still work? Because that's the paths directly affected by this line. Thanks.

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this please

**Comment by nikhiljindal** [comment]
Can I get an LGTM?
I want to cherrypick this

File: pkg/master/master.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/master/master.go]: @nikhiljindal, Could you double check /apis/extensions/ and /apis/extensions still work? Because that's the paths directly affected by this line. Thanks.

Comment (nikhiljindal) [inline pkg/master/master.go]: Yes Verified that both of them work

Comment (caesarxuchao) [inline pkg/master/master.go]: Thanks! LGTM.
