### PR TITLE
Fix for detach volume when node is not present/ powered off

### LINKED ISSUE #33061: vSphere Cloud provider:  Volume detach is not issued when VM is not present
When a vm is reported as no longer present in cloud provider and is deleted by node controller, there are no attempts to detach respective volumes.  For example, if a VM is powered off or paused, and pods are migrated to other nodes.  In the case of vSphere, the VM cannot be started again because the VM still holds mount points to volumes that are now mounted to other VMs.  

In order to re-join this node again, you will have to manually detach these volumes from the powered off vm before starting it.

### PR DESCRIPTION
**Pull request by BaluDontu**
Fixes #33061 
When a vm is reported as no longer present in cloud provider and is deleted by node controller, there are no attempts to detach respective volumes. For example, if a VM is powered off or paused, and pods are migrated to other nodes. In the case of vSphere, the VM cannot be started again because the VM still holds mount points to volumes that are now mounted to other VMs.

In order to re-join this node again, you will have to manually detach these volumes from the powered off vm before starting it.

The current fix will make sure the mount points are deleted when the VM is powered off. Since all the mount points are deleted, the VM can be powered on again.

This is a workaround proposal only. I still don't see the kubernetes issuing a detach request to the vsphere cloud provider which should be the case. (Details in original issue #33061 )

@luomiao @kerneltime @pdhamdhere @jingxu97 @saad-ali

### CODE REVIEW

**Comment by kerneltime** [comment]
@k8s-bot ok to test

**Comment by lsjostro** [comment]
🏆

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 1]
```diff
@@ -976,9 +994,15 @@ func (vs *VSphere) DisksAreAttached(volPaths []string, nodeName k8stypes.NodeNam
...
 		glog.Warningf(
-			"Node %q does not exist. DisksAreAttached will assume vmdk %v are not attached to it.",
+			"Node %q does not exist. DisksAreAttached will delete any vmdk %v attached to it.",
 			vSphereInstance,
 			volPaths)
+		for _, volPath := range volPaths {
+			if err = vs.DetachDisk(volPath, nodeName); err != nil {
+				glog.V(1).Infof("Error deleting vsphere volume %s: %v", volPath, err)
+				return attached, err
+			}
```
Comment (jingxu97) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: I think even if some detachDisk fail, it should continue to detach others.

Comment (jingxu97) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Actually since this function is only for checking the status, maybe we should put detachdisk function inside of it. When node node no longer exists, we should return an error message instead of returning false indicating volume is already detached.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 2]
```diff
@@ -924,10 +939,13 @@ func (vs *VSphere) DiskIsAttached(volPath string, nodeName k8stypes.NodeName) (b
 	}
 
 	if !nodeExist {
-		glog.Warningf(
-			"Node %q does not exist. DiskIsAttached will assume vmdk %q is not attached to it.",
+		glog.Warningf("Node %q does not exist. DisksAreAttached will delete any vmdk %v attached to it.",
 			vSphereInstance,
 			volPath)
+		if err = vs.DetachDisk(volPath, nodeName); err != nil {
```
Comment (jingxu97) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Actually since this function is only for checking the status, maybe we should put detachdisk function inside of it. When node node no longer exists, we should return an error message instead of returning false indicating volume is already detached.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 1 above)
Comment (dagnello) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: agreed, detach should be issued to all disks prior to returning.

**Comment by BaluDontu** [comment]
@jingxu97 : Can you please review the latest changes. Thanks!

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 3]
```diff
@@ -924,11 +924,10 @@ func (vs *VSphere) DiskIsAttached(volPath string, nodeName k8stypes.NodeName) (b
...
 
 	if !nodeExist {
-		glog.Warningf(
-			"Node %q does not exist. DiskIsAttached will assume vmdk %q is not attached to it.",
-			vSphereInstance,
-			volPath)
-		return false, nil
+		glog.Errorf("Node %q does not exist. DiskIsAttached will throw an error as node doesn't exist.",
+			vSphereInstance)
+		return false, errors.New(fmt.Sprintf("Node %q does not exist. DiskIsAttached will throw an error as node doesn't exist.",
```
Comment (jingxu97) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: the error log could be " DiskIsAttached failed to determine whether disk is still attached: node %q does not exist.

**Comment by dagnello** [comment]
@BaluDontu lgtm.  This change as is does not fully resolve #33061, k8s flow should be calling down to do detach in cloud provider when node is not present.

**Comment by jingxu97** [comment]
@k8s-bot verify test this

**Comment by BaluDontu** [comment]
@dagnello : It is k8s flow which actually makes the detach request. I am not explicitly making any detach calls in cloud provider. Please see the latest code out for review.

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Review by kerneltime — APPROVED** [review]

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by BaluDontu** [comment]
@jingxu97 : The test seems to be failing multiple times. Can you take a look.

**Comment by luomiao** [comment]
@k8s-bot verify test this

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 4]
```diff
@@ -924,11 +924,12 @@ func (vs *VSphere) DiskIsAttached(volPath string, nodeName k8stypes.NodeName) (b
...
 	if !nodeExist {
-		glog.Warningf(
-			"Node %q does not exist. DiskIsAttached will assume vmdk %q is not attached to it.",
-			vSphereInstance,
-			volPath)
-		return false, nil
+		glog.Errorf("DiskIsAttached failed to determine whether disk %q is still attached: node %q does not exist",
+			volPath,
+			vSphereInstance)
+		return false, errors.New(fmt.Sprintf("DiskIsAttached failed to determine whether disk %q is still attached: node %q does not exist",
```
Comment (jingxu97) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: I think you can use fmt.Errorf instead of errors.New(fmt.Sprintf...

**Comment by BaluDontu** [comment]
@k8s-bot kops aws e2e test this

**Comment by kerneltime** [comment]
@k8s-bot kops aws e2e test this

**Comment by jingxu97** [comment]
@k8s-bot test this

**Comment by kerneltime** [comment]
Thanks @jingxu97
