### PR TITLE
Fix APIServerTracing test data race

### LINKED ISSUE #132050: k8s.io/kubernetes/test/integration/apiserver/tracing: TestAPIServerTracing DATA RACE
### What happened?

```
k8s.io/kubernetes/test/integration/apiserver: tracing
...
=== RUN   TestAPIServerTracing
...
WARNING: DATA RACE
Write at 0x00c0038ccdb0 by goroutine 13734:
  k8s.io/kubernetes/test/integration/apiserver/tracing.TestAPIServerTracing.func1()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing/tracing_test.go:339 +0x84
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:610 +0x5d
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:887 +0x4e9
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:149 +0xc44
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/admissionregistration/rest.RESTStorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/admissionregistration/rest/storage_apiserver.go:83 +0x1e6
  k8s.io/kubernetes/pkg/registry/admissionregistration/rest.RESTStorageProvider.NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/admissionregistration/rest/storage_apiserver.go:50 +0x23a
  k8s.io/kubernetes/pkg/registry/admissionregistration/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xfb
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/apps/rest.StorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/apps/rest/storage_apps.go:68 +0x3e4
  k8s.io/kubernetes/pkg/registry/apps/rest.StorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/apps/rest/storage_apps.go:57 +0x146
  k8s.io/kubernetes/pkg/registry/apps/rest.StorageProvider.NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/apps/rest/storage_apps.go:43 +0x1da
  k8s.io/kubernetes/pkg/registry/apps/rest.(*StorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xd7
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/flowcontrol/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xeb
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/storage/rest.RESTStorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/storage/rest/storage_storage.go:99 +0x85
  k8s.io/kubernetes/pkg/registry/storage/rest.RESTStorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/storage/rest/storage_storage.go:95 +0x5e
  k8s.io/kubernetes/pkg/registry/storage/rest.RESTStorageProvider.NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/storage/rest/storage_storage.go:55 +0x3b7
  k8s.io/kubernetes/pkg/registry/storage/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xd7
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/rbac/rest.RESTStorageProvider.storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/rbac/rest/storage_rbac.go:84 +0x78
  k8s.io/kubernetes/pkg/registry/rbac/rest.RESTStorageProvider.NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/rbac/rest/storage_rbac.go:72 +0x244
  k8s.io/kubernetes/pkg/registry/rbac/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xeb
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/networking/rest.RESTStorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/networking/rest/storage_settings.go:71 +0x2bc
  k8s.io/kubernetes/pkg/registry/networking/rest.RESTStorageProvider.v1Storage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/networking/rest/storage_settings.go:62 +0x146
  k8s.io/kubernetes/pkg/registry/networking/rest.RESTStorageProvider.NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/networking/rest/storage_settings.go:48 +0x2c8
  k8s.io/kubernetes/pkg/registry/networking/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xd7
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/batch/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xd7
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/registry/autoscaling/rest.(*RESTStorageProvider).NewRESTStorage()
      <autogenerated>:1 +0xd7
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go:208 +0x3ad
  k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go:114 +0x245
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:792 +0x504
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallLegacyAPIGroup()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:849 +0x1e5
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:140 +0xab5
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:226 +0x2d24
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:201 +0x52d
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:191 +0x3b9
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:186 +0x30d
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:181 +0x21b
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:176 +0x1ed
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:172 +0x1b6
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:167 +0x190
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:162 +0x16a
  k8s.io/kubernetes/pkg/registry/core/rest.(*GenericConfig).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core_generic.go:109 +0xa39
  k8s.io/kubernetes/pkg/registry/core/rest.(*GenericConfig).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core_generic.go:104 +0xa13
  k8s.io/kubernetes/pkg/registry/core/rest.(*GenericConfig).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core_generic.go:99 +0x9ed
  k8s.io/kubernetes/pkg/registry/core/rest.(*GenericConfig).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core_generic.go:95 +0x9bb
  k8s.io/kubernetes/pkg/registry/core/rest.(*GenericConfig).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core_generic.go:90 +0x995
  k8s.io/kubernetes/pkg/registry/core/rest.(*legacyProvider).NewRESTStorage()
      /home/prow/go/src/k8s.io/kubernetes/pkg/registry/core/rest/storage_core.go:152 +0xc4
  k8s.io/kubernetes/pkg/controlplane/apiserver.(*Server).InstallAPIs()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/apis.go:105 +0x38a
  k8s.io/kubernetes/pkg/controlplane.CompletedConfig.New()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/instance.go:333 +0x29b
  k8s.io/kubernetes/pkg/controlplane.CompletedConfig.New()
      /home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/instance.go:328 +0x245
  k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:183 +0x471
  k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroup()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go:943 +0xb31
  k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:160 +0xac8
  k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:149 +0x592
  k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:177 +0x1f0
  k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServer()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:428 +0x58ee
  k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServer()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:424 +0x58d0
  k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServerConfig()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:221 +0x218
  k8s.io/kubernetes/cmd/kube-apiserver/app.NewConfig()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/config.go:89 +0x1f5
  k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServer()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:420 +0x58b2
  k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServerOrDie()
      /home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:566 +0xd3
  k8s.io/kubernetes/test/integration/apiserver/tracing.TestAPIServerTracing()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing/tracing_test.go:364 +0x8e4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1851 +0x44

Previous write at 0x00c0038ccdb0 by goroutine 13736:
  k8s.io/kubernetes/test/integration/apiserver/tracing.TestAPIServerTracing.func2()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing/tracing_test.go:357 +0x78

Goroutine 13734 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1851 +0x8f2
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2279 +0x85
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2277 +0x96c
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:2142 +0xeea
  testing.(*M).Run-fm()
      <autogenerated>:1 +0x33
  k8s.io/kubernetes/test/integration/framework.EtcdMain()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/framework/etcd.go:224 +0x64a
  k8s.io/kubernetes/test/integration/apiserver/tracing.TestMain()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing/main_test.go:26 +0x1c4
  main.main()
      _testmain.go:53 +0x16d

Goroutine 13736 (finished) created at:
  k8s.io/kubernetes/test/integration/apiserver/tracing.TestAPIServerTracing()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing/tracing_test.go:356 +0x72a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1792 +0x225
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1851 +0x44
```

/sig api-machinery

### What did you expect to happen?

No race.

### How can we reproduce it (as minimally and precisely as possible)?

Run locally with `go test -race`.

### Anything else we need to know?

Found in https://github.com/kubernetes/kubernetes/pull/116980.

### Kubernetes version

master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dashpole**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Fixes a data race in an integration test for APIServerTracing. The spawned goroutine was sharing the `err` variable with the main goroutine, causing the data race.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/132050#issuecomment-2937098962

#### Special notes for your reviewer:

Verified:

```
~/go/src/k8s.io/kubernetes/test/integration/apiserver/tracing$ go test ./... -race
ok  	k8s.io/kubernetes/test/integration/apiserver/tracing	68.825s
```

### CODE REVIEW

**Comment by dashpole** [comment]
cc @kubernetes/sig-instrumentation-leads

**Comment by dims** [comment]
/approve

thanks @dashpole

**Comment by pacoxu** [comment]
/retest
TestAuthorizerMetrics seems to be a UT flake, which is tracked in #131069.

File: test/integration/apiserver/tracing/tracing_test.go [hunk 1]
```diff
@@ -354,8 +354,8 @@ endpoint: %s`, listener.Addr().String())), os.FileMode(0755)); err != nil {
 	traceservice.RegisterTraceServiceServer(srv, fakeServer)
 
 	go func() {
-		if err = srv.Serve(listener); err != nil {
-			t.Error(err)
+		if serveErr := srv.Serve(listener); serveErr != nil {
+			t.Error(serveErr)
```
Comment (logicalhan) [inline test/integration/apiserver/tracing/tracing_test.go:358]: It's probably better to explicitly return in this gofunc like the one above, no?

**Review by logicalhan — COMMENTED** [review]
/lgtm
