### PR TITLE
[KEP-4191]: Fix issue in split filesystem

### LINKED ISSUE #126559: [KEP-4191] Support case when writeable layer and readable layers are on same mount but in different locations
### What would you like to be added?

In KEP-4191, we wanted to support a case where writable layers and readonly layers are on a separate disk.

This works fine but we found a bug if these layers are on the same disk but in different locations.

You can reproduce this by setting `graphRoot` and `imagestore` in crio storage to different locations.

### Why is this needed?

Kubelet should react to container storage configurations.

### PR DESCRIPTION
**Pull request by kannon92**
Fixes a bug where user can configure CRI-O to use imageStore and graphRoot on the same disk. We were incorrectly assuming that the system was separate but they can be on the same device.

#### Which issue(s) this PR fixes:

Fixes #126559

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue in the kubelet that showed when writeable layers and read-only layers were at different paths within the same mount.
Kubernetes was previously detecting that the image filesystem was split, even when that was not really the case.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/eviction/eviction_manager.go [hunk 1]
```diff
@@ -259,6 +260,17 @@ func (m *managerImpl) synchronize(diskInfoProvider DiskInfoProvider, podFunc Act
 		}
 		m.dedicatedImageFs = &hasImageFs
 		splitContainerImageFs := m.containerGC.IsContainerFsSeparateFromImageFs(ctx)
```
Comment (haircommander) [inline pkg/kubelet/eviction/eviction_manager.go:262]: do we even really need this check? if !m.dedicatedImageFs, then aren't we sure to not be split?

Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go:262]: We need to support the case where containerfs and imagefs are on the same disk but different from nodefs.

Comment (haircommander) [reply pkg/kubelet/eviction/eviction_manager.go:262]: I see, the function tests that? `IsContainerFsSeparateFromImageFs` seems like it's testing if imagefs==containerfs not if imagefs+containerfs == nodefs you know?

Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go:262]: yea. It looks to see if paths are different by talking with the CRI. It uses `ImageFsInfo` from container runtime to understand where these layers are stored. Since we only have path locations it will at least tell us if they are in different locations. 

The CRI doesn't really know about nodefs in this case. It only knows what the container runtime communicates back.

Comment (haircommander) [reply pkg/kubelet/eviction/eviction_manager.go:262]: yeah I guess my point in the original comment: would it really be a splitContainerImageFs if cadvisor didn't verify they're on different disks? ultimately that'd be the check. I don't see a situation where this containerGC check would help notice the contianerfs/imagefs are different from nodefs (don't we need to also ask cadvisor that?)

Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go:262]: True. I can rename the function. Its not possible to determine if a system is split from the just the CRI.

Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go:262]: CAdvisor is not exposed in the runtime service. It has access to imageService and runtimeService.

Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go:262]: We met offline. I’m going to drop this function call and introduce a dedicatedContainerFs function.

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Fix issue if writeable layers and read-only layers are on the same disk. We were detecting that the system is split but that is not really the case.
+Fixed an issue in the kubelet that showed when writeable layers and read-only layers were at different paths within the same mount.
+Kubernetes was previously detecting that the image filesystem was split, even when that was not really the case.
```

(is this revised text true? I guessed)

**Comment by sftim** [comment]
Let's avoid “disk”; you can use various things to back the image filesystem, including network storage or RAM.

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 2]
```diff
@@ -312,6 +312,12 @@ func (p *cadvisorStatsProvider) ImageFsStats(ctx context.Context) (imageFsRet *s
 	if err != nil {
 		return nil, nil, fmt.Errorf("failed to get container fs info: %w", err)
 	}
+	// ImageFs and ContainerFs could be on different paths on the same device.
+	if containerFsInfo.Device == imageFsInfo.Device {
+		return fsStats, fsStats, nil
+	}
+
+	klog.InfoS("Detect Split Filesystem", "ImageFilesystems", imageStats.ImageFilesystems[0], "ContainerFilesystems", imageStats.ContainerFilesystems[0])
```
Comment (sftim) [inline pkg/kubelet/stats/cadvisor_stats_provider.go:320]: aside: the message could be “Detected split storage for container image layers“.

File: pkg/kubelet/eviction/eviction_manager.go (hunk 1 above)
Comment (kannon92) [reply pkg/kubelet/eviction/eviction_manager.go]: PTAL @haircommander

**Comment by kannon92** [comment]
/priority important-soon
/triage accepted

important-soon in this case means I'd like to get this into 1.32 when it opens.

**Comment by pacoxu** [comment]
/assign @dchen1107 @mrunalp 
for approval

**Review by mrunalp — APPROVED** [review]
