### PR TITLE
Use zone from node for topology aware aws-ebs volume creation

### LINKED ISSUE #76975: Inefficient GetCandidateZonesForDynamicVolume impl caused aws api call throttling
**What happened**:

We have pretty large clusters in aws and in production, we found an inefficiency in provisioning dynamic EBS volumes, where aws-ebs volume provisioner tries to look for available zone from aws directly. With scale, this can trigger massive `Server.Unavailable` from ec2, and affect cluster stability.

This is also related to #76747

**What you expected to happen**:
To simply get zones with available instances, we can get information from API server for efficiency. There might be a delay between node gets shutting down and such change is reflected in api server, but in case node is not ready or gets terminated, there will be higher level reconciliation triggered so we are safe.

**How to reproduce it (as minimally and precisely as possible)**:
We only expect this to be hit when the cluster is huge (or aws account is huge) so not easy to reproduce.

/assign
/sig aws
/sig cloud-provider

### PR DESCRIPTION
**Pull request by zhan849**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
For topology aware (`WaitForFirstConsumer`) volume provisioning, node is already selected when we call cloud provider to create the volume. In aws-ebs volume provisioner, we currently still list ec2 instances for getting candidate zones, which is inefficient and redundant.

This PR keeps same behavior for volumes that need to bind immediately, but use zone info from bound node for topology aware volumes. If node for some reason does not have zone info recorded (which is unexpected), we double check with cloud provider.

With some 50pvc batch provisioning banchmark, this optimization can reduce 75% DescribeInstances calls, and reduce 50% peak QPS.

**Which issue(s) this PR fixes**:
Fixes #76975 

**Special notes for your reviewer**:
This issue is also being discussed in #78199 and #76976 , as reducing cloud provider calls is anyway necessary for optimizing topo aware volume provisioning code path, and whether and how to optimize finding zone for bind immediately volumes can be an orthogonal problem.

**Does this PR introduce a user-facing change?**:
No

**Release Note:**
```release-note
Use zone from node for topology aware aws-ebs volume creation to reduce unnecessary cloud provider calls
```

/sig storage aws scalability
/priority important-soon
/cc @msau42 @gnufied @liggitt @smarterclayton @mcrute

### CODE REVIEW

File: pkg/volume/awsebs/aws_util.go [hunk 1]
```diff
@@ -125,6 +128,39 @@ func (util *AWSDiskUtil) CreateVolume(c *awsElasticBlockStoreProvisioner, node *
...
+		} else {
+			// node controller should set zone label but somehow we cannot find it, fall back to retrieve information
+			// from cloud provider
+			klog.Warningf("Selected node %q does not have zone info for PVC %q, getting zone info from provider directly", selectedNode.Name, pvcName)
+			zone, err := cloud.GetZoneByProviderID(context.TODO(), selectedNode.Spec.ProviderID)
+			if err != nil {
+				return zones, err
+			}
+			klog.V(4).Infof("Using zone %q of selected node %q for PVC %q", zone.FailureDomain, selectedNode.Name, pvcName)
+			zones.Insert(zone.FailureDomain)
```
Comment (gnufied) [inline pkg/volume/awsebs/aws_util.go]: This is redundant. The underlying code will not use value returned from this function if `selectedNode` is set in `populateVolumeOptions` functions below. We can just return empty set from this function if `selectedNode != nil`

File: pkg/volume/awsebs/aws_util.go [hunk 2]
```diff
@@ -125,6 +128,39 @@ func (util *AWSDiskUtil) CreateVolume(c *awsElasticBlockStoreProvisioner, node *
 	return name, volumeOptions.CapacityGB, labels, fstype, nil
 }
 
+// getCandidateZones finds possible zones that a volume can be created in
+func getCandidateZones(cloud *aws.Cloud, selectedNode *v1.Node, pvcName string) (sets.String, error) {
```
Comment (gnufied) [inline pkg/volume/awsebs/aws_util.go]: Lets add some unit tests if we can...

File: pkg/volume/awsebs/aws_util.go (hunk 1 above)
Comment (zhan849) [reply pkg/volume/awsebs/aws_util.go]: I see your point, makes sense to me, and we can assume node controller will maintain zone labels here

File: pkg/volume/awsebs/aws_util.go (hunk 2 above)
Comment (zhan849) [reply pkg/volume/awsebs/aws_util.go]: I couldn't find a good way to mock `aws.Cloud` outside its package, so only added test cases for delayed binding test case. It's probably cloud provider's responsibility to provide reasonable mocks so I left a TODO here. please check

Comment (gnufied) [reply pkg/volume/awsebs/aws_util.go]: I think that is fine. `GetCandidateZonesForDynamicVolume` should already be considered "tested".

File: pkg/volume/awsebs/aws_util.go [hunk 3]
```diff
@@ -125,6 +127,30 @@ func (util *AWSDiskUtil) CreateVolume(c *awsElasticBlockStoreProvisioner, node *
...
+	var err error
+	zones := sets.NewString()
+	if selectedNode != nil {
+		// For topology aware volume provisioning, node is already selected so we use the zone from
+		// selected node directly. We can assume the information is always available as node controller
+		// shall maintain it
+		if zone, ok := selectedNode.Labels[v1.LabelZoneFailureDomain]; ok {
+			klog.V(4).Infof("Using zone %q of selected node %q for PVC %q", zone, selectedNode.Name, pvcName)
+			zones.Insert(zone)
```
Comment (gnufied) [inline pkg/volume/awsebs/aws_util.go]: We could just return completely empty set from here. There is no need to read `LabelZoneFailureDomain` too, because underlying code is already doing that.

Comment (zhan849) [reply pkg/volume/awsebs/aws_util.go]: you are right. thanks for pointing out. Done.

**Comment by gnufied** [comment]
Looks good to me. This code change should be fairly innocuous to land in. But I would wait for @jsafrane and @leakingtapan too. Will remove the hold once it has been reviewed by either of these folks.

/lgtm
/hold

File: pkg/volume/awsebs/aws_util.go [hunk 4]
```diff
@@ -125,6 +126,20 @@ func (util *AWSDiskUtil) CreateVolume(c *awsElasticBlockStoreProvisioner, node *
 	return name, volumeOptions.CapacityGB, labels, fstype, nil
 }
 
+// getCandidateZones finds possible zones that a volume can be created in
+func getCandidateZones(cloud *aws.Cloud, selectedNode *v1.Node, pvcName string) (sets.String, error) {
```
Comment (jsafrane) [inline pkg/volume/awsebs/aws_util.go]: Why is `pvcName` passed as an argument?

File: pkg/volume/awsebs/aws_ebs_test.go [hunk 5]
```diff
@@ -376,3 +378,38 @@ func TestMountOptions(t *testing.T) {
...
+		{
+			cloud: nil,
+			node: &v1.Node{
+				ObjectMeta: metav1.ObjectMeta{
+					Labels: map[string]string{
+						v1.LabelZoneFailureDomain: testZone,
+					},
+				},
+			},
+			expectedZones: sets.NewString(),
```
Comment (jsafrane) [inline pkg/volume/awsebs/aws_ebs_test.go]: The tests don't seem to be useful to me if they check the zones to be empty.

Comment (zhan849) [reply pkg/volume/awsebs/aws_ebs_test.go]: so the reasoning here for the function is - if we have a selected node, there should not be a "candidate zone" returned, and if not (bind immediately), we should compute candidate zone. once we have better way to mock aws cloud provider, we need to add other test cases.

Or since the logic is rather simple, I can remove the added helper and combine the logic in `CreateVolume` so we can remove the test. What do you think?

File: pkg/volume/awsebs/aws_util.go (hunk 4 above)
Comment (zhan849) [reply pkg/volume/awsebs/aws_util.go]: my bad, forgot to remove it during a refactor, changed the signature.

**Comment by gnufied** [comment]
@jsafrane I think this should be good to go. Can you approve?

**Comment by jsafrane** [comment]
I think the PR is OK, just the unit test does not seem to be really useful. On the other hand, it fits well the rest of the AWS provider :-)

/approve

This is a bug fix, trying to squeeze into 1.15.

**Comment by zhan849** [comment]
> I think the PR is OK, just the unit test does not seem to be really useful. On the other hand, it fits well the rest of the AWS provider :-)
> 
> /approve
> 
> This is a bug fix, trying to squeeze into 1.15.

Thanks @jsafrane for milestone 1.15, do I need to send out PR for cherry-pick or there will be an automatic process for this?

**Comment by jsafrane** [comment]
It has been merged to master, AFAIK it should get promoted to 1.15 branch automatically (if it is not there yet).
