### PR TITLE
win: fix cpu count to calculate cpu_maximum

### LINKED ISSUE #114211: windows cpu maximum incorrect with more than one processor group
### What happened?

When submitting a windows pod using resource limits on a node with more than one processor group, the specified `CpuMaximum` count is incorrect due to the usage of `runtime.NumCPU()` which does not take processor groups into account.

For example:
- node with 96 cores
- cpu limit 94
- `runtime.NumCPU()` returns `48`

This results in a CPU maximum of 10000 since the range is from [1, 10000]:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container_windows.go#L82..L91

```go
	limit := int64(94 * 1000)
	numCPU := 48
	fmt.Println(((10000 * limit) / int64(numCPU) / 1000))

// Output:
// 19583
```

Our initial goal for this was to limit a process to not use all available CPU and therefore render the node uncontrollable. 

### What did you expect to happen?

A CPU maximum of `9791` instead of `10000` for that specific case. For the calculation, it should use the CPU count for all available processor groups instead of just the current one. 

### How can we reproduce it (as minimally and precisely as possible)?

Launch a node with a lot of CPUs, for example [a Azure Standard_D96a_v4](https://learn.microsoft.com/en-us/azure/virtual-machines/dav4-dasv4-series) and schedule the following pod on it:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: debug-windows
  namespace: default
spec:
  containers:
  - args:
    - ping /t 127.0.0.1
    command:
    - cmd
    - /c
    image: mcr.microsoft.com/windows/nanoserver:1809
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        cpu: "94"
        memory: 300Gi
      requests:
        cpu: "90"
        memory: 200Gi
  nodeSelector:
    kubernetes.io/os: windows
```

Then SSH into the node and inspect the running container using `crictl.exe inspect <id>`. The `cpu_maximum` value will be set to 10000. 

### Anything else we need to know?

[tklauser/numcpus](https://github.com/tklauser/numcpus) (which just uses [`windows.GetActiveProcessorCount()`](https://pkg.go.dev/golang.org/x/sys/windows#GetActiveProcessorCount)) is able to correctly find out the number of CPUs available to a system. Using `golang.org/x/sys/windows` for calculation or incorporating that code might solve this issue. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>


### Cloud provider

<details>
Azure in-tree
</details>


### OS version

<details>

```console
# On Windows:
PS C:\Users\capi> wmic os get Caption                                                                                                                                                       
Caption                                                                                                                                                                                     
Microsoft Windows Server 2019 Datacenter                                                                                                                                                    
                                                                                                                                                                                            
PS C:\Users\capi> wmic os get Version                                                                                                                                                       
Version                                                                                                                                                                                     
10.0.17763                                                                                                                                                                                  
                                                                                                                                                                                            
PS C:\Users\capi> wmic os get Buildnumber                                                                                                                                                   
BuildNumber                                                                                                                                                                                 
17763                                                                                                                                                                                       
                                                                                                                                                                                            
PS C:\Users\capi> wmic os get osarchitecture                                                                                                                                                
OSArchitecture                                                                                                                                                                              
64-bit
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.10
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mweibel**
/sig windows
/hold

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Take all processor groups into account when calculating cpu maximum for windows.

Signed-off-by: Michael Weibel <michael@helio.exchange>

#### Which issue(s) this PR fixes:

Fixes #114211

#### Special notes for your reviewer:
I'd appreciate help with writing tests for this. 

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue when calculating CPU limits on Windows nodes with more than 64 logical processors
```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go [hunk 1]
```diff
@@ -79,7 +73,8 @@ func (m *kubeGenericRuntimeManager) generateWindowsContainerConfig(container *v1
 		//   https://github.com/opencontainers/runtime-spec/blob/ad53dcdc39f1f7f7472b10aa0a45648fe4865496/config-windows.md#cpu
 		//   If both CpuWeight and CpuMaximum are set - ContainerD catches this invalid case and returns an error instead.
 
-		cpuMaximum := 10000 * cpuLimit.MilliValue() / int64(runtime.NumCPU()) / 1000
+		numCPU := int64(winstats.ProcessorCount())
```
Comment (aravindhp) [inline pkg/kubelet/kuberuntime/kuberuntime_container_windows.go:76]: One suggestion would be to inline this as it was done before instead of introducing a single use variable.

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go [hunk 2]
```diff
@@ -79,7 +73,8 @@ func (m *kubeGenericRuntimeManager) generateWindowsContainerConfig(container *v1
...
+		cpuMaximum := 10000 * cpuLimit.MilliValue() / numCPU / 1000
```
Comment (profnandaa) [inline pkg/kubelet/kuberuntime/kuberuntime_container_windows.go:77]: What's with the multiplication by `10000`, then division by `1000`; can simplify to just multiplication by `10`?

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go (hunk 1 above)
Comment (mweibel) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go]: for testing and clarity reasons I extracted the calculation into an own function but did inline the `numCPU` again. LMK if that's fine.

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go (hunk 2 above)
Comment (mweibel) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go]: I'm not sure if I should do this in this PR since the PR's goal is just about the CPU count. However since I added unit tests while extracting the calculation, I also opted for adding your proposed simplification 👍

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go (hunk 1 above)
Comment (aravindhp) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go]: That's even better @mweibel

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go (hunk 2 above)
Comment (aravindhp) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go]: I like the simplification 👍🏽 Do we need a comment about it in case we come back to this and the calculation is not immediately obvious to us?

Comment (mweibel) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go]: I'm not quite sure how I'd phrase that. Could you suggest something please? Thanks 🙂 

Whether it's needed or not is debatable I guess. git history is there and the relevant docs on microsofts side are there, too. But over time it'll become harder to find the original reason why it got changed. A comment might help in this case.

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go [hunk 3]
```diff
@@ -128,3 +113,16 @@ func (m *kubeGenericRuntimeManager) generateWindowsContainerConfig(container *v1
 
 	return wc, nil
 }
+
+// calculateCPUMaximum calculates the maximum CPU given a limit and a number of cpus while ensuring it's in range [1,10000].
+func calculateCPUMaximum(cpuLimit *resource.Quantity, cpuCount int64) int64 {
+	cpuMaximum := 10 * cpuLimit.MilliValue() / cpuCount
```
Comment (jsturtevant) [inline pkg/kubelet/kuberuntime/kuberuntime_container_windows.go:119]: I am pretty sure this is equivalent to prior code, based on the [order of operations](https://go.dev/ref/spec#Operator_precedence) in golang though we've definitely had trouble in the area of the code base in the past so I feel paranoid 😨. Did you add the tests prior to making the code change to ensure things are the same?  

The code that is linked in the comment does it differently (https://github.com/moby/moby/blob/10866714412aea1bb587d1ad14b2ce1ba4cf4308/daemon/oci_windows.go#L426)  not sure I know why it was done slightly differently here.

@marosset want to double check this simplification is ok?

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go [hunk 4]
```diff
@@ -101,3 +98,48 @@ func TestApplyPlatformSpecificContainerConfig(t *testing.T) {
 	}
 	assert.Equal(t, expectedWindowsConfig, containerConfig.Windows)
 }
+
+func TestCalculateCPUMaximum(t *testing.T) {
```
Comment (jsturtevant) [inline pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go:102]: Thanks for adding tests to cover this section!  It looks like there was some coverage in the test above but this adds coverage for cpucounts greater than 64. In particular might need to change line 87 `expectedCpuMax := ((10000 * 3000) / int64(runtime.NumCPU()) / 1000)` or that would fail if run on a larger machine

**Comment by mweibel** [comment]
@matthyx this would be ready to review from my point of view. Is it fine to ping you? :)

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go (hunk 4 above)
Comment (matthyx) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go:102]: yes please

**Review by matthyx — CHANGES_REQUESTED** [review]
adjust tests based on @jsturtevant comment

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows.go (hunk 3 above)
Comment (mweibel) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows.go:119]: going to resolve this - let me know if you still have concerns.

File: pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go (hunk 4 above)
Comment (mweibel) [reply pkg/kubelet/kuberuntime/kuberuntime_container_windows_test.go:103]: adjusted 👍

**Comment by mweibel** [comment]
@matthyx thanks for the review. I adjusted the test accordingly. Ready to review again.

**Comment by matthyx** [comment]
/lgtm
waiting for another review from sig windows

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Comment by mweibel** [comment]
👍 thanks. Tests passed!

**Comment by jsturtevant** [comment]
lgtm 
/assign @marosset @claudiubelu

**Review by marosset — APPROVED** [review]
/lgtm

@mweibel - Can you update the release notes to something like `Fixing issue on Windows when calculating cpu limits on nodes with more than 64 logical processors' ?

**Comment by mweibel** [comment]
@marosset thanks! I updated the PR to include the release note.

**Comment by mweibel** [comment]
folks, what can I do to get this approved?

**Comment by jsturtevant** [comment]
looks like it is on the sig-node triage board marked ready for approval.  Will need someone from the kubelet approvers file to give the approval.

/assign @derekwaynecarr @mrunalp

**Comment by dims** [comment]
The PR just touches windows related code and nothing in kubelet and has a bunch of LGTM(s) from sig-windows folks. Happy to land this with my sig-node reviewer hat on.

/approve

**Comment by mweibel** [comment]
@sftim thanks - applied it on the first comment. I assume when generating the changelog it'll take this into account?

**Comment by sftim** [comment]
> I assume when generating the changelog it'll take this into account?

That's what I understand. Thanks for the tweak.
