### PR TITLE
Revert "add e2e test for Service ExternalIPs"

### LINKED ISSUE #96222: [Failing Test] gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)
**Which jobs are failing**:
`ci-kubernetes-e2e-ubuntu-gce`

**Which test(s) are failing**:

- `Kubernetes e2e suite.[sig-network] Services should be possible to connect to a service via ExternalIP when the external IP is not assigned to a node`
- `Overall`
- `Test`

**Since when has it been failing**:
`11-04 19:33 PST `

**Testgrid link**:
`https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-ubuntu-master-default`

**Reason for failure**:
`/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1187
Nov  4 11:59:41.385: Unexpected error:
    <*errors.errorString | 0xc00298c3d0>: {
        s: "service is not reachable within 2m0s timeout on endpoint 203.0.113.250:80 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 203.0.113.250:80 over TCP protocol
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1210`

**Anything else we need to know**:
/priority important-soon
/sig network
/cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by aojea**
This reverts commit 0ed8fd6dc9befb1d19ca05edf5b042ff26dcb94d.

It turns out that ExternalIPs are not allowed to be reachable from
pods unless the IP is present in the node.
However, due to a kube-proxy limitation it was working in environment
that used CNIs without bridges for the pods.

/kind failing-test
```release-note
NONE
```

Fixes: https://github.com/kubernetes/kubernetes/issues/96222

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
/retest
apimachinery test

**Comment by dims** [comment]
/assign @andrewsykim
/approve
/lgtm

( i don't have karma here :) )

**Comment by aojea** [comment]
3 times failed the same test?????
>  Kubernetes e2e suite: [sig-api-machinery] ResourceQuota should create a ResourceQuota and capture the life of a configMap. [Conformance] expand_less

but how is that related? @liggit I couldn't find a connection with this PR but hitting 3 failures in a row  in the same job and test worries me
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by liggitt** [comment]
> but how is that related? @liggitt I couldn't find a connection with this PR but hitting 3 failures in a row in the same job and test worries me

the test has an inherent flake that https://github.com/kubernetes/kubernetes/pull/96197#issuecomment-722070670 made worse. improved in https://github.com/kubernetes/kubernetes/pull/96265 but that test probably needs to be rethought

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -1179,37 +1179,6 @@ var _ = SIGDescribe("Services", func() {
 		framework.ExpectNoError(err)
 	})
 
-	/*
-		Create a ClusterIP service with an External IP that is not assigned to an interface.
-		The IP ranges here are reserved for documentation according to
-		[RFC 5737](https://tools.ietf.org/html/rfc5737) Section 3 and should not be used by any host.
-	*/
-	ginkgo.It("should be possible to connect to a service via ExternalIP when the external IP is not assigned to a node", func() {
```
Comment (andrewsykim) [inline test/e2e/network/service.go:1187]: So the problem is that externalIP is **not** allowed for any pods inside a bridge but because some CNIs don't use bridges it was allowed in some clusters?

Comment (andrewsykim) [reply test/e2e/network/service.go:1187]: So basically any cluster that is using a bridge is failing this test (as expected)?

Comment (aojea) [reply test/e2e/network/service.go:1187]: exactly, https://github.com/kubernetes/kubernetes/issues/95785#issuecomment-722255763

when using a ptp interface it considers that traffic is coming from outside and it goes through.

We have to sort out first the definition of ExternalIP first, this is breaking multiple CIs now ...

**Comment by andrewsykim** [comment]
Approving since this is breaking a bunch of CI jobs, but in general I think we should have a larger discussion on why we disallow externalIP access from bridges. My guess is that we only wanted to allow "external" traffic, but how we determine "external" should be done in the same way we determine it for node ports, load balancer IPs and other Service concepts. It shouldn't inherently be tied to bridges which many CNIs don't even use today.   

/approve
/lgtm

File: test/e2e/network/service.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/service.go:1187]: > So basically any cluster that is using a bridge is failing this test (as expected)?

we should clarify that IMHO, the definition can not be done by the implementation constraints
