### PR TITLE
Fix race conditions and timing issues in preemption tests

### LINKED ISSUE #137320: Flaky TestPreemption tests
### Which jobs are flaking?

integration-race-master

### Which tests are flaking?

test/integration/scheduler: preemption 

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-race-master/2027280264740212736

```
 RUN   TestPreemptionRespectsWaitingPod
    preemption_test.go:1720: Creating victim pod
    preemption_test.go:1726: Waiting for victim to reach WaitOnPermit
    preemption_test.go:1729: Victim reached WaitOnPermit
    preemption_test.go:1743: Creating preemptor pod
    preemption_test.go:1755: Waiting for preemptor to be scheduled
    preemption_test.go:1776: Failed waiting for preemptor validation: context deadline exceeded
--- FAIL: TestPreemptionRespectsWaitingPod (20.10s)
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-race-master/2027733410214055936

```
=== RUN   TestPreemptionRespectsBindingPod
    preemption_test.go:1931: Creating victim pod
    preemption_test.go:1938: Waiting for victim to reach PreBind
    preemption_test.go:1941: Victim reached PreBind
    preemption_test.go:1956: Creating preemptor pod
    preemption_test.go:2002: Preemptor should be scheduled on big-node, but was scheduled on small-node
--- FAIL: TestPreemptionRespectsBindingPod (6.90s)
```

### Since when has it been flaking?

2026-02-26, commit b55862975, okay in 225eb9047 and older

### Testgrid link

https://testgrid.k8s.io/sig-testing-canaries#integration-race-master

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig scheduling

### PR DESCRIPTION
**Pull request by srivastav-abhishek**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
This PR added mutex to prevent race conditions in node assignment and fixed timing issues in node assignment for preemption tests

#### Which issue(s) this PR is related to:
Fixes #137320

#### Special notes for your reviewer:
I utilised agent help to root cause the issue and changes with respect to node-assignment polling. Here is the o/p from stress tool with the fix,

```
# stress ./preemption.test -test.run TestPreemptionRespectsBindingPod
5s: 0 runs so far, 0 failures, 8 active
10s: 0 runs so far, 0 failures, 8 active
15s: 0 runs so far, 0 failures, 8 active
20s: 8 runs so far, 0 failures, 8 active
25s: 10 runs so far, 0 failures, 8 active
30s: 15 runs so far, 0 failures, 8 active
35s: 19 runs so far, 0 failures, 8 active
40s: 24 runs so far, 0 failures, 8 active
45s: 28 runs so far, 0 failures, 8 active
50s: 33 runs so far, 0 failures, 8 active
55s: 37 runs so far, 0 failures, 8 active
1m0s: 43 runs so far, 0 failures, 8 active
1m5s: 47 runs so far, 0 failures, 8 active
1m10s: 52 runs so far, 0 failures, 8 active
1m15s: 57 runs so far, 0 failures, 8 active
1m20s: 62 runs so far, 0 failures, 8 active
1m25s: 67 runs so far, 0 failures, 8 active
1m30s: 71 runs so far, 0 failures, 8 active
1m35s: 76 runs so far, 0 failures, 8 active
1m40s: 80 runs so far, 0 failures, 8 active
1m45s: 85 runs so far, 0 failures, 8 active
1m50s: 90 runs so far, 0 failures, 8 active
1m55s: 94 runs so far, 0 failures, 8 active
2m0s: 99 runs so far, 0 failures, 8 active
2m5s: 104 runs so far, 0 failures, 8 active
2m10s: 109 runs so far, 0 failures, 8 active
2m15s: 113 runs so far, 0 failures, 8 active
2m20s: 118 runs so far, 0 failures, 8 active
2m25s: 123 runs so far, 0 failures, 8 active
2m30s: 127 runs so far, 0 failures, 8 active
2m35s: 132 runs so far, 0 failures, 8 active
2m40s: 137 runs so far, 0 failures, 8 active
2m45s: 142 runs so far, 0 failures, 8 active
2m50s: 145 runs so far, 0 failures, 8 active
2m55s: 150 runs so far, 0 failures, 8 active
3m0s: 154 runs so far, 0 failures, 8 active
3m5s: 159 runs so far, 0 failures, 8 active
3m10s: 164 runs so far, 0 failures, 8 active
3m15s: 169 runs so far, 0 failures, 8 active
3m20s: 173 runs so far, 0 failures, 8 active
3m25s: 177 runs so far, 0 failures, 8 active
3m30s: 183 runs so far, 0 failures, 8 active
3m35s: 187 runs so far, 0 failures, 8 active
3m40s: 192 runs so far, 0 failures, 8 active
3m45s: 197 runs so far, 0 failures, 8 active
3m50s: 202 runs so far, 0 failures, 8 active
3m55s: 206 runs so far, 0 failures, 8 active
4m0s: 211 runs so far, 0 failures, 8 active
4m5s: 216 runs so far, 0 failures, 8 active
4m10s: 220 runs so far, 0 failures, 8 active
4m15s: 225 runs so far, 0 failures, 8 active
4m20s: 230 runs so far, 0 failures, 8 active
4m25s: 235 runs so far, 0 failures, 8 active
4m30s: 239 runs so far, 0 failures, 8 active
4m35s: 244 runs so far, 0 failures, 8 active
4m40s: 249 runs so far, 0 failures, 8 active
4m45s: 254 runs so far, 0 failures, 8 active
4m50s: 258 runs so far, 0 failures, 8 active
4m55s: 263 runs so far, 0 failures, 8 active
5m0s: 267 runs so far, 0 failures, 8 active
5m5s: 272 runs so far, 0 failures, 8 active
5m10s: 277 runs so far, 0 failures, 8 active
5m15s: 281 runs so far, 0 failures, 8 active
5m20s: 286 runs so far, 0 failures, 8 active
5m25s: 291 runs so far, 0 failures, 8 active
5m30s: 296 runs so far, 0 failures, 8 active
5m35s: 300 runs so far, 0 failures, 8 active
5m40s: 304 runs so far, 0 failures, 8 active
5m45s: 310 runs so far, 0 failures, 8 active
5m50s: 314 runs so far, 0 failures, 8 active
5m55s: 318 runs so far, 0 failures, 8 active
6m0s: 323 runs so far, 0 failures, 8 active
6m5s: 328 runs so far, 0 failures, 8 active
6m10s: 333 runs so far, 0 failures, 8 active
6m15s: 338 runs so far, 0 failures, 8 active
6m20s: 342 runs so far, 0 failures, 8 active
6m25s: 347 runs so far, 0 failures, 8 active
6m30s: 351 runs so far, 0 failures, 8 active
6m35s: 356 runs so far, 0 failures, 8 active
6m40s: 360 runs so far, 0 failures, 8 active
6m45s: 366 runs so far, 0 failures, 8 active
6m50s: 370 runs so far, 0 failures, 8 active
6m55s: 374 runs so far, 0 failures, 8 active
7m0s: 379 runs so far, 0 failures, 8 active
7m5s: 384 runs so far, 0 failures, 8 active
7m10s: 389 runs so far, 0 failures, 8 active
7m15s: 393 runs so far, 0 failures, 8 active
7m20s: 398 runs so far, 0 failures, 8 active
7m25s: 403 runs so far, 0 failures, 8 active
7m30s: 407 runs so far, 0 failures, 8 active
7m35s: 412 runs so far, 0 failures, 8 active
7m40s: 417 runs so far, 0 failures, 8 active
7m45s: 421 runs so far, 0 failures, 8 active
7m50s: 426 runs so far, 0 failures, 8 active
7m55s: 431 runs so far, 0 failures, 8 active
8m0s: 435 runs so far, 0 failures, 8 active
8m5s: 440 runs so far, 0 failures, 8 active
8m10s: 445 runs so far, 0 failures, 8 active
8m15s: 449 runs so far, 0 failures, 8 active
8m20s: 454 runs so far, 0 failures, 8 active
8m25s: 459 runs so far, 0 failures, 8 active
8m30s: 464 runs so far, 0 failures, 8 active
8m35s: 469 runs so far, 0 failures, 8 active
8m40s: 473 runs so far, 0 failures, 8 active
8m45s: 478 runs so far, 0 failures, 8 active
8m50s: 483 runs so far, 0 failures, 8 active
8m55s: 487 runs so far, 0 failures, 8 active
9m0s: 492 runs so far, 0 failures, 8 active
9m5s: 497 runs so far, 0 failures, 8 active
9m10s: 502 runs so far, 0 failures, 8 active
9m15s: 507 runs so far, 0 failures, 8 active
9m20s: 512 runs so far, 0 failures, 8 active
9m25s: 516 runs so far, 0 failures, 8 active
9m30s: 519 runs so far, 0 failures, 8 active
9m35s: 525 runs so far, 0 failures, 8 active
9m40s: 529 runs so far, 0 failures, 8 active
9m45s: 534 runs so far, 0 failures, 8 active
9m50s: 539 runs so far, 0 failures, 8 active
9m55s: 544 runs so far, 0 failures, 8 active
10m0s: 548 runs so far, 0 failures, 8 active
10m5s: 553 runs so far, 0 failures, 8 active
10m10s: 558 runs so far, 0 failures, 8 active
```

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

File: test/integration/scheduler/preemption/preemption_test.go [hunk 1]
```diff
@@ -1709,7 +1716,9 @@ func TestPreemptionRespectsWaitingPod(t *testing.T) {
 	victimToBlock := &blockedPod{
 		blocked: make(chan struct{}),
 	}
+	plugin.mu.Lock()
 	plugin.podsToBlock[victim.Name] = victimToBlock
+	plugin.mu.Unlock()
```
Comment (macsko) [inline test/integration/scheduler/preemption/preemption_test.go]: I think it will be enough to just move `plugin.podsToBlock[victim.Name] = victimToBlock` (without the mutex) above `testCtx := testutils.InitTestSchedulerWithOptions`. Then, we can be sure it won't race, because the permit is synchronous

File: test/integration/scheduler/preemption/preemption_test.go [hunk 2]
```diff
@@ -1914,12 +1927,14 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
...
 		released:    make(chan struct{}),
 	}
+	plugin.mu.Lock()
 	plugin.podToChannels[victim.Name] = victimBlockingPlugin
 	plugin.podToChannels[preemptor.Name] = &perPodBlockingPlugin{
 		shouldBlock: false,
 		blocked:     make(chan struct{}),
 		released:    make(chan struct{}),
 	}
+	plugin.mu.Unlock()
```
Comment (macsko) [inline test/integration/scheduler/preemption/preemption_test.go]: Similarly, we can move these podToChannels changes without the mutex above the `testCtx := testutils.InitTestSchedulerWithOptions`

File: test/integration/scheduler/preemption/preemption_test.go [hunk 3]
```diff
@@ -1985,21 +2000,55 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
...
-	}
-	if v.Spec.NodeName != "small-node" {
-		t.Fatalf("Victim should be scheduled on node2, but was scheduled on %s", v.Spec.NodeName)
+		t.Fatalf("Failed waiting for preemptor to be scheduled: %v", err)
 	}
 
-	p, err := cs.CoreV1().Pods(testCtx.NS.Name).Get(testCtx.Ctx, preemptor.Name, metav1.GetOptions{})
+	// 5. Verify final node assignments with proper synchronization.
+	// The PodScheduled condition can be set before Spec.NodeName is fully persisted,
+	// so we need to wait until both pods have their final node assignments.
```
Comment (macsko) [inline test/integration/scheduler/preemption/preemption_test.go]: It's incorrect. The PodScheduled condition is set in API server at the same time as the NodeName is. We can leave the previous version, without waiting here

File: test/integration/scheduler/preemption/preemption_test.go (hunk 1 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: I agree, have included the changes suggested. TY :)

File: test/integration/scheduler/preemption/preemption_test.go (hunk 2 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Done.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 3 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Removed this wait condition.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 4]
```diff
@@ -1645,9 +1645,13 @@ func (pl *blockingPermitPlugin) Name() string {
 }
 
 func (pl *blockingPermitPlugin) Permit(ctx context.Context, state fwk.CycleState, pod *v1.Pod, nodeName string) (*fwk.Status, time.Duration) {
-	if p, ok := pl.podsToBlock[pod.Name]; ok {
-		p.blocked <- struct{}{}
+	p, ok := pl.podsToBlock[pod.Name]
+	if ok {
```
Comment (mm4tt) [inline test/integration/scheduler/preemption/preemption_test.go]: What is the reason for having two same if ok { ... } blocks one after another? Cannot we just have:

```
if p, ok := pl.podsToBlock[pod.Name]; ok {
		delete(pl.podsToBlock, pod.Name)
		p.blocked <- struct{}{}
		return fwk.NewStatus(fwk.Wait, "waiting"), time.Minute
	}

```

File: test/integration/scheduler/preemption/preemption_test.go
Comment (mm4tt) [inline test/integration/scheduler/preemption/preemption_test.go]: This should be 4. Also can we update the comment to say: "Wait for victim to be scheduled" becaue this is what actually happens in this step.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 5]
```diff
@@ -1985,23 +1982,40 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
 		t.Fatalf("Failed waiting for victim validation: %v", err)
 	}
 
-	// 6. Check that preemptor and victim are scheduled on expected nodes: victim on a small node and preemptor on a big node.
+	// 4. Wait for preemptor to be scheduled.
```
Comment (mm4tt) [inline test/integration/scheduler/preemption/preemption_test.go]: This should be 5. given we actually have 4. above.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 6]
```diff
@@ -1985,23 +1982,40 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
...
-		t.Fatalf("Victim should be scheduled on node2, but was scheduled on %s", v.Spec.NodeName)
-	}
 
 	p, err := cs.CoreV1().Pods(testCtx.NS.Name).Get(testCtx.Ctx, preemptor.Name, metav1.GetOptions{})
 	if err != nil {
 		t.Fatalf("Error getting preemptor: %v", err)
 	}
+	// Verify the assignments are correct
+	if v.Spec.NodeName != "small-node" {
+		t.Fatalf("victim should be scheduled on small-node, but was scheduled on %s", v.Spec.NodeName)
```
Comment (mm4tt) [inline test/integration/scheduler/preemption/preemption_test.go]: NIT: Conceptually this should be t.Errorf. Failing here doesn't block us from checking preemptor's node name.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 7]
```diff
@@ -1985,23 +1982,40 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
...
+	}
 	if p.Spec.NodeName != "big-node" {
-		t.Fatalf("Preemptor should be scheduled on big-node, but was scheduled on %s", v.Spec.NodeName)
+		t.Fatalf("preemptor should be scheduled on big-node, but was scheduled on %s", p.Spec.NodeName)
```
Comment (mm4tt) [inline test/integration/scheduler/preemption/preemption_test.go]: Same here

**Review by mm4tt — COMMENTED** [review]
This looks good modulo small comments

File: test/integration/scheduler/preemption/preemption_test.go (hunk 4 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Yes agreed. I have done the changes in latest patch. TY !

File: test/integration/scheduler/preemption/preemption_test.go
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Updated the comment as suggested.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 5 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Done.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 6 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Updated to `t.Errorf`.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 7 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Done.

**Comment by srivastav-abhishek** [comment]
> This looks good modulo small comments

Thanks @mm4tt for reviewing. I have addressed your concerns, could you ptal ?

File: test/integration/scheduler/preemption/preemption_test.go [hunk 8]
```diff
@@ -1959,7 +1951,7 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
 		t.Fatalf("Error creating preemptor: %v", err)
 	}
 
-	// 3. Wait for preemptor to be scheduled (or at least nominated) and Check victim
+	// 4. Wait for victim to be scheduled.
```
Comment (macsko) [inline test/integration/scheduler/preemption/preemption_test.go]:
```suggestion
	// 4. Wait for victim to be rescheduled.
```

File: test/integration/scheduler/preemption/preemption_test.go [hunk 9]
```diff
@@ -1875,14 +1867,26 @@ func TestPreemptionRespectsBindingPod(t *testing.T) {
...
 	err := registry.Register(blockingPreBindPluginName, func(ctx context.Context, obj runtime.Object, fh fwk.Handle) (fwk.Plugin, error) {
-		pl, err := newBlockingPreBindPlugin(ctx, obj, fh)
-		if err == nil {
-			plugin = pl.(*blockingPreBindPlugin)
-		}
-		return pl, err
+		return &blockingPreBindPlugin{
+			podToChannels: podToChannels,
+			handle:        fh,
+		}, nil
```
Comment (macsko) [inline test/integration/scheduler/preemption/preemption_test.go]: nit:
Don't remove the `newBlockingPreBindPlugin`, but just modify it by adding `podToChannels` args and use it here.

Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Thank you @macsko. I have addressed the comment.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 8 above)
Comment (srivastav-abhishek) [reply test/integration/scheduler/preemption/preemption_test.go]: Done.
