### PR TITLE
Fix unknown admission control failure for ubuntu deployment

### LINKED ISSUE #14474: deployment for ubuntu fails for unknown admission plugin
api-server fails to start with admission control DenyEscalatingExec on ubuntu 14.04 
```
$ log for kube-apiserver
F0924 15:12:51.526539   25709 plugins.go:106] Unknown admission plugin: DenyEscalatingExec
```
Once I deprecate the plugin DenyEscalatingExec, everything works fine again.

Related to #13447
/cc @pweil- @derekwaynecarr 
/cc @resouer  @WIZARD-CXY

### PR DESCRIPTION
**Pull request by dalanlan**
- Fix #14474
  Deployment failure of unknown admission plugin DenyEscalatingExec 
- Follow-up for #13962 & #13712
  Doc enhancement
- upgrade k8s to 1.0.6

### CODE REVIEW

File: cluster/ubuntu/config-default.sh [hunk 1]
```diff
@@ -35,7 +35,7 @@ export SERVICE_CLUSTER_IP_RANGE=${SERVICE_CLUSTER_IP_RANGE:-192.168.3.0/24}  # f
 export FLANNEL_NET=${FLANNEL_NET:-172.16.0.0/16}
 
 # Admission Controllers to invoke prior to persisting objects in cluster
-export ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,DenyEscalatingExec,SecurityContextDeny
+export ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,SecurityContextDeny
```
Comment (pweil-) [inline cluster/ubuntu/config-default.sh]: :+1: to this.  It shouldn't have been added here since Ubuntu is using a specific version.  Thanks for the catch.

**Comment by dalanlan** [comment]
ping @brendandburns

File: docs/getting-started-guides/ubuntu.md [hunk 2]
```diff
@@ -135,7 +134,9 @@ that conflicts with your own private network range.
 The `FLANNEL_NET` variable defines the IP range used for flannel overlay network,
 should not conflict with above `SERVICE_CLUSTER_IP_RANGE`.
 
-**Note:** When deploying, master needs to connect the Internet to download the necessary files. If your machines locate in a private network that need proxy setting to connect the Internet, you can set the config `PROXY_SETTING` in cluster/ubuntu/config-default.sh such as:
+**Note:** When deploying, master needs to connect the Internet to download the necessary files.
+If your machines locate in a private network that need proxy setting to connect the Internet,
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: If your machines are located in a ...

File: docs/getting-started-guides/ubuntu.md [hunk 3]
```diff
@@ -143,16 +144,16 @@ After all the above variables being set correctly, we can use following command
 
 `$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh`
 
-The scripts automatically scp binaries and config files to all the machines and start the k8s service on them.
+The scripts automatically scp binaries and config files to all the machines and start k8s service on them.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: `scp` (code font)

Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: please use the full kubernetes not 'k8s' for clarity

File: docs/getting-started-guides/ubuntu.md [hunk 4]
```diff
@@ -250,17 +251,20 @@ the latter one could start it again.
 4. You can also customize your own settings in `/etc/default/{component_name}`.
 
 
-### Upgrading a Cluster
+## Upgrading a Cluster
 
 If you already have a kubernetes cluster, and want to upgrade to a new version,
-you can use following command in cluster/ directory to update the whole cluster or a specified node to a new version.
+you can use following command in cluster/ directory to update the whole cluster
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: ... you can use the following command ...

File: docs/getting-started-guides/ubuntu.md [hunk 5]
```diff
@@ -250,17 +251,20 @@ the latter one could start it again.
...
+or a specified node to a new version.
 
 ```console
 $ KUBERNETES_PROVIDER=ubuntu ./kube-push.sh [-m|-n <node id>] <version>
 ```
 
 It can be done for all components (by default), master(`-m`) or specified node(`-n`).
-If the version is not specified, the script will try to use local binaries.You should ensure all the binaries are well prepared in path `cluster/ubuntu/binaries`.
+Upgrading single node is experimental now.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: Upgrading a single node is currently experimental.

File: docs/getting-started-guides/ubuntu.md [hunk 6]
```diff
@@ -55,42 +56,40 @@ work, which has been merge into this document.
 ## Prerequisites
 
 1. The nodes have installed docker version 1.2+ and bridge-utils to manipulate linux bridge.
-2. All machines can communicate with each other. Master node needs to connect the Internet to download the necessary files, while working nodes do not.
+2. All machines can communicate with each other. Master node needs to connect the Internet to download
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: ... The master node needs to be connected to the Internet to download ...

File: docs/getting-started-guides/ubuntu.md [hunk 7]
```diff
@@ -55,42 +56,40 @@ work, which has been merge into this document.
...
+the necessary files, while working nodes do not.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: s/working/worker/

**Comment by brendandburns** [comment]
LGTM, minor wording tweaks

**Comment by dalanlan** [comment]
The comments are addressed  @brendandburns

**Comment by dalanlan** [comment]
ping @brendandburns  
PTAL. Also please re-trigger e2e, which is not required though.

File: docs/getting-started-guides/ubuntu.md [hunk 8]
```diff
@@ -135,24 +134,27 @@ that conflicts with your own private network range.
...
 
 ```console
 Deploying minion on machine 10.10.103.223
 ...
-[sudo] password to copy files and start minion: 
+[sudo] password to start minion: 
 ```
 
-If all things goes right, you will see the below message from console indicating the k8s is up.
+If everything works expectedly, you will see the following message from console indicating the k8s cluster is up.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: s/expectedly/correctly/

File: docs/getting-started-guides/ubuntu.md [hunk 9]
```diff
@@ -250,17 +252,20 @@ the latter one could start it again.
...
+you can use following command in `cluster/` directory to update the whole cluster
+or a specified node to a new version.
 
 ```console
 $ KUBERNETES_PROVIDER=ubuntu ./kube-push.sh [-m|-n <node id>] <version>
 ```
 
 It can be done for all components (by default), master(`-m`) or specified node(`-n`).
-If the version is not specified, the script will try to use local binaries.You should ensure all the binaries are well prepared in path `cluster/ubuntu/binaries`.
+Upgrading single node is currently experimental.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: Upgrading a single node ...

File: docs/getting-started-guides/ubuntu.md [hunk 10]
```diff
@@ -279,21 +284,29 @@ binaries/
...
 * upgrade node 10.10.103.223 to version 1.0.5 : `$ KUBERNETES_PROVIDER=ubuntu ./kube-push.sh -n 10.10.103.223 1.0.5`
 * upgrade master and all nodes to version 1.0.5: `$ KUBERNETES_PROVIDER=ubuntu ./kube-push.sh 1.0.5`
 
 The script will not delete any resources of your cluster, it just replaces the binaries.
-You can use `kubectl` command to check if the newly upgraded k8s is working correctly.
-For example, use `$ kubectl get nodes` to see if all of your nodes are ready.Or refer to [test-it-out](ubuntu.md#test-it-out)
+
+### Test it out
+
+You can use `kubectl` command to check if the newly upgraded kubernetes cluster is working correctly. See
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: You can use the `kubectl` command ...

File: docs/getting-started-guides/ubuntu.md [hunk 11]
```diff
@@ -279,21 +284,29 @@ binaries/
...
+also [test-it-out](ubuntu.md#test-it-out)
+
+To make sure the version of upgraded cluster is expected, you will find these commands helpful.
```
Comment (brendandburns) [inline docs/getting-started-guides/ubuntu.md]: ... of the upgraded cluster is what you expect ...

**Comment by brendandburns** [comment]
Thanks, minor typos, then LGTM.

**Comment by dalanlan** [comment]
@brendandburns  
updated.
Jenkins passed, yet Shippable is unhappy :)

**Comment by brendandburns** [comment]
Shipabble is a flake.  Merging.
