### PR TITLE
Filter nodePortAddresses to proxiers

### LINKED ISSUE #89923: DualStack: Kube-proxy/ipvs; nodePortAddresses with both ipv6 and ipv4 causes invalid ipvs entries
**What happened**:

In a dual-stack cluster when specifying both ipv6 and ipv4 addresses in the `nodePortAddresses` entries are inserted in ipvs for the ipv6 nodeports but with an invalid ipv4 address;

```
$ grep nodePortAddresses /etc/kubernetes/kube-proxy.config 
nodePortAddresses: ["::1/128","127.0.0.1/32"]
$ ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  12.0.0.1:443 rr
  -> 192.168.1.1:6443             Masq    1      0          0         
TCP  12.0.132.28:5001 rr
  -> 11.0.0.2:5001                Masq    1      0          0         
  -> 11.0.1.2:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.2:5001                Masq    1      0          0         
TCP  12.0.156.179:443 rr
  -> 11.0.0.3:4443                Masq    1      0          0         
TCP  127.0.0.1:30100 rr
  -> 11.0.0.2:5001                Masq    1      0          0         
  -> 11.0.1.2:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.2:5001                Masq    1      0          0         
TCP  127.0.0.1:30200 rr   # <---------- WRONG ENTRY!
  -> 17.0.0.0:5001                Masq    1      0          0         
TCP  [fd00:4000::27c7]:5001 rr
  -> [1100::2]:5001               Masq    1      0          0         
  -> [1100:0:0:1::2]:5001         Masq    1      0          0         
  -> [1100:0:0:2::2]:5001         Masq    1      0          0         
  -> [1100:0:0:3::2]:5001         Masq    1      0          0         
TCP  [::1]:30200 rr
  -> [1100::2]:5001               Masq    1      0          0         
  -> [1100:0:0:1::2]:5001         Masq    1      0          0         
  -> [1100:0:0:2::2]:5001         Masq    1      0          0         
  -> [1100:0:0:3::2]:5001         Masq    1      0          0         
```

The example shows the ipv4 loopback address but any ipv4 address in `nodePortAddresses` will cause a faulty entry.

**What you expected to happen**:

No ipv4 entry shall be inserted for the ipv6 nodeport.

**How to reproduce it (as minimally and precisely as possible)**:

* Configure `nodePortAddresses` with both ipv4 and ipv6 addresses
* Bring up a dual-stack cluster with proxy-mode `ipvs`
* Create a service with ipFamily:IPv6
* Do `ipvsadm -Ln`

**Anything else we need to know?**:

Proxy-mode=iptables seems to work.

With `nodePortAddresses: nil` no ipv4 entries are inserted for ipv6 nodeports.

In https://kubernetes.io/docs/concepts/services-networking/service/#nodeport it is recommended to use `127.0.0.0/8` but doing so makes kube-proxy enter rules for address `127.0.0.0` (in addition to "127.0.0.1"). While these entries cause no harm they can't be used and should not be there. These entries are created for both proxy-mode "iptables" and "ipvs". This should not be handled in this issue but in another (new) issue if needed. Example;

```
$ ipvsadm -Ln
TCP  127.0.0.0:30100 rr
  -> 11.0.0.2:5001                Masq    1      0          0         
  -> 11.0.1.3:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.2:5001                Masq    1      0          0         
TCP  127.0.0.0:30200 rr
  -> 17.0.0.0:5001                Masq    1      0          0         
(narrowed)
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.1.382+38f0a8bc74bed9", GitCommit:"38f0a8bc74bed92bef87e20a79c36c5feea78b3d", GitTreeState:"clean", BuildDate:"2020-04-07T08:36:57Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-alpha.1.382+38f0a8bc74bed9", GitCommit:"38f0a8bc74bed92bef87e20a79c36c5feea78b3d", GitTreeState:"clean", BuildDate:"2020-04-07T08:36:33Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Kvm's on Ubuntu
- OS (e.g: `cat /etc/os-release`): xcluster
- Kernel (e.g. `uname -a`):
```
Linux vm-002 5.6.0 #6 SMP Sun Apr 5 08:35:14 CEST 2020 x86_64 GNU/Linux
```
- Install tools: "from scratch"
- Network plugin and version (if this is a network-related bug): calico/cni:v3.12.0
- Others:

/sig network

### PR DESCRIPTION
**Pull request by uablrek**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

To avoid faulty entries in ipvs when both ipv4 and ipv6 addresses are used in "nodePortAddresses".

May also cause some yet unseen faults.

**Which issue(s) this PR fixes**:

Fixes #89923 

**Special notes for your reviewer**:

I did not see any faults for proxy-mode=iptables, but the same filtering might be appropriate also for proxy-mode=iptables.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by uablrek** [comment]
With;
```
nodePortAddresses: ["::1/128","127.0.0.1/32"]
```
Ipvs config;
```
$ ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  12.0.0.1:443 rr
  -> 192.168.1.1:6443             Masq    1      0          0         
TCP  12.0.19.107:443 rr
  -> 11.0.3.5:4443                Masq    1      0          0         
TCP  12.0.208.66:5001 rr
  -> 11.0.0.2:5001                Masq    1      0          0         
  -> 11.0.1.2:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.4:5001                Masq    1      0          0         
TCP  127.0.0.1:30100 rr
  -> 11.0.0.2:5001                Masq    1      0          0         
  -> 11.0.1.2:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.4:5001                Masq    1      0          0         
TCP  [fd00:4000::7710]:5001 rr
  -> [1100::2]:5001               Masq    1      0          0         
  -> [1100:0:0:1::2]:5001         Masq    1      0          0         
  -> [1100:0:0:2::2]:5001         Masq    1      0          0         
  -> [1100:0:0:3::4]:5001         Masq    1      0          0         
TCP  [::1]:30200 rr
  -> [1100::2]:5001               Masq    1      0          0         
  -> [1100:0:0:1::2]:5001         Masq    1      0          0         
  -> [1100:0:0:2::2]:5001         Masq    1      0          0         
  -> [1100:0:0:3::4]:5001         Masq    1      0          0         
```

**Comment by aojea** [comment]
I think you should add it to the single stack one too

https://github.com/kubernetes/kubernetes/pull/89998/files#diff-97649d13432b01b4e7669d728a2e2e82R483

```go
nodePortAddresses:     filterCIDRs(isIPv6, nodePortAddresses),
```

**Comment by uablrek** [comment]
@aojea You mean in case of user mistakes?

**Comment by uablrek** [comment]
The corresponding in the iptables proxier; https://github.com/kubernetes/kubernetes/blob/7b20442513a51882ebfd4a40a9600e8828851c13/pkg/proxy/iptables/proxier.go#L351-L363

**Comment by uablrek** [comment]
If the "filterCIDRs()" shall be used in the iptables proxier it should be moved to some "util" packade IMO to avoid duplicated code (and duplicated tests).

If so, where shall it go?

**Comment by aojea** [comment]
> @aojea You mean in case of user mistakes?

🤔 well,I think you are right, if you define IPv6 addresses in `--nodeport-addresses` in an IPv4 cluster is clearly an user mistake.

> If the "filterCIDRs()" shall be used in the iptables proxier it should be moved to some "util" packade IMO to avoid duplicated code (and duplicated tests).
> 
> If so, where shall it go?

my apologies, I was assuming you were already using this one 
https://github.com/kubernetes/kubernetes/blob/4d0e86f0b8d1eae00a202009858c8739e4c9402e/pkg/proxy/util/utils.go#L235-L243

**Comment by uablrek** [comment]
@aojea Thanks for the pointer :smiley:  The "filterCIDRs()" is just below the updated code and is already used in the call.

I will remove the "filterCIDRs()" to clean-up the code and also move to the place you pointed out. Then it can't go wrong since "NewProxy()" is called for ipv4/ipv6 in dual-stack. I think it will be cleaner.

Also I will add the update in the iptables proxier to avoid any yet-unseen problems.

**Comment by uablrek** [comment]
Hmm, IMHO "FilterIncorrectCIDRVersion()" is not intuitive. Not the name and not how it works. You must read the code to use it. I will use it in the iptables proxier, but keep "filterCIDRs()" in the ipvs proxier and let reviewers decide.

**Comment by uablrek** [comment]
The nodePortAddresses are filtered in `NewProxy()` as proposed by @aojea in https://github.com/kubernetes/kubernetes/pull/89998#issuecomment-611430756.

Not only will tis catch user mistakes which are probably common in transition to dual-stack and makes the code a little bit cleaner, it also allows a common setting for ipv4-only, ipv6-only and dual-stack in our use-case;

### Use case

When K8s is deployed in a DC (in VMs or bare-metal) with no K8s-aware load-balancers, loadbalancing to nodePorts can not be used. The external addresses must be configured in DC-GWs in some way, likely announced with BGP. `kube-proxy` will then load-balance incoming traffic.

This works fine but since NodePorts are implicit for services with `type: LoadBalancer` (and can't be turned-off) a number of ports above 30000 are opened but not used.

These ports show up on mandatory security scans, and a request to either describe their purpose or to close them is raised.

We can't close them but by setting;
```
nodePortAddresses: ["::1/128","127.0.0.1/32"]
```
we do not expose them externally. They will not show up on port scans any more.

**Comment by uablrek** [comment]
As the robot suggested;
/assign @bowei

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Comment by uablrek** [comment]
BTW localhost:<nodePort> do not work for ipvs; https://github.com/kubernetes/kubernetes/issues/67730

**Comment by uablrek** [comment]
@bowei ping. Can you please take a look at this? It is just a 2-line PR.

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -290,6 +290,7 @@ func NewProxier(ipt utiliptables.Interface,
 	serviceHealthServer := healthcheck.NewServiceHealthServer(hostname, recorder)
 
 	isIPv6 := ipt.IsIPv6()
+	nodePortAddresses, _ = utilproxy.FilterIncorrectCIDRVersion(nodePortAddresses, isIPv6)
```
Comment (liggitt) [inline pkg/proxy/iptables/proxier.go:293]: are there tests that exercise this scenario?

Comment (uablrek) [reply pkg/proxy/iptables/proxier.go:293]: Regression tests with ipv4 address, yes. Ipv6 addresses, no (as usual), mixed addresses, no.
I assume the library functions "FilterIncorrectCIDRVersion" has it's own tests.

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:293]: The FilterIncorrectCIDRVersion does have tests https://github.com/kubernetes/kubernetes/blob/4d0e86f0b8d1eae00a202009858c8739e4c9402e/pkg/proxy/util/utils_test.go#L541

It's being used to discriminate IP address of the load balancer services

https://github.com/kubernetes/kubernetes/blob/0a6c826d3e92dae8f20d6199d0ac7deeca9eed71/pkg/proxy/service.go#L157-L165

For the NewProxier testing there is  a TODO

https://github.com/kubernetes/kubernetes/blob/0a6c826d3e92dae8f20d6199d0ac7deeca9eed71/pkg/proxy/iptables/proxier_test.go#L350-L351

Comment (liggitt) [reply pkg/proxy/iptables/proxier.go:293]: filtering here and silently discarding invalid NodePortAddresses doesn't seem great... I would have expected to do the filtering in the NewDualStackProxier methods:

```
func NewDualStackProxier(
...
ipv4NodePortAddresses, ipv6NodePortAddresses := utilproxy.FilterIncorrectCIDRVersion(nodePortAddresses, false)
ipv4Proxier, err := NewProxier(..., ipv4NodePortAddresses, ...)
ipv6Proxier, err := NewProxier(..., ipv6NodePortAddresses, ...)
```

In NewProxier, if nodePortAddresses of the wrong family are passed in, that seems like something we should error on (that would catch the case where a single-stack proxier was created and --nodeport-addresses was misconfigured with the wrong family)

Comment (uablrek) [reply pkg/proxy/iptables/proxier.go:293]: I did that first and moved to `NewProxier` :smiley: I can move the check back. It it enough to log a fault _and_ filter the addresses to avoid the faulty entries reported in https://github.com/kubernetes/kubernetes/issues/89923? I does not seem right to crash `kube-proxy` in case of a misconfigured NodePortAddresses.

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:293]: > I did that first and moved to `NewProxier`  I can move the check back.

it was my fault to be honest https://github.com/kubernetes/kubernetes/pull/89998#issuecomment-611430756 :smile:

**Comment by uablrek** [comment]
Corrections after review are pushed.

True to;
> It does not seem right to crash kube-proxy in case of a misconfigured NodePortAddresses.

a warning is logged if NodePortAddresses of the wrong family is configured in a single-stack cluster;
```
W0515 07:37:53.620500     254 proxier.go:439] NodePortAddresses of wrong family; [::1/128]
```

In dual-stack the addresses are filtered in `NewDualStackProxier()` so the proxier instanses only gets addresses with it's family (no warnings).

**Comment by uablrek** [comment]
Problem does not seem to be related to the PR
/retest

**Comment by uablrek** [comment]
@aojea Can you please help since you have good knowledge of flaky tests.

The `pull-kubernetes-e2e-gci-gce-ipvs` keeps on failing and I can't see any way this PR can cause the failures. Unless there really are NodePortAddresses of the wrong family this PR should not make any difference.

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gci-gce-ipvs

let me check again, but seems the common test failures are
```
[sig-storage] Flexvolumes should be mountable when non-attachable expand_more5m17s | 
[sig-storage] Flexvolumes should be mountable when non-attachable expand_more | 5m17s
```

**Comment by aojea** [comment]
seems those tests were failing for a long time, 
https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gci-gce-ipvs

in the meantime let me fix the reporting in testgrid so we can notice it sooner next time (cc: @andrewsykim )

**Comment by uablrek** [comment]
@aojea Thanks a lot!

**Comment by aojea** [comment]
I'm also removing the storage tests for the ipvs jobs, I don't have time for debugging more current failures and we weren't tracking those jobs.
It is better having only tests we should care and expand later if necessary https://github.com/kubernetes/test-infra/pull/17623

**Comment by andrewsykim** [comment]
FYI https://github.com/kubernetes/kubernetes/issues/91253 

@aojea I can investigate soon if you haven't started

**Comment by aojea** [comment]
> FYI #91253
> 
> @aojea I can investigate soon if you haven't started

I just did an initial check, but nothing relevant. Please go ahead,  I'll be watching the issue to check if I can help, but I'm a bit tied this week

**Comment by uablrek** [comment]
Updated after review please see; https://github.com/kubernetes/kubernetes/pull/89998#issuecomment-629112097

@liggitt Please have a new look at it.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
