### PR TITLE
Copy annotations back from RS to Deployment on rollback

### LINKED ISSUE #23087: Incorrect annotation copied from deployment to RS after rolling back
Scenario:
1) Create a deployment d and record it. Change cause: d = "create", rs1 (v1) = "create" (copied from d). 
```console
$ kubectl create -f docs/user-guide/nginx-deployment.yaml --record
deployment "nginx-deployment" created
$ kubectl rollout history deployment
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
1		    kubectl create -f docs/user-guide/nginx-deployment.yaml --record
```
2) Update d with apply. Change cause: d = "apply", rs2 (v2) = "apply" (copied from d)
```console
$ kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
deployment "nginx-deployment" configured
$ kubectl rollout history deployment 
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
1		    kubectl create -f docs/user-guide/nginx-deployment.yaml --record
2		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
```
3) Rollback d. Change cause: d = "apply" (unchanged since we don't record command in `kubectl rollout undo`), rs1 (v3) = "apply" (copied from d). However, **it should be either "create" or "rollout undo"** (depending on how we want to implement it). This confuses users. 
```console
$ kubectl rollout undo deployment 
deployment "nginx-deployment" rolled back
$ kubectl rollout history deployment 
deployments "nginx-deployment":
REVISION	CHANGE-CAUSE
2		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
3		    kubectl apply -f docs/user-guide/new-nginx-deployment.yaml
```

@bgrant0607 @kargakis @kubernetes/sig-config @kubernetes/kubectl

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #23087 

@bgrant0607 @kargakis @kubernetes/sig-config

### CODE REVIEW

File: pkg/controller/deployment/deployment_controller.go [hunk 1]
```diff
@@ -922,6 +927,21 @@ func copyDeploymentAnnotationsToReplicaSet(deployment *extensions.Deployment, rs
 	return rsAnnotationsChanged
 }
 
+// copyReplicaSetAnnotationsToDeployment copies RS's annotations to deployment's annotations.
+// This action should be done if and only if the deployment is rolling back to this rs.
+// Note that apply and revision annotations are not copied.
```
Comment (kargakis) [inline pkg/controller/deployment/deployment_controller.go]: So the new revision is N+1?

**Comment by bgrant0607** [comment]
cc @pwittrock

File: pkg/controller/deployment/deployment_controller.go (hunk 1 above)
Comment (janetkuo) [inline pkg/controller/deployment/deployment_controller.go]: Revision is only updated (to max old revision + 1, if it's larger) in getNewReplicaSet and then copied to deployment (revision in deployment is for reference only and is always copied from new RS to deployment). We don't touch it here.

**Comment by bgrant0607** [comment]
@pwittrock PTAL. Good time to become familiar with Deployment. :-)

File: pkg/controller/deployment/deployment_controller.go [hunk 2]
```diff
@@ -1237,6 +1257,18 @@ func (dc *DeploymentController) rollbackToTemplate(deployment *extensions.Deploy
 	if !reflect.DeepEqual(deploymentutil.GetNewReplicaSetTemplate(deployment), rs.Spec.Template) {
 		glog.Infof("Rolling back deployment %s to template spec %+v", deployment.Name, rs.Spec.Template.Spec)
 		deploymentutil.SetFromReplicaSetTemplate(deployment, rs.Spec.Template)
+		// copy RS (the old RS we'll rolling back to) annotations back to the deployment;
+		// otherwise, the deployment's current annotations (should be the same as current new RS) will be copied to the RS after the rollback.
+		//
+		// For example,
+		// A Deployment has old RS1 with annotation {change-cause:create}, and new RS2 {change-cause:edit}.
```
Comment (pwittrock) [inline pkg/controller/deployment/deployment_controller.go]: How are annotations that do not directly override each other handled in this situation? e.g.
{rs1-annotation:foo}
{rs2-annotation:bar}

When we rollback to rs1 from rs2, this will add back {rs1-annotation:foo}, but does {rs2-annotation:bar} need to be explicitly removed (or is that handled by other code?)

Comment (janetkuo) [inline pkg/controller/deployment/deployment_controller.go]: Ah, yes we should remove those annotations.

Comment (janetkuo) [inline pkg/controller/deployment/deployment_controller.go]: Fixed

**Comment by janetkuo** [comment]
PTAL

**Comment by pwittrock** [comment]
Looks good.  Feel free to squash the comments commit.

**Comment by janetkuo** [comment]
Squashed and applying tag.
