### PR TITLE
fix: use pv annotation to trigger filesystem resize when necessary

### LINKED ISSUE #88683: Filesystem resize skipped if original PVC is deleted when FilesystemResizePending but PV is retained
**What happened**:
- Create a PVC using a StorageClass with Retain policy and allowVolumeExpansion. 
- Create a Pod to use the PVC. Check the filesystem size.
- Start volume expansion by modifying the PVC size. After PV and the associated volume is expanded to the new size, PVC size is unchanged and it is in FilesystemResizePending condition.
- Delete the Pod.
- Delete the PVC.  PV and the associated volume remains due to Retain policy.
- Remove "uid" field in ClaimRef of PV.
- Create a new PVC to statically bind with the existing PV.
- Create a Pod to use the new PVC.  PVC requested size is set to the new size.
- However, filesystem size remain unchanged.

**What you expected to happen**:
Filesystem should be resized.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a SC with Retain policy and allowVolumeExpansion set to true.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: example-vanilla-block-sc
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
```
2. Create a PVC using the SC.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-vanilla-block-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: example-vanilla-block-sc
```
```
# kubectl get pvc
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
example-vanilla-block-pvc2   Bound    pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2   1Gi        RWO            example-vanilla-block-sc   28s
# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                STORAGECLASS               REASON   AGE
pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2   1Gi        RWO            Retain           Bound    default/example-vanilla-block-pvc2   example-vanilla-block-sc            24s
```
3. Create a Pod to use the PVC.
4. Login to check the filesystem size.
```
kubectl exec -it example-vanilla-block-pod2 /bin/sh
```
```
/dev/sdb             ext4          999320      2568    927940   0% /mnt/volume1
```
5. Delete the Pod.
6. Increase the PVC size from 1 to 3G.
7. PV is changed to the new expanded size but PVC remains the same size.
PVC has FileSystemResizePending condition.
```
root@k8-master-430:/etc/kubernetes# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                STORAGECLASS               REASON   AGE
pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2   3Gi        RWO            Retain           Bound    default/example-vanilla-block-pvc2   example-vanilla-block-sc            18m
root@k8-master-430:/etc/kubernetes# kubectl get pvc
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS               AGE
example-vanilla-block-pvc2   Bound    pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2   1Gi        RWO            example-vanilla-block-sc   18m
```
```
# kubectl describe pvc example-vanilla-block-pvc2
Name:          example-vanilla-block-pvc2
Namespace:     default
StorageClass:  example-vanilla-block-sc
Status:        Bound
Volume:        pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"example-vanilla-block-pvc2","namespace":"default"},...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Conditions:
  Type                      Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----                      ------  -----------------                 ------------------                ------  -------
  FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Fri, 28 Feb 2020 17:52:58 -0800           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
```
8. Delete PVC.  PV remains.
9. Save PV config to a yaml file.
```
# kubectl get pv pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2 -o yaml > static-pv2.yaml
```
10. Modify PV to remove "uid" field of ClaimRef in PV.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  creationTimestamp: "2020-02-29T01:34:49Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/csi-vsphere-vmware-com
  name: pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2
  resourceVersion: "46099"
  selfLink: /api/v1/persistentvolumes/pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2
  uid: acda8aa8-5a93-11ea-bc63-0050568bf4d2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 3Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: example-vanilla-block-pvc2
    namespace: default
    resourceVersion: "43306"
    uid:
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1582932805902-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: 58e18582-965d-437e-accf-d9a4a084d43a
  persistentVolumeReclaimPolicy: Retain
  storageClassName: example-vanilla-block-sc
  volumeMode: Filesystem
status:
  phase: Released
```
```
# kubectl apply -f static-pv2.yaml
```
11. Create a PVC to statically bind with PV.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-vanilla-block-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeName: pvc-a94bcc93-5a93-11ea-bc63-0050568bf4d2
```
```
kubectl apply -f static-pvc2.yaml
```
12. Create a Pod to use PVC.
13. Check the filesystem.  It is unchanged.
```
/dev/sdb             ext4          999320      2568    927940   0% /mnt/volume1
```

**Anything else we need to know?**:
Note: If the volume does not have a pre-existing filesystem before resize (without steps 3-5 above), filesystem will be created with the correct new size (at step 13 above).

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.2 (Note: this is the setup I have currently, but this would happen in later versions such as 1.17 or later as well)
- Cloud provider or hardware configuration: vSphere CSI Driver
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
Linux k8-master-430 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sunpa93**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix: when newly binding pvc to a pv, adjust pvc.status.capacity to pv's annotation that denotes the pre-resize capacity of the original pvc that pv was bound to if it has one

test: confirm that pvc's status capacity is adjusted if pv has a pre-resize capacity annotation

#### Which issue(s) this PR fixes:

Fixes #88683

#### Special notes for your reviewer:

This PR is a sister PR of https://github.com/kubernetes-csi/external-resizer/pull/140

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
[`pull-kubernetes-unit`: new job, not yet blocking, fixed the config, nothing to see here!]

File: pkg/volume/util/resize_util.go [hunk 1]
```diff
@@ -57,27 +57,34 @@ func UpdatePVSize(
 	newSize resource.Quantity,
 	kubeClient clientset.Interface) error {
 	pvClone := pv.DeepCopy()
+	pvClone.Spec.Capacity[v1.ResourceStorage] = newSize
```
Comment (gnufied) [inline pkg/volume/util/resize_util.go:60]: Is this just re factoring change?

File: pkg/controller/volume/persistentvolume/BUILD [hunk 2]
```diff
@@ -37,6 +37,7 @@ go_library(
         "//staging/src/k8s.io/api/storage/v1:go_default_library",
         "//staging/src/k8s.io/apimachinery/pkg/api/errors:go_default_library",
         "//staging/src/k8s.io/apimachinery/pkg/api/meta:go_default_library",
+        "//staging/src/k8s.io/apimachinery/pkg/api/resource:go_default_library",
         "//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
         "//staging/src/k8s.io/apimachinery/pkg/labels:go_default_library",
```
Comment (gnufied) [inline pkg/controller/volume/persistentvolume/BUILD:42]: We are missing a change expand_controller which is https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/expand/expand_controller.go 

We need same change you did https://github.com/kubernetes-csi/external-resizer/pull/140/files in intree controller.

**Comment by gnufied** [comment]
I also want @msau42 and @jsafrane to take a look at the pv_controller change.

/assign @msau42 @jsafrane

File: pkg/controller/volume/persistentvolume/pv_controller.go [hunk 3]
```diff
@@ -783,7 +784,20 @@ func (ctrl *PersistentVolumeController) updateClaimStatus(claim *v1.PersistentVo
 				return nil, fmt.Errorf("PersistentVolume %q is without a storage capacity", volume.Name)
 			}
 			claimCap, ok := claim.Status.Capacity[v1.ResourceStorage]
-			if !ok || volumeCap.Cmp(claimCap) != 0 {
+			// If PV has a resize annotation, set the claim's request capacity
+			if metav1.HasAnnotation(volume.ObjectMeta, util.AnnPreResizeCapacity) {
+				klog.V(2).Infof("volume %q requires filesystem resize: setting pvc %s status capacity to %s", volume.Name, claimToClaimKey(claim), volume.ObjectMeta.Annotations[util.AnnPreResizeCapacity])
+				preQty, err := resource.ParseQuantity(volume.ObjectMeta.Annotations[util.AnnPreResizeCapacity])
```
Comment (gnufied) [inline pkg/controller/volume/persistentvolume/pv_controller.go:790]: I wonder if we can't parse here, we should simply revert to `volume.Spec.Capacity` rather than failing here.

**Comment by gnufied** [comment]
We can do this in a follow up but I think we should be able to test this with e2e and mock driver.

1. Define mock driver to have offline only expansion capability.
2. Create a PVC and then expand it.
3. change reclaim policy on PV to retain and delete the PVC
4. bind the PVC again and create a pod and ensure that PVC reports accurate size after expansion.

File: pkg/controller/volume/persistentvolume/pv_controller.go (hunk 3 above)
Comment (sunpa93) [reply pkg/controller/volume/persistentvolume/pv_controller.go:790]: Sounds good.

**Review by msau42 — COMMENTED** [review]
Sorry for the delayed review. I started reviewing the external-resizer one and came to this for some background.

General question. This annotation is alpha. What are our future plans for this? In general we have tried to move away from using alpha annotations because it's difficult to enforce alpha-level guarantees around them.

File: pkg/volume/util/resize_util.go [hunk 4]
```diff
@@ -39,6 +39,12 @@ var (
 		v1.PersistentVolumeClaimFileSystemResizePending: true,
 		v1.PersistentVolumeClaimResizing:                true,
 	}
+
+	// AnnPreResizeCapacity annotation is added to a PV when expanding volume.
+	// Its value is status capacity of the PVC prior to the volume expansion
+	// Its value will be set by the external-resizer when it deems that filesystem resize is required after resizing volume.
+	// Its value will be used by pv_controller to determine pvc's status capacity when binding pvc and pv.
```
[the remark this answers is not in the document]
Comment (sunpa93) [reply pkg/volume/util/resize_util.go:46]: Will do :)

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 5]
```diff
@@ -1551,6 +1551,14 @@ func (og *operationGenerator) GenerateExpandVolumeFunc(
 				klog.Warning(detailedErr)
 				return volumetypes.NewOperationContext(nil, nil, migrated)
 			}
+			oldCapacity := pvc.Status.Capacity[v1.ResourceStorage]
+			err = util.AddAnnPreResizeCapacity(pv, oldCapacity, og.kubeClient)
```
[the remark this answers is not in the document]
Comment (sunpa93) [reply pkg/volume/util/operationexecutor/operation_generator.go:1555]: I can't think of scenarios where there can be a race from top of my head. Could you point to when race could happen?
