### PR TITLE
Extends deviceplugin to gracefully handle full device plugin lifecycle.

### LINKED ISSUE #53395: Better handling of device plugin resource deletion
/kind feature

Spun off from https://github.com/kubernetes/kubernetes/issues/53342, there was a regression introduced by device plugin change in 1.8 that we might remove opaque integer resource or non-device extended resources. We fix this problem in 1.8 by never removing any extended resources from kubelet node status and requires cluster admins to manually remove extended resources exposed via device plugins when they remove plugins. This issue is to track better handling of device plugin resource removal after 1.8 so that we can better manage device plugin resource life cycle.

As @ConnorDoyle summarized in https://github.com/kubernetes/kubernetes/issues/53342, there are a few options to solve this:

Option 1: With the assumption that ContainerManager owns the full control of the resources listed in its GetCapacity(), track resource deletion in ContainerManager and mark it in the returning data structure of GetCapacity() by either explicitly introducing a new state field for each resource type or implicitly from special quantity value of a resource (e.g., -1).

Option 2: Introduce some naming convention for device plugin resources. This will simplify device plugin resource lifecycle management, but will probably require broader discussions.

Other than distinguishing device plugin resources from other extended resources, we also need to avoid temporary capacity drop for device plugin resources after kubelet restarts. Otherwise, Pods restarted at that time gap window would fail and it is a regression from using device plugin to manage a resource compared to the native resource management by Kubelet (e.g., gpu resource currently managed by GpuManager). Possible options to solve this:
Option 1: Tracks a grace period after Kubelet restart and avoid updating device plugin resource capacity during grace period.
Option 2: Wait for some time period during ContainerManager Start() for device plugins to re-register.

### PR DESCRIPTION
**Pull request by jiayingz**
**What this PR does / why we need it**:
- Instead of using cm.capacity field to communicate device plugin resource capacity,
this PR changes to use an explicit cm.GetDevicePluginResourceCapacity() function
that returns device plugin resource capacity as well as any inactive device plugin resource.
Kubelet syncNodeStatus call this function during its periodic run to update node status
capacity and allocatable. After this call, device plugin can remove the inactive device
plugin resource from its allDevices field as the update is already pushed to API server.
- Extends device plugin checkpoint data to record registered resources
so that we can finish resource removing even upon kubelet restarts.
- Passes sourcesReady from kubelet to device plugin to avoid removing
inactive pods during grace period of kubelet restart.
- Extends gpu_device_plugin e2e_node test to verify that scheduled pods
can continue to run even after device plugin deletion and kubelet
restarts.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Together with https://github.com/kubernetes/kubernetes/pull/54488, fixes https://github.com/kubernetes/kubernetes/issues/53395

**Special notes for your reviewer**:

**Release note**:

```release-note
Extends deviceplugin to gracefully handle full device plugin lifecycle.
```

### CODE REVIEW

**Comment by jiayingz** [comment]
cc @bsalamat

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go [hunk 1]
```diff
@@ -66,6 +69,9 @@ type HandlerImpl struct {
 	// so the amount of pluginResources requested by existing pods
 	// could be counted when updating allocated devices
 	activePods ActivePodsFunc
+	// sourcesReadyProvider provides the readyness of kubelet configuration sources.
+	// We use it to determine when we can purse inactive pods from checkpointed state.
```
Comment (tengqm) [inline pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: sourcesReadyProvider -> sourcesReady
readyness -> readiness
purse -> purge

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go [hunk 2]
```diff
@@ -90,7 +104,8 @@ func NewHandlerImpl(updateCapacityFunc func(v1.ResourceList)) (*HandlerImpl, err
 	deviceManagerMonitorCallback := func(resourceName string, added, updated, deleted []pluginapi.Device) {
```
Comment (tengqm) [inline pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: extract this function into something like `defaultCallback`?

File: pkg/kubelet/cm/container_manager_linux.go [hunk 3]
```diff
@@ -266,7 +267,7 @@ func NewContainerManager(mountUtil mount.Interface, cadvisorInterface cadvisor.I
 		cm.Lock()
 		defer cm.Unlock()
 		for k, v := range updates {
-			if v.Value() <= 0 {
+			if v.Value() < 0 {
```
Comment (RenaudWasTaken) [inline pkg/kubelet/cm/container_manager_linux.go]: When is the value less than 0 ?

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go (hunk 1 above)
Comment (jiayingz) [reply pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: done.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 3 above)
Comment (jiayingz) [reply pkg/kubelet/cm/container_manager_linux.go]: The comment above handler.garbageCollectionFunc definition explains how this happens. I also added some comment here to explain the scenario.

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go (hunk 2 above)
Comment (jiayingz) [reply pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: Do you mean define this as func (h *HandlerImpl) defaultCallback(...)?

**Review by jiayingz — COMMENTED** [review]
Thanks a lot for the reviews! PTAL.

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go (hunk 2 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: would it be better to rename the function to indicate that its common callback for all resources, something like genericDeviceSyncCallback?
Not sure if @tengqm meant the same or similar.

**Review by vikaschoudhary16 — COMMENTED** [review]
Though have not completed review yet. Please find couple of quick comments. Thanks!!

**Comment by vishh** [comment]
Capturing offline discussion:
1. I'd prefer device resource becoming inactive being signaled via an explicit channel than overloading resource quantity (negative values)
2. The callbacks from device plugins can be restricted to the device plugin manager and the rest of kubelet (klet->cm->deviceplugin manager) can be synchronous.
3. In the future, I'd prefer healthy and unhealthy devices be exposed as as-is via Container Manager and let kubelet decide on how to expose it.

Given the time crunch, I'm ok with deferring on `1` and `2` to a future PR, as long as there is an owner for them.

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go [hunk 4]
```diff
@@ -196,7 +271,9 @@ func (h *HandlerImpl) allocateContainerResources(pod *v1.Pod, container *v1.Cont
 		resource := string(k)
 		needed := int(v.Value())
 		glog.V(3).Infof("needs %d %s", needed, resource)
-		if _, registeredResource := h.allDevices[resource]; !registeredResource {
+		available, registeredResource := h.allDevices[resource]
+		_, allocatedResource := h.allocatedDevices[resource]
+		if (!registeredResource || available == nil) && !allocatedResource {
```
Comment (tengqm) [inline pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: Some explanation about the above line would be helpful.

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go [hunk 5]
```diff
@@ -321,18 +404,34 @@ func (h *HandlerImpl) updateAllocatedDevices(activePods []*v1.Pod) {
...
-	glog.V(5).Infof("pods to be removed: %v", podsToBeRemoved.List())
+	glog.V(3).Infof("pods to be removed: %v", podsToBeRemoved.List())
 	h.podDevices.delete(podsToBeRemoved.List())
 	// Regenerated allocatedDevices after we update pod allocation information.
 	h.allocatedDevices = h.podDevices.devices()
 }
 
+// checkpointData struct is used to store pod to device allocation information
+// and registered device information in a checkpoint file.
+// TODO: add version control when we need to change checkpoint format.
```
Comment (tengqm) [inline pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: Add a version field today please, or it will lead to a lot of troubles in future.

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go [hunk 6]
```diff
@@ -117,21 +134,75 @@ func NewHandlerImpl(updateCapacityFunc func(v1.ResourceList)) (*HandlerImpl, err
...
+	// mark them with nil device list, and sets their capacities to zero.
+	// Note the order of these two tasks are important because we need an extra step to
+	// mark a resource with capacity 0 so that kubelet syncNodeStatus go routine can pick up
+	// this signal and remove the resource capacity from node status. Only after this, in the
+	// next run of garbageCollectionFunc, we can remove the resource from the allDevices list
+	// and checkpoint data, as well as updates their capacity with negative value which will
+	// signal ContainerManager to remove them from cm.capcity.
+	// An implication of this requirement is that garbageCollectionFunc is expected to be run
+	// with longer interval than kubelet syncNodeStatus. Currently we configure it to run every 10 minutes.
+	handler.garbageCollectionFunc = func() {
```
[the remark this answers is not in the document]
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: looks cleaner to me!

File: pkg/kubelet/cm/deviceplugin/device_plugin_handler.go (hunk 2 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/device_plugin_handler.go]: This functions seems to be getting invoked only from unit tests. I am unable to understand what purpose this function, `deviceManagerMonitorCallback` has.
Looks to me we are adding a function which is not being used anywhere and then writing unit test to test its logic.

Please suggest if i misunderstood something.

**Review by vikaschoudhary16 — CHANGES_REQUESTED** [review]

**Comment by jiayingz** [comment]
Thinking about this after the discussion with @vishh yesterday, I feel it is probably better to switch from the asynchronous callback model to the synchronous polling model sooner rather than later. Otherwise we may keep accumulating technical debt. We still have some time before 1.9 freeze. Let me change this PR towards that direction. I think this will help simplify code structure a lot.

@vikaschoudhary16 and @tengqm thanks a lot for your comments! I think answers to some of your comments will be clear after the refactoring. I will let you know after I am done with the change.

**Comment by jiayingz** [comment]
FYI, this PR is ready for another round of review.

**Review by ScorpioCPH — COMMENTED** [review]
Leave some comments, and i have test this PR via e2e stub device plugin.

File: pkg/kubelet/kubelet_node_status.go [hunk 7]
```diff
@@ -595,15 +595,17 @@ func (kl *Kubelet) setNodeStatusMachineInfo(node *v1.Node) {
 			}
 		}
 
-		currentCapacity := kl.containerManager.GetCapacity()
-		if currentCapacity != nil {
-			for k, v := range currentCapacity {
-				if v1helper.IsExtendedResourceName(k) {
-					glog.V(2).Infof("Update capacity for %s to %d", k, v.Value())
-					node.Status.Capacity[k] = v
-				}
```
Comment (tengqm) [inline pkg/kubelet/kubelet_node_status.go]: Is this removing the updates that could have happened independently to "extended resources" created via node patch? Not all extended resources are device (plugin) resources, right?

**Review by tengqm — COMMENTED** [review]
Just one clarification needed from my viewpoint. I can point out many places where the code can be improved but I don't think we should block it for ever.

File: pkg/kubelet/kubelet_node_status.go (hunk 7 above)
Comment (jiayingz) [reply pkg/kubelet/kubelet_node_status.go]: This only affects extended resources we get through kl.containerManager and currently it only covers device plugin resources. Extended resources added through node patch should be unaffected.

Comment (tengqm) [reply pkg/kubelet/kubelet_node_status.go]: Thanks for the answer.

**Review by vishh — APPROVED** [review]
/lgtm
/approve
/hold

**Comment by mindprince** [comment]
I mentioned this offline, but I would love to see a document (or an update to the original design proposal) that describes the behavior:

- when everything is going fine.
- when kubelet restarts.
- when device plugin(s) restart.
- when device plugin(s) are unresponsive.
- when device plugin(s) go away.
- when multiple device plugins are present for the same resource.
- and so on

It would be great if we can have that document describe the current situation and what we think is the ideal behavior in these scenarios. I know there are comments about these situations through out the code base and in various issues and PRs but it's getting a little overwhelming to keep up.

**Comment by jiayingz** [comment]
Yes. Updating document to match the recent updates is on my TODO list. Hope to get it done after thanksgiving.
