### PR TITLE
reenable e2e_node services & debugging improvements

### LINKED ISSUE #95877: Investigate node-kubelet-conformance test failures
**Which jobs are failing**:

[node-kubelet-conformance suite](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-conformance&show-stale-tests=)

**Which test(s) are failing**:

The tests are failing in the `BeforeSuite`.

**Since when has it been failing**:

10/23/2020

**Testgrid link**:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-conformance

**Reason for failure**:

It started failing at commit `237dae5a5`, but it's unknown if it's related to that.

**Anything else we need to know**:

We discussed in the Kubernetes SIG-Node CI subgroup and will start taking a look at it.

### PR DESCRIPTION
**Pull request by MHBauer**
- re-enable e2e_node services
 - add log messages indicating location in process
 - move log messages to some more accurate locations

**What type of PR is this?**

/kind bug
/kind failing-test

**What this PR does / why we need it**:
I think the node-e2e services were accidentally disabled in https://github.com/kubernetes/kubernetes/pull/94723/files#r516304908

I would like @knight42 to comment on the movement of the code block into the if-statement.
/cc @knight42 

**Which issue(s) this PR fixes**:
As of latest version ~Noon EST 2020-10-03
Fixes #95877

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Other lookers at the existing issue...
/cc @knabben @mmerkes @alejandrox1

### CODE REVIEW

File: test/e2e_node/e2e_node_suite_test.go [hunk 1]
```diff
@@ -197,7 +197,6 @@ var _ = ginkgo.SynchronizedBeforeSuite(func() []byte {
 		// If the services are expected to keep running after test, they should not monitor the test process.
 		e2es = services.NewE2EServices(*stopServices)
 		gomega.Expect(e2es.Start()).To(gomega.Succeed(), "should be able to start node services.")
-		klog.Infof("Node services started.  Running tests...")
```
Comment (MHBauer) [inline test/e2e_node/e2e_node_suite_test.go:200]: deceptive position for this

File: test/e2e_node/services/services.go [hunk 2]
```diff
@@ -64,15 +64,19 @@ func NewE2EServices(monitorParent bool) *E2EServices {
...
 func (e *E2EServices) Start() error {
 	var err error
+	if e.services, err = e.startInternalServices(); err != nil {
+		return fmt.Errorf("failed to start internal services: %v", err)
+	}
+	klog.Infof("Node services started.")
 	if !framework.TestContext.NodeConformance {
-		if e.services, err = e.startInternalServices(); err != nil {
-			return fmt.Errorf("failed to start internal services: %v", err)
-		}
```
Comment (MHBauer) [inline test/e2e_node/services/services.go:70]: I'm not entirely sure if it matters if services are started before or after the kubelet.

File: test/e2e_node/services/services.go [hunk 3]
```diff
@@ -64,15 +64,19 @@ func NewE2EServices(monitorParent bool) *E2EServices {
 // standard kubelet launcher)
 func (e *E2EServices) Start() error {
 	var err error
+	if e.services, err = e.startInternalServices(); err != nil {
+		return fmt.Errorf("failed to start internal services: %v", err)
+	}
+	klog.Infof("Node services started.")
 	if !framework.TestContext.NodeConformance {
```
Comment (mmerkes) [inline test/e2e_node/services/services.go:71]: nit: Remove the `!` for readability?

```
if framework.TestContext.NodeConformance {
        klog.Info("nothing to do in node-e2e-services, running conformance suite")
} else {
        // Start kubelet
}

**Review by mmerkes — COMMENTED** [review]
Nice find and thanks for improving the messaging.

File: test/e2e_node/remote/node_conformance.go [hunk 4]
```diff
@@ -135,6 +135,7 @@ func (c *ConformanceRemote) SetupTestPackage(tardir, systemSpecName string) erro
 
 // loadConformanceImage loads node conformance image from tar file.
 func loadConformanceImage(host, workspace string) error {
+	klog.Info("loading conformance image from tarfile")
```
Comment (knabben) [inline test/e2e_node/remote/node_conformance.go:138]: can you upper case the first letter, just to keep the standard of these logs.

File: test/e2e_node/services/services.go [hunk 5]
```diff
@@ -64,15 +64,19 @@ func NewE2EServices(monitorParent bool) *E2EServices {
 // standard kubelet launcher)
 func (e *E2EServices) Start() error {
 	var err error
+	if e.services, err = e.startInternalServices(); err != nil {
```
Comment (knabben) [inline test/e2e_node/services/services.go:67]: At this point, the Kubelet is already started without a Bearer Token in the configuration for conformance, maybe the token must be generated on ```test/e2e_node/services/services.go``` and passed down the stack.

Comment (MHBauer) [reply test/e2e_node/services/services.go:67]: Yes, I think something like this is the case. I am taking a break from this for the moment, and have not started looking at the details. If someone else wants to keep looking for today, I'm happy to let them continue, otherwise I'll start again tomorrow.

File: test/e2e_node/remote/node_conformance.go (hunk 4 above)
Comment (MHBauer) [reply test/e2e_node/remote/node_conformance.go:138]: yup.

File: test/e2e_node/services/services.go (hunk 3 above)
Comment (MHBauer) [reply test/e2e_node/services/services.go:71]: I can, but I'd like another +1 before I go do so.

**Comment by knight42** [comment]
@MHBauer After taking a second look, I think the movement of the statement `e.startInternalServices()` should be a mistake, my original purpose was to start apiserver before kubelet. Sorry for breaking these tests 😢

File: test/e2e_node/services/services.go (hunk 5 above)
Comment (knabben) [reply test/e2e_node/services/services.go:67]: Running remote with the PR, This is the Kubeconfig:

```
@test-cos-beta-85-13310-1041-1 /tmp/node-e2e-20201103T122457 $ cat kubeconfig
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    token: loiXGCHWaBpe9m94
clusters:
- cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true
  name: local
contexts:
- context:
    cluster: local
    user: kubelet
  name: local-context
```

This is the run-services-mode rerun:
```
/usr/local/bin/e2e_node.test --run-services-mode --bearer-token=mjBCSf8Jd_N0FSTb ... 
```

Still breaking on both API server and Kubelet having a wrong token:

```
E1103 12:31:43.827172     103 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token 
```

Comment (knight42) [reply test/e2e_node/services/services.go:67]: hmm I guess this has something to do with how ginkgo run the tests https://github.com/kubernetes/kubernetes/pull/94723#issuecomment-700512458, I would take a deeper look, thanks for pointing it out.

**Comment by MHBauer** [comment]
For more context, launchKubelet is run https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/remote/node_conformance.go#L282 instead of L#73 in https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/services/services.go#L72 , which is excluded from running during the conformance tests by the if block.

Since the confusion seems to continue, I am inclined to flip the if so the blank/logged clause is first, to force thinking about it.

**Comment by knight42** [comment]
@MHBauer Thanks for your information!

@knabben Could you try adding the flag `fmt.Sprintf("--bearer-token=%s", framework.TestContext.BearerToken)` in https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/remote/node_conformance.go#L182-L183 like https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/services/services.go#L136
to see if the problem is solved?

**Comment by MHBauer** [comment]
I ended up with a blank substitution for the token. I think we're very close!

**Comment by MHBauer** [comment]
The main of running remote is https://github.com/kubernetes/kubernetes/blob/2ad5f014a12f6b2a34e8ddc71e3020e9298444a5/test/e2e_node/runner/remote/run_remote.go which is not a e2e framework enabled runner like e2e_node.test. Since that is what starts the kubelet, we need to move the token generation outside, or otherwise synch them up.

**Comment by knabben** [comment]
This looks like the point the conformance starts the suite via Docker, can we use this to send the token down (EXTRA_ENVS?), how does it will not leak in the logs?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/node_conformance.go#L296

**Comment by knabben** [comment]
> @MHBauer Thanks for your information!
> 
> @knabben Could you try adding the flag `fmt.Sprintf("--bearer-token=%s", framework.TestContext.BearerToken)` at
> 
> https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/remote/node_conformance.go#L182-L183

@knight42 the *Bearer token* at this point is "" getting from *framework.TestContext.BearerToken*

```
/e2e_node.test --run-kubelet-mode --logtostderr --node-name=test-cos-beta-85-13310-1041-1 --report-dir=/tmp/node-e2e-20201103T150632/results --feature-gates=DynamicKubeletConfig=true --kubelet-flags=--cgroups-per-qos=true --cgroup-root=/ --kubelet-flags=--pod-manifest-path=/tmp/node-e2e-20201103T150632/conformance-pod-manifest-20201103T145507 --bearer-token=
```

**Comment by knight42** [comment]
> The main of running remote is https://github.com/kubernetes/kubernetes/blob/2ad5f014a12f6b2a34e8ddc71e3020e9298444a5/test/e2e_node/runner/remote/run_remote.go which is not a e2e framework enabled runner like e2e_node.test. Since that is what starts the kubelet, we need to move the token generation outside, or otherwise synch them up.

Yes, I think you are totally right. @MHBauer could you try the following?
1. change this line https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/remote/node_conformance.go#L296 to 
```go
	cmd := fmt.Sprintf("'timeout -k 30s %fs docker run --rm --privileged=true --net=host -v /:/rootfs -v %s:%s -v %s:/var/result -e TEST_ARGS=--report-prefix=%s -e EXTRA_ENVS=%s -e TEST_ARGS=--bearer-token=dummy_token %s'",
```

2. change this line https://github.com/kubernetes/kubernetes/blob/f7cfe3ba0f0434f82208cc940c0770984e5758f5/test/e2e_node/remote/node_conformance.go#L182 to
```go
	startKubeletCmd := fmt.Sprintf("./%s --run-kubelet-mode --bearer-token=dummy_token --logtostderr --node-name=%s"+
```

Let's see if it works?

**Comment by MHBauer** [comment]
I had done the hardcoding of the token in those places, and I'm still waiting for the run, so maybe we can assume it works if done that way. :-D

Otherwise, very tangled together, difficult to plumb through cleanly. I suppose I can just add an arg to launchKubelet and relocate the token generator to a util func somewhere.

File: test/e2e_node/remote/node_conformance.go [hunk 6]
```diff
@@ -27,6 +27,7 @@ import (
 
 	"k8s.io/klog/v2"
 
+	"k8s.io/kubernetes/test/e2e/framework"
```
Comment (MHBauer) [inline test/e2e_node/remote/node_conformance.go:30]: I don't know if tangling this together is bad or not.

File: test/e2e/framework/test_context.go [hunk 7]
```diff
@@ -407,7 +407,7 @@ func createKubeConfig(clientCfg *restclient.Config) *clientcmdapi.Config {
 	return configCmd
 }
 
-func generateSecureToken(tokenLen int) (string, error) {
+func GenerateSecureToken(tokenLen int) (string, error) {
```
Comment (MHBauer) [inline test/e2e/framework/test_context.go:410]: If someone has an opinion on where to put this for everyone to consistently access it, or if I should just copy it into the remote runner code.

File: test/e2e_node/services/services.go (hunk 5 above)
Comment (MHBauer) [reply test/e2e_node/services/services.go:67]: yes, when started, we're outside of the ginkgo runner.

**Review by MHBauer — COMMENTED** [review]
PTAL

**Review by knight42 — APPROVED** [review]
LGTM

@MHBauer @knabben Thanks for taking time to sort out this problem, really appreciated 👍 And again, sorry for breaking these tests, it is a bit hard for me to foresee these test failures 😢

File: test/e2e_node/remote/node_conformance.go (hunk 6 above)
Comment (mmerkes) [reply test/e2e_node/remote/node_conformance.go:30]: Seems fair. It already has an indirect dependency on it anyway.

File: test/e2e/framework/test_context.go (hunk 7 above)
Comment (mmerkes) [reply test/e2e/framework/test_context.go:410]: Dunno if copying is ideal either. Maybe [util.go](https://github.com/kubernetes/kubernetes/blob/73190add9114a00ffe839acdd8c408c1e41ab4c5/test/e2e/framework/util.go)? I don't love kitchen sink files generally, but don't know if this one has any better home.

Comment (mmerkes) [reply test/e2e/framework/test_context.go:410]: It's also not the end of the world to leave it here for now.

**Comment by MHBauer** [comment]
for a conformance test this looks pretty flaky since 10/21 or so
[sig-cli] Kubectl client Kubectl server-side dry-run should check if kubectl can dry-run update Pods [Conformance]
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20check%20if%20kubectl%20can%20dry-run%20update%20Pods#f7be2b3498ba4b22e50d
looks like #95832

Verify is failing on a misisng golint comment, updating the PR.

File: test/e2e/framework/test_context.go (hunk 7 above)
Comment (oomichi) [reply test/e2e/framework/test_context.go:413]: Need to add the comment of this function to pass pull-kubernetes-verify job.
```
Errors from golint:
test/e2e/framework/test_context.go:410:1: exported function GenerateSecureToken should have comment or be unexported
```

**Review by oomichi — COMMENTED** [review]
The change itself is good for me.

/cc @oomichi

**Comment by MHBauer** [comment]
not sure what to do with this in pull-kubernetes-bazel-test:
```

[18,910 / 18,919] 897 / 964 tests; Testing //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test (run 2 of 2); 165s processwrapper-sandbox ... (8 actions, 7 running)
TIMEOUT: //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test (Summary)
      /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/staging/src/k8s.io/apiserver/pkg/server/filters/go_default_test/run_2_of_2/test.log
INFO: From Testing //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test (run 2 of 2):
==================== Test output for //staging/src/k8s.io/apiserver/pkg/server/filters:go_default_test (run 2 of 2):
2020/11/03 18:43:31 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc000708040 127.0.0.1:45306 in state active
  *net.TCPConn 0xc000708048 127.0.0.1:45308 in state active
Terminated
-- Test timed out at 2020-11-03 18:48:24 UTC -- 
```


I think his #95832 in pull-kubernetes-conformance-kind-ipv6-parallel 

maybe #96024 for pull-kubernetes-e2e-kind-ipv6 

/retest

**Comment by MHBauer** [comment]
@oomichi already seems okay with it, so for the framework testing changes
/assign @oomichi 
randomly picking someone from e2e_node/owners
@sjenning

**Review by oomichi — COMMENTED** [review]
Thanks for updating.

/approve
