### PR TITLE
Print a newline after ginkgo tests so the test infra doesn't think th…

### LINKED ISSUE #45279: Flake of pkg/kubectl/cmd/util/openapi.TestOpenapi
TestOpenapi failed frequently in recently CI runs, e.g. [here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41766/pull-kubernetes-unit/28845/#k8siokubernetespkgkubectlcmdutilopenapi-testopenapi)

```
k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi TestOpenapi 0.00s
go test -v k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi -run TestOpenapi$
```

cc/ @pwittrock @kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by pwittrock**
Fixes #45279

Print a newline after ginkgo tests so the test infra doesn't think that they fail

```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
Assigned to myself to make sure this actually solves the issue for our test infra

**Comment by pwittrock** [comment]
@k8s-bot node e2e test this

File: pkg/kubectl/cmd/util/openapi/openapi_cache_test.go [hunk 1]
```diff
@@ -14,7 +14,7 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
-package openapi
+package openapi_test
```
Comment (mengqiy) [inline pkg/kubectl/cmd/util/openapi/openapi_cache_test.go]: Why change the package name? Is this because trying to match the package name of openapi_suite_test.go?
I found other pkg usually the same name for the test.

Comment (pwittrock) [inline pkg/kubectl/cmd/util/openapi/openapi_cache_test.go]: Yes, to match the name of the suite.  I forget the tradeoffs, but this is the recommended way for ginkgo

**Comment by mengqiy** [comment]
LGTM
Will defer final call to @ixdy.
