### PR TITLE
Use the container whose limit is hit for system OOMs

### LINKED ISSUE #88868: SystemOOMs not reported for containers
**What happened**:

A SystemOOM event was not reported even when the memory limit hit was the root cgroup memory limit.

**What you expected to happen**:

A SystemOOM event should have been reported.

**How to reproduce it (as minimally and precisely as possible)**:

Do not set `--system-reserved` or `--kube-reserved`, and set `--eviction-hard=` to disable memory eviction on the kubelet.  Run a pod without memory limits which slowly consumes memory, such as with `k8s.gcr.io/stress:v1` from https://github.com/vishh/stress.  Use arguments -mem-alloc-size", "100Mi", "-mem-alloc-sleep", "10s".  This should trigger an OOM on the root cgroup, but no event will be generated.

**Anything else we need to know?**:

cAdvisor populates ContainerName and VictimContainerName from matching the regexp: [`Task in (.*) killed as a result of limit of (.*)`](https://github.com/google/cadvisor/blob/master/utils/oomparser/oomparser.go#L29).  A SystemOOM should mean VictimContainerName == "/", as we are looking for OOMs that are "killed as a results of limit of /".  However, we incorrectly [check ContainerName](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/oom/oom_watcher_linux.go#L75) instead in the kubelet. 

cc @kubernetes/sig-node-bugs @derekwaynecarr @sjenning @dchen1107

### PR DESCRIPTION
**Pull request by dashpole**
**What type of PR is this?**
/kind bug
/sig node
/priority important-soon

**What this PR does / why we need it**:
cAdvisor populates ContainerName and VictimContainerName from matching the regexp: Task in (.*) killed as a result of limit of (.*). A SystemOOM should mean VictimContainerName == "/", as we are looking for OOMs that are "killed as a results of limit of /". However, we incorrectly check ContainerName instead in the kubelet.

**Which issue(s) this PR fixes**:
Fixes #88868

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fix detection of SystemOOMs in which the victim is a container.
```

/assign @sjenning @derekwaynecarr @dchen1107

### CODE REVIEW

**Comment by dashpole** [comment]
/hold
i'll give others a day to make sure this looks correct to them.

File: pkg/kubelet/oom/oom_watcher_linux_test.go [hunk 1]
```diff
@@ -109,15 +109,15 @@ func TestWatcherRecordsEventsForOomEventsCorrectContainerName(t *testing.T) {
...
+			ContainerName:       recordEventContainerName + "/some-container",
+			VictimContainerName: recordEventContainerName,
 		},
 		{
 			Pid:                 1000,
 			ProcessName:         "fakeProcess",
 			TimeOfDeath:         time.Now(),
-			ContainerName:       "/dont-record-oom-event",
-			VictimContainerName: "some-container",
+			ContainerName:       recordEventContainerName + "/kubepods/some-container",
```
Comment (mattjmcnaughton) [inline pkg/kubelet/oom/oom_watcher_linux_test.go]: Is there a reason we changed this?

File: pkg/kubelet/oom/oom_watcher_linux_test.go [hunk 2]
```diff
@@ -57,8 +57,8 @@ func TestWatcherRecordsEventsForOomEvents(t *testing.T) {
 			Pid:                 1000,
 			ProcessName:         "fakeProcess",
 			TimeOfDeath:         time.Now(),
-			ContainerName:       recordEventContainerName,
-			VictimContainerName: "some-container",
+			ContainerName:       recordEventContainerName + "/some-container",
```
Comment (mattjmcnaughton) [inline pkg/kubelet/oom/oom_watcher_linux_test.go]: `ContainerName` will be `//some-container` (i.e. two slases as a prefix). Is that intended?

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
I believe this lgtm.

Can you add `cAdvisor populates ContainerName and VictimContainerName from matching the regexp: Task in (.*) killed as a result of limit of (.*). A SystemOOM should mean VictimContainerName == "/", as we are looking for OOMs that are "killed as a results of limit of /". However, we incorrectly check ContainerName instead in the kubelet.` from the issue into either the commit message or the pr?

Also, if I'm reading the git history correct, does this mean this feature never worked? In other words, would there ever have been a time where the container name is `/`? If this never worked, does that reflect a lack of e2e testing?

File: pkg/kubelet/oom/oom_watcher_linux_test.go (hunk 1 above)
Comment (dashpole) [reply pkg/kubelet/oom/oom_watcher_linux_test.go]: VictimContainerName should always be the prefix of ContainerName in practice.  I.E.
"Task in /kubepods/poduid/containerid killed as a result of /anothercgroup" isn't possible.

**Comment by dashpole** [comment]
> Also, if I'm reading the git history correct, does this mean this feature never worked? In other words, would there ever have been a time where the container name is /? If this never worked, does that reflect a lack of e2e testing?

Yeah, it never worked.  I thought about that as well in light of this issue.  The main problem is that e2e testing would be quite flaky.  SystemOOMs have been known to cause problems for the host VM, so a test that triggers a real SystemOOM would often fail.

File: pkg/kubelet/oom/oom_watcher_linux_test.go (hunk 2 above)
Comment (dashpole) [reply pkg/kubelet/oom/oom_watcher_linux_test.go]: Good catch, I fixed it here and elsewhere.

**Comment by mattjmcnaughton** [comment]
> > Also, if I'm reading the git history correct, does this mean this feature never worked? In other words, would there ever have been a time where the container name is /? If this never worked, does that reflect a lack of e2e testing?
> 
> Yeah, it never worked. I thought about that as well in light of this issue. The main problem is that e2e testing would be quite flaky. SystemOOMs have been known to cause problems for the host VM, so a test that triggers a real SystemOOM would often fail.

/retest

Yeah... that's a strong point that performing e2e tests with true system OOM events is a tricky game to play haha...

Updating the unit tests and clear comments/commit messages may be the best we can do for now.

**Comment by sjenning** [comment]
readding
/lgtm

**Comment by dashpole** [comment]
thanks for taking a look @sjenning 
/hold cancel

**Comment by KielChan** [comment]
I have came up with another problem about oom.
It is java app with tomcat. OOMKiller on system reject tomcat to apply more memory, and kill this tomcat process. Java app container does not restart and no oom event report.
Is it the same as this problem?

**Comment by dashpole** [comment]
No, this is for SystemOOM events, which you (hopefully) did not hit
