### PR TITLE
For e2e_node tests tell etcd to listen on ports 2379 and 4001

### LINKED ISSUE #29117: test-e2e-node broken by etcd port change from 4001 to 2379
etcd previously listened on 2379 and 4001, but in https://github.com/coreos/etcd/pull/5322 changed to just 4001.

Repro:

````
$ etcd --version
etcd Version: 3.0.3
Git SHA: 24a90ba
Go Version: go1.6.2
Go OS/Arch: linux/amd64
$ make test-e2e-node FOCUS=kubelet 
Go version: go version go1.6.2 linux/amd64
+++ [0718 14:10:51] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0718 14:10:51] Building go targets for linux/amd64:
    vendor/github.com/onsi/ginkgo/ginkgo
+++ [0718 14:10:51] Placing binaries
Running Suite: E2eNode Suite
============================
Random Seed: 1468847453 - Will randomize all specs
Will run 0 of 32 specs

I0718 14:11:06.059154   14147 e2e_build.go:41] Building k8s binaries...
Go version: go version go1.6.2 linux/amd64
+++ [0718 14:11:08] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0718 14:11:08] Building go targets for linux/amd64:
    cmd/kubelet
    cmd/kube-apiserver
    test/e2e_node/e2e_node.test
    vendor/github.com/onsi/ginkgo/ginkgo
+++ [0718 14:11:24] Placing binaries
I0718 14:11:26.396062   14147 e2e_node_suite_test.go:88] Pre-pulling images so that they are cached for the tests.
Failure [145.419 seconds]
[BeforeSuite] BeforeSuite 
/home/vagrant/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:107

  Unable to start node services.
  Timeout waiting for service `/home/vagrant/bin/etcd` health-check: http://127.0.0.1:4001/v2/keys/
````

I can submit a PR to change every 4001 to 2379.

### PR DESCRIPTION
**Pull request by bboreham**
This is the default for etcd2, but etcd3 only listens on 2379.
Specifying the ports keeps things consistent no matter which version the user has installed.

Fixes #29117

### CODE REVIEW

**Comment by dims** [comment]
Looks good to me 👍

**Comment by spxtr** [comment]
ok to test

**Comment by bboreham** [comment]
The Jenkins test failed because it ran on a machine where `/usr/bin/etcd` does not have the option `-listen-client-urls`.  This option was [apparently](https://github.com/coreos/etcd/commit/c2f96631d3f5e7dff46180bde7ca44ff65e1dcdd) added in version 0.5.

[Log file](https://00e9e64bac3741b84d3db5e75329b33529d9d9936ba68028d5-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F29267%2Fnode-pull-build-e2e-test%2F15206%2Fartifacts%2Ftmp-node-e2e-6ab56b82-e2e-node-coreos-alpha-1068-20160707-image%2Fetcd.log?qk=AD5uMEs_1pVLgFoeyd-jiPuPC6wJQGincrIdVqeLjzrv4Ktnc5pEQjOo9mJxvw0Gndg7ag8orM4IylZ1yWBrH_ClaCxKEi6nQf4rfVmQBzw9mrYeLAm8LI5Un_LYGJJ0dQz4u0VjyB4_tmoNTUJLKy-yeMw9sr6zyzTdQL8hNXznFtljr6MUmC8_JwWtARPAbWZdPres3xzujX2mJZj1ur2qqwcqS5FHulCuYRgPRZecJN_edIaV7gHh-5hVQaGauqUqAZDzREgBviNXzPabOVesQFfT88gTb3Z9sQUuV1i1jwCn1PHglxv08SdxuVRcLVEnlWCRnJbxZXgqq4Sdl-CkyuIkocMFnbqTbsj0QJ_KrDbcwRA6zD0YUEbB_xpjYMS1ZJ1UU9rWMY9Unh4UymWJ6uwLTFF-3d6uX0dRoJHq7mReIIomDDA_qtDTdITRJsXTiPP_b6NFL5XNz1kxq3rhMP5-3T-YXJcKS995EJ_9t2t6Ars2nUQclb50r53arwFLbKI66xHMVjfEPxb-RG47TU8XkGmEruP3V2gunw8tXgj3owUfL40eZYIBg0TEvyYzQrOj5xz6Wp0j-0SUjqq9MXNzbw2PIr05sJJ8zNybK6Rsuy2ckinpVeAAqJUshAsqeKwvUzSIF2Qf96OoDEklOkd8WJ3A4jQE2pbhRSnEzSNTlml5T_NVk1PrtMURlkzbgMgjSH3brL9zcmsU5rBFIyXUv0v-IrASG-mIbk_kG06RtKxrEcXHaB79sebBlzPG5jl337A8ca4YBeY_iy9JWbDJtol7-ReAvfV6JFHyB6jTDHcIbjkGgMYttEp9TSvQpQnXY6YQQJeR8ElXxUQVSudr_CbXohU0wn68rR5ruR5ZMlM3EUkkmAlfGUAFft1rUwnlz4TuOyQjGHjLiVcEE0gzHIpHdz2kqSZFKQH2jDbd0jdQMyrMOAWcJ4ety4cTPISUnQw8mZz7Vx3bH9ksLAlnx75HOzJ1I333wBTyCtbxv7KajmZJ9GZySIzI87ZnsBWAeVsZ)

Someone please point out the obvious thing I've missed.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
@bboreham node e2e tests are failing on CoreOS

<details>
etcd

Usage:
  etcd -name <name>
  etcd -name <name> [-data-dir=<path>]
  etcd -h | -help
  etcd -version

Options:
  -h -help          Show this screen.
  --version         Show version.
  -f -force         Force a new configuration to be used.
  -config=<path>    Path to configuration file.
  -name=<name>      Name of this node in the etcd cluster.
  -data-dir=<path>  Path to the data directory.
  -cors=<origins>   Comma-separated list of CORS origins.
  -v                Enabled verbose logging.
  -vv               Enabled very verbose logging.

Cluster Configuration Options:
  -discovery=<url>                Discovery service used to find a peer list.
  -peers-file=<path>              Path to a file containing the peer list.
  -peers=<host:port>,<host:port>  Comma-separated list of peers. The members
                                  should match the peer's '-peer-addr' flag.

Client Communication Options:
  -addr=<host:port>         The public host:port used for client communication.
  -bind-addr=<host[:port]>  The listening host:port used for client communication.
  -ca-file=<path>           Path to the client CA file.
  -cert-file=<path>         Path to the client cert file.
  -key-file=<path>          Path to the client key file.

Peer Communication Options:
  -peer-addr=<host:port>  The public host:port used for peer communication.
  -peer-bind-addr=<host[:port]>  The listening host:port used for peer communication.
  -peer-ca-file=<path>    Path to the peer CA file.
  -peer-cert-file=<path>  Path to the peer cert file.
  -peer-key-file=<path>   Path to the peer key file.
  -peer-heartbeat-interval=<time>
                          Time (in milliseconds) of a heartbeat interval.
  -peer-election-timeout=<time>
                          Time (in milliseconds) for an election to timeout.

Other Options:
  -max-result-buffer   Max size of the result buffer.
  -max-retry-attempts  Number of times a node will try to join a cluster.
  -retry-interval      Seconds to wait between cluster join retry attempts.
  -snapshot=false      Disable log snapshots
  -snapshot-count      Number of transactions before issuing a snapshot.
  -cluster-active-size Number of active nodes in the cluster.
  -cluster-remove-delay Seconds before one node is removed.
  -cluster-sync-interval Seconds between synchronizations for standby mode.

flag provided but not defined: -listen-client-urls
</details>

**Comment by bboreham** [comment]
> @bboreham node e2e tests are failing on CoreOS

@vish that's what I commented on at https://github.com/kubernetes/kubernetes/pull/29267#issuecomment-234600045; your test machine appears to have a really old etcd.  

Is it an option to upgrade the test machine to something newer?

I guess I could code up a check to see which one is installed and choose a flag to suit.

**Comment by vishh** [comment]
@yifan-gu The CoreOS test image has an old etcd binary. Will you be able to update it?

**Comment by timothysc** [comment]
@xiang90 or @hongchaodeng care to comment.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@euank can you help shepherd this PR? it needs a coreos test image change.

**Comment by euank** [comment]
Apologies for missing this in my queue for a bit, I'll look at updating the image today.

File: test/e2e_node/e2e_service.go [hunk 1]
```diff
@@ -190,7 +190,9 @@ func (es *e2eService) startEtcd() (*killCmd, error) {
 		}
 		etcdPath = defaultEtcdPath
 	}
-	cmd := exec.Command(etcdPath)
```
Comment (euank) [inline test/e2e_node/e2e_service.go]: We should change the lookpath bit above to try `etcd2` as the binary name and switch to `etcd` if it doesn't find it there. CoreOS ships both etcd and etcd2 currently, so this is using an old and not recommended version of etcd in that case, and it's possible another distro might follow this lead.

Comment (bboreham) [inline test/e2e_node/e2e_service.go]: Aha!  I'm not a CoreOS user, typically.

Should we extend the pattern to look for `etcd3`?

(This entire PR was triggered by me installing etcd V3 without realising this would cause everything to fail)

Comment (euank) [inline test/e2e_node/e2e_service.go]: The plan for `etcd3` is a bit different. It's not being shipped in the OS but rather as a container. For this code, it would probably be easiest to handle that difference in the CoreOS image config rather than the go code here. If we'd like to have the tests running against etcd3 on CoreOS I'd be happy to handle that in a followup PR.

**Comment by euank** [comment]
LGTM

**Comment by timothysc** [comment]
I need this for some other etcd changes so green lighting given other LGTMs.

**Comment by luxas** [comment]
Just one nit: I think we should switch over to `2379` for all etcd communication, and drop `4001`
@timothysc Is that something you're working on?

**Comment by timothysc** [comment]
Given that we may straddle etcd releases for at least one cycle (2+3) I'm fine with this PR and we can always change later on.

**Comment by luxas** [comment]
Yes, so dropping support for etcd2 in the roadmap for v1.5?

**Comment by bboreham** [comment]
@luxas note k8s currently uses 4001 and 4002 because it has two etcds ; you would need to switch to 2379 and another.

Etcd2 listens on 2379 and 4001 by default; that part isn't a problem.
