### PR TITLE
Fix system container detection in kubelet on systemd

### LINKED ISSUE #25909: kubelet container manager cgroup detection should error if cpu and memory differ
`kubelet` container manager setup node routine should ensure that cpu and memory cgroups for container runtime are of the same value, and warn if they are equal to `/`.

For background, on systemd environments, the default unit file for `docker` has CPU and Memory accounting not enabled, so the /proc/.../cgroup file reports `/` as cpu cgroup.

https://github.com/kubernetes/kubernetes/pull/25907#issuecomment-220449234

### PR DESCRIPTION
**Pull request by derekwaynecarr**
``` release-note
Fix system container detection in kubelet on systemd.

This fixed environments where CPU and Memory Accounting were not enabled on the unit 
that launched the kubelet or docker from reporting the root cgroup when 
monitoring usage stats for those components.
```

Fixes https://github.com/kubernetes/kubernetes/issues/25909

/cc @kubernetes/sig-node @kubernetes/rh-cluster-infra @vishh @dchen1107

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
If we are running e2e on systems with systemd, this could cause those systems to NOT report system container stats for `kubelet` or `runtime` unless they are launched from units with accounting enabled, or accounting is on by default in `/etc/systemd/system.conf`.

@pmorie @ingvagabund -- can you update the RHEL CI environment?

```shell
$ cat /etc/systemd/system.conf
...
DefaultCPUAccounting=true
DefaultMemoryAccounting=true
...
```

**Comment by ingvagabund** [comment]
```
$ cat /etc/systemd/system.conf
...
DefaultCPUAccounting=true
DefaultMemoryAccounting=true
...
```

This is suitable for ansible playbook so all can benefit from it. Do you think it should be enabled by default?

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -476,19 +476,49 @@ func ensureDockerInContainer(cadvisor cadvisor.Interface, oomScoreAdj int, manag
...
+	// users could enable CPU and memory accounting globally via /etc/systemd/system.conf (DefaultCPUAccounting=true DefaultMemoryAccounting=true).
+	// users could also enable CPU and memory accounting per unit via CPUAccounting=true and MemoryAccounting=true
+	// we only warn if accounting is not enabled for CPU or memory so as to not break local development flows where kubelet is launched in a terminal.
+	// for example, the cgroup for the user session will be something like /user.slice/user-X.slice/session-X.scope, but the cpu and memory
+	// cgroup will be the closest ancestor where accounting is performed (most likely /) on systems that launch docker containers.
+	// as a result, on those systems, you will not get cpu or memory accounting statistics for kubelet.
+	// in addition, you would not get memory or cpu accounting for the runtime unless accounting was enabled on its unit (or globally).
+	if systemd, found := cgs["name=systemd"]; found {
+		if systemd != cpu {
+			glog.Warningf("CPUAccounting not enabled for pid: %d", pid)
```
Comment (vishh) [inline pkg/kubelet/cm/container_manager_linux.go]: Should we require cpu and memory accounting to be enabled for kube daemons by default?

**Comment by vishh** [comment]
@derekwaynecarr This PR LGTM. For the future though, can we require cpu and memory accounting to be enabled by default?

**Comment by derekwaynecarr** [comment]
I wasn't sure everyone knew what to do when hacking on their local host.  Was worried it would cause people problems.   Ideas?

**Comment by derekwaynecarr** [comment]
Basically they need to turn global accounting on when they hack from a Linux host since most people don't have accounting on in user sessions.

**Comment by vishh** [comment]
@derekwaynecarr May be a flag to allow kubelet to run without stats? In any case, this PR is fine as-is. So I will add the LGTM label.

**Comment by vishh** [comment]
@derekwaynecarr Another option is to just validate metrics requirement as part of conformance testing and not change kubelet.

**Comment by derekwaynecarr** [comment]
The node e2e boxes that run systemd (in this case it looks like coreos stable), we need to enable cpu and memory accounting by default.  Will send a PR that does the same for vagrant as an example.

**Comment by alex-mohr** [comment]
fyi, required node test is failing.

**Comment by wojtek-t** [comment]
It seems that this PR broke node-e2e suite. Since this is blocking merge-queue, I'm going to revert this.
@k8s-oncall FYI

**Comment by derekwaynecarr** [comment]
This should not have been merged until the node e2e infrastructure was updated per:

https://github.com/kubernetes/kubernetes/issues/26198

I will re-open, but merge bot should not have merged this.

**Comment by ingvagabund** [comment]
@derekwaynecarr it should be enough to prefix the summary with [WIP] i believe to avoid merging
