### PR TITLE
Fix TestPortForward flake

### LINKED ISSUE #16394: flaky unit test in pkg/client/unversioned/portforward
```
--- FAIL: TestForwardPorts (0.01s)
	portforward_test.go:270: forward 2 ports with bidirectional data: server expected to receive "ghij", got "" for port 6000
E1027 15:46:48.833324    1555 portforward.go:303] error copying from local connection to remote stream: write tcp 127.0.0.1:45208->127.0.0.1:59640: write: broken pipe
I1027 15:46:48.833625    1555 portforward.go:213] Forwarding from 127.0.0.1:5555 -> 5555
I1027 15:46:48.833663    1555 portforward.go:213] Forwarding from [::1]:5555 -> 5555
E1027 15:46:48.834143    1555 portforward.go:202] Unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use
E1027 15:46:48.834190    1555 portforward.go:202] Unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use
W1027 15:46:48.834219    1555 portforward.go:154] Unable to listen on port 5555: All listeners failed to create with the following errors: listen tcp4 127.0.0.1:5555: bind: address already in use, listen tcp6 [::1]:5555: bind: address already in use
FAIL
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	0.188s
```

### PR DESCRIPTION
**Pull request by ncdc**
TestPortForward was failing occasionally due to the way the test was
written. It created a port forwarding session, then connected a client
to the local port, attempted to send some data, attempted to receive
some data, and then tore down the port forwarding session.
Unfortunately, some times the attempt to send data from the client to
the remote would be enqueued but not processed by the time the test tore
down everything. As a result, the data stream could get closed before
the client's data was transmitted to the server. If this happened, you'd
see an error such as 'forward 2 ports with bidirectional data: server
expected to receive "ghij", got "" for port 6000'.

This fixes the test by serializing the data flow: the client writes to
the remote, the remote waits to receive that data, the remote writes to
the client, and the client waits to receive the data from the remote.
This all takes place prior to the test tearing down port forwarding.

Fixes #16394

### CODE REVIEW

**Comment by ncdc** [comment]
@liggitt @kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
cc @lavalamp @thockin @wojtek-t

**Comment by thockin** [comment]
I am on my way out the door - I can not review this until next week - @wojtek-t ?

File: pkg/client/unversioned/portforward/portforward_test.go [hunk 1]
```diff
@@ -218,33 +220,23 @@ var _ kubelet.PortForwarder = &fakePortForwarder{}
...
-		pf.lock.Unlock()
-	}()
-
-	// server -> client
-	wg.Add(1)
-	go func() {
-		defer wg.Done()
+	// read from the client
+	received := make([]byte, len(pf.expected[port]))
+	n, err := stream.Read(received)
```
Comment (eparis) [inline pkg/client/unversioned/portforward/portforward_test.go]: Is this supposed to test the case where the client sends more than expected? io.Copy doesn't just stop at len(received) like Read...

**Comment by eparis** [comment]
I have to admit, I just don't understand what this fixes. It does however guarantee the send/receive order. In both cases the function can't get to the end until it runs all of the same code...

Was the problem that the `// server -> client` could happen before the `// client -> server` and now that is impossible? Is that the bug you are fixing?

**Comment by wojtek-t** [comment]
@thockin - can you please review it (this should fix the existing unit test flake).

**Comment by ncdc** [comment]
@eparis the issue is that the write issued to the local `net.Conn` isn't guaranteed to complete before `close(stopChan)` executes. If it doesn't complete, then the server never receives the data. If we instead do it ping-pong style, where everything is serial (client writes data, server waits for data, server receives data, server writes data, client waits for data, client receives data), we know that all the data is transmitted correctly.

This is only an issue with the unit test. When you run `kubectl port-forward ...`, the command runs until you hit ctrl-c. In the unit test, we're racing between writing data and simulating ctrl-c (closing stopChan).

File: pkg/client/unversioned/portforward/portforward_test.go (hunk 1 above)
Comment (ncdc) [inline pkg/client/unversioned/portforward/portforward_test.go]: I can switch it so the client calls `CloseWrite` on a `net.TCPConn` instead, in which case I can go back to using `io.Copy`. The reason I switched to only reading a certain amount is because the copy won't unblock unless we call `CloseWrite`.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please
