### PR TITLE
Using ServiceIPs instead of DNS names in the NetworkPolicy Probes + adding Interface decoupling

### LINKED ISSUE #102286: NetPol tests arbitrarily enforce the requirement "cluster DNS must be on pod port 53"
#### What happened:
The NetPol tests assume that creating a policy that blocks all egress except to UDP port 53 will still allow DNS. This does not work on OCP because while the DNS _Service_ is on `port: 53`, it redirects to `targetPort: 5353` on the DNS _Pods_ (so that the pods don't need to be pointlessly granted the `NET_BIND_SERVICE` capability), so a policy that only allows to port 53 will block DNS in this case.

#### What you expected to happen:
If Conformance does not require CoreDNS to run on port 53, then the NetPol tests should likewise not require it.

#### How to reproduce it (as minimally and precisely as possible):
Run e2e suite on OCP with ovn-kubernetes. Or else run on plain kube with DNS pods using a different port, with the DNS service mapping from 53 to that port.

#### Anything else we need to know?:
This was fixed for the old NetworkPolicy tests in https://github.com/kubernetes/kubernetes/pull/95453 by making them not use DNS. I still argue that there is absolutely no need to use DNS in the NetworkPolicy tests, because NetworkPolicy only operates on IPs, not on DNS names, so using DNS is just adding a gratuitous extra step that can fail spuriously (as it does here).

/cc @jayunit100

### PR DESCRIPTION
**Pull request by jayunit100**
fixes #102286 

This PR originally modified the tests to use Service IPs.  But that required me to add a few extra apiserver calls during the testing phase. 
So then @aojea had an idea about improving the framework to make the model better.
So, talked to @rajaskakodkar , and we added into this the ability to
make the model more easily reused, so that we dont have to make extra calls to the APIServer for getting service IPs. 

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/network/netpol/kubemanager.go [hunk 1]
```diff
@@ -258,45 +268,3 @@ func (k *kubeManager) deleteNamespaces(namespaces []string) error {
 	}
 	return nil
 }
-
-// waitForHTTPServers waits for all webservers to be up, on all protocols sent in the input,  and then validates them using the same probe logic as the rest of the suite.
-func (k *kubeManager) waitForHTTPServers(model *Model) error {
```
Comment (jayunit100) [inline test/e2e/network/netpol/kubemanager.go:263]: moving this out of here so that the things depending can live outside and the manager can implement a `i can probe` interface

File: test/e2e/network/netpol/test_helper.go [hunk 2]
```diff
@@ -64,6 +65,48 @@ func UpdatePolicy(k8s *kubeManager, policy *networkingv1.NetworkPolicy, namespac
 	framework.ExpectNoError(err, "Unable to update netpol %s/%s", namespace, policy.Name)
 }
 
+// waitForHTTPServers waits for all webservers to be up, on all protocols sent in the input,  and then validates them using the same probe logic as the rest of the suite.
```
Comment (jayunit100) [inline test/e2e/network/netpol/test_helper.go:68]: all the probing stuff lives here now

File: test/e2e/network/netpol/kubemanager.go [hunk 3]
```diff
@@ -111,9 +115,15 @@ func (k *kubeManager) getPod(ns string, name string) (*v1.Pod, error) {
...
 
-// probeConnectivity execs into a pod and checks its connectivity to another pod..
+// probeConnectivity execs into a pod and checks its connectivity to another pod.  
+// Implements the Prober interface.
 func (k *kubeManager) probeConnectivity(nsFrom string, podFrom string, containerFrom string, addrTo string, protocol v1.Protocol, toPort int, timeoutSeconds int) (bool, string, error) {
 	port := strconv.Itoa(toPort)
+	if addrTo == "" {
+		return false, "no IP provided", fmt.Errorf("wtf")
+	} else {
+		framework.Logf("POLLING %V >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ", addrTo)
```
Comment (jayunit100) [inline test/e2e/network/netpol/kubemanager.go:125]: promise to remove this later :)

**Comment by jayunit100** [comment]
@danwinship just a wip but i think it does the thing you want

File: test/e2e/network/netpol/model.go [hunk 4]
```diff
@@ -181,6 +187,20 @@ type Pod struct {
...
+}
+
+func (m *Model) SetServiceIP(namespace string, name string, ip string) {
+	pod, _ := m.FindPod(namespace, name)
+	pod.ServiceIP = ip
+	
+	pod, _ = m.FindPod(namespace, name)
+	if pod.ServiceIP != ip {
+		for i := 0 ; i < 30 ; i++ {
+			fmt.Print("omg")
```
Comment (mattfenwick) [inline test/e2e/network/netpol/model.go:200]: omg

File: test/e2e/network/netpol/model.go [hunk 5]
```diff
@@ -181,6 +187,20 @@ type Pod struct {
 	Namespace  string
 	Name       string
 	Containers []*Container
+	ServiceIP string
+}
+
+func (m *Model) SetServiceIP(namespace string, name string, ip string) {
+	pod, _ := m.FindPod(namespace, name)
```
Comment (mattfenwick) [inline test/e2e/network/netpol/model.go:194]: check error condition

File: test/e2e/network/netpol/model.go [hunk 6]
```diff
@@ -181,6 +187,20 @@ type Pod struct {
...
+	pod.ServiceIP = ip
+	
+	pod, _ = m.FindPod(namespace, name)
```
Comment (mattfenwick) [inline test/e2e/network/netpol/model.go:197]: why are you getting the pod twice?  probably not necessary

File: test/e2e/network/netpol/probe.go [hunk 7]
```diff
@@ -64,6 +74,12 @@ func ProbePodToPodConnectivity(k8s *kubeManager, model *Model, testCase *TestCas
 	for i := 0; i < size; i++ {
 		result := <-results
 		job := result.Job
+		if job.PodFrom == nil {
```
Comment (mattfenwick) [inline test/e2e/network/netpol/probe.go:77]: I don't these checks are necessary, if you actually check all the error conditions when constructing the model.

I'd recommend doing that -- make sure that the model is always in a valid state, so that these kinds of checks don't have to be performed by all clients.

File: test/e2e/network/netpol/probe.go [hunk 8]
```diff
@@ -83,11 +99,24 @@ func ProbePodToPodConnectivity(k8s *kubeManager, model *Model, testCase *TestCas
...
+				IsConnected: false,
+				Err: fmt.Errorf("empty service ip"),
+			}
+		}
+		// note that we can probe a dnsName instead of ServiceIP by using dnsName like so:
+		// we stopped doing this because we wanted to support netpol testing in non dns enabled
+		// clusters, but might re-enable it later. 
+		// dnsName := job.PodTo.QualifiedServiceAddress(job.ToPodDNSDomain)
+
+		// TODO how does ipv6 work here?
```
Comment (mattfenwick) [inline test/e2e/network/netpol/probe.go:118]: Is there an ipv6 problem caused by the changes in this PR?  Or can the ipv6 be separated into a different issue?

File: test/e2e/network/netpol/test_helper.go (hunk 2 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/test_helper.go:68]: 👍

File: test/e2e/network/netpol/network_policy.go [hunk 9]
```diff
@@ -1285,6 +1285,18 @@ func getK8SModel(f *framework.Framework) (string, string, string, *Model, *kubeM
 
 	model := defaultModel(namespaces, framework.TestContext.ClusterDNSDomain)
 
+	for _, ns := range model.Namespaces {
+		for _, pod := range ns.Pods {
+			svc, err := f.ClientSet.CoreV1().Services(pod.Namespace).Get(context.TODO(), fmt.Sprintf("s-%v-%v",pod.Namespace, pod.Name), metav1.GetOptions{})
```
Comment (mattfenwick) [inline test/e2e/network/netpol/network_policy.go:1290]: Doesn't the model (or pod model, I forget which) provide the service name?  If so, please use that so its logic isn't duplicated.

If not, we should add a method for that to the pod.

File: test/e2e/network/netpol/network_policy.go [hunk 10]
```diff
@@ -1285,6 +1285,18 @@ func getK8SModel(f *framework.Framework) (string, string, string, *Model, *kubeM
...
+			if err != nil {
+				framework.Logf("%v missing service in %v -------> %v", pod.Namespace, pod.Name, err)
```
Comment (mattfenwick) [inline test/e2e/network/netpol/network_policy.go:1292]: Why not just framework.Failf here?

File: test/e2e/network/netpol/model.go [hunk 11]
```diff
@@ -181,6 +187,20 @@ type Pod struct {
 	Namespace  string
 	Name       string
 	Containers []*Container
+	ServiceIP string
+}
+
+func (m *Model) SetServiceIP(namespace string, name string, ip string) {
```
Comment (mattfenwick) [inline test/e2e/network/netpol/model.go:193]: Shouldn't this method be on `(p *Pod)` instead of `Model`?  Every caller has a pod already, this method just adds error conditions?

File: test/e2e/network/netpol/network_policy.go [hunk 12]
```diff
@@ -1285,6 +1285,18 @@ func getK8SModel(f *framework.Framework) (string, string, string, *Model, *kubeM
...
+				time.Sleep(5*time.Second)
+				panic("uninitialized model, missing ns")
+			}
+			model.SetServiceIP(pod.Namespace, pod.Name,  svc.Spec.ClusterIP)
```
Comment (mattfenwick) [inline test/e2e/network/netpol/network_policy.go:1296]:
```suggestion
			pod.ServiceIP = svc.Spec.ClusterIP
```

File: test/e2e/network/netpol/probe.go [hunk 13]
```diff
@@ -17,11 +17,17 @@ limitations under the License.
 package netpol
 
 import (
+	"fmt"
 	"github.com/onsi/ginkgo"
 	v1 "k8s.io/api/core/v1"
 	"k8s.io/kubernetes/test/e2e/framework"
 )
 
+// decouple us from k8smanager.go
```
Comment (mattfenwick) [inline test/e2e/network/netpol/probe.go:26]: What's the point of doing this?  Now it's harder to click through the code because you hit the interface type instead of the implementation.

File: test/e2e/network/netpol/network_policy.go (hunk 9 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/network_policy.go]: done

File: test/e2e/network/netpol/network_policy.go (hunk 10 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/network_policy.go]: done

File: test/e2e/network/netpol/model.go (hunk 11 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/model.go]: done

File: test/e2e/network/netpol/probe.go (hunk 7 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/probe.go]: done

File: test/e2e/network/netpol/model.go (hunk 6 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/model.go]: done

File: test/e2e/network/netpol/model.go (hunk 5 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/model.go]: done

File: test/e2e/network/netpol/network_policy.go [hunk 14]
```diff
@@ -132,7 +132,7 @@ var _ = common.SIGDescribe("Netpol", func() {
 			}
 		})
 
-		ginkgo.It("should support a 'default-deny-ingress' policy [Feature:NetworkPolicy]", func() {
+		ginkgo.It("SMOKE should support a 'default-deny-ingress' policy [Feature:NetworkPolicy]", func() {
```
Comment (mattfenwick) [inline test/e2e/network/netpol/network_policy.go:135]: Revert this?

File: test/e2e/network/netpol/probe.go (hunk 8 above)
Comment (jayunit100) [reply test/e2e/network/netpol/probe.go:108]: havent tested ipv6 , need to think about what `ServiceIP` means :)

File: test/e2e/network/netpol/probe.go (hunk 13 above)
Comment (jayunit100) [reply test/e2e/network/netpol/probe.go:26]: we can just do a struct ? 
goal = decouple "Prober" bc its really confusing to see why the  "k8smanager"   is an input

File: test/e2e/network/netpol/network_policy.go (hunk 14 above)
Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go:135]: sure lets just keep it while were testing bc its easy to just do `ginkgo.focus=SMOKE` and run a test that things arent broken :)

File: test/e2e/network/netpol/kubemanager.go [hunk 15]
```diff
@@ -71,10 +70,14 @@ func (k *kubeManager) initializeCluster(model *Model) error {
 			}
 
 			createdPods = append(createdPods, kubePod)
-			_, err = k.createService(pod.Service())
+			svc, err := k.createService(pod.Service())
 			if err != nil {
 				return err
 			}
+			if svc.Spec.ClusterIP == "" {
```
Comment (aojea) [inline test/e2e/network/netpol/kubemanager.go:77]:
```suggestion
			if net.ParseIP(svc.Spec.ClusterIP) == nil {
```

File: test/e2e/network/netpol/network_policy.go [hunk 16]
```diff
@@ -1285,6 +1285,21 @@ func getK8SModel(f *framework.Framework) (string, string, string, *Model, *kubeM
...
 	model := defaultModel(namespaces, framework.TestContext.ClusterDNSDomain)
 
+	for _, ns := range model.Namespaces {
+		for _, pod := range ns.Pods {
+			service := pod.Service()
+			kubeService, err := f.ClientSet.CoreV1().Services(pod.Namespace).Get(context.TODO(), service.Name, metav1.GetOptions{})
+			if err != nil {
+				framework.Failf("unable to get service %s/%s: %+v", service.Namespace, service.Name, err)
+			}
+			if kubeService.Spec.ClusterIP == "" {
```
Comment (aojea) [inline test/e2e/network/netpol/network_policy.go:1295]:
```suggestion
			if net.ParseIP(kubeService.Spec.ClusterIP) == nil {
```

File: test/e2e/network/netpol/probe.go [hunk 17]
```diff
@@ -83,11 +89,24 @@ func ProbePodToPodConnectivity(k8s *kubeManager, model *Model, testCase *TestCas
 
 // probeWorker continues polling a pod connectivity status, until the incoming "jobs" channel is closed, and writes results back out to the "results" channel.
 // it only writes pass/fail status to a channel and has no failure side effects, this is by design since we do not want to fail inside a goroutine.
-func probeWorker(k8s *kubeManager, jobs <-chan *ProbeJob, results chan<- *ProbeJobResults, timeoutSeconds int) {
+func probeWorker(prober Prober, jobs <-chan *ProbeJob, results chan<- *ProbeJobResults, timeoutSeconds int) {
 	defer ginkgo.GinkgoRecover()
 	for job := range jobs {
 		podFrom := job.PodFrom
-		connected, command, err := k8s.probeConnectivity(podFrom.Namespace, podFrom.Name, podFrom.Containers[0].Name(), job.PodTo.QualifiedServiceAddress(job.ToPodDNSDomain), job.Protocol, job.ToPort, timeoutSeconds)
+		if job.PodTo.ServiceIP == "" {
```
Comment (aojea) [inline test/e2e/network/netpol/probe.go:96]: didn't we validate this already?

File: test/e2e/network/netpol/kubemanager.go [hunk 18]
```diff
@@ -71,10 +70,14 @@ func (k *kubeManager) initializeCluster(model *Model) error {
 			}
 
 			createdPods = append(createdPods, kubePod)
-			_, err = k.createService(pod.Service())
+			svc, err := k.createService(pod.Service())
 			if err != nil {
 				return err
 			}
+			if net.ParseIP(svc.Spec.ClusterIP) == nil {
+				return fmt.Errorf("empty IP address found for service %s/%s", svc.Namespace, svc.Name)
```
Comment (danwinship) [inline test/e2e/network/netpol/kubemanager.go:78]: I feel like this is testing "can't fail" kind of stuff, but maybe it's consistent with the rest of the netpol suite...

File: test/e2e/network/netpol/probe.go [hunk 19]
```diff
@@ -83,11 +89,24 @@ func ProbePodToPodConnectivity(k8s *kubeManager, model *Model, testCase *TestCas
...
+				IsConnected: false,
+				Err:         fmt.Errorf("empty service ip"),
+			}
+		}
+		// note that we can probe a dnsName instead of ServiceIP by using dnsName like so:
+		// we stopped doing this because we wanted to support netpol testing in non dns enabled
+		// clusters, but might re-enable it later.
+		// dnsName := job.PodTo.QualifiedServiceAddress(job.ToPodDNSDomain)
+
+		// TODO how does ipv6 work here?
```
Comment (danwinship) [inline test/e2e/network/netpol/probe.go:108]: For single-stack IPv6 you don't need to do anything.

In dual-stack clusters, ideally all tests would check both IPv4 and IPv6 connectivity. (ie, that you can connect to both `ClusterIPs` values when NetworkPolicy is supposed to allow the connection, and that you can't connect to either `ClusterIPs` value when NetworkPolicy is supposed to block the connection

File: test/e2e/network/netpol/probe.go (hunk 17 above)
Comment (jayunit100) [reply test/e2e/network/netpol/probe.go:96]: This should never be the case.  but, if it is the case, the probeWorker function should be robust enough to handle it and yield the right error message.  

Maybe in a follow on we should actually just have a `job.Validate()` function ?

File: test/e2e/network/netpol/probe.go (hunk 19 above)
Comment (jayunit100) [reply test/e2e/network/netpol/probe.go]: fixed to reflect this

File: test/e2e/network/netpol/kubemanager.go (hunk 18 above)
Comment (jayunit100) [reply test/e2e/network/netpol/kubemanager.go:78]: "sorta can fail" ... this will catch a regression in the impl of `createService` :)

File: test/e2e/network/netpol/network_policy.go (hunk 14 above)
Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go]: i removed this now that i think were mostly ready to mertge here

**Comment by jayunit100** [comment]
/squash just testing what command i need here

**Comment by jayunit100** [comment]
/tide/merge-method-squash

File: test/e2e/network/netpol/probe.go (hunk 13 above)
Comment (mattfenwick) [reply test/e2e/network/netpol/probe.go:27]: Can't figure out how to resolve this comment , but I'm fine with your changes here @jayunit100

Comment (jayunit100) [reply test/e2e/network/netpol/probe.go:27]: talked to matt on slack were fine w/ this interface

File: test/e2e/network/netpol/probe.go (hunk 17 above)
Comment (aojea) [reply test/e2e/network/netpol/probe.go:97]: it is ok, but then it should be 
```suggestion
		if net.ParseIP(job.PodTo.ServiceIP) == nil {
```

File: test/e2e/network/netpol/network_policy.go [hunk 20]
```diff
@@ -1285,6 +1286,21 @@ func getK8SModel(f *framework.Framework) (string, string, string, *Model, *kubeM
 
 	model := defaultModel(namespaces, framework.TestContext.ClusterDNSDomain)
 
+	for _, ns := range model.Namespaces {
+		for _, pod := range ns.Pods {
+			service := pod.Service()
+			kubeService, err := f.ClientSet.CoreV1().Services(pod.Namespace).Get(context.TODO(), service.Name, metav1.GetOptions{})
```
Comment (aojea) [inline test/e2e/network/netpol/network_policy.go:1292]: why do we have to get the service again?
Services are synchronous and clusterip inmutable

Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go]: pod.Service() is part of the model, which doesn't gaurantee anything about ordering around Service.Create . ill update the comments here to clarify .

Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go:1352]: https://github.com/kubernetes/kubernetes/issues/102919 <-- filed an issue here .... i think the broader question your asking is "why isn't the model stateful"  which is i think valid, but we should think a little more deeply about it before adding a one-off cache for service IPs.  

As is, we just don't have any assumptions in the framework that model data of any sort, including Service ClusterIPs,  needs to be cached.

Comment (aojea) [reply test/e2e/network/netpol/network_policy.go:1352]: scratch this comment, I didn't understand how this worked, the service returned is a local object not one from the API server

Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go:1352]: either way i think youve touched on something , so ill keep the other issue open

**Comment by jayunit100** [comment]
all set here @aojea ?

File: test/e2e/network/netpol/kubemanager.go [hunk 21]
```diff
@@ -111,9 +114,15 @@ func (k *kubeManager) getPod(ns string, name string) (*v1.Pod, error) {
...
-// probeConnectivity execs into a pod and checks its connectivity to another pod..
+// probeConnectivity execs into a pod and checks its connectivity to another pod.
+// Implements the Prober interface.
 func (k *kubeManager) probeConnectivity(nsFrom string, podFrom string, containerFrom string, addrTo string, protocol v1.Protocol, toPort int, timeoutSeconds int) (bool, string, error) {
 	port := strconv.Itoa(toPort)
+	if addrTo == "" {
+		return false, "no IP provided", fmt.Errorf("wtf")
+	} else {
+		framework.Logf("Starting probe from pod %v to %v", podFrom, addrTo)
+	}
```
Comment (aojea) [inline test/e2e/network/netpol/kubemanager.go:125]:
```suggestion
	if addrTo == "" {
		return false, "no IP provided", fmt.Errorf("wtf")
	} 
	framework.Logf("Starting probe from pod %v to %v", podFrom, addrTo)
```

File: test/e2e/network/netpol/model.go [hunk 22]
```diff
@@ -181,6 +181,7 @@ type Pod struct {
 	Namespace  string
 	Name       string
 	Containers []*Container
+	ServiceIP  string
```
Comment (aojea) [inline test/e2e/network/netpol/model.go:184]: This is the part that I'm finding difficult to understand, so each pod has its own service?

Comment (aojea) [reply test/e2e/network/netpol/model.go:184]: If it is that way, then I finally got it.
Pods where assigned a service by name convention, creation happened after, but now we need the IP, so convention is not longer enough to probe them

Comment (jayunit100) [reply test/e2e/network/netpol/model.go:184]: Yuppp

File: test/e2e/network/netpol/kubemanager.go [hunk 23]
```diff
@@ -111,9 +114,14 @@ func (k *kubeManager) getPod(ns string, name string) (*v1.Pod, error) {
 	return kubePod, nil
 }
 
-// probeConnectivity execs into a pod and checks its connectivity to another pod..
+// probeConnectivity execs into a pod and checks its connectivity to another pod.
+// Implements the Prober interface.
 func (k *kubeManager) probeConnectivity(nsFrom string, podFrom string, containerFrom string, addrTo string, protocol v1.Protocol, toPort int, timeoutSeconds int) (bool, string, error) {
 	port := strconv.Itoa(toPort)
+	if addrTo == "" {
+		return false, "no IP provided", fmt.Errorf("wtf")
```
Comment (aojea) [inline test/e2e/network/netpol/kubemanager.go:122]: missing trailing \"

Comment (aojea) [reply test/e2e/network/netpol/kubemanager.go:122]: add a serious message , kids are watching ;)

Comment (jayunit100) [reply test/e2e/network/netpol/kubemanager.go:122]: whoa no idea how that slipped through ha good catch

**Comment by aojea** [comment]
> /retest

The ingress job passes the tests but timesout https://github.com/kubernetes/test-infra/pull/22632 , it is not required also, we can omit it

**Comment by aojea** [comment]
/kind network
/release-note none
can we please squash all commits?

**Comment by jayunit100** [comment]
@aojea added the squash label, all good now ?

**Comment by aojea** [comment]
> @aojea added the squash label, all good now ?

what black magic is that "squash label" :) , I didn't know about , so it will squash and merge?

This LGTM, you are still missing the release-note thing to be able to merge.

@mattfenwick I defer to you the final LGTM for the netpol mechanics, I think that I have already demonstrated my ignorance in that area :sweat: 
https://github.com/kubernetes/kubernetes/pull/102354/files#r653457168
https://github.com/kubernetes/kubernetes/pull/102354#discussion_r651517900

**Comment by jayunit100** [comment]
ohhh bad rebase? 
/retest

**Comment by jayunit100** [comment]
```NetworkPolicy between server and client  should allow ingress access from updated pod```

```NetworkPolicy between server and client  should allow ingress access from updated pod```

```NetworkPolicy between server and client  should allow ingress access from updated pod ```

```Conntrack should be able to preserve UDP  traffic when server pod cycles for a NodePort service expand_more              ```

```Conntrack should be able to preserve UDP  traffic when server pod cycles for a NodePort service expand_more``` 

```NetworkPolicy between server and client  should enforce multiple egress policies with egress allow-all policy  taking precedence```

**Comment by jayunit100** [comment]
failures:
- `based on Multiple PodSelectors and NamespaceSelectors` 
- `based on NamespaceSelector with MatchLabels using default ns`
- `allow ingress access from namespace on one named port`
- `check ingress and egress policies`

**Comment by jayunit100** [comment]
this time
`Netpol NetworkPolicy between server and client should properly isolate pods that are selected by a policy allowing SCTP` failed

**Comment by jayunit100** [comment]
gofmt error, pushed and rebased again fixed

**Comment by jayunit100** [comment]
flakes:
`Netpol NetworkPolicy between server and client should properly isolate pods that are selected by a policy allowing SCTP, even if the plugin doesn't support SCT`
and
`TCP_WAIT`

,... re running.....

also removed an unused method

**Comment by jayunit100** [comment]
@rajaskakodkar can add the removal of the extra ServiceIP Querying, he has a solution.... 
can you push that commit onto this PR  Rajas ?

**Comment by rajaskakodkar** [comment]
> @rajaskakodkar can add the removal of the extra ServiceIP Querying, he has a solution....
> can you push that commit onto this PR Rajas ?

done

**Comment by rajaskakodkar** [comment]
added one more commit to include the refactor for SCTP test which was missed in the previous commit, prow should be happy now :)

File: test/e2e/network/netpol/network_policy.go [hunk 24]
```diff
@@ -119,21 +119,27 @@ and what is happening in practice:
 
 var _ = common.SIGDescribe("Netpol", func() {
 	f := framework.NewDefaultFramework("netpol")
+	//modelMap maps the root namespace of the test to the model created before running the test.
+	var modelMap = make(map[string]*Model)
```
Comment (mattfenwick) [inline test/e2e/network/netpol/network_policy.go:123]: There are multiple goroutines reading from and writing to `modelMap`, right?  This looks like a concurrency bug.

Comment (aojea) [reply test/e2e/network/netpol/network_policy.go:123]: why do we need a map to share across the tests?
you only need a model by test, no? 
you can create just global `var model  Model` and initialize it in BeforeEach, it is a closure variable 
https://onsi.github.io/ginkgo/#extracting-common-setup-beforeeach

Comment (rajaskakodkar) [reply test/e2e/network/netpol/network_policy.go:123]: yes, that was the original idea but we noticed issues while running the tests in parallel. `model` was being shared by multiple tests and there would only one root namespace for multiple tests.

Comment (aojea) [reply test/e2e/network/netpol/network_policy.go:123]: ... pfff, ginkgo is very opinionated, we should have this very clear or we'll end with unpredictable results...
each `It.` block must be independent  https://onsi.github.io/ginkgo/#avoiding-test-pollution

Comment (rajaskakodkar) [reply test/e2e/network/netpol/network_policy.go:123]: so keeping `var model Model` global and initializing it in BeforeEach should not be issue even if tests are run in parallel?

Comment (aojea) [reply test/e2e/network/netpol/network_policy.go:123]: global as in the `Describe` block, you have more details here https://github.com/onsi/ginkgo/issues/440

Comment (jayunit100) [reply test/e2e/network/netpol/network_policy.go:123]: imo we could just skip relying on `BeforeEach`  entirely, and initialize inside of the individual tests in a one liner function that send framework as an arg to a `initializeNamespacePods` or whatever, if we dont want to play the ginkgo guessing game.

Comment (rajaskakodkar) [reply test/e2e/network/netpol/network_policy.go:123]: Now we have 3 options:
1. stick to the modelMap approach but that may have concurrency issues
2. go with global model in `Describe` block and initialize it in `BeforeEach`
3. what Jay suggested

I have tried 1 and 2 locally with 2 ginkgo nodes, running tests in parallel and it worked for both. I don't see a reason why Jay's approach will fail either, because it is same as 2, has the same lines of `BeforeEach` in every `It`.

Let me know what we should go with.

Comment (aojea) [reply test/e2e/network/netpol/network_policy.go:123]: If we are under ginkgo we should do as ginkgo recommend, if all options are equivalent , option 2 is what ginkgo documents
https://github.com/kubernetes/kubernetes/pull/102354#discussion_r667853246

Comment (rajaskakodkar) [reply test/e2e/network/netpol/network_policy.go:123]: cool, I'll add the commit

**Comment by aojea** [comment]
/tests pull-kubernetes-e2e-ubuntu-gce-network-policies 
seems we are good now :clap: , let's run it a several times

**Comment by rajaskakodkar** [comment]
no failures seen in Netpol as of now, job is failing due to other tests :( 
/retest

**Comment by jayunit100** [comment]
ok, .... im running this concurrently locally as well to double check .... then lets get signoff from @mattfenwick  or @aojea ....

**Comment by aojea** [comment]
> ok, .... im running this concurrently locally as well to double check .... then lets get signoff from @mattfenwick or @aojea ....

LGTM but defer to Matt, he has more expertise here

**Comment by jayunit100** [comment]
hmmmm  before we merge....  
```
KUBERNETES_PROVIDER="skeleton" GINKGO_PARALLEL_NODES=2 ./hack/ginkgo-e2e.sh --ginkgo.focus=Netpol
```

had 12 failures for me.... broad range of tests no obvious smoking gun.... 

any thoughts on why? re running now....  hope im just misusing ginkgo :)

**Comment by aojea** [comment]
> hmmmm before we merge....
> 
> ```
> KUBERNETES_PROVIDER="skeleton" GINKGO_PARALLEL_NODES=2 
> ./hack/ginkgo-e2e.sh --ginkgo.focus=Netpol
> ```
> 
> had 12 failures for me.... broad range of tests no obvious smoking gun....
> 
> any thoughts on why? re running now.... hope im just misusing ginkgo :)

is this is kind in your laptop with 4g :eyes

**Comment by jayunit100** [comment]
hahahah not the 4g one  :) anyways re ran looking good now (ignore the failures, they are related to my old CNI) 
```
Ran 50 of 6429 Specs in 1321.947 seconds
FAIL! -- 47 Passed | 3 Failed | 0 Pending | 6379 Skipped

```

so , re running one last time then im signing off on this as well

**Comment by jayunit100** [comment]
and ran again, passed . so im good on this. lets merge pleaasssse

**Comment by aojea** [comment]
> and ran again, passed . so im good on this. lets merge pleaasssse

edit the description to add the release-node block none , I'd like @mattfenwick  to take a final pass

**Comment by mattfenwick** [comment]
/lgtm

nice one 😄

**Comment by aojea** [comment]
ping @kubernetes/milestone-maintainers 
this is addressing a bug and fixing a test, so it qualifies for milestone

**Comment by jayunit100** [comment]
merry xmas to our friends at red hat that are testing without DNS :) @danwinship @aojea @astoycos  
once merged can yall confirm these new tests work for you  ?

**Comment by jayunit100** [comment]
/priority/critical-urgent

**Comment by jayunit100** [comment]
im kinding this as regression since, dan mentioned this regresses some test results on openshift

**Comment by jayunit100** [comment]
can me merge this for 22 now that its tagged correctly ?

**Comment by danwinship** [comment]
> im kinding this as regression since, dan mentioned this regresses some test results on openshift

We have a local hack to deal with it (https://github.com/openshift/kubernetes/pull/770/files) but yes, we'd like this to get in (so we can replace the hack with a backport of this PR).

(Though FTR, we just had to temporarily disable the entire Netpol suite anyway because it's too flaky in our CI system due to bad timing assumptions. More fixes to come...)

**Comment by andrewsykim** [comment]
> (Though FTR, we just had to temporarily disable the entire Netpol suite anyway because it's too flaky in our CI system due to bad timing assumptions. More fixes to come...)

Fwiw the netpol tests are very flaky in our CI system as well, would be good to collaborate on how to make these more stable so it's more sustainable to run.

**Comment by aojea** [comment]
> > (Though FTR, we just had to temporarily disable the entire Netpol suite anyway because it's too flaky in our CI system due to bad timing assumptions. More fixes to come...)
> 
> Fwiw the netpol tests are very flaky in our CI system as well, would be good to collaborate on how to make these more stable so it's more sustainable to run.

it is a peformance problem, they run a lot of pods in parallel, in CI systems with low resources they don't even run ... we have already discussed this, and this is one of the reasons why I asked to keep the old tests around :wink:

**Comment by andrewsykim** [comment]
> it is a peformance problem, they run a lot of pods in parallel, in CI systems with low resources they don't even run ... we have already discussed this, and this is one of the reasons why I asked to keep the old tests around wink

I'm glad we did this, but fwiw I think there are issues with both the new and old one :(. The old one has flaky timing issues, and I guess the new one requires clusters with a lot of resources.

**Comment by aojea** [comment]
> I'm glad we did this, but fwiw I think there are issues with both the new and old one :(. The old one has flaky timing issues, and I guess the new one requires clusters with a lot of resources.

yeah, completely agree,  is a pick your poison thing right now

File: test/e2e/network/netpol/kubemanager.go (hunk 18 above)
Comment (neolit123) [reply test/e2e/network/netpol/kubemanager.go:77]: can this only be an empty IP at this point?

if not, might be better to reword:
```
return fmt.Errorf("invalid IP address found for service %s/%s: %s", svc.Namespace, svc.Name, svc.Spec.ClusterIP)
```

https://pkg.go.dev/net#ParseIP
> If s is not a valid textual representation of an IP address, ParseIP returns nil.

File: test/e2e/network/netpol/test_helper.go [hunk 25]
```diff
@@ -18,14 +18,15 @@ package netpol
 
 import (
 	"context"
-	"time"
-
+	"fmt"
 	"github.com/onsi/ginkgo"
+	"github.com/pkg/errors"
```
Comment (neolit123) [inline test/e2e/network/netpol/test_helper.go:23]: there is this:
https://github.com/kubernetes/kubernetes/issues/103043

line 107 could be fmt.Errorf(...) to avoid the import.

File: test/e2e/network/netpol/kubemanager.go [hunk 26]
```diff
@@ -70,10 +69,14 @@ func (k *kubeManager) initializeCluster(model *Model) error {
 			}
 
 			createdPods = append(createdPods, kubePod)
-			_, err = k.createService(pod.Service())
+			svc, err := k.createService(pod.Service())
 			if err != nil {
 				return err
 			}
+			if net.ParseIP(svc.Spec.ClusterIP) == nil {
+				return fmt.Errorf("empty IP address found for service %s/%s", svc.Namespace, svc.Name)
```
Comment (neolit123) [inline test/e2e/network/netpol/kubemanager.go:77]: can this only be an empty IP at this point?

if not, might be better to reword:
```
return fmt.Errorf("invalid IP address found for service %s/%s: %s", svc.Namespace, svc.Name, svc.Spec.ClusterIP)
```

https://pkg.go.dev/net#ParseIP
> If s is not a valid textual representation of an IP address, ParseIP returns nil.
