### PR TITLE
Fix DaemonSet misscheduled status not updating on node taint changes

### LINKED ISSUE #132459: DaemonSet wrongfully reported as misscheduled on added node
### What happened?

Since we upgraded from v1.32 to v1.33, we are having with DaemonSets getting (and keeping) flagged as misscheduled on newly added nodes. 

The DS seems to be able to get scheduled very early before the node gets tainted as not ready, and later (when it does have the taints) it gets flagged as "misscheduled" (due to the taints). After the taints dissapear when the node is ready, this status does not get updated and the DS is still reported as misscheduled. Triggering a status update by adding a bogus label removes the misscheduled status. 

### What did you expect to happen?

I would expected either or both of these things:

1. The pod not to get scheduled before the not ready taint is set
2. The DS status update routine to get triggered by node taint removal

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up a cluster
2. Add a couple of DS-es (we have 4 of these) without tolerations
3. Gracefully shutdown a node
4. Kubectl delete that node
5. Boot that node (so it will be added to the cluster)
6. Wait until that node is ready
7. `kubectl get -A ds -o json | jq '.items[] | select(.status.numberMisscheduled > 0) | .metadata.name'` if empty, goto 3

We are able to reproduce this behavior with 4 DS every 3-6 of above cylces.

### Anything else we need to know?

We are unable to reproduce above problem on 1.32, even after 100 cycles

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.2
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

</details>

### Cloud provider

This is Talos Linux on VMWare vSphere

### OS version

<details>

```console
$ talosctl version
Client:
        Tag:         v1.10.3
        SHA:         dde2cebc
        Built:
        Go version:  go1.24.3
        OS/Arch:     linux/amd64
Server:
        NODE:        <nope>
        Tag:         v1.10.3
        SHA:         dde2cebc
        Built:
        Go version:  go1.24.3
        OS/Arch:     linux/amd64
        Enabled:     RBAC
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by xigang**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes a bug in the DaemonSet controller where the `NumberMisscheduled` status field does not get updated when node properties (labels or taints) change, leading to incorrect DaemonSet status reporting.

**Problem:**
The `syncNodeUpdate` function in the DaemonSet controller has insufficient trigger conditions that only handle pod creation and deletion scenarios:

```
// Before: Only handles create/delete scenarios
if (shouldRun && !scheduled) || (!shouldContinueRunning && scheduled) {
    dsc.enqueueDaemonSet(ds)
}
```

This misses the critical third scenario where pods are already scheduled but their scheduling legitimacy changes due to node updates (e.g., when taints are added/removed).

**Specific scenario that fails:**

1. A DaemonSet pod gets scheduled on a node before the node is tainted as "not-ready"
2. When the node becomes ready and the taint is removed, the pod transitions from "misscheduled" to "correctly scheduled"
3. However, the DaemonSet status is not updated because the current logic doesn't trigger a sync for this state transition
4. The pod remains incorrectly flagged as misscheduled in the DaemonSet status

**Solution:**
Expand the trigger conditions to ensure any DaemonSet that has a relationship with the updated node (either should run on it or already has pods on it) gets resynced:

```
// After: Handles all scenarios including state transitions
if shouldRun || scheduled {
    dsc.enqueueDaemonSet(ds)
}
```

This ensures that DaemonSet status fields like `NumberMisscheduled`, `CurrentNumberScheduled`, etc., are recalculated whenever node properties change.

#### Which issue(s) this PR is related to:

Fixes #132459

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xigang** [comment]
cc @wojtek-t @soltysh

**Comment by xigang** [comment]
/cc @atiratree 
@wojtek-t is on vacation. Please take a review this PR. Thanks.

File: pkg/controller/daemon/daemon_controller.go [hunk 1]
```diff
@@ -1469,7 +1469,7 @@ func (dsc *DaemonSetsController) syncNodeUpdate(ctx context.Context, nodeName st
 		daemonPods := podsByDS[dsKey]
 		scheduled := len(daemonPods) > 0
 
-		if (shouldRun && !scheduled) || (!shouldContinueRunning && scheduled) {
+		if shouldRun || scheduled {
```
Comment (atiratree) [inline pkg/controller/daemon/daemon_controller.go]: This seems unnecessarily strong and could result in superfluous syncs. Would the following work for you?

```suggestion
		if (shouldRun && !scheduled) || (!shouldContinueRunning && scheduled) || (scheduled && ds.Status.NumberMisscheduled > 0 ) {
```

It would be good to add some explanation above this change and test it with at least a unit test (`TestUpdateNode`).

**Review by atiratree — COMMENTED** [review]
/triage accepted
/priority backlog

File: pkg/controller/daemon/daemon_controller.go (hunk 1 above)
Comment (xigang) [reply pkg/controller/daemon/daemon_controller.go]: @atiratree Thanks for the review. Code updated and unit test added.

**Comment by xigang** [comment]
@atiratree Please take another look, thanks!

File: pkg/controller/daemon/daemon_controller.go [hunk 2]
```diff
@@ -1445,7 +1445,15 @@ func (dsc *DaemonSetsController) syncNodeUpdate(ctx context.Context, nodeName st
...
 		scheduled := len(daemonPods) > 0
 
-		if (shouldRun && !scheduled) || (!shouldContinueRunning && scheduled) {
+		// Enqueue DaemonSet for sync in the following scenarios:
+		// 1. (shouldRun && !scheduled): Node now meets scheduling requirements but no pod exists
+		//    - Need to create a new pod on this node
+		// 2. (!shouldContinueRunning && scheduled): Node no longer meets requirements but pod exists
+		//    - Need to delete the existing pod from this node
+		// 3. (scheduled && ds.Status.NumberMisscheduled > 0): DaemonSet pod exists and misscheduled count is nonzero.
+		//    - For example: a pod was scheduled before the node became Ready; after the node becomes Ready or taints are removed, the pod may now be valid.
```
Comment (atiratree) [inline pkg/controller/daemon/daemon_controller.go]:
```suggestion
		//    - For example: a pod was scheduled before the node became unready and tainted; after the node becomes ready and taints are removed, the pod may now be valid again.
```

File: pkg/controller/daemon/daemon_controller_test.go [hunk 3]
```diff
@@ -2410,6 +2410,9 @@ func TestUpdateNode(t *testing.T) {
 		expectedEventsFunc func(strategyType apps.DaemonSetUpdateStrategyType) int
 		shouldEnqueue      bool
 		expectedCreates    func() int
+		// Indicates whether a DaemonSet pod was already present on the node before the node transitioned to Ready state.
```
Comment (atiratree) [inline pkg/controller/daemon/daemon_controller_test.go]:
```suggestion
		// Indicates whether a DaemonSet pod was already present on the node before the node transitioned to Ready and schedulable state.
```

File: pkg/controller/daemon/daemon_controller_test.go [hunk 4]
```diff
@@ -2410,6 +2410,9 @@ func TestUpdateNode(t *testing.T) {
...
+		// (In other words, was the DaemonSet pod scheduled before the node lost its NotReady taint?)
```
Comment (atiratree) [inline pkg/controller/daemon/daemon_controller_test.go]:
```suggestion
		// (In other words, was the DaemonSet pod scheduled before the node lost its readiness / was tainted?)
```

**Review by atiratree — COMMENTED** [review]
Added a couple of suggestions. LGTM overall.

**Comment by xigang** [comment]
@atiratree  Thanks a lot, the new comment has been fixed

File: pkg/controller/daemon/daemon_controller_test.go [hunk 5]
```diff
@@ -2410,6 +2410,9 @@ func TestUpdateNode(t *testing.T) {
 		expectedEventsFunc func(strategyType apps.DaemonSetUpdateStrategyType) int
 		shouldEnqueue      bool
 		expectedCreates    func() int
+		//  Indicates whether a DaemonSet pod was already present on the node before the node transitioned to Ready and schedulable state.
```
Comment (atiratree) [inline pkg/controller/daemon/daemon_controller_test.go]: thx, one last nit:

```suggestion
		// Indicates whether a DaemonSet pod was already present on the node before the node transitioned to Ready and schedulable state.
```

Comment (xigang) [reply pkg/controller/daemon/daemon_controller_test.go]: @atiratree Thanks, fixed.

**Comment by xigang** [comment]
@atiratree Thanks, fixed. For approval.

**Comment by sebastiangaiser** [comment]
Thanks for fixing this 👍🏻 
Would it be possible to backport this to `v1.34`, too?

**Comment by xigang** [comment]
I’ll cherry-pick it.

**Comment by sebastiangaiser** [comment]
Awesome thanks 👍🏻

**Comment by xigang** [comment]
@sebastiangaiser Merged into release-1.34.

**Comment by jonkerj** [comment]
It would be really great if it could make it into 1.33 as well. Should have asked that earlier, but our product lags 1 k8s minor behind, so we will be releasing it with 1.33, preferably without this bug.

**Comment by xigang** [comment]
> It would be really great if it could make it into 1.33 as well. Should have asked that earlier, but our product lags 1 k8s minor behind, so we will be releasing it with 1.33, preferably without this bug.

Done
