### PR TITLE
Check for an empty value in validateField

### LINKED ISSUE #20627: kubectl panic: runtime error: invalid memory address or nil pointer dereference
I am getting this runtime error on kubectl create:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7+e4e6878", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"6a81b50c7e97bbe0ade075de55ab4fa34f049dc2", GitTreeState:"clean"}

$ kubectl --server=http://localhost:18080 create -f test-rc.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x3b5cdc]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x0, 0x0, 0xc8205e7c80, 0x28, 0xc82056a130, 0x6, 0x0, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:241 +0x127c
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x74c480, 0xc8203d4900, 0xc8205e7c20, 0x25, 0xc82056a150, 0x5, 0xc8205d9680, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:258 +0xc87
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc8202f80c0, 0x7656e0, 0xc8205e7890, 0xc8205e7bf0, 0x21, 0xc8204400a0, 0xc, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:208 +0x11d0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x7656e0, 0xc8205e7890, 0xc8203d4de0, 0x20, 0xc8204400a0, 0xc, 0x0, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:231 +0xd3
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x74c480, 0xc8203d49c0, 0xc8203d4dc0, 0x1d, 0xc8204400c0, 0x5, 0xc8205d95f0, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:258 +0xc87
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc8202f80c0, 0x7656e0, 0xc8205e7860, 0xc8203d4ba0, 0x13, 0xc82025bbe0, 0xa, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:208 +0x11d0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x7656e0, 0xc8205e7860, 0xc8203d4b40, 0x12, 0xc82025bbe0, 0xa, 0xc8205d9200, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:231 +0xd3
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc8202f80c0, 0x7656e0, 0xc8205e77d0, 0xc82056b440, 0xe, 0xc82040fbe0, 0x12, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:208 +0x11d0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x7656e0, 0xc8205e77d0, 0xc82056b430, 0xd, 0xc82040fbe0, 0x12, 0xc8205d9050, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:231 +0xd3
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc8202f80c0, 0x7656e0, 0xc8205e7770, 0xc82056b400, 0x5, 0xc82000e180, 0x1c, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:208 +0x11d0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8202f80c0, 0x7656e0, 0xc8205e7770, 0xc82056ae80, 0x4, 0xc82000e180, 0x1c, 0xc8205d8d80, 0x0, 0x0, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:231 +0xd3
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc8202f80c0, 0x7656e0, 0xc8205e76e0, 0x0, 0x0, 0xc8203d4a40, 0x18, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:208 +0x11d0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateBytes(0xc8202f80c0, 0xc820302000, 0x2ff, 0x300, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:156 +0x8a1
k8s.io/kubernetes/pkg/kubectl/cmd/util.getSchemaAndValidate(0x13a03d0, 0xc8202660a0, 0xc820302000, 0x2ff, 0x300, 0xa08c30, 0x3, 0xc8203005e0, 0x2, 0xc8200f2520, ...)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:357 +0x8a1
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*clientSwaggerSchema).ValidateBytes(0xc8202569f0, 0xc820302000, 0x2ff, 0x300, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:379 +0x803
k8s.io/kubernetes/pkg/kubectl/resource.ValidateSchema(0xc820302000, 0x2ff, 0x300, 0x13a0178, 0xc8202569f0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:210 +0x1e4
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc8202e2c00, 0xc8202f36a0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:481 +0x2fc
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc8202f35a0, 0xc8202f36a0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:441 +0x12d
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc8202e8e70, 0x1, 0x1, 0xc8202ea990, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:186 +0x12c
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc8202f35c0, 0xc8202ea990, 0x0, 0x0)
	<autogenerated>:98 +0xb7
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x13a02b8, 0xc8202f35c0, 0xc8202ea930, 0xc8202e2c80, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:361 +0xaa
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc8202f35e0, 0xc8202e2c80, 0x0, 0x0)
	<autogenerated>:111 +0xb7
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x13a02e0, 0xc8202f35e0, 0xc8202f3620, 0x3, 0x4, 0xc8202f3660, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:276 +0xf0
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc8202ea960, 0xc8202f3660, 0x0, 0x0)
	<autogenerated>:127 +0xac
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x13a0308, 0xc8202ea960, 0xc8202e2c40, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:294 +0x12f
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc8202e8e90, 0xc8202e2c40, 0x0, 0x0)
	<autogenerated>:123 +0xae
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc8202f4230, 0xc8202e2c40, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:79 +0x6d
k8s.io/kubernetes/pkg/kubectl/cmd.RunCreate(0xc8201174a0, 0xc82000d180, 0x13643d0, 0xc820030010, 0xc8201d11c0, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:128 +0x547
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdCreate.func1(0xc82000d180, 0xc8201fed80, 0x0, 0x3)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:61 +0xf8
github.com/spf13/cobra.(*Command).execute(0xc82000d180, 0xc8201fecf0, 0x3, 0x3, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/Godeps/_workspace/src/github.com/spf13/cobra/command.go:499 +0x869
github.com/spf13/cobra.(*Command).Execute(0xc82000cc40, 0x0, 0x0)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/Godeps/_workspace/src/github.com/spf13/cobra/command.go:582 +0x46a
main.main()
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0xf9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xedf360)
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/private/tmp/kubernetes-cli20160129-22889-8puto1/kubernetes-1.1.7/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 10 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 14 [IO wait]:
net.runtime_pollWait(0x136c228, 0x72, 0xc820012160)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82022ad10, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82022ad10, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82022acb0, 0xc820236000, 0x1000, 0x1000, 0x0, 0x1360050, 0xc820012160)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200303f8, 0xc820236000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x136c2e8, 0xc8200303f8, 0xc8202007e8, 0xc820236000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820232a00, 0xc820236000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820234240)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820234240, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820200790)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:685 +0xc78

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc820200790)
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.5.3/libexec/src/net/http/transport.go:686 +0xc9d
```

And this is test-rc.yaml file:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v10
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
    version: v10
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: carbon-relay
        image: banno/carbon-relay
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        env:
        - name: DESTINATIONS
          # Azure DNS
          value: 192.168.81.25:17124
        args:
        -
      volumes:
      - name: etcd-storage
        emptyDir: {}
      - hostPath:
          path: /etc/ssl/certs
        name: ssl-certs-host
      dnsPolicy: Default
```

I can see that the empty `args: -` may be causing this but I'm sure we can show a better error for this.

### LINKED ISSUE #26927: Creating pod with empty argument crashes kubectl
`kubectl` crashes when creating a pod with one or more empty arguments. This also happens when creating a deployment with this as a pod spec.

I'm using v1.2.3.

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

I was able to get a similar crash with `kubectl` 1.2.4.

```bash
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
```

```bash
$ kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - echo
    - hello
    -
    - world

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x8386fb]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x0, 0x0, 0xc2081fc3a0, 0x1a, 0xc208587d88, 0x6, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:247 +0x198b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x11677e0, 0xc2082b7fc0, 0xc2081fc300, 0x17, 0xc208587dc0, 0x5, 0xc208462750, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:264 +0xa7b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843ced0, 0xc2081fc2a0, 0x13, 0xc20848d050, 0xc, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x118cbe0, 0xc20843ced0, 0xc2081fc200, 0x12, 0xc20848d050, 0xc, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:237 +0xe0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x11677e0, 0xc2081fc020, 0xc20843a590, 0xf, 0xc20848d070, 0x5, 0xc2084626c0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:264 +0xa7b
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843cea0, 0xc20843a579, 0x5, 0xc208613320, 0xa, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc20811c480, 0x118cbe0, 0xc20843cea0, 0xc20842b8f4, 0x4, 0xc208613320, 0xa, 0xc208462630, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:237 +0xe0
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateObject(0xc20811c480, 0x118cbe0, 0xc20843ce40, 0x0, 0x0, 0xc20843a498, 0x6, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:214 +0x119d
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).ValidateBytes(0xc20811c480, 0xc20806d130, 0xa6, 0xb0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:163 +0x89a
k8s.io/kubernetes/pkg/kubectl/cmd/util.getSchemaAndValidate(0x7fc7b327ee30, 0xc2081e86c0, 0xc20806d130, 0xa6, 0xb0, 0x1621220, 0x3, 0x1637ce0, 0x2, 0xc2081fda40, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:757 +0x407
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*clientSwaggerSchema).ValidateBytes(0xc2082033b0, 0xc20806d130, 0xa6, 0xb0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:819 +0xf41
k8s.io/kubernetes/pkg/kubectl/resource.ValidateSchema(0xc20806d130, 0xa6, 0xb0, 0x7fc7b327ea20, 0xc2082033b0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:213 +0x1f4
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc20810b3c0, 0xc2081a85c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:481 +0x2e0
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc2081a83e0, 0xc2081a85c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:441 +0x12e
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc208116fe0, 0x1, 0x1, 0xc2081a8560, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:198 +0x17e
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc2081a8420, 0xc2081a8560, 0x0, 0x0)
        <autogenerated>:100 +0xbd
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x7fc7b327eba0, 0xc2081a8420, 0xc20810aec0, 0xc2081a8520, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:361 +0x10b
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc2081a8480, 0xc2081a8520, 0x0, 0x0)
        <autogenerated>:117 +0xbd
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x7fc7b327ebc8, 0xc2081a8480, 0xc2081a84c0, 0x3, 0x4, 0xc2081a8500, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:269 +0x110
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc208203c50, 0xc2081a8500, 0x0, 0x0)
        <autogenerated>:138 +0xbc
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x7fc7b327ebf0, 0xc208203c50, 0xc208203c80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:296 +0x171
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc208117020, 0xc208203c80, 0x0, 0x0)
        <autogenerated>:133 +0xbb
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc208201f80, 0xc208203c80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:79 +0x73
k8s.io/kubernetes/pkg/kubectl/cmd.RunCreate(0xc208162960, 0xc208122000, 0x7fc7b3278030, 0xc208046008, 0xc20801ee80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:143 +0x743
k8s.io/kubernetes/pkg/kubectl/cmd.func·012(0xc208122000, 0xc2081a9200, 0x0, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/create.go:66 +0x107
github.com/spf13/cobra.(*Command).execute(0xc208122000, 0xc2081a90a0, 0x2, 0x2, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc20806b600, 0xc208122000, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc20806b600, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e6b160)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 16 [IO wait]:
net.(*pollDesc).Wait(0xc2081c73a0, 0x72, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081c73a0, 0x0, 0x0)
        /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081c7340, 0xc2081e2000, 0x1000, 0x1000, 0x0, 0x7fc7b3278378, 0xc208117038)
        /usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208046418, 0xc2081e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/src/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc7b327e1e0, 0xc208046418, 0xc20806ce18, 0xc2081e2000, 0x1000, 0x1000, 0x1309f20, 0x0, 0x0)
        /usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081c9800, 0xc2081e2000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20819fb60)
        /usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20819fb60, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20806cdc0)
        /usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 17 [select]:
net/http.(*persistConn).writeLoop(0xc20806cdc0)
        /usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/src/go/src/net/http/transport.go:661 +0xcbc
```

### PR DESCRIPTION
**Pull request by asalkeld**
``` release-note
* Fix a panic when args was not supplied with any values.
```

reflect.TypeOf() can take a nil (it then returns a nil), but
Kind() panics on a nil.

Now the user gets the following output:
./kubectl.sh --server=http://localhost:8080 create -f ../../test-files/test-rc.yaml
error validating "../../test-files/test-rc.yaml": error validating data: unexpected nil value for field spec.template.spec.containers[0].args[0]; if you choose to ignore these errors, turn validation off with --validate=false

fixes #20627 and fixes #26927

### CODE REVIEW

File: pkg/api/validation/schema.go [hunk 1]
```diff
@@ -311,6 +311,9 @@ func (s *SwaggerSchema) validateField(value interface{}, fieldName, fieldType st
 		return s.ValidateObject(value, fieldName, fieldType)
 	}
 	allErrs := []error{}
+	if reflect.TypeOf(value) == nil {
```
Comment (kargakis) [inline pkg/api/validation/schema.go]: How about `reflect.ValueOf(value).IsNil()`? Also I would expect this check to be at the top of this function.

Comment (asalkeld) [inline pkg/api/validation/schema.go]: Hi @kargakis , I have (locally) : 

1. moved the check up to the top of the function.
2. changed the check as you suggested, but it has the same behaviour as before (it panics)

./kubectl.sh --server=http://localhost:8080 create -f ../../test-files/test-rc.yaml
panic: reflect: call of reflect.Value.IsNil on string Value

goroutine 1 [running]:
panic(0x1795040, 0xc82027e520)
	/usr/lib/go-1.6/src/runtime/panic.go:464 +0x3e6
reflect.Value.IsNil(0x14b9240, 0xc8202f1bb0, 0x98, 0xc8202f1bb0)
	/usr/lib/go-1.6/src/reflect/value.go:978 +0xe6
k8s.io/kubernetes/pkg/api/validation.(*SwaggerSchema).validateField(0xc8200ee750, 0x14b9240, 0xc8202f1bb0, 0xc8202f1ba0, 0xa, 0xc8206aa0d8, 0x6, 0xc82025cbd0, 0x0, 0x0, ...)
	/home/angus/work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/api/validation/schema.go:302 +0xd3
Note the following text from https://golang.org/pkg/reflect/#Value.IsNil
" if v was created by calling ValueOf with an uninitialized interface variable i, i==nil will be true but v.IsNil will panic as v will be the zero Value. "

So I am going to stick with the nil check so we can prevent the panic. I'll update the PR so that the check is at the beginning of the function.

Comment (kargakis) [inline pkg/api/validation/schema.go]: Hm, I would expect IsNil to work. Anyway. Can you also add a test in hack/test-cmd.sh that tests that the panic is fixed?

Comment (smarterclayton) [inline pkg/api/validation/schema.go]: IsZero() || IsNil() would be correct then.

Comment (asalkeld) [inline pkg/api/validation/schema.go]: Hi @smarterclayton @kargakis , thanks for the review.

So I had a look at IsZero() in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/generate.go#L52

The problem with that (as I see it) is it will return true for any of the type specific zeros ("", 0, 0.0) so this means that a user will never be able to set an integer "0" or just a empty string. Is this truly what we want? Wouldn't it *break things*? 

Remember all I am trying to do here is prevent a panic when TypeOf() returns nil

test program:
package main

import (
	"fmt"
	"reflect"
)

func IsZero(i interface{}) bool {
	if i == nil {
		return true
	}
	return reflect.DeepEqual(i, reflect.Zero(reflect.TypeOf(i)).Interface())
}

func validateField(value interface{}, fieldName string) {
	fmt.Printf("%v] value:'%v', IsZero:%v\n", fieldName, reflect.ValueOf(value), IsZero(value))
}

func main() {
	var s *string
	x := "foo"
	e := ""
	i := 9
	var pi *int
	zi := 0

	validateField(s, "*string")
	validateField(x, "valid s")
	validateField(e, "empty s")
	validateField(zi, "0 int  ")
	validateField(i, "valid i")
	validateField(pi, "*int   ")
}

output:

*string] value:'<nil>', IsZero:true
valid s] value:'foo', IsZero:false
empty s] value:'', IsZero:true
0 int  ] value:'0', IsZero:true
valid i] value:'9', IsZero:false
*int   ] value:'<nil>', IsZero:true

**Comment by kargakis** [comment]
lgtm

re-assigning to @bgrant0607 for vetting the schema validation

File: pkg/api/validation/schema.go [hunk 2]
```diff
@@ -297,6 +297,10 @@ func (s *SwaggerSchema) isGenericArray(p swagger.ModelProperty) bool {
 var versionRegexp = regexp.MustCompile(`^v.+\..*`)
 
 func (s *SwaggerSchema) validateField(value interface{}, fieldName, fieldType string, fieldDetails *swagger.ModelProperty) []error {
+	allErrs := []error{}
+	if reflect.TypeOf(value) == nil {
+		return append(allErrs, fmt.Errorf("unexpected nil value for field %v", fieldName))
```
Comment (nikhiljindal) [inline pkg/api/validation/schema.go]: If the aim is just to prevent panic, then we can also return nil here instead of returning an error?
args is an optional field so its fine for it to be null?

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 3]
```diff
@@ -0,0 +1,44 @@
+apiVersion: v1
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: Is `invalid-rc-with-empty-args` a better name (clearer why it is broken)

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+kind: ReplicationController
+metadata:
+  name: kube-dns-v10
+  namespace: kube-system
+  labels:
+    k8s-app: kube-dns
+    version: v10
+    kubernetes.io/cluster-service: "true"
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: We dont need all these fields. remove

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+            cpu: 100m
+            memory: 50Mi
+          requests:
+            cpu: 100m
+            memory: 50Mi
+        env:
+        - name: DESTINATIONS
+          value: 192.168.81.25:17124
+        args:
+        -
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: Add a comment here pointing out that is the important part

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+      labels:
+        k8s-app: kube-dns
+        version: v10
+        kubernetes.io/cluster-service: "true"
+    spec:
+      containers:
+      - name: carbon-relay
+        image: banno/carbon-relay
+        resources:
+          limits:
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: Dont need resource limits. remove

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+spec:
+  replicas: 1
+  selector:
+    k8s-app: kube-dns
+    version: v10
+  template:
+    metadata:
+      labels:
+        k8s-app: kube-dns
+        version: v10
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: Just one label is enough. Remove version and cluster-service

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 8]
```diff
@@ -0,0 +1,44 @@
...
+      - name: carbon-relay
+        image: banno/carbon-relay
+        resources:
+          limits:
+            cpu: 100m
+            memory: 50Mi
+          requests:
+            cpu: 100m
+            memory: 50Mi
+        env:
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: remove env vars

File: hack/testdata/broken-rc-for-validate-test.yaml [hunk 9]
```diff
@@ -0,0 +1,44 @@
...
+        - name: DESTINATIONS
+          value: 192.168.81.25:17124
+        args:
+        -
+      volumes:
```
Comment (nikhiljindal) [inline hack/testdata/broken-rc-for-validate-test.yaml]: remove volumes

**Comment by nikhiljindal** [comment]
Thanks for sending the PR and apologies for the delay in looking at it.
We are in a 1.3 code freeze for the next few weeks. Will merge after it.

File: pkg/api/validation/schema.go (hunk 2 above)
Comment (asalkeld) [inline pkg/api/validation/schema.go]: Hi @nikhiljindal , thanks for the review.

So I tried returning a success (empty error list) then ran a hacked version of "blog-logging". The user gets a rather poor error:

```
./kubectl.sh create -f ../examples/blog-logging/counter-pod.yaml 
unable to decode "../examples/blog-logging/counter-pod.yaml": [pos 94]: json: expect char '"' but got char 'n'
```
Instead of the following:
```
./kubectl.sh create -f ../examples/blog-logging/counter-pod.yaml 
error validating "../examples/blog-logging/counter-pod.yaml": error validating data: unexpected nil value for field spec.containers[0].args[0]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by asalkeld** [comment]
@nikhiljindal there is no rush from my side. I'll cleanup the test yaml file and push a new commit.

**Comment by nikhiljindal** [comment]
ok to test

**Comment by nikhiljindal** [comment]
cc @kubernetes/kubectl

lgtm, thx
