### PR TITLE
apiserver: fix timeout handler

### LINKED ISSUE #29001: API server panics when writing response
When I was running large scale kubemark test (2000 Nodes with 95 pods each) my API server crashed with the error:
```
I0715 12:14:23.387809    3511 trace.go:61] Trace "List /api/v1/namespaces/e2e-tests-density-idftq/pods" (started 2016-07-15 12:13:01.712298253 +0000 UTC):
[102.412µs] [102.412µs] About to List from storage
[2.53469971s] [2.534597298s] Listing from storage done
[2.954350982s] [419.651272ms] Self-linking done
[1m21.675466193s] [1m18.721115211s] Writing http response done (130003 items)
[1m21.675467856s] [1.663µs] END
E0715 12:14:23.393199    3511 apiserver.go:210] recover from panic situation: - Header called after Handler finished^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:206^M
    /usr/local/go/src/runtime/asm_amd64.s:472^M
    /usr/local/go/src/runtime/panic.go:443^M
    /usr/local/go/src/net/http/h2_bundle.go:4452^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:170^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:238^M
    <autogenerated>:8^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:102^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120^M
    /usr/local/go/src/net/http/server.go:1618^M
    /usr/local/go/src/net/http/server.go:1910^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:485^M
    /usr/local/go/src/net/http/server.go:1618^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:420^M
    /usr/local/go/src/net/http/server.go:1618^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:66^M
    /usr/local/go/src/net/http/server.go:1618^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101^M
    /usr/local/go/src/net/http/server.go:1618^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101^M
    /usr/local/go/src/net/http/server.go:1618^M
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:194^M
    /usr/local/go/src/runtime/asm_amd64.s:1998^M

I0715 12:14:23.387986    3511 handlers.go:164] GET /api/v1/nodes/10.180.12.88: (144.600059ms) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/12483d9] 146.148.109.243:33217]
I0715 12:14:23.388150    3511 handlers.go:164] GET /api/v1/nodes/10.180.1.92: (154.464521ms) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/12483d9] 104.197.214.41:58039]
panic: Header called after Handler finished [recovered]
        panic: Header called after Handler finished

goroutine 54829830 [running]:
panic(0x20f0220, 0xc821e07010)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
net/http.(*http2responseWriter).Header(0xc956288948, 0x7fe725a76c88)
        /usr/local/go/src/net/http/h2_bundle.go:4452 +0x78
k8s.io/kubernetes/pkg/httplog.(*respLogger).Header(0xc9702bd260, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:170 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).Header(0xc9c39fb9e0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:238 +0x39
k8s.io/kubernetes/pkg/apiserver.logStackOnRecover(0x7fe725d5b8a8, 0xc82014ad90, 0x20f0220, 0xc8f69cd900, 0x7fe725b36be8, 0xc8fc256620)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:213 +0x2d9
k8s.io/kubernetes/pkg/apiserver.InstallRecoverHandler.func1(0x20f0220, 0xc8f69cd900, 0x7fe725b36be8, 0xc8fc256620)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:195 +0x5e
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func2(0xc82032cea0, 0xc83a235710)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:206 +0x6a
panic(0x20f0220, 0xc8f69cd900)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
net/http.(*http2responseWriter).Header(0xc956288948, 0x2)
        /usr/local/go/src/net/http/h2_bundle.go:4452 +0x78
k8s.io/kubernetes/pkg/httplog.(*respLogger).Header(0xc9702bd260, 0x2decc58)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:170 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).Header(0xc9c39fb9e0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:238 +0x39
k8s.io/kubernetes/pkg/apiserver/metrics.(*fancyResponseWriterDelegator).Header(0xc8fc256630, 0xc8bc4a8e10)
        <autogenerated>:8 +0x53
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc8bee93a10, 0xc90d296780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:102 +0x35c
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc82032cea0, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820ceb980, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8202c07b0, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
k8s.io/kubernetes/pkg/apiserver.WithAuthorizationCheck.func1(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:485 +0xf4
net/http.HandlerFunc.ServeHTTP(0xc820313ac0, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.WithImpersonation.func1(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:420 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc820313b00, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:66 +0x2c9
net/http.HandlerFunc.ServeHTTP(0xc8203f5270, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc820522660, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc820522680, 0x7fe725b36be8, 0xc8fc256620, 0xc83c513260)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc8216ec9c0, 0x7fe725b36ba8, 0xc8fc256620, 0xc83c513260, 0xc90d296720)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:194 +0x91
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:196 +0x15b
```

It happened around 110k-120k Pods in the cluster. 

It looks like a bug in http2 handling. cc @timothysc @smarterclayton @wojtek-t @lavalamp @kubernetes/sig-api-machinery

### PR DESCRIPTION
**Pull request by xiang90**
Protect access of the original writer. Panics if anything has wrote
into the original writer or the writer is hijacked when times out.

Fix #29001 

/cc @smarterclayton @lavalamp 

The next step would be respect the request context once 1.7 is out.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29594)

### CODE REVIEW

File: pkg/apiserver/handlers.go [hunk 1]
```diff
@@ -281,17 +307,40 @@ func (tw *baseTimeoutWriter) timeout(msg string) {
 			enc := json.NewEncoder(tw.w)
 			enc.Encode(errors.NewServerTimeout(api.Resource(""), "", 0))
 		}
+	} else {
+		// The timeout writer has been used by the inner handler. There is
+		// no way to timeout the HTTP request at the point. We have to shutdown
+		// the connection for HTTP1 or reset stream for HTTP2.
+		//
+		// Note from: Brad Fitzpatrick
```
Comment (xiang90) [inline pkg/apiserver/handlers.go]: @lavalamp @smarterclayton It seems that what Brad suggested might not work for us, since we actually try to recover the panic ourselves somehow in RecoverPanics?

**Comment by lavalamp** [comment]
Will take a look later this week. Stuck in meetings yesterday, today, and tomorrow.

File: pkg/apiserver/handlers.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/apiserver/handlers.go]: Which level of recover panics?  Would that be outside of the golang http server/client code?

Comment (xiang90) [inline pkg/apiserver/handlers.go]: panic in ServeHTTP. We want to throw that out directly to go HTTP Server, so it can gracefully kill the connection/stream. Right now we catch all panics in the handler, so it wont propagate to HTTP Server at all.

**Comment by xiang90** [comment]
@lavalamp @smarterclayton Can you take a look at this pr? Thank you very much!

**Comment by lavalamp** [comment]
Really sorry I didn't manage to get to this. Giving it to @krousey who will be more responsive than me. :)

File: pkg/apiserver/handlers.go (hunk 1 above)
Comment (krousey) [inline pkg/apiserver/handlers.go]: The original crash was caused because panics weren't being handed back up to the HTTP server to recover. I'm fine with a panic here, because it would be handed back to the server. 

We should invert the nesting of timeout and `RecoverPanics` so that we are again protected from panic crashes.

File: pkg/apiserver/handlers.go [hunk 2]
```diff
@@ -188,11 +190,11 @@ func (t *timeoutHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 		return
 	}
 
-	done := make(chan struct{}, 1)
+	done := make(chan struct{})
 	tw := newTimeoutWriter(w)
 	go func() {
 		t.handler.ServeHTTP(tw, r)
```
Comment (krousey) [inline pkg/apiserver/handlers.go]: This is the crash path. Panic in a goroutine bringing down the API server. In addition to inverting the timeout and recover handlers in genericapiserver.go, it wouldn't hurt to add a recover here as well just to be safe.

File: pkg/apiserver/handlers.go (hunk 1 above)
Comment (xiang90) [inline pkg/apiserver/handlers.go]: @krousey I want this panic to be propagated to the actual go HTTP Server. So that it can cleanly kill http stream/connections. But now it is recovered by panicHandler in API server.

File: pkg/apiserver/handlers.go (hunk 2 above)
Comment (xiang90) [inline pkg/apiserver/handlers.go]: Will this bring down the server? I thought server was recovered from panic. Also the log in the original issue showed that the API server recovered from the panic. We just did not handle the request correctly.

Comment (krousey) [inline pkg/apiserver/handlers.go]: Yes. And the server did crash. Here. There was one that was recovered by [`apiserver.InstallRecoverHandler`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/apiserver.go#L192), but it was soon followed by one that crashed with: 

```console
I0715 12:14:23.388150    3511 handlers.go:164] GET /api/v1/nodes/10.180.1.92: (154.464521ms) 200 [[kubemark/v1.4.0 (linux/amd64) kubernetes/12483d9] 104.197.214.41:58039]
panic: Header called after Handler finished [recovered]
        panic: Header called after Handler finished

goroutine 54829830 [running]:
panic(0x20f0220, 0xc821e07010)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
net/http.(*http2responseWriter).Header(0xc956288948, 0x7fe725a76c88)
        /usr/local/go/src/net/http/h2_bundle.go:4452 +0x78
...
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc8216ec9c0, 0x7fe725b36ba8, 0xc8fc256620, 0xc83c513260, 0xc90d296720)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:194 +0x91
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:196 +0x15b
```

`t.handler` here does not have any recover wrapper around it, and the code shouldn't rely on it to have one either.

File: pkg/apiserver/handlers.go (hunk 1 above)
Comment (krousey) [inline pkg/apiserver/handlers.go]: Yep. We agree.

**Comment by xiang90** [comment]
@krousey Thanks for your review. I will improve this pr, and ping you later.

File: pkg/apiserver/handlers.go (hunk 2 above)
Comment (lavalamp) [inline pkg/apiserver/handlers.go]: (not sure if relevant, but we now crash for real when there's a panic, so
if you don't want to bring down the whole process you'll need to intercept
it somewhere.)

Comment (krousey) [inline pkg/apiserver/handlers.go]: @lavalamp This is exactly what I was trying to point out. In the spirit of `http.Server`'s calls to `ServeHTTP`, we squash any panic in this goroutine.

Comment (lavalamp) [inline pkg/apiserver/handlers.go]: No-- we now deliberately bring down the entire process on a panic, this is something that changed a few weeks ago. I mean, you could `defer kruntime.HandlePanics()` or whatever but it now re-panics after catching panics.

Comment (krousey) [inline pkg/apiserver/handlers.go]: Oh so the crash is desired. Ok.

Comment (lavalamp) [inline pkg/apiserver/handlers.go]: Yeah, it makes it more obvious to monitoring tools. It also means that
someone who figures out how to trigger one can potentially DOS apiserver--
for this reason we did leave the mechanism in place and it can be turned on
by setting kruntime.ReallyCrash = false. (So you probably should defer
HandleCrash to keep that working...)

Comment (xiang90) [inline pkg/apiserver/handlers.go]: @krousey @lavalamp 

Even with your recent change at https://github.com/kubernetes/kubernetes/pull/28800. HTTP server will not really panic the whole process by default I think. HTTP server has internal mechanism to recover.

See this example:
``` go
package main

import (
	"fmt"
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/panic", func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if r := recover(); r != nil {
				fmt.Println("handle panic")
				panic(r)
			}
		}()

		fmt.Fprintf(w, "panic")
		panic("panic")
	})

	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

```bash
handle panic
2016/08/09 11:12:51 http: panic serving 127.0.0.1:61476: panic
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc820086200)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x28bca0, 0xc82006eee0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1.1()
	/Users/xiangli/playground/panic.go:14 +0x121
panic(0x28bca0, 0xc82006eee0)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1(0x7857a8, 0xc8200756c0, 0xc8200ec1c0)
	/Users/xiangli/playground/panic.go:19 +0xee
net/http.HandlerFunc.ServeHTTP(0x4062c0, 0x7857a8, 0xc8200756c0, 0xc8200ec1c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820072a80, 0x7857a8, 0xc8200756c0, 0xc8200ec1c0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820086080, 0x7857a8, 0xc8200756c0, 0xc8200ec1c0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820086200)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
handle panic
2016/08/09 11:12:56 http: panic serving 127.0.0.1:61477: panic
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc820086380)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x28bca0, 0xc82006ef90)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1.1()
	/Users/xiangli/playground/panic.go:14 +0x121
panic(0x28bca0, 0xc82006ef90)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1(0x7857a8, 0xc820075790, 0xc8200ec2a0)
	/Users/xiangli/playground/panic.go:19 +0xee
net/http.HandlerFunc.ServeHTTP(0x4062c0, 0x7857a8, 0xc820075790, 0xc8200ec2a0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820072a80, 0x7857a8, 0xc820075790, 0xc8200ec2a0)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820086080, 0x7857a8, 0xc820075790, 0xc8200ec2a0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820086380)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
handle panic
2016/08/09 11:12:57 http: panic serving 127.0.0.1:61478: panic
goroutine 22 [running]:
net/http.(*conn).serve.func1(0xc820086480)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x28bca0, 0xc82006f020)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1.1()
	/Users/xiangli/playground/panic.go:14 +0x121
panic(0x28bca0, 0xc82006f020)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
main.main.func1(0x7857a8, 0xc820075930, 0xc8200ec380)
	/Users/xiangli/playground/panic.go:19 +0xee
net/http.HandlerFunc.ServeHTTP(0x4062c0, 0x7857a8, 0xc820075930, 0xc8200ec380)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc820072a80, 0x7857a8, 0xc820075930, 0xc8200ec380)
	/usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820086080, 0x7857a8, 0xc820075930, 0xc8200ec380)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820086480)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by xiang90** [comment]
@krousey PTAL.

File: pkg/apiserver/handlers.go [hunk 3]
```diff
@@ -139,6 +139,13 @@ func tooManyRequests(req *http.Request, w http.ResponseWriter) {
 func RecoverPanics(handler http.Handler) http.Handler {
 	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
 		defer runtime.HandleCrash(func(err interface{}) {
+			if e, ok := err.(error); ok {
```
Comment (krousey) [inline pkg/apiserver/handlers.go]: I was thinking you'd just not wrap the timeout handler with `RecoverPanics`. Instead, wrap the handler you pass to timeout handler.

Comment (xiang90) [inline pkg/apiserver/handlers.go]: I can do that too. but i am not sure if there are other cases that we want to log panics and handle it from timeout handler? Not all panics we throw from timeout handler are expected, right?

Comment (krousey) [inline pkg/apiserver/handlers.go]: I think there are only 2 things that can panic in the current timeout handler: a call to `t.handler.ServerHTTP`, and `tw.timeout`.

Comment (xiang90) [inline pkg/apiserver/handlers.go]: It is up to you I guess. I checked again, now there is no other panic cases than the one we added in this commit. Just feel that handling it in recoverPanics is a little bit better.

File: pkg/apiserver/handlers.go (hunk 2 above)
Comment (lavalamp) [inline pkg/apiserver/handlers.go]: huh, that was not the way I thought it worked. I'll have to look into that.

Comment (xiang90) [inline pkg/apiserver/handlers.go]: @lavalamp OK. If you want a really panic on HTTP sever, I can help you fix it... But I will let you confirm that is what you want first...

File: pkg/apiserver/handlers.go (hunk 3 above)
Comment (xiang90) [inline pkg/apiserver/handlers.go]: > I think there are only 2 things that can panic in the current timeout handler: a call to t.handler.ServerHTTP, and tw.timeout.

You are right. See my last reply (we commented at the same time). Still, I feel the current approach is slightly better. But I have no strong opinion.

File: pkg/apiserver/handlers.go (hunk 2 above)
Comment (lavalamp) [inline pkg/apiserver/handlers.go]: We can worry about that separately, it doesn't need to block this PR :)

**Comment by xiang90** [comment]
@krousey Changed as you suggested.

File: pkg/apiserver/handlers.go (hunk 2 above)
Comment (xiang90) [inline pkg/apiserver/handlers.go]: > We can worry about that separately, it doesn't need to block this PR :)

Ha... That is also my point:https://github.com/kubernetes/kubernetes/pull/29594#discussion_r73968141

I created another issue for this: see https://github.com/kubernetes/kubernetes/issues/30305.

**Comment by xiang90** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by jayunit100** [comment]
@xiang90 

Are we sure this is fixed?  
We are seeing this in openshift clusters which contain the #29001 patch.
Any other possible culprits ?

**Comment by xiang90** [comment]
@jayunit100 can you create a new issue to track it? attach logs if you can. cc me on that issue. thanks.

**Comment by jayunit100** [comment]
oh , i see there is https://github.com/kubernetes/kubernetes/issues/30305 , which already tracking it, right @xiang90 ?
