### PR TITLE
Fix PV allocation on non-English vSphere

### LINKED ISSUE #71997: Provisioning a PVC using a storage class on vSphere fails with "runtime error: index out of range" if the default language on the VMware vCenter Server is not English
**What happened**:
Provsioning a PVC using a storage class with vSphere as the cloud provider failed with error "runtime error: index out of range".

**What you expected to happen**:
The PVC should have been created.

**How to reproduce it (as minimally and precisely as possible)**:
Create a PVC using a storage class with vSphere as the cloud provider and a VMware vCenter Server where the default language is not English.

**Anything else we need to know?**:
K8s in conjunction with vSphere PVC relies on English error messages from the VMware API in order to determine the canonical path for a newly created volume (VMDK file).

The faulting code (v1.11.3, still the same on master) can be found here (starting at line 312): https://github.com/kubernetes/kubernetes/blob/v1.11.3/pkg/cloudprovider/providers/vsphere/vsphere_util.go

```
func getcanonicalVolumePath(ctx context.Context, dc *vclib.Datacenter, volumePath string) (string, error) {
	var folderID string
	var folderExists bool
	canonicalVolumePath := volumePath
	dsPathObj, err := vclib.GetDatastorePathObjFromVMDiskPath(volumePath)
	if err != nil {
		return "", err
	}
	dsPath := strings.Split(strings.TrimSpace(dsPathObj.Path), "/")
	if len(dsPath) <= 1 {
		return canonicalVolumePath, nil
	}
	datastore := dsPathObj.Datastore
	dsFolder := dsPath[0]
	folderNameIDMap, datastoreExists := datastoreFolderIDMap[datastore]
	if datastoreExists {
		folderID, folderExists = folderNameIDMap[dsFolder]
	}
	// Get the datastore folder ID if datastore or folder doesn't exist in datastoreFolderIDMap
	if !datastoreExists || !folderExists {
		if !vclib.IsValidUUID(dsFolder) {
			dummyDiskVolPath := "[" + datastore + "] " + dsFolder + "/" + DummyDiskName
			// Querying a non-existent dummy disk on the datastore folder.
			// It would fail and return an folder ID in the error message.
			_, err := dc.GetVirtualDiskPage83Data(ctx, dummyDiskVolPath)
			if err != nil {
				re := regexp.MustCompile("File (.*?) was not found")
				match := re.FindStringSubmatch(err.Error())
				canonicalVolumePath = match[1]
			}
		}
		diskPath := vclib.GetPathFromVMDiskPath(canonicalVolumePath)
		if diskPath == "" {
			return "", fmt.Errorf("Failed to parse canonicalVolumePath: %s in getcanonicalVolumePath method", canonicalVolumePath)
		}
		folderID = strings.Split(strings.TrimSpace(diskPath), "/")[0]
		setdatastoreFolderIDMap(datastoreFolderIDMap, datastore, dsFolder, folderID)
	}
	canonicalVolumePath = strings.Replace(volumePath, dsFolder, folderID, 1)
	return canonicalVolumePath, nil
}
```

The line "canonicalVolumePath = match[1]" (340) in the above code is the problem because "File (.*?) was not found" (English) never matches for a different language (e.g. German: "Datei [DATASTORE] kubevols/kube-dummyDisk.vmdk wurde nicht gefunden") and a “runtime error: index out of range” oocurs in the "kube-controller-manager".

This causes the already created volume (VMDK file) not to be reported back to the K8s system which in turn will try to recreate it repeatedly in a loop (fails with "Cannot complete the operation because the file or folder [DATASTORE] /kubevols/kubernetes-dynamic-pvc-[UUID] already exists").

Find below the corresponding log excerpt (kube-controller-manager): 

```
I1210 13:40:10.467434       1 pv_controller.go:1394] error saving claim default/testing: Operation cannot be fulfilled on persistentvolumeclaims "testing": the object has been modified; please apply your changes to the latest version and try again
I1210 13:40:12.227023       1 vsphere.go:1108] Starting to create a vSphere volume with volumeOptions: &{CapacityKB:1048576 Tags:map[kubernetes.io/created-for/pvc/namespace:default kubernetes.io/created-for/pvc/name:testing kubernetes.io/created-for/pv/name:pvc-1d2167a0-fc81-11e8-bd11-005056968ce7] Name:kubernetes-dynamic-pvc-1d2167a0-fc81-11e8-bd11-005056968ce7 DiskFormat:thin Datastore: VSANStorageProfileData: StoragePolicyName: StoragePolicyID: SCSIControllerType:}
W1210 13:40:13.081793       1 datacenter.go:214] QueryVirtualDiskUuid failed for diskPath: "[DATASTORE] kubevols/kube-dummyDisk.vmdk". err: ServerFaultCode: Datei [DATASTORE] kubevols/kube-dummyDisk.vmdk wurde nicht gefunden
E1210 13:40:13.097671       1 goroutinemap.go:150] Operation for "provision-default/testing[1d2167a0-fc81-11e8-bd11-005056968ce7]" failed. No retries permitted until 2018-12-10 13:40:13.597467328 +0000 UTC m=+3186.860099451 (durationBeforeRetry 500ms). Error: "recovered from panic \"runtime error: index out of range\". (err=<nil>) Call stack:\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:154\n/usr/local/go/src/runtime/asm_amd64.s:573\n/usr/local/go/src/runtime/panic.go:502\n/usr/local/go/src/runtime/panic.go:28\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere_util.go:340\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:1198\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:1210\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume_util.go:143\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/vsphere_volume/vsphere_volume.go:359\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1481\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/persistentvolume/pv_controller.go:1369\n/workspace/anago-v1.11.3-beta.0.71+a4529464e4629c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:115\n/usr/local/go/src/runtime/asm_amd64.s:2361\n"
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"} 
```
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a

/kind bug

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixes PV allocation on a non-English vSphere installation

**Which issue(s) this PR fixes**:

Fixes #71997

**Special notes for your reviewer**:

I have manually verified that PV allocation still works on an English vSphere. I can not test it on a non-English vsphere as I don't have that at hand, however since the testcase contains the error message @ipointffogl  mentioned in #71997 I'd argue its safe to assume that this will fix the issue.

The whole thing still feels like a rubberduck fix because the proper solution would be to not use API error messages to gather infos. 

/shrug
/area vsphere

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug that caused PV allocation on non-English vSphere installations to fail 
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/priority backlog

i think this might be worth a release note?

**Comment by alvaroaleman** [comment]
@neolit123 Updated and added a release note, PTAL

**Comment by ipointffogl** [comment]
> **What type of PR is this?**
> 
> /kind bug
> 
> **What this PR does / why we need it**:
> 
> Fixes PV allocation on a non-English vSphere installation
> 
> **Which issue(s) this PR fixes**:
> 
> Fixes #71997
> 
> **Special notes for your reviewer**:
> 
> I have manually verified that PV allocation still works on an English vSphere. I can not test it on a non-English vsphere as I don't have that at hand, however since the testcase contains the error message @ipointffogl mentioned in #71997 I'd argue its safe to assume that this will fix the issue.
> 
> The whole thing still feels like a rubberduck fix because the proper solution would be to not use API error messages to gather infos.
> 
> /shrug
> /area vsphere
> 
> **Does this PR introduce a user-facing change?**:
> 
> ```
> Fixed a bug that caused PV allocation on noin-English vSphere installations to fail 
> ```

Can be tested by setting the environment variable "GOVMOMI_LOCALE" for the to kube controller to e.g. "de_DE".

**Comment by alvaroaleman** [comment]
Hey @divyenpatel or @dougm could one of you have a look?

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go [hunk 1]
```diff
@@ -326,8 +328,10 @@ func getcanonicalVolumePath(ctx context.Context, dc *vclib.Datacenter, volumePat
 			// It would fail and return an folder ID in the error message.
 			_, err := dc.GetVirtualDiskPage83Data(ctx, dummyDiskVolPath)
 			if err != nil {
-				re := regexp.MustCompile("File (.*?) was not found")
```
Comment (dougm) [inline pkg/cloudprovider/providers/vsphere/vsphere_util.go]: Rather than match the error message at all, we can use the fault type like so:
```go
// fileNotFound returns the value of File if err is a FileNotFound soap fault, an empty string otherwise.
func fileNotFound(err error) string {
	if soap.IsSoapFault(err) {
		fault := soap.ToSoapFault(err)
		if f, ok := fault.VimFault().(types.FileNotFound); ok {
			return f.File
		}
	}
	return ""
}
```

Comment (dougm) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: Note that this can be tested against vcsim, with the error returned here for example: https://github.com/kubernetes/kubernetes/blob/b66e332d3c19ce78e00dd7c904fa29e8f6784ba0/pkg/cloudprovider/providers/vsphere/vclib/datacenter_test.go#L138-L141

**Comment by alvaroaleman** [comment]
@dougm Updated, also did a quick smoke test again trying to allocate a PV when running this with `GOVMOMI_LOCALE=de_DE`, worked fine :+1:

**Review by dougm — COMMENTED** [review]
Nice @alvaroaleman 
/lgtm

**Comment by alvaroaleman** [comment]
@dougm Can you also `/approve` or do you want me to find someone else for that?
