### PR TITLE
fix updatePod() of RS and RC controllers

### LINKED ISSUE #27405: Replication Controller doesn't notice changes in pods labels
To reproduce, I create a rc, wait for its pods to be created, then modify the labels of the pod so that it doesn't match the rc's selector anymore. RC should create another pod, but it doesn't try to.

The problem is this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L357). It should enqueue the old rc if old rc exists.

I have a local fix for the rc manager. I'll check the replicaset controller and add a test then send the PR.

cc @bprashanth

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix updatePod of replication controller manager and replica set controller to handle pod label updates that match no RC or RS.

Fix #27405

### CODE REVIEW

File: pkg/controller/replicaset/replica_set.go [hunk 1]
```diff
@@ -327,11 +327,6 @@ func (rsc *ReplicaSetController) updatePod(old, cur interface{}) {
 	curPod := cur.(*api.Pod)
 	oldPod := old.(*api.Pod)
 	glog.V(4).Infof("Pod %s updated %+v -> %+v.", curPod.Name, oldPod, curPod)
-	rs := rsc.getPodReplicaSet(curPod)
-	if rs == nil {
-		return
-	}
-
 	if curPod.DeletionTimestamp != nil {
```
Comment (bprashanth) [inline pkg/controller/replicaset/replica_set.go]: If deletion timestamp is set on the cur pod and old pod has a different rc (i.e we got a single update with deletion timestamp and label change -- this can happen if both updates hit during a relist), we should invoke deletePod with the old one too. It's safe to do this becase deletion timestamp can never be unset.

Comment (caesarxuchao) [inline pkg/controller/replicaset/replica_set.go]: Yeah, this sounds good. I've updated the code.

File: pkg/controller/replicaset/replica_set.go [hunk 2]
```diff
@@ -327,22 +327,22 @@ func (rsc *ReplicaSetController) updatePod(old, cur interface{}) {
...
 		// when a pod is deleted gracefully it's deletion timestamp is first modified to reflect a grace period,
 		// and after such time has passed, the kubelet actually deletes it from the store. We receive an update
 		// for modification of the deletion timestamp and expect an rs to create more replicas asap, not wait
 		// until the kubelet actually deletes the pod. This is different from the Phase of a pod changing, because
 		// an rs never initiates a phase change, and so is never asleep waiting for the same.
 		rsc.deletePod(curPod)
+		if !reflect.DeepEqual(curPod.Labels, oldPod.Labels) {
```
Comment (caesarxuchao) [inline pkg/controller/replicaset/replica_set.go]: Added these lines to address the comment.

File: pkg/controller/replication/replication_controller.go [hunk 3]
```diff
@@ -353,22 +353,24 @@ func (rm *ReplicationManager) updatePod(old, cur interface{}) {
 		return
 	}
 	curPod := cur.(*api.Pod)
-	rc := rm.getPodController(curPod)
-	if rc == nil {
-		return
-	}
 	oldPod := old.(*api.Pod)
-
+	glog.V(4).Infof("Pod %s updated %+v -> %+v.", curPod.Name, oldPod, curPod)
```
Comment (bprashanth) [inline pkg/controller/replication/replication_controller.go]: %+v on a pod is really chatty, can we log something more specific? if we're only interested in the labels, maybe that's enough?

Comment (caesarxuchao) [inline pkg/controller/replication/replication_controller.go]: Copied from the RS code. I think the entire ObjectMeta would be useful.

File: pkg/controller/replicaset/replica_set.go (hunk 2 above)
Comment (bprashanth) [inline pkg/controller/replicaset/replica_set.go]: nit: please extract the deepequal into a local var with a name like labelsChanged since we're doing it twice, and add a comment about why it's safe to just invoke deletePod with the oldPod without checking delete timestamp (i.e we can never have a curPod without timestmap and oldPod with).

File: pkg/controller/replication/replication_controller.go [hunk 4]
```diff
@@ -353,22 +353,24 @@ func (rm *ReplicationManager) updatePod(old, cur interface{}) {
 		return
 	}
 	curPod := cur.(*api.Pod)
-	rc := rm.getPodController(curPod)
-	if rc == nil {
-		return
-	}
 	oldPod := old.(*api.Pod)
-
+	glog.V(6).Infof("Pod %s updated, objectMeta %+v -> %+v.", curPod.Name, oldPod.ObjectMeta, curPod.ObjectMeta)
```
Comment (bprashanth) [inline pkg/controller/replication/replication_controller.go]: V(6) is useless IMO, we need V(4) for it to show up in test logs. I think V(4) objectmeta is fine, the really verbose part are container statuses.

File: pkg/controller/replicaset/replica_set.go (hunk 2 above)
Comment (caesarxuchao) [inline pkg/controller/replicaset/replica_set.go]: Done.

File: pkg/controller/replication/replication_controller.go (hunk 4 above)
Comment (caesarxuchao) [inline pkg/controller/replication/replication_controller.go]: Done.

**Comment by bprashanth** [comment]
Thanks, LGTM

**Comment by bprashanth** [comment]
Both your failures are https://github.com/kubernetes/kubernetes/issues/27451 but I don't think triggering a rerun ensures that we won't hit it

**Comment by goltermann** [comment]
+priority/P0 label, this fixes an issue labeled P0

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this, issue #27451

**Comment by caesarxuchao** [comment]
@k8s-bot node e2e test this, issue #27451
