### PR TITLE
DualStack: basic dual-stack node IP handling

### LINKED ISSUE #89816: unexpected podIP and hostIP in pod
**What happened**:

Unexpected podIP and hostIP in pod, just like
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  ......
status:
  ......
  hostIP: <nil>
  podIP: <nil>
  ......
```

**What you expected to happen**:

This is a host-networking pod, podIP and hostIP in status should be node's internal IP.

**How to reproduce it (as minimally and precisely as possible)**:

Set kubelet's cloud provider to `external`, then set some invalid addresses to node.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.14

### LINKED ISSUE #91940: DualStack: nodes and hostNetwork pods have only a single IP
**What happened**:

I want to deploy k8s with IPV4/IPv6 dual stack.
But node internal IP always only one either IPV4 or IPV6.
Pod IP can auto assigned IPV4,IPV6 calico,  IPv6 Service also work.
But NodeType only listener at IPV4, not IPV6.

```bash
                "status": {
                "addresses": [
                    {
                        "address": "10.126.20.162",
                        "type": "InternalIP"
                    },
                    {
                        "address": "wxdlong",
                        "type": "Hostname"
                    }
                ],
```

**What you expected to happen**:

As https://kubernetes.io/docs/tasks/network/validate-dual-stack/  said.

```bash
kubectl get nodes k8s-linuxpool1-34450317-0 -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'
Hostname: k8s-linuxpool1-34450317-0
InternalIP: 10.240.0.5
InternalIP: 2001:1234:5678:9abc::5

```

**How to reproduce it (as minimally and precisely as possible)**:
the init config 

```yaml

apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.126.20.162"
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  kubeletExtraArgs:
    node-ip: "10.126.20.162,2001:1b74:88:9400::62:62"
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):  v1.17.4

```bash
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```bash
# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.6:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.6"

```
- Kernel (e.g. `uname -a`):

```bash
# uname -a
Linux wxdlong 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```bash
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:01:11Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Network plugin and version (if this is a network-related bug):
  calico
- Others:

  May be my init config is not correct, Any one can give an full example for IPV4,IPV6 dual stack. Thanks

### PR DESCRIPTION
**Pull request by danwinship**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Makes two related improvements to kubelet node IP handling:

- On bare metal (ie, when there is no `--cloud-provider`), the administrator can now pass a comma-separated pair of IPs via `--node-ip` to manually configure dual-stack `node.status.addresses`. No other scenarios (eg, cloud provider, bare-metal autodetection) are changed.
- On nodes with dual-stack `node.status.addresses` (regardless of how they got them), hostNetwork pods will now have dual-stack `pod.status.podIPs`, allowing the pod to be the target of either a single-stack IPv4 or single-stack IPv6 Service (or, once #91824 merges, a dual-stack Service).

There is ongoing discussion about dual-stack node IPs in https://github.com/kubernetes/enhancements/pull/1665, and it probably won't be resolved in time for Enhancement Freeze. However, it seems like there has always been consensus that (a) regardless of what else is possible, it ought to be possible to explicitly specify a dual-stack pair of IPs on bare-metal nodes, (b) regardless of how a node ends up with dual-stack IPs, if it has dual-stack IPs, then that should be reflected in hostNetwork pods. So this PR implements those two things. Additional functionality will presumably come later.

**Which issue(s) this PR fixes**:
Fixes #91940
Fixes #89816 (invalid node IP set by cloud provider causes `"<nil>"` podIP on hostnetwork pod)

**Special notes for your reviewer**:
Currently built on top of #94474 (the first two commits). That can still be reviewed separately, or it can be reviewed as part of this.

Does not conflict with #91824 (dual-stack Services), as this PR only touches kubelet-related things, and that PR does not touch anything kubelet related except a small fix to kubenet (which this PR doesn't touch).

**Does this PR introduce a user-facing change?**:
```release-note
In dual-stack bare-metal clusters, you can now pass dual-stack IPs to `kubelet --node-ip`.
eg: `kubelet --node-ip 10.1.0.5,fd01::0005`. This is not yet supported for non-bare-metal
clusters.

In dual-stack clusters where nodes have dual-stack addresses, hostNetwork pods
will now get dual-stack PodIPs.
```

/sig network
/sig node
/priority important-soon
/assign @thockin

### CODE REVIEW

**Comment by dcbw** [comment]
@danwinship verify failed:

```
Verifying verify-gofmt.sh

+++ Running case: verify.gofmt 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-gofmt.sh"
diff -u ./pkg/util/node/node_test.go.orig ./pkg/util/node/node_test.go
--- ./pkg/util/node/node_test.go.orig	2020-10-01 17:24:02.206547690 +0000
+++ ./pkg/util/node/node_test.go	2020-10-01 17:24:02.206547690 +0000
@@ -107,14 +107,14 @@
 			expectIPs: nil,
 		},
 		{
-			name:      "no InternalIP/ExternalIP",
+			name: "no InternalIP/ExternalIP",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeHostName, Address: "example.com"},
 			},
 			expectIPs: nil,
 		},
 		{
-			name:      "IPv4-only, simple",
+			name: "IPv4-only, simple",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "1.2.3.4"},
 				{Type: v1.NodeExternalIP, Address: "4.3.2.1"},
@@ -123,7 +123,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4")},
 		},
 		{
-			name:      "IPv4-only, external-first",
+			name: "IPv4-only, external-first",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeExternalIP, Address: "4.3.2.1"},
 				{Type: v1.NodeExternalIP, Address: "4.3.2.2"},
@@ -132,7 +132,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4")},
 		},
 		{
-			name:      "IPv4-only, no internal",
+			name: "IPv4-only, no internal",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeExternalIP, Address: "4.3.2.1"},
 				{Type: v1.NodeExternalIP, Address: "4.3.2.2"},
@@ -140,7 +140,7 @@
 			expectIPs: []net.IP{net.ParseIP("4.3.2.1")},
 		},
 		{
-			name:      "dual-stack node, single-stack cluster",
+			name: "dual-stack node, single-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "1.2.3.4"},
 				{Type: v1.NodeExternalIP, Address: "4.3.2.1"},
@@ -151,7 +151,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4")},
 		},
 		{
-			name:      "dual-stack node, dual-stack cluster",
+			name: "dual-stack node, dual-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "1.2.3.4"},
 				{Type: v1.NodeExternalIP, Address: "4.3.2.1"},
@@ -163,7 +163,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4"), net.ParseIP("a:b::c:d")},
 		},
 		{
-			name:      "dual-stack node, different order, single-stack cluster",
+			name: "dual-stack node, different order, single-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "1.2.3.4"},
 				{Type: v1.NodeInternalIP, Address: "a:b::c:d"},
@@ -174,7 +174,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4")},
 		},
 		{
-			name:      "dual-stack node, different order, dual-stack cluster",
+			name: "dual-stack node, different order, dual-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "1.2.3.4"},
 				{Type: v1.NodeInternalIP, Address: "a:b::c:d"},
@@ -186,7 +186,7 @@
 			expectIPs: []net.IP{net.ParseIP("1.2.3.4"), net.ParseIP("a:b::c:d")},
 		},
 		{
-			name:      "dual-stack node, IPv6-first, no internal IPv4, single-stack cluster",
+			name: "dual-stack node, IPv6-first, no internal IPv4, single-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "a:b::c:d"},
 				{Type: v1.NodeExternalIP, Address: "d:c::b:a"},
@@ -196,7 +196,7 @@
 			expectIPs: []net.IP{net.ParseIP("a:b::c:d")},
 		},
 		{
-			name:      "dual-stack node, IPv6-first, no internal IPv4, dual-stack cluster",
+			name: "dual-stack node, IPv6-first, no internal IPv4, dual-stack cluster",
 			addresses: []v1.NodeAddress{
 				{Type: v1.NodeInternalIP, Address: "a:b::c:d"},
 				{Type: v1.NodeExternalIP, Address: "d:c::b:a"},
@@ -209,7 +209,7 @@
 	}
 
 	for _, tc := range testcases {
-		t.Run(tc.name, func (t *testing.T) {
+		t.Run(tc.name, func(t *testing.T) {
 			defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.IPv6DualStack, tc.dualStack)()
 			node := &v1.Node{
 				Status: v1.NodeStatus{Addresses: tc.addresses},

Run ./hack/update-gofmt.sh
+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-gofmt.sh	16s
Verifying verify-golint.sh

+++ Running case: verify.golint 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-golint.sh"
installing golint
go: downloading golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: downloading golang.org/x/tools v0.0.0-20200710042808-f1c4188a97a1
Errors from golint:
pkg/kubelet/volume_host.go:237:9: if block ends with a return statement, so drop this else and outdent its block

Please review the above warnings. You can test via "golint" and commit the result.
If the above warnings do not make sense, you can exempt this package from golint
checking by adding it to hack/.golint_failures (if your reviewer is okay with it).

+++ exit code: 1
+++ error: 1
[0;31mFAILED[0m   verify-golint.sh	136s
```

File: pkg/kubelet/kubelet_getters.go [hunk 1]
```diff
@@ -262,23 +262,23 @@ func (kl *Kubelet) GetPodCgroupRoot() string {
 	return kl.containerManager.GetPodCgroupRoot()
 }
 
-// GetHostIP returns host IP or nil in case of error.
-func (kl *Kubelet) GetHostIP() (net.IP, error) {
+// GetHostIPs returns host IPs or nil in case of error.
+func (kl *Kubelet) GetHostIPs() ([]net.IP, error) {
```
Comment (andrewsykim) [inline pkg/kubelet/kubelet_getters.go:266]: Since callers of this always extract the IP at index 0, would it be better to keep this as GetHostIP and and return index 0 from the returned list at GetNodeHostIPs?

File: pkg/kubelet/nodestatus/setters_test.go [hunk 2]
```diff
@@ -443,6 +443,74 @@ func TestNodeAddress(t *testing.T) {
 	}
 }
 
+// We can't test failure or autodetection cases here because the relevant code isn't mockable
+func TestNodeAddress_BareMetal(t *testing.T) {
```
Comment (andrewsykim) [inline pkg/kubelet/nodestatus/setters_test.go:447]: nit: `TestNodeAddress_WithoutCloudProvider` might be a bit more accurate naming for this test since bare metal can technically have a "cloud provider" enabled

File: pkg/kubelet/volume_host.go [hunk 3]
```diff
@@ -231,7 +231,12 @@ func (kvh *kubeletVolumeHost) GetHostName() string {
 }
 
 func (kvh *kubeletVolumeHost) GetHostIP() (net.IP, error) {
-	return kvh.kubelet.GetHostIP()
+	hostIPs, err := kvh.kubelet.GetHostIPs()
+	if err != nil {
+		return nil, err
+	} else {
```
Comment (andrewsykim) [inline pkg/kubelet/volume_host.go:237]: I think this else is redundant?

File: pkg/kubelet/kubelet_getters.go (hunk 1 above)
Comment (danwinship) [reply pkg/kubelet/kubelet_getters.go:266]: I guess there's only one caller... I don't know, it seemed more appropriate to me to have the function return all the relevant information, and let the caller discard the secondary IP if it doesn't need it...

Comment (andrewsykim) [reply pkg/kubelet/kubelet_getters.go:266]: Okay good point, missed that there is only 1 caller.

File: cmd/kubelet/app/options/options.go [hunk 4]
```diff
@@ -325,7 +325,7 @@ func (f *KubeletFlags) AddFlags(mainfs *pflag.FlagSet) {
 
 	fs.StringVar(&f.HostnameOverride, "hostname-override", f.HostnameOverride, "If non-empty, will use this string as identification instead of the actual hostname. If --cloud-provider is set, the cloud provider determines the name of the node (consult cloud provider documentation to determine if and how the hostname is used).")
 
-	fs.StringVar(&f.NodeIP, "node-ip", f.NodeIP, "IP address of the node. If set, kubelet will use this IP address for the node. If unset, kubelet will use the node's default IPv4 address, if any, or its default IPv6 address if it has no IPv4 addresses. You can pass '::' to make it prefer the default IPv6 address rather than the default IPv4 address.")
+	fs.StringVar(&f.NodeIP, "node-ip", f.NodeIP, "IP address (or comma-separated dual-stack IP addresses) of the node. If unset, kubelet will use the node's default IPv4 address, if any, or its default IPv6 address if it has no IPv4 addresses. You can pass '::' to make it prefer the default IPv6 address rather than the default IPv4 address.")
```
Comment (khenidak) [inline cmd/kubelet/app/options/options.go:328]: the `if set` part of the doc has been removed. Is this intentional?

File: pkg/kubelet/kubelet_network_linux.go [hunk 5]
```diff
@@ -23,15 +23,39 @@ import (
...
-		[]utiliptables.Table{utiliptables.TableMangle, utiliptables.TableNAT, utiliptables.TableFilter},
-		kl.syncNetworkUtil, 1*time.Minute, wait.NeverStop)
+	exec := utilexec.New()
+
+	// At this point in startup we don't know the actual node IPs, so we configure dual stack iptables
+	// rules if the node _might_ be dual-stack, and single-stack based on requested nodeIPs[0] otherwise.
+	maybeDualStack := utilfeature.DefaultFeatureGate.Enabled(features.IPv6DualStack)
+	ipv6Primary := kl.nodeIPs != nil && utilnet.IsIPv6(kl.nodeIPs[0])
+
+	var iptClients []utiliptables.Interface
```
Comment (khenidak) [inline pkg/kubelet/kubelet_network_linux.go:42]: this `iptCllient` is the same as one defined on Kubelet `kl.iptClient`? did we remove it from Kubelet as we now pass it around?

File: pkg/util/node/node.go [hunk 6]
```diff
@@ -90,27 +93,59 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+// (for nodes that actually have dual-stack IPs). Among other things, the IPs returned
+// from this function are used as the `.status.PodIPs` values for host-network pods on the
+// node, and the first IP is used as the `.status.HostIP` for all pods on the node.
+func GetNodeHostIPs(node *v1.Node) ([]net.IP, error) {
+	// Re-sort the addresses with InternalIPs first and then ExternalIPs
+	allIPs := make([]net.IP, 0, len(node.Status.Addresses))
+	for _, addr := range node.Status.Addresses {
+		if addr.Type == v1.NodeInternalIP {
+			ip := net.ParseIP(addr.Address)
+			if ip != nil {
```
Comment (khenidak) [inline pkg/util/node/node.go:107]: shouldn't we at least log this?

File: pkg/util/node/node.go [hunk 7]
```diff
@@ -90,27 +93,59 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+				allIPs = append(allIPs, ip)
+			}
+		}
+	}
+	for _, addr := range node.Status.Addresses {
+		if addr.Type == v1.NodeExternalIP {
+			ip := net.ParseIP(addr.Address)
+			if ip != nil {
```
Comment (khenidak) [inline pkg/util/node/node.go:115]: similar to previous comment re logging failures

File: pkg/util/node/node.go [hunk 8]
```diff
@@ -90,27 +93,59 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+			}
+		}
 	}
-	if addresses, ok := addressMap[v1.NodeInternalIP]; ok {
-		return net.ParseIP(addresses[0].Address), nil
+	if len(allIPs) == 0 {
+		return nil, fmt.Errorf("host IP unknown; known addresses: %v", node.Status.Addresses)
+	}
+
+	nodeIPs := []net.IP{allIPs[0]}
```
Comment (khenidak) [inline pkg/util/node/node.go:124]: Order is assumed here. Which is fine if we know that the node.Status.Addresses is always ordered correctly. is this confirmed?

File: pkg/util/node/node.go [hunk 9]
```diff
@@ -90,27 +93,59 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+	allIPs := make([]net.IP, 0, len(node.Status.Addresses))
+	for _, addr := range node.Status.Addresses {
+		if addr.Type == v1.NodeInternalIP {
+			ip := net.ParseIP(addr.Address)
+			if ip != nil {
+				allIPs = append(allIPs, ip)
+			}
+		}
+	}
+	for _, addr := range node.Status.Addresses {
```
Comment (khenidak) [inline pkg/util/node/node.go:112]: why two loops?

File: pkg/util/node/node.go [hunk 10]
```diff
@@ -90,27 +93,59 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+}
+
+// GetNodeHostIP returns the provided node's "primary" IP; see GetNodeHostIPs for more details
+func GetNodeHostIP(node *v1.Node) (net.IP, error) {
+	ips, err := GetNodeHostIPs(node)
+	if err != nil {
+		return nil, err
 	}
-	return nil, fmt.Errorf("host IP unknown; known addresses: %v", addresses)
+	return ips[0], nil
```
Comment (khenidak) [inline pkg/util/node/node.go:143]: I understand that `GetNodeHostIPs(..)` will return error in case of len()==0. But a comment here will make it clearer.

File: pkg/util/node/node_test.go [hunk 11]
```diff
@@ -89,6 +94,147 @@ func TestGetPreferredAddress(t *testing.T) {
...
+			nodeIP, err2 := GetNodeHostIP(node)
+
+			if (err == nil && err2 != nil) || (err != nil && err2 == nil) {
+				t.Errorf("GetNodeHostIPs() returned error=%q but GetNodeHostIP() returned error=%q", err, err2)
+			}
+			if err != nil {
+				if tc.expectIPs != nil {
+					t.Errorf("expected %v, got error (%v)", tc.expectIPs, err)
+				}
+			} else if tc.expectIPs == nil {
```
Comment (khenidak) [inline pkg/util/node/node_test.go:227]: that does not test that func returned error. Just checks for len of slice.

File: pkg/util/node/BUILD [hunk 12]
```diff
@@ -11,15 +11,18 @@ go_library(
     srcs = ["node.go"],
     importpath = "k8s.io/kubernetes/pkg/util/node",
     deps = [
+        "//pkg/features:go_default_library",
```
Comment (khenidak) [inline pkg/util/node/BUILD:14]: low pri - Would be great if we move all the generated stuff into a separate commit, making it easier to skip in review

File: pkg/kubelet/nodestatus/setters.go [hunk 13]
```diff
@@ -57,25 +57,46 @@ const (
...
+	if len(nodeIPs) > 0 {
+		nodeIP = nodeIPs[0]
+	}
 	preferIPv4 := nodeIP == nil || nodeIP.To4() != nil
 	isPreferredIPFamily := func(ip net.IP) bool { return (ip.To4() != nil) == preferIPv4 }
 	nodeIPSpecified := nodeIP != nil && !nodeIP.IsUnspecified()
 
+	if len(nodeIPs) > 1 {
+		if externalCloudProvider || cloud != nil {
+			klog.Warningf("Cloud providers do not support multiple --node-ip values; ignoring second value")
```
Comment (khenidak) [inline pkg/kubelet/nodestatus/setters.go:78]: that is not entirely true. That means that cloud hosted clusters will always have host net with single IP? 

can we double check @andrewsykim would know more.

File: pkg/kubelet/nodestatus/setters.go [hunk 14]
```diff
@@ -57,25 +57,46 @@ const (
...
+		} else if nodeIP.IsUnspecified() || secondaryNodeIP.IsUnspecified() {
+			klog.Warningf("Multi-valued --node-ip cannot include 0.0.0.0 or ::; ignoring second value")
```
Comment (khenidak) [inline pkg/kubelet/nodestatus/setters.go:80]: this needs to move to option validation in option file. if we are to resolve the cloud comment earlier then we need to leave this validation here.

File: pkg/kubelet/kubelet_pods.go [hunk 15]
```diff
@@ -1531,14 +1531,17 @@ func (kl *Kubelet) generateAPIPodStatus(pod *v1.Pod, podStatus *kubecontainer.Po
...
-			klog.V(4).Infof("Cannot get host IP: %v", err)
+			klog.V(4).Infof("Cannot get host IPs: %v", err)
 		} else {
-			s.HostIP = hostIP.String()
+			s.HostIP = hostIPs[0].String()
 			if kubecontainer.IsHostNetworkPod(pod) && s.PodIP == "" {
-				s.PodIP = hostIP.String()
+				s.PodIP = hostIPs[0].String()
 				s.PodIPs = []v1.PodIP{{IP: s.PodIP}}
+				if len(hostIPs) == 2 {
```
Comment (khenidak) [inline pkg/kubelet/kubelet_pods.go:1542]: can we add a test for this?

**Review by khenidak — CHANGES_REQUESTED** [review]
few issues. The most concerning is the order of IPs dependancy.

File: cmd/kubelet/app/options/options.go (hunk 4 above)
Comment (danwinship) [reply cmd/kubelet/app/options/options.go:328]: It seemed like it would be awkward to rewrite the sentence in a way that reflected the fact that the value could be one or two addresses, and it seemed kind of obvious and unnecessary to state anyway... ("kubelet --node-ip tells kubelet to set the node IP")

File: pkg/kubelet/kubelet_network_linux.go (hunk 5 above)
Comment (danwinship) [reply pkg/kubelet/kubelet_network_linux.go:42]: Yes (https://github.com/kubernetes/kubernetes/pull/95239/commits/8a264e3a2d548a4e923c35b718c0a142050648e7#diff-bf28da68f62a8df6e99e447c4351122dL822). Nothing else in kubelet uses it, and given that the easiest way to make this code dual-stack was to call `syncNetworkUtil` twice with different clients, there was no longer any good reason to store the client(s) in the kubelet.

File: pkg/util/node/node.go (hunk 6 above)
Comment (danwinship) [reply pkg/util/node/node.go:107]: Hm... I don't like logging messages from "get" methods. Who knows how often it might be called.

This is mostly a "can't happen". (It can only happen if you're using a broken cloud provider. But apparently someone was, because there's a bug report.) I guess kubelet should log an error if it observes the cloud provider setting an invalid IP from the node-address-setting loop.

File: pkg/util/node/node.go (hunk 8 above)
Comment (danwinship) [reply pkg/util/node/node.go:124]: This function is what defines what "ordered correctly" is for node.Status.Addresses. Whatever IP the cloud provider returns first is the one that kubelet will use.

Note that the first IP returned here is the same as was traditionally returned by the old single-value `GetNodeHostIP()`; "the first InternalIP, unless there are no InternalIPs, in which case the first ExternalIP". I just changed the way it figures that out because with dual-stack we need to do that logic twice so it's easier to just sort the IPs correctly beforehand.

File: pkg/util/node/node.go (hunk 9 above)
Comment (danwinship) [reply pkg/util/node/node.go:112]: The first loop gets the InternalIPs, the second gets the ExternalIPs.

File: pkg/kubelet/nodestatus/setters.go (hunk 13 above)
Comment (danwinship) [reply pkg/kubelet/nodestatus/setters.go:78]: I worded this badly. It's not supposed to be saying anything about what the cloud provider can or can't do, it's just saying that _kubelet_ does not allow you to pass multiple `--node-ip` values if you are using a cloud provider, at this time.

(I assume we will eventually allow dual `--node-ip` with clouds as well, but this is more complicated because, among other things, the behavior of `--node-ip` is currently inconsistent between internal cloud providers and external cloud providers. This is one of the things discussed in KEP-1664 that isn't resolved yet.)

(So, the behavior both before and after this PR is that a cloud provider can return dual-stack node addresses, and kubelet will allow you to override _one_ of them, but not both.)

File: pkg/kubelet/nodestatus/setters_test.go [hunk 16]
```diff
@@ -443,6 +443,74 @@ func TestNodeAddress(t *testing.T) {
...
+				nodeAddressesFunc)
+
+			// call setter on existing node
+			err := setter(existingNode)
+			if err != nil {
+				t.Fatalf("unexpected error: %v", err)
+			}
+
+			// Sort both sets for consistent equality
+			sortNodeAddresses(testCase.expectedAddresses)
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/kubelet/nodestatus/setters_test.go:505]: huh... this was just copied from the existing `TestNodeAddress`...

ugh, the existing test is broken. There are a mix of "make sure addresses X gets filtered out of the results" tests and "make sure address X gets moved to the front of the list" tests, but the latter set are all no-ops. :facepalm:

File: pkg/util/node/node_test.go (hunk 11 above)
Comment (danwinship) [reply pkg/util/node/node_test.go:227]: The test case knows that GetNodeHostIPs returns an error XOR a non-empty slice, so the testcase struct does not have separate `expectIPs` and `expectError` fields. At this point we know that `err` is `nil` and `tc.expectIPs` is empty, so that means we expected an error and didn't get one, as the error message says.

So I think this is correct. If you want something changed please clarify what part of it

File: pkg/kubelet/kubelet_pods.go (hunk 15 above)
Comment (danwinship) [reply pkg/kubelet/kubelet_pods.go:1542]: done

File: pkg/kubelet/nodestatus/setters_test.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/kubelet/nodestatus/setters_test.go]: fixed

File: pkg/kubelet/kubelet.go [hunk 17]
```diff
@@ -462,7 +463,19 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
 		}
 	}
 	httpClient := &http.Client{}
-	parsedNodeIP := net.ParseIP(nodeIP)
+
+	var nodeIPs []net.IP
+	for _, nodeIP := range strings.Split(nodeIP, ",") {
+		parsedNodeIP := net.ParseIP(strings.TrimSpace(nodeIP))
+		if parsedNodeIP == nil {
+			klog.Warningf("Could not parse --node-ip value %q; ignoring", nodeIP)
```
Comment (thockin) [inline pkg/kubelet/kubelet.go:471]: Is it right to ignore this with no other signals?  I am not sure what is best but this seems likely to get lost in the noise

File: pkg/kubelet/kubelet.go [hunk 18]
```diff
@@ -462,7 +463,19 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
...
+		} else {
+			nodeIPs = append(nodeIPs, parsedNodeIP)
+		}
+	}
+	if len(nodeIPs) > 2 || (len(nodeIPs) == 2 && utilnet.IsIPv6(nodeIPs[0]) == utilnet.IsIPv6(nodeIPs[1])) {
```
Comment (thockin) [inline pkg/kubelet/kubelet.go:476]: Does this need to be gated?

File: pkg/kubelet/kubelet_getters.go [hunk 19]
```diff
@@ -262,23 +262,23 @@ func (kl *Kubelet) GetPodCgroupRoot() string {
...
 	node, err := kl.GetNode()
 	if err != nil {
 		return nil, fmt.Errorf("cannot get node: %v", err)
 	}
-	return utilnode.GetNodeHostIP(node)
+	return utilnode.GetNodeHostIPs(node)
```
Comment (thockin) [inline pkg/kubelet/kubelet_getters.go:271]: DO we now need to pluralize pod.status.hostIP ?

**Review by thockin — COMMENTED** [review]
I am approving, @khenidak owns the LGTM

/approve

File: pkg/kubelet/kubelet_getters.go (hunk 19 above)
Comment (aojea) [reply pkg/kubelet/kubelet_getters.go:271]: there is an open issue about that https://github.com/kubernetes/kubernetes/issues/85443
It seems so

Comment (danwinship) [reply pkg/kubelet/kubelet_getters.go:271]: I mentioned that in the KEP; it's not a critical fix, since for the most part, every client in a dual-stack cluster ought to be able to reach either node IP, so having easy API access to one of them but not the other should not be fatal. But probably should be fixed for beta.

File: pkg/kubelet/kubelet.go (hunk 17 above)
Comment (danwinship) [reply pkg/kubelet/kubelet.go:471]: Well, currently we ignore invalid `--node-ip` _without_ logging a warning, so this is at least an improvement...

Assuming we add `--node-ips` or `--node-ip-mode` in KEP-1664, we can make errors fatal there...

File: pkg/kubelet/kubelet.go (hunk 18 above)
Comment (danwinship) [reply pkg/kubelet/kubelet.go:476]: Define "need"...

There is no chance that a user is going to be accidentally injured by us not gating it, since they can only end up with two IPs here if they explicitly passed two IPs on the command line.

Note that the eventual side effect of setting dual-stack `podIPs` _is_ gated.

**Comment by khenidak** [comment]
One point re validation. But can be added later.

/LGTM

**Comment by danwinship** [comment]
@khenidak ah, I was in the middle of updating when you lgtm'ed; I addressed your comment about where node-ip validation happens. See if this is better.

/hold
need to rebase into openshift to test

**Comment by khenidak** [comment]
@danwinship great thank you. i will keep an eye until the hold is removed.

**Comment by danwinship** [comment]
/hold cancel
(had to repush to fix bazel BUILD files)

File: cmd/kubelet/app/options/options.go (hunk 4 above)
Comment (aojea) [reply cmd/kubelet/app/options/options.go:328]: so, in order to have a kubelet with dual stack addresses you always have to pass always the node-ips as a parameter.
This is a pita for installation automation :/ but since you did an extensive research on this topic I imagine that is not easy to support/add it

Comment (aojea) [reply cmd/kubelet/app/options/options.go:328]: ic, RTFM thing , it is in the KEP

File: pkg/kubelet/network/dns/dns.go [hunk 20]
```diff
@@ -373,11 +374,15 @@ func (c *Configurer) GetPodDNS(pod *v1.Pod) (*runtimeapi.DNSConfig, error) {
...
-			switch {
-			case c.nodeIP == nil || c.nodeIP.To4() != nil:
-				dnsConfig.Servers = []string{"127.0.0.1"}
-			case c.nodeIP.To16() != nil:
-				dnsConfig.Servers = []string{"::1"}
+			for _, nodeIP := range c.nodeIPs {
+				if utilnet.IsIPv6(nodeIP) {
+					dnsConfig.Servers = append(dnsConfig.Servers, "::1")
+				} else {
+					dnsConfig.Servers = append(dnsConfig.Servers, "127.0.0.1")
```
Comment (aojea) [inline pkg/kubelet/network/dns/dns.go:381]: I have to confess that this part scares me, how this is going to behave with both nameservers.
maybe just adding `localhost` and let the host handle it?

**Comment by aojea** [comment]
/hold
need to check something, sorry

File: pkg/util/node/node.go [hunk 21]
```diff
@@ -90,27 +93,60 @@ func GetPreferredNodeAddress(node *v1.Node, preferredAddressTypes []v1.NodeAddre
...
+	// GetNodeHostIPs always returns at least one IP if it didn't return an error
+	return ips[0], nil
 }
 
-// GetNodeIP returns the ip of node with the provided hostname
-// If required, wait for the node to be defined.
-func GetNodeIP(client clientset.Interface, hostname string) net.IP {
+// GetNodeIP returns an IP (as with GetNodeHostIP) for the node with the provided name.
+// If required, it will wait for the node to be created.
+func GetNodeIP(client clientset.Interface, name string) net.IP {
```
Comment (aojea) [inline pkg/util/node/node.go:149]: ok, I've found it, this has a dependency in kube-proxy but does not break it
https://github.com/kubernetes/kubernetes/blob/aa1f91286838d373a6d9217ad9f4fe0647a1c859/cmd/kube-proxy/app/server_others.go#L136-L142

possible something to follow up or do you want to fix it here?
anyway, unhold as you wish, I just was worried about this dependency in kube-proxy

**Comment by khenidak** [comment]
@danwinship + @aojea  according to my understanding this test "pull-kubernetes-e2e-kind-dual-canary " should start working with this PR? (@aojea: do we need to add anything to kind, e.g. making kubelet report two IPs?)

**Comment by aojea** [comment]
> we need to add anything to kind, e.g. making kubelet report two IPs?)

yep,I need to modify kind , we need to pass the node ips to  kubelet using the --node-ip ipv4,ipv6 format.

**Comment by khenidak** [comment]
> > we need to add anything to kind, e.g. making kubelet report two IPs?)
> 
> yep,I need to modify kind , we need to pass the node ips to kubelet using the --node-ip ipv4,ipv6 format.

Thanks.  let us move this PR forward and get the kind dual canary adjusted, so we can use it for everything dualstack..

**Comment by aojea** [comment]
/retest
jobs timing out

**Comment by aojea** [comment]
/retest
job timeouts

**Comment by dcbw** [comment]
more job times `Job execution failed: Pod pending timeout.`
/retest

**Comment by khenidak** [comment]
@dcbw it is across the board for multiple PRs. not sure if it is github or prow.

**Comment by aojea** [comment]
> @dcbw it is across the board for multiple PRs. not sure if it is github or prow.

prow 

/retest
