### PR TITLE
Fix DaemonSet cache mutation

### LINKED ISSUE #38985: DaemonSetsController mutates DaemonSets from the shared DaemonSetInformer
In `storeDaemonSetStatus`, the DaemonSetsController modifies the DaemonSet from the shared DaemonSetInformer, setting `ds.Status.DesiredNumberScheduled`, `ds.Status.CurrentNumberScheduled`, `ds.Status.NumberMisscheduled`, and `ds.Status.NumberReady`. It needs to make a copy of the DaemonSet prior to mutating it.

Discovered in OpenShift using the cache mutation detector.

cc @deads2k @mikedanese @lavalamp @smarterclayton

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**: stops the DaemonSetController from mutating the DaemonSet shared informer cache

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #38985

cc @deads2k @mikedanese @lavalamp @smarterclayton

### CODE REVIEW

**Comment by ncdc** [comment]
Working on fixing the unit test failure.

File: pkg/controller/daemon/daemoncontroller.go [hunk 1]
```diff
@@ -539,19 +540,26 @@ func storeDaemonSetStatus(dsClient unversionedextensions.DaemonSetInterface, ds
 		return nil
 	}
 
+	clone, err := conversion.NewCloner().DeepCopy(ds)
```
Comment (smarterclayton) [inline pkg/controller/daemon/daemoncontroller.go]: Is this the new convention for invoking deep copy?  I thought we were using the copy method directly now?

Comment (ncdc) [inline pkg/controller/daemon/daemoncontroller.go]: I saw this somewhere in the code. What is the correct way to do it now?

Comment (smarterclayton) [inline pkg/controller/daemon/daemoncontroller.go]: Majority of instances I see are doing api.Scheme.DeepCopy()

**Comment by ncdc** [comment]
My changes make the unit tests flakey. Investigating.

**Comment by mikedanese** [comment]
cc @kubernetes/daemonset

**Comment by ncdc** [comment]
OK, I compiled the unit tests for this package and ran them in an infinite loop for a few minutes and didn't get any failures. I'd appreciate it if someone else could try the same and let me know if you see any flakes.

**Comment by lukaszo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/38986)*

**Comment by lukaszo** [comment]
I've run DaemonSet unit tests in loop 100 times and all runs passed.

**Comment by kargakis** [comment]
LGTM. Was the test failure related to https://github.com/kubernetes/kubernetes/issues/38518?

**Comment by ncdc** [comment]
@kargakis no, it was because the shared informer factory was being started in the unit tests, which makes things a bit unpredictable
