### PR TITLE
[release 1.33] Update pod resize test to accept new cpu.weight conversion

### LINKED ISSUE #135214: [InPlacePodVerticalScaling] e2e tests fail when upgrading containerd v2.1.5 on kOps
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kops/17743/pull-kops-e2e-cni-calico/1986440803127398400
```
failed [FAILED] [
failed to verify cpu request cgroup value:
  value of cgroup "/sys/fs/cgroup/cpu.weight" for container "c1" was "6"; expected one of ["1"],
failed to verify cpu request cgroup value:
  value of cgroup "/sys/fs/cgroup/cpu.weight" for container "c2" was "6"; expected one of ["1"]
] In [It] at: k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
```

### Which tests are failing?

```
Summarizing 41 Failures:
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, mixed containers - scale up cpu and memory [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase memory requests and limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase memory requests only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease CPU requests and increase CPU limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase memory limits only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container - decrease memory request (RestartContainer memory resize policy) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, three containers (c1, c2, c3) - increase: CPU (c1,c3), memory (c2, c3) ; decrease: CPU (c2) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container - increase memory request (NoRestart memory resize policy) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, three containers - decrease c1 resources, increase c2 resources, no change for c3 (net increase for pod) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase CPU requests and limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one container - increase CPU & memory with an extended resource [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container, one restartable init container - decrease init container CPU only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, mixed containers - add requests [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase memory requests and decrease CPU limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one container - increase CPU & memory [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests - increase cpu request [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease CPU limits only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one container - increase CPU (NotRequired) & memory (RestartContainer) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease CPU requests only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one restartable init container - decrease CPU & increase memory [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease memory requests and increase CPU limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests - decrease memory request [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, three containers - no change for c1, increase c2 resources, decrease c3 (net decrease for pod) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase CPU requests only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container, one restartable init container - increase init container memory only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease memory requests only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase CPU requests and decrease CPU limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, mixed containers - add limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease CPU requests and limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container, one restartable init container - increase init container CPU only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container - decrease CPU (NotRequired) & memory (RestartContainer) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one restartable init container - increase CPU & memory [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease memory requests and increase memory limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one container, one restartable init container - decrease init container CPU [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - increase CPU limits only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container, one restartable init container - decrease init container memory requests only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container with cpu & memory requests + limits - decrease CPU requests and increase memory limits [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Guaranteed QoS pod, one container - decrease CPU only [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, one container, one restartable init container - increase init container CPU & memory [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod, three containers - increase c1 resources, no change for c2, decrease c3 resources (no net change for pod) [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
  [FAIL] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] [It] Burstable QoS pod with memory requests + limits - decrease memory limit [sig-node, FeatureGate:InPlacePodVerticalScaling, Beta]
  k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1072
```

### Since when has it been failing?

This is part of a PR that updates containerd to v2.1.5 and corresponding runc version.
https://github.com/kubernetes/kops/pull/17743

### Testgrid link

https://testgrid.k8s.io/kops-presubmits#e2e-gce-cni-calico

### Reason for failure (if possible)

runc v1.3.3 may has some changes that might be related:
https://github.com/opencontainers/runc/releases/tag/v1.3.2
> The conversion from cgroup v1 CPU shares to cgroup v2 CPU weight is
improved to better fit default v1 and v2 values. (https://github.com/opencontainers/runc/issues/4772, https://github.com/opencontainers/runc/pull/4785, https://github.com/opencontainers/runc/pull/4897)

### Anything else we need to know?

This same behaviour is visible in all e2e tests that did not fail for other reasons from the PR.
We run the same (or very similar) test periodically with the previous containerd version and there are no issues:
https://testgrid.k8s.io/kops-network-plugins#kops-aws-cni-calico

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by hakman**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Tests are failing when clusters are using containerd 1.3.2+.
Backport of #132791.

#### Which issue(s) this PR is related to:

Fixes #135214

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks! I had just started teasing this out.

Testing this PR locally with kind + runc 1.3.x local branch which I've confirmed failed the tests on release-1.33 prior to this change.

File: test/e2e/framework/pod/resize.go [hunk 1]
```diff
@@ -24,6 +24,7 @@ import (
 	"strconv"
 	"strings"
 
+	"github.com/opencontainers/cgroups"
```
Comment (BenTheElder) [inline test/e2e/framework/pod/resize.go]: this package only builds on linux, so I recommend putting it in a separate _linux.go until we can sort out the fix

Comment (BenTheElder) [reply test/e2e/framework/pod/resize.go]: (it should fail presubmits until then)

File: test/e2e/framework/pod/resize.go [hunk 2]
```diff
@@ -340,14 +342,24 @@ func VerifyPodContainersCgroupValues(ctx context.Context, f *framework.Framework
...
+				expectedCPUSharesString = append(expectedCPUSharesString, strconv.FormatInt(expectedCPUSharesOld, 10))
+				// Because of https://github.com/kubernetes/kubernetes/issues/131216, the way of conversion has been changed.
+				// runc: https://github.com/opencontainers/runc/pull/4785
+				// crun: https://github.com/containers/crun/issues/1721
+				// This is dependent on the container runtime version. In order not to break the tests when we upgrade the
+				// container runtimes, we check if either the old or the new conversion matches the actual value for now.
+				expectedCPUSharesNew := int64(cgroups.ConvertCPUSharesToCgroupV2Value(uint64(expectedCPUShares)))
+				expectedCPUSharesString = append(expectedCPUSharesString, strconv.FormatInt(expectedCPUSharesNew, 10))
+			} else {
+				expectedCPUSharesString = append(expectedCPUSharesString, strconv.FormatInt(expectedCPUShares, 10))
```
Comment (BenTheElder) [inline test/e2e/framework/pod/resize.go]: won't this clobber it?

Comment (hakman) [reply test/e2e/framework/pod/resize.go]: reworked the code to be closer to the original PR.

**Comment by BenTheElder** [comment]
still failing locally, double checked that 1.34 will pass locally with that [setup](https://github.com/kubernetes/kubernetes/issues/135214#issuecomment-3663665725).

**Comment by BenTheElder** [comment]
In both our branches it seems to produce a slice of identical weights like 1,1 which don't match the actual weights. I needed sleep and _may_ be able to follow up tomorrow, posted more to the issue how I'm testing.

**Comment by BenTheElder** [comment]
> @BenTheElder https://github.com/hakman/kubernetes/tree/baclkport-cpu.weight-conversion-3 is a clean branch that passes the tests on MacOS:

Thanks, I'm testing locally on linux and still getting issues when on this kind branch:  which has a base image with runc 1.3.3
https://github.com/kubernetes/kubernetes/issues/135214#issuecomment-3663753211

NOTE: kind @ HEAD is on runc 1.2.9 temporarily while we sort this out.

```
  value of cgroup "/sys/fs/cgroup/cpu.weight" for container "c1" should match one of the expectations: Expected
      <string>: 49
  to be an element of
      <[]string | len:2, cap:2>: ["16", "16"]

```

Will also test `hakman:baclkport-cpu.weight-conversion-2` (this PR branch) next.

**Comment by hakman** [comment]
> We can also hack up a test in CI, I think that's worthwhile at this point.

Hmm... at this point I am out of better ideas also.

**Comment by BenTheElder** [comment]
Quick solution for testing in CI: https://github.com/kubernetes-sigs/kind/pull/4079

Can `/test pull-kind-e2e-kubernetes-1-33` there (not here) to test this PR (see the second commit) with otherwise 1.33 config + upgrading runc again

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
thank you!

**Comment by puerco** [comment]
Thanks!
/lgtm

**Review by puerco — APPROVED** [review]
