### PR TITLE
bazel: make kubernetes-src.tar.gz actually include all srcs

### LINKED ISSUE #60863: staging repositories not handled properly in bazel-built kubernetes-src.tar.gz
I've been experimenting with producing a kubernetes src tarball from bazel that includes all generated code, such that an end user (like an OS distro) would be able to build kubernetes binaries using solely `go build`.

The kubernetes-src.tar.gz produced by the [build rule in build/release-tars](https://github.com/kubernetes/kubernetes/blob/f196b7c7523dbf0d6ed703a93af73f54e9d2e42c/build/release-tars/BUILD#L39-L52) almost already works, except that the staging directory symlinks under vendor/k8s.io are not handled correctly; some of the auxiliary files are included, but none of the go files.

For example:
```console
$ bazel build build/release-tars/kubernetes-src.tar.gz --define PACKAGE_SRC=true
INFO: Analysed target //build/release-tars:kubernetes-src.tar.gz (2 packages loaded).
INFO: Found 1 target...
Target //build/release-tars:kubernetes-src.tar.gz up-to-date:
  bazel-bin/build/release-tars/kubernetes-src.tar.gz
INFO: Elapsed time: 3.197s, Critical Path: 2.37s
INFO: Build completed successfully, 3 total actions
$ tar tzvf bazel-bin/build/release-tars/kubernetes-src.tar.gz | grep vendor/k8s.io/apimachinery
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/.github/
-r-xr-xr-x 0/0             150 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/.github/PULL_REQUEST_TEMPLATE.md
-r-xr-xr-x 0/0             730 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/CONTRIBUTING.md
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/
-r-xr-xr-x 0/0            4873 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/Godeps.json
-r-xr-xr-x 0/0              27 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/OWNERS
-r-xr-xr-x 0/0             136 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/Godeps/Readme
-r-xr-xr-x 0/0           11358 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/LICENSE
-r-xr-xr-x 0/0             243 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/OWNERS
-r-xr-xr-x 0/0            1251 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/README.md
-r-xr-xr-x 0/0             148 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/code-of-conduct.md
dr-xr-xr-x 0/0               0 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/pkg/
-r-xr-xr-x 0/0              74 1969-12-31 16:00 kubernetes/vendor/k8s.io/apimachinery/pkg/OWNERS
```
(Directory permissions also seem to be incorrect, which seems to be a bug in our fast build_tar implementation. The bazel-bundled one does not have this bug.)

I was able to fix this locally with a few basic changes:
* Adding `BUILD` files to all of the `staging/src/k8s.io` repos at their root to prevent any of these auxiliary files from ending up in the tarball. I believe this is because these files are matching the `package-srcs` glob in `vendor/BUILD`, but the `all-srcs` list does not follow symlinks (and hence the go files are missing, since those directories have BUILD files already).
* Explicitly adding a symlink attribute to the `kubernetes-src` `pkg_tar` rule with the staging symlinks:
```python
STAGING_DIRS = [
    "api",
    "apiextensions-apiserver",
    "apimachinery",
    "apiserver",
    "client-go",
    "code-generator",
    "kube-aggregator",
    "metrics",
    "sample-apiserver",
    "sample-controller",
]

pkg_tar(
    name = "kubernetes-src",
    srcs = select({
        ":package_src": ["//:all-srcs"],
        "//conditions:default": ["README-src.txt"],
    }), 
    extension = "tar.gz",
    package_dir = "kubernetes",
    strip_prefix = select({
        ":package_src": "//",
        "//conditions:default": ".",
    }), 
    symlinks = {"kubernetes/vendor/k8s.io/%s" % dir: "../../staging/src/k8s.io/%s" % dir for dir in STAGING_DIRS},
    tags = ["no-cache"],
)
```

What I haven't figured out yet is how best to manage that list of staging directories. (Extend kazel? Not excited about that, though.)

One other change is that we need to declare an explicit dependency on generated source files, since they are not picked up by globs; for example, in `pkg/generated/openapi/BUILD`:
```python
filegroup(
    name = "package-srcs",
    srcs = glob(["**"]) + [":zz_generated.openapi"],
    tags = ["automanaged"],
    visibility = ["//visibility:private"],
)
```

The good news is that with these changes I can extract kubernetes-src.tar.gz and `go build k8s.io/kubernetes/cmd/kube-apiserver` successfully.
(You can't do that in k/k without first running `make generated_files` or using bazel.)

/assign

### PR DESCRIPTION
**Pull request by ixdy**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**: addresses a few necessary items to make `kubernetes-src.tar.gz` actually contain all necessary Go sources:
- make `hack/update-bazel.sh` ensure all staging repos have a `BUILD` file at their root
- make `hack/update-bazel.sh` generate a `bzl` file containing a list of all staging repos
- use the list of staging repos to create symlinks in `kubernetes-src.tar.gz`
- always produce a real `kubernetes-src.tar.gz`, since it's pretty fast now

Additionally, I've removed one gazelle directive we don't need (and haven't needed for a while), which was fixed by bazelbuild/bazel-gazelle#207.

I'm not _super_ excited about adding more bash, but this seems too specialized and wonky to add to kazel. (Also, the logic is pretty simple.)

**Which issue(s) this PR fixes**:

Fixes #60863

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @BenTheElder @fejta

### CODE REVIEW

File: hack/update-bazel.sh [hunk 1]
```diff
@@ -29,14 +29,25 @@ go install k8s.io/kubernetes/vendor/github.com/bazelbuild/bazel-gazelle/cmd/gaze
...
-if ! grep -q "# gazelle:importmap_prefix" "${KUBE_ROOT}/vendor/BUILD"; then
-  echo "# gazelle:importmap_prefix k8s.io/kubernetes/vendor" >> "${KUBE_ROOT}/vendor/BUILD"
-fi
+staging_repos=($(cd "${KUBE_ROOT}/staging/src" && find k8s.io/ -mindepth 1 -maxdepth 1 -type d | sort))
 
+(
+  cat "${KUBE_ROOT}/hack/boilerplate/boilerplate.generatebzl.txt"
+  echo "# This file is autogenerated by hack/update-bazel.sh."
+  # avoid getting caught by the boilerplate checker
+  rev <<<".TIDE TON OD #"
```
Comment (ixdy) [inline hack/update-bazel.sh]: kudos to @BenTheElder for this suggestion

File: hack/update-bazel.sh [hunk 2]
```diff
@@ -29,14 +29,25 @@ go install k8s.io/kubernetes/vendor/github.com/bazelbuild/bazel-gazelle/cmd/gaze
...
 go install k8s.io/kubernetes/vendor/k8s.io/repo-infra/kazel
 
-touch "${KUBE_ROOT}/vendor/BUILD"
-# Ensure that we use the correct importmap for all vendored dependencies.
-# Probably not necessary in gazelle 0.13+
-# (https://github.com/bazelbuild/bazel-gazelle/pull/207).
-if ! grep -q "# gazelle:importmap_prefix" "${KUBE_ROOT}/vendor/BUILD"; then
-  echo "# gazelle:importmap_prefix k8s.io/kubernetes/vendor" >> "${KUBE_ROOT}/vendor/BUILD"
-fi
+staging_repos=($(cd "${KUBE_ROOT}/staging/src" && find k8s.io/ -mindepth 1 -maxdepth 1 -type d | LANG=C sort))
```
Comment (BenTheElder) [inline hack/update-bazel.sh]: can we add a comment about what the high level intent is here to match the sections above?

imo it might be worth putting a short one on the gazelle / kazel call(s) too to make this easier to follow for the uninitiated reader.

Comment (ixdy) [reply hack/update-bazel.sh]: done

File: hack/update-bazel.sh (hunk 1 above)
Comment (fejta) [reply hack/update-bazel.sh]: nit: should be ‮kudos to @BenTheElder for this suggestion

**Review by fejta — COMMENTED** [review]
/lgtm

**Comment by ixdy** [comment]
rebased

**Comment by ixdy** [comment]
The cross job is getting flakier and flakier...

/retest

**Review by fejta — COMMENTED** [review]
/lgtm

**Comment by ixdy** [comment]
/assign @smarterclayton
for `staging/`

**Comment by ixdy** [comment]
/hold cancel

(still waiting on approvals...)

**Comment by fejta** [comment]
/assign lavalamp smarterclayton
for staging approval
/assign apelisse BenTheElder cblecker dims thockin sttts
for dep approval

File: staging/src/k8s.io/apimachinery/BUILD [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+    srcs = glob(["**"]),
+    tags = ["automanaged"],
+    visibility = ["//visibility:private"],
+)
+
+filegroup(
+    name = "all-srcs",
+    srcs = [
+        ":package-srcs",
+        "//staging/src/k8s.io/apimachinery/pkg/api/apitesting:all-srcs",
```
Comment (apelisse) [inline staging/src/k8s.io/apimachinery/BUILD]: Does this mean that sub-directory hierarchy changes will required top-level apimachinery approval from now on? :-/

Comment (apelisse) [reply staging/src/k8s.io/apimachinery/BUILD]: Well, looking at the diff above, it was even worse before.

**Comment by apelisse** [comment]
> Additionally, I've removed one gazelle directive we don't need (and haven't needed for a while).

I'll trust you on this, I'm understanding that's what I'm approving.
/approve

File: staging/src/k8s.io/apimachinery/BUILD (hunk 3 above)
Comment (ixdy) [reply staging/src/k8s.io/apimachinery/BUILD]: That's correct. The easiest way to fix it is to ensure there's a `BUILD` file at appropriate ownership levels, since the `all-srcs` rules fold up to the next `all-srcs` rule.

For example, the `pkg/apis/OWNERS` file here has
```yaml
options:
  no_parent_owners: true
approvers:
- api-approvers
reviewers:
- api-reviewers
labels:
- kind/api-change
```

and since there are no `BUILD` files until well into the tree, the directory structure is encoded here in this top-level `BUILD` file:
```python
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/fuzzer:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/internalversion:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1:all-srcs",
        "//staging/src/k8s.io/apimachinery/pkg/apis/testapigroup:all-srcs",
```

If we were to create a `pkg/apis/BUILD` file, these lines would be replaced with
```python
        "//staging/src/k8s.io/apimachinery/pkg/apis:all-srcs",
```

and then any subsequent changes would be isolated from this top-level BUILD file.

Comment (ixdy) [reply staging/src/k8s.io/apimachinery/BUILD]: Note that I did something similar for the top-level `BUILD` file in kubernetes/kubernetes; each top-level directory has a `BUILD` file, so the `all-srcs` rule at top-level is simple and isolated from changes:
https://github.com/kubernetes/kubernetes/blob/d0c3b708026f681f7467d36dcf9696f89ccfcfab/build/root/BUILD.root#L78-L97

**Comment by ixdy** [comment]
The gazelle directive I removed was fixed by https://github.com/bazelbuild/bazel-gazelle/pull/207, which was merged last May (but not yet released at the time I was doing a bunch of refactoring in https://github.com/kubernetes/kubernetes/pull/64122).

File: staging/src/k8s.io/apimachinery/BUILD (hunk 3 above)
Comment (apelisse) [reply staging/src/k8s.io/apimachinery/BUILD]: Thank you Jeff!

**Comment by fejta** [comment]
Thanks Anton!
/unassign BenTheElder cblecker dims thockin sttts

**Comment by ixdy** [comment]
oh, I think I also need re-lgtm after the last rebase.
