### PR TITLE
Fix: Check `defaultBackend` in `allowRelaxedServiceNameValidation`

### LINKED ISSUE #135425: `RelaxedServiceNameValidation` feature gate does not cover ingress `spec.defaultBackend`
### What happened?

The `RelaxedServiceNameValidation` feature gate implementation in `allowRelaxedServiceNameValidation()` might be incomplete. It checks service names in `spec.rules` but does not check `spec.defaultBackend.service.name`.

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L701

This creates inconsistent behavior: Ingresses with relaxed service names in rules can be updated, but those with relaxed names only in defaultBackend cannot.

### What did you expect to happen?

The feature gate should consistently handle relaxed service name validation for both `spec.rules` and `spec.defaultBackend`. When the feature gate is disabled, existing Ingresses with RFC 1123-compliant but RFC 1035-noncompliant service names (e.g., "1-default-service") should remain updatable regardless of whether those names appear in `rules` or `defaultBackend`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable RelaxedServiceNameValidation feature gate
2. Create Ingress with defaultBackend with a service name starting with a digit
3. Disable RelaxedServiceNameValidation feature gate
4. Attempt to update this Ingress
5. The update fails because the old service name starts with a digit.

### Anything else we need to know?

I found a minor typo in comment: "old Ingresss" should be "old Ingress"
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/validation/validation.go#L710

### Kubernetes version

<details>

```console
$ kubectl version
v1.34
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kfess**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The `RelaxedServiceNameValidation` feature gate implementation in `allowRelaxedServiceNameValidation()` seems to be incomplete. It checks service names in `spec.rules` but does not check `spec.defaultBackend.service.name`.

This creates inconsistent behavior where Ingresses with relaxed service names (RFC 1123-compliant but RFC 1035-noncompliant, e.g., starting with digits) in rules can be updated, but those with such names only in defaultBackend cannot.

This PR completes the feature gate implementation by adding validation for `spec.defaultBackend.service.name` to maintain backward compatibility for existing Ingresses.

Changes:
- Add check for `spec.defaultBackend.service.name` in `allowRelaxedServiceNameValidation()`
- Add test cases covering defaultBackend scenarios
- Fix typo in comment: 'Ingresss' -> 'Ingress'

#### Which issue(s) this PR is related to:

Fixes #135425

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
N/A
```

### CODE REVIEW

**Comment by adrianmoisey** [comment]
I don't understand those test failures, retrying:
/retest-required

**Comment by adrianmoisey** [comment]
Cluster didn't initialize:
/retest-required

**Comment by kfess** [comment]
Thank you for handling the failure, it seems to be working.

**Comment by aojea** [comment]
/assign @thockin 

for api approval

File: pkg/apis/networking/validation/validation.go [hunk 1]
```diff
@@ -707,7 +707,20 @@ func allowRelaxedServiceNameValidation(oldIngress *networking.Ingress) bool {
 	if oldIngress == nil {
 		return false
 	}
-	// If feature gate is disabled, check if any service names in the old Ingresss
+
+	// Check if default backend service names in the old Ingress
+	if oldIngress.Spec.DefaultBackend != nil && oldIngress.Spec.DefaultBackend.Service != nil {
```
Comment (thockin) [inline pkg/apis/networking/validation/validation.go:712]: The problem with this is that, in theory, we might upgrade, use the feature then downgrade  binary, leaving the user with an object stored that now fails validation.  Stored objects should never fail validation.  Practically this is very unlikely, but the consequences of it are pretty severe.  On principle we don't really do this -- this is why we have alpha gates as a requirement for new API fields and for changes like this.

Am I missing something?  Why would this be allowable without a safe way to rollback?

What is happens if we don't do this, and instead demand a new gate, which would mean alpha in 36.  Sad, but that's how things work.

Comment (aojea) [reply pkg/apis/networking/validation/validation.go:712]: ~This is exactly the problem this patch is fixing, the problem is the logic in validation is confusing, first this function goal is to detect if the validation should use the relaxed way `allowRelaxedServiceNameValidation` , so this is true if the feature gate is enabled or the old object is using the relaxed format , precisely for the reasons that you mention, see https://github.com/kubernetes/kubernetes/issues/135425#issuecomment-3575813439 for more context~ clarified offline and by Adrian in the next comment

Comment (adrianmoisey) [reply pkg/apis/networking/validation/validation.go:712]: I think I see what Tim is saying.
Let's say we merge this PR into 1.35.0 and backport the fix to 1.34.3.

A user could upgrade to 1.35.0, modify their Ingress default backend name to use a relaxed service name
Then the user could downgrade to 1.34.2, and their ingress resource is now **invalid**.

I think we need to get this PR merged into 1.35.0 *and* revert the PR that promotes `RelaxedServiceNameValidation` to beta.

Meaning that 1.35.0 will get this PR bug fix, and 1.36.0 will get the promotion to beta.

Comment (aojea) [reply pkg/apis/networking/validation/validation.go:712]: I wonder if just a release note will be enough, this seems like a really complex corner case:

To have a Ingress with a relaxed service name in `spec.DefaultBackend.Service.Name` you seems to have two options:

1. you have created in 1.34 enabling the alpha feature gate

2 you have upgraded to 1.35 and created the Ingress object

After merging this fix for 1.35, the way it can break is if you downgrade to 1.34 and you also disable the feature gate.
If you are in scenario 1) that is not likely going to happen, you already had the feature enabled in alpha. 
That leaves us with scenario 2), that seems very unlikely

Comment (danwinship) [reply pkg/apis/networking/validation/validation.go:712]: Also, we have no reason to think anybody is even going to use this feature; we changed the validation because it will make the code (and docs) cleaner, not because users actually needed the relaxed validation for anything.

Comment (thockin) [reply pkg/apis/networking/validation/validation.go:712]: We're into risk-vs-reward territory.

The real problem for me is this: If we merge this one, which we know is not safe for rollbacks, then what stops us the next time there's a tasty fix which is similar?

Options:

1) Merge it and YOLO
2) Merge it, merge a patch to 34, tell people to _only_ roll back from 35.x to 34.3
3) Merge it in 35, revert the gate promotion
4) Merge it in 35, add a new gate(alpha), leave the existing gate promotion as is
5) Merge it in 36 with a new gate

I think (1) and (4) are right out.  I don't know if we have ever done (2) -- it seems like the sort of thing that will easily get missed, but it gives us max forward progress.  I don't think this gate is on anyone's critical path, so (3) or (5) are the safe path.

Comment (liggitt) [reply pkg/apis/networking/validation/validation.go:712]: Narrowly for the question about promoting the gate or not in 1.35, `--min-compatibility-version` (new in 1.35) is how admins can signal "rollback safe"

this is the pattern we'd use to say "once you're on 1.35 and aren't going back, this can default enable"
```
	RelaxedServiceNameValidation: {
		{Version: version.MustParse("1.34"), Default: false, PreRelease: featuregate.Alpha},
		{Version: version.MustParse("1.35"), Default: false, PreRelease: featuregate.Beta},
		{Version: version.MustParse("1.35"), Default: true, PreRelease: featuregate.Beta, MinCompatibilityVersion: version.MustParse("1.35")},
	},
```

That would enable when the admin indicates they're rollback safe explicitly on 1.35 with --min-compatibility-version=1.35, or in 1.36 (which defaults to being compatible one version back, with 1.35), whichever comes first

Comment (thockin) [reply pkg/apis/networking/validation/validation.go:712]: This is a good answer, and I am glad that this is ready to use!  I thought it was not quite ready yet.

Comment (liggitt) [reply pkg/apis/networking/validation/validation.go:712]: > This is a good answer, and I am glad that this is ready to use!

hat tip to @siyuanfoundation

Comment (adrianmoisey) [reply pkg/apis/networking/validation/validation.go:712]: My vote is for (3): Merge it in 35, revert the gate promotion

I don't understand how (5) (Merge it in 36 with a new gate) or `--min-compatibility-version` can solve the use case where:
1. Someone uses the feature in 1.35
2. They rollback to 1.34
3. They try edit their Ingress

However, I'm happy to defer to the smart people in the room and let them decide on a path forward.

If we go for (3), I'm happy to get the PRs ready.

EDIT: If we chose to go with (3), here are some PRs:
- ~~https://github.com/kubernetes/kubernetes/pull/135477~~ not needed
- Website: https://github.com/kubernetes/website/pull/53471

Comment (aojea) [reply pkg/apis/networking/validation/validation.go:712]: seems 3) is a no brainer, let me tag @kubernetes/release-managers to provide them visibility on the discussion.

@kfess do you mind incorporating #135477  commit so we have all in the same PR and is easy to manage and to trace back in the future?

Comment (kfess) [reply pkg/apis/networking/validation/validation.go:712]: If we go with (3), feel free to incorporate it.

Comment (aojea) [reply pkg/apis/networking/validation/validation.go:712]: @kfess the ask is for you to incorporate that commit in this PR so we have a single place with all changes :)

Comment (kfess) [reply pkg/apis/networking/validation/validation.go:712]: @aojea
Done, I've cherry-picked the commit from #135477.

Comment (liggitt) [reply pkg/apis/networking/validation/validation.go:712]: > I don't understand how (5) (Merge it in 36 with a new gate) or --min-compatibility-version can solve the use case where:
>
> 1. Someone uses the feature in 1.35
> 2. They rollback to 1.34
> 3. They try edit their Ingress

Both of those approaches put the 1.35-specific relaxation behind something that does not default on until 1.36, but an admin could enable in 1.35 after the upgrade is considered "rollback-safe"

Comment (adrianmoisey) [reply pkg/apis/networking/validation/validation.go:712]: Gotcha, I missed that your suggestion set 1.35 to `Default: false`

Comment (thockin) [reply pkg/apis/networking/validation/validation.go:712]: I'm fine with this, I thought for sure we would have gone witrh Jordan's answer, though.

**Review by thockin — COMMENTED** [review]
/approve

**Comment by aojea** [comment]
/lgtm
/retest

will wait one day for milestone unless @kubernetes/release-managers or others want to go ahead

Thanks
