### PR TITLE
Fix race in scheduler integration tests

### LINKED ISSUE #132025: scheduler handleSchedulingFailure: DATA RACE
### What happened?

I have https://github.com/kubernetes/kubernetes/pull/116980 which runs integration tests with race detection enabled. Running it shows in several tests:
```
k8s.io/kubernetes/test/integration/scheduler: preemption
...
=== RUN   TestPreemption/basic_pod_preemption_with_preFilter_(Async_preemption_enabled:_true)
...

WARNING: DATA RACE
Write at 0x00c0089f0c60 by goroutine 6125:
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).handleSchedulingFailure()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/schedule_one.go:1068 +0x1154
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).handleSchedulingFailure-fm()
      <autogenerated>:1 +0xcb
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).ScheduleOne()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/schedule_one.go:118 +0xd8a
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).ScheduleOne-fm()
      <autogenerated>:1 +0x47
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x9c
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
  k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:223 +0x108
  k8s.io/apimachinery/pkg/util/wait.UntilWithContext()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:172 +0x59
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).Run.gowrap1()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:507 +0x17

Previous read at 0x00c0089f0c60 by goroutine 5910:
  k8s.io/kubernetes/pkg/scheduler/backend/queue.(*PriorityQueue).Update()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/backend/queue/scheduling_queue.go:1020 +0x1652
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInSchedulingQueue()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/eventhandlers.go:164 +0xd06
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInSchedulingQueue-fm()
      <autogenerated>:1 +0x64
  k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:264 +0x81
  k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate()
      <autogenerated>:1 +0x1f
  k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:329 +0xef
  k8s.io/client-go/tools/cache.(*FilteringResourceEventHandler).OnUpdate()
      <autogenerated>:1 +0x84
  k8s.io/client-go/tools/cache.(*processorListener).run.func1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1074 +0x3b9
  k8s.io/client-go/tools/cache.(*processorListener).run()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1086 +0x5e
  k8s.io/client-go/tools/cache.(*processorListener).run-fm()
      <autogenerated>:1 +0x33
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x86

Goroutine 6125 (running) created at:
  k8s.io/kubernetes/pkg/scheduler.(*Scheduler).Run()
      /home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:507 +0x1c4
  k8s.io/kubernetes/test/integration/scheduler/preemption.TestPreemption.gowrap1()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/scheduler/preemption/preemption_test.go:179 +0x4f

Goroutine 5910 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0xe4
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:888 +0x1e7
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:892 +0x4b
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      <autogenerated>:1 +0x47
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).RunWithContext.(*Group).StartWithContext.func4()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:63 +0x46
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x86
```

### What did you expect to happen?

No data race.

### How can we reproduce it (as minimally and precisely as possible)?

Run locally with `go test -race`.

### Anything else we need to know?

_No response_

### Kubernetes version

master

/sig scheduling

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

There is an almost impossible data race in kube-scheduler that can be detected using built-in go test race detector. If pod gets updated (Update method of PriorityQueue is called - [here](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/backend/queue/scheduling_queue.go#L1020)) and then pod is popped from the queue, processed by the scheduling cycle and then handled in failure handler ([here](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/schedule_one.go#L1069)), the race occurs. See more detailed description here: https://github.com/kubernetes/kubernetes/pull/132043#issuecomment-2930651764.

This PR moves deletion from unschedulablePods right after the pod is moved to the backoffQ (similarly to the activeQ). This allows to remove deletion from unschedulablePods from Update method, removing the data race.

Moreover, preemptionDoneChannels in TestAsyncPreemption is covered by the lock to prevent race in the test code itself.

#### Which issue(s) this PR is related to:

Fixes #132025

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/cc @googs1025 

can you take a look for a first reviewing path

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 1]
```diff
@@ -1017,7 +1019,6 @@ func (p *PriorityQueue) Update(logger klog.Logger, oldPod, newPod *v1.Pod) {
 				queue := p.requeuePodWithQueueingStrategy(logger, pInfo, hint, evt.Label())
 				if queue != unschedulablePods {
 					logger.V(5).Info("Pod moved to an internal scheduling queue because the Pod is updated", "pod", klog.KObj(newPod), "event", evt.Label(), "queue", queue)
-					p.unschedulablePods.delete(pInfo.Pod, gated)
```
Comment (googs1025) [inline pkg/scheduler/backend/queue/scheduling_queue.go:1050]: (Not sure if this is correct) According to the description, but when I looked at the source code 🤔 , I found that the `Update` method still seems to call the `moveToBackoffQ` method. Will this have any impact?

> This PR moves deletion from unschedulablePods right after the pod is moved to the backoffQ (similarly to the activeQ). This allows to remove deletion from unschedulablePods from Update method, removing the data race.

https://github.com/kubernetes/kubernetes/blob/29ed1fb15274612b23ed1496f1fe33e1322c3637/pkg/scheduler/backend/queue/scheduling_queue.go#L1029-L1041

Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go:1050]: Update calls `moveToBackoffQ` through `requeuePodWithQueueingStrategy` as well. However, moving the deletion from `unschedulablePods` right after adding the pod to the backoffQ, mitigates the race risk.

I also noticed that I forgot to remove the line 1034, I updated the PR.

Comment (googs1025) [reply pkg/scheduler/backend/queue/scheduling_queue.go:1050]: got this. thanks 😄

**Comment by sanposhiho** [comment]
/hold 

for merging it after my (or dom4ha's) approval

**Comment by dom4ha** [comment]
The change itself looks good.
It's not clear to me why we need to update the pod Info in error handler at all. Shouldn't we wait for update instead?
I'd also think about removing pods from queues at the beginning of `Update` to prevent from poping out not updated pod version (pop does not block on PriorityQueue lock)

**Comment by macsko** [comment]
> It's not clear to me why we need to update the pod Info in error handler at all.

I agree that we need to take a look at the update part of the scheduling queue, likely in a new issue (I'll create it).

> I'd also think about removing pods from queues at the beginning of `Update` to prevent from poping out not updated pod version (pop does not block on PriorityQueue lock)

Or just take activeQ's and backoffQ's locks for a part of the `Update` func.

**Comment by dom4ha** [comment]
> Or just take activeQ's and backoffQ's locks for a part of the Update func.

Right, that might be equivalent.

**Comment by macsko** [comment]
@dom4ha @sanposhiho I've finally updated this PR. Now, the activeQ's lock is taken at the beginning of Update to preserve consistency, i.e. avoid popping the pod from activeQ/backoffQ in the meantime.

**Comment by sanposhiho** [comment]
I don't understand the problematic scenario yet. I read [your comment](https://github.com/kubernetes/kubernetes/pull/132043#issuecomment-2930651764) on a previous PR:

> 1. Scheduler receives pod update and calls SchedulingQueue.Update() with it
> 2. Pod is popped from the scheduling queue (either activeQ or backoffQ)
> 3. Pod is unschedulable and goes to handleSchedulingFailure (first - schedule_one.go#L1069), but in the same time SchedulingQueue.Update() is on scheduling_queue.go#L1020 - RACE


How can [scheduling_queue.go#L1020](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/backend/queue/scheduling_queue.go#L1020) be called at the same timing as [schedule_one.go#L1069](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/schedule_one.go#L1069)? At that timing, the pod is not back in the queue and `scheduling_queue.go#L1020` isn't reachable, right?

**Comment by macsko** [comment]
> How can [scheduling_queue.go#L1020](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/backend/queue/scheduling_queue.go#L1020) be called at the same timing as [schedule_one.go#L1069](https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/schedule_one.go#L1069)? At that timing, the pod is not back in the queue and `scheduling_queue.go#L1020` isn't reachable, right?

Remember that this case is _hypothetical_ (unfortunate interleaving on low #cores) and you have to think in another direction:

- `PriorityQueue.Update()` is called first
- In the simplest scenario it reaches line 1019 and is interleaved by the goroutine that does scheduling
- Then, (in another goroutine) the pod is popped from, let's say, backoffQ (it's possible, because pop isn't locked by the PriorityQueue.lock)
- Pod goes through the scheduling cycle and is rejected
- Pod goes to the `handleSchedulingFailure`, specifically to line 1069
- At that moment, the `PriorityQueue.Update()` execution goes to the line 1020 - RACE

**Comment by sanposhiho** [comment]
> (it's possible, because pop isn't locked by the PriorityQueue.lock)

aha

**Comment by sanposhiho** [comment]
But, how would the pod be moved to backoffQ and then popped out? 
The line 1019 can be reachable only when the pod is in the unschedulable pod pool. So, the pod has to be moved to backoffQ or activeQ to be poped out

File: pkg/scheduler/backend/queue/active_queue.go [hunk 2]
```diff
@@ -67,6 +66,12 @@ type unlockedActiveQueuer interface {
 	// The event should show which event triggered this addition and is used for the metric recording.
 	// This method should be called in activeQueue.underLock().
 	add(pInfo *framework.QueuedPodInfo, event string)
+	// update updates the pod in activeQ if oldPodInfo is already in the queue.
+	// It returns new pod info if updated, nil otherwise.
+	update(newPod *v1.Pod, oldPodInfo *framework.QueuedPodInfo) *framework.QueuedPodInfo
+	// addEventsIfPodInFlight adds clusterEvent to inFlightEvents if the newPod is in inFlightPods.
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/active_queue.go]:
```suggestion
	// addEventsIfPodInFlight adds events to inFlightEvents if the newPod is in inFlightPods.
	// It returns true if events were pushed to the inFlightEvents.
```

File: pkg/scheduler/backend/queue/active_queue.go [hunk 3]
```diff
@@ -40,7 +40,6 @@ type activeQueuer interface {
 	underLock(func(unlockedActiveQ unlockedActiveQueuer))
 	underRLock(func(unlockedActiveQ unlockedActiveQueueReader))
 
-	update(newPod *v1.Pod, oldPodInfo *framework.QueuedPodInfo) *framework.QueuedPodInfo
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/active_queue.go:43]: This is not entirely related to this change, but can you please update the doc comment for activeQueuer? I think method names are outdated?

File: pkg/scheduler/backend/queue/active_queue.go [hunk 4]
```diff
@@ -101,6 +112,34 @@ func (uaq *unlockedActiveQueue) add(pInfo *framework.QueuedPodInfo, event string
...
+func (uaq *unlockedActiveQueue) update(newPod *v1.Pod, oldPodInfo *framework.QueuedPodInfo) *framework.QueuedPodInfo {
+	if pInfo, exists := uaq.queue.Get(oldPodInfo); exists {
+		_ = pInfo.Update(newPod)
+		uaq.queue.AddOrUpdate(pInfo)
+		return pInfo
+	}
+	return nil
+}
+
+// addEventsIfPodInFlight adds clusterEvent to inFlightEvents if the newPod is in inFlightPods.
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/active_queue.go]: same change as above

File: pkg/scheduler/backend/queue/active_queue.go [hunk 5]
```diff
@@ -101,6 +112,34 @@ func (uaq *unlockedActiveQueue) add(pInfo *framework.QueuedPodInfo, event string
...
+// It returns true if pushed the event to the inFlightEvents.
+func (uaq *unlockedActiveQueue) addEventsIfPodInFlight(oldPod, newPod *v1.Pod, events []fwk.ClusterEvent) bool {
+	_, ok := uaq.inFlightPods[newPod.UID]
+	if ok {
+		for _, event := range events {
+			uaq.metricsRecorder.ObserveInFlightEventsAsync(event.Label(), 1, false)
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/active_queue.go:129]: optional:
```suggestion
			uaq.metricsRecorder.ObserveInFlightEventsAsync(event.Label(), 1, false /* don't force flush */)
```

File: pkg/scheduler/backend/queue/nominator.go [hunk 6]
```diff
@@ -61,11 +61,11 @@ func newPodNominator(podLister listersv1.PodLister) *nominator {
 	}
 }
 
-// AddNominatedPod adds a pod to the nominated pods of the given node.
+// addNominatedPod adds a pod to the nominated pods of the given node.
 // This is called during the preemption process after a node is nominated to run
 // the pod. We update the structure before sending a request to update the pod
 // object to avoid races with the following scheduling cycles.
-func (npm *nominator) AddNominatedPod(logger klog.Logger, pi fwk.PodInfo, nominatingInfo *framework.NominatingInfo) {
+func (npm *nominator) addNominatedPod(logger klog.Logger, pi fwk.PodInfo, nominatingInfo *framework.NominatingInfo) {
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/nominator.go:68]: why is this change needed?

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 7]
```diff
@@ -623,6 +623,16 @@ func (p *PriorityQueue) runPreEnqueuePlugin(ctx context.Context, logger klog.Log
 	return s
 }
 
+// AddNominatedPod adds a pod to the nominated pods of the given node.
+// This is called during the preemption process after a node is nominated to run
+// the pod. We update the structure before sending a request to update the pod
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: I don't understand - which structure (and in which function) do we update before sending the request? Can you please state it explicitly in the doc comment?

**Comment by macsko** [comment]
> But, how would the pod be moved to backoffQ and then popped out? The line 1019 can be reachable only when the pod is in the unschedulable pod pool. So, the pod has to be moved to backoffQ or activeQ to be poped out

`requeuePodWithQueueingStrategy()` (line 1017) in `Update()` does that.

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 8]
```diff
@@ -1006,37 +1018,51 @@ func (p *PriorityQueue) Update(logger klog.Logger, oldPod, newPod *v1.Pod) {
...
+	// which is protected by p.lock anyway.
+	p.activeQ.underLock(func(unlockedActiveQ unlockedActiveQueuer) {
+		if p.isSchedulingQueueHintEnabled {
+			// The inflight pod will be requeued using the latest version from the informer cache, which matches what the event delivers.
+			// Record this Pod update because
+			// this update may make the Pod schedulable in case it gets rejected and comes back to the queue.
+			// We can clean it up once we change updatePodInSchedulingQueue to call MoveAllToActiveOrBackoffQueue.
+			// See https://github.com/kubernetes/kubernetes/pull/125578#discussion_r1648338033 for more context.
+			if exists := unlockedActiveQ.addEventsIfPodInFlight(oldPod, newPod, events); exists {
+				logger.V(6).Info("The pod doesn't be queued for now because it's being scheduled and will be queued back if necessary", "pod", klog.KObj(newPod))
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go]:
```suggestion
				logger.V(6).Info("The pod doesn't need to be queued for now because it's being scheduled and will be queued back if necessary", "pod", klog.KObj(newPod))
```

File: test/integration/scheduler/preemption/preemption_test.go [hunk 9]
```diff
@@ -841,7 +845,10 @@ func TestAsyncPreemption(t *testing.T) {
 					preemptPodFn := preemptionPlugin.Evaluator.PreemptPod
 					preemptionPlugin.Evaluator.PreemptPod = func(ctx context.Context, c preemption.Candidate, preemptor, victim *v1.Pod, pluginName string) error {
 						// block the preemption goroutine to complete until the test case allows it to proceed.
-						if ch, ok := preemptionDoneChannels[preemptor.Name]; ok {
+						lock.Lock()
```
Comment (ania-borowiec) [inline test/integration/scheduler/preemption/preemption_test.go:848]: why do we need this lock?

**Review by ania-borowiec — COMMENTED** [review]
edit: nevermind, I forgot about the race integration tests :)

**Comment by macsko** [comment]
> Is there any way to write a test for this specific race?

I'm not sure if we need an additional test. This race is detectable by our integration tests anyway.

File: pkg/scheduler/backend/queue/nominator.go (hunk 6 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/nominator.go:68]: I don't want the `AddNominatedPod` function to be accessible from the outside (`nominator` is embedded into `AddNominatedPod`). `PriorityQueue.AddNominatedPod` should be always used from the outside.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 9 above)
Comment (macsko) [reply test/integration/scheduler/preemption/preemption_test.go:848]: See the changes to this file as unrelated to the rest.

Here, the lock had to be introduced, because `preemptionDoneChannels` map can be accessed from multiple goroutines (this `PreemptPod` method will be called in another goroutine than the tests' code).

File: pkg/scheduler/backend/queue/active_queue.go (hunk 3 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/active_queue.go:43]: Good catch

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 7 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: I adjusted the comment in `nominator.addNominatedPod`

**Comment by pohly** [comment]
Results in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/132451/pull-kubernetes-integration-race/1961019303457198080 are better than before https://testgrid.k8s.io/sig-testing-canaries#integration-race-master. Remaining failures have other reasons.

**Review by sanposhiho — APPROVED** [review]
Ok, fully understood now. The change all looks great.

/lgtm
/approve
