### PR TITLE
Periodically update pod status from kubelet.

### LINKED ISSUE #4561: Kubelet to POST pod status to apiserver
Split off #156 as a smaller more specific work item.

In the kubelet, once every N sync loops, it should POST `/api/$VERSION/namespaces/$NS/pods/$NAME/status` for each pod. 

The kubelet would do this if enabled by a flag, and emit a warning if it failed to POST the update.

The kubelet would ideally handle a 429 by retrying after the `Retry-after` header.

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This PR is based on #5205 with two bug fixes:
- deadlock in syncPodStatus
- in master.go some go-routines were referencing variables that went out of scope

This fixes #4561

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@wojtek-t

**Comment by vmarmol** [comment]
LGTM @fgrzadkowski, but it'll need a rebase :P

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1715,6 +1727,42 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
...
 }
 
+// syncStatus syncs pods statuses with the apiserver.
+func (kl *Kubelet) syncStatus() {
+	glog.V(3).Infof("Syncing pods status")
+
+	// Create the list of pods.
+	podFullNames := make(map[types.UID]string)
+	func() {
+		kl.podLock.Lock()
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: You are not writing to kl.pods, so you can use GetPods() (which does RLock()) to get a copy of kl.pods.

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1715,6 +1727,42 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
...
+		defer kl.podLock.Unlock()
+		for _, pod := range kl.pods {
+			source := pod.Annotations[ConfigSourceAnnotationKey]
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: My PR (#5401) has just been merged which enables sync status of static pods back to the apiserver. You should not need to check the source here anymore.

One caveat here is that the mirror pod at the api server may not have been created yet at the time of syncing. I think the small race window is fine for now. If we want to avoid this completely, we could look at both mirroPods and pods from kl.GetPods() to ensure the mirror pod has been created. Nonetheless, if the mirror pod gets deleted before the sync, we would still have the race. We'll just have to tolerate that.

File: pkg/kubelet/types.go [hunk 3]
```diff
@@ -68,12 +69,19 @@ type PodUpdate struct {
...
 
 // GetPodFullName returns a name that uniquely identifies a pod across all config sources.
+// NOTE: If changed ParsePodFullName must be also updated.
 func GetPodFullName(pod *api.Pod) string {
 	// Use underscore as the delimiter because it is not allowed in pod name
 	// (DNS subdomain format), while allowed in the container name format.
 	return fmt.Sprintf("%s_%s", pod.Name, pod.Namespace)
 }
 
+// ParsePodFullName parses full name generated by GetPodFullName and returns parts of it.
```
Comment (yujuhong) [inline pkg/kubelet/types.go]: I've already added a ParsePodFullName function in My PR (#5401). You'll need to remove this one.

**Comment by yujuhong** [comment]
@fgrzadkowski, you'll need to rebase because my PR (#5401) was just merged. I left some in-line comments to help you with that.

One nit. Now that we have two locks podStatusLock and podLock, which are used in multiple places, it'd be nice to point out in the comment that some use patterns may lead to deadlocks. E.g. if you grab the locks in the order of podStatusLock and podLock, it'd cause deadlock.

**Comment by yujuhong** [comment]
In fact, now that kubelet post pod statuses directly, we should be able to simply the lock usage. I'll write up another PR after this is merged, so don't worry about it.

**Comment by yujuhong** [comment]
As mentioned in #5538, you should add new integration tests for pod status, and make sure that all integration tests pass.

File: pkg/kubelet/types.go (hunk 3 above)
Comment (fgrzadkowski) [inline pkg/kubelet/types.go]: Done.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Done.

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Done.

**Comment by yujuhong** [comment]
Thanks for rebasing! The code LGTM. I'd like to see the integration test be fixed to reflect how we sync the pod status, but that could also be addressed in another PR. I'll leave it to @vmarmol to decide.

Did the PR pass e2e?

**Comment by fgrzadkowski** [comment]
Re integration tests - I'd prefer to add them in a separate PR (I already assigned myself to that issue I filed)

Re e2e tests - they pass. I checked this morning and everything worked as expected.

**Comment by vmarmol** [comment]
Another PR for the tests SGTM (we know where to find you and collect on our integration test ;) ). 

Thanks for taking a look @yujuhong!

**Comment by fgrzadkowski** [comment]
I've just noticed - that's a pretty PR number to have :D 5555

**Comment by vmarmol** [comment]
Haha you're right I didn't even notice! A good PR for that number.

File: pkg/client/pods.go [hunk 4]
```diff
@@ -113,3 +114,15 @@ func (c *pods) Watch(label labels.Selector, field fields.Selector, resourceVersi
 func (c *pods) Bind(binding *api.Binding) error {
 	return c.r.Post().Namespace(c.ns).Resource("pods").Name(binding.Name).SubResource("binding").Body(binding).Do().Error()
 }
+
+// UpdateStatus takes the name of the pod and the new status.  Returns the server's representation of the pod, and an error, if it occurs.
+func (c *pods) UpdateStatus(name string, newStatus *api.PodStatus) (result *api.Pod, err error) {
+	result = &api.Pod{}
```
Comment (smarterclayton) [inline pkg/client/pods.go]: I don't think this is the right implementation - a client should be required to send in an api.Pod to do this.

Comment (smarterclayton) [inline pkg/client/pods.go]: The reason for this is that you want to be able to force clients to deal with specifying a resource version, and this doesn't allow it (it's basically an overwrite).

Comment (smarterclayton) [inline pkg/client/pods.go]: Going to submit a pull that deals with this.

Comment (vmarmol) [inline pkg/client/pods.go]: SGTM, thanks @smarterclayton

Comment (yujuhong) [inline pkg/client/pods.go]: @smarterclayton, could you hold off on the PR to fix this? UpdateStatus needs to update the status of the mirror pods too. We'll need keep the mirror pods objects and use them here. I am working on a pod manager refactoring which will take care of this.

Comment (smarterclayton) [inline pkg/client/pods.go]: I wondered why the mirror status test is failing.  I'll wait until after your change to merge https://github.com/GoogleCloudPlatform/kubernetes/pull/5738.  Note my pull request changes SimpleRunKubelet so we can dial down the sync selector in the integration test.

----- Original Message -----
