### PR TITLE
fix e2e test apiserver endpoint and endpointslices

### LINKED ISSUE #104612: `[sig-network] EndpointSlice should have Endpoints and EndpointSlices pointing to API Server [Conformance]` E2E test fails when it shouldn't
#### What happened:

`[sig-network] EndpointSlice should have Endpoints and EndpointSlices pointing to API Server [Conformance]` E2E test fails.
The test is implemented at: https://github.com/kubernetes/kubernetes/blob/9c1f9c3962717c6078fa166eeb76242a4cc1d751/test/e2e/network/endpointslice.go#L62

#### What you expected to happen:

I would expect the test pass with these objects in place:
```
$ kubectl get ep,endpointslice 
NAME                   ENDPOINTS           AGE
endpoints/kubernetes   1.2.3.4:6443   5h

NAME                                              ADDRESSTYPE   PORTS   ENDPOINTS      AGE
endpointslice.discovery.k8s.io/kubernetes-nw6h9   IPv4          6443    1.2.3.4   5h
```

AFAIK this fulfills the general requirement of the test that there's a corresponding endpointslice object with same addressing information as is on the endpoint object.

IMO the test should rather look for epslice which is owned by the `kubernetes` endpoint rather than relying on a hardcoded name.

#### How to reproduce it (as minimally and precisely as possible):

- Add `--endpoint-reconciler-type=none` flag to kube-apiserver
- Manually create the `kubernetes` endpoint with proper addressing for the api-server
- epslice "mirroring" create new endpointslice with name like `kubernetes-xyzxyz`

--> The test fails as it's hardcoded to look for endpointslice named `kubernetes`

#### Anything else we need to know?:

I'm working on a PR to provide a fix proposal

#### Environment:
- Kubernetes version (use `kubectl version`): 1.22.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: k0s
- Network plugin and version (if this is a network-related bug): kube-router 1.3.1
- Others:

### PR DESCRIPTION
**Pull request by aojea**
The e2e test "should have Endpoints and EndpointSlices pointing to
the API Server Service" was veryfing the current endpoints
reconciler implementation on the apiservers, however, users may
disable the endpoint reconciler and create their own.

This e2e test is also a conformance test, so we should test the
behaviour and not the implementation details, so we just verify
that a kubernetes.default service exist,  an endpoint and endpoint
slices object referencing that service exist with the same endpoints.

/kind bug
/kind cleanup
/kind documentation
/kind failing-test

Fixes #104612

```release-note
conformance: the test "[sig-network] EndpointSlice should have Endpoints and EndpointSlices pointing to API Server [Conformance]" only requires that there is an EndpointSlice that references the "kubernetes.default" service, it no longer requires that its named "kubernetes".
```

### CODE REVIEW

File: test/e2e/network/endpointslice.go [hunk 1]
```diff
@@ -57,20 +57,36 @@ var _ = common.SIGDescribe("EndpointSlice", func() {
 		Description: The discovery.k8s.io API group MUST exist in the /apis discovery document.
 		The discovery.k8s.io/v1 API group/version MUST exist in the /apis/discovery.k8s.io discovery document.
 		The endpointslices resource MUST exist in the /apis/discovery.k8s.io/v1 discovery document.
-		API Server should create self referential Endpoints and EndpointSlices named "kubernetes" in the default namespace.
+		The cluster MUST have a service named "kubernetes" on the default namespace referencing the API servers.
+		The "kubernetes.default" service MUST have Endpoints and EndpointSlices pointing to each API server instance.
 	*/
-	framework.ConformanceIt("should have Endpoints and EndpointSlices pointing to API Server", func() {
+	framework.ConformanceIt("should have Endpoints and EndpointSlices pointing to the API Server Service", func() {
```
Comment (liggitt) [inline test/e2e/network/endpointslice.go:63]: I consider the conformance test in 1.22 flawed and think the check should be modified. I think changing the name of the test complicates that and isn't necessary.

File: test/e2e/network/endpointslice.go [hunk 2]
```diff
@@ -57,20 +57,36 @@ var _ = common.SIGDescribe("EndpointSlice", func() {
...
-		framework.ExpectNoError(err, "error creating EndpointSlice resource")
+
+		// verify EndpointSlices for the API servers exist
+		endpointSliceList, err := cs.DiscoveryV1().EndpointSlices(namespace).List(context.TODO(), metav1.ListOptions{
+			LabelSelector: "kubernetes.io/service-name=" + name,
+		})
+		framework.ExpectNoError(err, "error obtaining API server \"kubernetes\" EndpointSlice resource on \"default\" namespace")
+		// TODO for dual-stack apiserver we should have one EndpointSlice per each IP Family
+		// Ref: https://github.com/kubernetes/enhancements/pull/2622
+		if len(endpointSliceList.Items) != 1 {
```
Comment (liggitt) [inline test/e2e/network/endpointslice.go:86]: I wouldn't expect this to be hard-coded to 1, shouldn't this iterate and accumulate the endpoints / ports (potentially filtering by family)

File: test/e2e/network/endpointslice.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/endpointslice.go:63]: yeah, good point, renaming test is always a pain

File: test/e2e/network/endpointslice.go (hunk 2 above)
Comment (aojea) [reply test/e2e/network/endpointslice.go:86]: these slices are special since only refer to the apiserver, I think that is fair to request one object per IP family to simplify client side logic, we are not going to have more 100s apiservers and ports are hardcoded as today IIRC
The problem with IP families is that the EndpointSlice object can only be IPv4 or IPv6, in the case that we want to publish different IPs for the apiserver we have to create one per each family.

Comment (aojea) [reply test/e2e/network/endpointslice.go]: nevermind,  since we allow endpointslices reconciler outside of the cluster that is not simple to achieve, I rewrote the test to verify that the endpoint slices and the endpoints contain exactly the same IP:Port endpoints for the apiservers

File: test/e2e/network/endpointslice.go [hunk 3]
```diff
@@ -785,3 +792,56 @@ func createServiceReportErr(cs clientset.Interface, ns string, service *v1.Servi
...
+		for _, port := range subset.Ports {
+			epPorts.Insert(port.Port)
+		}
+	}
+	framework.Logf("Endpoints addresses: %v , ports: %v", epAddresses.List(), epPorts.List())
+
+	// Endpoints are single stack, and must match the primary IP family of the Service kubernetes.default
+	// However, EndpointSlices can be IPv4 or IPv6, we can only compare the Slices that match the same IP family
+	// framework.TestContext.ClusterIsIPv6() reports the IP family of the kubernetes.default service
+	isIPv6 := framework.TestContext.ClusterIsIPv6()
```
Comment (robscott) [inline test/e2e/network/endpointslice.go:818]: Tiny nit: You can replace/dedup the ifs in the loop if you add an if here. Something like this here:
```suggestion
	var addrType discoveryv1.AddressType
	if framework.TestContext.ClusterIsIPv6() {
	  addrType = discoveryv1.AddressTypeIPv6
	} else {
	  addrType = discoveryv1.AddressTypeIPv4
	}
```

Followed by this in the loop:
```go
		if slice.AddressType != addrType {
			framework.Logf("Skipping slice %s: wanted %s family, got %s", slice.Name, addrType, slice.AddressType)
			continue
		}
```

**Review by robscott — COMMENTED** [review]
Thanks for the work on this @aojea! You covered a lot of great edge cases with this one and significantly improved the test.

File: test/e2e/network/endpointslice.go (hunk 3 above)
Comment (aojea) [reply test/e2e/network/endpointslice.go:818]: much cleaner, thanks

**Comment by aojea** [comment]
/retest
> Kubernetes e2e suite: [sig-node] Probing container should have monotonically increasing restart count [NodeConformance] [Conformance]

**Comment by robscott** [comment]
Thanks!

/lgtm

File: test/e2e/network/endpointslice.go [hunk 4]
```diff
@@ -785,3 +792,57 @@ func createServiceReportErr(cs clientset.Interface, ns string, service *v1.Servi
...
+	} else {
+		addrType = discoveryv1.AddressTypeIPv4
+	}
+
+	// get the apiserver addresses from the endpoint slice list
+	sliceAddresses := sets.NewString()
+	slicePorts := sets.NewInt32()
+	for _, slice := range endpointSliceList.Items {
+		if slice.AddressType != addrType {
+			framework.Logf("Skipping slice %s: wanted %s family, got %s", slice.Name, addrType, slice.AddressType)
```
Comment (spiffxp) [inline test/e2e/network/endpointslice.go:830]: Should we be skipping or failing because the family is unexpected?

Comment (spiffxp) [reply test/e2e/network/endpointslice.go:830]: OK, I guess it's more ignoring or filtering down to what we're looking for

If the server didn't return any addresses of our expected family we'd error on not found

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
Thank you for doing this, much cleaner

**Comment by khenidak** [comment]
/retest
/lgtm
/approve

Thanks

File: test/e2e/network/endpointslice.go (hunk 4 above)
Comment (aojea) [reply test/e2e/network/endpointslice.go:830]: There is a kep to dualstack the Apiserver , in theory it should report for each family but is not clear defined, and failing means is not allowed, that is not completely correct
