### PR TITLE
Fixes #40819 and Fixes #33114

### LINKED ISSUE #33114: vSphere Cloud Provider invalid server name
Having an issue with how the vSphere provider is initialization and getting the VM name from vCenter.  Currently the provider tries to get the VM name by looking for the VM by IP address.  The issues arises here in that if you are using an overlay network, like flannel, and have multiple clusters running in the same datacenter, this method of finding the VM becomes non-deterministic.  This is because if you are lucky enough for flannel to pick IPs that are different from the other cluster, fine, you will find the right VM, but if flannel happens to pick the same IPs, which is very likely, then this method may, or may not, pick the right VM.

For example, if I have a host that has the IPs of 25.1.9.1 & 25.1.9.0 because of flannel which is configured to use a 25.1.0.0/16 network, then very easily another cluster could be spun up with flannel configured for this same network and have another host have these same IPs.

Now, when in `readInstance` we loop through the addresses of the host and then ask vCenter if it has a VM for this IP, you will now get the wrong VM returned.

I see a couple potential directions here:
1.  Allow the cloud config to specify an interface to "bind" to.  This way we don't ask the host for all IPs but just for the IPs on a specific interface.
2.  Ask vCenter if it has a VM for the hostname first, if this is returned move on.  Most of the time this will work as it is a strong convention that the VM name matches the hostname.  Albeit this is not guaranteed to always work.

If I were to choose I would think 1 would be the strongest option because it allows for the most user control over behavior.

Regardless, wanted to bring this up, as others may run in to the same thing.  Currently the only work around I have is to maintain flannel network segmentations among clusters.  This means all of my clusters now are indirectly coupled with each other and must maintain a cluster to network mapping.  This is not ideal in the long run, especially with the goal of making my clusters act as cattle as well.

### LINKED ISSUE #40819: Wrong VM name is retrieved by the vSphere Cloud Provider
**What keywords did you search in Kubernetes issues before filing this one?**: VMware, vSphere, IP, UUID

---

BUG REPORT. 

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: VMware vSphere 6.5.0
- **OS** : Debian GNU/Linux 8.7 (jessie)
- **Kernel** :` Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`
- **Install tools**: Kargo

**What happened**:

Some containers were launched on a node with a name containing the hostname of a different node and the `kubelet_node_status.go` does not retrieve the right node name :

```
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.953239    1060 kubelet_node_status.go:74] Attempting to register node k8s.minionpp-02
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972697    1060 kubelet_node_status.go:113] Node k8s.minionpp-02 was previously registered
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972783    1060 kubelet_node_status.go:77] Successfully registered node k8s.minionpp-02
```

Here `k8s.minionpp-02` is retrieved instead of `k8s.minionpp-01`.

When using the VSphere Cloud provider, the node name is retrieved from the `getVMName` function in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L204. 

Since this PR (https://github.com/kubernetes/kubernetes/pull/27331/files), the node data are retrieved based on the IP address instead of the UUID. The function gets all the IP address and check if one of the IP on any interface matches a VM on vSphere. The problem is that the docker0 interface has the same IP on all the nodes (usually 172.17.0.1) and this IP is referenced into VMware. As this IP may be the first to appear in the [addr list](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L205) it will match the first VM that vSphere gives with the [FindByIp](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L100) function and this can be any VM running Docker on vSphere. Thus, the provider has a big chance to not get the informations for the VM it is running on, leading to an inconsistent state in the cluster (wrong pod name for example). 

**Anything else we need to know**:

An idea would be to first retrieve the VM name with the [FindByDnsName](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L59) function and if no results use the IP address (and add an exclusion to not use the `docker0` interface).  What do you think ? If you think this might be the right way to do, we can try to propose the PR.

Thanks for your feedback.

### PR DESCRIPTION
**Pull request by robdaemon**
**What this PR does / why we need it**:

Start looking up the virtual machine by it's UUID in vSphere again. Looking up by IP address is problematic and can either not return a VM entirely, or could return the wrong VM.

Retrieves the VM's UUID in one of two methods - either by a `vm-uuid` entry in the cloud config file on the VM, or via sysfs. The sysfs route requires root access, but restores the previous functionality.

Multiple VMs in a vCenter cluster can share an IP address - for example, if you have multiple VM networks, but they're all isolated and use the same address range. Additionally, flannel network address ranges can overlap.

vSphere seems to have a limitation of reporting no more than 16 interfaces from a virtual machine, so it's possible that the IP address list on a VM is completely untrustworthy anyhow - it can either be empty (because the 16 interfaces it found were veth interfaces with no IP address), or it can report the flannel IP.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #40819
Fixes #33114

**Special notes for your reviewer**:

**Release note**:

```release-note
Reverts to looking up the current VM in vSphere using the machine's UUID, either obtained via sysfs or via the `vm-uuid` parameter in the cloud configuration file.
```

### CODE REVIEW

**Comment by kerneltime** [comment]
CC @BaluDontu @divyenpatel

**Comment by kerneltime** [comment]
Corresponding documentation needs a PR https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/getting-started-guides/vsphere.md

**Comment by kerneltime** [comment]
We should add support for this https://github.com/kubernetes/kubernetes-anywhere/blob/master/phase1/vsphere/vSphere.jsonnet#L82

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 1]
```diff
@@ -42,6 +41,8 @@ import (
 	"github.com/vmware/govmomi/vim25/types"
 	"golang.org/x/net/context"
 
+	"io/ioutil"
```
Comment (kerneltime) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Can this be moved along with other golang imports

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 2]
```diff
@@ -201,14 +205,26 @@ func init() {
...
 func getVMName(client *govmomi.Client, cfg *VSphereConfig) (string, error) {
-	addrs, err := net.InterfaceAddrs()
-	if err != nil {
-		return "", err
+	var vmUUID string
+
+	if cfg.Global.VMUUID != "" {
+		vmUUID = cfg.Global.VMUUID
+	} else {
+		vmUUIDbytes, err := ioutil.ReadFile("/sys/devices/virtual/dmi/id/product_uuid")
```
Comment (kerneltime) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Add a comment that this needs appropriate privilidges

**Comment by kerneltime** [comment]
Apart from unit testing were any other tests performed? Would be good to know.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 3]
```diff
@@ -122,12 +123,15 @@ type VSphereConfig struct {
 		WorkingDir string `gcfg:"working-dir"`
 		// Soap round tripper count (retries = RoundTripper - 1)
 		RoundTripperCount uint `gcfg:"soap-roundtrip-count"`
+		// VMUUID is the virtual machine's UUID. If not set, will be fetched from the machine.
```
Comment (pdhamdhere) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: We have many UUIDs! How about following;

// VM Instance UUID of virtual machine which can be retrieved from instanceUuid property in VmConfigInfo, or also set as vc.uuid in VMX file) ?

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 2 above)
Comment (pdhamdhere) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Can this path change in different linux distros?

**Comment by kerneltime** [comment]
Fixes #33114 
Hopefully Github will pick up the issue else can you extend the fixes line on your initial comment to include #33114

**Comment by MrTrustor** [comment]
Thank you for the fix! Does this have any chance to be backported in the 1.5 branch?
cc @cvauvarin

**Comment by robdaemon** [comment]
@kerneltime - I tested this on a vSphere 6.0 cluster - both by specifying the ID in the config, by running it without that (as root) and running it as non-root. It behaves as expected.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 2 above)
Comment (robdaemon) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Not that I'm aware of. sysfs is kernel-level, not distro-level. Someone please correct me if I'm wrong :)

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 3 above)
Comment (robdaemon) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: done - merged your comment with the existing one.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 2 above)
Comment (robdaemon) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: done

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 1 above)
Comment (robdaemon) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: done

**Comment by robdaemon** [comment]
@kerneltime Docs PR is kubernetes/kubernetes.github.io#2416

**Review by kerneltime — APPROVED** [review]

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 4]
```diff
@@ -201,14 +206,27 @@ func init() {
...
-	addrs, err := net.InterfaceAddrs()
-	if err != nil {
-		return "", err
+	var vmUUID string
+
+	if cfg.Global.VMUUID != "" {
+		vmUUID = cfg.Global.VMUUID
+	} else {
+		// This needs root privileges on the host, and will fail otherwise.
+		vmUUIDbytes, err := ioutil.ReadFile("/sys/devices/virtual/dmi/id/product_uuid")
```
Comment (kerneltime) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: This path can be made configurable and defaulted to this value. This way any distro specific concerns can be addressed by an optional item in the config passed in.

**Comment by kerneltime** [comment]
@k8s-bot ok to test

**Comment by kerneltime** [comment]
@roberthbailey this needs a LGTM

**Comment by robdaemon** [comment]
That failure looks unrelated to my change?

**Comment by kerneltime** [comment]
@k8s-bot gci gce e2e test this

**Comment by roberthbailey** [comment]
@kerneltime - I added you as an assignee so you should be able to lgtm now

**Comment by roberthbailey** [comment]
@robdaemon - we generally ask folks to squash their commits after addressing review feedback. If you feel this is ready to merge please squash it into a single commit.

**Comment by robdaemon** [comment]
@roberthbailey - squashed! Thanks!
