### PR TITLE
Extracting out the code to versionize docs from mark-new-version and fixing a bunch of issues

### LINKED ISSUE #11676: `mark_new_version.sh` busted for `.0` patch releases
If you try mimicking the release flow for a `.0` release on `master` right now, it's busted:

```
zml@zml:~/kubernetes$ build/mark-new-version.sh v99.99.0
+++ Versioning documentation and examples
+++ [0721 14:54:35] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [0721 14:54:44] Placing binaries
docs/README.md
----
analytics:
contents were modified

docs/admin/README.md
[...]
+++ [0721 14:54:50] Building apiserver
+++ [0721 14:54:50] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [0721 14:55:00] Placing binaries
etcd -data-dir /tmp/test-etcd.jJa4J1 --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null
Waiting for etcd to come up.
+++ [0721 14:55:00] On try 1, etcd: : 
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0721 14:55:02] Starting kube-apiserver
+++ [0721 14:55:02] On try 2, apiserver: : ok
+++ [0721 14:55:02] Updating 
    build/../hack/../api/swagger-spec
+++ [0721 14:55:02] SUCCESS
+++ [0721 14:55:02] Clean up complete
Checking that it builds... OK

Checking for files that need gofmt... OK

Checking for files that need boilerplate... OK

Checking for API descriptions... OK

Checking for docs that need updating... FAIL: changes needed but not made due to --verify
ERROR!
Some docs are out of sync between CLI and markdown.
To regenerate docs, run:
  hack/run-gendocs.sh

Checking for conversions that need updating... 
```

If I generate a dummy commit out of that failure, then run `hack/run-gendocs.sh` to see what gets generated, it's `mungedocs` attempting to actually add the unversioned warnings back in:

```
diff --git a/docs/README.md b/docs/README.md
index f6c55b6..6a53706 100644
--- a/docs/README.md
+++ b/docs/README.md
@@ -1,5 +1,33 @@
 <!-- BEGIN MUNGE: UNVERSIONED_WARNING -->
 
+<!-- BEGIN STRIP_FOR_RELEASE -->
+
+<img src="http://kubernetes.io/img/warning.png" alt="WARNING"
+     width="25" height="25">
+<img src="http://kubernetes.io/img/warning.png" alt="WARNING"
+     width="25" height="25">
+<img src="http://kubernetes.io/img/warning.png" alt="WARNING"
+     width="25" height="25">
+<img src="http://kubernetes.io/img/warning.png" alt="WARNING"
+     width="25" height="25">
+<img src="http://kubernetes.io/img/warning.png" alt="WARNING"
+     width="25" height="25">
+
+<h2>PLEASE NOTE: This document applies to the HEAD of the source tree</h2>
+
+If you are using a released version of Kubernetes, you should
+refer to the docs that go with that version.
+
+<strong>
+The latest 1.0.x release of this document can be found
+[here](http://releases.k8s.io/release-1.0/docs/README.md).
+
+Documentation for other releases can be found at
+[releases.k8s.io](http://releases.k8s.io).
+</strong>
+--
+
+<!-- END STRIP_FOR_RELEASE -->
```

I was trying to write up a PR to enact something for #11495, but this blocks the `.0` release piece for that. Which is fine, we have some time.

### PR DESCRIPTION
**Pull request by nikhiljindal**
Extracting out the relevant code to versionize our docs into a separate script.
Have also added a script to verify that running versionize-docs multiple times does not produce any diffs.
Apart from the refactoring, this PR fixes the following issues as well:
- Fixed HTML_PREVIEW_PREFIX regex, so that HEAD in htmlpreview links is now replaced appropriately.
- Updated the IS_VERSIONED tag to be enclosed in "BEGIN MUNGE" and "END MUNGE" tags, so that it is not stripped off by gendocs (Right now, gendocs strips off IS_VERSIONED and hence all our versioned kubectl docs contain the unversioned warnings)
- Fixed analytics munger to not delete line breaks which it should not. Also, added a relevant test case. (Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/11676)
- Changed the ordering of mungedocs, so that checkHeaderLines mungedoc is run after unversioned warning is added, so that it can add line breaks after unversioned warnings.

Original description:
Extracted the relevant code to a separate script.
This PR also includes a temporary commit produced by running versionize-docs.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @lavalamp @zmerlynn @brendandburns

**Comment by lavalamp** [comment]
The new script looks great-- but it doesn't work on your new preview links.

**Comment by lavalamp** [comment]
Specifically links like this one should have gotten changed:

https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/HEAD/docs/api-reference/definitions.html#_v1_node

**Comment by zmerlynn** [comment]
You can make preview commits by pushing a separate personal branch - that would make this PR mergeable.

**Comment by zmerlynn** [comment]
I'm now OOO until morning.. It looks reasonable but make sure mark_new_version didn't get broken in the process.

**Comment by thockin** [comment]
Looks obvious, but the analytics change seems unrelated?

**Comment by nikhiljindal** [comment]
The analytics mungedocs was deleting empty lines in front of ', which wasnt looking nice in the docs.
The change in that file is not to delete empty lines as per the comment I received here: https://github.com/nikhiljindal/kubernetes/commit/cd6e83410f67a9ee039ec5d4fb3315a861cb84a7#commitcomment-12263778

If required, I can move that change to a different PR.

**Comment by thockin** [comment]
I'm fine with it.

**Comment by nikhiljindal** [comment]
Updated code as per comments.
PTAL.
Will delete the second commit, when I get an LGTM

**Comment by thockin** [comment]
I can't final review right now.  @lavalamp

**Comment by lavalamp** [comment]
Looking.

**Comment by lavalamp** [comment]
Question-- why do we run mungedocs on the stripped docs??

**Comment by nikhiljindal** [comment]
Have added the suggested test case to cmd/mungedocs/analytics_test.go and have removed the second commit, so that this PR is now ready to be merged.

**Comment by zmerlynn** [comment]
What's going on with this commit? Why is @k8s-bot constantly testing it?

**Comment by nikhiljindal** [comment]
Sorry I think k8s-bot is rerunning the test, each time I update my commit.

**Comment by zmerlynn** [comment]
Oh, so you ARE re-pushing over and over again. :)

**Comment by nikhiljindal** [comment]
Is there a way to stop k8s-bot until I am ready?

**Comment by nikhiljindal** [comment]
Have fixed all comments as discussed.
Running versionize-docs repeatedly does not produce any diffs now. Have also added a script to verify that.
Apart from the refactoring, this PR fixes the following issues as well:
- Fixed HTML_PREVIEW_PREFIX regex, so that HEAD in htmlpreview links is now replaced appropriately.
- Updated the IS_VERSIONED tag to be enclosed in "BEGIN MUNGE" and "END MUNGE" tags, so that it is not stripped off by gendocs (Right now, gendocs strips off IS_VERSIONED and hence all our versioned kubectl docs contain the unversioned warnings)
- Fixed analytics munger to not delete line breaks which it should not. Also, added a relevant test case.
- Changed the ordering of mungedocs, so that checkHeaderLines mungedoc is run after unversioned warning is added, so that it can add line breaks after unversioned warnings.

PTAL

File: cmd/mungedocs/analytics_test.go [hunk 1]
```diff
@@ -27,53 +27,50 @@ func TestAnalytics(t *testing.T) {
...
-[![Analytics](https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/path/to/file-name.md?pixel)]()
-` + endMungeTag("GENERATED_ANALYTICS") + `
-`, `aoeu
-
-
-` + beginMungeTag("GENERATED_ANALYTICS") + `
-[![Analytics](https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/path/to/file-name.md?pixel)]()
-` + endMungeTag("GENERATED_ANALYTICS") + `
-`},
+		{"aoeu", "aoeu" + "\n" + "\n" + "\n" +
```
Comment (lavalamp) [inline cmd/mungedocs/analytics_test.go]: Can you insert a newline after the { so that the indentation will be consistent between the two strings? It's very hard to read right now.

File: hack/verify-versionize-docs.sh [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+cp -a "${DOCS_ROOT}" "${TMP_ORIGINAL_ROOT}"
+cp -a "${EXAMPLES_ROOT}" "${TMP_ORIGINAL_ROOT}"
+mkdir "${TMP_ORIGINAL_ROOT}pkg"
+cp -a "${API_ROOT}" "${TMP_ORIGINAL_ROOT}pkg"
+mkdir "${TMP_ORIGINAL_ROOT}api"
+cp -a "${SWAGGER_SPEC_ROOT}" "${TMP_ORIGINAL_ROOT}api"
+
+# Run versionize-docs.
+echo "Running versionize-docs for the first time"
+${KUBE_ROOT}/build/versionize-docs.sh v1 >/dev/null
```
Comment (lavalamp) [inline hack/verify-versionize-docs.sh]: Having some sort of test for this script is probably good.

But it seems kind of bad to have the test mutate the repo itself.

My suggestion is to make a copy, run versionize on the copy, and then run `mungedocs --verify` on the copy. My original (poorly worded!) complaint was that I had to run mungedocs after running versionize to get it to settle down. Sorry for the confusion!

Comment (nikhiljindal) [inline hack/verify-versionize-docs.sh]: Yea that is what I tried first, but none of these scripts support an OUTPUT_DIR. Looking around, the tests for those scripts do the same thing as I have done with this one i.e copy the original files that will be mutated by the script, run the script to mutate the repo, do the comparison and then copy back the original files.
So I assumed its an accepted pattern :)

If you do want me to change the test, I think that will be a big enough change, which I will prefer to do in a separate PR. I can remove the test file from this PR for now, and send a separate PR with the tests redone? Or we can submit this as is and improve it later?

File: cmd/mungedocs/analytics_test.go (hunk 1 above)
Comment (nikhiljindal) [inline cmd/mungedocs/analytics_test.go]: Done

File: cmd/mungedocs/mungedocs.go [hunk 3]
```diff
@@ -46,10 +46,10 @@ Examples:
 	// TODO: allow selection from command line. (e.g., just check links in the examples directory.)
 	allMunges = []munge{
 		{"table-of-contents", updateTOC},
+		{"unversioned-warning", updateUnversionedWarning},
```
Comment (lavalamp) [inline cmd/mungedocs/mungedocs.go]: just curious: why the reordering?

File: hack/verify-versionize-docs.sh (hunk 2 above)
Comment (lavalamp) [inline hack/verify-versionize-docs.sh]: > remove the test file from this PR for now, and send a separate PR with the tests redone

SGTM

File: cmd/mungedocs/mungedocs.go (hunk 3 above)
Comment (nikhiljindal) [inline cmd/mungedocs/mungedocs.go]: checkHeaderLines needs to run after this.
It adds blank lines above headings, but then this adds unversionedWarnings which messes up with those blank lines.

File: hack/verify-versionize-docs.sh (hunk 2 above)
Comment (nikhiljindal) [inline hack/verify-versionize-docs.sh]: Removed

**Comment by nikhiljindal** [comment]
Removed the test script and reverted the shippable change.
PTAL.

File: build/versionize-docs.sh [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+    echo "Usage: versionize-docs <release-version>"
+    exit
+fi
+
+SED=sed
+if which gsed &>/dev/null; then
+  SED=gsed
+fi
+if ! ($SED --version 2>&1 | grep -q GNU); then
+  echo "!!! GNU sed is required.  If on OS X, use 'brew install gnu-sed'."
```
Comment (lavalamp) [inline build/versionize-docs.sh]: exit 1?

File: build/versionize-docs.sh [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+set -o nounset
+set -o pipefail
+
+KUBE_ROOT=$(dirname "${BASH_SOURCE}")/..
+
+NEW_VERSION=${1-}
+
+if [ "$#" -lt 1 ]; then
+    echo "Usage: versionize-docs <release-version>"
+    exit
```
Comment (lavalamp) [inline build/versionize-docs.sh]: exit 1?

**Comment by lavalamp** [comment]
Just tiny nits-- sorry I didn't notice earlier.

File: build/versionize-docs.sh (hunk 4 above)
Comment (nikhiljindal) [inline build/versionize-docs.sh]: Done

File: build/versionize-docs.sh (hunk 5 above)
Comment (nikhiljindal) [inline build/versionize-docs.sh]: Done

**Comment by nikhiljindal** [comment]
Nice catch!
Thanks for pointing that out.
Have updated the code. PTAL.

**Comment by lavalamp** [comment]
lgtm, thanks

**Comment by nikhiljindal** [comment]
cc @vishh all green :)
