### PR TITLE
Fix NODE_INSTANCE_GROUPS resolution in GKE to only

### LINKED ISSUE #27692: kubernetes-e2e-gke-multizone perma-broken on 6/18/2016
The test job was passing consistently until midday on 6/18, e.g.

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-multizone/3736/

Then it started failing consistently, e.g:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-multizone/3737/

... with this error:

12:31:41 ... in gke:detect-node-instance-groups()
12:31:42 ERROR: (gcloud.compute.instance-groups.managed.list-instances) Some requests did not succeed:
12:31:42  - The resource 'projects/k8s-jkns-e2e-gke-multizone/zones/us-central1-f/instanceGroupManagers/gke-jenkins-e2e-default-pool-a48ce2c4-grp' was not found
12:31:42 

Assigning to @fejta and @roberthbailey to triage and assign someone to fix.

### PR DESCRIPTION
**Pull request by fabioy**
[Analytics]()

Fix NODE_INSTANCE_GROUPS resolution in GKE to only include single cluster groups. 
Add NODE_INSTANCE_GROUPS_URLS for multi-zone groups.

fixes #27692

### CODE REVIEW

File: cluster/gke/util.sh [hunk 1]
```diff
@@ -293,8 +293,10 @@ function detect-node-names {
 
 # Detect instance group name generated by gke.
 #
-# Note that this will only select instance groups in the same zone as the
-# cluster, meaning that it won't include all groups in a multi-zone cluster.
+# Note that the NODE_INSTANCE_GROUPS var will only have instance groups in the
+# same zone as the cluster, meaning that it won't include all groups in a
+# multi-zone cluster. The NODE_INSTANCE_GROUPS_URLS will contain all the
```
Comment (a-robinson) [inline cluster/gke/util.sh]: ALL_INSTANCE_GROUP_URLS, perhaps? Otherwise anyone that doesn't read the comment will assume they're the same. Or perhaps they shouldn't even be exposed outside of the method if they aren't used?

File: cluster/gke/util.sh [hunk 2]
```diff
@@ -303,15 +305,20 @@ function detect-node-names {
...
   echo "... in gke:detect-node-instance-groups()" >&2
   local urls=$("${GCLOUD}" ${CMD_GROUP:-} container clusters describe \
     --project="${PROJECT}" --zone="${ZONE}" \
     --format='value(instanceGroupUrls)' "${CLUSTER_NAME}")
   urls=(${urls//;/ })
+  NODE_INSTANCE_GROUPS_URLS=${urls[*]}
   NODE_INSTANCE_GROUPS=()
   for url in "${urls[@]:-}"; do
-    NODE_INSTANCE_GROUPS+=("${url##*/}")
+    local instance_url=$(expr match ${url} '.*/zones/\([a-z0-9-]*\)/')
```
Comment (a-robinson) [inline cluster/gke/util.sh]: `instance_url` seems like a weird name for this given that it's more like the zone of the MIG?

File: cluster/gke/util.sh (hunk 1 above)
Comment (fabioy) [inline cluster/gke/util.sh]: Done.

File: cluster/gke/util.sh (hunk 2 above)
Comment (fabioy) [inline cluster/gke/util.sh]: Done.

**Comment by a-robinson** [comment]
LGTM

**Comment by cjcullen** [comment]
This breaks testing GKE on a mac:

```
expr: syntax error
```

Trying to find out why now.

**Comment by cjcullen** [comment]
Looks like BSD `expr` doesn't support the match command (`expr match expr1 expr2`). It has `expr expr1 : expr2` instead.

**Comment by cjcullen** [comment]
Gnu expr has both. From the manpage:
```
       STRING : REGEXP
              anchored pattern match of REGEXP in STRING

       match STRING REGEXP
              same as STRING : REGEXP
```

I'll send out a PR
