### PR TITLE
Fix kubeadm upgrade ignores HighAvailability feature gate

### LINKED ISSUE #731: upgrade ignores HighAvailability feature gate
Choose one: BUG REPORT

I have the `HighAvailability` feature gate enabled in my kubeadm configuration file. On `kubeadm init`, that added `--endpoint-reconciler-type=lease` to the kube-apiserver static pod. After running `kubeadm upgrade` with the same configuration file, that option is gone.

## Versions

**kubeadm version** (use `kubeadm version`): 1.9.4

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.9.3
- **Cloud provider or hardware configuration**: Vagrant with VirtualBox
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- **Kernel** (e.g. `uname -a`):  Linux vagrant-kubernetes-master1 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?

Before upgrade:
```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --endpoint-reconciler-type=lease
```

After upgrade:

```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
```

## What you expected to happen?

After upgrade:
```
[root@vagrant-kubernetes-master1 etc]# grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --endpoint-reconciler-type=lease
```

## How to reproduce it (as minimally and precisely as possible)?

* Create kubeadm.yaml:
```
kind: MasterConfiguration

networking:
  podSubnet: 10.244.0.0/16

featureGates:
  HighAvailability: true
```

* `kubeadm init --config /etc/kubernetes/kubeadm.yaml`
* `grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml`: shows option
* Install CNI to make node ready: `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml`
* Wait for node to become ready: `kubectl get nodes -w`
* `kubeadm upgrade --yes --config /etc/kubernetes/kubeadm.yaml apply v1.9.4`
* `grep endpoint-reconciler-type /etc/kubernetes/manifests/kube-apiserver.yaml`: no output

## Anything else we need to know?

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR fixes https://github.com/kubernetes/kubeadm/issues/731

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubeadm/issues/731

**Special notes for your reviewer**:
The problem is a regression introduced by [#55952](https://github.com/kubernetes/kubernetes/pull/55952) which added a --feature-gates 
flag to `kubeadm upgrade`, to be used for updating feature gates during the upgrade process (so it is update + upgrade). 

The original implementation always override the actual feature gates with the flag value, even when the flag is not set; this PR fixes this behaviour making `kubeadm upgrade` considers the flag value only if set, otherwise actual feature gates will be preserved.

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-cluster-lifecycle-bugs 

**Release note**:
```release-note
Fixed #731 kubeadm upgrade ignores HighAvailability feature gate
```

### CODE REVIEW

**Comment by kargakis** [comment]
Do we also need this change for `kubeadm init` too?

**Comment by kargakis** [comment]
Also can you add a unit test?

File: cmd/kubeadm/app/cmd/upgrade/common.go [hunk 1]
```diff
@@ -70,16 +70,19 @@ func enforceRequirements(flags *cmdUpgradeFlags, dryRun bool, newK8sVersion stri
 		cfg.KubernetesVersion = newK8sVersion
 	}
 
+	// If features gates are passed to the command line, use it (otherwise use featureGates from configuration)
```
Comment (xiangpengzhao) [inline cmd/kubeadm/app/cmd/upgrade/common.go]: It'd be good to tell users this in the flag's description. They should know the behavior, IMO.

**Comment by fabriziopandini** [comment]
@kargakis 
> Do we also need this change for kubeadm init too?
No; in kubeadm init flags and config are mutually exclusive, so there is no risk of conflict

File: cmd/kubeadm/app/cmd/upgrade/common.go (hunk 1 above)
Comment (timothysc) [reply cmd/kubeadm/app/cmd/upgrade/common.go]: Agreed, but I'm not going to block on this and with the overhaul coming to CLI+phases+Config we will add that documentation. 

/cc @liztio @fabriziopandini

**Review by timothysc — APPROVED** [review]
/lgtm
/approve
