### PR TITLE
cloud service controller stops reporting events in the informer's event handlers

### LINKED ISSUE #128121: Crash on kube manager's service-lb-controller after v1.31.0
### What happened?

If kube manager is started with no `cloud-provider`, it looks like the service-lb-controller is instantiated but not started. However, part of its initialization happens on the `Run` method **and** its handlers are added to the informer on instantiation. So the handlers still run and it crashes when they do because there is stuff not initialized, like in this case, the event recorder:
```2024-10-14T11:27:20.573127782Z stderr F 	goroutine 735 [running]:
2024-10-14T11:27:20.573132561Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x38432a0, 0x5545b00}, {0x2d99000, 0x5480790})
2024-10-14T11:27:20.573137951Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
2024-10-14T11:27:20.573154772Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x38432a0, 0x5545b00}, {0x2d99000, 0x5480790}, {0x5545b00, 0x0, 0x43d945?})
2024-10-14T11:27:20.573159501Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
2024-10-14T11:27:20.573187343Z stderr F 	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001e5ec40?})
2024-10-14T11:27:20.573192182Z stderr F 		k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
2024-10-14T11:27:20.57319655Z stderr F 	panic({0x2d99000?, 0x5480790?})
2024-10-14T11:27:20.573200548Z stderr F 		runtime/panic.go:770 +0x132
2024-10-14T11:27:20.573204836Z stderr F 	k8s.io/cloud-provider/controllers/service.(*Controller).needsUpdate(0xc000978000, 0xc00324c288, 0xc000cf3688)
2024-10-14T11:27:20.573210016Z stderr F 		k8s.io/cloud-provider/controllers/service/controller.go:606 +0xcbb
2024-10-14T11:27:20.573214644Z stderr F 	k8s.io/cloud-provider/controllers/service.New.func2({0x326c8e0?, 0xc00324c288?}, {0x326c8e0, 0xc000cf3688?})
2024-10-14T11:27:20.573219133Z stderr F 		k8s.io/cloud-provider/controllers/service/controller.go:144 +0x74
2024-10-14T11:27:20.573224062Z stderr F 	k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
2024-10-14T11:27:20.573228831Z stderr F 		k8s.io/client-go/tools/cache/controller.go:253
2024-10-14T11:27:20.573233339Z stderr F 	k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2024-10-14T11:27:20.573237758Z stderr F 		k8s.io/client-go/tools/cache/shared_informer.go:976 +0xea
2024-10-14T11:27:20.573241875Z stderr F 	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
2024-10-14T11:27:20.57326562Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
2024-10-14T11:27:20.573270419Z stderr F 	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00311cf70, {0x380e700, 0xc001e3a8a0}, 0x1, 0xc001e3e780)
2024-10-14T11:27:20.573274767Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
2024-10-14T11:27:20.573279556Z stderr F 	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001e5a770, 0x3b9aca00, 0x0, 0x1, 0xc001e3e780)
2024-10-14T11:27:20.573284085Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
2024-10-14T11:27:20.573288433Z stderr F 	k8s.io/apimachinery/pkg/util/wait.Until(...)
2024-10-14T11:27:20.573292821Z stderr F 		k8s.io/apimachinery/pkg/util/wait/backoff.go:161
2024-10-14T11:27:20.573297059Z stderr F 	k8s.io/client-go/tools/cache.(*processorListener).run(0xc000892d80)
2024-10-14T11:27:20.573302339Z stderr F 		k8s.io/client-go/tools/cache/shared_informer.go:972 +0x69
2024-10-14T11:27:20.573306677Z stderr F 	k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2024-10-14T11:27:20.573310975Z stderr F 		k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x52
2024-10-14T11:27:20.573315874Z stderr F 	created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 690
2024-10-14T11:27:20.573320913Z stderr F 		k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x73
```

Might have been introduced with 
https://github.com/kubernetes/kubernetes/commit/50c12437604b0cd5a73514389409fc2fde8b91bd

### What did you expect to happen?

No crash.

### How can we reproduce it (as minimally and precisely as possible)?

```
❯ kind create cluster --name ovn
Creating cluster "ovn" ...
 ✓ Ensuring node image (kindest/node:v1.31.0) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-ovn"
You can now use your cluster with:

kubectl cluster-info --context kind-ovn

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/

❯ kind export kubeconfig --name ovn
Set kubectl context to "kind-ovn"

❯ kubectl get pods -A                                                                           
NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
kube-system          coredns-6f6b679f8f-2xrm5                    1/1     Running   0          2m57s
kube-system          coredns-6f6b679f8f-zpkp2                    1/1     Running   0          2m57s
kube-system          etcd-ovn-control-plane                      1/1     Running   0          3m6s
kube-system          kindnet-22kmz                               1/1     Running   0          2m58s
kube-system          kube-apiserver-ovn-control-plane            1/1     Running   0          3m5s
kube-system          kube-controller-manager-ovn-control-plane   1/1     Running   0          3m5s
kube-system          kube-proxy-8z75j                            1/1     Running   0          2m58s
kube-system          kube-scheduler-ovn-control-plane            1/1     Running   0          3m5s
local-path-storage   local-path-provisioner-57c5987fd4-sgvtl     1/1     Running   0          2m57s

❯ cat service.yaml                                                  
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer

❯ kubectl apply -f service.yaml    
service/example-service created

❯ kubectl get pods -A           
NAMESPACE            NAME                                        READY   STATUS    RESTARTS   AGE
kube-system          coredns-6f6b679f8f-2xrm5                    1/1     Running   0          5m15s
kube-system          coredns-6f6b679f8f-zpkp2                    1/1     Running   0          5m15s
kube-system          etcd-ovn-control-plane                      1/1     Running   0          5m24s
kube-system          kindnet-22kmz                               1/1     Running   0          5m16s
kube-system          kube-apiserver-ovn-control-plane            1/1     Running   0          5m23s
kube-system          kube-controller-manager-ovn-control-plane   1/1     Running   0          5m23s
kube-system          kube-proxy-8z75j                            1/1     Running   0          5m16s
kube-system          kube-scheduler-ovn-control-plane            1/1     Running   0          5m23s
local-path-storage   local-path-provisioner-57c5987fd4-sgvtl     1/1     Running   0          5m15s

❯ kubectl patch service example-service -p '{"spec":{"externalTrafficPolicy":"Local"}}'
service/example-service patched

❯ kubectl get pods -A                                                                  
NAMESPACE            NAME                                        READY   STATUS    RESTARTS     AGE
...
kube-system          kube-controller-manager-ovn-control-plane   0/1     Running   1 (2s ago)   6m25s
...
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

If kube manager is started with no cloud-provider, it looks like the service-lb-controller fails to be instantiated but its handlers are added to the informer on instantiation. A part of its initialization happens on the Run method. because the recorder is nil, the event handler will panic. 

The event handler shouldn't be registered. It is detected with https://github.com/kubernetes/kubernetes/commit/50c12437604b0cd5a73514389409fc2fde8b91bd. I open another PR to fix it, see https://github.com/kubernetes/kubernetes/pull/128182

This PR removes the event recorder from event handlers.

#### Which issue(s) this PR fixes:

Fixes #128121

#### Does this PR introduce a user-facing change?

```release-note
Fixes a bug in the `k8s.io/cloud-provider/service`  controller, it may panic when a service is updated because the event recorder was used before it was initialized. All cloud providers should using the `v1.31.0` cloud provider service controller must ensure that the controllers is initialized before the informer start to process events or update it to the version 1.32.0.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
Test result:

```
(base) ➜  kubernetes git:(fix-128121) kind create cluster --name fix-128121 --image kindest/node:fix-128121
Creating cluster "fix-128121" ...
 ✓ Ensuring node image (kindest/node:fix-128121) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-fix-128121"
You can now use your cluster with:

kubectl cluster-info --context kind-fix-128121

Thanks for using kind! 😊
(base) ➜  kubernetes git:(fix-128121) kubectl create -f __testdata/service.yaml
service/example-service created
(base) ➜  kubernetes git:(fix-128121) kubectl get pods -A
NAMESPACE            NAME                                               READY   STATUS    RESTARTS   AGE
kube-system          coredns-7c65d6cfc9-b5m2v                           1/1     Running   0          3m45s
kube-system          coredns-7c65d6cfc9-lgvvs                           1/1     Running   0          3m45s
kube-system          etcd-fix-128121-control-plane                      1/1     Running   0          3m54s
kube-system          kindnet-gw5fm                                      1/1     Running   0          3m46s
kube-system          kube-apiserver-fix-128121-control-plane            1/1     Running   0          3m55s
kube-system          kube-controller-manager-fix-128121-control-plane   1/1     Running   0          3m53s
kube-system          kube-proxy-mb7v8                                   1/1     Running   0          3m46s
kube-system          kube-scheduler-fix-128121-control-plane            1/1     Running   0          3m53s
local-path-storage   local-path-provisioner-57c5987fd4-nbghr            1/1     Running   0          3m45s
(base) ➜  kubernetes git:(fix-128121) kubectl patch service example-service -p '{"spec":{"externalTrafficPolicy":"Local"}}'
service/example-service patched
(base) ➜  kubernetes git:(fix-128121) kubectl get pods -A
NAMESPACE            NAME                                               READY   STATUS    RESTARTS   AGE
kube-system          coredns-7c65d6cfc9-b5m2v                           1/1     Running   0          4m4s
kube-system          coredns-7c65d6cfc9-lgvvs                           1/1     Running   0          4m4s
kube-system          etcd-fix-128121-control-plane                      1/1     Running   0          4m13s
kube-system          kindnet-gw5fm                                      1/1     Running   0          4m5s
kube-system          kube-apiserver-fix-128121-control-plane            1/1     Running   0          4m14s
kube-system          kube-controller-manager-fix-128121-control-plane   1/1     Running   0          4m12s
kube-system          kube-proxy-mb7v8                                   1/1     Running   0          4m5s
kube-system          kube-scheduler-fix-128121-control-plane            1/1     Running   0          4m12s
local-path-storage   local-path-provisioner-57c5987fd4-nbghr            1/1     Running   0          4m4s
```

**Comment by carlory** [comment]
Test on master: kube-controller-manager crash

```
(base) ➜  kubernetes git:(master) kind create cluster --name master --image kindest/node:master
Creating cluster "master" ...
 ✓ Ensuring node image (kindest/node:master) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-master"
You can now use your cluster with:

kubectl cluster-info --context kind-master

Have a nice day! 👋
(base) ➜  kubernetes git:(master) kubectl create -f __testdata/service.yaml
service/example-service created
(base) ➜  kubernetes git:(master) kubectl patch service example-service -p '{"spec":{"externalTrafficPolicy":"Local"}}'
service/example-service patched
(base) ➜  kubernetes git:(master)  kubectl get pods -A
NAMESPACE            NAME                                           READY   STATUS    RESTARTS     AGE
kube-system          coredns-7c65d6cfc9-2q4t7                       1/1     Running   0            6m19s
kube-system          coredns-7c65d6cfc9-7vp2v                       1/1     Running   0            6m19s
kube-system          etcd-master-control-plane                      1/1     Running   0            6m26s
kube-system          kindnet-jnshv                                  1/1     Running   0            6m19s
kube-system          kube-apiserver-master-control-plane            1/1     Running   0            6m26s
kube-system          kube-controller-manager-master-control-plane   0/1     Running   1 (5s ago)   6m26s
kube-system          kube-proxy-4smg4                               1/1     Running   0            6m19s
kube-system          kube-scheduler-master-control-plane            1/1     Running   0            6m26s
local-path-storage   local-path-provisioner-57c5987fd4-scvr4        1/1     Running   0            6m19s
```

**Comment by carlory** [comment]
unrelated failures
/test pull-kubernetes-integration

File: cmd/kube-controller-manager/app/core.go [hunk 1]
```diff
@@ -92,7 +92,8 @@ func newServiceLBControllerDescriptor() *ControllerDescriptor {
 }
 
 func startServiceLBController(ctx context.Context, controllerContext ControllerContext, controllerName string) (controller.Interface, bool, error) {
-	serviceController, err := servicecontroller.New(
+	serviceController, err := servicecontroller.NewWithContext(
```
Comment (aojea) [inline cmd/kube-controller-manager/app/core.go:95]: side note, @elmiko @thockin @liggitt @dims I wonder if we should still be running this controllers in the kube-controller-manager or completely remove them ... will they even work after the removal of the cloud provider code?

Comment (aojea) [reply cmd/kube-controller-manager/app/core.go:95]: more on https://github.com/kubernetes/kubernetes/issues/128121#issuecomment-2422075168

Comment (carlory) [reply cmd/kube-controller-manager/app/core.go:95]: /hold

@aojea @pohly I find another way to fix this issue and will create a new PR. It is an old bug in the service controller. I am testing it with my fix.

File: staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go [hunk 2]
```diff
@@ -113,12 +113,29 @@ type CloudNodeController struct {
...
 	kubeClient clientset.Interface,
 	cloud cloudprovider.Interface,
 	nodeStatusUpdateFrequency time.Duration,
 	workerCount int32) (*CloudNodeController, error) {
+	ctx := context.Background()
+	return NewCloudNodeControllerWithContext(ctx, nodeInformer, kubeClient, cloud, nodeStatusUpdateFrequency, workerCount)
+}
+
+// NewCloudNodeController creates a CloudNodeController object
+func NewCloudNodeControllerWithContext(
```
[the remark this answers is not in the document]
Comment (pohly) [reply staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go:129]: https://github.com/kubernetes/kubernetes/blob/aed92f4a6e1fb03951b8193470ce7e58a48331c0/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L573 is called by an event handler and wants to emit events. I'm not sure whether that's good or bad - it is what it is.

But why is it necessary to update the node controller? https://github.com/kubernetes/kubernetes/blob/aed92f4a6e1fb03951b8193470ce7e58a48331c0/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L313-L323 is the kind of trivial event handler that I would expect from a controller. It doesn't use the event recorder, so creating that in `Run` should be fine.

File: cmd/kube-controller-manager/app/core.go (hunk 1 above)
Comment (aojea) [reply cmd/kube-controller-manager/app/core.go:95]: so, cloud-provider name must no be empty https://github.com/kubernetes/kubernetes/blob/85ff7e75a2066fef3543a55ca995c5173e779b72/staging/src/k8s.io/cloud-provider/options/options.go#L271-L273

Comment (carlory) [reply cmd/kube-controller-manager/app/core.go:95]: @aojea @pohly  Another PR to fix an old issue: https://github.com/kubernetes/kubernetes/pull/128182

File: staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (carlory) [reply staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go:129]: >According to https://github.com/kubernetes/kubernetes/issues/128121, the problem is that informers are active and try to emit events even though the controller isn't running (yet).

>Should event handlers really emit events? If yes, then this is the right fix. Unfortunately it makes the API more complicated, something that https://github.com/kubernetes/kubernetes/commit/50c12437604b0cd5a73514389409fc2fde8b91bd was trying to avoid.

@pohly I think it is an old bug but it is detected by https://github.com/kubernetes/kubernetes/pull/122145

https://github.com/carlory/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L183

If the init fails, we shouldn't register event handlers. It will cause a crash since https://github.com/kubernetes/kubernetes/pull/122145 is merged.

There's a memory leak in the code. the queue has no worker to consume the event.

[the remark this answers is not in the document]
Comment (aojea) [reply staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go:129]: @pohly agree with @carlory , don't worry, I think that change only surfaced the bug

[the remark this answers is not in the document]
Comment (carlory) [reply staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go:129]: > I was wondering about that when the description said "service-lb-controller is instantiated but not started".

sorry for that, I update the description of this PR.

**Comment by carlory** [comment]
An open question is whether we can use `recorder` to report an event in the informer's event handlers?

File: staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (aojea) [reply staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go:129]: > Should event handlers really emit events? If yes, then this is the right fix

I think the event handlers should not emit events, that is noisy and not providing the right signal to cluster administrators ,

**Comment by aojea** [comment]
> An open question is whether we can use `recorder` to report an event in the informer's event handlers?

we should not

**Comment by carlory** [comment]
@aojea @pohly  These events were added by https://github.com/kubernetes/kubernetes/pull/20607 which provides more debug information for https://github.com/kubernetes/kubernetes/issues/20547. This issue was resolved but the event is still left in the controller. 

I'm unsure whether it is right to remove those events, switch to print some logs instead, or keep it as is. Leave it to the reviewer/author of the above issue or sig-cloudprovider to decide. I'll update the code later if needed.

/cc @bprashanth @mikedanese @thockin

**Comment by aojea** [comment]
> I'm unsure whether it is right to remove those events, switch to print some logs instead, or keep it as is. Leave it to the reviewer/author of the above issue or sig-cloudprovider to decide. I'll update the code later if needed.

I have been maintaining this controller both upstream and downstream in GCE for a long time and debugging complex failures without needing the events, I don't think throwing events on the handlers is the right thing to do for multiple reasons, is not the right place to perform API operations, can create a storm of events adding load to the control plane, ...

We need to remove  them please, https://github.com/kubernetes/kubernetes/pull/128179#issuecomment-2426329386

**Comment by carlory** [comment]
@aojea The last question is whether we can initialize the recorder variable in `Run` function instead of `New` function. If yes, other changes can be reverted. Most controllers in `pkg/controller` package are using the `New` function to initialize the recorder variable.

**Comment by pohly** [comment]
The problem with the event recorder is that it runs (sic!) goroutines. That makes initializing it in the `Run` method more suitable because then there is a proper context for those goroutines (cancellation!).

What was problematic with https://github.com/kubernetes/kubernetes/commit/50c12437604b0cd5a73514389409fc2fde8b91bd was that it left the event recorder as field in the controller struct. Usage of that field in the event handler then became a runtime problem instead of a compile-time error.

If I were to do this again, I would probably remove the recorder field and turn it into a parameter of the functions called by `Run`.

**Comment by aojea** [comment]
> The problem with the event recorder is that it runs (sic!) goroutines. That makes initializing it in the `Run` method more suitable because then there is a proper context for those goroutines (cancellation!).

is there any problem in moving them back to the constructors that is not correctness? as @carlory says most of the intree controllers are initializing them in the constructor ... if that simplify the problem I think the trade off is worth it

**Comment by pohly** [comment]
> is there any problem in moving them back to the constructors that is not correctness

Contextual logging depends on constructing the recorder with a context passed in by the caller. Also, cancellation.

>  as @carlory says most of the intree controllers are initializing them in the constructor 

That's only because that's old code that hasn't been updated yet.

**Comment by carlory** [comment]
/retitle "cloud service controller stops reporting events from the informer's event handlers"

**Comment by carlory** [comment]
> That's only because that's old code that hasn't been updated yet. 

Can I pick it up?

**Comment by carlory** [comment]
@aojea @pohly I remove the recorder from event handlers. It seems that we need another PR to update the old code that it makes `Run` of all controllers accept `recorder` as an argument.

**Comment by pohly** [comment]
> > That's only because that's old code that hasn't been updated yet.
> Can I pick it up?

Yes, please do.

My initial reaction was "let's combine with other upcoming changes once the new client-go APIs are available", but I don't know how many of this will be relevant for controllers (`logcheck` will tell us, I just haven't looked yet) and a single PR making exactly one change may be simpler to review.

**Comment by carlory** [comment]
If the controller removed the event recorder field, it would become harder for callers to get the recorder. These functions have to accept a recorder as an argument, which is a bit annoying. Or put the recorder into the context in the `Run` function and pass the generated context to children functions. When a child function needs to record an event, it has to get the recorder from the context liker logger.

```golang
func (c *Controller) Run(ctx context.Context) error {
	logger := klog.FromContext(ctx)

	eventBroadcaster = record.NewBroadcaster(record.WithContext(ctx))
	eventRecorder = eventBroadcaster.NewRecorder(scheme.Scheme, v1.EventSource{Component: "service-controller"})
	ctx = context.WithValue(ctx, "eventRecorder", eventRecorder)

	defer runtime.HandleCrash()
	defer c.serviceQueue.ShutDown()
	defer c.nodeQueue.ShutDown()

	// Start event processing pipeline.
	eventBroadcaster.StartStructuredLogging(0)
	eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: c.kubeClient.CoreV1().Events("")})
	defer eventBroadcaster.Shutdown()

	logger.Info("Starting controller")
	defer logger.Info("Shutting down controller")
}

func (c *Controller) sync(ctx context.Context, key string) error {
	logger := klog.FromContext(ctx)
	eventRecorder := ctx.Value("eventRecorder").(record.EventRecorder)

	// Record the event
	eventRecorder.Eventf(nil, v1.EventTypeNormal, "Synced", "Successfully synced %s", key)
}
```

Is it desired?

**Comment by aojea** [comment]
/hold cancel
/lgtm
/approve
/remove-kind bug
/remove-kind regression
/kind cleanup

Let's not conflate changes as Patrick says, throwing events on handlers does not seems the right thing to do

/assign @thockin 

for approval

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go [hunk 3]
```diff
@@ -552,19 +552,15 @@ func needsCleanup(service *v1.Service) bool {
 }
 
 // needsUpdate checks if load balancer needs to be updated due to change in attributes.
-func (c *Controller) needsUpdate(oldService *v1.Service, newService *v1.Service) bool {
+func needsUpdate(oldService *v1.Service, newService *v1.Service) bool {
 	if !wantsLoadBalancer(oldService) && !wantsLoadBalancer(newService) {
 		return false
 	}
 	if wantsLoadBalancer(oldService) != wantsLoadBalancer(newService) {
-		c.eventRecorder.Eventf(newService, v1.EventTypeNormal, "Type", "%v -> %v",
```
Comment (aojea) [inline staging/src/k8s.io/cloud-provider/controllers/service/controller.go:560]: /hold
@carlory we need to keep the information, can you replace the events by logs? V(2) should be enough

Comment (carlory) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:560]: updated. @aojea 

Can you take a look at the release note for this PR? It is a bug fix for the cloud provider's cloud-controller-manager if they use the library `k8s.io/cloud-provider` version 0.31.0 or later.

Should we add an `Action Required` section to the release note?

Comment (aojea) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:560]: I think is worth to mention it but I don't know if is as urgent as an Action required thing

**Comment by aojea** [comment]
/hold cancel

For release note something like this with better wording should be enough, we can also backport this change but it does not seems this can be easily hit, people usually vendor the whole initialization code

```
Fixes a bug in the `k8s.io/cloud-provider/service`  controller, it may panic when a service is updated because the event recorder was used before it was initialized. All cloud providers should using the `v1.31.0` cloud provider service controller must ensure that the controllers is initialized before the informer start to process events or update it to the version 1.32.0.
```

**Comment by carlory** [comment]
/release-note-edit  ```Fixes a bug in the `k8s.io/cloud-provider/service`  controller, it may panic when a service is updated because the event recorder was used before it was initialized. All cloud providers should using the `v1.31.0` cloud provider service controller must ensure that the controllers is initialized before the informer start to process events or update it to the version 1.32.0.```

**Comment by carlory** [comment]
@aojea but cloud vendors use `app.NewCloudControllerManagerCommand` to create a cloud controller manager. The `recorder` field may not initialized when event handler receives events. And the `recorder` field is private.  It can not make sure the `service controller` initialized during the `cloud controller manager` setup.

https://grep.app/search?q=app.NewCloudControllerManagerCommand

image

**Comment by aojea** [comment]
>  It can not make sure the service controller initialized during the cloud controller manager setup.

it will not receive events until the informer is started, and the informers are started AFTER the controllers have started

https://github.com/kubernetes/kubernetes/blob/72729db87fb710c12fce659450a332da078033ca/cmd/cloud-controller-manager/app/controllermanager.go#L218-L245

**Comment by carlory** [comment]
```
func initFunc() {
    c := NewFunc()
    go c.Run()
}

initFunc()
informer.Start()
```

I think `informer.Start()` may run before `go c.Run()`. @aojea

**Comment by pohly** [comment]
Let me reply here even though it doesn't belong into this PR:
> If the controller removed the event recorder field, it would become harder for callers to get the recorder.

I was thinking of a separate parameter, not storing it in the context - that wouldn't be very obvious. A better alternative might be to separate the recorder into a second struct:
```
struct Controller { 
    // no recorder here!
}

struct runningController {
   *Controller // embedded
   recorder ...
}

func (c *Controller) Run(ctx) {
    // construct recorder and runningController
}

func (c *runningController) someMethod(ctx) {
   // use c.recorder or any field in Controller, just as before.
}
```

**Comment by aojea** [comment]
@carlory there is a time

> I think `informer.Start()` may run before `go c.Run()`. So I backport it to release 1.31. @aojea

there are is a sleep, although the default is zero and wait function to call the apiserve before the informer is started ... I find unlikely that the scheduled of the goroutine of the service controller starts later than the informer ... backports are risky and we don't have any evidence this is an issue so I recommend precaution and holding on the backport
