### PR TITLE
Fix metrics AlreadyRegisteredError on TestRecordOperation and TestGetHistogramVecFromGatherer unit test

### LINKED ISSUE #104940: UT failure: panic: duplicate metrics collector registration attempted
### Failure cluster [1b410c50dc9c60031af5](https://go.k8s.io/triage#1b410c50dc9c60031af5)
https://storage.googleapis.com/k8s-triage/index.html?text=prometheus

##### Error text:
**TestRecordOperation**
```
=== RUN   TestRecordOperation
--- FAIL: TestRecordOperation (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 281 [running]:
testing.tRunner.func1.2({0x2b86420, 0xc000526a20})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x2b86420, 0xc000526a20})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000164000, {0xc00081ac80, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000164000, {0xc00081ac70, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/pkg/kubelet/kuberuntime.TestRecordOperation(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/instrumented_services_test.go:33 +0xe4
testing.tRunner(0xc000602b60, 0x2e77168)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727

```

**TestRecordOperation**
```
=== RUN   TestRecordOperation
--- FAIL: TestRecordOperation (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 281 [running]:
testing.tRunner.func1.2({0x2b86420, 0xc000526a20})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x2b86420, 0xc000526a20})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000164000, {0xc00081ac80, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000164000, {0xc00081ac70, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/pkg/kubelet/kuberuntime.TestRecordOperation(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/instrumented_services_test.go:33 +0xe4
testing.tRunner(0xc000602b60, 0x2e77168)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```
**TestGetHistogramVecFromGatherer**

```
=== RUN   TestGetHistogramVecFromGatherer/filter_with_one_label
    --- FAIL: TestGetHistogramVecFromGatherer/filter_with_one_label (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 131 [running]:
testing.tRunner.func1.2({0x9caea0, 0xc00008a7e0})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x9caea0, 0xc00008a7e0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000320000, {0xc000408b10, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000320000, {0xc000408b00, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil.TestGetHistogramVecFromGatherer.func1.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil/metrics_test.go:580 +0xa2
sync.(*Once).doSlow(0xc00041ab84, 0xc000078e38)
	/usr/local/go/src/sync/once.go:68 +0x128
sync.(*Once).Do(0xc00041ab84, 0xc00008a760)
	/usr/local/go/src/sync/once.go:59 +0x47
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil.TestGetHistogramVecFromGatherer.func1(0xc000419860)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil/metrics_test.go:579 +0x35f
testing.tRunner(0xc000419860, 0xc0001415a8)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```

#### Recent failures:
[2021/9/4 上午2:00:19 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433851876134096896)
[2021/9/3 下午8:00:05 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433761222271963136)
[2021/9/3 下午2:00:15 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433670624454119424)
[2021/9/3 上午7:59:43 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433580026854379520)
[2021/9/3 上午1:59:22 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433489204028903424)

/kind failing-test

/sig testing

This may be related with  https://github.com/prometheus/client_golang/issues/716 \  https://github.com/prometheus/client_golang/issues/733

### PR DESCRIPTION
**Pull request by CatherineF-dev**
Test:
```
make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./staging/src/k8s.io/component-base/metrics/testutil

make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./pkg/kubelet/kuberuntime/
```

Fixes #104940

It takes over #105809

### CODE REVIEW

**Comment by CatherineF-dev** [comment]
cc @MikeSpreitzer

File: pkg/kubelet/kuberuntime/instrumented_services_test.go [hunk 1]
```diff
@@ -41,7 +48,8 @@ func TestRecordOperation(t *testing.T) {
 	prometheusURL := "http://" + l.Addr().String() + "/metrics"
 	mux := http.NewServeMux()
 	//lint:ignore SA1019 ignore deprecated warning until we move off of global registries
-	mux.Handle("/metrics", legacyregistry.Handler())
+	handler := promhttp.InstrumentMetricHandler(prometheus.DefaultRegisterer, promhttp.HandlerFor(registry, promhttp.HandlerOpts{}))
```
Comment (dgrisonnet) [inline pkg/kubelet/kuberuntime/instrumented_services_test.go:51]: We don't really need an InstrumentedMetricHandler here since we aren't testing handler specific metrics coming from the Prometheus client. As such, having only the handler for the registry should be enough.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go [hunk 2]
```diff
@@ -61,6 +69,8 @@ func TestRecordOperation(t *testing.T) {
 	assert.HTTPBodyContains(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
 		mux.ServeHTTP(w, r)
 	}), "GET", prometheusURL, nil, runtimeOperationsDurationExpected)
+
+	registry.Reset()
```
Comment (dgrisonnet) [inline pkg/kubelet/kuberuntime/instrumented_services_test.go:73]: I don't think this is necessary since the test will terminate after evaluating this expression so we will not be using the registry anymore.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 1 above)
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:51]: Hi Damien, 
it failed with `make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./pkg/kubelet/kuberuntime/` before.

Since using local registry, the handler become `promhttp.InstrumentMetricHandler(prometheus.DefaultRegisterer, promhttp.HandlerFor(registry, promhttp.HandlerOpts{}))`.

If not using local registry, do you know other ways could fix `make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./pkg/kubelet/kuberuntime/`? Thanks!

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 2 above)
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:73]: It failed with `make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./pkg/kubelet/kuberuntime/` before. The test is a little bit special, it runs with `-count=10`.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 1 above)
Comment (dgrisonnet) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:51]: I was not saying that we should move away from the local registry, this is definitely the way to fix the issue at hand, but I was saying that we shouldn't need an instrumented handler here. I am suggesting the following change:
```suggestion
	handler := promhttp.HandlerFor(registry, promhttp.HandlerOpts{})
```

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 2 above)
Comment (dgrisonnet) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:73]: Even if it is run 10 times, all of the tests should have independent registries which shouldn't collide with one another.

A potential reason why you were still seeing failures might be because you are using the `prometheus.DefaultRegisterer` in the handler which is shared between the tests. Although the library might be protecting against that, I haven't checked. But it might be worth checking again with my suggestion from above: https://github.com/kubernetes/kubernetes/pull/106289/files#r746633125

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 1 above)
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:51]: Got it. Thanks Damien! 
I will try.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 2 above)
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:72]: Hi Damien, I think `registry.Reset()` is needed.

Even though registry is local,  metrics [RuntimeOperations](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/instrumented_services.go#L51-L52)  and [RuntimeOperationsDuration](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/instrumented_services.go#L51-L52) is global.

---
I tested that adding `metrics.RuntimeOperations.Reset()` would work if`registry.Reset()` was removed.
https://github.com/CatherineF-dev/kubernetes/commit/a8692c6e8fea86cddd63b9caab329acb2327ff4d

Comment (dgrisonnet) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:69]: Make sense, thank you for looking into that @CatherineF-dev :slightly_smiling_face:

**Comment by CatherineF-dev** [comment]
github.com/prometheus/ are not allowed to be used in pkg/kubelet/kuberuntime/instrumented_services_test.go.

I will add a new function NewPromHttpHandler in `component-base/metrics/testutil/testutil.go`.
```
func NewFakePromHttpHandler(registry metrics.KubeRegistry) http.Handler{
	return promhttp.HandlerFor(registry, promhttp.HandlerOpts{})
}
```
 

---
```
ERROR: Some files are importing packages under github.com/prometheus/* but are not allow-listed to do so.

See: https://github.com/kubernetes/kubernetes/issues/89267

Failing files:
  ./pkg/kubelet/kuberuntime/instrumented_services_test.go
```

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go [hunk 3]
```diff
@@ -576,19 +573,22 @@ func TestGetHistogramVecFromGatherer(t *testing.T) {
 				Buckets:   buckets,
 			}
 			vec := metrics.NewHistogramVec(HistogramOpts, labels)
-			registerMetrics.Do(func() {
-				legacyregistry.MustRegister(vec)
-			})
+			// Use local registry
+			var registry = metrics.NewKubeRegistry()
+			var gather metrics.Gatherer = registry
+			registry.MustRegister(vec)
```
Comment (logicalhan) [inline staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:579]: nit: `defer registry.Reset()` here is a bit cleaner

**Review by logicalhan — COMMENTED** [review]
/lgtm

File: pkg/kubelet/kuberuntime/instrumented_services_test.go [hunk 4]
```diff
@@ -22,26 +22,29 @@ import (
...
 
 	l, err := net.Listen("tcp", "127.0.0.1:0")
 	assert.NoError(t, err)
 	defer l.Close()
 
 	prometheusURL := "http://" + l.Addr().String() + "/metrics"
 	mux := http.NewServeMux()
-	//lint:ignore SA1019 ignore deprecated warning until we move off of global registries
-	mux.Handle("/metrics", legacyregistry.Handler())
+	handler := promhttp.HandlerFor(registry, promhttp.HandlerOpts{})
```
Comment (logicalhan) [inline pkg/kubelet/kuberuntime/instrumented_services_test.go:46]: You can't import from prometheus directly, you'll need to use one of our [wrapped handlers](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/component-base/metrics/http.go#L62-L64).

Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:46]: `Defer` inside for loop is a little tricky. 

It will begin to`Reset` after all loops finish instead of one loop finishes.
https://play.golang.org/p/9e9qyuE64nI

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go (hunk 3 above)
Comment (CatherineF-dev) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:579]: `Defer` inside for loop is a little tricky. 

It will begin to`Reset` after all loops finish instead of one loop finishes.
https://play.golang.org/p/9e9qyuE64nI

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 4 above)
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go]: It worked. Thanks!

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go [hunk 5]
```diff
@@ -576,19 +573,22 @@ func TestGetHistogramVecFromGatherer(t *testing.T) {
...
 			vec.WithLabelValues("value1-1", "value2-0").Observe(3.5)
 			vec.WithLabelValues("value1-1", "value2-1").Observe(4.5)
 			metricName := fmt.Sprintf("%s_%s_%s", HistogramOpts.Namespace, HistogramOpts.Subsystem, HistogramOpts.Name)
-			histogramVec, _ := GetHistogramVecFromGatherer(legacyregistry.DefaultGatherer, metricName, tt.lvMap)
+			histogramVec, _ := GetHistogramVecFromGatherer(gather, metricName, tt.lvMap)
 			if diff := cmp.Diff(tt.wantVec, histogramVec); diff != "" {
 				t.Errorf("Got unexpected HistogramVec (-want +got):\n%s", diff)
 			}
+
+			registry.Reset()
```
Comment (MikeSpreitzer) [inline staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:591]: What is this Reset for?  Both `vec` and `registry` are discarded right after this statement.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go [hunk 6]
```diff
@@ -24,24 +24,28 @@ import (
...
 )
 
 func TestRecordOperation(t *testing.T) {
-	legacyregistry.MustRegister(metrics.RuntimeOperations)
-	legacyregistry.MustRegister(metrics.RuntimeOperationsDuration)
-	legacyregistry.MustRegister(metrics.RuntimeOperationsErrors)
+	// Use local registry
+	var registry = compbasemetrics.NewKubeRegistry()
+	var gather compbasemetrics.Gatherer = registry
+	defer registry.Reset()
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: Both seem to be OK.
I prefer `defer it to the end` because we want to fix the test case multiple times.
The reset at the end of the test case will clear the metrics/env after running the case. 
This is also a very clear way.

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go (hunk 5 above)
Comment (CatherineF-dev) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:591]: It's for consistency.  And future contributors can add more tests inside this block without considering registry.Reset().

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: Doing the Reset at the end works if every test does a Reset at the end.  Doing a Reset at the start works regardless of what other tests do.  A local condition is better than a global one.

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go (hunk 5 above)
Comment (MikeSpreitzer) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:591]: Any added tests will have to be written with cognizance of what the metrics start out containing, or deliberate independence of that.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (CatherineF-dev) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: Both ways are okay.  

I prefer `defer`. Because
1. Other test files willn't affect this file. Because RuntimeOperations is supposed to be tested in this file.
2. It requires tests in this file doing Reset at the end.  We have done it since registration appears only once.  Or, it could keep code style more consistent if registration appears many times.

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go (hunk 3 above)
Comment (logicalhan) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:579]: It's wrapped in a function `func(t *testing.T)`, so your playground isn't an accurate representation of the flow. Defers are local to the function it is invoked in, so using a defer here should be fine.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: Both ways will work if, in a given process, no other function adds data to `metrics.RuntimeOperations`, `metrics.RuntimeOperationsDuration`, or `metrics.RuntimeOperationsErrors` before TestRecordOperation runs.  That is a global condition.  Note that `metrics.RuntimeOperations` is registered in legacyregistry in some other code invoked by another test.  Other test files _can_ affect this one, if the Reset is done at the end in this one.  Local conditions are better than global ones.

[the remark this answers is not in the document]
Comment (deads2k) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: > Both ways will work if, in a given process, no other function adds data to `metrics.RuntimeOperations`, `metrics.RuntimeOperationsDuration`, or `metrics.RuntimeOperationsErrors` before TestRecordOperation runs. That is a global condition. Note that `metrics.RuntimeOperations` is registered in legacyregistry in some other code invoked by another test. Other test files _can_ affect this one, if the Reset is done at the end in this one. Local conditions are better than global ones.

I find this argument persuasive.  Globals present numerous problems, but clearing the state before starting a test keeps the scope of control inside this Test instead of requiring every other test to "be perfect".

[the remark this answers is not in the document]
Comment (aojea) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: > clearing the state before starting a test keeps the scope of control inside this Test instead of requiring every other test to "be perfect".

yeah, we can't rely that other tests are right, but we also need to clean up the state once the test ends, same as we do with the listeners, per example

```
defer l.Close()
```
I feel that we need both
```
diff --git a/pkg/kubelet/kuberuntime/instrumented_services_test.go b/pkg/kubelet/kuberuntime/instrumented_services_test.go
index e95d6bdb74a..1801f995d5f 100644
--- a/pkg/kubelet/kuberuntime/instrumented_services_test.go
+++ b/pkg/kubelet/kuberuntime/instrumented_services_test.go
@@ -37,6 +37,7 @@ func TestRecordOperation(t *testing.T) {
        registry.MustRegister(metrics.RuntimeOperations)
        registry.MustRegister(metrics.RuntimeOperationsDuration)
        registry.MustRegister(metrics.RuntimeOperationsErrors)
+ registry.Reset()
 
        l, err := net.Listen("tcp", "127.0.0.1:0")
```

File: staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go (hunk 3 above)
Comment (CatherineF-dev) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics_test.go:579]: Oh, you're right.
I tested it.

https://gist.github.com/CatherineF-dev/3ca9d99aefda22775570cec7edb493af
```
=== RUN   TestGetHistogramVecFromGatherer
    metrics_test.go:564: ## begin main
=== RUN   TestGetHistogramVecFromGatherer/filter_with_one_label
    metrics_test.go:568: ## begin for
    metrics_test.go:571: ## end for
## defer 0
=== RUN   TestGetHistogramVecFromGatherer/filter_with_two_labels
    metrics_test.go:568: ## begin for
    metrics_test.go:571: ## end for
## defer 1
## end main
=== CONT  TestGetHistogramVecFromGatherer
    metrics_test.go:602: ## end main
```

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go:36]: I do not follow the analogy to calling Close.  The Close method is about releasing expensive resources that an active connection holds.  Reset is not analogous, it does not release expensive resources.  I mean, there may be some internal side-effects of resetting some metrics, but it is nothing like open network connections that can accumulate and cause problems.

**Comment by CatherineF-dev** [comment]
Thanks everyone! Have changed to `Reset` at the beginning.

File: pkg/kubelet/kuberuntime/instrumented_services_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/kubelet/kuberuntime/instrumented_services_test.go]: You are right, my bad,  I misinterpreted the reset on metrics. 

Agree with you and David, the test has to clear the state before starting and not depend that other tests do the same after finishing

**Comment by MikeSpreitzer** [comment]
@CatherineF-dev : thank you for caring and seeing this through to completion!

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by CatherineF-dev** [comment]
> /assign @derekwaynecarr

Thanks Mike!

**Comment by thockin** [comment]
Approving to allow others to rebase on it.

/approve
