### PR TITLE
gci: decouple from the built-in kubelet version

### LINKED ISSUE #31376: GCI: Decouple image building from Kubernetes release process
During the reviewing of release velocity doc, we found there is a regression introduced when switching master node from debian-based container-vm to gci image on GKE / GCE, which put gci image release into GKE / GCE release critical path. We should fix this regression for 1.4 release. 

cc/ @pwittrock, release czar for 1.4 release

cc/ @kubernetes/goog-image @kubernetes/goog-node

### PR DESCRIPTION
**Pull request by Amey-D**
Fixed #31376

Prior to this change, configure.sh would:
(1) compare versions of built-in kubelet and downloaded kubelet, and
(2) bind-mount downloaded kubelet at /usr/bin/kubelet in case of
version mismatch

With this change, configure.sh:
(1) compares the two versions only on test clusters, and
(2) uses the actual file paths to start kubelet w/o any bind-mounting

To allow (2), this change also provides its own version of kubelet
systemd service file.

Effectively with this change we will always use the downloaded kubelet
binary along with its own systemd service file on non-test clusters.  The
main advantage is this change does not rely on the kubelet being built in to
the OS image.

``` release-note
gci: decouple from the built-in kubelet version
```

@dchen1107 @wonderfly  can you please review

cc/ @kubernetes/goog-image FYI

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31367)

### CODE REVIEW

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/31376

**Comment by wonderfly** [comment]
> (1) compare the two versions (same as before), and
Curious, why still the check the builtin version? Isn't it more consistent to just use the downloaded version, and it's systemd config, no matter what? My concern is that as we go further this way, the builtin systemd config could diverge with upstream and trying to use it may cause unexpected problems.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 535 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPyYaNlcOsWIN-nWdkR:-KPyYaNlcOsWIN-nWdkS:bjzq20x) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L535)):*
> # Write the systemd service file for kubelet.
>   cat <<EOF >/etc/systemd/system/kubelet.service
> [Unit]
> Description=Kubernetes kubelet
> Requires=network-online.target
> After=network-online.target
>  
> [Service]
> Restart=always
> RestartSec=10
> ExecStart=${kubelet_bin} ${flags}
>  
> [Install]
> WantedBy=multi-user.target
> EOF

Many packages come with their own systemd service file as part of their distributions. Is it possible to have kubernetes do so too so that this doesn't need to be hard coded? Also, that will also make the service file versioned, which is good.

If not, can it at least be in one of the yaml configs?

---

*[cluster/gce/gci/configure-helper.sh, line 1099 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPyZQVVPHUWjjPnD24v:-KPyZQVVPHUWjjPnD24w:bulfz1j) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L1099)):*
> "${KUBE_HOME}"
In your current logic, you compare the builtin version with the download one. If the same, you would use the builtin version, right? Then do you copy it from /usr/bin to $KUBE_HOME/bin?

---

*[cluster/gce/gci/configure.sh, line 174 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy_0KcocrLNni-s8Bv:-KPy_0KcocrLNni-s8Bw:bpva97j) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure.sh#L174)):*
> "${kube_bin}
Is $KUBE_HOME in $PATH? Or is kubelet/kubectl always started with full path?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-:-KPyXZOcPbBIL7Lq-a6a:bnhth4f)*

File: cluster/gce/gci/configure-helper.sh [hunk 1]
```diff
@@ -506,7 +517,22 @@ function start-kubelet {
...
+  cat <<EOF >/etc/systemd/system/kubelet.service
+[Unit]
+Description=Kubernetes kubelet
+Requires=network-online.target
+After=network-online.target
+
+[Service]
+Restart=always
+RestartSec=10
+ExecStart=${kubelet_bin} ${flags}
```
Comment (adityakali) [inline cluster/gce/gci/configure-helper.sh]: Can we continue use the /etc/default/kubelet for flags? What we currently have is:

```
[Service]
Restart=always
RestartSec=10
EnvironmentFile=/etc/default/kubelet
ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
ExecStart=${kubelet_bin} $KUBELET_OPTS
```

Additionally, if you want, you can even do something like:
```
ExecStart=$KUBELET_BIN $KUBELET_OPTS
```
and set KUBELET_BIN also in /etc/default/kubelet. This can allow you to keep the kubelet.service file completely static.

**Comment by Amey-D** [comment]
I added an additional check for TEST_CLUSTER, that is the version comparison happens only if TEST_CLUSTER is 'true'.  On non-test clusters we will always use the downloaded kubelet and systemd service file.

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPygrVCOAgXYt5hB8yy:blkj62x) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, adityakali (Aditya Kali) wrote…</i></summary>
> Can we continue use the /etc/default/kubelet for flags? What we currently have is:
> 
> 
> 
> ```
> 
> [Service]
> 
> Restart=always
> 
> RestartSec=10
> 
> EnvironmentFile=/etc/default/kubelet
> 
> ExecStartPre=/bin/mkdir -p /etc/kubernetes/manifests
> 
> ExecStart=${kubelet_bin} $KUBELET_OPTS
> 
> ```
> 
> 
> 
> Additionally, if you want, you can even do something like:
> 
> ```
> 
> ExecStart=$KUBELET_BIN $KUBELET_OPTS
> 
> ```
> 
> and set KUBELET_BIN also in /etc/default/kubelet. This can allow you to keep the kubelet.service file completely static.
</details>
If we specify the full systemd service file as part of configure-helper.sh, then I do not see any benefits of using /etc/default/kubelet.  The /etc/default/kubelet would be useful if we put the service config in the yaml files, but in that case it would have to be duplicated in both master and node yaml.  LMK if you have a strong preference to moving the service config to yaml files.

---

*[cluster/gce/gci/configure-helper.sh, line 535 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPyYaNlcOsWIN-nWdkR:-KPybztR7AqmHpzuilbh:bfne2de) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L535)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > # Write the systemd service file for kubelet.
> >   cat <<EOF >/etc/systemd/system/kubelet.service
> > [Unit]
> > Description=Kubernetes kubelet
> > Requires=network-online.target
> > After=network-online.target
> >  
> > [Service]
> > Restart=always
> > RestartSec=10
> > ExecStart=${kubelet_bin} ${flags}
> >  
> > [Install]
> > WantedBy=multi-user.target
> > EOF
> 
> Many packages come with their own systemd service file as part of their distributions. Is it possible to have kubernetes do so too so that this doesn't need to be hard coded? Also, that will also make the service file versioned, which is good.
> 
> If not, can it at least be in one of the yaml configs?
</details>
It could be in the yaml file, but then it would have to be in both master and node yaml files and populating the binary file path and commandline args would be more work.  

---

*[cluster/gce/gci/configure-helper.sh, line 1099 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPyZQVVPHUWjjPnD24v:-KPybhfHdIcjYLSWHoOD:b-byjql4) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L1099)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > "${KUBE_HOME}"
> In your current logic, you compare the builtin version with the download one. If the same, you would use the builtin version, right? Then do you copy it from /usr/bin to $KUBE_HOME/bin?
</details>
If the versions match, I use the path /usr/bin/kubelet in the systemd service file.  No copying is involved.

---

*[cluster/gce/gci/configure.sh, line 174 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy_0KcocrLNni-s8Bv:-KPycliDjNO0CgJKs83u:b-vdeloq) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure.sh#L174)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> > "${kube_bin}
> Is $KUBE_HOME in $PATH? Or is kubelet/kubectl always started with full path?
</details>
kubelet is started with full path through systemd service.  kubectl is not run automatically -- users can run it manually if they wa

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-:-KPygVhzXyDVhPvurDJV:b-ljme17)*

File: cluster/gce/gci/configure-helper.sh (hunk 1 above)
Comment (dchen1107) [inline cluster/gce/gci/configure-helper.sh]: +1

**Comment by adityakali** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPypvYgGuhAb3nREqUR:bg33ksm) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, dchen1107 (Dawn Chen) wrote…</i></summary>
> +1
</details>
It doesn't have to be in yaml either. Just package it as-is into the release tar.gz as we do other manifest files (add an entry at https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L955).

Having the flags read from /etc/default/kubelet means that when debugging its easy to figure out what settings are in use and to changes. Otherwise even small changes like increasing log verbosity will require users (or system admins) to edit the systemd service file, do a systemd daemon reload, before restarting the service.

This is just for convenience though. So not strong preference.

---

*[cluster/gce/gci/configure-helper.sh, line 535 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPyYaNlcOsWIN-nWdkR:-KPyptKQDvqcbmONRmgK:bb6p4lt) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L535)):*
>  

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367)*

**Comment by wonderfly** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPyrEccHA8tIkCIFCUn:bfi854p) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, adityakali (Aditya Kali) wrote…</i></summary>
> It doesn't have to be in yaml either. Just package it as-is into the release tar.gz as we do other manifest files (add an entry at https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L955).
> 
> Having the flags read from /etc/default/kubelet means that when debugging its easy to figure out what settings are in use and to changes. Otherwise even small changes like increasing log verbosity will require users (or system admins) to edit the systemd service file, do a systemd daemon reload, before restarting the service.
> 
> This is just for convenience though. So not strong preference.
</details>
nit: Can you all get a GitHub profile photo? Hard to tell which is who. :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367)*

File: cluster/gce/gci/configure.sh [hunk 2]
```diff
@@ -128,32 +128,19 @@ function install-kube-binary-config {
...
-     [[ "${builtin_version}" != "${required_version}" ]]; then
-    cp "${src_dir}/kubectl" "${kube_bin}"
-    chmod 755 "${kube_bin}/kubelet"
-    chmod 755 "${kube_bin}/kubectl"
-    mount --bind "${kube_bin}/kubelet" /usr/bin/kubelet
-    mount --bind "${kube_bin}/kubectl" /usr/bin/kubectl
-  else
-    rm -f "${kube_bin}/kubelet"
-  fi
+  mv "${src_dir}/kubelet" "${kube_bin}"
```
Comment (adityakali) [inline cluster/gce/gci/configure.sh]: So if the instance reboots, I think we end up re-doing the entire download and untar thing right?
It might be worth testing if this continues to work with even after a reboot.

File: cluster/gce/gci/configure-helper.sh [hunk 3]
```diff
@@ -1070,7 +1098,7 @@ function start-rescheduler {
 
 function reset-motd {
   # kubelet is installed both on the master and nodes, and the version is easy to parse (unlike kubectl)
-  local -r version="$(/usr/bin/kubelet --version=true | cut -f2 -d " ")"
+  local -r version="$("${KUBE_HOME}"/bin/kubelet --version=true | cut -f2 -d " ")"
```
Comment (adityakali) [inline cluster/gce/gci/configure-helper.sh]: Does it make sense to also log the kubelet install location here? (i.e., whether its "${KUBE_HOME}"/bin/kubelet or /usr/bin/kubelet).
(again, only to avoid confusion).

**Comment by Amey-D** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPywv4kCmc84lCgy7qG:b41gxmc) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, wonderfly (Daniel Wang) wrote…</i></summary>
> nit: Can you all get a GitHub profile photo? Hard to tell which is who. :)
</details>
I'll keep the service file configuration how it is right now.

As for the photos I consider it beyond the scope of this CL :)

---

*[cluster/gce/gci/configure-helper.sh, line 1101 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r2-1101:-KPyzUg6yVh9lr1ZUDrS:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/9fb10f6ddc11a7794b884fd6c6e9145b7c8ea5ca/cluster/gce/gci/configure-helper.sh#L1101)):*
<details><summary><i>Previously, adityakali (Aditya Kali) wrote…</i></summary>
> Does it make sense to also log the kubelet install location here? (i.e., whether its "${KUBE_HOME}"/bin/kubelet or /usr/bin/kubelet).
> 
> (again, only to avoid confusion).
</details>
Done.

---

*[cluster/gce/gci/configure.sh, line 131 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdch-r2-131:-KPyytMTsm2e59Or3KWP:b-gnsg0j) ([raw file](https://github.com/kubernetes/kubernetes/blob/9fb10f6ddc11a7794b884fd6c6e9145b7c8ea5ca/cluster/gce/gci/configure.sh#L131)):*
<details><summary><i>Previously, adityakali (Aditya Kali) wrote…</i></summary>
> So if the instance reboots, I think we end up re-doing the entire download and untar thing right?
> 
> It might be worth testing if this continues to work with even after a reboot.
</details>
Done. Verified the installation and configuration services finish successfully upon reboot on master and nodes.  Besides I expect the e2e tests to test reboots.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367)*

**Comment by Amey-D** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPzD5O7THDaCsPF37oQ:b-lufvn3) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, Amey-D (Amey Deshpande) wrote…</i></summary>
> I'll keep the service file configuration how it is right now.
> 
> As for the photos I consider it beyond the scope of this CL :)
</details>
Added /etc/default/kubelet/service for KUBELET_OPTS.  Turned out systemd does not allows reading the binary file name from the environment file.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367)*

**Comment by Amey-D** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/gce/gci/configure-helper.sh, line 531 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-KPy7X8dwCrlzmPvrdcg-r1-531:-KPzDXTytV8tWrU2qI_y:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/56c1ac6f9b89192316b7a838bf12828bc8b290e1/cluster/gce/gci/configure-helper.sh#L531)):*
<details><summary><i>Previously, Amey-D (Amey Deshpande) wrote…</i></summary>
> Added /etc/default/kubelet/service for KUBELET_OPTS.  Turned out systemd does not allows reading the binary file name from the environment file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367)*

**Comment by wonderfly** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31367#-:-KPzIuOvDvpDLhJncrYS:bnfp4nl)*

**Comment by wonderfly** [comment]
LGTM but @adityakali should take a further look...

**Comment by adityakali** [comment]
LGTM
Thanks for the changes Amey!

**Comment by dchen1107** [comment]
LGTM
