### PR TITLE
Don't use mapfile as it isn't bash 3 compatible

### LINKED ISSUE #77349: building on mac results in KUBE_SERVER_PLATFORMS[@]: unbound variable
This issue was moved from https://github.com/kubernetes-sigs/kind/issues/471

**What happened**: building kubernetes with make fails on mac after https://github.com/kubernetes/kubernetes/pull/76974

**What you expected to happen**: building should not fail

**How to reproduce it (as minimally and precisely as possible)**: build from a mac

**Anything else we need to know?**: mapfile is not available on macOS bash. we should have a version check at minimum if we're going to use unsupported features (some of the code already does this)

cc @mtaufen @dims

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Moves away from using mapfile in `hack/lib/golang.sh` so that users don't have to use bash 4+. This mainly fixes building on Darwin.

**Which issue(s) this PR fixes**:
Fixes #77349

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: hack/lib/util.sh [hunk 1]
```diff
@@ -702,6 +702,23 @@ function kube::util::require-jq {
   fi
 }
 
+# kube::util::read-array
+# Reads in stdin and adds it line by line to the array provided. This can be
+# user instead of "mapfile -t", and is bash 3 compatible.
```
Comment (BenTheElder) [inline hack/lib/util.sh]: s/user/used

File: hack/lib/util.sh [hunk 2]
```diff
@@ -702,6 +702,23 @@ function kube::util::require-jq {
...
+#   $1 (name of array to create/modify)
+#
+# Example usage:
+# kube::util::read-array files < <(ls -1)
+#
+function kube::util::read-array {
+  local i=0
+  unset -v "$1"
+  while IFS= read -r "$1[i++]"; do :; done
+  eval "[[ \${$1[--i]} ]]" || unset "$1[i]"
```
Comment (BenTheElder) [inline hack/lib/util.sh]: what is this guarding against?

Comment (cblecker) [reply hack/lib/util.sh]: It's to make sure the last entry in the array isn't empty

File: hack/lib/util.sh (hunk 1 above)
Comment (cblecker) [reply hack/lib/util.sh]: Oops! Fixed.

**Review by thockin — COMMENTED** [review]
BLECH.  Does this work in the wonky bash 4.3 also?

**Comment by cblecker** [comment]
@thockin I'm not sure, I don't have a bash 4.3 environment set up to test. I have bash 3.2 and 5.0 installed on my system.

**Comment by thockin** [comment]
docker run -ti --entrypoint bash debian:jessie

now you do

**Comment by cblecker** [comment]
Thanks for the tip. Yes, this logic works:
```
$ docker run -ti  --entrypoint bash debian:jessie
root@1328009e9c49:/# function kube::util::read-array {
>   local i=0
>   unset -v "$1"
>   while IFS= read -r "$1[i++]"; do :; done
>   eval "[[ \${$1[--i]} ]]" || unset "$1[i]"
> }
root@1328009e9c49:/# kube::util::read-array files < <(ls -1 /)
root@1328009e9c49:/# echo ${files[@]}
bin boot dev etc home lib lib64 media mnt opt proc root run sbin srv sys tmp usr var
root@1328009e9c49:/# echo ${files[5]}
lib
root@1328009e9c49:/#
```

File: hack/lib/util.sh (hunk 2 above)
Comment (spiffxp) [reply hack/lib/util.sh]: I feel like this would be more informative to future maintainers as a comment alongside the magic incantation instead of buried in this PR

**Comment by spiffxp** [comment]
/lgtm
/hold
for a nit, which @cblecker or @thockin are free to cancel if satisfied this is good enough

**Comment by spiffxp** [comment]
/lgtm
Wrong button! Sorry...
