### PR TITLE
Do not forget recording loaded modules

### LINKED ISSUE #89729: kube-proxy panics with SIGSEGV on first run
**What happened**:
When creating a new `1.18.0` cluster using `kubeadm`, `kube-proxy` panics with SIGSEGV on first run:

```
I0401 11:10:20.858107       1 node.go:136] Successfully retrieved node IP: [redacted]
I0401 11:10:20.858228       1 server_others.go:259] Using ipvs Proxier.
W0401 11:10:20.859035       1 proxier.go:429] IPVS scheduler not specified, use rr by default
I0401 11:10:20.859307       1 server.go:583] Version: v1.18.0
I0401 11:10:20.860132       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0401 11:10:20.860212       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0401 11:10:20.860437       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0401 11:10:20.860540       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0401 11:10:20.860862       1 config.go:133] Starting endpoints config controller
I0401 11:10:20.860878       1 config.go:315] Starting service config controller
I0401 11:10:20.860890       1 shared_informer.go:223] Waiting for caches to sync for service config
I0401 11:10:20.860893       1 shared_informer.go:223] Waiting for caches to sync for endpoints config
I0401 11:10:20.961249       1 shared_informer.go:230] Caches are synced for service config 
I0401 11:10:20.961244       1 shared_informer.go:230] Caches are synced for endpoints config 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1514fb8]

goroutine 81 [running]:
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncService(0xc00000a3c0, 0xc000413800, 0x18, 0xc0001f8280, 0xc000243101, 0x5, 0xc00053a9ad)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1903 +0x48
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc00000a3c0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1186 +0xcdd
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointsSynced(0xc00000a3c0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:890 +0x62
k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).Run(0xc000796100, 0xc00009a0c0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:141 +0x108
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:701 +0xb7f
```

Note that after the crash the pod restarts, and the second run is successful:

```
I0401 11:10:22.387131       1 node.go:136] Successfully retrieved node IP: [redacted]
I0401 11:10:22.387187       1 server_others.go:259] Using ipvs Proxier.
W0401 11:10:22.390681       1 proxier.go:429] IPVS scheduler not specified, use rr by default
I0401 11:10:22.390993       1 server.go:583] Version: v1.18.0
I0401 11:10:22.392209       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0401 11:10:22.392555       1 config.go:133] Starting endpoints config controller
I0401 11:10:22.392574       1 shared_informer.go:223] Waiting for caches to sync for endpoints config
I0401 11:10:22.392588       1 config.go:315] Starting service config controller
I0401 11:10:22.392592       1 shared_informer.go:223] Waiting for caches to sync for service config
I0401 11:10:22.492824       1 shared_informer.go:230] Caches are synced for service config 
I0401 11:10:22.492976       1 shared_informer.go:230] Caches are synced for endpoints config
```

and everything seems to be working as expected.

**What you expected to happen**:

`kube-proxy` starts successfully the first time.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new `1.18.0` cluster using `kubeadm`, with `kube-proxy` in `ipvs` mode.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.18.0**
- Cloud provider or hardware configuration: **Hetzner VPS**
- OS (e.g: `cat /etc/os-release`): **Ubuntu 18.04.4 LTS**
- Kernel (e.g. `uname -a`): **5.3.0-45-generic** (Ubuntu's default HWE kernel)
- Install tools: **kubeadm**
- Network plugin and version (if this is a network-related bug):
- Others: using `cri-o 1.17.2` CRI and `kube-proxy` `ipvs` mode

Please let me know if you need any additional information.

### PR DESCRIPTION
**Pull request by gongguan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes [#89729](https://github.com/kubernetes/kubernetes/issues/89729)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Hi, thanks for this. 

I don't think the right answer is just to fake the allocation from deep down the call stack.  We need to understand why it is failing in the first place.

I'll be the first to admit that the setup code in here has gotten a bit twisty, which makes this hard to see by inspection

**Comment by gongguan** [comment]
> Hi, thanks for this.
> 
> I don't think the right answer is just to fake the allocation from deep down the call stack. We need to understand why it is failing in the first place.
> 
> I'll be the first to admit that the setup code in here has gotten a bit twisty, which makes this hard to see by inspection

Sorry, do you mean we should load missing modules in first `CanUseIPVSProxier` check?

**Comment by gongguan** [comment]
ping @thockin for review again, I think it's the root issue. If unit tests is needed, I'll add test tomorrow as it's too late now.

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -650,6 +650,8 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 			if err != nil {
 				klog.Warningf("Failed to load kernel module %v with modprobe. "+
 					"You can ignore this message when kube-proxy is running inside container without mounting /lib/modules", module)
+			} else {
+				bmods = append(bmods, module)
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go:654]: Logically this seems correct. The problem is that `CanUseIPVSProxier` returns false (hence we set a nil ipvs interface) because it doesn't account for modules we load at startup so it errors [here](https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/proxy/ipvs/proxier.go#L712-L714). 

Though we should use a new variable for this (`loadedMods` or similar).

Comment (gongguan) [reply pkg/proxy/ipvs/proxier.go:654]: can we put it to `mods` directly?
as `mods = append(mods, module)` avoid adding a []string, which one do you think better?

Comment (gongguan) [reply pkg/proxy/ipvs/proxier.go]: not add a new var `loadedMods` because add it to mods seems more concise :)
I'm sorry to handle other comments tomorrow morning.

Comment (andrewsykim) [reply pkg/proxy/ipvs/proxier.go]: Though not as concise, I think adding a `loadedMods` var will be better for readability.

**Review by thockin — COMMENTED** [review]
This seems like a more correct fix, indeed.

**Comment by andrewsykim** [comment]
> Should we be loading modules?

We do load the modules (see [here](https://github.com/kubernetes/kubernetes/blob/ff809a5d953ba778270ce8790b21d394821e1e28/pkg/proxy/ipvs/proxier.go#L633)) but we weren't recording that we did.

File: pkg/proxy/ipvs/proxier.go (hunk 1 above)
Comment (gongguan) [reply pkg/proxy/ipvs/proxier.go]: > Though not as concise, I think adding a `loadedMods` var will be better for readability.

Done, PTAL

**Comment by gongguan** [comment]
> This seems like a more correct fix, indeed.

And verified in same scenario(start kube-proxy in ipvs module without loading ip_vs module), it works.

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -650,11 +650,13 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
...
 				klog.Warningf("Failed to load kernel module %v with modprobe. "+
 					"You can ignore this message when kube-proxy is running inside container without mounting /lib/modules", module)
+			} else {
+				lmods = append(lmods, module)
 			}
 		}
 	}
 
-	return append(mods, bmods...), nil
+	return append(mods, append(bmods, lmods...)...), nil
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go:659]: This is a bit hard to read. Maybe this is simpler: 

```
mods = append(mods, bmods...)
mods = append(mods, lmods...)

return mods, nil
```

**Review by andrewsykim — COMMENTED** [review]
one more nit, lgtm otherwise

File: pkg/proxy/ipvs/proxier.go (hunk 2 above)
Comment (gongguan) [reply pkg/proxy/ipvs/proxier.go]: Addressed, thanks

**Comment by gongguan** [comment]
BTW, shall we backport it to other release?

**Comment by gongguan** [comment]
/test pull-kubernetes-e2e-gce
volume tests failed

**Comment by spiffxp** [comment]
re: pull-kubernetes-node-e2e-containerd, it's been timing out most of the day, it's non-blocking https://github.com/kubernetes/kubernetes/issues/89847

**Comment by andrewsykim** [comment]
/approve
/lgtm

Thanks @gongguan! 

> BTW, shall we backport it to other release?

Not critical/urgent since we're still loading the correct module and kube-proxy will only restart at most once, but yes we should backport this. Thanks!
