### PR TITLE
portAllocator sync local data before allocate

### LINKED ISSUE #85894: NodePort creation with statically assigned portNumber collide in multi-master HA cluster
Also reported in:
* https://github.com/kubernetes/kubernetes/issues/32987
* https://github.com/kubernetes/kubernetes/issues/73140
* https://github.com/kubernetes/kubernetes/issues/89042
* https://github.com/kubernetes/kubernetes/issues/86104

**What happened**:
Service of NodePort type fails to (re)create if it was just deleted, and that delete had executed on different apiserver than the create is executing in.

**What you expected to happen**:
Service of NodePort type is created successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Repeatedly create and delete service of NodePort type in a cluster that has more masters than one, and create/delete/create cycle hits two different masters:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - name: "proxy"
      port: 443
      protocol: TCP
      targetPort: 443
      nodePort: 30443
  type: NodePort
  selector:
    service: proxy
```
used in a loop:
```
while kubectl -n default create -f test.yaml ; do kubectl -n default delete -f test.yaml; done
```

results in
```
service/proxy created
service "proxy" deleted
Error from server (Invalid): error when creating "proxy.yaml": Service "proxy" is invalid: spec.ports[0].nodePort: Invalid value: 30443: provided port is already allocated
```
if create/delete requests are load balanced to two different apiservers. It can be forced to happen by using two different kubeconfigs pointing to different apiservers for create and delete. In such case, first create and delete succeed, but second create fails, as it doesn't register the deletion the apiserver 2 did.

**Anything else we need to know?**:
This is a simplified test case. In our testing, when deleting and creating lots of objects (and create and delete happening on different apiservers), this does occur even "kubectl delete ... --wait=true" has finished successfully, and no objects are present. There seems to be some sort of time window where changes committed to one apiserver are not visible by another apiserver.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: local VMs
- OS (e.g: `cat /etc/os-release`): RHEL 7.7
- Kernel (e.g. `uname -a`): `Linux kubemaster1 3.10.0-1062.4.1.el7.x86_64 #1 SMP Wed Sep 25 09:42:57 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: custom

### PR DESCRIPTION
**Pull request by aojea**
The port allocator method tries to allocate the ports directly
from the local memory instead from etcd.
It may happen, in deployments with multiple apiservers, that the
local port allocation information is out of sync, per example:

1. apiserver A create a service with NodePort X
2. apiserver B deletes the service
3. apiserver A creates the service again

If the allocation data of apiserver A wasn't refreshed with the
deletion of apiserver B, apiserver A fails the allocation because
the data is out of sync.

Don't try to do the Allocation operation locally first
and try them using etcd to avoid this issue.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #85894

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix bug in the port allocation logic that caused that the NodePort creation with statically assigned portNumber collide in multi-master HA cluster
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @liggitt @thockin 
Revamping previous PR https://github.com/kubernetes/kubernetes/pull/86527 since it seems there are more hits on the bug.
Basically, it tries to allocate the port only once inside the `tryUpdate` logic
https://github.com/kubernetes/kubernetes/pull/86527#discussion_r362011865

**Comment by aojea** [comment]
interesting 🤔  

pull-kubernetes-integration failed with 
>   synthetic_master_test.go:701: unexpected creation success. The following IPs exist: []string{"192.168.0.1", "192.168.0.4", "192.168.0.5", "192.168.0.6", "192.168.0.1", "192.168.0.2", "192.168.0.3"}. It should only be possible to allocate 2 IP addresses in this cluster.

**Comment by aojea** [comment]
/hold
I've located the issue, but I need to do more testing ...

File: pkg/registry/core/service/allocator/storage/storage_test.go [hunk 1]
```diff
@@ -102,3 +102,48 @@ func TestStore(t *testing.T) {
...
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	// Allocate it only in memory
+	if _, err := backing.Allocate(2); err != nil {
+		t.Fatal(err)
+	}
+
+	// It should succeed
+	ok, err := storage.Allocate(2)
```
Comment (aojea) [inline pkg/registry/core/service/allocator/storage/storage_test.go:144]: This test is failing with current implementation

File: pkg/registry/core/service/allocator/storage/storage.go [hunk 2]
```diff
@@ -100,58 +95,56 @@ func (e *Etcd) Allocate(offset int) (bool, error) {
...
+	return offset, true, nil
 }
 
-// Release attempts to release the provided item locally and then in etcd.
+// Release attempts to release the provided item locally.
 func (e *Etcd) Release(item int) error {
 	e.lock.Lock()
 	defer e.lock.Unlock()
 
-	if err := e.alloc.Release(item); err != nil {
```
Comment (aojea) [inline pkg/registry/core/service/allocator/storage/storage.go:148]: this never returns an err

File: pkg/registry/core/service/allocator/storage/storage_test.go [hunk 3]
```diff
@@ -102,3 +102,48 @@ func TestStore(t *testing.T) {
...
+}
+
+func TestAllocatedButReleasedEtcd(t *testing.T) {
+	storage, server, backing, _ := newStorage(t)
+	defer server.Terminate(t)
+	if err := storage.storage.Create(context.TODO(), key(), validNewRangeAllocation(), nil, 0); err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	// Allocate it only in memory
```
Comment (aojea) [inline pkg/registry/core/service/allocator/storage/storage_test.go:138]: this ways we "simulate" that the bit was deleted in etcd (by other apiserver) but it is still allocated locally

File: test/integration/master/kube_apiserver_test.go [hunk 4]
```diff
@@ -494,3 +495,84 @@ func TestReconcilerMasterLeaseMultiMoreMasters(t *testing.T) {
 func TestReconcilerMasterLeaseMultiCombined(t *testing.T) {
 	testReconcilersMasterLease(t, 3, 3)
 }
+
+func TestMultiMasterNodePortAllocation(t *testing.T) {
```
Comment (aojea) [inline test/integration/master/kube_apiserver_test.go:499]: this is exactly the scenario described in https://github.com/kubernetes/kubernetes/issues/85894

**Comment by aojea** [comment]
/hold cancel
This should be ready for review @thockin @liggitt , the tests seems are passing, but some comments first:

1st commit is a benchmark for the bitmap allocation strategy, not directly related to the PR but may be useful for documenting the code.

2nd commit add more tests to portallocator storage to try to give more coverage in this area.

3rd commit solves the bug removing the logic that checks the local bitmap first. Now,  it first checks that is operating with the same version of the data stored in etcd, and if not, it's loaded.
 I've also added one integration test reproducing the issue and new unit tests to cover scenarios with different data in the local bitmap and in etcd.

@wojtek-t is there any way I can check the impact of this change in performance?

File: pkg/registry/core/service/allocator/storage/storage.go [hunk 5]
```diff
@@ -80,17 +80,12 @@ func NewEtcd(alloc allocator.Snapshottable, baseKey string, resource schema.Grou
...
 	e.lock.Lock()
 	defer e.lock.Unlock()
 
-	ok, err := e.alloc.Allocate(offset)
-	if !ok || err != nil {
-		return ok, err
-	}
-
-	err = e.tryUpdate(func() error {
+	err := e.tryUpdate(func() error {
```
Comment (wojtek-t) [inline pkg/registry/core/service/allocator/storage/storage.go:88]: Just putting my scalability hat for now, I'm not sure I understand what does it change from scalability/performance prespective. We get+write from etcd both before and after.

So, what is the difference? That in case the IP was already allocated, we don't do get? [And that has a possibility to race?]
If that's the case, we should fix it no matter what scalability impact it has...

Comment (aojea) [reply pkg/registry/core/service/allocator/storage/storage.go:88]: yeah, I think that's the only change here on that regard. Thanks for confirming

File: pkg/registry/core/service/allocator/bitmap_test.go [hunk 6]
```diff
@@ -155,3 +155,37 @@ func TestContiguousAllocation(t *testing.T) {
...
 }
+
+func allocateAllBitmap(max int, m Interface) {
+	for i := 0; i < max; i++ {
+		m.AllocateNext()
+	}
+}
+
+func benchmarkContiguousAllocationBitmap(b *testing.B, max int) {
+	m := NewContiguousAllocationMap(max, "test")
```
Comment (thockin) [inline pkg/registry/core/service/allocator/bitmap_test.go:166]: As far as I can tell NOBODY uses this - should we just remove contiguous entirely?

File: pkg/registry/core/service/portallocator/storage/storage_test.go [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+	_, storage, backing, si, destroyFunc := newStorage(t)
+	defer destroyFunc()
+	if err := si.Create(context.TODO(), key(), validNewRangeAllocation(), nil, 0); err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	if err := storage.Allocate(30100); err != nil {
+		t.Fatal(err)
+	}
+	ok, err := backing.Allocate(100)
```
Comment (thockin) [inline pkg/registry/core/service/portallocator/storage/storage_test.go:102]: It's not clear what this is testing - comments?

File: pkg/registry/core/service/portallocator/storage/storage_test.go [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+	if err != nil {
+		t.Fatal(err)
+	}
+	if ok {
+		t.Fatal("Expected allocation to fail")
+	}
+	if err := storage.Allocate(30100); err != portallocator.ErrAllocated {
+		t.Fatal(err)
+	}
```
Comment (thockin) [inline pkg/registry/core/service/portallocator/storage/storage_test.go:111]: shouldn't we also test deallocation and re-allocation?

File: pkg/registry/core/service/allocator/storage/storage.go [hunk 9]
```diff
@@ -100,58 +95,56 @@ func (e *Etcd) Allocate(offset int) (bool, error) {
...
 func (e *Etcd) Release(item int) error {
 	e.lock.Lock()
 	defer e.lock.Unlock()
 
-	if err := e.alloc.Release(item); err != nil {
-		return err
-	}
-
-	return e.tryUpdate(func() error {
+	err := e.tryUpdate(func() error {
```
Comment (thockin) [inline pkg/registry/core/service/allocator/storage/storage.go:143]: just `return e.tryUpdate` ?

File: pkg/registry/core/service/allocator/storage/storage.go [hunk 10]
```diff
@@ -80,17 +80,12 @@ func NewEtcd(alloc allocator.Snapshottable, baseKey string, resource schema.Grou
 	}, nil
 }
 
-// Allocate attempts to allocate the item locally and then in etcd.
+// Allocate attempts to allocate the item.
 func (e *Etcd) Allocate(offset int) (bool, error) {
 	e.lock.Lock()
 	defer e.lock.Unlock()
 
-	ok, err := e.alloc.Allocate(offset)
```
Comment (thockin) [inline pkg/registry/core/service/allocator/storage/storage.go:88]: This looks like one of those "how did it ever work" cases.  I tried tracing thru code, but found it incredibly tedious to back-track thru interfaces.

I am going to do some digging, but this SEEMS correct...  back in a while.

File: pkg/registry/core/service/allocator/storage/storage_test.go [hunk 11]
```diff
@@ -102,3 +102,48 @@ func TestStore(t *testing.T) {
...
+
+	// It should fail
+	ok, err := storage.Allocate(2)
+	if ok || err != nil {
+		t.Fatal(err)
+	}
+
+}
+
+func TestAllocatedButReleasedEtcd(t *testing.T) {
```
Comment (thockin) [inline pkg/registry/core/service/allocator/storage/storage_test.go:131]: Some better comments would go a long way :)

File: pkg/registry/core/service/allocator/storage/storage_test.go [hunk 12]
```diff
@@ -102,3 +102,48 @@ func TestStore(t *testing.T) {
 		t.Fatal(err)
 	}
 }
+
+func TestAllocatedButReleasedLocally(t *testing.T) {
```
Comment (thockin) [inline pkg/registry/core/service/allocator/storage/storage_test.go:106]: I'm not sure this is a useful test as it doesn't simulate anything real, right?  Or am I misunderstanding?

File: pkg/registry/core/service/allocator/storage/storage.go (hunk 5 above)
Comment (thockin) [reply pkg/registry/core/service/allocator/storage/storage.go:88]: that is how I read it too

**Comment by thockin** [comment]
It took me a while to convince myself it was correct, but it seems so.  Nice find.

File: pkg/registry/core/service/allocator/bitmap_test.go (hunk 6 above)
Comment (aojea) [reply pkg/registry/core/service/allocator/bitmap_test.go:166]: it's about 12 lines of code and it can be used as an example or to compare against it, like in this benchmark.
I will keep it for now.

File: pkg/registry/core/service/allocator/storage/storage.go (hunk 9 above)
Comment (aojea) [reply pkg/registry/core/service/allocator/storage/storage.go:143]: let me check again, I don't know if was a legit failure or if I've tested in a dirty branch but it flaked returning directly

File: pkg/registry/core/service/allocator/storage/storage_test.go (hunk 12 above)
Comment (aojea) [reply pkg/registry/core/service/allocator/storage/storage_test.go:106]: ohh right, the bitmap locks before modifying it ... nothing should be able to modify it without updating etcd

Comment (aojea) [reply pkg/registry/core/service/allocator/storage/storage_test.go:106]: hmm, is testing that the local bitmap is out of date:
1. There is one port allocated in etcd
2. but that port is free in the local bitmap
3. When trying to allocate the port, if we use only the local bitmap it succeeds, that is wrong.

It checks that we are using the data from etcd for .Allocate(), is the inverse situation of the next test.

**Comment by wojtek-t** [comment]
> It took me a while to convince myself it was correct, but it seems so. Nice find.

Yeah - had the same.

File: pkg/registry/core/service/portallocator/storage/storage_test.go [hunk 13]
```diff
@@ -0,0 +1,112 @@
...
+}
+
+func TestStore(t *testing.T) {
+	_, storage, backing, si, destroyFunc := newStorage(t)
+	defer destroyFunc()
+	if err := si.Create(context.TODO(), key(), validNewRangeAllocation(), nil, 0); err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	if err := storage.Allocate(30100); err != nil {
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/registry/core/service/portallocator/storage/storage_test.go:154]: added in another test above

File: pkg/registry/core/service/portallocator/storage/storage_test.go [hunk 14]
```diff
@@ -0,0 +1,112 @@
...
+}
+
+func key() string {
+	return "/ranges/servicenodeports"
+}
+
+func TestEmpty(t *testing.T) {
+	_, storage, _, _, destroyFunc := newStorage(t)
+	defer destroyFunc()
+	if err := storage.Allocate(31000); !strings.Contains(err.Error(), "cannot allocate resources of type servicenodeportallocations at this time") {
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/registry/core/service/portallocator/storage/storage_test.go:86]: commented on the function

**Comment by aojea** [comment]
@thockin PTAL

File: pkg/registry/core/service/allocator/bitmap_test.go (hunk 6 above)
Comment (aojea) [reply pkg/registry/core/service/allocator/bitmap_test.go]: just remove the commit with the bitmap benchmark, is unrelated to the PR, and I'm not sure the benchmark is correct or at least meaningful in a way it can be used as an example

**Comment by aojea** [comment]
/retest
@thockin can we merge this early in this cycle to check that is not causing additional problems soon?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by yogeek** [comment]
Hi @aojea !

I encountered this bug and finally find this ticket : thank you for that.

As I cannot upgrade my cluster to 1.19 currently, I have an additionnal question please :

if I understood correcly, the information "the nodeport is deleted" is stored only locally on the master that received the `kubectl delete` command and not synched with other masters. 
And so, if the next `kubectl apply -f svc.yml` is processed by another master, he does not have this information and thinks that this port is still allocated.

So do you confirm that if I launch `kubectl apply -f svc.yml` several times, I may be load balanced on the "good" master (the one that knows the nodeport has been deleted) which is going to accept my command without error ?
=> In this case, I could achieve my action by repeating the same command a few times.

Or does the local "state" of the master will be known after a certain time by the others in the current state (i mean without this fix) ? Or if my command is always targeting the other nodes, it will indefinitely fail... ?
=> In this case, I could achieve my action by waiting a certain amount of time...

Thanks !

**Comment by aojea** [comment]
> As I cannot upgrade my cluster to 1.19 currently, I have an additionnal question please :

it can be backported to supported versions if you are interested, if I recall correctly last supported version is 1.16

> Or does the local "state" of the master will be known after a certain time by the others in the current state (i mean without this fix) ? Or if my command is always targeting the other nodes, it will indefinitely fail... ?

The port information eventually will be synchronised in all the apiservers ... retrying, waiting and using always the same master will solve the problem

**Comment by yogeek** [comment]
@aojea I am interested for this fix to be backport to 1.17 and 1.18 if possible.

`The port information eventually will be synchronised in all the apiservers`

What process is responsible for that synchronisation please ?

**Comment by aojea** [comment]
> What process is responsible for that synchronisation please ?

https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/registry/core/service/ipallocator/controller/repair.go

cherry picks 

https://github.com/kubernetes/kubernetes/pull/96816 1.18
https://github.com/kubernetes/kubernetes/pull/96817 1.17

**Comment by yogeek** [comment]
Nice thanks a lot !
