### PR TITLE
Replaced util.NewIOHandler() with fakeIOHandler to make UT pass on different host envs

### LINKED ISSUE #128963: [FAILING Test] UT TestSearchDisk fails when multipath device mapper device is found
### Which jobs are failing?

k8s.io/kubernetes/pkg/volume: fc TestSearchDisk at:
https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-tests-non-root-ppc64le/1860941588411191296

### Which tests are failing?

`k8s.io/kubernetes/pkg/volume: fc TestSearchDisk`

### Since when has it been failing?

`Nov 22, 2024`

### Testgrid link

_No response_

### Reason for failure (if possible)

Test is failing in envs where multipath device mapper is configured.

```
[root@debugging  kubernetes]# go test -run ^TestSearchDisk$ k8s.io/kubernetes/pkg/volume/fc
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
I1125 12:49:05.934534  155946 fc_util.go:74] fc: find disk: /dev/sda, dm: /dev/dm-0, fc path: pci-0000:41:00.0-fc-0x500a0981891b8dc5-lun-0
I1125 12:49:05.934710  155946 fc_util.go:74] fc: find disk: /dev/sdb, dm: /dev/dm-0, fc path: pci-0000:41:00.0-fc-0x500a0981891b8dc5-lun-1
I1125 12:49:05.934846  155946 fc_util.go:74] fc: find disk: /dev/sdc, dm: /dev/dm-0, fc path: fc-0x5005076810213b32-lun-2
--- FAIL: TestSearchDisk (0.00s)
    --- FAIL: TestSearchDisk/PCI_disk_0 (0.00s)
        fc_util_test.go:181: matching wrong disk, expected: /dev/sda, actual: /dev/dm-0
    --- FAIL: TestSearchDisk/PCI_disk_1 (0.00s)
        fc_util_test.go:181: matching wrong disk, expected: /dev/sdb, actual: /dev/dm-0
    --- FAIL: TestSearchDisk/Non_PCI_disk (0.00s)
        fc_util_test.go:181: matching wrong disk, expected: /dev/sdc, actual: /dev/dm-0
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/fc	0.018s
FAIL
```

### Anything else we need to know?

This is reproduced on `ppc64le` arch.

### Relevant SIG(s)

/sig storage

### PR DESCRIPTION
**Pull request by srivastav-abhishek**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
In some envs, `searchDisk` func returns a `multipath devicemapper device` instead of raw disk. Added check for same to fix UT.

#### Which issue(s) this PR fixes:

Fixes #128963

#### Special notes for your reviewer:
This issue is observed on `ppc64le` arch.
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by huww98** [comment]
How can we reproduce the failure? Given that the test is written in go, and all the IO operations are mock, the result should not change across different arch.

**Comment by huww98** [comment]
I think we should replace `util.NewIOHandler()` with `fakeIOHandler` to make sure we are not affected by host env.

**Comment by srivastav-abhishek** [comment]
> I think we should replace `util.NewIOHandler()` with `fakeIOHandler` to make sure we are not affected by host env.

I agree that UT shouldn't be affected by host env. I will add changes as suggested. TY !!

File: pkg/volume/fc/fc_util_test.go [hunk 1]
```diff
@@ -177,7 +178,7 @@ func TestSearchDisk(t *testing.T) {
 			if devicePath == "" && !test.expectError {
 				t.Errorf("no fc disk found")
 			}
-			if devicePath != test.disk {
+			if devicePath != test.disk && !strings.HasPrefix(devicePath, "/dev/dm") {
```
[the remark this answers is not in the document]
Comment (srivastav-abhishek) [reply pkg/volume/fc/fc_util_test.go:181]: Yes, it's a challenge to identify and implement. For now, as @huww98 suggested, we can use `fakeIOHandler ` instead of `util.NewIOHandler()`

**Comment by srivastav-abhishek** [comment]
> @srivastav-abhishek can you please remove `ppc64le` reference from the PR? because this can happen on any machine with multipath enabled.

Updated it. Thanks :)

**Comment by Rajalakshmi-Girish** [comment]
@huww98 / @jingxu97 Can you PTAL now? @srivastav-abhishek has implemented the suggested change.

**Comment by huww98** [comment]
/lgtm
I'm not experienced with fc, but I think this change is fine so long as it does not break the existing tests. Maybe we should add more test cases for multipath devices in the future.

**Comment by srivastav-abhishek** [comment]
@jsafrane Could you please specify if `fake io.LStat` is to check whether its part of multipath or not. This can be achieved with [this](https://github.com/kubernetes/kubernetes/pull/128997#discussion_r1862775335) also. `io.Lstat` just returns  a `fileinfo` describing the named file, if present. I think I am missing something. Any references would be helpful ? Thanks !

**Comment by srivastav-abhishek** [comment]
@jsafrane UT for multipath device is WIP, I will add it as part of follow up PR. I hope that is fine :)

File: pkg/volume/fc/fc_util.go [hunk 2]
```diff
@@ -196,6 +196,10 @@ func (util *fcUtil) MakeGlobalVDPDName(fc fcDisk) string {
 	return makeVDPDNameInternal(fc.plugin.host, fc.wwns, fc.lun, fc.wwids)
 }
 
+func parseDeviceName(devicePath string) string {
+	return strings.TrimPrefix(devicePath, "/dev/")
+}
```
Comment (jsafrane) [inline pkg/volume/fc/fc_util.go:201]: This is used only in unit tests, please move it to fc_util_test.go. If it is needed at all.

File: pkg/volume/fc/fc_util_test.go [hunk 3]
```diff
@@ -177,7 +187,12 @@ func TestSearchDisk(t *testing.T) {
 			if devicePath == "" && !test.expectError {
 				t.Errorf("no fc disk found")
 			}
-			if devicePath != test.disk {
+			// parsing device and disk name
+			devName := parseDeviceName(devicePath)
+			disk := parseDeviceName(test.disk)
+			// checking if device is a multpath devicemapper device
+			_, err = fakeMounter.fcDisk.io.Lstat(sysPath + devName + "/slaves/" + disk)
+			if devicePath != test.disk && err != nil {
```
Comment (jsafrane) [inline pkg/volume/fc/fc_util_test.go:195]: I may remember wrong, but was there an attempt to use `fakeIOHandler` to construct `NewDeviceHandler` above in some previous version? Because that's the right way to go, mock everything that fc_util.go needs from the OS, so it runs everywhere.

Comment (srivastav-abhishek) [reply pkg/volume/fc/fc_util_test.go:195]: Yes, in previous version `fakeIOHandler` was used but then unit test didn't go through whole code as mentioned [here](https://github.com/kubernetes/kubernetes/pull/128997#issuecomment-2541286143). So I kept `util.NewIOHandler()` with `fake Lstat`. I shall update it with `fakeIOHandler` with necessary mocks everywhere. Thanks !
