### PR TITLE
suppress libseccomp pkg-config errors

### LINKED ISSUE #79499: hack/update-bazel produces warnings
**What happened**:
Got the following error while trying to run `hack/update-bazel.sh`:
```
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: pkg-config not supported: #cgo pkg-config: libseccomp
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: pkg-config not supported: #cgo pkg-config: libseccomp
``` 

**How to reproduce it (as minimally and precisely as possible)**:
Ran this on a fresh install of ubuntu 19.04, Go 1.12.6, and bazel 0.26.1.

**Anything else we need to know?**:
Seems like the change might have been due to the update in vendored deps from #78187 ( https://github.com/kubernetes/kubernetes/pull/78187#discussion_r294546736 ).
Although this script is run in CI where it is working so may be some set of recommende pkg versions would help prevent this problem?

**Environment**:
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 19.04
- Kernel (e.g. `uname -a`): 5.0.0-15-generic
- bazel: 0.26.1
- Go: 1.12.6

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Suppresses the following gazelle output in `hack/update-bazel.sh`

```
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp.go: pkg-config not supported: #cgo pkg-config: libseccomp
gazelle: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: error reading go file: /home/user/go/src/k8s.io/kubernetes/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go: pkg-config not supported: #cgo pkg-config: libseccomp
```

These errors are known, and we already worked around this in https://github.com/kubernetes/kubernetes/pull/79287

We do not expect the root cause to change in the forseeable future.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/79499

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: hack/update-bazel.sh [hunk 1]
```diff
@@ -62,11 +62,15 @@ for repo in "${staging_repos[@]}"; do
...
+# filter out known pkg-config error (see buildozer workaround below)
+# NOTE: the `|| exit "${PIPESTATUS[0]}"` is to ignore grep errors 
+# while preserving the exit code of gazelle
 gazelle fix \
     -external=vendored \
     -mode=fix \
     -repo_root "${KUBE_ROOT}" \
-    "${KUBE_ROOT}"
+    "${KUBE_ROOT}" \
+    2>&1 | grep -Ev "vendor/github.com/seccomp/libseccomp-golang/seccomp(_internal)?.go: pkg-config not supported: #cgo pkg-config: libseccomp" || (exit "${PIPESTATUS[0]}")
```
Comment (BenTheElder) [inline hack/update-bazel.sh]: Open to better ideas for this. `grep` sets an exit code itself based on matching and I couldn't find an option to prevent this. AFAICT this works as intended though.

I tested adding bogus flags to `gazelle` to reliably cause an error and the script exited with an error properly with this workaround.

Comment (BenTheElder) [reply hack/update-bazel.sh]: original thread about possibly doing something like this, without much response ... https://github.com/kubernetes/kubernetes/pull/79287#discussion_r296493509

**Comment by tedyu** [comment]
Please correct the typo in the subject: supress

**Comment by BenTheElder** [comment]
anyone can do that now! 🙃 
/retitle suppress libseccomp pkg-config errors

**Review by alejandrox1 — APPROVED** [review]
Thank you for always coming to the rescue, Ben!
/lgtm
/hold

File: hack/update-bazel.sh (hunk 1 above)
Comment (odinuge) [reply hack/update-bazel.sh]: Looks like this works. 👍 

I guess it would also be possible to store the output in a variable instead of sending it through `grep` via a pipe? That should solve the problem with the return value too. Not sure what the optimal solution is tho

```bash
GAZELLE_OUT=$(gazelle fix ....)

grep -Ev "pattern" <<< ${GAZELLE_OUT}
```

Comment (BenTheElder) [reply hack/update-bazel.sh]: Since we have errexit you would never see the output on failure if we did it this way 😬

Comment (odinuge) [reply hack/update-bazel.sh]: Ahh, yee, totally forgot that! 🙃

**Review by spiffxp — APPROVED** [review]
/lgtm
