### PR TITLE
Make a certain ipv4-vs-ipv6 config error non-fatal, for backward compat

### LINKED ISSUE #120999: kube-proxy fails to start for IPv6 when underlying infra is dual stack in 1.28
### What happened?

A new  kube-proxyvalidation introduced in k8s 1.28 seems to break Azure + ipv6. IPv6 clusters on Azure run on dual-stack hosts. The IPv6 node IP seems like it's only getting assigned to the Node until after kube-proxy starts (someone might need to help me understand what component is responsible). However, kube-proxy now fails to start with:

kube-proxy is in CrashloopBackoff, logs show:

``` 
I0825 16:18:19.872382       1 server_others.go:69] "Using iptables proxy"
I0825 16:18:19.892673       1 node.go:141] Successfully retrieved node IP: 10.1.0.6
I0825 16:18:19.894163       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=131072
I0825 16:18:19.912200       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
E0825 16:18:19.912228       1 server.go:537] "Error running ProxyServer" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"
E0825 16:18:19.912240       1 run.go:74] "command failed" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"
```

Full logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4086/pull-cluster-api-provider-azure-conformance-ipv6-with-ci-artifacts/1709361655076360192/artifacts/clusters/capz-conf-klo2dh/

### What did you expect to happen?

Kube-proxy should start. This does not repro with prior versions of k8s (1.27 and below). 

### How can we reproduce it (as minimally and precisely as possible)?

- Build a Kubernetes cluster with v1.28 on Azure (underlying subnet has both IPv6 and Ipv4 addresses) with Kubeadm (e.g. CAPZ), configure the cluster CIDRs to single stack IPv6 (detailed instructions in https://capz.sigs.k8s.io/topics/ipv6)
- Observe the kube-proxy pod is crashing

This repros consistently

### Anything else we need to know?

This new validation was introduced in https://github.com/kubernetes/kubernetes/pull/119003

### Kubernetes version

v1.28.0 and above

### Cloud provider

Azure

### OS version

Linux version 6.2.0-1011-azure

### Install tools

CAPZ

### Container runtime (CRI) and version (if applicable)

revision=b69f1ad231b6d87eeb30504398075a92d615e83e version=v1.6.23

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Calico CNI (Calico fails to start due to crashing kube-proxy)

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug
/kind regression
/sig network
/priority important-soon

#### What this PR does / why we need it:
kube-proxy historically allowed badly-mismatched bits of configuration (e.g., specifying an IPv6 `--cluster-cidr` value on a seemingly dual-stack-IPv4-primary node). In 1.28 I consolidated the existing checks and added a bunch more, but I accidentally made one case fatal which had not been fatal in prior releases. This makes it just a warning again.

(It is still fatal to specify an IPv6 `--cluster-cidr` on a _necessarily_ single-stack-IPv4 node (e.g., when kernel IPv6 is disabled).)

#### Which issue(s) this PR fixes:
Fixes #120999

#### Does this PR introduce a user-facing change?
```release-note
Fixed a regression in kube-proxy where it might refuse to start if given
single-stack IPv6 configuration options on a node that has both IPv4 and
IPv6 IPs.
```

### CODE REVIEW

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -678,7 +678,7 @@ func checkIPConfig(s *ProxyServer, dualStackSupported bool) (error, bool) {
 		clusterCIDRs := strings.Split(s.Config.ClusterCIDR, ",")
 		if badCIDRs(clusterCIDRs, badFamily) {
```
Comment (aojea) [inline cmd/kube-proxy/app/server.go:679]: this function `badCidrs` only checks that the first cidr in the array is different than the badFamily, but the comment of the function seems to assume all the cidrs are not `badFamily`

> // badCIDRs returns true if cidrs is a non-empty list of CIDRs, all of wrongFamily.

just for my curiosity, the comment is wrong, right?

Comment (CecileRobertMichon) [reply cmd/kube-proxy/app/server.go:679]: I think the comment wording is weird but should be

> // badCIDRs returns true if cidrs is a non-empty list of CIDRs and all are of wrongFamily.

essentially if the list is empty, or as soon as it finds a "good" CIDR that's not of wrongFamily it returns false.

**Review by CecileRobertMichon — COMMENTED** [review]
lgtm

Is it possible to cherry-pick this to release-1.28?

**Comment by aojea** [comment]
> lgtm
> 
> Is it possible to cherry-pick this to release-1.28?

yes, it is

**Comment by CecileRobertMichon** [comment]
/retest

seems like the failures are unrelated (flakes?)

File: cmd/kube-proxy/app/server.go (hunk 1 above)
Comment (danwinship) [reply cmd/kube-proxy/app/server.go:679]: > this function `badCidrs` only checks that the first cidr in the array is different than the badFamily

No, it loops over all of the CIDRs, but bails out early in some cases. The semantics of the function are sort of confusing, so it's hard for the comment to be both concise and non-confusing...

There are three possibilities:
- `cidrs` is empty, meaning the admin isn't claiming anything about what the primary IP family is, so we don't learn anything about whether there is a config problem or not.
- `cidrs` is non-empty and contains at least one CIDR of the same family as nodeIP, meaning the admin is expecting that IP family to be in use, meaning it's OK that we detected nodeIP to be of that family.
- `cidrs` is non-empty and contains only CIDRs of the opposite IP family from nodeIP, meaning the admin is asserting that this is a single-stack cluster of that family, meaning our detected nodeIP is wrong.

`badCIDRs` returns `false` in the first two cases and `true` in the third.

Comment (aojea) [reply cmd/kube-proxy/app/server.go:679]: great, thanks for clarifying
