### PR TITLE
Return more useful error information when a persistent volume fails to mount

### LINKED ISSUE #22992: UXP: kubelet volume mount errors are not surfacing properly for true root cause in 'kubectl describe' leading to confusing generic error message on failed mounts
fyi @smarterclayton @pweil @pmorie
When using PV/PVC for Persistent Volume volume mounts, if something goes wrong in the builder, a generic error is surfaced in the 'kubectl describe' with the following event error description *unsupported volume type":

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  14s		14s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bb-gluster-pod2 to 127.0.0.1
  14s		14s		1	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-gluster-pod2_default(3ff651a5-eabf-11e5-b3b1-52540092b5fb)": unsupported volume type
  14s		14s		1	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: unsupported volume type
```

This only occurs when using the PV/PVC abstraction and not directly using a volume plugin.  These type of errors are common when using volume plugins for mounts and would be useful for users to have an easy way to identify the errors rather than searching the logs for root cause.

I think there are two issues:
1.  Why is the original error surfaced from the volume plugins (glusterfs.go, rbd.go, etc...) getting eaten when they return back to the volumes.go?  I can see in the logs that 2 volume types are processed for any pod - the first is the actual underlying type (i.e. kubernetes.io/glusterfs) and this is where the actual real error is surfaced, then immediately after this the 2nd type is processed which is the general  persistent claim type (i.e. kubernetes.io/persistent-claim) and this when the first type error is eaten
2.  A simple work around would be to simply add a recorder event in the volumes.go when there is a builder failure.  This ensures the error is recorded and displayed as an event for the describer and will handle all like errors from other volume plugin types.

full modifed function for reference from volumes.go
```
func (kl *Kubelet) newVolumeBuilderFromPlugins(spec *volume.Spec, pod *api.Pod, opts volume.VolumeOptions) (volume.Builder, error) {
	plugin, err := kl.volumePluginMgr.FindPluginBySpec(spec)
	if err != nil {
		return nil, fmt.Errorf("can't use volume plugins for %s: %v", spec.Name(), err)
	}
	if plugin == nil {
		// Not found but not an error
		return nil, nil
	}
	builder, err := plugin.NewBuilder(spec, pod, opts)
	if err != nil {
                // Add kubelet recorder event so the real error shows in the 'kubectl describe <pod>' event list
		ref, errGetRef := api.GetReference(pod)
		if errGetRef == nil && ref != nil {
			kl.recorder.Eventf(ref, api.EventTypeWarning, kubecontainer.FailedMountVolume, "Unable to mount volumes for pod %q: %v", format.Pod(pod), err)
			glog.Errorf("Unable to mount volumes for pod %q: %v; skipping pod", format.Pod(pod), err)
		}
		return nil, fmt.Errorf("failed to instantiate volume plugin for %s: %v", spec.Name(), err)
	}

	glog.V(10).Infof("Used volume plugin %q to mount %s", plugin.Name(), spec.Name())
	return builder, nil
}
```

This will produce a better user experience when trying to see what went wrong - in this example, I am doing glusterfs PV/PVC but am missing end points which you can clearly see now in the events of the describe:

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  12s		12s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bb-gluster-pod2 to 127.0.0.1
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-gluster-pod2_default(2b10a2c3-eac7-11e5-ac70-52540092b5fb)": endpoints "glusterfs-cluster" not found
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-gluster-pod2_default(2b10a2c3-eac7-11e5-ac70-52540092b5fb)": unsupported volume type
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: unsupported volume type
```

rbd example: (Missing or Couldn't get secret)

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  12s		12s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bb-gluster-pod2 to 127.0.0.1
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-rbd-pod2_default(2b10a2c3-eac7-11e5-ac70-52540092b5fb)": Couldn't get secret
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-rbd-pod2_default(2b10a2c3-eac7-11e5-ac70-52540092b5fb)": unsupported volume type
  12s		12s		1	{kubelet 127.0.0.1}			Warning		FailedSync	Error syncing pod, skipping: unsupported volume type
```

### LINKED ISSUE #23048: UXP: generic volume error - 'unsupported volume type' should be reworded
in volumes.go there is a generic error variable defined that is used when a failure occurs and no other error is surfaced, it is a catch-all when something goes wrong.

```
var errUnsupportedVolumeType = fmt.Errorf("unsupported volume type")
```

Think this should be reworded to something that is more reflective of the true issue and not so confusing for users.  This error mostly comes when a builder can not be created and it is typically not true that the volume type is unsupported, but rather some other underlying issue, such as missing secrets or endpoints or etc...

propose something like:

```
"failed volume mount, check previous pod describe events or logs for more details"  
```

or

```
"volume mount error - make sure the volume type is supported and also check previous pod describe events or logs for a more accurate root cause explanation"
```

### PR DESCRIPTION
**Pull request by screeley44**
Fixes #22992  
Fixes #23048   - resolves following issues - UXP issues

volume plugin type errors are not being surfaced to pod describe events properly when a failure occurs with PV/PVC volume building - for example plugin builder fails if secrets or endpoints are missing (rbd or glusterfs).  The user only sees a generic error that has incorrect meaning "unsupported volume type"

see issues  #22992 and #23048 for more details

### CODE REVIEW

**Comment by screeley44** [comment]
@smarterclayton @pmorie @pweil-  please review

File: pkg/kubelet/volumes.go [hunk 1]
```diff
@@ -34,7 +35,7 @@ import (
 	"k8s.io/kubernetes/pkg/volume"
 )
 
-var errUnsupportedVolumeType = fmt.Errorf("unsupported volume type")
+var errUnsupportedVolumeType = fmt.Errorf("failed volume mount, check previous pod describe events or logs for more details")
```
Comment (pweil-) [inline pkg/kubelet/volumes.go]: @screeley44 @pmorie - I took a look at the usages of this error.  It looks like some of the usages (`NewWrapperBuilder`, `NewWrapperCleaner`) will actually hide the underlying error from the `New*` call and some don't (`mountExternalVolumes`).  Should we go ahead and standardize that too?  

I'll defer to folks who are in this code more than me.

**Comment by pmorie** [comment]
There are a few different problems to untangle here:

1.  `NewWrapperBuilder` and `NewWrapperCleaner` in `volumes.go` both swallow errors when making their respective result objects; we should instead be passing those back
2.  `newVolumeBuilderFromPlugins` should return a nil and an error, or a builder and no error, and not locating a volume plugin should be considered an error.  Remove the check for a nil builder in `mountExternalVolumes`
3.  `unsupported volume type` doesn't mean anything to anyone -- the error message for this case should be something like "Unable to find a volume plugin that can handle volume of type X` -- there's some overlap with the stuff @pweil is doing with volumes and OpenShift SCCs (which is not yet ported upstream) that has some code for getting user-facing labels from Volume specs that could be used to provide a meaningful guess at the volume type, but I think in practice this error message should almost never happen.

I believe if we make these changes both the error message in the pod status and the message in the event will have the accurate root cause.

How does that sound @screeley44 @pweil-?

cc @saad-ali @thockin

**Comment by pweil-** [comment]
> NewWrapperBuilder and NewWrapperCleaner in volumes.go both swallow errors when making their respective result objects; we should instead be passing those back

Yes, agree

> newVolumeBuilderFromPlugins should return a nil and an error, or a builder and no error, and not locating a volume plugin should be considered an error. Remove the check for a nil builder in mountExternalVolumes

I like this better.  I noticed in the review (https://github.com/kubernetes/kubernetes/pull/23122#discussion_r56539362) that we have to go through extra gyrations because methods can return `nil, nil` which is "acceptable" but then just turned into an error anyway.  I'd rather bubble a "plugin not registered" or similar error and change the calling code to be more simple.

**Comment by saad-ali** [comment]
:+1: to @pmorie's suggestions

**Comment by dchen1107** [comment]
+1 on @pmorie's comment: https://github.com/kubernetes/kubernetes/pull/23122#issuecomment-198203694

@screeley44 Are you going to continue with pr with @pmorie's suggestion?

**Comment by screeley44** [comment]
@dchen1107 @pmorie -  Yes, I would like to continue, I've been off for spring break and Easter but back now and plan on picking back up on this

**Comment by screeley44** [comment]
@pmorie  @pweil-    please review what I did, I think this will expose all root cause errors to the user in the describe event as I tried to thoroughly test all conditions, but maybe I missed something or could have done something in a better way.

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  12s		12s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bb-gluster-pod2 to 127.0.0.1
  12s		1s		2	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-gluster-pod2_default(9fd3f3a2-f61a-11e5-b038-52540092b5fb)": failed to instantiate volume: glustervol for plugin: kubernetes.io/persistent-claim with root cause: failed to instantiate volume: pv-gluster for plugin: kubernetes.io/glusterfs with root cause: endpoints "glusterfs-cluster" not found
```

I also removed the errUnsupportedVolumeType generic error and added a method, I tried to replicate error scenarios where that might get called, but I really couldn't find any, but maybe doesn't hurt to keep around just in case?

**Comment by screeley44** [comment]
@dchen1107  -  any thoughts on this so far?

**Comment by erinboyd** [comment]
@pmorie @saad-ali @pweil- @smarterclayton where are we with this? Can we please merge this before ANOTHER rebase?

**Comment by smarterclayton** [comment]
@kubernetes/sig-storage

File: pkg/kubelet/volumes.go [hunk 2]
```diff
@@ -34,8 +34,6 @@ import (
 	"k8s.io/kubernetes/pkg/volume"
 )
 
-var errUnsupportedVolumeType = fmt.Errorf("unsupported volume type")
-
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Hmm.. do we really not need this or can we move it somewhere where we are sure that the volume is not supported ?

File: pkg/kubelet/volumes.go [hunk 3]
```diff
@@ -66,10 +64,16 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
...
+		return nil, err
 	}
-	return b, nil
+	if b != nil {
+		// return good volume mounter
+		return b, nil
+	}
+
+	// generic volume type error
+	return nil, createVolumeTypeError(volName)
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: can the above be replaced with:
```go
return vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
```
?

File: pkg/kubelet/volumes.go [hunk 4]
```diff
@@ -87,11 +91,22 @@ func (vh *volumeHost) NewWrapperUnmounter(volName string, spec volume.Spec, podU
...
+		return nil, err
+	}
+	if c != nil {
+		// return good volume unmounter
+		return c, nil
 	}
-	return c, nil
+
+	// generic volume type error
+	return nil, createVolumeTypeError(volName)
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Same comment as above

File: pkg/kubelet/volumes.go [hunk 5]
```diff
@@ -87,11 +91,22 @@ func (vh *volumeHost) NewWrapperUnmounter(volName string, spec volume.Spec, podU
...
+}
+
+func createVolumeTypeError(volName string) error {
+	return fmt.Errorf("Unable to mount volume or unsupported volume type for volume: %s for plugin: Unknown - check logs or pod describe events for possible root cause", volName)
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Hmm... I am not sure if we should prefix errors with all of that.
For example I think that:

`endpoints "glusterfs-cluster" not found`

provides better use experience than:

`FailedMount Unable to mount volumes for pod "bb-gluster-pod2_default(9fd3f3a2-f61a-11e5-b038-52540092b5fb)": failed to instantiate volume: glustervol for plugin: kubernetes.io/persistent-claim with root cause: failed to instantiate volume: pv-gluster for plugin: kubernetes.io/glusterfs with root cause: endpoints "glusterfs-cluster" not found`

Then again the underlying error might require explanation. Here I think we can get away with not prefixing and just returning the error. If the underlying error is too cryptic we can fix it at the point where it is generated.

File: pkg/kubelet/volumes.go [hunk 6]
```diff
@@ -132,8 +147,9 @@ func (kl *Kubelet) mountExternalVolumes(pod *api.Pod) (kubecontainer.VolumeMap,
 			glog.Errorf("Could not create volume mounter for pod %s: %v", pod.UID, err)
 			return nil, err
 		}
+		//This should never be hit if there is a failure in mounter - probably can remove??
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: I think it is reachable unless I am missing something.
`newVolumeMounterFromPlugins` can return `nil, nil` although `FindPluginBySpec` which it calls never returns `nil, nil`
I think it is safe to remove but might as well leave it for completeness. Eitherway I would remove the comment above

File: pkg/kubelet/volumes.go [hunk 7]
```diff
@@ -132,8 +147,9 @@ func (kl *Kubelet) mountExternalVolumes(pod *api.Pod) (kubecontainer.VolumeMap,
...
 		if mounter == nil {
-			return nil, errUnsupportedVolumeType
+			return nil, createVolumeTypeError(internal.Volume.Name)
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: I guess this would be an unknown error because when the plugin is not found you usually get an error.

File: pkg/kubelet/volumes.go (hunk 5 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: yeah, so what you are seeing here, is the result of two volume types producing errors, if the user was not using PVC/PV then you would only see the error associated with the underlying source volume (i.e. glusterfs type) but with PVC and PV types you also get another type of persistent-claim with no real error other than it fails but the real error comes from the underlying source plugin type.  So I guess we could repress the generic persistent-claim error and only show the underlying issue from the source type??

File: pkg/kubelet/volumes.go [hunk 8]
```diff
@@ -243,7 +259,7 @@ func (kl *Kubelet) getPodVolumesFromDisk() map[string]cleanerTuple {
 				continue
 			}
 			if unmounter == nil {
-				glog.Errorf("Could not create volume unmounter for %s: %v", volume.Name, errUnsupportedVolumeType)
+				glog.Errorf("Could not create volume unmounter for %s: %v", volume.Name, createVolumeTypeError(volume.Name))
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: This is also an unknown error because when the plugin is not found you get an error message.

File: pkg/kubelet/volumes.go [hunk 9]
```diff
@@ -274,7 +290,7 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
 	}
 	physicalMounter, err := plugin.NewMounter(spec, pod, opts)
 	if err != nil {
-		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for %s: %v", spec.Name(), err)
+		return nil, fmt.Errorf("failed to instantiate volume: %s for plugin: %s with root cause: %v", spec.Name(), plugin.Name(), err)
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: physicalMounter is accurate here.. please leave it in

File: pkg/kubelet/volumes.go (hunk 2 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: this is removed and replaced with a more generic error  createVolumeTypeError - which in theory should never be called from what I can tell, so I was asking if we can remove it all together (errUnsupportedVolumeType was original and I removed in this PR) but replaced with a function to eventually help generate a better error...but as I wondered in the PR I don't know if that error would ever get hit, since if the mounter fails in anyway that error is now surfaced where as before it wasn't...so wonder if we can remove altogether or keep around for some unforeseen scenario??  @swagiaal

Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Okay I am convinced it is not needed after reading the rest of the patch :)

File: pkg/kubelet/volumes.go (hunk 8 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: yeah, and now that wrappers are not eating errors, I think this would most likely never get called since the err would not be nil and it would be surfaced, I left it just because of cases that *might* happen. 
The idea behind the "createVolumeTypeError" was to replace the errUnsupportedVolumeType - which really meant nothing and was inaccurate, so I wanted a "generic" error for these unknown conditions that might pop up and wanted to find a way to give the user some more useful information (i.e. name of the volume from the spec and ideally the acutal plugin type - but plugin type was proving difficult, so figured at least giving the volume.Name was more useful for users than an error saying "Volume Type is Not Supported"   @swagiaal

File: pkg/kubelet/volumes.go (hunk 5 above)
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: > yeah, so what you are seeing here, is the result of two volume types producing errors, if the user was not using PVC/PV then you would only see the error associated with the underlying source volume (i.e. glusterfs type with the true root cause of missing endpoints) ... but with PVC and PV types you also get another type of persistent-claim with no real error other than it fails at the mounter level but the real error comes from the underlying source plugin type.

Gotcha!

> So I guess we could repress the generic persistent-claim error and only show the underlying issue from the source type??

I think that would be right thing to do. Not prefix errors unless they are too cryptic so that the use would not have to parse through a lot of boiler plate to get to the real issue. I would do that in a separate PR though or open an issue so it is not forgotten.

The instance in this PR though should be addressed here.

File: pkg/kubelet/volumes.go (hunk 8 above)
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: That makes sense.. especially after rereading the error message :). I am ok with this as is

File: pkg/kubelet/volumes.go (hunk 2 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: It should not be needed, and there's no utility to keeping it around 'just in case'.  YAGNI

File: pkg/kubelet/volumes.go (hunk 5 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: We need to expose the actual error wherever possible; don't eat errors, and don't add vague text to errors.  Think about it from the user's perspective -- we want to give them the information most relevant to solving the problem.

File: pkg/kubelet/volumes.go [hunk 10]
```diff
@@ -66,10 +64,16 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
 	}
 
 	b, err := vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: @screeley44 see my earlier feedback: `newVolumeMounterFromPlugins` should return a mounter and a nil error, or a nil mounter and a non-nil error, but never (nil, nil)

Comment (pmorie) [inline pkg/kubelet/volumes.go]: `newVolumeMounterFromPlugins` should return an error if there's no suitable volume plugin.

File: pkg/kubelet/volumes.go (hunk 4 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I have same concern as I articulated above.  `NewUnmounter` should never, ever return (nil, nil).

File: pkg/kubelet/volumes.go (hunk 5 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: To make it explicit, we should not need this error.

File: pkg/kubelet/volumes.go (hunk 8 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: We should not need to check for a nil unmounter.  Never return (nil, nil) from a method like this.

File: pkg/kubelet/volumes.go (hunk 10 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: no more nil, nil being returned from any of the functions - also no errors are being eaten, so any issue will be surfaced - think this addresses your concern @pmorie

File: pkg/kubelet/volumes.go [hunk 11]
```diff
@@ -268,13 +272,9 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
...
 		return nil, fmt.Errorf("can't use volume plugins for %s: %v", spec.Name(), err)
 	}
-	if plugin == nil {
-		// Not found but not an error
-		return nil, nil
-	}
 	physicalMounter, err := plugin.NewMounter(spec, pod, opts)
 	if err != nil {
-		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for %s: %v", spec.Name(), err)
+		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for: %s for plugin: %s with root cause: %v", spec.Name(), plugin.Name(), err)
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: `physicalMounter for volume:` plz

File: pkg/kubelet/volumes.go [hunk 12]
```diff
@@ -285,10 +285,6 @@ func (kl *Kubelet) newVolumeAttacherFromPlugins(spec *volume.Spec, pod *api.Pod,
 	if err != nil {
 		return nil, fmt.Errorf("can't use volume plugins for %s: %v", spec.Name(), err)
 	}
-	if plugin == nil {
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I think this has to stay because not all plugins are necessarily attachable.

File: pkg/kubelet/volumes.go [hunk 13]
```diff
@@ -83,15 +87,22 @@ func (vh *volumeHost) NewWrapperUnmounter(volName string, spec volume.Spec, podU
 	if err != nil {
 		return nil, err
 	}
-	if plugin == nil {
-		// Not found but not an error
-		return nil, nil
-	}
+
 	c, err := plugin.NewUnmounter(spec.Name(), podUID)
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I think it would be an improvement if `c` was renamed to `unmounter`

File: pkg/kubelet/volumes.go (hunk 10 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: let's rename `b` to `mounter`

File: pkg/kubelet/volumes.go [hunk 14]
```diff
@@ -66,10 +64,16 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
 	}
 
 	b, err := vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
-	if err == nil && b == nil {
-		return nil, errUnsupportedVolumeType
+	if err != nil {
+		return nil, err
 	}
-	return b, nil
+	if b != nil {
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: This check _should_ be unnecessary now.

File: pkg/kubelet/volumes.go [hunk 15]
```diff
@@ -323,10 +317,6 @@ func (kl *Kubelet) newVolumeDetacherFromPlugins(kind string, name string, podUID
 	if err != nil {
 		return nil, fmt.Errorf("can't use volume plugins for %s/%s: %v", podUID, kind, err)
 	}
-	if plugin == nil {
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: This is also a valid state because not every volume has a detacher

File: pkg/kubelet/volumes.go [hunk 16]
```diff
@@ -300,15 +296,13 @@ func (kl *Kubelet) newVolumeAttacherFromPlugins(spec *volume.Spec, pod *api.Pod,
 
 func (kl *Kubelet) newVolumeUnmounterFromPlugins(kind string, name string, podUID types.UID) (volume.Unmounter, error) {
 	plugName := strings.UnescapeQualifiedNameForDisk(kind)
+	glog.Infof("--- Scott - plugName = %s", plugName)
```
Comment (markturansky) [inline pkg/kubelet/volumes.go]: debug statement

File: pkg/kubelet/volumes.go (hunk 12 above)
Comment (markturansky) [inline pkg/kubelet/volumes.go]: like @pmorie's comment on Detacher below, this is also valid.  Not every volume plugin will have an attacher.

Comment (markturansky) [inline pkg/kubelet/volumes.go]: Correct for the Attachable bit.  This is for the volume plugin itself.

I think returning `nil, nil` is an error at this point.  No plugin was found to satisfy the volume spec.

Comment (swagiaal) [inline pkg/kubelet/volumes.go]: I think it is okay to remove this because FindPluginBySpec does not return nil,nil. If you did not get an error you are getting a plugin.

File: pkg/kubelet/volumes.go [hunk 17]
```diff
@@ -65,11 +63,13 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
...
-	if err == nil && b == nil {
-		return nil, errUnsupportedVolumeType
+	// newVolumeMounterFromPlugins can only return a valid mounter or an error
+	mounter, err := vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
+	if err != nil {
+		return nil, err
 	}
-	return b, nil
+
+	return mounter, nil
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: you don't need to check the return values here if you are just returning them. Just `return vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)` should do it

File: pkg/kubelet/volumes.go [hunk 18]
```diff
@@ -79,19 +79,20 @@ func (vh *volumeHost) NewWrapperUnmounter(volName string, spec volume.Spec, podU
...
+
+	// NewUnmounter can only return a valid unmounter or an error
+	unmounter, err := plugin.NewUnmounter(spec.Name(), podUID)
+	if err != nil {
+		return nil, err
 	}
-	return c, nil
+
+	return unmounter, nil
 }
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Same here unless I am missing something.
`return plugin.NewUnmounter(spec.Name(), podUID)`

File: pkg/kubelet/volumes.go (hunk 12 above)
Comment (markturansky) [inline pkg/kubelet/volumes.go]: I don't know how I cross reference morie's comment.  he's got it right.  

@swagiaal i agree with you.

File: pkg/kubelet/volumes.go (hunk 17 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: yeah, that's a good point.

File: pkg/kubelet/volumes.go (hunk 18 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: You're not missing anything, good point.

File: pkg/kubelet/volumes.go (hunk 17 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: yeah, agree, sorry I missed your original comment @swagiaal  -  these PRs get messy

File: pkg/kubelet/volumes.go [hunk 19]
```diff
@@ -79,19 +74,15 @@ func (vh *volumeHost) NewWrapperUnmounter(volName string, spec volume.Spec, podU
 		spec.Volume.Name = wrapperVolumeName
 	}
 
+	//FindPluginBySpec will only return a valid plugin if only one matched
+	// or an error if 0 plugins matched or more than 1 plugin matched
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: These comments and the others like it below don't belong here. You should add them to the godoc of the function being called (FindPluginBySpec, NewUnmounter, newVolumeMounterFromPlugins, etc)

File: pkg/kubelet/volumes.go (hunk 17 above)
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: > sorry I missed your original comment @swagiaal - these PRs get messy

no worries... almost there @screeley44!

File: pkg/kubelet/volumes.go (hunk 19 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Agree with @swagiaal.  Also, please add Godoc comments for `NewWrapperUnmounter` and friends (not just the ones you touch in this PR).

File: pkg/kubelet/volumes.go [hunk 20]
```diff
@@ -264,23 +248,22 @@ func (kl *Kubelet) getPodVolumesFromDisk() map[string]cleanerTuple {
...
+		return nil, fmt.Errorf("failed to instantiate physicalMounter for volume: %s using plugin: %s with a root cause: %v", spec.Name(), plugin.Name(), err)
 	}
 	glog.V(10).Infof("Used volume plugin %q to mount %s", plugin.Name(), spec.Name())
 	return physicalMounter, nil
 }
 
 func (kl *Kubelet) newVolumeAttacherFromPlugins(spec *volume.Spec, pod *api.Pod, opts volume.VolumeOptions) (volume.Attacher, error) {
+	// FindAttachablePluginBySpec can return an Attacher or an error or a nil detacher and error
+	// as not all volumes will have an attacher/detacher
 	plugin, err := kl.volumePluginMgr.FindAttachablePluginBySpec(spec)
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: This needs to move to the definition of `FindAttachablePluginBySpec`

Comment (screeley44) [inline pkg/kubelet/volumes.go]: @pmorie - I removed from here as the def of FindAttachablePluginBySpec already has a good godoc

File: pkg/kubelet/volumes.go [hunk 21]
```diff
@@ -263,23 +251,27 @@ func (kl *Kubelet) getPodVolumesFromDisk() map[string]cleanerTuple {
 	return currentVolumes
 }
 
+// newVolumeMounterFromPlugins attempts to find a plugin by volume spec and then create a physicalMounter from
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Strike this comment; there's a lot more to say about this method than is in-scope for this PR

File: pkg/kubelet/volumes.go [hunk 22]
```diff
@@ -263,23 +251,27 @@ func (kl *Kubelet) getPodVolumesFromDisk() map[string]cleanerTuple {
...
 	if err != nil {
-		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for %s: %v", spec.Name(), err)
+		return nil, fmt.Errorf("failed to instantiate physicalMounter for volume: %s using plugin: %s with a root cause: %v", spec.Name(), plugin.Name(), err)
 	}
 	glog.V(10).Infof("Used volume plugin %q to mount %s", plugin.Name(), spec.Name())
 	return physicalMounter, nil
 }
 
+// newVolumeAttacherFromPlugins attempts to find a plugin by a persistent volume spec and then create an attacher.
+// This is used when a volume needs to attach to a node before mounting.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Strike this line

File: pkg/kubelet/volumes.go [hunk 23]
```diff
@@ -263,23 +251,27 @@ func (kl *Kubelet) getPodVolumesFromDisk() map[string]cleanerTuple {
...
+// This func will return an error if the attacher plugin was not found or if the Attacher failed to instantiate.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: The information in this line and below is appropriate content, the tense is a little off.  Use present tense, viz: 'returns an error '

File: pkg/kubelet/volumes.go [hunk 24]
```diff
@@ -298,6 +290,9 @@ func (kl *Kubelet) newVolumeAttacherFromPlugins(spec *volume.Spec, pod *api.Pod,
 	return attacher, nil
 }
 
+// newVolumeUnmounterFromPlugins attempts to find a plugin by name and then create an unmounter from
+// a recoverable state.
+// This will return an error or a valid unmounter only
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Returns a valid unmounter or an error.

**Comment by screeley44** [comment]
@pmorie @swagiaal - how does this look?

File: pkg/kubelet/volumes.go [hunk 25]
```diff
@@ -106,11 +99,13 @@ func (vh *volumeHost) GetWriter() io.Writer {
 	return vh.kubelet.writer
 }
 
-// Returns the hostname of the host kubelet is running on
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Why are you removing this ?.. is it not true ?

File: pkg/kubelet/volumes.go [hunk 26]
```diff
@@ -305,10 +295,8 @@ func (kl *Kubelet) newVolumeUnmounterFromPlugins(kind string, name string, podUI
 		// TODO: Maybe we should launch a cleanup of this dir?
 		return nil, fmt.Errorf("can't use volume plugins for %s/%s: %v", podUID, kind, err)
 	}
-	if plugin == nil {
-		// Not found but not an error.
-		return nil, nil
-	}
+
+	// Can only return a valid unmounter or an error
```
Comment (swagiaal) [inline pkg/kubelet/volumes.go]: This should move to the godoc of NewUnmounter.

**Comment by swagiaal** [comment]
@screeley44 it is looking good just a couple of nits.

File: pkg/kubelet/volumes.go (hunk 25 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: @pmorie  previous comment said those are out of scope and I originally godoc'd all of them but he said they should be removed for now - although I think that Paul comment was in slack an not an official comment in this PR - that one line you reference above existed before I did all the other Get* functions, so I just removed it as well to be consistent...will put back in if you think I should @swagiaal @pmorie

Comment (swagiaal) [inline pkg/kubelet/volumes.go]: Hmm.. I think it should only be removed if it is not true anymore. @pmorie can you clarify ?

Also a general rule we try to keep a PR or a commit focused on related changes so if someone uses `git blame` in the future they should be able to understand why a line was changed when looking at the overall commit.

Comment (screeley44) [inline pkg/kubelet/volumes.go]: @swagiaal @pmorie  -  gottcha, and that makes sense.  I added back for now, unless Paul has a better reason to remove it.

File: pkg/kubelet/volumes.go [hunk 27]
```diff
@@ -65,13 +66,12 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
...
-	b, err := vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
-	if err == nil && b == nil {
-		return nil, errUnsupportedVolumeType
-	}
-	return b, nil
+	return vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
 }
 
+// NewWrapperUnmounter attempts to create a volume unmounter from a volume name and pod uid.
+// All volumes have a mounter and unmounter.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I think you can strike this line

File: pkg/kubelet/volumes.go [hunk 28]
```diff
@@ -58,6 +56,9 @@ func (vh *volumeHost) GetKubeClient() clientset.Interface {
 	return vh.kubelet.kubeClient
 }
 
+// NewWrapperMounter attempts to create a volume mounter from a volume Spec, pod and volume options.
+// All volumes have a mounter and unmounter.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I think you can strike this line

File: pkg/kubelet/volumes.go [hunk 29]
```diff
@@ -111,6 +104,9 @@ func (vh *volumeHost) GetHostName() string {
 	return vh.kubelet.hostname
 }
 
+// mountExternalVolumes creates a VolumeMap and attempts to physically mount
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: strike this comment, I made another PR adding a comment for this method (there's a lot more to say about it than this)

File: pkg/kubelet/volumes.go [hunk 30]
```diff
@@ -268,18 +257,17 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
...
 	physicalMounter, err := plugin.NewMounter(spec, pod, opts)
 	if err != nil {
-		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for %s: %v", spec.Name(), err)
+		return nil, fmt.Errorf("failed to instantiate physicalMounter for volume: %s using plugin: %s with a root cause: %v", spec.Name(), plugin.Name(), err)
 	}
 	glog.V(10).Infof("Used volume plugin %q to mount %s", plugin.Name(), spec.Name())
 	return physicalMounter, nil
 }
 
+// newVolumeAttacherFromPlugins attempts to find a plugin by a persistent volume spec and then create a volume Attacher.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: s/persistent//

Comment (pmorie) [inline pkg/kubelet/volumes.go]: Justify comments at 80 characters per line, please

File: pkg/kubelet/volumes.go [hunk 31]
```diff
@@ -268,18 +257,17 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
...
+// This function returns a valid volume Attacher or an error if the Attacher plugin was not found or if the Attacher failed to instantiate.
+// It can also return nil, nil as not all volumes will have an attacher/detacher
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I'd combine this and the previous sentence:

```
Returns:
- an attacher if one was found
- an error if no plugin could be found for the volume or the attacher failed to instantiate
- nil if there is no appropriate attacher for this volume

File: pkg/kubelet/volumes.go [hunk 32]
```diff
@@ -298,6 +286,9 @@ func (kl *Kubelet) newVolumeAttacherFromPlugins(spec *volume.Spec, pod *api.Pod,
 	return attacher, nil
 }
 
+// newVolumeUnmounterFromPlugins attempts to find a plugin by name and then create an Unmounter from
+// a recoverable state.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I don't understand what the 'recoverable state' is referring to here.

File: pkg/kubelet/volumes.go [hunk 33]
```diff
@@ -317,6 +305,9 @@ func (kl *Kubelet) newVolumeUnmounterFromPlugins(kind string, name string, podUI
 	return unmounter, nil
 }
 
+// newVolumeDetacherFromPlugins attempts to find a plugin by a name and then create a Detacher.
+// This function returns a valid volume Detacher or an error if the Detacher volume plugin was not found or if the Detacher failed to instantiate.
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Same comments here as for `newVolumeAttacherFromPlugins`

File: pkg/kubelet/volumes.go (hunk 12 above)
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Yes, sami is right, and this is fine the way it is now.

File: pkg/kubelet/volumes.go [hunk 34]
```diff
@@ -268,18 +257,17 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
...
 		return nil, fmt.Errorf("can't use volume plugins for %s: %v", spec.Name(), err)
 	}
-	if plugin == nil {
-		// Not found but not an error
-		return nil, nil
-	}
 	physicalMounter, err := plugin.NewMounter(spec, pod, opts)
 	if err != nil {
-		return nil, fmt.Errorf("failed to instantiate volume physicalMounter for %s: %v", spec.Name(), err)
+		return nil, fmt.Errorf("failed to instantiate physicalMounter for volume: %s using plugin: %s with a root cause: %v", spec.Name(), plugin.Name(), err)
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: I don't know what a 'physicalMounter' is -- just call it 'mounter' ?

File: pkg/kubelet/volumes.go [hunk 35]
```diff
@@ -58,6 +56,9 @@ func (vh *volumeHost) GetKubeClient() clientset.Interface {
 	return vh.kubelet.kubeClient
 }
 
+// NewWrapperMounter attempts to create a volume mounter
+// from a volume Spec, pod and volume options.
+// Returns a new volume Mounter or an error
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Missing period

File: pkg/kubelet/volumes.go [hunk 36]
```diff
@@ -65,13 +66,12 @@ func (vh *volumeHost) NewWrapperMounter(volName string, spec volume.Spec, pod *a
...
-	if err == nil && b == nil {
-		return nil, errUnsupportedVolumeType
-	}
-	return b, nil
+	return vh.kubelet.newVolumeMounterFromPlugins(&spec, pod, opts)
 }
 
+// NewWrapperUnmounter attempts to create a volume unmounter
+// from a volume name and pod uid.
+// Returns a new volume Unmounter or an error
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Missing period, whole sentences here please.

File: pkg/kubelet/volumes.go [hunk 37]
```diff
@@ -268,18 +254,21 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
...
 	return physicalMounter, nil
 }
 
+// newVolumeAttacherFromPlugins attempts to find a plugin from a volume spec
+// and then create an Attacher.
+// Returns:
+//  - an attacher if one exists
+//  - an error if no plugin was found for the volume
+//    or the attacher failed to instantiate
+//  - nil if there is no appropriate attacher for this volume
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: This is kind of the exception to the whole sentence rule -- this is fine as is re: the specification of return values

File: pkg/kubelet/volumes.go [hunk 38]
```diff
@@ -305,10 +297,7 @@ func (kl *Kubelet) newVolumeUnmounterFromPlugins(kind string, name string, podUI
 		// TODO: Maybe we should launch a cleanup of this dir?
 		return nil, fmt.Errorf("can't use volume plugins for %s/%s: %v", podUID, kind, err)
 	}
-	if plugin == nil {
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: This nil check has to go back in now, otherwise you will have a nil pointer when you call `plugin.NewUnmounter`

File: pkg/kubelet/volumes.go [hunk 39]
```diff
@@ -268,18 +254,21 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *api.Pod,
 	if err != nil {
```
Comment (pmorie) [inline pkg/kubelet/volumes.go]: Also, please add godoc for `newVolumeMounterFromPlugins`

File: pkg/kubelet/volumes.go (hunk 38 above)
Comment (screeley44) [inline pkg/kubelet/volumes.go]: @pmorie  - confused by this one...  FindPluginByName never returns a nil, nil - and the error check we do would catch any error scenario before we call the UnMounter - am I missing something here?

Comment (pmorie) [inline pkg/kubelet/volumes.go]: @screeley44 you're right, this check should be unnecessary now.

**Comment by screeley44** [comment]
The goal of this PR was to surface/expose plugin errors that were previously being eaten (i.e. errors that come from nfs.go, glusterfs.go, etc...).  And have them properly show in 'describe pod' so users could more easily see them without having to search the logs.  This accomplishes that, and all other errors that traditionally already showed in the 'describe' are not really affected.  After this I plan on continuing with additonal PRs and Issues to address other useability concerns in terms of error handling and other types of errors being eaten.

Below are a few example outputs from these changes, a newly surfaced plugin generated error that is now surfaced with true root cause and an existing non plugin type error that has always been surfaced and has not changed:

*Missing endpoints from GlusterFS using PV (previously being eaten):*
```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  15s		15s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bb-gluster-pod2 to 127.0.0.1
  15s		4s		2	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "bb-gluster-pod2_default(72a91ba0-fccb-11e5-9f13-52540092b5fb)": failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found

kubelet log output:
E0407 10:17:23.715015   17134 glusterfs.go:83] glusterfs: failed to get endpoints glusterfs-cluster[endpoints "glusterfs-cluster" not found]
E0407 10:17:23.715030   17134 persistent_claim.go:85] Error creating mounter for claim: glusterfs-claim
E0407 10:17:23.715037   17134 volumes.go:125] Could not create volume mounter for pod 72a91ba0-fccb-11e5-9f13-52540092b5fb: failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found
E0407 10:17:23.715056   17134 kubelet.go:1780] Unable to mount volumes for pod "bb-gluster-pod2_default(72a91ba0-fccb-11e5-9f13-52540092b5fb)": failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found; skipping pod
E0407 10:17:23.715062   17134 pod_workers.go:138] Error syncing pod 72a91ba0-fccb-11e5-9f13-52540092b5fb, skipping: failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found
I0407 10:17:23.715099   17134 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"bb-gluster-pod2", UID:"72a91ba0-fccb-11e5-9f13-52540092b5fb", APIVersion:"v1", ResourceVersion:"149", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Unable to mount volumes for pod "bb-gluster-pod2_default(72a91ba0-fccb-11e5-9f13-52540092b5fb)": failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found
I0407 10:17:23.715140   17134 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"bb-gluster-pod2", UID:"72a91ba0-fccb-11e5-9f13-52540092b5fb", APIVersion:"v1", ResourceVersion:"149", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to instantiate mounter for volume: glustervol using plugin: kubernetes.io/persistent-claim with a root cause: failed to instantiate mounter for volume: pv-gluster using plugin: kubernetes.io/glusterfs with a root cause: endpoints "glusterfs-cluster" not found

```

*NFS Connection Timeout using PV (timeout error remains the same as this does not stem from plugins directly):*
```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  4m		4m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned nfs-bb-pod2-pvc to 127.0.0.1
  2m		8s		2	{kubelet 127.0.0.1}			Warning		FailedMount	Unable to mount volumes for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)": Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out


kubelet log output:
I0407 10:07:06.898345   17134 kubelet.go:3242] Generating status for "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)"
I0407 10:07:06.911292   17134 manager.go:386] Status for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)" updated successfully: {status:{Phase:Pending Conditions:[{Type:Ready Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:0x2e4da80}} LastTransitionTime:{Time:{sec:63595634826 nsec:0 loc:0x2e70c60}} Reason:ContainersNotReady Message:containers with unready status: [nfs-bb-pod2-pvc]}] Message: Reason: HostIP:127.0.0.1 PodIP: StartTime:0xc2089fde60 ContainerStatuses:[{Name:nfs-bb-pod2-pvc State:{Waiting:0xc2089fde00 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:busybox ImageID: ContainerID:}]} version:1 podName:nfs-bb-pod2-pvc podNamespace:default}
E0407 10:09:17.994381   17134 kubelet.go:1780] Unable to mount volumes for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)": Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out

; skipping pod
E0407 10:09:17.994399   17134 pod_workers.go:138] Error syncing pod 0304472c-fcca-11e5-9f13-52540092b5fb, skipping: Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out

I0407 10:09:17.994429   17134 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nfs-bb-pod2-pvc", UID:"0304472c-fcca-11e5-9f13-52540092b5fb", APIVersion:"v1", ResourceVersion:"68", FieldPath:""}): type: 'Warning' reason: 'FailedMount' Unable to mount volumes for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)": Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out

I0407 10:09:17.994468   17134 server.go:608] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nfs-bb-pod2-pvc", UID:"0304472c-fcca-11e5-9f13-52540092b5fb", APIVersion:"v1", ResourceVersion:"68", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out

I0407 10:09:29.817521   17134 kubelet.go:3242] Generating status for "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)"
I0407 10:09:29.817652   17134 manager.go:277] Ignoring same status for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)", status: {Phase:Pending Conditions:[{Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-04-07 10:07:06 -0400 EDT Reason:ContainersNotReady Message:containers with unready status: [nfs-bb-pod2-pvc]}] Message: Reason: HostIP:127.0.0.1 PodIP: StartTime:2016-04-07 10:07:06 -0400 EDT ContainerStatuses:[{Name:nfs-bb-pod2-pvc State:{Waiting:0xc208ab6740 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:busybox ImageID: ContainerID:}]}
E0407 10:11:40.906401   17134 kubelet.go:1780] Unable to mount volumes for pod "nfs-bb-pod2-pvc_default(0304472c-fcca-11e5-9f13-52540092b5fb)": Mount failed: exit status 32
Mounting arguments: nfs1.rhs:/opt/data12 /var/lib/kubelet/pods/0304472c-fcca-11e5-9f13-52540092b5fb/volumes/kubernetes.io~nfs/pv-nfs nfs []
Output: mount.nfs: Connection timed out

```


@pmorie

**Comment by pmorie** [comment]
@screeley44 I would change the title of this PR (since it will become an entry in the release notes file) to be something like 'Return more useful error information when a persistent volume fails to mount'.

@saad-ali Do you have bandwidth to give this a review and then one of us can tag?

**Comment by saad-ali** [comment]
> @saad-ali Do you have bandwidth to give this a review and then one of us can tag?

Will do.

**Comment by saad-ali** [comment]
LGTM

**Comment by pmorie** [comment]
Thanks for the patch @screeley44.  I think this is one of the big usability issues w/ PVs today.

**Comment by markturansky** [comment]
>
> Thanks for the patch @screeley44 <https://github.com/screeley44>. I think
> this is one of the big usability issues w/ PVs today.
>

+1

**Comment by screeley44** [comment]
@pmorie  -  am I supposed to do something with the failed Jenkins?  I have not found the cause of the failure yet

**Comment by screeley44** [comment]
@k8s-bot test this issue: #24148

**Comment by swagiaal** [comment]
@k8s-bot test this issue: #24148
