### PR TITLE
Fix docker/journald logging conformance

### LINKED ISSUE #86367: kubectl logs ... --limit-bytes option is ignored for docker legacy logging
**What happened**:

Conformance test failed:
- `[sig-cli] Kubectl client Kubectl logs should be able to retrieve and filter logs  [Conformance]`

xref https://github.com/cncf/k8s-conformance/issues/746

```
Dec 17 20:19:54.514: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-582524409 logs logs-generator logs-generator --namespace=kubectl-2096 --limit-bytes=1'
Dec 17 20:19:54.563: INFO: stderr: ""
Dec 17 20:19:54.563: INFO: stdout: "I1217 20:19:52.996209       1 logs_generator.go:76] 0 PUT /api/v1/namespaces/default/pods/x9r 496\nI1217 20:19:53.196605       1 logs_generator.go:76] 1 PUT /api/v1/namespaces/kube-system/pods/dkb 259\nI1217 20:19:53.396285       1 logs_generator.go:76] 2 GET /api/v1/namespaces/ns/pods/27r 295\nI1217 20:19:53.596294       1 logs_generator.go:76] 3 POST /api/v1/namespaces/default/pods/csh 365\nI1217 20:19:53.796285       1 logs_generator.go:76] 4 GET /api/v1/namespaces/kube-system/pods/xm7 355\nI1217 20:19:53.996275       1 logs_generator.go:76] 5 PUT /api/v1/namespaces/default/pods/hmvn 559\nI1217 20:19:54.196280       1 logs_generator.go:76] 6 POST /api/v1/namespaces/kube-system/pods/w6gd 473\nI1217 20:19:54.396273       1 logs_generator.go:76] 7 PUT /api/v1/namespaces/ns/pods/rc2 534\n"
Dec 17 20:19:54.563: INFO: Unexpected unequal occurred: 8 and 1
Dec 17 20:19:54.563: FAIL: Expected
    &lt;int>: 8
to equal
    &lt;int>: 1
```

**What you expected to happen**:

I expected this conformance test to pass.

**How to reproduce it (as minimally and precisely as possible)**:

We have configured docker's logging driver to use journald, and then ran sonobouy tests against a k8s 1.16.3 cluster.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kkrc version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-09-03T18:55:44Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux Server release 7.7 (Maipo)
- Kernel (e.g. `uname -a`): 5.3.11-1.el7.elrepo.x86_64 #1 SMP Tue Nov 12 14:45:59 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jdef**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fixes a failing conformance test.

**Which issue(s) this PR fixes**:
Fixes #86367

**Special notes for your reviewer**:

The implementation of the docker legacy logger on master completely ignores a "byte limit" option that might be set for a log request. This PR resolves that ignorance by implementing a write limiter that attempts to only output up to the specified limit. The API for the byte limit itself is documented pretty loosely, more as a soft limit vs. a hard limit.

The docker client API doesn't appear to make any promises about how stdout/stderr are written to. e.g. are the streams written to concurrently? or one at a time (serially)? The solution here is defensive against the ambiguity of the docker API and tracks updates to the limit via sync/atomic functions. That said, via this PR it's possible (depending on the underlying docker client impl) that more bytes may be written than *actually* specified by the "byte limit" in the log request. However, the k8s API seem to be forgiving - as previously mentioned - by phrasing "byte limit" as a soft/best-effort limit. This PR does just that.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
@jdef thanks for the fix here :)

Could I trouble you to update either your pr or commit message with a description of the bug you ran into and how the changes you made fixed it? That'll give me a good starting off point for doing the review.

Thanks!

**Comment by jdef** [comment]
> @jdef thanks for the fix here :)
> 
> Could I trouble you to update either your pr or commit message with a description of the bug you ran into and how the changes you made fixed it? That'll give me a good starting off point for doing the review.
> 
> Thanks!

@mattjmcnaughton 
As stated in the PR description, this fixes bug #86367 "kubectl logs ... --limit-bytes option is ignored for docker legacy logging". There's additional context in that ticket. I was hoping to avoid a complete copy/paste of that bug report in this ticket, but will do so if additional context is needed *in this ticket* itself. Otherwise, kindly click through to the bug report as linked here. Thanks!

**Comment by jdef** [comment]
xref https://github.com/cncf/k8s-conformance/issues/746

**Comment by mattjmcnaughton** [comment]
> > @jdef thanks for the fix here :)
> > Could I trouble you to update either your pr or commit message with a description of the bug you ran into and how the changes you made fixed it? That'll give me a good starting off point for doing the review.
> > Thanks!
> 
> @mattjmcnaughton
> As stated in the PR description, this fixes bug #86367 "kubectl logs ... --limit-bytes option is ignored for docker legacy logging". There's additional context in that ticket. I was hoping to avoid a complete copy/paste of that bug report in this ticket, but will do so if additional context is needed _in this ticket_ itself. Otherwise, kindly click through to the bug report as linked here. Thanks!

Yeah, great point - I don't want to ask you to copy and paste the bug report. Perhaps I poorly phrased my original request -  what I meant to ask is if you could you provide context around why the changes you made fix the problem and why you decided on this implementation instead of other options (if other options exist).

Full disclosure - I was hoping to review this for you to get it moving along, but I don't have a ton of context on the logging code :) So I was hoping for some "jumping off points" in the commit message or pr.

Also, feel free to wait for another reviewer with more context on this part of the code base than myself :)

**Comment by jdef** [comment]
> > > @jdef thanks for the fix here :)
> > > Could I trouble you to update either your pr or commit message with a description of the bug you ran into and how the changes you made fixed it? That'll give me a good starting off point for doing the review.
> > > Thanks!
> > 
> > 
> > @mattjmcnaughton
> > As stated in the PR description, this fixes bug #86367 "kubectl logs ... --limit-bytes option is ignored for docker legacy logging". There's additional context in that ticket. I was hoping to avoid a complete copy/paste of that bug report in this ticket, but will do so if additional context is needed _in this ticket_ itself. Otherwise, kindly click through to the bug report as linked here. Thanks!
> 
> Yeah, great point - I don't want to ask you to copy and paste the bug report. Perhaps I poorly phrased my original request - what I meant to ask is if you could you provide context around why the changes you made fix the problem and why you decided on this implementation instead of other options (if other options exist).
> 
> Full disclosure - I was hoping to review this for you to get it moving along, but I don't have a ton of context on the logging code :) So I was hoping for some "jumping off points" in the commit message or pr.
> 
> Also, feel free to wait for another reviewer with more context on this part of the code base than myself :)

@mattjmcnaughton I've updated the description of this PR. PTAL

**Comment by mattjmcnaughton** [comment]
> > > > @jdef thanks for the fix here :)
> > > > Could I trouble you to update either your pr or commit message with a description of the bug you ran into and how the changes you made fixed it? That'll give me a good starting off point for doing the review.
> > > > Thanks!
> > > 
> > > 
> > > @mattjmcnaughton
> > > As stated in the PR description, this fixes bug #86367 "kubectl logs ... --limit-bytes option is ignored for docker legacy logging". There's additional context in that ticket. I was hoping to avoid a complete copy/paste of that bug report in this ticket, but will do so if additional context is needed _in this ticket_ itself. Otherwise, kindly click through to the bug report as linked here. Thanks!
> > 
> > 
> > Yeah, great point - I don't want to ask you to copy and paste the bug report. Perhaps I poorly phrased my original request - what I meant to ask is if you could you provide context around why the changes you made fix the problem and why you decided on this implementation instead of other options (if other options exist).
> > Full disclosure - I was hoping to review this for you to get it moving along, but I don't have a ton of context on the logging code :) So I was hoping for some "jumping off points" in the commit message or pr.
> > Also, feel free to wait for another reviewer with more context on this part of the code base than myself :)
> 
> @mattjmcnaughton I've updated the description of this PR. PTAL

Wonderful, ty!

File: pkg/kubelet/dockershim/helpers.go [hunk 1]
```diff
@@ -393,3 +396,48 @@ type dockerOpt struct {
 func (d dockerOpt) GetKV() (string, string) {
 	return d.key, d.value
 }
+
+// writeLimiter limits the total output written across one or more streams.
+type writeLimiter struct {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/dockershim/helpers.go]: Just to be sure I'm understanding, can you share more about why we need to create a new struct for limiting writes and can't use Go builtins such as `io.CopyN`?

Is it because we want to actually share the maximum amount of bytes to write across both stderr and stdout?

If we move forward with our own struct,  I wonder if we could update `writeLimiter` to make it a little clearer that its shared? For example, `sharedWriteLimiter` as a name?

Could you also share more about the decision to use `atomic` instead of a mutex around `limit`? I'm not an expert in go concurrency, so a little more context around the decision could be helpful for me :)

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for tackling this and adding the test coverage!

File: pkg/kubelet/dockershim/helpers.go (hunk 1 above)
Comment (jdef) [reply pkg/kubelet/dockershim/helpers.go]: yes, the limit is "shared" across both the stdout and stderr output stream, so CopyN doesn't really fit.

> For example, sharedWriteLimiter as a name

I'm not opposed to renaming this for clarity, though hopefully people would read the struct comment that I left that describes its use case.

> Could you also share more about the decision to use atomic instead of a mutex around limit?

Sure. I don't want to hold a mutex across I/O operations. But I do want concurrency-safe operations applied against the limit counter. Hence the use of sync/atomic. The downside of this approach is that concurrent writes can race and we *could* write more than the specified limit. However, given the softness of the requirements around the `LimitBytes` API, I think this is an acceptable trade-off that remains within spec.

File: pkg/kubelet/dockershim/helpers.go [hunk 2]
```diff
@@ -393,3 +396,48 @@ type dockerOpt struct {
...
+	}
+	var truncated bool
+	if limit < int64(len(p)) {
+		p = p[0:limit]
+		truncated = true
+	}
+	n, err := w.delegate.Write(p)
+	if n > 0 {
+		newLimit := limit - int64(n)
+		for !atomic.CompareAndSwapInt64(w.limit, limit, newLimit) {
```
Comment (jdef) [inline pkg/kubelet/dockershim/helpers.go]: It's arguable that we don't actually need a `for` loop to accomplish what this does. I originally wrote this because I thought there'd be more "work" to do in the loop iterations. But the result is over-complicated and only serves to decrease readability. e.g. it would be more straight forward to write `atomic.AddInt64(w.limit, -1 * n)`

**Comment by krmayankk** [comment]
- does this only not work for dockershim or also for other container runtimes as well ?
- also, is this useful, do people actually use this ? for what debugging scenarios (just curious )

**Comment by jdef** [comment]
> * does this only not work for dockershim or also for other container runtimes as well ?

I tested w/ k8s+docker. If there are other runtimes that expose a docker API and k8s is interacting with them then I suppose I would expect it to work similarly for those.

> * also, is this useful, do people actually use this ? for what debugging scenarios (just curious )

Yes, this is useful when using Docker w/ the journald logging driver.

File: pkg/kubelet/dockershim/helpers.go [hunk 3]
```diff
@@ -393,3 +396,44 @@ type dockerOpt struct {
...
+	if n > 0 {
+		atomic.AddInt64(w.limit, -1*int64(n))
+	}
+	if err == nil && truncated {
+		err = errMaximumWrite
+	}
+	return n, err
+}
+
+func limitedWriter(w io.Writer, limit *int64) io.Writer {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/dockershim/helpers.go]: Nit: Should we rename this function as well?

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for your thoughtful answers to my questions. 

/assign tallclair

**Comment by jdef** [comment]
@mattjmcnaughton nit addressed PTAL

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for addressing my nit :)

**Comment by jdef** [comment]
@krmayankk @resouer PTAL

**Comment by jdef** [comment]
@yujuhong PTAL

File: pkg/kubelet/dockershim/helpers_test.go [hunk 4]
```diff
@@ -332,3 +335,104 @@ func TestGenerateMountBindings(t *testing.T) {
...
+			b1, b2 bytes.Buffer
+			limit  = int64(10)
+			w1     = sharedLimitWriter(&b1, &limit)
+			w2     = sharedLimitWriter(&b2, &limit)
+			ch     = make(chan struct{})
+			wg     sync.WaitGroup
+		)
+		wg.Add(2)
+		go func() { defer wg.Done(); <-ch; w1.Write([]byte("hello")) }()
+		go func() { defer wg.Done(); <-ch; w2.Write([]byte("world")) }()
```
Comment (tallclair) [inline pkg/kubelet/dockershim/helpers_test.go]: A better test might be to spam many write calls against a larger buffer, but this is probably good enough for these purposes.

File: pkg/kubelet/dockershim/helpers.go [hunk 5]
```diff
@@ -393,3 +396,44 @@ type dockerOpt struct {
...
+type sharedWriteLimiter struct {
+	delegate io.Writer
+	limit    *int64
+}
+
+func (w sharedWriteLimiter) Write(p []byte) (int, error) {
+	if len(p) == 0 {
+		return 0, nil
+	}
+	limit := atomic.LoadInt64(w.limit)
```
Comment (tallclair) [inline pkg/kubelet/dockershim/helpers.go]: Note that it is possible to write past the limit. Imagine 2 write requests coming in simultaneously with only a few bytes left in the limit, both read the same limit, write their output, and then subtract from that limit. The end result is the limit has been passed.

If you care, you could use a `CompareAndSwapInt64` call to decrement the limit before writing to the delegate, but i'm not sure it's worth the trouble...

**Review by tallclair — COMMENTED** [review]
/approve
/hold

I had an open question about whether we care about the race condition. I defer to you, feel free to remove the hold if you decide not to change it.

File: pkg/kubelet/dockershim/helpers.go (hunk 5 above)
Comment (jdef) [reply pkg/kubelet/dockershim/helpers.go]: Yes, you're right. I intended to keep this implementation simple, especially given that the LimitBytes API doesn't guarantee a hard limit (only a soft one). I don't think it's worth the trouble/complexity to implement a hard limit here.
