### PR TITLE
[sig-windows] update winkernel to only use dualstack if the node and config supports it

### LINKED ISSUE #100966: winkernel kube-proxy problems when IPv6DualStack is enabled (ie, in 1.21)
#### What happened:
Ran winkernel kube-proxy in 1.21 (where `IPv6DualStack` is now enabled by default). It fails:

`F0408 17:17:11.043472    1316 server.go:489] unable to create proxier: unable to create ipv4 proxier: Could not find host mac address for 0.0.0.0, hostname: e2e-wmcow-bpfpl, clusterCIDR : 10.132.0.0/24, nodeIP:0.0.0.0`

Manually specifying `--bind-address` gets it past that problem but then fails with:

`F0408 21:22:41.744719    1804 server.go:489] unable to create proxier: unable to create ipv6 proxier: Could not find host mac address for ::, hostname: winworker-pbvb6, clusterCIDR : 10.132.0.0/24, nodeIP:::`

(Note that this is a single-stack IPv4 cluster.)

#### What you expected to happen:
Enabling the feature gate should not change the end-user-visible behavior for people who are not using the gated feature.

There are (at least) two problems:

1. When `IPv6DualStack` is disabled, the startup code calls `utilnode.GetNodeIP(client, hostname)` to get the node IP and passes that to `winkernel.NewProxier`, but when `IPv6DualStack` is enabled, it passes `nodeIPTuple(config.BindAddress)` instead, which will always pass at least one unspecified (`0.0.0.0`/`::`) IP to `NewDualStackProxier`. But the winkernel proxier code doesn't deal with unspecified IPs, at least when using an "overlay" network; it requires that the passed-in IP be an actual IP address on some interface. (It's possible that it should be using something like `utilnet.ResolveBindAddress()` from apimachinery to convert the possibly-unspecified bind address to a local IP.)
2. The winkernel kube-proxy startup code always creates a metaproxier with IPv4 and IPv6 sub-proxiers if `IPv6DualStack` is enabled, but then fails if it can't create either of those proxiers. This is wrong; it should fall back to single-stack operation if it can't run dual-stack, because the presence of the feature gate doesn't mean that the cluster is _actually_ dual-stack, it just means that it _is allowed to be_ dual-stack.

#### How to reproduce it (as minimally and precisely as possible):
Run kube-proxy 1.21 in winkernel mode with an overlay network on a single-stack IPv4 node

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Overlay (VXLAN) networks on Windows do not support dual-stack networking today, so we should not use the dualstack proxy. Additionally the dual stack proxier should only be created if the host supports it. 

This fixes a couple issues:
- `--bind-address` flag was not respected for Windows single stack
- dual-stack should not be used when the networking stack does not support it 
- dual-stack should not be used when overlay is enabled as it is not supported
- unspecified ip addresses are not supported in overlay,  if address is unspecified will attempt to get bind address for mac address which is required in overlay mode

#### Which issue(s) this PR fixes:

Fixes #100966

#### Does this PR introduce a user-facing change?

```release-note
Fix winkernel kube-proxy to only use dual stack when host and networking supports it
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/util/node/node.go [hunk 1]
```diff
@@ -144,6 +144,36 @@ func GetNodeHostIP(node *v1.Node) (net.IP, error) {
 	return ips[0], nil
 }
 
+// GetNodeIPs returns IPs (as with GetNodeHostIPs) for the node with the provided name.
+// If required, it will wait for the node to be created.
```
Comment (aojea) [inline pkg/util/node/node.go:148]: I had this in mind, so it is coherent with   `GetNodeHostIP` , just FYI 

https://github.com/kubernetes/kubernetes/pull/99066/commits/eadd0c9fe94834f7e100760f269437fcf1051e2f

File: cmd/kube-proxy/app/server_windows.go [hunk 2]
```diff
@@ -100,13 +100,34 @@ func newProxyServer(config *proxyconfigapi.KubeProxyConfiguration, cleanupAndExi
 		healthzServer = healthcheck.NewProxierHealthServer(config.HealthzBindAddress, 2*config.IPTables.SyncPeriod.Duration, recorder, nodeRef)
 	}
 
-	var proxier proxy.Provider
+	dualStack := utilfeature.DefaultFeatureGate.Enabled(features.IPv6DualStack)
+	if dualStack {
+		if utilfeature.DefaultFeatureGate.Enabled(features.WinOverlay) {
+			// Overlay (VXLAN) networks on Windows do not support dual-stack networking today
+			klog.Warning("Winoverlay is does not support dual-stack. Failing back to single-stack")
```
Comment (aojea) [inline cmd/kube-proxy/app/server_windows.go:107]: Winoverlay ~is~ does not support dual-stack

Comment (aramase) [inline cmd/kube-proxy/app/server_windows.go:107]:
```suggestion
			klog.Warning("Winoverlay does not support dual-stack. Falling back to single-stack")
```

File: cmd/kube-proxy/app/server_windows.go [hunk 3]
```diff
@@ -100,13 +100,34 @@ func newProxyServer(config *proxyconfigapi.KubeProxyConfiguration, cleanupAndExi
...
+			dualStack = false
+		} else {
+			// just because the feature is enabled doesn't mean that the node supports dual-stack
+			hasIPv6Address := false
+			ips := utilnode.GetNodeIPs(client, hostname)
+			for _, ip := range ips {
+				if utilsnet.IsIPv6(ip) {
+					hasIPv6Address = true
```
Comment (aramase) [inline cmd/kube-proxy/app/server_windows.go:115]: We can just break here after we find the IPv6 address

File: pkg/util/node/node.go (hunk 1 above)
Comment (jsturtevant) [reply pkg/util/node/node.go]: went a different direction that was closer to linux

**Comment by jsturtevant** [comment]
Updated the PR description for the things addressed.

I've tested this on a WS 2019 overlay host, 2019 l2bridge host and WS 2004 host.
 
On the WS 2004 host the if `supportedFeatures.IPv6DualStack` return false which was surprising.  It looks like the WS 2004 host is version is not with in the range specified as supported: https://github.com/microsoft/hcsshim/blob/d9474d26c57bed6081b3941dd7980d5e8457148e/hcn/hcnglobals.go#L56-L60

```
cmd /c ver

Microsoft Windows [Version 10.0.19041.867]
```

Add logging:
```
I0414 22:35:15.143135    3372 proxier.go:202] hns version%!(EXTRA hcn.Version={11 10})                                                                                                    
W0414 22:35:15.143135    3372 proxier.go:203] This version of Windows does not support dual-stack. Falling back to single-stack    
```

I am going to follow up to find out if what the correct version of support should be because the [docs](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack) state:  `2004 (kernel version 10.0.19041.610) `

**Comment by jsturtevant** [comment]
`pull-kubernetes-e2e-aks-engine-azure-windows` was renamed
/test pull-kubernetes-e2e-aks-engine-windows-dockershim

**Comment by jsturtevant** [comment]
the failure on `pull-kubernetes-e2e-aks-engine-windows-dockershim` was an issue with cni: https://github.com/Azure/azure-container-networking/issues/774#issuecomment-820503010

/test pull-kubernetes-e2e-aks-engine-windows-dockershim

**Comment by jsturtevant** [comment]
I got confirmation that dual stack is supported in WS 2004 and I have submitted a PR to fix this: https://github.com/microsoft/hcsshim/pull/1003

Should I make the updates to this PR check for the correct versions while we wait for an updated release of hcsshim?

**Comment by marosset** [comment]
@jsturtevant should the release notes indicate that this fixes an issue found that was already released?

**Comment by jsturtevant** [comment]
> @jsturtevant should the release notes indicate that this fixes an issue found that was already released?

updated indicate that this is a fix

File: pkg/proxy/winkernel/proxier.go [hunk 4]
```diff
@@ -605,6 +683,15 @@ func NewProxier(
 			return nil, fmt.Errorf("source-vip flag not set")
 		}
 
+		if nodeIP.IsUnspecified() {
+			// attempt to get the correct ip address
+			klog.V(2).InfoS("node ip was unspecified.  Attempting to find node ip")
+			nodeIP, err = apiutil.ResolveBindAddress(nodeIP)
+			if err != nil {
+				klog.Warningf("failed to find an ip. You may need set the --bind-address flag")
```
Comment (sbangari) [inline pkg/proxy/winkernel/proxier.go:691]: do you see a value in moving past this failure with just a warning? Do we expect the networking to work if nodeIP is not available?

File: cmd/kube-proxy/app/server_windows.go [hunk 5]
```diff
@@ -183,6 +185,16 @@ func newProxyServer(config *proxyconfigapi.KubeProxyConfiguration, cleanupAndExi
 	}, nil
 }
 
+func getDualStackMode(networkname string, compatTester winkernel.StackCompatTester) bool {
+	dualstack, err := compatTester.DualStackCompatible(networkname)
+	if err != nil {
+		klog.Errorf("unable to determine dual-stack status %v. Falling back to single-stack", err)
+		return dualstack
```
Comment (aramase) [inline cmd/kube-proxy/app/server_windows.go:192]: The `return dualstack` outside the `err != nil` check should be sufficient

File: pkg/proxy/winkernel/proxier.go [hunk 6]
```diff
@@ -138,6 +140,94 @@ type remoteSubnetInfo struct {
...
+		}
+	}
+	return hnsNetworkName, nil
+}
+
+func getNetworkInfo(hns HostNetworkService, hnsNetworkName string) (*hnsNetworkInfo, error) {
+	hnsNetworkInfo, err := hns.getNetworkByName(hnsNetworkName)
+	for err != nil {
+		klog.ErrorS(err, "Unable to find HNS Network specified. Please check network name and CNI deployment", "hnsNetworkName", hnsNetworkName)
+		time.Sleep(1 * time.Second)
```
Comment (aramase) [inline pkg/proxy/winkernel/proxier.go:169]: Could you add a comment here for why the sleep is required?

File: pkg/proxy/winkernel/proxier.go [hunk 7]
```diff
@@ -138,6 +140,94 @@ type remoteSubnetInfo struct {
...
+}
+
+// The hcsshim version logic has a bug that did not calculate the versioning of DualStack correctly.
+// DualStack is supported in WS 2004+ (10.0.19041+) where HCN component version is 11.10+
+// https://github.com/microsoft/hcsshim/pull/1003#issuecomment-827930358
+func isDualStackSupported() bool {
+	var IPv6DualStackVersion = hcn.VersionRange{MinVersion: hcn.Version{Major: 11, Minor: 10}}
+	globals, err := hcn.GetGlobals()
+	if err != nil {
+		klog.Warning("Unable to get version networking stack")
```
Comment (aramase) [inline pkg/proxy/winkernel/proxier.go:222]: Do we want to log the error here?

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (aramase) [inline pkg/proxy/winkernel/proxier.go:691]: Also, we should log the error here

Comment (aramase) [reply pkg/proxy/winkernel/proxier.go:691]: Yeah, `nodeIP` seems to be referenced later. So would that fail if there is an error here?

File: cmd/kube-proxy/app/server_windows.go [hunk 8]
```diff
@@ -85,6 +84,10 @@ func newProxyServer(config *proxyconfigapi.KubeProxyConfiguration, cleanupAndExi
 	if err != nil {
 		return nil, err
 	}
+
+	nodeIP := detectNodeIP(client, hostname, config.BindAddress)
+	klog.Infof("Detected node IP %s", nodeIP.String())
```
Comment (aramase) [inline cmd/kube-proxy/app/server_windows.go:89]: This package seems to be using structured logging. Could we make the new log statements structured?

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go:691]: it would fail later with `F0408 17:17:11.043472 1316 server.go:489] unable to create proxier: unable to create ipv4 proxier: Could not find host mac address for 0.0.0.0, hostname: e2e-wmcow-bpfpl, clusterCIDR : 10.132.0.0/24, nodeIP:0.0.0.0` which is the same behavior.

I was following the best effort pattern from https://github.com/kubernetes/kubernetes/blob/2f753ec4c826895e4ccd3d6bdda2b1ab777ceeb8/cmd/kube-proxy/app/server_others.go#L442. 

If we know it will always fails in this scenario we could exit early.

File: pkg/proxy/winkernel/proxier.go (hunk 6 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go:169]: I moved that section of code and don't know the original reasoning.  maybe @sbangari knows?

Comment (sbangari) [reply pkg/proxy/winkernel/proxier.go:169]: Neither do I :)  .... But it seems like kube-proxy is retrying to get HNS network, which is created by CNI. If kube-proxy happens to start before the network is created, it may be taking a guess that the CNI is just starting up or the HNS network creation is still in progress and will retry to read the network configuration after a second before giving up.

File: cmd/kube-proxy/app/server_windows.go (hunk 5 above)
Comment (jsturtevant) [reply cmd/kube-proxy/app/server_windows.go]: good point, the logging was inconsistent here (some was here some down in the function itself) so I moved it all to one location

File: pkg/proxy/winkernel/proxier.go (hunk 7 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go]: updated

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go]: updated

File: cmd/kube-proxy/app/server_windows.go (hunk 8 above)
Comment (jsturtevant) [reply cmd/kube-proxy/app/server_windows.go]: good catch!  this landed after i initially created this pr

**Comment by jsturtevant** [comment]
@sbangari @aramase Thanks for the reviews. I've updated the pr to address them.

File: pkg/proxy/winkernel/proxier.go [hunk 9]
```diff
@@ -138,6 +140,96 @@ type remoteSubnetInfo struct {
...
+type StackCompatTester interface {
+	DualStackCompatible(networkName string) bool
+}
+
+type DualStackCompatTester struct{}
+
+func (t DualStackCompatTester) DualStackCompatible(networkName string) bool {
+	dualStackFeatureEnabled := utilfeature.DefaultFeatureGate.Enabled(features.IPv6DualStack)
+	if dualStackFeatureEnabled {
+		if isDualStackSupported() {
```
Comment (aojea) [inline pkg/proxy/winkernel/proxier.go:189]: avoid nested ifs if possible
```
if !dualstackFeatureEnaled{
   return false
}
```

**Comment by notchairmk** [comment]
Hey👋 , Bug Triage here. @jsturtevant @aojea this PR is labeled `priority/critical-urgent` for the v1.22 milestone. It hasn't been updated in a couple of weeks. Any progress or concerns that would stop this from reaching the milestone?

File: pkg/proxy/winkernel/proxier.go (hunk 9 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go]: good call, I've updated this logic to remove this

**Comment by jsturtevant** [comment]
@sbangari @aramase @aojea @ksubrmnn I've address the comments. Please take another look.

**Comment by MonzElmasry** [comment]
Hello, 
@aojea @aramase @sbangari @bowei @dims can you take a look at the latest changes?

File: pkg/proxy/winkernel/proxier.go [hunk 10]
```diff
@@ -138,6 +140,98 @@ type remoteSubnetInfo struct {
...
+// DualStack is supported in WS 2004+ (10.0.19041+) where HCN component version is 11.10+
+// https://github.com/microsoft/hcsshim/pull/1003#issuecomment-827930358
+func kernelSupportsDualstack() bool {
+	var IPv6DualStackVersion = hcn.VersionRange{MinVersion: hcn.Version{Major: 11, Minor: 10}}
+	globals, err := hcn.GetGlobals()
+	if err != nil {
+		klog.ErrorS(err, "Unable to determine networking stack version")
+		return false
+	}
+	if globals.Version.Major >= IPv6DualStackVersion.MinVersion.Major && globals.Version.Minor >= IPv6DualStackVersion.MinVersion.Minor {
```
Comment (aojea) [inline pkg/proxy/winkernel/proxier.go:229]: 5.1 > 1.29, however this check will return false
I know there is a library in k8s that compares semver, apimachinery maybe? I'm afk and can't check

File: pkg/proxy/winkernel/proxier.go [hunk 11]
```diff
@@ -610,6 +692,15 @@ func NewProxier(
...
+		if nodeIP.IsUnspecified() {
+			// attempt to get the correct ip address
+			klog.V(2).InfoS("node ip was unspecified.  Attempting to find node ip")
+			nodeIP, err = apiutil.ResolveBindAddress(nodeIP)
+			if err != nil {
+				klog.InfoS("failed to find an ip. You may need set the --bind-address flag", "err", err)
+			}
+		}
+
 		interfaces, _ := net.Interfaces() //TODO create interfaces
```
Comment (aojea) [inline pkg/proxy/winkernel/proxier.go:704]: This is a todo, it has a performance problem to iterate over the interfaces first and later over the addreses 
https://github.com/kubernetes/kubernetes/pull/103116

File: pkg/proxy/winkernel/proxier.go (hunk 6 above)
Comment (aojea) [reply pkg/proxy/winkernel/proxier.go:169]: // TODO figure out why do we need this sleep

😅

File: pkg/proxy/winkernel/proxier.go [hunk 12]
```diff
@@ -610,6 +692,15 @@ func NewProxier(
 			return nil, fmt.Errorf("source-vip flag not set")
 		}
 
+		if nodeIP.IsUnspecified() {
```
Comment (aojea) [inline pkg/proxy/winkernel/proxier.go:695]: Since we are using detectNodeIP that deals with unspecified, is it possible to get an unspecified here?
I couldn't check all code paths, just asking

Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go:695]: Yes it could be unspecified, in DualStack the bind address doesn't go through detectNodeIp, which only works with IPv4.  This is the same on Linux: https://github.com/kubernetes/kubernetes/blob/90b02692e2980d460fa2e53bf4509df1ec10475f/cmd/kube-proxy/app/server_others.go#L239  https://github.com/kubernetes/kubernetes/blob/90b02692e2980d460fa2e53bf4509df1ec10475f/cmd/kube-proxy/app/server_windows.go#L120

File: pkg/proxy/winkernel/proxier.go (hunk 11 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go:704]: I created https://github.com/kubernetes/kubernetes/issues/103588 to track.  fyi @sbangari

File: pkg/proxy/winkernel/proxier.go (hunk 10 above)
Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go]: found it, It was a bit awkward to use do to hcn not using the correct format.  In 1.23 I can update the hcsshim library and this logic will no longer be required because it will have the correct checks internally

File: pkg/proxy/winkernel/proxier.go [hunk 13]
```diff
@@ -137,6 +138,101 @@ type remoteSubnetInfo struct {
...
+// DualStack is supported in WS 2004+ (10.0.19041+) where HCN component version is 11.10+
+// https://github.com/microsoft/hcsshim/pull/1003#issuecomment-827930358
+func kernelSupportsDualstack(currentVersion hcn.Version) bool {
+	hnsVersion := fmt.Sprintf("%d.%d.0", currentVersion.Major, currentVersion.Minor)
+	v, err := version.ParseSemantic(hnsVersion)
+	if err != nil {
+		return false
+	}
+
+	return v.AtLeast(version.MustParseSemantic("11.10.0"))
```
Comment (sbangari) [inline pkg/proxy/winkernel/proxier.go:233]: We should try fixing this in hcsshim to avoid  this version check across other components (like here in kube-proxy and possibly CNI's) ... we can merge this PR but should revert this change back once this is fixed in hcsshim

Comment (jsturtevant) [reply pkg/proxy/winkernel/proxier.go:233]: In 1.23 I can update the hcsshim library and this logic will no longer be required because it will have the correct checks internally.

**Comment by jsturtevant** [comment]
@aojea could you take another look?

**Comment by aojea** [comment]
> @aojea could you take another look?

I can't say much about the windows logic and I'm out until next week, I think that overall is ok, so don't wait for me if you want to get it merged today

**Comment by aojea** [comment]
/approve
kube-proxy bits

**Comment by aravindhp** [comment]
@jsturtevant shouldn't this be backported to all affected releases?

**Comment by neolit123** [comment]
@jsturtevant i'm assuming we need to backport this to 1.21?

**Comment by marosset** [comment]
Yes, this should get backported to 1.21.

**Comment by marosset** [comment]
I added a card on our board to track this.
https://github.com/orgs/kubernetes/projects/8#card-65265573
