### PR TITLE
Fix device uncertain errors on reboot

### LINKED ISSUE #119608: Kubelet cannot finish terminating a pod that uses a PVC with volumeMode: Block when poweroff the node and then restarting the node
### What happened?

A pod uses a PVC with volumeMode: Block. The block volume is backed by a block device on the node (which is created by some CSI storage providers).  If the node operating system is powered off , if the user delete the pod or the pod be eviceted by kcm, And then restarting the node, The pod would be stuck in terminating forever since Kubelet refuses to UnmapBlockVolume. kubelet  cannot delete the pod successfully.  

### What did you expect to happen?

Kubelet should be able to finish terminating a pod  

### How can we reproduce it (as minimally and precisely as possible)?

1.Install a CSI storage provider that supports volumeMode: Block.

2.Deloy a pod that has volumeClaimTemplates with volumeMode: Block. 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-pod
spec:
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
      name: test-pod
    spec:
      containers:
      - image: nginx:1.17.9
        name: test
        volumeDevices:
        - devicePath: /dev/blk-vol-1
          name: blk-vol-1
        volumeMounts:
      volumes:
      - name: blk-vol-1
        persistentVolumeClaim:
          claimName: test-bv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-bv
  namespace: default
spec:
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 5Gi
  storageClassName: FILLIN
  volumeMode: Block
```
3.After pod is running ,to  power off the node
4.delete the po: kubectl delete po test-pod
5.restart the node

The pod is stuck in terminating state forever. Logs from kubelet:
`13:31:57 wanguo-72 kubelet[1131]: E0428 13:31:57.597111 1131 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/topolvm.cybozu.com^a27f2f53-54fa-4068-bbad-cfbe70c0815c podName:8519283b-9521-4aed-9bfe-8f6687f99691 nodeName:}" failed. No retries permitted until 2023-04-28 13:33:59.597061528 +0800 CST m=+8838.750882463 (durationBeforeRetry 2m2s). Error: UnmapVolume.UnmapBlockVolume failed for volume "pvc-e2bc365a-a4e4-48a7-9057-af87b303f8fe" (UniqueName: "kubernetes.io/csi/topolvm.cybozu.com^a27f2f53-54fa-4068-bbad-cfbe70c0815c") pod "8519283b-9521-4aed-9bfe-8f6687f99691" (UID: "8519283b-9521-4aed-9bfe-8f6687f99691") : blkUtil.DetachFileDevice failed. globalUnmapPath:, podUID: 8519283b-9521-4aed-9bfe-8f6687f99691, bindMount: true: failed to unmap device from map path. mapPath is empty`

### Anything else we need to know?

This scene is similar to https://github.com/kubernetes/kubernetes/issues/109132 ，but the root cause is different
```
$ sudo losetup -a
/dev/loop1: [0005]:2704 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-c5e56a48-db16-44c9-aec3-9e67b756ad27/dev/94de7f89-c01d-4cf8-8f63-5a3f3ac66ca9)
/dev/loop19: [0005]:23395 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-afdc5c38-0c90-4ad0-beb7-28bafea10bb1/dev/093afe20-052b-4df3-8184-8e667a19106d)
/dev/loop17: [0005]:20856 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-45f0b187-9d08-421a-86cd-6b2c6ea65a1b/dev/bcaa2b22-a1a8-4551-bdde-a23b38b4d306)
/dev/loop8: [0005]:20704 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-e670b3d7-90a6-4cfa-8fbb-4dcb75c41d7a/dev/f23c27f0-45b7-4b11-b1cd-c99869197f9f)
/dev/loop15: [0005]:22688 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-f50310b1-85b8-43e9-be00-5f82f4435e4b/dev/e4ebae36-e84a-4968-a0be-ad3a41214e79)
/dev/loop6: [0005]:3759 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-8ee533bb-cbc0-45a9-9bd5-e258a31886dc/dev/8c8028ea-8196-42a8-bd50-ef252cf39df6)
/dev/loop13: [0005]:16311 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-92ac7830-4632-46bf-8981-ae0c4fbec863/dev/0aba3553-0faa-45cd-8544-03731a35532e)
/dev/loop4: [0005]:22070 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-33015057-fc15-4a4f-9cff-8467ec67d6f8/dev/ea14cbe3-601c-49f8-949f-51361a558f66)
/dev/loop11: [0005]:18021 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-93d2bf8d-6f8c-4e88-b4a4-3e662bbbc8b7/dev/88248589-4178-47c0-a558-1ef309300b01)
/dev/loop2: [0005]:20128 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-a4034307-c44e-4111-9ff3-da2eb9e742f3/dev/57dc1f17-2d51-4067-ab72-63f3bb1c81a4)
/dev/loop0: [0005]:1375 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-4d8c9f6d-f34f-4113-b45b-73cf76a42b6e/dev/e702842b-3675-42a2-8b2e-b71590248c38)
/dev/loop18: [0005]:21585 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-50dd3fbc-911f-4097-b4d0-638993bce26c/dev/a2af75d7-9cea-4d1a-b305-2b71f9804e76)
/dev/loop9: [0005]:22257 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-671fba05-9a3f-4206-9b10-e07b15c2de21/dev/f9b4a679-7bdf-42f7-8fa7-5e111a0a2183)
/dev/loop16: [0005]:17652 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-06dc1701-4a8d-4e51-8e47-b8665746eb85/dev/16a35cb1-2f9b-4c02-ba4d-0258e127722d)
/dev/loop7: [0005]:20238 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-1d5c3f67-5008-44c2-894b-bbac36f0369d/dev/c834e263-2b98-4eef-97e1-e8020e9f45a4)
/dev/loop14: [0005]:18170 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-27e3aa5d-78ff-4290-bca0-7ce388d59616/dev/43325d45-effe-4ebc-933e-3092e1fe7370)
/dev/loop5: [0005]:18019 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-2a7225ec-d36f-460a-a149-d472116976fc/dev/88248589-4178-47c0-a558-1ef309300b01)
/dev/loop12: [0005]:23287 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-6e3d4d44-a893-4208-b5bb-7ac842ce466f/dev/87312dee-9cbc-4f0c-9072-37c18f3f1d49)
/dev/loop3: [0005]:22484 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-b7400ad6-c12d-4b7f-b61e-d449f95ed2ee/dev/d356140f-5fd6-4538-bf7b-22142ee83296)
/dev/loop20: [0005]:23591 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-6cd59e57-53bc-4595-8eee-86437a8a672f/dev/fff010bf-0f0e-411e-9d01-e8d7613efc0f)
/dev/loop10: [0005]:15531 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pv-pvc-2ceffbcd-b2d2-4fa4-96ed-f9a671964f03/dev/fbf646ed-bdc1-44d0-8043-1c2ce2c2ec60)
```
### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.25.8
</details>

### Cloud provider

<details>
kubernetes cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
centos9
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://github.com/kubernetes/kubernetes/issues/119608

The underlying reason of this issue is - when node that has pods with raw block volumes is shutdown and assuming node is shutdown for long enough time that - pods on the node get evicted (or deleted), then when the node comes back such pods will be usually stuck in terminating state. 

The reason they are stuck in terminating state is because - although volume read from pod dir gets added to ASOW in `uncertain` state, a mount may still be performed for the volume and when that happens usually mount fails and that causes volume to be updated as `unmounted` in ASOW.  When this happens, it also removes `deviceMountPath` from the volume and hence subsequent attempt to `unmap` the device fails because `deviceMountPath` is empty.

```release-note
Allow deletion of pods that use raw block volumes on node reboot
```

### CODE REVIEW

**Comment by bart0sh** [comment]
/kind bug
/priority important-soon
/triage accepted

@gnufied please provide a release note and a test coverage, thanks

**Comment by jingxu97** [comment]
@gnufied could you add some description about the root cause of the issue?

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 1]
```diff
@@ -39,6 +39,11 @@ import (
 	volumetypes "k8s.io/kubernetes/pkg/volume/util/types"
 )
 
+const (
+	// EmptyUniquePodName is a UniquePodName for empty string.
```
Comment (jsafrane) [inline pkg/volume/util/operationexecutor/operation_executor.go:43]: The comment does not say what `EmptyUniquePodName` means. When a volume in ASW/DSW can get `EmptyUniquePodName`? Why is it good for? When you use it in `IsVolumeReconstructed `, how can it happen the pod name is empty, when the volume was reconstructed from the pod directory which contains the pod name?

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_executor.go:43]: No the pod name can't be empty when volume is reconstructed.  The reason for using empty pod name here is - we are checking for volume state during `nodeStage` (i.e when device is mounted/mapped to global path), so it doesn't matter what is the pod name, but I am trying to see if `uniqueVolumeName` is in reconstructed volume names or not.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 2]
```diff
@@ -414,6 +414,10 @@ func (asw *actualStateOfWorld) IsVolumeReconstructed(volumeName v1.UniqueVolumeN
 	if !ok {
 		return false
 	}
+
+	if podName == operationexecutor.EmptyUniquePodName {
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go:418]: what is reason for this one? and how it is different from the logic in line 407?

Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:418]: So if pod name is empty and volume exists in `foundDuringReconstruction` map, then there is no need to match for pod name, because we are looking for just unique volume name in global path and not any pod specific path.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 3]
```diff
@@ -404,7 +404,7 @@ func (asw *actualStateOfWorld) IsVolumeReconstructed(volumeName v1.UniqueVolumeN
 	volumeState := asw.GetVolumeMountState(volumeName, podName)
 
 	// only uncertain volumes are reconstructed
-	if volumeState != operationexecutor.VolumeMountUncertain {
+	if volumeState != operationexecutor.VolumeMountUncertain && podName != operationexecutor.EmptyUniquePodName {
```
Comment (jsafrane) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go:407]: The comment above does not match the condition now. Please add something about device mounts + pod mounts.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 2 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:418]: Please turn this explanation into a comment.

File: pkg/volume/util/operationexecutor/operation_executor.go (hunk 1 above)
Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_executor.go:43]: I mean, it should be written somewhere in a comment, because nobody is going to read this PR. And it's used to _ignore_ pod names for deviceMounts. Would a better name be more appropriate?

And frankly, a whole new function `IsDeviceMountReconstructed` would clear all the confusion about this PR.

**Review by jsafrane — COMMENTED** [review]
From the issue description it looks it should be possible to reproduce it quite reliably. Would it be possible to add an e2e test?

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 2 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: Added a new function to check if device was reconstructed.

**Comment by gnufied** [comment]
@jsafrane yeah the issue is easily reproducible, but e2e will obviously be disruptive and it is not just a plain reboot but node must be down long enough. IMO the unit test here is definitive and capture the error pretty well without relying on internal state of volume-manager too much. We should be okay.

**Comment by gnufied** [comment]
A further enhancement to this idea is - can a device ever be `Unmounted` globally if corresponding pod local volume is mounted in `uncertain` state?  I have been thinking of adding that check somewhere, so as we don't have inconsistent state in volume-manager. I can file it as a follow up.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 4]
```diff
@@ -780,6 +780,12 @@ func (og *operationGenerator) checkForFailedMount(volumeToMount VolumeToMount, m
 func (og *operationGenerator) markDeviceErrorState(volumeToMount VolumeToMount, devicePath, deviceMountPath string, mountError error, actualStateOfWorld ActualStateOfWorldMounterUpdater) {
 	if volumetypes.IsOperationFinishedError(mountError) &&
 		actualStateOfWorld.GetDeviceMountState(volumeToMount.VolumeName) == DeviceMountUncertain {
+
+		if actualStateOfWorld.IsVolumeDeviceReconstructed(volumeToMount.VolumeName) {
```
Comment (ZhangShuaiyi) [inline pkg/volume/util/operationexecutor/operation_generator.go:784]: In [markVolumeErrorState](https://github.com/kubernetes/kubernetes/blob/f4240cbf925ffc64697d4eabf3c6145d2948e840/pkg/volume/util/operationexecutor/operation_generator.go#L808) we pass `volumeToMount.PodName` to `IsVolumeReconstructed`. Is it possible to use `volumeToMount.PodName` in `markDeviceErrorState` too?

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 5]
```diff
@@ -780,6 +780,12 @@ func (og *operationGenerator) checkForFailedMount(volumeToMount VolumeToMount, m
...
+			klog.V(2).InfoS("MountVolume.markDeviceErrorState uncertainDeviceFix leaving volume uncertain", "volumeName", volumeToMount.VolumeName)
```
Comment (jsafrane) [inline pkg/volume/util/operationexecutor/operation_generator.go:785]: what does `uncertainDeviceFix` mean?

**Comment by jsafrane** [comment]
/approve
Now it's much clearer what the code does, thanks for the refactoring! I have just a minor nit in a log message above.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 5 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: leftover log marker message. removed. :-)

**Comment by jingxu97** [comment]
> mount may still be performed for the volume and when that happens usually mount fails and that causes volume to be updated as unmounted in ASOW. When this happens, it also removes deviceMountPath from the volume and hence subsequent attempt to unmap the device fails because deviceMountPath is empty.

Could you help me understand why mount fails after node is back, and also why mount fail will remove deviceMountPath from the volume? I forgot the details there.

**Comment by gnufied** [comment]
>Could you help me understand why mount could fail after node is back, and also why mount fail will remove deviceMountPath from the volume? I forgot the details there.

Yeah so once node comes back volume still appears in DSOW and since volume was previously marked as uncertain during reconstruction, kubelet tries to once mount the volume. The mount usually at this fails because Driver may simply be unavailable yet - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L1111 

When this happens, we call `markDeviceErrorState` which in turn tries to device as `unmounted` because mount failed with a final error. But when `MarkDeviceAsUnmounted` is called - it clears the `deiveMountPath` and hence any attempt to unmount device will fail in future. @PhanLe1010 posted same analysis here - https://github.com/longhorn/longhorn/issues/6919#issuecomment-1844103590

**Comment by jingxu97** [comment]
> > Could you help me understand why mount could fail after node is back, and also why mount fail will remove deviceMountPath from the volume? I forgot the details there.
> 
> Yeah so once node comes back volume still appears in DSOW and since volume was previously marked as uncertain during reconstruction, kubelet tries to once mount the volume. The mount usually at this fails because Driver may simply be unavailable yet - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L1111
> 
> When this happens, we call `markDeviceErrorState` which in turn tries to device as `unmounted` because mount failed with a final error. But when `MarkDeviceAsUnmounted` is called - it clears the `deiveMountPath` and hence any attempt to unmount device will fail in future. @PhanLe1010 posted same analysis here - [longhorn/longhorn#6919 (comment)](https://github.com/longhorn/longhorn/issues/6919#issuecomment-1844103590)

got it, thank you for the details! The only thing is when driver is not available, if we can identify this error, we should avoid changing any state  such as MarkDeviceAsUnmounted. But this is be out of scope this issue.

**Comment by gnufied** [comment]
>got it, thank you for the details! The only thing is when driver is not available, if we can identify this error, we should avoid changing any state such as MarkDeviceAsUnmounted. But this is be out of scope this issue.

yeah I agree. Lets file a follow up issue to clean things up. I want to keep things short in this PR, because we need to backport this to older versions.

**Comment by PhanLe1010** [comment]
@gnufied 

I see that we are backporting this PR to v1.29. Can we also backport it into the active branch 1.26, 1.27, and 1.28? A lot of users hitting this issue are on older version and not a lot of them can upgrade to v1.29 immediately

**Comment by gnufied** [comment]
@PhanLe1010 yeah sure.

**Comment by PhanLe1010** [comment]
Thanks a lot @gnufied!  We are very much appreciated your help
