### PR TITLE
Fix pkg/kubelet unit tests fail on OSX

### LINKED ISSUE #27730: pkg/kubelet unit tests fail on OSX
TestUpdateNewNodeStatus
TestUpdateExistingNodeStatus
TestUpdateNodeStatusWithRuntimeStateError

The above tests seem to be architecture specific now (and fail on unexpected objects "linux" vs "darwin").

Per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/testing.md#unit-tests I would expect unit tests to still pass on OSX

### PR DESCRIPTION
**Pull request by dims**
use runtime.GOOS for the OperatingSystem and not hardcode it to linux.

Fixes #27730

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

File: pkg/kubelet/kubelet_test.go [hunk 1]
```diff
@@ -2727,7 +2728,7 @@ func TestUpdateNewNodeStatus(t *testing.T) {
 				BootID:                  "1b3",
 				KernelVersion:           "3.16.0-0.bpo.4-amd64",
 				OSImage:                 "Debian GNU/Linux 7 (wheezy)",
-				OperatingSystem:         "linux",
+				OperatingSystem:         goruntime.GOOS,
 				Architecture:            "amd64",
```
Comment (vishh) [inline pkg/kubelet/kubelet_test.go]: nit: Change this to `goRuntime.GOARCH`

**Comment by vishh** [comment]
Just one comment. Otherwise LGTM

File: pkg/kubelet/kubelet_test.go (hunk 1 above)
Comment (dims) [inline pkg/kubelet/kubelet_test.go]: Ack @vishh respinning in a few mins

**Comment by vishh** [comment]
ok to test
