### PR TITLE
do not touch swap for cgroup v1 if not available

### LINKED ISSUE #119467: Failure cluster [ci-kubernetes-e2e-ubuntu-gce-network-policies.] Swap failed for containerd version .6.12-0ubuntu1~20.04.3
##### Error text:
```
[FAILED] Error waiting for all pods to be running and ready: Timed out after 600.000s.
Expected all pods (need at least 0) in namespace "kube-system" to be running and ready (except for 0).
21 / 34 pods were running and ready.
Expected 9 pod replicas, 5 are Running and Ready.
Pods that were neither completed nor running:
    <[]v1.Pod | len:13, cap:16>: 
        - metadata:
            annotations:
              cni.projectcalico.org/podIP: ""
              cni.projectcalico.org/podIPs: ""
            creationTimestamp: "2023-07-18T08:39:37Z"
            generateName: coredns-55968cc89d-
            labels:
              k8s-app: kube-dns
              pod-template-hash: 55968cc89d
            managedFields:
    
   
```
#### Recent failures:
[2023/7/20 04:35:04 ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1681764589919801344)
[2023/7/19 22:35:07 ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1681673989744758784)
[2023/7/19 16:35:04 ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1681583392207933440)
[2023/7/19 10:35:02 ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1681492793534451712)
[2023/7/19 04:34:03 ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1681401944259694592)

/kind failing-test

/sig node
see https://github.com/kubernetes/kubernetes/issues/119446.

> There is a bug https://github.com/containerd/containerd/pull/7836 in containerd that is fixed in v1.6.14. https://github.com/containerd/containerd/releases/tag/v1.6.14
> 
> The test here is using v1.6.12.
> https://github.com/containerd/containerd/blob/main/RELEASES.md#kubernetes-support
> 
> Kubernetes v1.27 supported containerd versions: 1.7.0+, 1.6.15+

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/119467 #119446

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/priority critical-urgent
for triage

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by harche** [comment]
@pacoxu Thanks for this PR, can you send your fixes in containerd repo as well? That way when they cut a new release of the containerd with your changes, we can bump it up in k8s.

**Comment by pacoxu** [comment]
/assign @dims @liggitt 
for vendor update

**Comment by pacoxu** [comment]
> @pacoxu Thanks for this PR, can you send your fixes in containerd repo as well? That way when they cut a new release of the containerd with your changes, we can bump it up in k8s. 

let me check the containerd fix.

**Comment by mqasimsarfraz** [comment]
> > @pacoxu Thanks for this PR, can you send your fixes in containerd repo as well? That way when they cut a new release of the containerd with your changes, we can bump it up in k8s.
> 
> let me check the containerd fix.

@pacoxu There is a fix in place for containerd already, https://github.com/containerd/containerd/pull/8857#issuecomment-1646242407. Please feel free to review it!

**Comment by iholder101** [comment]
LGTM

**Comment by pacoxu** [comment]
@dims @liggitt Do you have time to take a look?

**Comment by dims** [comment]
/approve
/lgtm
/milestone v1.28

fixes failures in our CI jobs for a bug that certainly show up in real world scenarios as well.

**Comment by mqasimsarfraz** [comment]
> > > @pacoxu Thanks for this PR, can you send your fixes in containerd repo as well? That way when they cut a new release of the containerd with your changes, we can bump it up in k8s.
> > 
> > 
> > let me check the containerd fix.
> 
> @pacoxu There is a fix in place for containerd already, [containerd/containerd#8857](https://github.com/containerd/containerd/pull/8857). Please feel free to review it!

The fixes were backported and are available in stable releases:
- https://github.com/containerd/containerd/releases/tag/v1.7.3 
- https://github.com/containerd/containerd/releases/tag/v1.6.22

**Comment by pacoxu** [comment]
> The fixes were backported and are available in stable releases:
> 
> * https://github.com/containerd/containerd/releases/tag/v1.7.3
> * https://github.com/containerd/containerd/releases/tag/v1.6.22

Thanks for the update.

> https://github.com/containerd/containerd/pull/8857#issuecomment-1646761156
> 
> - The fix in v1.6.14 is about when kubelet wasn’t passing any swap limit(swapLimit=0) but swap is not available:  https://github.com/containerd/containerd/pull/7838/
> - The recent fix is that when we pass swap limit but swap is not available
> - I also fixed it in kubelet side https://github.com/kubernetes/kubernetes/pull/119486 as well. (This is fixed in v1.28.0.)
> container also patched a fix in : https://github.com/containerd/containerd/pull/8857 (It will be included in next containerd v1.6.x release)

We may bump containerd later.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 1]
```diff
@@ -337,10 +372,12 @@ func (m swapConfigurationHelper) ConfigureLimitedSwap(lcr *runtimeapi.LinuxConta
 
 func (m swapConfigurationHelper) ConfigureNoSwap(lcr *runtimeapi.LinuxContainerResources) {
 	if !isCgroup2UnifiedMode() {
-		// memorySwapLimit = total permitted memory+swap; if equal to memory limit, => 0 swap above memory limit
-		// Some swapping is still possible.
-		// Note that if memory limit is 0, memory swap limit is ignored.
-		lcr.MemorySwapLimitInBytes = lcr.MemoryLimitInBytes
+		if swapControllerAvailable() {
```
Comment (elezar) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:375]: Question: Should this not be checked regardless of whether unified mode is enabled. Otherwise we explicitly set `memory.swap.max` even if swap is disabled?

For reference, I am having issues launching a >= 1.28.0 using `kind` on a node where swap is disabled. (I will spend some time creating an issue tomorrow).

cc @iholder101

Comment (pacoxu) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:375]: Is this fix a problem? I cannot catch up with you here.

This added a check for `no-cgroup v2`: to not set swap if swap controller is not available.

Comment (elezar) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:375]: I think this fix is fine. I was asking whether this check should also be done on `cgroup v2` systems. I have a PR #120784 under review to do this -- effectively moving the check higher up the call chain.

Feel free to review this as well.
