### PR TITLE
dockershim hostport manager use HostIP

### LINKED ISSUE #98648: [Failing Test] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol
**Which jobs are failing**:
- `ci-kubernetes-e2e-ubuntu-gce`

**Which test(s) are failing**:
- `[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]`

**Since when has it been failing**:
952e6f445

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:
```
I0129 14:50:03.948] STEP: checking connectivity from pod e2e-host-exec to serverIP: 10.138.0.4, port: 54321
I0129 14:50:03.948] Jan 29 14:49:53.197: INFO: ExecWithOptions {Command:[/bin/sh -c curl -g --connect-timeout 5 http://10.138.0.4:54321/hostname] Namespace:hostport-5032 PodName:e2e-host-exec ContainerName:e2e-host-exec Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
I0129 14:50:03.948] Jan 29 14:49:53.198: INFO: >>> kubeConfig: /workspace/.kube/config
I0129 14:50:03.948] Jan 29 14:49:54.749: INFO: pods must have different hostname: pod1 has hostname pod2, pod2 has hostname pod2
I0129 14:50:03.949] Jan 29 14:49:54.750: FAIL: Failed to connect to exposed host ports
```

**Anything else we need to know**:
Related to #98299 

Spyglass link: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1355160798921494528

/sig network
/cc @aojea

### PR DESCRIPTION
**Pull request by aojea**
the hostport manager was not taking into consideration the hostIP
when binding the socket of the hostPort, causing that the same
HostPort can not be used with different IP addresses.

**What type of PR is this?**

/kind bug
/kind failing-test

```release-note
kubelet: fixes a bug in the HostPort dockershim implementation that caused the conformance test "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" to fail.
```

Fixes: https://github.com/kubernetes/kubernetes/issues/98648

### CODE REVIEW

**Comment by aojea** [comment]
/hold
this is an alternative to just skipping the test for dockershim
https://github.com/kubernetes/test-infra/pull/20688

/test

**Comment by aojea** [comment]
the kubelet seems is using kubenet (that is the one used for the hostport thing with kubernetes)

> I0204 08:39:35.290281    9514 flags.go:59] FLAG: --minimum-container-ttl-duration="0s"
> I0204 08:39:35.290287    9514 flags.go:59] FLAG: --minimum-image-ttl-duration="2m0s"
> I0204 08:39:35.290294    9514 flags.go:59] FLAG: --network-plugin="kubenet"
> I0204 08:39:35.290300    9514 flags.go:59] FLAG: --network-plugin-mtu="0"

and the test passes now:

> Kubernetes e2e suite: [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]

**Comment by aojea** [comment]
The hostport tests passes now, these tests are failing though, I think that is due to the commit to force the runtime, will recheck
```
[sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with scheduling without 
```

**Comment by aojea** [comment]
/assign @thockin @BenTheElder @liggitt 
This is the fix for kubenet/dockershim/hostport, this is the same code we have working in CRI-O, that use to vendor this code until we realised that it had a bug because is not able to bind HostPorts to IPs (and that the test that was supposed to verified that was not doing it)
I think that the reason to not detecting this before is that in cloud environments doesn´t make much sense to use HostPorts with HostIP,  but people do a lot of "complicated" things with multiple interfaces, ips, ... and the API is there and clear about that :shrug:

**Comment by aojea** [comment]
/retest
unrelated failures, everything is passing right now

**Comment by dims** [comment]
/milestone v1.21
/area conformance
/priority critical-urgent
/triage accepted

this has conformance implications, without this dockershim nodes cannot pass conformance.

**Comment by liggitt** [comment]
I don't have the networking expertise to review this, but I'm +💯  on making sure dockershim can pass conformance tests.

/unassign

**Comment by dims** [comment]
cc @SergeyKanzhelev @ehashman @adisky

File: pkg/kubelet/dockershim/network/hostport/hostport_manager.go [hunk 1]
```diff
@@ -231,6 +238,11 @@ func (hm *hostportManager) Remove(id string, podPortMapping *PodPortMapping) (er
 		}
 	}
 
+	// exit if there is nothing to remove
+	if len(existingChainsToRemove) == 0 {
+		return nil
```
Comment (johnbelamaric) [inline pkg/kubelet/dockershim/network/hostport/hostport_manager.go:243]: Not familiar with this code, but is there any chance that exiting early, which prevents calling `closeHostPorts`, could cause a leak if the previous run crashed after `syncIPTables` and before `closeHostPorts`?

**Review by johnbelamaric — COMMENTED** [review]
Can we cherry pick to 1.20? Ref: https://github.com/kubernetes/test-infra/pull/20688#issuecomment-773079404

File: pkg/kubelet/dockershim/network/hostport/hostport_manager.go (hunk 1 above)
Comment (aojea) [reply pkg/kubelet/dockershim/network/hostport/hostport_manager.go:243]: hmm you are absolutely right

Comment (aojea) [reply pkg/kubelet/dockershim/network/hostport/hostport_manager.go:243]: however, this state is weird, so you still have hostportMappings but you don´t have iptables rules :thinking: 
I´m trying to remember why we added this, it was for dual stack for sure, because we called twice Remove()

Comment (aojea) [reply pkg/kubelet/dockershim/network/hostport/hostport_manager.go:243]: I think we can return closeHostports() here too, the method goes through the map so it doesn´t seem risky.
Holding iptables lock for nothing in a busy environment is expensive ....

**Comment by johnbelamaric** [comment]
this looks good to me but I would rather someone with some experience with this code give the lgtm and approval

File: pkg/kubelet/dockershim/network/hostport/fake_iptables.go [hunk 2]
```diff
@@ -148,14 +148,14 @@ func (f *fakeIPTables) ensureRule(position utiliptables.RulePosition, tableName
 		return true, nil
 	}
 
-	if position == utiliptables.Prepend {
```
Comment (thockin) [inline pkg/kubelet/dockershim/network/hostport/fake_iptables.go:151]: Ideally this would be in a sub-pkg, not linked into prod code.  Not going to hold this up for that.

**Review by thockin — COMMENTED** [review]
Despite the size, this seems OK to me.

Do you want to clean up the commits?  "TEMP" sets off alarm bells.

/approve

File: cluster/gce/config-default.sh [hunk 3]
```diff
@@ -98,6 +98,7 @@ export KUBELET_TEST_ARGS=${KUBE_KUBELET_EXTRA_ARGS:-}
 
 # Default container runtime
 export CONTAINER_RUNTIME=${KUBE_CONTAINER_RUNTIME:-containerd}
+export CONTAINER_RUNTIME="docker"
```
Comment (BenTheElder) [inline cluster/gce/config-default.sh:101]: @thockin this commit should indeed not merge, it's just a quick way to ensure the default presubmit runs dockershim for vetting the PR by forcing it regardless of the config.

Comment (BenTheElder) [reply cluster/gce/config-default.sh:101]: (also I suggested this as a low effort way to sanity check the code 🙃 )
I'll keep an eye out to help merge when it's removed.

Comment (aojea) [reply cluster/gce/config-default.sh]: removed
