### PR TITLE
Fix kubelet start in local-up-cluster.sh

### LINKED ISSUE #76048: hack/local-up-cluster.sh fails with kubelet reporting "server.go:160] unknown command"
The master branch is failing now. The error was because when staring the kubelet, the local-up-cluster.sh script ran:
```bash
hyperkube kubelet '' --v=3...
```
The `''` was interpreted as non-flag arguments and caused the kubelet to fail.

/assign
/kind bug
cc @roycaihw

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fixes #76048

Otherwise the empty "${priv_arg}" is interpreted as a non-flag argument and causes kubelet to fail to start.

/sig cluster-lifecycle
/assign @BenTheElder 
cc @roycaihw @janetkuo

### CODE REVIEW

File: hack/local-up-cluster.sh [hunk 1]
```diff
@@ -750,7 +750,7 @@ function start_kubelet {
 
     # shellcheck disable=SC2206
```
Comment (BenTheElder) [inline hack/local-up-cluster.sh]: we should not have inline shellcheck disable comments :/
this lint also catches legitimate bugs

File: hack/local-up-cluster.sh [hunk 2]
```diff
@@ -750,7 +750,7 @@ function start_kubelet {
...
     all_kubelet_flags=(
-      "${priv_arg}"
+      ${priv_arg}
```
Comment (BenTheElder) [inline hack/local-up-cluster.sh]: is this a single flag when set?

File: hack/local-up-cluster.sh (hunk 1 above)
Comment (BenTheElder) [reply hack/local-up-cluster.sh]: https://github.com/koalaman/shellcheck/wiki/SC2206

Comment (dims) [reply hack/local-up-cluster.sh]: ack, i'll get rid of it when i get a chance

File: hack/local-up-cluster.sh (hunk 2 above)
Comment (dims) [reply hack/local-up-cluster.sh]: yes it is https://cs.k8s.io/?q=priv_arg&i=nope&files=&repos=kubernetes/kubernetes

Comment (BenTheElder) [reply hack/local-up-cluster.sh]: `${priv_arg:+"$priv_arg"}` will avoid splitting issues and _also_ not become an empty string

File: hack/local-up-cluster.sh (hunk 1 above)
Comment (BenTheElder) [reply hack/local-up-cluster.sh]: will come back to this one later.

File: hack/local-up-cluster.sh (hunk 2 above)
Comment (BenTheElder) [reply hack/local-up-cluster.sh]: @caesarxuchao let's do `${priv_arg:+"$priv_arg"}`, this will expand to a single flag (shell word / array entry) if set to a non-empty string and otherwise not expand to anything.
