### PR TITLE
Fixes #75706 - Show warning message when namespace is specified for deleting a cluster-scoped resource

### LINKED ISSUE #75706: `kubectl delete ns -n <namespace> --all` deletes ALL namespaces
**What happened**:
`kubectl delete namespace --namespace=<namespace> --all` deletes all namespaces in the cluster. 

**What you expected to happen**:
The above command should throw an error since `--namespace` and `--all` are mutually exclusive commands.

**How to reproduce it (as minimally and precisely as possible)**:
**CAUTION**: This might delete all namespaces in your cluster!
Execute the command `kubectl delete namespace --namespace=<namespace> --all` by replacing `<namespace>` to any of your namespace.

**Anything else we need to know?**:
None.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
MacBook Pro 2.9 GHz Intel Core i9
```
- OS (e.g: `cat /etc/os-release`):
```
macOS Mojave Version 10.14.3
```
- Kernel (e.g. `uname -a`):
```
Darwin mbp 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by YoubingLi**
**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

Show warning message when namespace is specified for deleting a cluster-scoped resource

**Which issue(s) this PR fixes**:

Fixes # 75706

**Special notes for your reviewer**:
/assign @liggitt 
/assign @yue9944882

**Does this PR introduce a user-facing change?**:

   no

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/delete/delete.go [hunk 1]
```diff
@@ -143,12 +143,122 @@ func NewCmdDelete(f cmdutil.Factory, streams genericclioptions.IOStreams) *cobra
...
+	}
+}
+
 func (o *DeleteOptions) Complete(f cmdutil.Factory, args []string, cmd *cobra.Command) error {
 	cmdNamespace, enforceNamespace, err := f.ToRawKubeConfigLoader().Namespace()
 	if err != nil {
 		return err
 	}
 
+	err = checkNamespaceWithArgs(f, args[0], cmd)
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: Rejecting a command that specified -n along with cluster-scoped resources is not backwards compatible. at most, we could warn at this point. It would also be much simpler to check this after you have o.Result and o.Mapper resolved (or in the delete visit loop).

In Complete():
```
o.WarnClusterScope = enforceNamespace
```

in DeleteResult():
```
if !warnedClusterScope && o.WarnClusterScope && info.Mapping.Scope.Name() == meta.RESTScopeNameRoot {
	warnedClusterScope = true
	fmt.Fprintf(o.ErrOut, "Warning: deleting cluster-scoped resources, not scoped to the provided namespace\n")
}

response, err := o.deleteResource(info, options)
...
```

that would also give us a place to require an explicit opt-in in the future to delete cluster-scoped things in combination with an explicit --namespace arg (after a suitable warning/deprecation period)

Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: @liggitt 

     This approach is simple, but the warning message is appear alternately.

      Meanwhile, we don't need to show warning message for "default", "kube-system", "public" namespace who is rejected by server.


     BTW, do we need to show warning message if --all-namespaces is specified in the command line?

     I prefer to show one warning message for the command and handle --all-namespaces as --namespace.

./kubectl delete namespace -n test --all
Warning: deleting cluster-scoped resources <test>, not scoped to the provided namespace
namespace "test" deleted
Warning: deleting cluster-scoped resources <test1>, not scoped to the provided namespace
namespace "test1" deleted
Warning: deleting cluster-scoped resources <test2>, not scoped to the provided namespace
namespace "test2" deleted
Error from server (Forbidden): namespaces "default" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-public" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-system" is forbidden: this namespace may not be deleted

Comment (liggitt) [reply pkg/kubectl/cmd/delete/delete.go]: The "warnedClusterScope = true" marker could let us show the warning once per invocation

Comment (liggitt) [reply pkg/kubectl/cmd/delete/delete.go]: I could see skipping the warning if --all-namespaces was specified. Is that allowed in combination with an explicit --namespace arg?

Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: -n name and --all-namespaces={true|false} is allowed to specifed together in command.

Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: @liggitt @smarterclayton @yue9944882

   Diff has been updated and please help review it.

File: pkg/kubectl/cmd/delete/delete.go [hunk 2]
```diff
@@ -149,6 +150,8 @@ func (o *DeleteOptions) Complete(f cmdutil.Factory, args []string, cmd *cobra.Co
 		return err
 	}
 
+	o.WarnClusterScope = enforceNamespace
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: `o.WarnClusterScope = enforceNamespace && !o.DeleteAllNamespaces`?

File: pkg/kubectl/cmd/delete/delete.go [hunk 3]
```diff
@@ -117,6 +117,7 @@ type DeleteOptions struct {
 	Result        *resource.Result
 
 	genericclioptions.IOStreams
+	WarnClusterScope bool
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: nit: move up to the same set of variables as `Quiet`

File: pkg/kubectl/cmd/delete/delete.go [hunk 4]
```diff
@@ -216,6 +219,34 @@ func (o *DeleteOptions) Validate() error {
 	case o.ForceDeletion:
 		fmt.Fprintf(o.ErrOut, "warning: --force is ignored because --grace-period is not 0.\n")
 	}
+
+	if o.WarnClusterScope {
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: move this inside the Visit method inside DeleteResult so we don't iterate through all objects twice

File: pkg/kubectl/cmd/delete/delete.go [hunk 5]
```diff
@@ -216,6 +219,34 @@ func (o *DeleteOptions) Validate() error {
...
+		infos,_ := o.Result.Infos()
+		clsRes := make(map[string]bool)
+		if infos != nil {
+			for _, info := range infos {
+				if info.Mapping.Scope.Name() == meta.RESTScopeNameRoot {
+					switch info.Name {
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: don't special-case namespace names

File: test/cmd/core.sh [hunk 6]
```diff
@@ -1319,13 +1319,18 @@ run_namespace_tests() {
...
+
   # Clean up
   kubectl delete namespace my-namespace --wait=false
   # make sure that wait properly waits for finalization
   kubectl wait --for=delete ns/my-namespace
   output_message=$(! kubectl get ns/my-namespace 2>&1 "${kube_flags[@]}")
   kube::test::if_has_string "${output_message}" ' not found'
 
+  kubectl create namespace my-namespace
+  output_message=$(! kubectl delete namespace -n my-namespace --all 2>&1 "${kube_flags[@]}")
```
Comment (liggitt) [inline test/cmd/core.sh]: suggest deleting all of a different cluster-scoped object instead, like PersistentVolumes, where the command can actually succeed

File: pkg/kubectl/cmd/delete/delete.go (hunk 4 above)
Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: If I moved them inside Visit, there is warning message for each cluster-scoped resource.

It turns out there are multiple warning message in the output.

Comment (liggitt) [reply pkg/kubectl/cmd/delete/delete.go]: Set a warnedClusterScope boolean outside the visit function and set it to true once you've warned once

File: pkg/kubectl/cmd/delete/delete.go (hunk 2 above)
Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: If -n / --namespace is specified, enforceNamespace  would be true.

If --all-namespace is specified, I prefer not to show warning message.

Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: Even "--alll" is not specified, warning message shoule be thrown when the user deletes a cluster-scoped resource with -n option

Comment (liggitt) [reply pkg/kubectl/cmd/delete/delete.go]: Correct, that's what that does

File: pkg/kubectl/cmd/delete/delete.go (hunk 5 above)
Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: Done.
Case has been added  in test/cmd/core.sh, test/cmd/rbac.sh and test/cmd/storage.sh.

File: test/cmd/core.sh (hunk 6 above)
Comment (YoubingLi) [reply test/cmd/core.sh]: Done

**Comment by YoubingLi** [comment]
@liggitt 

    Diff has been updated.

File: pkg/kubectl/cmd/delete/delete.go [hunk 7]
```diff
@@ -149,6 +150,8 @@ func (o *DeleteOptions) Complete(f cmdutil.Factory, args []string, cmd *cobra.Co
 		return err
 	}
 
+	o.WarnClusterScope = enforceNamespace && ! o.DeleteAllNamespaces
```
Comment (liggitt) [inline pkg/kubectl/cmd/delete/delete.go]: `go fmt` will drop the space after `!`

File: test/cmd/rbac.sh [hunk 8]
```diff
@@ -30,6 +30,12 @@ run_clusterroles_tests() {
   kube::test::get_object_assert clusterrolebindings/cluster-admin "{{.metadata.name}}" 'cluster-admin'
 
   # test `kubectl create clusterrole`
+  kubectl create "${kube_flags[@]}" clusterrole pod-admin --verb=* --resource=pods
+  kube::test::get_object_assert clusterrole/pod-admin "{{range.rules}}{{range.verbs}}{{.}}:{{end}}{{end}}" '\*:'
+  output_message=$(! kubectl delete clusterrole pod-admin -n test 2>&1 "${kube_flags[@]}")
```
Comment (liggitt) [inline test/cmd/rbac.sh]: the command shouldn't fail, so there shouldn't be a `!` in this invocation, right?

File: test/cmd/storage.sh [hunk 9]
```diff
@@ -41,6 +41,13 @@ run_persistent_volumes_tests() {
   # Post-condition: no PVs
   kube::test::get_object_assert pv "{{range.items}}{{$id_field}}:{{end}}" ''
 
+  kubectl create -f test/fixtures/doc-yaml/user-guide/persistent-volumes/volumes/local-01.yaml "${kube_flags[@]}"
+  kube::test::get_object_assert pv "{{range.items}}{{$id_field}}:{{end}}" 'pv0001:'
+  output_message=$(! kubectl delete pv -n test --all 2>&1 "${kube_flags[@]}")
```
Comment (liggitt) [inline test/cmd/storage.sh]: the command shouldn't fail, so there shouldn't be a `!` in this invocation, right?

Comment (YoubingLi) [reply test/cmd/storage.sh]: Correct

File: test/cmd/rbac.sh (hunk 8 above)
Comment (YoubingLi) [reply test/cmd/rbac.sh]: Correct

File: pkg/kubectl/cmd/delete/delete.go (hunk 7 above)
Comment (YoubingLi) [reply pkg/kubectl/cmd/delete/delete.go]: Done

File: test/cmd/core.sh [hunk 10]
```diff
@@ -1326,6 +1326,12 @@ run_namespace_tests() {
   output_message=$(! kubectl get ns/my-namespace 2>&1 "${kube_flags[@]}")
   kube::test::if_has_string "${output_message}" ' not found'
 
+  kubectl create namespace my-namespace
+  kube::test::get_object_assert 'namespaces/my-namespace' "{{$id_field}}" 'my-namespace'
+  output_message=$(kubectl delete namespace -n my-namespace --all 2>&1 "${kube_flags[@]}")
```
Comment (liggitt) [inline test/cmd/core.sh]: this test is failing

**Comment by YoubingLi** [comment]
All failure cases are not related to  my code change.

/retest

**Comment by liggitt** [comment]
run_namespace_tests is failing, seems related

**Comment by YoubingLi** [comment]
According to following log

  I0402 01:37:40.255] [32mcore.sh:1330: Successful get namespaces/my-namespace {{.metadata.name}}: my-namespace
I0402 01:37:40.510] (B[m+++ exit code: 1
I0402 01:37:40.516] +++ error: 1
I0402 01:37:40.553] Error when running run_namespace_tests

Seems like line 1332 failed

1329   kubectl create namespace my-namespace
1330   kube::test::get_object_assert 'namespaces/my-namespace' "{{$id_field}}" 'my-namespace'
1331   output_message=$(kubectl delete namespace -n my-namespace --all 2>&1 "${kube_flags[@]}")
1332   kube::test::if_has_string "${output_message}" 'warning: deleting cluster-scoped resources'
1333   kube::test::if_has_string "${output_message}" 'namespace "my-namespace" deleted'

**Comment by liggitt** [comment]
line 1331 failed, because `kubectl delete namespace --all` never succeeds, because kube-system is not allowed to be deleted

**Comment by YoubingLi** [comment]
Yeah. I just figured it out

====  ./kubectl delete namespace -n my-namespace --all

warning: deleting cluster-scoped resources, not scoped to the provided namespace
namespace "my-namespace" deleted
Error from server (Forbidden): namespaces "default" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-public" is forbidden: this namespace may not be deleted
Error from server (Forbidden): namespaces "kube-system" is forbidden: this namespace may not be deleted

===== echo $?
1

**Comment by YoubingLi** [comment]
@liggitt @yue9944882 @smarterclayton 

    All test are passed
