### PR TITLE
Tolerate partial discovery in garbage collector

### LINKED ISSUE #55022: controller-manager crash loops if gc controller doesn't have access to extension apis
```
E1102 20:08:46.999099       5 controllermanager.go:480] Error starting "garbagecollector"
F1102 20:08:46.999145       5 controllermanager.go:155] error starting controllers: failed to get supported resources from server: unable to retrieve the complete list of server APIs: identity.k8s.io/v1alpha1: forbidden: User "system:serviceaccount:kube-system:generic-garbage-collector" cannot get path "/apis/identity.k8s.io/v1alpha1"
```

This is a fatal error. Is this the expected behavior?

/sig auth
/sig api-machinery

@kubernetes/sig-api-machinery-bugs

### PR DESCRIPTION
**Pull request by ironcladlou**
Allow the garbage collector to tolerate partial discovery failures. On a
partial failure, use whatever was discovered, log the failures, and
allow the resync logic to try again later.

Fixes #55022.

```release-note
API discovery failures no longer crash the kube controller manager via the garbage collector.
```

/cc @caesarxuchao

### CODE REVIEW

File: pkg/controller/garbagecollector/garbagecollector.go [hunk 1]
```diff
@@ -595,7 +595,11 @@ func (gc *GarbageCollector) GraphHasUID(UIDs []types.UID) bool {
 func GetDeletableResources(discoveryClient discovery.DiscoveryInterface) (map[schema.GroupVersionResource]struct{}, error) {
 	preferredResources, err := discoveryClient.ServerPreferredResources()
 	if err != nil {
-		return nil, fmt.Errorf("failed to get supported resources from server: %v", err)
+		if discovery.IsGroupDiscoveryFailedError(err) {
+			glog.V(0).Infof("failed to discover some groups: %v", err.(*discovery.ErrGroupDiscoveryFailed).Groups)
```
Comment (ironcladlou) [inline pkg/controller/garbagecollector/garbagecollector.go]: TODO: decide on an appropriate log level.

**Comment by ironcladlou** [comment]
Still needs testing.

File: pkg/controller/garbagecollector/garbagecollector.go (hunk 1 above)
Comment (ironcladlou) [reply pkg/controller/garbagecollector/garbagecollector.go]: Should this log and tolerate *any* discovery error?

Comment (ironcladlou) [reply pkg/controller/garbagecollector/garbagecollector.go]: Answer: yes

Comment (caesarxuchao) [reply pkg/controller/garbagecollector/garbagecollector.go]: Why not `glog.Warning`?

Comment (lavalamp) [reply pkg/controller/garbagecollector/garbagecollector.go]: And include a line to the effect that it will be retried.

File: pkg/controller/garbagecollector/garbagecollector.go [hunk 2]
```diff
@@ -592,15 +588,37 @@ func (gc *GarbageCollector) GraphHasUID(UIDs []types.UID) bool {
...
+		}
+	}
+	if preferredResources == nil {
+		return map[schema.GroupVersionResource]struct{}{}
 	}
+
+	// This is extracted from discovery.GroupVersionResources to allow tolerating
+	// failures on a per-resource basis.
 	deletableResources := discovery.FilteredBy(discovery.SupportsAllVerbs{Verbs: []string{"delete"}}, preferredResources)
-	deletableGroupVersionResources, err := discovery.GroupVersionResources(deletableResources)
```
Comment (caesarxuchao) [inline pkg/controller/garbagecollector/garbagecollector.go]: How about modifying `discovery.GroupVersionResources` to report error after parsing all resources?

File: pkg/controller/garbagecollector/garbagecollector.go (hunk 1 above)
Comment (ironcladlou) [reply pkg/controller/garbagecollector/garbagecollector.go]: Fixed

**Comment by lavalamp** [comment]
Giving this the approve flag, so it can go in as soon as Chao lgtms.

File: pkg/controller/garbagecollector/garbagecollector.go (hunk 2 above)
Comment (ironcladlou) [reply pkg/controller/garbagecollector/garbagecollector.go]: Didn't feel like changing its semantics in any way and doing the requisite usage audit for this, but generally I agree it could return an aggregated error or something.

File: pkg/controller/garbagecollector/garbagecollector_test.go [hunk 3]
```diff
@@ -671,3 +673,109 @@ func TestOrphanDependentsFailure(t *testing.T) {
...
+			Error:              test.err,
+		}
+		actual := GetDeletableResources(client)
+		if !reflect.DeepEqual(test.deletableResources, actual) {
+			t.Errorf("expected resources:\n%v\ngot:\n%v", test.deletableResources, actual)
+		}
+	}
+}
+
+type fakeServerResources struct {
```
Comment (caesarxuchao) [inline pkg/controller/garbagecollector/garbagecollector_test.go]: How about using the fake discovery client: https://github.com/kubernetes/kubernetes/blob/454074d2303424bd71ad340bdbf307aa4196a59d/staging/src/k8s.io/client-go/discovery/fake/discovery.go#L34

I know the fake client hasn't implemented the `ServerPreferredResources` yet, but shouldn't be hard to implement.

Comment (ironcladlou) [reply pkg/controller/garbagecollector/garbagecollector_test.go]: Saw that, but it also doesn't implement any user-specific error stuff and I didn't want to mess with it at the moment. Okay to just add an error field to the fake struct and return it from the implementation functions?

File: pkg/controller/garbagecollector/garbagecollector.go (hunk 2 above)
Comment (caesarxuchao) [reply pkg/controller/garbagecollector/garbagecollector.go]: Ok. How about adding `discovery.GroupVersionResourcesReturnLate` (or with a better name)? I think such a function is going to be useful for others as well.

File: pkg/controller/garbagecollector/garbagecollector_test.go (hunk 3 above)
Comment (caesarxuchao) [reply pkg/controller/garbagecollector/garbagecollector_test.go]: I see. Let's keep it as is then.

**Comment by ironcladlou** [comment]
@caesarxuchao @lavalamp I'm actually out of time to work on this today (and may have limited time tomorrow), so I went ahead and squashed in case you all decide that the feedback is minor enough to merge as-is. Otherwise I'll get to the remaining comment (https://github.com/kubernetes/kubernetes/pull/55259#pullrequestreview-74917078) and any others that arise ASAP. Thanks for the review!

**Comment by caesarxuchao** [comment]
Yes, the comments are minors. It's fine to send follow-up PRs. Thank you.

/lgtm

**Comment by justinsb** [comment]
Can we get this into 1.8.4?  Without it the aggregated apiserver feature in 1.8 is not really safe cc @jpbetz

File: pkg/controller/garbagecollector/garbagecollector.go [hunk 4]
```diff
@@ -592,15 +588,37 @@ func (gc *GarbageCollector) GraphHasUID(UIDs []types.UID) bool {
...
+//
+// All discovery errors are considered temporary. Upon encountering any error,
+// GetDeletableResources will log and return any discovered resources it was
+// able to process (which may be none).
+func GetDeletableResources(discoveryClient discovery.ServerResourcesInterface) map[schema.GroupVersionResource]struct{} {
 	preferredResources, err := discoveryClient.ServerPreferredResources()
 	if err != nil {
-		return nil, fmt.Errorf("failed to get supported resources from server: %v", err)
+		if discovery.IsGroupDiscoveryFailedError(err) {
+			glog.Warning("failed to discover some groups: %v", err.(*discovery.ErrGroupDiscoveryFailed).Groups)
```
Comment (php-coder) [inline pkg/controller/garbagecollector/garbagecollector.go]: I've created https://github.com/kubernetes/kubernetes/pull/56150 to fix improper formatting.

**Comment by justinsb** [comment]
Guess we missed 1.8.4 - can we get this into 1.8.5 please @jpbetz ? :-)

**Comment by justinsb** [comment]
Created #56222 to cherry-pick against 1.8.
