### PR TITLE
Fix reference to versioned object in kubectl apply

### LINKED ISSUE #19639: kubectl apply should be able to take a List
kubectl create, delete, etc. can already take a List object. kubectl apply can take the list object when it does creation, but it gives an (ugly) error when it's configuring the objects.

```
$ cat rcs.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx
  spec:
    replicas: 1
    selector:
      run: nginx
    template:
      metadata:
        labels:
          run: nginx
      spec:
        containers:
        - image: nginx
          name: nginx
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: nginx-2
  spec:
    replicas: 1
    selector:
      run: nginx-2
    template:
      metadata:
        labels:
          run: nginx-2
      spec:
        containers:
        - image: nginx
          name: nginx-2
$ kubectl create -f rcs.yaml
replicationcontroller "nginx" created
replicationcontroller "nginx-2" created
$ kubectl delete -f rcs.yaml
replicationcontroller "nginx" deleted
replicationcontroller "nginx-2" deleted
$ kubectl apply -f rcs.yaml
replicationcontroller "nginx" created
replicationcontroller "nginx-2" created
```

Then... expected:

```
$ kubectl apply -f rcs.yaml
replicationcontroller "nginx" configured
replicationcontroller "nginx-2" configured
$
```

Actual:

```
$ kubectl apply -f rcs.yaml
expected a struct, but received a %!t(string=nil)
expected a struct, but received a %!t(string=nil)
$
```

### PR DESCRIPTION
**Pull request by ghodss**
Fixes #19639.
#19639 occurs because info.VersionedObject is not filled in when Visit'ing elements of a builder when the input is a List (as opposed to a single object). VersionedObject is the struct used to create the strategic merge patch that is sent to the server. One option is to try and fix builder so that VersionedObject is filled in for List items, but it would require really bending builder over backwards because builder isn't really designed to provide VersionedObjects alongside Objects (VersionedObjects are [considered optional](https://github.com/kubernetes/kubernetes/blob/2fd38a7dc022c28f05403355061d521d8f124da3/pkg/kubectl/resource/visitor.go#L77-L80) and there's even a [TODO to eliminate them](https://github.com/kubernetes/kubernetes/blob/2fd38a7/pkg/kubectl/resource/mapper.go#L65-L67)). Instead @smarterclayton has recommended creating a RawResult method on builder, which provides the raw result from the server instead of one that has been converted to a potentially internal object or gone through any other mutations.

That would be a pretty major refactoring, while this is fairly broken behavior (List works for all other kubectl actions e.g. create, delete, etc.), and it would be great to get this fix into 1.2. As a result, I've just switched from using info.VersionedObject to using the server-side versioned serialized object (which will always exist by this point in the code) to create a versioned struct.

This is a little hacky but the whole thing will be much simpler when we create and move to RawResult, and looking even further ahead it's possible this code will be refactored to move server-side. As is, this fix doesn't change the status quo in any fundamental way and fixes a major bug.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

File: pkg/kubectl/cmd/apply.go [hunk 1]
```diff
@@ -161,8 +162,18 @@ func RunApply(f *cmdutil.Factory, cmd *cobra.Command, out io.Writer, options *Ap
 			return cmdutil.AddSourceToErr(fmt.Sprintf("retrieving original configuration from:\n%v\nfor:", info), info.Source, err)
 		}
 
+		// Create the versioned struct from the original from the server for
+		// strategic pitch.
```
Comment (bgrant0607) [inline pkg/kubectl/cmd/apply.go]: patch

**Comment by smarterclayton** [comment]
Can you add a reproducer test?  This *will* break when we fix this unless we have it :)

**Comment by ghodss** [comment]
Test added, with a small refactoring to break the dependency on example files and the ability to create custom fixtures for the test. Verified that the test is broken with the old code and fixed with the new.

File: pkg/kubectl/cmd/apply.go (hunk 1 above)
Comment (ghodss) [inline pkg/kubectl/cmd/apply.go]: done

**Comment by ghodss** [comment]
@smarterclayton Any chance for a LGTM?

**Comment by ghodss** [comment]
There's nothing left to do here but to wait until the merge robot gets to it, right?

**Comment by bgrant0607** [comment]
@ghodss Correct, unless it needs to be rebased before that occurs.

**Comment by ghodss** [comment]
Can someone re-kick jenkins unit/integration? I believe it's a flake.

**Comment by ghodss** [comment]
Though it seems like this might be a candidate for manual merge? Given how many times the tests have all passed. All the checks were green yesterday.

**Comment by smarterclayton** [comment]
@k8s-bot test this github issue: #IGNORE

**Comment by jackgr** [comment]
@ghodss Are there any other kubectl apply issues that are blocking you at the moment?

**Comment by ghodss** [comment]
@jackgr Not at the moment. However we plan to do a lot of testing when a 1.2 beta is released with apply and deployment objects, so that may uncover a few things at that point.
