### PR TITLE
DRA: e2e: test non-graceful node shutdown

### LINKED ISSUE #120421: DRA: interaction with unexpected node shutdown KEP
We need to explore how DRA interacts with https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown.

One likely outcome is that the DRA helper code watches for nodes with the special `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` label and helps DRA drivers clean up.

/sig node

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Added DRA e2e test that covers non graceful node shutdown

#### Which issue(s) this PR fixes:

Fixes #120421

#### Special notes for your reviewer:

see https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown for more details

This test takes 72 seconds to run:
```
Ran 1 of 7394 Specs in 72.083 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 7393 Skipped
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/dra/dra.go [hunk 1]
```diff
@@ -775,6 +777,70 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
...
+			gomega.Eventually(ctx, func(ctx context.Context) (*resourcev1alpha2.ResourceClaim, error) {
+				return b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name).Get(ctx, claim.Name, metav1.GetOptions{})
+			}).WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", (*resourcev1alpha2.AllocationResult)(nil)))
+
+			ginkgo.By("start node" + nodeName)
+			_, stderr, err = framework.RunCmd("docker", "start", nodeName)
+			gomega.Expect(stderr).To(gomega.BeEmpty())
+			framework.ExpectNoError(err)
+
+			ginkgo.By("remove out-of-service taint from the node " + nodeName)
```
Comment (pohly) [inline test/e2e/dra/dra.go:838]: This is also redundant.

File: test/e2e/dra/dra.go [hunk 2]
```diff
@@ -775,6 +777,70 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
...
+
+			ginkgo.By("waiting for claim to get deallocated")
+			gomega.Eventually(ctx, func(ctx context.Context) (*resourcev1alpha2.ResourceClaim, error) {
+				return b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name).Get(ctx, claim.Name, metav1.GetOptions{})
+			}).WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", (*resourcev1alpha2.AllocationResult)(nil)))
+
+			ginkgo.By("start node" + nodeName)
+			_, stderr, err = framework.RunCmd("docker", "start", nodeName)
+			gomega.Expect(stderr).To(gomega.BeEmpty())
+			framework.ExpectNoError(err)
```
Comment (pohly) [inline test/e2e/dra/dra.go:836]: You can move all of this into the `DeferCleanup` above. A cleanup callback can fail just like the `It` callback and it will make the test as failed.

File: test/e2e/dra/dra.go [hunk 3]
```diff
@@ -775,6 +777,70 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
...
+				Key:    v1.TaintNodeOutOfService,
+				Effect: v1.TaintEffectNoExecute,
+			}
+			e2enode.AddOrUpdateTaintOnNode(ctx, f.ClientSet, nodeName, taint)
+			ginkgo.DeferCleanup(e2enode.RemoveTaintOffNode, f.ClientSet, nodeName, taint)
+
+			ginkgo.By("waiting for claim to get deallocated")
+			gomega.Eventually(ctx, func(ctx context.Context) (*resourcev1alpha2.ResourceClaim, error) {
+				return b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name).Get(ctx, claim.Name, metav1.GetOptions{})
+			}).WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", (*resourcev1alpha2.AllocationResult)(nil)))
```
Comment (pohly) [inline test/e2e/dra/dra.go:831]: You can wrap `b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name).Get` with the helper in `e2e/framework/get.go` to get support handling transient API server errors, something like:


```suggestion
			gomega.Eventually(ctx, framework.GetObject(b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name), claim.Name, metav1.GetOptions{}).		 WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", gomega.BeNil()))
```

I'm using `gomega.BeNil` because it expresses the intent a bit more concisely.

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e/dra/dra.go [hunk 4]
```diff
@@ -775,6 +777,70 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
 	})
 })
 
+// This test covers aspects of non graceful node shutdown by DRA controller
+// More details about this can be found in the KEP:
+// https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown
+var _ = ginkgo.Describe("[sig-node] [Serial] [Disruptive] [Slow] [Feature:DynamicResourceAllocation] DRA: handling non graceful node shutdown", func() {
```
Comment (pohly) [inline test/e2e/dra/dra.go:783]: Does this have to be a new `Describe`? Can't it be a new `It` under some existing context?

File: test/e2e/dra/dra.go [hunk 5]
```diff
@@ -775,6 +777,70 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
...
+			labelSelector := labels.SelectorFromSet(labels.Set(pod.Labels))
+			pods, err := e2epod.WaitForPodsWithLabelRunningReady(ctx, f.ClientSet, pod.Namespace, labelSelector, 1, framework.PodStartTimeout)
+			framework.ExpectNoError(err, "start pod")
+			runningPod := &pods.Items[0]
+
+			nodeName := runningPod.Spec.NodeName
+			// Prevent builder tearDown to fail waiting for unprepared resources
+			delete(b.driver.Nodes, nodeName)
+			ginkgo.By("stop node " + nodeName + " non gracefully")
+			ginkgo.DeferCleanup(framework.RunCmd, "docker", "start", nodeName)
```
Comment (pohly) [inline test/e2e/dra/dra.go:815]: There's a dependency on running on a kind cluster here which isn't expressed via some test tag. At least call it out in the test comment, as we don't have a feature tag defined for it.

File: test/e2e/dra/dra.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:836]: why?

File: test/e2e/dra/dra.go (hunk 4 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:783]: No, it doesn't. I separated it because I wanted to show that's this is a special test case. It's disruptive, it shuts down test node, it works only with kind. I think it deserves to be visually separated in the test code.

File: test/e2e/dra/dra.go (hunk 3 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go]: After applying this, I've got this error:
```
type "k8s.io/client-go/kubernetes/typed/resource/v1alpha2".ResourceClaimInterface of b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name) does not match framework.APIGetFunc[T] (cannot infer T)compiler[CannotInferTypeArgs](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#CannotInferTypeArgs)
func (kubernetes.Interface).ResourceV1alpha2() v1alpha2.ResourceV1alpha2Interface
[(kubernetes.Interface).ResourceV1alpha2 on pkg.go.dev]
```
Any hints of fixing it?

File: test/e2e/dra/dra.go (hunk 2 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:834]: forget about it. It seems to work correctly without it. I'll remove this.

File: test/e2e/dra/dra.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:836]: same here. will remove. Thanks for the suggestion!

File: test/e2e/dra/dra.go (hunk 5 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:817]: done

File: test/e2e/dra/dra.go (hunk 3 above)
Comment (pohly) [reply test/e2e/dra/dra.go:833]: Add `.Get` to the first parameter of `GetObject`:

```
gomega.Eventually(ctx, framework.GetObject(b.f.ClientSet.ResourceV1alpha2().ResourceClaims(b.f.Namespace.Name).Get, claim.Name, metav1.GetOptions{}).		 WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", gomega.BeNil()))
```

File: test/e2e/dra/dra.go (hunk 4 above)
Comment (pohly) [reply test/e2e/dra/dra.go:783]: Not sure whether I agree with this rationale. It has a few downsides (some duplicated setup source code lines, full test name.

What is the the full test name?

Comment (pohly) [reply test/e2e/dra/dra.go:783]: Let me be more explicit "DRA: handling non graceful node shutdown cluster must deallocate on non graceful node shutdown" just doesn't look right.

File: test/e2e/dra/dra.go (hunk 2 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:832]: Without this test takes much longer. I've commented in the PR description about it. Now I've added a comment to the test code.

File: test/e2e/dra/dra.go (hunk 3 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go]: done, thanks for the suggestion!

File: test/e2e/dra/dra.go (hunk 2 above)
Comment (pohly) [reply test/e2e/dra/dra.go:830]: I wasn't suggesting to remove `framework.RunCmd("docker", "start", nodeName)`, just to put it into a `ginkgo.DeferCleanup`. Why is that slower? It shouldn't be.

Comment (bart0sh) [reply test/e2e/dra/dra.go:830]: `ginkgo.DeferCleanup(framework.RunCmd, "docker", "start", nodeName)` is in the code from the very beginning.
However, without explicitly calling `docker start` at the end of the test, the test takes a lot more time.

File: test/e2e/dra/dra.go [hunk 6]
```diff
@@ -773,6 +775,54 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
...
+	// This test covers aspects of non graceful node shutdown by DRA controller
+	// More details about this can be found in the KEP:
+	// https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown
+	ginkgo.Context("cluster", func() {
+		nodes := NewNodes(f, 2, 8)
+		driver := NewDriver(f, nodes, networkResources)
+		b := newBuilder(f, driver)
+
+		// NOTE: this test depends on kind. It will only work with kind cluster as it shuts down one of the
+		// nodes by running `docker stop <node name>`, which is very kind-specific.
```
Comment (aojea) [inline test/e2e/dra/dra.go:788]: this should not be inside the e2e framework, we should not start mixing deployment and testing

Comment (aojea) [reply test/e2e/dra/dra.go:788]: oh, mybad, sorry, is an independent folder, so sorry

File: test/e2e/dra/dra.go [hunk 7]
```diff
@@ -773,6 +775,58 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation]", fu
 		multipleDriversContext("using only drapbv1alpha3", false, true)
 		multipleDriversContext("using both drapbv1alpha2 and drapbv1alpha3", true, true)
 	})
+
+	// This test covers aspects of non graceful node shutdown by DRA controller
+	// More details about this can be found in the KEP:
+	// https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown
+	ginkgo.Context("cluster", func() {
```
Comment (pohly) [inline test/e2e/dra/dra.go:782]: The "cluster" context itself isn't about non-graceful shutdown. This comment belongs in front of the `ginkgo.It` with the test.

Regarding context: can you put the `It` under 
```
ginkgo.Context("multiple nodes", func() {
		nodes := NewNodes(f, 2, 8)
		ginkgo.Context("with network-attached resources", func() {
			driver := NewDriver(f, nodes, networkResources)
			b := newBuilder(f, driver)

                        ginkgo.It(...
```

There's no need for a new context. The advantage is that tests that use a similar setup are also grouped together and there's less code duplication.

Comment (bart0sh) [reply test/e2e/dra/dra.go]: done, please review again

**Review by pohly — APPROVED** [review]
/lgtm
/approve
