### PR TITLE
Charges quota only for initialized objects

### LINKED ISSUE #51842: Quota replenishment controller doesn't handle uninitialized objects
The quota is charged when an object is created, no matter if it's initialized or not. It has two problems:

* The quota replenish controller doesn't list/watch uninitialized objects, so it misses the deletion of uninitialized objects and leaks quota.

* The quota controller does periodic resync to recalculate the quota usage. It doesn't see the uninitialized objects, and will wrongly replenish the quota for yet-to-initialize objects.

https://github.com/kubernetes/kubernetes/pull/51749 makes most quota to be charged after the objects are initialized. But the object count quota is still (and ought to be) charged when an object is created, so it still suffers the above problems.

### PR DESCRIPTION
**Pull request by caesarxuchao**
Partially fix https://github.com/kubernetes/kubernetes/issues/51842.

Based on https://github.com/kubernetes/kubernetes/pull/51733/files. Only the commit "Don't charge quota when creating/updating an uninitialized object" is new.

The old plan was to charge quota for each update of uninitialized object. This PR makes the quota admission only charges the update that removes the last pending initializer. Because
* https://github.com/kubernetes/kubernetes/pull/51247, which lets sharedInformer see uninitialized objects, is not making the code freeze deadline. Hence, the quota replenishing controller won't capture deletion of uninitialized objects. We will leak quota if we charge quota for uninitialized objects.
* @lavalamp @erictune pointed out calculating/reserving quota is expensive, we should avoid doing it for every initializer update.
* My original argument was that quota admission should fail early so that user can easily figure out which initializer causes the quota outage. @lavalamp @erictune convinced me that user could easily figure the culprit if they watch the initialization process.

The only exception is the object count quota, which is charged whenever the object is created. This is to prevent attack from bypassing the object count quota to create too many uninitialized objects.

### CODE REVIEW

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 1]
```diff
@@ -49,8 +50,45 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
+		return false, err
+	}
+	initializers := newAccessor.GetInitializers()
+	if initializers == nil || (len(initializers.Pending) == 0 && initializers.Result == nil) {
+		return true, nil
+	}
+	return false, nil
+}
+
+// IsObjUninitialized returns if the new object still have pending initializers.
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/util/initializer.go]: Comment doesn't match function name.

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 2]
```diff
@@ -49,8 +50,45 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
-	if accessor.GetInitializers() == nil {
+	initializers := accessor.GetInitializers()
+	if initializers == nil || (len(initializers.Pending) == 0 && initializers.Result == nil) {
 		return false, nil
 	}
 	return true, nil
 }
+
+// IsFinalInitialization returns if the operation removes all pending initializers.
+func IsFinalInitialization(a admission.Attributes) (bool, error) {
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/util/initializer.go]: `IsInitializationCompletion` or `CompletesInitialization`

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 3]
```diff
@@ -49,8 +50,45 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
+	if a.GetOperation() != admission.Update {
+		return false, nil
+	}
+	oldObj := a.GetOldObject()
+	oldAccessor, err := meta.Accessor(oldObj)
+	if err != nil {
+		return false, err
+	}
+	if oldAccessor.GetInitializers() == nil {
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/util/initializer.go]: Shouldn't this be the same logic as in the IsObjInitialized method below?

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 4]
```diff
@@ -49,8 +50,45 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
+	if initializers == nil || (len(initializers.Pending) == 0 && initializers.Result == nil) {
+		return true, nil
+	}
+	return false, nil
+}
+
+// IsObjUninitialized returns if the new object still have pending initializers.
+func IsObjInitialized(a admission.Attributes) (bool, error) {
+	newObj := a.GetObject()
+	newAccessor, err := meta.Accessor(newObj)
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/util/initializer.go]: Perhaps this function should take an object, then it could be called on either old or new. And replace multiple lines of code repeating this logic earlier in this file.

File: plugin/pkg/admission/resourcequota/admission.go [hunk 5]
```diff
@@ -126,5 +127,13 @@ func (a *quotaAdmission) Admit(attr admission.Attributes) (err error) {
 	if attr.GetSubresource() != "" {
 		return nil
 	}
+	initialized, err := util.IsObjInitialized(attr)
+	if err != nil {
+		return err
```
Comment (liggitt) [inline plugin/pkg/admission/resourcequota/admission.go]: Object count quota should still apply to uninitialized resources

**Comment by lavalamp** [comment]
Concept seems good, I left a couple comments but didn't do an in-depth review.

**Review by liggitt — COMMENTED** [review]
cc @derekwaynecarr

**Comment by liggitt** [comment]
If admission rejects an initialize API call, what happens? The initializer get the error, not the end user, right, and the uninitialized object hangs?

**Comment by caesarxuchao** [comment]
> If admission rejects an initialize API call, what happens? The initializer get the error, not the end user, right, and the uninitialized object hangs?

The initializer controller should fill the error at metadata.initializers.result and update the object again. APIserver will admit the update and then delete the object. APIserver will return the error to the end user in a Status.

File: plugin/pkg/admission/resourcequota/admission.go (hunk 5 above)
Comment (lavalamp) [reply plugin/pkg/admission/resourcequota/admission.go]: Yeah, it is an exception.

Comment (lavalamp) [reply plugin/pkg/admission/resourcequota/admission.go]: Maybe quota needs to be in two buckets, at POST time and at initialization completion time.

**Comment by lavalamp** [comment]
> The initializer controller should fill the error at metadata.initializers.result and update the object again. APIserver will admit the update and then delete the object. ...

That's the most obvious thing to do, but it does add a hop. In the future we could let initializers opt-in to apiserver auto-canceling uninitialized objects when an update request on it will be rejected?

Actually it's alpha right now-- can we think of examples where initializers wouldn't want this behavior?

**Comment by liggitt** [comment]
> can we think of examples where initializers wouldn't want this behavior?

None I'd want to encourage. I also wouldn't want to depend on every initializer to remember to do that in order to correctly surface the actual error to the end user and not hang the create.

**Comment by caesarxuchao** [comment]
Maybe the initializer controller will want to retry? I think it's reasonable to request initializer controller to do error handling.

**Comment by liggitt** [comment]
> Maybe the initializer controller will want to retry? I think it's reasonable to request initializer controller to do error handling.

Retries within retries get pretty crazy. I'd really like initialization to be a single shot update for each. If retry is desired it can (and maybe should?) be driven by the original create request. 

Requires more thought… I'm thinking of admission/validation failures, not of conflict or other types of errors.

It also is preexisting to this PR and doesn't block it, it just occurred to me so I wanted to ask

File: plugin/pkg/admission/resourcequota/admission.go (hunk 5 above)
Comment (derekwaynecarr) [reply plugin/pkg/admission/resourcequota/admission.go]: agree with @liggitt , object count quotas need to apply to uninitialized resources.  we are not setup to to support that easily today, and quota will need some refactoring.

i think we should do the following in 1.9

* adding generic object count quota 
* validation performed prior to quota charges

and gate graduation of initializers pending above completion?

Comment (caesarxuchao) [reply plugin/pkg/admission/resourcequota/admission.go]: Hmm, who's going to replenish the object count if the object is deleted before initialized? The replenish controller won't see the deletion of uninitialized objects.

**Comment by caesarxuchao** [comment]
Addressed @lavalamp's comments.

Charged the object count quota when the object is created, no matter if it is initialized. However, this means we will still have the object count quota leak when an uninitialized object is deleted. This is better than the current state, where all quotas suffer from the leak.

File: plugin/pkg/admission/resourcequota/admission.go [hunk 6]
```diff
@@ -126,5 +127,19 @@ func (a *quotaAdmission) Admit(attr admission.Attributes) (err error) {
...
+	}
+	initialized, err := util.IsObjectInitialized(attr.GetObject())
+	if err != nil {
+		return err
+	}
+	// Object count quota should be charged when the object is created, no
+	// matter if the object is initialized or not.
+	// Other quotas should be charged after the object is initialized
```
Comment (liggitt) [inline plugin/pkg/admission/resourcequota/admission.go]: this code doesn't seem to match this comment

File: pkg/quota/evaluator/core/persistent_volume_claims.go [hunk 7]
```diff
@@ -188,6 +193,11 @@ func (p *pvcEvaluator) Usage(item runtime.Object) (api.ResourceList, error) {
 	if err != nil {
 		return result, err
 	}
+	if pvc.Initializers != nil {
```
Comment (liggitt) [inline pkg/quota/evaluator/core/persistent_volume_claims.go]: shouldn't these look more like moving line 204 here, and returning early if uninitialized?

```
result[api.ResourcePersistentVolumeClaims] = resource.MustParse("1")

// if uninitialized, don't compute usage based on any content yet
if pvc.Initializers != nil {
  return result, nil
}
```

also, in other places, you check `pvc.Initializers != nil && len(pvc.Initializers.Pending) == 0`... which is correct?

File: plugin/pkg/admission/resourcequota/admission.go (hunk 6 above)
Comment (liggitt) [reply plugin/pkg/admission/resourcequota/admission.go]: it seems like we should continue to call the evaluator, not assume initialization is the only aspect being considered by it and short-circuit here

Comment (caesarxuchao) [reply plugin/pkg/admission/resourcequota/admission.go]: The plugin used to care about CREATE and UPDATE. Now I make it ignore the intermediate updates during initialization. I think it's safe.

The code will just work if I remove the short-circuit here, but that causes many unnecessary calls to the evaluators. Can we keep the short-circuit until we have a use case?

File: pkg/quota/evaluator/core/persistent_volume_claims.go (hunk 7 above)
Comment (caesarxuchao) [reply pkg/quota/evaluator/core/persistent_volume_claims.go]: The complex one is correct. I centralized the logic into a utility function in apimachinery.

File: staging/src/k8s.io/apimachinery/pkg/util/initialization/initialization.go [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+package initialization
+
+import (
+	"k8s.io/apimachinery/pkg/api/meta"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/runtime"
+)
+
+// IsInitialized returns if the initializers indicates means initialized.
+func IsInitialized(initializers *metav1.Initializers) bool {
```
Comment (caesarxuchao) [inline staging/src/k8s.io/apimachinery/pkg/util/initialization/initialization.go]: Utility function to test if object is initialized. Useful if the object in question is not persisted yet.

**Comment by lavalamp** [comment]
I think quota has a bunch of problems that we can't address in a single PR. I filed #51820.

**Comment by lavalamp** [comment]
...and #51821 for the other discussion point in this PR.

**Comment by caesarxuchao** [comment]
@lavalamp do you want this PR as an intermediate fix? It does fix the leak of most quotas, and reduces the number operations handled by the quota system.

File: pkg/quota/evaluator/core/pods.go [hunk 9]
```diff
@@ -254,6 +255,13 @@ func PodUsageFunc(obj runtime.Object) (api.ResourceList, error) {
 	if err != nil {
 		return api.ResourceList{}, err
 	}
+	// Only charge pod count for uninitialized pod.
+	if !initialization.IsInitialized(pod.Initializers) {
+		result := api.ResourceList{}
+		result[api.ResourcePods] = resource.MustParse("1")
```
Comment (liggitt) [inline pkg/quota/evaluator/core/pods.go]: this changes behavior by moving object count above the `if !QuotaPod` check

Comment (liggitt) [reply pkg/quota/evaluator/core/pods.go]: I'd expect this done unconditionally after the `!QuotaPod` check, then an early return `if !initialization.IsInitialized`, just like PV

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 10]
```diff
@@ -49,8 +50,45 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
 	}
-	if accessor.GetInitializers() == nil {
+	if initialization.IsInitialized(accessor.GetInitializers()) {
 		return false, nil
 	}
 	return true, nil
 }
+
+// IsInitializationCompletion returns if the operation removes all pending initializers.
+func IsInitializationCompletion(a admission.Attributes) (bool, error) {
```
Comment (liggitt) [inline pkg/kubeapiserver/admission/util/initializer.go]: if the initializer feature is disabled, this should always return false, right?

Comment (liggitt) [reply pkg/kubeapiserver/admission/util/initializer.go]: similar short-circuits for the other helpers, though the package dependency for that is pretty bad, I guess :-/

File: pkg/quota/evaluator/core/persistent_volume_claims.go [hunk 11]
```diff
@@ -144,16 +145,21 @@ func (p *pvcEvaluator) GroupKind() schema.GroupKind {
 // Handles returns true if the evaluator should handle the specified operation.
 func (p *pvcEvaluator) Handles(a admission.Attributes) bool {
 	op := a.GetOperation()
-	if op == admission.Create {
+	initialized, err := initialization.IsObjectInitialized(a.GetObject())
+	if err != nil {
+		// fail closed, will try to give an evaluation.
+		return true
+	}
+	if op == admission.Create && initialized {
```
Comment (liggitt) [inline pkg/quota/evaluator/core/persistent_volume_claims.go]: unconditionally handle create

File: pkg/quota/evaluator/core/pods.go (hunk 9 above)
Comment (caesarxuchao) [reply pkg/quota/evaluator/core/pods.go]: Good catch. Though probably `QuotaPod` is never effective. This evaluator [used](https://github.com/kubernetes/kubernetes/blob/v1.7.3/pkg/quota/evaluator/core/pods.go#L136) to only handle `Create`, and no one can create `Pod` with Phase=Succeeded || Phase == Failed

File: plugin/pkg/admission/resourcequota/admission.go (hunk 5 above)
Comment (liggitt) [reply plugin/pkg/admission/resourcequota/admission.go]: I think we should drop this and let the evaluator Handles() methods decide what to handle... object count ones will stay with just Create, ones that inspect can do count on create and usage on the Uninitialized->Initialized transition

File: pkg/quota/evaluator/core/persistent_volume_claims.go (hunk 11 above)
Comment (liggitt) [reply pkg/quota/evaluator/core/persistent_volume_claims.go]: also pvc uses object count, so we'd want to handle an uninitialized create

File: plugin/pkg/admission/resourcequota/admission.go (hunk 5 above)
Comment (liggitt) [reply plugin/pkg/admission/resourcequota/admission.go]: > Hmm, who's going to replenish the object count if the object is deleted before initialized? The replenish controller won't see the deletion of uninitialized objects.

eventually, resync will correct it, but that should go on the list of things to improve in the interaction between quota and initialization

File: pkg/kubeapiserver/admission/util/initializer.go (hunk 10 above)
Comment (caesarxuchao) [reply pkg/kubeapiserver/admission/util/initializer.go]: The old object is persisted. If the feature gate is off, old object will always be initialized, so all these helpers (IsUpdatingInitializedObject, IsUpdatingUninitializedObject, IsInitializationCompletion) will return false. No need to protect them with feature gate.

File: pkg/quota/evaluator/core/persistent_volume_claims.go (hunk 11 above)
Comment (caesarxuchao) [reply pkg/quota/evaluator/core/persistent_volume_claims.go]: I updated it to be just like the pod evaluator.

File: pkg/quota/evaluator/core/pods.go (hunk 9 above)
Comment (caesarxuchao) [reply pkg/quota/evaluator/core/pods.go]: > this changes behavior by moving object count above the if !QuotaPod check

Done. Moved to after `!QuotaPod`.

> I'd expect this done unconditionally after the !QuotaPod check, then an early return if !initialization.IsInitialized, just like PV

The pod evaluator summarizes all containers's request/limits and then invokes a [helper function](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/pods.go#L277) to calculate the quota usage. Following the pvc pattern will require more change, so I keep it as is.

File: plugin/pkg/admission/resourcequota/admission.go (hunk 5 above)
Comment (caesarxuchao) [reply plugin/pkg/admission/resourcequota/admission.go]: Eh, the resync needs a [List](https://github.com/kubernetes/kubernetes/blob/master/pkg/quota/evaluator/core/pods.go#L77-L79), which don't see uninitialized objects, so it will ignore the object counts for the yet-to-initialize objects.

File: pkg/quota/evaluator/core/pods.go [hunk 12]
```diff
@@ -255,17 +257,19 @@ func PodUsageFunc(obj runtime.Object) (api.ResourceList, error) {
...
-		result[api.ResourcePods] = resource.MustParse("1")
-		return result, nil
-	}
 
 	// by convention, we do not quota pods that have reached an end-of-life state
 	if !QuotaPod(pod) {
 		return api.ResourceList{}, nil
 	}
+	// Only charge pod count for uninitialized pod.
+	if utilfeature.DefaultFeatureGate.Enabled(features.Initializers) {
```
Comment (caesarxuchao) [inline pkg/quota/evaluator/core/pods.go]: Perhaps the BeforeUpdate/BeforeCreate should fail the request if feature gate is disabled and initializers are set, instead of repairing the request. Then we don't have to deal with feature gate here. Admission is called before BeforeUpdate/BeforeCreate, it's hard to reasoning the correct admission behavior if the object might get changed later.

Comment (liggitt) [reply pkg/quota/evaluator/core/pods.go]: Feature gate off should behave as if those fields don't exist. We could drop pre-admission, I suppose

**Comment by liggitt** [comment]
This looks a lot better, thanks
/lgtm

File: pkg/kubeapiserver/admission/util/initializer.go [hunk 13]
```diff
@@ -49,8 +50,29 @@ func IsUpdatingUninitializedObject(a admission.Attributes) (bool, error) {
...
 		return false, err
 	}
-	if accessor.GetInitializers() == nil {
+	if initialization.IsInitialized(accessor.GetInitializers()) {
 		return false, nil
 	}
 	return true, nil
 }
+
+// IsInitializationCompletion returns if the operation removes all pending initializers.
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/util/initializer.go]: returns true if

File: pkg/quota/evaluator/core/persistent_volume_claims.go [hunk 14]
```diff
@@ -147,13 +150,12 @@ func (p *pvcEvaluator) Handles(a admission.Attributes) bool {
 	if op == admission.Create {
 		return true
 	}
-	updateUninitialized, err := util.IsUpdatingUninitializedObject(a)
+	initializationCompletion, err := util.IsInitializationCompletion(a)
```
Comment (lavalamp) [inline pkg/quota/evaluator/core/persistent_volume_claims.go]: Should the below error not be handled or logged in some way?

File: pkg/kubeapiserver/admission/util/initializer.go (hunk 13 above)
Comment (caesarxuchao) [reply pkg/kubeapiserver/admission/util/initializer.go]: The original writing is also valid?

File: pkg/quota/evaluator/core/persistent_volume_claims.go (hunk 14 above)
Comment (caesarxuchao) [reply pkg/quota/evaluator/core/persistent_volume_claims.go]: How about runtime.HandleError()? Is it ok to invoke it from pkg/quota?

File: pkg/kubeapiserver/admission/util/initializer.go (hunk 13 above)
Comment (lavalamp) [reply pkg/kubeapiserver/admission/util/initializer.go]: as written, it sounds like it never returns otherwise.

File: pkg/quota/evaluator/core/persistent_volume_claims.go (hunk 14 above)
Comment (lavalamp) [reply pkg/quota/evaluator/core/persistent_volume_claims.go]: sure, and I think so. There is another instance below.

**Comment by caesarxuchao** [comment]
Addressed Daniel's comments. Adding back the lgtm.

File: pkg/quota/evaluator/core/persistent_volume_claims.go [hunk 15]
```diff
@@ -149,17 +152,26 @@ func (p *pvcEvaluator) Handles(a admission.Attributes) bool {
 	if op == admission.Create {
 		return true
 	}
-	if op == admission.Update && utilfeature.DefaultFeatureGate.Enabled(features.ExpandPersistentVolumes) {
-		return true
+	if op == admission.Update && utilfeature.DefaultFeatureGate.Enabled(k8sfeatures.ExpandPersistentVolumes) {
```
Comment (caesarxuchao) [inline pkg/quota/evaluator/core/persistent_volume_claims.go]: This "if" block is introduced after rebase. It makes the pvc evaluator handle updates if the "ExpandPersistentVolumes" feature gate is enabled. During the rebase, I made it only handle the update if the pvc is initialized after the update.
