### PR TITLE
Fail fast when waiting for job conditions in e2e tests

### LINKED ISSUE #127295: Cleanup Job e2e helper functions (fail fast wait functions and don't use deprecated functions)
I would like to cleanup / improve the code in `test/e2e/framework/job/wait.go`. In particular:
1. `WaitForJobComplete` and `WaitForJobFailed` can fail fast - e.g. we wait for JobComplete condition, if we observe JobFailed we can fail immediately, the Job is not expected to do that. It is wasteful, especially when running the tests locally, to wait 15min if the Job fails after a couple of seconds.

2. `wait.PollImmediate` used in `WaitForJobFailed` is now deprecated, use `PollUntilContextTimeout`

I think these could be two PRs, but I combine them in a single issue as closely related in a theme.

### PR DESCRIPTION
**Pull request by kaisoz**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR makes both `WaitForJobComplete` and `WaitForJobFailed` functions to fail fast in case any abnormal situation is observed while waiting (e.g: job fails while `WaitForJobComplete`). 

#### Which issue(s) this PR fixes:
Fixes #127295

#### Special notes for your reviewer:

I changed the waiting functions to `gomega.Eventually` as suggested in this [issue comment](https://github.com/kubernetes/kubernetes/issues/127295#issuecomment-2345187828). 

In the preliminary implementation, I used the `HandleRetry` and `MakeMatcher` functions because I've seen them applied in other tests and `HandleRetry` is known for handling transient API errors. However, following a discussion with the reviewer, we concluded that this approach made the code too verbose. Currently, there's no need for such functionality, as we haven't experienced any end-to-end test flakes because of this issue.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/framework/job/wait.go [hunk 1]
```diff
@@ -161,6 +191,16 @@ func isJobFailed(j *batchv1.Job) bool {
 	return false
 }
 
+func isJobCompleted(j *batchv1.Job) bool {
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:194]: I would suggest to commonize this function with `isJobFailed` as `hasConditionTrue` (or named alike). You could extract that change to separate commit in the PR.

File: test/e2e/framework/job/wait.go [hunk 2]
```diff
@@ -118,38 +134,52 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
...
 			}
 		}
-		return false, nil
-	})
-	if err != nil {
-		return fmt.Errorf("waiting for Job %q to have the condition %q with reason: %v: %w", jobName, cType, reason, err)
-	}
-	return nil
+		return func() string {
+			return fmt.Sprintf("waiting for Job %q to have the condition %q with reason: %v", jobName, cType, reason)
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:180]: also include namespace in the messages (for example using klog.KRef). I remember often doing grep by the namespace when trying to understand some failures. (same comment for other messages)

File: test/e2e/framework/job/wait.go [hunk 3]
```diff
@@ -118,38 +134,52 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
...
+		if isJobCompleted(j) {
+			return func() string {
+				return fmt.Sprintf("job %q completed while waiting for its failure", jobName)
+			}, nil
+		}
+
+		if isJobFailed(j) {
+			return nil, nil
+		}
+
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:154]: nit (sorry for nitpicking), but I don't see a need for the empty lines here - they are sometimes useful for readability in large functions, but I think in case of the functions in this diff they don't improve that much, and it is not clear why some places have and some don't have an empty line.

File: test/e2e/framework/job/wait.go [hunk 4]
```diff
@@ -118,38 +134,52 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
 
 // WaitForJobFailed uses c to wait for the Job jobName in namespace ns to fail
 func WaitForJobFailed(c clientset.Interface, ns, jobName string) error {
-	return wait.PollImmediate(framework.Poll, JobTimeout, func() (bool, error) {
-		curr, err := c.BatchV1().Jobs(ns).Get(context.TODO(), jobName, metav1.GetOptions{})
+	return framework.Gomega().Eventually(context.TODO(), framework.HandleRetry(func(ctx context.Context) (*batchv1.Job, error) {
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:137]: Try to avoid TODO context. You could extract that change to a separate commit in the PR.

File: test/e2e/framework/job/wait.go [hunk 5]
```diff
@@ -82,14 +82,30 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
 // both conformance CI jobs with GA-only features and e2e CI jobs with all default-enabled features.
 // So, we need to skip "Complete" condition reason verifications in the e2e conformance test cases.
 func WaitForJobComplete(ctx context.Context, c clientset.Interface, ns, jobName string, reason *string, completions int32) error {
-	if err := wait.PollUntilContextTimeout(ctx, framework.Poll, JobTimeout, false, func(ctx context.Context) (bool, error) {
-		curr, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
+	err := framework.Gomega().Eventually(ctx, framework.HandleRetry(func(ctx context.Context) (*batchv1.Job, error) {
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
 		if err != nil {
-			return false, err
+			return nil, fmt.Errorf("getting the job in in namespace %s: %w", ns, err)
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:88]:
```suggestion
			return nil, fmt.Errorf("getting the job in namespace %s: %w", ns, err)
```
nit
also, use namespace/name consistently in the messages

File: test/e2e/framework/job/wait.go [hunk 6]
```diff
@@ -82,14 +82,30 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
 // both conformance CI jobs with GA-only features and e2e CI jobs with all default-enabled features.
 // So, we need to skip "Complete" condition reason verifications in the e2e conformance test cases.
 func WaitForJobComplete(ctx context.Context, c clientset.Interface, ns, jobName string, reason *string, completions int32) error {
-	if err := wait.PollUntilContextTimeout(ctx, framework.Poll, JobTimeout, false, func(ctx context.Context) (bool, error) {
-		curr, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
+	err := framework.Gomega().Eventually(ctx, framework.HandleRetry(func(ctx context.Context) (*batchv1.Job, error) {
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:85]: I'm not very familiar with `HandleRetry` and `MakeMatcher`, I suppose they are used to fail fast?

I'm wondering if there is a less-code alternative: await for the function used in eventually to return the number of succeeded pods, and use gomega to check `Should(gomega.Equal(completions))`. Now, if the opposite condition happens, then use framework.Fail to fail fast?

File: test/e2e/framework/job/wait.go (hunk 3 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go:154]: sure! no problem, all remove them 😊

File: test/e2e/framework/job/wait.go (hunk 4 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: Done in a separate commit as suggested 👍🏻

File: test/e2e/framework/job/wait.go (hunk 1 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: Done! I've created a `hasAnyConditionTrue` function which replaces all the `isJob...` functions since they were duplicating code. Let me know if this suits you 😊

Comment (mimowo) [reply test/e2e/framework/job/wait.go]: I liked the simplicity of invoking the checks before: `hasAnyConditionTrue(curr, []batchv1.JobConditionType{ batchv1.JobFailed})` vs `isJobFailed` :) 

How about keeping `isJobFailed`, `isJobComplete`, and `isJobFinished = isJobFailed || isJobComplete`? Then underneath have a helper function `isConditionTrue` which is used in `isJobFailed` and `isJobComplete`?

File: test/e2e/framework/job/wait.go [hunk 7]
```diff
@@ -178,16 +195,28 @@ func WaitForJobFinishWithTimeout(ctx context.Context, c clientset.Interface, ns,
...
-		if (c.Type == batchv1.JobComplete || c.Type == batchv1.JobFailed) && c.Status == v1.ConditionTrue {
+		if c.Type == condition && c.Status == v1.ConditionTrue {
 			return true
 		}
 	}
 
 	return false
 }
 
+func isJobFinished(j *batchv1.Job) bool {
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:216]: nit: move the function above  isJobFailed so that the functions chains follow the pattern in file

File: test/e2e/framework/job/wait.go (hunk 6 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: I did research alternative implementation and came up with a new proposal based on your suggestions which is indeed less verbose. PTAL and let me know your thoughts 😊

File: test/e2e/framework/job/wait.go [hunk 8]
```diff
@@ -117,48 +122,38 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
...
+			framework.Failf("getting the job %q: %v", klog.KRef(jobName, ns), err)
+		}
+		if isJobCompleted(job) {
+			framework.Failf("job %q completed while waiting for its failure", jobName)
 		}
 
-		return isJobFailed(curr), nil
-	})
+		return isJobFailed(job)
+	}).WithTimeout(JobTimeout).WithPolling(framework.Poll).Should(gomega.BeTrueBecause("timeout waiting for job %v/%v to fail", ns, jobName))
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:136]: Make the logging  consistent as currently there are 3 versions in the green code:
- "job %q completed while waiting for its failure", jobName
- getting the job %q: %v", klog.KRef(jobName, ns)
- "timeout waiting for job %v/%v to fail", ns, jobName)

Either use %q for klog.KRef(jobName, ns)), or %s/%s for ns/jobName.

File: test/e2e/framework/job/wait.go [hunk 9]
```diff
@@ -82,14 +83,17 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
...
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
 		if err != nil {
-			return false, err
+			framework.Failf("getting the job %v/%v: %v", ns, jobName, err)
 		}
-		return curr.Status.Succeeded == completions, nil
-	}); err != nil {
-		return nil
+		if isJobFailed(job) {
+			framework.Failf("job %v/%v failed while waiting for its completion", ns, jobName)
```
Comment (pohly) [inline test/e2e/framework/job/wait.go:92]: /lgtm cancel

You cannot use assertions inside a `Eventually` callback: `Eventually` is from gomega and doesn't know how to deal with the panic raised by ginkgo.

For transient errors that should be retried, return that error with wrapping as a second return value.

For permanent errors, use `gomega.StopPolling(...).Now()`.

File: test/e2e/framework/job/wait.go [hunk 10]
```diff
@@ -82,14 +83,17 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
 // both conformance CI jobs with GA-only features and e2e CI jobs with all default-enabled features.
 // So, we need to skip "Complete" condition reason verifications in the e2e conformance test cases.
 func WaitForJobComplete(ctx context.Context, c clientset.Interface, ns, jobName string, reason *string, completions int32) error {
-	if err := wait.PollUntilContextTimeout(ctx, framework.Poll, JobTimeout, false, func(ctx context.Context) (bool, error) {
-		curr, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
+	if err := framework.Gomega().Eventually(ctx, func() int32 {
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
 		if err != nil {
```
[the remark this answers is not in the document]
Comment (atiratree) [reply test/e2e/framework/job/wait.go:88]: I suppose, the best would be to allow for only a couple of failures. @pohly thoughts?

[the remark this answers is not in the document]
Comment (pohly) [reply test/e2e/framework/job/wait.go:88]: That's exactly the distinction that the test author needs to make: is an error retryable or permanent.

The `framework.HandleRetry` handler has some logic for API server errors. If you don't want to use it, then better treat all such errors as retryable and only use `StopPolling` for conditions which are definitely recognized as "this will definitely not change anymore".

**Review by hashim21223445 — APPROVED** [review]

File: test/e2e/framework/job/wait.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply test/e2e/framework/job/wait.go:88]: +1 on retrying the API failures. I think the previous approach would fail on API server errors, so I thought it could be a follow up PR. OTOH it is so closely related that we may as well use `HandleRetry` in this PR.

[the remark this answers is not in the document]
Comment (kaisoz) [reply test/e2e/framework/job/wait.go:88]: Makes sense, so in this case it makes sense to go back to the previous implementation (which can maybe be refactored to be less verbose) and use `HandleRetry`. WDYT?

[the remark this answers is not in the document]
Comment (mimowo) [reply test/e2e/framework/job/wait.go:88]: sgtm, let's try to use HandleRetry

[the remark this answers is not in the document]
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: @mimowo @pohly I've implemented the solution using `HandleRetry`. Now the `get` function returns a pointer to the job instead of a bool. In that way, in case of a non-transient error, `HandleRetry` [produces a meaningful message](https://github.com/kubernetes/kubernetes/blob/7ab8a2b92f675bb81715bfca7085b0c4d0a284c9/test/e2e/framework/get.go#L88) apart from stop polling. I've tested all these situations (fail fast, non-transient errors.. etc) and seems to work well.

P.S: @pohly out of curiosity, I've tested the same situations with the previous implementation and also seemed to work well 🤷🏻

File: test/e2e/framework/job/wait.go [hunk 11]
```diff
@@ -82,14 +83,33 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
...
+	get := func(ctx context.Context) (*batchv1.Job, error) {
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
+		if job != nil {
+			if isJobFailed(job) {
+				return nil, fmt.Errorf("job %q failed while waiting for its completion", klog.KObj(job))
+			}
+			return job, nil
+		}
+		// This function is called by HandleRetry, which will retry
+		// on transient API errors or stop polling in the case of other errors.
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:95]: Nit: move the comment just above declaring the `get` function.

File: test/e2e/framework/job/wait.go [hunk 12]
```diff
@@ -117,48 +137,55 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
...
+			if isJobCompleted(job) {
+				return nil, fmt.Errorf("job %q completed while waiting for its failure", klog.KObj(job))
+			}
+			return job, nil
 		}
-
-		return isJobFailed(curr), nil
-	})
+		// This function is called by HandleRetry, which will retry
+		// on transient API errors or stop polling in the case of other errors.
```
Comment (mimowo) [inline test/e2e/framework/job/wait.go:150]: nit: as in the other case

**Review by mimowo — COMMENTED** [review]
LGTM, just minor nits

**Review by hashim21223445 — APPROVED** [review]

File: test/e2e/framework/job/wait.go [hunk 13]
```diff
@@ -82,14 +83,33 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
...
+	// on transient API errors or stop polling in the case of other errors.
+	get := func(ctx context.Context) (*batchv1.Job, error) {
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
+		if job != nil {
+			if isJobFailed(job) {
+				return nil, fmt.Errorf("job %q failed while waiting for its completion", klog.KObj(job))
+			}
+			return job, nil
+		}
+		return nil, err
```
Comment (atiratree) [inline test/e2e/framework/job/wait.go:96]: It is a better practice to check for an error first. Also, are we sure the job is nil when we get the error?

Comment (kaisoz) [reply test/e2e/framework/job/wait.go:96]: yeah, you're right 🤦🏻 . Let me fix that

Comment (atiratree) [reply test/e2e/framework/job/wait.go]: thx!

**Comment by kaisoz** [comment]
/assign @pohly 

PTAL whenever you have time 😊 . Thanks!

File: test/e2e/framework/job/wait.go [hunk 14]
```diff
@@ -82,14 +83,33 @@ func waitForJobPodsInPhase(ctx context.Context, c clientset.Interface, ns, jobNa
...
+	// This function is called by HandleRetry, which will retry
+	// on transient API errors or stop polling in the case of other errors.
+	get := func(ctx context.Context) (*batchv1.Job, error) {
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
 		if err != nil {
-			return false, err
+			return nil, err
+		}
+		if isJobFailed(job) {
+			return nil, fmt.Errorf("job %q failed while waiting for its completion", klog.KObj(job))
```
Comment (pohly) [inline test/e2e/framework/job/wait.go:94]: Can you use gomega.StopTrying here? That makes the intent clearer. It's also possible to attach the job, which will cause it to be dumped as YAML when rendering the failure.

```suggestion
			return nil, gomega.StopTrying("job failed while waiting for its completion").Attach("job", job))
```

Returning a custom error works because https://github.com/kubernetes/kubernetes/blob/1f9d2577da68290c0466c1404bbff6100e1e303a/test/e2e/framework/get.go#L94-L111 treats unknown errors as final, but IMHO `StopTrying` is better.

File: test/e2e/framework/job/wait.go [hunk 15]
```diff
@@ -117,48 +137,55 @@ func WaitForJobSuspend(ctx context.Context, c clientset.Interface, ns, jobName s
...
+		job, err := c.BatchV1().Jobs(ns).Get(ctx, jobName, metav1.GetOptions{})
 		if err != nil {
-			return false, err
+			return nil, err
 		}
-
-		return isJobFailed(curr), nil
-	})
+		if isJobCompleted(job) {
+			return nil, fmt.Errorf("job %q completed while waiting for its failure", klog.KObj(job))
```
Comment (pohly) [inline test/e2e/framework/job/wait.go:149]: `StopTrying`?

**Review by pohly — COMMENTED** [review]
One suggestion for a possible improvement, otherwise it looks good.

File: test/e2e/framework/job/wait.go (hunk 14 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: Nice! I like it. Done!

File: test/e2e/framework/job/wait.go (hunk 15 above)
Comment (kaisoz) [reply test/e2e/framework/job/wait.go]: Done!
