### PR TITLE
Use --format='value()' instead of --fields with gcloud compute instances describe

### LINKED ISSUE #25153: gcloud unrecognized arguments --fields
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25054/kubernetes-pull-build-test-e2e-gce/38324/

```
INSTANCE_GROUPS=e2e-gce-master-1-minion-group
NODE_NAMES=e2e-gce-master-1-minion-0pce e2e-gce-master-1-minion-3mfi e2e-gce-master-1-minion-4jgj e2e-gce-master-1-minion-bmu8 e2e-gce-master-1-minion-qirl e2e-gce-master-1-minion-vywd
usage: gcloud compute instances describe  NAME [optional flags]
ERROR: (gcloud.compute.instances.describe) unrecognized arguments:
  --fields
  networkInterfaces[0].accessConfigs[0].natIP
```

### PR DESCRIPTION
**Pull request by ixdy**
Fixes #25153. As an added bonus, we get rid of an `awk` call.

This will probably need to be manually merged. It'll also need to be cherry-picked to release branches.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@dchen1107 I'm not sure it's worth waiting for automated tests before manually merging this, since they aren't going to provide any signal.

**Comment by roberthbailey** [comment]
Assigning to @dchen1107 as build cop.

**Comment by ixdy** [comment]
I would hope that the e2e build would pass (or at least get past cluster startup). Probably good to wait on that at least.

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -341,8 +340,7 @@ function detect-master () {
   KUBE_MASTER=${MASTER_NAME}
   if [[ -z "${KUBE_MASTER_IP-}" ]]; then
     KUBE_MASTER_IP=$(gcloud compute instances describe --project "${PROJECT}" --zone "${ZONE}" \
-      "${MASTER_NAME}" --fields networkInterfaces[0].accessConfigs[0].natIP \
-      --format=text | awk '{ print $2 }')
+      "${MASTER_NAME}" --format='value(networkInterfaces[0].accessConfigs[0].natIP)')
```
Comment (jlowdermilk) [inline cluster/gce/util.sh]: Are you sure we no longer need the `| awk '{ print $2 }' ?`

Comment (ixdy) [inline cluster/gce/util.sh]:
```console
$ gcloud compute instances describe --project kubernetes-jkns-e2e-gce-serial --zone us-central1-f  jenkins-e2e-master --format='value(networkInterfaces[0].accessConfigs[0].natIP)'
8.34.212.150
```

Comment (ixdy) [inline cluster/gce/util.sh]: This is basically the same fix as I did in #24746.

**Comment by freehan** [comment]
I think this has to be hand merged. e2e test will fail without this fix.

**Comment by ixdy** [comment]
e2e cluster started up: https://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/38352/console

Should be good to merge.

**Comment by ixdy** [comment]
Cherrypicks:
* release-1.2: https://github.com/kubernetes/kubernetes/pull/25164
* release-1.1: https://github.com/kubernetes/kubernetes/pull/25165
* release-1.0: https://github.com/kubernetes/kubernetes/pull/25166
