### PR TITLE
Fixed bug in TopologyManager with SingleNUMANode Policy

### LINKED ISSUE #83775: Pods  error out with 'Topology Affinity Error' if resources and limits are not mentioned as part of the pod spec. This is after #83492
**What happened**:

With the latest fix #83697 , which aims to resolve the issue of deploying pods with single-numa-node policy, it seems to have resulted in failure to deploy pods if the pod spec does not have resources and limits constraints. This is resulting in Kube-dns and other pods which do not have resource constraints mentioned fail to deploy due to Topology Affinity Error.
kube-system   kube-dns-b54d5f547-22dks   0/3     Topology Affinity Error   0    

**What you expected to happen**:
Ideally, if there are no resource constraints mentioned we will still need the pod to be deployed. 
We cannot have Kube-dns failing to deploy due to Topology Affinity issue.

**How to reproduce it (as minimally and precisely as possible)**:
With the latest fix, enabling single-numa-node policy, Kube-dns errors out on the node. 
One can just try to deploy simple pod without resource constraints in pod spec. 

**Anything else we need to know?**:
This happens only when policy is single-numa-node. Pods do not fail to deploy for best-case policy. 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.0-alpha.1.338+017842d49deca6-dirty", GitCommit:"017842d49deca68dab3a26b76d5dfd5df15a8113", GitTreeState:"dirty", BuildDate:"2019-10-11T10:39:19Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: 
   Baremetal x86 server with 2 NUMA nodes and 32 cpus.
- OS (e.g: `cat /etc/os-release`): Fedora 28
- Kernel (e.g. `uname -a`): 5.0.13-100.fc28.x86_64

### PR DESCRIPTION
**Pull request by lmdaly**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This patch fixes an issue where best-effort pods were not admitted
to the node if the single-numa-node policy was set.

This was because the Admit policy in single-numa-node policy does
not admit any pod where the hint is anything but single NUMA node. The 'best hint' in this case is {<set bits for num. Numa Nodes on machine>, true}
So on a machine with 2 NUMA nodes the best hint for a best-effort pod is {11,true} as best-effort pods have no Topology preferences.

The single-numa-node policy fails any pod with a not preferred hint OR a hint where > 1 bits are set, thus the above example resulting in termintaed pods with a Topology Affinity Error.

This is a short term fix for the single-numa-node policy, as there will be code refactoring for the 1.17 release.

**Which issue(s) this PR fixes**:

Fixes #83775 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug in the single-numa-policy of the TopologyManager. Previously, best-effort pods would result in a terminated state with a TopologyAffinity error. Now they will run as expected.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/topologymanager/policy_single_numa_node.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ func (p *singleNumaNodePolicy) Name() string {
 }
 
 func (p *singleNumaNodePolicy) CanAdmitPodResult(hint *TopologyHint) lifecycle.PodAdmitResult {
-	if !hint.Preferred || hint.NUMANodeAffinity.Count() > 1 {
+	if !hint.Preferred {
```
Comment (klueska) [inline pkg/kubelet/cm/topologymanager/policy_single_numa_node.go]: I see how this would fix the issue because of the one-off hack we currently have in the `TopologyManager`, i.e. where we intercept hints that have more than one NUMA affinity and force them to `false`.

However, since this is only broken on master, I'm inclined to wait for a proper fix in the form of https://github.com/kubernetes/kubernetes/issues/83478.

What do others think?

**Comment by klueska** [comment]
Let's go ahead and move forward with this change so that master starts working again for the single-numa-node policy.

Once we land https://github.com/kubernetes/kubernetes/pull/81586 this change should be overwritten / superceded.
