### PR TITLE
Fix unit tests for volume ownership

### LINKED ISSUE #130607: [Failing Test] pkg/volume/volume_linux_test.go
### Which jobs are failing?

NONE

### Which tests are failing?

- TestSetVolumeOwnershipOwner/*fsGroup=3000
- TestSetVolumeOwnershipOwner/symlink

### Since when has it been failing?

Since PR #130398 

### Testgrid link

_No response_

### Reason for failure (if possible)

-  volume_linux_test.go:592: for *fsGroup=3000 error verifying permissions with: invalid owner on /tmp/volume_linux_ownership3055383160/file.txt
- volume_linux_test.go:592: for symlink error verifying permissions with: invalid owner on /tmp/volume_linux_ownership3642780172/file_link.txt

### Anything else we need to know?

Two test cases started to fail after PR #130398, not sure if this [line](https://github.com/kubernetes/kubernetes/pull/130398#discussion_r1982400934) is the one causes the issue or not. We may need to revert or fix the test to work regardless of which user runs the test.

Error:
```
{Failed  === RUN   TestSetVolumeOwnershipOwner/*fsGroup=3000
    volume_linux_test.go:592: for *fsGroup=3000 error verifying permissions with: invalid owner on /tmp/volume_linux_ownership3055383160/file.txt
--- FAIL: TestSetVolumeOwnershipOwner/*fsGroup=3000 (0.60s)

=== RUN   TestSetVolumeOwnershipOwner/symlink
    volume_linux_test.go:592: for symlink error verifying permissions with: invalid owner on /tmp/volume_linux_ownership3642780172/file_link.txt
--- FAIL: TestSetVolumeOwnershipOwner/symlink (0.90s)

=== RUN   TestSetVolumeOwnershipOwner
--- FAIL: TestSetVolumeOwnershipOwner (1.51s)
}
```

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by gnufied**
Fixes unit tests for volume ownership

Fixes https://github.com/kubernetes/kubernetes/issues/130607

Ran the tests as root after the fix and everything works:

```
=== RUN   TestSetVolumeOwnershipOwner/symlink
--- PASS: TestSetVolumeOwnershipOwner (0.00s)
    --- PASS: TestSetVolumeOwnershipOwner/fsGroup=nil (0.00s)
    --- PASS: TestSetVolumeOwnershipOwner/*fsGroup=3000 (0.00s)
    --- PASS: TestSetVolumeOwnershipOwner/symlink (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/volume    3.644s
```

### CODE REVIEW

File: pkg/volume/volume_linux_test.go [hunk 1]
```diff
@@ -342,6 +342,11 @@ func TestProgressTracking(t *testing.T) {
 		time.Sleep(permissionSleepDuration)
 		return nil
 	}
+	defer func() {
```
Comment (liggitt) [inline pkg/volume/volume_linux_test.go:345]: can this capture existing values and reset to existing values rather than duplicate the assignments? hard-coding here means if we change the package defaults these will modify values

```go
func TestProgressTracking(t *testing.T) {
  originalFilePermissionChangeFunc = filePermissionChangeFunc
  originalProgressReportDuration = progressReportDuration
  originalFirstEventReportDuration = firstEventReportDuration
  t.Cleanup(func(){
    filePermissionChangeFunc = originalFilePermissionChangeFunc
    progressReportDuration = originalProgressReportDuration
    firstEventReportDuration = originalFirstEventReportDuration
  })
  ...
```

**Comment by liggitt** [comment]
@gnufied were you able to reproduce the failure running the unit test as root, and verify this package passes unit tests as root with this fix?

File: pkg/volume/volume_linux_test.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/volume_linux_test.go]: good idea. fixed.

**Comment by gnufied** [comment]
@liggitt yes, i was able to reproduce the issue when tests were ran as root. And I verified that tests pass now, when ran as root -  https://gist.github.com/gnufied/889012e3bfbe8eac33558ce7449fa8ee

**Comment by liggitt** [comment]
> @liggitt yes, i was able to reproduce the issue when tests were ran as root. And I verified that tests pass now, when ran as root

thanks

cc @pohly @aojea @BenTheElder for visibility to another example of unit tests that passed as non-root and broke as root

We definitely don't want to *require* root to run unit tests, so it's good that our presubmits have to pass as non-root, but a *lot* of the things we're unit testing actually *will* run as root (kubelet, etc), so it makes me slightly anxious that we don't have any visibility to whether the functions being unit tested actually work in the environment they will execute in. Right now we're just depending on downstreams telling us when unit tests break when run as root, which is ... not great.

**Comment by BenTheElder** [comment]
I think "kubelet interacts with the OS" is a great case for node_e2e, though maybe node needs node_integration, and then those tests _should_ run as root, in CI.

But attempting to cover that as a unit test is not a suitable approach, I mean we're also not going to e.g. run unit tests across kernel versions, cgroup v1 vs v2, etc. But we do to an extent for e2e.

**Comment by gnufied** [comment]
We do have full e2e coverage of feature affected by PR that broke the test - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/fsgroupchangepolicy.go , so as such we weren't in danger of serious of regression. But I added those tests when I originally developed this feature and full e2e wasn't written. 

I will consider deleting these unit tests now I think. But at the same time, failing unit test did indeed uncover a bug in unit test themselves, so I would like to improve tests somehow before doing that.

**Comment by mattcary** [comment]
The right way to unit tests this is probably to fake out chmod with something with no userid dependency, something simple like changing the filename that we can easily verify in the unittest.

**Comment by gnufied** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/130624 as a follow up.

**Review by hashim21223445 — APPROVED** [review]
