### PR TITLE
Make latest.txt files non-cacheable

### LINKED ISSUE #15308: 6 of the last 12 kubernetes-build jenkins runs have failed
[Marking this as team/test-infra since there isn't a release team yet]

@quinton-hoole @ixdy 

We currently have a 50% success rate building k8s.

### PR DESCRIPTION
**Pull request by ikehz**
Fixes #15308.

### CODE REVIEW

File: build/common.sh [hunk 1]
```diff
@@ -1177,7 +1177,9 @@ function kube::release::gcs::publish() {
 
   local contents
   if [[ ${KUBE_GCS_MAKE_PUBLIC} =~ ^[yY]$ ]]; then
+    kube::log::status "Making uploaded version file public and non-cacheable."
     gsutil acl ch -R -g all:R "${publish_file_dst}" >/dev/null 2>&1 || return 1
+    gsutil setmeta -h "Cache-Control:private, max-age=0" "${publish_file_dst}" >/dev/null 2>&1 || return 1
```
Comment (ixdy) [inline build/common.sh]: https://cloud.google.com/storage/docs/gsutil/commands/setmeta also suggests adding "no-transform", though I don't know if that's strictly necessary.

https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata says

> Another use of the Cache-Control header is through the “no-transform” value, which instructs Google Cloud Storage to not apply any content transformations based on specifics of a download request, such as removing gzip content-encoding for incompatible clients. Note that this parameter is only respected by the XML API. The Google Cloud Storage JSON API respects only the no-cache and max-age Cache-Control parameters.

Comment (ihmccreery) [inline build/common.sh]: Yeah, there's another usage of Cache-Control above, and it doesn't include no-transform.  I'm not really concerned about it, since this is a text file ...

**Comment by ixdy** [comment]
LGTM

**Comment by ihmccreery** [comment]
@k8s-oncall You might consider merging this ASAP, since right now we're failing half of our builds due to #15308.

**Comment by ixdy** [comment]
Yeah, and the build step of Jenkins and Travis passed, so this is probably good to merge now.

**Comment by roberthbailey** [comment]
Not waiting on shippable to merge this one, since it only affects the jenkins configs.
