### PR TITLE
e2e network policies test support network policies with finalizers

### LINKED ISSUE #2: e2e [It] should support creating NetworkPolicy API with endport field
The test delete the collection of API objects and does not wait for then to be deleted, expecting immediate deletion.

Since we add a finalizer the test fails because it needs the finalizer to be removed for the object to finally be deleted

```
2025-03-01T10:02:53.7826781Z [38;5;9m• [FAILED] [0.527 seconds][0m
2025-03-01T10:02:53.7827930Z [0m[sig-network] Netpol API [38;5;9m[1m[It] should support creating NetworkPolicy API with endport field[0m [38;5;204m[sig-network][0m
2025-03-01T10:02:53.7829118Z [38;5;243mk8s.io/kubernetes/test/e2e/network/netpol/network_policy_api.go:224[0m
2025-03-01T10:02:53.7832724Z 
2025-03-01T10:02:53.7833006Z   [38;5;243mTimeline >>[0m
2025-03-01T10:02:53.7834837Z   [1mSTEP:[0m Creating a kubernetes client [38;5;243m@ 03/01/25 10:02:53.236[0m
2025-03-01T10:02:53.7838558Z   I0301 10:02:53.236117 10291 util.go:502] >>> kubeConfig: /home/runner/work/network-policy-finalizer/network-policy-finalizer/_artifacts/kubeconfig.conf
2025-03-01T10:02:53.7842946Z   [1mSTEP:[0m Building a namespace api object, basename netpol [38;5;243m@ 03/01/25 10:02:53.238[0m
2025-03-01T10:02:53.7846863Z   [1mSTEP:[0m Waiting for a default service account to be provisioned in namespace [38;5;243m@ 03/01/25 10:02:53.343[0m
2025-03-01T10:02:53.7848999Z   [1mSTEP:[0m Waiting for kube-root-ca.crt to be provisioned in namespace [38;5;243m@ 03/01/25 10:02:53.371[0m
2025-03-01T10:02:53.7852841Z   [1mSTEP:[0m EndPort field cannot be defined if the Port field is not defined. [38;5;243m@ 03/01/25 10:02:53.408[0m
2025-03-01T10:02:53.7858036Z   [1mSTEP:[0m EndPort field cannot be defined if the Port field is defined as a named (string) port. [38;5;243m@ 03/01/25 10:02:53.464[0m
2025-03-01T10:02:53.7861997Z   [1mSTEP:[0m EndPort field must be equal or greater than port. [38;5;243m@ 03/01/25 10:02:53.494[0m
2025-03-01T10:02:53.7866640Z   [1mSTEP:[0m When EndPort field is smaller than port, it will failed [38;5;243m@ 03/01/25 10:02:53.494[0m
2025-03-01T10:02:53.7868553Z   [1mSTEP:[0m EndPort field is equal with port. [38;5;243m@ 03/01/25 10:02:53.517[0m
2025-03-01T10:02:53.7871441Z   [1mSTEP:[0m EndPort field is greater than port. [38;5;243m@ 03/01/25 10:02:53.544[0m
2025-03-01T10:02:53.7873749Z   [1mSTEP:[0m deleting all test collection [38;5;243m@ 03/01/25 10:02:53.594[0m
2025-03-01T10:02:53.7876920Z   [38;5;9m[FAILED][0m in [It] - k8s.io/kubernetes/test/e2e/network/netpol/network_policy_api.go:272 [38;5;243m@ 03/01/25 10:02:53.693[0m
2025-03-01T10:02:53.7879828Z   I0301 10:02:53.693777 10291 helper.go:125] Waiting up to 7m0s for all (but 0) nodes to be ready
2025-03-01T10:02:53.7883519Z   [1mSTEP:[0m Destroying namespace "netpol-7060" for this suite. [38;5;243m@ 03/01/25 10:02:53.734[0m
2025-03-01T10:02:53.7886168Z   [38;5;243m<< Timeline[0m
2025-03-01T10:02:53.7887937Z 
2025-03-01T10:02:53.7888600Z   [38;5;9m[FAILED] filtered list should be 0 items
2025-03-01T10:02:53.7890811Z   Expected
```

### LINKED ISSUE #3: e2e [It] should support creating NetworkPolicy API operations
```
2025-03-01T10:00:52.2937674Z   [1mSTEP:[0m getting /apis/networking.k8s.iov1 [38;5;243m@ 03/01/25 10:00:51.142[0m
2025-03-01T10:00:52.2947254Z   [1mSTEP:[0m creating [38;5;243m@ 03/01/25 10:00:51.146[0m
2025-03-01T10:00:52.2947936Z   [1mSTEP:[0m getting [38;5;243m@ 03/01/25 10:00:51.439[0m
2025-03-01T10:00:52.2948589Z   [1mSTEP:[0m listing [38;5;243m@ 03/01/25 10:00:51.513[0m
2025-03-01T10:00:52.2949224Z   [1mSTEP:[0m watching [38;5;243m@ 03/01/25 10:00:51.598[0m
2025-03-01T10:00:52.2949818Z   I0301 10:00:51.598335 10164 network_policy_api.go:146] starting watch
2025-03-01T10:00:52.2950587Z   [1mSTEP:[0m cluster-wide listing [38;5;243m@ 03/01/25 10:00:51.62[0m
2025-03-01T10:00:52.2951349Z   [1mSTEP:[0m cluster-wide watching [38;5;243m@ 03/01/25 10:00:51.835[0m
2025-03-01T10:00:52.2952273Z   I0301 10:00:51.835223 10164 network_policy_api.go:157] starting watch
2025-03-01T10:00:52.2952964Z   [1mSTEP:[0m patching [38;5;243m@ 03/01/25 10:00:51.847[0m
2025-03-01T10:00:52.2953599Z   [1mSTEP:[0m updating [38;5;243m@ 03/01/25 10:00:51.905[0m
2025-03-01T10:00:52.2954353Z   I0301 10:00:51.966892 10164 network_policy_api.go:173] waiting for watch events with expected annotations
2025-03-01T10:00:52.2955655Z   I0301 10:00:51.966931 10164 network_policy_api.go:190] missing expected annotations, waiting: map[string]string{"patched":"true"}
2025-03-01T10:00:52.2956741Z   I0301 10:00:51.966972 10164 network_policy_api.go:186] saw patched and updated annotations
2025-03-01T10:00:52.2957852Z   [1mSTEP:[0m deleting [38;5;243m@ 03/01/25 10:00:51.967[0m
2025-03-01T10:00:52.2958983Z   [38;5;9m[FAILED][0m in [It] - k8s.io/kubernetes/test/e2e/network/netpol/network_policy_api.go:202 [38;5;243m@ 03/01/25 10:00:52.079[0m
2025-03-01T10:00:52.2960040Z   I0301 10:00:52.079530 10164 helper.go:125] Waiting up to 7m0s for all (but 0) nodes to be ready
2025-03-01T10:00:52.2961070Z   [1mSTEP:[0m Destroying namespace "netpol-4308" for this suite. [38;5;243m@ 03/01/25 10:00:52.128[0m
2025-03-01T10:00:52.2961788Z   [38;5;243m<< Timeline[0m
2025-03-01T10:00:52.2962012Z 
2025-03-01T10:00:52.2962241Z   [38;5;9m[FAILED] expected 404, got <nil>[0m
```

The test should wait for the deletion to complete asynchronously , it does

```
		// NetPol resource delete operations
		ginkgo.By("deleting")
		err = npClient.Delete(ctx, createdNetPol.Name, metav1.DeleteOptions{})
		framework.ExpectNoError(err)
		_, err = npClient.Get(ctx, createdNetPol.Name, metav1.GetOptions{})
		if !apierrors.IsNotFound(err) {
			framework.Failf("expected 404, got %#v", err)
		}
```

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup
/kind failing-test

Fixes https://github.com/kubernetes-sigs/network-policy-finalizer/issues/3
Fixes https://github.com/kubernetes-sigs/network-policy-finalizer/issues/2

```release-note
NONE
```

The e2e test expect the deletion of network policies to be synchronous, but there are some cases where is needed to use finalizer to avoid security issues, so the tests must consider the network policy object deletion to be asynchronous.

/sig network
/assign @danwinship @adrianmoisey

### CODE REVIEW

File: test/e2e/network/netpol/network_policy_api.go [hunk 1]
```diff
@@ -208,9 +215,20 @@ var _ = common.SIGDescribe("Netpol API", func() {
...
-		nps, err = npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
-		framework.ExpectNoError(err)
-		gomega.Expect(nps.Items).To(gomega.BeEmpty(), "filtered list should have 0 items")
+		err = wait.PollUntilContextTimeout(ctx, 2*time.Second, 1*time.Minute, false, func(ctx context.Context) (done bool, err error) {
+			nps, err = npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
+			if err != nil {
+				return false, err
+			}
+			if len(nps.Items) > 0 {
+				framework.Logf("still %d network policies present, retrying ...")
```
Comment (adrianmoisey) [inline test/e2e/network/netpol/network_policy_api.go:224]:
```suggestion
				framework.Logf("still %d network policies present, retrying ...", len(nps.Items))
```

As per failing lint

File: test/e2e/network/netpol/network_policy_api.go [hunk 2]
```diff
@@ -267,8 +285,19 @@ var _ = common.SIGDescribe("Netpol API", func() {
...
-		nps, err := npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
-		framework.ExpectNoError(err)
-		gomega.Expect(nps.Items).To(gomega.BeEmpty(), "filtered list should be 0 items")
+		err = wait.PollUntilContextTimeout(ctx, 2*time.Second, 1*time.Minute, false, func(ctx context.Context) (done bool, err error) {
+			nps, err := npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
+			if err != nil {
+				return false, err
+			}
+			if len(nps.Items) > 0 {
+				framework.Logf("still %d network policies present, retrying ...")
```
Comment (adrianmoisey) [inline test/e2e/network/netpol/network_policy_api.go:294]:
```suggestion
				framework.Logf("still %d network policies present, retrying ...", len(nps.Items) )
```

**Comment by adrianmoisey** [comment]
This change seems sane to me, happy to give a LGTM
Just 2 minor lints that need fixing

File: test/e2e/network/netpol/network_policy_api.go [hunk 3]
```diff
@@ -267,8 +285,19 @@ var _ = common.SIGDescribe("Netpol API", func() {
...
-		nps, err := npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
-		framework.ExpectNoError(err)
-		gomega.Expect(nps.Items).To(gomega.BeEmpty(), "filtered list should be 0 items")
+		err = wait.PollUntilContextTimeout(ctx, 2*time.Second, 1*time.Minute, false, func(ctx context.Context) (done bool, err error) {
+			nps, err := npClient.List(ctx, metav1.ListOptions{LabelSelector: "special-label=" + f.UniqueName})
+			if err != nil {
+				return false, err
+			}
+			if len(nps.Items) > 0 {
+				framework.Logf("still %d network policies present, retrying ...", len(nps.Items) )
```
Comment (adrianmoisey) [inline test/e2e/network/netpol/network_policy_api.go:294]:
```suggestion
				framework.Logf("still %d network policies present, retrying ...", len(nps.Items))
```

Sorry! My bad

**Comment by aojea** [comment]
/retest

pod scheduling timeout issues, that is infra capacity problems
