### PR TITLE
Fix memory limit decrease test on cri-o

### LINKED ISSUE #133343: [Failing Test] [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] decrease memory limit below usage
Test is consistently failing on CRI-o jobs.

##### Error text:
```
[FAILED] Timed out after 300.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc0006b5df0>: 
    non-viable resize unexpectedly completed
    {
        s: "non-viable resize unexpectedly completed",
    }
In [It] at: k8s.io/kubernetes/test/e2e/common/node/pod_resize.go:1337 @ 07/22/25 07:42:44.481
[sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] decrease memory limit below usage
```
#### Recent failures:
[7/31/2025, 5:15:52 AM ci-crio-cgroupv1-node-e2e-unlabelled](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-unlabelled/1950893068647403520)
[7/31/2025, 2:27:52 AM ci-crio-cgroupv2-node-e2e-unlabelled](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-node-e2e-unlabelled/1950850789891117056)
[7/30/2025, 11:56:52 PM ci-crio-cgroupv1-node-e2e-unlabelled-canary](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-unlabelled-canary/1950812789287161856)
[7/30/2025, 11:56:52 PM ci-crio-cgroupv2-node-e2e-unlabelled-canary](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-node-e2e-unlabelled-canary/1950812789475905536)
[7/30/2025, 5:15:30 PM ci-crio-cgroupv1-node-e2e-unlabelled](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-unlabelled/1950711780959326208)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by tallclair**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

The test is supposed to decrease the memory limit below the usage, and verify that the resize is blocked, but the usage information is read from cAdvisor on cri-o, which uses periodic scraping and caches the results. If the usage has not yet been scraped, then the usage check reads 0 and allows the resize. The fix is to wait for 2 * housekeeping interval to ensure the stats are collected before initiating the resize.

 I'm not sure why there's so much more latency on cri-o than containerd.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/133343

#### Special notes for your reviewer:

FYI, local test setup: https://github.com/cri-o/cri-o/pull/9374

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/priority important-soon
/sig node
/assign @natasha41575 @haircommander

### CODE REVIEW

File: test/e2e/common/node/pod_resize.go [hunk 1]
```diff
@@ -1322,6 +1322,11 @@ func doPodResizeMemoryLimitDecreaseTest(f *framework.Framework) {
 		resizedPod := podresize.WaitForPodResizeActuation(ctx, f, podClient, testPod, viableLoweredLimit)
 		podresize.ExpectPodResized(ctx, f, resizedPod, viableLoweredLimit)
 
+		ginkgo.By("Waiting for stats scraping")
```
Comment (natasha41575) [inline test/e2e/common/node/pod_resize.go:1327]: maybe leave a comment that this only seems to be needed for crio?

Comment (tallclair) [reply test/e2e/common/node/pod_resize.go:1327]: Done.

**Review by natasha41575 — COMMENTED** [review]
/lgtm
