### PR TITLE
fix(test::npd): fix node problem detector test

### LINKED ISSUE #95955: [Failing test] SystemLogMonitor should generate node condition and events for corresponding errors
**Which jobs are failing**:
`ci-npd-e2e-node`

**Which test(s) are failing**:
`SystemLogMonitor should generate node condition and events for corresponding errors`

**Since when has it been failing**:
Last successful run (23 Oct 2020, 10:07 PDT): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-node/1319686617375444992
First unsuccessful run (23 Oct 2020, 12:08 PDT): https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-node/1319717073798041600

**Testgrid link**:
https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-node

**Reason for failure**:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:245
Timed out after 60.000s.
Expected success, but got an error:
    <*errors.errorString | 0xc001212cd0>: {
        s: "node condition \"TestCondition\" not found",
    }
    node condition "TestCondition" not found
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:360
```

**Anything else we need to know**:
[pull-npd-e2e-node](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-npd-e2e-node) presubmit job in k8s.io/node-problem-detector repository also started to fail in the same fashion.

Attempted to debug it myself, found out the following stuff:
* last successful run was accessing the apiserver via HTTP:
```
W1023 17:12:40.514888    2808 test_context.go:420] Unable to find in-cluster config, using default host : http://127.0.0.1:8080
```
* all unsuccessful runs attempted to access the apiserver via HTTPS but to no avail:
```
W1023 19:14:09.903857     995 test_context.go:437] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
(...)
W1023 19:15:40.789213     925 util.go:106] Health check on "https://127.0.0.1:6443/healthz" failed, status=500
```
* perused the history of `k/k/test` to find out that the PR https://github.com/kubernetes/kubernetes/pull/94723 is almost certainly the reason of the failures (or rather uncovered some problem with the NPD or its tests):
  * first, it coincides with the start of the failures of `ci-npd-e2e-node`,
  * second, we changed the default hostname of the apiserver in node tests in that PR.

Judging by the code and the changes in the aforementioned PR I think that a quick mitigation would be to add a `--host=http://127.0.0.1:8080` flag to the `--node-test-args` of these jobs.

/assign
/sig node
/cc @knight42 @Random-Liu

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Since the insecure port of apiserver has been disabled in e2e node tests,
we could create a service account in the test for node problem detector
and then bind the cluster role `cluster-admin` with this service account.

**Which issue(s) this PR fixes**:

Fixes #95955

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e_node/node_problem_detector_linux.go [hunk 1]
```diff
@@ -207,7 +239,7 @@ var _ = framework.KubeDescribe("NodeProblemDetector [NodeFeature:NodeProblemDete
 						{
 							Name:    name,
 							Image:   image,
-							Command: []string{"sh", "-c", "touch " + logFile + " && /node-problem-detector --logtostderr --system-log-monitors=" + configFile + fmt.Sprintf(" --apiserver-override=%s?inClusterConfig=false", framework.TestContext.Host)},
+							Command: []string{"sh", "-c", "touch " + logFile + " && /node-problem-detector --logtostderr --system-log-monitors=" + configFile + fmt.Sprintf(" --apiserver-override=%s?inClusterConfig=false&useServiceAccount=true&insecure=true", framework.TestContext.Host)},
```
Comment (Random-Liu) [inline test/e2e_node/node_problem_detector_linux.go:242]: Why `insecure=true`? I guess `insecure` here means not validating server cert instead of using `http`?

Comment (knight42) [reply test/e2e_node/node_problem_detector_linux.go:242]: > Why `insecure=true`?

Perhaps I am missing something, I think we don't know the CA used by apiserver in node e2e tests.

> I guess insecure here means not validating server cert instead of using http?

nope, it is equivalent to `kubectl --insecure-skip-tls-verify ...`: https://github.com/kubernetes/node-problem-detector/blob/53ee78d3725f157f12fd19978b94b2fe8978150b/vendor/k8s.io/heapster/common/kubernetes/configs.go#L54
we are still using HTTPS.

Comment (knight42) [reply test/e2e_node/node_problem_detector_linux.go:242]: looks like we could use `inClusterConfig`, so that we dont need `insecure=true` here.

File: test/e2e_node/node_problem_detector_linux.go [hunk 2]
```diff
@@ -160,24 +162,54 @@ var _ = framework.KubeDescribe("NodeProblemDetector [NodeFeature:NodeProblemDete
...
+
+			ginkgo.By("Bind the cluster role cluster-admin with the service account for node problem detector")
+			_, err = f.ClientSet.RbacV1().ClusterRoleBindings().Create(context.TODO(), &rbacv1.ClusterRoleBinding{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: name,
+				},
+				RoleRef: rbacv1.RoleRef{
+					APIGroup: rbacv1.GroupName,
+					Kind:     "ClusterRole",
+					Name:     "cluster-admin",
```
Comment (Random-Liu) [inline test/e2e_node/node_problem_detector_linux.go:190]: Can we use `system:node-problem-detector`?

Comment (knight42) [reply test/e2e_node/node_problem_detector_linux.go:190]: Oh sure, I don't know we have such clusterRole before, thanks for pointing it out.

**Comment by knight42** [comment]
/assign @tallclair

@tallclair PTAL

**Comment by karan** [comment]
/test pull-kubernetes-bazel-test
--
