### PR TITLE
os exit when option is true

### LINKED ISSUE #76727: kube-proxy does not exit after --cleanup
**What happened**:
I ran the following to clean up kube-proxy rules:

```
# docker run --privileged -v /lib/modules:/lib/modules --net=host k8s.gcr.io/kube-proxy-amd64:v1.14.1 kube-proxy --cleanup    
Unable to find image 'k8s.gcr.io/kube-proxy-amd64:v1.14.1' locally                                                                                           
v1.14.1: Pulling from kube-proxy-amd64                                                                                                                       
Digest: sha256:020d25ff45a33ec7958d7128308cb499d5b24cdaa228a2344514bcab9b7296c0                                                                              
Status: Downloaded newer image for k8s.gcr.io/kube-proxy-amd64:v1.14.1                                                                                       
W0417 14:39:15.363623       1 server.go:214] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a co
nfig file ASAP.                                                                                                                                              
I0417 14:39:15.375997       1 server.go:555] Version: v1.14.1
```
It did not exit after finishing the cleanup.

**What you expected to happen**:
I expected kube-proxy to cleanup and exit.

**How to reproduce it (as minimally and precisely as possible)**:
Build cluster with kubeadm
Run the docker command above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
vSphere on colo servers.

- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```redacted-hostname 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux```

- Install tools:
kubeadm

- Others:

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
When CleanupAndExit is true , kube-proxy doesn't exit
Related:
https://github.com/kubernetes/kubernetes/blob/6c55e2d20632cb1aa754bcad02139c30510cd1fe/cmd/kube-proxy/app/server.go#L322-L334
https://github.com/kubernetes/kubernetes/blob/6c55e2d20632cb1aa754bcad02139c30510cd1fe/cmd/kube-proxy/app/server.go#L553-L561
https://github.com/kubernetes/kubernetes/blob/6c55e2d20632cb1aa754bcad02139c30510cd1fe/cmd/kube-proxy/app/server.go#L466
**Which issue(s) this PR fixes**:

Fixes #76727 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kube-proxy: os exit when CleanupAndExit is set to true
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR.
this code is from 1.1 (2015).

/kind bug
/priority important-longterm
/ok-to-test

@kubernetes/sig-network-pr-reviews

**Comment by vllry** [comment]
/assign @andrewsykim 

Handling exits like this (raising an error as a non-error exit signal) feels like a code smell to me, but this does appear to solve the issue.

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by JieJhih** [comment]
@vllry 
> Handling exits like this (raising an error as a non-error exit signal) feels like a code smell to me, but this does appear to solve the issue.
>
Yeah it solved the issue but it can be better.
I think it can be something like this.
``errCh chan error`` change into  ``errCh chan errChannel``
```
type errChannel struct {
      Message string
      Err           error
 }
```
But the change will affect some places , I will create another PR to refactor this.

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -557,7 +557,7 @@ func (s *ProxyServer) Run() error {
 		if encounteredError {
 			return errors.New("encountered an error while tearing down rules")
 		}
-		return nil
+		return errors.New("cleaup and exit")
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: Agree with @vllry, this seems like a bit of a code smell, we're effectively saying that nil errors are invalid. I personally think we should fix/refactor properly in this PR. I'm wondering if it would be cleaner if we pulled the clean up & exit logic out of `Run()` and ran the clean up check prior, that would reduce some of the complexity with passing errors through channels.

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: That is a good way!
It can run clean up & exit logic before run proxy server if success then os exit else return the error message.
I will refactor in this PR.
https://github.com/kubernetes/kubernetes/blob/3b12266c06709f5a5ada9fd9605839ee8a796ef6/cmd/kube-proxy/app/server.go#L321-L325

Comment (andrewsykim) [reply cmd/kube-proxy/app/server.go]: Yeah that seems like a better approach to me, thoughts @vllry?

Comment (vllry) [reply cmd/kube-proxy/app/server.go]: +1 from me

**Comment by vllry** [comment]
I was thinking about test coverage for something like this - e2e would be messy, and unsure how to properly deal with iptables/IPVS scope in a unit test.

**Comment by JieJhih** [comment]
@andrewsykim @vllry 
May I ask what places are implemented proxyRun.Run()?
I think before I figure this out, I should use ``func CleanUpAndExit(s *ProxyServer)`` rather than ``func (s *ProxyServer) CleanUpAndExit()``

**Comment by JieJhih** [comment]
ping @andrewsykim @vllry  PTAL.

**Review by dixudx — COMMENTED** [review]
@JieJhih Would you please squash your commits. Others lgtm. Thanks.

File: cmd/kube-proxy/app/server.go [hunk 2]
```diff
@@ -549,16 +578,6 @@ func createClients(config componentbaseconfig.ClientConnectionConfiguration, mas
 func (s *ProxyServer) Run() error {
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: I still find it a little awkward that Run() cannot return a nil error. Should we document this somewhere or can we at least add a TODO comment here to clean this up in a follow-up PR?

File: cmd/kube-proxy/app/server.go [hunk 3]
```diff
@@ -463,7 +487,12 @@ with the apiserver API to configure the proxy.`,
 			if err := opts.Validate(args); err != nil {
 				klog.Fatalf("failed validate: %v", err)
 			}
-			klog.Fatal(opts.Run())
+			err := opts.Run()
+			if err, ok := err.(*OSExit); ok {
+				// os exit with status 0
+				err.Run(0)
+			}
+			klog.Fatal(err)
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: IIRC, `klog.Fatal` can accept nil here. Wondering if it's cleaner if we keep this as just:
```go
klog.Fatal(opts.Run())
```

and in `runLoop()`:
```go
func (o *Options) runLoop() error {
        if o.CleanupAndExit {
              return o.proxyServer.CleanUpAndExit()
        }
```

Actually exiting with 0 is nice here but maybe not worth the trade-off since previous versions have been exiting with non-zero exit codes already? Either way, might be good change the behavior for exit codes in a follow-up PR to make the cherry-pick to previous versions easier.

File: cmd/kube-proxy/app/server_test.go [hunk 4]
```diff
@@ -540,6 +540,13 @@ func (s *fakeProxyServerLongRun) Run() error {
 	}
 }
 
+// CleanUpAndExit runs in the specified ProxyServer.
+func (s *fakeProxyServerLongRun) CleanUpAndExit() error {
+	for {
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server_test.go]: why is the for loop needed here?

File: cmd/kube-proxy/app/server_test.go [hunk 5]
```diff
@@ -549,3 +556,11 @@ func (s *fakeProxyServerError) Run() error {
 		return fmt.Errorf("mocking error from ProxyServer.Run()")
 	}
 }
+
+// CleanUpAndExit runs in the specified ProxyServer.
+func (s *fakeProxyServerError) CleanUpAndExit() error {
+	for {
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server_test.go]: why is the for loop needed here?

File: cmd/kube-proxy/app/server.go (hunk 3 above)
Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: @andrewsykim Yeah, but should it use ``klog.Info`` rather than ``klog.Fatal`` when clean up and exit?

**Comment by JieJhih** [comment]
@andrewsykim Updated. Thanks

File: cmd/kube-proxy/app/server.go [hunk 6]
```diff
@@ -546,19 +550,10 @@ func createClients(config componentbaseconfig.ClientConnectionConfiguration, mas
 }
 
 // Run runs the specified ProxyServer.  This should never exit (unless CleanupAndExit is set).
+// TODO: cannot return a nil error.
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: // TODO: At the moment, Run() cannot return a nil error, otherwise it's caller will never exit. Update callers of Run to handle nil errors.

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: Updated.
Thanks

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: I have a little question. The func still return nil when success. 
```
func (s *ProxyServer) CleanUpAndExit() error {
	// remove iptables rules and exit
	if s.CleanupAndExit {
		encounteredError := userspace.CleanupLeftovers(s.IptInterface)
		encounteredError = iptables.CleanupLeftovers(s.IptInterface) || encounteredError
		encounteredError = ipvs.CleanupLeftovers(s.IpvsInterface, s.IptInterface, s.IpsetInterface, s.CleanupIPVS) || encounteredError
		if encounteredError {
			return errors.New("encountered an error while tearing down rules")
		}
	}
	return nil
}
```

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: Where did you expect to handle nil error?
https://github.com/kubernetes/kubernetes/blob/1377108c084545e2279bd67eed56e54283572302/cmd/kube-proxy/app/server.go#L310-L311

**Comment by JieJhih** [comment]
@dixudx @andrewsykim Squashed and pushed. Thanks

File: cmd/kube-proxy/app/server_test.go [hunk 7]
```diff
@@ -549,3 +554,9 @@ func (s *fakeProxyServerError) Run() error {
 		return fmt.Errorf("mocking error from ProxyServer.Run()")
 	}
 }
+
+// CleanUpAndExit runs in the specified ProxyServer.
+func (s *fakeProxyServerError) CleanUpAndExit() error {
+	time.Sleep(2 * time.Second)
```
Comment (vllry) [inline cmd/kube-proxy/app/server_test.go]: I don't think the sleep is necessary, as far as I can see we're not really testing async behavior.

**Review by vllry — CHANGES_REQUESTED** [review]

File: cmd/kube-proxy/app/server_test.go (hunk 7 above)
Comment (JieJhih) [reply cmd/kube-proxy/app/server_test.go]: Updated.
Thanks

**Comment by vllry** [comment]
Looks good. I'm not too happy with the pattern of returning non-errors as an err, but I feel like addressing that would be some scope-creep for this PR. @andrewsykim might be worth opening another issue?

/lgtm

**Comment by andrewsykim** [comment]
LGTM as well. Agree with @vllry, we should address the following in separate PRs to keep this PR in a cherry pick-able state:
* Handle nil errors from Run()
* Exit 0 if clean up and exit succeeds. Right now it's whatever `klog.Fatal` returns which is a non-zero exit status as far as I can tell. 

/assign @liggitt @thockin 
For approval, this is a follow-up bug fix from https://github.com/kubernetes/kubernetes/pull/59176

File: cmd/kube-proxy/app/server.go [hunk 8]
```diff
@@ -704,3 +699,17 @@ func getConntrackMax(config kubeproxyconfig.KubeProxyConntrackConfiguration) (in
 	}
 	return 0, nil
 }
+
+// CleanUpAndExit remove iptables rules and exit if success return nil
+func (s *ProxyServer) CleanUpAndExit() error {
+	// remove iptables rules and exit
+	if s.CleanupAndExit {
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: do we still need this field and test now?

File: cmd/kube-proxy/app/server.go [hunk 9]
```diff
@@ -314,6 +315,9 @@ func (o *Options) Run() error {
 // runLoop will watch on the update change of the proxy server's configuration file.
 // Return an error when updated
 func (o *Options) runLoop() error {
+	if o.CleanupAndExit {
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: Why not lift this into Run() above?

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: Yeah, this can be checked earlier.
Thanks

File: cmd/kube-proxy/app/server.go (hunk 8 above)
Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: ping @vllry @andrewsykim

Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: I have noticed that ``CleanupAndExit`` option, are this different?
https://github.com/kubernetes/kubernetes/blob/716344fd7d68f92d9a16280be1feae0ffe122bb4/cmd/kube-proxy/app/server.go#L97-L103
https://github.com/kubernetes/kubernetes/blob/716344fd7d68f92d9a16280be1feae0ffe122bb4/cmd/kube-proxy/app/server.go#L500
https://github.com/kubernetes/kubernetes/blob/716344fd7d68f92d9a16280be1feae0ffe122bb4/cmd/kube-proxy/app/server_others.go#L99-L106

Comment (vllry) [reply cmd/kube-proxy/app/server.go]: thockin is right, that if-statement can be removed, as the function is only called when CleanupAndExit is set.

CleanupAndExit / CleanUpAndExit are the same thing, there just appears to be some internal inconsistencies in variable names.

**Review by vllry — CHANGES_REQUESTED** [review]

File: cmd/kube-proxy/app/server.go (hunk 8 above)
Comment (JieJhih) [reply cmd/kube-proxy/app/server.go]: Updated
Thanks

File: cmd/kube-proxy/app/server.go [hunk 10]
```diff
@@ -704,3 +701,16 @@ func getConntrackMax(config kubeproxyconfig.KubeProxyConntrackConfiguration) (in
 	}
 	return 0, nil
 }
+
+// CleanUpAndExit remove iptables rules and exit if success return nil
+func (s *ProxyServer) CleanUpAndExit() error {
+	// remove iptables rules and exit
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: nit: this comment can be removed since we have the same comment for the method now.

File: cmd/kube-proxy/app/server_test.go [hunk 11]
```diff
@@ -549,3 +554,8 @@ func (s *fakeProxyServerError) Run() error {
 		return fmt.Errorf("mocking error from ProxyServer.Run()")
 	}
 }
+
+// CleanUpAndExit runs in the specified ProxyServer.
+func (s *fakeProxyServerError) CleanUpAndExit() error {
+	return fmt.Errorf("mocking error from ProxyServer.CleanUpAndExit()")
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server_test.go]: nit: 
```
errors.New("mocking error from ProxyServer.CleanUpAndExit()")
```

**Comment by andrewsykim** [comment]
@JieJhih this PR needs a release note since it's fixing a user visible bug

**Comment by JieJhih** [comment]
@andrewsykim Updated. Thanks

File: cmd/kube-proxy/app/server.go [hunk 12]
```diff
@@ -307,6 +308,11 @@ func (o *Options) Run() error {
 	if err != nil {
 		return err
 	}
+
+	if o.CleanupAndExit {
+		return proxyServer.CleanUpAndExit()
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: Can we name the method the same as the flag?

File: cmd/kube-proxy/app/server.go [hunk 13]
```diff
@@ -546,19 +552,10 @@ func createClients(config componentbaseconfig.ClientConnectionConfiguration, mas
 }
 
 // Run runs the specified ProxyServer.  This should never exit (unless CleanupAndExit is set).
+// TODO: At the moment, Run() cannot return a nil error, otherwise it's caller will never exit. Update callers of Run to handle nil errors.
 func (s *ProxyServer) Run() error {
 	// To help debugging, immediately log version
 	klog.Infof("Version: %+v", version.Get())
-	// remove iptables rules and exit
-	if s.CleanupAndExit {
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: can we remove the `ProxyServer.CleanupAndExit` field at the same time?

**Comment by JieJhih** [comment]
@thockin Updated. PTAL.

**Comment by andrewsykim** [comment]
@JieJhih I think @thockin mentioned to also remove the field `CleanupAndExit` field from the ProxyServer struct. See [here](https://github.com/kubernetes/kubernetes/blob/a9ab371f46ac746c8e3d293d83d485b1fdfc5f26/cmd/kube-proxy/app/server.go#L500).

**Comment by JieJhih** [comment]
@andrewsykim Yeah, I have removed that field in the newest commit. Thanks
https://github.com/kubernetes/kubernetes/pull/76732/files#diff-cf93bbed37202b7d58b5841f07ddd89fL500

**Review by thockin — APPROVED** [review]
Thanks!

/lgtm
/approve

**Comment by andrewsykim** [comment]
/lgtm

Thanks for iterating @JieJhih!

File: cmd/kube-proxy/app/server.go [hunk 14]
```diff
@@ -682,3 +678,15 @@ func getConntrackMax(config kubeproxyconfig.KubeProxyConntrackConfiguration) (in
 	}
 	return 0, nil
 }
+
+// CleanupAndExit remove iptables rules and exit if success return nil
+func (s *ProxyServer) CleanupAndExit() error {
+	encounteredError := userspace.CleanupLeftovers(s.IptInterface)
```
Comment (tedyu) [inline cmd/kube-proxy/app/server.go]: I wonder if CleanupLeftovers should return the (aggregate) error instead of returning just a boolean.
This would be useful for caller for analysis.

Comment (andrewsykim) [reply cmd/kube-proxy/app/server.go]: I agree that this is a bit ugly but I don't think it'll be easy to fix. A lot of errors from `CleanupLeftovers` don't warrant an early return. For what it's worth, most of the errors are still logged via `klog.Error` though.
