### PR TITLE
Fix validation for Job with suspend=true,completions=0 to set Complete condition

### LINKED ISSUE #132144: Job status.conditions behavior change 1.31 -> 1.32
### What happened?

In version 1.32.0 apply job with `spec.completions=0` and `spec.suspend=true`:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: suspended-zero-completions 
  namespace: default
spec:
  completions: 0
  suspend: true
  template:
    spec:
      containers: 
      - name: noop
        image: busybox
        command: ["true"] 
      restartPolicy: Never
```
Job ends up with conditions:
```
  status:
    conditions:
    - lastProbeTime: "2025-06-06T09:44:17Z"
      lastTransitionTime: "2025-06-06T09:44:17Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
``` 
and STATUS=Running
```
NAME                         STATUS    COMPLETIONS   DURATION   AGE
suspended-zero-completions   Running   0/0                      2s
```

### What did you expect to happen?

To have the same behavior as with version 1.31.9 when applying same job. 
That is expecting following conditions:
```
status:
    completionTime: "2025-06-06T09:40:50Z"
    conditions:
    - lastProbeTime: "2025-06-06T09:40:50Z"
      lastTransitionTime: "2025-06-06T09:40:50Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
    - lastProbeTime: "2025-06-06T09:40:50Z"
      lastTransitionTime: "2025-06-06T09:40:50Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: Complete
```
and STATUS=Complete
```
NAME                         STATUS     COMPLETIONS   DURATION   AGE
suspended-zero-completions   Complete   0/0                      11m
```

### How can we reproduce it (as minimally and precisely as possible)?

Apply job provided above to version 1.31 and version 1.32 and observe difference.

### Anything else we need to know?

If this is an intended change have release notes mention the change in behavior.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.32.0+k3s1
```

</details>

### Cloud provider

<details>
Irrelevant, core component.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR is related to:

Fixes #132144

#### Special notes for your reviewer:

There is an alternative solution, as proposed in https://github.com/kubernetes/kubernetes/issues/132144#issuecomment-2958751112.

I'm ok with both approaches, but with the relaxed validation the fix is smaller in scope as it only tweaks the validation introduced in the ManagedBy feature without setting StartTime.

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.32 regression in validation for Job with suspend=true, and completions=0 to set the Complete condition.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/4368-support-managed-by-for-batch-jobs
```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @tenzen-y @atiratree ptal

**Comment by tenzen-y** [comment]
> cc @tenzen-y @atiratree ptal

ACK

File: pkg/registry/batch/job/strategy.go [hunk 1]
```diff
@@ -379,6 +379,7 @@ func getStatusValidationOptions(newJob, oldJob *batch.Job) batchvalidation.JobSt
 		isUncountedTerminatedPodsChanged := !apiequality.Semantic.DeepEqual(oldJob.Status.UncountedTerminatedPods, newJob.Status.UncountedTerminatedPods)
 		isReadyChanged := !ptr.Equal(oldJob.Status.Ready, newJob.Status.Ready)
 		isTerminatingChanged := !ptr.Equal(oldJob.Status.Terminating, newJob.Status.Terminating)
+		isSuspendedWithZeroCompletions := newJob.Spec.Completions != nil && *newJob.Spec.Completions == 0 && newJob.Spec.Suspend != nil && *newJob.Spec.Suspend
```
Comment (tenzen-y) [inline pkg/registry/batch/job/strategy.go]:
```suggestion
		isSuspendedWithZeroCompletions := ptr.Equal(newJob.Spec.Completions, ptr.To[int32](0)) && ptr.Equal(newJob.Spec.Suspend, ptr.To(true))
```

We can simplify this criteria by `ptr` libs.

File: test/integration/job/job_test.go [hunk 2]
```diff
@@ -2902,6 +2902,29 @@ func TestParallelJobWithCompletions(t *testing.T) {
 	})
 }
 
+// TestSuspendedJobWithZeroCompletions verifies the suspended Job with
+// completions=0 is marked as Complete.
+func TestSuspendedJobWithZeroCompletions(t *testing.T) {
```
Comment (tenzen-y) [inline test/integration/job/job_test.go]: Instead of this dedicated one, shouldn't we generalize TestSuspend and add a new case to that?

https://github.com/kubernetes/kubernetes/blob/ca314b9f5614b976665279b5cd2e4a616dd8af3a/test/integration/job/job_test.go#L4039

**Review by tenzen-y — COMMENTED** [review]
Basically, LGTM
Thank you.

File: pkg/registry/batch/job/strategy.go (hunk 1 above)
Comment (mimowo) [reply pkg/registry/batch/job/strategy.go]: Done, also I swap the order to align with the variable name

File: test/integration/job/job_test.go (hunk 2 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: We could, but it seems the pre-existing test was written with the purpose of checking how the Suspend condition changes when we update the Job, which makes it non-trivial.

Also note we have pre-existing `TestSuspendJobControllerRestart`. My new test seems easier to consolidate with this one. For now, I align the name of the new test to use the same prefix as the preexisting tests `TestSuspendJob`.

Ultimately, I see all three tests should be consolidated. Since we already have 2 different tests, I suggest adding a new one, and opening an issue to consolidate them all, wdyt? Otherwise I would probably prefer to consolidate with `TestSuspendJobControllerRestart` as it is less effort.

Comment (tenzen-y) [reply test/integration/job/job_test.go]: That makes sense. Let us work on a follow-up PR / issue.
I raised the issue: https://github.com/kubernetes/kubernetes/issues/132621

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
as Job controller reviewer.

**Comment by mimowo** [comment]
/test pull-kubernetes-integration
due to unrelated flake https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/132614/pull-kubernetes-integration/1939644836831301632

**Comment by tenzen-y** [comment]
/assign @deads2k 
for strategy directory.

**Comment by mimowo** [comment]
@tenzen-y @atiratree @deads2k this is an edge case, but OTOH it is a regression, and the issue was opened by an end-user, see also [comment](https://github.com/kubernetes/kubernetes/issues/132144#issuecomment-2966466616).

Would you be supportive for cherry-picking to 1.32 and 1.33? If so I'm happy to prepare the PRs .

**Comment by tenzen-y** [comment]
> @tenzen-y @atiratree @deads2k this is an edge case, but OTOH it is a regression, and the issue was opened by an end-user, see also [comment](https://github.com/kubernetes/kubernetes/issues/132144#issuecomment-2966466616).
> 
> Would you be supportive for cherry-picking to 1.32 and 1.33? If so I'm happy to prepare the PRs .

IIUC, since v1.32, this Job behavior were broken user PoV. So, cherry-picking this to 1.32 and 1.33 sounds reasonable.
The discussion point is whether or not we should consider this corner case as a breaking specification change.

If a suspended Job with `completions=0` is not intended for the specifications and this should be restricted in the previous k8s version (until v1.31), we can consider this PR as a feature since this PR tries to explicitly allow them to deploy suspended Job with `completions=0`..

**Comment by mimowo** [comment]
> If a suspended Job with `completions=0` is not intended for the specifications and this should be restricted in the previous k8s version (until v1.31), we can consider this PR as a feature since this PR tries to explicitly allow them to deploy suspended Job with `completions=0`..

I'm not clear I understand this. Strengthening validation was discussed under the [issue](https://github.com/kubernetes/kubernetes/issues/132144#issuecomment-2957971941), I think the documentation is not clarifying it, but suspend=true and competitions=0 was supported for many releases prior to 1.32, so I think it makes sense to call it a bug/regression and continue supporting. 

Now, if we decide this configuration should not be supported (strengthening validation), then it is different PR to prepare.

**Comment by deads2k** [comment]
This is a bug and eligible for backport.  The unit test looks correct, but have the reporter confirm the fix works prior to backporting. 

/approve

**Comment by tenzen-y** [comment]
> This is a bug and eligible for backport. The unit test looks correct, but have the reporter confirm the fix works prior to backporting.
> 
> /approve

That makes sense. Thank you for checking that.

**Comment by mimowo** [comment]
/kind regression
since it started in 1.32
