### PR TITLE
Return attach error to A/D controller.

### LINKED ISSUE #63300: csi: Failed attach should be propagated to A/D controller
/kind bug
/sig storage

**What happened**:
Kubernetes continues with mounting of non-attached volume when CSI driver fails to attach a volume to a node.

Errors from the CSI driver (and external attacher) are just logged, but plugin.Attach() returns no error and A/D controller thinks that everything's all right and the volume was attached.

**How to reproduce it (as minimally and precisely as possible)**:
I forgot to run CSI registrar on a node and external attacher returned `node "host-172-16-120-15" has no NodeID annotation` in `VolumeAttachment.Status`.

This got propagated to CSI volume plugin in A/D controller, but the plugin just logged it:

```
E0430 14:56:34.581627       1 csi_attacher.go:112] kubernetes.io/csi: attacher.Attach attempted to wait for attachment to be ready, but failed with: node "host-172-16-120-15" has no NodeID annotation
I0430 14:56:34.581773       1 csi_attacher.go:115] kubernetes.io/csi: attacher.Attach finished OK with VolumeAttachment verified=false: attachment object [csi-135496b4c1ffbdb344c2fc649ddaae9e87413ccfca2c4b94af58fdb9ccd4bcd2]
```

The volume got marked as attached and kubeletet tried to mount non-existing volume.

**Anything else we need to know?**:
kubernetes v1.10.0+b81c8f8

### PR DESCRIPTION
**Pull request by jsafrane**
The plugin should not wait with errors for WaitForAttach, WaitForAttach runs on nodes, not in A/D controller.

**Which issue(s) this PR fixes**
Fixes #63300

~~Work in progress, missing testing.~~

**Release note**:

```release-note
Fixed error reporting of CSI volumes attachment.
```

/sig storage
@saad-ali @vladimirvivien

### CODE REVIEW

File: pkg/volume/csi/csi_attacher.go [hunk 1]
```diff
@@ -102,17 +102,11 @@ func (c *csiAttacher) Attach(spec *volume.Spec, nodeName types.NodeName) (string
 		glog.V(4).Info(log("attachment [%v] for volume [%v] created successfully", attachID, csiSource.VolumeHandle))
 	}
 
-	// probe for attachment update here
-	// NOTE: any error from waiting for attachment is logged only.  This is because
-	// the primary intent of the enclosing method is to create VolumeAttachment.
-	// DONOT return that error here as it is mitigated in attacher.WaitForAttach.
-	volAttachmentOK := true
 	if _, err := c.waitForVolumeAttachment(csiSource.VolumeHandle, attachID, csiTimeout); err != nil {
```
Comment (gnufied) [inline pkg/volume/csi/csi_attacher.go]: btw I noticed that CSI has default attachment time of 15s. That seems awfully short - is there anything in CSI that can return how much expected waiting time is going to be?

Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: No, there is no way how CSI driver could return estimated time.

On the other hand, attachment is handled by external attacher. External attacher still tries to attach the volume even when A/D controller timed out. A/D controller should periodically check (with exp. backoff?) if the volume got attached and does not need to wait in a blocking goroutine.

**Comment by jsafrane** [comment]
Added unit test.

**Comment by gnufied** [comment]
@msau42 problem is - if attach does not return `error` on attach failure then it will not be retried again will be assumed to be successful. So AD controller must know about incomplete attach in order to retry same operation again.

**Comment by msau42** [comment]
@gnufied can you explain how that causes the node's `WaitForAttach` to return success and continue to mount?  `WaitForAttach` only looks for `attach.Status.Attached` to be true, and that is only set by the external-attacher.

**Comment by jsafrane** [comment]
I had something wrong in my CSi driver setup and actually the driver continued with mounting from some reason. I can't reproduce the mounting part of this bug with my drivers now.

Anyway, A/D controller should re-check periodically and report errors when attaching fails.

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -102,17 +102,11 @@ func (c *csiAttacher) Attach(spec *volume.Spec, nodeName types.NodeName) (string
...
-		volAttachmentOK = false
-		glog.Error(log("attacher.Attach attempted to wait for attachment to be ready, but failed with: %v", err))
+		return "", err
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go]: Could this cause API quota issues because now we could be retrying a lot of VolumeAttachment.Create() operations for objects that already exist?  Can we potentially check the informer cache first to see if we already created it?

Comment (vladimirvivien) [reply pkg/volume/csi/csi_attacher.go]: The `volAttachmentOK` var was mainly there for status indication.  This change should work as just like before.  @msau42 are you saying to check for pre-existence before attemting to create ?

**Review by vladimirvivien — COMMENTED** [review]
Looks good to me.

File: pkg/volume/csi/csi_attacher.go (hunk 2 above)
Comment (msau42) [reply pkg/volume/csi/csi_attacher.go]: Yes, because this change can cause Attach() to retry more than before.

Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: That belongs to a separate PR

**Comment by gnufied** [comment]
I think API concern can be followed up in separate PR. As such this looks good to me.

/lgtm

File: pkg/volume/csi/csi_attacher.go (hunk 2 above)
Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: So, I checked how to fix this polling with something smarter, but it turns out that CSI volume plugin has no access to VolumeAttachment shared informer and the fix won't be simple one-liner. I filled #64429 to keep track of this, however, I am not actively working on it.
