### PR TITLE
skip reduceAllocatableMemoryUsage if cgroup v2 is enabled

### LINKED ISSUE #107062: Tests on sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial are failing
### Which jobs are failing?

sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Which tests are failing?

```
E2eNode Suite.[sig-node] Density [Serial] [Slow] create a batch of pods latency/resource should be within limit when create 10 pods with 0s intervalE2eNode Suite.[sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background podsE2eNode Suite.[sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring] when we run containers that should cause use quotas for LSCI monitoring (quotas enabled: false) should eventually evict all of the correct podsE2eNode Suite.[sig-node] Resource-usage [Serial] [Slow] regular resource usage tracking resource tracking for 10 pods per nodeE2eNode Suite.[sig-node] Restart [Serial] [Slow] [Disruptive] Container Runtime Network should recover from ip leak
```

### Since when has it been failing?

11/30, maybe earlier

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
/priority important-soon

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?

/sig node
/priority important-soon
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #107062

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
`[Feature:DevicePluginProbe]` failure is a known flake in serial tests.

File: test/e2e_node/util.go [hunk 1]
```diff
@@ -472,9 +472,11 @@ func toCgroupFsName(cgroupName cm.CgroupName) string {
 // to make the kernel reclaim memory in the allocatable cgroup
 // the time to reduce pressure may be unbounded, but usually finishes within a second
 func reduceAllocatableMemoryUsage() {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/util.go:474]: this method was introduced as a reaction on flakes https://github.com/kubernetes/kubernetes/pull/60900/. I agree, simply dropping it for cgroupv2 sounds like a reasonable idea.

Can you please update a method comment to indicate that this method does nothing for the cgroupv2. I would even suggest to rename the method to `reduceAllocatableMemoryUsageIfCgroupv1`

Looking at https://www.spinics.net/lists/linux-mm/msg227679.html and your comment https://github.com/kubernetes/kubernetes/issues/107062#issuecomment-995413273 I feel like we may want to watch for flakes instead of trying memory.high solution.

Comment (pacoxu) [reply test/e2e_node/util.go:474]: Let's rename it.

Once we have a solution for cgroup v2. We can rename it back and add the solution.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/skip

(skip as serial tests will fail with the known issues that is being investigated)
