### PR TITLE
openstack: Forcibly detach an attached cinder volume before attaching elsewhere

### LINKED ISSUE #33288: Openstack cinder volumes not detached from downed vm when pod is rescheduled to another node.
**Kubernetes version** (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.1062+1070a518301f0b", GitCommit:"1070a518301f0bfb6f6c8832feff0bba0c391a22", GitTreeState:"clean", BuildDate:"2016-09-20T11:34:18Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Also tried with 1.3.6

**Environment**:
- **Cloud provider or hardware configuration**: openstack
- **OS** (e.g. from /etc/os-release): ubuntu 14.04
- **Kernel** (e.g. `uname -a`): 3.13.0-93-generic
- **Install tools**: deb package (not selfhosted)
- **Others**: May be related to #32716  #28643  #28671

**What happened**:
If compute instance with attached volume is downed (physical volume in kubernetes terms), kubernetes doesn't try to detach said volume (ever). End result is that k8s is trying to attach a volume in a loop but never succeeds because it is already attached to a downed node.  I've waited for more than an hour for the volume to be detached (didn't help :c)

**What you expected to happen**:
I expect controller-manager or kubelet to detach volume before trying to attach it to a new compute instance. 

**How to reproduce it** (as minimally and precisely as possible):
Bring up cluster with two nodes on openstack. Schedule pod with a pvc. Shutdown (from the command line on the operating system) the node with attached volume. Pod gets rescheduled to another node, but volume stays with the downed node.

**Anything else do we need to know**:
I've looked through reconcile.go on both kubelet and controller-manager it seems to me that once a node is downed it is no longer on the list of nodesManaged (in desired_state_of_world.go) so it's volume is never going to be detached. I've also tried to disable --enable-controller-attach-detach on a kubelet, but it doesn't try to detach it either.

### PR DESCRIPTION
**Pull request by anguslees**
Fixes #33288

**What this PR does / why we need it**:
Without this fix, we can't preemptively reschedule pods with persistent volumes to other hosts (for rebalancing or hardware failure recovery).

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #33288

**Special notes for your reviewer**:
(This is a resurrection/cleanup of PR #33734, originally authored by @Rotwang)

**Release note**:

### CODE REVIEW

**Comment by xrl** [comment]
How will this get moved in to a kubernetes release? I'm not familiar with the release process. @thockin @anguslees

**Comment by mikebryant** [comment]
We're finding this issue is a big problem for us on 1.5.2 - any chance of a cherry-pick to the 1.5 series?

**Comment by codablock** [comment]
Cherry picking this one should probably depend on cherry picking https://github.com/kubernetes/kubernetes/issues/39791#issuecomment-278155433 as well, as otherwise https://github.com/kubernetes/kubernetes/issues/39791 might hit you here.

File: pkg/cloudprovider/providers/openstack/openstack_volumes.go [hunk 1]
```diff
@@ -52,18 +52,21 @@ func (os *OpenStack) AttachDisk(instanceID string, diskName string) (string, err
...
 			glog.V(4).Infof("Disk: %q is already attached to compute: %q", diskName, instanceID)
 			return disk.ID, nil
-		} else {
-			errMsg := fmt.Sprintf("Disk %q is attached to a different compute: %q, should be detached before proceeding", diskName, disk.Attachments[0]["server_id"])
-			glog.Errorf(errMsg)
-			return "", errors.New(errMsg)
+		}
+
+		glog.V(2).Infof("Disk %q is attached to a different compute (%q), detaching", diskName, disk.Attachments[0]["server_id"])
+		err = os.DetachDisk(fmt.Sprintf("%s", disk.Attachments[0]["server_id"]), diskName)
```
Comment (johnw188) [inline pkg/cloudprovider/providers/openstack/openstack_volumes.go]: I'm not super familiar with the release process here but 100% agreed with @codablock that this should not be pulled into mainline kube in its current state. For an example, lets say you're doing a `kubectl delete` on a webserver that's mid transaction. My expected behavior would be for the volume to be available until my pod fully exits, so the server can complete its final set of transactions. With this patch it would lose access to its volumes the instant a new pod gets scheduled which could cause data loss.

I'd imagine there should be a check to the kube API before this detach call to verify that the volume is not in use by any active pods. If this check was added kube would simply keep retrying until the volume isn't in use, at which point it would detach and continue.

**Comment by xmik** [comment]
It seems it was released in [v1.6.0-alpha.1](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.1/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L58)
