### PR TITLE
kubelet: Fix race when KillPod followed by IsPodPendingTermination

### LINKED ISSUE #98953: kubelet: Race when KillPod followed by IsPodPendingTermination
**What happened**:

Right after calling `KillPod`, `IsPodPendingTerminationByUID` returns false even the pod is not killed yet.

**What you expected to happen**:

In kubelet, after `KillPod` is complete, the pod should be pending termination or be killed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Related to https://github.com/kubernetes/kubernetes/issues/98893

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by gjkim42**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

In kubelet, we can't consistently use `IsPodPendingTermination` and `KillPod` since there is a race condition.
When we call `KillPod`, the buffered channel receives the request and `KillPod` is returned. Then `PerformPodKillingWork` fetches the request and adds the given pod to the `terminationMap`. In the meantime, the caller may call `IsPodPendingTerminationByUID` which could return false because `terminationMap` has not yet been set.

This PR
1. ensures the pod to be pending termination or be killed, after `(*podKillerWithChannel).KillPod` has been returned
1. fixes `TestSyncPodsDeletesWhenSourcesAreReadyPerQOS` by simulating `Runtime.KillPod`

Related to https://github.com/kubernetes/kubernetes/issues/98893

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/98953

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
Could you please review this? Thanks :)
/cc @ehashman @rphillips

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -1249,40 +1247,55 @@ func (pk *podKillerWithChannel) checkAndMarkPodPendingTerminationByPod(podPair *
...
 	pk.podKillingCh <- pair
 }
 
 // PerformPodKillingWork launches a goroutine to kill a pod received from the channel if
 // another goroutine isn't already in action.
 func (pk *podKillerWithChannel) PerformPodKillingWork() {
+	killing := sets.NewString()
+	var lock sync.Mutex
 	for podPair := range pk.podKillingCh {
-		if pk.checkAndMarkPodPendingTerminationByPod(podPair) {
```
Comment (rphillips) [inline pkg/kubelet/kubelet_pods.go:1271]: checkAndMarkPodPendingTerminationByPod adds the pod to the killing mutex... Adding the mutex and set back to this function is effectively the same functionality as checkAndMarkPodPendingTerminationByPod

Comment (rphillips) [reply pkg/kubelet/kubelet_pods.go:1271]: Ahh. This synchronizes the killing goroutine on 1289.

**Comment by rphillips** [comment]
/lgtm cancel

I'm getting a deadlock with the TestSyncPodsDeletesWhenSourcesAreReadyPerQOS test

**Comment by rphillips** [comment]
My goal was to centralize the lock into the podTerminationMap and mirrorPodTerminationMap. Which effectively be the same thing as the killing Set

**Comment by gjkim42** [comment]
@rphillips 

> /lgtm cancel
> 
> I'm getting a deadlock with the TestSyncPodsDeletesWhenSourcesAreReadyPerQOS test

I think it is not a deadlock. It is a timeout.
There are two reasons for the time out,
1. Every `HandlePodCleanUp` calls `podKiller.KillPod` because `FakeRuntime.KillPod` does not clear `FakeRuntime.PodList` which is the list of pod to be killed by next `HandlePodCleanUp`. As a result, it is possible that every `HandlePodCleanUp` cannot call `Destroy` if the pod is pending termination for each call.
2. If 1 were resolved, All of `HandlePodCleanUp` cannot call `Destroy` if the is pod pending termination for more than 4 seconds.

**Comment by gjkim42** [comment]
```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v -test.cpu 1
23m15s: 3991 runs so far, 0 failures
```

```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v
23m45s: 4072 runs so far, 0 failures
```

**Review by gjkim42 — COMMENTED** [review]
@rphillips 

Limited to one `podPair` per pod in buffered channel.

**Comment by gjkim42** [comment]
```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v -test.cpu 1
25m10s: 4319 runs so far, 0 failures
```

```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v
24m35s: 4220 runs so far, 0 failures
```

File: pkg/kubelet/kubelet_pods.go [hunk 2]
```diff
@@ -1219,69 +1223,75 @@ func (pk *podKillerWithChannel) markPodTerminated(uid string) {
 	defer pk.podKillingLock.Unlock()
 	delete(pk.mirrorPodTerminationMap, uid)
 	delete(pk.podTerminationMap, uid)
+	pk.killingSet.Delete(uid)
```
[the remark this answers is not in the document]
Comment (gjkim42) [reply pkg/kubelet/kubelet_pods.go]: I think we don't need `killingSet` anymore because I have limited to one request per pod in buffered channel.

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (gjkim42) [reply pkg/kubelet/kubelet_pods.go:1277]: We don't have to check it here anymore because I have limited to one request per pod in buffered channel.

**Comment by gjkim42** [comment]
```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v -test.cpu 1
...
21m50s: 3752 runs so far, 0 failures
```

```bash
stress ./kubelet.test -test.run TestSyncPodsDeletesWhenSourcesAreReadyPerQOS -test.v
...
21m15s: 3648 runs so far, 0 failures
```

File: pkg/kubelet/kubelet_test.go [hunk 3]
```diff
@@ -442,7 +442,12 @@ func TestSyncPodsDeletesWhenSourcesAreReadyPerQOS(t *testing.T) {
 	time.Sleep(2 * time.Second)
 
 	// assert that unwanted pods were killed
-	fakeRuntime.AssertKilledPods([]string{"12345678"})
+	if err := fakeRuntime.AssertKilledPods([]string{"12345678"}); err != nil {
```
Comment (gjkim42) [inline pkg/kubelet/kubelet_test.go:445]: Maybe we need to wait if the goroutine of https://github.com/gjkim42/kubernetes/blob/082cc1002a771fc337567af9db164cb9ffaaa6e5/pkg/kubelet/kubelet_pods.go#L1275-L1282 isn't complete for 2 seconds. It can be a flake.

**Review by ehashman — COMMENTED** [review]
This seems okay to me and the test and explanation seem quite reasonable. But I don't have enough brain on a Friday afternoon to feel confident in this subtle fix, so holding off for Ryan or Seth to put an LGTM.

**Comment by gjkim42** [comment]
@rphillips @sjenning 
Could you review this again? Thanks.

**Comment by rphillips** [comment]
lgtm. I've asked @sjenning to take a look.

**Comment by sjenning** [comment]
/lgtm
/approve
thanks!
