### PR TITLE
Fix filter plugins are not been called during preemption

### LINKED ISSUE #81866: [Framework] Filter plugins are not been called during preemption
/sig scheduling

code reference: https://github.com/kubernetes/kubernetes/blob/f3816fb757732200a9357fd06241411de63a545a/pkg/scheduler/core/generic_scheduler.go

`genericScheduler.Preempt` calls directly `podFitsOnNode`, whereas `genericScheduler.Schedule` calls `podFitsOnNode` and later `framework.RunFilterPlugins`.

We need to make them consistent or move `framework.RunFilterPlugins` to `podFitsOnNode`.

I think that, with current behavior, since Filter plugins are not queried, it's like they are saying that any pod passes the filter during preemption.

/priority important-soon

### PR DESCRIPTION
**Pull request by wgliang**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81866

**Special notes for your reviewer**:
@alculquicondor 

**Does this PR introduce a user-facing change?**:

```release-note
Fix filter plugins are not been called during preemption
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

File: pkg/scheduler/core/generic_scheduler.go [hunk 1]
```diff
@@ -1121,7 +1136,7 @@ func selectVictimsOnNode(
 	// inter-pod affinity to one or more victims, but we have decided not to
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
-	if fits, _, err := podFitsOnNode(pod, meta, nodeInfoCopy, fitPredicates, queue, false); !fits {
+	if fits, _, err, _ := podFitsOnNode(pluginContext, pod, meta, nodeInfoCopy, fitPredicates, queue, false, filterPluginsFunc); !fits {
```
Comment (draveness) [inline pkg/scheduler/core/generic_scheduler.go]: I think the following is correct since the err is the last return value

```suggestion
	if fits, _, _, err := podFitsOnNode(pluginContext, pod, meta, nodeInfoCopy, fitPredicates, queue, false, filterPluginsFunc); !fits {
```

File: pkg/scheduler/core/generic_scheduler.go [hunk 2]
```diff
@@ -614,13 +612,15 @@ func addNominatedPods(pod *v1.Pod, meta predicates.PredicateMetadata,
...
 func podFitsOnNode(
+	pluginContext *framework.PluginContext,
 	pod *v1.Pod,
 	meta predicates.PredicateMetadata,
 	info *schedulernodeinfo.NodeInfo,
 	predicateFuncs map[string]predicates.FitPredicate,
 	queue internalqueue.SchedulingQueue,
 	alwaysCheckAllPredicates bool,
-) (bool, []predicates.PredicateFailureReason, error) {
+	filterPluginsFunc func(pc *framework.PluginContext, pod *v1.Pod, nodeName string) *framework.Status,
```
Comment (draveness) [inline pkg/scheduler/core/generic_scheduler.go]: why are you using the function as a parameter? what about the framework

File: pkg/scheduler/core/generic_scheduler.go [hunk 3]
```diff
@@ -992,13 +1002,16 @@ func pickOneNodeForPreemption(nodesToVictims map[*v1.Node]*schedulerapi.Victims)
...
+func selectNodesForPreemption(
+	pluginContext *framework.PluginContext,
+	pod *v1.Pod,
 	nodeNameToInfo map[string]*schedulernodeinfo.NodeInfo,
 	potentialNodes []*v1.Node,
 	fitPredicates map[string]predicates.FitPredicate,
 	metadataProducer predicates.PredicateMetadataProducer,
 	queue internalqueue.SchedulingQueue,
 	pdbs []*policy.PodDisruptionBudget,
+	filterPluginsFunc func(pc *framework.PluginContext, pod *v1.Pod, nodeName string) *framework.Status,
```
Comment (draveness) [inline pkg/scheduler/core/generic_scheduler.go]: same here

**Review by draveness — CHANGES_REQUESTED** [review]
cc/ @alculquicondor

File: pkg/scheduler/core/generic_scheduler.go [hunk 4]
```diff
@@ -525,7 +515,15 @@ func (g *genericScheduler) findNodesThatFit(pluginContext *framework.PluginConte
 				}
 			} else {
 				predicateResultLock.Lock()
-				failedPredicateMap[nodeName] = failedPredicates
+				if status != nil && !status.IsSuccess() {
```
Comment (draveness) [inline pkg/scheduler/core/generic_scheduler.go]: nit: `!status.IsSuccess()` won't panic even if the status is nil, please take a look at the implementation of `IsSuccess` function.

**Review by draveness — CHANGES_REQUESTED** [review]

**Comment by hex108** [comment]
As mentioned in [comment](https://github.com/kubernetes/kubernetes/issues/81866#issuecomment-524550075), how about converting `podFitsOnNode` to default filter plugin, then `genericScheduler.Preempt` calls `framework.RunFilterPlugins` instead of `podFitsOnNode`?

**Comment by draveness** [comment]
> As mentioned in [comment](https://github.com/kubernetes/kubernetes/issues/81866#issuecomment-524550075), how about converting `podFitsOnNode` to default filter plugin, then `genericScheduler.Preempt` calls `framework.RunFilterPlugins` instead of `podFitsOnNode`?

There could be a lot of compatible work to do since they are using two different error systems, and this PR is a fine approach to solve this issue IMO.

**Comment by draveness** [comment]
cc/ @alculquicondor

File: pkg/scheduler/core/generic_scheduler.go (hunk 1 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: done

File: pkg/scheduler/core/generic_scheduler.go (hunk 2 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Thanks @draveness 
IMO, from now on, it is sufficient to pass filterPluginsFunc, which seems to be better from the perspective of minimum function implementation and testing.

File: pkg/scheduler/core/generic_scheduler.go (hunk 4 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Sorry, I understand that you don't mean it. You mean that when the status is nil, calling `status.IsSusccess()` won't panic? 
`nil` is untyped, my understanding will get an error similar to `use of untyped nil` panic error.

If my understanding is wrong, please let me know. Thanks. :)

Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: > Sorry, I understand that you don't mean it. You mean that when the status is nil, calling `status.IsSusccess()` won't panic?

Please take a look at https://github.com/kubernetes/kubernetes/pull/81876/files#diff-c237cdd9e4cb201118ca380732d7f361L509

Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: I created a [snippet](https://play.golang.org/p/GYoTeiT5hFi) here which shows it won't cause panic.

```go
package main

import (
	"fmt"
)

type Status struct{}

func (s *Status) IsSuccess() bool {
	if s == nil {
		return true
	}
	return false
}

func main() {
	st := returnStatus()
	fmt.Println(st.IsSuccess())
}

func returnStatus() *Status {
	return nil
}
package main

import (
	"fmt"
)

type Status struct{}

func (s *Status) IsSuccess() bool {
	if s == nil {
		return true
	}
	return false
}

func main() {
	st := returnStatus()
	fmt.Println(st.IsSuccess())
}

func returnStatus() *Status {
	return nil
}

$ go run ...
true
```

Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: cool! I got it.

File: pkg/scheduler/core/generic_scheduler.go [hunk 5]
```diff
@@ -137,7 +137,7 @@ type ScheduleAlgorithm interface {
 	// the pod by preempting lower priority pods if possible.
 	// It returns the node where preemption happened, a list of preempted pods, a
 	// list of pods whose nominated node name should be removed, and error if any.
-	Preempt(*v1.Pod, error) (selectedNode *v1.Node, preemptedPods []*v1.Pod, cleanupNominatedPods []*v1.Pod, err error)
+	Preempt(*framework.PluginContext, *v1.Pod, error) (selectedNode *v1.Node, preemptedPods []*v1.Pod, cleanupNominatedPods []*v1.Pod, err error)
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler.go]: pod and then pluginContext? I prefer we are consistent with `Schedule`

File: pkg/scheduler/core/generic_scheduler.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler.go]: On the other hand, this approach has the following drawbacks:
- Harder to read, IDEs can't find all the references to Framewokr.RunFilterPlugins
- We have repeated code for the function prototype. Refactoring takes longer.

If we have a proper fake Framework, testing shouldn't be a problem. Also, we should prefer to test exported interfaces.

File: pkg/scheduler/core/generic_scheduler.go [hunk 6]
```diff
@@ -678,7 +678,17 @@ func podFitsOnNode(
...
 	}
 
-	return len(failedPredicates) == 0, failedPredicates, nil
+	if len(failedPredicates) != 0 {
+		return false, failedPredicates, nil, nil
+	}
+
+	// Iterate each plugin to verify current node
+	status := filterPluginsFunc(pluginContext, pod, info.Node().Name)
+	if !status.IsSuccess() {
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler.go]: This doesn't seem necessary. We can directly return, right?

File: pkg/scheduler/core/generic_scheduler.go [hunk 7]
```diff
@@ -1121,7 +1136,7 @@ func selectVictimsOnNode(
 	// inter-pod affinity to one or more victims, but we have decided not to
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
-	if fits, _, err := podFitsOnNode(pod, meta, nodeInfoCopy, fitPredicates, queue, false); !fits {
+	if fits, _, _, err := podFitsOnNode(pluginContext, pod, meta, nodeInfoCopy, fitPredicates, queue, false, filterPluginsFunc); !fits {
 		if err != nil {
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler.go]: what about status? That could be an error as well.

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 8]
```diff
@@ -1330,7 +1330,8 @@ func TestSelectNodesForPreemption(t *testing.T) {
 			newnode := makeNode("newnode", 1000*5, priorityutil.DefaultMemoryRequest*5)
 			newnode.ObjectMeta.Labels = map[string]string{"hostname": "newnode"}
 			nodes = append(nodes, newnode)
-			nodeToPods, err := selectNodesForPreemption(test.pod, nodeNameToInfo, nodes, test.predicates, PredicateMetadata, nil, nil)
+			pluginContext := framework.NewPluginContext()
+			nodeToPods, err := selectNodesForPreemption(pluginContext, test.pod, nodeNameToInfo, nodes, test.predicates, PredicateMetadata, nil, nil, func(pc *framework.PluginContext, pod *v1.Pod, nodeName string) *framework.Status { return nil })
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler_test.go]: Can we add a test for what we are adding? preemption when the filter plugins keep filtering the nodes.

File: pkg/scheduler/scheduler.go [hunk 9]
```diff
@@ -349,14 +349,14 @@ func (sched *Scheduler) schedule(pod *v1.Pod, pluginContext *framework.PluginCon
 // preempt tries to create room for a pod that has failed to schedule, by preempting lower priority pods if possible.
 // If it succeeds, it adds the name of the node where preemption has happened to the pod spec.
 // It returns the node name and an error if any.
-func (sched *Scheduler) preempt(fwk framework.Framework, preemptor *v1.Pod, scheduleErr error) (string, error) {
+func (sched *Scheduler) preempt(pluginContext *framework.PluginContext, fwk framework.Framework, preemptor *v1.Pod, scheduleErr error) (string, error) {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go]: the framework should be available in `sched.Framework`. Pass `pluginContext` as second argument to for consistency with `schedule`

File: pkg/scheduler/core/generic_scheduler.go (hunk 5 above)
Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: I prefer the keep the context as the first argument, there is a chance it would conform `context.Context`.

File: pkg/scheduler/core/generic_scheduler.go (hunk 2 above)
Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: > If we have a proper fake Framework, testing shouldn't be a problem. Also, we should prefer to test exported interfaces.

We do have a fakeFramework in scheduling_queue_test.go

File: pkg/scheduler/core/generic_scheduler.go (hunk 6 above)
Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: It would be more clear to seperate the good and base cases IMO

File: pkg/scheduler/core/generic_scheduler.go (hunk 5 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: @alculquicondor 
FYI:https://golang.org/pkg/context/
_The Context should be the first parameter_

File: pkg/scheduler/scheduler.go (hunk 9 above)
Comment (wgliang) [reply pkg/scheduler/scheduler.go]: Like the reply above, I actually prefer to update pass pluginContext as first argument with schedule.

Comment (wgliang) [reply pkg/scheduler/scheduler.go]: Sure :)

**Review by ahg-g — COMMENTED** [review]
Thanks for sending this PR, I took a quick look, I will take another look once the comments are addressed.

File: pkg/scheduler/core/generic_scheduler.go (hunk 2 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: @ahg-g Agree with you, one more parameter is really unnecessary, whether it is `framework` or `filterPluginsFunc`.

File: pkg/scheduler/core/generic_scheduler.go (hunk 6 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Thanks @ahg-g review. IMO, we need to return a bool type value to indicate whether the current node matches.

Because the results cannot be directly determined based on failedPredicates or err, this is because [L663](https://github.com/kubernetes/kubernetes/blob/de1cfa9bc16a08116b8f6b56929d3b1ea39fd1e3/pkg/scheduler/core/generic_scheduler.go#L663) and [L681](https://github.com/kubernetes/kubernetes/blob/de1cfa9bc16a08116b8f6b56929d3b1ea39fd1e3/pkg/scheduler/core/Generic_scheduler.go#L681). Indeed, we can check both len(failedPredicates) and err, but this undoubtedly brings complexity to the judgment. We need more readable and easy to understand processing logic.

File: pkg/scheduler/core/generic_scheduler.go [hunk 10]
```diff
@@ -678,7 +678,17 @@ func podFitsOnNode(
 		}
 	}
 
-	return len(failedPredicates) == 0, failedPredicates, nil
+	if len(failedPredicates) != 0 {
+		return false, failedPredicates, nil, nil
+	}
+
+	// Iterate each plugin to verify current node
+	status := filterPluginsFunc(pluginContext, pod, info.Node().Name)
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: I suggest a separate PR to complete this.

File: pkg/scheduler/core/generic_scheduler.go (hunk 5 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Ok. I will do that. :)

File: pkg/scheduler/core/generic_scheduler.go (hunk 7 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: DONE

File: pkg/scheduler/core/generic_scheduler.go [hunk 11]
```diff
@@ -525,7 +515,15 @@ func (g *genericScheduler) findNodesThatFit(pluginContext *framework.PluginConte
 				}
 			} else {
 				predicateResultLock.Lock()
-				failedPredicateMap[nodeName] = failedPredicates
+				if !status.IsSuccess() {
+					filteredNodesStatuses[nodeName] = status
+					if status.Code() != framework.Unschedulable {
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: DONE,Thanks!

File: pkg/scheduler/core/generic_scheduler.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Yeah！

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 12]
```diff
@@ -653,7 +653,7 @@ func TestGenericScheduler(t *testing.T) {
 				schedulerapi.DefaultPercentageOfNodesToScore,
 				false)
 			result, err := scheduler.Schedule(test.pod, framework.NewPluginContext())
-			if !reflect.DeepEqual(err, test.wErr) {
+			if err != nil && !reflect.DeepEqual(err, test.wErr) {
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: Because the returned err may be nil, otherwise reflect.DeepEqual(err, test.wErr) in test will panic.

File: pkg/scheduler/core/generic_scheduler.go [hunk 13]
```diff
@@ -1121,10 +1129,15 @@ func selectVictimsOnNode(
 	// inter-pod affinity to one or more victims, but we have decided not to
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
-	if fits, _, err := podFitsOnNode(pod, meta, nodeInfoCopy, fitPredicates, queue, false); !fits {
+	if fits, _, status, err := g.podFitsOnNode(pluginContext, pod, meta, nodeInfoCopy, fitPredicates, queue, false); !fits {
 		if err != nil {
 			klog.Warningf("Encountered error while selecting victims on node %v: %v", nodeInfo.Node().Name, err)
 		}
+
+		if !status.IsSuccess() {
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: There may be unschedulable here.

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 14]
```diff
@@ -1307,6 +1307,9 @@ func TestSelectNodesForPreemption(t *testing.T) {
 	labelKeys := []string{"hostname", "zone", "region"}
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
+			g := &genericScheduler{
+				framework: emptyFramework,
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: `TestSelectNodesForPreemption` mainly tests `selectNodesForPreemption`, so the empty framework does not seem to be necessary. However, I have changed to a non-empty framework. If I understand your comment, please let me know, thanks. :)

File: pkg/scheduler/core/generic_scheduler.go [hunk 15]
```diff
@@ -676,9 +671,19 @@ func podFitsOnNode(
...
+			return false, failedPredicates, status, status.AsError()
+		}
+	}
+
+	if len(failedPredicates) != 0 {
+		return false, failedPredicates, status, nil
 	}
 
-	return len(failedPredicates) == 0, failedPredicates, nil
+	return true, failedPredicates, status, nil
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: SGTM, DONE thanks！

File: pkg/scheduler/core/generic_scheduler.go [hunk 16]
```diff
@@ -676,9 +671,19 @@ func podFitsOnNode(
 				}
 			}
 		}
+
+		// Iterate each plugin to verify current node
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: DONE

File: pkg/scheduler/core/generic_scheduler.go [hunk 17]
```diff
@@ -525,7 +514,11 @@ func (g *genericScheduler) findNodesThatFit(pluginContext *framework.PluginConte
 				}
 			} else {
 				predicateResultLock.Lock()
-				failedPredicateMap[nodeName] = failedPredicates
+				if !status.IsSuccess() {
+					filteredNodesStatuses[nodeName] = status
+				} else {
+					failedPredicateMap[nodeName] = failedPredicates
+				}
```
[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler.go]: Fixed

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (mrkm4ntr) [reply pkg/scheduler/core/generic_scheduler_test.go]: > reflect.DeepEqual(err, test.wErr) in test will panic

No, it won't panic.
https://play.golang.org/p/nLXk5MDyc7k

[the remark this answers is not in the document]
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: In this line of code, I did get a null pointer error in my development environment, which is why I originally made this change. But I found that it doesn't exist now, so weird.

I have cancelled this change, thanks for all of you reminding me.

File: pkg/scheduler/core/generic_scheduler.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler.go]: My understanding is that these warnings are for actual errors. Also, if the filters failed, this conditional and the one about would both produce the same output, which is bad for troubleshooting when looking at logs.

**Review by alculquicondor — COMMENTED** [review]
I suggest to avoid forced pushes. It makes reviewing harder. Once a PR gets approved, the approver will ask you to squash/rebase.

File: pkg/scheduler/core/generic_scheduler.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler.go]: I agree, we shouldn't have this warning.

**Review by ahg-g — COMMENTED** [review]
I will take a second look once #82034 is merged, and this one is rebased to include the changes in #82034.

**Comment by ahg-g** [comment]
@k82cn can you please add milestone 1.16 for this one as well? this is a bug fix.

**Comment by alculquicondor** [comment]
You can rebase now

**Comment by wgliang** [comment]
> You can rebase now

Ok, done

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 8 above)
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go]: Did you work on this?

**Comment by alculquicondor** [comment]
Implementation LGTM. Let's just add the regression test.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 8 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: Sorry, I missed it. If I am not mistaken, the test case you are talking about is actually to confirm that the filter plugins are also executed when preemption occurs.

This does not seem to be a test case, but rather the number of times the filter plugins are executed.

I will check filterPlugin.numFilterCalled with the expected in TestSelectNodesForPreemption. What do you think of this?

Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go]: that sounds good. But you could also check that a plugin responds Unschedulable in the preemption phase and then the node is not returned in the list.

Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: DONE

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 18]
```diff
@@ -1119,14 +1119,31 @@ var startTime20190107 = metav1.Date(2019, 1, 7, 1, 1, 1, 0, time.UTC)
 // that podsFitsOnNode works correctly and is tested separately.
 func TestSelectNodesForPreemption(t *testing.T) {
 	defer algorithmpredicates.SetPredicatesOrderingDuringTest(order)()
+
+	filterPluginRegistry := framework.Registry{filterPlugin.Name(): NewFilterPlugin}
```
Comment (ahg-g) [inline pkg/scheduler/core/generic_scheduler_test.go]: we faced problems in the past when using shared variables for the plugin instances, it would be great if we can change the way we instantiate plugins to be similar to what we did in integration tests:

define a generic function for instantiation:
```
// newPlugin returns a plugin factory with specified Plugin.
func newPlugin(plugin framework.Plugin) framework.PluginFactory {
	return func(_ *runtime.Unknown, fh framework.FrameworkHandle) (framework.Plugin, error) {
		return plugin, nil
	}
}
```

and here, you can just do:
```
filterPlugin := &FilterPlugin{}
	registry := framework.Registry{filterPluginName: newPlugin(filterPlugin)}
```

The above should allow you to remove the global instance ```filterPlugin```

**Comment by guineveresaenger** [comment]
@ahg-g @alculquicondor @wgliang 

I'm the Release Lead Shadow for 1.16 release.

This is an outstanding 1.16 PR and needs to be merged before EOD Monday 9/9 in time for our rc cut.

It _looks_ like according to @ahg-g 's review that this isn't _actually_ marked `lgtm`? Can someone update with an expected time of completion? Thank you! ❤️

**Comment by alculquicondor** [comment]
> It _looks_ like according to @ahg-g 's review that this isn't _actually_ marked `lgtm`? Can someone update with an expected time of completion? Thank you!

Exactly, @wgliang is going to handle the latest minor suggestion

/lgtm cancel

**Comment by guineveresaenger** [comment]
do you have a reasonable notion of when thiswill be done, @alculquicondor? one thing that's missing is an Approver, it might be helpful to find someone so we can 🚢 it!

**Comment by ahg-g** [comment]
I can approve it.

File: pkg/scheduler/core/generic_scheduler.go (hunk 5 above)
Comment (draveness) [reply pkg/scheduler/core/generic_scheduler.go]: IMO we could accept this since we have already reached a consensus on conforming the Context in https://github.com/kubernetes/kubernetes/issues/81433 and https://github.com/kubernetes/kubernetes/pull/82072 is making the change.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 18 above)
Comment (wgliang) [reply pkg/scheduler/core/generic_scheduler_test.go]: DONE

**Comment by wgliang** [comment]
@ahg-g @alculquicondor 
Already updated all comments. Thank you for your review. :)

**Comment by ahg-g** [comment]
/lgtm
/approve
Thanks @wgliang

File: pkg/scheduler/scheduler.go (hunk 9 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go]: FYI, this is being handled in #82072

Comment (ahg-g) [reply pkg/scheduler/scheduler.go]: We should do this in a separate small PR because we don't know if #82072 will move forward or not, and if yes in what form, so it may take a little while to merge.
