### PR TITLE
Delete pod with uid as precondition.

### LINKED ISSUE #24937: Flake in node e2e: "Container Runtime Conformance Test container conformance blackbox test when running a container that terminates [It] it should be possible to delete [Conformance] "
```
Summarizing 1 Failure:

[Fail] Container Runtime Conformance Test container conformance blackbox test when running a container that terminates [It] it should be possible to delete [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:76

Ran 22 of 22 Specs in 1205.295 seconds
```

### LINKED ISSUE #25169: flake e2e node conformance test failure
>
23:49:35       Expected error:
23:49:35           <*errors.StatusError | 0xc82057fe00>: {
23:49:35               ErrStatus: {
23:49:35                   TypeMeta: {Kind: "Status", APIVersion: "v1"},
23:49:35                   ListMeta: {SelfLink: "", ResourceVersion: ""},
23:49:35                   Status: "Failure",
23:49:35                   Message: "pods \"busybox\" not found",
23:49:35                   Reason: "NotFound",
23:49:35                   Details: {Name: "busybox", Group: "", Kind: "pods", Causes: nil, RetryAfterSeconds: 0},
23:49:35                   Code: 404,
23:49:35               },
23:49:35           }
23:49:35           pods "busybox" not found
23:49:35       not to have occurred

[logs](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/2473)

### PR DESCRIPTION
**Pull request by Random-Liu**
Addressed https://github.com/kubernetes/kubernetes/issues/25169#issuecomment-217033202.

Fix #25169 
Fix #24937

This PR change status manager to delete pods with uid as a precondition, so that kubelet won't delete pods with different uid but the same name and namespace accidentally.

/cc @yujuhong

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM. Thanks.

File: pkg/kubelet/status/manager.go [hunk 1]
```diff
@@ -396,7 +396,12 @@ func (m *manager) syncPod(uid types.UID, status versionedPodStatus) {
 				glog.V(3).Infof("Pod %q is terminated, but some containers are still running", format.Pod(pod))
 				return
 			}
-			if err := m.kubeClient.Core().Pods(pod.Namespace).Delete(pod.Name, api.NewDeleteOptions(0)); err == nil {
+			// The delete options guaranteed that:
+			//   1. The pod should be deleted immediately
+			//   2. Only the pod with the same uid should be deleted. See #25169
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: This is obviously the right thing to do. Don't think we need to link the issue :-)
maybe change the comment to "Use the pod UID as the precondition for deletion to prevent deleting a newly created pod with the same name and namespace"

Comment (Random-Liu) [inline pkg/kubelet/status/manager.go]: ACK.

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments.

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Comment by Random-Liu** [comment]
Mark P1 to get rid of flakes.
