### PR TITLE
Fix: do not assign an empty value to the resource (CPU or memory) if it's not defined in the container

### LINKED ISSUE #117589: pod_status_manager_state: checkpoint is corrupted
### What happened?

After enabling In-Place Pod Vertical Scaling, if deploy a pod without setting memory (or cpu) request, kubelet will be failed at its second restart

### What did you expect to happen?

kubelet restart successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. start kubelet with In-Place Pod Vertical Scaling enabled
2. deploy a pod without setting memory request, e.g: 
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: nginx:1.24.0
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      requests:
        cpu: 100m
```
3. restart kubelet for the first time
4. restart kubelet for the second time
5. kubelet will fail with error: `panic: could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file "/var/lib/kubelet/pod_status_manager_state" before restarting Kubelet` 

### Anything else we need to know?

After deploying the pod, the following information is saved in the file `pod_status_manager_state`:

```
      "nginx": {
        "cpu": "100m"
      }
```
Then restart kubelet for the first time, the relevant content in the file becomes: 
```
      "nginx": {
        "cpu": "100m",
        "memory": "0"
      }
```
------
When deploying the pod, as there are no records in the checkpoint (`pod_status_manager_state`), kubelet will get resource config from `pod.Spec.Container.Resources`  directly and save it to the checkpoint (without memory request)
https://github.com/kubernetes/kubernetes/blob/3125009dd1ebdde499a810110ba1f6d3fb05698f/pkg/kubelet/kubelet.go#L2504-L2521
When restarting kubelet for the first time, it will restore the previously saved data from the checkpoint. Since the memory request was not previously set, it will be set to an empty value and resaved to the checkpoint
https://github.com/kubernetes/kubernetes/blob/3125009dd1ebdde499a810110ba1f6d3fb05698f/pkg/kubelet/kubelet.go#L2508-L2514
When restarting kubelet for the second time, it will process `memory: 0` as a value of 0 (not empty), which resulting in the inconsistency between the calculated checksum during data recovery and the previous one

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aheng-ch**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/117589

#### Does this PR introduce a user-facing change?

```release-note
Do not assign an empty value to the resource (CPU or memory) that not defined when stores the resources allocated to the pod in checkpoint
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by gjkim42 — COMMENTED** [review]
Can we add some tests for this?

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2508,8 +2512,12 @@ func (kl *Kubelet) HandlePodAdditions(pods []*v1.Pod) {
...
 					if c.Resources.Requests != nil && found {
-						c.Resources.Requests[v1.ResourceCPU] = allocatedResources[v1.ResourceCPU]
-						c.Resources.Requests[v1.ResourceMemory] = allocatedResources[v1.ResourceMemory]
+						if _, ok := allocatedResources[v1.ResourceCPU]; ok {
+							c.Resources.Requests[v1.ResourceCPU] = allocatedResources[v1.ResourceCPU]
+						}
+						if _, ok := allocatedResources[v1.ResourceMemory]; ok {
+							c.Resources.Requests[v1.ResourceMemory] = allocatedResources[v1.ResourceMemory]
+						}
 					}
```
Comment (bart0sh) [inline pkg/kubelet/kubelet.go:2521]: It looks like it's a good time to wrap this  duplicated code into a function.

Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2521]: +1. Looks good otherwise.

Comment (aheng-ch) [reply pkg/kubelet/kubelet.go]: Updated. PTAL @bart0sh @vinaykul

**Comment by aheng-ch** [comment]
> @aheng-ch Since this is a bugfix please update or add unit or e2e test to ensure the bug is fixed.
Added a UT

File: pkg/kubelet/kubelet_test.go [hunk 2]
```diff
@@ -2437,6 +2438,155 @@ func TestHandlePodAdditionsInvokesPodAdmitHandlers(t *testing.T) {
...
+			podResourceAllocationExist: true,
+			expectedPodResourceAllocation: state.PodResourceAllocation{
+				"8": map[string]v1.ResourceList{
+					emptyPodSpec.Containers[0].Name: emptyPodSpec.Containers[0].Resources.Requests,
+				},
+			},
+		},
+	}
+	for _, tc := range tests {
+		if tc.podResourceAllocationExist {
```
Comment (vinaykul) [inline pkg/kubelet/kubelet_test.go:2573]: Can I ask for one small change? Could you please set the allocation to a value (cpu only, mem only, cpu and mem) that is different from the value in tc.pod and adjust expected accordingly? This will test the cases where `desired != allocated`

**Comment by bart0sh** [comment]
@aheng-ch please provide release note

**Comment by aheng-ch** [comment]
> @aheng-ch please provide release note

Added

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -2535,6 +2525,22 @@ func (kl *Kubelet) HandlePodAdditions(pods []*v1.Pod) {
...
+func (kl *Kubelet) updateContainerResourceAllocation(pod *v1.Pod) {
+	for _, c := range pod.Spec.Containers {
+		allocatedResources, found := kl.statusManager.GetContainerResourceAllocation(string(pod.UID), c.Name)
+		if c.Resources.Requests != nil && found {
+			if _, ok := allocatedResources[v1.ResourceCPU]; ok {
+				c.Resources.Requests[v1.ResourceCPU] = allocatedResources[v1.ResourceCPU]
+			}
+			if _, ok := allocatedResources[v1.ResourceMemory]; ok {
+				c.Resources.Requests[v1.ResourceMemory] = allocatedResources[v1.ResourceMemory]
+			}
```
Comment (bart0sh) [inline pkg/kubelet/kubelet.go:2539]: Would it make sense to set requests values from checkpoint so we don't have different data in the checkpoint and in the c.Resources.Requests? Alternatively we can save/restore data to/from checkpoint in a bit smarter way so that if memory or cpu is not requested it will not be saved and restored?

Not 100% sure it makes sense, but this difference between checkpoint and memory data is a bit concerning.

@vinaykul @SergeyKanzhelev @aheng-ch WDYT?

Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2539]: @bart0sh GetContainerResourceAllocation reads from checkpoint **because** the Requests and checkpoint values (what kubelet agreed to at a prior point) can differ. Did I miss something?

Comment (bart0sh) [reply pkg/kubelet/kubelet.go:2539]: sorry, this PR somehow slipped off my radar. I was thinking that some fields with `nil` value can be converted to empty lists before checkpointing them, so when they're read from a checkpoint we don't need to check if they're nil.

**Comment by wenzhaojie** [comment]
As of now, the latest version officially released is 1.28.0. I found that as long as the feature gate of InPlacePodVPA is turned on, restarting the cluster nodes will cause the kubelet to fail to start normally. Can this pr fix this problem?

**Comment by LingyanYin** [comment]
We used Inplace VPA in our product, and  @LastNight1997 also found this issue
We reviewed the code, and it looks good cc @Jeffwan

**Comment by LastNight1997** [comment]
We've merged this PR into our branch and it looks to be working fine in our production environment.

**Comment by wenzhaojie** [comment]
> We've merged this PR into our branch and it looks to be working fine in our production environment.

What do you mean？Does this PR no longer needed?

**Comment by LastNight1997** [comment]
@wenzhaojie No, I means that this PR is working well in our environment, and suggest it can be merged.

**Review by vinaykul — APPROVED** [review]

**Review by mrunalp — APPROVED** [review]
