### PR TITLE
disruptioncontroller: check for scale subresource correctly

### LINKED ISSUE #109954: CalculateExpectedPodCountFailed events occur intermittently on supported resources.
### What happened?

We frequently see events on PodDisruptionBudgets consisting of: 
```
reason=CalculateExpectedPodCountFailed message=Failed to calculate the number of expected pods: replicasets.apps does not implement the scale subresource
```

As stated in the [API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#read-scale-replicaset-v1-apps), replicasets.apps clearly does implement the scale subresource.

### What did you expect to happen?

CalculateExpectedPodCountFailed events not to occur.

### How can we reproduce it (as minimally and precisely as possible)?

It seems to be an intermittent error, I believe it is a race condition that occurs when a Deployment is progressing and a replicaset and its pods are being deleted.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EC2
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux ip-172-16-114-137.us-west-2.compute.internal 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by adammw**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Updates the logic which checks if a resource implements the scale subresource to look for the main resource first, then find the scale subresource from that, expecting an autoscaling/v1 Scale Kind rather than the main resource Kind.

Without this, core API types are listed as not supporting the Scale subresource when they in fact do.

#### Which issue(s) this PR fixes:

Partially addresses #109954, in that it will not produce the incorrect error message that "replicasets.apps does not implement the scale subresource", however does not fix the cause of the race condition and an error will still occur after this PR.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/disruption/disruption.go [hunk 1]
```diff
@@ -326,12 +326,29 @@ func (dc *DisruptionController) implementsScale(gv schema.GroupVersion, kind str
 	if err != nil {
 		return false, err
 	}
+
+	var subresourceName string
 	for _, resource := range resourceList.APIResources {
-		if resource.Kind != kind {
+		if resource.Kind == kind {
+			subresourceName = fmt.Sprintf("%s/scale", resource.Name)
```
Comment (FillZpp) [inline pkg/controller/disruption/disruption.go:333]: We'd better check if the `resource.Name` contains "/" to avoid generating `subresourceName` like `{Kind}/status/scale` (even if it seems apiserver will put the sub resources behind their main resource in the `APIResources` list).

Comment (adammw) [reply pkg/controller/disruption/disruption.go:333]: good catch, will add an extra guard and reorder the test to account for that

**Comment by FillZpp** [comment]
/lgtm
This fixes `implementsScale` from #98346 .
/cc @soltysh @liggitt

File: pkg/controller/disruption/disruption.go [hunk 2]
```diff
@@ -326,12 +326,29 @@ func (dc *DisruptionController) implementsScale(gv schema.GroupVersion, kind str
 	if err != nil {
```
Comment (liggitt) [inline pkg/controller/disruption/disruption.go:326]: rather than passing in the `kind` and trying to locate the scale subresource, pass in the resource name from the GroupResource we used to make the scale API request, and look for `gr.Resource + "/scale"` in discovery

Comment (adammw) [reply pkg/controller/disruption/disruption.go:325]: Updated. Now relies on the RESTMapper getting the right `Kind` -> `Resource` translation and then asserts the scale subresource data format matches the expected scale formats.

File: pkg/controller/disruption/disruption.go [hunk 3]
```diff
@@ -321,17 +320,24 @@ func (dc *DisruptionController) getScaleController(ctx context.Context, controll
...
+	scaleSubresourceName := fmt.Sprintf("%s/scale", gvr.Resource)
 	for _, resource := range resourceList.APIResources {
-		if resource.Kind != kind {
+		if resource.Name != scaleSubresourceName {
 			continue
 		}
-		if strings.HasSuffix(resource.Name, "/scale") {
-			return true, nil
+
+		for _, scaleGv := range scaleclient.NewScaleConverter().ScaleVersions() {
```
Comment (liggitt) [inline pkg/controller/disruption/disruption.go:335]: add a unit test case that exercises a `.../scale` subresource that is not one of the recognized Scale types?

File: pkg/controller/disruption/disruption.go (hunk 2 above)
Comment (liggitt) [reply pkg/controller/disruption/disruption.go:325]: much cleaner / simpler, thanks

**Comment by liggitt** [comment]
logic looks good. one request for a test case, then lgtm
