### PR TITLE
kubelet: ensure stable order for images in node status

### LINKED ISSUE #79577: kubelet: Images with the same size on a node do not have a stable order
**What happened**:

When two or more images on a given node have the same size, their order inside the `node.status.images` field set by the `kubelet` process is not deterministic.

This problem has the side effect of continually triggering controllers which assume this list to be always equal on node updates unless images are added or removed.

**What you expected to happen**:

The order of images should be stable even when two images have the same size, using the image ID as a second sort field would help this.

**How to reproduce it (as minimally and precisely as possible)**:

Choose a node and run:

```
docker commit $(docker create busybox) busybox2
```

Run a few times:

```
kubectl get node <chosen node> -o yaml | grep busybox
```

It should be possible to see `busybox` and `busybox2` images alternating on the output.

**Anything else we need to know?**:

Our particular use case make it really common for multiple images to have the same size on a given node. I came across this problem while debugging slow updates to DaemonSets and finding out that the kube-controller-manager was leaking memory until it eventually dies due to OOM:

Screen Shot 2019-06-30 at 20 27 22

I was able to track this leak to a large number of watched elements in memory and by taking a look at the logs with increased verbosity I figured it was due to too many Node notifications being processed by the DaemonSet controller:

Screen Shot 2019-06-30 at 20 36 23

It's possible that other controllers in the wild that watch nodes and only ignore the conditions timestamps on updates to face the same problem.

I'll send a simple PR to fix this shortly.

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.9", GitCommit:"e09f5c40b55c91f681a46ee17f9bc447eeacee57", GitTreeState:"clean", BuildDate:"2019-05-27T15:58:45Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

But by taking a look at the code this problem also happens on master.

### PR DESCRIPTION
**Pull request by cezarsa**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR uses the image ID alongside the image size as part of the sort function to ensure a stable order for the `node.status.images` field even for images with the same size.

When two or more images on the same node have the same size, their order in the `node.status.images` field was not stable. As shown in #79577 a large number of nodes with this problem could become problematic to controllers due to apparent changes to the node.

**Which issue(s) this PR fixes**:
Fixes #79577

**Special notes for your reviewer**:

I wasn't sure about renaming the type from `ByImageSize` to something like `ByImageSizeAndID` in the end I left it as is. Please let me know if you think it would be better to rename it.

/sig node

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/util/sliceutils/sliceutils.go [hunk 1]
```diff
@@ -53,6 +53,9 @@ func (s PodsByCreationTime) Less(i, j int) bool {
 type ByImageSize []kubecontainer.Image
 
 func (a ByImageSize) Less(i, j int) bool {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/util/sliceutils/sliceutils.go]: Do we have unit testing for this function? If not, could we add it? If yes, could we update it to capture this new use case?

File: pkg/kubelet/util/sliceutils/sliceutils.go [hunk 2]
```diff
@@ -53,6 +53,9 @@ func (s PodsByCreationTime) Less(i, j int) bool {
 type ByImageSize []kubecontainer.Image
```
Comment (mattjmcnaughton) [inline pkg/kubelet/util/sliceutils/sliceutils.go]: I think I'm fine with us keeping `ByImageSize` as the name... in my mind, that's the "public" behavior we care about... the ID tie-breaker feels like an implementation detail.

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Thanks for this fix!

I think this is on a great path. Please ping me once you add unit testing and I'll add the `lgtm` label. 

One quick note - re the release note. Please include it in a code block, i.e.:

```release-note
NONE
```

File: pkg/kubelet/util/sliceutils/sliceutils.go (hunk 1 above)
Comment (cezarsa) [reply pkg/kubelet/util/sliceutils/sliceutils.go]: Unit test added.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for updating the tests.

**Comment by cezarsa** [comment]
Pinging @yujuhong for approval.
