### PR TITLE
Fix `PodScheduled` bug for static pod.

### LINKED ISSUE #60589: [test flakes] master-scalability suites
Failing release-blocking suites:
- [x] https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-correctness
- [x] https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-100
- [x] https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance

all three suites are flaking a lot recently, mind triage?

/sig scalability
/priority failing-test
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus 
/assign @shyamjvs @wojtek-t

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/kubernetes/kubernetes/issues/60589.

This is an implementation of option 2 in https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-375103979.
I've validated this in my own cluster, and there won't be continuously status update for static pod any more.

Signed-off-by: Lantao Liu <lantaol@google.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by Random-Liu** [comment]
Here is the kubelet log, and we can see that status for `kube-proxy` is only updated once.
```
I0321 22:30:41.194634   27534 status_manager.go:471] ================== Update status for pod "kube-proxy-kubernetes-minion-group-47nr_kube-system(c29c0921-2d47-11e8-8fea-42010af00003)": (1, {Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-20 09:20:13 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 20:38:07 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 22:30:38 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.240.0.7 PodIP:10.240.0.7 StartTime:2018-03-20 09:20:13 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:kube-proxy State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2018-03-21 20:38:07 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/kube-proxy:v1.10.0-beta.0.924_07240b7166d83b-dirty ImageID:sha256:ecb104d562a74444a05950578d622f3e70cb8d03514ced2fc8d05e4204c2aa69 ContainerID:containerd://3b22f114f26336426fd2614d88918e331e6f34a0cd51aa4ac64755e451d6c392}] QOSClass:Burstable})
...
I0321 22:30:46.345465   27534 server.go:796] GET /healthz: (52.015µs) 200 [[curl/7.56.1] 127.0.0.1:43070]
W0321 22:30:46.845813   27534 prober.go:103] No ref for container "containerd://de3ca97e2cd91462e528934e24e241adba2564929c2886d994d780476ca58068" (fluentd-gcp-v3.0.0-9cfgt_kube-system(2c64b0f4-2c20-11e8-8fea-42010af00003):fluentd-gcp)
I0321 22:30:46.846298   27534 prober.go:111] Liveness probe for "fluentd-gcp-v3.0.0-9cfgt_kube-system(2c64b0f4-2c20-11e8-8fea-42010af00003):fluentd-gcp" failed (failure):
I0321 22:30:48.574493   27534 kubelet_node_status.go:422] Recording NodeReady event message for node kubernetes-minion-group-47nr
I0321 22:30:56.357070   27534 server.go:796] GET /healthz: (25.345µs) 200 [[curl/7.56.1] 127.0.0.1:43122]
I0321 22:31:05.177880   27534 server.go:796] GET /stats/summary/: (120.738954ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:31:05.232772   27534 server.go:796] GET /stats/summary/: (80.016964ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:31:06.369159   27534 server.go:796] GET /healthz: (24.365µs) 200 [[curl/7.56.1] 127.0.0.1:43152]
I0321 22:31:16.383658   27534 server.go:796] GET /healthz: (50.854µs) 200 [[curl/7.56.1] 127.0.0.1:43168]
I0321 22:31:26.393437   27534 server.go:796] GET /healthz: (25.394µs) 200 [[curl/7.56.1] 127.0.0.1:43182]
I0321 22:31:36.405931   27534 server.go:796] GET /healthz: (23.661µs) 200 [[curl/7.56.1] 127.0.0.1:43196]
I0321 22:31:46.417353   27534 server.go:796] GET /healthz: (22.056µs) 200 [[curl/7.56.1] 127.0.0.1:43210]
I0321 22:31:56.428645   27534 server.go:796] GET /healthz: (26.363µs) 200 [[curl/7.56.1] 127.0.0.1:43226]
I0321 22:32:05.070636   27534 server.go:796] GET /stats/summary/: (49.885711ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:32:05.111837   27534 server.go:796] GET /stats/summary/: (58.64164ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:32:06.436132   27534 server.go:796] GET /healthz: (22.744µs) 200 [[curl/7.56.1] 127.0.0.1:43242]
I0321 22:32:16.443933   27534 server.go:796] GET /healthz: (33.88µs) 200 [[curl/7.56.1] 127.0.0.1:43258]
I0321 22:32:26.451497   27534 server.go:796] GET /healthz: (24.873µs) 200 [[curl/7.56.1] 127.0.0.1:43272]
I0321 22:32:36.459397   27534 server.go:796] GET /healthz: (22.564µs) 200 [[curl/7.56.1] 127.0.0.1:43288]
I0321 22:32:46.467466   27534 server.go:796] GET /healthz: (24.696µs) 200 [[curl/7.56.1] 127.0.0.1:43302]
I0321 22:32:56.475586   27534 server.go:796] GET /healthz: (23.687µs) 200 [[curl/7.56.1] 127.0.0.1:43316]
I0321 22:33:05.125205   27534 server.go:796] GET /stats/summary/: (74.077704ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:33:05.224966   27534 server.go:796] GET /stats/summary/: (70.418427ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:33:06.484713   27534 server.go:796] GET /healthz: (24.476µs) 200 [[curl/7.56.1] 127.0.0.1:43332]
I0321 22:33:16.492405   27534 server.go:796] GET /healthz: (49.061µs) 200 [[curl/7.56.1] 127.0.0.1:43348]
I0321 22:33:26.501703   27534 server.go:796] GET /healthz: (25.152µs) 200 [[curl/7.56.1] 127.0.0.1:43362]
I0321 22:33:36.512540   27534 server.go:796] GET /healthz: (48.769µs) 200 [[curl/7.56.1] 127.0.0.1:43376]
I0321 22:33:46.523107   27534 server.go:796] GET /healthz: (22.709µs) 200 [[curl/7.56.1] 127.0.0.1:43392]
I0321 22:33:56.531935   27534 server.go:796] GET /healthz: (23.723µs) 200 [[curl/7.56.1] 127.0.0.1:43406]
I0321 22:34:05.048744   27534 server.go:796] GET /stats/summary/: (42.792833ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:34:05.101640   27534 server.go:796] GET /stats/summary/: (46.267861ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:34:06.542764   27534 server.go:796] GET /healthz: (24.343µs) 200 [[curl/7.56.1] 127.0.0.1:43422]
I0321 22:34:16.556412   27534 server.go:796] GET /healthz: (18.607µs) 200 [[curl/7.56.1] 127.0.0.1:43438]
I0321 22:34:26.564219   27534 server.go:796] GET /healthz: (18.175µs) 200 [[curl/7.56.1] 127.0.0.1:43452]
I0321 22:34:36.571836   27534 server.go:796] GET /healthz: (36.56µs) 200 [[curl/7.56.1] 127.0.0.1:43466]
I0321 22:34:46.582761   27534 server.go:796] GET /healthz: (153.236µs) 200 [[curl/7.56.1] 127.0.0.1:43480]
I0321 22:34:56.596202   27534 server.go:796] GET /healthz: (78.601µs) 200 [[curl/7.56.1] 127.0.0.1:43496]
I0321 22:35:05.208022   27534 server.go:796] GET /stats/summary/: (57.712134ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:35:05.223007   27534 server.go:796] GET /stats/summary/: (55.662438ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:35:06.603562   27534 server.go:796] GET /healthz: (18.759µs) 200 [[curl/7.56.1] 127.0.0.1:43512]
I0321 22:35:16.610862   27534 server.go:796] GET /healthz: (19.071µs) 200 [[curl/7.56.1] 127.0.0.1:43526]
I0321 22:35:26.618365   27534 server.go:796] GET /healthz: (18.622µs) 200 [[curl/7.56.1] 127.0.0.1:43542]
I0321 22:35:36.627461   27534 server.go:796] GET /healthz: (24.728µs) 200 [[curl/7.56.1] 127.0.0.1:43556]
I0321 22:35:46.637225   27534 server.go:796] GET /healthz: (24.358µs) 200 [[curl/7.56.1] 127.0.0.1:43570]
I0321 22:35:56.644759   27534 server.go:796] GET /healthz: (25.729µs) 200 [[curl/7.56.1] 127.0.0.1:43584]
I0321 22:36:05.231005   27534 server.go:796] GET /stats/summary/: (106.511197ms) 200 [[Go-http-client/1.1] 10.64.2.5:36602]
I0321 22:36:05.271887   27534 server.go:796] GET /stats/summary/: (121.351428ms) 200 [[Go-http-client/1.1] 10.64.2.4:43002]
I0321 22:36:06.652245   27534 server.go:796] GET /healthz: (19.677µs) 200 [[curl/7.56.1] 127.0.0.1:43602]
```

Here is the kubelet.log without this fix:
```
...
I0321 22:28:13.614078   15035 status_manager.go:471] ================== Update status for pod "kube-proxy-kubernetes-minion-group-47nr_kube-system(c29c0921-2d47-11e8-8fea-42010af00003)": (90, {Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-20 09:20:13 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 20:38:07 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 22:28:13 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.240.0.7 PodIP:10.240.0.7 StartTime:2018-03-20 09:20:13 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:kube-proxy State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2018-03-21 20:38:07 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/kube-proxy:v1.10.0-beta.0.924_07240b7166d83b-dirty ImageID:sha256:ecb104d562a74444a05950578d622f3e70cb8d03514ced2fc8d05e4204c2aa69 ContainerID:containerd://3b22f114f26336426fd2614d88918e331e6f34a0cd51aa4ac64755e451d6c392}] QOSClass:Burstable})
I0321 22:28:16.199808   15035 server.go:796] GET /healthz: (19.249µs) 200 [[curl/7.56.1] 127.0.0.1:42824]
I0321 22:28:26.207674   15035 server.go:796] GET /healthz: (23.997µs) 200 [[curl/7.56.1] 127.0.0.1:42838]
I0321 22:28:36.215735   15035 server.go:796] GET /healthz: (34.876µs) 200 [[curl/7.56.1] 127.0.0.1:42854]
I0321 22:28:46.222985   15035 server.go:796] GET /healthz: (33.031µs) 200 [[curl/7.56.1] 127.0.0.1:42868]
I0321 22:28:56.230789   15035 server.go:796] GET /healthz: (19.98µs) 200 [[curl/7.56.1] 127.0.0.1:42886]
I0321 22:29:05.106764   15035 server.go:796] GET /stats/summary/: (56.409529ms) 200 [[Go-http-client/1.1] 10.64.2.4:36246]
I0321 22:29:05.111483   15035 server.go:796] GET /stats/summary/: (60.813303ms) 200 [[Go-http-client/1.1] 10.64.2.5:58078]
I0321 22:29:06.238982   15035 server.go:796] GET /healthz: (27.4µs) 200 [[curl/7.56.1] 127.0.0.1:42902]
I0321 22:29:16.247392   15035 server.go:796] GET /healthz: (23.56µs) 200 [[curl/7.56.1] 127.0.0.1:42916]
I0321 22:29:17.609658   15035 status_manager.go:471] ================== Update status for pod "kube-proxy-kubernetes-minion-group-47nr_kube-system(c29c0921-2d47-11e8-8fea-42010af00003)": (91, {Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-20 09:20:13 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 20:38:07 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 22:29:17 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.240.0.7 PodIP:10.240.0.7 StartTime:2018-03-20 09:20:13 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:kube-proxy State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2018-03-21 20:38:07 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/kube-proxy:v1.10.0-beta.0.924_07240b7166d83b-dirty ImageID:sha256:ecb104d562a74444a05950578d622f3e70cb8d03514ced2fc8d05e4204c2aa69 ContainerID:containerd://3b22f114f26336426fd2614d88918e331e6f34a0cd51aa4ac64755e451d6c392}] QOSClass:Burstable})
I0321 22:29:26.258076   15035 server.go:796] GET /healthz: (55.776µs) 200 [[curl/7.56.1] 127.0.0.1:42930]
I0321 22:29:36.272203   15035 server.go:796] GET /healthz: (585.961µs) 200 [[curl/7.56.1] 127.0.0.1:42944]
I0321 22:29:46.281676   15035 server.go:796] GET /healthz: (27.557µs) 200 [[curl/7.56.1] 127.0.0.1:42958]
I0321 22:29:56.290874   15035 server.go:796] GET /healthz: (263.145µs) 200 [[curl/7.56.1] 127.0.0.1:42972]
I0321 22:30:05.139097   15035 server.go:796] GET /stats/summary/: (130.318564ms) 200 [[Go-http-client/1.1] 10.64.2.5:58078]
I0321 22:30:05.159130   15035 server.go:796] GET /stats/summary/: (151.304378ms) 200 [[Go-http-client/1.1] 10.64.2.4:36246]
I0321 22:30:06.303150   15035 server.go:796] GET /healthz: (25.255µs) 200 [[curl/7.56.1] 127.0.0.1:42992]
I0321 22:30:16.311042   15035 server.go:796] GET /healthz: (27.496µs) 200 [[curl/7.56.1] 127.0.0.1:43006]
I0321 22:30:26.322578   15035 server.go:796] GET /healthz: (26.58µs) 200 [[curl/7.56.1] 127.0.0.1:43020]
I0321 22:30:27.610688   15035 status_manager.go:471] ================== Update status for pod "kube-proxy-kubernetes-minion-group-47nr_kube-system(c29c0921-2d47-11e8-8fea-42010af00003)": (92, {Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-20 09:20:13 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 20:38:07 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-03-21 22:30:27 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.240.0.7 PodIP:10.240.0.7 StartTime:2018-03-20 09:20:13 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:kube-proxy State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2018-03-21 20:38:07 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/kube-proxy:v1.10.0-beta.0.924_07240b7166d83b-dirty ImageID:sha256:ecb104d562a74444a05950578d622f3e70cb8d03514ced2fc8d05e4204c2aa69 ContainerID:containerd://3b22f114f26336426fd2614d88918e331e6f34a0cd51aa4ac64755e451d6c392}] QOSClass:Burstable})
...
```

**Comment by yujuhong** [comment]
The condition will be reset once kubelet restarts. 

If we really want to do this, we should follow the convention of setting the transition time in the status manager.

**Comment by Random-Liu** [comment]
@yujuhong proposed a new fix, which is cleaner and smaller. :)

I tried it and it works. I've updated the PR. PTAL.

**Comment by jdumars** [comment]
@yujuhong if this looks good, could you LGTM it?

File: pkg/kubelet/status/status_manager.go [hunk 1]
```diff
@@ -337,6 +337,17 @@ func (m *manager) updateStatusInternal(pod *v1.Pod, status v1.PodStatus, forceUp
 		initCondition.LastTransitionTime = lastTransitionTime
 	}
 
+	// Set PodScheduledCondition.LastTransitionTime.
```
Comment (yujuhong) [inline pkg/kubelet/status/status_manager.go]: nit: There's a lot of copy-pasting happening here. Should we just factor this out as a function?

Comment (yujuhong) [reply pkg/kubelet/status/status_manager.go]: Otherwise, the code lgtm

Comment (Random-Liu) [reply pkg/kubelet/status/status_manager.go]: Done

**Comment by wojtek-t** [comment]
/hold

Before merging, I would like to first confirm that it really help:
https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-375203351

**Comment by yujuhong** [comment]
> Before merging, I would like to first confirm that it really help:
> #60589 (comment)

Removed the hold since this has been confirmed.

**Comment by wojtek-t** [comment]
> Removed the hold since this has been confirmed.

I was waiting for results of second run by @shyamjvs but I'm fine with that.
This needs to be cherrypicked to 1.10 branch. @jdumars

**Comment by shyamjvs** [comment]
FYI - the second run was also fine - https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-375350217

**Comment by jdumars** [comment]
@dims is going to generate the cherry pick

**Comment by shyamjvs** [comment]
Not sure why, the bazel presubmit seems stuck for a long time.

/retest

**Comment by dims** [comment]
i did a `/test all` which seems to have successfully re-triggered all the tests - https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&pull=61504 - hope it works this time

**Comment by dims** [comment]
@Random-Liu seems to be running into trouble with `pull-kubernetes-e2e-gce` persistently. Can you please check?

/test pull-kubernetes-e2e-gce
