### PR TITLE
kubeadm: change the default bootstrap token TTL to 24 hours

### LINKED ISSUE #343: `kubeadm init` should default to a finite token TTL
## Versions

**kubeadm version** (use `kubeadm version`): <= 1.7

## What happened?
`kubeadm init` created a default token with infinite TTL.

## What you expected to happen?
`kubeadm` creates a token with limited (2 hour?) TTL by default

## How to reproduce it (as minimally and precisely as possible)?
Run `kubeadm init` without specifying the `--token-ttl` parameter.

## Anything else we need to know?
This was discussed in SIG-cluster-lifecycle earlier today. It should be a trivial fix if we agree on the new default.

cc @jbeda @luxas

### PR DESCRIPTION
**Pull request by mattmoyer**
**What this PR does / why we need it**:
This PR changes the TTL for the default bootstrap token generated by `kubeadm init` (without the `--token-ttl` parameter) and `kubeadm token create` (without the `--ttl` flag). Previously, the default TTL was infinite. After this change it is 24 hours.

~~The reasoning for 2 hours as a default is that it's 1) long enough that someone manually using kubeadm (copy-pasting) shouldn't have any issues and 2) short enough that if something is going to break, it should break while the user/admin is still paying attention to the cluster. I'm open to bikeshedding about the exact value, 2 hours is a bit of a strawman.~~

**Edit: updated this to 24 hours instead of 2 hours.**

This is a breaking change if you rely on infinite TTL tokens (e.g., if you had an ASG group of worker nodes). The old behavior is easily restored by passing `--token-ttl 0` to `kubeadm init` or the `--ttl 0` flag to `kubeadm token create`.

**Which issue this PR fixes**: fixes https://github.com/kubernetes/kubeadm/issues/343

**Special notes for your reviewer**:
This was discussed earlier today in SIG-cluster-lifecycle

**Release note**:
```release-note
Change the default kubeadm bootstrap token TTL from infinite to 24 hours. This is a breaking change. If you require the old behavior, use `kubeadm init --token-ttl 0` / `kubeadm token create --ttl 0`.
```

cc @jbeda

### CODE REVIEW

File: cmd/kubeadm/app/constants/constants.go [hunk 1]
```diff
@@ -81,8 +81,8 @@ const (
 	MinimumAddressesInServiceSubnet = 10
 
 	// DefaultTokenDuration specifies the default amount of time that a bootstrap token will be valid
-	// Default behaviour is "never expire" == 0
-	DefaultTokenDuration = 0
+	// Default behaviour is 2 hours
+	DefaultTokenDuration = 2 * time.Hour
```
Comment (resouer) [inline cmd/kubeadm/app/constants/constants.go]: As you said this have possibility to break existing users, @luxas Do we have any rollout plan to avoid this?

Comment (luxas) [inline cmd/kubeadm/app/constants/constants.go]: Inform users very well I suppose

**Comment by luxas** [comment]
@mattmoyer Please cc me on kubeadm PRs so it's easier for me to notice ;)

@jbeda @mattmoyer Could we make this a day (24 hrs) instead?

**Comment by luxas** [comment]
/lgtm

Thanks @mattmoyer!
