### PR TITLE
Replace force

### LINKED ISSUE #28115: kubectl replace: --force options is broken be design
When replacing an existing pod, the ``kubectl replace --force`` command fails as it tries to create a pod with a name that is still used by terminating pod.

How does the ``--force`` option works?

1. ``kubectl replace`` deletes a pod (e.g. mypod)
1. ``kubectl replace`` creates a new pod with the same name (mypod)

What happens? As the command tries to recreate the pod, it fails as the ``mypod`` is in ``Terminating`` state. Thus it can not be created.

The problem is the ``kubectl replace`` does not wait for a pod to be deleted.

**Reproducer**:

1. kubectl run mypod --image=yapei/hello-openshift  --generator=run-pod/v1
1. kubectl get pod mypod -o yaml > mypod.json
1. kubectl replace -f  mypod.json --force

The last command ends with:

```
pod "mypod" deleted
Error from server: pods "mypod" already exists
```

### PR DESCRIPTION
**Pull request by fraenkel**
fixes #28115

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31841)

### CODE REVIEW

File: pkg/kubectl/cmd/replace.go [hunk 1]
```diff
@@ -205,17 +215,34 @@ func forceReplace(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []
...
 
+	if timeout == 0 {
+		timeout = kubectl.Timeout
+	}
+	r.Visit(func(info *resource.Info, err error) error {
+		if err != nil {
+			return err
+		}
+
+		return wait.Poll(kubectl.Interval, timeout, func() (bool, error) {
```
Comment (kargakis) [inline pkg/kubectl/cmd/replace.go]: Intercept the error returned by Poll and if it's a `ErrWaitTimeout` replace with a `NotFound`.

Comment (kargakis) [inline pkg/kubectl/cmd/replace.go]: Also change to `PollImmediate`

File: pkg/kubectl/cmd/replace.go [hunk 2]
```diff
@@ -205,17 +216,38 @@ func forceReplace(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []
...
 		err = DeleteResult(r, out, ignoreNotFound, shortOutput, mapper)
 	}
 	if err != nil {
 		return err
 	}
 
+	if timeout == 0 {
+		timeout = kubectl.Timeout
+	}
+	r.Visit(func(info *resource.Info, err error) error {
```
Comment (brendandburns) [inline pkg/kubectl/cmd/replace.go]: I think we should only do this if `--force` is specified.  Otherwise, we're going to throw timeout errors instead of already exists errors.

File: pkg/kubectl/cmd/replace.go [hunk 3]
```diff
@@ -205,17 +216,38 @@ func forceReplace(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []
...
+		}
+
+		err = wait.PollImmediate(kubectl.Interval, timeout, func() (bool, error) {
+			if err := info.Get(); !errors.IsNotFound(err) {
+				return false, err
+			}
+			return true, nil
+		})
+		if err == wait.ErrWaitTimeout {
+			err = errors.NewNotFound(unversioned.GroupResource{}, info.Name)
```
Comment (brendandburns) [inline pkg/kubectl/cmd/replace.go]: I don't think that Not Found is correct here, I would just return the timeout.  The resource _is_ found, we were just hoping that it wouldn't be.

File: pkg/kubectl/cmd/replace.go (hunk 2 above)
Comment (fraenkel) [inline pkg/kubectl/cmd/replace.go]: This is already in the --force path.

File: pkg/kubectl/cmd/replace.go (hunk 3 above)
Comment (fraenkel) [inline pkg/kubectl/cmd/replace.go]: Which is how it was, so who is making the final decision?

**Comment by dims** [comment]
ok to test

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
@fraenkel unit tests are failing:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31841/kubernetes-pull-test-unit-integration/43548/

Looks related to your changes, please check,

**Comment by fraenkel** [comment]
@brendandburns Sorry about that. Test cases have been fixed.

**Comment by brendandburns** [comment]
LGTM, thanks.
