### PR TITLE
Fix flaky typecheck by enforcing serial execution

### LINKED ISSUE #136121: [Flaking Test] pull-kubernetes-typecheck hangs sometimes
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136106/pull-kubernetes-typecheck/2009246286275940352
- Test started yesterday at 8:51 PM is still running after 13h50m9s. 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136105/pull-kubernetes-typecheck/2009245382688641024
- Test started yesterday at 8:48 PM is still running after 13h53m16s. ([more info](https://prow.k8s.io/spyglass/lens/metadata/iframe?req=%7B%22artifacts%22%3A%5B%22prowjob.json%22%2C%22started.json%22%5D%2C%22index%22%3A0%2C%22src%22%3A%22gs%2Fkubernetes-ci-logs%2Fpr-logs%2Fpull%2F136105%2Fpull-kubernetes-typecheck%2F2009245382688641024%22%7D&topURL=https%3A//prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136105/pull-kubernetes-typecheck/2009245382688641024&lensIndex=0#))

### Which tests are flaking?

the CI has no test cases. It hangs like 
```
Verifying verify-typecheck.sh

+++ Running case: verify.typecheck 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/verify-typecheck.sh"
type-checking windows/arm64
type-checking linux/arm
type-checking linux/arm64
type-checking linux/386
type-checking windows/amd64
type-checking linux/ppc64le
```

### Since when has it been flaking?

IIRC, it happened last week or the week before.

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig testing

### PR DESCRIPTION
**Pull request by MohammedMutee**
#### What type of PR is this?
/kind flake /kind bug

#### What this PR does / why we need it:
Fixes a flake in the pull-kubernetes-typecheck job where the test would hang indefinitely due to memory exhaustion (OOM) on CI nodes.

This PR makes two changes to hack/verify-typecheck.sh:

Fixes flag parsing order: Moves the flags (like --serial) before the package arguments ("$@"). Previously, flag.Parse() in the Go tool was ignoring flags because they appeared after non-flag arguments.

Defaults to serial execution: Sets TYPECHECK_SERIAL to true by default. This ensures type-checks run sequentially (one platform at a time) rather than in parallel, significantly reducing memory usage to prevent CI hangs.
#### Which issue(s) this PR is related to:
Fixes #136121

#### Special notes for your reviewer:
The verify-typecheck tool previously defaulted to running 2 checks in parallel. However, due to the flag parsing bug in the shell script, the --serial flag was being ignored even if set. By fixing the order and defaulting to serial, we ensure stable execution on resource-constrained CI runners.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: hack/verify-typecheck.sh [hunk 1]
```diff
@@ -39,8 +39,8 @@ if [[ $# == 0 ]]; then
 fi
 
 ret=0
-TYPECHECK_SERIAL="${TYPECHECK_SERIAL:-false}"
-go run ./test/typecheck "$@" "--serial=$TYPECHECK_SERIAL" || ret=$?
+TYPECHECK_SERIAL="${TYPECHECK_SERIAL:-true}"
+go run ./test/typecheck "--serial=$TYPECHECK_SERIAL" "$@" || ret=$?
```
Comment (pohly) [inline hack/verify-typecheck.sh:43]: I suppose the alternative would be to increase the memory for the typecheck job such that different platforms can be checked in parallel again?

I can imagine that that would makes overall utilization worse and typecheck is a fast presubmit, so I'm okay with making it serial. Feel free to lift the hold.

/lgtm
/hold

Comment (pohly) [reply hack/verify-typecheck.sh:43]: 5m37s (https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136124/pull-kubernetes-typecheck/2009525739551985664), which is in the ballpark where it was before (https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-typecheck).

/approve
/hold cancel

**Comment by pacoxu** [comment]
Thanks for the quick fix!👍
