### PR TITLE
do not return err when PodSandbox not exist

### LINKED ISSUE #98218: kubelet will panic when pause container lose during kubelet restarting
**What happened**:
with --cpu-manager-policy=static
kubelet will panic when pause container lose during kubelet restarting

**What you expected to happen**:
kubelet can start normally

**How to reproduce it (as minimally and precisely as possible)**:
1,config kubelet with --cpu-manager-policy=static
2, Run a large number of pods on the test node
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 25
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test1
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command: ["sleep", "1000000"]
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        ports:
        - containerPort: 81
          name: test
        volumeMounts:
        - mountPath: /data
          name: test-conf-file
          subPathExpr: test
      - name: test2
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        command: ["sleep", "1000000"]
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
        readinessProbe:
          exec:
            command:
            - cat
            - /dev/null
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 82
          name: test
        volumeMounts:
        - mountPath: /data
          name: test-conf-file
          subPathExpr: test
      volumes:
      - name: test-conf-file
        hostPath:
          path: /data
          type: Directory
```

3,stop kubelet use command: `systemctl  stop kubelet`
4,kill and remove all the pause container like this:
```
for line in `docker ps | grep test | grep "pause" | awk '{print $1}'` ; do  echo $line; docker kill $line; docker rm $line; done
```
image

5,start kubelet use command: `systemctl start kubelet`

and then kubelet maybe panic, log is :

[panic.log](https://github.com/kubernetes/kubernetes/files/5842395/panic.log)

```
space:"default", IPs:[]string{"10.244.0.110"}, ContainerStatuses:[]*container.Status{(*container.Status)(0xc000d442a0), (*container.Status)(0xc000298000), (*container.Status)(0xc000298380), (*container.Status)(0xc00130ba40)}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc00148aea0)}} (err: <nil>)
I0120 20:22:40.234543   11414 kuberuntime_manager.go:958] getSandboxIDByPodUID got sandbox IDs ["8793b332487b77ba17f7a00ac98311d44ce0a06ed01bee3f257ed69766a47881"] for pod "test-5c48444797-9fvhc_default(065868dc-edf7-4c76-9786-2d8b684d804e)"
F0120 20:22:40.248180   11414 kubelet.go:1376] Failed to start ContainerManager failed to build map of initial containers from runtime: no PodsandBox found with Id '596a017311e0085ccdbfa1a3d648a09a373b69e79459c0853d11e146d8d81b9e'
goroutine 394 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000ab6a01, 0xc001b96140, 0xe7, 0x137)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x7304d60, 0xc000000003, 0x0, 0x0, 0xc000b655e0, 0x6f69cfc, 0xa, 0x560, 0x0)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7304d60, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x495299c, 0x23, 0xc000563860, 0x1, ...)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:750 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1502
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc000176000)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1376 +0x547
sync.(*Once).doSlow(0xc000176850, 0xc000a27d98)
        /home/cyw/sdk/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /home/cyw/sdk/go/src/sync/once.go:57
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0xc000176000)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2211 +0x6fa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00042a030)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00042a030, 0x4f322a0, 0xc000c5a420, 0x1, 0xc0001aa060)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00042a030, 0x12a05f200, 0x0, 0x1, 0xc0001aa060)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00042a030, 0x12a05f200, 0xc0001aa060)
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
        /home/cyw/k8s/k8s_path/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1430 +0x16a
```

**Anything else we need to know?**:
When we actually encountered this problem, only one pause container was lost. In order to reproduce this bug, I deleted all pause containers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration: x86_64
- OS (e.g: `cat /etc/os-release`):18.04.5 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux ecs-linux-0008-43ee 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?** 
/kind bug

**What this PR does / why we need it**:

with --cpu-manager-policy=static, kubelet will panic when pause container lose during kubelet restarting

**Which issue(s) this PR fixes**:

Fixes #98218
same as #98225 (rebased)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet: fix panic when pause container loses during kubelet restarting
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by pacoxu** [comment]
/cc @cynepco3hahue
/assign @sjenning @dims

rebased #98225 for inactivity

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -746,12 +740,13 @@ func buildContainerMapFromRuntime(runtimeService internalapi.RuntimeService) (co
 	containerList, _ := runtimeService.ListContainers(nil)
 	for _, c := range containerList {
 		if _, exists := podSandboxMap[c.PodSandboxId]; !exists {
-			return nil, fmt.Errorf("no PodsandBox found with Id '%s' for container with ID '%s' and Name '%s'", c.PodSandboxId, c.Id, c.Metadata.Name)
+			klog.InfoS("no PodSandBox found for the container", "podSandboxId", c.PodSandboxId, "containerName", c.Metadata.Name, "containerId", c.Id)
```
Comment (249043822) [inline pkg/kubelet/cm/container_manager_linux.go:743]: We have also encountered this problem, seems to make sense.

**Comment by pacoxu** [comment]
/assign @mrunalp  
for approval

**Review by mrunalp — APPROVED** [review]

**Comment by rptaylor** [comment]
AFAICT this was merged into the 1.24 release branch:
https://github.com/kubernetes/kubernetes/blob/release-1.24/pkg/kubelet/cm/container_manager_linux.go

However "108325" is not in the v1.24 release notes:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md

So it's hard to tell what k8s version actually has this fix.

**Comment by pytimer** [comment]
@pacoxu Can we consider  merge this pr to 1.23 release branch?

**Comment by pacoxu** [comment]
@rptaylor Probably, we can add a release note for it.

```
kubelet: fix panic when pause container lose during kubelet restarting with `--cpu-manager-policy=static`
```

**Comment by gaurav90sharma** [comment]
We are facing this issue in "1.21.12" , is there a plan to backport this release to 1.21 or 1.22 ?

**Comment by dims** [comment]
@gaurav90sharma https://endoflife.date/kubernetes#:~:text=1.22.17-,1.21,-1%20year%20and
