### PR TITLE
--no-header available now for custom-column

### LINKED ISSUE #24133: kubectl cannot set --no-headers with --outputs
There is no documentation and no visible way to have custom columns without header:

    $ kubectl get pods --no-headers --output=custom-columns=PHASE:.status.phase

Having no header name also doesn't work:

    $ kubectl get pods --output=custom-columns=:.status.phase

### PR DESCRIPTION
**Pull request by sylwekb**
Change `CustomColumnsPrinter` to have `noHeader` boolean, also changed `GetPrinter` to receive this bool and pass it through.
One test `TestNewColumnPrinterFromSpecWithNoHeaders` added for checking if there is no headers in output for sure

fixes #24133

### CODE REVIEW

**Comment by janetkuo** [comment]
ok to test

**Comment by janetkuo** [comment]
@gitfred thanks for submitting the fix, although this needs to wait until after the 1.3 code freeze ends.

File: pkg/kubectl/cmd/util/printing.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ import (
 func AddPrinterFlags(cmd *cobra.Command) {
 	cmd.Flags().StringP("output", "o", "", "Output format. One of: json|yaml|wide|name|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=... See golang template [http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template [http://releases.k8s.io/HEAD/docs/user-guide/jsonpath.md].")
 	cmd.Flags().String("output-version", "", "Output the formatted object with the given group version (for ex: 'extensions/v1beta1').")
-	cmd.Flags().Bool("no-headers", false, "When using the default output, don't print headers.")
+	cmd.Flags().Bool("no-headers", false, "When using the default output (except for custom-column), don't print headers.")
```
Comment (janetkuo) [inline pkg/kubectl/cmd/util/printing.go]: Why except for custom-column? Isn't it supported in this PR?

File: pkg/kubectl/custom_column_printer_test.go [hunk 2]
```diff
@@ -206,6 +207,27 @@ func TestNewColumnPrinterFromTemplate(t *testing.T) {
 	}
 }
 
+func TestNewColumnPrinterFromSpecWithNoHeaders(t *testing.T) {
```
Comment (janetkuo) [inline pkg/kubectl/custom_column_printer_test.go]: Suggest adding no-headers tests in `TestNewColumnPrinterFromSpec`. You can add `noHeaders bool` as a field of the tests struct.

File: pkg/kubectl/cmd/util/printing.go (hunk 1 above)
Comment (gitfred) [inline pkg/kubectl/cmd/util/printing.go]: the sentence says "no-header works only for default output". Custom-column is not default so I put "except for custom-column" there  :)

**Comment by gitfred** [comment]
@janetkuo updated.

File: pkg/kubectl/cmd/util/printing.go [hunk 3]
```diff
@@ -52,7 +52,7 @@ func AddOutputFlags(cmd *cobra.Command) {
 
 // AddNoHeadersFlags adds no-headers flags to a command.
 func AddNoHeadersFlags(cmd *cobra.Command) {
-	cmd.Flags().Bool("no-headers", false, "When using the default output, don't print headers.")
+	cmd.Flags().Bool("no-headers", false, "When using the default output, don't print headers (except for not default custom-column, it also works then).")
```
Comment (janetkuo) [inline pkg/kubectl/cmd/util/printing.go]: How about `When using the default or custom-column output format, don't print headers.`

File: pkg/kubectl/custom_column_printer_test.go [hunk 4]
```diff
@@ -115,8 +122,19 @@ func TestNewColumnPrinterFromSpec(t *testing.T) {
 			t.Errorf("[%s] unexpected error: %v", test.name, err)
 			continue
 		}
+		if test.noHeaders {
+			buffer := &bytes.Buffer{}
 
-		if !reflect.DeepEqual(test.expectedColumns, printer.Columns) {
+			printer.PrintObj(&api.Pod{}, buffer)
```
Comment (janetkuo) [inline pkg/kubectl/custom_column_printer_test.go]: How about reusing the `DeepEqual` check, and set `test.expectedColumns` (which should have `Header: ""`)?

**Comment by janetkuo** [comment]
I made a few more comments.

File: pkg/kubectl/custom_column_printer_test.go (hunk 4 above)
Comment (gitfred) [inline pkg/kubectl/custom_column_printer_test.go]: It's not gonna work because the columns are still there (which is desired behaviour), the only difference with `--no-header` happens in "presentation" method which is `PrintObj`

Comment (janetkuo) [inline pkg/kubectl/custom_column_printer_test.go]: Ah, you're right

**Comment by janetkuo** [comment]
LGTM now. Thanks much @gitfred!

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #26760

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #27462

**Comment by dims** [comment]
looks good to me 👍

**Comment by janetkuo** [comment]
@k8s-bot node e2e test this issue #28683
