### PR TITLE
Fix duplicate unbind action in kube-proxy

### LINKED ISSUE #51694: Use netlink instead of ip command to bind IP address in ipvs pkg
When fixing a problem  in #51686 ,I notice that it is treated as already bound if `ip` returned 2 in `EnsureVirtualServerAddressBind`, but ref to the   [manual](http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS) and [source code](https://git.kernel.org/pub/scm/linux/kernel/git/shemminger/iproute2.git/tree/ip/ipaddress.c#n2080) of ip , it just means an error was reported by the kernel, such as "Operation not permitted". 

I prefer to use [netlink](https://github.com/vishvananda/netlink) instead of `ip` command to manage ip address. If so,  we will know whether the IP are bound or unbound from the interface in a more accurate way.

### PR DESCRIPTION
**Pull request by choury**
**What this PR does / why we need it**:
Fix duplicate unbind action in kube-proxy. It will generate unnecessary error info If unbind multi-ports on one service .

**Which issue this PR fixes**:
fixes #51694

**Release-note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by choury** [comment]
cc @m1093782566

**Comment by m1093782566** [comment]
@choury Thanks for your PR.

Did you run go test locally? I think UT won't pass in pkg/util/ipvs.

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -1328,17 +1328,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
...
-			err = proxier.ipvs.UnbindVirtualServerAddress(svc, DefaultDummyDevice)
-			if err != nil {
-				glog.Errorf("Failed to unbind service from dummy interface, error: %v", err)
-			}
+			unbindIPAddr[svc.Address.String()] = true
+		}
+	}
+
+	for addr := range unbindIPAddr {
+		err := proxier.ipvs.UnbindVirtualServerAddress(addr, DefaultDummyDevice)
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: Can we just check if IP address exist before doing unbind? Introducing an extra map probably is over-killed.

Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: There is no good way to check it. Do You mean add another function like "CheckVirtualServerAddressBind"  invoking `ip addr` ? But I think  it is more over-killed than this.

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -1328,17 +1328,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
...
+		if err != nil {
+			glog.Errorf("Failed to unbind service from dummy interface, error: %v", err)
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: output IP address will help debug

File: pkg/proxy/ipvs/proxier.go (hunk 1 above)
Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: No, I mean can we check the IP address exist in the function UnbindVirtualServerAddress()?

Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: Actually, service IPs can be more than 10K, and do you ever evaluate the memory consume of the unbindIPAddr map?

Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: There is only two ways to check in  UnbindVirtualServerAddress(), The first is judging the output info of `ip addr` command, and treating it as succeed, but I think it is not reliable. Another is remembing the address after unbind, It is almost the same as the way above.

File: pkg/proxy/ipvs/proxier.go (hunk 2 above)
Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: More debug info will be added in next commit.

Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: ACK

File: pkg/util/ipvs/ipvs_linux.go [hunk 3]
```diff
@@ -52,9 +52,8 @@ func New(exec utilexec.Interface) Interface {
 }
 
 // EnsureVirtualServerAddressBind is part of Interface.
-func (runner *runner) EnsureVirtualServerAddressBind(vs *VirtualServer, dummyDev string) (exist bool, err error) {
-	addr := vs.Address.String() + "/32"
-	args := []string{"addr", "add", addr, "dev", dummyDev}
+func (runner *runner) EnsureVirtualServerAddressBind(addr string, dummyDev string) (exist bool, err error) {
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs_linux.go]: If you change the parameter from *VirtualServer to string, should it still exist in util. It seems nothing to do with IPVS now, it's more close to proxier.

Comment (choury) [reply pkg/util/ipvs/ipvs_linux.go]: Yes, you are right, I will move it to `pkg/proxy/util/utils.go`

Comment (m1093782566) [reply pkg/util/ipvs/ipvs_linux.go]: Actually, I don't think `pkg/proxy/util/utils.go` is a good place since other proxiers maybe never use it. What about `pkg/proxy/ipvs/proxier.go`?

Comment (choury) [reply pkg/util/ipvs/ipvs_linux.go]: Yeah, `pkg/proxy/ipvs/proxier.go` might be a better place.

File: pkg/proxy/ipvs/proxier.go (hunk 1 above)
Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: I found it is treated as already bound if `ip` returned 2 in `EnsureVirtualServerAddressBind`, but ref to the  manual of ip [link](http://man7.org/linux/man-pages/man8/ip.8.html#EXIT_STATUS), it just means an error was reported by the kernel.

Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: Sounds not a bad idea.

Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: I guess if you employ netlink, probably you don't need to rely on `ip addr` command output message.

File: pkg/util/ipvs/ipvs_linux.go (hunk 3 above)
Comment (thockin) [reply pkg/util/ipvs/ipvs_linux.go]: Put stuff in utils when you have a reason to put it there.

File: pkg/util/ipvs/ipvs_linux.go [hunk 4]
```diff
@@ -52,9 +52,8 @@ func New(exec utilexec.Interface) Interface {
...
+	args := []string{"addr", "add", addr + "/32", "dev", dummyDev}
```
Comment (thockin) [inline pkg/util/ipvs/ipvs_linux.go]: ping to @danehans et al - another ipv4-ism has crept in :)

**Comment by thockin** [comment]
@m1093782566 you own this review.  When you lgtm it, assign to me for approval

File: pkg/proxy/ipvs/proxier.go [hunk 5]
```diff
@@ -1328,17 +1328,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
 }
 
 func (proxier *Proxier) cleanLegacyService(atciveServices map[string]bool, currentServices map[string]*utilipvs.VirtualServer) {
+	unbindIPAddr := map[string]bool{}
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: Can't we use `sets.String`?

**Review by m1093782566 — CHANGES_REQUESTED** [review]

File: pkg/proxy/ipvs/proxier.go (hunk 5 above)
Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: But... Is there `sets` in golang?

**Comment by m1093782566** [comment]
see the sets.String usage in proxier.go. Yes，golang has no sets type，but k8s created one


________________________________
杜军
M：+86-13732245813<tel:+86-13732245813>
E：dujun5@huawei.com<mailto:dujun5@huawei.com>
产品与解决方案-PaaS服务产品部
Products & Solutions-PaaS Product Dept

发件人： choury
收件人： kubernetes/kubernetes<kubernetes@noreply.github.com<mailto:kubernetes@noreply.github.com>>
抄送： dujun (D)<dujun5@huawei.com<mailto:dujun5@huawei.com>>;Mention<mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题： Re: [kubernetes/kubernetes] Fix duplicate unbind action in kube-proxy (#51686)
时间： 2017-09-01 18:00:16


@choury commented on this pull request.

________________________________

In pkg/proxy/ipvs/proxier.go<https://github.com/kubernetes/kubernetes/pull/51686#discussion_r136540849>:

> @@ -1328,17 +1328,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
 }

 func (proxier *Proxier) cleanLegacyService(atciveServices map[string]bool, currentServices map[string]*utilipvs.VirtualServer) {
+       unbindIPAddr := map[string]bool{}


But... Is there sets in golang?

―

**Comment by choury** [comment]
All review comments are fixed.

**Comment by danehans** [comment]
@choury can you update the IPv4-specific functions (i.e. anything with /32) and associated tests to support IPv6 addressing?

File: pkg/proxy/util/utils.go [hunk 6]
```diff
@@ -56,3 +59,45 @@ func ShouldSkipService(svcName types.NamespacedName, service *api.Service) bool
...
+	LinkByName(dev string) (netlink.Link, error)
+}
+
+// EnsureAddressBind checks if address is bound to the interface and, if not, binds it. If the address is already bound, return true.
+func EnsureAddressBind(address, devName string, h NetlinkHandle) (exist bool, err error) {
+	dev, err := h.LinkByName(devName)
+	if err != nil {
+		return false, fmt.Errorf("error get interface: %s, err: %v", devName, err)
+	}
+	addr, err := netlink.ParseAddr(address + "/32")
```
Comment (m1093782566) [inline pkg/proxy/util/utils.go]: I think we can remove the /32 now. In fact, IPVS interface support IPV6 as well.

**Comment by m1093782566** [comment]
@choury Pls take care of cross build.

File: pkg/proxy/util/utils.go [hunk 7]
```diff
@@ -56,3 +59,45 @@ func ShouldSkipService(svcName types.NamespacedName, service *api.Service) bool
...
+	if err != nil {
+		return false, fmt.Errorf("error parse ip address: %s/32, err: %v", address, err)
+	}
+	if err := h.AddrAdd(dev, addr); err != nil {
+		// "EEXIST" will be returned if the address is already bound to device
+		if err == syscall.Errno(syscall.EEXIST) {
```
Comment (m1093782566) [inline pkg/proxy/util/utils.go]: Can it paas cross-build?

**Review by m1093782566 — CHANGES_REQUESTED** [review]

File: pkg/proxy/util/utils.go [hunk 8]
```diff
@@ -56,3 +59,45 @@ func ShouldSkipService(svcName types.NamespacedName, service *api.Service) bool
...
+	return false, nil
+}
+
+// UnbindAddress unbind address with the interface
+func UnbindAddress(address, devName string, h NetlinkHandle) error {
+	dev, err := h.LinkByName(devName)
+	if err != nil {
+		return fmt.Errorf("error get interface: %s, err: %v", devName, err)
+	}
+	addr, err := netlink.ParseAddr(address + "/32")
```
Comment (m1093782566) [inline pkg/proxy/util/utils.go]: Same as above, remove /32?

File: pkg/proxy/util/utils.go [hunk 9]
```diff
@@ -56,3 +59,45 @@ func ShouldSkipService(svcName types.NamespacedName, service *api.Service) bool
...
+	if err != nil {
+		return fmt.Errorf("error parse ip address: %s/32, err: %v", address, err)
```
Comment (m1093782566) [inline pkg/proxy/util/utils.go]: Same as above, remove /32?

File: pkg/proxy/util/utils.go (hunk 7 above)
Comment (choury) [reply pkg/proxy/util/utils.go]: I will move it to `utils_linux.go`

File: pkg/proxy/util/utils.go (hunk 8 above)
Comment (choury) [reply pkg/proxy/util/utils.go]: No, If `/32` removed, an error of `invalid CIDR address`  will be thrown  by `netlink.ParseAddr`
I will add suitable mask or prefix by judging the address type.

**Comment by choury** [comment]
@m1093782566 
This should fix cross-build.
@danehans 
There is no IPv4-specific function now, and add some ipv6 test code.

**Comment by danehans** [comment]
@choury thank you for adding IPv6 support.

File: pkg/proxy/util/utils_linux.go [hunk 10]
```diff
@@ -0,0 +1,73 @@
+// +build linux
```
Comment (m1093782566) [inline pkg/proxy/util/utils_linux.go]: I would suggest put this file in pkg/proxy/ipvs and rename it to `netlink_unsupported.go`

File: pkg/proxy/util/utils_unsupported.go [hunk 11]
```diff
@@ -0,0 +1,43 @@
+// +build !linux
```
Comment (m1093782566) [inline pkg/proxy/util/utils_unsupported.go]: I would suggest put this file in pkg/proxy/ipvs and rename it to `netlink_unsupported.go`

File: pkg/proxy/util/utils_linux.go [hunk 12]
```diff
@@ -0,0 +1,73 @@
...
+	AddrDel(link netlink.Link, addr *netlink.Addr) error
+	LinkByName(dev string) (netlink.Link, error)
+}
+
+func NewNetLinkHandle() NetlinkHandle {
+	return &netlink.Handle{}
+}
+
+// EnsureAddressBind checks if address is bound to the interface and, if not, binds it. If the address is already bound, return true.
+func EnsureAddressBind(address, devName string, h NetlinkHandle) (exist bool, err error) {
```
Comment (m1093782566) [inline pkg/proxy/util/utils_linux.go]: This method looks odd, why do you take an interface as a parameter?

What about

```
type NetlinkHandle interface {
 	EnsureAddressBind(address, devName string)
 }
```

?

File: pkg/proxy/ipvs/proxier.go [hunk 13]
```diff
@@ -1261,7 +1264,7 @@ func (proxier *Proxier) syncService(svcName string, vs *utilipvs.VirtualServer,
 	// bind service address to dummy interface even if service not changed,
 	// in case that service IP was removed by other processes
 	if bindAddr {
-		_, err := proxier.ipvs.EnsureVirtualServerAddressBind(vs, DefaultDummyDevice)
+		_, err := utilproxy.EnsureAddressBind(vs.Address.String(), DefaultDummyDevice, proxier.netlinkHandle)
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: What about

```
nl := NewLinkNetLinkHandle()
nl.EnsureAddressBind(vs.Address.String(), DefaultDummyDevice)
```

?

File: pkg/proxy/util/utils_linux.go (hunk 10 above)
Comment (choury) [reply pkg/proxy/util/utils_linux.go]: May be `netlink_linux.go` ?

Comment (m1093782566) [reply pkg/proxy/util/utils_linux.go]: true :)

File: pkg/proxy/ipvs/proxier.go [hunk 14]
```diff
@@ -1350,17 +1353,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
...
-			err = proxier.ipvs.UnbindVirtualServerAddress(svc, DefaultDummyDevice)
-			if err != nil {
-				glog.Errorf("Failed to unbind service from dummy interface, error: %v", err)
-			}
+			unbindIPAddr.Insert(svc.Address.String())
+		}
+	}
+
+	for _, addr := range unbindIPAddr.UnsortedList() {
+		err := utilproxy.UnbindAddress(addr, DefaultDummyDevice, proxier.netlinkHandle)
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: Same as above

File: pkg/proxy/ipvs/proxier.go [hunk 15]
```diff
@@ -1350,17 +1353,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
...
+		if err != nil {
+			glog.Errorf("Failed to unbind service from dummy interface, error: %v", err)
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: nits:

service -> IP address?

output IP address and dummy interface name?

File: pkg/proxy/util/utils_unsupported.go (hunk 11 above)
Comment (choury) [reply pkg/proxy/util/utils_unsupported.go]: The netlink specific functions can be used by other proxies and it is not associated with ipvs, as thockin says, put it in util may be a better place ?

File: pkg/proxy/util/utils_linux.go (hunk 12 above)
Comment (choury) [reply pkg/proxy/util/utils_linux.go]: Good suggestion.

File: pkg/proxy/util/testing/fake.go [hunk 16]
```diff
@@ -0,0 +1,67 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package testing
+
+import (
+	"syscall"
+
+	"github.com/vishvananda/netlink"
```
Comment (m1093782566) [inline pkg/proxy/util/testing/fake.go]: I suspect it can not be compiled in windows. I mean, can you run go test in windows?

File: pkg/proxy/util/utils_unsupported.go (hunk 11 above)
Comment (m1093782566) [reply pkg/proxy/util/utils_unsupported.go]: If other proxiers consume these functions, then they should be in util. Sorry, I can't find any now...

File: pkg/proxy/ipvs/proxier.go (hunk 15 above)
Comment (choury) [reply pkg/proxy/ipvs/proxier.go]: The IP address and interface name can be printed in the `err` returned by `UnbindAddress`.

Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: If so, I would prefer directly return error in `UnbindAddress()` and then log detailed message here.

File: pkg/proxy/util/utils_linux.go [hunk 17]
```diff
@@ -0,0 +1,73 @@
...
+import (
+	"fmt"
+	"net"
+	"syscall"
+
+	"github.com/vishvananda/netlink"
+)
+
+type NetlinkHandle interface {
+	AddrAdd(link netlink.Link, addr *netlink.Addr) error
```
Comment (m1093782566) [inline pkg/proxy/util/utils_linux.go]: I would take `EnsureAddressBind()` and `UnbindAddress()` as interface functions, and hide AddrAdd, AddrDel, LinkByName.

File: pkg/proxy/ipvs/proxier.go [hunk 18]
```diff
@@ -1350,17 +1353,22 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
 }
 
 func (proxier *Proxier) cleanLegacyService(atciveServices map[string]bool, currentServices map[string]*utilipvs.VirtualServer) {
+	unbindIPAddr := sets.NewString()
 	for cS := range currentServices {
```
Comment (m1093782566) [inline pkg/proxy/ipvs/proxier.go]: cS -> cs/currentService

File: pkg/proxy/util/utils_linux.go (hunk 17 above)
Comment (choury) [reply pkg/proxy/util/utils_linux.go]: I'am trying to do so, But after I changed to this, the test cases are hard to write, because we can't mock netlink function in `EnsureAddressBind`.

Comment (m1093782566) [reply pkg/proxy/util/utils_linux.go]: I can't understand. The parameter of `EnsureAddressBind()` has nothing to do with netlink. We can simply return nil in FakeInterface.EnsureAddressBind()

Comment (choury) [reply pkg/proxy/util/utils_linux.go]: I mean I can't write a test case to test `EnsureAddressBind` itself.

Comment (m1093782566) [reply pkg/proxy/util/utils_linux.go]: Don't worry much about it.

**Comment by choury** [comment]
ping @m1093782566

**Comment by m1093782566** [comment]
I am in long holiday, and well be back in a few days :)

File: pkg/proxy/ipvs/netlink.go [hunk 19]
```diff
@@ -0,0 +1,25 @@
...
+limitations under the License.
+*/
+
+package ipvs
+
+// NetLinkHandle for revoke netlink interface
+type NetLinkHandle interface {
+	// EnsureAddressBind checks if address is bound to the interface and, if not, binds it. If the address is already bound, return true.
+	EnsureAddressBind(address, devName string) (exist bool, err error)
+	// UnbindAddress unbind address with the interface
```
Comment (m1093782566) [inline pkg/proxy/ipvs/netlink.go]: nit: unbind from...?

File: pkg/proxy/ipvs/netlink_linux.go [hunk 20]
```diff
@@ -0,0 +1,72 @@
...
+		// "EEXIST" will be returned if the address is already bound to device
+		if err == syscall.Errno(syscall.EEXIST) {
+			return true, nil
+		}
+		return false, fmt.Errorf("error bind address: %s to interface: %s, err: %v", address, devName, err)
+	}
+	return false, nil
+}
+
+// UnbindAddress unbind address with the interface
```
Comment (m1093782566) [inline pkg/proxy/ipvs/netlink_linux.go]: Same as above...

File: pkg/proxy/ipvs/netlink_unsupported.go [hunk 21]
```diff
@@ -0,0 +1,41 @@
...
+}
+
+// NewNetLinkHandle will create an EmptyHandle
+func NewNetLinkHandle() NetLinkHandle {
+	return &emptyHandle{}
+}
+
+// EnsureAddressBind checks if address is bound to the interface and, if not, binds it. If the address is already bound, return true.
+func (h *emptyHandle) EnsureAddressBind(address, devName string) (exist bool, err error) {
+	return false, fmt.Errorf("netlink not supported for this platform")
```
Comment (m1093782566) [inline pkg/proxy/ipvs/netlink_unsupported.go]: I believe this fake function should return `{true, nil}` or `{false, nil}`.

IPVS doesn't work on !linux platform, that's true. However, we may run UTs on !linux systems when developing. So, I would like this function and below return err=nil.

**Comment by m1093782566** [comment]
Just some nits. Please rebase, then LGTM.

File: pkg/proxy/ipvs/testing/fake.go [hunk 22]
```diff
@@ -0,0 +1,38 @@
+// +build linux
```
Comment (ixdy) [inline pkg/proxy/ipvs/testing/fake.go]: is it necessary to restrict the fake to linux-only? this is breaking the test on macOS because there's no non-linux fake implemented currently.

Comment (m1093782566) [reply pkg/proxy/ipvs/testing/fake.go]: NO. We should remove this restriction.

Comment (m1093782566) [reply pkg/proxy/ipvs/testing/fake.go]: I already send a PR, see https://github.com/kubernetes/kubernetes/pull/54666
