### PR TITLE
FIX: HPAs scale down with target >= 100

### LINKED ISSUE #111433: Increase fallback consumption for HPAs with target over 100%
### What would you like to be added?

Change the fallback consumption from `100%` to `max(100%, target)` when pod metrics are missing on a scale down.

Background from [HPA docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/):
> If there were any missing metrics, the control plane recomputes the average more conservatively, assuming those pods were consuming 100% of the desired value in case of a scale down, and 0% in case of a scale up. This dampens the magnitude of any potential scale.

### Why is this needed?

The fallback value of 100% is supposed to be a safe overestimate of the desired value to dampen the magnitude of a potential scale down. However, if a metric target is set to more than 100% then this fallback typically becomes an **underestimate** that **amplifies** a potential scale down.

Note that a metric target of over 100% is a valid HPA configuration.

### Alternative fallback

We could choose a fallback of `max(100%, target + safety_margin)` instead. However, any safety margin would be arbitrary and I think it's better to opt for simplicity vs. precision in this corner case.

### PR DESCRIPTION
**Pull request by kushagra98**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
During a scale down, we assume pods with missing metrics to be using 100% of the desired resource. However, it can happen that the target >= 100%
Eg.
```
type: Resource
resource:
  name: cpu
  target:
    type: Utilization
    averageUtilization: 200
```
Here 200% actually means 2 cores (cpu). Hence, during a case of a potential scale down, to compute the average more conservatively, we should consider the fallback as max(100%, resource utilization)

Background from [HPA docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/):

> If there were any missing metrics, the control plane recomputes the average more conservatively, assuming those pods were consuming 100% of the desired value in case of a scale down, and 0% in case of a scale up. This dampens the magnitude of any potential scale.

#### Which issue(s) this PR fixes:

Fixes #111433

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 1]
```diff
@@ -210,7 +211,7 @@ func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMet
 
 	if len(missingPods) > 0 {
 		if usageRatio < 1.0 {
-			// on a scale-down, treat missing pods as using 100% of the resource request
+			// on a scale-down, treat missing pods as using 100% (all) of the resource request
```
Comment (pbetkier) [inline pkg/controller/podautoscaler/replica_calculator.go:214]: let's reword to: "(...) as using exactly the target amount" while you're touching this comment. This reference to 100% of resource request doesn't make sense for `AverageValue` metric type here, seems like a bad copy&paste from `GetResourceReplicas `.

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 2]
```diff
@@ -107,9 +107,10 @@ func (c *ReplicaCalculator) GetResourceReplicas(ctx context.Context, currentRepl
...
```
Comment (pbetkier) [inline pkg/controller/podautoscaler/replica_calculator.go:110]: How about `(...) as using 100% (all) of the resource request or target utilization for targets higher than 100%`?

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 3]
```diff
@@ -107,9 +107,10 @@ func (c *ReplicaCalculator) GetResourceReplicas(ctx context.Context, currentRepl
...
+			maxTargetUtilization := int64(max(100, int32(targetUtilization)))
```
Comment (pbetkier) [inline pkg/controller/podautoscaler/replica_calculator.go:111]: nit: maybe `fallbackUtilization` instead of `maxTargetUtilization`?

Comment (pbetkier) [inline pkg/controller/podautoscaler/replica_calculator.go:111]: `int32(targetUtilization)` is redundant, `int64(max(100, targetUtilization))` should work.

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 1 above)
Comment (kushagra98) [reply pkg/controller/podautoscaler/replica_calculator.go]: Addressed

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 2 above)
Comment (kushagra98) [reply pkg/controller/podautoscaler/replica_calculator.go:110]: Addressed

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 3 above)
Comment (kushagra98) [reply pkg/controller/podautoscaler/replica_calculator.go]: Addressed

Comment (kushagra98) [reply pkg/controller/podautoscaler/replica_calculator.go]: Addressed

**Review by pbetkier — APPROVED** [review]
/lgtm 👍

Note we should update the docs in a separate PR to website repo.

Question to approvers: should we add release notes for this change? It does change the behavior, but for a rare corner case (missing metrics and an HPA with target over 100%).

**Comment by pbetkier** [comment]
/assign @mwielgus

Should we add release notes for this change? It does change the behavior, but for a rare corner case (missing metrics and an HPA with target over 100%).

**Comment by pbetkier** [comment]
/remove-lgtm

Overlooked originally: let's add a unit test for this change.

File: pkg/controller/podautoscaler/replica_calculator_test.go [hunk 4]
```diff
@@ -1464,6 +1464,24 @@ func TestReplicaCalcMissingMetricsUnreadyScaleDown(t *testing.T) {
...
+		currentReplicas:  4,
+		expectedReplicas: 2,
+		podReadiness:     []v1.ConditionStatus{v1.ConditionFalse, v1.ConditionTrue, v1.ConditionTrue, v1.ConditionTrue},
+		resource: &resourceInfo{
+			name:     v1.ResourceCPU,
+			requests: []resource.Quantity{resource.MustParse("1.0"), resource.MustParse("1.0"), resource.MustParse("2.0"), resource.MustParse("2.0")},
+			levels:   makePodMetricLevels(200, 100, 100),
+
+			targetUtilization:   300,
+			expectedUtilization: 6,
```
[the remark this answers is not in the document]
Comment (pbetkier) [reply pkg/controller/podautoscaler/replica_calculator_test.go:1478]: OK the rounding down got me confused, now I know :)

**Review by pbetkier — APPROVED** [review]

**Comment by pbetkier** [comment]
/assign @mwielgus

Should we add release notes for this change? It does change the behavior, but for a rare corner case (missing metrics and an HPA with target over 100%).

We plan to adjust [HPA docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) in a separate PR.

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 5]
```diff
@@ -208,7 +210,7 @@ func (c *ReplicaCalculator) calcPlainMetricReplicas(metrics metricsclient.PodMet
 
 	if len(missingPods) > 0 {
 		if usageRatio < 1.0 {
-			// on a scale-down, treat missing pods as using 100% of the resource request
+			// on a scale-down, treat missing pods as using exactly the target amount
 			for podName := range missingPods {
 				metrics[podName] = metricsclient.PodMetric{Value: targetUtilization}
```
Comment (mwielgus) [inline pkg/controller/podautoscaler/replica_calculator.go:215]: Why not max(target,100)?

Comment (kushagra98) [reply pkg/controller/podautoscaler/replica_calculator.go:215]: Here, these metrics are non-utlilization (non-percentage) metrics. These metrics here are the **usage** metrics like 10m CPU, 1G memory, etc.  Hence, making it equal to 100 would not be a good idea since this number (100) can be too big or too small depending on the metric.

Let say the target is 1G memory making it to = 100G memory (in case of missing metric) is not a good idea.

The variable `targetUtilization` here seems to be a bad copy paste from above function `GetResourceReplicas` and should be fixed, maybe to `targetUsage`

Comment (mwielgus) [reply pkg/controller/podautoscaler/replica_calculator.go:215]: Ok. Can we rename it in the next PR, please?

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by ialidzhikov** [comment]
@kushagra98 I assume 1.25 is also affected by the corresponding issue. Can you confirm? If yes, can you also cherry-pick to all affected versions?
