### PR TITLE
Fix an e2e flake for preemption with hard PodTopologySpread

### LINKED ISSUE #88680: [sig-scheduling] SchedulerPreemption [Serial] PodTopologySpread Preemption validates proper pods are preempted
**Which jobs are flaking**:

[sig-scheduling] SchedulerPreemption [Serial] PodTopologySpread Preemption validates proper pods are preempted

**Which test(s) are flaking**:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1233012032534482949
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1232952638320939008
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1232836114176282624

**Testgrid link**:

- https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

**Reason for failure**:

It's likely when the preemptor preempts low-priority pods, and gets running, the low-priority pods are still terminating. #88681 tries to wait for all low-priority pods to be totally deleted and do the final check.

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind failing-test
/sig scheduling

**What this PR does / why we need it**:

The e2e (PodTopologySpread Preemption > validates proper pods are preempted) was designed to ensure a Pod with high priority can preempt low priority ones when its hard topologySpreadConstraints cannot be satisfied.

The flake reveals that when the high priority Pod gets running (which indicates it has finished the preemption process and low-priority Pods should be gone), some low-priority Pods are still there.

The most likely cause is: when the high priority Pods's nominatedNode gets set, and by the time low priority Pods gets terminated (but not fully gone yet), it enters the next scheduling cycle, due to recent changes (#87845), the high priority Pod will be immediately gets scheduled instead of waiting again for terminating Pods to disappear. Hence the flake surfaced - by that moment, the terminating Pods are still there.

This PR replaced the immediate check with a wait loop, which will wait for all the terminating Pods to go away before performing the final check.

**Flake Replay:**

- initial state is [\<high\>, <lowA, lowB, lowC>]
- during Preemption cycle, final state is [\<high\>, <med with nominatedNode set, lowA terminaing, lowB terminating, lowC>]

then the interesting thing happens:

- med Pod gets popped out to be scheduled, in the before, it will wait for both lowA and lowB to disappear; otherwise, it will be put back into schedulingQ again and wait for its another retry
- however, as podTopologySpread don't consider terminating Pods (#87845), med Pod will be immediately scheduled once lowA or lowB gets killed.
  why it waits for lowA or lowB to go away? it's because lowA and lowB takes 3 (fake) resources, med Pod needs to satify the noderesource plugin as well.

so the flake always shows there are 4 pods instead of 3 - which are high, med, <lowA or lowB>, lowC.

**Which issue(s) this PR fixes**:

Fixes #88680

**Special notes for your reviewer**:

The 2nd commit is a trick to test it in CI presubmit job, I will run the e2e test ~20 times to ensure the fix works, and then remove it.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
- [test1](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88681/pull-kubernetes-e2e-gce/1233622970044256258/) passed

**Comment by Huang-Wei** [comment]
//test pull-kubernetes-e2e-gce

**Comment by Huang-Wei** [comment]
/hold
I will remove the 2nd commit once the review is done.

File: test/e2e/scheduling/preemption.go [hunk 1]
```diff
@@ -394,15 +394,21 @@ var _ = SIGDescribe("SchedulerPreemption [Serial]", func() {
...
 			runPausePod(f, mediumPodCfg)
-			e2epod.WaitForPodNotPending(cs, ns, mediumPodCfg.Name)
 
 			ginkgo.By("Verify there are 3 Pods left in this namespace")
 			wantPods := sets.NewString("high", "medium", "low")
 
-			podList, err := cs.CoreV1().Pods(ns).List(context.TODO(), metav1.ListOptions{})
-			pods := podList.Items
+			var pods []v1.Pod
+			err := wait.PollImmediate(framework.Poll, framework.PollShortTimeout, func() (bool, error) {
```
Comment (alculquicondor) [inline test/e2e/scheduling/preemption.go]: Add a comment to explain why we poll instead of doing a one-time check. Also, isn't there any function like this in the framework?

**Comment by alculquicondor** [comment]
> The flake is very likely related with recent changes that excludes terminating Pods in PodTopologySpread plugin. So this PR waits for the victim Pods to totally before final check; in the before, the final check starts once the preemptor comes to be running status.

quickly summarize what the test is trying to do and why it was failing now. I had to go read the test code to understand, which is not good for tracking purposes. Also the title could be like: "Fix E2E for preemption with hard PodTopologySpread"

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Seems there isn't any in the framework :(

Comment (alculquicondor) [reply test/e2e/scheduling/preemption.go]: if we don't need another OWNER approval, I would suggest to just add `WaitForNumberOfRunningPods` or something like that. It would make the test more readable.

**Comment by Huang-Wei** [comment]
> quickly summarize what the test is trying to do and why it was failing now. I had to go read the test code to understand, which is not good for tracking purposes.

See if it's clear now.

> Also the title could be like: "Fix E2E for preemption with hard PodTopologySpread"

Done.

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: maybe in a followup, I want it to be merged ASAP so as not to impact the release timeline.

**Comment by alculquicondor** [comment]
Thanks!

/approve

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (alculquicondor) [reply test/e2e/scheduling/preemption.go]: sounds good. But just add the comment here. Maybe:

```Wait until the number of pods stabilizes. Note that `medium` pod can get scheduled once the second low priority pod is marked as terminating.```

Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Thanks. Done.

**Comment by Huang-Wei** [comment]
Some (new) error observed due to not having 2 different nodes:

- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88681/pull-kubernetes-e2e-gce/1234617017286266880/ (this test even cannot find 1 node to run a testing Pod)

```
I0302 23:37:10.139] Full Stack Trace
I0302 23:37:10.139] k8s.io/kubernetes/test/e2e/scheduling.runPausePod(0xc000ba1ce0, 0x4b7be0a, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0302 23:37:10.139] 	test/e2e/scheduling/predicates.go:869 +0x100
I0302 23:37:10.139] k8s.io/kubernetes/test/e2e/scheduling.runPodAndGetNodeName(0xc000ba1ce0, 0x4b7be0a, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0302 23:37:10.139] 	test/e2e/scheduling/predicates.go:880 +0x70
I0302 23:37:10.140] k8s.io/kubernetes/test/e2e/scheduling.GetNodeThatCanRunPod(0xc000ba1ce0, 0xc002f4cf00, 0x4d4098)
I0302 23:37:10.140] 	test/e2e/scheduling/predicates.go:947 +0x95
I0302 23:37:10.140] k8s.io/kubernetes/test/e2e/scheduling.Get2NodesThatCanRunPod(0xc000ba1ce0, 0x31, 0x0, 0x0)
I0302 23:37:10.140] 	test/e2e/scheduling/predicates.go:952 +0x43
I0302 23:37:10.140] k8s.io/kubernetes/test/e2e/scheduling.glob..func
```

I think we should let the error bumped up.
