### PR TITLE
Fixed a scheduler panic when using PodAffinity (k8s version >= 1.15)

### LINKED ISSUE #82796: kube-scheduler panic on PodAffinity
**What happened**:

Kube scheduler went into a crash loop after upgrading to 1.15.2. The logs can be located here: https://gist.github.com/bernadinm/30416acf185f4ea36d620d60d81f3f56

```
E0909 23:20:26.016048       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 366 [running]:
```

We suspect that it is related to this commit here that https://github.com/kubernetes/kubernetes/pull/76973/files was introduced in k8s-v1.15.0-alpha

```
kube-scheduler-ip-10-0-1-10             0/1     CrashLoopBackOff   10         5d
kube-scheduler-ip-10-0-2-20             0/1     CrashLoopBackOff   10         5d
kube-scheduler-ip-10-0-3-30             0/1     CrashLoopBackOff   10         4d23h
```

**What you expected to happen**:

This issue was addressed when we downgraded the kube-scheduler to 1.14.6 as this is a supportable skew k8s configuration. 

```
kube-scheduler-ip-10-0-1-10            1/1     Running   20         5d1h
kube-scheduler-ip-10-0-2-20            1/1     Running   20         5d1h
kube-scheduler-ip-10-0-3-30            1/1     Running   20         5d1h
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

We've downgraded the kube-scheduler version from 1.5.2 to 1.14.6.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
- masters: m5.2xlarge
```
- OS (e.g: `cat /etc/os-release`):
```
DISTRIB_ID="Container Linux by CoreOS"
DISTRIB_RELEASE=1855.4.0
DISTRIB_CODENAME="Rhyolite"
DISTRIB_DESCRIPTION="Container Linux by CoreOS 1855.4.0 (Rhyolite)"
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1855.4.0
VERSION_ID=1855.4.0
BUILD_ID=2018-09-11-0003
PRETTY_NAME="Container Linux by CoreOS 1855.4.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-13-63-158.eu-west-1.compute.internal 4.14.67-coreos #1 SMP Mon Sep 10 23:14:26 UTC 2018 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux
```
- Install tools:
N/A
- Network plugin and version (if this is a network-related bug):
weave-plugin-2.5.1
- Others:

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/sig scheduling
/priority critical-urgent

**What this PR does / why we need it**:

A bug was introduced in 1.15 which can cause the scheduler panic.

**Which issue(s) this PR fixes**:

Fixes #82796.

**Special notes for your reviewer**:

**>Background:** There was an attempt in 1.15 to improve PodAffinity performance - which tried to use `atomic.AddInt64()` to replace explicit lock. Which was expected to work well for PodAffinity and it did, but it exposed penalties on regular workloads. So we reverted that PR. And later on, the penalties lied in the unconditional initialization on the int64 pointer for every node. So we introduced a dynamic/lazy initialization for only the necessary nodes, which is the current version.

**>Why it panics?** #82796 indicated that the idea of "pre-detecting the nodes and then initialize them with *int64" is hard to achieve. In other words, we can't deduce which nodes could be pre-counted. For example, there is 1 zone having 2 nodes, nodeA has pods with Pod(Anti-)Affinity, while nodeB doesn't have pods with Pod(Anti-)Affinity. In this case, we need to know the exact `topologyKey` each pod (holding Pod(Anti-Affinity) in nodeA, so that we can know whether nodeB is a qualified node can be scored (and hence should be initialized). The logic is way too complex and wasn't covered. And in runtime, if it ends up with nodeB is a qualified one, adding a score to `counts[nodeB]` will panic as it's nil.
(The panic case is included in the unit test of this PR.)

**>Solutions:** At a first glance, it seems we only need to check if `counts[nodeB]` is nil and if it's not, initialize it in runtime (#82798). Which looks good, but it happens in each concurrent goroutine, and they're operating the same `map` obj, so it can cause a race condition. Another solution is to initialize every node with an int64 pointer, as aforementioned, it will regress the regular workloads.

**>Solution in this PR:** (Not sure why I didn't think of this in 1.15...) This PR replaced `map` with a fixed `slice` when calculating counts. So that `&slice[i]` is addressable, and the `slice` is initialized with the nil value (0), without additional overhead.

**>Performance:** A benchmark test is included in this PR. It's expected that our current PR performs the best.

The following tests are using the same benchmark test to simulate a 1000-nodes cluster with 10k pods with shuffled PodAffinity. (The unit is "ns/op")

> Master (Baseline)

|                                                                                    | average  | run1     | run2     | run3     |
|------------------------------------------------------------------------------------|----------|----------|----------|----------|
| incoming_pod_without_PodAffinity_and_existing_pods_without_PodAffinity-8 | 209589   | 208704   | 210674   | 209389   |
| incoming_pod_with_PodAffinity_and_existing_pods_without_PodAffinity-8    | 8888500  | 9090174  | 8938776  | 8636551  |
| incoming_pod_without_PodAffinity_and_existing_pods_with_PodAffinity-8    | 58973078 | 58118594 | 60900042 | 57900597 |
| incoming_pod_with_PodAffinity_and_existing_pods_with_PodAffinity-8       | 64750096 | 65891670 | 65887335 | 62471282 |

> Master + This PR

|                                                                          | average  | run1     | run2     | run3     |
|--------------------------------------------------------------------------|----------|----------|----------|----------|
| incoming_pod_without_PodAffinity_and_existing_pods_without_PodAffinity-8 | 197480   | 189574   | 212554   | 190311   |
| incoming_pod_with_PodAffinity_and_existing_pods_without_PodAffinity-8    | 8527400  | 8647236  | 8491254  | 8443710  |
| incoming_pod_without_PodAffinity_and_existing_pods_with_PodAffinity-8    | 43504498 | 41093945 | 46569620 | 42849928 |
| incoming_pod_with_PodAffinity_and_existing_pods_with_PodAffinity-8       | 45220779 | 44766175 | 46500664 | 44395499 |

> Master + #82798 (it can cause a potential racing though)

|                                                                          | average  | run1     | run2     | run3     |
|--------------------------------------------------------------------------|----------|----------|----------|----------|
| incoming_pod_without_PodAffinity_and_existing_pods_without_PodAffinity-8 | 212721   | 215281   | 210121   | 212760   |
| incoming_pod_with_PodAffinity_and_existing_pods_without_PodAffinity-8    | 8778035  | 8714004  | 8885097  | 8735004  |
| incoming_pod_without_PodAffinity_and_existing_pods_with_PodAffinity-8    | 65006391 | 63493375 | 65481544 | 66044255 |
| incoming_pod_with_PodAffinity_and_existing_pods_with_PodAffinity-8       | 68722439 | 71596582 | 68081107 | 66489627 |

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a scheduler panic when using PodAffinity.
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
cc/ @tedyu @bsalamat 
/assign @ahg-g

File: pkg/scheduler/testing/workload_prep.go [hunk 1]
```diff
@@ -22,15 +22,15 @@ import (
 	"k8s.io/api/core/v1"
 )
 
-// MakeNodesAndPods serves as a testing helper for EvenPodsSpread feature.
+// MakeNodesAndPodsForEvenPodsSpread serves as a testing helper for EvenPodsSpread feature.
 // It builds a fake cluster containing running Pods and Nodes.
```
Comment (alculquicondor) [inline pkg/scheduler/testing/workload_prep.go]: Specify that this helper creates nodes within a set of different zones.

File: pkg/scheduler/testing/workload_prep.go [hunk 2]
```diff
@@ -65,3 +65,70 @@ func MakeNodesAndPods(pod *v1.Pod, existingPodsNum, allNodesNum, filteredNodesNu
 	}
 	return
 }
+
+// MakeNodesAndPodsForPodAffinity serves as a testing helper for Pod(Anti)Affinity feature.
```
Comment (alculquicondor) [inline pkg/scheduler/testing/workload_prep.go]: Specify what are the characteristics of the pods or nodes.

File: pkg/scheduler/testing/workload_prep.go [hunk 3]
```diff
@@ -65,3 +65,70 @@ func MakeNodesAndPods(pod *v1.Pod, existingPodsNum, allNodesNum, filteredNodesNu
...
+		leftIdx, rightIdx := affinityIdx/len(left), affinityIdx%len(left)
+		podWrapper = podWrapper.PodAffinityExists(label, tpKey, left[leftIdx])
+		podWrapper = podWrapper.PodAntiAffinityExists(label, tpKey, right[rightIdx])
+		existingPods = append(existingPods, podWrapper.Obj())
+	}
+
+	return
+}
+
+// MakeNodesAndPods serves as a testing helper to generate regular Nodes and Pods.
```
Comment (alculquicondor) [inline pkg/scheduler/testing/workload_prep.go]: What is regular? :)

File: pkg/scheduler/algorithm/priorities/interpod_affinity.go [hunk 4]
```diff
@@ -106,13 +106,8 @@ func (ipa *InterPodAffinity) CalculateInterPodAffinityPriority(pod *v1.Pod, node
 	// the node.
 	pm := newPodAffinityPriorityMap(nodes)
 	allNodeNames := make([]string, 0, len(nodeNameToInfo))
-	lazyInit := hasAffinityConstraints || hasAntiAffinityConstraints
 	for name := range nodeNameToInfo {
```
Comment (alculquicondor) [inline pkg/scheduler/algorithm/priorities/interpod_affinity.go]: So we are saying:
We can't deduce which nodes could be counted, so create a counter for all of them. Please add this to the solution section of the PR description.

Not related to this PR: have we done the same mistake for even pod spreading?

**Review by alculquicondor — COMMENTED** [review]
In your third benchmark table, it looks like you referenced the issue instead of the old PR.

File: pkg/scheduler/testing/workload_prep.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/testing/workload_prep.go]: Alternatively, make the function name unrelated to EvenPodSpread. Something like: `MakeNodesAndPodsInZones`

File: pkg/scheduler/algorithm/priorities/interpod_affinity.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/algorithm/priorities/interpod_affinity.go]: > We can't deduce which nodes could be counted, so create a counter for all of them.

Yes, and in the before, the overhead of using a map and initializing *int64 is too high.

> have we done the same mistake for even pod spreading?

Even pods spreading doesn't need to consider Symmetry, so it's fine.

File: pkg/scheduler/testing/workload_prep.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/testing/workload_prep.go]: But it relies on the input pod's `pod.Spec.TopologySpreadConstraints` to construct the workload. Would you mind putting the refactoring in another PR?

File: pkg/scheduler/testing/workload_prep.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/testing/workload_prep.go]: Regular means just plain cluster without using any advanced scheduling feature like Affinity and EvenPodsSpread.

File: pkg/scheduler/testing/workload_prep.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/testing/workload_prep.go]: I'm fine with keeping the name as is. Just explain what the expected state of the nodes/pods is.

Having a separate PR is fine too.

File: pkg/scheduler/testing/workload_prep.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/testing/workload_prep.go]: `MakeNodesAndPods serves a testing helper to generate Nodes and Pods that don't use any advanced scheduling features.`

File: pkg/scheduler/algorithm/priorities/interpod_affinity.go [hunk 5]
```diff
@@ -55,13 +55,13 @@ type podAffinityPriorityMap struct {
 	nodes []*v1.Node
 	// counts store the mapping from node name to so-far computed score of
 	// the node.
-	counts map[string]*int64
+	counts []int64
```
Comment (bsalamat) [inline pkg/scheduler/algorithm/priorities/interpod_affinity.go]: Please fix the comment.

**Review by bsalamat — COMMENTED** [review]
Thanks, Wei for fixing the issue. Looks like the new implementation gives us a nice performance improvement when there are pods with affinity/anti-affinity.
(I didn't review the tests, but the fix looks good to me.)

File: pkg/scheduler/algorithm/priorities/interpod_affinity.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/algorithm/priorities/interpod_affinity.go]: Updated.

**Comment by Huang-Wei** [comment]
@bsalamat Thanks for the review. I didn't realize why I didn't come up current solution back in 1.15...

/hold
I will squash the commits later.

And the code fix (without the benchmark test) needs to be backported to 1.15 release.

**Comment by bsalamat** [comment]
> I didn't realize why I didn't come up current solution back in 1.15...

Adding/removing a node would break this logic, but since the scheduler works with a snapshot, the new logic should work fine.

**Comment by alculquicondor** [comment]
LGTM, FWIIW :)

File: pkg/scheduler/algorithm/priorities/interpod_affinity_test.go [hunk 6]
```diff
@@ -612,3 +629,57 @@ func TestHardPodAffinitySymmetricWeight(t *testing.T) {
 		})
 	}
 }
+
+func BenchmarkInterPodAffinityPriority(b *testing.B) {
```
Comment (ahg-g) [inline pkg/scheduler/algorithm/priorities/interpod_affinity_test.go]: should we move this to https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_bench_test.go

**Review by ahg-g — COMMENTED** [review]
Thanks Wei for the quick fix.

File: pkg/scheduler/algorithm/priorities/interpod_affinity_test.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/algorithm/priorities/interpod_affinity_test.go]: We should come up with a common library and make it consumed by both UT and Perf/Integration tests.

FYI: @draveness

**Comment by Huang-Wei** [comment]
@ahg-g Most of the comments have been addressed (except for the "returned variables", I'm ok either way, but would like to keep it as is for now). PTAL.

(And for sure there is room to improve "workload prepping" piece. The ideal case is to polish it and uplift as a common library to be consumed by all kinds of tests.)

**Comment by ahg-g** [comment]
/hold

 until comments are squashed

**Comment by Huang-Wei** [comment]
Commits squashed. Once it's merged, I will raise cherry-pick PRs to 1.15 and 1.16.

/hold cancel

**Comment by tpepper** [comment]
@Huang-Wei is there also a cherry-pick for 1.15 coming?

**Comment by Huang-Wei** [comment]
@tpepper Yes, #82907 is the one.
