### PR TITLE
Fix for the 'kubectl explain crd --recursive' goes into an infinite loop issue

### LINKED ISSUE #546: kubectl explain crd --recursive goes into an infinite loop
The reason is because the visitor at path spec.validation.openAPIV3Schema.allOf will reference an object type that references itself, causing the visitor to go into an infinite loop.

The visitor needs some of kind of loop detection.

### PR DESCRIPTION
**Pull request by vithati**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
'kubectl explain crd --recursive' goes into infinite loop because visitor at path spec.validation.openAPIV3Schema.allOf reference an object type that references itself. This PR change detects self reference loops while visiting references to avoid infinite loop. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubectl/issues/546

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/explain/recursive_fields_printer.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ type recursiveFieldsPrinter struct {
 
 var _ proto.SchemaVisitor = &recursiveFieldsPrinter{}
 var _ fieldsPrinter = &recursiveFieldsPrinter{}
+var visitedReferences = make(map[string]bool)
```
Comment (apelisse) [inline pkg/kubectl/explain/recursive_fields_printer.go]: use `map[string]struct{}` instead?

**Comment by apelisse** [comment]
Cool, thanks, can you squash the commits?

**Comment by vithati** [comment]
@apelisse , I have squashed the commits. Thanks.

File: pkg/kubectl/explain/recursive_fields_printer.go [hunk 2]
```diff
@@ -64,7 +65,12 @@ func (f *recursiveFieldsPrinter) VisitPrimitive(p *proto.Primitive) {
 
 // VisitReference is just a passthrough.
 func (f *recursiveFieldsPrinter) VisitReference(r proto.Reference) {
+	if value, ok := visitedReferences[r.Reference()]; ok && value {
+		return
+	}
+	visitedReferences[r.Reference()] = true
```
Comment (apelisse) [inline pkg/kubectl/explain/recursive_fields_printer.go]: you still don't have the `map[string]struct{}`

Comment (vithati) [reply pkg/kubectl/explain/recursive_fields_printer.go]: If i change to map[string]struct{} i am getting **'pkg/kubectl/explain/recursive_fields_printer.go:33:25: type map[string]struct {} is not an expression'** error. So i thought you want to me make change from make(map[string]bool) to map[string]bool{} to initialize empty map.

Comment (apelisse) [reply pkg/kubectl/explain/recursive_fields_printer.go]: To initialize the empty map, you would have to do `map[string]struct{}{}`

Comment (vithati) [reply pkg/kubectl/explain/recursive_fields_printer.go]: Thanks. I have changed to map[string]struct{}.

**Comment by apelisse** [comment]
Thanks!
/lgtm

**Comment by mingfang** [comment]
I don't think keeping track of References in a map like this is good enough.  I think it needs a legit loop detection algorithm

**Comment by apelisse** [comment]
@mingfang Can you send a PR with a test example that would break?

**Comment by mingfang** [comment]
sorry I think you're right; looks like this ```delete(visitedReferences, r.Reference())``` makes it work.  
I tried using the map technique before but didn't have the delete so mine didn't work.
