### PR TITLE
Validate SHA/Tag when checking docker images

### LINKED ISSUE #30355: kubelet gets confused when docker image tag is the same as docker image id start
We had rather strange case today when after rolling update one of the kubelet's started wrong container.

For this specific  replicationcontroller we are using         `imagePullPolicy: IfNotPresent`

What happened was that after rolling-update when i started to debug the issue i discovered that one of the kubelet's did not pull the image:
`2m            2m              1       {kubelet x.x.x.x}  spec.containers{myimage}        Normal          Pulled          Container image "myrepo:5000/myimage:2208" already present on machine`

When looking into what image it actually started i saw:
`Image ID:           docker://sha256:2208f7a29005d226d1ee33a63e33af1f47af6156c740d7d23c7948e8d282d53d`

When checking from the actual node i saw this
```
$ docker images | grep 2208
myrepo:5000/myimage                  1393                2208f7a29005        3 months ago        611.7 MB
```
It seems that instead of starting myimage with tag 2208 kubelet started image tagged as 1393 since the docker image id starts with 2208.

```
$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:        
 OS/Arch:      linux/amd64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:45:16Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.4", GitCommit:"dd6b458ef8dbf24aff55795baa68f83383c9b3a9", GitTreeState:"clean", BuildDate:"2016-08-01T16:38:31Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
$ kubelet --version
Kubernetes v1.3.4
$ uname -a
Linux node 4.6.3-coreos #2 SMP Mon Jul 18 06:10:39 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz GenuineIntel GNU/Linux
```

### PR DESCRIPTION
**Pull request by dims**
Docker API does not validate the tag/sha, for example, all the following
calls work say for a alpine image with short SHA "4e38e38c8ce0"
echo -e "GET /images/alpine:4e38e38c8ce0/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock
echo -e "GET /images/alpine:4e38e38c/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock
echo -e "GET /images/alpine:4/json HTTP/1.0\r\n" | nc -U /var/run/docker.sock

So we should check the response from the Docker API and look for the tags or SHA explicitly.

Fixes #30355

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30366)

### CODE REVIEW

File: pkg/kubelet/dockertools/kube_docker_client.go [hunk 1]
```diff
@@ -184,7 +185,27 @@ func (d *kubeDockerClient) InspectImage(image string) (*dockertypes.ImageInspect
 		}
 		return nil, err
 	}
-	return &resp, nil
+	parts := strings.SplitN(image, ":", 2)
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/kube_docker_client.go]: Could probably reuse/share the logic in `applyDefaultImageTag`
https://github.com/kubernetes/kubernetes/blob/9f1c3a4c562a1b5ab96a4c43d95c5c39d80fbec5/pkg/kubelet/dockertools/docker.go#L161

File: pkg/kubelet/dockertools/kube_docker_client.go [hunk 2]
```diff
@@ -184,7 +185,27 @@ func (d *kubeDockerClient) InspectImage(image string) (*dockertypes.ImageInspect
...
+	if len(parts) == 1 {
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/kube_docker_client.go]: This is ok, but kubelet applies a default image tag (i.e., "latest") if none is specified.

**Comment by yujuhong** [comment]
Could you add a unit test for this? Thanks!

/cc @Random-Liu

**Comment by dims** [comment]
@yujuhong I don't see ANY tests for anything in this file !!

**Comment by yujuhong** [comment]
> @yujuhong I don't see ANY tests for anything in this file !!

That's not a very good reason too not add a test, is it? :-) 
I think this file was supposed to be a simple wrapper, but as we add more logic in it. It's worth adding tests for the additional logic. Especially now we have an ongoing integration worth with the new runtime interface (CRI), it'd be best to add test for new changes to ensure that any regression would be caught in the new implementation. 

The `applyDefaultImageTag` function actually has [a test](https://github.com/kubernetes/kubernetes/blob/9f1c3a4c562a1b5ab96a4c43d95c5c39d80fbec5/pkg/kubelet/dockertools/docker_test.go#L160). In the same file, there are other image pulling tests as well. You can just add higher-level image pulling test there.

**Comment by dims** [comment]
@yujuhong LOL, of course :)

File: pkg/kubelet/dockertools/kube_docker_client.go [hunk 3]
```diff
@@ -184,6 +184,10 @@ func (d *kubeDockerClient) InspectImage(image string) (*dockertypes.ImageInspect
 		}
 		return nil, err
 	}
+	if !matchImageTagOrSHA(resp, image) {
+		err = imageNotFoundError{ID: image}
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/kube_docker_client.go]: nit: just `return nil, imageNotFoundError{ID: image}`

File: pkg/kubelet/dockertools/docker.go [hunk 4]
```diff
@@ -150,6 +150,31 @@ func filterHTTPError(err error, image string) error {
...
+		}
+	}
+	// Look specifically for short and long sha(s)
+	if size := len(parts[1]); size == 12 || size == 64 {
+		if strings.Contains(inspected.ID, "sha256:"+parts[1]) {
+			// We found the short or long SHA requested
+			return true
+		}
+	}
+	glog.V(4).Infof("inspected image (%q) does not match %s", inspected.ID, image)
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker.go]: nit: s/inspected/Inspected

File: pkg/kubelet/dockertools/docker.go [hunk 5]
```diff
@@ -150,6 +150,31 @@ func filterHTTPError(err error, image string) error {
...
+	}
+	// Check the RepoTags for an exact match
+	for _, tag := range inspected.RepoTags {
+		if tag == image {
+			// We found a specific tag that we were looking for
+			return true
+		}
+	}
+	// Look specifically for short and long sha(s)
+	if size := len(parts[1]); size == 12 || size == 64 {
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker.go]: Why does this look for short/long sha specifically. Does k8s validate the image string in the apiserver?

Comment (dims) [inline pkg/kubelet/dockertools/docker.go]: @yujuhong We are trying to compensate for the way the Docker API works here. We want to allow the user to specify either a short SHA or a long SHA and that should work properly. If they give any other string we need to make sure that string is a tag and would not match a sha as shown by the issue #30355. I have an explicit unit test for this condition the user faced to make sure we don't regress.

File: pkg/kubelet/dockertools/kube_docker_client.go (hunk 3 above)
Comment (dims) [inline pkg/kubelet/dockertools/kube_docker_client.go]: Done

File: pkg/kubelet/dockertools/docker.go (hunk 4 above)
Comment (dims) [inline pkg/kubelet/dockertools/docker.go]: Done. Are the rules for capitalized written down somewhere? Thanks!

File: pkg/kubelet/dockertools/docker.go (hunk 5 above)
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker.go]: > If they give any other string we need to make sure that string is a tag and would not match a sha

My problem with that is if we don't validate the "Image" string in the apiserver, users can specify a string "sha256:.." of any length. In that case, should we still verify that the partial string matches the complete sha? I think we should do that anyway.

File: pkg/kubelet/dockertools/docker.go [hunk 6]
```diff
@@ -150,6 +150,31 @@ func filterHTTPError(err error, image string) error {
 	}
 }
 
+// Check if the inspected image matches what we are looking for
+func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
+	parts := strings.SplitN(image, ":", 2)
+	if len(parts) == 1 {
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker.go]: Can we reuse the same dockerref code for parsing the given string? https://github.com/kubernetes/kubernetes/blob/9f1c3a4c562a1b5ab96a4c43d95c5c39d80fbec5/pkg/kubelet/dockertools/docker.go#L161

**Comment by yujuhong** [comment]
```
!!! 'gofmt -s -w' needs to be run on the following files: 
./pkg/kubelet/dockertools/docker_test.go
FAILED   hack/make-rules/../../hack/verify-gofmt.sh	11s
```

**Comment by smarterclayton** [comment]
This is too aggressive - it is broken on valid Docker 1.9 and 1.10 deployments where the image is in the v1 registry format (the version on disk of the ID != the pull digest because Docker).

This needs to be reverted for 1.4 or Docker 1.10 clusters cannot pull v1 schema images by digest, or the check needs to be strict.

**Comment by smarterclayton** [comment]
@kubernetes/sig-node @ncdc @derekwaynecarr this is the same problem as the imageID value being discussed in sig-node - we cannot rely on this check until we drop support for Docker 1.10.

**Comment by smarterclayton** [comment]
Also, you have to check RepoDigests as well

**Comment by ncdc** [comment]
You could maybe only do this check if the image pull spec contains a tag, which would at least address the original issue. And defer the digest check until we resolve #32159.

**Comment by yujuhong** [comment]
> Also, you have to check RepoDigests as well

@smarterclayton, is the `RepoDigests` always correct? Can we switch to using that instead?

**Comment by smarterclayton** [comment]
It looks correct on the Red Hat 1.10 I have but I don't think it was supported in Docker 1.9.  Did we make a formal statement that we dropped 1.9?

**Comment by smarterclayton** [comment]
I'm much less confident in RepoDigests being correct on every Docker variant version - probably couldn't say without trying a fair number of them.

**Comment by yujuhong** [comment]
> It looks correct on the Red Hat 1.10 I have but I don't think it was supported in Docker 1.9. Did we make a formal statement that we dropped 1.9?

I just checked 1.9 on my desktop and it reported correct RepoDigest nonetheless:
```
    "Id": "c38cc6bc48807ea450f17762c784114de8bf74ec1f33eab62b68d931f82ad167",
    "RepoTags": [],
    "RepoDigests": [
        "centos/ruby-23-centos7@sha256:940584acbbfb0347272112d2eb95574625c0c60b4e2fdadb139de5859cf754bf"
    ],
```

**Comment by smarterclayton** [comment]
Tomorrow I'll have someone look at the various 1.10 versions and make sure they're correct against schema 1.10.  If i can prove that RepoDigest is correct I'll change the patch to prefer RepoDigests for a prefix match and then fall back to ID.  The prefix match seemed slightly questionable, but I assume we validated there was no security risk in that?

**Comment by yujuhong** [comment]
@smarterclayton thanks! Should we hold on to the PR #32627 for now until this is verified?

**Comment by yujuhong** [comment]
> but I assume we validated there was no security risk in that?

The motivation of adding this check is because docker's image inspection syntax is too loose and may mix up tags and digests. This is merely a sanity check to make sure docker has the right image. What security risk do you have in mind?

**Comment by smarterclayton** [comment]
The prefix matching wasn't bounded, so you could get partial matches on tags by specifying part of a name that didn't end on a boundary:

pull "foo/bar:latest" would match "server/foo/bar:latest" as well as "superfoo/bar:latest"

**Comment by yujuhong** [comment]
Yes, I had that in the [comment](https://github.com/kubernetes/kubernetes/blob/b9ad337bbdbc5e929491331325d521ae26619e83/pkg/kubelet/dockertools/docker.go#L173) and also in the comment from the PR https://github.com/kubernetes/kubernetes/pull/30789#discussion_r75557212. There will be false positives. The alternative is to hard code the docker default registry (`docker.io`).

**Comment by smarterclayton** [comment]
That's not enough because the default registry can be remapped.  Basically, no tag prefix checking is really safe or accurate.

**Comment by smarterclayton** [comment]
Only a SHA and a force verification can help

**Comment by yujuhong** [comment]
> That's not enough because the default registry can be remapped. Basically, no tag prefix checking is really safe or accurate.

Yes, it's a best effort check, which is better than nothing IMO.

**Comment by smarterclayton** [comment]
But if it fails, you've broken a user who is doing something the container
engine allows.

**Comment by smarterclayton** [comment]
The tag check in this case fails closed (safer) but breaks allowed
scenarios.  Remapping is really common in OpenShift production deployments
- I'd say at least 50% of the enterprises I know of deploying docker at
scale use registry remapping.

**Comment by yujuhong** [comment]
@smarterclayton I meant the current check (which checks only the suffix matches) allow false positives, so that it's not so strict, but would still catch some cases.


> - I'd say at least 50% of the enterprises I know of deploying docker at
> scale use registry remapping.

That's why I didn't hard code the registry name to enforce a more strict check.

**Comment by ncdc** [comment]
Given that a prefix match against the inspected image's ID will match the `config.digest` of a schema version 2 image manifest, which is not a valid pull-by-id spec, the only way a prefix match can work is if you know:

1. Node N has an image with ID A already on it (and remember, that's not the pull spec)
1. Your pod specifies a container to run image ID A
1. Your pod is scheduled to node N

**Comment by yujuhong** [comment]
@ncdc I was talking about the "tag" check, not the digest check :-)
