### PR TITLE
e2e flake fix: Namespace controller error handling improvements

### LINKED ISSUE #21406: Handle errors in namespace controller sync
If the namespace controller gets an error when doing a sync and the error is not a `contentRemainingError` error the error will not be handled.

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go#L112-L113

Ran in to this when we found https://github.com/kubernetes/kubernetes/pull/21340.   When deleting a namespace it received a `NotFound` error that wasn't reported anywhere and the namespace stuck in `Terminating` because a finalizer was left.

### LINKED ISSUE #22045: e2e flake: Namespace wasn't deleted correctly
It seems there is some bug around namespace controller. What happened is:

    08:05:39 STEP: Collecting events from namespace "e2e-tests-density-b5lqr".
    08:05:39 STEP: Destroying namespace "e2e-tests-density-b5lqr" for this suite.
    09:05:40 Feb 25 09:05:40.322: FAIL: Couldn't delete ns "e2e-tests-density-b5lqr": namespace e2e-tests-density-b5lqr was not deleted within limit: timed out waiting for the condition, pods remaining: []

So basically, namespace wasn't deleted for the whole hour.
Then the next test actually timed out

    09:05:40 Feb 25 09:05:40.997: INFO: >>> testContext.KubeConfig: /jenkins-master-data/jobs/kubernetes-kubemark-gce/workspace/kubernetes/test/kubemark/kubeconfig.loc
    09:05:40 
    09:05:41 Feb 25 09:05:41.182: INFO: Waiting for terminating namespaces to be deleted...
    09:46:36 
    Build timed out (after 120 minutes). Marking the build as failed.

So in total, namespace wasn't deleted for more than 90 minutes (note that usually it takes ~2-3 minutes for density test).

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-kubemark-gce/5970/build-log.txt

The problem is that we can't really debug it, since we don't have logs from k8s components if build times out. - @ixdy @spxtr @kubernetes/goog-testing

### PR DESCRIPTION
**Pull request by derekwaynecarr**
If an unexpected error is encountered during namespace deletion, automatically add the namespace back to the processing queue rather than wait for a full resync and log it.  If the error is a content remaining error, we continue to wait for the time estimate, but we now have a proper crash handler.

fixes #21406

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Ah, opened this too quick, closing, will reopen when ready.

**Comment by wojtek-t** [comment]
@derekwaynecarr - what was wrong with this PR?

**Comment by derekwaynecarr** [comment]
@wojtek-t - nothing it turns out... i had wanted to run e2e myself once.

**Comment by derekwaynecarr** [comment]
i had forgot i was running a stress e2e test at the same time as i kicked off a new e2e and had weird flakes for a moment, anyway, this is good to go.

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 1]
```diff
@@ -244,6 +244,9 @@ func syncNamespace(kubeClient clientset.Interface, versions *unversioned.APIVers
 	// we have removed content, so mark it finalized by us
 	result, err := retryOnConflictError(kubeClient, namespace, finalizeNamespaceFunc)
 	if err != nil {
+		if errors.IsNotFound(err) {
```
Comment (wojtek-t) [inline pkg/controller/namespace/namespace_controller_utils.go]: I'm not convinved about this - if we return "not found" error, it doesn't meen that it finished succefully - there might still be objects to remove. Or am I missing something?

Comment (derekwaynecarr) [inline pkg/controller/namespace/namespace_controller_utils.go]: It's not possible for a namespace to be deleted when its list of finalizers is non-empty.

see: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/namespace/etcd/etcd.go#L110

So if we ever got a not found error here, the namespace is gone, and all content should be gone.  I worried about the error here in cases where a cluster found itself running two instances of controllermanager inadvertently.

Comment (wojtek-t) [inline pkg/controller/namespace/namespace_controller_utils.go]: Oh yeah - sure, sorry. Somehow I though it's doing "deleteContent" here, not "finalizing".
Yes - it looks ok. Thanks for explanation.

Maybe it's wort adding a comment, that it's mostly about protecting from two controllers doing their work?

**Comment by wojtek-t** [comment]
Just one minor comment - feel free to self-lgtm it. Thanks!

**Comment by derekwaynecarr** [comment]
Added comment, marking lgtm per @wojtek-t agreement.

**Comment by wojtek-t** [comment]
LGTM - thanks!

File: pkg/controller/namespace/namespace_controller.go [hunk 2]
```diff
@@ -112,11 +112,16 @@ func (nm *NamespaceController) worker() {
...
 					go func() {
+						defer utilruntime.HandleCrash()
 						t := estimate.Estimate/2 + 1
 						glog.V(4).Infof("Content remaining in namespace %s, waiting %d seconds", key, t)
 						time.Sleep(time.Duration(t) * time.Second)
 						nm.queue.Add(key)
 					}()
+				} else {
+					// rather than wait for a full resync, re-add the namespace to the queue to be processed
+					nm.queue.Add(key)
```
Comment (wojtek-t) [inline pkg/controller/namespace/namespace_controller.go]: Actually wait (I mean not wait with this PR, it's correct, but wait with  #22045).

Now I think, it that was something different, because even if we don't readd it here, we will sec the namespace every resync period, which is now 5 minutes:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/options/options.go#L61

If that's the case, if we didn't remove the namespace for 1h30m (which was the case in that issue), this would mean that we had errors that we didn't handled correctly ~100 times, which seems quite non-realistic.
@derekwaynecarr - am I missing something?

Comment (derekwaynecarr) [inline pkg/controller/namespace/namespace_controller.go]: I was hoping the logging would have shown the underlying cause of 22045, but I am fine removing the fixes until we have that logging.

Comment (wojtek-t) [inline pkg/controller/namespace/namespace_controller.go]: Thanks - I thought that I missed something.
