### PR TITLE
bug: fix segfault when EnableServiceLinks is nil

### LINKED ISSUE #71749: kubelet 1.13.0 panic when run against 1.12.x kube-apiserver
**What happened**:

Kubelet panics after registering node

**What you expected to happen**:

Kubelet should not panic

**How to reproduce it (as minimally and precisely as possible)**:

Use kubelet on an ARM64 machine (i'm on Scaleway provider)

**Anything else we need to know?**:

I upgraded from 1.12.3 to 1.13.0

here is the statup log (only the end):

```
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: I1205 14:17:18.151924    5523 reconciler.go:154] Reconciler: start to sync state
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: I1205 14:17:18.327832    5523 kubelet_node_status.go:114] Node scw-xxxxxx was previously registered
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: I1205 14:17:18.327924    5523 kubelet_node_status.go:75] Successfully registered node scw-xxxxxx
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: E1205 14:17:18.356785    5523 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /usr/local/go/src/runtime/asm_arm64.s:412
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /usr/local/go/src/runtime/panic.go:513
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /usr/local/go/src/runtime/panic.go:82
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /usr/local/go/src/runtime/signal_unix.go:390
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:546
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:449
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:192
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:115
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:741
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1689
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:824
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:174
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:183
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:221
Dec 05 14:17:18 scw-xxxxxx kubelet[5523]: /usr/local/go/src/runtime/asm_arm64.s:1114
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.0
- Cloud provider or hardware configuration: Scaleway
- OS (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): 4.15.11-mainline-rev1
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by joejulian**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When upgrading to 1.13, pods that were created prior to the upgrade have
no pod.Spec.EnableServiceLinks set. This causes a segfault and prevents
the pod from ever starting.

Check and set to the default if nil

**Which issue(s) this PR fixes**:

Fixes #71749

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -533,6 +533,10 @@ func (kl *Kubelet) getServiceEnvVarMap(ns string, enableServiceLinks bool) (map[
 // Make the environment variables for a pod in the given namespace.
 func (kl *Kubelet) makeEnvironmentVariables(pod *v1.Pod, container *v1.Container, podIP string) ([]kubecontainer.EnvVar, error) {
 	var result []kubecontainer.EnvVar
+    if pod.Spec.EnableServiceLinks == nil {
+        enableServiceLinks := v1.DefaultEnableServiceLinks
+        pod.Spec.EnableServiceLinks = &enableServiceLinks
```
Comment (tallclair) [inline pkg/kubelet/kubelet_pods.go]: I don't think it's safe to modify the pod spec here. better to just use a local variable:
```go
enableServiceLinks := v1.DefaultEnableServiceLinks
if pod.Spec.EnableServiceLinks != nil {
  enableServiceLinks = *pod.Spec.EnableServiceLinks
}
```

**Comment by joejulian** [comment]
rebased

**Comment by liggitt** [comment]
> pods that were created prior to the upgrade have no pod.Spec.EnableServiceLinks set

That should not be the case if the api server is at 1.13 or above. Defaults are applied when reading previously persisted pods out of etcd as well.
