### PR TITLE
Switch kube-proxy to informers & save 2/3 of cpu & memory of non-iptables related code.

### LINKED ISSUE #42000: Possible regression in pod-startup-time
In the last 10 runs of kubemark-500, 4-of them failed with "too high pod-startup-time".
We've never had problems with it before.

The failures are:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2777
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2782
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2784
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/2785

Should be investigated.

@shyamjvs @gmarek

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #42000

This PR should be no-op from the behavior perspective.
It is changing KubeProxy to use standard "informer" framework instead of combination of reflector + undelta store.

This is significantly reducing CPU usage of kube-proxy and number of memory allocations.
Previously, on every endpoints/service update, we were copying __all__ endpoints/services at least 3 times, now it is once (which should also be removed in the future).

In Kubemark-500, hollow-proxies were processing backlog from load test for an hour after the test was finishing. With this change, it is keeping up with the load.

@thockin @ncdc @derekwaynecarr

### CODE REVIEW

File: pkg/proxy/config/api.go [hunk 1]
```diff
@@ -21,55 +21,136 @@ import (
...
-func NewServiceStore(store cache.Store, ch chan<- ServiceUpdate) cache.Store {
-	fn := func(objs []interface{}) {
-		var services []api.Service
-		for _, o := range objs {
-			services = append(services, *(o.(*api.Service)))
+func sendAddService(servicesChan chan<- ServiceUpdate) func(obj interface{}) {
+	return func(obj interface{}) {
+		service, ok := obj.(*api.Service)
+		if !ok {
+			glog.Errorf("cannot convert to *api.Pod: %v", obj)
```
Comment (smarterclayton) [inline pkg/proxy/config/api.go]: utilruntime.HandleError.  Always :)

File: pkg/proxy/config/api.go [hunk 2]
```diff
@@ -21,55 +21,136 @@ import (
...
+}
+
+func sendUpdateService(servicesChan chan<- ServiceUpdate) func(oldObj, newObj interface{}) {
+	return func(_, newObj interface{}) {
+		service, ok := newObj.(*api.Service)
+		if !ok {
+			glog.Errorf("cannot convert to *api.Pod: %v", newObj)
+			return
+		}
+		servicesChan <- ServiceUpdate{Op: ADD, Service: service}
```
Comment (smarterclayton) [inline pkg/proxy/config/api.go]: Hrm - shouldn't this be SET?

File: pkg/proxy/config/api.go [hunk 3]
```diff
@@ -21,55 +21,136 @@ import (
...
+}
+
+func sendUpdateEndpoints(endpointsChan chan<- EndpointsUpdate) func(oldObj, newObj interface{}) {
+	return func(_, newObj interface{}) {
+		endpoints, ok := newObj.(*api.Endpoints)
+		if !ok {
+			glog.Errorf("cannot convert to *api.Endpoints: %v", newObj)
+			return
+		}
+		endpointsChan <- EndpointsUpdate{Op: ADD, Endpoints: endpoints}
```
Comment (smarterclayton) [inline pkg/proxy/config/api.go]: Why not SET?

File: pkg/kubemark/hollow_proxy.go [hunk 4]
```diff
@@ -73,7 +73,7 @@ func NewHollowProxyOrDie(
 	}
 	proxyconfig.NewSourceAPI(
 		client.Core().RESTClient(),
-		30*time.Second,
+		15*time.Minute,
```
Comment (smarterclayton) [inline pkg/kubemark/hollow_proxy.go]: Reasoning?

**Comment by smarterclayton** [comment]
/approve

A few questions, mostly as to removing SET and how that impacts how rules are set.  I follow the logic of the change though and agree getting rid of undelta store is the right thing.

File: pkg/proxy/config/api.go (hunk 2 above)
Comment (wojtek-t) [inline pkg/proxy/config/api.go]: Both Add and Update are handled exactly the same way later.

Previously "SET" was actually a "REPLACE" so wanted to avoid confusion with the previous version.

File: pkg/kubemark/hollow_proxy.go (hunk 4 above)
Comment (wojtek-t) [inline pkg/kubemark/hollow_proxy.go]: Consistency with production kube-proxy:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/options/options.go#L63

File: pkg/proxy/config/api.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/proxy/config/api.go]: done

File: pkg/proxy/config/api.go (hunk 2 above)
Comment (wojtek-t) [inline pkg/proxy/config/api.go]: @smarterclayton - do you think it makes sense to introduce "SET" here and have it handled always the same way as ADD?
Or maybe we should rename "ADD" to "SET"?

**Comment by wojtek-t** [comment]
@smarterclayton - thanks for looking. I fixed some of your comments and asked some questions about of of them. PTAL

File: pkg/proxy/config/api.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/proxy/config/api.go]: So in the very beginning, ADD and SET were handled differently (to convey the difference).  If nothing in the subsequent steps cares about the difference (they probably shouldn't), I'd be happy having this be SET (or ADD) in all cases.

File: pkg/kubemark/hollow_proxy.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/kubemark/hollow_proxy.go]: Oh, missed it.  Ok.

File: pkg/proxy/config/api_test.go [hunk 5]
```diff
@@ -174,24 +165,16 @@ func TestNewEndpointsSourceApi_UpdatesAndMultipleEndpoints(t *testing.T) {
...
-	got, ok := <-ch
-	if !ok {
-		t.Errorf("Unable to read from channel when expected")
-	}
-	expected := EndpointsUpdate{Op: SET, Endpoints: []api.Endpoints{}}
-	if !apiequality.Semantic.DeepEqual(expected, got) {
-		t.Errorf("Expected %#v; Got %#v", expected, got)
-	}
+	endpointsController := NewEndpointsController(lw, 30*time.Second, ch)
+	go endpointsController.Run(wait.NeverStop)
```
Comment (wojtek-t) [inline pkg/proxy/config/api_test.go]: > So this used to be meaningful, in that the first update was a "clear" if there were no endpoints

Sorry - don't understand this. Can you please clarify?

But anyway, I agree that previously "SET" was handled differently than "ADD", because:
- ADD was used only in unit tests (i.e. production code was never issuing ADD) - it was always taking all contents from the underlying store and calling "SET" (meaning "replace") from those contents (no matter if it was add, update or remove).

However, with the controller framework, "REPLACE" is not an external concept.
If we are doing relist, controller internally is handling it - it is computing the difference and sending appropriate Add, Update and Remove calls if needed to match the desired state.
The same for resync (though since resync is called from in-memory state, there are pretty much only update handlers called).

That means, that since those are internal details of controller framework, we don't have a good was for forcing it. Also, those are already tested at the level of Informer, so testing framework internals here doesn't sound like a good idea to me.

But if you don't agree, can you please clarify what exactly you want to be tested, since I'm not sure I understood it correctly.

**Comment by smarterclayton** [comment]
Flake was https://github.com/kubernetes/kubernetes/issues/41892

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

File: pkg/proxy/config/api_test.go (hunk 5 above)
Comment (smarterclayton) [inline pkg/proxy/config/api_test.go]: I want to be sure that 

1. Kube-proxy doesn't do anything incorrect until initial sync
2. Resync doesn't reset state of the proxy to "no services"

File: pkg/proxy/config/api.go [hunk 6]
```diff
@@ -17,59 +17,140 @@ limitations under the License.
...
+	return func(obj interface{}) {
+		var service *api.Service
+		switch t := obj.(type) {
+		case *api.Service:
+			service = t
+		case cache.DeletedFinalStateUnknown:
+			var ok bool
+			service, ok = t.Obj.(*api.Service)
+			if !ok {
+				utilruntime.HandleError(fmt.Errorf("cannot convert to *api.Pod: %v", t.Obj))
```
Comment (justinsb) [inline pkg/proxy/config/api.go]: api.Service

File: pkg/proxy/config/api.go [hunk 7]
```diff
@@ -17,59 +17,140 @@ limitations under the License.
...
+				return
+			}
+		default:
+			utilruntime.HandleError(fmt.Errorf("cannot convert to *api.Pod: %v", t))
```
Comment (justinsb) [inline pkg/proxy/config/api.go]: api.Service

File: pkg/proxy/config/api_test.go (hunk 5 above)
Comment (justinsb) [inline pkg/proxy/config/api_test.go]: I think by #1 here you mean "Make sure that the List has fully completed before we do anything with the state", and a big +1 on that...  I think we've seen that bug in a few controllers.  But ... did this bug also exist previously (if not, can someone point me to magic where it was avoided?)

(Also in general, if anyone has a good doc on Informers vs Reflectors vs direct-watching.  I prefer direct-watching, but I guess that means I have all sort of edge cases in my code.)

File: pkg/proxy/config/api.go [hunk 8]
```diff
@@ -17,59 +17,140 @@ limitations under the License.
...
+	return func(obj interface{}) {
+		var endpoints *api.Endpoints
+		switch t := obj.(type) {
+		case *api.Endpoints:
+			endpoints = t
+		case cache.DeletedFinalStateUnknown:
+			var ok bool
+			endpoints, ok = t.Obj.(*api.Endpoints)
+			if !ok {
+				utilruntime.HandleError(fmt.Errorf("cannot convert to *api.Endpoints: %v", t.Obj))
```
Comment (justinsb) [inline pkg/proxy/config/api.go]: Is it our belief that this does not happen?

Because we do have the `Key`, which does have the Name & Namespace, which is all we need.  We even have `SplitMetaNamespaceKey` which splits them (and a TODO to replace the whole string-packing in go2)

**Comment by justinsb** [comment]
@k8s-bot kops aws e2e test this

**Comment by justinsb** [comment]
(The kops AWS failure was `NetworkPlugin kubenet failed on the status hook for pod "nginx-562755153-kw4k9_e2e-tests-deployment-sxtkc": Unexpected command output nsenter: cannot open : No such file or directory` which I can't think is related.)

**Comment by justinsb** [comment]
Oh actually, that error is in some other logs also, e.g. https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/42108/pull-kubernetes-e2e-gce/20098/artifacts/e2e-gce-agent-pr-37-0-minion-group-pjmc/kubelet.log  Came up in #41225 also

File: pkg/proxy/config/config.go [hunk 9]
```diff
@@ -31,28 +31,21 @@ type Operation int
 
 // These are the available operation types.
 const (
-	SET Operation = iota
-	ADD
+	ADD Operation = iota
```
Comment (smarterclayton) [inline pkg/proxy/config/config.go]: We use add and remove consistently in event informers, I would prefer not to drift into othe syntax.  This is ultimately referring to membership change in a set.

File: pkg/proxy/config/api.go (hunk 8 above)
Comment (smarterclayton) [inline pkg/proxy/config/api.go]: DeltaFIFO is not required to return a valid object on delete.

Comment (smarterclayton) [inline pkg/proxy/config/api.go]: So this code should cover both paths as Justin noted

File: pkg/proxy/config/config.go (hunk 9 above)
Comment (justinsb) [inline pkg/proxy/config/config.go]: Fair enough.  We can debate set axioms some other time :-)

**Comment by justinsb** [comment]
@k8s-bot kops aws e2e test this issue #42086

File: pkg/proxy/config/config.go [hunk 10]
```diff
@@ -118,38 +111,26 @@ func (c *EndpointsConfig) Config() []api.Endpoints {
...
-		glog.V(5).Infof("Setting endpoints %s", spew.Sdump(update))
-		// Clear the old map entries by just creating a new map
-		endpoints = make(map[types.NamespacedName]api.Endpoints)
-		for _, value := range update.Endpoints {
-			name := types.NamespacedName{Namespace: value.Namespace, Name: value.Name}
-			endpoints[name] = value
-		}
+		glog.V(5).Infof("Removing an endpoint %s", spew.Sdump(update.Endpoints))
+		name := types.NamespacedName{Namespace: update.Endpoints.Namespace, Name: update.Endpoints.Name}
+		delete(endpoints, name)
```
Comment (justinsb) [inline pkg/proxy/config/config.go]: Never mind ... this is nonsense :-)

File: pkg/proxy/config/api.go (hunk 8 above)
Comment (wojtek-t) [inline pkg/proxy/config/api.go]: I don't understand. I think the only it can return is the cache.DeletedFinalStateUnknown.

I'm 100% sure that if this is not true, then we have at least 10+ places in the code which are not handling this one correctly. And a bunch of other different controllers won't be working correctly.

File: pkg/proxy/config/api_test.go (hunk 5 above)
Comment (wojtek-t) [inline pkg/proxy/config/api_test.go]: I agree with 1 - (though us @justinsb wrote, I think it also wasn't handled correctly before).
Will add on Monday morning.

Regarding 2 - this is covered by Informer (DeltaFifo) tests.

File: pkg/proxy/config/api.go (hunk 8 above)
Comment (wojtek-t) [inline pkg/proxy/config/api.go]: So what I wanted to say is basically - the case of unknown final state this is exactly:
"cache.DeletedFinalStateUnknown" what it returned here and it contains Obj which is a correct api.Service (or whatever we are watching), contains correct Name and Namespace etc., but may potentially contain state state of the object.

Which means that I'm handling this case (exactly the same is it is handled in other places).

File: pkg/proxy/config/config.go (hunk 9 above)
Comment (wojtek-t) [inline pkg/proxy/config/config.go]: OK - so I will explicitly change it to contain: "ADD", "UPDATE" and "REMOVE" actions, and will just handle ADD and UPDATE the same in the handling code - I agree this is cleaner and will be consistent with our codebase.

Comment (wojtek-t) [inline pkg/proxy/config/config.go]: Fixed.

File: pkg/proxy/config/api_test.go (hunk 5 above)
Comment (wojtek-t) [inline pkg/proxy/config/api_test.go]: So regarding one - it seems it's not easy to handle (and this is not the regression).
Basically, both before and now, with the initial "LIST" operation (of the underlying reflector), we are sending the ADD events from the results of it one by one, and then passing to proxier.

We need a better way to handle it, but since this is not a regression, I would prefer fixing it in a separate PR (I can try sending it later today).

**Review by wojtek-t — COMMENTED** [review]
@smarterclayton - PTAL

File: pkg/proxy/config/api_test.go (hunk 5 above)
Comment (smarterclayton) [inline pkg/proxy/config/api_test.go]: That's fine
