### PR TITLE
fix GPU resource validation that incorrectly allows zero limits

### LINKED ISSUE #50182: GPU resource validation incorrectly allows zero limits
The [validation logic](https://github.com/kubernetes/kubernetes/blob/886e04f1fffbb04faf8a9f9ee141143b2684ae68/pkg/api/v1/validation/validation.go#L49) for GPUs is not run if limits is not set for GPUs. 
We need to check limits equals requests even if just request is set for GPUs.

@jiayingz can you fix this bug? This may be a good starter bug in k8s.

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

The validation logic for GPUs is not run if limits is not set for GPUs.
We need to check limits equals requests even if just request is set for GPUs.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50182

**Special notes for your reviewer**:
/assign @vishh 
/cc @jiayingz 

**Release note**:

```release-note
fix GPU resource validation that incorrectly allows zero limits
```

### CODE REVIEW

**Comment by vishh** [comment]
@dixudx I appreciate posting this PR. Your contributions are much welcome. In the future, can I request you to mention explicitly that you are working on a fix for an issue before you post a patch?
This will help avoid multiple people spending time on the same problem. Co-ordination is a but difficult in an OSS project. Your cooperation is much appreciated :)

File: pkg/api/v1/validation/validation.go [hunk 1]
```diff
@@ -60,6 +60,15 @@ func ValidateResourceRequirements(requirements *v1.ResourceRequirements, fldPath
 		allErrs = append(allErrs, validateContainerResourceName(string(resourceName), fldPath)...)
 		// Validate resource quantity.
 		allErrs = append(allErrs, ValidateResourceQuantityValue(string(resourceName), quantity, fldPath)...)
+
+		// For GPUs, not only requests can't exceed limits, they also can't be lower, i.e. must be equal.
```
Comment (vishh) [inline pkg/api/v1/validation/validation.go]: This comment is not appropriate to the check down below

Comment (dixudx) [inline pkg/api/v1/validation/validation.go]: @vishh Updated. PTAL. Thanks.

Also many thanks for your kind reminder.

File: pkg/api/v1/validation/validation.go [hunk 2]
```diff
@@ -60,6 +60,15 @@ func ValidateResourceRequirements(requirements *v1.ResourceRequirements, fldPath
 		allErrs = append(allErrs, validateContainerResourceName(string(resourceName), fldPath)...)
 		// Validate resource quantity.
 		allErrs = append(allErrs, ValidateResourceQuantityValue(string(resourceName), quantity, fldPath)...)
+
+		// For GPUs, limits has to be set equal to requests.
+		if resourceName == v1.ResourceNvidiaGPU {
```
Comment (xiangpengzhao) [inline pkg/api/v1/validation/validation.go]: Since limits has to be set equal to requests for GPU, would it be better to set limits defaulting to requests if limits not configured? @vishh

Comment (thockin) [inline pkg/api/v1/validation/validation.go]: Unfortunately, we don't really have any precedent for request/limit defaulting per-resource.  I sort of wish we did.  What do you think @vishh

Comment (xiangpengzhao) [inline pkg/api/v1/validation/validation.go]: IIRC, for resources like CPU/memory, if their requests are not configured, they will be defaulted to the limits.

**Comment by thockin** [comment]
AFAIK, the default for both CPU and RAM if limit is unspecified is "inf".

https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-ram-container/

Why can't GPU just ignore limit - it's kind of semantically silly?

**Comment by xiangpengzhao** [comment]
>AFAIK, the default for both CPU and RAM if limit is unspecified is "inf".

Correct. But what I meant is that if _limit is specified but request is unspecified_, request will default to limit. @vishh right?

**Comment by dixudx** [comment]
@xiangpengzhao 

> if limit is specified but request is unspecified, request will default to limit.

Exactly.

File: pkg/api/v1/validation/validation.go (hunk 2 above)
Comment (vishh) [inline pkg/api/v1/validation/validation.go]: Every line of code we introduce that's per resource makes the system harder to explain.
GPUs will be kicked out to an extension sometime soon. So I don't think its worth expanding the validation logic just for GPUs.

**Comment by vishh** [comment]
> Why can't GPU just ignore limit - it's kind of semantically silly?

@thockin specifying request for GPUs is silly as well since GPUs (or any non shared resource) cannot exceed their requests. 
I think the validation logic could have been `limits must be specified for GPUs and request must equal limits`. If only limits is specified, validation would always pass due to defaulting.

**Comment by vishh** [comment]
@dixudx We need unit tests for this PR.

File: pkg/api/v1/validation/validation.go [hunk 3]
```diff
@@ -60,6 +60,15 @@ func ValidateResourceRequirements(requirements *v1.ResourceRequirements, fldPath
 		allErrs = append(allErrs, validateContainerResourceName(string(resourceName), fldPath)...)
 		// Validate resource quantity.
 		allErrs = append(allErrs, ValidateResourceQuantityValue(string(resourceName), quantity, fldPath)...)
+
```
Comment (vishh) [inline pkg/api/v1/validation/validation.go]: I feel the check under `limits` validation can be merged into this logic.
1. If limits are specified and requests aren't specified, requests will equal limits. The logic here will be hit.
2. If limits aren't specified and request is, then this logic will be hit as well.
3. If neither is specified, we do not care.

**Comment by dixudx** [comment]
@vishh @thockin Updated. PTAL. Thanks.

**Comment by dixudx** [comment]
@vishh @thockin Updated. PTAL. Thanks.

**Comment by vishh** [comment]
/lgtm
/approve

@thockin This PR is ready for your review (again)

File: pkg/api/v1/validation/validation.go [hunk 4]
```diff
@@ -42,24 +42,26 @@ func ValidateResourceRequirements(requirements *v1.ResourceRequirements, fldPath
...
 	}
 	for resourceName, quantity := range requirements.Requests {
 		fldPath := reqPath.Key(string(resourceName))
 		// Validate resource name.
 		allErrs = append(allErrs, validateContainerResourceName(string(resourceName), fldPath)...)
 		// Validate resource quantity.
 		allErrs = append(allErrs, ValidateResourceQuantityValue(string(resourceName), quantity, fldPath)...)
+
+		// Check that request <= limit.
+		limitQuantity, exists := requirements.Limits[resourceName]
```
Comment (thockin) [inline pkg/api/v1/validation/validation.go]: Why does this function exist in 2 places?  @caesarxuchao your fingerprints are on the commit that copied these functions into versioned.  Why?  This is a nightmare for updates like this - who would expect this code to be in two places?

Comment (xiangpengzhao) [inline pkg/api/v1/validation/validation.go]: +1, there are also other functions which exist in two places. We DO NOT want to maintain things this way.

See one example: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/service/util.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/service/util.go

They almost have the same functions. We'd better only keep one copy.

Comment (xiangpengzhao) [inline pkg/api/v1/validation/validation.go]: Tim, I sent an issue to track this. https://github.com/kubernetes/kubernetes/issues/50653

Comment (xiangpengzhao) [inline pkg/api/v1/validation/validation.go]: As per https://github.com/kubernetes/kubernetes/issues/50653#issuecomment-322365714 by @liggitt , we should keep them as-is...

**Comment by dixudx** [comment]
ping @vishh @thockin 
Rebased. PTAL. Need your approve again. Thanks.

File: pkg/api/v1/validation/validation.go (hunk 4 above)
Comment (caesarxuchao) [inline pkg/api/v1/validation/validation.go]: Agree with liggitt's comment. I'd like to explore if we can make admission controllers operate on versioned objects, because we want to make the life easier for developers of thirdparty admission webhooks.

**Comment by dixudx** [comment]
ping @vishh @thockin @caesarxuchao 

Rebased. PTAL. Need your approve again. Thanks.
