### PR TITLE
Fix GCE kube-down incorrect MIG delete OpID

### LINKED ISSUE #8193: GCE Kube Down MIG Wait Incorrect OpId
@roberthbailey is running in to an issue where the operation ID pulled from the MIG delete command during GCE kube-down is incorrect:
```
$deleteCmdOutput = Managed instance group kubernetes-minion-group is being deleted. Operation: operation-1431541925656-cab1f176-d44b-4d67-b770-76524d597691
$deleteCmdOperationId = Managedin
```

#8096

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #8193

PR #8096 was relying on GNU `sed` behavior to work correctly, so it would break when run from OS X. Fix is to limit ourselves to POSIX `sed` features

Tested on Ubuntu with `sed`, `sed --posix` and on OS X.

CC @quinton-hoole and @roberthbailey

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -653,14 +653,14 @@ function kube-down {
...
-    deleteCmdOperationId=$(echo $deleteCmdOutput | grep "Operation:" | sed "s/.*Operation:\s//" | sed "s/\s.*//" | sed "s/ //g")
+    deleteCmdOperationId=$(echo $deleteCmdOutput | grep "Operation:" | sed "s/.*Operation:[[:space:]]*\([^[:space:]]*\).*/\1/g")
     if [[ "$deleteCmdOperationId" != ""  ]]; then
       deleteCmdStatus="PENDING"
       while [[ "$deleteCmdStatus" != "DONE" ]]
       do
 	sleep 5
         deleteCmdOperationOutput=$(gcloud preview managed-instance-groups --zone "${ZONE}" get-operation $deleteCmdOperationId)
-        deleteCmdStatus=$(echo $deleteCmdOperationOutput | grep -i "status:" | sed "s/.*status:\s//" | sed "s/\s.*//" | sed "s/ //g")
+	deleteCmdStatus=$(echo $deleteCmdOperationOutput | grep -i "status:" | sed "s/.*status:[[:space:]]*\([^[:space:]]*\).*/\1/g")
```
Comment (roberthbailey) [inline cluster/gce/util.sh]: did you mean to change this from spaces to a tab?

File: cluster/gce/util.sh [hunk 2]
```diff
@@ -653,14 +653,14 @@ function kube-down {
     "${NODE_INSTANCE_PREFIX}-group")
   if [[ "$deleteCmdOutput" != ""  ]]; then
     # Managed instance group deletion is done asyncronously, we must wait for it to complete, or subsequent steps fail
-    deleteCmdOperationId=$(echo $deleteCmdOutput | grep "Operation:" | sed "s/.*Operation:\s//" | sed "s/\s.*//" | sed "s/ //g")
+    deleteCmdOperationId=$(echo $deleteCmdOutput | grep "Operation:" | sed "s/.*Operation:[[:space:]]*\([^[:space:]]*\).*/\1/g")
     if [[ "$deleteCmdOperationId" != ""  ]]; then
       deleteCmdStatus="PENDING"
       while [[ "$deleteCmdStatus" != "DONE" ]]
       do
```
Comment (roberthbailey) [inline cluster/gce/util.sh]: the indentation under the do is inconsistent (spaces/tabs) which my editor renders differently than github (way worse).

**Comment by roberthbailey** [comment]
LGTM modulo the spaces vs tabs comments.

**Comment by mbforbes** [comment]
Thanks—this is driving me nuts :boat:

**Comment by saad-ali** [comment]
Tabs replaced with spaces. PTAL

**Comment by roberthbailey** [comment]
Thanks. This isn't covered by any unit tests so merging now.
