### PR TITLE
Fix hpa scaling above max replicas w/ scaleUpLimit

### LINKED ISSUE #53670: HPA scaling above spec.maxReplicas
/kind bug

**What happened**:
Since upgrading to Kube 1.7.6, I'm seeing my HPAs scale above it's maxReplicas.  Because of this, it's rapidly creating pods, then terminating them, and repeat.

**What you expected to happen**:
I expected the HPA to never exceed maxReplicas.

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: monolith-mq-remotefileops
  namespace: na-prod
spec:
  maxReplicas: 4
  minReplicas: 2
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: monolith-mq-remotefileops
```

The HPA is logging:
```
2017-10-10T18:46:22Z: the desired replica count is increasing faster than the maximum scale rate
2017-10-10T18:46:22Z: the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
2017-10-10T18:46:22Z: the HPA controller was able to update the target scale to 8
2017-10-10T18:47:22Z: the desired replica count was more than the maximum replica count
2017-10-10T18:50:52Z: the time since the previous scale is still within both the downscale and upscale forbidden windows
2017-10-10T18:52:23Z: the HPA controller was able to update the target scale to 4
```

This seems to happen with the deployment's spec.resources.request.cpu is low, and the HPA shows the deployment using more than 175% of it's spec.resource.requests.cpu.  If I increase 
 the deployment's spec.resources.request.cpu to better match actual usage (so that the deployment is using 120% or less), it occurs much less often.

I deliberately set the spec.resources.request.cpu low, to ensure services were over provisioned during the first roll out of HPA.

I think the switch in pkg/controller/podautoscaler/horizontal.go after ```scaleUpLimit := calculateScaleUpLimit(currentReplicas)``` should be converted to individual if() statements.

**Anything else we need to know?**:
I am only setting spec.resource.requests.cpu on the deployment, not spec.resource.limits.cpu

Looking at the code in pkg/controller/podautoscaler/horizontal.go, the version that worked (1.6.2) would only scale up and down by 1.  The 1.7.6+ code is attempting to scale up by a larger amount.

The new code seems appropriate in large clusters, where maxReplicas is in the tens or hundreds.  It doesn't seem appropriate for clusters where maxReplicas is in the single digits.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T19:06:19Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:36:08Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
AWS m4.2xlarge, 5 nodes

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`):
```
Linux ip-10-66-46-241 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:
kops Version 1.7.0

- Others:

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What this PR does / why we need it**:

Fix a bug where `desiredReplicas` could be greater than `maxReplicas`
if the original value for `desiredReplicas > scaleUpLimit` and
`scaleUpLimit > maxReplicas`. Previously, when that happened, we would
scale up to `scaleUpLimit`, and then in the next auto-scaling run, scale
down to `maxReplicas`. Address this issue and introduce a regression
test.

**Which issue this PR fixes**

fixes #53670

**Release note**:
```release-note
Address a bug which allowed the horizontal pod autoscaler to allocate `desiredReplicas` > `maxReplicas` in certain instances.
```

### CODE REVIEW

**Comment by mwielgus** [comment]
/lgtm
Please cherry-pick it to 1.7 branch.

**Comment by MaciekPytel** [comment]
@mattjmcnaughton It looks like this doesn't pass gofmt. Can you update the PR?

**Comment by mattjmcnaughton** [comment]
Whoops! Fixed and ready for a final look @mwielgus @MaciekPytel 

Re cherry-picking onto 1.7 and 1.8, is that something I do, or something a bot does, or something the OWNERs do?

Thanks for the quick eyes on this :)

**Comment by MaciekPytel** [comment]
https://github.com/eBay/Kubernetes/blob/master/docs/devel/cherry-picks.md

File: pkg/controller/podautoscaler/horizontal.go [hunk 1]
```diff
@@ -422,6 +422,15 @@ func (a *HorizontalController) reconcileAutoscaler(hpav1Shared *autoscalingv1.Ho
 		case desiredReplicas > scaleUpLimit:
 			setCondition(hpa, autoscalingv2.ScalingLimited, v1.ConditionTrue, "ScaleUpLimit", "the desired replica count is increasing faster than the maximum scale rate")
 			desiredReplicas = scaleUpLimit
+
+			// Ensure that even if the scaleUpLimit is greater
+			// than the maximum number of replicas, we only
+			// set the max number of replicas as desired.
+			if scaleUpLimit > hpa.Spec.MaxReplicas {
```
Comment (MaciekPytel) [inline pkg/controller/podautoscaler/horizontal.go]: This is basically an exact copy-paste of one of the cases below. Adding ifs checking whether we would trigger condition of a different case if we haven't already triggered the one we're in makes me think switch-case is not the right solution here and we should move to a sequence of ifs instead (perhaps contained in a separate function that can be unittested in isolation).

Especially since we already had a very similar bug caused by interaction of conditions in this switch-case: https://github.com/kubernetes/kubernetes/pull/48997.

I'm ok with keeping this bugfix as is, but we should revisit this part of hpa, clean it up and make sure it's reasonably unittested to avoid another such issue in future. @mwielgus @DirectXMan12

Comment (MaciekPytel) [reply pkg/controller/podautoscaler/horizontal.go]: I've created an issue #53728 to do this.

**Comment by MaciekPytel** [comment]
@mattjmcnaughton can you create cherry-pick PRs for this into 1.7 and 1.8 branches? This is done by just running hack/cherry_pick_pull.sh script. Alternatively I can create them for you.

**Comment by mattjmcnaughton** [comment]
Yup, I can create the cherry-pick PRs - I'll do it rn :)
