### PR TITLE
Ignore transient errors when gathering stats for Windows Containers in Dockershim

### LINKED ISSUE #98509: Windows Kubelet stats/summary endpoint returns "Internal Error: failed to list pod stats: failed to list all container stats on Windows"
**What happened**:

When reviewing Windows kubelet logs noticed errors like:

```
E0930 20:21:31.218007 5020 handler.go:321] HTTP InternalServerError serving /stats/summary: Internal Error: failed to list pod stats: failed to list all container
stats: rpc error: code = Unknown desc = container 46527a779618ed4197babc79889886b540f352d72503656eda3c37c2f247c4a0 encountered an error during Properties: failure in a
Windows system call: The requested virtual machine or container operation is not valid in the current state. (0xc0370105) 
```

```
E0930 20:21:34.026254 5020 handler.go:321] HTTP InternalServerError serving /stats/summary: Internal Error: failed to list pod stats: failed to list all container
stats: rpc error: code = Unknown desc = container d8a566cef3d9ed97442c37ee5f26fb4ff51aac19ad9c1b4bb6caf84acaf0afa5 encountered an error during Properties: failure in a
Windows system call: Access is denied. (0x5)
```

**What you expected to happen**:
The stats should be returned

**How to reproduce it (as minimally and precisely as possible)**:
This occurs when the pods has just started or during termination. To simulate the issue:

```
k proxy
for (( ; ; ))
do
   curl http://localhost:8001/api/v1/nodes/1241k8s00000000/proxy/stats/summary
done
```

Then deploy pod:

```
k apply -f https://gist.githubusercontent.com/jsturtevant/5f49c3bd9218666af877927a674b7645/raw/fb042ff14b689c308c9404422e08cf85c56b6ff1/deployment.yaml
```

**Anything else we need to know?**:

The container is in a `Created` state but is has not started running so the call to get the stats fails:

https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/dockershim/docker_stats_windows.go#L53-L56

This is handled in other places like moby: 

https://github.com/moby/moby/blob/46cdcd206c56172b95ba5c77b827a722dab426c5/daemon/stats.go#L38-L39

and 

https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/stats/cri_stats_provider_windows.go#L44-L48

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18+
- Cloud provider or hardware configuration: aks-engine
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): 2019
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others: Dockershim

/sig windows 
/priority critical-urgent
/assign

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When a Windows container is started by docker there is a case when stats may be accessed before the container is started causing errors.

**Which issue(s) this PR fixes**: 

Fixes #98509

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix errors when accessing Windows container stats for Dockershim 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig windows

### CODE REVIEW

File: pkg/kubelet/dockershim/docker_stats_windows.go [hunk 1]
```diff
@@ -52,6 +52,14 @@ func (ds *dockerService) getContainerStats(containerID string) (*runtimeapi.Cont
 
 	stats, err := hcsshimContainer.Statistics()
 	if err != nil {
+		if strings.Contains(err.Error(), "0x5") || strings.Contains(err.Error(), "0xc0370105") {
+			// When the container is just started quering for stats causes access errors
+			// This is transient; skip container for now
+			// These hcs errors do not have helpers exposed in public package so need to query for the known codes:
+			// https://github.com/microsoft/hcsshim/blob/master/internal/hcs/errors.go
```
Comment (ehashman) [inline pkg/kubelet/dockershim/docker_stats_windows.go:59]: Can we file a bug asking them to make these public?

**Review by ehashman — COMMENTED** [review]
/triage accepted
LGTM but I'm not a windows person :)

File: pkg/kubelet/dockershim/docker_stats_windows.go [hunk 2]
```diff
@@ -52,6 +52,14 @@ func (ds *dockerService) getContainerStats(containerID string) (*runtimeapi.Cont
 
 	stats, err := hcsshimContainer.Statistics()
 	if err != nil {
+		if strings.Contains(err.Error(), "0x5") || strings.Contains(err.Error(), "0xc0370105") {
```
Comment (ehashman) [inline pkg/kubelet/dockershim/docker_stats_windows.go:55]: Don't forget to import "strings"

File: pkg/kubelet/dockershim/docker_stats_windows.go (hunk 1 above)
Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_stats_windows.go:59]: https://github.com/microsoft/hcsshim/pull/933

File: pkg/kubelet/dockershim/docker_stats_windows.go (hunk 2 above)
Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_stats_windows.go:56]: Had it staged but not committed. guess I missed it when I committed the patch :smile:

**Comment by jsturtevant** [comment]
looks like `pull-kubernetes-bazel-build ` failed with 

```
2021/01/28 21:58:14 Image pull was unsuccessful: unable to save remote image k8s.gcr.io/build-image/debian-base@sha256:afff10fcd513483e492807f8d934bdf0be4a237997f55e0f1f8e34c04a6cb213: unable to write image layers: unable to write image layer: unable to write the contents of layer 0 to /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/external/debian-base-amd64/image/000.tar.gz: read tcp 10.32.255.3:46322->142.250.128.128:443: read: connection reset by peer
```

/retest

**Comment by jsturtevant** [comment]
looks like the azure disk is known issue: https://github.com/kubernetes/kubernetes/issues/98492

File: pkg/kubelet/dockershim/docker_stats_windows.go [hunk 3]
```diff
@@ -52,6 +53,14 @@ func (ds *dockerService) getContainerStats(containerID string) (*runtimeapi.Cont
...
+			// When the container is just started quering for stats causes access errors
```
Comment (marosset) [inline pkg/kubelet/dockershim/docker_stats_windows.go:57]:
```suggestion
			// When the container is just started, querying for stats causes access errors
```

File: pkg/kubelet/dockershim/docker_stats_windows.go [hunk 4]
```diff
@@ -52,6 +53,14 @@ func (ds *dockerService) getContainerStats(containerID string) (*runtimeapi.Cont
...
+			// This is transient; skip container for now
+			// These hcs errors do not have helpers exposed in public package so need to query for the known codes:
+			// https://github.com/microsoft/hcsshim/blob/master/internal/hcs/errors.go
+			klog.Errorf("Container is not in a state that stats can be accessed '%s': %v. This occurs when the container is created but not started.", containerID, err)
```
Comment (marosset) [inline pkg/kubelet/dockershim/docker_stats_windows.go:61]: Should we make this an info message since nothing is actually wrong and there is nothing actionable?

Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_stats_windows.go:61]: I was following the same pattern as above https://github.com/kubernetes/kubernetes/blob/4a8b2d377ba51124c0277ed4e25afe2eeefda085/pkg/kubelet/dockershim/docker_stats_windows.go#L41-L43

If we do that here I think we should do it there too?

Comment (marosset) [reply pkg/kubelet/dockershim/docker_stats_windows.go:61]: Let's update both messages to log as Info at V(4).
That matches some similar logs messages i'm seeing in dockershim
https://github.com/kubernetes/kubernetes/blob/64a6ee4321d37740b84a5c5c7aaa67e0bf6b6508/pkg/kubelet/dockershim/docker_container.go#L76

@ehashman any concerns or comments with this?

Comment (ehashman) [reply pkg/kubelet/dockershim/docker_stats_windows.go:61]: I know we're not yet on structured logging in this file yet but I don't think there's any issue with changing this to an Info, the current guidance is that expected errors are fine to log at the info level: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#using-errors

Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_stats_windows.go]: I've updated to log using info

**Comment by jsturtevant** [comment]
@ehashman this is ready for final approval

**Comment by jsturtevant** [comment]
@ehashman  I see you are not the approver for this sorry!

/assign @dchen1107 @derekwaynecarr

**Comment by AbelHu** [comment]
@jsturtevant Thanks for fixing this issue. Do you have a plan to backport this fix to earlier versions since lots of users are hitting this issue?
