### PR TITLE
kube-proxy: only set route_localnet if required

### LINKED ISSUE #106976: Iptable:  missing IsLoopBack() check for nodeAddress
### What happened?

Just similar to [#96879](https://github.com/kubernetes/kubernetes/issues/96879) , for service with type nodeport , iptable proxy should add IsLoopback check for nodeAddress. 
https://github.com/kubernetes/kubernetes/blob/159fcbb01e2017f1f3351cbb1ed987db6895b0a6/pkg/proxy/ipvs/proxier.go#L1096-L1116
 Line 1104-1106 check nodeAddress is localhost address or not for ipvs mode proxy 
but for iptable mode proxy , when deal with nodePort type service,  there is no similar check for nodeAddress
https://github.com/kubernetes/kubernetes/blob/159fcbb01e2017f1f3351cbb1ed987db6895b0a6/pkg/proxy/iptables/proxier.go#L1293-L1305

### What did you expect to happen?

since the use of localhost addresses for nodeports is the only know reason to require net.ipv4.conf.all.route_localnet=1 (#90259),  Just for the purpose of security ,this requirement shall be removed for proxy-mode=itable.

### How can we reproduce it (as minimally and precisely as possible)?

Start a cluster with proxy-mode=iptable and some services
Do; iptable  -Ln | grep 127.0.0.1

### Anything else we need to know?

just as https://github.com/kubernetes/kubernetes/issues/96879#issuecomment-736291567
says : ipv6+iptables , ::1 is not work for Nodeport

### Kubernetes version

all supporting proxy-mode=iptable

### Cloud provider

any

### OS version

any

### Related plugins (CNI, CSI, ...) and versions (if applicable)

/sig network
/kind cleanup
/area iptable

### PR DESCRIPTION
**Pull request by aojea**
kube-proxy sets the sysctl net.ipv4.conf.all.route_localnet=1
so NodePort services can be accessed on the loopback addresses in
IPv4, but this may present security issues.

Leverage the --nodeport-addresses flag to opt-out of this feature,
if the list is not empty and none of the IP ranges contains a
loopback address this sysctl is not set.

In addition, add a warning to inform users about this behavior.

/kind cleanup

```release-note
kube-proxy doesn't set the sysctl net.ipv4.conf.all.route_localnet=1 if no IPv4 loopback address is selected by the nodePortAddresses configuration parameter.
```

Fixes: #106976

### CODE REVIEW

**Comment by dcbw** [comment]
This LGTM but I'd like a second opinion.

**Comment by dims** [comment]
cc @jayunit100

File: pkg/proxy/util/utils.go [hunk 1]
```diff
@@ -78,6 +78,25 @@ func BuildPortsToEndpointsMap(endpoints *v1.Endpoints) map[string][]string {
...
+		return true
+	}
+	for _, cidr := range cidrStrings {
+		if IsZeroCIDR(cidr) {
+			return true
+		}
+		// swallow the error, we are only interested in finding cidrs containing loopbacks
+		// The cidrs should have been validated before.
+		ip, _, _ := netutils.ParseCIDRSloppy(cidr)
+		if ip.IsLoopback() {
```
Comment (thockin) [inline pkg/proxy/util/utils.go:93]: if I pass 0.0.0.0/1 or 64.0.0.0/2 or 96.0.0.0/3 (etc), that won't trigger this.  Should it?

**Review by thockin — COMMENTED** [review]
I like the idea.

Should we also add a flag to disable localhost node-ports?

**Comment by cyclinder** [comment]
/lgtm
I think we should also add a flag for it(default true). When set it to false, we don't need set `sysctl net.ipv4.conf.all.route_localnet=1`.
 When this pr merged, I can take this one.

File: pkg/proxy/util/utils.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/util/utils.go:93]: actually this is IPv4 only, it should not check IPv6

Comment (aojea) [reply pkg/proxy/util/utils.go:102]: fixes, great catch

File: pkg/proxy/util/utils.go [hunk 2]
```diff
@@ -78,6 +78,38 @@ func BuildPortsToEndpointsMap(endpoints *v1.Endpoints) map[string][]string {
...
+		}
+
+		if netutils.IsIPv6CIDR(ipnet) {
+			continue
+		}
+
+		if ip.IsLoopback() {
+			return true
+		}
+		if ipnet.Contains(ipv4LoopbackStart) || ipnet.Contains(ipv4LoopbackEnd) {
```
Comment (thockin) [inline pkg/proxy/util/utils.go:106]: Do you need both?  How could it contain ipv4LoopbackEnd but not ipv4LoopbackStart and not be `IsLoopback()` ?

**Review by thockin — COMMENTED** [review]
Minor thing :)

/lgtm
/approve

File: pkg/proxy/util/utils.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/util/utils.go:106]: honestly, I wasn't doing the bit operations but it can't, right?
to "contain" the other subnet, the mask has to be always greater and will completely contain the network ... I don't know why I had a memory flash that this can happen ... let me fix it

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
