### PR TITLE
use the cgroup aware OOM killer if available

### LINKED ISSUE #117070: [SIG-Node]  Cgroups v2 memory.oom.group support (kill all pids in a pod on oom)
### What would you like to be added?

Follow up on meeting of 28-03-2022 [Meeting notes](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.2cz4ars29skh) - [Slack thread](https://kubernetes.slack.com/archives/C0BP8PW9G/p1679649131585659)

In the meeting was specified that this most likely won't need a KEP and should be started with a Issue

I see that the kernel in cgroups v2 has an option memory.oom.group which would make all the pids of a given container to get killed on OOM:
```
+  memory.oom.group
+	A read-write single value file which exists on non-root
+	cgroups.  The default value is "0".
+
+	Determines whether the cgroup should be treated as a single
+	unit by the OOM killer. If set, the cgroup and its descendants
+	are killed together or not at all. This can be used to avoid
+	partial kills to guarantee workload integrity.
+
+	Tasks with the OOM protection (oom_score_adj set to -1000)
+	are treated as an exception and are never killed.
+
+	If the OOM killer is invoked in a cgroup, it's not going
+	to kill any tasks outside of this cgroup, regardless
+	memory.oom.group values of ancestor cgroups.
```
@mrunalp  @SergeyKanzhelev 

### Why is this needed?

Some workloads that fork the process in the container, when the OOM kicks in, it kills only one process of the cgroup, causing a lot of noise due to process failures but health checks being successfull. We think that for our scenarios, killing all the pids in the containter would be better.

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Sets the oom.memory.group bit for container cgroups on kernels with cgroups v2.

#### Which issue(s) this PR fixes:
Fixes #117070

#### Does this PR introduce a user-facing change?

```release-note
If using cgroups v2, then the cgroup aware OOM killer will be enabled for container cgroups via  `memory.oom.group` .  This causes processes within the cgroup to be treated as a unit and killed simultaneously in the event of an OOM kill on any process in the cgroup.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

https://github.com/torvalds/linux/blob/3c4aa44343777844e425c28f1427127f3e55826f/Documentation/admin-guide/cgroup-v2.rst?plain=1#L1280

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 1]
```diff
@@ -215,9 +222,39 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
 		resources.CpuPeriod = cpuPeriod
 	}
 
+	if supportsMemoryOOMGroup() {
+		// Turn on memory.oom.group which tells the kernel to treat the entire container cgroup as
+		// a single unit for OOM kill purposes.  This will cause all processes in the container to be
+		// OOM killed together if any are OOM killed.
+		resources.Unified = map[string]string{
+			"memory.oom.group": "1",
```
Comment (tzneal) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:230]: There should probably be some setting on the container to let users opt out of this behavior, but I didn't see any good place to hang it.  Suggestions?

**Comment by bobbypage** [comment]
Thanks for making the change. I agree this would be nice to have, my only concern is if there are some workloads that want to maintain the current behavior and _avoid_ having a cgroup OOM. I agree this this a better default for the majority of workloads, but does it make sense to have some way for a workload to opt out of this behavior? Some folks mention that some workloads (e.g. postgressql, ngnix) do handle this case correctly, xref: https://github.com/kubernetes/kubernetes/issues/50632#issuecomment-1151776249

/cc @mrunalp @haircommander @guineveresaenger for thoughts

**Comment by haircommander** [comment]
Yeah at this point, we have an established behavior of not doing this (even if it's the right thing). Unfortunately, if we want it tunable, we may need to introduce a knob to the pod api

**Comment by haircommander** [comment]
I am happy to put it on by default. As another thought (which I worry will unnecessarily increase complexity): are there other cgroup fields we want to optionally enable? Would an opaque key value field for memoryCgroupOptions be useful? I am not immediately seeing other options that the kubelet wouldn't make opinionated decisions about already (like memory.high), so maybe we don't need the complexity. I just am wary of adding too many fields to the pod api so I want to consider before adding one for just this field

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 2]
```diff
@@ -215,9 +222,39 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
...
+		}
+	}
 	return &resources
 }
 
+// supportsMemoryOOMGroup returns true if
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:236]: please complete the sentence

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:230]: I think making it default is fine and non-controversial

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 3]
```diff
@@ -215,9 +222,39 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
...
+func supportsMemoryOOMGroup() bool {
+	supportsMemoryOOMGroupOnce.Do(func() {
+		kernelVersionStr, err := ipvs.NewLinuxKernelHandler().GetKernelVersion()
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:239]: is there a good place to reuse similar from sysctl (pkg/kubelet/sysctl/safe_sysctls.go)? Have you copied from there?

Also interesting that the `NewLinuxKernelHandler` in pkg/proxy/ipvs/proxier.go is not compiling only for linux like this file. I remember in sysctl we had problems trying to call it from Windows

File: test/e2e_node/oomkiller_test.go [hunk 4]
```diff
@@ -32,32 +32,62 @@ import (
...
+				getOOMTargetContainerMultiProcess),
+		})
+	}
+	for _, tc := range testCases {
+		runOomKillerTest(f, tc)
+	}
 })
 
+// isCgroupV2 is a hack to check for cgroup v2 without importing a platform specific library
+func isCgroupV2() bool {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/oomkiller_test.go:67]: there is `isHostRunningCgroupV2` in framework. You may reuse the logic

File: test/e2e_node/oomkiller_test.go [hunk 5]
```diff
@@ -32,32 +32,62 @@ import (
...
+		name:                   "single process container",
+		oomTargetContainerName: "oomkill-single-target-container",
+		podSpec: getOOMTargetPod("oomkill-target-pod", "oomkill-single-target-container",
+			getOOMTargetContainer),
+	}}
+
+	// If using cgroup v2, we set memory.oom.group=1 for the container cgroup so that any process which gets OOM killed
+	// in the process, causes all processes in the container to get OOM killed
+	if isCgroupV2() {
+		testCases = append(testCases, testCase{
```
Comment (SergeyKanzhelev) [inline test/e2e_node/oomkiller_test.go:54]: can you add an opposite case for completeness?

File: test/e2e_node/oomkiller_test.go [hunk 6]
```diff
@@ -32,32 +32,62 @@ import (
...
 			ginkgo.By("setting up the pod to be used in the test")
 			e2epod.NewPodClient(f).Create(context.TODO(), testCase.podSpec)
 		})
 
 		ginkgo.It("The containers terminated by OOM killer should have the reason set to OOMKilled", func() {
-
 			ginkgo.By("Waiting for the pod to be failed")
-			e2epod.WaitForPodTerminatedInNamespace(context.TODO(), f.ClientSet, testCase.podSpec.Name, "", f.Namespace.Name)
+			err := e2epod.WaitForPodTerminatedInNamespace(context.TODO(), f.ClientSet, testCase.podSpec.Name, "", f.Namespace.Name)
+			framework.ExpectNoError(err, "Failed waiting for pod to terminate, %s/%s", f.Namespace.Name, testCase.podSpec.Name)
```
Comment (SergeyKanzhelev) [inline test/e2e_node/oomkiller_test.go:90]: Do we validate that the second process was terminated? Or the container will show as running if there is still a process running?

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 3 above)
Comment (giuseppe) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:239]: I think you could just assume the functionality is present if it is running on cgroup v2, since we are already using features (like the hugetlb controller) that were added much later

Comment (tzneal) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:239]: It's a cgroup file, not a sysctl value.  But assuming it works if cgroupsv2 is in used SGTM, the docs say that requires kernel 5.8 or later.

File: test/e2e_node/oomkiller_test.go (hunk 4 above)
Comment (tzneal) [reply test/e2e_node/oomkiller_test.go:67]: That one SSH's into the host, I don't think it will work here.

File: test/e2e_node/oomkiller_test.go (hunk 5 above)
Comment (tzneal) [reply test/e2e_node/oomkiller_test.go:54]: Added an API to allow disabling the new default and added a test case.

**Comment by tzneal** [comment]
> I am happy to put it on by default. As another thought (which I worry will unnecessarily increase complexity): are there other cgroup fields we want to optionally enable? Would an opaque key value field for memoryCgroupOptions be useful? I am not immediately seeing other options that the kubelet wouldn't make opinionated decisions about already (like memory.high), so maybe we don't need the complexity. I just am wary of adding too many fields to the pod api so I want to consider before adding one for just this field

I looked as well and didn't see any other fields that looked relevant, hard to know what might appear in the future.  It might be worth considering putting this in platform specific struct (e.g. `Containers[*].LinuxOptions`).  I'll drop a link #api-reviews and see if someone wants to provide some input from there.

**Comment by tzneal** [comment]
> This looks awesome.
> Do we need another KEP for this?

That was my thought originally, but when it was discussed in a SIG-Node meeting the consensus there was that we didn't need one. I'm not sure if that was fully considering the API change.  I'll put this on the agenda for this week's meeting.

**Comment by smarterclayton** [comment]
If we're GA and proposing a behavior change and/or an API for workloads, then it's a KEP.

File: test/e2e_node/oomkiller_test.go [hunk 7]
```diff
@@ -122,3 +154,26 @@ func getOOMTargetContainer(name string) v1.Container {
 		},
 	}
 }
+
+// getOOMTargetContainerMultiProcess returns a container with two processes, one of which attempts to allocate more
+// memory than is allowed by the container memory limit, and a second process which just sleeps
+func getOOMTargetContainerMultiProcess(name string) v1.Container {
```
Comment (CoderSherlock) [inline test/e2e_node/oomkiller_test.go:160]: qq: Looks to me that without setting memory.oom.group, multi process container still has failed and 137 as exit code. I'm wondering will the new added test cover new added oom.group feature?

Comment (tzneal) [reply test/e2e_node/oomkiller_test.go:160]: Sorry, I don't understand this comment.  Without setting the new cgroup flag, individual processes are killed in the container, but the container is still running.  You can verify this by running this pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: bash
    resources:
      limits:
        memory: 10M
    image: busybox:latest
    command: ["sh","-c", "dd if=/dev/zero of=/dev/null bs=20M & sleep 86400"]
```

On my cluster, the pod and container still look ok:

```bash
$ k get pod test-pod -o yaml | yq '.status'
conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T18:07:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T18:07:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T18:07:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-09T18:07:07Z"
    status: "True"
    type: PodScheduled
containerStatuses:
  - containerID: containerd://7fd5eda37230c4a532632ca19da29e8a72c0f1d2d05e7f3059e783dac4c656f0
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:b5d6fe0712636ceb7430189de28819e195e8966372edfc2d9409d79402a0dc16
    lastState: {}
    name: bash
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-09T18:07:09Z"
hostIP: 192.168.67.135
phase: Running
podIP: 192.168.93.235
podIPs:
  - ip: 192.168.93.235
qosClass: Burstable
startTime: "2023-05-09T18:07:07Z"
```

But on my node, I can see that dd was killed:
```
May  9 18:07:09 i-00706ac6ebbe246c9 kernel: dd invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=999
```
```
10187 ?        Sl     0:00 /usr/bin/containerd-shim-runc-v2 -namespace k8s.io -id d7e43a3f4dac52075c3ebcdb88f375ad134a2dfca49f45bab65d7a9cb7b5357e -address /run/containerd/containerd.sock
10210 ?        Ss     0:00  \_ /pause
10244 ?        Ss     0:00  \_ sh -c dd if=/dev/zero of=/dev/null bs=20M & sleep 86400
10257 ?        Z      0:00      \_ [dd] <defunct>
```

Comment (CoderSherlock) [reply test/e2e_node/oomkiller_test.go:160]: Thanks for sharing the info. I just reproduced the same result. Correct me if I'm wrong, in this test, without kill other processes(sleep) in the same cgroup, test supposed to failed because the timeout.

My apology made confusion in previous comments, because I tried similar test case last week(`["sh","-c", "dd if=/dev/zero of=/dev/null bs=20M & (sleep 100; exit 0)"]`) and I misunderstand the test.

**Comment by tzneal** [comment]
> EDIT: If we can make the argument that the existing behavior isn't guaranteed to only kill the offending process (i.e. if the OOM killer could kill a bunch of processes in the pod anyway, even with the value we set now) there's more of an argument to changing the default behavior. If we can't make that argument, we'd probably have to preserve the already GA'd behavior or make the argument that the cluster / node admin is the best user to make the decision about the flag value (justifying it being a kubelet option) vs the workload author, which is a hard argument to make.


This was the consensus yesterday in SIG-Node. The desired behavior was for containers to be killed and it wasn't feasible before. From what I understand, the OOM killer may kill multiple processes within the same container if there is still memory pressure.  I've verified that the docs consistently mention containers being killed as opposed to individual processes within the container being killed.

CC @dchen1107

File: test/e2e_node/oomkiller_test.go (hunk 4 above)
Comment (haircommander) [reply test/e2e_node/oomkiller_test.go:67]: don't we need to ssh into the host the test is running on? I'm not sure using local cgroup2 context will give us the correct state

Comment (haircommander) [reply test/e2e_node/oomkiller_test.go:67]: ah totally I believe you're right my mistake

Comment (haircommander) [inline test/e2e_node/oomkiller_test.go:67]: a separate nit here is there's https://github.com/opencontainers/runc/blob/v1.1.7/libcontainer/cgroups/utils.go#L34 which achieves this more precisely. Why not use that?

Comment (tzneal) [reply test/e2e_node/oomkiller_test.go:67]: IIRC, I tried that first but the test fails to build on Windows.  I checked and all usage of libcontainercgroups are in `*_linux.go`

Comment (tzneal) [reply test/e2e_node/oomkiller_test.go:67]: Yeah, I confirmed it fails that way:

```
$ GOOS=windows go test -v
# github.com/opencontainers/runc/libcontainer/devices
../../vendor/github.com/opencontainers/runc/libcontainer/devices/device.go:173:9: undefined: mkDev
```

Comment (haircommander) [reply test/e2e_node/oomkiller_test.go:67]: I feel like this file should be linux only.. the test says [LinuxOnly]...

Comment (haircommander) [reply test/e2e_node/oomkiller_test.go:67]: doesn't have to be addressed here but could be if you felt so inclined :)

Comment (tzneal) [reply test/e2e_node/oomkiller_test.go]: Easy enough and lets me remove some code.

**Comment by haircommander** [comment]
/lgtm

thanks @tzneal !

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
/assign @dchen1107 

(as discussed yesterday at SIG Node meeting, let's go with the unconditional change of a default for cgroupv2 for better experience)

File: test/e2e_node/oomkiller_linux_test.go [hunk 8]
```diff
@@ -122,3 +143,26 @@ func getOOMTargetContainer(name string) v1.Container {
...
+// memory than is allowed by the container memory limit, and a second process which just sleeps
+func getOOMTargetContainerMultiProcess(name string) v1.Container {
+	return v1.Container{
+		Name:  name,
+		Image: busyboxImage,
+		Command: []string{
+			"sh",
+			"-c",
+			// use the dd tool to attempt to allocate 20M in a block which exceeds the limit
+			"dd if=/dev/zero of=/dev/null bs=20M & sleep 86400",
```
[the remark this answers is not in the document]
Comment (mrunalp) [reply test/e2e_node/oomkiller_linux_test.go:157]: cc: @kolyshkin

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 9]
```diff
@@ -215,6 +215,16 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
 		resources.CpuPeriod = cpuPeriod
 	}
 
+	// the "memory.oom.group" flag appeared in kernel 4.19 and the docs indicate that 5.8 is the minimum kernel version
+	// if using cgroups v2, so we just need to check for that
```
Comment (kolyshkin) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:219]: In addition, `runc` does not allow resources.Unified for cgroup v1, so cgroup v2 is a hard requirement here.

Maybe you can rephrase your comment based on that fact.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 10]
```diff
@@ -215,6 +215,16 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
...
+	if libcontainercgroups.IsCgroup2UnifiedMode() {
+		// Turn on memory.oom.group which tells the kernel to treat the entire container cgroup as
+		// a single unit for OOM kill purposes.  This will cause all processes in the container to be
+		// OOM killed together if any are OOM killed.
```
Comment (kolyshkin) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:223]: nit: this comment belongs to `"memory.oom.group": "1"` not to the `resources.Unified =` line.

You can also make the comment more concise; something like

```
// Ask the kernel to kill all processes in the container cgroup in case of OOM.
```

File: test/e2e_node/oomkiller_linux_test.go [hunk 11]
```diff
@@ -1,3 +1,6 @@
+//go:build linux
+// +build linux
```
Comment (kolyshkin) [inline test/e2e_node/oomkiller_linux_test.go:2]: nit: no need to have that, since the file name has `_linux` in it.

File: test/e2e_node/oomkiller_linux_test.go [hunk 12]
```diff
@@ -88,20 +107,22 @@ func verifyReasonForOOMKilledContainer(pod *v1.Pod, oomTargetContainerName strin
...
 			Containers: []v1.Container{
-				getOOMTargetContainer(ctnName),
+				createContainer(ctnName),
 			},
 		},
 	}
 }
 
+// getOOMTargetContainer returns a container with a single process, which attempts to allocate more memory than is
+// allowed by the container memory limit
```
Comment (kolyshkin) [inline test/e2e_node/oomkiller_linux_test.go:125]: nit: missing `.` at the end of the sentence.

File: test/e2e_node/oomkiller_linux_test.go [hunk 13]
```diff
@@ -122,3 +143,26 @@ func getOOMTargetContainer(name string) v1.Container {
 		},
 	}
 }
+
+// getOOMTargetContainerMultiProcess returns a container with two processes, one of which attempts to allocate more
+// memory than is allowed by the container memory limit, and a second process which just sleeps
```
Comment (kolyshkin) [inline test/e2e_node/oomkiller_linux_test.go:148]: nit: missing `.` at the end of the sentence.

File: test/e2e_node/oomkiller_linux_test.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (kolyshkin) [reply test/e2e_node/oomkiller_linux_test.go:157]: The problem with the `dd` memory eater is it eats 20+M real fast and then it just stays that way. This "stalling" may make it less attractive for the OOM killer, so I ended up changing it to 

```shell
for ((i=0; i<1000; i++)); do val=$(seq -w -s - $i $((i + 100000))); eval var$i=$val_$val_$val; done
```

(also run via 'sh -c'), which is not that fast but it keeps eating more and more memory until being killed.

**Comment by kolyshkin** [comment]
Also, the subject:

> use the cgroup aware OOM killer if available

is misleading. The OOM killed is already cgroup aware, it just kills individual processes by default.

A more proper title would be something like "kill the whole container in case of OOM".

**Comment by kolyshkin** [comment]
> Also, the subject:
> 
> > use the cgroup aware OOM killer if available
> 
> is misleading. The OOM killed is already cgroup aware, it just kills individual processes by default.
> 
> A more proper title would be something like "kill the whole container in case of OOM", or "kill all processes in the container cgroup in case of OOM".

Ditto for the release note in this PR description.

**Comment by kolyshkin** [comment]
Finally, it would be nice to have some description of the commit in the git commit message (which is currently just the subject and the signed-off-by), for the sake of anyone using `git log`, `git bisect` etc.

File: test/e2e_node/oomkiller_linux_test.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (tzneal) [reply test/e2e_node/oomkiller_linux_test.go:157]: I haven't seen any flakes in my testing and this method is used in the current OOM test here: https://github.com/kubernetes/kubernetes/blob/9d231f8ce77b4a8413b41130ea130d392ca860c7/test/e2e_node/oomkiller_test.go#L113


I need the memory to be exhausted by some process other than the one keeping the container alive.  It's probably possible to adapt the code and run it in a separate bash, but it doesn't seem straight forward.

**Comment by tzneal** [comment]
> Also, the subject:
> 
> > use the cgroup aware OOM killer if available
> 
> is misleading. The OOM killed is already cgroup aware, it just kills individual processes by default.
> 

It depends on your kernel version if it's aware or not, but it has been since 4.19. I'll change the subject if it helps clarify.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 14]
```diff
@@ -215,6 +215,13 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
 		resources.CpuPeriod = cpuPeriod
 	}
 
+	// runc requires cgroupv2 for unified mode
+	if libcontainercgroups.IsCgroup2UnifiedMode() {
+		resources.Unified = map[string]string{
+			// Ask the kernel to kill all processes in the container cgroup in case of OOM.
+			"memory.oom.group": "1",
```
Comment (dims) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:222]: Let's add a link to the documentation please. LGTM after that:
https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

**Comment by dims** [comment]
/approve
/lgtm

Merging this to get more soaktime in the CI.

**Comment by superbrothers** [comment]
This feature affected several of our workloads and caused a lot of OOM Killing in the cluster. One was an ML workload where the main process was not killed when a child process was killed, so another computation could continue. The second was for interactive workloads. For example, what used to work well with `make -j20 -k || make -j10` is now OOMKilled.

We wanted to disable this feature because it was difficult to fix those workloads immediately, but we could not because it was not an option. We patched kubelet to disable this feature.

I understand that this feature works better with many workloads. (It would be better if it could be controlled on a per pod basis, but from the discussion so far it appears that this is not going to be provided.) Many clusters are currently running on cgroup v1. The problem will become more apparent when they switch to cgroup v2.

**Comment by poolnitsol** [comment]
We would like an option to disable this feature as well. We saw several containers restarting if one of the process gets OOMKilled. It impacted us on a mass level and we had to revert to cgroup v1 in middle of k8s upgrades. We are trying to figure out what would it take for us to come up with a workaround if goes live without an option to disable

**Comment by gdhagger** [comment]
@haircommander what's the best place to keep informed on progress on that feature? - I don't see anything in the sig-node google group or slack channel that seems directly related

**Comment by haircommander** [comment]
it was mostly discussed in the meeting (of which the notes can be found [here](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit)). as we enter 1.30 cycle there will be additional documentation

**Comment by tzneal** [comment]
PR to add a flag to enable the old behavior: https://github.com/kubernetes/kubernetes/pull/122813

**Comment by mbrt** [comment]
Hey folks!

A bit late to the party, but we upgraded to Kubernetes 1.28 last week and, like others [[1](https://github.com/kubernetes/kubernetes/pull/117793#issuecomment-1837400726), [2](https://github.com/kubernetes/kubernetes/pull/122813#issuecomment-2004527657), [3](https://github.com/kubernetes/kubernetes/pull/117793#issuecomment-1843606901)], had to face outages due to increased OOMs. At Celonis, among other things, we run a compute and memory intensive workload (10k cores, 80TiB memory), which loads data models (>100k) into memory to serve queries. Each data model is handled by a separate process, managed within a Pod by a coordinator process. Multiple Pods are managed by an orchestrator. The old behavior allowed serving tens of thousands of models with just a few nodes in a fairly dynamic way. If one process died because of OOM, the orchestrator would reschedule it. This had no repercussions on other models served in the same Pod, it’s simple, and memory utilization is very good.

I’m sharing these details because I think this is a valid use case. Splitting each process in its own Pod is infeasible, given the sheer amount of processes (up to 100k) and also the variability in memory usage of a single process. Splitting them into coarser grained Pods is also not a solution long term, as it would only reduce the blast radius, but not eliminate the problem of a single model taking down hundreds more. Resource utilization would also be lower and result in a rather expensive bill. Keeping ourselves with cgroups v1 seems also not feasible long term, as I’m seeing discussions to drop support, both [in Kubernetes](https://github.com/kubernetes/enhancements/pull/4572), [in systemd](https://github.com/systemd/systemd/pull/24086) and in [AWS Bottlerocket](https://github.com/bottlerocket-os/bottlerocket/issues/3018) (which we’re using). We were also already using cgroups v2 and downgrading to v1 seems to fix the problem in the wrong way.

I agree that the new behavior seems like a saner default. I’m however afraid that we’re thinking that the previous use case is no longer valid, so this is the deeper question we would like to address.

In summary, I have the following concerns:

1. The proposed mitigations seem to go along the lines of “[adding a flag](https://github.com/kubernetes/kubernetes/pull/122813)” to give people more time to migrate. Those would also be coming 2 releases late (at best), while we’re leaving people reliant on the previous behavior exposed without a real mitigation.
2. There seems to be no way forward for workloads managing their own memory in a granular way through sub-processes.
3. Solutions to the previous point sound all like workarounds and not viable long term (I only see https://github.com/kubernetes/kubernetes/issues/124253#issuecomment-2052238805 being proposed, but it comes as part of a much bigger feature, which makes it hard to know when and if it will land).

Is there anything we could be doing to mitigate the impact of this change? For example, short term backporting the new kubelet flag to 1.28 or 1.29, and longer term expedite a subset of solution 3 targeted to OOMs only?

These are just ideas, and I’m happy to take other suggestions back to our teams as well. I hope SIG-Node can take this into consideration (cc @haircommander, @tzneal).

Thanks!

**Comment by xhejtman** [comment]
Hello,

would it be possible to mark pod status as OOMKilled when any oom kill occurs in the pod. It seems, that oomkilled status is set only iff oomkill is received by PID 1 in the container.

**Comment by zaheerabbas-prodigal** [comment]
Hello,

We migrated to k8s 1.28 this week on AWS EKS. I reached this issue after debugging for over a day. This is an issue that is affecting us in Prod. Do you have any update on when it will be backported to support the option to opt out of this default setting?

Would appreciate any solutions others have implemented as a temp fix for this.

Thanks

**Comment by dims** [comment]
> This is an issue that is affecting us in Prod

@zaheerabbas-prodigal please open an issue with AWS/EKS support.

**Comment by zaheerabbas-prodigal** [comment]
@dims - Unfortunately, we do NOT have a support subscription for raising this as a priority issue with AWS/EKS support.

We have mitigated this issue by increasing the memory limits of our service and backporting to cgroup1 using bottle rocket configs. That seemed to be the only solution we could do to mitigate this as a temporary fix. But this is a really bad state to be in. 

I wanted to reach out here and check if the k8s team is looking to prioritize and support this feature on an opt-in basis and NOT make it the default behavior. Or if we could employ other techniques to mitigate this behavior.

**Comment by dims** [comment]
@zaheerabbas-prodigal please see the tail end of the discussion in https://github.com/kubernetes/kubernetes/pull/122813

( someone's gotta step up to do the work ... )

**Comment by mbrt** [comment]
@zaheerabbas-prodigal on our side we have implemented a scrappy workaround (but it works), that just goes through all Pods cgroups and periodically disables the group oom killer. Note that this is done in a loop, not because the kubelet will revert it, but because we need to do it after every container is created:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disable-memory-oom-group
spec:
  selector:
    matchLabels:
      app: disable-memory-oom-group
  template:
    metadata:
      labels:
        app: disable-memory-oom-group
    spec:
      containers:
      - name: disable-memory-oom-group
        image: busybox
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |-
          while true; do
            for f in $(find /sys/fs/cgroup/kubepods.slice/ -name memory.oom.group); do
              echo "0" > "$f"
            done
            sleep 60
          done
```

**Comment by dwyart** [comment]
We have successfully tested the proposed "ugly" workaround, but we chose to convert it to a cronjob running directly on the host and defined in user data:
```
dnf update -y && dnf install -y cronie && systemctl start crond
(echo '* * * * * for f in $(find /sys/fs/cgroup/kubepods.slice/ -name memory.oom.group); do echo "0" > "$f"; done') | crontab
```
we think this makes it less ugly  ;)

**Comment by ryancurrah** [comment]
When a child process is killed instead of PID 1 it doesn't give our parent process the ability to properly shutdown the child process and then the workflow we are running in the pod is left in a dirty state.

**Comment by Sungurik** [comment]
Almost like @mbrt and @dwyart we created a Kyverno policy to workaround the issue more precisely. Add label the pods for which you need to disable group OOM, and Kyverno injects a privileged sidecar. Something like:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disable-group-oom
  annotations:
    policies.kyverno.io/title: Disable group OOM for single pod
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Injects priveleged container into pod
      and set 0 to memory.oom.group on node filesystem
spec:
  rules:
  - name: disable-group-oom
    match:
      any:
        - resources:
            kinds:
              - Pod
            selector:
              matchLabels:
                sexygroup/kyverno-policies: "disable-group-oom"
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - name: disable-group-oom
              image: alpine:3.20.2
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 5m
                  memory: 30Mi
                limits:
                  memory: 30Mi
              command: ["sh", "-c"]
              args:
              - |
                sleep 15
                POD_UID=$(cat /proc/self/mountinfo | grep -m 1 '/pods/' | awk -F '/' '{print $4}' | tr '-' '_')
                while true; do
                  for f in $(find /sys/fs/cgroup/kubepods.slice/ -name memory.oom.group | grep $POD_UID); do
                    echo 0 > $f
                    echo $f
                    cat $f
                  done
                  sleep 300
                done
```
Of course that's still a durty hack, but at least you can control it partly not disabling completely for whole cluster.

**Comment by buckleyGI** [comment]
Seems a toggle is added in V1.32

Added singleProcessOOMKill flag to the kubelet configuration. Setting that to true enable single process OOM killing in cgroups v2. In this mode, if a single process is OOM killed within a container, the remaining processes will not be OOM killed. (#126096, @utam0k) [SIG API Machinery, Node, Testing and Windows]

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.32.md

**Comment by pratikmallya** [comment]
hey folks, I also ran into this issue. One solution to handling this gracefully is to use `setrlimit` syscall (e.g. available via the `ulimit` utility) to set the hard limit for the child process that might be running into OOMKills. This has worked for me (it avoids the OOMKiller altogether), and have written a short blurb describing the approach [here](https://blog.mallya.dev/2025/05/10/oomkill-k8s/).
