### PR TITLE
fix(kube-proxy): fix health check binding failure in case of dual-stack

### LINKED ISSUE #114702: dual-stack local traffic policy service health checks...
If you create a dual-stack service with `externalTrafficPolicy: Local`, kube-proxy will log something like:

```
I1226 19:46:08.852777       1 service_health.go:124] "Opening healthcheck" service="default/fruit-service" port=30122
I1226 19:46:08.929154       1 service_health.go:124] "Opening healthcheck" service="default/fruit-service" port=30122
E1226 19:46:08.929216       1 service_health.go:141] "Failed to start healthcheck" err="listen tcp :30122: bind: address already in use" node="kind-control-plane" service="default/fruit-service" port=30122
```

Despite the error, the service health check _does_ actually work. The problem is that the IPv4 and IPv6 `{iptables,ipvs}.Proxier`s each create their own `ServiceHealthServer` (one which only knows about IPv4 endpoints, and one which only knows about IPv6 endpoints), but the service only has a single `healthCheckNodePort`, and in the dual-stack service case, both health servers will try to bind it. One will succeed and one will fail.

Ways we could fix this:

- Only have a single `ServiceHealthServer` which tracks both IPv4 and IPv6 eTP:Local information. This seems probably right to me, but it would be hard to implement efficiently given the current architecture. (It also implies that the correct rule for declaring an eTP:Local Service to be "healthy" on a node is "the service has at least one endpoint IP on the node _for every IP family the Service supports_", not just "the service has at least one endpoint IP on the node". Yes, _normally_ those rules would give the same answer, but it's _possible_ to have a dual-stack service backed by single-stack pods...)
- Keep two `ServiceHealthServer`s, but have the one for the secondary IP family ignore dual-stack services. This is easier than the above, but is obviously a hack, and it would give wrong answers in the dual-stack-service-backed-by-single-stack-pods case.
- Have each `ServiceHealthServer` only bind on the IP family that it is tracking. This would be easy, but is probably an API break? I don't think we have ever claimed that IPv4 load balancers must connect to the `healthCheckNodePort` on an IPv4 node IP, and IPv6 load balancers must connect on an IPv6 node IP; it is plausible that some LBs always connect on the node's primary IP regardless of the family of the load balancer...

/cc @khenidak

### PR DESCRIPTION
**Pull request by terror96**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

In case of dual-stack service with `externalTrafficPolicy: Local` kube-proxy fails to bind one of the health-check instances to a node address and port and instead outputs the following error:
```
E0303 10:33:40.628701       1 service_health.go:145] "Failed to start healthcheck" err="listen tcp 0.0.0.0:30270: bind: address already in use" node="tero-cilium" service="default/nginx-dual" port=30270
```
This happens because kube-proxy creates two instances that both try to bind to the same address and port.

This PR fixes the issue by binding the IPv4 health-check instance to an IPv4 socket and the IPv6 instance to an IPv6 socket, allowing both instances to bind successfully without producing an error.

#### Which issue(s) this PR is related to:

Fixes #114702

#### Special notes for your reviewer:

This change does not address the scenario of a dual‑stack service with single‑stack endpoints; it's unclear whether that configuration is a valid use case. See #114702 for more information.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by terror96** [comment]
> @danwinship any idea what could cause pull-kubernetes-integration: test/integration/scheduler/filters TestUnschedulablePodBecomesSchedulable to fail?

Seems to locally pass:
✓  test/integration/scheduler/filters (5m38.158s)

**Comment by terror96** [comment]
I run a few tests to see how the implementation behaves when the binding issue is fixed and when the IPv6 support detection is fixed (see #137402). I have the following setup:
```
dual-stack service (2 nginx pods, one per each node)
PreferDualStack
LoadBalancer
externalTrafficPolicy: Local
[10.106.96.35,fd00:1234::5:39f5]
links to   -----------+-------------------> dual-stack pod: 10.244.73.204,fd00:5678::1eec:4beb:7691:1b0b
                      |                     on dual-stack node (dual-stack-1)
                      +-------------------> single-stack pod: 10.244.9.138
                                            on IPv4-only node (single-stack-2)
```
There are no health check binding errors and the single-stack mode is correctly detected in the IPv4-only node.
 
The dual-stack node listens to the following ports for the health check:
```
dual-stack-1$ netstat -na | grep 31404
tcp        0      0 0.0.0.0:31404           0.0.0.0:*               LISTEN     
tcp6       0      0 :::31404                :::*                    LISTEN
```
The single-stack node:
```
single-stack-2$ netstat -na | grep 31404
tcp        0      0 0.0.0.0:31404           0.0.0.0:*               LISTEN
```
 
and naturally the dual-stack node's health check can be reached with both IP address families:
 
```
dual-stack-1$ curl [::]:31404
{
	"service": {
		"namespace": "default",
		"name": "nginx-dual"
	},
	"localEndpoints": 1,
	"serviceProxyHealthy": true
}
dual-stack-1$ curl 127.0.0.1:31404
{
	"service": {
		"namespace": "default",
		"name": "nginx-dual"
	},
	"localEndpoints": 1,
         "serviceProxyHealthy": true
}
```
whereas the single node only with IPv4:
```
single-stack-2$ curl 127.0.0.1:31404
{
	"service": {
		"namespace": "default",
		"name": "nginx-dual"
	},
	"localEndpoints": 1,
	"serviceProxyHealthy": true
}
```
If I then alter the scenario a little bit and enable the IPv6 support also on the second node but still request only IPv4 address for the pod. Both health checks are now created on the second node, which is expected, because it also is now dual-stack capable:

```
dual-stack-2$ netstat -na | grep 31292
tcp        0      0 0.0.0.0:31292           0.0.0.0:*               LISTEN     
tcp6       0      0 :::31292                :::*                    LISTEN   
```
However, now if you run the health check, you get a different result on IPv4 and IPv6, but I would say that this is how it should be: the pod does not have an IPv6 address and thus `localEndpoints` is 0.
 
 ```
dual-stack-2$ curl 0.0.0.0:31292
{
	"service": {
		"namespace": "default",
		"name": "nginx-dual"
	},
	"localEndpoints": 1,
	"serviceProxyHealthy": true
}
dual-stack-2$ curl [::]:31292
{
	"service": {
		"namespace": "default",
		"name": "nginx-dual"
	},
	"localEndpoints": 0,
	"serviceProxyHealthy": true
}
```

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 1]
```diff
@@ -149,7 +149,7 @@ func TestServer(t *testing.T) {
 	nodePortAddresses := proxyutil.NewNodePortAddresses(v1.IPv4Protocol, []string{})
 	proxyChecker := &fakeProxyHealthChecker{true}
 
-	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, nodePortAddresses, proxyChecker)
+	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, nodePortAddresses, proxyChecker, v1.IPv4Protocol)
```
Comment (terror96) [inline pkg/proxy/healthcheck/healthcheck_test.go:152]: I wonder whether we should use `v1.IPFamilyUnknown` instead. That way the test behavior would not be altered: the health service is now created to listen only on IPv4, whereas previously it listened on both IPv4 and IPv6 when both were available on the host.

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 2]
```diff
@@ -972,7 +972,7 @@ func TestServerWithSelectiveListeningAddress(t *testing.T) {
 	// machine nor testing ipv6 || ipv4. using loop back guarantees the test will work on any machine
 	nodePortAddresses := proxyutil.NewNodePortAddresses(v1.IPv4Protocol, []string{"127.0.0.0/8"})
 
-	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, nodePortAddresses, proxyChecker)
+	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, nodePortAddresses, proxyChecker, v1.IPv4Protocol)
```
Comment (terror96) [inline pkg/proxy/healthcheck/healthcheck_test.go:975]: Same here.

File: pkg/proxy/healthcheck/healthcheck_test.go (hunk 1 above)
Comment (danwinship) [reply pkg/proxy/healthcheck/healthcheck_test.go:152]: These tests use `fakeListener` and `fakeNetListener` so they're not really testing the real code anyway...

**Comment by timuthy** [comment]
Thanks for the fix @terror96. Is it planned to backport this fix?
