### PR TITLE
Cap nf_conntrack limits to prevent excessive memory usage on high-core machines

### LINKED ISSUE #136228: kubernetes is reconfiguring iptables/netfilter data structures with bad settings
### What happened?

Hello,

I've been debugging issues with my Kubernetes nodes having very high CPU usage in network components.

I've finally traced down the origin to that block of code, which is overriding sysctl settings for iptables with insanely high values.
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/conntrack/sysctls.go#L62

The default is for the kernel to configurable iptables data structures based on available memory. Typically 32k-256k buckets and 256k max entries (this may be a tad low for the most busy servers). 

**Problem: Kubernetes is reconfiguring the iptables data structures based on the number of CPU cores. It's broken on machines with many CPU.
On my servers with 512 cores, I am seeing Kubernetes reconfigure the kernel to have 16M iptables entries with a 4M hash table.
That's a 32 MB hash table that can't fit in CPU cache, with 6 GB of entries. It's ridiculous.**

The large data structure is causing constant thrashing of the CPU cache on all cores, as every network packet has to lookup the table multiple times, and network packets are distributed across all CPU cores for processing.

Some operations need to go over the whole hashtable, for read or write (write has locks), which is affected by the large size of the table. This is why you've been having issues with nginx proxy (among other bugs), you've got bug tickets investigating performance issue with processing/updating that table, but nobody pointing out that it should not have millions of items, no wonder it's slow to process!

Can you please correct this code?

This should be set to a fixed value. I think 256k buckets, 1M max entries is a good default value that should work for >99% of users.
If anyone reaches that limit, they should check with `netstat` what is consuming active entries, then they probably need to reduce the sysctl timeout to evict these entries faster, as the default is keeping them for too long.

```
net.nf_conntrack_max = 1048576
net.netfilter.nf_conntrack_buckets = 262144
```

Regards.

### What did you expect to happen?

iptables should have reasonable configuration

### How can we reproduce it (as minimally and precisely as possible)?

you can look at sysctl settings on any kubernetes nodes with many cores and see the problem

### Anything else we need to know?

_No response_

### Kubernetes version

all versions affected

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
on premise
</details>

### OS version

all Linux OS are affected as kubernetes is incorrected overwriting iptables settings from the OS.

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```
</details>

### Install tools

<details>
</details>

### Container runtime (CRI) and version (if applicable)

<details>
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
</details>

### PR DESCRIPTION
**Pull request by kairosci**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

On machines with a very high number of cores (e.g., 512 cores), the default calculation for `nf_conntrack_max` (based on `MaxPerCore`) can result in excessively large values that consume significant system memory.

This PR introduces a hard cap of 1,048,576 for the automatically calculated `nf_conntrack_max` value to prevent these edge cases, while still allowing for high-performance networking on most configurations.

#### Which issue(s) this PR fixes:

Fixes #136228

#### Special notes for your reviewer:

A new test case `TestGetConntrackMax_Capped` has been added to `pkg/proxy/conntrack/sysctls_test.go` to verify the capping logic with mocked high core counts.

#### Does this PR introduce a user-facing change?

```release-note
Capped nf_conntrack_max to 1,048,576 to prevent excessive memory consumption on high-core machines when using automatic calculation.
```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

it is clear the problem but is unclear the solution, if we pick a number, why that number? it will be always valid? users can already override the values to fit to their environments, is that option not valid? 

mandatory xkcd 
image

**Comment by danwinship** [comment]
There's some discussion of why specific values in the issue. Also, note that the cap in this PR only applies to the auto-detected default value; you can still manually specify a larger value.

File: pkg/proxy/conntrack/sysctls_test.go [hunk 1]
```diff
@@ -238,3 +238,30 @@ func TestSetupConntrack(t *testing.T) {
 		})
 	}
 }
+
+func TestGetConntrackMax_Capped(t *testing.T) {
+	// preserve original
+	originalDetectNumCPU := detectNumCPU
+	defer func() { detectNumCPU = originalDetectNumCPU }()
```
Comment (danwinship) [inline pkg/proxy/conntrack/sysctls_test.go]: Hm... this is weird. I don't think we do anything like this anywhere else.

`getConntrackMax` is only used internally; you can move the `detectNumCPU` call out into its caller and pass in the result.

**Comment by danwinship** [comment]
> #### Which issue(s) this PR is related to:
> 
> N/A

can you fix that? ("Fixes #136228")

File: pkg/proxy/conntrack/sysctls_test.go (hunk 1 above)
Comment (kairosci) [reply pkg/proxy/conntrack/sysctls_test.go]: I believe I done.

File: pkg/proxy/conntrack/sysctls_test.go [hunk 2]
```diff
@@ -69,7 +69,7 @@ func TestGetConntrackMax(t *testing.T) {
 			MaxPerCore: ptr.To(tc.maxPerCore),
 		}
 		_, ctx := ktesting.NewTestContext(t)
-		x, e := getConntrackMax(ctx, &cfg)
+		x, e := getConntrackMax(ctx, &cfg, ncores)
```
Comment (danwinship) [inline pkg/proxy/conntrack/sysctls_test.go:72]: Ha! This test was wrong before because the test called `runtime.NumCPU()` but `getConntrackMax()` called `detectNumCPU()` which would give a different answer in some environments, making the test fail. But now it's guaranteed it will calculate the answer in the expected way.
