### PR TITLE
Fix:[Flaky test] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods

### LINKED ISSUE #108774: [Flaky test] [sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods
### Failure cluster [39e8b3298cff6883920e](https://go.k8s.io/triage#39e8b3298cff6883920e)

Test: [sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods

##### Error text:
```
test/e2e_node/density_test.go:248
Unexpected error:
    <*errors.errorString | 0xc00164fef0>: {
        s: "too high pod startup latency 50th percentile: 6.015599293s",
    }
    too high pod startup latency 50th percentile: 6.015599293s
occurred
test/e2e_node/density_test.go:588
```
#### Recent failures:
[3/16/2022, 1:18:16 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1504190296534028288)
[3/15/2022, 9:17:38 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1503948564064112640)
[3/11/2022, 8:08:57 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502315621528899584)
[3/11/2022, 12:06:56 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502194321300918272)
[3/10/2022, 4:05:24 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502073143848603648)

/kind flake

/sig node

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/issues/108774#issuecomment-1077053385

We reduce the poll interval to 500ms to get the pod Running status in time
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/108774

#### Special notes for your reviewer:
/cc @ehashman @SergeyKanzhelev 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/density_test.go [hunk 1]
```diff
@@ -528,7 +532,8 @@ func createBatchPodSequential(f *framework.Framework, pods []*v1.Pod) (time.Dura
 	e2eLags := make([]e2emetrics.PodLatencyData, 0)
 	for _, pod := range pods {
 		create := metav1.Now()
-		f.PodClient().CreateSync(pod)
+		p := f.PodClient().Create(pod)
+		framework.ExpectNoError(wait.PollImmediate(500*time.Millisecond, 2*time.Minute, podRunningAndReady(f, p.Name)))
```
Comment (endocrimes) [inline test/e2e_node/density_test.go:536]: The default timeout is 5 minutes (https://github.com/kubernetes/kubernetes/blob/e2206cae9dacb397369980bf1c9e76d04234845b/test/e2e/framework/timeouts.go#L23) - we might want to reference that here, rather than reducing it - or at least document why it's shorter.

Comment (aojea) [reply test/e2e_node/density_test.go:536]: there are already plenty of these helpers https://github.com/kubernetes/kubernetes/blob/f173d01c011c3574dea73a6fa3e20b0ab94531bb/test/e2e/framework/pod/wait.go#L365

I see that the e2e_node keep drifting from the e2e frameworks and is much more unstable, I think that there is more benefit on keep things aligned, also consolidating the timeouts as Danielle suggests

Comment (249043822) [reply test/e2e_node/density_test.go:536]: The intention for my change is to deduce the polling interval for getting the pod status Running as soon as possible, because the test is for performance, so 2s > 500ms could be more punctual for status change

Comment (249043822) [reply test/e2e_node/density_test.go:536]: okay, agree that we should keep the timeout as it is originally

Comment (pacoxu) [reply test/e2e_node/density_test.go]: https://storage.googleapis.com/k8s-triage/index.html?test=create%20a%20sequence%20of%20pods%20latency#ae63e7365ad14fba9b1e
The test case still flakes.

I agree that 500ms may help if the percent 50 is expected to under 5s.
- 2s interval is too big for a density check which is 5-10s.
```
				podStartupLimits: e2emetrics.LatencyMetric{
					Perc50: 5000 * time.Millisecond,
					Perc90: 9000 * time.Millisecond,
					Perc99: 10000 * time.Millisecond,
				},
```

However, as Antonio pointed out, there is already helper func like `WaitTimeoutForPodReadyInNamespace`.
Can we reuse it or add a help func for this configurable interval wait in `wait.go` for this?

Comment (249043822) [reply test/e2e_node/density_test.go]: okay, thanks

File: test/e2e_node/density_test.go [hunk 2]
```diff
@@ -530,7 +530,8 @@ func createBatchPodSequential(f *framework.Framework, pods []*v1.Pod) (time.Dura
 	e2eLags := make([]e2emetrics.PodLatencyData, 0)
 	for _, pod := range pods {
 		create := metav1.Now()
-		f.PodClient().CreateSync(pod)
+		p := f.PodClient().Create(pod)
+		framework.ExpectNoError(e2epod.WaitTimeoutForPodReadyInNamespaceWithInterval(f.ClientSet, p.Name, p.Namespace, 500*time.Millisecond, framework.PodStartTimeout))
```
Comment (aojea) [inline test/e2e_node/density_test.go:534]: why polling faster solves the problem?

Comment (pacoxu) [reply test/e2e_node/density_test.go:534]: Sorry, I just see the test is using `LatencyMetric` which is not related with the checking interval.

It should not be related.

Comment (aojea) [reply test/e2e_node/density_test.go:534]: then I think that the right fix is to use a listWatcher, same technique is used by sig-scalability

https://github.com/kubernetes/perf-tests/blob/1e3b84449e818ab9ae3a0336da53f374c6dea560/clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go#L127-L155

Comment (249043822) [reply test/e2e_node/density_test.go]: I have changed to use informer which has been used by `runDensityBatchTest`, /cc @aojea @pacoxu

**Review by pacoxu — APPROVED** [review]
/lgtm
will try to test it locally.

**Review by endocrimes — APPROVED** [review]
This is a little bit over complicated, and i'd like us to follow up by trying to simplify it, but going to approve to try and bring things to a little more stable.

**Comment by pacoxu** [comment]
@endocrimes you approved the pr, but the pr is not updated by the CI-bot.

**Review by pacoxu — APPROVED** [review]

**Comment by pacoxu** [comment]
The result looks good.

**Before**
Succeed will be like 40xx. Or failed like 60xx ms.
```
        "Perc50": 4026.764349,
```

**After**
Succeed will be like 3000~5000.
```
        "Perc50": 3465.344608,
```
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1542403039346823168/artifacts/performance-latency-fedora-density_create_sequence_10_50_0_5.json
