### PR TITLE
cluster/aws: Fix #14162, reboot docker failure with Ubuntu server

### LINKED ISSUE #14162: Node in NotReady status after kernel upgrade and reboot on Ubuntu Vivid (15.04) due to Docker service failure (no aufs)
Hi. I'm writing this partially because I want to start a discussion and to leave some trails for others potentially affected.

I started my journey with Kubernetes just a few days ago. I downloaded the 1.0.6 release (now I know this a only a pre-release and I should've downloaded the 1.0.4 release but this doesn't seem to be related to my particular issue).

I brought up a tiny k8s cluster with the following config:
```
export KUBERNETES_PROVIDER=aws
export KUBE_AWS_ZONE=eu-west-1a
export NUM_MINIONS=3
export MINION_SIZE=t2.micro
export AWS_S3_REGION=eu-west-1
export AWS_S3_BUCKET=xxx
export KUBE_AWS_INSTANCE_PREFIX=xxx
```

My cluster was created properly and after a bit of playing I left it in a good shape.

The next day I wanted to investigate some DNS related issue on k8s nodes so I logged in on one of the minions. I noticed `*** System restart required ***` in the MOTD. I ignored it for a moment and investigated the DNS matters (some `nslookup`s, nothing dangerous). Then I rebooted the machine.

Once the machine was up again I found out that `kubectl` reported it as `NotReady`. I started digging and investigating. It took me some time to find out that the Docker service on the node was not running:

```
$ sudo docker info
FATA[0001] Get http:///var/run/docker.sock/v1.18/info: read unix /var/run/docker.sock: connection reset by peer. Are you trying to connect to a TLS-enabled daemon without TLS?
```

```
$ sudo journalctl -u docker -f
-- Logs begin at Fri 2015-09-18 08:06:53 UTC. --
Sep 18 08:09:49 ip-172-20-0-149 systemd[1]: docker.service failed.
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: docker.service holdoff time over, scheduling restart.
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: Started Docker Application Container Engine.
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: Starting Docker Application Container Engine...
Sep 18 08:09:51 ip-172-20-0-149 docker[3397]: time="2015-09-18T08:09:51Z" level=info msg="+job serveapi(fd://)"
Sep 18 08:09:51 ip-172-20-0-149 docker[3397]: time="2015-09-18T08:09:51Z" level=info msg="Listening for HTTP on fd ()"
Sep 18 08:09:51 ip-172-20-0-149 docker[3397]: time="2015-09-18T08:09:51Z" level=fatal msg="Shutting down daemon due to errors: error intializing graphdriver: driver not supported"
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: Unit docker.service entered failed state.
Sep 18 08:09:51 ip-172-20-0-149 systemd[1]: docker.service failed.
```

Further investigation led me to a conclusion that the problem arose from the fact that before the reboot the kernel was upgraded to 3.19.0-28, which no longer by default supports AUFS module which Docker uses as its storage driver.

Looks like the solution is to install the `linux-image-extra-virtual`, as concluded from docker/docker#10859 and other sources, and reboot the node. After reboot the node got back to the `Ready` state.

Moreover, I guess an upgrade to a newer Docker version, using the official install command `curl -sSL https://get.docker.com/ | sh` would solve the problem as the most recent install script already installs `linux-image-extra-virtual` as per docker/docker#10860, although I'm not sure how Docker was installed on the k8s node, so I don't know if it's safe to upgrade it this way.

So I have a number of questions:
1. should k8s provide a workaround / fix for this particular issue?
2. or is it left to a cluster admin as it's an issue of a particular provider/env/configuration?
3. why is k8s using Docker v1.6.0 which is pretty old?
4. is it safe to use k8s in production on a setup in which Docker uses AUFS storage driver which seems to be deprecated by the Ubuntu team and thus dropped from the main kernel image?

Note that I haven't done anything unusual, just installed fresh k8s on AWS using the default Ubuntu release. Hence I believe it's important to fix it somehow in k8s.

Possible duplicate: #9779.

### PR DESCRIPTION
**Pull request by paralin**
Fixes AWS ubuntu deployment due to extra-$(uname) vs extra-virtual package being installed. See issue #14162.

### CODE REVIEW

**Comment by paralin** [comment]
This is a good solution until Docker is upgraded on default for cutting v1.1 release.

File: cluster/aws/templates/format-disks.sh [hunk 1]
```diff
@@ -172,7 +172,10 @@ if [[ ${docker_storage} == "btrfs" ]]; then
   DOCKER_OPTS="${DOCKER_OPTS} -s btrfs"
 elif [[ ${docker_storage} == "aufs-nolvm" || ${docker_storage} == "aufs" ]]; then
   # Install aufs kernel module
-  apt-get install --yes linux-image-extra-$(uname -r)
+  #apt-get install --yes linux-image-extra-$(uname -r)
```
Comment (romanek-adam) [inline cluster/aws/templates/format-disks.sh]: This line should not be commented out!

You need aufs module for the current kernel, so that kubernetes could run docker images until kernel is upgraded and machine is reboot.

I made the same mistake when trying to fix the root cause but I had to leave two separate `apt-get install linux-image-extra-XXX`.

Comment (paralin) [inline cluster/aws/templates/format-disks.sh]: Okay, so we just leave both?

**Comment by paralin** [comment]
@romanek-adam Fixed, please have a look

**Comment by romanek-adam** [comment]
@paralin looks fine to me.

**Comment by paralin** [comment]
cc @davidopp

**Comment by justinsb** [comment]
ok to test

**Comment by justinsb** [comment]
(stealing this one @eparis - LMK if you're unhappy about that!)

Thanks for the fix @paralin .  I will LGTM this once e2e passes.  (I'm not even sure whether I technically need to do that, given GCE e2e won't even touch this code, but anyway...)

**Comment by eparis** [comment]
/me is not upset, I'm going to dig myself out of reviews today.

**Comment by justinsb** [comment]
e2e test failure is unrelated; marking LGTM.

**Comment by four43** [comment]
For what it's worth, I was able to start docker once again by just installing the linux-image-extra-$(uname -r) package. Steps to reproduce:

1) Deploy Kuberentes v1.0.6 prod to AWS using Ubuntu Vivid
2) Restart a minion
3) Minion fails to return to the cluster, Docker won't start
4) Install linux-image-extra-xxx, Docker auto started, back running fine again.

**Comment by paralin** [comment]
@four43 after a reboot it will be broken again

**Comment by davidopp** [comment]
@k8s-bot test this please
