### PR TITLE
Skip storage tests that depend on default SC - if no default SC is found

### LINKED ISSUE #76623: Skip PVC protection tests in environments where there is no default storageclass available
We should be able to skip pvc protection e2es in environments that don't have any default 
storageclass available (such as baremetal). Currently they fail on waiting for default storageclass.

/sig storage

cc @kubernetes/sig-storage-misc

### PR DESCRIPTION
**Pull request by gnufied**
Other tests that check for default storageclass also
check for cloudprovider such as gce, aws and openstack
and hence are already skipped in bare metal environments.

But this particular test keeps failing because no such check exists.

fixes https://github.com/kubernetes/kubernetes/issues/76623

/sig storage

cc @kubernetes/sig-storage-misc

### CODE REVIEW

File: test/e2e/storage/pvc_protection.go [hunk 1]
```diff
@@ -48,7 +48,10 @@ var _ = utils.SIGDescribe("PVC Protection", func() {
 
 		By("Creating a PVC")
 		suffix := "pvc-protection"
-		defaultSC := getDefaultStorageClassName(client)
+		defaultSC, _ := getDefaultStorageClassName(client)
+		if defaultSC == "" {
+			framework.Skipf("no default storagclass configured skipping")
```
Comment (neolit123) [inline test/e2e/storage/pvc_protection.go]: minor typo in `storagclass`
-> "storage class"

Comment (msau42) [reply test/e2e/storage/pvc_protection.go]: There's a similar pr out here: https://github.com/kubernetes/kubernetes/pull/68949

I think skipping is fine for now, although we may want to think of a better way for how we define/skip tests. Maybe via tags?  By blindly skipping, providers won't know if they've misconfigured their environment and may be missing out on test coverage.

**Comment by gnufied** [comment]
Still the failures are:

```
openshift-tests [Feature:Builds][Conformance] oc new-app should succeed with a --name of 58 characters [Suite:openshift/conformance/parallel/minimal] 1m5s
openshift-tests [sig-scheduling] ResourceQuota should create a ResourceQuota and capture the life of a secret. [Suite:openshift/conformance/parallel] [Suite:k8s] 55s
```

Which look unrelated to this change.


/retest

File: test/e2e/storage/pvc_protection.go (hunk 1 above)
Comment (gnufied) [reply test/e2e/storage/pvc_protection.go]: Yeah I think we may want to tag all the tests that depend on default SC. We have to do full sweep of test suite. 

Also #68949 is although related but does not affects at least in baremetal environments because there is no default SC anyways installed.

File: test/e2e/storage/pvc_protection.go [hunk 2]
```diff
@@ -48,7 +48,10 @@ var _ = utils.SIGDescribe("PVC Protection", func() {
 
 		By("Creating a PVC")
 		suffix := "pvc-protection"
-		defaultSC := getDefaultStorageClassName(client)
+		defaultSC, _ := framework.GetDefaultStorageClassName(client)
```
Comment (msau42) [inline test/e2e/storage/pvc_protection.go]: do you want to use SkipIfNoDefaultStorageClass here?

File: test/e2e/storage/volume_metrics.go [hunk 3]
```diff
@@ -52,8 +52,12 @@ var _ = utils.SIGDescribe("[Serial] Volume metrics", func() {
 	BeforeEach(func() {
 		c = f.ClientSet
 		ns = f.Namespace.Name
+		var err error
 		framework.SkipUnlessProviderIs("gce", "gke", "aws")
-		defaultScName = getDefaultStorageClassName(c)
+		defaultScName, _ = framework.GetDefaultStorageClassName(c)
+		if err != nil {
+			framework.Failf(err.Error())
```
Comment (msau42) [inline test/e2e/storage/volume_metrics.go]: Should this be a skip? I think we should consider removing the skip based on provider

File: test/e2e/storage/volume_metrics.go [hunk 4]
```diff
@@ -52,8 +52,12 @@ var _ = utils.SIGDescribe("[Serial] Volume metrics", func() {
...
+		}
 		verifyDefaultStorageClass(c, defaultScName, true)
```
Comment (msau42) [inline test/e2e/storage/volume_metrics.go]: is this verify needed?

File: test/e2e/storage/volume_provisioning.go [hunk 5]
```diff
@@ -803,7 +806,10 @@ var _ = utils.SIGDescribe("Dynamic Provisioning", func() {
 		// Modifying the default storage class can be disruptive to other tests that depend on it
 		It("should be disabled by removing the default annotation [Serial] [Disruptive]", func() {
 			framework.SkipUnlessProviderIs("openstack", "gce", "aws", "gke", "vsphere", "azure")
-			scName := getDefaultStorageClassName(c)
+			scName, scErr := framework.GetDefaultStorageClassName(c)
+			if scErr != nil {
+				framework.Failf(scErr.Error())
```
Comment (msau42) [inline test/e2e/storage/volume_provisioning.go]: same thing, skip and remove provider check?

File: test/e2e/storage/volume_metrics.go (hunk 3 above)
Comment (gnufied) [reply test/e2e/storage/volume_metrics.go]: Since some of these tests depend on underlying volume plugin implementing the particular metric interface, it may not be sufficient for default storageclass to be found.

File: test/e2e/storage/volume_provisioning.go (hunk 5 above)
Comment (gnufied) [reply test/e2e/storage/volume_provisioning.go]: Do we know that whatever default SC that will exist will support dynamic provisioning?

File: test/e2e/storage/volume_metrics.go (hunk 4 above)
Comment (gnufied) [reply test/e2e/storage/volume_metrics.go]: fixed

**Comment by gnufied** [comment]
@msau42 addressed most of the review comments. PTAL.

File: test/e2e/storage/volume_provisioning.go (hunk 5 above)
Comment (msau42) [reply test/e2e/storage/volume_provisioning.go]: it seems odd to define a default storageclass that cannot support dynamic provisioning. There is movement in the conformance area to also add some "validation" suites using the default storage class

Comment (gnufied) [reply test/e2e/storage/volume_provisioning.go]: Given current defaults it isn't out of question to have a SC that does not support dynamic provisioning. For example - a bare metal cluster that uses only local PVCs.  The cloudprovider tests explicitly allow us to skip these tests but a default SC won't.
