### PR TITLE
Fix zero PSI metrics emitted when OS doesn't enable PSI

### LINKED ISSUE #136333: Zero value Kubelet PSI metrics emitted even if underlying OS doesn't enable it
### What happened?

In Kubernetes 1.34, the KubeletPSI feature gate was set to true. However, when running Kubernetes on an OS that does not have PSI enabled, the PSI metrics are not expected to be generated. Here are the counts of the metrics observed during a test:
```
# for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do echo "=== Node: $node ==="; for metric in cpu_waiting cpu_stalled memory_waiting memory_stalled io_waiting io_stalled; do echo -n "container_pressure_${metric}_seconds_total: "; kubectl get --raw "/api/v1/nodes/$node/proxy/metrics/cadvisor" | grep "container_pressure_${metric}_seconds_total" | wc -l; done; done
=== Node: ip-10-0-11-217.us-east-2.compute.internal ===
container_pressure_cpu_waiting_seconds_total:      267
container_pressure_cpu_stalled_seconds_total:      267
container_pressure_memory_waiting_seconds_total:      267
container_pressure_memory_stalled_seconds_total:      267
container_pressure_io_waiting_seconds_total:      267
container_pressure_io_stalled_seconds_total:      267
```
I suspect this part of the code:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L105C53-L105C63
```
	if utilfeature.DefaultFeatureGate.Enabled(features.KubeletPSI) {
		includedMetrics[cadvisormetrics.PressureMetrics] = struct{}{}
	} 
```
and prometheus does this: https://github.com/google/cadvisor/blob/master/metrics/prometheus.go#L1842
```
	if includedMetrics.Has(container.PressureMetrics) {
		c.containerMetrics = append(c.containerMetrics, []containerMetric{
			{
				name:      "container_pressure_cpu_stalled_seconds_total", 
```

cc: @haircommander @bitoku 

### What did you expect to happen?

There should be no PSI metrics when underlying OS never enables it.

### How can we reproduce it (as minimally and precisely as possible)?

Run k8s 1.34 and above and use grafana to monitor PSI metrics

### Anything else we need to know?

This is a good to have. Doesn't really impact anything as cardinality is also negligible. This zero value confuses the end-user as it gives a visual impression that PSI is enabled when looking at grafana charts.

I can propose a fix on this.

### Kubernetes version

1.34
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>
k8s on GCP instances

### OS version

Linux: 5.14.0-570.78.1.el9_6.x86_64

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by amritansh1502**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When the `KubeletPSI` feature gate is enabled but the OS does not support PSI (either the kernel lacks `CONFIG_PSI` or was booted with `psi=0`), the kubelet could register `PressureMetrics` with cAdvisor. This causes zero-valued PSI metrics to be emitted, which is confusing for monitoring and alerting.

The previous `IsPsiEnabled()` implementation checked `/proc/pressure` and parsed `/proc/cmdline` for `psi=0`. This was unreliable because `/proc/pressure` can exist even when per-cgroup PSI files — which cAdvisor actually reads — are absent ( on cgroup v1 systems).

This PR simplifies `IsPsiEnabled()` to open `/sys/fs/cgroup/cpu.pressure` — the same type of per-cgroup file that cAdvisor reads PSI values from. This single check is sufficient because:
- PSI is a single kernel feature (`CONFIG_PSI` / boot param `psi=`) so checking `cpu.pressure` determines support for all three resources (cpu, memory, io).
- On cgroup v1 systems (where cAdvisor cannot read per-cgroup PSI anyway), this file does not exist, so we correctly skip PSI metrics.
- The `/proc/cmdline` parsing is no longer needed since the cgroup file's absence already covers the `psi=0` case.

#### Note:
PSI is a single kernel feature (`CONFIG_PSI` / boot param `psi=`) that exposes `/sys/fs/cgroup/cpu.pressure` atomically — checking onlys sys/fs/cgroup/cpu.pressure is sufficient to determine support for all three resource types.

The check is used in both `cadvisor.New()` and `Server.InstallAuthNotRequiredHandlers()` so that pressure metrics
are only collected when PSI is actually supported by the OS.

#### Screenshots:
After making the code changes , i have build it and copy kubelet to the local kind cluster and tested for both psi =0 and psi =1,  here are the results.
**Before (zero PSI metrics emitted):**
Screenshot From 2026-03-01 16-45-59

**After (PSI metrics skipped when unsupported):**
Screenshot From 2026-03-01 16-37-20

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/136333

#### Special notes for your reviewer:

- Unit tests cover both cases (file present and file absent) and all pass.
- Manually tested on a kind cluster with PSI enabled and PSI disabled (`psi=0` via GRUB).

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue where zero-valued PSI (Pressure Stall Information) metrics were emitted by the kubelet when the OS does not support PSI, even if the KubeletPSI feature gate was enabled.

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
N/A
```

### CODE REVIEW

File: pkg/kubelet/cadvisor/cadvisor_linux.go [hunk 1]
```diff
@@ -162,6 +168,40 @@ func (cc *cadvisorClient) ImagesFsInfo(ctx context.Context) (cadvisorapiv2.FsInf
 	return cc.getFsInfo(ctx, label)
 }
 
+// IsPsiEnabled checks whether PSI (Pressure Stall Information) is available on
+// the host. PSI is a single kernel feature (CONFIG_PSI / boot param "psi=")
+// that exposes /proc/pressure/{cpu,memory,io} atomically — checking the
+// /proc/pressure directory is sufficient to determine support for all three.
+func IsPsiEnabled(ctx context.Context) bool {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: is kubelet the right place to have this logic in? Will it be better to have this detection be read from the same place cAdvisor reads actual values?

File: pkg/kubelet/cadvisor/cadvisor_linux.go [hunk 2]
```diff
@@ -102,7 +103,12 @@ func New(imageFsInfoProvider ImageFsInfoProvider, rootPath string, cgroupRoots [
 	}
 
 	if utilfeature.DefaultFeatureGate.Enabled(features.KubeletPSI) {
-		includedMetrics[cadvisormetrics.PressureMetrics] = struct{}{}
+		ctx := context.Background()
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: nit, it may be best to allow to pass logger into `New` method and use it everywhere. We may decide to have a context in future in those operations, but since it is mostly file system operations, I do not expect it happen very soon.

Comment (amritansh1502) [reply pkg/kubelet/cadvisor/cadvisor_linux.go]: will fix , i will update New() to accept a klog.Logger instead of creating a context.Background() internally.

File: pkg/kubelet/cadvisor/cadvisor_linux.go (hunk 1 above)
Comment (amritansh1502) [reply pkg/kubelet/cadvisor/cadvisor_linux.go]: Yeah reading from the same place cadvisor reads actual values is feasible , Currently i am checking /proc/pressure +  /proc/cmdline , but cadvisor actually reads PSI from per-cgroup pressure files via the opencontainers/cgroups library, and its statPSI() already returns nil when those files don't exist or the kernel returns ENOTSUP. I will change the detection to stat the root cgroup's file instead .

Comment (SergeyKanzhelev) [reply pkg/kubelet/cadvisor/cadvisor_linux.go]: is there a reference to opencontainers/cgroups already? Can we call some library method instead of re-implementing it and trying to keep in-sync long term?

Comment (amritansh1502) [reply pkg/kubelet/cadvisor/cadvisor_linux.go]: thanks, yes opencontainers/cgroups is already used in pkg/kubelet/cm/, we can use cgroups.Openfile and cgroupfs2.UnifiedMountpoint

File: pkg/kubelet/cadvisor/cadvisor_linux.go [hunk 3]
```diff
@@ -162,6 +168,26 @@ func (cc *cadvisorClient) ImagesFsInfo(ctx context.Context) (cadvisorapiv2.FsInf
...
+// the host by opening the root cgroup's cpu.pressure file using the same
+// opencontainers/cgroups library that cAdvisor uses to read actual PSI values.
+// PSI is a single kernel feature (CONFIG_PSI / boot param "psi=") so checking
+// cpu.pressure alone is sufficient to determine support for all three resources
+// (cpu, memory, io).
+func IsPsiEnabled(logger klog.Logger) bool {
+	return isPsiEnabled(logger, cgroupfs2.UnifiedMountpoint, "cpu.pressure")
+}
+
+func isPsiEnabled(logger klog.Logger, cgroupDir, psiFile string) bool {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cadvisor/cadvisor_linux.go:181]: this way of checking is lgtm. Ideal for me would be if this would have happened in cAdvisor and it will not return zeroes for something that doesn't exist.

**Review by SergeyKanzhelev — COMMENTED** [review]
@ndixita any thoughts on this PR?

File: pkg/kubelet/cadvisor/cadvisor_linux.go (hunk 3 above)
Comment (amritansh1502) [reply pkg/kubelet/cadvisor/cadvisor_linux.go:181]: thanks, agreed, ideally cAdvisor itself would not emit zeros when PSI data is nil ,the statPSI() nil gets flattened to a zero-valued struct in cAdvisor setPSIStats before reaching the prometheus . I will file an upstream issue on google/cadvisor to track that as a follow-up.

**Comment by amritansh1502** [comment]
hi @SergeyKanzhelev, thank you for the review feedback i have  addressed your comments 
in the latest push. Could you take another look when you get a chance?

with Code Freeze coming up tomorrow , I would really appreciate a review 
if possible. 

cc @ndixita @dchen1107

File: pkg/kubelet/cadvisor/cadvisor_linux.go (hunk 3 above)
Comment (roycaihw) [reply pkg/kubelet/cadvisor/cadvisor_linux.go:181]: +1. Having cAdvisor handle that will be cleaner and more consistent. This PR LGTM as to mitigate the issue. We can migrate when cAdvisor is ready.

File: pkg/kubelet/cadvisor/cadvisor_linux.go [hunk 4]
```diff
@@ -102,7 +104,11 @@ func New(imageFsInfoProvider ImageFsInfoProvider, rootPath string, cgroupRoots [
 	}
 
 	if utilfeature.DefaultFeatureGate.Enabled(features.KubeletPSI) {
-		includedMetrics[cadvisormetrics.PressureMetrics] = struct{}{}
+		if IsPsiEnabled(logger) {
+			includedMetrics[cadvisormetrics.PressureMetrics] = struct{}{}
+		} else {
+			logger.Info("PSI support not available")
```
Comment (roycaihw) [inline pkg/kubelet/cadvisor/cadvisor_linux.go:110]: Instead of Info, should this be Warning? It seems to be a misconfiguration to me if KubeletPSI is enabled but kernel doesn't support it.

**Comment by SergeyKanzhelev** [comment]
/lgtm
/approve
/skip

let's merge this and follow up on cAdvisor fix
