### PR TITLE
Fixing e2e CSI test

### LINKED ISSUE #60803: CSI E2E test failure
After switching to CSI spec 0.2.0 extra permissions are required. 
/kind bug
/assign @sbezverk
/sig storager

### PR DESCRIPTION
**Pull request by sbezverk**
Closes #60803

After switching to CSI 0.2.0 spec, additional RBAC permissions are required.  This PR adds missing permissions.

```release-note
None
```

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]

File: test/e2e/storage/csi_volumes.go [hunk 1]
```diff
@@ -92,6 +92,16 @@ func csiClusterRole(
 				Resources: []string{"persistentvolumeclaims"},
 				Verbs:     []string{"get", "list", "watch", "update"},
 			},
+			{
+				APIGroups: []string{""},
+				Resources: []string{"events"},
+				Verbs:     []string{"get", "list", "watch", "creat", "update", "patch"},
```
Comment (jsafrane) [inline test/e2e/storage/csi_volumes.go]: typo: `create`?

Comment (saad-ali) [reply test/e2e/storage/csi_volumes.go]: https://github.com/kubernetes/kubernetes/pull/60840
