### PR TITLE
Fix e2e for PodHostIPs

### LINKED ISSUE #121424: [Failing-Test][sig-network] DualStack Host IP [Feature:PodHostIPs] when creating a Pod, it has no PodHostIPs feature should create pod with hostNetwork, add host ips is empty
### Which jobs are failing?

4 other Test Failures in ci-crio-cgroupv1-node-e2e-features.

### Which tests are failing?

Test [E2eNode Suite.[It] [sig-network] DualStack Host IP [NodeFeature:PodHostIPs] [Feature:PodHostIPs] when creating a Pod, it has no PodHostIPs feature should create pod with hostNetwork, add host ips is empty [sig-network]](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features) has failed 61 times (no passing result found). Earliest failure found at commit/239537e74 (Thu Oct 19 21:41 PDT).

### Since when has it been failing?

https://github.com/kubernetes/kubernetes/pull/120257
/cc @wzshiming

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Reason for failure (if possible)

{ failed [FAILED] Error creating Pod: pods "pod-dualstack-host-ips9ddb9810-134c-4d35-a0c6-84950abdef25" is forbidden: violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true)
In [It] at: test/e2e/framework/pod/pod_client.go:99 @ 10/23/23 01:38:06.024
}

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig network node

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind flake

#### Which issue(s) this PR fixes:

Fixes #121424

https://github.com/kubernetes/kubernetes/pull/121445

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: test/e2e_node/pod_host_ips.go [hunk 1]
```diff
@@ -54,33 +55,21 @@ var _ = common.SIGDescribe("DualStack Host IP [NodeFeature:PodHostIPs] [Feature:
...
-
-			gomega.Expect(p.Status.HostIP).ShouldNot(gomega.BeEquivalentTo(""))
-			gomega.Expect(p.Status.HostIPs).Should(gomega.BeNil())
-
-			ginkgo.By("deleting the pod")
-			err := podClient.Delete(ctx, pod.Name, *metav1.NewDeleteOptions(1))
-			framework.ExpectNoError(err, "failed to delete pod")
-		})
-
-		ginkgo.It("should create pod with hostNetwork, add host ips is empty", func(ctx context.Context) {
```
Comment (wzshiming) [inline test/e2e_node/pod_host_ips.go:70]: Remove case with hostNetwork, because `forbidden: violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true)`

**Comment by pacoxu** [comment]
/priority critical-urgent
 this test failed in multi- test grid boards:

- https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features
- https://testgrid.k8s.io/sig-node-cri-o#kubelet-gce-e2e-swap-fedora
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-features
- https://testgrid.k8s.io/sig-node-containerd#image-validation-node-features

**Comment by aojea** [comment]
> /priority critical-urgent this test failed in multi- test grid boards:
> 
> * https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features
> * https://testgrid.k8s.io/sig-node-cri-o#kubelet-gce-e2e-swap-fedora
> * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features
> * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-features
> * https://testgrid.k8s.io/sig-node-containerd#image-validation-node-features

Some important thing to take into account, the tests are authoritative, if some job fail to run the test is the job that has to skip it , we never remove tests unless they are clearly wrong or doing bad assumptions

/hold

In this case , it seems the test requires privileges on those environments, no?

```
   pods "pod-dualstack-host-ips2c343e2d-5145-46d1-9095-95aa8358465a" is forbidden: violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true)
    {
        ErrStatus: 
            code: 403
            details:
              kind: pods
              name: pod-dualstack-host-ips2c343e2d-5145-46d1-9095-95aa8358465a
            message: 'pods "pod-dualstack-host-ips2c343e2d-5145-46d1-9095-95aa8358465a" is forbidden:
              violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true)'
            metadata: {}
```

File: test/e2e_node/pod_host_ips.go [hunk 2]
```diff
@@ -76,11 +84,16 @@ var _ = common.SIGDescribe("DualStack Host IP [NodeFeature:PodHostIPs] [Feature:
 			podClient := e2epod.NewPodClient(f)
 			p := podClient.CreateSync(ctx, pod)
 
+			_ = e2epod.WaitForPodCondition(ctx, f.ClientSet, p.Namespace, p.Name, "PodHostIPs", 30*time.Second, func(pod *v1.Pod) (bool, error) {
+				return pod.Status.HostIPs == nil, nil
+			})
+			p, err := podClient.Get(ctx, pod.Name, metav1.GetOptions{})
+			framework.ExpectNoError(err)
 			gomega.Expect(p.Status.HostIP).ShouldNot(gomega.BeEquivalentTo(""))
 			gomega.Expect(p.Status.HostIPs).Should(gomega.BeNil())
```
Comment (aojea) [inline test/e2e_node/pod_host_ips.go:93]: I don't think you need this async check, the CreateSync method already waits for the pod to be ready and at taht point it should have the ips set.

Just remove the async checks added, only add the tag for the security thing

**Review by aojea — CHANGES_REQUESTED** [review]

File: test/e2e_node/pod_host_ips.go (hunk 2 above)
Comment (aojea) [reply test/e2e_node/pod_host_ips.go]: great, thanks for pointing out

Comment (aojea) [reply test/e2e_node/pod_host_ips.go]: in that case, you need to move the assertion in the async loop, don't need to assert twice

```
			err := e2epod.WaitForPodCondition(ctx, f.ClientSet, p.Namespace, p.Name, "PodHostIPs", 30*time.Second, func(pod *v1.Pod) (bool, error) {
                                 if pod.Status.HostIP == "" {
                                         return false, nil
                                 }
				return len(pod.Status.HostIPs) >0 , nil
			})
-			p, err := podClient.Get(ctx, pod.Name, metav1.GetOptions{})
			framework.ExpectNoError(err)
-			gomega.Expect(p.Status.HostIP).ShouldNot(gomega.BeEquivalentTo(""))
-			gomega.Expect(p.Status.HostIPs).Should(gomega.BeNil())
```

Comment (aojea) [reply test/e2e_node/pod_host_ips.go]: just add
```
			err := e2epod.WaitForPodCondition(ctx, f.ClientSet, p.Namespace, p.Name, "PodHostIPs", 30*time.Second, func(pod *v1.Pod) (bool, error) {
                                 if pod.Status.HostIP == "" {
                                         return false, nil
                                 }
				return len(pod.Status.HostIPs) >0 , nil
			})
			if err != nil {
                                framework.Failf("timeout waiting for Pod %s to get HostIPs", pod.Name, err)
                        }

```

and remove 
```
			p, err := podClient.Get(ctx, pod.Name, metav1.GetOptions{})
			framework.ExpectNoError(err)
			gomega.Expect(p.Status.HostIP).ShouldNot(gomega.BeEquivalentTo(""))
			gomega.Expect(p.Status.HostIPs).Should(gomega.BeNil())
- ```

**Comment by wzshiming** [comment]
@aojea @pacoxu PTAL

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121429/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1716694153540145152 

One of the GracefulNodeShutdown fixes is in progress at https://github.com/kubernetes/kubernetes/pull/120728

File: test/e2e_node/pod_host_ips.go [hunk 3]
```diff
@@ -276,6 +333,17 @@ func testDownwardAPI(ctx context.Context, f *framework.Framework, podName string
 						},
 					},
 					Env: env,
+					SecurityContext: &v1.SecurityContext{
```
Comment (aojea) [inline test/e2e_node/pod_host_ips.go:336]: do we really need this?
I'm surprised we need this just to create a simple pod, the errors on policy we saw were related to the HostNetwork capability that should be fixed by `	f.NamespacePodSecurityLevel = admissionapi.LevelPrivileged`

Comment (wzshiming) [reply test/e2e_node/pod_host_ips.go:336]: Before adding `admissionapi.LevelPrivileged` according to CI error added before, I try to delete it

File: test/e2e_node/pod_host_ips.go [hunk 4]
```diff
@@ -214,23 +172,34 @@ var _ = common.SIGDescribe("Dual Stack Host IP [Feature:PodHostIPs]", func() {
...
 
 			ginkgo.By("deleting the pod")
-			err = podClient.Delete(ctx, pod.Name, *metav1.NewDeleteOptions(30))
+			err = podClient.Delete(ctx, pod.Name, *metav1.NewDeleteOptions(1))
 			framework.ExpectNoError(err, "failed to delete pod")
 		})
 
 		ginkgo.It("should provide hostIPs as an env var", func(ctx context.Context) {
+			if !utilfeature.DefaultFeatureGate.Enabled(kubefeatures.PodHostIPs) {
+				e2eskipper.Skipf("PodHostIPs feature is not enabled")
```
Comment (aojea) [inline test/e2e_node/pod_host_ips.go:200]: at least in e2e this does not work as people think, @pacoxu is this valid in this case?

Comment (aojea) [reply test/e2e_node/pod_host_ips.go:200]: yeah, but `!utilfeature.DefaultFeatureGate.Enabled(kubefeatures.PodHostIPs) ` this only works on unit or integration tests that build the test and the code that exercise the test, in e2e you build an external binary that runs api calls against the code you want to test, so the featuregate utils here are not related, at least for the e2e that is not node, and I can't understand how this can work here

File: test/e2e_node/pod_host_ips.go [hunk 5]
```diff
@@ -158,41 +123,34 @@ var _ = common.SIGDescribe("Dual Stack Host IP [Feature:PodHostIPs]", func() {
...
+					}
+
+					want := sets.New[string]()
 					for _, address := range node.Status.Addresses {
 						if address.Type == v1.NodeInternalIP {
-							nodeIPs = append(nodeIPs, address.Address)
+							want.Insert(address.Address)
 						}
 					}
-					gomega.Expect(p.Status.HostIPs).Should(gomega.Equal(nodeIPs))
```
Comment (aojea) [inline test/e2e_node/pod_host_ips.go:167]: I think this is the problem expressed here https://github.com/kubernetes/kubernetes/commit/6d02fbdbe07422b1d48fc20dc4ba7d3f98603a95#r130786064

File: test/e2e_node/pod_host_ips.go (hunk 4 above)
Comment (wzshiming) [reply test/e2e_node/pod_host_ips.go:200]: https://github.com/kubernetes/kubernetes/blob/619be9c15372238edbb442e6b2ffd7a6cc827cfc/test/e2e_node/swap_test.go#L145-L148

https://github.com/kubernetes/kubernetes/blob/dd9c3358f5e99d4eb4f8a2d7dc77f59e896249e0/test/e2e_node/util.go#L526-L532

There are two other places in e2e_node that also use this

File: test/e2e_node/pod_host_ips.go (hunk 5 above)
Comment (wzshiming) [reply test/e2e_node/pod_host_ips.go:167]: Yeah, I don't remember why I wrote it that way, because in the alpha phase, the initial merge was a revert and then a merge over a bit of a long period of time, and I didn't realize that until I switched to the beta phase and ran the test this time.

**Comment by wzshiming** [comment]
@aojea

Is there anything else I need to do with this PR?

**Comment by pacoxu** [comment]
/remove-priority critical-urgent
as we reverted that one.

**Comment by aojea** [comment]
@wzshiming add a second commit enabling the feature so we exercise the tests in the CI
@pacoxu have you reviewed, I'm not that familiar with the e2e_node framework

File: test/e2e_node/pod_host_ips.go (hunk 4 above)
Comment (aojea) [reply test/e2e_node/pod_host_ips.go:200]: yeahm, but I don't know if those tests are correct either, it will be easy to verify by running the test manually,

**Comment by wzshiming** [comment]
> @wzshiming add a second commit enabling the feature so we exercise the tests in the CI 

I send a new for this test #121589

File: test/e2e_node/pod_host_ips.go (hunk 4 above)
Comment (pacoxu) [reply test/e2e_node/pod_host_ips.go:185]: Probably, we should add TODO item or track it somewhere.

**Review by pacoxu — APPROVED** [review]
/lgtm
/cc @SergeyKanzhelev @bart0sh 
/assign @mrunalp 

@iholder101  as you are working on something similar to make e2e can get the feature gate status of API server.

**Comment by aojea** [comment]
/approve

unhold once you verify the tests are good

**Comment by aojea** [comment]
hold cancel

is passing in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121589/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1718648979463344128
