### PR TITLE
fix(e2e): retry on conflict when deleting extended resource

### LINKED ISSUE #128911: [Flaking Test] SchedulerPreemption [Serial] validates pod disruption condition is added to the preempted pod [Conformance]
### Which jobs are flaking?

- ci-kubernetes-ec2-conformance-latest	
- e2e-ci-kubernetes-e2e-al2023-aws-conformance-cilium-canary
- ci-kubernetes-e2e-ec2-eks-al2023-serial	
- ci-kubernetes-ec2-conformance-latest

### Which tests are flaking?

[It] [sig-scheduling] SchedulerPreemption [Serial] validates pod disruption condition is added to the preempted pod [Conformance]

### Since when has it been flaking?

- Last Flake: [11/20/2024, 11:15:20 PM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ec2-eks-al2023-serial/1859359565544427520)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only&exclude-non-failed-tests=

### Reason for failure (if possible)

https://storage.googleapis.com/k8s-triage/index.html?test=%20validates%20pod%20disruption%20condition%20is%20added%20to%20the%20preempted%20pod

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

The test is flake with:
> [FAILED] Operation cannot be fulfilled on nodes "kind-worker": the object has been modified; please apply your changes to the latest version and try again
In [AfterEach] at: k8s.io/kubernetes/test/e2e/framework/node/helper.go:212 @ 11/16/24 06:17:12.464
https://storage.googleapis.com/k8s-triage/index.html?test=%20validates%20pod%20disruption%20condition%20is%20added%20to%20the%20preempted%20pod

Probably due to the recent refactoring: https://github.com/kubernetes/kubernetes/pull/128194/.

#### Which issue(s) this PR fixes:

Fixes #128911

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/framework/node/helper.go [hunk 1]
```diff
@@ -204,10 +205,15 @@ func RemoveExtendedResource(ctx context.Context, clientSet clientset.Interface,
 	extendedResource := v1.ResourceName(extendedResourceName)
 
 	ginkgo.By("Removing a custom resource")
-	node, err := clientSet.CoreV1().Nodes().Get(ctx, nodeName, metav1.GetOptions{})
-	framework.ExpectNoError(err)
-	delete(node.Status.Capacity, extendedResource)
-	delete(node.Status.Allocatable, extendedResource)
-	_, err = clientSet.CoreV1().Nodes().UpdateStatus(ctx, node, metav1.UpdateOptions{})
+	err := retry.RetryOnConflict(retry.DefaultBackoff, func() error {
```
Comment (AnishShah) [inline test/e2e/framework/node/helper.go:208]: No need to retry I think. You can just do patch with status subresource.

Comment (sanposhiho) [reply test/e2e/framework/node/helper.go:208]: But, you intentionally used the update, not patch, for ease here, right?
https://github.com/kubernetes/kubernetes/pull/128194#discussion_r1829913783

Comment (AnishShah) [reply test/e2e/framework/node/helper.go:208]: Yeah. I thought there won't be resource conflict and hence used UpdateStatus. We can revert to patch again to avoid doing retry.

Comment (sanposhiho) [reply test/e2e/framework/node/helper.go:208]: I meant, that was for the implementation simplicity, right?
I'm not sure why you prefer to switch back to the patch here. Efficiency-wise too, the flake is pretty rare, that is, the retry would happen only rarely, and I don't think we need to mind (... and this is a test code either way).

Comment (aojea) [reply test/e2e/framework/node/helper.go:208]: this is an e2e test so we don't need to over optimize, I think current approach is ok and avoids more code churn

Comment (AnishShah) [reply test/e2e/framework/node/helper.go:208]: > I meant, that was for the implementation simplicity, right? I'm not sure why you prefer to switch back to the patch here. Efficiency-wise too, the flake is pretty rare, that is, the retry would happen only rarely, and I don't think we need to mind (... and this is a test code either way).

patch requests avoid resource conflicts. so there won't be any need to retry and we can keep the logic similar to `AddExtendedResource` func above.

Comment (aojea) [reply test/e2e/framework/node/helper.go:208]: either way works for me, I also prefer to use patch if the patch is really simple ... I'm just trying to say we should not overthink it, chose one solution and move on , a retry on conflict is common in multiple places of the code, so is nota bad solution either

Comment (Huang-Wei) [reply test/e2e/framework/node/helper.go:208]: We need either retry on update, or simply patch. Reported by @wendy-ha18 we got flakes and it's impacting 1.32 release: https://kubernetes.slack.com/archives/C09TP78DV/p1733547680436909

Agree with @aojea we should move on either way. (we can follow-up with the approach of switching to patch)
