### PR TITLE
NodeController doesn't evict Pods if no Nodes are Ready

### LINKED ISSUE #13412: We should handle flaky cloud provider APIs more gracefully
From: jonathanbweeks@gmail.com
... we experienced a catastrophic failure this morning when our in-house OpenStack cloud team went to upgrade from Juno to Kilo, and the OpenStack API went away for a period. (We are running Kubernetes on top of Openstack for our internal private cloud.)

We are still trying to completely grok the sequence of events, but from logs and source code inspection (we are on K8s 1.0.1):

1. The kubelets on each node periodically poll the cloud provider API to get network/IP interface information. When the API went away, this update starting failing, causing them to be marked as "Not Ready" by the controller-manager. This would be bad, as it would lead to the scheduler obviously not being able to schedule pods on the affected nodes (eventually all nodes)

However, it is exacerbated by:

2. The controller-manager eventually then ends up evicting (AKA killing) all pods on every "NotReady" node after a timeout (which is quickly all nodes in the K8s cluster)

This means that the entire cluster basically offs itself in a misguided violent purge. (But no one ever expects the Spanish Inquisition).

This issue was at least partially captured today in the IRC, and a related issue logged here: https://github.com/kubernetes/kubernetes/issues/13398

Now clearly, Openstack should have an HA API and allow seamless rolling upgrades, but cloud providers will likely have occasional unplanned API downtime, and kubernetes needs to be more tolerant and robust in the face of that (at the very least, not kill all running pods :)

We looked at various timeout config settings, but there seemed to be non-trivial side-effects to setting them to "high" values (we continue to investigate this). As a workaround, we are patching our kubelet to keep posting status even if the cloud provider is unavailable and will submit a pull request.

### PR DESCRIPTION
**Pull request by gmarek**
Fix #13412 #24597

When NodeControllers don't see any Ready Node it goes into "network segmentation mode". In this mode it cancels all evictions and don't evict any Pods.

It leaves network segmentation mode when it sees at least one Ready Node. When leaving it resets all timers, so each Node has full grace period to reconnect to the cluster.

cc @lavalamp @davidopp @mml @wojtek-t @fgrzadkowski

### CODE REVIEW

**Comment by gmarek** [comment]
I think this is it. I want to run tests on real cluster, but I believe it's ready for review.

@lavalamp @davidopp

File: pkg/controller/node/rate_limited_queue.go [hunk 1]
```diff
@@ -63,6 +63,11 @@ type UniqueQueue struct {
 	set   sets.String
 }
 
+// Length returns a number of items currently in the queue
+func (q *UniqueQueue) Length() int {
```
Comment (lavalamp) [inline pkg/controller/node/rate_limited_queue.go]: looks unsafe re: locking. Please don't add this, esp don't make it public.

File: pkg/controller/node/rate_limited_queue.go [hunk 2]
```diff
@@ -199,3 +216,13 @@ func (q *RateLimitedTimedQueue) Add(value string) bool {
...
 	return q.queue.Remove(value)
 }
+
+// Removes all items from the queue
+func (q *RateLimitedTimedQueue) Clear() {
+	q.queue.Clear()
+}
+
+// Retruns a number of elements currently in the queue
+func (q *RateLimitedTimedQueue) Length() int {
```
Comment (lavalamp) [inline pkg/controller/node/rate_limited_queue.go]: Same. Unit test can just look directly at the private members.

**Comment by lavalamp** [comment]
looks OK to me.

File: pkg/controller/node/rate_limited_queue.go (hunk 1 above)
Comment (gmarek) [inline pkg/controller/node/rate_limited_queue.go]: Done.

File: pkg/controller/node/rate_limited_queue.go (hunk 2 above)
Comment (gmarek) [inline pkg/controller/node/rate_limited_queue.go]: Done.

**Comment by lavalamp** [comment]
Ping me when you get tests working. :)

**Comment by davidopp** [comment]
@lavalamp tests are passing now
(I didn't review the PR, just saw your comment)

**Comment by gmarek** [comment]
I guess that @lavalamp meant the tests I mentioned in previous comment. There's no e2e tests for this and I didn't have time to write those. I'll hand test it today and add tests sometime next week.

**Comment by gmarek** [comment]
@lavalamp I run manual tests and it seems to work now (I had a bug - now I skip master node when looking for Ready Nodes).

**Comment by lavalamp** [comment]
Can you exercise your bugfix in the unit test? then LGTM.

**Comment by gmarek** [comment]
There is a unit test for this - the last case I added checks exactly this.

**Comment by gmarek** [comment]
@k8s-bot test this issue: #IGNORE
yesterday's jenkins problems

**Comment by lavalamp** [comment]
Sorry, maybe I'm blind, but I can't see a test case with a node having a name ending in "-master"?

**Comment by gmarek** [comment]
Oh, sorry - the master thing. I miss-read your comment.

**Comment by gmarek** [comment]
@lavalamp PTAL

**Comment by lavalamp** [comment]
LGTM!

**Comment by gmarek** [comment]
It's pretty high in the queue, but we might need to merge it by hand if it won't make it until tomorrow.

**Comment by pesho** [comment]
This looks like it might also resolve the scenario described in #19124. Will it be backported to 1.2 as well?

**Comment by davidopp** [comment]
@pesho No. But 1.3 should be out relatively soon (less than a month).

**Comment by manojlds** [comment]
I am seeing this error in the kubelet logs:

```
E0930 18:21:12.386245    2565 kubelet.go:2913] Error updating node status, will retry: failed to get node address from cloud provider: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/local-ipv4: dial tcp 169.254.169.254:80: getsockopt: no route to host
```

All pods in the node were rescheduled to other nodes. Is this how this is supposed to behave? Also, did it reschedule without doing few retries at the least?

**Comment by gmarek** [comment]
@manojlds - yes it is is as expected, and NC does a number of retries before it evicts Pods (by default 30 times, but it depends on how often NodeStatus is reported, and what are the settings for PodEvictionGracePeriod). From what you wrote there were other Nodes that were serving, so the behavior seems to be correct, or did you expect something else?

This log line suggests that the cloud provider became unreachable from some of your Nodes. @yujuhong

**Comment by manojlds** [comment]
@gmarek - thanks. This is the only instance of the error I could see in the log, so not sure if it did retry before actually evicting the pods. The behaviour seems fine, only doubt/question is on the retry.

**Comment by gmarek** [comment]
Even if the kubelet does not retry it's fine, as NC requires a lot of failed NodeStatus updates to actually start doing something.

For kubelet-side of this @yujuhong should be able to answer/point you to someone who can.

**Comment by yujuhong** [comment]
Kubelet should retry up to 5 times by default. On top of that, kubelet tries to update the node status every 10s (or a customized period passed by flags/configs), and node controller only reacts in O(min). One failed attempt should not cause any serious reactions.

**Comment by manojlds** [comment]
@yujuhong thanks. Will take a look at the flags, and see how best I can use them in my cluster.
