### PR TITLE
Fix StatefulSet set-based selector bug

### LINKED ISSUE #59266: set-based selectors are broken in statefulsets
If a set-based (new type) selector is used with statefulsets, the statefulset breaks and never starts a pod. The reason is [this](https://github.com/kubernetes/apimachinery/blob/bfe7139b14565386b4470736ca765bf21616b60e/pkg/labels/labels.go#L157) selector conversion helper.

Reproduce with:
```yaml
$ cat grin.yaml
apiVersion: v1
kind: Service
metadata:
  name: grin
  labels:
    app: grin
spec:
  ports:
  - port: 13413
    targetPort: 13413
    name: http
  - port: 13414
    targetPort: 13414
    name: p2p
  clusterIP: None
  selector:
    app: grin
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: grin
spec:
  serviceName: grin
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchExpressions:
      - {key: app, operator: In, values: [grin]}
  template:
    metadata:
      labels:
        app: grin
    spec:
      containers:
      - image: quay.io/kargakis/grin:0.1
        name: grin
        command:
        - grin
        - server
        - run
        ports:
        - containerPort: 13413
          name: http
        - containerPort: 13414
          name: p2p
```
```console
$ kc create -f grin.yaml
service "grin-public" created
service "grin" created
statefulset "grin" created
$ kc get sts
NAME      AGE
grin      1h
$ kc get controllerrevision
No resources found.
$ kc get po
No resources found.
```
Controller manager logs:
```console
E0202 13:02:28.502538   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:28.663007   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:28.983965   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:29.624798   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:30.905600   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:33.466074   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
E0202 13:02:37.382397   26447 stateful_set.go:399] Error syncing StatefulSet default/grin, requeuing: invalid selector: [app in (grin)]
```
```console
$ kc version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.1.245+dddee913926377-dirty", GitCommit:"dddee9139263775670d3ed94b788c8abc06d5c2b", GitTreeState:"dirty", BuildDate:"2018-01-24T12:16:32Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
@kubernetes/sig-apps-bugs

### PR DESCRIPTION
**Pull request by ayushpateria**
**What this PR does / why we need it**:
ControllerRevisions were using selectors as the labels, in case of set-based selectors, the helper function to convert selectors to labels would break. This PR uses pod labels for ControllerRevision labels instead of selectors.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59266

**Special notes for your reviewer**:
I'm trying to learn Kubernetes codebase and would be happy to make changes if anything is off.
**Release note**:

```release-note
Fix StatefulSet to work with set-based selectors.
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Please add a test :)

File: pkg/controller/history/controller_history.go [hunk 1]
```diff
@@ -454,3 +452,31 @@ func (fh *fakeHistory) ReleaseControllerRevision(parent metav1.Object, revision
 	}
 	return clone, fh.indexer.Update(clone)
 }
+
+func getPodLabelsFromData(data runtime.RawExtension) map[string]string {
+	var dat map[string]interface{}
+	labelMap := make(map[string]string)
+	if err := json.Unmarshal(data.Raw, &dat); err != nil {
```
Comment (cheftako) [inline pkg/controller/history/controller_history.go]: How do we know that the raw extension will always be json and not say protobuf?

File: pkg/controller/history/controller_history.go [hunk 2]
```diff
@@ -454,3 +452,31 @@ func (fh *fakeHistory) ReleaseControllerRevision(parent metav1.Object, revision
...
+		return labelMap
```
Comment (cheftako) [inline pkg/controller/history/controller_history.go]: If the raw data does not parse we should not be silently swallowing that error.

File: pkg/controller/history/controller_history.go [hunk 3]
```diff
@@ -454,3 +452,31 @@ func (fh *fakeHistory) ReleaseControllerRevision(parent metav1.Object, revision
...
+	metadata, ok := template["metadata"].(map[string]interface{})
+	if !ok {
+		return labelMap
+	}
+	labels, ok := metadata["labels"].(map[string]interface{})
+	if !ok {
+		return labelMap
+	}
+	for key, value := range labels {
+		labelMap[key] = value.(string)
```
Comment (cheftako) [inline pkg/controller/history/controller_history.go]: We should make sure to validate both the key and value to make sure they are valid label key and label values.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-pr-reviews

File: pkg/controller/history/controller_history.go (hunk 2 above)
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: Will a warning in log work? I didn't want it to break like previously if the problem is only with parsing of labels, as they aren't being used anywhere anyway.

File: pkg/controller/history/controller_history.go (hunk 3 above)
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: Are we required to validate key and values again? Because they must have already been validated when creating the StatefulSet (or pods).

File: pkg/controller/history/controller_history.go [hunk 4]
```diff
@@ -66,10 +67,7 @@ func NewControllerRevision(parent metav1.Object,
 	data runtime.RawExtension,
 	revision int64,
 	collisionCount *int32) (*apps.ControllerRevision, error) {
-	labelMap, err := labels.ConvertSelectorToLabelsMap(selector.String())
-	if err != nil {
-		return nil, err
-	}
+	labelMap := getPodLabelsFromData(data)
```
Comment (enisoc) [inline pkg/controller/history/controller_history.go]: I think we should require the caller of `NewControllerRevision` to provide the labels, rather than making assumptions about the contents of `data`.

cc @kow3ns @janetkuo

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 5]
```diff
@@ -316,8 +316,10 @@ func newRevision(set *apps.StatefulSet, revision int64, collisionCount *int32) (
 	if err != nil {
 		return nil, err
 	}
+	podLabels := set.Spec.Template.Labels
```
Comment (ayushpateria) [inline pkg/controller/statefulset/stateful_set_utils.go]: Can this ever be nil?

File: pkg/controller/history/controller_history.go (hunk 4 above)
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: Please check :)

File: pkg/controller/history/controller_history.go (hunk 1 above)
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: @cheftako Please have a look at my recent commit :)

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 6]
```diff
@@ -316,8 +316,13 @@ func newRevision(set *apps.StatefulSet, revision int64, collisionCount *int32) (
...
+	if podLabels == nil {
```
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set_utils.go]: podLabels should never be nil

- The statefulset selector is required to be [non-empty](https://github.com/kubernetes/kubernetes/blob/05944b1d2ca7f60b09762a330425108f48f6b603/pkg/apis/apps/validation/validation.go#L106-L113)
- [The podtemplate labels are required to match the selector](https://github.com/kubernetes/kubernetes/blob/05944b1d2ca7f60b09762a330425108f48f6b603/pkg/apis/apps/validation/validation.go#L50-L53).

Comment (ayushpateria) [reply pkg/controller/statefulset/stateful_set_utils.go]: I had this doubt, did the check anyway to be on safer side. Removed the check now. Please see the recent commit.

**Comment by kargakis** [comment]
lgtm

also needs a unit test that uses a set-based selector

**Comment by ayushpateria** [comment]
@kargakis I've modified newStatefulSet() to include a set based selector, this should ensure controller revisions don't fail when stateful sets are having set-based selectors.

File: pkg/controller/history/controller_history_test.go [hunk 7]
```diff
@@ -1633,22 +1539,17 @@ func TestSortControllerRevisions(t *testing.T) {
...
 	}
 	ss1Rev1.Namespace = ss1.Namespace
-	ss1Rev2, err := NewControllerRevision(ss1, parentKind, sel1, rawTemplate(&ss1.Spec.Template), 2, ss1.Status.CollisionCount)
+	ss1Rev2, err := NewControllerRevision(ss1, parentKind, ss1.Spec.Template.Labels, rawTemplate(&ss1.Spec.Template), 2, ss1.Status.CollisionCount)
 	if err != nil {
 		t.Fatal(err)
 	}
 	ss1Rev2.Namespace = ss1.Namespace
-	ss1Rev3, err := NewControllerRevision(ss1, parentKind, sel1, rawTemplate(&ss1.Spec.Template), 2, ss1.Status.CollisionCount)
+	ss1Rev3, err := NewControllerRevision(ss1, parentKind, ss1.Spec.Template.Labels, rawTemplate(&ss1.Spec.Template), 3, ss1.Status.CollisionCount)
```
Comment (ayushpateria) [inline pkg/controller/history/controller_history_test.go]: TestSortControllerRevisions was failing because of the incorrect version number (2 was being used for ss1Rev3).

**Comment by ayushpateria** [comment]
Why is `pull-kubernetes-bazel-test` failing? Is it a flake?

**Comment by janetkuo** [comment]
The failure looks relevant to the change made in this PR.

```
//pkg/controller/statefulset:go_default_test 0.00s
bazel test //pkg/controller/statefulset:go_default_test
E0219 23:03:17.207307      14 stateful_pod_control.go:125] error getting updated Pod default/foo-0 from lister: pod "foo-0" not found
Terminated
```

File: pkg/controller/history/controller_history.go [hunk 8]
```diff
@@ -56,20 +56,17 @@ func ControllerRevisionName(prefix string, hash uint32) string {
...
-	selector labels.Selector,
+	podLabels map[string]string,
 	data runtime.RawExtension,
 	revision int64,
 	collisionCount *int32) (*apps.ControllerRevision, error) {
-	labelMap, err := labels.ConvertSelectorToLabelsMap(selector.String())
-	if err != nil {
-		return nil, err
-	}
+	labelMap := podLabels
```
Comment (janetkuo) [inline pkg/controller/history/controller_history.go]: Need to make a copy here; otherwise, `podLabels` gets mutated when `cr.Labels` is mutated in L91.

File: pkg/controller/history/controller_history.go [hunk 9]
```diff
@@ -56,20 +56,17 @@ func ControllerRevisionName(prefix string, hash uint32) string {
 }
 
 // NewControllerRevision returns a ControllerRevision with a ControllerRef pointing to parent and indicating that
-// parent is of parentKind. The ControllerRevision has labels matching selector, contains Data equal to data, and
+// parent is of parentKind. The ControllerRevision has labels matching pod, contains Data equal to data, and
```
Comment (janetkuo) [inline pkg/controller/history/controller_history.go]: CR's labels is a copy of template labels. Matching is between selector and labels.

File: pkg/controller/history/controller_history.go [hunk 10]
```diff
@@ -56,20 +56,17 @@ func ControllerRevisionName(prefix string, hash uint32) string {
...
 // has a Revision equal to revision. The collisionCount is used when creating the name of the ControllerRevision
 // so the name is likely unique. If the returned error is nil, the returned ControllerRevision is valid. If the
 // returned error is not nil, the returned ControllerRevision is invalid for use.
 func NewControllerRevision(parent metav1.Object,
 	parentKind schema.GroupVersionKind,
-	selector labels.Selector,
+	podLabels map[string]string,
```
Comment (janetkuo) [inline pkg/controller/history/controller_history.go]: Name it `templateLabels`

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 11]
```diff
@@ -312,13 +312,10 @@ func newRevision(set *apps.StatefulSet, revision int64, collisionCount *int32) (
...
 	}
-	selector, err := metav1.LabelSelectorAsSelector(set.Spec.Selector)
-	if err != nil {
-		return nil, err
-	}
+	podLabels := set.Spec.Template.Labels
 	cr, err := history.NewControllerRevision(set,
 		controllerKind,
-		selector,
+		podLabels,
```
Comment (janetkuo) [inline pkg/controller/statefulset/stateful_set_utils.go]: `templateLabels`

**Review by janetkuo — CHANGES_REQUESTED** [review]

File: pkg/controller/history/controller_history_test.go [hunk 12]
```diff
@@ -178,30 +172,23 @@ func TestFakeHistory_ListControllerRevisions(t *testing.T) {
...
-	sel1, err := metav1.LabelSelectorAsSelector(ss1.Spec.Selector)
-	if err != nil {
-		t.Fatal(err)
-	}
-	sel2, err := metav1.LabelSelectorAsSelector(ss2.Spec.Selector)
-	if err != nil {
-		t.Fatal(err)
-	}
-	ss1Rev1, err := NewControllerRevision(ss1, parentKind, sel1, rawTemplate(&ss1.Spec.Template), 1, nil)
+	sel1 := labels.Set(ss1.Spec.Template.Labels).AsSelector()
```
Comment (enisoc) [inline pkg/controller/history/controller_history_test.go]: Same here.

File: pkg/controller/history/controller_history_test.go [hunk 13]
```diff
@@ -1695,6 +1604,13 @@ func newStatefulSet(replicas int, name string, uid types.UID, labels map[string]
 		Spec: apps.StatefulSetSpec{
 			Selector: &metav1.LabelSelector{
 				MatchLabels: labels,
+				MatchExpressions: []metav1.LabelSelectorRequirement{
```
Comment (enisoc) [inline pkg/controller/history/controller_history_test.go]: I agree that this change to the test would have prevented the exact manifestation of the bug we hit (converting a new-style, set-based selector into a string and then trying to parse it as an old-style, map-only selector). However, there are other possible manifestations of the general problem (forgetting about set-based selectors) that this test won't prevent in the future. For example, if we regress to pulling the labels from `MatchLabels` without converting via string format/parse, this test won't catch that.

I think we'll catch more potential regressions if we include test cases with no MatchLabels at all, so we're sure it will break if any link in the chain ignores the set-based MatchExpressions. We could do that by converting all entries in `labels` into MatchExpressions (instead of just the first pair), and leaving MatchLabels empty.

Also, we should leave a comment here saying that we are intentionally using a selector with empty MatchLabels to make sure MatchExpressions works as expected, to reduce the chance that someone will weaken our test in the future.

File: pkg/controller/statefulset/stateful_set_utils.go (hunk 11 above)
Comment (enisoc) [inline pkg/controller/statefulset/stateful_set_utils.go]: You can directly put `set.Spec.Template.Labels` here.

**Review by enisoc — CHANGES_REQUESTED** [review]

File: pkg/controller/history/controller_history.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: `podLabels` is not being used anywhere later, I agree with what you struck out. Am I missing something?

Comment (janetkuo) [reply pkg/controller/history/controller_history.go]: And this means template labels (of the given StatefulSet) gets mutated.

[the remark this answers is not in the document]
Comment (enisoc) [reply pkg/controller/history/controller_history.go]: @janetkuo pointed out in the other thread that we mutate this map below on this line:

```go
cr.Labels[ControllerRevisionHashLabel] = strconv.FormatInt(int64(hash), 10)
```

Since map types are references, this means we're mutating the map that the caller passed in to us. So it turns out we do need to make our own `labelMap` var after all, to hold a deep copy of `podLabels`. Unless you can find a utility helper for this, you'll need to just allocate a new map and then range loop over the input map to copy each entry.

[the remark this answers is not in the document]
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: Okay, I was thinking that even if it gets mutated it's not affecting anything. But yeah, we should not mutate anything that caller passes.

[the remark this answers is not in the document]
Comment (janetkuo) [reply pkg/controller/history/controller_history.go]: > it's not affecting anything

It actually mutates template labels (`set.Spec.Template.Labels`) the caller passes.

File: pkg/controller/history/controller_history_test.go [hunk 14]
```diff
@@ -77,30 +77,24 @@ func TestRealHistory_ListControllerRevisions(t *testing.T) {
...
-	sel1, err := metav1.LabelSelectorAsSelector(ss1.Spec.Selector)
-	if err != nil {
-		t.Fatal(err)
-	}
-	sel2, err := metav1.LabelSelectorAsSelector(ss2.Spec.Selector)
-	if err != nil {
-		t.Fatal(err)
-	}
-	ss1Rev1, err := NewControllerRevision(ss1, parentKind, sel1, rawTemplate(&ss1.Spec.Template), 1, nil)
+	sel1 := labels.Set(ss1.Spec.Template.Labels).AsSelector()
```
[the remark this answers is not in the document]
Comment (enisoc) [reply pkg/controller/history/controller_history_test.go]: It's always safe to use the StatefulSet's selector, because we ensure through validation that it selects the pod template labels. Since we now apply the pod template labels to revisions too, we can also expect that the StatefulSet's selector will match those revisions.

On the other hand, generating a selector purely from the template labels will not always give the right result. Here is a contrived example of that:

```yaml
...
metadata:
  name: ss1
spec:
  selector:
    matchLabels:
      component: mything
    matchExpressions:
    - {key: role, operator: DoesNotExist}
  template:
    metadata:
      labels:
        component: mything
...
---
...
metadata:
  name: ss2
spec:
  selector:
    matchLabels:
      component: mything
      role: test
  template:
    metadata:
      labels:
        component: mything
        role: test
```

If you generate a selector directly from the pod template labels, ss1 would end up also selecting ss2's revisions, whereas ss1's actual selector means that it will avoid selecting ss2's pods. We want the behavior for selecting pods and revisions to be consistent with each other, so we respect the user's intention.

I called this example contrived because it's probably a bad idea for the user to do this. However, the API allows it, so we need to make sure we do the right thing.

File: pkg/controller/history/controller_history.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (ayushpateria) [reply pkg/controller/history/controller_history.go]: Got it. Thanks.

File: pkg/controller/statefulset/stateful_set_utils.go (hunk 11 above)
Comment (ayushpateria) [reply pkg/controller/statefulset/stateful_set_utils.go]: @enisoc Updated! :)

File: pkg/controller/history/controller_history_test.go (hunk 13 above)
Comment (ayushpateria) [reply pkg/controller/history/controller_history_test.go]: @enisoc Updated! :)

**Review by janetkuo — APPROVED** [review]

**Review by enisoc — APPROVED** [review]
/lgtm

**Comment by enisoc** [comment]
The `verify` failure looks like #60447. Looks like `e2e-gce` didn't even run.

/test pull-kubernetes-e2e-gce

**Comment by BenTheElder** [comment]
fix PR for verify merged
/test pull-kubernetes-verify

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 15]
```diff
@@ -312,13 +312,9 @@ func newRevision(set *apps.StatefulSet, revision int64, collisionCount *int32) (
...
 		return nil, err
 	}
-	selector, err := metav1.LabelSelectorAsSelector(set.Spec.Selector)
-	if err != nil {
-		return nil, err
-	}
 	cr, err := history.NewControllerRevision(set,
 		controllerKind,
-		selector,
+		set.Spec.Template.Labels,
```
Comment (lavalamp) [inline pkg/controller/statefulset/stateful_set_utils.go]: What happens if the selector doesn't match these labels?

Comment (janetkuo) [reply pkg/controller/statefulset/stateful_set_utils.go]: Validation prevents a StatefulSet with a selector that doesn't match its own template labels from being created. apps/v1 StatefulSet's selector cannot be changed after creation.

Comment (lavalamp) [reply pkg/controller/statefulset/stateful_set_utils.go]: Thanks!
