### PR TITLE
Fix for HNS local endpoint was being deleted instead of the remote endpoint.

### LINKED ISSUE #130963: [Windows] HNS endpoints creation fails after remote HNS endpoints with same IP address were created
### What happened?

When deploying Windows containers on Windows Nodes, some Windows containers fails to have network configuration inside like this:
```
S C:\> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : windows-server-iis-ltsc2022-58467d4759-vgzjr
   Primary Dns Suffix  . . . . . . . : 
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
```

This issue happens for Windows containers that got assigned the same IP address that was previously assigned to pods on Linux but were deleted later.

When we create a Pod on Linux and a `LoadBalancer` service type that refers to Linux pod, `kube-proxy` on Windows create HNS endpoints of Remote type. If we delete these Linux pods, IP addresses assigned to these pods are released and Remote HNS endpoints are deleted from Windows nodes.

When I deploy Windows pod, and if this Windows pod gets assigned the same IP as Linux pod, HNS endpoint for these Windows containers fails to be created causing networking issues inside Windows container.

This issue is a likely regression due to #124092

### What did you expect to happen?

All Windows containers should successfully create HNS endpoint and networking should work inside Windows containers.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy kubernetes cluster with limited available IPs for pods on both Linux and Windows node.
2. Deploy Linux pods that consume almost all IPs.
3. Deploy service type LoadBalancer that refer to Linux pods, This will trigger `kube-proxy` to create Remote HNS endpoint on Windows. This Remote HNS endpoint will have Linux pod IP.
4. Scale down the Linux pods to 1.
5. Deploy Windows pods so that same IP address from Linux pod can be reassigned to Windows Pods.
6. HNS endpoints for Windows pods with same address will not be created.
7. Internet connectivity inside these Windows pod will fail.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
1.31 and higher only
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture

BuildNumber  Caption                                   OSArchitecture  Version
20348        Microsoft Windows Server 2022 Datacenter  64-bit          10.0.20348
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by princepereira**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The queriedEndpoints map keeps track of HNS endpoint information for Windows nodes. If two endpoints (one remote and one local) share the same IP within the Windows nodes, the second entry will overwrite the first in the map since the IP address serves as the key. If, unfortunately, the second endpoint happens to be a local one, any attempt by the proxier code to retrieve the remote endpoint for deletion will instead fetch the local endpoint, leading to its unintended removal.

The update ensures that when two endpoints with the same IP exist on a Windows node, the remote endpoint always takes precedence. This map is exclusively used for endpoint deletion, and since kube-proxy is primarily concerned with remote endpoints, local endpoint information holds little significance in this context.

#### Which issue(s) this PR fixes:
Fixes #130963

#### Does this PR introduce a user-facing change?

```release-note
Resolve a regression introduced in version 1.31 on Windows Proxy, where the creation of HNS endpoints fails if remote HNS endpoints with the same IP address have already been created.

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/winkernel/hns.go [hunk 1]
```diff
@@ -147,26 +147,21 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
...
-		endpointInfos[ep.IpConfigurations[0].IpAddress] = endpointInfos[ep.Id]
 
-		if len(ep.IpConfigurations) == 1 {
-			continue
-		}
+		endpointInfos[ep.Id] = epInfo
 
-		// If ipFamilyPolicy is RequireDualStack or PreferDualStack, then there will be 2 IPS (iPV4 and IPV6)
-		// in the endpoint list
-		endpointDualstack := &endpointInfo{
```
Comment (daschott) [inline pkg/proxy/winkernel/hns.go:158]: Any reason we no longer need to store dual stack IP address in the endpoint info?

**Comment by KlwntSingh** [comment]
I tested the PR. It works. I tested the patch with k8s `1.31`.
FYI, I tested the following test cases:
1. Verify remote endpoints get cleaned up after deleting Linux pods. [pass]
2. Verify No network issue on Windows pods with same IP as remote endpoints after their deletion. [pass]
3. Verify Local endpoints gets deleted after deleting windows pods. [pass]
4. Verify Remote endpoints with the same on IP local endpoints gets created after deleting local endpoints. [pass]

File: pkg/proxy/winkernel/hns.go (hunk 1 above)
Comment (princepereira) [reply pkg/proxy/winkernel/hns.go:158]: We need dualstack information too. Instead of specifying the index, will iterate through the ep.IpConfigurations array to access dualstack info. In previous commit, I missed to keep epInfo construction part of the loop. I have added it now.

**Comment by princepereira** [comment]
I have simulated (since the actual repro was not happening for me) the scenarios using following steps:

- Created a linux pod deployment
- Picked a linux pod ip which will be remote endpoint in Windows nodes.
- Created local endpoint in Windows nodes with same ip using powershell scripts. Now we have a local endpoint and a remote endpoint with the same ip in the node.
- Then deleted the linux pod with the selected ip.
- This should delete the remote endpoint from Windows Node. But before the fix, it was deleting powershell created local endpoint. But with the fix, it's deleting remote endpoint.

**Comment by princepereira** [comment]
Gentle reminder
/cc @sbangari , @daschott , @jsturtevant , @marosset , @dims

File: pkg/proxy/winkernel/hns.go [hunk 2]
```diff
@@ -133,40 +133,38 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
...
-		endpointInfos[ep.IpConfigurations[0].IpAddress] = endpointInfos[ep.Id]
+		for index, ipConfig := range ep.IpConfigurations {
 
-		if len(ep.IpConfigurations) == 1 {
-			continue
-		}
+			if index > 1 {
+				// Expecting only ipv4 and ipv6 ipaddresses
+				break
+			}
```
Comment (jsturtevant) [inline pkg/proxy/winkernel/hns.go:141]: what is the scenario where the index would be greater than 1?  Should this be a hard error or atleast a log warning?

File: pkg/proxy/winkernel/hns.go [hunk 3]
```diff
@@ -133,40 +133,38 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
...
-			serving:     true,
-			terminating: false,
+			if _, ok := endpointInfos[ipConfig.IpAddress]; ok && isLocal {
+				// If the endpoint is already part of the queried endpoints map and is local,
+				// then we should not add it again to the map
+				continue
+			}
+
+			// Add to map with key endpoint ID or IP address
+			// Storing this is expensive in terms of memory, however there is a bug in Windows Server 2019 that can cause two endpoints to be created with the same IP address.
```
Comment (sbangari) [inline pkg/proxy/winkernel/hns.go:152]: Is this behavior only specific to WS2019? Did we verify that this isn't the case for WS2022 and beyond?

Comment (princepereira) [reply pkg/proxy/winkernel/hns.go]: It occurs in 2022 as well. Modified the comment.

File: pkg/proxy/winkernel/hns.go (hunk 2 above)
Comment (princepereira) [reply pkg/proxy/winkernel/hns.go]: This scenario is highly unlikely, but in the event of garbage values or issues with underlying components (e.g., HNS), this will aid in root cause analysis.

Warning logs added.

**Comment by princepereira** [comment]
@jsturtevant ,

All checks have passed, but the PR is stuck at the Tide check with the message: [Waiting for status to be reported — Not mergeable. Must be in milestone v1.33]. Could you help me get it merged?

**Comment by princepereira** [comment]
@jsturtevant , is there a lockdown of the branch going on? There is a tide checking blocking my pr.

**Comment by marosset** [comment]
> @jsturtevant , is there a lockdown of the branch going on? There is a tide checking blocking my pr.

Yes, code freeze for 1.33 was put into effect on March 20th.
The freeze should be lifted after the release (which is scheduled for April 23rd)

https://github.com/kubernetes/sig-release/tree/master/releases/release-1.33#summary

**Comment by princepereira** [comment]
> > @jsturtevant , is there a lockdown of the branch going on? There is a tide checking blocking my pr.
> 
> Yes, code freeze for 1.33 was put into effect on March 20th. The freeze should be lifted after the release (which is scheduled for April 23rd)
> 
> https://github.com/kubernetes/sig-release/tree/master/releases/release-1.33#summary

@marosset , Thanks for the info!

**Comment by KlwntSingh** [comment]
Thanks @princepereira for cherry picking it into older k8s versions.
