### PR TITLE
Remove dead pods upon stopping a job

### LINKED ISSUE #16255: [infrastructure_public_197]Delete a Job can't cleanup the completed pods it created
Description of problem:
As the [job doc](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/jobs.md#what-is-a-job) description "Deleting a Job will cleanup the pods it created."
Now when delete a job, the completed pod it created still exist.
```
Version-Release number of selected component (if applicable):
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.320+0884214fe040e2", GitCommit:"0884214fe040e2824e9710b0a1154705122be413", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.320+0884214fe040e2", GitCommit:"0884214fe040e2824e9710b0a1154705122be413", GitTreeState:"clean"}

How reproducible:
Always

Steps to Reproduce:
1.Create a job
[root@ip-172-18-12-52 kubernetes]# cat job.yaml
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: pi
spec:
  completions: 5
  selector:
    matchLabels:
      app: pi
  template:
    metadata:
      name: pi
      labels:
        app: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
[root@ip-172-18-12-52 kubernetes]# kubectl create -f job.yaml 
job "pi" created

2.Wait the pod to be Completed
[root@ip-172-18-12-52 kubernetes]# kubectl get job
JOB       CONTAINER(S)   IMAGE(S)   SELECTOR      SUCCESSFUL
pi        pi             perl       app in (pi)   5
[root@ip-172-18-12-52 kubernetes]# kubectl get pod
NAME       READY     STATUS      RESTARTS   AGE
pi-4136c   0/1       Completed   0          4m
pi-9wwlv   0/1       Completed   0          4m
pi-e83ai   0/1       Completed   0          4m
pi-j2uxa   0/1       Completed   0          4m
pi-nnp03   0/1       Completed   0          4m

3.Delete the job
[root@ip-172-18-12-52 kubernetes]# kubectl delete job/pi
job "pi" deleted

4.Check the pod
[root@ip-172-18-12-52 kubernetes]# kubectl get pod
NAME       READY     STATUS      RESTARTS   AGE
pi-4136c   0/1       Completed   0          5m
pi-9wwlv   0/1       Completed   0          5m
pi-e83ai   0/1       Completed   0          5m
pi-j2uxa   0/1       Completed   0          5m
pi-nnp03   0/1       Completed   0          5m

Actual results:
4.The related pods still exist.

Expected results:
4.When delete job the pod should be cleanup.

Additional info:
```

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #16255.
I've pods removal logic before removing a job.
@erictune @davidopp ptal.

This should be cherry-picked into 1.1, if possible.

### CODE REVIEW

**Comment by davidopp** [comment]
@mikedanese

**Comment by davidopp** [comment]
How is this different from the call to DeletePod() here
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/controller.go#L389
which should be triggered by scaling down to zero already?

**Comment by soltysh** [comment]
This will only deal with active pods, where there are also completed/failed pods that are not handled by the controller.

**Comment by bgrant0607** [comment]
Thanks. The other option would be to let the pod garbage collector clean them up, but I think this is more intuitive. We should probably do the same for ReplicationController.

**Comment by soltysh** [comment]
Yeah, I wanted to check how RC will react for such situation but failed. I'll try to have a closer look once again and prepare necessary PR.

**Comment by bgrant0607** [comment]
@soltysh Let's not change RC now, at least not for 1.1.

File: pkg/kubectl/stop.go [hunk 1]
```diff
@@ -241,6 +243,18 @@ func (reaper *JobReaper) Stop(namespace, name string, timeout time.Duration, gra
...
 	}
+	// at this point only dead pods are left, that should be removed
+	selector, _ := extensions.PodSelectorAsSelector(job.Spec.Selector)
+	podList, err := pods.List(selector, fields.Everything())
+	if err != nil {
+		return "", err
+	}
+	for _, pod := range podList.Items {
+		if err := pods.Delete(pod.Name, gracePeriod); err != nil {
+			return "", err
```
Comment (bgrant0607) [inline pkg/kubectl/stop.go]: This is also what rolling update does (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/rolling_updater.go#L684). It's fine for now, but it would probably be better to try deleting all the pods and return all the errors using an aggregate error (https://github.com/kubernetes/kubernetes/blob/master/pkg/util/errors/errors.go).

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

File: pkg/kubectl/stop.go (hunk 1 above)
Comment (soltysh) [inline pkg/kubectl/stop.go]: Yeah, I was thinking about it as well. If you want me it can be fixed withing the next couple of minutes.

Comment (bgrant0607) [inline pkg/kubectl/stop.go]: Would the caller DTRT with an aggregate error? If so, it would be desirable. Thanks.

**Comment by soltysh** [comment]
@bgrant0607 done

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

**Comment by bgrant0607** [comment]
LGTM

**Comment by davidopp** [comment]
LGTM

Thanks for fixing!

**Comment by erictune** [comment]
Thanks!

**Comment by bgrant0607** [comment]
Has anyone cherrypicked this into 1.1?

**Comment by davidopp** [comment]
Not yet.

**Comment by davidopp** [comment]
I'm working on it now.
