### PR TITLE
DRA: call plugins for claims even if exist in cache

### LINKED ISSUE #119850: dynamic-resource-allocation: PrepareResource won't be called on node reboot
### What happened?

We have k8s cluster with  Scalable function DRA driver deployed. 
We created Pod with resource claim to allocate Scalable function to Pod. 
When reboot the worker node the Pod with with Scalable function  failed to start with error [1].
The reason for the error is that PrepareResource is not called after reboot so we didn't create Scalable function  resource and prepare CDI file for it. 

[1] - Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873380    1851 remote_runtime.go:302] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3" podSandboxID="5ce2a000bf64e9b7d9570a95e53718f9369376b866b22fbbeed22f8faca2c88b"
Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873586    1851 kuberuntime_manager.go:1212] container &Container{Name:ctr,Image:docker.io/busybox,Command:[sleep 10000],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{ResourceClaim{Name:sf,},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-5cs79,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},} start failed in pod test-pod_default(64de5407-6ae7-47b7-9229-1ab750117a38): CreateContainerError: failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3
Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873711    1851 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"ctr\" with CreateContainerError: \"failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3\"" pod="default/test-pod" podUID=64de5407-6ae7-47b7-9229-1ab750117a38
Aug 09 09:58:59 cloud-dev-44 kubelet[1851]: I0809 09:58:59.891666    1851 scope.go:115] "RemoveContainer" containerID="11c40dace1080ff80bdc6695312d911536e1c3ca6c1844b38f6ba358ad8823da"

### What did you expect to happen?

The Pod should be in Running state

### How can we reproduce it (as minimally and precisely as possible)?

k8s v1.27.2
Scalable function DRA driver deployed
Create Pod with DRA Scalable function resource
reboot the worker node where the Pod runs

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
root@cloud-dev-44:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
SUPPORT_URL="[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
BUG_REPORT_URL="[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
PRIVACY_POLICY_URL="[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
 uname -a
Linux cloud-dev-44 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by adrianchiris**
Initial PR to gather Feedback if the proposed approach for fixing #119850 is acceptable or a different approach is required.
See [Alternatives](#alternatives) section for a different approach.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Today, DRA manager does not call plugin NodePrepareResource
for claims that it previously successfully handled, that is,
if claims are present in cache (checkpoint) even if node
rebooted.

After node reboots, it is required to call DRA plugin
for resource claims so that plugins may prepare them
again in case the resources dont persist reboot.

To achieve that, once kubelet is started, we call DRA
plugins for claims once if a pod sandbox is required
to be created during PodSync.

##### DRA Manager NodePrepareResource  in different scenarios:

When kubelet restarts, DRA Manager NodePrepareResource will not be called during SyncPod as pods will already be in running state (pod sandbox state ready), thus no redundant calls will be performed to DRA plugins.

When A Pod's sandbox need to be (re)created, DRA Manager NodePrepareResource will be called however its claims in in-memory claim cache would be marked as "prepared", thus no call to plugin will occur.

When Kubelet restarts AND a Pod's sandbox need to be (re)created, DRA manager will call DRA plugin. At that point its expected that the plugin is idempotent and return same results as resource already exists.

When Node reboots, resource may not be created on the node. however same steps as above will occur, which will trigger resource preparation by DRA plugin.
Note that result may be different in this case. thus latest results for a claim are stored in checkpoint. 

#### Which issue(s) this PR fixes:

Fixes #119850 

#### Does this PR introduce a user-facing change?

NONE

#### Alternatives

Place DRA manager checkpoint file under /var/run/kubelet so that its content is cleared
on node boot. that way if a pod sandbox is required to be created (during PodSync), NodePrepareResouce call will only
call DRA plugins for a given resource claim once.

### CODE REVIEW

**Comment by adrianchiris** [comment]
cc @moshe010 @klueska

**Comment by adrianchiris** [comment]
@bart0sh @klueska PTAL and let me know if you prefer the alternative.

**Comment by bart0sh** [comment]
I generally like this approach.
It would be good though, to understand if we need to put other checkpoints (device plugins, cpu/memory/topology managers) to /var/run/kubelet.
Another thing that this change makes `rundir` a command like option, which means that users can effectively disable checkpoint removal without knowing about it.  We should probably mention this in the command line option description or make `rundir` a constant.

**Comment by adrianchiris** [comment]
> It would be good though, to understand if we need to put other checkpoints (device plugins, cpu/memory/topology managers) to /var/run/kubelet.

perhaps @klueska has some inputs on this one ? (will try to have a look , im not too familiar with the other managers)
also i think each such manager would need to be addressed in his own PR. 

> Another thing is that this change makes rundir a command like option, which means that users can effectively disable checkpoint removal without knowing about it. We should probably mention this in the command line option description or make rundir a constant.

im fine with either, for now, let me update flag description that it is a requirement this path is cleared on node boot by some means.

**Comment by klueska** [comment]
Sorry it's taken me so long to get to review this.

I'm not sure I agree with the following premise which motivates this PR:
> After node reboots, it is required to call DRA plugin for resource claims so that plugins may prepare them again in case the resources don't persist reboot.

It should be up to the plugin to maintain its own state about what it has prepared or not (how else could it be idempotent), and if that state is not the current state of the hardware when the plugin tries to come online (for example after a node reboot or a simple restart), then it needs to do what's necessary to bring the hardware to that state before it marks itself as ready.

**Comment by adrianchiris** [comment]
> It should be up to the plugin to maintain its own state about what it has prepared or not (how else could it be idempotent),

i assume it depends on the plugin, one way is to have the desired result in the request. (e.g in my case request consists of allocating a scalable function aka SF on a specific device with a specific index)

> then it needs to do what's necessary to bring the hardware to that state before it marks itself as ready.

even if a plugin stores it state in yet another cache. how do you ensure pods consuming resources dont spin up (by kubelet on node reboot) before the dra plugin pod starts and has time to align its own internal state.

now, even if it has time to sort its internal state by some means, what if preparing some of the resources fail (and some succeed) do we fail all by not starting ?

there are even more subtleties in my case when we get into creating resources in parallel but i think these are solvable

**Comment by adrianchiris** [comment]
OK, I have discussed with @klueska off-line, the points raised above are valid in his view.

However his preference is to take the alternative approach described in the PR title.
as its a more conservative approach, which seems safer as currently we dont have anything kubelet related in /var/run.

As kubelet should generally NOT restart, the added overhead of calling DRA plugins on kubelet restart is the same as node reboot and should be deemed acceptable IMO.

@bart0sh LMK if you are also OK with this (the alternative) approach and I can start working on implementation.

**Comment by bart0sh** [comment]
> @bart0sh LMK if you are also OK with this (the alternative)

I'm generally OK, but would like to know more details about possible overhead, i.e. when and how often `NodePrepareResources` will be called in this case in comparison with the original approach.

Would it make sense to implement a node_e2e to simulate node reboot and analyse both approaches?

**Comment by adrianchiris** [comment]
>I'm generally OK, but would like to know more details about possible overhead, i.e. when and how often NodePrepareResources will be called in this case in comparison with the original approach.

Hi, appologies for the delay, i have updated the PR to reflect the new direction. see updated PR description as well.

**The below compares the two approaches:**

**Approach-1(Original)**: Store checkpoint in /var/run/
**Approach-2 (Current)**: Call dra plugin for pod claims regardless of their presence in cache, but keep track in-memory if kubelet already prepared a given claim so we dont process a claim twice during kubelet run.

given a single pod running on node with N claims to K plugins.

**Scenarios:**
1. Pod is already running, kubelet restarted

both approach 1 and 2 will not call DRA plugins for pod claims.

2. pod sandbox need to be re-created, kubelet running

both approach 1 and 2 will not call DRA plugins for pod claims.

3. kubelet restarted then Pod sandbox need to be re-created

Approach-1 will not call DRA plugins for pod claims
Approach-2 will call DRA plugins for pod claims (K calls to DRA plugins), subsequent pods that reference same claims will not trigger a call to DRA pluigns.

4. node reboot

Both Approach-1 and Approach-2 will call DRA plugins  for pod claims.
subsequent pods that reference same claims will not trigger a call to DRA pluigns


so essentially the only overhead WRT DRA plugins is in scenario 3, as kubelet restart would cause kubelet to "lose" its in-memory state of which claims it handled. it may require up to N claims to be prepared by DRA plugins, N being the total number of claims that are bound to this node. IF we start having pod sandbox recreation requests for Pods.

File: pkg/kubelet/cm/dra/manager.go [hunk 1]
```diff
@@ -120,31 +122,34 @@ func (m *ManagerImpl) PrepareResources(pod *v1.Pod) error {
...
+			}
+		} else {
+			// Grab the allocation.resourceHandles. If there are no
+			// allocation.resourceHandles, create a single resourceHandle with no
+			// content. This will trigger processing of this claim by a single
+			// kubelet plugin whose name matches resourceClaim.Status.DriverName.
+			resourceHandles := resourceClaim.Status.Allocation.ResourceHandles
+			if len(resourceHandles) == 0 {
+				resourceHandles = make([]resourcev1alpha2.ResourceHandle, 1)
+			}
```
Comment (klueska) [inline pkg/kubelet/cm/dra/manager.go:137]: Something feel odd about this -- it may be correct, but the logic is not very obivous and I'm getting a little lost trying to understand it.

Previously the logic was:
* If the claim is in the cache, we know it has been prepared successfully, so just add a pod reference and continue
* If the claim is not in the cache, attempt to prepare it, and if that succeeds, add it to the cache.

I think the new logic should be:
* If the claim is in the cache and it is prepared, add a pod reference and continue
* If the claim is in the cache, and not prepared, prepare it and mark it as such
* If the claim is not in the cache, prepare it, add it to the cache, and make it as prepared

If you agree, can you update the logic to make this flow more obvious.

Comment (adrianchiris) [reply pkg/kubelet/cm/dra/manager.go:137]: i agree at high level, however the lower level details are a bit different.

one thing to note is that checking if a claim needs to be processed  (prepared) by the manager and marking it as prepared then actually adding to cache happens in a separate loops

the method has two main loops:
1. go over all pod claims, check them and determine which claims should process by calling to DRA plugin  (filling in `claimInfos` map and `batches`)
2. call DRA plugins in a batch manner and update cache

the changes i introduced:
in 1 :  claims that have not been processed (not prepared) by manager will get added to the relevant structs to be processed
in 2: after a claim has been successfully handled by DRA plugin mark it as prepared before adding it to cache.

lemme try to simplify 1 a bit.

**Review by adrianchiris — COMMENTED** [review]
Thx for the feedback, will upload PR shortly

File: pkg/kubelet/cm/dra/manager.go [hunk 2]
```diff
@@ -109,42 +107,31 @@ func (m *ManagerImpl) PrepareResources(pod *v1.Pod) error {
...
+		claimInfo := m.cache.get(*claimName, pod.Namespace)
 
-		// Grab the allocation.resourceHandles. If there are no
-		// allocation.resourceHandles, create a single resourceHandle with no
-		// content. This will trigger processing of this claim by a single
-		// kubelet plugin whose name matches resourceClaim.Status.DriverName.
-		resourceHandles := resourceClaim.Status.Allocation.ResourceHandles
-		if len(resourceHandles) == 0 {
-			resourceHandles = make([]resourcev1alpha2.ResourceHandle, 1)
+		if claimInfo == nil {
```
Comment (klueska) [inline pkg/kubelet/cm/dra/manager.go:112]: nit: remove newline

File: pkg/kubelet/cm/dra/manager.go [hunk 3]
```diff
@@ -109,42 +107,31 @@ func (m *ManagerImpl) PrepareResources(pod *v1.Pod) error {
...
+			// claim does not exist in cache, create new claimInfo object
+			// to be processed later
```
Comment (klueska) [inline pkg/kubelet/cm/dra/manager.go:114]:
```suggestion
			// Claim does not exist in cache, create new claimInfo object
			// to be processed later.
```

**Review by klueska — COMMENTED** [review]
Thanks for the cleanup. It is much clearer now what is going on.

/approve
/lgtm

File: pkg/kubelet/cm/dra/manager.go (hunk 2 above)
Comment (adrianchiris) [reply pkg/kubelet/cm/dra/manager.go]: Done.

File: pkg/kubelet/cm/dra/manager.go (hunk 3 above)
Comment (adrianchiris) [reply pkg/kubelet/cm/dra/manager.go]: done.

**Comment by pacoxu** [comment]
A release note is needed.
The original release note is like
```
Added a new kubelet CLI flag "--run-dir" : directory path for managing kubelet runtime files. (default "/var/run/kubelet")
```

Or you may comment `/release-note-none` if no release note is not needed.

**Comment by adrianchiris** [comment]
no release note is needed for this one (went with a different impl than the original proposal)

/release-note-none

**Comment by adrianchiris** [comment]
@bart0sh @klueska do we want to backport this to 1.28 ? is there anything i need to do WRT backport ?
