### PR TITLE
Ensure reproducible builds - support for SOURCE_DATE_EPOCH with docke…

### LINKED ISSUE #48710: kubernetes packages differ for each build
/kind bug

**What happened**:
```
/usr/bin/hyperkube
/usr/bin/kubeadm
/usr/src/kubernetes/platforms/linux/amd64/e2e.test
```
have a date+time string embedded in them in the format
2018-08-15T19:08:34Z
that differs for each build

**What you expected to happen**:
It should be possible to build reproducibly, generating identical binaries no matter when (and where)

**How to reproduce it (as minimally and precisely as possible)**:
on openSUSE do
```bash
osc checkout openSUSE:Factory/kubernetes
cd $_
osc build --keep-pkg=RPMS --vm-type=kvm
cd RPMS
unrpm kubernetes-kubeadm-1.6.1-0.x86_64.rpm
strings usr/bin/kubeadm | grep $(date +%Y-%m-%d)
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.6.1
- OS: openSUSE (any)

proposed fix: #48708

### PR DESCRIPTION
**Pull request by dims**
…rized builds

**What this PR does / why we need it**:

- Pass in SOURCE_DATE_EPOCH when we run the docker container
- Looks like cleaning up symbol table also helps
- Also trimming the path

Tips from
- https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/
- https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Change-Id: Iedba85d9c1a36790fb8814795f7c27c1371cff1b

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #48710

**Special notes for your reviewer**:
Also see https://github.com/kubernetes/release/issues/637

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
tested using a ubuntu box and macos laptop.

```
[dims@dims-mac 12:17] ~/go/src/k8s.io/kubernetes ⟩ uname -a
Darwin dims-mac.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
[dims@dims-mac 12:18] ~/go/src/k8s.io/kubernetes ⟩ env | grep SOU
SOURCE_DATE_EPOCH=1537756023
[dims@dims-mac 11:48] ~/go/src/k8s.io/kubernetes ⟩ make quick-release KUBE_RELEASE_RUN_TESTS=n KUBE_FASTBUILD=true KUBE_BUILD_PLATFORMS=linux/amd64 > build.log 2>&1
[dims@dims-mac 12:16] ~/go/src/k8s.io/kubernetes ⟩ find _output/ -name kubeadm | head -1 | xargs go tool buildid
VujZqRe2tl3WkQ0nMAZ_/tilMkR22RO1vDkNHWtL0/MwvFRcSW3Pv416atmbib/JB0Q72ltdahSYxZKGfNF
```

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ uname -a
Linux bigbox 4.15.0-33-generic #36~16.04.1-Ubuntu SMP Wed Aug 15 17:21:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
dims@bigbox:~/go/src/k8s.io/kubernetes$ env | grep SOU
SOURCE_DATE_EPOCH=1537756023
dims@bigbox:~/go/src/k8s.io/kubernetes$ make quick-release KUBE_RELEASE_RUN_TESTS=n KUBE_FASTBUILD=true KUBE_BUILD_PLATFORMS=linux/amd64 > build.log 2>&1
dims@bigbox:~/go/src/k8s.io/kubernetes$ find _output/ -name kubeadm | head -1 | xargs go tool buildid
VujZqRe2tl3WkQ0nMAZ_/tilMkR22RO1vDkNHWtL0/MwvFRcSW3Pv416atmbib/JB0Q72ltdahSYxZKGfNF
```

File: build/common.sh [hunk 1]
```diff
@@ -600,6 +600,7 @@ function kube::build::run_build_command_ex() {
     --env "GOFLAGS=${GOFLAGS:-}"
     --env "GOLDFLAGS=${GOLDFLAGS:-}"
     --env "GOGCFLAGS=${GOGCFLAGS:-}"
+    --env "SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-}"
```
Comment (ixdy) [inline build/common.sh]: I don't think we need this - all of the version info is saved outside of docker before we enter the build container because we don't sync `.git` into the container.

https://github.com/kubernetes/kubernetes/blob/170dcc2ea086f94fb5d80c75f2aa1c1039084d36/build/common.sh#L193-L194

**Comment by ixdy** [comment]
I agree with @cblecker, thanks for looking into this!

File: build/common.sh (hunk 1 above)
Comment (ixdy) [reply build/common.sh]: ... though I guess it doesn't hurt, in case any other tools consult `SOURCE_DATE_EPOCH`.

Comment (dims) [reply build/common.sh]: @ixdy the `kube::version::ldflag()` does not use the stuff from .dockerized-kube-version-defs

it builds a new date if the env var is not set (the best i can tell):
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L155-L156

Comment (ixdy) [reply build/common.sh]: The build image sets `KUBE_GIT_VERSION_FILE`:
https://github.com/kubernetes/kubernetes/blob/170dcc2ea086f94fb5d80c75f2aa1c1039084d36/build/build-image/Dockerfile#L36-L37

When this is set, we read it for the version info:
https://github.com/kubernetes/kubernetes/blob/170dcc2ea086f94fb5d80c75f2aa1c1039084d36/hack/lib/version.sh#L32-L38

Comment (ixdy) [reply build/common.sh]: Oh wait, now I see what you're saying. Yes, you are right. I forgot that we only save the git metadata, not time metadata (unlike bazel's workspace status script).

Comment (dims) [reply build/common.sh]: correct :)

**Comment by cblecker** [comment]
boskos failure (likely the cluster upgrade -- cc: @BenTheElder)
/test pull-kubernetes-e2e-gce

**Comment by BenTheElder** [comment]
Yeah :( We're looking. It's not the cluster upgrade though, bad resource name merged around the same time https://github.com/kubernetes/test-infra/pull/9501/files#r219996998

**Comment by BenTheElder** [comment]
Awesome work btw -- does this get us fully reproducible for the binaries at least? I would guess other things like the docker images need more work still?

**Comment by dims** [comment]
@BenTheElder y, easiest was the man pages, next is the binaries. @bmwiedemann is running the show and will tell us where to put our efforts next hopefully.

**Comment by BenTheElder** [comment]
great!
/retest
hopefully boskos is sorted now, it appears to be...

**Comment by dims** [comment]
@ixdy @BenTheElder one of you please re-lgtm
