### PR TITLE
tests Windows: Fixes test failures related to COMPUTERNAMEs being truncated

### LINKED ISSUE #106640: e2e test host_processs.go failed when the hostname is greater then 15 characters.
### What happened?

I want to run the host_process.go e2e test but it failed.

Reason:
Node name and hostname is longer than 15 characters.
But the ComputerName only used the first 15 characters.
So they don't equal and the test failed.

### What did you expect to happen?

The e2etest should pass regardless of the hostname length.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a Windows with long nodename (longer than 15 characters). Then, run host_process.go e2e test.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+vmware.1", GitCommit:"1e08ca8eda6b74527882c9baee8e05620d24c96a", GitTreeState:"clean",
 BuildDate:"2021-11-01T20:55:58Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"windows/amd64"}  
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
BuildNumber  Caption                                 OSArchitecture  Version                                                                                  
17763        Microsoft Windows Server 2019 Standard  64-bit          10.0.17763
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### LINKED ISSUE #109821: Windows HostProcessContainer jobs fail due to mismatching COMPUTERNAME
### Which jobs are failing?

Windows GCE jobs:

https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master
https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-master

### Which tests are failing?

[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should run as a process on the host/node
[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should support various volume mount types

### Since when has it been failing?

Since the jobs were reintroduced.

### Testgrid link

https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master

### Reason for failure (if possible)

Windows COMPUTERNAMEs are typically limited to 15 characters [1], while the kubelet nodes spawned in the GCE test jobs are much longer (e.g.: ``e2e-e84a5b9f56-7f363-windows-node-group-0n9g``). The names might be truncated, resulting in the test failure.

[1] https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou#netbios-computer-names

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig windows
/sig testing

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig windows
/sig testing

/kind failing-test
/priority important-soon

#### What this PR does / why we need it:

Windows ComputerNames cannot exceed 15 characters. This causes a few tests to fail when the node names exceed that limit. Additionally, the checks should be case insensitive.

Sample failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce-master/1524626757083205632

#### Which issue(s) this PR fixes:

Fixes #109821
Fixes #106640
Related: #109908

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/windows/host_process.go [hunk 1]
```diff
@@ -95,6 +97,8 @@ var _ = SIGDescribe("[Feature:WindowsHostProcessContainers] [MinimumKubeletVersi
 		ginkgo.By("scheduling a pod with a container that verifies %COMPUTERNAME% matches selected node name")
 		image := imageutils.GetConfig(imageutils.BusyBox)
 		podName := "host-process-test-pod"
+		// Windows ComputerNames cannot exceed 15 characters.
+		truncComputerName := targetNode.Name[:15]
```
Comment (jsturtevant) [inline test/e2e/windows/host_process.go:101]: Won't this trhow if the targetNode.Name is less than 15? https://go.dev/play/p/MQnDG7IZDpf

**Comment by jsturtevant** [comment]
this was discussed a bit in slack awhile back https://github.com/kubernetes/kubernetes/issues/106640#issuecomment-977999401. Did you try this with Hostname?

**Comment by ibabou** [comment]
> /cc @ibabou , can you check if this fix solves the `[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should support various volume mount types` and `[sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers should run as a process on the host/node` tests that are currently failing on GCE?

Thanks Caludiu for looking into this! Is there a way to invoke the test against master with this change to verify it? I mean from the PR itself? I can get to it on Monday and create a run manually on an internal prow cluster to verify otherwise.

**Comment by jsturtevant** [comment]
> Thanks Caludiu for looking into this! Is there a way to invoke the test against master with this change to verify it? I mean from the PR itself? I can get to it on Monday and create a run manually on an internal prow cluster to verify otherwise.

We have the `pull-kubernetes-e2e-capz-windows-containerd` which will validate it against azure setup.  I am not aware of any pre-submits for gce Windows.  It could be possible to add one that could verify the ci job: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-windows/windows-gce.yaml  

(if we update those maybe we can move them to the folder https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs/sig-windows to have everything in one place?)

File: test/e2e/windows/host_process.go (hunk 1 above)
Comment (jsturtevant) [reply test/e2e/windows/host_process.go:101]: @claudiubelu

Comment (claudiubelu) [reply test/e2e/windows/host_process.go]: Done

**Review by jsturtevant — CHANGES_REQUESTED** [review]
If the node name is generated by capi framework, then the last few characters of the name are usually the unique ones for the node for example from the [issue](https://github.com/kubernetes/kubernetes/issues/106640#issuecomment-978701243) `tkg-mgmt-vc-md-2-5566ff-7scfg` then this code taking 15 chars would match `tkg-mgmt-vc-md-` which wouldn't be unique.  

Have you tried this with hostname https://github.com/kubernetes/kubernetes/issues/106640#issuecomment-977999401?

**Comment by helayoty** [comment]
@jsturtevant @claudiubelu @feiskyer  👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this PR and if we are still targeting the current release. Also, is it a release blocker?

**Comment by jsturtevant** [comment]
not release blocking
/milestone clear

File: test/e2e/windows/host_process.go [hunk 2]
```diff
@@ -109,9 +116,10 @@ var _ = SIGDescribe("[Feature:WindowsHostProcessContainers] [MinimumKubeletVersi
 				HostNetwork: true,
 				Containers: []v1.Container{
 					{
-						Image:   image.GetE2EImage(),
-						Name:    "computer-name-test",
-						Command: []string{"cmd.exe", "/K", "IF", "NOT", "%COMPUTERNAME%", "==", targetNode.Name, "(", "exit", "-1", ")"},
+						Image: image.GetE2EImage(),
+						Name:  "computer-name-test",
+						// The /I argument makes the string comparison case insensitive.
+						Command: []string{"cmd.exe", "/K", "IF", "/I", "NOT", "%COMPUTERNAME%", "==", computerName, "(", "exit", "-1", ")"},
```
Comment (jayunit100) [inline test/e2e/windows/host_process.go:122]: @claudiubelu ...  wait... shouldnt this be

```
if $COMPUTERNAME%.contains(computerName) ;
   pass
else
   fail
```
?

**Comment by jsturtevant** [comment]
/hold
This won't work as is, due to the way it is truncating https://github.com/kubernetes/kubernetes/pull/110014#pullrequestreview-998943740

File: test/e2e/windows/host_process.go (hunk 2 above)
Comment (claudiubelu) [reply test/e2e/windows/host_process.go:122]: Just as a sample:

```
C:\Users\Administrator\workdir\kubernetes>echo %COMPUTERNAME:~0,15%
WIN-AE7D7USH1E2

C:\Users\Administrator\workdir\kubernetes>echo %COMPUTERNAME:~0,5%
WIN-A
```

**Comment by marosset** [comment]
Waiting on confirmation from @knabben that this works in sig-windows-dev-tools

**Comment by knabben** [comment]
I confirm the hostname usage fixed the issue for CAPV and long node names.

/lgtm

**Comment by knabben** [comment]
maybe I will be able to do it?

/unhold
