### PR TITLE
Fix a failing test in NetworkPolicy e2e

### LINKED ISSUE #85908: A NetworkPolicy e2e test is failing
**What happened**:
The NetworkPolicy e2e test ["should allow ingress access from updated pod"](https://github.com/kubernetes/kubernetes/blob/6d5eee88e0811276d144976d7523948199b752e5/test/e2e/network/network_policy.go#L823) fails regardless of which CNI plugin is enabled.

The test assumes the client Pod can recheck connectivity after updating its label, but the client won't restart after the first failure, so the second check will always fail.

**What you expected to happen**:
The test should succeed if a CNI plugin implements NetworkPolicy correctly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install a CNI that supports NetworkPolicy.
2. Run the e2e test by focusing "should allow ingress access from updated pod".
3. The test will always fail.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
The test "should allow ingress access from updated pod" fails regardless
of which CNI plugin is enabled. It's because the test assumes the client
Pod can recheck connectivity after updating its label, but the client
won't restart after the first failure, so the second check will always
fail. The PR creates a client Pod with OnFailure RestartPolicy to fix it.

In addition to the above test that checks rule selector takes effect on
updated client pod, the PR adds a test "should deny ingress access to
updated pod" to ensure network policy selector can take effect on updated
server pod.

**Which issue(s) this PR fixes**:

Fixes #85908

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
sig-network owns review of this test

**Comment by matthyx** [comment]
> sig-network owns review of this test

sorry

**Comment by jayunit100** [comment]
cc @andrewsykim  .... i like that this fixes network policy tests, can you confirm that we're not altering the semantics of the test in a way that can cause a regression ?   Im looking into this as well no.

File: test/e2e/network/network_policy.go [hunk 1]
```diff
@@ -821,49 +821,39 @@ var _ = SIGDescribe("NetworkPolicy [LinuxOnly]", func() {
...
 
-		ginkgo.It("should allow ingress access from updated pod [Feature:NetworkPolicy]", func() {
+		ginkgo.It("should deny ingress access to updated pod [Feature:NetworkPolicy]", func() {
 			const allowedPort = 80
-			ginkgo.By("Creating a network policy for the server which allows traffic from client-a-updated.")
+			ginkgo.By("Creating a network policy for the server which denies all traffic.")
 			policy := &networkingv1.NetworkPolicy{
 				ObjectMeta: metav1.ObjectMeta{
-					Name: "allow-pod-b-via-pod-selector",
+					Name: "deny-all",
```
Comment (andrewsykim) [inline test/e2e/network/network_policy.go]: A better name might be `deny-ingress-via-isolated-label-selector`

Comment (tnqn) [reply test/e2e/network/network_policy.go]: Done

**Comment by tnqn** [comment]
Thanks @andrewsykim @jayunit100 for reviewing and the suggestion.

File: test/e2e/network/network_policy.go [hunk 2]
```diff
@@ -821,49 +821,39 @@ var _ = SIGDescribe("NetworkPolicy [LinuxOnly]", func() {
...
-			ginkgo.By(fmt.Sprintf("Updating client pod %s that should successfully connect to %s.", podClient.Name, service.Name))
-			podClient = updateNetworkClientPodLabel(f, f.Namespace, podClient.Name, "replace", "/metadata/labels", map[string]string{})
-			checkConnectivity(f, f.Namespace, podClient, service)
+			// Client can connect to service when the server pod is not selected by the network policy.
+			testCanConnect(f, f.Namespace, "client-a", service, allowedPort)
+
+			// Client cannot connect to service after updating the server pod's labels to match the network policy.
+			ginkgo.By(fmt.Sprintf("Updating server pod %s to be selected by network policy %s.", podServer.Name, policy.Name))
+			updateNetworkClientPodLabel(f, f.Namespace, podServer.Name, "add", "/metadata/labels", map[string]string{"isolated": ""})
+			testCannotConnect(f, f.Namespace, "client-a", service, allowedPort)
```
Comment (andrewsykim) [inline test/e2e/network/network_policy.go]: Pod client has `RestartPolicyNever`, so would this also fail since pod will be in `Succeeded` state from previous test case?

Comment (tnqn) [reply test/e2e/network/network_policy.go]: `testCanConnect` and `testCannotConnect` create new client Pod, check connection, and clean up it. 
https://github.com/kubernetes/kubernetes/blob/52d7614a8ca5b8aebc45333b6dc8fbf86a5e7ddf/test/e2e/network/network_policy.go#L1386-L1396
Using same pod name `client-a` is to emphasize the behavior changes by server pod's label change only. The two steps actually use two client Pods having same name and labels.

Comment (andrewsykim) [reply test/e2e/network/network_policy.go]: So this is no longer "ingress access to updated pod", but "ingress access to new pod" then? I think we still want the updated pod test case.

Comment (tnqn) [reply test/e2e/network/network_policy.go]: It's still updated pod, but just updated server Pod.
As the PR description explains, all network policy tests are using the utils "testCannotConnect" and "testCanConnect" which creates a client Pod designed for **one-shot** check without restarting, it's not convenient to test twice with a single client Pod (that's also the mistake the original test made), unless we write another util just for this case.
I think essentially the updated pod test case wants to ensure network policy can be enabled on existing Pods after updating their labels to match them, so it should make sense to verify it on server Pod, as even the original test just verified it on client Pod. Does it make sense?

Comment (andrewsykim) [reply test/e2e/network/network_policy.go]: I see, so if we are creating new client pod every time and only the server pod gets updated labels, it seems like we can still test the `deny` -> `allow` test case right and we don't really need to flip the order? I think we could benefit from having both:
* deny -> allow by updating server pod labels with new client pod for each connection
* allow -> deny by updating server pod labels with new client pod for each connection

Comment (tnqn) [reply test/e2e/network/network_policy.go]: I updated the order because the server Pod and its service is created in `BeforeEach`, having only a fixed label `pod-name: server` which is also used by its service to select backends. So it's not convenient to first create a deny policy which selects the server Pod, and then update the server Pod to not match it as updating label "pod-name: server" will make service not work.
To have both tests, I can append one more step to remove the "isolated" label and call `testCanConnect` again, it would be the reversed version of your proposal, what do you think?

**Comment by bowei** [comment]
cc: @lzang

File: test/e2e/network/network_policy.go (hunk 2 above)
Comment (lzang) [reply test/e2e/network/network_policy.go]: This looks like a different test case to me. The original one is to change the network policy ingress rule selector, so a client that couldn't connect can connect now. Your test case is to change network policy selector, so a server that was protected by the policy become not protected. Maybe we can fix the original one by creating a new client pod and create a new test case for this change? Creating a new client pod is not ideal to test policy change but the enforcement is on the server side for both cases anyway.

File: test/e2e/network/network_policy.go [hunk 3]
```diff
@@ -821,49 +821,39 @@ var _ = SIGDescribe("NetworkPolicy [LinuxOnly]", func() {
...
-
-			ginkgo.By(fmt.Sprintf("Updating client pod %s that should successfully connect to %s.", podClient.Name, service.Name))
-			podClient = updateNetworkClientPodLabel(f, f.Namespace, podClient.Name, "replace", "/metadata/labels", map[string]string{})
-			checkConnectivity(f, f.Namespace, podClient, service)
+			// Client can connect to service when the server pod is not selected by the network policy.
+			testCanConnect(f, f.Namespace, "client-a", service, allowedPort)
+
+			// Client cannot connect to service after updating the server pod's labels to match the network policy.
+			ginkgo.By(fmt.Sprintf("Updating server pod %s to be selected by network policy %s.", podServer.Name, policy.Name))
+			updateNetworkClientPodLabel(f, f.Namespace, podServer.Name, "add", "/metadata/labels", map[string]string{"isolated": ""})
```
Comment (lzang) [inline test/e2e/network/network_policy.go]: Use updateNetworkClientPodLabel to change a server pod label is confusing. Could you rename the function to a generic one?

File: test/e2e/network/network_policy.go (hunk 2 above)
Comment (tnqn) [reply test/e2e/network/network_policy.go]: Thanks @lzang for reviewing. I restored the original test and fixed it by creating the client pod with `OnFailure` RestartPolicy and updating its label after failure is detected as creating a new client pod may make the test case same as some existing tests which check pods with different labels will have different behaviors, like 
https://github.com/kubernetes/kubernetes/blob/29b09c7fb1a8d38ab9df4873553cc0b8d97aae95/test/e2e/network/network_policy.go#L147-L152
I created a new test case to ensure network policy selector can take effect on updated server pod as you suggested.

File: test/e2e/network/network_policy.go (hunk 3 above)
Comment (tnqn) [reply test/e2e/network/network_policy.go]: I didn't notice the function name, thanks for catching it, done.

File: test/e2e/network/network_policy.go [hunk 4]
```diff
@@ -852,20 +852,75 @@ var _ = SIGDescribe("NetworkPolicy [LinuxOnly]", func() {
...
+				framework.Failf("Pod %s should not be able to connect to service %s, but was able to connect.\nPod logs:\n%s\n\n Current NetworkPolicies:\n\t%v\n\n Pods:\n\t%v\n\n", podClient.Name, service.Name, logs, policies.Items, pods)
+
+				// Dump debug information for the test namespace.
+				framework.DumpDebugInfo(f.ClientSet, f.Namespace.Name)
+			}
 
 			ginkgo.By(fmt.Sprintf("Updating client pod %s that should successfully connect to %s.", podClient.Name, service.Name))
-			podClient = updateNetworkClientPodLabel(f, f.Namespace, podClient.Name, "replace", "/metadata/labels", map[string]string{})
+			podClient = updatePodLabel(f, f.Namespace, podClient.Name, "replace", "/metadata/labels", map[string]string{})
 			checkConnectivity(f, f.Namespace, podClient, service)
```
Comment (lzang) [inline test/e2e/network/network_policy.go]: If checkConnectivity fails, who will clean up the pod as it would keep restarting on failure?

File: test/e2e/network/network_policy.go (hunk 2 above)
Comment (lzang) [reply test/e2e/network/network_policy.go]: The existing one doesn't have policy update, so I don't think they are the same, but I am fine if the new approach by modifying the restart policy could work.

File: test/e2e/network/network_policy.go [hunk 5]
```diff
@@ -1415,28 +1470,7 @@ func checkConnectivity(f *framework.Framework, ns *v1.Namespace, podClient *v1.P
...
-		podsInNS, err := e2epod.GetPodsInNamespace(f.ClientSet, f.Namespace.Name, map[string]string{})
-		if err != nil {
-			framework.Logf("error getting pods for %s namespace: %s", f.Namespace.Name, err)
-		}
-
-		pods := []string{}
-		for _, p := range podsInNS {
-			pods = append(pods, fmt.Sprintf("Pod: %s, Status: %s\n", p.Name, p.Status.String()))
-		}
+		pods, policies, logs := collectPodsAndNetworkPolicies(f, podClient)
```
Comment (lzang) [inline test/e2e/network/network_policy.go]: Thanks for cleaning this up!

File: test/e2e/network/network_policy.go [hunk 6]
```diff
@@ -852,20 +852,75 @@ var _ = SIGDescribe("NetworkPolicy [LinuxOnly]", func() {
...
+			podClient := createNetworkClientPodWithRestartPolicy(f, f.Namespace, "client-a", service, allowedPort, v1.RestartPolicyOnFailure)
 			defer func() {
 				ginkgo.By(fmt.Sprintf("Cleaning up the pod %s", podClient.Name))
 				if err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Delete(podClient.Name, nil); err != nil {
 					framework.Failf("unable to cleanup pod %v: %v", podClient.Name, err)
 				}
 			}()
-			checkNoConnectivity(f, f.Namespace, podClient, service)
+			// Check Container exit code as restartable Pod's Phase will be Running even when container fails.
+			err = e2epod.WaitForPodCondition(f.ClientSet, f.Namespace.Name, podClient.Name, "terminated", framework.PodStartTimeout, func(pod *v1.Pod) (bool, error) {
```
[the remark this answers is not in the document]
Comment (tnqn) [reply test/e2e/network/network_policy.go]: Done

File: test/e2e/network/network_policy.go (hunk 4 above)
Comment (tnqn) [reply test/e2e/network/network_policy.go]: `checkConnectivity` has timeout (3 min):
https://github.com/kubernetes/kubernetes/blob/ae95a4bfcac12bf6b19e2d5acf6404359b1a8c3b/test/e2e/framework/pod/wait.go#L356-L357
The test will fail if timeout occurs and the Pod will be cleaned up by the deferred delete function.

**Comment by tnqn** [comment]
@andrewsykim @bowei @lzang I think I have addressed all comments, fixed the original updated pod (matching rule selector) case, and added a new one for updated server pod (matching network policy selector), could you take another look at this?

**Comment by tnqn** [comment]
Resolved conflicts.
@andrewsykim @bowei @lzang @matthyx could you review again and approve it if the fix makes sense to you?
