### PR TITLE
fix kubelet trace broke in 1.28

### LINKED ISSUE #121192: kubelet traces broken from at least 1.28
### What happened?

spans are not being parented to other spans - propagation of context seems broken. More context: https://kubernetes.slack.com/archives/C0BP8PW9G/p1695396184849579

### What did you expect to happen?

spans should be parented to other spans

### How can we reproduce it (as minimally and precisely as possible)?

enable kubelet tracing at v1.28 and hook up a tracing backend.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
v1.28 at least
</details>

### Cloud provider

<details>
Not sure this matters.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by fatsheep9146**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

The kubelet trace is broken since kubernetes 1.28

The broken issue is due to the pr #117412, which try to propagate context brought by pod worker to syncPod function in order to let the syncPod can be interrupted in time by other asynchronous routines, for example eviction.

But in the line 

https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/kubelet/kubelet.go#L1963-L1965

we did not pass the context which contain the parent span and trace into `syncPod` function, so the trace is broken.

https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/kubelet/kubelet.go#L1719

So I want to fix this by passing the `ctx` into `syncPod`, which is also desired in comment 

https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/kubelet/kubelet.go#L1959-L1962

But passing the ctx into syncPod may have something other to do as described in comments, so I tried to fix as comments advised. #122087

 

#### Which issue(s) this PR fixes:
Fixes #121192

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

**Comment by fatsheep9146** [comment]
@dashpole could you help add ok-to-test label, so I can see if this change will broke any test which is mentioned in comments

https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/kubelet/kubelet.go#L1959-L1962

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1960,9 +1960,11 @@ func (kl *Kubelet) SyncPod(ctx context.Context, updateType kubetypes.SyncPodType
 	// Currently, using that context causes test failures. To remove this todoCtx, any wait.Interrupted
 	// errors need to be filtered from result and bypass the reasonCache - cancelling the context for
 	// SyncPod is a known and deliberate error, not a generic error.
-	todoCtx := context.TODO()
```
Comment (dashpole) [inline pkg/kubelet/kubelet.go:1963]: Can you try using `context.WithoutCancel(ctx)` instead?: https://pkg.go.dev/context#WithoutCancel

That should keep our trace context, but not propagate cancellation while #113606 is worked on

Comment (dashpole) [reply pkg/kubelet/kubelet.go:1963]: For background, this code is an extremely sensitive part of the kubelet.  The less we can change while fixing our bug, the better.

Comment (fatsheep9146) [reply pkg/kubelet/kubelet.go:1963]: Agree, and I think we should also add test in case this problem will not happened again.

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1960,9 +1960,12 @@ func (kl *Kubelet) SyncPod(ctx context.Context, updateType kubetypes.SyncPodType
...
 	// Call the container runtime's SyncPod callback
-	result := kl.containerRuntime.SyncPod(todoCtx, pod, podStatus, pullSecrets, kl.backOff)
+	sctx := context.WithoutCancel(ctx)
+	result := kl.containerRuntime.SyncPod(sctx, pod, podStatus, pullSecrets, kl.backOff)
+	if wait.Interrupted(result.Error()) {
```
Comment (dashpole) [inline pkg/kubelet/kubelet.go:1966]: lets remove this addition

**Comment by dashpole** [comment]
Looks like this passes tests now.  We just need to confirm that it fixes kubelet traces via a test

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -1960,9 +1960,9 @@ func (kl *Kubelet) SyncPod(ctx context.Context, updateType kubetypes.SyncPodType
 	// Currently, using that context causes test failures. To remove this todoCtx, any wait.Interrupted
 	// errors need to be filtered from result and bypass the reasonCache - cancelling the context for
 	// SyncPod is a known and deliberate error, not a generic error.
-	todoCtx := context.TODO()
```
Comment (VirrageS) [inline pkg/kubelet/kubelet.go:1963]: Removing this line outdates the comment which should be updated.

**Review by VirrageS — CHANGES_REQUESTED** [review]

**Comment by fatsheep9146** [comment]
> Looks like this passes tests now. We just need to confirm that it fixes kubelet traces via a test

I wrote a test `TestSyncPodSpans` in which called `syncPod`, and try to check the outputted spans in following aspects

- there exists a root span whose span name is called `syncPod`.
- there exist several spans which belong to `runtime.v1.ImageService` and also have trace id same as root span's trace id and parent span id as root span's span id.
- there exist several spans which belong to `runtime.v1.RuntimeService` and also have trace id same as root span's trace id and parent span id as root span's span id.

@dashpole  what do you think about the idea of test?

File: pkg/kubelet/kubelet_test.go [hunk 4]
```diff
@@ -3222,3 +3225,121 @@ func TestNewMainKubeletStandAlone(t *testing.T) {
...
+		SyncFrequency: metav1.Duration{Duration: time.Minute},
+		ConfigMapAndSecretChangeDetectionStrategy: kubeletconfiginternal.WatchChangeDetectionStrategy,
+		ContainerLogMaxSize:                       "10Mi",
+		ContainerLogMaxFiles:                      5,
+		MemoryThrottlingFactor:                    utilpointer.Float64(0),
+	}
+
+	exp := tracetest.NewInMemoryExporter()
+	tp := sdktrace.NewTracerProvider(
+		sdktrace.WithBatcher(exp),
```
Comment (dashpole) [inline pkg/kubelet/kubelet_test.go:3252]: consider just using WithSyncer, so you don't need to forceflush later

File: pkg/kubelet/kubelet_test.go [hunk 5]
```diff
@@ -3222,3 +3225,121 @@ func TestNewMainKubeletStandAlone(t *testing.T) {
...
+	spans := exp.GetSpans()
+	for i, span := range spans {
+		if span.Name == "syncPod" {
+			rootSpan = &spans[i]
+			break
+		}
+	}
+	assert.NotNil(t, rootSpan)
+
+	imageServiceSpans := make([]tracetest.SpanStub, 0)
```
Comment (dashpole) [inline pkg/kubelet/kubelet_test.go:3331]: are there multiple imageService spans? or runtimeServiceSpans?

File: pkg/kubelet/kubelet_test.go [hunk 6]
```diff
@@ -3222,3 +3225,121 @@ func TestNewMainKubeletStandAlone(t *testing.T) {
...
+	runtimeServiceSpans := make([]tracetest.SpanStub, 0)
+	for _, span := range exp.GetSpans() {
+		if span.SpanContext.TraceID() == rootSpan.SpanContext.TraceID() && span.Parent.SpanID() == rootSpan.SpanContext.SpanID() {
```
Comment (dashpole) [inline pkg/kubelet/kubelet_test.go:3334]: If possible, can we find the span first, and then check that the traceID and span ID match?  Otherwise, we just get an "Empty" error below, which can be hard to debug.

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (dashpole) [reply pkg/kubelet/kubelet.go:1963]: Suggestion:
```
// TODO(#113606): use cancellation from the incoming context parameter, which comes from the pod worker.
// Currently, using cancellation from that context causes test failures. To remove this WithoutCancel, 
// any wait.Interrupted errors need to be filtered from result and bypass the reasonCache - cancelling
// the context for SyncPod is a known and deliberate error, not a generic error.
```

File: pkg/kubelet/kubelet_test.go (hunk 4 above)
Comment (fatsheep9146) [reply pkg/kubelet/kubelet_test.go:3252]: Done

File: pkg/kubelet/kubelet_test.go (hunk 5 above)
Comment (fatsheep9146) [reply pkg/kubelet/kubelet_test.go:3331]: yes, 
the imageService spans we can get include
- runtime.v1.ImageService/ImageStatus
- runtime.v1.ImageService/PullImage

the runtimeService spans we can get include
- runtime.v1.RuntimeService/RunPodSandbox
- runtime.v1.RuntimeService/PodSandboxStatus
- runtime.v1.RuntimeService/CreateContainer
- runtime.v1.RuntimeService/StartContainer

File: pkg/kubelet/kubelet_test.go (hunk 6 above)
Comment (fatsheep9146) [reply pkg/kubelet/kubelet_test.go:3334]: Ok, I will change like this way

Comment (fatsheep9146) [reply pkg/kubelet/kubelet_test.go:3334]: I suggest we get span through checking if the trace id is matched with root span `syncPod`, and then compare each span if the are child of root span. 

This is for two reasons
1. In this test, we will also got some spans out of `syncPod` when starting the fake kubelet, for example, `runtime.v1.RuntimeService/Version`, `runtime.v1.ImageService/ImageFsInfo` which can be filtered out by checking the trace id.
2. We can first check whether the trace of `syncPod` only contains one span which means the context is not propagated well.

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (fatsheep9146) [reply pkg/kubelet/kubelet.go:1963]: How about we also add the reason of using `WithoutCancel`?

// The reason we use `WithoutCancel` is to keep the integrity of trace for `syncPod`. 

@dashpole

Comment (dashpole) [reply pkg/kubelet/kubelet.go:1963]: sounds good

Comment (dashpole) [reply pkg/kubelet/kubelet.go:1963]: Or, actually, i'd prefer:

```
// Use WithoutCancel instead of a new context.TODO() to propagate trace context
```

**Comment by fatsheep9146** [comment]
> Unit test LGTM. Once you update the comment, I think this is good to go.
> 
> cc @smarterclayton

comments are updated @dashpole

**Review by dashpole — APPROVED** [review]
/lgtm

**Comment by dashpole** [comment]
@Random-Liu 

Can you approve?

**Comment by fatsheep9146** [comment]
@saschagrunert @bart0sh @wzshiming could you help review or approve this pr?

**Comment by bart0sh** [comment]
/assign @mrunalp @derekwaynecarr @dchen1107 
for a final approval

**Review by saschagrunert — APPROVED** [review]

**Comment by dims** [comment]
/approve

happy with the level of reviews (@dashpole and others are happy!) given it's a one line change essentially and new tests have been added
