### PR TITLE
fix tabwriter to remember column widths, align `kubectl get -w` output

### LINKED ISSUE #3: kubectl get po columns aren't aligned when using watch mode
`kubectl version`

`Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}`

`Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`

See the below screenshot, when executing `kubectl get po -o wide -w`, the columns aren't aligned

untitled-1

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixes column alignment when using `kubectl get -w`

Before:
```
kubectl get ns -w
NAME              STATUS   AGE
default           Active   9h
kube-node-lease   Active   9h
kube-public       Active   9h
kube-system       Active   9h
ns1   Active   0s
ns-with-a-really-long-name   Active   0s
ns1   Terminating   8s
ns-with-a-really-long-name   Terminating   5s
ns1   Terminating   13s
ns-with-a-really-long-name   Terminating   10s
ns1   Terminating   13s
ns-with-a-really-long-name   Terminating   10s
```

After:
```
kubectl get ns -w
NAME              STATUS   AGE
default           Active   9h
kube-node-lease   Active   9h
kube-public       Active   9h
kube-system       Active   9h
ns1               Active   0s
ns-with-a-really-long-name   Active   0s
ns1                          Terminating   13s
ns-with-a-really-long-name   Terminating   6s
ns1                          Terminating   18s
ns1                          Terminating   18s
ns-with-a-really-long-name   Terminating   11s
ns-with-a-really-long-name   Terminating   11s
```

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubectl/issues/3

**Special notes for your reviewer**:
The golang text/tabwriter package is frozen and is not accepting new features.

https://github.com/liggitt/tabwriter is a branch of that package that adds the ability to remember column widths beyond `Flush()` calls. Columns align as much as possible as subsequent events are seen and printed. If columns are required to grow, the larger size informs later lines.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig cli
/cc @smarterclayton @seans3

### CODE REVIEW

**Comment by liggitt** [comment]
/hold
for review

File: pkg/printers/humanreadable.go [hunk 1]
```diff
@@ -399,7 +406,14 @@ func PrintTable(table *metav1beta1.Table, output io.Writer, options PrintOptions
 // does not expose metadata). It returns an error if the table cannot
 // be decorated.
 func DecorateTable(table *metav1beta1.Table, options PrintOptions) error {
+	return DecorateTableForEvent("", table, options)
+}
+
+func DecorateTableForEvent(eventType string, table *metav1beta1.Table, options PrintOptions) error {
```
Comment (smarterclayton) [inline pkg/printers/humanreadable.go]: Kind of yucky.  A table should know its column structure, and an event should be `<underlying printer> + event type wrapper`, so I feel like this shouldn't be necessary.

File: pkg/printers/humanreadable.go [hunk 2]
```diff
@@ -279,6 +281,11 @@ func printHeader(columnNames []string, w io.Writer) error {
 
 // PrintObj prints the obj in a human-friendly format according to the type of the obj.
 func (h *HumanReadablePrinter) PrintObj(obj runtime.Object, output io.Writer) error {
+	return h.PrintObjEvent("", obj, output)
+}
+
+// PrintObj prints the obj in a human-friendly format according to the type of the obj.
```
Comment (smarterclayton) [inline pkg/printers/humanreadable.go]: Why not just pass Event to PrintObj and have it to do the right thing?  This feels like a workaround to the underlying structure, and events are runtime.Objects just like everything else.

**Review by smarterclayton — COMMENTED** [review]
Don't love the separate Event handling methods

File: pkg/printers/humanreadable.go (hunk 1 above)
Comment (liggitt) [reply pkg/printers/humanreadable.go]: Move the event printing comments to https://github.com/kubernetes/kubernetes/pull/72416

Will rebase this on master so it's just the tabwriter change
