### PR TITLE
Correctly feature-gate WatchList e2e

### LINKED ISSUE #131380: [Failing Test] API Streaming (aka. WatchList) test fail when disables the beta WatchList feature was  by default
@liggitt @deads2k there are some e2e test that started failing after https://github.com/kubernetes/kubernetes/pull/131359 https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns-nodecache

```
W0418 16:53:21.966885   11003 simple.go:262] The watchlist request for /v1, Resource=secrets ended with an error, falling back to the standard LIST semantics, err = ListOptions.meta.k8s.io "" is invalid: sendInitialEvents: Forbidden: sendInitialEvents is forbidden for watch unless the WatchList feature gate is enabled
STEP: Verifying if expected response was sent by the server - k8s.io/kubernetes/test/e2e/apimachinery/watchlist.go:196 @ 04/18/25 16:53:22.009
[FAILED] Expected
    <string>: 422 Unprocessable Entity
to equal
    <string>: 406 Not Acceptable
```

The problem seems the be the assumption that `SetFeatureGateDuringTest` applies to e2e, that is wrong
> 		featuregatetesting.SetFeatureGateDuringTest(ginkgo.GinkgoTB(), utilfeature.DefaultFeatureGate, featuregate.Feature(clientfeatures.WatchListClient), true)

https://github.com/kubernetes/kubernetes/blob/66931f07d9c3a4b8b7aecb5649d710896001047c/test/e2e/apimachinery/watchlist.go#L54C22-L54C46

but it has to use the decorators in   ( I'm not sure if we need a new one or the linked one is valid for this)
https://github.com/kubernetes/kubernetes/blob/66931f07d9c3a4b8b7aecb5649d710896001047c/test/e2e/feature/feature.go#L560-L561

since e2e filtering is based on labels and tags

We need also to tag correct these tests, I'm AFK today and I will not be able to send a PR, but it will be good to get those te

cc: @carlory @pohly @BenTheElder

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/issues/131359#issuecomment-2816640694_

### PR DESCRIPTION
**Pull request by liggitt**
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/131380

This test assumes the watchlist feature is enabled on the server. Since it is not GA / locked on, it should not make that assumption.

https://github.com/kubernetes/kubernetes/pull/128053 removed the check of the feature gate when the feature was promoted to beta. This restores it so that the test is informed by the feature stability level and default state.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/feature/feature.go [hunk 1]
```diff
@@ -557,9 +557,6 @@ var (
 	// TODO: document the feature (owning SIG, when to use this feature for a test)
 	Vsphere = framework.WithFeature(framework.ValidFeatures.Add("vsphere"))
 
-	// TODO: document the feature (owning SIG, when to use this feature for a test)
-	WatchList = framework.WithFeature(framework.ValidFeatures.Add("WatchList"))
```
Comment (liggitt) [inline test/e2e/feature/feature.go:561]: dropping this in favor of the framework.WithFeatureGate incantation which is automatically informed by feature gate stability level and default state

**Comment by liggitt** [comment]
passed in watchlist

pushed restoring serial tag

/hold cancel

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
