### PR TITLE
Fix flake for GracefulNodeShutdown e2e

### LINKED ISSUE #101570: [flake] [sig-node]  [GracefulNodeShutdown] when gracefully shutting down should be able to handle a cancelled shutdown
Testgrid link:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-graceful-node-shutdown
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-graceful-node-shutdown/1387152775078481920

Reason for failure:

```
I0427 21:23:04.896] • Failure [25.418 seconds]
I0427 21:23:04.897] [sig-node] GracefulNodeShutdown [Serial] [NodeAlphaFeature:GracefulNodeShutdown]
I0427 21:23:04.897] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
I0427 21:23:04.897]   when gracefully shutting down
I0427 21:23:04.897]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:44
I0427 21:23:04.897]     should be able to handle a cancelled shutdown [It]
I0427 21:23:04.898]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:153
I0427 21:23:04.898] 
I0427 21:23:04.898]     Timed out after 10.000s.
I0427 21:23:04.898]     Expected
I0427 21:23:04.898]         <*errors.errorString | 0xc000e4a060>: {
I0427 21:23:04.898]             s: "node did not become shutdown as expected",
I0427 21:23:04.899]         }
I0427 21:23:04.899]     to be nil
I0427 21:23:04.899] 
I0427 21:23:04.899]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:163
```

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind flake
/sig node

#### What this PR does / why we need it:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-graceful-node-shutdown
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-graceful-node-shutdown/1387152775078481920

It is expected that the execution interval of these two cases is too close, and the Node state has not been restored, causing the next case to fail.

```
I0427 21:23:04.380] STEP: Verifying that all pods are shutdown

...

I0427 21:23:04.896] • Failure [25.418 seconds]
I0427 21:23:04.897] [sig-node] GracefulNodeShutdown [Serial] [NodeAlphaFeature:GracefulNodeShutdown]
I0427 21:23:04.897] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
I0427 21:23:04.897]   when gracefully shutting down
I0427 21:23:04.897]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:44
I0427 21:23:04.897]     should be able to handle a cancelled shutdown [It]
I0427 21:23:04.898]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:153
I0427 21:23:04.898] 
I0427 21:23:04.898]     Timed out after 10.000s.
I0427 21:23:04.898]     Expected
I0427 21:23:04.898]         <*errors.errorString | 0xc000e4a060>: {
I0427 21:23:04.898]             s: "node did not become shutdown as expected",
I0427 21:23:04.899]         }
I0427 21:23:04.899]     to be nil
I0427 21:23:04.899] 
I0427 21:23:04.899]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:163
```

#### Which issue(s) this PR fixes:

Fixes #101570

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: test/e2e_node/node_shutdown_linux_test.go [hunk 1]
```diff
@@ -59,6 +59,17 @@ var _ = SIGDescribe("GracefulNodeShutdown [Serial] [NodeAlphaFeature:GracefulNod
 			initialConfig.ShutdownGracePeriodCriticalPods = metav1.Duration{Duration: nodeShutdownGracePeriodCriticalPods}
 		})
 
+		ginkgo.BeforeEach(func() {
+			ginkgo.By("Waiting node ready")
```
Comment (bobbypage) [inline test/e2e_node/node_shutdown_linux_test.go:63]: Looks good, but what do you think about just using `waitForNodeReady` from [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/e2e_node_suite_test.go#L264-L283) instead? it seems to already have this logic built in :)

Comment (oomichi) [reply test/e2e_node/node_shutdown_linux_test.go:63]: That is a nice point, +1

**Review by oomichi — COMMENTED** [review]
It is fine to put approved label to solve the issue soon, I think.

/approve

**Comment by bobbypage** [comment]
/lgtm 

Thanks for fixing this!
