### PR TITLE
Pods which have not "started" can not be "ready"

### LINKED ISSUE #89995: Unexpected startupProbe behavior.
If I have `startupProbe` probe and `readinessProbe` then all good. Previous version of the pod is terminated after startup probe success, but if  `readinessProbe` wasn't specified the pod becomes ready immediately. It would be nice to add new state (for example starting) which would have pods until a `startupProbe` is successful. Also, it would mean that container not ready for connection.

Thank you for attention!

### PR DESCRIPTION
**Pull request by thockin**
Before this commit, containers which have both a `startupProbe` and a
`readinessProbe` are marked as `ready=false` during stratup, but
containers which have only a `startupProbe` are marked `ready=true`.
This doesn't make sense.

This commit only considers readiness if the container is considered to
have "started", which leaves `ready=false` while starting up.

/kind bug

Fixes #89995

**Special notes for your reviewer**:

I am NOT super familiar with this code area.  I dug around to find this and empirically it seems to work. 

**Does this PR introduce a user-facing change?**:

```release-note
Containers which specify a `startupProbe` but not a `readinessProbe` were previously considered "ready" before the `startupProbe` completed, but are now considered "not-ready".
```

### CODE REVIEW

**Comment by matthyx** [comment]
Thanks Tim. Let me have a look later today...

**Comment by matthyx** [comment]
Tests are fine, which show the poor coverage of these edge cases...
Looks good, but I will add some tests in a follow-up PR.
/lgtm
/hold
Thanks!

**Comment by matthyx** [comment]
* you can cancel the hold when you are ready.

**Comment by matthyx** [comment]
Once merged we should look at the serial e2e test results as there is some coverage there.

**Review by matthyx — APPROVED** [review]

File: pkg/kubelet/prober/prober_manager.go [hunk 1]
```diff
@@ -261,6 +249,20 @@ func (m *manager) UpdatePodStatus(podUID types.UID, podStatus *v1.PodStatus) {
 			started = !exists
 		}
 		podStatus.ContainerStatuses[i].Started = &started
+
+		if started {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/prober_manager.go:253]: If there is no way container can be ready, but not started, perhaps the status can be stored in a single variable instead of two independent flags?

Comment (matthyx) [reply pkg/kubelet/prober/prober_manager.go:253]: No, there are more ramifications... I think it's clearer to keep both even just for the sake of explanation and ease of testing.

Comment (thockin) [reply pkg/kubelet/prober/prober_manager.go:253]: Do you mean in the API or in this function?

The API has shipped, we don't want to change that.

This commit was designed to be surgical - move the code block, add an `if`.  Further cleanup may be possible, but it seems low-value to me - this code is pretty simple to read?

**Comment by thockin** [comment]
/retest

verify failed after 2 hours and a LOT of logs

File: pkg/kubelet/prober/prober_manager.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/prober_manager.go:253]: I meant API =). I commented before looked into it and understand it's seems to be hard to change. The only benefit is guaranteed consistency of the status. This method is ok. But there are more. For instance, this: https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/kubelet/status/status_manager.go#L241 where `Ready` and `Started` are set seemingly independently.

Comment (thockin) [reply pkg/kubelet/prober/prober_manager.go:253]: That case (I think) is after readiness has been considered at a lower level, but I admit I am not 100% confident in this code area any more :(

**Comment by matthyx** [comment]
@thockin what's the difference between your initial commit and the force-pushed one? I don't see it...

**Comment by matthyx** [comment]
@SergeyKanzhelev there are 2 states, ready and started, and they represent 2 different notions that are monitored by different probes... started is a permanent state (once startupProbe succeeds it never changes) whereas ready depends on the result of the readinessProbe.

Please refer to the KEP (https://github.com/kubernetes/enhancements/issues/950) or my lightning talk on the subject: https://youtu.be/wO1uy9QKNHQ

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev there are 2 states, ready and started, and they represent 2 different notions that are monitored by different probes... started is a permanent state (once startupProbe succeeds it never changes) whereas ready depends on the result of the readinessProbe.

Totally with you on this. My comment was that there are three acceptable states represented with four possible combinations of flags. Which led to this Ready, but not Started issue.  And there are seems to be other places which set these flags independently without ensuring that container is not ending up in un-acceptable state. 

I'm pretty sure the `Ready` flag was already defined when `Started` was introduced. So it wasn't much of a choice for redesigning flags. I made my comment before looking deeper into  changes needed to forbid this un-acceptable state in compile time.

Also, great lightning talk.

**Comment by matthyx** [comment]
> seems to be other places which set these flags independently without ensuring that container is not ending up in un-acceptable state.

Good point, should we create another issue, or put everything on #89995 - in that case this PR should not "fix" it alone.

**Comment by heckad** [comment]
Recently, I noticed that pods without a readiness probe continue to receive traffic while they are in terminating status. In this regard, I propose to add new state for startUp probe and make liveness and readiness probs work **only** for ` running` state. If our pods in terminating or startUp state, they are should be not ready also if readiness probe didn't set. Olso add startUp probe an excellent start to add a new feature which should run depended pods only when pod started. For example, if bd not in startUp state, we don't start pods dependent from DB.

Why is it so important to solve this problem?
Because the readiness probe is responsible not only for sending traffic but also for making a decision when stopping old pods, if we don't have readiness probe then Kubernetes stopping old pods when new just start starting. Because I propose to add a new state and make readiness and licenses probes available only for running pods, not for pods in startUp state or in terminating states.

Thanks for your attention!

**Comment by matthyx** [comment]
> I noticed that pods without a readiness probe continue to receive traffic while they are in terminating status.

This has always been the case... when you don't specify a readinessProbe, you assume an always ready state.

> I propose to add a new state and make readiness and liveness probes available only for running pods, not for pods in starting or terminating states.

This is clearly a different use case than what the startupProbe was designed to solve. If you feel strong enough you can take the point and start a KEP to modify the handling of the shutdown phase...

However, now that we have the startupProbe, people could almost do without a readinessProbe (if they don't care about removing/adding back the pod to the load balancer pool) if that case had been covered. Then it could be a feature (or follow up) of my KEP...

What do you think @thockin (from a philosophical point of view) ?

**Comment by heckad** [comment]
> This has always been the case... when you don't specify a readinessProbe, you assume an always ready state.

Yes, I propose to change this behaviour. A pod should be ready only in running state and readiness probe should manage ready state also only for running state. In startUp and terminating state pod should be not ready. I think this is bad behaviour when requests can go to pods wich starting work and completing work. How do you think this is a good propose? This propose can solve many problems.

**Comment by matthyx** [comment]
> In startUp and terminating state pod should be not ready. I think this is bad behaviour when requests can go to pods wich starting work and completing work.

According to this page, it should not be the case: https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

Even if the pod is still "ready" no new traffic should go to it... so if it's something you can reproduce I suggest you fill a bug report (which is something I can help you with).

**Comment by heckad** [comment]
> Even if the pod is still "ready" no new traffic should go to it...

What mean "ready" for pods in termination state?

**Comment by matthyx** [comment]
> What mean "ready" for pods in termination state?

I need to check in the kubelet code...

**Comment by thockin** [comment]
It was just a rebase - trying to unstick tests
