### PR TITLE
fix rbd info when return warning information

### LINKED ISSUE #75581: rbd info output parse error
**What happened**:
The rbd plugin use "rbd info" error:
```
/ # rbd info volume-9b7dc9e1-dc65-42ef-9506-c54d137ba305 -m 10.66.166.39:6789,10
.66.166.56:6789,10.66.167.144:6789,10.66.168.23:6789,10.66.169.142:6789 --pool v
olumes --id lvs01cinder --key=xxxxx== --format=
json
2019-03-22 07:27:34.258083 7fb67ff26d40 -1 did not load config file, using default settings.
2019-03-22 07:27:34.263422 7fb67ff26d40 -1 Errors while parsing config file!
2019-03-22 07:27:34.263427 7fb67ff26d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.263432 7fb67ff26d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.263433 7fb67ff26d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.264838 7fb67ff26d40 -1 Errors while parsing config file!
2019-03-22 07:27:34.264846 7fb67ff26d40 -1 parse_file: cannot open /etc/ceph/ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.264847 7fb67ff26d40 -1 parse_file: cannot open ~/.ceph/ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.264847 7fb67ff26d40 -1 parse_file: cannot open ceph.conf: (2) No such file or directory
2019-03-22 07:27:34.290166 7fb67ff26d40 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.lvs01cinder.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory
{"name":"volume-9b7dc9e1-dc65-42ef-9506-c54d137ba305","size":1073741824,"objects":256,"order":22,"object_size":4194304,"block_name_prefix":"rbd_data.fef50c2eefb203","format":2,"features":["layering"],"flags":[]}, invalid character '-' after top-level value
```
The messages before and after json result is warning string and no effect to rbd info, but it is effect to parse the output. So the kubernetes will failed:
```
Warning   VolumeResizeFailed   PersistentVolumeClaim   Error expanding volume "shentao/cindersimple" of plugin kubernetes.io/rbd : rbd info failed, error: can not get image size info volume-9b7dc9e1-dc65-42ef-9506-c54d137ba305: 2019-03-22 06:24:58.972703 7f0391868d40 -1 did not load config file, using default settings.
```
**What you expected to happen**:
Kubernete no failed and errors

**How to reproduce it (as minimally and precisely as possible)**:
Remove the config file

### PR DESCRIPTION
**Pull request by smileusd**
**What type of PR is this?**
/kind bug
**What this PR does / why we need it:**
fix https://github.com/kubernetes/kubernetes/issues/75581
This pr clean rbd info command output of warning information. If not fix this, provider will parse the output error.
**Special notes for your reviewer:**
/sig storage
**Does this PR introduce a user-facing change?:**
```release-note
Ceph RBD volume plugin now does not use any keyring (/etc/ceph/ceph.client.lvs01cinder.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin) for authentication. Ceph user credentials must be provided in PersistentVolume objects and referred Secrets.
```

### CODE REVIEW

**Comment by smileusd** [comment]
Has anyone to review this?

File: pkg/volume/rbd/rbd_util.go [hunk 1]
```diff
@@ -727,7 +727,12 @@ func getRbdImageSize(output []byte) (int, error) {
 	info := struct {
 		Size int64 `json:"size"`
 	}{}
-	if err := json.Unmarshal(output, &info); err != nil {
+	startJson := strings.LastIndex(string(output), "{")
+	endJson := strings.LastIndex(string(output), "}")
+	if startJson > endJson {
+		return 0, fmt.Errorf("can't find json result")
+	}
+	if err := json.Unmarshal([]byte(string(output)[startJson: endJson+1]), &info); err != nil {
```
Comment (cofyc) [inline pkg/volume/rbd/rbd_util.go]: This way to filter out warning infos is too hacky. And `mount.Exec` does not provide a method to filter out stderr stream too.
How about using `-c /dev/null` to override ceph configuration, then `rbd` command will not search ceph configuration file from the host? So no warnings will be emitted.
Actually, for kubelet rbd plugin, all required information to access ceph cluster are provided from command line arguments.

Comment (cofyc) [reply pkg/volume/rbd/rbd_util.go]: `rbd` command in this plugin will search and use Ceph configuration if it exists on the host is a side-effect, it is not documented and officially supported I guess. I think we should remove it.

cc @rootfs and @jsafrane what's your opinion?

Comment (jsafrane) [reply pkg/volume/rbd/rbd_util.go]: I don't understand Ceph enough to judge if it's a common thing to configure its client via config in /etc/ on every node. Are all options really configurable via Kubernetes PV? If we remove parsing of /etc/, how likely is some cluster going to break?

There should be at least some a warning in release notes + deprecation period.

Comment (cofyc) [reply pkg/volume/rbd/rbd_util.go]: It is not a common thing to configure its client via config in `/etc` on every node. It's hard to maintain (need to copy configurations to every new node), and easy to make mistakes. All options are configurable via Kubernetes PV and client arguments will override configurations in `/etc/ceph`.  

In fixing this bug, I don't it is necessary to warn users that we don't support reading configurations from `/etc/ceph` because we have all required arguments in the command line:

https://github.com/kubernetes/kubernetes/blob/ea0099103ea5532b49f5a9e5570d44f33b24bd67/pkg/volume/rbd/rbd_util.go#L702-L704

Comment (smileusd) [reply pkg/volume/rbd/rbd_util.go]: @cofyc @jsafrane Thank you and I make sense. If required arguments in the command line in code at beginning, it will not break exist cluster. And if we make sure all the arguments of the command will override the options of config file, it is safety to do following @cofyc says. But I will also make annotations to attention user not necessary to config  `/etc/ceph` in code.

Comment (Symbianx) [reply pkg/volume/rbd/rbd_util.go]: @cofyc I just came across this issue and I did a quick test in my environment, your suggestion to use `-c /dev/null` will still output the following line to stderr:
> 2019-06-14 11:23:20.741527 7f1d737e60c0 -1 auth: unable to find a keyring on /etc/ceph/ceph.client.kube-admin.keyring,/etc/ceph/ceph.keyring,/etc/ceph/keyring,/etc/ceph/keyring.bin,: (2) No such file or directory

If you go that way you should also include `-k /dev/null -K /dev/null` to point the keyrings to the empty file.

Comment (Ranler) [reply pkg/volume/rbd/rbd_util.go]: touch a empty `/etc/ceph/ceph.conf` and `/etc/ceph/keyring`  files should be work for take ceph client warning message away.

Comment (smileusd) [reply pkg/volume/rbd/rbd_util.go]: @Symbianx You are right, but -K will cover the secret, i will change with -k /dev/null to cover it.

**Comment by smileusd** [comment]
@cofyc @jsafrane PTAL

**Comment by cofyc** [comment]
/lgtm

I think this makes sense because we don't need to search keyring file because we provided the user and secret via `--id` and `--key` flags.

**Comment by jsafrane** [comment]
@smileusd, can you please add release note to the first comment of this PR, so Ceph users are aware of this change?

**Comment by smileusd** [comment]
@jsafrane updated.
