### PR TITLE
Fix flapping pod.status.resourceClaimStatuses

### LINKED ISSUE #138407: [DRA] pod.status.resourceClaimStatuses entries are flapping
### What happened?

I have a Pod that uses two ResourceClaimTemplates that is stuck in pending for various (irrelevant) reasons. I noticed that the status.resourceClaimStatuses field was flapping between entries with the the RCs created for each of the templates:

```console
$ kubectl get pods vllm-opt-125m-6b6f655ddb-8zb4p -w -o custom-columns="NAME:.metadata.name,RV:.metadata.resourceVersion,CLAIM STATUSES:.status.resourceClaimStatuses[*].name"
NAME                             RV                    CLAIM STATUSES
vllm-opt-125m-6b6f655ddb-8zb4p   1776286634735007008   model
vllm-opt-125m-6b6f655ddb-8zb4p   1776286634832495008   model
vllm-opt-125m-6b6f655ddb-8zb4p   1776286634891151008   gpu
vllm-opt-125m-6b6f655ddb-8zb4p   1776286634934959008   model
vllm-opt-125m-6b6f655ddb-8zb4p   1776286634986255008   gpu
vllm-opt-125m-6b6f655ddb-8zb4p   1776286635035711008   model
vllm-opt-125m-6b6f655ddb-8zb4p   1776286635087583008   gpu
vllm-opt-125m-6b6f655ddb-8zb4p   1776286635134271008   model
vllm-opt-125m-6b6f655ddb-8zb4p   1776286635186143008   gpu
vllm-opt-125m-6b6f655ddb-8zb4p   1776286635235007008   model
```

This shouldn't be happening. Once the resource claims are created, they should be added there and it should remain stable.

### What did you expect to happen?

Once the resource claims are created, they should be added there and it should remain stable. Here's an example of a Pod that has reached `Running` state:

```console
$ kubectl get pods vllm-gemma-4-e2b-it-586d595ffc-85k4h -w -o custom-columns="NAME:.metadata.name,RV:.metadata.resourceVersion,CLAIM STATUSES:.status.resourceClaimStatuses[*].name"
NAME                                   RV                    CLAIM STATUSES
vllm-gemma-4-e2b-it-586d595ffc-85k4h   1776276444200351023   gpu,model
```

### How can we reproduce it (as minimally and precisely as possible)?

I suspect this happens whenever a pod is in pending and uses multiple ResourceClaims, but I am not sure. I have a unit test that reproduces it, but not an e2e test. I will submit a PR with the unit test and a fix.

### Anything else we need to know?

/wg device-management
/sig node

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.3
Kustomize Version: v5.7.1
Server Version: v1.35.1-gke.1396002
```

With the DRAConsumableCapacity feature gate enabled.
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by johnbelamaric**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
resourceclaimcontroller: fix incorrect SSA apply in syncPod method

The ResourceClaimController's syncPod method only includes new resource claims in the server-side apply, not existing claims. Since this controller is the owning fieldManager, SSA removes the missing existing keys. This results in flapping between claims when more than one claim is assigned to the Pod.

This fix includes the existing claims in the SSA request.

#### Which issue(s) this PR is related to:
Fixes #138407 

#### Special notes for your reviewer:
An alternative would be to change `handleClaims` to not just return when it finds an existing claim, but instead add it to the list of claims. This would require changing the signature and meaning of the `newPodClaims`.

Google Gemini was used in preparing this PR.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where Pod `.status.resourceClaimStatuses` could flap between partial lists of claims, when multiple claims were used in the pod.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/resourceclaim/controller.go [hunk 1]
```diff
@@ -861,10 +861,27 @@ func (ec *Controller) syncPod(ctx context.Context, namespace, name string) error
...
+		mergedStatuses := make(map[string]string)
+		for _, status := range pod.Status.ResourceClaimStatuses {
+			if status.ResourceClaimName != nil {
+				mergedStatuses[status.Name] = *status.ResourceClaimName
+			}
+		}
 		for podClaimName, resourceClaimName := range newPodClaims {
-			statuses = append(statuses, corev1apply.PodResourceClaimStatus().WithName(podClaimName).WithResourceClaimName(resourceClaimName))
+			mergedStatuses[podClaimName] = resourceClaimName
+		}
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/138408/pull-kubernetes-linter-hints/2044542293263781888:

mapsloop: Replace m[k]=v loop with maps.Copy (modernize)
			mergedStatuses[podClaimName] = resourceClaimName

**Review by pohly — COMMENTED** [review]
Looks correct to me.

I suppose one reason why we haven't noticed this before is that `syncPod` only starts flapping when it doesn't succeed with setting the entire status in one go (for example, missing template).

Maybe this can be used to write an E2E test: one pod referencing two different templates, of which only one exists. Once that template has been processed, create the next template.

File: pkg/controller/resourceclaim/controller.go (hunk 1 above)
Comment (johnbelamaric) [reply pkg/controller/resourceclaim/controller.go]: Update pushed.

> Maybe this can be used to write an E2E test: one pod referencing two different templates, of which only one exists. Once that template has been processed, create the next template.

@pohly e2e test for this seems like overkill, wdyt?

Comment (pohly) [reply pkg/controller/resourceclaim/controller.go]: I suppose the fake unit test is emulating SSA closely enough, so we can skip e2e or integration test.

A specific flow which triggers this would have been nice to have because it sheds some light on what the actual circumstances have to be (the "one template missing" from my review comment).

**Comment by pohly** [comment]
This fixes a bug, so we need a release note entry.

File: pkg/controller/resourceclaim/controller_test.go [hunk 2]
```diff
@@ -780,6 +818,14 @@ func TestSyncHandler(t *testing.T) {
 				t.Fatalf("expected error, got none")
 			}
 
+			if tc.name == "flapping-resourceclaim-statuses" {
+				assert.Len(t, appliedPatches, 1, "should have applied status once")
+				// The patch should contain both claims if the bug is fixed.
```
Comment (troychiu) [inline pkg/controller/resourceclaim/controller_test.go]: Is this comment still effective?

**Comment by lmktfy** [comment]
Changelog suggestion
```diff
-Fixed a bug where pod.status.resourceClaimStatuses would flap between partial lists of claims when multiple claims are used in the pod.
+Fixed a bug where Pod `.status.resourceClaimStatuses` could flap between partial lists of claims, when multiple claims were used in the pod.
```

File: pkg/controller/resourceclaim/controller_test.go (hunk 2 above)
Comment (johnbelamaric) [reply pkg/controller/resourceclaim/controller_test.go]: fixed

**Comment by johnbelamaric** [comment]
> Changelog suggestion
> 
> ```diff
> -Fixed a bug where pod.status.resourceClaimStatuses would flap between partial lists of claims when multiple claims are used in the pod.
> +Fixed a bug where Pod `.status.resourceClaimStatuses` could flap between partial lists of claims, when multiple claims were used in the pod.
> ```

Thanks @lmktfy, updated.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

What is the priority, i.e. how likely is this to happen? It seems a bit unlikely to me, but it's a bug and thus worth backporting to Kubernetes >= 1.34 (first GA)?

**Comment by johnbelamaric** [comment]
> What is the priority, i.e. how likely is this to happen? It seems a bit unlikely to me, but it's a bug and thus worth backporting to Kubernetes >= 1.34 (first GA)?

It's not clear. I think it also does eventually resolve. I don't think it stopped. my pods from scheduling.

**Comment by troychiu** [comment]
I took a closer look at the bug and suspect the issue is also caused by a cache mismatch, specifically because https://github.com/kubernetes/kubernetes/blob/03779bbd00da25c7fcd03711ddfe466a3322e1d7/pkg/controller/resourceclaim/controller.go#L943 uses the standard informer lister (`claimLister`) instead of the mutation cache (`claimCache`).

Here is the suspected flow that causes the flapping:
1. Initially, the controller successfully creates claims for both templates and updates the Pod status with both names.
2. In a subsequent reconciliation, if the controller's informer cache is stale and cannot find the claim for **Template A**, it falls through and tries to create one. In https://github.com/kubernetes/kubernetes/blob/03779bbd00da25c7fcd03711ddfe466a3322e1d7/pkg/controller/resourceclaim/controller.go#L984, it calls `findPodResourceClaim`, which **does** use the mutation cache. It finds the claim and adds it to the `newPodClaims` map.
4. Because only Template A was added to `newPodClaims` in this run, the controller override the status with claim A.
5. In the next round, the controller sees that **Template B** is missing from the status, finds it in the mutation cache, and applies it—causing **Template A** to be removed.

**Comment by pohly** [comment]
> I don't think it stopped my pods from scheduling.

Hmm, that is a bit odd. With two ResourceClaimTemplate references I'd expect it to flip back and forth forever.

> I took a closer look at the bug and suspect the issue is also caused by a cache mismatch, specifically because [...]
> In a subsequent reconciliation, if the controller's informer cache is stale and cannot find the claim for Template A, it falls through and tries to create one.

Switching that to use `claimCache` might not necessarily be better: the claim might have been created, thus be in `claimCache`, but then might have been removed already. There's no guarantee either that this create+delete gets reported through the normal informer. So when using a claim from `claimCache`, then code would have to do a GET to verify that the claim really exists because if it doesn't and points to a non-existent ResourceClaim in the status, there might not be any automatic recovery: the controller itself might never look at the Pod again (not sure!).

If it plays it safe and instead relies on the informer cache, then it might encounter a false negative (existing ResourceClaim ignored), but that merely errs on the side of safety and should not have any long-lasting consequences: the extra ResourceClaim will be unused and eventually gets garbage-collected together with the Pod.

The main question is: how often does this happen? If a reconcile runs into this race often, we could end up with quite a lot of dangling  ResourceClaims.

**Comment by johnbelamaric** [comment]
/hold

Let me investigate a bit more; I will have time later today. @troychiu feel free do so as well, and push a PR to my branch if you find something.

**Comment by johnbelamaric** [comment]
@pohly I am not able to reproduce anymore. But it's clearly a bug we should fix. At this point, without some real world feedback, I would suggest not back porting.

/hold cancel

**Comment by pohly** [comment]
> Maybe this can be used to write an E2E test: one pod referencing two different templates, of which only one exists. Once that template has been processed, create the next template.

I [tried that](https://github.com/kubernetes/kubernetes/pull/138504). The controller aborts syncing the pod after creating the first ResourceClaim because the second template is missing *without* updating the pod status. That makes sense, there's no need to write a partial status. But if the controller always does a single Apply with all statuses, how could @johnbelamaric ever get his pod into a state with partial status? That remains a mystery.

**Comment by troychiu** [comment]
@johnbelamaric mentioned he or some folks ran into this again in older releases. I am going to back port this PR.

**Comment by pohly** [comment]
In the cherry-pick PRs, please explain why the cherry-picks meet the cherry-pick criteria (https://github.com/kubernetes/community/blob/main/contributors/devel/sig-release/cherry-picks.md).

**Comment by troychiu** [comment]
@pohly Updated the PRs. Thanks for the heads-up.

**Comment by pohly** [comment]
> permanently flaps between subsets of the pod's claims, causing data loss in the status and an endless write loop against the API server

Is this really permanent? Have you been able to reproduce this? I don't think we identified the actual trigger for this.

"causing data loss in the status" is a bit too alarming: the data is not lost forever.

**Comment by troychiu** [comment]
> "causing data loss in the status" is a bit too alarming: the data is not lost forever.

right. Updated

**Comment by johnbelamaric** [comment]
> Is this really permanent? Have you been able to reproduce this? I don't think we identified the actual trigger for this.

Not sure. But I never saw it actually resolve itself. I suspected it may eventually but never saw that happen. I haven't reproduced this since, but we got a live customer bug report where they are seeing this exact issue in 1.35 so it's not a fluke.
