### PR TITLE
Reduce Azure API calls by replacing the current backoff retry with SDK's backoff

### LINKED ISSUE #70865: Azure cloud provider is retrying too aggressive
**What happened**:

When something unexpected happened (e.g. hitting Azure API throttling) , Azure cloud provider would retry with a configurable exponential backoff.  While this seems work for processing various unexpected errors, it's actually sending too much requests to Azure API.

The reason is Azure Go SDK also includes an internal backoff, e.g. [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/rp.go#L28) and [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/async.go#L184). The SDK would retry 3 attempts for compute APIs and 5 attempts for storage APIs when following HTTP response are got:

- http.StatusRequestTimeout,      // 408

- http.StatusTooManyRequests,     // 429
- http.StatusInternalServerError, // 500
- http.StatusBadGateway,          // 502
- http.StatusServiceUnavailable,  // 503
- http.StatusGatewayTimeout,      // 504

That means every failed `AttachDisk` operation would invoke `(1+6)*3 = 21` API calls (suppose cloudProviderBackoffRetries is set 6 in cloud config).

We should really avoid those two-layer backoff retries by 

- (1) either disable SDK's backoff and only keep cloud provider's backoff retry
- (2) or, remove cloud provider's backoff and only use SDK's backoff instead

According to [Throttling Resource Manager requests](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits#waiting-before-sending-next-request), when the request limits are reached, clients should honor **Retry-After** value in the response header:

> When you reach the request limit, Resource Manager returns the **429** HTTP status code and a **Retry-After** value in the header. The **Retry-After** value specifies the number of seconds your application should wait (or sleep) before sending the next request. If you send a request before the retry value has elapsed, your request isn't processed and a new retry value is returned.

Since this header has already been handled within SDK's backoff retries, (2) is our preferred way to reduce the API calls.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig azure
/assign

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

When something unexpected happened (e.g. hitting Azure API throttling) , Azure cloud provider would retry with a configurable exponential backoff.  While this seems work for processing various unexpected errors, it's actually sending too much requests to Azure API.

The reason is Azure Go SDK also includes an internal backoff, e.g. [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/rp.go#L28) and [here](https://github.com/Azure/go-autorest/blob/master/autorest/azure/async.go#L184). The SDK would retry 3 attempts for compute APIs and 5 attempts for storage APIs when following HTTP response are got:

- http.StatusRequestTimeout,      // 408

- http.StatusTooManyRequests,     // 429
- http.StatusInternalServerError, // 500
- http.StatusBadGateway,          // 502
- http.StatusServiceUnavailable,  // 503
- http.StatusGatewayTimeout,      // 504

That means every failed `AttachDisk` operation would invoke `(1+6)*3 = 21` API calls (suppose cloudProviderBackoffRetries is set 6 in cloud config).

We should really avoid those two-layer backoff retries by 

- (1) either disable SDK's backoff and only keep cloud provider's backoff retry
- (2) or, remove cloud provider's backoff and only use SDK's backoff instead

According to [Throttling Resource Manager requests](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits#waiting-before-sending-next-request), when the request limits are reached, clients should honor **Retry-After** value in the response header:

> When you reach the request limit, Resource Manager returns the **429** HTTP status code and a **Retry-After** value in the header. The **Retry-After** value specifies the number of seconds your application should wait (or sleep) before sending the next request. If you send a request before the retry value has elapsed, your request isn't processed and a new retry value is returned.

Since this header has already been handled within SDK's backoff retries, (2) is our preferred way to reduce the API calls.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70865

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
New Azure cloud provider option 'cloudProviderBackoffMode' has been added to reduce Azure API retries. Candidate values are:

* default (or empty string): keep same with before.
* v2: only backoff retry with Azure SDK with fixed exponent 2.
```

/sig azure
/cc @khenidak @andyzhangx

### CODE REVIEW

**Comment by feiskyer** [comment]
Since this change would take effect on all Azure API calls, we need to run enough tests before merging it. I'm setting those e2e tests flows in [cloud-provier-azure](https://github.com/kubernetes/cloud-provider-azure) repo.

Meanwhile, any comments or suggestions are welcomed.

/cc @brendandburns  @khenidak @andyzhangx 

/hold

File: pkg/cloudprovider/providers/azure/azure.go [hunk 1]
```diff
@@ -264,17 +259,44 @@ func NewCloud(configReader io.Reader) (cloudprovider.Interface, error) {
...
+		// Assign backoff defaults if no configuration was passed in
+		if config.CloudProviderBackoffRetries == 0 {
+			config.CloudProviderBackoffRetries = backoffRetriesDefault
+		}
+		if config.CloudProviderBackoffDuration == 0 {
+			config.CloudProviderBackoffDuration = backoffDurationDefault
+		}
+		// Log warning for deprecated options.
+		if config.CloudProviderBackoffExponent != 0 {
+			klog.Warning("Azure cloud provider config 'cloudProviderBackoffExponent' has been deprecated. 2 is always used as the backoff exponent.")
```
Comment (brendandburns) [inline pkg/cloudprovider/providers/azure/azure.go]: I don't think we can do this, we should print the deprecation warning, but use the user supplied value...

File: pkg/cloudprovider/providers/azure/azure.go [hunk 2]
```diff
@@ -264,17 +259,44 @@ func NewCloud(configReader io.Reader) (cloudprovider.Interface, error) {
...
+		}
+		if config.CloudProviderBackoffJitter != 0 {
+			klog.Warning("Azure cloud provider config 'cloudProviderBackoffJitter' has been deprecated. 2 is always used as the backoff exponent.")
```
Comment (brendandburns) [inline pkg/cloudprovider/providers/azure/azure.go]: This error is incorrect (copy and pasted...) and also, I think we still need to obey the user provided value.

**Comment by brendandburns** [comment]
I'm a little bit worried about taking out the manual configuration knobs and deferring entirely to the SDK.

I think that we should both maintain the existing behavior, and implement the new one, and switch between them based on a flag.

Since this is a big change, we need to maintain backward/rollback as an option for clusters without reverting the Kubernetes version.

File: pkg/cloudprovider/providers/azure/azure.go (hunk 1 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure.go]: I do think that's the right way, but we couldn't do it because the exponent is fixed `2` within SDK.

File: pkg/cloudprovider/providers/azure/azure.go (hunk 2 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure.go]: oops, my mistake

**Comment by feiskyer** [comment]
> I think that we should both maintain the existing behavior, and implement the new one, and switch between them based on a flag. 
> Since this is a big change, we need to maintain backward/rollback as an option for clusters without reverting the Kubernetes version.

Reasonable. Since there are two layers of retrying today, we should provide a way to disable either SDK's retry or cloud provider's retry.

File: pkg/cloudprovider/providers/azure/azure.go [hunk 3]
```diff
@@ -59,6 +59,9 @@ const (
 	vmTypeVMSS     = "vmss"
 	vmTypeStandard = "standard"
 
+	backoffModeDefault = "default"
+	backoffModeMinimum = "minimum"
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure.go]: maybe `v2` is better.

File: pkg/cloudprovider/providers/azure/azure.go [hunk 4]
```diff
@@ -118,6 +121,12 @@ type Config struct {
 	CloudProviderBackoffDuration int `json:"cloudProviderBackoffDuration" yaml:"cloudProviderBackoffDuration"`
 	// Backoff jitter
 	CloudProviderBackoffJitter float64 `json:"cloudProviderBackoffJitter" yaml:"cloudProviderBackoffJitter"`
+	// Backoff mode, options are minimum and default.
+	// * default means two-layer backoff retrying, one in the cloud provider and the other in the Azure SDK.
+	// * minimum means only backoff in the Azure SDK is used. In such mode, CloudProviderBackoffDuration and
+	//   CloudProviderBackoffJitter are omitted.
+	// "default" will be used if not specified.
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure.go]: I would suggest to use sdk retry flavor by default, we have 3 months to test this retry change, and if we don't change the original retry mechanism, I doubt whether aks or acs-engine will use sdk retry flavor, the new retry machanism will never be used.

File: pkg/cloudprovider/providers/azure/azure_backoff.go [hunk 5]
```diff
@@ -134,6 +180,28 @@ func (az *Cloud) CreateOrUpdateSGWithRetry(service *v1.Service, sg network.Secur
...
+				// Invalidate the cache right after updating
+				az.lbCache.Delete(*lb.Name)
+			} else if resp != nil {
+				return fmt.Errorf("HTTP response %q", resp.Status)
+			}
+		}
+		return err
+	}
+
+	return az.CreateOrUpdateLBWithRetry(service, lb)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_backoff.go]: So `CreateOrUpdateLBWithRetry` may be changed to `createOrUpdateLBWithRetry` since it's not external now.

File: pkg/cloudprovider/providers/azure/azure_backoff.go [hunk 6]
```diff
@@ -151,6 +219,25 @@ func (az *Cloud) CreateOrUpdateLBWithRetry(service *v1.Service, lb network.LoadB
...
+		if err != nil {
+			az.Event(service, v1.EventTypeWarning, "ListLoadBalancers", err.Error())
+			klog.Errorf("LoadBalancerClient.List(%v) failure with err=%v", az.ResourceGroup, err)
+			return nil, err
+		}
+		klog.V(2).Infof("LoadBalancerClient.List(%v) success", az.ResourceGroup)
+		return allLBs, nil
+	}
+
+	return az.ListLBWithRetry(service)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_backoff.go]: change to `listLBWithRetry`?

File: pkg/cloudprovider/providers/azure/azure_backoff.go [hunk 7]
```diff
@@ -240,6 +387,27 @@ func (az *Cloud) DeletePublicIPWithRetry(service *v1.Service, pipResourceGroup s
...
+				// Invalidate the cache right after updating
+				az.lbCache.Delete(lbName)
+			} else if resp != nil {
+				return fmt.Errorf("HTTP response %q", resp.Status)
+			}
+		}
+		return err
+	}
+
+	return az.DeleteLBWithRetry(service, lbName)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_backoff.go]: same here.

File: pkg/cloudprovider/providers/azure/azure.go (hunk 4 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure.go]: @brendandburns @khenidak What do you think about the default backoff mode?

File: pkg/cloudprovider/providers/azure/azure.go (hunk 3 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure.go]: @brendandburns @khenidak What do you think about the new backoff mode name? I don't think "minimum" is good enough. What's your suggestion?

File: pkg/cloudprovider/providers/azure/azure.go (hunk 4 above)
Comment (khenidak) [reply pkg/cloudprovider/providers/azure/azure.go]: I don't think we should maintain two modes. Do you see a usecase for maintaining the old mode?

**Review by khenidak — CHANGES_REQUESTED** [review]
Just one comment really. I think we are taking on a lot of tech debt maintaining two modes of `retry behavior`. From user stand point the cluster will behave the same. We should switch to the new mode, remove all the `retry wrappers` around the SDK and let the SDK do the work. 

We can also emit a warning message  as if we found that user is still supplying values for the old backoff style.

File: pkg/cloudprovider/providers/azure/azure.go (hunk 4 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure.go]: per @brendandburns suggestion [here](https://github.com/kubernetes/kubernetes/pull/70866#issuecomment-438447463). 

> I'm a little bit worried about taking out the manual configuration knobs and deferring entirely to the SDK.

> I think that we should both maintain the existing behavior, and implement the new one, and switch between them based on a flag.

> Since this is a big change, we need to maintain backward/rollback as an option for clusters without reverting the Kubernetes version.

**Comment by andyzhangx** [comment]
LGTM 
@khenidak @brendandburns any comments on this?
The plan is to keep the old retry method, and use sdk retry methond in aks-engine by default.
