### PR TITLE
kubelet: set failed phase during graceful shutdown

### LINKED ISSUE #104531: Graceful Node Shutdown regression in 1.21 → 1.22
#### What happened:

Shutdown a node gracefully. E.g. with `systemctl reboot`.

#### What you expected to happen:

Expected to see pods being evicted, and pods being started on another nodes.

#### How to reproduce it (as minimally and precisely as possible):

Let a deployment create one pod, configure Graceful Node Shutdown as described in https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/, then just `systemctl reboot` that node. Then, the pod will get a state of `Terminated` or `Completed`, but no new pod is being created and scheduled on a different node. Then, when the node comes back, the terminated pod stays in such a state:

```
home-assistant-5dfcb44d74-rg2zs                       1/1     Terminated   2          30m   10.112.0.69    k8s-node13   <none>           <none>
```

Effectively, the pod is running on the node which has been rebooted gracefully, but is in a `Terminated` state.

#### Anything else we need to know?:

This worked as expected in v1.21

#### Environment:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/arm"}
```
- Cloud provider or hardware configuration: bare metal
- OS (e.g: `cat /etc/os-release`):
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
# uname -a
Linux k8s-node07 5.10.0-8-armmp #1 SMP Debian 5.10.46-4 (2021-08-03) armv7l GNU/Linux
```
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
kube-router
- Others:

### PR DESCRIPTION
**Pull request by bobbypage**
Revert to previous behavior in 1.21/1.20 of setting pod phase to failed
during graceful node shutdown.

Setting pods to failed phase will ensure that external controllers that
manage pods like deployments will create new pods to replace those that
are shutdown. Many customers have taken a dependency on this behavior
and it was breaking change in 1.22, so this change reverts back to the
previous behavior.

Signed-off-by: David Porter <david@porter.me>

#### What type of PR is this?

/kind bug

/kind regression

#### Which issue(s) this PR fixes:

Fixes #104531

#### Special notes for your reviewer:

As discussed in https://github.com/kubernetes/kubernetes/issues/104531#issuecomment-982763592, the plan is to revert back to previous behavior in 1.22 and 1.23 and make this option configurable in 1.24. The change was introduced in [3eadd1a#diff-d0efebc6b30989428cd9bc3f04bb15cd75134e38ad38ce21a648fed69389c7aeL273](https://github.com/kubernetes/kubernetes/commit/3eadd1a9ead7a009a9abfbd603a5efd0560473cc#diff-d0efebc6b30989428cd9bc3f04bb15cd75134e38ad38ce21a648fed69389c7aeL273)

For master branch (1.24) first step will be to revert to previous behavior. As a followup we will introduce a new kubelet option to make this configurable as discussed on the issue. 

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.22 regression to revert graceful node shutdown to match 1.21 behavior of setting pods that have not yet successfully completed to "Failed" phase if the GracefulNodeShutdown feature is enabled in kubelet. The GracefulNodeShutdown feature is beta and must be explicitly configured via kubelet config to be enabled in 1.21+. This changes 1.22 and 1.23 behavior on node shutdown to match 1.21. If you do not want pods to be marked terminated on node shutdown in 1.22 and 1.23, disable the GracefulNodeShutdown feature.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
1.22 cherrypick - https://github.com/kubernetes/kubernetes/pull/106899
1.23 cherrypick - https://github.com/kubernetes/kubernetes/pull/106900/

**Comment by bobbypage** [comment]
> I know this is up against the 1.22 cherry-pick deadline of 12/10, but could a test assertion be added to an existing test of the graceful node shutdown behavior to verify this is taking effect (even if it's not in a full e2e)

Updated with PR with corresponding e2e test. The test change reverts a part of https://github.com/kubernetes/kubernetes/pull/106108 which removed the check the pod is in Failed phase. 

Ran the test manually to validate the change:

Invocation: https://gist.github.com/eb0a893eb9a2d38c39e2055922950e67
Passing build-log: https://gist.github.com/ed5449b5b3e5a5202cdd879124850b6e

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 1]
```diff
@@ -316,6 +316,7 @@ func (m *managerImpl) processShutdownEvent() error {
 				klog.V(1).InfoS("Shutdown manager killing pod with gracePeriod", "pod", klog.KObj(pod), "gracePeriod", gracePeriodOverride)
 
 				if err := m.killPodFunc(pod, false, &gracePeriodOverride, func(status *v1.PodStatus) {
```
Comment (wzshiming) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: > I'm referring to specifically a pod that answers graceful shutdown with exit code 0 that is restartonfailure. That should exit as succeeded (hardcoding Failed in the phase is incorrect).
https://github.com/kubernetes/kubernetes/pull/104798#issuecomment-924066206
/cc @smarterclayton


I had a similar fix before, and I don't have a strong opinion

Comment (wzshiming) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: /cc @smarterclayton

Comment (smarterclayton) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: This should be an if check - `if Phase != <terminal phase>, set phase failed`

File: test/e2e_node/node_shutdown_linux_test.go [hunk 2]
```diff
@@ -510,5 +510,5 @@ func isPodShutdown(pod *v1.Pod) bool {
 		}
 	}
 
-	return pod.Status.Message == podShutdownMessage && pod.Status.Reason == podShutdownReason && hasContainersNotReadyCondition
+	return pod.Status.Message == podShutdownMessage && pod.Status.Reason == podShutdownReason && hasContainersNotReadyCondition && pod.Status.Phase == v1.PodFailed
```
Comment (smarterclayton) [inline test/e2e_node/node_shutdown_linux_test.go:513]: Fixing the above will probably make this flaky, so force the failure condition in the test (create a pod that always exits 1)

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go (hunk 1 above)
Comment (bobbypage) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: > This should be an if check - `if Phase != <terminal phase>, set phase failed`

hmm, I don't completely follow. We are setting the pod phase to failed here, so I'm a little confused which phase you mentioned we should be reading here (i.e. the `Phase != <terminal phase>`)

Comment (liggitt) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: @bobbypage I'm not seeing how it's possible to encounter a succeeded pod here, but just as a protection, you can do this:

```go
if status.Phase = v1.PodSucceeded {
	status.Phase = v1.PodFailed
}
```

Comment (smarterclayton) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: No, you can absolutely get already succeeded pods here.  Two kill requests can happen at the same time, and the pod can already be terminating or successfully finish between when you call killPod and when your callback gets invoked (kill pod is async).  Jordan's suggested code is fine.

Comment (bobbypage) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: Thanks for the clarification and suggestion. Updated as Jordan mentioned.

File: test/e2e_node/node_shutdown_linux_test.go (hunk 2 above)
Comment (liggitt) [reply test/e2e_node/node_shutdown_linux_test.go:513]: if this specific test never expects a successful pod, that makes sense to me

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go (hunk 1 above)
Comment (liggitt) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:318]: This lgtm now in terms of fixing the 1.22 regression while not introducing a Succeeded → Failed transition.

Follow-up in 1.24 is definitely needed for the other scenarios described in https://github.com/kubernetes/kubernetes/pull/104798#issuecomment-924066206 (pod terminates successfully without wanting to be restarted, etc).

**Comment by liggitt** [comment]
changes lgtm

I'd suggest a release note like this:

> `Reverts graceful node shutdown to match 1.21 behavior of setting pods that have not yet successfully completed to "Failed" phase if the GracefulNodeShutdown feature is enabled in kubelet. The GracefulNodeShutdown feature is beta and enabled by default in 1.21+. This changes 1.22 and 1.23 behavior on node shutdown to match 1.21. If you do not want pods to be marked terminated on node shutdown in 1.22 and 1.23, disable the GracefulNodeShutdown feature.`

**Comment by arianvp** [comment]
Was this cherry-picked to 1.23 already?
