### PR TITLE
Fix the race between configuring cbr0 and restarting static pods

### LINKED ISSUE #9822: kube-apiserver fails to start
Looking in kubelet's logs, I see: "API error (500): Cannot start container \<ID\>: [8] System error: read parent: connection reset by peer"

I have only been able to consistently reproduce it on a dev build of kubernetes running in GKE, but I think I saw the same thing happen off and on when debugging some of the Jenkins GKE-Test failures from Friday.

More logs:
```
event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67", UID:"10230b2ecdd307213211dedb5c7bd1c4", APIVersion:"v1", R
esourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}): reason: 'created' Created with docker id a76faba71e1615d5a638590c6c0d8e303f93d8c0c1702e7af4b42c84d59d210e
E0615 21:53:54.719591    2464 manager.go:1491] Error running pod "kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67_default" container "kube-apiserver": API error (500): Cannot start container a76faba71e1615d5a638590c6c
0d8e303f93d8c0c1702e7af4b42c84d59d210e: [8] System error: read parent: connection reset by peer
I0615 21:53:54.719648    2464 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67", UID:"10230b2ecdd307213211dedb5c7bd1c4", APIVersion:"v1", R
esourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}): reason: 'failed' Failed to start with docker id a76faba71e1615d5a638590c6c0d8e303f93d8c0c1702e7af4b42c84d59d210e with error: API error (500): Cannot start c
ontainer a76faba71e1615d5a638590c6c0d8e303f93d8c0c1702e7af4b42c84d59d210e: [8] System error: read parent: connection reset by peer
W0615 21:53:54.720978    2464 container.go:249] Failed to create summary reader for "/a76faba71e1615d5a638590c6c0d8e303f93d8c0c1702e7af4b42c84d59d210e": none of the resources are being tracked.
E0615 21:54:04.427496    2464 kubelet.go:1574] error getting node: node gke-664608984929-3a3afa5a2b3942c0cf67 not found
I0615 21:54:04.577893    2464 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67", UID:"10230b2ecdd307213211dedb5c7bd1c4", APIVersion:"v1", R
esourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}): reason: 'created' Created with docker id 6a170b2cf16b426df4cf0b4631cafeef6f7dddbb9c71624960ac9b4f4a2f2e8b
E0615 21:54:04.769703    2464 manager.go:1491] Error running pod "kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67_default" container "kube-apiserver": API error (500): Cannot start container 6a170b2cf16b426df4cf0b4631
cafeef6f7dddbb9c71624960ac9b4f4a2f2e8b: [8] System error: read parent: connection reset by peer
I0615 21:54:04.769741    2464 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67", UID:"10230b2ecdd307213211dedb5c7bd1c4", APIVersion:"v1", R
esourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}): reason: 'failed' Failed to start with docker id 6a170b2cf16b426df4cf0b4631cafeef6f7dddbb9c71624960ac9b4f4a2f2e8b with error: API error (500): Cannot start c
ontainer 6a170b2cf16b426df4cf0b4631cafeef6f7dddbb9c71624960ac9b4f4a2f2e8b: [8] System error: read parent: connection reset by peer
W0615 21:54:04.771218    2464 container.go:249] Failed to create summary reader for "/6a170b2cf16b426df4cf0b4631cafeef6f7dddbb9c71624960ac9b4f4a2f2e8b": none of the resources are being tracked.
E0615 21:54:14.434616    2464 kubelet.go:1574] error getting node: node gke-664608984929-3a3afa5a2b3942c0cf67 not found
I0615 21:54:14.615883    2464 event.go:203] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67", UID:"10230b2ecdd307213211dedb5c7bd1c4", APIVersion:"v1", R
esourceVersion:"", FieldPath:"spec.containers{kube-apiserver}"}): reason: 'created' Created with docker id 3e0201804da0616ed9942635b54d9b28c804e2ca590569f304ea3a6ea5d10442
E0615 21:54:14.800110    2464 manager.go:1491] Error running pod "kube-apiserver-gke-664608984929-3a3afa5a2b3942c0cf67_default" container "kube-apiserver": API error (500): Cannot start container 3e0201804da0616ed9942635b5
4d9b28c804e2ca590569f304ea3a6ea5d10442: [8] System error: read parent: connection reset by peer
```

### LINKED ISSUE #10122: kube-apiserver unable to write to etcd
In about 100 test runs overnight, 5 clusters failed with the same problem:
Nodes try to register with the apiserver, apiserver sends back a 500.
Looking at the kube-apiserver logs, I see:
```
E0619 20:37:50.685032       5 errors.go:62] apiserver received an error that is not an api.Status: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexp
ected HTTP status code]) [0]
I0619 20:37:50.685229       5 handlers.go:135] POST /api/v1/namespaces: (12.228060557s) 500
...
E0619 20:37:50.643558       5 errors.go:62] apiserver received an error that is not an api.Status: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexp
ected HTTP status code]) [0]
I0619 20:37:50.643762       5 handlers.go:135] POST /api/v1/nodes: (12.228247163s) 500
```

To me, that looks like writes to etcd are failing. Looking into the etcd container logs, I see a lot of:

```
2015/06/19 20:40:38 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:38 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:38 etcdserver: publish error: etcdserver: request timed out
2015/06/19 20:40:38 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:41 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:41 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:42 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:43 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:43 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:43 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:43 etcdserver: publish error: etcdserver: request timed out
2015/06/19 20:40:44 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:44 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:44 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:47 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:47 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/19 20:40:47 etcdhttp: unexpected error: etcdserver: request timed out
```

Trying to hit etcd directly:
```
# curl -L http://127.0.0.1:4001/v2/keys/message -XPUT -d value="Hello world"
{"message":"Internal Server Error"}
```
Etcd's data directory is pretty empty, other than one entry in members/wal, so I tried listing members:
```
# curl http://127.0.0.1:4001/v2/members
{"members":[]}
```
In a working cluster, that looks more like:
```
# curl http://127.0.0.1:4001/v2/members
{"members":[{"id":"ce2a822cea30bfca","name":"default","peerURLs":["http://localhost:2380","http://localhost:7001"],"clientURLs":["http://127.0.0.1:4001"]}]}
```

I'm about at the extent of my etcd knowledge, so if anybody has any idea what else to poke at, I'd love to hear it.

### PR DESCRIPTION
**Pull request by dchen1107**
The pr is based on #10153. It doesn't execute any podSpecs until network configuration is done no matter it is master nodes or minion nodes, the detail can be found at  https://github.com/GoogleCloudPlatform/kubernetes/pull/10153#issuecomment-113729964. 

Fixed #10122 and fixed  #9822.

Since I couldn't reproduce either  #10122 or #9822 on GCE, I run cluster/kube-down.sh && hack/dev-build-and-up.sh && gcutil ssh kubernetes-master sudo docker ps -a for 10 times, and make sure there are no docker containers (kube-apiserver, etcd, pause...) killed at the booting time.

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @brendandburns @zmerlynn @cjcullen @roberthbailey 

GKE folks, I think the last commit I added here: eb3c8ae92c5cbd7a5ab8a097a805302465ca16c2 is good enough to eliminate most of unnecessary restarting of master component pods caused by docker upgrades / flag changes. We could only patch this commit into v0.19.4, and leave rest of to v0.20 for more soaking time. How do you guys think?

Also please note that there is still a potential race between configuring cbr0 and starting static pods by pre-installed kubelet in containervm image on minion nodes until the fixing in this pr is included in our image. The only static pod left on minion nodes on GKE / GCE is fluentd, and I haven't heard any issue on restarting them, so I leave them untouched here.

**Comment by dchen1107** [comment]
ok to test

File: pkg/util/util.go [hunk 1]
```diff
@@ -198,6 +198,21 @@ func CompileRegexps(regexpStrings []string) ([]*regexp.Regexp, error) {
...
 }
 
+// Detects if using systemd as the init system
+// Please note that simply reading /proc/1/cmdline can be misleading because
+// some installation of various init programs can automatically make /sbin/init
+// a symlink or even a renamed version of their main program.
+// TODO(dchen1107): realiably detects the init system using on the system:
+// systemd,
+func UsingSystemdInitSystem() bool {
+	_, err := os.Stat("/run/systemd/system")
```
Comment (roberthbailey) [inline pkg/util/util.go]: This should be written as:

if _, err := os.Stat(...); err != nil {
  return false
}
return true

File: pkg/kubelet/status_manager.go [hunk 2]
```diff
@@ -58,6 +60,8 @@ func (s *statusManager) Start() {
 		err := s.syncBatch()
 		if err != nil {
 			glog.Warningf("Failed to updated pod status: %v", err)
+			// Errors and tight-looping are bad, m-kay
+			time.Sleep(30 * time.Second)
```
Comment (roberthbailey) [inline pkg/kubelet/status_manager.go]: Could this cause cluster creation to slow down significantly? I wonder if this should include increasing backoff rather than a long-ish sleep.

File: pkg/kubelet/container_bridge.go [hunk 3]
```diff
@@ -40,30 +81,22 @@ func ensureCbr0(wantCIDR *net.IPNet) error {
...
-			// TODO (dawnchen) figure out what we should do for rkt here.
-		}
-		glog.V(2).Info("Recreated cbr0 and restarted docker")
+		return createCBR0(wantCIDR)
 	}
 	return nil
 }
 
+func cbr0Exists() (bool, error) {
+	_, err := os.Stat("/sys/class/net/cbr0")
```
Comment (roberthbailey) [inline pkg/kubelet/container_bridge.go]: should be

if _, err := os.Stat(...); err != nil { ...}

File: pkg/kubelet/container_bridge.go [hunk 4]
```diff
@@ -40,30 +81,22 @@ func ensureCbr0(wantCIDR *net.IPNet) error {
...
-			// For now just log the error. The containerRuntime check will catch docker failures.
-			// TODO (dawnchen) figure out what we should do for rkt here.
-		}
-		glog.V(2).Info("Recreated cbr0 and restarted docker")
+		return createCBR0(wantCIDR)
 	}
 	return nil
 }
 
+func cbr0Exists() (bool, error) {
```
Comment (roberthbailey) [inline pkg/kubelet/container_bridge.go]: Please add a comment explaining the dual return values.

File: pkg/kubelet/container_bridge.go [hunk 5]
```diff
@@ -19,16 +19,57 @@ package kubelet
...
 func ensureCbr0(wantCIDR *net.IPNet) error {
-	if !cbr0CidrCorrect(wantCIDR) {
+	exists, err := cbr0Exists()
+	if err != nil {
+		return err
+	}
+	if !exists {
+		glog.V(2).Infof("CBR0 doesn't exist, attempting to create it with range: %s", wantCIDR)
+		return createCBR0(wantCIDR)
+	} else if !cbr0CidrCorrect(wantCIDR) {
```
Comment (roberthbailey) [inline pkg/kubelet/container_bridge.go]: This doesn't need to be in an else block since the if block above returns.

File: pkg/kubelet/container_bridge.go [hunk 6]
```diff
@@ -19,16 +19,57 @@ package kubelet
...
+	if err := exec.Command("ip", "link", "set", "dev", "cbr0", "up").Run(); err != nil {
+		glog.Error(err)
+		return err
+	}
+	// restart docker
+	if util.UsingSystemdInitSystem() {
+		if err := exec.Command("systemctl", "retart", "docker").Run(); err != nil {
+			glog.Error(err)
+			// For now just log the error. The containerRuntime check will catch docker failures.
+			// TODO (dawnchen) figure out what we should do for rkt here.
```
Comment (roberthbailey) [inline pkg/kubelet/container_bridge.go]: Is this TODO still relevant? And why does it exist in both branches?

File: cluster/saltbase/salt/kube-master-addons/init.sls [hunk 7]
```diff
@@ -37,10 +37,19 @@ master-docker-image-tags:
...
+# The ordering of salt states for service docker, kubelet and
+# master-addon below is very important to avoid the race between
+# salt restart docker or kubelet and kubelet start master components.
 kube-master-addons:
   service.running:
     - enable: True
     - restart: True
+    - require:
+      - service: docker
+      - service: kubelet
```
Comment (roberthbailey) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: Can you explain _why_ the order here is important. My best guess is that because this script is what side-loads the docker images for the master components, so the kubelet won't be able to start them before the images are side-loaded (attempts to fetch them from gcr.io will fail). But I'm not sure how that eliminates the race condition. Won't the images be side loaded right after the kubelet starts (potentially before it restarts docker) -- meaning that there will be a race between when salt decides to side load the images into docker and when the kubelet tries to launch pods from the manifest?

If the kubelet waits to launch pods from the manifest until after the networking is configured, I don't see how this would have any additional effect -- it shouldn't matter when the docker images are side loaded if the kubelet isn't trying to use them until it is safe to do so.

**Comment by roberthbailey** [comment]
We haven't seen any issues restarting fluentd on the node machines.

File: pkg/kubelet/container_bridge.go (hunk 6 above)
Comment (fcantournet) [inline pkg/kubelet/container_bridge.go]: s/retart/restart/

File: cluster/saltbase/salt/kube-master-addons/init.sls (hunk 7 above)
Comment (zmerlynn) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: This script shouldn't be loading the master components at all. It's responsible for the addons (SkyDNS, etc). I'm equally confused.

**Comment by a-robinson** [comment]
We also don't really monitor fluentd restarting on the node machines, do we?

File: pkg/kubelet/status_manager.go (hunk 2 above)
Comment (zmerlynn) [inline pkg/kubelet/status_manager.go]: Yeah, 30s is a long time here.

File: cluster/saltbase/salt/kube-master-addons/init.sls (hunk 7 above)
Comment (zmerlynn) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: Ignore my last comment. I forgot we also [started using it to load the master components](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/init.sls#L25).

Comment (zmerlynn) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: God, the coffee just isn't kicking this morning. Ignore both comments, I just remembered this is a separate script. So horribly embarrassed.

Okay, I worked out how this helps and now am on the same. I was worried because the manifest files are laid out on disk when Salt runs, and they're laid out in arbitrary order (because Salt). But this service is the only thing doing the `docker load` from the binary tar files, so yes, as @roberthbailey worked out, kubelet won't be able to start them until they're side-loaded. (Slowly waking up.)

Now that I've caught up - this does feel like a noop patch. I'm not sure what guarantees it's trying to provide.

Comment (dchen1107) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: I explained why the order is very important here: https://github.com/GoogleCloudPlatform/kubernetes/issues/10122#issuecomment-114566063

**Comment by zmerlynn** [comment]
The flip side of this conversation is that if it solves a real problem, eb3c8ae92c5cbd7a5ab8a097a805302465ca16c2 is so surgical that I'm honestly quite willing to take it for a 0.19.4 with very limited qualification.

The rest of this PR, it would be nice to get into HEAD today, and maybe we can let it sit for today before we cut 0.20 tomorrow?

**Comment by dchen1107** [comment]
@roberthbailey and @a-robinson I also don't see any issues caused by fast restarting fluentd on the node machines. Also last commit https://github.com/dchen1107/kubernetes-1/commit/eb3c8ae92c5cbd7a5ab8a097a805302465ca16c2 I introduced here will eliminate most of killings at the boot time too. I thought it is worthy mentioning it here since there is still a little chance of killing at minion nodes at boot time. :-)

File: pkg/kubelet/status_manager.go (hunk 2 above)
Comment (dchen1107) [inline pkg/kubelet/status_manager.go]: This is introduced in @brendandburns original commits, and you are right 30s is too long, and it is irrelevant to this pr. My bad ignoring it. I am going to remove it for now.

File: pkg/kubelet/container_bridge.go (hunk 6 above)
Comment (dchen1107) [inline pkg/kubelet/container_bridge.go]: @fcantournet good catch. Thanks.

@roberthbailey It is still relevant. We talked about this when you guys first introducing configuring cbr0 by kubelet. One of reasons of restarting docker is killing all existing kubernetes containers which might have wrong network configurations. rkt doesn't require network containers, and rkt is daemon-less too, we need to figure out the impact here too.

**Comment by dchen1107** [comment]
Addressed all comments, PTAL? Thanks @roberthbailey @zmerlynn!

File: cluster/saltbase/salt/docker/docker-defaults [hunk 8]
```diff
@@ -2,5 +2,6 @@ DOCKER_OPTS=""
 {% if grains.docker_opts is defined and grains.docker_opts %}
 DOCKER_OPTS="${DOCKER_OPTS} {{grains.docker_opts}}"
 {% endif %}
-DOCKER_OPTS="${DOCKER_OPTS} --bridge cbr0 --iptables=false --ip-masq=false"
+
+DOCKER_OPTS="${DOCKER_OPTS} --bridge=cbr0 --iptables=false --ip-masq=false"
```
Comment (roberthbailey) [inline cluster/saltbase/salt/docker/docker-defaults]: I don't think there are any changes to this file. revert it?

File: cluster/saltbase/salt/kube-master-addons/init.sls (hunk 7 above)
Comment (roberthbailey) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: Please add a brief note here as well so that the explanation stays with the code. Something along the lines of "Don't allow the kubelet that is pre-installed on the container vm to launch any of the side-loaded containers since it is being replaced by salt."

You might also note that once we move these containers to gcr.io with proper release versions, this sideloading will be unnecessary and we will need another way to control this.

File: cmd/kubelet/app/server.go [hunk 9]
```diff
@@ -241,7 +242,7 @@ func (s *KubeletServer) AddFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&s.ConfigureCBR0, "configure-cbr0", s.ConfigureCBR0, "If true, kubelet will configure cbr0 based on Node.Spec.PodCIDR.")
 	fs.IntVar(&s.MaxPods, "max-pods", 100, "Number of Pods that can run on this Kubelet.")
 	fs.StringVar(&s.DockerExecHandlerName, "docker-exec-handler", s.DockerExecHandlerName, "Handler to use when executing a command in a container. Valid values are 'native' and 'nsenter'. Defaults to 'native'.")
-
+	fs.StringVar(&s.PodCIDR, "pod-cidr", "", "The CIDR to use for pod IP addresses, only used in standalone mode.  In cluster mode, this is obtained from the master.")
```
Comment (roberthbailey) [inline cmd/kubelet/app/server.go]: What happens in stand-alone mode if this isn't set? (if we put this into 0.20.0 and then put that into a container vm release, the kubelet needs to work for folks running a [standalone container vm](https://cloud.google.com/compute/docs/containers/container_vms)).

Comment (zmerlynn) [inline cmd/kubelet/app/server.go]: And why not just have a default value here if so?

File: pkg/kubelet/container_bridge.go (hunk 4 above)
Comment (zmerlynn) [inline pkg/kubelet/container_bridge.go]: I don't think this comment was addressed?

File: cmd/kubelet/app/server.go (hunk 9 above)
Comment (dchen1107) [inline cmd/kubelet/app/server.go]: The standalone here means master node only. For container vm case, the feature is controlled by flag --configure-cbr0, which should be false. I mentioned this in our earlier meeting.

@zmerlynn what do you mean the default value here? In our master node case, kubelet obtains the value from environment variable $MASTER_IP_RANCE.

**Comment by dchen1107** [comment]
Revert that unnecessary line. PTAL?

File: cmd/kubelet/app/server.go (hunk 9 above)
Comment (zmerlynn) [inline cmd/kubelet/app/server.go]: Misunderstanding of the word "standalone".

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
@zmerlynn any further comments?

File: cluster/saltbase/salt/kube-master-addons/init.sls (hunk 7 above)
Comment (dchen1107) [inline cluster/saltbase/salt/kube-master-addons/init.sls]: more comments for this one. But please note that even we have current kubelet included in container vm image, this change is still good. Basically unnecessary fast restart those docker containers might introduce some issues in general. We can remove this until we never push new docker flags through salt, and reinstall new kubelet through salt.

**Comment by dchen1107** [comment]
@alex-mohr or @davidopp or @lavalamp Can I have one more TL lgtm from you guys? We want to include this into v0.20 release and get some soaking time. Thanks!

**Comment by zmerlynn** [comment]
LGTM

**Comment by alex-mohr** [comment]
LGTM -- thank you so much dawn!
