### PR TITLE
Simplify the unregistration of csiplugin

### LINKED ISSUE #87282: kubelet can't unregister csiplugin after csiplugin pod is deleted from node
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR simplifies the unregistration of csiplugin by dropping SocketPluginHandlers.

**Which issue(s) this PR fixes**:
Addresses concerns raised in https://github.com/kubernetes/kubernetes/pull/88006#issuecomment-610554384
Fixes https://github.com/kubernetes/kubernetes/issues/87282

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go [hunk 1]
```diff
@@ -96,10 +99,9 @@ func (oe *operationExecutor) RegisterPlugin(
 	socketPath string,
 	timestamp time.Time,
 	pluginHandlers map[string]cache.PluginHandler,
```
Comment (saad-ali) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: Remove `pluginHandlers map[string]cache.PluginHandler` from `RegisterPlugin(`

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -144,35 +137,21 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
 func (og *operationGenerator) GenerateUnregisterPluginFunc(
 	socketPath string,
 	pluginHandlers map[string]cache.PluginHandler,
```
Comment (saad-ali) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go:139]: Remove `pluginHandlers map[string]cache.PluginHandler` from `GenerateUnregisterPluginFunc( ...)` and replace with `pluginInfo` that way you can also remove the `actualStateOfWorldUpdater.GetPlugin(socketPath)` method.

**Review by saad-ali — CHANGES_REQUESTED** [review]

File: pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go (hunk 1 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: pluginHandlers is used by registration (see operationGenerator#GenerateRegisterPluginFunc):
```
		handler, ok := pluginHandlers[infoResp.Type]
```
the handler depends on the type of the response.
Can you elaborate how to retrieve the handler if the map is dropped ?

Comment (saad-ali) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: Once you implement the suggestion in https://github.com/kubernetes/kubernetes/pull/89934/files#r405081120 you will no longer need it here.

**Review by saad-ali — CHANGES_REQUESTED** [review]

File: pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go (hunk 1 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: pluginHandlers can be removed from GenerateUnregisterPluginFunc without side effect (since it is not used by unregistration). Looking at the code for registration, it seems pluginHandlers is still needed.

Comment (saad-ali) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: Sorry you're right, I was thinking of `pathToHandlers` not `pluginHandlers`.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: Please let me know whether pluginHandlers should be removed from GenerateUnregisterPluginFunc. Keeping it as is would make the signatures symmetrical.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: @saad-ali 
Let me know if there is remaining comment to be addressed.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go:101]: @saad-ali 
Gentle ping for review.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 3]
```diff
@@ -53,6 +53,9 @@ type ActualStateOfWorld interface {
 	// If a plugin does not exist with the given socket path, this is a no-op.
 	RemovePlugin(socketPath string)
 
+	// GetPlugin retrieves PluginInfo by socketPath
+	GetPlugin(socketPath string) PluginInfo
```
Comment (saad-ali) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go:57]: This should no longer be needed, please remove.

**Review by saad-ali — CHANGES_REQUESTED** [review]

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 3 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go:57]: This is still used by operation_generator 
```
		pluginInfo := actualStateOfWorldUpdater.GetPlugin(socketPath)
```

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 2 above)
Comment (saad-ali) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: > Please let me know whether pluginHandlers should be removed from GenerateUnregisterPluginFunc. Keeping it as is would make the signatures symmetrical with registration.

Yes please remove `pluginHandlers` and replace with `pluginInfo` as mentioned above.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 3 above)
Comment (saad-ali) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go:57]: https://github.com/kubernetes/kubernetes/pull/89934#discussion_r406971435

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 2 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @saad-ali 
Your comments have been addressed.

**Comment by saad-ali** [comment]
Thanks @tedyu 
/lgtm
/approve

/test pull-kubernetes-conformance-kind-ga-only-parallel
/test pull-kubernetes-e2e-kind-ipv6

/hold
To let @taragu review

**Review by taragu — COMMENTED** [review]
Looks good overall! Just one suggestion for consistency. The `PluginInfo` objects in `actual_state_of_world_test.go` need to be updated with the new fields to be added.

**Comment by tedyu** [comment]
@taragu 
In operationGenerator#GenerateRegisterPluginFunc, handler is retrieved from pluginHandlers.
I looked at the test code where there is no pluginHandlers.

Can you be a bit specific on how the PluginInfo object should be populated in the test ?

**Comment by taragu** [comment]
@tedyu sure, here for example: https://github.com/kubernetes/kubernetes/blob/b54e7d92652797d8485596440960490d66c505be/pkg/kubelet/pluginmanager/cache/actual_state_of_world_test.go#L30 we can change it to the following just for completion purposes
```
pluginInfo := PluginInfo{
		SocketPath: "/var/lib/kubelet/device-plugins/test-plugin.sock",
		Timestamp:  time.Now(),
		Handler: nil,
		Name: "test",
	}
```

**Comment by tedyu** [comment]
@taragu 
Your comment has been addressed.

**Comment by taragu** [comment]
/lgtm
Any idea why the tests aren't running?
