### PR TITLE
Setup fluentd-ds-ready label in startup script not in kubelet

### LINKED ISSUE #42840: Deprecate / remove alpha.kubernetes.io/fluentd-ds-ready annotation
PR #32088 introduced an annotation for fluentd migration from static pod to the daemonset to avoid two instances of fluentd on a single node during the transition stage. I didn't read the pr carefully, but based on the code at https://github.com/kubernetes/kubernetes/pull/32088/files#diff-6b0808bd1afb15f9f77986f4459601c2R199, every node object has one label be default: 
"alpha.kubernetes.io/fluentd-ds-ready". I think this is wrong. 1) Not everyone use fluentd as the logging agent. 2) It is hard-coded in Kubelet code as part of kubelet_node_status. No matter running fluentd as a static pod or a daemonset on the node, Kubelet shouldn't treat it different from other pods. The right approach is introducing an external controller to apply this cloud-provider / kubernetes vendor (i.e. GKE) specific label to the node. 

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    scheduler.alpha.kubernetes.io/taints: '[]'
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: 2017-02-25T01:50:12Z
  labels:
    alpha.kubernetes.io/fluentd-ds-ready: "true"                                                        <======================
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: n1-standard-8
    beta.kubernetes.io/os: linux
...
```

cc/ @kubernetes/sig-node-bugs @mikedanese

### PR DESCRIPTION
**Pull request by piosz**
fix #42840

``` release-note
Fluentd was migrated to Daemon Set, which targets nodes with beta.kubernetes.io/fluentd-ds-ready=true label. If you use fluentd in your cluster please make sure that the nodes with version 1.6+ contains this label.
```

### CODE REVIEW

**Comment by crassirostris** [comment]
That'll break fluentd upgrade for non-gce installation

**Comment by piosz** [comment]
I'll add appropriate release notes.

File: cluster/gce/config-default.sh [hunk 1]
```diff
@@ -106,6 +106,13 @@ ENABLE_L7_LOADBALANCING="${KUBE_ENABLE_L7_LOADBALANCING:-glbc}"
 #   standalone     - Heapster only. Metrics available via Heapster REST API.
 ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-influxdb}"
 
+# Historically fluentd was a manifest pod and then was migrated to DaemonSet.
+# To avoid situation during cluster upgrade when there are two instances
+# of fluentd running on a node, kubelet need to mark node on which
+# fluentd in not running as a manifest pod with appriopriate label.
+# TODO(piosz): remove this in 1.8
+NODE_LABELS="${KUBE_NODE_LABELS:-alpha.kubernetes.io/fluentd-ds-ready=true}"
```
Comment (crassirostris) [inline cluster/gce/config-default.sh]: If users defines $KUBE_NODE_LABELS with some custom stuff, fluentd stops working, that doesn't seem OK

**Review by crassirostris — CHANGES_REQUESTED** [review]

**Comment by dchen1107** [comment]
From GCE / GKE standpoint, I am ok with this. 

But like what @crassirostris pointed out above, there is a potential upgrade issue for other kubernetes vendors. 

cc/ a few folks: @justinsb for AWS, @derekwaynecarr for openshift, @calebamiles for coreos, and @jbeda, @roberthbailey for cluster lifecycle in general.

File: cluster/gce/config-default.sh (hunk 1 above)
Comment (piosz) [inline cluster/gce/config-default.sh]: It's not a problem with backward compatibility, because `$KUBE_NODE_LABELS` hasn't existed before. I can add a comment here (or below near logging setup) that if you want to override the flag and use fluentd for logging at the same time you need to make sure that there is the label `alpha.kubernetes.io/fluentd-ds-ready=true` specified there. WDYT?

Comment (crassirostris) [inline cluster/gce/config-default.sh]: > because `$KUBE_NODE_LABELS` hasn't existed before

Oh :)

SGTM then

**Review by crassirostris — APPROVED** [review]

**Comment by piosz** [comment]
Thanks @crassirostris @dchen1107. Let's wait for cc-ed folks.

**Comment by piosz** [comment]
@k8s-bot e2e test this

File: cluster/gce/config-default.sh [hunk 2]
```diff
@@ -106,6 +106,13 @@ ENABLE_L7_LOADBALANCING="${KUBE_ENABLE_L7_LOADBALANCING:-glbc}"
 #   standalone     - Heapster only. Metrics available via Heapster REST API.
 ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-influxdb}"
 
+# Historically fluentd was a manifest pod and then was migrated to DaemonSet.
+# To avoid situation during cluster upgrade when there are two instances
+# of fluentd running on a node, kubelet need to mark node on which
+# fluentd in not running as a manifest pod with appriopriate label.
```
Comment (justinsb) [inline cluster/gce/config-default.sh]: nit - two small typos: s/in/is and s/appriopriate/appropriate

**Comment by justinsb** [comment]
Thank for the heads up, but not a problem for kops - we curate our own manifests, but now I know what the label is for :-)

File: cluster/gce/config-default.sh (hunk 2 above)
Comment (piosz) [inline cluster/gce/config-default.sh]: Done

**Comment by piosz** [comment]
@crassirostris @dchen1107 fixed typos, e2e passed, it doesn't impact other providers. Can you please grant lgtm?

**Comment by piosz** [comment]
@roberthbailey can you please approve?

**Comment by piosz** [comment]
@roberthbailey I meant are you ok with this change on behalf of cluster lifecycle team?

**Comment by piosz** [comment]
Waiting for @roberthbailey lgtm

**Comment by Random-Liu** [comment]
@piosz Please update the release note. This is still shown as `TBD` in our release note.
https://github.com/kubernetes/features/blob/master/release-1.6/release-notes-draft.md#other-notable-changes

**Comment by piosz** [comment]
@Random-Liu done
