### PR TITLE
Ignore changes to managed field in noderestriction

### LINKED ISSUE #74049: Volume resize tests are failing in multizone and alpha environment
Alpha environment tests are failing - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/6876

The root cause of the tests failing in alpha environment appears to be:

```
Feb 14 01:16:24.068: INFO: At 2019-02-14 01:11:31 +0000 UTC - event for deployment-535e408a-2ff5-11e9-9340-52a97e11b2fc-bd8c54665-llwhg: {kubelet bootstrap-e2e-minion-group-1cn1} FailedMount: MountVolume.resizeFileSystem update PVC status failed for volume "pvc-4f7dab2d-2ff5-11e9-95c5-42010a8a0002" : PatchPVCStatus.Failed to patch PVC "pvc-rqfkj" with persistentvolumeclaims "pvc-rqfkj" is forbidden: node "bootstrap-e2e-minion-group-1cn1" is not allowed to update fields other than status.capacity and status.conditions: 
object.ObjectMeta.ManagedFields[0].Fields.Map[f:metadata].Map[f:finalizers].Map[.].Map:
```

So basically kubelet is not allowed to update PVC. Which is weird. Need to investigate further.

Also for multizone environment - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-multizone/28052

This line looks weird from e2e:

```
FailedScheduling: 0/10 nodes are available: 1 node(s) had volume node affinity conflict, 1 node(s) were unschedulable, 8 node(s) didn't match node selector.
```

So the deployment is straight up not getting started.

/sig storage
/assign

### PR DESCRIPTION
**Pull request by apelisse**
The validation is failing because the managedfields are changed when the
object is updated. We don't have a good way to verify that the changes
are only the ones that are supposed to happen, so we'll just ignore them
for now.

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #74049

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @msau42 @liggitt

### CODE REVIEW

File: plugin/pkg/admission/noderestriction/admission.go [hunk 1]
```diff
@@ -309,6 +309,12 @@ func (c *nodePlugin) admitPVCStatus(nodeName string, a admission.Attributes) err
 		oldPVC.Status.Conditions = nil
 		newPVC.Status.Conditions = nil
 
+		// TODO(apelisse): We don't have a good mechanism to
```
Comment (liggitt) [inline plugin/pkg/admission/noderestriction/admission.go]: can you add this to the list of things to look at for beta?

Comment (apelisse) [reply plugin/pkg/admission/noderestriction/admission.go]: Yeah, good idea

Comment (apelisse) [reply plugin/pkg/admission/noderestriction/admission.go]: done

**Comment by liggitt** [comment]
/lgtm
/approve

this field is non-escalating, so I'm not super concerned about it, but being able to tell whether the contents were computed by the server or overridden by the incoming request seems like a useful thing to know.

**Comment by apelisse** [comment]
> this field is non-escalating, so I'm not super concerned about it, but being able to tell whether the contents were computed by the server or overridden by the incoming request seems like a useful thing to know.

Correct, I agree.
