### PR TITLE
More descriptive error message for `make test`

### LINKED ISSUE #52025: Add helpful error message when using `make test` with a `WHAT` value relative to the current directory, not the $GOPATH
/kind feature

**What happened**:
I tried to use `make test` to run the podautoscaler tests, with `make test WHAT=pkg/controller/podautoscaler`. I got the error message 
```
can't load package: package pkg/controller/podautoscaler: cannot find package "pkg/controller/podautoscaler" in any of: ...
```

The issue was that because I was specifying the package path relative to my current directory, as opposed to $GOPATH, I needed to append a `./` to my path dir. The command should have been `make test WHAT=./pkg/controller/podautoscaler`.

**What you expected to happen**:
It would have been great to get a helpful message from `make test`. For example, "it appears you specified your package path relative to your current directory - try running this command again with "./" prepended to the path". I would think that `hack/make-rules/test.sh` could do a relatively easy calculation to check if you incorrectly specified the path (i.e. does it not exist at $GOPATH but does exist from the current dir).

**How to reproduce it (as minimally and precisely as possible)**:
`make test WHAT=pkg/controller/podautoscaler`

**Anything else we need to know?**:
I'd be happy to submit a pr for this if it would be helpful :)

/sig contributor-experience

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**Which issue this PR fixes**
Fix #52025

**What this PR does / why we need it**:

The `[packages]` argument to `go test` can be confusing. If the
`package` does not begin with `./`, `go test` considers it relative to
`$GOPATH/src`. If it does begin with `./`, `go test` considers it
relative to `pwd`. `hack/make-rules/test.sh`, and thus `make test`, use
`go test`.

This commit adds a verify step to `hack/make-rules/test.sh`. Before we
run `go test`, we check the packages under test exist. If the user
specified the package path in the incorrect format - for example they
didn't prepend with `./` when they should have, the check logs a
suggestion of the alternative path they should use.

Running the test suites for a package is an activity many all first time
contributors will take. Hopefully including a more descriptive error
message, with a suggestion for a fix if applicable, will make this an
easier experience.

Signed-off-by: mattjmcnaughton <mattjmcnaughton@gmail.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
Realized I forgot to tag @DirectXMan12 - just wanted to put it on your radar cause we talked about this in the issue and thought you might have thoughts. Thanks :)

**Comment by mattjmcnaughton** [comment]
/assign @cblecker

Whoops, I noticed I never actually entered the comment to assign this. If you have a second to take a look, that would be wonderful - thanks!

File: hack/make-rules/test.sh [hunk 1]
```diff
@@ -211,6 +211,38 @@ junitFilenamePrefix() {
...
+
+verifyPathsToPackagesUnderTest() {
+  local packages_under_test=($@)
+
+  for package_path in "${packages_under_test[@]}"; do
+    local local_package_path="$(pwd)/$package_path"
+    local go_package_path="$GOPATH/src/$package_path"
+
+    if [[ "${package_path:0:2}" == "./" ]] ; then
+      verifyAndSuggestPackagePath "$local_package_path" "$go_package_path" "$package_path" "${package_path:2}"
```
Comment (sttts) [inline hack/make-rules/test.sh]: what's `"${package_path:2}"`?

Comment (sttts) [reply hack/make-rules/test.sh]: oh, ic

Comment (cblecker) [reply hack/make-rules/test.sh]: The error messages are a bit confusing though because the test framework works under it's own gopath. Have a look at this error when I intentionally specify the wrong path:
```
$ make test WHAT=./k8s.io/kubernetes/pkg/controller/podautoscaler
Running tests for APIVersion: v1,admissionregistration.k8s.io/v1alpha1,admission.k8s.io/v1alpha1,apps/v1beta1,apps/v1beta2,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,,federation/v1beta1
!!! [0925 10:22:23] specified test path "/opt/k8sgopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/./k8s.io/kubernetes/pkg/controller/podautoscaler" does not exist
if you intended to test "/opt/k8sgopath/src/k8s.io/kubernetes/_output/local/go/src/./k8s.io/kubernetes/pkg/controller/podautoscaler", change
      "./k8s.io/kubernetes/pkg/controller/podautoscaler" to "k8s.io/kubernetes/pkg/controller/podautoscaler"
make: *** [test] Error 1
```

**Review by cblecker — CHANGES_REQUESTED** [review]

File: hack/make-rules/test.sh (hunk 1 above)
Comment (mattjmcnaughton) [reply hack/make-rules/test.sh]: Great point @cblecker ! Updated the pr with clearer error messages.

```
$ make test WHAT=pkg/controller/podautoscaler`
specified test path '$GOPATH/src/pkg/controller/podautoscaler' does not exist
try changing "pkg/controller/podautoscaler" to "./pkg/controller/podautoscaler"
```
and
```
$ make test WHAT=./k8s.io/kubernetes/pkg/controller/podautoscaler
specified test path './k8s.io/kubernetes/pkg/controller/podautoscaler' does not exist.
try changing './k8s.io/kubernetes/pkg/controller/podautoscaler' to 'k8s.io/kubernetes/pkg/controller/podautoscaler'
```

Do you think that's easier to parse?

File: hack/make-rules/test.sh [hunk 2]
```diff
@@ -211,6 +211,41 @@ junitFilenamePrefix() {
...
+  local specified_package_path="$1"
+  local alternative_package_path="$2"
+  local original_package_path="$3"
+  local suggestion_package_path="$4"
+
+  if ! [ -d "$specified_package_path" ]; then
+    # Because k8s sets a localized $GOPATH for testing, seeing the actual
+    # directory can be confusing. Instead, just show $GOPATH if it exists in the
+    # $specified_package_path.
+    printable_package_path=$(echo "$specified_package_path" | sed "s|$GOPATH|\$GOPATH|")
```
Comment (cblecker) [inline hack/make-rules/test.sh]: should be local var

Comment (mattjmcnaughton) [reply hack/make-rules/test.sh]: Great catch @cblecker ! Made fix and updated diff.
