### PR TITLE
Fix waiting in kubectl rollout status

### LINKED ISSUE #40224: "kubectl rollout status" returns error message before rollout finish
When we execute `kubectl rollout status`, we're receiving this error:
```
kubectl rollout status deployment/app --namespace=app
Waiting for rollout to finish: 2 out of 6 new replicas have been updated...
Waiting for rollout to finish: 2 out of 6 new replicas have been updated...

error: timed out waiting for the condition
```
I also tried to put the option `-w`, but it did't change anything.

Since we upgraded to Kubernetes 1.5.2 we're receiving this. In 1.4.6 it works with no problems. I've tried to update `kubectl` and use previous versions too, but seems to be a problem with the cluster, not with `kubectl` command.  

This is a problem for us because Jenkins is using this command to monitor the deployment status, so our builds are crashing in the end. 

We're running the cluster on AWS  with Kops provisioning.

### PR DESCRIPTION
**Pull request by tnozicka**
**What this PR does / why we need it**:
By `kubectl rollout status` being based on `UntilWithoutRetry` it will fail whenever the watcher is closed - cased by the closing the underlying connection - e.g. on API timeout, LB timeout, ... 

Using UntilWithSync (based on informer) allows it to recover from all the failures and truly work trough unlimited timeouts.

(Split from https://github.com/kubernetes/kubernetes/pull/50102)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/40224

**Special notes for your reviewer**:

**Release note**:
```release-note
`kubectl rollout status` now works for unlimited timeouts.
```

### CODE REVIEW

**Comment by tnozicka** [comment]
/milestone v1.12

/cc @janetkuo @kow3ns @kubernetes/sig-apps-pr-reviews @kubernetes/sig-cli-pr-reviews 

/cc @smarterclayton @wojtek-t @liggitt
(as this is split from the big PR you were rewiewing)

**Comment by tnozicka** [comment]
@soltysh addressed your comments from https://github.com/kubernetes/kubernetes/pull/50102#discussion_r212627560

File: pkg/kubectl/cmd/rollout/rollout_status.go [hunk 1]
```diff
@@ -158,60 +181,70 @@ func (o *RolloutStatusOptions) Run() error {
...
+				return false, nil
+
+			case watch.Deleted:
+				// We need to abort to avoid cases of recreation and not to silently watch the wrong (new) object
+				return true, fmt.Errorf("object has been deleted")
+
+			default:
+				glog.Fatalf("unexpected event %#v", e)
+				// Compiler doesn't see that glog.Fatalf exits the flow, panic makes it happy.
+				panic("glog failed to exit")
```
Comment (soltysh) [inline pkg/kubectl/cmd/rollout/rollout_status.go]: Don't, return empty error instead.

File: pkg/kubectl/cmd/rollout/rollout_status.go [hunk 2]
```diff
@@ -158,60 +181,70 @@ func (o *RolloutStatusOptions) Run() error {
...
+				}
+
+				return false, nil
+
+			case watch.Deleted:
+				// We need to abort to avoid cases of recreation and not to silently watch the wrong (new) object
+				return true, fmt.Errorf("object has been deleted")
+
+			default:
+				glog.Fatalf("unexpected event %#v", e)
```
Comment (soltysh) [inline pkg/kubectl/cmd/rollout/rollout_status.go]: Log event (even with higher `V`, eg. `V(1)` or `V(2)`, to help debugging, but don't do `Fatalf`.

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/kubectl/cmd/rollout/rollout_status.go (hunk 2 above)
Comment (tnozicka) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: This is the case of internal error in the logic here, this branch should never be reached unless something is horribly wrong. Silently ignoring the error is wrong and would mean that our whole test suite would never uncover it!

File: pkg/kubectl/cmd/rollout/rollout_status.go (hunk 1 above)
Comment (tnozicka) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: Same here, if glog.Fatal were not to exit something is horribly wrong. There might be other ways than panic to deal with this but we need to error out here, not ignore that the universe is falling apart :) I personally think the panic is appropriate action if such state should ever be reached.

Comment (soltysh) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: Having `V(1)` error and checking for its not appearing in tests is the same approach. Although I'm not happy with us having `panic`-s in code :/

Comment (soltysh) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: If you want to go with panic, do `panic(fmt.Sprintf(unexpected event %#v", e))` instead.

Comment (soltysh) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: Bypassing compiler problems with double lines is wrong.

**Comment by soltysh** [comment]
/hold
Until I get my fix for the `panic` + `Fatalf`

File: pkg/kubectl/cmd/rollout/rollout_status.go (hunk 1 above)
Comment (tnozicka) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: > Having V(1) error and checking for its not appearing in tests is the same approach.

I don't see how that's comparable. This needs to end with the CLI command exiting with non 0 return code. I am open to other paths that end up in that place.

> Although I'm not happy with us having panic-s in code :/

In normal code paths this is correct. This is a bit special case since it's only run if we asked to exit the program and it didn't - seems like totally appropriate action to what happened.

> If you want to go with panic, do panic(fmt.Sprintf(unexpected event %#v", e)) instead.

this seemed resonable on the first look, but we are not panicing because unexpected event, but because our call to exit the program failed.

> Bypassing compiler problems with double lines is wrong.

It's not ideal, but much better then ignoring errors.

Comment (tnozicka) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: wanted to file an issue in the glog to fix this; the I've found out:
```
The master copy of the source lives inside
Google, not here. The code in this repo is for export only and is not itself
under development. Feature requests will be ignored.
```
just awesome to be based on such internal project...

Comment (tnozicka) [reply pkg/kubectl/cmd/rollout/rollout_status.go]: went for regular error which will result in setting the exit code to non-zero as well. I believe this removes the objections you had for fatal/panic since they are now gone

/hold cancel

**Comment by tnozicka** [comment]
@soltysh @kubernetes/sig-apps-pr-reviews @kubernetes/sig-cli-pr-reviews PTAL before the freeze :)

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by kargakis** [comment]
:champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne: :champagne:

**Comment by ocofaigh** [comment]
Does anyone know if this fix will be backported to v1.11? I can reproduce the issue on v1.11.5:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:41:50Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ kubectl rollout status sts logstash -n connections --request-timeout=10m
Waiting for 2 pods to be ready...
Waiting for 1 pods to be ready...
error: watch closed before Until timeout
```

**Comment by ocofaigh** [comment]
@tnozicka Is it possible to request this fix in v1.11 since that is still a supported version.

**Comment by tnozicka** [comment]
I don't think this is eligible for backport as that requires new apimachinery and although it is fixing this bug it's more a feature (the machinery part).
