### PR TITLE
Fix broken gke regional logging test.

### LINKED ISSUE #60882: "Cluster level logging implemented by Stackdriver should ingest events" fails for GKE Regional Clusters
This test consistently fails for GKE Regional Clusters:
https://k8s-testgrid.appspot.com/google-gke#gke-regional

```
go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdrvier/basic.go:141
Expected error:
    <*errors.errorString | 0xc420f6a3f0>: {
        s: "timed out waiting for ingestion, still not ingested: ",
    }
    timed out waiting for ingestion, still not ingested: 
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdrvier/basic.go:168
```

@piosz @crassirostris - can you please triage?

### PR DESCRIPTION
**Pull request by loburm**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60882

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/instrumentation/logging/stackdrvier/basic.go [hunk 1]
```diff
@@ -162,8 +162,11 @@ var _ = instrumentation.SIGDescribe("Cluster level logging implemented by Stackd
 			}()
 
 			ginkgo.By("Waiting for events to ingest")
-			zone := framework.TestContext.CloudConfig.Zone
-			c := utils.NewLogChecker(p, utils.UntilFirstEntryFromZone(zone), utils.JustTimeout, "")
+			location := framework.TestContext.CloudConfig.Zone
+			if framework.TestContext.CloudConfig.MultiZone {
```
Comment (crassirostris) [inline test/e2e/instrumentation/logging/stackdrvier/basic.go]: Isn't multi-zone different from region? What the `Zone` value will be in regional case?

**Review by crassirostris — COMMENTED** [review]
Thanks a lot!

One question though

File: test/e2e/instrumentation/logging/stackdrvier/basic.go (hunk 1 above)
Comment (loburm) [reply test/e2e/instrumentation/logging/stackdrvier/basic.go]: AFAIU this parameter is true for both of this cases in test env:
https://github.com/kubernetes/test-infra/blob/master/jobs/config.json#L7093

In case of regional ZONE is just a random zone from region.

**Comment by tpepper** [comment]
@crassirostris should this be labelled for 1.10 milestone inclusion?

**Comment by loburm** [comment]
Yes that should go for 1.10, because PR that broke this test is marked:
https://github.com/kubernetes/kubernetes/pull/60503
