### PR TITLE
AWS kube-down: don't fail if ELB not in VPC - #23784

### LINKED ISSUE #23784: shutting down cluster throws KeyError: 'VPCId'
Assumes all ELBs are within a VPC.

./kubernetes/cluster/aws/util.sh
```
function get_elbs_in_vpc {
  # ELB doesn't seem to be on the same platform as the rest of AWS; doesn't support filtering
  aws elb --output json describe-load-balancers  | \
    python -c "import json,sys; lst = [str(lb['LoadBalancerName']) for lb in json.load(sys.stdin)['LoadBalancerDescriptions'] if lb['VPCId'] == '$1']; print('\n'.join(lst))"
}

```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'VPCId'
```

### PR DESCRIPTION
**Pull request by ajohnstone**
Prevent python undefined key error.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'VPCId'
```

Fixes #23784

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23785)

### CODE REVIEW

File: cluster/aws/util.sh [hunk 1]
```diff
@@ -151,7 +151,7 @@ function get_igw_id {
 function get_elbs_in_vpc {
   # ELB doesn't seem to be on the same platform as the rest of AWS; doesn't support filtering
   aws elb --output json describe-load-balancers  | \
-    python -c "import json,sys; lst = [str(lb['LoadBalancerName']) for lb in json.load(sys.stdin)['LoadBalancerDescriptions'] if lb['VPCId'] == '$1']; print('\n'.join(lst))"
+    python -c "import json,sys; lst = [str(lb['LoadBalancerName']) for lb in json.load(sys.stdin)['LoadBalancerDescriptions'] if 'VPCId' in lb and lb['VPCId'] == '$1']; print('\n'.join(lst))"
```
Comment (justinsb) [inline cluster/aws/util.sh]: I think you could also do `if lb.get('VPCId') ==`.  This way is more verbose but likely clearer.

**Comment by justinsb** [comment]
LGTM.  Can you change the topic of the commit though - put a description like "AWS kube-up: don't fail if ELB not in VPC" (i.e. no issue # here).  And then in the body include "Fixes #23784" on a line by itself, and then github will auto close the issue when this merges.

One comment on the python, but on second thoughts I like your way better.

Thanks for the fix!

**Comment by justinsb** [comment]
ok to test
