### PR TITLE
Fixing hooks/description to catch API fields without description tags

### LINKED ISSUE #7080: verify-description.sh doesn't seem to be triggering API json errors correctly
PR #6597 had a few errors in its API objects, where the "description" field errors in its JSON declarations were missing. But, the "verify-description.sh" presubmit check didn't flag them. This should be investigated and fixed.

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/7080

Looks like hooks/description broke in https://github.com/GoogleCloudPlatform/kubernetes/pull/5150

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

File: pkg/api/v1/types.go [hunk 1]
```diff
@@ -519,25 +519,25 @@ type VolumeMount struct {
 type EnvVar struct {
 	// Required: This must be a C_IDENTIFIER.
 	Name string `json:"name" description:"name of the environment variable; must be a C_IDENTIFIER"`
-	// Optional: defaults to "".
+	// Optional: No more than one of the following may be set.
```
Comment (nikhiljindal) [inline pkg/api/v1/types.go]: These changes are because I copied v1beta3 to v1 again, so this now includes changes to v1beta3 that happened while https://github.com/GoogleCloudPlatform/kubernetes/pull/7454 was in review.

File: hooks/description.sh [hunk 2]
```diff
@@ -17,7 +17,7 @@
 # Print 1 if the file in $1 is not in need of additional field descriptions, 0 otherwise.
 FILE="$1"
 
-if grep json: "${FILE}" | grep -v ,inline | grep -v -q description: | grep -v // ; then
+if grep json: "${FILE}" | grep -v // | grep -v ,inline | grep -v -q description: ; then
```
Comment (bgrant0607) [inline hooks/description.sh]: Does "description:" need to be quoted?

**Comment by bgrant0607** [comment]
Thanks! LGTM

File: hooks/description.sh (hunk 2 above)
Comment (bgrant0607) [inline hooks/description.sh]: Good catch, btw.
