### PR TITLE
fix longRunningRequestRE to something that doesn't match pretty much all requests

### LINKED ISSUE #9840: longRunningRE matches practically all requests
longRunningRE defaults to:
```
regexp.MustCompile("[.*\\/watch$][^\\/proxy.*]")
```

That is supposed to reject paths that should be rate-limited. Turns out, it matches pretty much every request made to the API: http://play.golang.org/p/K1voSIkX4K

Basically, any string with one of these characters:
```
. * / w a t c h $
```
followed by something other than one of these characters:
```
^ / p r o x y . *
```
anywhere in the path

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #9840 
cc @liggitt

### CODE REVIEW

File: cmd/kube-apiserver/app/server_test.go [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+		"/api/v1/watch-namespace/",
+		"/api/v1/namespace-proxy/",
+		"api/v1/watch/stuff",
+		". anything",
+		"/ that",
+	}
+	doMatch := []string{
+		"/api/v1/pods/watch",
+		"/api/v1/default/service/proxy",
+		"/api/v1/pods/proxy/path/to/thing",
```
Comment (liggitt) [inline cmd/kube-apiserver/app/server_test.go]: I think we should also match these urls, which are expected to be long-running:
* `/api/v1/namespaces/myns/pods/mypod/logs`
* `/api/v1/namespaces/myns/pods/mypod/portforward`
* `/api/v1/namespaces/myns/pods/mypod/exec`
* `/api/v1/watch/namespaces/myns/pods`

File: cmd/kube-apiserver/app/server.go [hunk 2]
```diff
@@ -51,7 +51,8 @@ import (
 const (
 	// Maximum duration before timing out read/write requests
 	// Set to a value larger than the timeouts in each watch server.
-	ReadWriteTimeout = time.Minute * 60
+	ReadWriteTimeout            = time.Minute * 60
+	defaultLongRunningRequestRE = "(/watch$|/proxy(/.*|))"
```
Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: * can't assume `/watch` terminates the string
* `(/.*|)` without an anchor in the second half is meaningless

**Comment by liggitt** [comment]
Since fixing this could drastically change how incoming requests are bucketed, this should get attention from whoever is doing performance tuning to decide if the `MaxRequestsInFlight` default of 400 still makes sense

**Comment by erictune** [comment]
@bprashanth are you a good person to comment on MaxRequestInFlight?

**Comment by mikedanese** [comment]
@liggitt addressed comments. Please take another look.

**Comment by bprashanth** [comment]
Thanks for fixing this. We pretty much never hit our max-inflight-requests limit, it's too high, probably why this hasn't been noticed. LGTM.

**Comment by bprashanth** [comment]
I take that back, this hasn't been noticed because we ignore everything. 400 shold be high enough for most of our scalability testing through.

**Comment by bprashanth** [comment]
should be good to merge

File: cmd/kube-apiserver/app/server.go [hunk 3]
```diff
@@ -51,7 +51,8 @@ import (
 const (
 	// Maximum duration before timing out read/write requests
 	// Set to a value larger than the timeouts in each watch server.
-	ReadWriteTimeout = time.Minute * 60
+	ReadWriteTimeout            = time.Minute * 60
+	defaultLongRunningRequestRE = "(/watch(/.*|)$|/proxy(/.*|)$|logs(/|)$|portforward(/|)$|exec(/|)$)"
```
Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: simplify this to?
```
"(/|^)(watch|proxy|logs|portforward|exec)(/|$)"
```

Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: also add a TODO that this still needs tightening (currently matches path segments for namespaces/names of things named "watch", "proxy", etc

Comment (mikedanese) [inline cmd/kube-apiserver/app/server.go]: It can be somewhat simplified. It's my understanding that /watch/ and /proxy/ can have more path after but portforward, logs, and exec have to be at the end of the path. Is that incorrect?

Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: I'm not sure.. @csrwng, are all params to pods/logs, pods/portforward, pods/exec done as query params, or can you also have path params?

Comment (csrwng) [inline cmd/kube-apiserver/app/server.go]: you can have path params as in pods/proxy/{path}

Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: I know subpaths are possible for proxy, wasn't sure about the others

Comment (mikedanese) [inline cmd/kube-apiserver/app/server.go]: @csrwng but not on logs, portforward, and exec right?

**Comment by mikedanese** [comment]
added comment and simplified.

File: cmd/kube-apiserver/app/server.go [hunk 4]
```diff
@@ -52,6 +52,8 @@ const (
 	// Maximum duration before timing out read/write requests
 	// Set to a value larger than the timeouts in each watch server.
 	ReadWriteTimeout = time.Minute * 60
+	//TODO: This can be tightened up. It still matches objects named watch or proxy.
+	defaultLongRunningRequestRE = "(/|^)((watch|proxy)(/.*|)|(logs|portforward|exec)(/|))$"
```
Comment (liggitt) [inline cmd/kube-apiserver/app/server.go]: * Don't make the watch/proxy rule match to the end of the string, just ensure it is followed by `(/|$)`
* Simplify `(/|)` to `/?`

Something like:
```
"(/|^)((watch|proxy)(/|$)|(logs|portforward|exec)/?$)"
```

**Comment by liggitt** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
So if I use watch as a query parameter (which server supports and was supposed to replace /watch ) am I no longer allowed to be treated as a long running operation?

**Comment by liggitt** [comment]
The regex is/was only checked against the URL path. Detecting long running requests via params is a separate change and worth another issue
