### PR TITLE
Set the annotation only if the test requires it.

### LINKED ISSUE #36107: StatefulSet cannot scale down after network partition is healed sometimes
**What happened**:
https://github.com/kubernetes/kubernetes/issues/36035

**What you expected to happen**:
The statefulset should have scaled down to 0.
Instead, even after 10 minutes:

```
~/g/s/k/kubernetes (kenspr) kubectl.sh --namespace=e2e-tests-network-partition-837rt get statefulsets
NAME      DESIRED   CURRENT   AGE
pet       0         0         17m

~/g/s/k/kubernetes (kenspr) kubectl.sh --namespace=e2e-tests-network-partition-837rt get pods
NAME      READY     STATUS    RESTARTS   AGE
pet-0     1/1       Running   0          7m
pet-1     1/1       Running   0          17m
pet-2     1/1       Running   0          17m
```

**How to reproduce it** (as minimally and precisely as possible):
Run the `[StatefulSet] should not reschedule pets if there is a network partition [Slow] [Disruptive]` e2e test on a gce cluster running the latest and greatest kubernetes.

cc @smarterclayton @bprashanth @kubernetes/sig-apps

### PR DESCRIPTION
**Pull request by foxish**
**What this PR does / why we need it**: Fixes StatefulSet flake

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/36107

**Special notes for your reviewer**: We shouldn't be setting the debug annotation in all our tests, only the ones that bring statefulset pods up one after another. In the absence of the annotation, we have the new default behavior governed by https://github.com/kubernetes/kubernetes/pull/35739

**Release note**:
```release-note
NONE
```

cc @kubernetes/sig-apps @bprashanth @calebamiles

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36212)

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot gci gke e2e test this

**Comment by foxish** [comment]
@k8s-bot node e2e test this

**Comment by bprashanth** [comment]
Suggest changing the comment or log line that confused you into something more representative of what's going on, maybe even add an event. @janetkuo should go ahead and do this review since I may not have time to by freeze (though we don't stricly need it in by then).

File: test/e2e/network_partition.go [hunk 1]
```diff
@@ -391,7 +391,7 @@ var _ = framework.KubeDescribe("Network Partition [Disruptive] [Slow]", func() {
 			Expect(err).NotTo(HaveOccurred())
 
 			pst := statefulSetTester{c: c}
-			pst.saturate(ps)
```
Comment (janetkuo) [inline test/e2e/network_partition.go]: Keep this and remove `setHealthy`

**Comment by foxish** [comment]
@k8s-bot node e2e test this

**Comment by foxish** [comment]
@bprashanth Thanks! You're right, I'll modify the event in another PR. I'd like to get this test fix in before the other node controller changes are merged, so that we know that the current petset behavior is retained. 
@janetkuo can you PTAL?

File: test/e2e/network_partition.go (hunk 1 above)
Comment (foxish) [inline test/e2e/network_partition.go]: `saturate` does the step-wise initialization of pets when we have the debug annotation set. Since we don't have it set here, we can just wait for all the replicas to start running? I'm not sure why we should call saturate here.

File: test/e2e/petset.go [hunk 2]
```diff
@@ -311,6 +314,7 @@ var _ = framework.KubeDescribe("Pet set recreate [Slow] [Feature:PetSet]", func(
 
 		By("creating statefulset with conflicting port in namespace " + f.Namespace.Name)
 		ps := newStatefulSet(statefulSetName, f.Namespace.Name, headlessSvcName, 1, nil, nil, labels)
+		setInitializedAnnotation(ps, "false")
```
Comment (janetkuo) [inline test/e2e/petset.go]: remove this

File: test/e2e/network_partition.go (hunk 1 above)
Comment (janetkuo) [inline test/e2e/network_partition.go]: I see. Sounds good

**Comment by janetkuo** [comment]
One comment and LGTM otherwise
