### PR TITLE
Remove ready directory which created in empty volumeMounter setUp func

### LINKED ISSUE #72675: configmap volume should delete the "ready" file of the internal emptydir volume on mount failure
**What happened**:
There is a node in my cluster whose disk is full on root partition, I cleared the disk and then rebooted the node to recover it. After the reboot, the kube-proxy on that node got stuck in "ContainerCreating" status and never changes, and all other pods can't run properly since the kubeproxy is not runing.

**What you expected to happen**:
Kubeproxy on that node can run normally after the disk clean and reboot

**How to reproduce it (as minimally and precisely as possible)**:
1. make the disk full on root partition
-  in my env, leave roughly 100k space on root partition would make this issue more reproducible

- this issue is kind of tricky, to reproduce it, one need to populate the disk repeatedly since some disk space would be cleared because of pod eviction

-  the kube-proxy got deleted and created repeatedly because of pod eviction and daemon-set mechanism, it would stuck in ContainerCreating status if the disk space is not enough for creating volume contents of kube-proxy configMap volume, the first pod error event is like:
_MountVolume.Setup failed for volume "kube-proxy":.....no space left on device_

- After it got stuck, the following  pod error event woud repeat over and over, kube-proxy is trying to mount configMap volume but always fail
_MountVolume.Setup failed for volume "kube-proxy": stat /var/lib/kubelet/pods/{pod_id}/volumes/kubernetes.io~configmap/kube-proxy no such file or directory_

2.clear the disk and reboot
- the reboot is neccesary to reproduce the issue, without the reboot the pod eviction would kick in to delete kube-proxy pod

3. now the kube-proxy woud stuck in ContainerCreating Status forever, restart kubelet has no effects on that, kube-proxy pod need to be mannully deleted to get recover
- kube-proxy pod can't mount  configMap volume, the following error keeps repeating
_MountVolume.Setup failed for volume "kube-proxy": stat /var/lib/kubelet/pods/{pod_id}/volumes/kubernetes.io~configmap/kube-proxy no such file or directory_

**Anything else we need to know?**:
After digging into this issue for a quite long time, i think the reason for this issue is:

The configMap volume uses emptyDir internally to create the volume directory, after the directory is created, configMap volume failed to populate it with configMap content because the disk is full, then configMap volume calls emptyDir.tearDown() to clear the temp directory.

The problem is that emptyDir uses a "ready" file under /var/lib/kubelet/pods/{podId}/plugin/..  to determine whether the directory is created or not, if the ready file is present, then it wouldn't create the directory. The tearDown method only remove the directory, it doen't remove the ready file, so after the first out of disk error, the diretory creation always get skipped, hence no such file or directory error repeat over and over.

**Environment**:
- Kubernetes version (use `kubectl version`):
v.1.11.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
cent os 7
- Kernel (e.g. `uname -a`):
- Install tools:
kubeadm
- Others:

### PR DESCRIPTION
**Pull request by jingxu97**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Remove ready file and its directory (which is created during volume SetUp) during emptyDir volume TearDown

**Which issue(s) this PR fixes**:

Fixes #72675

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove ready file and its directory (which is created during volume SetUp) during emptyDir volume TearDown. 
```

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42 @jsafrane

Please help verify this PR. Thanks!

File: pkg/volume/emptydir/empty_dir.go [hunk 1]
```diff
@@ -421,6 +421,14 @@ func (ed *emptyDir) TearDown() error {
 
 // TearDownAt simply discards everything in the directory.
 func (ed *emptyDir) TearDownAt(dir string) error {
+	defer func() {
+		// remove ready dir which created in SetUp func
+		readyDir := ed.getMetaDir()
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir.go:426]: Do you know why we need this ready file? I could not tell from the original pr.

Would the setup be more resilient if we also checked for the directory existing in addition to the ready file? We already check for tmpfs that it's a mount point.

Can you add a unit test for this new behavior?

**Comment by msau42** [comment]
cc @yuga711

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

File: pkg/volume/emptydir/empty_dir.go (hunk 1 above)
Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir.go:426]: I have a theory based on digging old code and issues. https://github.com/kubernetes/kubernetes/pull/85136#issuecomment-676556803

We could add check on setup. Because setup should always create volume dir and then ready file, so logically it is enough to check ready file alone since it indicates volume dir already created. The issue is caused by teardown because it Only delete volume dir, not the ready file which leaves the situation. After this is fixed, then the logic should be right.

Comment (msau42) [reply pkg/volume/emptydir/empty_dir.go:426]: at least changing permissions on empty directory or tmpfs mount should not take a long time. Maybe hugepages?

Doing only teardown means that we rely on teardown to be called in all cases. Do we handle reconstruction and uncertain mount scenarios properly?

Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir.go:426]: this is my guess, need to confirm with original author Paul.

Actually now checking other type of volumes which do not use this ready file, it might be some potential issues. e.g., in gce pd setup()

1. first setup call finishes mounting, and not yet to start to set ownership, now kubelet restarts
2. second setup call checks mount already exists, and will return success, without actually setting up ownership anymore?

ready files seems more useful for this type of volume type actually, which is not used..

Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir.go:426]: If we add the check of volum dir during setup, I think we should remove ready file First to avoid the following situation

1. in first setup call, because it creates volume dir and ready file, but fail to write payload, it will trigger teardown, volume dir is deleted, but ready file could not be removed temporally 
2. a second setup call is issued, check volume dir does not exist, create it and might not yet start to change ownership (takes some time), kubelet restarts
3. a third setup call comes, it see both ready file and volume dir, it will think it is ready and go ahead to write data (ownership is not set correctly yet?)

Comment (msau42) [reply pkg/volume/emptydir/empty_dir.go:426]: If you remove ready file first during the teardown, does it solve that race?

I do agree if you need to call setup directories again, ready file should be removed first.

Comment (msau42) [reply pkg/volume/emptydir/empty_dir.go:426]: For general issue of fsgroup, I do think it would be better to have it in two phases so we can recover from those partial scenarios. Related issues:
https://github.com/kubernetes/kubernetes/issues/78130
https://github.com/kubernetes/kubernetes/issues/89776

Comment (yuga711) [reply pkg/volume/emptydir/empty_dir.go:426]: The original ready file logic seems to have been introduced to indicate the emptyDir setup is complete. It doesn't seem to be related to the time taken for hugePages etc., At the time of [original CL](https://github.com/kubernetes/kubernetes/pull/9384/files), hugepageMedium support doesnt seem to exist. 

During teardown, if we remove the ready file first, then restarted kubelet might attempt to SetVolumeOwnership->changeFilePermission(). In that case, I am thinking if the current file permissions may prevent new permission changes.

Comment (msau42) [reply pkg/volume/emptydir/empty_dir.go:426]: I think kubelet needs to run as root so that it can change any permissions

Comment (yuga711) [reply pkg/volume/emptydir/empty_dir.go:426]: Update: If current file permissions can prevent further permission changes, I think the current logic is no better. During setup, if kubelet crashes before creating readyfile, the restarted kubelet will reattempt to set the permissions.

Comment (yuga711) [reply pkg/volume/emptydir/empty_dir.go:426]: Yes, agree. running as root shouldn't prevent from setting the permissions.

**Comment by jingxu97** [comment]
Updated to address comments. PTAL

File: pkg/volume/emptydir/empty_dir_test.go [hunk 2]
```diff
@@ -194,6 +195,9 @@ func doTestPlugin(t *testing.T, config pluginTestConfig) {
 	}
 
 	// Stat the directory and check the permission bits
+	if !volumeutil.IsReady(metadataDir) {
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir_test.go:198]: Do you also want to add a test case for calling SetUp again when readydir exists but volume directory does not?

File: pkg/volume/emptydir/empty_dir.go [hunk 3]
```diff
@@ -212,7 +212,12 @@ func (ed *emptyDir) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
 		if ed.medium == v1.StorageMediumMemory && !notMnt {
 			return nil
 		} else if ed.medium == v1.StorageMediumDefault {
-			return nil
+			// Further check dir exists
+			if _, err := os.Stat(dir); err == nil {
+				return nil
+			}
+			// This situation should not happen. In this case, print a warning for it.
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir.go:219]: Should we remove readydir too?

**Comment by msau42** [comment]
You need to remove the "Fixes" line from your commit message

File: pkg/volume/emptydir/empty_dir.go (hunk 3 above)
Comment (yuga711) [reply pkg/volume/emptydir/empty_dir.go:219]: I think we can. Since the current order of operations in setup() and tearDown() guarantee that readyfile shouldn't exist if vol-dir does not exist. I think this situation happens only if someone deletes vol-dir out of band. In that case, kubelet restart is needed to recover, irrespective of we delete the readydir here or not. Isnt it?

Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir.go:219]: y, no matter readyfile exist or not, we want to continue to recover. I think if in the case we allow concurrent volume setup, delete ready file is a must to avoid another process see ready exist and path exist and then consider setup is done while the first one is still in the middle of setting up permission and ownership. Although in operation executor, we don't allow the same volume same pod to start concurrent volume setup calls, this should not be an issue. But I agree delete ready file might be safer in case we have bugs on allowing concurrent operations.

**Comment by jingxu97** [comment]
updated PR. PTAL

File: pkg/volume/emptydir/empty_dir.go [hunk 4]
```diff
@@ -208,11 +208,21 @@ func (ed *emptyDir) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
...
-			return nil
+			// Further check dir exists
+			if _, err := os.Stat(dir); err == nil {
+				return nil
+			}
+			// This situation should not happen unless user manually delete volumd dir.
+			// In this case, delete ready file and print a warning for it.
+			klog.Warningf("volume ready file dir %s exist, but volume dir %s does not. Remove ready dir", readyDir, dir)
+			if err := os.RemoveAll(readyDir); err != nil && !os.IsNotExist(err) {
+				return fmt.Errorf("failed to remove ready dir [%s]: %v", readyDir, err)
```
Comment (yuga711) [inline pkg/volume/emptydir/empty_dir.go:224]: Why not continue here, instead of failing the setup()? I think there is no downside with continuing.

Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir.go:224]: either way seems fine to me. I cannot think of cases that this failure will happen unless system crashes.

File: pkg/volume/emptydir/empty_dir.go [hunk 5]
```diff
@@ -208,11 +208,21 @@ func (ed *emptyDir) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
...
+	if volumeutil.IsReady(readyDir) {
 		if ed.medium == v1.StorageMediumMemory && !notMnt {
 			return nil
 		} else if ed.medium == v1.StorageMediumDefault {
-			return nil
+			// Further check dir exists
+			if _, err := os.Stat(dir); err == nil {
+				return nil
+			}
+			// This situation should not happen unless user manually delete volumd dir.
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir.go:220]: typo: volume

File: pkg/volume/emptydir/empty_dir_test.go [hunk 6]
```diff
@@ -236,14 +243,19 @@ func doTestPlugin(t *testing.T, config pluginTestConfig) {
 		t.Errorf("Got a nil Unmounter")
 	}
 
-	// Tear down the volume
-	if err := unmounter.TearDown(); err != nil {
-		t.Errorf("Expected success, got: %v", err)
+	if config.idempotent {
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir_test.go:246]: How come idempotent creates `volPath` but removes `metadataDir`?

Comment (msau42) [reply pkg/volume/emptydir/empty_dir_test.go:246]: Also why is it removed before teardown?

File: pkg/volume/emptydir/empty_dir_test.go [hunk 7]
```diff
@@ -119,6 +140,7 @@ func TestPluginHugetlbfs(t *testing.T) {
 type pluginTestConfig struct {
 	medium                        v1.StorageMedium
 	idempotent                    bool
+	readyDirOnly                  bool
```
Comment (msau42) [inline pkg/volume/emptydir/empty_dir_test.go:143]: Can you add comments explaining what `idempotent` and `readyDirfonly` do?

File: pkg/volume/emptydir/empty_dir_test.go (hunk 6 above)
Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir_test.go:246]: this idempotent setting is from previous PR, I am still not sure the exact reasoning behind it. It was used to indicate whether the Readyfile already exist or not before setting up the volume. In the previous design, readyFile could already exist because tear down does not delete it.

Now after changing the logic, I think maybe it is better to use different name since we are testing differently. Basically we have volumeDir, and readyDir, I am testing the following scenarios
1. neither volumeDir nor readyDir exist before volume setup
2. volumeDir exist, but not readyDir before setup
3. readyDir exist, volumeDir does not
4. both exist

For teardown, similarly it tests different scenarios to represent kubelet crashes or user intentionally delete dirs.
1. both dir exist
2. readyDir still exist, but not volumeDir
3. volumeDir still exist, but not readyDir

Comment (jingxu97) [reply pkg/volume/emptydir/empty_dir_test.go]: updated the test, PTAL

**Comment by msau42** [comment]
/approve

Thanks for adding all the permutations in the test!

You'll need to fix your commit message. And adding a release note about this bug fix would be good too.

**Comment by jingxu97** [comment]
This PR is originally from  https://github.com/kubernetes/kubernetes/pull/85136 because the author is not working on it now.

**Comment by jingxu97** [comment]
/retest

finally fix the commit message issue, (still not sure what is the reason). PTAL

**Comment by jingxu97** [comment]
I think we should cherry-pick this change.
