### PR TITLE
Make CPU manager release CPUs when Pod enters completed phase. 

### LINKED ISSUE #52351: Static CPU manager policy should release allocated CPUs when container enters "completed" phase.
/kind bug
/sig node

When the `restartStrategy` is set to `Never` and a container that was granted exclusive CPUs terminates with a normal exit status, the CPU Manager never receives a `RemoveContainer` call. Kuberuntime should be updated to invoke the container manager's `PostStopContainer` hook on detecting normal termination for these containers. This method is already idempotent since it is currently invoked both from kuberuntime's `killContainer` and `removeContainer` (the latter of which is invoked by GC.)

**How to reproduce it (as minimally and precisely as possible)**:

* Start singleton cluster with static CPU manager policy enabled.
* Start a guaranteed pod with a single container that consumes 1 CPU (to get an exclusive allocation) with restartPolicy never that simply exits `0`.
* Try to start a similar container that won't fit on the node unless the first container's CPU is reaped.
* Observe the second container fails with insufficient CPUs, and this problem does not resolve even after an extended period of time.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8 beta
- Cloud provider or hardware configuration**: all
- OS (e.g. from /etc/os-release): all

cc @derekwaynecarr @sjenning @balajismaniam

### PR DESCRIPTION
**Pull request by balajismaniam**
**What this PR does / why we need it**: When CPU manager is enabled, this PR releases allocated CPUs when container is not running and is non-restartable. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52351

**Special notes for your reviewer**:
This bug is only reproduced for pods with `restartPolicy` = `Never` or `OnFailure`.  The following output is from a 4 CPU node. This bug can be reproduced as long >= half the cores are requested. 

pod1.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  containers:
  - image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "sleep 5"]
    name: test-container1
    resources:
      requests:
        cpu: 2
        memory: 100Mi
      limits:
        cpu: 2
        memory: 100Mi
  restartPolicy: "Never"
```

pod2.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
spec:
  containers:
  - image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "sleep 5"]
    name: test-container1
    resources:
      requests:
        cpu: 2
        memory: 100Mi
      limits:
        cpu: 2
        memory: 100Mi
  restartPolicy: "Never"
```
Run a local Kubernetes cluster with CPU manager enabled. 
```sh
KUBELET_FLAGS='--feature-gates=CPUManager=true --cpu-manager-policy=static --cpu-manager-reconcile-period=1s --kube-reserved=cpu=500m' ./hack/local-up-cluster.sh
```
_Before:_
Create `test-pod1` using pod1.yaml. 
```
./cluster/kubectl.sh create -f pod1.yaml
```
Wait for the pod to complete and wait another 90 seconds (give enough time for GC to kick-in). 

Create `test-pod2` using pod2.yaml. 
```
./cluster/kubectl.sh create -f pod2.yaml
```

Get all pods in the cluster. 
```
./cluster/kubectl.sh get pods -a
NAME        READY     STATUS                                         RESTARTS   AGE
test-pod1   0/1       Completed                                      0          1m
test-pod2   0/1       not enough cpus available to satisfy request   0          9s
```

_After:_
Create `test-pod1` using pod1.yaml. 
```
./cluster/kubectl.sh create -f pod1.yaml
```
Wait for the pod to complete and wait another 90 seconds (give enough time for GC to kick-in). 

Create `test-pod2` using pod2.yaml. 
```
./cluster/kubectl.sh create -f pod2.yaml
```

Get all pods in the cluster. 
```
./cluster/kubectl.sh get pods -a
NAME        READY     STATUS      RESTARTS   AGE
test-pod1   0/1       Completed    0          1m
test-pod2   0/1       Completed    0          9s
```

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
cc @derekwaynecarr could we add the v1.8 milestone please?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -481,6 +481,13 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
 				message := fmt.Sprintf("Container %+v is dead, but RestartPolicy says that we should restart it.", container)
 				glog.Info(message)
 				changes.ContainersToStart = append(changes.ContainersToStart, idx)
+			} else {
```
Comment (ConnorDoyle) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: I think we can call PostStopContainer unconditionally here, since at this point the container ID doesn't refer to a running container. This could prevent the next container restart from failing due to inability to allocate CPUs (because of a race between this sync and the garbage collector.)

**Comment by balajismaniam** [comment]
@ConnorDoyle Updated. PTAL.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -474,6 +474,17 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
 	// check the status of containers.
 	for idx, container := range pod.Spec.Containers {
 		containerStatus := podStatus.FindContainerStatusByName(container.Name)
+
+		// Call internal container post-stop lifecycle hook for any non-running container so that any
+		// allocated cpus are released immediately. If the container is restarted, cpus will be re-allocated
+		// to it.
+		if containerStatus != nil && containerStatus.State != kubecontainer.ContainerStateRunning {
```
Comment (jiaxuanzhou) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: what will happen when `containerStatus.State == kubecontainer.ContainerStateCreated` ?

**Review by jiaxuanzhou — CHANGES_REQUESTED** [review]

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (balajismaniam) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: The container will be restarted as per https://github.com/kubernetes/kubernetes/blob/ccaaf5cad5901f26283bfa8c2b230dc1dc3579b4/pkg/kubelet/container/helpers.go#L77. See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L480.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -474,6 +474,17 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
...
+			if err := m.internalLifecycle.PostStopContainer(containerStatus.ID.ID); err != nil {
+				glog.Errorf("internal container post-stop lifecycle hook failed for container ID %v with error %v",
```
[the remark this answers is not in the document]
Comment (balajismaniam) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Updated.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (ConnorDoyle) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: The same question could be asked for the existing condition in the next block. I believe this is because in the runtime, `startContainer` both creates and starts the container so we won't see the created state from this sync loop.

Comment (ConnorDoyle) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: To be more explicit, we could check for only the terminal container states. WDYT @balajismaniam ?

Comment (ConnorDoyle) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: It would be even nicer if there were a helper predicate to determine which container states are actually terminal. Then if a new one is added we wouldn't have to track down and re-vet all the conditions. Nice to have, we can propose that in a follow-up maybe.

Comment (balajismaniam) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: @ConnorDoyle I think we should leave the code as is (i.e., check for all non-running container states). It will help in a scenarios where `createContainer` + pre-start lifecycle hook is called but not `startContainer` (might not be possible but it will be useful to guard against it). Also, if the container ends-up in create or unknown state, it will be restarted anyways.

Comment (balajismaniam) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Agree with the helper predicate. We can propose it.

**Comment by ConnorDoyle** [comment]
Reproduced and verified the fix manually as in the PR description.

/lgtm

**Comment by sjenning** [comment]
@balajismaniam federation test is broken and now not blocking.  We just need to get this in the 1.8 milestone. @derekwaynecarr can you do this?

**Comment by balajismaniam** [comment]
Thanks @sjenning. Didn't realize it was broken again (it was passing for me yeterday).

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (derekwaynecarr) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: is it possible that this hook gets called multiple times for the same container?

**Comment by derekwaynecarr** [comment]
this is a bug, adding to milestone, had the one question to ensure that handlers will never throw an error if called multiple times for the same container.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (balajismaniam) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Yes, it is possible. But the call is idempotent and hence safe to call here.

**Comment by balajismaniam** [comment]
Thanks @derekwaynecarr.

**Comment by derekwaynecarr** [comment]
verified that this is fine if called multiple times.

/lgtm
/approve

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (ConnorDoyle) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Yes, this is already the case, since we call RemoveContainer from both PreStopContainer and PostStopContainer.

**Comment by sjenning** [comment]
verify test flaked with `No space left on device`

/retest

**Comment by balajismaniam** [comment]
The same test has been failing since yesterday: https://k8s-testgrid.appspot.com/sig-instrumentation#gce-sd-logging.

**Comment by sjenning** [comment]
federation test is non-blocking.  we are in the queue at last! https://submit-queue.k8s.io/#/queue

**Comment by ConnorDoyle** [comment]
👍
