### PR TITLE
Link kernel log files to have them be copied over as part of node e2e.

### LINKED ISSUE #25993: Collect more logs (e.g., docker.log, kern.log) for node e2e tests
https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/25701/node-pull-build-e2e-test/6866/build-log.txt

```
------------------------------
â€¢ Failure [300.010 seconds]
Container runtime Conformance Test
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:314
  container runtime conformance blackbox test
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:313
    when start a container that keeps running
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:201
      it should run with the expected status [Conformance] [It]
      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:200

      Timed out after 300.000s.
      Expected
          <api.PodPhase>: Pending
      to equal
          <api.PodPhase>: Running

      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:173
------------------------------
STEP: it should get the expected 'RestartCount'
â€¢ Failure [300.012 seconds]
Container runtime Conformance Test
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:314
  container runtime conformance blackbox test
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:313
    when start a container that exits failure
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:255
      it should run with the expected status [Conformance] [It]
      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:254

      Timed out after 300.000s.
      Expected
          <int32>: 0
      to be >
          <int32>: 0

      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:238
------------------------------
â€¢ Failure [20.011 seconds]
Container runtime Conformance Test
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:314
  container runtime conformance blackbox test
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:313
    when running a container with invalid image
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:306
      it should run with the expected status [Conformance] [It]
      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:305

      Expected error:
          <*errors.errorString | 0xc82064aa60>: {
              s: "Failed to get container status",
          }
          Failed to get container status
      not to have occurred

      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:287
------------------------------
STEP: Creating a host exec pod
â€¢ Failure [120.061 seconds]
PrivilegedPod
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:83
  should test privileged pod [It]
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:82

  Failed waiting for pod "privileged-pods/hostexec" to become running: Time out while waiting for pod privileged-pods/hostexec to become running; current status: {Phase:Pending Conditions:[] Message: Reason: HostIP: PodIP: StartTime:<nil> InitContainerStatuses:[] ContainerStatuses:[]}
  Expected error:
      <*errors.errorString | 0xc820652ef0>: {
          s: "Time out while waiting for pod privileged-pods/hostexec to become running; current status: {Phase:Pending Conditions:[] Message: Reason: HostIP: PodIP: StartTime:<nil> InitContainerStatuses:[] ContainerStatuses:[]}",
      }
      Time out while waiting for pod privileged-pods/hostexec to become running; current status: {Phase:Pending Conditions:[] Message: Reason: HostIP: PodIP: StartTime:<nil> InitContainerStatuses:[] ContainerStatuses:[]}
  not to have occurred

  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:210
------------------------------
STEP: create the static pod
STEP: wait for the mirror pod to be running
STEP: delete the static pod
STEP: wait for the mirror pod to disappear
â€¢ Failure in Spec Setup (BeforeEach) [120.003 seconds]
MirrorPod
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:121
  when create a mirror pod 
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:120
    should be updated when static pod updated [BeforeEach]
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:79

    Timed out after 120.000s.
    Expected
        <*errors.errorString | 0xc82067a680>: {
            s: "expected the mirror pod \"static-pod-85b2b301-1e2c-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" to appear: pods \"static-pod-85b2b301-1e2c-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" not found",
        }
    to be nil

    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56
------------------------------
STEP: create the static pod
STEP: wait for the mirror pod to be running
STEP: delete the static pod
STEP: wait for the mirror pod to disappear
â€¢ Failure in Spec Setup (BeforeEach) [120.003 seconds]
MirrorPod
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:121
  when create a mirror pod 
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:120
    should be recreated when mirror pod gracefully deleted [BeforeEach]
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:94

    Timed out after 120.000s.
    Expected
        <*errors.errorString | 0xc82067a680>: {
            s: "expected the mirror pod \"static-pod-cd39ca0c-1e2c-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" to appear: pods \"static-pod-cd39ca0c-1e2c-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" not found",
        }
    to be nil

    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56
------------------------------
STEP: create the static pod
STEP: wait for the mirror pod to be running
STEP: delete the static pod
STEP: wait for the mirror pod to disappear
â€¢ Failure in Spec Setup (BeforeEach) [120.003 seconds]
MirrorPod
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:121
  when create a mirror pod 
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:120
    should be recreated when mirror pod forcibly deleted [BeforeEach]
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:109

    Timed out after 120.000s.
    Expected
        <*errors.errorString | 0xc82067a680>: {
            s: "expected the mirror pod \"static-pod-14c0cf9b-1e2d-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" to appear: pods \"static-pod-14c0cf9b-1e2d-11e6-8f61-42010af00032-tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image\" not found",
        }
    to be nil

    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56
------------------------------


Summarizing 7 Failures:

[Fail] Container runtime Conformance Test container runtime conformance blackbox test when start a container that keeps running [It] it should run with the expected status [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:173

[Fail] Container runtime Conformance Test container runtime conformance blackbox test when start a container that exits failure [It] it should run with the expected status [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:238

[Fail] Container runtime Conformance Test container runtime conformance blackbox test when running a container with invalid image [It] it should run with the expected status [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:287

[Fail] PrivilegedPod [It] should test privileged pod 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/privileged_test.go:210

[Fail] MirrorPod when create a mirror pod  [BeforeEach] should be updated when static pod updated 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56

[Fail] MirrorPod when create a mirror pod  [BeforeEach] should be recreated when mirror pod gracefully deleted 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56

[Fail] MirrorPod when create a mirror pod  [BeforeEach] should be recreated when mirror pod forcibly deleted 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/mirror_pod_test.go:56

Ran 18 of 18 Specs in 2020.805 seconds
FAIL! -- 11 Passed | 7 Failed | 0 Pending | 0 Skipped I0520 01:51:25.194944     951 e2e_node_suite_test.go:84] Tests Finished
I0520 01:51:25.196224     951 e2e_node_suite_test.go:118] Process Log For Failed Suite On tmp-node-e2e-a2b03fc4-e2e-node-coreos-stable20160218-image
```

### PR DESCRIPTION
**Pull request by vishh**
Fixes #25993

cc @pwittrock

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot test this github issue #26203

**Comment by vishh** [comment]
Adding a `P1` label because this PR will help debug other node e2e flakes.

File: test/e2e_node/e2e_service.go [hunk 1]
```diff
@@ -208,6 +209,24 @@ func (es *e2eService) startServer(cmd *healthCheckCommand) error {
...
+	"/var/log/messages",
+	"/var/log/docker.log",
+}
+
+// Add hard links to log files that are of interest.
+// Since we scp files from the remote directory, hardlinks will be treated as normal files and file contents will be copied over.
+func linkLogFiles() {
+	for _, file := range logFiles {
+		targetLink := path.Join(*reportDir, path.Base(file))
+		if err := os.Symlink(file, targetLink); err != nil {
```
Comment (pwittrock) [inline test/e2e_node/e2e_service.go]: fwiw, this will fail if the logs are on a different partition because you can't link across partitions.  That may be fine for now.

Comment (vishh) [inline test/e2e_node/e2e_service.go]: Good point. I can't think of a node now that will hit that issue though.

On Thu, May 26, 2016 at 10:58 AM, Phillip Wittrock <notifications@github.com

Comment (pwittrock) [inline test/e2e_node/e2e_service.go]: SGTM.  We can fix it when it breaks.

**Comment by pwittrock** [comment]
The logs seem to be missing from the test artifacts in the PR builder.

**Comment by vishh** [comment]
Yeah. Thats why I marked it as `do-not-merge`. Investigating. It works
locally.

On Thu, May 26, 2016 at 12:10 PM, Phillip Wittrock <notifications@github.com

**Comment by vishh** [comment]
@pwittrock Updated patch. PTAL.

**Comment by pwittrock** [comment]
For some reason the junit_01-04.xml files are missing from the artifacts.  Any idea why?

**Comment by pwittrock** [comment]
FYI, need to add the known flag txt:

>
Verifying ./hack/../hack/verify-flags-underscore.py
Found flags in golang files not in the list of known flags. Please add these to hack/verify-flags/known-flags.txt
image-project

**Comment by vishh** [comment]
@pwittrock I do see the `junit*.xml` files. Is the naming format incorrect? https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26314/node-pull-build-e2e-test/8104/artifacts/

**Comment by pwittrock** [comment]
The junit files need to be copied directly under artifacts/ so that jenkins can locate them (not just in the host subdirectory).  AFAICT junit 0-4 seem to be missing from artifacts.

**Comment by pwittrock** [comment]
Nothing you changed should have affected this though...

**Comment by pwittrock** [comment]
Ah, I think I found a bug in logging in the existing code: .RunRemote doesn't return the error from copying test artifacts, so it may have failed without us realizing it.

**Comment by pwittrock** [comment]
@k8s-bot node e2e test this issue: #26435

**Comment by pwittrock** [comment]
PR #26437 May help us figure out what is going on.

**Comment by vishh** [comment]
Recent changes should satisfy our pre-submit hooks.

**Comment by vishh** [comment]
I'm unsure why the junit files are not being copied over. I enabled error reporting from the framework for copy failures. Let's see why it failed.

**Comment by vishh** [comment]
This PR does not work on CoreOS. I need to add a journalctl source for logs of interest.

**Comment by vishh** [comment]
@pwittrock node e2e is failing because of Core OS, which requires a journald plugin for collecting kernel logs. I will update this PR to include a journald option in a bit.

**Comment by vishh** [comment]
@pwittrock Added `journalctl` support. PTAL.

**Comment by vishh** [comment]
Logs are now available for all our current distros. https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26314/node-pull-build-e2e-test/8733/artifacts/

Now I need to find out why the runtime is panicking after running the tests.

**Comment by vishh** [comment]
Tests are passing locally without any issues. I hope it passes on jenkins as well.

**Comment by vishh** [comment]
Found out the issue. Invalid link causes scp to panic. Ubuntu stores docker logs in a different directory..

File: test/e2e_node/e2e_remote.go [hunk 2]
```diff
@@ -188,6 +188,7 @@ func RunRemote(archive string, host string, cleanup bool, junitFileNumber int) (
 	glog.Infof("Copying test artifacts from %s", host)
 	scpErr := getTestArtifacts(host, tmp)
 	exitOk := true
+	glog.Errorf("vishh: %v", scpErr)
```
Comment (dims) [inline test/e2e_node/e2e_remote.go]: Should this be printed inside the "if scpErr != nil" below? Looks like a temporary/local change
