### PR TITLE
devicemanager: fix cleanup of unhealthy devices

### LINKED ISSUE #133702: Device Plugins: "Unexpected: unhealthyDevices and endpoints became out of sync"
### What happened?

Kubelet puts this error in the log 5 minutes (`endpointStopGracePeriod` I guess) after running DRA e2e "supports extended resources together with ResourceClaim" test: `I0822 10:03:19.580504 2854861 devicemanager.go:471] "Unexpected: unhealthyDevices and endpoints became out of sync"`

### What did you expect to happen?

endpoints and unhealthyDevices (whatever this means) should be in sync and `Unexpected` error should not occur.

### How can we reproduce it (as minimally and precisely as possible)?

Running DRA test case `supports extended resources together with ResourceClaim` and then waiting for 5 minutes and then grepping kubelet logs.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
today's (Tue Aug 26 13:15:14 EEST 2025) master branch
```console
$ KUBECONFIG=/var/run/kubernetes/admin.kubeconfig ./cluster/kubectl.sh version
Using image: cos-109-17800-570-37 from project: cos-cloud as master image
Using image: cos-109-17800-570-37 from project: cos-cloud as node image
Client Version: v1.35.0-alpha.0.50+091f87c10bc353-dirty
Kustomize Version: v5.7.1
Server Version: v1.35.0-alpha.0.50+091f87c10bc353-dirty```
</details>


### Cloud provider

<details>
skeleton
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -a
Linux dev 6.11.0-24-generic #24~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 25 20:14:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
ginkgo
</details>

### Container runtime (CRI) and version (if applicable)

<details>
$ containerd --version
containerd github.com/containerd/containerd/v2 v2.1.4 75cb2b7193e4e490e9fbdc236c0e811ccaba337
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Removed the resource from both healthy and unhealthy device maps when resource endpoint expires.
This makes resource endpoint and unhealthy device set consistent.

#### Which issue(s) this PR is related to:
Fixes #133702

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -450,6 +450,7 @@ func (m *ManagerImpl) GetCapacity() (v1.ResourceList, v1.ResourceList, []string)
 			}
 			delete(m.endpoints, resourceName)
 			delete(m.healthyDevices, resourceName)
+			delete(m.unhealthyDevices, resourceName)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cm/devicemanager/manager.go]: isn't this covered in the next loop?

Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go]: It is,  but `Unexpected: unhealthyDevices and endpoints became out of sync` error is raised before that(line 465). This happens because the above code removes resource from the `endpoints`(line 451), but leaves it in `unhealthyDevices`.

Comment (SergeyKanzhelev) [reply pkg/kubelet/cm/devicemanager/manager.go]: oh, fun. Why keeping the second loop then? This fix makes code complicated and hard to understand.

Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go]: If m.heathyDevices is empty, first loop will never be executed, so we need a second one. I suspect that the code will be even more complicated if we do it in one loop.

Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go]: This change per se makes sense, but I couldn't yet track down the reason why we end up with this code in the first place. The healthy/unhealthy split seems to be introduced in e9cf3f1ac4c97bea716fbac03d2cd71c5189d5c4 with further related changes in 5514a1f4dd60b35b4b9d4915744ec65aab40938f which hints about races between Allocate and endpoint deletion.

These flows and race opportunities are not well covered. Besides adding tests (and taking care of the existing ones, like we did for cpumanager) I'm not sure how much we can do, because I believe that fixing the API is a pretty hard task and we have DRA now. And we had other proposals to improve the general API which I'd rather investigate rather than painstakingly chase the current issues.

Of course, regressions are never acceptable, but I can't spot any obvious regressions here.

**Comment by ffromani** [comment]
the devicemanager code in general is surprisingly brittle and unfortunately, surprisingly poorly tested despite its age. The change makes sense to me and I don't see any obvious mistake.
I recommend to have clean pre-merge runs to gain confidence using the existing tests. I'll keep digging a bit in the history to learn if there are obvious reasons the code is the way it is. Once we have continuous green signal for a bit we can merge, I think.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/cm/devicemanager/manager.go]: Can the fix be changed by adding devices to `deletedResources` in two loops and then a single loop to clean them up from both lists? This way we are not deleting anything from the map that we iterating. Also it is a single place to delete from both collection without cross deletion.

Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go]: @SergeyKanzhelev Thanks for the idea! Done, PTAL.

**Comment by SergeyKanzhelev** [comment]
this is LGTM

@bart0sh can you please rebase?

@ffromani do you like how it looks now? I think this way code is very clear and straightforward

**Comment by bart0sh** [comment]
> this is LGTM
> 
> @bart0sh can you please rebase?

Sorry, missed that. Rebased. PTAL.

**Review by ffromani — COMMENTED** [review]
/triage accepted
/priority important-longterm

**Comment by ffromani** [comment]
/lgtm

yes, I think this is an improvement over the current state and I like the new shape of the code
