### PR TITLE
Fix GCE PD attach/detach issues

### LINKED ISSUE #11231: Kubernetes/GCE corrupted PD volume
Somehow a GCE persistent disk was corrupted when used exclusively by a single pod on a container engine. While testing, i repeatedly deleted / created the replication controller and pod (a singleton) with 4 containers all using a single PD in read-write mode.
Eventually the pod just refused to start, and the instance reported filesystem corruption in the logs.
This looks like failure to sync/unmount the volume properly
Here's /var/log/messages from the instance (there's nothing else going on in this tiny 2-node cluster so it was being assigned to the same one repeatedly) - http://pastebin.com/rH6jfHFH

### LINKED ISSUE #11321: Explicit errors while detaching GCE PD prevent PD from ever being detached
If `GetCloudProvider` or `DetachDisk` calls fail while detaching a GCE PD, because the previous `Unmount` call succeeded, there are no further attempts by kubelet to detach the PD, and the PD remains attached to the node indefinitely.

Code in question [pkg/volume/gce_pd/gce_util.go#L114](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L114):
```
	// Detach the disk
	gce, err := cloudprovider.GetCloudProvider("gce", nil)
	if err != nil {
		return err
	}
	if err := gce.(*gce_cloud.GCECloud).DetachDisk(pd.pdName); err != nil {
		return err
	}
```

`verifyDetached(pd, gce)` is called to ensure retries on silent failures of the detach call (which are much more common); explicit failures should also be handled similarly.

Discovered while trying to repro #11231. 

Relevant logs:
```
W0715 07:17:51.574898    3062 kubelet.go:1343] Orphaned volume "7c60d5e7-2ac1-11e5-b69c-42010af04fdb/testpd" found, tearing down volume
I0715 07:17:51.575607    3062 mount_linux.go:129] Unmounting /var/lib/kubelet/pods/7c60d5e7-2ac1-11e5-b69c-42010af04fdb/volumes/kubernetes.io~gce-pd/testpd
I0715 07:17:51.579307    3062 gce_util.go:109] DetachDisk(pd) where pd is &gce_pd.gcePersistentDisk{volName:"testpd", podUID:"7c60d5e7-2ac1-11e5-b69c-42010af04fdb", pdName:"e2e-7096e666-2ac1-11e5-907d-f0921cde18c1", fsType:"", partition:"", readOnly:false, manager:(*gce_pd.GCEDiskUtil)(0x1c15f78), mounter:(*mount.Mounter)(0x1c15f78), diskMounter:(*gce_pd.gceSafeFormatAndMount)(0xc2096a71a0), plugin:(*gce_pd.gcePersistentDiskPlugin)(0xc20833aa60), legacyMode:false} and the globalPDPath is "/var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/e2e-7096e666-2ac1-11e5-907d-f0921cde18c1"
E0715 07:17:51.583962    3062 kubelet.go:1349] Could not tear down volume "7c60d5e7-2ac1-11e5-b69c-42010af04fdb/testpd": Get http://169.254.169.254/computeMetadata/v1/instance/zone: EOF
```

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #11231
Fixes #11321
- Make GCE PD attach block on pending detach (addresses https://github.com/GoogleCloudPlatform/kubernetes/issues/11231#issuecomment-122049113), instead of terminating the previous detach operation.
- Skip GCE PD attach operation, if one is already pending for the same PD, instead of terminating the previous detach operation.
- Retry if there are any errors on GCE detach/attach or provider object fetching (addresses #11321).
- Added new E2E test to repro #11231, which passes with this this PR, and fails without it.

CC @thockin 

Running PD tests repeatedly overnight to test stability.

### CODE REVIEW

**Comment by wojtek-t** [comment]
Ref #11561

**Comment by wojtek-t** [comment]
To be clear - I'm (hopefully temporarily) moving the "Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both" test to flaky.
Basically, I ran it 50 times locally and it didn't fail for me even once, wherease it is failing on Jenkins in almost all runs. We can easily move it back after merging this PR if it fixes it.

File: pkg/util/operationmanager/operationmanager.go [hunk 1]
```diff
@@ -37,6 +37,9 @@ type OperationManager interface {
 	// Attempts to send msg to the channel associated with ID.
 	// Returns an error if no associated channel exists.
 	Send(id string, msg interface{}) error
+
+	// Returns true or if an entry with the specified ID already exists.
```
Comment (wojtek-t) [inline pkg/util/operationmanager/operationmanager.go]: nit: s/or //

File: pkg/util/operationmanager/operationmanager.go [hunk 2]
```diff
@@ -90,3 +93,11 @@ func (cm *operationManager) Send(id string, msg interface{}) error {
 	cm.chanMap[id] <- msg
 	return nil
 }
+
+// Returns true or if an entry with the specified ID already exists.
```
Comment (wojtek-t) [inline pkg/util/operationmanager/operationmanager.go]: nit: s/or //

File: pkg/volume/gce_pd/gce_util.go [hunk 3]
```diff
@@ -108,33 +102,49 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+			}
+		}
+
+		if numRetries > 0 {
+			glog.Warningf("Timed out waiting for GCE PD %q to attach. Retrying attach.", pd.pdName)
+		}
+
+		if err := gce.(*gce_cloud.GCECloud).AttachDisk(pd.pdName, pd.readOnly); err != nil {
+			// Retry on error. See issue #11321
+			glog.Errorf("Error attaching PD %q: %v", pd.pdName, err)
```
Comment (wojtek-t) [inline pkg/volume/gce_pd/gce_util.go]: shouldn't we add "sleep X and continue" here?
IIUC, if AttachDisk returns an error, there is no chance that disk will be attached at some point.

File: pkg/volume/gce_pd/gce_util.go [hunk 4]
```diff
@@ -143,84 +153,105 @@ func verifyAttached(pd *gcePersistentDisk, sdBeforeSet util.StringSet, gce cloud
...
-		glog.Warningf("Timed out waiting for GCE PD %q to detach. Retrying detach.", pd.pdName)
+		if numRetries > 0 {
+			glog.Warningf("Timed out waiting for GCE PD %q to detach. Retrying detach.", pd.pdName)
+		}
+
 		if err := gce.(*gce_cloud.GCECloud).DetachDisk(pd.pdName); err != nil {
-			glog.Errorf("Error on retry detach PD %q: %v", pd.pdName, err)
-			return
+			// Retry on error. See issue #11321
+			glog.Errorf("Error detaching PD %q: %v", pd.pdName, err)
```
Comment (wojtek-t) [inline pkg/volume/gce_pd/gce_util.go]: shouldn't we add "sleep X and continue" here?
IIUC, if AttachDisk returns an error, there is no chance that disk will be attached at some point.

File: pkg/util/operationmanager/operationmanager.go (hunk 1 above)
Comment (saad-ali) [inline pkg/util/operationmanager/operationmanager.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 3 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Good catch. Added sleep.

Comment (wojtek-t) [inline pkg/volume/gce_pd/gce_util.go]: Shouldn't we also add "continue" after this sleep? If not - can you please add a comment why it makes sense to verify whether disk is attached after AttachDisk returning error?

(Same for detaching)

File: pkg/volume/gce_pd/gce_util.go [hunk 5]
```diff
@@ -143,84 +155,107 @@ func verifyAttached(pd *gcePersistentDisk, sdBeforeSet util.StringSet, gce cloud
...
-		if err := gce.(*gce_cloud.GCECloud).AttachDisk(pd.pdName, pd.readOnly); err != nil {
-			return "", err
-		}
 	}
 
 	return "", fmt.Errorf("Could not attach GCE PD %q. Timeout waiting for mount paths to be created.", pd.pdName)
 }
 
-// Veify the specified persistent disk device has been succesfully detached, and retries if it fails.
+// Detaches the specified persistent disk device from node, verifies that it is attached, and retries if it fails.
```
Comment (wojtek-t) [inline pkg/volume/gce_pd/gce_util.go]: s/attached/detached/

**Comment by wojtek-t** [comment]
Just few small comments.

File: pkg/volume/gce_pd/gce_util.go (hunk 5 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 3 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Actually I just remembered I did this on prupose. A previous attach/detach operation could succeed therefore it is worth checking at every iteration whether the disk is attached/detached, instead of doing nothing and sleeping, we can do verification--so I remeoved the sleep as well.

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
Thanks for the feedback @wojtek-t! PTAL

**Comment by wojtek-t** [comment]
Thanks - LGTM

**Comment by wojtek-t** [comment]
@saad-ali - please rebase this PR (I wanted to merge this).
