### PR TITLE
attachdetach controller: attach volumes immediately when Pod's PVCs are bound

### LINKED ISSUE #64549: PV randomly take up to few minutes to attach
**BUG REPORT**:

/kind bug

**What happened**:
When using a `pvc` with a `deployment`, we observe a delay (that randomly vary between 15 sec and up to few minutes) between the volume's creation and when it is attached to the pod.

**What you expected to happen**:
The volume should be attached reasonably quickly after it's created, and within a predictible delay.

**How to reproduce it (as minimally and precisely as possible)**:

The manifest we used to reproduce the issue:

```
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app-instance-id: app-test-xxxxx
  name: app-test-xxxxx-redis
spec:
  progressDeadlineSeconds: 150
  replicas: 1
  selector:
    matchLabels:
      app: app-test-xxxxx-redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-test-xxxxx-redis
        app-instance-id: app-test-xxxxx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values: ["node01"]
      automountServiceAccountToken: false
      containers:
      - image: redis:4-alpine
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 120
        name: main
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: "/data"
          name: app-test-xxxxx-redis-pvc
          readOnly: false
      imagePullSecrets:
      - name: gitlab-registry
      volumes:
      - name: app-test-xxxxx-redis-pvc
        persistentVolumeClaim:
          claimName: app-test-xxxxx-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app-instance-id: app-test-xxxxx
  name: app-test-xxxxx-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-18T23:58:35Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
``` 

- Cloud provider or hardware configuration:

```Bare metal```

- OS (e.g. from /etc/os-release):

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):

```
Linux node01 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz GenuineIntel GNU/Linux
```

- Install tools:

```bootkube base setup```

- Others:

    * We're using a NetApp SAN with [`trident`](https://github.com/NetApp/trident) as PVC controller.
    * During our tests, it seem that the delay between the creation of the `pv` and when it's actually mounted to the pod can vary from `20s` to `>4min`
    * When deleting and re-creating the `deployment` (without deleting the `pvc`), we don't observe this issue, even when forcing a different node selector.

- Timeline:

  1. the pv is seen by the kubelet
  2. kubelet reports its new status to the apiserver (with the given volume in the `requestObject.volumesInUse` field)
  3. the `kube-controller-manager`'s log report that the `node_status_updater` is  updating the list of `VolumesAttached`.
  4. the `kubelet`'s logs show that the volume is successfully attached to the pod

```
[kubelet.log]                     May 30 16:28:47 node01 kubelet-wrapper[24033]: I0530 16:28:47.102390   24033 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "dev-app-test-xxxxx-redis-86590" (UniqueName: "kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42") pod "app-test-xxxxx-redis-695b4b774d-2979s" (UID: "8656d955-6426-11e8-90fc-005056bcaf95")
[kube-apiserver.log]          2018-05-30T16:28:56.925236777Z {"kind":"Event","apiVersion":"audit.k8s.io/v1beta1","metadata":{"creationTimestamp":"2018-05-30T16:28:56Z"},"level":"RequestResponse","timestamp":"2018-05-30T16:28:56Z","auditID":"eaa186d0-8821-444c-abcc-dfbf503485ec","stage":"ResponseComplete","requestURI":"/api/v1/nodes/node01/status","verb":"patch","user":{"username":"kubelet","groups":["system:masters","system:authenticated"]},"sourceIPs":["10.1.44.136"],"objectRef":{"resource":"nodes","name":"node01","apiVersion":"v1","subresource":"status"},"responseStatus":{"metadata":{},"code":200},"requestObject":{"status":{"$setElementOrder/conditions":[{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2018-05-30T16:28:56Z","type":"OutOfDisk"},{"lastHeartbeatTime":"2018-05-30T16:28:56Z","type":"MemoryPressure"},{"lastHeartbeatTime":"2018-05-30T16:28:56Z","type":"DiskPressure"},{"lastHeartbeatTime":"2018-05-30T16:28:56Z","type":"Ready"}],"images":[{"names":["registry.ci.i.my-corp.io/apps/eigenv2@sha256:dd559a41e61a56cb026ef00260461441e05c2515f99a1e0b2024142fd3d15099","registry.ci.i.my-corp.io/apps/eigenv2:2.0.7_auto_credentials_2"],"sizeBytes":3241810363},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4eedca31e3813aaa070105b166f8039f67a12feb3243e4383972f0ed3a2e0f2b","registry.ci.i.my-corp.io/apps/sigpage:4b9afd4a6015e21d7cc3ecfdaa9ddcf8692cd587"],"sizeBytes":2749328609},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9e429a2254ab3c6aae883239c22d7cd83efc8d75983f0e65239b6cd01156da90","registry.ci.i.my-corp.io/apps/sigpage:f1a089117eb7cb9f574cad5b0bfc2aef86effdd9"],"sizeBytes":2749326441},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2edd1b74d7f166b58f06bc00252e6a5f703ed9129d90f825171b012c03325831","registry.ci.i.my-corp.io/apps/sigpage:c4fc903af078837a47f003fadf38d48b37f5b605","registry.ci.i.my-corp.io/apps/sigpage:e21cf8bc0af680cd4f4f323775000ecb3ee1facd"],"sizeBytes":2749326441},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:012d8c0a74f949301f698ab9c5cc99cec8ea2fd72b8dc151a2e7dbef426c164e","registry.ci.i.my-corp.io/apps/sigpage:a68e0acf28fa4c1a5980a712b5c197e643717106"],"sizeBytes":2749325758},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6fb3d1ebcf0cadb53100f90351188292852c37f10e2869a81231bb9f6ef62d0c","registry.ci.i.my-corp.io/apps/sigpage:83abf05709cf57d32f3bdbebfec7bbde1035b028"],"sizeBytes":2749325758},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:25494a871f8f3c32c720356901cd6c4503506be5d9224a9b786e60400c2b2446","registry.ci.i.my-corp.io/apps/sigpage:8847bb9090203e6d6e7b40edff3dcadc83aa3fe4","registry.ci.i.my-corp.io/apps/sigpage:d19ff5783406b80dea1dbe3c2f57f0f376def884"],"sizeBytes":2749325619},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:dd06ab19f5213c15cb0a2f4b10808b6aea9d44a5093befd54d9bcc6f81561a26","registry.ci.i.my-corp.io/apps/sigpage:122791bef01c9dd74383f76d6a6a2b973d9fd49c"],"sizeBytes":2749324655},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:143d836b411a86522b6fecd23dda00f8331735759d06a7870e45cbb703405814","registry.ci.i.my-corp.io/apps/sigpage:0bdcdff1afb27f912c05b1fd633a006a65f246f7"],"sizeBytes":2749324286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6b951dd0479018a69c18f3b86b59639dd78f4f6b0cb8661ac6adb610933d4c48","registry.ci.i.my-corp.io/apps/sigpage:d493a029db35cb574789da1405994663b5ae40cc"],"sizeBytes":2749324241},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:14ab225b3649fb844bc0443152410acf79b15a0943616590f7376af4eff85cd8","registry.ci.i.my-corp.io/apps/sigpage:29f7cdb95fabb76c15d1c635d5eadfc3d1060516"],"sizeBytes":2749324208},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:1381c34498d792276658f3f79cba8471444b4da2e01fc6cb007f437df5a12032","registry.ci.i.my-corp.io/apps/sigpage:ab16ebef60c5d7d04d822728c783466f17192931"],"sizeBytes":2749324201},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:befbc6c06cd1fd2be764f886e624df581fba51595fa8b2c8de44e0228ae5c9a5","registry.ci.i.my-corp.io/apps/sigpage:9418250cc5ae3b8e83b51d6acbae0a006759ffb7"],"sizeBytes":2749323635},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ed9da553096d02719919ca9c373cd0744be44a343991c4c7251242b8aace0398","registry.ci.i.my-corp.io/apps/sigpage:12cbd6430fb30c9f8b6cb1d0b5ad5021cbffa7c9"],"sizeBytes":2749321616},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:5b668aa7af54f1930ba7b067e1076312941c5a716724ce02a9ba591efdc2a95f","registry.ci.i.my-corp.io/apps/sigpage:3d70b1fbaa1cce205a1051a0c01d829b4d2fb07f"],"sizeBytes":2749314538},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:15d2d60157efb69353f237abda9ceb5ddefc41955088286cfa39b5e91f4586d9","registry.ci.i.my-corp.io/apps/sigpage:f41f434231099799f771501a2382c62657eb9ef2"],"sizeBytes":2749313855},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4e7e5d3fe9f2b9097221c2637ee45385e159805e1f1c54336c15e957460fb454","registry.ci.i.my-corp.io/apps/sigpage:d61f64b4cc2cdb460d7d04ebc757dacf2bec5507"],"sizeBytes":2749312827},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:c9fbf31444c17e46738616ab4b37f9c5712de0e54bbf0931e763fdc726eedacf","registry.ci.i.my-corp.io/apps/sigpage:dc74646d353581f30928e64f324c25414d2cbade"],"sizeBytes":2749312799},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6d95b09fe04178c745d00bfe0840c7880e99dad7bc9d01175446e989a976285a","registry.ci.i.my-corp.io/apps/sigpage:e4aa1fe7c14466804900a77f16b5fd537ab26152"],"sizeBytes":2566387819},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:0f3f6cc9a8dc5db9c7d7851813da59335b7d4cb68ed44c609666d175d56c8981","registry.ci.i.my-corp.io/apps/sigpage:91bead83d30bd0fcf9a02c1af4fad779f39b8182"],"sizeBytes":2566387754},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:5cf8c66c1ef595d8d81dc7f0daf1b35f6aa325fa0f76aea4dee3d8eebfc7900e","registry.ci.i.my-corp.io/apps/sigpage:212ac6a67fb8019b84c901a8402978d6480070c7"],"sizeBytes":2566370389},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3acfe82f50f20955bc03f149ba8b539c5f3818afb934357e48b2022f62d3214d","registry.ci.i.my-corp.io/apps/sigpage:a3f9dd813b36e643beb6f2d81f0191f3f5f5b68f"],"sizeBytes":2566369424},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:91e3538d3179a221348aaf63109dcd806eaa5b8afba755a1b28783367eb57e5e","registry.ci.i.my-corp.io/apps/sigpage:702057e655eb24ef3957bed7ffc4c508abc4f686"],"sizeBytes":2566369365},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a6adbdb25844cd9c0a90c5b811fd94099a3804ecdc966b1bca1e40c667efd251","registry.ci.i.my-corp.io/apps/sigpage:30cc6b261be324024a7dc07838ddc5ede663ff4f"],"sizeBytes":2566369203},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:956e0713745314fae79c797bd7ee6194b67cdc85eca31b0e1e4389222fd4895b","registry.ci.i.my-corp.io/apps/sigpage:3f74f06c624cd2b20403bb2abe0e72774df6dd11"],"sizeBytes":2566369189},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9c093f95d59da87c20693c41f826f7335a056cb2a9f583ede338531179acaa39","registry.ci.i.my-corp.io/apps/sigpage:59904dec784790d8be3ae7caeb900c2fbfd4cbf6"],"sizeBytes":2566369130},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2e5abe153ffc0afafe33dc7b8c69ca3e4e0d70b23b8521b4a18233cfca4a7c2a","registry.ci.i.my-corp.io/apps/sigpage:09412161cdc567fa9c2e0db34273a0d14d2e325d"],"sizeBytes":2566369114},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d3514305af5359a5bc9a4a53b02d9b1c99e687a366250c749ecdd4076f73c43b","registry.ci.i.my-corp.io/apps/sigpage:d9fc886c839c97fc37f0747cc9a4336b05cba187"],"sizeBytes":2566368976},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2873974db1805ec2a6a310ed7abf58f13b79e4a2d18fefdb3f4d0ddf70bea8d6","registry.ci.i.my-corp.io/apps/sigpage:7b4cb4400cb95505460594ac685f3ef7d9dbfdd5"],"sizeBytes":2566368941},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3479e521375e236a62682da46bf56745ce6dbe5b73450aa1e09c7b1ea91794a6","registry.ci.i.my-corp.io/apps/sigpage:9f5045f0d2348a16c271a4dbe115306d5ccd8fe9"],"sizeBytes":2563360491},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:132419d6f7bc19cb162c4b7eb5d8c374035dc9dc8e40496af8d048634420acad","registry.ci.i.my-corp.io/apps/sigpage:91187d93a951ee91f89673d70872c489aa45f513"],"sizeBytes":2562463101},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ce7b678ace071328d101e0acf1c5906d5602dcc83ba4ef02f8f3025d2783459e","registry.ci.i.my-corp.io/apps/sigpage:c2dd69b1cfa909f3d651c2702052ddd18d243722"],"sizeBytes":2562461303},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4e4e551f47bd927b5128d9becf2db677a40cdeb22baa6238f8fbf26c08d09303","registry.ci.i.my-corp.io/apps/sigpage:41c7908d79cb3fbce6dce50aa240711e6b6a4819"],"sizeBytes":2560202625},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:0a4c11511b33cd19e7afd2834d1edf754c09782c88a93a2c7213acf9d03ae769","registry.ci.i.my-corp.io/apps/sigpage:328ed5184a0a8807f4e86dba555063eff32d1128"],"sizeBytes":2560187286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a83cafbd37d26e9c13ef79696811f266aa2cc0f749a09f911f6784c30292029a","registry.ci.i.my-corp.io/apps/sigpage:a0d20c2ea291b6ca2eef5540434363ef160764cd"],"sizeBytes":2560187286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:c9927df74e390d097fa2cffdc408cf6b4dc3a3823549b7ddef76973aa45def5a","registry.ci.i.my-corp.io/apps/sigpage:ac5f46e1cd6427ce450b0deb232f2d04f42cae35"],"sizeBytes":2560187234},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:76b5c57550ca047086b75e547733cc3180d97d97a714f602856caed87871556e","registry.ci.i.my-corp.io/apps/sigpage:f4f96c176b00e9e476bd333ee76290d2a12c0d3a"],"sizeBytes":2560187184},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:f605687b1eb1502d09096d550577b92753df337b5999adf42a7de5fd38355337","registry.ci.i.my-corp.io/apps/sigpage:7836958481886b622e5f9215f01d74821802998d"],"sizeBytes":2560187075},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:07112f224983e9c15058ff48d744b6ab57450d7d30278fe6228d46ee27d65b59","registry.ci.i.my-corp.io/apps/sigpage:3d47eb3e1a543c243ab608ea470a6509e82871e4"],"sizeBytes":2560170925},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3fa5af040ca41594b46ef633b79b0935affef95753b51682d9cea115928253f7","registry.ci.i.my-corp.io/apps/sigpage:ae3220fb26809b91c60ad71fb538693269efe76f"],"sizeBytes":2560170896},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a32fd1b5e4403ac82db278bdc0c9a2b5ac5e1b4f43ae015e7be3887c829ffa57","registry.ci.i.my-corp.io/apps/sigpage:6599af824b8e4a91ab3235794b91a8f3f2c05a3b"],"sizeBytes":2560170173},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d8cf79ba4adbe8b5500d7c747edf645c49386af15d98ddc9767fe81f8e075b05","registry.ci.i.my-corp.io/apps/sigpage:c7fe8daebe99a686052e770c2b1983ef5d91563b"],"sizeBytes":2559953082},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ae141e43ef42ca3a5909aba7a28d417ee4945efcd2ee871e44743c27cd0308f5","registry.ci.i.my-corp.io/apps/sigpage:40f4a77bdddde9e7f70799f2d8d18f939c063383"],"sizeBytes":2559952976},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:262471b6f35c539d1f7c83c1e302c0770bf5cc3ffab13d5220f08dcf36a7fe97","registry.ci.i.my-corp.io/apps/sigpage:2496ced9e5f113c4a9b496e493535e5e27694a82","registry.ci.i.my-corp.io/apps/sigpage:36747fb58c6b17a3a72693fb828a0d0ef8eacfd3"],"sizeBytes":2559931411},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a558e2afa14ae04678356967c1e8aac03c5f39c67f46d8614af03df401673e13","registry.ci.i.my-corp.io/apps/sigpage:75b9086f8646b959556688b5bc255fe4253315bc"],"sizeBytes":2559931411},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d0b32a9eb5ed418d977e675315bda991f066af9249f1918cce77287042fba2c4","registry.ci.i.my-corp.io/apps/sigpage:725bc46398a74ef2d0f61104d229ce198c0b3a15"],"sizeBytes":2557795642},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6a3cc1d552282c67178dce5b50143b8b6c13f15f759f671da1004bba085260f3","registry.ci.i.my-corp.io/apps/sigpage:f4449175f48360eb0907a7a5fedc6233695eff66"],"sizeBytes":2557795642},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9075a983fd20d84d34008aedb2a193eb2570183c7d10c508f150c834614f0b42","registry.ci.i.my-corp.io/apps/sigpage:2bfd6e9f4ebecfced1bc0a0c2548449168c1224e","registry.ci.i.my-corp.io/apps/sigpage:98e7c6d2cd1f76e1204d2e929aa8cfac6fc66261","registry.ci.i.my-corp.io/apps/sigpage:cb825e4a3a988ab2dd0e3d51f3d8be9f94f719bb","registry.ci.i.my-corp.io/apps/sigpage:e172f7fc1772ac73f93610a5ad7d15cb4720082c"],"sizeBytes":2557795187},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3f29acc089443b362c3a1611ab643b313d2a16b36b4a4a18182a3381bf55adb4","registry.ci.i.my-corp.io/apps/sigpage:6b808422c457a715655fd437ac7fdc85d798a9c1"],"sizeBytes":2557793624},{"names":["registry.ci.i.my-corp.io/apps/ocr@sha256:d731ff3fa4892f5fbbd352a3db8629bcb58af15d3f318b33a6db14711c2597f0","registry.ci.i.my-corp.io/apps/ocr:23997cb316dcfc349b5d08cb0997446167bfd90f"],"sizeBytes":2241128085}],"volumesInUse":["kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:34","kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42","kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:5","kubernetes.io/iscsi/ci-main-gitlab-redis-storage-f22f5:ci-main-gitlab-redis-storage-f22f5:0","kubernetes.io/iscsi/prod-apps-ocr-prod-postgresql-baa0a:prod-apps-ocr-prod-postgresql-baa0a:0"]}},"responseObject":{"kind":"Node","apiVersion":"v1","metadata":{"name":"node01","selfLink":"/api/v1/nodes/node01/status","uid":"ff927685-4a46-11e8-8096-005056bced2e","resourceVersion":"36561049","creationTimestamp":"2018-04-27T18:15:43Z","labels":{"beta.kubernetes.io/arch":"amd64","beta.kubernetes.io/os":"linux","kubernetes.io/hostname":"node01","node-role.kubernetes.io/ingress":"","node-role.kubernetes.io/worker":""},"annotations":{"node.alpha.kubernetes.io/ttl":"0","projectcalico.org/IPv4Address":"10.1.44.136/32","volumes.kubernetes.io/controller-managed-attach-detach":"true"}},"spec":{"podCIDR":"172.20.3.0/24","externalID":"node01"},"status":{"capacity":{"cpu":"12","ephemeral-storage":"149968156Ki","memory":"32942144Ki","pods":"110"},"allocatable":{"cpu":"12","ephemeral-storage":"138210652341","memory":"32839744Ki","pods":"110"},"conditions":[{"type":"OutOfDisk","status":"False","lastHeartbeatTime":"2018-05-30T16:28:56Z","lastTransitionTime":"2018-04-27T18:15:43Z","reason":"KubeletHasSufficientDisk","message":"kubelet has sufficient disk space available"},{"type":"MemoryPressure","status":"False","lastHeartbeatTime":"2018-05-30T16:28:56Z","lastTransitionTime":"2018-05-06T17:32:50Z","reason":"KubeletHasSufficientMemory","message":"kubelet has sufficient memory available"},{"type":"DiskPressure","status":"False","lastHeartbeatTime":"2018-05-30T16:28:56Z","lastTransitionTime":"2018-05-06T17:32:50Z","reason":"KubeletHasNoDiskPressure","message":"kubelet has no disk pressure"},{"type":"Ready","status":"True","lastHeartbeatTime":"2018-05-30T16:28:56Z","lastTransitionTime":"2018-05-30T10:14:41Z","reason":"KubeletReady","message":"kubelet is posting ready status"}],"addresses":[{"type":"InternalIP","address":"10.1.44.136"},{"type":"Hostname","address":"node01"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10250}},"nodeInfo":{"machineID":"40beb5eb909e171860ceee669da56e1d","systemUUID":"423C92FF-163E-A491-B205-003D6FCCF0D8","bootID":"fbe60ab3-ed6e-4bf7-a981-2d83eb61603a","kernelVersion":"4.14.32-coreos","osImage":"Container Linux by CoreOS 1688.5.3 (Rhyolite)","containerRuntimeVersion":"docker://17.12.1-ce","kubeletVersion":"v1.9.7","kubeProxyVersion":"v1.9.7","operatingSystem":"linux","architecture":"amd64"},"images":[{"names":["registry.ci.i.my-corp.io/apps/eigenv2@sha256:dd559a41e61a56cb026ef00260461441e05c2515f99a1e0b2024142fd3d15099","registry.ci.i.my-corp.io/apps/eigenv2:2.0.7_auto_credentials_2"],"sizeBytes":3241810363},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4eedca31e3813aaa070105b166f8039f67a12feb3243e4383972f0ed3a2e0f2b","registry.ci.i.my-corp.io/apps/sigpage:4b9afd4a6015e21d7cc3ecfdaa9ddcf8692cd587"],"sizeBytes":2749328609},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9e429a2254ab3c6aae883239c22d7cd83efc8d75983f0e65239b6cd01156da90","registry.ci.i.my-corp.io/apps/sigpage:f1a089117eb7cb9f574cad5b0bfc2aef86effdd9"],"sizeBytes":2749326441},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2edd1b74d7f166b58f06bc00252e6a5f703ed9122018-05-30T16:28:56.925340395Z 9d90f825171b012c03325831","registry.ci.i.my-corp.io/apps/sigpage:c4fc903af078837a47f003fadf38d48b37f5b605","registry.ci.i.my-corp.io/apps/sigpage:e21cf8bc0af680cd4f4f323775000ecb3ee1facd"],"sizeBytes":2749326441},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:012d8c0a74f949301f698ab9c5cc99cec8ea2fd72b8dc151a2e7dbef426c164e","registry.ci.i.my-corp.io/apps/sigpage:a68e0acf28fa4c1a5980a712b5c197e643717106"],"sizeBytes":2749325758},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6fb3d1ebcf0cadb53100f90351188292852c37f10e2869a81231bb9f6ef62d0c","registry.ci.i.my-corp.io/apps/sigpage:83abf05709cf57d32f3bdbebfec7bbde1035b028"],"sizeBytes":2749325758},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:25494a871f8f3c32c720356901cd6c4503506be5d9224a9b786e60400c2b2446","registry.ci.i.my-corp.io/apps/sigpage:8847bb9090203e6d6e7b40edff3dcadc83aa3fe4","registry.ci.i.my-corp.io/apps/sigpage:d19ff5783406b80dea1dbe3c2f57f0f376def884"],"sizeBytes":2749325619},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:dd06ab19f5213c15cb0a2f4b10808b6aea9d44a5093befd54d9bcc6f81561a26","registry.ci.i.my-corp.io/apps/sigpage:122791bef01c9dd74383f76d6a6a2b973d9fd49c"],"sizeBytes":2749324655},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:143d836b411a86522b6fecd23dda00f8331735759d06a7870e45cbb703405814","registry.ci.i.my-corp.io/apps/sigpage:0bdcdff1afb27f912c05b1fd633a006a65f246f7"],"sizeBytes":2749324286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6b951dd0479018a69c18f3b86b59639dd78f4f6b0cb8661ac6adb610933d4c48","registry.ci.i.my-corp.io/apps/sigpage:d493a029db35cb574789da1405994663b5ae40cc"],"sizeBytes":2749324241},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:14ab225b3649fb844bc0443152410acf79b15a0943616590f7376af4eff85cd8","registry.ci.i.my-corp.io/apps/sigpage:29f7cdb95fabb76c15d1c635d5eadfc3d1060516"],"sizeBytes":2749324208},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:1381c34498d792276658f3f79cba8471444b4da2e01fc6cb007f437df5a12032","registry.ci.i.my-corp.io/apps/sigpage:ab16ebef60c5d7d04d822728c783466f17192931"],"sizeBytes":2749324201},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:befbc6c06cd1fd2be764f886e624df581fba51595fa8b2c8de44e0228ae5c9a5","registry.ci.i.my-corp.io/apps/sigpage:9418250cc5ae3b8e83b51d6acbae0a006759ffb7"],"sizeBytes":2749323635},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ed9da553096d02719919ca9c373cd0744be44a343991c4c7251242b8aace0398","registry.ci.i.my-corp.io/apps/sigpage:12cbd6430fb30c9f8b6cb1d0b5ad5021cbffa7c9"],"sizeBytes":2749321616},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:5b668aa7af54f1930ba7b067e1076312941c5a716724ce02a9ba591efdc2a95f","registry.ci.i.my-corp.io/apps/sigpage:3d70b1fbaa1cce205a1051a0c01d829b4d2fb07f"],"sizeBytes":2749314538},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:15d2d60157efb69353f237abda9ceb5ddefc41955088286cfa39b5e91f4586d9","registry.ci.i.my-corp.io/apps/sigpage:f41f434231099799f771501a2382c62657eb9ef2"],"sizeBytes":2749313855},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4e7e5d3fe9f2b9097221c2637ee45385e159805e1f1c54336c15e957460fb454","registry.ci.i.my-corp.io/apps/sigpage:d61f64b4cc2cdb460d7d04ebc757dacf2bec5507"],"sizeBytes":2749312827},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:c9fbf31444c17e46738616ab4b37f9c5712de0e54bbf0931e763fdc726eedacf","registry.ci.i.my-corp.io/apps/sigpage:dc74646d353581f30928e64f324c25414d2cbade"],"sizeBytes":2749312799},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6d95b09fe04178c745d00bfe0840c7880e99dad7bc9d01175446e989a976285a","registry.ci.i.my-corp.io/apps/sigpage:e4aa1fe7c14466804900a77f16b5fd537ab26152"],"sizeBytes":2566387819},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:0f3f6cc9a8dc5db9c7d7851813da59335b7d4cb68ed44c609666d175d56c8981","registry.ci.i.my-corp.io/apps/sigpage:91bead83d30bd0fcf9a02c1af4fad779f39b8182"],"sizeBytes":2566387754},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:5cf8c66c1ef595d8d81dc7f0daf1b35f6aa325fa0f76aea4dee3d8eebfc7900e","registry.ci.i.my-corp.io/apps/sigpage:212ac6a67fb8019b84c901a8402978d6480070c7"],"sizeBytes":2566370389},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3acfe82f50f20955bc03f149ba8b539c5f3818afb934357e48b2022f62d3214d","registry.ci.i.my-corp.io/apps/sigpage:a3f9dd813b36e643beb6f2d81f0191f3f5f5b68f"],"sizeBytes":2566369424},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:91e3538d3179a221348aaf63109dcd806eaa5b8afba755a1b28783367eb57e5e","registry.ci.i.my-corp.io/apps/sigpage:702057e655eb24ef3957bed7ffc4c508abc4f686"],"sizeBytes":2566369365},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a6adbdb25844cd9c0a90c5b811fd94099a3804ecdc966b1bca1e40c667efd251","registry.ci.i.my-corp.io/apps/sigpage:30cc6b261be324024a7dc07838ddc5ede663ff4f"],"sizeBytes":2566369203},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:956e0713745314fae79c797bd7ee6194b67cdc85eca31b0e1e4389222fd4895b","registry.ci.i.my-corp.io/apps/sigpage:3f74f06c624cd2b20403bb2abe0e72774df6dd11"],"sizeBytes":2566369189},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9c093f95d59da87c20693c41f826f7335a056cb2a9f583ede338531179acaa39","registry.ci.i.my-corp.io/apps/sigpage:59904dec784790d8be3ae7caeb900c2fbfd4cbf6"],"sizeBytes":2566369130},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2e5abe153ffc0afafe33dc7b8c69ca3e4e0d70b23b8521b4a18233cfca4a7c2a","registry.ci.i.my-corp.io/apps/sigpage:09412161cdc567fa9c2e0db34273a0d14d2e325d"],"sizeBytes":2566369114},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d3514305af5359a5bc9a4a53b02d9b1c99e687a366250c749ecdd4076f73c43b","registry.ci.i.my-corp.io/apps/sigpage:d9fc886c839c97fc37f0747cc9a4336b05cba187"],"sizeBytes":2566368976},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:2873974db1805ec2a6a310ed7abf58f13b79e4a2d18fefdb3f4d0ddf70bea8d6","registry.ci.i.my-corp.io/apps/sigpage:7b4cb4400cb95505460594ac685f3ef7d9dbfdd5"],"sizeBytes":2566368941},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3479e521375e236a62682da46bf56745ce6dbe5b73450aa1e09c7b1ea91794a6","registry.ci.i.my-corp.io/apps/sigpage:9f5045f0d2348a16c271a4dbe115306d5ccd8fe9"],"sizeBytes":2563360491},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:132419d6f7bc19cb162c4b7eb5d8c374035dc9dc8e40496af8d048634420acad","registry.ci.i.my-corp.io/apps/sigpage:91187d93a951ee91f89673d70872c489aa45f513"],"sizeBytes":2562463101},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ce7b678ace071328d101e0acf1c5906d5602dcc83ba4ef02f8f3025d2783459e","registry.ci.i.my-corp.io/apps/sigpage:c2dd69b1cfa909f3d651c2702052ddd18d243722"],"sizeBytes":2562461303},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:4e4e551f47bd927b5128d9becf2db677a40cdeb22baa6238f8fbf26c08d09303","registry.ci.i.my-corp.io/apps/sigpage:41c7908d79cb3fbce6dce50aa240711e6b6a4819"],"sizeBytes":2560202625},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:0a4c11511b33cd19e7afd2834d1edf754c09782c88a93a2c7213acf9d03ae769","registry.ci.i.my-corp.io/apps/sigpage:328ed5184a0a8807f4e86dba555063eff32d1128"],"sizeBytes":2560187286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a83cafbd37d26e9c13ef79696811f266aa2cc0f749a09f911f6784c30292029a","registry.ci.i.my-corp.io/apps/sigpage:a0d20c2ea291b6ca2eef5540434363ef160764cd"],"sizeBytes":2560187286},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:c9927df74e390d097fa2cffdc408cf6b4dc3a3823549b7ddef76973aa45def5a","registry.ci.i.my-corp.io/apps/sigpage:ac5f46e1cd6427ce450b0deb232f2d04f42cae35"],"sizeBytes":2560187234},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:76b5c57550ca047086b75e547733cc3180d97d97a714f602856caed87871556e","registry.ci.i.my-corp.io/apps/sigpage:f4f96c176b00e9e476bd333ee76290d2a12c0d3a"],"sizeBytes":2560187184},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:f605687b1eb1502d09096d550577b92753df337b5999adf42a7de5fd38355337","registry.ci.i.my-corp.io/apps/sigpage:7836958481886b622e5f9215f01d74821802998d"],"sizeBytes":2560187075},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:07112f224983e9c15058ff48d744b6ab57450d7d30278fe6228d46ee27d65b59","registry.ci.i.my-corp.io/apps/sigpage:3d47eb3e1a543c243ab608ea470a6509e82871e4"],"sizeBytes":2560170925},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3fa5af040ca41594b46ef633b79b0935affef95753b51682d9cea115928253f7","registry.ci.i.my-corp.io/apps/sigpage:ae3220fb26809b91c60ad71fb538693269efe76f"],"sizeBytes":2560170896},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a32fd1b5e4403ac82db278bdc0c9a2b5ac5e1b4f43ae015e7be3887c829ffa57","registry.ci.i.my-corp.io/apps/sigpage:6599af824b8e4a91ab3235794b91a8f3f2c05a3b"],"sizeBytes":2560170173},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d8cf79ba4adbe8b5500d7c747edf645c49386af15d98ddc9767fe81f8e075b05","registry.ci.i.my-corp.io/apps/sigpage:c7fe8daebe99a686052e770c2b1983ef5d91563b"],"sizeBytes":2559953082},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:ae141e43ef42ca3a5909aba7a28d417ee4945efcd2ee871e44743c27cd0308f5","registry.ci.i.my-corp.io/apps/sigpage:40f4a77bdddde9e7f70799f2d8d18f939c063383"],"sizeBytes":2559952976},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:262471b6f35c539d1f7c83c1e302c0770bf5cc3ffab13d5220f08dcf36a7fe97","registry.ci.i.my-corp.io/apps/sigpage:2496ced9e5f113c4a9b496e493535e5e27694a82","registry.ci.i.my-corp.io/apps/sigpage:36747fb58c6b17a3a72693fb828a0d0ef8eacfd3"],"sizeBytes":2559931411},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:a558e2afa14ae04678356967c1e8aac03c5f39c67f46d8614af03df401673e13","registry.ci.i.my-corp.io/apps/sigpage:75b9086f8646b959556688b5bc255fe4253315bc"],"sizeBytes":2559931411},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:d0b32a9eb5ed418d977e675315bda991f066af9249f1918cce77287042fba2c4","registry.ci.i.my-corp.io/apps/sigpage:725bc46398a74ef2d0f61104d229ce198c0b3a15"],"sizeBytes":2557795642},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:6a3cc1d552282c67178dce5b50143b8b6c13f15f759f671da1004bba085260f3","registry.ci.i.my-corp.io/apps/sigpage:f4449175f48360eb0907a7a5fedc6233695eff66"],"sizeBytes":2557795642},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:9075a983fd20d84d34008aedb2a193eb2570183c7d10c508f150c834614f0b42","registry.ci.i.my-corp.io/apps/sigpage:2bfd6e9f4ebecfced1bc0a0c2548449168c1224e","registry.ci.i.my-corp.io/apps/sigpage:98e7c6d2cd1f76e1204d2e929aa8cfac6fc66261","registry.ci.i.my-corp.io/apps/sigpage:cb825e4a3a988ab2dd0e3d51f3d8be9f94f719bb","registry.ci.i.my-corp.io/apps/sigpage:e172f7fc1772ac73f93610a5ad7d15cb4720082c"],"sizeBytes":2557795187},{"names":["registry.ci.i.my-corp.io/apps/sigpage@sha256:3f29acc089443b362c3a1611ab643b313d2a16b36b4a4a18182a3381bf55adb4","registry.ci.i.my-corp.io/apps/sigpage:6b808422c457a715655fd437ac7fdc85d798a9c1"],"sizeBytes":2557793624},{"names":["registry.ci.i.my-corp.io/apps/ocr@sha256:d731ff3fa4892f5fbbd352a3db8629bcb58af15d3f318b33a6db14711c2597f0","registry.ci.i.my-corp.io/apps/ocr:23997cb316dcfc349b5d08cb0997446167bfd90f"],"sizeBytes":2241128085}],"volumesInUse":["kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:34","kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42","kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:5","kubernetes.io/iscsi/ci-main-gitlab-redis-storage-f22f5:ci-main-gitlab-redis-storage-f22f5:0","kubernetes.io/iscsi/prod-apps-ocr-prod-postgresql-baa0a:prod-apps-ocr-prod-postgresql-baa0a:0"],"volumesAttached":[{"name":"kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:5","devicePath":""},{"name":"kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:34","devicePath":""}]}},"requestReceivedTimestamp":"2018-05-30T16:28:56.920247Z","stageTimestamp":"2018-05-30T16:28:56.924554Z"}
[kube-controller-manager.log] 2018-05-30T16:31:31.091379812Z I0530 16:31:31.091200       1 node_status_updater.go:139] Updating status for node "node01" succeeded. patchBytes: "{\"status\":{\"volumesAttached\":[{\"devicePath\":\"\",\"name\":\"kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:34\"},{\"devicePath\":\"\",\"name\":\"kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:5\"},{\"devicePath\":\"\",\"name\":\"kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42\"}]}}" VolumesAttached: [{kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:34 } {kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:5 } {kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42 }]
[kubelet.log]                     May 30 16:32:56 node01 kubelet-wrapper[24033]: I0530 16:32:56.871483   24033 operation_generator.go:1121] Controller attach succeeded for volume "dev-app-test-xxxxx-redis-86590" (UniqueName: "kubernetes.io/iscsi/10.1.72.201:iqn.1992-08.com.netapp:sn.440d6a6ad6a311e79b3500a0981e9162:vs.13:42") pod "app-test-xxxxx-redis-695b4b774d-2979s" (UID: "8656d955-6426-11e8-90fc-005056bcaf95") device path: ""
```

When testing, we observe a delay that randomly varies between 20s & >4min between steps `ii.` & `iv.`.

### PR DESCRIPTION
**Pull request by cofyc**
**What this PR does / why we need it**:

Let attachdetach controller to attach volumes immediately when Pod's PVCs are bound.

Current attachdetach controller calls `util.ProcessPodVolume` to add pod volumes into `desiredStateOfWorld` on these events:

- podAdd event
- podUpdate event
- podDelete event
- periodical `desiredStateOfWorldPopulator.findAndAddActivePod`

But if a pod is created with PVCs not bound, no volumes will be added into `desiredStateOfWorld` [because PVCs not bound](https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.0/pkg/controller/volume/attachdetach/util/util.go#L99). When pv controller binds PVCs successfully, attachdetach controller will not add pod volumes immediately because it does not watch on PVC events.

It will wait until a pod update event is triggered (normally will not happen because no new status will be reported by kubelet) or `desiredStateOfWorldPopulator.findAndAddActivePod` is called (maybe 0~3 minutes later, see [timer configs](https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.0/pkg/controller/volume/attachdetach/attach_detach_controller.go)).

In bad case, pod start time will be very long (~3 minutes + ~2 minutes (kubelet max exponential backoff)), for example: https://github.com/kubernetes/kubernetes/issues/64549#issuecomment-409440546.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64549

**Special notes for your reviewer**:

**Release note**:

```release-note
attachdetach controller attaches volumes immediately when Pod's PVCs are bound
```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go [hunk 1]
```diff
@@ -168,3 +170,40 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddActivePods() {
...
+}
+
+// FindAndAddPodsByPVC finds and add active pods which reference the given
+// PVC.
+func (dswp *desiredStateOfWorldPopulator) FindAndAddActivePodsByPVC(pvc *v1.PersistentVolumeClaim) {
+	if pvc.Status.Phase != v1.ClaimBound || pvc.Spec.VolumeName == "" {
+		// Skip unbound PVCs.
+		return
+	}
+	pods, err := dswp.podLister.List(labels.Everything())
```
Comment (gnufied) [inline pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go]: Another way - perhaps we can solve this is, by implementing work queues in attach/detach controller. The problem here is - any random PVC update will cause iteration of all pods in the cluster. One can perhaps DOS the cluster by constantly updating the pvc?

Comment (cofyc) [reply pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go]: Yes, you're right. I'll update it.

Comment (cofyc) [reply pkg/controller/volume/attachdetach/populator/desired_state_of_world_populator.go]: Because PVC does not contains Pod references, but we can index pods by PVC locally, then we don't need to iterate all pods every time. For example, daemon controller [indexes pods based on their NodeName](https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.1/pkg/controller/daemon/daemon_controller.go#L197).

I think this will improve performance in large cluster.

**Comment by cofyc** [comment]
/assign @saad-ali 
Ready to review, summary of changes:

- Use queue to process PVCs on add/update events
- Index pods by PVC key then we don't need to iterate to find pods
- Add integration test for this feature

cc @jingxu97 @msau42

**Comment by redbaron** [comment]
@cofyc , do you think it is cherry-pickable to 1.10, 1.11?

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 2]
```diff
@@ -179,15 +184,53 @@ func NewAttachDetachController(
...
 	})
 
+	pvcInformer.Informer().AddEventHandler(kcache.ResourceEventHandlerFuncs{
+		AddFunc: func(obj interface{}) {
+			adc.enqueuePVC(obj)
+		},
+		UpdateFunc: func(old, new interface{}) {
+			adc.enqueuePVC(new)
+		},
+		DeleteFunc: nil,
```
Comment (gnufied) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go]: I dont think you need to specify `DeleteFunc` if you don't want to.

**Review by gnufied — COMMENTED** [review]
mostly looks good to me.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 2 above)
Comment (cofyc) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Updated.

**Comment by cofyc** [comment]
@redbaron 
Patch of `attachdetach` is easy to be cherry-picked, test part have some conflicts. 
I'll try to cherry-pick it into old releases when it's accepted.

**Comment by gnufied** [comment]
@cofyc can you please squash your commits?

**Comment by cofyc** [comment]
@gnufied 
Done. I split it into two parts:

- attachdetach controller: https://github.com/kubernetes/kubernetes/pull/66863/commits/8db47db84a09e3fa00c240383519f6a19ffa200a 
- integration tets: https://github.com/kubernetes/kubernetes/pull/66863/commits/83366218a0eb990b73c1f180bf923f270e5c4be2

File: test/integration/volume/attach_detach_test.go [hunk 3]
```diff
@@ -446,3 +523,85 @@ func TestPodAddedByDswp(t *testing.T) {
...
+	go ctrl.Run(stopCh)
+	go pvCtrl.Run(stopCh)
+
+	waitToObservePods(t, informers.Core().V1().Pods().Informer(), 2)
+	// Give attachdetach controller enough time to populate pods into DSWP.
+	time.Sleep(10 * time.Second)
+	waitForPodFuncInDSWP(t, ctrl.GetDesiredStateOfWorld(), 10*time.Second, "expected 1 pod in dsw", 1)
+	createPVForPVC(t, testClient, pvc)
+	waitForPodFuncInDSWP(t, ctrl.GetDesiredStateOfWorld(), 20*time.Second, "expected 2 pods in dsw after PVCs are bound", 2)
+	close(stopCh)
```
Comment (jingxu97) [inline test/integration/volume/attach_detach_test.go]: I wonder how well 10s and 20s setting will work? What is the typical delay under normal load, and heavy load?

Comment (cofyc) [reply test/integration/volume/attach_detach_test.go]: attachdetach controller processes Pod's PVs to attach very fast, the delay should be almost same as apiserver watch event delay, because it does nothing except adding Pod's Volumes into DSWP (no api calls) on event. 
In my local test, delay to attach PV is less than 100ms. The most delay is waiting PV controller to bound PVC, normally 4~5 seconds.
Perhaps we should increase `timeout` of `waitForPodFuncInDSWP`, and it will not increase execution time of test.
`time.Sleep(10 * time.Second)` is a hack to make sure the second pod cannot be added into DSWP at least in given seconds, because no object state or event can be checked to verify. 10 seconds should be enough here.

Comment (cofyc) [reply test/integration/volume/attach_detach_test.go]: `timeout` of `waitForPodFuncInDSWP` is increased to 60 seconds now.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 4]
```diff
@@ -179,15 +184,52 @@ func NewAttachDetachController(
...
+const (
+	pvcKeyIndex string = "pvcKey"
+)
+
+func indexByPVCKey(obj interface{}) ([]string, error) {
+	pod, ok := obj.(*v1.Pod)
+	if !ok {
+		return []string{}, nil
+	}
+	// We are only interested in active pods with nodeName set
```
Comment (msau42) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go]: Can you also add a comment that this cache is only used for attaching

**Review by msau42 — COMMENTED** [review]
This is awesome! I just have two nits

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 5]
```diff
@@ -486,6 +534,83 @@ func (adc *attachDetachController) nodeDelete(obj interface{}) {
 	adc.processVolumesInUse(nodeName, node.Status.VolumesInUse)
 }
 
+func (adc *attachDetachController) enqueuePVC(obj interface{}) {
+	key, err := kcache.DeletionHandlingMetaNamespaceKeyFunc(obj)
+	if err != nil {
+		runtime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", obj, err))
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go]: Just curious: Why `runtime.HandleError`? Why not just `glog.Errorf`?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 6]
```diff
@@ -486,6 +534,83 @@ func (adc *attachDetachController) nodeDelete(obj interface{}) {
...
+	if err != nil {
+		return err
+	}
+
+	if pvc.Status.Phase != v1.ClaimBound || pvc.Spec.VolumeName == "" {
+		// Skip unbound PVCs.
+		return nil
+	}
+
+	objs, err := adc.podIndexer.ByIndex(pvcKeyIndex, key)
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go]: Just to verify, if there are multiple pods using the same PVC, this will return all pods? If so make sure there is a test case for that.

**Review by saad-ali — COMMENTED** [review]
Largely LGTM, a couple of questions.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 5 above)
Comment (cofyc) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: I followed https://github.com/kubernetes/kubernetes/blob/v1.12.0-alpha.1/pkg/controller/daemon/daemon_controller.go#L316, and found [sample-controller](https://github.com/kubernetes/sample-controller/blob/master/controller.go#L341) uses `runtime.HandleError` to log errors too. Perhaps because `runtime.HandleError` is dedicated to log non-user facing ignored errors and can be extended by adding error handlers.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 4 above)
Comment (cofyc) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Updated.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 7]
```diff
@@ -486,6 +534,83 @@ func (adc *attachDetachController) nodeDelete(obj interface{}) {
...
+func (adc *attachDetachController) syncPVCByKey(key string) error {
+	glog.V(5).Infof("syncPVCByKey[%s]", key)
+	namespace, name, err := kcache.SplitMetaNamespaceKey(key)
+	if err != nil {
+		glog.V(4).Infof("error getting namespace & name of pvc %q to get pvc from informer: %v", key, err)
+		return nil
+	}
+	pvc, err := adc.pvcLister.PersistentVolumeClaims(namespace).Get(name)
+	if apierrors.IsNotFound(err) {
+		glog.V(2).Infof("error getting pvc %q from informer: %v", key, err)
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Fixed, increased to log level 4.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 6 above)
Comment (cofyc) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Yes, test has been updated.

**Comment by cofyc** [comment]
Squashed into two commits:

- attachdetach controller: 5fafae11d8dc33ae3120f2b686d762d4101d4ecc
- integration test: 17ab4c36ce0c012e0447f338315307d6db5b3ac8

**Comment by cofyc** [comment]
@redbaron 

I've created cherry pick PRs for 1.9/1.10/1.11:

- release-1.9: https://github.com/kubernetes/kubernetes/pull/67417
- release-1.10: https://github.com/kubernetes/kubernetes/pull/67415
- release-1.11: https://github.com/kubernetes/kubernetes/pull/67413
