### PR TITLE
Automatically wipe dependent fields on service "type" updates

### LINKED ISSUE #33766: Apply service changes fails when load balancer is removed
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): 'remove load balancer'

---

BUG REPORT

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Google Cloud (GKE)
- **OS** (e.g. from /etc/os-release):

```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.0
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
- **Kernel** (e.g. `uname -a`):

```
Linux ga-redis-cache 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 Linux
```
- **Install tools**: Google Cloud SDK
- **Others**:

**What happened**:

I have a service that I configured with an external load balancer with specific firewall rules.

```
apiVersion: v1
kind: Service
metadata:
  name: ga-redis-cache
  labels:
    service: redis
    purpose: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    service: redis
    purpose: cache
  type: LoadBalancer
  loadBalancerSourceRanges:
  # IP address changed for security; real IP address is routeable
  - 192.168.1.1/32
```

We were ready to remove the external access so I changed the configuration to remove the load balancer:

```
apiVersion: v1
kind: Service
metadata:
  name: ga-redis-cache
  labels:
    service: redis
    purpose: cache
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    service: redis
    purpose: cache
```

And ran `kubectl apply -f` and got an error about an invalid port:

```
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
The Service "ga-redis-cache" is invalid.
spec.ports[0].nodePort: Invalid value: 30179: may not be used when `type` is 'ClusterIP'
```

**What you expected to happen**:
I expected Kubernetes to remove the load balancer from the service and convert back to internal balancing for access from the cluster only.

**How to reproduce it** (as minimally and precisely as possible):
See configuration files above.

**Anything else do we need to know**:
I tried this with another service and got repeated result, just a different port:

```
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
proto: tag has too few fields: "-"
proto: no coders for struct *reflect.rtype
proto: no encoder for sec int64 [GetProperties]
proto: no encoder for nsec int32 [GetProperties]
proto: no encoder for loc *time.Location [GetProperties]
proto: no encoder for Time time.Time [GetProperties]
proto: no coders for intstr.Type
proto: no encoder for Type intstr.Type [GetProperties]
The Service "keylime-redis-cache" is invalid.
spec.ports[0].nodePort: Invalid value: 32537: may not be used when `type` is 'ClusterIP'
```

### PR DESCRIPTION
**Pull request by thockin**
Service has had a problem since forever:

* User creates a service type=LoadBalancer
* We silently allocate them a NodePort
* User changes type to ClusterIP
* We fail the operation because they did not clear NodePort

They never asked for or used the NodePort!

This change introduces auto-wiping of dependent fields.  If you squint,
you can see Service as a big, messy discriminated union, with `type` as
the discriminator.  Ignoring fields for non-selected union-modes seems
right.

This introduces the potential for an apply loop.  Specifically, we will
accept YAML that we did not previously accept.  Apply *could* see the
field in local YAML and not in the server and repeatedly try to patch it
in.  But since that YAML is currently an error, it seems like a very low
risk.  Almost nobody actually specifies their own NodePort values.

To mitigat this somewhat, we only auto-wipe on updates.  The same YAML
would fail to create.  This is a little inconsistent.  We could
auto-wipe on create, too, at the risk of more potential impact.

To do this properly, we need to know the old and new values, which means
we can not do it in defaulting or conversion.  So we do it in strategy.

/kind bug
/kind api-change
/sig network
/sig api-machinery

**Which issue(s) this PR fixes**:

Fixes #33766

```release-note
Certain fields on  Service objects will be automatically cleared when changing the service's `type` to a mode that does not need those fields.  For example, changing from type=LoadBalancer to type=ClusterIP will clear the NodePort assignments, rather than forcing the user to clear them.
```

### CODE REVIEW

File: pkg/registry/core/service/strategy.go [hunk 1]
```diff
@@ -205,6 +207,50 @@ func topologyKeysInUse(svc *api.Service) bool {
 	return len(svc.Spec.TopologyKeys) > 0
 }
 
+// This is an unusual call.  Service has a number of inter-linked fields and in
+// order to avoid breaking clients we try really hard to infer what users
+// meant.
+//
+// Services are effectively a discriminated union, where type is the
+// discriminator. Some fields just don't make sense with some types.
+func normalizeLinkedFields(newSvc *api.Service, oldSvc *api.Service) {
```
Comment (apelisse) [inline pkg/registry/core/service/strategy.go:216]: Do we want the name to be more specific? That sounds too generic and I'm concerned people would want to insert all kind of changes here. Maybe `wipeNodePortsOnNewType` or something that is very targeted to what we're doing?

File: test/e2e/network/service.go [hunk 2]
```diff
@@ -1552,7 +1552,6 @@ var _ = SIGDescribe("Services", func() {
 		ginkgo.By("changing TCP service back to type=ClusterIP")
 		_, err = tcpJig.UpdateService(func(s *v1.Service) {
 			s.Spec.Type = v1.ServiceTypeClusterIP
-			s.Spec.Ports[0].NodePort = 0
```
Comment (apelisse) [inline test/e2e/network/service.go:1555]: Any test we could add to show the new behavior?

File: pkg/registry/core/service/strategy.go (hunk 1 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:216]: Well, this is somewhat a trial baloon.  Dual-stack will have to add other fields here, too.  I could be convinced that `wipeIrrelevantFields` and `handleLinkedFields` are 2 different functions if you think that is important.  The main point is that something special is happening

File: test/e2e/network/service.go (hunk 2 above)
Comment (thockin) [reply test/e2e/network/service.go:1555]: Great point, will add verification

**Comment by thockin** [comment]
Hopefully CI will pass this time.

The looming question: Am I going to regret this?  So far nobody has convinced me I will...

File: pkg/registry/core/service/strategy.go [hunk 3]
```diff
@@ -205,6 +207,50 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+			newSvc.Spec.Ports[i].NodePort = 0
+		}
+	}
+}
+
+func needsClusterIP(svc *api.Service) bool {
+	if svc.Spec.Type == api.ServiceTypeExternalName {
+		return false
+	}
+	return true
```
Comment (apelisse) [inline pkg/registry/core/service/strategy.go:244]: I don't know how you feel about this in general:
```suggestion
	return svc.Spec.Type != api.ServiceTypeExternalName
```

File: pkg/registry/core/service/strategy.go [hunk 4]
```diff
@@ -205,6 +207,50 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+}
+
+func needsNodePort(svc *api.Service) bool {
+	if svc.Spec.Type == api.ServiceTypeNodePort || svc.Spec.Type == api.ServiceTypeLoadBalancer {
+		return true
+	}
+	return false
```
Comment (apelisse) [inline pkg/registry/core/service/strategy.go:251]:
```suggestion
	return svc.Spec.Type == api.ServiceTypeNodePort || svc.Spec.Type == api.ServiceTypeLoadBalancer
```

**Comment by apelisse** [comment]
Maybe rename PR title to "Automatically wipe dependent fields on Service type updates", otherwise it's very broad.

> Am I going to regret this? So far nobody has convinced me I will...

Almost certainly :-)

**Comment by apelisse** [comment]
LGTM for me, I'll let someone else decide if that's a good idea.

**Comment by lavalamp** [comment]
I have a bit of a queue, will look when I am able...

**Comment by thockin** [comment]
This is a small change, but requires an opinion :)

File: staging/src/k8s.io/api/core/v1/types.go [hunk 5]
```diff
@@ -4012,7 +4012,7 @@ type ServiceSpec struct {
 	// of the service will fail. This field can not be changed through updates.
```
Comment (lavalamp) [inline staging/src/k8s.io/api/core/v1/types.go:4012]: How can you wipe it if it cannot be changed through updates?

File: test/e2e/network/service.go (hunk 2 above)
Comment (lavalamp) [reply test/e2e/network/service.go:1555]: Yeah still thinking about the change, but I think a unit test would be better?

**Comment by lavalamp** [comment]
Since you said it was small, I looked... 

I think this won't generate conflicts for SSA users with a wrong manifest, which would be nice?

If that's the worst thing that can be said for it, it's probably fine.

Maybe @liggitt can think of something bad that will happen.

**Comment by thockin** [comment]
Verify fails for openapi, but running it locally doesn't update anything.  Sigh.  Every PR I write, I end up debugging something in hack

**Comment by apelisse** [comment]
Yes, verify is correct, you've updated the comment which will update the description of the type in the openapi.

**Comment by thockin** [comment]
Sure, but my local client is not seeing that - something is not being rebuilt when it needs to be.  The binary result of `make kube-apiserver` is still emitting "Ignored" rather than "Wiped".  I don't know enough about how those strings get into kube-apiserver and I don't have time to debug this build failure right now, so I just did `make clean` and it not finds that diff.

Yay.

**Comment by thockin** [comment]
```
$ git grep clusterIP.*None.*Ignored
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json:          "description": "clusterIP is the IP address of the service and is usually assigned randomly by the master. If an address is specified manually and is not in use by others, it will be allocated to the service; otherwise, creation of the service will fail. This field can not be changed through updates. Valid values are \"None\", empty string (\"\"), or a valid IP address. \"None\" can be specified for headless services when proxying is not required. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies",
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json:          "description": "clusterIP is the IP address of the service and is usually assigned randomly by the master. If an address is specified manually and is not in use by others, it will be allocated to the service; otherwise, creation of the service will fail. This field can not be changed through updates. Valid values are \"None\", empty string (\"\"), or a valid IP address. \"None\" can be specified for headless services when proxying is not required. Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if type is ExternalName. More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies",
```

How do THOSE get fixed?

**Comment by apelisse** [comment]
I would expect these to be used either for test purposes (staging/src/k8s.io/kubectl/*testdata*/openapi) and don't need updating, or are updated manually occasionally. I think you're fine.

**Comment by thockin** [comment]
Re-pushed with renamed function and more comments

File: pkg/registry/core/service/strategy.go [hunk 6]
```diff
@@ -205,6 +207,61 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+	// confusion since many of the cases we are handling here are pretty niche.
+	if oldSvc == nil {
+		return
+	}
+
+	// If the user is switching to a type that does not need a value (even
+	// "None" counts), we can wipe ClusterIP.  There are other fields that
+	// could also be wiped, but historically were ignored.  For compat, we
+	// leave it that way.
+	if needsClusterIP(oldSvc) && !needsClusterIP(newSvc) {
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:234]: also make sure newSvc did not change the clusterIP (if the incoming request explicitly monkeyed with the field, they should fail rather than get wiped and succeed)

File: pkg/registry/core/service/strategy.go [hunk 7]
```diff
@@ -205,6 +207,61 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+		newSvc.Spec.ClusterIP = ""
+	}
+
+	// If the user is switching to a type that doesn't use NodePorts, we can
+	// wipe any allocated ports.
+	if needsNodePort(oldSvc) && !needsNodePort(newSvc) {
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:240]: if possible limit clearing to fields we inherited unchanged from the old object

File: pkg/registry/core/service/strategy.go [hunk 8]
```diff
@@ -205,6 +207,61 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+		for i := range newSvc.Spec.Ports {
+			newSvc.Spec.Ports[i].NodePort = 0
+		}
+	}
+
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:245]: do we also allocate HealthCheckNodePort? how does that interact with load balancer policy. check what API validation existed around this case.

**Comment by liggitt** [comment]
this seems like a good addition for the narrowly scoped cases where we auto-allocate these fields

can move this question to Kal's PR if you want, but I'm curious if/when this is expanded to defaulted dual-stack fields (ipFamilies, ipFamilyPolicy, etc), under what circumstances would you envision clearing/re-populating those? something like "if the old and new field for {ipFamily,ipFamilyPolicy,clusterIPs} match values, and that value is not valid for the new service type"?

File: pkg/registry/core/service/strategy.go [hunk 9]
```diff
@@ -101,6 +101,7 @@ func (strategy svcStrategy) PrepareForCreate(ctx context.Context, obj runtime.Ob
 	}
 
 	dropServiceDisabledFields(service, nil)
+	dropTypeDependentFields(service, nil)
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:104]: would you envision ipFamilies/ipFamilyPolicy/clusterIPs population happening *after* this call?

File: pkg/registry/core/service/strategy.go [hunk 10]
```diff
@@ -119,6 +120,7 @@ func (strategy svcStrategy) PrepareForUpdate(ctx context.Context, obj, old runti
 	}
 
 	dropServiceDisabledFields(newService, oldService)
+	dropTypeDependentFields(newService, oldService)
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:123]: same question about ordering w.r.t. ipFamilies/ipFamilyPolicy/clusterIPs population

File: pkg/registry/core/service/strategy.go (hunk 6 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:234]: ACK, in next push

File: pkg/registry/core/service/strategy.go (hunk 7 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:240]: ACK, in next push

File: pkg/registry/core/service/strategy.go (hunk 8 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:245]: That is cleared later, but I will add it here for completeness.

File: pkg/registry/core/service/strategy.go (hunk 10 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:123]: Yes, allocation happens later

File: pkg/registry/core/service/strategy.go (hunk 9 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:104]: Yes, allocation happens later

**Comment by thockin** [comment]
> something like "if the old and new field for {ipFamily,ipFamilyPolicy,clusterIPs} match values, and that value is not valid for the new service type"?

Exactly.  IF the user made a valid change of `type` we will clear fields that don't make sense for the new type (modulo compat, so not changing fields that don't today cause errors).

New push is up, now with a test.  PTAL

**Comment by thockin** [comment]
Adding 2 more test cases, BRB

**Comment by thockin** [comment]
Added ability to add/remove ports (valid in API) as long as that doesn't increase the set of NodePorts

**Comment by thockin** [comment]
PTAL at your leisure

File: staging/src/k8s.io/api/core/v1/types.go (hunk 5 above)
Comment (liggitt) [reply staging/src/k8s.io/api/core/v1/types.go:4012]: it *can* be changed iff the old service or new service in the update request was of type ExternalName:

https://github.com/kubernetes/kubernetes/blob/2318a13228dfaadd2de4669c8ce3ffb126ed3958/pkg/apis/core/validation/validation.go#L4445-L4455

File: staging/src/k8s.io/api/core/v1/types.go [hunk 11]
```diff
@@ -4012,7 +4012,7 @@ type ServiceSpec struct {
...
 	// Valid values are "None", empty string (""), or a valid IP address. "None"
 	// can be specified for headless services when proxying is not required.
-	// Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if
+	// Only applies to types ClusterIP, NodePort, and LoadBalancer. Wiped if
 	// type is ExternalName.
```
Comment (liggitt) [inline staging/src/k8s.io/api/core/v1/types.go:4016]: should describe the exact circumstances under which it is cleared (e.g. "IP values are cleared on update from non-ExternalName service to ExternalName service if the value ClusterIP value remains unchanged")

File: staging/src/k8s.io/api/core/v1/types.go [hunk 12]
```diff
@@ -4012,7 +4012,7 @@ type ServiceSpec struct {
 	// of the service will fail. This field can not be changed through updates.
 	// Valid values are "None", empty string (""), or a valid IP address. "None"
 	// can be specified for headless services when proxying is not required.
-	// Only applies to types ClusterIP, NodePort, and LoadBalancer. Ignored if
+	// Only applies to types ClusterIP, NodePort, and LoadBalancer. Wiped if
```
Comment (liggitt) [inline staging/src/k8s.io/api/core/v1/types.go:4015]: similar doc updates needed for healthz and nodeports

File: pkg/registry/core/service/strategy.go [hunk 13]
```diff
@@ -205,6 +207,127 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+	}
+
+	// If the user is switching to a type that does not need a value (even
+	// "None" counts), AND they did not change the ClusterIP value, we can wipe
+	// it.  It will be deallocated later.
+	//
+	// There are other fields that could also be wiped, but historically were
+	// ignored.  For compat, we leave it that way.
+	if needsClusterIP(oldSvc) && !needsClusterIP(newSvc) && sameClusterIP(oldSvc, newSvc) {
+		newSvc.Spec.ClusterIP = ""
```
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/registry/core/service/strategy.go:237]: yes - "None" is a value and is currently invalid when type=ExternalName, so this is consistent.  I mentioned it in comments above :)

File: pkg/registry/core/service/strategy.go [hunk 14]
```diff
@@ -205,6 +207,127 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+	if svc.Spec.Type == api.ServiceTypeNodePort || svc.Spec.Type == api.ServiceTypeLoadBalancer {
+		return true
+	}
+	return false
+}
+
+func sameNodePorts(oldSvc, newSvc *api.Service) bool {
+	// Helper to make a unique key so we can tell if a port changed.
+	makeKey := func(p *api.ServicePort) string {
+		return fmt.Sprintf("%s/%d", p.Protocol, p.Port)
```
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/registry/core/service/strategy.go:282]: I thought about that and it seems correct.  It is effectively a new port definition.  So if you did this AND switch to ExternalName at the same time, it would fail (later in validation) for having a NodePort value.

We simply don't have an immutable key for ports, so I can't really tell the difference between "I changed an existing port number which already had a NodePort" and "I added a new port and specified a NodePort for it".  I think this is as close to correct as we can get.

There's a test-case for it "don't clear changed nodePorts" and "don't clear nodePorts when adding a port with NodePort"

File: staging/src/k8s.io/api/core/v1/types.go (hunk 11 above)
Comment (thockin) [reply staging/src/k8s.io/api/core/v1/types.go:4016]: OK, a bunch of these comments can be updated.  Will do and re-push.

File: pkg/registry/core/service/strategy.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/registry/core/service/strategy.go:282]: seems reasonable, just wanted to make sure we considered it

**Comment by liggitt** [comment]
lgtm modulo doc updates

**Comment by thockin** [comment]
I fixed up a bunch of the API doc-comments.  PTAL

File: pkg/registry/core/service/strategy.go [hunk 15]
```diff
@@ -205,6 +207,127 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+		return out
+	}
+
+	oldPorts := mapNodePorts(oldSvc)
+	newPorts := mapNodePorts(newSvc)
+
+	// Every old port must have the same NodePort in the new config or be
+	// cleared to 0 or must be removed.
+	for k, oldVal := range oldPorts {
+		if newVal, found := newPorts[k]; found {
```
Comment (khenidak) [inline pkg/registry/core/service/strategy.go:300]: What happens to partial remove, eg change type and remove one of n ports?

File: pkg/registry/core/service/strategy.go [hunk 16]
```diff
@@ -205,6 +207,127 @@ func topologyKeysInUse(svc *api.Service) bool {
...
+			if newVal != oldVal && newVal != 0 {
+				return false
+			}
+		}
+	}
+	// Every new port must not have a NodePort.
```
Comment (khenidak) [inline pkg/registry/core/service/strategy.go:306]: That does not make it same right? it confuses the user intent with (change type and add new ports)

File: pkg/registry/core/service/strategy.go (hunk 15 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:300]: If they remove a port it is fine.

If they change a port number or protocol, this treats it as if they removed the old and added the new.  If they did not clear NodePort, we will not clear it (they "added" a port with NodePort set) and will fail validation.

I thought it was important to allow adding a new port and removing an old port.  Changing an existing port is more complicated.  I could buy an argument that as long as the node port value didn't change, we could still wipe it (though that's not what is here).  Do you think that's better?  Now that I spell it out, I am coming around..

examples (assume {protocol, port, nodeport)


Good Add: New port does not have a NodePort
`{ type: NodePort, ports: [{TCP, 80, 30080}] }` -> `{ type: ClusterIP, ports: [{TCP, 80, 30080}, {TCP, 443}] }`

Bad Add: New port has a NodePort
`{ type: NodePort, ports: [{TCP, 80, 30080}] }` -> `{ type: ClusterIP, ports: [{TCP, 80, 30080}, {TCP, 443, 30443}] }`

Good Del:
`{ type: NodePort, ports: [{TCP, 80, 30080}, {TCP, 443, 30443}] }` -> `{ type: ClusterIP, ports: [{TCP, 80, 30080}] }`

Good Mod: New port does not have a NodePort
`{ type: NodePort, ports: [{TCP, 80, 30080} }` -> `{ type: ClusterIP, ports: [{TCP, 443}] }`

The open question is this one (set to demonstrate worst case):
`{ type: NodePort, ports: [{TCP, 80, 30080} }` -> `{ type: ClusterIP, ports: [{UDP, 53, 30080}] }`

Both the protocol and port number changed, but the NodePort stayed the same.  Can I wipe the node port safely?  I was thinking not, but now I am changing my thinking...

File: pkg/registry/core/service/strategy.go (hunk 16 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:306]: I'm saying that it is valid to change both things AS LONG AS the user did not specify a NodePort value.  This is closer to the create path, where we will barf if you set NodePort.  If the new state does not need a NodePort (e.g. ExternalName) and the new port does not have a NodePort, the user intent is clear.

File: pkg/registry/core/service/strategy.go (hunk 15 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go]: New push is up as a 2nd commit.  Will mark this PR for squash

Comment (khenidak) [reply pkg/registry/core/service/strategy.go]: the original line of thought (or at least that is what i thought we are trying to do):
as captured by this line https://github.com/kubernetes/kubernetes/pull/95196/files#diff-2dd9a1ef6872092e519941c8a4870f4c2a71eda096b660510b02afe9b3d19fefR243

`user should be able to change a service type to a service that does not need NodePorts without having to wipe out NodePorts while patching the Service`

**a truth table would look like this** 
O = old
N = new
O-type-need-node-ports => N-type-need-node-ports + ports changed               `OK: if node port is immutable*`
O-type-need-node-ports => N-type-need-node-ports + ports same                     `OK: validate other fields`
O-type-need-node-ports => N-DO NOT-need-node-ports + ports same               `OK: clear intent`
O-type-need-node-ports => N-DO NOT-need-node-ports + ports cleared            `OK: clear intent`
O-type-need-node-ports => N-DO NOT-need-node-ports + ports changed `NOT OK: unclear intent **`
O-type-DO NOT- need-node-ports => N-DO NOT-need-node-ports + add ports `NOT OK: ports! (validation)`
O-type-DO NOT- need-node-ports => N-DO NOT-need-node-ports + no ports    `OK`
O-type-DO NOT- need-node-ports => N-need-node-ports + no ports                    `OK`
O-type-DO NOT- need-node-ports => N-need-node-ports + some ports `OK: if ports available (alloc)***`
O-type-DO NOT- need-node-ports => N-need-node-ports + all ports `OK: if ports available (alloc)***`

* i am not even sure if we allow changing them (i am assuming yes)
** any change add/change/partial delete did the user really want to change type or made a mistake?
*** assuming we allow specific port allocation if available (similar to clusterIPs)

Comment (thockin) [reply pkg/registry/core/service/strategy.go]: I think it's safe to assume that a user who changed ports meant to do so.  E.g.

CREATE { type=LB, ports[0] = (TCP, 8080) }
PATCH { type=ClusterIP, ports[0]=(TCP, 8000) }

I think that should NOT cause an error - we need to clear the NodePort.

**Comment by khenidak** [comment]
> this seems like a good addition for the narrowly scoped cases where we auto-allocate these fields
> 
> can move this question to Khal's PR if you want, but I'm curious if/when this is expanded to defaulted dual-stack fields (ipFamilies, ipFamilyPolicy, etc), under what circumstances would you envision clearing/re-populating those? something like "if the old and new field for {ipFamily,ipFamilyPolicy,clusterIPs} match values, and that value is not valid for the new service type"?

we have a similar thing for change to `ExternalName` type services. We don't compare old to new though. Also in strategy. We only clear. we leave repopulation to user and/or defaulting.

**Comment by thockin** [comment]
pushed with a net-simpler sameNodePorts impl.

Putting a hold until Kal and I decide sequencing this with his PR

/hold

**Comment by liggitt** [comment]
/lgtm

> pushed with a net-simpler sameNodePorts impl.

doc updates and simpler sameNodePorts impl lgtm

> Putting a hold until Kal and I decide sequencing this with his PR

ack, will let you two wrangle order.

**Comment by thockin** [comment]
Rebased this one HEAD which includes dual-stack support.

File: test/e2e/network/service.go (hunk 2 above)
Comment (thockin) [reply test/e2e/network/service.go:1555]: We have unit tests and this makes e2e also verify this behavior.
