### PR TITLE
Disable matching on few selectors. Remove duplicates.

### LINKED ISSUE #71327: SelectorSpreadPriority does not spread pods across zones
**What happened**:
/kind bug
**What you expected to happen**:
* Problem 1: Predicates filter nodes. Existing pods on those nodes will be not be counted when calculating max pods per (zone or node) resulting in imbalanced cluster.
Eg: [GeneralPredicates](https://github.com/kubernetes/kubernetes/blob/e20c15174e96957c4e1faf7822125c7d295316a4/pkg/scheduler/algorithm/predicates/predicates.go#L1071) removes nodes which cannot [fit this pod](https://github.com/kubernetes/kubernetes/blob/e20c15174e96957c4e1faf7822125c7d295316a4/pkg/scheduler/algorithm/predicates/predicates.go#L728). If any of the pods are already scheduled on this node, they are not considered when counting  [max pods](https://github.com/kubernetes/kubernetes/blob/e20c15174e96957c4e1faf7822125c7d295316a4/pkg/scheduler/algorithm/priorities/selector_spreading.go#L122-L137) in `CalculateSpreadPriorityReduce`.

* Problem 2: When there are 2 selectors(service and replication controller), it is sufficient to match any one selector for distribution. This creates imbalance [[selector match code](https://github.com/kubernetes/kubernetes/blob/e20c15174e96957c4e1faf7822125c7d295316a4/pkg/scheduler/algorithm/priorities/selector_spreading.go#L101)].
Pods from previous deploys matches `service selector` and are counted when distributing pods across zones/nodes (Even though they do not match `replicaset selector`) . These pods will be deleted. After the deploy completes, the cluster is imbalanced - by zone and/or pods per node.
```
service selector: {app:sd-status-staging}
rc selector  {app: sd-status-staging,pod-template-hash: 4090075901}
```

**How to reproduce it (as minimally and precisely as possible)**:

* Problem 1:
Get pods to get scheduled on nodes with very high cpu utilization [Existing cpu utilization + 1 new pod will result in `allocatable.MilliCPU` almost equal to 0]. 
GeneralPredicate will drop this node after scheduling the first pod. 
This will lead to over utilization of an already loaded zone. 
If there are enough nodes like this one, it will create a pile on effect resulting in most pods scheduled in an already loaded zone.

* Problem 2:
Have 2 selectors and deploy 30 pods across 3 zones. Twice.
```
service selector: {app:sd-status-staging}
rc selector  {app: sd-status-staging,pod-template-hash: 4090075901}

Expected distribution by zone: 10, 10 10.
Actual distribution by zone: 10, 8, 12 (imbalanced cluster).
```

**Anything else we need to know?**:

**Environment**:
* Kubernetes version (use `kubectl version`):

```
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Happens on master too.
```
/sig scheduling

/kind bug

### PR DESCRIPTION
**Pull request by Ramyak**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
*Problem:* When there are 2 selectors(eg: service and replication controller), it is sufficient to match any one selector for distribution. This creates imbalance [[selector match code](https://github.com/kubernetes/kubernetes/blob/e20c15174e96957c4e1faf7822125c7d295316a4/pkg/scheduler/algorithm/priorities/selector_spreading.go#L101)].

Pods from previous deploys matches `service selector` and are counted when distributing pods across zones/nodes (Even though they do not match `replicaset selector`) . These pods will be deleted. After the deploy completes, the cluster is imbalanced - by zone and/or pods per node.

*Fix:* All selectors must match pods. Partial matches are still allowed.

**Which issue(s) this PR fixes**:
Fixes #71327

**Special notes for your reviewer**:
https://github.com/kubernetes/kubernetes/pull/71328 
Splitting this into 2 reviews.

**Does this PR introduce a user-facing change?**:

```release-note
Fix SelectorSpreadPriority scheduler to match all selectors when distributing pods.
```
/sig scheduling

### CODE REVIEW

File: pkg/scheduler/algorithm/priorities/selector_spreading.go [hunk 1]
```diff
@@ -84,26 +84,9 @@ func (s *SelectorSpread) CalculateSpreadPriorityMap(pod *v1.Pod, meta interface{
...
-			continue
-		}
-		for _, selector := range selectors {
-			if selector.Matches(labels.Set(nodePod.ObjectMeta.Labels)) {
-				count++
-				break
-			}
-		}
-	}
+	filteredPods := filterPods(pod.Namespace, selectors, nodeInfo)
```
Comment (bsalamat) [inline pkg/scheduler/algorithm/priorities/selector_spreading.go]: This unnecessarily allocates a slice of pods. We only need the number of matching pods here and are not interested in the pods themselves. Memory allocation/release is known to cause performance degradation and should be avoided when possible.

**Review by bsalamat — CHANGES_REQUESTED** [review]
Thanks, @Ramyak for the fix. Could you please address my comment?

File: pkg/scheduler/algorithm/priorities/selector_spreading.go (hunk 1 above)
Comment (Ramyak) [reply pkg/scheduler/algorithm/priorities/selector_spreading.go]: Thanks. Fixed.

File: pkg/scheduler/algorithm/priorities/selector_spreading.go [hunk 2]
```diff
@@ -201,19 +183,29 @@ func (s *ServiceAntiAffinity) getNodeClassificationByLabels(nodes []*v1.Node) (m
...
+					break
+				}
+			}
+			if matches {
+				pods = append(pods, pod)
+			}
 		}
 	}
-	return
+	return int(len(pods))
```
Comment (bsalamat) [inline pkg/scheduler/algorithm/priorities/selector_spreading.go]: len() returns and `int`. No need to convert.

**Review by bsalamat — COMMENTED** [review]
This PR addresses "Problem 2" of #71327, but it is a diversion from the existing behavior. Our existing code gets a union of all pods that match any of the selectors. This PR changes the union to an intersection operator. While I don't have a particular scenario in mind that would break if someone uses a standard collection, it is easy to find scenarios where pods with custom labels will no longer spread properly after this change. For that reason, I would like to think a bit more about this PR before I can approve it.

**Review by bsalamat — APPROVED** [review]
/approve 

I thought more about this change and given that the pattern mentioned in the issue can happen for many users, I decided to approve it.

**Review by bsalamat — COMMENTED** [review]
/lgtm
