### PR TITLE
Make ExponentialFailureRateLimiter slightly slower and cap the backof…

### LINKED ISSUE #27503: [k8s.io] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied. {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce/18757/

Failed: [k8s.io] LimitRange should create a LimitRange with defaults and ensure pod has those defaults applied. {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:130
Jun 15 16:30:32.516: Couldn't delete ns "e2e-tests-limitrange-kal5f": namespace e2e-tests-limitrange-kal5f was not deleted within limit: timed out waiting for the condition, pods remaining: [pod-no-resources pod-partial-resources]
```

### PR DESCRIPTION
**Pull request by gmarek**
Fix #27503

cc @deads2k @derekwaynecarr @ncdc @wojtek-t

For the context of this change see: https://github.com/kubernetes/kubernetes/issues/27503#issuecomment-244741161

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32082)

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@gmarek - please fix errors (test failures and gofmt)

**Comment by wojtek-t** [comment]
@k8s-bot gke test this, issue: #IGNORE (Jenkins issue)

**Comment by deads2k** [comment]
Power of two sounds good, but I still think that something that fails enough should end up with a multi-minute backoff.  How about 10 minutes max, with powers of two, that would be 16-ish, right?

**Comment by wojtek-t** [comment]
@deads2k - did you read this: https://github.com/kubernetes/kubernetes/issues/27503#issuecomment-244741161
If you think that 10 minutes max is something that we really need, it seems that we need namespace deletiong timeout higher than 5 minutes by default.

**Comment by deads2k** [comment]
> @deads2k - did you read this: #27503 (comment)
> If you think that 10 minutes max is something that we really need, it seems that we need namespace deletiong timeout higher than 5 minutes by default.

With powers of two, that's a *lot* of failures.  At 100 seconds max, you'll be close to the limit before you reattempt anyway, right?

**Comment by wojtek-t** [comment]
@gmarek - I talked with @deads2k offline, and we basically agreed that as a first step we would like to just change powers of 10 to powers of 2 and leave the higher max.
After some discussion we both think that it should be enough - if not, we can do some other changes.
Can you please update the PR according to that?

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
If this won't fix the problem we should probably increase the default timeout for removing namespace (which is currently 5 minutes). But this change should hopefully be enough.

File: pkg/util/workqueue/default_rate_limiters.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ type RateLimiter interface {
 // both overall and per-item rate limitting.  The overall is a token bucket and the per-item is exponential
 func DefaultControllerRateLimiter() RateLimiter {
 	return NewMaxOfRateLimiter(
-		DefaultItemBasedRateLimiter(),
+		NewItemExponentialFailureRateLimiter(5*time.Millisecond, 1000*time.Second),
```
Comment (smarterclayton) [inline pkg/util/workqueue/default_rate_limiters.go]: 1000 seconds?!

Comment (wojtek-t) [inline pkg/util/workqueue/default_rate_limiters.go]: This didn't change - it was 1000s also before this PR.

Comment (wojtek-t) [inline pkg/util/workqueue/default_rate_limiters.go]: It seems that @deads2k has strong opinion that this value should be high.

Comment (smarterclayton) [inline pkg/util/workqueue/default_rate_limiters.go]: I'm fine

Comment (deads2k) [inline pkg/util/workqueue/default_rate_limiters.go]: > It seems that @deads2k has strong opinion that this value should be high.

@smarterclayton does too, since we want to have controllers retry on external conditions that are eventually fixed, but not loop quickly on them.  An image import that fails 20 times for instance.  Maybe it comes back up.  May as well try infrequently, especially since we're talking about removing resync-ing.

Comment (gmarek) [inline pkg/util/workqueue/default_rate_limiters.go]: Yeah - I wanted to make it a 100, but there was a strong opposition:)

**Comment by gmarek** [comment]
@k8s-bot test this issue: #27462, #26822
