### PR TITLE
set config.BindAddress to IPv4 address "127.0.0.1" if not specified

### LINKED ISSUE #83791: kube-proxy node IP / bind address does not fall back to 127.0.0.1 anymore in iptables mode when node is missing from API
**What happened**:

Using Kubernetes 1.16.1, I started kube-proxy in iptables mode as a static pod on a master node. The master node was intentionally (and permanently) not available in the API as a Node object.

kube-proxy started up and terminated soon after because it failed to [fetch the Node from the API](https://github.com/kubernetes/kubernetes/blob/v1.16.1/pkg/util/node/node.go#L112-L138) (which is supposed to function as the bound address) and eventually returned an error:

```
E1011 15:25:45.275305       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:46.414712       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:48.557554       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:25:52.953709       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
E1011 15:26:01.612814       1 node.go:124] Failed to retrieve node info: nodes "master-k8s-1-16" not found
F1011 15:26:01.612866       1 server.go:443] unable to get node IP for hostname master-k8s-1-16
```

**What you expected to happen**:

I expected the same behavior as in Kubernetes 1.15 where failure to look up the Node in the API would result in [127.0.0.1 to be used as the default bind address when iptables mode is used](https://github.com/kubernetes/kubernetes/blob/v1.15.4/pkg/proxy/iptables/proxier.go#L315-L318).

**How to reproduce it (as minimally and precisely as possible)**:

Configure kube-proxy with iptables mode on Kubernetes 1.16 without the hosting Node being available in the Kubernetes API (under the OS hostname).

**Anything else we need to know?**:

PR #77167 (_Fix for kube-proxy to wait for some duration for the node to be defined_) introduced an additional [check for the node IP and returns an error if it is found empty](https://github.com/kubernetes/kubernetes/pull/77167/files#diff-934760ea1a4e195e49bcd10625cf4e46R146-R148). I believe this is the part that is causing the change in behavior: in Kubernetes 1.15, the check would be omitted and cause `iptables.NewProxier()` to set the default bind address to 127.0.0.1 (when iptables mode is set; I haven't checked other modes).

The PR's primary purpose seems to be a different one (retrying node IP retrieval from the API), so my understanding is that the added check was not really needed; unless I'm misunderstanding things which I don't want to rule out at all. 

The quick workaround was to explicitly configure kube-proxy with `--bind-address 127.0.0.1`. However, I'm not entirely sure if that's a good solution long-term compared to letting Kubernetes do The Right Thing, which is what I'd like to clarify through this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.1
- Cloud provider or hardware configuration: Kubernetes running on DigitalOcean VMs (droplets)
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): Linux master-k8s-1-16-test1 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64 GNU/Linux

/sig network

/cc @paulsubrata55 @thockin who were involved in the referenced PR.

### PR DESCRIPTION
**Pull request by zouyee**
SetDefaults_KubeProxyConfiguration will set config.BindAddress to IPv4 address "0.0.0.0" if not specified

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #83791

**Special notes for your reviewer**:
SetDefaults_KubeProxyConfiguration will set config.BindAddress to IPv4 address "0.0.0.0" if not specified

**Does this PR introduce a user-facing change?**:

```release-note
set config.BindAddress to IPv4 address "127.0.0.1" if not specified
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -278,11 +278,6 @@ func NewProxier(ipt utiliptables.Interface,
 	masqueradeValue := 1 << uint(masqueradeBit)
 	masqueradeMark := fmt.Sprintf("%#08x/%#08x", masqueradeValue, masqueradeValue)
 
-	if nodeIP == nil {
```
Comment (liggitt) [inline pkg/proxy/iptables/proxier.go]: This has been present for ~4 years (https://github.com/kubernetes/kubernetes/commit/1acaa1db09e96d297255270ecb1cf29791615fdf#diff-d51765b83fe795b469e8a86276b12dc9R218-R221). Can you explain why this is correct to remove?

**Comment by liggitt** [comment]
/assign @bowei @thockin 
as original reviewers of https://github.com/kubernetes/kubernetes/pull/77167

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go]: @liggitt I think https://github.com/kubernetes/kubernetes/pull/77167 introduced a breaking change where kube-proxy exits if nodeIP is nil. Before v1.16, if nodeIP is nil kube-proxy continues assuming later it would default node IP to 127.0.0.1.

Comment (zouyee) [reply pkg/proxy/iptables/proxier.go]: > This has been present for ~4 years ([1acaa1d#diff-d51765b83fe795b469e8a86276b12dc9R218-R221](https://github.com/kubernetes/kubernetes/commit/1acaa1db09e96d297255270ecb1cf29791615fdf#diff-d51765b83fe795b469e8a86276b12dc9R218-R221)). Can you explain why this is correct to remove?

At first, I thought that `iptables.NewProxier` was only used here, if so, it might be redundant to validate `nodeIP` again. Later, I found that it was used by https://github.com/kubernetes/kubernetes/blob/master/pkg/kubemark/hollow_proxy.go#L82, so I withdrew the modification here

File: cmd/kube-proxy/app/server_others.go [hunk 2]
```diff
@@ -137,7 +137,8 @@ func newProxyServer(
 	if nodeIP.IsUnspecified() {
 		nodeIP = utilnode.GetNodeIP(client, hostname)
 		if nodeIP == nil {
-			return nil, fmt.Errorf("unable to get node IP for hostname %s", hostname)
+			klog.Warning("invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP")
+			nodeIP = net.ParseIP("127.0.0.1")
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server_others.go]: The proxier implementations already sets node IP to 127.0.0.1 if it doesn't exist already, wondering if it makes more sense to remove this nil check altogether (see https://github.com/kubernetes/kubernetes/pull/84071).

Comment (timoreimann) [reply cmd/kube-proxy/app/server_others.go]: This change _may_ now impact `ipvs.NewProxier()` (I can't tell for sure currently as I'm on mobile only) which used to not necessarily come with a set node IP.

Is there a reason we cannot just drop line 140 without adding anything else? That's what the code originally used to do, so it seems like the cleaner approach to me with regards to addressing the bug.

Comment (andrewsykim) [reply cmd/kube-proxy/app/server_others.go]: IPVS proxier has the same behavior as iptables for nil `nodeIP` (see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L406-L409) so agreed with @timoreimann this can just be
```go
if nodeIP.IsUnspecified() {
	if nodeIP.IsUnspecified() {
		nodeIP = utilnode.GetNodeIP(client, hostname)
        }
}
```

Comment (andrewsykim) [reply cmd/kube-proxy/app/server_others.go]: IPVS proxier has the same behavior as iptables for nil `nodeIP` (see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L406-L409) so agreed with @timoreimann this can just be
```go
if nodeIP.IsUnspecified() {
	if nodeIP.IsUnspecified() {
		nodeIP = utilnode.GetNodeIP(client, hostname)
        }
}
```

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (thockin) [reply pkg/proxy/iptables/proxier.go]: How is this different from simply rolling back #77167 ?  I thought the point of that was to force kube-proxy not to proceed with a wrong IP address?

Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go]: https://github.com/kubernetes/kubernetes/pull/77167 also adds exponential back-off which fixes https://github.com/kubernetes/kubernetes/issues/37414 where kube-proxy would try to get the node IP before the node is registered. IMO removing the nodeIP check entirely and having the proxy implementations fall back to use 127.0.0.1 is better.

**Comment by andrewsykim** [comment]
This should probably go into the next cherry-pick of v1.16 since it's a breaking change? @zouyee can you address comments please?

File: cmd/kube-proxy/app/server_others.go (hunk 2 above)
Comment (thockin) [reply cmd/kube-proxy/app/server_others.go]: Should we remove the code in NewProxier implementations that checks for and handles nil?  This is kind of a contract change - they can assume it is non-nil.

So I guess from a compat POV this is correct.  From a correctness POV, this is wrong.  At least the iptables module will make a wrong decision based on this information.  IPVS seems only to log it.

Comment (thockin) [reply cmd/kube-proxy/app/server_others.go]: Having the user set the --bind-address seems like the RIGHT answer, but I acknowledge that this is a breaking change and we should fix it.

Can we enhance the log message to say something like:
````
    klog.V(0).Infof("can't determine this node's IP, assuming 127.0.0.1; if this is incorrect, set the --bind-address flag")
```

Of course, flags are passe and config files are vogue, and it's harder to reference config file fields.  This is also wrongish in the case of IPv6.

**Review by thockin — COMMENTED** [review]
Beef up the comment and I will approve

File: cmd/kube-proxy/app/server_others.go (hunk 2 above)
Comment (zouyee) [reply cmd/kube-proxy/app/server_others.go]: > Should we remove the code in NewProxier implementations that checks for and handles nil? This is kind of a contract change - they can assume it is non-nil.

If  iptables.NewProxier was only used here, it might be redundant to validate nodeIP `nil` again. But, I found that it was used by https://github.com/kubernetes/kubernetes/blob/master/pkg/kubemark/hollow_proxy.go#L82, so I withdrew the modification here

**Comment by zouyee** [comment]
/remove-area apiserver
/remove-area cloudprovider
/remove-area dependency
/remove-area e2e-test-framework
/remove-area ipvs
/remove-area kubeadm
/remove-area kubectl kubelet test
/remove-kind feature
/remove-sig api-machinery apps auth cli cloud-provider cluster-lifecycle network storage testing

/remove-sig node instrumentation scheduling
/remove-kind api-change
/remove-area code-generation

File: cmd/kube-proxy/app/server_others.go (hunk 2 above)
Comment (thockin) [reply cmd/kube-proxy/app/server_others.go]: Can we fix that do explicitly pass 127.0.0.1 and remove it from NewProxier?

Comment (zouyee) [reply cmd/kube-proxy/app/server_others.go]: > Can we fix that do explicitly pass 127.0.0.1 and remove it from NewProxier?

Done.PTAL

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by andrewsykim** [comment]
@zouyee can you cherry-pick this to v1.16 please?
