### PR TITLE
Fix the e2e bug related to the Garbage collector in api-machinery

### LINKED ISSUE #121582: The e2e CI test for the Garbage collector in sig-api-machinery is reporting an error
### What happened?

Kubernetes e2e suite: [It] [sig-api-machinery] Garbage collector should support orphan deletion of custom resources [sig-api-machinery]

As stated in https://github.com/kubernetes/apimachinery/blob/master/pkg/util/wait/poll.go#L84:
```
// Deprecated: This method does not return errors from context, use PollUntilContextTimeout.
// Note that the new method will no longer return ErrWaitTimeout and instead return errors
// defined by the context package. Will be removed in a future release.
func PollWithContext(ctx context.Context, interval, timeout time.Duration, condition ConditionWithContextFunc) error {
	return poll(ctx, false, poller(interval, timeout), condition)
}
```
When I replace PollWithContext with PollUntilContextTimeout in the test directory, the CI always returns the following error:
[Related links](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121401/pull-kubernetes-e2e-ec2/1717584584415121408)
```
{ failed [FAILED] failed to ensure the dependent is not deleted: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
In [It] at: test/e2e/apimachinery/garbage_collector.go:1110 @ 10/26/23 17:14:08.526
}
```

### What did you expect to happen?

The testcase can pass consistently.

### How can we reproduce it (as minimally and precisely as possible)?

In the code where the error occurs, replace PollWithContext with PollUntilContextTimeout

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind bug
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #121582

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
Hi, @pohly  
when you have a moment, could you please review this PR? Thank you very much.

File: test/e2e/apimachinery/garbage_collector.go [hunk 1]
```diff
@@ -1102,10 +1102,13 @@ var _ = SIGDescribe("Garbage collector", func() {
...
-		ginkgo.By("wait for 30 seconds to see if the garbage collector mistakenly deletes the dependent crd")
-		if err := wait.PollWithContext(ctx, 5*time.Second, 30*time.Second+gcInformerResyncRetryTimeout, func(ctx context.Context) (bool, error) {
+		ginkgo.By("wait for 90 seconds to see if the garbage collector mistakenly deletes the dependent crd")
+		if err := wait.PollUntilContextTimeout(ctx, 5*time.Second, 30*time.Second+gcInformerResyncRetryTimeout, false, func(ctx context.Context) (bool, error) {
 			_, err := resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
-			return false, err
+			if err != nil {
+				return false, err
+			}
+			return true, nil
```
Comment (pohly) [inline test/e2e/apimachinery/garbage_collector.go:1111]: This doesn't look right. If it returns `true` here, `PollUntilContextTimeout` will return a nil error and the test will pass in a situation where it should have failed.

In general, using any of the `wait.Poll` variants to check that something is true consistently obscures the intent of the test because one expects an error and then has to check for the "right" error.

Can you use `gomega.Consistently` instead? It might be as simple as:
```
gomega.Consistently(ctx, framework.Get(resourceClient.Get, dependentName, metav1.GetOptions{}).WithTimeout(30*time.Second+gcInformerResyncRetryTimeout).WithPollInterval(5*time.Second).Should(gomega.Succeed())
```

Comment (bzsuni) [reply test/e2e/apimachinery/garbage_collector.go]: Yes, you're right. 
Thanks for your suggestions. 
Can I modify it like this? Because I didn't find the method framework.Get
```
gomega.Consistently(func() error {
  _, err := resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
  return err
}, 30*time.Second+gcInformerResyncRetryTimeout, 5*time.Second).Should(gomega.BeNil())
```

File: test/e2e/apimachinery/garbage_collector.go [hunk 2]
```diff
@@ -1102,13 +1102,11 @@ var _ = SIGDescribe("Garbage collector", func() {
...
-		if err := wait.PollWithContext(ctx, 5*time.Second, 30*time.Second+gcInformerResyncRetryTimeout, func(ctx context.Context) (bool, error) {
+		ginkgo.By("wait for 90 seconds to see if the garbage collector mistakenly deletes the dependent crd")
+		gomega.Consistently(func() error {
 			_, err := resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
-			return false, err
-		}); err != nil && !wait.Interrupted(err) {
-			framework.Failf("failed to ensure the dependent is not deleted: %v", err)
-		}
+			return err
+		}, 30*time.Second+gcInformerResyncRetryTimeout, 5*time.Second).Should(gomega.BeNil())
```
Comment (pohly) [inline test/e2e/apimachinery/garbage_collector.go:1109]: Have you tried what I suggested? It's a bit simpler and handles retries properly, something that this code here doesn't.

Comment (pohly) [reply test/e2e/apimachinery/garbage_collector.go]: I see. Can you add `HandleRetry` (https://github.com/kubernetes/kubernetes/blob/38ed3ef7b7d00353ab81332c5c34e1cb5abec3f2/test/e2e/framework/get.go#L48C9-L48C20)?

Also, please use `gomega.Succeed()`. It provides a better failure message than `BeNil`.

Comment (pohly) [reply test/e2e/apimachinery/garbage_collector.go]: Another problem with your `func() error` approach is that it doesn't use the context provided by `gomega.Consistently`. Instead, the anonymous function uses the context from the surrounding test. Please use `func(ctx context.Context) error` instead.

Comment (bzsuni) [reply test/e2e/apimachinery/garbage_collector.go]: Yes, thanks. Is it right then?
```
gomega.Consistently(ctx, framework.HandleRetry[*unstructured.Unstructured](
  func(ctx context.Context) (*unstructured.Unstructured, error) {
  return resourceClient.Get(ctx, dependentName, metav1.GetOptions{})})).WithTimeout(30*time.Second + gcInformerResyncRetryTimeout).WithPolling(5*time.Second).Should(gomega.Succeed())
```

**Comment by pohly** [comment]
Some syntax error crept into that last update, it's not compiling.

File: test/e2e/apimachinery/garbage_collector.go [hunk 3]
```diff
@@ -1101,14 +1101,14 @@ var _ = SIGDescribe("Garbage collector", func() {
...
-		}); err != nil && !wait.Interrupted(err) {
-			framework.Failf("failed to ensure the dependent is not deleted: %v", err)
-		}
+		// Wait 90s and ensure the dependent is not deleted.
+		ginkgo.By("wait for 90 seconds to see if the garbage collector mistakenly deletes the dependent crd")
+		gomega.Consistently(ctx, func(ctx context.Context) error {
+			_, err := framework.HandleRetry(func(ctx context.Context) (*unstructured.Unstructured, error) {
+				return resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
+			})(ctx)
+			return err
```
Comment (pohly) [inline test/e2e/apimachinery/garbage_collector.go:1110]: This can be simplified:
```
gomega.Consistently(ctx, framework.HandleRetry(func(ctx context.Context) (*unstructured.Unstructured, error) { return resourceClient.Get(ctx, dependentName, metav1.GetOptions{}))).WithTimeout(timeout).WithPolling(5 * time.Second).Should(gomega.Succeed())
```

File: test/e2e/apimachinery/garbage_collector.go [hunk 4]
```diff
@@ -1101,14 +1101,14 @@ var _ = SIGDescribe("Garbage collector", func() {
...
-		// Wait 30s and ensure the dependent is not deleted.
-		ginkgo.By("wait for 30 seconds to see if the garbage collector mistakenly deletes the dependent crd")
-		if err := wait.PollWithContext(ctx, 5*time.Second, 30*time.Second+gcInformerResyncRetryTimeout, func(ctx context.Context) (bool, error) {
-			_, err := resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
-			return false, err
-		}); err != nil && !wait.Interrupted(err) {
-			framework.Failf("failed to ensure the dependent is not deleted: %v", err)
-		}
+		// Wait 90s and ensure the dependent is not deleted.
+		ginkgo.By("wait for 90 seconds to see if the garbage collector mistakenly deletes the dependent crd")
```
Comment (pohly) [inline test/e2e/apimachinery/garbage_collector.go:1105]: Who do you know that it's 90 seconds? Better don't make assumptions about the value of `gcInformerResyncRetryTimeout`:
```suggestion
                timeout := 30*time.Second + gcInformerResyncRetryTimeout
		ginkgo.By(fmt.Sprintf("wait for %s to see if the garbage collector mistakenly deletes the dependent crd"), timeout))
```

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e/apimachinery/garbage_collector.go (hunk 4 above)
Comment (bzsuni) [reply test/e2e/apimachinery/garbage_collector.go]: Yes, you are absolutely right. Thank you very much for your advice.

Comment (bzsuni) [reply test/e2e/apimachinery/garbage_collector.go]: It seems that a match for error type is needed here？
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121583/pull-kubernetes-e2e-kind/1719286645296992256

File: test/e2e/apimachinery/garbage_collector.go (hunk 3 above)
Comment (bzsuni) [reply test/e2e/apimachinery/garbage_collector.go]: It seems that a match for error type is needed here？
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121583/pull-kubernetes-e2e-kind/1719286645296992256

File: test/e2e/apimachinery/garbage_collector.go [hunk 5]
```diff
@@ -1101,14 +1101,11 @@ var _ = SIGDescribe("Garbage collector", func() {
...
-			_, err := resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
-			return false, err
-		}); err != nil && !wait.Interrupted(err) {
-			framework.Failf("failed to ensure the dependent is not deleted: %v", err)
-		}
+		timeout := 30*time.Second + gcInformerResyncRetryTimeout
+		ginkgo.By(fmt.Sprintf("wait for %s to see if the garbage collector mistakenly deletes the dependent crd\n", timeout))
+		gomega.Consistently(ctx, framework.HandleRetry(func(ctx context.Context) (*unstructured.Unstructured, error) {
+			return resourceClient.Get(ctx, dependentName, metav1.GetOptions{})
+		})).WithTimeout(timeout).WithPolling(5*time.Second).Should(gomega.And(gomega.Succeed()), gomega.Not(gomega.BeNil()))
```
Comment (pohly) [inline test/e2e/apimachinery/garbage_collector.go:1108]: What I had suggested earlier (only `gomega.Succeed`) wasn't right: `gomega.Consistently` implicitly does the error checking when giving a function which returns "value + error". Then the value is passed to the matcher.

I'm not sure if doing both here works (haven't looked at test results), but just `ShouldNot(gomega.BeNil())` should be fine: the error is checked by `Consistently` and then we verify that we actually got some object.

**Review by pohly — APPROVED** [review]
Thanks for your patience. I think we found a good solution in the end :smile: 

/lgtm
/approve

**Comment by bzsuni** [comment]
> Thanks for your patience. I think we found a good solution in the end :smile: 
> 


Thank you too. It was my pleasure to have a conversation with you

**Comment by pacoxu** [comment]
/milestone v1.29
For test
