### PR TITLE
reduce logspam when calculating sandbox resources

### LINKED ISSUE #131914: Kubelet logspam: "Enforcing CFS Quota"
On v1.33 nodes, the Kubelet logs now have lots of lines like
```
kuberuntime_sandbox_linux.go:62] "Enforcing CFS quota" pod="kube-system/pdcsi-node-n234h" unlimited=false
```

This log line is not particularly informative. I think it should be moved to a higher verbosity or just removed.

It might be more informative to log the full generated LinuxContainerResources, but that would only be for a higher verbosity log anyway.

Looks like this was introduced in https://github.com/kubernetes/kubernetes/pull/127525

I'm not going to label this a regression, but I think we should consider backporting the fix.

/kind bug

/cc scott-grimes
/sig node

### PR DESCRIPTION
**Pull request by Peac36**
#### What type of PR is this?
kind cleanup

#### What this PR does / why we need it:

Fixes: https://github.com/kubernetes/kubernetes/issues/131914

#### Does this PR introduce a user-facing change?
Nope 

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
reduce logspam when calculating the container resources on linux


```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 1]
```diff
@@ -59,9 +59,10 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 
 	// If pod has exclusive cpu the sandbox will not have cfs quote enforced
 	disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod)
-	klog.V(2).InfoS("Enforcing CFS quota", "pod", klog.KObj(pod), "unlimited", disableCPUQuota)
 
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory(), disableCPUQuota)
+	resources := m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory(), disableCPUQuota)
+	klog.V(4).InfoS("Enforcing CFS quota", "pod", klog.KObj(pod), "unlimited", disableCPUQuota, "resources", resources)
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: Thanks for the contribution!
this looks correct, but it adds unnecessary changes logging extra data which we're not sure we need. I'd just bump the relevant log to `V=4` or so. May be worth use V=5 or more.
There are more instances of messages like this, please `git grep` for "CFS quota" or so.

Comment (Peac36) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: >this looks correct, but it adds unnecessary changes logging extra data which we're not sure we need. 

In the issue's description, it was mentioned that it would be beneficial for debugging, but if you think it's too much, that's okay.

>There are more instances of messages like this, please git grep for "CFS quota" or so.

I've increased the log level for all instances of "CFS quota"  that I've found.

Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: Hi, thanks for the updates. Regading the verbosity level I'm still thinking if it should be V=4 or V=5 indeed. Nothing are really wrong though, and I'm inclined to go with V=5 as suggested, but is not a clear cut.

>In the issue's description, it was mentioned that it would be beneficial for debugging, but if you think it's too much, that's okay.

Yes, this was suggested as more informative approach (which I don't disagree with) but thing is adding this information is a different change, so it should be on its own commit (preferably in its own PR, but this is too much unfortunately). Let's see how the logs look like and we can add this data in a followup commit in this series maybe.

[EDIT] Thinking about it, the current logs in the codebase are indeed excessive, but want to tell WHY the resources where computed in a certain way (focus on input), while logging the computed resource configs makes us aware of the WHAT (focus on output). The best logging would probably be like it was initially proposed: add the computed resources AND bump the verbosity. This however needs to be conveyed in the PR/commit messages and it is a wider scope than reducing log spam; in order to just reduce log spam, bumping the verbosity of the existing logs is sufficient.

Comment (tallclair) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: We may want to backport this change to v1.33, so I'd prefer to constrain this PR to just bumping the verbosity, and add the computed resources in a separate PR.

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 2]
```diff
@@ -77,7 +77,7 @@ func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	if !alreadyExists {
 		enforceCPULimits := m.enforceCPULimits
 		if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.podContainerManager.PodHasExclusiveCPUs(pod) {
-			klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
+			klog.V(5).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/cm/pod_container_manager_linux.go]: per discussion in https://github.com/kubernetes/kubernetes/pull/127525/files#r1940278408 this log is expected to happen rarely and is expected to tell us the fix took place. So I think it should be kept V=2 (my previous comment was too broad).

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -703,7 +703,7 @@ func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podContainerC
 	enforceCPULimits := m.cpuCFSQuota
 	if utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod) {
 		enforceCPULimits = false
-		klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
+		klog.V(5).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: likewise, per discussion in https://github.com/kubernetes/kubernetes/pull/127525/files#r1940278408 this log is expected to happen rarely and is expected to tell us the fix took place. So I think it should be kept V=2 (my previous comment was too broad).

**Review by ffromani — COMMENTED** [review]
thanks @Peac36 . I agree with @tallclair this change should be minimal to make the backport possible and smooth. We need one final minimal tuning and should be good to go (sorry for the partial back and forth)

**Comment by Peac36** [comment]
@ffromani  - got it. I've updated the log level accordingly. @tallclair  mentioned something about the backport. Do I need to do anything for this backport, or is there automation that would handle this?

**Comment by ffromani** [comment]
> @ffromani - got it. I've updated the log level accordingly. @tallclair mentioned something about the backport. Do I need to do anything for this backport, or is there automation that would handle this?

Thanks for the updates! I will review shortly but I'm positive that other than my previous comments the PR is good to go.
The backport process is still manual unfortunately https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

Other contributors can take care of the cherry pick, meaning is not necessarily something the original PR author is in charge to do. May or may not be.

In our case https://github.com/kubernetes/kubernetes/pull/127525 was merged in 1.33 so we need to backport only on 1.33.
