### PR TITLE
hostNetwork tests can't share the same port

### LINKED ISSUE #104406: hostNetwork tests can't use the same port or they will collide
Failed here
```
Kubernetes e2e suite: [sig-network] Services should respect internalTrafficPolicy=Local Pod to Pod (hostNetwork: true) [Feature:ServiceInternalTrafficPolicy] expand_more
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104401/pull-kubernetes-e2e-ubuntu-gce-network-policies/1427400844852072448
/retest

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/issues/104401#issuecomment-900063266_

This fails because the pod tries to bind port 80, that is a very demanded port, but there are two tests doing that, that increase the chance to collide

### PR DESCRIPTION
**Pull request by aojea**
The pods using hostNetwork use the host network namespace, hence
they have to share it with the rest of the process and pods.
If several pods try to bind to the same port, the test will fail,
so we try to use a non common port, and run the different scenario
in the same test, so we only have to bind once and we avoid consuming
ports reducing the port collision risk.

/kind failing-test
/kind flake
Fixes #104406

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/retest

Unrelated failure

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -2215,20 +2215,23 @@ var _ = common.SIGDescribe("Services", func() {
 		serviceName := "svc-itp"
 		ns := f.Namespace.Name
 		servicePort := 80
+		// If the pod can't bind to this port, it will fail to start, and it will fail the test,
+		// because is using hostNetwork. Using a not common port will reduce this possibility.
+		endpointPort := 10180
```
Comment (libaoan) [inline test/e2e/network/service.go:2220]: I think a random port number is best here

Comment (aojea) [reply test/e2e/network/service.go:2220]: we discussed that approach before and that was discarded because the test failures will be hard to debug, you can't know which port is free in advance, at least, with this  approach you know that if it fails to bind it will fail consistently in the same port
This is not great, but the alternative is not much better

**Comment by aojea** [comment]
ups, it seems we collide :) @danwinship 
hostnetwork tests have to run in the same ginkgo statement, same as we did with the other connectivity tests

**Comment by aojea** [comment]
```
E2eNode Suite: [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api 
```
unrelated failure
/retest
