### PR TITLE
Enforce specified service-cluster-ip-range is not too large

### LINKED ISSUE #12820: Service IP registry assumes CIDRs of /16 and smaller (less IPs), too big fails
If you spec a /8 for your service Cluster IPs, the bitmask becomes 2 MB, which is too big for etcd.

We should enforce that the prefix be /12 or smaller or something like that.

@smarterclayton

### PR DESCRIPTION
**Pull request by wb14123**
This fixes #12820

### CODE REVIEW

**Comment by wb14123** [comment]
I signed it!

File: cmd/kube-apiserver/app/server.go [hunk 1]
```diff
@@ -227,6 +227,10 @@ func (s *APIServer) verifyClusterIPFlags() {
 	if s.ServiceClusterIPRange.IP == nil {
 		glog.Fatal("No --service-cluster-ip-range specified")
 	}
+	var ones, bits = s.ServiceClusterIPRange.Mask.Size()
+	if bits-ones > 20 {
```
Comment (mikedanese) [inline cmd/kube-apiserver/app/server.go]: should be greater than or equal to since we allow /12.

nit: move the assignment into the if.
```golang
if ones, bits := s.ServiceClusterIPRange.Mask.Size(); bits-ones > 20 {
```

Comment (wb14123) [inline cmd/kube-apiserver/app/server.go]: This allows /12: 32 - 12 = 20 not > 20, so the error is not reported.

Comment (mikedanese) [inline cmd/kube-apiserver/app/server.go]: oops misread. Thanks for explanation.

Comment (thockin) [inline cmd/kube-apiserver/app/server.go]: Why is this not simply `ones < 12`?  No confusion there :)

Also 12 should be a `const minServiceCIDRMask` or something

Comment (wb14123) [inline cmd/kube-apiserver/app/server.go]: I'm not so familiar with Golang and don't know if the mask only appears in IPv4. If the IPNet is an IPv6 format, then just verify `ones` would be wrong since the storage is related to zeros.

Comment (thockin) [inline cmd/kube-apiserver/app/server.go]: Fair answer.

**Comment by thockin** [comment]
lgtm
