### PR TITLE
kubelet: return mirror pod in GetActivePods()

### LINKED ISSUE #73572: Static and critical pod is evicted
**What happened**:

Eviction manager evicts the below static and critical pod when the node observed MemoryPressure.
The k8s server version is v1.13.2, and the pod priority is enabled.

```yaml
Name:               node-prober-worker-7c8f45f1-zczzz-caas-m22qk-test
Namespace:          kube-system
Priority:           2000001000
PriorityClassName:  system-node-critical
...
Annotations:        kubernetes.io/config.source: file
...
Status:             Failed
Reason:             Evicted
Message:            The node was low on resource: memory. Container bph was using 11896Ki, which exceeds its request of 0. 
...
```

As far as I can see, the eviction manager does not evict such pods.
https://github.com/kubernetes/kubernetes/blob/6cea9266dcfb89d1d278d102885c03b11dbe26fc/pkg/kubelet/eviction/eviction_manager.go#L547

**What you expected to happen**:

Static pods with `SystemCriticalPriority` are not deleted as well as those with a critical pod annotation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Boot pod with system-node-critical priority using by kubelet `--pod-manifest-path` option
2. Apply memory load to the target node until eviction manager observes memory pressure.
3. The critical and static pod is evicted.

**Anything else we need to know?**:

When I set critical-pod annotation (and enables `ExperimentalCriticalPodAnnotation`) insted of pod priority, the eviction manager **DOES NOT** evict the static and critical pod.

```
Jan 31 05:23:29 worker-7c8f45f1-zczzz-test-m22qk-test kubelet-wrapper[10083]: I0131 05:23:29.942701   10083 eviction_manager.go:358] eviction manager: pods ranked for eviction: node-prober-worker-7c8f45f1-zczzz-test-m22qk-test_kube-system(70eede23a9faee60311f7ee4a0d6457e), stress1-67f94bb9cf-m4qkx_kube-system(480601e2-2518-11e9-9b99-fa163efcff57), stress1-67f94bb9cf-72qxp_kube-system(0b77dd77-2518-11e9-9b99-fa163efcff57), stress1-67f94bb9cf-qtnt4_kube-system(0b7cc794-2518-11e9-9b99-fa163efcff57), stress1-67f94bb9cf-6fg72_kube-system(0b7ae76f-2518-11e9-9b99-fa163efcff57), stress1-67f94bb9cf-f7r8j_kube-system(0b7cd495-2518-11e9-9b99-fa163efcff57), stress1-67f94bb9cf-t5n9g_kube-system(49738ffc-2518-11e9-9b99-fa163efcff57), pod-network-problem-detector-tw9f6_kube-system(f0ba6ab2-2517-11e9-9b99-fa163efcff57), node-exporter-z49dm_kube-system(f0ba7978-2517-11e9-9b99-fa163efcff57), container-log-forwarder-s6z7s_kube-system(f6b56829-2517-11e9-9b99-fa163efcff57)
Jan 31 05:23:29 worker-7c8f45f1-zczzz-test-m22qk-test kubelet-wrapper[10083]: E0131 05:23:29.942727   10083 eviction_manager.go:548] eviction manager: cannot evict a critical static pod node-prober-worker-7c8f45f1-zczzz-test-m22qk-test_kube-system(70eede23a9faee60311f7ee4a0d6457e)
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration: baremetal

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

For static pod, kubelet maintains a pair of {static pod, mirror pod} internally. Mirror pod reflects the real status of the pod, and also persisted in etcd/apiserver, audited by admission plugins, etc.

But when kubelet makes eviction decisions, it fetches regular pods + static pods. It's problematic b/c "static pod" is just a snapshot of the yaml file, hence it doesn't carry the real info like "spec.priority" (usually only "spec.priorityClassName" is defined in yaml file and hence "spec.priority" is nil b/c it's updated by admission plugin). This is what issue #73572 reported.

**Which issue(s) this PR fixes**:

Fixes #73572

**Special notes for your reviewer**:

This PR is based on the assumption that static pod don't need or can't be updated. Otherwise I can come up with optimal solutions.

**Does this PR introduce a user-facing change?**:

```release-note
Kubelet won't evict a static pod with priority `system-node-critical` upon resource pressure.
```

/sig node
/sig scheduling

### CODE REVIEW

**Comment by anarchistHH1983** [comment]
Master

**Comment by Huang-Wei** [comment]
cc/ @yujuhong as you seem to be most recent author on mirror pod related logic. Ignore if I'm wrong.

/priority important-soon

**Comment by Huang-Wei** [comment]
`pull-kubernetes-local-e2e-containerized` keeps failing. Related with #73073

**Comment by Huang-Wei** [comment]
/assign @yujuhong 

for reviewing.

**Comment by derekwaynecarr** [comment]
is there a e2e or unit test we can write around eviction manager to confirm this does not regress again?

**Comment by Huang-Wei** [comment]
@derekwaynecarr I will try to compose a test.

**Comment by Huang-Wei** [comment]
@derekparker e2e test has been added, PTAL. I verified locally that it fails on codebase without my change, and passes with my change.

PS: the local test is running as `make test-e2e-node SKIP="XYZ" FOCUS="SystemNodeCriticalPod" TEST_ARGS='--feature-gates=DynamicKubeletConfig=true,LocalStorageCapacityIsolation=true'`.

PSS: the e2e test gets skipped due to keyword "slow/serial/disruptive tests". Let me know if you'd like to enable it in ci pre-commit temporarily.

**Comment by derekwaynecarr** [comment]
I will verify locally for now, thanks for test.

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -88,7 +88,19 @@ func (kl *Kubelet) listPodsFromDisk() ([]types.UID, error) {
 
 // GetActivePods returns non-terminal pods
 func (kl *Kubelet) GetActivePods() []*v1.Pod {
-	allPods := kl.podManager.GetPods()
+	allPods, mirrorPods := kl.podManager.GetPodsAndMirrorPods()
```
Comment (ravisantoshgudimetla) [inline pkg/kubelet/kubelet_pods.go]: Why can't we make this change within `GetPodsAndMirrorPods()` fn? I don't see any other place in the code where this is being used.

Comment (Huang-Wei) [reply pkg/kubelet/kubelet_pods.go]: `GetPodsAndMirrorPods()` is defined as:

> // GetPodsAndMirrorPods returns the both regular and mirror pods.

So IMO "regular pods" literally means all pods including "real regular" and "static" pods. I prefer to think of current function as a consistent behavior with the comment.

Comment (ravisantoshgudimetla) [reply pkg/kubelet/kubelet_pods.go]: I am fine with the change, just that I am not sure, if there is a need of using static pods somewhere else in the code base instead of using mirror pods. If we have some use then it makes sense to keep the function as is.

**Comment by ravisantoshgudimetla** [comment]
I verified this test locally on kube master branch, it is working as expected but I see the following the logs even when the eviction is not happening.

`kubelet_pods.go:914] Pod "hello-world-127.0.0.1_kube-system(8c4c406b-3aa1-11e9-b9d9-c85b76333877)" is terminated, but some containers are still running`

**Comment by Huang-Wei** [comment]
Kindly ping @derekwaynecarr as 1.14 code freeze is approaching.

cc/ @bsalamat @k82cn

**Comment by derekwaynecarr** [comment]
thank you for adding the test case.

/approve
/lgtm

**Comment by namreg** [comment]
this patch does not work. see https://github.com/kubernetes/kubernetes/issues/73572#issuecomment-470426246

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (tedyu) [inline pkg/kubelet/kubelet_pods.go]: Looking at the other usage of mirrorPods in removeOrphanedPodStatuses, the mirrorPods can be in the Map structure shown below (and not affecting functionality).
I wonder if GetPodsAndMirrorPods should return mirror pods in Map.

Comment (Huang-Wei) [reply pkg/kubelet/kubelet_pods.go]: @tedyu this PR is incomplete. Please check the other PR #75144.
