### PR TITLE
Move code to prepare for e2e/restart transition

### LINKED ISSUE #10826: GCE/GKE: test/e2e/restart.go - MIG rolling update with identical template will not restart nodes
test/e2e/restart.go, func restartNodes, assumes that MIG rolling update on GCE will cause node restart.

However, there is a feature of MIG rolling update (currently broken) that skips update if the new instance template is the same as the old one.
The feature is supposed to work quite soon, so the test will not test anything (reboot will not be performed).

A workaround may be to create an identical instance template with a different name.

By the way, the current name `restartNodes` is misleading. It should be `recreateNodes`.

cc @mbforbes @quinton-hoole

### PR DESCRIPTION
**Pull request by mbforbes**
**This only moves code around and adds a comment.**

This is to prepare for #10826, where we'll switch the restart test from a MIG rolling-update to a recreate-instances call. Thus, I'm moving the rolling-update code to the only place it's used (`cluster_upgrade.go`) and moving `parseKVLines` to the common area (`util.go`) where it will be shared (recreate-instances will also use it).

I also added a comment that describes how to fix #10826 because I already did it in bash and it was annoying. If a piano falls on me, no one will have to re-solve that.

The purpose of this PR is to minimize the size of the next PR so its risk can be accurately assessed.

### CODE REVIEW

**Comment by mbforbes** [comment]
@mikedanese and @zmerlynn could probably give LGTMs but we need TLs... @roberthbailey and @davidopp? Also +cc @marekbiskup as he kindly raised this issue.

**Comment by mbforbes** [comment]
Holy cow, all green!

**Comment by mikedanese** [comment]
LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
Re-assigning to @ixdy for ok-to-merge.

File: test/e2e/cluster_upgrade.go [hunk 1]
```diff
@@ -494,3 +494,153 @@ func validate(f Framework, svcNameWant, rcNameWant string, ingress api.LoadBalan
...
+
+	By(fmt.Sprintf("polling the MIG rolling update (%s) until it completes", id))
+	if err := migRollingUpdatePoll(id, nt); err != nil {
+		return fmt.Errorf("err waiting until update completed: %v", err)
+	}
+
+	return nil
+}
+
+// migTemlate (GCE/GKE-only) returns the name of the MIG template that the
```
Comment (ixdy) [inline test/e2e/cluster_upgrade.go]: don't need to fix now, but migTemlate is a typo.
