### PR TITLE
Issue #70020; Flush Conntrack entities for SCTP

### LINKED ISSUE #70020: Conntrack entities for SCTP are not flushed for deleted Service endpoints
/kind bug
/sig network

I have the K8s 1.12.1 deployment with SCTP support implementation from #64973. I have faced an issue while running SCTP traffic and it’s the same issue as #19029 with UPD protocol. SCTP conntrack doesn’t flush entries for deleted pods. Thus associations which were established on that deleted pod can not be reestablished since conntrack still tries to route all the SCTP packets (INIT/DATA) to not existent IP. Unless the association is explicitly ABORTed from remote side (this way conntrack will delete the entry).
Reproduction steps are the same as in UDP case:
1.	Create a Service for SCTP port
2.	Create pods that bind to this Service 
3.	Start a client Pod that uses the Service. This client establishes SCTP association to the Service and sends data via this assoc
4.	Check which Pod handles all the traffic in scope of the association (collect tcpdump for example)
5.	Delete that Service endpoint by, for example, killing the corresponding Pod which the client is communicating with
6.	Observe that the Pod's IP no longer appears in endpoints (e.g. using kubectl)
7.	BUG: Observe that conntrack still NATs all SCTP traffic to deleted endpoint.
8.	WORKAROUND 1: use client Pod to explicitly ABORT and reestablish the association.
9.	WORKAROUND 2: use conntrack –D to manually remove the entity in conntrack Hash Table
I guess the solution will be just the same as [here](https://github.com/kubernetes/kubernetes/pull/22573/commits/4fa6f3841ad362844c3c1e04c8657cacad5decde#diff-d51765b83fe795b469e8a86276b12dc9R591) and [here](https://github.com/kubernetes/kubernetes/pull/22573/commits/4fa6f3841ad362844c3c1e04c8657cacad5decde#diff-d51765b83fe795b469e8a86276b12dc9R608).(reusing these functions for SCTP protocol). Basically it’s just adding api.ProtocolSCTP into a couple of checks in solution #22573

### PR DESCRIPTION
**Pull request by uablrek**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Lingering SCTP conntrack entries prevent reestablishment. Please see the issue #70020

**Which issue(s) this PR fixes**:

Fixes #70020

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by KomorkinMikhail** [comment]
Hi @janosi 
Just letting you know about this PR. Think you will be interested. It's regarding conntrack issue in SCTP.

**Comment by janosi** [comment]
Hi @KomorkinMikhail,
Thank you for the notification! I appreciate it! Also thank you for the effort @uablrek !

**Comment by KomorkinMikhail** [comment]
@dcbw @brendandburns 
If you have any questions regarding implementation of this PR do not hesitate to ask me or @uablrek. We are looking forward to merge this one

**Comment by KomorkinMikhail** [comment]
@dcbw @brendanburns 
Hi guys. Have you had any chance to review the changes? We highly anticipate this fix to be on the main branch.

**Comment by MaximProshin** [comment]
@dcbw @brendandburns, do you plan to review it? Do you have any forecast?
It seems to be pretty simple correction as the same was fixed for UDP.

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -1369,7 +1369,6 @@ func (proxier *Proxier) syncProxyRules() {
 	if err := proxier.healthChecker.SyncEndpoints(endpointUpdateResult.HCEndpointsLocalIPSize); err != nil {
 		klog.Errorf("Error syncing healthcheck endpoints: %v", err)
 	}
-
```
Comment (dcbw) [inline pkg/proxy/iptables/proxier.go]: @uablrek unecessary whitespace removal?

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -601,14 +601,14 @@ func servicePortEndpointChainName(servicePortName string, protocol string, endpo
 // TODO: move it to util
 func (proxier *Proxier) deleteEndpointConnections(connectionMap []proxy.ServiceEndpoint) {
 	for _, epSvcPair := range connectionMap {
-		if svcInfo, ok := proxier.serviceMap[epSvcPair.ServicePortName]; ok && svcInfo.GetProtocol() == v1.ProtocolUDP {
+		if svcInfo, ok := proxier.serviceMap[epSvcPair.ServicePortName]; ok && (svcInfo.GetProtocol() == v1.ProtocolUDP || svcInfo.GetProtocol() == v1.ProtocolSCTP) {
```
Comment (dcbw) [inline pkg/proxy/iptables/proxier.go]: Might make sense to create a separate function like "needsClearConntrack(proto v1.Protocol) bool" for this and use it in both places here, *and* in proxier_test.go below.

**Review by dcbw — CHANGES_REQUESTED** [review]
@uablrek also needs a rebase to fix the conflict.

**Comment by danwinship** [comment]
@uablrek can you rebase?

File: pkg/util/conntrack/conntrack.go [hunk 3]
```diff
@@ -119,7 +119,15 @@ func ClearEntriesForPortNAT(execer exec.Interface, dest string, port int, protoc
...
 	if err != nil && !strings.Contains(err.Error(), NoConnectionToDelete) {
-		return fmt.Errorf("error deleting conntrack entries for UDP port: %d, error: %v", port, err)
+		return fmt.Errorf("error deleting conntrack entries for %s port: %d, error: %v", protoStr(protocol), port, err)
 	}
 	return nil
 }
+
+// IsClearConntrackNeeded returns true if protocol requires conntrack cleanup for the stale connections
+func IsClearConntrackNeeded(proto v1.Protocol) bool {
+	if proto == v1.ProtocolUDP || proto == v1.ProtocolSCTP {
```
Comment (aojea) [inline pkg/util/conntrack/conntrack.go]: nit, I guess this can be reduced to
```
return proto == v1.ProtocolUDP || proto == v1.ProtocolSCTP
```

File: pkg/util/conntrack/conntrack_test.go [hunk 4]
```diff
@@ -200,30 +208,52 @@ func TestDeleteUDPConnections(t *testing.T) {
...
+			proto:  v1.ProtocolUDP,
 		},
 		{
 			name:   "IPv6 success",
 			origin: "fd00::600d:f00d",
 			dest:   "2001:db8::5",
+			proto:  v1.ProtocolUDP,
+		},
+		{
+			name:   "IPv4 success",
```
Comment (aojea) [inline pkg/util/conntrack/conntrack_test.go]: I guess we should update the name of the tests with the protocol to differentiate them

File: pkg/util/conntrack/conntrack_test.go [hunk 5]
```diff
@@ -235,42 +265,46 @@ func TestDeleteUDPConnections(t *testing.T) {
...
-			name: "IPv4 success",
-			port: 30211,
-			dest: "1.2.3.4",
+			name:  "IPv4 success",
+			port:  30211,
+			dest:  "1.2.3.4",
+			proto: v1.ProtocolUDP,
+		},
+		{
+			name:  "IPv4 success",
```
Comment (aojea) [inline pkg/util/conntrack/conntrack_test.go]: ditto, updating the name with the protocol?

File: pkg/proxy/ipvs/graceful_termination.go [hunk 6]
```diff
@@ -167,7 +167,8 @@ func (m *GracefulTerminationManager) deleteRsFunc(rsToDelete *listItem) (bool, e
 			// For UDP traffic, no graceful termination, we immediately delete the RS
 			//     (existing connections will be deleted on the next packet because sysctlExpireNoDestConn=1)
 			// For other protocols, don't delete until all connections have expired)
-			if strings.ToUpper(rsToDelete.VirtualServer.Protocol) != "UDP" && rs.ActiveConn+rs.InactiveConn != 0 {
+			proto := strings.ToUpper(rsToDelete.VirtualServer.Protocol)
+			if proto != "UDP" && proto != "SCTP" && rs.ActiveConn+rs.InactiveConn != 0 {
```
Comment (danwinship) [inline pkg/proxy/ipvs/graceful_termination.go]: should this use `conntrack.IsClearConntrackNeeded`? it's not quite the same thing, but...

either way, the comment above is wrong now

**Review by danwinship — COMMENTED** [review]
just one nit

**Comment by uablrek** [comment]
Updated after comments and squashed.

**Comment by uablrek** [comment]
@brendanburns Can you please review so this can be merged?

**Comment by aojea** [comment]
/assign @thockin 
he's been more active :smile:

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
