### PR TITLE
Issue 71769: Correctly display '_' in the help message

### LINKED ISSUE #71769: kubectl help can't display underscore properly
**What happened**:
kubectl help description can't display underscore properly.

Example 1:
`kubectl diff -h`

```
Diff configurations specified by filename or stdin between the current online configuration, and the configuration as it
would be if applied.

Output is always YAML.

KUBECTL EXTERNAL DIFF environment variable can be used to select your own diff command. By default, the "diff" command
available in your path will be run with "-u" (unicode) and "-N" (treat new files as empty) options.
```
The environment variable `KUBECTL_EXTERNAL_DIFF` displayed but missing underscore.

Example 2:
`kubectl apply edit-last-applied -h`

```
Edit the latest last-applied-configuration annotations of resources from the default editor.

The edit-last-applied command allows you to directly edit any API resource you can retrieve via the command line tools.
It will open the editor defined by your KUBE _EDITOR, or EDITOR environment variables, or fall back to 'vi' for Linux or
'notepad' for Windows. You can edit multiple objects, although changes are applied one at a time. The command accepts
filenames as well as command line arguments, although the files you point to must be previously saved versions of
resources.
```

The environment variable `KUBE_EDITOR` with an additional space before underscore.

**What you expected to happen**:

Display underscore properly without missing or additional space.

**How to reproduce it (as minimally and precisely as possible)**:

Use kubectl and run following example:

`kubectl diff -h`
`kubectl apply edit-last-applied -h`
`kubectl config rename-context -h`

**Anything else we need to know?**:

The description are correctly in code base, but display with wrong message format.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/diff/diff.go#L54
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply/apply_edit_last_applied.go#L33

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

and also linux version kubectl

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

### PR DESCRIPTION
**Pull request by YoubingLi**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Correctly display '_" in the help message

**Which issue(s) this PR fixes**:
Fixes #71769

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by YoubingLi** [comment]
I signed it

**Comment by YoubingLi** [comment]
Test result:

./kubectl apply edit-last-applied -h | grep _

 The edit-last-applied command allows you to directly edit any API resource you can retrieve via the command line tools. It will open the editor defined by your **KUBE_EDITOR**, or EDITOR environment variables, or fall back to 'vi' for Linux or 'notepad' for Windows. You can edit multiple objects, although changes are applied one at a time. The command accepts filenames as well as command line arguments, although the files you point to must be previously saved versions of resources.

 ./kubectl diff -h | grep _

 **KUBECTL_EXTERNAL_DIFF** environment variable can be used to select your own diff command. By default, the "diff" command available in your path will be run with "-u" (unicode) and "-N" (treat new files as empty) options.

 ./kubectl config rename-context -h | grep _

 **CONTEXT_NAME** is the context name that you wish change.
 **NEW_NAME** is the new name you wish to set.
  kubectl config rename-context **CONTEXT_NAME NEW_NAME** [options]

./kubectl config unset --help | grep _

 **PROPERTY_NAME** is a dot delimited name where each token represents either an attribute name or a map key.  Map keys may not contain dots.
  kubectl config unset **PROPERTY_NAME** [options]

**Comment by YoubingLi** [comment]
@seans3 @ghodss 
    Please help review this code change.

Thanks
Youbing

File: pkg/kubectl/util/templates/normalizers.go [hunk 1]
```diff
@@ -70,7 +70,7 @@ type normalizer struct {
 
 func (s normalizer) markdown() normalizer {
 	bytes := []byte(s.string)
-	formatted := blackfriday.Markdown(bytes, &ASCIIRenderer{Indentation: Indentation}, 0)
+	formatted := blackfriday.Markdown(bytes, &ASCIIRenderer{Indentation: Indentation}, blackfriday.EXTENSION_NO_INTRA_EMPHASIS);
```
Comment (k-toyoda-pi) [inline pkg/kubectl/util/templates/normalizers.go]: I think ";" is not needed and markdown.go includes unnecessary spaces. run "go fmt" to both files.

Comment (YoubingLi) [reply pkg/kubectl/util/templates/normalizers.go]: All comments have been addressed in the new commit.

Thanks a lot.

**Comment by YoubingLi** [comment]
@k-toyoda-pi  @seans3 @ghodss
Please help review the latest code change.

Thanks
Youbing

File: pkg/kubectl/util/templates/normalizers.go (hunk 1 above)
Comment (k-toyoda-pi) [reply pkg/kubectl/util/templates/normalizers.go]: I have checked it. Looks good.

**Review by soltysh — APPROVED** [review]
/ok-to-test
/priority important-longterm
/lgtm
/approve
