### PR TITLE
Eliminate half-baked multi-architecture support

### LINKED ISSUE #33916: kubeadm deploys kube-proxy daemonsets for different architectures, but it doesn't work
Right now we create 3 daemonsets for `kube-proxy` in `app/master/addons.go`, but `images.GetCoreImage()` will only give use image names for `runtime.GOARCH`, so this feature is broken. We should only deploy one daemon set for the native architecture, but ensure it has the right label selectors, so we don't try to run `amd64` pods on nodes of different architecture. We should also make sure all addons have architecture labels, and not just `kube-proxy`. If user is building heterogeneous clusters, the will need to take about deploying addons for additional architectures, we shouldn't pre-deploy multiple things knowing that they will most likely remain unschedulable.

### PR DESCRIPTION
**Pull request by errordeveloper**
**What this PR does / why we need it**:

We have release `kubeadm` with half-baked support for clusters with nodes of different CPU architectures. The problem with the code as it stand is that user will notice pending daemonsets of `kube-proxy` for machines with architectures that they don't have. At the same time, the code as it stand did not pick up correct images for architectures it wanted to allow. Additionally, it only treated `kube-proxy` in such a way, but didn't do anything about `kube-dns`. This removes multiple daemonesets, but ensures that whichever resources we deploy have node affinity set to the architecture native to the master. Users wishing to use mixed architectures can still create extra daemonsets via the API.

**Which issue this PR fixes**: fixes #33916

**Release note**:

``` release-note
Remove support for multi-architecture code in `kubeadm`, which was released untested.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35124)

### CODE REVIEW

**Comment by pires** [comment]
@luxas you're the ARM ninja around, care to test?

File: cmd/kubeadm/app/master/apiclient.go [hunk 1]
```diff
@@ -223,6 +220,18 @@ func SetMasterNodeAffinity(meta *api.ObjectMeta) {
 	meta.Annotations[api.AffinityAnnotationKey] = string(affinityAnnotation)
 }
 
+func MasterNodeAffinity() api.NodeSelectorRequirement {
+	return api.NodeSelectorRequirement{
+		Key: "kubeadm.alpha.kubernetes.io/role", Operator: api.NodeSelectorOpIn, Values: []string{"master"},
+	}
+}
+
+func MonoArchitectureNodeAffinity() api.NodeSelectorRequirement {
```
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: The term "Mono" here makes me think of [Mono](http://www.mono-project.com/) and windows and such.  Perhaps just "ArchitectureNodeAffinity"?  If we add multi-arch support in the future we can rename/rework this.

File: cmd/kubeadm/app/master/apiclient.go [hunk 2]
```diff
@@ -206,14 +207,10 @@ func SetMasterTaintTolerations(meta *api.ObjectMeta) {
 	meta.Annotations[api.TolerationsAnnotationKey] = string(tolerationsAnnotation)
 }
 
-func SetMasterNodeAffinity(meta *api.ObjectMeta) {
+func SetNodeAffinity(meta *api.ObjectMeta, expr ...api.NodeSelectorRequirement) {
```
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: We don't have documentation on public functions here and we should probably start.  Can you start documenting some of this stuff as you touch it?

File: cmd/kubeadm/app/master/apiclient.go [hunk 3]
```diff
@@ -223,6 +220,18 @@ func SetMasterNodeAffinity(meta *api.ObjectMeta) {
 	meta.Annotations[api.AffinityAnnotationKey] = string(affinityAnnotation)
 }
 
+func MasterNodeAffinity() api.NodeSelectorRequirement {
```
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: Doc?

File: cmd/kubeadm/app/master/apiclient.go (hunk 1 above)
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: Doc?

**Review by jbeda — CHANGES_REQUESTED** [review]
Looks reasonable to me with some small nits.  Would love to get @luxas's take.

File: cmd/kubeadm/app/master/apiclient.go (hunk 1 above)
Comment (errordeveloper) [inline cmd/kubeadm/app/master/apiclient.go]: Haha, happy to rename. What about `NativeArchitectureNodeAffinity()`?

File: cmd/kubeadm/app/master/apiclient.go (hunk 2 above)
Comment (errordeveloper) [inline cmd/kubeadm/app/master/apiclient.go]: Ack.

File: cmd/kubeadm/app/master/apiclient.go (hunk 1 above)
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: `NativeArchitectureNodeAffinity` SGTM

**Comment by errordeveloper** [comment]
@jbeda I've addressed your comments and rebased.
