### PR TITLE
dualstack: use correct IPFamily list for conntrack checks in e2e

### LINKED ISSUE #96024: IPv6 Conntrack UDP NodePort kind tests failing
**Which jobs are failing**:
sig-network-kind-ipvs,dual,master
sig-network-kind-ipvs,IPv6,master

**Which test(s) are failing**:

- [ ] KubeProxy should set TCP CLOSE_WAIT timeout
- [ ] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort Service
- [x] KubeProxy should resorve connection reset issue (tracking in  #93281)

**Since when has it been failing**:
Oct 28 

**Testgrid link**:
- [sig-network-kind,ipvs,IPv6,master](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-ipvs-ipv6/1321817895239421952)
- [sig-network-kind-ipvs,dual,master
](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-ipvs-dual/1321794994394107904)

**Reason for failure**:
- Both appear to be failing on missing conntrack entries

ex. 
```test/e2e/network/kube_proxy.go:54
Oct 29 15:09:08.240: no conntrack entry for port 11302 on node fc00:f853:ccd:e793::2
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by cmluciano**
Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>

**What type of PR is this?**
/kind bug
/kind failing-test

**What this PR does / why we need it**:
We hardcode the index number in the KubeProxy/Conntrack e2es and
CollectAddresses returns 4 mixed IP Family addresses in a dualstack
cluster. This change ensures that the serverNodeInfo.nodeIP has only
valid addresses for the expected IPFamily per test case.

**Which issue(s) this PR fixes**:
Fixes: #96024

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
In addition to get the right IP family, I also think that we have to call https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/test/e2e/framework/node/resource.go#L252 instead of `CollectAddresses`

File: test/e2e/network/conntrack.go [hunk 1]
```diff
@@ -297,3 +304,22 @@ func dumpConntrack(cs clientset.Interface) {
...
+			}
+		}
+	}
+	if family == v1.IPv6Protocol {
+		for _, ip := range ips {
+			if netutil.IsIPv6String(ip) {
+				expectedIPs = append(expectedIPs, ip)
+			}
+		}
+	}
```
Comment (aojea) [inline test/e2e/network/conntrack.go:323]: I think this can be simplified to something like
```go
		for _, ip := range ips {
			if netutil.IsIPv6String(ip) == (family == v1.IPv6Protocol) {
				expectedIPs = append(expectedIPs, ip)
			}
		}
```

File: test/e2e/network/conntrack.go [hunk 2]
```diff
@@ -105,6 +106,12 @@ var _ = SIGDescribe("Conntrack", func() {
 
 		ips := e2enode.CollectAddresses(nodes, v1.NodeInternalIP)
 
+		if framework.TestContext.ClusterIsIPv6() {
```
Comment (aojea) [inline test/e2e/network/conntrack.go:109]: I think that it will be "more solid" if we create the node info independentyl 
https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/test/e2e/framework/node/resource.go#L252

```
                ips := e2enode.GetAddresses(nodes.Items[0], v1.NodeInternalIP)
		clientNodeInfo = nodeInfo{
			name:   nodes.Items[0].Name,
			nodeIP: ips[0],
		}

                ips = e2enode.GetAddresses(nodes.Items[1], v1.NodeInternalIP)
                
		serverNodeInfo = nodeInfo{
			name:   nodes.Items[1].Name,
			nodeIP: ips[0],
		}
```

Comment (cmluciano) [reply test/e2e/network/conntrack.go:109]: This is much simpler, I will change to this

File: test/e2e/network/conntrack.go [hunk 3]
```diff
@@ -103,16 +103,18 @@ var _ = SIGDescribe("Conntrack", func() {
...
 			name:   nodes.Items[0].Name,
 			nodeIP: ips[0],
 		}
 
+		ips = e2enode.GetAddresses(&nodes.Items[1], v1.NodeInternalIP)
+
 		serverNodeInfo = nodeInfo{
 			name:   nodes.Items[1].Name,
-			nodeIP: ips[1],
+			nodeIP: ips[0],
```
Comment (aojea) [inline test/e2e/network/conntrack.go:117]: we still need to be sure that the IP we choose correspond to the main IP family the cluster is using, `framework.TestContext.ClusterIsIPv6()`

Comment (cmluciano) [reply test/e2e/network/conntrack.go:117]: Is that necessary since we are doing a separate hardcoded check of GetAddresses? It works locally on a dualstack cluster.

Comment (aojea) [reply test/e2e/network/conntrack.go:117]: you don't control the order of the internalIP returned, and if the main family is IPv4 and the ip returned is IPv6 it will fail , actually is the reason why the tests fail today, it connects to an IPv4 service (by default services are SingleStack on the main family) but uses the IPv6 node address to connect to it ...

```

ï¿½[1mSTEPï¿½[0m: waiting up to 3m0s for service svc-udp in namespace conntrack-2577 to expose endpoints map[pod-server-1:[80]]
Nov  3 15:13:54.111: INFO: successfully validated that service svc-udp in namespace conntrack-2577 exposes endpoints map[pod-server-1:[80]]
ï¿½[1mSTEPï¿½[0m: checking client pod connected to the backend 1 on Node IP fc00:f853:ccd:e793::4
Nov  3 15:14:54.143: INFO: Pod client logs: Tue Nov  3 15:13:49 UTC 2020
Tue Nov  3 15:13:49 UTC 2020 Try: 1
```

Comment (cmluciano) [reply test/e2e/network/conntrack.go:117]: Ah ok, I thought it was just failing bc we also picked the 2nd entry which consistently ended up being the IPv6 address, but that makes sense now.

File: test/e2e/network/conntrack.go [hunk 4]
```diff
@@ -103,16 +104,25 @@ var _ = SIGDescribe("Conntrack", func() {
...
+		}
+
+		for _, ip := range e2enode.GetAddresses(&nodes.Items[1], v1.NodeInternalIP) {
```
Comment (aojea) [inline test/e2e/network/conntrack.go:121]: I think that we are almost there, but I feel that is better that we use the right ip for both clientNodeInfo and serverNodeInfo, maybe just do the assignment directly instead of modifying it later ?

File: test/e2e/framework/node/resource.go [hunk 5]
```diff
@@ -248,6 +249,27 @@ func GetInternalIP(node *v1.Node) (string, error) {
...
+		for j := range node.Status.Addresses {
+			nodeAddress := &node.Status.Addresses[j]
+			if nodeAddress.Type == addressType && nodeAddress.Address != "" && netutil.IsIPv6String(nodeAddress.Address) {
+				ips = append(ips, nodeAddress.Address)
+			}
+		}
+	} else {
+		for j := range node.Status.Addresses {
+			nodeAddress := &node.Status.Addresses[j]
+			if nodeAddress.Type == addressType && nodeAddress.Address != "" {
```
Comment (aojea) [inline test/e2e/framework/node/resource.go:265]:
```suggestion
			if nodeAddress.Type == addressType && nodeAddress.Address != "" && ! netutil.IsIPv6String(nodeAddress.Address) {
```

Comment (cmluciano) [reply test/e2e/framework/node/resource.go:265]: When I tried running the KubeProxy tests with this change locally, it failed on the TCP reconnect test job with the wrong IP on an IPV6 only cluster.

Comment (aojea) [reply test/e2e/framework/node/resource.go:265]: but ... how does this reach this place if `family == v1.IPv6Protocol`? 
maybe I'm missing something but it seems that we can ask for IPv4 addresses and receive IPv6 ones this way

Comment (cmluciano) [reply test/e2e/framework/node/resource.go:265]: I just retried with this change on a fresh IPV6-only cluster and the same result happened. I uploaded the test output [here](https://gist.github.com/cmluciano/68e33194b8d2d39aad606e76ca087b6a).

Comment (aojea) [reply test/e2e/framework/node/resource.go:265]: the test `KubeProxy should resolve connection reset issue` always fails with ipv6, is a problem with the image used for the test , I had a fix for that but the process to promote the new container image of the test is broken now :)
https://github.com/kubernetes/kubernetes/pull/95351

Comment (aojea) [reply test/e2e/framework/node/resource.go:265]: can you add the check to the PR so we can run it in the CI?
I think that is necessary to filter out IPv6 addresses if we ask for IPv4 only

Comment (cmluciano) [reply test/e2e/framework/node/resource.go:265]: Yes will do

**Comment by aojea** [comment]
/assign @MrHohn 
/assign @spiffxp 
This will fix the dual-stack jobs errors https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20dual,%20master

File: test/e2e/framework/node/resource.go [hunk 6]
```diff
@@ -248,6 +249,27 @@ func GetInternalIP(node *v1.Node) (string, error) {
 	return host, nil
 }
 
+// GetAddressesByFamily returns a list of addresses of the given addressType for the given node
+// and filtered by IPFamily
+func GetAddressesByFamily(node *v1.Node, addressType v1.NodeAddressType, family v1.IPFamily) (ips []string) {
+	if family == v1.IPv6Protocol {
+		for j := range node.Status.Addresses {
```
Comment (andrewsykim) [inline test/e2e/framework/node/resource.go:256]: This can be collapsed into a single loop:
```go
for _, ndoeAddress := range node.Status.Addresses {
    if nodeAddress.Type != addressType {
        continue
    }

    nodeAddress.Address == "" {
       continue
    } 

    if family == v1.IPv6Protocol && netutil.IsIPv6String(nodeAddress.Address) {
         ips = append(ips, nodeAddress.Address)
         continue
    }

     if if family == v1.IPv4Protocol && !netutil.IsIPv6String(nodeAddress.Address) {
         ips = append(ips, nodeAddress.Address)
         continue
    }

     // error here?
}
```

File: test/e2e/framework/node/resource.go [hunk 7]
```diff
@@ -248,6 +249,27 @@ func GetInternalIP(node *v1.Node) (string, error) {
 	return host, nil
 }
 
+// GetAddressesByFamily returns a list of addresses of the given addressType for the given node
+// and filtered by IPFamily
+func GetAddressesByFamily(node *v1.Node, addressType v1.NodeAddressType, family v1.IPFamily) (ips []string) {
```
Comment (andrewsykim) [inline test/e2e/framework/node/resource.go:254]: GetAddressByTypeAndFamily?

File: test/e2e/framework/node/resource.go [hunk 8]
```diff
@@ -20,6 +20,7 @@ import (
 	"context"
 	"encoding/json"
 	"fmt"
+	netutil "k8s.io/utils/net"
```
Comment (andrewsykim) [inline test/e2e/framework/node/resource.go:23]: I think most other import aliases for this package has been `utilnet`?

File: test/e2e/framework/node/resource.go (hunk 6 above)
Comment (cmluciano) [reply test/e2e/framework/node/resource.go:256]: I'm not sure if I understand why we would continue on the following

```
if nodeAddress.Type != addressType {
        continue
}

if nodeAddress.Address == "" {
       continue
} 
```

The code as written has these option reversed in order to add to the returned IP slice. I rewritten in the suggested style, wouldn't we want to break on those conditions instead?

File: test/e2e/framework/node/resource.go (hunk 8 above)
Comment (cmluciano) [reply test/e2e/framework/node/resource.go:23]: I have seen it a few different ways, but I'm happy to switch to this format since the majority seems to favor it.

```
cmluciano@starlord:~/go/src/k8s.io/kubernetes$ ack 'netutil "k8s.io/utils/net"'|wc -l
6
cmluciano@starlord:~/go/src/k8s.io/kubernetes$ ack 'netutils "k8s.io/utils/net"'|wc -l
14
cmluciano@starlord:~/go/src/k8s.io/kubernetes$ ack 'utilnet "k8s.io/utils/net"'|wc -l
42

```

Comment (andrewsykim) [reply test/e2e/framework/node/resource.go:23]: hmm okay, feel free to ignore then

File: test/e2e/framework/node/resource.go (hunk 6 above)
Comment (andrewsykim) [reply test/e2e/framework/node/resource.go:256]: `continue` because we skip adding IPs that either don't match the type or has an empty address. if we break then we don't check all node addresses after the first invalid one is found.

Comment (cmluciano) [reply test/e2e/framework/node/resource.go:256]: Ok that makes sense, will change

File: test/e2e/framework/node/resource.go [hunk 9]
```diff
@@ -248,6 +249,26 @@ func GetInternalIP(node *v1.Node) (string, error) {
 	return host, nil
 }
 
+// GetAddressesByTypeAndFamily returns a list of addresses of the given addressType for the given node
+// and filtered by IPFamily
+func GetAddressesByTypeAndFamily(node *v1.Node, addressType v1.NodeAddressType, family v1.IPFamily) (ips []string) {
```
Comment (andrewsykim) [inline test/e2e/framework/node/resource.go:254]: don't use named return here

**Review by andrewsykim — COMMENTED** [review]
/approve

(lgtm to @aojea)

**Comment by aojea** [comment]
/lgtm
thanks
