### PR TITLE
node: device-mgr: sample device plugin: Add support to control registration process

### LINKED ISSUE #109595: device manager can incorrectly recover devices on node restart
### What happened?

The following behaviour was reproduced on openshift 4.10 ("Kubelet version" kubeletVersion="v1.23.3+54654d2") but I believe the root cause is on kubernetes.

Let's consider a pod requiring resources, among them a device (point in case: dpdk network device)
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dpdk
  name: testpmd
  namespace: default
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: $DPKDK_IMAGE
      imagePullPolicy: Always
      name: dpdk
      resources:
        limits:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
        requests:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
```
the pods starts and run just fine up until the node is restarted. On restart, the device manager correctly recover its state from the checkpoint data:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.461850    2011 manager.go:247] "Starting Device Plugin manager"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.463809    2011 container_manager_linux.go:930] "Attempting to apply oom_score_adj to process" oomScoreAdj=-999 pid=2011
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464997    2011 oom_linux.go:66] attempting to set "/proc/2011/oom_score_adj" to "-999"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464269    2011 iptables.go:462] running iptables: ip6tables [-w 5 -W 100000 -N KUBE-POSTROUTING -t nat]
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.465254    2011 event.go:294] "Event occurred" object="TESTNODE" kind="Node" apiVersion="" type="Normal" reason="NodeAllocatableEnforced" message="Updated Node Allocatable limit across pods"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466379    2011 pod_devices.go:215] "Get checkpoint entry" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" containerName="dpdk" resourceName="openshift.io/dpdk_nic_1" deviceIDs=map[-1:[0000:00:05.0]] allocated="\n1\n!PCIDEVICE_OPENSHIFT_IO_DPDK_NIC_1\x12\f0000:00:05.0\x1a%\n\x0e/dev/vfio/vfio\x12\x0e/dev/vfio/vfio\x1a\x03mrw\x1a'\n\v/dev/vfio/0\x12\x13/dev/vfio/noiommu-0\x1a\x03mrw"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466823    2011 manager.go:289] "Serving device plugin registration server on socket" path="/var/lib/kubelet/device-plugins/kubelet.sock"
```
As expected, the device plugin capacity is set to zero until the device plugin correctly re-register itself:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.607362    2011 setters.go:344] "Updated capacity for device plugin" plugin="openshift.io/dpdk_nic_1" capacity=0`
```
A bit later, the recovery process from the apiserver begins:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193478    2011 config.go:278] "Setting pods for source" source="api"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193526    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-node-tuning-operator/tuned-tql4x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193541    2011 config.go:383] "Receiving a new pod" pod="openshift-sdn/sdn-fnls4"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193549    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/node-exporter-jzprg"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193557    2011 config.go:383] "Receiving a new pod" pod="openshift-ingress-canary/ingress-canary-62kq2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193565    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-87sbt"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193573    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/network-metrics-daemon-5qb5q"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193580    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/node-ca-frkhr"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193597    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193605    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193615    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193624    2011 config.go:383] "Receiving a new pod" pod="openshift-machine-config-operator/machine-config-daemon-nkqsq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193632    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/image-pruner-27496800-n4qzq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193640    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193649    2011 config.go:383] "Receiving a new pod" pod="openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193659    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-additional-cni-plugins-xwgkj"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193667    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/coredns-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193674    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/node-resolver-6n2vp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193682    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/keepalived-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193689    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/dns-default-cnlrl"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193695    2011 config.go:383] "Receiving a new pod" pod="default/testpmd"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193703    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193711    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-network-config-daemon-p94vm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193721    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-device-plugin-bw7rq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193728    2011 config.go:383] "Receiving a new pod" pod="openshift-network-diagnostics/network-check-target-2tbjs"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.195257    2011 kubelet.go:2106] "SyncLoop ADD" source="api" pods=[openshift-cluster-node-tuning-operator/tuned-tql4x openshift-sdn/sdn-fnls4 openshift-monitoring/node-exporter-jzprg openshift-ingress-canary/ingress-canary-62kq2 openshift-multus/multus-87sbt openshift-multus/network-metrics-daemon-5qb5q openshift-image-registry/node-ca-frkhr openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2 openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp openshift-machine-config-operator/machine-config-daemon-nkqsq openshift-image-registry/image-pruner-27496800-n4qzq openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6 openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x openshift-multus/multus-additional-cni-plugins-xwgkj openshift-openstack-infra/coredns-TESTNODE openshift-dns/node-resolver-6n2vp openshift-openstack-infra/keepalived-TESTNODE openshift-dns/dns-default-cnlrl default/testpmd openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm openshift-sriov-network-operator/sriov-network-config-daemon-p94vm openshift-sriov-network-operator/sriov-device-plugin-bw7rq openshift-network-diagnostics/network-check-target-2tbjs]
```
we can see already that the workload pod (testpmd) is going to be recovered BEFORE the device plugin. When the workload pod 
enters the admission flow (as per recovered pods), because the devicemanager restored its state and has data about this pod, we see:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204837    2011 topology_manager.go:200] "Topology Admit Handler"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204848    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204859    2011 topology_hints.go:49] "Resource does not have a topology preference" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204873    2011 scope_container.go:77] "TopologyHints" hints=map[openshift.io/dpdk_nic_1:[]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204880    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204928    2011 policy_static.go:437] "TopologyHints generated" pod="default/testpmd" containerName="dpdk" cpuHints=[{NUMANodeAffinity:01 Preferred:true}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204941    2011 scope_container.go:77] "TopologyHints" hints=map[cpu:[{NUMANodeAffinity:01 Preferred:true}]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204949    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204957    2011 scope_container.go:77] "TopologyHints" hints=map[] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204964    2011 policy.go:78] "Hint Provider has no preference for NUMA affinity with resource" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204971    2011 policy.go:70] "Hint Provider has no preference for NUMA affinity with any resource"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204979    2011 scope_container.go:85] "ContainerTopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true}
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204987    2011 scope_container.go:54] "Best TopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204995    2011 scope_container.go:59] "Topology Affinity" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205009    2011 manager.go:914] "Looking for needed resources" needed=1048576000 resourceName="memory"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205016    2011 manager.go:914] "Looking for needed resources" needed=1 resourceName="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205024    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205037    2011 manager.go:694] "Found pre-allocated devices for resource on pod" resourceName="openshift.io/dpdk_nic_1" containerName="dpdk" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" devices=[0000:00:05.0]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205044    2011 manager.go:914] "Looking for needed resources" needed=2 resourceName="cpu"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205050    2011 manager.go:914] "Looking for needed resources" needed=1073741824 resourceName="hugepages-1Gi"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205060    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
```
When the topology manager requests device allocation, we end up in the devicemanager's [devicesToAllocate](https://github.com/kubernetes/kubernetes/blob/v1.24.0-rc.0/pkg/kubelet/cm/devicemanager/manager.go#L686) function. This function checks if there already a pre-allocated device (and there is, thanks to the recovered data), and if so exits early, skipping the health check which would have failed, because the device plugin has not re-registered itself yet.

The end result is that containers can be admitted and start running without the requested device actually available, causing runtime errors in the workload.

### What did you expect to happen?

The kubelet should reject the admission of the pod until the device plugins re-registered themselves; then the pods requiring devices should be processed again. This seems the only meaningful way to recover pods while taking in consideration the actualy health of the devices.

### How can we reproduce it (as minimally and precisely as possible)?

The behaviour here depends on the order on which pods are recovered, so it's essentially a race.

1. run a test pod requiring devices. Make sure this test pod clearly fails if the requested devices are not available
2. restart the node (can take few attempts)
3. check the health of the test pod

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
kubelet 1.23.3
likely happening on current master
```
</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Update the sample device plugin to enable the e2e node tests (or any other entity with full access to the node filesystem) to control the registration process. We add a new environment variable `REGISTER_CONTROL_FILE`.
The value of this variable must be a file which prevents the plugin to register itself while it's present. Once removed, the plugin will go on and complete the registration. The plugin will automatically detect the parent directory on which the file resides and detect deletions, unblocking the registration process. If the file is specified but unaccessible, the plugin will fail. If the file is not specified, the registration process will progress as usual and never pause. The plugin will need read access to the parent directory.

This feature is useful because it is not possible to control the order in which the pods are recovered after node reboot/kubelet restart.

In this approach, the testing environment will create a directory and then a empty file to pause the registration process of the plugin. Once pointed to that file, the plugin will start and wait for it to be deleted. Only after the directory has been deleted, the plugin would proceed to registration.

This feature is used in https://github.com/kubernetes/kubernetes/pull/114640 where e2e test is implemented to simulate scenarios where application pods requesting devices come up before the device plugin pod on node reboot/ kubelet restart.

#### Which issue(s) this PR fixes:

Issue: #109595
#### Special notes for your reviewer:
This is a pre-requisite for e2e tests implemented in https://github.com/kubernetes/kubernetes/pull/114640.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/images/sample-device-plugin/sampledeviceplugin.go [hunk 1]
```diff
@@ -84,14 +91,54 @@ func main() {
...
+		autoRegister, err = strconv.ParseBool(autoRegisterString)
+		if err != nil {
+			klog.Errorf("invalid boolean value specified")
+			panic(err)
+		}
+
+	}
+
 	socketPath := pluginSocksDir + "/dp." + fmt.Sprintf("%d", time.Now().Unix())
+	triggerPath := pluginSocksDir + "/registered"
```
Comment (bart0sh) [inline test/images/sample-device-plugin/sampledeviceplugin.go:105]: This line can be moved down to the `if !autoRegister` block as it's used only there.

File: test/images/sample-device-plugin/sampledeviceplugin.go [hunk 2]
```diff
@@ -84,14 +91,54 @@ func main() {
...
+		go func(ln net.Listener, c chan os.Signal) {
+			sig := <-c
+			klog.Infof("Received termination signal %s: shutting down.", sig)
+			ln.Close()
+			os.Exit(0)
+		}(l, sigc)
+
+		klog.InfoS("Starting to accept connections")
+		// Accept new connections
+		conn, err := l.Accept()
```
Comment (bart0sh) [inline test/images/sample-device-plugin/sampledeviceplugin.go:133]: Would it make sense to use simpler synchronisation approach? For example sample device plugin would create a file and wait until it's deleted. e2e test would just delete that file to enable registration?

File: test/images/sample-device-plugin/sampledeviceplugin.go (hunk 1 above)
Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go:105]: Ack, Thanks!

File: test/images/sample-device-plugin/sampledeviceplugin.go (hunk 2 above)
Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go:133]: Sure, we can certainly use a file based synchronization approach. I used that in my initial experimentation but pivoted to using a unix socket because I thought it was cleaner. 

I will add additional commits and if you find the file based approach preferable we can get rid of the unix socket completely.

Comment (bart0sh) [reply test/images/sample-device-plugin/sampledeviceplugin.go:133]: It's up to you to decide. I just thought that creating special purpose unix socket in the same directory can confuse people. From other point of view creating file there can confuse them too.

Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go]: I don't feel too strongly either way :) Let's see if @ffromani or @klueska have a preference here.

Comment (ffromani) [reply test/images/sample-device-plugin/sampledeviceplugin.go]: no real preference for me. I _thought_ socket could be simpler but I have zero data to back my claim.

**Comment by swatisehgal** [comment]
/assign @pohly @aojea
for review/approval on test related changes

This PR is a pre-requisite to https://github.com/kubernetes/kubernetes/pull/114640.

**Review by bart0sh — COMMENTED** [review]
/lgtm

**Comment by bart0sh** [comment]
@swatisehgal Would it make sense to give more control of the registration delay to the test, i.e. the test would create a lock file and the plugin would just wait until the lock is deleted, if the lock exists?

**Comment by swatisehgal** [comment]
> @swatisehgal Would it make sense to give more control of the registration delay to the test, i.e. the test would create a lock file and the plugin would just wait until the lock is deleted, if the lock exists?

I prefer the approach we have right now where sample-device-plugin has more control. We control device plugin registration only for this rare test case with an environment variable. In all the other cases, the device plugin registers by default.

Changing to the way you are suggesting means that we rely on an external entity (e2e test here) to delete the lock file and iff the file has been deleted, device plugin registration can take place. What if we had a residual lock file from a bad test run? This could prevent device plugin registration for all cases where we expect device plugins to have registered normally which IMO is not ideal.

**Comment by bart0sh** [comment]
>  What if we had a residual lock file from a bad test run? This could prevent device plugin registration for all cases where we expect device plugins to have registered normally which IMO is not ideal.

We can not only check if lock file exists, but also if it's locked, e.g. with fcntl lock or any other locking mechanism.

This would allow us, among other things, to use the same yaml file `sample-device-plugin.yaml` for all test cases as far as I understand.

**Comment by swatisehgal** [comment]
> > What if we had a residual lock file from a bad test run? This could prevent device plugin registration for all cases where we expect device plugins to have registered normally which IMO is not ideal.
> 
> We can not only check if lock file exists, but also if it's locked, e.g. with fcntl lock or any other locking mechanism.
> 
> This would allow us, among other things, to use the same yaml file `sample-device-plugin.yaml` for all test cases as far as I understand.

Am I understanding this correctly that you are suggesting that the presence of the file itself (created by e2e) can be used as an indication that the device plugin registration needs to be stalled and that way we don't need an environment variable for preventing autoregistration?  I liked the fact that we were explicitly specifying the behavior we wanted out of sample device plugin (default behavior where we autoregister vs this rare case where AUTO_REGISTER environment variable is set to false) rather than an implicit assumption between e2e test and the device plugin.

I am sensing that you would like to optimize the way we are going about this. I don't have any major objections to further improvements and I tend to agree that there is room for improvement here.  However, every time we make updates to the sample device plugin implmenetation, e2e test implementation would require updates and further stall the [main PR](https://github.com/kubernetes/kubernetes/pull/114640) which has already become quiet large.

How do you feel about separating this optimization work as a separate PR?  I will think a bit more about this and we can focus specifically on this optimization once the bug fix lands in.

**Comment by bart0sh** [comment]
I'm ok with the current implementation. We can optimise it later on if we want.

File: test/images/sample-device-plugin/VERSION [hunk 3]
```diff
@@ -1 +1 @@
-1.4
+1.5
```
Comment (ffromani) [inline test/images/sample-device-plugin/VERSION:1]: let's fix the commit message:
```
Update the sample device plugin to enable the e2e node tests (or any other entity with full access to the node filesystem) to control the registration process. We add a new environment variable `REGISTER_CONTROL_FILE`.
The value of this variable must be a file which prevents the plugin to register itself while it's present. Once removed, the plugin will go on and complete the registration. The plugin will automatically detect the parent directory on which the file resides and detect deletions, unblocking the registration process. If the file is specified but unaccessible, the plugin will fail. If the file is not specified, the registration process will progress as usual and never pause. The plugin will need read access to the parent directory.

This feature is useful because it is not possible to control the order in which the pods are recovered after node reboot/kubelet restart.

In this approach, the testing environment will create a directory and then a empty file to pause the registration process of the plugin. Once pointed to that file, the plugin will start and wait for it to be deleted. Only after the directory has been deleted, the plugin would proceed to registration.

In the subsequent...
```

**Review by ffromani — COMMENTED** [review]
LGTM once the commit message is also updated to reflect the latest changes.

I'm suggesting some content, but feel free to rephrase or change as you see fit.

File: test/images/sample-device-plugin/VERSION (hunk 3 above)
Comment (swatisehgal) [reply test/images/sample-device-plugin/VERSION:1]: Thanks, will update now.

**Comment by ffromani** [comment]
/lgtm

thanks for addressing the comments and for all your work here. I think this will really help the e2e tests in the future.
I'm very happy we are making progress in the e2e area.

**Comment by ffromani** [comment]
/test pull-kubernetes-integration

unrelated apiserver test failure

**Comment by ffromani** [comment]
/test pull-kubernetes-e2e-gce

unrelated failure:
```Kubernetes e2e suite: [It] [sig-node] Pods Extended Pod TerminationGracePeriodSeconds is negative pod with negative grace period expand_more
```

**Comment by swatisehgal** [comment]
@pohly A gentle ping for review/approval. This is a subset of https://github.com/kubernetes/kubernetes/pull/114640 which you have already reviewed. Thanks!

**Review by pohly — APPROVED** [review]
/approve

**Comment by liggitt** [comment]
oh, I see https://github.com/kubernetes/kubernetes/issues/116241 is open to track resolving that
