### PR TITLE
Fix the `ResourceQuota` admission plugin does not respect ANY scope change 

### LINKED ISSUE #124436: Quota scopes cannot handle the transition case from one scope to another when the target object is updated.
### What happened?

I create 2 quotas with different scopes, one is Terminating, and the other is NotTerminating. I create a pod that belongs to NotTerminating, then update the pod's spec.activeDeadlineSeconds with 5, the pod should belong to Terminating. But the quota is not updated.

```shell
Every 2.0s: kubectl get pod,quota -A

NAMESPACE     NAME                          READY   STATUS    RESTARTS   AGE
default       pod/test-pod                  0/1     Pending   0          28s
kube-system   pod/coredns-58cd89f5d-wtpxv   0/1     Pending   0          5m45s

NAMESPACE   NAME                               AGE     REQUEST           LIMIT
default     resourcequota/not-terminating   5m16s   count/pods: 1/1
default     resourcequota/terminating          5m16s   count/pods: 0/1
```

### What did you expect to happen?

Quota scopes can handle the transition case from one scope to another when the target object is updated.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create 2 quotas.
  ```yaml
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: terminating
  spec:
    hard:
      count/pods: "1"
    scopes:
    - Terminating
  ---
  apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: not-terminating
  spec:
    hard:
      count/pods: "1"
    scopes:
    - NotTerminating
  ```
2. Create a pod which belongs to not-terminating
  ```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: test-pod
  spec:
   
    containers:
    - name: test
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
  ```
3. Update pod's spec.activeDeadlineSeconds with 5. the pods should belong to terminating
  ```shell
  kubectl patch pod test-pod -p '{"spec":{"activeDeadlineSeconds":5}}'
  ```
4. Get all quotas, you will see the terminating quota is not updated.
  ```shell
  kubectl get quota -A
  ```

### Anything else we need to know?

The root cause is, when the pod is updated, the delta is calculated based on the old object and the new object, it doesn't consider the scope change where the updated object belongs to, so the final delta is not correct.

In this case, the final delta is zero, so the terminating quota is not updated.

Related k/k code: 

https://github.com/kubernetes/kubernetes/blob/5a31a46d4bfe1fcf5962fa9cee23ff3148a094e3/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go#L495-L558

When I implement https://github.com/kubernetes/kubernetes/pull/124360, I found this issue.

### Kubernetes version

<details>

```console
(base) (⎈|local-up-cluster:N/A)➜  __testdata git:(kep-3751-quota-2) ✗ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.0-alpha.0.47+5a31a46d4bfe1f-dirty
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

https://github.com/kubernetes/enhancements/issues/986 promoted ResourceQuotaScopeSelectors to GA since 1.15. But it is not working as expected in ANY scope change case. 

Mannually tested with the following steps:

- 2 quotas are created, one for Terminating and one for NotTerminating
- test-pod without `activeDeadlineSeconds`
- test-pod-2 with `activeDeadlineSeconds` set to 5

**Without this fix:**

```
(base) ➜  kubernetes git:(master) ✗ sudo LOG_LEVEL=4 hack/local-up-cluster.sh
```

```
(base) ➜  kubernetes git:(master) ✗ kubectl create -f __testdata/quota/quota.yaml && sleep 5 && kubectl create -f __testdata/quota/pod.yaml && sleep 5 && kubectl patch pod test-pod -p '{"spec":{"activeDeadlineSeconds":5}}' && kubectl create -f __testdata/quota/pod2.yaml
resourcequota/terminating created
resourcequota/not-terminating created
pod/test-pod created
pod/test-pod patched
pod/test-pod-2 created

(base) ➜  ~ kubectl get quota -w
NAME          REQUEST   LIMIT   AGE
terminating                     0s
terminating   count/pods: 0/1           0s
not-terminating                             0s
not-terminating   count/pods: 0/1           0s
not-terminating   count/pods: 1/1           5s
terminating       count/pods: 1/1           10s
terminating       count/pods: 2/1           2m41s
not-terminating   count/pods: 0/1           2m41s
```

**With this fix:**

```
(base) ➜  kubernetes git:(fix-quota-scope) ✗ sudo LOG_LEVEL=4 hack/local-up-cluster.sh
```

```
(base) ➜  kubernetes git:(fix-quota-scope) ✗ kubectl create -f __testdata/quota/quota.yaml && sleep 5 && kubectl create -f __testdata/quota/pod.yaml && sleep 5 && kubectl patch pod test-pod -p '{"spec":{"activeDeadlineSeconds":5}}' && kubectl create -f __testdata/quota/pod2.yaml
resourcequota/terminating created
resourcequota/not-terminating created
pod/test-pod created
pod/test-pod patched
Error from server (Forbidden): error when creating "__testdata/quota/pod2.yaml": pods "test-pod-2" is forbidden: exceeded quota: terminating, requested: count/pods=1, used: count/pods=1, limited: count/pods=1

(base) ➜  ~ kubectl get quota -w
NAME          REQUEST   LIMIT   AGE
terminating                     0s
terminating   count/pods: 0/1           0s
not-terminating                             0s
not-terminating   count/pods: 0/1           0s
not-terminating   count/pods: 1/1           5s
terminating       count/pods: 1/1           10s
not-terminating   count/pods: 0/1           4m26s
^C%
```

#### Which issue(s) this PR fixes:

Fixes #124436

#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver: Fix a bug where the `ResourceQuota` admission plugin does not respect ANY scope change when a resource is being updated. i.e., to set/unset an existing pod's `terminationGracePeriodSeconds` field.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/986
```

### CODE REVIEW

**Comment by carlory** [comment]
Comparing the same e2e tests between the master branch and the patched branch. 

e2e tests take a long time to complete because the controller slowly update the status. I'm not sure whether it is expected.

```
(base) ➜  kubernetes git:(master) ✗ go run github.com/onsi/ginkgo/v2/ginkgo --focus "should verify ResourceQuota with terminating scopes through scope selectors" -v test/e2e -- -allowed-not-ready-nodes=-1  -num-nodes=0
...
[sig-api-machinery] ResourceQuota should verify ResourceQuota with terminating scopes through scope selectors. [sig-api-machinery]
/Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1349
  STEP: Creating a kubernetes client @ 02/10/25 15:26:29.753
  I0210 15:26:29.753361 75378 util.go:453] >>> kubeConfig: /var/run/kubernetes/admin.kubeconfig
  STEP: Building a namespace api object, basename scope-selectors @ 02/10/25 15:26:29.754
  STEP: Waiting for a default service account to be provisioned in namespace @ 02/10/25 15:26:29.772
  STEP: Waiting for kube-root-ca.crt to be provisioned in namespace @ 02/10/25 15:26:29.777
  STEP: Creating a ResourceQuota with terminating scope @ 02/10/25 15:26:29.778
  STEP: Ensuring ResourceQuota status is calculated @ 02/10/25 15:26:29.784
  STEP: Creating a ResourceQuota with not terminating scope @ 02/10/25 15:26:31.79
  STEP: Ensuring ResourceQuota status is calculated @ 02/10/25 15:26:31.799
  STEP: Creating a long running pod @ 02/10/25 15:26:33.805
  STEP: Ensuring resource quota with not terminating scope captures the pod usage @ 02/10/25 15:26:33.831
  STEP: Ensuring resource quota with terminating scope ignored the pod usage @ 02/10/25 15:26:35.839
  STEP: Updating the pod to have an active deadline @ 02/10/25 15:26:37.843
  STEP: Creating second terminating pod @ 02/10/25 15:26:37.854
  [FAILED] in [It] - /Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1420 @ 02/10/25 15:26:37.868
  STEP: dump namespace information after failure @ 02/10/25 15:26:37.868
  STEP: Collecting events from namespace "scope-selectors-939". @ 02/10/25 15:26:37.868
  STEP: Found 3 events. @ 02/10/25 15:26:37.874
  I0210 15:26:37.874110 75378 dump.go:53] At 0001-01-01 00:00:00 +0000 UTC - event for terminating-pod: { } FailedScheduling: no nodes available to schedule pods
  I0210 15:26:37.874130 75378 dump.go:53] At 0001-01-01 00:00:00 +0000 UTC - event for test-pod: { } FailedScheduling: no nodes available to schedule pods
  I0210 15:26:37.874142 75378 dump.go:53] At 0001-01-01 00:00:00 +0000 UTC - event for test-pod: { } FailedScheduling: no nodes available to schedule pods
  I0210 15:26:37.877779 75378 resource.go:168] POD              NODE  PHASE    GRACE  CONDITIONS
  I0210 15:26:37.877893 75378 resource.go:175] terminating-pod        Pending         [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2025-02-10 15:26:37 +0800 CST Unschedulable no nodes available to schedule pods}]
  I0210 15:26:37.877911 75378 resource.go:175] test-pod               Pending         [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2025-02-10 15:26:33 +0800 CST Unschedulable no nodes available to schedule pods}]
  I0210 15:26:37.877921 75378 resource.go:178]
  STEP: Destroying namespace "scope-selectors-939" for this suite. @ 02/10/25 15:26:37.879
• [FAILED] [8.133 seconds]
[sig-api-machinery] ResourceQuota [It] should verify ResourceQuota with terminating scopes through scope selectors. [sig-api-machinery]
/Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1349

  [FAILED] Expected an error, got nil
  In [It] at: /Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1420 @ 02/10/25 15:26:37.868
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[SynchronizedAfterSuite]
/Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/e2e.go:80
  I0210 15:26:37.918705 75378 suites.go:34] Running AfterSuite actions on node 1
[SynchronizedAfterSuite] PASSED [0.000 seconds]
------------------------------
[ReportAfterSuite] Kubernetes e2e suite report
/Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/e2e_test.go:157
[ReportAfterSuite] PASSED [0.000 seconds]
------------------------------

Summarizing 1 Failure:
  [FAIL] [sig-api-machinery] ResourceQuota [It] should verify ResourceQuota with terminating scopes through scope selectors. [sig-api-machinery]
  /Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1420

Ran 1 of 6679 Specs in 8.243 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 6678 Skipped
--- FAIL: TestE2E (8.33s)
FAIL

Ginkgo ran 1 suite in 27.284202958s

Test Suite Failed
exit status 1

(base) ➜  kubernetes git:(fix-quota-scope) ✗ go run github.com/onsi/ginkgo/v2/ginkgo --focus "should verify ResourceQuota with terminating scopes through scope selectors" -v test/e2e -- -allowed-not-ready-nodes=-1  -num-nodes=0
...
[sig-api-machinery] ResourceQuota should verify ResourceQuota with terminating scopes through scope selectors. [sig-api-machinery]
...
[ReportAfterSuite] Kubernetes e2e suite report
/Users/kiki/workspace/golang/src/k8s.io/kubernetes/test/e2e/e2e_test.go:157
[ReportAfterSuite] PASSED [0.000 seconds]
------------------------------

Ran 1 of 6679 Specs in 296.377 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 6678 Skipped
PASS

Ginkgo ran 1 suite in 5m19.794915334s
Test Suite Passed
```

**Comment by carlory** [comment]
/cc @deads2k @yliaog @sunnylovestiramisu @mattcary

cc @aojea, but I'm unsure whether kep is needed.

File: test/e2e/apimachinery/resource_quota.go [hunk 1]
```diff
@@ -1397,8 +1403,43 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Ensuring resource quota with not terminating scope ignored the pod usage")
+		usedResources[v1.ResourcePods] = resource.MustParse("0")
+		usedResources[v1.ResourceRequestsCPU] = resource.MustParse("0")
+		usedResources[v1.ResourceRequestsMemory] = resource.MustParse("0")
+		usedResources[v1.ResourceLimitsCPU] = resource.MustParse("0")
+		usedResources[v1.ResourceLimitsMemory] = resource.MustParse("0")
+		// FIXME: controller takes longer time to update the resource quota status than expected
+		err = waitForResourceQuotaWithTimeout(ctx, f.ClientSet, f.Namespace.Name, resourceQuotaNotTerminating.Name, usedResources, 5*time.Minute)
```
Comment (carlory) [inline test/e2e/apimachinery/resource_quota.go:1438]: The default timeout in e2e tests is [1 minute](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/resource_quota.go\#L63), but the actual time it takes for a resource quota update to occur can be longer than that. i.e., the period for syncing quota usage status is [5 minutes by default](https//github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/config/v1alpha1/defaults.go\#L41). 

Should I update the default timeout in e2e tests to 5 minutes? or is there a better way to handle this?

Comment (carlory) [reply test/e2e/apimachinery/resource_quota.go]: It is resolved in the https://github.com/kubernetes/kubernetes/pull/130060/commits/6ea714fb02b9cd842b72f3e38513a3f94fe48ce4

**Comment by sunnylovestiramisu** [comment]
The original KEP does not have too much details, it does not talk about Scope change but it seems like a bug. Does a bug fix need a KEP as well?

**Review by hashim21223445 — APPROVED** [review]

File: staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go [hunk 2]
```diff
@@ -492,16 +492,26 @@ func CheckRequest(quotas []corev1.ResourceQuota, a admission.Attributes, evaluat
...
+	if negativeUsage := quota.IsNegative(inputUsage); len(negativeUsage) > 0 {
 		return nil, admission.NewForbidden(a, fmt.Errorf("quota usage is negative for resource(s): %s", prettyPrintResourceNames(negativeUsage)))
 	}
 
+	// initialize a map of delta usage for each interesting quota index.
+	deltaUsageIndexMap := make(map[int]corev1.ResourceList, len(interestingQuotaIndexes))
+	for _, index := range interestingQuotaIndexes {
+		deltaUsageIndexMap[index] = inputUsage
+	}
+	var deltaUsageWhenNoInterestingQuota corev1.ResourceList
```
Comment (sunnylovestiramisu) [inline staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:510]: Will there be any race condition if the user changed the quota and scope quickly twice in a roll?

**Comment by deads2k** [comment]
Looking at these lines here: https://github.com/kubernetes/kubernetes/blob/7aea7ccb8885cdc96d48af52bd184f87c8634d66/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go#L451-L466

If the inputObject is in scope/Terminating, then how will the evaluator for scope/NonTerminating  know to evaluate the and have a negative delta?

I think I've created a unit test demonstrated the phenomenon here: https://github.com/carlory/kubernetes/pull/1.  I can run it locally, but it break back-reference rules, so it needs updating to be merged as a unit test later.

**Comment by cici37** [comment]
/triage accepted

/sig scheduling 
Tag since the original KEP owned by sig scheduling previous.

File: staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go (hunk 2 above)
Comment (carlory) [reply staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:510]: @sunnylovestiramisu The plugin will recheck the request if it fails to update the quota.

**Comment by carlory** [comment]
> I bet this doesn't obey back-reference compilation rules, but I think it demonstrates that when transitioning from non-terminating to terminating, the non-terminating quota is not recovered.

@deads2k  The quota controller in KCM is responsible for reconciling non-terminating quota. The admission plugin does not apply negative deltas to the quota. 

FYI @liggitt's comment on https://github.com/kubernetes/kubernetes/pull/122701

> That said, I don't think it's correct to allow negative deltas in a request like this, since admission can complete but persistence in etcd can fail. That would allow a request to decrement quota without actually reducing use. Quota admission is intended to fail "high" in that case, and depends on a controller reconciling actual persisted use to lower / free the reserved quota.

File: staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller_test.go [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+					false,
+					nil,
+				),
+				evaluator: podEvaluator,
+				limited:   nil,
+			},
+			want: []corev1.ResourceQuota{
+				*newScopedQuota("foo", "terminating", corev1.ResourceQuotaScopeTerminating, 2),
+				*newScopedQuota("foo", "nonterminating", corev1.ResourceQuotaScopeNotTerminating, 0),
+			},
```
Comment (carlory) [inline staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller_test.go:152]: According to https://github.com/kubernetes/kubernetes/pull/130060#issuecomment-2667389066, I think the expected value of nonterminating should be 1, not 0.

Comment (carlory) [reply staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller_test.go:152]: reverted.
```
ERROR: "k8s.io/apiserver/pkg/admission/plugin/resourcequota ((tests:resourcequota))" -> "k8s.io/kubernetes/pkg/quota/v1/evaluator/core" is forbidden by /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/.import-restrictions
exit status 1
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-import-boss.sh	276s
```

Comment (carlory) [reply staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller_test.go]: Add new unit test in https://github.com/kubernetes/kubernetes/pull/130060/commits/963b13aaa662346ae96b575eaa31d3dfcc1de212

**Review by hashim21223445 — APPROVED** [review]

File: plugin/pkg/admission/resourcequota/admission_test.go [hunk 4]
```diff
@@ -860,6 +860,124 @@ func TestAdmitBelowTerminatingQuotaLimit(t *testing.T) {
 	}
 }
 
+// TestAdmitBelowTerminatingQuotaLimitWhenPodScopeUpdated ensures that terminating pods are charged to the right quota.
+// It creates a terminating and non-terminating quota, and changes an existing pod to be terminating.
+// It ensures that the terminating quota is incremented, and the non-terminating quota is not.
```
Comment (deads2k) [inline plugin/pkg/admission/resourcequota/admission_test.go:865]: Add the explanation of why we do this (always overcount if something something later causes the request to be rejected so you cannot reduce quota with requests that aren't completed).

Comment (carlory) [reply plugin/pkg/admission/resourcequota/admission_test.go:865]: added.
