### PR TITLE
Set default value for TEST_CLUSTER_LOG_LEVEL and KUBE_GCE_INSTANCE_PREFIX

### LINKED ISSUE #85507: start-kubemark.sh fails with unbound variable
**What happened**:
Run `test/kubemark/start-kubemark.sh`, will get error:

`k8s.io/kubernetes/test/kubemark/gce/../../../cluster/kubemark/gce/config-default.sh: line 32: TEST_CLUSTER_LOG_LEVEL: unbound variable`

Try to fix this by `export TEST_CLUSTER_LOG_LEVEL=--v=4` and rerun get another error:

`k8s.io/kubernetes/test/kubemark/gce/util.sh: line 45: KUBE_GCE_INSTANCE_PREFIX: unbound variable`

Basically, we should have default value for `TEST_CLUSTER_LOG_LEVEL` and `KUBE_GCE_INSTANCE_PREFIX`. I found that they have default values before, and was deleted accidentally in #78246. Although we can predefine these two variables before running the script, it will be more convenient to have default values, and more friendly to people who are not familiar with this script.

**What you expected to happen**:
We should be able to run `test/kubemark/start-kubemark.sh` without setting any environment variable manually.

**How to reproduce it (as minimally and precisely as possible)**:
`test/kubemark/start-kubemark.sh`

/cc @wojtek-t @mm4tt @mborsz
/sig testing
/sig cluster-lifecycle
/assign

### PR DESCRIPTION
**Pull request by notpad**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Set default value for variable `TEST_CLUSTER_LOG_LEVEL` and `KUBE_GCE_INSTANCE_PREFIX`, so that we can run `test/kubemark/start-kubemark.sh` directly without predefining these two variables.

**Which issue(s) this PR fixes**:

Fixes #85507 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig testing
/sig cluster-lifecycle

### CODE REVIEW

File: cluster/kubemark/gce/config-default.sh [hunk 1]
```diff
@@ -24,6 +24,8 @@
 source "${KUBE_ROOT}/cluster/gce/config-common.sh"
 
 CLEANUP_KUBEMARK_IMAGE=${CLEANUP_KUBEMARK_IMAGE:-true}
+TEST_CLUSTER_LOG_LEVEL="${TEST_CLUSTER_LOG_LEVEL:-"--v=4"}"
+KUBE_GCE_INSTANCE_PREFIX="${KUBE_GCE_INSTANCE_PREFIX:-"default"}"
```
Comment (mm4tt) [inline cluster/kubemark/gce/config-default.sh]: While the TEST_CLUSTER_LOG_LEVEL totally make sense, I'm not sure about this one.

KUBE_GCE_INSTANCE_PREFIX serves as kind of obligatory parameter that should be set by user. It allows you to set the "name" of the cluster, in a way that if you set a different names for two different start-kubemark.sh invocations, you'll get two different kubemark clusters, while if the name is the same the second call would most likely fail.

If we set the default for it, we should at least document that if you want to set up two kubemark clusters with different "names" you should change this env per each start-kubemark.sh invocation.

Comment (notpad) [reply cluster/kubemark/gce/config-default.sh]: Thanks, you are right. I've added the document.

PS: Previously, the name was defined by 

> INSTANCE_PREFIX="${INSTANCE_PREFIX:-"default"}"
MASTER_NAME="${INSTANCE_PREFIX}-kubemark-master"

**Comment by mm4tt** [comment]
There is no need to assign it further, I already approved it but in won't merge in 1.17 (it's not a critical bug fix). 
It will merge once the code freeze is lifted.

**Comment by notpad** [comment]
I see. Thanks!

**Comment by notpad** [comment]
> There is no need to assign it further, I already approved it but in won't merge in 1.17 (it's not a critical bug fix).
> It will merge once the code freeze is lifted.

@mm4tt When will the code freeze end? I think this PR doesn't have lgtm and approve label yet.

**Comment by mm4tt** [comment]
Sorry, I thought I already approved this. I must have mistaken this PR with one of others of yours

/lgtm
/approve
