### PR TITLE
selinux: add a new SELinux translator to the controller

### LINKED ISSUE #130036: SELinux controller does not work when KCM runs in a container
### What happened?

When KCM runs in a container (such as in a kops cluster), the SELinuxWarning controller does not do anything, because it thinks that SELinux is disabled - it reads /etc/selinux and /sys/fs/selinux to detect so here:
https://github.com/kubernetes/kubernetes/blob/20b12ad5c389ff74792988bf1e0c10fe2820d9a1/pkg/volume/util/selinux.go#L109

As result, it does not emit useful warnings.

### What did you expect to happen?

The controller emits events, regardless if it can access /etc or /sys on the host. The controller must be explicitly enabled, so it can expect that someone who enabled it also enabled SELinux on nodes.

### How can we reproduce it (as minimally and precisely as possible)?

Run KCM with `--controllers=*,selinux-warning-controller --feature-gates=SELinuxChangePolicy=true,SELinuxMount=true` and create 2 pods that use the same volume, but each Pod has different `seLinuxOptions`.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
Today's master
```console
v1.33.0-alpha.0.569+834719d46dabe1-dirty
```
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>
```console
PRETTY_NAME="Fedora Linux 41 (Cloud Edition)"
```
</details>

### Install tools

<details>
kops
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind feature

Fixes: #130036
#### What this PR does / why we need it:
KCM cannot read host's `/etc/selinux` to read the defaults, because it often runs as in a container with no access to host's `/etc` or `/sys`.  Therefore implement a custom `SELinuxOptionsToFileLabel` that does not default fields in SELinuxOptions and uses just fields provided by the Pod.

Since the controller cannot default empty SELinux label components, treat them as incomparable.
Example: "system_u:system_r:container_t:s0:c1,c2" *does not* conflict with ":::s0:c1,c2", because the node that will run such a Pod may expand "":::s0:c1,c2" to "system_u:system_r:container_t:s0:c1,c2".
However, "system_u:system_r:container_t:s0:c1,c2" *does* conflict with ":::s0:c98,c99".

#### Does this PR introduce a user-facing change?
```release-note
Fixed SELinuxWarningController defaults when running kube-controller-manager in a container.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1710
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
pull-kubernetes-e2e-kind-ipv6 job did not even start ?!

**Comment by carlory** [comment]
retry due to OutOfpods
/test pull-kubernetes-e2e-kind-ipv6

File: pkg/controller/volume/selinuxwarning/translator/selinux_translator_test.go [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+}
+
+func TestLabelsConflict(t *testing.T) {
+	tests := []struct {
+		name     string
+		a, b     string
+		conflict bool
+	}{
+		{
+			name:     "empty strings",
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/translator/selinux_translator_test.go:90]: Can we label these tests with which tests are incomparable, which tests are comparable but don't conflict. This will make reading these tests easier in future.

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go [hunk 2]
```diff
@@ -117,7 +120,7 @@ func NewController(
 				Name: "selinux_warning",
 			},
 		),
-		labelCache: volumecache.NewVolumeLabelCache(),
+		labelCache: volumecache.NewVolumeLabelCache(seLinuxTranslator),
 	}
 
 	err := c.vpm.InitPlugins(plugins, prober, c)
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:126]: Not visible in this PR, but in following code: 

```
	conflictCh := make(chan cache.Conflict)
	go func() {
		c.cache.SendConflicts(c.logger, conflictCh)
		close(conflictCh)
	}()
```

Is there any value in using channel for reading conflicts from cache? It appears to me, those can be read synchronously...

**Comment by gnufied** [comment]
Do we consider metrics as something privileged or not? One concern I have is, anyone who has access to KCM metrics can view, which selinux label it should use, in order to gain access to the volume from different namespace. For events, IIRC - we decided not to emit events with full details if pods are on different namespace. But for metrics, we are emitting metrics with full details (which could be a problem).

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go (hunk 2 above)
Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:126]: The cache does not have list of conflict ready in the format that metrics need it. I found it  better to structure the cache to react to new / deleted Pods quickly than cache all conflicts.
I'd optimize later, if it's necessary.

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:126]: And the main reason was to avoiding allocation of array of conflicts of unknown size. For large nr. of conflicts, it would need to be extended several times just to discard it after the call.

**Comment by jsafrane** [comment]
> Do we consider metrics as something privileged or not? [...] we are emitting metrics with full details (which could be a problem).

Good point. This PR does not change anything in the metric labels and their sensitivity, I filed https://github.com/kubernetes/kubernetes/issues/130215 to continue this discussion

File: pkg/controller/volume/selinuxwarning/translator/selinux_translator_test.go (hunk 1 above)
Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/translator/selinux_translator_test.go]: updated the test names, PTAL
