### PR TITLE
Fix setNodeAddress when a node IP and a cloud provider are set

### LINKED ISSUE #48760: No InternalIP when upgrading to kubernetes >= 1.6.5 with VSphere Cloud Provider
**BUG REPORT**:

/kind bug

**What happened**:
After upgrading the kubernetes cluster from 1.6.4 with the VSphere Cloud Provider enabled to 1.6.5/1.6.6 or 1.6.7, the cluster nodes don't have anymore InternalIPs

```
# kubectl get node debug.k8s.debug-01 -o yaml
...
status:
  addresses:
  - address: 10.9.65.204
    type: ExternalIP
  - address: debug.k8s.debug-01
    type: Hostname
...
```

Several issues occur at this step.
For example, it breaks heapster with such an error :
```
E0711 12:59:05.000192       1 kubelet.go:282] Node debug.k8s.debug-01 has no valid hostname and/or IP address: debug.k8s.debug-01
```
**What you expected to happen**:
The node should have an InternalIP.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a 1 node kubernetes cluster in a VM, and enable the _vsphere_ cloud provider.

**Anything else we need to know?**:
with kubernetes 1.6.4 we get :
```
status:
  addresses:
  - address: 10.9.65.204
    type: InternalIP
  - address: debug.k8s.debug-01
    type: Hostname
```
Downgrading to 1.6.4 fixes the issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7+coreos.0", GitCommit:"c8c505ee26ac3ab4d1dff506c46bc5538bc66733", GitTreeState:"clean", BuildDate:"2017-07-06T17:38:33Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux debug.k8s.debug-01 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```
- Install tools:
- Others: It may be related to some changes around PR kubernetes#45201

@kubernetes/sig-cluster-ops-bugs @kubernetes/sig-network-bugs
/area platform/vsphere cloudprovider

### PR DESCRIPTION
**Pull request by cbonte**
**What this PR does / why we need it**:
When a node IP is set and a cloud provider returns the same address with
several types, only the first address was accepted. With the changes made
in PR #45201, the vSphere cloud provider returned the ExternalIP first,
which led to a node without any InternalIP.

The behaviour is modified to return all the address types for the
specified node IP.

**Which issue this PR fixes**: fixes #48760

**Special notes for your reviewer**:
* I'm not a golang expert, is it possible to mock `kubelet.validateNodeIP()` to avoid the need of real host interface addresses in the test ?
* It would be great to have it backported for a next 1.6.8 release.

**Release note**:
```release-note
Fix for Nodes in vSphere lacking an InternalIP. (#48760)
```

### CODE REVIEW

**Comment by cbonte** [comment]
PR has been rebased according to current master branch.

**Comment by jhorwit2** [comment]
Does this issue also occur in the cloud controller manager?

**Comment by jhorwit2** [comment]
cc @wlan0 @luxas

**Comment by wlan0** [comment]
@cbonte Thanks for the PR.

It LGTM, except for the part where host IP addresses are used. 

> I'm not a golang expert, is it possible to mock kubelet.validateNodeIP() to avoid the need of real host interface addresses in the test ? 

I don't think there is a simple answer to this. You could "inject" a interface here - https://github.com/cbonte/kubernetes/blob/25767ae38906ca7dc00c6c6a2935de583c12eaa5/pkg/kubelet/kubelet.go#L846

and in the test, while creating the kubelet object (newTestKubelet method), pass a mock struct to that interface. This is quite a bit of refactoring! 

Tbh, I'm not entirely sure that relying on the host IP addresses is a bad idea. If that is ok, then we don't need any of this refactoring, and the current tests will suffice.

@luxas what would you suggest?

**Comment by cbonte** [comment]
> Tbh, I'm not entirely sure that relying on the host IP addresses is a bad idea. If that is ok, then we don't need any of this refactoring, and the current tests will suffice.

I tend to agree.

Note : I'm currently rebasing the PR again, as some changes since yesterday introduce new conflicts.

**Comment by cbonte** [comment]
ping @luxas @Random-Liu @euank

File: pkg/kubelet/kubelet_node_status.go [hunk 1]
```diff
@@ -469,15 +469,17 @@ func (kl *Kubelet) setNodeAddress(node *v1.Node) error {
...
-					node.Status.Addresses = []v1.NodeAddress{
-						{Type: nodeAddress.Type, Address: nodeAddress.Address},
-						{Type: v1.NodeHostName, Address: kl.GetHostname()},
-					}
-					return nil
+					enforcedNodeAddresses = append(enforcedNodeAddresses, v1.NodeAddress{Type: nodeAddress.Type, Address: nodeAddress.Address})
 				}
 			}
+			if len(enforcedNodeAddresses) > 0 {
+				enforcedNodeAddresses = append(enforcedNodeAddresses, v1.NodeAddress{Type: v1.NodeHostName, Address: kl.GetHostname()})
```
Comment (liggitt) [inline pkg/kubelet/kubelet_node_status.go]: this is preexisting, but while we're here, nothing would prevent a cloud provider from returning the IP as a type Hostname as well... if we double-set the hostname type, the update will fail.

Comment (cbonte) [reply pkg/kubelet/kubelet_node_status.go]: Right, I didn't want to change this part, as this is how it used to work previously.
I can update the PR to only add a `NodeHostName` address if none is already defined or I can create a new PR specifically for this change, once this one is approved and applied.
@liggitt What do you prefer ?

**Comment by luxas** [comment]
@calebamiles Why remove the v1.8 milestone for this _bug_ in the ccm?

File: pkg/kubelet/kubelet_node_status.go (hunk 1 above)
Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: Separate PR is fine

**Comment by luxas** [comment]
@jdumars @calebamiles May I re-add the v1.8 milestone for this bug fix?

**Comment by calebamiles** [comment]
@luxas, sorry this was a bulk remove from the milestone since the PR was unmergable at the time of code freeze (missing either, lgtm, or approve, or had test failures). Added the PR back to the milestone but the PR itself is still unmergable

**Comment by liggitt** [comment]
flake on #50695 
/test pull-kubernetes-e2e-gce-etcd3

**Comment by dims** [comment]
@Random-Liu @vishh @tallclair @dchen1107 - Can one of you please approve?

**Review by cheftako — APPROVED** [review]
/lgtm

File: pkg/kubelet/kubelet_node_status_test.go [hunk 2]
```diff
@@ -127,6 +129,85 @@ func (lcm *localCM) GetCapacity() v1.ResourceList {
...
+	defer testKubelet.Cleanup()
+	kubelet := testKubelet.kubelet
+	kubelet.hostname = testKubeletHostname
+
+	existingNode := v1.Node{
+		ObjectMeta: metav1.ObjectMeta{Name: testKubeletHostname, Annotations: make(map[string]string)},
+		Spec:       v1.NodeSpec{},
+	}
+
+	// TODO : is it possible to mock kubelet.validateNodeIP() to avoid relying on the host interface addresses ?
```
Comment (yujuhong) [inline pkg/kubelet/kubelet_node_status_test.go]: I looked at `validateNodeIP()` and there is nothing to prevent it from being a standalone function. I think that'd make testing much easier.

**Comment by cbonte** [comment]
Hi @yujuhong, is it possible to make this PR as a cherry-pick candidate for release-1.6 ?
Thanks !

**Comment by yujuhong** [comment]
@cbonte you can submit a cherrypick PR.
