### PR TITLE
kubeadm init: skip checking cri socket in preflight checks

### LINKED ISSUE #657: Installing crictl requires use of --ignore-preflight-errors=cri
## Versions
kubeadm version: v1.9.1
kubectl version: v1.9.1
Centos 7.4 w/ kernel: 3.10.0-693.11.6.el7.x86_64

## What happened?
If running kubeadm init without crictl being in the system path you get the expected warning of:
`[WARNING FileExisting-crictl]: crictl not found in system path` but the process continues as normal.

However if you have got crictl in your system path, kubeadm init will fail on this output:
`[ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1` which means you need to provide --ignore-preflight-errors=cri and then the init will work as expected.

The same behaviour occurs when running kubeadm join on a node.

## What you expected to happen?
To have the join/init process to work the same way regardless of the presence of crictl. 

## How to reproduce it (as minimally and precisely as possible)?
* Try to run kubeadm init on a server without crictl in $PATH
* Try to run kubeadm init on a server with crictl in $PATH

## Anything else we need to know?
The issue seems to be related to the fact that the dockershim.sock file is created by the kubelet service but, unless I'm missing something, this can't be started without having run kubeadm init/join in the first place.

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
`kubeadm init` does not need to require `dockershim.sock` to be present.
Remove the check for `dockershim.sock`.
xref #55055

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#657

**Special notes for your reviewer**:
/area kubeadm
/kind bug
/assign @luxas 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 

**Release note**:

```release-note
kubeadm init: skip checking cri socket in preflight checks
```

### CODE REVIEW

File: cmd/kubeadm/app/preflight/checks.go [hunk 1]
```diff
@@ -98,7 +98,12 @@ func (CRICheck) Name() string {
 
 // Check validates the container runtime through the CRI.
 func (criCheck CRICheck) Check() (warnings, errors []error) {
-	if err := criCheck.exec.Command("sh", "-c", fmt.Sprintf("crictl -r %s info", criCheck.socket)).Run(); err != nil {
+	crictlPath, err := criCheck.exec.LookPath("crictl")
```
Comment (jamiehannaford) [inline cmd/kubeadm/app/preflight/checks.go]: how do you feel about putting this in a single function?

**Review by jamiehannaford — COMMENTED** [review]
generally looks good, just 1 question

**Comment by imcsk8** [comment]
LGTM

File: cmd/kubeadm/app/preflight/checks.go (hunk 1 above)
Comment (dixudx) [reply cmd/kubeadm/app/preflight/checks.go]: That would be tedious IMO. LOCs will not get changed. WDYT? @jamiehannaford

**Review by jamiehannaford — APPROVED** [review]

**Comment by dixudx** [comment]
Rebased. ping @luxas @fabriziopandini @jamiehannaford PTAL. Thanks.

File: cmd/kubeadm/app/preflight/checks.go [hunk 2]
```diff
@@ -99,7 +99,12 @@ func (CRICheck) Name() string {
...
+	if err != nil {
+		errors = append(errors, fmt.Errorf("unable to find command crictl: %s", err))
+		return warnings, errors
+	}
+	if err := criCheck.exec.Command("sh", "-c", fmt.Sprintf("%s -r %s info", crictlPath, criCheck.socket)).Run(); err != nil {
```
Comment (kad) [inline cmd/kubeadm/app/preflight/checks.go]: Why we have here execution via "sh -c ... " ?
criCheck.socket is practically unverified user input, meaning, any shell expansion/functions will be executed silently by kubeadm.

Comment (errordeveloper) [reply cmd/kubeadm/app/preflight/checks.go]: Well spotted! I think this is an existing bug that just carried along. Now is a good time to also review other uses of `sh -c` in preflight checks.

**Review by kad — CHANGES_REQUESTED** [review]
Let's fix here "sh -c" as well, if we are touching that line of code.

**Comment by dixudx** [comment]
@kad @fabriziopandini Addressed the comments. PTAL. Thanks.

**Comment by kad** [comment]
@dixudx please check test failures. this seems to be real.

**Comment by dixudx** [comment]
ping @kad @fabriziopandini  @luxas Updated. PTAL. Thanks.

**Review by runcom — APPROVED** [review]
LGTM

**Review by timothysc — APPROVED** [review]
/approve - Thx @dixudx 
/lgtm

**Comment by MikeSpreitzer** [comment]
This was an incomplete fix.  There were _two_ lists of checkers, and CRICheck was removed from only one of them --- but should have been removed from both.  Then #62481 unified the common elements, and included CRICheck in the common list --- which was a mistake.

**Comment by luxas** [comment]
@dixudx please fix ^

**Comment by dixudx** [comment]
@luxas Already sent out #63907 to back port release-1.10. PTAL.
