### PR TITLE
Kubelet config sources should use the provided hostname, not lookup os.Hostname()

### LINKED ISSUE #5757: hack/test-integration.sh fails on Mac with mirror pod error
hack/test-integration.sh started failing recently.  Is this dependent on fsnotify function that is not implemented on a Mac?

```
I0321 12:21:23.799994   89865 integration.go:516] Done update (a, z)
I0321 12:21:23.802459   89865 integration.go:528] Atomic PUTs work.
F0321 12:21:24.707694   89865 integration.go:325] FAILED: mirror pod has not been created or is not running: pods "static-pod-Claytons-MacBook-Pro.local" not found
!!! Error in hack/test-integration.sh:33
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=2 --apiVersion="$1"' exited with status 255
Call stack:
  1: hack/test-integration.sh:33 runTests(...)
  2: hack/test-integration.sh:53 main(...)
Exiting with status 1
+++ Integration test cleanup complete
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Also fix race conditions on status sync loops which can result in sporadic failures.

Fixes #5757

### CODE REVIEW

**Comment by smarterclayton** [comment]
Yuck, lots of code using os.Hostname()...

**Comment by smarterclayton** [comment]
I've cleaned up pkg/kubelet/config/* to not use os.Hostname() and instead take the Kubelets hostname as an argument.

File: cmd/integration/integration.go [hunk 1]
```diff
@@ -205,7 +205,7 @@ func startComponents(manifestURL, apiVersion string) (string, string) {
 	scheduler.New(schedulerConfig).Run()
 
 	endpoints := service.NewEndpointController(cl)
-	go util.Forever(func() { endpoints.SyncServiceEndpoints() }, time.Second*10)
+	go util.Forever(func() { endpoints.SyncServiceEndpoints() }, time.Second*4)
```
Comment (wojtek-t) [inline cmd/integration/integration.go]: nit: Can you add some comment why do you set to 4 seconds (and why 10 seconds is too long?)

File: cmd/integration/integration.go [hunk 2]
```diff
@@ -222,13 +222,17 @@ func startComponents(manifestURL, apiVersion string) (string, string) {
 	testRootDir := makeTempDirOrDie("kubelet_integ_1.", "")
 	configFilePath := makeTempDirOrDie("config", testRootDir)
 	glog.Infof("Using %s as root dir for kubelet #1", testRootDir)
-	kubeletapp.SimpleRunKubelet(cl, &fakeDocker1, machineList[0], testRootDir, manifestURL, "127.0.0.1", 10250, api.NamespaceDefault, empty_dir.ProbeVolumePlugins(), nil, cadvisorInterface, configFilePath)
+	kcfg := kubeletapp.SimpleKubelet(cl, &fakeDocker1, machineList[0], testRootDir, manifestURL, "127.0.0.1", 10250, api.NamespaceDefault, empty_dir.ProbeVolumePlugins(), nil, cadvisorInterface, configFilePath)
+	kcfg.PodStatusUpdateFrequency = 1 * time.Second
```
Comment (wojtek-t) [inline cmd/integration/integration.go]: cc @fgrzadkowski 
Filip is removing this in #5714, so I think this change will no longer be needed.

File: cmd/integration/integration.go [hunk 3]
```diff
@@ -222,13 +222,17 @@ func startComponents(manifestURL, apiVersion string) (string, string) {
...
+	kubeletapp.RunKubelet(kcfg)
 	// Kubelet (machine)
 	// Create a second kubelet so that the guestbook example's two redis slaves both
 	// have a place they can schedule.
 	testRootDir = makeTempDirOrDie("kubelet_integ_2.", "")
 	glog.Infof("Using %s as root dir for kubelet #2", testRootDir)
-	kubeletapp.SimpleRunKubelet(cl, &fakeDocker2, machineList[1], testRootDir, "", "127.0.0.1", 10251, api.NamespaceDefault, empty_dir.ProbeVolumePlugins(), nil, cadvisorInterface, "")
+	kcfg = kubeletapp.SimpleKubelet(cl, &fakeDocker2, machineList[1], testRootDir, "", "127.0.0.1", 10251, api.NamespaceDefault, empty_dir.ProbeVolumePlugins(), nil, cadvisorInterface, "")
+	kcfg.PodStatusUpdateFrequency = 1 * time.Second
```
Comment (wojtek-t) [inline cmd/integration/integration.go]: cc @fgrzadkowski 
Filip is removing this in #5714, so I think this change will no longer be needed.

File: cmd/integration/integration.go [hunk 4]
```diff
@@ -317,8 +323,7 @@ containers:
 	ioutil.WriteFile(manifestFile.Name(), []byte(manifest), 0600)
 
 	// Wait for the mirror pod to be created.
-	hostname, _ := os.Hostname()
-	podName := fmt.Sprintf("static-pod-%s", hostname)
+	podName := "static-pod-localhost"
```
Comment (wojtek-t) [inline cmd/integration/integration.go]: FYI: I'm also touching this in #5785, but your PR will probably be merged sooner :)

**Comment by wojtek-t** [comment]
LGTM

Thanks for those changes @smarterclayton

**Comment by wojtek-t** [comment]
It seems that Shippable failure is a flake.

File: cmd/integration/integration.go (hunk 2 above)
Comment (smarterclayton) [inline cmd/integration/integration.go]: We still want the ability to tune the simple kubelet for test cases instead of adding methods to it.  If #5714 goes in first I will remove this usage of PodStatusUpdateFrequency.

**Comment by smarterclayton** [comment]
Addressed nit, will merge on green.

**Comment by smarterclayton** [comment]
The shippable failure is either a timing problem (slow) or a race in the integration test.  Will look a bit more through it to double check.

**Comment by smarterclayton** [comment]
Ah ha!  There was a bug in podRunning.  That was fun... this should go green now.

File: cmd/integration/integration.go [hunk 5]
```diff
@@ -295,6 +302,9 @@ func podNotFound(c *client.Client, podNamespace string, podID string) wait.Condi
 func podRunning(c *client.Client, podNamespace string, podID string) wait.ConditionFunc {
 	return func() (bool, error) {
 		pod, err := c.Pods(podNamespace).Get(podID)
+		if apierrors.IsNotFound(err) {
```
Comment (smarterclayton) [inline cmd/integration/integration.go]: This being missing was causing integration to race and be flaky.

**Comment by thockin** [comment]
LGTM, just waiting

**Comment by smarterclayton** [comment]
One shippable flaked, the other passed.

**Comment by smarterclayton** [comment]
Travis will probably run sometime before next Monday.

File: cmd/integration/integration.go (hunk 5 above)
Comment (yujuhong) [inline cmd/integration/integration.go]: @smarterclayton, why does this help? Line 308 checks whether err is nil anyway...

Comment (smarterclayton) [inline cmd/integration/integration.go]: If the pod is not found that means it's not there "yet".  Returning an error immediately terminates the Poll.  So before, this method ran once and returned failure, so it wasn't waiting.  IsNotFound means "keep looking" not "finish".

**Comment by thockin** [comment]
1/2 shippable is done.  only took 15 minutes

File: cmd/integration/integration.go (hunk 5 above)
Comment (yujuhong) [inline cmd/integration/integration.go]: If error terminates the poll, shouldn't we always return no err? What if the apiserver refuses the connection or some other unrelated errors happen?

Comment (smarterclayton) [inline cmd/integration/integration.go]: Unrelated errors should be logged since this is an integration test (it might be a bad configuration).  The odds of an individual call failing due to apiserver is so low that in a test case it's better to report it.

----- Original Message -----

**Comment by thockin** [comment]
Green
