### PR TITLE
Fix kubeadm etcd manifests to use brackets around IPv6 addrs

### LINKED ISSUE #1212: kubeadm init failing for IPv6-only configuration
reported by @leblancd here:
https://github.com/kubernetes/kubernetes/issues/70617

------

**What happened**:
If you run 'kubeadm init ...' with an IPv6-only configuration, kubeadm will keep hanging and timing out here:

```
[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
```
Looking at the state of kubernetes system pods, both etcd and API controller pods are crashing.
Looking at the etcd server docker container logs, you'll find:

```
invalid value "https://fd00:20::2:2379" for flag -advertise-client-urls: URL address does not have the form "host:port": https://fd00:20::2:2379
. . .
```
The issue here is that the URL used for '--advertise-client-urls' needs square brackets around the IP address iff that IP address is IPv6, i.e. the URL should be "https://[fd00:20::2]:2379.

Inspecting the kubeadm code, the problem appears to be here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/etcd/local.go#L145-L147

```
   "advertise-client-urls":       fmt.Sprintf("https://%s:%d", cfg.APIEndpoint.AdvertiseAddress, kubeadmconstants.EtcdListenClientPort),
   "listen-peer-urls":            fmt.Sprintf("https://%s:%d", cfg.APIEndpoint.AdvertiseAddress, kubeadmconstants.EtcdListenPeerPort),
   "initial-advertise-peer-urls": fmt.Sprintf("https://%s:%d", cfg.APIEndpoint.AdvertiseAddress, kubeadmconstants.EtcdListenPeerPort),
```
There are other "IPv4-isms" in this script, just search for "%s:%d".

**What you expected to happen**:
IPv6 magic.

**How to reproduce it (as minimally and precisely as possible)**:
(1) git clone latest k8s master: https://github.com/kubernetes/kubernetes
(2) git clone https://github.com/kubernetes-sigs/kubeadm-dind-cluster
(2) Use Kubeadm-DinD-Cluster (K-D-C) scripts to bring up an IPv6-only cluster:

```
cd $GOPATH/src/k8s.io/kubernetes
make clean
export IP_MODE=ipv6
export BUILD_KUBEADM=y
export BUILD_HYPERKUBE=y
export REMOTE_DNS64_V4SERVER=<your-local-DNS-server-if-necessary>
$HOME/kubeadm-dind-cluster/dind-cluster.sh up
```
**Anything else we need to know?**:
Looks like the code in local.go that is described above was changed with PR #69486

**Environment**:

* Kubernetes version (use `kubectl version`): Latest, it's build with K-D-C scripts above
* Cloud provider or hardware configuration: Any Linux server, just use K-D-C
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Install tools:
* Others:

### PR DESCRIPTION
**Pull request by leblancd**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Kubeadm init with an IPv6-only configuration is currently failing to bring up a cluster. In this failure condition, kubeadm is waiting forever for the control plane to come up. This failure is described in [kubernetes/kubeadm Issue # 1212](https://github.com/kubernetes/kubeadm/issues/1212). The root cause is that kubeadm is generating an erroneous etcd.yaml manifest that has entries of the form:
```
   - --advertise-client-urls=https://fd00:20::2:2379
```
And this is causing the etcd server to crash.
For IPv6 addresses, this URL should use square brackets around the IPv6 address, e.g.:
```
   - --advertise-client-urls=https://[fd00:20::2]:2379
```
The fix is to use net.JoinHostPort() to generate URLs such as the above.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes [kubernetes/kubeadm # 1212](https://github.com/kubernetes/kubeadm/issues/1212)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Review by rosti — COMMENTED** [review]
@leblancd thanks for your contribution! Looks OK to me.

One tiny nit though. It looks to me, that we have too many times code in the spirit of:

```go
fmt.Sprintf("https://%s", net.JoinHostPort(cfg.APIEndpoint.AdvertiseAddress, strconv.Itoa(kubeadmconstants.EtcdListenClientPort)))
```

Perhaps we should add an utility function to `k8s.io/kubernetes/cmd/kubeadm/app/util/etcd` that takes `AdvertiseAddress` as an argument?

**Review by pmichali — APPROVED** [review]
/lgtm Looks like that'll resolve the regeression.

**Comment by leblancd** [comment]
@rosti - I can create a utility function for generating the URLs. This would need to be passed the port as well as the IP address / host. Any preference for name, e.g. etcdutil.URL() or etcdutil.genURL()?
BTW, looks like a github outage is causing test failures?

**Review by pmichali — COMMENTED** [review]
BTW, I see there is a TestGetEtcdCommand() that at least tests some of the URLs generated. Could you add some test cases there, for IPv6? Can you check the other areas to see if there are existing tests that could be adapted to test IPv6 variants?

It looks like there are only two ports used. It would be useful to have a pair of helper methods to generate the URL strings, and use them, to reduce duplication.

**Comment by rosti** [comment]
@leblancd you can add a couple of tiny utility funcs in there, named `GetClientURL` and `GetPeerURL`, so that we keep code more understandable and not have to pass the port constants.

**Comment by leblancd** [comment]
@rosti - Roger that, I understand your earlier comment now, thanks.

**Review by neolit123 — COMMENTED** [review]
@leblancd thank you for this bug fix.
the _test.go files accompanying the touched files would need some updates too.
i.e. we need to add test coverage for IPv6 where applicable.

**Comment by neolit123** [comment]
@pmichali your PR [here](https://github.com/kubernetes/kubernetes/pull/70659/files) is newer and seems to be conflicting with this one on the kubeadm side.

@pmichali and @leblancd please resolve which PR is going to touch kubeadm. we can make this the kubeadm change and the other one the kubelet change.
thanks.

**Comment by leblancd** [comment]
@neolit123 - @pmichali 's PR #70659 is temporarily including my changes because his fix depends on my fix being in place. This change (PR #70633) should be considered the fix for IPv6 errors in kubeadm etcd.yaml .

**Comment by leblancd** [comment]
@neolit123 , @pmichali - I've added unit test cases for local.go and etcd.go.

**Comment by neolit123** [comment]
thanks for the update.
/retest

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 1]
```diff
@@ -330,3 +332,28 @@ func (c Client) WaitForClusterAvailable(delay time.Duration, retries int, retryI
 func CheckConfigurationIsHA(cfg *kubeadmapi.Etcd) bool {
 	return cfg.External != nil && len(cfg.External.Endpoints) > 1
 }
+
+// ipPortURL creates an HTTPS URL based on an IP address
+// and  a port. The URL that is created is of the form:
+//     https://<ip>:<port>
+func ipPortURL(host string, port int) string {
```
Comment (timothysc) [inline cmd/kubeadm/app/util/etcd/etcd.go]: I don't think this really needs to live here, but I don't think it's blocking for me. 

/approve 
/assign @kad   
/cc @bart0sh

**Review by timothysc — APPROVED** [review]
I'd like one of the intel folks to review in the broader context, b/c they've done most of the IPv6 work.

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 1 above)
Comment (kad) [reply cmd/kubeadm/app/util/etcd/etcd.go]: I'd do simpler `"https://" + net.JoinHostPort(...)` instead of calling that function, but this not critical.

Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go]: @leblancd please just remove the utility as per the above comments then LGTM.
thanks!

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 2]
```diff
@@ -358,3 +360,21 @@ func (c Client) WaitForClusterAvailable(delay time.Duration, retries int, retryI
 func CheckConfigurationIsHA(cfg *kubeadmapi.Etcd) bool {
 	return cfg.External != nil && len(cfg.External.Endpoints) > 1
 }
+
+// GetClientURL creates an HTTPS URL that uses the configured advertise
+// address and client port for the API controller
+func GetClientURL(cfg *kubeadmapi.InitConfiguration) string {
+	return "https://" + net.JoinHostPort(cfg.LocalAPIEndpoint.AdvertiseAddress, strconv.Itoa(constants.EtcdListenClientPort))
```
Comment (rosti) [inline cmd/kubeadm/app/util/etcd/etcd.go]: Could have used GetClientURLByIP here, but it's not bad the way it is either.

**Review by rosti — APPROVED** [review]
Thank you @leblancd ! Looks good!
