### PR TITLE
Fixing expected pod subdomain to match framework.TestContext.ClusterD…

### LINKED ISSUE #96288: [Failing Test] [sig-node] SetHostnameAsFQDN tests are failing (ci-kubernetes-node-kubelet-features)
**Which jobs are failing**:
`node-kubelet-features-master` / `ci-kubernetes-node-kubelet-features`

**Which test(s) are failing**:

- `Hostname of Pod [Feature:SetHostnameAsFQDN][NodeFeature:SetHostnameAsFQDN] a pod with subdomain field has FQDN, hostname is shortname [cos-stable1, cos-stable2, ubuntu]`
- `Hostname of Pod [Feature:SetHostnameAsFQDN][NodeFeature:SetHostnameAsFQDN] a pod with subdomain field has FQDN, when setHostnameAsFQDN is set to true, the FQDN is set as hostname [cos-stable1, cos-stable2, ubuntu]`

**Since when has it been failing**:
Since #96173 was merged

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#node-kubelet-features-master

**Reason for failure**:
Example:
```
Expected
        <string>: hostfqdn-29843;hostfqdn-29843.t.hostfqdn-3619.svc.;
        
    to contain substring
        <string>: hostfqdn-29843;hostfqdn-29843.t.hostfqdn-3619.svc.cluster.local;
```

Looks like the `dnsDomain` at L122 and L144 doesn't actually get printed? https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/pod_hostnamefqdn_test.go 

**Anything else we need to know**:
/sig node
/cc @kubernetes/ci-signal @kubernetes/sig-node-test-failures 
/priority important-soon

### PR DESCRIPTION
**Pull request by javidiaz**
Fixing expected pod subdomain to match framework.TestContext.ClusterDNSDomain

**What type of PR is this?**
/kind bug
/kind failing-test

**What this PR does / why we need it**:
Fixes expected subdomain in SetHostnameAsFQDN e2e feature tests

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/96288

### CODE REVIEW

File: test/e2e_node/pod_hostnamefqdn_test.go [hunk 1]
```diff
@@ -71,11 +71,7 @@ func testPod(podnamebase string) *v1.Pod {
 
 var _ = SIGDescribe("Hostname of Pod [Feature:SetHostnameAsFQDN][NodeFeature:SetHostnameAsFQDN]", func() {
 	f := framework.NewDefaultFramework("hostfqdn")
-	dnsDomain := "cluster.local"
-	if cdn := framework.TestContext.ClusterDNSDomain; cdn != "" {
-		dnsDomain = cdn
-	}
-
+	dnsDomain := framework.TestContext.ClusterDNSDomain
```
Comment (AlexeyPerevalov) [inline test/e2e_node/pod_hostnamefqdn_test.go:74]: The default value has been set in test/e2e/framework/test_context.go in RegisterClusterFlags, right?

Comment (javidiaz) [reply test/e2e_node/pod_hostnamefqdn_test.go:74]: Hmm, not sure. The issue I see is that cluster domain is "", but the default should be cluster.local (see https://github.com/kubernetes/kubernetes/blob/512b7b75a8da19e669e058bf13d5978560c4c65f/test/e2e/framework/test_context.go#L334). Maybe I am doing something wrong in my e2e config or maybe framework.NewDefaultFramework sets dns-domain to "", I cannot find it though.

Comment (javidiaz) [reply test/e2e_node/pod_hostnamefqdn_test.go:74]: I add dns-domain to the kubelet-flags when testing, but framework.TestContext.ClusterDNSDomain remains "", even though Pod now have cluster.local

`make test-e2e-node FOCUS="\[NodeFeature:SetHostnameAsFQDN\]" PARALLELISM=1 TEST_ARGS='--kubelet-flags="--fail-swap-on=false" --kubelet-flags="--cluster-domain=cluster.local"'
`
Maybe I should follow up in a new issue, current change should help Node CI to stop failing these tests.

Comment (javidiaz) [reply test/e2e_node/pod_hostnamefqdn_test.go:74]: I think I found the issue with test-e2e-node, I will submit another PR suggesting a change that will make test-e2e-node similar to what hack/ginkgo-e2e.sh does.

Comment (javidiaz) [reply test/e2e_node/pod_hostnamefqdn_test.go]: I created https://github.com/kubernetes/kubernetes/pull/96315 to have cluster.local as default DNS cluster-domain

**Review by alejandrox1 — COMMENTED** [review]
In the context of https://github.com/kubernetes/kubernetes/pull/96315 seems like this should be the proper fix.
Again, thank you @javidiaz for looking into this!

/triage accepted
/approve
/lgtm

**Comment by javidiaz** [comment]
thanks @alejandrox1 !
