### PR TITLE
Fix broken links in api after moving proposals to subdirs

### LINKED ISSUE #918: Organize Design Proposals Folder
The design proposals folder is getting a little out of hand, and we could do a few things to help improve it.

- [ ] In lieu of sig subdirs, create functional area subdirs with clear ownership
- [ ] Create OWNERS files in those subdirs
- [ ] Disambiguate proposals from accepted changes as tracked by #914

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**:
fix incorrect links in api after kubernetes/community#1010

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes  kubernetes/community#918

**Special notes for your reviewer**:
CC @bgrant0607
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, but this is not the right way to fix this. These are all generated files.

Additionally, user documentation should not link to design proposals. They need to link to kubernetes.io docs.

cc @mehdy

**Comment by mbohlool** [comment]
> Thanks, but this is not the right way to fix this. These are all generated files.
Additionally, user documentation should not link to design proposals. They need to link to kubernetes.io docs.

Agree with both. change API docs in pkg/api (to the right locations not design docs) and then run hack/update-openapi-spec.sh and hack/update-swagger-spec*. Put all manual changes in one commit and all generated ones in another commit.

**Comment by huzhengchuan** [comment]
ok, i will fix it. after finished, then review it. @bgrant0607  @mbohlool

**Comment by huzhengchuan** [comment]
I fix your comments, manual changes in the first commit ->'Fix incorrect link in api' and make the new componets, the execute hack/update-all.sh, all generated push in the second commit(generated when exec hack/update-all.sh)
help me review it, thanks  @bgrant0607 @mbohlool

File: pkg/apis/componentconfig/v1alpha1/defaults.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ const (
 
 var (
 	zeroDuration = metav1.Duration{}
-	// Refer to [Node Allocatable](https://git.k8s.io/community/contributors/design-proposals/node-allocatable.md) doc for more information.
+	// Refer to [Node Allocatable](https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md) doc for more information.
```
Comment (mbohlool) [inline pkg/apis/componentconfig/v1alpha1/defaults.go]: This is still pointing to a design doc. Do we have a corresponding doc in kubernetes.io?

File: staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go [hunk 2]
```diff
@@ -1054,7 +1054,7 @@ func applyRetainKeysDirective(original, patch map[string]interface{}, options Me
 // Then, sort them by the relative order in setElementOrder, patch list and live list.
 // The precedence is $setElementOrder > order in patch list > order in live list.
 // This function will delete the item after merging it to prevent process it again in the future.
-// Ref: https://git.k8s.io/community/contributors/design-proposals/preserve-order-in-strategic-merge-patch.md
+// Ref: https://git.k8s.io/community/contributors/design-proposals/cli/preserve-order-in-strategic-merge-patch.md
```
Comment (mbohlool) [inline staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go]: ditto

File: pkg/apis/componentconfig/v1alpha1/defaults.go (hunk 1 above)
Comment (huzhengchuan) [reply pkg/apis/componentconfig/v1alpha1/defaults.go]: because I think this will not be used to generate user documentation. Link to design proposals for developer is more appropriate.

File: staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go (hunk 2 above)
Comment (huzhengchuan) [reply staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go]: I think this will not be used to generate user documentation.  For developer, design proposals is also  appropriate.

**Comment by huzhengchuan** [comment]
@mbohlool thinks for your review.  check it again.
I comment your reviews, If you do not agree with me, please tell me.
also Whether there is more documents about how to generate api doc, please link it to me, I want to know more.

**Comment by huzhengchuan** [comment]
ping  @mbohlool   @erictune  
I think the fix is valid, please help me review it.

**Comment by huzhengchuan** [comment]
rebase it .  @mbohlool  ptal

**Comment by mbohlool** [comment]
unit test is failing. ping me again when the tests are passing and I will take another look.

**Comment by huzhengchuan** [comment]
/cc @luxas   
why the pull-kubernetes-e2e-kubeadm-gce is pending long time. i think you can help me.

**Comment by huzhengchuan** [comment]
ping @mbohlool  ptal
not know why pull-kubernetes-e2e-kubeadm-gce  is always pending.

**Comment by huzhengchuan** [comment]
ping  @smarterclayton  need your approve, thanks
