### PR TITLE
kubelet: Read DNS Config options from file for Windows

### LINKED ISSUE #116782: Sandboxes creation fails with "Unexpected resolver config value" if resolverConfig != "Host" - Windows
### What happened?

When a --resolv-conf (DNS resolver config) is passed to kubelet on a Windows node, the config content is used as part of sandbox initialization (through getHostDNSConfig()). Now with the recent changes ([here](https://github.com/kubernetes/kubernetes/commit/f335812719cfa5d5fb235320fb63af3669ffdcb1)), it seems now to fail with an error like:

`
E0315 10:22:16.244956    4764 pod_workers.go:1256] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8_img-puller-3842(5abbdf2b-b40a-459d-9033-4fec6efe9aba)\" with CreatePodSandboxError: \"Failed to generate sandbox config for pod \\\"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8_img-puller-3842(5abbdf2b-b40a-459d-9033-4fec6efe9aba)\\\": Unexpected resolver config value: \\\"C:\\\\etc\\\\kubernetes\\\\cni\\\\hostdns.conf\\\". Expected \\\"\\\" or \\\"Host\\\".\"" pod="img-puller-3842/img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8" podUID=5abbdf2b-b40a-459d-9033-4fec6efe9aba
`

This is showing on all the runs of GCE testgrid (latest): [here](https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master&show-stale-tests=)

### What did you expect to happen?

Reading/using the passed resolv config on Windows

### How can we reproduce it (as minimally and precisely as possible)?

Run a Windows pool with DNS resolv config being set as part of kubelet params.

### Anything else we need to know?

_No response_

### Kubernetes version

1.27 alpha.3 1.27 beta.0 master

### Cloud provider

<details>
GCE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug
/kind failing-test

/sig windows
/milestone v1.27
/priority important-critical

#### What this PR does / why we need it:

A previous commit added the capability to read the DNS configuration options from a Windows host, while removing the capability to read from a ``resolv.conf``-like file.

This PR addresses this issue: if the given ``--resolv-conf`` option is not set to ``Host``, it will consider it as a file, preserving the previous behavior.

#### Which issue(s) this PR fixes:

Fixes #116782

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by claudiubelu — COMMENTED** [review]
Unit tests on Windows with this PR:

```
PS C:\Users\Administrator\workdir\kubernetes> git fetch origin pull/116800/head
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 12 (delta 9), reused 12 (delta 9), pack-reused 0
Unpacking objects: 100% (12/12), 1.90 KiB | 29.00 KiB/s, done.
From https://github.com/kubernetes/kubernetes
 * branch                    refs/pull/116800/head -> FETCH_HEAD
PS C:\Users\Administrator\workdir\kubernetes> git checkout -f FETCH_HEAD
Updating files: 100% (6024/6024), done.
Previous HEAD position was c9ff2866682 Merge pull request #116772 from jiahuif-forks/fix/validating-admission-policy/message-expression-validation
HEAD is now at a35e5ffa99a kubelet: Read DNS Config options from file for Windows
PS C:\Users\Administrator\workdir\kubernetes> go test -v .\pkg\kubelet\network\dns\
=== RUN   TestParseResolvConf
--- PASS: TestParseResolvConf (0.00s)
=== RUN   TestFormDNSSearchFitsLimits
=== RUN   TestFormDNSSearchFitsLimits/valid:_3_search_paths
=== RUN   TestFormDNSSearchFitsLimits/valid:_5_search_paths
=== RUN   TestFormDNSSearchFitsLimits/invalid:_longer_than_256_characters_in_search_path_list
E0321 03:02:20.152550    1320 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB"
=== RUN   TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_2048_characters_in_search_path_list
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_2050_characters_in_search_path_list
E0321 03:02:20.153755    1320 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_256_characters_search_path
E0321 03:02:20.153863    1320 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB"
=== RUN   TestFormDNSSearchFitsLimits/invalid:_7_search_paths
E0321 03:02:20.153863    1320 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB CCC"
=== RUN   TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_32_search_paths
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_33_search_paths
E0321 03:02:20.153863    1320 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32"
--- PASS: TestFormDNSSearchFitsLimits (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid:_3_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid:_5_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid:_longer_than_256_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_2048_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_2050_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_256_characters_search_path (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid:_7_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_32_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_33_search_paths (0.00s)
=== RUN   TestFormDNSNameserversFitsLimits
E0321 03:02:20.153863    1320 dns.go:158] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 127.0.0.1 10.0.0.10 8.8.8.8"
--- PASS: TestFormDNSNameserversFitsLimits (0.00s)
=== RUN   TestMergeDNSOptions
--- PASS: TestMergeDNSOptions (0.00s)
=== RUN   TestGetPodDNSType
=== RUN   TestGetPodDNSType/valid_DNSClusterFirst_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_with_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSDefault_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSDefault_with_hostnetwork
=== RUN   TestGetPodDNSType/DNSClusterFirst_with_hostnetwork,_fallback_to_DNSDefault
=== RUN   TestGetPodDNSType/valid_DNSNone
=== RUN   TestGetPodDNSType/invalid_DNS_policy,_should_return_error
--- PASS: TestGetPodDNSType (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirst_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_with_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSDefault_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSDefault_with_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/DNSClusterFirst_with_hostnetwork,_fallback_to_DNSDefault (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSNone (0.00s)
    --- PASS: TestGetPodDNSType/invalid_DNS_policy,_should_return_error (0.00s)
=== RUN   TestGetPodDNS
=== RUN   TestGetPodDNS/Not_ExpandedDNSConfig
    dns_test.go:549: nameservers [8.8.8.8]
=== RUN   TestGetPodDNS/ExpandedDNSConfig
    dns_test.go:549: nameservers [8.8.8.8]
--- PASS: TestGetPodDNS (0.00s)
    --- PASS: TestGetPodDNS/Not_ExpandedDNSConfig (0.00s)
    --- PASS: TestGetPodDNS/ExpandedDNSConfig (0.00s)
=== RUN   TestGetPodDNSCustom
=== RUN   TestGetPodDNSCustom/DNSNone_without_DNSConfig_should_have_empty_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSNone_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSClusterFirst_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSClusterFirstWithHostNet_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSDefault_with_DNSConfig_should_have_a_merged_DNS_settings
--- PASS: TestGetPodDNSCustom (0.01s)
    --- PASS: TestGetPodDNSCustom/DNSNone_without_DNSConfig_should_have_empty_DNS_settings (0.01s)
    --- PASS: TestGetPodDNSCustom/DNSNone_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSClusterFirst_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSClusterFirstWithHostNet_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSDefault_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet/network/dns       0.122s
```

File: pkg/kubelet/network/dns/dns_windows.go [hunk 1]
```diff
@@ -64,30 +64,22 @@ var (
 )
 
 func getHostDNSConfig(resolverConfig string) (*runtimeapi.DNSConfig, error) {
-	if resolverConfig != "" && resolverConfig != hostResolvConf {
-		err := fmt.Errorf(`Unexpected resolver config value: "%s". Expected "" or "%s".`, resolverConfig, hostResolvConf)
-		klog.ErrorS(err, "Cannot get host DNS Configuration.")
-		return nil, err
+	if resolverConfig != hostResolvConf {
```
Comment (liggitt) [inline pkg/kubelet/network/dns/dns_windows.go:67]: is "" still possible to encounter here?

**Comment by liggitt** [comment]
/assign @thockin 
as reviewer/approver of https://github.com/kubernetes/kubernetes/pull/110566

File: pkg/kubelet/network/dns/dns_windows.go (hunk 1 above)
Comment (thockin) [inline pkg/kubelet/network/dns/dns_windows.go:67]: Is "Host" sufficiently unambiguous now?  For example, could I point this flag at a file named "File" ?  If so, why would "Host" not mean a file named "Host" ?

Is there some syntax Windows comprehends that is clear not a possible filename?  "Host:" or "host://" or something without the ambiguity?

Or can we assert that this must be an absolute path?  Does a relative path like "File" work today?  We didn't used to assert that, so it's kind of a breaking change.

Comment (marosset) [reply pkg/kubelet/network/dns/dns_windows.go:67]: If relative paths **do not** work today, I'm in favor of asserting this must be an absolute path.
@claudiubelu - can you check if relative paths work today? (and determine where the path is relative *from* so we can document that?)

**Comment by SergeyKanzhelev** [comment]
is it better to change forward or revert and apply both changes in 1.28 to allow more soak time?

**Comment by thockin** [comment]
I'd say to give this one a day or so before aborting the previous PR

**Comment by cici37** [comment]
This Issue/PR has been marked as release blocker. Please have the PR merged by eod today otherwise the feature has to be reverted. For the Issue/PR owner: please have a revert/feature disable PR open today in case the fix failed to get in. Thank you! See the [announcement here](https://groups.google.com/a/kubernetes.io/g/dev/c/yzSvdfk8mo8)

-- Kubernetes 1.27 release manager

**Comment by marosset** [comment]
/lgtm
The updates match the behavior we discussed in the sig-windows community meeting this morning.

File: pkg/kubelet/network/dns/dns_windows.go (hunk 1 above)
Comment (claudiubelu) [reply pkg/kubelet/network/dns/dns_windows.go]: @thockin ``Host`` is the name we've chosen. We could instead use ``HostRegistry``, which is going to be less ambiguous, IMO.

@marosset relative paths are relative to the executable. So, if we're to ``os.Open("resolv.conf")`` file, it would open the ``resolv.conf`` file from the same folder as the binary.

I've updated the PR. Now, we're first checking if the given ``resolverConfig`` is a file or not. If it's a file (using ``os.Stat``), then we're treating it as a file. If it's not a file, we're checking if it's ``resolverConfig`` is ``Host``, and if so, we're getting the Host's DNS configuration. If it's an empty string, an empty DNS configuration is returned.

**Comment by claudiubelu** [comment]
Unit tests run on Windows with the latest changes:

```
git checkout FETCH_HEAD
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  a35e5ffa99a kubelet: Read DNS Config options from file for Windows

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> a35e5ffa99a

HEAD is now at 39ddf738ea0 kubelet: Read DNS Config options from file for Windows
PS C:\Users\Administrator\workdir\kubernetes> go test -count=1 -v .\pkg\kubelet\network\dns\
=== RUN   TestParseResolvConf
--- PASS: TestParseResolvConf (0.00s)
=== RUN   TestFormDNSSearchFitsLimits
=== RUN   TestFormDNSSearchFitsLimits/valid:_3_search_paths
=== RUN   TestFormDNSSearchFitsLimits/valid:_5_search_paths
=== RUN   TestFormDNSSearchFitsLimits/invalid:_longer_than_256_characters_in_search_path_list
E0321 14:39:10.934049    2664 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB"
=== RUN   TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_2048_characters_in_search_path_list
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_2050_characters_in_search_path_list
E0321 14:39:10.935949    2664 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_256_characters_search_path
E0321 14:39:10.935949    2664 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB"
=== RUN   TestFormDNSSearchFitsLimits/invalid:_7_search_paths
E0321 14:39:10.935949    2664 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST AAA BBB CCC"
=== RUN   TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_32_search_paths
=== RUN   TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_33_search_paths
E0321 14:39:10.935949    2664 dns.go:148] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: testNS.svc.TEST svc.TEST TEST 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32"
--- PASS: TestFormDNSSearchFitsLimits (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid:_3_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid:_5_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid:_longer_than_256_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_2048_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_2050_characters_in_search_path_list (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_256_characters_search_path (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid:_7_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/valid_ExpandedDNSConfig:_32_search_paths (0.00s)
    --- PASS: TestFormDNSSearchFitsLimits/invalid_ExpandedDNSConfig:_33_search_paths (0.00s)
=== RUN   TestFormDNSNameserversFitsLimits
E0321 14:39:10.937816    2664 dns.go:158] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 127.0.0.1 10.0.0.10 8.8.8.8"
--- PASS: TestFormDNSNameserversFitsLimits (0.00s)
=== RUN   TestMergeDNSOptions
--- PASS: TestMergeDNSOptions (0.00s)
=== RUN   TestGetPodDNSType
=== RUN   TestGetPodDNSType/valid_DNSClusterFirst_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_with_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSDefault_without_hostnetwork
=== RUN   TestGetPodDNSType/valid_DNSDefault_with_hostnetwork
=== RUN   TestGetPodDNSType/DNSClusterFirst_with_hostnetwork,_fallback_to_DNSDefault
=== RUN   TestGetPodDNSType/valid_DNSNone
=== RUN   TestGetPodDNSType/invalid_DNS_policy,_should_return_error
--- PASS: TestGetPodDNSType (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirst_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_with_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSClusterFirstWithHostNet_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSDefault_without_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSDefault_with_hostnetwork (0.00s)
    --- PASS: TestGetPodDNSType/DNSClusterFirst_with_hostnetwork,_fallback_to_DNSDefault (0.00s)
    --- PASS: TestGetPodDNSType/valid_DNSNone (0.00s)
    --- PASS: TestGetPodDNSType/invalid_DNS_policy,_should_return_error (0.00s)
=== RUN   TestGetPodDNS
=== RUN   TestGetPodDNS/Not_ExpandedDNSConfig
    dns_test.go:549: nameservers [8.8.8.8]
=== RUN   TestGetPodDNS/ExpandedDNSConfig
    dns_test.go:549: nameservers [8.8.8.8]
--- PASS: TestGetPodDNS (0.00s)
    --- PASS: TestGetPodDNS/Not_ExpandedDNSConfig (0.00s)
    --- PASS: TestGetPodDNS/ExpandedDNSConfig (0.00s)
=== RUN   TestGetPodDNSCustom
=== RUN   TestGetPodDNSCustom/DNSNone_without_DNSConfig_should_have_empty_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSNone_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSClusterFirst_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSClusterFirstWithHostNet_with_DNSConfig_should_have_a_merged_DNS_settings
=== RUN   TestGetPodDNSCustom/DNSDefault_with_DNSConfig_should_have_a_merged_DNS_settings
--- PASS: TestGetPodDNSCustom (0.01s)
    --- PASS: TestGetPodDNSCustom/DNSNone_without_DNSConfig_should_have_empty_DNS_settings (0.01s)
    --- PASS: TestGetPodDNSCustom/DNSNone_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSClusterFirst_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSClusterFirstWithHostNet_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
    --- PASS: TestGetPodDNSCustom/DNSDefault_with_DNSConfig_should_have_a_merged_DNS_settings (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet/network/dns       0.144s
```

File: pkg/kubelet/network/dns/dns_windows.go [hunk 2]
```diff
@@ -63,11 +64,18 @@ var (
 	procGetNetworkParams = iphlpapidll.MustFindProc("GetNetworkParams")
 )
 
+func fileExists(filename string) bool {
+	stat, err := os.Stat(filename)
+	if os.IsNotExist(err) {
+		return false
+	}
+	return stat.Mode().IsRegular()
```
Comment (thockin) [inline pkg/kubelet/network/dns/dns_windows.go:72]: If you get any error other than `IsNotExist()`, you can't rely on `stat`.  You need to handle other errors.

File: pkg/kubelet/network/dns/dns_windows.go [hunk 3]
```diff
@@ -63,11 +64,18 @@ var (
...
+}
+
 func getHostDNSConfig(resolverConfig string) (*runtimeapi.DNSConfig, error) {
-	if resolverConfig != "" && resolverConfig != hostResolvConf {
-		err := fmt.Errorf(`Unexpected resolver config value: "%s". Expected "" or "%s".`, resolverConfig, hostResolvConf)
-		klog.ErrorS(err, "Cannot get host DNS Configuration.")
-		return nil, err
+	if fileExists(resolverConfig) {
```
Comment (thockin) [inline pkg/kubelet/network/dns/dns_windows.go:76]: I think, for clarity, this should check `!= "" && fileExists`

Comment (thockin) [reply pkg/kubelet/network/dns/dns_windows.go:76]: Or maybe it should check `== "" || fileExists` - this is the back-compatible path, which lets `getDNSConfig` return it's defaults.

Maybe restructure this as:

```
if resolverConfig != hostResolvConf || fileExists(resolverConfig) {
    // Get the DNS config from a resolv.conf-like file.  This handles "" by returning defaults.
    return getDNSConfig(resolverConfig)
}

// If we get here, the resolverConfig == hostResolvConf and that is not actually a file, so
// it means to use the host settings.

<...>
```

Comment (claudiubelu) [reply pkg/kubelet/network/dns/dns_windows.go]: Done

File: pkg/kubelet/network/dns/dns_windows.go (hunk 2 above)
Comment (claudiubelu) [reply pkg/kubelet/network/dns/dns_windows.go]: Done

**Comment by claudiubelu** [comment]
Unit tests run on Windows with the latest version:

```
PS C:\Users\Administrator\workdir\kubernetes> git fetch origin pull/116800/head
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 12 (delta 7), reused 10 (delta 6), pack-reused 0
Unpacking objects: 100% (12/12), 11.54 KiB | 223.00 KiB/s, done.
From https://github.com/kubernetes/kubernetes
 * branch                    refs/pull/116800/head -> FETCH_HEAD
PS C:\Users\Administrator\workdir\kubernetes> git checkout FETCH_HEAD
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  39ddf738ea0 kubelet: Read DNS Config options from file for Windows

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 39ddf738ea0

HEAD is now at c68bc27f739 kubelet: Read DNS Config options from file for Windows
PS C:\Users\Administrator\workdir\kubernetes> go test -count=1 .\pkg\kubelet\network\dns\
ok      k8s.io/kubernetes/pkg/kubelet/network/dns       0.173s
```

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
