### PR TITLE
(scheduler e2e) Create balanced pods in parallel

### LINKED ISSUE #100705: Regression: Multi-AZ Clusters test timing out in big clusters
From https://github.com/kubernetes/kubernetes/pull/98699#issuecomment-810916947

After #98699, Multi-AZ Clusters tests in 1.19 and 1.20 started timing out as createBalancedPodForNodes is extremely inefficient in scale: for each node (out of 5k), it lists all pods in a cluster serially (each list takes ~5s), which translates to ~7 hours.

Optimizing this function by listing pods once and then in memory by Spec.NodeName

/kind bug
/priority critical-urgent
/sig scheduling

### PR DESCRIPTION
**Pull request by damemi**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
In large clusters, the tests which use this function are timing out due to creating the pods one at a time. This creates them in parallel

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/100705

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/cc @alculquicondor 
This would be the simplest way to do it, but let me know if you think we should wrap the whole function in a `go func` rather than just the pod creation part

File: test/e2e/scheduling/priorities.go [hunk 1]
```diff
@@ -567,10 +570,14 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
-			*initPausePod(f, *podConfig), true, framework.Logf)
+		go func(){
+			err := testutils.StartPods(cs, 1, ns, string(uuid.NewUUID()),
+				*initPausePod(f, *podConfig), true, framework.Logf)
+			errChan <- err
+		}()
 
-		if err != nil {
+		select {
+		case err := <-errChan:
```
Comment (alculquicondor) [inline test/e2e/scheduling/priorities.go:580]: This doesn't look correct. This will be satisfied when any `StartPods` function finishes, with or without an error.

We better use a wait group.

BTW, could there be a node or a set of nodes where we don't need to create any pod?

Comment (damemi) [reply test/e2e/scheduling/priorities.go]: Good point, I updated this to use a waitgroup. We do still need to handle the errors if necessary, so I changed the `select` statement to add a conditional check for `err != nil`.

To answer your question, we are creating a pod on every node that's at least the cri-o minMemLimit (from https://github.com/kubernetes/kubernetes/pull/98073)

File: test/e2e/scheduling/priorities.go [hunk 2]
```diff
@@ -527,6 +528,10 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
 		}
 	}
 
+	errChan := make(chan error, 1)
```
Comment (alculquicondor) [inline test/e2e/scheduling/priorities.go:531]: if more than one creation fails, the routines will be blocked before they can do `wg.Done()`.

File: test/e2e/scheduling/priorities.go (hunk 1 above)
Comment (alculquicondor) [reply test/e2e/scheduling/priorities.go]: Or rather, a node that already has the desired cpu/memory ratio.

Comment (damemi) [reply test/e2e/scheduling/priorities.go]: Nope, doing so could cause the problem described in https://github.com/kubernetes/kubernetes/pull/98073. For example, if one node already has the target ratio and another node is just below it, the requested balancing resources could be less than the cri-o minimum. If every node gets at least 1 pod that is requesting at least the cri-o minimum, then we know that all balancing pods will request sufficient memory.

File: test/e2e/scheduling/priorities.go (hunk 2 above)
Comment (damemi) [reply test/e2e/scheduling/priorities.go:531]: Should `size` be `len(nodes)` then?

Comment (jkaniuk) [reply test/e2e/scheduling/priorities.go:531]: yes and select handling this channel should also summarize those errors

Comment (damemi) [reply test/e2e/scheduling/priorities.go]: Sounds good, I updated that and aggregated the errors from the error channel. Though, I am not sure how exactly the `wg.Wait()` works, should I have some different handling for that so it doesn't block the `select` statement or will the errors just get through once all the routines have finished?

Comment (jkaniuk) [reply test/e2e/scheduling/priorities.go]: select will only handle single value from chan.

I propose sth like:
```
close(errChan)
for err := range errChan {
     ...
}
```

File: test/e2e/scheduling/priorities.go [hunk 3]
```diff
@@ -20,7 +20,9 @@ import (
 	"context"
 	"encoding/json"
 	"fmt"
+	"k8s.io/apimachinery/pkg/util/errors"
```
Comment (pacoxu) [inline test/e2e/scheduling/priorities.go:23]: Add this import in Line 38.

File: test/e2e/scheduling/priorities.go (hunk 2 above)
Comment (damemi) [reply test/e2e/scheduling/priorities.go]: @jkaniuk thanks, updated with what you said. please let me know if this looks right

Comment (jkaniuk) [reply test/e2e/scheduling/priorities.go]: LGTM modulo one comment

File: test/e2e/scheduling/priorities.go [hunk 4]
```diff
@@ -566,14 +571,25 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
-
-		err := testutils.StartPods(cs, 1, ns, string(uuid.NewUUID()),
-			*initPausePod(f, *podConfig), true, framework.Logf)
-
+		wg.Add(1)
+		go func() {
+			defer wg.Done()
+			err := testutils.StartPods(cs, 1, ns, string(uuid.NewUUID()),
+				*initPausePod(f, *podConfig), true, framework.Logf)
+			errChan <- err
```
[the remark this answers is not in the document]
Comment (damemi) [reply test/e2e/scheduling/priorities.go]: good call, updated

File: test/e2e/scheduling/priorities.go (hunk 3 above)
Comment (jkaniuk) [reply test/e2e/scheduling/priorities.go:23]: +1

Comment (damemi) [reply test/e2e/scheduling/priorities.go]: Done, thanks

**Comment by jkaniuk** [comment]
Thanks Mike!

**Comment by alculquicondor** [comment]
retroactive lgtm

**Comment by alculquicondor** [comment]
also, we need backports
