### PR TITLE
Bugfix: remove PV dir when umount raw block device

### LINKED ISSUE #79780: Dir  automatically create would not be automatically removed when using csi raw block volume
**What happened**:

dir crated in /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices would not be automatically removed.

**What you expected to happen**:

when a pod delete the, the dir would be removed

**How to reproduce it (as minimally and precisely as possible)**:

create a pod using csi raw block volume and delete it

**Anything else we need to know?**:

image
 pod using pv-cb59bbc9-6195-49a0-b262-1adc9edeed1b actually has been deleted and the volume has been unmounted, but the dir still exists.

image

/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/{pv}/data still exists

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Dir automatically create would not be automatically removed when using csi raw block volume

**Which issue(s) this PR fixes**:

Fixes #79780 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
@jsafrane  I have updated this PR, since it seems that the issue only occurs when we use csi block drivers because we need to save vol_data.json.

 I would also try  to check other block volumes if other volumes also need clean up when `TearDown`

**Comment by cwdsuzhou** [comment]
ping @jsafrane for review

File: pkg/volume/csi/csi_block.go [hunk 1]
```diff
@@ -367,5 +367,10 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
 		}
 	}
 
+	pvPath := filepath.Dir(globalMapPath)
+	err = os.RemoveAll(pvPath)
```
Comment (jsafrane) [inline pkg/volume/csi/csi_block.go]: I don't feel well when I see `os.RemoveAll`. In case of a driver failure, it *can* remove user data, right? Even if it is a symlink / bind mount to a real device.

`os.Remove` would be IMO enough here, reporting errors if it fails (so user knows the driver left some stale data there).

**Review by jsafrane — COMMENTED** [review]
Should we remove also `publishPath` directory too?

File: pkg/volume/csi/csi_block.go (hunk 1 above)
Comment (cwdsuzhou) [reply pkg/volume/csi/csi_block.go]: Yeap, but usually data.vol.json would still exist, which would cause os.Remove() failed.
So, I think, we should remove the file first.

**Comment by cwdsuzhou** [comment]
> Should we remove also `publishPath` directory too?

`publishPath` has already been removed.

File: pkg/volume/csi/csi_block.go (hunk 1 above)
Comment (cwdsuzhou) [reply pkg/volume/csi/csi_block.go]: @jsafrane wdyt?

File: pkg/volume/csi/csi_block.go [hunk 2]
```diff
@@ -367,5 +367,18 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
 		}
 	}
 
+	// remove vol_data.json first, then remove the other dir
+	pvPath := filepath.Dir(globalMapPath)
+
+	volDataFilePath := filepath.Join(pvPath, volDataFileName)
```
Comment (cwdsuzhou) [inline pkg/volume/csi/csi_block.go]: I  would like remove the vol_data.json here, but not user data

File: pkg/volume/csi/csi_block.go [hunk 3]
```diff
@@ -367,5 +367,17 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
 		}
 	}
 
+	// remove /data/vol_data.json first, then remove the other dir.
+	dataDir := getVolumeDeviceDataDir(m.specName, m.plugin.host)
+	err = os.RemoveAll(dataDir)
```
Comment (jingxu97) [inline pkg/volume/csi/csi_block.go]: use Remove() or RemoveAll() here?

Comment (cwdsuzhou) [reply pkg/volume/csi/csi_block.go]: current dir is like this ~/${pv}/data/vol.json.  Due to vol_data.json left, /data can not be removed use Remove(). Users' data is under ~/${pv}/${link}, so I think RemoveAll() would not harm users' data

Comment (jsafrane) [reply pkg/volume/csi/csi_block.go]: I've seen CSI drivers that use bind-mounts instead of a symlink. I know, in most cases it will delete just the device file, not content of device itself.

But we've learned the hard way not to use RemoveAll on a directory / file exported to a container (CSI, in this case). I'd prefer to remove the json file + `Remove()` on the dir. If there are any leftovers it should be reported as error of the CSI driver.

Comment (cwdsuzhou) [reply pkg/volume/csi/csi_block.go]: Thanks, I have change the PR, like this:

1. Remove json file
2. Remove data dir
3. Remove pv dir

PTAL

**Comment by davidz627** [comment]
Hi @cwdsuzhou @jsafrane, It looks like this broke block volumes for the PD CSI driver.
I haven't figured out exactly how/why it breaks it yet but I've confirmed that this is the PR that stops it from working. The behavior in the failing test's I'm seeing is that the volume doesn't get detached from the node and therefore can't be deleted. Will look into it more tomorrow but wanted to post this first in case you had any hunches as to why.

testgrid links: https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest

**Comment by davidz627** [comment]
Reading through the comments on this PR it looks like maybe the PD Driver needs to clean up after itself when using block volumes or else the `Remove` may fail.

**Comment by davidz627** [comment]
Ok the more I dig the weirder this gets.

First of all, according to this comment we were already removing the dir and the stored data *after* `TearDownDevice`:
https://github.com/kubernetes/kubernetes/blob/dc0013a506d50c54d5a5833e92d82fce61301c2e/pkg/volume/util/operationexecutor/operation_generator.go#L1346

However, actually looking at this function it actually only does a `RemoveAll` on this mysterious `globalMapPath` (which doesn't actually contain the stored data, it's actually `~/${pv}/dev`):
https://github.com/kubernetes/kubernetes/blob/dc0013a506d50c54d5a5833e92d82fce61301c2e/pkg/volume/util/volumepathhandler/volume_path_handler.go#L138
  - Note: IIUC `RemoveAll` is a call we were trying to avoid here - it has the potential to remove all data on disk depending on what `globalMapPath` is.

But here it's even weirder. The original error I'm getting with the PD driver is actually here:
https://github.com/kubernetes/kubernetes/blob/dc0013a506d50c54d5a5833e92d82fce61301c2e/pkg/volume/csi/csi_block.go#L381
because this mysterious `globalMapPath` still exists in the directory. Digging into it more I see that the `globalMapPath` directory is created in `MapDevice`:
https://github.com/kubernetes/kubernetes/blob/dc0013a506d50c54d5a5833e92d82fce61301c2e/pkg/volume/csi/csi_block.go#L270
which seems to use a util function to map the device to the `globalMapPath`:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L516

Unfortunately, this is where the trail ends. The `globalMapPath` is not used ANYWHERE else as far as I can tell. It is never passed in to the driver as an argument to any call (which explains why the driver doesn't clean it up) AND the k8s/k8s cleanup for the path comes *after* the new logic to delete the volume data in `RemoveMapPath`. I believe anybody using block volumes will encounter this same bug EVERY time you try to unmount a volume so unclear to me how any tests ever passed with Block volumes after this change was made (my tests certainly don't pass). 

I honestly have no idea what the intention of `globalMapPath` is but from what I can tell right now it doesn't actually do anything (?). From my guess `globalMapPath` is supposed to equal `stagingPath` but this was lost somewhere along the way and now we have this weird duplicate thing going on.

I also looked into why host-path tests aren't failing with this and actually you can see from the logs that the same error is happening (search `UnmapDevice.TearDownDevice failed for volume`):
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1179119983301496839/artifacts/bootstrap-e2e-minion-group-w1gd/kubelet.log
The "saving grace" is that since host-path doesn't actually attach/detach/provision volumes there is no failure to cleanup the volumes so the tests just stay green.

Anyway, based on the above observations my concrete recommendations are in time order:
1) Revert this PR
2) Turn on block volume tests for in-tree gce pd (my bad I forgot to do this)
3) Check for successful unmount/unstage in all tests (@msau42 says this can be proxied by checking for successful pod deletion)
4) De-deupe `globalMapPath` and `stagingVolumePath` logic since they're the same thing (probably)
5) Rewrite volume data deletion logic in the right place.

**Comment by msau42** [comment]
1) #83379
2) tbd @davidz627 
3) #83382
4) #73773
5) #79780

**Comment by cwdsuzhou** [comment]
Thanks for your analysis @davidz627 and sorry for my mistakes. For my own csi driver(without stage), I do not found the failure and my previous issue showed the reason is then json_data file.

Anyway, It is my mistakes and I  think too many paths exist for block volume, maybe we can optimize it

**Comment by davidz627** [comment]
> Thanks for your analysis @davidz627 and sorry for my mistakes. For my own csi driver(without stage), I do not found the failure and my previous issue showed the reason is then json_data file.
> 
> Anyway, It is my mistakes and I think too many paths exist for block volume, maybe we can optimize it

No worries! The code is confusing and our tests didn't catch any of the errors. Thanks for understanding :)
