### PR TITLE
kubelet: cloud-provider external addresses

### LINKED ISSUE #120720: kubelet: lookup node address logic for external provider assign wrong PodIPs to hostNetwork pods
The kubelet  logic used to get the Node addresses when using an external provider, temporary assigns an address discovered from the node , this address can be overriden later by the external cloud provider

https://github.com/kubernetes/kubernetes/blob/0241da314e0e69817d66313b45a69c19d1ce7327/pkg/kubelet/nodestatus/setters.go#L123-L131

This was implemented in https://github.com/kubernetes/kubernetes/pull/75229 to improve the  bootstrapping problems with some external cloud providers

The side effect of this behavior is that if the external cloud provider sets a different address/es, then the pods with `HostNetwork: true` will be showing the "first" addresses as their `PodIPs`, since we don't mutate those IPs once set to avoid problems

https://github.com/kubernetes/kubernetes/blob/0241da314e0e69817d66313b45a69c19d1ce7327/pkg/kubelet/kubelet_pods.go#L1770-L1786

I think that we should revert the existing logic for external cloud providers, since is causing a temporary and inconsistent state and it seem to address mainly a problem with kubeadm https://github.com/kubernetes/kubernetes/pull/75229#issuecomment-516592142 but kubeadm folks seems to not need this functionality https://github.com/kubernetes/kubernetes/pull/75229#issuecomment-516580449

/kind bug
/sig network
/sig node

### PR DESCRIPTION
**Pull request by aojea**
Kubelet, when using cloud provider external, initializes temporary the node addresses using the --node-ip flag values if set, until the cloud provider overrides it.

This behavior has undesired consequences if the cloud-provider addresses are different than the original ones, specially for hostNetwork pods, that inherit these addresses from the Node.

Since some cloud-providers depend on this behavior, in order to keep backward compatibility, assume that the specifying addresses via the node-ip flags means that the intent is to keep the existing behavior to temporary initialize the addresses.

If the node-ips are the unspecified addresses or are not set, then wait for the external cloud provider to set the node addresses.

/kind bug
/kind documentation
/kind feature

Fixes #120720

```release-note
Kubelet, when using cloud provider external, initializes temporary the node addresses using the --node-ip flag values if set, until the cloud provider overrides it.
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @andrewsykim @danwinship @thockin 
/cc @liggitt 

I think that this approach solves the backwards compatiblity problem and the bug https://github.com/kubernetes/kubernetes/issues/120720

**Review by tzneal — APPROVED** [review]
I don't see any issues with this.  If you supply a node IP, you should know that its correct already.  If you don't supply a node IP, I think it makes sense to just wait for the cloudprovider vs. trying to discover it (and potentially getting it wrong).

/lgtm

File: pkg/kubelet/nodestatus/setters.go [hunk 1]
```diff
@@ -123,11 +123,19 @@ func NodeAddress(nodeIPs []net.IP, // typically Kubelet.nodeIPs
...
 				return nil
 			}
+			// If nodeIPs are not specified wait for the external cloud-provider to set the node addresses.
+			// Otherwise uses them on the assumption that the installer/administrator has the previous knowledge
+			// required to ensure the external cloud provider will use the same addresses to avoid the issues explained
+			// in https://github.com/kubernetes/kubernetes/issues/120720.
+			// We are already hinting the external cloud provider via the annotation AnnotationAlphaProvidedIPAddr.
+			if !nodeIPSpecified {
+				return nil
+			}
```
Comment (danwinship) [inline pkg/kubelet/nodestatus/setters.go:138]: Maybe just squash these two into a single `if` / comment?

**Review by danwinship — APPROVED** [review]

**Comment by danwinship** [comment]
So in #120751 you said:

> superseded by https://github.com/kubernetes/kubernetes/pull/121028 , based on all the comments here and in the issue, I think this new PR covers all the existing cases without breaking compatibility

but AFAICT this PR is identical other than not introducing a feature gate? (You moved the new `if` to the other side of the old `if` but the effect is still the same.)

**Comment by aojea** [comment]
> but AFAICT this PR is identical other than not introducing a feature gate? (You moved the new `if` to the other side of the old `if` but the effect is still the same.)

featuregates are meant to be removed, not to be used as flag, so the behavior is the same ... until the feature flag is removed, this will keep the same behavior

**Comment by cartermckinnon** [comment]
/lgtm

+1 @tzneal, I don't see a risk of breakage here. Thanks @aojea

File: pkg/kubelet/nodestatus/setters.go (hunk 1 above)
Comment (aojea) [reply pkg/kubelet/nodestatus/setters.go:138]: I thought that but in terms of code readability I found this split easier to understand and the git blame will keep the history for both blocks ... in terms of performance is the same , I expect the compiler to do the same thing

**Comment by tzneal** [comment]
> but AFAICT this PR is identical other than not introducing a feature gate? (You moved the new `if` to the other side of the old `if` but the effect is still the same.)

The other one just checked for the feature gate, not the presence of the `--node-ip` flag. In that PR, if you use `--node-ip`, then you would need to make sure the feature gate was set properly, whereas in this one you can just keep using it.

File: pkg/kubelet/nodestatus/setters.go (hunk 1 above)
Comment (liggitt) [reply pkg/kubelet/nodestatus/setters.go:138]: not a huge deal either way, but personally, I appreciate the second if block with the dedicated comment and the preserved history

**Comment by liggitt** [comment]
This means that if you want to run kubelet with `--cloud-provider=external`, the Node either waits for addresses to be assigned by the cloud controller, or you can tell the kubelet the IP (and optionally the hostname) the cloud controller *would* assign with `--node-ip` (and optionally `--hostname-override`) and it'll report them on registration.

That makes sense to me.

**Comment by dims** [comment]
/approve

Treating this as a sig-cloud-provider related PR though the code is in kubelet :) (looks good both as a sig-node reviewer as well as with my sig-cloud-provider 🎩 )

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-apps] Job should not create pods when created in suspend state expand_more	1s
> Kubernetes e2e suite: [It] [sig-storage] HostPath should give a volume the correct mode [LinuxOnly] [NodeConformance] expand_more

unrelated

/test pull-kubernetes-e2e-kind

**Comment by caseydavenport** [comment]
For what it's worth, I think this did have some breaking impacts. Namely, external cloud providers may rely on pod networking to be functioning, and pod networking may rely on node IP addresses being available, resulting in a deadlock (https://github.com/projectcalico/calico/issues/8453#issuecomment-2035324407). I suspect we have workarounds, but figured I'd raise it.

**Comment by aojea** [comment]
> For what it's worth, I think this did have some breaking impacts. Namely, external cloud providers may rely on pod networking to be functioning, and pod networking may rely on node IP addresses being available, resulting in a deadlock ([projectcalico/calico#8453 (comment)](https://github.com/projectcalico/calico/issues/8453#issuecomment-2035324407)). I suspect we have workarounds, but figured I'd raise it.

yeah, it was also reported by the clusterapi people, I'm sorry about that but at least this mode fails fast and loudly, with previous behavior your static pods will have different ips from the new static pods and it will have interesting failures mode

**Comment by aojea** [comment]
For people coming to this issue, and trying to clarify one important issue because most of the problems are related to bad deployment architectures that broke this deployment by this change in behavior.

Since the move to `--cloud-provider=external`, the `cloud-controller-manager` is responsible of some important loops of the cluster that previously ran in the `kube-controller-manager`, like the node bootstrap controller, the node lifecycle controller, the service loadbalancers, the node ipam .....

**IMPORTANT** deploy the CLOUD-CONTROLLER-MANAGER the same as yout `kube-controller-manager`, typically as an static pod on the control plane nodes or you may end with stability problems. Most people is workarounding the problem using the `--node-ip` flag, but if this controller is running as a pod in any node of the cluster it can be impacted by other workloads

**Comment by elmiko** [comment]
@aojea we were talking about this comment in the SIG cloud provider meeting today and we think it would be nice to have a more formal discussion about deployment patterns and the possible advantages and disadvantages of different styles. would you be willing to collaborate on a blog post to go into greater detail on your comment here about static pod deployment?

happy to followup on slack or emails, whatever is most convenient.

**Comment by aojea** [comment]
> happy to followup on slack or emails, whatever is most convenient.

happy to collaborate, let's follow up on slack
