### PR TITLE
AWS: Skip instances that are taggged as a master

### LINKED ISSUE #34583: PersistentVolume on EBS can be created in availability zones with no nodes
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: `aws`
- **Install tools**: `kops` default install

**What happened**: 
AWS EBS backed PersitantVolumeClaim created a volume in an AZ where there was a master but no nodes. Making it unusable.

**What you expected to happen**:
Zones with master and no nodes shouldn't be used to create the EBS Volume

**How to reproduce it** (as minimally and precisely as possible):
- AWS setup across 3 AZs in one region
- Master in three AZs
- Nodes in 2 AZs (so one AZ has a Master but no Nodes)
- Create a Storage class to use EBS without specifying AZ 

```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: ebs
provisioner: kubernetes.io/aws-ebs
```
- Create PVC against StorageClass 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ebs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
```
- PVC can create a volume in an availability zone with no nodes

**Anything else do we need to know**:
Mentioned on Slack channel #sig-aws with @justinsb who asked me to raise this

### PR DESCRIPTION
**Pull request by justinsb**
We recognize a few AWS tags, and skip over masters when finding zones
for dynamic volumes.  This will fix #34583.

This is not perfect, in that really the scheduler is the only component
that can correctly choose the zone, but should address the common
problem.

```release-note
AWS: Do not consider master instance zones for dynamic volume creation
```

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gce e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot kubemark e2e test this
@k8s-bot gci gce e2e test this

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -157,6 +157,10 @@ const (
 	createTagSteps        = 9
 )
 
+// awsTagNameMasterRoles is a set of well-known AWS tag names that indicate the instance is a master
+// The major consequence is that it is then not considered for AWS zone discovery for dynamic volume creation.
+var awsTagNameMasterRoles = sets.NewString("kubernetes.io/role/master", "k8s.io/role/master")
```
Comment (redbaron) [inline pkg/cloudprovider/providers/aws/aws.go]: which of them is more standard? `kubernetes.io` or `k8s.io`?
