### PR TITLE
fix limitranger to handle latent caches without live lookups every time

### LINKED ISSUE #21234: e2e flake: LimitRange [It] should create a LimitRange with defaults and ensure pod has those defaults applied.
LimitRange e2e flake:

```
Failure [7.616 seconds]
LimitRange
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:95
  should create a LimitRange with defaults and ensure pod has those defaults applied. [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:93

  Expected error:
      <*errors.errorString | 0xc20853e960>: {
          s: "resource cpu expected 100m actual 0",
      }
      resource cpu expected 100m actual 0
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/limit_range.go:64
------------------------------
```

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/20114/kubernetes-pull-build-test-e2e-gce/28527/

### PR DESCRIPTION
**Pull request by deads2k**
Fixes https://github.com/kubernetes/kubernetes/issues/21234

If a limit range and a pod are all created very close together, then the cache for the limitranger will not be up to date and I'll be able to sneak a pod in.

It is too expensive to do a live lookup every time.  Instead, and empty answer from the indexer is used to do a lookup in a lru cache of live lookups.  If that results in a cache miss, then an actual live listing is done and the lru cache is primed.

This brought in a new LRU cache library which is thread-safe (the existing one is not).

### CODE REVIEW

File: plugin/pkg/admission/limitranger/admission.go [hunk 1]
```diff
@@ -79,8 +86,27 @@ func (l *limitRanger) Admit(a admission.Attributes) (err error) {
 	if err != nil {
 		return admission.NewForbidden(a, fmt.Errorf("Unable to %s %v at this time because there was an error enforcing limit ranges", a.GetOperation(), a.GetResource()))
 	}
+
+	// if there are no items held in our indexer, check our live-lookup LRU, if that misses, do the live lookup to prime it.
 	if len(items) == 0 {
-		return nil
+		lruList, ok := l.liveLookupCache.Get(a.GetNamespace())
+		if !ok {
+			liveList, err := l.client.Core().LimitRanges(a.GetNamespace()).List(api.ListOptions{})
```
Comment (derekwaynecarr) [inline plugin/pkg/admission/limitranger/admission.go]: isn't this prone to being wrong if the LRU cache is never cleared?  for example, if you add a limit range to a namespace, and later remove it, the LRU cache could have the wrong data?  also what happens if i delete and readd the same namespace, but the new namespace has no limit range?  this looks like it could return wrong data in that scenario?

File: plugin/pkg/admission/limitranger/admission.go [hunk 2]
```diff
@@ -79,8 +86,27 @@ func (l *limitRanger) Admit(a admission.Attributes) (err error) {
...
+			if err != nil {
+				return admission.NewForbidden(a, err)
+			}
+			l.liveLookupCache.Add(a.GetNamespace(), liveList)
```
Comment (derekwaynecarr) [inline plugin/pkg/admission/limitranger/admission.go]: we would need to map to the namespace + uid to ensure we dont get wrong results when namespaces are deleted and recreated...

**Comment by derekwaynecarr** [comment]
I would prefer a flag to admission controller that says to always do a live look-up, and downstream we can run with that flag enabled...  that seems less error-prone and brings it fewer dependencies.

File: plugin/pkg/admission/limitranger/admission.go (hunk 1 above)
Comment (deads2k) [inline plugin/pkg/admission/limitranger/admission.go]: I'll add a ttl to the cache entry to timebound the wrongness.  One minute ought to do for the majority of cases. Once you're beyond that the locality doesn't help.

**Comment by derekwaynecarr** [comment]
After in person chat, I see the point that its best to fail by default if LimitRange is viewed as a more formal aspect of the security apparatus.  With a TTL on the LRU cache to handle re-using namespace names, this is fine.

**Comment by derekwaynecarr** [comment]
Actually, the TTL is problematic, since it will keep checking for those namespaces that don't use it at all...  I guess if that is a major concern, they can choose to not run with the admission controller enabled.

**Comment by deads2k** [comment]
> Actually, the TTL is problematic, since it will keep checking for those namespaces that don't use it at all... I guess if that is a major concern, they can choose to not run with the admission controller enabled.

And the re-lookup boundary would be hit only a couple times per minute, not every request.

**Comment by derekwaynecarr** [comment]
sgtm

**Comment by deads2k** [comment]
ttl added.

**Comment by derekwaynecarr** [comment]
cool, lgtm.

**Comment by nikhiljindal** [comment]
This should fix https://github.com/kubernetes/kubernetes/issues/21234. 
@deads2k You need to run hack/update-godep-licenses.sh to get travis to pass.

**Comment by deads2k** [comment]
> This should fix #21234. 
> @deads2k You need to run hack/update-godep-licenses.sh to get travis to pass.

Thanks, repushed

**Comment by deads2k** [comment]
fix for p1 flake
