### PR TITLE
Remove last endpoint for kubernetes Service during graceful shutdown of final kube-apiserver

### LINKED ISSUE #115804: Last apiserver to shutdown doesn't remove its IP from k8s svc endpoints
### What happened?

As part of the apiserver's pre-shutdown sequence, we stop the lease-controller from renewing the apiserver's etcd lease anymore and delete the lease:

https://github.com/kubernetes/kubernetes/blob/125e38c0872521bec49351415cc9fb624b046659/pkg/controlplane/controller.go#L211-L215

As part of the `RemoveEndpoints` call we expect that after the lease is deleted, the apiserver's IP is also removed from the k8s service endpoints object:

https://github.com/kubernetes/kubernetes/blob/125e38c0872521bec49351415cc9fb624b046659/pkg/controlplane/reconcilers/lease.go#L315-L321

However, `doReconcile` isn't removing the IP if it's the last remaining one:

https://github.com/kubernetes/kubernetes/blob/125e38c0872521bec49351415cc9fb624b046659/pkg/controlplane/reconcilers/lease.go#L210-L215

The comment there is assuming that `doReconcile` is always called after renewing the lease, which is incorrect since it can also be called as part of the shutdown workflow.

### What did you expect to happen?

The IP of the apiserver (even though it's the last one remaining) should be removed from k8s svc endpoints on shutdown.

### How can we reproduce it (as minimally and precisely as possible)?

Shutdown the last apiserver of the cluster and you'll see logs like this:

```
I1031 17:34:49.517758      12 controller.go:181] Shutting down kubernetes service endpoint reconciler
E1031 17:34:49.534880      12 controller.go:184] no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
```

And the audit logs also confirm that the IP isn't removed from k8s endpoints object.

#### Why is this an issue?

If the IP isn't removed from the k8s endpoints object, clients (using in-cluster API mode) will try to continue talking/connecting to that instance even after the apiserver is dead. There are at least two issues with this:
- Causes confusing `i/o timeout` and `connection refused` errors for clients, instead of a cleaner `no route to host` error
- If the apiserver pod is restarted by kubelet (let's say due to healthcheck failure), clients may start talking to it prematurely even without healthz/readyz passing. This is not a recommended behavior ([xref](https://kubernetes.io/docs/reference/using-api/health-checks/)) as a bunch post-startup hooks like informer sync, internal controllers, etc may not have initialized yet

/sig api-machinery

### Kubernetes version

All versions till HEAD.

### Cloud provider

N/A

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by nayihz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The IP of the last one apiserver isn't removed from k8s svc endpoints on shutdown.  Clients (using in-cluster API mode) will try to continue talking/connecting to that instance even after the apiserver is dead.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/115804

#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver always removes its endpoint from kubernetes service during graceful shutdown (even if it's the only/last one)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by czybjtu** [comment]
fix it according to your suggestion, please take a look when you have time. @aojea

File: pkg/controlplane/reconcilers/lease.go [hunk 1]
```diff
@@ -146,16 +147,14 @@ func NewLeases(config *storagebackend.ConfigForResource, baseKey string, leaseTi
 type leaseEndpointReconciler struct {
 	epAdapter             EndpointsAdapter
 	masterLeases          Leases
-	stopReconcilingCalled bool
-	reconcilingLock       sync.Mutex
+	stopReconcilingCalled atomic.Bool
```
Comment (aojea) [inline pkg/controlplane/reconcilers/lease.go:150]: this is ok, this solves the problem of handling termination inside the `doReconcile` method

File: pkg/controlplane/reconcilers/lease.go [hunk 2]
```diff
@@ -167,10 +166,7 @@ func NewLeaseEndpointReconciler(epAdapter EndpointsAdapter, masterLeases Leases)
 // different from the directory listing, and update the endpoints object
 // accordingly.
 func (r *leaseEndpointReconciler) ReconcileEndpoints(serviceName string, ip net.IP, endpointPorts []corev1.EndpointPort, reconcilePorts bool) error {
-	r.reconcilingLock.Lock()
-	defer r.reconcilingLock.Unlock()
```
Comment (aojea) [inline pkg/controlplane/reconcilers/lease.go:171]: if we move this lock inside `doReconcile` we make it thread safe and avoid the race you mentioned, no?

File: pkg/controlplane/reconcilers/lease.go [hunk 3]
```diff
@@ -184,6 +180,7 @@ func (r *leaseEndpointReconciler) ReconcileEndpoints(serviceName string, ip net.
 	return r.doReconcile(serviceName, endpointPorts, reconcilePorts)
 }
 
+// doReconcile can be called from ReconcileEndpoints() or RemoveEndpoints()
 func (r *leaseEndpointReconciler) doReconcile(serviceName string, endpointPorts []corev1.EndpointPort, reconcilePorts bool) error {
 	e, err := r.epAdapter.Get(corev1.NamespaceDefault, serviceName, metav1.GetOptions{})
```
Comment (aojea) [inline pkg/controlplane/reconcilers/lease.go:185]:
```suggestion
// doReconcile can be called from ReconcileEndpoints() or RemoveEndpoints(), it is safe to call it from multiple goroutines
func (r *leaseEndpointReconciler) doReconcile(serviceName string, endpointPorts []corev1.EndpointPort, reconcilePorts bool) error {
          r.reconcilingLock.Lock()
	defer r.reconcilingLock.Unlock()
	e, err := r.epAdapter.Get(corev1.NamespaceDefault, serviceName, metav1.GetOptions{})
```

File: pkg/controlplane/reconcilers/lease.go (hunk 2 above)
Comment (czybjtu) [reply pkg/controlplane/reconcilers/lease.go:171]: Maybe the safest way is keep this lock in `ReconcileEndpoints` and locked this lock in `RemoveEndpoints` meanwhile.

File: pkg/controlplane/reconcilers/lease.go [hunk 4]
```diff
@@ -210,7 +217,9 @@ func (r *leaseEndpointReconciler) doReconcile(serviceName string, endpointPorts
 	// Since we just refreshed our own key, assume that zero endpoints
 	// returned from storage indicates an issue or invalid state, and thus do
 	// not update the endpoints list based on the result.
-	if len(masterIPs) == 0 {
+	// If the controller was ordered to stop and is this is the last apiserver
+	// we keep going to remove our endpoint before shutting down.
+	if !r.stopReconcilingCalled.Load() && len(masterIPs) == 0 {
 		return fmt.Errorf("no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service")
```
Comment (sftim) [inline pkg/controlplane/reconcilers/lease.go:223]:
```suggestion
		return fmt.Errorf("no API server IP addresses were listed in storage, refusing to erase all endpoints for the kubernetes Service")
```
?

File: pkg/controlplane/reconcilers/lease_test.go [hunk 5]
```diff
@@ -503,6 +503,16 @@ func TestLeaseRemoveEndpoints(t *testing.T) {
 			expectUpdate:  makeEndpointsArray("foo", []string{"4.3.2.2", "4.3.2.3", "4.3.2.4"}, []corev1.EndpointPort{{Name: "foo", Port: 8080, Protocol: "TCP"}}),
 			expectLeases:  []string{"4.3.2.2", "4.3.2.3", "4.3.2.4"},
 		},
+		{
+			testName:      "the last apiserver was shutdown",
```
Comment (sftim) [inline pkg/controlplane/reconcilers/lease_test.go:507]:
```suggestion
			testName:      "the last API server was shut down cleanly",
```

File: pkg/controlplane/reconcilers/lease.go
Comment (sftim) [inline pkg/controlplane/reconcilers/lease.go:1]: :thought_balloon: if we know that this is the last kube-apiserver in a cluster, which should we do:
- remove the endpoint representing us from the relevant EndpointSlice
- delete the EndpointSlice (the first API server to start up would need to make a new one)

From an architectural / philosophical point of view, I'm not sure which feels more appropriate.

**Comment by sftim** [comment]
This change is visible to end users. We should provide a release note.

File: pkg/controlplane/reconcilers/lease.go (hunk 2 above)
Comment (aojea) [reply pkg/controlplane/reconcilers/lease.go:171]: > There will be no lock protection after move this lock into `doReconcile` when`UpdateLease` in `ReconcileEndpoints` and `RemoveLease` in `RemoveEndpoints`.

it is an API call, AFAIK the concurrency will be handled by etcd

**Comment by aojea** [comment]
/assign @wojtek-t 

I need your x-rays here, I think that one solution is:
1. move the `stop` variable to atomic.bool so we can handle `termination` inside `doReconcile`
2. lock `doReconcile` to make it threadsafe, so `RemoveEndpoint` and `ReconcileEndpoints` serialize their operations

Because of how the interface is defined, there is no guarantee to implement a better coordination between `RemoveEndpoint` and `ReconcileEndpoints` , since `RemoveEndpoint` is called before start reconciled and when stopping.

Maybe document better its usage to avoid people calling `RemoveEndpoint` and `ReconcileEndpoints` at the same time

File: pkg/controlplane/reconcilers/lease.go (hunk 2 above)
Comment (czybjtu) [reply pkg/controlplane/reconcilers/lease.go:171]: There is a possibility that call `UpdateLease` after `RemoveLease`. So user could get an unexpected error in `ReconcileEndpoints`. I looks a bit strange even though this has no side effects.

Comment (aojea) [reply pkg/controlplane/reconcilers/lease.go:171]: > There is a possibility that call UpdateLease after RemoveLease

that possibility always exist, despite it is locked or not,

Comment (czybjtu) [reply pkg/controlplane/reconcilers/lease.go:171]: yes, you're right.

File: pkg/controlplane/reconcilers/lease_test.go [hunk 6]
```diff
@@ -514,6 +524,7 @@ func TestLeaseRemoveEndpoints(t *testing.T) {
 			clientset := fake.NewSimpleClientset(test.initialState...)
 			epAdapter := NewEndpointsAdapter(clientset.CoreV1(), clientset.DiscoveryV1())
 			r := NewLeaseEndpointReconciler(epAdapter, fakeLeases)
+			r.StopReconciling()
 			err = r.RemoveEndpoints(test.serviceName, netutils.ParseIPSloppy(test.ip), test.endpointPorts)
```
Comment (aojea) [inline pkg/controlplane/reconcilers/lease_test.go:528]: does this no affect the other tests? 
we may add more test cases to exercise the races you mentioned during the review

**Comment by aojea** [comment]
/lgtm cancel

the tests can be improved, also I couldn't look deeper to see if modifying the existing one can cause issues

File: pkg/controlplane/reconcilers/lease_test.go (hunk 6 above)
Comment (czybjtu) [reply pkg/controlplane/reconcilers/lease_test.go:528]: `r.StopReconciling()` has no side effect to current tests because the precondition for executing `TestLeaseRemoveEndpoints` function is that the apiserver has already been shutdown. It's better to add test case for the scenario of apiserver start up.

File: pkg/controlplane/reconcilers/lease.go (hunk 2 above)
Comment (czybjtu) [reply pkg/controlplane/reconcilers/lease.go:171]: I found that `UpdateLease` will create a new key in etcd if the key doesn't exist. So I think locking the `reconcilingLock` in `RemoveEndpoints` and `ReconcileEndpoints` separately is simpler and safer than do this in `doReconcile`.
PR has updated. PTAL if you have time.

Comment (aojea) [reply pkg/controlplane/reconcilers/lease.go:171]: yes, you are right, so the leases can not be updated during the reconcile block

**Comment by czybjtu** [comment]
kindly ping @aojea

**Comment by aojea** [comment]
> kindly ping @aojea

yeah, if you don't ping me I would nto remember sorry, let me check it

**Comment by wojtek-t** [comment]
@aojea I have added release note - PTAL.

Overall this looks good - thanks for making this happen.

/lgtm
/approve
