### PR TITLE
Check KUBE_SERVER_PLATFORMS emptiness

### LINKED ISSUE #78055: Make release of v1.14.2 failed
**What happened**:
Make release of v1.14.2 failed. After facing the error `hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable` ([link to code](https://github.com/kubernetes/kubernetes/blob/v1.14.2/hack/lib/golang.sh#L295)) we did 4 `cherry-pick`:

- 38b7f2125fa571bdd9fe3070b808635f88586dd1
- 7e2aa46f64a67a50e8155538750c08b83dffa348
- eaafa5952f8073f51b13dbeafe406019995c8c0b

- a commit in @cblecker 's opening PR #78048 (b8481b62fcb38d7af96d4af2e2077fcfb2921712)

Then the build process failed again:
```
/home/ubuntu/kubernetes/hack/lib/golang.sh: line 305: KUBE_SERVER_PLATFORMS[@]: unbound variable
/home/ubuntu/kubernetes/hack/lib/golang.sh: line 305: KUBE_SERVER_PLATFORMS[@]: unbound variable
Makefile.generated_files:514: recipe for target 'gen_bindata' failed
make[2]: *** [gen_bindata] Error 1
make[2]: Leaving directory '/home/ubuntu/kubernetes'
Makefile:526: recipe for target 'generated_files' failed
make[1]: *** [generated_files] Error 2
make[1]: Leaving directory '/home/ubuntu/kubernetes'
Makefile:23: recipe for target 'kubernetes-build' failed
make: *** [kubernetes-build] Error 2
```
What we did was:
we ran two commands
```
make generated_files
make WHAT=cmd/kubectl KUBE_BUILD_PLATFORMS="darwin/amd64 windows/amd64"
```
`make generated_files` called [kubernetes/build/root/Makefile](https://github.com/kubernetes/kubernetes/blob/v1.14.2/build/root/Makefile#L92), after that,  we did `make WHAT=cmd/kubectl KUBE_BUILD_PLATFORMS="darwin/amd64 windows/amd64"`. And right after this command, the error happened.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.2
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04, bash version 4.3

@cblecker @tpepper @figo

### PR DESCRIPTION
**Pull request by figo**
when compile kubectl on platform other than
linux/amd64, KUBE_SERVER_PLATFORMS will be empty which is expected,
so we need to check the KUBE_SERVER_PLATFORMS array emptiness before use it.

the example command is:
make WHAT=cmd/kubectl KUBE_BUILD_PLATFORMS="darwin/amd64 windows/amd64"

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #78055

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix KUBE_SERVER_PLATFORMS null error when cross compiling kubectl for non-linux platform
```

@cblecker @tpepper @jiatongw @dims @BenTheElder 

/sig release

### CODE REVIEW

**Comment by figo** [comment]
cc @mtaufen could you help to review it since you introduced KUBE_SERVER_PLATFORMS

**Review by jiatongw — COMMENTED** [review]
Tested on my 1.14.2 testing branch and it works for command `make WHAT=cmd/kubectl KUBE_BUILD_PLATFORMS="darwin/amd64 windows/amd64"`

OS: ubuntu 16.04, bash version 4.3

**Comment by tpepper** [comment]
Works for me on non-homebrew MacOS, for 1.14.2 plus the other stack of make fixes described in #78048

File: hack/lib/golang.sh [hunk 1]
```diff
@@ -292,7 +292,9 @@ kube::golang::server_test_targets() {
 IFS=" " read -ra KUBE_TEST_SERVER_TARGETS <<< "$(kube::golang::server_test_targets)"
 readonly KUBE_TEST_SERVER_TARGETS
 readonly KUBE_TEST_SERVER_BINARIES=("${KUBE_TEST_SERVER_TARGETS[@]##*/}")
-readonly KUBE_TEST_SERVER_PLATFORMS=("${KUBE_SERVER_PLATFORMS[@]}")
+if [[ -n "${KUBE_SERVER_PLATFORMS:-}" ]]; then
+  readonly KUBE_TEST_SERVER_PLATFORMS=("${KUBE_SERVER_PLATFORMS[@]}")
```
Comment (cblecker) [inline hack/lib/golang.sh]: Instead of ifs, just change this line to:
```suggestion
  readonly KUBE_TEST_SERVER_PLATFORMS=("${KUBE_SERVER_PLATFORMS[@]:+"${KUBE_SERVER_PLATFORMS[@]}"}")
```

Comment (figo) [reply hack/lib/golang.sh]: @cblecker  thank you for the suggestion, your version is really nit with just one line, but i find it is less obvious and took me sometime to understand.

i would prefer to keep the current ifs if the extra line make it a little easier to understand, thanks

Comment (cblecker) [reply hack/lib/golang.sh]: @figo Yours does something different, however. Yours doesn't even set `KUBE_TEST_SERVER_PLATFORMS` because it's an if.

Please make the requested change. Thank you!

Comment (figo) [reply hack/lib/golang.sh]: @cblecker i see what you mean now, PR refreshed, thx
