### PR TITLE
Fixed race condition in test manager shutdown

### LINKED ISSUE #108040: kubelet: Race condition in nodeshutdown unit test
### What happened?

There seems to be a race condition in the following unit test

https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L617

The race happens between
read at
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L707

and write at
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L328

### What did you expect to happen?

No race condition

### How can we reproduce it (as minimally and precisely as possible)?

```bash
cd $KUBE_ROOT/pkg/kubelet/nodeshutdown
go test -c -race
stress ./nodeshutdown.test -test.run ^Test_managerImpl_processShutdownEvent$
```

### Anything else we need to know?

CI logs where race was detected: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108039/pull-kubernetes-unit/1491676749694504960

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by utkarsh348**
#### What type of PR is this?

 /kind bug

#### Which issue(s) this PR fixes:

Fixes #108040

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by utkarsh348** [comment]
@MadhavJivrajani Please do have a look. Thank you!

**Comment by MadhavJivrajani** [comment]
/remove-sig api-machinery apps scalability auth cli network cloud-provider cluster-lifecycle storage testing

**Comment by MadhavJivrajani** [comment]
/remove-sig architecture scheduling instrumentation release windows security

**Comment by MadhavJivrajani** [comment]
/remove-kind api-change
/kind cleanup
(all labels applied due to a `git` mishap :), this is a sig-node change, please ignore the `area` labels except for `area/kubelet`)

**Comment by SergeyKanzhelev** [comment]
/remove-area apiserver cloudprovider code-generation e2e-test-framework kubectl release-eng
/triage accepted

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go [hunk 1]
```diff
@@ -681,7 +698,7 @@ func Test_managerImpl_processShutdownEvent(t *testing.T) {
 			l := klog.Level(1)
 			l.Set("1")
 			// hijack the klog output
-			tmpWriteBuffer := bytes.NewBuffer(nil)
+			tmpWriteBuffer := new(buffer)
 			klog.SetOutput(tmpWriteBuffer)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:702]: I wonder how this test even work with other tests. It never restores output and level back to what it was. Is the race here between the test cases? And if the test keeps writing to the buffer, does the `string.Contains` guaranteed to have a string to compare?

/sig instrumentation

@kubernetes/sig-instrumentation-members what are the best practices to test the klog output in unit tests?

Comment (utkarsh348) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:702]: The problem earlier was with the test itself attempting to read from the buffer while the writes were still being made by klog. I think the issue was within a test case itself and I don't think there's a problem with klog. ```string.Contains``` should have a string since I don't think it can proceed until it's been safe to read from the buffer. I saw a similar issue in another test being affected by writes from klog as well here [#98944](https://github.com/kubernetes/kubernetes/pull/98944) and I assumed there's a similar problem here. Please do let me know if I've misunderstood your question or missed something in the fix. Thank you for responding!

**Comment by dims** [comment]
@endocrimes i am going to get this in today so we can get an extra day of soak to see if this helps or not.

I did test this by hand with the instructions in https://github.com/kubernetes/kubernetes/issues/108040 and i do not see the race condition after the patch.

/approve
/lgtm

**Comment by dims** [comment]
@MadhavJivrajani @utkarsh348 once this merges, please poke at logs in the ci jobs where this gets run and confirm that the patch helps or not.

thanks!
