### PR TITLE
scheduler: fix race in DRA pending allocation sharing

### LINKED ISSUE #137617: DRA scheduler plugin cannot fulfill gang scheduling with shared ResourceClaims
### What happened?

When two Pods are created in a gang where both Pods share the same ResourceClaim, the scheduler falls into an endless loop trying to schedule the Pods and never succeeds.

```
Events:
  Type     Reason            Age                          From               Message
  ----     ------            ----                         ----               -------
  Warning  FailedScheduling  2m21s (x2292168 over 7m21s)  default-scheduler  0/2 nodes are available: resource claim default/single-gpu is in the process of being allocated. no new claims to deallocate, preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

### What did you expect to happen?

Both Pods schedule with the shared ResourceClaim.

### How can we reproduce it (as minimally and precisely as possible)?

Create a kind cluster:
```
kind build node-image --image kindest/node:latest
kind create cluster --image kindest/node:latest --config kind.yaml
```
<details>
<summary>kind.yaml</summary>

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    apiServer:
        extraArgs:
          runtime-config: "scheduling.k8s.io/v1alpha2=true"
featureGates:
  GenericWorkload: true
  GangScheduling: true
```

</details>

Install a DRA driver:
```
helm upgrade --install dra-example-driver oci://registry.k8s.io/dra-example-driver/charts/dra-example-driver -n dra-example-driver --create-namespace
```

Create a ResourceClaim, PodGroup, and Pods in the PodGroup sharing the claim:
<details>
<summary>workload.yaml</summary>

```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: single-gpu
spec:
  devices:
    requests:
    - name: gpu
      exactly:
        deviceClassName: gpu.example.com
---
apiVersion: scheduling.k8s.io/v1alpha2
kind: PodGroup
metadata:
  name: podgroup
spec:
  schedulingPolicy:
    gang:
      minCount: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      resourceClaims:
        - name: claim
          resourceClaimName: single-gpu
      containers:
        - name: ctr
          image: ubuntu:22.04
          command: ["bash", "-c"]
          args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
          resources:
            claims:
              - name: claim
      schedulingGroup:
        podGroupName: podgroup
```
</details>

### Anything else we need to know?

Both Pods will schedule together if either of the following changes are made:
- Set the PodGroup's `spec.schedulingPolicy` to `basic: {}`
- Create separate ResourceClaims for each Pod instead of sharing (ResourceClaimTemplate).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.1
Kustomize Version: v5.7.1
Server Version: v1.36.0-alpha.2.435+0009958799e560
```

</details>

### Cloud provider

<details>
Local kind cluster
</details>

### OS version

Kind node:
<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux kind-control-plane 6.17.0-1008-azure #8~24.04.1-Ubuntu SMP Mon Jan 26 18:35:40 UTC 2026 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```
% kind version
kind v0.31.0 go1.26.1 linux/amd64
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
DRA Example Driver v0.2.1
</details>

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

#137647 made it possible for pending DRA allocations to be shared among several scheduling Pods. @pohly [pointed out](https://github.com/kubernetes/kubernetes/pull/137647#pullrequestreview-3973552467) a few issues with the approach there after it was merged. This PR addresses that feedback.

- Pending claims and the count are now tracked in the same map protected by a single `sync.RWMutex`
- The API has been simplified.
  - The functionality from RemoveSharedClaimPendingAllocation is now built in to MaybeRemoveClaimPendingAllocation, so separate method is needed
  - The `claimUID` parameter for AddSharedClaimPendingAllocation has been removed and the UID of the `allocatedClaim` is used instead.

#### Which issue(s) this PR is related to:

Fixes #137617

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go
Comment (nojnhuh) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:1]: I'm wondering if it's worth making the sharable pending allocations use a totally parallel implementation so it more obviously doesn't affect existing usage. Kind of like the experimental/incubating/stable allocators.

File: pkg/scheduler/framework/autoscaler_contract/lister_contract_test.go [hunk 1]
```diff
@@ -152,6 +152,10 @@ func (r *resourceClaimTrackerContract) SignalClaimPendingAllocation(_ types.UID,
 	return nil
 }
 
+func (r *resourceClaimTrackerContract) AddSharedClaimPendingAllocation(allocatedClaim *resourceapi.ResourceClaim) error {
```
Comment (pohly) [inline pkg/scheduler/framework/autoscaler_contract/lister_contract_test.go]: I know I suggested removing the UID parameter, but as I compare this now with `SignalClaimPendingAllocation` I wonder whether consistency trumps simplicity: `SignalClaimPendingAllocation` also has a separate UID parameters when, strictly speaking, it shouldn't need one.

Maybe add it back?

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:1]: It doesn't seem too bad, i.e. doesn't justify the overhead of forking the code. Just don't introduce any bugs 😜

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 2]
```diff
@@ -214,65 +224,41 @@ func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocate
...
+	inFlight, found := c.inFlightAllocations[claimUID]
 	// The assume cache doesn't log this, but maybe it should.
 	if found {
-		claim := claim.(*resourceapi.ResourceClaim)
-		c.logger.V(5).Info("Removed in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion)
+		claim := inFlight.claim
+		inFlight.sharers--
+		if shareable && inFlight.sharers > 0 {
+			c.inFlightAllocations[claimUID] = inFlight
+			c.logger.V(5).Info("Claim is still shared by other pods, not removing in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion, "sharers", inFlight.sharers)
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Suppose the allocation was stored successfully in the claim and thus in the assume cache. Should it remain in-flight? Probably not. If (for whatever reason) the claim gets deallocated while the in-flight entry still exists, we keep the device blocked longer (best case) or tentatively use it for other when it's already gone (should get resolved during PreBind failing to add ReservedFor, but still).

Maybe add a "force" parameter that instructs this code to remove the in-flight claim even if shared? This must be used only in the case above (successfully stored).

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: I suppose we could get the same result by simply setting `shareable` to false in that case, regardless of whether or not we're scheduling a PodGroup. If we rename that flag something like `keepSharedAllocations` could we use that for both purposes (toggling PodGroup/non-PodGroup behavior and force-overwriting on success)?

File: pkg/scheduler/framework/autoscaler_contract/lister_contract_test.go (hunk 1 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/autoscaler_contract/lister_contract_test.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 2 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Made this change in the second commit here.

/hold for squash

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 3]
```diff
@@ -454,9 +454,22 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
...
 			if pendingAllocation, found := pl.draManager.ResourceClaims().GetPendingAllocation(claim.UID); found {
 				allocation = pendingAllocation
+
+				// Inform the tracker that this pod still needs the pending
+				// allocation. Then PreBind or Unreserve can know whether or not
+				// it's safe to remove the pending allocation.
+				//
+				// Extended resources claims cannot be shared, so we never
+				// signal sharing for it.
+				if err := pl.draManager.ResourceClaims().AddSharedClaimPendingAllocation(claim.UID, claim); err != nil {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: We Read and Write without holding a lock here, so it's also a place where it can fail to write (as it assumes it's just need to increment the counter)?

I imagine we could do it in the following flow:
- In PreFilter we just read pending allocation and use for the rest of the process
- In SignalClaimPendingAllocation (Reserve) we either write the 1st allocation or increment the counter if allocations were the same
- In PreBinding / Unreserve we decrement or remove allocation

I wouldn't distinguish the Signal (in Reserve) from Add (in PreFilter), unless there are some reasons I don't see now. I know that the small difference is that allocation may be released and re-acquired, but no other Pod could be able to use it in the meantime, as we're during the scheduling cycle.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 4]
```diff
@@ -186,25 +185,36 @@ type claimTracker struct {
 	// pods is expected to be rare compared to per-pod claim, so we end up
 	// hitting the "multiple goroutines read, write, and overwrite entries
 	// for disjoint sets of keys" case that sync.Map is optimized for.
-	inFlightAllocations *sync.Map
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:218]: IIIUC we still could use `sync.Map` which hold both the claim and counter (it should work faster), but I'm fine with mutex as well.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:218]: The `sync.Map` protects only during the access to the map, not while some code is working with the result of the lookup.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 5]
```diff
@@ -331,14 +317,15 @@ func (c *claimTracker) ListAllAllocatedDevices() (a sets.Set[structured.DeviceID
 	allocated, revision := c.allocatedDevices.Get()
 
 	// Whatever is in flight also has to be checked.
-	c.inFlightAllocations.Range(func(key, value any) bool {
-		claim := value.(*resourceapi.ResourceClaim)
+	c.inFlightMutex.RLock()
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Can you move it into a separate function to be able to release lock using defer?

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 6]
```diff
@@ -404,8 +391,9 @@ func (c *claimTracker) GatherAllocatedState() (s *structured.AllocatedState, err
 	}
 
 	// Whatever is in flight also has to be checked.
-	c.inFlightAllocations.Range(func(key, value any) bool {
-		claim := value.(*resourceapi.ResourceClaim)
+	c.inFlightMutex.RLock()
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Same here

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 7]
```diff
@@ -213,66 +223,42 @@ func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocate
...
 
-	claim, found := c.inFlightAllocations.LoadAndDelete(claimUID)
+	inFlight, found := c.inFlightAllocations[claimUID]
 	// The assume cache doesn't log this, but maybe it should.
 	if found {
-		claim := claim.(*resourceapi.ResourceClaim)
-		c.logger.V(5).Info("Removed in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion)
+		claim := inFlight.claim
+		inFlight.sharers--
+		if keepSharedAllocations && inFlight.sharers > 0 {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Do we need `keepSharedAllocations` at all? Cannot we assume that the number of Signals and Remove will be the same in the legacy case?

Signal operation cannot fail, but only Remove when the Claim is no longer available. It can happen only when it was deleted, so the map entry is not useful anymore anyway.

In such case `keepSharedAllocations` will become `forceRemove`

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 3 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > We Read and Write without holding a lock here, so it's also a place where it can fail to write (as it assumes it's just need to increment the counter)?

AddSharedClaimPendingAllocation is wrapped with the same lock as Signal and MaybeRemove, or are you talking about a different lock?


> * In AddSharedClaimPendingAllocation (Reserve) we either write the 1st allocation or increment the counter if allocations were the same

Right now AddSharedClaimPendingAllocation is only called for unallocated claims, and reusing the pending allocation here effectively treats the claim as allocated. Is there a reasonable way to refactor Reserve to include calling Signal for all claims without doing too much unnecessary work?

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: `AddSharedClaimPendingAllocation` assumes there is a pending allocation, but `GetPendingAllocation` was called earlier and `inFlightMutex` was released in the meantime.

It's ok to leave it as is, but we should Get and Add in the same call to keep the lock, for instance in `AcquireSharedClaimPendingAllocation`

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 7 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Without `keepSharedAllocations` can we still accommodate @pohly's concern from https://github.com/kubernetes/kubernetes/pull/137897#discussion_r2961564936? Is it possible that we'd want to remove the pending allocation even if some Pods are still using it if it's successfully stored in the AssumeCache?

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Or are you suggesting only to change the name to `forceRemove` and invert the semantics?

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Yes, if we count unconditionally (without sharing only to 1), then the semantic of this argument reduces to a boolean `forceRemove`.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 3 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Ah, makes sense. I've brought back `ClaimHasPendingAllocation` and now `GetPendingAllocation` will both increment the counter and return the allocation all while holding the lock.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 5 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: I added a new wrapper method that should be able to accommodate both.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 7 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Makes sense, updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 8]
```diff
@@ -186,25 +185,50 @@ type claimTracker struct {
...
+	_, found := c.inFlightAllocations[claimUID]
+	return found
 }
 
-func (c *claimTracker) GetPendingAllocation(claimUID types.UID) (*resourceapi.AllocationResult, bool) {
-	var allocation *resourceapi.AllocationResult
-	claim, found := c.inFlightAllocations.Load(claimUID)
-	if found && claim != nil {
-		allocation = claim.(*resourceapi.ResourceClaim).Status.Allocation
+func (c *claimTracker) GetPendingAllocation(claimUID types.UID) *resourceapi.AllocationResult {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: I'd still suggest a different name than Get, since it does something more and it should be denoted clearly. Typically we could use `Claim...`, but that would be confusing with ResourceClaim. That's why I suggested `Acquire`, but a similar name should work as well.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 9]
```diff
@@ -186,25 +185,50 @@ type claimTracker struct {
...
 }
 
 func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error {
-	c.inFlightAllocations.Store(claimUID, allocatedClaim)
+	c.inFlightMutex.Lock()
+	defer c.inFlightMutex.Unlock()
+
+	c.inFlightAllocations[claimUID] = inFlightAllocation{
+		claim:   allocatedClaim,
+		sharers: 1,
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Am I correct that Signal will be called for all pods in the `Reserve` phase?

If so, then we'd reset the counter to 1 even though it might be one of the shared allocations. Shouldn't we skip it when in flight allocation already exists?

We should have a unit test covering this case.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 10]
```diff
@@ -186,25 +185,50 @@ type claimTracker struct {
...
+	newInFlight := inFlight
+	newInFlight.sharers++
+	c.inFlightAllocations[claimUID] = newInFlight
+	claim := newInFlight.claim
+
+	c.logger.V(5).Info("Added share for in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion, "sharers", newInFlight.sharers)
+	return claim.Status.Allocation
 }
 
 func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:240]: Signal cannot return any error, so consider removing it.

**Review by dom4ha — COMMENTED** [review]
I look better now.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 8 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Ah I missed that. I like `Acquire`, I'll change to that.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 10 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:240]: The comment there explains the reason for returning the error:
https://github.com/kubernetes/kubernetes/blob/3b0b8a6b9074ed3037b5a81209cb762b60cb9b5b/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go#L234-L237

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Based on logs from running the 20-Pod gang scheduling integration test, I see Signal only once for the first Pod in the group. Subsequent Pods skip Signal in Reserve because an allocator is never set up for them in PreFilter since the pending allocation is found.

https://github.com/kubernetes/kubernetes/blob/8380b0dc851548a1642b5641a3ea7ed4e36ff551/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L998-L999

It seems like those Pods should instead be following this path, like pods that are reusing an existing non-in-flight claim:
https://github.com/kubernetes/kubernetes/blob/8380b0dc851548a1642b5641a3ea7ed4e36ff551/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L970-L976

They don't because `state.claims` doesn't update based on in-flight claims. Do we need to check in-flight claims there?

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 11]
```diff
@@ -186,25 +186,50 @@ type claimTracker struct {
...
-	var allocation *resourceapi.AllocationResult
-	claim, found := c.inFlightAllocations.Load(claimUID)
-	if found && claim != nil {
-		allocation = claim.(*resourceapi.ResourceClaim).Status.Allocation
+func (c *claimTracker) AcquirePendingAllocation(claimUID types.UID) *resourceapi.AllocationResult {
+	c.inFlightMutex.Lock()
+	defer c.inFlightMutex.Unlock()
+
+	inFlight, found := c.inFlightAllocations[claimUID]
+	if !found || inFlight.claim.Status.Allocation == nil {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: The old code was checking the map entry for nil. That may have been just a precaution.

Now the code doesn't check the claim pointer anymore and instead checks the allocation, which is different. I think it's okay, `ListAllAllocatedDevices` doesn't check for nil claim either.

A comment about whether the `Allocation` really can be nil would be good.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 12]
```diff
@@ -186,25 +186,50 @@ type claimTracker struct {
...
+		return nil
 	}
-	return allocation, found
+
+	newInFlight := inFlight
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: No need for a new variable here and the name is confusing: it's not actually new, it was already created earlier.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 10 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:240]: This is the problem with interfaces: one has to consider all possible implementations. Several interfaces in Kubernetes lack a `context.Context` because the "main" implementation is local and simple. That works until someone adds an implementation which does long-running, blocking API calls...

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 13]
```diff
@@ -213,67 +238,27 @@ func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocate
...
-			// The value must have changed since we loaded
-			return fmt.Errorf("conflict adding in-flight allocation sharer for claim %s/%s, UID=%s", allocatedClaim.Namespace, allocatedClaim.Name, claimUID)
+		claim := inFlight.claim
+		inFlight.sharers--
+		if !forceRemove && inFlight.sharers > 0 {
+			c.inFlightAllocations[claimUID] = inFlight
+			c.logger.V(5).Info("Claim is still shared by other pods, not removing in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion, "sharers", inFlight.sharers)
+		} else {
+			delete(c.inFlightAllocations, claimUID)
+			deleted = true
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: There may have been a reason to have `deleted bool` as a named result (maybe some deferred logging?) but now this is not needed anymore.

You can remove it and flatten the entire function:
```Go
if !found {
    c.logger.V(5).Info("Redundant remove of in-flight claim, not found", "uid", claimUID)
   return false
}
if !forceRemove && inFlight.sharers > 0 {
    ...
    return false
}
delete ...

return true
```

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 14]
```diff
@@ -435,6 +422,12 @@ func (c *claimTracker) GatherAllocatedState() (s *structured.AllocatedState, err
 	return nil, errClaimTrackerConcurrentModification
 }
 
+func (c *claimTracker) withInFlightRLock(cb func()) {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: A better pattern would be to use Go iterators. Then the caller can do `for inFlight := c.allInFlightAllocationsRLocked(() {
}`, which avoids changing the indention.

Like this:
```patch
diff --git a/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go b/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go
index de37cab4ae5..b9d53696ecc 100644
--- a/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go
+++ b/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go
@@ -20,6 +20,7 @@ import (
 	"context"
 	"errors"
 	"fmt"
+	"iter"
 	"slices"
 	"sync"
 
@@ -316,15 +317,13 @@ func (c *claimTracker) ListAllAllocatedDevices() (a sets.Set[structured.DeviceID
 	allocated, revision := c.allocatedDevices.Get()
 
 	// Whatever is in flight also has to be checked.
-	c.withInFlightRLock(func() {
-		for _, inFlight := range c.inFlightAllocations {
-			claim := inFlight.claim
-			foreachAllocatedDevice(claim, func(deviceID structured.DeviceID) {
-				c.logger.V(6).Info("Device is in flight for allocation", "device", deviceID, "claim", klog.KObj(claim))
-				allocated.Insert(deviceID)
-			}, false, func(structured.SharedDeviceID) {}, func(structured.DeviceConsumedCapacity) {})
-		}
-	})
+	for _, inFlight := range c.allInFlightAllocationsRLocked() {
+		claim := inFlight.claim
+		foreachAllocatedDevice(claim, func(deviceID structured.DeviceID) {
+			c.logger.V(6).Info("Device is in flight for allocation", "device", deviceID, "claim", klog.KObj(claim))
+			allocated.Insert(deviceID)
+		}, false, func(structured.SharedDeviceID) {}, func(structured.DeviceConsumedCapacity) {})
+	}
 
 	if revision == c.allocatedDevices.Revision() {
 		// Our current result is valid, nothing changed in the meantime.
@@ -390,25 +389,23 @@ func (c *claimTracker) GatherAllocatedState() (s *structured.AllocatedState, err
 	}
 
 	// Whatever is in flight also has to be checked.
-	c.withInFlightRLock(func() {
-		for _, inFlight := range c.inFlightAllocations {
-			claim := inFlight.claim
-			foreachAllocatedDevice(claim,
-				func(deviceID structured.DeviceID) { // dedicatedDeviceCallback
-					c.logger.V(6).Info("Device is in flight for allocation", "device", deviceID, "claim", klog.KObj(claim))
-					allocated.Insert(deviceID)
-				},
-				enabledConsumableCapacity,
-				func(sharedDeviceID structured.SharedDeviceID) { // sharedDeviceCallback
-					c.logger.V(6).Info("Device is in flight for allocation", "shared device", sharedDeviceID, "claim", klog.KObj(claim))
-					allocatedSharedDeviceIDs.Insert(sharedDeviceID)
-				},
-				func(capacity structured.DeviceConsumedCapacity) { // consumedCapacityCallback
-					c.logger.V(6).Info("Device is in flight for allocation", "consumed capacity", capacity, "claim", klog.KObj(claim))
-					aggregatedCapacity.Insert(capacity)
-				})
-		}
-	})
+	for _, inFlight := range c.allInFlightAllocationsRLocked() {
+		claim := inFlight.claim
+		foreachAllocatedDevice(claim,
+			func(deviceID structured.DeviceID) { // dedicatedDeviceCallback
+				c.logger.V(6).Info("Device is in flight for allocation", "device", deviceID, "claim", klog.KObj(claim))
+				allocated.Insert(deviceID)
+			},
+			enabledConsumableCapacity,
+			func(sharedDeviceID structured.SharedDeviceID) { // sharedDeviceCallback
+				c.logger.V(6).Info("Device is in flight for allocation", "shared device", sharedDeviceID, "claim", klog.KObj(claim))
+				allocatedSharedDeviceIDs.Insert(sharedDeviceID)
+			},
+			func(capacity structured.DeviceConsumedCapacity) { // consumedCapacityCallback
+				c.logger.V(6).Info("Device is in flight for allocation", "consumed capacity", capacity, "claim", klog.KObj(claim))
+				aggregatedCapacity.Insert(capacity)
+			})
+	}
 
 	if revision1 == c.allocatedDevices.Revision() {
 		// Our current result is valid, nothing changed in the meantime.
@@ -422,10 +419,16 @@ func (c *claimTracker) GatherAllocatedState() (s *structured.AllocatedState, err
 	return nil, errClaimTrackerConcurrentModification
 }
 
-func (c *claimTracker) withInFlightRLock(cb func()) {
-	c.inFlightMutex.RLock()
-	defer c.inFlightMutex.RUnlock()
-	cb()
+func (c *claimTracker) allInFlightAllocationsRLocked() iter.Seq2[types.UID, inFlightAllocation] {
+	return func(yield func(types.UID, inFlightAllocation) bool) {
+		c.inFlightMutex.RLock()
+		defer c.inFlightMutex.RUnlock()
+		for uid, inFlight := range c.inFlightAllocations {
+			if !yield(uid, inFlight) {
+				return
+			}
+		}
+	}
 }
 
 func (c *claimTracker) AssumeClaimAfterAPICall(claim *resourceapi.ResourceClaim) error {
```

File: staging/src/k8s.io/kube-scheduler/framework/listers.go [hunk 15]
```diff
@@ -106,23 +106,19 @@ type ResourceClaimTracker interface {
 	// SignalClaimPendingAllocation signals to the tracker that the given ResourceClaim will be allocated via an API call in the
 	// binding phase. This change is immediately reflected in the result of List() and the other accessors.
 	SignalClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error
-	// GetPendingAllocation answers whether a given claim has a pending allocation during the binding phase. It can be used to avoid
+	// ClaimHasPendingAllocation answers whether a given claim has a pending allocation during the binding phase. It can be used to avoid
 	// race conditions in subsequent scheduling phases.
-	GetPendingAllocation(claimUID types.UID) (*resourceapi.AllocationResult, bool)
+	ClaimHasPendingAllocation(claimUID types.UID) bool
```
Comment (pohly) [inline staging/src/k8s.io/kube-scheduler/framework/listers.go]: The non-PodGroup case still uses this. If this approach with sharer counting works out okay, we could drop that restriction and remove this method, right?

In other words, always allow sharing the in-flight claim?

Maybe file a tracking issue for following up?

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 11 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: I added a check for `inFlight` to at least avoid panicking there. Also updated the comment in the interface for `SignalClaimPendingAllocation`.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 12 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 13 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Updated.

File: staging/src/k8s.io/kube-scheduler/framework/listers.go (hunk 15 above)
Comment (nojnhuh) [reply staging/src/k8s.io/kube-scheduler/framework/listers.go]: Yeah, whatever we figure out for PodGroups could work in the normal case.

Opened https://github.com/kubernetes/kubernetes/issues/137932.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 14 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I think calling SignalClaimPendingAllocation only once is consistent. The other pods then do AcquirePendingAllocation.

What I am not sure about based on the discussion above is this: suppose the first pod creates the in-flight claim. A second pod gets scheduled before the first one updates the claim. First pod fails to update the claim.

Does the second pod in PreBind then know that it needs to try again to write the status?

Definitely worth a unit test.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I think PreBind for the second Pod will fail when it tries to update the ResourceClaim status if the claim's allocation is nil since that fails validation.

> Does the second pod in PreBind then know that it needs to try again to write the status?

Do you mean a retry within PreBind like the existing `RetryOnConflict` block or in a subsequent binding attempt orchestrated by the higher-level scheduling framework? Is returning an error from PreBind enough to generally trigger a retry?

I'll try to come up with a unit test.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: With that I meant test cases in  dynamicresources_test.go that cover the whole flow, not just unit tests for the individual functions. I don't see anything added there as part of https://github.com/kubernetes/kubernetes/pull/137647, let's fix that.

We need, for pods in a pod group:
- pod is the first to allocate a claim.
- second pod with claim in flight
- second pod with claim in assume cache

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I think each pod in the pod group which reaches PreBind must try to store the allocation. This may imply retrying in case of a conflict.

If we don't do this, we could have:
- Pod A  puts claim in flight.
- Pod B sees in-flight claim, proceeds to PreBind *before* Pod A updates the status.
- Pod B tries to add ReservedFor and fails.

We want scheduling of the pods in the pod group to succeed, no matter in which order their PreBind methods are called.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: > With that I meant test cases in dynamicresources_test.go that cover the whole flow

That's what I feared 🙂. The PodGroup scheduling flow is pretty different so I'll try to come up with something like `TestPlugin` that works on multiple pods.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Alternatively you can write an integration test. You could copy https://github.com/kubernetes/kubernetes/blob/69d4f67bc45781c44e4bf90331647db22883202e/test/integration/dra/resourceclaim.go#L35-L177 and change it so that the pods are in a pod group sharing the same claim.

That also gives us confidence that each plugin extension point works as expected. That doesn't simulate failures to store claim status - or at least not easily.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I did add integration tests with the first PR: https://github.com/kubernetes/kubernetes/blob/69d4f67bc45781c44e4bf90331647db22883202e/test/integration/dra/pod_group.go#L29

They work, but based on the logs things could go smoother. Better than generating millions of events and not scheduling any pods though.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I'll let you and @dom4ha come to a conclusion here, as you were also the ones originally discussing it.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 16]
```diff
@@ -213,67 +238,29 @@ func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocate
...
-		newSharers = oldSharers + 1
-		swapped := c.inFlightAllocationSharers.CompareAndSwap(claimUID, oldSharers, newSharers)
-		if !swapped {
-			// The value must have changed since we loaded
-			return fmt.Errorf("conflict adding in-flight allocation sharer for claim %s/%s, UID=%s", allocatedClaim.Namespace, allocatedClaim.Name, claimUID)
-		}
+	// The assume cache doesn't log this, but maybe it should.
+	claim := inFlight.claim
+	inFlight.sharers--
+	if !forceRemove && inFlight.sharers > 0 {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Consider also reverting the order and handle `forceRemove` case first:
```
if forceRemove || inFlight.sharers == 1 {
  ...
  return false
}
inFlight.sharers--
...
```

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 17]
```diff
@@ -59,9 +60,9 @@ func NewDRAManager(ctx context.Context, claimsCache *assumecache.AssumeCache, re
 	manager := &DefaultDRAManager{
 		resourceClaimTracker: &claimTracker{
 			cache:               claimsCache,
-			inFlightAllocations: &sync.Map{},
 			allocatedDevices:    newAllocatedDevices(logger),
 			logger:              logger,
+			inFlightAllocations: make(map[types.UID]inFlightAllocation),
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Nit. Can you move it to its original position?

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Note that the problem we're trying to solve is multi-layer:
1. Scheduling Pods within a PodGroup in a single cycle
2. Re-scheduling the same PodGroups across many scheduling cycles (mainly Basic gang smaller minCount)
3. Scheduling different Pods (sharing the same Claim) across different cycles
4. Scheduling different PodGroups (sharing the same Claim) across different cycles

We need to solve the case 1, but we ended up solving all other case 2 - 4. This is fine as the difference between them is not big, as even in the case 1 we still have sync (PreFilter, Reserve, Unreserve) and async (Bind, Unreserve) phases. But the question is whether we want to worry about the allocations crafted in the previous cycle which haven't bound yet (or fail binding)?

I'm fine with focusing on case 1 entirely as it guarantees that the first Reserve (Signal) does not race with any Unreserve of the previous cycle (on failed binding). It also reduces the number of tests we need to have (the existing one cover case 1 only).

To achieve that, we just need to detect whether pods schedule with the same cycle or not. Not sure if we expose the cycle number to the plugins, but it should be doable. We still have async Binding, so:

> I think each pod in the pod group which reaches PreBind must try to store the allocation. This may imply retrying in case of a conflict.
> We want scheduling of the pods in the pod group to succeed, no matter in which order their PreBind methods are called.

Yes, I even assumed that we already have that. We should address that in this release. Note that in the next one I hope to introduce PodGroup binding phase, so the problem of async write (to api-server) will be addressed on the framework level.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Regarding detecting whether it's a single cycle, we don't have to capture cycle number, but we could use new PodGroup cycle state instead:

1. When the first pod goes into Reserve (and Signal), it can register allocation in the PodGroup cycle state.
2. When the second (and following) pods go into PreFilter, they can notice that allocation is DRA manager
3. If the information about allocation is also in the cycle state,
  3a. this means it belongs to this cycle and they can acquire it,
  3b. otherwise, they will become unschedulable (like today)

We still need to use `RetryOnConflict` for binding and try to bind the ResourceClaim by the first pod.

Effectively, this PR would change the behavior only for PodGroups, so it could become another commit of  https://github.com/kubernetes/kubernetes/pull/136989

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 16 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 17 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: @dom4ha Can the DynamicResources plugin access the PodGroup CycleState? I only see that passed to PlacementGeneratePlugins.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Yeah, that's true, only GeneratePlacements plugins receive it. Technically DRA plugin could implement that extension point as well (to learn when new PogGroup cycle starts), but unfortunately we explicitly allow one such plugin in 1.36 to not support merging two topologies yet:

https://github.com/kubernetes/kubernetes/blob/dd776ab4c5ed6b94389987f9bd3fe541e7711bd5/pkg/scheduler/framework/runtime/framework.go#L439

Cycle number is also not visible to plugins, so I'm afraid that we cannot detect scheduling cycle boundaries without changing how CycleState works. Potentially Pod state could expose PodGroups state, but that's a bigger change. @macsko @sanposhiho any ideas?

I'm afraid that we need to stick for now with cross cycle consequences. Let me think if there is anything specific we should worry about.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: On the other hand CycleState already has method informing pods whether it's PogGroup scheduling cycle, so exposing the PodGroup state should not be that big change then.

WDYT about changing `SetPodGroupSchedulingCycle(boo)` -> `SetPodGroupSchedulingCycle(PodGroupCycleState)` and adding `GetPodGroupSchedulingCycle()`?

https://github.com/kubernetes/kubernetes/blob/dd776ab4c5ed6b94389987f9bd3fe541e7711bd5/staging/src/k8s.io/kube-scheduler/framework/cycle_state.go#L99-L100

Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: > Potentially Pod state could expose PodGroups state

That sound good, and even looks like a cleaner approach for storing the single-cycle state for DRA.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Just pushed the changes to store pending claims in the PodGroup CycleState. Still trying to find a good way to make it so every Pod sharing the allocation tries to update the ResourceClaim status in PreBind.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 18]
```diff
@@ -1076,6 +1128,9 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
 		if deleted := pl.draManager.ResourceClaims().MaybeRemoveClaimPendingAllocation(claim.UID, false); deleted {
 			logger.V(5).Info("Released resource in allocation result", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion, "allocation", klog.Format(claim.Status.Allocation))
 			pl.draManager.ResourceClaims().AssumedClaimRestore(claim.Namespace, claim.Name)
+			if podGroupState != nil {
+				podGroupState.pendingAllocations.Delete(claim.UID)
```
Comment (nojnhuh) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1289]: If we make changes to this set stored in the PodGroup CycleState in Unreserve, do we need to protect it with a mutex? The race detector doesn't catch that for me in the integration tests if we do.

File: pkg/scheduler/schedule_one_podgroup.go [hunk 19]
```diff
@@ -464,7 +464,7 @@ func (sched *Scheduler) submitPodGroupAlgorithmResult(ctx context.Context, sched
 			switch {
 			case podGroupResult.status.IsSuccess():
 				// Disable pod group scheduling in cycle state before binding.
-				podCtx.state.SetPodGroupSchedulingCycle(false)
+				podCtx.state.SetPodGroupSchedulingCycle(nil)
```
Comment (dom4ha) [inline pkg/scheduler/schedule_one_podgroup.go:534]: Note that we are clearing the PodGroup state here before binding. It's pretty useful as it allows us to conclude that whenever this state exists, it is updated synchronously (including sync Unreserve) and does not require locking.

However, once it's removed here, we know that we entered asynchronous binding, so whenever Unreserve is called, it is asynchronous version. Anyway, the downside is that this state is no longer available, so we need to take it into consideration.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 20]
```diff
@@ -1301,22 +1347,21 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
-				// Since several Pods may be sharing a claim with a pending
-				// allocation, make sure that we don't remove the pending
-				// allocation until the last Pod sharing it is Bound or Unreserved.
-				if pl.isSchedulingPodGroup(pod) {
-					if err := pl.draManager.ResourceClaims().RemoveSharedClaimPendingAllocation(claim.UID, claim); err != nil {
-						logger.Error(err, "unreserve", "resourceclaim", klog.KObj(claim))
-						continue
+				if deleted := pl.draManager.ResourceClaims().MaybeRemoveClaimPendingAllocation(claimUID, forceRemovePendingAllocation); deleted {
+					if podGroupState != nil {
+						podGroupState.pendingAllocations.Delete(claim.UID)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1532]: PodGroup state is no longer available in Binding (see my other comment).

However, once we're in binding, we no longer need to care as new cycle needs to start.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 18 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1289]: So if the podGroupState exists, it means it's synchronous version of Unreserve and locking is not necessary. So what we have here is correct, but I'd just comment why it's sync version.

If the state does not exist, we don't know whether it ever existed, but we also have a counter in `MaybeRemoveClaimPendingAllocation`. We will also start a new cycle anyway before we can start reusing pending allocations again.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 21]
```diff
@@ -1056,6 +1088,10 @@ func (pl *DynamicResources) Reserve(ctx context.Context, cs fwk.CycleState, pod
 			}
 			logger.V(5).Info("Reserved resource in allocation result", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion, "allocation", klog.Format(allocation))
 			allocIndex++
+
+			if podGroupState != nil {
+				podGroupState.pendingAllocations.Insert(claim.UID)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1243]: Don't we need to write podGroupState?

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: Forgive my vague understanding of the problem, but Isn't it enough to store allocator for every pod which reuses pending_allocation?

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I'm primarily trying to avoid adding a completely different path through the scheduler plugin for claims with pending allocations in addition to totally-allocated and totally-unallocated claims. Right now, the plugin treats claims with pending allocations more like allocated claims which skips steps like `SignalClaimPendingAllocation` in Reserve and updating the ResourceClaim status with the allocation in PreBind. The main thing we want to avoid with pending allocations is [recomputing the allocations](https://github.com/nojnhuh/kubernetes/blob/d4d1d9d181f05fb76223d9af1d561cf6cde8b65d/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L784).

To avoid breaking too many assumptions made by the plugin, I'm wondering if it might make sense to continue treating claims with pending allocations in PreFilter as "unallocated" and then [pass the allocator](https://github.com/nojnhuh/kubernetes/blob/d4d1d9d181f05fb76223d9af1d561cf6cde8b65d/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L604) a view of the pending allocations that it can use to short-circuit. Then the rest of the plugin can continue handling those as it normally does vs. checking for pending allocations separately from finished allocations.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 18 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1289]: Makes sense. I've explained that in a comment in both Unreserve and PreBind.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 21 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1243]: Since a pointer is stored in the CycleState, modifying the data through the pointer also modifies it in the CycleState. That's mentioned in a comment for the `stateData` type but I've added that for the `podGroupStateData` type too.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 9 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:256]: I think I got this working now where all the Pods will `SignalClaimPendingAllocation` in Reserve and all try to update the ResourceClaim status in PreBind with both the allocation and their `reservedFor` entry.

I'm reusing `informationForClaim.allocation` to store the pending allocation in PreFilter, then only sending the non-pending, unallocated claims to the allocator. Results are combined and stored in `stateData.nodeAllocations`. From there, the claim's with pending allocations are treated like any other unallocated claim.

I didn't root-cause the [current CI flakes](https://storage.googleapis.com/k8s-triage/index.html?text=TestDRA%2F%5Cw%2B%2FPodGroup&job=kubernetes-integration) but this definitely improves things for me locally:

Before: `19m10s: 1003 runs so far, 11 failures (1.10%), 12 active`
After: `23m35s: 1045 runs so far, 0 failures, 12 active`

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 22]
```diff
@@ -812,13 +870,18 @@ func (pl *DynamicResources) Filter(ctx context.Context, cs fwk.CycleState, pod *
...
+				}
+			}
 			nodeAllocatableClaimStatus, status = pl.calculateAndCheckNodeAllocatableResources(ctx, state, pod, nodeInfo, allocationsMap)
 			if status != nil {
 				return status
 			}
 		}
 		// Reserve uses this information.
-		allocations = allocationResult
+		allocations = append(allocationResult, pendingResult...)
```
Comment (nojnhuh) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:898]: > ERROR: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:884:17: appendAssign: append result not assigned to the same slice (gocritic)
> ERROR: 		allocations = append(allocationResult, pendingResult...)

This is intentional. Is there a better way to write this?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:898]: You could first update allocation result, then store in allocation.

But as it's intentional, I'd  ignore the hint.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 21 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1243]: It's preferred to do deep copy, especially since we don't need synchronization (we thought about it initially). But for me it's a nit and we can keep it this way.

**Review by dom4ha — COMMENTED** [review]
LGTM from scheduler perspective @sanposhiho @macsko to confirm whether I haven't missed anything.

Overall I think that the changes are safe wrt breaking any existing functionality considering that the logic triggers only when we have podGroupState (GenericWorkload enabled) AND ResourceClaim shared between pods in a PodGroup. Sharing ResourceClaim between cycles (by individual pods) works like before.

Waiting for lgtm from @pohly from the DRA POV.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go [hunk 23]
```diff
@@ -3884,10 +3884,11 @@ func (tc *testContext) listAssumedClaims() ([]metav1.Object, []metav1.Object) {
 
 func (tc *testContext) listInFlightClaims() []metav1.Object {
 	var inFlightClaims []metav1.Object
-	tc.draManager.resourceClaimTracker.inFlightAllocations.Range(func(key, value any) bool {
-		inFlightClaims = append(inFlightClaims, value.(*resourceapi.ResourceClaim))
-		return true
-	})
+	tc.draManager.resourceClaimTracker.inFlightMutex.RLock()
+	for _, inFlight := range tc.draManager.resourceClaimTracker.inFlightAllocations {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Nit: can't this use the new `allInFlightAllocationsRLocked`?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 24]
```diff
@@ -503,10 +516,24 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
...
+			// succeed through the Reserve phase, then binding all of the Pods.
+			// Since a claim's allocation is not recorded in [stateData.claims]
+			// until PreBind, we look for a pending allocation made in Reserve
+			// here to avoid blocking this Pod on waiting for the allocation to
+			// complete.
+			if podGroupState != nil && podGroupState.pendingAllocations.Has(claim.UID) {
+				if pendingAllocation := pl.draManager.ResourceClaims().GetPendingAllocation(claim.UID); pendingAllocation != nil {
+					s.informationsForClaim[index].allocation = pendingAllocation
+					logger.V(5).Info("reusing pending allocation", "pod", klog.KObj(pod), "resourceclaim", klog.KObj(claim), "uid", claim.UID, "allocation", klog.Format(pendingAllocation))
+					continue
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:543]: This occurs after `numClaimsToAllocate++` which at first glance is odd because it doesn't really need to be allocated anymore. 

I think this is intentional because it keeps the rest of the flow more or less as before, but a source code comment explaining this and the next step for this claim would be good here.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 25]
```diff
@@ -503,10 +516,24 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
 		} else {
 			numClaimsToAllocate++
 
+			// Gang scheduling works by waiting for all Pods in a gang to
+			// succeed through the Reserve phase, then binding all of the Pods.
+			// Since a claim's allocation is not recorded in [stateData.claims]
+			// until PreBind, we look for a pending allocation made in Reserve
+			// here to avoid blocking this Pod on waiting for the allocation to
+			// complete.
+			if podGroupState != nil && podGroupState.pendingAllocations.Has(claim.UID) {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:539]: This seems to be the one place where it matters whether we a) have a `podGroupState` and b) whether the claim is pending allocation.

I get that we only want to do this for pods in a pod group, to limit the scope for now. Long term we could do the same for all pods sharing an in-flight claims.

But why do we need `pendingAllocations`? Isn't that something that we can directly check via `GetPendingAllocation`?

In other words, could we eliminate `pendingAllocations`? If it is not needed now and is only preparing for some future change, then let's not add it in this PR.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:539]: The `pendingAllocations` in PodGroup state allows us to detect that the allocation is pending for this particular cycle, as cycle number is not exposed to the plugins. So without it we cannot limit the scope of the change.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:539]: I've added a note about this in https://github.com/kubernetes/kubernetes/issues/137932.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:539]: So you want to limit the scope of scheduling pods in parallel when they share a ResourceClaim to pods currently meant to be scheduled together - makes sense. But please also put it into the source code as a comment.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go (hunk 23 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: It can, updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 24 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:543]: Added in a comment.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 25 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:539]: Added in a comment.

**Comment by nojnhuh** [comment]
> @nojnhuh : please squash into a single commit.

I'll squash once this has LGTM and I'll push a zero-diff to keep the label.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 26]
```diff
@@ -522,6 +522,20 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
 			// until PreBind, we look for a pending allocation made in Reserve
 			// here to avoid blocking this Pod on waiting for the allocation to
 			// complete.
+			//
+			// Claims with pending allocations are considered "unallocated" in
+			// that the claim's Status.Allocation needs to be populated. Claims
+			// with pending allocations are not input to the allocator, though
+			// we numClaimsToAllocate increment to create an allocator anyway to
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:529]: Nit: "we increment numClaimsToAllocate".

English a difficult language is. 😜 

I don't care about fixing this. If this is the only thing, then don't bother loosing the LGTM over it.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:529]: This "allocator exists" is a left-over from when it was possible to allocate through classic DRA. We probably can clean this up and simplify the code, but this is something for 1.37.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 27]
```diff
@@ -522,6 +522,20 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
...
+			// signal that some claims need their status updated in PreBind.
+			//
+			// Currently, sharing is limited to a single PodGroup scheduling
+			// cycle. Ungrouped Pods and Pods across different PodGroup
+			// scheduling cycles cannot share claims with pending allocations
+			// for now to limit potential impact outside of the alpha
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:535]: 👍

**Review by pohly — COMMENTED** [review]
/approve
/lgtm

I understand the DRA plugin changes and trust that https://github.com/kubernetes/kubernetes/pull/137897#pullrequestreview-3997247506 and https://github.com/kubernetes/kubernetes/pull/137897#issuecomment-4116861269 have considered the overall impact for PodGroup support.

/hold

For squashing.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 26 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:529]: > Nit: "we increment numClaimsToAllocate".
> 
> English a difficult language is. 😜

I continue to surprise myself with these things. I'll leave it for now but if I need to push again I'll make this change.
