### PR TITLE
Validate Service.Spec.publicIPs to be a valid IP that is not a localhost

### LINKED ISSUE #5319: 0.0.0.0 and 127.0.0.1 should be rejected as a  publicIP fields for kube services.
When spinning up VMs w/ kube, I attempted to use `publicIPs=["0.0.0.0"]` but this fails.

ironically, 127.0.0.1 succeeds (internally you can then access a kube service via `curl 127.0.0.1:3000`, for example, but you *cannot* do this if you try to bind to 0.0.0.0.

- binding works to 127.0.0.1, but is a horrible idea (since this IP wont be reachable by the outside world), so in that case kube should print a clear message on *why* this is the case and fail. 
- binding to 0.0.0.0 fails right out of the bat, so in this case, also, kube should fail immediately.

To be clear, im suggesting that these should fail at the service submission layer.

Possibly a module for validating logic of submitted services/pods , which extends syntactical validation is in order if one doesn't already exist?

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This fixes #5319

### CODE REVIEW

File: pkg/api/validation/validation.go [hunk 1]
```diff
@@ -731,6 +731,14 @@ func ValidateService(service *api.Service) errs.ValidationErrorList {
 		allErrs = append(allErrs, errs.NewFieldNotSupported("spec.sessionAffinity", service.Spec.SessionAffinity))
 	}
 
+	for _, ip := range service.Spec.PublicIPs {
+		if !util.IsValidIP(ip) || ip == "0.0.0.0" {
+			allErrs = append(allErrs, errs.NewFieldInvalid("spec.publicIPs", ip, "is not an IP address"))
+		} else if ip == "127.0.0.1" {
```
Comment (thockin) [inline pkg/api/validation/validation.go]: How about 

```
if net.ParseIP(ip).IsLoopback() 
```

Being loopback is more than just 127.0.0.1.

In fact, http://golang.org/pkg/net/#ParseIP has a bunch of conditions that are probably worth checking.  Maybe

```
if !net.ParseIP(ip).IsGlobalUnicast() {
```

Comment (fgrzadkowski) [inline pkg/api/validation/validation.go]: That simplifies logic a lot! Thanks!

Regarding IsGlobalUnicast() - isn't it only for IPv6 which we don't support anyway? IsValidIP returns true only for IPv4 addresses.

**Comment by fgrzadkowski** [comment]
New version pushed and synced to HEAD.

**Comment by gust1n** [comment]
Isn't publicIPs supposed to be string to support AWS load balancer (ELB) which is a hostname and not an actual IP? 
#5228 @justinsb

**Comment by fgrzadkowski** [comment]
@gust1n @justinsb Thanks for linking PR. I haven't noticed it. In that case I'll just check if it's not 0.0.0.0 or a loopback.

**Comment by fgrzadkowski** [comment]
Ping.

**Comment by quinton-hoole** [comment]
LGTM - but needs a rebase before merge please.

**Comment by fgrzadkowski** [comment]
Rebased.

File: pkg/util/validation.go [hunk 2]
```diff
@@ -94,3 +95,8 @@ func IsCIdentifier(value string) bool {
 func IsValidPortNum(port int) bool {
 	return 0 < port && port < 65536
 }
+
+// IsValidIP tests that the argument is a valid IPv4 address.
+func IsValidIP(value string) bool {
```
Comment (gmarek) [inline pkg/util/validation.go]: Can you rename it to IsValidIPv4, to make it more explicit.

Comment (fgrzadkowski) [inline pkg/util/validation.go]: To be honest I'd prefer to keep the name as is, because from k8s perspective this verifies whether it's a valid IP (because k8s works only for v4).
