### PR TITLE
fix immediate evict in cache

### LINKED ISSUE #24163: util cache entry can self evict during add()
cacheShard.add() adds the new entry (or updates the existing one) before the eviction, in the case that the shard is full.  Because of the nature of how the eviction entry is chosen (random, yuck), the entry we just added can be evicted.  This results in the add() call returning with the added entry not in the cache.

### PR DESCRIPTION
**Pull request by sjenning**
Fixes #24163

Also adds a minimum cache size check.

### CODE REVIEW

File: pkg/util/cache/cache.go [hunk 1]
```diff
@@ -27,6 +27,9 @@ const (
 type Cache []*cacheShard
 
 func NewCache(maxSize int) Cache {
+	if maxSize < shardsCount {
```
Comment (lavalamp) [inline pkg/util/cache/cache.go]: You added this because it was making a size-0 shard, I guess? I think the better thing to do is to make the shard count not be fixed at 32, that seems really weird. I'm not sure what this cache is used for, though.

Comment (lavalamp) [inline pkg/util/cache/cache.go]: At any rate, silently returning nil here is not good, it will make the error show up as a crash and not as a construction error. Since no one is checking the result of this to see if it's nil.

File: pkg/util/cache/cache.go [hunk 2]
```diff
@@ -61,14 +64,14 @@ func (s *cacheShard) add(index uint64, obj interface{}) bool {
 	s.Lock()
 	defer s.Unlock()
 	_, isOverwrite := s.items[index]
-	s.items[index] = obj
-	if len(s.items) > s.maxSize {
+	if !isOverwrite && len(s.items) >= s.maxSize {
```
Comment (lavalamp) [inline pkg/util/cache/cache.go]: The change to this function looks good.

File: pkg/util/cache/cache_test.go [hunk 3]
```diff
@@ -63,3 +66,31 @@ func TestOverwrite(t *testing.T) {
...
+	cache := NewCache(shardsCount - 1)
+	if cache != nil {
+		t.Errorf("Expect to cache to be nil, maxSize too small")
+	}
+}
+
+// TestEvict this test will fail sporatically depending on what add()
+// selects for the randomKey to be evicted.  Ensure that randomKey
+// is never the key we most recently added.  Through experimentation,
+// 5 times through the loop is enough to create the issue if it exists.
```
Comment (lavalamp) [inline pkg/util/cache/cache_test.go]: 5 times should give you 1/32 false pass rate, let's make it 7, which should drop the false pass rate below 1%.

File: pkg/util/cache/cache.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/util/cache/cache.go]: I agree with @lavalamp here. What we should really do is to set number of shards to min(shardsCount, maxSize) here

Comment (wojtek-t) [inline pkg/util/cache/cache.go]: @lavalamp - regarding why this cache exists. It was added before 1.0 release, where we didn't have "cacher" in apiserver, and thus we were unnecessary deserializing the same object multiple times (as it was send to different watchers). It's possible that currently it doesn't provide much value and we can remove it. We should evaluate it, but I would wait for protobufs to be in, to really confirm if it is useful (I guess it won't be at that point).

**Comment by sjenning** [comment]
@lavalamp @wojtek-t thanks for the review. updated per your comments.

File: pkg/util/cache/cache.go [hunk 4]
```diff
@@ -27,6 +27,9 @@ const (
 type Cache []*cacheShard
 
 func NewCache(maxSize int) Cache {
+	if maxSize < shardsCount {
+		maxSize = shardsCount
```
Comment (wojtek-t) [inline pkg/util/cache/cache.go]: I thought about doing it the other direction, but this is also fine :)

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #23350

**Comment by wojtek-t** [comment]
@eparis ^^ - this PR is for master branch, why does merge-bot said it's not?

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: #25135
