### PR TITLE
e2e: make GetSubnetPrefix IP family agnostic

### LINKED ISSUE #113964: "LoadBalancers should be able to preserve UDP traffic" test incorrectly assumes IPv4
### Which jobs are failing?

https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6&show-stale-tests=
https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6-flatcar&show-stale-tests=
https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-cilium-ipv6&show-stale-tests=
https://testgrid.k8s.io/kops-ipv6#kops-aws-ipv6-flatcar&show-stale-tests=

### Which tests are failing?

Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes
Kubernetes e2e suite.[It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes

### Since when has it been failing?

Since these tests were added in #113650

### Testgrid link

https://testgrid.k8s.io/kops-ipv6#kops-aws-cni-calico-ipv6&show-stale-tests=

### Reason for failure (if possible)

Test fails with `invalid IP address format: [2600:1f14:dae:f400:1626:905:6b64:7304]:22 failed test/e2e/network/loadbalancer.go:68`. That is a perfectly valid IP address format.

### Anything else we need to know?

The AWS CCM cannot create working loadbalancers for IPv6 clusters. One needs to disable the CCM's service controller and enable AWS LBC instead.

### Relevant SIG(s)

/sig network

### PR DESCRIPTION
**Pull request by anggao**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
e2e loadbalancer udp conntrack test depends on GetSubnetPrefix which only works under IPv4,
this change make GetSubnetPrefix IP family agnostic, and thus fixes failed tests.

#### Which issue(s) this PR fixes:

Fixes #113964

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
Thanks @anggao , let's try to fix the test better, `GetSubnetPrefix` is something we can do better, use multiple commits per change so is easier to review.

Some suggestions:

1. move `GetSubnetPrefix` method out of `framework/node` and make it private inside `loadbalancer.go`

```
test/e2e/network/loadbalancer.go:               subnetPrefix, err = e2enode.GetSubnetPrefix(cs)
test/e2e/network/loadbalancer.go:               subnetPrefix, err = e2enode.GetSubnetPrefix(cs)
test/e2e/framework/node/resource.go:// GetSubnetPrefix gets first 2 number of an IP in the node subnet. [IPv4]
test/e2e/framework/node/resource.go:func GetSubnetPrefix(c clientset.Interface) ([]string, error) {
```

2. make `GetSubnetPrefix` IP family agnostic, you can convert the string to a net.IPNet and set a custom mask ... i
3. instead of returning a slice of `[]string` return a `[]net.IPnet` and replace on the test the `strings.Contain` by the `IPNet.Contains` method

we iterate on these ideas, I may be missing something so feel free to add suggestions

/ok-to-test

File: test/e2e/network/loadbalancer.go [hunk 1]
```diff
@@ -54,6 +54,42 @@ import (
 	"github.com/onsi/gomega"
 )
 
+// getSubnetPrefix gets first 2 number of an IP in the node subnet. [IPv4]
+// It assumes that the subnet mask is /16.
+func getSubnetPrefix(c clientset.Interface) ([]string, error) {
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:59]:
```suggestion
func getSubnetPrefix(c clientset.Interface) (*net.IPNet, error) {
```

File: test/e2e/network/loadbalancer.go [hunk 2]
```diff
@@ -54,6 +54,42 @@ import (
 	"github.com/onsi/gomega"
 )
 
+// getSubnetPrefix gets first 2 number of an IP in the node subnet. [IPv4]
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:57]:
```
getSubnetPrefix returns a network prefix based on one of the workers InternalIP adding a /16 or /64 mask
depending on the IP family of the node`
IMPORTANT: These assumes a flat network assigned to the nodes, that is common
on cloud providers, but here be dragons
```

File: test/e2e/network/loadbalancer.go [hunk 3]
```diff
@@ -54,6 +54,42 @@ import (
...
+		return nil, fmt.Errorf("error getting a ready schedulable worker Node, err: %v", err)
+	}
+	internalIP, err := e2enode.GetInternalIP(node)
+	if err != nil {
+		return nil, fmt.Errorf("error getting Node internal IP, err: %v", err)
+	}
+	splitted := strings.Split(internalIP, ".")
+	if len(splitted) == 4 {
+		return splitted[:2], nil
+	}
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:71]:
```suggestion
	ip := net.ParseIP(internalIP)
	if ip == nil {
	  return nil, fmt.Errorf("invalid IP address format: %s", internalIP) 
	}
	// if IPv4 return a net.IPNet with IP = ip and  mask /16
	// if IPv6 return a net.IPNet with IP = ip and mask /64
```

File: test/e2e/network/loadbalancer.go [hunk 4]
```diff
@@ -54,6 +54,42 @@ import (
...
+	return nil, fmt.Errorf("invalid IP address format: %s", internalIP)
+}
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:73]: can't comment on untouched code, after returning a net.IPnet you can use net.IPNet.Contains and replace the `strings.HasPrefix(ingressEndpoint, subnetPrefix[0]+".")` for using IPNet and IP comparisons

Comment (aojea) [reply test/e2e/network/loadbalancer.go:73]: https://pkg.go.dev/net#IPNet.Contains

Comment (anggao) [reply test/e2e/network/loadbalancer.go:73]: 👍  Thank you for the detailed guidance, will do these changes in follow up commits (following suggestions to do multiple commits for easier review)

Comment (aojea) [reply test/e2e/network/loadbalancer.go:73]: take your time, and check the code around, maybe you can come up with some better ideas

File: test/e2e/framework/node/resource.go [hunk 5]
```diff
@@ -217,36 +217,26 @@ func TotalReady(c clientset.Interface) (int, error) {
 	return len(nodes.Items), nil
 }
 
-// GetExternalIP returns node external IP concatenated with port 22 for ssh
+// GetExternalSSHIP returns node external IP concatenated with port 22 for ssh
 // e.g. 1.2.3.4:22
-func GetExternalIP(node *v1.Node) (string, error) {
+func GetExternalSSHIP(node *v1.Node) (string, error) {
```
Comment (aojea) [inline test/e2e/framework/node/resource.go:222]: can we avoid changing names to these exported functions in this PR?

I'd like to avoid touching other tests 😄

File: test/e2e/network/loadbalancer.go [hunk 6]
```diff
@@ -54,17 +55,72 @@ import (
...
+func getSubnetPrefix(c clientset.Interface) (*net.IPNet, error) {
+	node, err := getReadySchedulableWorkerNode(c)
+	if err != nil {
+		return nil, fmt.Errorf("error getting a ready schedulable worker Node, err: %v", err)
+	}
+	internalIP, err := getInternalIP(node)
+	if err != nil {
+		return nil, fmt.Errorf("error getting Node internal IP, err: %v", err)
+	}
+	ip := net.ParseIP(internalIP)
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:81]: the linter will complain about using `netutils.ParseIPSloppy()`

File: test/e2e/network/loadbalancer.go [hunk 7]
```diff
@@ -1585,7 +1648,7 @@ var _ = common.SIGDescribe("LoadBalancers ESIPP [Slow]", func() {
 			if err != nil {
 				return false, nil
 			}
-			if strings.HasPrefix(clientIP, subnetPrefix[0]+".") {
+			if subnetPrefix.Contains(net.ParseIP(clientIP)) {
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:1651]: if you see the test failure

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114027/pull-kubernetes-e2e-gci-gce-ingress/1595217512394395648

The error message doesn't show the IP

> Nov 23 01:48:00.570: FAIL: Source IP WAS preserved even after ESIPP turned off. Got , expected a ten-dot cluster ip.

that means that most probably we need to sanitize the output of `GetHTTPContent(i` usually with TrimSpaces, and assert that net.ParseIP() is != nil and log and retry if it is

File: test/e2e/network/loadbalancer.go [hunk 8]
```diff
@@ -1614,7 +1677,7 @@ var _ = common.SIGDescribe("LoadBalancers ESIPP [Slow]", func() {
 				return false, nil
 			}
 			ginkgo.By(fmt.Sprintf("Endpoint %v:%v%v returned client ip %v", ingressIP, svcTCPPort, path, clientIP))
-			if !strings.HasPrefix(clientIP, subnetPrefix[0]+".") {
+			if !subnetPrefix.Contains(net.ParseIP(clientIP)) {
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:1680]: assert the clientIP is valid https://github.com/kubernetes/kubernetes/pull/114027/files#r1030216487

**Comment by aojea** [comment]
almost there, looking good

File: test/e2e/framework/node/resource.go (hunk 5 above)
Comment (anggao) [reply test/e2e/framework/node/resource.go]: Yes, reverted :) Can do a separate PR if you think that's make sense, or we can leave as it is.

File: test/e2e/network/loadbalancer.go (hunk 6 above)
Comment (anggao) [reply test/e2e/network/loadbalancer.go]: Thanks! found the linter failures

File: test/e2e/network/loadbalancer.go [hunk 9]
```diff
@@ -1306,7 +1369,7 @@ var _ = common.SIGDescribe("LoadBalancers ESIPP [Slow]", func() {
 		framework.Logf("ClientIP detected by target pod using VIP:SvcPort is %s", clientIP)
 
 		ginkgo.By("checking if Source IP is preserved")
-		if strings.HasPrefix(clientIP, subnetPrefix[0]+".") {
+		if subnetPrefix.Contains(net.ParseIP(clientIP)) {
```
[the remark this answers is not in the document]
Comment (anggao) [reply test/e2e/network/loadbalancer.go]: Yes, done.

File: test/e2e/network/loadbalancer.go (hunk 8 above)
Comment (anggao) [reply test/e2e/network/loadbalancer.go]: Yup.

File: test/e2e/network/loadbalancer.go (hunk 7 above)
Comment (anggao) [reply test/e2e/network/loadbalancer.go]: Guess we want retry as the IP might not be ready ?

**Comment by anggao** [comment]
Failed due to `Nov 23 11:33:15.091: FAIL: Invalid client IP address format: "34.136.112.132:53512"` will take a look

File: test/e2e/network/loadbalancer.go (hunk 7 above)
Comment (aojea) [reply test/e2e/network/loadbalancer.go]: yes,

File: test/e2e/framework/node/resource.go (hunk 5 above)
Comment (aojea) [reply test/e2e/framework/node/resource.go]: separate PR better, I'd like to backport it and make it as much targeted as possible

Comment (anggao) [reply test/e2e/framework/node/resource.go]: sure, updated!

**Comment by anggao** [comment]
@aojea I think its ready for another look, thank you!

**Comment by aojea** [comment]
/approve

can you squash all the commits into 1 ? 
I'll lgtm after that

Thank you very much

**Comment by anggao** [comment]
@aojea done. Thank you!

**Comment by aojea** [comment]
/assign @andrewsykim 

for final lgtm

/milestone v1.27
we have to wait master opens again,

Thanks

**Comment by dcbw** [comment]
@aojea @anggao any chance you can backport to 1.26? It's making v6/dual-stack fail there in LB tests.

**Comment by aojea** [comment]
> @aojea @anggao any chance you can backport to 1.26? It's making v6/dual-stack fail there in LB tests.

@dcbw https://github.com/kubernetes/kubernetes/pull/115558

**Comment by anggao** [comment]
@aojea thank you!
