### PR TITLE
DRA: return error on filter timeout instead of unschedulable

### LINKED ISSUE #133531: Flaky test: [sig-node] [DRA] retries pod scheduling after updating device class
### Which jobs are flaking?

TestGrid Link: https://testgrid.k8s.io/sig-release-1.34-blocking#gce-cos-k8sbeta-default

Failed Run: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-default/1955087524003057664

e2e test: https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/test/e2e/dra/dra.go#L801

The test failed with the following error:
```
{ failed [FAILED] schedule pod: Timed out after 80.001s.
expected pod to be pod is scheduled, got instead:
```

The error is originating from: https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/test/e2e/dra/utils/builder.go#L399-L404

The test times out waiting for the pod to be scheduled
```
status:
          conditions:
          - lastProbeTime: null
            lastTransitionTime: "2025-08-12T02:18:04Z"
            message: '0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane:
              }, 1 timed out trying to allocate devices, 2 cannot allocate all claims. still
              not schedulable, preemption: 0/4 nodes are available: 4 Preemption is not helpful
              for scheduling.'
            observedGeneration: 1
            reason: Unschedulable
            status: "False"
            type: PodScheduled
          phase: Pending
          qosClass: BestEffort
          resourceClaimStatuses:
          - name: my-inline-claim
            resourceClaimName: tester-1-my-inline-claim-mhnh9
```

https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/test/e2e/framework/pod/wait.go#L863-L867

A timeline of the events constructed from the audit log:
- a) `02:17:43.699544Z`: the device class is updated to `expression: false`
```
  "auditID": "084c3e2f-262d-44d4-830a-79bc4851ed7f",
  "stage": "ResponseComplete",
  "requestURI": "/apis/resource.k8s.io/v1/deviceclasses/dra-6628-class",
  "verb": "update",
```
- b) `02:17:44.023`: the test pod `dra-6628/tester-1` gets created
- c) the test starts waiting for the pod to be Unschedulable 
- d) `02:17:54.385781Z`: the scheduler adds the status `Unschedulable`
```
  "auditID": "1f7d7773-12f4-4b2e-8b21-0948750b0d23",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/dra-6628/pods/tester-1/status",
...
"status": {
      "conditions": [
        {
          "lastProbeTime": null,
          "lastTransitionTime": "2025-08-12T02:17:54Z",
          "message": "0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 cannot allocate all claims. still not schedulable, preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.",
          "observedGeneration": 1,
          "reason": "Unschedulable",
          "status": "False",
          "type": "PodScheduled"
        }
      ]
    }
```
- e) `02:17:56.638903Z`: the device class is restored by the test so the pod can be scheduled
```
  "auditID": "6a2a511c-2c62-4c58-aa78-4d9dfb564c10",
  "stage": "ResponseComplete",
  "requestURI": "/apis/resource.k8s.io/v1/deviceclasses/dra-6628-class",
  "verb": "update",
```
- f) the test starts waiting for the pod to be scheduled
- g) `02:18:04.292566Z`: The scheduler updates the pod status
```
  "auditID": "a88f656d-6447-4e27-a7ae-8b53e9fe26a5",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/dra-6628/pods/tester-1/status",
  "verb": "patch",
  ...
    "status": {
      "conditions": [
        {
          "lastProbeTime": null,
          "lastTransitionTime": "2025-08-12T02:18:04Z",
          "message": "0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 3 cannot allocate all claims. still not schedulable, preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.",
          "observedGeneration": 1,
          "reason": "Unschedulable",
          "status": "False",
          "type": "PodScheduled"
        }
      ]
    }
```
- h) `02:18:15.027340Z`: The scheduler updates the pod status
```
  "auditID": "40e22815-28b1-4111-9db5-42e03ea8f344",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/dra-6628/pods/tester-1/status",
  "verb": "patch",
  ...
  "requestObject": {
    "status": {
      "$setElementOrder/conditions": [
        {
          "type": "PodScheduled"
        }
      ],
      "conditions": [
        {
          "message": "0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 1 timed out trying to allocate devices, 2 cannot allocate all claims. still not schedulable, preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.",
          "type": "PodScheduled"
        }
      ]
    }
  },  
```
- i) `T02:19:17`: the test times and deletes the pod
```
  "auditID": "21099d72-783f-405a-84dc-0f0c6e60ec00",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/dra-6628/pods/tester-1",
  "verb": "delete", 
```
The test times out after `80s`, and the wait between `e` and `i` is expectedly about `80s`

The test restored the deviceclass at `02:17:56` (from `e`), and it seems the scheduler did not pick up DeviceClass update, I did not see any "DeviceClassUpdate" event, is this not expected?

The scheduler does show slow traces around the time the test was running:
```
I0812 02:18:04.188864      11 trace.go:236] Trace[1802395760]: "Scheduling" namespace:dra-6628,name:tester-1 (12-Aug-2025 02:17:54.394) (total time: 9794ms):
Trace[1802395760]: ---"Snapshotting scheduler cache and node infos done" 0ms (02:17:54.394)
Trace[1802395760]: ---"Computing predicates done" 9794ms (02:18:04.188)
Trace[1802395760]: [9.794235951s] [9.794235951s] END
```

Could that cause the scheduler to not pick up the changes to the deviceclass? I do see the scheduler picking up other events though

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by 0xMH**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
I was looking at the flaky test "retries pod scheduling after updating device class" and trying to understand why the pod sometimes never recovers after the DeviceClass is restored.

I originally thought the issue was in the queueing hints, that DeviceClass update events were getting consumed during in flight scheduling cycles and not triggering a retry. But @pohly's review made me realize that mechanism works as designed, and I might be looking at the wrong layer.

I dug deeper into the scheduling queue code in `scheduling_queue.go` to understand how unschedulable pods get retried. When a pod fails scheduling, what happens next depends on how it failed. If the failure is an `Error`, the pod goes to the backoff queue and retries automatically. If it's `UnschedulableAndUnresolvable`, the pod sits in the unschedulable queue waiting for a cluster event to move it out, and if that event never comes, it's stuck for up to 5 minutes.

The DRA filter returns `UnschedulableAndUnresolvable` when allocation times out. But a timeout is transient, it means the allocator didn't finish in time, not that the node is incompatible. So the pod ends up in the wrong queue.

This PR changes the timeout path to return `Error` instead, so the pod lands in the backoff queue and retries automatically. It also fixes a secondary issue: when the DRA filter returns `Error` on one node, `findNodesThatFitPod` was discarding successful results from other nodes. Now it keeps feasible nodes and proceeds with them.

#### Which issue(s) this PR is related to:

/fix #133531

#### Special notes for your reviewer:

I tried to reproduced the flake locally on a cluster by reducing the DRA filter timeout to force the timeout code path. Without this fix, the test sometimes fails. With the fix, it passes.

#### Does this PR introduce a user-facing change?

```release-note
Previously, when trying to allocate devices through DRA for a node timed out, scheduling would proceed with another node if any had the necessary resources. This potentially hid that a node was ignored. Worse, if scheduling was slow overall, the pod was incorrectly moved to "unschedulable" and only retried after a periodic sweep. Now timeouts are errors that are always visible as pod scheduling failures and get retried with per-pod exponential backoff.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/scheduler/schedule_one.go [hunk 1]
```diff
@@ -690,7 +690,11 @@ func (sched *Scheduler) findNodesThatFitPod(ctx context.Context, schedFramework
 	processedNodes := len(feasibleNodes) + diagnosis.NodeToStatus.Len()
 	sched.nextStartNodeIndex = (sched.nextStartNodeIndex + processedNodes) % len(allNodes)
 	if err != nil {
-		return nil, diagnosis, nodeHint, signature, err
+		if len(feasibleNodes) == 0 {
+			return nil, diagnosis, nodeHint, signature, err
+		}
+		// Don't discard nodes that already passed filters.
+		logger.V(2).Info("Filter error on some nodes, proceeding with feasible nodes", "pod", klog.KObj(pod), "feasibleNodes", len(feasibleNodes), "err", err)
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go]: This is a correct behavior that plugins returning Error cause the entire schedulng cycle to fail.

Comment (0xMH) [reply pkg/scheduler/schedule_one.go]: Agreed, dropped this change.

**Review by pohly — COMMENTED** [review]
/ok-to-test
/assign

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 2]
```diff
@@ -715,7 +715,10 @@ func (pl *DynamicResources) Filter(ctx context.Context, cs fwk.CycleState, pod *
 		a, err := state.allocator.Allocate(allocCtx, node, claimsToAllocate)
 		switch {
 		case errors.Is(err, context.DeadlineExceeded):
-			return statusUnschedulable(logger, "timed out trying to allocate devices", "pod", klog.KObj(pod), "node", klog.KObj(node), "resourceclaims", klog.KObjSlice(claimsToAllocate))
+			// Timeouts are transient, not a property of the node. Return Error
+			// so the pod retries via backoff instead of sitting in the
+			// unschedulable queue waiting for a cluster event.
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: There's another twist to this: if the timeout occurs for one node, but not another, what should happen?

Before it would continue with the result of the good node. I vaguely remember that this was the motivation for not making it an error.

Now the entire allocation fails and the pod gets retried with backoff. That's good if the timeout was because of load. But why should it? This only occurs if the scheduler competes with other processes for CPU time.

It's bad if, for whatever reason, allocation on one node always runs into the timeout. Perhaps that node publishes an abnormal amount of almost-right devices and allocation tries a lot more combinations that on other nodes.

One could argue that this is similar to user-caused errors (users must be made aware that they cannot run on some node), but it's also different because the user might not be able to fix it.

I'm undecided.

@0xMH: you said that you saw the timeouts. Do you know why they occurred?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: https://github.com/kubernetes/kubernetes/issues/133531 has a lot more details.

Basically it looks like a flake caused by an overloaded control plane during E2E testing. Making scheduling more resilient against that seems worthwhile. For the "too much work on some nodes" case we probably also want to raise visibility, so not scheduling to other nodes may also be the right thing to do.

**Review by pohly — COMMENTED** [review]
I'm undecided whether this should be called a bug fix or a feature. It worked as designed before, we just change the design.

And because we change behavior, do we need a feature gate? It could be beta, enabled by default, and get graduated quickly. The only purpose of it would be to restore the previous behavior if we misjudged and the prior behavior is the desirable one after all.

@mortent, @nojnhuh: thoughts on https://github.com/kubernetes/kubernetes/pull/137607#discussion_r2925934220?

File: test/integration/dra/dra_test.go [hunk 3]
```diff
@@ -708,6 +697,28 @@ func expectPodUnschedulable(tCtx ktesting.TContext, pod *v1.Pod, reason string)
...
+		if pod.Status.Phase == v1.PodPending {
+			for _, cond := range pod.Status.Conditions {
+				if cond.Type == v1.PodScheduled && cond.Status == v1.ConditionFalse && cond.Reason == v1.PodReasonSchedulerError {
+					return true, nil
+				}
+			}
+		}
+		return false, nil
+	}), fmt.Sprintf("expected pod to have scheduler error because %q", reason))
+	pod, err := tCtx.Client().CoreV1().Pods(pod.Namespace).Get(tCtx, pod.Name, metav1.GetOptions{})
```
Comment (bart0sh) [inline test/integration/dra/dra_test.go]: It looks like the pod is fetched again only to check if reason contains expected substring as the rest of fields are already tested on line 705. Can we test this as well and drop the code below ?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 2 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: Overall I agree with making this an error that gets retried. For things like scoring, users may be relying on having a complete picture of all nodes, so ignoring the ones that time out may produce unexpected results in those cases.

I don't think we can reliably tell in real-time if a given node times out because finding a solution is too complex or if the scheduler is under too much load. Both of those factors can contribute to the same timeout. Even if the user can't fix the root cause, would generating a warning Event (user-facing) and log message (admin-facing) make that adequately visible?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: I think if we make this an error, it will show up in the pod status (user-facing) and in logs+metrics (admin facing) - no need to do anything special.

@nojnhuh: so shall we just change it, without a feature gate? I'd be okay with that, in particular when considering the odd behavior when it really times out on all nodes: pod goes to unschedulable queue, only gets retried when sweeping that queue periodically. That really is a bug.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: I think changing it without a feature gate is okay as long we're confident the additional retries don't cause adverse effects due to CPU spikes or anything like that.

Comment (0xMH) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:726]: Hi @pohly 
Apologies for the late reply. I'm drowning in work these days. 

> @0xMH: you said that you saw the timeouts. Do you know why they occurred?

The timeouts in the original flake were caused by control plane overload during E2E runs. As you might have seen @tkashem's latency analysis on the issue confirms this. When I was testing I reproduced that behavior locally by reducing the DRA filter timeout to force the code path. Without the fix the pod gets stuck in the unschedulable queue. With it, backoff retries resolve it.

**Comment by 0xMH** [comment]
Yup was working on it.

File: test/integration/dra/core.go
Comment (pohly) [inline test/integration/dra/core.go:1]: FilterTimeout/enabled fails, I can reproduce locally:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137607/pull-kubernetes-integration/2033853342316236800

Comment (pohly) [inline test/integration/dra/core.go:156]:
```
    core.go:146: FATAL ERROR: I0317 11:52:39.558946]
                Unexpected error: Timed out after 80.001s.
                expected pod to be pod is scheduled, got instead:
...
                        status:
                          conditions:
                          - lastProbeTime: null
                            lastTransitionTime: "2026-03-17T10:51:17Z"
                            message: 'running "DynamicResources" filter plugin: timed out trying to allocate
                              devices'
                            observedGeneration: 1
                            reason: SchedulerError
                            status: "False"
                            type: PodScheduled
                          phase: Pending
                          qosClass: BestEffort
```

Comment (0xMH) [reply test/integration/dra/core.go:1]: I reproduced it locally too. Took me a while to track down.  I think the issue is in how `findNodesThatPassFilters` handles `Error` vs `Unschedulable` status. When a filter returns Error for any node, the scheduler cancels the entire parallel evaluation and aborts the cycle. With Unschedulable, it just marks that node as not feasible and continues to the next one.

Comment (0xMH) [reply test/integration/dra/core.go:1]: So I think what's happening is after we update worker-1's slice, the scheduler retries from backoff and evaluates both nodes in parallel. worker-0 still has 20 devices, the allocator can't finish in 10ms, returns `Error`. That `Error` cancels the context for the whole cycle, so worker-1 either never gets a chance to complete or gets cancelled mid-allocation. The pod goes back to backoff, retries, hits the same wall, over and over until `WaitForPodScheduled` gives up after 80s.

With the old `UnschedulableAndUnresolvable`, worker-0's timeout was treated as a rejection. The scheduler continued to worker-1, found 21 devices, allocated them, done.

I'm thinking the fix would be to clear worker-0's devices before updating worker-1. With 0 devices the allocator should return `ErrFailedAllocationOnNode` instantly so no timeout, which maps to `Unschedulable`, so the scheduler continues to worker-1 and succeeds. I think this also better models the real scenario, the transient overload clears and the pod retries successfully. Does that sound right to you?

Comment (0xMH) [reply test/integration/dra/core.go:156]: Yup the issue I described in the other thread. The pod keeps hitting the timeout on worker-0 which returns Error, and that aborts the whole scheduling cycle before worker-1 gets evaluated. So it loops forever until [`podScheduledBeforeTimeout`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/wait.go#L55) (80s) gives up.

Comment (pohly) [reply test/integration/dra/core.go:1]: I arrrived at the same conclusion.

I can see several pod scheduling attempts:
```
    schedule_one.go:278: E0317 12:29:43.723864] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:29:45.013629] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:29:48.013272] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:29:53.014588] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:02.013952] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:13.012636] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:24.014597] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:35.013018] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:46.014607] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
    schedule_one.go:278: E0317 12:30:57.012554] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: timed out trying to allocate devices" pod="default-filtertimeout-g8jn8/my-pod"
```

What the test does is "Update *one* slice such that allocation succeeds." (emphasis mine). The other node then still times out. That used to work when all we required was success on some node. Now we require no timeout on all nodes.

If the error message contained the node name, this would be clearer. Let's add that. I'm working on a patch.

Comment (pohly) [reply test/integration/dra/core.go:1]: And a fix for the test.

Comment (pohly) [reply test/integration/dra/core.go:1]:
```
    schedule_one.go:278: E0317 12:55:22.032141] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: node worker-0: timed out trying to allocate devices" pod="default-filtertimeout-fs7b4/my-pod"
```

Bingo!

Comment (0xMH) [reply test/integration/dra/core.go:1]: Nice, glad we're on the same page. I already pushed a fix that clears worker-0's devices before updating worker-1, so the allocator completes instantly on worker-0 and the scheduler can reach worker-1. Tests pass locally on both default and all packages. Could you have a look? Do we need a separate PR for fixing the test or is it okay to do that in this one?

Comment (pohly) [reply test/integration/dra/core.go:1]:
```
    schedule_one.go:278: E0317 13:08:51.856631] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: node worker-1: timed out trying to allocate devices" pod="default-filtertimeout-f955f/my-pod"
    schedule_one.go:278: E0317 13:08:53.013303] scheduler: Error selecting node for pod err="running \"DynamicResources\" filter plugin: node worker-1: timed out trying to allocate devices" pod="default-filtertimeout-f955f/my-pod"
```

This is with the following patch:
```patch
diff --git a/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go b/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go
index 80f9a1a37bf..bdaaa0bb569 100644
--- a/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go
+++ b/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go
@@ -721,10 +721,13 @@ func (pl *DynamicResources) Filter(ctx context.Context, cs fwk.CycleState, pod *
 		a, err := state.allocator.Allocate(allocCtx, node, claimsToAllocate)
 		switch {
 		case errors.Is(err, context.DeadlineExceeded):
-			// Timeouts are transient, not a property of the node. Return Error
+			// Timeouts are potentially transient. Return Error
 			// so the pod retries via backoff instead of sitting in the
 			// unschedulable queue waiting for a cluster event.
-			return statusError(logger, fmt.Errorf("timed out trying to allocate devices"), "pod", klog.KObj(pod), "node", klog.KObj(node), "resourceclaims", klog.KObjSlice(claimsToAllocate))
+			//
+			// The timeout might be caused by ResourceSlices for the node,
+			// so including the node name may help with diagnosing the failure.
+			return statusError(logger, fmt.Errorf("node %s: timed out trying to allocate devices", node.Name), "pod", klog.KObj(pod), "node", klog.KObj(node), "resourceclaims", klog.KObjSlice(claimsToAllocate))
 		case errors.Is(err, structured.ErrFailedAllocationOnNode):
 			// Not a fatal error, allocation on other nodes may proceed.
 			// The error is only surfaced if allocation fails on all nodes.
diff --git a/test/integration/dra/core.go b/test/integration/dra/core.go
index 876f7e2fac7..d0acbe5df44 100644
--- a/test/integration/dra/core.go
+++ b/test/integration/dra/core.go
@@ -95,19 +95,22 @@ func testConvert(tCtx ktesting.TContext) {
 // testFilterTimeout covers the scheduler plugin's filter timeout configuration and behavior.
 //
 // It runs the scheduler with non-standard settings and thus cannot run in parallel.
-func testFilterTimeout(tCtx ktesting.TContext, devicesPerSlice int) {
+func testFilterTimeout(tCtx ktesting.TContext, requestDeviceCount int) {
 	namespace := createTestNamespace(tCtx, nil)
 	class, driverName := createTestClass(tCtx, namespace)
-	deviceNames := make([]string, devicesPerSlice)
-	for i := range devicesPerSlice {
+	deviceNames := make([]string, requestDeviceCount)
+	for i := range requestDeviceCount {
 		deviceNames[i] = fmt.Sprintf("dev-%d", i)
 	}
 	slice := st.MakeResourceSlice("worker-0", driverName).Devices(deviceNames...)
 	createSlice(tCtx, slice.Obj())
-	otherSlice := st.MakeResourceSlice("worker-1", driverName).Devices(deviceNames...)
+	otherSlice := st.MakeResourceSlice("worker-1", driverName).Devices(deviceNames[:requestDeviceCount-1]...)
 	createdOtherSlice := createSlice(tCtx, otherSlice.Obj())
 	claim := claim.DeepCopy()
-	claim.Spec.Devices.Requests[0].Exactly.Count = int64(devicesPerSlice + 1) // Impossible to allocate.
+	// Impossible to allocate on worker-1: not enough devices, but allocation is too
+	// dumb to notice that upfront and keeps trying until it times out.
+	// On worker-0 we can allocate, but don't schedule because of the timeout on worker-1.
+	claim.Spec.Devices.Requests[0].Exactly.Count = int64(requestDeviceCount)
 	claim = createClaim(tCtx, namespace, "", class, claim)
 
 	runSubTest(tCtx, "disabled", func(tCtx ktesting.TContext) {
@@ -135,11 +138,11 @@ profiles:
 `)
 		expectPodSchedulerError(tCtx, pod, "timed out trying to allocate devices")
 
-		// Update one slice such that allocation succeeds.
+		// Update the smaller slice such that allocation also succeeds.
 		// The scheduler retries automatically (timeouts go through
 		// backoff queue, not unschedulable pool) and should succeed now.
 		createdOtherSlice.Spec.Devices = append(createdOtherSlice.Spec.Devices, resourceapi.Device{
-			Name: fmt.Sprintf("dev-%d", devicesPerSlice),
+			Name: deviceNames[requestDeviceCount-1],
 		})
 		_, err := tCtx.Client().ResourceV1().ResourceSlices().Update(tCtx, createdOtherSlice, metav1.UpdateOptions{})
 		tCtx.ExpectNoError(err, "update worker-1's ResourceSlice")
diff --git a/test/integration/dra/dra.go b/test/integration/dra/dra.go
index 35ce2cc6daf..0fb153a387b 100644
--- a/test/integration/dra/dra.go
+++ b/test/integration/dra/dra.go
@@ -133,7 +133,7 @@ func run(tCtx ktesting.TContext, whatRE string) {
 				runSubTest(tCtx, "EvictClusterWithSlices", func(tCtx ktesting.TContext) { testEvictCluster(tCtx, useNoRule) })
 				// Number of devices per slice is chosen so that Filter takes a few seconds:
 				// without a timeout, the test doesn't run too long, but long enough that a short timeout triggers.
-				runSubTest(tCtx, "FilterTimeout", func(tCtx ktesting.TContext) { testFilterTimeout(tCtx, 20) })
+				runSubTest(tCtx, "FilterTimeout", func(tCtx ktesting.TContext) { testFilterTimeout(tCtx, 21) })
 				runSubTest(tCtx, "UsesAllResources", testUsesAllResources)
 			},
 		},
@@ -243,7 +243,7 @@ func run(tCtx ktesting.TContext, whatRE string) {
 				// Number of devices per slice is chosen so that Filter takes a few seconds: The allocator
 				// in the experimental channel has an improvement that requires a higher number here than
 				// in the incubating and stable channels.
-				runSubTest(tCtx, "FilterTimeout", func(tCtx ktesting.TContext) { testFilterTimeout(tCtx, 20) })
+				runSubTest(tCtx, "FilterTimeout", func(tCtx ktesting.TContext) { testFilterTimeout(tCtx, 21) })
 				runSubTest(tCtx, "ShareResourceClaimSequentially", testShareResourceClaimSequentially)
 				runSubTest(tCtx, "UsesAllResources", testUsesAllResources)
 			},
```

I'm renaming the parameter to make the semantic a bit clearer. The request count is fixed, device per slice is not.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 4]
```diff
@@ -721,7 +721,10 @@ func (pl *DynamicResources) Filter(ctx context.Context, cs fwk.CycleState, pod *
...
+			return statusError(logger, fmt.Errorf("timed out trying to allocate devices"), "pod", klog.KObj(pod), "node", klog.KObj(node), "resourceclaims", klog.KObjSlice(claimsToAllocate))
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Let's include the node name here in the error itself.

Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Let's include the node name in the error message (https://github.com/kubernetes/kubernetes/pull/137607/changes#r2946269651 is more useful).

File: test/integration/dra/core.go [hunk 5]
```diff
@@ -133,14 +133,23 @@ profiles:
...
-		// The scheduler must retry and should succeed now.
+		expectPodSchedulerError(tCtx, pod, "timed out trying to allocate devices")
+
+		// Clear worker-0's devices so the allocator completes quickly
+		// on that node. With Error status (from timeouts), the scheduler
+		// aborts the entire cycle, so no node with a slow allocation
+		// can remain.
+		createdSlice.Spec.Devices = nil
+		_, err := tCtx.Client().ResourceV1().ResourceSlices().Update(tCtx, createdSlice, metav1.UpdateOptions{})
+		tCtx.ExpectNoError(err, "clear worker-0's ResourceSlice")
```
Comment (pohly) [inline test/integration/dra/core.go]: I like my approach from https://github.com/kubernetes/kubernetes/pull/137607/changes#r2946329223 slightly better: it makes it so that only one node times out, which then also covers the "don't proceed when some, but not all nodes time out" part of this PR.

Comment (pohly) [reply test/integration/dra/core.go]: I then also only need to update one slice.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Thanks a lot!
