### PR TITLE
[PodLevelResources] Add missing label to Downward API test

### LINKED ISSUE #133232: [sig-node] Downward API [Feature:PodLevelResources] Downward API tests for pod level resources should provide default limits.cpu/memory from pod level resources
### Which jobs are failing?

cos-cgroupv2-containerd-node-features
cos-cgroupv1-containerd-node-features

### Which tests are failing?

Downward API tests for pod level resources should provide default limits.cpu/memory from pod level resources

### Since when has it been failing?

07-25 08:06 CST

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-features

### Reason for failure (if possible)

```
{ failed [FAILED] expected "MEMORY_LIMIT=67108864" in container output: Expected
    <string>: KUBERNETES_SERVICE_PORT=443
    KUBERNETES_PORT=tcp://10.0.0.1:443
    HOSTNAME=downward-api-9fa6472b-4aeb-4fa9-845d-91b5243a668f
    SHLVL=1
    HOME=/root
    KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    KUBERNETES_PORT_443_TCP_PORT=443
    KUBERNETES_PORT_443_TCP_PROTO=tcp
    CPU_LIMIT=2
    KUBERNETES_SERVICE_PORT_HTTPS=443
    KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
    KUBERNETES_SERVICE_HOST=10.0.0.1
    PWD=/
    MEMORY_LIMIT=3849900032
    
to match regular expression
    <string>: MEMORY_LIMIT=67108864
In [It] at: k8s.io/kubernetes/test/e2e/framework/pod/output/output.go:282 @ 07/26/25 08:31:53.432
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by toVersus**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Fix for a test failure caused by a test running in an unintended test lane. (e.g. https://testgrid.k8s.io/sig-node-containerd#node-e2e-features)

#### Which issue(s) this PR is related to:

Fixes: https://github.com/kubernetes/kubernetes/issues/133232

https://github.com/kubernetes/kubernetes/commit/a82187cf11aa41e0f907761bdd4b815984f6de67#r162871647

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/override pull-kubernetes-node-e2e-containerd-features

Looks to be fixed now.

**Comment by kannon92** [comment]
/lgtm
/approve

@dims can we get this in? Helps with failing test cases .

**Comment by kannon92** [comment]
Holding for an approver and to make sure we are okay with merging.

https://github.com/kubernetes/kubernetes/pull/133220#issuecomment-3119935474

File: test/e2e/common/node/downwardapi.go [hunk 1]
```diff
@@ -416,7 +417,7 @@ var _ = SIGDescribe("Downward API", framework.WithSerial(), framework.WithDisrup
 
 })
 
-var _ = SIGDescribe("Downward API", feature.PodLevelResources, func() {
+var _ = SIGDescribe("Downward API", feature.PodLevelResources, framework.WithFeatureGate(features.PodLevelResources), func() {
```
Comment (BenTheElder) [inline test/e2e/common/node/downwardapi.go:420]: Does podlevelresources require anything other than enabling the featuregate?

If not, then `feature.PodLevelResources` should be replaced with just `framework.WithFeatureGate(features.PodLevelResources)`.

Comment (BenTheElder) [reply test/e2e/common/node/downwardapi.go:420]: looks like no:
https://github.com/kubernetes/kubernetes/blob/f9ed14bf9b1119a2e091f4b487a3b54930661034/test/e2e/feature/feature.go#L330-L333

In that case:
```suggestion
var _ = SIGDescribe("Downward API", framework.WithFeatureGate(features.PodLevelResources), func() {
```

Comment (BenTheElder) [reply test/e2e/common/node/downwardapi.go:420]: (We should actually remove the `test/e2e/feature.PodLevelResources` entirely ...)

Comment (BenTheElder) [reply test/e2e/common/node/downwardapi.go:420]: Hmm, I see that many of the node e2e jobs aren't quite working like that yet ...

Comment (toVersus) [reply test/e2e/common/node/downwardapi.go:420]: Ah, I see. You're referring to this thread.
https://groups.google.com/a/kubernetes.io/g/dev/c/uVga86nJDuI

That said, the current `pull-kubernetes-node-kubelet-serial-podlevelresources` presubmit job is filtered by `Feature:PodLevelResources`. So, if `feature.PodLevelResources` label is missing, the tests will be skipped.
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133220/pull-kubernetes-node-kubelet-serial-podlevelresources/1948869177884282880

Would it be okay to keep the `feature.PodLevelResources` label for now?

**Comment by toVersus** [comment]
@SergeyKanzhelev 
Sorry, I broke some presubmit tests. Could you take a look?

File: test/e2e/common/node/downwardapi.go (hunk 1 above)
Comment (BenTheElder) [reply test/e2e/common/node/downwardapi.go:420]: Yeah, ideally we'd align node_e2e and the cluster e2e tests on this longterm, but now is not the time

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev Sorry, I broke some presubmit tests. Could you take a look?

after the @BenTheElder is this still needed?

**Comment by toVersus** [comment]
Yes. Without this fix, some jobs won't run properly.

**Comment by BenTheElder** [comment]
I think the node e2e jobs are still split between how the test cases are selected and both FeatureGate and Feature are being used there. `Feature:OffByDefault` is added to `WithFeatureGate` for feature gates that are off by default, but if you allow all `Feature`  then ...

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by SergeyKanzhelev** [comment]
> I think the node e2e jobs are still split between how the test cases are selected and both FeatureGate and Feature are being used there. `Feature:OffByDefault` is added to `WithFeatureGate` for feature gates that are off by default, but if you allow all `Feature` then ...

yes, we need to migrate and clean up all the tests
