### PR TITLE
fix terminationGracePeriod blocked by preStop

### LINKED ISSUE #115817: kubelet: PreStop Hooks can hang termination of a pod beyond pod's termination grace period
### What happened?

Termination grace period includes the termination time of prestop hooks and containers in the pod. The total time that the pod terminates should always be < termination grace period seconds.

A misconfigured pod with a preStopHook that hangs indefinitely and pod ignoring SIGTERM can result in the pod taking 2X (double) the termination grace period seconds to terminate.
 

### What did you expect to happen?

The time to terminate the pod should always be <= termination grace period seconds including prestop hook execution time as documented in https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

### How can we reproduce it (as minimally and precisely as possible)?

1) Apply the following pod

```
kind: Pod
apiVersion: v1
metadata:
  name: prestop-repro
  labels:
    pod: prestop-repro
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 999999"]
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    command: ["/bin/sh", "-c"]
    args:
      - |
        _term() {
            echo "Caught SIGTERM signal!"
            while true; do sleep 5; done
        }
        trap _term SIGTERM
        while true; do sleep 5; done
```

2) 

```
$ time kubectl delete pod prestop-repro
pod "prestop-repro" deleted

real    2m1.035s
user    0m0.172s
sys     0m0.077s
```

3) Observe it actually took ~120s to terminate the pod not ~60s as would be expected.

### Anything else we need to know?

The kubelet logs for the pod https://gist.github.com/1f76e54b32bc51f1a9525cc8b707f820

```

# pods start terminating at `23:54:37 `

Feb 15 23:54:37 kind-worker kubelet[268]: I0215 23:54:37.470356     268 kubelet.go:1858] "syncTerminatingPod enter" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866
Feb 15 23:54:37 kind-worker kubelet[268]: I0215 23:54:37.470576     268 kubelet.go:1888] "Pod terminating with grace period" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 gracePeriod=60


# preStop hook starts running

Feb 15 23:54:37 kind-worker kubelet[268]: I0215 23:54:37.470633     268 kuberuntime_container.go:588] "Running preStop hook" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184"
Feb 15 23:54:37 kind-worker kubelet[268]: I0215 23:54:37.473551     268 status_manager.go:719] "Patch status for pod" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 patch="{\"metadata\":{\"uid\":\"0f651710-9a93-4424-afe6-646d01698866\"}}"


# preStop hook times out (after 60s)

Feb 15 23:55:37 kind-worker kubelet[268]: I0215 23:55:37.470698     268 kuberuntime_container.go:605] "PreStop hook not completed in grace period" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184" gracePeriod=60

# container is given _another_ 60s to terminate

Feb 15 23:55:37 kind-worker kubelet[268]: I0215 23:55:37.470737     268 kuberuntime_container.go:705] "Killing container with a grace period override" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184" gracePeriod=60
Feb 15 23:55:37 kind-worker kubelet[268]: I0215 23:55:37.470752     268 kuberuntime_container.go:709] "Killing container with a grace period" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184" gracePeriod=60
Feb 15 23:56:37 kind-worker kubelet[268]: E0215 23:56:37.505958     268 kuberuntime_container.go:596] "PreStop hook failed" err="command '/bin/sh -c sleep 999999' exited with 137: " pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184"
Feb 15 23:56:37 kind-worker kubelet[268]: I0215 23:56:37.550077     268 kuberuntime_container.go:718] "Container exited normally" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containerName="busybox" containerID="containerd://5ae2cb9d4f1a99a7da040027f6c8e036fe901b2e125de2a164159d0e427d2184"
Feb 15 23:56:37 kind-worker kubelet[268]: I0215 23:56:37.751329     268 kubelet.go:1939] "Post-termination container state" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866 containers=[{Name:busybox State:exited ExitCode:137 FinishedAt:2023-02-15T23:56:37.495827089Z}]
Feb 15 23:56:37 kind-worker kubelet[268]: I0215 23:56:37.751382     268 kubelet.go:1955] "Pod termination stopped all running containers" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866

# all containers are fully terminated 2 minutes later (instead of 1 minute as expected)

Feb 15 23:56:37 kind-worker kubelet[268]: I0215 23:56:37.751420     268 kubelet.go:1957] "syncTerminatingPod exit" pod="default/prestop-repro" podUID=0f651710-9a93-4424-afe6-646d01698866
```

The issue is that we are not taking into account the time taken by execution of the prestop hook when calculating the time remaining to kill the remaining containers in the pod.

### Kubernetes version

Reproduced on 1.26.0

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix unreasonable hang caused by preStopHook after terminationGracePeriodSeconds, which is different from what is described in https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution

#### Which issue(s) this PR fixes:

Fixes #115817

#### Does this PR introduce a user-facing change?

```release-note
Fixed the preStop hook will block the pod termination grace period
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Please include some tests into this PR

**Comment by SergeyKanzhelev** [comment]
/unassign @yujuhong

Let's ok to test once there are tests added to the PR

**Comment by HirazawaUi** [comment]
> /unassign @yujuhong
> 
> Let's ok to test once there are tests added to the PR

hi, i have added the test code, please help to start test

**Comment by HirazawaUi** [comment]
> @HirazawaUi Are you still working on this?

yes i'm still working on it

**Review by gjkim42 — COMMENTED** [review]
I think `gracePeriodOverride` should be applied only before `executePreStopHook` so that the `killContainer` can finish in at most `gracePeriodOverride` + 2 seconds.

**Comment by HirazawaUi** [comment]
> I think `gracePeriodOverride` should be applied only before `executePreStopHook` so that the `killContainer` can finish in at most `gracePeriodOverride` + 2 seconds.



> 

If executePreStopHook is executed, gracePeriodOverride will be skipped to override gracePeriod, and killContainer will also be completed in gracePeriodOverride +2s

**Comment by gjkim42** [comment]
> > I think `gracePeriodOverride` should be applied only before `executePreStopHook` so that the `killContainer` can finish in at most `gracePeriodOverride` + 2 seconds.
> 
> > 
> 
> If executePreStopHook is executed, gracePeriodOverride will be skipped to override gracePeriod, and killContainer will also be completed in gracePeriodOverride +2s

If `executePreStopHook` runs without applying `gracePeriodOverride`, it can take `gracePeriod` seconds which can be longer than `gracePeriodOverride` seconds.

**Comment by sanusatyadarshi** [comment]
Will this be fixed in v1.25 of Kubernetes or only in the latest release(s)?

**Comment by gjkim42** [comment]
> Will this be fixed in v1.25 of Kubernetes or only in the latest release(s)?

We can only cherry-pick the critical bugfixes and I am not sure this is one of them. Let's see.

**Review by gjkim42 — COMMENTED** [review]
The patch looks reasonable.
Can we make some unit tests simulating https://github.com/kubernetes/kubernetes/issues/115817?

https://github.com/kubernetes/kubernetes/blob/c9ff2866682432075da1a961bc5c3f681b34c8ea/pkg/kubelet/container/helpers.go#L42-L44

Maybe we have to implement a fake HandlerRunner to simulate a long-running pre stop hook.

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go [hunk 1]
```diff
@@ -493,6 +501,26 @@ func TestLifeCycleHook(t *testing.T) {
...
+		lcHanlder = lifecycletest.NewFakeHandlerRunner()
+		m.runner = lcHanlder
+
+		testPod.Spec.Containers[0].Lifecycle = cmdLongTermLifeCycle
+		m.killContainer(ctx, testPod, cID, "foo", "testKill", "", &gracePeriod)
+
+		if time.Since(startTime) > time.Duration(gracePeriod+minimumGracePeriodInSeconds)*time.Second {
+			t.Error("When gracePeriod is 0, PreStop exec should complete in 3s")
+		}
+	})
```
Comment (gjkim42) [inline pkg/kubelet/kuberuntime/kuberuntime_container_test.go:522]: I think this cannot simulate https://github.com/kubernetes/kubernetes/issues/115817 as `runtime.StopContainer` always returns `contaienr not found error` immediately. (This test succeeds without the fix as well.)

I wrote [an e2e test](https://github.com/kubernetes/kubernetes/pull/116911) to simulate this scenario as it may be too complex to write it in a unit test. Could you cherry-pick that commit or write your own and remove this unit test if you don't mind?

Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go:522]: > I think this cannot simulate #115817 as `runtime.StopContainer` always returns `contaienr not found error` immediately. (This test succeeds without the fix as well.)
> 
> I wrote [an e2e test](https://github.com/kubernetes/kubernetes/pull/116911) to simulate this scenario as it may be too complex to write it in a unit test. Could you cherry-pick that commit or write your own and remove this unit test if you don't mind?

Okay, I will delete this unit test and cherry-pick your commit

Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go]: you just cherry-picked outdated commit (sorry, I force-pushed it)

**Review by gjkim42 — COMMENTED** [review]
This is not just a cleanup but a bug so you should provide the release note about what this PR addresses.

**Comment by HirazawaUi** [comment]
@gjkim42 I have finished the modifications and cherry-picked the commit, so we should be able to retest now

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go (hunk 1 above)
Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go]: > you just cherry-picked outdated commit (sorry, I force-pushed it)

Already cherry-pick the latest commit

Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go]: > you should cherry-pick the test again as I fixed a lint error.

Okay

**Comment by gjkim42** [comment]
@HirazawaUi 
Looks like this fixes the e2e test correctly.

However, I am not sure reviewers have time to review this as we are in the middle of the release process. Let's see.

/assign @SergeyKanzhelev 
Could you PTAL when available?
This makes kubernetes include the time taken to execute preStop hooks when calculating termination grace period.

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go [hunk 2]
```diff
@@ -18,6 +18,7 @@ package kuberuntime
 
 import (
 	"context"
+	"k8s.io/kubernetes/pkg/kubelet/lifecycle"
```
Comment (SataQiu) [inline pkg/kubelet/kuberuntime/kuberuntime_container_test.go:21]: The package imports need to be grouped. So this change is unexpected.

File: test/e2e_node/pod_termination_test.go [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+	"github.com/onsi/ginkgo/v2"
+	v1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/kubernetes/test/e2e/framework"
+	e2epod "k8s.io/kubernetes/test/e2e/framework/pod"
+	imageutils "k8s.io/kubernetes/test/utils/image"
+	admissionapi "k8s.io/pod-security-admission/api"
+)
+
+var _ = SIGDescribe("Pod Termination", func() {
```
Comment (SataQiu) [inline test/e2e_node/pod_termination_test.go:32]: This looks more like part of the container-lifecycle tests, how about moving it into `test/e2e_node/container_lifecycle_test.go`?

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go (hunk 2 above)
Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go:21]: Okay, I'll reset this file

File: test/e2e_node/pod_termination_test.go (hunk 3 above)
Comment (HirazawaUi) [reply test/e2e_node/pod_termination_test.go:32]: > This looks more like part of the container-lifecycle tests, how about moving it into `test/e2e_node/container_lifecycle_test.go`?

all right

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
