### PR TITLE
Install specific salt version on AWS, based on GCE

### LINKED ISSUE #8114: Salt error (AWS?): container_bridge.ensure was not found
I saw this error in `/var/log/salt/minion` on the master after a failed cluster start:

```
2015-05-12 14:37:02,635 [salt.state       ][ERROR   ][4524] State 'container_bridge.ensure' was not found in SLS 'docker'
```

I'm looking into this, but I want to create a tracking issue as I think some other people may be hitting this.

### PR DESCRIPTION
**Pull request by justinsb**
The latest salt version breaks the container_bridge.py _state function

We can lock to the same version as GCE.  This is not a full fix,
because we can't update to the latest salt without breaking GCE,
but this at least unbreaks and sync AWS with GCE.

This isn't a straight copy from GCE, because we still use
the salt master on AWS (for now)

Fixes #8114

### CODE REVIEW

File: cluster/aws/templates/common.sh [hunk 1]
```diff
@@ -27,3 +27,72 @@ download-or-bust() {
...
+  # We do this to prevent Salt from starting the salt-minion
+  # daemon. The other packages don't have relevant daemons. (If you
+  # add a package that needs a daemon started, add it to a different
+  # list.)
+  cat > /usr/sbin/policy-rc.d <<EOF
+#!/bin/sh
+echo "Salt shall not start." >&2
+exit 101
+EOF
+  chmod 0755 /usr/sbin/policy-rc.d
```
Comment (zmerlynn) [inline cluster/aws/templates/common.sh]: You probably don't want the policy-rc.d section here. We do it on GCE because the `.deb`  automatically starts the daemon, even though we're just using it in local mode. It would save you actually having to start the daemon manually below, I believe.

Comment (justinsb) [inline cluster/aws/templates/common.sh]: I think I need it because we are installing the debs for e.g. salt-master, but the debs that salt-master depends on are likely missing.  Those get installed later.  I am not sure whether it should retry restarting the daemons after the fix, but it seemed not to.  In any case, it seems risky to try starting the daemons without the dependencies in place.

Comment (zmerlynn) [inline cluster/aws/templates/common.sh]: The way the code used to work (prior to when I put the policy-rc.d stuff in), the daemon actually gets fired up in the `apt-get install -f -y` section below after deps are resolved. It all works out.

**Comment by justinsb** [comment]
You were right @zmerlynn.  I'm a little nervous about what actually is happening under the covers here (does apt know that the dependencies aren't met, or is the service failing to start because the dependencies aren't met), but we can go with the simpler approach!

**Comment by zmerlynn** [comment]
In theory, I'm not sure you need the `service start` anymore, but in practice it's probably a good habit. :) LGTM. I'm sure you had to do this!

**Comment by justinsb** [comment]
Good point - we probably don't need service start.  Probably / hopefully harmless.  I haven't seen any issues with it, but I'll double-check it isn't warning something horrible...

**Comment by zmerlynn** [comment]
I believe it actually does poke to make sure the service is actually started before blindly starting another copy.
