### PR TITLE
fix hack/verify-golint.sh on a Mac

### LINKED ISSUE #31905: hack/verify-golint.sh fails on a Mac
Looks like it is chopping off the correct Kube prefix, maybe because of bash 4.0isms.

```
hack/verify-golint.sh
cannot find package "_/Users/clayton/projects/go/src/cluster/addons/fluentd-elasticsearch/es-image/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cluster/addons/fluentd-elasticsearch/es-image/*.go (from $GOROOT)
       	/Users/clayton/projects/tempgo/src/_/Users/clayton/projects/go/src/cluster/addons/fluentd-elasticsearch/es-image/*.go (from $GOPATH)
cannot find package "_/Users/clayton/projects/go/src/cluster/images/etcd/attachlease/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cluster/images/etcd/attachlease/*.go (from $GOROOT)
       	/Users/clayton/projects/tempgo/src/_/Users/clayton/projects/go/src/cluster/images/etcd/attachlease/*.go (from $GOPATH)
cannot find package "_/Users/clayton/projects/go/src/cmd/gendocs/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cmd/gendocs/*.go (from $GOROOT)
       	/Users/clayton/projects/tempgo/src/_/Users/clayton/projects/go/src/cmd/gendocs/*.go (from $GOPATH)
cannot find package "_/Users/clayton/projects/go/src/cmd/genkubedocs/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cmd/genkubedocs/*.go (from $GOROOT)
       	/Users/clayton/projects/tempgo/src/_/Users/clayton/projects/go/src/cmd/genkubedocs/*.go (from $GOPATH)
cannot find package "_/Users/clayton/projects/go/src/cmd/genman/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cmd/genman/*.go (from $GOROOT)
       	/Users/clayton/projects/tempgo/src/_/Users/clayton/projects/go/src/cmd/genman/*.go (from $GOPATH)
cannot find package "_/Users/clayton/projects/go/src/cmd/genswaggertypedocs/*.go" in any of:
       	/usr/local/Cellar/go/1.4.2/libexec/src/_/Users/clayton/projects/go/src/cmd/genswaggertypedocs/*.go (from $GOROOT)
```

### PR DESCRIPTION
**Pull request by dims**
Relax the location of the files a bit (Don't assume the
k8s.io/kubernetes always!)

Fixes #31905

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31913)

### CODE REVIEW

**Comment by dims** [comment]
cc @thockin

**Comment by thockin** [comment]
Why do we need to relax the regex?  I don't want to match things that aren't exact...

**Comment by dims** [comment]
@thockin - my main directory is /Users/dims/kubernetes, everything else works except for this one

**Comment by dims** [comment]
@thockin or the other option is to use KUBE_ROOT or something to construct the sed

**Comment by smarterclayton** [comment]
In my case I have kubernetes symlinked to a different GOPATH (many gopaths, one symlink) - I suspect that's the issue here.

**Comment by dims** [comment]
@smarterclayton @thockin - Here's another attempt. PTAL

File: hack/verify-golint.sh [hunk 1]
```diff
@@ -52,7 +52,7 @@ fi
 
 export IFS=$'\n'
 all_packages=(
-	$(go list -e ./... | egrep -v "/(third_party|vendor|staging|generated|clientset_generated)" | sed 's/k8s.io\/kubernetes\///g')
+	$(go list -e ./... | egrep -v "/(third_party|vendor|staging|generated|clientset_generated)" | sed -r "s/^_${KUBE_ROOT//\//\\/}\///g")
```
Comment (thockin) [inline hack/verify-golint.sh]: This is a heck of a regex.

First, can you change to | to it's more like `s|^_${KUBE_ROOT//\//\\/}\/||g` ?  Reduce some noise :)

Second, what is the `_` for in there?

Third this doesn't match - go list produces strings like "k8s.io/kubernetes/test/utils" - no KUBE_ROOT there.

Comment (dims) [inline hack/verify-golint.sh]: Here's what i see on my mac - current directory is `/Users/dims/kubernetes/kubernetes`

```
[dims@dims-mac 18:01] ~/kubernetes/kubernetes ⟩ go list -e ./... | tail -5
_/Users/dims/kubernetes/kubernetes/vendor/gopkg.in/inf.v0
_/Users/dims/kubernetes/kubernetes/vendor/gopkg.in/natefinch/lumberjack.v2
_/Users/dims/kubernetes/kubernetes/vendor/gopkg.in/yaml.v2
_/Users/dims/kubernetes/kubernetes/vendor/k8s.io/heapster/metrics/api/v1/types
_/Users/dims/kubernetes/kubernetes/vendor/k8s.io/heapster/metrics/apis/metrics/v1alpha1
```

And on my ububtu - current directory is `/home/dims/kubernetes`

```
[dims@ubuntu-brix 19:19] ~/kubernetes ⟩ go list -e ./... | tail -5
_/home/dims/kubernetes/vendor/gopkg.in/inf.v0
_/home/dims/kubernetes/vendor/gopkg.in/natefinch/lumberjack.v2
_/home/dims/kubernetes/vendor/gopkg.in/yaml.v2
_/home/dims/kubernetes/vendor/k8s.io/heapster/metrics/api/v1/types
_/home/dims/kubernetes/vendor/k8s.io/heapster/metrics/apis/metrics/v1alpha1
```

Comment (dims) [inline hack/verify-golint.sh]: So if i run from the GO directory thing, yes i see what you see which is

```
[dims@dims-mac 19:21] ~/go/src/k8s.io/kubernetes ⟩ go list -e ./... | tail -5
k8s.io/kubernetes/vendor/gopkg.in/inf.v0
k8s.io/kubernetes/vendor/gopkg.in/natefinch/lumberjack.v2
k8s.io/kubernetes/vendor/gopkg.in/yaml.v2
k8s.io/kubernetes/vendor/k8s.io/heapster/metrics/api/v1/types
k8s.io/kubernetes/vendor/k8s.io/heapster/metrics/apis/metrics/v1alpha1
```

Comment (thockin) [inline hack/verify-golint.sh]: Yeah, if you run outside of GOPATH, go gives up and throws that leading
underscore in to give you a clue.  Pretty useless IMO.  Maybe make the
regex do both, and document it REALLY WELL

`... | sed -e 's|^k8s.io/kubernetes/||' -e "s|^_${KUBE_ROOT}/\?||"`

Comment (dims) [inline hack/verify-golint.sh]: Ack. will do @thockin

**Comment by dims** [comment]
@smarterclayton does this work for you? PTAL

**Comment by smarterclayton** [comment]
Mostly succeeded but I got this at the end:

```
Some packages passed golint but are not listed in hack/.linted_packages.
Please add them in alphabetical order:

  echo kubernetes/cluster/addons/fluentd-elasticsearch/es-image >> hack/.linted_packages
  echo kubernetes/docs/user-guide/environment-guide/containers/backend >> hack/.linted_packages
  echo kubernetes/docs/user-guide/environment-guide/containers/show >> hack/.linted_packages
  echo kubernetes/docs/user-guide/liveness/image >> hack/.linted_packages
  echo kubernetes/examples >> hack/.linted_packages
  echo kubernetes/examples/apiserver/server >> hack/.linted_packages
  echo kubernetes/examples/explorer >> hack/.linted_packages
  echo kubernetes/examples/https-nginx >> hack/.linted_packages
  echo kubernetes/examples/sharing-clusters >> hack/.linted_packages
  LANG=C sort -o hack/.linted_packages hack/.linted_packages

You can test via this script and commit the result.

```

**Comment by dims** [comment]
@k8s-bot kubemark test this issue: #IGNORE

**Comment by dims** [comment]
@k8s-bot kubemark test this issue: #IGNORE

**Comment by dims** [comment]
Guess if anyone else needs it then we can resurrect this PR

**Comment by thockin** [comment]
:( I don't like seeing good PRs closed - what's the reason?

**Comment by dims** [comment]
@thockin - i can reopen if you wish

**Comment by thockin** [comment]
LGTM

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by dims** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by dims** [comment]
@k8s-bot test this issue: #IGNORE
