### PR TITLE
kube-up: increase download timeout for kubernetes.tar.gz

### LINKED ISSUE #29418: AWS kube-up fails due to download timeout
We download the kube bundle from S3 with curl `--max-time=80`.  But, now that the bundle is well over 1GB, 80 seconds is often not long enough on some of the smaller AWS instances (I think it's a combo of disk slowness, CPU slowness for the SSL and network slowness).

PR coming which bumps it to 300 once I have tested it.

### PR DESCRIPTION
**Pull request by justinsb**
Particularly on smaller instances on AWS, we were hitting the 80 second
timeout now that our image is well over the 1GB mark.

Increase the timeout from 80 seconds to 300 seconds.

Fix #29418

### CODE REVIEW

**Comment by justinsb** [comment]
Not sure how we currently mark this for cherrypick, but I think we'll want to cherrypick this to 1.3

File: cluster/gce/configure-vm.sh [hunk 1]
```diff
@@ -166,7 +166,7 @@ download-or-bust() {
     for url in "${urls[@]}"; do
       local file="${url##*/}"
       rm -f "${file}"
-      if ! curl -f --ipv4 -Lo "${file}" --connect-timeout 20 --max-time 80 --retry 6 --retry-delay 10 "${url}"; then
+      if ! curl -f --ipv4 -Lo "${file}" --connect-timeout 20 --max-time 300 --retry 6 --retry-delay 10 "${url}"; then
```
Comment (mikedanese) [inline cluster/gce/configure-vm.sh]: are either of these files used in aws?

Comment (justinsb) [inline cluster/gce/configure-vm.sh]: configure-vm definitely is: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L21

I was thinking about this though...

1.5 GB  in 80 seconds is about 20 MB/second.    300 seconds is about 5 MB / second.  I would argue we probably shouldn't treat anything over 1MB/s as an error, but a 1500 second timeout just feels ridiculous.  The right answer is to make the download smaller (or skip it entirely), but in the meantime...
