### PR TITLE
Fix race condition in iptables partial sync handling

### LINKED ISSUE #121362: endpoints not configured with MinimizeIPTablesRestore
### What happened?

To test out the MinimizeIPTablesRestore feature enabled in 1.27 by default we enabled the setting in 1.26 and discovered that it appears to not configure endpoints properly everytime.
While the version in 1.26 is still alpha I have not found any significant changes, bug reports or backports in the changelog regarding this.

It seems sometimes kube-proxy does not see that the endpoints of a service need to be updated despite the api endpointslice having changed. This typically is not that visible with externalTrafficPolicy Cluster services as some other endpoint still is configured, but in the case of low replica services or externalTrafficPolicy Local services this can lead to service disruption due to the only endpoint on the local node not getting configured while other components see the update correctly and direct traffic there.

For example this two pod deployment both pods ready since hours:

```
$ kubectl -n ns get pods pod1 pod2-o yaml | grep -B 2 Ready
      lastTransitionTime: "2023-10-19T10:21:19Z"
      status: "True"
      type: Ready
--
      lastTransitionTime: "2023-10-19T10:21:19Z"
      status: "True"
      type: ContainersReady
--
      lastTransitionTime: "2023-10-19T10:20:19Z"
      status: "True"
      type: Ready
--
      lastTransitionTime: "2023-10-19T10:20:19Z"
      status: "True"
      type: ContainersReady

```

and the chain on one node only contains one of the ready endpoints:

```
KUBE-SERVICES -d 10.78.44.163/32 -p tcp -m comment --comment "svc:serviceport loadbalancer IP" -m tcp --dport 4000 -j KUBE-EXT-APW7J2FZSAAP4Z43
KUBE-EXT-APW7J2FZSAAP4Z43 -m comment --comment "masquerade traffic for svc:serviceport external destinations" -j KUBE-MARK-MASQ
KUBE-EXT-APW7J2FZSAAP4Z43 -j KUBE-SVC-APW7J2FZSAAP4Z43
KUBE-SVC-APW7J2FZSAAP4Z43 ! -s 100.64.0.0/13 -d 100.72.16.186/32 -p tcp -m comment --comment "svc:serviceport cluster IP" -m tcp --dport 4000 -j KUBE-MARK-MASQ
KUBE-SVC-APW7J2FZSAAP4Z43 -j KUBE-SEP-JDEM23RCGZCIYUJI
KUBE-SEP-JDEM23RCGZCIYUJI -s 100.64.131.130/32 -j KUBE-MARK-MASQ
KUBE-SEP-JDEM23RCGZCIYUJI -p tcp -m tcp -j DNAT --to-destination 100.64.131.130:4000
```

this situation remains until either the pod readiness changes, a partial sync fails and it does a full resync or kube-proxy is restartet which also full syncs

The kube-proxy logs show nothing unusual, just lots of partial syncs (which in our cluster take about 1-2 seconds for a partial sync while the full sync takes 20-40seconds).

### What did you expect to happen?

On endpoint change the iptables are always configured.

### How can we reproduce it (as minimally and precisely as possible)?

We see this in clusters with 1500 services, 14000 pods and 300 nodes on most nodes for a small handful of the services.
The cluster is running v1.26.9
I have written a very crude script to check for the inconsistencies and fix them via a proxy restart:
https://gist.github.com/juliantaylor/996e0255809cb2077b66dc034ec47f55
I imagine reproducing it is tricky, but maybe someone can run the script in their clusters maybe also in a newer version to see is still a problem.
Note due to races it can report errors while stuff in the cluster is changing, but if a deployment behind an ip is stable and still shows up kube-proxy has not configured it properly. (One could at a check on the ready state transition time in the script to avoid this)

```
./check-iptables-nodes.sh $(kubectl get nodes | awk '{print $1}'
kworker-be-prod-iz2-001
kworker-be-prod-iz2-003
kworker-be-prod-iz2-004
10.78.44.54 cep 1 2 
Cluster service ERROR
10.78.44.53 cep 1 2 
Cluster service ERROR
kubectl -n kube-system delete pod kube-proxy-f3cabbf48bbe893419216de2439c9ae609ae6c8a-llvqk
kworker-be-prod-iz2-005
kworker-be-prod-iz2-006
10.78.44.53 cep 1 2 
Cluster service ERROR
kubectl -n kube-system delete pod kube-proxy-f3cabbf48bbe893419216de2439c9ae609ae6c8a-5sd9r
kworker-be-prod-iz2-008
10.78.44.54 cep 1 2 
Cluster service ERROR
10.78.44.49 cep 1 2 
Cluster service ERROR
10.78.44.53 cep 1 2 
Cluster service ERROR
10.78.44.82 cep 1 2 
Cluster service ERROR
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:25:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>
linux 5.15 flatcar stable
kube-proxy hyperkube image

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
Fixes a race condition in the iptables proxy partial sync handling; the methods that process apiserver events (`proxier.OnServiceUpdated` etc) rely on the change trackers' mutexes rather than the proxier's mutexes (since they don't use any mutable variables in the proxier), but `syncProxyRules` currently makes two separate calls into the change trackers, `PendingUpdates()` and `Update()`, so it's possible that an event could arrive between them, causing the two results to reflect inconsistent state. (https://github.com/kubernetes/kubernetes/issues/121362#issuecomment-1840599101)

#### Which issue(s) this PR fixes:
Fixes #121362

#### Special notes for your reviewer:
This does not add any regression test since the bug is a race condition and I don't think there's any easy way we could force it?

#### Does this PR introduce a user-facing change?
```release-note
Fixes a race condition in the iptables mode of kube-proxy in 1.27 and later
that could result in some updates getting lost (e.g., when a service gets a
new endpoint, the rules for the new endpoint might not be added until
much later).
```

/sig network
/priority important-soon
cc @aojea @juliantaylor

### CODE REVIEW

File: pkg/proxy/endpointslicecache.go [hunk 1]
```diff
@@ -188,25 +188,10 @@ func (cache *EndpointSliceCache) updatePending(endpointSlice *discovery.Endpoint
...
-	return changes
-}
-
-// checkoutChanges returns a list of all endpointsChanges that are
+// checkoutChanges returns a map of all endpointsChanges that are
 // pending and then marks them as applied.
-func (cache *EndpointSliceCache) checkoutChanges() []*endpointsChange {
-	changes := []*endpointsChange{}
+func (cache *EndpointSliceCache) checkoutChanges() map[types.NamespacedName]*endpointsChange {
+	changes := make(map[types.NamespacedName]*endpointsChange)
```
Comment (aojea) [inline pkg/proxy/endpointslicecache.go:194]: this is obtained from `trackerByServiceMap` so there is no risk of collapsing two different changes associated to the same service

File: pkg/proxy/endpoints_test.go [hunk 2]
```diff
@@ -1709,15 +1690,17 @@ func TestCheckoutChanges(t *testing.T) {
 				t.Fatalf("Expected %d changes, got %d", len(tc.expectedChanges), len(changes))
 			}
 
-			for i, change := range changes {
-				expectedChange := tc.expectedChanges[i]
+			for _, change := range changes {
+				// The test only supports 0 or 1 changes, so if we're here,
```
Comment (aojea) [inline pkg/proxy/endpoints_test.go:1694]: I didn't check in detail , but is this because the test can not support more than 1 change or existing testcases only have 0 or 1?

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -1207,7 +1201,7 @@ func (proxier *Proxier) syncProxyRules() {
 		// them in activeNATChains, so they won't get deleted.) However, we have
 		// to still figure out how many chains we _would_ have written to make the
 		// metrics come out right, so we just compute them and throw them away.
-		if tryPartialSync && !serviceChanged.Has(svcName.NamespacedName.String()) && !endpointsChanged.Has(svcName.NamespacedName.String()) {
+		if tryPartialSync && !serviceUpdateResult.UpdatedServices.Has(svcName.NamespacedName) && !endpointUpdateResult.UpdatedServices.Has(svcName.NamespacedName) {
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:1204]: this seems much better and easier to think about

**Comment by aojea** [comment]
only one question about one test, but LGTM

File: pkg/proxy/endpoints_test.go (hunk 2 above)
Comment (danwinship) [reply pkg/proxy/endpoints_test.go:1694]: the latter

**Comment by aojea** [comment]
@danwinship the bot says it needs rebase

**Comment by danwinship** [comment]
it doesn't; the tag is stale...
maybe if I rebase and repush it will notice this time...
