### PR TITLE
[e2e] Fix panicing ingress jobs

### LINKED ISSUE #60381: [failing test] Loadbalancing: L7 GCE
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-ingress

/priority failing-test
/kind bug
/status approved-for-milestone
/sig network

cc @jdumars @jberkus @bowei @MrHohn

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
When a nil error is passed into IsProbableEOF(), test will panic. Ref https://github.com/kubernetes/kubernetes/issues/60381#issuecomment-369353511.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60381

**Special notes for your reviewer**:
/assign @shyamjvs 
cc @krzyzacy 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Need to do more verification. err should not be nil in ingress test.
/hold

**Comment by MrHohn** [comment]
Seems like it can be nil:
https://github.com/kubernetes/kubernetes/blob/6daff5aba1a34bfd0e864ca9330c9cb000c61890/test/e2e/framework/ingress_utils.go#L1305-L1310

Though changing this will break ingress test in another way. Will fix the ingress util func instead.

**Comment by MrHohn** [comment]
Updated PR to fix the ingress util instead.

/assign @bowei 
/hold cancel

**Comment by MrHohn** [comment]
Fix #60588.

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -5110,6 +5110,7 @@ func DumpDebugInfo(c clientset.Interface, ns string) {
 }
 
 // TODO: Get rid of this duplicate function in favour of the one in test/utils.
+// This assumes err is not nil.
```
Comment (shyamjvs) [inline test/e2e/framework/util.go]: Why? I think in general this assumption isn't true (seems to be the case only inside your e2e). Because a 'nil' error isn't a retryable error.

File: test/utils/create_resources.go [hunk 2]
```diff
@@ -50,6 +50,7 @@ func RetryWithExponentialBackOff(fn wait.ConditionFunc) error {
 	return wait.ExponentialBackoff(backoff, fn)
 }
 
+// This assumes err is not nil.
```
Comment (shyamjvs) [inline test/utils/create_resources.go]: Same as above. I think we shouldn't add this comment.

File: test/e2e/framework/util.go (hunk 1 above)
Comment (MrHohn) [reply test/e2e/framework/util.go]: > Why? I think in general this assumption isn't true (seems to be the case only inside your e2e). Because a 'nil' error isn't a retryable error.

Fair enough, let's fix this func to not panic on nil error then.

**Comment by MrHohn** [comment]
@shyamjvs Updated PR, PTAL thanks!

**Comment by shyamjvs** [comment]
Ideally, I would prefer that we fix the `IsProbableEOF` function to not panic in case of nil error (also sth which shouldn't happen in general (i.e unnecessary panics)).

**Comment by MrHohn** [comment]
> Ideally, I would prefer that we fix the IsProbableEOF function to not panic in case of nil error (also sth which shouldn't happen in general (i.e unnecessary panics)).

SGTM, updated PR.

/assign @liggitt

**Comment by shyamjvs** [comment]
Thanks. Will let Jordan lgtm.

**Comment by liggitt** [comment]
I don't object to the panic fix, but why are we passing nil things to IsRetryableAPIError? Passing a nil error to four subfunctions doesn't seem very smart

/approve

**Comment by MrHohn** [comment]
Can anyone apply /status approved-for-milestone? Thanks!

**Comment by krzyzacy** [comment]
done

**Comment by MrHohn** [comment]
> but why are we passing nil things to IsRetryableAPIError? Passing a nil error to four subfunctions doesn't seem very smart

Yeah, will followup on removing those nil calls.

**Comment by MrHohn** [comment]
@krzyzacy Thanks!
