### PR TITLE
Delete evicted pet

### LINKED ISSUE #31098: Petset can't create new pod on other node when pod is evicted
**Description of problem**
Create a petset, when pod is evicted, the petset can't create a new pod on other node and make sure pod is running.

**Kubernetes version** (use `kubectl version`):
v1.4.0-alpha.2.1427+5b6e1c37c66098

**How to reproduce it** (as minimally and precisely as possible):
1. Config kubele eviction-hard="memory.available<${value}"
2. Create a peset and wait all pod is running
3. Make node MemoryPressure=true
4. Check all pod status

**What happened**:
4. pod is evicted and petset can't create new pod and make sure pod is running.
```
[root@dhcp-140-39 ~]# kubectl get pod --show-all
NAME             READY     STATUS    RESTARTS   AGE
hello-petset-0   0/1       Evicted   0          32m
hello-petset-1   0/1       Evicted   0          24m
[root@dhcp-140-39 ~]# kubectl get petset
NAME           DESIRED   CURRENT   AGE
hello-petset   2         2         32m
```
**What you expected to happen**:
4. Petset create new pod on other node and make sure pod is running.

### PR DESCRIPTION
**Pull request by dshulyak**
If pet was evicted by kubelet - it will stuck in this state forever.
By analogy to regular pod we need to re-create pet so that it will
be re-scheduled to another node, so in order to re-create pet
and preserve consitent naming we will delete it in petset controller
and create after that.

fixes: https://github.com/kubernetes/kubernetes/issues/31098

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31777)

### CODE REVIEW

**Comment by dshulyak** [comment]
I will cover this change with tests, but i want first to confirm if my approach makes sense

**Comment by bprashanth** [comment]
Thanks for the pr, will take a look shortly. Currently fighting flakes for 1.4 so may take longer than usual.

File: pkg/controller/petset/pet.go [hunk 1]
```diff
@@ -311,3 +317,7 @@ func (d *defaultPetHealthChecker) isHealthy(pod *api.Pod) bool {
 func (d *defaultPetHealthChecker) isDying(pod *api.Pod) bool {
 	return pod != nil && pod.DeletionTimestamp != nil
 }
+
+func isEvicted(pod *api.Pod) bool {
+	return pod != nil && pod.Status.Phase == api.PodFailed && pod.Status.Reason == "Evicted"
```
Comment (bprashanth) [inline pkg/controller/petset/pet.go]: Lets just do this when phase==failed, @smarterclayton wdyt? 
I think the only situation that happens is when the kubelet rejects the pod because of admission check failure, since we disallow `restartPolicy=Never` on petset.

File: test/e2e/framework/pods.go [hunk 2]
```diff
@@ -109,3 +112,54 @@ func (c *PodClient) mungeSpec(pod *api.Pod) {
...
+			Containers: []api.Container{
+				{
+					Name:            ctnName,
+					Image:           "gcr.io/google-containers/stress:v1",
+					ImagePullPolicy: "Always",
+					Env:             env,
+					// 60 min timeout * 60s / tick per 10s = 360 ticks before timeout => ~11.11Mi/tick
+					// to fill ~4Gi of memory, so initial ballpark 12Mi/tick.
+					// We might see flakes due to timeout if the total memory on the nodes increases.
+					Args:      []string{"-mem-alloc-size", "12Mi", "-mem-alloc-sleep", "10s", "-mem-total", memLimit},
```
Comment (bprashanth) [inline test/e2e/framework/pods.go]: A simpler test would just force hostPort collision so the kubelet marks the pet as Failed.

File: test/e2e/pet_set_memory_evict_test.go [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+
+	"k8s.io/kubernetes/pkg/api"
+	"k8s.io/kubernetes/pkg/api/resource"
+	"k8s.io/kubernetes/test/e2e/framework"
+
+	. "github.com/onsi/ginkgo"
+	. "github.com/onsi/gomega"
+)
+
+var _ = framework.KubeDescribe("Pet set eviction [Feature:PetSet] [Disruptive] [Slow]", func() {
```
Comment (bprashanth) [inline test/e2e/pet_set_memory_evict_test.go]: just integrate this into the petset e2e?

File: test/e2e/framework/pods.go (hunk 2 above)
Comment (dshulyak) [inline test/e2e/framework/pods.go]: I tried to create 2 pods with same hostPort and it resulted in different behavior. Second pod is stuck in Pending state with following logs in scheduler:

```
factory.go:517] Error scheduling default nginx: pod (nginx) failed to fit in any node
```

After i removed 1st - 2nd was successfully created

**Comment by derekwaynecarr** [comment]
@dshulyak -- this PR helps me understand the problem better... basically, pet set was not handling the failure state correctly, and the problem was not eviction in kubelet per se.

File: test/e2e/framework/pods.go (hunk 2 above)
Comment (bprashanth) [inline test/e2e/framework/pods.go]: Yeah to do that I suggested you need to cut the scheduler out of the loop, by setting nodeName in the test. kubectl will probably still show `Pending`, but the actual pod phase should be `Failed`.

I'd like to avoid doing it this way if possible, because memory is not going to get reclaimed immeidately. There will be some time after this test has finished and its pods are dead that the kubelet uses for recovery, to swap, evict pages etc. Ensuring this doesn't disrupt the next test will be tricky.

Comment (dshulyak) [inline test/e2e/framework/pods.go]: Thanks, that works. You are right, actual pod phase is Failed, but the reason is different

```
  "status": {
    "phase": "Failed",
    "message": "Pod Predicate PodFitsHostPorts failed",
    "reason": "PodFitsHostPorts",
    "startTime": "2016-09-07T07:52:08Z"
  }
```

**Comment by dshulyak** [comment]
@bprashanth reworked test like you suggested. I think it is not exactly eviction, but behavior is the same

File: test/e2e/petset.go [hunk 4]
```diff
@@ -676,12 +821,17 @@ func dec(i int64, exponent int) *inf.Dec {
 }
 
 func newPVC(name string) api.PersistentVolumeClaim {
+	// TODO storage class for vagrant provider https://github.com/kubernetes/kubernetes/issues/32119
```
Comment (dshulyak) [inline test/e2e/petset.go]: i think i missed enable-hostpath-provisioner, will see how it works

**Comment by dshulyak** [comment]
Requires https://github.com/kubernetes/kubernetes/pull/32264 to pass on vagrant cluster

**Comment by dshulyak** [comment]
@bprashanth hi, do you have time to take a look?

File: pkg/controller/petset/pet.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/controller/petset/pet.go]: Yes, agree (sorry for the delay).

File: test/e2e/petset.go [hunk 5]
```diff
@@ -243,6 +243,120 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+		framework.ExpectNoError(err)
+		initialPetPodUID := petPod.UID
+
+		By("waiting until pet pod will enter failed state in namespace " + f.Namespace.Name)
+		Eventually(func() error {
+			petPod, err := f.Client.Pods(f.Namespace.Name).Get(petPod.Name)
+			// if err not nil - pod was already removed and we can move on to the next step
+			if petPod.Status.Phase == api.PodFailed || err != nil {
+				return nil
+			}
```
Comment (bprashanth) [inline test/e2e/petset.go]: please describe what we expect to happen in a comment. This is going to race with the petset controller which deletes/recreates pods in parallel right? overall it might work out because of the polling, but feels sketchy. 

We want to prove that in 2minutes the pod enteres failed, and gets recreatd by the petset controller. A more exact way to do this would be via watch (either use `watch.until` or setup your own watch like eg test/e2e/daemon_restart.go), you will get both a delete event, and a recreate for the new pet. 

maybe its sufficient to just poll till the uid changes at least once?

File: test/e2e/petset.go [hunk 6]
```diff
@@ -243,6 +243,120 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+		podMounts := []api.VolumeMount{{Name: "home", MountPath: "/home"}}
+		ps := newPetSet(petSetName, f.Namespace.Name, headlessSvcName, 1, petMounts, podMounts, labels)
+		petContainer := &ps.Spec.Template.Spec.Containers[0]
+		petContainer.Ports = append(petContainer.Ports, conflictingPort)
+		ps.Spec.Template.Spec.NodeName = node.Name
+		_, err = f.Client.Apps().PetSets(f.Namespace.Name).Create(ps)
+		framework.ExpectNoError(err)
+
+		By("waiting until pod " + podName + " pet pod " + petPodName + " will be created in namespace " + f.Namespace.Name)
+		Eventually(func() error {
```
Comment (bprashanth) [inline test/e2e/petset.go]: isnt' there a better way to waitForPodRunning? probably in the framework.util library?

File: test/e2e/petset.go [hunk 7]
```diff
@@ -243,6 +243,120 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+					},
+				},
+				NodeName: node.Name,
+			},
+		}
+		pod, err := f.Client.Pods(f.Namespace.Name).Create(pod)
+		framework.ExpectNoError(err)
+
+		By("creating petset with conflicting port in namespace " + f.Namespace.Name)
+		petMounts := []api.VolumeMount{{Name: "datadir", MountPath: "/data/"}}
```
Comment (bprashanth) [inline test/e2e/petset.go]: does this test actually need volumes? if not suggest not using them as they're a source of leakage

Comment (dshulyak) [inline test/e2e/petset.go]: done

File: test/e2e/petset.go (hunk 6 above)
Comment (dshulyak) [inline test/e2e/petset.go]: done

File: test/e2e/petset.go (hunk 5 above)
Comment (dshulyak) [inline test/e2e/petset.go]: Yes, the idea was to exit either because a pod was evicted or removed. But i see that it is potential case for a flake. Thanks for the suggestion, i will rework this part

**Comment by dshulyak** [comment]
@bprashanth maybe it is in good shape to get merged?

File: test/e2e/petset.go [hunk 8]
```diff
@@ -243,6 +245,121 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+		if err := f.WaitForPodRunning(podName); err != nil {
+			framework.Failf("Pod %v did not start running: %v", podName, err)
+		}
+
+		var initialPetPodUID types.UID
+		By("waiting until pet pod " + petPodName + " will be recreated and deleted at least once in namespace " + f.Namespace.Name)
+		w, err := f.Client.Pods(f.Namespace.Name).Watch(api.SingleObject(api.ObjectMeta{Name: petPodName}))
+		framework.ExpectNoError(err)
+		// we need to get UID from pod in any state and wait until pet set controller will remove pod atleast once
+		_, err = watch.Until(2*time.Minute, w, func(event watch.Event) (bool, error) {
```
Comment (bprashanth) [inline test/e2e/petset.go]: suggest defining a 5m const and using that as the uniform timeout, in fact there's probably somewhere else in this file that uses the same const

File: test/e2e/petset.go [hunk 9]
```diff
@@ -243,6 +245,121 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+			switch event.Type {
+			case watch.Deleted:
+				if initialPetPodUID == "" {
+					return false, nil
+				}
```
Comment (bprashanth) [inline test/e2e/petset.go]: please log saying "observed delete of pet with name blah uid blah"

File: test/e2e/petset.go [hunk 10]
```diff
@@ -243,6 +245,121 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+				return true, nil
+			}
+			switch t := event.Object.(type) {
+			case *api.Pod:
+				initialPetPodUID = t.UID
```
Comment (bprashanth) [inline test/e2e/petset.go]: please log here saying "observed pet with name blah uid blah in state blah, waiting for petset controller to delete"

File: test/e2e/petset.go [hunk 11]
```diff
@@ -243,6 +245,121 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+			if err != nil {
+				return err
+			}
+			if petPod.Status.Phase != api.PodRunning {
+				return fmt.Errorf("Pod %v is not in running phase: %v", petPod.Name, petPod.Status.Phase)
+			} else if petPod.UID == initialPetPodUID {
+				return fmt.Errorf("Pod %v wasn't recreated: %v == %v", petPod.Name, petPod.UID, initialPetPodUID)
+			}
+			return nil
+		}, 1*time.Minute, 2*time.Second).Should(BeNil())
```
Comment (bprashanth) [inline test/e2e/petset.go]: suggest just giving this 5m, that's the standard timeout we use for pod running/recreate etc in other places.

**Review by bprashanth — COMMENTED** [review]
lgtm just some e2e nits for the last round, sorry for the delay busy with 1.4 release

**Comment by dshulyak** [comment]
Fixed review comments

**Comment by dshulyak** [comment]
@bprashanth ping

File: test/e2e/petset.go [hunk 12]
```diff
@@ -243,6 +247,121 @@ var _ = framework.KubeDescribe("PetSet [Slow] [Feature:PetSet]", func() {
...
+		"foo": "bar",
+		"baz": "blah",
+	}
+	headlessSvcName := "test"
+	podName := "test-pod"
+	petSetName := "web"
+	petPodName := "web-0"
+
+	BeforeEach(func() {
+		framework.SkipUnlessProviderIs("gce", "vagrant")
```
Comment (bprashanth) [inline test/e2e/petset.go]: vagratn == minikube? in that case, do the other petset tests also require similar treatment?

**Comment by bprashanth** [comment]
LGTM sorry for the delay

File: test/e2e/petset.go (hunk 12 above)
Comment (dshulyak) [inline test/e2e/petset.go]: Other tests are using persistent volumes and there was no dynamic storage provisioner for vagrant cluster. But i enabled hostpath provisioner (https://github.com/kubernetes/kubernetes/pull/32264) and now all petset tests should pass with 1 node vagrant cluster for sure.

I will try them and submit PR.

**Comment by dshulyak** [comment]
@k8s-bot gke smoke e2e test this issue: #IGNORE

**Comment by dshulyak** [comment]
@k8s-bot gke e2e test this issue: #28721

**Comment by dshulyak** [comment]
@k8s-bot gke e2e test this issue: #28721

**Comment by dshulyak** [comment]
Looks like i can't make `[k8s.io] Kubectl client [k8s.io] Guestbook application should create and stop a working application [Conformance] 10m53s` pass

My change definitely doesn't affect Guestbook as there is no any pet set in it

**Comment by dshulyak** [comment]
@k8s-bot gke e2e test this issue: #28721

**Comment by dshulyak** [comment]
@k8s-bot gke e2e test this issue: #28721

**Comment by dshulyak** [comment]
@bprashanth can you remove do not merge label?

**Comment by dshulyak** [comment]
@k8s-bot test this
