### PR TITLE
aim to fix runtime class error

### LINKED ISSUE #129949: [Flaking Test] [sig-node] RuntimeClass should reject a Pod requesting a deleted RuntimeClass
### Which jobs are flaking?

- sig-release-master-blocking
  - ci-node-e2e

### Which tests are flaking?

- ci-kubernetes-node-e2e-containerd

### Since when has it been flaking?

- 2025/01/19 02:00 UTC
- 2025/01/21 10:00 UTC
- 2025/01/30 14:00 UTC
- 2025/02/02 06:00 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-node-e2e

### Reason for failure (if possible)

```
error during go run /home/prow/go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go --cleanup -vmodule=*=4 --ssh-env=gce --results-dir=/logs/artifacts --project=k8s-infra-e2e-boskos-055 --zone=us-west1-b --ssh-user=prow --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --test_args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}" --test-timeout=1h5m0s --image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/containerd/image-config-v2.yaml: exit status 1
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
@kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Fix flake with runtime class e2e
#### Which issue(s) this PR fixes:

Fixes #129949

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tallclair** [comment]
> Fixes https://github.com/kubernetes/kubernetes/issues/129949

This isn't actually fixing this, right? Just adding more output for debugging?

**Comment by tallclair** [comment]
The rejection is done by the runtime class admission controller, which uses an informer cache to lookup the runtime class. I'm assuming the deletion just hasn't propogated to the cache yet. https://github.com/kubernetes/kubernetes/blob/491a23f0793a16a3036d17494c29b7a403b604d6/plugin/pkg/admission/runtimeclass/admission.go#L153

I think the best way to fix this is probably just to use `gomega.Eventually(...)` ([example of using Eventually](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/wait.go#L139))for the assertion that the pod is rejected. You could use dry-run to avoid spamming a bunch of pods that need to be cleaned up.

**Comment by kannon92** [comment]
> I think the best way to fix this is probably just to use gomega.Eventually(...) ([example of using Eventually](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/wait.go#L139))for the assertion that the pod is rejected. You could use dry-run to avoid spamming a bunch of pods that need to be cleaned up

This would be hiding a bug though..

We eventually want the pod to fail but there is a race where the pod will still succeed because it is present in the API?

**Comment by tallclair** [comment]
> This would be hiding a bug though..

Yes. This is generally a tradeoff with a lot of E2E tests. I think of it like "sensitivity", and generally we want to tune e2e tests to be less flaky (fewer false positives, even at the cost of more false negatives).

> We eventually want the pod to fail but there is a race where the pod will still succeed because it is present in the cache?

Yes. The timing isn't important to this functionality, but we went eventual (within a reasonable time) consistency.

**Comment by kannon92** [comment]
Added eventually for pod creation. PTAL @tallclair.

File: test/e2e/common/node/runtimeclass.go [hunk 1]
```diff
@@ -375,12 +374,15 @@ func createRuntimeClass(ctx context.Context, f *framework.Framework, name, handl
...
-func expectPodRejection(ctx context.Context, f *framework.Framework, pod *v1.Pod) {
-	_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{})
-	gomega.Expect(err).To(gomega.HaveOccurred(), "should be forbidden")
-	if !apierrors.IsForbidden(err) {
-		framework.Failf("expected forbidden error, got %#v", err)
-	}
+func expectPodRejection(ctx context.Context, f *framework.Framework, rcName string) {
+	gomega.Eventually(ctx, func() error {
+		pod := e2eruntimeclass.NewRuntimeClassPod(rcName)
+		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{})
```
Comment (pohly) [inline test/e2e/common/node/runtimeclass.go:380]:
```suggestion
		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{DryRun: []string{"All"}})
```

> You could use dry-run to avoid spamming a bunch of pods that need to be cleaned up.

Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go]: updated. https://github.com/kubernetes/kubernetes/pull/130009/commits/9fa39276e7d4e7d751efd419e814ea8373a97874

File: test/e2e/common/node/runtimeclass.go [hunk 2]
```diff
@@ -375,12 +374,15 @@ func createRuntimeClass(ctx context.Context, f *framework.Framework, name, handl
...
-func expectPodRejection(ctx context.Context, f *framework.Framework, pod *v1.Pod) {
-	_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{})
-	gomega.Expect(err).To(gomega.HaveOccurred(), "should be forbidden")
-	if !apierrors.IsForbidden(err) {
-		framework.Failf("expected forbidden error, got %#v", err)
-	}
+func expectPodRejection(ctx context.Context, f *framework.Framework, rcName string) {
+	gomega.Eventually(ctx, func() error {
+		pod := e2eruntimeclass.NewRuntimeClassPod(rcName)
+		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{DryRun: []string{"All"}})
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:380]: nit:
```suggestion
		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{DryRun: []string{metav1.DryRunAll}})
```

**Review by tallclair — COMMENTED** [review]
LGTM with a nit

File: test/e2e/common/node/runtimeclass.go (hunk 2 above)
Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go]: rebased and updated.

File: test/e2e/common/node/runtimeclass.go [hunk 3]
```diff
@@ -375,12 +374,15 @@ func createRuntimeClass(ctx context.Context, f *framework.Framework, name, handl
...
-	gomega.Expect(err).To(gomega.HaveOccurred(), "should be forbidden")
-	if !apierrors.IsForbidden(err) {
-		framework.Failf("expected forbidden error, got %#v", err)
-	}
+func expectPodRejection(ctx context.Context, f *framework.Framework, rcName string) {
+	gomega.Eventually(ctx, func() error {
+		pod := e2eruntimeclass.NewRuntimeClassPod(rcName)
+		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{DryRun: []string{metav1.DryRunAll}})
+		if !apierrors.IsForbidden(err) {
+			return err
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:382]: If err is nil then this will return nil, and be marked as success. I think you need a add a `if err == nil` check before this.

File: test/e2e/common/node/runtimeclass.go [hunk 4]
```diff
@@ -56,7 +56,7 @@ var _ = SIGDescribe("RuntimeClass", func() {
 	*/
 	framework.ConformanceIt("should reject a Pod requesting a non-existent RuntimeClass", f.WithNodeConformance(), func(ctx context.Context) {
 		rcName := f.Namespace.Name + "-nonexistent"
-		expectPodRejection(ctx, f, e2eruntimeclass.NewRuntimeClassPod(rcName))
+		expectPodRejection(ctx, f, rcName)
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:59]: Unlike the delete case, this one should never pass.

You could change `expectPodRejection` to return an error, and then apply the appropriate expectation at each caller (i.e. this becomes somtehing like `gomega.Expect(checkPodRejection()).ToBe(Success())`, and an `Eventually(..)` call below

**Review by tallclair — COMMENTED** [review]
Sorry, missed a few issues in the last round.

**Comment by kannon92** [comment]
/hold

CI issues are relevant for this PR.

File: test/e2e/common/node/runtimeclass.go [hunk 5]
```diff
@@ -375,12 +386,19 @@ func createRuntimeClass(ctx context.Context, f *framework.Framework, name, handl
...
+	_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(ctx, pod, metav1.CreateOptions{DryRun: []string{metav1.DryRunAll}})
+	if err == nil {
+		return fmt.Errorf("should get forbidden error")
+	}
 	if !apierrors.IsForbidden(err) {
-		framework.Failf("expected forbidden error, got %#v", err)
+		return err
 	}
+	// in this case means we got the forbidden error
+	return err
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:401]: Sort of weird to return an error here. Either call this method something like "dryRunRuntimeClassPod", and just have the caller check the error, or keep it "expectPodRejection" and return nil in this case (and only this case).

File: test/e2e/common/node/runtimeclass.go [hunk 6]
```diff
@@ -56,9 +56,11 @@ var _ = SIGDescribe("RuntimeClass", func() {
 	*/
 	framework.ConformanceIt("should reject a Pod requesting a non-existent RuntimeClass", f.WithNodeConformance(), func(ctx context.Context) {
 		rcName := f.Namespace.Name + "-nonexistent"
-		expectPodRejection(ctx, f, e2eruntimeclass.NewRuntimeClassPod(rcName))
-	})
+		err := expectPodRejection(ctx, f, rcName)
+		gotForbiddenError := apierrors.IsForbidden(err)
+		gomega.Expect(gotForbiddenError).To(gomega.BeTrueBecause("we expect a forbidden error"))
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:61]: See comment on `expectPodRejection`. I'd expect this to just be `framework.ExpectNoError(expectPodRejection(...`

Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go:61]: It returns an error though.

Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go:61]: Okay. I will return nil for only rejection error.

Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go]: updated.

File: test/e2e/common/node/runtimeclass.go (hunk 5 above)
Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go]: updated.

File: test/e2e/common/node/runtimeclass.go [hunk 7]
```diff
@@ -176,7 +177,14 @@ var _ = SIGDescribe("RuntimeClass", func() {
...
 		})
 
-		expectPodRejection(ctx, f, e2eruntimeclass.NewRuntimeClassPod(rcName))
+		gomega.Eventually(ctx, func() error {
+			err := expectPodRejection(ctx, f, rcName)
+			if err != nil {
+				return err
+			}
+			// Forbidden error is our intended state for this test case.
+			return nil
```
Comment (tallclair) [inline test/e2e/common/node/runtimeclass.go:186]:
```suggestion
			return expectPodRejection(ctx, f, rcName)
```

Comment (kannon92) [reply test/e2e/common/node/runtimeclass.go]: pushed.

**Comment by tallclair** [comment]
/lgtm
/approve

Thanks for fixing this!

**Review by hashim21223445 — APPROVED** [review]
