### PR TITLE
Fix data race in imageManager test.

### LINKED ISSUE #5611: Data race found in kubelet TestFreeSpaceRemoveByLeastRecentlyUsed
```
W0318 21:00:59.059042    2947 docker.go:728] found a container with the "k8s" prefix, but too few fields (2): "k8s_unidentified"
I0318 21:00:59.059610    2947 container_gc.go:104] Removing unidentified dead container "/k8s_unidentified" with ID "2876"
I0318 21:00:59.065302    2947 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 1024 bytes
==================
WARNING: DATA RACE
Write by goroutine 29:
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.TestFreeSpaceRemoveByLeastRecentlyUsed()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/image_manager_test.go:224 +0x19a
  testing.tRunner()
      /home/shippable/.gvm/gos/go1.3/src/pkg/testing/testing.go:422 +0x10f

Previous read by goroutine 30:
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools.(*FakeDockerClient).ListImages()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/dockertools/fake_docker_client.go:195 +0x6c
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*realImageManager).detectImages()
      github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/_test/_obj_test/image_manager.go:103 +0xf7
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.func·001()
      github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/_test/_obj_test/image_manager.go:90 +0xc2
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.func·003()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:107 +0x5e
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Until()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:108 +0xbb
  github.com/GoogleCloudPlatform/kubernetes/pkg/util.Forever()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:92 +0x47

Goroutine 29 (running) created at:
  testing.RunTests()
      /home/shippable/.gvm/gos/go1.3/src/pkg/testing/testing.go:504 +0xb46
  testing.Main()
      /home/shippable/.gvm/gos/go1.3/src/pkg/testing/testing.go:435 +0xa2
  main.main()
      github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/_test/_testmain.go:321 +0x18b

Goroutine 30 (running) created at:
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.(*realImageManager).start()
      github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/_test/_obj_test/image_manager.go:95 +0x1b0
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.newImageManager()
      github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/_test/_obj_test/image_manager.go:67 +0x1f7
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.newRealImageManager()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/image_manager_test.go:40 +0x16a
  github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet.TestFreeSpaceRemoveByLeastRecentlyUsed()
      /home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/image_manager_test.go:220 +0x6f
  testing.tRunner()
      /home/shippable/.gvm/gos/go1.3/src/pkg/testing/testing.go:422 +0x10f
==================
==================
WARNING: DATA RACE
```

### PR DESCRIPTION
**Pull request by vmarmol**
The background monitoring thread was using the DockerClient before we
had written our fake data. This commit stops the background thread from
running during tests.

Fixes #5611.

### CODE REVIEW

File: pkg/kubelet/image_manager_test.go [hunk 1]
```diff
@@ -32,14 +32,17 @@ import (
 
 var zero time.Time
 
-func newRealImageManager(t *testing.T, policy ImageGCPolicy) (*realImageManager, *dockertools.FakeDockerClient, *cadvisor.Mock) {
+func newRealImageManager(policy ImageGCPolicy) (*realImageManager, *dockertools.FakeDockerClient, *cadvisor.Mock) {
 	fakeDocker := &dockertools.FakeDockerClient{
 		RemovedImages: util.NewStringSet(),
 	}
 	mockCadvisor := new(cadvisor.Mock)
-	im, err := newImageManager(fakeDocker, mockCadvisor, policy)
```
Comment (yujuhong) [inline pkg/kubelet/image_manager_test.go]: A quick question (which may not be relevant to this PR). Why does we start the background thread so early (in newImageManager)? This is before kubelet was officially created. Can't we start it later, similar to calling StartGarbageCollection()?

Comment (vmarmol) [inline pkg/kubelet/image_manager_test.go]: I go back and forth on this. We can have all the objects that do housekeeping expose a Start() and have the Kubelet start all of them, or have them start themselves when they're initialized. They'll be in a good, known state and no implementation details leak to the Kubelet (the fact that there are some background threads for example). The downside is that some initialization is done earlier than would otherwise happen and an assumption that calling NewMainKubelet() means you want to start one. I've found that trade-off to be the correct one, but I am happy to hear otherwise.

Today the way we initialize the Kubelet is interesting, we create it, then we start the housekeepings (GC and BirthCry), then we either run the main loop or have it RunOnce. Arguable, we should have all the periodic things start with Run().

Comment (yujuhong) [inline pkg/kubelet/image_manager_test.go]: I am not sure I understand the downside correctly. If calling `NewMainKubelet()` means you want to start an image manager, that should also applies to garbage collection too?

I don't have strong preference, but would be happy to see them be consistent :)

Comment (vmarmol) [inline pkg/kubelet/image_manager_test.go]: Yes, what we have today leaves little reason to separate the garbage collection since we do it right after the new.

We should probably move most of this work to Run(). Today we do it in New(), after New(), and in Run(). The only reason to not do it in New() is when RunOnce() is called, I don't think we want any of those to be running in that case anyways. I'll file an issue and send some PRs tomorrow :)

File: pkg/kubelet/image_manager_test.go [hunk 2]
```diff
@@ -32,14 +32,17 @@ import (
 
 var zero time.Time
 
-func newRealImageManager(t *testing.T, policy ImageGCPolicy) (*realImageManager, *dockertools.FakeDockerClient, *cadvisor.Mock) {
+func newRealImageManager(policy ImageGCPolicy) (*realImageManager, *dockertools.FakeDockerClient, *cadvisor.Mock) {
```
Comment (yujuhong) [inline pkg/kubelet/image_manager_test.go]: This is not a real issue, but it almost tricked me. Looking at the function name, I'd assume this is creating a *real* image manager, but it's using all the fake components :\

**Comment by yujuhong** [comment]
LGTM.

File: pkg/kubelet/image_manager_test.go (hunk 2 above)
Comment (vmarmol) [inline pkg/kubelet/image_manager_test.go]: I'm terrible at names, open to suggestions :) the "real" prefix hasn't been quite working out.

Comment (yujuhong) [inline pkg/kubelet/image_manager_test.go]: You stole my line. I usually tell people I'm terrible at names... ;)
