### PR TITLE
Various exec fixes

### LINKED ISSUE #13394: `echo foo | kubectl exec -i <pod> cat` hangs instead of cleanly exiting
If you run the following

    echo foo | kubectl exec -i <pod> cat

it will print out foo and hang instead of returning control to the user in the shell. This is due to various changes to how go-dockerclient handles attach and exec.

I am working on a fix and will have a PR soon.

### LINKED ISSUE #13395: kubectl exec -it <pod> bash hangs after you type exit
If you run the following

    kubectl exec -it <pod> bash
    # exit

it will hang instead of returning control to the user in the shell. This is due to various changes to how go-dockerclient handles attach and exec.

I am working on a fix and will have a PR soon.

### PR DESCRIPTION
**Pull request by ncdc**
If stdin is noninteractive, the io.Copy from stdin to remoteStdin will
unblock when it finishes reading from stdin. In this case, make sure to
close remoteStdin so the server knows the client won't be sending any
more data. This ensures that the remote process terminates. For example:

```
echo foo | kubectl exec -i <pod> -- cat
```

Without this change, the `cat` process never terminates and `kubectl
exec` hangs.

Fix interactive exec sessions hanging after you type 'exit'.

Add e2e test to cover noninteractive stdin: `echo a | kubectl exec -i <pod>
cat`

Add e2e test to cover psuedo-interactive stdin: `kubectl exec -i <pod> bash`

Prep for sending multiple data frames over multiple streams in remote command
test, which is more likely to find flakes (requires bump of spdystream
once an issue with the frame worker queues not being fully drained when
a goaway frame is received).

Fixes #13394
Fixes #13395

**Release note info**
Fixed hanging when using non-interactive stdin data, e.g.  `echo foo | kubectl exec -i <pod> -- cat`
Fixed interactive `kubectl exec` sessions hanging after you type 'exit'

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton @pmorie @liggitt

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -159,11 +159,19 @@ var _ = Describe("Kubectl client", func() {
...
-			if execOutput != expectedExecOutput {
-				Failf("Unexpected kubectl exec output. Wanted '%s', got '%s'", execOutput, expectedExecOutput)
+			if e, a := "running in container", execOutput; e != a {
+				Failf("Unexpected kubectl exec output. Wanted %q, got %q", e, a)
+			}
+
+			By("executing a command in the container with noninteractive stdin")
+			execOutput = newKubectlCommand("exec", fmt.Sprintf("--namespace=%v", ns), "-i", simplePodName, "cat").
+				withStdinData("abcd1234").
+				exec()
```
Comment (liggitt) [inline test/e2e/kubectl.go]: +1 for tests for this scenario

File: pkg/client/unversioned/remotecommand/remotecommand.go [hunk 2]
```diff
@@ -194,12 +194,19 @@ func (e *Streamer) doStream() error {
 		if err != nil {
 			return err
 		}
-		defer remoteStdin.Reset()
```
Comment (liggitt) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: don't you still need the deferred remoteStdin.Reset() in the case where the remoteStdin `cp` never completes, or does the conn.Close() cover that?

Comment (ncdc) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: I'll check and see, but it's broken until #13324 lands. I can test w/that locally.

Comment (liggitt) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: actually, I'm surprised the remote connection was being held open with the deferred Reset() in place previously

Comment (ncdc) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: It's a bit of a chicken and egg game. With this scenario:

    echo foo | kubectl exec -i <pod> cat

The `cat` command won't terminate until it gets EOF from its stdin. Its stdin comes from the spdy stream. The spdy stream gets its stdin from the non interactive input (`echo foo`). While `foo` is fully read and closed, `doStream` won't exit until `cat` is done, but we aren't resetting `remoteStdin` until `doStream` exits, etc etc etc. This makes sure that `remoteStdin` gets closed/reset as soon as the copy unblocks. Make sense?

Comment (liggitt) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: interesting, the `cp` essentially "intercepts" the EOF, so the remote command never sees it.

Comment (ncdc) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: Hmm, assuming I merged and rebuilt everything locally correctly, trying to exit an interactive shell is hanging. Grrr....

Comment (liggitt) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: the deferred remoteStdin.Close() in the goroutine makes sense, but I would keep the deferred `Reset()` in place

File: test/e2e/kubectl.go (hunk 1 above)
Comment (liggitt) [inline test/e2e/kubectl.go]: actually, it would be easy to add a `withStdin(io.Reader)` helper so we could also test an interactive exec with a  stdin that sends "echo hello\nexit\n", then blocks

Comment (ncdc) [inline test/e2e/kubectl.go]: Good idea. I'll definitely want to add that. Once I figure out why interactive is broken...

Comment (ncdc) [inline test/e2e/kubectl.go]: Blocks via `select {}` or something else?

File: pkg/client/unversioned/remotecommand/remotecommand.go (hunk 2 above)
Comment (ncdc) [inline pkg/client/unversioned/remotecommand/remotecommand.go]: Ok, added it back.

File: test/e2e/kubectl.go (hunk 1 above)
Comment (liggitt) [inline test/e2e/kubectl.go]: Yeah, something like http://play.golang.org/p/zasWBNstx6

**Comment by ncdc** [comment]
@liggitt @smarterclayton PR updated. I *think* I've finally gotten there...

**Comment by liggitt** [comment]
LGTM... the additional e2e tests give me a lot more confidence

**Comment by ncdc** [comment]
And e2e passed, woot!

**Comment by ncdc** [comment]
... oh, for a previous commit. Guess we'll wait a bit longer

**Comment by ncdc** [comment]
e2e failure looks like flakes:

```
[Fail] Services [It] should serve multiport endpoints from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1147

[Fail] Services [It] should serve a basic endpoint from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1147

[Fail] Services [It] should be able to up and down services 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:247
```

@k8s-bot test this please

**Comment by liggitt** [comment]
wondering how to kick what appears to be a hung e2e... @k8s-bot test this again please?

**Comment by ncdc** [comment]
Woot :-)
