### PR TITLE
fix(e2e::network): refactor NoSNAT test 

### LINKED ISSUE #93525: Failing Test [sig-network] NoSNAT [Feature:NoSNAT] [Slow] Should be able to send traffic between Pods without SNAT
**What would you like to be added**:

The test currently only works on Cloud Providers or environments that set the External IP on nodes, because it is using the framework directly to check the IPs of the pods, using a no-snat-test-proxy to check if the Pods are not using SNAT.

However, this can be simplified, removing the no-snat-test-proxy Pod and executing the queries directly in a Pod.

**Why is this needed**:

The test should work in all environments, and it's failing

https://k8s-testgrid.appspot.com/sig-network-kind#sig-network-kind,%20master&include-filter-by-regex=NoSNAT

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

> @aojea: removing the no-snat-test-proxy Pod and executing the queries directly in a Pod

**Which issue(s) this PR fixes**:

Fixes #93525 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
hi @knight42 
the test is failing to me, also adding `e2enetwork.NewNetworkingTestConfig` to the test adds more overhead and complexity (it creates services and additional pods that are not being used)

I was wondering if we can simplify the test, also get rid of the agnhost no-snat-test-* commands.

Let me know what do you think if we rewrite the test to be something like this

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L944-L1026

replacing the service by a pod

**Comment by knight42** [comment]
/cc @aojea

I have simplified the test a bit, and run the test locally and it passed.

File: test/e2e/network/no_snat.go [hunk 1]
```diff
@@ -194,64 +128,22 @@ var _ = SIGDescribe("NoSNAT [Feature:NoSNAT] [Slow]", func() {
...
-			for _, ip := range podIPs {
-				if ip == pip {
+		for _, sourcePod := range pods.Items {
+			for _, targetPod := range pods.Items {
+				if targetPod.Name == sourcePod.Name {
 					continue
 				}
-				ips = append(ips, ip)
+				targetAddr := net.JoinHostPort(targetPod.Status.PodIP, testPodPort)
+				sourceIP, execPodIP := execSourceipTest(sourcePod, targetAddr)
```
Comment (aojea) [inline test/e2e/network/no_snat.go:143]: awesome

**Comment by aojea** [comment]
This is great @knight42 
/lgtm
/assign @hasheddan @mrhohn

Daniel this fixes a failing test, asking for adding it to mileston 1.19 :smile:

**Review by hasheddan — APPROVED** [review]
/lgtm
/milestone v1.19

File: test/e2e/network/no_snat.go [hunk 2]
```diff
@@ -154,29 +108,9 @@ var _ = SIGDescribe("NoSNAT [Feature:NoSNAT] [Slow]", func() {
 			framework.ExpectNoError(err)
 		}
 
-		// In some (most?) scenarios, the test harness doesn't run in the same network as the Pods,
```
Comment (andrewsykim) [inline test/e2e/network/no_snat.go:157]: Do we still need to feed the node IP in `newTestPod` or can that be removed now?

Comment (aojea) [reply test/e2e/network/no_snat.go:157]: I think so, so we test the connectivity from all the nodes in the cluster that is being tested, and make the test predictable

Comment (aojea) [reply test/e2e/network/no_snat.go:157]: we can get rid of all the environment variables though

Comment (andrewsykim) [reply test/e2e/network/no_snat.go:157]: > we can get rid of all the environment variables though

yeah was specifically referring to the NODE_IP env var we're adding to all the tests above. Seems enough to just create a test pod per node without the env var now.

Comment (aojea) [reply test/e2e/network/no_snat.go:157]: duh, scratch my comment, you are absolutely right, nodeName is what we need :upside_down_face:

File: test/e2e/network/no_snat.go [hunk 3]
```diff
@@ -194,64 +97,22 @@ var _ = SIGDescribe("NoSNAT [Feature:NoSNAT] [Slow]", func() {
...
-			for _, ip := range podIPs {
-				if ip == pip {
+		for _, sourcePod := range pods.Items {
+			for _, targetPod := range pods.Items {
+				if targetPod.Name == sourcePod.Name {
 					continue
 				}
-				ips = append(ips, ip)
+				targetAddr := net.JoinHostPort(targetPod.Status.PodIP, testPodPort)
+				sourceIP, execPodIP := execSourceipTest(sourcePod, targetAddr)
```
Comment (andrewsykim) [inline test/e2e/network/no_snat.go:112]: really minor comment: can we refactor the parameters in `execSourceipTest` to be:
```
func execSourceipTest(pod v1.Pod, targetAddress string) (string, string) 
```

Since it no longer for service addresses only.

Comment (andrewsykim) [reply test/e2e/network/no_snat.go:112]: and also maybe move it to `test/e2e/network/utils.go`?

Comment (knight42) [reply test/e2e/network/no_snat.go:112]: sure thing!

File: test/e2e/network/util.go [hunk 4]
```diff
@@ -125,3 +126,37 @@ func CheckSCTPModuleLoadedOnNodes(f *framework.Framework, nodes *v1.NodeList) bo
...
+		if strings.TrimSpace(stdout) == "" {
+			framework.Logf("got empty stdout, retry until timeout")
+			continue
+		}
+		break
+	}
+
+	framework.ExpectNoError(err)
+
+	// The stdout return from RunHostCmd is in this format: x.x.x.x:port or [xx:xx:xx::x]:port
```
Comment (andrewsykim) [inline test/e2e/network/util.go:155]: I suspect this test may fail in some scenarios with v6 cause of the `[ ]` :thinking: 

Something to watch out for in the future.

File: test/e2e/network/util.go [hunk 5]
```diff
@@ -125,3 +126,37 @@ func CheckSCTPModuleLoadedOnNodes(f *framework.Framework, nodes *v1.NodeList) bo
 	}
 	return false
 }
+
+// execSourceIPTest executes curl to access "/clientip" endpoint on target address
+// from pause Pod to check if source ip is preserved.
+func execSourceIPTest(pausePod v1.Pod, targetAddr string) (string, string) {
```
Comment (andrewsykim) [inline test/e2e/network/util.go:132]: Just `pod` instead of `pausePod`?

File: test/e2e/network/util.go (hunk 4 above)
Comment (knight42) [reply test/e2e/network/util.go:155]: looks like `net.SplitHostPort` would strip the brackets: https://play.golang.org/p/YoTX6bnpXas

Comment (andrewsykim) [reply test/e2e/network/util.go:157]: good to know!

**Review by andrewsykim — COMMENTED** [review]
/approve

Can you squash commits please?

**Review by andrewsykim — COMMENTED** [review]
/lgtm

**Comment by knight42** [comment]
looks like `pull-kubernetes-verify` is constantly failing now: #93623
