### PR TITLE
Avoid using tag filters for EC2 API where possible

### LINKED ISSUE #76747: Tag expression results in EC2 API throttling
**What happened**:
When scaling and attaching volumes to very large Kubernetes clusters running on AWS the cloud provider is returning EC2 API throttling errors when attempting to add nodes to the cluster and attach volumes to the nodes.

The reason for this is due to the way the AWS cloud provider uses tags. The tags query combines both a legacy tag and a modern tag into a logical OR filter. This filter is not efficient within the EC2 API and results in the cloud provider being throttled when performing many EC2 API operations.

**What you expected to happen**:
Scaling and volume attachment should succeed without being throttled by EC2.

**How to reproduce it (as minimally and precisely as possible)**:

/kind bug
/sig aws

### PR DESCRIPTION
**Pull request by mcrute**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
For very large clusters these tag filters are not efficient within the EC2 API and will result in rate limiting. Most of these queries have filters that are targeted narrowly enough that the elimination of the tags filter will not return significantly more data but will be executed more efficiently by the EC2 API and reduce the chance of throttling.

Additionally, some API wrappers did not support pagination despite the underlying API calls being paginated. This change adds pagination to prevent accidentally truncating the returned results.

This change, once approved, will also need back-ported to 1.13 and 1.14.

**Which issue(s) this PR fixes**:
Fixes #76747

**Does this PR introduce a user-facing change?**:
```release-note
Limit use of tags when calling EC2 API to prevent API throttling for very large clusters
```

/sig aws
/sig cloud-provider
/priority critical-urgent
/assign @mcrute @justinsb

### CODE REVIEW

File: pkg/cloudprovider/providers/aws/tags.go [hunk 1]
```diff
@@ -247,9 +247,32 @@ func (t *awsTagging) addFilters(filters []*ec2.Filter) []*ec2.Filter {
 		}
 		return filters
 	}
-	// For 1.6, we always recognize the legacy tag, for the 1.5 -> 1.6 upgrade
-	// There are no "or" filters by key, so we look for both the legacy and new key, and then we have to post-filter
-	f := newEc2Filter("tag-key", TagNameKubernetesClusterLegacy, t.clusterTagKey())
+
+	f := newEc2Filter("tag-key", t.clusterTagKey())
```
Comment (zhan849) [inline pkg/cloudprovider/providers/aws/tags.go]: Out of curiosity, why do we use "tag-key" as filter name here but "tag:{name}" filter name in addLegacyFilters?

File: pkg/cloudprovider/providers/aws/tags.go [hunk 2]
```diff
@@ -247,9 +247,32 @@ func (t *awsTagging) addFilters(filters []*ec2.Filter) []*ec2.Filter {
...
+	// So if we end up with no filters; we need to return nil
+	filters = append(filters, f)
+	return filters
+}
+
+// Add additional filters, to match on our tags. This uses the tag for legacy
+// 1.5 -> 1.6 clusters and exists for backwards compatibility
+//
+// This lets us run multiple k8s clusters in a single EC2 AZ
+func (t *awsTagging) addLegacyFilters(filters []*ec2.Filter) []*ec2.Filter {
```
Comment (zhan849) [inline pkg/cloudprovider/providers/aws/tags.go]: I see you are removing quite a few legacy filters from various places including load balancer, routes, and subnets, is this going to change the behavior and cause backward compatibility issues?

File: pkg/cloudprovider/providers/aws/aws.go [hunk 3]
```diff
@@ -1573,13 +1604,30 @@ func (c *Cloud) GetCandidateZonesForDynamicVolume() (sets.String, error) {
...
+	// filters than to call it once with a tag filter that results in a logical
+	// OR. For really large clusters the logical OR will result in EC2 API rate
+	// limiting.
+	instances := []*ec2.Instance{}
 
-	instances, err := c.describeInstances(filters)
+	baseFilters := []*ec2.Filter{newEc2Filter("instance-state-name", "running")}
+
+	filters := c.tagging.addFilters(baseFilters)
+	di, err := c.describeInstances(filters)
```
[the remark this answers is not in the document]
Comment (mcrute) [reply pkg/cloudprovider/providers/aws/aws.go]: There are two rate limits at play here; the rate limit for `DescribeInstances` and an overload protection rate limit for some downstream services used by `DescribeInstances`. The previous tag query was particularly inefficient and resulted in the triggering of the downstream overload protection limit which can not be raised. It is significantly more efficient to make two `DescribeInstances` calls with a more simple tag filter than one with the combined filter. It should be possible to raise the `DescribeInstances` rate limit if a user still hits that limit with this update.

File: pkg/cloudprovider/providers/aws/tags.go (hunk 2 above)
Comment (mcrute) [reply pkg/cloudprovider/providers/aws/tags.go]: Removing these filters may result in a few more items being returned from the API calls but those extra items will be filtered out in the existing filtering loops below each change in this PR. The trade-off is that these queries are much more efficient within the EC2 API and are less likely to trigger internal rate limits as was the case with `DescribeInstances`. Given we're already doing a second pass of filtering this code is entirely backwards compatible.

File: pkg/cloudprovider/providers/aws/tags.go (hunk 1 above)
Comment (mcrute) [reply pkg/cloudprovider/providers/aws/tags.go]: I have this backwards... will swap the lines and update.

**Review by micahhausler — APPROVED** [review]
/approve 
/lgtm

File: pkg/cloudprovider/providers/aws/aws.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (zhan849) [reply pkg/cloudprovider/providers/aws/aws.go]: Thanks @mcrute 

I double checked the code, since this function is only used in volume creation, and it is just looking for a set of zones that has running instances from the cluster, would using kube client (`aws.Cloud` already has this) to fetch such information be enough? This will not need to make cloud provider call at all. We can start with List from api server directly and look for optimization by listing from cache.

It is true that there could be a race between node die and and the node actually disappear from api server, but under such condition, there will be more high level reconciliation triggered so we are good.

wanna see what other people thinks about it

File: pkg/cloudprovider/providers/aws/tags.go (hunk 2 above)
Comment (zhan849) [reply pkg/cloudprovider/providers/aws/tags.go]: I see, looks good with recent version, but @justinsb you might wanna check this as well to see if clusters provisioned by legacy kube up (not sure if we still care about it) and old versions of kops are fine.

File: pkg/cloudprovider/providers/aws/aws.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (zhan849) [reply pkg/cloudprovider/providers/aws/aws.go]: Looks like getting zone from kubernetes work - we tried #76976 (same logic but slightly different function calls in the version we use), and before we were able only to create 1 PVC every ~5sec, and now with the reduced calls, we are able to create 50 PVC all at a time and get all volumes bound within 30sec, all pods started running within 90sec.

**Comment by zhan849** [comment]
since there is no objections from community, shall we can proceed and merge it in? cc @mcrute @micahhausler
