### PR TITLE
GIT-110239: fix activeDeadlineSeconds enforcement bug

### LINKED ISSUE #110239: activeDeadlineSeconds not working correctly for Jobs in 1.24.0
### What happened?

Prior to 1.24.0 setting `spec.adctiveDeadlineSeconds` in a Job object (`batch/v1`) would kill the Job and Pods if they ran longer than the integer specified. I tested today with 1.24.0 and it's not working. The Job defined below (for testing) should be killed 10 seconds, but isn't. It's actually being terminated after about 55 seconds.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  activeDeadlineSeconds: 10
  ttlSecondsAfterFinished: 120
  completions: 5
  parallelism: 1
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ctr
        image: alpine:latest
        command: ['sh', '-c', 'echo "TEST" && sleep 60']
```

### What did you expect to happen?

The Job to be killed after 10 seconds as per `activeDeadlineSeconds: 10`. It's worked like this in 1.23.x.

### How can we reproduce it (as minimally and precisely as possible)?

On a cluster running 1.24.0 with the following YAML file called `job.yml`.

**job.yml**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  activeDeadlineSeconds: 10
  ttlSecondsAfterFinished: 120
  completions: 5
  parallelism: 1
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ctr
        image: alpine:latest
        command: ['sh', '-c', 'echo "TEST" && sleep 60']
```

Create the Job.
`kubectl apply -f job.yml`

On Kubernetes clusters earlier than 1.24.0 it would fail after 10 seconds and the following command should show `Warning  DeadlineExceeded  Xs     job-controller  Job was active longer than specified deadline` in the events 10 seconds after the **Pod** is created.

`kubectl describe job test`

```
<SNIP>
Events:
  Type     Reason            Age   From            Message
  ----     ------            ----  ----            -------
  Normal   SuccessfulCreate  16s   job-controller  Created pod: ckad1-kk6jt
  Normal   SuccessfulDelete  6s    job-controller  Deleted pod: ckad1-kk6jt
  Warning  DeadlineExceeded  6s    job-controller  Job was active longer than specified deadline
```

In K8s 1.24.0 it's terminated after about a minute instead of 10 seconds. It works as expected in 1.23.6 and other point versions of 1.23.

### Anything else we need to know?

It works as expected, and documented, in all versions of 1.23 I've tested on.

Docs: https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
All and also local clusters.
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

### PR DESCRIPTION
**Pull request by harshanarayana**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:

The current implementation of the `job_controller.go` fails to enforce the `activeDeadlineSeconds` configuration properly when the `JobReadyPods` feature gate is enabled. 

This causes the pods taking longer than `activeDeadlineSeconds` to not get deleted on time. When the pods actually do get terminated, it will then track this and mark this as `DeadlineExceeded` condition. This is not the documented behaviour of `activeDeadlineSeconds`.  This PR addresses the changes required to fix the same.

#### Which issue(s) this PR fixes:
Fixes #110239

#### Special notes for your reviewer:
Implementation is based on the suggestion from @alculquicondor in https://github.com/kubernetes/kubernetes/issues/110239#issuecomment-1141390385

This changes also modifies one of the existing test to make sure the re-queue behaviour is asserted to prevent future regressions.

#### Does this PR introduce a user-facing change?
```release-note
Fix 1.24 regression that prevented the job controller from enforcing activeDeadlineSeconds when set
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
None
```

### CODE REVIEW

File: pkg/controller/job/job_controller.go [hunk 1]
```diff
@@ -688,6 +688,14 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
 	// make a copy so we don't mutate the shared cache
 	job := *sharedJob.DeepCopy()
 
+	// Let us queue the job back accounting to the activeDeadlineSeconds if the item is not marked to be forgotten
+	defer func(key string, job *batch.Job) {
```
Comment (FillZpp) [inline pkg/controller/job/job_controller.go:692]: First, we'd better put this after `IsJobFinished` check, so that we won't AddAfter a finished job.
Second, why not just put this logic into the existing defer in L716-722 ? You don't have to define the arguments of defer func, for you can directly use them in the function by closure.

Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:692]: Ack. Changed accordingly.

Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:692]: The reason to keep a different defer was because of what was in  https://github.com/kubernetes/kubernetes/blob/4c125cca5621501f1ace2d362eaed297fda0ab37/pkg/controller/job/job_controller.go#L704-L707

However, I think it should be fine if we don't re-queue the event there anyway since the `syncJob` itself is not going to run for unknown `CompletionMode`.

File: pkg/controller/job/job_controller_test.go [hunk 2]
```diff
@@ -1853,6 +1854,17 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
 	if !forget {
 		t.Errorf("Unexpected forget value. Expected %v, saw %v\n", true, forget)
 	}
+	time.Sleep(5 * time.Second)
+	if manager.queue.Len() != 1 {
+		t.Errorf("Unexpected queue length. Expected %d, saw %d\n", 1, manager.queue.Len())
+	}
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: I was just making the same change while fixing the broken test as part of the changes I did. Thanks @aojea

[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]:
```go
err = wait.PollImmediate(1*time.Second, 5*time.Second, func() (done bool, err error) {
		if manager.queue.Len() == 1 {
			return true, nil
		}
		return false, nil
	})
	if err != nil {
		t.Error("job key did not get re-queued to account for activeDeadlineSeconds enforcement")
	}
```
made it as above.

File: pkg/controller/job/job_controller_test.go [hunk 3]
```diff
@@ -1853,14 +1853,33 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
...
-		t.Errorf("Unexpected number of creates.  Expected %d, saw %d\n", 0, len(fakePodControl.Templates))
+	wait.PollImmediate(1*time.Second, 5*time.Second, func() (done bool, err error) {
+		if manager.queue.Len() == 1 {
+			return true, nil
+		}
+		return false, nil
+	})
+	if manager.queue.Len() != 1 {
+		t.Errorf("Unexpected queue length. Expected %d, saw %d\n", 1, manager.queue.Len())
+	}
```
Comment (aojea) [inline pkg/controller/job/job_controller_test.go:1864]: I think that is better if you assert in the error returned by the helper
```suggestion
	err = wait.PollImmediate(1*time.Second, 5*time.Second, func() (done bool, err error) {
		if manager.queue.Len() == 1 {
			return true, nil
		}
		return false, nil
	})
	if err != nil {
		t.Errorf("Unexpected queue length. Expected %d, saw %d\n", 1, manager.queue.Len())
	}
```

anyway, I defer to current code owners for the review , thanks

File: pkg/controller/job/job_controller_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]:
```bash
go test -timeout 2h -run ^TestSyncPastDeadlineJobFinished$ k8s.io/kubernetes/pkg/controller/job -v

=== RUN   TestSyncPastDeadlineJobFinished
I0531 13:17:12.971398   32252 job_controller_test.go:1884] "Conditions stored in Actual Job" conditions=[{Type:Failed Status:True LastProbeTime:2022-05-31 13:17:12.971126 +0530 IST m=+1.017520003 LastTransitionTime:2022-05-31 13:17:12.971126 +0530 IST m=+1.017520145 Reason:DeadlineExceeded Message:Job was active longer than specified deadline}]
--- PASS: TestSyncPastDeadlineJobFinished (1.00s)
PASS
ok  	k8s.io/kubernetes/pkg/controller/job	1.702s
```

File: pkg/controller/job/job_controller_test.go (hunk 3 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: Sorry, I was doing that already. This was the code before I pushed the assertion of the error.

File: pkg/controller/job/job_controller_test.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: @aojea  I also had to do a small tweak and use `wait.Poll` instead to give it an initial delay so that I can get the active deadline item re-queued the right way.

File: pkg/controller/job/job_controller.go [hunk 4]
```diff
@@ -705,6 +705,13 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
 	action := metrics.JobSyncActionReconciling
 
 	defer func() {
+		// Let us queue the job back accounting to the activeDeadlineSeconds. The duration after which it should be
+		// re-queued is activeDeadlineSeconds - time spent after start time.
+		if job.Spec.ActiveDeadlineSeconds != nil {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller.go:710]: This code is duplicated in line 762.

The solution is to move that code out of the if `job.Status.StartTime == nil` conditional. But it should still be conditioned on `jobSuspended(&job)`

File: pkg/controller/job/job_controller_test.go [hunk 5]
```diff
@@ -1853,14 +1853,36 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
 	if !forget {
 		t.Errorf("Unexpected forget value. Expected %v, saw %v\n", true, forget)
 	}
-	if len(fakePodControl.Templates) != 0 {
-		t.Errorf("Unexpected number of creates.  Expected %d, saw %d\n", 0, len(fakePodControl.Templates))
+	// Poll with a delay of 1 second to account for exhausting the active deadline behavior
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1856]: I suggest another approach to this test:

Simply start the job workers with `go manager.Run(ctx, 1)` and use `wait.Poll` to wait for the job to get the Failed condition.

Btw, do not use `context.TODO` like other tests are doing. Create a context with `context.WithCancel()` and defer the cancel function.

File: pkg/controller/job/job_controller.go (hunk 4 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:710]: ack.

In the `defer` call, do you prefer if I did a `job.Status.StartTime  != nil` just to be on the safer side ?

Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:710]: You don't need to do it in the defer. You can do it in line 762 after we know that `StartTime` is set.

Comment (harshanarayana) [reply pkg/controller/job/job_controller.go]: Cool. We are on the same page then.

File: pkg/controller/job/job_controller_test.go (hunk 5 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: ack

File: pkg/controller/job/job_controller.go (hunk 4 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go]: @alculquicondor I've addressed the changes suggested by you including the tests. PTAL.

File: pkg/controller/job/job_controller.go [hunk 6]
```diff
@@ -705,6 +705,14 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
 	action := metrics.JobSyncActionReconciling
 
 	defer func() {
+		// Let us queue the job back accounting to the activeDeadlineSeconds. The duration after which it should be
+		// re-queued is activeDeadlineSeconds - time spent after start time.
+		if !jobSuspended(&job) && job.Spec.ActiveDeadlineSeconds != nil {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller.go:710]: Why do this in defer? It's harder to read and doesn't add much value. You can just do it after the conditional in lines 759 to 762.

Comment (harshanarayana) [reply pkg/controller/job/job_controller.go]: Ack. Changes have been addressed.

Comment (harshanarayana) [reply pkg/controller/job/job_controller.go]: The original intent of keeping in defer was to account for any other return from the `syncJob` other than job finished cases.

File: pkg/controller/job/job_controller_test.go [hunk 7]
```diff
@@ -1827,40 +1828,49 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
+	})
+
+	stopCh := make(chan struct{})
+	sharedInformerFactory.Start(stopCh)
+	ctx, cancel := context.WithCancel(context.TODO())
+
+	defer func() {
+		close(stopCh)
+		cancel()
+	}()
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1848]:
```suggestion
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	sharedInformerFactory.Start(ctx.Done())
```

File: pkg/controller/job/job_controller_test.go [hunk 8]
```diff
@@ -1827,40 +1828,49 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
+
+	go manager.Run(ctx, 1)
 	job := newJob(1, 1, 6, batch.NonIndexedCompletion)
-	activeDeadlineSeconds := int64(10)
+	activeDeadlineSeconds := int64(5)
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1852]: ack

File: pkg/controller/job/job_controller_test.go [hunk 9]
```diff
@@ -1827,40 +1828,49 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
 	}
-	if len(fakePodControl.DeletePodName) != 0 {
-		t.Errorf("Unexpected number of deletes.  Expected %d, saw %d\n", 0, len(fakePodControl.DeletePodName))
+	if err := sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job); err != nil {
+		t.Fatalf("Failed to insert job in index: %v", err)
 	}
-	if actual != nil {
-		t.Error("Unexpected job modification")
+	manager.queue.Add(fmt.Sprintf("%s/%s", job.GetNamespace(), job.GetName()))
+	err = wait.Poll(1*time.Second, 6*time.Second, func() (done bool, err error) {
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1862]: ack

File: pkg/controller/job/job_controller_test.go [hunk 10]
```diff
@@ -1827,40 +1828,49 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
+		t.Error(err)
 	}
-	if len(fakePodControl.DeletePodName) != 0 {
-		t.Errorf("Unexpected number of deletes.  Expected %d, saw %d\n", 0, len(fakePodControl.DeletePodName))
+	if err := sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job); err != nil {
+		t.Fatalf("Failed to insert job in index: %v", err)
 	}
-	if actual != nil {
-		t.Error("Unexpected job modification")
+	manager.queue.Add(fmt.Sprintf("%s/%s", job.GetNamespace(), job.GetName()))
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1861]: This can indeed be cleaned up. Sorry for the trouble. Cleaning it up

File: pkg/controller/job/job_controller_test.go [hunk 11]
```diff
@@ -1827,40 +1828,49 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
-	manager.podControl = &fakePodControl
 	manager.podStoreSynced = alwaysReady
 	manager.jobStoreSynced = alwaysReady
-	var actual *batch.Job
-	manager.updateStatusHandler = func(ctx context.Context, job *batch.Job) (*batch.Job, error) {
-		actual = job
-		return job, nil
-	}
 
+	// Prepend this reactor to avoid un-necessary event related logs from getting triggered if invoked with -v switch
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1836]: Not doing this also causes some random 

```bash
E0601 19:23:35.632044   78339 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foobar.16f4838f87b10148", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"foobar", UID:"e87cbcd6-dba8-4c49-a240-d61d1ba2c104", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"DeadlineExceeded", Message:"Job was active longer than specified deadline", Source:v1.EventSource{Component:"job-controller", Host:""}, FirstTimestamp:time.Date(2022, time.June, 1, 19, 23, 35, 631901000, time.Local), LastTimestamp:time.Date(2022, ti
me.June, 1, 19, 23, 35, 631901000, time.Local), Count:1, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'request namespace does not match object namespace, request: "" object: "default"' (will not retry!)
E0601 19:23:35.632740   78339 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foobar.16f4838f87b10148", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"foobar", UID:"e87cbcd6-dba8-4c49-a240-d61d1ba2c104", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"DeadlineExceeded", Message:"Job was active longer than specified deadline", Source:v1.EventSource{Component:"job-controller", Host:""}, FirstTimestamp:time.Date(2022, time.June, 1, 19, 23, 35, 631901000, time.Local), LastTimestamp:time.Date(2022, ti
me.June, 1, 19, 23, 35, 631964000, time.Local), Count:2, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'request namespace does not match object namespace, request: "" object: "default"' (will not retry!)
```
Errors like this one.  It only happens randomly

[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: Never mind. That won't work either. That will cause a different issue while generating events for pods running in other namespace.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go]: I would say let's ignore it in this unit test.

**Review by mimowo — COMMENTED** [review]
Please revisit he computation of syncDuration for calling AddAfter. In the current form the computation of time appears broken leading to  continous invoking of AddAfter

File: pkg/controller/job/job_controller_test.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: Ack

File: pkg/controller/job/job_controller.go [hunk 12]
```diff
@@ -746,17 +746,19 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
...
-			klog.V(4).Infof("Job %s has ActiveDeadlineSeconds will sync after %d seconds",
-				key, *job.Spec.ActiveDeadlineSeconds)
-			jm.queue.AddAfter(key, time.Duration(*job.Spec.ActiveDeadlineSeconds)*time.Second)
-		}
+	}
+
+	// Let us queue the job back accounting to the activeDeadlineSeconds. The duration after which it should be
+	// re-queued is activeDeadlineSeconds - time spent after start time.
+	if !jobSuspended(&job) && job.Spec.ActiveDeadlineSeconds != nil {
+		syncDuration := time.Duration(*job.Spec.ActiveDeadlineSeconds) - time.Since(job.Status.StartTime.Time)
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:759]: @mimowo @alculquicondor 

```golang
	defer func() {
		// Let us queue the job back accounting to the activeDeadlineSeconds. The duration after which it should be
		// re-queued is activeDeadlineSeconds - time spent after start time.
		if !forget && !jobSuspended(&job) && job.Spec.ActiveDeadlineSeconds != nil {
			syncDuration := time.Duration(time.Duration(*job.Spec.ActiveDeadlineSeconds).Seconds()) - time.Duration(time.Since(job.Status.StartTime.Time).Seconds())
			klog.V(2).InfoS("Job has activeDeadlineSeconds configuration. Will sync this job again", "job", key, "duration", syncDuration, "status", job.Status)
			jm.queue.AddAfter(key, syncDuration)
		}
	}()
```
This seem to ensure that we do not re-queue it back after the item has been marked to be forgotten and addresses the time delta you were mentioning. Does this look all right ?

[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:759]: cc @mimowo  @alculquicondor  after incorporating the changes suggested by @mimowo

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:759]: Hi, any progress on this?

[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:759]: Pushing an update in a few hour.. Sorry. Got held up in some work related items.

[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go]: Changes pushed. PTAL.

**Comment by mimowo** [comment]
@harshanarayana could you double check if the new test is stable for you? I check it locally by this command:
`go test ./pkg/controller/job  -run ^TestSyncPastDeadlineJobFinished$ -count=100` (takes about 2min). It failed 3 out of 3 runs with 1,3,1 individual run failures for me locally.

**Comment by harshanarayana** [comment]
> @harshanarayana could you double check if the new test is stable for you? I check it locally by this command: `go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100` (takes about 2min). It failed 3 out of 3 runs with 1,3,1 individual run failures for me locally.

Checking.

**Comment by harshanarayana** [comment]
@mimowo  @alculquicondor 

```bash
❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100
ok  	k8s.io/kubernetes/pkg/controller/job	119.614s


❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100 -v
---- snipped
I0606 23:05:45.498587   18557 job_controller.go:204] Shutting down job controller
PASS
ok  	k8s.io/kubernetes/pkg/controller/job	120.406s

❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100
ok  	k8s.io/kubernetes/pkg/controller/job	119.116s

```
Ran 3 times and worked every single time! What am I missing ?

File: pkg/controller/job/job_controller_test.go [hunk 13]
```diff
@@ -1827,40 +1827,40 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
+		if err != nil {
+			return false, nil
+		}
+		if len(j.Status.Conditions) == 1 && j.Status.Conditions[0].Reason == "DeadlineExceeded" {
+			return true, nil
+		}
+		return false, nil
+	})
+	if err != nil {
+		t.Error("Job failed to enforce activeDeadlineSeconds configuration")
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1863]: maybe worth logging the status here

File: pkg/controller/job/job_controller.go [hunk 14]
```diff
@@ -775,6 +769,10 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
 		finishedCondition = newCondition(batch.JobFailed, v1.ConditionTrue, "BackoffLimitExceeded", "Job has reached the specified backoff limit")
 	} else if pastActiveDeadline(&job) {
 		finishedCondition = newCondition(batch.JobFailed, v1.ConditionTrue, "DeadlineExceeded", "Job was active longer than specified deadline")
+	} else if job.Spec.ActiveDeadlineSeconds != nil && !jobSuspended(&job) {
+		syncDuration := time.Duration(*job.Spec.ActiveDeadlineSeconds)*time.Second - time.Since(job.Status.StartTime.Time)
+		klog.V(2).InfoS("Job has activeDeadlineSeconds configuration. Will sync this job again", "job", key, "duration", syncDuration, "status", job.Status)
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller.go:774]: Done.

File: pkg/controller/job/job_controller_test.go [hunk 15]
```diff
@@ -1827,40 +1827,40 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
-	manager.podControl = &fakePodControl
 	manager.podStoreSynced = alwaysReady
 	manager.jobStoreSynced = alwaysReady
-	var actual *batch.Job
-	manager.updateStatusHandler = func(ctx context.Context, job *batch.Job) (*batch.Job, error) {
-		actual = job
-		return job, nil
-	}
+
+	ctx, cancel := context.WithCancel(context.TODO())
```
[the remark this answers is not in the document]
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1835]: Done

File: pkg/controller/job/job_controller_test.go (hunk 13 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1863]: Would you prefer a `t.Errorf` or `klog.Info` instead for the status and then fail ?

Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1863]: `t.Errorf("Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in %v", j.Status)` ?

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go]: yes, that sounds good.

File: pkg/controller/job/job_controller_test.go [hunk 16]
```diff
@@ -1827,40 +1827,40 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
 	job.Spec.ActiveDeadlineSeconds = &activeDeadlineSeconds
-	start := metav1.Unix(metav1.Now().Time.Unix()-15, 0)
-	job.Status.StartTime = &start
-	job.Status.Conditions = append(job.Status.Conditions, *newCondition(batch.JobFailed, v1.ConditionTrue, "DeadlineExceeded", "Job was active longer than specified deadline"))
-	sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job)
-	forget, err := manager.syncJob(context.TODO(), testutil.GetKey(job, t))
+	_, err := clientset.BatchV1().Jobs(job.GetNamespace()).Create(ctx, job, metav1.CreateOptions{})
 	if err != nil {
-		t.Errorf("Unexpected error when syncing jobs %v", err)
+		t.Error(err)
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1846]:
```suggestion
		t.Error("Could not create Job: %v", err)
```

File: pkg/controller/job/job_controller_test.go (hunk 13 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go]: Changes have been updated. PTAL

File: pkg/controller/job/job_controller_test.go (hunk 16 above)
Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1846]: Done

**Comment by harshanarayana** [comment]
> @mimowo @alculquicondor
> 
> ```shell
> ❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100
> ok  	k8s.io/kubernetes/pkg/controller/job	119.614s
> 
> 
> ❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100 -v
> ---- snipped
> I0606 23:05:45.498587   18557 job_controller.go:204] Shutting down job controller
> PASS
> ok  	k8s.io/kubernetes/pkg/controller/job	120.406s
> 
> ❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=100
> ok  	k8s.io/kubernetes/pkg/controller/job	119.116s
> ```
> 
> Ran 3 times and worked every single time! What am I missing ?

❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=200                                                                                                                                                                                   
ok  	k8s.io/kubernetes/pkg/controller/job	239.940s

Ran a few more tests in loop. @mimowo So far, no failures on my local testing. I also tested by running a `kind build node-image` and standing up a cluster. Things are working fine there as well. Anything else I should check ?

**Comment by alculquicondor** [comment]
/lgtm

Maybe it's just reaching the timeout. If the k8s CI is flaky, we can increase the timeout to 3s.

**Comment by mimowo** [comment]
@harshanarayana I repeated the test 300 times again and got 6 failures. Indeed, it might be the timeout issue which manifests on my machine. I include some logs from one failure in case they tell you something. 
```
    job_controller_test.go:1863: Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in {[] 2022-06-06 20:33:48.472283094 +0200 CEST m=+243.832841058 <nil> 0 0 0  nil 0xc0009dc354}
I0606 20:33:49.472060 3892298 job_controller.go:204] Shutting down job controller
I0606 20:33:49.472231 3892298 job_controller.go:190] Starting job controller
I0606 20:33:49.472254 3892298 shared_informer.go:255] Waiting for caches to sync for job
I0606 20:33:49.472266 3892298 shared_informer.go:262] Caches are synced for job
I0606 20:33:49.472361 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:49.472481 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:49.472524 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:50.472791 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:50.473648 3892298 job_controller.go:204] Shutting down job controller
E0606 20:33:50.473720 3892298 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foobar.16f61bc160d90337", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"foobar", UID:"d46f4daf-5314-42c0-b042-9fd6e01eb1b1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"DeadlineExceeded", Message:"Job was active longer than specified deadline", Source:v1.EventSource{Component:"job-controller", Host:""}, FirstTimestamp:time.Date(2022, time.June, 6, 20, 33, 50, 472708919, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 20, 33, 50, 472708919, time.Local), Count:1, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'request namespace does not match object namespace, request: "" object: "default"' (will not retry!)
I0606 20:33:50.473339 3892298 event.go:294] "Event occurred" object="default/foobar" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
I0606 20:33:50.474101 3892298 job_controller.go:190] Starting job controller
I0606 20:33:50.474183 3892298 shared_informer.go:255] Waiting for caches to sync for job
I0606 20:33:50.474197 3892298 shared_informer.go:262] Caches are synced for job
I0606 20:33:50.474478 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:50.475207 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:50.475309 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:51.475874 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:51.475926 3892298 event.go:294] "Event occurred" object="default/foobar" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
E0606 20:33:51.475947 3892298 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foobar.16f61bc19ca2977c", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"foobar", UID:"2ce0d273-29d4-4be8-9d90-a7c22722f970", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"DeadlineExceeded", Message:"Job was active longer than specified deadline", Source:v1.EventSource{Component:"job-controller", Host:""}, FirstTimestamp:time.Date(2022, time.June, 6, 20, 33, 51, 475775356, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 20, 33, 51, 475775356, time.Local), Count:1, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'request namespace does not match object namespace, request: "" object: "default"' (will not retry!)
I0606 20:33:51.674143 3892298 job_controller.go:204] Shutting down job controller
I0606 20:33:51.674318 3892298 job_controller.go:190] Starting job controller
I0606 20:33:51.674339 3892298 shared_informer.go:255] Waiting for caches to sync for job
I0606 20:33:51.674348 3892298 shared_informer.go:262] Caches are synced for job
I0606 20:33:51.674490 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:51.674596 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:51.674646 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:52.674872 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:52.674936 3892298 event.go:294] "Event occurred" object="default/foobar" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
E0606 20:33:52.674985 3892298 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"foobar.16f61bc1e4199b0e", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Job", Namespace:"default", Name:"foobar", UID:"7d7bb219-9e93-4203-a107-e2d53a1690cf", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"DeadlineExceeded", Message:"Job was active longer than specified deadline", Source:v1.EventSource{Component:"job-controller", Host:""}, FirstTimestamp:time.Date(2022, time.June, 6, 20, 33, 52, 674757390, time.Local), LastTimestamp:time.Date(2022, time.June, 6, 20, 33, 52, 674757390, time.Local), Count:1, Type:"Warning", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'request namespace does not match object namespace, request: "" object: "default"' (will not retry!)
I0606 20:33:52.875345 3892298 job_controller.go:204] Shutting down job controller
I0606 20:33:52.875559 3892298 job_controller.go:190] Starting job controller
I0606 20:33:52.875596 3892298 shared_informer.go:255] Waiting for caches to sync for job
I0606 20:33:52.875607 3892298 shared_informer.go:262] Caches are synced for job
I0606 20:33:52.875833 3892298 job_controller.go:504] enqueueing job default/foobar
I0606 20:33:53.876095 3892298 job_controller.go:504] enqueueing job default/foobar
--- FAIL: TestSyncPastDeadlineJobFinished (2.00s)
```

**Comment by mimowo** [comment]
Hm, maybe I got confused by the output boundaries between retries as I didn't use the -v flag. When I run with -v flag it seems the output is cleaner, here is an example:

```
=== RUN   TestSyncPastDeadlineJobFinished
I0607 11:49:40.754116 1598184 job_controller.go:204] Shutting down job controller
I0607 11:49:40.754344 1598184 job_controller.go:190] Starting job controller
I0607 11:49:40.754370 1598184 shared_informer.go:255] Waiting for caches to sync for job
I0607 11:49:40.754380 1598184 shared_informer.go:262] Caches are synced for job
I0607 11:49:40.754445 1598184 job_controller.go:504] enqueueing job default/foobar
I0607 11:49:41.754862 1598184 job_controller.go:504] enqueueing job default/foobar
    job_controller_test.go:1863: Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in {[] 2022-06-07 11:49:41.754777156 +0200 CEST m=+87.309423315 <nil> 0 0 0  nil 0xc00005316c}
--- FAIL: TestSyncPastDeadlineJobFinished (2.00s)
```

**Comment by mimowo** [comment]
Ok, It seems the timeout of 2s to poll the events is too strict. I have locally increased the timeout to 10s and got 500 passes. Then I looked at the execution times of the successful runs and got 4 which took 2.2s - those would fail with the current timeout. Thus, I think it would be practical to increase the timeout to at least 3s (or preferrably 5s)  as other may experience the same issue. Note that extending the maximal poll time does not affect the overall test execution by itself.

File: pkg/controller/job/job_controller_test.go [hunk 17]
```diff
@@ -1827,40 +1827,40 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
...
-	}
-	if len(fakePodControl.DeletePodName) != 0 {
-		t.Errorf("Unexpected number of deletes.  Expected %d, saw %d\n", 0, len(fakePodControl.DeletePodName))
+	if err := sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job); err != nil {
+		t.Fatalf("Failed to insert job in index: %v", err)
 	}
-	if actual != nil {
-		t.Error("Unexpected job modification")
+	var j *batch.Job
+	err = wait.Poll(200*time.Millisecond, 2*time.Second, func() (done bool, err error) {
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:1852]: I suggest to increase the timeout. On my machine, which is rather fast, I get the test failing with around 1% frequency. When I increased the polll timeout all test retries pass, but 4 out of 500 took 2.2s. Thus, 3s would make the test stable enough for my env, but maybe 5s would be safer. Note that, the timeout itself does not make the test execute longer.

Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1852]: ACK. Let me change the max timeout to 3s to start with, I will keep an eye on the tests to see if we need to further increase this down the line,

**Comment by harshanarayana** [comment]
> Ok, It seems the timeout of 2s to poll the events is too strict. I have locally increased the timeout to 10s and got 500 passes. Then I looked at the execution times of the successful runs and got 4 which took 2.2s - those would fail with the current timeout. Thus, I think it would be practical to increase the timeout to at least 3s (or preferrably 5s) as other may experience the same issue. Note that extending the maximal poll time does not affect the overall test execution by itself.

Interestingly enough I have tested the 500 one in a loop as well and never once did it fail. BUt I see your point of increasing the max timeout. Currently the test should not have taken more than a second in reality, but that was already getting violated. So the 2 second thing. I don't think there is a problem with increasing the max poll timeout to 3 second to start with. Pushing an update right away.

**Comment by harshanarayana** [comment]
```bash
❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=600 -v | egrep  "TestSyncPastDeadlineJobFinished \(" | sort | uniq

--- PASS: TestSyncPastDeadlineJobFinished (1.00s)
--- PASS: TestSyncPastDeadlineJobFinished (1.01s)
--- PASS: TestSyncPastDeadlineJobFinished (1.20s)
--- PASS: TestSyncPastDeadlineJobFinished (2.20s)

**Comment by mimowo** [comment]
Voila, you got 2.2s as well :) I think 3s should be enough to ensure 0.1% failure rate on most environments.

**Comment by harshanarayana** [comment]
```bash
❯ go test ./pkg/controller/job -run ^TestSyncPastDeadlineJobFinished$ -count=500 -v | egrep  "TestSyncPastDeadlineJobFinished \(" | sort | uniq -c
   6 --- PASS: TestSyncPastDeadlineJobFinished (1.00s)
 493 --- PASS: TestSyncPastDeadlineJobFinished (1.20s)
   1 --- PASS: TestSyncPastDeadlineJobFinished (1.21s)
```

@mimowo  Another thing to notice, I never get > 2s if I run with `-count=500` only once I hit the `-count=600` is when it crosses the 2s mark!

**Comment by harshanarayana** [comment]
> If the flag was generic, say activeDeadlimeTime: 100ms, it would be easier to write faster and more reliable tests.

Indeed. Wonder if this is an acceptable thing to propose ?

**Comment by aojea** [comment]
> it would be easier to write faster and more reliable tests.

I'm not following the entire discussion so forgive me if this comment doesn't apply, but for test depending on clock we use to insert a fake.Clock dependency, so you don't depend on the real time

**Comment by alculquicondor** [comment]
> I'm not following the entire discussion so forgive me if this comment doesn't apply, but for test depending on clock we use to insert a fake.Clock dependency, so you don't depend on the real time

+1 on that, although it requires more refactoring. I think we can do it as a follow up.

We need to backport this fix to 1.24 at least. My general preference for backporting is commits as targeted and small as possible.

**Comment by harshanarayana** [comment]
> +1 on that, although it requires more refactoring. I think we can do it as a follow up.

@alculquicondor @aojea  I would be more than happy to take a stab at it if that is all right. Let me open up a different issue to track this

File: pkg/controller/job/job_controller_test.go [hunk 18]
```diff
@@ -1827,40 +1827,40 @@ func hasTrueCondition(job *batch.Job) *batch.JobConditionType {
 }
 
 func TestSyncPastDeadlineJobFinished(t *testing.T) {
```
Comment (soltysh) [inline pkg/controller/job/job_controller_test.go:1829]: This test doesn't proof your fix is working as expected, with or without the fix the test passes. 
I think we'd need 2 tests:
1. the current one
2. the one where you have `job.Status.StartTime` set when creating a job, this mimics the behavior you're seeing.

**Review by soltysh — APPROVED** [review]
/approve
/hold
I'll let @alculquicondor decide if he wants to land this or wait for @harshanarayana add the missing test

File: pkg/controller/job/job_controller_test.go (hunk 18 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:1829]: You transform this test into a test table, where a boolean controls whether StartTime is set

Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1829]: Ack. Let me push an updated test for this by EOD.

Comment (harshanarayana) [reply pkg/controller/job/job_controller_test.go:1829]: Updated the changes for tests. PTAL. cc @alculquicondor  @soltysh

File: pkg/controller/job/job_controller_test.go [hunk 19]
```diff
@@ -58,11 +58,19 @@ import (
...
 
+func newJobWithName(name string, parallelism, completions, backoffLimit int32, completionMode batch.CompletionMode) *batch.Job {
+	return generateJob(name, parallelism, completions, backoffLimit, completionMode)
+}
+
 func newJob(parallelism, completions, backoffLimit int32, completionMode batch.CompletionMode) *batch.Job {
+	return generateJob("foobar", parallelism, completions, backoffLimit, completionMode)
+}
+
+func generateJob(name string, parallelism, completions, backoffLimit int32, completionMode batch.CompletionMode) *batch.Job {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:69]: nit: just have two functions `newJob` and `newJobWithName`. `newJob` calls `newJobWithName`.

File: pkg/controller/job/job_controller_test.go [hunk 20]
```diff
@@ -1838,29 +1845,53 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
...
-	job.Spec.ActiveDeadlineSeconds = &activeDeadlineSeconds
-	_, err := clientset.BatchV1().Jobs(job.GetNamespace()).Create(ctx, job, metav1.CreateOptions{})
-	if err != nil {
-		t.Errorf("Could not create Job: %v", err)
-	}
-	if err := sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job); err != nil {
-		t.Fatalf("Failed to insert job in index: %v", err)
+	tests := []struct {
+		name      string
+		startTime *metav1.Time
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1850]: make it a boolean instead and create the time within the implementation. Otherwise `time.Now` could be too old for it to be a useful test.

But reiterating: we need to make the test have a fake clock as a follow up.

**Review by alculquicondor — COMMENTED** [review]
You can squash as you fix my latest comments

**Review by alculquicondor — COMMENTED** [review]
/lgtm

Thanks!

Can you please open a cherry-pick for each supported version?

**Comment by harshanarayana** [comment]
> /lgtm
> 
> Thanks!
> 
> Can you please open a cherry-pick for each supported version?

All the way from v1.21 upto v1.24 right ?

**Comment by alculquicondor** [comment]
From 1.22 to newer

**Comment by alculquicondor** [comment]
/hold

wait a second, this needs a release note :)

**Comment by alculquicondor** [comment]
/release-note Fix bug that prevented the job controller from enforcing activeDeadlineSeconds when set

**Comment by alculquicondor** [comment]
/release-note-edit ```Fix bug that prevented the job controller from enforcing activeDeadlineSeconds when set```

**Comment by alculquicondor** [comment]
I don't know if that worked. Could you update the issue description with the suggested release note?

**Comment by harshanarayana** [comment]
@alculquicondor Done. PTAL. Updated the other PRs with the same
