### PR TITLE
Use client set to get nodes configuration

### LINKED ISSUE #106468: [Flake] [Feature:Windows] Memory Limits [Serial] [Slow] Allocatable node memory
### Which jobs are flaking?

ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-serial-slow

### Which tests are flaking?

Kubernetes e2e suite: [sig-windows] [Feature:Windows] Memory Limits [Serial] [Slow] Allocatable node memory should be equal to a calculated allocatable memory value expand_more

### Since when has it been flaking?

this month

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-serial-slow/1460477599246454784

### Reason for failure (if possible)

```
Nov 16 06:35:35.319: INFO: Opening proxy to cluster
Nov 16 06:35:35.319: INFO: Asynchronously running '/home/prow/go/src/k8s.io/kubernetes/_output/bin/kubectl kubectl --server=https://kubetest-p1qgnr1o.francecentral.cloudapp.azure.com --kubeconfig=/root/tmp3820256733/kubeconfig/kubeconfig.francecentral.json --namespace=memory-limit-test-windows-3019 proxy -p 0'
Nov 16 06:35:35.401: INFO: http requesting node kubelet /configz
Nov 16 06:35:35.953: FAIL: Unexpected error:
    <*errors.errorString | 0xc00009e110>: {s: "unexpected EOF"}
    unexpected EOF
occurred
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig windows

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
Instead of opening a proxy use the golang client to query the endpoint

#### Which issue(s) this PR fixes:

Fixes #106468

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows
/assign @marosset

### CODE REVIEW

File: test/e2e/windows/memory_limits.go [hunk 1]
```diff
@@ -184,12 +188,14 @@ func getNodeMemory(f *framework.Framework) nodeMemory {
...
 
 	ginkgo.By("Getting memory details from node status and kubelet config")
-
 	status := nodeList.Items[0].Status
-
 	nodeName := nodeList.Items[0].ObjectMeta.Name
 
-	kubeletConfig, err := e2ekubelet.GetCurrentKubeletConfig(nodeName, f.Namespace.Name, true)
+	framework.Logf("Getting configuration details for node %s", nodeName)
+	request := f.ClientSet.CoreV1().RESTClient().Get().Resource("nodes").Name(nodeName).SubResource("proxy").Suffix("configz")
```
Comment (aojea) [inline test/e2e/windows/memory_limits.go:195]: is this something stable? [the current docs says](https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/#generating-a-file-that-contains-the-current-configuration)

> Caution: The kubelet's configz endpoint is there to help with debugging, and is not a stable part of kubelet behavior. Do not rely on the behavior of this endpoint for production scenarios or for use with automated tools.

Comment (aojea) [reply test/e2e/windows/memory_limits.go:195]: I'm wondering if this can add more flakiness or break in the future , but it is just a comment , not blocking anything

Comment (jsturtevant) [reply test/e2e/windows/memory_limits.go:195]: good call out.  `e2ekubelet.GetCurrentKubeletConfig` was essentially doing the same thing only using kubectl as an external process to open a port so this change is not adding a dependency on that endpoint but changing the way it is called.  In my runs locally I didn't see the flake with this new approach

If in the future this proves to be unstable we can revisit the approach to getting the active configuration.

**Comment by jsturtevant** [comment]
/retest
aks flake is being addressed by https://github.com/Azure/aks-engine/pull/4743

**Comment by marosset** [comment]
> If in the future this proves to be unstable we can revisit the approach to getting the active configuration.

Let's make sure to honor this if needed :)

/lgtm
/approve
