### PR TITLE
Fix nil pointer access panic in kubelet from uninitialized pod allocation checkpoint manager in standalone kubelet scenario

### LINKED ISSUE #116262: VPA panics in standalone kubelets
1. Start a standalone kubelet (not registered to an API server)

2. Manager construction short-circuits `Start()` here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L186-L192

3. VPA state is never initialized here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L195-L200

4. All pod syncs then panic on this line:

https://github.com/kubernetes/kubernetes/blob/a1b12e49eac237a37939642d0c3395008b9ab380/pkg/kubelet/kubelet.go#L2412

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3b5f21f]
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc00073c400, {0xc001816c00?, 0x27, 0x40})
  pkg/kubelet/kubelet.go:2412 +0x4df
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/102884#issuecomment-1454089210_

cc @thockin @vinaykul
/sig node
/kind bug
/priority important-soon

### PR DESCRIPTION
**Pull request by vinaykul**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes: https://github.com/kubernetes/kubernetes/issues/116262

Fixes #116262

#### Special notes for your reviewer:
Testing done:
1. Hacky way but not initializing checpoint manager
2. Pods come up normally with local cluster.
3. Verified local cluster pod resize E2E tests work.
4. Unit tests
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2105,21 +2105,30 @@ func (kl *Kubelet) canAdmitPod(pods []*v1.Pod, pod *v1.Pod) (bool, string, strin
...
+						c.Resources.Requests[v1.ResourceCPU] = resourcesAllocated[v1.ResourceCPU]
+						c.Resources.Requests[v1.ResourceMemory] = resourcesAllocated[v1.ResourceMemory]
+					}
 				}
+				otherPods = append(otherPods, op)
 			}
-			otherPods = append(otherPods, op)
+			attrs.OtherPods = otherPods
+		} else {
+			klog.ErrorS(nil, "pod resource allocation checkpoint manager is not initialized.")
```
Comment (liggitt) [inline pkg/kubelet/kubelet.go:2130]: If checkpoint state is nil in non-error cases (like standalone kubelet) we can't log errors on every pod sync. We'll flood the error log with these otherwise. 

Is there a way we can make VPA inactive/inert for standalone kubelets, since they won't be getting pod updates from the API that change resources?

Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2130]: Thanks for the review and catching this issue. I think I can add a couple of Get interfaces to status manager (similar pattern to GetPodStatus) and avoid these nil checks. I'll work on it.

Comment (vinaykul) [reply pkg/kubelet/kubelet.go:2130]: BTW, how did you find this issue? Is this it: https://github.com/kelseyhightower/standalone-kubelet-tutorial ?

Comment (liggitt) [reply pkg/kubelet/kubelet.go]: > how did you find this issue?

we (GKE) run standalone kubelets, and our CI started failing once the VPA change merged to master

Comment (liggitt) [reply pkg/kubelet/kubelet.go]: > I think I can add a couple of Get interfaces to status manager (similar pattern to GetPodStatus) and avoid these nil checks

Does the VPA feature make sense for a standalone kubelet? I don't think it does. It would be easier to reason about if standalone kubelets didn't ever hit VPA code paths.

Comment (vinaykul) [reply pkg/kubelet/kubelet.go]: Is there a way to repro locally on my mac (ubuntu VM)? (With my company shutting down, I don't have access to GKE anymore)

For the in-place pod resize part of the code, I can optimize away [invocation of handlePodResourcesResize](https://github.com/kubernetes/kubernetes/blob/0270fc75d0f59e1f5a31a810737ac35ac3eeb8a3/pkg/kubelet/kubelet.go#L1841L1843) based on an additional KubeClient==nil check. But, imho, the code that tracks ResourcesAllocated (upon pod addition) and Resize (which will always be "" in this case) should continue to work in its current form consistency with how GetPodStatus/SetPodStatus currently works. (Just by looking at code, they seem to be in play)

Comment (liggitt) [reply pkg/kubelet/kubelet.go]: maybe something like this:

```
mkdir -p /var/run/kubernetes/static-pods

echo "
kind: Pod
apiVersion: v1
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
" > /var/run/kubernetes/static-pods/busybox.yaml

START_MODE=kubeletonly FEATURE_GATES=InPlacePodVerticalScaling=true hack/local-up-cluster.sh
```

but I bet local-up-cluster.sh has atrophied and START_MODE=kubeletonly won't work quite right

Comment (liggitt) [reply pkg/kubelet/kubelet.go]: @SergeyKanzhelev @smarterclayton looks like we have a general test gap for standalone kubelet that regularly causes problems:
* https://github.com/kubernetes/kubernetes/pull/113501
* https://github.com/kubernetes/kubernetes/pull/108442
* https://github.com/kubernetes/kubernetes/issues/108063
* https://github.com/kubernetes/kubernetes/issues/87558
* https://github.com/kubernetes/kubernetes/issues/77174
* https://github.com/kubernetes/kubernetes/pull/75308 (this actually seems similar to this PR in keeping code paths active and trying to add nil checks, which exposed later code to unexpected nils)

Comment (vinaykul) [reply pkg/kubelet/kubelet.go]: > 
> START_MODE=kubeletonly FEATURE_GATES=InPlacePodVerticalScaling=true hack/local-up-cluster.sh
> ```
> 
> but I bet local-up-cluster.sh has atrophied and START_MODE=kubeletonly won't work quite right

Thanks, that works. Needs one additional envvar: 
`POD_MANIFEST_PATH=/var/run/kubernetes/static-pods START_MODE=kubeletonly FEATURE_GATES=InPlacePodVerticalScaling=true hack/local-up-cluster.sh`

Anyways, I have another commitment I need to get to. I'll verify this with the above suggested optimization later in the day today.

Comment (bobbypage) [reply pkg/kubelet/kubelet.go]: Thanks Jordan for raising this, AFAIU I don't think we have good coverage of standalone kubelet in CI today. I think we could extend node e2e to also support a mode where we spin up kubelet in standalone mode specifically and only run static pods as a few tests. 

In general, it may help as well to have an environment we can dedicate to static pod related tests since we have a few issues there that @smarterclayton and others been trying to tackle recently.

Comment (vinaykul) [reply pkg/kubelet/kubelet.go]: Looking more closely, `kubeletonly` mode conveniently brings up just kubelet (POD_MANIFEST_PATH default works) but kubeClient is created. But, I was able to set `kubeDeps.KubeClient = nil` just before NewMainKubelet and get a repro to verify the before & after.

We don't need a new check for `kubeClient==nil` before invoking  handlePodResourcesResize  because `!kubetypes.IsStaticPod(pod)` check achieves the same goal.

File: pkg/kubelet/status/status_manager.go [hunk 2]
```diff
@@ -232,8 +240,33 @@ func (m *manager) State() state.Reader {
 	return m.state
 }
 
+// GetContainerResourceAllocation returns the last checkpointed ResourcesAllocated values
+// If checkpoint manager has not been initialized, it returns nil, false
+func (m *manager) GetContainerResourceAllocation(podUID string, containerName string) (v1.ResourceList, bool) {
```
Comment (liggitt) [inline pkg/kubelet/status/status_manager.go:245]: check nil and return not found before locking?

File: pkg/kubelet/status/status_manager.go [hunk 3]
```diff
@@ -232,8 +240,33 @@ func (m *manager) State() state.Reader {
...
+	if m.state != nil {
+		return m.state.GetContainerResourceAllocation(podUID, containerName)
+	}
+	return nil, false
+}
+
+// GetPodResizeStatus returns the last checkpointed ResizeStaus value
+// If checkpoint manager has not been initialized, it returns nil, false
+func (m *manager) GetPodResizeStatus(podUID string) (v1.PodResizeStatus, bool) {
+	m.podStatusesLock.RLock()
```
Comment (liggitt) [inline pkg/kubelet/status/status_manager.go:257]: check nil and return not found before locking?

File: pkg/kubelet/status/status_manager.go [hunk 4]
```diff
@@ -140,6 +140,12 @@ type Manager interface {
 	// State returns a read-only interface to the internal status manager state.
 	State() state.Reader
```
Comment (liggitt) [inline pkg/kubelet/status/status_manager.go:141]: looks like we have no external callers of State() now... given we're unsure whether it will be nil or not, can we drop this accessor from the interface to keep all nil-handling local?

File: pkg/kubelet/status/status_manager.go [hunk 5]
```diff
@@ -183,23 +189,25 @@ func isPodStatusByKubeletEqual(oldStatus, status *v1.PodStatus) bool {
...
-	if m.kubeClient == nil {
-		klog.InfoS("Kubernetes client is nil, not starting status manager")
-		return
-	}
-
+	// Create pod allocation checkpoint manager even if we don't have a client to allow local get/set of ResourcesAllocated & Resize
 	if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
 		stateImpl, err := state.NewStateCheckpoint(m.stateFileDirectory, podStatusManagerStateFile)
 		if err != nil {
+			//TODO(vinaykul,InPlacePodVerticalScaling): Check if this error should be a critical (stop kubelet) failure
```
Comment (liggitt) [inline pkg/kubelet/status/status_manager.go:196]: we're going to absolutely flood the kubelet error log when the feature is enabled if state ends up nil

File: pkg/kubelet/status/status_manager.go (hunk 2 above)
Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:245]: yes.

File: pkg/kubelet/status/status_manager.go (hunk 4 above)
Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:141]: Yes, this can go.

File: pkg/kubelet/status/status_manager.go (hunk 5 above)
Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:196]: This particular log line? Start() only gets called once when [kubelet is spun up](https://github.com/kubernetes/kubernetes/blob/f461527491effcdbe23814b7481f46723cddda9e/pkg/kubelet/kubelet.go#L1546L1547). Or did I miss something?

I do somehow feel that checkpoint state allocation failure is worthy of panic and get rid of the Errorf in SetPodAllocation and SetPodResizeStatus (which will flood the logs), but I'll go with SME opinions about adding panic here.

Comment (liggitt) [reply pkg/kubelet/status/status_manager.go:196]: no, the places we return errors if state is nil

Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:196]: Got it. The more I think about it, the more I feel that hitting the panic button here and getting rid of nil checks is the better way to go. Let me try it out and see how it looks in code.

File: pkg/kubelet/status/status_manager.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubelet/status/status_manager.go:237]: state will still be nil in all of these functions if the feature gate is disabled. 

sweeping all the callers, it's pretty twisty to tell that all of the call sites are guarded by feature gate checks (these are sometimes called from functions which are only called under feature gate guard, or are called from declared closures which are then invoked inside a feature gate guard)

Comment (liggitt) [reply pkg/kubelet/status/status_manager.go:237]: this PR is an improvement on current state of master, but this still seems like a sharp edge to improve before 1.27 cut

Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:237]: True. I can add feature gates check in these functions as a conservative check that makes it easier for future reviews vs. adding a nil check and forgetting to remove at GA. It is one extra compare and branch instruction we don't need on every pod sync (if we can count on pull & CI tests).

Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:237]: > this PR is an improvement on current state of master, but this still seems like a sharp edge to improve before 1.27 cut

What other things do you want to see fixed? I initially wanted to move away from node local checkpoint in favor of relying on values persisted in PodStatus (if it is legit use of [KEP 2527](https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/2527-clarify-status-observations-vs-rbac)), but that wouldn't fly in standalone kubelet scenario. I feel kubelet could use a more generic KV abstraction that better decouples the checkpointing implementation details, but that is a bit larger scope work.. jmho.

Comment (liggitt) [reply pkg/kubelet/status/status_manager.go:237]: probably not leaving those manager methods NPE landmines if the feature-gate is disabled? either doing nil checks in those functions, or assigning a dummy/no-op impl to `state` when the feature gate is off

but a follow-up is fine... I'm more concerned with getting alpha standalone clusters green again at this point

Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:237]: no-op is a good idea. Since this fix is urgent and already LTGM'd, I'll create a separate PR follow-up or tack it on to an existing follow-up PR.

**Comment by vinaykul** [comment]
The containerd/main e2e test I care about has passed. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116271/pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2/1633119440885256192

File: pkg/kubelet/status/status_manager.go (hunk 2 above)
Comment (vinaykul) [reply pkg/kubelet/status/status_manager.go:237]: Does PR https://github.com/kubernetes/kubernetes/pull/116351 get it done?
