### PR TITLE
wait for federation informer store to catch up before update

### LINKED ISSUE #33838: TestNamespaceController {namespace}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/17573/

Failed: TestNamespaceController {namespace}

```
panic: interface conversion: interface is nil, not *v1.Namespace
/usr/local/go/src/runtime/panic.go:481 +0x3ff
/usr/local/go/src/testing/testing.go:467 +0x22a
/usr/local/go/src/runtime/panic.go:443 +0x521
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:170 +0x70
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:119 +0x1bed
/usr/local/go/src/testing/testing.go:473 +0xdd
/usr/local/go/src/testing/testing.go:582 +0xae3
```

Previous issues for this test: #30855

### PR DESCRIPTION
**Pull request by sjenning**
Fixes #33838 #33880 

There is a flake in the federation-controller code where an update to a resource is done too quickly after the create.  Because the resource is not yet in the federated informer store, when the reconcile<Resource>() is called, it can't find the resource and treats the change as a create rather than a update.

This causes a failure (actually a panic) in the test code, which expects an update event, not a create, in response to the resource modification.

@derekwaynecarr @apelisse @mwielgus

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33866)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
A less hacky way to achieve this might be to poll the federated informer store in the ingress controller directly from the unit test.  That way you'd know exactly when to continue, rather than guessing at 1 second. The reason the unit tests are inside the same package as the actuall controller is to allow them to do dirty things like this :-)

**Comment by sjenning** [comment]
@apelisse @quinton-hoole Just pushed a better version. Now it polls the informer store to ensure the entry is present before proceeding.

**Comment by sjenning** [comment]
@k8s-bot kubemark e2e test this

File: federation/pkg/federation-controller/util/test/test_helper.go [hunk 1]
```diff
@@ -211,3 +212,20 @@ func NewCluster(name string, readyStatus api_v1.ConditionStatus) *federation_api
 		},
 	}
 }
+
+// Ensure a key is in the store before returning (or timeout w/ error)
+func WaitForStoreUpdate(store util.FederatedReadOnlyStore, clusterName, key string, timeout time.Duration) error {
+	timeoutEnd := time.Now().Add(timeout)
+	retryInterval := 100 * time.Millisecond
+	for time.Now().Before(timeoutEnd) {
```
Comment (ncdc) [inline federation/pkg/federation-controller/util/test/test_helper.go]: Use `wait.PollImmediate` or one of its family members?

File: federation/pkg/federation-controller/util/test/test_helper.go [hunk 2]
```diff
@@ -211,3 +212,20 @@ func NewCluster(name string, readyStatus api_v1.ConditionStatus) *federation_api
 		},
 	}
 }
+
+// Ensure a key is in the store before returning (or timeout w/ error)
+func WaitForStoreUpdate(store util.FederatedReadOnlyStore, clusterName, key string, timeout time.Duration) error {
+	timeoutEnd := time.Now().Add(timeout)
```
Comment (quinton-hoole) [inline federation/pkg/federation-controller/util/test/test_helper.go]: The right idea, but please use wait.Poll from https://github.com/kubernetes/kubernetes/blob/master/pkg/util/wait/wait.go#L158

File: federation/pkg/federation-controller/namespace/namespace_controller_test.go [hunk 3]
```diff
@@ -111,6 +111,12 @@ func TestNamespaceController(t *testing.T) {
 	assert.NotNil(t, createdNamespace)
 	assert.Equal(t, ns1.Name, createdNamespace.Name)
 
+	// Wait for the secret to appear in the informer store
+	err := WaitForStoreUpdate(
+		namespaceController.namespaceFederatedInformer.GetTargetStore(),
+		cluster1.Name, ns1.Name, 10*time.Second)
```
Comment (ncdc) [inline federation/pkg/federation-controller/namespace/namespace_controller_test.go]: Change 10s to `wait.ForeverTestTimeout`? It's 30s instead of 10, but it would be more consistent with other tests.

File: federation/pkg/federation-controller/util/test/test_helper.go (hunk 2 above)
Comment (ncdc) [inline federation/pkg/federation-controller/util/test/test_helper.go]: Jinx!

**Comment by sjenning** [comment]
@ncdc @quinton-hoole updated

**Comment by quinton-hoole** [comment]
Nice!  Thanks @sjenning .  LGTM.

**Comment by madhusudancs** [comment]
Making this a P0 because the issue this is fixing is causing so many other PR tests to fail.

**Comment by madhusudancs** [comment]
@k8s-bot gce e2e test this

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this ISSUE#33979
