### PR TITLE
podIPs order match node IP family preference (Downward API)

### LINKED ISSUE #103263: "fieldPath: status.podIP" may use wrong IP family in dual stack cluster.
#### What happened:

In a dual-stack cluster with IPv4 as default family (first kubelet IP), a container is created with a env var set to  `fieldPath: status.podIP`.

When the container is running, `status.podIP` properly contains the IPv4

```yaml
apiVersion: v1
kind: Pod
metadata:
  …
spec:
  containers:
  - args:
    - --config.file=/etc/alertmanager/config/alertmanager.yaml
    - --storage.path=/alertmanager
    - --data.retention=120h
    - --cluster.listen-address=[$(POD_IP)]:9094
    - --web.listen-address=:9093
    - --web.route-prefix=/
    - --cluster.peer=alertmanager-main-0.alertmanager-operated:9094
    - --cluster.peer=alertmanager-main-1.alertmanager-operated:9094
    - --cluster.peer=alertmanager-main-2.alertmanager-operated:9094
    - --cluster.reconnect-timeout=5m
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
…
status:
  …
  podIP: 10.145.0.149
  podIPs:
  - ip: 10.145.0.149
  - ip: fd00:abba:96fb::7a
```

But at runtime, this env var  (used in container args) is expanded to the pod IPv6 instead of the IPv4.

```
kubectl exec pod/alertmanager-main-0 -- printenv | grep POD_IP
POD_IP=fd00:abba:96fb::7a
```

```
/bin/alertmanager --config.file=/etc/alertmanager/config/alertmanager.yaml --storage.path=/alertmanager --data.retention=120h --cluster.listen-address=[fd00:abba:96fb::7a]:9094 --web.listen-address=:9093 --web.route-prefix=/ --cluster.peer
=alertmanager-main-0.alertmanager-operated:9094 --cluster.peer=alertmanager-main-1.alertmanager-operated:9094 --cluster.peer=alertmanager-main-2.alertmanager-operated:9094 --cluster.reconnect-timeout=5m
```

#### What you expected to happen:

When using `status.podIP`, it should always return the value actually exposed as `status.podIP` and not something else.

#### Environment:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: Bare metal cluster
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux 5.8.0-59-generic 66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin and version (if this is a network-related bug): cilium 1.10
- Others: CRI-O 1.21 + crun.

### PR DESCRIPTION
**Pull request by aojea**
Following up on https://github.com/kubernetes/kubernetes/pull/97979,
we should implement the same logic for the exposed PodIPs in the downward API, so
both values are identical.

In addition, it also fixes a bug that causes panic in the kubelet, because the podIPs object was mutated meanwhile the code was parsing the IP addresses.

xref: https://github.com/kubernetes/kubernetes/pull/102817

#### Additional information

I've tried different approaches, also to filter directly the podIPs in 
https://github.com/kubernetes/kubernetes/blob/5f8f5ab3268b41d45481d2d865716fa04c026aab/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L231

but I've discarded that approach because it has to add a dependeny to the runtimeManager on the kubelet nodeIPs.

Another alternative that I started and stopped because  it is toooo disruptive, is to refactor all code to stop plumbing `podIP` and `podIPs` 

#### What type of PR is this?

/kind bug
Fixes #103263, #102806

```release-note
kubelet: the returned value for PodIPs is the same in the Downward API and in the pod.status.PodIPs field
```

### CODE REVIEW

**Comment by aojea** [comment]
/retest


Kubernetes e2e suite: [sig-node] RuntimeClass should reject a Pod requesting a deleted RuntimeClass [NodeFeature:RuntimeHandler]

**Comment by aojea** [comment]
/priority important-soon

/test pull-kubernetes-integration
TestCertRotationContinuousRequests

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce-ubuntu-containerd

Kubernetes e2e suite: [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (filesystem volmode)] volumeLimits should verify that all csinodes have volume limits expand_less

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -1588,21 +1593,40 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *v1.Pod, podStatus *kubecontaine
...
+}
+
+// convertStatusToAPIStatus creates an api PodStatus for the given pod from
+// the given internal pod status.  It is purely transformative and does not
+// alter the kubelet state at all.
+func (kl *Kubelet) convertStatusToAPIStatus(pod *v1.Pod, podStatus *kubecontainer.PodStatus) *v1.PodStatus {
+	var apiPodStatus v1.PodStatus
+
+	// copy pod status IPs to avoid race conditions with PodStatus #102806
+	podIPs := make([]string, len(podStatus.IPs))
```
Comment (thockin) [inline pkg/kubelet/kubelet_pods.go:1618]: Don't you want `make([]string, 0, len(podStatus.IPs))` ?  Set capacity not size?

File: pkg/kubelet/kubelet_pods.go [hunk 2]
```diff
@@ -1570,16 +1577,14 @@ func (kl *Kubelet) generateAPIPodStatus(pod *v1.Pod, podStatus *kubecontainer.Po
...
-	// first, followed by the first IP of the opposite IP family (if any).
-	podIPs := make([]v1.PodIP, 0, len(podStatus.IPs))
+// sortPodIPs return the PodIPs sorted and truncated by the cluster IP family preference.
+// The runtime pod status may have an arbitrary number of IPs, in an arbitrary order.
+// PodIPs are obtained by: func (m *kubeGenericRuntimeManager) determinePodSandboxIPs()
+// Pick out the first returned IP of the same IP family as the node IP
+// first, followed by the first IP of the opposite IP family (if any)
+// and use them for the Pod.Status.PodIPs and the Downward API environment variables
+func (kl *Kubelet) sortPodIPs(podIPs []string) []string {
+	ips := make([]string, 0, len(podIPs))
```
Comment (thockin) [inline pkg/kubelet/kubelet_pods.go:1587]: does this capacity ever need to be > 2?  Why not just use literal 2?

Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1587]: it can be 1

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1618]: I did wrong the `for` loop to copy, it should not be an `append` it should set the `ip` directly

File: pkg/kubelet/kubelet_pods.go (hunk 2 above)
Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1587]: ah, I got it now

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -1588,21 +1593,40 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *v1.Pod, podStatus *kubecontaine
...
+	var apiPodStatus v1.PodStatus
+
+	// copy pod status IPs to avoid race conditions with PodStatus #102806
+	podIPs := make([]string, len(podStatus.IPs))
+	for j, ip := range podStatus.IPs {
+		podIPs[j] = ip
+	}
+
+	// make podIPs order match node IP family preference #97979
+	podIPs = kl.sortPodIPs(podIPs)
```
Comment (aojea) [inline pkg/kubelet/kubelet_pods.go:1624]: there is some subtle golang thing that disallow this?

Comment (thockin) [reply pkg/kubelet/kubelet_pods.go:1624]: I don't know - is something not working?

Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1624]: it does work, I just pass the slice as argument and override the same variable with the output, I think is fine, but I just wanted to double check

**Comment by thockin** [comment]
No, that;s fine :)

**Comment by thockin** [comment]
This whole sorting things makes me a little uneasy, not going to lie.  But it's already being done elsewhere, so ....

/lgtm
/approve

**Comment by aojea** [comment]
> This whole sorting things makes me a little uneasy, not going to lie. But it's already being done elsewhere, so ....
> 
> /lgtm
> /approve

I think that this is one of the things that goes to the bucket of "needs a refactor", the `podIP` and `podIPs` combo are plumbed in a lot of functions, we no longer need podIP IIUIC .... as I wrote in the description I think that this should be done in the runtime https://github.com/kubernetes/kubernetes/blob/5f8f5ab3268b41d45481d2d865716fa04c026aab/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L231 but that is a big change , adds a new dependency on the kubelet, and there is a big PR to refactor these code https://github.com/kubernetes/kubernetes/pull/102344 in flight, :shrug:
