### PR TITLE
Fix goroutine leaks in ephemeral volume controller test

### LINKED ISSUE #134565: Some goroutine leaks in staging/src/k8s.io/client-go/tools/cache
### What happened?

Blocking Position1:
https://github.com/kubernetes/kubernetes/blob/42ee6dafd55e411a258f6e5d947b1fb95f38a6b5/staging/src/k8s.io/client-go/tools/cache/controller.go#L151

Blocking Position2:
https://github.com/kubernetes/kubernetes/blob/42ee6dafd55e411a258f6e5d947b1fb95f38a6b5/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L1031-L1049

Blocking Position3:
https://github.com/kubernetes/kubernetes/blob/42ee6dafd55e411a258f6e5d947b1fb95f38a6b5/staging/src/k8s.io/client-go/tools/cache/the_real_fifo.go#L207

### What did you expect to happen?

No goroutines leak.

### How can we reproduce it (as minimally and precisely as possible)?

Using goleak at the beginning of the test:
https://github.com/kubernetes/kubernetes/blob/42ee6dafd55e411a258f6e5d947b1fb95f38a6b5/pkg/controller/volume/ephemeral/controller_test.go#L59
Like this:
```
func TestSyncHandler(t *testing.T) {
	defer goleak.VerifyNone(t)
```
The output information is as follow:
```
found unexpected goroutines:
        [Goroutine 63 in state select, with k8s.io/client-go/tools/cache.(*processorListener).pop on top of the stack:
        k8s.io/client-go/tools/cache.(*processorListener).pop(0x34184d0)
        	e:/goProjects/src/kubernetes-master/kubernetes-master/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1031 +0xf8
        k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        	e:/goProjects/src/kubernetes-master/kubernetes-master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x4a
        created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 97
        	e:/goProjects/src/kubernetes-master/kubernetes-master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0x77
...
```

### Anything else we need to know?

_No response_

### Kubernetes version

Latest

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by MyoungHaSong**
## Summary

Fixes #134565

As discussed in the issue, the `TestSyncHandler` test in `pkg/controller/volume/ephemeral/controller_test.go` leaks goroutines because it uses `context.Background()` which never cancels, leaving informer and workqueue goroutines running after test completion.

Now that context support has been added to `tools/cache` (#126387), the informers can be cleanly shut down via context cancellation. This PR:

- Replaces `context.Background()` with `context.WithCancel()` and defers `cancel()`
- Adds `defer informerFactory.Shutdown()` to properly clean up informer goroutines
- Adds `defer ec.queue.ShutDown()` to clean up workqueue goroutines
- Adds `goleak.VerifyTestMain` in `main_test.go` to prevent goroutine leak regressions

The defer ordering ensures `cancel()` is called before `Shutdown()` (LIFO), so informer goroutines are unblocked before waiting for them to finish.

I'd appreciate any feedback on this approach -- happy to adjust if needed.

/sig api-machinery
/kind bug

## Test plan

- [x] `go test ./pkg/controller/volume/ephemeral/ -count=1` passes with goleak verification
- [x] All three blocking positions reported in #134565 are resolved (controller processLoop, processorListener.pop, FIFO Pop)

```release-note
NONE
```

### CODE REVIEW

**Review by themavik — COMMENTED** [review]
WithCancel, defer cancel before informerFactory.Shutdown, and ec.queue.ShutDown() line up with shared informer shutdown; goleak.VerifyTestMain should catch future leaks. nit: defer runs cancel then Shutdown on exit—keep that ordering if more controllers share the factory in this file.

File: pkg/controller/volume/ephemeral/main_test.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
+/*
+Copyright 2026 The Kubernetes Authors.
```
Comment (carlory) [inline pkg/controller/volume/ephemeral/main_test.go]:
```suggestion
Copyright The Kubernetes Authors.
```

Comment (MyoungHaSong) [reply pkg/controller/volume/ephemeral/main_test.go]: Fixed, thanks! (2266830)

File: pkg/controller/volume/ephemeral/main_test.go [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+import (
+	"testing"
+
+	"go.uber.org/goleak"
+)
+
+func TestMain(m *testing.M) {
+	goleak.VerifyTestMain(m)
+}
```
Comment (soltysh) [inline pkg/controller/volume/ephemeral/main_test.go]: Given this is only verifying the tests in this directory and the controller is verified for leaks in the integration tests let's drop this entire file.

**Review by soltysh — COMMENTED** [review]
one comment about the `main_test.go` and I'll be happy to tag this as is

File: pkg/controller/volume/ephemeral/main_test.go (hunk 2 above)
Comment (MyoungHaSong) [reply pkg/controller/volume/ephemeral/main_test.go]: @soltysh Done, dropped the file. (f4977b9)

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by carlory** [comment]
@MyoungHaSong This PR has been approved. It will be merged once 1.36 is released.
