### PR TITLE
don't wait for first kubelet to be ready and drop dummy deploy

### LINKED ISSUE #43815: kubeadm 1.6 is broken due to unconfigured CNI making kubelet NotReady
Initial report in https://github.com/kubernetes/kubeadm/issues/212.

I suspect that this was introduced in https://github.com/kubernetes/kubernetes/pull/43474.

What is going on (all on single master):
1. kubeadm starts configures a kubelet and uses static pods to configure a control plane
1. kubeadm creates node object and waits for kubelet to join and be ready
1. kubelet is never ready and so kubeadm waits forever

In the conditions list for the node:
```
  Ready 		False 	Wed, 29 Mar 2017 15:54:04 +0000 	Wed, 29 Mar 2017 15:32:33 +0000 	KubeletNotReady 		runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

Previous behavior was for the kubelet to join the cluster even with unconfigured CNI.  The user will then typically run a DaemonSet with host networking to bootstrap CNI on all nodes.  The fact that the node never joins means that, fundamentally, DaemonSets cannot be used to bootstrap CNI.

### Edit by @mikedanese: please test patched debian amd64 kubeadm https://github.com/kubernetes/kubernetes/issues/43815#issuecomment-290616036 with fix

### PR DESCRIPTION
**Pull request by mikedanese**
Per https://github.com/kubernetes/kubernetes/issues/43815#issuecomment-290270198, I suggest that we drop both the node ready and the dummy deployment check altogether for 1.6 and move them to a validation phase for 1.7.

I really think we should drop these checks altogether. CreateClientAndWaitForAPI should create a client and wait for the API, not create dummy deployments and wait for nodes to register and be healthy. These are end to end validations and this is the wrong place to do this stuff. We need an explicit final validation phase for this.

```release-note
Fix a deadlock in kubeadm master initialization.
```

Fixes #43815

### CODE REVIEW

File: cmd/kubeadm/app/master/apiclient.go [hunk 1]
```diff
@@ -55,20 +55,11 @@ func CreateClientAndWaitForAPI(file string) (*clientset.Clientset, error) {
...
-			fmt.Println("[apiclient] First node has registered, but is not ready yet")
-			return false, nil
-		}
 
-		fmt.Printf("[apiclient] First node is ready after %f seconds\n", time.Since(start).Seconds())
+		fmt.Printf("[apiclient] First node has registered after %f seconds\n", time.Since(start).Seconds())
 		return true, nil
 	})
 
-	if err := createAndWaitForADummyDeployment(client); err != nil {
```
Comment (feiskyer) [inline cmd/kubeadm/app/master/apiclient.go]: Do we still need this check if the first node has already ready?

Comment (mikedanese) [inline cmd/kubeadm/app/master/apiclient.go]: I suggest we move this and the node ready check to a seperate final validation step. Do you mean we should drop it permanently?

**Comment by jbeda** [comment]
This LGTM but, as noted in #43815, I prefer #43824.  I'm cool with either, though.

File: cmd/kubeadm/app/master/apiclient.go [hunk 2]
```diff
@@ -55,20 +55,11 @@ func CreateClientAndWaitForAPI(file string) (*clientset.Clientset, error) {
...
 			return false, nil
 		}
-		n := &nodeList.Items[0]
-		if !v1.IsNodeReady(n) {
-			fmt.Println("[apiclient] First node has registered, but is not ready yet")
-			return false, nil
-		}
 
-		fmt.Printf("[apiclient] First node is ready after %f seconds\n", time.Since(start).Seconds())
+		fmt.Printf("[apiclient] First node has registered after %f seconds\n", time.Since(start).Seconds())
```
Comment (jbeda) [inline cmd/kubeadm/app/master/apiclient.go]: Nit: you change this comment but don't fix up line 47.  Most users won't parse registered vs. ready though.

File: cmd/kubeadm/app/master/apiclient.go (hunk 1 above)
Comment (feiskyer) [inline cmd/kubeadm/app/master/apiclient.go]: Hmm, just noticed #43824 did this just after firstNodeIsReady

Comment (mikedanese) [inline cmd/kubeadm/app/master/apiclient.go]: I don't think this is the right place to check that. Commented below.

**Comment by mikedanese** [comment]
@jbeda I really think we should drop these checks altogether. CreateClientAndWaitForAPI should create a client and wait for the API, not create dummy deployments and wait for nodes to register and be healthy. These are end to end validations and this is the wrong place to do this stuff. We need an explicit final validation phase for this.

File: cmd/kubeadm/app/master/apiclient.go (hunk 2 above)
Comment (mikedanese) [inline cmd/kubeadm/app/master/apiclient.go]: Fixed

**Comment by kensimon** [comment]
I agree with @mikedanese that it would be better to separate the validation steps so that it's easier to automate the `kubeadm init && kubectl apply cni-plugin.yaml` workflows, or at least have let kubeadm manage the network plugin application for you (see https://github.com/kubernetes/kubeadm/issues/214)

In the mean time I'm good with this PR or mine, but I'll leave it to someone else to make the final judgement here.  Thanks everyone for your help!

**Comment by pipejakob** [comment]
/lgtm

Code looks fine to me, but other reviewers are probably more familiar with the expectations around initialization. I'm happy so long as end-to-end testing works.

**Comment by luxas** [comment]
If we do this (which we probably should), we should _really_ make sure it doesn't break us again. The dummy depkoyment was added because of race conditions when the controller manager and/or scheduler said they were ready while they weren't IIRC (deadlock). So I think the problem with removing this is that we might start getting these race conditions (flakes) instead. I'm not 100 % sure this applies anymore but it should be noted.

Can't we just tolerate the taint for the dummy deployment?

**Comment by mikedanese** [comment]
The race was due to immediately creating the kube-discovery deployment and should not be a problem. I have been and will continue to test this extensively with @pipejakob  before we cut 1.6.1

**Comment by kensimon** [comment]
@luxas apparently tolerations don't work for scheduling new pods on NotReady nodes, the scheduler always excludes those nodes from scheduling regardless of tolerations.  (see the discussion on the other PR: https://github.com/kubernetes/kubernetes/pull/43824#issuecomment-290469045)

But if people are waiting on "which PR?" to proceed, I'm totally willing to say let's just do this one, whatever gets this out the door quickest since 1.6.0 is kind of DOA for new clusters due to this.

**Comment by SadPyro** [comment]
@mikedanese how do i apply your patch to my kubernetes installment?

**Comment by leslau** [comment]
@SadPyro change your apt repo to unstable and update kubeadm

**Comment by luxas** [comment]
LGTM to me as well given the comments above

**Comment by SadPyro** [comment]
@leslau could you tell me my precise movements to do that? how do i change apt repo to unstable?

**Comment by leslau** [comment]
@SadPyro 

`cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial-unstable main
EOF`

**Comment by bgrant0607** [comment]
@mikedanese Do you intend to cherrypick this into the release branch?

**Comment by mikedanese** [comment]
@bgrant0607 it has already been cherry-picked #43837
