### PR TITLE
kubelet: dockershim ExecSync should return context.DeadlineExeceeded on timeout

### LINKED ISSUE #96463: [Failing Test] [k8s.io] Probing container should be restarted with a docker exec liveness probe with timeout [ci-kubernetes-e2e-ubuntu-gce]
**Which jobs are failing**:

`gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)`

**Which test(s) are failing**:

`[k8s.io] Probing container should be restarted with a docker exec liveness probe with timeout`

**Since when has it been failing**:

`11-09-20 18:43 PST`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:214
Nov 10 03:11:15.973: pod container-probe-9373/busybox-723ec292-164c-46d1-b47b-b0761bee2121 - expected number of restarts: 1, found restarts: 0
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/container_probe.go:223
```

**Anything else we need to know**:

Test flipped to failing and has consistently been failing since.
Commit failure started on: https://github.com/kubernetes/kubernetes/commits/734889ed8
Looks like it is related to this PR: https://github.com/kubernetes/kubernetes/pull/94115

/sig node
/priority critical-urgent
/cc @kubernetes/ci-signal 
/assign @hasheddan 
/milestone v1.20

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In https://github.com/kubernetes/kubernetes/pull/94115 we fixed a bug where kubelet did not respect exec probe timeouts. That PR also re-enabled some tests to ensure we don't regress. So far all the tests using containerd have been passing, but some tests using dockershim started to fail (see https://github.com/kubernetes/kubernetes/issues/96463). This wasn't caught during presubmit since jobs that run dockershim only run e2es marked with `[NodeConformance]`. 

The bug is in the CRI implementation of dockershim where it should be returning `context.Deadline` in the ExecSync response instead of `exec.TimedoutError`. `TimedoutError` is actually the error as expected by the prober, which is what should be returned by the gRPC client, not the server. The server is expected to return `context.DeadlineExeceeded`, which results in the cri client returning `TimedoutError` back to the prober. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/96463

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@andrewsykim looks like this may break some of the other probing container tests

**Comment by andrewsykim** [comment]
@hasheddan that's interesting, I thought none of the presubmits run docker (see https://github.com/kubernetes/kubernetes/issues/96463#issuecomment-725516698), but this PR only touches dockreshim.

**Comment by hasheddan** [comment]
@andrewsykim so it looks like the presubmit does use dockershim, but our periodic does not. From the failing test logs:
```
NodeSystemInfo{MachineID:3733c809a1e5b150506bec770a5c5c70,SystemUUID:3733c809-a1e5-b150-506b-ec770a5c5c70,BootID:4cd37059-30d4-4a94-86d5-9a1c18597431,KernelVersion:5.3.0-1016-gke,OSImage:Ubuntu 18.04.4 LTS,ContainerRuntimeVersion:docker://19.3.2,KubeletVersion:v1.20.0-beta.1.466+011d0e2ffaf85f,KubeProxyVersion:v1.20.0-beta.1.466+011d0e2ffaf85f,OperatingSystem:linux,Architecture:amd64,}
```

I know @oomichi tested out that the test did in fact fail without your PR but it wasn't `pull-kubernetes-node-e2e`, it was `pull-kubernetes-e2e-gce-ubuntu-containerd` (see https://github.com/kubernetes/kubernetes/pull/96178). I am looking at differences between the `pull-kubernetes-node-e2e` presubmit and the `gce-ubuntu-master-default` periodic now. I do notice that we are using different Ubuntu versions in each:
- presubmit: `ubuntu-gke-1804-1-16-v20200330`
- periodic: `ubuntu-2004-focal-v20200423`

**Comment by hasheddan** [comment]
@andrewsykim ah found it, we are skipping the test that is failing in the periodic

**Comment by hasheddan** [comment]
xref https://github.com/kubernetes/test-infra/pull/19934

**Comment by dims** [comment]
TODO for @dims : Need to find a optional CI job that uses docker and run that to confirm

**Comment by andrewsykim** [comment]
> TODO for @dims : Need to find a optional CI job that uses docker and run that to confirm

Yes please or just remove dockershim, thanks!

**Comment by andrewsykim** [comment]
(just kidding)

File: pkg/kubelet/dockershim/exec.go [hunk 1]
```diff
@@ -114,22 +112,24 @@ func (*NativeExecHandler) ExecInContainer(client libdocker.Interface, container
 		return err
 	}
 
-	// if ExecProbeTimeout feature gate is disabled, preserve existing behavior to ignore exec timeouts
-	var execTimeout <-chan time.Time
+	execCtx := ctx
```
Comment (andrewsykim) [inline pkg/kubelet/dockershim/exec.go:115]: Problem is that StartExec is actually a blocking call, so turns out the for loop below calling `InspectExec` was never actually called on a running process.

**Comment by andrewsykim** [comment]
Got a green run of `pull-kubernetes-node-e2e` https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/96495/pull-kubernetes-node-e2e/1328344236902322176/ 

Undoing some temporary checks I put in to help debug this.

File: test/e2e/common/container_probe.go [hunk 2]
```diff
@@ -211,7 +212,7 @@ var _ = framework.KubeDescribe("Probing container", func() {
 		Testname: Pod liveness probe, docker exec, restart
 		Description: A Pod is created with liveness probe with a Exec action on the Pod. If the liveness probe call  does not return within the timeout specified, liveness probe MUST restart the Pod.
 	*/
-	ginkgo.It("should be restarted with a docker exec liveness probe with timeout ", func() {
+	ginkgo.It("should be restarted with an exec liveness probe with timeout [NodeConformance]", func() {
```
Comment (andrewsykim) [inline test/e2e/common/container_probe.go:215]: I added this temporarily so that `pull-kubernetes-e2e-node` (running dockershim) would start running this, since that job only runs `[NodeConformance]` tests. This was why this failing test was not caught in https://github.com/kubernetes/kubernetes/pull/94115, since only jobs running containerd ran the full e2e suite. Correct me if I got anything incorrect here @hasheddan. 

I think it's appropriate to add this test to `[NodeConformance]` but I'll defer to SIG Node leads if we're okay with this now or if we should defer this discussion to a separate PR

Comment (hasheddan) [reply test/e2e/common/container_probe.go:215]: @andrewsykim this is mostly correct :+1: I believe right now we actually are split between some of the e2e suite being run against dockershim and some being run against containerd. As @dims pointed out above, it would be a good first step to get an optional test that we can invoke as a presubmit that will run the full test suite against either.

I think you are correct that we need to defer adding `[NodeConformance]` to this test to a separate PR.

File: test/e2e/common/container_probe.go [hunk 3]
```diff
@@ -139,6 +139,7 @@ var _ = framework.KubeDescribe("Probing container", func() {
 		livenessProbe := &v1.Probe{
 			Handler:             execHandler([]string{"cat", "/tmp/health"}),
 			InitialDelaySeconds: 15,
+			TimeoutSeconds:      5, // default 1s can be pretty aggressive in CI environments with low resources
```
Comment (andrewsykim) [inline test/e2e/common/container_probe.go:142]: This test started to flake once dockershim was updated to correctly return DeadlineExceeded grpc status error. It seems like the default 1s timeout was  too aggressive here, my guess is because `pull-kubernetes-e2e-node` is probably very resource starved. I updated this to 5 seconds and the test seems to be passing consistently. 

Increasing the timeout here seems safe, because this test is really expecting that the exit code from the probe returns 0, it should allow for the probe to take longer than the default 1s, as long as it doesn't return a non-zero exit code.

File: pkg/kubelet/dockershim/exec.go [hunk 4]
```diff
@@ -109,53 +105,55 @@ func (*NativeExecHandler) ExecInContainer(client libdocker.Interface, container
...
+	// InspectExec may not always return latest state of exec, so call it a few times until
+	// it returns an exec inspect that shows that the process is no longer running.
+	retries := 0
+	maxRetries := 5
 	ticker := time.NewTicker(2 * time.Second)
 	defer ticker.Stop()
-	count := 0
 	for {
-		select {
-		case <-execTimeout:
```
Comment (andrewsykim) [inline pkg/kubelet/dockershim/exec.go:131]: This timeout check was incorrect because `StartExec` is a blocking call.

File: pkg/kubelet/dockershim/docker_streaming.go [hunk 5]
```diff
@@ -77,17 +81,21 @@ func (r *streamingRuntime) PortForward(podSandboxID string, port int32, stream i
...
+	err := ds.streamingRuntime.exec(ctx, req.ContainerId, req.Cmd,
 		nil, // in
 		ioutils.WriteCloserWrapper(ioutils.LimitWriter(&stdoutBuffer, maxMsgSize)),
 		ioutils.WriteCloserWrapper(ioutils.LimitWriter(&stderrBuffer, maxMsgSize)),
 		false, // tty
 		nil,   // resize
 		timeout)
 
+	if errors.Is(err, context.DeadlineExceeded) {
+		return nil, status.Errorf(codes.DeadlineExceeded, err.Error())
```
Comment (andrewsykim) [inline pkg/kubelet/dockershim/docker_streaming.go:96]: remote_runtime.go expects a grpc error with status code `DeadlineExceeded`:

https://github.com/kubernetes/kubernetes/blob/4bb30c3b0e9167eb85b1e3b0c9a3bab3b351a3e2/pkg/kubelet/cri/remote/remote_runtime.go#L394-L397

**Comment by andrewsykim** [comment]
```
Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
```

seems unrelated

/retest

File: pkg/kubelet/dockershim/docker_streaming.go (hunk 5 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/dockershim/docker_streaming.go:96]: maybe this comment can be added into the code. It is not very logical when you simply looking at this method

File: test/e2e/common/container_probe.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply test/e2e/common/container_probe.go:142]: should the same be on line 124?

Comment (andrewsykim) [reply test/e2e/common/container_probe.go:142]: hmmm.. so that test wasn't failing because the test is expecting a restart, but now that you mention it may be failing due to timeout and not a non-zero exit code, so I think it may make sense to set a similar timeout there.

File: pkg/kubelet/dockershim/exec.go [hunk 6]
```diff
@@ -109,53 +105,55 @@ func (*NativeExecHandler) ExecInContainer(client libdocker.Interface, container
...
+	execErr := make(chan error, 1)
+	go func() {
+		execErr <- client.StartExec(execObj.ID, startOpts, streamOpts)
+	}()
+
+	select {
+	case <-ctx.Done():
+		return ctx.Err()
+	case err := <-execErr:
+		if err != nil {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/dockershim/exec.go:126]: nothing bad will happen, but maybe need to call `cancel()`?

Comment (andrewsykim) [reply pkg/kubelet/dockershim/exec.go:126]: cancel is called with defer on line 112

Comment (SergeyKanzhelev) [reply pkg/kubelet/dockershim/exec.go:126]: yes, totally. My comment is that we can cancel timeout in case the exec has already finished =)

File: test/e2e/common/container_probe.go (hunk 2 above)
Comment (derekwaynecarr) [reply test/e2e/common/container_probe.go:216]: i agree we should defer labeling this NodeConformance

**Review by derekwaynecarr — CHANGES_REQUESTED** [review]
just the one comment about not adding NodeConformance tag.

File: test/e2e/common/container_probe.go (hunk 2 above)
Comment (andrewsykim) [reply test/e2e/common/container_probe.go:216]: ack, I'll remove this

Comment (andrewsykim) [reply test/e2e/common/container_probe.go]: Removed, thanks

**Comment by andrewsykim** [comment]
@derekwaynecarr removed exec probe timeout tests from `[NodeConformance]`, PTAL

File: pkg/kubelet/dockershim/exec.go [hunk 7]
```diff
@@ -109,53 +105,55 @@ func (*NativeExecHandler) ExecInContainer(client libdocker.Interface, container
...
+			return err
+		}
 	}
 
+	// InspectExec may not always return latest state of exec, so call it a few times until
+	// it returns an exec inspect that shows that the process is no longer running.
+	retries := 0
+	maxRetries := 5
 	ticker := time.NewTicker(2 * time.Second)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/dockershim/exec.go:135]: I cannot understand why we need a `ticker` after this change?

**Review by hasheddan — APPROVED** [review]
/lgtm

@derekwaynecarr could you take another look here and approve if looks good to you?
