### PR TITLE
delete stale UDP conntrack entries for loadbalancer IPs

### LINKED ISSUE #103857: UDP Pod behind a LoadBalancer Service (External IP) replacing another Pod in the same node not receiving traffic
#### What happened:

UDP traffic to a Pod behind a LoadBalancer Service exposing a UDP listener service is blackholed when the replacement Pod is scheduled on the same node as the "old" Pod.

#### What you expected to happen:

A new Pod that gets provisioned (replacing the previous one) will receive traffic once it's ready.

#### How to reproduce it (as minimally and precisely as possible):

1. Run a UDP Listener Pod (single pod) and using nodeSelector ensure it runs on a specific node
2. Expose the Pod behind a LoadBalancer Service
3. Send continuous stream of UDP packets from outside the cluster to the External IP of the Service
4. Observe that traffic is correctly received
5. Delete the Pod and observe as a new one is created, traffic should now be blackholed and not reaching the "new" Pod

#### Anything else we need to know?:

After the new Pod is recreated, we noticed the following `conntrack` entries on the node:
```
udp 17 29 src=<SRC IP A> dst=<SVC EXT IP> sport=51287 dport=6343 packets=111046 bytes=144979158 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP A> sport=6343 dport=51287 packets=0 bytes=0 mark=0 use=1
udp 17 29 src=<src ip B> dst=<SVC EXT IP> sport=53156 dport=6343 packets=132186 bytes=174564682 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP B> sport=6343 dport=53156 packets=0 bytes=0 mark=0 use=1
udp 17 29 src=<src ip C> dst=<SVC EXT IP> sport=54882 dport=6343 packets=97917 bytes=129246821 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP C> sport=6343 dport=54882 packets=0 bytes=0 mark=0 use=2
udp 17 29 src=<src ip D> dst=<SVC EXT IP> sport=50427 dport=6343 packets=220813 bytes=290159533 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP D> sport=6343 dport=50427 packets=0 bytes=0 mark=0 use=1
```

notice that the <SVC EXT IP> appears here both in the original `dst` and the NATed `src`, this is wrong and I suspect happens because the conntrack for the old Pod were flushed before the iptables rules for the new Pod were created (?) and in the interim new packets have reached the node and resulted in these incorrect conntrack entries.

To "fix" this, we manually deleted the above conntrack entries, and this allowed new correct one to be established based on the now existing iptables nat rule:

```
 udp 17 29 src=<SRC IP A> dst=<SVC EXT IP> sport=51287 dport=6343 packets=7716 bytes=10071760 [UNREPLIED] src=172.30.3.219 dst=<SRC IP A> sport=6343 dport=51287 packets=0 bytes=0 mark=0 use=2
 udp 17 29 src=<SRC IP B> dst=<SVC EXT IP> sport=53156 dport=6343 packets=8100 bytes=10710888 [UNREPLIED] src=172.30.3.219 dst=<SRC IP B> sport=6343 dport=53156 packets=0 bytes=0 mark=0 use=1
 udp 17 29 src=<SRC IP C> dst=<SVC EXT IP> sport=54882 dport=6343 packets=5129 bytes=6759873 [UNREPLIED] src=172.30.3.219 dst=<SRC IP C> sport=6343 dport=54882 packets=0 bytes=0 mark=0 use=1
 udp 17 29 src=<SRC IP D> dst=<SVC EXT IP> sport=50427 dport=6343 packets=9988 bytes=13124292 [UNREPLIED] src=172.30.3.219 dst=<SRC IP D> sport=6343 dport=50427 packets=0 bytes=0 mark=0 use=2
```

with this new conntrack entries, the traffic started flowing as expected to the new Pod and notice that the NATed `src` now correctly shows the Pod IP (172.30.3.219) instead of the Service External IP.

While spelunking through the GitHub issues and PRs, I found this issue https://github.com/kubernetes/kubernetes/issues/91236 which was addressed in https://github.com/kubernetes/kubernetes/pull/98305, it does mention that:
> The conntrack entries have to be cleared after the iptables rules are programmed and when
the service has endpoints available.

Since the fix in this PR refers to NodePort, perhaps the same also applies to External IP (i.e. LoadBalancer Service?) or there's something else at play here? AFAICT, this fix is included in v1.20.7 that we are running.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-gke.1800", GitCommit:"cd6f9121893d6cdb30e3c48d57830ed44411e4ba", GitTreeState:"clean", BuildDate:"2021-06-07T09:17:22Z", GoVersion:"go1.15.12b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP/GKE
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=c19d150c6bd658510ec786390aec80ad476c7578
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=89
VERSION_ID=89
BUILD_ID=16108.403.15
```
- Kernel (e.g. `uname -a`): `Linux gke-stg-usc1-workloads-b5d2c472-xbzb 5.4.104+ #1 SMP Tue Apr 6 09:49:56 PDT 2021 x86_64 Intel(R) Xeon(R) CPU GenuineIntel GNU/Linux`
- Install tools: Terraform (with google provider)
- Network plugin and version (if this is a network-related bug): `Calico v3.16.10-gke.0`
- Others:

### PR DESCRIPTION
**Pull request by aojea**
/kind bug

#### What this PR does / why we need it:

From the long saga of UDP conntrack stale entries breaking services, we have a new chapter because I forget to consider the lb ingress IPs

```release-note
kube-proxy: delete stale conntrack UDP entries for loadbalancer ingress IP.
```

Fixes: https://github.com/kubernetes/kubernetes/issues/103857

### CODE REVIEW

File: pkg/proxy/iptables/proxier_test.go [hunk 1]
```diff
@@ -3229,21 +3242,33 @@ func TestProxierDeleteNodePortStaleUDP(t *testing.T) {
...
+	actualCommands := []string{
+		strings.Join(fcmd.CombinedOutputLog[0], " "),
+		strings.Join(fcmd.CombinedOutputLog[1], " "),
+		strings.Join(fcmd.CombinedOutputLog[2], " "),
+		strings.Join(fcmd.CombinedOutputLog[3], " "),
+	}
+	sort.Strings(expectedCommands)
+	sort.Strings(actualCommands)
+
+	if !reflect.DeepEqual(expectedCommands, actualCommands) {
```
Comment (aojea) [inline pkg/proxy/iptables/proxier_test.go:3270]: this is flake free
```
$ go test -timeout 100s -run ^TestProxierDeleteNodePortStaleUDP$ k8s.io/kubernetes/pkg/proxy/iptables -c
$ stress ./iptables.test 
105 runs so far, 0 failures
```

**Comment by dkulchinsky** [comment]
@aojea thank for the fix! 😄 

Do you think this is important enough to get ported into v1.20 🙏🏼

**Comment by aojea** [comment]
> @aojea thank for the fix! 
> 
> Do you think this is important enough to get ported into v1.20 🙏🏼

yeah, I think it qualifies
/retest

**Comment by aojea** [comment]
/test pull-kubernetes-integration
--


<br class="Apple-interchange-newline">

**Comment by dkulchinsky** [comment]
@aojea happy to see this passing and getting merged! I see two cherry picks linked here for 1.22 and 1.21, is there any chance to see a 1.20 cherry pick as well?

**Comment by aojea** [comment]
> @aojea happy to see this passing and getting merged! I see two cherry picks linked here for 1.22 and 1.21, is there any chance to see a 1.20 cherry pick as well?

https://github.com/kubernetes/kubernetes/pull/104152

**Comment by dkulchinsky** [comment]
> > @aojea happy to see this passing and getting merged! I see two cherry picks linked here for 1.22 and 1.21, is there any chance to see a 1.20 cherry pick as well?
> 
> #104152
> 
> it is not a clean backport, I need to figure out the issues

Wonderful! Sorry, should have looked better for it myself.

**Comment by aojea** [comment]
> > > @aojea happy to see this passing and getting merged! I see two cherry picks linked here for 1.22 and 1.21, is there any chance to see a 1.20 cherry pick as well?
> > 
> > 
> > #104152
> > it is not a clean backport, I need to figure out the issues
> 
> Wonderful! Sorry, should have looked better for it myself.

is not your fault, I had to cherry pick it from a cherry pick, that is why it didn't show up here,
