### PR TITLE
custom plugin config should take precedence over default plugin config

### LINKED ISSUE #99580: scheduler failed to start due to the custom plugin config in scheduler config file
#### What happened:
Start the scheduler with a scheduler config file which has a custom configuration for a specific plugin, the scheduler will fail to start and throw below exception, 

*kube-scheduler.yaml*
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: default-scheduler
  plugins:
    score:
      enabled:
        - name: InterPodAffinity
          weight: 2
   ...
```

error message, 
```
W0301 18:07:50.432541   26557 authorization.go:184] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
couldn't create scheduler using provider "DefaultProvider": initializing profiles: creating profile for scheduler name default-scheduler: plugin "InterPodAffinity" already registered as "ScorePlugin"
Process 26557 has exited with status 1
```

#### What you expected to happen:
custom plugin config should take precedence over default plugin config.

#### How to reproduce it (as minimally and precisely as possible):
start a scheduler with a config file.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

Add one of the following kinds:
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/99580

#### Does this PR introduce a user-facing change?

```release-note
kube-scheduler: a plugin enabled in a v1beta2 configuration file takes precedence over the default configuration for that plugin; this simplifies enabling default plugins with custom configuration without needing to explicitly disable those default plugins.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/apis/config/types.go [hunk 1]
```diff
@@ -298,18 +298,21 @@ func (p *Plugins) Apply(customPlugins *Plugins) {
 
 func mergePluginSets(defaultPluginSet, customPluginSet PluginSet) PluginSet {
 
-	disabledPlugins := sets.NewString()
+	disabledPlugins, enabledCustomPlugin := sets.NewString(), sets.NewString()
```
Comment (Huang-Wei) [inline pkg/scheduler/apis/config/types.go:301]:
```suggestion
	disabledPlugins, enabledCustomPlugins := sets.NewString(), sets.NewString()
```

File: pkg/scheduler/apis/config/types.go [hunk 2]
```diff
@@ -298,18 +298,21 @@ func (p *Plugins) Apply(customPlugins *Plugins) {
...
+	for _, enabledPlugin := range customPluginSet.Enabled {
+		enabledCustomPlugin.Insert(enabledPlugin.Name)
+	}
 
 	var enabledPlugins []Plugin
 	if !disabledPlugins.Has("*") {
 		for _, defaultEnabledPlugin := range defaultPluginSet.Enabled {
-			if disabledPlugins.Has(defaultEnabledPlugin.Name) {
+			// custom plugin config will take precedence over default plugin config
+			if disabledPlugins.Has(defaultEnabledPlugin.Name) || enabledCustomPlugin.Has(defaultEnabledPlugin.Name) {
```
Comment (Huang-Wei) [inline pkg/scheduler/apis/config/types.go:313]: (a bit off the topic)

@alculquicondor no matter with or w/o this PR, a lightweight customized plugin may be placed in the end, am I understanding right?

File: pkg/scheduler/apis/config/types.go (hunk 1 above)
Comment (chendave) [reply pkg/scheduler/apis/config/types.go]: Done

**Comment by chendave** [comment]
@alculquicondor @Huang-Wei , I managed to reserve both the order of default and custom plugins.

Current code implementation and testcase, "InsertBeforeAllPlugins" for example, show me that the overwrite of  the default plugin config is allowed, so this PR intends to release us from explicitly disable the default plugins and then re-enable it again, which sound like a hack to me, this will help reduce the surprise to end user.

**Comment by chendave** [comment]
@alculquicondor @Huang-Wei  since v1beta2 has been landed, so revive this PR accordingly, mind taking a look? thanks!

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 3]
```diff
@@ -147,19 +147,38 @@ func mergePlugins(defaultPlugins, customPlugins *v1beta2.Plugins) *v1beta2.Plugi
...
+}
+
 func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2.PluginSet {
 	disabledPlugins := sets.NewString()
+	enabledCustomPlugins := make(map[string]pluginIndex)
 	for _, disabledPlugin := range customPluginSet.Disabled {
 		disabledPlugins.Insert(disabledPlugin.Name)
 	}
+	// Filter duplication: custom plugin is allowed to be configured multiple times but only last one will be used.
+	for index, enabledPlugin := range customPluginSet.Enabled {
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: This is not doing what we proposed:

- Fail when plugin is already registered in the custom configuration, and only warning if the plugin was already part of defaults.
- Override the default weight, preserving order


The failure should not happen in defaults.go. It should happen during validation. So:
- The first time a plugin shows up in `customPluginSet`, you replace the weight that `defaultPluginSet` has.
- The second time, you append.

Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: > Fail when plugin is already registered in the custom configuration, and only warning if the plugin was already part of defaults.

I think I was over-thinking about the duplicate config, it has been validated when the framework is initialized and is banned there, valid this ahead of framework initialization might be better but at least it has not caused any problem today. 

One line of warning will be added.

https://github.com/kubernetes/kubernetes/blob/554c65fb776c5e93f8540799424f8006a88a0e3e/pkg/scheduler/framework/runtime/framework.go#L432-L434

> The first time a plugin shows up in customPluginSet, you replace the weight that defaultPluginSet has.
> The second time, you append.

Implementation in this PR is a little different but achieve the same goal,  it is checking the existence of custom plugin when looping the `defaultPluginSet`, so needn't loop them separately, pls let me know your thoughts on this IMPL?

Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:161]: hmm... I still need to loop it twice, since `defaultPluginSet.Enabled` is  a slice, this might be the easier way to fix it.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 4]
```diff
@@ -147,19 +147,34 @@ func mergePlugins(defaultPlugins, customPlugins *v1beta2.Plugins) *v1beta2.Plugi
...
+
 func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2.PluginSet {
 	disabledPlugins := sets.NewString()
+	enabledCustomPlugins := make(map[string]pluginIndex)
 	for _, disabledPlugin := range customPluginSet.Disabled {
 		disabledPlugins.Insert(disabledPlugin.Name)
 	}
-
+	for index, enabledPlugin := range customPluginSet.Enabled {
+		enabledCustomPlugins[enabledPlugin.Name] = pluginIndex{index, enabledPlugin}
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: only the first repetition?

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 5]
```diff
@@ -147,19 +147,34 @@ func mergePlugins(defaultPlugins, customPlugins *v1beta2.Plugins) *v1beta2.Plugi
...
 	var enabledPlugins []v1beta2.Plugin
 	if !disabledPlugins.Has("*") {
 		for _, defaultEnabledPlugin := range defaultPluginSet.Enabled {
 			if disabledPlugins.Has(defaultEnabledPlugin.Name) {
 				continue
 			}
-
+			// The default plugin is explicitly re-configured, update the default plugin accordingly.
+			if customPlugin, ok := enabledCustomPlugins[defaultEnabledPlugin.Name]; ok {
+				klog.InfoS("Defaut plugin is explicitly re-configured, will be overridden.", "plugin", defaultEnabledPlugin.Name)
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:172]: use present tense: overriding

**Review by alculquicondor — COMMENTED** [review]
Since you are changing the interpretation of `PluginSet.Enabled`, you need to update the documentation for the field in `k8s.io/kube-scheduler/config/v1beta2/types.go`

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 4 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: true, seems like we'd better to validate this config to avoid the case of repetition, will fix it in my next day!

Comment (alculquicondor) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: recall that code freeze is on Thursday

Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: because `mergePlugins` is done before the validation, so the repetition here is still possible, I'd suggest to just log something here or revert to the original version, only the last repetition will be valid for either way.
I am a little lost here, do you have any suggestion?

Comment (alculquicondor) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:162]: You can keep it like this, it doesn't really matter because more than one repetition will fail later.

Fix the types.go though

**Comment by alculquicondor** [comment]
You probably need to run `make update`

**Comment by chendave** [comment]
> You probably need to run make update

I did, nothing was changed.

**Comment by chendave** [comment]
only run `make generated_files` which I think should be enough.

**Comment by liggitt** [comment]
does this fix only apply to v1beta2 configs? if so, should that be noted in the release note?

**Comment by liggitt** [comment]
My understanding is that this makes config files work which would previously fail validation (because they didn't explicitly disable the default plugin they wanted to explicitly enable), and would have no impact on config files which were previously working. Is that correct?

**Comment by chendave** [comment]
> does this fix only apply to v1beta2 configs? if so, should that be noted in the release note?

Just updated

**Comment by chendave** [comment]
> My understanding is that this makes config files work which would previously fail validation (because they didn't explicitly disable the default plugin they wanted to explicitly enable), and would have no impact on config files which were previously working. Is that correct?

yes, no impact on the previous config file, this PR does some enhancement only if the default plugin is not disabled by *, and thus more flexible for end-user to config, and avoid unnecessary failure if there is no config confliction with default plugin.
