### PR TITLE
call kube::golang::setup_env before setting up worktree, cleanup update-mocks.sh

### LINKED ISSUE #117272: hack/verify-mocks.sh fails on cleanup
### What happened?

I get a permission denied error when running hack/verify-mocks.sh from my macOS Monterey (Silicon).  #116338 is basically the same problem BUT with Linux. 

"go install" is adding some files to the cache and because of the permissions I can't delete them. This is an example:

```
% ls -l /private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.h6yL2P2F/_output/local/go/cache/mod/golang.org/x/tools@v0.6.0/go/analysis/passes/tests/testdata/src/a
total 32
-r--r--r--  1 marthinal  staff    25 Apr 12 15:30 a.go
-r--r--r--  1 marthinal  staff  3562 Apr 12 15:30 a_test.go
-r--r--r--  1 marthinal  staff   155 Apr 12 15:30 ax_test.go
-r--r--r--  1 marthinal  staff  3794 Apr 12 15:30 go118_test.go
```

The problem can be fixed by running "go clean -modcache" from the cleanup function. 

### What did you expect to happen?

The test must pass.

### How can we reproduce it (as minimally and precisely as possible)?

Execute "make verify" from  macOS M1. BUT in [this issue](https://github.com/kubernetes/kubernetes/issues/116338)  they are using Linux. 

Here is the error:
Screenshot 2023-04-13 at 07 46 15

After running "go clean -modcache" from the cleanup function:
Screenshot 2023-04-13 at 07 52 21

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
macOS Monterey 12.6.4 (Apple Silicon)
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

Alternate to https://github.com/kubernetes/kubernetes/pull/117525

Fixes https://github.com/kubernetes/kubernetes/issues/117272

Ensures we persist GOCACHE etc through git worktree.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: hack/update-mocks.sh [hunk 1]
```diff
@@ -45,22 +35,26 @@ pushd "${KUBE_ROOT}/hack/tools" >/dev/null
 popd >/dev/null
 
 function git_find() {
-    # Similar to find but faster and easier to understand.  We want to include
```
Comment (thockin) [inline hack/update-mocks.sh:48]: You should send these as a different PR :)

**Review by thockin — COMMENTED** [review]
I think you also want:

```diff
diff --git a/hack/lib/golang.sh b/hack/lib/golang.sh
index 94a2efc47e9..fc7d9661e88 100755
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -18,7 +18,7 @@
 
 # The golang package that we are building.
 readonly KUBE_GO_PACKAGE=k8s.io/kubernetes
-readonly KUBE_GOPATH="${KUBE_OUTPUT}/go"
+export KUBE_GOPATH="${KUBE_GOPATH:-"${KUBE_OUTPUT}/go"}"
 
 # The server platform we are building on.
 readonly KUBE_SUPPORTED_SERVER_PLATFORMS=(
```

I'd also copy the comment about GOCACHE from the codegen scripts and stick it all over.

**Comment by thockin** [comment]
my scratch notes - let me know if you want to punt it


```diff
diff --git a/hack/lib/golang.sh b/hack/lib/golang.sh
index 94a2efc47e9..fc7d9661e88 100755
--- a/hack/lib/golang.sh
+++ b/hack/lib/golang.sh
@@ -18,7 +18,7 @@
 
 # The golang package that we are building.
 readonly KUBE_GO_PACKAGE=k8s.io/kubernetes
-readonly KUBE_GOPATH="${KUBE_OUTPUT}/go"
+export KUBE_GOPATH="${KUBE_GOPATH:-"${KUBE_OUTPUT}/go"}"
 
 # The server platform we are building on.
 readonly KUBE_SUPPORTED_SERVER_PLATFORMS=(
diff --git a/hack/verify-internal-modules.sh b/hack/verify-internal-modules.sh
index 8ec9678e17f..28496bc3847 100755
--- a/hack/verify-internal-modules.sh
+++ b/hack/verify-internal-modules.sh
@@ -23,13 +23,15 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 
 kube::util::ensure_clean_working_dir
 
+# This sets up the environment, like GOCACHE, which keeps the worktree cleaner.
+kube::golang::setup_env
+
 _tmpdir="$(kube::realpath "$(mktemp -d -t verify-internal-modules.XXXXXX)")"
-#kube::util::trap_add "rm -rf ${_tmpdir}" EXIT
+kube::util::trap_add "rm -rf ${_tmpdir}" EXIT
 
 _tmp_gopath="${_tmpdir}/go"
 _tmp_kuberoot="${_tmp_gopath}/src/k8s.io/kubernetes"
 git worktree add -f "${_tmp_kuberoot}" HEAD
-kube::util::trap_add "git worktree remove -f ${_tmp_kuberoot}" EXIT
 
 pushd "${_tmp_kuberoot}" >/dev/null
 ./hack/update-internal-modules.sh
diff --git a/hack/verify-licenses.sh b/hack/verify-licenses.sh
index 0987e714ea3..2f943255a01 100755
--- a/hack/verify-licenses.sh
+++ b/hack/verify-licenses.sh
@@ -26,26 +26,23 @@ KUBE_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
 source "${KUBE_ROOT}/hack/lib/init.sh"
 source "${KUBE_ROOT}/hack/lib/util.sh"
 
+# This sets up the environment, like GOCACHE, which keeps the worktree cleaner.
+kube::golang::setup_env
 
-kube::golang::verify_go_version
 kube::util::ensure-temp-dir
 
-
 # Creating a new repository tree 
 # Deleting vendor directory to make go-licenses fetch license URLs from go-packages source repository
 git worktree add -f "${KUBE_TEMP}"/tmp_test_licenses/kubernetes HEAD >/dev/null 2>&1 || true
 cd "${KUBE_TEMP}"/tmp_test_licenses/kubernetes && rm -rf vendor
 
-
 # Ensure that we find the binaries we build before anything else.
 export GOBIN="${KUBE_OUTPUT_BINPATH}"
 PATH="${GOBIN}:${PATH}"
 
-
 # Explicitly opt into go modules, even though we're inside a GOPATH directory
 export GO111MODULE=on
 
-
 allowed_licenses=()
 packages_flagged=()
 packages_url_missing=()
diff --git a/hack/verify-mocks.sh b/hack/verify-mocks.sh
index 07452c7e7db..8806eae45cc 100755
--- a/hack/verify-mocks.sh
+++ b/hack/verify-mocks.sh
@@ -32,6 +32,9 @@ export GO111MODULE=on
 
 kube::util::ensure_clean_working_dir
 
+# This sets up the environment, like GOCACHE, which keeps the worktree cleaner.
+kube::golang::setup_env
+
 _tmpdir="$(kube::realpath "$(mktemp -d -t "$(basename "$0").XXXXXX")")"
 git worktree add -f -q "${_tmpdir}" HEAD
 kube::util::trap_add "git worktree remove -f ${_tmpdir}" EXIT
diff --git a/hack/verify-yamlfmt.sh b/hack/verify-yamlfmt.sh
index cea2c7edde3..774ed63b255 100755
--- a/hack/verify-yamlfmt.sh
+++ b/hack/verify-yamlfmt.sh
@@ -29,6 +29,9 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 
 kube::util::ensure_clean_working_dir
 
+# This sets up the environment, like GOCACHE, which keeps the worktree cleaner.
+kube::golang::setup_env
+
 _tmpdir="$(kube::realpath "$(mktemp -d -t "$(basename "$0").XXXXXX")")"
 git worktree add -f -q "${_tmpdir}" HEAD
 kube::util::trap_add "git worktree remove -f ${_tmpdir}" EXIT
```

File: hack/update-mocks.sh (hunk 1 above)
Comment (BenTheElder) [reply hack/update-mocks.sh:48]: fair!

**Comment by BenTheElder** [comment]
> I think you also want:

Agree, slightly modified: https://github.com/kubernetes/kubernetes/pull/117526/commits/18ae393ec2796928fae676b3d57d679f2e5d157f
```diff
-readonly KUBE_GOPATH="${KUBE_OUTPUT}/go"
+readonly KUBE_GOPATH="${KUBE_GOPATH:-"${KUBE_OUTPUT}/go"}"
+export KUBE_GOPATH
```

We can export and still set readonly.

Added the GOCACHE comment everywhere and the other changes suggested.

**Review by thockin — COMMENTED** [review]
You are now on my list of people to send horrible shell PRs too.  We thank you for your service.

/lgtm
/approve

File: hack/verify-internal-modules.sh [hunk 2]
```diff
@@ -26,7 +26,7 @@ kube::util::ensure_clean_working_dir
 kube::golang::setup_env
 
 _tmpdir="$(kube::realpath "$(mktemp -d -t verify-internal-modules.XXXXXX)")"
-#kube::util::trap_add "rm -rf ${_tmpdir}" EXIT
+kube::util::trap_add "rm -rf ${_tmpdir:?}" EXIT
```
Comment (thockin) [inline hack/verify-internal-modules.sh:29]: YOu can remove the trap 5 lines below, then

Comment (BenTheElder) [inline hack/verify-internal-modules.sh:29]: @thockin lost your LGTM pulling this one out

Also adding `:?` because even though we just set _tmpdir we should encourage the habit of `rm -rf ${foo:?}` to prevent accidents like `rm -rf "${foo:}/"` where $foo is unset.

Comment (BenTheElder) [reply hack/verify-internal-modules.sh:29]: does git worktree not have any other internal git state we need to cleanup?

**Comment by BenTheElder** [comment]
/triage accepted
/priority important-soon
(since right now locally verify-mocks is broken, not that the priority label means much ...)
