### PR TITLE
Fix stale conntrack flow detection logic

### LINKED ISSUE #119249: Conntrack cleaning happens before network programming endpoints
### What happened?

Currently kube-proxy efficiently cleans all stale conntrack entries preventing traffic black holing for deleted endpoints, but there can be some corner cases when conntrack cleaning happens before programming the network leaving a small window in which if any packet arrives will back-hole the traffic.

The corner case:
Taking a simple case of load-balancer service backed by a deployment with single replica, on deleting the pod(gracefully), I observed two **OnEndpointSliceUpdate** invocations:
1.  First one with EndpointConditions.Ready as false
2. EndpointSlice was cleared for the pod 

The conntrack flow for this case:
1. After processing the first **OnEndpointSliceUpdate** invocation **EndpointsMap** will still have entries for the pod as endpoint still exists, though not in ready state so proxier won't program deletion of endpoint from the data path. But the endpoint IP will be picked for conntrack cleaning as new endpoint != old endpoint because of the not ready condition.
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L423-L436
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L120-L126

2.  After processing the second **OnEndpointSliceUpdate** invocation **EndpointsMap** won't have entries for the endpoint and the proxier will program deletion of the endpoint in the data path. EndpointIP won't be picked up for conntrack cleaning as the following logic will skip it
https://github.com/kubernetes/kubernetes/blob/95e915c4288eda15da1724989f3f7dec9f3512d6/pkg/proxy/endpoints.go#L417-L421

This behaviour leads to conntrack cleaning one cycle ahead of network programming.  
This might be a regression of https://github.com/kubernetes/kubernetes/pull/106163

### What did you expect to happen?

Conntrack cleanup should happen after programming the network.

### How can we reproduce it (as minimally and precisely as possible)?

This behaviour can be observed in kube-proxy logs (verbosity=4).
[link to log snippet showing the behaviour](https://github.com/kubernetes/kubernetes/pull/119010#issuecomment-1622325495)

I used the following objects for experimenting:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      nodeSelector:
        kubernetes.io/hostname: kind-worker2
      containers:
      - name: test
        image: registry.k8s.io/e2e-test-images/agnhost:2.45
        command:
          - /agnhost
        args:
          - netexec
          - --udp-port=80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  selector:
    app: test
  ports:
    - protocol: UDP
      name: udp
      nodePort: 31111
      port: 80
      targetPort: 80
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
I was using latest kind node-image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes a small bug in stale conntrack entries detection  for UDP connections.
#### Which issue(s) this PR fixes:

Fixes #119249

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aroradaman** [comment]
[It] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] multi process container The containers terminated by OOM killer should have the reason set to OOMKilled

/retest pull-kubernetes-node-e2e-containerd

**Comment by aroradaman** [comment]
[It] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] multi process container The containers terminated by OOM killer should have the reason set to OOMKilled

/test pull-kubernetes-node-e2e-containerd

File: pkg/proxy/endpoints_test.go [hunk 1]
```diff
@@ -495,35 +495,35 @@ func TestUpdateEndpointsMap(t *testing.T) {
...
+		// previousEndpointSlices and currentEndpointSlices are used to call appropriate
 		// handlers OnEndpointSlice* (based on whether corresponding values are nil
 		// or non-nil) and must be of equal length.
 		name                           string
-		previousEndpoints              []*discovery.EndpointSlice
-		currentEndpoints               []*discovery.EndpointSlice
-		oldEndpoints                   map[ServicePortName][]*BaseEndpointInfo
+		previousEndpointSlices         []*discovery.EndpointSlice
+		currentEndpointSlices          []*discovery.EndpointSlice
+		oldEndpointsMap                map[ServicePortName][]*BaseEndpointInfo
```
Comment (danwinship) [inline pkg/proxy/endpoints_test.go:534]: If `previousEndpointSlices` and `oldEndpointsMap` are just different representations of the same data (which I think they are?) then that would be more obvious if they both used the same adjective ("previous" or "old").

File: pkg/proxy/endpoints.go [hunk 2]
```diff
@@ -121,7 +121,7 @@ func (info *BaseEndpointInfo) Port() (int, error) {
 func (info *BaseEndpointInfo) Equal(other Endpoint) bool {
 	return info.String() == other.String() &&
 		info.GetIsLocal() == other.GetIsLocal() &&
-		info.IsReady() == other.IsReady()
+		info.IsServing() == other.IsServing()
```
Comment (danwinship) [inline pkg/proxy/endpoints.go:124]: This feels wrong. Surely an `Endpoint` that is terminating is not "Equal" to one that is not terminating?

It seems that `Endpoint.Equal` is actually only used in `detectStaleConntrackEntries`... I think rather than having an alleged "Equal" function whose semantics have to be fine-tuned to do what `detectStaleConntrackEntries` wants, we should just remove the function from the interface (and also iptables's redefinition of it for its `endpointsInfo`), and just have `detectStaleConntrackEntries` check the specific thing that it cares about; for each old endpoint which is Serving, is there a corresponding new endpoint which is still Serving. ("Corresponding" meaning "`oldEP.String() == newEP.String()`".)

File: pkg/proxy/iptables/proxier_test.go [hunk 3]
```diff
@@ -5291,7 +5291,7 @@ func TestProxierDeleteNodePortStaleUDP(t *testing.T) {
 			eps.Endpoints = []discovery.Endpoint{{
 				Addresses: []string{epIP},
 				Conditions: discovery.EndpointConditions{
-					Ready: pointer.Bool(true),
+					Serving: pointer.Bool(true),
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier_test.go:5294]: We should fix this everywhere. `BaseEndpointInfo.Ready` should just go away, and `BaseEndpointInfo.IsReady()` should return `info.Serving && !info.Terminating`.

File: pkg/proxy/endpoints_test.go (hunk 1 above)
Comment (aroradaman) [reply pkg/proxy/endpoints_test.go]: renamed `oldEndpointsMap` -> ` previousEndpointsMap`

File: pkg/proxy/iptables/proxier_test.go (hunk 3 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:5294]: > Do you mean to completely remove the property `Ready` from `BaseEndpointInfo` structure itself ?

Yes. It's redundant; `info.Ready` is guaranteed to always be the same as `info.Serving && !info.Terminating`, because that is true of the corresponding EndpointSlice fields that they're set from.

Comment (aroradaman) [reply pkg/proxy/iptables/proxier_test.go:5294]: setting `Terminating: false` for this one.

Comment (aroradaman) [reply pkg/proxy/iptables/proxier_test.go:5294]: same for this, https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/proxy/ipvs/proxier_test.go#L4577-L4581

Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go]: Yeah, `Ready: false, Serving: true, Terminating: false` is an invalid combination of conditions. The test cases are bad.

> setting `Terminating: true` for this one.

(that might make it redundant with an already-existing test case)

Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go]: we can only ignore Ready if Serving is exactly the same, if we have some corner case that is not covered as reported here https://github.com/kubernetes/kubernetes/issues/119773 we can not modify an existing behavior ... 

There was an incoherence when setting the `publishNotReady` field, check if this is the problem here https://github.com/kubernetes/kubernetes/issues/116285

File: pkg/proxy/endpoints.go [hunk 4]
```diff
@@ -87,7 +81,7 @@ func (info *BaseEndpointInfo) GetIsLocal() bool {
 
 // IsReady returns true if an endpoint is ready and not terminating.
 func (info *BaseEndpointInfo) IsReady() bool {
-	return info.Ready
+	return info.Serving && !info.Terminating
```
Comment (aojea) [inline pkg/proxy/endpoints.go:84]: This is not true because of https://github.com/kubernetes/kubernetes/issues/116285

File: pkg/proxy/iptables/proxier_test.go (hunk 3 above)
Comment (aroradaman) [reply pkg/proxy/iptables/proxier_test.go]: endpoint slice controller also considers `PublishNotReadyAddresses` in determining the Ready state. 
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/endpointslice/utils.go#L36-L42

Comment (aroradaman) [reply pkg/proxy/iptables/proxier_test.go]: @danwinship should I remove this commit and use **EndpointConditions.Ready** condition only ?

Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go]: The API docs for `EndpointConditions` say

>     // serving is identical to ready except that it is set regardless of the
>     // terminating state of endpoints.

And the docs for `publishNotReadyAddresses` say

>     // publishNotReadyAddresses indicates that any agent which deals with endpoints for this
>     // Service should disregard any indications of ready/not-ready.

Which means that given the current state of the endpointslice controller, kube-proxy does not handle terminating endpoints correctly for Services with `publishNotReadyAddresses` set, because it looks at `serving`, not `ready`.

I would say that the quoted endpointslice utils code is incorrect; it ought to be overriding `serving` based on `publishNotReadyAddresses`, _not_ overriding `ready` based on that, and it ought to always be setting `ready` to `serving && !terminating`.

However, that is getting a bit far afield from the rest of this PR, so I guess just leave the maybe-redundant-maybe-incorrect separate handling of Ready and Serving in `pkg/proxy` for now.

Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:5294]: the api doc was fixed in https://github.com/kubernetes/kubernetes/pull/116743/files

Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:5294]: >  always be setting ready to serving && !terminating.

+1

Comment (thockin) [reply pkg/proxy/iptables/proxier_test.go:5294]: Agree, since previously we just removed terminating endpoints entirely, right?

File: pkg/proxy/endpoints.go [hunk 5]
```diff
@@ -407,20 +407,19 @@ func detectStaleConntrackEntries(oldEndpointsMap, newEndpointsMap EndpointsMap,
...
-			// ready to not ready. If it did change stale entries for the old
+			// serving to not serving. If it did change stale entries for the old
 			// endpoint have to be cleared.
 			for i := range newEndpointsMap[svcPortName] {
 				if newEndpointsMap[svcPortName][i].String() == ep.String() &&
-					newEndpointsMap[svcPortName][i].IsReady() == ep.IsReady() &&
-					newEndpointsMap[svcPortName][i].GetIsLocal() == ep.GetIsLocal() {
+					newEndpointsMap[svcPortName][i].IsServing() == ep.IsServing() {
 					deleted = false
 					break
```
Comment (danwinship) [inline pkg/proxy/endpoints.go:424]: You don't need to test Serving here; we already know that `ep` is Serving (line 412), and we already know that `newEndpointsMap[svcPortName][i]` is Serving (because it couldn't be in `newEndpointsMap` otherwise).

**Comment by danwinship** [comment]
/approve
everything else looks good

File: pkg/proxy/endpoints.go [hunk 6]
```diff
@@ -407,20 +407,19 @@ func detectStaleConntrackEntries(oldEndpointsMap, newEndpointsMap EndpointsMap,
...
 			deleted := true
 			// Check if the endpoint has changed, including if it went from
-			// ready to not ready. If it did change stale entries for the old
+			// serving to not serving. If it did change stale entries for the old
 			// endpoint have to be cleared.
 			for i := range newEndpointsMap[svcPortName] {
 				if newEndpointsMap[svcPortName][i].String() == ep.String() &&
-					newEndpointsMap[svcPortName][i].IsReady() == ep.IsReady() &&
-					newEndpointsMap[svcPortName][i].GetIsLocal() == ep.GetIsLocal() {
+					newEndpointsMap[svcPortName][i].IsServing() == ep.IsServing() {
```
Comment (aojea) [inline pkg/proxy/endpoints.go:422]: @danwinship I don't understand this change, so previously we were detecting "old the endpoints were ready and new endpoints are ready and are local", and now we move to "old endpoints were serving and new endpoints are still serving".

Why do we remove the local condition?

If one endpoint is Serving and Terminating only will receive traffic if there are not more ready endpoints, do we want to perform additional conntracl flushes?

**Comment by aojea** [comment]
/hold

just for this question https://github.com/kubernetes/kubernetes/pull/119394/commits/6530e2f59c9ea6f9c75481371c1e4b2c53037d78#r1313376101 , please unhold if my question is not relevant

File: pkg/proxy/endpoints.go (hunk 6 above)
Comment (aroradaman) [reply pkg/proxy/endpoints.go]: I guess the **String()** comparison takes care of the local part. If both the endpoints have the same string representation (IP:PORT) then they are the same only,  both of them will be either local or remote and **GetIsLocal()** comparison will always be true, redundant here.

**Comment by aroradaman** [comment]
```
pull-kubernetes-node-e2e-containerd
[sig-node] OOMKiller [LinuxOnly] [NodeConformance] init container The containers terminated by OOM killer should have the reason set to OOMKilled 

pull-kubernetes-integration
k8s.io/kubernetes/test/integration/TestRequeueByBindFailure

```
/retest

File: pkg/proxy/endpoints.go (hunk 6 above)
Comment (aojea) [reply pkg/proxy/endpoints.go]: oh, I somehow assumed this was only considering local endpoints, makes sense.

what about 

> If one endpoint is Serving and Terminating only will receive traffic if there are not more ready endpoints, do we want to perform additional conntracl flushes?

**Comment by aojea** [comment]
/hold cancel
/lgtm

Thanks

**Comment by aojea** [comment]
/hold



/test pull-kubernetes-e2e-gci-gce-ipvs

The test failed here are related

File: pkg/proxy/endpoints.go (hunk 6 above)
Comment (aroradaman) [reply pkg/proxy/endpoints.go]: > If one endpoint is Serving and Terminating only will receive traffic if there are not more ready endpoints, do we want to perform additional conntracl flushes?

The NAT conntrack entry will be flushed independently for every endpoint when it transitions from serving to not serving. And if the service is left with zero serving endpoints, as soon as any new endpoint becomes active **NewlyActiveUDPServices** flow will clear all the conntrack entries for that service. 

I guess we don't need any additional conntrack flushes.

**Comment by aroradaman** [comment]
```
[sig-apps] ReplicaSet should serve a basic image on each replica with a private image
[sig-apps] ReplicationController should serve a basic image on each replica with a private image 
```
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by aroradaman** [comment]
**pull-kubernetes-e2e-gci-gce-ipvs** failed again with
```
[sig-apps] ReplicaSet should serve a basic image on each replica with a private image
[sig-apps] ReplicationController should serve a basic image on each replica with a private image
```

**Comment by aojea** [comment]
> [sig-apps] ReplicaSet should serve a basic image on each replica with a private image
> [sig-apps] ReplicationController should serve a basic image on each replica with a private image


they does not seems to be failing without this PR

https://testgrid.k8s.io/sig-network-gce#gci-gce-ipvs

/test

**Comment by aojea** [comment]
/lgtm cancel

until we sort out the failures on the jobs

**Comment by aroradaman** [comment]
**pull-kubernetes-e2e-kind-ipvs-dual-canary** failed with 
```
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] patching/updating a mutating webhook should work [Conformance] 
```

**Comment by aojea** [comment]
The ipvs jobs fail  also in this PR https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120386/pull-kubernetes-e2e-gci-gce-ipvs/1698313800849035264

**Comment by aojea** [comment]
> **pull-kubernetes-e2e-gci-gce-ipvs** failed again with
> 
> ```
> [sig-apps] ReplicaSet should serve a basic image on each replica with a private image
> [sig-apps] ReplicationController should serve a basic image on each replica with a private image
> ```

This is failing since Sept 1st, @aroradaman see https://github.com/kubernetes/kubernetes/issues/120391

/hold cancel
/lgtm
/approve
