### PR TITLE
Annotate errors in apimachinery e2e tests

### LINKED ISSUE #34059: destroy the "Expect(err).NotTo(HaveOccurred())" anti-pattern in e2e tests
I'm getting tired of seeing flake issues like https://github.com/kubernetes/kubernetes/issues/33647 where every single failure is of the form

```
Expected error:
    <*errors.errorString | 0xc820412c10>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

This is about as unhelpful an error message as you can get.

The problem is that we have

``` go
Expect(err).NotTo(HaveOccurred())
```

peppered throughout the code everywhere, and in this form, you can only figure out what failed if you read the Ginkgo error, remember which line has the line number you actually want, and then try to read surrounding code in that file.

Possible improvements given in http://onsi.github.io/gomega/#handling-errors:
- Use `Succeed()`
- Annotate the assertions
- Basically, do anything except just Expect(err).NotTo(HaveOccurred())

cc @kubernetes/sig-testing

### PR DESCRIPTION
**Pull request by audreylim**
Related to https://github.com/kubernetes/kubernetes/issues/34059

**What this PR does / why we need it**:
This PR makes errors more helpful in the apimachinery e2e tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
My first contribution to Kubernetes

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/apimachinery/etcd_failure.go [hunk 1]
```diff
@@ -130,7 +131,7 @@ func checkExistingRCRecovers(f *framework.Framework) {
 	framework.ExpectNoError(wait.Poll(time.Millisecond*500, time.Second*60, func() (bool, error) {
 		options := metav1.ListOptions{LabelSelector: rcSelector.String()}
 		pods, err := podClient.List(options)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to list pods in namespace: %s, that match label selector: %s", f.Namespace.Name, rcSelector.String())
```
Comment (spiffxp) [inline test/e2e/apimachinery/etcd_failure.go]: Overall this PR LGTM, but I'm curious if there is a way we could get the namespace name from `podClient` here? Something about having to refer back N>10 lines to see why/how to craft this message seems less than ideal

File: test/e2e/apimachinery/initializers.go [hunk 2]
```diff
@@ -72,34 +73,34 @@ var _ = SIGDescribe("Initializers [Feature:Initializers]", func() {
...
 		// clear initializers
 		pod.Initializers = nil
 		pod, err = c.CoreV1().Pods(ns).Update(pod)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to update pod %s to: %+v", pod.Name, pod)
 
 		// pod should now start running
 		err = framework.WaitForPodRunningInNamespace(c, pod)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "timeout while waiting for pod %s to run in namespace: %s, or pod is in a Failed state", pod.Name, pod.Namespace)
```
Comment (spiffxp) [inline test/e2e/apimachinery/initializers.go]: maybe `"error while waiting for pod %s to go to Running phase in namespace %s"`

File: test/e2e/apimachinery/initializers.go [hunk 3]
```diff
@@ -72,34 +73,34 @@ var _ = SIGDescribe("Initializers [Feature:Initializers]", func() {
...
 
 		// ensure create call returns
 		<-ch
 
 		// verify that we cannot start the pod initializing again
 		pod, err = c.CoreV1().Pods(ns).Get(podName, metav1.GetOptions{})
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to get pod: %s", podName)
```
Comment (spiffxp) [inline test/e2e/apimachinery/initializers.go]: missing namespace

File: test/e2e/apimachinery/initializers.go [hunk 4]
```diff
@@ -145,8 +147,9 @@ var _ = SIGDescribe("Initializers [Feature:Initializers]", func() {
 		ch := make(chan struct{})
 		go func() {
 			defer close(ch)
-			_, err := c.CoreV1().Pods(ns).Create(newInitPod(podName))
-			Expect(err).NotTo(HaveOccurred())
+			pod := newInitPod(podName)
+			_, err := c.CoreV1().Pods(ns).Create(pod)
+			Expect(err).NotTo(HaveOccurred(), "failed to create pod: %+v", pod)
```
Comment (spiffxp) [inline test/e2e/apimachinery/initializers.go]: missing namespace, and consider using the pod's name with a `%s` instead

File: test/e2e/apimachinery/initializers.go [hunk 5]
```diff
@@ -72,34 +73,34 @@ var _ = SIGDescribe("Initializers [Feature:Initializers]", func() {
...
+		Expect(err).NotTo(HaveOccurred(), "failed to get pod %s in namespace: %s", podName, ns)
 		pod.Annotations = map[string]string{"update-1": "test"}
 		pod, err = c.CoreV1().Pods(ns).Update(pod)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to update pod %s to: %+v", pod.Name, pod)
 
 		// verify the list call filters out uninitialized pods
 		pods, err := c.CoreV1().Pods(ns).List(metav1.ListOptions{IncludeUninitialized: true})
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to list pods in namespace: %s", ns)
```
Comment (spiffxp) [inline test/e2e/apimachinery/initializers.go]: I saw earlier messages included the list options, maybe here as well?

**Review by spiffxp — CHANGES_REQUESTED** [review]
Thanks so much for PR'ing this, this is a lot of lines touched!

I reviewed about halfway before stopping, so keep in mind there are more examples of the following than I explicitly called out:
- I think we want to be consistent about logging the namespace being used for namespace-scoped objects
- I think we generally don't want to dump an entire pod spec with `+%v`, but there were some cases that may make sense (ie: error updating pod "foo" to <pod spec>)
- I'm not sure it's worth calling out "or pods went to Failed state" if you're err'ing on WaitForPod, but I could be convinced either way

File: test/e2e/apimachinery/garbage_collector.go [hunk 6]
```diff
@@ -818,31 +818,34 @@ var _ = SIGDescribe("Garbage collector", func() {
...
+		patch3 := addRefPatch(pod2.Name, pod2.UID)
+		pod3, err = podClient.Patch(pod3.Name, types.StrategicMergePatchType, patch3)
+		Expect(err).NotTo(HaveOccurred(), "failed to apply to pod %s a strategic merge patch: %s", pod3.Name, patch3)
 		framework.Logf("pod3.ObjectMeta.OwnerReferences=%#v", pod3.ObjectMeta.OwnerReferences)
 		// delete one pod, should result in the deletion of all pods
 		deleteOptions := getForegroundOptions()
 		deleteOptions.Preconditions = metav1.NewUIDPreconditions(string(pod1.UID))
 		err = podClient.Delete(pod1.ObjectMeta.Name, deleteOptions)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to delete pod: %s", pod1.ObjectMeta.Name)
```
[the remark this answers is not in the document]
Comment (audreylim) [reply test/e2e/apimachinery/garbage_collector.go]: I referenced the previous line which used `pod1.ObjectMeta.Name` but I think both refer to the same since `ObjectMeta.Name` is a promoted field (https://github.com/kubernetes/api/blob/master/core/v1/types.go#L3116). I've changed it to `pod1.Name` here and left the other references to `pod1.ObjectMeta.Name` alone, maybe the author wanted more clarity.

File: test/e2e/apimachinery/webhook.go [hunk 7]
```diff
@@ -672,15 +672,15 @@ func testWebhook(f *framework.Framework) {
 		cm.Data["webhook-e2e-test"] = "webhook-disallow"
 	}
 	_, err = updateConfigMap(client, f.Namespace.Name, allowedConfigMapName, toNonCompliantFn)
-	Expect(err).NotTo(BeNil())
+	Expect(err).To(HaveOccurred(), "update (PUT) admitted configmap %s to a non-compliant one should be rejected by webhook", allowedConfigMapName)
```
Comment (spiffxp) [inline test/e2e/apimachinery/webhook.go]: missing namespace

File: test/e2e/apimachinery/watch.go [hunk 8]
```diff
@@ -261,23 +263,23 @@ var _ = SIGDescribe("Watchers", func() {
 
 		By("creating a watch on configmaps with a certain label")
 		testWatch, err := watchConfigMaps(f, "", toBeChangedLabelValue)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to create configmap with label: %s", toBeChangedLabelValue)
 
 		By("creating a new configmap")
 		testConfigMap, err = c.CoreV1().ConfigMaps(ns).Create(testConfigMap)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to create configmap %s", configMapName, configMapName)
```
Comment (spiffxp) [inline test/e2e/apimachinery/watch.go]: missing namespace

**Comment by audreylim** [comment]
Thanks for your feedback! I've:
- added namespaces where its scoped
- replaced spec dumps with object names
- addressed the other comments

Notes:
- I added `or pods went to Failed state` on WaitForPod to give possible reasons on failure (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L1422), but I changed them to the more generic and also helpful "error while waiting for pod %s to go to Running phase in namespace %s". 
- I can squash the commits if needed

File: test/e2e/apimachinery/watch.go [hunk 9]
```diff
@@ -261,23 +263,23 @@ var _ = SIGDescribe("Watchers", func() {
 
 		By("creating a watch on configmaps with a certain label")
 		testWatch, err := watchConfigMaps(f, "", toBeChangedLabelValue)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to create configmap with label: %s", toBeChangedLabelValue)
```
Comment (spiffxp) [inline test/e2e/apimachinery/watch.go]: failed to create a watch on configmaps with label

File: test/e2e/apimachinery/watch.go [hunk 10]
```diff
@@ -197,17 +198,17 @@ var _ = SIGDescribe("Watchers", func() {
 
 		By("creating a watch on configmaps")
 		testWatchBroken, err := watchConfigMaps(f, "", watchRestartedLabelValue)
-		Expect(err).NotTo(HaveOccurred())
+		Expect(err).NotTo(HaveOccurred(), "failed to create a watch on configmaps: %s", watchRestartedLabelValue)
```
Comment (spiffxp) [inline test/e2e/apimachinery/watch.go]: configmaps with with label

**Review by spiffxp — COMMENTED** [review]
few tiny nits to fix, otherwise lgtm

and yeah feel free to squash

**Comment by audreylim** [comment]
Fixed

**Comment by audreylim** [comment]
oops, made a slight change here: https://github.com/kubernetes/kubernetes/pull/69583/files#diff-b3ef5995f1063613af33e678183dc03dR57

removed `pod := newTablePod(podName)` since pod spec wasn't used in error message anymore
