### PR TITLE
Enhance log information of verifyRunAsNonRoot, add pod, container information

### LINKED ISSUE #94898: container has runAsNonRoot and image will run as root warning should include container name
when deploying a container that has runAsNonRoot but runs as root this error appears, but for pods with lots of containers it can be confusing which container failed, especially if there are 3-rd party webhooks that inject containers
please add the container name to the message, making it `container "foo" has runAsNonRoot and image will run as root`

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

If the pod contains multiple containers, the prompt message here cannot quickly determine which container `verifyRunAsNonRoot` has the problem. 

Therefore, add information about pod and container to the log for quick positioning

**Which issue(s) this PR fixes**:

Fixes #94898

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Enhance log information of verifyRunAsNonRoot, add pod, container information
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by grosser** [comment]
adding the container sounds right, I'm not sure if we need the pod since that might be already in the message/be the object of the event, but I bet there are cases where it's not, so should be a good addition (and in doubt better have more info to debug) 👍

File: pkg/kubelet/kuberuntime/security_context_others.go [hunk 1]
```diff
@@ -35,16 +35,16 @@ func verifyRunAsNonRoot(pod *v1.Pod, container *v1.Container, uid *int64, userna
 
 	if effectiveSc.RunAsUser != nil {
 		if *effectiveSc.RunAsUser == 0 {
-			return fmt.Errorf("container's runAsUser breaks non-root policy")
+			return fmt.Errorf("container's runAsUser breaks non-root policy (pod: %s, container: %s)", pod.Name, container.Name)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_others.go:38]: ass pod namespace. `format.Pod` would be the best

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go:38]: same below

Comment (tallclair) [reply pkg/kubelet/kuberuntime/security_context_others.go:38]: We have a standard utility for this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/format/pod.go#L32

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 1 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go]: done~

Comment (krmayankk) [reply pkg/kubelet/kuberuntime/security_context_others.go]: nice , didnt know about this . Curious why is this utility in pkg/kubelet, it can be useful outside of kubelet as well

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go]: > nice , didnt know about this . Curious why is this utility in pkg/kubelet, it can be useful outside of kubelet as well

I think the idea is to eventually switch to structured logging where this would be solved out of the box

**Comment by wawa0210** [comment]
@sjenning @ yujuhong
