### PR TITLE
Update 1.4 test to stop looking at field that isn't present.  Fixes #…

### LINKED ISSUE #35741: [k8s.io] Kubectl client [k8s.io] Kubectl apply should reuse nodePort when apply to an existing SVC {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke-staging-parallel/1671/

Failed: [k8s.io] Kubectl client [k8s.io] Kubectl apply should reuse nodePort when apply to an existing SVC {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:134
Oct 27 16:08:39.030: Couldn't delete ns: "e2e-tests-kubectl-5yeis": an error on the server ("Internal Server Error: \"/apis/autoscaling/v1/namespaces/e2e-tests-kubectl-5yeis/horizontalpodautoscalers\"") has prevented the request from succeeding (get horizontalpodautoscalers.autoscaling) (&errors.StatusError{ErrStatus:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"an error on the server (\"Internal Server Error: \\\"/apis/autoscaling/v1/namespaces/e2e-tests-kubectl-5yeis/horizontalpodautoscalers\\\"\") has prevented the request from succeeding (get horizontalpodautoscalers.autoscaling)", Reason:"InternalError", Details:(*unversioned.StatusDetails)(0xc82097e730), Code:500}})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:338
```

Previous issues for this test: #28523

### PR DESCRIPTION
**Pull request by pwittrock**
Fixes #35741 by making the test a no-op.  It was a no-op before because it had invalid expectations that are now validated in 1.5

### CODE REVIEW

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -498,25 +498,29 @@ var _ = framework.KubeDescribe("Kubectl client", func() {
 			By("checking the result")
 			forEachReplicationController(c, ns, "app", "redis", validateReplicationControllerConfiguration)
 		})
-		It("should reuse nodePort when apply to an existing SVC", func() {
+		It("should reuse port when apply to an existing SVC", func() {
+			// This test doesn't do anything meaningful.  It was supposed to test that the nodeport
```
Comment (ixdy) [inline test/e2e/kubectl.go]: if this test doesn't do anything meaningful, why do we have it?

Comment (pwittrock) [inline test/e2e/kubectl.go]: It is intended to do something meaningful - but was written in a way that didn't.  I could just delete the whole test, but ideally we would fix it to test the right thing.

Comment (ymqytw) [inline test/e2e/kubectl.go]: FYI This test is initially introduced by #24180 in v1.2

Comment (pwittrock) [inline test/e2e/kubectl.go]: These changes were already made on master, and should have been backported to 1.4 branch, but weren't.  This backports the changes to make the version skew test pass.

**Comment by jessfraz** [comment]
lgtm and all green so merging
