### PR TITLE
Assume volume is detached if node doesn't exist

### LINKED ISSUE #29358: GCE PD Detach fails if node no longer exists
**Problem:**

If a node with a GCE PD attached is deleted (before the volume is detached), subsequent attempts by the attach/detach controller to detach it continuously fail, and prevent the controller from attaching the volume to another node.

**Repro steps:**

1. Create a pod referencing a GCE PD
2. Wait for pod to get scheduled and running.
3. Delete the node VM (using gcloud) that the pod is scheduled to.
4. Check if volume is detached by attach/detach controller:
  * *Expected:* Volume detached.
  * *Actual:* Volume continuously fails detach.

**Logs:**
<details>
From `/var/log/kube-controller-manager.log`:
```
I0721 03:21:43.464087       7 reconciler.go:134] Started DetachVolume for volume "X" from node "Y" due to maxWaitForUnmountDuration expiry.
E0721 03:21:43.591941       7 gce.go:2580] getInstanceByName/single-zone: failed to get instance Y; err: googleapi: Error 404: The resource 'projects/[project]/zones/[zone]/instances/Y' was not found, notFound
E0721 03:21:43.591985       7 attacher.go:215] Error checking if PD ("[pdname]") is already attached to current node ("Y"). Will continue and try detach anyway. err=instance not found
E0721 03:21:43.698786       7 gce.go:2580] getInstanceByName/single-zone: failed to get instance Y; err: googleapi: Error 404: The resource 'projects/[project]/zones/[zone]/instances/Y' was not found, notFound
E0721 03:21:43.698828       7 attacher.go:225] Error detaching PD "[pdname]" from node "Y": error getting instance "Y"
```
</details>

**Workarounds:**

* Restart the kube-controller-manager binary on the master.

-or-

* Recreate a node with the same name.

**Proposed Fix:**

If GCE PD detach fails with `instance not found`, assume successful detach.

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #29358

### CODE REVIEW

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -869,7 +869,7 @@ func (c *Cloud) InstanceID(name string) (string, error) {
 	}
 	inst, err := c.getInstanceByNodeName(name)
 	if err != nil {
-		return "", err
+		return "", fmt.Errorf("getInstanceByNodeName failed for %q with %v", name, err)
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Yes, we have to be really careful with when we return InstanceNotFound.  According to the comments on cloudprovider.Instances, we must return InstanceNotFound, but actually that's wrong and it only applies to ExternalID (AFAICT), and you didn't wrap it.  I'll put in a separate PR to fix the comments.

To (try to) be clear: But what you're done here is right,  though it would be wrong if the docs were right.  At least I think so!

**Comment by justinsb** [comment]
LGTM

**Comment by justinsb** [comment]
Doc fix for the contract: https://github.com/kubernetes/kubernetes/pull/29490

**Comment by saad-ali** [comment]
Thanks @justinsb

File: pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go [hunk 2]
```diff
@@ -62,10 +62,12 @@ func (nsu *nodeStatusUpdater) UpdateNodeStatuses() error {
...
 		nodeObj, exists, err := nsu.nodeInformer.GetStore().GetByKey(nodeName)
 		if nodeObj == nil || !exists || err != nil {
-			return fmt.Errorf(
-				"failed to find node %q in NodeInformer cache. %v",
+			// If node does not exist, its status cannot be updated, log error and move on.
+			glog.Warningf(
+				"Could not update node status. Failed to find node %q in NodeInformer cache. %v",
 				nodeName,
 				err)
+			return nil
```
Comment (liggitt) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: should this be continuing (as per the comment), rather than returning from the whole func?

Comment (saad-ali) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: The behavior is correct. Perhaps the comment can be clarified. "Move on" in this case means abandon trying to update the status of a node (since it no longer exists).

Comment (liggitt) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: ok, wasn't sure if it was intending to also short-circuit and not update any of the other remaining nodes, or if a bad nodeName could permanently block ever getting to update those nodes' status
