### PR TITLE
Test API more extensivelly before declaring readiness 

### LINKED ISSUE #34411: error: <master/discovery> failed to create "kube-discovery" deployment [deployments.extensions "kube-discovery" is forbidden: not yet ready to handle request]
used kubeadm init error? thanks for help!

### PR DESCRIPTION
**Pull request by errordeveloper**
**What this PR does / why we need it**:

It's possible that first deployment kubeadm creates will hit `deployments.extensions "kube-discovery" is forbidden: not yet ready to handle request`, which comes from NamespaceLifecycle admission controller and has something to do with cache. According to @derekwaynecarr, we need to create a namespace-scoped resource to really check for this. I didn't want to make a check with deployment of whatever comes first right now, and decided to have explicit step for this in `apiclient.go`.

**Which issue this PR fixes**: fixes #34411

**Special notes for your reviewer**: @kubernetes/sig-cluster-lifecycle 

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34573)

### CODE REVIEW

**Comment by errordeveloper** [comment]
I have signed LF CLA now.

**Comment by mikedanese** [comment]
Would it work to just retry the deployment creation?

**Comment by errordeveloper** [comment]
> Would it work to just retry the deployment creation?

Like each and every one, or just the first one. I don't like doing it for the first one, as order is easy to break.

**Review by pires — APPROVED** [review]

File: cmd/kubeadm/app/master/apiclient.go [hunk 1]
```diff
@@ -219,3 +222,41 @@ func SetMasterNodeAffinity(meta *api.ObjectMeta) {
...
+	fmt.Println("<master/apiclient> attempting a test deployment")
+	dummyDeployment := NewDeployment("dummy", 1, api.PodSpec{
+		SecurityContext: &api.PodSecurityContext{HostNetwork: true},
+		Containers: []api.Container{{
+			Name:  "dummy",
+			Image: images.GetAddonImage("pause"),
+		}},
+	})
+
+	wait.PollInfinite(apiCallRetryInterval, func() (bool, error) {
```
Comment (mikedanese) [inline cmd/kubeadm/app/master/apiclient.go]: This seems like it could run forever silently. Can we add a timeout or occasionally report statuses?

Comment (errordeveloper) [inline cmd/kubeadm/app/master/apiclient.go]: There is a status line below...

**Comment by mikedanese** [comment]
I'm farily certain this error is coming from the service account admission controller because a service account doesn't exist in the namespace. Why aren't we polling for the existance of the default service account?

File: cmd/kubeadm/app/master/apiclient.go (hunk 1 above)
Comment (mikedanese) [inline cmd/kubeadm/app/master/apiclient.go]: Oops, misread.

Comment (errordeveloper) [inline cmd/kubeadm/app/master/apiclient.go]: I'd like to find a way to improve our usage of `wait.PollInfinite()` everywhere, but haven't quite figured it out yet. We would definitely benefit from kubelet API, if it will allow us to do less polling and get instant confirmation of control plane components getting deployed or erroring otherwise...

File: cmd/kubeadm/app/master/apiclient.go [hunk 2]
```diff
@@ -219,3 +222,41 @@ func SetMasterNodeAffinity(meta *api.ObjectMeta) {
...
+		d, err := client.Extensions().Deployments(api.NamespaceSystem).Get("dummy")
+		if err != nil {
+			fmt.Printf("<master/apiclient> failed to get test deployment [%v] (will retry)", err)
+			return false, nil
+		}
+		if d.Status.AvailableReplicas < 1 {
+			return false, nil
```
Comment (errordeveloper) [inline cmd/kubeadm/app/master/apiclient.go]: This will make it wait silently, but hopefully it should be quick enough...

**Comment by mikedanese** [comment]
e.g. https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L946-L951

**Comment by errordeveloper** [comment]
Looks like we could with some other funcs from `e2e/framework/util.go`...

**Comment by mikedanese** [comment]
Let's do this for now and then move to waiting for the service account.

**Comment by luxas** [comment]
@mikedanese Is that a LGTM? :)
