### PR TITLE
[Proxy]: add `healthz` verification when determining HC response for eTP:Local

### LINKED ISSUE #111539: [scale] node state changes causes excessive LB re-configurations
### What happened?

There is scale bug related to the cloud-controller-manager, namely: when a cluster reaches a state where the relation between the amount of LBs and cluster nodes reaches an almost equal amount (i.e: a many-to-many relation between LBs and nodes) the amount of cloud API calls performed by the CCM to sync LBs can become overwhelming for the cloud provider. This can (among other things) lead to:

1. an excessive amount of cloud API calls for the LB re-configurations
2. rate limiting by the cloud provider as an effect of 1.
3. or worse: a non-trivial amount of time to sync all services in the cluster, leading to desynchronized LBs.

An example of problem 3. is: imagine we have 200 LBs and 500 nodes, on clusters at such scale, the amount of events processed by the CCM for transitioning node state can become important. The current implementation of the CCM will resync all 200 LB services for any node which has a transitioning state - as to keep the LBs' configured backends in sync with the state of the cluster. It has been observed that on clusters at that scale, the cloud provider can take up to hours to process a full resync for all services. A scenario such as the below is hence not improbable (and actually quite likely):

1. Node25 transitions from Ready -> NotReady
[All LB services are synced - time taken for this might be long]
2. Service1's LB which only has an endpoint on Node25 gets Node25 removed from its list of backend
3. Node25 transitions from NotReady -> Ready again, cancelling the scheduled eviction for the endpoint hosted on Node25 for Service1
4. CCM is still processing the updated caused by 1. and clients connecting to the LB of Service1 continues experiencing connectivity issues, even though Node25 now is in a Ready state.
[Eventually - once the CCM enters its second reconciliation loop caused by 3.]
5. The LB for Service1 gets Node25 added to its list of backend again and connectivity is again achieved by clients.

The sync function which is triggered when a node transitions state from Ready <-> NotReady, is currently correct but can be avoided for services which have ExternalTrafficPolicyLocal if the service does not have an endpoint on any of the nodes which are transitioning state between Ready <-> NotReady. This is because such services are not designed to forward traffic to any other node, and the update is thus useless to them. The node which is experiencing a transitioning state is already configured for that LB, and the fact that it transitions state is a moot point for what concerns these services. 

The longer vision I have for this: remove the sync function for transitioning node readiness state from the CCM altogether and instead have all services of type LoadBalancer evaluate the node's readiness state by the utilization of a LB configured health check probe against the [kubelet's read-only port](https://github.com/kubernetes/kubernetes/blob/master/pkg/cluster/ports/ports.go#L33). This would allow transitioning node readiness state to be handled much more dynamically (similar to what has already been implemented for HealthCheckNodePort by kube-proxy) for all services of type LoadBalancer irrespectively of if they define ExternalTrafficPolicyLocal or not....but that will require a enhancement proposal since cloud providers have divergent implementations of how they configure health check probes for LB services.

I am putting this here for completeness sake: this is what the major cloud providers currently do to health check services which are not ExternalTrafficPolicyLocal

GCE: probes [10256](https://github.com/kubernetes/kubernetes/blob/master/pkg/cluster/ports/ports.go#L36)
AWS: if ELB: probes the first NodePort defined on the service spec.
Azure: probes all NodePort defined on the service spec.

All of these can be improved, but an enhancement proposal would be needed to align them all. For now: this PR will help fix some cases.

### What did you expect to happen?

Node readiness changes should not re-configure load balancers associated with services of type ETP=local. 

- Nodes not hosting any endpoints associated with these services do not forward traffic to nodes that do, so re-configuring the LB because said node goes NotReady is useless. 
- Nodes hosting endpoints associated with these services are already health checked using the HC probe configured for the `healthCheckNodePort` and can rely on that much more dynamically without needing to re-configure the LB. 

In the long-term: all load balancers should not be re-configured because of node state changes. That will need an enhancement proposal however (which I am currently drafting) to change service proxies and align cloud provider HCs. 

### How can we reproduce it (as minimally and precisely as possible)?

"as minimally and precisely as possible" not sure if this hits the definition, but: we need a big cluster with a lot of entropy (for example by performing an upgrade and restarting all nodes one-by-one) - this should end up re-configuring every single LB N*M (where N is the amount of nodes and M is the amount of state transitions per node). 

### Anything else we need to know?

Presumably, this has never been a big issue for the externally exposed Kube API service, since that runs on control plane nodes...and I assume those nodes are labeled with https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/well_known_labels.go#L62-L67 (I am pretty sure that's the case for OpenShift). So "Kubernetes distros" avoid this problem using that label...users, don't get that luxury however.  

### Kubernetes version

All versions.

### Cloud provider

All cloud providers. 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### LINKED ISSUE #115825: Kube-proxy does not validate `healthz` state when answering to HC for eTP:Local
### What happened?

KEP https://github.com/kubernetes/enhancements/pull/3837 outlined the fact that Kube-proxy today doesn't perform any validation of its `healthz` state when answering to load balancer HCs for eTP:Local services.

This is a potential problem, because if Kube-proxy is unhealthy then it might also not be writing the rules needed to forward traffic to the endpoint on the node. This means that it might indicate to a load balancer that it should forward traffic to the node, simply because the endpoint is scheduled there

### What did you expect to happen?

Kube-proxy should perform the same validation it currently does for eTP:Local services (i.e: validate that the service has an endpoint scheduled and ready on the node) but AND it with its `healthz` state. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a service of `type: LoadBalancer` + `externalTrafficPolicy: Local`
2. Trigger an issue with Kube-proxy which causes it to fail when writing its rules on the node 
3. Spin up a pod for this service
4. Validate that Kube-proxy continues to indicate to the load balancer that it should send the node traffic, even though it hasn't been able to write the rules required as a consequence of 3. due to 2. 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
all 
</details>

### Cloud provider

<details>
all 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
#### What type of PR is this?

/kind bug 

#### What this PR does / why we need it:

This PR adds an accessor field for `service_health.go` (the one answering to LB HCs for eTP:Local) to the `healthz` state computed in `proxier_health.go`. It will then return a HTTP 200 is the service has a ready endpoint on the node AND if `healthz` is true.   

#### Which issue(s) this PR fixes:

Fixes #[115825](https://github.com/kubernetes/kubernetes/issues/115825)

Kube-proxy will now include the `healthz` state in its response to the LB HC as to avoid indicating to the LB that it should use the node in question when Kube-proxy is not healthy.

#### Does this PR introduce a user-facing change?

```release-note
Fixes #115825. Kube-proxy will now include the `healthz` state in its response to the LB HC as to avoid indicating to the LB that it should use the node in question when Kube-proxy is not healthy.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig network
/assign @thockin

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/assign @thockin @danwinship 

We've found recently that the node handlers are feature gated, if we want to use this handlers we should remove the feature gate check on the Node informer https://github.com/kubernetes/kubernetes/pull/111344#discussion_r936833738


https://github.com/kubernetes/kubernetes/blob/d96af5f2761c23eddde206aee7b7147a9692b737/cmd/kube-proxy/app/server.go#L753-L766

File: pkg/proxy/healthcheck/service_health.go [hunk 1]
```diff
@@ -36,6 +36,12 @@ import (
 	utilproxy "k8s.io/kubernetes/pkg/proxy/util"
 )
 
+const (
+	// ToBeDeletedTaint is a taint used by the CLuster Autoscaler before marking a node for deletion. Defined in
+	// https://github.com/kubernetes/autoscaler/blob/e80ab518340f88f364fe3ef063f8303755125971/cluster-autoscaler/utils/deletetaint/delete.go#L36
+	ToBeDeletedTaint = "ToBeDeletedByClusterAutoscaler"
```
Comment (aojea) [inline pkg/proxy/healthcheck/service_health.go:42]: this can be a slippery slope if we have to support all the projects that add taints on nodes :/

File: pkg/proxy/healthcheck/service_health.go [hunk 2]
```diff
@@ -75,14 +85,20 @@ func newServiceHealthServer(hostname string, recorder events.EventRecorder, list
...
 
 // NewServiceHealthServer allocates a new service healthcheck server manager
-func NewServiceHealthServer(hostname string, recorder events.EventRecorder, nodePortAddresses []string) ServiceHealthServer {
-	return newServiceHealthServer(hostname, recorder, stdNetListener{}, stdHTTPServerFactory{}, nodePortAddresses)
+func NewServiceHealthServer(hostname string, recorder events.EventRecorder, nodePortAddresses []string, healthzServer ProxierHealthUpdater) ServiceHealthServer {
+	return newServiceHealthServer(hostname, recorder, stdNetListener{}, stdHTTPServerFactory{}, nodePortAddresses, healthzServer)
+}
+
+type nodeState struct {
+	isHealthy bool
```
Comment (aojea) [inline pkg/proxy/healthcheck/service_health.go:101]: don't we have to do this variable thread safe, it is accessed from multiple places
use atomic perhaps?

File: pkg/proxy/healthcheck/proxier_health.go [hunk 3]
```diff
@@ -91,6 +97,33 @@ func (hs *proxierHealthServer) QueuedUpdate() {
 	hs.oldestPendingQueued.CompareAndSwap(zeroTime, hs.clock.Now())
 }
 
+// IsHealthy returns the proxier's health state. The result reflects its
+// performance w.r.t updating the service rules on the node, specifically:
+// it's healthy when it's fully synced and not timing out syncing the
+// service rules.
+func (hs *proxierHealthServer) IsHealthy() (bool, time.Time, time.Time) {
```
Comment (aojea) [inline pkg/proxy/healthcheck/proxier_health.go:104]: We are exporting a method that outputs two `time.Time` var that are never used and are really obscure.
I suggest to have an internal variable with the healthy status and use IsHealthy() to return its value only, keeping this logic where it was. Same as you did with the services_health
However, wait for @danwinship and @thockin opinions on this

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 4]
```diff
@@ -127,8 +127,10 @@ type healthzPayload struct {
 func TestServer(t *testing.T) {
 	listener := newFakeListener()
 	httpFactory := newFakeHTTPServerFactory()
+	fakeClock := testingclock.NewFakeClock(time.Now())
```
Comment (aojea) [inline pkg/proxy/healthcheck/healthcheck_test.go:130]: We have to add new testcases with the new combinations that we are adding

File: pkg/proxy/healthcheck/service_health.go (hunk 1 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:42]: Hmm, I wanted to start off by saying: "I can't say anything about the future for the proxy code, but the CCM has been looking at only this one taint on services for...", and while looking at the service controller code and inspecting who added this taint, it seems it was added with: https://github.com/kubernetes/kubernetes/pull/105946 which had a very dubious reason for adding it in the first place:

> Prior to https://github.com/kubernetes/kubernetes/pull/90823, these nodes would get removed from the LoadBalancer backend once they were marked as Unschedulable. Now that Unschedulable nodes are tolerated by the node predicate, these nodes will only get removed when the nodes have been deleted.  

Which is not true _today_, the unschedulable predicate was re-added by me in the CCM...but now I am asking myself questions as to whether that was good, the PR removing the unschedulability predicate (#90823) mentioned a production outage

> This caused a production outage when nodes in an autoscaling group were marked unschedulable so the autoscaler would gracefully terminate them - instead the ingress controllers on those nodes were immediately removed from the LB pool and no new ingress requests could be accepted.

/cc @thockin

File: pkg/proxy/healthcheck/proxier_health.go (hunk 3 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/proxier_health.go:104]: Yes, that makes more sense. I will change

File: pkg/proxy/healthcheck/healthcheck_test.go (hunk 4 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/healthcheck_test.go:130]: Will do

File: pkg/proxy/healthcheck/service_health.go (hunk 2 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:101]: Good point, we probably need to "wrap" `SyncNode` in 

```
hcs.lock.Lock()
defer hcs.lock.Unlock()
```

As has been done for `SyncService`. The read should already be protected though in `ServeHTTP` by the read lock.

Comment (aojea) [reply pkg/proxy/healthcheck/service_health.go:101]: I like this atomic bool vars for these cases, your choice though

https://github.com/kubernetes/kubernetes/blob/ee505677f70439ff8f5515cc899eab7c18cdb1dd/pkg/proxy/iptables/proxier.go#L588-L598

https://gist.github.com/mahan/6256149

Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:101]: But in this case there really is only one writer, there's no concurrency. `SyncNode` is only invoked by the node informer, and its event handlers (add/update/delete) cannot be called concurrently. So we hence only ever have one writer at any given moment in time. 

Making it an atomic bool would give the impression to people reading the code that we are dealing with concurrency, where in fact that is not the case.

Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:101]: Nevermind what I said above, I was confused. There is concurrency, but I find the code reads better by using `hcs.lock`

**Comment by alexanderConstantinescu** [comment]
> We've found recently that the node handlers are feature gated, if we want to use this handlers we should remove the feature gate check on the Node informer [#111344 (comment)](https://github.com/kubernetes/kubernetes/pull/111344#discussion_r936833738)

Hmm, I would have imagined the node handler to be feature gated because `TopologyAwareHints` is, not because the node handler specifically is? If the latter is true, what does that even mean for the node handler to be feature gated - it's not a feature in itself, but more like a means to implementing a feature - like `TopologyAwareHints`.  

In any case: we could also just dial the Kubelet's healthz port on `localhost`, that should be equivalent to listing / watching the node object and inspecting if its `NodeReady` condition is `ConditionTrue`. The problem would be trying to work out the taints the node object has. But I would say the taint we currently look at (`ToBeDeletedByClusterAutoscaler`) is just pre-mature optimization for a node which will be deleted or go `NotReady` in the future. That taint doesn't mean anything _right now_, and if it really is going to be deleted in the near future, then we could just start flagging the node as "not serviceable for LB traffic" when that happens.  PR #105946 didn't really go a very good job at mentioning why we do this to begin with:

> Prior to https://github.com/kubernetes/kubernetes/pull/90823, these nodes would get removed from the LoadBalancer backend once they were marked as Unschedulable. Now that Unschedulable nodes are tolerated by the node predicate, these nodes will only get removed when the nodes have been deleted. If multiple such nodes are being deleted, the list of nodes passed to cloud-provider code via UpdateLoadBalancer() will be stale, causing a few failed updates before the backends stabilize.

File: pkg/proxy/healthcheck/service_health.go (hunk 1 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:42]: I've revisited this condition as a part of my work on https://github.com/kubernetes/kubernetes/pull/111658. I think we can remove this condition. It didn't have any clear reasons for being added in the first place and logically, today, it doesn't make sense. 

We can discuss this on the on-going KEP I have: https://github.com/kubernetes/enhancements/pull/3460 now during the 1.26 KEP cycle. I thought upon the life cycle of the Node and its relation to the LB in that document. I think we can remove this condition altogether at this point, but I will leave the PR as-is until we get some clarity and consensus on the KEP. Once done, I will update the PR for 1.26.

**Comment by thockin** [comment]
I was away for a bit but I spent all afternoon thinking about this topic and I am less confident than ever :)

An even more revised drawing (now v3):
Node_LB_states_v3

A few things of note:

### 1) How to handle `deletionTimestamp` being set

a) We could exclude being-deleted nodes as a predicate (e.g. `notBeingDeletedPredicate`).  This is simple to do here, and well-behaved clusters already drained the node anyway (with `unschedulable`).  We might miss out on some extra draining time while being deleted, but that seems pretty minor (I don't think cluster-autoscaler uses finalizers).

b) Or we could NOT exclude them (but comment in code why not), and make the on-node HC fail while being deleted.  This gives us extra time to drain LB traffic, but well-behaved clusters already drained the node anyway (with `unschedulable`).

I think (a).

### How to handle the `ToBeDeletedByClusterAutoScaler` taint

See https://github.com/kubernetes/autoscaler/issues/5201 for more context

a) We could exclude tained nodes (as we do today).  The way cluster-autosclaer seems to work means that down-scaled nodes would get `unschedulable` and `ToBeDeletedByClusterAutoScaler` set at the same time, and thus get no LB drain time (as we do today).

b) We could NOT exclude them (but comment in code why not) and maybe make the on-node HC fail.  I think this will break autoscalers who try to delete the underlying VM before the k8s node.  Perhaps we should use finalizers (clear it when all LBs have been updated), which would add weight to (1a) above.

I think (a) for now, but I find it clumsy, and hope I am just mis-reading.

### How to handle `unschedulable` being true

We already do not handle this in the controller.

a) We could ignore it (as we do today).  Given that `unschedulable` often means a node is going away "soon", this would let such nodes handle new connections right up until it is deleted, which cause abrupt errors.

b) We could make all LB->Node HCs fail when `unschedulable` is set.  This would drain LB traffic on some clouds (no new connections, retain existing ones), which makes sense if you consider that `unschedulable` often means a node is going away "soon".   For `eTP: Local` services, this would mean any endpoints on that node are no longer available to serve, even during draining.  If you have a one-replica service and start draining the node that lone pod is on, the service will be unavailable until a new pod is started elsewhere.

c) We could make `eTP: Cluster` LB->Node HCs fail when `unschedulable` is set, while `eTP: Local` would pass.  This would drain "at-large" LB traffic on some clouds (no new connections, retain existing ones), which makes sense if you consider that `unschedulable` often means a node is going away "soon", but would let `eTP: Local` services continue to serve.  Presumable such pods would be gracefully terminated and restarted elsewhere.

I think (c) makes sense, but it a bit more subtle than we discussed before.

What do you think?

**Comment by alexanderConstantinescu** [comment]
Update:

On https://github.com/kubernetes/enhancements/pull/3837 we agreed that the fact that Kube-proxy does not consider its healthz state when answering to the HC for eTP:Local services, to be a bug. 

I've updated this PR to only address that bug. 

I will file an issue for this and link it to this bug.

**Comment by alexanderConstantinescu** [comment]
/retitle [Proxy]: add `healthz` verification when determining HC response for eTP:Local

File: pkg/proxy/healthcheck/service_health.go [hunk 5]
```diff
@@ -226,14 +229,15 @@ func (h hcHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
...
 	count := svc.endpoints
+	healthzHealthy := h.hcs.healthzServer.IsHealthy()
 	h.hcs.lock.RUnlock()
 
 	resp.Header().Set("Content-Type", "application/json")
 	resp.Header().Set("X-Content-Type-Options", "nosniff")
-	if count == 0 {
-		resp.WriteHeader(http.StatusServiceUnavailable)
-	} else {
+	if count != 0 && healthzHealthy {
```
Comment (danwinship) [inline pkg/proxy/healthcheck/service_health.go:237]: You should probably update the JSON body as well. eg, add a `"kubeProxyHealthy": %v`, to make it clear why it's failing in this case

File: pkg/proxy/healthcheck/proxier_health.go [hunk 6]
```diff
@@ -39,6 +39,12 @@ type ProxierHealthUpdater interface {
 	// rules to reflect the current state.
 	Updated()
 
+	// IsHealthy returns the proxier's health state. The result reflects its
+	// performance w.r.t updating the service rules on the node, specifically:
+	// it's healthy when it's fully synced and not timing out syncing the
+	// service rules.
+	IsHealthy() bool
```
[the remark this answers is not in the document]
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/proxier_health.go:44]: OK, I changed the wording

File: pkg/proxy/healthcheck/service_health.go (hunk 5 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go]: Updated!

File: pkg/proxy/healthcheck/service_health.go [hunk 7]
```diff
@@ -52,7 +52,7 @@ type ServiceHealthServer interface {
 	SyncEndpoints(newEndpoints map[types.NamespacedName]int) error
 }
 
-func newServiceHealthServer(hostname string, recorder events.EventRecorder, listener listener, factory httpServerFactory, nodePortAddresses []string) ServiceHealthServer {
+func newServiceHealthServer(hostname string, recorder events.EventRecorder, listener listener, factory httpServerFactory, nodePortAddresses []string, healthzServer ProxierHealthUpdater) ServiceHealthServer {
```
Comment (thockin) [inline pkg/proxy/healthcheck/service_health.go:55]: I would maybe do:

```
type proxyHealthChecker interface {
  IsHealthy() bool
}

func newServiceHealthServer(..., proxyChecker proxyHealthChecker) ServiceHealthServer {
```

**Review by thockin — COMMENTED** [review]
looks good, just needs rebase. minor comment

File: pkg/proxy/healthcheck/proxier_health.go [hunk 8]
```diff
@@ -94,6 +98,37 @@ func (hs *proxierHealthServer) QueuedUpdate() {
...
 }
 
+// IsHealthy returns the proxier's health state, following the same definition
+// the HTTP server defines.
+func (hs *proxierHealthServer) IsHealthy() bool {
+	isHealthy, _, _ := hs.isHealthy()
+	return isHealthy
+}
+
+func (hs *proxierHealthServer) isHealthy() (bool, time.Time, time.Time) {
```
Comment (aojea) [inline pkg/proxy/healthcheck/proxier_health.go:108]: just a thought, we are returning the two `time.Time` just for the output message, why if we just output the message directly?

```
// isHealthy returns the state of the proxy and a message with the reason in case is not healthy
func (hs *proxierHealthServer) isHealthy() (bool, string)
...
return false, fmt.Printf(`{"lastUpdated": %q,"currentTime": %q}`, lastUpdated, currentTime)
```

or just an error with the message

```
// isHealthy returns and error if not healthy
func (hs *proxierHealthServer) isHealthy() error
...
return fmt.Errorf(`{"lastUpdated": %q,"currentTime": %q}`, lastUpdated, currentTime)
```

File: pkg/proxy/healthcheck/proxier_health.go [hunk 9]
```diff
@@ -94,6 +98,37 @@ func (hs *proxierHealthServer) QueuedUpdate() {
...
+	var oldestPendingQueued, lastUpdated time.Time
+	if val := hs.oldestPendingQueued.Load(); val != nil {
+		oldestPendingQueued = val.(time.Time)
+	}
+	if val := hs.lastUpdated.Load(); val != nil {
+		lastUpdated = val.(time.Time)
```
Comment (aojea) [inline pkg/proxy/healthcheck/proxier_health.go:114]: @danwinship why do we need lastUpdated, it doesn't seem to be used anywhere?

Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/proxier_health.go:114]: Maybe: https://github.com/kubernetes/kubernetes/blob/f286545c48fa04f609cb923ac39b5c7679098054/pkg/proxy/healthcheck/proxier_health.go#L168-L173

?

File: pkg/proxy/healthcheck/service_health.go (hunk 7 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:55]: We could, [but every proxier implementation is initialized with a `ProxierHealthUpdater`](https://github.com/kubernetes/kubernetes/blob/f286545c48fa04f609cb923ac39b5c7679098054/pkg/proxy/iptables/proxier.go#L237), so we would need to do wire things like:

```go
// ProxierHealthUpdater allows callers to update healthz timestamp only.
type ProxierHealthUpdater interface {
	// QueuedUpdate should be called when the proxier receives a Service or Endpoints
	// event containing information that requires updating service rules.
	QueuedUpdate()

	// Updated should be called when the proxier has successfully updated the service
	// rules to reflect the current state.
	Updated()

	// Run starts the healthz HTTP server and blocks until it exits.
	Run() error

	proxierHealthChecker
}

type proxierHealthChecker interface {
	// IsHealthy returns the proxier's health state, following the same
	// definition the HTTP server defines.
	IsHealthy() bool
}
```

maybe I'm missing something?

File: pkg/proxy/healthcheck/proxier_health.go (hunk 8 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/proxier_health.go:108]: I will let owners / people more experienced with the proxy code comment on this.

Comment (thockin) [reply pkg/proxy/healthcheck/proxier_health.go:108]: I would not rely on an `error.Error()` to return valid JSON - that's a little weird.

We could return the JSON as `[]byte` or even return a struct but I don't think it's worth the extra plumbing.

File: pkg/proxy/healthcheck/service_health.go (hunk 7 above)
Comment (thockin) [reply pkg/proxy/healthcheck/service_health.go:55]: I just meant an interface to decouple and maybe make tesing easier.

I checked out your PR and made this change:

```diff
diff --git a/pkg/proxy/healthcheck/service_health.go b/pkg/proxy/healthcheck/service_health.go
index 277a127d9dc..44f3d255afe 100644
--- a/pkg/proxy/healthcheck/service_health.go
+++ b/pkg/proxy/healthcheck/service_health.go
@@ -52,7 +52,12 @@ type ServiceHealthServer interface {
 	SyncEndpoints(newEndpoints map[types.NamespacedName]int) error
 }
 
-func newServiceHealthServer(hostname string, recorder events.EventRecorder, listener listener, factory httpServerFactory, nodePortAddresses []string, healthzServer ProxierHealthUpdater) ServiceHealthServer {
+// healthChecker is something that can report whether it is healthy or not.
+type healthChecker interface {
+	IsHealthy() bool
+}
+
+func newServiceHealthServer(hostname string, recorder events.EventRecorder, listener listener, factory httpServerFactory, nodePortAddresses []string, proxyChecker healthChecker) ServiceHealthServer {
 
 	nodeAddresses, err := utilproxy.GetNodeAddresses(nodePortAddresses, utilproxy.RealNetwork{})
 	if err != nil || nodeAddresses.Len() == 0 {
@@ -75,15 +80,15 @@ func newServiceHealthServer(hostname string, recorder events.EventRecorder, list
 		recorder:      recorder,
 		listener:      listener,
 		httpFactory:   factory,
-		healthzServer: healthzServer,
+		proxyChecker:  proxyChecker,
 		services:      map[types.NamespacedName]*hcInstance{},
 		nodeAddresses: nodeAddresses,
 	}
 }
 
 // NewServiceHealthServer allocates a new service healthcheck server manager
-func NewServiceHealthServer(hostname string, recorder events.EventRecorder, nodePortAddresses []string, healthzServer ProxierHealthUpdater) ServiceHealthServer {
-	return newServiceHealthServer(hostname, recorder, stdNetListener{}, stdHTTPServerFactory{}, nodePortAddresses, healthzServer)
+func NewServiceHealthServer(hostname string, recorder events.EventRecorder, nodePortAddresses []string, proxyChecker healthChecker) ServiceHealthServer {
+	return newServiceHealthServer(hostname, recorder, stdNetListener{}, stdHTTPServerFactory{}, nodePortAddresses, proxyChecker)
 }
 
 type server struct {
@@ -94,7 +99,7 @@ type server struct {
 	listener      listener
 	httpFactory   httpServerFactory
 
-	healthzServer ProxierHealthUpdater
+	proxyChecker healthChecker
 
 	lock     sync.RWMutex
 	services map[types.NamespacedName]*hcInstance
@@ -229,7 +234,7 @@ func (h hcHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
 		return
 	}
 	count := svc.endpoints
-	kubeProxyHealthy := h.hcs.healthzServer.IsHealthy()
+	kubeProxyHealthy := h.hcs.proxyChecker.IsHealthy()
 	h.hcs.lock.RUnlock()
 
 	resp.Header().Set("Content-Type", "application/json")
```

That compiles.

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 10]
```diff
@@ -349,9 +352,29 @@ func TestServer(t *testing.T) {
...
 
 func testHandler(hcs *server, nsn types.NamespacedName, status int, endpoints int, t *testing.T) {
+	tHanlder(hcs, nsn, status, endpoints, true, t)
+}
+
+func testHandlerWithHealth(hcs *server, nsn types.NamespacedName, status int, endpoints int, kubeProxyHealthy bool, t *testing.T) {
+	tHanlder(hcs, nsn, status, endpoints, kubeProxyHealthy, t)
+}
+
+func tHanlder(hcs *server, nsn types.NamespacedName, status int, endpoints int, kubeProxyHealthy bool, t *testing.T) {
```
Comment (thockin) [inline pkg/proxy/healthcheck/healthcheck_test.go:377]: tHandler - spelling :)

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 11]
```diff
@@ -131,8 +132,10 @@ type healthzPayload struct {
 func TestServer(t *testing.T) {
 	listener := newFakeListener()
 	httpFactory := newFakeHTTPServerFactory()
+	fakeClock := testingclock.NewFakeClock(time.Now())
+	hs := newProxierHealthServer(listener, httpFactory, fakeClock, "127.0.0.1:10256", 10*time.Second, nil, nil)
```
Comment (thockin) [inline pkg/proxy/healthcheck/healthcheck_test.go:136]: The `interface` in my other comment means you don't have to do this fake-clock stuff (which I find hard to reason about and is not germane to this test)

```diff
diff --git a/pkg/proxy/healthcheck/healthcheck_test.go b/pkg/proxy/healthcheck/healthcheck_test.go
index dd3e9b76976..8db3feaecfb 100644
--- a/pkg/proxy/healthcheck/healthcheck_test.go
+++ b/pkg/proxy/healthcheck/healthcheck_test.go
@@ -129,13 +129,20 @@ type healthzPayload struct {
 	CurrentTime string
 }
 
+type fakeHealthChecker struct {
+	value bool
+}
+
+func (fake fakeHealthChecker) IsHealthy() bool {
+	return fake.value
+}
+
 func TestServer(t *testing.T) {
 	listener := newFakeListener()
 	httpFactory := newFakeHTTPServerFactory()
-	fakeClock := testingclock.NewFakeClock(time.Now())
-	hs := newProxierHealthServer(listener, httpFactory, fakeClock, "127.0.0.1:10256", 10*time.Second, nil, nil)
+	proxyChecker := &fakeHealthChecker{true}
 
-	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, []string{}, hs)
+	hcsi := newServiceHealthServer("hostname", nil, listener, httpFactory, []string{}, proxyChecker)
 	hcs := hcsi.(*server)
 	if len(hcs.services) != 0 {
 		t.Errorf("expected 0 services, got %d", len(hcs.services))
@@ -354,13 +361,13 @@ func TestServer(t *testing.T) {
 	testHandler(hcs, nsn4, http.StatusOK, 6, t)
 
 	// fake a temporary unhealthy proxy
-	hs.oldestPendingQueued.Store(hs.clock.Now().Add(-hs.healthTimeout - time.Second))
+	proxyChecker.value = false
 	testHandlerWithHealth(hcs, nsn2, http.StatusServiceUnavailable, 0, false, t)
 	testHandlerWithHealth(hcs, nsn3, http.StatusServiceUnavailable, 7, false, t)
 	testHandlerWithHealth(hcs, nsn4, http.StatusServiceUnavailable, 6, false, t)
 
 	// fake a healthy proxy
-	hs.oldestPendingQueued.Store(hs.clock.Now())
+	proxyChecker.value = true
 	testHandlerWithHealth(hcs, nsn2, http.StatusServiceUnavailable, 0, true, t)
 	testHandlerWithHealth(hcs, nsn3, http.StatusOK, 7, true, t)
 	testHandlerWithHealth(hcs, nsn4, http.StatusOK, 6, true, t)
```

File: pkg/proxy/healthcheck/service_health.go (hunk 7 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go]: OK, updated the PR with this

File: pkg/proxy/healthcheck/proxier_health.go (hunk 9 above)
Comment (aojea) [reply pkg/proxy/healthcheck/proxier_health.go:118]: yeah, it is always set to currentTime , no? why do we need to get this value, is not used anywhere AFAIK

Comment (aojea) [reply pkg/proxy/healthcheck/proxier_health.go:118]: I mean, we can return `oldestPendingQueued` instead of `lastUpdated`

Comment (aojea) [reply pkg/proxy/healthcheck/proxier_health.go:118]: nevermind, it doesn't solve anything, I just wanted to see if we can save a variable and I said nonsense, please resolve this comment

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 12]
```diff
@@ -434,12 +467,14 @@ func testHealthzHandler(server httpServer, status int, t *testing.T) {
 func TestServerWithSelectiveListeningAddress(t *testing.T) {
 	listener := newFakeListener()
 	httpFactory := newFakeHTTPServerFactory()
+	fakeClock := testingclock.NewFakeClock(time.Now())
```
Comment (thockin) [inline pkg/proxy/healthcheck/healthcheck_test.go:470]: Any reason not to use the simpler fake here?

File: pkg/proxy/healthcheck/proxier_health.go [hunk 13]
```diff
@@ -41,6 +41,14 @@ type ProxierHealthUpdater interface {
 
 	// Run starts the healthz HTTP server and blocks until it exits.
 	Run() error
+
+	proxierHealthChecker
+}
+
+type proxierHealthChecker interface {
```
Comment (thockin) [inline pkg/proxy/healthcheck/proxier_health.go:48]: This is not something you need to act on, but I wanted to call out a small distinction.

You can define this interface here, next to the "producer", and it's fine (it's all the same pkg, after all).  Or you can define it next to the consumer, embracing the Go idea of "produce types, accept interfaces".  This file has no use of this interface, but the service_health (and test) file gets simpler because of it.

The receiver is saying "I need something I can ask IsHealthy()", the producer is passing something that satisfies it.

Again, it's fine this way, too.

**Review by thockin — COMMENTED** [review]
/lgtm
/approve
/hold


minor comment in test - remove hold if you just want to go

File: pkg/proxy/healthcheck/proxier_health.go (hunk 13 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/proxier_health.go]: I wasn't aware of these notions. You got me reading up on something :) I updated the PR with this

File: pkg/proxy/healthcheck/healthcheck_test.go (hunk 12 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/healthcheck_test.go]: No other reason other than: I overlooked it

File: pkg/proxy/healthcheck/service_health.go [hunk 14]
```diff
@@ -226,24 +235,26 @@ func (h hcHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
...
 	}
 	fmt.Fprint(resp, strings.Trim(dedent.Dedent(fmt.Sprintf(`
 		{
 			"service": {
 				"namespace": %q,
 				"name": %q
 			},
-			"localEndpoints": %d
+			"localEndpoints": %d,
+			"kubeProxyHealthy": %v
```
Comment (thockin) [inline pkg/proxy/healthcheck/service_health.go:255]: If we expect this to be an API that different proxy implementations could implement, maybe we should call this `dataplaneHealthy` or something?  Specifically not "kubeProxy" ?

**Review by thockin — COMMENTED** [review]
sorry, 1 more thing

File: pkg/proxy/healthcheck/service_health.go (hunk 14 above)
Comment (alexanderConstantinescu) [reply pkg/proxy/healthcheck/service_health.go:255]: At this point this isn't library code so I wouldn't consider it an API. That being said: I do know some proxy implementations copy this code, so...sure, I'll update

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
```
=== Failed
2595
=== FAIL: pkg/proxy/healthcheck TestServer (0.11s)
2596
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2597
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2598
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2599
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2600
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2601
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2602
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2603
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2604
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2605
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2606
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2607
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2608
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2609
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2610
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2611
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2612
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2613
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2614
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2615
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2616
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2617
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
2618
2619
=== FAIL: pkg/proxy/healthcheck TestServerWithSelectiveListeningAddress (0.00s)
2620
    healthcheck_test.go:413: expected true kubeProxyHealthy, got false
```

**Comment by alexanderConstantinescu** [comment]
Fixed the failing tests and re-pushed
