### PR TITLE
Volume manager must verify containers terminated before deleting for ungracefully terminated pods

### LINKED ISSUE #27691: [k8s.io] Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host [Slow] {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/5567/

Failed: [k8s.io] Pod Disks should schedule a pod w/ a RW PD, remove it, then schedule it on another host [Slow] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:132
Expected error:
    <*errors.errorString | 0xc8200d40b0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

Previous issues for this test: #26970

### PR DESCRIPTION
**Pull request by saad-ali**
A pod is removed from volume manager (triggering unmount) when it is deleted from the kubelet pod manager. Kubelet deletes the pod from pod manager as soon as it receives a delete pod request. As long as the graceful termination period is non-zero, this happens after kubelet has terminated all containers for the pod. However, when graceful termination period for a pod is set to zero, the volume is deleted from pod manager _before_ its containers are terminated.

This  can result in volumes getting unmounted from a pod before all containers have exited when graceful termination is set to zero.

This PR prevents that from happening by only deleting a volume from volume manager once it is deleted from the pod manager AND the kubelet containerRuntime status indicates all containers for the pod have exited. Because we do not want to call containerRuntime too frequently, we introduce a delay in the `findAndRemoveDeletedPods()` method to prevent it from executing more often than every two seconds.

Fixes https://github.com/kubernetes/kubernetes/issues/27691, https://github.com/kubernetes/kubernetes/issues/27477

Running test in tight loop to verify fix.

### CODE REVIEW

**Comment by matchstick** [comment]
@yujuhong Please Take a look.

**Comment by yujuhong** [comment]
> A pod is removed from volume manager (triggering unmount) when it is deleted from the kubelet pod manager. However, kubelet deletes the pod from pod manager as soon as it receives a delete pod request (before it actually does any actual cleanup/waiting for graceful termination of containers). This can result in volumes getting unmounted from a pod before all containers have exited.

Just trying to get enough context before reading the PR. IIUC, the problem would only occur when a pod is deleted non-gracefully (e.g., `kubectl delete pod --grace-period=0`). In other cases, kubelet will ensure all containers have terminated, then send a delete request to the apiserver, and finally cleans up the volumes.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 1]
```diff
@@ -120,6 +124,32 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
 	for _, volumeToMount := range dswp.desiredStateOfWorld.GetVolumesToMount() {
 		if _, podExists :=
 			dswp.podManager.GetPodByUID(volumeToMount.Pod.UID); !podExists {
+			// Once a pod has been deleted from kubelet pod manager, do not
+			// delete it from volume manager. Instead call out to the kubelet
+			// containerRuntime interface to verify all containers in the pod
+			// have been terminated.
+
+			podStatus, podStatusErr := dswp.kubeContainerRuntime.GetPodStatus(
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: I'd prefer getting the podStatus through the cache (`kl.podCache`) to avoid hitting the runtime directly.

**Comment by saad-ali** [comment]
> Just trying to get enough context before reading the PR. IIUC, the problem would only occur when a pod is deleted non-gracefully (e.g., kubectl delete pod --grace-period=0). In other cases, kubelet will ensure all containers have terminated, then send a delete request to the apiserver, and finally cleans up the volumes.

The Problem would occur even if kubelet gracefully shuts down a pod, because volume manager was not waiting for kubelet to terminate the pod.

**Comment by saad-ali** [comment]
> Running test in tight loop to verify fix.

The test still failed after about an hour, going to add in my additional logging to see what's happening.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 2]
```diff
@@ -120,6 +124,32 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
...
+				volumeToMount.Pod.Name,
+				volumeToMount.Pod.Namespace)
+			if podStatusErr != nil {
+				glog.Errorf(
+					"kubeContainerRuntime.GetPodStatus returned error %v. Assuming pod %q is deleted.",
+					podStatusErr,
+					volumeToMount.PodName)
+			} else {
+				for _, containerStatus := range podStatus.ContainerStatuses {
+					if containerStatus.State != kubecontainer.ContainerStateExited {
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: nit: why not just check for `ContainerStateRunning`?

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 3]
```diff
@@ -120,6 +124,32 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
...
+						glog.V(5).Infof(
+							"Pod %q has been removed from pod manager. However, it still has one or more containers (%q) in the non-exited state. Therefore it will not be removed from volume manager.",
+							volumeToMount.PodName,
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: A question: what does `PodName` contain? Just `api.Pod.Name` or does it include namespace?

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 4]
```diff
@@ -120,6 +124,32 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
...
+							containerStatus.ID)
+						continue
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Uh..... is this a `continue` for the outer `for` loop or the inner `for` loop? If it's only for the inner `for` loop, the code will continue to check the next status. I think this is incorrect.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go (hunk 3 above)
Comment (saad-ali) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Just the name. I'll add the namespace for logging.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go (hunk 2 above)
Comment (saad-ali) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Wasn't sure if it was ok for us to assume state unknown was safe to assume not running. But sure, will make that change.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Also, docker returns errors sometimes, especially when it's under load. It's better to default to *not* unmount here.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 5]
```diff
@@ -120,11 +124,56 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
 	for _, volumeToMount := range dswp.desiredStateOfWorld.GetVolumesToMount() {
 		if _, podExists :=
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: nit: reduce indent by `continue` eariler 
```go
if _, podExists := dswp.podManager.GetPodByUID(volumeToMount.Pod.UID); podExists {
   continue
}
```

Comment (saad-ali) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Done.

File: pkg/kubelet/kubelet.go [hunk 6]
```diff
@@ -504,7 +504,8 @@ func NewMainKubelet(
 		hostname,
 		klet.podManager,
 		klet.kubeClient,
-		klet.volumePluginMgr)
+		klet.volumePluginMgr,
+		klet.containerRuntime)
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: FWIW, I still think it's better to pass the kl.podCache here because otherwise, the code would be calling `docker ps` 10 times per second while waiting for kubelet to stop the container.

**Comment by yujuhong** [comment]
> The test still failed after about an hour, going to add in my additional logging to see what's happening.

According to the log you sent me, the kubelet version of the failed run is
```
I0628 13:50:32.740059    3494 server.go:726] Started kubelet v1.3.0-alpha.4.2254+bc07f7ffa0f2d2
```
This is the same commit which suffers the `continue` bug (https://github.com/kubernetes/kubernetes/pull/28160/commits/bc07f7ffa0f2d2e37bd43b8e127a78a06577de99#r68817766)
I'd say that we shouldn't be overly concerned about the failed run.

**Comment by saad-ali** [comment]
> I'd say that we shouldn't be overly concerned about the failed run.

Yep, you're right, I must've kicked off another run after I made that change.

**Comment by saad-ali** [comment]
New run has been running back to back without failure for over 1.5 hours. No ext4 errors on first machine (the signature of this bug). We see some JBD2 errors on the second machine that we're looking investigating. But this PR appears to eliminate the original error.

I'm going to go ahead and switch to the pod cache now, as recommended.

File: pkg/kubelet/kubelet.go (hunk 6 above)
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: Retract my comment since this would slightly increase the window for race condition to happen.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 7]
```diff
@@ -102,6 +110,15 @@ func (dswp *desiredStateOfWorldPopulator) populatorLoopFunc() func() {
 	return func() {
 		dswp.findAndAddNewPods()
 
+		if time.Since(dswp.timeOfLastGetPodStatus) < dswp.getPodStatusRetryDuration {
+			glog.Infof( // TODO REDUCE VERBOSITY
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: Add a comment to call it out that we do this on purpose to not hitting the runtime frequently.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 8]
```diff
@@ -119,17 +136,67 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddNewPods() {
...
+		// containerRuntime interface to verify all containers in the pod
+		// have been terminated.
+		podStatus, podStatusErr := dswp.kubeContainerRuntime.GetPodStatus(
+			volumeToMount.Pod.UID,
+			volumeToMount.Pod.Name,
+			volumeToMount.Pod.Namespace)
+		if podStatusErr != nil {
+			glog.Errorf(
+				"yosaad: Pod %q/%q (%q) has been removed from pod manager. However, kubeContainerRuntime.GetPodStatus returned error %v. Therefore it will not be removed from volume manager.",
+				volumeToMount.Pod.Namespace,
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: nit: If you store the entire `api.Pod` object in `volumeToMount`, you can use `format.Pod(pod)` from `pkg/kubelet/util/format` to print a in a format consistent with the rest of the kubelet code.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 9]
```diff
@@ -119,17 +136,67 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddNewPods() {
...
+				volumeToMount.Pod.Name,
+				volumeToMount.Pod.UID,
+				podStatusErr)
+			continue
+		} else {
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: nit: remove the `else {` block now that you skip the rest of the iteration in line 160.

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 10]
```diff
@@ -119,17 +136,67 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddNewPods() {
...
-				volumeToMount.VolumeSpec.Name(),
-				volumeToMount.PodName)
-
-			dswp.desiredStateOfWorld.DeletePodFromVolume(
-				volumeToMount.PodName, volumeToMount.VolumeName)
-			dswp.deleteProcessedPod(volumeToMount.PodName)
+			dswp.podManager.GetPodByUID(volumeToMount.Pod.UID); podExists {
+			continue
 		}
+
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: This will still cause quite a lot of churn when deleting a large number of pods in a short time. The older code had less performance impact because it ran `docker ps` once and looked at all the volumes based on the output. 

E.g., https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/kubelet/kubelet.go#L2168

**Comment by saad-ali** [comment]
@k8s-bot k8s-bot test this issue: #25393

**Comment by saad-ali** [comment]
@yujuhong PTAL

File: pkg/kubelet/volume/populator/desired_state_of_world_populator.go [hunk 11]
```diff
@@ -117,19 +139,75 @@ func (dswp *desiredStateOfWorldPopulator) findAndAddNewPods() {
...
+			}
+
+			runningPodsFetched = true
+			dswp.timeOfLastGetPodStatus = time.Now()
 		}
+
+		runningContainers := []kubecontainer.ContainerID{}
+		for _, runningPod := range runningPods {
+			if runningPod.ID == volumeToMount.Pod.UID {
+				for _, container := range runningPod.Containers {
```
Comment (yujuhong) [inline pkg/kubelet/volume/populator/desired_state_of_world_populator.go]: just check the length of the `runningPod.Containers` since `GetPods(false)` should only return running containers.

**Comment by yujuhong** [comment]
Looks good overall with one suggestion to simplify the code and nits from the previous commit (e.g., https://github.com/kubernetes/kubernetes/pull/28160#discussion_r68871221)

**Comment by saad-ali** [comment]
nits addressed. commits squashed. debug logging removed. PTAL

**Comment by thockin** [comment]
LGTM to get miles on it.  @yujuhong can TAL, please

**Comment by yujuhong** [comment]
LGTM.
