### PR TITLE
Fix iSCSI storage plugin cleanup in block volumes

### LINKED ISSUE #79973: iSCSI storage plugin not cleaning up dir
**What happened**:

When creating a block volume, the iSCSI storage plugin stores volume-related data in different directories:

```console
# tree /var/lib/kubelet/plugins/kubernetes.io/iscsi
/var/lib/kubelet/plugins/kubernetes.io/iscsi
`-- volumeDevices
    |-- iface-127.0.0.1:3260:pv1
    |   `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
    |       `-- iscsi.json
    `-- iface-default
        `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
            `-- 9c205fba-730a-430e-8b48-5f53dba9a7db -> /dev/sdc

5 directories, 2 files
```
As a result, some data is not cleaned up once the volume is detached:

```console
# tree /var/lib/kubelet/plugins/kubernetes.io/iscsi
/var/lib/kubelet/plugins/kubernetes.io/iscsi
`-- volumeDevices
    |-- iface-127.0.0.1:3260:pv1
    |   `-- 127.0.0.1:3260-iqn.2003-01.io.k8s:e2e.volume-1-lun-2
    |       `-- iscsi.json
    `-- iface-default

4 directories, 1 file
```
**How to reproduce it (as minimally and precisely as possible)**:

These are the objects I used to reproduce this issue:

claim.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  storageClassName: ""
  resources:
    requests:
      storage: 50Mi
```

pod-block.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-block
  labels:
    name: test
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  tolerations:
    - key: node.kubernetes.io/network-unavailable
  containers:
    - image: gcr.io/google_containers/busybox
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do date; sleep 1; done"
      name: busybox
      volumeDevices:
        - name: vol
          devicePath: /mnt/test
  volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: claim1
```

pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv1
spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Mi
    iscsi:
      fsType: ext4
      iqn: iqn.2003-01.io.k8s:e2e.volume-1
      iscsiInterface: default
      lun: 2
      targetPortal: 127.0.0.1:3260
      initiatorName: "iqn.1994-05.com.redhat:2a3ac65b173"
    persistentVolumeReclaimPolicy: Delete
    volumeMode: Block
```

/sig storage
CC @jsafrane, @msau42, @bswartz, @j-griffith

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

During the attach of a block volume, the function [makeVDPDNameInternal](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L195) is called twice in order to return a string like the one below. Note that the iface name is part of the path:

`/var/lib/kubelet/plugins/kubernetes.io/iscsi/volumeDevices/iface_name/portal-some_iqn-lun-lun_id`

On the first call, the iSCSI iface used is typically the default one. Later on, **if there's an initiator set in the PV**, we create [a new iface and overwrite the default one](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L309-L320). Then, the next call to `makeVDPDNameInternal` will return a different path because the iface is different.

This patch sets the correct iface during the iSCSI disk initialization, so we always get the correct path.

**Which issue(s) this PR fixes**:

Fixes #79973

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig storage
/assign @bswartz @jsafrane @j-griffith

### CODE REVIEW

File: pkg/volume/iscsi/iscsi.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ import (
 	"strconv"
 	"strings"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (j-griffith) [inline pkg/volume/iscsi/iscsi.go]: Just curious, why the import v1 as v1 here?

**Review by j-griffith — COMMENTED** [review]
I haven't tried running it, but code wise it looks good.  I'll get it loaded up and verify asap.

File: pkg/volume/iscsi/iscsi.go (hunk 1 above)
Comment (bertinatto) [reply pkg/volume/iscsi/iscsi.go]: This was added by goimports. They say it's intended: https://github.com/golang/go/issues/30051

**Comment by bertinatto** [comment]
Thanks, @j-griffith! This is specially important for the new reference counter that I'm working on.

/priority important-soon

File: pkg/volume/iscsi/iscsi.go [hunk 2]
```diff
@@ -551,6 +551,17 @@ func createISCSIDisk(spec *volume.Spec, podUID types.UID, plugin *iscsiPlugin, m
 		return nil, err
 	}
 
+	if initiatorName != "" && len(bkportal) > 0 {
+		// Create a new iface and copy parameters from the pre-configured iface
+		newIface := bkportal[0] + ":" + spec.Name()
+		exec := plugin.host.GetExec(plugin.GetPluginName())
+		if err := cloneIface(exec, initiatorName, iface, newIface); err != nil {
```
Comment (jsafrane) [inline pkg/volume/iscsi/iscsi.go]: Is it possible to call `cloneIface` in `AttachDisk` where it originally was and only leave the old/new interface name calculation here? `createISCSIDisk` is called by `volumeSpecToMounter` and I think that does not need to clone the interface at all.

Comment (j-griffith) [reply pkg/volume/iscsi/iscsi.go]: I thought he was moving that to make the ref counter work, but maybe I am wrong about that.

Comment (bertinatto) [reply pkg/volume/iscsi/iscsi.go]: That's possible, but if we move the `cloneIface` back to `AttachDisk`, we'd have to check if the initiator is set in two different places (both here and in `AttachDisk`). It's not a big deal, but it seemed better to keep this logic together.

I don't have strong feelings about it, so I can move it back if you prefer.

Comment (jsafrane) [reply pkg/volume/iscsi/iscsi.go]: > That's possible, but if we move the cloneIface back to AttachDisk, we'd have to check if the initiator is set in two different places (both here and in AttachDisk)

I think it's OK.

I'm afraid that cloning interfaces in functions like `reconstructVolume`, `GenerateExpandInUseVolumeFunc` and `GetGlobalMapPath` won't do any good. It should be really used only when kubelet attaches & mounts a volume.

Comment (bertinatto) [reply pkg/volume/iscsi/iscsi.go]: I see; I had to add a new field to `iscsiDisk` to store the "old" iface (we need it to copy the parameters to the new one during attach).

The code may have got a bit tangled, but it was the way I found to clone ifaces only during attach.

**Review by j-griffith — APPROVED** [review]
