### PR TITLE
remove LegacyNodeRoleBehavior and mv ServiceNodeExclusion to GA

### LINKED ISSUE #97542: kubelet log continuously prints  "Initializing eviction metric for zone"
**What happened**:
The node name is `daocloud-master`.

```
I1228 07:38:27.124528       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
I1228 07:38:32.124936       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
I1228 07:38:37.126648       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
I1228 07:38:42.127029       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
I1228 07:38:47.127361       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
I1228 07:38:52.127598       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: paco::zone2
```

**What you expected to happen**:

A normal node log is like below
```
I1228 06:14:14.099144       1 node_lifecycle_controller.go:1429] Initializing eviction metric for zone: region::zone
I1228 06:14:14.099284       1 node_lifecycle_controller.go:1245] Controller detected that zone region::zone is now in state Normal.
```

**How to reproduce it (as minimally and precisely as possible)**:
run kube in a node whose hostname ends with "master"

/sig node
/sig network

/area kubelet

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug
/kind cleanup
/sig network
/area kubelet

**What this PR does / why we need it**:
According to KEP from https://github.com/kubernetes/enhancements/blob/54b409decd8d2e7f8a631fb845db58c810b4254c/keps/sig-architecture/2019-07-16-node-role-label-use.md
Master link:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1143-node-role-labels

**Which issue(s) this PR fixes**:
Fixes #97542 

Part of #94495
@thockin @smarterclayton @rikatz

**Special notes for your reviewer**:

During investigating the 97542 in my kubelet log, I read the KEP and #94495 comments. It needs to be done in 1.21.

The part related to #97542  is the function of node checking. 
https://github.com/kubernetes/kubernetes/pull/97543/files#diff-62d886bf35c4945f56ff8cfd3d60e9f47a0deb8f6b3d09d89f48aacf3ba7b70eL972-L977

**Does this PR introduce a user-facing change?**:

```release-note
[ACTION REQUIRED] `ServiceNodeExclusion`, `NodeDisruptionExclusion` and `LegacyNodeRoleBehavior`(locked to false) features have been promoted to GA. 
To prevent control plane nodes from being added to load balancers automatically, upgrade users need to add "node.kubernetes.io/exclude-from-external-load-balancers" label to control plane nodes.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1143-node-role-labels
```

### CODE REVIEW

File: pkg/features/kube_features.go [hunk 1]
```diff
@@ -753,8 +748,8 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 	CPUManager:                     {Default: true, PreRelease: featuregate.Beta},
 	CPUCFSQuotaPeriod:              {Default: false, PreRelease: featuregate.Alpha},
 	TopologyManager:                {Default: true, PreRelease: featuregate.Beta},
-	ServiceNodeExclusion:           {Default: true, PreRelease: featuregate.Beta},
-	NodeDisruptionExclusion:        {Default: true, PreRelease: featuregate.Beta},
+	ServiceNodeExclusion:           {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.21
+	NodeDisruptionExclusion:        {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.21
```
Comment (rikatz) [inline pkg/features/kube_features.go:752]: You mean remove in v1.22? :)

In v1.21 we're moving this to GA and locking to default, in v1.22 we can remove completely

File: pkg/features/kube_features.go [hunk 2]
```diff
@@ -850,6 +845,5 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 
 	// features that enable backwards compatibility but are scheduled to be removed
 	// ...
-	HPAScaleToZero:         {Default: false, PreRelease: featuregate.Alpha},
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
+	HPAScaleToZero: {Default: false, PreRelease: featuregate.Alpha},
```
Comment (rikatz) [inline pkg/features/kube_features.go:848]: Wait, this feature is not related to the PR. Why is this being moved back to Alpha?

File: pkg/features/kube_features.go [hunk 3]
```diff
@@ -850,6 +845,5 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 
 	// features that enable backwards compatibility but are scheduled to be removed
 	// ...
-	HPAScaleToZero:         {Default: false, PreRelease: featuregate.Alpha},
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
```
Comment (rikatz) [inline pkg/features/kube_features.go:854]: Per feature lifecycle, shouldn't this be locked to default before removing it?

Comment (rikatz) [reply pkg/features/kube_features.go:854]: Also, per the KEP this should be defaulted to FALSE: 

Release 4 (1.20):

"Default the legacy gate LegacyNodeRoleBehavior to off. Admins whose deployments still use the old labels may set LegacyNodeRoleBehavior=true during 1.19 to get the legacy behavior."

File: staging/src/k8s.io/controller-manager/pkg/features/kube_features.go [hunk 4]
```diff
@@ -58,7 +46,6 @@ func SetupCurrentKubernetesSpecificFeatureGates(featuregates featuregate.Mutable
 // cloudPublicFeatureGates consists of cloud-specific feature keys.
 // To add a new feature, define a key for it at k8s.io/api/pkg/features and add it here.
 var cloudPublicFeatureGates = map[featuregate.Feature]featuregate.FeatureSpec{
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
```
Comment (rikatz) [inline staging/src/k8s.io/controller-manager/pkg/features/kube_features.go:61]: Per KEP, should be defaulted to false and locked.

File: staging/src/k8s.io/controller-manager/pkg/features/kube_features.go [hunk 5]
```diff
@@ -21,23 +21,11 @@ import (
 )
 
 const (
-	// Every feature gate should add method here following this template:
```
Comment (rikatz) [inline staging/src/k8s.io/controller-manager/pkg/features/kube_features.go:24]: This should not be excluded, as it's an example for people willing to change this file

File: pkg/controller/nodelifecycle/node_lifecycle_controller_test.go [hunk 6]
```diff
@@ -1200,7 +1199,7 @@ func TestMonitorNodeHealthEvictPodsWithDisruption(t *testing.T) {
 				testutil.CreateZoneID("region1", "zone1"): stateFullDisruption,
 			},
 			expectedEvictPods: false,
-			description:       "NetworkDisruption: eviction should stop, only -master Node is healthy",
+			description:       "NetworkDisruption: eviction should stop, only Node with lable node.kubernetes.io/exclude-disruption is healthy",
```
Comment (rikatz) [inline pkg/controller/nodelifecycle/node_lifecycle_controller_test.go:1202]: typo in label here

File: pkg/features/kube_features.go [hunk 7]
```diff
@@ -137,23 +137,18 @@ const (
 	// Enable pods to set sysctls on a pod
 	Sysctls featuregate.Feature = "Sysctls"
 
-	// owner @smarterclayton
-	// alpha: v1.16
-	// beta:  v1.19
-	//
-	// Enable legacy behavior to vary cluster functionality on the node-role.kubernetes.io labels. On by default (legacy), will be turned off in 1.18.
-	LegacyNodeRoleBehavior featuregate.Feature = "LegacyNodeRoleBehavior"
```
Comment (rikatz) [inline pkg/features/kube_features.go:145]: This should not be removed yet, as it's not GA'd and locked

**Comment by rikatz** [comment]
@pacoxu thanks for raising this.

Overall it looks good to me, but as a previous discussion we've had with sig-apimachinery and sig-arch:

1) Not GA'd feature gates should first be moved to GA and locked to the default (true for ServiceNodeExclusion and NodeDisruptionExclusion, false for LegacyNodeRoleBehavior per KEP) and then removed from kube_features.go in v1.22

2) I will do another pass into the code to check also if some FG or some reference is removed, although it seems the tests just passed fine :)

Can you please correct the FG versioning? Thanks!!

File: pkg/features/kube_features.go (hunk 1 above)
Comment (pacoxu) [reply pkg/features/kube_features.go]: fixed.

File: pkg/features/kube_features.go [hunk 8]
```diff
@@ -142,18 +142,21 @@ const (
 	// beta:  v1.19
 	//
```
Comment (rikatz) [inline pkg/features/kube_features.go:143]: don't forget here to put the version we're doing this into GA :)

File: pkg/features/kube_features.go [hunk 9]
```diff
@@ -851,5 +854,5 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 	// features that enable backwards compatibility but are scheduled to be removed
 	// ...
 	HPAScaleToZero:         {Default: false, PreRelease: featuregate.Alpha},
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
+	LegacyNodeRoleBehavior: {Default: false, PreRelease: featuregate.Beta, LockToDefault: true},
```
Comment (rikatz) [inline pkg/features/kube_features.go:857]: PreRelease: featuregate.GA

File: staging/src/k8s.io/controller-manager/pkg/features/kube_features.go [hunk 10]
```diff
@@ -58,7 +60,7 @@ func SetupCurrentKubernetesSpecificFeatureGates(featuregates featuregate.Mutable
 // cloudPublicFeatureGates consists of cloud-specific feature keys.
 // To add a new feature, define a key for it at k8s.io/api/pkg/features and add it here.
 var cloudPublicFeatureGates = map[featuregate.Feature]featuregate.FeatureSpec{
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
-	ServiceNodeExclusion:   {Default: true, PreRelease: featuregate.Beta},
+	LegacyNodeRoleBehavior: {Default: false, PreRelease: featuregate.Beta, LockToDefault: true},
```
Comment (rikatz) [inline staging/src/k8s.io/controller-manager/pkg/features/kube_features.go:63]: featuregate.GA

**Comment by rikatz** [comment]
@pacoxu left two more reviews: one to insert the proper comment of which is the version we're marking LegacyNodeRoleBehavior to GA and other to change LegacyNodeRoleBehavior to featuregate.GA (you left this as Beta).

Thanks!

**Comment by rikatz** [comment]
More comments: in https://github.com/kubernetes/kubernetes/blob/v1.20.1/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L69 I guess we can remove the reference to ServiceNodeExclusion gate, as we're removing it.

**Comment by rikatz** [comment]
/hold

One more thing: I don't think that deprecating and locking a feature gate is not worth of a Release Note, so can you please change the description in the PR?

Thank you!!!

**Comment by pacoxu** [comment]
Thanks a lot @rikatz  fixed per your comments and add a release note.

File: staging/src/k8s.io/controller-manager/pkg/features/kube_features.go [hunk 11]
```diff
@@ -21,6 +21,7 @@ import (
 )
 
 const (
+
```
Comment (rikatz) [inline staging/src/k8s.io/controller-manager/pkg/features/kube_features.go:24]: nit: leading line, but I guess it's ok for now

**Comment by rikatz** [comment]
/hold cancel
/lgtm

@pacoxu Thanks!

**Comment by rikatz** [comment]
/triage accepted
/priority backlog 
/assign @thockin @smarterclayton 

For the approvers, this is the promotion of some features scheduled for v1.21, related to #94495

Thanks!

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go [hunk 12]
```diff
@@ -57,27 +57,15 @@ const (
 	maxRetryDelay = 300 * time.Second
 
 	// labelNodeRoleMaster specifies that a node is a master. The use of this label within the
-	// controller is deprecated and only considered when the LegacyNodeRoleBehavior feature gate
-	// is on.
+	// controller is deprecated.
 	labelNodeRoleMaster = "node-role.kubernetes.io/master"
```
Comment (thockin) [inline staging/src/k8s.io/cloud-provider/controllers/service/controller.go:61]: Can we get rid of this const now?

**Review by thockin — COMMENTED** [review]
LGTM overall

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go (hunk 12 above)
Comment (pacoxu) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go]: @thockin  remove it per your comments.

**Comment by pacoxu** [comment]
/test pull-kubernetes-e2e-kind-ipv6
--

File: pkg/features/kube_features.go [hunk 13]
```diff
@@ -851,5 +855,5 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 	// features that enable backwards compatibility but are scheduled to be removed
 	// ...
 	HPAScaleToZero:         {Default: false, PreRelease: featuregate.Alpha},
-	LegacyNodeRoleBehavior: {Default: true, PreRelease: featuregate.Beta},
+	LegacyNodeRoleBehavior: {Default: false, PreRelease: featuregate.GA, LockToDefault: true},
```
Comment (rikatz) [inline pkg/features/kube_features.go:858]: nit, but we can go without it :) put a comment about removing in v1.22, but otherwise it stills lgtm :)

**Comment by rikatz** [comment]
no big changes from my last lgtm, other than Tim's recommendation of removing the unused const, so 
/lgtm

Thanks :)

File: pkg/features/kube_features.go (hunk 13 above)
Comment (pacoxu) [reply pkg/features/kube_features.go]: fixed

**Comment by pacoxu** [comment]
@rikatz  Done for the comment.

**Comment by rikatz** [comment]
Great, thank you!

/lgtm

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go [hunk 14]
```diff
@@ -56,28 +56,12 @@ const (
...
-	labelNodeRoleMaster = "node-role.kubernetes.io/master"
-
 	// labelNodeRoleExcludeBalancer specifies that the node should not be considered as a target
 	// for external load-balancers which use nodes as a second hop (e.g. many cloud LBs which only
 	// understand nodes). For services that use externalTrafficPolicy=Local, this may mean that
 	// any backends on excluded nodes are not reachable by those external load-balancers.
-	// Implementations of this exclusion may vary based on provider. This label is honored starting
-	// in 1.16 when the ServiceNodeExclusion gate is on.
+	// Implementations of this exclusion may vary based on provider.
 	labelNodeRoleExcludeBalancer = "node.kubernetes.io/exclude-from-external-load-balancers"
```
Comment (thockin) [inline staging/src/k8s.io/cloud-provider/controllers/service/controller.go:64]: followup nit - we should rename this to "labelNodeExcludeBalancers" or something  -  "role" has no place any more :)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go (hunk 14 above)
Comment (rikatz) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:64]: want me to open a new issue and mark as a good first issue? I'm on it :D

Comment (rikatz) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:64]: https://github.com/kubernetes/kubernetes/issues/97734 :)

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go [hunk 15]
```diff
@@ -635,17 +614,8 @@ func nodeSlicesEqualForLB(x, y []*v1.Node) bool {
...
-			// Recognize nodes labeled as master, and filter them also, as we were doing previously.
-			if _, hasMasterRoleLabel := node.Labels[labelNodeRoleMaster]; hasMasterRoleLabel {
-				return false
-			}
-		}
-		if s.serviceNodeExclusionFeatureEnabled {
-			if _, hasExcludeBalancerLabel := node.Labels[labelNodeRoleExcludeBalancer]; hasExcludeBalancerLabel {
-				return false
-			}
+		if _, hasExcludeBalancerLabel := node.Labels[labelNodeRoleExcludeBalancer]; hasExcludeBalancerLabel {
```
Comment (andrewsykim) [inline staging/src/k8s.io/cloud-provider/controllers/service/controller.go:617]: I imagine this change is going to break some users since control plane nodes will now be added to load balancers automatically when previously they were not. Can we add an `ACTION REQUIRED` to the release notes and call out that users need to add the `labelNodeExcludeBalancer` label to control plane nodes if they want to preserve this behaviour?

**Comment by neolit123** [comment]
the KEP link is now broken because we moved some files in k/e.
also it should be under:
> Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

**Comment by neolit123** [comment]
does sig-network recommend that kubeadm in 1.21 stats applying the `node.kubernetes.io/exclude-from-external-load-balancers` label on its CP nodes?

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go (hunk 15 above)
Comment (pacoxu) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:617]: Need I edit the release note to 
```
`ServiceNodeExclusion`, `NodeDisruptionExclusion` and `LegacyNodeRoleBehavior`(locked to false) features have been promoted to GA. 
To prevent control plane nodes being added to load balancers automatically, upgrade users need to add "node.kubernetes.io/exclude-from-external-load-balancers"  label to control plane nodes.
```

**Comment by pacoxu** [comment]
KEP link  updated @neolit123

File: staging/src/k8s.io/cloud-provider/controllers/service/controller.go (hunk 15 above)
Comment (andrewsykim) [reply staging/src/k8s.io/cloud-provider/controllers/service/controller.go:617]: Yes, that would be better than the current release notes

**Comment by wilsonehusin** [comment]
@pacoxu hello from 1.21 release notes team! The release notes annotated in bold caught my attention:

> To prevent control plane nodes being added to load balancers automatically, **upgrade users need to** add "node.kubernetes.io/exclude-from-external-load-balancers"  label to control plane nodes.

Can you clarify that this requires users / operators to take action / warrants a spot in ["Urgent upgrade notes"](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#urgent-upgrade-notes)? If so, please prepend the release note with `[ACTION REQUIRED]`, otherwise confirm that users / operators do not need to take action when upgrading from 1.20 to 1.21.

Thanks!

**Comment by andrewsykim** [comment]
This definitely warrants an `ACTION REQUIRED` item in the release notes IMO.

**Comment by wilsonehusin** [comment]
> This definitely warrants an `ACTION REQUIRED` item in the release notes IMO.

Thanks @andrewsykim! I have [marked this to be in `ACTION REQUIRED` section](https://github.com/kubernetes/sig-release/pull/1434/files#diff-4a6e752cc399e6c8f21a8706f137dd6d72d2efca17a591389582ef04f5f654fa).

**Comment by pacoxu** [comment]
@wilsonehusin  thanks.
I edited like
image

Am I right?

**Comment by wilsonehusin** [comment]
yup that works, thanks @pacoxu
