### PR TITLE
Ignore unschedulable pods

### LINKED ISSUE #79158: Unscheduled Pods cause HPA to get stuck
**What happened**:

When the HPA scales up beyond the capacity of the cluster, many unscheduled pods are created.  When load is removed, the usage ratio drops and the HPA tries to scale down.  The unscheduled pods do not produce metrics, so the HPA fills in the 100% usage and re-evaluates the usage ratio.  Because of the many fake 100% metrics, the new usage ratio is above the target value and the direction of scale is reversed.  In this case, the HPA decides not to make any change to the current scale.

https://github.com/kubernetes/kubernetes/blob/9162d932cff0f57580640ba049574f72bfd96d4b/pkg/controller/podautoscaler/replica_calculator.go#L104-L110

https://github.com/kubernetes/kubernetes/blob/9162d932cff0f57580640ba049574f72bfd96d4b/pkg/controller/podautoscaler/replica_calculator.go#L131-L135

**What you expected to happen**:

I would expect the HPA to not get stuck when load is removed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/ and put it under load in a cluster without cluster autoscaling.
2. Edit the Deployment to increase the CPU request beyond the capability of the cluster (e.g. 500m).  This should produce many Pending pods.
3. Remove load.  The Pending pods will keep the HPA scaled indefinitely.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}                                                                                                                                                                                     
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.3", GitCommit:"01866bfa8b9692c6504622311d5b5015f16bfd18", GitTreeState:"clean", BuildDate:"2019-06-06T21:30:53Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}                                                                                                                                                                            

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by josephburnett**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When the HPA decides which pods and metric values to take into account when scaling, it divides the pods into three disjoint subsets: 1) ready 2) missing metrics and 3) ignored.

https://github.com/kubernetes/kubernetes/blob/003c4e51555f6e9fce8b62ba6916d5b70b2f3010/pkg/controller/podautoscaler/replica_calculator.go#L361-L363

First the HPA selects pods which are missing metrics.  Then it selects pods should be ignored because they are not ready yet, or are still consuming CPU during initialization.  All the remaining pods go into the ready set.

After the HPA has decided what direction it wants to scale based on the ready pods, it considers what might have happened if it had the missing metrics.  It makes a conservative guess about what the missing metrics might have been, 0% if it wants to scale up--100% if it wants to scale down.

https://github.com/kubernetes/kubernetes/blob/003c4e51555f6e9fce8b62ba6916d5b70b2f3010/pkg/controller/podautoscaler/replica_calculator.go#L104-L116

This is a good thing when scaling up, because newly added pods will likely help reduce the usage ratio, even though their metrics are missing at the moment.  The HPA should wait to see the results of its previous scale decision before it makes another one.

However when scaling down, it means that many missing metrics can pin the HPA at high scale, even when load is completely removed.  In particular, when there are many unschedulable pods due to insufficient cluster capacity, the many missing metrics (assumed to be 100%) can cause the HPA to avoid scaling down indefinitely.

This change adding unschedulable pods to the ignored set **first** before selecting pods missing metrics.  Unschedulable pods are always ignored when calculating scale.

**Which issue(s) this PR fixes**:

Fixes #79158

**Special notes for your reviewer**:

This can be reproduced by using the [Kubernetes Horizontal Pod Autoscaler Walkthrough](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/) and updating the Deployment while under load to a higher CPU request (e.g. 1700m).

image

I have tested this change (with #79035 patched) by deploying Kubernetes to GCE and running through the repro steps.  After removing load, the HPA scales down as expected, even with many unschedulable pending pods.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 1]
```diff
@@ -365,6 +365,12 @@ func groupPods(pods []*v1.Pod, metrics metricsclient.PodMetricsInfo, resource v1
 		if pod.DeletionTimestamp != nil || pod.Status.Phase == v1.PodFailed {
 			continue
 		}
+		// Unschedulable pods are always ignored.
+		_, scheduled := podutil.GetPodCondition(&pod.Status, v1.PodScheduled)
+		if scheduled != nil && scheduled.Status == v1.ConditionFalse && scheduled.Reason == v1.PodReasonUnschedulable {
```
Comment (krzysztof-jastrzebski) [inline pkg/controller/podautoscaler/replica_calculator.go]: What if there is no scheduled condition? Isn't pod unscheduled in that case?
Shouldn't we also ignore pods that were scheduled but are not running yet?
Maybe we should use pod.Status.Phase instead?

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 2]
```diff
@@ -365,6 +365,12 @@ func groupPods(pods []*v1.Pod, metrics metricsclient.PodMetricsInfo, resource v1
 		if pod.DeletionTimestamp != nil || pod.Status.Phase == v1.PodFailed {
 			continue
 		}
+		// Unschedulable pods are always ignored.
+		_, scheduled := podutil.GetPodCondition(&pod.Status, v1.PodScheduled)
```
Comment (krzysztof-jastrzebski) [inline pkg/controller/podautoscaler/replica_calculator.go]: What if there is no scheduled condition? Isn't pod unscheduled in that case?
Shouldn't we also ignore pods that were scheduled but are not running yet?
Maybe we should use pod.Status.Phase instead?

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: > Maybe we should use pod.Status.Phase instead?

Yes, I think you're right.

It's very important that, on scale up, pods that are not reporting metrics or are not ready are considered as using 0%.  This ensures that the HPA doesn't runaway because pods are slow to start or the metrics pipeline is slow (it is).  We already have this case which will include ignored pods as 0% in the metrics: https://github.com/kubernetes/kubernetes/blob/efdc3fb0a2938b72e4de02f147ab3329895ff018/pkg/controller/podautoscaler/replica_calculator.go#L118-L123

Since we already consider all ignored pods as 0% in addition to the missing metric pods, I think there is no harm in including **all** pending pods in the ignored set.

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: Done.

Comment (krzysztof-jastrzebski) [reply pkg/controller/podautoscaler/replica_calculator.go]: I meant that I'm not sure if pod after creation has condition PodScheduled. Even if it has the condition then scheduled.Reason won't be equal to v1.PodReasonUnschedulable. If there is a lot of pods to be scheduled then it can take some time before condition is added by scheduler. Maybe it would be better to use pod.Spec.NodeName != nil instead. All scheduled pods have this field set.
