### PR TITLE
Service: Fix semantics for Update wrt allocations

### LINKED ISSUE #91459: Replace does not work for services
**What happened**:

[This issue on kubectl](https://github.com/kubernetes/kubectl/issues/798#issue-547658418) was closed as not a problem with kubectl, but with the server

**What you expected to happen**:

'kubectl replace' with no change on a service should work.

**How to reproduce it (as minimally and precisely as possible)**:

reproduction included in this issue https://github.com/kubernetes/kubectl/issues/798#issue-547658418

**Anything else we need to know?**:

Seems to me like this comment sums up the options https://github.com/kubernetes/kubectl/issues/798#issuecomment-577321234

I got here from this issue https://github.com/helm/helm/issues/6378#issuecomment-572716384

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by thockin**
It is not uncommon for users to Create a Service and not specify things
like ClusterIP and NodePort, which we then allocate for them.  They same
that YAML somewhere and later use it again in an Update, but then it
fails.

That's because we detected them trying to set a ClusterIP from a value
to "", which is not allowed.  If it was just NodePort, they would
actually succeed and reallocate a new port.

After this change, we try to "patch" updates where the user did not
specify those values from the old object.

/kind bug
/kind api-change

Fixes #91459 

Builds on #103467

```release-note
When using `kubectl replace` (or the equivalent API call) on a Service, the caller no longer needs to do a read-modify-write cycle to fetch the allocated values for `.spec.clusterIP` and `.spec.ports[].nodePort`.  Instead the API server will automatically carry these forward from the original object when the new object does not specify them.  
```

### CODE REVIEW

File: pkg/registry/core/service/strategy.go [hunk 1]
```diff
@@ -302,6 +303,43 @@ func (serviceStatusStrategy) WarningsOnUpdate(ctx context.Context, obj, old runt
...
+		if newSvc.Spec.ClusterIP == "" {
+			newSvc.Spec.ClusterIP = oldSvc.Spec.ClusterIP
+		}
+		if len(newSvc.Spec.ClusterIPs) == 0 {
+			newSvc.Spec.ClusterIPs = oldSvc.Spec.ClusterIPs
+		}
+	}
+
+	if needsNodePort(oldSvc) && needsNodePort(newSvc) {
+		// Map NodePorts by name.  The user may have changed other properties
```
Comment (aojea) [inline pkg/registry/core/service/strategy.go:321]: name is optional if there is only one port, isn't it?

File: pkg/registry/core/service/strategy.go [hunk 2]
```diff
@@ -302,6 +303,43 @@ func (serviceStatusStrategy) WarningsOnUpdate(ctx context.Context, obj, old runt
 	return nil
 }
 
+// patchAllocatedValues allows clients to avoid a read-modify-write cycle while
+// preserving values that we allocated on their behalf.  For example, they
+// might create a Service without specifying the ClusterIP, in which case we
+// allocate one.  If they resubmit that same YAML, we want it to succeed.
+func patchAllocatedValues(newSvc, oldSvc *api.Service) {
+	if needsClusterIP(oldSvc) && needsClusterIP(newSvc) {
```
Comment (aojea) [inline pkg/registry/core/service/strategy.go:311]: what about adding like in https://github.com/kubernetes/kubernetes/pull/103532/files#diff-2dd9a1ef6872092e519941c8a4870f4c2a71eda096b660510b02afe9b3d19fefR432-R436
```go
	// For now we are only wiping on updates.  This minimizes potential
	// confusion since many of the cases we are handling here are pretty niche.
	if oldSvc == nil {
		return
	}
```

File: pkg/registry/core/service/strategy.go (hunk 1 above)
Comment (aojea) [reply pkg/registry/core/service/strategy.go:321]: if that is the case we should add a check for services with a single srevice port without name

File: pkg/registry/core/service/storage/rest_test.go [hunk 3]
```diff
@@ -621,6 +621,55 @@ func TestServiceRegistryUpdate(t *testing.T) {
...
+		t.Fatalf("expected ClusterIPs to be set")
+	}
+	if createdSvc.Spec.Ports[0].NodePort == 0 {
+		t.Fatalf("expected NodePort to be set")
+	}
+	if createdSvc.Spec.HealthCheckNodePort == 0 {
+		t.Fatalf("expected HealthCheckNodePort to be set")
+	}
+
+	// Update the selector - trivial.
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest_test.go:649]: should we worry about mutating services types or some of these less common services nuances?

File: pkg/api/service/testing/make.go [hunk 4]
```diff
@@ -160,3 +160,17 @@ func SetInternalTrafficPolicy(policy api.ServiceInternalTrafficPolicyType) Tweak
...
+		svc.Spec.ExternalTrafficPolicy = policy
+	}
+}
+
+// SetAllocateLoadBalancerNodePorts sets the allocate LB node port field.
+func SetAllocateLoadBalancerNodePorts(val bool) Tweak {
+	return func(svc *api.Service) {
+		svc.Spec.AllocateLoadBalancerNodePorts = utilpointer.BoolPtr(val)
+	}
+}
```
Comment (aojea) [inline pkg/api/service/testing/make.go:176]: these doesn't seems to be used in any other place, is a leftover from other branch or something you are planning to add?

Comment (aojea) [reply pkg/api/service/testing/make.go:176]: the unit test is failing because of this, so I think is missing below

```
    rest_test.go:633: Expected no error: Service "foo" is invalid: allocateLoadBalancerNodePorts: Required value
```

File: pkg/registry/core/service/strategy.go (hunk 1 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:321]: The name is "" in that case.  I could add a multi-port testcase if it makes us feel safer

Comment (thockin) [reply pkg/registry/core/service/strategy.go:321]: Added in next push

File: pkg/registry/core/service/strategy.go (hunk 2 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:311]: If someone passes nil, I think we WANT it to crash - it's semantically wrong

File: pkg/registry/core/service/storage/rest_test.go (hunk 3 above)
Comment (thockin) [reply pkg/registry/core/service/storage/rest_test.go:649]: If you mutate ServiceType and it no longer needs these values, then we don't want to carry them forward, right?  I thought about adding more here, but it feels redundant - we have tests around all sorts of updates already.

File: pkg/api/service/testing/make.go (hunk 4 above)
Comment (thockin) [reply pkg/api/service/testing/make.go:176]: I needed to rebase this on https://github.com/kubernetes/kubernetes/pull/103467

Comment (thockin) [reply pkg/api/service/testing/make.go:176]: done in new push

File: pkg/registry/core/service/storage/rest_test.go (hunk 3 above)
Comment (aojea) [reply pkg/registry/core/service/storage/rest_test.go]: sounds good, just being paranoid

File: pkg/registry/core/service/strategy.go (hunk 2 above)
Comment (aojea) [reply pkg/registry/core/service/strategy.go:311]: > If someone passes nil, I think we WANT it to crash - it's semantically wrong

The "old" object is not obtained from storage? if is an Update it can't be nil

**Comment by aojea** [comment]
/lgtm
/hold
waiting for https://github.com/kubernetes/kubernetes/pull/103467
unhold once that merges

File: pkg/registry/core/service/strategy.go (hunk 2 above)
Comment (aojea) [reply pkg/registry/core/service/strategy.go:311]: so we can shortcircuit here

**Comment by aojea** [comment]
/lgtm cancel
one doubt here https://github.com/kubernetes/kubernetes/pull/103532/commits/8dcce11a26af6632dd421e93a7b02b0c2577cf61#r665594286

File: pkg/registry/core/service/strategy.go (hunk 2 above)
Comment (thockin) [reply pkg/registry/core/service/strategy.go:311]: I think we are agreeing?

This is only called on the update path and if it turns out to be a creat-on-update, we end up calling the create path (PrepareForCreate()) and not PrepareForUpdate().  So I don't see how we could end up in PrepareForUpdate() without a valid old and new object.

If we ever did end up here with a nil pointer, that would indicate some bizarre condition I have no idea how to handle properly right now.

Do you buy that ?

Comment (aojea) [reply pkg/registry/core/service/strategy.go:311]: the code will panic for us, I guess ...

Comment (aojea) [reply pkg/registry/core/service/strategy.go:311]: I see it now https://github.com/kubernetes/kubernetes/blob/f01c9e8683adacbfbad58e5153dfac9ebf954c4b/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L121-L134

Thanks

**Comment by aojea** [comment]
/retest
2 sig-node and 1 sig-storage test
/lgtm
Thanks

**Comment by aojea** [comment]
verified the whole apiserver path also with 

```
--- a/test/integration/service/loadbalancer_test.go
+++ b/test/integration/service/loadbalancer_test.go
@@ -121,6 +121,8 @@ func Test_ServiceLoadBalancerEnableThenDisableAllocatedNodePorts(t *testing.T) {
                t.Error("expected node ports but found none")
        }
 
+       service.Spec.ClusterIP = ""
+       service.Spec.ClusterIPs = []string{}
        service.Spec.AllocateLoadBalancerNodePorts = utilpointer.BoolPtr(false)
        service, err = client.CoreV1().Services(ns.Name).Update(context.TODO(), service, metav1.UpdateOptions{})
```

**Comment by jim-barber-he** [comment]
Is this likely to be backported to Kubernetes v1.21?
I see that is isn't in the `v1.21.4-rc.0` git tag

File: pkg/registry/core/service/strategy.go [hunk 5]
```diff
@@ -302,6 +303,43 @@ func (serviceStatusStrategy) WarningsOnUpdate(ctx context.Context, obj, old runt
...
+		if newSvc.Spec.ClusterIP == "" {
+			newSvc.Spec.ClusterIP = oldSvc.Spec.ClusterIP
+		}
+		if len(newSvc.Spec.ClusterIPs) == 0 {
+			newSvc.Spec.ClusterIPs = oldSvc.Spec.ClusterIPs
+		}
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:317]: does copying the value of this field from the old object break the assumptions in NormalizeClusterIPs for an update operation where the user was only aware of the `clusterIP` field and was trying to update it?

File: pkg/registry/core/service/strategy.go [hunk 6]
```diff
@@ -302,6 +303,43 @@ func (serviceStatusStrategy) WarningsOnUpdate(ctx context.Context, obj, old runt
...
+	}
+
```
Comment (liggitt) [inline pkg/registry/core/service/strategy.go:319]: it's an edge case, but shouldn't this avoid copying node ports that are explicitly referenced in the new service?

otherwise a user that depends on allocated ports initially then applies an update that explicitly uses a specific port that is not used by any other service can get an error when they would otherwise succeed:

1. create service with multiple ports, requiring a node port and healthcheck node port and depending on auto-allocated values

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: port1
      port: 100
    - name: port2
      port: 200
    - name: port3
      port: 300
  selector:
    test: "true"
```

resulting in 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.0.0.178
  clusterIPs:
  - 10.0.0.178
  externalTrafficPolicy: Local
  healthCheckNodePort: 31091
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port1
    nodePort: 32545
    port: 100
    protocol: TCP
    targetPort: 100
  - name: port2
    nodePort: 31089
    port: 200
    protocol: TCP
    targetPort: 200
  - name: port3
    nodePort: 32697
    port: 300
    protocol: TCP
    targetPort: 300
  selector:
    test: "true"
  sessionAffinity: None
  type: LoadBalancer
```

2. update service, explicitly specifying some ports and leaving others blank

```
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: port1
      port: 100
    - name: port2
      port: 200
      nodePort: 32545 # happens to match auto-allocated port1
    - name: port3
      port: 300
      nodePort: 31091 # happens to match auto-allocated health check port
  selector:
    test: "true"
```

result:

```
The Service "test" is invalid: spec.ports[1].nodePort: Duplicate value: 32545
```

The current code copies the previously allocated node port from the old service to the new service and errors because the same node port was used twice in the update

Comment (aojea) [reply pkg/registry/core/service/strategy.go:319]: but 32545 was already allocated, why we should deallocate it from port1 in your example?

Comment (liggitt) [reply pkg/registry/core/service/strategy.go:319]: things the user sets explicitly should take priority over copying previously allocated values from the old service into the new to save reallocating

Comment (aojea) [reply pkg/registry/core/service/strategy.go:319]: so, empty doesn't mean "keep the old value", means "keep the old value if I'm not reusing it"?
