### PR TITLE
Dual-stack: fix the bug that Service clusterIP does not respect specified ipFamily

### LINKED ISSUE #89610: Dual-stack with base family IPv6: Services with ipFamily:IPv4 gets ipv6 addresses
**What happened**:

When K8s is started in dual-stack mode with IPv6 as the "main" (or base) family services specified with ipFamily:IPv4 still get a ipv6 `ClusterIP`;

```
vm-001 ~ # kubectl get svc mconnect-ipv4
NAME            TYPE           CLUSTER-IP        EXTERNAL-IP   PORT(S)          AGE
mconnect-ipv4   LoadBalancer   fd00:4000::6586   10.0.0.0      5001:31270/TCP   5m25s
vm-001 ~ # kubectl get svc mconnect-ipv4 -o json | jq .spec
{
  "clusterIP": "fd00:4000::6586",
  "externalTrafficPolicy": "Cluster",
  "ipFamily": "IPv4",
  "loadBalancerIP": "10.0.0.0",
  "ports": [
    {
      "nodePort": 31270,
      "port": 5001,
      "protocol": "TCP",
      "targetPort": 5001
    }
  ],
  "selector": {
    "app": "mconnect"
  },
  "sessionAffinity": "None",
  "type": "LoadBalancer"
}
```
The `loadBalancerIP` is expicitly set to "10.0.0.0" using [assign-lb-ip](https://github.com/Nordix/assign-lb-ip).

**What you expected to happen**:

Services with ipFamily:IPv4 shall get ipv4 ClusterIP addresses.

**How to reproduce it (as minimally and precisely as possible)**:

* Setup a K8s cluster in dual-stack mode with family IPv6 as base
* Define a service with ipFamily: IPv4

To make K8s think IPv6 is the main family the cue is to define ipv6 addresses to K8s binaries. Below are my settings as an example. I do not use `kubeadm` but install "from scratch";

Master processes;
```
kube-scheduler --kubeconfig /etc/kubernetes/kubeconfig --leader-elect=false \
  --feature-gates IPv6DualStack=true

kube-controller-manager --kubeconfig /etc/kubernetes/kubeconfig \
  --allocate-node-cidrs=true --cluster-cidr=11.0.0.0/16,1100::/48 \
  --controllers=*,serviceaccount,serviceaccount-token \
  --feature-gates IPv6DualStack=true \
  --service-account-private-key-file=/srv/kubernetes/server.key \
  --root-ca-file=/srv/kubernetes/server.crt --leader-elect=false

kube-apiserver --token-auth-file=/srv/kubernetes/known_tokens.csv \
  --allow-privileged=true --insecure-bind-address=1000::1:192.168.1.1 \
  --advertise-address=1000::1:192.168.1.1 --authorization-mode=AlwaysAllow \
  --feature-gates IPv6DualStack=true --etcd-servers=http://127.0.0.1:2379 -\
  --anonymous-auth=false --service-cluster-ip-range=fd00:4000::/112,12.0.0.0/16 \
  --enable-admission-plugins=ServiceAccount,AlwaysAdmit \
  --client-ca-file=/srv/kubernetes/ca.crt \
  --tls-private-key-file=/srv/kubernetes/server.key \
  --tls-cert-file=/srv/kubernetes/server.crt
```

`etcd` is accessed with ipv4 which does not affect the K8s family.

Worker processes;
```
kubelet --address=:: --node-ip=1000::1:192.168.1.2 --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/crio/crio.sock \
  --image-service-endpoint=unix:///var/run/crio/crio.sock \
  --feature-gates IPv6DualStack=true --register-node=true \
  --kubeconfig /etc/kubernetes/kubeconfig \
  --network-plugin=cni --cluster-dns=1000::1:192.168.1.2 \
  --cluster-domain=xcluster --runtime-cgroups=/systemd/system.slice \
  --kubelet-cgroups=/systemd/system.slice
$ cat /etc/kubernetes/kubeconfig
apiVersion: v1
clusters:
- cluster:
    server: http://[1000::1:192.168.1.1]:8080
  name: xcluster
contexts:
- context:
    cluster: xcluster
    user: root
  name: xcluster
current-context: xcluster
kind: Config
preferences: {}
users:
- name: root
  user:
    as-user-extra: {}

kube-proxy --config /etc/kubernetes/kube-proxy.config
$ cat /etc/kubernetes/kube-proxy.config
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: "::1"
featureGates:
  IPv6DualStack: true
  SCTPSupport: true
clientConnection:
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: "/etc/kubernetes/kubeconfig"
  qps: 5
clusterCIDR: "1100::/48,11.0.0.0/16"
configSyncPeriod: 15m0s
conntrack:
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  syncPeriod: 30s
metricsBindAddress: 127.0.0.1:10249
mode: "ipvs"
nodePortAddresses: null
oomScoreAdj: -999
portRange: ""
udpIdleTimeout: 250ms
```

**Anything else we need to know?**:

There are other problems with dual-stack/ipv6-base but may be caused by this one. For example `kubectl top nodes` does not work and some `calico` processes does not become "ready".

Ipv6 traffic to ipv6 services and DNS works;
```
# mconnect -address mconnect-ipv6.default.svc.xcluster:5001 -nconn 100
Failed connects; 0
Failed reads; 0
mconnect-deployment-6c5bc66c5c-fq82x 25
mconnect-deployment-6c5bc66c5c-x8r9l 25
mconnect-deployment-6c5bc66c5c-7rqw9 25
mconnect-deployment-6c5bc66c5c-zk5b4 25
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: -
- OS (e.g: `cat /etc/os-release`): BusyBox based own setup.
- Kernel (e.g. `uname -a`):
```
Linux vm-002 5.5.7 #4 SMP Wed Mar 18 12:47:34 CET 2020 x86_64 GNU/Linux
```
- Install tools: "from scratch"
- Network plugin and version (if this is a network-related bug): `calico/cni:v3.12.0`
- Others:

### PR DESCRIPTION
**Pull request by SataQiu**
Signed-off-by: SataQiu <1527062125@qq.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix the bug that Service clusterIP does not respect specified ipFamily

**Which issue(s) this PR fixes**:

Fixes #89610

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
dual-stack: fix the bug that Service clusterIP does not respect specified ipFamily
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

File: pkg/registry/core/service/storage/rest.go [hunk 1]
```diff
@@ -574,7 +574,9 @@ func (r *REST) getAllocatorBySpec(service *api.Service) ipallocator.Interface {
 	}
 
 	secondaryAllocatorCIDR := r.secondaryServiceIPs.CIDR()
-	if *(service.Spec.IPFamily) == api.IPv6Protocol && netutil.IsIPv6CIDR(&secondaryAllocatorCIDR) {
+	secondaryAllocatorIsIPv6 := netutil.IsIPv6CIDR(&secondaryAllocatorCIDR)
+	if *(service.Spec.IPFamily) == api.IPv6Protocol && secondaryAllocatorIsIPv6 ||
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go]: looking at the method 
`func (r *REST) getAllocatorByClusterIP(service *api.Service) ipallocator.Interface {`

https://github.com/kubernetes/kubernetes/pull/89612/files#diff-a17c85ca4491ca68b2c928ed6221828eR556 

I think that it has the same problem and we should fix it there too.

**Comment by aojea** [comment]
Just one comment to fix https://github.com/kubernetes/kubernetes/pull/89612/files#diff-a17c85ca4491ca68b2c928ed6221828eR556 too.
Also, we should add unit tests to cover these scenarios
Thanks for the quick fix though

**Comment by liggitt** [comment]
cc @smarterclayton 
this looks related to the long-lived PR Clayton is working on… I'm not sure if the fixes there would include a fix for this

this also needs a test demonstrating the bug and that this fixes the issue

**Review by uablrek — APPROVED** [review]
lgtm. Also verified that is works on cluster.

**Comment by aojea** [comment]
> this looks related to the long-lived PR Clayton is working on… I'm not sure if the fixes there would include a fix for this

@liggitt I think that Clayton's PR is totally related but it's leaning towards a more in deep revision of the whole dual-stack API and is not likely to be merged soon, however, this PR is just fixing current dual-stack implementation that assumes that the secondary ip allocator is always ipv6.

> this also needs a test demonstrating the bug and that this fixes the issue

Absolutely, I think that this is something that we should stress for going to beta with dual-stack, IMHO at least we should have:
- skew version testing
- e2e test with ipv4 primary ipv6 secondary
- e2e test with ipv6 primary ipv4 secondary

@aramase do you think that we can add another job like current azure-dual stack end to end with IPv6 as primary address?

https://k8s-testgrid.appspot.com/sig-network-dualstack-azure-e2e#dualstack-azure-e2e-master

meanwhile it seems we have to rely on manual testing, per @uablrek comment

> lgtm. Also verified that is works on cluster.

and unit testing :(

Anyway,  this is LGTM to me but I defer to @thockin and @smarterclayton the last decision.

**Comment by aojea** [comment]
hmm I think that I understand your point @liggitt 😅 
```
spec:
  clusterIP: fd00:10:96::x
  ipFamily: IPv4
```

`clusterIP` and `ipFamily` doesn't match

**Comment by uablrek** [comment]
@aojea How did you get that? I have not seen anything like that.

**Comment by aojea** [comment]
> @aojea How did you get that? I have not seen anything like that.

https://github.com/kubernetes/kubernetes/issues/89526#issue-588494743

**Comment by uablrek** [comment]
Ah, I thught it was *with* this PR. Thanks.

**Comment by duylong** [comment]
Do you know if this merge will be provided in a version 1.19 or 1.18.x ?? because currently, I have a dualstack ipv6/ipv4 cluster but I cannot use ipv4 o :-)

**Comment by liggitt** [comment]
in general, I would not expect backports for alpha-level features

**Comment by aramase** [comment]
> @aramase do you think that we can add another job like current azure-dual stack end to end with IPv6 as primary address?

@aojea I can definitely do that. It requires some changes in aks-engine to allow that. I'll make the changes and add a job so we can validate v6-v4 scenario as well.

**Comment by aojea** [comment]
that will be awesome, we can add it to the new KEP review ...

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by duylong** [comment]
Nice, it only remains to wait for the release :)
