### PR TITLE
Fix concurrent map write access in Portworx create volume call

### LINKED ISSUE #76340: Fix concurrent map read and map write in Portworx driver
**What happened**: The Portworx volume driver is accessing the storage parameters and also modifying it. This is a shared map object used by all PVCs being created at that time from the same StorageClass.

This causes 2 issues:

1. The Portworx driver ends up saving annotations of one PVC into the parameters of another PVC as both CreateVolume calls use the same map. See https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/portworx/portworx_util.go#L76
2. The controller manager crashes as 2 CreateVolume routines try to modify the same map. This is a big problem since the controller manager container crashes half way into creating a volume resulting in the volume being present in the backend portworx cluster but not bound in Kubernetes.

**What you expected to happen**: CreateVolume call for one PVC should be completely isolated from another PVC

**How to reproduce it (as minimally and precisely as possible)**: Create a large number of PVCs using the Portworx volume driver using the same StorageClass.

**Anything else we need to know?**:

**Environment**: n/a
- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: Kubernetes cluster with Portworx installed
- Others:

### PR DESCRIPTION
**Pull request by harsh-px**
Fixes #76340

Signed-off-by: Harsh Desai <harsh@portworx.com>

**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**: 

Fixes a crash in controller manager due to concurrent map access in the Portworx volume driver create call

**Which issue(s) this PR fixes**:
Fixes #76340

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

```release-note
Fix issue in Portworx volume driver causing controller manager to crash
```

### CODE REVIEW

File: pkg/volume/portworx/portworx_util.go [hunk 1]
```diff
@@ -72,12 +72,14 @@ func (util *portworxVolumeUtil) CreateVolume(p *portworxVolumeProvisioner) (stri
 	}
 
 	// Pass all parameters as volume labels for Portworx server-side processing
-	if len(p.options.Parameters) > 0 {
-		spec.VolumeLabels = p.options.Parameters
-	} else {
+	if spec.VolumeLabels == nil {
```
Comment (liggitt) [inline pkg/volume/portworx/portworx_util.go]: this doesn't seem to protect against concurrent access... was the issue concurrency or assigning to a nil map?

Comment (harsh-px) [reply pkg/volume/portworx/portworx_util.go]: @liggitt  thanks for reviewing this.

Before this change, reference to `p.options.Parameters` (which is the shared map) was getting saved in `spec.VolumeLabels` and line 103 below updates this map. When multiple PVCs are getting provisioned, this causes concurrent map writes. The golang panic will say `fatal: concurrent map read and write`.

Another problem you can see from the below for loop is `p.options.Parameters` will start accumulate annotations of all PVCs sharing a StorageClass.

Let me know if you have further questions.

Comment (liggitt) [reply pkg/volume/portworx/portworx_util.go]: I see, thanks
