### PR TITLE
fix(scheduler): skip best-effort pods in BalancedAllocation PreScore

### LINKED ISSUE #129138: NodeResourcesBalancedAllocation cause too many pods scheduled to the same node
### What happened?

NodeResourcesBalancedAllocation will return different score if pod request is empty.

```
I1210 06:42:54.701779       1 resource_allocation.go:70] "Listing internal info for allocatable resources, requested resources and score" pod="tuyaco-k8s/task-worker-9" node="10.20.96.50" resourceAllocationScorer="NodeResourcesBalancedAllocation" allocatableResource=map[cpu:15600 memory:28727588291] requestedResource=map[cpu:14580 memory:24593301504] resourceScore=96
I1210 06:42:54.701793       1 resource_allocation.go:70] "Listing internal info for allocatable resources, requested resources and score" pod="tuyaco-k8s/task-worker-9" node="10.20.96.8" resourceAllocationScorer="NodeResourcesBalancedAllocation" allocatableResource=map[cpu:15600 memory:28727600579] requestedResource=map[cpu:15350 memory:24235737088] resourceScore=92
I1210 06:42:54.701807       1 resource_allocation.go:70] "Listing internal info for allocatable resources, requested resources and score" pod="tuyaco-k8s/task-worker-9" node="10.20.96.9" resourceAllocationScorer="NodeResourcesBalancedAllocation" allocatableResource=map[cpu:15600 memory:28727600579] requestedResource=map[cpu:13480 memory:19474153472] resourceScore=90
```

### What did you expect to happen?

NodeResourcesBalancedAllocation score should return zero if podRequest is zero. 

https://github.com/kubernetes/kubernetes/blob/a499facee693a1a83daadb82d88f7b51d324ffc5/pkg/scheduler/framework/plugins/noderesources/resource_allocation.go#L85-L114

The code below use `IsPrefixedNativeResource`, which ignore `cpu` and `memory`. 
https://github.com/kubernetes/kubernetes/blob/a499facee693a1a83daadb82d88f7b51d324ffc5/pkg/scheduler/util/utils.go#L158-L162

I think we should use below function.

https://github.com/kubernetes/kubernetes/blob/a499facee693a1a83daadb82d88f7b51d324ffc5/pkg/apis/core/v1/helper/helpers.go#L54-L60

### How can we reproduce it (as minimally and precisely as possible)?

create pod whcih request is empty and enable NodeResourcesBalancedAllocation.

scheduler config:
```yaml
- name: NodeResourcesBalancedAllocation
  args:
    resources:
      - name: cpu
      - name: memory
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Server Version: v1.24.15
```

</details>

### Cloud provider

<details>
vanilla
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Bowser1704**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

- Refactored `PreScore` method in `balanced_allocation.go` to skip best-effort pods.
- Updated unit tests in `balanced_allocation_test.go` to check for the new status codes.

The NodeResourcesBalancedAllocation maybe cause too many pods scheduled to the same node.

#### Which issue(s) this PR fixes:

Fixes #129138

#### Does this PR introduce a user-facing change?

```release-note
The BalancedAllocation plugin will skip all best-effort (zero-requested) pod.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/ok-to-test
@kubernetes/sig-scheduling-misc can anyone take a look for a first reviewing path.

**Comment by AxeZhan** [comment]
/assign 
Will take a look later this week.

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go [hunk 1]
```diff
@@ -63,8 +65,12 @@ func (s *balancedAllocationPreScoreState) Clone() framework.StateData {
 
 // PreScore calculates incoming pod's resource requests and writes them to the cycle state used.
 func (ba *BalancedAllocation) PreScore(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod, nodes []*framework.NodeInfo) *framework.Status {
+	podRequests := ba.calculatePodResourceRequestList(pod, ba.resources)
+	if ba.isBestEffortPod(podRequests) {
```
Comment (googs1025) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go:69]: where is the `isBestEffortPod` implement? I can't find any

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go:69]: in the resource_allocation.go.

can you try checkout with force?

Comment (googs1025) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go:69]: sorry for miss. thanks

**Comment by AxeZhan** [comment]
Code changes look good to me.  Only a nit.

I think we need an integration test to verify best-effort pods are spread to different nodes.
Maybe something like [TestDefaultPodTopologySpreadScoring](https://github.com/kubernetes/kubernetes/blob/de7708f06e11efe1140805f1eb4814f358a8d31e/test/integration/scheduler/scoring/priorities_test.go#L1140). I'm not sure if there is already such a test though.

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go [hunk 2]
```diff
@@ -37,8 +37,10 @@ type BalancedAllocation struct {
 	resourceAllocationScorer
 }
 
-var _ framework.PreScorePlugin = &BalancedAllocation{}
-var _ framework.ScorePlugin = &BalancedAllocation{}
+var (
```
[the remark this answers is not in the document]
Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go]: fixed

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go [hunk 3]
```diff
@@ -63,8 +65,12 @@ func (s *balancedAllocationPreScoreState) Clone() framework.StateData {
 
 // PreScore calculates incoming pod's resource requests and writes them to the cycle state used.
 func (ba *BalancedAllocation) PreScore(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod, nodes []*framework.NodeInfo) *framework.Status {
+	podRequests := ba.calculatePodResourceRequestList(pod, ba.resources)
+	if ba.isBestEffortPod(podRequests) {
+		return framework.NewStatus(framework.Skip)
```
[the remark this answers is not in the document]
Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go:71]: Sounds good, added

**Comment by Bowser1704** [comment]
> I think we need an integration test to verify best-effort pods are spread to different nodes.
Maybe something like [TestDefaultPodTopologySpreadScoring](https://github.com/kubernetes/kubernetes/blob/de7708f06e11efe1140805f1eb4814f358a8d31e/test/integration/scheduler/scoring/priorities_test.go#L1140). I'm not sure if there is already such a test though.

My understanding is that there is no policy for spreading best-effort pods across different nodes. The default policy is PodTopologySpread for deployments. So, it might not be necessary.

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 4]
```diff
@@ -136,12 +137,13 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
 			// CPU Fraction: 0 / 4000 = 0 %
 			// Memory Fraction: 0 / 10000 = 0%
 			// Node2 Score: (1-0) * MaxNodeScore = MaxNodeScore
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:139]: Please update the test cases comments

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 5]
```diff
@@ -395,8 +407,8 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
 			for i := range test.nodes {
 				if test.runPreScore {
 					status := p.(framework.PreScorePlugin).PreScore(ctx, state, test.pod, tf.BuildNodeInfos(test.nodes))
-					if !status.IsSuccess() {
-						t.Errorf("PreScore is expected to return success, but didn't. Got status: %v", status)
+					if status.Code() != test.wantPreScoreStatusCode {
+						t.Errorf("unexpected status code, want: %v, got: %v", test.wantPreScoreStatusCode, status.Code())
 					}
 				}
 				hostResult, status := p.(framework.ScorePlugin).Score(ctx, state, test.pod, test.nodes[i].Name)
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:414]: You shouldn't run Score when preScore returns Skip. Please fix this.

Then you could remove `expectedList` from test cases returning Skip

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 6]
```diff
@@ -395,8 +407,8 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
 			for i := range test.nodes {
 				if test.runPreScore {
 					status := p.(framework.PreScorePlugin).PreScore(ctx, state, test.pod, tf.BuildNodeInfos(test.nodes))
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:409]: PreScore should be called once, not per node. I think you can also fix this (move above for loop)

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go (hunk 5 above)
Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:315]: fixed

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go (hunk 4 above)
Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go]: fixed, I also removed some redundent tests.

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go [hunk 7]
```diff
@@ -63,8 +63,15 @@ func (s *balancedAllocationPreScoreState) Clone() framework.StateData {
 
 // PreScore calculates incoming pod's resource requests and writes them to the cycle state used.
 func (ba *BalancedAllocation) PreScore(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod, nodes []*framework.NodeInfo) *framework.Status {
+	podRequests := ba.calculatePodResourceRequestList(pod, ba.resources)
+	if ba.isBestEffortPod(podRequests) {
+		// skip BalancedAllocation scoring for best-effort pods to
+		// prevent a large number of pods from being scheduled to the same node.
+		// see: https://github.com/kubernetes/kubernetes/issues/129138
```
Comment (haosdent) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation.go:70]:
```suggestion
		// Skip BalancedAllocation scoring for best-effort pods to
		// prevent a large number of pods from being scheduled to the same node.
		// See https://github.com/kubernetes/kubernetes/issues/129138 for details.
```

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 8]
```diff
@@ -161,76 +146,6 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
...
-			nodes:        []*v1.Node{makeNode("node1", 250, 1000*1024*1024, nil), makeNode("node2", 250, 1000*1024*1024, nil)},
-			expectedList: []framework.NodeScore{{Name: "node1", Score: 100}, {Name: "node2", Score: 100}},
-			name:         "no resources requested, pods with container scheduled",
-			pods: []*v1.Pod{
-				st.MakePod().Node("node1").Obj(),
-				st.MakePod().Node("node1").Obj(),
-			},
-			args:        config.NodeResourcesBalancedAllocationArgs{Resources: defaultResourceBalancedAllocationSet},
-			runPreScore: true,
-		},
```
Comment (AxeZhan) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: Why are these case deleted?

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: All no resource requested pods will be skipped in PreScore, regardless of the node.

Comment (AxeZhan) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: Ah right.

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: Can I squash these commits together now?

Comment (AxeZhan) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: You can always squash the commits, don't have to wait for reviewers.

> All no resource requested pods will be skipped in PreScore, regardless of the node.

My opinion(maybe weird): Can we still keep these cases to verify the calculation in `Score()`? 
Maybe just change `runPreScore` to false. cc @macsko

**Comment by AxeZhan** [comment]
BTW, can you check the cla status?

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go (hunk 8 above)
Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: > My opinion(maybe weird): Can we still keep these cases to verify the calculation in Score()?
Maybe just change runPreScore to false. cc @macsko

It's also my initial thought.

**Comment by Bowser1704** [comment]
> BTW, can you check the cla status?

I already signed many times, but the EasyCLA status is still failing. It's weird.

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go (hunk 8 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: Maybe we could. Feel free to keep these, but mention in the test cases' comments the score would be 0 if the preScore would be ran.

Maybe we could. Feel free to keep them, but mention in the comments on the test cases that the score would be 0 if preScore was run before.

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:209]: Added back. cc @AxeZhan @macsko

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 9]
```diff
@@ -183,9 +178,10 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
 				st.MakePod().Node("node2").Labels(labels1).Obj(),
 			},
 			args:        config.NodeResourcesBalancedAllocationArgs{Resources: defaultResourceBalancedAllocationSet},
-			runPreScore: true,
+			runPreScore: false,
```
Comment (sanposhiho) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: Do we need `runPreScore: false` test cases with the best effort pod? Those are unrealistic (or uncommon) scenarios because we basically recommend people set the plugins at `multiPoint`, that is, it's a rare case that people disable plugin's PreScore only.

It'd prefer to remove such test cases (if other test cases cover things enough), or to change them to have pods with resource requests (if other test cases don't cover things enough).

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: Other test cases cover enough ground, but @AxeZhan think we should keep these cases to verify the calculations in Score().

cc @macsko

Comment (sanposhiho) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: I meant "cover" equals whether other test cases verify the calculations in Score() enough.
If other test cases verify the calculations sufficiently, we can remove those, vs, if not, can we change the best effort pods into pods with request resources, which make the test cases realistic.

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: Actually, it verifies the calculation sufficiently. I've changed one test to use pods with requested resources, while the remaining test case uses best-effort pods solely for calculating best-effort pods.

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: >  it's a rare case that people disable plugin's PreScore only.

I think not.

As you mentioned, it's a rare case, and perhaps the user wants to disable PreScore to prevent skipping best-effort pods.

Comment (sanposhiho) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:181]: > the remaining test case uses best-effort pods solely for calculating best-effort pods.

Then, can we remove those?

> shouldn't we change the Score func as well?
> As @sanposhiho mentioned, it's a rare case, and perhaps the user wants to disable PreScore to prevent skipping best-effort pods.

@macsko 's point makes sense to me, actually. We don't have a reason to implement the same at Score. Even though it's a rare scenario, we can make an effort to perform the best calculation, as long as the implementation isn't complicated by those.

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go]: > Then, can we remove those?

Removed.

> @macsko 's point makes sense to me, actually. We don't have a reason to implement the same at Score. Even though it's a rare scenario, we can make an effort to perform the best calculation, as long as the implementation isn't complicated by those.

Sounds good, added.

cc @sanposhiho @macsko

File: pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go [hunk 10]
```diff
@@ -392,13 +301,17 @@ func TestNodeResourcesBalancedAllocation(t *testing.T) {
...
-					status := p.(framework.PreScorePlugin).PreScore(ctx, state, test.pod, tf.BuildNodeInfos(test.nodes))
-					if !status.IsSuccess() {
-						t.Errorf("PreScore is expected to return success, but didn't. Got status: %v", status)
-					}
+			if test.runPreScore {
+				status := p.(framework.PreScorePlugin).PreScore(ctx, state, test.pod, tf.BuildNodeInfos(test.nodes))
+				if status.Code() != test.wantPreScoreStatusCode {
+					t.Errorf("unexpected status code, want: %v, got: %v", test.wantPreScoreStatusCode, status.Code())
 				}
+				if test.wantPreScoreStatusCode == framework.Skip {
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go:309]: To match the log message:
```suggestion
				if status.Code() == framework.Skip {
```

Comment (Bowser1704) [reply pkg/scheduler/framework/plugins/noderesources/balanced_allocation_test.go]: fixed

**Review by hashim21223445 — APPROVED** [review]
