### PR TITLE
use kubectl-with-retry on pause & resume

### LINKED ISSUE #25645: test-cmd flake: kubectl rollout pause deployments --recursive
```
FAIL!
Get deployment {{range.items}}{{.spec.paused}}:{{end}}
  Expected: true:true:
  Got:      <no value>:true:
(B
1090 ./hack/test-cmd.sh
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25221/kubernetes-pull-test-unit-integration/25998/

### PR DESCRIPTION
**Pull request by metral**
attempts to fix https://github.com/kubernetes/kubernetes/issues/25645 by using `kubectl-with-retry` on `rollout {pause,resume}` (`resume` is for safe measures) instead of `kubectl` directly, as is done with other `rollout {pause,resume}` tests in this same script.

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by metral** [comment]
The `e2e` and `Node e2e` tests are hitting the following errors:
```
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-agent-pr-3-0-minion-e2e-gce-agent-pr-3-0-http-alt' was not found
ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/e2e-gce-agent-pr-3-0-minion-e2e-gce-agent-pr-3-0-nodeports' was not found
Bringing down cluster using provider: gce
```

```
ERROR: gcloud crashed (OSError): [Errno 39] Directory not empty: '/usr/local/share/google/google-cloud-sdk.staging/lib/googlecloudsdk/third_party/apis'

If you would like to report this issue, please run the following command:
  gcloud feedback
Project: kubernetes-jenkins-pull
Zone: us-central1-f
INSTANCE_GROUPS=
NODE_NAMES=
Bringing down cluster
ERROR: gcloud failed to load: No module named argcomplete
```

```
WARNING: You are creating a legacy network. Using --mode=legacy will be required in future releases.
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Quota 'ROUTES' exceeded.  Limit: 170.0

2016/05/25 06:28:42 e2e.go:206: Error running up: exit status 1
2016/05/25 06:28:42 e2e.go:202: Step 'up' finished in 47.621947144s
2016/05/25 06:28:42 e2e.go:114: Error starting e2e cluster. Aborting.
```

**Comment by eparis** [comment]
@k8s-bot e2e test this flake: #26271

File: hack/test-cmd.sh [hunk 1]
```diff
@@ -1087,13 +1087,11 @@ __EOF__
   kube::test::get_object_assert deployment "{{range.items}}{{$deployment_image_field}}:{{end}}" "${IMAGE_NGINX}:${IMAGE_NGINX}:"
   kube::test::if_has_string "${output_message}" "Object 'Kind' is missing"
   ## Pause the deployment
-  output_message=$(! kubectl rollout pause -f hack/testdata/recursive/deployment --recursive 2>&1 "${kube_flags[@]}")
```
Comment (janetkuo) [inline hack/test-cmd.sh]: Would you change the title comment of this test too (L1077)? These tests are about "--recursive" and the "rollout" commands, but not about "Rollback a deployment". It's somewhat misleading. Changing each sub-title would help too (maybe add "recursively" to the end of each sub-title, and mention that we expect error message "Object 'Kind' is missing").

File: hack/test-cmd.sh [hunk 2]
```diff
@@ -1087,13 +1087,11 @@ __EOF__
...
+  kubectl-with-retry rollout pause -f hack/testdata/recursive/deployment --recursive 2>&1 "${kube_flags[@]}"
   kube::test::get_object_assert deployment "{{range.items}}{{.spec.paused}}:{{end}}" "true:true:"
-  kube::test::if_has_string "${output_message}" "Object 'Kind' is missing"
```
Comment (janetkuo) [inline hack/test-cmd.sh]: I believe we still want this check?

File: hack/test-cmd.sh (hunk 1 above)
Comment (metral) [inline hack/test-cmd.sh]: Sure thing

File: hack/test-cmd.sh (hunk 2 above)
Comment (metral) [inline hack/test-cmd.sh]: We do, but I removed it as the only solution to triage the flake was to attempt using `kubectl-with-retry` instead of `kubectl`.

However, in doing so, `kubectl-with-retry` directs stderr to a file that is removed once it is done executing, and does not allow me to review it for this missing object as I was doing

**Comment by metral** [comment]
The e2e test is hitting flake https://github.com/kubernetes/kubernetes/issues/26210

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #IGNORE

File: hack/test-cmd.sh (hunk 2 above)
Comment (janetkuo) [inline hack/test-cmd.sh]: We can have a try function with customized error message check, or we can pass the expected error message to that retry function. WDYT?

Comment (janetkuo) [inline hack/test-cmd.sh]: Do we still need 2>&1 when we're using kubectl-with-retry?

Comment (janetkuo) [inline hack/test-cmd.sh]: Maybe creating a new retry function with your own check is easier, and we can add a comment saying that removing this function once #20437 is fixed

**Comment by metral** [comment]
@janetkuo I've gone ahead and addressed your feedback:

- cleared up test title comments to describe the tests more effectively
- removed 2>&1 from `kubectl-with-retry` as it wasn't needed
- modified `kubectl-with-retry` slightly to allow me to preserve the error file for review/usage in my tests

PTAL

**Comment by janetkuo** [comment]
Thanks, looks good now. Please squash and I'll apply the tag.

**Comment by metral** [comment]
@janetkuo all set, thanks!
