### PR TITLE
Increase failureThresholds for failing HTTP liveness test

### LINKED ISSUE #59150: Probing container should *not* be restarted with a /healthz http liveness probe [Conformance] {E2eNode Suite}
We have noticed few months ago that this test flaked again(https://github.com/openshift/origin/issues/12072#issuecomment-335311564)

 Opening this issue again to start dicussion on the test.

Following are my observations after going through history and logs :
- We are bringing up a nginx container and trying to check if <container_IP:80> is available.
 - While this is not a bad idea, there are many things that could go wrong because of which nginx may not come to running. Some of them could be related to underlying infrastructure on which we have no control over, some could be related to network plugin being used etc. Some were mentioned in kubernetes/kubernetes#30714 (comment) as well.
    For example, the latest one failed with dial tcp 10.128.1.69:80: getsockopt: no route to host. This could be related to network setup as well.
-   This makes the test indeterministic and therefore flaky.

Since the goal this test is to check that a good container won't restart based on liveness probe, would it make sense to add a liveness command that checks for the existence of a particular directory that was created during container start up or something else instead of a HTTP GET.

/sig node
cc @Random-Liu

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
Removes test from e2e which relies on HTTP liveness as a measure to tell if the container is good or bad. While this is not a bad idea, we cannot rely on this test as HTTP liveness relies on network/infrastructure etc on which sometimes we have no control over. While increasing the timeout may be an option it may not be ideal for all cloud providers/type of hardware etc.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59150 

**Special notes for your reviewer**:
I have stated reasons in the issue #59150. We have seen that this test is flaking recently in https://github.com/openshift/origin/issues/12072

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sjenning** [comment]
Not sure if removing the test is the best.  It is checking functionality that should reliably work on the kubelet i.e. it should be able to contact the IP of local pods and do an HTTP GET against them.

There is another test in that same file that tests the reverse; making sure the pod *does* restart in the case of HTTP probe failure.  I imagine that doesn't flake though in that if the probe fails for any reason, the pod will be restarted.

If we do remove this one, probably should remove the other as well since, in the case of a bad node network config, it will pass but not for a good reason.

**Comment by ravisantoshgudimetla** [comment]
Thanks @sjenning for your sharing your thoughts. 

> Not sure if removing the test is the best.  It is checking functionality that should reliably work on the kubelet i.e. it should be able to contact the IP of local pods and do an HTTP GET against them.

That is correct but as I mentioned in the issue, the reliability depends on external factors too like how underlying infrastructure, CNI plugin being used etc and most of the times, the container is not coming up within timeout because of which test is flaking. While the other option is to increase the time out, I am not sure if at some point the timeout has to be increased/decreased again.

> If we do remove this one, probably should remove the other as well since, in the case of a bad node network config, it will pass but not for a good reason.

Agreed.

**Comment by ravisantoshgudimetla** [comment]
@kubernetes/sig-node-test-failures

**Comment by ravisantoshgudimetla** [comment]
@sjenning and I had an internal discussion and it seemed that it would be better to increase the timeout as a first step and see those flakes are going away.

**Comment by sjenning** [comment]
i think what we talked about doing is increasing the failureThreshold to something like 5.  don't want to slow the test down for the fast case.

**Comment by ravisantoshgudimetla** [comment]
@sjenning As discussed I updated the failure threshold for good pod.

**Comment by sjenning** [comment]
/lgtm
/assign @smarterclayton @liggitt 

We are interested to see if this decreases failure rates or if the failures are due to persistent conditions (bad pod network, etc).  Idea is the merge this and see if the flakes decrease (or ideally go away)

File: test/e2e/common/container_probe.go [hunk 1]
```diff
@@ -263,7 +263,7 @@ var _ = framework.KubeDescribe("Probing container", func() {
 							},
 							InitialDelaySeconds: 15,
 							TimeoutSeconds:      5,
-							FailureThreshold:    1,
+							FailureThreshold:    5, // to accommodate nodes which are slow in bringing up containers.
```
Comment (liggitt) [inline test/e2e/common/container_probe.go]: does this start to get close to the observation timeout? if the container was restarted at the end of 5 failures, would that happen within the observation timeout and fail the test as we would want?

Comment (sjenning) [reply test/e2e/common/container_probe.go]: `defaultObservationTimeout` is 2m.  default probe `periodSeconds` is 10s.  So `InitialDelaySeconds + periodSeconds * FailureThreshold = 65s.   So that should be fine.

Comment (liggitt) [reply test/e2e/common/container_probe.go]: ok
