### PR TITLE
Fix ServiceCIDR status field wiping

### LINKED ISSUE #137680: serviceCIDRStrategy does not perform status wiping
Neither `serviceCIDRStrategy.PrepareForCreate` nor `serviceCIDRStrategy.PrepareForUpdate` perform status wiping.

Should be:

```go
// PrepareForCreate clears the status of an ServiceCIDR before creation.
func (serviceCIDRStrategy) PrepareForCreate(ctx context.Context, obj runtime.Object) {
	cidr := obj.(*networking.ServiceCIDR)
	cidr.Status = networking.ServiceCIDRStatus{}
}

// PrepareForUpdate clears fields that are not allowed to be set by end users on update.
func (serviceCIDRStrategy) PrepareForUpdate(ctx context.Context, obj, old runtime.Object) {
	newServiceCIDR := obj.(*networking.ServiceCIDR)
	oldServiceCIDR := old.(*networking.ServiceCIDR)

	newServiceCIDR.Status = oldServiceCIDR.Status
}
```

cc @liggitt

### PR DESCRIPTION
**Pull request by jpbetz**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

builds on https://github.com/kubernetes/kubernetes/pull/137689

Addresses https://github.com/kubernetes/kubernetes/issues/137680#issuecomment-4055655960

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/137680

#### Does this PR introduce a user-facing change?

```release-note
Writes to the ServiceCIDR main resource now ignore status field changes in the request, consistent with all other Kubernetes APIs.
The ServiceCIDRStatusFieldWiping feature gate can be disabled to restore the previous behavior; it will be locked to enabled in a future release.
```

### CODE REVIEW

File: pkg/features/kube_features.go [hunk 1]
```diff
@@ -1820,6 +1825,10 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 		{Version: version.MustParse("1.32"), Default: true, PreRelease: featuregate.GA, LockToDefault: true},
 	},
 
+	ServiceCIDRStatusFieldWiping: {
+		{Version: version.MustParse("1.36"), Default: true, PreRelease: featuregate.Beta},
```
Comment (aojea) [inline pkg/features/kube_features.go]: should we use the `featuregate.Deprecated` like we use to do with these kind of bugs with user facing behavior?

Comment (liggitt) [reply pkg/features/kube_features.go]: That's a good question. We could retconn this as a gate introduced in the release servicecidr was, deprecated and false, then switches to deprecated and true in 1.36

I'd even consider backports of the behavior, off-by-default but able to be opted into via the gate

Comment (jpbetz) [reply pkg/features/kube_features.go]: > should we use the `featuregate.Deprecated` like we use to do with these kind of bugs with user facing behavior?

Good catch. Adding.

> That's a good question. We could retconn this as a gate introduced in the release servicecidr was, deprecated and false, then switches to deprecated and true in 1.36

> I'd even consider backports of the behavior, off-by-default but able to be opted into via the gate

While I like the idea of back-porting this fix, Wouldn't that mean that some patch versions of a minor have a gate while others do not? Have we ever done that before?

Comment (liggitt) [reply pkg/features/kube_features.go]: > Good catch. Adding.

did you mark the field stability level as deprecated? it still looks like beta

> While I like the idea of back-porting this fix, Wouldn't that mean that some patch versions of a minor have a gate while others do not? Have we ever done that before?

for backports we needed to do for permissions / security / data correctness reasons, but needed to make opt-in, yes, many times

**Comment by jpbetz** [comment]
@liggitt @aojea LGTM this one to merge it.
