### PR TITLE
Avoid dereferencing same endpoint twice on the deletion or update of a service

### LINKED ISSUE #93229: Windows Kubeproxy has Connectivity issues when one of the multiple services referencing a same endpoint is deleted or updated
**What happened**:
Two services referring the same endpoint. One of the services was deleted. This brought down the connectivity of the other service.

**What you expected to happen**:
The connectivity to service should continue to work

**How to reproduce it (as minimally and precisely as possible)**:
1. Create two services referencing same endpoint
2. Delete one of the services
3. The connectivity is broken to the other service

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sbangari**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
When a service is deleted or updated, the service becomes stale and is cleaned up. In the current logic this service cleanup can be triggered multiple times. Except the first cleanup the subsequent cleanup calls are a no-op. But as part of service cleanup the endpoints in the endpoint map are attempted to be cleaned up a second time and dereferenced twice.

In a scenario where the remote endpoints are shared across two services, the second dereference causes the remote endpoint to be deleted from HNS. This breaks connectivity to the service.
**Which issue(s) this PR fixes**:

Fixes #93229

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/winkernel/proxier.go [hunk 1]
```diff
@@ -319,19 +319,21 @@ func (ep *endpointsInfo) Cleanup() {
...
-		klog.V(4).Infof("Removing endpoints for %v, since no one is referencing it", ep)
-		err := ep.hns.deleteEndpoint(ep.hnsID)
-		if err == nil {
-			ep.hnsID = ""
-		} else {
-			klog.Errorf("Endpoint deletion failed for %v: %v", ep.IP(), err)
+		// Remove the remote hns endpoint, if no service is referring it
+		// Never delete a Local Endpoint. Local Endpoints are already created by other entities.
+		// Remove only remote endpoints created by this service
+		if *ep.refCount <= 0 && !ep.GetIsLocal() {
```
Comment (elweb9858) [inline pkg/proxy/winkernel/proxier.go:326]: So the second endpoint deletion was happening because of the ep.refCount == nil condition?

File: pkg/proxy/winkernel/proxier_test.go [hunk 2]
```diff
@@ -315,7 +315,312 @@ func TestCreateRemoteEndpointL2Bridge(t *testing.T) {
...
+		svc.Spec.Ports = []v1.ServicePort{{
+			Name:     svcPortName1.Port,
+			Port:     int32(svcPort1),
+			Protocol: v1.ProtocolTCP,
+			NodePort: int32(svcNodePort1),
+		}}
+	})
+
+	makeServiceMap(proxier,
+		service1,
```
Comment (elweb9858) [inline pkg/proxy/winkernel/proxier_test.go:500]: It's a little awkward passing one service as a variable and one via makeTestService, but I see that you need access to service1 later on (same for endpoints below). In iptables+ipvs proxier_test I see some examples where an array of services is created or all the services are declared as variables. Take a look at those & see if you think they are better style--I could go either way

File: pkg/proxy/winkernel/proxier.go (hunk 1 above)
Comment (sbangari) [reply pkg/proxy/winkernel/proxier.go:326]: yes

File: pkg/proxy/winkernel/proxier_test.go (hunk 2 above)
Comment (sbangari) [reply pkg/proxy/winkernel/proxier_test.go:500]: I actually don't need to access service1 later. Changed both the instances to use makeTestService.

**Review by kumarvin123 — APPROVED** [review]

**Comment by daschott** [comment]
@marosset or @michmike can you set milestone to v1.20 for this PR please?

**Review by elweb9858 — APPROVED** [review]

File: pkg/proxy/winkernel/proxier_test.go [hunk 3]
```diff
@@ -315,7 +315,329 @@ func TestCreateRemoteEndpointL2Bridge(t *testing.T) {
...
+		makeTestService(svcPortName1.Namespace, svcPortName1.Name, func(svc *v1.Service) {
+			svc.Spec.Type = "NodePort"
+			svc.Spec.ClusterIP = svcIP1
+			svc.Spec.Ports = []v1.ServicePort{{
+				Name:     svcPortName1.Port,
+				Port:     int32(svcPort1),
+				Protocol: v1.ProtocolTCP,
+				NodePort: int32(3003),
+			}}
+		}))
```
[the remark this answers is not in the document]
Comment (sbangari) [reply pkg/proxy/winkernel/proxier_test.go:580]: I did run gofmt on this file already

File: pkg/proxy/winkernel/proxier_test.go [hunk 4]
```diff
@@ -315,7 +315,329 @@ func TestCreateRemoteEndpointL2Bridge(t *testing.T) {
...
+		t.Errorf("RefCount not incremented. Current value: %v", *proxier.endPointsRefCount[guid])
+	}
+
+	if *proxier.endPointsRefCount[guid] != *epInfo.refCount {
+		t.Errorf("Global refCount: %v does not match endpoint refCount: %v", *proxier.endPointsRefCount[guid], *epInfo.refCount)
+	}
+
+	proxier.setInitialized(false)
+
+	proxier.OnServiceUpdate(
```
[the remark this answers is not in the document]
Comment (sbangari) [reply pkg/proxy/winkernel/proxier_test.go:560]: we are updating a field in the service definition here .... in this case we are changing the NodePort for svc1

Old: NodePort: int32(svcNodePort1),
New: NodePort: int32(3003)

[the remark this answers is not in the document]
Comment (elweb9858) [reply pkg/proxy/winkernel/proxier_test.go:560]: gotcha. This PR lgtm

**Review by madhanrm — APPROVED** [review]

**Comment by sbangari** [comment]
@daschott Do you know when we will be able to merge PR's to 1.20?

This PR is still blocked on the error 
"Pending — Not mergeable. Must be in milestone v1.19"

**Comment by daschott** [comment]
@sbangari probably around mid September, but I haven't heard an official date yet. 

@jrsapi Is there an ETA on when SIG-Release determines 1.20 release cycle begin?

**Comment by liggitt** [comment]
see https://groups.google.com/g/kubernetes-dev/c/YXGBa6pxLzo for the plan for reopening development for 1.20

**Comment by liggitt** [comment]
this will be moved back into the milestone as part of the [phased reopen for 1.20 merges](https://docs.google.com/document/d/1yI7o7R2bOB7QtkHUFMHMb5XObiJmzIAnJPuxhdAX-CA/edit)
