### PR TITLE
deprecate created-by annotation for cronjob

### LINKED ISSUE #44407: Deprecate created-by annotation, in favor of ControllerRef
TODOs:

* [x] `kubectl describe` list of controllers for an object.
* [x] `kubectl drain` Pod filtering.
* [x] Classifying failed Pods in e2e test framework.
* [x] CronJob grouping Jobs by owner/creator.
* [ ] Announce deprecation of created-by annotation in the release note

@erictune @enisoc @kow3ns @foxish @kargakis @kubernetes/sig-apps-feature-requests

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**: This PR deprecates created-by annotation for cronjob. This is needed as we now have ControllerRef.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: xref #44407

**Special notes for your reviewer**: I will create 3 PRs to fix the issue as the annotation is used in various parts of the codebase: cronjob, pod drain, and e2e test framework. This is the first PR. Other PRs can be found here: #47471, #47475

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot ok to test

**Comment by janetkuo** [comment]
gofmt verification failed - you need to run `hack/update-gofmt.sh` 
Other test failure looks unrelated

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crimsonfaith91** [comment]
This PR is blocked by flaky `pull-kubernetes-e2e-gce-etcd3` test. Feel free to review it though.

File: pkg/controller/cronjob/utils_test.go [hunk 1]
```diff
@@ -143,6 +149,16 @@ func TestGetParentUIDFromJob(t *testing.T) {
 		// Case 2: Has UID annotation
 		j.ObjectMeta.Annotations = map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"default","name":"pi","uid":"5ef034e0-1890-11e6-8935-42010af0003e","apiVersion":"extensions","resourceVersion":"427339"}}`}
 
+		j.ObjectMeta.SetOwnerReferences([]metav1.OwnerReference{
+			{
+				Kind: "CronJob",
+			},
+		})
+		j.ObjectMeta.SetName("pi")
```
Comment (enisoc) [inline pkg/controller/cronjob/utils_test.go]: Why did you set these other values? I think the test still shouldn't need them.

File: pkg/controller/cronjob/utils_test.go [hunk 2]
```diff
@@ -159,10 +175,46 @@ func TestGroupJobsByParent(t *testing.T) {
 	uid1 := types.UID("11111111-1111-1111-1111-111111111111")
 	uid2 := types.UID("22222222-2222-2222-2222-222222222222")
 	uid3 := types.UID("33333333-3333-3333-3333-333333333333")
-	createdBy1 := map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"x","name":"pi","uid":"11111111-1111-1111-1111-111111111111","apiVersion":"extensions","resourceVersion":"111111"}}`}
-	createdBy2 := map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"x","name":"pi","uid":"22222222-2222-2222-2222-222222222222","apiVersion":"extensions","resourceVersion":"222222"}}`}
-	createdBy3 := map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"y","name":"pi","uid":"33333333-3333-3333-3333-333333333333","apiVersion":"extensions","resourceVersion":"333333"}}`}
-	noCreatedBy := map[string]string{}
+
+	job1 := batchv1.Job{ObjectMeta: metav1.ObjectMeta{
```
Comment (enisoc) [inline pkg/controller/cronjob/utils_test.go]: Creating all the Jobs up here changes the meaning of the test. What you want to create up here is several different values of `OwnerReferences`, which you can then insert into the Jobs that get created below.

File: pkg/controller/cronjob/utils_test.go [hunk 3]
```diff
@@ -176,8 +228,9 @@ func TestGroupJobsByParent(t *testing.T) {
 	{
 		// Case 2: there is one controller with one job it created.
 		js := []batchv1.Job{
-			{ObjectMeta: metav1.ObjectMeta{Name: "a", Namespace: "x", Annotations: createdBy1}},
+			job1,
```
Comment (enisoc) [inline pkg/controller/cronjob/utils_test.go]: You should revert back to the original form for these lines (in particular, letting each one have a different `Name`), but remove `Annotations` and replace it with one of the various `OwnerReferences` you create up top.

File: pkg/controller/cronjob/utils.go [hunk 4]
```diff
@@ -63,17 +63,23 @@ func deleteFromActiveList(sj *batchv2alpha1.CronJob, uid types.UID) {
 
 // getParentUIDFromJob extracts UID of job's parent and whether it was found
 func getParentUIDFromJob(j batchv1.Job) (types.UID, bool) {
-	creatorRefJson, found := j.ObjectMeta.Annotations[v1.CreatedByAnnotation]
-	if !found {
-		glog.V(4).Infof("Job with no created-by annotation, name %s namespace %s", j.Name, j.Namespace)
+	creatorRefJson, err := makeCreatedByRefJson(&j)
```
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils.go]: you are definitely right about this. i found several ways to obtain the same result, and chose a poor one. it is a good lesson for me - i will change my codes accordingly.

File: pkg/controller/cronjob/utils.go [hunk 5]
```diff
@@ -63,17 +63,23 @@ func deleteFromActiveList(sj *batchv2alpha1.CronJob, uid types.UID) {
...
+
+	if err != nil {
+		glog.V(4).Infof("Failed to create object reference, name %s namespace %s: %v", j.Name, j.Namespace, err)
 		return types.UID(""), false
 	}
+
 	var sr v1.SerializedReference
-	err := json.Unmarshal([]byte(creatorRefJson), &sr)
+	err = json.Unmarshal([]byte(creatorRefJson), &sr)
```
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils.go]: yup! i will use `GetControllerOf()` to obtain the deserialized object. thanks for the explanation!

File: pkg/controller/cronjob/utils_test.go [hunk 6]
```diff
@@ -87,17 +87,23 @@ func TestGetJobFromTemplate(t *testing.T) {
 	if len(job.ObjectMeta.Annotations) != 2 {
 		t.Errorf("Wrong number of annotations")
 	}
-	v, ok := job.ObjectMeta.Annotations[v1.CreatedByAnnotation]
+	_, ok := job.ObjectMeta.Annotations[v1.CreatedByAnnotation]
```
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: no, i haven't started working on cronjob at that moment. :)

i removed `v` as i thought annotation testing is unnecessary. after second thought, the annotation testing should still be there. although we do not depend on the annotation anymore, but we still have it at `getJobFromTemplate()`. it is still better to test the annotation.

File: pkg/controller/cronjob/utils_test.go [hunk 7]
```diff
@@ -143,6 +149,16 @@ func TestGetParentUIDFromJob(t *testing.T) {
 		// Case 2: Has UID annotation
 		j.ObjectMeta.Annotations = map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"default","name":"pi","uid":"5ef034e0-1890-11e6-8935-42010af0003e","apiVersion":"extensions","resourceVersion":"427339"}}`}
 
+		j.ObjectMeta.SetOwnerReferences([]metav1.OwnerReference{
+			{
+				Kind: "CronJob",
```
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: noted! good reminder! :)

File: pkg/controller/cronjob/utils_test.go (hunk 1 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: ya, the name is unnecessary. i peeked into attributes of serialized reference, and set all attributes to `j.ObjectMeta`, ensuring i have everything right in the place.

File: pkg/controller/cronjob/utils_test.go (hunk 2 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: ya! rather than having several redundant jobs, a better way is to create several different values of `OwnerReferences`, and plug them to the created jobs.

File: pkg/controller/cronjob/utils_test.go (hunk 3 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: ya, this will work better. the codes will be much more concise.

File: pkg/controller/cronjob/utils.go [hunk 8]
```diff
@@ -63,28 +63,19 @@ func deleteFromActiveList(sj *batchv2alpha1.CronJob, uid types.UID) {
...
-		return types.UID(""), false
-	}
-	var sr v1.SerializedReference
-	err := json.Unmarshal([]byte(creatorRefJson), &sr)
-	if err != nil {
-		glog.V(4).Infof("Job with unparsable created-by annotation, name %s namespace %s: %v", j.Name, j.Namespace, err)
+	controllerRef := controller.GetControllerOf(&j)
+
+	if controllerRef == nil {
+		glog.V(4).Infof("Failed to obtain controller reference, name %s namespace %s", j.Name, j.Namespace)
```
Comment (enisoc) [inline pkg/controller/cronjob/utils.go]: Keep the word `Job` in the log message so it's clear what kind of object we're talking about: `"Job with no ControllerRef, ..."`.

File: pkg/controller/cronjob/utils_test.go [hunk 9]
```diff
@@ -142,6 +144,13 @@ func TestGetParentUIDFromJob(t *testing.T) {
 	{
 		// Case 2: Has UID annotation
 		j.ObjectMeta.Annotations = map[string]string{v1.CreatedByAnnotation: `{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"CronJob","namespace":"default","name":"pi","uid":"5ef034e0-1890-11e6-8935-42010af0003e","apiVersion":"extensions","resourceVersion":"427339"}}`}
```
Comment (enisoc) [inline pkg/controller/cronjob/utils_test.go]: Since we plan to remove the annotation in a later release, we should remove this line to make sure things work without it.

File: pkg/controller/cronjob/utils_test.go [hunk 10]
```diff
@@ -142,6 +144,13 @@ func TestGetParentUIDFromJob(t *testing.T) {
 	{
 		// Case 2: Has UID annotation
```
Comment (enisoc) [inline pkg/controller/cronjob/utils_test.go]: Rename this test case to "Has ControllerRef".

**Review by enisoc — APPROVED** [review]
A few minor comments but LGTM overall.

**Comment by enisoc** [comment]
@soltysh Could you take a look?

File: pkg/controller/cronjob/utils.go (hunk 8 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils.go]: noted!

File: pkg/controller/cronjob/utils_test.go (hunk 10 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: my bad. i should have checked the title.

File: pkg/controller/cronjob/utils_test.go (hunk 9 above)
Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils_test.go]: noted! good point. :)

File: pkg/controller/cronjob/utils.go (hunk 8 above)
Comment (janetkuo) [inline pkg/controller/cronjob/utils.go]: As a side note, CronJob controller lists all jobs, and then find the jobs that are controlled by cronjobs. https://github.com/kubernetes/kubernetes/blob/v1.7.0-beta.2/pkg/controller/cronjob/cronjob_controller.go#L128

Therefore, it's normal to find a job without controller reference here, and thus no need to mention "failed" or "error" in the log.

Comment (crimsonfaith91) [inline pkg/controller/cronjob/utils.go]: got it! i will remove it. :)

**Comment by crimsonfaith91** [comment]
i still have to investigate whether the cronjob does obtain the _same_ list of jobs during cluster version change.

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by janetkuo** [comment]
The e2e test failure is actually relevant. 
```
[k8s.io] CronJob should adopt Jobs it owns that don't have ControllerRef yet 
```
Failed at https://github.com/kubernetes/kubernetes/blob/v1.7.0-beta.2/test/e2e/cronjob.go#L319

Look at how we adopt jobs: https://github.com/kubernetes/kubernetes/blob/v1.7.0-beta.2/pkg/controller/cronjob/cronjob_controller.go#L253 and https://github.com/kubernetes/kubernetes/blob/v1.7.0-beta.2/pkg/controller/cronjob/utils.go#L287-L323

Note that CronJob doesn't use label selector to find its Jobs, instead, it originally uses created-by annotation, and now Controller Ref. Then how does CronJob adopt an orphaned Job?

**Comment by enisoc** [comment]
> Note that CronJob doesn't use label selector to find its Jobs, instead, it originally uses created-by annotation, and now Controller Ref. Then how does CronJob adopt an orphaned Job?

Since we are targeting 1.8, we only have to support upgrading from a 1.6+ master. In that case, it should be safe to remove this e2e test because there should not be anymore CronJob-created Jobs that don't have ControllerRef.

@crimsonfaith91 This is the kind of upgrade concern I mentioned we'll need to think through. It's nice that this one was caught by a test. :) Please continue your work to think through whether we may have other concerns.

**Comment by crimsonfaith91** [comment]
@janetkuo @enisoc Nice catch by the e2e test! I will remove the e2e test.
I am still investigating how the change affects the cronjob to find the jobs. i will use the example of this e2e test to track down others (if any). :)

**Comment by janetkuo** [comment]
> Since we are targeting 1.8, we only have to support upgrading from a 1.6+ master. In that case, it should be safe to remove this e2e test because there should not be anymore CronJob-created Jobs that don't have ControllerRef.

And we don't need `adoptJobs()` anymore.

**Comment by crimsonfaith91** [comment]
noted. i will remove `adoptJobs()` too.

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by crimsonfaith91** [comment]
@enisoc @janetkuo I have investigated the codes within directory `/pkg/controller/cronjob/`, and did not find any part of codes that obtains job list using annotations (after removing `adoptJobs()` and related e2e test). I will continue investigating the parent directory `/pkg/controller` for any sign of annotation usage to obtain the job list.

All the submit-queue tests have passed. We will still have to wait for @soltysh to review the codes though.

**Comment by soltysh** [comment]
Late in the game, but I see other already caught was to be found.

/lgtm
/approve

**Comment by crimsonfaith91** [comment]
@soltysh thank you very much!

**Comment by crimsonfaith91** [comment]
@janetkuo @enisoc I have re-investigated `/pkg/controller/cronjob/` codes, and didn't find any component affected by created-by annotation removal. :)

**Comment by soltysh** [comment]
@crimsonfaith91 mind squashing all your changes into a single commit/

**Comment by crimsonfaith91** [comment]
@soltysh squashed after fixing import paths. :)
