### PR TITLE
apiextensions: commit generated openapi definitions

### LINKED ISSUE #75338: k8s.io/apiextensions-apiserver misses the generated code
**What happened**:

I'm trying to vendor k8s.io/kubernetes/test/e2e, which due to (recently added ?) code in test/e2e/framework/crd_util.go depends on k8s.io/apiextensions-apiserver. The problem now is that the content of k8s.io/apiextensions-apiserver is incomplete:
apiextensions-apiserver/pkg/controller/openapi/builder.go calls generatedopenapi.GetOpenAPIDefinitions, but apiextensions-apiserver/pkg/generated/openapi/ doesn't contain the generated code.

**What you expected to happen**:

I expect k8s.io/apiextensions-apiserver to compile when fetching it with "go get" or vendoring it with tools like "dep".

**How to reproduce it (as minimally and precisely as possible)**:

```
$ go get k8s.io/apiextensions-apiserver
# k8s.io/apiextensions-apiserver/pkg/controller/openapi
../apiextensions-apiserver/pkg/controller/openapi/builder.go:327:16: undefined: "k8s.io/apiextensions-apiserver/pkg/generated/openapi".GetOpenAPIDefinitions
../apiextensions-apiserver/pkg/controller/openapi/builder.go:382:11: undefined: "k8s.io/apiextensions-apiserver/pkg/generated/openapi".GetOpenAPIDefinitions
```

**Environment**:
- Kubernetes version (use `kubectl version`): master

### PR DESCRIPTION
**Pull request by roycaihw**
so the package is complete to compile

the goal is to have a clean workspace when we run any of the following:
- `go get k8s.io/apiextensions-apiserver`
- `make clean` or `make generated_files` when no API change is made
- `hack/verify-generated-files.sh`

fixes #75338

**Special notes for your reviewer**:
- [x] ~need to check if .gitignore and `update-index --assume-unchanged` help~ 
   - there is no repo-level support for `--assume-unchanged`
- [x] in future we want to move code-generation to k8s.io/apiextensions-apiserver (tracked in https://github.com/kubernetes/kubernetes/issues/74976)
- [x] ~presumably #75338 could also happen for `k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go` when you `go get k8s.io/kubernetes`~ 
   - `go get` doesn't try compiling kubernetes because there is no go file in the package

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @liggitt @pohly

### CODE REVIEW

**Comment by liggitt** [comment]
> * presumably #75338 could also happen for `k8s.io/kubernetes/pkg/generated/openapi/zz_generated.openapi.go`

It could, though we explicitly intend the published repos to be consumable as dependencies.

Given the generated extensions openapi file is slow moving (only has autoscaling and metadata fields), relatively small, and is unlikely to be a conflict target, should we commit it (switch the .gitignore file to `/pkg/generated/openapi/zz_generated.openapi.go`)?

**Comment by roycaihw** [comment]
> should we commit it?

@liggitt I just made the change and updated the first comment :) waiting for test results

**Comment by roycaihw** [comment]
this pr is ready for review. Please take a look

tested locally that `go build k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver` works

**Comment by pohly** [comment]
I've no idea whether this PR does what it says it does, so I have to punt on reviewing it.

I was a bit worried when an older revision said "commit dummy function declaration for ignored generated file". That didn't sound right, because the expectation is that the exported content works the same way as in Kubernetes itself.

But including the generated source code in the repo and mirroring it looks good to me.

File: hack/verify-godeps.sh [hunk 1]
```diff
@@ -101,7 +101,7 @@ pushd "${KUBE_ROOT}" > /dev/null 2>&1
     ret=1
   fi
 
-  if ! _out="$(diff -Naupr -x "BUILD" -x "zz_generated.openapi.go" -x "AUTHORS*" -x "CONTRIBUTORS*" vendor "${_kubetmp}/vendor")"; then
```
Comment (lavalamp) [inline hack/verify-godeps.sh]: Won't this affect every file with that name? We have more than one, correct?

**Comment by lavalamp** [comment]
This is really gross, but I don't have any better ideas :(

File: hack/verify-godeps.sh (hunk 1 above)
Comment (liggitt) [reply hack/verify-godeps.sh]: this is the only one under staging, and if we had others, we'd want to publish them as well (we shouldn't make published staging repos depend on build processes inside k/k)

Comment (lavalamp) [reply hack/verify-godeps.sh]: OK. It's not at all obvious that this command is constrained to the staging directory.

If the intent is to get everything in staging (which I agree with) then the path in the other diffs is overly specific.

File: hack/make-rules/clean.sh [hunk 2]
```diff
@@ -24,7 +24,7 @@ source "${KUBE_ROOT}/hack/lib/util.sh"
 CLEAN_PATTERNS=(
   "_tmp"
   "doc_tmp"
-  ".*/zz_generated.openapi.go"
+  "((?!staging\/src\/k8s\.io\/apiextensions-apiserver\/pkg\/generated\/openapi).)*/zz_generated.openapi.go"
```
Comment (lavalamp) [inline hack/make-rules/clean.sh]: A nit which doesn't really matter since we only have one of these in staging: this path should probably be general enough to find everything the diff is going to consider. (same in the .gitignore file)

File: hack/verify-godeps.sh (hunk 1 above)
Comment (roycaihw) [reply hack/verify-godeps.sh]: this line (verify-godeps.sh) is undoing https://github.com/kubernetes/kubernetes/pull/75184. The script's intent is to make sure the checked-in staging/vendor code is the same as a fresh `godep restore&save` (with whatever build process running in serial/parallel). https://github.com/kubernetes/kubernetes/pull/75184 added an exception for that uncommitted openapi definitions to make the script pass. We withdraw the exception as we commit that openapi now

the intent for the rest changes is to commit that generated openapi so `go get/build k8s.io/apiextensions-apiserver` doesn't fail #75338.

the diffs were specific because I didn't want to advocate committing more generated files, but we probably have to do the same for sample-apiserver https://github.com/kubernetes/kubernetes/pull/74133 in future. 

> if we had others, we'd want to publish them as well

I agree now. We have to commit all files for the staging repos to be consumed as dependencies.

**Comment by roycaihw** [comment]
> This is really gross, but I don't have any better ideas :(

I think this is the same problem as https://github.com/kubernetes/kubernetes/pull/29017
