### PR TITLE
remove stale OutOfDisk condition from kubelet side

### LINKED ISSUE #72485: 1.12 kubelet upgraded to 1.13 leaves stale OutOfDisk condition
**What happened**:

https://github.com/kubernetes/kubernetes/pull/70111 removed reporting of the OutOfDisk condition in the kubelet.

A 1.12 kubelet upgraded to a 1.13 kubelet leaves the previously reported OutOfDisk condition in place, and it eventually gets switched to Unknown status.

**What you expected to happen**:

If this condition is no longer reported, it should be removed by the kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run a 1.12 kubelet, let it report OutOfDisk condition status.
2. Upgrade to 1.13
3. Note the condition is no longer updated
4. After a while, the node controller flips the status to Unknown

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig node

### PR DESCRIPTION
**Pull request by dixudx**
**What type of PR is this?**
Remove stale node condition OutOfDisk

**What this PR does / why we need it**:

Node condition OutOfDisk has been removed starting from v1.13

A 1.12 kubelet upgraded to a 1.13 kubelet leaves the previously reported OutOfDisk condition in place, and it eventually gets switched to Unknown status.

We should cherry pick this to v1.13.

**Which issue(s) this PR fixes**:

Fixes #72485

**Special notes for your reviewer**:
/cc liggitt resouer 
/cc kubernetes/sig-node-bugs 

**Does this PR introduce a user-facing change?**:

```release-note
remove stale OutOfDisk condition from kubelet side
```

Signed-off-by: stephen.xd@alibaba-inc.com

### CODE REVIEW

**Comment by changyaowei** [comment]
LGTM

File: pkg/kubelet/kubelet_node_status.go [hunk 1]
```diff
@@ -474,6 +475,24 @@ func (kl *Kubelet) recordNodeSchedulableEvent(node *v1.Node) error {
...
 // refactor the node status condition code out to a different file.
 func (kl *Kubelet) setNodeStatus(node *v1.Node) {
+	// TODO(dixudx): remove this in v1.14
+	// OutOfDisk condition has been removed from kubelet in 1.12
+	// For legacy node conditions, this should be removed when upgrading
+	if version.Get().Major == "1" && version.Get().Minor > "12" {
+		var conditions []v1.NodeCondition
+		var hasOutOfDisk bool
+		for i := range node.Status.Conditions {
+			if node.Status.Conditions[i].Type != v1.NodeOutOfDisk {
```
Comment (zhangxiaoyu-zidif) [inline pkg/kubelet/kubelet_node_status.go]: v1.NodeOutOfDisk -> a local const.
considered that v1.NodeOutOfDisk maybe removed.

Comment (dixudx) [reply pkg/kubelet/kubelet_node_status.go]: @zhangxiaoyu-zidif `v1.NodeOutOfDisk` should be removed together in the future, e.g. v1.14.

File: pkg/kubelet/kubelet_node_status.go [hunk 2]
```diff
@@ -474,6 +475,24 @@ func (kl *Kubelet) recordNodeSchedulableEvent(node *v1.Node) error {
 // TODO(madhusudancs): Simplify the logic for setting node conditions and
 // refactor the node status condition code out to a different file.
 func (kl *Kubelet) setNodeStatus(node *v1.Node) {
+	// TODO(dixudx): remove this in v1.14
```
Comment (zhangxiaoyu-zidif) [inline pkg/kubelet/kubelet_node_status.go]: why remove in v1.14？ this may occur in Ever release version upgrade later than 1.13.

Comment (dixudx) [reply pkg/kubelet/kubelet_node_status.go]: @zhangxiaoyu-zidif We do not recommend upgrading more than two minor releases at a time (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#upgrades).

File: pkg/kubelet/kubelet_node_status.go [hunk 3]
```diff
@@ -474,6 +475,24 @@ func (kl *Kubelet) recordNodeSchedulableEvent(node *v1.Node) error {
...
+	// OutOfDisk condition has been removed from kubelet in 1.12
+	// For legacy node conditions, this should be removed when upgrading
+	if version.Get().Major == "1" && version.Get().Minor > "12" {
```
Comment (dashpole) [inline pkg/kubelet/kubelet_node_status.go]: Why do we need a version guard here?  We should only be cherry-picking back to 1.13, so this should always evaluate to true.

File: pkg/kubelet/kubelet_node_status.go [hunk 4]
```diff
@@ -474,6 +475,24 @@ func (kl *Kubelet) recordNodeSchedulableEvent(node *v1.Node) error {
...
+		var hasOutOfDisk bool
+		for i := range node.Status.Conditions {
+			if node.Status.Conditions[i].Type != v1.NodeOutOfDisk {
+				conditions = append(conditions, node.Status.Conditions[i])
+			} else {
+				hasOutOfDisk = true
+			}
+		}
+		if hasOutOfDisk {
+			node.Status.Conditions = conditions
```
Comment (dashpole) [inline pkg/kubelet/kubelet_node_status.go]: Can we always set conditions, and remove `hasOutOfDisk`?

File: pkg/kubelet/kubelet_node_status.go (hunk 3 above)
Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: agree, no version check necessary

Comment (dixudx) [reply pkg/kubelet/kubelet_node_status.go]: @dashpole @liggitt Addressed. PTAL. Thanks.

File: pkg/kubelet/kubelet_node_status.go [hunk 5]
```diff
@@ -474,6 +474,17 @@ func (kl *Kubelet) recordNodeSchedulableEvent(node *v1.Node) error {
 // TODO(madhusudancs): Simplify the logic for setting node conditions and
 // refactor the node status condition code out to a different file.
 func (kl *Kubelet) setNodeStatus(node *v1.Node) {
+	// TODO(dixudx): remove this in v1.14
```
Comment (liggitt) [inline pkg/kubelet/kubelet_node_status.go]: rather than adding specific logic into this method, move this into a `nodestatus.RemoveOutOfDiskCondition` node status func and add to the list here:

https://github.com/kubernetes/kubernetes/blob/62e8a1bf40a22680fe19a84addad4972deb1d846/pkg/kubelet/kubelet_node_status.go#L521-L532

Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: also needs a unit test

Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: and could be commented to be removed in 1.16 (skip-level kubelet upgrades are permitted), or could be left indefinitely without harm

**Review by resouer — COMMENTED** [review]
We do need a test to verify the change @dixudx

File: pkg/kubelet/kubelet_node_status.go (hunk 5 above)
Comment (dixudx) [reply pkg/kubelet/kubelet_node_status.go]: @liggitt Done. PTAL.

**Comment by dixudx** [comment]
Flaky tests here. Will retest it when the CI becomes happy.

**Comment by liggitt** [comment]
looks good to me structurally

will leave to @kubernetes/sig-node-pr-reviews for lgtm/approval

**Comment by dixudx** [comment]
ping @kubernetes/sig-node-pr-reviews for approval. Thanks.
