### PR TITLE
Fix projected volume test clean up

### LINKED ISSUE #79922: Protected_test.go do not remove tempdir when test finished
**What happened**:

I run the unit tests for project.go, but I found it would not clean the tempdir it created.
image

**What you expected to happen**:

automatically clean up when finishing unit tests.

**How to reproduce it (as minimally and precisely as possible)**:

go test $GOPATH/k8s.io/kubernetes/pkg/volume projected_test.go

**Anything else we need to know?**:

**Environment**: k8s 1.15
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:

clean up when finishing unit tests

**Which issue(s) this PR fixes**:

Fixes #79922

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I suggest remove `kind/bug` lable, it's related to a `kind/cleanup` i think.

**Comment by RainbowMango** [comment]
Please correct me if i'm wrong.
/remove-kind bug

File: pkg/volume/projected/projected_test.go [hunk 1]
```diff
@@ -258,8 +258,8 @@ func TestCollectDataWithSecret(t *testing.T) {
 		testPodUID := types.UID("test_pod_uid")
 		pod := &v1.Pod{ObjectMeta: metav1.ObjectMeta{Namespace: testNamespace, UID: testPodUID}}
 		client := fake.NewSimpleClientset(tc.secret)
-		_, host := newTestHost(t, client)
-
+		tempDir, host := newTestHost(t, client)
```
Comment (msau42) [inline pkg/volume/projected/projected_test.go]: Can we use `t.Run(tc.name, func(t *testing.T)` to iterate over the test cases?  That way all variables created are enclosed in a single run and get cleaned up after each run instead of only at the very end of all the test cases.

Comment (cwdsuzhou) [reply pkg/volume/projected/projected_test.go]: done, thanks

**Comment by msau42** [comment]
/lgtm
Thanks!
