### PR TITLE
Deflake TestRequestExecuteRemoteCommand

### LINKED ISSUE #9119: Flaky test: TestRequestExecuteRemoteCommand
A test is flaky.  

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/65002732

--- FAIL: TestRequestExecuteRemoteCommand (0.04 seconds)
	remotecommand_test.go:207: 1: expected true, got false: <nil>
FAIL

This is with go1.3, though I suspect it is not version-related.
This is during race testing, but there is not a specific message about a race being detected.  Probably things are happening in a different order, causing a test expectation to fail.
This is also during coverage measurement, which might also affect timing. 

Please try running this test many times to see if it fails again, and then fix it.  Run with race detection and coverage if needed to repro.

### PR DESCRIPTION
**Pull request by ncdc**
1 of the test cases in `TestRequestExecuteRemoteCommand` attempts to ensure that if there is an error message transmitted over the error stream, the call to `Execute` returns an `error` with the message. This test has been flaky because the order in which data is read from the stdout, stderr, and error streams is non-deterministic. It was possible for stdout and stderr to finish first, in which case `Execute` would return no error.

This change forces the stdout and stderr reads to go quite slowly, allowing the error stream to return its data first.

Fixes #9119

### CODE REVIEW

**Comment by lavalamp** [comment]
add to whitelist

File: pkg/client/remotecommand/remotecommand_test.go [hunk 1]
```diff
@@ -98,13 +108,17 @@ func (c *fakeUpgradeConnection) SetIdleTimeout(timeout time.Duration) {
...
-	readCalled  bool
-	writeCalled bool
-	dataWritten []byte
-	closeCalled bool
-	resetCalled bool
-	data        string
-	lock        sync.Mutex
+	readCalled        bool
+	writeCalled       bool
+	dataWritten       []byte
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Why the custom implementation? Is there a reason why bytes.Buffer won't work?

File: pkg/client/remotecommand/remotecommand_test.go [hunk 2]
```diff
@@ -112,8 +126,41 @@ func (s *fakeUpgradeStream) Read(p []byte) (int, error) {
 	defer s.lock.Unlock()
 	s.readCalled = true
 	b := []byte(s.data)
-	n := copy(p, b)
-	return n, io.EOF
+
+	// resume reading where we left off
+	start := s.index
+
+	// default to 10 bytes per invocation
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Is this really a good analog of the "real" upgrade stream object? I suspect not?

File: pkg/client/remotecommand/remotecommand_test.go [hunk 3]
```diff
@@ -112,8 +126,41 @@ func (s *fakeUpgradeStream) Read(p []byte) (int, error) {
...
+		// return EOF
+		err = io.EOF
+	}
+
+	n := copy(p, b[start:end])
+
+	// bookmark our position
+	s.index = end
+
+	// sleep if necessary
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Why would sleep ever be necessary?

File: pkg/client/remotecommand/remotecommand_test.go [hunk 4]
```diff
@@ -62,16 +66,22 @@ func (c *fakeUpgradeConnection) CreateStream(headers http.Header) (httpstream.St
 	c.lock.Lock()
 	defer c.lock.Unlock()
 
-	stream := &fakeUpgradeStream{}
+	stream := &fakeUpgradeStream{
+		closeChan: make(chan struct{}, 10),
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Why 10? The fact that this isn't 0 makes me pretty sure that your Reset/Close calls are not idempotent. Should they be?

File: pkg/client/remotecommand/remotecommand_test.go [hunk 5]
```diff
@@ -126,6 +173,9 @@ func (s *fakeUpgradeStream) Write(p []byte) (int, error) {
 }
 
 func (s *fakeUpgradeStream) Close() error {
+	// send to the channel outside of the lock so we can unblock Read
+	s.closeChan <- struct{}{}
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Non-blocking write, to make this idempotent:

```
select {
case s.closeChan <- struct{}{}:
default:
}
```

File: pkg/client/remotecommand/remotecommand_test.go [hunk 6]
```diff
@@ -133,6 +183,9 @@ func (s *fakeUpgradeStream) Close() error {
 }
 
 func (s *fakeUpgradeStream) Reset() error {
+	// send to the channel outside of the lock so we can unblock Read
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: I'm always skeptical of code that uses both locks and channels. :)

File: pkg/client/remotecommand/remotecommand_test.go [hunk 7]
```diff
@@ -185,6 +238,12 @@ func TestRequestExecuteRemoteCommand(t *testing.T) {
 	for i, testCase := range testCases {
 		if testCase.Error != "" {
 			testCase.Upgrader.conn.errorData = testCase.Error
+
+			// force the stdout and stderr streams to be "slow"
+			testCase.Upgrader.conn.stdoutBytesPerRead = 1
+			testCase.Upgrader.conn.stdoutReadSleepDuration = 5 * time.Second
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Is it possible to just delay writing?

File: pkg/client/remotecommand/remotecommand_test.go (hunk 1 above)
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Another alternative is to use an os.Pipe().

**Comment by lavalamp** [comment]
I think a lot of my skepticism here is due to the original code and not your changes in this PR. But I'm having a hard time believing that this fake is a good analog for the real thing. Is it possible to use the real object?

File: pkg/client/remotecommand/remotecommand_test.go (hunk 6 above)
Comment (ncdc) [inline pkg/client/remotecommand/remotecommand_test.go]: It's been a long time since I wrote the original tests and the fake structs to go along with them, but the data race detector kept finding races when I had no locks.

**Comment by ncdc** [comment]
@lavalamp let me see what I can do with the real stream objects, if anything.

**Comment by ncdc** [comment]
@lavalamp does this look any better? I ripped out all the fake upgrade code and replaced it with an `httptest.Server` that mimics what the Kubelet does when handling an exec request. If you like it, I will squash down to 1 commit.

**Comment by ncdc** [comment]
Assuming something along these lines is good, I can do a similar change for the port forward tests.

File: pkg/client/remotecommand/remotecommand_test.go [hunk 8]
```diff
@@ -18,271 +18,171 @@ package remotecommand
...
+		if !testCase.Tty {
+			// stderr
+			expectedStreams++
 		}
 
-		conn := testCase.Upgrader.conn
-		if testCase.Error != "" {
-			if conn.errorStream == nil {
-				t.Fatalf("%d: expected error stream creation", i)
+		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
```
Comment (lavalamp) [inline pkg/client/remotecommand/remotecommand_test.go]: Is the body of this server copied from somewhere? Can it be factored out into a common function/type?

If not, can it be separated from the body of this test for readability?

Comment (ncdc) [inline pkg/client/remotecommand/remotecommand_test.go]: It's from `handleExec` Kubelet's server.go, modified for testing. I can definitely split it out for readability, but I'm not sure it could be shared w/the Kubelet.

**Comment by lavalamp** [comment]
Yeah, this is an improvement, thanks. Still wondering if it can be improved further, though :)

Sorry for the slow responses, should be a bit faster now that we're entering code thaw ;)

**Comment by ncdc** [comment]
@lavalamp server code split out, code squashed.

**Comment by lavalamp** [comment]
LGTM, sorry for delay
