### PR TITLE
Validate verb in auth can-i command

### LINKED ISSUE #95471: kubectl auth can-i doesn't validate verb
**What happened**:
When using kubectl auth can-i <verb> <resources> the "verb" isn't check and returns yes on any resource regardless of what the verb is.

**What you expected to happen**:
I expected the cli to register an error like when you don't have enough arguments.

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl auth can-i dfkajfdlfjk pods  
yes
```

**Anything else we need to know?**:
`none`

**Environment**:
- Kubernetes version (use `kubectl version`): client version GitVersion: 1.19.2 server version: GitVersion: 1.19.0
- Cloud provider or hardware configuration: Mac OS X
- OS (e.g: `cat /etc/os-release`):  n/a
- Kernel (e.g. `uname -a`): Darwin 
- Install tools: brew 
- Network plugin and version (if this is a network-related bug): n/a
- Others: `none`

### PR DESCRIPTION
**Pull request by troy0820**
**What type of PR is this?**
Fixes issue #95471

/kind bug

**What this PR does / why we need it**:
This will ensure that the validation of the verb used in `kubectl auth can-i ` is in fact a Kubernetes verb and doesn't respond yes to anything inputted before the resource in the query.  _(Currently you can put anything before e.g pods and it will respond yes.)_

**Which issue(s) this PR fixes**:

Fixes #95471

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

Allowing arbitrary verbs in permission checks is intentional (see comment on the linked issue). Doing something similar to what is done for resources could make sense though. Having a list of known verbs, and warning but continuing with checks of unrecognized verbs would surface typos without blocking currently supported uses.

File: pkg/kubectl/cmd/auth/cani.go [hunk 1]
```diff
@@ -393,3 +395,13 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
 
 	return false, fmt.Errorf("the server doesn't have a resource type '%s' in group '%s'", gvr.Resource, gvr.Group)
 }
+
+func isVerb(s string) error {
+	verbs := []string{"create", "watch", "post", "put", "list", "get", "delete", "deletecollection", "update", "patch"}
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:400]: suggest one check/warning for nonResourceURL checks: get, put, post, head, options, delete, patch

and another check/warning for resource verbs:
* standard crud resource verbs (get, list, watch, create, update, patch, delete, deletecollection)
* known special verbs: use, bind, escalate, `*`

File: pkg/kubectl/cmd/auth/cani.go [hunk 2]
```diff
@@ -393,3 +395,13 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
...
+	for _, verb := range verbs {
+		if strings.ToLower(s) == verb {
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:402]: if we're trying to warn about possible typos, I wouldn't change case of the specified verb… a case-mismatch would affect authz checks

File: pkg/kubectl/cmd/auth/cani.go [hunk 3]
```diff
@@ -393,3 +395,13 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
...
+			return nil
+		}
+	}
+	return fmt.Errorf("the verb %s is not a kubernetes verb", s)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:406]: make the warning similar to the warning presented for unknown resources

File: pkg/kubectl/cmd/auth/cani.go [hunk 4]
```diff
@@ -193,7 +193,10 @@ func (o *CanIOptions) Validate() error {
 		}
 		return nil
 	}
-
+	err := isVerb(o.Verb)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:196]: do distinct checks depending on whether we're checking resource or nonResourceURL permissions. warn, but continue on unknown verbs

File: pkg/kubectl/cmd/auth/cani.go [hunk 5]
```diff
@@ -201,6 +201,9 @@ func (o *CanIOptions) Validate() error {
 		if o.Resource != (schema.GroupVersionResource{}) || o.ResourceName != "" {
 			return fmt.Errorf("NonResourceURL and ResourceName can not specified together")
 		}
+		if !isVerb(o) {
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:204]:
```suggestion
		if !isKnownNonResourceVerb(o) {
```

File: pkg/kubectl/cmd/auth/cani.go [hunk 6]
```diff
@@ -209,6 +212,10 @@ func (o *CanIOptions) Validate() error {
 				fmt.Fprintf(o.ErrOut, "Warning: resource '%s' is not namespace scoped in group '%s'\n", o.Resource.Resource, o.Resource.Group)
 			}
 		}
+		if !isVerb(o) {
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:215]:
```suggestion
		if !isKnownResourceVerb(o) {
```

File: pkg/kubectl/cmd/auth/cani.go [hunk 7]
```diff
@@ -393,3 +399,22 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
 
 	return false, fmt.Errorf("the server doesn't have a resource type '%s' in group '%s'", gvr.Resource, gvr.Group)
 }
+
+func isVerb(o *CanIOptions) bool {
+	nonResourceURLVerbs := []string{"get", "put", " post", "head", "options", "delete", " patch"}
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:404]: * split these to `isKnownNonResourceVerb`
* there are typos with leading spaces in the post and patch strings

File: pkg/kubectl/cmd/auth/cani.go [hunk 8]
```diff
@@ -393,3 +399,22 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
...
+	resourceVerbs := []string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection", "use", "bind", "impersonate", "*"}
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:405]: split these to `isKnownResourceVerb`

File: pkg/kubectl/cmd/auth/cani.go (hunk 7 above)
Comment (liggitt) [reply pkg/kubectl/cmd/auth/cani.go:404]: can construct package variable `nonResourceURLVerbs := sets.NewString(...)` and do `nonResourceURLVerbs.Has(verb)`

File: pkg/kubectl/cmd/auth/cani.go [hunk 9]
```diff
@@ -393,3 +399,22 @@ func isNamespaced(gvr schema.GroupVersionResource, discoveryClient discovery.Dis
...
+
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:406]: can construct package variable `resourceVerbs := sets.NewString(...)` and do `resourceVerbs.Has(verb)`

File: pkg/kubectl/cmd/auth/cani.go [hunk 10]
```diff
@@ -209,6 +212,10 @@ func (o *CanIOptions) Validate() error {
 				fmt.Fprintf(o.ErrOut, "Warning: resource '%s' is not namespace scoped in group '%s'\n", o.Resource.Resource, o.Resource.Group)
 			}
 		}
+		if !isVerb(o) {
+			fmt.Fprintf(o.ErrOut, "Warning: verb %s is not a kubernetes verb\n", o.Verb)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:216]:
```suggestion
			fmt.Fprintf(o.ErrOut, "Warning: verb '%s' is not a known verb\n", o.Verb)
```

File: pkg/kubectl/cmd/auth/cani.go [hunk 11]
```diff
@@ -201,6 +201,9 @@ func (o *CanIOptions) Validate() error {
 		if o.Resource != (schema.GroupVersionResource{}) || o.ResourceName != "" {
 			return fmt.Errorf("NonResourceURL and ResourceName can not specified together")
 		}
+		if !isVerb(o) {
+			fmt.Fprintf(o.ErrOut, "Warning: verb %s is not a kubernetes verb\n", o.Verb)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:205]:
```suggestion
			fmt.Fprintf(o.ErrOut, "Warning: verb '%s' is not a known verb\n", o.Verb)
```

**Review by liggitt — COMMENTED** [review]
consider including the known verbs in the long help output

File: pkg/kubectl/cmd/auth/cani.go [hunk 12]
```diff
@@ -201,6 +205,9 @@ func (o *CanIOptions) Validate() error {
 		if o.Resource != (schema.GroupVersionResource{}) || o.ResourceName != "" {
 			return fmt.Errorf("NonResourceURL and ResourceName can not specified together")
 		}
+		if !isKnownNonResourceVerb(o.Verb) {
+			fmt.Fprintf(o.ErrOut, "Warning: verb %s is not a known verb\n", o.Verb)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:209]: to make any whitespace issues clearer:

```suggestion
			fmt.Fprintf(o.ErrOut, "Warning: verb '%s' is not a known verb\n", o.Verb)
```

File: pkg/kubectl/cmd/auth/cani.go [hunk 13]
```diff
@@ -209,6 +216,10 @@ func (o *CanIOptions) Validate() error {
 				fmt.Fprintf(o.ErrOut, "Warning: resource '%s' is not namespace scoped in group '%s'\n", o.Resource.Resource, o.Resource.Group)
 			}
 		}
+		if !isKnownResourceVerb(o.Verb) {
+			fmt.Fprintf(o.ErrOut, "Warning: verb %s is not a known verb\n", o.Verb)
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:220]: to make any whitespace issues clearer:
```suggestion
			fmt.Fprintf(o.ErrOut, "Warning: verb '%s' is not a known verb\n", o.Verb)
```

File: pkg/kubectl/cmd/auth/cani.go [hunk 14]
```diff
@@ -94,6 +95,9 @@ var (
 
 		# List all allowed actions in namespace "foo"
 		kubectl auth can-i --list --namespace=foo`)
+
+	resourceVerbs       = sets.NewString("get", "list", "watch", "create", "update", "patch", "delete", "deletecollection", "use", "bind", "impersonate", "*")
+	nonResourceURLVerbs = sets.NewString("get", "put", "post", "head", "options", "delete", "patch")
```
Comment (liggitt) [inline pkg/kubectl/cmd/auth/cani.go:100]: include `*` in this list as well, in case someone was going to check if they had superuser permissions on non-resource URLs

**Review by liggitt — COMMENTED** [review]
a couple last comments, squash commits, then lgtm

**Comment by troy0820** [comment]
Thanks @liggitt commits squashed and suggestions applied.

**Comment by troy0820** [comment]
@liggitt tests were failing, I'm not sure if they were flakes but I ran the `hack/update-vendor` script.  So this needs a `lgtm` label again

File: vendor/OWNERS [hunk 15]
```diff
@@ -1,4 +0,0 @@
-# See the OWNERS docs at https://go.k8s.io/owners
-
-approvers:
-- dep-approvers
```
Comment (liggitt) [inline vendor/OWNERS:4]: revert the change to this file

**Comment by troy0820** [comment]
@liggitt is this a flake? Running into issues trying to get this to pass.

**Comment by liggitt** [comment]
looks like CI infra error:

> RESOURCE_POOL_EXHAUSTED_WITH_DETAILS Location: Message:The zone 'projects/k8s-infra-e2e-boskos-044/zones/us-west1-b' does not have enough resources available to fulfill the request.

just leave the PR alone, the bot will kick retest and once the error is resolved this will merge

/lgtm
