### PR TITLE
order sandbox by attempt or create time

### LINKED ISSUE #126514: You have to remove that sandbox to be able to reuse that name.
### What happened?

When power is turned off and restarted, `kubelet `reports an error when starting etcd and apiserver:
Aug 02 10:01:03 openEuler kubelet[1024]: E0802 10:01:03.693078    1024 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = Conflict. The name \"k8s_POD_etcd-openeuler_kube-system_ae0fcba533f9b951c6983487becf13f9_0\" is already in use by sandbox 30ed179087f03d03fef197363103427e48242829f815488bb774313db02c41a4. You have to remove that sandbox to be able to reuse that name."
Aug 02 10:01:03 openEuler kubelet[1024]: E0802 10:01:03.693228    1024 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = Conflict. The name \"k8s_POD_etcd-openeuler_kube-system_ae0fcba533f9b951c6983487becf13f9_0\" is already in use by sandbox 30ed179087f03d03fef197363103427e48242829f815488bb774313db02c41a4. You have to remove that sandbox to be able to reuse that name." pod="kube-system/etcd-openeuler"
Aug 02 10:01:03 openEuler kubelet[1024]: E0802 10:01:03.693276    1024 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = Conflict. The name \"k8s_POD_etcd-openeuler_kube-system_ae0fcba533f9b951c6983487becf13f9_0\" is already in use by sandbox 30ed179087f03d03fef197363103427e48242829f815488bb774313db02c41a4. You have to remove that sandbox to be able to reuse that name." pod="kube-system/etcd-openeuler"
Aug 02 10:01:03 openEuler kubelet[1024]: E0802 10:01:03.693400    1024 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-openeuler_kube-system(ae0fcba533f9b951c6983487becf13f9)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"etcd-openeuler_kube-system(ae0fcba533f9b951c6983487becf13f9)\\\": rpc error: code = Unknown desc = Conflict. The name \\\"k8s_POD_etcd-openeuler_kube-system_ae0fcba533f9b951c6983487becf13f9_0\\\" is already in use by sandbox 30ed179087f03d03fef197363103427e48242829f815488bb774313db02c41a4. You have to remove that sandbox to be able to reuse that name.\"" pod="kube-system/etcd-openeuler" podUID="ae0fcba533f9b951c6983487becf13f9"
Aug 02 10:01:04 openEuler kubelet[1024]: E0802 10:01:04.276824    1024 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"ae0fcba533f9b951c6983487becf13f9\" with KillPodSandboxError: \"rpc error: code = Unknown desc = You cannot stop container d5c60843291be7385fc0377c625582ccbc83715e6ae7614533cd21f7e313a50f in garbage collector progress.\"" pod="kube-system/etcd-openeuler" podUID="ae0fcba533f9b951c6983487becf13f9"
Aug 02 10:01:09 openEuler kubelet[1024]: E0802 10:01:09.888481    1024 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"ae0fcba533f9b951c6983487becf13f9\" with KillPodSandboxError: \"rpc error: code = Unknown desc = You cannot stop container d5c60843291be7385fc0377c625582ccbc83715e6ae7614533cd21f7e313a50f in garbage collector progress.\"" pod="kube-system/etcd-openeuler" podUID="ae0fcba533f9b951c6983487becf13f9"
Aug 02 10:01:11 openEuler kubelet[1024]: E0802 10:01:11.199099    1024 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"ae0fcba533f9b951c6983487becf13f9\" with KillPodSandboxError: \"rpc error: code = Unknown desc = You cannot stop container d5c60843291be7385fc0377c625582ccbc83715e6ae7614533cd21f7e313a50f in garbage collector progress.\"" pod="kube-system/etcd-openeuler" podUID="ae0fcba533f9b951c6983487becf13f9"
Aug 02 10:01:23 openEuler kubelet[1024]: E0802 10:01:23.335772    1024 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"ae0fcba533f9b951c6983487becf13f9\" with KillPodSandboxError: \"rpc error: code = Unknown desc = You cannot stop container d5c60843291be7385fc0377c625582ccbc83715e6ae7614533cd21f7e313a50f in garbage collector progress.\"" pod="kube-system/etcd-openeuler" podUID="ae0fcba533f9b951c6983487becf13f9"

### What did you expect to happen?

Once the above error is reported, the startup of etcd and apiserver will be delayed, and this bug will affect the startup speed of the business pod.

### How can we reproduce it (as minimally and precisely as possible)?

After deploying `k8s v1.30.3`, turn on the `EventedPLEG` feature, power off and restart.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
k8s v1.30.3
</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>
openeuler 22.03 LTS
arm64

Linux edgenode06 5.10.0 #7 SMP Sat Jun 10 13:37:24 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
isulad v2.1.5
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yylt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This issue is caused by system clock rollback, which is prone to occur during system startup, especially when NTP starts around static pods.

**Detailed Reproduction Steps:**

1.  **Set up a node:**  Install a Kubernetes node using kubeadm and cri-o. Refer to the tutorial: [https://github.com/cri-o/cri-o/blob/main/tutorials/kubeadm.md](https://github.com/cri-o/cri-o/blob/main/tutorials/kubeadm.md)
2.  **Stop NTP Service:** Stop the NTP service (or chrony, systemd-timesyncd) on the node.
    ```bash
    systemctl stop ntp  // or chrony, systemd-timesyncd
    ```
3.  **Create a Busybox Deployment:** Deploy a simple busybox deployment in the Kubernetes cluster.
    ```bash
    kubectl create -f busybox-deploy
    ```
4.  **Simulate Clock Rollback:** Set the system date back to the epoch start (or a very early time) to simulate a clock rollback.
    ```bash
    date -s '0:0:0'
    ```
5.  **Stop the Busybox Pod (Initial Stop):** Stop the busybox pod using `crictl`.
    ```bash
    crictl stopp $(crictl pods |grep -w busybox|awk '{print $1}')
    ```
6.  **Start NTP Service:** Start the NTP service (or chrony, systemd-timesyncd) on the node.
    ```bash
    systemctl start ntp  // or chrony, systemd-timesyncd
    ```
7.  **Stop the Busybox Pod (Second Stop):** Stop the busybox pod again using `crictl`.
    ```bash
    crictl stopp $(crictl pods |grep -w busybox|awk '{print $1}')
    ```
8. **Log crio sevice**
    ```bash
    journalctl -eu crio --no-pager -ocat
    ...
    time="2025-03-11T04:48:10.760615237Z" level=info msg="Running pod sandbox: default/busybox-74c5fcfb8-5kbmh/POD" id=07cdd735-da9d-4217-8987-bbac8656f566 name=/runtime.v1.RuntimeService/RunPodSandbox
    time="2025-03-11T04:48:10.76067006Z" level=warning msg="error reserving pod name k8s_busybox-74c5fcfb8-5kbmh_default_240ce90c-efe1-432b-aae0-88006b9ff369_2 for id 5d0d17bf66724375923d4467c4869bc822a6151195573e9e3afb418b0f302066: name is reserved
    ...
    ```
Making kubelet dependent on time services like NTP during system startup is unnecessary. 

It's would be a more convenient and robust approach if kubelet use logical time to determine the number of sandbox creations 

This could potentially mitigate issues arising from clock rollback, especially in scenarios where NTP synchronization is delayed or fails during early system boot.

#### Which issue(s) this PR fixes:

Fixes #126514

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yylt** [comment]
/cc @feiskyer 

More information could be seen:

- https://github.com/containerd/containerd/issues/9459

Similar issues:

- https://github.com/kubernetes/kubernetes/issues/123139
- https://github.com/kubernetes/kubernetes/issues/126514

**Comment by pacoxu** [comment]
/ok-to-test
/assign @klueska
for approval

File: pkg/kubelet/kuberuntime/helpers.go [hunk 1]
```diff
@@ -47,9 +47,14 @@ func (b containersByID) Less(i, j int) bool { return b[i].ID.ID < b[j].ID.ID }
...
-func (p podSandboxByCreated) Len() int           { return len(p) }
-func (p podSandboxByCreated) Swap(i, j int)      { p[i], p[j] = p[j], p[i] }
-func (p podSandboxByCreated) Less(i, j int) bool { return p[i].CreatedAt > p[j].CreatedAt }
+func (p podSandboxByCreated) Len() int      { return len(p) }
+func (p podSandboxByCreated) Swap(i, j int) { p[i], p[j] = p[j], p[i] }
+func (p podSandboxByCreated) Less(i, j int) bool {
+	if p[i].Metadata == nil || p[j].Metadata == nil {
+		return p[i].CreatedAt > p[j].CreatedAt
+	}
+	return p[i].Metadata.Attempt > p[j].Metadata.Attempt
```
Comment (HirazawaUi) [inline pkg/kubelet/kuberuntime/helpers.go:56]: This issue appears to be caused by containerd, and this PR aims to implement some defensive programming in kubelet to address the bug in containerd.

At first glance, this seems like a positive change: when the physical clock is unreliable, it replaces the absolute time order with a logical incremental relationship.

I would like to raise a question here:

Both https://github.com/kubernetes/kubernetes/issues/126514 and https://github.com/containerd/containerd/issues/9459 seem to be atypical issues.

That is, when an exception occurs here and reports error="failed to reserve sandbox name", there are already issues elsewhere before this point.

Could this fix potentially mask the real underlying problems? If it does mask the true errors, will users still have other means to troubleshoot this exception after we've obscured it?

I also have another question: Can this issue be reproduced on CRIO?

Comment (yylt) [reply pkg/kubelet/kuberuntime/helpers.go:56]: YES, also happend on CRIO

This is a system time issue. If NTP synchronizes the wrong time, causing time rollback, this problem will occur

**Comment by yylt** [comment]
> You can add this information under the **What this PR does / why we need it:** section.

Thanks suggestion, had add more info.

File: pkg/kubelet/kuberuntime/helpers.go (hunk 1 above)
Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/helpers.go:56]: As I mentioned earlier, the repeated creation of sandbox containers by kubelet is atypical behavior. This could be caused by:

1. Race conditions in kubelet and rapid pod lifecycle changes leading to duplicate sandbox creation (this would be a bug).

2. Containerd failing to create sandbox containers due to resource constraints, or sandbox containers entering erroneous states for other reasons.

For 2, we have already implemented some defensive programming in kubelet. We now sort the list of retrieved sandbox containers by creation time and select the first one.

Currently, kubelet strictly increments the Attempt value each time it tries to create a new sandbox for the same Pod (starting at 0, incrementing to 1 on retry after failure, etc.). This Attempt value is persisted and retained even across node reboots or containerd crashes, and continues to increment. Its value does not depend on system time, it is solely tied to the actual number of sandbox creation attempts.

From a defensive programming perspective, there appears to be no reason to reject this PR. In distributed systems, logical increment-based ordering is more reliable than absolute time order. Using the Attempt value as the sorting criterion is therefore justified.

cc @yujuhong @SergeyKanzhelev @tallclair  sig-node maintainers for more accurate and comprehensive insights.

**Comment by HirazawaUi** [comment]
/release-note-none

As I mentioned in the [comment](https://github.com/kubernetes/kubernetes/pull/130551#discussion_r1994545099), this is a defensive programming measure to prevent atypical issues, so it shouldn't be considered a bug.

/remove-kind bug
/kind feature

**Comment by bart0sh** [comment]
@yylt please address review comments or close the PR, thanks!
BTW, the issue this PR is trying to fix is closed. Please, reopen if still relevant.

**Comment by yylt** [comment]
> As I mentioned in the [comment](https://github.com/kubernetes/kubernetes/pull/130551#discussion_r1994545099), this is a defensive programming measure to prevent atypical issues, so it shouldn't be considered a bug.

It seems difficult to define, but if the timesync(ntp) service is not ready and the kubelet starts the pod, it will trigger this type of error, and the reason for the error is the use of physical time sorting, which is the root cause of the error, so it is a bug worthy type.

Also, I don't have permission to open https://github.com/kubernetes/kubernetes/issues/126514 here

**Comment by XmchxUp** [comment]
I think the `containerStatusByCreated` here also needs to be modified, and the struct name should be renamed to `xxxByAttemptAndCreated` as well.

**Comment by yylt** [comment]
> I think the `containerStatusByCreated` here also needs to be modified, and the struct name should be renamed to `xxxByAttemptAndCreated` as well.

There is a binding relationship between `container` and `sandbox`. 
Based on the cases that have occurred, the only reason for the failure is due to sandbox, and it cannot be automatically restored

**Comment by yylt** [comment]
cc @hshiina 

Is there anything I can do at this point to help? Or should I wait for other maintainers?

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

let's take it in 1.35. Please ping when master will open. The change is LGTM and I do not think we can write good tests for this.

**Comment by yylt** [comment]
ping @SergeyKanzhelev

**Comment by HirazawaUi** [comment]
@yylt We will unfreeze the code on August 27, at which time we can proceed with merging this PR.

**Comment by yylt** [comment]
> @yylt We will unfreeze the code on August 27, at which time we can proceed with merging this PR.

thanks, I saw a `v1.35.0-alpha.0` tag and thought it had been unfrozen, and where can see information about the freezing time?

**Comment by HirazawaUi** [comment]
> thanks, I saw a `v1.35.0-alpha.0` tag and thought it had been unfrozen, and where can see information about the freezing time?

FYI: https://github.com/kubernetes/sig-release/tree/master/releases/release-1.34

**Comment by HirazawaUi** [comment]
/assign @SergeyKanzhelev 

The branch is now open, and this PR is ready to merge.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by HirazawaUi** [comment]
The test jobs are very flaky, but it's not related to the current PR.

/retest
