### PR TITLE
Fix negative pod startup duration values

### LINKED ISSUE #130432: pod_startup_latency_tracker : podStartSLOduration returns negative value with serializeImagePulls set to false
### What happened?

This can be observed easily when deployed a large number of pods (i.e. 20 pods) at the same time in Kubernetes version 1.31. I found an issue with similar symptom, but it's supposed to be resolved on version 1.27
```
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.323529    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-c74hl" podStartSLOduration=1.344002188 podStartE2EDuration="3.323519624s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.734807377 +0000 UTC m=+565.347657070" lastFinishedPulling="2025-02-25 21:38:55.714324713 +0000 UTC m=+567.327174506" observedRunningTime="2025-02-25 21:38:56.323492624 +0000 UTC m=+567.936342317" watchObservedRunningTime="2025-02-25 21:38:56.323519624 +0000 UTC m=+567.936369517"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.338810    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-bd4br" podStartSLOduration=1.2549581779999999 podStartE2EDuration="3.338800195s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.661167137 +0000 UTC m=+565.274016830" lastFinishedPulling="2025-02-25 21:38:55.745009154 +0000 UTC m=+567.357858847" observedRunningTime="2025-02-25 21:38:56.338414293 +0000 UTC m=+567.951264086" watchObservedRunningTime="2025-02-25 21:38:56.338800195 +0000 UTC m=+567.951649988"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.361959    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-5ljwx" podStartSLOduration=1.360169063 podStartE2EDuration="3.361949302s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.709078158 +0000 UTC m=+565.321927851" lastFinishedPulling="2025-02-25 21:38:55.710858397 +0000 UTC m=+567.323708090" observedRunningTime="2025-02-25 21:38:56.353660063 +0000 UTC m=+567.966509756" watchObservedRunningTime="2025-02-25 21:38:56.361949302 +0000 UTC m=+567.974799095"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.369811    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-btpww" podStartSLOduration=1.305661411 podStartE2EDuration="3.369803938s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.681766232 +0000 UTC m=+565.294615925" lastFinishedPulling="2025-02-25 21:38:55.745908759 +0000 UTC m=+567.358758452" observedRunningTime="2025-02-25 21:38:56.369554537 +0000 UTC m=+567.982404230" watchObservedRunningTime="2025-02-25 21:38:56.369803938 +0000 UTC m=+567.982653731"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.387444    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-46lsl" podStartSLOduration=1.348360709 podStartE2EDuration="3.387435419s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.674280998 +0000 UTC m=+565.287130691" lastFinishedPulling="2025-02-25 21:38:55.713355708 +0000 UTC m=+567.326205401" observedRunningTime="2025-02-25 21:38:56.387005517 +0000 UTC m=+567.999855210" watchObservedRunningTime="2025-02-25 21:38:56.387435419 +0000 UTC m=+568.000285112"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.403513    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-jnjrp" podStartSLOduration=1.3758508360000001 podStartE2EDuration="3.403501694s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.719430606 +0000 UTC m=+565.332280399" lastFinishedPulling="2025-02-25 21:38:55.747081464 +0000 UTC m=+567.359931257" observedRunningTime="2025-02-25 21:38:56.403166792 +0000 UTC m=+568.016016485" watchObservedRunningTime="2025-02-25 21:38:56.403501694 +0000 UTC m=+568.016351387"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.419566    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-ccb4x" podStartSLOduration=1.444765554 podStartE2EDuration="3.419556368s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.728079746 +0000 UTC m=+565.340929439" lastFinishedPulling="2025-02-25 21:38:55.70287056 +0000 UTC m=+567.315720253" observedRunningTime="2025-02-25 21:38:56.419161366 +0000 UTC m=+568.032011159" watchObservedRunningTime="2025-02-25 21:38:56.419556368 +0000 UTC m=+568.032406061"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.436171    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-r87rt" podStartSLOduration=1.4568067089999999 podStartE2EDuration="3.436161144s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.730592558 +0000 UTC m=+565.343442251" lastFinishedPulling="2025-02-25 21:38:55.709946993 +0000 UTC m=+567.322796686" observedRunningTime="2025-02-25 21:38:56.435724342 +0000 UTC m=+568.048574035" watchObservedRunningTime="2025-02-25 21:38:56.436161144 +0000 UTC m=+568.049010837"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.451845    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-ddtjq" podStartSLOduration=1.468768364 podStartE2EDuration="3.451837417s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.716675693 +0000 UTC m=+565.329525386" lastFinishedPulling="2025-02-25 21:38:55.699744746 +0000 UTC m=+567.312594439" observedRunningTime="2025-02-25 21:38:56.451532415 +0000 UTC m=+568.064382108" watchObservedRunningTime="2025-02-25 21:38:56.451837417 +0000 UTC m=+568.064687210"
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.466178    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-dvz9k" podStartSLOduration=1.349237313 podStartE2EDuration="3.466167683s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.600616658 +0000 UTC m=+565.213466351" lastFinishedPulling="2025-02-25 21:38:55.717546928 +0000 UTC m=+567.330396721" observedRunningTime="2025-02-25 21:38:56.466025982 +0000 UTC m=+568.078875675" watchObservedRunningTime="2025-02-25 21:38:56.466167683 +0000 UTC m=+568.079017476"
Feb 25 21:39:05 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:05.352953    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-8fdzh" podStartSLOduration=-9223372024.501835 podStartE2EDuration="12.352941551s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.759004789 +0000 UTC m=+565.371854482" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:05.35260405 +0000 UTC m=+576.965453743" watchObservedRunningTime="2025-02-25 21:39:05.352941551 +0000 UTC m=+576.965791244"
Feb 25 21:39:07 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:07.357166    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-xjqwh" podStartSLOduration=-9223372022.497623 podStartE2EDuration="14.357152842s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.747887837 +0000 UTC m=+565.360737530" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:07.356718546 +0000 UTC m=+578.969568239" watchObservedRunningTime="2025-02-25 21:39:07.357152842 +0000 UTC m=+578.970002535"
Feb 25 21:39:07 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:07.373079    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-txh69" podStartSLOduration=-9223372022.481707 podStartE2EDuration="14.373068399s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.77438226 +0000 UTC m=+565.387231953" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:07.372808301 +0000 UTC m=+578.985657994" watchObservedRunningTime="2025-02-25 21:39:07.373068399 +0000 UTC m=+578.985918092"
Feb 25 21:39:07 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:07.392708    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-7nhl7" podStartSLOduration=-9223372022.462074 podStartE2EDuration="14.392701821s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.758577787 +0000 UTC m=+565.371427480" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:07.392238626 +0000 UTC m=+579.005088319" watchObservedRunningTime="2025-02-25 21:39:07.392701821 +0000 UTC m=+579.005551614"
Feb 25 21:39:07 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:07.410015    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-t877k" podStartSLOduration=-9223372022.44477 podStartE2EDuration="14.410004765s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.758583587 +0000 UTC m=+565.371433280" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:07.409663668 +0000 UTC m=+579.022513361" watchObservedRunningTime="2025-02-25 21:39:07.410004765 +0000 UTC m=+579.022854458"
Feb 25 21:39:08 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:08.365845    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-gb6tb" podStartSLOduration=-9223372021.488941 podStartE2EDuration="15.365835135s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.748261839 +0000 UTC m=+565.361111632" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:08.36525234 +0000 UTC m=+579.978102133" watchObservedRunningTime="2025-02-25 21:39:08.365835135 +0000 UTC m=+579.978684828"
Feb 25 21:39:08 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:08.414713    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-6h58c" podStartSLOduration=-9223372021.440079 podStartE2EDuration="15.414697194s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.768832034 +0000 UTC m=+565.381681827" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:08.414602395 +0000 UTC m=+580.027452188" watchObservedRunningTime="2025-02-25 21:39:08.414697194 +0000 UTC m=+580.027546987"
Feb 25 21:39:08 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:08.479999    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-8kf54" podStartSLOduration=-9223372021.374792 podStartE2EDuration="15.479984263s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.773336955 +0000 UTC m=+565.386186648" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:08.432632432 +0000 UTC m=+580.045482125" watchObservedRunningTime="2025-02-25 21:39:08.479984263 +0000 UTC m=+580.092834156"
Feb 25 21:39:09 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:09.368159    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-2vfzh" podStartSLOduration=-9223372020.48663 podStartE2EDuration="16.368146878s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.740005101 +0000 UTC m=+565.352854894" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2025-02-25 21:39:09.368031478 +0000 UTC m=+580.980881171" watchObservedRunningTime="2025-02-25 21:39:09.368146878 +0000 UTC m=+580.980996571"
Feb 25 21:39:09 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:39:09.383023    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-hgd78" **podStartSLOduration=-9223372020.471764** podStartE2EDuration="16.383012397s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.753171862 +0000 UTC m=+565.366021555" **lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC"** observedRunningTime="2025-02-25 21:39:09.382750199 +0000 UTC m=+580.995599892" watchObservedRunningTime="2025-02-25 21:39:09.383012397 +0000 UTC m=+580.995862090"
```

For the last 10 pods, the log is like this: pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-hgd78" **podStartSLOduration=-9223372020.471764** podStartE2EDuration="16.383012397s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.753171862 +0000 UTC m=+565.366021555" **lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC"** observedRunningTime="2025-02-25 21:39:09.382750199 +0000 UTC m=+580.995599892" watchObservedRunningTime="2025-02-25 21:39:09.383012397 +0000 UTC m=+580.995862090"

I saw similar issue [here](https://github.com/kubernetes/kubernetes/issues/114903) and it's supposed to be fixed in k8s version 1.27

### What did you expect to happen?

The result should be like the first 10 pods, but somehow it returned negative value for the last 10 pods:
Feb 25 21:38:56 aks-userpool0-20459031-vmss000001 kubelet[3201]: I0225 21:38:56.323529    3201 pod_startup_latency_tracker.go:104] "Observed pod startup duration" pod="default/resource-consume-5fb68775dc-c74hl" **podStartSLOduration=1.344002188** podStartE2EDuration="3.323519624s" podCreationTimestamp="2025-02-25 21:38:53 +0000 UTC" firstStartedPulling="2025-02-25 21:38:53.734807377 +0000 UTC m=+565.347657070" **lastFinishedPulling="2025-02-25 21:38:55.714324713 +0000 UTC** m=+567.327174506" observedRunningTime="2025-02-25 21:38:56.323492624 +0000 UTC m=+567.936342317" watchObservedRunningTime="2025-02-25 21:38:56.323519624 +0000 UTC m=+567.936369517"

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with kubernetes version 1.31. Use the following deployment to create pods 
Deployment spec
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-consume
  labels:
    group: resource-consume
spec:
  replicas: 20
  selector:
    matchLabels:
      name: resource-consume
  template:
    metadata:
      labels:
        name: resource-consume
        group: resource-consume
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: "aks-userpool0-20459031-vmss000001"
      containers:
      - name: resource-consumer-memory
        image: registry.k8s.io/e2e-test-images/resource-consumer:1.9
        imagePullPolicy: IfNotPresent
        command:
          - stress
        args:
          - --vm
          - "1"
          - --vm-bytes
          - 5000K
          - --vm-hang
          - "0"
          - --timeout
          - "3600"
        resources:
          requests:
            memory: 5000Ki
      tolerations:
      - key: "cri-resource-consume"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "cri-resource-consume"
        operator: "Equal"
        value: "true"
        effect: "NoExecute"
```
Run `kubectl node-shell` into the node to check kubelet log and grep the podStartE2EDuration
```
kubectl node-shell <node-name>
cd var/log
cat messages | grep pod_startup_latency_tracker
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.5
```

</details>

### Cloud provider

<details>
AKS

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# paste output here
Linux aks-userpool0-20459031-vmss000001 5.15.0-1079-azure #88-Ubuntu SMP Thu Jan 16 19:18:54 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.7.25-1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig node
/kind bug
/help

### PR DESCRIPTION
**Pull request by ali-a-a**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
I faced an issue with the pod startup duration metric, which sometimes shows negative values. This problem is also mentioned here #130432. 

When parallel image pulling is enabled (`serializeImagePulls: false`) and the image pull policy is `IfNotPresent`, this problem may happen. When there are multiple pods concurrently pulling the image, it is possible that some of the pull requests fail (e.g., pull QPS excess). It means that some pods start recording the image pull duration, but they never stop it since they return due to an error.

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/pkg/kubelet/images/image_manager.go#L284-L302

After the back-off duration, these pods retry and call `EnsureImageExists`, but this time, they don't call `pullImage` as the image already exists.

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/pkg/kubelet/images/image_manager.go#L209-L246

Therefore, `state.lastFinishedPulling` never will be set.

To fix the issue, we can finish the recording by calling `RecordImageFinishedPulling` before returning from `EnsureImageExists` if there is some recording in progress (i.e., `!state.firstStartedPulling.IsZero()`). The measured pull duration is also correct, as it is the time the pod has taken to finally retrieve the image (start recording -> pull the image -> error -> retry -> image already exists -> finish recording).

I also tested the fix and couldn't reproduce the problem after that.

#### Which issue(s) this PR fixes:

Fixes #130432

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/images/image_manager.go [hunk 1]
```diff
@@ -210,6 +210,11 @@ func (m *imageManager) EnsureImageExists(ctx context.Context, objRef *v1.ObjectR
 		if !utilfeature.DefaultFeatureGate.Enabled(features.KubeletEnsureSecretPulledImages) {
 			msg := fmt.Sprintf("Container image %q already present on machine", requestedImage)
 			m.logIt(objRef, v1.EventTypeNormal, events.PulledImage, logPrefix, msg, klog.Info)
+
+			// we need to stop recording if it is still in progress, as the image
+			// has already been pulled by another pod.
+			m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)
```
Comment (bart0sh) [inline pkg/kubelet/images/image_manager.go:216]: This would unconditionally update `lastFinishedPulling`, which doesn't look correct to me as in this particular case the was no pulling done (image already pulled by another pod?).

Comment (ali-a-a) [reply pkg/kubelet/images/image_manager.go:216]: If `firstStartedPulling` is not set (i.e., `state.firstStartedPulling.IsZero()`), this call is a no-op. So, we wouldn't unconditionally update `lastFinishedPulling`?

If you mean we should not record the pulling time for this pod as it didn't pull the image itself, I think we should consider the time the pod tried to pull the image and failed. The `podStartSLOduration` and `podStartE2EDuration` shouldn't be the same for this pod. With my implementation, we capture the duration from the time the pod starts pulling to the time it realizes the image exists, which seems correct to me :?

**Comment by ali-a-a** [comment]
> @ali-a-a Thank you for your PR! Please provide unit or e2e tests that cover this issue. It's required for bugfixes.

I added a unit test for this issue, which would fail without the fix.

File: pkg/kubelet/container/testing/fake_runtime.go [hunk 2]
```diff
@@ -348,7 +347,7 @@ func (f *FakeRuntime) PullImage(ctx context.Context, image kubecontainer.ImageSp
 	case <-f.imagePullTokenBucket:
 	}
 
-	return image.Image, retCreds, retErr
+	return image.Image, retCreds, f.Err
```
Comment (bart0sh) [inline pkg/kubelet/container/testing/fake_runtime.go:350]: Can you explain why locking is not needed to access f.Err?

File: pkg/kubelet/images/image_manager.go (hunk 1 above)
Comment (bart0sh) [reply pkg/kubelet/images/image_manager.go:216]: I'm still not fully understand the logic, sorry. So, some other pod downloaded the image, but for some reason (error?) it didn't update `lastFinishedPulling`. This (another) pod, doesn't download the image as image is already downloaded, but for some reason updates `lastFinishedPulling`. Why can't it be done by the pod, that does the actual downloading?
Another thing is that this image seems to be fully downloaded (without errors), but `lastFinishedPulling` is not updated. How can it happen? I'd understand this if there was a downloading error, but in this case image should be downloaded again, right?

File: pkg/kubelet/images/image_manager_test.go [hunk 3]
```diff
@@ -854,6 +863,88 @@ func TestMaxParallelImagePullsLimit(t *testing.T) {
...
+	assert.False(t, fakePodPullingTimeRecorder.finishedPullingRecorded[pods[0].UID])
+	assert.False(t, fakePodPullingTimeRecorder.finishedPullingRecorded[pods[1].UID])
+
+	// Unblock one of the pods to pull the image
+	fakeRuntime.UnblockImagePulls(1)
+	time.Sleep(1 * time.Second)
+
+	// Introduce a pull error for the second pod before unblocking it
+	fakeRuntime.Err = errors.New("pull image error")
+	fakeRuntime.UnblockImagePulls(1)
```
Comment (bart0sh) [inline pkg/kubelet/images/image_manager_test.go:928]: This doesn't reproduce the error, does it? In this case image should be fully downloaded by the puller that's not errored, right? And finishedPullingRecorded should be updated by it. 
What I'd like to see is the original error, i.e. negative `podStartSLOduration`.

File: pkg/kubelet/images/image_manager.go (hunk 1 above)
Comment (ali-a-a) [reply pkg/kubelet/images/image_manager.go:216]: > Why can't it be done by the pod, that does the actual downloading?

I think the part missing here is that each pod has its own `firstStartedPulling` and `lastFinishedPulling`. The pod that has successfully downloaded the image will update its own state:

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/pkg/kubelet/util/pod_startup_latency_tracker.go#L144-149

On the other hand, pods that get an error and go into a back-off phase after setting their `firstStartedPulling`, cannot come back and update their `lastFinishedPulling`, as the image is already downloaded and the `EnsureImageExists` won't call `pullImage` again.

> Another thing is that this image seems to be fully downloaded (without errors), but `lastFinishedPulling` is not updated. How can it happen? I'd understand this if there was a downloading error, but in this case image should be downloaded again, right?

When `serializeImagePulls: false` is set, multiple pods can pull the image at the same time. When one pod successfully does that, other pods may be still in the process of downloading the image (other goroutines here are still trying to pull):

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/pkg/kubelet/images/puller.go#L55-76

Again, as `lastFinishedPulling` is per pod, it is possible to fully download the image with one pod and have another pod's `lastFinishedPulling` unset.

Regarding the error itself, I also mentioned it in the PR's description. A `pull qps exceeded` error should be the reason we get those negative values. Say 20 pods are pulling an image at the same time. If the pull qps threshold is 10, 10 pods pull the image and 10 pods face the qps exceeded error. So, the error I'm referring to can be quite often if parallel pulling is enabled.

File: pkg/kubelet/images/image_manager_test.go (hunk 3 above)
Comment (ali-a-a) [reply pkg/kubelet/images/image_manager_test.go:928]: It is the reason we get negative `podStartSLOduration`. In the middle of the test, we check whether both `firstStartedPulling` values are true. At the end of the test, we check whether both `lastFinishedPulling` values are true. Without the fix, one of the `lastFinishedPulling` values wouldn't be true and essentially would cause a negative value if we wanted to calculate `podStartSLOduration` (`lastFinishedPulling (not set) - firstStartedPulling (set)`).

Could you also please look at my reply here , as I talked about it further?

https://github.com/kubernetes/kubernetes/pull/131324#discussion_r2047524590

File: pkg/kubelet/container/testing/fake_runtime.go (hunk 2 above)
Comment (ali-a-a) [reply pkg/kubelet/container/testing/fake_runtime.go]: I'm not completely familiar with the way `fake_runtime` is used. If all the test cases run concurrently, I suppose this change could add issues. I added a new variable for the purpose of introducing errors after blocking image pull calls.

File: pkg/kubelet/images/image_manager.go (hunk 1 above)
Comment (bart0sh) [reply pkg/kubelet/images/image_manager.go:216]: > On the other hand, pods that get an error and go into a back-off phase after setting their firstStartedPulling, cannot come back and update their lastFinishedPulling, as the image is already downloaded and the EnsureImageExists won't call pullImage again.

Thanks for the explanations!
Would it make sense for errored pods to set `lastFinishedPulling` when error occurs?

Comment (ali-a-a) [reply pkg/kubelet/images/image_manager.go:216]: It is how I think about it:

For errored pods, we could unset their `firstStartedPulling` and pretend they experienced no image pull latency (i.e., their `podStartSLOduration` == their `podStartE2EDuration`). But in this way, it doesn't match the definition we have here:

https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md

"We are explicitly excluding image pulling from time the SLI."

Imagine the errored pod gets an error in the middle of the pulling. It experiences a portion of the image-pulling duration and the backoff phase, and we are including these latencies in its SLO duration, which doesn't follow the definition.

In this implementation, in all scenarios, we measure the cost of pulling an image. For errored pods, this cost is the duration that starts with pulling and ends with realizing that the image exists on the machine after a retry. I think the final calculated duration for these pods matches the definition.

We could also define a new metric to indicate this kind of situation, but it seems like overkill.

But if you have any other ideas, I would love to try them out.

Comment (bart0sh) [reply pkg/kubelet/images/image_manager.go:216]: > In this implementation, in all scenarios, we measure the cost of pulling an image. For errored pods, this cost is the duration that starts with pulling and ends with realizing that the image exists on the machine after a retry. I think the final calculated duration for these pods matches the definition.

This makes sense to me. However, there is still certain latency between the time image is successfully pulled and the time of realising this. This latency can be eliminated if `lastFinishedPulling` would be updated for all pods when the image pulling succeeds.

Comment (ali-a-a) [reply pkg/kubelet/images/image_manager.go:216]: Hmm. I totally understand your point, but I have one thing on my mind. Currently, I think we consider the latency you are referring to. When one pod gets an error and retries to pull the image again, we don't reset its `firstStartedPulling`.

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/pkg/kubelet/util/pod_startup_latency_tracker.go#L135-L137

 It means that the time it takes to do other things than pulling (e.g., backing off) is also included in its pull latency. Do you mean this should not be like this, and only the duration of pulling itself should be considered?

Comment (bart0sh) [reply pkg/kubelet/images/image_manager.go:216]: That's a bit different story, but I understand what you mean. Let's keep your approach.

**Comment by bart0sh** [comment]
@ali-a-a please fix CI failures, thanks!

**Comment by bart0sh** [comment]
@ali-a-a Looking at `basicPodStartupLatencyTracker:ObservedPodOnWatch` code I'd say that the current approach doesn't guarantee that `podStartSLOduration` will alway be positive. For example, if it's called while image is not yet downloaded, `imagePullingDuration` and `podStartSLOduration` will be negative.

This makes me think that there should be better approach to fix https://github.com/kubernetes/kubernetes/issues/130432.

WDYT?

**Comment by ali-a-a** [comment]
> For example, if it's called while image is not yet downloaded, `imagePullingDuration` and `podStartSLOduration` will be negative.

I cannot think of a scenario where this creates an issue and couldn't reproduce it. If `ObservedPodOnWatch` is called while the pod doesn't have the image, it won't observe the pod startup latency as the pod cannot have `hasPodStartedSLO`.

https://github.com/kubernetes/kubernetes/blob/680ea07dbb2c6050d13b93660fa4d27d2d28d6eb/pkg/kubelet/util/pod_startup_latency_tracker.go#L181-L189

I think of it as if the pod tries to pull the image even once (so it sets its `firstStartedPulling`), we are in trouble (may get negative values). When it happens, the pod cannot be running unless one of these situations happens:

1. It itself downloads the image and sets its `lastFinishedPulling`.
2. It doesn't succeed, but also it cannot go to a running state before `EnsureImageExists` returns true. When `EnsureImageExists` does that, the pod either successfully downloads the image this time or realizes it exists.

Do you have a subtle corner case in your mind that I'm missing?

**Comment by bart0sh** [comment]
@ali-a-a CI failures seem to be related to your changes, at least some of them. PTAL.

**Comment by ali-a-a** [comment]
> @ali-a-a CI failures seem to be related to your changes, at least some of them. PTAL.

Yeah, there is a race condition in my unit test. I've gotten a bit busy these days, but I'll fix it shortly.

**Comment by ali-a-a** [comment]
I fixed the unit test. Only `pull-kubernetes-unit-windows-master` fails now...

Its log says that one pod doesn't start pulling at all (both `firstStartedPulling` and `lastFinishedPulling` are not set). I conjecture the blocking mechanism in `fake_runtime` doesn't block the pods on windows-master as the first pod pulls the image, although it is blocked. Consequently, the second pod doesn't pull as the image already presents on the machine.

```
 I0423 23:27:45.587568    7940 image_manager.go:130] test-ns/test_pod2/missing_image Pulling image "missing_image"
I0423 23:27:45.587680    7940 image_manager.go:130] test-ns/test_pod1/missing_image Container image "missing_image" already present on machine
    fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 2 times, but was actually called 1 times. 
```

@bart0sh Do you have any idea about it? Moreover, can I simulate the windows-master environment on my local machine? I don't have access to Windows.

**Comment by bart0sh** [comment]
@ali-a-a I don't have an idea, but I have a windows machine. I'll try to debug failing test there when I have time, hopefully tomorrow.

**Comment by bart0sh** [comment]
@ali-a-a I could only reproduce this when I created heavy load on my Windows laptop. My guess so far is that CI instances are low-powered and that caused the test to run slower than expected, so go-routines started at line 912 are not able to run fast enough to be registered by fake runtime before the check on line 920.

Calling `wg.Wait()` instead of sleeping for 1 second can help with this.

BTW, the error `fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 2 times, but was actually called 1 times.` seems to be ignored. You should probably consider using assert on line 917 instead of simply calling `fakeRuntime.AssertCallCounts("PullImage", 2)`.

**Comment by ali-a-a** [comment]
> @ali-a-a I could only reproduce this when I created heavy load on my Windows laptop. My guess so far is that CI instances are low-powered and that caused the test to run slower than expected, so go-routines started at line 912 are not able to run fast enough to be registered by fake runtime before the check on line 920.

@bart0sh Thank you so much for looking into it. I found the exact problem of CI failures. In `fake_runtime.PullImage`, the blocking mechanism only blocks the function before returning - it doesn't block the actual fake pulling behavior (i.e., `f.ImageList = append(f.ImageList, i)`). It means that in the previous version of the code, one goroutine could pull the image, although it was blocked. I fixed `fake_runtime.PullImage` in my third commit. Now, the whole operation gets blocked not just the return statement.

> Calling `wg.Wait()` instead of sleeping for 1 second can help with this.

It could also cause an issue, but in that case, the other unit test (`TestMaxParallelImagePullsLimit`) would also fail. Moreover, it is not that trivial to use `wg.Wait()` here. As both pull calls are blocked, using wg.Wait() causes deadlock. If tests get flaky because of these test cases, we can think about a solution in another PR probably.

> BTW, the error fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 2 times, but was actually called 1 times. seems to be ignored. You should probably consider using assert on line 917 instead of simply calling fakeRuntime.AssertCallCounts("PullImage", 2).

I double-checked it. When everything is okay, and we change the expected number of calls from 2 to, say, 3, the test blows up. So, it seems that it actually asserts it. Did you mean something else by being ignored?

**Review by hashim21223445 — APPROVED** [review]

**Comment by bart0sh** [comment]
> Did you mean something else by being ignored?

Sorry for not being clear. Here is what I've seen in the log:
```
    fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 2 times, but was actually called 1 times.
    image_manager_test.go:949: 
        	Error Trace:	C:/kubernetes/pkg/kubelet/images/image_manager_test.go:949
        	Error:      	Should be true
        	Test:       	TestParallelPodPullingTimeRecorderWithErr
```
fake_runtime.go:162 produced the error message, but it was ignored and the test failed at image_manager_test.go:949, which is `assert.True(t, fakePodPullingTimeRecorder.finishedPullingRecorded[pods[0].UID])`. If we add `assert.True(t, fakeRuntime.AssertCallCounts("PullImage", 2))` the error would be caught and the test would fail at image_manager_test.go:946.

**Comment by ali-a-a** [comment]
> fake_runtime.go:162 produced the error message, but it was ignored and the test failed at image_manager_test.go:949, which is `assert.True(t, fakePodPullingTimeRecorder.finishedPullingRecorded[pods[0].UID])`. If we add `assert.True(t, fakeRuntime.AssertCallCounts("PullImage", 2))` the error would be caught and the test would fail at image_manager_test.go:946.

Thanks for the clarification. I tested it, and it seems without the `assert.True()`, `fakeRuntime.AssertCallCount` still causes the test to fail. It is what I get when everything is okay and only `fakeRuntime.AssertCallCounts("PullImage", 3)` fails (changed 2 to 3 to make a failure):

```
--- FAIL: TestParallelPodPullingTimeRecorderWithErr (2.00s)
    fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 3 times, but was actually called 2 times.

FAIL    k8s.io/kubernetes/pkg/kubelet/images    8.163s
```

So, the error gets caught there, but it lets the test finish and shows all the failed asserts. Having `assert.True(t, fakeRuntime.AssertCallCounts("PullImage", 3))` only makes it better for tracing. It shows the exact line test failed in the unit test. In terms of causing the test to fail, they act the same.

```
--- FAIL: TestParallelPodPullingTimeRecorderWithErr (2.00s)
    fake_runtime.go:162: AssertCallCounts: expected PullImage to be called 3 times, but was actually called 2 times.
    image_manager_test.go:917: 
                Error Trace:    /home/kos/github/kubernetes/pkg/kubelet/images/image_manager_test.go:917
                Error:          Should be true
                Test:           TestParallelPodPullingTimeRecorderWithErr
```

But if you still think it is better to have `assert.True()`, we can add it.

File: pkg/kubelet/container/testing/fake_runtime.go [hunk 4]
```diff
@@ -318,6 +322,30 @@ func (f *FakeRuntime) GetContainerLogs(_ context.Context, pod *v1.Pod, container
...
+	}
+
+	blockImagePulls := f.BlockImagePulls
+	f.Unlock()
+
+	if blockImagePulls {
+		// Block the function before adding the image to f.ImageList
+		select {
+		case <-ctx.Done():
+		case <-f.imagePullTokenBucket:
```
Comment (bart0sh) [inline pkg/kubelet/container/testing/fake_runtime.go:340]: Here f is unlocked, but the code uses its field.

File: pkg/kubelet/container/testing/fake_runtime.go [hunk 5]
```diff
@@ -318,6 +322,30 @@ func (f *FakeRuntime) GetContainerLogs(_ context.Context, pod *v1.Pod, container
...
+		case pullImageErr := <-f.imagePullErrBucket:
```
Comment (bart0sh) [inline pkg/kubelet/container/testing/fake_runtime.go:341]: The same here.

File: pkg/kubelet/container/testing/fake_runtime.go (hunk 4 above)
Comment (ali-a-a) [reply pkg/kubelet/container/testing/fake_runtime.go:340]: Shouldn't it be like that? It is a channel, and we want all the goroutines to be blocked behind it. So, the channel should not be protected by the lock. The current implementation also uses this field without a lock. I only changed the place where we block the function.

File: pkg/kubelet/container/testing/fake_runtime.go (hunk 5 above)
Comment (ali-a-a) [reply pkg/kubelet/container/testing/fake_runtime.go:341]: Same as my comment here https://github.com/kubernetes/kubernetes/pull/131324#discussion_r2063840510

File: pkg/kubelet/container/testing/fake_runtime.go (hunk 4 above)
Comment (bart0sh) [reply pkg/kubelet/container/testing/fake_runtime.go:340]: I don't know how it should be. I've just noticed that usage of all other fields is guarded by the lock, but this one is not. So, potentially it can cause a race if this field is accessed by 2 or more go-routines at the same time.

Comment (ali-a-a) [reply pkg/kubelet/container/testing/fake_runtime.go:340]: I see. Thank you for looking at it.

For as long as I can understand, in this part of the code, we want all the go-routines to access the field (i.e., the channel) at the same time so they can sit there and wait for new messages. This is the reason this field is not protected by the lock. If we held the lock while accessing this channel, we could get a deadlock as the channel is exclusively accessed by a go-routine that is waiting for someone else to write to the channel, but it wouldn't happen as no one else could access the channel.

Moreover, even before these changes, this field was accessed without the lock. This PR only changes the location of the select statement.

https://github.com/kubernetes/kubernetes/blob/8aa1d337e955b7fa8d8656b77a1ef56b284f44cf/pkg/kubelet/container/testing/fake_runtime.go#L344-L349

Also, if we had a race condition, we would probably get an error in test results as tests run with the -race flag.

**Comment by bart0sh** [comment]
/lgtm

/assign @SergeyKanzhelev @mrunalp 
for approval

**Comment by esotsal** [comment]
Thanks @bart0sh and @ali-a-a !

**Comment by ali-a-a** [comment]
@bart0sh @SergeyKanzhelev @mrunalp 

It seems that this PR has a merge conflict now. If you still plan to review the PR, please let me know, and I'll rebase it.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

great discussions in PR comments

**Comment by dims** [comment]
needs to be rebased :( 
```
[tide] — Not mergeable. PR has a merge conflict.
```

**Comment by ali-a-a** [comment]
@SergeyKanzhelev @dims 

Thanks for taking a look at the PR. I will rebase it as soon as I can.

**Comment by ali-a-a** [comment]
@bart0sh @SergeyKanzhelev @mrunalp

I rebased the branch. Please take a look whenever possible.

File: pkg/kubelet/images/image_manager_test.go [hunk 6]
```diff
@@ -678,7 +678,10 @@ func (m *mockPodPullingTimeRecorder) RecordImageStartedPulling(podUID types.UID)
 func (m *mockPodPullingTimeRecorder) RecordImageFinishedPulling(podUID types.UID) {
 	m.Lock()
 	defer m.Unlock()
-	m.finishedPullingRecorded = true
+
+	if m.startedPullingRecorded {
```
Comment (bart0sh) [inline pkg/kubelet/images/image_manager_test.go]: This looks like a workaround to me. Should we instead stop calling `RecordImageFinishedPulling` when pulling is not started?

File: pkg/kubelet/util/pod_startup_latency_tracker.go [hunk 7]
```diff
@@ -150,7 +150,9 @@ func (p *basicPodStartupLatencyTracker) RecordImageFinishedPulling(podUID types.
 		return
 	}
 
-	state.lastFinishedPulling = p.clock.Now() // Now is always grater than values from the past.
+	if !state.firstStartedPulling.IsZero() {
```
Comment (bart0sh) [inline pkg/kubelet/util/pod_startup_latency_tracker.go:153]: This at least requires an explanation. It looks suspicious that `RecordImageFinishedPulling` silently doesn't do what it's supposed to do.

**Comment by bart0sh** [comment]
@ali-a-a Please, squash commits into 2:
- Fix negative pod startup duration
- Fix fake runtime's image pull

Some more info in commit messages would be nice to have as well.

File: pkg/kubelet/util/pod_startup_latency_tracker.go (hunk 7 above)
Comment (ali-a-a) [reply pkg/kubelet/util/pod_startup_latency_tracker.go:153]: It happens because we call `RecordImageFinishedPulling` in `EnsureImageExists` every time the image is already present on the machine. There are two cases in  `EnsureImageExists`. One is that the pod realizes the image exists right away and doesn't start recording. The other one is that it doesn't find the image in its first try, starts recording, goes to the imagePullLoopback phase, finds out that the image exists after a retry, and stops recording. We could distinguish between these cases by adding a new method to the `ImagePodPullingTimeRecorder` interface that tells us whether the recording has started or not. But I think the current implementation keeps it simpler. Right now, we just tell the pod, "Stop recording whenever you find the image". Under the hood, if the recording is going on, we stop it. If it is not, the stop operation is a no-op. This explanation also applies to this comment https://github.com/kubernetes/kubernetes/pull/131324#discussion_r2328688453. But please let me know if you have other ideas.

Comment (bart0sh) [reply pkg/kubelet/util/pod_startup_latency_tracker.go:153]: Thanks for the explanations! This makes sense to me. The code doesn't look clear, but this PR doesn't make it more complicated that it is.

Please, squash commits and I'll lgtm and unhold this PR, thanks!

Comment (ali-a-a) [reply pkg/kubelet/util/pod_startup_latency_tracker.go:153]: Thank you @bart0sh. I squashed commits into two as you said.

EDIT: I also added an extra note for each commit.

Comment (bart0sh) [reply pkg/kubelet/util/pod_startup_latency_tracker.go:153]: /lgtm
/unhold
