### PR TITLE
ignore base.go in client-verify

### LINKED ISSUE #42290: verify-staging-client-go.sh continuously failing on release-1.6 branch
The verification tests have been [continuously failing](https://k8s-testgrid.appspot.com/google-unit#verify-1.6) since we enabled them on the release-1.6 branch. It looks like `verify-staging-client-go.sh` is the failing check.
From [a recent log](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.6/25?log#log):
```
I0228 15:14:44.255]   diff '--ignore-matching-lines=^\s*\"Comment\"' -NauprB -I 'GoVersion.*\|GodepVersion.*' /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/version/base.go /go/src/k8s.io/kubernetes/staging/src/k8s.io/_tmp/pkg/version/base.go
I0228 15:14:44.255]   --- /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/version/base.go	2017-02-28 14:42:14.828391346 -0800
I0228 15:14:44.255]   +++ /go/src/k8s.io/kubernetes/staging/src/k8s.io/_tmp/pkg/version/base.go	2017-02-28 15:14:32.592488892 -0800
I0228 15:14:44.255]   @@ -39,8 +39,8 @@ var (
I0228 15:14:44.255]    	// them irrelevant. (Next we'll take it out, which may muck with
I0228 15:14:44.255]    	// scripts consuming the kubectl version output - but most of
I0228 15:14:44.256]    	// these should be looking at gitVersion already anyways.)
I0228 15:14:44.256]   -	gitMajor string = "" // major version, always numeric
I0228 15:14:44.256]   -	gitMinor string = "" // minor version, numeric possibly followed by "+"
I0228 15:14:44.256]   +	gitMajor string = "1"  // major version, always numeric
I0228 15:14:44.256]   +	gitMinor string = "6+" // minor version, numeric possibly followed by "+"
I0228 15:14:44.256]    
I0228 15:14:44.256]    	// semantic version, derived by build scripts (see
I0228 15:14:44.256]    	// https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md
I0228 15:14:44.256]   @@ -51,7 +51,7 @@ var (
I0228 15:14:44.256]    	// semantic version is a git hash, but the version itself is no
I0228 15:14:44.257]    	// longer the direct output of "git describe", but a slight
I0228 15:14:44.257]    	// translation to be semver compliant.
I0228 15:14:44.257]   -	gitVersion   string = "v0.0.0-master+$Format:%h$"
I0228 15:14:44.257]   +	gitVersion   string = "v1.6.0-beta.0+$Format:%h$"
I0228 15:14:44.257]    	gitCommit    string = "$Format:%H$"    // sha1 from git, output of $(git rev-parse HEAD)
I0228 15:14:44.257]    	gitTreeState string = "not a git tree" // state of git tree, either "clean" or "dirty"
I0228 15:14:44.257]    
I0228 15:14:44.257]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0228 15:14:44.270] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	147s
```

Does this check need to be fixed? Should we disable this check on release branches? Or is something actually wrong with the release branch?

cc @ethernetdan @enisoc

### PR DESCRIPTION
**Pull request by caesarxuchao**
We need to cherry-pick it to 1.6 to fix #42290.

### CODE REVIEW

File: staging/copy.sh [hunk 1]
```diff
@@ -224,7 +224,7 @@ rm -rf "${CLIENT_REPO_TEMP}/staging"
 if [ "${FAIL_ON_CHANGES}" = true ]; then
   echo "running FAIL_ON_CHANGES"
   ret=0
-  if diff --ignore-matching-lines='^\s*\"Comment\"' -NauprB -I "GoVersion.*\|GodepVersion.*" "${CLIENT_REPO}" "${CLIENT_REPO_TEMP}"; then
+  if diff -NauprB  -I '^\s*\"Comment\"' -I "GoVersion.*\|GodepVersion.*" -x "base.go" "${CLIENT_REPO}" "${CLIENT_REPO_TEMP}"; then
```
Comment (caesarxuchao) [inline staging/copy.sh]: I tried to use the full path to be safe, but `diff -x` doesn't take a full path. i can do `find XXX | diff` but that looks like an overkill.

Comment (sttts) [inline staging/copy.sh]: What about:
```shell
cp "${CLIENT_REPO}/pkg/version/base.go" "${CLIENT_REPO_TEMP}/pkg/version" # ignore base.go in diff
```

Comment (sttts) [inline staging/copy.sh]: also the  `ret=0` can go

Comment (caesarxuchao) [inline staging/copy.sh]: Ah, missed the obvious. Thanks.

**Comment by caesarxuchao** [comment]
Fixed. @sttts ptal. Thanks.

**Comment by caesarxuchao** [comment]
Adding the milestone. This is a bug fix.

**Comment by sttts** [comment]
@smarterclayton approved?

**Comment by caesarxuchao** [comment]
Need an approval, @smarterclayton help?

**Comment by caesarxuchao** [comment]
I think we need to revert this. The base.go is important, it affects the client version as shown by `kubectl version`.

**Comment by sttts** [comment]
@caesarxuchao how does reverting help? This only stops the verify script from failing. It does not stop the update script from updating the base.go file.

**Comment by caesarxuchao** [comment]
I think the original failure was because update-staging-client-go.sh was not included in update-all.sh yet, thus not run when the release was cut, so it's fixed now.

**Comment by sttts** [comment]
I thought some patching of base.go was going on. If not, we can revert indeed.

**Comment by enisoc** [comment]
If updating base.go does matter, then I think we need to fix the release scripts somehow. Currently every time I cut a new beta, verify will break on the release branch. We would need to figure out what is the right time to run update-staging-client-go.sh: as part of cutting the beta, or just after cutting the beta?
