### PR TITLE
prevent printing of stack trace when proxying 304 requests in api gateway

### LINKED ISSUE #32747: kube-apiserver: httplog: don't print stack traces when proxies return 304s
I noticed that the code that prints stack traces when we return an unexpected status code runs even if we're just proxying that code from a service or pod. We should probably not do that.

### PR DESCRIPTION
**Pull request by aofry**
partially addresses #32747.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32786)

### CODE REVIEW

File: pkg/apiserver/handlers.go [hunk 1]
```diff
@@ -152,6 +152,7 @@ func RecoverPanics(handler http.Handler) http.Handler {
 				http.StatusNotFound,
 				http.StatusUnauthorized,
 				http.StatusForbidden,
+				http.StatusNotModified,
```
Comment (lavalamp) [inline pkg/apiserver/handlers.go]: This protects against 304's and is probably fine.

I was hoping to not log on *any* response that's just being echoed by our proxy, though. Which is harder.:(

**Comment by lavalamp** [comment]
ok to test
