### PR TITLE
Use PATCH instead of PUT when update events

### LINKED ISSUE #14126: Events missing UIDs
Certain events are missing UIDs. After a bit of investigation with @lavalamp and @saad-ali we realized that UIDs are not validated if existing events are updated. The api-server can populate UIDs for events if they are missing based on the Name. 
Fixing the client side event generator may not work everywhere since it requires re-compiling all the clients.

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #14126
#14126 identifies the problem that we accidentally wipe out the UID when update an Event. Update of an Event occurs when we compress events, so it requires updating the `Event.Count` and `Event.LastTimeStamp`. This PR uses "patch" instead of "update" when we need to modify an event, so fields other than the above two won't be changed.

Please ignore the first commit "increase the on-wire precision of time" which is in PR #15263. This PR needs this fix to pass the unit test.

@saad-ali @vishh @liggitt @jiangyaoguo @bgrant0607 @lavalamp

### CODE REVIEW

File: pkg/client/record/event_test.go [hunk 1]
```diff
@@ -540,6 +578,27 @@ func TestEventfNoNamespace(t *testing.T) {
 			updateEvent <- event
 			return event, nil
 		},
+		OnPatch: func(event *api.Event, patch []byte) (*api.Event, error) {
+			cachedEvent, found := testCache[getEventKey(event)]
+			if !found {
```
Comment (bgrant0607) [inline pkg/client/record/event_test.go]: Looks like a lot of copied code.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: Yeah, I have to copy the code because I need to use the free variable testCache and updateEvent etc. I'll discuss with Saad to see if there is a better way.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: Fixed.

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

File: pkg/client/record/event.go [hunk 2]
```diff
@@ -111,19 +112,19 @@ func (eventBroadcaster *eventBroadcasterImpl) StartRecordingToSink(sink EventSin
...
 			previousEvent := eventCache.getEvent(event)
 			updateExistingEvent := previousEvent.Count > 0
 			if updateExistingEvent {
-				event.Count = previousEvent.Count + 1
-				event.FirstTimestamp = previousEvent.FirstTimestamp
+				// we still need to copy Name because the Patch relies on the Name to find the target event
 				event.Name = previousEvent.Name
-				event.ResourceVersion = previousEvent.ResourceVersion
+				time, _ := event.LastTimestamp.MarshalJSON()
+				patch = []byte(fmt.Sprintf("{\"count\":%d,\"lastTimestamp\":%s}", previousEvent.Count+1, string(time)))
```
Comment (saad-ali) [inline pkg/client/record/event.go]: Is this the correct way to do a patch? It feels weird that the client has to construct and pass in serialized json bytes. 

If so, is there any common util method for constructing a patch, that you could use instead?

Comment (caesarxuchao) [inline pkg/client/record/event.go]: I don't know of any common util method for constructing a patch. @bgrant0607 @lavalamp do you have any suggestion? Thanks.

Comment (lavalamp) [inline pkg/client/record/event.go]: There's a function that will produce a patch from two objects, I think.
Look at the PATCH handling code in apiserver, or do a search for
strategicmergepatch.

Comment (caesarxuchao) [inline pkg/client/record/event.go]: I think you are talking about this: https://github.com/kubernetes/kubernetes/blob/49d6c86eb764a8c825d78a7810f4d57db55e9308/pkg/util/strategicpatch/patch.go#L111

Let me try if I can use this to create patch for individual fields.

Comment (caesarxuchao) [inline pkg/client/record/event.go]: Fixed.

File: pkg/client/record/event.go [hunk 3]
```diff
@@ -111,19 +114,26 @@ func (eventBroadcaster *eventBroadcasterImpl) StartRecordingToSink(sink EventSin
...
 			updateExistingEvent := previousEvent.Count > 0
 			if updateExistingEvent {
-				event.Count = previousEvent.Count + 1
-				event.FirstTimestamp = previousEvent.FirstTimestamp
+				// we still need to copy Name because the Patch relies on the Name to find the target event
 				event.Name = previousEvent.Name
-				event.ResourceVersion = previousEvent.ResourceVersion
+				event.Count = previousEvent.Count + 1
+
+				// we need to make sure the Count and LastTimestamp are the only differences between event and the eventCopy2
```
Comment (saad-ali) [inline pkg/client/record/event.go]: I was hoping using an existing method would reduce the amount of code here, but it increased it :) Oh well

**Comment by saad-ali** [comment]
LGTM
I'll let @lavalamp take a look

File: pkg/client/record/event.go (hunk 3 above)
Comment (caesarxuchao) [inline pkg/client/record/event.go]: It's better than spelling a string ourselves :) Thanks for the good advice.

**Comment by caesarxuchao** [comment]
@saad-ali, I removed the dependency on the commit that increases time accuracy. I shifted the timestamp by -10 seconds in OnCreate in the last commit. PTAL. Thank you.

**Comment by saad-ali** [comment]
LGTM
@lavalamp ?

File: pkg/client/record/event_test.go [hunk 4]
```diff
@@ -56,6 +61,57 @@ func (t *testEventSink) Update(e *api.Event) (*api.Event, error) {
...
+func (t *testEventSink) Patch(e *api.Event, p []byte) (*api.Event, error) {
+	if t.OnPatch != nil {
+		return t.OnPatch(e, p)
+	}
+	return e, nil
+}
+
+type OnCreateFunc func(*api.Event) (*api.Event, error)
+
+func OnCreateFactory(testCache map[string]*api.Event, createEvent chan *api.Event) OnCreateFunc {
```
Comment (krousey) [inline pkg/client/record/event_test.go]: can you make this `createEvent chan<- *api.Event`? Same for `patchEvent` below.

File: pkg/client/record/event_test.go [hunk 5]
```diff
@@ -56,6 +61,57 @@ func (t *testEventSink) Update(e *api.Event) (*api.Event, error) {
...
+	return func(event *api.Event) (*api.Event, error) {
+		// because the accuracy of time decreases to second-level after time is
+		// encoded, we have to manually shift the timestamp here, so the
+		// timestamp in patch will be different even if the same event occurs in
+		// rapid succession.
+		shift := time.Duration(-10 * time.Second)
+		event.FirstTimestamp = unversioned.NewTime(event.FirstTimestamp.Time.Add(shift))
```
Comment (krousey) [inline pkg/client/record/event_test.go]: Where are these original timestamps generated? Somewhere in the code under test? And where does the 10 second shift matter? Is that comparison in the code under test as well? Or in the actual test code?

I don't know if it's possible, but I would rather see these just pull subsequent times off of a shared resource.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: > Where are these original timestamps generated? Somewhere in the code under test?

yes. 

> And where does the 10 second shift matter?

that's in the actual test code.

> I would rather see these just pull subsequent times off of a shared resource.

I don't follow. Could you explain this in another way? Thanks.

Comment (krousey) [inline pkg/client/record/event_test.go]: I would like to remove the dependency on timing completely. This can lead to flaky tests, even if it is unlikely. I was thinking maybe something like:

```go
func OnCreateFactory(testCache map[string]*api.Event, createEvent chan<- *api.Event, ticker func() time.Time) OnCreateFunc {
	return func(event *api.Event) (*api.Event, error) {
		ts := ticker()
		event.FirstTimestamp = ts
		event.LastTimestamp = ts
		...
	}
}

func OnPatchFactory(testCache map[string]*api.Event, createEvent chan<- *api.Event, ticker func() time.Time) OnPatchFunc {
	return func(event *api.Event) (*api.Event, error) {
		ts := ticker()
		// Modify timestamps appropriately
		...
	}
}

...

func TestEventf(t *testing.T) {
	...
	var tickerTimestamp time.Time
	ticker := func() time.Time {
		tickerTimestamp = tickerTimestamp.Add(time.Second)
		return tickerTimestamp
	}
	testEvent := testEventSink{
		OnCreate: OnCreateFactory(testCache, createEvent, ticker),
		OnPatch:  OnPatchFactory(testCache, patchEvent, ticker),
		...
}
```

Would something like this work? Is the only place these timestamp matter in `validateEvent`?

Comment (lavalamp) [inline pkg/client/record/event_test.go]: There's a fake clock in util, unless it's been moved. That should be used
for time based tests.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: > 
```
func OnPatchFactory(testCache map[string]*api.Event, createEvent chan<- *api.Event, ticker func() time.Time) OnPatchFunc {
    return func(event *api.Event) (*api.Event, error) {
        ts := ticker()
        // Modify timestamps appropriately
        ...
    }
}
```

Introducing a fake clock would be a good idea, but we shouldn't manually change the patch here, the point of this unit test is verifying the generated patch is correct.
We just need a difference between the time when an event is created and when it's patched. The introduced 10 seconds shift will eliminate flake.

Comment (krousey) [inline pkg/client/record/event_test.go]: I guess if there's a strict ordering of the events, then yea, the patch will always have at least a 10 second difference.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: Now the test uses the fake clock. PTAL. Thank you for all the suggestions!

File: pkg/client/record/event_test.go (hunk 4 above)
Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: Forgot to take care of this. Will send another commit.

Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: Done.

File: pkg/client/record/event.go [hunk 6]
```diff
@@ -232,12 +245,18 @@ func (eventBroadcaster *eventBroadcasterImpl) StartEventWatcher(eventHandler fun
 
 // NewRecorder returns an EventRecorder that records events with the given event source.
 func (eventBroadcaster *eventBroadcasterImpl) NewRecorder(source api.EventSource) EventRecorder {
-	return &recorderImpl{source, eventBroadcaster.Broadcaster}
+	return &recorderImpl{source, eventBroadcaster.Broadcaster, util.RealClock{}}
+}
+
+// NewRecorderWithClock makes it easy to write test with a fake clock.
+func (eventBroadcaster *eventBroadcasterImpl) NewRecorderWithClock(source api.EventSource, clock util.Clock) EventRecorder {
```
Comment (krousey) [inline pkg/client/record/event.go]: Do we need this outside of this packages tests?

File: pkg/client/record/event.go [hunk 7]
```diff
@@ -86,6 +89,9 @@ type EventBroadcaster interface {
 	// NewRecorder returns an EventRecorder that can be used to send events to this EventBroadcaster
 	// with the event source set to the given event source.
 	NewRecorder(source api.EventSource) EventRecorder
+
+	// NewRecorderWithClock makes it easy to write test with a fake clock.
+	NewRecorderWithClock(source api.EventSource, clock util.Clock) EventRecorder
```
Comment (krousey) [inline pkg/client/record/event.go]: Oh wow this is gross. I see why you have to do it, and that's bad. This would be so much better if `NewBroadcaster` return an implementation and not an interface. If it did, you could add this as a private method to that implementation, access it in the tests, and never expose it to anything outside this package. Would it be hard to change `eventBroadcasterImpl` to a public type (probably a different name), return that from `NewBroadcaster`, and then just have this be a private method?

This is a good example of why you shouldn't return interfaces if you can.

Comment (krousey) [inline pkg/client/record/event.go]: A less desirable way to do it (but much prefered to adding this method to the public interface) would be to type assert the interface to `*eventBroadcasterImpl` after calling `NewBroadcaster` in the tests, and then calling a private method on that.

File: pkg/client/record/event.go (hunk 6 above)
Comment (liggitt) [inline pkg/client/record/event.go]: I would hope not... this should be a private function in the _test.go file

File: pkg/client/record/event.go (hunk 7 above)
Comment (lavalamp) [inline pkg/client/record/event.go]: Note-- you *can* return private types!

Comment (lavalamp) [inline pkg/client/record/event.go]: But do note in the godoc that it returns an EventRecorder if you choose to do so.

Comment (liggitt) [inline pkg/client/record/event.go]: don't change the interface, set up the struct with the fake clock in the test file

Comment (caesarxuchao) [inline pkg/client/record/event.go]: If I make NewRecorderWithClock a private method of the interface, will that be good enough?

Comment (liggitt) [inline pkg/client/record/event.go]: just make it a helper function in the test file... doesn't need to be in the interface at all

Comment (caesarxuchao) [inline pkg/client/record/event.go]: @liggitt , something like this ?
```
recorder := &recorderImpl{api.EventSource{Component: "eventTest"}, eventBroadcaster.(*eventBroadcasterImpl).Broadcaster, clock}
```

Comment (liggitt) [inline pkg/client/record/event.go]: something like that, sure. if the cast stops working, the unit tests will bark at us. I'd rather have something ugly like that hidden in an in-package test helper function than exported in an interface

File: pkg/client/record/event_test.go [hunk 8]
```diff
@@ -348,6 +398,10 @@ func validateEvent(actualEvent *api.Event, expectedEvent *api.Event, t *testing.
 	return actualEvent, nil
 }
 
+func recorderWithFakeClock(eventSource api.EventSource, eventBroadcaster EventBroadcaster, clock util.Clock) EventRecorder {
```
Comment (caesarxuchao) [inline pkg/client/record/event_test.go]: @liggitt @krousey is this better?

Comment (krousey) [inline pkg/client/record/event_test.go]: Yes.

**Comment by caesarxuchao** [comment]
squashed.

**Comment by caesarxuchao** [comment]
add "lgtm" back as it's a squash
