### PR TITLE
fix:When the --bind-address parameter of kube-proxy is configured as ipv6, the ip address of metrics listens to 127.0.0.1 by default, instead of::1

### LINKED ISSUE #123544: Docs: When the `--bind-address` parameter of kube-proxy is configured as ipv6, the ip address of metrics listens to 127.0.0.1 by default, instead of::1
### What happened?

The `--bind-address` parameter of kube-proxy is configured as ipv6
```
--bind-address=aaaa:bbbb::2e8

```
The metrics port of kube-proxy listens to the ipv4 address
​```
netstat -nlap|grep 10249
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      5412/kube-proxy     
```

### What did you expect to happen?

When the `--bind-address` parameter of kube-proxy is configured as ipv6, the ip address of metrics listens to ::1 by default

### How can we reproduce it (as minimally and precisely as possible)?

The `--bind-address` parameter of kube-proxy is configured as ipv6

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #123544

#### Does this PR introduce a user-facing change?

```release-note
Updated description of default values for --healthz-bind-address and --metrics-bind-address parameters
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -1063,3 +1064,28 @@ func getNodeIPs(logger klog.Logger, client clientset.Interface, name string) []n
 	}
 	return nodeIPs
 }
+
+func (o *Options) setDefaultAddresses(config *kubeproxyconfig.KubeProxyConfiguration) {
+	defaultHealthzAddress, defaultMetricsAddress := getDefaultAddresses(config.BindAddress)
```
Comment (tnqn) [inline cmd/kube-proxy/app/server.go:1069]: The config's usage has declared the current behavior:
> --bind-address string     Default: 0.0.0.0
>
>   Overrides kube-proxy's idea of what its node's primary IP is. Note that the name is a historical artifact, and kube-proxy does not actually bind any sockets to this IP.

This change may even break users who correctly use `--bind-address` to specify node's primary IP and `--healthz-bind-address` to specify HealthzBindAddress.

Comment (tnqn) [reply cmd/kube-proxy/app/server.go:1069]: ok, there is also another usage declaring the behavior you are fixing:
> --healthz-bind-address ipport     Default: 0.0.0.0:10256
>
> The IP address and port for the health check server to serve on, defaulting to "0.0.0.0:10256" (if --bind-address is unset or IPv4), or "[::]:10256" (if --bind-address is IPv6). Set empty to disable. This parameter is ignored if a config file is specified by --config.

Comment (yangjunmyfm192085) [reply cmd/kube-proxy/app/server.go:1069]: Yes, this is the key. This PR solution fits this description

Comment (tnqn) [reply cmd/kube-proxy/app/server.go:1069]: I thought this change would break "Set empty to disable" if it overrides the addresses after defaulting. However, I then found setting empty value didn't work even before the patch as an explicit `--healthz-bind-address=` can't reset the default value either. Not sure if this is a doc issue, or empty value is really expected to disable it. If the latter, perhaps moving defaulting here may make it harder to be disabled?

As a side note, setting "bindAddress" to ipv6 address in config file does make metrics and healthz listen to IPv6 addresses. https://github.com/kubernetes/kubernetes/pull/120274 updated the usages in both config file and CLI flags, it's also possible that it should have updated config file only? cc @danwinship

**Comment by khenidak** [comment]
The issue that triggered this PR is a confusion around docs and field usage. The field (probably archaic) is not well documented.

**Comment by uablrek** [comment]
You MUST NOT mess with the `--bind-address` option! It should basically be obsoleted and removed. Perhaps replaced with a proxy-mode=iptables(nftables?) unique option, since it has _no function_ for proxy-mode=ipvs. You should not introduce some semantics to it!

Please see https://github.com/kubernetes/kubernetes/pull/119525.

/cc @danwinship

File: cmd/kube-proxy/app/server.go (hunk 1 above)
Comment (danwinship) [reply cmd/kube-proxy/app/server.go:1069]: > As a side note, setting "bindAddress" to ipv6 address in config file does make metrics and healthz listen to IPv6 addresses. #120274 updated the usages in both config file and CLI flags, it's also possible that it should have updated config file only? cc @danwinship

Ah... yeah, I guess that's probably the real bug here; I assumed that the CLI options had the same semantics as the config options here, but actually they didn't.

At this point, I think we should not be changing the semantics of the CLI options, even where they are clearly bad. The plan is to deprecate them in favor of the v1alpha2/eventual-v1 config file anyway.

**Comment by danwinship** [comment]
So as commented above, I think the fix here is to just make `--help` document the existing behavior, rather than changing the behavior to match the existing `--help` strings

**Comment by yangjunmyfm192085** [comment]
I have updated

**Review by uablrek — APPROVED** [review]
