### PR TITLE
Check if options returning an error

### LINKED ISSUE #78735: kube-proxy prints misleading error on successful --cleanup
**What happened**:
`kube-proxy --cleanup` logs a nil error on success, EG:

`server.go:475] <nil>`.

**What you expected to happen**:
kube-proxy shouldn't log an error on success. Either a nil error should be interpreted as success, or an explicit exit boolean should be returned & evaluated.

**How to reproduce it (as minimally and precisely as possible)**:
Run `kube-proxy --cleanup` in master/1.15, or 1.14.2+.

**Anything else we need to know?**:
Code indicates that this is a problem ever since exiting was introduced (kube-proxy previously hung). It calls log.Fatal() on the return result, under the now-false assumption that an exit -> a crash.

**Environment**:
- Hyperkube, 1.14.2

### PR DESCRIPTION
**Pull request by johscheuer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR fixes that `kube-proxy` don't log an `nil` error after a successful run.

**Which issue(s) this PR fixes**:
Fixes #78735

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
kube-proxy --cleanup will return the correct exit code if the cleanup was successful
```

### CODE REVIEW

**Comment by johscheuer** [comment]
So the `--cleanup` case works now:

```bash
sudo /tmp/kube-proxy --cleanup
W0606 20:51:18.343204   18959 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
```
but now I get an Stacktrace when an error is happening:

```bash
sudo /tmp/kube-proxy
W0606 20:51:33.797272   19263 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0606 20:51:33.812251   19263 server.go:502] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
F0606 20:51:33.812290   19263 server.go:451] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0x2744101, 0x3, 0xc0002fc000, 0x9a)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:900 +0xb1
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x27441a0, 0xc000000003, 0xc00019f9d0, 0x26a8363, 0x9, 0x1c3, 0x0)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:815 +0xe6
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x27441a0, 0x3, 0x1, 0xc00057bd28, 0x1, 0x1)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:718 +0x12b
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(...)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:709
k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(...)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1289
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc0003b4000, 0x2761660, 0x0, 0x0)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:451 +0x1ea
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003b4000, 0xc000086190, 0x0, 0x0, 0xc0003b4000, 0xc000086190)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003b4000, 0x179cea8, 0x2743d40, 0x16fd4b8)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/proxy.go:49 +0x105

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x27441a0)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1035 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:404 +0x6c

goroutine 13 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x179cec0, 0x12a05f200, 0x0, 0xc0003a2001, 0xc0000840c0)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:164 +0x181
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x179cec0, 0x12a05f200)
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:79 +0x50
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	/Users/jscheuermann/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
```

I will take a look where and why the stacktrace is happening 🤔

**Comment by johscheuer** [comment]
Okay I just validated with the latest master that I also get the Stacktrace seems to be an issue (or feature??) in klog ?

**Comment by vllry** [comment]
Are those stack traces only on fatal errors, or in general?

**Comment by johscheuer** [comment]
This happens only on fatals (I just verified it). The fatal error above is raised because I didn't provide any configuration to kube-proxy.

It seems like this is newly introduced into a release of klog. Do we really want to throw an fatal with an stacktrace when we don't provide any configuration to kube-proxy ?

**Comment by johnbelamaric** [comment]
No. For a CLI, "handling" the error is just letting the user know. I don't see a need to use Fatal here, why not just log as error and exit with a non-zero value?

That said, this seems like a bad change in klog to assume you want a stack trace for any Fatal - maybe that should be a new function FatalWithTrace or something.

**Comment by johnbelamaric** [comment]
(by CLI i mean that this is related to the CLI options, but I guess that it may be called in automation...but still stack trace implies programmer error not user error)

**Comment by vllry** [comment]
I suspect the reason is that kube-proxy is part CLI and part daemon... as a cluster admin, I'd really want to know if kube-proxy was crashing.

**Comment by johscheuer** [comment]
I adjusted the code to use log level error instead of fatal to suppress the stacktrace, now everything is working as expected:

Running the cleanup:
```bash
sudo /tmp/kube-proxy --cleanup
W0608 21:01:10.740895   11955 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
```

Calling without arguments:
```bash
/tmp/kube-proxy 
W0608 21:01:22.544614   12261 server.go:216] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
I0608 21:01:22.562628   12261 server.go:503] Neither kubeconfig file nor master URL was specified. Falling back to in-cluster config.
E0608 21:01:22.562673   12261 server.go:451] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

**Comment by vllry** [comment]
Do we want to downgrade the log level? I would lean towards leaving it at fatal.

(Also, nit, there's a typo in the release note)

**Comment by johscheuer** [comment]
Thanks for the hint I fixed the typo in the release notes.

I take a look if we can leave the log level at fatal and don't print a stacktrace (or do we want to print a stacktrace if no configuration is provided).

**Comment by johscheuer** [comment]
Ping @vllry should we fix the upstream klog (to add an option to use `fatal` without stacktrace) or can we go with the error level ?

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -446,7 +446,11 @@ with the apiserver API to configure the proxy.`,
 			if err := opts.Validate(args); err != nil {
 				klog.Fatalf("failed validate: %v", err)
 			}
-			klog.Fatal(opts.Run())
+
+			if err := opts.Run(); err != nil {
+				klog.Error(err)
+				os.Exit(1)
```
Comment (danwinship) [inline cmd/kube-proxy/app/server.go]: You can just do `klog.Exit(err)`, which will exit without stacktracing. I agree that the stack trace is unwanted in this context.

Comment (johscheuer) [reply cmd/kube-proxy/app/server.go]: Changed the code. Thanks for the hint !

**Comment by danwinship** [comment]
looks good, but you can you squash it down into a single commit?

**Comment by johscheuer** [comment]
Squashed the commits
