### PR TITLE
don't mutate original master->kubelet TLS config

### LINKED ISSUE #33140: Dialing different nodes breaks TLS-verified master<->kubelet connections
When the master dials nodes, it is mutating the tlsConfig held by the master kubelet client, to add a server name.

That means if two different nodes are dialed from a master started with `--kubelet-certificate-authority`, x509 verification will fail for the second one.

Introduced in https://github.com/kubernetes/kubernetes/commit/7e9d82129e58196b2d3f0b22e6b139c1c6b04dd1#diff-e00658bdc0ba8e28b32f709e4e41558eR72

### PR DESCRIPTION
**Pull request by liggitt**
fixes https://github.com/kubernetes/kubernetes/issues/33140

``` release-note
Resolves x509 verification issue with masters dialing nodes when started with --kubelet-certificate-authority
```

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33141)

### CODE REVIEW

**Comment by marun** [comment]
Consider adding a test to prevent this regression from recurring.

**Comment by liggitt** [comment]
Test and fix that govet won't complain about forthcoming

**Comment by liggitt** [comment]
Updated to copy the struct field-by-field (which makes me cringe, but is what golang also ended up doing in net/http/cloneTLSClientConfig to get around govet warnings when copying tls.Config structs for client use). In go1.8, we can use `tls.Config#Clone` instead. Added a reflective test to catch drift on the field-by-field copy until then.

Added dial tests to make sure insecure, secured, and pinned name dials all work as expected, and don't mutate the transport's tls.Config

File: pkg/util/net/http.go [hunk 1]
```diff
@@ -108,6 +108,33 @@ func Dialer(transport http.RoundTripper) (DialFunc, error) {
 	}
 }
 
+// CloneTLSConfig returns a tls.Config with all exported fields except SessionTicketsDisabled and SessionTicketKey copied.
+// This makes it safe to call CloneTLSConfig on a config in active use by a server.
```
Comment (smarterclayton) [inline pkg/util/net/http.go]: Todo about replacing with Clone() in Go 1.8

**Review by smarterclayton — COMMENTED** [review]
One minor comment

File: pkg/util/net/http.go (hunk 1 above)
Comment (liggitt) [inline pkg/util/net/http.go]: done

**Comment by liggitt** [comment]
comment addressed

**Comment by smarterclayton** [comment]
LGTM

**Comment by pwittrock** [comment]
@k8s-bot gce e2e test this

**Comment by pwittrock** [comment]
@k8s-bot kubemark e2e test this

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/31570

@k8s-bot gce e2e test this

**Comment by pwittrock** [comment]
@k8s-bot gce e2e test this

**Comment by liggitt** [comment]
unrelated flake (passed in the cherry pick PR run):
```
STEP: validating guestbook app
Sep 21 12:02:25.051: INFO: Waiting for all frontend pods to be Running.
Sep 21 12:02:55.053: INFO: Waiting for frontend to serve content.
Sep 21 12:02:55.089: INFO: Trying to add a new entry to the guestbook.
Sep 21 12:02:55.109: INFO: Verifying that added entry can be retrieved.
Sep 21 12:02:55.119: INFO: Failed to get response from guestbook. err: <nil>, response: {"data": ""}
Sep 21 12:03:00.138: INFO: Failed to get response from guestbook. err: <nil>, response: {"data": ""}
Sep 21 12:03:05.149: INFO: Failed to get response from guestbook. err: <nil>, response: {"data": ""}
Sep 21 12:03:10.154: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://10.180.4.95:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 21 12:03:15.169: INFO: Failed to get response from guestbook. err: <nil>, response: {"data": ""}
Sep 21 12:03:20.174: INFO: Failed to get response from guestbook. err: an error on the server ("Error: 'EOF'\nTrying to reach: 'http://10.180.4.95:80/guestbook.php?cmd=get&key=messages&value='") has prevented the request from succeeding (get services frontend), response: 
Sep 21 12:03:25.199: INFO: Failed to get response from guestbook. err: <nil>, response: {"data": ""}
```

**Comment by pwittrock** [comment]
What is the cherrypick PR?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/33187

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/33175

@k8s-bot gce e2e test this
