### PR TITLE
sched: fix a bug that metrics of init or collected pods are re-collected

### LINKED ISSUE #99218: Metrics of ignored/initialized pods in a scheduler performance test are benchmarked
#### What happened:

In the new scheduler performance testing framework, `collectMetrics`(bool) is provided to benchmark performance of pods created in an "operator": (L11 below)

https://github.com/kubernetes/kubernetes/blob/df8dee80c838bfb50532d1509c1a77a9c4463a11/test/integration/scheduler_perf/config/performance-config.yaml#L1-L17

However, the initialized Pods created in L5~L7 seem to be also benchmarked, although it doesn't specify `collectMetrics: true`. (please see the reproduce steps below).

I think it's b/c once scheduler starts, the associated Prometheus artifacts are also up, and it's a single in-memory datastore. So no matter we start to collect the metric in which step, the prometheus data is already up-to-date. In the above workload config, the final data have benchmarked 1500 pods instead of 1000 pods. I guess it won't work either if running `hist.Clear()` in the pod initialization step or not. Unless we manage a breakpoint at the end of each `createPods` step, and calculate delta histogram for the step that specifies `collectMetrics: true`.

#### What you expected to happen:

Pods created in step `createPods` without `collectMetrics: true` are not benchmarked.

#### How to reproduce it (as minimally and precisely as possible):

Apply the following diff:

```diff
diff --git a/staging/src/k8s.io/component-base/metrics/testutil/metrics.go b/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
index ac66772c446..c9319c769e2 100644
--- a/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
+++ b/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
@@ -273,6 +273,10 @@ func (hist *Histogram) Quantile(q float64) float64 {
 		})
 	}
 
+	for _, b := range buckets {
+		fmt.Printf("[DEBUG] %v le %v\n", b.count, b.upperBound)
+	}
+
 	return bucketQuantile(q, buckets)
 }
 
diff --git a/test/integration/scheduler_perf/scheduler_perf_test.go b/test/integration/scheduler_perf/scheduler_perf_test.go
index 3ed259e8d01..beba1b7d069 100644
--- a/test/integration/scheduler_perf/scheduler_perf_test.go
+++ b/test/integration/scheduler_perf/scheduler_perf_test.go
@@ -49,9 +49,9 @@ const (
 var (
 	defaultMetricsCollectorConfig = metricsCollectorConfig{
 		Metrics: []string{
-			"scheduler_scheduling_algorithm_predicate_evaluation_seconds",
-			"scheduler_scheduling_algorithm_priority_evaluation_seconds",
-			"scheduler_e2e_scheduling_duration_seconds",
+			// "scheduler_scheduling_algorithm_predicate_evaluation_seconds",
+			// "scheduler_scheduling_algorithm_priority_evaluation_seconds",
+			// "scheduler_e2e_scheduling_duration_seconds",
 			"scheduler_pod_scheduling_duration_seconds",
 		},
 	}
```

And then run:

```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling/SchedulingBasic/500Nodes"
```

You will get an output sth. like:

```
+++ [0218 15:31:02] Running tests without code coverage
[DEBUG] 263 le 0.01
[DEBUG] 367 le 0.02
[DEBUG] 449 le 0.04
[DEBUG] 586 le 0.08
[DEBUG] 865 le 0.16
[DEBUG] 1210 le 0.32
[DEBUG] 1213 le 0.64
[DEBUG] 1446 le 1.28
[DEBUG] 1495 le 2.56
[DEBUG] 1500 le 5.12
[DEBUG] 1500 le 10.24
[DEBUG] 1500 le 20.48
[DEBUG] 1500 le 40.96
[DEBUG] 1500 le 81.92
[DEBUG] 1500 le 163.84
[DEBUG] 1500 le 327.68
[DEBUG] 1500 le 655.36
[DEBUG] 1500 le 1310.72
[DEBUG] 1500 le 2621.44
[DEBUG] 1500 le 5242.88
[DEBUG] 1500 le +Inf
......
```

/sig scheduling

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/sig scheduling

#### What this PR does / why we need it:

Fix a bug in scheduler integration perf test that metrics of init or collected pods get re-collected. See https://github.com/kubernetes/kubernetes/issues/99218#issuecomment-786226360 for more details.

After applying this fix, running:

```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -benchtime=1ns -bench=BenchmarkPerfScheduling/SchedulingBasic"
```

will observe 1000 measure Pods getting collected:

<details><summary>Output:</summary>
<p>

```
[DEBUG] 35 le 0.01
[DEBUG] 102 le 0.02
[DEBUG] 228 le 0.04
[DEBUG] 297 le 0.08
[DEBUG] 350 le 0.16
[DEBUG] 409 le 0.32
[DEBUG] 790 le 0.64
[DEBUG] 921 le 1.28
[DEBUG] 985 le 2.56
[DEBUG] 1000 le 5.12
[DEBUG] 1000 le 10.24
[DEBUG] 1000 le 20.48
[DEBUG] 1000 le 40.96
[DEBUG] 1000 le 81.92
[DEBUG] 1000 le 163.84
[DEBUG] 1000 le 327.68
[DEBUG] 1000 le 655.36
[DEBUG] 1000 le 1310.72
[DEBUG] 1000 le 2621.44
[DEBUG] 1000 le 5242.88
[DEBUG] 1000 le +Inf
pkg: k8s.io/kubernetes/test/integration/scheduler_perf
BenchmarkPerfScheduling/SchedulingBasic/500Nodes-4         	       1	14656122851 ns/op

[DEBUG] 0 le 0.01
[DEBUG] 0 le 0.02
[DEBUG] 6 le 0.04
[DEBUG] 14 le 0.08
[DEBUG] 30 le 0.16
[DEBUG] 70 le 0.32
[DEBUG] 175 le 0.64
[DEBUG] 365 le 1.28
[DEBUG] 968 le 2.56
[DEBUG] 1000 le 5.12
[DEBUG] 1000 le 10.24
[DEBUG] 1000 le 20.48
[DEBUG] 1000 le 40.96
[DEBUG] 1000 le 81.92
[DEBUG] 1000 le 163.84
[DEBUG] 1000 le 327.68
[DEBUG] 1000 le 655.36
[DEBUG] 1000 le 1310.72
[DEBUG] 1000 le 2621.44
[DEBUG] 1000 le 5242.88
[DEBUG] 1000 le +Inf
BenchmarkPerfScheduling/SchedulingBasic/5000Nodes-4        	       1	37273363857 ns/op
```

</p>
</details> 

#### Which issue(s) this PR fixes:

Fixes #99218

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/scheduler_perf/util.go [hunk 1]
```diff
@@ -199,10 +199,6 @@ func collectHistogram(metric string, labels map[string]string) *DataItem {
 	q99 := hist.Quantile(0.95)
 	avg := hist.Average()
 
-	// clear the metrics so that next test always starts with empty prometheus
-	// metrics (since the metrics are shared among all tests run inside the same binary)
-	hist.Clear()
```
Comment (alculquicondor) [inline test/integration/scheduler_perf/util.go:204]: shouldn't we still call Reset here?

**Review by alculquicondor — COMMENTED** [review]
/assign @logicalhan

File: test/integration/scheduler_perf/util.go (hunk 1 above)
Comment (Huang-Wei) [reply test/integration/scheduler_perf/util.go:204]: Not really, Reset() or Clear() doesn't behave as we expected.

Comment (alculquicondor) [reply test/integration/scheduler_perf/util.go:204]: How can we prevent metrics from leaking into the next test then?

Comment (Huang-Wei) [reply test/integration/scheduler_perf/util.go:204]: We now have the new logic in test/integration/scheduler_perf/scheduler_perf_test.go:

```go
if !concreteOp.SkipWaitToCompletion {
    // SkipWaitToCompletion=false indicates this step have waited for the Pods to be scheduled.
    // So we reset the metrics in global registry; otherwise metrics gathered in this step/test
    // will be rolled over to next step/test.
    legacyregistry.Reset()
}
```

Comment (alculquicondor) [reply test/integration/scheduler_perf/util.go:204]: but that's conditional.... better safe to always remove

Comment (Huang-Wei) [reply test/integration/scheduler_perf/util.go:204]: > better safe to always remove

An unconditional reset doesn't make a lot of sense, as during the asynchronous (SkipWaitToCompletion=true) createPods operation, we cannot really get rid of their metrics. This is also mentioned in https://github.com/kubernetes/kubernetes/issues/99218#issuecomment-782297367. So I choose to only reset when it's a synchronous operation.

Comment (ingvagabund) [reply test/integration/scheduler_perf/util.go:204]: As @alculquicondor mentioned, let's assume this configuration (`skipWaitToCompletion` is `false` in all cases):
```
- name: Unschedulable
  workloadTemplate:
  - opcode: createNodes
    countParam: $initNodes
  - opcode: createPods
    countParam: $measurePods
    podTemplatePath: config/pod-default.yaml
    collectMetrics: true
  workloads:
  - name: 500Nodes/1000Pods
    params:
      initNodes: 500
      measurePods: 1000
  - name: 5000Nodes/5000Pods
    params:
      initNodes: 5000
      measurePods: 5000
```
Once the second workload (`5000Nodes/5000Pods`) gets ran, metrics collected from the previous workload will get counted as well. I second what @alculquicondor says. `Reset()` needs to be ran at every end of `for opIndex, op := range tc.WorkloadTemplate` loop at least.

Comment (ingvagabund) [reply test/integration/scheduler_perf/util.go:204]: > as during the asynchronous (SkipWaitToCompletion=true) createPods operation, we cannot really get rid of their metrics

I see the point. In which case we need to wait until all pods get scheduled before the next workload gets processed.

File: test/integration/scheduler_perf/scheduler_perf_test.go [hunk 2]
```diff
@@ -387,6 +388,13 @@ func runWorkload(b *testing.B, tc *testCase, w *workload) []DataItem {
 				mu.Unlock()
 			}
 
+			if !concreteOp.SkipWaitToCompletion {
+				// SkipWaitToCompletion=false indicates this step have waited for the Pods to be scheduled.
+				// So we reset the metrics in global registry; otherwise metrics gathered in this step/test
+				// will be rolled over to next step/test.
```
Comment (adtac) [inline test/integration/scheduler_perf/scheduler_perf_test.go:394]: doing this even when this step doesn't collect metrics is a bit wasteful, no? I think we could change the condition to `CollectMetrics && !SkipWaitToCompletion`? I don't mind leaving this as it is to be more defensive, I'm only interested in knowing if what I said is true as a sanity check

File: test/integration/scheduler_perf/util.go (hunk 1 above)
Comment (adtac) [reply test/integration/scheduler_perf/util.go:204]: I agree, we should reset at the end of every workload but that is implicitly guaranteed because we don't have any workloadTemplate that uses SkipWaitToCompletion as the last step (which doesn't really make sense). perhaps we should add guards to make SkipWaitToCompletion in the last step isn't possible.

Comment (Huang-Wei) [reply test/integration/scheduler_perf/util.go:204]: @adtac is right, however, we probably don't want to ban the pattern using SkipWaitToCompletion at the last step, so adding a double-check at the end of each workload's running is fine with me. Updated the code.

> I second what @alculquicondor says. `Reset()` needs to be ran at every end of `for opIndex, op := range tc.WorkloadTemplate` loop at least.

Technically correct, but to save cost, we only need to run Reset() when SkipWaitToCompletion is false.

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 2 above)
Comment (Huang-Wei) [reply test/integration/scheduler_perf/scheduler_perf_test.go:394]: Not quite, in some case, it's intentional to only initialize Pods, but not collect metrics of them:

```yaml
- name: SchedulingBasic
  workloadTemplate:
  - opcode: createNodes
    countParam: $initNodes
  - opcode: createPods
    countParam: $initPods
    podTemplatePath: config/pod-default.yaml
```

This step generates metrics, so we should get them cleared.

File: test/integration/scheduler_perf/util.go (hunk 1 above)
Comment (alculquicondor) [reply test/integration/scheduler_perf/util.go:204]: Current logic for resetting lgtm

File: test/integration/scheduler_perf/scheduler_perf_test.go [hunk 3]
```diff
@@ -33,6 +33,7 @@ import (
 	clientset "k8s.io/client-go/kubernetes"
 	"k8s.io/component-base/featuregate"
 	featuregatetesting "k8s.io/component-base/featuregate/testing"
+	"k8s.io/component-base/metrics/legacyregistry"
```
Comment (alculquicondor) [inline test/integration/scheduler_perf/scheduler_perf_test.go:36]: should we be migrating off the legacyregistry?

Comment (Huang-Wei) [reply test/integration/scheduler_perf/scheduler_perf_test.go:36]: I will leave it for sig-instrumentation to comment.

BTW: this is not a brand new dependency - scheduler_perf/util.go used to and still depends on it.

**Comment by Huang-Wei** [comment]
@logicalhan could you take a look, or re-assign to the proper sig-instrumentation expert? Thanks.

/assign @logicalhan 
/priority important-soon

**Comment by Huang-Wei** [comment]
@alculquicondor @adtac @ingvagabund Any other comments before I pursue approval from sig-instrumentation?

File: test/integration/scheduler_perf/scheduler_perf_test.go [hunk 4]
```diff
@@ -387,6 +391,13 @@ func runWorkload(b *testing.B, tc *testCase, w *workload) []DataItem {
 				mu.Unlock()
 			}
 
+			if !concreteOp.SkipWaitToCompletion {
```
Comment (chendave) [inline test/integration/scheduler_perf/scheduler_perf_test.go:394]: This line could move  up to @Line380.

Instead of those check, why not resetting the registry only when collecting the metrics as my proposal here?
https://github.com/kubernetes/kubernetes/pull/97757/files

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go [hunk 5]
```diff
@@ -281,21 +281,6 @@ func (hist *Histogram) Average() float64 {
 	return hist.GetSampleSum() / float64(hist.GetSampleCount())
 }
 
-// Clear clears all fields of the wrapped histogram
-func (hist *Histogram) Clear() {
```
Comment (chendave) [inline staging/src/k8s.io/component-base/metrics/testutil/metrics.go:285]: Is this method only called by scheduler?

**Comment by alculquicondor** [comment]
It looks like Han is OOO.

/assign @dashpole

**Comment by Huang-Wei** [comment]
@alculquicondor I joined today's sig-instrumentation weekly meeting, @logicalhan said he will review :)

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 4 above)
Comment (Huang-Wei) [reply test/integration/scheduler_perf/scheduler_perf_test.go:394]: > This line could move up to @Line380.

Nope, you have to wait for collectors to finish their collecting.

> why not resetting the registry only when collecting the metrics as my proposal here?

Upon completion of an operator (step) of each workload, we need to reset if needed - think about the case of InitPods.

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go (hunk 5 above)
Comment (Huang-Wei) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics.go:285]: As far as I can tell, yes.

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 4 above)
Comment (chendave) [reply test/integration/scheduler_perf/scheduler_perf_test.go:394]: > Upon completion of an operator (step) of each workload, we need to reset if needed - think about the case of InitPods.

`InitPods` is a different case, iiuc, `collectMetrics` is set only with `measurePods`, we can clear all the stale metric before we are really measure something, all the data generated before could be discarded.

File: test/integration/scheduler_perf/scheduler_perf_test.go [hunk 6]
```diff
@@ -296,6 +297,9 @@ func BenchmarkPerfScheduling(b *testing.B) {
 						defer featuregatetesting.SetFeatureGateDuringTest(b, utilfeature.DefaultFeatureGate, feature, flag)()
 					}
 					dataItems.DataItems = append(dataItems.DataItems, runWorkload(b, tc, w)...)
+					// Reset metrics to prevent metrics generated in current workload gets
+					// carried over to the next workload.
+					legacyregistry.Reset()
```
Comment (chendave) [inline test/integration/scheduler_perf/scheduler_perf_test.go:302]: what I meant is `Reset` is not always needed, this will reset `testcase*workload` times while most of `reset` here as far as I can see is not necessary.

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 4 above)
Comment (Huang-Wei) [reply test/integration/scheduler_perf/scheduler_perf_test.go:394]: I don't think it's a good idea to clear the metrics generated in **previous** steps at the beginning of the **current** step. Each test/step is better designed atomic and stateless - in other words, a test/step should clear its metrics upon its completion, instead of leaving the leftover for subsequent test/step to clear.

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 6 above)
Comment (Huang-Wei) [reply test/integration/scheduler_perf/scheduler_perf_test.go:302]: Yes, it's discussed here: https://github.com/kubernetes/kubernetes/pull/99472#discussion_r584435795

File: test/integration/scheduler_perf/scheduler_perf_test.go (hunk 4 above)
Comment (adtac) [reply test/integration/scheduler_perf/scheduler_perf_test.go:394]: while both approaches are probably functionally similar, I agree with @Huang-Wei that each step should be cleaning up after itself

**Review by adtac — COMMENTED** [review]
/lgtm

**Comment by ahg-g** [comment]
/milestone v1.21

This PR improves testing, hence eligible for the milestone.

**Review by logicalhan — COMMENTED** [review]
/lgtm
(for the bit in component-base since you're just removing code)
/approve
