### PR TITLE
Use any host that mounts the datastore to create Volume

### LINKED ISSUE #75091: Volume creation fails with "A component of the virtual machine is not accessible on the host"
**What happened**:
Creation of Volume on vSphere Cloud Provider failed with error "A component of the virtual machine is not accessible on the host" under these conditions:

Assume we have following setup.

```
DC1
    cls1 - zone-a
        vsandatastore-1     (SPBM Policy: spbm-policy-1)
        host-1  - localds1
        host-2  - localds2
        host-3  - localds3
        resource-pool1

    cls2 – zone-b
        vsandatastore-2     (SPBM Policy: spbm-policy-2)
        host-4 - localds4
        host-5 - localds5 
        host-6 - localds6
        resource-pool2
```

If vsphere.conf has `resourcepool-path="cls1/resource-pool1"` then the dummy VM for a SPBM policy based Volume will be created on this resource pool.

However, if the volume is provisioned using a SC that uses spbm-policy-2 on zone: zone-b, then the Volume creation fails with this error - Failed to provision volume with StorageClass "xxx": A component of the virtual machine is not accessible on the host.

**What you expected to happen**:
One work around is to correct the entry in vsphere.conf as `resourcepool-path="cls2/resource-pool2"` in the above example. This will then allow the Volume to be created in this cluster cls2.

However, the next Volume creation on the first cluster cls1 will once again face the same issue. Changing the configuration in vsphere.conf and restarting the kube services potentially every time a Volume needs to be created is a very inferior work around.

The right behaviour is for vSphere Cloud Provider to either
1. provide a way for users to configure both the resource pools, one for each zone, in vsphere.conf
2. automatically detect the right 'resource pool' to use when creating a Volume.

I would prefer the approach 2.

**How to reproduce it (as minimally and precisely as possible)**:
Already described above.

**Anything else we need to know?**:
This issue affects only when SPBM policy is used in Volume creation.

**Environment**:
- Kubernetes version (use `kubectl version`): all
- Cloud provider or hardware configuration: vsphere

/sig vmware
/sig cloud-provider

### PR DESCRIPTION
**Pull request by subramanian-neelakantan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When there is more than one cluster in a VC without a shared datastore, and an SPBM storage policy is used in the SC, the user has to specify one of the cluster as the `resourcepool-path` to use for Volume creation. This is a problem with multi-zone environments where two zones do not have a common shared datastore among them. So this PR does away with the need to specify a `resourcepool-path` in the vsphere.conf file totally.

The change here is to automatically figure out a host to use for creating the dummy VM for the Volume. Once the Volume's datastore is determined (based on user provided inputs of optional datastore, storage policy and zone), any host that mounts that datastore is picked to create the dummy VM. This should work since the VM is anyway deleted soon after and the VMDK for the Volume gets placed on the determined datastore correctly.

**Which issue(s) this PR fixes**:
Fixes #75091

**Special notes for your reviewer**:
* The VMOptions now has an additional field to hold the host. The ResourcePool is filled with the host's resource pool.
* The setVMOptions() method is changed to pick a host at random from among those that mount the given datastore.
* Fixed a minor bug in Datastore.GetDatastoreHostMounts() where an empty array was initialized and then elements were "appended" to it, making the array twice the size and the first half with empty elements.
* Added a e2e test specific to this scenario. The complete e2e tests pass with this change, as well as the new test added (that fails without this change) passes now.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SandeepPissay** [comment]
I have a concern about this:

> Once the Volume's datastore is determined (based on user provided inputs of optional datastore, storage policy and zone), any host that mounts that datastore is picked to create the dummy VM. This should work since the VM is anyway deleted soon after and the VMDK for the Volume gets placed on the determined datastore correctly

What if the dummy VM could not be deleted for whatever reasons? We have observed this issue in the past. The current design is that the dummy VMs are created under a particular Virtual Center/Datacenter/Folder and a background task keeps cleaning it up. If we are creating the dummy VM on any host under any datacenter, the dummyVMs may appear/remain indefinitely. How do you plan to solve this problem?

**Comment by subramanian-neelakantan** [comment]
@SandeepPissay thanks for taking a look and sharing your comments.

> I have a concern about this:
> 
> > Once the Volume's datastore is determined (based on user provided inputs of optional datastore, storage policy and zone), any host that mounts that datastore is picked to create the dummy VM. This should work since the VM is anyway deleted soon after and the VMDK for the Volume gets placed on the determined datastore correctly
> 
> What if the dummy VM could not be deleted for whatever reasons? We have observed this issue in the past. The current design is that the dummy VMs are created under a particular Virtual Center/Datacenter/Folder and a background task keeps cleaning it up. If we are creating the dummy VM on any host under any datacenter, the dummyVMs may appear/remain indefinitely. How do you plan to solve this problem?

The dummy VM is still created under a VM folder. The cleanup routine identifies dummy VMs by looking for VM names with a prefix under the configured VM folder. This folder can be configured by the user in `vsphere.conf` file as shown here.
```
[Workspace]
    folder = <folder_name>
```
So this is working as expected and should not be a concern.

**Comment by divyenpatel** [comment]
@subramanian-neelakantan Can you also remove `ResourcePoolPath` from Workspace struct.
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L190

rest looks good to me.

**Review by divyenpatel — APPROVED** [review]
/approve

File: test/e2e/storage/vsphere/vsphere_zone_support.go [hunk 1]
```diff
@@ -176,6 +176,13 @@ var _ = utils.SIGDescribe("Zone Support", func() {
 		verifyPVCAndPodCreationSucceeds(client, namespace, scParameters, zones)
 	})
 
+	It("Verify a pod is created and attached to a dynamically created PV, based on the allowed zones and storage policy specified in storage class", func() {
```
Comment (oomichi) [inline test/e2e/storage/vsphere/vsphere_zone_support.go]: It is better to make the test name different from line 172 for distinguishing which test is failed if that happens.

**Comment by SandeepPissay** [comment]
@subramanian-neelakantan Lets take this example. Say, the Virtual Center inventory is as below:

DC1
    cls1 - zone-1
        host-1 
        host-2
        host-3

DC2
    cls2 – zone-2
        host-4
        host-5
        host-6

Note: DC = "Datacenter"; cls = "Compute Cluster"

Say there is no shared datastores across cls1 and cls2. And say the vSphere.conf had this workspace configuration:

[Workspace]
    datacenter = "DC1"
    folder = folder1

If the PV is created on zone-1, where(under which folder) is the dummy VM created? If the PV is created on zone-2, where(under which folder) is the dummy VM created? How does dummy VM cleanup background task work in these two scenarios? I see a problem with your logic of choosing any host for dummy VM creation since the cleanup thread deletes dummy VM only under one DC.

**Comment by divyenpatel** [comment]
@SandeepPissay, @subramanian-neelakantan 

In the `CleanUpDummyVMs` routine
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vclib/diskmanagers/vmdm.go#L233

We are wrapping `object.NewVirtualMachine(dc.Client(), vm.Reference())` into `vclib.VirtualMachine`. 

This is not required as `DeleteVM` function of `vclib.VirtualMachine` is not using datacenter. All we need is vm MoRef and vc client, which can also be retrieved using folder.client. I think we should also  remove `Datacenter` from `Workspace`.

and for `Folder` in the workspace, we should ask user to specify folder name created under VC root which is accessible to all datacenters in the VC.
 
image

**Comment by SandeepPissay** [comment]
@divyenpatel If we can create a VM under any datacenter and one folder at root level, then that should solve the concern I had. The background task that cleans up the dummy VMs can look into this this folder. @subramanian-neelakantan could you confirm if this solution works?

If this is not a workable solution, then the background task should be able to identify dummy VMs somehow (searching inventory by VM name prefix or reading dummy VM morefs in API server etc).

File: test/e2e/storage/vsphere/vsphere_zone_support.go (hunk 1 above)
Comment (subramanian-neelakantan) [reply test/e2e/storage/vsphere/vsphere_zone_support.go]: Good point @oomichi. I will rename this test.

**Comment by subramanian-neelakantan** [comment]
> @subramanian-neelakantan Can you also remove `ResourcePoolPath` from Workspace struct.
> https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L190

Sure @divyenpatel.

Regarding your comment on `CleanUpDummyVMs` routine not using Datacenter, that is a good point. I will see if I can incorporate this change. However the complete removal of dependency on Workspace.Datacenter across all of VCP volume provisioning seems to be a larger task. We could do that as part of a different PR. I agree that removing the dependency on `[Workspace]` section for Volume provisioning is the right direction to take, and this PR is already removing the dependency on `Workspace.ResourcePoolPath`. Agree?

Regarding your comment on using a folder under the VC root to create the dummy VM - unfortunately this does not work (I wish it had). The problem is that a high-level folder cannot hold VMs. I am able to create VMs only within folders that are under a Datacenter.

Coming to @SandeepPissay's comments:
> @divyenpatel If we can create a VM under any datacenter and one folder at root level, then that should solve the concern I had. The background task that cleans up the dummy VMs can look into this this folder. @subramanian-neelakantan could you confirm if this solution works?
> 
> If this is not a workable solution, then the background task should be able to identify dummy VMs somehow (searching inventory by VM name prefix or reading dummy VM morefs in API server etc).

@SandeepPissay, unfortunately this does not work for reasons explained above. Since this approach cannot work, the background task to cleanup dummy VMs would have to look for this folder in each Datacenter and remove VMs starting with the prefix in such a folder. This folder will still be configured under the `[Workspace]` section. I will update this PR soon with these changes. Any preliminary thoughts on this approach? Any other approaches possible here? I did not understand what you meant by "reading dummy VM morefs in API server".

Can you review the approach I am planning to take and share your comments? Really appreciate your insights into VCP and effort to make this work correctly for the user.

**Comment by subramanian-neelakantan** [comment]
@SandeepPissay, @divyenpatel, To address your comment on safely deleting the dummy VMs across all datacenters, I had to reproduce the issue first. Doing that I figured out that zone support does not work well when there are multiple datacenters in VC since the volume creation always used the Datacenter taken from [Workspace] section of vsphere.conf. So the usage of [Workspace] Datacenter for volume creation should be removed similar to resourcepool-path.

In this second commit https://github.com/kubernetes/kubernetes/pull/75187/commits/813f07698bb8aacc939f96e79cf8a46670ff41e7, I have tried to clean up the usage of Datacenter taken from [Workspace] section of vsphere.conf. The list of changes include:
1. The Volume provisioning workflow looks for the given datastore in all the Datacenters of VC(s) and not just in the datacenter mentioned in [Workspace] section of vsphere.conf. The volume is finally created in a folder of this datacenter.
2. So some places in code that were not populating the `Datacenter` field within the `DatastoreInfo` had to fixed up. For example, in virtualmachine.go:VirtualMachine.GetAllAccessibleDatastores() and vsphere_util.go:getDatastoresForZone() methods.
3. The validations performed within VSphere.CreateVolume() method use the datastore's URL instead of name.
4. Similarly the logic to cleanup dummy VMs also look for the dummy VMs across all the datacenters of VC(s).

With these changes, the e2e tests of VCP run successfully (with only 4 known failures that are unrelated). The unit tests also pass.

Please take another look. I have kept the commits separate to help with incremental reviews.

**Comment by subramanian-neelakantan** [comment]
> @subramanian-neelakantan Can you also remove `ResourcePoolPath` from Workspace struct.
> https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L190

This needs to be done more carefully. This will break existing deployments. kubelet will fail to startup until resourcepool-path is removed from vsphere.conf. Due to backward compatibility issue I have left this in for now.

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go [hunk 2]
```diff
@@ -675,3 +648,59 @@ func GetNodeUUID(node *v1.Node) (string, error) {
...
+				datacenterObjs = append(datacenterObjs, datacenterObj)
+			}
+		}
+	}
+	return datacenterObjs, nil
+}
+
+// FindDatastore looks for the given datastore by name across all available datacenters.
+// Returns the first found entry. If more than one Datacenter has a Datastore with the given
+// name, then
```
[the remark this answers is not in the document]
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: Thanks. Corrected the comments.

File: pkg/cloudprovider/providers/vsphere/vclib/datacenter.go [hunk 3]
```diff
@@ -187,6 +187,29 @@ func (dc *Datacenter) GetDatastoreByName(ctx context.Context, name string) (*Dat
...
+	if err != nil {
+		klog.Errorf("Failed while searching for datastore: %s. err: %+v", name, err)
+		return nil, err
+	}
+	datastore := Datastore{ds, dc}
+	var dsMoList []mo.Datastore
+	dsRefList := []types.ManagedObjectReference{ds.Reference()}
+	pc := property.DefaultCollector(dc.Client())
+	properties := []string{DatastoreInfoProperty}
+	err = pc.Retrieve(ctx, dsRefList, properties, &dsMoList)
```
[the remark this answers is not in the document]
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vclib/datacenter.go]: Sounds good. Will do.

File: pkg/cloudprovider/providers/vsphere/vclib/constants.go [hunk 4]
```diff
@@ -52,6 +52,7 @@ const (
 	DatacenterType             = "Datacenter"
 	ClusterComputeResourceType = "ClusterComputeResource"
 	HostSystemType             = "HostSystem"
+	Name                       = "name"
```
[the remark this answers is not in the document]
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vclib/constants.go]: Yes, NameProperty sounds better. Will change.

File: pkg/cloudprovider/providers/vsphere/nodemanager.go [hunk 5]
```diff
@@ -39,6 +39,11 @@ type NodeInfo struct {
 	zone       *cloudprovider.Zone
 }
 
+func (n *NodeInfo) String() string {
+	return fmt.Sprintf("{datacenter: %s, vm: %s, vcServer: %s, vmUUID: %s, zone: %s}",
```
[the remark this answers is not in the document]
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/nodemanager.go]: Sure, will change the format to %v for datacenter, vm and zone. The log line will look like this.
```
I0318 03:27:19.059266       1 nodemanager.go:300] Renewing NodeInfo {datacenter: Datacenter:datacenter-3, vm: VirtualMachine:vm-112, vcServer: 10.192.214.35, vmUUID: 421a4973-4b23-94c3-d469-437de857de63, zone: {z1 r1}} for node "node1"
```

File: pkg/cloudprovider/providers/vsphere/nodemanager.go [hunk 6]
```diff
@@ -39,6 +39,11 @@ type NodeInfo struct {
 	zone       *cloudprovider.Zone
 }
 
+func (n *NodeInfo) String() string {
```
[the remark this answers is not in the document]
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/nodemanager.go]: I added this in so that NodeInfo gets printed correctly in the controller logs. Otherwise we see only pointer addresses in the logs which is not very useful:
```
I0313 03:23:55.927698       1 nodemanager.go:319] Updated NodeInfo {0xc000617e68 0xc001c872c0 10.161.113.44 42152c0a-5802-4b6f-7e72-d806b0da233d 0xc000f61520} for node "node5".
```

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go [hunk 7]
```diff
@@ -316,45 +319,54 @@ func getDatastoresForZone(ctx context.Context, dc *vclib.Datacenter, nodeManager
...
 	}
-	klog.V(9).Infof("Resource pool path %s, resourcePool %+v", resourcePoolPath, resourcePool)
-	folder, err := dc.GetFolderByPath(ctx, vs.cfg.Workspace.Folder)
+	folder, err := ds.Datacenter.GetFolderByPath(ctx, vs.cfg.Workspace.Folder)
 	if err != nil {
 		return nil, err
 	}
 	vmOptions.VMFolder = folder
 	vmOptions.VMResourcePool = resourcePool
+	vmOptions.VMHost = dummyVMHost
```
Comment (SandeepPissay) [inline pkg/cloudprovider/providers/vsphere/vsphere_util.go]: Since we already know the folder and host resource pool, do we need dummyVMHost? If no, could you please remove it?

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 8]
```diff
@@ -1164,40 +1164,40 @@ func (vs *VSphere) DisksAreAttached(nodeVolumes map[k8stypes.NodeName][]string)
...
 		if err != nil {
 			return "", err
 		}
-		dc, err := vclib.GetDatacenter(ctx, vsi.conn, vs.cfg.Workspace.Datacenter)
+		// If datastore not specified, then use default datastore
+		datastoreName := strings.TrimSpace(volumeOptions.Datastore)
+		if datastoreName == "" {
+			datastoreName = strings.TrimSpace(vs.cfg.Workspace.DefaultDatastore)
+		}
+		datastoreInfo, err = vs.FindDatastore(ctx, datastoreName)
```
Comment (SandeepPissay) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: How would volume creation work if allowedTopologies is specifying zone-1 and this code is selecting a datastore in zone-2?

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go (hunk 7 above)
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: Sure will do.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 8 above)
Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vsphere.go]: Changed this to consider all matching datastores (across datacenters) and allow the other inputs like zone or storage profile to pick out one of these datastores that also match the zone or storage profile.

Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vsphere.go]: Changed this to consider all matching datastores (across datacenters) and allow the other inputs like zone or storage profile to pick out one of these datastores that also match the zone or storage profile.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 9]
```diff
@@ -1317,11 +1318,24 @@ func (vs *VSphere) CreateVolume(volumeOptions *vclib.VolumeOptions) (canonicalVo
 				}
 			}
 		}
-		ds, err := dc.GetDatastoreByName(ctx, datastore)
+
+		// When zone or storage profile is not specified in storage class, datastoreInfo is still not determined
+		if datastoreInfo == nil {
```
Comment (skarthiksrinivas) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: As per the existing if else blocks above, looks like datastoreInfo is not expected to be nil at this point.

Comment (subramanian-neelakantan) [reply pkg/cloudprovider/providers/vsphere/vsphere.go]: Removed this check and raised an error here if datastoreInfo is still nil.

**Comment by andrewsykim** [comment]
@subramanian-neelakantan the vSphere cloud provider was moved to staging so this PR needs to be rebased updating the new location https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/vsphere

File: staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go [hunk 10]
```diff
@@ -265,7 +243,7 @@ func getDatastoresForZone(ctx context.Context, dc *vclib.Datacenter, nodeManager
 
 		for _, host := range hosts {
 			var hostSystemMo mo.HostSystem
-			err = host.Properties(ctx, host.Reference(), []string{"datastore"}, &hostSystemMo)
+			err = host.Properties(ctx, host.Reference(), []string{"datastore", "parent"}, &hostSystemMo)
```
Comment (skarthiksrinivas) [inline staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go]: This parent might not be needed at this step since you are using Ancestors() to find the parent dc.

Comment (subramanian-neelakantan) [reply staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util.go]: Done. Thanks for the review.

**Comment by subramanian-neelakantan** [comment]
/assign @jsafrane @saad-ali @gnufied @rootfs 
Can one you kindly review this PR and mark your approval as owner of test/e2e/storage/OWNERS? Thanks.

**Comment by jsafrane** [comment]
/approve
test changes
