### PR TITLE
[kubelet]: Fix the bug where pod grace period will be overwritten

### LINKED ISSUE #64530: minimumGracePeriodInSeconds from eviction config can increase the grace period
/kind bug
/sig node
cc @mtaufen 

We use the gracePeriodOverride from the eviction manager (which is set to m.config.MaxPodGracePeriodSeconds for soft evictions) as the gracePeriodOverride that we pass to `killPod()`
This is consumed here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L568
Where it overrides whatever the pod's DeletionGracePeriodSeconds and Spec.TerminationGracePeriodSeconds.  Either the name is misleading, or it isn't actually a maximum, but rather is just "the" grace period for soft evictions.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The `spec.terminationGracePeriodSeconds` of the pod will always be overwritten by the `MaxPodGracePeriodSeconds` of the soft eviction, which is not as described in the documentation
ref: https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#soft-eviction-thresholds
>  If you specify a maximum allowed grace period and the soft eviction threshold is met, the kubelet uses the lesser of the two grace periods.

#### Which issue(s) this PR fixes:

Fixes #64530

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug where spec.terminationGracePeriodSeconds of the pod will always be overwritten by the MaxPodGracePeriodSeconds of the soft eviction, you can enable the `AllowOverwriteTerminationGracePeriodSeconds` feature gate, which will restore the previous behavior.  If you do need to set this, please file an issue with the Kubernetes project to help contributors understand why you need it.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
/lgtm
should we cover this with tests?

**Review by bboreham — COMMENTED** [review]
I confess it has been a while since I looked in detail at kublet code, but the change looks to me to match the documented behaviour. 

> Does this PR introduce a user-facing change?

I think it does. I would recommend a release note pointing this out to users.

Should [this comment](https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L524) be updated in this PR?

**Comment by bboreham** [comment]
Oh, and thanks!  Bug open for nearly 6 years.

**Comment by bart0sh** [comment]
/triage accepted
/priority important-longterm

@HirazawaUi As this is a bugfix it would be nice to cover this case with either unit or e2e tests.

**Comment by HirazawaUi** [comment]
> should we cover this with tests?

of course

**Comment by HirazawaUi** [comment]
> Should [this comment](https://github.com/kubernetes/kubernetes/blob/a07b1aaa5b39b351ec8586de800baa5715304a3f/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L524) be updated in this PR?

Yes, these comments can be removed when this PR is merged.

**Review by justankiit — COMMENTED** [review]
lgtm

**Comment by HirazawaUi** [comment]
> As this is a bugfix it would be nice to cover this case with either unit or e2e tests.

e2e test code has been added.

**Comment by yujuhong** [comment]
> Yes, these comments can be removed when this PR is merged.

Why not updating it in this PR as well?

**Comment by HirazawaUi** [comment]
> Why not updating it in this PR as well?

all right

**Comment by yujuhong** [comment]
Need a release note since the PR fixes a known issue

**Comment by HirazawaUi** [comment]
> Need a release note since the PR fixes a known issue

added.

**Comment by SergeyKanzhelev** [comment]
This PR changes the behavior in non backward compatible way. As per deprecation policy we need to make an announcement first and provide a reasonable way to transition users to this behavior: https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior

/lgtm cancel
/sig architecture

I don't know how widely this field is being used out wild. So we may decide that the comment was enough of a warning. But having a way to switch it back to the previous behavior for at least a couple of releases would be desirable. Added sig architecture for an opinion or the best practice. Would the env variable suffice?

**Comment by SergeyKanzhelev** [comment]
Discussed with @mrunalp and the suggestion is to introduce the environment variable that will return the old behavior. We can remove it in couple of releases. Also linked in sig arch slack: https://kubernetes.slack.com/archives/C5P3FE08M/p1709142442365899

**Comment by HirazawaUi** [comment]
@SergeyKanzhelev  I used the approach in PR #119789, added a new feature gate to ensure backward compatibility :)

File: test/e2e_node/eviction_test.go [hunk 1]
```diff
@@ -248,6 +248,44 @@ var _ = SIGDescribe("LocalStorageSoftEviction", framework.WithSlow(), framework.
 	})
 })
 
+var _ = SIGDescribe("LocalStorageSoftEvictionNotOverwriteTerminationGracePeriodSeconds", framework.WithSlow(), framework.WithSerial(), framework.WithDisruptive(), nodefeature.Eviction, func() {
```
Comment (gjkim42) [inline test/e2e_node/eviction_test.go:251]: Could you confirm that this test passes?
(Not sure there is a job focusing Slow, Serial, and Disruptive)

**Review by gjkim42 — COMMENTED** [review]
The fix looks good to me.

**Comment by gjkim42** [comment]
nit:

> ...of the soft eviction, , you can enable...

Please correct the release note part of the PR description.

**Comment by HirazawaUi** [comment]
This test is green in my local environment, but it will error in the CI environment, and `
pull-kubernetes-cos-cgroupv2-containerd-node-e2e-eviction`  is a very fragile test task, and other test cases will fail when I run the test.

```
➜  kubernetes make  test-e2e-node FOCUS="LocalStorageSoftEvictionNotOverwriteTerminationGracePeriodSeconds" SKIP="" TEST_ARGS='--ginkgo.vv'
go version go1.21.6 linux/amd64
+++ [0318 00:18:23] Building go targets for linux/amd64
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
go version go1.21.6 linux/amd64
+++ [0318 00:18:25] Set GOMAXPROCS automatically to 16
Creating artifacts directory at /tmp/_artifacts/240318T001825
Test artifacts will be written to /tmp/_artifacts/240318T001825
No need to refresh sudo credentials
I0318 00:18:37.013372  294025 build.go:59] Building k8s binaries...
+++ [0318 00:18:37] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubelet (non-static)
I0318 00:18:42.764449  294025 build.go:59] Building k8s binaries...
+++ [0318 00:18:42] Building go targets for linux/amd64
    k8s.io/kubernetes/test/e2e_node/e2e_node.test (test)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/cluster/gce/gci/mounter (static)
    k8s.io/kubernetes/test/e2e_node/plugins/gcp-credential-provider (non-static)
I0318 00:18:48.843025  294025 run_local.go:58] Got build output dir: /home/bing/go/src/k8s.io/kubernetes/_output/local/go/bin
I0318 00:18:48.843057  294025 run_local.go:81] Running command: /home/bing/go/src/k8s.io/kubernetes/_output/local/go/bin/ginkgo -timeout=24h -nodes=8  -focus="LocalStorageSoftEvictionNotOverwriteTerminationGracePeriodSeconds"  /home/bing/go/src/k8s.io/kubernetes/_output/local/go/bin/e2e_node.test -- --v 4 --report-dir=/tmp/_artifacts/240318T001825 --node-name fedora --kubelet-flags="--cluster-domain=cluster.local" --dns-domain="cluster.local" --prepull-images=false  --container-runtime-endpoint=unix:///run/containerd/containerd.sock --ginkgo.vv --runtime-config= --kubelet-config-file="test/e2e_node/jenkins/default-kubelet-config.yaml"
Running Suite: E2eNode Suite - /home/bing/go/src/k8s.io/kubernetes/_output/local/go/bin
=======================================================================================
Random Seed: 1710692328 - will randomize all specs

Will run 1 of 558 specs
Running in parallel across 8 processes
  I0318 00:18:49.012180  295479 mount_linux.go:288] Detected umount with safe 'not mounted' behavior
  I0318 00:18:49.013422  295479 mount_linux.go:288] Detected umount with safe 'not mounted' behavior
  W0318 00:18:49.024119  295479 test_context.go:545] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
  I0318 00:18:49.024144  295479 test_context.go:560] Tolerating taints "node-role.kubernetes.io/control-plane" when considering if nodes are ready
  Mar 18 00:18:49.024: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
  I0318 00:18:49.024240  295479 feature_gate.go:254] feature gates: {map[]}
  I0318 00:18:49.024279  295479 feature_gate.go:254] feature gates: {map[]}
Validating os...
OS: Linux
Validating kernel...
KERNEL_VERSION: 6.5.11-300.fc39.x86_64
CONFIG_NAMESPACES: enabled
CONFIG_NET_NS: enabled
CONFIG_PID_NS: enabled
CONFIG_IPC_NS: enabled
CONFIG_UTS_NS: enabled
CONFIG_CGROUPS: enabled
CONFIG_CGROUP_CPUACCT: enabled
CONFIG_CGROUP_DEVICE: enabled
CONFIG_CGROUP_FREEZER: enabled
CONFIG_CGROUP_PIDS: enabled
CONFIG_CGROUP_SCHED: enabled
CONFIG_CPUSETS: enabled
CONFIG_MEMCG: enabled
CONFIG_INET: enabled
CONFIG_EXT4_FS: enabled
CONFIG_PROC_FS: enabled
CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
CONFIG_FAIR_GROUP_SCHED: enabled
CONFIG_OVERLAY_FS: enabled (as module)
CONFIG_AUFS_FS: not set - Required for aufs.
CONFIG_BLK_DEV_DM: enabled
CONFIG_CFS_BANDWIDTH: enabled
CONFIG_CGROUP_HUGETLB: enabled
CONFIG_SECCOMP: enabled
CONFIG_SECCOMP_FILTER: enabled
Validating cgroups...
CGROUPS_CPU: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
CGROUPS_IO: enabled
Validating package...
PASS
------------------------------
[SynchronizedBeforeSuite] PASSED [18.244 seconds]
[SynchronizedBeforeSuite] 
k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:225

  Captured StdOut/StdErr Output >>
    I0318 00:18:49.012180  295479 mount_linux.go:288] Detected umount with safe 'not mounted' behavior
    I0318 00:18:49.013422  295479 mount_linux.go:288] Detected umount with safe 'not mounted' behavior
    W0318 00:18:49.024119  295479 test_context.go:545] Unable to find in-cluster config, using default host : https://127.0.0.1:6443
    I0318 00:18:49.024144  295479 test_context.go:560] Tolerating taints "node-role.kubernetes.io/control-plane" when considering if nodes are ready
    Mar 18 00:18:49.024: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
    I0318 00:18:49.024240  295479 feature_gate.go:254] feature gates: {map[]}
    I0318 00:18:49.024279  295479 feature_gate.go:254] feature gates: {map[]}
  Validating os...
  OS: Linux
  Validating kernel...
  KERNEL_VERSION: 6.5.11-300.fc39.x86_64
  CONFIG_NAMESPACES: enabled
  CONFIG_NET_NS: enabled
  CONFIG_PID_NS: enabled
  CONFIG_IPC_NS: enabled
  CONFIG_UTS_NS: enabled
  CONFIG_CGROUPS: enabled
  CONFIG_CGROUP_CPUACCT: enabled
  CONFIG_CGROUP_DEVICE: enabled
  CONFIG_CGROUP_FREEZER: enabled
  CONFIG_CGROUP_PIDS: enabled
  CONFIG_CGROUP_SCHED: enabled
  CONFIG_CPUSETS: enabled
  CONFIG_MEMCG: enabled
  CONFIG_INET: enabled
  CONFIG_EXT4_FS: enabled
  CONFIG_PROC_FS: enabled
  CONFIG_NETFILTER_XT_TARGET_REDIRECT: enabled (as module)
  CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled (as module)
  CONFIG_FAIR_GROUP_SCHED: enabled
  CONFIG_OVERLAY_FS: enabled (as module)
  CONFIG_AUFS_FS: not set - Required for aufs.
  CONFIG_BLK_DEV_DM: enabled
  CONFIG_CFS_BANDWIDTH: enabled
  CONFIG_CGROUP_HUGETLB: enabled
  CONFIG_SECCOMP: enabled
  CONFIG_SECCOMP_FILTER: enabled
  Validating cgroups...
  CGROUPS_CPU: enabled
  CGROUPS_CPUSET: enabled
  CGROUPS_DEVICES: enabled
  CGROUPS_FREEZER: enabled
  CGROUPS_MEMORY: enabled
  CGROUPS_PIDS: enabled
  CGROUPS_HUGETLB: enabled
  CGROUPS_IO: enabled
  Validating package...
  PASS
  << Captured StdOut/StdErr Output
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Ran 1 of 558 Specs in 709.100 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 557 Skipped


Ginkgo ran 1 suite in 11m49.211393933s
Test Suite Passed

```

I would modifying the test case to try and get it to turn green in CI

**Comment by HirazawaUi** [comment]
@SergeyKanzhelev  Because of https://github.com/kubernetes/kubernetes/issues/107063, I have no way to make the `pull-kubernetes-cos-cgroupv2-containerd-node-e2e-eviction` test job turn green in the current PR, but the new case is green. Can we make it lgtm?

**Comment by HirazawaUi** [comment]
/cc @yujuhong @SergeyKanzhelev  
Do you think we can still merge it in v1.31? If not, I will modify the feature gate's comments.

**Comment by SergeyKanzhelev** [comment]
@HirazawaUi do you want to revive this PR?

**Comment by HirazawaUi** [comment]
> @HirazawaUi do you want to revive this PR?

Yes, I'm still working on it and have already rebased.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by SergeyKanzhelev** [comment]
/assign @thockin 

for the update of the comment. This PR fixes long standing bug and allows to revert the previous behavior via the feature gate. The bug only encountered on nodes with soft eviction configured, with the pods of short graceful termination period which is shorter than the maximum soft eviction graceful termination period. So it is very scoped.

**Comment by HirazawaUi** [comment]
/ping @thockin  Could you review for it? It has already been approved by sig-node.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
