### PR TITLE
[KEP-4639] Remove image volume e2e test because CI has containerd < 2.1

### LINKED ISSUE #135247: [Failing Test] [sig-node] ImageVolume should succeed with pod and pull policy of Always [MinimumKubeletVersion:1.35]
### Which jobs are failing?

* sig-release-master-blocking
* gce-cos-master-default

### Which tests are failing?

* [Kubernetes e2e suite.[It] [sig-node] ImageVolume should succeed with pod and pull policy of Always [MinimumKubeletVersion:1.35]](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1988078996033638400)

### Since when has it been failing?

* First failure: Sun, 09 Nov 2025 00:12:02 UTC
* Latest failure: Tue, 11 Nov 2025 02:59:04 UTC

### Testgrid link

* [https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&exclude-non-failed-tests=](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&exclude-non-failed-tests=)
* [https://storage.googleapis.com/k8s-triage/index.html?job=ci-kubernetes-e2e-gci-gce%24&test=ImageVolume%20should%20succeed%20with%20pod%20and%20pull%20policy%20of%20Always](https://storage.googleapis.com/k8s-triage/index.html?job=ci-kubernetes-e2e-gci-gce%24&test=ImageVolume%20should%20succeed%20with%20pod%20and%20pull%20policy%20of%20Always)

### Reason for failure (if possible)

```
{ failed [FAILED] Failed to await for the pod to be running: (image-volume-6922/test-pod): Timed out after 300.001s.
Expected Pod to be in <v1.PodPhase>: "Running"
Got instead:
    <*v1.Pod | 0xc006bf0f08>: 
        metadata:
          creationTimestamp: "2025-11-11T02:26:12Z"
          generation: 1
          labels:
            topology.kubernetes.io/region: us-central1
            topology.kubernetes.io/zone: us-central1-b
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                f:containers:
                  k:{"name":"test-container"}:
                    .: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                    f:volumeMounts:
                      .: {}
                      k:{"mountPath":"/volume"}:
                        .: {}
                        f:mountPath: {}
                        f:name: {}
                f:dnsPolicy: {}
                f:enableServiceLinks: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext: {}
                f:terminationGracePeriodSeconds: {}
                f:volumes:
                  .: {}
                  k:{"name":"volume"}:
                    .: {}
                    f:image:
                      .: {}
                      f:pullPolicy: {}
                      f:reference: {}
                    f:name: {}
            manager: e2e.test
            operation: Update
            time: "2025-11-11T02:26:12Z"
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:status:
                f:conditions:
                  k:{"type":"ContainersReady"}:
                    .: {}
                    f:lastProbeTime: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
                  k:{"type":"Initialized"}:
                    .: {}
                    f:lastProbeTime: {}
                    f:lastTransitionTime: {}
                    f:observedGeneration: {}
                    f:status: {}
                    f:type: {}
                  k:{"type":"PodReadyToStartContainers"}:
                    .: {}
                    f:lastProbeTime: {}
                    f:lastTransitionTime: {}
                    f:observedGeneration: {}
                    f:status: {}
                    f:type: {}
                  k:{"type":"PodScheduled"}:
                    f:observedGeneration: {}
                  k:{"type":"Ready"}:
                    .: {}
                    f:lastProbeTime: {}
                    f:lastTransitionTime: {}
                    f:message: {}
                    f:observedGeneration: {}
                    f:reason: {}
                    f:status: {}
                    f:type: {}
                f:containerStatuses: {}
                f:hostIP: {}
                f:hostIPs: {}
                f:observedGeneration: {}
                f:podIP: {}
                f:podIPs:
                  .: {}
                  k:{"ip":"10.64.1.91"}:
                    .: {}
                    f:ip: {}
                f:startTime: {}
            manager: kubelet
            operation: Update
            subresource: status
            time: "2025-11-11T02:31:00Z"
          name: test-pod
          namespace: image-volume-6922
          resourceVersion: "23417"
          uid: 4dd37e99-418b-498b-9f1a-be7938f18321
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - while true; do echo test; sleep 1; done
            image: registry.k8s.io/e2e-test-images/busybox:1.37.0-1
            imagePullPolicy: IfNotPresent
            name: test-container
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /volume
              name: volume
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-tg4lz
              readOnly: true
          dnsPolicy: ClusterFirst
          enableServiceLinks: true
          nodeName: bootstrap-e2e-minion-group-cvt7
          preemptionPolicy: PreemptLowerPriority
          priority: 0
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: default
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 300
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 300
          volumes:
          - image:
              pullPolicy: Always
              reference: registry.k8s.io/e2e-test-images/kitten:1.7
            name: volume
          - name: kube-api-access-tg4lz
            projected:
              defaultMode: 420
              sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                  - key: ca.crt
                    path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                  - fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                    path: namespace
        status:
          conditions:
          - lastProbeTime: null
            lastTransitionTime: "2025-11-11T02:26:16Z"
            observedGeneration: 1
            status: "True"
            type: PodReadyToStartContainers
          - lastProbeTime: null
            lastTransitionTime: "2025-11-11T02:26:12Z"
            observedGeneration: 1
            status: "True"
            type: Initialized
          - lastProbeTime: null
            lastTransitionTime: "2025-11-11T02:26:12Z"
            message: 'containers with unready status: [test-container]'
            observedGeneration: 1
            reason: ContainersNotReady
            status: "False"
            type: Ready
          - lastProbeTime: null
            lastTransitionTime: "2025-11-11T02:26:12Z"
            message: 'containers with unready status: [test-container]'
            observedGeneration: 1
            reason: ContainersNotReady
            status: "False"
            type: ContainersReady
          - lastProbeTime: null
            lastTransitionTime: "2025-11-11T02:26:12Z"
            observedGeneration: 1
            status: "True"
            type: PodScheduled
          containerStatuses:
          - image: registry.k8s.io/e2e-test-images/busybox:1.37.0-1
            imageID: ""
            lastState: {}
            name: test-container
            ready: false
            restartCount: 0
            started: false
            state:
              waiting:
                message: 'failed to generate container "12fc7e3a20ad8cdab7c060719b7cb4726c7c4eda968934fa354c5d823a1ce292"
                  spec: failed to generate spec: failed to mkdir "": mkdir : no such file
                  or directory'
                reason: CreateContainerError
            volumeMounts:
            - mountPath: /volume
              name: volume
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-tg4lz
              readOnly: true
              recursiveReadOnly: Disabled
          hostIP: 10.40.0.3
          hostIPs:
          - ip: 10.40.0.3
          observedGeneration: 1
          phase: Pending
          podIP: 10.64.1.91
          podIPs:
          - ip: 10.64.1.91
          qosClass: BestEffort
          startTime: "2025-11-11T02:26:12Z"
In [It] at: k8s.io/kubernetes/test/e2e/common/node/image_volume.go:118 @ 11/11/25 02:31:12.672
}

```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
/kind failing-test
cc @kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Remove the e2e test since we switched to beta (enabled by default) instead of GA. We re-add the test in 1.36.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/135247

#### Special notes for your reviewer:
Follow-up on https://github.com/kubernetes/kubernetes/pull/134502, https://github.com/kubernetes/kubernetes/pull/135195 for KEP 4639.
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4639-oci-volume-source/README.md
```

### CODE REVIEW

File: test/e2e/common/node/image_volume.go [hunk 1]
```diff
@@ -49,6 +57,55 @@ var _ = SIGDescribe("ImageVolume", func() {
...
+	}
+
+	requireContainerdVersion := func(givenVersion string) {
+		runtime, _, err := getCRIClient()
+		framework.ExpectNoError(err, "Failed to get CRI client")
+
+		resp, err := runtime.Version(context.Background(), "")
+		framework.ExpectNoError(err, "Failed to get runtime version")
+
+		// Other runtimes like CRI-O do not need to enforce any version requirement.
```
Comment (kannon92) [inline test/e2e/common/node/image_volume.go]:
```suggestion
		// For CRI-O do not need to enforce any version requirement.
```

If we had other runtimes in our CI, we aren't actually sure if this test will pass. I'm not sure if cri-dockerd or openeuler have implemented this feature but I don't think we need to mention that.

Comment (haircommander) [reply test/e2e/common/node/image_volume.go]: sig node's position only considers cri-o and containerd right now because they're active in the sig, so I think this is fine.

**Comment by kannon92** [comment]
/hold

CI failures seem related to this failure.

File: test/e2e/common/node/image_volume.go (hunk 1 above)
Comment (carlory) [reply test/e2e/common/node/image_volume.go]: Could we get the container runtime version from a node's status, as sig-windows does? https://github.com/kubernetes/kubernetes/blob/9c915e357f3805124401f0ccf2babf28beb9d8aa/test/e2e/windows/utils.go#L85-L101

**Comment by saschagrunert** [comment]
We decided to remove the test for now because it's just going to be another beta. I opened a tracker to re-add in 1.36: https://github.com/kubernetes/kubernetes/issues/135269


/unhold
