### PR TITLE
Extending DSR loadbalancer feature in winkernel kube-proxy to HNS versions 9.3-9.max, 10.2+

### LINKED ISSUE #93304: Windows HNS version check for DSR feature is failing on RS5, even though it is supported
**What happened**:
I tried to enabled DSR loadbalancers on kube-proxy Windows but there was an error shown
"Platform does not support feature Direct Server Return (DSR)"

**What you expected to happen**:
I expected kube-proxy to run in DSR mode on a supported Windows build.

**How to reproduce it (as minimally and precisely as possible)**:
Enable DSR mode using --enable-dsr=true --feature-gates="WinDSR=true"

**Anything else we need to know?**:
The hcsshim [version check used by winkernel proxier](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/proxier.go#L545) needs to be updated to be inclusive of HNS versions used in Windows Server, version 1809.

**Environment**: Windows Server, version 1809

- Kubernetes version (use `kubectl version`): 1.19

- Cloud provider or hardware configuration: VM

- OS (e.g: `cat /etc/os-release`): Windows Server, version 1809

- Kernel (e.g. `uname -a`): Windows Server, version 1809 with HNS version 9.3

- Install tools: kubeadm

- Network plugin and version (if this is a network-related bug): Flannel host-gw mode
- Others:

### PR DESCRIPTION
**Pull request by elweb9858**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR introduces an updated version of hcsshim, which has the latest version check for DSR loadbalancers, which are used in winkernel kube-proxy. Customers running on older versions of Windows (HNS versions 9.3-9.max, 10.2+) will be able to use the DSR feature with these changes.

**Which issue(s) this PR fixes**:

Fixes #93304

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Extended DSR loadbalancer feature in winkernel kube-proxy to HNS versions 9.3-9.max, 10.2+
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by elweb9858** [comment]
fyi @keith-mange @sbangari

**Comment by elweb9858** [comment]
fyi @daschott

**Comment by elweb9858** [comment]
@feiskyer I know it's a bit late in the cycle, but we are trying to get this in v1.19. Any chance you could mark this PR with the v1.19 milestone?

**Review by michmike — APPROVED** [review]
/lgtm
/approve

File: pkg/proxy/winkernel/proxier_test.go [hunk 1]
```diff
@@ -374,6 +384,67 @@ func TestCreateLoadBalancer(t *testing.T) {
...
+	proxier.setInitialized(true)
+	proxier.syncProxyRules()
+
+	svc := proxier.serviceMap[svcPortName]
+	svcInfo, ok := svc.(*serviceInfo)
+	if !ok {
+		t.Errorf("Failed to cast serviceInfo %q", svcPortName.String())
+
+	} else {
+		if svcInfo.hnsID != guid {
```
Comment (kumarvin123) [inline pkg/proxy/winkernel/proxier_test.go:441]: Can you also make sure that svcInfo has dsr field set to  true

**Comment by feiskyer** [comment]
Michael has already added to v1.19. @elweb9858 could you also add a release note?

**Review by kumarvin123 — APPROVED** [review]

File: pkg/proxy/winkernel/proxier.go [hunk 2]
```diff
@@ -1177,7 +1184,7 @@ func (proxier *Proxier) syncProxyRules() {
 			// Try loading existing policies, if already available
 			hnsLoadBalancer, err = hns.getLoadBalancer(
 				hnsEndpoints,
-				loadBalancerFlags{sessionAffinity: sessionAffinityClientIP, isIPv6: proxier.isIPv6Mode},
+				loadBalancerFlags{isDSR: svcInfo.dsr, sessionAffinity: sessionAffinityClientIP, isIPv6: proxier.isIPv6Mode},
```
Comment (ksubrmnn) [inline pkg/proxy/winkernel/proxier.go:1187]: Would we want to also check proxier.isDSR for these other loadbalancer types?

Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go:1187]: I was not planning on altering any functionality surrounding isDSR and preserveDIP, @madhanrm could you weigh in on this?

File: pkg/proxy/winkernel/proxier.go [hunk 3]
```diff
@@ -352,6 +353,11 @@ func (proxier *Proxier) newServiceInfo(port *v1.ServicePort, service *v1.Service
 	if err != nil {
 		preserveDIP = false
 	}
+	dsr := service.Spec.ExternalTrafficPolicy == v1.ServiceExternalTrafficPolicyTypeLocal
+	err = hcn.Slash32EndpointPrefixesSupported()
```
Comment (JocelynBerrendonner) [inline pkg/proxy/winkernel/proxier.go:357]: We need to use DSRSupported() here.

Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go:357]: @JocelynBerrendonner I am using the Slash32EndpointPrefixesSupported() method here because DSRSupported() does not reflect the backport of the dsr functionality. Some users need this functionality on rs5, which DSRSupported() will inaccurately say is not supported. I can update the version check in hcsshim (assuming the preserveDIP functionality has also been backported) and file a bug to change this version check the next time an hcsshim release is vendored into k8s

Comment (JocelynBerrendonner) [reply pkg/proxy/winkernel/proxier.go:357]: @elweb9858 : why not do the proper fix in hcsshim today, merge it and pick it up here later today or tomorrow?

Comment (JocelynBerrendonner) [reply pkg/proxy/winkernel/proxier.go:357]: FWIW, the hcsshim change should be a two lines change in this file: https://github.com/microsoft/hcsshim/blob/27a858bf1651e8204c64b5e6f9979f6c51a0f943/hcn/hcnglobals.go#L41

File: pkg/proxy/winkernel/proxier.go [hunk 4]
```diff
@@ -352,6 +353,11 @@ func (proxier *Proxier) newServiceInfo(port *v1.ServicePort, service *v1.Service
 	if err != nil {
 		preserveDIP = false
 	}
+	dsr := service.Spec.ExternalTrafficPolicy == v1.ServiceExternalTrafficPolicyTypeLocal
```
Comment (ksubrmnn) [inline pkg/proxy/winkernel/proxier.go:356]: You need to also check if the feature flag is enabled as DSR is still an alpha feature.

File: pkg/proxy/winkernel/proxier.go (hunk 3 above)
Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go:357]: @JocelynBerrendonner you make a fair point, I just want to make sure we are not breaking existing scenarios that use DSRSupported()

Comment (JocelynBerrendonner) [reply pkg/proxy/winkernel/proxier.go:357]: They shouldn't. Fixing the Hcsshim should actually help everyone. Let's take the conversation offline.

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go:356]: @ksubrmnn Isn't that feature gate tied to the preserveDIP implementation of DSR? AFAIK this is a separate implementation based on the existing ExternalTrafficPolicy feature in the service spec. @madhanrm correct me if I'm wrong

Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:356]: No it is not. That flag is for DSR, not preserve dip. PreserveDIP is not an implementation of DSR. Rather, it depends on DSR.

However, you are right in that we won't need to guard with a flag for the pre-existing ExternalTrafficPolicy feature. So this is a separate implementation.

For 1.20, you can follow up with a PR to add DSR functionality for the other loadbalancers if the feature flag is enabled.

Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:356]: Please rename this variable so that it is not confused with proxier.isDSR

File: pkg/proxy/winkernel/proxier.go (hunk 3 above)
Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:357]: Since vendoring in new dependencies does take time, I think it's acceptable to use the version checks we have today (as long as they work properly) and update the shim for future releases.

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go:356]: > For 1.20, you can follow up with a PR to add DSR functionality for the other loadbalancers if the feature flag is enabled.

I'm not quite following on this. Could you explain what you mean here?

Also, I will change the variable to localTrafficDSR

Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:356]: DSR is its own feature. PreserveDIP depends on DSR.

We have enabled DSR to work for all types of loadbalancers on the platform. However, external traffic policy only applies to loadbalancers of type Loadbalancer and of type NodePort. This PR also needs to be amended to honor that.

To add DSR to the other loadbalancer types, we would need to first check the feature flag. Then we would enable it accordingly.

Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:356]: Looks like Kubernetes will block on yaml deployment if the incorrect loadbalancer type is specified with externalTrafficPolicy local so you won't have to worry about that after all.

File: pkg/proxy/winkernel/proxier.go (hunk 2 above)
Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go:1187]: Let's follow up in a separate PR to use proxier.isDSR for these loadbalancers as well.

File: pkg/proxy/winkernel/proxier.go [hunk 5]
```diff
@@ -1131,7 +1138,7 @@ func (proxier *Proxier) syncProxyRules() {
 
 		hnsLoadBalancer, err := hns.getLoadBalancer(
 			hnsEndpoints,
-			loadBalancerFlags{isDSR: proxier.isDSR, isIPv6: proxier.isIPv6Mode, sessionAffinity: sessionAffinityClientIP},
+			loadBalancerFlags{isDSR: proxier.isDSR || svcInfo.dsr, isIPv6: proxier.isIPv6Mode, sessionAffinity: sessionAffinityClientIP},
```
Comment (ksubrmnn) [inline pkg/proxy/winkernel/proxier.go:1141]: I believe that we should not be modifying this loadbalancer as externalTrafficPolicy: Local only affects the nodeport loadbalancer. Same for below.

File: pkg/proxy/winkernel/proxier.go (hunk 3 above)
Comment (JocelynBerrendonner) [reply pkg/proxy/winkernel/proxier.go]: Thanks @elweb9858 ! The latest iteration looks good.

**Review by JocelynBerrendonner — APPROVED** [review]
LGTM

**Review by ksubrmnn — APPROVED** [review]

File: pkg/proxy/winkernel/proxier.go (hunk 2 above)
Comment (liggitt) [reply pkg/proxy/winkernel/proxier.go]: > Let's follow up in a separate PR to use proxier.isDSR for these loadbalancers as well.

would that follow-up PR be required to be in 1.19 as well? as noted, we are past code freeze

Comment (ksubrmnn) [reply pkg/proxy/winkernel/proxier.go]: No that is for 1.20. This PR is now only updating a dependency which contains a fix for Windows 2004

Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go]: @liggitt this is no longer in scope for this PR and v1.20. Originally was trying to implement externalTrafficPolicy local in winkernel kube-proxy in this PR, but we are going to hold off on that and the followup work mentioned here until v1.20. This PR is now just simply vendoring in a version check update from hcsshim

File: pkg/proxy/winkernel/proxier.go (hunk 4 above)
Comment (elweb9858) [reply pkg/proxy/winkernel/proxier.go]: Resolving this as out of scope for the PR. We are continuing this conversation offline for future changes

File: pkg/proxy/winkernel/proxier.go (hunk 2 above)
Comment (liggitt) [reply pkg/proxy/winkernel/proxier.go]: ack

**Comment by liggitt** [comment]
/approve
for dependency mechanics

/hold
would like a clean CI run once https://github.com/kubernetes/kubernetes/pull/93063 merges, then can unhold

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93080/pull-kubernetes-node-e2e/1283460130247020544 flake is #93210

**Comment by liggitt** [comment]
@elweb9858 can you add a link to the bug this is fixing?

**Comment by liggitt** [comment]
@michmike can cancel the hold on this once the two azure jobs pass

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/issues/93295 for CI failure

**Comment by liggitt** [comment]
azure jobs are green

/hold cancel

**Comment by daschott** [comment]
@liggitt here is the bug this is fixing: https://github.com/kubernetes/kubernetes/issues/93304

There are many other bugs that need the DSR mode to be properly resolved, such as https://github.com/Azure/AKS/issues/1375
