### PR TITLE
Ignore reported goroutine leak during SPDY shutdown

### LINKED ISSUE #125028: [Flaking Test] integration-master (goroutine leak detection)
### Which jobs are flaking?

master-blocking:
- integration-master 

### Which tests are flaking?

- `k8s.io/kubernetes/test/integration/kubelet.kubelet`
- `k8s.io/kubernetes/test/integration/apiserver: portforward`

### Since when has it been flaking?

This has been occasionally flaking for some time. Recent Failures:

[4/30/2024, 1:42:50 PM ci-kubernetes-integration-1-30](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-30/1785220481515786240)
[4/29/2024, 6:33:48 PM ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1784931323572391936)
[4/22/2024, 1:05:57 PM ci-kubernetes-integration-1-30](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-30/1782312093924462592)

[2024-06-03 22:44:28 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1797761029896146944)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

`k8s.io/kubernetes/test/integration/kubelet.kubelet`
```
E0429 13:44:12.935549  115466 etcd.go:221] "EtcdMain goroutine check" err=<
	found unexpected goroutines:
	[Goroutine 29225 in state select, with golang.org/x/net/http2.(*serverConn).serve on top of the stack:
	golang.org/x/net/http2.(*serverConn).serve(0xc006b7ba00)
```

`k8s.io/kubernetes/test/integration/apiserver: portforward`
```
E0603 23:09:41.143906  109550 etcd.go:221] "EtcdMain goroutine check" err=<
	found unexpected goroutines:
	[Goroutine 4444 in state chan send, with github.com/moby/spdystream.(*Connection).shutdown on top of the stack:
	github.com/moby/spdystream.(*Connection).shutdown(0xc0042c4f20, 0x0)
		/home/prow/go/src/k8s.io/kubernetes/vendor/github.com/moby/spdystream/connection.go:743 +0x285
	created by github.com/moby/spdystream.(*Connection).Close in goroutine 4437
		/home/prow/go/src/k8s.io/kubernetes/vendor/github.com/moby/spdystream/connection.go:769 +0x145
	]
 >
FAIL	k8s.io/kubernetes/test/integration/apiserver/portforward	9.811s
```

### Anything else we need to know?

Another leak was fixed at https://github.com/kubernetes/kubernetes/issues/116196.

### Relevant SIG(s)

/sig api-machinery
/sig testing

### PR DESCRIPTION
**Pull request by seans3**
* Ignore SPDY shutdown goroutine leak report.
* Helps fix: https://github.com/kubernetes/kubernetes/issues/125028
  * ...but there is another flake in a `kubelet` integration test that needs to be addressed before this issue if marked `FIXED`.

/kind flake

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
for reference https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1797761029896146944

```
k8s.io/kubernetes/test/integration/apiserver: portforward expand_less	4s
{Failed;  I0603 23:09:31.452457  109550 i18n.go:119] Couldn't find the LC_ALL, LC_MESSAGES or LANG environment variables, defaulting to en_US
I0603 23:09:31.452557  109550 i18n.go:157] Setting language to default
I0603 23:09:31.480015  109550 etcd.go:71] etcd already running at http://127.0.0.1:2379
PASS
E0603 23:09:41.143906  109550 etcd.go:221] "EtcdMain goroutine check" err=<
	found unexpected goroutines:
	[Goroutine 4444 in state chan send, with github.com/moby/spdystream.(*Connection).shutdown on top of the stack:
	github.com/moby/spdystream.(*Connection).shutdown(0xc0042c4f20, 0x0)
		/home/prow/go/src/k8s.io/kubernetes/vendor/github.com/moby/spdystream/connection.go:743 +0x285
	created by github.com/moby/spdystream.(*Connection).Close in goroutine 4437
		/home/prow/go/src/k8s.io/kubernetes/vendor/github.com/moby/spdystream/connection.go:769 +0x145
	]
 >
FAIL	k8s.io/kubernetes/test/integration/apiserver/portforward	9.811s
;}
```

File: test/integration/framework/etcd.go [hunk 1]
```diff
@@ -207,6 +207,14 @@ func EtcdMain(tests func() int) {
 		// Both names occurred in practice.
 		goleak.IgnoreTopFunction("k8s.io/kubernetes/vendor/gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun"),
 		goleak.IgnoreTopFunction("gopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun"),
+		// If there is an error during connection shutdown, SPDY keeps a
+		// goroutine around for ten minutes, which gets reported as a leak
```
Comment (BenTheElder) [inline test/integration/framework/etcd.go:211]: hmm, does this not potentially build up in prod as well? there's no way to override this timeout etc?

Comment (seans3) [reply test/integration/framework/etcd.go:211]: No, it should not build up in prod. 1) This only happens if there is an error in the SPDY shutdown. Practically, this flake happened about 2 times in 600 tests. A script to reproduce the error ran the `portforward` integration test 1000 times, without triggering the goroutine leak. 2) The goroutine is cleaned up after 10 minutes. The timeout is long enough to trigger the leak detector, but it eventually the goroutine gets cleaned up.

Comment (BenTheElder) [reply test/integration/framework/etcd.go:211]: ... and 3) we're removing SPDY anyhow :-)

Comment (aojea) [reply test/integration/framework/etcd.go:211]: well, not completely :)

Comment (aojea) [reply test/integration/framework/etcd.go:211]: @seans3 @BenTheElder :) https://github.com/moby/spdystream/issues/92

Comment (BenTheElder) [reply test/integration/framework/etcd.go:211]: > well, not completely :)

We are _completely_ removing it soon, aren't we? I don't think the goroutine leak is new?

Comment (aojea) [reply test/integration/framework/etcd.go:211]: image

Comment (liggitt) [reply test/integration/framework/etcd.go:211]: > We are completely removing it soon, aren't we?

we're tunnelling portforward spdy over websockets, because spdy has traffic direction / backpressure characteristics websockets don't

Comment (aojea) [reply test/integration/framework/etcd.go:211]: and there are still two legs missing apiserver -- kubelet and kubelet -- container runtime

Comment (BenTheElder) [reply test/integration/framework/etcd.go:211]: I see, portforward-over-spdy-over-websocket, what a world :-)
