### PR TITLE
Fix influxdb e2e test failure.

### LINKED ISSUE #54636: Influxdb-related e2e shouldn't run when influxdb is not enabled on the cluster
The e2e test 'Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster.' is running in our [gce-scale-correctness job](https://k8s-testgrid.appspot.com/sig-scalability-gce-scale#gce-scale-correctness) and failing, while we're using the 'standalone' mode for monitoring (ref: https://github.com/kubernetes/test-infra/blob/67bc30718f5468cdd64675c2c710118f34af33c3/jobs/env/ci-kubernetes-e2e-gce-scale-correctness.env#L14) which iiuc doesn't start influxdb.

@fgrzadkowski - Assigning this to you. Feel free to redirect as apt.

cc @kubernetes/sig-instrumentation-bugs

### PR DESCRIPTION
**Pull request by loburm**
In scalability testing influxdb was recently disabled, but we still
trying to execute corresponidng test, as a result it fails all the time.
Skip test if influxdb is disabled.

Fixes #54636 

```release-note
NONE
```

### CODE REVIEW

File: hack/ginkgo-e2e.sh [hunk 1]
```diff
@@ -148,6 +148,7 @@ export PATH=$(dirname "${e2e_test}"):"${PATH}"
   --network="${KUBE_GCE_NETWORK:-${KUBE_GKE_NETWORK:-e2e}}" \
   --node-tag="${NODE_TAG:-}" \
   --master-tag="${MASTER_TAG:-}" \
+  --cluster-monitoring="${KUBE_ENABLE_CLUSTER_MONITORING:-influxdb}" \
```
Comment (shyamjvs) [inline hack/ginkgo-e2e.sh]: I wouldn't push on it - but `cluster-monitoring-mode` might be a better representation of what the flag is doing.

File: test/e2e/framework/test_context.go [hunk 2]
```diff
@@ -103,6 +103,8 @@ type TestContextType struct {
 	// Node e2e specific test context
 	NodeTestContextType
 
+	// Monitoring solution that is used in current cluster. Values are coming from ENABLE_CLUSTER_MONITORING flag.
```
Comment (shyamjvs) [inline test/e2e/framework/test_context.go]: You mean 'KUBE_ENABLE_CLUSTER_MONITORING env var'?
I would skip mentioning that, as it's not necessary that the value has to come from there - someone can also just set the flag.

File: test/e2e/framework/test_context.go [hunk 3]
```diff
@@ -103,6 +103,8 @@ type TestContextType struct {
...
+	ClusterMonitoring string
```
Comment (shyamjvs) [inline test/e2e/framework/test_context.go]: Add a newline before the next line (like it was before). And remove the one above - it's not needed imo.

File: test/e2e/framework/util.go [hunk 4]
```diff
@@ -331,6 +331,12 @@ func SkipUnlessProviderIs(supportedProviders ...string) {
 	}
 }
 
+func SkipUnlessClusterMonitoringIs(supportedMonitoring ...string) {
```
Comment (shyamjvs) [inline test/e2e/framework/util.go]: Here also I'd name it sth like `SkipUnlessClusterMonitoringModeIs`.

**Comment by loburm** [comment]
Thanks for the review. I have resolved all your comments, PTAL.

**Comment by shyamjvs** [comment]
/lgtm

Thanks a lot for fixing!

**Comment by shyamjvs** [comment]
@gmarek Could you approve for the `hack/` part?
