### PR TITLE
Retry NodeStageVolume if CSI Driver Is Missing; Treat this Error as Transient

### LINKED ISSUE #120268: Transient Driver Registration on the CSINode can Result in Missed NodeUnstageVolume RPCs During Pod Migration
### What happened?

In `unmountDetachDevices` (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler_common.go#L279-L316)) we have the following code that will ultimately dispatch `NodeUnstageVolume` RPCs to the underlying CSI plugin.

Here is a pseudo-code representation of the current logic:

```
function unmountDetachDevices
	for all unmounted volumes in ASoW
		if volume not in DSoW &&
		   not operation pending on volume
			if device is mounted globally or
			   device is mounted uncertain
				Case A:
				unmount device
				(this will kick off the NodeUnstageVolume RPC; we want to be here)
			else
				Case B:
				just remove volume from ASoW
				(general badness since we don't issue a NodeUnstageVolume RPC)
```

In our testbeds, we have observed a number of occurrences where we fall into `Case B` when the CSI Node plugin for a particular driver is being bounced, which leads to the volumemanager failing to dispatch the `NodeUnstageVolume` RPC. If the pod migrates to another node, this will leave behind a Zombie LUN in our testbeds (we're using iSCSI).

A Zombie LUN can and often does result in corruption when other pods later migrate to the node in question.

Based on testing that we conducted, we discovered that this case occurs because the device is marked as unmounted.

Initially, we see the device marked as uncertain during reconstruction.

However, if the CSI Node driver pod is bounced in the exact window when a `NodeStageVolume` RPC is issued, then we end up [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L777C1-L798C2).

There we check to see if the error encountered is a “transient error” or a “final error”; if a “final error” is encountered, then the device state transitions from uncertain to unmounted. That is what is happening in our case.

The error is generated when the CSIClient cannot find the requested driver [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L158C1-L161C3).

The driver registration code is socket based; based on our testing, if the Node plugin goes down for any reason the driver registration is removed from the CSINode.

Now for the `NodePublishVolume` path, this is mitigated by wrapping the error in a transient error [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L109C3-L109C3) (I assume to avoid such state transitions?):

```
	csi, err := c.csiClientGetter.Get()
	if err != nil {
		return volumetypes.NewTransientOperationFailure(log("mounter.SetUpAt failed to get CSI client: %v", err))
	}
```

Based on our testing to date, adding parity [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L293C20-L293C20) to the `NodeStageVolume` path would help us avoid Zombie LUNs in our test setups due to missing `NodeUnstageVolume` calls:

```
	// lets check if node/unstage is supported
	if c.csiClient == nil {
		c.csiClient, err = newCsiDriverClient(csiDriverName(csiSource.Driver))
		if err != nil {
			return errors.New(log("attacher.MountDevice failed to create newCsiDriverClient: %v", err))
		}
	}
	csi := c.csiClient
```

This can be fixed by also wrapping this error in a transient error.

### What did you expect to happen?

We expected to see a `NodeUnstageVolume` call coming to the underlying NodePlugin (once it was finally back up).

### How can we reproduce it (as minimally and precisely as possible)?

* Force reconstruction on a node.
* Take down the CSI node plugin on the node while pods are mounting.
* Try to migrate the pod to another node; the underlying machinery will correctly wait for the plugin to come back up before proceeding.
* Later, bring up the CSI node plugin.
* While the pod migration might be successful, a `NodeUnstageVolume` should be missing if the correct timing windows were hit.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
root@bootstrapper:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4-gke.500", GitCommit:"a955253697d6572565777f63dfe6df9fd74591a2", GitTreeState:"clean", BuildDate:"2023-07-26T09:27:11Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.27) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Google
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by rohitssingh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This allows the device state to be preserved if a `NodeStageVolume` RPC encounters an error because the CSI driver is missing.

This is accomplished by correctly marking this error as transient.

#### Which issue(s) this PR fixes:

Fixes #120268

#### Does this PR introduce a user-facing change?

```release-note
Retry NodeStageVolume calls if CSI node driver is not running
```

### CODE REVIEW

**Comment by rohitssingh** [comment]
@bswartz @jingxu97 @msau42 @saad-ali

File: cmd/kube-controller-manager/app/options/attachdetachcontroller.go [hunk 1]
```diff
@@ -37,6 +37,7 @@ func (o *AttachDetachControllerOptions) AddFlags(fs *pflag.FlagSet) {
 
 	fs.BoolVar(&o.DisableAttachDetachReconcilerSync, "disable-attach-detach-reconcile-sync", false, "Disable volume attach detach reconciler sync. Disabling this may cause volumes to be mismatched with pods. Use wisely.")
 	fs.DurationVar(&o.ReconcilerSyncLoopPeriod.Duration, "attach-detach-reconcile-sync-period", o.ReconcilerSyncLoopPeriod.Duration, "The reconciler sync wait time between volume attach detach. This duration must be larger than one second, and increasing this value from the default may allow for volumes to be mismatched with pods.")
+	fs.BoolVar(&o.DisableForceDetachOnUnmount, "disable-force-detach", false, "Prevent force detaching volumes based on maximum unmount time and node status. If enabled, the non-graceful node shutdown feature must be used to recover from node failure (see https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/). If enabled and a pod must be forcibly terminated at the risk of corruption, then the appropriate VolumeAttachment object (see here: https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume-attachment-v1/) must be deleted.")
```
Comment (jsafrane) [inline cmd/kube-controller-manager/app/options/attachdetachcontroller.go:40]: This belongs to a separate PR

Comment (rohitssingh) [reply cmd/kube-controller-manager/app/options/attachdetachcontroller.go:40]: ACK; I think I messed something up in the import process...

Comment (rohitssingh) [reply cmd/kube-controller-manager/app/options/attachdetachcontroller.go]: I've reverted the offending commit; hopefully that was the correct way to address this?

Comment (msau42) [reply cmd/kube-controller-manager/app/options/attachdetachcontroller.go]: Try doing a [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and delete the commits. Create a new branch to save your commits in case something goes wrong with the rebase.

**Comment by msau42** [comment]
Since we will likely want to backport this, can you add a release note? Something like "Retry NodeStageVolume calls if CSI driver is not running"

File: cmd/kube-controller-manager/app/options/attachdetachcontroller.go (hunk 1 above)
Comment (rohitssingh) [reply cmd/kube-controller-manager/app/options/attachdetachcontroller.go]: Gotcha; I'll push in a bit...

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -287,7 +287,9 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
 	if c.csiClient == nil {
 		c.csiClient, err = newCsiDriverClient(csiDriverName(csiSource.Driver))
 		if err != nil {
-			return errors.New(log("attacher.MountDevice failed to create newCsiDriverClient: %v", err))
+			// Treat the absence of the CSI driver as a transient error
+			// See https://github.com/kubernetes/kubernetes/issues/120268
+			return volumetypes.NewTransientOperationFailure(log("attacher.MountDevice failed to create newCsiDriverClient: %v", err))
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go:292]: Doing a quick scan of other places where we should return transient error:
UnstageVolume: https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_attacher.go#L612

Teardown: https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_mounter.go#L422

SetUpDevice:
https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_block.go#L322

MapDevice: https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_block.go#L382

TeardownDevice: https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_block.go#L447

UnmapDevice: https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/csi_block.go#L509

NodeExpand? https://github.com/kubernetes/kubernetes/blob/689285c4101a2035a012cd275b8d1996d71ba74d/pkg/volume/csi/expander.go#L49

@gnufied @jsafrane wdyt?

File: cmd/kube-controller-manager/app/options/attachdetachcontroller.go (hunk 1 above)
Comment (rohitssingh) [reply cmd/kube-controller-manager/app/options/attachdetachcontroller.go]: Just pushed; I had to do a forced update but it looks like it worked!

**Comment by msau42** [comment]
Looks like the failures are a test-infra issue. Retrying won't help until https://github.com/kubernetes/kubernetes/issues/120367 fixed

**Comment by rohitssingh** [comment]
Looks like #120367 has been resolved; let's try again

**Comment by rohitssingh** [comment]
Looks like all of the automated tests passed!

File: pkg/volume/csi/csi_attacher.go (hunk 2 above)
Comment (rohitssingh) [reply pkg/volume/csi/csi_attacher.go:292]: @msau42: I'll upload a patch to treat all of these errors as transient too.
