### PR TITLE
Fix assertion for host network hostname e2e test

### LINKED ISSUE #8167: [Failing Test] [sig-network] DNS HostNetwork spec.Hostname field is silently ignored and the node hostname is used when hostNetwork is set to true for a Pod
### Which jobs are failing?

- ci/prow/ci-rhel-e2e
- ci/prow/ci-e2e
- ci/prow/ci-e2e-evented-pleg
- ci/prow/ci-cgroupv2-e2e-crun
- ci/prow/ci-crun-e2e
- ci/prow/ci-e2e-conmonrs
- ci/prow/ci-cgroupv2-e2e

### Which tests are failing?

`[sig-network] DNS HostNetwork spec.Hostname field is silently ignored and the node hostname is used when hostNetwork is set to true for a Pod `

### Since when has it been failing?

A couple of days now.

### Testgrid link

_No response_

### Reason for failure (if possible)

```
{ failed [FAILED] expected hostname: 10.0.0.2, got: ci-op-ngp0fq79-3f73e-buildhost
In [It] at: k8s.io/kubernetes/test/e2e/network/dns.go:690 @ 05/13/24 10:09:04.27

There were additional failures detected after the initial failure. These are visible in the timeline
}
```

### Anything else we need to know?

- Refers to
  - https://github.com/kubernetes/kubernetes/issues/67019
  - https://github.com/kubernetes/kubernetes/pull/124428
- I'm able to reproduce it locally

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

The original assumption is wrong, as the node name may not match the hostname of the host in some circumstances.

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri-o/issues/8167
Follow-up on https://github.com/kubernetes/kubernetes/pull/124428
#### Special notes for your reviewer:
cc @aojea @yashsingh74 @aroradaman
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

File: test/e2e/network/dns.go [hunk 1]
```diff
@@ -686,8 +687,12 @@ var _ = common.SIGDescribe("DNS HostNetwork", func() {
 		stdout, err := e2eoutput.RunHostCmd(testAgnhostPod.Namespace, testAgnhostPod.Name, "hostname")
 		framework.ExpectNoError(err, "failed to run command hostname: %s", stdout)
 		hostname := strings.TrimSpace(stdout)
-		if node.Name != hostname {
-			framework.Failf("expected hostname: %s, got: %s", node.Name, hostname)
+
+		localHostname, err := os.Hostname()
```
Comment (aojea) [inline test/e2e/network/dns.go:691]: this will not work, we want the hostname of the node where the pod is running

File: test/e2e/network/dns.go [hunk 2]
```diff
@@ -686,8 +687,12 @@ var _ = common.SIGDescribe("DNS HostNetwork", func() {
 		stdout, err := e2eoutput.RunHostCmd(testAgnhostPod.Namespace, testAgnhostPod.Name, "hostname")
 		framework.ExpectNoError(err, "failed to run command hostname: %s", stdout)
 		hostname := strings.TrimSpace(stdout)
-		if node.Name != hostname {
-			framework.Failf("expected hostname: %s, got: %s", node.Name, hostname)
```
Comment (aojea) [inline test/e2e/network/dns.go:690]: The problem is here, it seems this assumption is wrong, as the node name may not match the hostname of the host in some circumstances .... I think the only thing we can do is to  validate is that the spec.Hostname is ignored so we just need to change this assertion by

```
if dnsTestPodHostName == hostname {
   framework.Failf("https://issues.k8s.io/67019 expected spec.Hostname  %s to be ignored", hostname)
}
```

Comment (saschagrunert) [reply test/e2e/network/dns.go:690]: The assertion does not work for kind, is that expected?

Comment (aojea) [reply test/e2e/network/dns.go:690]: we need to assert that the provided hostname is not the one configured, that is the existing behavior ... (that is weird, but it is what it is :)

File: test/e2e/network/dns.go [hunk 3]
```diff
@@ -686,8 +686,8 @@ var _ = common.SIGDescribe("DNS HostNetwork", func() {
...
+		if node.Name == hostname {
```
[the remark this answers is not in the document]
Comment (aojea) [reply test/e2e/network/dns.go:689]: `testAgnhostPod.Spec.Hostname = dnsTestPodHostName`

**Comment by saschagrunert** [comment]
@kubernetes/sig-network-bugs PTAL

**Comment by aojea** [comment]
/lgtm
/approve

We can not assume the nodename will be equal to hostname , so we just check that the hostnme set in the pod spec is not the one assigned to the pod
