### PR TITLE
Suppress container not found errors in container runtime getPodStatuses

### LINKED ISSUE #107483: Kubelet cannot start static pod when move in manifest file after removing manifest file for a while
### What happened?

An error occurs in `managePodLoop` after the static pod has being deleted, then `syncCh` is triggerred and error event will be dequeued from work queue but pod manage has no such pod because `HandlePodRemoves` has been called.

`No such container error` is a common error type from `p.podCache.GetNewerThan` or `syncTerminatingPodFn` method in `managePodLoop` .

So this event can not trigger `HandlePodSyncs` to finish pod terminating.

Because of terminating state of pod, `SyncLoop ADD` will mark restartable flag and return.

So the housekeeper becomes the only way to start the pod. But also due to terminating state(not finished), the pod cannot be added to `restartablePods`, so it cannot be retarted again.

Eventually, the pod will never be restarted again.

### What did you expect to happen?

Static pod can be started or restarted again.

### How can we reproduce it (as minimally and precisely as possible)?

We found that the pod would fail to start after the events occurred in the following order:
1. HandlePodRemoves -> podManager.DeletePod -> managePodLoop ->  err occurred, like "No such container" -> completeWork -> workQueue.Enqueue

2. syncCh -> getPodsToSync -> workQueue.GetWork() -> podManager.GetPods() -> pod has been deleted, and HandlePodSyncs cannot be entered 

3. HandlePodAdditions -> podManager.AddPod -> status.IsTerminationRequested -> status.restartRequested=true -> return

4. HandlePodCleanups -> podWorkers.SyncKnownPods -> removeTerminatedWorker -> !status.finished -> do not delete podSyncStatuses -> status.terminatedAt.IsZero() && !status.terminatingAt.IsZero() -> still in TerminatingPod state

Then the pod will never be started due to lack of trigger of pod worker, unless the kubelet is restarted.

Stub method for error in managePodLoop:
1. Add a delay between `podSandboxIDs, err := m.getSandboxIDByPodUID(uid, nil)` and `podSandboxStatus, err := m.runtimeService.PodSandboxStatus(podSandboxID)` in for range in `GetPodStatus` in `syncTerminatingPod` .
2. Once `getSandboxIDByPodUID` has been called, kill and remove the pause container of the pod manually.
3. An `No such container` error occurs.

Kubelet Log:
<details>

```log
I1213 17:26:45.869540   19130 kubelet.go:2249] "SyncLoop REMOVE" source="file" pods=[fst-manage/webhook-paas-192-168-2-2]
I1213 17:26:45.869806   19130 kuberuntime_container.go:721] "Killing container with a grace period" pod="fst-manage/webhook-paas-192-168-2-2" podUID=3a91011824b5370050c4bb2c2c0705ad containerName="webhook" containerID="docker://9ff7d0fbdb1f96db833ae273cee55cec2ae73cdd201088d9b6af515c2879d350" gracePeriod=5
I1213 17:26:46.211320   19130 reconciler.go:197] "operationExecutor.UnmountVolume started for volume \"localtime\" (UniqueName: \"kubernetes.io/host-path/3a91011824b5370050c4bb2c2c0705ad-localtime\") pod \"3a91011824b5370050c4bb2c2c0705ad\" (UID: \"3a91011824b5370050c4bb2c2c0705ad\") "
...
I1213 17:26:46.761943   19130 generic.go:159] "GenericPLEG" podUID=3a91011824b5370050c4bb2c2c0705ad containerID="9ff7d0fbdb1f96db833ae273cee55cec2ae73cdd201088d9b6af515c2879d350" oldState=running newState=exited
I1213 17:26:46.761949   19130 generic.go:159] "GenericPLEG" podUID=3a91011824b5370050c4bb2c2c0705ad containerID="5b0e3b74c2a73880c3e984fac3c40c8ef0648c92b3df6c0cbf178d4541af5e2d" oldState=running newState=exited
E1213 17:26:47.292895   19130 kuberuntime_manager.go:1091] "getPodContainerStatuses for pod failed" err="Error: No such container: 740ab753973f7ad32c5ef2c9778fb061469fc1a664710988569a46deb7eea66e" pod="fst-manage/webhook-paas-192-168-2-2"
E1213 17:26:47.292948   19130 pod_workers.go:894] "Error syncing pod, skipping" err="Error: No such container: 740ab753973f7ad32c5ef2c9778fb061469fc1a664710988569a46deb7eea66e" pod="fst-manage/webhook-paas-192-168-2-2" podUID=3a91011824b5370050c4bb2c2c0705ad
I1213 17:26:48.312614   19130 kubelet_volumes.go:161] "Cleaned up orphaned pod volumes dir" podUID=3a91011824b5370050c4bb2c2c0705ad path="/var/lib/kubelet/pods/3a91011824b5370050c4bb2c2c0705ad/volumes"
I1213 17:26:48.712057   19130 kubelet.go:2281] "SyncLoop (PLEG): pod does not exist, ignore irrelevant event" event=&{ID:3a91011824b5370050c4bb2c2c0705ad Type:ContainerDied Data:5b0e3b74c2a73880c3e984fac3c40c8ef0648c92b3df6c0cbf178d4541af5e2d}
I1213 17:27:00.876529   19130 kubelet.go:2239] "SyncLoop ADD" source="file" pods=[fst-manage/webhook-paas-192-168-2-2]
```

Another reoccurrence:
```log
I0110 11:56:03.480296   25160 kubelet.go:2249] "SyncLoop REMOVE" source="file" pods=[fst-manage/kube-apiserver-paas-192-168-2-2]
I0110 11:56:03.480433   25160 pod_workers.go:840] "Got non-process pod, start sync pod" pod="fst-manage/kube-apiserver-paas-192-168-2-2"
I0110 11:56:03.480768   25160 kuberuntime_container.go:721] "Killing container with a grace period" pod="fst-manage/kube-apiserver-paas-192-168-2-2" podUID=c6dc565f27a76405ed35d58bc441a407 containerName="kube-apiserver" containerID="docker://524779760c0050c8391419ea54295020f42460802cea89a2f11df8d08cb87f15" gracePeriod=1
I0110 11:56:05.297011   25160 generic.go:159] "GenericPLEG" podUID=c6dc565f27a76405ed35d58bc441a407 containerID="524779760c0050c8391419ea54295020f42460802cea89a2f11df8d08cb87f15" oldState=running newState=exited
I0110 11:56:06.177361   25160 generic.go:338] "Generic (PLEG): container finished" podID=c6dc565f27a76405ed35d58bc441a407 containerID="524779760c0050c8391419ea54295020f42460802cea89a2f11df8d08cb87f15" exitCode=137
I0110 11:56:06.177414   25160 kubelet.go:2281] "SyncLoop (PLEG): pod does not exist, ignore irrelevant event" event=&{ID:c6dc565f27a76405ed35d58bc441a407 Type:ContainerDied Data:524779760c0050c8391419ea54295020f42460802cea89a2f11df8d08cb87f15}
E0110 11:56:07.147581   25160 kuberuntime_manager.go:1091] "getPodContainerStatuses for pod failed" err="Error: No such container: fa6daeb414be6249f3f8002c7c6098bcf888debeebcef108d7c6b2fb5cfea447" pod="fst-manage/kube-apiserver-paas-192-168-2-2"
E0110 11:56:07.147608   25160 kubelet.go:1983] "Unable to read pod status prior to final pod termination" err="Error: No such container: fa6daeb414be6249f3f8002c7c6098bcf888debeebcef108d7c6b2fb5cfea447" pod="fst-manage/kube-apiserver-paas-192-168-2-2" podUID=c6dc565f27a76405ed35d58bc441a407
E0110 11:56:07.147629   25160 pod_workers.go:894] "Error syncing pod, skipping" err="Error: No such container: fa6daeb414be6249f3f8002c7c6098bcf888debeebcef108d7c6b2fb5cfea447" pod="fst-manage/kube-apiserver-paas-192-168-2-2" podUID=c6dc565f27a76405ed35d58bc441a407
I0110 11:56:07.245849   25160 generic.go:159] "GenericPLEG" podUID=c6dc565f27a76405ed35d58bc441a407 containerID="fa6daeb414be6249f3f8002c7c6098bcf888debeebcef108d7c6b2fb5cfea447" oldState=exited newState=non-existent
I0110 11:56:07.245860   25160 generic.go:159] "GenericPLEG" podUID=c6dc565f27a76405ed35d58bc441a407 containerID="349f55d33dc68eddebc3383a251e8048ceaa83cf0b006843b99e168736e61b82" oldState=running newState=exited
I0110 11:56:07.257231   25160 kubelet.go:2281] "SyncLoop (PLEG): pod does not exist, ignore irrelevant event" event=&{ID:c6dc565f27a76405ed35d58bc441a407 Type:ContainerDied Data:349f55d33dc68eddebc3383a251e8048ceaa83cf0b006843b99e168736e61b82}
I0110 11:57:20.569359   25160 kubelet.go:2239] "SyncLoop ADD" source="file" pods=[fst-manage/kube-apiserver-paas-192-168-2-2]
```
</details>

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Kubernetes version: v1.22.1-c5fe23a7fbdd1d996731d6c996ba8aed3804d471
and already backportted  #105075
```
</details>

### Cloud provider

<details>

Local machine
</details>

### OS version

<details>

```console  
$ cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP10x86_64)"
ID="euleros"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP10x86_64)"
ANSI_COLOR="0;31"
$ uname -a
Linux host-192-168-2-2 4.18.0-147.5.2.5.h732.eulerosv2r10.x86_64 #1 SMP Sat Nov 27 16:33:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux  
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
1. while inspect containers from result of list last step, the elder exited containers may be garbage collected, so we should ignore this not found error which defined by cri-api.
2. If a pod is already in terminated and it's podworker has just been removed and the housekeeping loop sees an
out of date cache entry for a running container, then the podworker would still keep killing a NotFound pod and being stucked until next kubelet restart.
#### Which issue(s) this PR fixes:

Fixes #107483

#### Special notes for your reviewer:
/cc @ehashman @smarterclayton 

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.22 regression with static pod restarts in cases where the container is not present.
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liushi001** [comment]
I think this might be a temporary solution. If another kind of error returns from `syncTerminatingPodFn`, we should retry to terminate the Pod again. Because the conainer maybe has not yet been killed. 

I also tried a way to avoid it that adding a `status.working` condition in `(p *podWorkers) removeTerminatedWorker(uid types.UID)`. So after housekeeping `podSyncStatuses` can be clear. Then ADD a static manifest file can trigger `synPod` to start container. 

But this method relies on housekeeping period. If I remove in and out manifest file in period of housekeeping, the container will keep running and cannot be restarted.

So I'm wondering if some larger scale refactoring is needed to fix the problem.

```go
func (p *podWorkers) removeTerminatedWorker(uid types.UID) {
	status, ok := p.podSyncStatuses[uid]
	if !ok {
		// already forgotten, or forgotten too early
		klog.V(4).InfoS("Pod worker has been requested for removal but is not a known pod", "podUID", uid)
		return
	}

	if !status.finished && status.working {
		klog.V(4).InfoS("Pod worker has been requested for removal but is still not fully terminated", "podUID", uid)
		return
	}

	if status.restartRequested {
		klog.V(4).InfoS("Pod has been terminated but another pod with the same UID was created, remove history to allow restart", "podUID", uid)
	} else {
		klog.V(4).InfoS("Pod has been terminated and is no longer known to the kubelet, remove all history", "podUID", uid)
	}
	delete(p.podSyncStatuses, uid)
	delete(p.podUpdates, uid)
	delete(p.lastUndeliveredWorkUpdate, uid)
}
```

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 1]
```diff
@@ -506,6 +507,10 @@ func (m *kubeGenericRuntimeManager) getPodContainerStatuses(uid kubetypes.UID, n
 	// TODO: optimization: set maximum number of containers per container name to examine.
 	for i, c := range containers {
 		status, err := m.runtimeService.ContainerStatus(c.Id)
+		if crierror.IsNotFound(err) {
+			klog.V(5).InfoS("Container not found", "containerID", c.Id, "err", err)
```
Comment (yangjunmyfm192085) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:511]: Why is this level 5？ Can it be consistent with the following log level?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -1036,6 +1036,10 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(uid kubetypes.UID, name, namesp
 	podIPs := []string{}
 	for idx, podSandboxID := range podSandboxIDs {
 		podSandboxStatus, err := m.runtimeService.PodSandboxStatus(podSandboxID)
+		if crierror.IsNotFound(err) {
+			klog.V(5).InfoS("Sandbox for pod not found", "podSandboxID", podSandboxID, "pod", klog.KObj(pod), "err", err)
```
Comment (yangjunmyfm192085) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1040]: Ditto

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by 249043822** [comment]
> I think this might be a temporary solution. If another kind of error returns from `syncTerminatingPodFn`, we should retry to terminate the Pod again. Because the conainer maybe has not yet been killed.

Yea, this behavior is as expected, if  `syncTerminatingPodFn` cause error, we really need retry.  Because the target of `syncTerminatingPodFn` is to kill pod containers, so If this container happens to be deleted, we should tolerate this exception.


> 
> I also tried a way to avoid it that adding a `status.working` condition in `(p *podWorkers) removeTerminatedWorker(uid types.UID)`. So after housekeeping `podSyncStatuses` can be clear. Then ADD a static manifest file can trigger `synPod` to start container.
> 
> But this method relies on housekeeping period. If I remove in and out manifest file in period of housekeeping, the container will keep running and cannot be restarted.
> 
> So I'm wondering if some larger scale refactoring is needed to fix the problem.
> 
> ```go
> func (p *podWorkers) removeTerminatedWorker(uid types.UID) {
> 	status, ok := p.podSyncStatuses[uid]
> 	if !ok {
> 		// already forgotten, or forgotten too early
> 		klog.V(4).InfoS("Pod worker has been requested for removal but is not a known pod", "podUID", uid)
> 		return
> 	}
> 
> 	if !status.finished && status.working {
> 		klog.V(4).InfoS("Pod worker has been requested for removal but is still not fully terminated", "podUID", uid)
> 		return
> 	}
> 
> 	if status.restartRequested {
> 		klog.V(4).InfoS("Pod has been terminated but another pod with the same UID was created, remove history to allow restart", "podUID", uid)
> 	} else {
> 		klog.V(4).InfoS("Pod has been terminated and is no longer known to the kubelet, remove all history", "podUID", uid)
> 	}
> 	delete(p.podSyncStatuses, uid)
> 	delete(p.podUpdates, uid)
> 	delete(p.lastUndeliveredWorkUpdate, uid)
> }
> ```

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (249043822) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:511]: I think that not-found is an error we can tolerate, so I let it's level more lower

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (smarterclayton) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:511]: I don't know that we need to log at this level here.  If the container isn't found, that's normal.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 3]
```diff
@@ -506,6 +507,10 @@ func (m *kubeGenericRuntimeManager) getPodContainerStatuses(uid kubetypes.UID, n
 	// TODO: optimization: set maximum number of containers per container name to examine.
 	for i, c := range containers {
 		status, err := m.runtimeService.ContainerStatus(c.Id)
+		if crierror.IsNotFound(err) {
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:510]: We need tests to verify this behavior - one unit test for the generic runtime, and then probably an integration test.  We also want to add a node e2e test to verify that the behavior doesn't regress.  We're changing a fundamental property of the kubelet (one that was racy before), so we want to make sure in the future we get the right outcome, and can't regress.

Comment (smarterclayton) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:510]: I would add a comment here explaining that between List (above) and check (here) another thread might remove a container, and that is normal.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 4]
```diff
@@ -1036,6 +1036,10 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(uid kubetypes.UID, name, namesp
 	podIPs := []string{}
 	for idx, podSandboxID := range podSandboxIDs {
 		podSandboxStatus, err := m.runtimeService.PodSandboxStatus(podSandboxID)
+		if crierror.IsNotFound(err) {
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1039]: Same comment as above, needs tests AND a comment describing this as a race condition between the previous call and the current call.

Roughly, the previous call (getSandboxIDByPodUID) never fails due to a pod sandbox not existing.  Therefore, this method should not either, but instead act as if the previous call failed, which means the error should be ignored.

**Comment by smarterclayton** [comment]
We should review all CRI call sites that do a `list` then `for list_item { inspect }` for this race (value in list but then cleaned up before inspect).  The general pattern is vulnerable to the same problem described here and it's the container runtime manager's job to hide that implementation detail.

@kubernetes/sig-node-bugs @mrunalp

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 3 above)
Comment (249043822) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:514]: Done

Comment (249043822) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:514]: @smarterclayton I can mock runtimeservice to throw a notfound error in unit test, but I could not catch any thing that can illustrate that syncTerminatingFn has encountered  notfound error in e2e test by kube-api(no event or no pod status change), so do you thank we can write such a e2e test for regression?

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go [hunk 5]
```diff
@@ -334,6 +336,44 @@ func TestGetPodStatus(t *testing.T) {
...
+
+	// Set fake sandbox and faked containers to fakeRuntime.
+	makeAndSetFakePod(t, m, fakeRuntime, pod)
+	fakeRuntime.InjectError("ContainerStatus", status.Error(codes.NotFound, "No such container"))
+	podStatus, err := m.GetPodStatus(pod.UID, pod.Name, pod.Namespace)
+	assert.NoError(t, err)
+	assert.Equal(t, pod.UID, podStatus.ID)
+	assert.Equal(t, pod.Name, podStatus.Name)
+	assert.Equal(t, pod.Namespace, podStatus.Namespace)
+	assert.Equal(t, apitest.FakePodSandboxIPs, podStatus.IPs)
```
Comment (endocrimes) [inline pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:374]:
```suggestion
	require.NoError(t, err)
	require.Equal(t, pod.UID, podStatus.ID)
	require.Equal(t, pod.Name, podStatus.Name)
	require.Equal(t, pod.Namespace, podStatus.Namespace)
	require.Equal(t, apitest.FakePodSandboxIPs, podStatus.IPs)
```

prefer require over assert, to avoid potentially crashing tests when assertions are not met.

**Comment by liushi001** [comment]
> > I think this might be a temporary solution. If another kind of error returns from `syncTerminatingPodFn`, we should retry to terminate the Pod again. Because the conainer maybe has not yet been killed.
> 
> Yea, this behavior is as expected, if `syncTerminatingPodFn` cause error, we really need retry. Because the target of `syncTerminatingPodFn` is to kill pod containers, so If this container happens to be deleted, we should tolerate this exception.
> 
> > I also tried a way to avoid it that adding a `status.working` condition in `(p *podWorkers) removeTerminatedWorker(uid types.UID)`. So after housekeeping `podSyncStatuses` can be clear. Then ADD a static manifest file can trigger `synPod` to start container.
> > But this method relies on housekeeping period. If I remove in and out manifest file in period of housekeeping, the container will keep running and cannot be restarted.
> > So I'm wondering if some larger scale refactoring is needed to fix the problem.
> > ```go
> > func (p *podWorkers) removeTerminatedWorker(uid types.UID) {
> > 	status, ok := p.podSyncStatuses[uid]
> > 	if !ok {
> > 		// already forgotten, or forgotten too early
> > 		klog.V(4).InfoS("Pod worker has been requested for removal but is not a known pod", "podUID", uid)
> > 		return
> > 	}
> > 
> > 	if !status.finished && status.working {
> > 		klog.V(4).InfoS("Pod worker has been requested for removal but is still not fully terminated", "podUID", uid)
> > 		return
> > 	}
> > 
> > 	if status.restartRequested {
> > 		klog.V(4).InfoS("Pod has been terminated but another pod with the same UID was created, remove history to allow restart", "podUID", uid)
> > 	} else {
> > 		klog.V(4).InfoS("Pod has been terminated and is no longer known to the kubelet, remove all history", "podUID", uid)
> > 	}
> > 	delete(p.podSyncStatuses, uid)
> > 	delete(p.podUpdates, uid)
> > 	delete(p.lastUndeliveredWorkUpdate, uid)
> > }
> > ```

But how to ensure other kind of errors can continue to retry stop containers when the pod is deleted from PodManger?

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go (hunk 5 above)
Comment (rphillips) [reply pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:374]: @249043822 could you update the PR to use 'require'?

Comment (249043822) [reply pkg/kubelet/kuberuntime/kuberuntime_manager_test.go]: okay @rphillips

**Comment by rphillips** [comment]
It looks like the issues have been addressed in this PR. Are there any further comments?

/lgtm

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 6]
```diff
@@ -714,15 +722,16 @@ func (m *kubeGenericRuntimeManager) killContainer(pod *v1.Pod, containerID kubec
 		"containerName", containerName, "containerID", containerID.String(), "gracePeriod", gracePeriod)
 
 	err := m.runtimeService.StopContainer(containerID.ID, gracePeriod)
-	if err != nil {
+	if err != nil && !crierror.IsNotFound(err) {
 		klog.ErrorS(err, "Container termination failed with gracePeriod", "pod", klog.KObj(pod), "podUID", pod.UID,
 			"containerName", containerName, "containerID", containerID.String(), "gracePeriod", gracePeriod)
+		return err
 	} else {
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:729]: You should remove this else.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 7]
```diff
@@ -19,13 +19,13 @@ package kuberuntime
 import (
 	"errors"
 	"fmt"
+	cadvisorapi "github.com/google/cadvisor/info/v1"
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:22]: This looks wrong, you might be missing the necessary goimports step to keep these in the right import section.

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go [hunk 8]
```diff
@@ -17,6 +17,8 @@ limitations under the License.
 package kuberuntime
 
 import (
+	"google.golang.org/grpc/codes"
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:20]: Same problem with imports here

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 3 above)
Comment (smarterclayton) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:513]: It should be possible to write a node e2e that creates the pod, then triggers a delete AND deletes the container.  However, for the sake of the fix, I don't think it's necessary here.

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go (hunk 8 above)
Comment (rphillips) [reply pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:20]: This is correct as well. [example](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L30)

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 6 above)
Comment (rphillips) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:729]: To clarify, the else on line 729 needs removed but to keep the log line.

Comment (249043822) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go]: Done

**Comment by rphillips** [comment]
retest

**Review by mrunalp — APPROVED** [review]

**Comment by rphillips** [comment]
@logicalhan can you approve for the vendor change?

**Review by endocrimes — APPROVED** [review]
/lgtm

for vendor/ approval:
/cc @dims

**Comment by logicalhan** [comment]
> @logicalhan can you approve for the vendor change?

sure 
/lgtm
