### PR TITLE
Fixes the regression of GCEPD not provisioning correctly on GKE alpha clusters.

### LINKED ISSUE #59047: Dynamic Volume Provisioning not working on GKE alpha clusters
/kind bug

**What happened**:

I created a new version 1.8.6-gke.0 alpha cluster on GKE and it no longer is allowing me to dynamically provision volumes. 

I tried a few things, creating a pvc with this yaml:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
spec:
  accessModes:
    - 'ReadWriteOnce'
  resources:
    requests:
      storage: '100Gi'
```
And observed this error when calling 'describe' on the resource:

```
Name:          pvc
Namespace:     default
StorageClass:  standard
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Capacity:
Access Modes:
Events:
  Type     Reason              Age              From                         Message
  ----     ------              ----             ----                         -------
  Warning  ProvisioningFailed  3s (x2 over 5s)  persistentvolume-controller  Failed to provision volume with StorageClass "standard": googleapi: Error 403: Required 'Alpha Access' permission for 'Compute API', forbidden
```

I also tried defining my own storage class, according to:
https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/
and encountered a similar error.

Yaml:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
spec:
  accessModes:
    - 'ReadWriteOnce'
  storageClassName: slow
  resources:
    requests:
      storage: '100Gi'
```

'Describe' output:

```
storageclass "slow" created
persistentvolumeclaim "pvc" created

Name:          pvc
Namespace:     default
StorageClass:  slow
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=kubernetes.io/gce-pd
Capacity:
Access Modes:
Events:
  Type     Reason              Age   From                         Message
  ----     ------              ----  ----                         -------
  Warning  ProvisioningFailed  3s    persistentvolume-controller  Failed to provision volume with StorageClass "slow": googleapi: Error 403: Required 'Alpha Access' permission for 'Compute API', forbidden
```
It seems I may be missing some 'Alpha Access'. Is there a way to sign up for this? Although it seems like this functionality was working before.

**What you expected to happen**:
Persistent Volume to be dynamically provisioned and bound to the persistent volume claim.

This methodology works on a 1.8.4.gke.X alpha cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Create a fresh alpha 1.8.6-gke.0 cluster on GKE and try using the above YAML.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.6-gke.0 
- Cloud provider or hardware configuration: Google Kubernetes Engine
- OS (e.g. from /etc/os-release): COS

### PR DESCRIPTION
**Pull request by verult**
Fixes the regression by better distinguishing between single-zone and multi-zone PDs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59047

**Special notes for your reviewer**: All PD and dynamic provisioning e2e tests pass, manually verified provision, delete, attach, and detach of both single-zone and multi-zone PDs. Will create e2e tests for multizone PDs in a separate PR.

**Release note**:

``` release-note
Bug fix: Clusters with GCE feature 'DiskAlphaAPI' enabled were unable to dynamically provision GCE PD volumes.
```

/sig storage
/assign @saad-ali

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce_disks.go [hunk 1]
```diff
@@ -398,9 +325,12 @@ func (manager *gceServiceManager) getDiskSourceURI(disk *GCEDisk) (string, error
 
 func (manager *gceServiceManager) getDiskTypeURI(
 	diskRegion string, diskZoneInfo zoneType, diskType string) (string, error) {
-	getProjectsAPIEndpoint := manager.getProjectsAPIEndpoint()
+
+	var getProjectsAPIEndpoint string
 	if manager.gce.AlphaFeatureGate.Enabled(AlphaFeatureGCEDisk) {
```
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce_disks.go]: Since this method is used by both `CreateDiskOnCloudProvider(...)` and `CreateRegionalDiskOnCloudProvider(...)`, we should probably not key off `AlphaFeatureGate.Enabled(AlphaFeatureGCEDisk)` alone, right? That would force standard disks that are running on alpha cluster to use the alpha api?

Comment (verult) [reply pkg/cloudprovider/providers/gce/gce_disks.go]: Agreed, better to pass that info in from the `CreateDisk...` methods.

**Comment by verult** [comment]
Addressed comments, and added basic attach unit test.

**Comment by verult** [comment]
Test issue: https://github.com/kubernetes/kubernetes/issues/59518

**Comment by saad-ali** [comment]
/lgtm
/approve

Fix bazel:
```
I0207 20:58:32.283] Verifying verify-bazel.sh
I0207 20:58:32.299] 
I0207 20:58:32.301] +++ Running case: verify.bazel 
I0207 20:58:32.303] +++ working dir: /go/src/k8s.io/kubernetes
I0207 20:58:32.305] +++ command: bash "hack/make-rules/../../hack/verify-bazel.sh"
I0207 20:58:51.167] diff -Naupr /go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD /tmp/verify-bazel.sga0kG/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD
I0207 20:58:51.168] --- /go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD	2018-02-07 20:54:40.213954347 +0000
I0207 20:58:51.168] +++ /tmp/verify-bazel.sga0kG/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD	2018-02-07 20:58:45.028965317 +0000
I0207 20:58:51.168] @@ -43,6 +43,7 @@ go_test(
I0207 20:58:51.168]      embed = [":go_default_library"],
I0207 20:58:51.169]      importpath = "k8s.io/kubernetes/pkg/volume/gce_pd",
I0207 20:58:51.169]      deps = [
I0207 20:58:51.169] +        "//pkg/kubelet/apis:go_default_library",
I0207 20:58:51.169]          "//pkg/util/mount:go_default_library",
I0207 20:58:51.169]          "//pkg/volume:go_default_library",
I0207 20:58:51.170]          "//pkg/volume/testing:go_default_library",
I0207 20:58:51.170] 
I0207 20:58:51.170] Run ./hack/update-bazel.sh
I0207 20:58:52.103] +++ exit code: 1
I0207 20:58:52.108] +++ error: 1
I0207 20:58:52.128] FAILED   verify-bazel.sh	20s
```

Also could you manually test and verify that RePD is working (create, attach, mount, etc.). And also verify that in a project that is not whitelisted for GCE alpha that standard PD works (create, attach, mount), but RePD fails?

**Comment by cblecker** [comment]
Legitimate verify-bazel failure:
```
I0208 05:12:20.879] Verifying verify-bazel.sh
I0208 05:12:20.894] 
I0208 05:12:20.896] +++ Running case: verify.bazel 
I0208 05:12:20.897] +++ working dir: /go/src/k8s.io/kubernetes
I0208 05:12:20.899] +++ command: bash "hack/make-rules/../../hack/verify-bazel.sh"
I0208 05:12:39.293] diff -Naupr /go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD /tmp/verify-bazel.fFjFv4/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD
I0208 05:12:39.293] --- /go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD	2018-02-08 05:08:43.249678444 +0000
I0208 05:12:39.294] +++ /tmp/verify-bazel.fFjFv4/go/src/k8s.io/kubernetes/pkg/volume/gce_pd/BUILD	2018-02-08 05:12:33.130579654 +0000
I0208 05:12:39.294] @@ -43,6 +43,7 @@ go_test(
I0208 05:12:39.295]      embed = [":go_default_library"],
I0208 05:12:39.295]      importpath = "k8s.io/kubernetes/pkg/volume/gce_pd",
I0208 05:12:39.296]      deps = [
I0208 05:12:39.296] +        "//pkg/kubelet/apis:go_default_library",
I0208 05:12:39.297]          "//pkg/util/mount:go_default_library",
I0208 05:12:39.297]          "//pkg/volume:go_default_library",
I0208 05:12:39.297]          "//pkg/volume/testing:go_default_library",
I0208 05:12:39.298] 
I0208 05:12:39.298] Run ./hack/update-bazel.sh
I0208 05:12:40.146] +++ exit code: 1
I0208 05:12:40.150] +++ error: 1
I0208 05:12:40.170] FAILED   verify-bazel.sh	20s
```

**Comment by cblecker** [comment]
/lgtm cancel
Removing LGTM to stop retesting loop

**Comment by verult** [comment]
@saad-ali I've done the following tests manually for multizone clusters, with DiskAlphaAPI both set and unset, and single-zone cluster with alpha flag unset:

- (Create) Dynamic provisioning with RePD storage class and Delete reclaim policy.
- (Attach & mount) Running a pod referencing the PVC created above.
- (Detach & unmount) Deleting the previous pod
- (Delete) Deleting the PVC created above.
And all of the above are done using the default gce-pd storage class as well.

**Comment by saad-ali** [comment]
Awesome, one more thing to run the same set of tests against an alpha cluster on a project that is not whitelisted for the GCE API (to verify the regression is fixed).

/lgtm

**Comment by saad-ali** [comment]
Once merged, this should be cherry picked to 1.9 and 1.8 branches.
