### PR TITLE
Parallelize attach operations across different nodes for volumes that allow multi-attach

### LINKED ISSUE #73972: Slow volume attach for single ReadOnlyMany volume across multiple nodes
**What happened**: A GCE PD volume is used in read-only mode (through a PVC & PV pair in ReadOnlyMany mode) by over 100 pods running across tens of nodes. Volume attachment sometimes takes over 30min for some of these pods.

**What you expected to happen**: Attaching should take seconds instead of minutes.

**How to reproduce it (as minimally and precisely as possible)**:
* Provision a read-only GCE PD, and the associated PVC & PV.
* Run a Job with parallelism of 100+ pods in a cluster with tens of nodes (we tested with 50+), and use the PD inside all pods.

**Anything else we need to know?**: Generally attach/detach calls are parallelized (through OperationExecutor), but calls with the same volume name are serialized. This was done as a way to prevent races between attach and detach calls for the same volume. However, it's sufficient to provide this guarantee for each node, as long as the volume is Read[Write|Only]Many.

https://github.com/kubernetes/kubernetes/blob/f96849981203ea506ea8fa3f88c173d36cf688aa/pkg/volume/util/operationexecutor/operation_executor.go#L607-L608

**Environment**:
- Kubernetes version (use `kubectl version`): Tested with multiple 1.10 patch releases (including 1.10.6 and 1.10.9)
- Cloud provider or hardware configuration: GCP

/sig storage
/priority critical-urgent
/assign
/cc @davidz627 @jingxu97 @msau42 @saad-ali

### PR DESCRIPTION
**Pull request by verult**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: This is the improved version of #87258 that fixes the problem discovered in #88355. The following is different from the previous PR:
* The fix: updated `getOperations()` and `deleteOperations()` in the second commit.
* Includes a unit test to capture the scenario that likely caused #88355, and captures the fix.
* Changed `operationKey` string representation to use `%s` instead of `%q`.

**Which issue(s) this PR fixes**:

Fixes #73972, and partially #88355

**Special notes for your reviewer**:
Special notes from #87258:
"""
There are 2 commits. The first one is a refactor of the operation key structure in NestedPendingOperations. The second one is the main change.

I'm not a fan of the method signature of Run() and IsOperationPending() (especially the giant comment block above Run()). I'd like to refactor it to use a single generic OperationKey type, but since it could be a controversial change I'm going to have it in a separate PR.
"""

**Does this PR introduce a user-facing change?**:

```release-note
For volumes that allow attaches across multiple nodes, attach and detach operations across different nodes are now executed in parallel.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

/sig storage
/assign @jingxu97 @misterikkit @saad-ali

### CODE REVIEW

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 1]
```diff
@@ -151,72 +178,69 @@ func (grm *nestedPendingOperations) Run(
...
+	return 0, fmt.Errorf("Operation %q not found", key)
 }
 
-func (grm *nestedPendingOperations) deleteOperation(
+func (grm *nestedPendingOperations) deleteOperation(key operationKey) {
 	// Assumes lock has been acquired by caller.
-	volumeName v1.UniqueVolumeName,
-	podName types.UniquePodName) {
 
 	opIndex := -1
```
Comment (verult) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: We should be defensive about indexing on a negative number and return if op isn't found. Update coming soon.

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by verult** [comment]
/hold
@misterikkit is in the middle of review. Feel free to remove when you think it's ready. Thanks!

**Comment by jsafrane** [comment]
@gnufied, can you please check this today?

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 2]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+	testConcurrentOperationsNegative(t,
+		v1.UniqueVolumeName("volume-name"),
+		"", /* podName1 */
+		types.NodeName("operation-nodename"),
+		v1.UniqueVolumeName("volume-name"),
+		"", /* podName2 */
+		"" /* nodeName2 */)
+}
+
+func Test_NestedPendingOperations_Negative_SecondOpBeforeFirstCompletes_FirstVolumeNode_SecondVolumeNode(t *testing.T) {
```
Comment (gnufied) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: Can we move these into one test with table driven tests?

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 3]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+	// op1(v1, n1) starts
+	// op2(v1, n2) starts
+	// opZ(v0) ends with success
+	// op2(v1, n2) ends with an error (exponential backoff should be triggered)
+	// op1(v1, n1) ends with success
+	// op3(v1, n2) starts (continuously retried on exponential backoff error)
+	// op3(v1, n2) ends with success
+	// op4(v1, n2) starts
+	// op4(v1, n2) ends with success
+
```
Comment (gnufied) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: It is still not clear to me how this led to PD leaks in e2e..

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 4]
```diff
@@ -29,45 +29,73 @@ import (
...
-	// This enables multiple operations to execute in parallel for the same
-	// volumeName as long as they have different podName.
+
+	// Run adds the concatenation of volumeName and one of podName or nodeName to
+	// the list of running operations and spawns a new go routine to execute
+	// OperationFunc inside generatedOperations.
+
+	// volumeName, podName, and nodeName collectively form the operation key.
+	// The following forms of operation keys are supported:
+	// - volumeName empty, podName empty, nodeName empty
```
Comment (jingxu97) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: just for completeness, when volumeName is empty, no matter podName, nodeName empty or not, there is no conflicting keys.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 5]
```diff
@@ -151,84 +178,84 @@ func (grm *nestedPendingOperations) Run(
...
+	if key.volumeName == EmptyUniqueVolumeName {
 		return false, -1
 	}
 
 	for previousOpIndex, previousOp := range grm.operations {
-		if previousOp.volumeName != volumeName {
-			// No match, keep searching
-			continue
-		}
+		volumeNameMatch := previousOp.key.volumeName == key.volumeName
```
Comment (jingxu97) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: if volumeNameMatch is false, we could skip it and continue with next loop.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 6]
```diff
@@ -29,45 +29,73 @@ import (
...
+	// volumeName, podName, and nodeName collectively form the operation key.
+	// The following forms of operation keys are supported:
+	// - volumeName empty, podName empty, nodeName empty
+	//   This key does not have any conflicting keys.
+	// - volumeName exists, podName empty, nodeName empty
+	//   This key conflicts with all other keys with the same volumeName.
+	// - volumeName exists, podName exists, nodeName empty
+	//   This key conflicts with:
+	//   - the same volumeName and podName
+	//   - the same volumeName, but no podName
```
Comment (jingxu97) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: maybe use empty name instead of "no name" in all places.

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 7]
```diff
@@ -182,9 +146,16 @@ func (rc *reconciler) reconcile() {
 			// This check must be done before we do any other checks, as otherwise the other checks
 			// may pass while at the same time the volume leaves the pending state, resulting in
 			// double detach attempts
-			if rc.attacherDetacher.IsOperationPending(attachedVolume.VolumeName, "") {
-				klog.V(10).Infof("Operation for volume %q is already running. Can't start detach for %q", attachedVolume.VolumeName, attachedVolume.NodeName)
-				continue
+			if util.IsMultiAttachForbidden(attachedVolume.VolumeSpec) {
+				if rc.attacherDetacher.IsOperationPending(attachedVolume.VolumeName, "" /* podName */, "" /* nodeName */) {
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go]: a small thing, change "" to nestedpendingoperations.EmptyNodeName and similar places?

Comment (jingxu97) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: also to save some code, maybe define podName and nodeName based on util.IsMultiAttachForbidden, and then share the same code.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 8]
```diff
@@ -151,84 +178,84 @@ func (grm *nestedPendingOperations) Run(
...
+func (grm *nestedPendingOperations) getOperation(key operationKey) (uint, error) {
 	// Assumes lock has been acquired by caller.
 
 	for i, op := range grm.operations {
-		if op.volumeName == volumeName &&
-			op.podName == podName {
+		if op.key.volumeName == key.volumeName &&
+			op.key.podName == key.podName &&
+			op.key.nodeName == key.nodeName {
 			return uint(i), nil
```
Comment (jingxu97) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: the fix to https://github.com/kubernetes/kubernetes/pull/87258/files is here?
just want to understand how this causes PD leaks. Do you have the workflow of how it happens?

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go (hunk 5 above)
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: The next few conditions evaluations should be pretty fast. For the sake of clarity I have a slight preference for the current form

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 7 above)
Comment (verult) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: >  small thing, change "" to nestedpendingoperations.EmptyNodeName and similar places?

The reconciler package actually doesn't import the nestedpendingoperations package. By referring to nestedpendingoperations.EmptyNodeName we might be breaking the abstraction boundary, though ideally Empty*Names should really be moved to a different place. On the other hand, I'm doing a refactor that will largely remove the need of specifying empty arguments, so IMO it's OK to leave them here for now.

> also to save some code, maybe define podName and nodeName based on util.IsMultiAttachForbidden, and then share the same code. Same thing applied below during attach.
The log messages are slight different between the two cases to make it more obvious which branch was followed

File: pkg/volume/util/operationexecutor/operation_executor_test.go [hunk 9]
```diff
@@ -222,7 +321,91 @@ func TestOperationExecutor_DetachVolumeConcurrently(t *testing.T) {
...
+		oe.DetachVolume(attachedVolumes[i], true /* verifySafeToDetach */, nil /* actualStateOfWorldAttacherUpdater */)
+	}
+
+	// Assert
+	if !isOperationRunSerially(ch, quit) {
+		t.Fatalf("DetachVolume operations should not run concurrently")
+	}
+}
+
+func TestOperationExecutor_DetachSingleNodeVolumeConcurrentlyFromDifferentNodes(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/operationexecutor/operation_executor_test.go]: I can't think of anything either :) over-tested a bit here, will remove

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 10]
```diff
@@ -29,45 +29,73 @@ import (
...
-	// and same operationName exits, an AlreadyExists or ExponentialBackoff
-	// error is returned. If an operation with same volumeName and podName
-	// has ExponentialBackoff error but operationName is different, exponential
-	// backoff is reset and operation is allowed to proceed.
-	// This enables multiple operations to execute in parallel for the same
-	// volumeName as long as they have different podName.
+
+	// Run adds the concatenation of volumeName and one of podName or nodeName to
+	// the list of running operations and spawns a new go routine to execute
+	// OperationFunc inside generatedOperations.
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: ACK, yeah some of this will be changed naturally when the key is more generic

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 11]
```diff
@@ -29,45 +29,73 @@ import (
...
+	// - volumeName exists, podName exists, nodeName empty
+	//   This key conflicts with:
+	//   - the same volumeName and podName
+	//   - the same volumeName, but no podName
+	// - volumeName exists, podName empty, nodeName exists
+	//   This key conflicts with:
+	//   - the same volumeName and nodeName
+	//   - the same volumeName but no nodeName
+
+	// If an operation with the same operationName and a conflicting key exists,
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: This is incorrect actually - operationName isn't considered at all when throwing an `alreadyExists` error. Updating

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 7 above)
Comment (jingxu97) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: it is a level 10 log, Also I don't see that difference matters. you log the volumename, nodename, isn't that enough?

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 12]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+		node1          = "node1"
+		node2          = "node2"
+
+		// delay after an operation is signaled to finish to ensure it actually
+		// finishes before running the next operation.
+		delay = 50 * time.Millisecond
+	)
+
+	grm := NewNestedPendingOperations(true /* exponentialBackOffOnError */)
+	opZContinueCh := make(chan interface{}, 0 /* bufferSize */)
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: I left it as `interface{}` this time around - couldn't figure out the appropriate value to pass into a `struct{}` channel quickly enough. Next time!

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 13]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+		t.Fatalf("NestedPendingOperations failed. Expected: <no error> Actual: <%v>", err1)
+	}
+
+	err2 := grm.Run(mainVolumeName, "" /* podName */, node2, volumetypes.GeneratedOperations{OperationFunc: operation2})
+	if err2 != nil {
+		t.Fatalf("NestedPendingOperations failed. Expected: <no error> Actual: <%v>", err2)
+	}
+
+	opZContinueCh <- true
+	time.Sleep(delay)
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: Yup! I thought about doing it with channels but it adds a lot of complexity to the reader trying to understand what the code is doing. Maybe there's a simpler way than what was on my mind though.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 14]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+
+	for {
+		err3 := grm.Run(mainVolumeName, "" /* podName */, node2, volumetypes.GeneratedOperations{OperationFunc: operation3})
+		if err3 == nil {
+			break
+		} else if !exponentialbackoff.IsExponentialBackoff(err3) {
+			t.Fatalf("NestedPendingOperations failed. Expected: <no error> Actual: <%v>", err3)
+		}
+		time.Sleep(100 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: It replicates the AttachDetachController reconciler delay. Changed it to a const

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 7 above)
Comment (verult) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: IMO it's still good to keep it because the log messages say slightly different things to more accurately describe what kind of operation is pending.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 15]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+	volumeName1 v1.UniqueVolumeName,
+	podName1 volumetypes.UniquePodName,
+	nodeName1 types.NodeName,
+	volumeName2 v1.UniqueVolumeName,
+	podName2 volumetypes.UniquePodName,
+	nodeName2 types.NodeName) {
+
+	// Arrange
+	grm := NewNestedPendingOperations(false /* exponentialBackOffOnError */)
+	operation1DoneCh := make(chan interface{}, 0 /* bufferSize */)
```
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: It's a lot of spots to change due to the fact that `Fatalf()` changes control flow. I made a note to include it for the refactor, but please bring it up if I forget

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 16]
```diff
@@ -141,7 +151,7 @@ func (grm *nestedPendingOperations) Run(
 			return NewAlreadyExistsError(opKey)
 		}
 
-		backOffErr := previousOp.expBackoff.SafeToRetry(opKey.String())
+		backOffErr := previousOp.expBackoff.SafeToRetry(fmt.Sprintf("%+v", opKey))
```
Comment (misterikkit) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: OMG can we include the exponential backoff package in the refactor? I just read why you even need to pass this string in.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 17]
```diff
@@ -737,6 +701,9 @@ func Test_NestedPendingOperations_Positive_Issue_88355(t *testing.T) {
 		// delay after an operation is signaled to finish to ensure it actually
 		// finishes before running the next operation.
 		delay = 50 * time.Millisecond
+
+		// Replicates the default AttachDetachController reconcile period
+		reconcilerPeriod = 100 * time.Millisecond
```
Comment (misterikkit) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: If the test actually depends on this time value matching one in the code under test, then it smells funny to me. However, I think it would be better to address this during the refactor.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 18]
```diff
@@ -590,129 +593,90 @@ func Test_NestedPendingOperations_Positive_WaitWithExpBackoff(t *testing.T) {
...
-	testConcurrentOperationsNegative(t,
-		v1.UniqueVolumeName("volume-name"),
-		EmptyUniquePodName,
-		types.NodeName("operation-nodename"),
-		v1.UniqueVolumeName("volume-name"),
-		EmptyUniquePodName,
-		EmptyNodeName)
-}
+		if test.expectPass {
+			testConcurrentOperationsPositive(t, test.testId,
```
Comment (misterikkit) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: It is better to use `t.Run()` than to pass the testId into the helper function. e.g.

```
t.Run(fmt.Sprintf("test %d", test.testId), func(t *testing.T){
    if test.expectPass...
})

**Review by misterikkit — COMMENTED** [review]
My only nit is to use t.Run instead of logging the test ID. Other than that, I'd say we can squash commits and get this merged.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 19]
```diff
@@ -564,6 +566,294 @@ func Test_NewGoRoutineMap_Positive_WaitWithExpBackoff(t *testing.T) {
...
+	}
+
+	opZContinueCh <- true
+	time.Sleep(delay)
+	op2ContinueCh <- true
+	time.Sleep(delay)
+	op1ContinueCh <- true
+	time.Sleep(delay)
+
+	for {
```
[the remark this answers is not in the document]
Comment (misterikkit) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: That seems like the right behavior to me. Just wanted to make sure that the failure mode did not hang tests.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (misterikkit) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: `Fatalf()` does not prevent a defer, but let's leave this as is since a lot will change in the refactor.

**Review by misterikkit — COMMENTED** [review]
/lgtm

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 20]
```diff
@@ -29,45 +29,83 @@ import (
...
-	Run(volumeName v1.UniqueVolumeName, podName types.UniquePodName, generatedOperations types.GeneratedOperations) error
+
+	// Run adds the concatenation of volumeName, podName, and nodeName to the list
+	// of running operations and spawns a new go routine to run
+	// generatedOperations.
+
+	// volumeName, podName, and nodeName collectively form the operation key.
+	// The following forms of operation keys are supported (two keys are designed
+	// to be "matched" if we want to serialize their operations):
+	// - volumeName empty, podName and nodeName could be anything
```
Comment (jingxu97) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: Is there any case that volumeName is empty?

**Comment by verult** [comment]
Weird, verify is shown as failed even though all the tests passed...

/test pull-kubernetes-verify
/test pull-kubernetes-e2e-gce-csi-serial

**Comment by mattjmcnaughton** [comment]
@verult do you mind sharing a little more about why this PR should be cherry-picked to previous releases? Is it to address the test flakes that you mentioned this change will help with?

Thanks :)

**Comment by gnufied** [comment]
I tend to agree with @mattjmcnaughton on this one. Why do we have to cherry pick this fix? The PR does not fixes something that was broken but speed things up (nice to have).

**Comment by verult** [comment]
@mattjmcnaughton @gnufied we are seeing many use cases where a user starts up many pods across many nodes all reading from the same volume. This is common especially among batch workloads (AI/ML use cases for example). For many users, taking an hour for something that should take no more than a few min is unacceptable and essentially renders this case unusable. Some users are considering Mesos instead since this is handled smoothly and attaches all happen in parallel.

**Comment by mattjmcnaughton** [comment]
> @mattjmcnaughton @gnufied we are seeing many use cases where a user starts up many pods across many nodes all reading from the same volume. This is common especially among batch workloads (AI/ML use cases for example). For many users, taking an hour for something that should take no more than a few min (at most) is unacceptable and essentially renders this case unusable. Some users are considering Mesos instead since this is handled smoothly and attaches all happen in parallel.

Thanks for the extra context :) I defer to whoever is in charge of cherry-picks :)

**Comment by tpepper** [comment]
> > @mattjmcnaughton @gnufied we are seeing many use cases where a user starts up many pods across many nodes all reading from the same volume. This is common especially among batch workloads (AI/ML use cases for example). For many users, taking an hour for something that should take no more than a few min (at most) is unacceptable and essentially renders this case unusable. Some users are considering Mesos instead since this is handled smoothly and attaches all happen in parallel.
> 
> Thanks for the extra context :) I defer to whoever is in charge of cherry-picks :)

This feels quite impactful and in my mind would merit cherry picking. The three cherry-picks first though need lgtm and approve from appropriate OWNERS.  Then the @kubernetes/patch-release-team will approve.

**Comment by mattjmcnaughton** [comment]
Thanks for the additional context @tpepper!

**Comment by mattjmcnaughton** [comment]
cc @saad-ali I assigned you to all of the cherry-picks, as you were the approver of the original diff. Thanks :)
