### PR TITLE
DRA: report NodePrepareResource errors

### LINKED ISSUE #118468: DRA: Kubelet doesn't report anything when it fails to prepare dynamic resources
### What happened?

When `PrepareResource` API fails there is no way to understand what happens because error is not reported.

### What did you expect to happen?

Error should be either logged or, better event should be recorded, so user would see it in the `kubelet describe pod` output.

### How can we reproduce it (as minimally and precisely as possible)?

1. Apply this patch to the kubernetes sources:
```
diff --git a/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml b/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
index 13b177c8426..c494a54b287 100644
--- a/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
+++ b/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
@@ -28,6 +28,7 @@ kind: Pod
 metadata:
   name: test-inline-claim
 spec:
+  nodeName: 127.0.0.1
   restartPolicy: Never
   containers:
   - name: with-resource
```

2. Create a pod: ```kubectl apply -f test/e2e/dra/test-driver/deploy/example/pod-inline.yaml```
3. Get the pod details: 
```
kubectl.sh describe pod test-inline-claim 
Using image: cos-97-16919-294-27 from project: cos-cloud as master image
Using image: cos-97-16919-294-27 from project: cos-cloud as node image
Name:             test-inline-claim
Namespace:        default
Priority:         0
Service Account:  default
Node:             127.0.0.1/127.0.0.1
Start Time:       Mon, 05 Jun 2023 18:50:16 +0300
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Containers:
  with-resource:
    Container ID:  
    Image:         registry.k8s.io/e2e-test-images/busybox:1.29-2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      set && mount && ls -la /dev/
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7snqh (ro)
  without-resource:
    Container ID:  
    Image:         registry.k8s.io/e2e-test-images/busybox:1.29-2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      set && mount && ls -la /dev/
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7snqh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-7snqh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```
4. There is not mentioning why pod is in pending state.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.0.949+9e4f74592c9037-dirty", GitCommit:"9e4f74592c90373a81a04392e165a63230851df9", GitTreeState:"dirty", BuildDate:"2023-05-16T08:40:17Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux devel 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Log an error and submit an event when NodePrepareResource fails.

#### Which issue(s) this PR fixes:

Fixes #118468

#### Does this PR introduce a user-facing change?

```release-note
Dynamic Resource Allocation: log a error and submit an event when Kubelet fails to prepare dynamic resources
```

/sig node

### CODE REVIEW

**Comment by sftim** [comment]
For the changelog entry, are we confident that readers understand what DRA is short for?

**Comment by bart0sh** [comment]
@sftim thank you for the review! updated the description as suggested.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -1099,7 +1099,13 @@ func (m *kubeGenericRuntimeManager) SyncPod(ctx context.Context, pod *v1.Pod, po
...
 		// Prepare resources allocated by the Dynammic Resource Allocation feature for the pod
 		if utilfeature.DefaultFeatureGate.Enabled(features.DynamicResourceAllocation) {
-			if m.runtimeHelper.PrepareDynamicResources(pod) != nil {
+			if err := m.runtimeHelper.PrepareDynamicResources(pod); err != nil {
+				ref, referr := ref.GetReference(legacyscheme.Scheme, pod)
+				if referr != nil {
+					klog.ErrorS(referr, "Couldn't make a ref to pod", "pod", klog.KObj(pod))
+				}
+				m.recorder.Eventf(ref, v1.EventTypeWarning, events.FailedPrepareDynamicResources, "Failed to prepare dynamic resources: %v", err)
+				klog.ErrorS(err, "Failed to prepare dynamic resources", "pod", klog.KObj(pod))
```
Comment (klueska) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1108]: I believe you need the additional return statement otherwise you end up accessing a nil ref later on:
```suggestion
			if err := m.runtimeHelper.PrepareDynamicResources(pod); err != nil {
				ref, referr := ref.GetReference(legacyscheme.Scheme, pod)
				if referr != nil {
					klog.ErrorS(referr, "Couldn't make a ref to pod", "pod", klog.KObj(pod))
					return
				}
				m.recorder.Eventf(ref, v1.EventTypeWarning, events.FailedPrepareDynamicResources, "Failed to prepare dynamic resources: %v", err)
				klog.ErrorS(err, "Failed to prepare dynamic resources", "pod", klog.KObj(pod))
```

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1108]: +1 and maybe add the `err` to the log in this case so the `err` will be at least in logs

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1108]: looking at the code around - this is actually a pattern. @bart0sh can you check what will be the behavior in case of `nil` and maybe more instance of this behavior needs to be fixed in this file

Comment (bart0sh) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: @klueska done, thanks for pointing out.

@SergeyKanzhelev considering that the code freeze is coming, I'd like to come up with another PR covering similar cases in the code around, so this one gets a chance to be accepted before the freeze. Makes sense?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -1089,7 +1089,14 @@ func (m *kubeGenericRuntimeManager) SyncPod(ctx context.Context, pod *v1.Pod, po
...
-			if m.runtimeHelper.PrepareDynamicResources(pod) != nil {
+			if err := m.runtimeHelper.PrepareDynamicResources(pod); err != nil {
+				ref, referr := ref.GetReference(legacyscheme.Scheme, pod)
+				if referr != nil {
+					klog.ErrorS(referr, "Couldn't make a ref to pod", "pod", klog.KObj(pod))
+					return
+				}
+				m.recorder.Eventf(ref, v1.EventTypeWarning, events.FailedPrepareDynamicResources, "Failed to prepare dynamic resources: %v", err)
+				klog.ErrorS(err, "Failed to prepare dynamic resources", "pod", klog.KObj(pod))
 				return
```
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1100]: OK; then better to error out at the point of error.

/lgtm
/approve
