### PR TITLE
Fixed: 22422 use singleflight to alleviate simultaneous calls to

### LINKED ISSUE #22422: Admission controllers can cause unnecessary significant load on apiserver
Recently we observed high latencies on POST pods on our scalability tests.
For more context see: https://github.com/kubernetes/kubernetes/issues/22340

It appeared to be throttling related, e.g.:

```
W0302 21:38:28.190204       5 request.go:627] Throttling request took 1.281100127s, request: GET:http://127.0.0.1:8080/api/v1/namespaces/e2e-tests-load-6cqci/limitranges
I0302 21:38:28.191235       5 handlers.go:152] GET /api/v1/namespaces/e2e-tests-load-6cqci/limitranges: (853.53Âµs) 200 [[kube-apiserver/v1.2.0 (linux/amd64) kubernetes/2cf9157] 127.0.0.1:58515]
I0302 21:38:28.193396       5 trace.go:57] Trace "Create /api/v1/namespaces/e2e-tests-load-6cqci/pods" (started 2016-03-02 21:38:26.908795629 +0000 UTC):
[20.412Âµs] [20.412Âµs] About to convert to expected version
[239.558Âµs] [219.146Âµs] Conversion done
[1.282815499s] [1.282575941s] About to store object in database
[1.284377959s] [1.56246ms] Object stored in database
[1.284389884s] [11.925Âµs] Self-link added
[1.284548334s] [158.45Âµs] END
```

As an example look at resource quota admission controller.
In https://github.com/kubernetes/kubernetes/pull/20446 there was some fallback added to use lru cache in case of on objects.
However, not what happens if we are sending multiple POST pods at the same time to apiserver.
What happens in Admit() if there are no results in Indexer, we list ResourceQuotas.
But if there are multiple calls at the same time, there can be multiple LISTs before the cache is updated:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/admission.go#L131
But this can cause throttling of these requests.

What we should do is: if there is List() in flight, we should wait until it is finished and lookupCache is updated.

@derekwaynecarr

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #22422

#### Does this PR introduce a user-facing change?

```release-note
Fixed: #22422 Admission controllers can cause unnecessary significant load on apiserver
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: plugin/pkg/admission/limitranger/admission.go [hunk 1]
```diff
@@ -161,21 +163,23 @@ func (l *LimitRanger) GetLimitRanges(a admission.Attributes) ([]*corev1.LimitRan
...
 		lruItemObj, ok := l.liveLookupCache.Get(a.GetNamespace())
 		if !ok || lruItemObj.(liveLookupEntry).expiry.Before(time.Now()) {
-			// TODO: If there are multiple operations at the same time and cache has just expired,
-			// this may cause multiple List operations being issued at the same time.
-			// If there is already in-flight List() for a given namespace, we should wait until
-			// it is finished and cache is updated instead of doing the same, also to avoid
-			// throttling - see #22422 for details.
-			liveList, err := l.client.CoreV1().LimitRanges(a.GetNamespace()).List(context.TODO(), metav1.ListOptions{})
+			// Fixed: #22422
+			// use singleflight to alleviate simultaneous calls to
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission.go:167]: there should be a regression test verifying the fix

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission.go:167]: I have added a test, please help me to see if this matches

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 2]
```diff
@@ -856,3 +857,50 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+	wg := sync.WaitGroup{}
+	for i := 0; i < 10; i++ {
+		wg.Add(1)
+		go func(wg *sync.WaitGroup) {
+			_, err := handler.GetLimitRanges(attributes)
+			if err != nil {
+				t.Errorf("unexpected error: %v", err)
+			}
+			wg.Done()
+		}(&wg)
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:900]: do you need to pass the wg var as parameter?
```suggestion
		go func() {
			defer wg.Done()
			_, err := handler.GetLimitRanges(attributes)
			if err != nil {
				t.Errorf("unexpected error: %v", err)
			}
		}()
```

nit, defer wg.Done() use to be more idiomatic

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 3]
```diff
@@ -856,3 +857,50 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+			ListMeta: metav1.ListMeta{
+				ResourceVersion: fmt.Sprintf("%d", len(limitRanges)),
+			},
+		}
+		for index, value := range limitRanges {
+			value.ResourceVersion = fmt.Sprintf("%d", index)
+			limitRangeList.Items = append(limitRangeList.Items, value)
+		}
+		// Set the latency to simulate the real environment
+		time.Sleep(200 * time.Millisecond)
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:880]: this is a low value and can flake, just set 1*time.Second

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 4]
```diff
@@ -856,3 +857,50 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+
+// TestLimitRanger_GetLimitRangesFixed22422 Fixed Admission controllers can cause unnecessary significant load on apiserver #22422
+func TestLimitRanger_GetLimitRangesFixed22422(t *testing.T) {
+	limitRange := validLimitRangeNoDefaults()
+	limitRanges := []corev1.LimitRange{limitRange}
+
+	count := 0
+	mockClient := &fake.Clientset{}
+	mockClient.AddReactor("list", "limitranges", func(action core.Action) (bool, runtime.Object, error) {
+		count++
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:869]: without the singleflight this will race, you can use an atomic counter 
var count int64
atomic.AddInt64(&count,1)

File: plugin/pkg/admission/limitranger/admission_test.go (hunk 3 above)
Comment (aojea) [reply plugin/pkg/admission/limitranger/admission_test.go:880]: hmm, I think we can do this more reliable if we add a select and block on a channel

Comment (aojea) [reply plugin/pkg/admission/limitranger/admission_test.go:880]: that you signal before the wg.Wait(), so you guarantee that all the request were sent

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 5]
```diff
@@ -856,3 +857,50 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+				t.Errorf("unexpected error: %v", err)
+			}
+			wg.Done()
+		}(&wg)
+	}
+	wg.Wait()
+	if count != 1 {
+		t.Errorf("Expected 1 limit range, got %d", count)
+	}
+}
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:906]: I would add another 

```
			_, err := handler.GetLimitRanges(attributes)
			if err != nil {
				t.Errorf("unexpected error: %v", err)
			}
```

and check that count == 2

**Comment by aimuz** [comment]
@aojea please take a look at it, I'm done with it

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 6]
```diff
@@ -856,3 +858,68 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+		wg.Add(1)
+		go func() {
+			defer wg.Done()
+			_, err := handler.GetLimitRanges(attributes)
+			if err != nil {
+				t.Errorf("unexpected error: %v", err)
+			}
+		}()
+	}
+	finished <- struct{}{}
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:905]: ok, so here we unhold all `handler.GetLimitRanges(attributes)` calls, that have to be aggregated

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 7]
```diff
@@ -856,3 +858,68 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+	wg.Wait()
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:906]: and here we wait for all the goroutines

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 8]
```diff
@@ -856,3 +858,68 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+	if count != 1 {
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:907]: since all the calls were holded, they must be catched on the singleflight group, hence only 1

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 9]
```diff
@@ -856,3 +858,68 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+		t.Errorf("Expected 1 limit range, got %d", count)
+	}
+
+	// invalidate the cache
+	handler.liveLookupCache.Remove(attributes.GetNamespace())
+	go func() {
+		finished <- struct{}{}
+	}()
```
Comment (aojea) [inline plugin/pkg/admission/limitranger/admission_test.go:915]: what is this doing?

Comment (aojea) [reply plugin/pkg/admission/limitranger/admission_test.go:915]: ah, ok, finished it is blocking until GetLimitRanges is executed

**Comment by aojea** [comment]
/lgtm
/assign @deads2k @liggitt 

can you please add comments on the test explaining the steps (I added some comments in github that may translated to comments in code , with better wording of course ;))

**Comment by aimuz** [comment]
I added the comment, please look at the

**Comment by aojea** [comment]
/lgtm
/ok-to-test

Thanks

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 10]
```diff
@@ -856,3 +858,75 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+		<-unhold
+		return true, limitRangeList, nil
+	})
+
+	handler, _, err := newHandlerForTest(mockClient)
+	if err != nil {
+		t.Errorf("unexpected error initializing handler: %v", err)
+	}
+
+	attributes := admission.NewAttributesRecord(nil, nil, api.Kind("kind").WithVersion("version"), "test", "name", api.Resource("resource").WithVersion("version"), "subresource", admission.Create, &metav1.CreateOptions{}, false, nil)
```
Comment (liggitt) [inline plugin/pkg/admission/limitranger/admission_test.go:893]: does anything test the namespace sharding of the singleflight to make sure that is working as expected?

Comment (aojea) [reply plugin/pkg/admission/limitranger/admission_test.go:893]: I thought about it, but since you hit the lrucache first, I couldn't see how to properly exercise it

```
		lruItemObj, ok := l.liveLookupCache.Get(a.GetNamespace())
```

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission_test.go:893]: Is this approach testable?

```
diff --git a/plugin/pkg/admission/limitranger/admission_test.go b/plugin/pkg/admission/limitranger/admission_test.go
index ea3853afecb..10f66b9759c 100644
--- a/plugin/pkg/admission/limitranger/admission_test.go
+++ b/plugin/pkg/admission/limitranger/admission_test.go
@@ -867,7 +867,8 @@ func TestLimitRanger_GetLimitRangesFixed22422(t *testing.T) {
        var count int64
        mockClient := &fake.Clientset{}
 
-       unhold := make(chan struct{})
+       unhold := make(chan struct{}, 1)
+
        mockClient.AddReactor("list", "limitranges", func(action core.Action) (bool, runtime.Object, error) {
                atomic.AddInt64(&count, 1)
 
@@ -908,6 +909,15 @@ func TestLimitRanger_GetLimitRangesFixed22422(t *testing.T) {
        unhold <- struct{}{}
        // and here we wait for all the goroutines
        wg.Wait()
+
+       // he will not block if there is a cache failure
+       unhold <- struct{}{}
+       // This call will use the cache, and if the count changes, it will be an error
+       _, err = handler.GetLimitRanges(attributes)
+       if err != nil {
+               t.Errorf("unexpected error: %v", err)
+       }
+
        // since all the calls were holded, they must be catched on the singleflight group,
        // hence only 1

```

Comment (liggitt) [reply plugin/pkg/admission/limitranger/admission_test.go:893]: I think this test is close, the fake client should just record the request count per namespace it was asked for, and you should make requests for a couple different namespaces to make sure singleflights share per namespace but not across them

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission_test.go:893]: I tweaked it so that it should meet the test requirements @liggitt  @aojea

File: plugin/pkg/admission/limitranger/admission.go [hunk 11]
```diff
@@ -161,21 +163,23 @@ func (l *LimitRanger) GetLimitRanges(a admission.Attributes) ([]*corev1.LimitRan
...
+			lruItemObj, err, _ = l.group.Do(a.GetNamespace(), func() (interface{}, error) {
```
Comment (liggitt) [inline plugin/pkg/admission/limitranger/admission.go:168]: if I switch this to partition on a constant string "x" instead of the namespace, the added unit test still passes, so the test is not effectively verifying this is correct

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission.go:168]: If the constant string x will be used, then he will partition all calls. If there are two concurrent calls with different namespaces, he will only call them once until the call returns. This should be the wrong behavior.

Currently using namespaces as partitions, this is partitioning a set of calls with the same namespace. This is the same behavior as using namespaces as keys for LRU caching before
@liggitt

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 12]
```diff
@@ -856,3 +858,89 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+	// unhold all the calls with the same namespace handler.GetLimitRanges(attributes) calls, that have to be aggregated
+	unhold <- struct{}{}
+	unhold <- struct{}{}
+
+	// and here we wait for all the goroutines
+	wg.Wait()
+	// since all the calls with the same namespace will be holded, they must be catched on the singleflight group,
+	// There are two different sets of namespace calls
+	// hence only 2
+	if count != 2 {
```
Comment (aimuz) [inline plugin/pkg/admission/limitranger/admission_test.go:927]: It actually shows up in the test, in the loop I turned on two different sets of namespace calls and he also correctly increased the count to 2, so I don't think it's a problem. @liggitt

File: plugin/pkg/admission/limitranger/admission_test.go [hunk 13]
```diff
@@ -856,3 +858,89 @@ func TestPersistentVolumeClaimLimitFunc(t *testing.T) {
...
+		}()
+
+		// simulation of different namespaces is not a call
+		go func() {
+			defer wg.Done()
+			_, err := handler.GetLimitRanges(attributesTest1)
+			if err != nil {
+				t.Errorf("unexpected error: %v", err)
+			}
+		}()
```
Comment (aimuz) [inline plugin/pkg/admission/limitranger/admission_test.go:916]: Two different sets of namespace calls are initiated here

File: plugin/pkg/admission/limitranger/admission.go (hunk 11 above)
Comment (liggitt) [reply plugin/pkg/admission/limitranger/admission.go:168]: using a constant string "x" here would be a bug, since it would make calls from different namespaces share a single lookup and use the same retrieved result. The unit test should fail under those circumstances, and it does not.

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission.go:168]: If you use the constant string x, the test will block

Comment (liggitt) [reply plugin/pkg/admission/limitranger/admission.go:168]: that's not what I'm seeing:

```shell
git diff
```

```diff
diff --git a/plugin/pkg/admission/limitranger/admission.go b/plugin/pkg/admission/limitranger/admission.go
index 4525463d2e6..907a28bda32 100644
--- a/plugin/pkg/admission/limitranger/admission.go
+++ b/plugin/pkg/admission/limitranger/admission.go
@@ -165,7 +165,7 @@ func (l *LimitRanger) GetLimitRanges(a admission.Attributes) ([]*corev1.LimitRan
                if !ok || lruItemObj.(liveLookupEntry).expiry.Before(time.Now()) {
                        // Fixed: #22422
                        // use singleflight to alleviate simultaneous calls to
-                       lruItemObj, err, _ = l.group.Do(a.GetNamespace(), func() (interface{}, error) {
+                       lruItemObj, err, _ = l.group.Do("x", func() (interface{}, error) {
                                liveList, err := l.client.CoreV1().LimitRanges(a.GetNamespace()).List(context.TODO(), metav1.ListOptions{})
                                if err != nil {
                                        return nil, admission.NewForbidden(a, err)
```

```shell
go test ./plugin/pkg/admission/limitranger -count=1 -v -run TestLimitRanger_GetLimitRangesFixed22422
=== RUN   TestLimitRanger_GetLimitRangesFixed22422
--- PASS: TestLimitRanger_GetLimitRangesFixed22422 (0.00s)
PASS
ok  	k8s.io/kubernetes/plugin/pkg/admission/limitranger	0.800s
```

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission.go:168]: I just updated it and the problem should be fixed

Comment (aimuz) [reply plugin/pkg/admission/limitranger/admission.go:168]: go test ./plugin/pkg/admission/limitranger -count=1 -v -run TestLimitRanger_GetLimitRangesFixed22422
=== RUN   TestLimitRanger_GetLimitRangesFixed22422
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
    admission_test.go:910: Expected test namespace, got test1
--- FAIL: TestLimitRanger_GetLimitRangesFixed22422 (0.00s)
FAIL
FAIL    k8s.io/kubernetes/plugin/pkg/admission/limitranger      0.792s
FAIL
