### PR TITLE
fix: --chunk-size with selector returns missing result

### LINKED ISSUE #110625: `--chunk-size` with selector returns missing result, so `describe node` / `drain` could be works wrong
### What happened?

`kubectl get` has `--chunk-size=500` by default, and since 1.22 `describe` `drain` has the same.   
 https://github.com/kubernetes/kubectl/issues/1028

They seem to return wrong results in certain situations combined with `--selector` / `--field-selector`.

And `kubectl describe node` / `kubectl drain` also use `--field-selector=spec.nodeName=NODE`, so they also don't work correctly.  
`describe node` outputs partial list of pods on the node, `drain` doesn't evict some of the pods.

To make it work correctly, I had to specify `--chunk-size=0`

### What did you expect to happen?

`get` `describe` `drain` works correctly with any `chunk-size`, since it's just a performance optimizing parameter.

### How can we reproduce it (as minimally and precisely as possible)?

I can't provide an actual concrete example (no `--chunk-size` = default `chunk-size=500`), but instead I show how to reproduce it with a smaller `chunk-size`

I believe that the same problem occurs with `chunk-size=500`

----

create two deployments.

```
$ kubectl create deployment hello-server --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0 --replicas=5
$ kubectl create deployment another-server --image=us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0 --replicas=5
```

 there are 5 pods in each.

```
$ kubectl get po
NAME                              READY   STATUS    RESTARTS   AGE
another-server-65f84969d6-h99mt   1/1     Running   0          4s
another-server-65f84969d6-hfc96   1/1     Running   0          4s
another-server-65f84969d6-lm26l   1/1     Running   0          4s
another-server-65f84969d6-vk44c   1/1     Running   0          4s
another-server-65f84969d6-x6vl5   1/1     Running   0          4s
hello-server-7bb955f957-db4sc     1/1     Running   0          58s
hello-server-7bb955f957-dsdpj     1/1     Running   0          58s
hello-server-7bb955f957-hdw8m     1/1     Running   0          58s
hello-server-7bb955f957-x9m4t     1/1     Running   0          58s
hello-server-7bb955f957-z44n2     1/1     Running   0          58s
```

with --selector=app=another-server and `--chunk-size=2`, it shows only 4 pods.

```
$ kubectl get po --selector=app=another-server --chunk-size=2
NAME                              READY   STATUS    RESTARTS   AGE
another-server-65f84969d6-h99mt   1/1     Running   0          10s
another-server-65f84969d6-hfc96   1/1     Running   0          10s
another-server-65f84969d6-lm26l   1/1     Running   0          10s
another-server-65f84969d6-vk44c   1/1     Running   0          10s
```

### Anything else we need to know?

I could confirm that the problem happens

* in both  case of `--selector` and  `--field-selector`
* regardless namespace, even with `-n kube-system`, or `--all-namespaces`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6-gke.1700", GitCommit:"694183800acb7cce57699639c06a9dd196c9f227", GitTreeState:"clean", BuildDate:"2022-05-13T09:31:28Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GCP / GKE Standard
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
It is easy to reproduce this bug:
```bash
# 1. create a 1.24 cluster
$ kind create cluster
# 2. create 2 deploy replicas=5
$ kubectl create deployment nginx1 --image=nginx --replicas=5 
$ kubectl create deployment nginx2 --image=nginx --replicas=5
# 3. You should get 5 results, but only get 4.
$ kubectl get po -l app=nginx1 --chunk-size=2
# 4. But if you use --chunk-size=1, you get the correct 5 results again
$ kubectl get po -l app=nginx1 --chunk-size=1
```
I have tested several versions and only the >= 1.24 version has errors.

I found that once I revert https://github.com/kubernetes/kubernetes/pull/108569, the error disappears. 😂 This means that it is https://github.com/kubernetes/kubernetes/pull/108569 that exposes the bug. 

But the version provided by [the reporter is v1.23.6-gke.1700](https://github.com/kubernetes/kubernetes/issues/110625#issue-1273646265). I did not reproduce the bug in the 1.23.6 cluster created by kind.

So I think this fix should at least cherry-pick to 1.23 to help other distributions fix this issue.

#### Which issue(s) this PR fixes:

Fixes #110625

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.24 regression that caused the wrong result length when using --chunk-size and --selector together
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/cmd/get.sh [hunk 1]
```diff
@@ -491,3 +491,26 @@ __EOF__
   set +o nounset
   set +o errexit
 }
+
+run_get_chunk_size_with_label_selector_tests() {
```
Comment (lavalamp) [inline test/cmd/get.sh:495]: This is not the right place to test that change, it should go in one of the list / pagination tests. Should be an integration test.

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go [hunk 2]
```diff
@@ -779,7 +779,7 @@ func growSlice(v reflect.Value, maxCapacity int, sizes ...int) {
 		return
 	}
 	if v.Len() > 0 {
-		extra := reflect.MakeSlice(v.Type(), 0, max)
+		extra := reflect.MakeSlice(v.Type(), v.Len(), max)
```
Comment (lavalamp) [inline staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go:782]: This is kind of a terrifying function and it needs a bunch of unit tests. ... it looks to have been broken quite badly in ways that should cause drastic problems everywhere it's used, so either it's barely ever called, or we're reading it wrong, but either way I need to see a unit test.

Comment (lavalamp) [reply staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go:782]: @logicalhan do you know anything about this function?

File: test/cmd/get.sh (hunk 1 above)
Comment (Abirdcfly) [reply test/cmd/get.sh]: Done.Function test and integration test have been updated.

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go (hunk 2 above)
Comment (Abirdcfly) [reply staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go:782]: > so either it's barely ever called

I agree with this opinion. I have tested several versions and only the >= 1.24 version has errors.

The current exposure of this problem depends on https://github.com/kubernetes/kubernetes/issues/108569's code modifications and  https://github.com/kubernetes/kubernetes/issues/110625's feedback. (Thanks @mborsz and @yokomotod!) 

@yokomotod's test case is typical, in fact, if only some objects with the same lables were created, this problem would not be reproduced, otherwise we would not have found a problem here.

Maybe other scenarios also have the problem, but we did not find the feedback

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go [hunk 3]
```diff
@@ -1199,6 +1203,9 @@ func Test_growSlice(t *testing.T) {
 			if tt.cap != tt.args.v.Cap() {
 				t.Errorf("Unexpected capacity: got=%d want=%d", tt.args.v.Cap(), tt.cap)
 			}
+			if tt.len != tt.args.v.Len() {
```
Comment (lavalamp) [inline staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go:1206]: Please also compare the elements to verify they didn't change (might require putting some values in).

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go [hunk 4]
```diff
@@ -1173,21 +1175,23 @@ func Test_growSlice(t *testing.T) {
 		},
 		{
 			name: "with existing capacity above max",
-			args: args{initialCapacity: 12, maxCapacity: 10, sizes: []int{8, 4}},
+			args: args{initialCapacity: 12, initialLen: 5, maxCapacity: 10, sizes: []int{8, 4}},
```
Comment (lavalamp) [inline staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go:1178]: Thanks -- can you duplicate these test cases before modifying? That way it's 100% clear that no existing test coverage is lost.

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go (hunk 2 above)
Comment (lavalamp) [reply staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go:782]: Can you open an issue to capture these two points? (I won't block this PR on them since the bug looks disastrous)
* I am skeptical that this function is actually an improvement over just letting the go runtime pick the size. I'd like to see benchmarks with it swapped out for just calling append.
* If we do keep it, this desperately needs to be rewritten to use the new type parameters instead of reflection.

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go (hunk 3 above)
Comment (Abirdcfly) [reply staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go:1220]: Done.

File: staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go (hunk 4 above)
Comment (Abirdcfly) [reply staging/src/k8s.io/apiserver/pkg/storage/etcd3/store_test.go:1188]: Done

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks for this fix!!

Can you file the issue I mentioned above so we don't forget?

**Comment by Abirdcfly** [comment]
@lavalamp I created a cherry-pick for v1.24 https://github.com/kubernetes/kubernetes/pull/110735 (the version where the bug was found). 

Maybe 1.23 is also needed, because the [reporter's version is v1.23.6-gke.1700](https://github.com/kubernetes/kubernetes/issues/110625#issue-1273646265), but I use kind 1.23 without reproducing this bug. (But the wrong code does exist in [1.23](https://github.com/kubernetes/kubernetes/blob/release-1.23/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L854))

Do you think we need to cherry-pick to a lower version? (According to the [releases documentation](https://kubernetes.io/releases/), we are now maintaining 4 versions of 1.21, 1.22, 1.23, 1.24, and the End of Life of 1.21 is 2022-06-28)

Can you give me some advice? Thanks!
