### PR TITLE
Fix service latency test.

### LINKED ISSUE #10248: Flaky e2e test: Service_endpoints_latency_should_not_be_very_high fails 70% of the time
@lavalamp This is still failing ~70% of the time. I'll open a separate issue to track fixing this.

Example Jenkins link: 
job/kubernetes-e2e-gce-flaky/1162/testReport/(root)/Kubernetes%20e2e%20suite/Service_endpoints_latency_should_not_be_very_high/history/

### PR DESCRIPTION
**Pull request by lavalamp**
- More accurate latency measurement.
- More lenient/sensible pass requirements.

Fixes #10248.

My cluster is passing with 15s/16s median/99p. It seems like that's much slower than it used to be.

### CODE REVIEW

File: test/e2e/service_latency.go [hunk 1]
```diff
@@ -85,45 +90,61 @@ var _ = Describe("Service endpoints latency", func() {
 		Logf("50 %%ile: %v", p50)
 		Logf("90 %%ile: %v", p90)
 		Logf("99 %%ile: %v", p99)
+		Logf("Total sample count: %v", len(dSorted))
 
-		if p99 > 4*p50 {
-			failing.Insert("Tail latency is > 4x median latency")
+		if p50 > time.Second*30 {
```
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Please make the multiplier a constant, rather than duplicate it in the equation and the message text.

File: test/e2e/service_latency.go [hunk 2]
```diff
@@ -85,45 +90,61 @@ var _ = Describe("Service endpoints latency", func() {
...
+			failing.Insert("Median latency should be less than 30 seconds")
 		}
-
-		if p50 > time.Second*20 {
-			failing.Insert("Median latency should be less than 20 seconds")
+		if p99 > time.Minute {
```
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: As above.

File: test/e2e/service_latency.go (hunk 1 above)
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: 30 seconds seems way too long.  I understand that it's what you're seeing empirically, but it seems that the system is broken, and should be fixed, rather than the tests tweaked.

File: test/e2e/service_latency.go [hunk 3]
```diff
@@ -144,58 +165,155 @@ func runServiceLatencies(f *Framework, inParallel, total int) (output []time.Dur
...
-func singleServiceLatency(f *Framework, i int) (time.Duration, error) {
-	// Make an RC with a single pod.
-	cfg := RCConfig{
-		Client:       f.Client,
-		Image:        "gcr.io/google_containers/pause:1.0",
-		Name:         fmt.Sprintf("trial-%v", i),
-		Namespace:    f.Namespace.Name,
-		Replicas:     1,
-		PollInterval: time.Second,
+type endpointQuery struct {
```
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Old code, but I'm pretty sure that you need to handle closed channels in the above for loop.  Github wouldn't let me put this comment there, so it's here :-)

File: test/e2e/service_latency.go [hunk 4]
```diff
@@ -144,58 +165,155 @@ func runServiceLatencies(f *Framework, inParallel, total int) (output []time.Dur
...
+	endpointsName string
+	endpoints     *api.Endpoints
+	result        chan<- struct{}
+}
+
+type endpointQueries struct {
+	requests map[string]*endpointQuery
```
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Indentation?

File: test/e2e/service_latency.go [hunk 5]
```diff
@@ -144,58 +165,155 @@ func runServiceLatencies(f *Framework, inParallel, total int) (output []time.Dur
...
+	eq := &endpointQueries{
+		requests: map[string]*endpointQuery{},
+
+		stop:        make(chan struct{}, 100),
+		requestChan: make(chan *endpointQuery),
+		seenChan:    make(chan *api.Endpoints, 100),
 	}
-	if err := RunRC(cfg); err != nil {
-		return 0, err
+	go eq.join()
```
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: This is just to check for failures on the above make's, right?  Probably worth a comment explaining.

Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Noooo!  Sorry - I get it.  Ignore above.

**Comment by quinton-hoole** [comment]
More review to come, but I got interrupted.

**Comment by timothysc** [comment]
@lavalamp how big is your cluster?

**Comment by lavalamp** [comment]
@timothysc 4 nodes

**Comment by timothysc** [comment]
/cc @rrati 

Our latencies are much higher on 25 node HA cluster.

File: test/e2e/service_latency.go (hunk 4 above)
Comment (lavalamp) [inline test/e2e/service_latency.go]: gofmt does the indentation :)

File: test/e2e/service_latency.go (hunk 3 above)
Comment (lavalamp) [inline test/e2e/service_latency.go]: Nothing closes those channels, so it should be fine.

File: test/e2e/service_latency.go (hunk 1 above)
Comment (lavalamp) [inline test/e2e/service_latency.go]: Yeah actually I'm seeing 15s, which is 3-4x what it used to be, and I agree that's too long. But I would like to get this in to keep it from getting worse. I can file an issue so we can track getting that back down again.

I'll change the conditions to be a constant.

Comment (lavalamp) [inline test/e2e/service_latency.go]: https://github.com/GoogleCloudPlatform/kubernetes/issues/10436

**Comment by lavalamp** [comment]
I added constants and a few more comments. PTAL

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Comment by rrati** [comment]
@lavalamp Have you tried the test on a cluster larger than 4? We've gotten the test to pass on a cluster of 8 nodes, but it fails on 22 nodes.  It seems like either kube isn't scaling properly for this test, or the variances in this test don't scale to larger clusters.

**Comment by lavalamp** [comment]
@rrati do you have the output of those runs handy? Can you send it to me or post it here?

If this latency increases with cluster size, that's actually a bug that needs to be fixed.

**Comment by rrati** [comment]
@lavalamp Tim posted our results in #10348.  Is there other data you would want?

That data is 4 days old.  I can run the test again on our 22 node cluster if you want recent/more data.

**Comment by lavalamp** [comment]
@rrati Actually that would be helpful if you could run it with this PR patched in, as I'm not sure if the version of this test currently committed measures the time correctly. Also, how much CPU do you give to controller-manager?

**Comment by rrati** [comment]
INFO: 50 %ile: 1m28.003322392s
INFO: 90 %ile: 1m35.316141426s
INFO: 99 %ile: 1m44.917936666s
INFO: Total sample count: 1100

  Median latency should be less than 30s
  Tail (99 percentile) latency should be less than 1m0s
  50, 90, 99 percentiles: 1m28.003322392s 1m35.316141426s 1m44.917936666s

This is on our 22 node cluster.  The controller-manager is running on a 40-core box.

File: test/e2e/service_latency.go (hunk 3 above)
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: As it stands at the moment, the second for loop will silently deadlock if total is not equal to the sum of errs and duration.  Wouldn't it be better to put a basic timeout on these reads so that you could produce a decent failure message, rather than a silent deadlock.
e.g here's a simple implementation:
http://blog.golang.org/go-concurrency-patterns-timing-out-and

Comment (quinton-hoole) [inline test/e2e/service_latency.go]: PS:  I realize that with the corrent code, this *shouldn't* happen, but, you know, bugs.

File: test/e2e/service_latency.go (hunk 4 above)
Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Fair enough - seems it got confused.

**Comment by quinton-hoole** [comment]
Other than relatively minor nit, LGTM.  It sounds like this test is actually going to fail on non-trivial sized clusters, but that's good if it confirms a system problem and provides good data to build a fix.

**Comment by quinton-hoole** [comment]
@thockin for a second TL LGTM.  This is purely e2e test code, and very useful.  Worth merging for v1.0, IMO.

**Comment by lavalamp** [comment]
Awesome, thanks.

I think the problem is rate limiting in the e2e test's client. I will update this shortly with a fix.

**Comment by lavalamp** [comment]
@rrati I took out the parts that were scaling the workload by the size of the cluster. I think this should fix its behavior in your cluster.

File: test/e2e/service_latency.go (hunk 3 above)
Comment (lavalamp) [inline test/e2e/service_latency.go]: If I use that pattern here, I have basically the same problem that makes ginkgo's timeout feature useless - outstanding goroutines which might use a *Framework pointer that is deallocated.

Comment (quinton-hoole) [inline test/e2e/service_latency.go]: Fair enough.  Add a log message that says "If this deadlocks, call @lavalamp " :-)

**Comment by rrati** [comment]
@lavalamp Here's the results with the latest changes:
INFO: 50 %ile: 2.230045533s
INFO: 90 %ile: 2.630304389s
INFO: 99 %ile: 2.831806407s
INFO: Total sample count: 200

I ran this multiple times and it always passed with the "worst" results being:
INFO: 50 %ile: 2.260581261s
INFO: 90 %ile: 2.580007133s
INFO: 99 %ile: 3.028985929s
INFO: Total sample count: 200

Removing the scaling to the cluster scaling makes the test run much faster and seems to pass, but is it sacrificing the validity of the test?  I don't know what the requirement is that spawned this test but is there, or should there be, a cluster size component?

**Comment by lavalamp** [comment]
@rrati Thanks, your cluster is better than mine :)

We haven't defined our target here. We'll probably want to eventually define a "loaded" state and run this test when the cluster is in that state.

**Comment by lavalamp** [comment]
Shippable is this flake, restarting:

F0629 22:50:56.456209 33315 integration.go:803] FAILED: unexpected endpoints: timed out waiting for the condition

**Comment by thockin** [comment]
LGTM

**Comment by wojtek-t** [comment]
Since this PR is ok-to-merge and this test is constantly failing on jenkin I'm merging it now.

**Comment by zmerlynn** [comment]
@wojtek-t: Thanks. I saw this in queue earlier, then totally forgot about when I pinged the other bug.
