### PR TITLE
move e2e hostport conflict test to sig-network

### LINKED ISSUE #98075: Exercise hostPort test in scheduler e2e for both Windows and Linux nodes
**Which jobs are failing**:
We want to change ownership of a test from scheduler to network
**Which test(s) are failing**:
[sig-scheduling] SchedulerPredicates [Serial] validates that there is no conflict between pods with same hostPort but different hostIP and protocol [Conformance]

**Since when has it been failing**:

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-windows-releases#aks-engine-azure-windows-master-staging-serial-slow
**Reason for failure**:
Once #97003 merges, we will exclude hostPort test on Windows. This is because of how the hostPort test is structured where we are relying on hostNetwork pod to test the communication between hostPort pods. This will not work on Windows as hostNetwork is not supported.

I think it is better to have this test in sig-network and test the communication as scheduler should be responsible only for assigning a pod to node. This also ensures that hostPort on Windows is exercised properly. 

**Anything else we need to know**:
More context [here](https://github.com/kubernetes/kubernetes/pull/96627#issuecomment-736978866)

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**

/kind cleanup
/kind failing-test

**What this PR does / why we need it**:

The test "validates that there is no conflict between pods with same
hostPort but different hostIP and protocol" was testing the scheduler
capability to schedule pods on the same node with hostPorts, however,
it wasn´t validating that the HostPorts was working, causing false
positives, because the pods were scheduled, but the HostPort exposed
wasn´t working.

In order to test the HostPort functionality, we have to use HostNetwork
pods, that are incompatible with Windows platforms. Also, since this
is touching both network and scheduling, there is no clear the ownership,
but sig-network is happy to adopt it.

We also add a new test for scheduling only under "scheduling", so Windows
folks can use it to test the scheduled in that platform.

**Which issue(s) this PR fixes**:
Fixes #98075

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @spiffxp @dims @BenTheElder @johnbelamaric 

I think that this conformance tests need to do more changes, just putting up the PR for discussion/guidance

xref: https://github.com/kubernetes/kubernetes/issues/98075

**Review by damemi — APPROVED** [review]
Agree that the functionality itself should belong to networking, while the scheduling test is sufficient for the scheduler's purposes. Thanks for addressing that todo!

/approve
from scheduling

File: test/e2e/network/hostport.go [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+	)
+
+	ginkgo.BeforeEach(func() {
+		cs = f.ClientSet
+		ns = f.Namespace.Name
+
+	})
+
+	/*
+		Release: v1.16
```
Comment (johnbelamaric) [inline test/e2e/network/hostport.go:52]: This should be `v1.16, v1.20` to show that the test behavior changed in 1.20. Otherwise this is good.

File: test/e2e/network/hostport.go [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+	)
+
+	ginkgo.BeforeEach(func() {
+		cs = f.ClientSet
+		ns = f.Namespace.Name
+
+	})
+
+	/*
+		Release: v1.20
```
Comment (spiffxp) [inline test/e2e/network/hostport.go:52]: I think @johnbelamaric's comment remains unaddressed here
```suggestion
		Release: v1.16, v1.20
```

Comment (aojea) [reply test/e2e/network/hostport.go:52]: 🤦

Comment (aojea) [reply test/e2e/network/hostport.go]: that happens when you are closing your laptop and thinks ... I an send one more patch is a simple change :)

**Comment by aojea** [comment]
/retest
unrelated failures

**Review by ravisantoshgudimetla — APPROVED** [review]
Thank you for working on this @aojea 

/approve

**Comment by aojea** [comment]
/assign @dcbw @danwinship 
for sig network approval

**Review by spiffxp — APPROVED** [review]
/lgtm
/approve
for conformance, but since I am a test/ approver...
/hold
for network approvers that @aojea cc'ed, please /hold cancel if you're satisfied

**Comment by aojea** [comment]
/hold cancel

I will take the blame for sig-network  ;)

**Comment by aojea** [comment]
/retest
storage and node failures

**Comment by nraghavan86** [comment]
Hi,
Can you please let me know if this patch will be made available for k8s 1.20.1?

**Comment by aojea** [comment]
> Hi,
> Can you please let me know if this patch will be made available for k8s 1.20.1?

Can you elaborate on the need to backport this?

**Comment by nraghavan86** [comment]
> 
> 
> > Hi,
> > Can you please let me know if this patch will be made available for k8s 1.20.1?
> 
> Can you elaborate on the need to backport this?

I am currently using k8s v1.20.1 and I see the conformance tests are failing. The test case which is failing is "validates that there is no conflict between pods with same hostPort but different hostIP and protocol". The port 54321 is not getting opened which is causing the failure.
/bin/sh -c curl -g --connect-timeout 5 --interface x.x.x.x http://127.0.0.1:54321/hostname -> This particular curl is failing.

**Review by Cheef5 — COMMENTED** [review]
https://discord.gg/w8sSmkTk

**Comment by aojea** [comment]
The test was wrong and this fixed it, however, there were certain implementations with a bug that, because the test was wrong, were passing when they had to fail. If you are using dockershim you need this fix https://github.com/kubernetes/kubernetes/pull/98755

**Comment by johnbelamaric** [comment]
And that fix will be cherry picked back to 1.20, so that should do it.

**Comment by aojea** [comment]
I just cherry-picked it to 1.20 https://github.com/kubernetes/kubernetes/pull/98838, the next minor release will have the fix and pass the conformance test.
sorry for the inconveniences
