### PR TITLE
tolerate existing subpath on pod update when feature is disabled

### LINKED ISSUE #70270: Pod can't be deleted because  of feature disabled
**What happened**:
1. We used to run k8s1.9, which has volume subpath feature enabled.
 https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath

Then user create pods with volume subpath.
User's pods have finalizers.

2. Since we met many issues with this feature at k8s 1.9.  
related link: https://github.com/kubernetes/kubernetes/issues/61563
We decide to disable this feature when we upgrade to k8s 1.10

3. After we upgrade to k8s 1.10, some of the pods which use volumepath feature are still running on the cluster. It has subpath field in their pod spec, but now  we can't remove the pod's finalizer,  because of

```
Err:Pod \"api-xxxx\" is invalid: spec.containers[0].volumeMounts.subPath: Forbidden: subPath is disabled by feature-gate\n","stream":"stderr","time":"2018-10-18T18:48:25.343285188Z"
```
4. So the pod will stuck at terminating and can't be deleted.

**What you expected to happen**:
The pod can be deleted. 
The api validation should handle this case.

**How to reproduce it (as minimally and precisely as possible)**:
1. In the cluster, enable volume subpath feature
2. Create a pod with this feature.
3. Add a finalizer to the pod
4. Disable this feature 
5. Delete the pod , and remove the finalizer manually
6. Pod stuck at `terminating`
 
**Anything else we need to know?**:
I think issue should happens for many of the features , not just volume subpath
@msau42 's comments is valuable for solve this kind of issue.
https://github.com/kubernetes/kubernetes/pull/65829#issuecomment-432441449

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Failing validation on the existence of this field meant that pods (or some immutable pod-spec containing objects) containing subpath volume mounts could not be deleted once the feature was disabled.

See updated guidance around API changes: https://github.com/kubernetes/community/pull/3040

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70270

**Does this PR introduce a user-facing change?**:
```release-note
fixes an issue deleting pods containing subpath volume mounts with the VolumeSubpath feature disabled
```

@kubernetes/sig-storage-pr-reviews

### CODE REVIEW

File: pkg/api/pod/util.go [hunk 1]
```diff
@@ -312,6 +312,10 @@ func DropDisabledVolumeMountsAlphaFields(volumeMounts []api.VolumeMount) {
 			volumeMounts[i].MountPropagation = nil
 		}
 	}
+
+	if !utilfeature.DefaultFeatureGate.Enabled(features.VolumeSubpath) {
```
Comment (msau42) [inline pkg/api/pod/util.go]: This will cause kubelet to successfully mount but at the wrong path (volume root).  Are we expecting that the application container handles this appropriately by crashing?
