### PR TITLE
Read number of running processes from /proc/loadavg.

### LINKED ISSUE #107107: PIDPressure incorrect when system thread number exceeds 65538
### What happened?

Condition PIDPressure is not set to true when the system thread number exceeds 65538 even it's reaching the limit.

### What did you expect to happen?

Condition PIDPressure is set to true correctly

### How can we reproduce it (as minimally and precisely as possible)?

See cause below

### Anything else we need to know?

The bug is due to [using linux syscall](https://github.com/kubernetes/kubernetes/blob/712745cb6755b3a28ca12292b30d138d5f737aa6/pkg/kubelet/stats/pidlimit/pidlimit_linux.go#L43) `sysinfo`, which truncates any process number greater than 65538 because of type conversion.

See kernel code [here](https://elixir.bootlin.com/linux/latest/source/kernel/sys.c#L2571). Reading it from `/proc/loadavg` should be working.

### Kubernetes version

v1.23.1

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ uname -a
5.10.46
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by linxiulei**
Fallback to using sysinfo syscall if failed.

Fixes kubernetes#107107

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #107107

#### Does this PR introduce a user-facing change?

None

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go [hunk 1]
```diff
@@ -39,12 +41,33 @@ func Stats() (*statsapi.RlimitStats, error) {
...
-	procs := int64(info.Procs)
-	rlimit.NumOfRunningProcesses = &procs
+	if procs, err := runningProcNum(); err == nil {
+		rlimit.NumOfRunningProcesses = &procs
+	} else {
+		var info syscall.Sysinfo_t
+		syscall.Sysinfo(&info)
+		procs := int64(info.Procs)
+		rlimit.NumOfRunningProcesses = &procs
+	}
```
Comment (sftim) [inline pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: If opening `/proc/loadavg` fails, won't this bear a risk of giving an erroneous reading?

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go [hunk 2]
```diff
@@ -39,12 +41,33 @@ func Stats() (*statsapi.RlimitStats, error) {
...
+	if err != nil {
+		return 0, err
+	}
+	fields := strings.Fields(string(bytes))
+	if len(fields) < 5 {
+		return 0, fmt.Errorf("not enough fields in /proc/loadavg")
+	}
+	subfields := strings.Split(fields[3], "/")
+	if len(subfields) != 2 {
+		return 0, fmt.Errorf("not enough fields in third field of /proc/loadavg")
```
Comment (sftim) [inline pkg/kubelet/stats/pidlimit/pidlimit_linux.go:70]:
```suggestion
		return 0, fmt.Errorf("error parsing fourth field of /proc/loadavg")
```

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go [hunk 3]
```diff
@@ -39,12 +41,33 @@ func Stats() (*statsapi.RlimitStats, error) {
...
+		procs := int64(info.Procs)
+		rlimit.NumOfRunningProcesses = &procs
+	}
 
 	rlimit.Time = v1.NewTime(time.Now())
 
 	return rlimit, nil
 }
+
+func runningProcNum() (int64, error) {
```
Comment (sftim) [inline pkg/kubelet/stats/pidlimit/pidlimit_linux.go:58]: I would call this `countRunningTasks`. The number of running processes is typically much smaller than the number of tasks that this function actually returns (on Linux).
(yes, I know that the caller then stores this into a variable named `procs`)

**Review by sftim — COMMENTED** [review]
Some thoughts on the proposed code. I hope this feedback helps.

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go (hunk 3 above)
Comment (sftim) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:58]: Another name could be `fetchCountOfRunningTasks`.

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go (hunk 1 above)
Comment (linxiulei) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: Yes, however it doesn't make thing worse compared to previous code. 

Another possibility is that /proc/loadavg might be open and read successfully, but the content has been changed in format so the functions returns an error. 

I might be too conservative to keep the sysinfo code here.

Comment (matthyx) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: I think it makes sense to keep it... at least for compatibility with older kernels?
I guess it's not easy to add a test with 65k+ processes to show the benefits of this patch?
/ok-to-test

**Comment by matthyx** [comment]
I'll wait for the regular triage process to happen on the issue first...

**Comment by linxiulei** [comment]
/retest

flake #106904

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go (hunk 1 above)
Comment (sftim) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: Maybe we can start a pod that creates 65k+ tasks (on Linux, POSIX threads implemented as kernel tasks consume a PID each)? It's definitely possible to make that container image.

Comment (sftim) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: I made a tool that might help with this testing: https://github.com/sftim/manytasks

Comment (matthyx) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: rust XD
@sftim looks good, however not sure if that fits our e2e testing... at least for local tinkering for sure it helps

Comment (sftim) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:51]: > rust

The prototype was Perl...

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go [hunk 4]
```diff
@@ -39,12 +41,33 @@ func Stats() (*statsapi.RlimitStats, error) {
...
 	}
 
-	var info syscall.Sysinfo_t
-	syscall.Sysinfo(&info)
-	procs := int64(info.Procs)
-	rlimit.NumOfRunningProcesses = &procs
+	if procs, err := runningTaskCount(); err == nil {
+		rlimit.NumOfRunningProcesses = &procs
+	} else {
+		var info syscall.Sysinfo_t
```
Comment (bobbypage) [inline pkg/kubelet/stats/pidlimit/pidlimit_linux.go:47]: can we leave a comment here on why we prefer to use /proc/loadavg as opposed to `Sysinfo`, i.e. link to https://github.com/kubernetes/kubernetes/issues/107107?

Comment (linxiulei) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:47]: Done. Thanks

File: pkg/kubelet/stats/pidlimit/pidlimit_linux.go [hunk 5]
```diff
@@ -39,12 +41,36 @@ func Stats() (*statsapi.RlimitStats, error) {
...
+	}
 
 	rlimit.Time = v1.NewTime(time.Now())
 
 	return rlimit, nil
 }
+
+func runningTaskCount() (int64, error) {
+	// Example: 1.36 3.49 4.53 2/3518 3715089
+	bytes, err := ioutil.ReadFile("/proc/loadavg")
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/stats/pidlimit/pidlimit_linux.go:63]: let's have an e2e test for this functionality so we can make sure to catch potential issues with the format change.

Comment (linxiulei) [reply pkg/kubelet/stats/pidlimit/pidlimit_linux.go:63]: There is an e2e test for pid eviction https://github.com/kubernetes/kubernetes/blob/8a259641532d12f730d0fc6b237d36206d405e52/test/e2e_node/eviction_test.go#L448. I think it should be able to catch the format change.

**Review by matthyx — APPROVED** [review]

**Review by mrunalp — APPROVED** [review]
