### PR TITLE
fix namespace termination conditions to be consistent and correct

### LINKED ISSUE #82194: namespace conditions are not consistently set during termination
In https://github.com/kubernetes/kubernetes/pull/73405, terminating namespaces got new conditions, but they are not cleared on fully successful runs and when they are `False` (the good state), they are not written if they aren't present.

I think it's ok that these are not present when namespaces active (not in terminating), but once we observe terminating namespaces, the conditions need to be consistently present and correct.

/assign
@kubernetes/sig-api-machinery-bugs 
/priority important-soon

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/82194

This updates the conditions to be set correctly event when they succeed.  Before, if you had other finalizers, you could get stuck with conditions saying things were broken when they were actually ok.

/kind bug
/priority important-soon
@kubernetes/sig-api-machinery-bugs 

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
This lgtm, I'll allow @p0lynomial have final saying

File: pkg/controller/namespace/deletion/status_condition_utils_test.go [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+			},
+			startingStatus: &v1.NamespaceStatus{
+				Conditions: []v1.NamespaceCondition{
+					{Type: v1.NamespaceDeletionGVParsingFailure, Status: v1.ConditionFalse},
+					{Type: v1.NamespaceDeletionDiscoveryFailure, Status: v1.ConditionTrue},
+				},
+			},
+			expecteds: []v1.NamespaceCondition{
+				{Type: v1.NamespaceDeletionGVParsingFailure, Status: v1.ConditionTrue, Reason: "foo", Message: "bar"},
+				*newSuccessfulCondition(v1.NamespaceDeletionDiscoveryFailure),
```
Comment (p0lyn0mial) [inline pkg/controller/namespace/deletion/status_condition_utils_test.go]: I tend not to use "production" code in testing code, unintentional changes to code are more visible.

File: test/integration/namespace/ns_conditions_test.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+	informers.Start(stopCh)
+	go nsController.Run(5, stopCh)
+
+	data := etcd.GetEtcdStorageDataForNamespace(nsName)
+	podJSON, err := jsonToUnstructured(data[corev1.SchemeGroupVersion.WithResource("pods")].Stub, "v1", "Pod")
+	if err != nil {
+		t.Fatal(err)
+	}
+	_, err = dynamicClient.Resource(corev1.SchemeGroupVersion.WithResource("pods")).Namespace(nsName).Create(podJSON, metav1.CreateOptions{})
+	if err != nil {
```
Comment (p0lyn0mial) [inline test/integration/namespace/ns_conditions_test.go]: What is the advantage of using the dynamic client here? Wouldn't the standard client would make the code more readable?

**Review by p0lyn0mial — COMMENTED** [review]
some nits, feel free to merge it.

**Comment by guineveresaenger** [comment]
We really need this to merge before Monday 9/9 EOD - hopefully a retest will merge this.

/test pull-kubernetes-e2e-gce
