### PR TITLE
Kube-proxy/ipvs; Use go "net" lib to get nodeIPs

### LINKED ISSUE #93858: DualStack: NodePort failed when opening dual-stack with ipvs
**What happened**:
when i created nodeport service by opening dual-stack ,it's faild. i check the kube-proxy by 
```shell
netsat -anp|grep kube-proxy
```
and got nothing 
**What you expected to happen**:
nodeport works well when dual-stack
**How to reproduce it (as minimally and precisely as possible)**:
open dual-stack and create a nodeport service 
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.17.5 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
```shell
uname -a
Linux k8s 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):knitter
- Others:
see the pr：

#93631

### PR DESCRIPTION
**Pull request by uablrek**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

To get node addresses to be used for nodePorts using netlink to read the local routing table was unnecessary complex and caused problems with older kernels as reported in #93858.

Using the go `net` library makes the code cleaner and more maintainable while reducing dependencies.

#### Which issue(s) this PR fixes:

Fixes #93858

#### Special notes for your reviewer:

I have limit the update to one file.

The "NetLinkHandle" in the `realIPGetter` is not really needed but unfortunately the unit tests are using the `realIPGetter` with a fake NetLinkHandle. So to limit the size of the PR (and the risk of mistakes) I let it be.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

File: pkg/proxy/ipvs/netlink_linux.go [hunk 1]
```diff
@@ -123,72 +124,67 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
+	for _, i := range ifaces {
+		if i.Name == filterDev {
+			continue
+		}
+		h.appendAddresses(ips, &i)
+	}
+	return ips, nil
+}
+
+func (h *netlinkHandle) appendAddresses(ips sets.String, ifi *net.Interface) {
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:163]: you don't need this to be a method, actually none of those, but I assume you want them to keep compatible the code

File: pkg/proxy/ipvs/netlink_linux.go [hunk 2]
```diff
@@ -123,72 +124,67 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
+	ifaces, err := net.Interfaces()
 	if err != nil {
-		return nil, fmt.Errorf("error list route table, err: %v", err)
+		return nil, fmt.Errorf("Could not get interfaces: %v", err)
 	}
-	res := sets.NewString()
-	for _, route := range routes {
-		if route.LinkIndex == filterLinkIndex {
+	ips := sets.NewString()
+	for _, i := range ifaces {
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:154]: I always struggle with this , but I think that you have to capture this variable since you are passing it as reference
https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
```
i := i
```

File: pkg/proxy/ipvs/netlink_linux.go (hunk 1 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:163]: I actually wrote all logic into `proxier.go` but then I realized that would force me to re-write the unit-tests quite extensively. I had to balance the work a bit.

File: pkg/proxy/ipvs/netlink_linux.go [hunk 3]
```diff
@@ -123,72 +124,67 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
+		if i.Name == filterDev {
+			continue
+		}
+		h.appendAddresses(ips, &i)
+	}
+	return ips, nil
+}
+
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:162]: a personal thought, is not clearer to have a function
```
func getInterfaceAddresses(ifi *net.Interface) []string {
}
```
and do the set insertions in the main loop?

File: pkg/proxy/ipvs/netlink_linux.go [hunk 4]
```diff
@@ -123,72 +124,67 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
-// --> result set: [10.0.0.1, 10.0.0.10, 10.0.0.252, 100.106.89.164, 127.0.0.1, 172.17.0.1, 192.168.122.1]
-
-// If dev is specified, it's equivalent to exec:
-// $ ip route show table local type local proto kernel dev kube-ipvs0
-// 10.0.0.1  scope host  src 10.0.0.1
-// 10.0.0.10  scope host  src 10.0.0.10
-// Then cut the unique src IP fields,
-// --> result set: [10.0.0.1, 10.0.0.10]
-
-// If filterDev is specified, the result will discard route of specified device and cut src from other routes.
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:147]: I found these examples useful

File: pkg/proxy/ipvs/netlink_linux.go (hunk 3 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:162]: Good point. I'll check that :+1:

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:162]: Would remove the reference-issue also.

File: pkg/proxy/ipvs/netlink_linux.go (hunk 4 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:147]: I'll bring them back. But there is a copy in `proxier.go` I think.

File: pkg/proxy/ipvs/netlink_linux.go (hunk 2 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:154]: I think it's ok in this case. The interface pointer &i is only used within the loop to get the addresses. It's not stored anywhere.

Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:154]: yeah, but `h.appendAddresses(ips, &i)`  will only use the last value, check this example from the link I pasted
```
While this example might look a bit obvious, the same unexpected behavior could be more hidden in some other cases. For example, the loop variable can be an array and the reference can be a slice:
func main() {
	var out [][]int
	for _, i := range [][1]int{{1}, {2}, {3}} {
		out = append(out, i[:])
	}
	fmt.Println("Values:", out)
}
Output:

Values: [[3] [3] [3]]
```

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:154]: But in that example you have actually stored an address in `out`. In `h.appendAddresses(ips, &i)` the pointer is just used once.

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:154]: And I made some printouts when testing and addresses from all interfaces are checked and added.

Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:154]: I told you that I always struggle with it XD, if you've tested it has to be ok

File: pkg/proxy/ipvs/netlink_linux.go (hunk 3 above)
Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:162]: checking in, do you prefer current format and no try to return a slice instead of  set?

File: pkg/proxy/ipvs/netlink_linux.go (hunk 4 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: The comments are back

File: pkg/proxy/ipvs/netlink_linux.go [hunk 5]
```diff
@@ -143,52 +148,62 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
+			ip = v.IP
+		case *net.IPNet:
+			ip = v.IP
+		default:
 			continue
 		}
 		if h.isIPv6 {
-			if route.Dst.IP.To4() == nil && !route.Dst.IP.IsLinkLocalUnicast() {
-				res.Insert(route.Dst.IP.String())
+			if ip.To4() != nil || ip.IsLinkLocalUnicast() {
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:199]: this applies to ipv4 to, do you want to discard them only for ipv6?
https://golang.org/src/net/ip.go?s=4256:4294#L143

Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:199]: you can simplify the check with the utitlnet.IsIPv6 from net/utils and avoid nested ifs
```
if h.isIPv6 != utilnet.IsIPv6(ip) {
   continue
}
if h.isIPv6 && ip.IsLinkLocalUnicast() {
   continue
}
```

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:199]: Better! Thanks. I will update

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:199]: I keep the link-local check for ipv6 only. The thing is that for ipv6 a "scope" is required for link-local addresses, which is an interface, like `fe80::200:ff:fe01:1%eth0` and they are usually auto-assigned so they are always there. For ipv4 it would be possible to use them I think, and whey must have been configured by some one.

**Comment by aojea** [comment]
LGTM
/assign @andrewsykim 
for final approval

**Comment by aojea** [comment]
/hold

I need to apologise, seems that using the go net library has performance issues
https://github.com/kubernetes/kubernetes/pull/103116

**Comment by uablrek** [comment]
Re-factored with `net.InterfaceAddrs()`.

**Comment by aojea** [comment]
/lgtm

This was stuck for a long time, if after some days nobody else review I think we can just unhold it

File: pkg/proxy/ipvs/netlink_linux.go [hunk 6]
```diff
@@ -143,52 +148,63 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
 // 10.0.0.10  scope host  src 10.0.0.10
 // Then cut the unique src IP fields,
 // --> result set: [10.0.0.1, 10.0.0.10]
-
-// If filterDev is specified, the result will discard route of specified device and cut src from other routes.
 func (h *netlinkHandle) GetLocalAddresses(dev, filterDev string) (sets.String, error) {
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/netlink_linux.go:151]: Given this is a big refactor for a (very) important function, any thoughts on adding some unit tests for it?

File: pkg/proxy/ipvs/netlink_linux.go [hunk 7]
```diff
@@ -143,52 +148,63 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
-		if err != nil {
-			return nil, fmt.Errorf("error get filter device %s, err: %v", filterDev, err)
+		if filterDev != "" {
+			return nil, fmt.Errorf("Invalid argument")
 		}
-		filterLinkIndex = link.Attrs().Index
+		return h.getLocalAddressesDev(dev)
+	}
+
+	if filterDev == "" {
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/netlink_linux.go:159]: It seems like empty filterDev was valid but now we're erroring here. Do you know if we never pass in empty filterDev here?

Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:159]: AFAIk this is only used in https://github.com/kubernetes/kubernetes/blob/e6922078577c5c8896b3619857dd744f1c1ecf6b/pkg/proxy/ipvs/proxier.go#L305-L324

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: I have now made the _really big_ refactoring that I wanted to do from the start. I do not like "combo" functions with clever use of parameters to make the function do different things. @andrewsykim IMHO your question proves my point.

@aojea Sorry, I have removed the big address comment again. It is no longer relevant.

**Comment by uablrek** [comment]
I have added the function commented in https://github.com/kubernetes/kubernetes/pull/103116#issuecomment-870334408 with unit-tests. This makes further code clean-ups possible. The address handling code is very messy with conversions back ans forth from strings to net.IP and from slices and sets.

File: pkg/proxy/ipvs/netlink_linux.go (hunk 6 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: Unit test existed but IMHO they mostly test the fake implementation. With the new implementation I have added unit-tests for the `IpIsValidForSet` function.

**Comment by uablrek** [comment]
I accidently pushed a merge commit. Sorry for the mess you other sig-folks :anguished:

**Comment by uablrek** [comment]
@ehashman Please remove the sig/node triage tag. I accidently pushed a merge commit and the robot added just every sig and area code in existence.

**Comment by uablrek** [comment]
I have to check some filtering functions so hold review for now.

File: pkg/proxy/ipvs/proxier_test.go [hunk 8]
```diff
@@ -34,6 +34,8 @@ import (
 	"k8s.io/apimachinery/pkg/util/intstr"
 	"k8s.io/apimachinery/pkg/util/sets"
 	utilfeature "k8s.io/apiserver/pkg/util/feature"
+
+	//utilproxy "k8s.io/kubernetes/pkg/proxy/util"
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier_test.go:38]: is this a leftover?

File: pkg/proxy/util/utils.go [hunk 9]
```diff
@@ -251,6 +251,29 @@ func GetNodeAddresses(cidrs []string, nw NetworkInterfacer) (sets.String, error)
 	return uniqueAddressList, nil
 }
 
+type IpSetValidator interface {
+	IpIsValidForSet(ip net.IP) bool
+}
+
+func AddressSet(validator IpSetValidator, addrs []net.Addr) sets.String {
```
Comment (aojea) [inline pkg/proxy/util/utils.go:258]: we should add a comment explaining what this function does

File: pkg/proxy/ipvs/netlink_linux.go [hunk 10]
```diff
@@ -123,72 +125,45 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
-		}
-		chosenLinkIndex = link.Attrs().Index
-	} else if filterDev != "" {
-		link, err := h.LinkByName(filterDev)
-		if err != nil {
-			return nil, fmt.Errorf("error get filter device %s, err: %v", filterDev, err)
-		}
-		filterLinkIndex = link.Attrs().Index
-	}
+type familyValidator struct {
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:128]: we should add the method just next instead at the end of the file
Also, add a statement for the compiler to check it matches the interface

```

Assuming the question is about Go, e.g.
```go
var _ util.IpSetValidator = familyValidator{}
```

**Review by aojea — CHANGES_REQUESTED** [review]

File: pkg/proxy/ipvs/proxier_test.go (hunk 8 above)
Comment (uablrek) [reply pkg/proxy/ipvs/proxier_test.go:38]: Yes. Fixed.

File: pkg/proxy/util/utils.go (hunk 9 above)
Comment (uablrek) [reply pkg/proxy/util/utils.go]: I re-worked the function. The validator is now a function, which is much better. I did not know that you can pass a method as a function in go (you can't do that in C++).

File: pkg/proxy/ipvs/netlink_linux.go (hunk 10 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: I re-worked the AddressSet() function, please see comment above.

**Comment by uablrek** [comment]
Please note; I re-worked the AddressSet() function. The validator is now a function not an interface.

File: pkg/proxy/ipvs/netlink_linux.go [hunk 11]
```diff
@@ -124,72 +126,41 @@ func (h *netlinkHandle) ListBindAddress(devName string) ([]string, error) {
...
-			continue
-		}
-		if h.isIPv6 {
-			if route.Dst.IP.To4() == nil && !route.Dst.IP.IsLinkLocalUnicast() {
-				res.Insert(route.Dst.IP.String())
-			}
-		} else if route.Src != nil {
-			res.Insert(route.Src.String())
-		}
+	if ip.IsLoopback() {
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:162]: should we mention in the comments that loopbacks are already excluded, it only mentions about ipv6 link-locals

File: pkg/proxy/ipvs/proxier_test.go [hunk 12]
```diff
@@ -430,12 +426,12 @@ func TestGetNodeIPs(t *testing.T) {
 		},
 		// case 8
 		{
-			devAddresses: map[string][]string{"kube-ipvs0": {"1.2.3.4", "2.3.4.5"}, "eth5": {"3.4.5.6"}, "lo": {"127.0.0.1"}},
+			devAddresses: map[string][]string{"kube-ipvs0": {"1.2.3.4", "2.3.4.5"}, "eth5": {"3.4.5.6"}},
 			expectIPs:    []string{"3.4.5.6"},
 		},
 		// case 9
 		{
-			devAddresses: map[string][]string{"ipvs0": {"1.2.3.4"}, "lo": {"127.0.0.1"}, "encap7": {"10.20.30.31"}},
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier_test.go:438]: why removing the loopbacks here, shouldn't those be excluded by the new methods `GetAllLocalAddresses()`?

File: pkg/proxy/ipvs/netlink_linux.go (hunk 11 above)
Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:162]: I mean in `pkg/proxy/ipvs/netlink.go`

File: pkg/proxy/ipvs/proxier_test.go (hunk 12 above)
Comment (uablrek) [reply pkg/proxy/ipvs/proxier_test.go:438]: Because the GetAllLocalAddresses() comes from the "fake" in testing/fake.go, and that does not filter loopback (code was moved). I could add filtering in "fake", but then I would like test the test-code.

Comment (uablrek) [reply pkg/proxy/ipvs/proxier_test.go:438]: But you are right. It is clearer to have it in the test-case if the mock procedure would change in the future. I'll restore it and add some ipv6 tests for good measure.

But I will not be able to do that today.

**Comment by uablrek** [comment]
@aojea I have problems with running the typecheck scripts locally;
```
kubernetes > ./hack/verify-typecheck-dockerless.sh
type-checking windows/arm64
type-checking linux/arm
type-checking windows/386
signal: killed
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
```
A re-run can help, but not always. Do you know the cause and some way to fix this?

File: pkg/proxy/ipvs/netlink_linux.go (hunk 11 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:162]: Updated

File: pkg/proxy/ipvs/netlink_linux.go [hunk 13]
```diff
@@ -21,8 +21,10 @@ package ipvs
 
 import (
 	"fmt"
+	"net"
 
 	"k8s.io/apimachinery/pkg/util/sets"
+	utilproxy "k8s.io/kubernetes/pkg/proxy/util"
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:27]: this seems the reasons that verify check breaks, since it doesn't compile in windows

> ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier_test.go:5429:9: undeclared name: netlinkHandle
> ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/vishvananda/netlink/xfrm.go:13:36: IPPROTO_ROUTING not declared by package unix
> ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/vishvananda/netlink/xfrm.go:14:36: IPPROTO_ESP not declared by package unix

File: pkg/proxy/ipvs/proxier_test.go [hunk 14]
```diff
@@ -27,6 +27,7 @@ import (
 	"time"
 
 	"github.com/stretchr/testify/assert"
+	"github.com/vishvananda/netlink"
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier_test.go:30]: this seems the reasons that verify check breaks, since it doesn't compile in windows

ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier_test.go:5429:9: undeclared name: netlinkHandle
ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/vishvananda/netlink/xfrm.go:13:36: IPPROTO_ROUTING not declared by package unix
ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/vishvananda/netlink/xfrm.go:14:36: IPPROTO_ESP not declared by package unix

**Comment by uablrek** [comment]
Squashed and force-pushed (finally!)

**Comment by thockin** [comment]
@uablrek did you make this commit with different email maybe?  Not sure why CLA is failing...

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
> @uablrek did you make this commit with different email maybe? Not sure why CLA is failing...

the sig-contrib? is rolling out the new EasyCLA, there was an announcement somewhere, I remember they mention there can be issues with some users

**Comment by uablrek** [comment]
I have commented it on slack https://kubernetes.slack.com/archives/C09R23FHP/p1636757607042000
And updated the feedback issue https://github.com/kubernetes/org/issues/3068#issuecomment-967802772

The merge should work anyway I am told. This seem to be a test that it's working. However there doesn't seem to be any fixing going on when it doesn't work, as for me and some others.
