### PR TITLE
Fix federated config map unit tests

### LINKED ISSUE #41419: TestConfigMapController test flake
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41412/pull-kubernetes-unit/17829/#k8siokubernetesfederationpkgfederation-controllerconfigmap-testconfigmapcontroller

```
panic: interface conversion: interface is nil, not *v1.ConfigMap
/usr/local/go/src/runtime/panic.go:500 +0x1ae
/usr/local/go/src/testing/testing.go:579 +0x474
/usr/local/go/src/runtime/panic.go:458 +0x271
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/configmap/configmap_controller_test.go:158 +0x74
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/configmap/configmap_controller_test.go:140 +0x1d8b
/usr/local/go/src/testing/testing.go:610 +0xca
/usr/local/go/src/testing/testing.go:646 +0x530
```

### PR DESCRIPTION
**Pull request by mwielgus**
Fixes #41419 and #42847 and possibly other issues in this area.

cc: @nikhiljindal @csbell @perotinus

### CODE REVIEW

File: federation/pkg/federation-controller/configmap/configmap_controller.go [hunk 1]
```diff
@@ -325,6 +325,13 @@ func (configmapcontroller *ConfigMapController) reconcileConfigMap(configmap typ
 	}
 	baseConfigMap := baseConfigMapObj.(*apiv1.ConfigMap)
 
+	obj, err := api.Scheme.DeepCopy(baseConfigMapObj)
+	baseConfigMap, ok := obj.(*apiv1.ConfigMap)
```
Comment (perotinus) [inline federation/pkg/federation-controller/configmap/configmap_controller.go]: Can you rename this to configMap?

It's not the baseConfigMap anymore.

File: federation/pkg/federation-controller/configmap/configmap_controller_test.go [hunk 2]
```diff
@@ -143,11 +143,18 @@ func TestConfigMapController(t *testing.T) {
 	}
 
 	configmapWatch.Modify(configmap1)
-	updatedConfigMap = GetConfigMapFromChan(cluster1UpdateChan)
-	assert.NotNil(t, updatedConfigMap)
-	assert.Equal(t, configmap1.Name, updatedConfigMap.Name)
-	assert.Equal(t, configmap1.Namespace, updatedConfigMap.Namespace)
-	assert.True(t, util.ConfigMapEquivalent(configmap1, updatedConfigMap))
+	for {
```
Comment (perotinus) [inline federation/pkg/federation-controller/configmap/configmap_controller_test.go]: This fix irks me, because it seems like the occasional double delivery should not be happening.

That said, it seems not worth the effort to fix this for real in light of upcoming work to refactor the federation controllers to use a common framework.

**Comment by nikhiljindal** [comment]
@perotinus's review should be enough since he has been looking at this code closely.
Will add the LGTM label (or @mwielgus feel free to add label) once he LGTMs.

File: federation/pkg/federation-controller/configmap/configmap_controller_test.go (hunk 2 above)
Comment (mwielgus) [inline federation/pkg/federation-controller/configmap/configmap_controller_test.go]: It happens because we are running controller with greatly reduced delay time. It is possible that the change doesn't get through the async mock transport layer before the config map is  processed again. We could probably rethink the mocks but double delivery in this type of integration test with reduced delays will still be possible.

File: federation/pkg/federation-controller/configmap/configmap_controller.go (hunk 1 above)
Comment (mwielgus) [inline federation/pkg/federation-controller/configmap/configmap_controller.go]: done

File: federation/pkg/federation-controller/configmap/configmap_controller_test.go (hunk 2 above)
Comment (perotinus) [inline federation/pkg/federation-controller/configmap/configmap_controller_test.go]: That's reasonable. It still seems like this is an issue that could happen in the real world, but I suppose that's OK because it's still eventually consistent.
