### PR TITLE
pkg/util/flock: Fix the flock so it actually locks.

### LINKED ISSUE #42929: pkg/util/flock.Acquire() doesn't guarantee mutual exclusion
**BUG REPORT**:

**Kubernetes version latest master**:

**Environment**:
- **Ubuntu 16.04 LTS, Linux 4.2.0-42-generic**:

**What happened**:
The `flock.Acquire()` doesn't provide mutual exclusion. Two processes can both grab the same flock at the same time.

**What you expected to happen**:
Only one process should be able to grab the flock.

**How to reproduce it** (as minimally and precisely as possible):

```shell
cat testflock.go
package main

import (
	"fmt"
	"time"

	"k8s.io/kubernetes/pkg/util/flock"
)

func main() {
	if err := flock.Acquire("/tmp/foo.lock"); err != nil {
		fmt.Println("error:", err)
		return
	}

	fmt.Println("acquired")

	time.Sleep(time.Hour)
}

go build testflock.go; ./testflock
acquired

# open another terminal and run
./testflock
acquired
```

**Anything else we need to know**:

Although the flock doesn't work, the [watchForLockfileContention()](https://github.com/kubernetes/kubernetes/blob/v1.7.0-alpha.0/cmd/kubelet/app/server.go#L324) does work. Since we _usually_ specify `--exit-on-lock-contention` together with `--lock-file`, so the 1st process will exit anyway.
However we still need to fix the flock..

### PR DESCRIPTION
**Pull request by yifan-gu**
With this PR, the second call to `Acquire()` will block unless the lock is released (process exits).
Also removed the memory mutex in the previous code since we don't need `Release()` here so no need to save and protect the local fd.

Fix #42929.

### CODE REVIEW

**Comment by yifan-gu** [comment]
cc @mikedanese

File: pkg/util/flock/flock_unix.go [hunk 1]
```diff
@@ -18,34 +18,18 @@ limitations under the License.
 
 package flock
 
-import (
-	"os"
-	"sync"
-
-	"golang.org/x/sys/unix"
```
Comment (k82cn) [inline pkg/util/flock/flock_unix.go]: `./hack/update-bazel.sh` for import changes.

**Comment by yifan-gu** [comment]
Bazel updated.

**Comment by mikedanese** [comment]
Was the fd previously being close? Why does this work and the other way doesn't?

**Comment by yifan-gu** [comment]
> Was the fd previously being close? Why does this work and the other way doesn't?

Yes that's the reason.

**Comment by yifan-gu** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by yifan-gu** [comment]
@mikedanese Are we gonna get this in for the release? It's a bug fix.

**Review by mikedanese — APPROVED** [review]

File: pkg/util/flock/flock_unix.go (hunk 1 above)
Comment (yifan-gu) [inline pkg/util/flock/flock_unix.go]: fixed
