### PR TITLE
[test] statefulset controller: fix requests tracker concurrency

### LINKED ISSUE #124526: Flaky UT TestStatefulSetControl/CreatePodFailure/Burst/ScaleDownOnly/StatefulSetAutoDeletePVCEnabled
### Which jobs are flaking?

https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

### Which tests are flaking?

TestStatefulSetControl/CreatePodFailure/Burst/ScaleDownOnly/StatefulSetAutoDeletePVCEnabled of pkg/controller/statefulset/stateful_set_control_test.go

### Since when has it been flaking?

Have started observing more flakes recently since last week.

### Testgrid link

https://testgrid.k8s.io/ibm-k8s-unit-tests-ppc64le#periodic-k8s-unit-tests-ppc64le

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

Able to reproduce using stress tool.
```
[root@maxwells1 kubernetes]# /root/go/bin/stress ./statefulset.test -test.run TestStatefulSetControl/CreatePodFailure/Burst/ScaleDownOnly/StatefulSetAutoDeletePVCEnabled
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
--------
--------
--------
8m25s: 108 runs so far, 0 failures
8m30s: 110 runs so far, 0 failures

/tmp/go-stress-20240425T015624-1279903570
--- FAIL: TestStatefulSetControl (0.16s)
    --- FAIL: TestStatefulSetControl/CreatePodFailure/Burst/ScaleDownOnly/StatefulSetAutoDeletePVCEnabled (0.08s)
        stateful_set_control_test.go:526: StatefulSetControl did not return InternalError, found %!s(<nil>)
E0425 02:04:54.791294 2073044 stateful_set.go:374] "Unhandled Error" err="user error: more than one StatefulSet is selecting pods with labels: map[apps.kubernetes.io/pod-index:0 foo:bar statefulset.kubernetes.io/pod-name:foo-0]. Sets: [foo foo2]" logger="UnhandledError"
E0425 02:04:54.803356 2073044 stateful_set.go:374] "Unhandled Error" err="user error: more than one StatefulSet is selecting pods with labels: map[apps.kubernetes.io/pod-index:0 foo:bar statefulset.kubernetes.io/pod-name:foo-0]. Sets: [foo foo2]" logger="UnhandledError"
E0425 02:04:54.806908 2073044 stateful_set.go:374] "Unhandled Error" err="user error: more than one StatefulSet is selecting pods with labels: map[apps.kubernetes.io/pod-index:0 foo:bar statefulset.kubernetes.io/pod-name:foo-0]. Sets: [foo foo2]" logger="UnhandledError"
E0425 02:04:54.814283 2073044 stateful_set.go:374] "Unhandled Error" err="user error: more than one StatefulSet is selecting pods with labels: map[apps.kubernetes.io/pod-index:0 foo:bar statefulset.kubernetes.io/pod-name:foo-0]. Sets: [foo foo2]" logger="UnhandledError"
FAIL


ERROR: exit status 1

8m35s: 112 runs so far, 1 failures (0.89%)
```

### Relevant SIG(s)

/sig testing
/sig apps

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

fixes a flake when using Parallel PodManagementPolicy (burst) in StatefulSets

#### Which issue(s) this PR fixes:

Fixes #124526

#### Special notes for your reviewer:

tested with the stress tool

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ingvagabund** [comment]
Can you more elaborate on why the current implementation does not work as expected? I.e. what's the underlying cause that makes the test flake? And what has changed and how it removes the flakiness?

**Comment by atiratree** [comment]
We set ecpected failure here after 2 requests: 

https://github.com/kubernetes/kubernetes/blob/0590bb1ac495ae8af2a573f879408e48800da2c5/pkg/controller/statefulset/stateful_set_control_test.go#L523

Then we scale up the replica set in parallel (Burst).

https://github.com/kubernetes/kubernetes/blob/0590bb1ac495ae8af2a573f879408e48800da2c5/pkg/controller/statefulset/stateful_set_control_test.go#L525

Then the pod tracker is called. 

https://github.com/kubernetes/kubernetes/blob/0590bb1ac495ae8af2a573f879408e48800da2c5/pkg/controller/statefulset/stateful_set_control_test.go#L2516

Each tracker method is thread safe but they are not thread safe together. This is the reason behind the flake.

So we fix that by locking the increment and error checking with a single lock.

---

Also we have the parallel requests checking which is independent and used in TestParallelScale test.

https://github.com/kubernetes/kubernetes/blob/0590bb1ac495ae8af2a573f879408e48800da2c5/pkg/controller/statefulset/stateful_set_control_test.go#L2946

This was guarded by a lock before and maxParallel was always equal to the number of requests. So it didn't test the parallelness correctly and had to be fixed as well.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 1]
```diff
@@ -2423,51 +2423,48 @@ type requestTracker struct {
...
+func (rt *requestTracker) incWithOptionalError() error {
 	rt.Lock()
 	defer rt.Unlock()
-	return rt.err
+	rt.requests++
+	if rt.err != nil && rt.requests >= rt.after {
+		// reset and pass the error
+		defer func() {
+			rt.err = nil
+			rt.after = 0
```
Comment (ingvagabund) [inline pkg/controller/statefulset/stateful_set_control_test.go:2463]: `reset()` originally set rt.delay = 0. Why not do the same here for `rt.parallelRequestDelay`?

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 2]
```diff
@@ -2945,47 +2938,52 @@ func fakeResourceVersion(object interface{}) {
 
 func TestParallelScale(t *testing.T) {
 	for _, tc := range []struct {
-		desc            string
-		replicas        int32
-		desiredReplicas int32
+		desc                        string
+		replicas                    int32
+		desiredReplicas             int32
+		expectedMinParallelRequests int
```
Comment (ingvagabund) [inline pkg/controller/statefulset/stateful_set_control_test.go:2944]: `expectedMinParallelRequests` is a new field? Why the original `1` is not enough?

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 3]
```diff
@@ -3017,8 +3015,8 @@ func parallelScale(t *testing.T, set *apps.StatefulSet, replicas, desiredReplica
 		t.Errorf("Failed to scale statefulset to %v replicas, got %v replicas", desiredReplicas, set.Status.Replicas)
 	}
 
-	if (diff < -1 || diff > 1) && om.createPodTracker.maxParallel <= 1 {
-		t.Errorf("want max parallel requests > 1, got %v", om.createPodTracker.maxParallel)
+	if om.createPodTracker.maxParallelRequests < expectedMinParallelRequests {
```
Comment (ingvagabund) [inline pkg/controller/statefulset/stateful_set_control_test.go:3018]: Why is `(diff < -1 || diff > 1)` no longer tested?

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 4]
```diff
@@ -2423,51 +2423,48 @@ type requestTracker struct {
...
+	}
+	// increase the chance of collisions
+	if rt.parallelRequestDelay != 0 {
+		time.Sleep(rt.parallelRequestDelay)
 	}
 }
 
-func (rt *requestTracker) reset() {
-	rt.parallelLock.Lock()
-	rt.parallel = 0
```
Comment (ingvagabund) [inline pkg/controller/statefulset/stateful_set_control_test.go:2457]: Turning into `rt.parallelRequests`. So from now on `rt.parallelRequests` is never reset. So originally `rt.parallel` was counting the number of requests in parallel until an error was ready. Followed by resting it. Why is it no longer needed to reset it?

**Comment by ingvagabund** [comment]
Worth mentioning:
- with `trackParallelRequests` locking the parallel requests/routines are serialized which makes the testing less real (some of the state space is not explored).
- removing reset of both delay and parallel fields is ok since they execution path does not generate the error so the reset code is actually never executed -> safe to remove the code resetting both fields

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 1 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control_test.go:2469]: As mentioned in https://github.com/kubernetes/kubernetes/pull/124624#issuecomment-2098186385 
this reset was never used before, because errors and parallel requests have not been tested at the same time before.

Logic of these two blocks `trackParallelRequests` and `incWithOptionalError` is independent of each other, so I think it makes sense to keep them separate.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 4 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control_test.go:2457]: https://github.com/kubernetes/kubernetes/pull/124624#discussion_r1592923857

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 2 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control_test.go:2949]: I have moved this refactoring to a new commit: https://github.com/kubernetes/kubernetes/pull/124624/commits/7b725f3bfcc0eb88a75f91f523e7b669213321ef.

This is to make the test more accurate as originally we expected only 2 parallel requests. But if we create a 1000 pods we should expect more, otherwise it would suggest a regression.

**Comment by atiratree** [comment]
> with trackParallelRequests locking the parallel requests/routines are serialized which makes the testing less real (some of the state space is not explored).

I have solved this by requiring the enablement for the tracking

https://github.com/kubernetes/kubernetes/pull/124624/files#diff-49263a54d6a7753728e489881537462578ddc2b9b09404ee335c73e27e178ddcR2436-R2438

so it should not affect the other tests now, apart from the `TestParallelScale`

---

I have also added a check for the expectedMinParallelRequests values.

https://github.com/kubernetes/kubernetes/pull/124624/files#diff-49263a54d6a7753728e489881537462578ddc2b9b09404ee335c73e27e178ddcR2990-R2994
