### PR TITLE
the component status health check should check whether the scheme of backend storage url is https or not

### LINKED ISSUE #23897: getServersToValidate does not respect the scheme
I met a problem today when trying to get component statues.

```
NAME                 STATUS      MESSAGE                                                                                    ERROR
etcd-0               Unhealthy   Get http://10.65.244.200:4001/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
controller-manager   Healthy     ok
scheduler            Healthy     ok
```

It is a little bit strange, since the `http://10.65.244.200:4001/health` should be `https://10.65.244.200:4001/health` actually (notice the scheme change). 

Then I found the related code here: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L495-L516

```go
for ix, machine := range c.StorageDestinations.Backends() {
	glog.V(2).Infof("etcd debug: check the backend: %d: %s", ix, machine)
	etcdUrl, err := url.Parse(machine)
	if err != nil {
		glog.Errorf("Failed to parse etcd url for validation: %v", err)
		continue
	}
	var port int
	var addr string
	if strings.Contains(etcdUrl.Host, ":") {
		var portString string
		addr, portString, err = net.SplitHostPort(etcdUrl.Host)
		if err != nil {
			glog.Errorf("Failed to split host/port: %s (%v)", etcdUrl.Host, err)
			continue
		}
		port, _ = strconv.Atoi(portString)
		glog.V(2).Infof("etcd debug: addr: %s, port: %d", addr, port)
	} else {
		addr = etcdUrl.Host
		port = 4001
	}
	// TODO: etcd health checking should be abstracted in the storage tier
	serversToValidate[fmt.Sprintf("etcd-%d", ix)] = apiserver.Server{Addr: addr, Port: port, Path: "/health", Validate: etcdutil.EtcdHealthCheck}
}
```

And the check code is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/validator.go#L55-L76

```go
func (server *Server) DoServerCheck(prober httpprober.HTTPProber) (probe.Result, string, error) {
	scheme := "http"
	if server.EnableHTTPS {
		scheme = "https"
	}
	url := utilnet.FormatURL(scheme, server.Addr, server.Port, server.Path)

	result, data, err := prober.Probe(url, nil, probeTimeOut)

	if err != nil {
		return probe.Unknown, "", err
	}
	if result == probe.Failure {
		return probe.Failure, string(data), err
	}
	if server.Validate != nil {
		if err := server.Validate([]byte(data)); err != nil {
			return probe.Failure, string(data), err
		}
	}
	return result, string(data), nil
}
```

It looks like there is an option to setup the `EnableHTTPS` attribute, but we do not set up it correctly.

### PR DESCRIPTION
**Pull request by zhouhaibing089**
fix https://github.com/kubernetes/kubernetes/issues/23897, when querying the component status of etcd (backend storage), the scheme of url is not checked and use `http` always, this commit aims to fix this.

### CODE REVIEW

File: pkg/master/master.go [hunk 1]
```diff
@@ -513,7 +513,7 @@ func (m *Master) getServersToValidate(c *Config) map[string]apiserver.Server {
 			port = 4001
 		}
 		// TODO: etcd health checking should be abstracted in the storage tier
-		serversToValidate[fmt.Sprintf("etcd-%d", ix)] = apiserver.Server{Addr: addr, Port: port, Path: "/health", Validate: etcdutil.EtcdHealthCheck}
+		serversToValidate[fmt.Sprintf("etcd-%d", ix)] = apiserver.Server{Addr: addr, EnableHTTPS: etcdUrl.Scheme == "https", Port: port, Path: "/health", Validate: etcdutil.EtcdHealthCheck}
```
Comment (lavalamp) [inline pkg/master/master.go]: nit: can you break out onto multiple lines? Thanks.

**Comment by lavalamp** [comment]
ok to test

**Comment by lavalamp** [comment]
Thanks-- just a style nit.

**Comment by zhouhaibing089** [comment]
@lavalamp updated, :)

File: pkg/master/master.go [hunk 2]
```diff
@@ -513,7 +513,12 @@ func (m *Master) getServersToValidate(c *Config) map[string]apiserver.Server {
 			port = 4001
 		}
 		// TODO: etcd health checking should be abstracted in the storage tier
-		serversToValidate[fmt.Sprintf("etcd-%d", ix)] = apiserver.Server{Addr: addr, Port: port, Path: "/health", Validate: etcdutil.EtcdHealthCheck}
+		serversToValidate[fmt.Sprintf("etcd-%d", ix)] = apiserver.Server{
+			Addr:        addr,
+			EnableHTTPS: etcdUrl.Scheme == "https",
+			Port:        port,
+			Path:        "/health",
+			Validate:    etcdutil.EtcdHealthCheck}
```
Comment (lavalamp) [inline pkg/master/master.go]: A tiny nit, but these look better if you end with a new line, e.g.

```
  blah: blah,
}
```

I'll LGTM anyway, since it is done this way elsewhere. Please update if you see this before the merge queue merges, though :) :)

**Comment by lavalamp** [comment]
LGTM thank you!!

**Comment by zhouhaibing089** [comment]
@lavalamp hi, it looks like a flake, though I can not tell which kind of flake, please help to trigger a retest(not int the whitelist).

**Comment by lavalamp** [comment]
@k8s-bot test this issue #24161
