### PR TITLE
 Speed up block volume e2e test by checking events 

### LINKED ISSUE #71748: e2e storage testsuites: avoid timeout in "volumeMode should fail in binding dynamic provisioned PV to PVC"
**What would you like to be added**:

Here's how the test is written at the moment:
https://github.com/kubernetes/kubernetes/blob/e689d515f77cda51898045d626ec4070e3328194/test/e2e/storage/testsuites/volumemode.go#L329-L330

During a normal test run, this `framework.WaitForPersistentVolumeClaimPhase` will run for five minutes and then time out. The timeout error then is considered a test success.

Instead, the test should wait for the expected error condition and fail if that isn't reached within the timeout period.

**Why is this needed**:

Faster test execution, more precise testing (no false positives when the operation fails for some other reason).

/kind feature

/sig storage
/cc @mkimuram

### PR DESCRIPTION
**Pull request by mkimuram**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Block volume e2e tests for unsupported plugins take much time (more than 5 minutes), which makes total time of executing e2e tests too long. This PR speeds up the tests by checking events.

**Which issue(s) this PR fixes**:
Fixes #71748

**Special notes for your reviewer**:
/sig storage
/cc @pohly @msau42 

As @jsafrane found out the approach that "Events only speed up the test, we still check the pod is not scheduled if all events are lost." in #79796, this PR is applying the approach to existing block volume e2e tests.

In most cases, this PR will save:
 - about 3 minutes(PodStartTimeout - "time to FailedBinding") for "should fail to create pod by failing to mount volume [Slow]" 
 - about 5 minutes(ClaimProvisionTimeout) for "should fail in binding dynamic provisioned PV to PVC [Slow]" 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by mkimuram** [comment]
/hold
Wait until #79796 to be merged to save @jsafrane 's time.

**Comment by mkimuram** [comment]
/hold cancel

@jsafrane 

Rebased to resolve conflicts from #79796. PTAL

**Comment by mkimuram** [comment]
For test approval:
/assign @neolit123

This PR renames `WaitTimeoutForPodEvent` to `WaitTimeoutForEvent` and move it back to e2e/framework from e2e/common so that it can be used for volume event. (See https://github.com/kubernetes/kubernetes/pull/77526)

Could you review and approve this PR?

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -786,6 +786,27 @@ func WaitForPersistentVolumeClaimsPhase(phase v1.PersistentVolumeClaimPhase, c c
 	return fmt.Errorf("PersistentVolumeClaims %v not all in phase %s within %v", pvcNames, phase, timeout)
 }
 
+// WaitTimeoutForEvent waits the given timeout duration for an event to occur.
+func WaitTimeoutForEvent(c clientset.Interface, namespace, eventSelector, msg string, timeout time.Duration) error {
```
Comment (neolit123) [inline test/e2e/framework/util.go]: i don't think we should be moving functions back into util.go, client based utilities should live in sub-packages and famework/wait is a good one. there is ongoing work to potentially only have essentials in util.go.

**Comment by neolit123** [comment]
FYI this package `test/e2e/common/` is owned by SIG Node and i'm not in the owners there. only for `test/e2e/framework`

File: test/e2e/framework/util.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/framework/util.go]: if you think the utility is not fine to be in framework/pod, can it be in a different sub-package?

Comment (mkimuram) [reply test/e2e/framework/util.go]: @neolit123 

Thank you for your comment. 
Are you suggesting to move it from `framework/pod` to something like `framework/event`?

This PR is trying to use it for a volume event, not for a pod event.
(Actually, we can use it as is, but the name is confusing, so I'm renaming and moving it.)

File: test/e2e/storage/testsuites/volumemode.go [hunk 2]
```diff
@@ -196,13 +196,33 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
...
-					nil, framework.NodeSelection{Name: l.config.ClientNodeName}, framework.PodStartTimeout)
+				pod := framework.MakeSecPod(l.ns.Name, []*v1.PersistentVolumeClaim{l.pvc}, nil, false, "", false, false, framework.SELinuxLabel, nil)
+				// Setting node
+				pod.Spec.NodeName = l.config.ClientNodeName
+				pod, err = l.cs.CoreV1().Pods(l.ns.Name).Create(pod)
 				defer func() {
 					framework.ExpectNoError(framework.DeletePodWithWait(f, l.cs, pod))
 				}()
-				framework.ExpectError(err)
+				framework.ExpectNoError(err)
```
Comment (neolit123) [inline test/e2e/storage/testsuites/volumemode.go]: should have an annotation (e.g. Failed to create...)

File: test/e2e/framework/util.go [hunk 3]
```diff
@@ -786,6 +786,27 @@ func WaitForPersistentVolumeClaimsPhase(phase v1.PersistentVolumeClaimPhase, c c
...
+	return wait.PollImmediate(Poll, timeout, eventOccurred(c, namespace, eventSelector, msg))
+}
+
+func eventOccurred(c clientset.Interface, namespace, eventSelector, msg string) wait.ConditionFunc {
+	options := metav1.ListOptions{FieldSelector: eventSelector}
+	return func() (bool, error) {
+		events, err := c.CoreV1().Events(namespace).List(options)
+		if err != nil {
+			return false, fmt.Errorf("got error while getting events: %s", err)
```
Comment (neolit123) [inline test/e2e/framework/util.go]: %v

File: test/e2e/framework/util.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/framework/util.go]: `framework/event` makes sense to me.
it can hold `v1.Event*` related utils.

we seem to have some of these under util.go already.

/cc @oomichi 
WDYT?

Comment (mkimuram) [reply test/e2e/framework/util.go]: Moved to `common/events.go`
Adding sig node for review this part. 

/sig node

@Random-Liu @dchen1107 Could you review this PR?

File: test/e2e/storage/testsuites/volumemode.go (hunk 2 above)
Comment (mkimuram) [reply test/e2e/storage/testsuites/volumemode.go]: Fixed all in volumemode.go

File: test/e2e/framework/util.go (hunk 3 above)
Comment (mkimuram) [reply test/e2e/framework/util.go]: Fixed as suggested.

File: test/e2e/framework/util.go (hunk 1 above)
Comment (oomichi) [reply test/e2e/framework/util.go]: I think current PR way(`common/events.go`) is good for me, because the function is used for the test only.

File: test/e2e/storage/testsuites/volumemode.go [hunk 4]
```diff
@@ -182,27 +183,47 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
...
+				pod := framework.MakeSecPod(l.ns.Name, []*v1.PersistentVolumeClaim{l.pvc}, nil, false, "", false, false, framework.SELinuxLabel, nil)
+				// Setting node
+				pod.Spec.NodeName = l.config.ClientNodeName
+				pod, err = l.cs.CoreV1().Pods(l.ns.Name).Create(pod)
 				defer func() {
-					framework.ExpectNoError(framework.DeletePodWithWait(f, l.cs, pod))
+					framework.ExpectNoError(framework.DeletePodWithWait(f, l.cs, pod), "Failed to delete pod")
 				}()
-				framework.ExpectError(err)
+				framework.ExpectNoError(err, "Failed to create pod")
```
Comment (oomichi) [inline test/e2e/storage/testsuites/volumemode.go]: If an error happens here, I guess the above `defer func() {` causes another error because of nonexistent pod.

**Review by oomichi — COMMENTED** [review]
Most part is good for me, just one comment for a corner case.

File: test/e2e/framework/util.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/framework/util.go]: ok, moving the utility out of the framework SGTM too.

File: test/e2e/storage/testsuites/volumemode.go (hunk 4 above)
Comment (mkimuram) [reply test/e2e/storage/testsuites/volumemode.go]: @oomichi

Thank you for your review.

`DeletePodWithWait` handles `pod == nil` case properly, so no additional error will happen.
However, I've moved `ExpectNoError` before `defer` for readability, in the second commit.

PTAL

(BTW, original code was intentionaly implemented with that order, because it expects such a case that pod creation succeeds but it doesn't become running state, where pod needs to be deleted. By this PR, we won't need to care about it, for we check them separatedly.)

**Review by oomichi — COMMENTED** [review]
@mkimuram  Thanks for your explanation and updating.

/approve
