### PR TITLE
Revert dockershim CRI v1 changes

### LINKED ISSUE #106798: dockershim.sock in 1.23 only supports v1 of CRI and tools dependent on v1alpha2 will not work
### What happened?

With this change: https://github.com/kubernetes/kubernetes/pull/106501 the version of CRI API that `dockershim.sock` exposes is `v1` (as oppose to `v1alpha2` it used to be). So tools that takes dependency on dockershim.sock will fail with:

```
rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.ImageServicepanic
```

/sig node
/priority critical-urgent

### What did you expect to happen?

v1alpha2 is exposed as before. Especially given that we only have a single release left where dockershim will present

### How can we reproduce it (as minimally and precisely as possible)?

For example, this program will fail on 1.23

``` go
package main

import (
	"context"
	"fmt"

	runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1alpha2"

	"google.golang.org/grpc"
)

const (
    addr = "unix:///var/run/dockershim.sock"
)

func main() {
    ctx := context.Background()
    newclient, err := NewImageService()
    if err != nil {
        fmt.Printf("error with client: %v", err)
    }
    images, err := newclient.ListImages(ctx, &runtimeapi.ListImagesRequest{})
    if err != nil {
        fmt.Printf("error getting images: %v", err)
    }
    for _, img := range images.Images {
        fmt.Println(img.RepoTags)
    }

}

func NewImageService() (runtimeapi.ImageServiceClient, error) {
    conn, err := grpc.Dial(addr, grpc.WithInsecure())
    return runtimeapi.NewImageServiceClient(conn), err
}
```

### Anything else we need to know?

_No response_

### Kubernetes version

1.23

### Cloud provider

any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:
We should not touch the dockershim ahead of removal and therefore default to `v1alpha2` CRI instead of `v1`.

Partially reverts changes from https://github.com/kubernetes/kubernetes/pull/106501

#### Which issue(s) this PR fixes:

Fixes #106798

#### Special notes for your reviewer:
Needs a cherry-pick for `release-1.23`.
#### Does this PR introduce a user-facing change?

```release-note
Fixes 1.23 regression to revert the CRI API version surfaced by dockershim to v1alpha2
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by liggitt** [comment]
should we add something like the testcase in the description in https://github.com/kubernetes/kubernetes/issues/106798, or do the modified unit tests cover that scenario?

**Comment by saschagrunert** [comment]
> should we add something like the testcase in the description in #106798, or do the modified unit tests cover that scenario?

Added a unit test in `pkg/kubelet/dockershim/remote/docker_server_test.go`.

**Comment by saschagrunert** [comment]
Since this is kinda urgent, let me apply the milestone:
/milestone v1.23

**Comment by liggitt** [comment]
/hold
would like to make sure docker e2e jobs pass first

File: pkg/kubelet/dockershim/docker_streaming.go [hunk 1]
```diff
@@ -123,7 +125,12 @@ func (ds *dockerService) Exec(_ context.Context, req *runtimeapi.ExecRequest) (*
 	if err != nil {
 		return nil, err
 	}
-	return ds.streamingServer.GetExec(req)
+	r := (*runtimeapiv1.ExecRequest)(unsafe.Pointer(req))
```
Comment (liggitt) [inline pkg/kubelet/dockershim/docker_streaming.go:128]: these are a copy/paste of the conversions in pkg/kubelet/cri/remote/conversion.go, right?

I don't love that these are disconnected from those unit tests, but I guess this is only until master reopens for 1.24

should we export those conversion methods from pkg/kubelet/cri/remote/conversion.go and use them here, or at least add comments to those conversion methods that if they have to change, these have to change as well?

Comment (SergeyKanzhelev) [reply pkg/kubelet/dockershim/docker_streaming.go:128]: Since 1.23 will potentially be longer time supported version (at least by vendors) as the last one with dockershim, we will benefit from tests here. Maybe if this is too much change now we can bring them later?

Comment (saschagrunert) [reply pkg/kubelet/dockershim/docker_streaming.go:128]: Yeah just copy pasted. I’d prefer not making the conversions Public because both (dockershim and v1alpha2) should be removed in the future.

I could follow-up on the tests since I’m running out of time for today, or add them Monday morning my time.

Comment (liggitt) [reply pkg/kubelet/dockershim/docker_streaming.go:128]: I'd be ok with either exporting the conversion methods that are already tested and using them here, or commenting in the conversion methods that this code needs to be adjusted if the conversion is adjusted

Comment (liggitt) [reply pkg/kubelet/dockershim/docker_streaming.go:128]: the comment seems fine, given the lifetime of this code is ~1 week in master

Comment (saschagrunert) [reply pkg/kubelet/dockershim/docker_streaming.go:128]: Adding the comment in the next minutes.

Comment (saschagrunert) [reply pkg/kubelet/dockershim/docker_streaming.go:130]: Added the comments on both sides of the implementation.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
lgtm once the docker e2e jobs pass showing exec/attach/portforward calls succeed

**Comment by saschagrunert** [comment]
Test timed out.
/test pull-kubernetes-e2e-gce

**Comment by ehashman** [comment]
Hmm, e2e test really doesn't look happy still :\

**Comment by liggitt** [comment]
at least https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106803/pull-kubernetes-e2e-gce-ubuntu/1466840849231908864/ passed

**Comment by liggitt** [comment]
last time https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce ran was 11/18 ... so it's entirely possible something else turned it red since then :-/

**Comment by saschagrunert** [comment]
Green :) 

/remove-hold

As @ligitt mentioned earlier.

**Comment by saschagrunert** [comment]
Preparing the CP
