### PR TITLE
Retry github and godep operations in test-dockerized.sh

### LINKED ISSUE #21887: Cloning godeps fails before integration tests
Not sure if this concided with a Jenkins restart. 
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21856/kubernetes-pull-test-unit-integration/15944/?debugUI=CLOUD
```
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': gnutls_handshake() failed: Error in the pull function.
package github.com/tools/godep: exit status 128
Build step 'Execute shell' marked build as failure
Recording test results
```

### PR DESCRIPTION
**Pull request by fejta**
closes #21887.

Attempt to mitigate go get and godep flakes by retrying a few times inside of jenkins

### CODE REVIEW

File: hack/jenkins/test-dockerized.sh [hunk 1]
```diff
@@ -19,6 +19,13 @@ set -o nounset
 set -o pipefail
 set -o xtrace
 
+function _retry {
```
Comment (ixdy) [inline hack/jenkins/test-dockerized.sh]: minor nit: I don't think we use underscore-prefixed function names anywhere else in the repo. is there something you're worried about shadowing?

Comment (fejta) [inline hack/jenkins/test-dockerized.sh]: Okay I'll just use retry

File: hack/jenkins/test-dockerized.sh [hunk 2]
```diff
@@ -44,7 +51,7 @@ export LOG_LEVEL=4
 cd /go/src/k8s.io/kubernetes
 
 ./hack/build-go.sh
-godep go install ./...
+retry godep go install ./...
```
Comment (ixdy) [inline hack/jenkins/test-dockerized.sh]: has this one actually failed on downloading dependencies? I worry that this will end up retrying a broken build 5 times.

**Comment by ixdy** [comment]
LGTM, but maybe squash?
