### PR TITLE
fix kubeproxy e2e

### LINKED ISSUE #14342: kubeproxy e2e test is flaky
```
STEP: Hit Test with Fewer Endpoints
STEP: Hitting endpoints from host and container
STEP: dialing(udp) endpointPodIP:endpointUdpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do echo 'hostName' | nc -w 2 -u 10.245.3.24 8081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) endpointPodIP:endpointHttpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do curl -s --connect-timeout 2 http://10.245.3.24:8080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) endpointPodIP:endpointUdpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.245.3.24&port=8081&tries=1'
STEP: dialing(http) endpointPodIP:endpointHttpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.245.3.24&port=8080&tries=1'
STEP: dialing(udp) endpointPodIP:endpointUdpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do echo 'hostName' | nc -w 2 -u 10.245.1.23 8081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) endpointPodIP:endpointHttpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do curl -s --connect-timeout 2 http://10.245.1.23:8080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) endpointPodIP:endpointUdpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.245.1.23&port=8081&tries=1'
STEP: dialing(http) endpointPodIP:endpointHttpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.245.1.23&port=8080&tries=1'
STEP: dialing(udp) endpointPodIP:endpointUdpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do echo 'hostName' | nc -w 2 -u 10.245.4.25 8081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) endpointPodIP:endpointHttpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do curl -s --connect-timeout 2 http://10.245.4.25:8080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) endpointPodIP:endpointUdpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.245.4.25&port=8081&tries=1'
STEP: dialing(http) endpointPodIP:endpointHttpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.245.4.25&port=8080&tries=1'
STEP: dialing(udp) endpointPodIP:endpointUdpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do echo 'hostName' | nc -w 2 -u 10.245.2.25 8081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) endpointPodIP:endpointHttpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do curl -s --connect-timeout 2 http://10.245.2.25:8080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) endpointPodIP:endpointUdpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.245.2.25&port=8081&tries=1'
STEP: dialing(http) endpointPodIP:endpointHttpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.245.2.25&port=8080&tries=1'
STEP: dialing(udp) endpointPodIP:endpointUdpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do echo 'hostName' | nc -w 2 -u 10.245.5.17 8081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) endpointPodIP:endpointHttpPort from node1
STEP: Dialing from node. command:for i in $(seq 1 1); do curl -s --connect-timeout 2 http://10.245.5.17:8080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) endpointPodIP:endpointUdpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.245.5.17&port=8081&tries=1'
STEP: dialing(http) endpointPodIP:endpointHttpPort from test container
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.245.5.17&port=8080&tries=1'
STEP: Hitting clusterIP from host and container
STEP: dialing(udp) node1 --> clusterIP:clusterUdpPort
STEP: Dialing from node. command:for i in $(seq 1 35); do echo 'hostName' | nc -w 2 -u 10.0.225.2 90; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) node1 --> clusterIP:clusterHttpPort
STEP: Dialing from node. command:for i in $(seq 1 35); do curl -s --connect-timeout 2 http://10.0.225.2:80/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(udp) test container --> clusterIP:clusterUdpPort
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=udp&host=10.0.225.2&port=90&tries=35'
STEP: dialing(http) test container --> clusterIP:clusterHttpPort
STEP: Dialing from container. Running command:curl -q 'http://10.245.1.27:8080/dial?request=hostName&protocol=http&host=10.0.225.2&port=80&tries=35'
STEP: dialing(udp) endpoint container --> clusterIP:clusterUdpPort
STEP: Dialing from container. Running command:curl -q 'http://10.245.3.24:8080/dial?request=hostName&protocol=udp&host=10.0.225.2&port=90&tries=35'
STEP: dialing(http) endpoint container --> clusterIP:clusterHttpPort
STEP: Dialing from container. Running command:curl -q 'http://10.245.3.24:8080/dial?request=hostName&protocol=http&host=10.0.225.2&port=80&tries=35'
STEP: Hitting nodePort from host and container
STEP: dialing(udp) node1 --> node1:nodeUdpPort
STEP: Dialing from node. command:for i in $(seq 1 35); do echo 'hostName' | nc -w 2 -u 162.222.176.86 32081; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
STEP: dialing(http) node1  --> node1:nodeHttpPort
STEP: Dialing from node. command:for i in $(seq 1 35); do curl -s --connect-timeout 2 http://162.222.176.86:32080/hostName; echo; done | grep -v '^\s*$' |sort | uniq -c | wc -l
[AfterEach] KubeProxy
```
```
KubeProxy
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:118
  should test kube-proxy [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:117

  Expected
      <int>: 4
  to be ==
      <int>: 5

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubeproxy.go:265
```
More detail can be seen in #13632  e2e test

### PR DESCRIPTION
**Pull request by jiangyaoguo**
fixed #14342 
When "Hit Test with Fewer Endpoints", it should ensure the pod is deleted and can't response to http request. A 5s wait can't ensure kube-proxy has remove endpoint from service.

### CODE REVIEW

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

File: test/e2e/kubeproxy.go [hunk 1]
```diff
@@ -459,7 +460,13 @@ func (config *KubeProxyTestConfig) deleteNetProxyPod() {
 	pod := config.endpointPods[0]
 	config.getPodClient().Delete(pod.Name, nil)
 	config.endpointPods = config.endpointPods[1:]
-	time.Sleep(5 * time.Second) // wait for kube-proxy to catch up with the pod being deleted.
+	// wait for pod being deleted.
+	err := waitForPodDisappear(config.f.Client, config.f.Namespace.Name, pod.Name, labels.Everything(), 500*time.Microsecond, 20*time.Second)
```
Comment (erictune) [inline test/e2e/kubeproxy.go]: 500microseconds seems fast.  Do you want to do 500*time.Millisecond?

File: test/e2e/util.go [hunk 2]
```diff
@@ -642,11 +642,8 @@ func waitForRCPodOnNode(c *client.Client, ns, rcName, node string) (*api.Pod, er
 	return p, err
 }
 
-// waitForRCPodToDisappear returns nil if the pod from the given replication controller (described by rcName) no longer exists.
-// In case of failure or too long waiting time, an error is returned.
-func waitForRCPodToDisappear(c *client.Client, ns, rcName, podName string) error {
-	label := labels.SelectorFromSet(labels.Set(map[string]string{"name": rcName}))
-	return wait.Poll(20*time.Second, 5*time.Minute, func() (bool, error) {
+func waitForPodDisappear(c *client.Client, ns, podName string, label labels.Selector, interval, timeout time.Duration) error {
```
Comment (erictune) [inline test/e2e/util.go]: waitForPodToDisappear

File: test/e2e/kubeproxy.go (hunk 1 above)
Comment (jiangyaoguo) [inline test/e2e/kubeproxy.go]: you caught me.

File: test/e2e/kubeproxy.go [hunk 3]
```diff
@@ -471,7 +472,13 @@ func (config *KubeProxyTestConfig) deleteNetProxyPod() {
 	pod := config.endpointPods[0]
 	config.getPodClient().Delete(pod.Name, nil)
 	config.endpointPods = config.endpointPods[1:]
-	time.Sleep(5 * time.Second) // wait for kube-proxy to catch up with the pod being deleted.
+	// wait for pod being deleted.
+	err := waitForPodToDisappear(config.f.Client, config.f.Namespace.Name, pod.Name, labels.Everything(), 500*time.Millisecond, 20*time.Second)
```
Comment (brendandburns) [inline test/e2e/kubeproxy.go]: Please update this timeout to use util.ForeverTestTimeout

File: test/e2e/kubeproxy.go [hunk 4]
```diff
@@ -471,7 +472,13 @@ func (config *KubeProxyTestConfig) deleteNetProxyPod() {
...
+	if err != nil {
+		Failf("Failed to delete %s pod: %v", pod.Name, err)
+	}
+	// wait for kube-proxy to catch up with the pod being deleted.
+	time.Sleep(5 * time.Second)
```
Comment (brendandburns) [inline test/e2e/kubeproxy.go]: This is a recipe for flakiness.  Please poll on the endpoints resource until the endpoints reflect the pod disappearing.  (and then perhaps sleep an additional 5 seconds)

File: test/e2e/kubeproxy.go (hunk 3 above)
Comment (brendandburns) [inline test/e2e/kubeproxy.go]: Also no real need to poll faster than 1/second

**Comment by ArtfulCoder** [comment]
@k8s-bot test this please

**Comment by ArtfulCoder** [comment]
@jiangyaoguo  can you kick shippable in case it fails ?
I have LGTMed the PR
thank you for your contribution!

**Comment by jiangyaoguo** [comment]
@ArtfulCoder What should I do to kick shippable? I saw the  result, but I
