### PR TITLE
The Pod is eligible to preempt when previous nominanted node is UnschedulableAndUnresolvable 

### LINKED ISSUE #92600: Pod won't be considered for preemption even its nominated node is considered as UnschedulableAndUnresolvable by filters
**What happened**:
When a Pod's nominated node is considered as UnschedulableAndUnresolvable in the filter stage, the scheduler doesn't consider that pod for preemption even there are pods can be preempted on another node.

**What you expected to happen**:
When the pod's nominated node is considered as 'UnschedulableAndUnresolvable ' (For example, the taint being added by those conditions, https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition), the scheduler should try to preemption on other nodes.

**How to reproduce it (as minimally and precisely as possible)**:
- Create low priority pod, which schedule to nodeA
- Create mid priority pod, which schedule to nodeB
- Create high priority pod, which preempt the low priority pod on nodeA, and set high priority pod's nominated node as nodeA
- The nodeA's kubelet is down, the node life cycle controller taint the nodeA with 'node.kubernetes.io/unschedulable' (or taint with disk pressure..etc) before low priority pod finishes the termination.
- The high priority pod is keeping as pending status. The scheduler doesn't try to preempt the mid-priority pod on nodeB

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18.0
- Cloud provider or hardware configuration:
baremetal
- OS (e.g: `cat /etc/os-release`):
ubuntu1804
- Kernel (e.g. `uname -a`):
5.3.0-46-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by soulxu**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:
This PR is trying to fix the Pod won't be considered for preemption even its nominated node is considered as UnschedulableAndUnresolvable by the filters

**Which issue(s) this PR fixes**:

Fixes #92600

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixes the pod can be considered for preemption after its previous nominated node become unschedulable and unresolvable.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 1]
```diff
@@ -191,13 +191,18 @@ func preempt(ctx context.Context, fh framework.FrameworkHandle, state *framework
...
 		klog.V(5).Infof("Pod %v/%v is not eligible for preemption because it has a preemptionPolicy of %v", pod.Namespace, pod.Name, v1.PreemptNever)
 		return false
 	}
 	nomNodeName := pod.Status.NominatedNodeName
 	if len(nomNodeName) > 0 {
+		if status, ok := m[nomNodeName]; ok {
+			if status.Code() == framework.UnschedulableAndUnresolvable {
+				return true
+			}
+		}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:205]: I don't think this logic can help resolve the problem thoroughly. There are more cases that this fix doesn't cover:

- The nominatedNode can no longer exist, due to network partition or node shutdown.
- High-priority pod gets scheduled to that node to take the "reserved" room, etc. And also the status.Code()
- Terminating low-priority pods are still occupying the "to-be-releasing" resources.

With that said, ok can be either true or false, also the code can be Unschedulable or UnschedulableAndUnresolvable. So fixing inside `podEligibleToPreemptOthers()` is not a good idea.

A promising solution is to continue the work in #91750 - which was too aggressive, but should be easy to rework a bit to thoroughly considering all meaningful return paths of preemption.

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:205]: > Just mention that the issue shouldn't only about the case of the node being down, it covers all the case of UnschedulableAndUnresolvable. Like the operator taint the node in same time, the pod won't be able to this node anymore, so the pod should be trying to preempt other node.

Ah, I understood your motivation now. Got misled by the issue that you highlighted as "the node gets down"... The solution here is totally irrelevant with the node is down or not, right?

I _guess_ (please confirm) you were trying to say: if the nominated node is somehow infeasible, in particular UnschedulableAndUnresolvable (it can be a new high-priority pod makes the preemptor violate some critical constraints , or the node gets tainted, etc.), we shouldn't return false in `podEligibleToPreemptOthers()` by simply checking whether there are pods being terminated, as that would waste one preemption cycle.

Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:205]: > > Just mention that the issue shouldn't only about the case of the node being down, it covers all the case of UnschedulableAndUnresolvable. Like the operator taint the node in same time, the pod won't be able to this node anymore, so the pod should be trying to preempt other node.
> 
> Ah, I understood your motivation now. Got misled by the issue that you highlighted as "the node gets down"... The solution here is totally irrelevant with the node is down or not, right?

Yes, it isn't only about the node down, it should be about the nominated node considered as 'UnschedulableAndUnresolvable'. Sorry for miss leading that.

> 
> I _guess_ (please confirm) you were trying to say: if the nominated node is somehow infeasible, in particular UnschedulableAndUnresolvable (it can be a new high-priority pod makes the preemptor violate some critical constraints , or the node gets tainted, etc.), we shouldn't return false in `podEligibleToPreemptOthers()` by simply checking whether there are pods being terminated, as that would waste one preemption cycle.

Yes, exactly

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:205]: Got it. Then I think this PR is valid, could you reword the original issue and this PR's description?

Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:205]: > Got it. Then I think this PR is valid, could you reword the original issue and this PR's description?

Thanks, done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 2]
```diff
@@ -108,7 +108,7 @@ func preempt(ctx context.Context, fh framework.FrameworkHandle, state *framework
 		return "", err
 	}
 
-	if !podEligibleToPreemptOthers(pod, fh.SnapshotSharedLister().NodeInfos()) {
+	if !podEligibleToPreemptOthers(pod, fh.SnapshotSharedLister().NodeInfos(), m) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:111]: You can just pass a *status: `m[pod.Status.NominatedNodeName]`, which will be evaluated to nil if either pod.Status.NominatedNodeName == "" or m[nnn] does not exist.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 3]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
 	}
 }
 
+func TestPodEligibleToPreemptOthers(t *testing.T) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:930]: Can you refer to the format of #92571 to rewrite this test a bit?  In particular, use {Node/Pod}Wrapper to build the API objects.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:111]: And please add some comments to explain the case.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 4]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
...
+			name:  "Pod with nominated node",
+			pod:   &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "machine1", UID: types.UID("machine1")}, Spec: v1.PodSpec{Containers: smallContainers}, Status: v1.PodStatus{NominatedNodeName: "machine1"}},
+			pods:  []*v1.Pod{},
+			nodes: []string{"machine1"},
+			nodesStatuses: framework.NodeToStatusMap{
+				"machine1": framework.NewStatus(framework.UnschedulableAndUnresolvable, tainttoleration.ErrReasonNotMatch),
+			},
+			expected: true,
+		},
+	}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:949]: I'd like to expect another test to cover`expected = false`.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 5]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
...
+		pod           *v1.Pod
+		pods          []*v1.Pod
+		nodes         []string
+		nodesStatuses framework.NodeToStatusMap
+		expected      bool
+	}{
+		{
+			name:  "Pod with nominated node",
+			pod:   &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "machine1", UID: types.UID("machine1")}, Spec: v1.PodSpec{Containers: smallContainers}, Status: v1.PodStatus{NominatedNodeName: "machine1"}},
+			pods:  []*v1.Pod{},
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:942]: Remove this field if it's not needed.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 6]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
...
+			nodes: []string{"machine1"},
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:943]: nit: node1 is shorter :)

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 7]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
...
+			expected: true,
+		},
+	}
+
+	for _, test := range tests {
+		var nodes []*v1.Node
+		for _, n := range test.nodes {
+			nodes = append(nodes, makeNode(n, schedutil.DefaultMilliCPURequest*5, schedutil.DefaultMemoryRequest*5))
+		}
+		snapshot := internalcache.NewSnapshot(test.pods, nodes)
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:956]: You don't need to build a snapshot **_just for_** fetching nodeInfos. Just build the nodeInfos directly, something like:

```go
var nodeInfos []*framework.NodeInfo
for _, name := range nodeNames {
	ni := framework.NewNodeInfo()
	ni.SetNode(st.MakeNode().Name(name).Obj())
	nodeInfos = append(nodeInfos, ni)
}
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 8]
```diff
@@ -927,6 +927,40 @@ func TestPickOneNodeForPreemption(t *testing.T) {
...
+		ret := podEligibleToPreemptOthers(test.pod, snapshot.NodeInfos(), test.nodesStatuses)
+		if ret != test.expected {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:958]: nit:

```go
if got := ...; got != test.expected
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 2 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:111]: got it, will do

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 3 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:930]: got it, will do after #92571 merge.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 5 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:942]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 6 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:943]: Yes, you are right :)

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 4 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:949]: Since there are missing unittests for podEligibleToPreemptOther method, I orginially plan to add more tests in another PR, but I think I can add them in this PR with separated commit. Let me know if it is good way your expected.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 7 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:956]: got it, thanks!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 8 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:958]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 7 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:940]: sorry, I continue use the snapshot, since the podEligibleToPreemptOthers function is looking for 'framework.NodeInfoLister' which snapshot implement it

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 9]
```diff
@@ -189,13 +189,19 @@ func preempt(ctx context.Context, fh framework.FrameworkHandle, state *framework
...
+func podEligibleToPreemptOthers(pod *v1.Pod, nodeInfos framework.NodeInfoLister, nominatedNodeStatus *framework.Status) bool {
 	if pod.Spec.PreemptionPolicy != nil && *pod.Spec.PreemptionPolicy == v1.PreemptNever {
 		klog.V(5).Infof("Pod %v/%v is not eligible for preemption because it has a preemptionPolicy of %v", pod.Namespace, pod.Name, v1.PreemptNever)
 		return false
 	}
 	nomNodeName := pod.Status.NominatedNodeName
 	if len(nomNodeName) > 0 {
+		// If the pod's nominated node is considered as UnschedulableAndUnresolvable by the filters,
+		// then the pod should be considered for preempting again.
+		if nominatedNodeStatus != nil && nominatedNodeStatus.Code() == framework.UnschedulableAndUnresolvable {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:201]:
```suggestion
		if nominatedNodeStatus.Code() == framework.UnschedulableAndUnresolvable {
```

As status.Code() ensure we get a success if the status is nil.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:892]: #92571 just got merged. Please rebase to check out the latest format.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:933]: SG.

**Review by Huang-Wei — COMMENTED** [review]
We're almost there. Just one nit.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 9 above)
Comment (soulxu) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:201]: thanks, let me update

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Thanks @soulxu !

**Comment by soulxu** [comment]
@Huang-Wei appreciate your help!
