### PR TITLE
stabilization of Network.should survive network partition.

### LINKED ISSUE #9487: Nodes Network should survive network partition. (Failed 4 times in the last 20 runs. Stability: 80 %)
Master tracking bug: #9312

### PR DESCRIPTION
**Pull request by marekbiskup**
fixes #9487

@jszczepkowski is a good person for review.

@lavalamp please have a look if my assumptions, stated in comments, about the scheduler are valid (in the last step we want to check if new pods can be scheduled on the node that has just recovered from network partition - this is an important check so we can't just remove it; but maybe we can still improve it).

### CODE REVIEW

File: test/e2e/resize_nodes.go [hunk 1]
```diff
@@ -400,6 +405,21 @@ var _ = Describe("Nodes", func() {
 			waitForNodeToBe(c, node.Name, true, 2*time.Minute)
 
 			By("verify wheter new pods can be created on the re-attached node")
+
+			/*
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: nit: style-- we tend to use // instead of /* except for the boilerplate.

File: test/e2e/resize_nodes.go [hunk 2]
```diff
@@ -400,6 +405,21 @@ var _ = Describe("Nodes", func() {
...
+			 * I'm assuming here that the scheduler is 'monotonic': we scheduled
+			 * as many pods as we had nodes, and the node X was chosed to host
+			 * a pod (at least one). Then we failed node X and after that all
+			 * other nodes have more (or the same number of) pods as at the beginning
+			 * of the test. And the new node has no pods. I'm assuming that
+			 * the new pod, created just below, will be scheduled on node X.
+			 *
+			 * I think this assumption is true for schedulers that take into account
+			 * pod names.
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Please use the feature that we have designed for this. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/types.go#L897

File: test/e2e/resize_nodes.go [hunk 3]
```diff
@@ -400,12 +439,30 @@ var _ = Describe("Nodes", func() {
...
 			By("verify wheter new pods can be created on the re-attached node")
-			err = resizeReplicationController(c, ns, name, replicas+1)
-			Expect(err).NotTo(HaveOccurred())
-			err = waitForPodsCreatedRunningResponding(c, ns, name, replicas+1)
-			Expect(err).NotTo(HaveOccurred())
-			_, err = waitForRCPodOnNode(c, ns, name, node.Name)
-			Expect(err).NotTo(HaveOccurred())
+			additionalPod := "additionalpod"
+			expectNoError(createServeHostnamePodOnNode(c, ns, additionalPod, node.Name))
+			expectNoError(waitForPodsCreatedRunningResponding(c, ns, additionalPod, 1))
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Please use the Expect(err).NotTo(HaveOccurred()) pattern, or switch the entire file over.

File: test/e2e/util.go [hunk 4]
```diff
@@ -432,10 +433,13 @@ func waitForRCPodOnNode(c *client.Client, ns, rcName, node string) (*api.Pod, er
 		for _, pod := range pods.Items {
 			if pod.Spec.NodeName == node {
 				Logf("Pod %s found on node %s", pod.Name, node)
-				p = &pod
-				return true, nil
 			}
 		}
+		for _, pod := range pods.Items {
```
Comment (lavalamp) [inline test/e2e/util.go]: Why did you add this loop? It appears that it will return the first pod instead of the pod on the requested node?

File: test/e2e/resize_nodes.go [hunk 5]
```diff
@@ -358,12 +393,15 @@ var _ = Describe("Nodes", func() {
 			err := waitForPodsCreatedRunningResponding(c, ns, name, replicas)
 			Expect(err).NotTo(HaveOccurred())
 
-			By("cause network partition on one node")
-			nodelist, err := c.Nodes().List(labels.Everything(), fields.Everything())
+			By("chose node with at least one pod - the one will fail")
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: What does "the one will fail" mean?

File: test/e2e/resize_nodes.go [hunk 6]
```diff
@@ -372,18 +410,19 @@ var _ = Describe("Nodes", func() {
 					break
 				}
 			}
-			Logf("Setting network partition on %s", node.Name)
+			By(fmt.Sprintf("cause network partition on node %s", node.Name))
+
 			dropCmd := fmt.Sprintf("sudo iptables -I OUTPUT 1 -d %s -j DROP", testContext.CloudConfig.MasterName)
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Does this actually partition the network or just drop traffic from (to?) the master?

Can you add a comment stating the exact effects on network traffic this command has?

Sorry, I know you didn't add this in this PR but without this knowledge it's difficult to review this.

File: test/e2e/resize_nodes.go [hunk 7]
```diff
@@ -372,18 +410,19 @@ var _ = Describe("Nodes", func() {
...
 			if _, _, code, err := SSH(dropCmd, host, testContext.Provider); code != 0 || err != nil {
 				Failf("Expected 0 exit code and nil error when running %s on %s, got %d and %v",
-					dropCmd, node, code, err)
+					dropCmd, node.Name, code, err)
 			}
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Please move the reattachement code below (lines 431-436) into a defer block; Otherwise, if the test fails before that, the node will be permanently broken and future tests will probably fail.

File: test/e2e/resize_nodes.go [hunk 8]
```diff
@@ -400,12 +439,30 @@ var _ = Describe("Nodes", func() {
...
+			// node would be to increase the RC size by 1 and check that the new
+			// pod is scheduled on the recovered node. Something like:
+			// * resizeReplicationController(c, ns, name, replicas+1)
+			// * waitForPodsCreatedRunningResponding(c, ns, name, replicas+1)
+			// * waitForRCPodOnNode(c, ns, name, node.Name)
+			//
+			// But the problem with this approach is that we rely on the scheduler
+			// implementation that may change. For instance, if rescheduling is added,
+			// the pods will go back to original nodes and the new pod may be scheduled
+			// anywhere in the cluster, not only on the recovered node.
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Suggest removing this comment block, or phrasing as "increasing the RC size is not a valid way to test this because...", since it *isn't* an alternative way of doing this :)

File: examples/blog-logging/diagrams/README.md [hunk 9]
```diff
@@ -1 +1,4 @@
 # Diagrams for Cloud Logging Blog Article
+
+
+[![Analytics](https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/examples/blog-logging/diagrams/README.md?pixel)]()
```
Comment (quinton-hoole) [inline examples/blog-logging/diagrams/README.md]: This doesn't belong in this PR?

File: test/e2e/resize_nodes.go [hunk 10]
```diff
@@ -124,6 +126,38 @@ func createServiceWithNameSelector(c *client.Client, ns, name string) error {
 	return err
 }
 
+func newPodOnNode(podName, nodeName string, image string) *api.Pod {
```
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: What namespace is the pod in?

File: test/e2e/resize_nodes.go (hunk 6 above)
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: It drops all packets outbound from the node to the master.  Note that this will not work when we have multi-master (pretty soon).

Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: Note also that only outbound packets from the node will be dropped.  You might also want to drop inbound packets from the master.

File: test/e2e/resize_nodes.go (hunk 3 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: ok

File: test/e2e/util.go (hunk 4 above)
Comment (marekbiskup) [inline test/e2e/util.go]: reverted

File: test/e2e/resize_nodes.go (hunk 5 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: Improved:
By("choose a node with at least one pod - we will block network traffic on this node")

File: test/e2e/resize_nodes.go (hunk 6 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: 1. test name changed to:
```
		testName = "should survive unresponding node."
```

2. comment improved:
```
			By(fmt.Sprintf("block network traffic from node %s", node.Name))

			// The command will block all outgoing network traffic from the node to the master
			// When multi-master is implemented, this test will have to be improved to block
			// network traffic to all masters.
			// We could also block network traffic from the master(s)s to this node,
			// but blocking it one way is sufficient for this test.
```

File: test/e2e/resize_nodes.go (hunk 7 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: ok

File: test/e2e/resize_nodes.go (hunk 10 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: This function only creates an API object. It is created in a given namespace in createServeHostnamePodOnNode

File: test/e2e/resize_nodes.go (hunk 8 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: ok

File: test/e2e/resize_nodes.go (hunk 10 above)
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: OK

**Comment by quinton-hoole** [comment]
@k8s-bot Test this please

**Comment by marekbiskup** [comment]
@lavalamp, please review

File: test/e2e/resize_nodes.go [hunk 11]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+// environments.
+func performTemporaryNetworkFailure(c *client.Client, ns, rcName string, replicas int, podNameToDisappear string, node *api.Node) {
+	Logf("Getting external IP address for %s", node.Name)
+	host := ""
+	for _, a := range node.Status.Addresses {
+		if a.Type == api.NodeExternalIP {
+			host = a.Address + ":22"
+			break
+		}
+	}
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: need to fail if host is still empty here.

File: test/e2e/resize_nodes.go [hunk 12]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+	By(fmt.Sprintf("block network traffic from node %s to the master", node.Name))
+
+	defer func() {
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Shouldn't you only defer this if adding the drop command was successful?

File: test/e2e/resize_nodes.go [hunk 13]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+		By(fmt.Sprintf("Unblock network traffic from node %s to the master", node.Name))
+		// delete OUTPUT rule number 1
+		undropCmd := "sudo iptables --delete OUTPUT 1"
+		if _, _, code, err := SSH(undropCmd, host, testContext.Provider); code != 0 || err != nil {
+			Failf("Expected 0 exit code and nil error when running %s on %s, got %d and %v",
```
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: If this fails, the node is broken and not coming back. Not sure what to do, but it means subsequent tests might have failures.

**Comment by lavalamp** [comment]
Needs a rebase. Assigning to Quinton for final review.

File: test/e2e/resize_nodes.go [hunk 14]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+			host = a.Address + ":22"
+			break
+		}
+	}
+	By(fmt.Sprintf("block network traffic from node %s to the master", node.Name))
+
+	defer func() {
+		By(fmt.Sprintf("Unblock network traffic from node %s to the master", node.Name))
+		// delete OUTPUT rule number 1
+		undropCmd := "sudo iptables --delete OUTPUT 1"
```
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: This will actually delete the wrong rule if anything (e.g. kube-proxy) has inserted an iptables rule at position 1 after you did below.  Better to match on the rule specification, e.g.

sudo iptables --delete OUTPUT --destination %s --jump DROP", testContext.CloudConfig.MasterName

Notes:

1. Prefer use of full parameter names (--delete, --destination etc) rather the -D, -d etc, which get confusing for people less familiar with iptables.

2. Use a constant string here as the syntax must match that used for the insert (except swap --insert/--delete)

3. Re: lavalamp's suggestion above, unconditionally deferring the delete would be safer in the case that the iptables command succeeded but the SSH session failed after that.  But see below for a safer idea altogether.

Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: Note that the use of MasterName will cause iptables to to a DNS lookup to resolve then name to an IP address, which will slow down the test and cause it to fail if DNS is absent or broken.  Could you use the IP address instead please?

File: test/e2e/resize_nodes.go [hunk 15]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+		}
+	}()
+
+	// The command will block all outgoing network traffic from the node to the master
+	// When multi-master is implemented, this test will have to be improved to block
+	// network traffic to all masters.
+	// We could also block network traffic from the master(s)s to this node,
+	// but blocking it one way is sufficient for this test.
+	// (insert output rule number 1)
+	dropCmd := fmt.Sprintf("sudo iptables -I OUTPUT 1 -d %s -j DROP", testContext.CloudConfig.MasterName)
```
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: Please use the syntax described above, and omit the '1', which is the default anyway.

File: test/e2e/resize_nodes.go (hunk 13 above)
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: I thought that I had a better idea (doing the insert, sleep, delete sequence in a single backgrounded/nohupped SSH operation, but that makes synchronization with your checks below more difficult).

So I think the best that you can do here is a few retries.  Please use wait.Poll() for that.

File: test/e2e/resize_nodes.go [hunk 16]
```diff
@@ -223,6 +257,59 @@ func waitForPodsCreatedRunningResponding(c *client.Client, ns, name string, repl
...
+	if _, _, code, err := SSH(dropCmd, host, testContext.Provider); code != 0 || err != nil {
+		Failf("Expected 0 exit code and nil error when running %s on %s, got %d and %v",
```
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: I think, although I'm not 100% sure, that this will prevent your deferred delete from firing.

File: test/e2e/resize_nodes.go [hunk 17]
```diff
@@ -341,7 +428,8 @@ var _ = Describe("Nodes", func() {
 			}
 		})
 
-		testName = "should survive network partition."
+		// TODO: this test has nothing to do with resizing nodes so it should be moved elsewhere.
+		testName = "should survive unresponsive node."
```
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: At the risk of being pedantic, "Nodes should survive unresponsive node" is not actually what you're testing here.  You're testing that "Pods on uncontactable nodes disappear and are recreated by replication controller"

Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: Or perhaps "Nodes, when uncontactable, have their pods recreated by a replication controller"

Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: My apologies, I'm wrong.  You do also check that the node comes back again and can host a pod.

In that case I'd suggest splitting this into two separate tests:

1. testing that pods on the disconnected node are rescheduled, and
2. testing that a disconnected node, once reconnected, can host a pod.

You could do this in a separate PR I guess.

**Comment by quinton-hoole** [comment]
All done.  When these comments are addressed, we're LGTM!

@marekbiskup my apologies for the somewhat protracted review here.  I hope you understand that unless we make this test very robust it's likely to be flaky, and induce flakyness in other tests too, and this will take more time for someone else to diagnose later than it will take to get it as robust as we can during this review.

File: test/e2e/resize_nodes.go (hunk 16 above)
Comment (quinton-hoole) [inline test/e2e/resize_nodes.go]: I checked this up, and I was wrong.  Fail causes a panic, which causes deferred to be called as usual.  So you're all good.

"Fail (and therefore Gomega, since it uses fail) will record a failure for the current space and panic. This allows Ginkgo to stop the current spec in its tracks - no subsequent assertions (or any code for that matter) will be called. Ordinarily Ginkgo will rescue this panic itself and move on to the next test."

File: test/e2e/resize_nodes.go (hunk 11 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: ok

File: test/e2e/resize_nodes.go (hunk 14 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: Ok for most of the comments.
But I don't know how to find the IP of the master within the cluster. I'll leave the DNS name for now.

File: test/e2e/resize_nodes.go (hunk 13 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: I'll retry for 30s with 0.1s interval.

wait.Poll() waits the delay period before executing the first check. I wonder how much time this feature wastes in our tests.

File: test/e2e/resize_nodes.go (hunk 15 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: ok

File: test/e2e/resize_nodes.go (hunk 17 above)
Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: I added a TODO in the code. I'll put this task on my list (at the end, unfortunately)

**Comment by marekbiskup** [comment]
@lavalamp , @quinton-hoole , thanks for the review!

@quinton-hoole , please look at the new versions. There are a lot of TODOs. Just decide if you want them now or later (personally I'd prefer later) - maybe only the master IP now, if you tell me how to do it

**Comment by quinton-hoole** [comment]
Later for the TODO's is fine.  Please open github issues for all of the TODO's, assign them to yourself, and link to those issues in the TODO comments.   LGTM.

**Comment by marekbiskup** [comment]
I reported #10085 and  pull request #10086

File: test/e2e/resize_nodes.go (hunk 16 above)
Comment (lavalamp) [inline test/e2e/resize_nodes.go]: Yes-- deferred things still run when there's a panic unwinding the stack. double-panicing is a bad idea, though.

Comment (marekbiskup) [inline test/e2e/resize_nodes.go]: @lavalamp , you are absolutely right. I reported #10157
I'll fix it after 1.0 (unless it causes problems earlier).
