### PR TITLE
fix incorrect warning whenever headless service is created/updated

### LINKED ISSUE #134040: kubectl prints a warning about spec.SessionAffinity being ignored when creating a headless service
### What happened?

When creating a headless service (see manifest in the reproducer section) without session affinity defined, kubectl (version v1.34.1) always prints a warning:

```
Warning: spec.SessionAffinity is ignored for headless services
````

As  far as I can tell, session affinity when unset defaults to `None` so there's no way for the validation to determine whether or not a value was defined by the client.

### What did you expect to happen?

No warning.

### How can we reproduce it (as minimally and precisely as possible)?

Run this command

```
kubectl create -f -<<EOF
apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  type: ClusterIP
EOF
```

### Anything else we need to know?

The change seems to be introduced by https://github.com/kubernetes/kubernetes/pull/132214

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.0
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
NAME="Fedora Linux"
VERSION="42 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=42
VERSION_CODENAME=""
PLATFORM_ID="platform:f42"
PRETTY_NAME="Fedora Linux 42 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:42"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f42/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=42
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=42
SUPPORT_END=2026-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Peac36**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR is related to:
Fixes: https://github.com/kubernetes/kubernetes/issues/134040

#### Does this PR introduce a user-facing change?

```release-note
remove incorrectly printed warning for SessionAffinity whenever a headless service is creater or updated
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by soltysh** [comment]
/ok-to-test

/assign @danwinship @thockin 
since they approved https://github.com/kubernetes/kubernetes/pull/132214

**Comment by danwinship** [comment]
looks right but please fix the problems pointed out by the linter

File: pkg/api/service/warnings.go [hunk 1]
```diff
@@ -48,7 +48,7 @@ func GetWarningsForService(service, oldService *api.Service) []string {
 		if len(service.Spec.ExternalIPs) > 0 {
 			warnings = append(warnings, "spec.externalIPs is ignored for headless services")
 		}
-		if service.Spec.SessionAffinity != "" {
+		if service.Spec.SessionAffinity != api.ServiceAffinityNone {
```
Comment (aojea) [inline pkg/api/service/warnings.go:51]: per the api docs 

https://github.com/kubernetes/kubernetes/blob/f42b497cf25548aa0f327c675e11c57240bfab4b/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L63-L82

so at this point it has been defaulted

**Comment by aojea** [comment]
/lgtm
/approve

It seems this will require a backport since is an user facing problem, legit services are receiving warnings

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
