### PR TITLE
Derive kubelet serving certificate CSR template from node status addresses

### LINKED ISSUE #55633: Master Kubelet TLS verification broken due to external cloud provider node initialization order
Before the CCM started initializing node addresses (IP addresses and Hostnames) asynchronously, the kubelet would read the addresses, and hostnames from the node or from the cloud before creating the TLS serving certs. This ensured that the TLS certs reflected the correct addresses.

Now that the asynchronous model is being followed for node initialization, the kubelet generates certs with a set of addresses that do not reflect the cloud initialized addresses for the node. 

The order of node address initialization -> TLS cert creation should be preserved with the new asynchronous model as well

### PR DESCRIPTION
**Pull request by liggitt**
xref https://github.com/kubernetes/features/issues/267
fixes #55633

Builds on https://github.com/kubernetes/kubernetes/pull/65587

* Makes the cloud provider authoritative when recording node status addresses
* Makes the node status addresses authoritative for the kube-apiserver determining how to speak to a kubelet (stops paying attention to the hostname label when determining how to reach a kubelet, which was only done to support kubelets < 1.5)
* Updates kubelet certificate rotation to be driven from node status
  * Avoids needing to compute node addresses a second time, and differently, in order to request serving certificates.
  * Allows the kubelet to react to changes in its status addresses by updating its serving certificate
  * Allows the kubelet to be driven by external cloud providers recording node addresses on the node status

test procedure:
```sh
# setup
export FEATURE_GATES=RotateKubeletServerCertificate=true
export KUBELET_FLAGS="--rotate-server-certificates=true --cloud-provider=external"

# cleanup from previous runs
sudo rm -fr /var/lib/kubelet/pki/

# startup
hack/local-up-cluster.sh

# wait for a node to register, verify it didn't set addresses
kubectl get nodes 
kubectl get node/127.0.0.1 -o jsonpath={.status.addresses}

# verify the kubelet server isn't available, and that it didn't populate a serving certificate
curl --cacert _output/certs/server-ca.crt -v https://localhost:10250/pods
ls -la /var/lib/kubelet/pki

# set an address on the node
curl -X PATCH http://localhost:8080/api/v1/nodes/127.0.0.1/status \
  -H "Content-Type: application/merge-patch+json" \
  --data '{"status":{"addresses":[{"type":"Hostname","address":"localhost"}]}}'

# verify a csr was submitted with the right SAN, and approve it
kubectl describe csr
kubectl certificate approve csr-...

# verify the kubelet connection uses a cert that is properly signed and valid for the specified hostname, but NOT the IP
curl --cacert _output/certs/server-ca.crt -v https://localhost:10250/pods
curl --cacert _output/certs/server-ca.crt -v https://127.0.0.1:10250/pods
ls -la /var/lib/kubelet/pki

# set an hostname and IP address on the node
curl -X PATCH http://localhost:8080/api/v1/nodes/127.0.0.1/status \
  -H "Content-Type: application/merge-patch+json" \
  --data '{"status":{"addresses":[{"type":"Hostname","address":"localhost"},{"type":"InternalIP","address":"127.0.0.1"}]}}'

# verify a csr was submitted with the right SAN, and approve it
kubectl describe csr
kubectl certificate approve csr-...

# verify the kubelet connection uses a cert that is properly signed and valid for the specified hostname AND IP
curl --cacert _output/certs/server-ca.crt -v https://localhost:10250/pods
curl --cacert _output/certs/server-ca.crt -v https://127.0.0.1:10250/pods
ls -la /var/lib/kubelet/pki
```

```release-note
* kubelets that specify `--cloud-provider` now only report addresses in Node status as determined by the cloud provider (unless `--hostname-override` is used to force reporting of the specified hostname)
* kubelet serving certificate rotation now reacts to changes in reported node addresses, and will request certificates for addresses set by an external cloud provider
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-node-pr-reviews @kubernetes/sig-auth-pr-reviews 
/assign @mikedanese @awly

File: pkg/kubelet/certificate/kubelet.go [hunk 1]
```diff
@@ -92,6 +105,43 @@ func NewKubeletServerCertificateManager(kubeClient clientset.Interface, kubeCfg
...
+				seenIP[address.Address] = true
+			}
+		case v1.NodeExternalDNS, v1.NodeInternalDNS:
+			if !seenDNS[address.Address] {
+				dnsNames = append(dnsNames, address.Address)
+				seenDNS[address.Address] = true
+			}
+		}
+	}
+
```
Comment (rphillips) [inline pkg/kubelet/certificate/kubelet.go]: @liggitt since we are using reflect to verify a deep equal later in the code, we should sort the dns and IP addresses just in case they get returned in a different order at some point.

Comment (liggitt) [reply pkg/kubelet/certificate/kubelet.go]: good point, done

File: pkg/kubelet/certificate/kubelet.go [hunk 2]
```diff
@@ -92,6 +103,47 @@ func NewKubeletServerCertificateManager(kubeClient clientset.Interface, kubeCfg
...
+	seenDNS := map[string]bool{}
+	seenIP := map[string]bool{}
+	for _, address := range addresses {
+		if len(address.Address) == 0 {
+			continue
+		}
+
+		switch address.Type {
+		case v1.NodeHostName:
+			if ip := net.ParseIP(address.Address); ip != nil {
```
Comment (smarterclayton) [inline pkg/kubelet/certificate/kubelet.go]: Hrm.  Is there any scenario where the node hostname can like an IP, but is not actually an IP and would not be appropriate to interpret as an IP?

File: staging/src/k8s.io/client-go/util/certificate/certificate_manager.go [hunk 3]
```diff
@@ -215,11 +232,30 @@ func (m *manager) Start() {
 
 	glog.V(2).Infof("Certificate rotation is enabled.")
 
+	lastTemplate := m.getTemplate()
+	if m.dynamicTemplate && lastTemplate == nil {
+		// wait for our first template
+		wait.PollImmediateInfinite(time.Second, func() (bool, error) {
+			lastTemplate = m.getTemplate()
+			if lastTemplate == nil {
+				glog.Infof("Waiting for certificate template")
```
Comment (smarterclayton) [inline staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: Why not v(2)?  Because it hangs?  If so, might want a slightly longer message.

Comment (liggitt) [reply staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: Yeah, wanted visibility

File: pkg/kubelet/certificate/kubelet.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubelet/certificate/kubelet.go]: > Is there any scenario where the node hostname can like an IP, but is not actually an IP and would not be appropriate to interpret as an IP?

No? A hostname that parses as an IP *is* an IP... SNI wouldn't treat it as a DNS name, cert verification would require an IP SAN (c.f. https://golang.org/src/crypto/x509/verify.go?s=28297:28349#L914)

File: pkg/kubelet/certificate/kubelet_test.go [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+
+import (
+	"net"
+	"reflect"
+	"testing"
+
+	"k8s.io/api/core/v1"
+)
+
+func Test_addressesToHostnamesAndIP(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/kubelet/certificate/kubelet_test.go]: vscode generated the function that way, will change it

File: staging/src/k8s.io/client-go/util/certificate/certificate_manager.go [hunk 5]
```diff
@@ -232,6 +270,22 @@ func (m *manager) Start() {
...
+			if !reflect.DeepEqual(newTemplate, lastTemplate) {
+				lastTemplate = newTemplate
+				select {
+				case templateChanged <- struct{}{}:
+					// attempt to interrupt rotation sleep
+				default:
+					// if we're not currently sleeping
+				}
+			}
+		}, 32*time.Second)
```
[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: matches the interval at which we reattempt rotation

File: staging/src/k8s.io/client-go/util/certificate/certificate_manager.go [hunk 6]
```diff
@@ -232,6 +270,22 @@ func (m *manager) Start() {
...
+	if m.dynamicTemplate {
+		// watch to see if the template has changed
+		go wait.Forever(func() {
+			newTemplate := m.getTemplate()
+			if !reflect.DeepEqual(newTemplate, lastTemplate) {
+				lastTemplate = newTemplate
+				select {
+				case templateChanged <- struct{}{}:
+					// attempt to interrupt rotation sleep
+				default:
```
[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: hmm... good point. would like to avoid double rotate, though. will think about a more correct way to do this.

**Comment by mikedanese** [comment]
Please ping when you want this reviewed.

**Comment by liggitt** [comment]
> Please ping when you want this reviewed

this is ready now. simplified the change detection and avoided double requests. tested with --cloud-provider=external, verified kubelet waited until addresses were populated, then immediately requested a CSR. when addresses were changed, it requested a new CSR and swapped the certificate once approved.

File: staging/src/k8s.io/client-go/util/certificate/certificate_manager.go [hunk 7]
```diff
@@ -158,9 +170,17 @@ func NewManager(config *Config) (Manager, error) {
...
+	if getTemplate == nil {
+		getTemplate = func() *x509.CertificateRequest { return config.Template }
+		dynamicTemplate = false
+	}
+
 	m := manager{
 		certSigningRequestClient: config.CertificateSigningRequestClient,
-		template:                 config.Template,
+		getTemplate:              getTemplate,
+		dynamicTemplate:          dynamicTemplate,
```
Comment (awly) [inline staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: This can be `config.GetTemplate != nil` and local `dynamicTemplate` var can be removed

**Review by awly — COMMENTED** [review]
LGTM, but @mikedanese should take another look

File: staging/src/k8s.io/client-go/util/certificate/certificate_manager.go (hunk 7 above)
Comment (liggitt) [reply staging/src/k8s.io/client-go/util/certificate/certificate_manager.go]: config.GetTemplate and config.Template are mutually exclusive. `dynamicTemplate` is used to determine whether we need to monitor getTemplate() for changes

**Comment by mikedanese** [comment]
This fixed GKE alpha cluster creation.

/lgtm

**Comment by liggitt** [comment]
/assign @smarterclayton 
for approval of change to pkg/util/node/node.go (dropped use of the hostname label when computing node connection URLs... was for <1.5 compatibility)
