### PR TITLE
fix: show only effective default StorageClass in kubectl output

### LINKED ISSUE #134568: kubectl get storageclass should indicate the effective default StorageClass when multiple defaults exist
### What would you like to be added?

When multiple StorageClasses are annotated as default (`storageclass.kubernetes.io/is-default-class: "true"`), Kubernetes uses the most recently created one as the actual default applied to PVCs without an explicit storageClassName.
https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass

However, kubectl get storageclass currently shows all of them simply as (default), which makes it unclear which StorageClass will actually be used.

I propose enhancing the kubectl get storageclass output to indicate which default StorageClass is effective.

For example:
```
NAME                       PROVISIONER                   RECLAIMPOLICY   AGE
nfs-client (default, effective)   k8s-sigs.io/nfs-...  Delete          3s
standard   (default, inactive)    rancher.io/local-path Delete         48m
```

or by adding a new column:
```
NAME         PROVISIONER                   DEFAULT   EFFECTIVE   AGE
nfs-client   k8s-sigs.io/nfs-...           true      true        3s
standard     rancher.io/local-path         true      false       48m
```

now display
```
NAME                    PROVISIONER                RECLAIMPOLICY   AGE
nfs-client (default)    k8s-sigs.io/nfs-...        Delete          3s
standard   (default)    rancher.io/local-path      Delete          48m
```

### Why is this needed?

This improves user experience and reduces operational mistakes.

### PR DESCRIPTION
**Pull request by jaehanbyun**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
When multiple StorageClasses have the default annotation, `kubectl get storageclass` was showing all of them as "(default)". 
However, only the most recently created one is the effective default.

This PR introduces a custom `TableConvertor` for StorageClass that determines the effective default and only marks that one with "(default)".

**Before:**
```
$ kubectl get storageclass
NAME                   PROVISIONER                                   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)   k8s-sigs.io/nfs-subdir-external-provisioner   Delete          Immediate           false                  3s
standard (default)     kubernetes.io/host-path                       Delete          Immediate           false                  42s
```

**After:**
```
$ kubectl get storageclass
NAME                   PROVISIONER                                   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)   k8s-sigs.io/nfs-subdir-external-provisioner   Delete          Immediate           false                  4s
standard               kubernetes.io/host-path                       Delete          Immediate           false                  14s
```

#### Which issue(s) this PR is related to:
Fixes #134568

#### Special notes for your reviewer:

The existing `printStorageClass` and `printStorageClassList` in `pkg/printers/internalversion/printers.go` process each StorageClass individually, so they cannot determine which one is the effective default. 
A custom `TableConvertor` was needed to access the full list of StorageClasses and compare their creation timestamps before generating the table.

#### Does this PR introduce a user-facing change?

```release-note
Fixed kubectl get storageclass to show only the effective default StorageClass as "(default)" when multiple StorageClasses have the default annotation.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/registry/storage/storageclass/storage/storage.go [hunk 1]
```diff
@@ -46,14 +45,17 @@ func NewREST(optsGetter generic.RESTOptionsGetter) (*REST, error) {
 		DeleteStrategy:      storageclass.Strategy,
 		ReturnDeletedObject: true,
 
-		TableConvertor: printerstorage.TableConvertor{TableGenerator: printers.NewTableGenerator().With(printersinternal.AddHandlers)},
+		TableConvertor: tableConvertor,
```
Comment (soltysh) [inline pkg/registry/storage/storageclass/storage/storage.go]: This is not the correct place where you want to change this. This ensures we have a generic mechanism working across all of the resources. You want to change the actual function responsible for printing the StorageClass resource, which is located here: 
https://github.com/kubernetes/kubernetes/blob/97bd924010a39b71d3fd802e4284418c8b79545c/pkg/printers/internalversion/printers.go#L2648-L2677

Comment (jaehanbyun) [reply pkg/registry/storage/storageclass/storage/storage.go]: Thanks for the review @soltysh.

Yes, I initially tried to implement this in `printStorageClass` as you suggested. However, the function only receives a single StorageClass object, so it cannot determine which one is the effective default among multiple StorageClasses with the default annotation.

When multiple StorageClasses have the default annotation, `kubectl get storageclass` could potentially be fixed in `printStorageClassList` since it has access to the full list. 
But for `kubectl get storageclass <name>`, only a single StorageClass object is passed to `printStorageClass`, so any StorageClass with the default annotation would still be shown as "(default)" even if it's not the effective default.

To identify the effective default in both cases, we need to compare creation timestamps across all StorageClasses. That's why I implemented a custom `TableConvertor` that can list all StorageClasses before generating the table.

Is there an alternative approach you would suggest?

Comment (soltysh) [reply pkg/registry/storage/storageclass/storage/storage.go]: @jaehanbyun I'd say that I prefer best effort than 100% correctness in that case. Let's go with updating `printStorageClassList` based on your suggestion, and when a single storage class is requested we'll abstain from providing information if that's the default or not. This will ensure we have consistency in the code, and we provide best effort value, based on the provided data.

Comment (jaehanbyun) [reply pkg/registry/storage/storageclass/storage/storage.go]: @soltysh Thanks for the follow-up feedback. Updated as you suggested. PTAL.


```
$ kubectl get storageclass
NAME                   PROVISIONER                                   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)   k8s-sigs.io/nfs-subdir-external-provisioner   Delete          Immediate           false                  1s
standard               kubernetes.io/host-path                       Delete          Immediate           false                  55s

$ kubectl get storageclass standard
NAME       PROVISIONER               RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard   kubernetes.io/host-path   Delete          Immediate           false                  55s

$ kubectl get storageclass nfs-client
NAME         PROVISIONER                                   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client   k8s-sigs.io/nfs-subdir-external-provisioner   Delete          Immediate           false                  1s
```

(both `standard` and `nfs-client` have the default annotation, `nfs-client` was created more recently)

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by jaehanbyun** [comment]
Thanks a lot for the review and approval, @soltysh !
