### PR TITLE
Fix VolumeAttachment garbage collection for migrated PVs

### LINKED ISSUE #102097: Garbage collect VolumeAttachments of migrated in-tree volumes
#### What happened:

_Context:_ When a cluster has dangling `VolumeAttachment`s caused by restarts of kube-controller-manager (like described in https://github.com/kubernetes/kubernetes/issues/77324), the attach/detach controller tries to clean them up on startup (ref https://github.com/kubernetes/kubernetes/pull/96617).
For this, it iterates over all `VolumeAttachment`s and finds the responsible volume plugin for retrieving the unique volume name.

_Problem:_ However, if the volume was provisioned by an in-tree plugin, then later migrated to CSI and now the `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate is set, the volume is skipped during `processVolumeAttachments`, so the `VolumeAttachment` will stay in the system and the volume will not be detached from the undesired node and potentially block a new attach operation to a different node.

_Analysis:_ The `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate causes the respective in-tree volume plugins not to be registered: https://github.com/kubernetes/kubernetes/blob/bda557b4bc3f5ec655d32a9ec23345ed9c77147b/cmd/kube-controller-manager/app/plugins_providers.go#L53-L55

The `PersistentVolume` spec only contains the in-tree fields (e.g `awsElasticBlockStore` or `gcePersistentDisk`), but not the `csi` fields:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/migrated-to: pd.csi.storage.gke.io
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
  name: pvc-some-uid
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: some-pvc
    namespace: some-namespace
  gcePersistentDisk:
    fsType: ext4
    pdName: some-pd-name
status:
  phase: Bound
```

This causes the `FindAttachablePluginBySpec` call in `processVolumeAttachments` to find no responsible volume plugin for the `VolumeAttachment`, which will skip the cleanup: https://github.com/kubernetes/kubernetes/blob/be583070d23435577775a276af69c74bc640b964/pkg/controller/volume/attachdetach/attach_detach_controller.go#L719-L733

That's why we see a lot of logs like this on startup of kube-controller-manager and dangling `VolumeAttachment`s on our clusters:
```text
{"log":"Skipping processing the volume \"pvc-some-uid\" on nodeName: \"some-node\", no attacher interface found. err=no volume plugin matched","pid":"1","severity":"WARN","source":"attach_detach_controller.go:738"}
```

#### What you expected to happen:

The attach/detach controller should cleanup dangling `VolumeAttachment`s for migrated in-tree plugins with unregistered in-tree plugins as well.

#### How to reproduce it (as minimally and precisely as possible):
ref https://github.com/kubernetes/kubernetes/issues/94912, https://github.com/kubernetes/kubernetes/pull/101423#issuecomment-828678256

#### Anything else we need to know?:

https://github.com/kubernetes/kubernetes/pull/101737 addresses a similar issue. Though, the fix doesn't come into effect, if the respective `CSIMigration*Complete ` / `InTreePlugin*Unregister` feature gate is enabled.

#### Environment:
- Kubernetes version (use `kubectl version`): `1.18.16` / `1.20.6`
- Cloud provider or hardware configuration: AWS, GCP

### PR DESCRIPTION
**Pull request by timebertt**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR builds on https://github.com/kubernetes/kubernetes/pull/101737 to also cleanup dangling `VolumeAttachment`s after completed migration to CSI (like described in https://github.com/kubernetes/kubernetes/issues/102097).

#### Which issue(s) this PR fixes:

Fixes #102097

#### Special notes for your reviewer:

/sig storage

I validated the change on our clusters, where we observed the issue (AWS/GCP, k8s v1.18/v1.19). On startup, kube-controller-manager now marks the old `VolumeAttachment`s as uncertain and later detaches them, e.g.:
```
{"log":"Marking volume attachment as uncertain as volume:\"kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIFIED/zones/europe-west1-b/disks/pvc-some-id\" (\"some-node\") is not attached (Detached)","pid":"1","severity":"INFO","source":"attach_detach_controller.go:766"}
{"log":"attacherDetacher.DetachVolume started for volume \"pvc-some-id\" (UniqueName: \"kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIFIED/zones/europe-west1-b/disks/pvc-some-id\") on node \"some-node\" This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching","pid":"1","severity":"WARN","source":"reconciler.go:222"}
{"log":"DetachVolume.Detach succeeded for volume \"pvc-some-id\" (UniqueName: \"kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIFIED/zones/europe-west1-b/disks/pvc-some-id\") on node \"some-node\" ","pid":"1","severity":"INFO","source":"operation_generator.go:472"}
```

#### Does this PR introduce a user-facing change?

```release-note
Fixed garbage collection of dangling VolumeAttachments for PersistentVolumes migrated to CSI on startup of kube-controller-manager.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by timebertt** [comment]
/cc @Jiawei0227
if you want to have a look :)

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 1]
```diff
@@ -715,33 +715,47 @@ func (adc *attachDetachController) processVolumeAttachments() error {
...
-		if err != nil || plugin == nil {
-			// Currently VA objects are created for CSI volumes only. nil plugin is unexpected, generate a warning
-			klog.Warningf(
-				"Skipping processing the volume %q on nodeName: %q, no attacher interface found. err=%v",
-				*pvName,
-				nodeName,
-				err)
-			continue
+
+		var (
```
Comment (Jiawei0227) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:719]: nit:
could you use 
```golang
var plugin volume.AttachableVolumePlugin
volumeSpec := volume.NewSpecFromPersistentVolume(pv, false)
```
so that it is consistent code style with other places?

**Review by Jiawei0227 — COMMENTED** [review]
/lgtm
Thanks for the fix! I think this is looking good to me. Just want to understand the issue more, this only happens if there is indeed dangling attachment in the system, right? in a normal sequence, after CSI migration, the Pod should still able to detach this volume?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 1 above)
Comment (timebertt) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Sure, done.

**Comment by timebertt** [comment]
> Just want to understand the issue more, this only happens if there is indeed dangling attachment in the system, right? in a normal sequence, after CSI migration, the Pod should still able to detach this volume?

Yes, this bug is a real edge case, it doesn't happen in a normal sequence.

In all cases, where we observed the bug, kube-controller-manager was restarted while an attach/detach operation was in progress, e.g. because a `StatefulSet` pod was rolled/restarted (like described in https://github.com/kubernetes/kubernetes/pull/96617). What happens on startup then, is that it tries to process the old `VolumeAttachment`, but it can't find a responsible volume plugin (AWS/GCP is unregistered and CSI doesn't feel responsible as the volume was created by in-tree plugins), here: https://github.com/kubernetes/kubernetes/blob/be583070d23435577775a276af69c74bc640b964/pkg/controller/volume/attachdetach/attach_detach_controller.go#L719-L728

If the pod was scheduled on another node, then the Volume won't be detached on the old node as the old `VolumeAttachment` is not cleaned up, which leads to exclusive attach errors.

This is quite hard to reproduce, because it has to happen in a very precise timing (which in large scale environments can of course happen more frequently).
Does this help? :)

**Comment by Jiawei0227** [comment]
> This is quite hard to reproduce, because it has to happen in a very precise timing (which in large scale environments can of course happen more frequently).
Does this help? :)

Thanks a lot! This is very helpful info. 
/lgtm
/cc @gnufied 
For approval.

**Comment by timebertt** [comment]
@Jiawei0227 these two tests are consistently failing. I first assumed, that they were flakes as the test logs don't indicate anything related to my change. I guess, you assumed the same, as you typed `/retest` multiple times, right?

Meanwhile, I will try to run the tests manually and check the failures in more detail.

**Comment by timebertt** [comment]
Ahh wait, the tests seem to be failing since 5/14 already: https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-csi-serial&sort-by-flakiness=
Probably tracked in https://github.com/kubernetes/kubernetes/issues/102077

**Comment by timebertt** [comment]
Tests are green now :)
Friendly ping to @gnufied @jingxu97 for approval.
/priority important-soon

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 2]
```diff
@@ -715,33 +715,45 @@ func (adc *attachDetachController) processVolumeAttachments() error {
...
+				volumeSpec, err = csimigration.TranslateInTreeSpecToCSI(volumeSpec, "" /* podNamespace */, adc.intreeToCSITranslator)
+				if err != nil {
+					klog.Errorf(
+						"Failed to translate intree volumeSpec to CSI volumeSpec for volume:%q, va.Name:%q, nodeName:%q: %v. Error: %v",
+						*pvName,
+						va.Name,
+						nodeName,
+						inTreePluginName,
+						err)
+					continue
```
Comment (gnufied) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:739]: nit: lets use '%s` for `inTreePluginName` .

Comment (timebertt) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:739]: Done, PTAL.
