### PR TITLE
Return error instead of panic when cpu manager fails on startup.

### LINKED ISSUE #84703: cpumanager: kubelet should log fatal error and exit rather than panic when cpu manager fails on startup
**What happened**:

When static policy is enabled, cpu manager do validate state between checkpoint (`/var/lib/kubelet/cpu_manager_state`) and current node cpu topology before kubelet fully started. If the validation is failed (sometimes occurred after node or kubelet crash), cpu manager will panic immediately. However, this panic is handled and ignored by upper wait.Util(). This causes kubelet continue to start (PLEG, syncLoop) normally although other modules in container manager (like qosContainerManager, in setupNode method) doesn't start successfully. Then, kubelet sync pod with a uninitialized qosContainerManager. And it will leads to unexpected results such as:

1. panic when call UpdateQoSCgroups in syncPod.
3. all pods/containers on node will be killed
3. all cgroup path (like kubepods.slice) recursively in each cgroup will be housekept.
2. node status is still ready, kubelet process is still running (doesn't work, panic continuously but not exit)

panic log of `1`:

```
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: E1104 14:48:31.406568    5461 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: goroutine 788 [running]:
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3ad3360, 0x7a8efc0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: panic(0x3ad3360, 0x7a8efc0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /snap/go/4765/src/runtime/panic.go:522 +0x1b5
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).setCPUCgroupConfig(0xc0008170e0, 0xc0010beee8, 0x42f4e55, 0xa)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_container_manager_linux.go:169 +0x3b
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).UpdateCgroups(0xc0008170e0, 0x0, 0x0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_container_manager_linux.go:285 +0x25a
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UpdateQOSCgroups(0xc000435d40, 0xc000a86c00, 0xc00071d680)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:559 +0x3a
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).killPod(0xc0001be400, 0xc000a86c00, 0x0, 0xc000928680, 0x0, 0x4, 0x4)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:822 +0x118
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc0001be400, 0x0, 0xc000a86c00, 0x2, 0xc000928680, 0x0, 0xc00127aa80, 0xc00071bbc0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1615 +0x25d3
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc0009e9ed8, 0xc0001521c0, 0xc0010bfec0, 0x100c000f346c0, 0x0)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:175 +0x25d
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc0001521c0, 0xc001196a20)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:184 +0x13f
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0xc0001521c0, 0xc001196a20)
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:222 +0x62
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
Nov 04 14:48:31 k8s-a-2 kubelet[5461]:         /root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:220 +0x395
```

`docker ps` of `2`:
```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

housekeeping log for `3`:
```
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.055186    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda5eaa6a7_ad37_4aea_a70a_77f040f45692.slice/docker-34533e2e609a61548e6fd687ca8e908fa99edd367abeeda826debfb659829b9c.scope" (aliases: [k8s_calico-node_calico-node-96wk8_kube-system_a5eaa6a7-ad37-4aea-a70a-77f040f45692_5 34533e2e609a61548e6fd687ca8e908fa99edd367abeeda826debfb659829b9c], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.067184    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod65f7c408_6c1e_48f8_aa97_827c25b6e795.slice/docker-4acf276ec577147740809dddc8337d38ded9e962e976d216b9257ffda1a693e2.scope" (aliases: [k8s_kube-proxy_kube-proxy-vfm8b_kube-system_65f7c408-6c1e-48f8-aa97-827c25b6e795_5 4acf276ec577147740809dddc8337d38ded9e962e976d216b9257ffda1a693e2], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.108097    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3052785d_b13d_48ef_96e9_8ef240eda996.slice/docker-4fbfb36132d99091f73e4c96802eb79d3b5b9393d837ce1b2775e5e07a361d80.scope" (aliases: [k8s_nginx_nginx-1-0-4sc6l_default_3052785d-b13d-48ef-96e9-8ef240eda996_4 4fbfb36132d99091f73e4c96802eb79d3b5b9393d837ce1b2775e5e07a361d80], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.117912    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod53e366df_e1f6_486c_9d74_ba88b2f0d8ad.slice/docker-e632915f5b56a522b414c09abe42832cc12fa1aa38b05f835b4a4cd47952010d.scope" (aliases: [k8s_nginx_nginx-1-1-bzm7n_default_53e366df-e1f6-486c-9d74-ba88b2f0d8ad_4 e632915f5b56a522b414c09abe42832cc12fa1aa38b05f835b4a4cd47952010d], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.265379    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda5eaa6a7_ad37_4aea_a70a_77f040f45692.slice/docker-0932b5cb8aa4bd9e5eddad8448d15bf9ff4e2fdb987aaac56b78d4f999b9ad89.scope" (aliases: [k8s_POD_calico-node-96wk8_kube-system_a5eaa6a7-ad37-4aea-a70a-77f040f45692_5 0932b5cb8aa4bd9e5eddad8448d15bf9ff4e2fdb987aaac56b78d4f999b9ad89], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.273375    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod65f7c408_6c1e_48f8_aa97_827c25b6e795.slice/docker-96baff62f92fc4c2cfe2c5d8eb8b19f6d235f7902f128b5f4da90168ae18ca1e.scope" (aliases: [k8s_POD_kube-proxy-vfm8b_kube-system_65f7c408-6c1e-48f8-aa97-827c25b6e795_5 96baff62f92fc4c2cfe2c5d8eb8b19f6d235f7902f128b5f4da90168ae18ca1e], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.540306    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3052785d_b13d_48ef_96e9_8ef240eda996.slice/docker-815160ce8abf28485e6ef1533520f7ee0d3f39ffc8a4f8eab7697f778365cd51.scope" (aliases: [k8s_POD_nginx-1-0-4sc6l_default_3052785d-b13d-48ef-96e9-8ef240eda996_4 815160ce8abf28485e6ef1533520f7ee0d3f39ffc8a4f8eab7697f778365cd51], namespace: "docker")
Nov 04 14:48:31 k8s-a-2 kubelet[5461]: I1104 14:48:31.577601    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod53e366df_e1f6_486c_9d74_ba88b2f0d8ad.slice/docker-f262358e244971f26d73bb03ac43d788f9b0634da414bfd2cc4668d6c5edb574.scope" (aliases: [k8s_POD_nginx-1-1-bzm7n_default_53e366df-e1f6-486c-9d74-ba88b2f0d8ad_4 f262358e244971f26d73bb03ac43d788f9b0634da414bfd2cc4668d6c5edb574], namespace: "docker")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.610904    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod65f7c408_6c1e_48f8_aa97_827c25b6e795.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611025    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod53e366df_e1f6_486c_9d74_ba88b2f0d8ad.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611654    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3052785d_b13d_48ef_96e9_8ef240eda996.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611687    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-besteffort.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611785    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda5eaa6a7_ad37_4aea_a70a_77f040f45692.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611807    5461 manager.go:1005] Destroyed container: "/kubepods.slice/kubepods-burstable.slice" (aliases: [], namespace: "")
Nov 04 14:48:32 k8s-a-2 kubelet[5461]: I1104 14:48:32.611857    5461 manager.go:1005] Destroyed container: "/kubepods.slice" (aliases: [], namespace: "")
``` 

node status of `4`:
```
k8s-a-2   Ready    <none>   3d2h   v1.16.2
```

**What you expected to happen**:

IMHO, It may not be a good idea that panics in new/start code logic. We shoud use `return err` instead, so the caller is able to check the err and exit immediately.

kubelet should log fatal error and exit when some modules create or start failed.

**How to reproduce it (as minimally and precisely as possible)**:

1. enable cpu manager static policy

modify `/var/lib/kubelet/config.yaml` to enable cpu manager static policy:

```
cpuManagerPolicy: static
systemReserved:
  cpu: 500m
  memory: 200M
```

remove `/var/lib/kubelet/cpu_manager_state` and restart kubelet

2. modify /var/lib/kubelet/cpu_manager_state by a invalid value to simulate node crash situation.

for example, change valid checkpoint from:
```
{"policyName":"static","defaultCpuSet":"0-3","checksum":2479968155}
```
to:
```
{"policyName":"static","defaultCpuSet":"0,2-3","checksum":1104188325}
```

3. restart kubelet again

**Anything else we need to know?**:

Ref: 
1. container manager start and panic:

- container manager start: https://github.com/kubernetes/kubernetes/blob/08410cbf06f1c8649157407c660b1c5cb528947b/pkg/kubelet/cm/container_manager_linux.go#L576

- cpu manager start: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/cpu_manager.go#L180

- static policy panic: https://github.com/kubernetes/kubernetes/blob/08410cbf06f1c8649157407c660b1c5cb528947b/pkg/kubelet/cm/cpumanager/policy_static.go#L122

2. it can neither catch the error nor exit immediately here:
https://github.com/kubernetes/kubernetes/blob/08410cbf06f1c8649157407c660b1c5cb528947b/pkg/kubelet/kubelet.go#L1375

This PR would Fix it, PLTA: https://github.com/kubernetes/kubernetes/pull/84705

3. it would be happen when node crash or kubelet down:
https://github.com/kubernetes/kubernetes/issues/84783

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
kvm
```
- OS (e.g: `cat /etc/os-release`):
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS
```
- Kernel (e.g. `uname -a`):
```
Linux ubuntu 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
```
# lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Socket(s):             4
NUMA node(s):          1
Model name:            QEMU Virtual CPU version 2.5+
NUMA node0 CPU(s):     0-3
```

### PR DESCRIPTION
**Pull request by whypro**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Return error instead of panic when cpu manager starts failed.

**Which issue(s) this PR fixes**:

Fixes #84703 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Thanks for your pr!

From your description of the issue, I agree with you that this change seems positive. If the cpu manager does fail to start because of validation issues, I agree its more appropriate for the entire kubelet to fail to start, instead of allowing the kubelet to continue with an only partially functional container manager.

I'll let someone with more experience with the cpu manager sign off on the exact implementation/double check me that this is a good idea :)

**Comment by sjenning** [comment]
/cc @klueska @ConnorDoyle 
fyi @rphillips

File: pkg/kubelet/cm/cpumanager/state/state_checkpoint.go [hunk 1]
```diff
@@ -159,37 +158,52 @@ func (sc *stateCheckpoint) SetCPUSet(containerID string, cset cpuset.CPUSet) {
 	sc.mux.Lock()
 	defer sc.mux.Unlock()
 	sc.cache.SetCPUSet(containerID, cset)
-	sc.storeState()
+	err := sc.storeState()
+	if err != nil {
+		panic("store state error: " + err.Error())
```
Comment (ConnorDoyle) [inline pkg/kubelet/cm/cpumanager/state/state_checkpoint.go]: I took a look elsewhere in the container manager. In the device manager, the current behavior is to log a warning when this occurs. Would you mind making this code consistent with the device manager as part of this PR? This function signature would not need to change. Same for the other four panics in this file, and also state_file.go.

**Review by ConnorDoyle — COMMENTED** [review]
Thanks a lot for finding the root cause of the issue and updating these code paths not to panic. The main changes are LGTM. I wonder what you think about the remaining panics in the checkpoint interface (see comment below).

File: pkg/kubelet/cm/cpumanager/state/state_checkpoint.go (hunk 1 above)
Comment (whypro) [reply pkg/kubelet/cm/cpumanager/state/state_checkpoint.go]: Ok, log warning is better. I've updated these codes.

**Comment by whypro** [comment]
Please also take a look at issue https://github.com/kubernetes/kubernetes/issues/84783 and PR https://github.com/kubernetes/kubernetes/pull/84849 , Thanks! @ConnorDoyle @klueska

**Comment by cbf123** [comment]
I think it would make more sense to call it "Return error instead of panic when cpu manager fails on startup"

**Comment by cbf123** [comment]
Rather than changing it around to return an error, can we change the code that ignores the panic to catch the panic instead and cleanly shut down kubelet?

**Comment by mattjmcnaughton** [comment]
On Wed, Nov 06, 2019 at 09:05:31AM -0800, Chris Friesen wrote:
> Rather than changing it around to return an error, can we change the code that ignores the panic to catch the panic instead and cleanly shut down kubelet?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/84705#issuecomment-550405518

Could you share more about the benefits of using panic/defer vs returning an
error? In my, limited, experience, my sense is that the Go community prefers
returning errors, unless there's a strong reason not to. In this situation,
I believe our ability to cleanly shutdown the Kubelet should still exist if we
return an error.

Its very possible I'm missing an advantage of using panic/defer though :)

**Comment by cbf123** [comment]
> Could you share more about the benefits of using panic/defer vs returning an error?

Heh...I'm the wrong person to be asking about what the Go community or the Kubernetes community prefers.  I was just assuming that there'd be less code churn involved.

One other thought...did you consider deleting the state file and rebuilding it if validation fails?

**Comment by whypro** [comment]
> One other thought...did you consider deleting the state file and rebuilding it if validation fails?

Deleting the state file and rebuilding is a good idea I think, because (static policy) cpumanager reconciler could ensure the consistence in most cases (except for changing the static `policy` to `none`, because none policy has no reconciler).

**Comment by whypro** [comment]
gently ping for review again? @ConnorDoyle @mattjmcnaughton

File: pkg/kubelet/cm/cpumanager/state/state_compatibility_test.go [hunk 2]
```diff
@@ -44,7 +44,10 @@ func TestFileToCheckpointCompatibility(t *testing.T) {
 	// ensure testing state is removed after testing
 	defer os.Remove(statePath)
 
-	fileState := NewFileState(statePath, "none")
+	fileState, err := NewFileState(statePath, "none")
+	if err != nil {
+		t.Fatalf("could not new file state: %v", err)
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/state/state_compatibility_test.go]: s/could not new file state/could not create new file state/

File: pkg/kubelet/cm/cpumanager/state/state_compatibility_test.go [hunk 3]
```diff
@@ -74,7 +77,10 @@ func TestCheckpointToFileCompatibility(t *testing.T) {
 	checkpointState.SetDefaultCPUSet(state.defaultCPUSet)
 	checkpointState.SetCPUAssignments(state.assignments)
 
-	restoredState := NewFileState(path.Join(testingDir, compatibilityTestingCheckpoint), "none")
+	restoredState, err := NewFileState(path.Join(testingDir, compatibilityTestingCheckpoint), "none")
+	if err != nil {
+		t.Fatalf("could not new file state: %v", err)
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/state/state_compatibility_test.go]: s/could not new file state/could not create new file state/

File: pkg/kubelet/cm/cpumanager/state/state_file.go [hunk 4]
```diff
@@ -52,13 +52,14 @@ func NewFileState(filePath string, policyName string) State {
...
 		// could not restore state, init new state file
-		msg := fmt.Sprintf("[cpumanager] state file: unable to restore state from disk (%s)\n", err.Error()) +
-			"Panicking because we cannot guarantee sane CPU affinity for existing containers.\n" +
-			fmt.Sprintf("Please drain this node and delete the CPU manager state file \"%s\" before restarting Kubelet.", stateFile.stateFilePath)
-		panic(msg)
+		klog.Errorf("[cpumanager] state file: unable to restore state from disk (%v)"+
+			" We cannot guarantee sane CPU affinity for existing containers."+
+			" Please drain this node and delete the CPU manager state file \"%s\" before restarting Kubelet.",
+			err, stateFile.stateFilePath)
+		return nil, err
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/state/state_file.go]: Why remove the newlines here? It is usually easer to read if it is broken up, and forces it to jump out when this is the error.

I'm not 100% against the change, just curious about the reasoning to change it.

File: pkg/kubelet/cm/cpumanager/state/state_checkpoint.go [hunk 5]
```diff
@@ -52,8 +52,7 @@ func NewCheckpointState(stateDir, checkpointName, policyName string) (State, err
 
 	if err := stateCheckpoint.restoreState(); err != nil {
 		//lint:ignore ST1005 user-facing error message
-		return nil, fmt.Errorf("could not restore state from checkpoint: %v\n"+
-			"Please drain this node and delete the CPU manager checkpoint file %q before restarting Kubelet.",
+		return nil, fmt.Errorf("could not restore state from checkpoint: %v, please drain this node and delete the CPU manager checkpoint file %q before restarting Kubelet",
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/state/state_checkpoint.go]: Why remove the newlines here? It is usually easer to read if it is broken up, and forces it to jump out when this is the error.

I'm not 100% against the change, just curious about the reasoning to change it.

**Review by klueska — APPROVED** [review]
Mostly looks good to me. Added a few minor comments.

File: pkg/kubelet/cm/cpumanager/state/state_file.go (hunk 4 above)
Comment (whypro) [reply pkg/kubelet/cm/cpumanager/state/state_file.go]: It is just friendly for log collectors which are sensitive to newline. :)
 
Single-line error message may be easy for being collected with log prefix (level, time, file and line number, etc.).  
Multi-line one might lose prefix which contains that info. When these lines are sent to remote log db, It is sometimes hard to search and locate.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 6]
```diff
@@ -188,11 +191,17 @@ func (m *manager) Start(activePods ActivePodsFunc, sourcesReady config.SourcesRe
 	}
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go]: You probably want to change this code to returrn an error instead of panicing too.

Comment (whypro) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: Thanks for noticing.

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: I wrote the patch that recently got merged that introduced this, so wanted to make sure it got covered here on the rebase :)

**Comment by whypro** [comment]
friendly ping @ConnorDoyle @klueska @mattjmcnaughton

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 7]
```diff
@@ -183,16 +186,22 @@ func (m *manager) Start(activePods ActivePodsFunc, sourcesReady config.SourcesRe
 
 	stateImpl, err := state.NewCheckpointState(m.stateFileDirectory, cpuManagerStateFileName, m.policy.Name(), initialContainers)
 	if err != nil {
-		klog.Errorf("[cpumanager] could not initialize checkpoint manager: %v\n", err)
-		panic("[cpumanager] - please drain node and remove policy state file")
+		klog.Errorf("[cpumanager] could not initialize checkpoint manager: %v, please drain node and remove policy state file", err)
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go]: Logging here is redundant because the same information is printed when the Container manager errors out at the next level based on the returned error.

I'd say it's OK for now though. Let's get this PR pushed through and then come back with a cleanup PR for these kind of things afterwards-

Comment (whypro) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: OK, Thanks. 👍
