### PR TITLE
fix flakiness on e2e test TCP CLOSE_WAIT timeout

### LINKED ISSUE #71565: Flake: [sig-network] Network should set TCP CLOSE_WAIT timeout
**Which jobs are failing**:
pull-kubernetes-e2e-kops-aws

**Which test(s) are failing**:
[sig-network] Network should set TCP CLOSE_WAIT timeout 
Test (that's what the name appears as, I don't have any more info)

**Since when has it been failing**:
11-28-2018

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/71479/pull-kubernetes-e2e-kops-aws/115150/
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kops-aws&include-filter-by-regex=%5EOverall%24%7CTest

**Reason for failure**:

**[sig-network] Network should set TCP CLOSE_WAIT timeout**
```test/e2e/network/kube_proxy.go:50
Expected error:
    <*strconv.NumError | 0xc001812c90>: {
        Func: "Atoi",
        Num: "",
        Err: {s: "invalid syntax"},
    }
    strconv.Atoi: parsing "": invalid syntax
not to have occurred
test/e2e/network/kube_proxy.go:204
```

**Test**
```
error during ./hack/ginkgo-e2e.sh --ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[HPA\]|Dashboard|Services.*functioning.*NodePort --report-dir=/workspace/_artifacts --disable-log-dump=true: exit status 1
```

**Anything else we need to know**:
Filing this as a flake as subsequent test executions succeeded.

/kind failing-test
/kind flake

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:

The e2e test "Network should set TCP CLOSE_WAIT timeout"
was not using correctly the option to keep the connection
on the close_wait status, hence it was flake depending on
how fast it checked the conntrack table it may find the entry.

This PR also removes the need to use ssh, using a pod to check 
the conntrack entries and adding a retry loop will avoid flakiness 
related to ssh or race conditions checking the conntrack file.

**Which issue(s) this PR fixes**:

Fixes #71565

**Special notes for your reviewer**:

The failing tests shows that the first ssh command gives the right output, however, the second time the output is empty. This means that the test will not fail if uses the result obtained from the first command or, maybe, if we retry.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/network/kube_proxy.go [hunk 1]
```diff
@@ -186,27 +187,25 @@ var _ = SIGDescribe("Network", func() {
...
 		// Timeout in seconds is available as the fifth column from
 		// /proc/net/nf_conntrack.
-		result, err := e2essh.IssueSSHCommandWithResult(
+		re := regexp.MustCompile(
 			fmt.Sprintf(
-				"sudo cat /proc/net/nf_conntrack "+
-					"| grep 'CLOSE_WAIT.*dst=%v.*dport=%v' "+
-					"| tail -n 1"+
-					"| awk '{print $5}' ",
+				"^\\w+\\s+\\w+\\s+\\w+\\s+\\w+\\s+(\\d+)\\s+CLOSE_WAIT.*dst=%s.*dport=%d",
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: would be cleaner with back-ticks to avoid double backslashes, and a `{4}` pattern instead of repeating `\w+\s+` 4x:

```go
`^(\w+\s+){4}(\d+)\s+CLOSE_WAIT.*dst=%s.*dport=%d`
```

File: test/e2e/network/kube_proxy.go [hunk 2]
```diff
@@ -186,27 +187,25 @@ var _ = SIGDescribe("Network", func() {
...
+		framework.ExpectNoError(err)
 
 		// Timeout in seconds is available as the fifth column from
 		// /proc/net/nf_conntrack.
-		result, err := e2essh.IssueSSHCommandWithResult(
+		re := regexp.MustCompile(
 			fmt.Sprintf(
-				"sudo cat /proc/net/nf_conntrack "+
-					"| grep 'CLOSE_WAIT.*dst=%v.*dport=%v' "+
-					"| tail -n 1"+
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: this took the last of multiple matching lines... is that expected? do we need to do the same?

**Comment by liggitt** [comment]
test is still failing:
```
I1230 00:03:45.493] Dec 30 00:03:32.642: INFO: SSH "sudo cat /proc/net/nf_conntrack | grep 'dport=11302'" on e2e-214148999a-674b9-minion-group-3thf(34.83.3.46:22)
I1230 00:03:45.493] Dec 30 00:03:33.108: INFO: ssh prow@34.83.3.46:22: command:   sudo cat /proc/net/nf_conntrack | grep 'dport=11302'
I1230 00:03:45.493] Dec 30 00:03:33.108: INFO: ssh prow@34.83.3.46:22: stdout:    ""
I1230 00:03:45.493] Dec 30 00:03:33.108: INFO: ssh prow@34.83.3.46:22: stderr:    ""
I1230 00:03:45.493] Dec 30 00:03:33.108: INFO: ssh prow@34.83.3.46:22: exit code: 1
I1230 00:03:45.493] Dec 30 00:03:33.109: FAIL: Unexpected error:
I1230 00:03:45.493]     <*errors.errorString | 0xc0004722f0>: {
I1230 00:03:45.494]         s: "failed running \"sudo cat /proc/net/nf_conntrack | grep 'dport=11302'\": <nil> (exit code 1, stderr )",
I1230 00:03:45.494]     }
I1230 00:03:45.494]     failed running "sudo cat /proc/net/nf_conntrack | grep 'dport=11302'": <nil> (exit code 1, stderr )
```

File: test/e2e/network/kube_proxy.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: absolutely, thanks for the tip

File: test/e2e/network/kube_proxy.go (hunk 2 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: good question, I expect to find only conntrack entry per the tuple dst_address, dst_port and CLOSE_WAIT status and the regexp seems very restrictive.
I've added a condition to the match regexp so we check that there is only one entry matching

**Comment by aojea** [comment]
Test passed now 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86708/pull-kubernetes-e2e-gce/1211598744705830912/

will try to remove the ssh dependency so we can run it with KIND too

**Comment by aojea** [comment]
/hold
gce failures are unrelated, the network test is passing in gce but running it locally in a kind cluster is not working
/test pull-kubernetes-e2e-gce

File: test/e2e/network/kube_proxy.go [hunk 3]
```diff
@@ -20,17 +20,20 @@ import (
...
 	"strconv"
 	"strings"
 	"time"
 
 	v1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/util/wait"
 
 	"k8s.io/kubernetes/test/e2e/framework"
+	"k8s.io/kubernetes/test/e2e/storage/utils"
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: is this ok or the hostexec code should be moved to its own folder inside test/e2e/framework/hostexec?

File: test/e2e/network/kube_proxy.go [hunk 4]
```diff
@@ -184,42 +188,48 @@ var _ = SIGDescribe("Network", func() {
...
+		re := regexp.MustCompile(
+			fmt.Sprintf(
+				`^(?:\w+\s+){4}(\d+)\s+CLOSE_WAIT.*dst=%s.*dport=%d`,
+				serverNodeInfo.nodeIP,
+				testDaemonTCPPort))
+		// Obtain the corresponding conntrack entry on the node
+		// retry in a loop to avoid flakes
+		if err := wait.Poll(5*time.Second, 30*time.Second, func() (bool, error) {
+			result, err := hostExec.IssueCommandWithResult(
+				fmt.Sprintf("cat /proc/net/nf_conntrack | grep 'dport=%v'",
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: KIND does not have `sudo`

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce

flake 

[sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support file as subpath [LinuxOnly] expand_more

File: test/e2e/network/kube_proxy.go (hunk 3 above)
Comment (liggitt) [reply test/e2e/network/kube_proxy.go]: I wouldn't expect network e2e tests to use storage utils

File: test/e2e/network/kube_proxy.go [hunk 5]
```diff
@@ -82,11 +87,10 @@ var _ = SIGDescribe("Network", func() {
...
 
 		// Some distributions (Ubuntu 16.04 etc.) don't support the proc file.
-		_, err = e2essh.IssueSSHCommandWithResult(
-			"ls /proc/net/nf_conntrack",
-			framework.TestContext.Provider,
+		err = hostExec.IssueCommand(
+			"test -f /proc/net/nf_conntrack",
 			clientNodeInfo.node)
-		if err != nil && strings.Contains(err.Error(), "No such file or directory") {
+		if err != nil {
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: making this error check less specific means that any infrastructure error will skip the test, rather than failing it as we want

File: test/e2e/network/kube_proxy.go [hunk 6]
```diff
@@ -105,7 +109,7 @@ var _ = SIGDescribe("Network", func() {
 						Image:           kubeProxyE2eImage,
 						ImagePullPolicy: "Always",
 						Args: []string{
-							"net", "--serve", fmt.Sprintf("0.0.0.0:%d", testDaemonHTTPPort),
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: this is a curious change... aren't these equivalent?

File: test/e2e/network/kube_proxy.go [hunk 7]
```diff
@@ -184,42 +188,48 @@ var _ = SIGDescribe("Network", func() {
...
+		// Timeout in seconds is available as the fifth column from
+		// /proc/net/nf_conntrack.
+		re := regexp.MustCompile(
+			fmt.Sprintf(
+				`^(?:\w+\s+){4}(\d+)\s+CLOSE_WAIT.*dst=%s.*dport=%d`,
+				serverNodeInfo.nodeIP,
+				testDaemonTCPPort))
+		// Obtain the corresponding conntrack entry on the node
+		// retry in a loop to avoid flakes
+		if err := wait.Poll(5*time.Second, 30*time.Second, func() (bool, error) {
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: use wait.ForeverTestTimeout instead of 30 seconds?

Comment (liggitt) [reply test/e2e/network/kube_proxy.go]: use wait.PollImmediate

File: test/e2e/network/kube_proxy.go (hunk 6 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: indeed, we've discussed this in other PR previously, but I keep thinking that 0.0.0.0 is misleading and this way is easy to understand that it listens in all addresses and families.
Just a matter of taste I guess

File: test/e2e/network/kube_proxy.go [hunk 8]
```diff
@@ -184,42 +188,48 @@ var _ = SIGDescribe("Network", func() {
...
+				clientNodeInfo.node)
+			// retry if we can't obtain the conntrack entry
+			if err != nil {
+				framework.Logf("failed to obtain conntrack entry: %v %v", result, err)
+				return false, nil
+			}
+			match := re.FindStringSubmatch(result)
+			// there should be only one matching entry
+			if match == nil || len(match) != 2 {
+				framework.Logf("no conntrack entry %v for port %d on node %s", match, testDaemonTCPPort, serverNodeInfo.nodeIP)
```
Comment (liggitt) [inline test/e2e/network/kube_proxy.go]: would logging `result` here be helpful?

File: test/e2e/network/kube_proxy.go (hunk 5 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: last commit replaces the command to test if the file exists, previously was using `ls` hence the check for the error message. I've replace `ls` by `test -f` that I think it won't need additional checks to the error message

Comment (liggitt) [reply test/e2e/network/kube_proxy.go]: > I think don't need additional checks to the error message

why wouldn't we need to check the specific error? this error could be "failed to exec host command", and we would definitely not want to skip the test in that scenario

Comment (aojea) [reply test/e2e/network/kube_proxy.go]: ups, I said that  due to my ignorance, I was thinking that it receives directly the command execution output ... it seems that is better to use `ls` then. let me revert the change

File: test/e2e/network/kube_proxy.go (hunk 2 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: I understand now the reason of this, it seems that sometimes there are stale entries or unrelated connections that may hit the regexp ... I've recovered tthis

**Comment by aojea** [comment]
/hold cancel
it works locally with KIND, waiting for the CI and another round of reviews

File: test/e2e/network/kube_proxy.go (hunk 6 above)
Comment (thockin) [reply test/e2e/network/kube_proxy.go]: They literally mean the same thing, right?

File: test/e2e/network/kube_proxy.go [hunk 9]
```diff
@@ -184,42 +225,52 @@ var _ = SIGDescribe("Network", func() {
 		<-time.After(time.Duration(1) * time.Second)
 
 		ginkgo.By("Checking /proc/net/nf_conntrack for the timeout")
-		// If test flakes occur here, then this check should be performed
-		// in a loop as there may be a race with the client connecting.
-		e2essh.IssueSSHCommandWithResult(
```
Comment (thockin) [inline test/e2e/network/kube_proxy.go]: This did not check results or error - what was the purpose of it?

File: test/e2e/network/kube_proxy.go [hunk 10]
```diff
@@ -184,42 +225,52 @@ var _ = SIGDescribe("Network", func() {
...
+			serverNodeInfo.nodeIP,
+			testDaemonTCPPort)
+		if err := wait.PollImmediate(5*time.Second, 30*time.Second, func() (bool, error) {
+			result, err := framework.RunHostCmd(fr.Namespace.Name, "e2e-net-exec", cmd)
+			// retry if we can't obtain the conntrack entry
+			if err != nil {
+				framework.Logf("failed to obtain conntrack entry: %v %v", result, err)
+				return false, nil
+			}
+			match := re.FindStringSubmatch(result)
```
Comment (thockin) [inline test/e2e/network/kube_proxy.go]: Would this be simpler if we just took the result line, broke it with `strings.Fields`, and then looked at `[4]` ?

I love regex, but it requires brainpower, which is a bad thing in a test

File: test/e2e/network/kube_proxy.go (hunk 6 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: Jordan clarified it to me 2 weeks ago https://github.com/kubernetes/kubernetes/issues/86479#issuecomment-567968306 , I've been thinking until then that unspecified addresses were IP family bounded 😅

File: test/e2e/network/kube_proxy.go [hunk 11]
```diff
@@ -184,42 +224,42 @@ var _ = SIGDescribe("Network", func() {
...
+				framework.Logf("failed to obtain conntrack entry: %v %v", result, err)
+				return false, nil
+			}
+			framework.Logf("conntrack entry for node %v and port %v:  %v", serverNodeInfo.nodeIP, testDaemonTCPPort, result)
+			// Timeout in seconds is available as the fifth column of
+			// the matched entry in /proc/net/nf_conntrack.
+			match := strings.Fields(result)[4]
+			timeoutSeconds, err := strconv.Atoi(match)
+			if err != nil {
+				return false, fmt.Errorf("failed to convert matched timeout %s to integer: %v", match, err)
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: should we return errors here or just log the errors only and retry?

Comment (thockin) [reply test/e2e/network/kube_proxy.go]: error will not trigger a retry - that seems correct

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
/hold

:/
> Panic: runtime error: index out of range [4] with length 0

**Comment by aojea** [comment]
```
Jan  2 21:40:09.272: INFO: Running '/go/src/k8s.io/kubernetes/kubernetes/platforms/linux/amd64/kubectl --server=https://34.83.44.147 --kubeconfig=/workspace/.kube/config exec --namespace=network-5722 e2e-net-exec -- /bin/sh -x -c cat /rootfs/proc/net/nf_conntrack | grep 'CLOSE_WAIT.*dst=10.40.0.5.*dport=11302' | tail -n 1'
Jan  2 21:40:12.005: INFO: stderr: "+ cat /rootfs/proc/net/nf_conntrack\n+ grep CLOSE_WAIT.*dst=10.40.0.5.*dport=11302\n+ tail -n 1\n"
Jan  2 21:40:12.005: INFO: stdout: ""
Jan  2 21:40:12.006: INFO: conntrack entry for node 10.40.0.5 and port 11302:  
[AfterEach] [sig-network] Network
```

is the tail masking the error 🤔

**Comment by aojea** [comment]
/hold cancel
fixed the pipefail bug and added some checks to make the test more robust

File: test/e2e/network/kube_proxy.go (hunk 2 above)
Comment (aojea) [reply test/e2e/network/kube_proxy.go]: it turned out that the tail was masking the error because we are not setting pipefail, replaced by `grep -m 1`to avoid duplicates

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
/hold
good news is that the test is ok now, and it retries several times to find the entry in the conntrack file

bad news is that we hit the flake :/ , the entry is not there after checking for it multiple times, what's deleting the entry so fast?

@bowei @thockin is this a bug then?

**Comment by aojea** [comment]
/hold
there is something odd with the way the runners are executing the tests to leak the connections, need to investigate more the logic

**Comment by aojea** [comment]
The conntrack file is empty???

> error:
```
exit status 1
Jan  3 15:14:17.008: INFO: Running '/go/src/k8s.io/kubernetes/kubernetes/platforms/linux/amd64/kubectl --server=https://34.83.71.13 --kubeconfig=/workspace/.kube/config exec --namespace=network-4379 e2e-net-exec -- /bin/sh -x -c cat /rootfs/proc/net/nf_conntrack'
Jan  3 15:14:19.568: INFO: stderr: "+ cat /rootfs/proc/net/nf_conntrack\n"
Jan  3 15:14:19.568: INFO: stdout: ""
```

**Comment by aojea** [comment]
/hold
need to understand why the tests work locally with KIND but in GCE the nf_conntrack file mounted in the pod is not showing any conntrack entry

**Comment by aojea** [comment]
/hold cancel
it's passing in GCE and locally, it's ready to go now

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
failure unrelated

**Comment by spiffxp** [comment]
FYI we may want to revert this, seeing an uptick in failures with
```
	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
```

On test runs that don't have this test passing (h/t hakman in #kops-dev https://kubernetes.slack.com/archives/C8MKE2G5P/p1578423258096800)

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=ginkgo

**Comment by aojea** [comment]
I think that the problem is that this goroutine is leaking
https://github.com/kubernetes/kubernetes/pull/86708/files#diff-e99584717e21a274f44c98f0c97a3182R231

The test in the build log is passing but it doesn't show up in the report
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1214622159129808896
