### PR TITLE
Fix run-in-gopath issue with symlink'd gopath

### LINKED ISSUE #65403: godep-save remove all  "BUILD" file
I am trying  to update  aws-sdk-go dep version, following the guide in
https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md

I checkout to the master branch, and I use these commands:
```
hack/run-in-gopath.sh hack/godep-restore.sh -v
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/aws/aws-sdk-go'
hack/run-in-gopath.sh go get -d github.com/aws/aws-sdk-go
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/aws/aws-sdk-go checkout v1.14.10'
hack/run-in-gopath.sh hack/godep-save.sh
```
But all the "BUILD" files in the "vendor" folder are deleted.
```
vendor/k8s.io/utils/clock/BUILD"
vendor/ks.io/utils/exec/BUILD
vendor/k8s.io/utils/exec/testing/BUILD
...
```
What did i do wrong？What are the right steps?

When I use the same commands in the "release-1.9" branch,  all these files are not changed.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Fixes `hack/update-bazel.sh` so that it can be run in a symlink'd GOPATH, (such as using `hack/run-in-gopath.sh`).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65403.

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: hack/update-bazel.sh [hunk 1]
```diff
@@ -43,9 +42,11 @@ if ! grep -q "# gazelle:importmap_prefix" "${KUBE_ROOT}/vendor/BUILD"; then
   echo "# gazelle:importmap_prefix k8s.io/kubernetes/vendor" >> "${KUBE_ROOT}/vendor/BUILD"
 fi
 
-gazelle fix \
-    -build_file_name=BUILD,BUILD.bazel \
-    -external=vendored \
-    -mode=fix
+pushd "$(kube::realpath ${KUBE_ROOT})" > /dev/null 2>&1
```
Comment (cblecker) [inline hack/update-bazel.sh]: Made this slightly less awful by using `kube::realpath`

File: hack/lib/init.sh [hunk 2]
```diff
@@ -23,7 +23,7 @@ set -o pipefail
 unset CDPATH
 
 # The root of the build/dist directory
-KUBE_ROOT="$(cd "$(dirname "${BASH_SOURCE}")/../.." && pwd -P)"
+KUBE_ROOT="$(cd "$(dirname "${BASH_SOURCE}")/../.." && pwd)"
```
Comment (ixdy) [inline hack/lib/init.sh]: I think we do want to fully resolve this.

File: hack/update-bazel.sh (hunk 1 above)
Comment (ixdy) [reply hack/update-bazel.sh]: I have a slight preference on subshell instead of pushd/popd, i.e.

```bash
(
  cd wherever
  gazelle ...
)
```

File: hack/update-bazel.sh [hunk 3]
```diff
@@ -43,9 +42,11 @@ if ! grep -q "# gazelle:importmap_prefix" "${KUBE_ROOT}/vendor/BUILD"; then
...
+  gazelle fix \
```
Comment (ixdy) [inline hack/update-bazel.sh]: the alternate fix (mentioned by @jayconrod on slack) is to do
```bash
gazelle fix ... -repo_root="${KUBE_ROOT}" "${KUBE_ROOT}"
```
which is also clunky.

File: hack/update-bazel.sh [hunk 4]
```diff
@@ -30,10 +28,11 @@ rm -f "${KUBE_ROOT}/pkg/generated/openapi/zz_generated.openapi.go"
 export GOBIN="${KUBE_OUTPUT_BINPATH}"
 PATH="${GOBIN}:${PATH}"
 
-# Install tools we need, but only from vendor/...
-go install ./vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle
-
-go install ./vendor/github.com/kubernetes/repo-infra/kazel
+pushd "${KUBE_ROOT}" > /dev/null 2>&1
+  # Install tools we need, but only from vendor/...
+  go install ./vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle
```
Comment (ixdy) [inline hack/update-bazel.sh]: we could make these `go install k8s.io/kubernetes/vendor/...` but I'm not sure that's better.

File: hack/update-bazel.sh (hunk 3 above)
Comment (cblecker) [reply hack/update-bazel.sh]: it's clunky, but local tests of it seem to work.. and it's less clunky than subshells IMO

File: hack/update-bazel.sh [hunk 5]
```diff
@@ -31,9 +29,8 @@ export GOBIN="${KUBE_OUTPUT_BINPATH}"
 PATH="${GOBIN}:${PATH}"
 
 # Install tools we need, but only from vendor/...
-go install ./vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle
-
-go install ./vendor/github.com/kubernetes/repo-infra/kazel
+go install k8s.io/kubernetes/vendor/github.com/bazelbuild/bazel-gazelle/cmd/gazelle
```
Comment (ixdy) [inline hack/update-bazel.sh]: for consistency, should we update https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/hack/verify-spelling.sh#L27-L28 too?

Comment (BenTheElder) [reply hack/update-bazel.sh]: SGTM
