### PR TITLE
Set field manager for kubectl diff --server-side

### LINKED ISSUE #87600: `kubectl diff --server-side` fails
**What happened**:

`kubectl diff --server-side` fails.

```
$ kubectl diff --server-side -f file.yaml
The PatchOptions "" is invalid: fieldManager: Required value: is required for apply patch
```

**What you expected to happen**:

I would expect the PatchOptions to not include FieldManager. 

The following fix will eliminate the problem.

```diff
diff --git a/pkg/cmd/diff/diff.go b/pkg/cmd/diff/diff.go
index ac762a71..08c98896 100644
--- a/pkg/cmd/diff/diff.go
+++ b/pkg/cmd/diff/diff.go
@@ -73,6 +73,7 @@ type DiffOptions struct {
 
 	ServerSideApply bool
 	ForceConflicts  bool
+	FieldManager    string
 
 	OpenAPISchema    openapi.Resources
 	DiscoveryClient  discovery.DiscoveryInterface
@@ -261,6 +262,7 @@ type InfoObject struct {
 	Force           bool
 	ServerSideApply bool
 	ForceConflicts  bool
+	FieldManager    string
 	genericclioptions.IOStreams
 }
 
@@ -282,6 +284,7 @@ func (obj InfoObject) Merged() (runtime.Object, error) {
 		options := metav1.PatchOptions{
 			Force:        &obj.ForceConflicts,
 			DryRun:       []string{metav1.DryRunAll},
+			FieldManager: obj.FieldManager,
 		}
 		return resource.NewHelper(obj.Info.Client, obj.Info.Mapping).Patch(
 			obj.Info.Namespace,
@@ -406,6 +409,7 @@ func (o *DiffOptions) Complete(f cmdutil.Factory, cmd *cobra.Command) error {
 
 	o.ServerSideApply = cmdutil.GetServerSideApplyFlag(cmd)
 	o.ForceConflicts = cmdutil.GetForceConflictsFlag(cmd)
+	o.FieldManager = cmdutil.GetFieldManagerFlag(cmd)
 	if o.ForceConflicts && !o.ServerSideApply {
 		return fmt.Errorf("--force-conflicts only works with --server-side")
 	}
@@ -494,6 +498,7 @@ func (o *DiffOptions) Run() error {
 				Force:           force,
 				ServerSideApply: o.ServerSideApply,
 				ForceConflicts:  o.ForceConflicts,
+				FieldManager:    o.FieldManager,
 				IOStreams:       o.Diff.IOStreams,
 			}

```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16 and 1.17
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by julianvmodesto**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This change sets the server-side apply field manager for `kubectl diff` when `--server-side` is passed.

Field manager is a required field:

```
$ kubectl diff --server-side -f file.yaml
The PatchOptions "" is invalid: fieldManager: Required value: is required for apply patch
```

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/87600

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/priority important-soon
/sig cli
/assign @apelisse

### CODE REVIEW

File: test/cmd/diff.sh [hunk 1]
```diff
@@ -44,6 +47,11 @@ run_kubectl_diff_tests() {
     # Test that we have a return code bigger than 1 if there is an error when diffing
     kubectl diff -f hack/testdata/invalid-pod.yaml || test $? -gt 1
 
+    # Test diff with server-side apply
+    kubectl apply -f hack/testdata/pod.yaml --server-side --force-conflicts
+    # Make sure that diffing the resource right after returns nothing (0 exit code).
+    kubectl diff -f hack/testdata/pod.yaml --server-side
```
Comment (julianvmodesto) [inline test/cmd/diff.sh]: Oh this produces a diff and exits w/ 1 only because of the field manager timestamp

```diff
diff -u -N /tmp/LIVE-571109069/v1.Pod.namespace-1583178564-24022.test-pod /tmp/MERGED-959055816/v1.Pod.namespace-1583178564-24022.test-pod
--- /tmp/LIVE-571109069/v1.Pod.namespace-1583178564-24022.test-pod	2020-03-02 19:49:27.028935894 +0000
+++ /tmp/MERGED-959055816/v1.Pod.namespace-1583178564-24022.test-pod	2020-03-02 19:49:27.032936239 +0000
@@ -22,7 +22,7 @@
             f:name: {}
     manager: kubectl
     operation: Apply
-    time: "2020-03-02T19:49:26Z"
+    time: "2020-03-02T19:49:27Z"
   - apiVersion: v1
     fieldsType: FieldsV1
     fieldsV1:
```

Comment (apelisse) [reply test/cmd/diff.sh]: @jennybuckley This happens only because we've changed the object on a no-op apply. That's a bad bug. Don't we have a test for that?

Comment (julianvmodesto) [reply test/cmd/diff.sh]: cc @jennybuckley

File: test/cmd/diff.sh [hunk 2]
```diff
@@ -41,9 +44,18 @@ run_kubectl_diff_tests() {
...
+    # Test found diff with server-side apply
+    output_message=$(kubectl diff -f hack/testdata/pod-changed.yaml --server-side || test $? -eq 1)
+    kube::test::if_has_string "${output_message}" 'k8s.gcr.io/pause:3.0'
+
     # Test that we have a return code bigger than 1 if there is an error when diffing
     kubectl diff -f hack/testdata/invalid-pod.yaml || test $? -gt 1
 
+    # Test empty diff with server-side apply
+    kubectl apply -f hack/testdata/pod.yaml --server-side --force-conflicts
+    # Make sure that diffing the resource right after returns nothing (0 exit code).
```
Comment (apelisse) [inline test/cmd/diff.sh]: We clearly need to change that in the future, maybe add a comment explaining why we're doing the test here. Also let's open an issue to track that we need to fix that when the apply bug is fixed.

Comment (julianvmodesto) [reply test/cmd/diff.sh]: Ah ok, I'll update the comment.

Opened https://github.com/kubernetes/kubernetes/issues/88816

Comment (julianvmodesto) [reply test/cmd/diff.sh]: Done.

**Comment by apelisse** [comment]
You've got to fix the `shellcheck` test in `verify`

**Comment by apelisse** [comment]
And the integration diff test must be related to the PR too

File: test/cmd/diff.sh (hunk 1 above)
Comment (jennybuckley) [reply test/cmd/diff.sh]: The test is only to verify no-op updates don't write to etcd.

**Comment by julianvmodesto** [comment]
Let me remove that no-op test and replace it with a diff between CSA and SSA

File: test/cmd/diff.sh [hunk 3]
```diff
@@ -41,6 +44,11 @@ run_kubectl_diff_tests() {
     output_message=$(kubectl diff -f hack/testdata/pod-changed.yaml || test $? -eq 1)
     kube::test::if_has_string "${output_message}" 'k8s.gcr.io/pause:3.0'
 
+    # Test found diff with server-side apply
+    kubectl apply -f hack/testdata/pod.yaml
+    output_message=$(kubectl diff -f hack/testdata/pod-changed.yaml --server-side --force-conflicts || test $? -eq 1)
```
Comment (apelisse) [inline test/cmd/diff.sh]: I wasn't expecting to find the `test $? -eq 1`, I'm not sure what you're trying to do here?

Comment (julianvmodesto) [reply test/cmd/diff.sh]: Oh this is for a diff between `hack/testdata/pod.yaml` (CSA) and `hack/testdata/pod-changed.yaml` (SSA).

This exercises `kubectl diff --server-side` to validate that the original issue is fixed and `kubectl diff --server-side` is usuable since now we pass fieldManager

Comment (julianvmodesto) [reply test/cmd/diff.sh]: I think it's confusing that I added `kubectl apply -f hack/testdata/pod.yaml` first

**Comment by apelisse** [comment]
/approve
/lgtm
/milestone v1.18
cc @jeremyrickard

File: test/cmd/diff.sh (hunk 3 above)
Comment (lavalamp) [reply test/cmd/diff.sh]: You're doing this in a subshell, does it propagate and cause a failure when triggered?

**Comment by apelisse** [comment]
@jeremyrickard Exception has been approved for that, it's just missing the milestone now!

File: test/cmd/diff.sh (hunk 3 above)
Comment (apelisse) [reply test/cmd/diff.sh]: Yeah, the test fails even if the error is in the sub-shell
