### PR TITLE
fix smb unmount issue on Windows

### LINKED ISSUE #75025: pod with smb mount could not be terminated when password becomes invalid on Windows
**What happened**:
pod with smb(cifs) mount could not be terminated on Windows when that smb account is invalid, the pod will be stuck forever 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. create a pod with azure file mount on Windows
2. make the storage account of azure file invalid
3. delete the pod
4. pod with azure file mount could not be terminated forever

**Anything else we need to know?**:
similar to case: https://github.com/kubernetes/kubernetes/issues/73513

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign
/sig windows

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fix following issue:
pod with smb(cifs) mount could not be terminated on Windows when that smb account is invalid, the pod will be stuck forever

This PR is another windows fix related to https://github.com/kubernetes/kubernetes/pull/74625

**Which issue(s) this PR fixes**:

Fixes #75025

**Special notes for your reviewer**:
This PR implement `IsCorruptedMnt` func on Windows, unix code is actully unchanged. 
The warnning logs in this PR would be like following in kubelet which is expected:
```
W0308 05:53:34.344557    2392 mount_helper_windows.go:52] IsCorruptedMnt failed with ERROR_LOGON_FAILURE error: CreateFile c:\var\lib\kubelet\pods\4fe70e4a-4166-11e9-bf93-000d3af95268\volumes\kubernetes.io~azure-file\pvc-4fe1243c-4166-11e9-bf93-000d3af95268: The user name or password is incorrect.
W0308 05:53:34.347757    2392 mount_helper_windows.go:52] IsCorruptedMnt failed with ERROR_LOGON_FAILURE error: CreateFile c:\var\lib\kubelet\pods\4fe70e4a-4166-11e9-bf93-000d3af95268\volumes\kubernetes.io~azure-file\pvc-4fe1243c-4166-11e9-bf93-000d3af95268: The user name or password is incorrect.
I0308 05:53:34.347757    2392 mount_helper_common.go:74] "c:\\var\\lib\\kubelet\\pods\\4fe70e4a-4166-11e9-bf93-000d3af95268\\volumes\\kubernetes.io~azure-file\\pvc-4fe1243c-4166-11e9-bf93-000d3af95268" is a mountpoint, unmounting
I0308 05:53:34.347757    2392 mount_windows.go:149] azureMount: Unmount target ("c:\\var\\lib\\kubelet\\pods\\4fe70e4a-4166-11e9-bf93-000d3af95268\\volumes\\kubernetes.io~azure-file\\pvc-4fe1243c-4166-11e9-bf93-000d3af95268")
```

**Does this PR introduce a user-facing change?**:

```release-note
fix smb unmount issue on Windows
```

/sig windows
/priority important-soon
/assign @jingxu97 @davidz627 @msau42 

cc @feiskyer could you mark milestone of this PR, thanks.

### CODE REVIEW

File: pkg/util/mount/mount_helper_windows.go [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+	SMBConnectionError = "password is incorrect"
+)
+
+// IsCorruptedMnt return true if err is about corrupted mount point
+func IsCorruptedMnt(err error) bool {
+	if err == nil {
+		return false
+	}
+
+	if strings.Contains(err.Error(), SMBConnectionError) {
```
Comment (feiskyer) [inline pkg/util/mount/mount_helper_windows.go]: Is "password is incorrect" the only case for corrupt? Are there any other possibilities?

Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: good question, there must be other possiblities, while I don't know.
another fix is write like this which may have drawbacks, it depens on whether we use whiltelist or backlist:
```
func IsCorruptedMnt(err error) bool {
    return err != nil
}
```

I think there are some errors still missing on Linux implementation since only following 4 errors caught in `IsCorruptedMnt` func:
https://github.com/kubernetes/kubernetes/blob/a8492d74ecacea9503f08b8e6bf664777b7d41e4/pkg/util/mount/mount_helper.go#L107-L123

@jingxu97 @msau42 @davidz627 what do you think about this? why way do you prefer on Windows?

Comment (msau42) [reply pkg/util/mount/mount_helper_windows.go]: invalid password seems like a strange scenario to consider as a "corrupted" mount.  Is that a normal error that users may encounter?  Is it recoverable?

**Comment by michmike** [comment]
adding a hold until we identify all the proper mount failures on windows
/hold
@neolit123 can you also please review?

**Comment by michmike** [comment]
cc: @benmoss  for review as well

**Comment by PatrickLang** [comment]
Just like #74625, this would also need backport to 1.11-1.13.

File: pkg/util/mount/mount_helper_windows.go [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+package mount
+
+import (
+	"k8s.io/klog"
+	"strings"
+)
+
+const (
+	// SMBConnectionError : SMB Connection Error, e.g. password change
+	SMBConnectionError = "password is incorrect"
```
Comment (PatrickLang) [inline pkg/util/mount/mount_helper_windows.go]: I think this message can be localized, is there an error number we can compare against instead? https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-
ERROR_INVALID_PASSWORD = 86

File: pkg/util/mount/mount_helper_windows.go (hunk 1 above)
Comment (PatrickLang) [reply pkg/util/mount/mount_helper_windows.go]: I think these could also be returned
- ERROR_NETWORK_ACCESS_DENIED
- ERROR_BAD_NET_NAME
- ERROR_NETNAME_DELETED

(reference list: https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--0-499-)

**Comment by PatrickLang** [comment]
cc @KnicKnic - any feedback on identifying failed mounts?

File: pkg/util/mount/mount_helper_windows.go (hunk 1 above)
Comment (neolit123) [reply pkg/util/mount/mount_helper_windows.go]: @andyzhangx 

> I think there are some errors still missing on Linux implementation since only following 4 errors caught in IsCorruptedMnt func

this command uses Stat() -> fstatat() on *unix
and i think the list of existing errors is odd.

here is what fstatat returns:
http://man7.org/linux/man-pages/man3/fstatat.3p.html

----

on Windows Stat() uses the stat() function here:
https://golang.org/src/os/stat_windows.go

so it will throw a `PathError` at least. i don't know where SMBConnectionError comes from.

in terms of Windows error codes @PatrickLang already listed some, i don't know the codes of a corrupted `mklink / CreateSymbolicLink`, but here is what you can do to check against them:

```
package main

import (
	"fmt"
	"golang.org/x/sys/windows"
	"syscall"
)

func main() {
	ptr, err := windows.UTF16PtrFromString("./some-missing-path")
	if err != nil {
		fmt.Println(err)
		return
	}
	attrib, err := windows.GetFileAttributes(ptr)
	if err != nil {
		fmt.Println(err.(syscall.Errno) == windows.ERROR_FILE_NOT_FOUND)
		return
	}
	fmt.Println(attrib)
}
```

Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: @neolit123 thanks for the check, it will throw a `PathError` error, the return error is like following by invoking Lstat --> GetFileAttributesEx, and then error info `The user name or password is incorrect` does not exists in `types_windows.go`:
```
Lstat: GetFileAttributesEx \\f2fd4bb983fba11e9bc4200.file.core.windows.net\andy-k8swin1126-dynami-pvc-2fc7d669-3fba-11e9-8003-000d3a0d9b61: The user name or password is incorrect.
```

Comment (neolit123) [reply pkg/util/mount/mount_helper_windows.go]: > and then error info The user name or password is incorrect does not exists in types_windows.go

we can still verify against the integer (ERROR_LOGON_FAILURE, 1326)
https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--1300-1699-

e.g.
```
const ERROR_LOGON_FAILURE = 1326
... 
err.(syscall.Errno) == ERROR_LOGON_FAILURE
```

Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: @neolit123 thanks, it's `1040`, not in the list of https://docs.microsoft.com/en-us/windows/desktop/Debug/system-error-codes--1000-1299-, so shall I go with `1040` error checking?

Comment (neolit123) [reply pkg/util/mount/mount_helper_windows.go]: hm, i don't know what 1040 is, but probably best not to check for it.
golang just calls native functions and those follow only the existing error codes.

Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: @neolit123 sorry, I was wrong, it's this error:
```
ERROR_LOGON_FAILURE
1326 (0x52E)
The user name or password is incorrect.
```
I think I have the correct solution now, I have this error check in the code first, thanks!

**Comment by andyzhangx** [comment]
thanks guys, I used errorno check as @neolit123 suggested, pushed a new commit: https://github.com/kubernetes/kubernetes/pull/75087/commits/d0d49da2ca9f693fb1da377b9b765b3066a67877

BTW, this issue is a common failure in SMB user scenario, for some reason(e.g. security consideration), user changed the password of SMB server, while the original SMB mount could not be terminated **forever**, on Linux, it has been fixed by adding one more check:
```
underlyingError == syscall.EACCES
```
https://github.com/kubernetes/kubernetes/blob/788f24583e95ac47938a41daaf1f1efc58153738/pkg/util/mount/mount_helper.go#L123

While it is not fixed on Windows yet.

It looks like it's very close to code freeze date, can we make it into 1.14?

File: pkg/util/mount/mount_helper_windows.go (hunk 1 above)
Comment (michmike) [reply pkg/util/mount/mount_helper_windows.go]: that's great that it matches the real error codes from windows

**Comment by michmike** [comment]
> thanks guys, I used errorno check as @neolit123 suggested, pushed a new commit: [d0d49da](https://github.com/kubernetes/kubernetes/commit/d0d49da2ca9f693fb1da377b9b765b3066a67877)
> 
> BTW, this issue is a common failure in SMB user scenario, for some reason(e.g. security consideration), user changed the password of SMB server, while the original SMB mount could not be terminated **forever**, on Linux, it has been fixed by adding one more check:
> 
> ```
> underlyingError == syscall.EACCES
> ```
> [kubernetes/pkg/util/mount/mount_helper.go](https://github.com/kubernetes/kubernetes/blob/788f24583e95ac47938a41daaf1f1efc58153738/pkg/util/mount/mount_helper.go#L123)
> 
> Line 123 in [788f245](/kubernetes/kubernetes/commit/788f24583e95ac47938a41daaf1f1efc58153738)
> 
>  return underlyingError == syscall.ENOTCONN || underlyingError == syscall.ESTALE || underlyingError == syscall.EIO || underlyingError == syscall.EACCES 
> While it is not fixed on Windows yet.
> 
> It looks like it's very close to code freeze date, can we make it into 1.14?

don't worry about code freeze. we need to fix this properly , test it and then we can see about 1.14

**Comment by michmike** [comment]
i would like @adelina-t, @bclau to also have the fix run in the same environment where it failed before

**Comment by andyzhangx** [comment]
> i would like @adelina-t, @bclau to also have the fix run in the same environment where it failed before

This fix only applies for SMB unmount issue on Windows, happens when password changed, do we have any test failure on this before? @michmike

File: pkg/util/mount/mount_helper_windows.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+	case *os.PathError:
+		underlyingError = pe.Err
+	case *os.LinkError:
+		underlyingError = pe.Err
+	case *os.SyscallError:
+		underlyingError = pe.Err
+	}
+
+	if ee, ok := underlyingError.(syscall.Errno); ok {
+		if int(ee) == ERROR_LOGON_FAILURE {
```
Comment (michmike) [inline pkg/util/mount/mount_helper_windows.go]: thank you for the code update. My main issue is why are we only checking for logon failure on windows and not the other network related issues that the linux codebase is checking for? Patrick had given 3 more network related failures to account for as well.

**Comment by michmike** [comment]
> > i would like @adelina-t, @bclau to also have the fix run in the same environment where it failed before
> 
> This fix only applies for SMB unmount issue on Windows, happens when password changed, do we have any test failure on this before? @michmike

patrick had mentioned there was... adelina or bclau can shed more light

File: pkg/util/mount/mount_helper_windows.go (hunk 3 above)
Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: @michmike thanks, I have added those 3 network failures in the code.

**Comment by adelina-t** [comment]
In the upstream tests there is no such failure that I am aware of. Given the nature of the bug ( password change ) I doubt we will ever see it in upstream tests.

**Comment by andyzhangx** [comment]
> In the upstream tests there is no such failure that I am aware of. Given the nature of the bug ( password change ) I doubt we will ever see it in upstream tests.

Correct, this should be a negative case on windows for testing SMB functionality, apparently it's not in current test list.

**Comment by michmike** [comment]
@jingxu97 or @saad-ali can you please take a look at this change and see if you approve?

**Comment by neolit123** [comment]
LGTM on the code in general.
the only remaining question is if we handle all relevant errors under `IsCorruptedMnt` for Windows.
cc @PatrickLang @KnicKnic for a final call on that.

**Comment by michmike** [comment]
let's add these error codes as well and  i am good to LGTM after that.
have we run some tests to verify this works?
ERROR_BAD_NETPATH
53 (0x35)

ERROR_NETWORK_BUSY
54 (0x36)

ERROR_UNEXP_NET_ERR
59 (0x3B)

ERROR_BAD_DEV_TYPE
66 (0x42)

File: pkg/util/mount/mount_helper_windows.go [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+		underlyingError = pe.Err
+	case *os.LinkError:
+		underlyingError = pe.Err
+	case *os.SyscallError:
+		underlyingError = pe.Err
+	}
+
+	if ee, ok := underlyingError.(syscall.Errno); ok {
+		errno := int(ee)
+		if errno == ERROR_NETNAME_DELETED || errno == ERROR_NETWORK_ACCESS_DENIED || errno == ERROR_BAD_NET_NAME || errno == ERROR_LOGON_FAILURE {
```
Comment (michmike) [inline pkg/util/mount/mount_helper_windows.go]: also one more question. why is the check that already exists in Linux for underlyingError == syscall.ENOTCONN  not applicable on windows? 
i understand the need to check for additional error codes around ERROR_LOGON_FAILURE for example, but the linux checks should apply as well.

Comment (andyzhangx) [reply pkg/util/mount/mount_helper_windows.go]: hi @michmike this issue is discussed in another PR: https://github.com/kubernetes/kubernetes/pull/74625#issuecomment-469938248, that is: error code is different between Linux and Windows. E.g. on Linux, the SMB password incorrect is `syscall.EACCES` while on Windows, it's `ERROR_LOGON_FAILURE`, they are different error no

Comment (michmike) [reply pkg/util/mount/mount_helper_windows.go]: i agree @andyzhangx , but in Linux we are checking for more error codes than just syscall.EACCES

**Comment by andyzhangx** [comment]
I have added more error code check and squashed all commits, PTAL again.
In the code, I used an array to collect all known errors.

**Comment by michmike** [comment]
> I have added more error code check and squashed all commits, PTAL again.
> In the code, I used an array to collect all known errors.
> 
> Below are the errors we need to handle per windows team:
> 
> For SMB mounts, the typical errors for connectivity are 53 and 64.
> 
> 53 ERROR_BAD_NETPATH <--> 0xc00000be STATUS_BAD_NETWORK_PATH
> 64 ERROR_NETNAME_DELETED <--> 0xc00000c9 STATUS_NETWORK_NAME_DELETED
> 64 ERROR_NETNAME_DELETED <--> 0xc000013b STATUS_LOCAL_DISCONNECT
> 64 ERROR_NETNAME_DELETED <--> 0xc000013c STATUS_REMOTE_DISCONNECT
> 64 ERROR_NETNAME_DELETED <--> 0xc000020b STATUS_ADDRESS_CLOSED
> 64 ERROR_NETNAME_DELETED <--> 0xc000020c STATUS_CONNECTION_DISCONNECTED
> 64 ERROR_NETNAME_DELETED <--> 0xc000020d STATUS_CONNECTION_RESET
> 64 ERROR_NETNAME_DELETED <--> 0xc0000466 STATUS_SERVER_UNAVAILABLE
> 64 ERROR_NETNAME_DELETED <--> 0xc0000480 STATUS_SHARE_UNAVAILABLE
> 
> For incorrect password/logon failure:
> 1326 ERROR_LOGON_FAILURE <--> c000006d STATUS_LOGON_FAILURE
> 
> This is an error if there is another existing mapping using a different set of credentials:
> 1219 ERROR_SESSION_CREDENTIAL_CONFLICT <--> c0000195 STATUS_NETWORK_CREDENTIAL_CONFLICT
> 
> This indicates the share does not exist:
> 67 ERROR_BAD_NET_NAME <--> c00000cc STATUS_BAD_NETWORK_NAME

do all those errors map to the same one with 64 as the error code?

File: pkg/util/mount/mount_windows.go [hunk 5]
```diff
@@ -378,16 +378,17 @@ func getAllParentLinks(path string) ([]string, error) {
...
 		return []string{}, nil
+	} else if IsCorruptedMnt(pathErr) {
+		klog.Warningf("GetMountRefs found corrupted mount at %s, treating as unmounted path", windowsPath)
+		return []string{}, nil
 	} else if pathErr != nil {
-		return nil, fmt.Errorf("error checking path %s: %v", normalizeWindowsPath(pathname), pathErr)
+		return nil, fmt.Errorf("error checking path %s: %v", windowsPath, pathErr)
 	}
-	return []string{pathname}, nil
+	return []string{windowsPath}, nil
```
Comment (michmike) [inline pkg/util/mount/mount_windows.go]: in the past, we used to return the same path passed to the function. now we return the normalized path. is that ok?

**Review by michmike — APPROVED** [review]

**Comment by michmike** [comment]
i added some comments which you should resolve before removing the hold
/hold
/lgtm

**Comment by michmike** [comment]
pinging the sig-storage team to take a look at this as well

**Comment by msau42** [comment]
Are these all errors that when if encountered, the mount point could still be successfully unmounted and cleaned up?

To give some context, the unmount sequence is like:
1. Check if directory is a mount point <-- this is where the IsCorruptedMount check is done
2. If it is a mount, then call Unmount
3. If unmount was successful and the directory is no longer a mount point, remove the directory.

File: pkg/util/mount/mount_windows.go (hunk 5 above)
Comment (andyzhangx) [reply pkg/util/mount/mount_windows.go]: good catch, it should use the original path when return from `GetMountRef`, i have changed it back.

**Comment by andyzhangx** [comment]
> do all those errors map to the same one with 64 as the error code?

Partly correct, a lot of errors are mapping to 64, others are different error codes. @michmike 

> Are these all errors that when if encountered, the mount point could still be successfully unmounted and cleaned up?
To give some context, the unmount sequence is like:
Check if directory is a mount point <-- this is where the IsCorruptedMount check is done
If it is a mount, then call Unmount
If unmount was successful and the directory is no longer a mount point, remove the directory.

Yes, on Windows, all Unmount would be simply rmdir opertion, it will always succeed for those conditions(@msau42 ):
https://github.com/kubernetes/kubernetes/blob/01c9edf7fa587090458e03e3a10884817f5aff8d/pkg/util/mount/mount_windows.go#L148-L153

/hold cancel
/test pull-kubernetes-cross

**Review by michmike — APPROVED** [review]

**Comment by michmike** [comment]
@msau42 if this looks good to you as well, please approve and we will go through the motions of getting this approved for 1.14

**Comment by jingxu97** [comment]
I have a questions of what is considered as corrupted mount point? In what condition we should clean them up? For example, for error STATUS_SERVER_UNAVAILABLE, is that possible that server is just temporally unavailable, do we want to clean up the mount in this situation?

**Comment by jingxu97** [comment]
Talked with @msau42 and @saad-ali, for this PR, adding more error codes should be safe. If it is considered corrected mount point, it will move to the next step trying to unmount and then check mountpoint before removing files and directories. 

But the whole process of checking correpted mount point before trying to unmount and remove files could be simplified. I propose to call umount directly, if it fails, checks whether the path is a mount point or not, if not, delete the files and directories. Please see #75273
