### PR TITLE
fix get-kube authorization headers

### LINKED ISSUE #88367: Will download and extract kubernetes-test tarball(s) -  curl: (22) The requested URL returned error: 403
Many jobs are failing because of 
```console
 I0220 10:10:17.124] Will download and extract kubernetes-test tarball(s) from https://storage.googleapis.com/kubernetes-release-dev/ci/v1.19.0-alpha.0.64+937008e3aca75c
I0220 10:10:17.124] https://www.googleapis.com/auth/cloud-platform
W0220 10:10:17.225]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
W0220 10:10:17.225]                                  Dload  Upload   Total   Spent    Left  Speed
W0220 10:10:17.328] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
W0220 10:10:17.328] curl: (22) The requested URL returned error: 403 
```

Some of the job logs:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1230434368032346114
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1230434368032346114
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1230440661795213312#1:build-log.txt%3A205
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1230420526376161281#1:build-log.txt%3A161

/priority critical-urgent
/cc @kubernetes/ci-signal 
/cc @justaugustus @alejandrox1 @kubernetes/release-managers 
/milestone v1.18

/sig release

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/88367

**Special notes for your reviewer**:

I kinda hope users are not using get-kube.sh, but technically it is still a release artifact AFAIK.

There are many other uses of the old pattern, but these all appear to be _on the e2e nodes_ instead of the CI cluster or local workstation.

This change only applies to usage with GCE / GKE set as the provider, in which case gcloud must be installed anyhow. This defers to gcloud to determine which account to use.

**Does this PR introduce a user-facing change?**:

```release-note
get-kube.sh uses the gcloud's current local GCP service account for auth when the provider is GCE or GKE instead of the metadata server default
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cluster/get-kube-binaries.sh [hunk 1]
```diff
@@ -168,8 +157,8 @@ function download_tarball() {
     # if the url belongs to GCS API we should use oauth2_token in the headers
     curl_headers=""
     if { [[ "${KUBERNETES_PROVIDER:-gce}" == "gce" ]] || [[ "${KUBERNETES_PROVIDER}" == "gke" ]] ; } &&
-       [[ "$url" =~ ^https://storage.googleapis.com.* ]] && valid-storage-scope ; then
```
Comment (BenTheElder) [inline cluster/get-kube-binaries.sh]: I don't think we ever needed the valid-storage-scope check, if the SA doesn't have scope then we pass no auth, so the resource must be public read ...?

This could (?) bite us later, but only for non-public resources (security patch testing?), if it does I expect to have fun figuring out a follow up with @krzyzacy ;-)

We should not be using the metadata server for this.

Comment (fejta) [reply cluster/get-kube-binaries.sh]: (if and only if you enable workload identity then the metadata server is part of the pod and it is safe to use)

Otherwise this makes jobs non-portable as they have implicit dependencies on the details of the node the pod gets scheduled on (which we do not want).

**Review by fejta — COMMENTED** [review]
thanks so much!
/lgtm
/approve

File: cluster/get-kube-binaries.sh (hunk 1 above)
Comment (BenTheElder) [reply cluster/get-kube-binaries.sh]: the previous check asked if the default SA for the metadata server had storage scopes before passing the auth header, if it doesn't it passes no headers.

I'm not sure that makes sense regardless of workload identity. That would mean you would get an error about not being authenticated instead of an error about the auth not having IAM permission.

I'm not sure this ever made sense.

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88383/pull-kubernetes-e2e-gce/1230657352529612801/
[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted expand_less | 1m51s
-- | --
test/e2e/storage/testsuites/subpath.go:439 Feb 21 01:32:49.710: while waiting for pod to be running Unexpected error:     <*errors.errorString \| 0xc000303d20>: {         s: "pod ran to completion",     }     pod ran to completion occurred test/e2e/storage/testsuites/subpath.go:458


/retest

**Comment by droslean** [comment]
@BenTheElder Shall we cherry-pick this in `release-1.17` branch?

**Comment by spiffxp** [comment]
I've opened cherry picks to the previous three release branches
- https://github.com/kubernetes/kubernetes/pull/88497
- https://github.com/kubernetes/kubernetes/pull/88498
- https://github.com/kubernetes/kubernetes/pull/88499
