### PR TITLE
kubelet waits for node lister to sync at least once

### LINKED ISSUE #92067: Kubernetes scheduler spams cluster with pods in NodeAffinity status
**What happened**:

A deployment is created that uses a `nodeSelector` after the cluster master is created but before the cluster worker nodes are fully initialized.  During the initialization of the worker nodes, the nodes are temporarily available for scheduling without the necessary label to match the deployment's node selector.  Depending on how long the nodes are available for scheduling without the necessary node labels for the deployment, the scheduler will start to spam with cluster with pods in `NodeAffinity` status.  This spamming stops once the worker nodes are fully initialized and the pods are scheduled successful.  The exact timing of all of this is TBD.

**What you expected to happen**:

Pods in `NodeAffinity` status are annoying and require manual cleanup.  It would be preferred that the scheduler avoid this an simply issue warning events.

**How to reproduce it (as minimally and precisely as possible)**:

See issue description.

**Anything else we need to know?**: No.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration: IBM Cloud Kubernetes Service
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): 4.15.0-96-generic
- Install tools: Managed service install
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If node has a kube client, it will wait to ensure the node lister has synced at least once before trusting its data.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/92067

**Special notes for your reviewer**:
still under discussion where to best wait (in getter, or in main kubelet startup)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@sjenning idea is to do similar as seen here, just need to work out pro/con for where we wait for node lister to sync at least once.

**Comment by derekwaynecarr** [comment]
after following up with @deads2k seems like it would be a good time to move away from list/watch and to a node informer with filter, then we can just use regular HasSynced function.  will iterate, just trying to determine the best location to wait for the node informer to sync at least once and not cause issues (do not want to do it in the kubelet_getters if possible)

**Comment by sjenning** [comment]
this might also fix https://github.com/kubernetes/kubernetes/issues/93338

**Comment by derekwaynecarr** [comment]
@sjenning take a look, the idea is to move the predicate function to call GetNode, which if we have a kubeclient ensures we synced the node lister at least once (otherwise, it errors).  I am still trying to think through an edge case for the scheduler scenario that we may miss, but this would ensure that we do not fall back to the kubelet "initialNode" and stop tripping up scheduler.

File: pkg/kubelet/kubelet_getters.go [hunk 1]
```diff
@@ -245,7 +256,7 @@ func (kl *Kubelet) GetNode() (*v1.Node, error) {
 // zero capacity, and the default labels.
 func (kl *Kubelet) getNodeAnyWay() (*v1.Node, error) {
 	if kl.kubeClient != nil {
-		if n, err := kl.nodeLister.Get(string(kl.nodeName)); err == nil {
+		if n, err := kl.GetNode(); err == nil {
```
Comment (sjenning) [inline pkg/kubelet/kubelet_getters.go:259]: pretty sure this whole function collapses to just `return kl.GetNode()` since `GetNode()` contains the standalone logic

File: pkg/kubelet/kubelet_getters.go [hunk 2]
```diff
@@ -235,6 +237,15 @@ func (kl *Kubelet) GetNode() (*v1.Node, error) {
 	if kl.kubeClient == nil {
 		return kl.initialNode(context.TODO())
 	}
+	// if we have a valid kube client, we wait up to 5s for initial lister to sync
+	if !kl.nodeHasSynced() {
+		err := wait.PollImmediate(time.Second, 5*time.Second, func() (bool, error) {
```
Comment (deads2k) [inline pkg/kubelet/kubelet_getters.go:242]: choose a weird number so we can find this later if it comes up. How about 8 seconds

File: pkg/kubelet/kubelet_getters.go (hunk 1 above)
Comment (derekwaynecarr) [reply pkg/kubelet/kubelet_getters.go:259]: GetNode does not guarantee a response in case where kubeclient is not nil, whereas getNodeAnyway does (it falls back to initial node).

**Comment by cwdsuzhou** [comment]
Hi we have run into the same issue and open this pr https://github.com/kubernetes/kubernetes/pull/95824

seems similar with this one.


I have a question that why not use cache.WaitForCacheSynced.

**Comment by alculquicondor** [comment]
/priority critical-urgent

What is this missing to not be a WIP?

**Comment by liggitt** [comment]
Kubelets dropping the beta OS/Arch labels on registration in https://github.com/kubernetes/kubernetes/pull/91046 made this issue much more common. I think we should re-enable kubelets self-adding the beta labels in 1.19/1.20 to preserve the bring-up characteristics of nodes and deployments/daemonsets targeting well-known labels, then try to land this in 1.21. Opened https://github.com/kubernetes/kubernetes/pull/96810 to do that

**Comment by alculquicondor** [comment]
Can this be prioritized?

Cherry-pick deadline for the 1.19, 1.18, and 1.17 branches is Friday, December 04, 2020 EOD PT.

**Comment by ehashman** [comment]
@liggitt I see #96810 was merged, is there anything left blocking this PR?

**Comment by derekwaynecarr** [comment]
i want to look at this again, i am still confused how a test that was red earlier went green without any clear change on my part.

**Comment by alculquicondor** [comment]
Could it have been #96810?
Or is the test using other labels?

**Comment by ehashman** [comment]
/retitle kubelet waits for node lister to sync at least once
/hold

talked to Derek about this, it's not really a WIP but the tests were previously failing. I'm going to look into why they turned green and see if we can get this merged

**Comment by ehashman** [comment]
Me and @troy0820 have reviewed this in depth, I am comfortable with this change assuming tests pass. There's no test history available so we can't confirm why this was previously failing or if @liggitt's PR is the reason things turned green.

@derekwaynecarr I'm going to remove the hold but I'll watch for failures on the retest.

/lgtm
/hold cancel

**Comment by liggitt** [comment]
> There's no test history available so we can't confirm why this was previously failing or if @liggitt's PR is the reason things turned green.

You could run the tests against a combination of this PR and a revert of https://github.com/kubernetes/kubernetes/pull/96810 if you wanted to verify this addressed the issue

**Comment by ehashman** [comment]
/hold

I'll throw up a PR to try that

**Comment by ehashman** [comment]
@liggitt thus far I've been unable to reproduce any failures with #96810 reverted on #97931, I'm retesting a third time

**Comment by derekwaynecarr** [comment]
i am fine removing my own hold on this as its possible what i saw was related to another unreliable aspect of CI at that time.

/hold cancel

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -431,14 +434,31 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
...
+		kubeInformers := informers.NewSharedInformerFactoryWithOptions(kubeDeps.KubeClient, 0, informers.WithTweakListOptions(func(options *metav1.ListOptions) {
+			options.FieldSelector = fields.Set{api.ObjectNameField: string(nodeName)}.String()
+		}))
+		nodeLister = kubeInformers.Core().V1().Nodes().Lister()
+		nodeHasSynced = func() bool {
+			if kubeInformers.Core().V1().Nodes().Informer().HasSynced() {
+				klog.Infof("kubelet nodes sync")
+				return true
+			}
+			klog.Infof("kubelet nodes not sync")
```
Comment (neolit123) [inline pkg/kubelet/kubelet.go:450]: this message is posted *a lot* in the logs, i think it can be omitted.

File: pkg/kubelet/kubelet_getters.go [hunk 4]
```diff
@@ -235,6 +237,15 @@ func (kl *Kubelet) GetNode() (*v1.Node, error) {
...
 	}
+	// if we have a valid kube client, we wait for initial lister to sync
+	if !kl.nodeHasSynced() {
+		err := wait.PollImmediate(time.Second, maxWaitForAPIServerSync, func() (bool, error) {
+			return kl.nodeHasSynced(), nil
+		})
+		if err != nil {
+			return nil, fmt.Errorf("nodes have not yet been read at least once, cannot construct node object")
+		}
+	}
```
Comment (neolit123) [inline pkg/kubelet/kubelet_getters.go:248]: this poll is problematic.
GetNode is called in a loop, which means that the poll is present on each call.

the sequence looks like:
- GetNode()
  - Poll for nodeHasSynced()
  - Poll ....
- GetNode()
  - Poll for nodeHasSynced()
  - Poll ....

if there is a valid client, arguably the informer sync check should be outside of this loop.

**Comment by neolit123** [comment]
the Minikube maintainers (cc @medyagh) [found](https://github.com/kubernetes/kubeadm/issues/2395) that this change introduced a performance regression.
when client credentials are fed to a primary kubelet in a cluster (`--kubeconfig`), but there are no other nodes or an API server running yet (because this primary kubelet will boot it from a static pod), this blocks for extra ~40 seconds.

i can see the informer wait as something desired but i think the logic here can be improved.
cc @derekwaynecarr @deads2k @liggitt 

we also backported this change in the support skew and since we don't have direct performance tests, nobody saw it until now.

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (pacoxu) [reply pkg/kubelet/kubelet.go:450]: Line 447 `klog.Infof("kubelet nodes sync")` is removed in #98137

File: pkg/kubelet/kubelet_getters.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/kubelet/kubelet_getters.go:248]: Wouldn't it be enough to check `HasSynced` once before creating the Kubelet object?

Comment (neolit123) [reply pkg/kubelet/kubelet_getters.go:248]: it would only sync after the api server is up.

Comment (alculquicondor) [reply pkg/kubelet/kubelet_getters.go:248]: if the API server is down, there is nothing to sync. Am I missing something?

Comment (neolit123) [reply pkg/kubelet/kubelet_getters.go:248]: BTW we are discussion how to improve this in:
https://github.com/kubernetes/kubernetes/pull/99336

if the kubelet is managing the first server instance in the cluster as a static pod and if the HasSynced check is before the kubelet object creation this means for such a kubelet instance the single HasSynced check will always be false.

maybe that's what we want, given this is the first node in the cluster and there is no need to sync it.

for subsequent kubelets the check should pass.

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (neolit123) [reply pkg/kubelet/kubelet.go:450]: it's still present at HEAD:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L452

**Comment by snowplayfire** [comment]
If these pods are re-scheduled automatically,  can the problem be solved? @derekwaynecarr
