### PR TITLE
Apply pod restart policy to Containers that fail to start

### LINKED ISSUE #14491: Container failing to start isn't governed by pod's restart policy
If you create a pod with a restart policy of never, and you have a container that fails to start (e.g. you set its command to a nonexistent file), the Kubelet currently tries to restart it infinitely because the container never started successfully, and therefore never received an exit code. You end up with something like this from Docker:

```
Cannot start container ebd101cfcd0b1aab572a184ece01a17ce081658114977bd6490cd6c78aff06e3: [8] System error: exec: "start": executable file not found in $PATH
```

Is it worth modifying the code to consider a container that failed to start as actually failed, so the pod's restart policy can govern it?

Originally reported at https://bugzilla.redhat.com/show_bug.cgi?id=1262753

@kubernetes/rh-cluster-infra @kubernetes/goog-node @smarterclayton @dchen1107

### PR DESCRIPTION
**Pull request by samsabed**
fixes #14491
restart (or not) docker containers, that don't start (e.g. due to bad command)
Also update the status manager to not delete the status if it's unable to update the apiserver

### CODE REVIEW

**Comment by yujuhong** [comment]
@samsabed, IIUC, the point of adding a `flushed` variable is so that we don't have delete the status when the update request fails. This sounds like a good idea, but seems unrelated to the "containers failed to start" issue. Could you split this into two PRs or at least two commits? That'd help if we ever need to revert, etc. Thanks!

File: pkg/kubelet/status/manager.go [hunk 1]
```diff
@@ -236,7 +241,9 @@ func (m *manager) syncBatch() error {
 		statusPod, err = m.kubeClient.Pods(pod.Namespace).UpdateStatus(statusPod)
 		if err == nil {
 			glog.V(3).Infof("Status for pod %q updated successfully", kubeletUtil.FormatPodName(pod))
-
+			if psInfo, ok := m.podStatusInfos[pod.UID]; ok {
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: You didn't acquire the lock and should not be modifying the map directly here. How about adding another method to flip the `flushed` bit?

File: pkg/kubelet/status/manager.go [hunk 2]
```diff
@@ -38,14 +38,19 @@ type podStatusSyncRequest struct {
 	status api.PodStatus
 }
 
+type PodStatusInfo struct {
+	api.PodStatus
+	flushed bool
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: It'd be nice to have a comment describing what `flushed` indicates.

File: pkg/kubelet/dockertools/manager.go [hunk 3]
```diff
@@ -348,17 +348,25 @@ func (dm *DockerManager) inspectContainer(dockerID, containerName, tPath string,
 				}
 			}
 		}
-	} else if !inspectResult.State.FinishedAt.IsZero() {
+	} else if !inspectResult.State.FinishedAt.IsZero() || inspectResult.State.ExitCode != 0 {
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/manager.go]: could use a comment here to explain what the conditions are for.

**Comment by bgrant0607** [comment]
See also #14307

**Comment by dchen1107** [comment]
@samsabed could you please also take care of #14307 in this PR? 

Error reason is set at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L357

**Comment by samsabed** [comment]
@dchen1107 no problem, amended to handle it
@yujuhong I've removed the status update bit, I realized it wasn't needed for this a bit after submitting.

for a wrong command it looks like this ( the double Asterisk is not part of the output)
```
Name:                           loopy-xstss
Namespace:                      default
Image(s):                       nginx
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Tue, 06 Oct 2015 13:50:21 +1100
Labels:                         run=loopy
Status:                         Running <----
Reason:
Message:
IP:                             172.17.0.18
Replication Controllers:        loopy (1/1 replicas created)
Containers:
  loopy:
    Container ID:               docker://2bfee911b5560d73b0ed0a428173adc6f8837877b312ed040a64915812bcd95e
    Image:                      nginx
    Image ID:                   docker://cd3cf76a61eed2094db241cc47185d04320671b2e5db360baf5956aebdbdf82c
    State:                      Waiting  <----
      Reason:                   CrashLoopBackOff  <----
    Last Termination State:     Terminated  <----
      Reason:                   ContainerCannotRun <----
      Message:                  [8] System error: exec: "/crashy": stat /crashy: no such file or directory
      Exit Code:                -1
      Started:                  Tue, 06 Oct 2015 15:31:09 +1100
      Finished:                 Tue, 06 Oct 2015 15:31:09 +1100
    Ready:                      False
    Restart Count:              26
    Environment Variables:
```

_for a pod with a restartPolicy: Never_

```
Name:                           oneoff
Namespace:                      default
Image(s):                       nginx
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Tue, 06 Oct 2015 13:49:58 +1100
Labels:                         <none>
Status:                         Failed <----
Reason:
Message:
IP:                             172.17.0.17
Replication Controllers:        <none>
Containers:
  oneoff:
    Container ID:       docker://68499a448120d108da86eee5289533124c55ac9319c52322193c2cc431f3fdce
    Image:              nginx
    Image ID:           docker://cd3cf76a61eed2094db241cc47185d04320671b2e5db360baf5956aebdbdf82c
    State:              Terminated
      Reason:           ContainerCannotRun   <----
      Message:          [8] System error: exec: "/missing": stat /missing: no such file or directory
      Exit Code:        -1
      Started:          Tue, 06 Oct 2015 13:49:59 +1100
      Finished:         Tue, 06 Oct 2015 13:49:59 +1100
    Ready:              False
    Restart Count:      0
    Environment Variables:
```

_for a pod with a container that finishes _ as in #14307 
```
Name:                           succeeder
Namespace:                      default
Image(s):                       centos:centos7
Node:                           127.0.0.1/127.0.0.1
Start Time:                     Tue, 06 Oct 2015 13:49:42 +1100
Labels:                         <none>
Status:                         Succeeded    <----
Reason:
Message:
IP:
Replication Controllers:        <none>
Containers:
  c:
    Container ID:       docker://644b964e8e6058a39f5c25484988fd23ae27113ec78524b79f519393a45a82bd
    Image:              centos:centos7
    Image ID:           docker://0f73ae75014f435e279d85ad31edc67e46c4a5d692b61840ff51e9d05f3b01ec
    State:              Terminated     <----
      Reason:          Completed   <----
      Exit Code:        0
      Started:          Tue, 06 Oct 2015 13:49:43 +1100
      Finished:         Tue, 06 Oct 2015 13:49:43 +1100
    Ready:              False
    Restart Count:      0
    Environment Variables:
```

**Comment by yujuhong** [comment]
Sorry just found one loose end. @samsabed, could you delete the code in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L380 since it no longer applies? Thanks.

**Comment by dchen1107** [comment]
Yes, docker/docker/#8294 was fixed for recorded Start Error was fixed a while back.

**Comment by samsabed** [comment]
yeah, I thought it would be a good visible indicator for a docker state that is not being handled. The image pull backoff PR should make the reason "ContainerCreating"

**Comment by samsabed** [comment]
... I've removed it as suggested
