### PR TITLE
kubelet: Pods that have terminated before starting should not block startup

### LINKED ISSUE #107733: Some static pods fail to start on K8S 1.23
### What happened?

In Kubernetes 1.23 we are seeing some static pods fail to start. These static pods failures are on quick remove and adds leaving the static pod not started.

We need to revert kubernetes/kubernetes#104743.

cc @gjkim42 

### What did you expect to happen?

All static pods should restart.

### How can we reproduce it (as minimally and precisely as possible)?

```diff
diff --git a/pkg/kubelet/pod_workers_test.go b/pkg/kubelet/pod_workers_test.go
index 4028c06c292..0e852594a40 100644
--- a/pkg/kubelet/pod_workers_test.go
+++ b/pkg/kubelet/pod_workers_test.go
@@ -880,3 +880,34 @@ func Test_allowPodStart(t *testing.T) {
 		})
 	}
 }
+
+func TestUpdatePodWithQuickAddRemoveStaticPod(t *testing.T) {
+	podWorkers, _ := createPodWorkers()
+	staticPodA := newStaticPod("0000-0000-0000", "running-static-pod")
+	staticPodB := newStaticPod("0000-0000-0000", "running-static-pod")
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodA,
+		UpdateType: kubetypes.SyncPodCreate,
+	})
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodA,
+		UpdateType: kubetypes.SyncPodKill,
+	})
+
+	drainAllWorkers(podWorkers)
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodB,
+		UpdateType: kubetypes.SyncPodCreate,
+	})
+
+	drainAllWorkers(podWorkers)
+
+	t.Logf("rphillips waitingToStartStaticPodsByFullName=%v", podWorkers.waitingToStartStaticPodsByFullname)
+	if status, ok := podWorkers.podSyncStatuses["0000-0000-0000"]; ok {
+		t.Logf("rphillips podSyncStatuses=%+v", status)
+	}
+	t.Logf("rphillips startedStaticPodsByFullname=%v", podWorkers.startedStaticPodsByFullname)
+}
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
1.23
</details>

### Cloud provider

<details>
All
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by smarterclayton**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When a pod terminates before it can be started (which only applies to static pods today), it blocks other static pod changes for that namespace/name that arrive later. We must ignore terminated pods when we identify the next start candidate, and we must also ensure that a pod worker waiting to start does not wait if the pod is deleted.

Update `allowPodStart` to return a second boolean indicating whether the pod can ever start, and if not the loop should exit.

Add a more thorough set of unit tests around unique pods.

#### Which issue(s) this PR fixes:

Fixes #107733

Builds on #107854, supercedes #107734

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.22 regression where a static pod that is rapidly updated was failing to start until the Kubelet was restarted.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/pod_workers_test.go [hunk 1]
```diff
@@ -427,6 +522,473 @@ func TestUpdatePodDoesNotForgetSyncPodKill(t *testing.T) {
...
+	drainAllWorkers(podWorkers)
+
+	// expect sync to put 3-static into final state and remove the status
+	if e, a := map[types.UID]PodWorkerState{
+		"1-normal": SyncPod,
+		"2-static": TerminatedPod,
+		"3-static": TerminatedPod,
+		"4-static": SyncPod,
+	}, state; !reflect.DeepEqual(e, a) {
+		t.Fatalf("unexpected actual state: %s", diff.ObjectReflectDiff(e, a))
```
Comment (gjkim42) [inline pkg/kubelet/pod_workers_test.go:761]: https://pkg.go.dev/k8s.io/apimachinery/pkg/util/diff#ObjectReflectDiff

We can use github.com/google/go-cmp/cmp, as this has been deprecated.

File: pkg/kubelet/pod_workers_test.go [hunk 2]
```diff
@@ -870,13 +1565,37 @@ func Test_allowPodStart(t *testing.T) {
 			if tc.waitingToStartStaticPodsByFullname != nil {
 				podWorkers.waitingToStartStaticPodsByFullname = tc.waitingToStartStaticPodsByFullname
 			}
-			if podWorkers.allowPodStart(tc.pod) != tc.allowed {
+			if allowed, _ := podWorkers.allowPodStart(tc.pod); allowed != tc.allowed {
```
Comment (gjkim42) [inline pkg/kubelet/pod_workers_test.go:1568]: I think we need to check canEverStart as well in here.

**Review by gjkim42 — COMMENTED** [review]
/triage accepted

`completeUnstartedTerminated` at pod worker itself looks more sense to me as well.

**Review by gjkim42 — COMMENTED** [review]
lgtm

/hold
(to not be merged accidentally without node reviewers)

**Comment by smarterclayton** [comment]
Integrated review comments.  I added two test conditions to test_allowPodStart that cover terminated pods and pods without sync status (both of which are "the pod worker must exit right away")

**Comment by smarterclayton** [comment]
/priority critical-urgent

Since this breaks static pod updates

**Comment by rphillips** [comment]
I successfully tested this PR within OpenShift CI and bench tested it. This issue is fixed with this code change.

**Comment by rphillips** [comment]
lgtm... I'll defer the final lgtm and unhold to @ehashman

File: pkg/kubelet/pod_workers.go [hunk 3]
```diff
@@ -1066,6 +1086,33 @@ func (p *podWorkers) completeTerminated(pod *v1.Pod) {
 	}
 }
 
+// completeUnstartedTerminated is invoked if a pod that has never been started receives a termination
+// signal before it can be started.
+func (p *podWorkers) completeUnstartedTerminated(pod *v1.Pod) {
+	p.podLock.Lock()
+	defer p.podLock.Unlock()
+
+	klog.V(4).InfoS("Pod never started and the worker can now stop", "pod", klog.KObj(pod), "podUID", pod.UID)
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:1095]: Do we want this to be hidden at V=4? I feel like this might be worth logging at V=2 since it's unlikely to be a common thing.

**Review by ehashman — COMMENTED** [review]
/lgtm
/hold cancel

File: pkg/kubelet/pod_workers.go (hunk 3 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:1095]: Hrm.  If all the others weren't 4 i would agree.  I think it might be useful to come back and add some of this at v3 for better insight into pod lifecycle in logs on later review.
