### PR TITLE
Fix hyperkube flag parsing

### LINKED ISSUE #24088: hyperkube + kubectl - unknown flag
When trying to use kubectl from hyperkube I'm met with "unknown flag" errors. It looks as if the flags aren't being passed through to kubectl but hyperkube is trying to handle them itself (and subsequently giving an error when you give it flags it doesn't understand).

You can reproduce simply by running:

```
docker run -it gcr.io/google_containers/hyperkube-amd64:v1.2.2 /hyperkube kubectl create -f x
```

And you'll see the error:
```
Error: unknown shorthand flag: 'f' in -f

Kubernetes command line client

Usage:
  Kubernetes command line client [flags]

Available Flags:
..
..
..
```

### PR DESCRIPTION
**Pull request by colhom**
Hyperkube flag parsing was not playing nicely with kubectl command and sub-commands. This PR addresses that problem, and adds some tests which exercise hyperkube dispatching to nested cobra commands.

\cc @aaronlevy @kbrwn @mumoshu

fixes #24088

[Analytics]()

### CODE REVIEW

**Comment by colhom** [comment]
@k8s-bot I signed it!

**Comment by thockin** [comment]
I'm assigning to to Mike semi-randomly

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
See also #22737

cc @ingvagabund

**Comment by ingvagabund** [comment]
@colhom I am definitely +1 for the hyperkube_test.go.

File: cmd/hyperkube/hyperkube.go [hunk 1]
```diff
@@ -123,8 +123,8 @@ func (hk *HyperKube) Run(args []string) error {
 	command := args[0]
 	baseCommand := path.Base(command)
 	serverName := baseCommand
+	args = args[1:]
 	if serverName == hk.Name {
-		args = args[1:]
```
Comment (ingvagabund) [inline cmd/hyperkube/hyperkube.go]: As long as you run ``hyperkube kubectl``, this should not matter. Why movin 2 lines higher?

File: cmd/hyperkube/kubectl.go [hunk 2]
```diff
@@ -19,21 +19,20 @@ package main
 import (
 	"os"
 
-	"k8s.io/kubernetes/cmd/kubectl/app"
+	"k8s.io/kubernetes/pkg/kubectl/cmd"
+	cmdutil "k8s.io/kubernetes/pkg/kubectl/cmd/util"
 )
 
 func NewKubectlServer() *Server {
+	cmd := cmd.NewKubectlCommand(cmdutil.NewFactory(nil), os.Stdin, os.Stdout, os.Stderr)
```
Comment (ingvagabund) [inline cmd/hyperkube/kubectl.go]: So far hyperkube has always collected cmds from ``k8s.io/kubernetes/cmd`` as it adds another layer between ``k8s.io/kubernetes/pkg`` and ``k8s.io/kubernetes/cmd/hyperkube``.  Calling ``cmd.NewKubectlCommand`` right here is against that. Not sure, if it really matters. Still, I see the additional layer as a useful assumption when debugging hyperkube. At the same time the common pattern of defining ``Server.Run`` (as bellow) is to delegate the call to another ``app.Run``.

File: cmd/hyperkube/hyperkube.go (hunk 1 above)
Comment (jbeda) [inline cmd/hyperkube/hyperkube.go]: This looks to perhaps break things when you softlink `kubectl` to the `hyperkube` binary.  Have you tested that?

File: cmd/hyperkube/hyperkube.go [hunk 3]
```diff
@@ -162,7 +162,7 @@ func (hk *HyperKube) Run(args []string) error {
 		hk.Usage()
 		return err
 	}
-
+	s.Flags().SetInterspersed(false)
```
Comment (jbeda) [inline cmd/hyperkube/hyperkube.go]: This is a behavior change.  Some of the servers may want to allow for interspersed flags.  No reason to slam the preference here.

File: cmd/hyperkube/hyperkube.go (hunk 1 above)
Comment (ingvagabund) [inline cmd/hyperkube/hyperkube.go]: +1

File: cmd/hyperkube/kubectl.go [hunk 4]
```diff
@@ -19,21 +19,20 @@ package main
...
 		SimpleUsage: "Kubernetes command line client",
 		Long:        "Kubernetes command line client",
 		Run: func(s *Server, args []string) error {
-			os.Args = os.Args[1:]
-			if err := app.Run(); err != nil {
-				os.Exit(1)
-			}
-			os.Exit(0)
-			return nil
+			cmd.SetArgs(args)
```
Comment (jbeda) [inline cmd/hyperkube/kubectl.go]: if we don't muck with args above, this should be args[1:]

File: cmd/hyperkube/kubectl.go (hunk 2 above)
Comment (jbeda) [inline cmd/hyperkube/kubectl.go]: I'm okay with skipping `k8s.io/kubernetes/cmd/kubectl` as long as we put a big comment in there that any significant changes need to be duplicated here.  At some point hopefully we can finish the hyperkube transition and hyperkube will be the *only* way to get at this stuff.  Until the, we need to keep stuff in sync.

**Comment by jbeda** [comment]
I'm in favor of integrating this with the cobra command structure (I looked at it originally but found it a forced fit) but we need to make sure we don't change behavior of existing commands.  Also, need to make sure we don't get divergent implementations between the `hyperkube` version and the stand along version of `kubectl`.

File: cmd/hyperkube/hyperkube.go (hunk 1 above)
Comment (colhom) [inline cmd/hyperkube/hyperkube.go]: Ironically enough, this was actually a fix to make softlinking work better :) I've tested it.

There's no reason to pass the command arg to any of the Server Run blocks . In particular, since `kubectl` is now a Cobra command, it requires that if `args[0]` is not a flag, it match the command name exactly. In the case of a softlink, it's possible thats `args[0]` will be for example `/usr/bin/kubectl`, and the Cobra command will complain. This removes that possibility.

File: cmd/hyperkube/kubectl.go (hunk 4 above)
Comment (colhom) [inline cmd/hyperkube/kubectl.go]: Depending on whether or not it's a softlink (`os.Args[0] == "hyperkube"`), it's either `os.Args[1:]` or `os.Args[2:]`. It's kind of nice to let the hyperkube server deal with that logic and sub-servers can just assume that their args list starts with the first relevant flag. This would easily support, for example, nesting servers in servers.

File: cmd/hyperkube/hyperkube.go (hunk 3 above)
Comment (colhom) [inline cmd/hyperkube/hyperkube.go]: Agreed- this is something the servers should decide for themselves. Addressed in 09e3d0913a53e342ea4dbb563cf0788d8b5a5756

File: cmd/hyperkube/kubectl.go (hunk 2 above)
Comment (colhom) [inline cmd/hyperkube/kubectl.go]: addressed in followup commit.

File: cmd/hyperkube/hyperkube.go (hunk 1 above)
Comment (jbeda) [inline cmd/hyperkube/hyperkube.go]: Ah!  Looking at the documentation for [`pflags.FlagSet.Parse`](https://godoc.org/github.com/spf13/pflag#FlagSet.Parse) it looks like the args should *not* contain the command name.  That would imply that we were doing it wrong before when the command name was being included.  `interspersed` defaulting to `true` must have covered our sins.

**Comment by jbeda** [comment]
Looks good to me. 

@ingvagabund, what are your thoughts?

Honestly, I lean toward merging both changes.  The cobra stuff does enough fancy flag parsing that it makes sense to let it do it.  It is a decent service for the rest of the servers.

Also, we need to figure out what is going on with the CLA for @colhom.  I think you need to respond with `I signed it!` without any other text.  Apparently the googlebot is picky.

**Comment by colhom** [comment]
I signed it!

File: cmd/hyperkube/hyperkube.go (hunk 1 above)
Comment (colhom) [inline cmd/hyperkube/hyperkube.go]: Yep, that's very true!

**Comment by colhom** [comment]
@jbeda @ingvagabund I see no advantage to introducing a mechanism to disable flag parsing for servers in general, or for kubectl in particular. It adds even more complexity to `hyperkube` flag parsing behavior, and we already know how to make nested Cobra commands work without bypassing hyperkube flag parsing. 

Going forward it's going to be detrimental as well. Using a  server with `ParseArgs=false`, you won't be able to provide any flags options to the hyperkube server itself.

`hyperkube --hyperkube-option=value kubectl version` will result in `hyperkube-option` flag being silently ignored, as hyperkube won't parse it's own flags. If we insist hyperkube always parse it's own flags, this won't be an issue. I believe this is how this whole system is "supposed to work".

**Comment by jbeda** [comment]
First, looks like the googlebot is broken wrt CLA.  @bgrant0607 @thockin -- hate to bug you guys but any ideas on who can debug that and/or confirm the CLA manually?

Second, hyperkube specific options will be parsed in the non-symlink case.  The example you have there *should* work.  (Not that we don't have many of these options now and I question `--make-symlinks` being an option vs. a command)

Third, I see where you are coming from but the interaction here is really pretty subtle.  The flag parsing in hyperkube was really done as a way to consolidate boilerplate from multiple servers.  With cobra based hierarchies we don't need that.  In fact, sub-commands will be parsed by cobra while the root will be parsed by hk.

Also, as I've been looking at the code, I end up with one more question -- why are you calling `SetInterspersed(false)`?  This isn't the default for cobra and I can't see it set anywhere in kubectl.

Personally, I could go either way here.  @ingvagabund -- do you have opinions here?  If not, I'm leaning toward going with @colhom's version as we can always add the "don't parse" stuff later if we need it.

**Comment by bgrant0607** [comment]
@colhom Did you provide your github ID when signing the CLA? You're not in the database.

**Comment by ingvagabund** [comment]
@jbeda @colhom I like the cobra way. The ``ParseArgs=false`` was a "least evil" hack to make kubectl work when symlinked to hyperkube.

@colhom, you are right about the hyperkube commands. Let's take the cobra way and see how well it is going to work.

**Comment by colhom** [comment]
@bgrant0607 The site says that I'm covered by the CoreOS corporate agreement. I think I need to set the git commit email address to my coreos.com email address in order for that to take effect.

**Comment by colhom** [comment]
@jbeda kubectl is the only server which has sub-commands, and hence the only flagset which needs to stop parsing once the first non-flag arg is encountered. That is currently not configured in master. 

All the other binaries aren't passed any sub-commands, so interspersed parsing is fine. Any non-flag arguments interspersed in the args list are simply be ignored. (The [default](https://github.com/spf13/pflag/blob/master/flag.go#L912) is interspersed)

**Comment by jbeda** [comment]
@colhom To be clear, this is a change for from the standalone `kubectl` as the standalone parses flags without having interspersed parsing.  However, it ends up being a no-op as base kubectl has no "local" flags so all flags get inherited down.  If it did have local flags there'd be breakage here.

I'm pretty sure we don't need to muck with "interspersed" at all.  By the time that flagset is parsed, all of the hyperkube stuff should be stripped of the front of the arg list.

Again, though, I can't see it doing any harm, right now.

**Comment by jbeda** [comment]
Marking `cla: human-approved` as @colhom works for CoreOS.  Not sure how to have googlebot know this, though.

**Comment by jbeda** [comment]
Not worth pushing it.  Marking LGTM.

**Comment by mikedanese** [comment]
This needs a squash

**Comment by colhom** [comment]
squashed up.

**Comment by jbeda** [comment]
@k8s-bot test this github issue: #25629

**Comment by luxas** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by ArtfulCoder** [comment]
@k8s-bot test this github issue:#22655

**Comment by ArtfulCoder** [comment]
k8s-bot test this issue: #22655

**Comment by ArtfulCoder** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by colhom** [comment]
@ArtfulCoder could I get another `lgtm` label and a shot at the tests?

**Comment by jbeda** [comment]
I believe this is not merged because it isn't marked for 1.3.  @bgrant0607 -- what is the criteria/process for that?  I don't see it linked off of the 1.3 release wiki page or obvious from kubernetes-dev chatter.

**Comment by luxas** [comment]
@jbeda I added it to the v1.3 milestone.
This will be merged although it doesn't have the milestone attached to it, but having a milestone adds a little more priority to it
It's just waiting to be on the top of the queue

**Comment by jbeda** [comment]
Thanks @luxas!

**Comment by colhom** [comment]
@mikedanese what do you think about a cherrypick-candidate label?

**Comment by colhom** [comment]
\cc @jbeda

**Comment by roberthbailey** [comment]
@colhom I assume you are asking about cherry picking into 1.2 (and that the 1.3 milestone was added to get through the submit queue). Is that correct?

**Comment by colhom** [comment]
@roberthbailey that is correct.

**Comment by roberthbailey** [comment]
@colhom I've adjusted the milestone label to indicate where you want it cherry picked to. Please send a cherry pick PR for the 1.2 release branch.

**Comment by colhom** [comment]
@roberthbailey cherry pick PR is up: #26754

**Comment by roberthbailey** [comment]
This was cherrypicked into 1.2 in https://github.com/kubernetes/kubernetes/pull/26754. Manually removing the cherrypick candidate label.
