### PR TITLE
kubeadm: make kubeadm init and join output the same error

### LINKED ISSUE #3149: Make kubeadm init and join output the same error after failing to wait for control plane components
Currently, during `kubeadm init`, if waiting for the control plane components to start fails, we output a templated error message.
Ref: https://github.com/kubernetes/kubernetes/blob/50fc400f178d2078d0ca46aee955ee26375fc437/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go#L39-L58

However, during `kubeadm join`, if waiting for the control plane components to start fails, we output a raw error message.
Ref: https://github.com/kubernetes/kubernetes/blob/50fc400f178d2078d0ca46aee955ee26375fc437/cmd/kubeadm/app/cmd/phases/join/waitcontrolplane.go#L73-L77

We aim to ensure that `kubeadm init` and `kubeadm join` output the same error message format when waiting for the control plane components to start fails.

This can be implemented after the merge of https://github.com/kubernetes/kubernetes/pull/129620.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently, during kubeadm init, if waiting for the control plane components to start fails, we output a templated error message.

However, during kubeadm join, if waiting for the control plane components to start fails, we output a raw error message.

This PR aim to ensure that kubeadm init and kubeadm join output the same error message format when waiting for the control plane components to start fails.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3149

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: improved `kubeadm init` and `kubeadm join` to provide consistent error messages when the kubelet failed or when failed to wait for control plane components.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
After this PR, kubeadm init will throw the following error:
```
[kubelet-check] The kubelet is healthy after 502.472315ms

Unfortunately, an error has occurred:
	error

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'


	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.
	Here is one example how you may list all running Kubernetes containers by using crictl:
		- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: could not initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

```

After this PR, kubeadm join will throw the following error:

```
[kubelet-check] The kubelet is healthy after 501.697408ms

Unfortunately, an error has occurred:
	error

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
error execution phase kubelet-wait-bootstrap: could not join the node to the Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
```

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go [hunk 1]
```diff
@@ -102,27 +79,15 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
...
-
 	waiter.SetTimeout(data.Cfg().Timeouts.KubeletHealthCheck.Duration)
 	kubeletConfig := data.Cfg().ClusterConfiguration.ComponentConfigs[componentconfigs.KubeletGroup].Get()
 	kubeletConfigTyped, ok := kubeletConfig.(*kubeletconfig.KubeletConfiguration)
 	if !ok {
 		return errors.New("could not convert the KubeletConfiguration to a typed object")
 	}
 	if err := waiter.WaitForKubelet(kubeletConfigTyped.HealthzBindAddress, *kubeletConfigTyped.HealthzPort); err != nil {
-		return handleError(err)
+		kubelet.HandleKubeletFailError(err, data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, true)
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:89]: we should stop passing that err to this function

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go [hunk 2]
```diff
@@ -102,27 +79,15 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
...
+		return errors.New("could not initialize a Kubernetes cluster")
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:90]: in all places we should:
`return errors.Wrap(err, "...some text")`

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 3]
```diff
@@ -18,13 +18,43 @@ package kubelet
...
 	kubeadmconstants "k8s.io/kubernetes/cmd/kubeadm/app/constants"
 	"k8s.io/kubernetes/cmd/kubeadm/app/util/initsystem"
 )
 
+var (
+	commonFailMsg = dedent.Dedent(`
+	Unfortunately, an error has occurred:
+		{{ .Error }}
+
+	This error is likely caused by:
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:36]:
```suggestion
	Unfortunately, an error has occurred, like caused by:
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 4]
```diff
@@ -45,6 +75,23 @@ func TryStartKubelet() {
...
+	context := struct {
+		Error  string
+		Socket string
+	}{
+		Error:  fmt.Sprintf("%v", err),
+		Socket: criSocket,
+	}
+
+	if controlPlan {
+		_ = controlPlanKubeletFailTempl.Execute(outputWriter, context)
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:89]: Here follow the previous behavior and do not handle the error returned by the `Execute` method.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 5]
```diff
@@ -45,6 +75,23 @@ func TryStartKubelet() {
 	}
 }
 
+// HandleKubeletFailError formats and writes an error message using the provided template.
+func HandleKubeletFailError(err error, outputWriter io.Writer, criSocket string, controlPlan bool) {
+	context := struct {
+		Error  string
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:81]:
```suggestion
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 6]
```diff
@@ -45,6 +75,23 @@ func TryStartKubelet() {
...
+		Socket string
+	}{
+		Error:  fmt.Sprintf("%v", err),
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:84]:
```suggestion
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 7]
```diff
@@ -45,6 +75,23 @@ func TryStartKubelet() {
 	}
 }
 
+// HandleKubeletFailError formats and writes an error message using the provided template.
+func HandleKubeletFailError(err error, outputWriter io.Writer, criSocket string, controlPlan bool) {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:79]:
```suggestion
// PrintKubeletErrorHelpScreen prints help text on kubelet errors.
func PrintKubeletErrorHelpScreen(err error, outputWriter io.Writer, criSocket string, controlPlane bool) {
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 8]
```diff
@@ -45,6 +75,23 @@ func TryStartKubelet() {
...
+	}{
+		Error:  fmt.Sprintf("%v", err),
+		Socket: criSocket,
+	}
+
+	if controlPlan {
+		_ = controlPlanKubeletFailTempl.Execute(outputWriter, context)
+	} else {
+		_ = commonKubeletFailTempl.Execute(outputWriter, context)
+	}
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:92]: this should be 
```suggestion
	fmt.Fprintln(outputWriter, commonFailMsg)
	if controlPlane {
		_ = controlPlanKubeletFailTempl.Execute(outputWriter, context)
	}
```

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @HirazawaUi 
here is how i think this old code should be refactored.

**Comment by neolit123** [comment]
please, always prefix notes with `kubeadm:` then small letter.
/release-note-edit

```release-note
kubeadm: improved `kubeadm init` and `kubeadm join` to provide consistent error messages when the kubelet failed or when failed to wait for control plane components.
```

**Comment by HirazawaUi** [comment]
All suggestions fixed.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 9]
```diff
@@ -18,13 +18,38 @@ package kubelet
...
+	Unfortunately, an error has occurred, like caused by:
+		- The kubelet is not running
+		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
+
+	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
+		- 'systemctl status kubelet'
+		- 'journalctl -xeu kubelet'
+`)
+
+	controlPlanKubeletFailTempl = template.Must(template.New("init").Parse(dedent.Dedent(`
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:42]:
```suggestion
	controlPlaneFailTempl = template.Must(template.New("init").Parse(dedent.Dedent(`
```

File: cmd/kubeadm/app/cmd/phases/join/waitcontrolplane.go [hunk 10]
```diff
@@ -80,7 +81,8 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
 	}
 	if err = waiter.WaitForControlPlaneComponents(pods,
 		data.Cfg().ControlPlane.LocalAPIEndpoint.AdvertiseAddress); err != nil {
-		return err
+		kubelet.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, true)
+		return errors.Wrap(err, "could not join the node to the Kubernetes cluster")
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/join/waitcontrolplane.go:85]:
```suggestion
		return errors.Wrap(err, "failed while waiting for the control plane to start")
```

File: cmd/kubeadm/app/cmd/phases/join/kubelet.go [hunk 11]
```diff
@@ -328,13 +312,13 @@ func runKubeletWaitBootstrapPhase(c workflow.RunData) (returnErr error) {
...
-			return err
+			kubeletphase.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, false)
+			return errors.Wrap(err, "could not join the node to the Kubernetes cluster")
 		}
 
 		if err := waitForTLSBootstrappedClient(cfg.Timeouts.TLSBootstrap.Duration); err != nil {
-			fmt.Printf(kubeadmJoinFailMsg, err)
-			return err
+			kubeletphase.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, false)
+			return errors.Wrap(err, "could not join the node to the Kubernetes cluster")
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/join/kubelet.go:321]:
```suggestion
			return errors.Wrap(err, "failed while waiting for TLS bootstrap")
```

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go [hunk 12]
```diff
@@ -102,27 +79,15 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
...
 	waiter.SetTimeout(data.Cfg().Timeouts.KubeletHealthCheck.Duration)
 	kubeletConfig := data.Cfg().ClusterConfiguration.ComponentConfigs[componentconfigs.KubeletGroup].Get()
 	kubeletConfigTyped, ok := kubeletConfig.(*kubeletconfig.KubeletConfiguration)
 	if !ok {
 		return errors.New("could not convert the KubeletConfiguration to a typed object")
 	}
 	if err := waiter.WaitForKubelet(kubeletConfigTyped.HealthzBindAddress, *kubeletConfigTyped.HealthzPort); err != nil {
-		return handleError(err)
+		kubelet.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, true)
+		return errors.Wrap(err, "could not initialize a Kubernetes cluster")
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:90]:
```suggestion
		return errors.Wrap(err, "failed while waiting for the kubelet to start")
```

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go [hunk 13]
```diff
@@ -138,7 +103,9 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
 		err = waiter.WaitForAPI()
 	}
 	if err != nil {
-		return handleError(err)
+		kubelet.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, true)
+		return errors.Wrap(err, "could not initialize a Kubernetes cluster")
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:107]:
```suggestion
		return errors.Wrap(err, "failed while waiting for the control plane to start")
```

**Comment by neolit123** [comment]
LGTM, mostly. should have a second reviewer too.

**Comment by neolit123** [comment]
ok, it would be nice to have another new line here:
```
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: failed while waiting for the kubelet to start: error
To see the stack trace of this error execute with --v=5 or higher
```

**Comment by neolit123** [comment]
> error execution phase wait-control-plane: failed while waiting for the kubelet to start: error

this dosn't seem correct, any idea why here is a trailing `: error`.

**Comment by HirazawaUi** [comment]
> this dosn't seem correct, any idea why here is a trailing `: error`.

This error string is an error I injected. :)


> ok, it would be nice to have another new line here:

Yes, I will debug and modify it further tomorrow.

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go [hunk 14]
```diff
@@ -102,27 +79,15 @@ func runWaitControlPlanePhase(c workflow.RunData) error {
...
 	waiter.SetTimeout(data.Cfg().Timeouts.KubeletHealthCheck.Duration)
 	kubeletConfig := data.Cfg().ClusterConfiguration.ComponentConfigs[componentconfigs.KubeletGroup].Get()
 	kubeletConfigTyped, ok := kubeletConfig.(*kubeletconfig.KubeletConfiguration)
 	if !ok {
 		return errors.New("could not convert the KubeletConfiguration to a typed object")
 	}
 	if err := waiter.WaitForKubelet(kubeletConfigTyped.HealthzBindAddress, *kubeletConfigTyped.HealthzPort); err != nil {
-		return handleError(err)
+		kubelet.PrintKubeletErrorHelpScreen(data.OutputWriter(), data.Cfg().NodeRegistration.CRISocket, true)
+		return errors.Wrap(err, "failed while waiting for the kubelet to start")
```
Comment (pacoxu) [inline cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:90]: The wrapped message use `kubelet`, but the printer is `controlPlane=true`.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 15]
```diff
@@ -45,6 +68,20 @@ func TryStartKubelet() {
...
+func PrintKubeletErrorHelpScreen(outputWriter io.Writer, criSocket string, controlPlane bool) {
+	context := struct {
+		Socket string
+	}{
+		Socket: criSocket,
+	}
+
+	fmt.Fprintln(outputWriter, kubeletFailMsg)
+	if controlPlane {
+		_ = controlPlaneFailTempl.Execute(outputWriter, context)
```
Comment (pacoxu) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:81]: We didn't print handle the error(probably print it) before. Not sure if we should do that.

**Review by pacoxu — COMMENTED** [review]
Overall LGTM. Only one nit.

File: cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go (hunk 14 above)
Comment (HirazawaUi) [reply cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:90]: Good catch!

Initially, I just wanted to use the `controlPlane` parameter to determine whether to display the full content of `kubeletFailTempl` as before. However, we can make it more granular:

* If kubelet fails to start, we should only display the kubelet startup failure error and guidance.
* If the failure occurs while waiting for `WaitForControlPlaneComponents`, we should display both the kubelet startup failure information and container troubleshooting logs.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go (hunk 15 above)
Comment (HirazawaUi) [reply cmd/kubeadm/app/phases/kubelet/kubelet.go:81]: In other parts of kubeadm, calls to the Execute method similarly do not return errors, so I chose to ignore the error here.

**Comment by HirazawaUi** [comment]
kubeadm init:
```
[kubelet-check] The kubelet is healthy after 501.458126ms

Unfortunately, an error has occurred, likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///run/containerd/containerd.sock logs CONTAINERID'

error execution phase wait-control-plane: failed while waiting for the kubelet to start: error message
To see the stack trace of this error execute with --v=5 or higher
```

kubeadm join:
```
[kubelet-check] The kubelet is healthy after 501.000436ms

Unfortunately, an error has occurred, likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

error execution phase kubelet-wait-bootstrap: failed while waiting for the kubelet to start: error message
To see the stack trace of this error execute with --v=5 or higher
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 16]
```diff
@@ -45,6 +68,21 @@ func TryStartKubelet() {
 	}
 }
 
+// PrintKubeletErrorHelpScreen prints help text on kubelet errors.
+func PrintKubeletErrorHelpScreen(outputWriter io.Writer, criSocket string, waitControlPlaneComponents bool) {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:72]: after some thinking let's split this func into two;
PrintKubeletErrorHelpScreen
PrintControlPlaneErrorHelpScreen

this is nicer than using the same function and having a flag waitControlPlaneComponents
also, when a control plane fails we already run the kubelet check earlier which passed. so the problem at that point seems like failing CP components, not failing kublet.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go [hunk 17]
```diff
@@ -18,13 +18,36 @@ package kubelet
...
+	Unfortunately, an error has occurred, likely caused by:
+		- The kubelet is not running
+		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
+
+	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
+		- 'systemctl status kubelet'
+		- 'journalctl -xeu kubelet'`)
+
+	controlPlaneFailTempl = template.Must(template.New("init").Parse(dedent.Dedent(`
+	Additionally, a control plane component may have crashed or exited when started by the container runtime.
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:42]:
```suggestion
	A control plane component may have crashed or exited when started by the container runtime.
```

File: cmd/kubeadm/app/phases/kubelet/kubelet.go (hunk 16 above)
Comment (HirazawaUi) [reply cmd/kubeadm/app/phases/kubelet/kubelet.go:72]: If possible, I would prefer to split this function only after the WaitForAllControlPlaneComponents feature gate reaches the GA stage. If users manually disable this feature gate, the error reporting could become confusing as we would lose troubleshooting hints for checking controlPlane components failures.

Alternatively, we could implement a more laborious approach now: when the WaitForAllControlPlaneComponents feature gate is enabled, we would output separate troubleshooting hints for kubelet and controlPlane components respectively. If it's disabled, we would maintain the current behavior.

Comment (neolit123) [reply cmd/kubeadm/app/phases/kubelet/kubelet.go:72]: WaitForControlPlaneComponents is basically the new WaitForAPI which used to wait for only apiserver. the help text to debug a control pod is relevant for both cases.

i think the two errors are distinctive. we shouldn't show an error that the kubelet has failed if the control plane (or just the apiserver) could not start. that's a separate problem.

Comment (HirazawaUi) [reply cmd/kubeadm/app/phases/kubelet/kubelet.go:72]: Fair.

File: cmd/kubeadm/app/phases/kubelet/kubelet.go (hunk 17 above)
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/kubelet.go:42]: leaving the text like that even if the wiatforcontrolplanecomponents FG is disabled, still makes sense.
the error will actually say that it couldn't probe kub-apiserver at healthz for n minutes.

File: cmd/kubeadm/app/util/apiclient/wait.go [hunk 18]
```diff
@@ -52,6 +54,17 @@ const (
 	argAdvertiseAddress = "advertise-address"
 )
 
+var (
+	controlPlaneFailTempl = template.Must(template.New("init").Parse(dedent.Dedent(`
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/util/apiclient/wait.go:58]: I moved `controlPlaneFailTempl` here. After the split, putting it in the kubelet's file seems a bit unreasonable.

Comment (HirazawaUi) [reply cmd/kubeadm/app/util/apiclient/wait.go:58]: fixed.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

thanks
