### PR TITLE
Relax namespace restriction for critical pods

### LINKED ISSUE #76308: Quota for priorityClasses not allowing critical pods to be created in namespaces other than "kube-*"
**What happened**:

Following the documentation at the https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default, I tried enabling quota for a namespace other than `kube-system` but I was still not able to create a pod with `system-cluster-critical` priorityClass in my namespace with following error:

`
Error from server (Forbidden): error when creating "test_pod.yaml": pods "memory-demo" is forbidden: pods with system-cluster-critical priorityClass is not permitted in my-namespace namespace
`

**What you expected to happen**:

Expected pod to be created with namespace where I allowed quota. I can see that both ResourceQuota and Priority Plugins are enabled from logs.

`I0408 17:15:08.558389   29395 plugins.go:158] Loaded 8 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,MutatingAdmissionWebhook.
I0408 17:15:08.558406   29395 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,ResourceQuota.
`

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps at https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default

**Anything else we need to know?**:

I think, the issue is with priorityPlugin where we are rejecting instead of letting resourceQuota plugin to handle the admission when `ResourceQuotaScopeSelectors` is enabled.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

I think, we should relax the restriction on critical pods to be created within `kube-system`, I have outlined an approach which ensures that, initial quota will be restricted to `kube-system` namespace which can later be expanded to other namespaces(https://github.com/kubernetes/kubernetes/pull/76310/files#diff-4e1245d9faac6e47c01c1c068f4de517R199). Let me know, if I have missed something.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/76308

**Special notes for your reviewer**:
/cc @bsalamat @vikaschoudhary16 

**Does this PR introduce a user-facing change?**:

```release-note
Critical pods can now be created in namespaces other than kube-system. To limit critical pods to the kube-system namespace, cluster admins should create an admission configuration file limiting critical pods by default, and a matching quota object in the `kube-system` namespace permitting critical pods in that namespace. See https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default for details.
```
Ref: [document](https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default)

### CODE REVIEW

File: plugin/pkg/admission/priority/admission.go [hunk 1]
```diff
@@ -196,8 +196,14 @@ func (p *priorityPlugin) admitPod(a admission.Attributes) error {
 			pod.Spec.PriorityClassName = pcName
 		} else {
 			pcName := pod.Spec.PriorityClassName
-			if !priorityClassPermittedInNamespace(pcName, a.GetNamespace()) {
-				return admission.NewForbidden(a, fmt.Errorf("pods with %v priorityClass is not permitted in %v namespace", pcName, a.GetNamespace()))
+			// If ResourceQuotaScopeSelectors is enabled, we should let critical priorityClass to be created
+			// any namespace where administrator wants it to be created.
+			// TODO: @ravig Add a default quota at cluster bootstrap which limits critical priorityClasses
```
Comment (vikaschoudhary16) [inline plugin/pkg/admission/priority/admission.go]: I think we would desire that quota is required mandatorily to be present in a namespace for allowing `SystemPriorityClasses` to be created in that namespace. To enforce this, `AdmissionConfiguration` object with matching scopes for `SystemPriorityClasses` must be configured.

Then to allow creation, quota can be created in desired namespaces.

**Review by bsalamat — CHANGES_REQUESTED** [review]
This restriction was an informed decision that we made to prevent a potential vulnerability where a user may create a lot of high priority pods that would preempt system critical components. I still believe that other pods in the system shouldn't be run with those predefined priority classes reserved for system critical components. Why pods in other namespaces need to run with these special priority classes instead of running with a user defined priority that is higher than any other priority, but lower than the system critical priorities?

File: plugin/pkg/admission/priority/admission.go (hunk 1 above)
Comment (bsalamat) [reply plugin/pkg/admission/priority/admission.go]: The problem with this approach is that users will need to add extra configuration to their clusters when they enable ResourceQuotaScopeSelectors. If they don't, this change may create a security gap in their clusters.
Whatever solution we propose here should not need extra configuration by users.

File: plugin/pkg/admission/priority/admission.go [hunk 2]
```diff
@@ -196,8 +196,14 @@ func (p *priorityPlugin) admitPod(a admission.Attributes) error {
...
+			// to be in kube-system namespace. This can be modified later.
+			if !utilfeature.DefaultFeatureGate.Enabled(features.ResourceQuotaScopeSelectors) {
```
Comment (bsalamat) [inline plugin/pkg/admission/priority/admission.go]: Our recent benchmarks show that checking feature gates is relatively slow. We should avoid checking feature gates here. Instead we should check the feature gates at the time of plugin creation and store it in a member variable and use that variable instead.

**Comment by trdavi2** [comment]
Is there any estimate as to when this will be merged and released?  My team and I could really use it

File: plugin/pkg/admission/resourcequota/config.go [hunk 3]
```diff
@@ -37,18 +37,39 @@ func init() {
...
+			},
+		},
+	}
+}
+
 // LoadConfiguration loads the provided configuration.
 func LoadConfiguration(config io.Reader) (*resourcequotaapi.Configuration, error) {
 	// if no config is provided, return a default configuration
-	if config == nil {
+	/*if config == nil {
```
Comment (ravisantoshgudimetla) [inline plugin/pkg/admission/resourcequota/config.go]: The problem with this approach is if `cluster-admin` gives an admission config, we cannot have this default admission. config being used. Alternate approaches that I can think of:

- Read the config and merge it with default config, we have to be careful while merging because there is a chance that `cluster-admin` purposefully sets up a config which is contradicting the default admission config. The downside of this approach is it's not transparent to the user.

File: plugin/pkg/admission/resourcequota/config.go [hunk 4]
```diff
@@ -37,19 +37,35 @@ func init() {
...
+					ScopeName: corev1.ResourceQuotaScopePriorityClass,
+					Operator:  corev1.ScopeSelectorOpIn,
+					Values:    []string{"system-cluster-critical", "system-node-critical"},
+				},
+			},
+		},
+	}
+}
+
+func DefaultAdmissionConfig() *resourcequotaapi.Configuration {
```
Comment (ravisantoshgudimetla) [inline plugin/pkg/admission/resourcequota/config.go]: I want to use this function in test cases, so exposing this as a public function.

**Comment by ravisantoshgudimetla** [comment]
> Is there any estimate as to when this will be merged and released? My team and I could really use it

Perhaps in 1.15. Atleast as of now, that's the plan.

**Comment by dims** [comment]
/milestone v1.15

( per last comment from @ravisantoshgudimetla )

**Comment by ravisantoshgudimetla** [comment]
/hold

for @bsalamat to review.

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 5]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
-			return true, nil
-		})
-		// if we're never able to make it through initialization, kill the API server.
+		}
+		klog.Infof("all system priority classes are created successfully or already exist.")
+		return true, nil
+	})
+}
+
+func AddDefaultSystemQuota(hookContext genericapiserver.PostStartHookContext) error {
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: This seems like a significant change.  Can you document why we are going to have an undeleteable resourcequota object?  Is this trying to preserve some previous behavior around allowing any number of critical pods in the kube-system namespace?  I'm not seeing a value for the number of pods set, so it's not obvious to me what it's doing.

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 6]
```diff
@@ -23,6 +23,9 @@ import (
 	"k8s.io/klog"
 
 	schedulingv1beta1 "k8s.io/api/scheduling/v1beta1"
+
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: nit, remove extra space

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 7]
```diff
@@ -23,6 +23,9 @@ import (
...
+	"k8s.io/api/core/v1"
+
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: nit, remove extra space

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 8]
```diff
@@ -31,7 +34,10 @@ import (
 	"k8s.io/apiserver/pkg/registry/rest"
 	genericapiserver "k8s.io/apiserver/pkg/server"
 	serverstorage "k8s.io/apiserver/pkg/server/storage"
+
 	schedulingclient "k8s.io/client-go/kubernetes/typed/scheduling/v1beta1"
+
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: nit, remove extra space

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 9]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+	})
+}
+
+func AddDefaultSystemQuota(hookContext genericapiserver.PostStartHookContext) error {
+	return wait.Poll(1*time.Second, 30*time.Second, func() (done bool, err error) {
+		client := clientset.NewForConfigOrDie(hookContext.LoopbackClientConfig)
+		_, err = client.CoreV1().ResourceQuotas("kube-system").Get("default-system-quota", metav1.GetOptions{})
 		if err != nil {
-			return fmt.Errorf("unable to add default system priority classes: %v", err)
+			if apierrors.IsNotFound(err) {
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: move this block above the `err != nil` check

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 10]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+				_, err := client.CoreV1().ResourceQuotas("kube-system").Create(systemDefaultQuota())
+				if err != nil && !apierrors.IsAlreadyExists(err) {
+					return false, err
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: This looks questionable.  Seems like we should tolerate most errors until the time is up.  Perhaps logging at a lower verbosity or track "lastErr"?

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 11]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+				} else {
+					klog.Info("Created defaultResourceQuota")
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: This isn't adding much value.  Tell me which one.

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 12]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+		}
+		klog.Infof("all system priority classes are created successfully or already exist.")
+		return true, nil
+	})
+}
+
+func AddDefaultSystemQuota(hookContext genericapiserver.PostStartHookContext) error {
+	return wait.Poll(1*time.Second, 30*time.Second, func() (done bool, err error) {
+		client := clientset.NewForConfigOrDie(hookContext.LoopbackClientConfig)
+		_, err = client.CoreV1().ResourceQuotas("kube-system").Get("default-system-quota", metav1.GetOptions{})
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: the name of this resource isn't very helpful. What is this for?

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 13]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
 		if err != nil {
-			return fmt.Errorf("unable to add default system priority classes: %v", err)
+			if apierrors.IsNotFound(err) {
+				_, err := client.CoreV1().ResourceQuotas("kube-system").Create(systemDefaultQuota())
+				if err != nil && !apierrors.IsAlreadyExists(err) {
+					return false, err
+				} else {
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: try remove the if/else and nesting by using structure and early returns

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 14]
```diff
@@ -89,51 +95,99 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+				return false, nil
+			}
 		}
-		return nil
+		klog.Info("Required default resource quota is created")
+		return true, nil
+	})
+}
+
+func systemDefaultQuota() *v1.ResourceQuota {
```
Comment (deads2k) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: explain what this si for.

File: plugin/pkg/admission/priority/admission.go [hunk 15]
```diff
@@ -51,8 +52,9 @@ func Register(plugins *admission.Plugins) {
 // priorityPlugin is an implementation of admission.Interface.
 type priorityPlugin struct {
 	*admission.Handler
-	client kubernetes.Interface
-	lister schedulingv1listers.PriorityClassLister
+	client   kubernetes.Interface
+	lister   schedulingv1listers.PriorityClassLister
+	features featuregate.FeatureGate
```
Comment (deads2k) [inline plugin/pkg/admission/priority/admission.go]: no. Use the bools for the things you want to check and assign them.

File: plugin/pkg/admission/resourcequota/admission.go [hunk 16]
```diff
@@ -42,6 +43,7 @@ func Register(plugins *admission.Plugins) {
 			// load the configuration provided (if any)
 			configuration, err := LoadConfiguration(config)
 			if err != nil {
+				klog.Infof("Error while loading default config %v", err)
```
Comment (deads2k) [inline plugin/pkg/admission/resourcequota/admission.go]: this looks extraneous.  Why isn't it normally reported?

File: plugin/pkg/admission/resourcequota/config.go [hunk 17]
```diff
@@ -37,19 +37,35 @@ func init() {
...
+		LimitedResources: defaultLimitedResources(),
+	}
+}
+
 // LoadConfiguration loads the provided configuration.
 func LoadConfiguration(config io.Reader) (*resourcequotaapi.Configuration, error) {
 	// if no config is provided, return a default configuration
 	if config == nil {
-		externalConfig := &resourcequotav1beta1.Configuration{}
-		scheme.Default(externalConfig)
```
Comment (deads2k) [inline plugin/pkg/admission/resourcequota/config.go]: did you just lose defaulting?

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 5 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: >  Is this trying to preserve some previous behavior around allowing any number of critical pods in the kube-system namespace? I'm not seeing a value for the number of pods set, so it's not obvious to me what it's doing.

Yeah, it's to ensure backwards compatibility to allow unlimited critical pods in `kube-system` namespace. This is especially true for DS critical DS pods, which as of now are being created in kube-system namespace.

>  Can you document why we are going to have an undeleteable resourcequota object?

I will create a document.

File: plugin/pkg/admission/resourcequota/config.go [hunk 18]
```diff
@@ -63,5 +79,7 @@ func LoadConfiguration(config io.Reader) (*resourcequotaapi.Configuration, error
 	if !ok {
 		return nil, fmt.Errorf("unexpected type: %T", decodedObj)
 	}
+	// append default quota admission config
+	resourceQuotaConfiguration.LimitedResources = append(resourceQuotaConfiguration.LimitedResources, defaultLimitedResources()...)
```
Comment (deads2k) [inline plugin/pkg/admission/resourcequota/config.go]: ux on this is weird.  Is it a default or is `requiredLimitedResources`

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: So, if the user provides some `limitedResources` this value will be appended. It's not a default.

File: plugin/pkg/admission/resourcequota/config.go (hunk 17 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: I did that purposefully. I did not notice any defaulterFuncs for this type. Not sure, if this is needed for every type? Do we need to?

File: plugin/pkg/admission/resourcequota/admission.go (hunk 16 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/admission.go]: Ya, it wasn't showing up in my log when testing locally. I did not debug it though. I will revert this for now and come back to it after debugging.

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 10 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: Do you want logging to be reduced to something like V(5) or above?

Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: I am fine with increasing the log level. Just that, it becomes difficult to debug.

File: plugin/pkg/admission/priority/admission.go (hunk 15 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/priority/admission.go]: Looking at this comment https://github.com/kubernetes/kubernetes/pull/76310#discussion_r273732346, I made featuregates part of plugin, we don't assign here rather check for those values. If we set it as bool I cannot think of cleaner way to get status for all the featuregates we need inside the admission plugin.

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 19]
```diff
@@ -89,51 +94,111 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+				klog.V(5).Infof("Unable to create system default resourceQuota %v: %v. Retrying..", DefaultSystemQuota, err)
+				return false, nil
+			} else {
+				klog.V(5).Infof("Created defaultResourceQuota %v which allows unlimited critical pods to be created in kube-system namespace", DefaultSystemQuota)
+			}
+		}
 		if err != nil {
-			return fmt.Errorf("unable to add default system priority classes: %v", err)
+			// Unable to get the default resource quota for reasons other than "not found".
+			klog.Warning("Unable to get system default resourceQuota %v: %v. Retrying..", DefaultSystemQuota, err)
```
Comment (ravisantoshgudimetla) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: Do you want this to be logged at V(5) and above @deads2k?

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 14 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: Done.

File: plugin/pkg/admission/resourcequota/config.go (hunk 17 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: Added it back.

File: plugin/pkg/admission/priority/admission.go [hunk 20]
```diff
@@ -63,7 +66,24 @@ var _ = genericadmissioninitializers.WantsExternalKubeClientSet(&priorityPlugin{
...
 func newPlugin() *priorityPlugin {
 	return &priorityPlugin{
-		Handler: admission.NewHandler(admission.Create, admission.Update, admission.Delete),
+		Handler:      admission.NewHandler(admission.Create, admission.Update, admission.Delete),
+		featureGates: newFeatureGates(),
+	}
+}
+
+// featureGateStatus contains all the featuregates that are required for this plugin
+type featureGateStatus struct {
```
Comment (ravisantoshgudimetla) [inline plugin/pkg/admission/priority/admission.go]: @deads2k  - Are you fine with this initialization?

File: plugin/pkg/admission/priority/admission.go [hunk 21]
```diff
@@ -63,7 +66,24 @@ var _ = genericadmissioninitializers.WantsExternalKubeClientSet(&priorityPlugin{
...
+	priorityFeatureGateEnabled      bool
+	resourceQuotaFeatureGateEnabled bool
+	criticalPodAnnotationEnabled    bool
+}
+
+// newFeatureGates returns the list of needed featuregates for this plugin to be used.
+func newFeatureGates() featureGateStatus {
```
Comment (ravisantoshgudimetla) [inline plugin/pkg/admission/priority/admission.go]: @deads2k - Are you fine with this initialization?

**Comment by timmycarr** [comment]
Hi! Friendly reminder from your release team: we are starting the code freeze for 1.15 tomorrow EOD. Looks like we have movement here. Can I get quick confirmation that this is still planned for the 1.15 cycle?

**Comment by ravisantoshgudimetla** [comment]
>  Can I get quick confirmation that this is still planned for the 1.15 cycle?

It's still planned for 1.15

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 22]
```diff
@@ -89,51 +94,112 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+		// namespace. This is to ensure backwards compatibility with existing system where we limit critical pods
+		// to be created in `kube-system`.
+		if err := AddDefaultSystemQuota(hookContext); err != nil {
+			return fmt.Errorf("unable to add default system resource quota: %v", err)
+		}
+		return nil
+	}
+}
+
+func AddSystemPriorityClasses(hookContext genericapiserver.PostStartHookContext) error {
```
Comment (bsalamat) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: I don't think this function needs to be public.

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 23]
```diff
@@ -89,51 +94,112 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+		klog.Infof("all system priority classes are created successfully or already exist.")
+		return true, nil
+	})
+}
+
+// AddDefaultSystemQuota adds a quota which allows unlimited critical pods to be created in `kube-system` namespace
+// This quota can be deleted/updated by cluster-admin. If the cluster-admin wants critical pods to be created in
+// namespace other than `kube-system`, he/she can configure quotas which allows these critical pods to be created
+// in that namespace.
+func AddDefaultSystemQuota(hookContext genericapiserver.PostStartHookContext) error {
```
Comment (bsalamat) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: This function can be private too.

File: plugin/pkg/admission/priority/admission.go [hunk 24]
```diff
@@ -196,8 +216,12 @@ func (p *priorityPlugin) admitPod(a admission.Attributes) error {
 			pod.Spec.PriorityClassName = pcName
 		} else {
 			pcName := pod.Spec.PriorityClassName
-			if !priorityClassPermittedInNamespace(pcName, a.GetNamespace()) {
-				return admission.NewForbidden(a, fmt.Errorf("pods with %v priorityClass is not permitted in %v namespace", pcName, a.GetNamespace()))
+			// If ResourceQuotaScopeSelectors is enabled, we should let pods with critical priorityClass to be created
+			// any namespace where administrator wants it to be created.
+			if !p.featureGates.resourceQuotaFeatureGateEnabled {
```
Comment (bsalamat) [inline plugin/pkg/admission/priority/admission.go]: This is a risky change. In our current code, we protect clusters from users who may create pods with system-critical priority causing preemption of important workloads. The protection is enabled regardless of existence of quota or whether the quota feature is enabled. With this change, users can create pods with system-critical priority if quota is disabled.

File: plugin/pkg/admission/resourcequota/config.go [hunk 25]
```diff
@@ -37,19 +37,38 @@ func init() {
...
-		if err := scheme.Convert(externalConfig, internalConfig, nil); err != nil {
-			return nil, err
-		}
-		return internalConfig, nil
+		config := &resourcequotaapi.Configuration{}
+		scheme.Default(config)
+		// append pods as limited resources so that we can limit the number of critical pods to be created. We have
+		// a matching default quota in `kube-system` namespace which allows unlimited pods to be created in that
+		// namespace
+		config.LimitedResources = append(config.LimitedResources, AddCriticalPodLimitedResources()...)
```
Comment (bsalamat) [inline plugin/pkg/admission/resourcequota/config.go]: What if there is an existing and conflicting `LimitedResource` config? What would be the behavior of ResourceQuota?

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 22 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: Sure, I can make these functions private.

File: plugin/pkg/admission/priority/admission.go (hunk 24 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/priority/admission.go]: You mean users can create pods with system-critical priority in any namespace when resourceQuotaScopeSelectors is disabled? If yes, I don't think so - You cannot create critical pods in any namespace other than `kube-system`, if you try to create cluster-critical pods, it would throw an error.

File: plugin/pkg/admission/resourcequota/config.go (hunk 25 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: It may not happen here since we're creating config object here but it can certainly happen at https://github.com/kubernetes/kubernetes/pull/76310/files#diff-468653fefaaca80a88656dcb46002defR87. I thought about this but don't have a clean solution atm because of combinations possible.

File: plugin/pkg/admission/priority/admission.go (hunk 24 above)
Comment (bsalamat) [reply plugin/pkg/admission/priority/admission.go]: You are right. I missed it initially.

File: plugin/pkg/admission/resourcequota/config.go (hunk 25 above)
Comment (bsalamat) [reply plugin/pkg/admission/resourcequota/config.go]: Yeah, those conflicts could cause surprises. For that reason, I am not comfortable with this change at the moment. I think more checks are needed and if conflicting `LimitedResources` exist, we should either merge them, or at least not add the new rules and throw errors.

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: > if conflicting LimitedResources exist, we should either merge them, or at least not add the new rules and throw errors.

So to be clear, even if we have conflicting `LimitedResources` it won't cause an error, as long as we have a matching limitedresource we would proceed allow `system-critical-pods` to be created in `kube-system` namespace. The only thing that concerns me is should we allow that to happen or not(the combinations I was talking about earlier) and it might not be transparent to cluster-admin as to why this is happening but this has been age old problem and clear documentation on why this happens might solve the problem.

I updated the integration test to have conflicting `LimitedResource` operators(In, NotIn) and still the test passes - https://github.com/kubernetes/kubernetes/pull/76310/files#diff-4b71ba6f24c40153543bb61e06d2e54cR403

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 22 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: Done..

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 26]
```diff
@@ -89,51 +94,112 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+// addDefaultSystemQuota adds a quota which allows unlimited critical pods to be created in `kube-system` namespace
+// This quota can be deleted/updated by cluster-admin. If the cluster-admin wants critical pods to be created in
+// namespace other than `kube-system`, he/she can configure quotas which allows these critical pods to be created
+// in that namespace.
+func addDefaultSystemQuota(hookContext genericapiserver.PostStartHookContext) error {
+	return wait.Poll(1*time.Second, 30*time.Second, func() (done bool, err error) {
+		client := clientset.NewForConfigOrDie(hookContext.LoopbackClientConfig)
+		_, err = client.CoreV1().ResourceQuotas(metav1.NamespaceSystem).Get(DefaultSystemQuota, metav1.GetOptions{})
+		if apierrors.IsNotFound(err) {
+			_, err := client.CoreV1().ResourceQuotas(metav1.NamespaceSystem).Create(systemDefaultQuota())
```
Comment (derekwaynecarr) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: doesnt this prevent the user from deleting the quota if its just recreated?

File: plugin/pkg/admission/resourcequota/config.go (hunk 25 above)
Comment (derekwaynecarr) [reply plugin/pkg/admission/resourcequota/config.go]: i am not sure i see an immediate conflict, by definition, a pod with system-critical or system-node critical priority was a limited resource in that it could only be created in one location with an implied quota.  this is basically codifying that rule in the configuration.

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 26 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: I don't think so, the re-creation happens during bootstrap stage where user cannot interact with the api-server yet. Once the bootstrap is complete, users will be able to delete the quota.

File: plugin/pkg/admission/resourcequota/config.go (hunk 25 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: I agree with you. No one wants to create or would have created a config which tells I want my `critical-pods` to be created in any namespace.

**Review by bsalamat — COMMENTED** [review]
only a minor comment. the rest is fine, but I haven't looked at the tests yet.

**Comment by xmudrii** [comment]
@ravisantoshgudimetla Hello! I'm bug triage lead for the 1.16 release cycle and considering this PR has not been updated for a long time, I'd like to check what's the status of this PR. The code freeze is starting 29th August (about 2.5 weeks from now) and while there is plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.16, is it still planned for this release?

**Comment by liggitt** [comment]
moving out of the milestone due to lack of activity

/milestone v1.17

**Comment by ahg-g** [comment]
@draveness @ravisantoshgudimetla can we please prioritize this, we are actually making an incorrect claim in the docs that this is already supported: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical

**Comment by ahg-g** [comment]
@ravisantoshgudimetla any updates on this one? can we try to get it done in 1.17?

/milestone v1.17

**Comment by kikisdeliveryservice** [comment]
Bug Triage Release Team checking in. Code freeze for the 1.17 release is on November 18. Is this still intended for 1.17? Thanks!

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 27]
```diff
@@ -108,46 +114,107 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
+// systemDefaultQuota returns a default system quota. This default quota allows unlimited number of critical pods
+// to be created in `kube-system` namespace. This is needed for backwards compatibility with current system
+// as we allow unlimited critical pods to be created in `kube-system` namespace. The DefaultSystemQuota gets
+// automatically created when we start kube-apiserver. The cluster-admin is allowed to create/delete or update
+// this quota. In order to create critical pods in other namespaces, cluster-admin can create quotas
+// in those namespaces.
+func systemDefaultQuota() *v1.ResourceQuota {
+	defaultQuota := &v1.ResourceQuota{
+		ObjectMeta: metav1.ObjectMeta{Name: DefaultSystemQuota, Namespace: metav1.NamespaceSystem},
+		Spec: v1.ResourceQuotaSpec{
```
Comment (ahg-g) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: so not specifying the ```Hard``` parameter means unlimited? where is that documented?

**Review by ahg-g — COMMENTED** [review]
scheduler changes lgtm

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 27 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: That's right, if you don't specify any limit it's equivalent to unlimited. This is not explicitly called out in documentation AFAIK.

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 26 above)
Comment (deads2k) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: > doesnt this prevent the user from deleting the quota if its just recreated?

but it will come back on the next server restart.

Comment (ahg-g) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: @deads2k  do we have an option other than documenting the behavior, and that an operator can only update the default quota not delete it?

File: pkg/registry/scheduling/rest/storage_scheduling.go [hunk 28]
```diff
@@ -108,46 +114,107 @@ func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.API
...
-				utilruntime.HandleError(fmt.Errorf("unable to initialize client: %v", err))
-				return false, nil
-			}
+		if err := addSystemPriorityClasses(hookContext); err != nil {
+			return fmt.Errorf("unable to add default system priority classes: %v", err)
+		}
+		// Add default resource quota which allows unlimited number of critical pods to be created in kube-system
+		// namespace. This is to ensure backwards compatibility with existing system where we limit critical pods
+		// to be created in `kube-system`.
+		if err := addDefaultSystemQuota(hookContext); err != nil {
```
Comment (liggitt) [inline pkg/registry/scheduling/rest/storage_scheduling.go]: I wouldn't have expected the scheduling storage to create resources in an unrelated API group. narrowly, this storage doesn't even know if quota is available or enabled, right?

File: plugin/pkg/admission/resourcequota/config.go [hunk 29]
```diff
@@ -63,5 +82,8 @@ func LoadConfiguration(config io.Reader) (*resourcequotaapi.Configuration, error
 	if !ok {
 		return nil, fmt.Errorf("unexpected type: %T", decodedObj)
 	}
+	// append pods as limited resources so that we can limit the number of critical pods to be created. We have
+	// a matching default quota in `kube-system` namespace which allows unlimited pods to be created in that namespace
+	resourceQuotaConfiguration.LimitedResources = append(resourceQuotaConfiguration.LimitedResources, AddCriticalPodLimitedResources()...)
```
Comment (liggitt) [inline plugin/pkg/admission/resourcequota/config.go]: adding this to the user-specified config is strange to me. does that mean it is impossible to write a quota config that does not limit critical pods globally and require per-namespace quota? I'm glad it is possible to limit this globally, I just didn't expect us to force-add that to user's global quota config.

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: > does that mean it is impossible to write a quota config that does not limit critical pods globally and require per-namespace quota?

I think, the limitation comes for quota object as it's limited to namespace. So, as a cluster-admin, we need to create matching quotas in every namespace that we'd like critical pods to be brought up.

File: pkg/registry/scheduling/rest/storage_scheduling.go (hunk 28 above)
Comment (ravisantoshgudimetla) [reply pkg/registry/scheduling/rest/storage_scheduling.go]: Good point. The main reason I added it here was we're adding `defaultQuota` to limit priorityClasses which is a scheduling construct.

File: plugin/pkg/admission/resourcequota/config.go (hunk 29 above)
Comment (liggitt) [reply plugin/pkg/admission/resourcequota/config.go]: The more fundamental question is what we expect to happen whenever we add a new resource that can be controlled by global quota.

This is establishing a precedent that new resources 1) will be considered a limited resource by global quota whether or not the cluster-admin provides a global quota config file and whether or not the cluster-admin indicates they want it to be a limited resource and therefore 2) will require per-namespace quota to use

Neither of those are what I expected

**Comment by kikisdeliveryservice** [comment]
Following up: Is this still intended for 1.17 or should we bump it to 1.18?  Code freeze is Nov 14th.

-Bug Triage Team

**Comment by liggitt** [comment]
it is intended for 1.17

File: plugin/pkg/admission/resourcequota/config.go (hunk 29 above)
Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: I think the scope of this `defaultQuota` should be limited to priorityClasses where it is ok to have those matching quotas per namespace which aligns with what we've in [docs](https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default). I think for other resources it's better to keep them out of `defaultQuota`.

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: Also, @deads2k is suggesting to create a control loop which would ensure that we'll allow updates to only few fields in the `defaultQuota`. Having something like would also ensure that `defaultQuota` is not updated for resources other than `priorityClasses`.

Comment (liggitt) [reply plugin/pkg/admission/resourcequota/config.go]: Special-casing a system-maintained quota for one type of resource in kube-system doesn't seem like it would scale well. Special-casing one type of resource to be limited-by-default and to require per-namespace quotas makes the quota policy harder to understand, and requires admins that don't care about quotaing critical pods to set up per-namespace resourcequota objects.

What is the downside to simply making the critical-pod limited resource capability available to cluster admins, without forcing them to use it?

Comment (liggitt) [reply plugin/pkg/admission/resourcequota/config.go]: Given that code freeze is imminent, it might be good to jump on a call with interested parties (@ravisantoshgudimetla, @ahg-g, @derekwaynecarr, @deads2k, others?) to resolve this.

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: I've to call it out that @deads2k was against special casing too. I was talking about the approach he suggested for ensuring backwards compatibility.

> What is the downside to simply making the critical-pod limited resource capability available to cluster admins, without forcing them to use it?

You mean via RBAC?

> Given that code freeze is imminent, it might be good to jump on a call with interested parties (@ravisantoshgudimetla, @ahg-g, @derekwaynecarr, @deads2k, others?) to resolve this.

Sounds good to me. Let me ping folks to slack to find time that works for everyone.

Comment (liggitt) [reply plugin/pkg/admission/resourcequota/config.go]: > > What is the downside to simply making the critical-pod limited resource capability available to cluster admins, without forcing them to use it?
> 
> You mean via RBAC?

no, by specifying it explicitly in their resource quota config file in the `limitedResources` list

Comment (ravisantoshgudimetla) [reply plugin/pkg/admission/resourcequota/config.go]: Just give everyone some context. @liggit, @deads2k, @ahg-g, @damemi and I had a meeting to discuss this and we agreed up on what Jordan suggested earlier - `Have cluster-admins explicitly create a global quota object and admission config to allow which namespaces can have critical pods`

**Comment by ravisantoshgudimetla** [comment]
@liggitt @deads2k @ahg-g up for review again.

File: plugin/pkg/admission/priority/admission.go [hunk 30]
```diff
@@ -189,8 +206,12 @@ func (p *Plugin) admitPod(a admission.Attributes) error {
...
```
Comment (ravisantoshgudimetla) [inline plugin/pkg/admission/priority/admission.go]: @liggit, would this guard be good enough?

Comment (liggitt) [reply plugin/pkg/admission/priority/admission.go]: that matches my expectations as long as that feature has the potential to be turned off

File: plugin/pkg/admission/priority/admission.go (hunk 21 above)
Comment (liggitt) [reply plugin/pkg/admission/priority/admission.go]: wait until https://github.com/kubernetes/kubernetes/pull/84813 merges, then mimic https://github.com/kubernetes/kubernetes/pull/84813/files#diff-3fcca335c60149004f9b76a575070564R123-R127

**Comment by liggitt** [comment]
matches changes discussed with @deads2k, @ravisantoshgudimetla, and @ahg-g

**Comment by pires** [comment]
Can someone please clarify why this is labeled as a bug, has been fixed but not backported? Right now, every version where the feature-gate is enabled actually didn't get this relaxation. So what is the point of validating the feature-gate is enabled when it is already GA in 1.17?

**Comment by liggitt** [comment]
> Can someone please clarify why this is labeled as a bug, has been fixed but not backported? 

This was incorrectly labeled as a bug. It is the completion of the feature which includes support for default quota limiting critical pods.

> Right now, every version where the feature-gate is enabled actually didn't get this relaxation. So what is the point of validating the feature-gate is enabled when it is already GA in 1.17?

In 1.17, the feature is enabled unconditionally, and the supporting quota configuration graduated to v1 status.

**Comment by pires** [comment]
Thanks.
