### PR TITLE
Prioritize deleting the non-running pods when reducing replicas

### LINKED ISSUE #3948: Kubernetes killing running pods instead of unassigned when reducing replicas
I've noticed a issue where if you have multiple replicated slave pods that don't have a HOST assigned and you reduce the number of replicas in the replicationController definition for those pods, sometimes the currently assigned (and running) pods get killed and the unassigned pod will get assigned to run in the killed pods place.
The issue can be reproduced using the guestbook example provided in the repo.

**Steps to reproduce**: (Note this is not always deterministic and may need multiple attempts)

1. Create the master pod 
        
        #create the pods
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-master.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-master.json
        redis-master
    
        #query for pods
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl 
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                 CONTAINER(S)        IMAGE(S)            HOST                LABELS              STATUS
        redis-master        master              dockerfile/redis    127.0.0.1/          name=redis-master   Running
2. Create the master service
           
        #create the service
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-master-service.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-master-service.json
        redis-master
        
        # query for services
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get services
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get services
        NAME                LABELS                                    SELECTOR            IP                  PORT
        kubernetes          component=apiserver,provider=kubernetes   <none>              10.0.0.82           443
        kubernetes-ro       component=apiserver,provider=kubernetes   <none>              10.0.0.204          80
        redis-master        name=redis-master                         name=redis-master   10.0.0.90           6379
3. Create the replicated slaves

        #create the slaves
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh create -f examples/guestbook/redis-slave-controller.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl create -f examples/guestbook/redis-slave-controller.json
        redisSlaveController

        #query for number of replication controllers. Note we have 2 replicas for this controller
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get replicationControllers
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get replicationControllers
        CONTROLLER             CONTAINER(S)        IMAGE(S)                   SELECTOR            REPLICAS
        redisSlaveController   slave               brendanburns/redis-slave   name=redisslave     2

        #query the pods. Note that POD: 51149bbc-a7fb-11e4-a34c-0800279696e1 is unassigned and has pending STATUS
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                                    CONTAINER(S)        IMAGE(S)                   HOST                LABELS                              STATUS
        51149bbc-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   <unassigned>        name=redisslave,uses=redis-master   Pending
        redis-master                           master              dockerfile/redis           127.0.0.1/          name=redis-master                   Running
        34fc5e81-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   127.0.0.1/          name=redisslave,uses=redis-master   Running

4. Edit the Slave Controller definition to only have 1 replicas
5. Update the Slave Controller with new definition

        #update with new definition
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh update -f examples/guestbook/redis-slave-controller.json
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl update -f examples/guestbook/redis-slave-controller.json
        redisSlaveController

        #query for number of replication controllers. Note we have 1 replicas for this controller now after update
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get replicationControllers
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get replicationControllers
        CONTROLLER             CONTAINER(S)        IMAGE(S)                   SELECTOR            REPLICAS
        redisSlaveController   slave               brendanburns/redis-slave   name=redisslave     1

        #query for pods. Note that POD 51149bbc-a7fb-11e4-a34c-0800279696e1 which was previously PENDING with no associated host is now running and the previously running pod has been killed
        [vagrant@k8s-env kubernetes]$ ./cluster/kubectl.sh get pods
        ./cluster/../_output/local/bin/linux/amd64/kubectl
        Running: ./cluster/../_output/local/bin/linux/amd64/kubectl get pods
        POD                                    CONTAINER(S)        IMAGE(S)                   HOST                LABELS                              STATUS
        redis-master                           master              dockerfile/redis           127.0.0.1/          name=redis-master                   Running
        51149bbc-a7fb-11e4-a34c-0800279696e1   slave               brendanburns/redis-slave   <unassigned>        name=redisslave,uses=redis-master   Pending

The expected behavior should be that the scheduler is able to determine that unassigned pods are more viable candidates when reducing number of replicas. It seems to be more likely that since this issue is not deterministic, the ordering in which the `./cluster/kubectl.sh get pods` command returns result is not always deterministically in the same order

### PR DESCRIPTION
**Pull request by yujuhong**
This changes instructs the replication controller to delete replicas in the
order of "unscheduled (pending)", "scheduled (pending)", and "scheduled
(running)" pods. This is less disruptive than deleting random pods.

This fixes #3948.

### CODE REVIEW

File: pkg/controller/replication_controller.go [hunk 1]
```diff
@@ -198,20 +199,38 @@ func FilterActivePods(pods []api.Pod) []api.Pod {
...
+func (s activePods) Less(i, j int) bool {
+	// PodPending < PodUnknown < PodRunning
+	m := map[api.PodPhase]int{api.PodPending: 0, api.PodUnknown: 1, api.PodRunning: 2}
+	if m[s[i].Status.Phase] != m[s[j].Status.Phase] {
+		return m[s[i].Status.Phase] < m[s[j].Status.Phase]
+	}
+	// Unassigned < assigned
+	if s[i].Spec.Host == "" && s[j].Spec.Host != "" {
+		return true
+	}
```
Comment (bgrant0607) [inline pkg/controller/replication_controller.go]: This is great. You could also check readiness (not ready < ready). The endpoints controller check could be factored out into a function:
https://github.com/GoogleCloudPlatform/kubernetes/blob/e1b76b922b3f7aec73715cc53cb6f8e9180e5c26/pkg/service/endpoints_controller.go#L99

Comment (yujuhong) [inline pkg/controller/replication_controller.go]: Factored out the pod ready logic to api.IsPodReady. Added this new condition to pod sorting.

**Comment by yujuhong** [comment]
Comments addressed in the new patch. Thanks for the suggestion!

File: pkg/controller/replication_controller.go [hunk 2]
```diff
@@ -198,20 +199,43 @@ func FilterActivePods(pods []api.Pod) []api.Pod {
...
 }
 
+type activePods []api.Pod
+
+func (s activePods) Len() int      { return len(s) }
+func (s activePods) Swap(i, j int) { s[i], s[j] = s[j], s[i] }
+
+func (s activePods) Less(i, j int) bool {
+	// Not ready < ready
+	if !api.IsPodReady(&s[i]) && api.IsPodReady(&s[j]) {
```
Comment (bgrant0607) [inline pkg/controller/replication_controller.go]: I would order the checks as follows:
1. host
2. phase
3. readiness

but it shouldn't make a lot of difference.

**Comment by bgrant0607** [comment]
LGTM

File: pkg/controller/replication_controller.go (hunk 2 above)
Comment (yujuhong) [inline pkg/controller/replication_controller.go]: Done.

**Comment by yujuhong** [comment]
Addressed the comments and rebased.

**Comment by bgrant0607** [comment]
Thanks. LGTM.
