### PR TITLE
[kubeadm] Fail fast if there already is a node in the cluster with that name

### LINKED ISSUE #36255: [kubeadm] fail fast if two nodes have the same name
ref: http://stackoverflow.com/questions/40294423/kubeadm-why-does-my-node-not-show-up-though-kubelet-says-it-joined/40416796#40416796

@kubernetes/sig-cluster-lifecycle

### PR DESCRIPTION
**Pull request by kenan435**
kubeadm Fail fast if there is another node with the same name already in the cluster. 

Fixes #36255

cc @kubernetes/sig-cluster-federation

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37084)

### CODE REVIEW

**Comment by kenan435** [comment]
@k8s-bot ok to test

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by kenan435** [comment]
Any ideas on how to fix the failing tests? I am not sure how my change breaks the build.

**Comment by kad** [comment]
@kenan435 at least for one failure, you need to update cmd/kubeadm/app/node/BUILD.
line
```
"//pkg/client/clientset_generated/internalclientset/typed/certificates/internalversion:go_default_library"
```
not needed anymore, and corresponding line for new dependency "k8s.io/kubernetes/pkg/api" should be added.

**Comment by errordeveloper** [comment]
LGTM, please fix the tests. Also we are subject to code freeze.

@luxas is there a branch we could merge this into?

File: cmd/kubeadm/app/node/bootstrap.go [hunk 1]
```diff
@@ -105,6 +106,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
...
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("<node/bootstrap> failed to get node hostname [%v]", err)
+	}
+	// TODO(phase1+) https://github.com/kubernetes/kubernetes/issues/33641
+	nodeName := types.NodeName(hostName)
+	nodeList, err := connection.ClientSet.Nodes().List(api.ListOptions{})
+	for _, node := range nodeList.Items {
+		if nodeName == types.NodeName(node.Name) {
+			return errors.New("Node with name: [" + node.Name + "] already exisit")
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: replace to `fmt.Errorf("Node with name [%s] already exists.", node.Name)`

File: cmd/kubeadm/app/node/bootstrap.go [hunk 2]
```diff
@@ -22,22 +22,23 @@ import (
 	"sync"
 	"time"
 
+	"errors"
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: not needed

**Review by luxas — COMMENTED** [review]
LGTM to me as well, and thanks for doing this :+1: 

Please run `hack/update-gofmt.sh` or edit the file manually as @kad suggested.

**Comment by luxas** [comment]
@kenan435 Are you gonna take care of this or should we carry your commit?
For me it doesn't matter, but I'd like this functionality soon

**Comment by kenan435** [comment]
@luxas I'll have a look ASAP.

**Comment by luxas** [comment]
@kenan435 Thanks, but seems like you have to rebase once more and run `./hack/update-bazel.sh` as well in order for tests to pass

File: cmd/kubeadm/app/node/bootstrap.go [hunk 3]
```diff
@@ -105,6 +105,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
...
+func CheckForNodeNameDuplicates(connection *ConnectionDetails) error {
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("<node/bootstrap> failed to get node hostname [%v]", err)
+	}
+	// TODO(phase1+) https://github.com/kubernetes/kubernetes/issues/33641
+	nodeName := types.NodeName(hostName)
+	nodeList, err := connection.ClientSet.Nodes().List(v1.ListOptions{})
+	for _, node := range nodeList.Items {
+		if nodeName == types.NodeName(node.Name) {
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: Why convert `node.Name` here when you can just directly check it against `hostName` like this?
```go
if hostName == node.Name
```

I think that's a safer approach

File: cmd/kubeadm/app/node/bootstrap.go [hunk 4]
```diff
@@ -105,6 +105,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
...
 }
 
+// check to see if there are other nodes in the cluster with identical node names.
+func CheckForNodeNameDuplicates(connection *ConnectionDetails) error {
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("<node/bootstrap> failed to get node hostname [%v]", err)
+	}
+	// TODO(phase1+) https://github.com/kubernetes/kubernetes/issues/33641
+	nodeName := types.NodeName(hostName)
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: This won't be needed then...

File: cmd/kubeadm/app/node/bootstrap.go [hunk 5]
```diff
@@ -105,6 +105,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
 	return establishedConnection, nil
 }
 
+// check to see if there are other nodes in the cluster with identical node names.
+func CheckForNodeNameDuplicates(connection *ConnectionDetails) error {
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("<node/bootstrap> failed to get node hostname [%v]", err)
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: you can omit the `<node/bootstrap>` in errors

File: cmd/kubeadm/app/node/bootstrap.go [hunk 6]
```diff
@@ -105,6 +105,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
...
+	}
+	// TODO(phase1+) https://github.com/kubernetes/kubernetes/issues/33641
+	nodeName := types.NodeName(hostName)
+	nodeList, err := connection.ClientSet.Nodes().List(v1.ListOptions{})
+	for _, node := range nodeList.Items {
+		if nodeName == types.NodeName(node.Name) {
+			return fmt.Errorf("Node with name [%s] already exists.", node.Name)
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: instead of `[%s]`, can you use `%q`?

File: cmd/kubeadm/app/node/bootstrap.go [hunk 7]
```diff
@@ -105,6 +105,23 @@ func EstablishMasterConnection(s *kubeadmapi.NodeConfiguration, clusterInfo *kub
...
 
+// check to see if there are other nodes in the cluster with identical node names.
+func CheckForNodeNameDuplicates(connection *ConnectionDetails) error {
+	hostName, err := os.Hostname()
+	if err != nil {
+		return fmt.Errorf("<node/bootstrap> failed to get node hostname [%v]", err)
+	}
+	// TODO(phase1+) https://github.com/kubernetes/kubernetes/issues/33641
+	nodeName := types.NodeName(hostName)
+	nodeList, err := connection.ClientSet.Nodes().List(v1.ListOptions{})
```
Comment (luxas) [inline cmd/kubeadm/app/node/bootstrap.go]: Please check for the error here and return it if set.
```go
if err != nil {
    return fmt.Errorf("Failed to list the nodes in the cluster: [%v]\n")
```

File: cmd/kubeadm/app/cmd/join.go [hunk 8]
```diff
@@ -145,6 +145,11 @@ func (j *Join) Run(out io.Writer) error {
 		return err
 	}
 
+	err = kubenode.CheckForNodeNameDuplicates(connectionDetails)
```
Comment (luxas) [inline cmd/kubeadm/app/cmd/join.go]: Have you manually verified this works?
Just wondering if it should be before or after the TLS bootstrap...

**Review by luxas — COMMENTED** [review]
Thanks again, but I found some small things before I LGTM

File: cmd/kubeadm/app/cmd/join.go (hunk 8 above)
Comment (kenan435) [inline cmd/kubeadm/app/cmd/join.go]: Yeah, I did at one point. Not sure what difference it makes if its before or after TLS bootstrap since we are passing the same object.

File: cmd/kubeadm/app/node/bootstrap.go (hunk 3 above)
Comment (kenan435) [inline cmd/kubeadm/app/node/bootstrap.go]: done

**Comment by luxas** [comment]
Okay, so now there's just one thing left to fix :smile:!

The cmd/kubeadm/app/node unit test failed, can you see what's failing there (by running something like `go test ./cmd/kubeadm/app/node`), and fix it?
Then I can LGTM this

**Comment by luxas** [comment]
@kenan435 Hi, do you need help with fixing the tests?
I can help and carry it if you want, otherwise just say that you take on to rebase and fix it some time in the coming days and I'll lgtm it :+1:

**Comment by luxas** [comment]
Thanks @kenan435! LGTM

File: cmd/kubeadm/app/cmd/join.go (hunk 8 above)
Comment (kad) [inline cmd/kubeadm/app/cmd/join.go]: @luxas it should be before tls bootstrap, otherwise it will try to issue new cert for same node name, so looks at right place.
