### PR TITLE
Fix overlapping client CA and requestheader CA validation with proper certificate checking

### LINKED ISSUE #119267: NCC-E003660-F9W: Common Certificate Authority Possible for Client CA and Request
### NCC-E003660-F9W: Common Certificate Authority Possible for Client CA and Request
Header CA
This issue was reported in the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Impact**
A misconfiguration of the API server could lead to a situation where privilege escalation for
any authenticated user to cluster admin is possible.

**Description**
The Kubernetes API server allows a certificate authority (CA) to be specified (using the `--
client-ca-file flag`) which will be used to verify client certificates under the familiar X.
509 client certificate authentication scheme6. Another CA can be specified (using `--
requestheader-client-ca-file`) that will be used to verify requests authenticated using
the request header scheme (described in the documentation as Authenticating Proxy). If
these two CAs are the same, and the `--requestheader-allowed-names` flag is not used to
specify particular certificate common names that are permitted for request header
authentication, it is possible for any holder of a client certificate from the shared CA to
trivially authenticate to the API server as any user, by using their certificate to authenticate
a request using the request header scheme. While it is not intended that these CAs be the
same, and common Kubernetes deployment methods do not configure the deployment in
this way, it is possible that administrators could be unaware of this pitfall.

The Kubernetes documentation does include some advice against sharing CAs, but is not
explicit about the potentially serious security impact of this specific case.

For an example, please see the original finding on page 18 of the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Recommendation**
The Kubernetes API server should reject any configuration where `--client-ca-file` and
`--requestheader-client-ca-file` are set to the same value, unless `--requestheaderallowed-
names` has been set to specific value(s).

It may also be advisable to update the Kubernetes documentation to be more explicit about
the specific risks of sharing certificate authorities. For example, using the same CA for X.
509 client certificates for etcd authentication would allow any authenticated user to
directly access etcd (although this scenario is considered less likely than sharing of the
client CA and request header CA).

**Component**
kube-apiserver

**Anything else we need to know?**
See umbrella issue [#118980](https://github.com/kubernetes/kubernetes/issues/118980) for current status of all issues created from these findings.
The vendor gave this issue an ID of NCC-E003660-F9W and it was finding 5 of the report under the kube-apiserver section.
The vendor considers this issue Medium Risk, High Impact, Low Exploitability
To view the original finding, begin on page 18 of the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Test Environment**
Kubernetes 1.24.3

### PR DESCRIPTION
**Pull request by ballista01**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR introduces a validation check at server startup for the Kubernetes API server configuration. It ensures that when `--client-ca-file` and `--requestheader-client-ca-file` refer to CA bundles that **share any certificate**, and `--requestheader-allowed-names` is **not set**, then the API server will **abort startup with an error**.

This closes a privilege escalation risk where any client with a certificate issued by the shared CA can spoof identities via the request header authentication approach, based on [Kubernetes Security Audit Finding NCC-E003660-F9W](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf).

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/119267

#### Special notes for your reviewer:
- Certificate overlap detection uses `client-go/util/cert.CertsFromFile()` and `x509.Certificate.Equal()`.
- Newly added test CA files are from `staging/src/k8s.io/kube-aggregator/pkg/apiserver/testdata`
- It's a continuation of [PR#123008](https://github.com/kubernetes/kubernetes/pull/123008)

#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver: when --requestheader-client-ca-file and --client-ca-file contain overlapping certificates, --requestheader-allowed-names must be specified to ensure regular client certificates cannot set authenticating proxy headers for arbitrary users
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/119267#issuecomment-1875877373
/assign @liggitt

File: pkg/kubeapiserver/options/authentication.go [hunk 1]
```diff
@@ -307,11 +309,39 @@ func (o *BuiltInAuthenticationOptions) Validate() []error {
...
+		if o.ClientCert != nil &&
+			len(o.ClientCert.ClientCA) > 0 &&
+			len(o.RequestHeader.ClientCAFile) > 0 &&
+			len(o.RequestHeader.AllowedNames) == 0 {
+			clientCACerts, err1 := certutil.CertsFromFile(o.ClientCert.ClientCA)
+			requestHeaderCACerts, err2 := certutil.CertsFromFile(o.RequestHeader.ClientCAFile)
+			if err1 == nil && err2 == nil {
+				if certificatesOverlap(clientCACerts, requestHeaderCACerts) {
+					allErrors = append(allErrors,
+						fmt.Errorf("when 'requestheader-client-ca-file' and 'client-ca-file' are the same, 'requestheader-allowed-names' must be specified"))
```
Comment (liggitt) [inline pkg/kubeapiserver/options/authentication.go:322]:
```suggestion
						fmt.Errorf("--requestheader-client-ca-file and --client-ca-file contain overlapping certificates; --requestheader-allowed-names must be specified to ensure regular client certificates cannot set authenticating proxy headers for arbitrary users"))
```

**Review by liggitt — COMMENTED** [review]
one suggestion on the error message, and squash to a single commit, then lgtm

**Review by hashim21223445 — APPROVED** [review]

File: pkg/kubeapiserver/options/authentication_test.go [hunk 2]
```diff
@@ -55,8 +56,12 @@ import (
 )
 
 func TestAuthenticationValidate(t *testing.T) {
+	testDataDir := filepath.Join("testdata")
```
Comment (liggitt) [inline pkg/kubeapiserver/options/authentication_test.go:59]: You can remove this variable and use "testdata" directly below. Linting is complaining about this bit

Comment (ballista01) [reply pkg/kubeapiserver/options/authentication_test.go:59]: Sure!

Comment (ballista01) [reply pkg/kubeapiserver/options/authentication_test.go]: Sorry I forgot to ping you after I made the change. Could you take a look?
