### PR TITLE
kubeadm: refactor the dry-run logic

### LINKED ISSUE #1932: the dynamic dryrun client in kubeadm only supports the core/v1 GroupVersion
if one tries to use the dry-run client with something like batch/v1, the object will be created
but then it will fail GET calls here:

https://github.com/kubernetes/kubernetes/blob/fa1ca34550b70b017234099a5d469fd99e7eed0d/cmd/kubeadm/app/util/apiclient/clientbacked_dryrun.go#L77

ideally we want to refactor this area to support any API object.
potentially not using a dynamic client.

/kind design
/priority backlog

### LINKED ISSUE #2653: add dry run e2e tests
kubeadm is currently missing integration / e2e tests for `--dry-run`.
this means if we happen to break our dry run support for a particular command (e.g. `init`) we will not know about it until users report it to us.

xref https://github.com/kubernetes/kubeadm/issues/2649

kubeadm has integration tests here:
https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/test/cmd
these tests execute a precompiled kubeadm binary to perform some checks and look for exist status 0.

we can use the same method for the `init`, `join`, `reset` tests with `--dry-run`.
because the dry-run will be reentrant.

but we cannot use this method for `upgrade *` commands, because the `--dry-run` for upgrade expects an existing cluster.
- kubeconfig files in /etc/kubernetes/...
- a running kube-apiserver
- other running components...

to have everything in the same place we can add dry-run as part of kinder e2e test workflow:
https://github.com/kubernetes/kubeadm/tree/main/kinder/ci/workflows

the workflow can look like the following:
- allocate a kinder cluster with 1 node
- call `kubeadm init --dry-run` on it (add `--upload-certs` and other special flags, how to test external CA?)
- call` kubeadm join --dry-run` on it (add `--control-plane`,  `--certificate-key` and other flags?)
- call `kubeadm reset --dry-run` on it
- call `kubeadm init ...` to create an actual k8s node
- call `kubeadm upgrade apply --dry-run` to dry run the "primary node" upgrade of this node
- call `kubeadm upgrade node --dry-run` to dry run the "secondary node" upgrade of this node
- .. cleanup

tasks:
- [x] add initial e2e test job for dry-run
k/kubeadm: https://github.com/kubernetes/kubeadm/pull/2673
k/test-infra PR: https://github.com/kubernetes/test-infra/pull/25997
- [ ] in k/k, improve kubeadm's join to use a custom dry-run client as noted [here](https://github.com/kubernetes/kubeadm/issues/2653#issuecomment-1096496562)
TODO
- [ ] update e2e test jobs to have join dry-run as noted [here](https://github.com/kubernetes/kubeadm/issues/2653#issuecomment-1096496562)
TODO

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The current dryrun client implemnetation is suboptimal
and sparse. It has the following problems:

- When an object CREATE or UPDATE reaches the default dryrun client
the operation is a NO-OP, which means subsequent GET calls must
fully emulate the object that exists in the store.
- There are multiple implmentations of a DryRunGetter interface
such the one in init_dryrun.go but there are no implementations
for reset, upgrade, join.
- There is a specific DryRunGetter that is backed by a real
client in clientbacked_dryrun.go, but this is used for upgrade
and does not work in conjuction with a fake client.

This commit does the following changes:

- Removes all existing *dryrun*.go implementations.
- Add a new DryRun implementation in dryrun.go that implements
3 clients - fake clientset, real clientset, real dynamic client.
- The DryRun object uses the method chaining pattern.
- Allows the user opt-in into real clients only if needed, by passing
a real kubeconfig. By default only constructs a fake client.
- The default reactor chain for the fake client, always logs the
object action, then for GET or LIST actions attempts to use the
real dynamic client to get the object. If a real object does not
exist it attempts to get the object from the fake object store.
- The user can prepend or append reactors to the chain.
- All known needed reactors for operations during init, join,
reset, upgrade are added as methods of the DryRun struct.
- Adds detailed unit test for the DryRun struct and its methods
including reactors.

Additional changes:
- Use the new DryRun implementation in all command workflows -
init, join, reset, upgrade.
- Ensure that --dry-run works even if there is no active cluster
by returning faked objects. For join, a faked cluster-info
with a fake bootstrap token and CA are used.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2653
Fixes https://github.com/kubernetes/kubeadm/issues/1932

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: increased the verbosity of API client dry-run actions during the subcommands "init", "join", "upgrade" and "reset". Allowed dry-run on 'kubeadm join' even if there is no existing cluster by utilizing a faked, in-memory cluster-info ConfigMap.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold for
- https://github.com/kubernetes/kubernetes/pull/126032

**Comment by neolit123** [comment]
/retitle kubeadm: refactor the dry-run logic

this is ready for review

File: cmd/kubeadm/app/util/apiclient/dryrun.go [hunk 1]
```diff
@@ -0,0 +1,635 @@
...
+	kubeadmutil "k8s.io/kubernetes/cmd/kubeadm/app/util"
+)
+
+// DryRun is responsible for performing verbose dry-run operations with a set of different
+// API clients. Any REST action that reaches the FakeClient() of a DryRun will be processed
+// as follows by the fake client reactor chain:
+//   - Log the action.
+//   - If the action is not GET or LIST just use the fake client store to write it, unless
+//     a user reactor was added with PrependReactor() or AppendReactor().
+//   - Attempt to GET or LIST using the real dynamic client.
```
Comment (carlory) [inline cmd/kubeadm/app/util/apiclient/dryrun.go:55]: > real dynamic client to get the object. If a real object does not
exist it attempts to get the object from the fake object store.

The above message is copied from the PR's description. It‘s not truth when the real client is instantiated and the given object doesn't exist in the cluster, it will mark the action as handled.

```go
// handleGetAction tries to handle all GET actions with the dynamic client.
func (d *DryRun) handleGetAction(action testing.GetAction) (bool, runtime.Object, error) {
	if d.dynamicClient == nil {
		return false, nil, errors.New("dynamicClient is nil")
	}

	unstructuredObj, err := d.dynamicClient.
		Resource(action.GetResource()).
		Namespace(action.GetNamespace()).
		Get(context.Background(), action.GetName(), metav1.GetOptions{})
	if err != nil {
		return true, nil, err
	}

	newObj, err := d.decodeUnstructuredIntoAPIObject(action, unstructuredObj)
	if err != nil {
		return true, nil, err
	}

	return true, newObj, err
}
```

According to the implementation, it attempts to GET or LIST using the real dynamic client if it is instantiated, otherwise tries to GET or LIST the object from the fake client store. Is it desired?

Comment (carlory) [reply cmd/kubeadm/app/util/apiclient/dryrun.go:55]: Sorry, I didn't see the caller.

```go
				handled, obj, err := d.handleGetAction(getAction)
				if err != nil {
					fmt.Fprintln(d.writer, "[dryrun] Real object does not exist. "+
						"Attempting to GET from followup reactors or from the fake client tracker")
					return false, nil, nil
				}
```

Please ingore above comments.

File: cmd/kubeadm/app/cmd/init.go [hunk 2]
```diff
@@ -502,12 +502,16 @@ func (d *initData) OutputWriter() io.Writer {
 
 // getDryRunClient creates a fake client that answers some GET calls in order to be able to do the full init flow in dry-run mode.
 func getDryRunClient(d *initData) (clientset.Interface, error) {
-	svcSubnetCIDR, err := kubeadmconstants.GetKubernetesServiceCIDR(d.cfg.Networking.ServiceSubnet)
-	if err != nil {
-		return nil, errors.Wrapf(err, "unable to get internal Kubernetes Service IP from the given service CIDR (%s)", d.cfg.Networking.ServiceSubnet)
+	dryRun := apiclient.NewDryRun()
+	if err := dryRun.WithKubeConfigFile(d.KubeConfigPath()); err != nil {
```
Comment (carlory) [inline cmd/kubeadm/app/cmd/init.go:506]: In dry-run mode, `d.KubeConfigPath()` always returns the kubeconfig path from a kubeadm tmp dir. 

I'm not sure whether the created client is able to talk with the real cluster? 

Do sub phases under init phase need a real cluster when a user run a sub phase with the `--dry-run` flag.

File: cmd/kubeadm/app/cmd/join.go [hunk 3]
```diff
@@ -618,15 +670,21 @@ func fetchInitConfigurationFromJoinConfiguration(cfg *kubeadmapi.JoinConfigurati
...
+	var err error
+
+	client := dryRunClient
+	if dryRunClient == nil {
+		// creates a client to access the cluster using the bootstrap token identity
+		client, err = kubeconfigutil.ToClientSet(tlsBootstrapCfg)
+		if err != nil {
+			return nil, errors.Wrap(err, "unable to access the cluster")
+		}
+
```
Comment (carlory) [inline cmd/kubeadm/app/cmd/join.go:683]: please remove this blank line.

File: cmd/kubeadm/app/discovery/token/token.go [hunk 4]
```diff
@@ -49,35 +49,45 @@ const BootstrapUser = "token-bootstrap-client"
 // RetrieveValidatedConfigInfo connects to the API Server and tries to fetch the cluster-info ConfigMap
 // It then makes sure it can trust the API Server by looking at the JWS-signed tokens and (if CACertHashes is not empty)
 // validating the cluster CA against a set of pinned public keys
-func RetrieveValidatedConfigInfo(cfg *kubeadmapi.Discovery, timeout time.Duration) (*clientcmdapi.Config, error) {
-	return retrieveValidatedConfigInfo(nil, cfg, constants.DiscoveryRetryInterval, timeout)
+func RetrieveValidatedConfigInfo(dryRunClient clientset.Interface, cfg *kubeadmapi.Discovery, timeout time.Duration) (*clientcmdapi.Config, error) {
+	isDryRun := dryRunClient != nil
+	isTesting := false
```
Comment (carlory) [inline cmd/kubeadm/app/discovery/token/token.go:54]: What's the purpose of `isTesting`? Can we remove it?

File: cmd/kubeadm/app/discovery/discovery.go [hunk 5]
```diff
@@ -71,7 +72,7 @@ func For(cfg *kubeadmapi.JoinConfiguration) (*clientcmdapi.Config, error) {
 }
 
 // DiscoverValidatedKubeConfig returns a validated Config object that specifies where the cluster is and the CA cert to trust
-func DiscoverValidatedKubeConfig(cfg *kubeadmapi.JoinConfiguration) (*clientcmdapi.Config, error) {
+func DiscoverValidatedKubeConfig(dryRunClient clientset.Interface, cfg *kubeadmapi.JoinConfiguration, isDryRun bool) (*clientcmdapi.Config, error) {
```
Comment (carlory) [inline cmd/kubeadm/app/discovery/discovery.go:75]: `isDryRun` is not used.

File: cmd/kubeadm/app/cmd/join.go [hunk 6]
```diff
@@ -618,15 +670,21 @@ func fetchInitConfigurationFromJoinConfiguration(cfg *kubeadmapi.JoinConfigurati
...
-func fetchInitConfiguration(tlsBootstrapCfg *clientcmdapi.Config) (*kubeadmapi.InitConfiguration, error) {
-	// creates a client to access the cluster using the bootstrap token identity
-	tlsClient, err := kubeconfigutil.ToClientSet(tlsBootstrapCfg)
-	if err != nil {
-		return nil, errors.Wrap(err, "unable to access the cluster")
+func fetchInitConfiguration(dryRunClient clientset.Interface, tlsBootstrapCfg *clientcmdapi.Config) (*kubeadmapi.InitConfiguration, error) {
+	var err error
+
+	client := dryRunClient
+	if dryRunClient == nil {
```
Comment (carlory) [inline cmd/kubeadm/app/cmd/join.go:677]: Is it possible to move the creating client logic to `InitCfg()` ?

File: cmd/kubeadm/app/discovery/token/token.go (hunk 4 above)
Comment (neolit123) [reply cmd/kubeadm/app/discovery/token/token.go:54]: it's a left over from when i was testing with different ways to make the changes in token.go. i will remove it.

File: cmd/kubeadm/app/cmd/join.go (hunk 6 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/join.go:677]: yes, makes sense

**Comment by neolit123** [comment]
just rebased.
still need to address your comments @carlory

File: cmd/kubeadm/app/cmd/init.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/init.go:506]: @carlory so i approached this differently. the problem is that a tmp dir is used for many files not only the admin.conf.

so i think the only way to allow running individual phases in dry-run mode is to allow the user to specify the dry-run directory. we already had an env variable for that called KUBEADM_INIT_DRYRUN_DIR. i just added new ones for UPGRADE and JOIN as well. so here is how the user can used this.

```
lubo@3B69Q73:~/go/src/k8s.io/kubernetes$ sudo kubeadm init phase certs ca --dry-run
W0925 15:27:34.028290  147394 constants.go:610] Using dry-run directory /etc/kubernetes/tmp/kubeadm-init-dryrun1123083720. To override it, set the environment variable KUBEADM_INIT_DRYRUN_DIR
[certs] Using existing ca certificate authority

lubo@3B69Q73:~/go/src/k8s.io/kubernetes$ sudo ls /etc/kubernetes/tmp/kubeadm-init-dryrun1123083720
ca.crt  ca.key
lubo@3B69Q73:~/go/src/k8s.io/kubernetes$ sudo KUBEADM_INIT_DRYRUN_DIR=/etc/kubernetes/tmp/kubeadm-init-dryrun1123083720
kubeadm init phase kubeconfig all --dry-run
[kubeconfig] Using kubeconfig folder "/etc/kubernetes/tmp/kubeadm-init-dryrun1123083720"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "super-admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
```

so when not setting the env var a random dir is generted, but if the env var is set it can be used for phase dry-run.

File: cmd/kubeadm/app/discovery/token/token.go (hunk 4 above)
Comment (neolit123) [reply cmd/kubeadm/app/discovery/token/token.go:54]: actually, it has a purpose. without it the function retrieveValidatedConfigInfo is difficult to unit test.
during tests retrieveValidatedConfigInfo gets isDryRun = false and isTesting = true, that results in no loading of additional kubeconfig files (retrieveValidatedConfigInfo loads kubeconfig files). during tests client is a fake client and during real usage client is a dryRun client.

ideas to improve this are welcome, but i think it might be suitable for a new PR that would refactor / break apart  retrieveValidatedConfigInfo. perhaps in multiple functions.

File: cmd/kubeadm/app/cmd/join.go (hunk 6 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/join.go:677]: moved this to fetchInitConfigurationFromJoinConfiguration as that func also needs tlsBootstrapCfg.

**Comment by neolit123** [comment]
looking for more reviews.

**Comment by carlory** [comment]
Thanks for your update. It looks good to me. 

/lgtm

Looking another reviewer for the final approval.
/hold

File: cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go [hunk 7]
```diff
@@ -105,7 +105,7 @@ func runCleanupNode(c workflow.RunData) error {
 			klog.Warningf("[reset] Failed to remove containers: %v\n", err)
 		}
 	} else {
-		fmt.Println("[reset] Would remove Kubernetes-managed containers")
+		fmt.Println("[dyrrun] Would remove Kubernetes-managed containers")
```
Comment (pacoxu) [inline cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go:108]:
```suggestion
		fmt.Println("[dryrun] Would remove Kubernetes-managed containers")
```
typo

File: cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go [hunk 8]
```diff
@@ -176,7 +176,7 @@ func resetConfigDir(configPathDir string, dirsToClean []string, isDryRun bool) {
 			}
 		}
 	} else {
-		fmt.Printf("[reset] Would delete files: %v\n", filesToClean)
+		fmt.Printf("[dryrun] Would delete files: %v\n", filesToClean)
```
Comment (pacoxu) [inline cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go:179]: Should file path be quoted using %q?

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go:179]: filesToClean is a slice of strings, so that's why here is  %v

**Comment by neolit123** [comment]
updated

File: cmd/kubeadm/app/util/apiclient/dryrun.go [hunk 9]
```diff
@@ -0,0 +1,635 @@
...
+}
+
+// DeleteBootstrapTokenReactor returns a reactor that handles the DELETE action
+// of bootstrap token Secret.
+func (d *DryRun) DeleteBootstrapTokenReactor() *testing.SimpleReactor {
+	return &testing.SimpleReactor{
+		Verb:     "delete",
+		Resource: "secrets",
+		Reaction: func(action testing.Action) (bool, runtime.Object, error) {
+			a := action.(testing.GetAction)
```
Comment (SataQiu) [inline cmd/kubeadm/app/util/apiclient/dryrun.go:461]:
```suggestion
			a := action.(testing.DeleteAction)
```

**Comment by neolit123** [comment]
thanks for the reviews. @SataQiu add comments if you have too.
i will try to merge this early next week and update the dry run e2e test.

File: cmd/kubeadm/app/util/apiclient/dryrun.go [hunk 10]
```diff
@@ -0,0 +1,635 @@
...
+		d.LogObject(objAction.GetObject(), objAction.GetResource().GroupVersion())
+	}
+}
+
+// LogObject marshals the object and then prints it to the io.Writer of this DryRun.
+func (d *DryRun) LogObject(obj runtime.Object, gv schema.GroupVersion) {
+	objBytes, err := d.marshalFunc(obj, gv)
+	if err == nil {
+		fmt.Fprintln(d.writer, "[dryrun] Attached object:")
+		fmt.Fprintf(d.writer, "%s", objBytes)
```
[the remark this answers is not in the document]
Comment (neolit123) [reply cmd/kubeadm/app/util/apiclient/dryrun.go:331]: yeah, or just use Fprintf properly.

**Comment by neolit123** [comment]
@SataQiu updated.

**Comment by neolit123** [comment]
@SataQiu @pacoxu @carlory 
looking for LGTM so that i can merge this and update e2e tests.

**Comment by pacoxu** [comment]
/lgtm
/approve
(The only update after my last LGTM is a message format update according to Sata's comments. )
