### PR TITLE
fix race on integration test for portforward

### LINKED ISSUE #125904: portforward test: race condition
### What happened?

I ran https://github.com/kubernetes/kubernetes/pull/116980 ("make test-integration" with race detection) and it [found](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116980/pull-kubernetes-integration/1808940570375098368) this:

```
WARNING: DATA RACE
Write at 0x00c00901bdd0 by goroutine 4387:
  bytes.(*Buffer).grow()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/bytes/buffer.go:151 +0x2d3
  bytes.(*Buffer).Write()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/bytes/buffer.go:179 +0xc4
  fmt.Fprintf()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/fmt/print.go:225 +0xab
  k8s.io/client-go/tools/portforward.(*PortForwarder).handleConnection()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/portforward/portforward.go:339 +0x19d
  k8s.io/client-go/tools/portforward.(*PortForwarder).waitForConnection.gowrap1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/portforward/portforward.go:320 +0x6b

Previous read at 0x00c00901bdd0 by goroutine 120:
  bytes.(*Buffer).String()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/bytes/buffer.go:71 +0x18f7
  k8s.io/kubernetes/test/integration/apiserver/portforward.TestPortforward()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/portforward/portforward_test.go:153 +0x18d1
  testing.tRunner()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:1742 +0x44

Goroutine 4387 (running) created at:
  k8s.io/client-go/tools/portforward.(*PortForwarder).waitForConnection()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/portforward/portforward.go:320 +0x84
  k8s.io/client-go/tools/portforward.(*PortForwarder).listenOnPortAndAddress.gowrap1()
      /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/portforward/portforward.go:277 +0x6b

Goroutine 120 (running) created at:
  testing.(*T).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:1742 +0x825
  testing.runTests.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:2161 +0x85
  testing.tRunner()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:1689 +0x21e
  testing.runTests()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:2159 +0x8be
  testing.(*M).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/cache/mod/golang.org/toolchain@v0.0.1-go1.22.5.linux-amd64/src/testing/testing.go:2027 +0xf17
  testing.(*M).Run-fm()
      <autogenerated>:1 +0x33
  k8s.io/kubernetes/test/integration/framework.EtcdMain()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/framework/etcd.go:224 +0x656
  k8s.io/kubernetes/test/integration/apiserver/portforward.TestMain()
      /home/prow/go/src/k8s.io/kubernetes/test/integration/apiserver/portforward/main_test.go:26 +0x31e
  main.main()
      _testmain.go:49 +0x2d0
```

### What did you expect to happen?

No race.

### How can we reproduce it (as minimally and precisely as possible)?

Run the test with `go test -race`.

### Anything else we need to know?

_No response_

### Kubernetes version

master

### Cloud provider

n/a

### OS version

_No response_

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aojea**
Fixes: #125904 

```release-note
NONE
```

The race happens because the test reads the buffer used to store the `stdout` that is also used by the streams .

Making the buffer thread safe removes the race

```
o test -timeout 30s -run ^TestPortforward$ k8s.io/kubernetes/test/integration/apiserver/portforward  -count 1 -race
ok      k8s.io/kubernetes/test/integration/apiserver/portforward        8.784s
```

### CODE REVIEW

File: test/integration/apiserver/portforward/portforward_test.go [hunk 1]
```diff
@@ -113,7 +113,15 @@ func TestPortforward(t *testing.T) {
 	// local port missing asks os to find random open port.
 	// Example: ":8000" (local = random, remote = 8000)
 	localRemotePort := fmt.Sprintf(":%s", remotePort)
-	streams, _, out, errOut := genericiooptions.NewTestIOStreams()
+	out := &mBuffer{
```
Comment (pohly) [inline test/integration/apiserver/portforward/portforward_test.go:116]: There are quite a few other tests which use `NewTestIOStreams`. That method is marked "deprecated" with itself (?!) as replacement. I haven't looked into the history.

Would it perhaps make sense to fix that method so that it returns thread-safe streams?

Otherwise we might have to adapt the other tests at some future time....

Comment (mauri870) [reply test/integration/apiserver/portforward/portforward_test.go:116]: I also got confused for a moment, looks like there are two similarly named packages that expose `NewTestIOStreams`, `genericiooptions` and `genericiclioptions`.

Comment (aojea) [reply test/integration/apiserver/portforward/portforward_test.go:116]: > Would it perhaps make sense to fix that method so that it returns thread-safe streams?

IIRC the streams are not safe because they are used on tests and the buffers are shared, same as the test on the apiserver that need to do deepcopy on the vars

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
