### PR TITLE
deprecate created-by annotation for pod drain

### LINKED ISSUE #44407: Deprecate created-by annotation, in favor of ControllerRef
TODOs:

* [x] `kubectl describe` list of controllers for an object.
* [x] `kubectl drain` Pod filtering.
* [x] Classifying failed Pods in e2e test framework.
* [x] CronJob grouping Jobs by owner/creator.
* [ ] Announce deprecation of created-by annotation in the release note

@erictune @enisoc @kow3ns @foxish @kargakis @kubernetes/sig-apps-feature-requests

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**: This PR deprecates created-by annotation for pod drain. This is required as we now have ControllerRef.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: xref #44407

**Special notes for your reviewer**: This is the second PR for deprecating created-by annotation. Other PRs can be found here: https://github.com/kubernetes/kubernetes/pull/47469 , #47475 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot ok to test

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-verify test this

File: pkg/kubectl/cmd/drain.go [hunk 1]
```diff
@@ -282,16 +283,28 @@ func (o *DrainOptions) getController(sr *api.SerializedReference) (interface{},
...
+			Name:       pod.GetOwnerReferences()[0].Name,
+			Namespace:  pod.GetObjectMeta().GetNamespace(),
+		},
+	}
+}
+
 func (o *DrainOptions) getPodCreator(pod api.Pod) (*api.SerializedReference, error) {
-	creatorRef, found := pod.ObjectMeta.Annotations[api.CreatedByAnnotation]
-	if !found {
+	if controller.GetControllerOf(pod.GetObjectMeta()) == nil {
```
Comment (enisoc) [inline pkg/kubectl/cmd/drain.go]: It should work to just do `GetControllerOf(pod)`.

Also, keep the returned value since it will already contain what you need, and you won't need to use `newSerializedControllerRef()` to pull the same info out of `pod` again.

```go
controllerRef := controller.GetControllerOf(pod)
if controllerRef == nil {
  return nil, nil
}
```

File: pkg/kubectl/cmd/drain.go [hunk 2]
```diff
@@ -282,16 +283,28 @@ func (o *DrainOptions) getController(sr *api.SerializedReference) (interface{},
...
 		return nil, nil
 	}
 	// Now verify that the specified creator actually exists.
-	sr := &api.SerializedReference{}
-	if err := runtime.DecodeInto(o.Factory.Decoder(true), []byte(creatorRef), sr); err != nil {
-		return nil, err
-	}
+	sr := newSerializedControllerRef(pod)
```
Comment (enisoc) [inline pkg/kubectl/cmd/drain.go]: The `SerializedReference` type was only used here because it's the type of object that was stored in the `CreatedByAnnotation`. Instead of translating the ControllerRef back into a `SerializedReference`, I suggest to modify `getController()` and all callers of `getPodCreator()` to work based on a value of type `*metav1.OwnerReference`. Then you can directly use the value returned by `controller.GetControllerOf()` (if it's not `nil`).

File: pkg/kubectl/cmd/drain.go [hunk 3]
```diff
@@ -282,16 +283,28 @@ func (o *DrainOptions) getController(sr *api.SerializedReference) (interface{},
...
 }
 
+func newSerializedControllerRef(pod api.Pod) *api.SerializedReference {
+	return &api.SerializedReference{
+		TypeMeta: metav1.TypeMeta{
+			APIVersion: "v1",
+			Kind:       "SerializedReference",
+		},
+		Reference: api.ObjectReference{ //currently only set based on first controller
+			APIVersion: pod.GetOwnerReferences()[0].APIVersion,
```
Comment (enisoc) [inline pkg/kubectl/cmd/drain.go]: I suggest using a different approach (see below) that would mean this function can be removed. However, for future reference, note that `pod.GetOwnerReferences()[0]` is dangerous here because a pod can have multiple OwnerReferences, and there is no guarantee that the first one is the ControllerRef (which is the one you actually are looking for).

File: pkg/kubectl/cmd/drain.go (hunk 2 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: Yes, i think it is a better way than translating `ControllerRef` back to `SerializedReference`. I will work on modifying `getController()` and `getPodCreator()` callers.

File: pkg/kubectl/cmd/drain.go (hunk 3 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: noted! i thought a pod has only one owner like cronjob and job, and decided to have a try with `pod.GetOwnerReferences()[0]`. i will use another approach.

File: pkg/kubectl/cmd/drain.go (hunk 1 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: I will remove `newSerializedControllerRef()` and keep the `ControllerRef` value.

Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: just pass `&pod` is enough

File: pkg/kubectl/cmd/drain.go (hunk 2 above)
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: IIUC, `sr` is only used by `o.getController` to get the resource to see if it actually exists. From the above returned controller ref you can get `Kind` and `Name` of the controller, and you already have `Namespace` from `pod.Namespace`. Pass these to `getController` is enough.

File: pkg/kubectl/cmd/drain.go (hunk 1 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: yup! :)

File: pkg/kubectl/cmd/drain.go (hunk 2 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: noted! thanks for the details! i will change my approach accordingly.

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by crimsonfaith91** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

File: pkg/kubectl/cmd/drain.go [hunk 4]
```diff
@@ -266,40 +267,36 @@ func (o *DrainOptions) deleteOrEvictPodsSimple() error {
 	return err
 }
 
-func (o *DrainOptions) getController(sr *api.SerializedReference) (interface{}, error) {
-	switch sr.Reference.Kind {
+func (o *DrainOptions) getController(pod *api.Pod, controllerRef *metav1.OwnerReference) (interface{}, error) {
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: Do a sanity check to make sure controllerRef isn't `nil`, and pass namespace instead of `pod` since we don't need the whole `pod`.

Comment (enisoc) [inline pkg/kubectl/cmd/drain.go]: I would prefer if this function just accepts `namespace string` rather than the `pod`, since the namespace is all it needs.

File: pkg/kubectl/cmd/drain.go [hunk 5]
```diff
@@ -266,40 +267,36 @@ func (o *DrainOptions) deleteOrEvictPodsSimple() error {
...
+		return o.client.Apps().StatefulSets(pod.Namespace).Get(controllerRef.Name, metav1.GetOptions{})
 	}
-	return nil, fmt.Errorf("Unknown controller kind %q", sr.Reference.Kind)
+	return nil, fmt.Errorf("Unknown controller kind %q", controllerRef.Kind)
 }
 
-func (o *DrainOptions) getPodCreator(pod api.Pod) (*api.SerializedReference, error) {
-	creatorRef, found := pod.ObjectMeta.Annotations[api.CreatedByAnnotation]
-	if !found {
+func (o *DrainOptions) getPodCreator(pod api.Pod) (*metav1.OwnerReference, error) {
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: Maybe we should rename this function, since it doesn't return the pod creator anymore, such as `getPodController`

**Review by enisoc — APPROVED** [review]
One minor comment, but LGTM overall.

File: pkg/kubectl/cmd/drain.go (hunk 4 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: noted! :)

File: pkg/kubectl/cmd/drain.go [hunk 6]
```diff
@@ -266,40 +267,36 @@ func (o *DrainOptions) deleteOrEvictPodsSimple() error {
...
-	sr := &api.SerializedReference{}
-	if err := runtime.DecodeInto(o.Factory.Decoder(true), []byte(creatorRef), sr); err != nil {
-		return nil, err
-	}
+
 	// We assume the only reason for an error is because the controller is
 	// gone/missing, not for any other cause.  TODO(mml): something more
 	// sophisticated than this
-	_, err := o.getController(sr)
+	_, err := o.getController(&pod, controllerRef)
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: Actually, do we still need this? This originally checks if the controller specified in created-by annotation is gone or missing. Created-by annotation is never updated, but controller ref is different. If a pod has a controller ref set, the controller must exist. @enisoc

File: pkg/kubectl/cmd/drain.go (hunk 4 above)
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: Or maybe we don't need `getController` at all.

File: pkg/kubectl/cmd/drain.go (hunk 5 above)
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: If we don't need `getController`, `getPodCreator` is redundant (`controller.GetControllerOf` is enough)

Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: i will change the name to `getPodController`.

File: pkg/kubectl/cmd/drain.go (hunk 6 above)
Comment (enisoc) [inline pkg/kubectl/cmd/drain.go]: It's tempting to remove the check, since then this would work for controller types that we don't know about. The one corner case I can think of is if the pod has other OwnerRefs besides the ControllerRef. Then we can't assume it is destined for garbage collection.

Should we do the check only if the pod has more than one OwnerRef? It seems like that would add complexity for not much gain though.

File: pkg/kubectl/cmd/drain.go (hunk 4 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: there is already a sanity check in `getPodController()` function.
interesting. if we remove `getController, `getPodController()` will become an inline function.

File: pkg/kubectl/cmd/drain.go (hunk 6 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: i think we can have the check :)

Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: as discussed by person, i will have the `getController` function intact. i will also add a TODO explaining the situation.

File: pkg/kubectl/cmd/drain_test.go [hunk 7]
```diff
@@ -272,7 +285,17 @@ func TestDrain(t *testing.T) {
 			Namespace:         "default",
 			CreationTimestamp: metav1.Time{Time: time.Now()},
 			Labels:            labels,
+			SelfLink:          "/apis/extensions/v1beta1/namespaces/default/daemonsets/ds",
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain_test.go]: Just use `testapi.Default.SelfLink` to set the selflink.

File: pkg/kubectl/cmd/drain_test.go [hunk 8]
```diff
@@ -272,7 +285,17 @@ func TestDrain(t *testing.T) {
...
 			Annotations:       ds_anno,
+			OwnerReferences: []metav1.OwnerReference{
+				{
+					APIVersion:         "extensions",
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain_test.go]: It doesn't matter for this test, but it should look like `extensions/v1beta1`

File: pkg/kubectl/cmd/drain_test.go [hunk 9]
```diff
@@ -244,7 +246,18 @@ func TestDrain(t *testing.T) {
 			Namespace:         "default",
 			CreationTimestamp: metav1.Time{Time: time.Now()},
 			Labels:            labels,
+			SelfLink:          testapi.Default.SelfLink("replicationcontrollers", "rc"),
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain_test.go]: Although it doesn't matter for this test, SelfLink should link to the pod itself, not its controller.

**Review by janetkuo — COMMENTED** [review]
Just nits, LGTM otherwise.

File: pkg/kubectl/cmd/drain.go (hunk 6 above)
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: @crimsonfaith91 Would you open an issue for this?

File: pkg/kubectl/cmd/drain_test.go (hunk 9 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain_test.go]: good catch. i will have `testapi.Default.SelfLink` for all test cases.

File: pkg/kubectl/cmd/drain_test.go (hunk 8 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain_test.go]: noted!

File: pkg/kubectl/cmd/drain_test.go (hunk 7 above)
Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain_test.go]: i will set the selflink using `testapi` for all the test cases.

File: pkg/kubectl/cmd/drain.go [hunk 10]
```diff
@@ -266,40 +267,37 @@ func (o *DrainOptions) deleteOrEvictPodsSimple() error {
...
-		return nil, err
-	}
+
 	// We assume the only reason for an error is because the controller is
-	// gone/missing, not for any other cause.  TODO(mml): something more
-	// sophisticated than this
-	_, err := o.getController(sr)
+	// gone/missing, not for any other cause.
+	// TODO(mml): something more sophisticated than this
+	// TODO(juntee): remove getController() if the pod's owner can be of any type
```
Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: `TODO(juntee): determine if it's safe to remove getController(), so that drain can work for controller types that we don't know about.`

Comment (janetkuo) [inline pkg/kubectl/cmd/drain.go]: We can open an issue to track this too

Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: sorry for late reply. sent out another commit with the updated TODO message.

Comment (crimsonfaith91) [inline pkg/kubectl/cmd/drain.go]: here's the issue: https://github.com/kubernetes/kubernetes/issues/47667

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
LGTM, please squash commits

**Comment by crimsonfaith91** [comment]
@janetkuo should we add a `v1.8` milestone to prevent merging?

**Comment by janetkuo** [comment]
/lgtm

That's fine, the bot only merges PRs marked with 1.7 milestone during code freeze

**Comment by soltysh** [comment]
lgtm
