### PR TITLE
Reduce the number of expensive calls in the Windows stats queries for dockershim

### LINKED ISSUE #104283: Context Deadline exceeded when Metrics Server calls Windows Stats endpoint
#### What happened:

Metric server reports "context Deadline exceeded when calling metrics endpoint.  This cause its with `kubectl top pods` and potentially HPA if it is being used.

```
E0726 23:44:07.782895       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:aksnpwin000002: unable to fetch metrics from Kubelet aksnpwin000002 (10.240.0.97): Get https://10.240.0.97:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded
```

Looking at kubelet logs this with `-v5` we can see the request is return in time but is over the 60sec timeout the metric server defaults.  

```
sls -Path .\kubelet.err* -Pattern "latency=""\d+m\d+.\d+s"""       
kubelet.err-20210727T134827.473.log:9418:I0727 13:13:23.610822     984 httplog.go:89] "HTTP" verb="GET" URI="/stats/summary?only_cpu_and_memory=true" latency="1m9.8193246s"  
```

When I am able to reproduce this I can see several components querying the stats endpoint at once including sometimes an internal error timeout.

```
kubelet.err-20210727T134827.473.log:9333:I0727 13:13:14.034332     984 httplog.go:89] "HTTP" verb="GET" URI="/stats/summary?only_cpu_and_memory=true" latency="2m0.2529876s"
userAgent="Go-http-client/2.0" srcIP="10.240.0.15:35654" resp=500 statusStack="\ngoroutine 2624574 ....
kubelet.err-20210727T134827.473.log:9418:I0727 13:13:23.610822     984 httplog.go:89] "HTTP" verb="GET" URI="/stats/summary?only_cpu_and_memory=true" latency="1m9.8193246s"
userAgent="Go-http-client/2.0" srcIP="10.240.0.15:35654" resp=200
kubelet.err-20210727T134827.473.log:9483:I0727 13:13:24.289825     984 httplog.go:89] "HTTP" verb="GET" URI="/stats/summary" latency="1m21.3725636s" userAgent="Ruby" srcIP="10.240.0.29:48702"
resp=200
```

#### What you expected to happen:

Gathering stats for windows to not timeout

#### How to reproduce it (as minimally and precisely as possible):

It is difficult to reproduce. I've written a little program that manually does multiple calls windows stats system call and i can reproduce it.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows
/assign

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This improves the response time and minimizes the calls to the system stats which reduces overall cpu for kubelet.  This is done by passing the container object, which has the information required, instead of querying for it on every container via the dockerservice. It also caches some information like the runtime info so it is not queried on every container.

Dockershim create a  new namepiped instance to docker every call causing reads and higher cpu usage.  (Containerd re-uses the same namedpipe instance so doesn't see the same cpu spike).

#### Which issue(s) this PR fixes:

Fixes #104283 
#### Special notes for your reviewer:

I initially included the commits from https://github.com/kubernetes/kubernetes/pull/105744 but moved it to a separate PR.  That PR also improves the overall CPU used here but not opening and list all the containers twice.

#### Does this PR introduce a user-facing change?

```release-note
Reduce the number of calls to docker for stats via dockershim. For Windows this reduces the latency when calling docker, for Linux this saves cpu cycles. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsturtevant** [comment]
https://github.com/kubernetes/kubernetes/pull/104880 made it in which has the parts needed for the hns endpoints stats.

**Comment by jsturtevant** [comment]
not sure how all these labels and areas were added. cleaning up...

/remove-sig architecture
/remove-sig cli
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-sig storage

/remove-area apiserver
/remove-area cloudprovider
/remove-area code-generation
/remove-area dependecy
/remove-area kubectl

File: pkg/kubelet/dockershim/docker_service.go [hunk 1]
```diff
@@ -536,6 +549,20 @@ func (ds *dockerService) getDockerVersionFromCache() (*dockertypes.Version, erro
 	return dv, nil
 }
 
+func (ds *dockerService) getDockerInfoFromCache() (*dockertypes.Info, error) {
+	// We only store on key in the cache.
+	const dummyKey = "info"
```
Comment (marosset) [inline pkg/kubelet/dockershim/docker_service.go:554]: nit: maybe rename dummyKey to something slightly more descriptive?
infoCacheKey?

File: pkg/kubelet/dockershim/docker_stats.go [hunk 2]
```diff
@@ -22,15 +22,26 @@ package dockershim
...
+func (ds *dockerService) ContainerStats(ctx context.Context, r *runtimeapi.ContainerStatsRequest) (*runtimeapi.ContainerStatsResponse, error) {
+	filter := &runtimeapi.ContainerFilter{
+		Id: r.ContainerId,
+	}
+	listResp, err := ds.ListContainers(ctx, &runtimeapi.ListContainersRequest{Filter: filter})
+	if err != nil {
+		return nil, err
+	}
+	if len(listResp.Containers) != 1 {
+		return nil, fmt.Errorf("not found")
```
Comment (marosset) [inline pkg/kubelet/dockershim/docker_stats.go:42]:
```suggestion
		return nil, fmt.Errorf("container not found")
```

or something slightly more helpful? should the containerId be in the error message to?

File: pkg/kubelet/dockershim/docker_stats_windows.go [hunk 3]
```diff
@@ -98,7 +86,10 @@ func (ds *dockerService) getContainerStats(containerID string) (*runtimeapi.Cont
 		WritableLayer: &runtimeapi.FilesystemUsage{
 			Timestamp: timestamp,
 			FsId:      &runtimeapi.FilesystemIdentifier{Mountpoint: info.DockerRootDir},
-			UsedBytes: &runtimeapi.UInt64Value{Value: uint64(*containerJSON.SizeRw)},
+			// used bytes from image are not implemented on Windows
+			// don't query for it since it is expensive to call docker over named pipe
+			// https://github.com/moby/moby/blob/1ba54a5fd0ba293db3bea46cd67604b593f2048b/daemon/images/image_windows.go#L11-L14
+			UsedBytes: &runtimeapi.UInt64Value{Value: 0},
```
Comment (marosset) [inline pkg/kubelet/dockershim/docker_stats_windows.go:92]: Do you have a sense of how much of the perf improvements you see on Windows are due to info from the docker api vs how much is due to not querying for this data on Windows?

**Review by marosset — COMMENTED** [review]
The code changes look pretty good to me.

While reviewing this I had 2 questions.

1) Is it worth making this change in v1.23 knowing that dockershim is going to be removed in v1.24 
2) Do we want to make to cache info for Linux and Windows or just Windows.

I think my answer to the first question is yes. We've seen a few different issues on Windows around querying container stats w/ dockershim and other issues on Windows when resource usage on the node is high.
Either one can result in functionality like HPA not working as expected - which can be a big deal for operators.
I think we should still pursue this change so we can backport it to v1.20-v1.22 as well.

For the second question, I think that if we know we want to backport this fix it might be better to try and limit it to Windows only (Unless there are issues on Linux similar to what I mentioned above) just to limit the scope.
I'm curious what @SergeyKanzhelev thinks here.

File: pkg/kubelet/dockershim/docker_service.go [hunk 4]
```diff
@@ -314,6 +324,9 @@ type dockerService struct {
 	// the docker daemon every time we need to do such checks.
 	versionCache *cache.ObjectCache
 
+	// caches the info from the runtime.
+	infoCache *cache.ObjectCache
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/dockershim/docker_service.go:328]: can we just keep the `dockertypes.Info` object? What's the benefit of using the cache with a single value in it?

Comment (SergeyKanzhelev) [reply pkg/kubelet/dockershim/docker_service.go:328]: oh, I see, the expiration in case it was restarted

**Comment by SergeyKanzhelev** [comment]
> For the second question, I think that if we know we want to backport this fix it might be better to try and limit it to Windows only (Unless there are issues on Linux similar to what I mentioned above) just to limit the scope.
> I'm curious what @SergeyKanzhelev thinks here.

Looking briefly into it feels strange that `info` is only seems to be used for the `info.DockerRootDir`, so practically this value can be cached for much longer. I wonder what's the size of `info` if we only use a single field, it looks like a big waste. 

If you can look a bit on savings we get on Linux - it may help to say whether we need it. The only concern with cache is the data consistency, that docker will be reinstalled in those 60 seconds... but I doubt it is a big deal.

Also, please correct the release notes if you will proceed with the fix for Linux as well.

**Comment by jsturtevant** [comment]
> Looking briefly into it feels strange that `info` is only seems to be used for the `info.DockerRootDir`, so practically this value can be cached for much longer. I wonder what's the size of `info` if we only use a single field, it looks like a big waste.

I had a similar thoughts for only that field but was being conservative on the timing.  When you say it looks like a big waste do you mean caching the object in memory or the query? If we cached just the string would be better?

> The only concern with cache is the data consistency, that docker will be reinstalled in those 60 seconds... but I doubt it is a big deal.

Is re-installing docker or restarting it while kubelet is running a supported scenario?


> If you can look a bit on savings we get on Linux - it may help to say whether we need it. 

There isn't much savings from Linux side communication across the pipe fast (I will double check this). This why I didn't remove all those calls from linux. The issue on the windows is that it creates a new instance of a named pipe per call to docker. When we make 4 calls to docker over the pipe per container every 10 seconds (calls from eviction manager) it causes quite a bit of I/O. Plus there can be scrapes from other things interested in metrics (metric server and other third part metric tools) which can cause the [response be over 1m 20s ](https://github.com/kubernetes/kubernetes/issues/104283#issue-965577389) even though it was successful.  We don't see this type of latency on Linux.

>limit it to Windows only (Unless there are issues on Linux similar to what I mentioned above) just to limit the scope.

The reason it touched both is because the the function `getContainerStats` that is shared across version `_windows.go` and `_linux.go` needs to take the container not just the id of the container to limit the calls on the windows side.

Since its not expensive on linux those calls don't matter as much and are duplicated but on windows it causes more I/O.  For example we have all the labels/metadata/annotations  about the all the containers from this single call

https://github.com/kubernetes/kubernetes/blob/27d3a9ec57e88567b5a5aebbf59cd1b72e01937c/pkg/kubelet/dockershim/docker_stats.go#L51

but we get it again here for _every_ container even though we already have it

https://github.com/kubernetes/kubernetes/blob/27d3a9ec57e88567b5a5aebbf59cd1b72e01937c/pkg/kubelet/dockershim/docker_stats_windows.go#L75

**Comment by SergeyKanzhelev** [comment]
> > Looking briefly into it feels strange that `info` is only seems to be used for the `info.DockerRootDir`, so practically this value can be cached for much longer. I wonder what's the size of `info` if we only use a single field, it looks like a big waste.
> 
> I had a similar thoughts for only that field but was being conservative on the timing. When you say it looks like a big waste do you mean caching the object in memory or the query? If we cached just the string would be better?

Both. Maybe just store that value in the cache? Also if it really just this string, maybe we need to get status more rare than 60 seconds.

> > The only concern with cache is the data consistency, that docker will be reinstalled in those 60 seconds... but I doubt it is a big deal.
> 
> Is re-installing docker or restarting it while kubelet is running a supported scenario?

It really depends on what data from `info` is used. I'm saying re-install because assuming that just the root dir is used. But if more is used, simple process crash may lead for inconsistency. If for sure we only using DockerRootDir, maybe we can just store it as a constant fir the duration of kubelet lifecycle. No need to even refresh.

> > If you can look a bit on savings we get on Linux - it may help to say whether we need it.
> 
> There isn't much savings from Linux side communication across the pipe fast (I will double check this).

This will be mostly CPU consumed than, rather than real delays. Still a valuable save. With the dockershim gone soon, may not worth your effort checking it.

**Comment by marosset** [comment]
> Also, please correct the release notes if you will proceed with the fix for Linux as well.

I think we should also indicate that these improvements are only for dockershim in the release notes.

**Comment by marosset** [comment]
> The issue on the windows is that it creates a new instance of a named pipe per call to docker. When we make 4 calls to docker over the pipe per container every 10 seconds (calls from eviction manager) it causes quite a bit of I/O.

Since eviction doesn't work on Windows should we just stop having eviction manager make these calls on Windows?

File: pkg/kubelet/dockershim/docker_service.go (hunk 1 above)
Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_service.go:554]: was mimicking https://github.com/kubernetes/kubernetes/pull/104287/files#diff-5aa5f12c1a4791a1ab2b9a0378b27c2a11d5b8cf7f24c26adec1a8b3caf4354dR540

**Comment by jsturtevant** [comment]
> Since eviction doesn't work on Windows should we just stop having eviction manager make these calls on Windows?

That seems like a bigger change that could have unattended consequences.  There is alot of things that happening in that component and I wouldn't want to accidentally disable some aspect that might be partially working which someone took a dependency on. This is more localized so feel more confident in it.

**Comment by marosset** [comment]
> > Since eviction doesn't work on Windows should we just stop having eviction manager make these calls on Windows?
> 
> That seems like a bigger change that could have unattended consequences. There is alot of things that happening in that component and I wouldn't want to accidentally disable some aspect that might be partially working which someone took a dependency on. This is more localized so feel more confident in it.

Fair enough :)

**Comment by jsturtevant** [comment]
Some information from Docker info was already being stored on dockershimservice. I've updated to do something similiar for `dockerRootdir`.  This introduced a potential change since the info was queried but didn't fail if not found.  I looked through history and issues but wasn't able to find out why this wasn't a fatal call although it looks like it could cause issues for configuration.

This might not be a desirable change but I thought I would present it. I am not sure the best way to add the info at this level if it isn't fatal.  There are code paths in new docker service that fail if not able to able to communicate with docker during service set up so not sure why this was different.

**Comment by marosset** [comment]
> Some information from Docker info was already being stored on dockershimservice. I've updated to do something similiar for `dockerRootdir`. This introduced a potential change since the info was queried but didn't fail if not found. I looked through history and issues but wasn't able to find out why this wasn't a fatal call although it looks like it could cause issues for configuration.
> 
> This might not be a desirable change but I thought I would present it. I am not sure the best way to add the info at this level if it isn't fatal. There are code paths in new docker service that fail if not able to able to communicate with docker during service set up so not sure why this was different.

These new changes seem more scoped than the original changes and look good to me from a Windows perspective.

**Comment by jsturtevant** [comment]
these look like flakes
/retest

**Comment by jsturtevant** [comment]
From a latency perspective on a for these improvements for windows, the more happening on the node (ie. if there are pods being created/deleted) the slower the response is.  The value goes up with the number of containers, or concurrent calls as well. 

With a stable cluster (no pods created/deleted) there is a noticeable difference ~480ms to ~280ms. 3 calls to the stats endpoint is chosen as that was number of calls in the initial report (https://github.com/kubernetes/kubernetes/issues/104283).  The difference is dramatic as the number of calls to the endpoint increases (5 concurrent is ~1s vs 450ms)  but is a bit unrealistic in reality, though it simulates multiple calls to the docker pipe during container creation.

```
go run . -l 3 -n capz-conf-n4466 -s 0 
Starting 0 containers on node capz-conf-n4466
pods at start: 14
starting 0 containers
run call to stats 3 times
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 480.129248ms
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 498.438276ms
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 498.858143ms
pods at end: 14
```

After the fix:
```
go run . -l 3 -n capz-conf-n4466 -s 0 
Starting 0 containers on node capz-conf-n4466
pods at start: 14
starting 0 containers
run call to stats 3 times
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 265.476383ms
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 280.700123ms
timing: capz-conf-n4466/proxy/stats/summary?only_cpu_and_memory=true took 297.86408ms
pods at end: 14
```

**Comment by claudiubelu** [comment]
> 
> > > The only concern with cache is the data consistency, that docker will be reinstalled in those 60 seconds... but I doubt it is a big deal.
> > 

Hm, reinstalling docker... Generally, Kubelet and Docker are registered as Services, and Kubelet is set as dependent on Docker. In this scenario, if you'd want to reinstall docker, you'd have to stop the service first, which you can't without stopping Kubelet first, unless forcefully stopping Docker, which automatically stops Kubelet as well. Afterwards, both services will have to be restarted, so this shouldn't be a problem in most cases.

This change is pretty straight-forward, IMO. It shouldn't cause any problems, and it is limited to just Windows Docker.

**Comment by SergeyKanzhelev** [comment]
> if you'd want to reinstall docker, you'd have to stop the service first, which you can't without stopping Kubelet first, unless forcefully stopping Docker, which automatically stops Kubelet as well.

yeah, exactly my thinking... I was just looking for any potential reason that would justify to use cache instead of just reading the value once.

File: pkg/kubelet/dockershim/docker_service.go [hunk 5]
```diff
@@ -257,16 +257,19 @@ func NewDockerService(config *ClientConfig, podSandboxImage string, streamingCon
...
+	dockerInfo, err := ds.client.Info()
+	if err != nil {
+		return nil, fmt.Errorf("Failed to execute Info() call to the Docker client")
+	}
+	klog.InfoS("Docker Info", "dockerInfo", dockerInfo)
+	ds.dockerRootDir = dockerInfo.DockerRootDir
+
 	// skipping cgroup driver checks for Windows
 	if runtime.GOOS == "linux" {
 		// NOTE: cgroup driver is only detectable in docker 1.11+
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/dockershim/docker_service.go:269]: is this comment still needed? Was it here for the call to `.Info`? Also the version mentioned is very old so maybe just drop the comment

File: pkg/kubelet/dockershim/docker_service.go [hunk 6]
```diff
@@ -257,16 +257,19 @@ func NewDockerService(config *ClientConfig, podSandboxImage string, streamingCon
 	ds.network = network.NewPluginManager(plug)
 	klog.InfoS("Docker cri networking managed by the network plugin", "networkPluginName", plug.Name())
 
+	dockerInfo, err := ds.client.Info()
+	if err != nil {
+		return nil, fmt.Errorf("Failed to execute Info() call to the Docker client")
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/dockershim/docker_service.go:262]: this is a change of behavior. If docker is slow to respond, kubelet may fail to start now? I don't think it's a critical change, just leaving this comment for other reviewers to pay attention.

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm

File: pkg/kubelet/dockershim/docker_service.go (hunk 6 above)
Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_service.go:262]: agreed, I called this out here: https://github.com/kubernetes/kubernetes/pull/104287#issuecomment-963710205.  There are other calls to the docker during this time that could cause a failure, so we should be confident that docker is running

Comment (SergeyKanzhelev) [reply pkg/kubelet/dockershim/docker_service.go:262]: yep, I see it now =) Sorry missed it

**Review by SergeyKanzhelev — COMMENTED** [review]
/priority backlog
/lgtm

File: pkg/kubelet/dockershim/docker_stats_windows.go (hunk 3 above)
Comment (jsturtevant) [reply pkg/kubelet/dockershim/docker_stats_windows.go:87]: not this specifically but I added a comment here with some details https://github.com/kubernetes/kubernetes/pull/104287#issuecomment-964702227

**Comment by jsturtevant** [comment]
Woops, I noticed a few white space changes in an unrelated file so I pushed again after the lgtm.  Sorry about that.

**Comment by jsturtevant** [comment]
unrelated flake https://github.com/kubernetes/kubernetes/issues/106326
/retest

**Comment by varshaprasad96** [comment]
Hi @jsturtevant,
k8s 1.23 bug triage here 👋,
Just wanted to follow up and check if this issue is on track for 1.23?

**Comment by marosset** [comment]
> Hi @jsturtevant, k8s 1.23 bug triage here 👋, Just wanted to follow up and check if this issue is on track for 1.23?

We would to have this merged for 1.23. We just need final approval from area owners.

**Review by mrunalp — APPROVED** [review]
