### PR TITLE
Make kube-proxy check if IPv6 is really supported before assuming dual-stack

### LINKED ISSUE #99031: weird error message for ip6tables-save / restore in ipvs kube proxy logs
#### What happened:

(update: likely this is benign, but it seems really weird when your reading kube proxy logs) 

- in healthy, IPTABLES jobs, the various ip6tables-restore commands are happy.... 
```

I0212 11:19:29.343337       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
I0212 11:19:29.345654       1 proxier.go:1651] "Deleting conntrack stale entries for Services" ips=[]
I0212 11:19:29.345723       1 proxier.go:1657] "Deleting conntrack stale entries for Services" nodeports=[]
I0212 11:19:29.345765       1 proxier.go:1664] "Deleting stale endpoint connections" endpoints=[]
I0212 11:19:29.345779       1 proxier.go:830] "syncProxyRules complete" elapsed="53.750935ms"
```
- MEANWHILE  in ipvs jobs (healthy, or non healthy, we see that some of the iptables dont exist which makes sense...   why is ipvs kube proxy tyrying to do iptables-restore operations on  the `nat` table ?  why is it trying to do iptables stuff *at all* ?  
```
I0212 11:16:50.747339       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
E0212 11:16:50.751646       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'
```

It seems like we get `iptables-restore` error messages when running ipv6.  not sure why though? in particular i found these errors when looking at the test failures for https://github.com/kubernetes/kubernetes/issues/99018 

#### What you expected to happen:

You wouldnt see error messages for ip6tables-restore when running ipvs tests.  This may be my own ignorance however, i.e. maybe this is normal. 

#### How to reproduce it (as minimally and precisely as possible):

I guess every job has this (wether or not the job passes or fails) ?  Here is an example from a passing test.... 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360184247821799424/artifacts/bootstrap-e2e-minion-group-0q7f/kube-proxy.log 

Similar logs from a failing tests that i originally saw this message ...

- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-kj6x/kube-proxy.log 
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-1l3l/kube-proxy.log
- https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1360165096948502528/artifacts/bootstrap-e2e-minion-group-m52w/kube-proxy.log

has this failure, it is reproduced via the corresponding ci job ...

the logs in the kube-proxy for one of the nodes look like this:

```
I0212 10:03:39.735971       1 bounded_frequency_runner.go:304] sync-runner: 1.022588529s since last run, possible in 8.977411471s, scheduled in 8.977434941s
I0212 10:03:41.058181       1 config.go:351] Calling handler.OnServiceUpdate
I0212 10:03:41.058238       1 service.go:279] Service esipp-4128/external-local-pods updated: 1 ports
I0212 10:03:41.058268       1 bounded_frequency_runner.go:304] sync-runner: 2.344886585s since last run, possible in 7.655113415s, scheduled in 7.655135774s
I0212 10:03:41.181710       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:43.685594       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:43.685696       1 bounded_frequency_runner.go:304] sync-runner: 4.972312847s since last run, possible in 5.027687153s, scheduled in 5.027702757s
I0212 10:03:44.147732       1 config.go:260] Calling handler.OnEndpointSliceUpdate
I0212 10:03:44.147818       1 bounded_frequency_runner.go:304] sync-runner: 5.43443661s since last run, possible in 4.56556339s, scheduled in 4.565586328s
I0212 10:03:47.619505       1 config.go:334] Calling handler.OnServiceAdd
I0212 10:03:47.619552       1 utils.go:179] Skipping service test in namespace statefulset-4758 due to clusterIP = "None"
I0212 10:03:47.619574       1 utils.go:179] Skipping service test in namespace statefulset-4758 due to clusterIP = "None"
I0212 10:03:47.619592       1 bounded_frequency_runner.go:304] sync-runner: 8.906210899s since last run, possible in 1.093789101s, scheduled in 1.093830216s
I0212 10:03:48.206917       1 proxier.go:1063] Syncing ipvs Proxier rules
I0212 10:03:48.206970       1 iptables.go:351] running ip6tables-save [-t filter]
I0212 10:03:48.209648       1 iptables.go:351] running ip6tables-save [-t nat]
E0212 10:03:48.213253       1 proxier.go:1949] Failed to execute iptables-save, syncing all rules: exit status 1
E0212 10:03:48.216444       1 proxier.go:1907] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": exit status 3: ip6tables v1.8.5 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
I0212 10:03:48.261278       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
E0212 10:03:48.264469       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
)
Rules:
*nat
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-POSTROUTING -m mark ! --mark 0x00004000/0x00004000 -j RETURN
-A KUBE-POSTROUTING -j MARK --xor-mark 0x00004000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-MARK-MASQ -j MARK --or-mark 0x00004000
COMMIT
*filter
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x00004000/0x00004000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-NODE-PORT -m comment --comment "Kubernetes health check node port" -m set --match-set KUBE-6-HEALTH-CHECK-NODE-PORT dst -j ACCEPT
COMMIT
I0212 10:03:48.264493       1 proxier.go:1042] syncProxyRules took 57.601179ms
```
#### Anything else we need to know?:

ill add more links as i collect more data.  

#### Environment:
- Kubernetes version (use `kubectl version`): prow (main branch as of feb 12 2021)

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Now that the dual stack feature gate is enabled by default, kube-proxy defaults to trying to run dual stack (regardless of the cluster configuration), but some nodes have no IPv6 support, resulting in lots of spurious errors.

#### Which issue(s) this PR fixes:
Fixes #99031

#### Special notes for your reviewer:
@aojea I wrote this before noticing #99066... but this version is much smaller and more back-port-able. Maybe we want to merge pieces of both PRs together

#### Does this PR introduce a user-facing change?
-->
```release-note
Fixes spurious errors about IPv6 in kube-proxy logs on nodes with IPv6 disabled.
```

/priority important-soon
/sig network

### CODE REVIEW

File: cmd/kube-proxy/app/server_others.go [hunk 1]
```diff
@@ -181,27 +173,48 @@ func newProxyServer(
...
+	if dualStack {
+		// Create iptables handlers for both families, one is already created
+		// Always ordered as IPv4, IPv6
+		if primaryProtocol == utiliptables.ProtocolIPv4 {
+			ipt[0] = iptInterface
+			ipt[1] = utiliptables.New(execer, utiliptables.ProtocolIPv6)
+
+			// Just because the feature gate is enabled doesn't mean the node
+			// actually supports dual-stack
+			if _, err := ipt[1].ChainExists(utiliptables.TableFilter, utiliptables.ChainInput); err != nil {
```
Comment (aojea) [inline cmd/kube-proxy/app/server_others.go:193]: the error in the CI only happens in the table NAT

> > I0212 20:00:52.552777       1 iptables.go:351] running ip6tables-save [-t filter]
> I0212 20:00:52.555445       1 iptables.go:351] running ip6tables-save [-t nat]
> E0212 20:00:52.559906       1 proxier.go:1949] Failed to execute iptables-save, syncing all rules: exit status 1
> E0212 20:00:52.563206       1 proxier.go:1907] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": exit status 3: ip6tables v1.8.5 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
> Perhaps ip6tables or your kernel needs to be upgraded.
> I0212 20:00:52.625278       1 iptables.go:416] running ip6tables-restore [-w 5 -W 100000 --noflush --counters]
> E0212 20:00:52.629072       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'
> 
> Error occurred at line: 1
> Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
> )
> Rules:
> *nat

File: cmd/kube-proxy/app/server_others.go [hunk 2]
```diff
@@ -181,27 +173,48 @@ func newProxyServer(
...
+				klog.Warningf("No iptables support for IPv6: %v", err)
+				dualStack = false
+			}
+		} else {
+			ipt[0] = utiliptables.New(execer, utiliptables.ProtocolIPv4)
+			ipt[1] = iptInterface
+		}
+	}
+	if dualStack {
+		klog.V(0).Infof("kube-proxy running in dual-stack mode, %s-primary", iptInterface.Protocol)
```
Comment (aojea) [inline cmd/kube-proxy/app/server_others.go:203]: this is not correctly casted

> I0216 18:59:55.179544       1 server_others.go:203] kube-proxy running in dual-stack mode, %!s(func() iptables.Protocol=0x1786e80)-primary

**Comment by aojea** [comment]
> @aojea I wrote this before noticing #99066... but this version is much smaller and more back-port-able. Maybe we want to merge pieces of both PRs together

This is much better :+1:  ... the service IP family detection from the other PR can be done as a follow up, and we can get rid of the bindAddress hack

File: cmd/kube-proxy/app/server_others.go [hunk 3]
```diff
@@ -181,27 +173,48 @@ func newProxyServer(
...
+
+			// Just because the feature gate is enabled doesn't mean the node
+			// actually supports dual-stack
+			if _, err := ipt[1].ChainExists(utiliptables.TableFilter, utiliptables.ChainInput); err != nil {
+				klog.Warningf("No iptables support for IPv6: %v", err)
+				dualStack = false
+			}
+		} else {
+			ipt[0] = utiliptables.New(execer, utiliptables.ProtocolIPv4)
+			ipt[1] = iptInterface
```
Comment (aojea) [inline cmd/kube-proxy/app/server_others.go:199]: do you think we'll see the day that this fail because IPv4 is disabled in the host? :upside_down_face:

File: cmd/kube-proxy/app/server_others.go (hunk 1 above)
Comment (aojea) [reply cmd/kube-proxy/app/server_others.go:193]: that I think for kube-proxy is the more important table to monitor

Comment (aojea) [reply cmd/kube-proxy/app/server_others.go:193]: we need to check the nat table, the kube-proxy logs keep showing the same error with this PR

Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:193]: Yes, but I assume it fails on `nat` because trying to reference the `nat` table is the very first thing we do ("`Error occurred at line: 1`") not because the problem is specific to `nat`.

File: cmd/kube-proxy/app/server_others.go (hunk 3 above)
Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:199]: I doubt any of this code will still be around then. The kernel does not currently support disabling IPv4.

File: cmd/kube-proxy/app/server_others.go (hunk 1 above)
Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:193]: That said, this PR does not fix the problem.

    I0216 19:46:49.653776       1 server_others.go:137] Detected node IP 10.40.0.5
    I0216 19:46:49.684755       1 server_others.go:203] kube-proxy running in dual-stack mode, %!s(func() iptables.Protocol=0x1786e80)-primary
    ...
    E0216 19:46:50.139766       1 proxier.go:1619] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.8.5 (legacy): ip6tables-restore: unable to initialize table 'nat'

but

    Feb 16 19:44:18.154608 localhost kernel: Linux version 5.4.49+ ...

so it's not "the kernel is older than 3.7"

Comment (aojea) [reply cmd/kube-proxy/app/server_others.go]: the problem is that those nodes doesn't have the the kernel ipv6 nat module loaded,

https://github.com/kubernetes/test-infra/blob/2abb7ff26579325f6a335990003f665755c96d7a/images/krte/wrapper.sh#L77-L78

we had to loaded it in order ip6tables to work

```
  # enable ipv6 iptables
  modprobe -v ip6table_nat
```

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gci-gce-ipvs
this is the one reporting the error, because it runs in a different cluster with the nodes that blacklist the kernel module for nat ipv6

**Comment by dcbw** [comment]
I presume there's no way to do unit tests for this?

**Comment by aojea** [comment]
@danwinship[ it works ](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/99127/pull-kubernetes-e2e-gci-gce-ipvs/1362048993026117632/artifacts/e2e-baf67c8e28-2e794-minion-group-g46s/kube-proxy.log):clap: 

> I0217 14:53:18.118226       1 server_others.go:174] DetectLocalMode: 'NodeCIDR'
> I0217 14:53:18.151595       1 iptables.go:624] DEBUG: ChainExists %#v output
> %s
> %v[POSTROUTING -t nat]ip6tables v1.8.5 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
> Perhaps ip6tables or your kernel needs to be upgraded.
> exit status 3
> W0217 14:53:18.151639       1 server_others.go:194] No iptables support for IPv6: exit status 3
> I0217 14:53:18.151659       1 server_others.go:205] kube-proxy running in single-stack IPv4 mode
> I0217 14:53:18.151672       1 server_others.go:271] Using ipvs Proxier.

**Comment by danwinship** [comment]
>  W0217 14:53:18.151639 1 server_others.go:194] No iptables support for IPv6: exit status 3

great error reporting there but that's a general utiliptables problem.

repushed without the debug commit. Should be ready to go now

**Comment by danwinship** [comment]
> I presume there's no way to do unit tests for this?

It's _possible_... we'd have to refactor kube-proxy startup to make this subpart of it independently testable... but it would be kind of vacuous. "If we hack it so iptables returns exactly the specific error we're testing for, then kube-proxy will fall back to single-stack". It doesn't really prove that the code actually does the right thing in any real environment.

File: cmd/kube-proxy/app/server_others.go [hunk 4]
```diff
@@ -181,27 +173,48 @@ func newProxyServer(
...
+		}
+	}
+	if dualStack {
+		klog.V(0).Infof("kube-proxy running in dual-stack mode, %s-primary", iptInterface.Protocol())
```
Comment (aojea) [inline cmd/kube-proxy/app/server_others.go:203]: has `primaryProtocol` the same problem logging the error?

Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:203]: you mean logging `%!s(func() iptables.Protocol=0x1786e80)` ? No, the problem is that `iptables.Protocol` is a function that returns a string but I was previously treating it as a string. `primaryProtocol` actually is a string.

**Comment by aojea** [comment]
/retest
unrelated sig-storage tests

**Comment by aojea** [comment]
ping @dcbw for final approval

**Comment by dcbw** [comment]
CI system issues...
```
Init container initupload not ready: (state: terminated, reason: "Error", message: ".com/token\\\": dial tcp: i/o timeout writer close error: Post \\\"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\\u0026name=pr-logs%2Fpull%2F99127%2Fpull-kubernetes-bazel-build%2F1362409247526096896%2Fclone-log.txt\\u0026prettyPrint=false\\u0026projection=full\\u0026uploadType=multipart\\\": oauth2: cannot fetch token: Post \\\"https://oauth2.googleapis.com/token\\\": dial tcp: i/o timeout writer close error: Post \\\"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\\u0026name=pr-logs%2Fpull%2F99127%2Fpull-kubernetes-bazel-build%2F1362409247526096896%2Fstarted.json\\u0026prettyPrint=false\\u0026projection=full\\u0026uploadType=multipart\\\": oauth2: cannot fetch token: Post \\\"https://oauth2.googleapis.com/token\\\": dial tcp: i/o timeout writer close error: Post \\\"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\\u0026name=pr-logs%2Fdirectory%2Fpull-kubernetes-bazel-build%2F1362409247526096896.txt\\u0026prettyPrint=false\\u0026projection=full\\u0026uploadType=multipart\\\": oauth2: cannot fetch token: Post \\\"https://oauth2.googleapis.com/token\\\": dial tcp: i/o timeout writer close error: Post \\\"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\\u0026name=pr-logs%2Fpull%2F99127%2Fpull-kubernetes-bazel-build%2F1362409247526096896%2Ffinished.json\\u0026prettyPrint=false\\u0026projection=full\\u0026uploadType=multipart\\\": oauth2: cannot fetch token: Post \\\"https://oauth2.googleapis.com/token\\\": dial tcp: i/o timeout writer close error: Post \\\"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\\u0026name=pr-logs%2Fdirectory%2Fpull-kubernetes-bazel-build%2Flatest-build.txt\\u0026prettyPrint=false\\u0026projection=full\\u0026uploadType=multipart\\\": oauth2: cannot fetch token: Post \\\"https://oauth2.googleapis.com/token\\\": dial tcp: i/o timeout]\",\"file\":\"prow/cmd/initupload/main.go:45\",\"func\":\"main.main\",\"level\":\"fatal\",\"msg\":\"Failed to initialize job\",\"severity\":\"fatal\",\"time\":\"2021-02-18T14:47:26Z\"}\n") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")
```
/retest
