### PR TITLE
Match both old and new kubectl version for a while in e2e

### LINKED ISSUE #119230: [Failing test] Kubectl client Kubectl version should check is all data is printed (capz-windows-master)
### Which jobs are failing?

master-informing:
- capz-windows-master

### Which tests are failing?

`Kubernetes e2e suite.[It] [sig-cli] Kubectl client Kubectl version should check is all data is printed [Conformance]`

Image

### Since when has it been failing?

07-10 17:46 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Reason for failure (if possible)

```
{ failed [FAILED] Item Client Version:  value is not valid in Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.4.71+86038ae5906dfa", GitCommit:"86038ae5906dfa64c6f8e7d44aecb87400298db8", GitTreeState:"clean", BuildDate:"2023-07-11T11:53:24Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}

In [It] at: test/e2e/kubectl/kubectl.go:1680 @ 07/11/23 15:54:03.879
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig cli
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind failing-test
/kind flake

/sig cli
/sig testing

#### What this PR does / why we need it:
In https://github.com/kubernetes/kubernetes/pull/116720 I dropped the deprecated long version, but our [release informing](https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master) jobs are using an older version of kubectl which still prints the long version. 

Based on that, given our compatibility guarantees I'll match either the new or the old version until 1.30. 

#### Which issue(s) this PR fixes:
Fixes #119230

#### Special notes for your reviewer:
/assign @ardaguclu 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/kubectl/kubectl.go [hunk 1]
```diff
@@ -1676,7 +1676,12 @@ metadata:
 			// we expect following values for: Major -> digit, Minor -> numeric followed by an optional '+',  GitCommit -> alphanumeric
 			requiredItems := []string{"Client Version: ", "Server Version: "}
 			for _, item := range requiredItems {
-				if matched, _ := regexp.MatchString(item+`v\d\.\d+\.[\d\w\-\.\+]+`, versionString); !matched {
+				// prior to 1.28 we printed long version information
+				oldMatched, _ := regexp.MatchString(item+`version.Info\{Major:"\d", Minor:"\d+\+?", GitVersion:"v\d\.\d+\.[\d\w\-\.\+]+", GitCommit:"[0-9a-f]+"`, versionString)
```
Comment (ardaguclu) [inline test/e2e/kubectl/kubectl.go:1680]: We can not run `kubectl version -ojson` because kubectl is still old and will fail?.

Comment (soltysh) [reply test/e2e/kubectl/kubectl.go:1680]: we could, but I don't want that, I want the bare `kubectl version` output here, only

**Comment by soltysh** [comment]
/test pull-kubernetes-conformance-kind-ga-only-parallel
unrelated failure
