### PR TITLE
Remove --config option from suggest kubeadm command

### LINKED ISSUE #3201: No `--config` for kubeadm init phase upload-config in > 1.31
### What happened?

**Issue Overview**
When trying to upgrade a cluster using `kubeadm`, the command returns some hints to upload user configuration to a config map:
```
core@fcos-k8s:~$ sudo kubeadm upgrade plan
[preflight] Running pre-flight checks.
[upgrade/config] Reading configuration from the "kubeadm-config" ConfigMap in namespace "kube-system"...
[upgrade/config] Use 'kubeadm init phase upload-config --config your-config-file' to re-upload it.
[upgrade] Running cluster health checks
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: 1.33.1
[upgrade/versions] kubeadm version: v1.33.0
[upgrade/versions] Target version: v1.33.1
[upgrade/versions] Latest version in the v1.33 series: v1.33.1
```

Coming from:
```
cmd/kubeadm/app/util/config/cluster.go|64 col 98| _, _ = printer.Printf("[%s] Use 'kubeadm init phase upload-config --config your-config-file' to re-upload it.\n", logPrefix)
cmd/kubeadm/app/cmd/upgrade/apply.go|236 col 105| _, _ = printer.Printf("[upgrade] Use 'kubeadm init phase upload-config --config your-config.yaml' to re-upload it.\n")

```

But the `--config` option isn't valid - at least in 1.33 for `kubeadm`:
```
core@fcos-k8s:~$ kubeadm init phase upload-config --config /var/lib/kubelet/config.yaml
unknown flag: --config
To see the stack trace of this error execute with --v=5 or higher
```

It seems like the correct way to do this is now by specifying which config to upload by name, or `all`:
```
core@fcos-k8s:~$ kubeadm init phase upload-config
Upload the kubeadm and kubelet configuration to a ConfigMap

Usage:
  kubeadm init phase upload-config [flags]
  kubeadm init phase upload-config [command]

Aliases:
  upload-config, uploadconfig

Available Commands:
  all         Upload all configuration to a config map
  kubeadm     Upload the kubeadm ClusterConfiguration to a ConfigMap
  kubelet     Upload the kubelet component config to a ConfigMap

Flags:
  -h, --help   help for upload-config

Global Flags:
      --add-dir-header   If true, adds the file directory to the header of the log messages
      --rootfs string    The path to the 'real' host root filesystem. This will cause kubeadm to chroot into the provided path.
      --skip-headers     If true, avoid header prefixes in the log messages
  -v, --v Level          number for the log level verbosity
```

So, this command for example works fine:
```
core@fcos-k8s:~$ sudo !!
sudo kubeadm init phase upload-config all
[upload-config] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config" in namespace kube-system with the configuration for the kubelets in the cluster
```

**Suggestion**
Should we remove the suggestion to use `--config` and instead just suggest that users use `all`?
```
cmd/kubeadm/app/util/config/cluster.go|64 col 98| _, _ = printer.Printf("[%s] Use 'kubeadm init phase upload-config --config your-config-file' to re-upload it.\n", logPrefix)
cmd/kubeadm/app/cmd/upgrade/apply.go|236 col 105| _, _ = printer.Printf("[upgrade] Use 'kubeadm init phase upload-config --config your-config.yaml' to re-upload it.\n")
```

### What did you expect to happen?

The command should return a suggestion that will work for users on their version of k8s and kubeadm.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster using 1.31 kubeadm:
```
sudo kubeadm init
```

Run the upgrade command:
```
kubeadm init phase upload-config --config /var/lib/kubelet/config.yaml
```

Observe the error:
```
core@fcos-k8s:~$ kubeadm init phase upload-config --config /var/lib/kubelet/config.yaml
unknown flag: --config
To see the stack trace of this error execute with --v=5 or higher
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

</details>

### Cloud provider

<details>
nil. Just a baremetal env
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="42.20250427.3.0 (CoreOS)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=42
VERSION_CODENAME=""
PLATFORM_ID="platform:f42"
PRETTY_NAME="Fedora CoreOS 42.20250427.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:42"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=42
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=42
SUPPORT_END=2026-05-13
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='42.20250427.3.0'
$ uname -a
Linux fcos-k8s.bne-home.net 6.14.3-300.fc42.x86_64 kubernetes/kubernetes#1 SMP PREEMPT_DYNAMIC Sun Apr 20 16:08:39 UTC 2025 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm:
```
core@fcos-k8s:~$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"33", EmulationMajor:"", EmulationMinor:"", MinCompatibilityMajor:"", MinCompatibilityMinor:"", GitVersion:"v1.33.0", GitCommit:"60a317eadfcb839692a68eab88b2096f4d708f4f", GitTreeState:"archive", BuildDate:"2025-04-23T00:00:00Z", GoVersion:"go1.24.2", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
core@fcos-k8s:~$ crio version
INFO[2025-05-18T16:23:47.229418638+10:00] Updating config from single file: /etc/crio/crio.conf
INFO[2025-05-18T16:23:47.229436289+10:00] Updating config from drop-in file: /etc/crio/crio.conf
INFO[2025-05-18T16:23:47.230743215+10:00] Updating config from path: /etc/crio/crio.conf.d
Version:        1.32.4
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2025-05-02T18:03:10Z_Release:1.fc42
GoVersion:      go1.24.2
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  rpm_crashtraceback
  seccomp
  selinux
  exclude_graphdriver_devicemapper
LDFlags:           -X  github.com/cri-o/cri-o/internal/version.buildDate=2025-05-02T18:03:10Z_Release:1.fc42   -B 0x2cd599b4ced5da8b201a6abf7fe447e25e8b6c67 -compressdwarf=false -linkmode=external -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -Wl,-z,undefs'
SeccompEnabled:   true
AppArmorEnabled:  false
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bshephar**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This change removes the --config option from the kubeadm init phase upload-config command that we suggest to users. Kubeadm doesn't have handling for this flag in the latest releases, so this change conforms with the current status and suggests the more simplified command option to upload all config files instead.

#### Which issue(s) this PR fixes: 131831

Fixes: https://github.com/kubernetes/kubeadm/issues/3201

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/upgrade/apply.go [hunk 1]
```diff
@@ -233,7 +233,7 @@ func newApplyData(cmd *cobra.Command, args []string, applyFlags *applyFlags) (*a
 	if err != nil {
 		if apierrors.IsNotFound(err) {
 			_, _ = printer.Printf("[upgrade] In order to upgrade, a ConfigMap called %q in the %q namespace must exist.\n", constants.KubeadmConfigConfigMap, metav1.NamespaceSystem)
-			_, _ = printer.Printf("[upgrade] Use 'kubeadm init phase upload-config --config your-config.yaml' to re-upload it.\n")
+			_, _ = printer.Printf("[upgrade] Use 'kubeadm init phase upload-config all' to re-upload it.\n")
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/cmd/upgrade/apply.go:236]: Can you modify this line based on the suggestion in the comment (https://github.com/kubernetes/kubeadm/issues/3201#issuecomment-2888811130)?

Comment (HirazawaUi) [inline cmd/kubeadm/app/cmd/upgrade/apply.go:236]:
```suggestion
			_, _ = printer.Printf("[upgrade/config] Use 'kubeadm init phase upload-config kubeadm --config your-config-file' to re-upload it.\n")
```

Comment (bshephar) [reply cmd/kubeadm/app/cmd/upgrade/apply.go]: Ack, I also changed the second reference to this command as well in:
https://github.com/kubernetes/kubernetes/pull/131832/files#diff-d9520473ad3de82e8118c7fb75b34ac28d71f3701ed91ca973e3d4c2e19e61ebR63
