### PR TITLE
Work around for PDs stop mounting after a few hours issue

### LINKED ISSUE #9994: Persistent Disk mount test sometimes fails to delete disk
The "`Pod Disks should schedule a pod w/ a readonly PD on two hosts, then remove both`" E2E test will sometimes fail because it fails to delete the PD used in the test after the test is finished.

The error:
```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:187
Error deleting PD
Expected error:
    <*exec.ExitError | 0xc208035ea8>: {
        ProcessState: {
            pid: 10524,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 428000},
                Stime: {Sec: 0, Usec: 48000},
                Maxrss: 39024,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 19580,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 32,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 62,
                Nivcsw: 27,
            },
        },
    }
    exit status 1
not to have occurred
```

Detailed test log:
```
===================================
Random Seed: 1434502630 - Will randomize all specs
Will run 2 of 86 specs

SSSSSSS
------------------------------
Pod Disks 
  should schedule a pod w/ a readonly PD on two hosts, then remove both.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:187
[BeforeEach] Pod Disks
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:63
>>> testContext.KubeConfig: /usr/local/google/home/saadali/.kube/config
[It] should schedule a pod w/ a readonly PD on two hosts, then remove both.
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:187
STEP: creating PD
STEP: submitting rwPod to ensure PD is formatted
INFO: Waiting up to 5m0s for pod pd-test-ce826684-148b-11e5-8fe7-f0921cde18c1            status to be running
INFO: Waiting for pod pd-test-ce826684-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (40.185418ms elapsed)
INFO: Waiting for pod pd-test-ce826684-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (5.080065636s elapsed)
INFO: Waiting for pod pd-test-ce826684-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (10.120245467s elapsed)
STEP: submitting host0ROPod to kubernetes
STEP: submitting host1ROPod to kubernetes
INFO: Waiting up to 5m0s for pod pd-test-ce82688d-148b-11e5-8fe7-f0921cde18c1            status to be running
INFO: Waiting for pod pd-test-ce82688d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (39.613602ms elapsed)
INFO: Waiting up to 5m0s for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            status to be running
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (40.657896ms elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (5.081138448s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (10.124147413s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (15.16559385s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (20.205778834s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (25.246490617s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (30.28698796s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (35.327289576s elapsed)
INFO: Waiting for pod pd-test-ce82693d-148b-11e5-8fe7-f0921cde18c1            in namespace 'default' status to be 'running'(found phase: "Pending", readiness: false) (40.371424117s elapsed)
STEP: deleting host0ROPod
STEP: deleting host1ROPod
STEP: deleting PD "e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1"
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
INFO: Couldn't delete PD. Sleeping 5 seconds
STEP: cleaning up PD-RO test environment

• Failure [255.246 seconds]
Pod Disks
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:188
  should schedule a pod w/ a readonly PD on two hosts, then remove both. [It]
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:187

  Error deleting PD
  Expected error:
      <*exec.ExitError | 0xc208036b40>: {
          ProcessState: {
              pid: 12383,
              status: 256,
              rusage: {
                  Utime: {Sec: 0, Usec: 250389},
                  Stime: {Sec: 0, Usec: 52537},
                  Maxrss: 35048,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 22735,
                  Majflt: 0,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 32,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 0,
                  Nvcsw: 64,
                  Nivcsw: 58,
              },
          },
      }
      exit status 1
  not to have occurred

  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:186
```

The disk that fails to delete still shows up in `/dev/disk/by-id/`:
```
root@e2e-test-saadali-minion-0knj:/home/saadali# ls /dev/disk/by-id/
google-e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1  scsi-0Google_PersistentDisk_e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1
google-persistent-disk-0                         scsi-0Google_PersistentDisk_persistent-disk-0
google-persistent-disk-0-part1                   scsi-0Google_PersistentDisk_persistent-disk-0-part1
```

My attempts to manually try to delete the PD fail with:
```
gcloud -q compute --project=saads-vms2 disks delete --zone=us-central1-b e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1
ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
 - The disk resource 'e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1' is already being used by 'e2e-test-saadali-minion-0knj'
```

`udevadm trigger` (the work around for #7972) doesn't change anything here:
```
root@e2e-test-saadali-minion-0knj:/home/saadali# udevadm trigger
root@e2e-test-saadali-minion-0knj:/home/saadali# ls /dev/disk/by-id/
google-e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1  scsi-0Google_PersistentDisk_e2e-cc09ef6a-148b-11e5-8fe7-f0921cde18c1
google-persistent-disk-0                         scsi-0Google_PersistentDisk_persistent-disk-0
google-persistent-disk-0-part1                   scsi-0Google_PersistentDisk_persistent-disk-0-part1
```

### PR DESCRIPTION
**Pull request by saad-ali**
This is a temporary work around for #7972 and fixes #9994 (and is a follow-up to PR #9929).

The problem was that if we repeatedly create, attach, mount, unmount, detach, and delete a PD from a GCE instance (PD soak test did this), after a few hours the GCE instance gets corrupted and stops attaching PDs correctly.

The real fix lies on the GCE side, in the meantime, they suggest calling `udevadm trigger` as a work around. @quinton-hoole dug in to `udevadm trigger` and suggested that we target the trigger more narrowly to the device being mounted/unmounted to prevent any unintended side effects.

In addition to calling `udevadm trigger` on the device being attached/detached, this adds logic to verify that a disk detach completed (for #9994) and adds robust retry logic for both attaches and detaches.

Tested this locally by running PD tests back to back for hours. Although it is much more stable than before, the tests still flake out every few hours (disk doesn't attach or detach properly). But when this happens it doesn't leave the machine unable to attach any new disks (as was the case before this fix).

CC @quinton-hoole  @brendanburns @dchen1107

### CODE REVIEW

**Comment by saad-ali** [comment]
Per new merge policy, risk assessment for this PR: this PR touches GCE Volume PD attach and detach code. I'd consider this a critical bug fix, that'll improve system stability--without this PR, GCE Volume PD attachment may stop working after some time on some nodes.

File: pkg/volume/gce_pd/gce_util.go [hunk 1]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+		if !sdexists[sd] {
+			udevadmChangeToDrive(sd)
+		}
+	}
+}
+
+// Calls "udevadm trigger --action=change" on the specified drive.
+// drivePath must be the the block device path to trigger on, in the format "/dev/sd*", or a symlink to it.
+// This is workaround for Issue #7972. Once the underlying issue has been resolved, this may be removed.
+func udevadmChangeToDrive(drivePath string) {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Lets try to split this function up, it does too many things.

File: pkg/volume/gce_pd/gce_util.go [hunk 2]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+	glog.Infof("udevadmChangeToDrive: drive=%q", drivePath)
+
+	// Evaluate symlink, if any
+	drive, err := filepath.EvalSymlinks(drivePath)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: You should only do this if it is in fact a sym link.

File: pkg/volume/gce_pd/gce_util.go [hunk 3]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+	if err != nil {
+		glog.Errorf("udevadmChangeToDrive: filepath.EvalSymlinks(%q) failed with %v.", drivePath, err)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: This is not in fact an error if the path was not a sym link.  Perhaps pass in a flag to indicate whether or not the path is supposed be a sym link?

**Comment by quinton-hoole** [comment]
More to come on this review.  I'll get back on it tomorrow - gotta run, sorry.

File: pkg/volume/gce_pd/gce_util.go (hunk 1 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: I would prefer to leave this as one function since it is implementing temporary behavior that I'd like to keep all together (and remove all together when the time comes). Let me know if you feel strongly otherwise.

File: pkg/volume/gce_pd/gce_util.go (hunk 2 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: If a path is not a symlink `evalSymlinks` simply returns the same path, it does not error. For example, `/dev/sda` would just return `/dev/sda`. Since there is no harm in calling this on a non-symlink path and it helps avoid unnecessarily adding logic to decide when it should be called, I'll leave it as is. Let me know if you disagree.

File: pkg/volume/gce_pd/gce_util.go (hunk 3 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: As mentioned above, `evalSymlinks` does not return an error if a path is not a symlink, it simply returns the same path. It will return an error if the path doesn't exist, in which case it makes sense to both log an error and abort the rest of this function.

File: pkg/volume/gce_pd/gce_util.go (hunk 1 above)
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: I think that you can put the split functions into a separate source file if you want to make it easy to delete them together at a later date.  I actually suspect that this code might be required for some time still, given that the underlying GCE fix does not in fact directly address the fact that udev events are not being processed strictly correctly (which this PR works around).

I will leave the decision to you, but if there are bugs in this code, we're going to need to split it up to debug effectively.

Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: And you're definitely going to need to write unit and integration tests for this code, which is going to be easier if you split up the function.

File: pkg/volume/gce_pd/gce_util.go (hunk 2 above)
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Aah - yes, that makes sense.

File: pkg/volume/gce_pd/gce_util.go (hunk 3 above)
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Agreed.

File: pkg/volume/gce_pd/gce_util.go [hunk 4]
```diff
@@ -58,6 +66,12 @@ func (util *GCEDiskUtil) AttachAndMountDisk(pd *gcePersistentDisk, globalPDPath
 	devicePath := ""
 	// Wait for the disk device to be created
 	for {
+		sdAfter, err := filepath.Glob("/dev/sd*")
+		if err != nil {
+			glog.Errorf("Error filepath.Glob(\"/dev/sd*\"): %v\r\n", err)
+		}
+		udevadmChangeToNewDrives(sdBefore, sdAfter)
+
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Not new code below, but this causes kubelet to go to sleep for 1 second, perhaps 10 times in a row, as far as I understand.  Is this in a separate go rountine?

Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: @dchen1107 @lavalamp I'm being a bit lazy here, but what is the preferred way of doing these sorts of retries inside kubelet?

Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: It should block only one pod and not the entire queue. I'm not clear on why this is a ```for {``` loop rather than a ```for numTries := 0; numTries < 10; numTries++ {``` loop.

File: pkg/volume/gce_pd/gce_util.go [hunk 5]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
 	if err := gce.(*gce_cloud.GCECloud).DetachDisk(pd.pdName); err != nil {
 		return err
 	}
+
+	devicePaths := []string{
+		path.Join("/dev/disk/by-id/", "google-"+pd.pdName),
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: These are cut-n-pasted literal strings from AttachAndMountDisk().  Please factor out the code, or move to named constants.

File: pkg/volume/gce_pd/gce_util.go [hunk 6]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+	}
+
+	if pd.partition != "" {
+		for i, path := range devicePaths {
+			devicePaths[i] = path + "-part" + pd.partition
+		}
+	}
+	numTries := 0
+	// Wait for the disk device to detach
+	for {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Same comment as above.  Please avoid cut-n-paste code.

File: pkg/volume/gce_pd/gce_util.go [hunk 7]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+		time.Sleep(time.Second)
+	}
+
 	return nil
 }
 
+// Calls "udevadm trigger --action=change" for newly created "/dev/sd*" drives (exist only in after set).
+// This is workaround for Issue #7972. Once the underlying issue has been resolved, this may be removed.
+func udevadmChangeToNewDrives(sdBefore, sdAfter []string) {
+	sdexists := make(map[string]bool)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: You can remove most of this function by using pkg/util/set.go which includes StringSet.Has()

File: pkg/volume/gce_pd/gce_util.go [hunk 8]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+	if err != nil {
+		glog.Errorf("udevadmChangeToDrive: filepath.EvalSymlinks(%q) failed with %v.", drivePath, err)
+		return
+	}
+	glog.V(5).Infof("udevadmChangeToDrive: symlink path is %q", drive)
+
+	// Check to make sure input is "/dev/sd*"
+	if !strings.Contains(drive, "/dev/sd") {
+		glog.Errorf("udevadmChangeToDrive: expected input in the form \"/dev/sd*\" but drive is %q.", drive)
+		return
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: You need to return an error here, not just log it.  Same for each similar case below.

File: pkg/volume/gce_pd/gce_util.go [hunk 9]
```diff
@@ -122,9 +137,111 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+	}
+
+	// Get the DEVPATH for the specified block device
+	udevInfoOutBytes, err := exec.New().Command("udevadm", "info", "--q=all", fmt.Sprintf("--name=%s", drive)).CombinedOutput()
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: So I've poked around a bit and I think that we can remove most of this code.
example:
$ /sbin/udevadm trigger --action=change --verbose --property-match=DEVNAME=/dev/sd
b
/sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:2/0:0:2:0/block/sdb

So basically you can remove the "udevadmin info" invocation, and all the stuff to parse out DEVPATH. 

And the "udevadmin trigger" command reduces to just:

udevadmin trigger --action=change --property-match=DEVNAME=$drive

**Comment by quinton-hoole** [comment]
OK, review done.  If you can strip all of the stuff I suggested out of udevadmChangeToNewDrives() and udevadmChangeToDrive() then there's no need to split up udevadmChangeToDrive().  Ideally I'd like unit and integration tests for this, but it's going to be tricky to stub out udevadm, and given how simple the code should become if you implement the suggested changes, I think that it's OK to merge without these tests.  The e2e tests should catch any bad breakages in future, albeit at more test execution time.

File: pkg/volume/gce_pd/gce_util.go (hunk 4 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Actually @quinton-hoole's intuition is right here. This could cause kubelet's `syncPods` loop to sleep for an additional 10 seconds, see [kubelet.go#L1328](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1328), since volume teardown is synchronous (unlike [volume creation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1166) which is asynchronous, see [pkg/kubelet/pod_workers.go#L151](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L151)). Any opposition to spawning of a new thread (go routine) to execute `vol.TearDown()` in `kubelet.go:cleanupOrphanedVolumes(...)`?

File: pkg/volume/gce_pd/gce_util.go (hunk 5 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Cleaned up

File: pkg/volume/gce_pd/gce_util.go (hunk 6 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Cleaned up

File: pkg/volume/gce_pd/gce_util.go (hunk 7 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 8 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: I don't think that udevadm errors should cause attach or detach calls to fail, hence log and continue. But, I don't feel strongly either way, so I changed it: udevadm failure will now cause `AttachAndMountDisk` and `DetachDisk` to fail.

Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Actually, I'll continue to insist that udevadm errors should NOT cause attach or detach calls to fail. I'll go ahead and have `udevadmChangeToDrive` and `udevadmChangeToNewDrives` return errors, but I'll have `waitForDiskToAttach` and `waitForDiskToDetach` log and swallow them.

File: pkg/volume/gce_pd/gce_util.go (hunk 9 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

**Comment by saad-ali** [comment]
@k8s-bot retest this please

**Comment by saad-ali** [comment]
Thanks for the feedback @quinton-hoole 
PTAL

File: pkg/kubelet/kubelet.go [hunk 10]
```diff
@@ -1310,10 +1310,12 @@ func (kl *Kubelet) cleanupOrphanedVolumes(pods []*api.Pod, runningPods []*kubeco
 			// TODO(yifan): Refactor this hacky string manipulation.
 			kl.volumeManager.DeleteVolumes(types.UID(parts[0]))
 			//TODO (jonesdl) This should not block other kubelet synchronization procedures
-			err := vol.TearDown()
-			if err != nil {
-				glog.Errorf("Could not tear down volume %q: %v", name, err)
-			}
+			go func(volumeName string) {
```
Comment (lavalamp) [inline pkg/kubelet/kubelet.go]: Remove TODO. @dchen1107 is it OK to start a random goroutine here?

Comment (lavalamp) [inline pkg/kubelet/kubelet.go]: E.g., what if it comes through next time and it's still working on tearing this down and it tears it down again.

File: pkg/volume/gce_pd/gce_util.go [hunk 11]
```diff
@@ -122,6 +112,135 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+// Wait for the disk device to be created
+func waitForDiskToAttach(pd *gcePersistentDisk, sdBeforeSet util.StringSet) (string, error) {
+	devicePaths := getDiskByIdPaths(pd)
+	for numTries := 0; numTries < 10; numTries++ {
+		if err := udevadmChangeToNewDrives(sdBeforeSet); err != nil {
+			// udevadm errors should not block disk attachment, log and continue
+			glog.Errorf("%v", err)
+		}
+
+		for _, path := range devicePaths {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: getDeviceByIdPaths() returns multiple symlinks to the same device file, but we only actually need/use one of them (/dev/disk/by-id/*).  Does it make sense to check for the existence of all of the other, unnecessary links here, or is that just inviting unnecessary failure?  I'm not sure.

**Comment by quinton-hoole** [comment]
@saad-ali Let me know when you're ready for another round of reviews on this one.  Assigning to you until then.

**Comment by saad-ali** [comment]
Will do. I'll hopefully send out an update to this PR this afternoon.

The workaround we discussed yesterday, having the sync loop do the detach retries, won't work: specifically creating a dummy dir to fake a mount while detach is unsuccessful is not sufficient to get the tear down logic to retry the detach and because the tear down code does reference counting to try and figure out when it is ok to detach a volume, that approach won't work.

So, I'm now testing a new work around, that asynchronously handles the detach retry logic, and introduces some more logic to prevent concurrency issues. It looks very promising in my tests so far.

File: pkg/volume/gce_pd/gce_util.go (hunk 11 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: More robust to watch all of them, and grab on to the first one that shows up. And then as long as one shows up we know that the device is successfully attached and can use that as the global mount point.

**Comment by saad-ali** [comment]
PTAL.

Big change is that the detach verification/retry loop is run asynchronously in a go routine and managed with a "channel manager" to ensure that it does not interfere with new attach/detach calls for the same PD.

I've been running PD tests against this code back to back for 7 hours, and so far they're rock solid--will report back in the morning.

I will squash changes once I have the green light before merge.

**Comment by quinton-hoole** [comment]
Awesome Saad. I'll take a look and in the morning. Kudos for your tenacity on this one. It's been a long haul.

**Comment by quinton-hoole** [comment]
Good Heavens! "385 additions and 35 deletions."  I was hoping for something way smaller.  Let me take a look and see what wee can do.

File: pkg/volume/gce_pd/gce_util.go [hunk 12]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
 		return err
 	}
+
+	// Verify disk detached, retry if needed.
+	go verifyDiskDetachedRetryIfNeeded(pd, gce)
+	return nil
+}
+
+// Verifys the disk device to be created has been succesffully attached, and retries if it fails.
+func verifyDiskAttachedRetryIfNeeded(pd *gcePersistentDisk, sdBeforeSet util.StringSet, gce cloudprovider.Interface) (string, error) {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: nit: ensureAttached() or verifyAttached() rather?  Disk and RetryIfNeeded are implied..

File: pkg/volume/gce_pd/gce_util.go [hunk 13]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+		if err := gce.(*gce_cloud.GCECloud).AttachDisk(pd.pdName, pd.readOnly); err != nil {
+			return "", err
+		}
+	}
+
+	return "", fmt.Errorf("Could not attach GCE PD %q. Timeout waiting for mount paths to be created.", pd.pdName)
+}
+
+// Veify the specified persistent disk device has been succesfully detached, and retries if it fails.
+func verifyDiskDetachedRetryIfNeeded(pd *gcePersistentDisk, gce cloudprovider.Interface) {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: nit: As above.  ensureDetached() or verifyDetached() rather?

File: pkg/volume/gce_pd/gce_util.go [hunk 14]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+
+	// Verify disk detached, retry if needed.
+	go verifyDiskDetachedRetryIfNeeded(pd, gce)
+	return nil
+}
+
+// Verifys the disk device to be created has been succesffully attached, and retries if it fails.
+func verifyDiskAttachedRetryIfNeeded(pd *gcePersistentDisk, sdBeforeSet util.StringSet, gce cloudprovider.Interface) (string, error) {
+	devicePaths := getDiskByIdPaths(pd)
+	for numRetries := 0; numRetries < 10; numRetries++ {
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Please make maxRetries, maxChecks explicit named constants rather than literals.

File: pkg/volume/gce_pd/gce_util.go [hunk 15]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+				} else if pathExists {
+					// A device path has succesfully been created for the PD
+					glog.V(5).Infof("Succesfully attached GCE PD %q.", pd.pdName)
+					return path, nil
+				}
+			}
+
+			// Sleep then check again
+			glog.V(5).Infof("Waiting for GCE PD %q to attach.", pd.pdName)
+			time.Sleep(time.Second)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Same with this one please.  An explicit named constant rather.

File: pkg/volume/gce_pd/gce_util.go [hunk 16]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+func verifyDiskDetachedRetryIfNeeded(pd *gcePersistentDisk, gce cloudprovider.Interface) {
+	ch := detachChanManager.CreateAndAddChan(pd.pdName, 0 /* bufferSize */)
+	defer detachChanManager.CloseAndRemoveChan(pd.pdName)
+	devicePaths := getDiskByIdPaths(pd)
+	for numRetries := 0; numRetries < 10; numRetries++ {
+		for numChecks := 0; numChecks < 10; numChecks++ {
+			select {
+			case <-ch:
+				glog.Warningf("Terminating GCE PD %q detach verification. Another attach/detach call was made for this PD.", pd.pdName)
+				return
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: You should ideally return whether you succeeded or failed to the caller of this function.  Even if they choose not to do anything with that info other than log it.

File: pkg/volume/gce_pd/gce_util.go [hunk 17]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+			default:
+				allPathsRemoved := true
+				for _, path := range devicePaths {
+					if err := udevadmChangeToDrive(path); err != nil {
+						// udevadm errors should not block disk detachment, log and continue
+						glog.Errorf("%v", err)
+					}
+					if exists, err := pathExists(path); err != nil {
+						glog.Errorf("Error check path: %v", err)
+						return
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Same comment as above.

File: pkg/volume/gce_pd/gce_util.go [hunk 18]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+				}
+				if allPathsRemoved {
+					// All paths to the PD have been succefully removed
+					glog.V(5).Infof("Succesfully detached GCE PD %q.", pd.pdName)
+					return
+				}
+
+				// Sleep then check again
+				glog.V(5).Infof("Waiting for GCE PD %q to detach.", pd.pdName)
+				time.Sleep(time.Second)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Same comment as previously.  Use a named constant please.

File: pkg/volume/gce_pd/gce_util.go [hunk 19]
```diff
@@ -122,6 +122,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+				glog.Errorf("%v", err)
+			}
+
+			for _, path := range devicePaths {
+				if pathExists, err := pathExists(path); err != nil {
+					return "", err
+				} else if pathExists {
+					// A device path has succesfully been created for the PD
+					glog.V(5).Infof("Succesfully attached GCE PD %q.", pd.pdName)
+					return path, nil
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: It is possible for you to return success here when only one, and the not used symlink has been created.  Your subsequent attempt to stat the other symlink will then fail.  You don't want that.  I think we discussed this previously.

**Comment by quinton-hoole** [comment]
Final set of changes (mostly nits) in my feedback.  Nearly there now.
We need to make a second pass over all of this and try to reduce the amount of code, as there really is a lot of it given how little we're actually doing here.  But lets leave that to a follow-up PR.

File: pkg/volume/gce_pd/gce_util.go (hunk 12 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done

File: pkg/volume/gce_pd/gce_util.go (hunk 13 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done

File: pkg/volume/gce_pd/gce_util.go (hunk 14 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done

File: pkg/volume/gce_pd/gce_util.go (hunk 15 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done

File: pkg/volume/gce_pd/gce_util.go (hunk 16 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: I agree with you, but in this case this method is executed asynchronously as a go routine. Returning errors here doesn't make any sense.

File: pkg/volume/gce_pd/gce_util.go (hunk 17 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Reiterating above, since this method is executed as a go routine, it doesn't make sense for it to return anything. From the [golang spec](http://golang.org/ref/spec#Go_statements): `When the function terminates, its goroutine also terminates. If the function has any return values, they are discarded when the function completes.`

File: pkg/volume/gce_pd/gce_util.go (hunk 18 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 19 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: The logic here is when a disk is attached there are multiple symlinks that are created--all of them link back to the same `/dev/sd*` drive. We watch all the possible symlinks and declare success when any one of them show up. This is not a problem, because we just need one handle to the PD and whichever symlink shows up first is sufficient for the PD to be considered attached and it can be used as the as the global mount point.

More robust to watch all of them, and grab on to the first one that shows up. And then as long as one shows up we know that the device is successfully attached and can use that as the global mount point.

**Comment by saad-ali** [comment]
Thanks for the feedback @quinton-hoole
Comments addressed. Squashed commits. PTAL

File: pkg/volume/gce_pd/gce_util.go (hunk 17 above)
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Here it's executed as a go routine, but having it return a value would make it more useful generally.  But OK, leave as it is if you prefer.

File: pkg/volume/gce_pd/gce_util.go (hunk 19 above)
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: The problem is that I seem to recall that you mount the /dev/disk/by-id symlink, and not the /dev/sd device?  Let me check...

Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: Yes, definitely mounting the symlink. More later...

Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: OK, I guess this will work.  It's just non-deterministic which symlink you'll mount (whichever one shows up first), which makes debugging a little tricky.  Lets leave it as it is.

File: pkg/volume/gce_pd/gce_util.go [hunk 20]
```diff
@@ -17,65 +17,63 @@ limitations under the License.
...
 // Attaches a disk specified by a volume.GCEPersistentDisk to the current kubelet.
 // Mounts the disk to it's global path.
-func (util *GCEDiskUtil) AttachAndMountDisk(pd *gcePersistentDisk, globalPDPath string) error {
+func (diskUtil *GCEDiskUtil) AttachAndMountDisk(pd *gcePersistentDisk, globalPDPath string) error {
+	glog.V(5).Infof("AttachAndMountDisk(pd, %q) where pd is %#v\r\n", globalPDPath, pd)
+	// Terminate any in progress verify detach go routines
+	detachChanManager.SignalChan(pd.pdName, true)
+	sdBefore, err := filepath.Glob(diskSDPattern)
+	if err != nil {
+		glog.Errorf("Error filepath.Glob(\"/dev/sd*\"): %v\r\n", err)
```
Comment (quinton-hoole) [inline pkg/volume/gce_pd/gce_util.go]: This should be diskSDPattern, not the literal.

**Comment by quinton-hoole** [comment]
minor nit, then LGTM.  @lavalamp, could you give a second TL LGTM?

**Comment by saad-ali** [comment]
Nits addressed. Thanks @quinton-hoole

**Comment by saad-ali** [comment]
@lavalamp can you take a look when you get a chance. I'd like to get this checked in.

File: pkg/util/chanmanager/chanmanager.go [hunk 21]
```diff
@@ -0,0 +1,83 @@
...
+
+// Channel Manager keeps track of multiple channels
+package chanmanager
+
+import (
+	"fmt"
+	"sync"
+)
+
+type ChanManager interface {
```
Comment (lavalamp) [inline pkg/util/chanmanager/chanmanager.go]: Please add a godoc comment. Also, can we name this for the service it provides instead of for the implementation it uses? Like, OperationManager or something?

File: pkg/util/chanmanager/chanmanager.go [hunk 22]
```diff
@@ -0,0 +1,83 @@
...
+	// Returns a read-only version of the newly created channel.
+	CreateAndAddChan(chanId string, bufferSize uint) <-chan interface{}
+
+	// Closes and removes the channel associated with chanID.
+	// Returns an error if no associated channel exists.
+	CloseAndRemoveChan(chanId string) error
+
+	// Attempts to send msg to the channel associated with chanID.
+	// Returns an error if no associated channel exists.
+	SignalChan(chanId string, msg interface{}) error
```
Comment (lavalamp) [inline pkg/util/chanmanager/chanmanager.go]: Perhaps Start, Close, and Send as the three method names?

also perhaps just 'id' instead of chanId (which should be chanID anyway)

Sorry for nitpicky naming comments, but I think it will make it easier for people to read this.

File: pkg/util/chanmanager/chanmanager.go [hunk 23]
```diff
@@ -0,0 +1,83 @@
...
+package chanmanager
+
+import (
+	"fmt"
+	"sync"
+)
+
+type ChanManager interface {
+	// Creates a new channel with specified buffer size. Adds it to manager with the specified chanID.
+	// Returns a read-only version of the newly created channel.
```
Comment (lavalamp) [inline pkg/util/chanmanager/chanmanager.go]: What if chanId already exists?

File: pkg/util/chanmanager/chanmanager.go [hunk 24]
```diff
@@ -0,0 +1,83 @@
...
+	cm.chanMap[chanId] = make(chan interface{}, bufferSize)
+	return cm.chanMap[chanId]
+}
+
+// Closes and removes the channel associated with chanID.
+// Returns an error if no associated channel exists.
+func (cm *chanManager) CloseAndRemoveChan(chanId string) error {
+	cm.Lock()
+	defer cm.Unlock()
+	if cm.chanMap[chanId] == nil {
```
Comment (lavalamp) [inline pkg/util/chanmanager/chanmanager.go]: minor style nit:

```
if _, exists := cm.chanMap[chanId]; !exists {
```

**Comment by thockin** [comment]
LGTM

File: pkg/volume/gce_pd/gce_util.go [hunk 25]
```diff
@@ -17,65 +17,63 @@ limitations under the License.
...
+	"github.com/GoogleCloudPlatform/kubernetes/pkg/util/chanmanager"
 	"github.com/GoogleCloudPlatform/kubernetes/pkg/util/exec"
 	"github.com/GoogleCloudPlatform/kubernetes/pkg/util/mount"
 	"github.com/golang/glog"
 )
 
+const (
+	diskByIdPath         = "/dev/disk/by-id/"
+	diskGooglePrefix     = "google-"
+	diskScsiGooglePrefix = "scsi-0Google_PersistentDisk_"
```
Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: do we have control of this prefix? If so, do we have to mix _ and -?

File: pkg/util/chanmanager/chanmanager.go (hunk 21 above)
Comment (lavalamp) [inline pkg/util/chanmanager/chanmanager.go]: (godoc should mention that it's threadsafe)

File: pkg/volume/gce_pd/gce_util.go (hunk 25 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: No, that's defined by GCE.

File: pkg/volume/gce_pd/gce_util.go [hunk 26]
```diff
@@ -122,6 +125,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+			return "", err
+		}
+	}
+
+	return "", fmt.Errorf("Could not attach GCE PD %q. Timeout waiting for mount paths to be created.", pd.pdName)
+}
+
+// Veify the specified persistent disk device has been succesfully detached, and retries if it fails.
+func verifyDetached(pd *gcePersistentDisk, gce cloudprovider.Interface) {
+	ch := detachChanManager.CreateAndAddChan(pd.pdName, 0 /* bufferSize */)
```
Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: Please add a comment to the effect:

bufferSize being 0 is very important, because it means that when senders send, they are blocked until we recieve; this avoids having to have a separate "did you exit yet" check.

File: pkg/volume/gce_pd/gce_util.go [hunk 27]
```diff
@@ -108,6 +106,11 @@ func (util *GCEDiskUtil) AttachAndMountDisk(pd *gcePersistentDisk, globalPDPath
 func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
 	// Unmount the global PD mount, which should be the only one.
 	globalPDPath := makeGlobalPDName(pd.plugin.host, pd.pdName)
+	glog.V(5).Infof("DetachDisk(pd) where pd is %#v and the globalPDPath is %q\r\n", pd, globalPDPath)
+
+	// Terminate any in progress verify detach go routines
```
Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: Please extend this comment-- "this will block until the goroutine is ready to exit because the channel is unbuffered"

File: pkg/util/chanmanager/chanmanager.go (hunk 21 above)
Comment (saad-ali) [inline pkg/util/chanmanager/chanmanager.go]: Done.

File: pkg/util/chanmanager/chanmanager.go (hunk 22 above)
Comment (saad-ali) [inline pkg/util/chanmanager/chanmanager.go]: Done.

File: pkg/volume/gce_pd/gce_util.go [hunk 28]
```diff
@@ -122,6 +125,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+		if err := gce.(*gce_cloud.GCECloud).AttachDisk(pd.pdName, pd.readOnly); err != nil {
+			return "", err
+		}
+	}
+
+	return "", fmt.Errorf("Could not attach GCE PD %q. Timeout waiting for mount paths to be created.", pd.pdName)
+}
+
+// Veify the specified persistent disk device has been succesfully detached, and retries if it fails.
+func verifyDetached(pd *gcePersistentDisk, gce cloudprovider.Interface) {
```
Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: if this is intended to run as a goroutine, please add a comment to that effect, and defer util.HandleCrash.

File: pkg/util/chanmanager/chanmanager.go (hunk 24 above)
Comment (saad-ali) [inline pkg/util/chanmanager/chanmanager.go]: Done.

File: pkg/volume/gce_pd/gce_util.go [hunk 29]
```diff
@@ -122,6 +125,167 @@ func (util *GCEDiskUtil) DetachDisk(pd *gcePersistentDisk) error {
...
+
+		// Try detaching disk again
+		glog.Warningf("Timed out waiting for GCE PD %q to detach. Retrying detach.", pd.pdName)
+		if err := gce.(*gce_cloud.GCECloud).DetachDisk(pd.pdName); err != nil {
+			glog.Errorf("Error on retry detach PD %q: %v", pd.pdName, err)
+			return
+		}
+	}
+
+	glog.Errorf("Could not detach GCE PD %q. One or more mount paths was not removed.", pd.pdName)
```
Comment (lavalamp) [inline pkg/volume/gce_pd/gce_util.go]: Is this a permanent error? If not, please include something like "will try again" to keep down the number of support bugs opened.

**Comment by lavalamp** [comment]
removing ok-to-merge since it looks like saad has unpushed changes ;)

File: pkg/volume/gce_pd/gce_util.go (hunk 27 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 28 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 26 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: Done.

File: pkg/util/chanmanager/chanmanager.go (hunk 23 above)
Comment (saad-ali) [inline pkg/util/chanmanager/chanmanager.go]: I was debating what to do in that case. I decided I didn't really care, since my code handled the cleanup. But to make this more generally useful, it would be good to error if an entry already exists. Done.

File: pkg/volume/gce_pd/gce_util.go (hunk 29 above)
Comment (saad-ali) [inline pkg/volume/gce_pd/gce_util.go]: This one is permanent, it means (10 second wait + detach) x 10 times all failed to detach the drive, so we're giving up (no further retries will happen).

**Comment by lavalamp** [comment]
LGTM

**Comment by saad-ali** [comment]
@k8s-bot retest this please

**Comment by saad-ali** [comment]
@k8s-bot retest this please

**Comment by saad-ali** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
Looks like github is flaky today.  This is the second error accessing github that I've seen in the past hour.  Retrying...

```
Unable to query GitHub for status of PullRequestjava.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/GoogleCloudPlatform/kubernetes/pulls/10169
	at sun.reflect.GeneratedConstructorAccessor107.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	at org.kohsuke.github.Requester.to(Requester.java:198)
	at org.kohsuke.github.GHPullRequest.populate(GHPullRequest.java:196)
	at org.kohsuke.github.GHPullRequest.getMergeable(GHPullRequest.java:169)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onStarted(GhprbBuilds.java:72)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:19)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onStarted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:215)
	at hudson.model.Run.execute(Run.java:1740)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/GoogleCloudPlatform/kubernetes/pulls/10169
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
Oh wait.  It's a 401 (unauthorized) error.  I wonder whether the problem is on our Jenkins side with credentials?  Checking...

**Comment by quinton-hoole** [comment]
@ixdy Tells me that these 401 errors have been happening intermittently for an hour, and are mostly innocuous.

**Comment by quinton-hoole** [comment]
The new e2e run seems to be succeeding...

**Comment by saad-ali** [comment]
Thanks for taking a look @quinton-hoole

**Comment by quinton-hoole** [comment]
e2e Passed.  LGTM, ok-to-merge

**Comment by quinton-hoole** [comment]
See #7972.  This bug still exists, by the looks of our soak test results.
