### PR TITLE
ContainerRestartRules feature gate should work with probes

### LINKED ISSUE #133216: [Failing test] [sig-node] Probing container should override timeoutGracePeriodSeconds when LivenessProbe field is set, [sig-node] Probing container should override timeoutGracePeriodSeconds when StartupProbe field is set
### Which jobs are failing?

- [kind-master-alpha-beta](https://testgrid.k8s.io/sig-release-master-informing#kind-master-alpha-beta)
- [kind-master-alpha](https://testgrid.k8s.io/sig-release-master-informing#kind-master-alpha)

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-node] Probing container should override timeoutGracePeriodSeconds when LivenessProbe field is set [NodeConformance]
- Kubernetes e2e suite.[It] [sig-node] Probing container should override timeoutGracePeriodSeconds when StartupProbe field is set [NodeConformance]

[Traige ci-kubernetes-e2e-kind-alpha-beta-features](https://storage.googleapis.com/k8s-triage/index.html?job=ci-kubernetes-e2e-kind-alpha-beta-features&test=Probing%20container%20should%20override%20timeoutGracePeriodSeconds%20when)
[Triage ci-kubernetes-e2e-kind-alpha-features](https://storage.googleapis.com/k8s-triage/index.html?job=ci-kubernetes-e2e-kind-alpha-features&test=Probing%20container%20should%20override%20timeoutGracePeriodSeconds%20when)

### Since when has it been failing?

recent failures:
[25/07/2025, 09:21:12](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1948629481044316160)
[25/07/2025, 05:21:09](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1948569081963614208)
[25/07/2025, 09:19:10](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-features/1948628977522315264)

Failures started 25-07-2025 05:21 EEST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kind-master-alpha-beta, https://testgrid.k8s.io/sig-release-master-informing#kind-master-alpha

### Reason for failure (if possible)

 	4m43s
```
{ failed [FAILED] pod container-probe-7690/busybox-e96533e3-f55b-4652-853c-55d89c4f087a - expected number of restarts: 1, found restarts: 0. Pod status: &PodStatus{Phase:Running,Conditions:[]PodCondition{PodCondition{Type:PodReadyToStartContainers,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-07-25 06:35:17 +0000 UTC,Reason:,Message:,ObservedGeneration:1,},PodCondition{Type:Initialized,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-07-25 06:35:16 +0000 UTC,Reason:,Message:,ObservedGeneration:1,},PodCondition{Type:Ready,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-07-25 06:35:17 +0000 UTC,Reason:,Message:,ObservedGeneration:1,},PodCondition{Type:ContainersReady,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-07-25 06:35:17 +0000 UTC,Reason:,Message:,ObservedGeneration:1,},PodCondition{Type:PodScheduled,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2025-07-25 06:35:16 +0000 UTC,Reason:,Message:,ObservedGeneration:1,},},Message:,Reason:,HostIP:172.18.0.2,PodIP:10.244.1.202,StartTime:2025-07-25 06:35:16 +0000 UTC,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:busybox,State:ContainerState{Waiting:nil,Running:&ContainerStateRunning{StartedAt:2025-07-25 06:35:16 +0000 UTC,},Terminated:nil,},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:true,RestartCount:0,Image:registry.k8s.io/e2e-test-images/busybox:1.37.0-1,ImageID:registry.k8s.io/e2e-test-images/busybox@sha256:0ffbe172f8d245c83f285c6992b452c53d085661e03ddfd3b484332026e6c8bb,ContainerID:containerd://4ea6621d0dcfa9d606a85cca309dc3f894d900aad5179f084d4aaecda3aec0ca,Started:*true,AllocatedResources:ResourceList{},Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMountStatus{VolumeMountStatus{Name:kube-api-access-6xsqb,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,ReadOnly:true,RecursiveReadOnly:*Disabled,},},User:&ContainerUser{Linux:&LinuxContainerUser{UID:0,GID:0,SupplementalGroups:[0 10],},},AllocatedResourcesStatus:[]ResourceStatus{},StopSignal:nil,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:10.244.1.202,},},EphemeralContainerStatuses:[]ContainerStatus{},Resize:,ResourceClaimStatuses:[]PodResourceClaimStatus{},HostIPs:[]HostIP{HostIP{IP:172.18.0.2,},},ObservedGeneration:1,}.
In [It] at: k8s.io/kubernetes/test/e2e/common/node/container_probe.go:1782 @ 07/25/25 06:39:58.695
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by yuanwang04**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes the feature gate ContainerRestartRules not working with readiness probes.

#### Which issue(s) this PR is related to:

Fixes #133216 
KEP: https://github.com/kubernetes/enhancements/issues/5307

#### Special notes for your reviewer:

Added the `computePodAction` unit tests under the feature gate ContainerRestartRules to ensure all existing behavior stays the same when the feature is enabled.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/5307
```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
This feature-related e2e test was skipped in the `pull-kubernetes-e2e-kind-alpha-beta-features` test job and was not executed.

You don't need to add the `feature.ContainerRestartRules` label to the test case, as it appears to be causing the test case to be skipped.

**Comment by aojea** [comment]
> You don't need to add the `feature.ContainerRestartRules` label to the test case, as it appears to be causing the test case to be skipped.

See https://groups.google.com/a/kubernetes.io/g/dev/c/uVga86nJDuI/m/gVujvOCnDwAJ for instructions
/cc @BenTheElder

**Comment by aojea** [comment]
@yuanwang04 , what @HirazawaUi says

```diff
diff --git a/test/e2e/node/pods.go b/test/e2e/node/pods.go
index 94171ea245f..dd8528bcf74 100644
--- a/test/e2e/node/pods.go
+++ b/test/e2e/node/pods.go
@@ -718,7 +718,7 @@ var _ = SIGDescribe("Pods Extended (pod generation)", feature.PodObservedGenerat
        })
 })
 
-var _ = SIGDescribe("Pod Extended (container restart policy)", feature.ContainerRestartRules, framework.WithFeatureGate(features.ContainerRestartRules), func() {
+var _ = SIGDescribe("Pod Extended (container restart policy)", framework.WithFeatureGate(features.ContainerRestartRules), func() {
        f := framework.NewDefaultFramework("pods")
        f.NamespacePodSecurityLevel = admissionapi.LevelBaseline
```

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 1]
```diff
@@ -1222,7 +1222,9 @@ func (m *kubeGenericRuntimeManager) computeInitContainerActions(ctx context.Cont
 
 				restartOnFailure := restartOnFailure
 				if utilfeature.DefaultFeatureGate.Enabled(features.ContainerRestartRules) {
-					restartOnFailure = kubecontainer.ShouldContainerBeRestarted(container, pod, podStatus)
+					if container.RestartPolicy != nil {
+						restartOnFailure = *container.RestartPolicy != v1.ContainerRestartPolicyNever
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:1229]: please add a comment into code suggesting that restart rules should not be checked here unless we will introduce the rules for probe restarts

**Comment by SergeyKanzhelev** [comment]
changes are ok, and I think it is safe to move forward instead of rolling back. Everything is under the feature gate still.

let's wait for tests execution

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (yuanwang04) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1229]: Done, added comments for the containerStatus=unknown and the probe failing cases.

File: test/e2e/node/pods.go [hunk 2]
```diff
@@ -718,7 +718,7 @@ var _ = SIGDescribe("Pods Extended (pod generation)", feature.PodObservedGenerat
 	})
 })
 
-var _ = SIGDescribe("Pod Extended (container restart policy)", feature.ContainerRestartRules, framework.WithFeatureGate(features.ContainerRestartRules), func() {
+var _ = SIGDescribe("Pod Extended (container restart policy)", framework.WithFeatureGate(features.ContainerRestartRules), func() {
```
Comment (BenTheElder) [inline test/e2e/node/pods.go:721]: LGTM

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133243/pull-kubernetes-e2e-kind-alpha-beta-features/1949883864046374912

Five passing test cases match `Pod Extended (container restart policy)`

**Comment by BenTheElder** [comment]
> Kubernetes e2e suite: [It] [sig-network] Proxy version v1 should proxy through a service and a pod [Conformance] 

https://github.com/kubernetes/kubernetes/issues/133257

/retest

**Comment by BenTheElder** [comment]
[these **PASSED**, testing again for more signal]
/test pull-kubernetes-e2e-kind-alpha-beta-features
/test pull-kubernetes-e2e-kind-beta-features

**Comment by BenTheElder** [comment]
/priority critical-urgent
/triage accepted
/approve
for test/

**Review by SergeyKanzhelev — APPROVED** [review]
/approve
/lgtm
/milestone v1.34

**Comment by SergeyKanzhelev** [comment]
> [these **PASSED**, testing again for more signal] /test pull-kubernetes-e2e-kind-alpha-beta-features /test pull-kubernetes-e2e-kind-beta-features

oops, I missed this. Sorry. Let's watch for tests in master

**Comment by BenTheElder** [comment]
SGTM, I expect them to pass again, and these were *failing* not flaking so we probably don't need another run anyhow.

But they're quick, cheap, and currently all non-blocking so ...
