### PR TITLE
Relax OpenAPI Verification to pass for both strict and non-strict alpha enforcement

### LINKED ISSUE #128616: openapi verify breaks sometimes when release tags are added, we should prevent this
### Which jobs are failing?

https://prow.k8s.io/?job=pull-kubernetes-verify

### Which tests are failing?

verify: openapi-spec is broken

### Since when has it been failing?

At least 6:55AM Pacific, November 6th. You can see the failed batch runs

### Testgrid link

_No response_

### Reason for failure (if possible)

Diff in the discovery api json data.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/pull/128615

### Relevant SIG(s)

/sig api-machinery release

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Implementation of https://docs.google.com/document/d/1zF_Qr6tqbbUYFu3WBpwqnE9lkcTqDGtHRaS-iPl2kto/edit?resourcekey=0-LRrOS8jDSvs9bDcUWhZE5A&tab=t.0#heading=h.yy7ullo1egs0.

Allow OpenAPI verification to pass both with and without strict alpha handling. `update-openapi-spec.sh` will use strict handling by default but users may choose to run the command with strict handling off via an env variable. 

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/128616

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig api-machinery release
/cc @BenTheElder @deads2k

### CODE REVIEW

File: hack/verify-openapi-spec.sh [hunk 1]
```diff
@@ -26,5 +26,7 @@ set -o pipefail
 KUBE_ROOT=$(dirname "${BASH_SOURCE[0]}")/..
 
 source "${KUBE_ROOT}/hack/lib/verify-generated.sh"
-
-kube::verify::generated "Generated files need to be updated" "Please run 'hack/update-openapi-spec.sh'" hack/update-openapi-spec.sh "$@"
+(
```
Comment (jpbetz) [inline hack/verify-openapi-spec.sh:29]: Can we get a comment summarizing the below logic?  Something like "either strict or non-strict validation must pass"?  Also a short explanation of why we allow non-strict here might be helpful to future readers.

File: hack/verify-openapi-spec.sh [hunk 2]
```diff
@@ -26,5 +26,7 @@ set -o pipefail
...
+  kube::verify::generated "Generated files failed strict alpha check and MAY need be updated" "Running verification again without strict alpha check" hack/update-openapi-spec.sh "$@"
+) || \
+STRICT_ALPHA_HANDLING=false kube::verify::generated "Generated files need to be updated" "Please run 'hack/update-openapi-spec.sh'" hack/update-openapi-spec.sh "$@"
```
Comment (liggitt) [inline hack/verify-openapi-spec.sh:32]: where will we run this strictly in a way that prevents release while the strict check is failing?

Comment (Jefftree) [reply hack/verify-openapi-spec.sh:32]: > where will we run this strictly in a way that prevents release while the strict check is failing?

I'd imagine a release-blocking job, will reach out to the release team about it. 

> we know contributors get their local tags confused in ways that mess up generation... will this tolerance allow accidentally regressing around the beta tag where a contributor without the beta tag locally will generate openapi containing just-stopped-serving beta types and readd them into the repo in a commit accidentally? can we prevent that?

That is a good point, but I think we avoid this because by default we will treat the tag as beta with `update-openapi-spec.sh` (strict=true).  Thus, we will only encounter issues if the git tag version and k8s version are mismatched on the user side. If that happens, openapi won't be the only thing that breaks...

File: hack/verify-openapi-spec.sh (hunk 1 above)
Comment (Jefftree) [reply hack/verify-openapi-spec.sh:34]: Added additional documentation at the beginning of the script.

File: api/discovery/aggregated_v2.json [hunk 3]
```diff
@@ -364,25 +364,6 @@
             }
           ],
           "version": "v1"
-        },
```
Comment (liggitt) [inline api/discovery/aggregated_v2.json:367]: I'm really surprised to see a diff in this file just because we're *relaxing* the openapi validation script

File: hack/update-openapi-spec.sh [hunk 4]
```diff
@@ -72,7 +77,7 @@ fi
 # Start kube-apiserver
 # omit enums from static openapi snapshots used to generate clients until #109177 is resolved
 kube::log::status "Starting kube-apiserver"
-kube-apiserver \
+KUBE_APISERVER_STRICT_REMOVED_API_HANDLING_IN_ALPHA=${STRICT_ALPHA_HANDLING} kube-apiserver \
```
Comment (liggitt) [inline hack/update-openapi-spec.sh:80]: won't being strict here drop all the types from the next minor once master goes to alpha.0, which happens at release branch cut time *before* .0 release of the previous minor?

File: hack/update-openapi-spec.sh [hunk 5]
```diff
@@ -21,6 +21,11 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+# STRICT_ALPHA_HANDLING ensures that the OpenAPI is updated with all APIs
+# that are intended to be removed at a particular release. This should be true by default.
+# If a new version tag was just created and you are seeing an unrelated diff when adding
+# a new API, run `STRICT_ALPHA_HANDLING=false ./hack/update-openapi-spec.sh`.
+STRICT_ALPHA_HANDLING=${STRICT_ALPHA_HANDLING:-true}
```
Comment (liggitt) [inline hack/update-openapi-spec.sh:28]: I don't think we should default this to true, or master generation will break during release branch phase

File: hack/verify-openapi-spec.sh (hunk 2 above)
Comment (Jefftree) [reply hack/verify-openapi-spec.sh:37]: I spent some time looking into this and I feel like we HAVE to default strict to true for generation to obtain a benefit.

My previous comment is actually wrong, `STRICT=false` can only happen with the alpha tag. [Link to code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/deleted_kinds.go#L130, the flag is a noop if the branch does not have an alpha tag. Thus, we don't need to create a separate CI to run this strictly since we will always transition to a non-alpha tag before release. This also means that defaulting strict to false per https://github.com/kubernetes/kubernetes/pull/130320#discussion_r1965846336 does not accomplish what we want as strict mode will automatically be enforced once we release the beta tag and CI will still break :/.

How often would an API get updated during code freeze between when `1.$next-alpha.0` is released and `1.x.rc`? My assumption is that we shouldn't really be changing APIs too much during that phase and we can ask any contributors that need to regenerate OpenAPI to run `STRICT=false make update` (or only the `update-openapi-spec.sh` script. Furthermore, changes to `master` are cherry picked to the `release-1.x` branch instead of synced right? Can we just not cherry pick the OpenAPI generation if we were to commit the change to master? `verify-openapi-spec.sh` should continue to pass on both branches as  the release branch would verify on `1.x` with `STRICT=true` and master branch would verify on `1.$next` with `STRICT=false`.

Comment (Jefftree) [reply hack/verify-openapi-spec.sh:37]: Without setting defaults, an alternative is to commit the `STRICT` setting in code. For instance, STRICT=1.33 (We cannot directly set true/false because these change over version boundaries) implies that if the current branch is on 1.33, generation should be done in strict mode. These can then be updated every release when we want to transition to strict instead of having the transition line fixed at the first release of the alpha tag. I dislike committing version information in code though because we've been trying so hard to remove this kind of information.

Comment (liggitt) [reply hack/verify-openapi-spec.sh:37]: Timeline:

* code freeze / release-1.n branch / 1.(n+1).alpha.0 in master - everything merged to master auto-propagates to release-1.n branch
  * `make update` generates with strict-after-alpha-1 removal behavior to produce 1.n content
  * verify enforces strict-after-alpha-1 or default removal (this ensures 1.n content)
* 1.n release
  * v1.n.0 tag will exist
* 1.(n+1).alpha.1
  * `make update` generates in strict-after-alpha-1 mode to produce 1.(n+1) content
  * verify enforces strict-after-alpha-1 or default removal (this works with default `make update` output, but does *allow* a regression to 1.n content, but this is unlikely)
* 1.(n+1).beta.1
  * `make update` generates in strict-after-alpha-1 mode to produce 1.(n+1) content
  * verify enforces strict-after-alpha-1 or default removal (this ensures 1.(n+1) content)

For the above timeline to work, we need to tweak the behavior of KUBE_APISERVER_STRICT_REMOVED_API_HANDLING_IN_ALPHA to mean "alpha AND not alpha.0".

This will let us keep the verify jobs identical between presubmit and periodic, and keep `make update` invocations identical at all phases of development.

File: hack/update-openapi-spec.sh (hunk 4 above)
Comment (Jefftree) [reply hack/update-openapi-spec.sh:80]: Resolved in https://github.com/kubernetes/kubernetes/pull/130320#discussion_r1980305938. Strict will only happen in alpha but not alpha.0

File: hack/update-openapi-spec.sh (hunk 5 above)
Comment (Jefftree) [reply hack/update-openapi-spec.sh:28]: Resolved in https://github.com/kubernetes/kubernetes/pull/130320#discussion_r1980305938. Strict will only happen in alpha but not alpha.0

[the remark this answers is not in the document]
Comment (Jefftree) [reply hack/update-openapi-spec.sh]: Fixed.

**Comment by Jefftree** [comment]
Sample PR with the changes to show that an outdated OpenAPI will fail verify: https://github.com/kubernetes/kubernetes/pull/130600
