### PR TITLE
Periodically update pod status from kubelet.

### LINKED ISSUE #4561: Kubelet to POST pod status to apiserver
Split off #156 as a smaller more specific work item.

In the kubelet, once every N sync loops, it should POST `/api/$VERSION/namespaces/$NS/pods/$NAME/status` for each pod. 

The kubelet would do this if enabled by a flag, and emit a warning if it failed to POST the update.

The kubelet would ideally handle a 429 by retrying after the `Retry-after` header.

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Every 3 sync loops kubelet updates pod status using new pod/status handler. This PR fixes #4561 (kubelet to POST pod status to apiserver).

### CODE REVIEW

**Comment by brendandburns** [comment]
Needs gofmt...

**Comment by fgrzadkowski** [comment]
Formatting fixed. Sorry about that. Added hooks as described [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#hooks) to prevent it in the future.

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1554,6 +1554,10 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
 			unsyncedPod = true
 		case <-time.After(kl.resyncInterval):
 			glog.V(4).Infof("Periodic sync")
+		case <-time.After(3 * kl.resyncInterval):
```
Comment (wojtek-t) [inline pkg/kubelet/kubelet.go]: I think this will never happen - the above condition (waiting for kl.resyncInterval above) will always happen before it.

Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: It will :) select chooses a random channel that is ready, i.e. has an input.

Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: See https://golang.org/ref/spec#Select_statements

Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: I've just tested it and you're right. What happened is that I was testing it previously with 0.1 instead of 3, so my branch was always running, and the other was not. That's why I haven't noticed it. Thanks for spotting this!

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1554,6 +1555,10 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
 			unsyncedPod = true
 		case <-time.After(kl.resyncInterval):
 			glog.V(4).Infof("Periodic sync")
+		case <-syncStatusTicker:
+			glog.V(4).Infof("Periodic status sync")
+			kl.syncStatus()
+			continue
```
Comment (wojtek-t) [inline pkg/kubelet/kubelet.go]: This looks better.
However, I'm not sure if that's the best we can do. Basically assume that no updates are coming to "updates" channel. Then (before your change) we expected that SyncPods() will be called every resyncInterval. This will no longer be true with your changes because every third call will be replaced with syncStatus() (or if it will be an expensive synchronous method, even more than every third call).
So in my opinion we should remove "continue" here.

Adding @vmarmol for his opinion on it.

Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: I see your point, but I don't think that removing continue is the way to go. This assumes how often syncStatusTicker ticks. If we change it to 0.1 * kl.resyncInterval, it would be syncing pods too often, right?

How about we just have two tickers - one for syncing pods and one for syncing status. We will effectively do a bit more pods syncing, but I guess it should be acceptable and it will also make the code more readable (currently it's kind of hard to understand for me when something is triggered). WDYT?

Comment (wojtek-t) [inline pkg/kubelet/kubelet.go]: I'm not sure that it's the best option because with tickers we can accumulate the "signals" to SyncPods() method over time (if SyncPods() will take a lot of time), which I don't think it's good.
But let's wait for others opinions on it.

Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: My vote is to just have a separate Go-routine that syncsStatus() on its own interval. The code should looks simpler (minus having more Go-routines to reason about, but they're well scoped). I don't think we need to place those updates in this sync loop alone.

Also note that the default sync interval is 10s, which would make the syncStatus happen every 30s, is that often enough?

Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: One thing to note is that if we separate the loops we'll need to lock around the pods. I think we are moving that route anyways, but just a heads-up.

File: pkg/api/validation/validation.go [hunk 3]
```diff
@@ -687,11 +687,10 @@ func ValidatePodStatusUpdate(newPod, oldPod *api.Pod) errs.ValidationErrorList {
 
 	allErrs = append(allErrs, ValidateObjectMetaUpdate(&oldPod.ObjectMeta, &newPod.ObjectMeta).Prefix("metadata")...)
 
-	// TODO: allow change when bindings are properly decoupled from pods
```
Comment (vmarmol) [inline pkg/api/validation/validation.go]: Why this change? I'm not particularly familiar with this code, but I figured you had a reason.

**Comment by vmarmol** [comment]
We also need to rebase btw

**Comment by dchen1107** [comment]
We already introduced "thread-per-pod" logic to kubelet, why not asking that thread to generate podstatus periodically and cache somewhere, and SyncLoop just simply aggregates the status, and propagates the result back?

**Comment by wojtek-t** [comment]
I agree with Dawn that caching statuses as part of SyncLoop is a good idea (we should integrate it into pod_workers.go). However, the question is how expensive computing the status is - if it can potentially be expensive we should consider having a separate thread for it.
Also, if you decide to moving it to "thread-per-pod" goroutine, please also take a look into #5239, which may affect your work.

**Comment by vmarmol** [comment]
I agree with @dchen1107  that a better way to achieve this is through the worker per pod. We should change the podWorkers to handle more arbitrary work items that we can schedule on that thread.

Only downside (as @wojtek-t  noted) is that the worker may fall behind and post it later. That's probably fine though, since the pod worker would be the first to reflect the pod's state and if it is blocked is because a config change is occurring.

File: pkg/api/validation/validation.go (hunk 3 above)
Comment (fgrzadkowski) [inline pkg/api/validation/validation.go]: Otherwise kubelet would have to fill this, which doesn't make much sense since the host cannot change.

CC-ing @smarterclayton who wrote this function.

Comment (bgrant0607) [inline pkg/api/validation/validation.go]: Note that this code was just updated.

I don't understand the change, either.

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -1579,6 +1584,30 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
...
+
+	for _, pod := range kl.pods {
+		status, err := kl.GetPodStatus(GetPodFullName(&pod), pod.UID)
+		if err != nil {
+			glog.Warningf("Error getting pod %s status: %v, retry later", pod.Name, err)
+			continue
+		}
+		source := pod.Annotations[ConfigSourceAnnotationKey]
+		if source != ApiserverSource {
+			glog.V(3).Infof("Pod status for %s is not updated due to its source %s", pod.Name, source)
```
Comment (bgrant0607) [inline pkg/kubelet/kubelet.go]: FYI: @yujuhong

Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: Ack.

File: pkg/api/validation/validation.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/api/validation/validation.go]: When would this happen?  Kubelet would have to post a host that is empty to a pod that has a host?

Comment (fgrzadkowski) [inline pkg/api/validation/validation.go]: By default pod status does not contain host(IP). It used to be filled in pod_cache. Also, if we don't allow to change this, why not just overwrite it to the last known value instead of returning error?

Comment (bgrant0607) [inline pkg/api/validation/validation.go]: For consistency, and to catch bugs.

For a few select readonly fields we don't expect the client to know, such as creationTimestamp, we do allow them to be empty. However, in general, PUT doesn't merge. It overwrites. Host is a mutable field, it just can't be changed once written. An attempt to do so, including leaving it empty, is a bug.

We could potentially remove this field from Status in v1beta3, since binding is now writing Spec, but kubelet needs to know its identity in order to update NodeStatus, so it doesn't seem like it should be hard for it to populate this field.

Furthermore, kubelet has to watch and cache the pods in order to know what to run, anyway, so it could do what I proposed for NodeStatus, which is to merge the status updates with the status received from apiserver.

Comment (bgrant0607) [inline pkg/api/validation/validation.go]: I prefer to remove Status.Host.

https://github.com/GoogleCloudPlatform/kubernetes/pull/5256#issuecomment-78413041

**Comment by vmarmol** [comment]
Ping @fgrzadkowski, anything I can help with? I think we talked about moving this to periodically scheduled on the podWorker. WDYT of that approach?

**Comment by fgrzadkowski** [comment]
Sorry for the delay. I've been in Spotify for the last 3 days and didn't have time to work on this.

I think that having this logic in podWorker makes sense.

**Comment by vmarmol** [comment]
@fgrzadkowski no worries, I hadn't heard back so figured I'd ping :)

**Comment by fgrzadkowski** [comment]
Ok. I've just pushed new version:
1. hostname is set as part of the Status generated by kubelet
2. status is created after syncPod (run using podWorker) and cached
3. separate go routine to send status to apiserver.

PTAL

**Comment by fgrzadkowski** [comment]
I have also tested this with disabled pod_cache and it works.

File: pkg/kubelet/kubelet.go [hunk 5]
```diff
@@ -1299,6 +1301,14 @@ func (kl *Kubelet) syncPod(pod *api.BoundPod, containersInPod dockertools.Docker
 		}
 	}
 
+	// Regenerate status and store it in the cache.
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: I think we may want to do this in a defer, if we error out on any part of the function we won't generate the status.

File: pkg/kubelet/kubelet.go [hunk 6]
```diff
@@ -1615,6 +1625,30 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
 	}
 }
 
+// syncStatus syncs pods statuses with the apiserver.
+func (kl *Kubelet) syncStatus() {
+	glog.V(3).Infof("Syncing pods status")
+
+	for _, pod := range kl.pods {
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: We should protect the access to kl.pods with pocLock. We should probably build a list of statuses and then send them so we don't block on network.

This also made me realize there is one case where we're not locking kl.pods, will send a PR for that. It should not affect this.

File: pkg/kubelet/kubelet.go [hunk 7]
```diff
@@ -1615,6 +1625,30 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
...
+		status, err := kl.GetPodStatus(GetPodFullName(&pod), pod.UID)
+		if err != nil {
+			glog.Warningf("Error getting pod %s status: %v, retry later", pod.Name, err)
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: nit: I tend to always use %q for strings which prints out the string in quotes. It makes it clearer what's in the string and catches errors like empty string and whitespace characters. Feel free to heed or ignore :)

**Comment by vmarmol** [comment]
I'd like us to also push the status in the podWorker, but I'm fine with a separate thread for now so I won't block on that.

**Comment by vmarmol** [comment]
Will need a rebase btw, just merges some changes to syncPod()

File: pkg/kubelet/kubelet.go (hunk 5 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Done.

File: pkg/kubelet/kubelet.go (hunk 6 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Done.

File: pkg/kubelet/kubelet.go (hunk 7 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Thanks, done.

**Comment by fgrzadkowski** [comment]
All comments addressed and rebased to head.

Regarding pushing the status in podWorker, I'm not sure this is a good idea, because AFAIU we want to push status updates in bulks.

File: pkg/kubelet/kubelet.go [hunk 8]
```diff
@@ -1715,6 +1727,38 @@ func (kl *Kubelet) syncLoop(updates <-chan PodUpdate, handler SyncHandler) {
 	}
 }
 
+// syncStatus syncs pods statuses with the apiserver.
+func (kl *Kubelet) syncStatus() {
+	glog.V(3).Infof("Syncing pods status")
+
+	statuses := make(map[string]api.PodStatus)
+	kl.podLock.Lock()
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: We usually always use defer to reduce the probability of bugs. For cases like this we use this pattern:

```Go

statuses := ...
func() {
  lock.Lock()
  defer lock.Unlock()
}

for podFullName, ... {
}
```

**Comment by dchen1107** [comment]
>>Regarding pushing the status in podWorker, I'm not sure this is a good idea, because AFAIU we want to push status updates in bulks.

+1. podWorker should populate related Status periodically, not push directly. Eventually we want to introduce a bulk post on Status including both Pod and Node.

File: pkg/kubelet/kubelet.go (hunk 8 above)
Comment (fgrzadkowski) [inline pkg/kubelet/kubelet.go]: Done.

**Comment by vmarmol** [comment]
I'm sorry, you'll need to rebase again :( this is done though.

**Comment by fgrzadkowski** [comment]
Rebased :) 

We have so much churn that it's quite some work to keep it in sync...

**Comment by vmarmol** [comment]
Thanks for dealing with the churn @fgrzadkowski :) merging.

**Comment by wojtek-t** [comment]
This PR broke e2e tests - Filip is looking into it now.
