### PR TITLE
Fix:[Flake] [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet hould correctly account for terminated pods after restart

### LINKED ISSUE #108775: [Flake] [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should correctly account for terminated pods after restart
### Failure cluster [03a28923a9772498aaf8](https://go.k8s.io/triage#03a28923a9772498aaf8)

Test: [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should correctly account for terminated pods after restart

##### Error text:
```
test/e2e_node/restart_test.go:142
Mar  4 09:00:41.495: Failed to run sufficient restartAlways pods, got 3 but expected 4
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

I've also seen

```
{ Failure test/e2e_node/restart_test.go:142
Mar 16 21:28:06.720: Failed to run sufficient restartNever pods, got 0 but expected 1
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113}
```

on https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1504190296534028288

#### Recent failures:
[3/16/2022, 1:18:16 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1504190296534028288)
[3/12/2022, 12:10:12 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502557516268048384)
[3/6/2022, 7:55:56 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1500500414972301312)
[3/4/2022, 12:45:54 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1499667417851236352)

/kind flake
/sig node

Looks like occasionally we have a second 50m CPU pod hanging around on the node, blocking enough pods getting scheduled for the test:

```
I0316 21:25:06.552690  172062 config.go:384] "Receiving a new pod" pod="restart-test-721/test-179d535e-98f2-4a77-9a56-27fd9c16901e"
I0316 21:25:06.552726  172062 kubelet.go:2039] "SyncLoop ADD" source="api" pods=[restart-test-721/test-179d535e-98f2-4a77-9a56-27fd9c16901e]
I0316 21:25:06.552746  172062 topology_manager.go:200] "Topology Admit Handler"
I0316 21:25:06.552760  172062 manager.go:914] "Looking for needed resources" needed=1 resourceName="cpu"
I0316 21:25:06.552829  172062 predicate.go:130] "Predicate failed on Pod" pod="restart-test-721/test-179d535e-98f2-4a77-9a56-27fd9c16901e" err="Node didn't have enough resource: cpu, requested: 950, used: 100, capacity: 1000"
```

I'm a bit puzzled because no pods are listed as currently running when the node dumps debug info. Could be a bug?

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/issues/108775#issuecomment-1075999859
https://github.com/kubernetes/kubernetes/issues/108775#issuecomment-1076045749

We check the pid of container after the pod becomes running, so we could prevent getting other pid with same name, which would make the test to end prematurely
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/108775

#### Special notes for your reviewer:
/cc @ehashman @SergeyKanzhelev 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/container_manager_test.go [hunk 1]
```diff
@@ -192,6 +195,9 @@ var _ = SIGDescribe("Container Manager Misc [Serial]", func() {
 						},
 					},
 				})
+				if err := e2epod.WaitForPodCondition(f.ClientSet, f.Namespace.Name, podName, "Ready", 120*time.Second, testutils.PodRunningReady); err != nil {
```
Comment (ehashman) [inline test/e2e_node/container_manager_test.go:198]: I don't think this is it. In the failure output, the pod is getting rejected because there aren't enough resources (CPU) left on the node, not due to a race condition on checking Ready status.

For some reason we have system pods requesting too much CPU which occasionally interferes with this test.

**Review by ehashman — COMMENTED** [review]
/hold

File: test/e2e_node/container_manager_test.go (hunk 1 above)
Comment (249043822) [reply test/e2e_node/container_manager_test.go:198]: Yea, the restart-test-pod was rejected because it requested 950m cpu, but the node has 1000m cpu, and other 100m was occupied by the guaranteed-pod of the container-manager-test-case(see the code https://github.com/kubernetes/kubernetes/blob/324ba1324b4b10ae7ef4d9d0a0654da7b118b920/test/e2e_node/container_manager_test.go#L187) which I analysed in the issue,  the kubelet log can prove this inference:
`I0316 21:25:06.552829  172062 predicate.go:130] "Predicate failed on Pod" pod="restart-test-721/test-179d535e-98f2-4a77-9a56-27fd9c16901e" err="Node didn't have enough resource: cpu, requested: 950, used: 100, capacity: 1000"`

Comment (249043822) [reply test/e2e_node/container_manager_test.go:198]: Adding the pod ready status checking is because the code https://github.com/kubernetes/kubernetes/blob/324ba1324b4b10ae7ef4d9d0a0654da7b118b920/test/e2e_node/container_manager_test.go#L200 which checks the pid of nginx can pass even while the pod has not been created. see 


> ```
> I0316 21:25:08.688468  172062 kuberuntime_manager.go:889] "Creating container in pod" containerType="container" container="&Container{Name:guaranteede9d81584-c234-43a2-8e2f-12b067d05eec,Image:k8s.gcr.io/e2e-test-images/nginx:1.14-2,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{52428800 0} {<nil>} 50Mi BinarySI},},Requests:ResourceList{cpu: {{100 -3} {<nil>} 100m DecimalSI},memory: {{52428800 0} {<nil>} 50Mi BinarySI},},},VolumeMounts:[]VolumeMount{},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Never,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}" pod="kubelet-container-manager-8210/guaranteede9d81584-c234-43a2-8e2f-12b067d05eec"
> I0316 21:25:08.696208  172062 kubelet_pods.go:161] "Creating hosts mount for container" pod="kubelet-container-manager-8210/guaranteede9d81584-c234-43a2-8e2f-12b067d05eec" containerName="guaranteede9d81584-c234-43a2-8e2f-12b067d05eec" podIPs=[10.85.0.111 1100:200::6f] path=true
> ```
> 
> Since at 0316 21:25:08, the container of pod guaranteede9d81584 has just been creating, but the test case [sig-node] Container Manager Misc [Serial] has already finished at 0316 21:25:06, so the test case check condition may be not strict
> 
> ```
> W0316 21:43:30.267] [sig-node] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup 
> W0316 21:43:30.267]   guaranteed container's oom-score-adj should be -998
> W0316 21:43:30.267]   test/e2e_node/container_manager_test.go:173
> W0316 21:43:30.267] [BeforeEach] [sig-node] Container Manager Misc [Serial]
> W0316 21:43:30.267]   test/e2e/framework/framework.go:185
> W0316 21:43:30.267] STEP: Creating a kubernetes client
> W0316 21:43:30.268] STEP: Building a namespace api object, basename kubelet-container-manager
> W0316 21:43:30.268] Mar 16 21:25:06.470: INFO: Skipping waiting for service account
> W0316 21:43:30.268] [It] guaranteed container's oom-score-adj should be -998
> W0316 21:43:30.268]   test/e2e_node/container_manager_test.go:173
> W0316 21:43:30.268] [AfterEach] [sig-node] Container Manager Misc [Serial]
> W0316 21:43:30.268]   test/e2e/framework/framework.go:186
> W0316 21:43:30.268] Mar 16 21:25:06.507: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
> W0316 21:43:30.268] STEP: Destroying namespace "kubelet-container-manager-8210" for this suite.
> W0316 21:43:30.268] •
> W0316 21:43:30.269] ------------------------------
> W0316 21:43:30.269] [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet 
> ```

**Comment by haircommander** [comment]
based on the discussion, it's not clear to me that this actually does fix the flake problem. I get the logic of how the test cases may not be waiting for the right condition to deem the process as existing, but the connection to the flaky test is confusing: why would the flakes always report a lower number of pods than expected?

regardless, this change does look correct generally, even if it doesn't fix the flake. Therefore, I think we can
/lgtm

and reopen the bug if the flake appears again (or reopen immediately and wait a bit to see if it pops up again)

**Comment by 249043822** [comment]
/hold cancel
/assign @endocrimes @SergeyKanzhelev 
thanks for @haircommander , althougth the code which I changed looks not directly relate to this flake case and maybe  confusing to others,  but it actually affects the failure of this test indirectly

File: test/e2e_node/container_manager_test.go [hunk 2]
```diff
@@ -192,6 +195,9 @@ var _ = SIGDescribe("Container Manager Misc [Serial]", func() {
...
+					framework.Logf("Pod %v took too long to enter running/ready: %v", podName, err)
```
Comment (SergeyKanzhelev) [inline test/e2e_node/container_manager_test.go:199]: I'd suggest to fail the test in this case. Otherwise we are checking the oom score adj for the wrong process potentially

**Review by SergeyKanzhelev — COMMENTED** [review]
sorry took long time to get to this. lgtm overall, good catch that we can check the wrong process. I'd suggest to fail the test if we failed to schedule a pod.

File: test/e2e_node/container_manager_test.go (hunk 2 above)
Comment (249043822) [reply test/e2e_node/container_manager_test.go]: Done

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by 249043822** [comment]
this pr hangs for a long time, so the code is dirty, adding `e2epod.WaitForPodCondition(ctx` for this push

**Comment by bart0sh** [comment]
/lgtm
@SergeyKanzhelev would you mind approving again?

**Comment by bart0sh** [comment]
@249043822 it looks like this PR causes some tests to fail, e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-serial/1611051478682701824

30sec timeout could be too short. Did you happen to run node-e2e suite when you worked on this PR?

**Comment by bobbypage** [comment]
Created issue to track this - [115045](https://github.com/kubernetes/kubernetes/issues/115045)
