### PR TITLE
Fully close sockets in kube-proxy

### LINKED ISSUE #18354: Kube-proxy socket descriptor leak
While investigating a socket leak in our kubernetes-deployed application, I have found out that the kube-proxy also seems to have a serious leak of its own.

In two of my three nodes, out of the ~44K connections of the kube-proxy ....

```
ubuntu@ip-172-20-0-60:~$ sudo netstat -np | grep kube-proxy > netstat.txt
ubuntu@ip-172-20-0-60:~$ wc -l netstat.txt
44445 netstat.txt
```

... about 65% are legit established connections caused by the aforementioned leak ...
```
ubuntu@ip-172-20-0-60:~$ grep ESTABLISHED netstat.txt | wc -l
28922
```

... but ~14K are in FIN_WAIT2 state ...
```
ubuntu@ip-172-20-0-60:~$ grep FIN_WAIT2 netstat.txt | wc -l
14544
```

... and ~1K are in CLOSE_WAIT.
```
ubuntu@ip-172-20-0-60:~$ grep CLOSE_WAIT netstat.txt | wc -l
977
```

Here's some debug info:

* Gist with service descriptions, node descriptions and iptables rules from node `ip-172-20-0-60` (we are running kubernetes 1.1 in AWS): https://gist.github.com/2opremio/24adfa5a10b45b1b77da
* Goroutine dump of kube-proxy at node `ip-172-20-0-60`, obtained with `curl localhost:10249/debug/pprof/goroutine?debug=2`: [kube-proxy-go-routines.log.gz](https://www.dropbox.com/s/2bfz30z4q7pt5dl/kube-proxy-go-routines.log.gz?dl=1)
* `sudo netstat -np | grep kube-proxy` at node `ip-172-20-0-60`: [netstat.txt.gz](https://www.dropbox.com/s/1q4ncrf1xzxuj5b/netstat.txt.gz?dl=1)
* `/proc/sys/net/ipv4/tcp_fin_timeout` has a value of 60 in all my nodes.

After deploying the fix for application-level leak and waiting 10 minutes, according to `sudo netstat -np | grep kube-proxy` the number of ESTABLISHED connections is ~100 in all nodes as expected but, in the two affected nodes:

* The CLOSE_WAIT connections only halve from 1K to 500
* The FIN_WAIT2 ones also halve from 14K to 7K

I obtained new goroutine and netstat dumps, in case it helps:

* [kube-proxy-go-routines-after.log.gz](https://www.dropbox.com/s/xxcz0eb5p4l6xqt/kube-proxy-go-routines-after.log.gz?dl=1)
* [netstat-after.txt.gz](https://www.dropbox.com/s/o6igs1avb01apr1/netstat-after.txt.gz?dl=1)

Also, it may be valuable to know that the application-level leaks were caused by a websocket proxy (part of the `app-mapper` pods) which failed to clean up connections when the client-side closed the underlying TCP socket. Both the app-mapper and the destination are accessed through kubernetes services, which means that the kube-proxy is caught up in-between:

```
 frontend -> (kube-proxy local to frontend) -> app-mapper -> (kube proxy local to app-mapper) -> destination
```

The two kube-proxy instances affected live in the same nodes where the two app-mapper pods live: `ip-172-20-0-60` and `ip-172-20-0-62`

### PR DESCRIPTION
**Pull request by thockin**
We were trying to be clever and respect TCP's notion of half-open sockets, but
it causes leaks when we can't unblock io.Copy().  This fixes those leaks and
seems to follow most expectations.  I think we were just be too clever.

Fixes #18354 and hopefully #17641 

@2opremio

### CODE REVIEW

File: pkg/proxy/userspace/proxysocket.go [hunk 1]
```diff
@@ -162,11 +160,13 @@ func copyBytes(direction string, dest, src *net.TCPConn, wg *sync.WaitGroup) {
...
-		glog.Errorf("I/O error: %v", err)
+		if !isClosedError(err) {
+			glog.Errorf("I/O error: %v", err)
+		}
 	}
 	glog.V(4).Infof("Copied %d bytes %s: %s -> %s", n, direction, src.RemoteAddr(), dest.RemoteAddr())
-	dest.CloseWrite()
-	src.CloseRead()
+	dest.Close()
+	src.Close()
```
Comment (2opremio) [inline pkg/proxy/userspace/proxysocket.go]: If you only close the destination you will end up closing both connections but without double closes and in turn without needing the `isClosedError()` check.

**Comment by 2opremio** [comment]
A regression unit test for `ProxyLoop()` with a leaking destination like https://github.com/kubernetes/kubernetes/issues/18354#issuecomment-163460510 would be good.
