### PR TITLE
kms: fix go routine leak in gRPC connection

### LINKED ISSUE #111674: reduce goroutine leakage in `test/integration/controlplane/transformation`
Following up on https://github.com/kubernetes/kubernetes/pull/111126#discussion_r935087747 to shutdown the gRPC goroutines and reduce the number of leaked goroutines.

/sig auth

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mok@microsoft.com>

/kind bug
/sig auth
/milestone v1.26
/priority important-soon
/triage accepted
/assign @aramase @wojtek-t 
Fixes #111674

```release-note
NONE
```

### CODE REVIEW

File: test/integration/framework/etcd.go [hunk 1]
```diff
@@ -198,7 +198,7 @@ func EtcdMain(tests func() int) {
 		// like k8s.io/klog/v2.(*loggingT).flushDaemon()
 		// TODO(#108483): Reduce this number once we address the
 		//   couple remaining issues.
-		if dg := runtime.NumGoroutine() - before; dg <= 15 {
+		if dg := runtime.NumGoroutine() - before; dg <= 10 {
```
Comment (aramase) [inline test/integration/framework/etcd.go:201]: `dg <= 10` was set because `integration/controlplane/transformation` had 9 leaked goroutines before. With this PR that number should have come down even more because this closes the connection for v1 and v2. Could we evaluate what the current number of goroutines are leaked including this change and reduce the allowed number to a lower strict value?

Comment (enj) [reply test/integration/framework/etcd.go]: The worst offender is:

```
=== FAIL: test/integration/clustercidr  (0.00s)
I0824 17:41:24.044151  116775 etcd.go:76] etcd already running at http://127.0.0.1:2379
PASS
F0824 17:41:53.931022  116775 etcd.go:213] unexpected number of goroutines: before: 2 after 11
FAIL	k8s.io/kubernetes/test/integration/clustercidr	29.958s
```

Comment (enj) [reply test/integration/framework/etcd.go]: I have set the limit to `9` to allow `test/integration/clustercidr` to pass while being as strict as possible.

**Review by aramase — COMMENTED** [review]
/lgtm

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by wojtek-t** [comment]
Will take a look later this week.

File: staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go [hunk 2]
```diff
@@ -536,3 +541,12 @@ func (u unionTransformers) TransformFromStorage(ctx context.Context, data []byte
 func (u unionTransformers) TransformToStorage(ctx context.Context, data []byte, dataCtx value.Context) (out []byte, err error) {
 	return u[0].TransformToStorage(ctx, data, dataCtx)
 }
+
+func stopChToContext(stopCh <-chan struct{}) context.Context {
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig/config.go:545]: Instead of creating your own method, let's use already existing one that does what you want:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L299

File: staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go [hunk 3]
```diff
@@ -84,6 +84,12 @@ func NewGRPCService(endpoint string, callTimeout time.Duration) (Service, error)
 	}
 
 	s.kmsClient = kmsapi.NewKeyManagementServiceClient(s.connection)
+
+	go func() {
+		<-ctx.Done()
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/grpc_service.go:89]: please add defer HandleCrash() - we generally try to do that in all goroutines (in production code) for safety

File: staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service.go [hunk 4]
```diff
@@ -75,6 +75,12 @@ func NewGRPCService(endpoint string, callTimeout time.Duration) (Service, error)
 	}
 
 	s.kmsClient = kmsapi.NewKeyManagementServiceClient(s.connection)
+
+	go func() {
+		<-ctx.Done()
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service.go:80]: please add defer HandleCrash() - we generally try to do that in all goroutines (in production code) for safety

File: cmd/kube-apiserver/app/server.go [hunk 5]
```diff
@@ -412,7 +412,7 @@ func buildGenericConfig(
 		lastErr = err
 		return
 	}
-	storageFactory, lastErr = completedStorageFactoryConfig.New()
+	storageFactory, lastErr = completedStorageFactoryConfig.New(genericConfig.DrainedNotify())
```
Comment (wojtek-t) [inline cmd/kube-apiserver/app/server.go:415]: My small concern with this is that draining currently doesn't drain long-running requests, in particular watches.

However, watches can also require KMS or decrypting stuff they receive from etcd.

It's technically not end of the world, because it will just result in sending an error event:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L331
and watchers should recover from it.
But in some cases, it may cause unnecessary relists:
https://github.com/kubernetes/kubernetes/blob/09e8339ae4e575ec40e8ed0fc2829fcb678c0f19/staging/src/k8s.io/client-go/tools/cache/reflector.go#L473
[FWIW - I wanted to address it for some time, but never got to it...]

I'm wondering if we shouldn't use some other signal, like HTTPServerStoppedListening in the meantime.

**Review by wojtek-t — COMMENTED** [review]
Just a couple small comments - other than that is LGTM

File: cmd/kube-apiserver/app/server.go (hunk 5 above)
Comment (aojea) [reply cmd/kube-apiserver/app/server.go:415]: I'm not familiar with this, but it seems the apiserver stops to receive request a few steps earlier

https://github.com/kubernetes/kubernetes/blob/253acfc8bce430ed835f14d5ec062356701cff2f/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L417-L458

has to be this the last thing stopping?

File: test/integration/framework/etcd.go [hunk 6]
```diff
@@ -198,7 +198,7 @@ func EtcdMain(tests func() int) {
 		// like k8s.io/klog/v2.(*loggingT).flushDaemon()
 		// TODO(#108483): Reduce this number once we address the
 		//   couple remaining issues.
-		if dg := runtime.NumGoroutine() - before; dg <= 15 {
+		if dg := runtime.NumGoroutine() - before; dg <= 9 {
```
Comment (aojea) [inline test/integration/framework/etcd.go:201]: :clap: :clap: :clap:

**Comment by enj** [comment]
@wojtek-t all comments addressed.

File: cmd/kube-apiserver/app/server.go (hunk 5 above)
Comment (liggitt) [reply cmd/kube-apiserver/app/server.go]: put another way, it sounds like using HTTPServerStoppedListening means in-flight write requests will now fail, not just in-flight long-lived watch requests

Comment (aojea) [reply cmd/kube-apiserver/app/server.go]: I'm not sure I follow, listening vs accepting has different meanings 

https://github.com/kubernetes/kubernetes/blob/9644edc321e3b7e5180eb7c15a27bf28e19485db/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L563-L564

Comment (wojtek-t) [reply cmd/kube-apiserver/app/server.go]: > that would seem to indicate we should use InFlightRequestsDrained not HTTPServerStoppedListening, right?

As I mentioned above, InFlightRequestsDrained does NOT include long-running requests. So that's not perfect.
@liggitt - I think the comment you pasted, is not really up-to-date.

I would appreciate if someone would double check me, but the  HTTPServerStoppedListening channel:
https://github.com/kubernetes/kubernetes/blob/253acfc8bce430ed835f14d5ec062356701cff2f/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L539

is effectively closed here:
https://github.com/kubernetes/kubernetes/blob/253acfc8bce430ed835f14d5ec062356701cff2f/staging/src/k8s.io/apiserver/pkg/server/secure_serving.go#L242
So when http server is already down. Which basically happens after the requests are drained.


I agree that HTTPServerStoppedListening is not a perfect signal [we're probably missing one more signal], but I still think it's better than the Drained one which doesn't include long-running requests.

Comment (enj) [reply cmd/kube-apiserver/app/server.go]: After reading the code I believe:

Neither `InFlightRequestsDrained` nor `HTTPServerStoppedListening` handle long running requests.  We have no option to handle that case AFAIK.

>  So when http server is already down. Which basically happens after the requests are drained.
> 
> I agree that HTTPServerStoppedListening is not a perfect signal [we're probably missing one more signal], but I still think it's better than the Drained one which doesn't include long-running requests.

This is not true.  `HTTPServerStoppedListening` corresponds to the listener socket being closed.  It does not close connections that have already been accepted (i.e. watches) by that socket (they have distinct FDs).

Thus I believe `InFlightRequestsDrained` is the best option available to us because:

1. We know new connections will not be made
2. We know that we have attempted to drain non-long running requests

Comment (enj) [reply cmd/kube-apiserver/app/server.go]: @wojtek-t @liggitt ping re ^

Comment (liggitt) [reply cmd/kube-apiserver/app/server.go]: > Thus I believe InFlightRequestsDrained is the best option available to us because:
>
> 1. We know new connections will not be made
> 2. We know that we have attempted to drain non-long running requests

that makes sense to me

Comment (enj) [reply cmd/kube-apiserver/app/server.go:415]: @liggitt this is ready now.

**Comment by wojtek-t** [comment]
@enj - I'm sorry for delay (I'm recently more often out than around).

Your explanation makes sense (I still think that the DrainedInFlight is not exactly what we want, but we don't have a better one, so we can leave with it). I'm planning to get to draining long-running requests too, which would address this issue.

This LGTM too!

And thanks a lot for following on that!
