### PR TITLE
Fix agnhost sctp

### LINKED ISSUE #124209: SCTP Server on agnhost image crashes when a client connects from the same pod
How to repro:
1. Run an agnhost pod listening on sctp
```
spec:
  containers:
  - command:
    - /agnhost
    - netexec
    - --sctp-port
    - "8080"
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
```

2. Exec into the pod and use the connect command to probe against the same pod
```
/agnhost connect --timeout=2s --protocol=sctp localhost:8080
bash-5.0# FATA[0014] execing command in container: command terminated with exit code 137
```

The stack trace 

```
I0406 18:21:17.102027       1 log.go:195] Started HTTP server on port 8080
I0406 18:21:17.102399       1 log.go:195] Started UDP server on port  8081
I0406 18:21:17.102465       1 log.go:195] Started SCTP server
I0406 18:22:07.943777       1 log.go:195] SCTP server exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15097bb]

goroutine 77 [running]:
k8s.io/kubernetes/test/images/agnhost/netexec.startSCTPServer(0x0?)
        /go/src/k8s.io/kubernetes/test/images/agnhost/netexec/netexec.go:696 +0x3fb
created by k8s.io/kubernetes/test/images/agnhost/netexec.main
        /go/src/k8s.io/kubernetes/test/images/agnhost/netexec/netexec.go:217 +0x22f
root@kind-worker:/#

```

that points to 

https://github.com/kubernetes/kubernetes/blob/f8930f980d2986f9e486b04c14c3e93e57bdbe12/test/images/agnhost/netexec/netexec.go#L696

and this is from the vendored library vendor/github.com/ishidawataru/sctp/sctp.go , 

/kind bug
/sig network 
/help

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #124209

#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/issues/124209#issuecomment-2052052796
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig network
/triage accepted

### CODE REVIEW

**Comment by aroradaman** [comment]
```go
Both [conn.RemoteAddr](https://github.com/ishidawataru/sctp/blob/master/sctp.go#L602) and [SCTPRemoteAddr](https://github.com/ishidawataru/sctp/blob/7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0/sctp.go#L590C20-L590C34) call the same underlying internal function. 

The first one implements/is-part of [net.Conn](https://github.com/golang/go/blob/5c20d5faeb3d048a31896f3edfb54dbd960d07cc/src/net/net.go#L173) while second one returns errors on which we can assert on. 
```

**Comment by aroradaman** [comment]
Both [RemoteAddr](https://github.com/ishidawataru/sctp/blob/master/sctp.go#L602) and [SCTPRemoteAddr](https://github.com/ishidawataru/sctp/blob/7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0/sctp.go#L590C20-L590C34) call the same underlying internal function. 

The first one helps to implement [net.Conn](https://github.com/golang/go/blob/master/src/net/net.go#L112) interface, while the second one returns errors on which we can assert.

File: test/images/agnhost/connect/connect.go [hunk 1]
```diff
@@ -114,11 +120,21 @@ func connectSCTP(dest string, timeout time.Duration) {
...
-		conn, err := sctp.DialSCTP("sctp", nil, addr)
-		if err == nil {
-			conn.Close()
+		conn, err = sctp.DialSCTP("sctp", nil, addr)
+		defer func() {
+			errCh <- conn.Close()
+		}()
+		if err != nil {
+			errCh <- err
+		}
```
Comment (aojea) [inline test/images/agnhost/connect/connect.go:129]: you have to defer only if the connection was successful, you have to check the error first

File: test/images/agnhost/connect/connect.go [hunk 2]
```diff
@@ -114,11 +120,21 @@ func connectSCTP(dest string, timeout time.Duration) {
...
+
+		if _, err = conn.Write([]byte(fmt.Sprintf("%s\n", data))); err != nil {
+			errCh <- err
```
Comment (aojea) [inline test/images/agnhost/connect/connect.go:132]: send the error and return, no need to keep processing things here

File: test/images/agnhost/connect/connect.go [hunk 3]
```diff
@@ -114,11 +120,21 @@ func connectSCTP(dest string, timeout time.Duration) {
...
 	go func() {
-		conn, err := sctp.DialSCTP("sctp", nil, addr)
-		if err == nil {
-			conn.Close()
+		conn, err = sctp.DialSCTP("sctp", nil, addr)
+		defer func() {
+			errCh <- conn.Close()
+		}()
+		if err != nil {
+			errCh <- err
```
Comment (aojea) [inline test/images/agnhost/connect/connect.go:128]: send the error and return, no need to keep processing things here

File: test/images/agnhost/netexec/netexec.go [hunk 4]
```diff
@@ -693,7 +693,11 @@ func startSCTPServer(sctpPort int) {
 	for {
 		conn, err := listener.AcceptSCTP()
 		assertNoError(err, fmt.Sprintf("failed accepting SCTP connections"))
-		clientAddress := conn.RemoteAddr().String()
+		remoteAddr, err := conn.SCTPRemoteAddr(0)
```
Comment (aojea) [inline test/images/agnhost/netexec/netexec.go:696]: this seems the same as `conn.RemoteAddr()`, no?

File: test/images/agnhost/netexec/netexec.go [hunk 5]
```diff
@@ -693,7 +693,11 @@ func startSCTPServer(sctpPort int) {
...
+		if err != nil {
+			assertNoError(err, "failed to get SCTP client remote address")
+		}
+		clientAddress := remoteAddr.String()
```
Comment (aojea) [inline test/images/agnhost/netexec/netexec.go:700]: you should check that remoteAddrs is not nil

File: test/images/agnhost/netexec/netexec.go (hunk 4 above)
Comment (aroradaman) [reply test/images/agnhost/netexec/netexec.go:696]: Yes, the underlying call is the same. It additionally returns an error on which we assert and exit. 

https://github.com/kubernetes/kubernetes/pull/124425#issuecomment-2068038859

File: test/images/agnhost/netexec/netexec.go (hunk 5 above)
Comment (aroradaman) [reply test/images/agnhost/netexec/netexec.go:700]: I think this should be sufficient `remoteAddrs` will only be nil if err is not nil.

File: test/images/agnhost/connect/connect.go [hunk 6]
```diff
@@ -114,11 +120,24 @@ func connectSCTP(dest string, timeout time.Duration) {
...
+		defer func() {
+			errCh <- conn.Close()
+		}()
+
+		if _, err = conn.Write([]byte(fmt.Sprintf("%s\n", data))); err != nil {
+			errCh <- err
+			return
+		}
+
+		if _, err = conn.Read(buf); err != nil {
```
Comment (aojea) [inline test/images/agnhost/connect/connect.go:137]: do we have guarantee something is going to write back? I can't remember if we implemented that in the sctp server

File: test/images/agnhost/connect/connect.go [hunk 7]
```diff
@@ -114,11 +120,24 @@ func connectSCTP(dest string, timeout time.Duration) {
...
-		if err == nil {
-			conn.Close()
+		conn, err = sctp.DialSCTP("sctp", nil, addr)
+		if err != nil {
+			errCh <- err
+			return
+		}
+		defer func() {
+			errCh <- conn.Close()
+		}()
```
Comment (aojea) [inline test/images/agnhost/connect/connect.go:130]: This implementation with the goroutine is hard to read, since is test code I Assume is ok, but if you return because of any error this will try to send something for a channel that nothing is reading, however the previous error will call os.Exit so this will die independently

**Comment by aojea** [comment]
you need to bump the version https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/VERSION , also we need to test this, not it assumes some data will sent back but I can't remember if we implemented that on the server

File: test/images/agnhost/connect/connect.go (hunk 6 above)
Comment (aroradaman) [reply test/images/agnhost/connect/connect.go:137]: Yes, the sctp server replies back.

**Comment by aroradaman** [comment]
> not it assumes some data will sent back but I can't remember if we implemented that on the server

The SCTP server [reads](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/netexec/netexec.go#L697) from the client and 
[writes](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/netexec/netexec.go#L697) back to it. 

The read is the reason I'm additionally sending some data from sctp-client, if I don't it will die in **AssertNoError** with EOF.

File: test/images/agnhost/connect/connect.go (hunk 6 above)
Comment (aroradaman) [reply test/images/agnhost/connect/connect.go:137]: Also, it tested this locally.

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-cli] Kubectl client Simple pod should contain last line of the log expand_less	

/test pull-kubernetes-e2e-gce
/lgtm
/approve 

Thanks

**Comment by aroradaman** [comment]
@aojea the image promotion failed https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1782455918949044224
```
./image-util.sh build_and_push agnhost
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Building image for agnhost OS/ARCH: linux/amd64...
./image-util.sh: line 130: kube::realpath: command not found
```

**Comment by aroradaman** [comment]
potential fix for **post-kubernetes-push-e2e-agnhost-test-images**: https://github.com/kubernetes/kubernetes/pull/124449

**Comment by aojea** [comment]
retriggered to see if #124449 fixed the problem https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1782455918949044224
