### PR TITLE
Limiting the scope of new kubectl get e2e tests to decrease flakiness

### LINKED ISSUE #84863: [Failing Test] gce-master-scale-correctness - sig-cli tests
**Which jobs are failing**:
gce-master-scale-correctness

**Which test(s) are failing**:
[sig-cli] Kubectl client kubectl get output should contain custom columns for each resource

**Since when has it been failing**:
11/6

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
```
Nov  6 12:28:23.583: Unexpected error:
    <*errors.StatusError | 0xc00202b040>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "nodes \"node1v6g5xn767k\" not found",
            Reason: "NotFound",
            Details: {
                Name: "node1v6g5xn767k",
                Group: "",
                Kind: "nodes",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    nodes "node1v6g5xn767k" not found
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:2581
```

**Anything else we need to know**:
n/a

/sig cli
/sig scalability 
/cc @kubernetes/sig-cli-test-failures

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
The `kubectl get output` e2e test I'd previously added ended up being flaky in certain e2e test scenarios. It relies on getting a list of API resources in the cluster and running `kubectl get` calls against them. The problem ended up being that other e2e tests could create resources that would cause this test to fail. This change limits the scope of the tests to exclude CRDs. This should still allow the test to catch new Kubernetes resources with improperly configured kubectl output while limiting the flakiness of the test.

**Which issue(s) this PR fixes**:
Fixes #84863

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig cli testing
/priority critical-urgent
/cc @wojtek-t @oxddr

### CODE REVIEW

File: test/e2e/kubectl/kubectl.go [hunk 1]
```diff
@@ -453,6 +449,14 @@ var _ = SIGDescribe("Kubectl client", func() {
 			testableResources := etcd.GetEtcdStorageDataForNamespace(f.Namespace.Name)
 
 			for _, group := range apiGroups {
+				// This significantly limits the scope of this test, but should
+				// ensure it's only covering Kubernetes API resources and not
+				// CRDs or other unexpected resources. For coverage of all
+				// resources in a cluster, remove this line.
+				if !strings.Contains(group.GroupVersion, ".k8s.io") {
+					continue
```
Comment (wojtek-t) [inline test/e2e/kubectl/kubectl.go]: Won't it exclude e.g. core/v1 ?

Also - someone from SIG CLI and/or Apimachinery should remove this one.

Comment (robscott) [reply test/e2e/kubectl/kubectl.go]: Yep, this assumes no new API resources will be added to that group. Definitely not ideal, but was trying to avoid adding a long list of approved API groups here. The real goal of this test is to ensure that new API resources are added with kubectl get output that works as intended.

**Comment by robscott** [comment]
@deads2k Do you have a minute to look at this change to the kubectl get e2e test I added? I know you had the original vision for it, hoping this change doesn't limit it too much.

/assign @deads2k

File: test/e2e/kubectl/kubectl.go [hunk 2]
```diff
@@ -453,6 +449,14 @@ var _ = SIGDescribe("Kubectl client", func() {
 			testableResources := etcd.GetEtcdStorageDataForNamespace(f.Namespace.Name)
 
 			for _, group := range apiGroups {
+				// This significantly limits the scope of this test, but should
+				// ensure it's only covering Kubernetes API resources and not
+				// CRDs or other unexpected resources. For coverage of all
+				// resources in a cluster, remove this line.
+				if !strings.Contains(group.GroupVersion, ".k8s.io") {
```
Comment (deads2k) [inline test/e2e/kubectl/kubectl.go]: Can you enumerate the known exceptions (existing groups)?

Comment (robscott) [reply test/e2e/kubectl/kubectl.go]: Currently that's everything in core, apps, autoscaling, batch, extensions, and policy API groups. On further thought it doesn't seem like it would be that bad to add those to a whitelist here, will push an update shortly.

Comment (robscott) [reply test/e2e/kubectl/kubectl.go]: @deads2k Updated this to include all groups that either have `.k8s.io` or do not have `.` in their group name. I _think_ this is a reliable way to exclude CRDs, but I could be missing something.

File: test/e2e/kubectl/kubectl.go [hunk 3]
```diff
@@ -453,6 +449,13 @@ var _ = SIGDescribe("Kubectl client", func() {
 			testableResources := etcd.GetEtcdStorageDataForNamespace(f.Namespace.Name)
 
 			for _, group := range apiGroups {
+				// This limits the scope of this test to exclude CRDs. This
+				// assumes that CRDs will not have a .k8s.io group and will have
+				// a . in their name.
+				if !strings.Contains(group.GroupVersion, ".k8s.io") && strings.Contains(group.GroupVersion, ".") {
```
Comment (deads2k) [inline test/e2e/kubectl/kubectl.go]: neat.  I think that actually work. :)
