### PR TITLE
Fix hack/e2e.go exit status for -test

### LINKED ISSUE #4177: hack/e2e.go -test not giving accurate exit status
Hacking this away from Jenkins for now, since Jenkins can just infer from test failures. :(

### PR DESCRIPTION
**Pull request by zmerlynn**
Test() was mis-tracked. Change the variable name / handling here, and
also just make it unset so that if it's ever uninitialized it's
obvious.

Along the way, clean up the output handling for remaining bash output
to dovetail stdout/stderr and remove escaping for TAP. This shows the
obvious issue with watchEvents today, which I'll open an issue on
shortly.

Fixes #4177

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @filbranden @satnam6502 @roberthbailey

File: hack/e2e.go [hunk 1]
```diff
@@ -146,21 +146,21 @@ func main() {
 		}
 	}
 
-	failure := false
+	var success bool
```
Comment (filbranden) [inline hack/e2e.go]: If neither `*ctlCmd` or `*test` are set then this will exit non-zero... no? If I simply want to `-up` or `-down` a cluster it should be able to report whether it was successful or not.

Comment (filbranden) [inline hack/e2e.go]: Maybe simply leaving everything as is and just doing `failure = !Test()` might be enough to fix this bug?

File: hack/e2e.go [hunk 2]
```diff
@@ -327,44 +327,11 @@ func finishRunning(stepName string, cmd *exec.Cmd) bool {
 	return result
 }
 
-func printBashOutputs(headerprefix, lineprefix, stdout, stderr string, escape bool) {
```
Comment (filbranden) [inline hack/e2e.go]: I like this but it's unrelated to the exit status of `-test`, so can we please keep it in a separate commit?

File: hack/e2e.go (hunk 1 above)
Comment (zmerlynn) [inline hack/e2e.go]: I hate the existing logic. The name is obnoxious.

Comment (zmerlynn) [inline hack/e2e.go]: But yes, I screwed up the -up case. Fixing.

File: hack/e2e.go (hunk 2 above)
Comment (zmerlynn) [inline hack/e2e.go]: Not anymore?

Comment (zmerlynn) [inline hack/e2e.go]: Those hunks are easy to separate, splitting.

File: hack/e2e.go [hunk 3]
```diff
@@ -277,8 +277,8 @@ func Test() bool {
 // call the returned anonymous function to stop.
 func runBashUntil(stepName string, cmd *exec.Cmd) func() {
 	log.Printf("Running in background: %v", stepName)
-	stdout, stderr := bytes.NewBuffer(nil), bytes.NewBuffer(nil)
-	cmd.Stdout, cmd.Stderr = stdout, stderr
+	output := bytes.NewBuffer(nil)
```
Comment (filbranden) [inline hack/e2e.go]: I'm wondering if we could simply use `cmd.CombinedOutput()` here? Maybe in a goroutine? It's not like we're streaming the output to stdout live, we're just capturing it to include in the final output... Not 100% sure if it will work with a command that gets interrupted but I think it just might... What do you think?

**Comment by filbranden** [comment]
Looks good. Certainly a step in the right direction. I still wish we could further simplify it by using `cmd.CombinedOutput()` but I'm happy to merge this one as is and try to refactor that later on. Unless you tell me not to, I'll merge it as soon as Travis is happy with it.

Cheers,
Filipe

**Comment by zmerlynn** [comment]
`CombinedOutput` in a goroutine looks promising, but I'm not sure about signal processing there either. Certainly more effort than I wanted here. :)
