### PR TITLE
Validate CSI Inline Migration unconditionally

### LINKED ISSUE #80931: Re-review API validation for CSI Inline Migration
**What happened**:
While glancing through storage validation.go, I noticed that we were doing feature gate checking in validation for CSI inline migration.  At first glance, I think this will cause validation errors when downgrading to a version with the feature disabled.

https://github.com/kubernetes/kubernetes/commit/c34309acdf1813961051023e913e07ec7a535428#diff-5aba802af469dbe928456a4b2c7988adR177

**What you expected to happen**:
We generally don't do feature gate checking in validation in order to support downgrade cases.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As @msau42 pointed out in #80931, we should perform validation unconditionally for downgrading to a version with the feature disabled.

**Which issue(s) this PR fixes**:
Fixes #80931

**Special notes for your reviewer**:

```release-note
Fixes validation of VolumeAttachment API objects created with inline volume sources.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @msau42

**Comment by tedyu** [comment]
@msau42 
Can you see if I missed something ?

File: pkg/apis/storage/validation/validation.go [hunk 1]
```diff
@@ -174,11 +171,7 @@ func validateVolumeAttachmentSource(source *storage.VolumeAttachmentSource, fldP
 	allErrs := field.ErrorList{}
 	switch {
 	case source.InlineVolumeSpec == nil && source.PersistentVolumeName == nil:
-		if utilfeature.DefaultFeatureGate.Enabled(features.CSIMigration) {
-			allErrs = append(allErrs, field.Required(fldPath, "must specify exactly one of inlineVolumeSpec and persistentVolumeName"))
-		} else {
-			allErrs = append(allErrs, field.Required(fldPath, "must specify persistentVolumeName when CSIMigration feature is disabled"))
-		}
+		allErrs = append(allErrs, field.Required(fldPath, "must specify exactly one of inlineVolumeSpec and persistentVolumeName"))
```
Comment (ddebroy) [inline pkg/apis/storage/validation/validation.go]: Now that I am looking at this again, I wonder if an error message like: `must specify either inlineVolumeSpec or persistentVolumeName` makes more sense in the case where neither are specified. The `exactly one of ... ` is more appropriate for the case below (where both `persistentVolumeName` and `inlineVolumeSpec` are specified.)

**Review by ddebroy — COMMENTED** [review]
Looks good with one suggestion.

**Comment by tedyu** [comment]
@ddebroy 
Your comment has been addressed.

File: pkg/apis/storage/validation/validation.go [hunk 2]
```diff
@@ -174,11 +171,7 @@ func validateVolumeAttachmentSource(source *storage.VolumeAttachmentSource, fldP
 	allErrs := field.ErrorList{}
 	switch {
 	case source.InlineVolumeSpec == nil && source.PersistentVolumeName == nil:
-		if utilfeature.DefaultFeatureGate.Enabled(features.CSIMigration) {
```
Comment (liggitt) [inline pkg/apis/storage/validation/validation.go]: restore this, it only affects the validation message, not whether  the object is considered valid or not (both branches lead to an error)

File: pkg/apis/storage/validation/validation.go [hunk 3]
```diff
@@ -187,11 +180,7 @@ func validateVolumeAttachmentSource(source *storage.VolumeAttachmentSource, fldP
 			allErrs = append(allErrs, field.Required(fldPath.Child("persistentVolumeName"), "must specify non empty persistentVolumeName"))
 		}
 	case source.InlineVolumeSpec != nil:
-		if utilfeature.DefaultFeatureGate.Enabled(features.CSIMigration) {
-			allErrs = append(allErrs, storagevalidation.ValidatePersistentVolumeSpec(source.InlineVolumeSpec, "", true, fldPath.Child("inlineVolumeSpec"))...)
-		} else {
-			allErrs = append(allErrs, field.Forbidden(fldPath, "may not specify inlineVolumeSpec when CSIMigration feature is disabled"))
-		}
+		allErrs = append(allErrs, storagevalidation.ValidatePersistentVolumeSpec(source.InlineVolumeSpec, "", true, fldPath.Child("inlineVolumeSpec"))...)
```
Comment (liggitt) [inline pkg/apis/storage/validation/validation.go]: this looks good

**Comment by liggitt** [comment]
one comment about restoring the conditional validation message, then lgtm

this will need to be picked back to 1.15

File: pkg/apis/storage/validation/validation.go (hunk 2 above)
Comment (tedyu) [reply pkg/apis/storage/validation/validation.go]: @liggitt 
Your comment has been addressed

File: pkg/apis/storage/validation/validation.go [hunk 4]
```diff
@@ -18,6 +18,7 @@ package validation
 
 import (
 	"fmt"
+	"k8s.io/kubernetes/pkg/features"
```
Comment (liggitt) [inline pkg/apis/storage/validation/validation.go]: revert this to group with other `k8s.io/kubernetes` imports

File: pkg/apis/storage/validation/validation_test.go [hunk 5]
```diff
@@ -400,27 +400,6 @@ func TestVolumeAttachmentValidation(t *testing.T) {
 			t.Errorf("expected success: %v %v", volumeAttachment, errs)
 		}
 	}
-
-	migrationDisabledErrorCases := []storage.VolumeAttachment{
-		{
-			// InlineSpec specified with migration disabled
```
Comment (liggitt) [inline pkg/apis/storage/validation/validation_test.go]: actually, move this up to the `migrationDisabledSuccessCases`... a valid inlineSpec should validate

Comment (tedyu) [reply pkg/apis/storage/validation/validation_test.go]: That would lead to:
```
--- FAIL: TestVolumeAttachmentValidation (0.00s)
    validation_test.go:418: expected failure: {{ } {foo      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []} {myattacher {<nil> 0x2222b80} node} {false map[] <nil> <nil>}} []
```

Comment (liggitt) [reply pkg/apis/storage/validation/validation_test.go]: in the `migrationDisabledSuccessCases`, success is expected

Comment (liggitt) [reply pkg/apis/storage/validation/validation_test.go]: just move this testcase into `migrationDisabledSuccessCases`

**Comment by tedyu** [comment]
@liggitt 
Your comment has been addressed.

**Comment by davidz627** [comment]
thanks @tedyu @liggitt !

**Comment by liggitt** [comment]
let me know when the 1.15 pick is open and I'll tag that as well

**Comment by tedyu** [comment]
I ran the following for master branch of my local repo:
```
GITHUB_USER=tedyu hack/cherry_pick_pull.sh upstream/release-1.5 80945
```
```
Falling back to patching base and 3-way merge...
Auto-merging pkg/apis/storage/validation/validation_test.go
CONFLICT (content): Merge conflict in pkg/apis/storage/validation/validation_test.go
Auto-merging pkg/apis/storage/validation/validation.go
CONFLICT (content): Merge conflict in pkg/apis/storage/validation/validation.go
error: Failed to merge in the changes.
Patch failed at 0001 Validate CSI Inline Migration unconditionally
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
```
I wonder if the command I used was wrong.

**Comment by liggitt** [comment]
you probably want upstream/release-1.15

**Comment by tedyu** [comment]
That was the issue

**Comment by tedyu** [comment]
Created #81038
