### PR TITLE
Fix "Kubelet doesn't kill old pods when BoundPods is empty" issue

### LINKED ISSUE #2495: Kubelet doesn't kill old pods when BoundPods is empty
To reproduce:
* Start a cluster via hack/local-up-cluster.sh
* Start some pods
* Kill the cluster
* "docker ps -a" should show the pod containers running still
* Start the cluster again
* "etcdctl ls /registry" should show that there is no boundpods directory -- only minions and services
* "docker ps -a" should show the old pod containers still running
* Start a new pod
* After, say, 10s, "docker ps -a" should show the old containers dead

/cc @dchen1107

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #2495: **Kubelet doesn't kill old pods when BoundPods is empty**

The first time kubelet starts, while there are no updates, `kl.pods` is `nil` ([pkg/kubelet/kubelet.go#L1118](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1118)):

``` GO
case <-time.After(kl.resyncInterval):
    glog.V(4).Infof("Periodic sync")
    if kl.pods == nil {
        continue
    }
```

which guarantees that [`syncPods(...)`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L992), which contains the container killing logic is never called.

So the first part of the fix is to remove this check and allow `syncPods(...)` to be called even when nil, so that the first periodic sync can clean up old containers.

However, this isn't enough because inside `syncPods(...)` there is a check to make sure that all sources have been "seen" before it will kill old containers ([pkg/kubelet/kubelet.go#L1026](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1026)):

``` GO
if !kl.sourcesReady() {
    // If the sources aren't ready, skip deletion, as we may accidentally delete pods
    // for sources that haven't reported yet.
    glog.V(4).Infof("Skipping deletes, sources aren't ready yet.")
    return nil
}
```

This check is performed in the [`SeenAllSources()`](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/config.go#L87) function, and is `true` only if a `SET` update has been seen for all registered kubelet sources.

However, no `SET` update is emitted by any of the sources until they successfully read a value, which means the original problem still exists.

So the second part of the fix is to have the kubelet boundpod sources (etcd, file, and http) all emit a `SET` update with an empty pod list when the source is first read but no value exists; the empty update will not make it back to the kubelet sync loop because it will be filtered out by the [update merge logic](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/config.go#L140); but it will cause the source to be [marked as seen](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/config/config.go#L238) so the periodic sync (enabled by the first fix) will clean up the old containers (since all sources will now be marked as seen after the first read attempt).

### CODE REVIEW

**Comment by thockin** [comment]
The second step is probably to split the "have we seen the source" logic up
to be per-source, so we can delete file containers even if the API server
is AWOL

File: pkg/kubelet/config/file.go [hunk 1]
```diff
@@ -54,6 +54,8 @@ func NewSourceFile(path string, period time.Duration, updates chan<- interface{}
 func (s *sourceFile) run() {
 	if err := s.extractFromPath(); err != nil {
 		glog.Errorf("Unable to read config path %q: %v", s.path, err)
+		// Emit an update with an empty PodList to allow FileSource to be marked as seen
+		s.updates <- kubelet.PodUpdate{[]api.BoundPod{}, kubelet.SET, kubelet.FileSource}
```
Comment (lavalamp) [inline pkg/kubelet/config/file.go]: This seems questionable-- perhaps only do this if err is file not found? You don't want to blow away all pods if they put up a non-parsing config.

File: pkg/kubelet/config/http.go [hunk 2]
```diff
@@ -52,6 +52,8 @@ func NewSourceURL(url string, period time.Duration, updates chan<- interface{})
 func (s *sourceURL) run() {
 	if err := s.extractFromURL(); err != nil {
 		glog.Errorf("Failed to read URL: %v", err)
+		// Emit an update with an empty PodList to allow HTTPSource to be marked as seen
+		s.updates <- kubelet.PodUpdate{[]api.BoundPod{}, kubelet.SET, kubelet.HTTPSource}
```
Comment (lavalamp) [inline pkg/kubelet/config/http.go]: Same idea here-- should only emit this blank list when you get a blank return; a 404 or transport error could maybe be transient and you don't want to mistake that for positive knowledge that nothing should be running.

File: pkg/kubelet/config/etcd.go [hunk 3]
```diff
@@ -59,7 +59,7 @@ func NewSourceEtcd(key string, client tools.EtcdClient, updates chan<- interface
 }
 
 func (s *sourceEtcd) run() {
-	watching := s.helper.Watch(s.key, 0)
+	watching := s.helper.Watch(s.key, 0, true /* emitNilOnNotFound */)
```
Comment (lavalamp) [inline pkg/kubelet/config/etcd.go]: So I know we chatted about this last night, but I think I wasn't thinking very clearly. I think the pattern we decided on elsewhere, basically because of this problem, is that clients must first list, and then watch (using the resourceVersion the list returns).

So here is an example (though it uses the api and not etcd): https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/proxy/config/api.go#L82

s.helper should have a few different List methods that will return what you need.

Sorry for the bad advice last night, I didn't make the right connection until I saw this written out :/

**Comment by saad-ali** [comment]
@thockin Good suggestion to split up the "sources seen" logic to be more robust--Created #3371 to track this.

@lavalamp Great points. Feedback addressed.

PTAL

File: pkg/kubelet/config/etcd.go [hunk 4]
```diff
@@ -59,7 +59,17 @@ func NewSourceEtcd(key string, client tools.EtcdClient, updates chan<- interface
 }
 
 func (s *sourceEtcd) run() {
-	watching := s.helper.Watch(s.key, 0)
+	boundPods := api.BoundPods{}
+	err := s.helper.ExtractToList(s.key, &boundPods)
+	glog.Infof("Read BoundPods via ExtractList: %#v", boundPods)
```
Comment (lavalamp) [inline pkg/kubelet/config/etcd.go]: .V(4).Infof ?

File: pkg/kubelet/config/etcd.go [hunk 5]
```diff
@@ -87,21 +97,23 @@ func (s *sourceEtcd) run() {
...
-	boundPods, ok := ev.Object.(*api.BoundPods)
-	if !ok {
-		return pods, errors.New("unable to parse response as BoundPods")
-	}
-
-	for _, pod := range boundPods.Items {
-		// TODO: generate random UID if not present
-		if pod.UID == "" && !pod.CreationTimestamp.IsZero() {
-			pod.UID = strconv.FormatInt(pod.CreationTimestamp.Unix(), 10)
+	if ev.Object != nil {
```
Comment (lavalamp) [inline pkg/kubelet/config/etcd.go]: nit: 
```go
if ev.Object == nil {
  return pods, nil
}
```

Keeps the indentation level low. :)

File: pkg/kubelet/config/file_test.go [hunk 6]
```diff
@@ -92,8 +92,15 @@ func TestUpdateOnNonExistentFile(t *testing.T) {
...
-		t.Errorf("Expected no update, Got %#v", got)
+		update := got.(kubelet.PodUpdate)
+		expected := CreatePodUpdate(kubelet.SET, kubelet.FileSource)
+		if !api.Semantic.DeepEqual(expected, update) {
+			t.Fatalf("Expected %#v, Got %#v", expected, update)
+		}
+
 	case <-time.After(2 * time.Millisecond):
+		t.Errorf("Expected update, timeout instead")
+
```
Comment (lavalamp) [inline pkg/kubelet/config/file_test.go]: optional nit: extra blank lines

**Comment by lavalamp** [comment]
LGTM, just a few minor suggestions

**Comment by saad-ali** [comment]
Thanks. Nits addressed

**Comment by lavalamp** [comment]
LGTM, thanks for the change!
