### PR TITLE
Fix typo in create-heapster-node

### LINKED ISSUE #73632: Cluster creation script fails - no "get-linux-node-instance-metadata-from-file" function
**What happened**:
The gce cluster creation script fails, when HEAPSTER_MACHINE_TYPE env variable is provided. The cluster/gce/util.sh script calls 

**What you expected to happen**:
Script shouldn't fail.

**How to reproduce it (as minimally and precisely as possible)**:
Run hack script to setup the cluster.

**Anything else we need to know?**:
Tis bug was introduced in https://github.com/kubernetes/kubernetes/pull/73442
This problem is due to call to not existing function - get-linux-node-instance-metadata-from-file": https://github.com/kubernetes/kubernetes/blob/a3c14ecfa5f463bf712760e7b823ecd32cefca4b/cluster/gce/util.sh#L2777

**Environment**:
- Kubernetes version (use `kubectl version`): HEAD
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mborsz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Without this PR, all tests using special heapster node are failing with:
```
I0201 08:06:13.544] Creating a special node for heapster with machine-type n1-standard-32
W0201 08:06:14.107] /workspace/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 2764: get-linux-node-instance-metadata-from-file: command not found
W0201 08:06:14.404] ERROR: (gcloud.compute.instances.create) argument --metadata-from-file: not enough args
```
**Which issue(s) this PR fixes**:

Fixes #73632

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @wojtek-t @mm4tt

### CODE REVIEW

File: cluster/gce/config-test.sh [hunk 1]
```diff
@@ -179,7 +179,7 @@ ENABLE_METADATA_AGENT="${KUBE_ENABLE_METADATA_AGENT:-none}"
 
 # One special node out of NUM_NODES would be created of this type if specified.
 # Useful for scheduling heapster in large clusters with nodes of small size.
-HEAPSTER_MACHINE_TYPE="${HEAPSTER_MACHINE_TYPE:-}"
+HEAPSTER_MACHINE_TYPE="${HEAPSTER_MACHINE_TYPE:-n1-standard-4}"
```
Comment (wojtek-t) [inline cluster/gce/config-test.sh]: We don't want this in my opinion.
This file is used for every single test and we don't want to have 4-core heapster machine in bazillions of different test suites we are running.

Comment (mborsz) [reply cluster/gce/config-test.sh]: Sure, I just put this here to trigger the logic in the gce-100-performance presubmit and validate the change. I'm going to remove this before submitting.

Comment (mborsz) [reply cluster/gce/config-test.sh]: it worked, removing.

**Comment by mborsz** [comment]
@mm4tt FYI

**Comment by pjh** [comment]
Just saw this, sorry for missing this change in my PR!
