### PR TITLE
kubeadm: fix panic when no UpgradeConfiguration was found in the config file

### LINKED ISSUE #3161: `kubeadm upgrade node` panics if config has `KubeletConfiguration`
```
[root@moniserver ~]# kubeadm --config /etc/kubernetes/kubeadm.yaml upgrade node
W0215 12:30:36.826324  766880 upgradeconfiguration.go:135] [config] WARNING: YAML document with Component Configs kubelet.config.k8s.io is deprecated for upgrade and will be ignored
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f2c6db5b612]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/util/config.prepareStaticVariables({0x5f2c6e75d560, 0x0})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/util/config/common.go:398 +0x152
k8s.io/kubernetes/cmd/kubeadm/app/util/config.LoadOrDefaultUpgradeConfiguration({0x7ffd1cac1d91, 0x1c}, 0xc00074fba0, {0x0, 0x0})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/util/config/upgradeconfiguration.go:160 +0x1a5
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newNodeData(0xc000776908, 0xc000458910, {0x5f2c6e890ae8, 0xc00007c030})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/cmd/upgrade/node.go:184 +0x3ba
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdNode.func2(0xc000776908, {0xc00006d720, 0x0, 0x2})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/cmd/upgrade/node.go:127 +0x9b
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData(0xc00016e240, {0xc00006d720, 0x0, 0x2})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/cmd/phases/workflow/runner.go:185 +0xd8
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdNode.func1(0xc000776908, {0xc00006d720, 0x0, 0x2})
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/cmd/upgrade/node.go:90 +0xce
github.com/spf13/cobra.(*Command).execute(0xc000776908, {0xc00006d700, 0x2, 0x2})
	/build/kubernetes/src/kubernetes-1.32.1/vendor/github.com/spf13/cobra/command.go:985 +0xfca
github.com/spf13/cobra.(*Command).ExecuteC(0xc000452608)
	/build/kubernetes/src/kubernetes-1.32.1/vendor/github.com/spf13/cobra/command.go:1117 +0x9d0
github.com/spf13/cobra.(*Command).Execute(0xc000452608)
	/build/kubernetes/src/kubernetes-1.32.1/vendor/github.com/spf13/cobra/command.go:1041 +0x32
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/app/kubeadm.go:47 +0xd1
main.main()
	/build/kubernetes/src/kubernetes-1.32.1/cmd/kubeadm/kubeadm.go:25 +0x13
```
```
[root@moniserver ~]# cat /etc/kubernetes/kubeadm.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# Use a resolv.conf file without the curry domain/search to prevent ndots spam.
resolvConf: /etc/resolv-k8s.conf
# Wait this duration for pods to gracefully terminate.
shutdownGracePeriod: 120s
# Of the duration above, the following duration will be reserved for terminating critical pods after non-critical ones.
shutdownGracePeriodCriticalPods: 20s
```

Not specifying a `--config` with `KubeletConfiguration` for this operation works around the issue, but I thin it would be best if the config was gracefully ignored as the log message indicates.

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubeadm: fix panic when no UpgradeConfiguration was found in the config file

#### Which issue(s) this PR fixes:

Fixes kubernetes/kubeadm#3161

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fix panic when no UpgradeConfiguration was found in the config file
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 1]
```diff
@@ -137,6 +137,11 @@ func LoadUpgradeConfigurationFromFile(cfgPath string, _ LoadOrDefaultConfigurati
 		}
 	}
 
+	// If no UpgradeConfiguration kind was found in the config file, return an error.
+	if upgradeCfg == nil {
+		return nil, errors.Errorf("no UpgradeConfiguration kind was found in the YAML file")
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/upgradeconfiguration.go:142]:
```suggestion
		return nil, errors.Errorf("no % found in the configuration file", constants.UpgradeConfigurationKind)
```

let't use the constant and not mention 'kind'.
the file can be json as well.

we should also chanange this i tihnk;
```
	// Check is there any component configs defined in the config file.
	for gvk := range docmap {
		if componentCfgGV.Has(gvk.Group) {
			klog.Warningf("[config] WARNING: YAML document with Component Configs %v is deprecated for upgrade and will be ignored \n", gvk.Group)
			continue
		}
	}
```

i think the logic should be that any kind other than upgradeconfiguration produce the warning?
other places like 'init' have similar i believe.

**Review by neolit123 — COMMENTED** [review]
thanks for sending the PR @SataQiu

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go:142]: we need a message for this one for unsupported kinds
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/initconfiguration.go#L361

Comment (SataQiu) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go]: Updated, PTAL. @neolit123

Comment (SataQiu) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go]: >the file can be json as well.

We mentioned `YAML document` in several places, and maybe it should be renamed uniformly with another PR, but that's not a serious issue.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 2]
```diff
@@ -22,28 +22,34 @@ import (
...
 // finds a UpgradeConfiguration, decodes it, dynamically defaults it and then validates it prior to return.
 func documentMapToUpgradeConfiguration(gvkmap kubeadmapi.DocumentMap, allowDeprecated bool) (*kubeadmapi.UpgradeConfiguration, error) {
-	var internalcfg *kubeadmapi.UpgradeConfiguration
+	upgradeBytes := []byte{}
 
 	for gvk, bytes := range gvkmap {
+		if kubeadmutil.GroupVersionKindsHasInitConfiguration(gvk) || kubeadmutil.GroupVersionKindsHasClusterConfiguration(gvk) || componentconfigs.Scheme.IsGroupRegistered(gvk.Group) {
+			klog.Warningf("[config] WARNING: YAML document with GroupVersionKind %v is deprecated for upgrade, please use config file with kind of UpgradeConfiguration instead \n", gvk)
+			continue
+		}
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/upgradeconfiguration.go:46]:
```suggestion
```

the deprecation so technically over so this can be removed.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 3]
```diff
@@ -22,28 +22,34 @@ import (
...
+
+		if gvk.Kind != constants.UpgradeConfigurationKind {
+			klog.Warningf("[config] WARNING: Ignored YAML document with GroupVersionKind %v\n", gvk)
+			continue
+		}
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/upgradeconfiguration.go:51]: this should be below 

```
		// check if this version is supported and possibly not deprecated
		if err := validateSupportedVersion(gvk, allowDeprecated, true); err != nil {
			return nil, err
		}
```

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 4]
```diff
@@ -123,18 +108,8 @@ func LoadUpgradeConfigurationFromFile(cfgPath string, _ LoadOrDefaultConfigurati
 	// Convert documentMap to internal UpgradeConfiguration, InitConfiguration and ClusterConfiguration from config file will be ignored.
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/upgradeconfiguration.go:108]: the comments here can be updated to only say that everything other than UpgradeConfiguration will be ignored. instead of talking about the various kinds.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go]: > > the file can be json as well.
> 
> We mentioned `YAML document` in several places, and maybe it should be renamed uniformly with another PR, but that's not a serious issue.

agreed, also given this one has to be backported and the YAML issue can be fixed only on master branch.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go (hunk 4 above)
Comment (SataQiu) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go]: updated

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold

@HirazawaUi ptal too if possible, since we need to backport this to 2 releases. 1.31, 1.32.

@SataQiu it seems we are inconsistent about a few things under util/config which can be a separate pr for the master branch:
- using text 'YAML' while json i also supported.
- some documentMapToX functions don't warn about non-target kinds e.g. join only needs joinconfiguration
https://github.com/kubernetes/kubernetes/blob/46d68d306e09b71ffe729ea93fb9aa9e09b975ee/cmd/kubeadm/app/util/config/joinconfiguration.go#L100
- probably other things too.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 5]
```diff
@@ -22,69 +22,52 @@ import (
...
-			// Set internalcfg to an empty struct value the deserializer will populate
-			internalcfg = &kubeadmapi.UpgradeConfiguration{}
-			// Decode the bytes into the internal struct. Under the hood, the bytes will be unmarshalled into the
-			// right external version, defaulted, and converted into the internal version.
-			if err := runtime.DecodeInto(kubeadmscheme.Codecs.UniversalDecoder(), bytes, internalcfg); err != nil {
-				return nil, err
-			}
-			continue
-		}
+		upgradeBytes = bytes
```
[the remark this answers is not in the document]
Comment (SataQiu) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go:58]: Our previous actions didn't break here, so the later one will override the previous one. 
I do not recommend modifying the behavior in this PR to avoid disruptive changes.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go [hunk 6]
```diff
@@ -22,69 +22,52 @@ import (
...
+	upgradeBytes := []byte{}
 
 	for gvk, bytes := range gvkmap {
 		// check if this version is supported and possibly not deprecated
 		if err := validateSupportedVersion(gvk, allowDeprecated, true); err != nil {
 			return nil, err
 		}
 
+		// not interested in anything other than UpgradeConfiguration
+		if gvk.Kind != constants.UpgradeConfigurationKind {
```
[the remark this answers is not in the document]
Comment (SataQiu) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go:48]: yes, we can add the ut.

File: cmd/kubeadm/app/util/config/upgradeconfiguration.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (HirazawaUi) [reply cmd/kubeadm/app/util/config/upgradeconfiguration.go:58]: Agree. However, this implicitly implemented behavior is not currently documented. We should consider updating the documentation to explicitly clarify this behavior.

**Comment by HirazawaUi** [comment]
/lgtm
/hold cancel

Good night!

We still need to follow up the [comment](https://github.com/kubernetes/kubernetes/pull/130202#discussion_r1959883873) .

**Comment by neolit123** [comment]
@SataQiu we should backport to 1.31, 1.32

**Comment by neolit123** [comment]
> @SataQiu we should backport to 1.31, 1.32
> 
> maybe not 1.30

i have some time and will send the backports in a bit.
