### PR TITLE
KEP-2570: Add tiered memory protection, metrics, rollback fix, and E2E tests for MemoryQoS

### LINKED ISSUE #137674: Pod-level memory.min not reconciled when MemoryQoS config changes
### What happened?

When MemoryQoS is enabled with `memoryReservationPolicy=HardReservation`, the kubelet sets `memory.min` on pod-level cgroups. If the operator later disables MemoryQoS or switches to `memoryReservationPolicy=None` and restarts kubelet, the pod-level `memory.min` retains its previous non-zero value for existing pods.

QoS-level cgroups (`kubepods-burstable.slice`) are correctly reset via the periodic `setMemoryQoS()` loop, but pod-level cgroups are not reconciled.

### What did you expect to happen?

Pod-level `memory.min` should be reset to 0 when MemoryQoS is disabled or `memoryReservationPolicy` changes to `None`.

### How can we reproduce it (as minimally and precisely as possible)?

   1. Start kubelet with `--feature-gates=MemoryQoS=true` and `memoryReservationPolicy: HardReservation`
   2. Create a Burstable pod with `requests.memory: 128Mi`
   3. Verify pod cgroup has `memory.min=134217728`
   4. Change kubelet config to disable MemoryQoS or set `memoryReservationPolicy: None`, restart kubelet
   5. Observe pod cgroup still has `memory.min=134217728`

### Anything else we need to know?

 This also affects the container-level `memory.min` set in `generateLinuxContainerResources()`, which only runs at container creation time. However, container-level is less impactful since containers are typically recreated more frequently than kubelet config changes.

 ### Related

   - KEP-2570: Memory QoS with cgroups v2
   - https://github.com/kubernetes/kubernetes/pull/137584
   - https://github.com/kubernetes/kubernetes/pull/137637

### Kubernetes version

<details>

```console
$ kubectl version
master (v1.36.0-alpha)
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sohankunkerkar**
#### What type of PR is this?
  /kind feature

  #### What this PR does / why we need it:
  Adds supporting infrastructure for KEP-2570 (MemoryQoS) alpha v3 in v1.36:

  1. **Kernel 5.9+ version check**: Logs a warning when MemoryQoS is enabled on kernels older than 5.9, which have a livelock bug in `memory.high` throttling.

  2. **Tiered memory protection**: Guaranteed pods get `memory.min` (hard protection, kernel never reclaims) while Burstable pods get `memory.low` (soft protection, kernel prefers not to reclaim but can under extreme pressure). This avoids hard-locking memory for overcommitted Burstable workloads, as discussed in kubernetes/kubernetes#131077.

  3. **Node-level metrics**: Two separate gauges for memory protection observability:
     - `kubelet_memory_qos_node_memory_min_bytes`: hard-reserved memory (Guaranteed pods)
     - `kubelet_memory_qos_node_memory_low_bytes`: soft-reserved memory (Burstable pods)

  4. **Pod-level rollback fix**: When `memoryReservationPolicy` changes or MemoryQoS is disabled, pod-level `memory.min` and `memory.low` are reconciled to 0 via the periodic `setMemoryQoS` loop. Previously, stale values persisted because the cgroup manager only writes keys present in the Unified map.

  5. **E2E tests**

  Benchmark results: https://github.com/sohankunkerkar/kep-2570-memoryqos-benchmarks

  #### Which issue(s) this PR is related to:

  KEP: https://github.com/kubernetes/enhancements/issues/2570
  Fixes https://github.com/kubernetes/kubernetes/issues/137674
  Depends on https://github.com/kubernetes/kubernetes/pull/137584

 <!--                                                                                                                                              
Please link relevant issues to help with tracking.                                                                                                
                                                                                                                                                  
To automatically close the linked issue(s) when this PR is merged,                                                                                
add the word "Fixes" before the issue number or link.                                                                                             
Do not use "Fixes" if the PR is of kind `failing-test` or `flake`.                                                                                
                                                                                                                                                  
Reference KEPs when applicable in addition to specific issues.                                                                                    
                                                                                                                                                  
Examples:                                                                                                                                         
Fixes #<issue number>                                                                                                                             
<issue link> (issue in a different repository)                                                                                                    
KEP: https://github.com/kubernetes/enhancements/issues/<kep-issue-number>                                                                         
                                                                                                                                                  
If there is no associated issue, then write "N/A".                                                                                                
-->                                                                                                                                               
                                                                                                                                                  
#### Special notes for your reviewer:                                                                                                             
                                                                                                                                                  
#### Does this PR introduce a user-facing change?                                                                                                 
<!--                                                                                                                                              
If no, just write "NONE" in the release-note block below.                                                                                         
If yes, a release note is required:                                                                                                               
Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the    
string "action required".                                                                                                                         
                                                                                                                                                  
For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md                                       
-->                                                                                                                                               
```release-note                                                                                                                                   
Add tiered cgroup v2 memory protection for MemoryQoS: memory.min for Guaranteed pods, memory.low for Burstable pods, with node-level metrics and rollback reconciliation (KEP-2570)                                                                                                                                         
```                                                                                                                                               
                                                                                                                                                  
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:                                                    
                                                                                                                                                  
<!--                                                                                                                                              
This section can be blank if this pull request does not require a release note.                                                                   
                                                                                                                                                  
When adding links which point to resources within git repositories, like                                                                          
KEPs or supporting documentation, please reference a specific commit and avoid                                                                    
linking directly to the master branch. This ensures that links reference a                                                                        
specific point in time, rather than a document that may change over time.                                                                         
                                                                                                                                                  
See here for guidance on getting permanent links to files: https://help.github.com/en/articles/getting-permanent-links-to-files                   
                                                                                                                                                  
Please use the following format for linking documentation:                                                                                        
- [KEP]: <link>                                                                                                                                   
- [Usage]: <link>                                                                                                                                 
- [Other doc]: <link>                                                                                                                             
-->                                                                                                                                               
```docs                                                                                                                                           
[KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2570-memory-qos/README.md                                             
```

### CODE REVIEW

**Comment by sohankunkerkar** [comment]
Benchmark testing: https://github.com/sohankunkerkar/kep-2570-memoryqos-benchmarks

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 1]
```diff
@@ -156,7 +156,13 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(ctx context.
...
-			unified[cm.Cgroup2MemoryMin] = strconv.FormatInt(memoryRequest, 10)
+			// Guaranteed pods get memory.min (hard protection).
+			// Burstable pods get memory.low (soft protection).
+			if kubeapiqos.GetPodQOS(pod) == v1.PodQOSGuaranteed {
+				unified[cm.Cgroup2MemoryMin] = strconv.FormatInt(memoryRequest, 10)
+			} else {
+				unified[cm.Cgroup2MemoryLow] = strconv.FormatInt(memoryRequest, 10)
+			}
 		} else {
 			unified[cm.Cgroup2MemoryMin] = "0"
```
Comment (QiWang19) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:167]: For a safely clear, we can also add `unified[cm.Cgroup2MemoryLow] = "0"` in the else case here?

Comment (sohankunkerkar) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:167]: Good catch! will fix that

File: pkg/kubelet/cm/qos_container_manager_linux.go [hunk 2]
```diff
@@ -288,34 +289,73 @@ func (m *qosContainerManagerImpl) retrySetMemoryReserve(logger klog.Logger, conf
...
 	if m.memoryReservationPolicy != kubeletconfig.HardReservationMemoryReservationPolicy {
-		setMemoryMin(v1.PodQOSGuaranteed, 0)
-		setMemoryMin(v1.PodQOSBurstable, 0)
+		setUnified(v1.PodQOSGuaranteed, Cgroup2MemoryMin, 0)
+		setUnified(v1.PodQOSBurstable, Cgroup2MemoryLow, 0)
+		kubeletmetrics.MemoryQoSProtectedBytesTotal.Set(0)
+		// NOTE: this writes memory.min=0 and memory.low=0 per pod every
+		// periodic cycle (~1 min). Cost is negligible since
+		// writing 0 to an already-0 cgroup value is a kernel no-op.
+		m.reconcilePodMemoryProtection(logger)
```
Comment (saschagrunert) [inline pkg/kubelet/cm/qos_container_manager_linux.go]: `reconcilePodMemoryProtection` iterates all active pods and calls `cgroupManager.Update()` for each one. This runs under the `qosContainerManagerImpl` mutex (held by `UpdateCgroups` at line 362) every periodic cycle (~1 min), even on nodes where `HardReservation` was never enabled (the default is `None`). Consider tracking whether reconciliation is actually needed (e.g., a flag set on policy transitions) and skipping it when there are no stale values to clear.

File: pkg/kubelet/cm/qos_container_manager_linux.go [hunk 3]
```diff
@@ -347,9 +387,9 @@ func (m *qosContainerManagerImpl) UpdateCgroups(logger logr.Logger) error {
 		return err
 	}
 
-	// update the qos level cgrougs v2 settings of memory qos if feature enabled
-	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.MemoryQoS) &&
-		libcontainercgroups.IsCgroup2UnifiedMode() {
+	// Update cgroup v2 memory.min settings. Called regardless of the MemoryQoS
+	// feature gate to clear stale values when the feature is disabled.
+	if libcontainercgroups.IsCgroup2UnifiedMode() {
```
Comment (saschagrunert) [inline pkg/kubelet/cm/qos_container_manager_linux.go:395]: Removing the `MemoryQoS` feature gate check means `setMemoryQoS` runs on every cgroup v2 node regardless of whether the feature is enabled. If `memoryReservationPolicy` is `HardReservation` while the gate is off, this will write non-zero `memory.min` values to QoS cgroups. The feature gate should remain the authoritative control. Consider passing the gate state into `setMemoryQoS` and forcing the zero-out path when `MemoryQoS` is disabled.

File: pkg/kubelet/metrics/metrics.go [hunk 4]
```diff
@@ -936,6 +939,17 @@ var (
 		},
 	)
 
+	// MemoryQoSProtectedBytesTotal tracks the total cgroup v2 memory.min across all pods on the node.
+	// Guaranteed pods use memory.min (hard), Burstable pods use memory.low (soft).
+	MemoryQoSProtectedBytesTotal = metrics.NewGauge(
+		&metrics.GaugeOpts{
+			Subsystem:      KubeletSubsystem,
+			Name:           MemoryQoSProtectedBytesTotalKey,
```
Comment (saschagrunert) [inline pkg/kubelet/metrics/metrics.go]: Per OpenMetrics/Prometheus naming conventions, the `_total` suffix is reserved for Counters. This is a Gauge. Consider renaming to e.g. `memory_qos_node_protected_bytes`.

File: test/e2e_node/memory_qos_test.go [hunk 5]
```diff
@@ -0,0 +1,909 @@
...
+					Namespace: f.Namespace.Name,
+				},
+				Spec: v1.PodSpec{
+					Containers: []v1.Container{
+						{
+							Name:  "mem-eater",
+							Image: "registry.k8s.io/e2e-test-images/busybox:1.36.1-1",
+							// Repeatedly allocate memory above memory.high (~121Mi) but under memory.max (128Mi)
+							// to trigger sustained throttling. Each dd allocates a 124Mi buffer.
+							Command: []string{"sh", "-c", "while true; do dd if=/dev/zero of=/dev/null bs=124M 2>/dev/null; done"},
```
Comment (saschagrunert) [inline test/e2e_node/memory_qos_test.go]: `dd bs=124M` allocates a 124Mi buffer with a 128Mi limit, leaving ~4Mi for the shell, dd binary, and runtime overhead. This is likely to cause OOM kills rather than sustained `memory.high` throttling, making the `oom_kill == 0` assertion at line 856 flaky. Consider reducing the buffer size (e.g., `bs=80M`) or increasing the memory limit to leave more headroom above `memory.high` but well below `memory.max`.

File: pkg/kubelet/cm/qos_container_manager_linux.go (hunk 3 above)
Comment (sohankunkerkar) [reply pkg/kubelet/cm/qos_container_manager_linux.go:395]: The gate check was removed intentionally for rollback. When MemoryQoS is disabled, stale `memory.(min/low)` values persist in cgroups because the cgroup manager only writes keys present in the Unified map. Without this path running, there's no cleanup. On nodes that never enabled HardReservation, the values are already 0, so writing 0 is a kernel no-op with negligible cost.

Comment (sohankunkerkar) [reply pkg/kubelet/cm/qos_container_manager_linux.go:395]: I can add a bool field `memoryProtectionEverEnabled` to the struct, set it to true when `HardReservation` is active, and only reconcile when that flag is true. It won't survive restarts though

Comment (saschagrunert) [reply pkg/kubelet/cm/qos_container_manager_linux.go:395]: The `memoryProtectionEverEnabled` flag can't solve the main scenario: cleanup after a restart with the feature disabled. Since writing 0 to a cgroup that's already 0 is a kernel no-op, I'm fine with dropping the gate check entirely. The cleanup path (lines 302-306) already does the right thing.

File: pkg/kubelet/cm/qos_container_manager_linux.go (hunk 2 above)
Comment (sohankunkerkar) [reply pkg/kubelet/cm/qos_container_manager_linux.go]: The gate check was removed intentionally for rollback. the kubelet has no persistent state tracking previous policy, so after a restart with the feature disabled, writing zeros is the only way to clean stale cgroup values. the cost is negligible since the kernel short-circuits writes of 0 to already-0 values

Comment (saschagrunert) [reply pkg/kubelet/cm/qos_container_manager_linux.go]: Same reasoning as the other thread, agreed. Pod-level values need the same cleanup after a restart.

**Review by saschagrunert — APPROVED** [review]
/lgtm

The KEP graduation criteria (Alpha v3) lists three per-container metrics (kubelet_memory_qos_memory_min_bytes, kubelet_memory_qos_memory_high_bytes, kubelet_memory_qos_throttle_events_total) that aren't implemented here. The PR adds node-level aggregates instead. The KEP also still describes memory.min for all QoS classes, but this PR implements tiered protection (memory.min for Guaranteed, memory.low for Burstable). Please update the KEP to reflect the current implementation.

**Comment by liggitt** [comment]
API enum rename lgtm, tag me once the kubelet impl packages have had `/lgtm` + `/approve` added and I'll tag the PR for merge

**Review by mrunalp — APPROVED** [review]
