### PR TITLE
Validate uids and gids for securitycontext when create pod

### LINKED ISSUE #16352: [storage_public_178]No validation info when create pod with invalid Supplemental Groups and FSGroup
```
Description of problem:
When create pod with invalid Supplemental Groups and FSGroup, should tip invalid value and create pod failed.

Version-Release number of selected component (if applicable):
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.364+fcd99461ff1420", GitCommit:"fcd99461ff142036fc70b24a0378b80b9ee0ee57", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.370+2d29d266e7f2c1-dirty", GitCommit:"2d29d266e7f2c16ae309d2ebca6acbb97898762e", GitTreeState:"dirty"}

How reproducible:
Always

Steps to Reproduce:
1.Create pod with invalid Supplemental Groups and 
[root@ip-172-18-1-44 kubernetes]# cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nfs-server
  labels:
    role: nfs-server
spec:
  containers:
    - name: nfs-server
      image: jsafrane/nfs-data
      ports:
        - name: nfs
          containerPort: 2049
      securityContext:
        privileged: false
  securityContext:
    supplementalGroups:
      - -123
    fsGroup: 2147483648
[root@ip-172-18-1-44 kubernetes]# kubectl create -f pod.yaml 
pod "nfs-server" created

2.Check the pod
[root@ip-172-18-1-44 kubernetes]# kubectl get pod
NAME         READY     STATUS               RESTARTS   AGE
nfs-server   0/1       ContainerCannotRun   0          5s
[root@ip-172-18-1-44 kubernetes]# kubectl describe pod/nfs-server
Name:                nfs-server
Namespace:            default
Image(s):            jsafrane/nfs-data
Node:                127.0.0.1/127.0.0.1
Start Time:            Tue, 27 Oct 2015 08:38:15 +0000
Labels:                role=nfs-server
Status:                Running
Reason:                
Message:            
IP:                172.17.0.95
Replication Controllers:    <none>
Containers:
  nfs-server:
    Container ID:    docker://bcf6257270654a05aa6598330451919a63bb325ce95a531bb0ddadc0f9633ee2
    Image:        jsafrane/nfs-data
    Image ID:        docker://c33ae16781aa35f163327995f83790c60f78d0cca9e1d73d766ac5300ea30a32
    QoS Tier:
      memory:        BestEffort
      cpu:        BestEffort
    State:        Terminated
      Reason:        ContainerCannotRun
      Message:        [8] System error: Uids and gids must be in range 0-2147483647
      Exit Code:    -1
      Started:        Tue, 27 Oct 2015 08:38:15 +0000
      Finished:        Tue, 27 Oct 2015 08:38:15 +0000
    Ready:        False
    Restart Count:    0
    Environment Variables:
Conditions:
  Type        Status
  Ready     False 
Volumes:
  default-token-df70w:
    Type:    Secret (a secret that should populate this volume)
    SecretName:    default-token-df70w
Events:
  FirstSeen    LastSeen    Count    From            SubobjectPath                Reason        Message
  ─────────    ────────    ─────    ────            ─────────────                ──────        ───────
  23s        23s        1    {scheduler }                            Scheduled    Successfully assigned nfs-server to 127.0.0.1
  23s        23s        1    {kubelet 127.0.0.1}    implicitly required container POD    Pulled        Container image "beta.gcr.io/google_containers/pause:2.0" already present on machine
  23s        23s        1    {kubelet 127.0.0.1}    implicitly required container POD    Created        Created with docker id 93e8ffb337c9
  23s        23s        1    {kubelet 127.0.0.1}    implicitly required container POD    Started        Started with docker id 93e8ffb337c9
  23s        23s        1    {kubelet 127.0.0.1}    spec.containers{nfs-server}        Created        Created with docker id bcf625727065
  23s        23s        1    {kubelet 127.0.0.1}    spec.containers{nfs-server}        Failed        Failed to start with docker id bcf625727065 with error: API error (500): Cannot start container bcf6257270654a05aa6598330451919a63bb325ce95a531bb0ddadc0f9633ee2: [8] System error: Uids and gids must be in range 0-2147483647

  23s    13s    2    {kubelet 127.0.0.1}    spec.containers{nfs-server}    Pulled    Container image "jsafrane/nfs-data" already present on machine


Actual results:
1.Create pod no tip invalid value.
2.The pod has some error "Uids and gids must be in range 0-2147483647"

Expected results:
1.When create pod should tip invalid value.

Additional info:
```

### PR DESCRIPTION
**Pull request by mdshuai**
fix [16352](https://github.com/kubernetes/kubernetes/issues/16352)

Validate fsGroup, runAsUser and supplementalGroups for PodSecurityContext.

### CODE REVIEW

**Comment by mdshuai** [comment]
@pmorie

**Comment by mdshuai** [comment]
I signed it!

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by ashcrow** [comment]
@mdshuai  looks like gofmt needs to be run. Here is the travis failure:

```
hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./pkg/api/validation/validation.go
./pkg/util/validation/validation.go
```

**Comment by pmorie** [comment]
@mdshuai Add a comment explaining the upper limit? Thanks for the PR.

File: pkg/api/validation/validation.go [hunk 1]
```diff
@@ -58,6 +58,8 @@ var DNS1123LabelErrorMsg string = fmt.Sprintf(`must be a DNS label (at most %d c
 var DNS952LabelErrorMsg string = fmt.Sprintf(`must be a DNS 952 label (at most %d characters, matching regex %s): e.g. "my-name"`, validation.DNS952LabelMaxLength, validation.DNS952LabelFmt)
 var pdPartitionErrorMsg string = IntervalErrorMsg(0, 255)
 var PortRangeErrorMsg string = IntervalErrorMsg(0, 65536)
+var GroupIdRangeErrorMsg string = IntervalErrorMsg(-1, 2147483648)
```
Comment (thockin) [inline pkg/api/validation/validation.go]: GIDs and UIDs are *usually* unsigned value, with some small number of negative values having meaning.

Maybe the limits should be `(math.MaxUint32 - 16)` or if we want to be not-exactly-compatible `math.MaxInt32`

File: pkg/util/validation/validation.go [hunk 2]
```diff
@@ -105,6 +105,16 @@ func IsValidPortNum(port int) bool {
 	return 0 < port && port < 65536
 }
 
+// IsValidGroupId tests that the argument is a valid gids. 
+func IsValidGroupId(gid int64) bool {
+	return 0 <= gid && gid < 2147483648
```
Comment (thockin) [inline pkg/util/validation/validation.go]: same not about values for this limit

File: pkg/api/validation/validation.go (hunk 1 above)
Comment (mdshuai) [inline pkg/api/validation/validation.go]: @thockin @pmorie I got this limit from the error tip when create pod with invalid value, 
"Failed to start with docker id bcf625727065 with error: API error (500): Cannot start container bcf6257270654a05aa6598330451919a63bb325ce95a531bb0ddadc0f9633ee2: [8] System error: Uids and gids must be in range 0-2147483647" refer the issue #16352  I linked.
They must be unsigned value and grater than 0 and less than 2147483648.  (can equal 0 and 2147483647, so I set the error tip to -1, 2147483648)

File: pkg/util/validation/validation.go (hunk 2 above)
Comment (mdshuai) [inline pkg/util/validation/validation.go]: same above

**Comment by mdshuai** [comment]
@ashcrow Thanks for your info, I fixed the invalid gofmt.

File: pkg/api/validation/validation.go [hunk 3]
```diff
@@ -1142,11 +1144,22 @@ func ValidatePodSpec(spec *api.PodSpec) errs.ValidationErrorList {
 // ValidatePodSecurityContext test that the specified PodSecurityContext has valid data.
 func ValidatePodSecurityContext(securityContext *api.PodSecurityContext, spec *api.PodSpec) errs.ValidationErrorList {
 	allErrs := errs.ValidationErrorList{}
-
 	if securityContext != nil {
 		allErrs = append(allErrs, validateHostNetwork(securityContext.HostNetwork, spec.Containers).Prefix("hostNetwork")...)
 	}
-
+	if !validation.IsValidGroupId(*(securityContext.FSGroup)) {
```
Comment (pweil-) [inline pkg/api/validation/validation.go]: RunAsUser and FSGroup are both pointers so we should be doing a nil check to avoid a nil pointer dereference.

We should also add this check to the SecurityContext (container) validation if not already done for consistency.

File: pkg/api/validation/validation.go (hunk 1 above)
Comment (swagiaal) [inline pkg/api/validation/validation.go]: > : Uids and gids must be in range 0-2147483647" refer the issue

@mdshuai that message comes from lib container, but I suppose the check is valid as long as libcontainer has that restriction. Perhaps add a comment to clarify that though. If you want you can file an issue against libcontainer and refer to it.

File: pkg/api/validation/validation.go [hunk 4]
```diff
@@ -1142,11 +1144,22 @@ func ValidatePodSpec(spec *api.PodSpec) errs.ValidationErrorList {
...
+	}
+	if !validation.IsValidUserId(*(securityContext.RunAsUser)) {
+		allErrs = append(allErrs, errs.NewFieldInvalid("runAsUser", *(securityContext.RunAsUser), UserIdRangeErrorMsg))
+	}
+	for i, gid := range securityContext.SupplementalGroups {
+		pErrs := errs.ValidationErrorList{}
+		if !validation.IsValidGroupId(gid) {
+			pErrs = append(pErrs, errs.NewFieldInvalid("supplementalGroups", gid, GroupIdRangeErrorMsg))
+		}
+		allErrs = append(allErrs, pErrs.PrefixIndex(i)...)
```
Comment (swagiaal) [inline pkg/api/validation/validation.go]: Hmm.. why are you adding to pErrs list then appending to allErrs ?

File: pkg/api/validation/validation.go (hunk 1 above)
Comment (mdshuai) [inline pkg/api/validation/validation.go]: @swagiaal yes. The maxId restriction in libcontainer  is 1<<31 - 1  https://github.com/opencontainers/runc/blob/master/libcontainer/user/user.go#L14

Comment (thockin) [inline pkg/api/validation/validation.go]: properly spelled as math.MaxInt32, please

Comment (thockin) [inline pkg/api/validation/validation.go]: Actually, let's do this:

// TODO: once we have a type for UID/GID we should make these that type.
const minUserID = 0
const maxUserID = math.MaxInt32
const maxGroupID = 0
const maxGroupID = math.MaxInt32

File: pkg/util/validation/validation.go [hunk 5]
```diff
@@ -105,6 +105,16 @@ func IsValidPortNum(port int) bool {
 	return 0 < port && port < 65536
 }
 
+// IsValidGroupId tests that the argument is a valid gids.
+func IsValidGroupId(gid int64) bool {
```
Comment (thockin) [inline pkg/util/validation/validation.go]: We have some incompat going on.  UNIXes generally leave room for -1 and -2 UIDs to mean something, but they usually define uid_t as unsigned. If we're treating UID as signed just because Docker does - is that kosher?  It's probably not a huge issue, but it seems a bit off.

**Comment by mdshuai** [comment]
@thockin @pweil- @swagiaal Thanks for your comment, I have updated the PR, help review again. thanks.

**Comment by mdshuai** [comment]
@pmorie @swagiaal Any feedback about this ? This should be finish in this sprint. thanks.

**Comment by swagiaal** [comment]
Regarding the signed vs unsigned issue I think it is okay to treat uid as signed during the validation because if docker will eventually reject your container you might as well get validation upfront. To make it kosher I would suggest @mdshuai add a note explaining the limitation. Extra points for filing an issue against runc requesting uid be treated as uint32 (better yet int64) and referencing the issue in the comment.

@thockin @mdshuai

**Comment by mdshuai** [comment]
This pr have some problem, will fix it soon

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

File: pkg/api/validation/validation.go [hunk 6]
```diff
@@ -58,6 +59,7 @@ var DNS1123LabelErrorMsg string = fmt.Sprintf(`must be a DNS label (at most %d c
 var DNS952LabelErrorMsg string = fmt.Sprintf(`must be a DNS 952 label (at most %d characters, matching regex %s): e.g. "my-name"`, validation.DNS952LabelMaxLength, validation.DNS952LabelFmt)
 var pdPartitionErrorMsg string = IntervalErrorMsg(0, 255)
 var PortRangeErrorMsg string = IntervalErrorMsg(0, 65536)
+var IdRangeErrorMsg string = fmt.Sprintf(`Uids and gids must be in range %d-%d`, 0, math.MaxInt32)
```
Comment (pmorie) [inline pkg/api/validation/validation.go]: `UIDs and GIDs`

File: pkg/api/validation/validation.go [hunk 7]
```diff
@@ -1143,11 +1143,31 @@ func ValidatePodSpec(spec *api.PodSpec) errs.ValidationErrorList {
...
-
 	if securityContext != nil {
-		allErrs = append(allErrs, validateHostNetwork(securityContext.HostNetwork, spec.Containers).Prefix("hostNetwork")...)
+		if securityContext.HostNetwork && spec != nil {
+			if len(spec.Containers) > 0 {
+				allErrs = append(allErrs, validateHostNetwork(spec.Containers).Prefix("hostNetwork")...)
+			}
+		}
+		if securityContext.FSGroup != nil {
+			if !validation.IsValidGroupId(*(securityContext.FSGroup)) {
```
Comment (pmorie) [inline pkg/api/validation/validation.go]: How about collapsing these two if statements into:

```go
if securityContext.FSGroup != nil &&
    !validation.IsValidGroupId(*securityContext.FSGroup) {
  // do stuff
}
```

File: pkg/api/validation/validation.go [hunk 8]
```diff
@@ -1143,11 +1143,31 @@ func ValidatePodSpec(spec *api.PodSpec) errs.ValidationErrorList {
...
+				allErrs = append(allErrs, errs.NewFieldInvalid("fsGroup", *(securityContext.FSGroup), IdRangeErrorMsg))
+			}
+		}
+		if securityContext.RunAsUser != nil {
+			if !validation.IsValidUserId(*(securityContext.RunAsUser)) {
```
Comment (pmorie) [inline pkg/api/validation/validation.go]: Same thing here, collapse these if statements into a single one as above.

File: pkg/api/validation/validation.go [hunk 9]
```diff
@@ -1143,11 +1143,31 @@ func ValidatePodSpec(spec *api.PodSpec) errs.ValidationErrorList {
...
+				allErrs = append(allErrs, errs.NewFieldInvalid("runAsUser", *(securityContext.RunAsUser), IdRangeErrorMsg))
+			}
+		}
+		if len(securityContext.SupplementalGroups) > 0 {
```
Comment (pmorie) [inline pkg/api/validation/validation.go]: no need to wrap this in an if statement, just range over the array.

**Comment by mdshuai** [comment]
@pmorie thanks your comment, update the pr as your comment.

**Comment by pmorie** [comment]
@mdshuai fyi: #17353

File: pkg/api/validation/validation.go [hunk 10]
```diff
@@ -58,6 +59,7 @@ var DNS1123LabelErrorMsg string = fmt.Sprintf(`must be a DNS label (at most %d c
 var DNS952LabelErrorMsg string = fmt.Sprintf(`must be a DNS 952 label (at most %d characters, matching regex %s): e.g. "my-name"`, validation.DNS952LabelMaxLength, validation.DNS952LabelFmt)
 var pdPartitionErrorMsg string = IntervalErrorMsg(0, 255)
 var PortRangeErrorMsg string = IntervalErrorMsg(0, 65536)
+var IdRangeErrorMsg string = fmt.Sprintf(`UIDs and GIDs must be in range %d-%d`, 0, math.MaxInt32)
```
Comment (thockin) [inline pkg/api/validation/validation.go]: Why is this different than IntervalError(0, math.MaxInt32) ?  That function was added so we get consistent errors.

File: pkg/api/validation/validation.go [hunk 11]
```diff
@@ -1074,14 +1076,12 @@ func validateDNSPolicy(dnsPolicy *api.DNSPolicy) errs.ValidationErrorList {
...
-func validateHostNetwork(hostNetwork bool, containers []api.Container) errs.ValidationErrorList {
+func validateHostNetwork(containers []api.Container) errs.ValidationErrorList {
 	allErrors := errs.ValidationErrorList{}
-	if hostNetwork {
-		for _, container := range containers {
-			for _, port := range container.Ports {
-				if port.HostPort != port.ContainerPort {
-					allErrors = append(allErrors, errs.NewFieldInvalid("containerPort", port.ContainerPort, "containerPort must match hostPort if hostNetwork is set to true"))
-				}
+	for _, container := range containers {
```
Comment (thockin) [inline pkg/api/validation/validation.go]: I like this change, but it is unrelated,  Maybe it can be broken to a different PR?

File: pkg/api/validation/validation.go (hunk 10 above)
Comment (mdshuai) [inline pkg/api/validation/validation.go]: IntervalErrorMsg(0, math.MaxInt32), "must be greater than %d and less than %d" means can't equal 0 and math.MaxInt32. For uid and gid it can equal it. Would you like IntervalErrorMsg(-1, math.MaxInt32+1) ?

File: pkg/api/validation/validation.go (hunk 11 above)
Comment (mdshuai) [inline pkg/api/validation/validation.go]: I seprate this change to a single commit in this pr. would you like this change? if not. I will change it in a different PR. This function only use by ValidatePodSecurityContext now.

**Comment by mdshuai** [comment]
@pmorie As your comment, I changed the type to int32.  @thockin I update the pr. help review again. thanks very much.

**Comment by pmorie** [comment]
@mdshuai this needs rebase -- do you have bandwidth to get to this?  If not, I will probably need to open my own PR for this.

**Comment by mdshuai** [comment]
@pmorie rebase the pr, help to review. thanks.

**Comment by mdshuai** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot unit test this

**Comment by pmorie** [comment]
@mdshuai Please add unit tests for the new validations.

**Comment by mdshuai** [comment]
@pmorie add unit test, help review.

@k8s-bot unit test this

**Comment by mdshuai** [comment]
@k8s-bot test this

**Comment by ncdc** [comment]
@k8s-bot test this

**Comment by eparis** [comment]
@k8s-bot test this

File: pkg/api/validation/validation.go [hunk 12]
```diff
@@ -58,6 +59,7 @@ var DNS1123LabelErrorMsg string = fmt.Sprintf(`must be a DNS label (at most %d c
 var DNS952LabelErrorMsg string = fmt.Sprintf(`must be a DNS 952 label (at most %d characters, matching regex %s): e.g. "my-name"`, validation.DNS952LabelMaxLength, validation.DNS952LabelFmt)
 var pdPartitionErrorMsg string = InclusiveRangeErrorMsg(1, 255)
 var PortRangeErrorMsg string = InclusiveRangeErrorMsg(1, 65535)
+var IdRangeErrorMsg string = fmt.Sprintf(`UIDs and GIDs must be in range %d-%d`, 0, math.MaxInt32)
```
Comment (thockin) [inline pkg/api/validation/validation.go]: for consistency this should just be `InclusiveRangeErrorMsg(0, math.MaxInt32)`

File: pkg/api/validation/validation.go [hunk 13]
```diff
@@ -1309,8 +1311,21 @@ func ValidatePodSecurityContext(securityContext *api.PodSecurityContext, spec *a
 
 	if securityContext != nil {
 		allErrs = append(allErrs, validateHostNetwork(securityContext.HostNetwork, spec.Containers, specPath.Child("containers"))...)
+		if securityContext.FSGroup != nil &&
+			!validation.IsValidGroupId(int32(*securityContext.FSGroup)) {
```
Comment (thockin) [inline pkg/api/validation/validation.go]: what's worse - casting to int32 here or receiving int64?  I feel like receiving int64 is less ugly.

**Comment by mdshuai** [comment]
@thockin update the pr as your comment. help review again. thanks.

**Comment by mdshuai** [comment]
@k8s-bot test this

File: pkg/api/validation/validation.go [hunk 14]
```diff
@@ -1309,6 +1311,20 @@ func ValidatePodSecurityContext(securityContext *api.PodSecurityContext, spec *a
 
 	if securityContext != nil {
 		allErrs = append(allErrs, validateHostNetwork(securityContext.HostNetwork, spec.Containers, specPath.Child("containers"))...)
+		if securityContext.FSGroup != nil &&
+			!validation.IsValidGroupId(*securityContext.FSGroup) {
```
Comment (thockin) [inline pkg/api/validation/validation.go]: nit: the linewrap here hurts readability

File: pkg/api/validation/validation.go [hunk 15]
```diff
@@ -1309,6 +1311,20 @@ func ValidatePodSecurityContext(securityContext *api.PodSecurityContext, spec *a
...
+			allErrs = append(allErrs, field.Invalid(fldPath.Child("fsGroup"), *(securityContext.FSGroup), IdRangeErrorMsg))
+		}
+		if securityContext.RunAsUser != nil &&
+			!validation.IsValidUserId(*securityContext.RunAsUser) {
```
Comment (thockin) [inline pkg/api/validation/validation.go]: same

**Comment by thockin** [comment]
LGTM, just a formatting nit

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by mdshuai** [comment]
@thockin  Updated the formatting nit

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
@k8s-bot test this
