### PR TITLE
Use ioutil.TempDir for temporary dir creation

### LINKED ISSUE #73689: Kubernetes unit tests failing due to build failure
**What happened**:
make test is failing due to  build failure

**What you expected to happen**:
make test should be successful

**How to reproduce it (as minimally and precisely as possible)**:
clone kubenetes git and run make test
**Anything else we need to know?**:

**Environment**:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `Linux ubuntu18.04-icp-node-4 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

GO Version:

```go version go1.11.1 linux/amd64```

Other:

```
root@ubuntu18:/go/src/k8s.io/kubernetes# make test --trace
Makefile:523: target 'generated_files' does not exist
make -f Makefile.generated_files generated_files CALLED_FROM_MAIN_MAKEFILE=1
Makefile.generated_files:63: update target '.make/go-pkgdeps.mk' due to: FORCE
if [[ "" == 1 ]]; then          \
    echo "DBG: calculating Go dependencies";  \
fi
hack/run-in-gopath.sh go install ./hack/make-rules/helpers/go2make
hack/run-in-gopath.sh go2make                     \
    k8s.io/kubernetes/...                         \
    --prune  k8s.io/kubernetes/staging            \
    --prune  k8s.io/kubernetes/vendor             \
    k8s.io/kubernetes/vendor/k8s.io/...           \
    github.com/jteeuwen/go-bindata/go-bindata/... \
    > .make/go-pkgdeps.mk.tmp
if ! cmp -s .make/go-pkgdeps.mk.tmp .make/go-pkgdeps.mk; then                       \
    if [[ "" == 1 ]]; then          \
        echo "DBG: go-pkgdeps.mk changed";   \
    fi;                                           \
    cat .make/go-pkgdeps.mk.tmp > .make/go-pkgdeps.mk;                              \
fi
rm -f .make/go-pkgdeps.mk.tmp
Makefile.generated_files:152: update target 'gen_deepcopy' due to: _output/bin/deepcopy-gen .make/_output/bin/deepcopy-gen.todo
if [[ -s .make/_output/bin/deepcopy-gen.todo ]]; then                 \
    pkgs=$(cat .make/_output/bin/deepcopy-gen.todo | paste -sd, -);  \
    if [[ "" == 1 ]]; then                           \
        echo "DBG: running _output/bin/deepcopy-gen for $pkgs";            \
    fi;                                                            \
    ./hack/run-in-gopath.sh _output/bin/deepcopy-gen                        \
        --v 1                                        \
        --logtostderr                                              \
        -i "$pkgs"                                                \
        --bounding-dirs k8s.io/kubernetes,"k8s.io/api"               \
        -O zz_generated.deepcopy                                    \
        "$@";                                                     \
fi                                                                 \

Makefile.generated_files:248: update target 'gen_defaulter' due to: _output/bin/defaulter-gen .make/_output/bin/defaulter-gen.todo
if [[ -s .make/_output/bin/defaulter-gen.todo ]]; then                 \
    pkgs=$(cat .make/_output/bin/defaulter-gen.todo | paste -sd, -);  \
    if [[ "" == 1 ]]; then                            \
        echo "DBG: running _output/bin/defaulter-gen for $pkgs";            \
    fi;                                                             \
    ./hack/run-in-gopath.sh _output/bin/defaulter-gen                        \
        --v 1                                         \
        --logtostderr                                               \
        -i "$pkgs"                                                 \
        --extra-peer-dirs $(echo k8s.io/kubernetes/cmd/cloud-controller-manager/app/apis/config/v1alpha1 k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3 k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1 k8s.io/kubernetes/pkg/apis/abac/v1beta1 k8s.io/kubernetes/pkg/apis/admission/v1beta1 k8s.io/kubernetes/pkg/apis/admissionregistration/v1beta1 k8s.io/kubernetes/pkg/apis/apps/v1 k8s.io/kubernetes/pkg/apis/apps/v1beta1 k8s.io/kubernetes/pkg/apis/apps/v1beta2 k8s.io/kubernetes/pkg/apis/auditregistration/v1alpha1 k8s.io/kubernetes/pkg/apis/authentication/v1 k8s.io/kubernetes/pkg/apis/authentication/v1beta1 k8s.io/kubernetes/pkg/apis/authorization/v1 k8s.io/kubernetes/pkg/apis/authorization/v1beta1 k8s.io/kubernetes/pkg/apis/autoscaling/v1 k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1 k8s.io/kubernetes/pkg/apis/autoscaling/v2beta2 k8s.io/kubernetes/pkg/apis/batch/v1 k8s.io/kubernetes/pkg/apis/batch/v1beta1 k8s.io/kubernetes/pkg/apis/batch/v2alpha1 k8s.io/kubernetes/pkg/apis/certificates/v1beta1 k8s.io/kubernetes/pkg/apis/coordination/v1 k8s.io/kubernetes/pkg/apis/coordination/v1beta1 k8s.io/kubernetes/pkg/apis/core/v1 k8s.io/kubernetes/pkg/apis/events/v1beta1 k8s.io/kubernetes/pkg/apis/extensions/v1beta1 k8s.io/kubernetes/pkg/apis/imagepolicy/v1alpha1 k8s.io/kubernetes/pkg/apis/networking/v1 k8s.io/kubernetes/pkg/apis/policy/v1beta1 k8s.io/kubernetes/pkg/apis/rbac/v1 k8s.io/kubernetes/pkg/apis/rbac/v1alpha1 k8s.io/kubernetes/pkg/apis/rbac/v1beta1 k8s.io/kubernetes/pkg/apis/scheduling/v1alpha1 k8s.io/kubernetes/pkg/apis/scheduling/v1beta1 k8s.io/kubernetes/pkg/apis/settings/v1alpha1 k8s.io/kubernetes/pkg/apis/storage/v1 k8s.io/kubernetes/pkg/apis/storage/v1alpha1 k8s.io/kubernetes/pkg/apis/storage/v1beta1 k8s.io/kubernetes/pkg/controller/apis/config/v1alpha1 k8s.io/kubernetes/pkg/kubelet/apis/config/v1beta1 k8s.io/kubernetes/pkg/proxy/apis/config/v1alpha1 k8s.io/kubernetes/pkg/scheduler/apis/config/v1alpha1 k8s.io/kubernetes/plugin/pkg/admission/eventratelimit/apis/eventratelimit/v1alpha1 k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/apis/podtolerationrestriction/v1alpha1 k8s.io/kubernetes/plugin/pkg/admission/resourcequota/apis/resourcequota/v1alpha1 k8s.io/kubernetes/plugin/pkg/admission/resourcequota/apis/resourcequota/v1beta1 k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1beta1 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/testapigroup/v1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/config/apis/webhookadmission/v1alpha1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1alpha1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1beta1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/config/v1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example/v1 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example2/v1 k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1alpha1 k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/apis/clientauthentication/v1beta1 k8s.io/kubernetes/vendor/k8s.io/code-generator/_examples/MixedCase/apis/example/v1 k8s.io/kubernetes/vendor/k8s.io/code-generator/_examples/apiserver/apis/example/v1 k8s.io/kubernetes/vendor/k8s.io/code-generator/_examples/apiserver/apis/example2/v1 k8s.io/kubernetes/vendor/k8s.io/code-generator/_examples/crd/apis/example/v1 k8s.io/kubernetes/vendor/k8s.io/code-generator/_examples/crd/apis/example2/v1 k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1 k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apis/wardle/v1beta1 | sed 's/ /,/g') \
        -O zz_generated.defaults                                    \
        "$@";                                                      \
fi
Makefile.generated_files:352: update target 'gen_conversion' due to: _output/bin/conversion-gen .make/_output/bin/conversion-gen.todo
if [[ -s .make/_output/bin/conversion-gen.todo ]]; then                 \
    pkgs=$(cat .make/_output/bin/conversion-gen.todo | paste -sd, -);  \
    if [[ "" == 1 ]]; then                             \
        echo "DBG: running _output/bin/conversion-gen for $pkgs";            \
    fi;                                                              \
    ./hack/run-in-gopath.sh _output/bin/conversion-gen                        \
        --extra-peer-dirs k8s.io/kubernetes/pkg/apis/core,k8s.io/kubernetes/pkg/apis/core/v1,k8s.io/api/core/v1              \
        --v 1                                          \
        --logtostderr                                                \
        -i "$pkgs"                                                  \
        -O zz_generated.conversion                                    \
        "$@";                                                       \
fi
Makefile.generated_files:500: update target 'gen_bindata' due to: _output/bin/go-bindata FORCE
./hack/run-in-gopath.sh hack/generate-bindata.sh
Makefile:184: update target 'test' due to: generated_files
hack/make-rules/test.sh
Running tests for APIVersion: v1,admissionregistration.k8s.io/v1beta1,admission.k8s.io/v1beta1,apps/v1,apps/v1beta1,apps/v1beta2,auditregistration.k8s.io/v1alpha1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,autoscaling/v2beta2,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,coordination.k8s.io/v1beta1,coordination.k8s.io/v1,extensions/v1beta1,events.k8s.io/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,scheduling.k8s.io/v1beta1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,storage.k8s.io/v1alpha1,
+++ [0204 07:05:17] Running tests without code coverage
ok  	k8s.io/kubernetes/cluster/gce/cos	(cached)
ok  	k8s.io/kubernetes/cluster/gce/custom	(cached)
ok  	k8s.io/kubernetes/cluster/gce/gci	(cached)
ok  	k8s.io/kubernetes/cluster/gce/ubuntu	(cached)
ok  	k8s.io/kubernetes/cluster/images/etcd/migrate	(cached)
ok  	k8s.io/kubernetes/cmd/cloud-controller-manager/app/apis/config/v1alpha1	(cached)
ok  	k8s.io/kubernetes/cmd/cloud-controller-manager/app/options	(cached)
ok  	k8s.io/kubernetes/cmd/controller-manager/app	(cached)
ok  	k8s.io/kubernetes/cmd/controller-manager/app/options	(cached)
ok  	k8s.io/kubernetes/cmd/genkubedocs	(cached)
ok  	k8s.io/kubernetes/cmd/genutils	(cached)
go build k8s.io/kubernetes/cmd/kube-scheduler/app/options.test: open /tmp/go-build138919994/b2000/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.test: open /tmp/go-build138919994/b2003/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/fuzzer.test: open /tmp/go-build138919994/b2006/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3.test: open /tmp/go-build138919994/b2013/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1.test: open /tmp/go-build138919994/b2016/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.test: open /tmp/go-build138919994/b2019/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd.test: open /tmp/go-build138919994/b2022/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd/alpha.test: open /tmp/go-build138919994/b2028/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases.test: open /tmp/go-build138919994/b2033/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.test: open /tmp/go-build138919994/b2036/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.test: open /tmp/go-build138919994/b2039/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/cmd/util.test: open /tmp/go-build138919994/b2042/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs.test: open /tmp/go-build138919994/b2045/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/constants.test: open /tmp/go-build138919994/b2048/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/discovery.test: open /tmp/go-build138919994/b2051/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/discovery/token.test: open /tmp/go-build138919994/b2054/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/features.test: open /tmp/go-build138919994/b2057/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/images.test: open /tmp/go-build138919994/b2060/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.test: open /tmp/go-build138919994/b2063/importcfg: no such file or directory
open /tmp/go-build138919994/b1994/options.test: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/proxy.test: open /tmp/go-build138919994/b2066/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo.test: open /tmp/go-build138919994/b2069/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/certs.test: open /tmp/go-build138919994/b2072/importcfg: no such file or directory
open /tmp/go-build138919994/b1988/options.test: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kube-apiserver/app/options [build failed]
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.test: open /tmp/go-build138919994/b2075/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/controlplane.test: open /tmp/go-build138919994/b2078/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd.test: open /tmp/go-build138919994/b2081/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.test: open /tmp/go-build138919994/b2084/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/kubelet.test: open /tmp/go-build138919994/b2087/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/markcontrolplane.test: open /tmp/go-build138919994/b2090/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting.test: open /tmp/go-build138919994/b2093/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.test: open /tmp/go-build138919994/b2096/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/phases/uploadconfig.test: open /tmp/go-build138919994/b2099/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/preflight.test: open /tmp/go-build138919994/b2102/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util.test: open /tmp/go-build138919994/b2105/importcfg: no such file or directory
open /tmp/go-build138919994/b1991/app.test: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kube-controller-manager/app [build failed]
FAIL	k8s.io/kubernetes/cmd/kube-controller-manager/app/options [build failed]
E0204 07:05:35.706500   20506 server_others.go:320] can't determine whether to use iptables proxy, using userspace proxier: oops!
E0204 07:05:35.708949   20506 server_others.go:320] can't determine whether to use iptables proxy, using userspace proxier: error
E0204 07:05:35.710082   20506 server_others.go:320] can't determine whether to use iptables proxy, using userspace proxier: oops!
E0204 07:05:35.711186   20506 server_others.go:320] can't determine whether to use iptables proxy, using userspace proxier: error
E0204 07:05:35.721662   20506 server_others.go:305] can't determine whether to use ipvs proxy, error: ipset version: 0.0 is less than min required version: 6.0
E0204 07:05:35.725672   20506 ipset.go:172] vstring (a.b.c) is not a valid version string: could not parse "a.b.c" as version
E0204 07:05:35.725698   20506 server_others.go:305] can't determine whether to use ipvs proxy, error: ipset version: a.b.c is less than min required version: 6.0
E0204 07:05:35.727070   20506 server_others.go:305] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_sh ip_vs ip_vs_rr ip_vs_wrr]
E0204 07:05:35.729634   20506 server_others.go:305] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs_rr ip_vs_wrr ip_vs_sh ip_vs]
E0204 07:05:35.733640   20506 server_others.go:305] can't determine whether to use ipvs proxy, error: ipset version: 0.0 is less than min required version: 6.0
E0204 07:05:35.733670   20506 server_others.go:320] can't determine whether to use iptables proxy, using userspace proxier: error
--- FAIL: TestConfigChange (0.17s)
    server_test.go:495: unexpected error when setting up environment: unexpected error when creating temp file: open /tmp/kube-proxy-config-234555039: no such file or directory
FAIL
FAIL	k8s.io/kubernetes/cmd/kube-proxy/app	0.324s
FAIL	k8s.io/kubernetes/cmd/kube-scheduler/app/options [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/fuzzer [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3 [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/alpha [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/cmd/util [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/constants [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/discovery [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/discovery/token [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/features [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/images [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/proxy [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/certs [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/controlplane [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/kubelet [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/markcontrolplane [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/selfhosting [build failed]
go build k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient.test: open /tmp/go-build138919994/b2108/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/audit.test: open /tmp/go-build138919994/b2111/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/config.test: open /tmp/go-build138919994/b2114/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/uploadconfig [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/preflight [build failed]
go build k8s.io/kubernetes/cmd/kubeadm/app/util/config/strict.test: open /tmp/go-build138919994/b2117/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.test: open /tmp/go-build138919994/b2120/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util [build failed]
go build k8s.io/kubernetes/cmd/kubeadm/app/util/kubeconfig.test: open /tmp/go-build138919994/b2123/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/apiclient [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/audit [build failed]
go build k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil.test: open /tmp/go-build138919994/b2126/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/pubkeypin.test: open /tmp/go-build138919994/b2129/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/runtime.test: open /tmp/go-build138919994/b2132/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/staticpod.test: open /tmp/go-build138919994/b2135/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubeadm/app/util/system.test: open /tmp/go-build138919994/b2138/importcfg: no such file or directory
go build k8s.io/kubernetes/cmd/kubelet/app.test: open /tmp/go-build138919994/b2141/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/config [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/config/strict [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/etcd [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/kubeconfig [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/pkiutil [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/pubkeypin [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/runtime [build failed]
go build k8s.io/kubernetes/cmd/kubelet/app/options.test: open /tmp/go-build138919994/b2144/importcfg: no such file or directory
go build k8s.io/kubernetes/hack.test: open /tmp/go-build138919994/b2147/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/staticpod [build failed]
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/util/system [build failed]
go build k8s.io/kubernetes/hack/make-rules/helpers/go2make.test: open /tmp/go-build138919994/b2151/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/endpoints.test: open /tmp/go-build138919994/b2154/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/persistentvolume.test: open /tmp/go-build138919994/b2157/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/persistentvolumeclaim.test: open /tmp/go-build138919994/b2161/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/pod.test: open /tmp/go-build138919994/b2164/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/podsecuritypolicy.test: open /tmp/go-build138919994/b2167/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/ref.test: open /tmp/go-build138919994/b2170/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/resource.test: open /tmp/go-build138919994/b2174/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/resourcequota.test: open /tmp/go-build138919994/b2177/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/service.test: open /tmp/go-build138919994/b2180/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/testapi.test: open /tmp/go-build138919994/b2183/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/testing.test: open /tmp/go-build138919994/b2186/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/v1/endpoints.test: open /tmp/go-build138919994/b2203/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/v1/persistentvolume.test: open /tmp/go-build138919994/b2206/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/v1/pod.test: open /tmp/go-build138919994/b2209/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/api/v1/resource.test: open /tmp/go-build138919994/b2212/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/cmd/kubelet/app [build failed]
FAIL	k8s.io/kubernetes/cmd/kubelet/app/options [build failed]
FAIL	k8s.io/kubernetes/hack [build failed]
FAIL	k8s.io/kubernetes/hack/make-rules/helpers/go2make [build failed]
FAIL	k8s.io/kubernetes/pkg/api/endpoints [build failed]
FAIL	k8s.io/kubernetes/pkg/api/persistentvolume [build failed]
FAIL	k8s.io/kubernetes/pkg/api/persistentvolumeclaim [build failed]
FAIL	k8s.io/kubernetes/pkg/api/pod [build failed]
FAIL	k8s.io/kubernetes/pkg/api/podsecuritypolicy [build failed]
FAIL	k8s.io/kubernetes/pkg/api/ref [build failed]
FAIL	k8s.io/kubernetes/pkg/api/resource [build failed]
FAIL	k8s.io/kubernetes/pkg/api/resourcequota [build failed]
FAIL	k8s.io/kubernetes/pkg/api/service [build failed]
FAIL	k8s.io/kubernetes/pkg/api/testapi [build failed]
go build k8s.io/kubernetes/pkg/api/v1/service.test: open /tmp/go-build138919994/b2215/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/api/testing [build failed]
FAIL	k8s.io/kubernetes/pkg/api/v1/endpoints [build failed]
FAIL	k8s.io/kubernetes/pkg/api/v1/persistentvolume [build failed]
go build k8s.io/kubernetes/pkg/apis/abac/v0.test: open /tmp/go-build138919994/b2218/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/abac/v1beta1.test: open /tmp/go-build138919994/b2221/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/api/v1/pod [build failed]
go build k8s.io/kubernetes/pkg/apis/admissionregistration/validation.test: open /tmp/go-build138919994/b2224/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/apps/v1.test: open /tmp/go-build138919994/b2227/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/apps/v1beta1.test: open /tmp/go-build138919994/b2230/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/api/v1/resource [build failed]
FAIL	k8s.io/kubernetes/pkg/api/v1/service [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/abac/v0 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/abac/v1beta1 [build failed]
go build k8s.io/kubernetes/pkg/apis/apps/v1beta2.test: open /tmp/go-build138919994/b2233/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/admissionregistration/validation [build failed]
go build k8s.io/kubernetes/pkg/apis/apps/validation.test: open /tmp/go-build138919994/b2236/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/auditregistration/v1alpha1.test: open /tmp/go-build138919994/b2239/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/apps/v1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/apps/v1beta1 [build failed]
go build k8s.io/kubernetes/pkg/apis/auditregistration/validation.test: open /tmp/go-build138919994/b2242/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/authorization/validation.test: open /tmp/go-build138919994/b2245/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/apps/v1beta2 [build failed]
go build k8s.io/kubernetes/pkg/apis/autoscaling/v1.test: open /tmp/go-build138919994/b2248/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1.test: open /tmp/go-build138919994/b2251/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/apps/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/auditregistration/v1alpha1 [build failed]
go build k8s.io/kubernetes/pkg/apis/autoscaling/validation.test: open /tmp/go-build138919994/b2256/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/auditregistration/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/authorization/validation [build failed]
go build k8s.io/kubernetes/pkg/apis/batch/v1.test: open /tmp/go-build138919994/b2259/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/autoscaling/v1 [build failed]
go build k8s.io/kubernetes/pkg/apis/batch/v1beta1.test: open /tmp/go-build138919994/b2262/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/batch/v2alpha1.test: open /tmp/go-build138919994/b2265/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/batch/validation.test: open /tmp/go-build138919994/b2268/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/coordination/validation.test: open /tmp/go-build138919994/b2271/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core.test: open /tmp/go-build138919994/b2274/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core/helper.test: open /tmp/go-build138919994/b2277/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core/install.test: open /tmp/go-build138919994/b2280/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core/pods.test: open /tmp/go-build138919994/b2283/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/autoscaling/v2beta1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/autoscaling/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/batch/v1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/batch/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/batch/v2alpha1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/batch/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/coordination/validation [build failed]
go build k8s.io/kubernetes/pkg/apis/core/v1.test: open /tmp/go-build138919994/b2286/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core/v1/helper.test: open /tmp/go-build138919994/b2289/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/core/v1/helper/qos.test: open /tmp/go-build138919994/b2292/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/core [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/core/helper [build failed]
go build k8s.io/kubernetes/pkg/apis/core/v1/validation.test: open /tmp/go-build138919994/b2295/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/core/install [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/core/pods [build failed]
go build k8s.io/kubernetes/pkg/apis/core/validation.test: open /tmp/go-build138919994/b2298/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/extensions/v1beta1.test: open /tmp/go-build138919994/b2301/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/extensions/validation.test: open /tmp/go-build138919994/b2304/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/networking/v1.test: open /tmp/go-build138919994/b2307/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/core/v1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/core/v1/helper [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/core/v1/helper/qos [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/core/v1/validation [build failed]
go build k8s.io/kubernetes/pkg/apis/networking/validation.test: open /tmp/go-build138919994/b2310/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/policy/validation.test: open /tmp/go-build138919994/b2313/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/rbac.test: open /tmp/go-build138919994/b2316/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/rbac/v1alpha1.test: open /tmp/go-build138919994/b2319/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/rbac/validation.test: open /tmp/go-build138919994/b2322/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/scheduling.test: open /tmp/go-build138919994/b2325/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/scheduling/validation.test: open /tmp/go-build138919994/b2328/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/settings/validation.test: open /tmp/go-build138919994/b2331/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/storage/util.test: open /tmp/go-build138919994/b2334/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/storage/v1.test: open /tmp/go-build138919994/b2337/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/storage/v1beta1.test: open /tmp/go-build138919994/b2340/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/apis/storage/validation.test: open /tmp/go-build138919994/b2343/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/auth/authorizer/abac.test: open /tmp/go-build138919994/b2346/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/auth/nodeidentifier.test: open /tmp/go-build138919994/b2349/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/capabilities.test: open /tmp/go-build138919994/b2352/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/apis/core/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/extensions/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/extensions/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/networking/v1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/networking/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/policy/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/rbac [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/rbac/v1alpha1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/rbac/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/scheduling [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/scheduling/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/settings/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/storage/util [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/storage/v1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/storage/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/pkg/apis/storage/validation [build failed]
go build k8s.io/kubernetes/pkg/client/tests.test: open /tmp/go-build138919994/b2355/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/cloudprovider/providers/azure.test: open /tmp/go-build138919994/b2384/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/auth/authorizer/abac [build failed]
FAIL	k8s.io/kubernetes/pkg/auth/nodeidentifier [build failed]
FAIL	k8s.io/kubernetes/pkg/capabilities [build failed]
go build k8s.io/kubernetes/pkg/cloudprovider/providers/cloudstack.test: open /tmp/go-build138919994/b2387/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/cloudprovider/providers/aws.test: open /tmp/go-build138919994/b2379/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/client/tests [build failed]
go build k8s.io/kubernetes/pkg/cloudprovider/providers/gce.test: open /tmp/go-build138919994/b2390/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/cloudprovider/providers/openstack.test: open /tmp/go-build138919994/b2393/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/cloudprovider/providers/ovirt.test: open /tmp/go-build138919994/b2396/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/aws [build failed]
go build k8s.io/kubernetes/pkg/cloudprovider/providers/photon.test: open /tmp/go-build138919994/b2399/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/azure [build failed]
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/cloudstack [build failed]
go build k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.test: open /tmp/go-build138919994/b2402/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib.test: open /tmp/go-build138919994/b2414/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller.test: open /tmp/go-build138919994/b2418/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/gce [build failed]
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/openstack [build failed]
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/ovirt [build failed]
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/photon [build failed]
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere [build failed]
go build k8s.io/kubernetes/pkg/controller/apis/config/scheme.test: open /tmp/go-build138919994/b2422/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/apis/config/v1alpha1.test: open /tmp/go-build138919994/b2426/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/bootstrap.test: open /tmp/go-build138919994/b2429/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/certificates.test: open /tmp/go-build138919994/b2432/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/certificates/approver.test: open /tmp/go-build138919994/b2435/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vclib [build failed]
FAIL	k8s.io/kubernetes/pkg/controller [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/apis/config/scheme [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/apis/config/v1alpha1 [build failed]
go build k8s.io/kubernetes/pkg/controller/certificates/cleaner.test: open /tmp/go-build138919994/b2438/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/certificates/rootcacertpublisher.test: open /tmp/go-build138919994/b2441/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/certificates/signer.test: open /tmp/go-build138919994/b2444/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/cloud.test: open /tmp/go-build138919994/b2447/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/bootstrap [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/certificates [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/certificates/approver [build failed]
go build k8s.io/kubernetes/pkg/controller/clusterroleaggregation.test: open /tmp/go-build138919994/b2451/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/certificates/cleaner [build failed]
go build k8s.io/kubernetes/pkg/controller/cronjob.test: open /tmp/go-build138919994/b2454/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/daemon.test: open /tmp/go-build138919994/b2457/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/certificates/rootcacertpublisher [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/certificates/signer [build failed]
go build k8s.io/kubernetes/pkg/controller/daemon/util.test: open /tmp/go-build138919994/b2460/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/deployment.test: open /tmp/go-build138919994/b2463/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/cloud [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/clusterroleaggregation [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/cronjob [build failed]
go build k8s.io/kubernetes/pkg/controller/deployment/util.test: open /tmp/go-build138919994/b2466/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/disruption.test: open /tmp/go-build138919994/b2469/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/endpoint.test: open /tmp/go-build138919994/b2472/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/garbagecollector.test: open /tmp/go-build138919994/b2475/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/daemon [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/daemon/util [build failed]
go build k8s.io/kubernetes/pkg/controller/history.test: open /tmp/go-build138919994/b2479/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/deployment [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/deployment/util [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/disruption [build failed]
go build k8s.io/kubernetes/pkg/controller/job.test: open /tmp/go-build138919994/b2482/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/endpoint [build failed]
go build k8s.io/kubernetes/pkg/controller/namespace/deletion.test: open /tmp/go-build138919994/b2485/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/nodeipam.test: open /tmp/go-build138919994/b2488/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/nodeipam/ipam.test: open /tmp/go-build138919994/b2491/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/nodeipam/ipam/cidrset.test: open /tmp/go-build138919994/b2495/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/garbagecollector [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/history [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/job [build failed]
go build k8s.io/kubernetes/pkg/controller/nodeipam/ipam/sync.test: open /tmp/go-build138919994/b2498/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/namespace/deletion [build failed]
go build k8s.io/kubernetes/pkg/controller/nodelifecycle.test: open /tmp/go-build138919994/b2501/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler.test: open /tmp/go-build138919994/b2504/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/nodeipam [build failed]
go build k8s.io/kubernetes/pkg/controller/podautoscaler.test: open /tmp/go-build138919994/b2507/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/nodeipam/ipam [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/nodeipam/ipam/cidrset [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/nodeipam/ipam/sync [build failed]
go build k8s.io/kubernetes/pkg/controller/podautoscaler/metrics.test: open /tmp/go-build138919994/b2518/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/podgc.test: open /tmp/go-build138919994/b2521/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/nodelifecycle [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler [build failed]
go build k8s.io/kubernetes/pkg/controller/replicaset.test: open /tmp/go-build138919994/b2524/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/replication.test: open /tmp/go-build138919994/b2527/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/resourcequota.test: open /tmp/go-build138919994/b2530/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/route.test: open /tmp/go-build138919994/b2533/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/service.test: open /tmp/go-build138919994/b2536/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/serviceaccount.test: open /tmp/go-build138919994/b2539/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/podautoscaler [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/podautoscaler/metrics [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/podgc [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/replicaset [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/replication [build failed]
go build k8s.io/kubernetes/pkg/controller/statefulset.test: open /tmp/go-build138919994/b2542/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/resourcequota [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/route [build failed]
go build k8s.io/kubernetes/pkg/controller/ttl.test: open /tmp/go-build138919994/b2545/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/ttlafterfinished.test: open /tmp/go-build138919994/b2548/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/service [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/serviceaccount [build failed]
go build k8s.io/kubernetes/pkg/controller/volume/attachdetach.test: open /tmp/go-build138919994/b2551/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache.test: open /tmp/go-build138919994/b2555/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/volume/attachdetach/metrics.test: open /tmp/go-build138919994/b2559/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/volume/attachdetach/populator.test: open /tmp/go-build138919994/b2562/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/statefulset [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/ttl [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/ttlafterfinished [build failed]
go build k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler.test: open /tmp/go-build138919994/b2565/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/volume/attachdetach [build failed]
go build k8s.io/kubernetes/pkg/controller/volume/expand/cache.test: open /tmp/go-build138919994/b2568/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/volume/attachdetach/cache [build failed]
go build k8s.io/kubernetes/pkg/controller/volume/persistentvolume.test: open /tmp/go-build138919994/b2571/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/volume/attachdetach/metrics [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/volume/attachdetach/populator [build failed]
go build k8s.io/kubernetes/pkg/controller/volume/pvcprotection.test: open /tmp/go-build138919994/b2574/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/controller/volume/pvprotection.test: open /tmp/go-build138919994/b2577/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/volume/attachdetach/reconciler [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/volume/expand/cache [build failed]
go build k8s.io/kubernetes/pkg/credentialprovider.test: open /tmp/go-build138919994/b2580/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/credentialprovider/aws.test: open /tmp/go-build138919994/b2583/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/credentialprovider/azure.test: open /tmp/go-build138919994/b2586/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/credentialprovider/gcp.test: open /tmp/go-build138919994/b2589/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/credentialprovider/rancher.test: open /tmp/go-build138919994/b2592/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/fieldpath.test: open /tmp/go-build138919994/b2595/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubeapiserver/admission.test: open /tmp/go-build138919994/b2598/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubeapiserver/authorizer/modes.test: open /tmp/go-build138919994/b2601/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubeapiserver/options.test: open /tmp/go-build138919994/b2604/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/controller/volume/persistentvolume [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/volume/pvcprotection [build failed]
FAIL	k8s.io/kubernetes/pkg/controller/volume/pvprotection [build failed]
FAIL	k8s.io/kubernetes/pkg/credentialprovider [build failed]
FAIL	k8s.io/kubernetes/pkg/credentialprovider/aws [build failed]
FAIL	k8s.io/kubernetes/pkg/credentialprovider/azure [build failed]
FAIL	k8s.io/kubernetes/pkg/credentialprovider/gcp [build failed]
FAIL	k8s.io/kubernetes/pkg/credentialprovider/rancher [build failed]
FAIL	k8s.io/kubernetes/pkg/fieldpath [build failed]
go build k8s.io/kubernetes/pkg/kubectl.test: open /tmp/go-build138919994/b2607/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/apply/parse.test: open /tmp/go-build138919994/b2637/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubeapiserver/admission [build failed]
FAIL	k8s.io/kubernetes/pkg/kubeapiserver/authorizer/modes [build failed]
go build k8s.io/kubernetes/pkg/kubectl/apply/strategy.test: open /tmp/go-build138919994/b2672/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/apps.test: open /tmp/go-build138919994/b2678/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubeapiserver/options [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd.test: open /tmp/go-build138919994/b2681/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/apply/parse [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/apply/strategy [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/apps [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/annotate.test: open /tmp/go-build138919994/b2755/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/apply.test: open /tmp/go-build138919994/b2760/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/attach.test: open /tmp/go-build138919994/b2764/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/auth.test: open /tmp/go-build138919994/b2767/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo.test: open /tmp/go-build138919994/b2770/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/annotate [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/config.test: open /tmp/go-build138919994/b2773/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/convert.test: open /tmp/go-build138919994/b2776/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/apply [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/attach [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/cp.test: open /tmp/go-build138919994/b2779/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/auth [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/clusterinfo [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/create.test: open /tmp/go-build138919994/b2782/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/delete.test: open /tmp/go-build138919994/b2785/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/config [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/convert [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/describe.test: open /tmp/go-build138919994/b2788/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/diff.test: open /tmp/go-build138919994/b2791/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/cp [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/drain.test: open /tmp/go-build138919994/b2794/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/exec.test: open /tmp/go-build138919994/b2800/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/create [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/delete [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/describe [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/edit.test: open /tmp/go-build138919994/b2797/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/expose.test: open /tmp/go-build138919994/b2803/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/diff [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/get.test: open /tmp/go-build138919994/b2806/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/label.test: open /tmp/go-build138919994/b2809/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/drain [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/edit [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/exec [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/logs.test: open /tmp/go-build138919994/b2812/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/patch.test: open /tmp/go-build138919994/b2815/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/expose [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/plugin.test: open /tmp/go-build138919994/b2818/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/portforward.test: open /tmp/go-build138919994/b2821/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/replace.test: open /tmp/go-build138919994/b2824/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.test: open /tmp/go-build138919994/b2827/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/get [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/label [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/logs [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/patch [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/plugin [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/rollout.test: open /tmp/go-build138919994/b2830/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/portforward [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/run.test: open /tmp/go-build138919994/b2833/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/scale.test: open /tmp/go-build138919994/b2836/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/set/env.test: open /tmp/go-build138919994/b2842/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/replace [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/rollout [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/set.test: open /tmp/go-build138919994/b2839/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/taint.test: open /tmp/go-build138919994/b2845/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/run [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/scale [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/top.test: open /tmp/go-build138919994/b2848/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/util.test: open /tmp/go-build138919994/b2851/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/util/editor.test: open /tmp/go-build138919994/b2855/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/set [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/set/env [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/taint [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi.test: open /tmp/go-build138919994/b2858/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi/validation.test: open /tmp/go-build138919994/b2861/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/top [build failed]
go build k8s.io/kubernetes/pkg/kubectl/cmd/wait.test: open /tmp/go-build138919994/b2864/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/describe/versioned.test: open /tmp/go-build138919994/b2867/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/generate.test: open /tmp/go-build138919994/b2873/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/util [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/util/editor [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/util/openapi/validation [build failed]
go build k8s.io/kubernetes/pkg/kubectl/explain.test: open /tmp/go-build138919994/b2870/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/generate/versioned.test: open /tmp/go-build138919994/b2876/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/polymorphichelpers.test: open /tmp/go-build138919994/b2879/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/wait [build failed]
go build k8s.io/kubernetes/pkg/kubectl/proxy.test: open /tmp/go-build138919994/b2882/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/scheme.test: open /tmp/go-build138919994/b2885/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/util.test: open /tmp/go-build138919994/b2888/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/describe/versioned [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/explain [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/generate [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/generate/versioned [build failed]
go build k8s.io/kubernetes/pkg/kubectl/util/event.test: open /tmp/go-build138919994/b2891/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/polymorphichelpers [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/proxy [build failed]
go build k8s.io/kubernetes/pkg/kubectl/util/hash.test: open /tmp/go-build138919994/b2894/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/scheme [build failed]
go build k8s.io/kubernetes/pkg/kubectl/util/i18n.test: open /tmp/go-build138919994/b2897/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubectl/util/slice.test: open /tmp/go-build138919994/b2900/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/util [build failed]
go build k8s.io/kubernetes/pkg/kubectl/util/term.test: open /tmp/go-build138919994/b2903/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/util/event [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/util/hash [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/util/i18n [build failed]
go build k8s.io/kubernetes/pkg/kubectl/validation.test: open /tmp/go-build138919994/b2906/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet.test: open /tmp/go-build138919994/b2909/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/util/slice [build failed]
go build k8s.io/kubernetes/pkg/kubelet/apis/config.test: open /tmp/go-build138919994/b2918/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.test: open /tmp/go-build138919994/b2921/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/apis/config/validation.test: open /tmp/go-build138919994/b2925/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubectl/util/term [build failed]
FAIL	k8s.io/kubernetes/pkg/kubectl/validation [build failed]
go build k8s.io/kubernetes/pkg/kubelet/apis/podresources.test: open /tmp/go-build138919994/b2928/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cadvisor.test: open /tmp/go-build138919994/b2931/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/certificate.test: open /tmp/go-build138919994/b2934/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap.test: open /tmp/go-build138919994/b2937/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/checkpoint.test: open /tmp/go-build138919994/b2940/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/checkpointmanager.test: open /tmp/go-build138919994/b2943/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/client.test: open /tmp/go-build138919994/b2948/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cloudresource.test: open /tmp/go-build138919994/b2951/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm.test: open /tmp/go-build138919994/b2954/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm/cpumanager.test: open /tmp/go-build138919994/b2957/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state.test: open /tmp/go-build138919994/b2960/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/topology.test: open /tmp/go-build138919994/b2964/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm/cpuset.test: open /tmp/go-build138919994/b2967/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.test: open /tmp/go-build138919994/b2970/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/config.test: open /tmp/go-build138919994/b2973/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/configmap.test: open /tmp/go-build138919994/b2976/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/container.test: open /tmp/go-build138919994/b2979/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/apis/config [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/apis/config/scheme [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/apis/config/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/apis/podresources [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cadvisor [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/certificate [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/certificate/bootstrap [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/checkpoint [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/checkpointmanager [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/client [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cloudresource [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cm [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/cpumanager [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/topology [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/cpuset [build failed]
go build k8s.io/kubernetes/pkg/kubelet/custommetrics.test: open /tmp/go-build138919994/b2984/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/devicemanager [build failed]
go build k8s.io/kubernetes/pkg/kubelet/dockershim.test: open /tmp/go-build138919994/b2987/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/config [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/configmap [build failed]
go build k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker.test: open /tmp/go-build138919994/b2991/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/dockershim/network/cni.test: open /tmp/go-build138919994/b2994/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/container [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/custommetrics [build failed]
go build k8s.io/kubernetes/pkg/kubelet/dockershim/network/hairpin.test: open /tmp/go-build138919994/b2998/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport.test: open /tmp/go-build138919994/b3001/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet.test: open /tmp/go-build138919994/b3004/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/dockershim/network/testing.test: open /tmp/go-build138919994/b3010/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/envvars.test: open /tmp/go-build138919994/b3013/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/libdocker [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/network/cni [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/network/hairpin [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport [build failed]
go build k8s.io/kubernetes/pkg/kubelet/eviction.test: open /tmp/go-build138919994/b3016/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/images.test: open /tmp/go-build138919994/b3019/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/kubeletconfig.test: open /tmp/go-build138919994/b3023/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/network/kubenet [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/dockershim/network/testing [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/envvars [build failed]
go build k8s.io/kubernetes/pkg/kubelet/kubeletconfig/checkpoint.test: open /tmp/go-build138919994/b3026/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/kubeletconfig/checkpoint/store.test: open /tmp/go-build138919994/b3030/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/eviction [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/images [build failed]
go build k8s.io/kubernetes/pkg/kubelet/kubeletconfig/configfiles.test: open /tmp/go-build138919994/b3033/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/kubeletconfig/util/files.test: open /tmp/go-build138919994/b3036/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/kuberuntime.test: open /tmp/go-build138919994/b3039/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/kubeletconfig [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/kubeletconfig/checkpoint [build failed]
go build k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs.test: open /tmp/go-build138919994/b3044/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/lifecycle.test: open /tmp/go-build138919994/b3047/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/kubeletconfig/checkpoint/store [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/kubeletconfig/configfiles [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/kubeletconfig/util/files [build failed]
go build k8s.io/kubernetes/pkg/kubelet/logs.test: open /tmp/go-build138919994/b3050/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/metrics/collectors.test: open /tmp/go-build138919994/b3053/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/mountpod.test: open /tmp/go-build138919994/b3057/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/network/dns.test: open /tmp/go-build138919994/b3060/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/nodelease.test: open /tmp/go-build138919994/b3063/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/nodestatus.test: open /tmp/go-build138919994/b3066/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/pleg.test: open /tmp/go-build138919994/b3069/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/kuberuntime [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/lifecycle [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/logs [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/metrics/collectors [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/mountpod [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/network/dns [build failed]
go build k8s.io/kubernetes/pkg/kubelet/pod.test: open /tmp/go-build138919994/b3072/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/preemption.test: open /tmp/go-build138919994/b3075/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/nodelease [build failed]
go build k8s.io/kubernetes/pkg/kubelet/prober.test: open /tmp/go-build138919994/b3078/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/prober/results.test: open /tmp/go-build138919994/b3081/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/qos.test: open /tmp/go-build138919994/b3084/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/remote.test: open /tmp/go-build138919994/b3087/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/nodestatus [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/pleg [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/pod [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/preemption [build failed]
go build k8s.io/kubernetes/pkg/kubelet/runtimeclass.test: open /tmp/go-build138919994/b3091/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/secret.test: open /tmp/go-build138919994/b3094/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/server.test: open /tmp/go-build138919994/b3097/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/server/portforward.test: open /tmp/go-build138919994/b3100/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/server/stats.test: open /tmp/go-build138919994/b3103/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/prober [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/prober/results [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/qos [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/remote [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/runtimeclass [build failed]
go build k8s.io/kubernetes/pkg/kubelet/server/streaming.test: open /tmp/go-build138919994/b3106/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/secret [build failed]
go build k8s.io/kubernetes/pkg/kubelet/stats.test: open /tmp/go-build138919994/b3109/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/status.test: open /tmp/go-build138919994/b3112/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/sysctl.test: open /tmp/go-build138919994/b3115/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/server [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/server/portforward [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/server/stats [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/server/streaming [build failed]
go build k8s.io/kubernetes/pkg/kubelet/token.test: open /tmp/go-build138919994/b3118/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/types.test: open /tmp/go-build138919994/b3121/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util.test: open /tmp/go-build138919994/b3124/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util/cache.test: open /tmp/go-build138919994/b3127/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util/format.test: open /tmp/go-build138919994/b3130/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/stats [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/status [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/sysctl [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/token [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/types [build failed]
go build k8s.io/kubernetes/pkg/kubelet/util/manager.test: open /tmp/go-build138919994/b3133/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.test: open /tmp/go-build138919994/b3136/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util/queue.test: open /tmp/go-build138919994/b3139/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/util [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/util/cache [build failed]
go build k8s.io/kubernetes/pkg/kubelet/util/sliceutils.test: open /tmp/go-build138919994/b3142/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/util/store.test: open /tmp/go-build138919994/b3145/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/util/format [build failed]
go build k8s.io/kubernetes/pkg/kubelet/volumemanager.test: open /tmp/go-build138919994/b3148/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/volumemanager/cache.test: open /tmp/go-build138919994/b3151/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/volumemanager/metrics.test: open /tmp/go-build138919994/b3154/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/util/manager [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/util/queue [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/util/sliceutils [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/util/store [build failed]
go build k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.test: open /tmp/go-build138919994/b3157/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.test: open /tmp/go-build138919994/b3160/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager/cache [build failed]
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager/metrics [build failed]
go build k8s.io/kubernetes/pkg/master.test: open /tmp/go-build138919994/b3164/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/master/controller/crdregistration.test: open /tmp/go-build138919994/b3210/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager/populator [build failed]
go build k8s.io/kubernetes/pkg/master/reconcilers.test: open /tmp/go-build138919994/b3213/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler [build failed]
?   	k8s.io/kubernetes/pkg/kubelet/winstats	[no test files]
go build k8s.io/kubernetes/pkg/master/tunneler.test: open /tmp/go-build138919994/b3216/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/printers.test: open /tmp/go-build138919994/b3219/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/printers/internalversion.test: open /tmp/go-build138919994/b3222/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/probe/exec.test: open /tmp/go-build138919994/b3226/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/probe/http.test: open /tmp/go-build138919994/b3229/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/probe/tcp.test: open /tmp/go-build138919994/b3232/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy.test: open /tmp/go-build138919994/b3235/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/apis/config/scheme.test: open /tmp/go-build138919994/b3238/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/apis/config/validation.test: open /tmp/go-build138919994/b3242/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/config.test: open /tmp/go-build138919994/b3245/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/healthcheck.test: open /tmp/go-build138919994/b3248/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/iptables.test: open /tmp/go-build138919994/b3251/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/ipvs.test: open /tmp/go-build138919994/b3255/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/master [build failed]
FAIL	k8s.io/kubernetes/pkg/master/controller/crdregistration [build failed]
FAIL	k8s.io/kubernetes/pkg/master/reconcilers [build failed]
FAIL	k8s.io/kubernetes/pkg/master/tunneler [build failed]
FAIL	k8s.io/kubernetes/pkg/printers [build failed]
FAIL	k8s.io/kubernetes/pkg/printers/internalversion [build failed]
FAIL	k8s.io/kubernetes/pkg/probe/exec [build failed]
FAIL	k8s.io/kubernetes/pkg/probe/http [build failed]
FAIL	k8s.io/kubernetes/pkg/probe/tcp [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/apis/config/scheme [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/apis/config/validation [build failed]
go build k8s.io/kubernetes/pkg/proxy/ipvs/testing.test: open /tmp/go-build138919994/b3261/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/proxy/userspace.test: open /tmp/go-build138919994/b3264/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/proxy/config [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/healthcheck [build failed]
go build k8s.io/kubernetes/pkg/proxy/util.test: open /tmp/go-build138919994/b3267/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/proxy/iptables [build failed]
go build k8s.io/kubernetes/pkg/proxy/winuserspace.test: open /tmp/go-build138919994/b3270/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/quota/v1.test: open /tmp/go-build138919994/b3278/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/quota/v1/evaluator/core.test: open /tmp/go-build138919994/b3281/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/proxy/ipvs [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/ipvs/testing [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/userspace [build failed]
FAIL	k8s.io/kubernetes/pkg/proxy/util [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/controllerrevision.test: open /tmp/go-build138919994/b3284/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/apps/controllerrevision/storage.test: open /tmp/go-build138919994/b3287/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/apps/daemonset.test: open /tmp/go-build138919994/b3293/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/proxy/winuserspace [build failed]
FAIL	k8s.io/kubernetes/pkg/quota/v1 [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/daemonset/storage.test: open /tmp/go-build138919994/b3296/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/quota/v1/evaluator/core [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/apps/controllerrevision [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/deployment.test: open /tmp/go-build138919994/b3299/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/apps/deployment/storage.test: open /tmp/go-build138919994/b3302/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/controllerrevision/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/apps/daemonset [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/replicaset.test: open /tmp/go-build138919994/b3305/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/apps/replicaset/storage.test: open /tmp/go-build138919994/b3308/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/daemonset/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/statefulset.test: open /tmp/go-build138919994/b3311/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/deployment [build failed]
go build k8s.io/kubernetes/pkg/registry/apps/statefulset/storage.test: open /tmp/go-build138919994/b3314/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/authorization/subjectaccessreview.test: open /tmp/go-build138919994/b3317/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/deployment/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/apps/replicaset [build failed]
go build k8s.io/kubernetes/pkg/registry/authorization/util.test: open /tmp/go-build138919994/b3320/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/autoscaling/horizontalpodautoscaler/storage.test: open /tmp/go-build138919994/b3323/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/replicaset/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/apps/statefulset [build failed]
go build k8s.io/kubernetes/pkg/registry/batch/cronjob.test: open /tmp/go-build138919994/b3326/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/batch/cronjob/storage.test: open /tmp/go-build138919994/b3329/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/apps/statefulset/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/authorization/subjectaccessreview [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/authorization/util [build failed]
go build k8s.io/kubernetes/pkg/registry/batch/job.test: open /tmp/go-build138919994/b3332/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/batch/job/storage.test: open /tmp/go-build138919994/b3336/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/certificates/certificates.test: open /tmp/go-build138919994/b3339/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/componentstatus.test: open /tmp/go-build138919994/b3342/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/autoscaling/horizontalpodautoscaler/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/batch/cronjob [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/batch/cronjob/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/batch/job [build failed]
go build k8s.io/kubernetes/pkg/registry/core/configmap.test: open /tmp/go-build138919994/b3345/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/configmap/storage.test: open /tmp/go-build138919994/b3348/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/endpoint/storage.test: open /tmp/go-build138919994/b3351/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/event.test: open /tmp/go-build138919994/b3354/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/batch/job/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/certificates/certificates [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/componentstatus [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/configmap [build failed]
go build k8s.io/kubernetes/pkg/registry/core/event/storage.test: open /tmp/go-build138919994/b3357/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/limitrange/storage.test: open /tmp/go-build138919994/b3360/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/configmap/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/endpoint/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/event [build failed]
go build k8s.io/kubernetes/pkg/registry/core/namespace/storage.test: open /tmp/go-build138919994/b3366/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/namespace.test: open /tmp/go-build138919994/b3363/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/node.test: open /tmp/go-build138919994/b3369/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/event/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/node/storage.test: open /tmp/go-build138919994/b3372/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/limitrange/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/persistentvolume.test: open /tmp/go-build138919994/b3375/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/namespace [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/namespace/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/persistentvolume/storage.test: open /tmp/go-build138919994/b3378/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/node [build failed]
go build k8s.io/kubernetes/pkg/registry/core/persistentvolumeclaim.test: open /tmp/go-build138919994/b3381/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/persistentvolumeclaim/storage.test: open /tmp/go-build138919994/b3384/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/pod.test: open /tmp/go-build138919994/b3387/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/pod/rest.test: open /tmp/go-build138919994/b3390/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/pod/storage.test: open /tmp/go-build138919994/b3393/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/node/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/persistentvolume [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/persistentvolume/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/persistentvolumeclaim [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/persistentvolumeclaim/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/podtemplate/storage.test: open /tmp/go-build138919994/b3396/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/pod [build failed]
go build k8s.io/kubernetes/pkg/registry/core/replicationcontroller.test: open /tmp/go-build138919994/b3399/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/pod/rest [build failed]
go build k8s.io/kubernetes/pkg/registry/core/replicationcontroller/storage.test: open /tmp/go-build138919994/b3402/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/resourcequota.test: open /tmp/go-build138919994/b3405/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/resourcequota/storage.test: open /tmp/go-build138919994/b3408/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/rest.test: open /tmp/go-build138919994/b3411/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/secret.test: open /tmp/go-build138919994/b3414/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/pod/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/podtemplate/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/replicationcontroller [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/replicationcontroller/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/secret/storage.test: open /tmp/go-build138919994/b3417/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/resourcequota [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/resourcequota/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/core/service.test: open /tmp/go-build138919994/b3420/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/allocator.test: open /tmp/go-build138919994/b3423/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/allocator/storage.test: open /tmp/go-build138919994/b3426/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/ipallocator.test: open /tmp/go-build138919994/b3429/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/ipallocator/controller.test: open /tmp/go-build138919994/b3432/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/ipallocator/storage.test: open /tmp/go-build138919994/b3435/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/rest [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/secret [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/secret/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/service [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/service/allocator [build failed]
go build k8s.io/kubernetes/pkg/registry/core/service/portallocator.test: open /tmp/go-build138919994/b3438/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/service/allocator/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/service/ipallocator [build failed]
go build k8s.io/kubernetes/pkg/registry/core/service/portallocator/controller.test: open /tmp/go-build138919994/b3441/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/service/storage.test: open /tmp/go-build138919994/b3444/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/core/serviceaccount/storage.test: open /tmp/go-build138919994/b3447/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/extensions/controller/storage.test: open /tmp/go-build138919994/b3450/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/service/ipallocator/controller [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/service/ipallocator/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/service/portallocator [build failed]
go build k8s.io/kubernetes/pkg/registry/extensions/ingress.test: open /tmp/go-build138919994/b3453/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/service/portallocator/controller [build failed]
go build k8s.io/kubernetes/pkg/registry/extensions/ingress/storage.test: open /tmp/go-build138919994/b3456/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/networking/networkpolicy/storage.test: open /tmp/go-build138919994/b3459/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/policy/poddisruptionbudget.test: open /tmp/go-build138919994/b3462/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/policy/poddisruptionbudget/storage.test: open /tmp/go-build138919994/b3465/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/core/service/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/core/serviceaccount/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/extensions/controller/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/extensions/ingress [build failed]
go build k8s.io/kubernetes/pkg/registry/policy/podsecuritypolicy/storage.test: open /tmp/go-build138919994/b3468/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/rbac/clusterrole/policybased.test: open /tmp/go-build138919994/b3474/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/extensions/ingress/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/networking/networkpolicy/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/policy/poddisruptionbudget [build failed]
go build k8s.io/kubernetes/pkg/registry/rbac.test: open /tmp/go-build138919994/b3471/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/rbac/reconciliation.test: open /tmp/go-build138919994/b3477/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/policy/poddisruptionbudget/storage [build failed]
go build k8s.io/kubernetes/pkg/registry/rbac/role/policybased.test: open /tmp/go-build138919994/b3480/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/rbac/validation.test: open /tmp/go-build138919994/b3483/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/policy/podsecuritypolicy/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/rbac [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/rbac/clusterrole/policybased [build failed]
go build k8s.io/kubernetes/pkg/registry/scheduling/priorityclass.test: open /tmp/go-build138919994/b3486/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/scheduling/priorityclass/storage.test: open /tmp/go-build138919994/b3489/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/settings/podpreset/storage.test: open /tmp/go-build138919994/b3492/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/storage/storageclass.test: open /tmp/go-build138919994/b3495/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/rbac/reconciliation [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/rbac/role/policybased [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/rbac/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/scheduling/priorityclass [build failed]
go build k8s.io/kubernetes/pkg/registry/storage/storageclass/storage.test: open /tmp/go-build138919994/b3498/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/storage/volumeattachment.test: open /tmp/go-build138919994/b3501/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/registry/storage/volumeattachment/storage.test: open /tmp/go-build138919994/b3504/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler.test: open /tmp/go-build138919994/b3507/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/scheduling/priorityclass/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/settings/podpreset/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/storage/storageclass [build failed]
go build k8s.io/kubernetes/pkg/scheduler/algorithm/predicates.test: open /tmp/go-build138919994/b3511/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.test: open /tmp/go-build138919994/b3515/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/storage/storageclass/storage [build failed]
FAIL	k8s.io/kubernetes/pkg/registry/storage/volumeattachment [build failed]
go build k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util.test: open /tmp/go-build138919994/b3518/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/registry/storage/volumeattachment/storage [build failed]
go build k8s.io/kubernetes/pkg/scheduler/algorithmprovider.test: open /tmp/go-build138919994/b3521/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults.test: open /tmp/go-build138919994/b3524/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/api/compatibility.test: open /tmp/go-build138919994/b3527/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/api/validation.test: open /tmp/go-build138919994/b3530/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/algorithm/predicates [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/algorithm/priorities [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/algorithmprovider [build failed]
go build k8s.io/kubernetes/pkg/scheduler/apis/config/v1alpha1.test: open /tmp/go-build138919994/b3533/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/apis/config/validation.test: open /tmp/go-build138919994/b3536/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/algorithmprovider/defaults [build failed]
go build k8s.io/kubernetes/pkg/scheduler/core.test: open /tmp/go-build138919994/b3539/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/factory.test: open /tmp/go-build138919994/b3542/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/internal/cache.test: open /tmp/go-build138919994/b3545/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/internal/cache/debugger.test: open /tmp/go-build138919994/b3548/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/api/compatibility [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/api/validation [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/apis/config/v1alpha1 [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/apis/config/validation [build failed]
go build k8s.io/kubernetes/pkg/scheduler/internal/queue.test: open /tmp/go-build138919994/b3551/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/scheduler/nodeinfo.test: open /tmp/go-build138919994/b3554/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/core [build failed]
go build k8s.io/kubernetes/pkg/scheduler/util.test: open /tmp/go-build138919994/b3557/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/factory [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/internal/cache [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/internal/cache/debugger [build failed]
go build k8s.io/kubernetes/pkg/security/apparmor.test: open /tmp/go-build138919994/b3560/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy.test: open /tmp/go-build138919994/b3563/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/apparmor.test: open /tmp/go-build138919994/b3566/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/internal/queue [build failed]
FAIL	k8s.io/kubernetes/pkg/scheduler/nodeinfo [build failed]
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/capabilities.test: open /tmp/go-build138919994/b3569/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/group.test: open /tmp/go-build138919994/b3572/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/scheduler/util [build failed]
FAIL	k8s.io/kubernetes/pkg/security/apparmor [build failed]
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/seccomp.test: open /tmp/go-build138919994/b3575/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/selinux.test: open /tmp/go-build138919994/b3578/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/sysctl.test: open /tmp/go-build138919994/b3581/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/util.test: open /tmp/go-build138919994/b3587/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/security/podsecuritypolicy/user.test: open /tmp/go-build138919994/b3584/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/apparmor [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/capabilities [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/group [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/seccomp [build failed]
go build k8s.io/kubernetes/pkg/securitycontext.test: open /tmp/go-build138919994/b3590/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/selinux [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/sysctl [build failed]
go build k8s.io/kubernetes/pkg/ssh.test: open /tmp/go-build138919994/b3599/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/user [build failed]
FAIL	k8s.io/kubernetes/pkg/security/podsecuritypolicy/util [build failed]
FAIL	k8s.io/kubernetes/pkg/securitycontext [build failed]
go build k8s.io/kubernetes/pkg/util/async.test: open /tmp/go-build138919994/b3602/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/config.test: open /tmp/go-build138919994/b3608/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/configz.test: open /tmp/go-build138919994/b3611/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/bandwidth.test: open /tmp/go-build138919994/b3605/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/conntrack.test: open /tmp/go-build138919994/b3614/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/dbus.test: open /tmp/go-build138919994/b3617/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ebtables.test: open /tmp/go-build138919994/b3620/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/env.test: open /tmp/go-build138919994/b3623/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/flag.test: open /tmp/go-build138919994/b3626/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/goroutinemap.test: open /tmp/go-build138919994/b3629/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/hash.test: open /tmp/go-build138919994/b3632/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ipconfig.test: open /tmp/go-build138919994/b3635/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ipset/testing.test: open /tmp/go-build138919994/b3641/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ipset.test: open /tmp/go-build138919994/b3638/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/serviceaccount.test: open /tmp/go-build138919994/b3593/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ipvs.test: open /tmp/go-build138919994/b3647/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/ipvs/testing.test: open /tmp/go-build138919994/b3650/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/iptables.test: open /tmp/go-build138919994/b3644/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/labels.test: open /tmp/go-build138919994/b3653/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/metrics.test: open /tmp/go-build138919994/b3656/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/net.test: open /tmp/go-build138919994/b3662/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/net/sets.test: open /tmp/go-build138919994/b3665/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/serviceaccount [build failed]
FAIL	k8s.io/kubernetes/pkg/ssh [build failed]
FAIL	k8s.io/kubernetes/pkg/util/async [build failed]
FAIL	k8s.io/kubernetes/pkg/util/bandwidth [build failed]
FAIL	k8s.io/kubernetes/pkg/util/config [build failed]
FAIL	k8s.io/kubernetes/pkg/util/configz [build failed]
FAIL	k8s.io/kubernetes/pkg/util/conntrack [build failed]
FAIL	k8s.io/kubernetes/pkg/util/dbus [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ebtables [build failed]
FAIL	k8s.io/kubernetes/pkg/util/env [build failed]
FAIL	k8s.io/kubernetes/pkg/util/flag [build failed]
FAIL	k8s.io/kubernetes/pkg/util/goroutinemap [build failed]
FAIL	k8s.io/kubernetes/pkg/util/hash [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ipconfig [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ipset [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ipset/testing [build failed]
FAIL	k8s.io/kubernetes/pkg/util/iptables [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ipvs [build failed]
FAIL	k8s.io/kubernetes/pkg/util/ipvs/testing [build failed]
FAIL	k8s.io/kubernetes/pkg/util/labels [build failed]
FAIL	k8s.io/kubernetes/pkg/util/metrics [build failed]
go build k8s.io/kubernetes/pkg/util/oom.test: open /tmp/go-build138919994/b3674/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/netsh.test: open /tmp/go-build138919994/b3668/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/parsers.test: open /tmp/go-build138919994/b3677/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/node.test: open /tmp/go-build138919994/b3671/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/procfs.test: open /tmp/go-build138919994/b3683/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/pod.test: open /tmp/go-build138919994/b3680/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/mount.test: open /tmp/go-build138919994/b3659/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/removeall.test: open /tmp/go-build138919994/b3686/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/slice.test: open /tmp/go-build138919994/b3689/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/tail.test: open /tmp/go-build138919994/b3695/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/system.test: open /tmp/go-build138919994/b3692/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/util/mount [build failed]
FAIL	k8s.io/kubernetes/pkg/util/net [build failed]
FAIL	k8s.io/kubernetes/pkg/util/net/sets [build failed]
FAIL	k8s.io/kubernetes/pkg/util/netsh [build failed]
FAIL	k8s.io/kubernetes/pkg/util/node [build failed]
FAIL	k8s.io/kubernetes/pkg/util/oom [build failed]
FAIL	k8s.io/kubernetes/pkg/util/parsers [build failed]
FAIL	k8s.io/kubernetes/pkg/util/pod [build failed]
FAIL	k8s.io/kubernetes/pkg/util/procfs [build failed]
FAIL	k8s.io/kubernetes/pkg/util/removeall [build failed]
FAIL	k8s.io/kubernetes/pkg/util/slice [build failed]
FAIL	k8s.io/kubernetes/pkg/util/system [build failed]
FAIL	k8s.io/kubernetes/pkg/util/tail [build failed]
go build k8s.io/kubernetes/pkg/util/tolerations.test: open /tmp/go-build138919994/b3701/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/util/taints.test: open /tmp/go-build138919994/b3698/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/util/taints [build failed]
FAIL	k8s.io/kubernetes/pkg/util/tolerations [build failed]
go build k8s.io/kubernetes/pkg/volume/awsebs.test: open /tmp/go-build138919994/b3710/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/azure_dd.test: open /tmp/go-build138919994/b3713/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/azure_file.test: open /tmp/go-build138919994/b3716/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/cephfs.test: open /tmp/go-build138919994/b3719/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume.test: open /tmp/go-build138919994/b3704/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/configmap.test: open /tmp/go-build138919994/b3725/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/cinder.test: open /tmp/go-build138919994/b3722/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/awsebs [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/azure_dd [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/azure_file [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/cephfs [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/cinder [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/configmap [build failed]
go build k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager.test: open /tmp/go-build138919994/b3734/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/emptydir.test: open /tmp/go-build138919994/b3740/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/downwardapi.test: open /tmp/go-build138919994/b3737/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/csi.test: open /tmp/go-build138919994/b3728/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/fc.test: open /tmp/go-build138919994/b3743/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/flocker.test: open /tmp/go-build138919994/b3750/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/csi [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/csi/nodeinfomanager [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/downwardapi [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/emptydir [build failed]
go build k8s.io/kubernetes/pkg/volume/flexvolume.test: open /tmp/go-build138919994/b3746/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/fc [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/flexvolume [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/flocker [build failed]
go build k8s.io/kubernetes/pkg/volume/git_repo.test: open /tmp/go-build138919994/b3756/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/glusterfs.test: open /tmp/go-build138919994/b3759/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/host_path.test: open /tmp/go-build138919994/b3762/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/gcepd.test: open /tmp/go-build138919994/b3753/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/iscsi.test: open /tmp/go-build138919994/b3765/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/nfs.test: open /tmp/go-build138919994/b3771/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/gcepd [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/git_repo [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/glusterfs [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/host_path [build failed]
go build k8s.io/kubernetes/pkg/volume/local.test: open /tmp/go-build138919994/b3768/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/iscsi [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/local [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/nfs [build failed]
go build k8s.io/kubernetes/pkg/volume/portworx.test: open /tmp/go-build138919994/b3777/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/photon_pd.test: open /tmp/go-build138919994/b3774/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/projected.test: open /tmp/go-build138919994/b3780/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/quobyte.test: open /tmp/go-build138919994/b3783/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/photon_pd [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/portworx [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/projected [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/quobyte [build failed]
go build k8s.io/kubernetes/pkg/volume/scaleio.test: open /tmp/go-build138919994/b3789/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/rbd.test: open /tmp/go-build138919994/b3786/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/secret.test: open /tmp/go-build138919994/b3792/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/storageos.test: open /tmp/go-build138919994/b3795/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/rbd [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/scaleio [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/secret [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/storageos [build failed]
go build k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.test: open /tmp/go-build138919994/b3801/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/validation.test: open /tmp/go-build138919994/b3810/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/util/recyclerclient.test: open /tmp/go-build138919994/b3807/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/util/operationexecutor.test: open /tmp/go-build138919994/b3804/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/admit.test: open /tmp/go-build138919994/b3816/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/util.test: open /tmp/go-build138919994/b3798/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/alwayspullimages.test: open /tmp/go-build138919994/b3819/importcfg: no such file or directory
go build k8s.io/kubernetes/pkg/volume/vsphere_volume.test: open /tmp/go-build138919994/b3813/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/antiaffinity.test: open /tmp/go-build138919994/b3822/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/util [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/util/operationexecutor [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/util/recyclerclient [build failed]
FAIL	k8s.io/kubernetes/pkg/volume/validation [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/deny.test: open /tmp/go-build138919994/b3828/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/defaulttolerationseconds.test: open /tmp/go-build138919994/b3825/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/eventratelimit/apis/eventratelimit/validation.test: open /tmp/go-build138919994/b3834/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/pkg/volume/vsphere_volume [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/admit [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/alwayspullimages [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/antiaffinity [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/defaulttolerationseconds [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/deny [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/extendedresourcetoleration.test: open /tmp/go-build138919994/b3840/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/exec.test: open /tmp/go-build138919994/b3837/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/gc.test: open /tmp/go-build138919994/b3843/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/eventratelimit.test: open /tmp/go-build138919994/b3831/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/eventratelimit [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/eventratelimit/apis/eventratelimit/validation [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/exec [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/extendedresourcetoleration [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/imagepolicy.test: open /tmp/go-build138919994/b3846/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/gc [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/imagepolicy [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/namespace/autoprovision.test: open /tmp/go-build138919994/b3852/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/namespace/exists.test: open /tmp/go-build138919994/b3855/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/nodetaint.test: open /tmp/go-build138919994/b3861/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/limitranger.test: open /tmp/go-build138919994/b3849/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/podnodeselector.test: open /tmp/go-build138919994/b3864/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/limitranger [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/namespace/autoprovision [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/namespace/exists [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/podpreset.test: open /tmp/go-build138919994/b3867/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/apis/podtolerationrestriction/validation.test: open /tmp/go-build138919994/b3873/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction.test: open /tmp/go-build138919994/b3870/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/noderestriction.test: open /tmp/go-build138919994/b3858/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/priority.test: open /tmp/go-build138919994/b3876/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/noderestriction [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/nodetaint [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/podnodeselector [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/podpreset [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/podtolerationrestriction/apis/podtolerationrestriction/validation [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/resourcequota/apis/resourcequota/validation.test: open /tmp/go-build138919994/b3882/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/priority [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/securitycontext/scdeny.test: open /tmp/go-build138919994/b3888/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/security/podsecuritypolicy.test: open /tmp/go-build138919994/b3885/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/resourcequota.test: open /tmp/go-build138919994/b3879/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/label.test: open /tmp/go-build138919994/b3894/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/serviceaccount.test: open /tmp/go-build138919994/b3891/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/resourcequota [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/resourcequota/apis/resourcequota/validation [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/security/podsecuritypolicy [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/securitycontext/scdeny [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/serviceaccount [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/label [build failed]
go build k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/resize.test: open /tmp/go-build138919994/b3897/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/storage/storageobjectinuseprotection.test: open /tmp/go-build138919994/b3903/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/admission/storage/storageclass/setdefault.test: open /tmp/go-build138919994/b3900/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/bootstrap.test: open /tmp/go-build138919994/b3906/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/admission/storage/persistentvolume/resize [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/storage/storageclass/setdefault [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/admission/storage/storageobjectinuseprotection [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/bootstrap [build failed]
go build k8s.io/kubernetes/test/conformance.test: open /tmp/go-build138919994/b3919/importcfg: no such file or directory
go build k8s.io/kubernetes/test/images/crd-conversion-webhook/converter.test: open /tmp/go-build138919994/b3922/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.test: open /tmp/go-build138919994/b3912/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/auth/authorizer/node.test: open /tmp/go-build138919994/b3909/importcfg: no such file or directory
go build k8s.io/kubernetes/test/list.test: open /tmp/go-build138919994/b3928/importcfg: no such file or directory
go build k8s.io/kubernetes/test/images/webhook.test: open /tmp/go-build138919994/b3925/importcfg: no such file or directory
go build k8s.io/kubernetes/test/typecheck.test: open /tmp/go-build138919994/b3931/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/auth/authorizer/node [build failed]
FAIL	k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission.test: open /tmp/go-build138919994/b3937/importcfg: no such file or directory
go build k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy.test: open /tmp/go-build138919994/b3915/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/configuration.test: open /tmp/go-build138919994/b3940/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/initializer.test: open /tmp/go-build138919994/b3943/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy [build failed]
FAIL	k8s.io/kubernetes/test/conformance [build failed]
FAIL	k8s.io/kubernetes/test/images/crd-conversion-webhook/converter [build failed]
FAIL	k8s.io/kubernetes/test/images/webhook [build failed]
FAIL	k8s.io/kubernetes/test/list [build failed]
FAIL	k8s.io/kubernetes/test/typecheck [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/configuration [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/initializer [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/errors.test: open /tmp/go-build138919994/b3952/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics.test: open /tmp/go-build138919994/b3946/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/metrics [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/initializer.test: open /tmp/go-build138919994/b3961/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle.test: open /tmp/go-build138919994/b3949/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/errors [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/generic.test: open /tmp/go-build138919994/b3955/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/rules.test: open /tmp/go-build138919994/b3972/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/generic [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/initializer [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/namespace.test: open /tmp/go-build138919994/b3969/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/install.test: open /tmp/go-build138919994/b3978/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating.test: open /tmp/go-build138919994/b3964/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating.test: open /tmp/go-build138919994/b3975/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/namespace [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/rules [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/install [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1alpha1.test: open /tmp/go-build138919994/b3982/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/validation.test: open /tmp/go-build138919994/b3988/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1beta1.test: open /tmp/go-build138919994/b3985/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example/install.test: open /tmp/go-build138919994/b3991/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example2/install.test: open /tmp/go-build138919994/b3995/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1alpha1 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/audit/validation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example/install [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/apis/example2/install [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/event.test: open /tmp/go-build138919994/b4001/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/util.test: open /tmp/go-build138919994/b4007/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit.test: open /tmp/go-build138919994/b3998/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/authenticator.test: open /tmp/go-build138919994/b4010/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/event [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/group.test: open /tmp/go-build138919994/b4013/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/policy.test: open /tmp/go-build138919994/b4004/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/anonymous.test: open /tmp/go-build138919994/b4016/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/bearertoken.test: open /tmp/go-build138919994/b4019/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/policy [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/audit/util [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/authenticator [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/group [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/anonymous [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/bearertoken [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/union.test: open /tmp/go-build138919994/b4025/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest.test: open /tmp/go-build138919994/b4022/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/websocket.test: open /tmp/go-build138919994/b4028/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/headerrequest [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/union [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/x509.test: open /tmp/go-build138919994/b4031/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/serviceaccount.test: open /tmp/go-build138919994/b4034/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/websocket [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/cache.test: open /tmp/go-build138919994/b4037/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/request/x509 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/serviceaccount [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/union.test: open /tmp/go-build138919994/b4043/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/tokenfile.test: open /tmp/go-build138919994/b4040/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/cache [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/authorizerfactory.test: open /tmp/go-build138919994/b4046/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/path.test: open /tmp/go-build138919994/b4049/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/tokenfile [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authentication/token/union [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/authorizerfactory [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/path [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/union.test: open /tmp/go-build138919994/b4052/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/authorization/union [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/discovery.test: open /tmp/go-build138919994/b4059/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.test: open /tmp/go-build138919994/b4062/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/negotiation.test: open /tmp/go-build138919994/b4068/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.test: open /tmp/go-build138919994/b4071/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.test: open /tmp/go-build138919994/b4065/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.test: open /tmp/go-build138919994/b4074/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/openapi.test: open /tmp/go-build138919994/b4077/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.test: open /tmp/go-build138919994/b4081/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/rest.test: open /tmp/go-build138919994/b4087/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest.test: open /tmp/go-build138919994/b4090/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.test: open /tmp/go-build138919994/b4055/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.test: open /tmp/go-build138919994/b4084/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.test: open /tmp/go-build138919994/b4096/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/discovery [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/negotiation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/openapi [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.test: open /tmp/go-build138919994/b4102/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/rest [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.test: open /tmp/go-build138919994/b4099/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.test: open /tmp/go-build138919994/b4105/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.test: open /tmp/go-build138919994/b4093/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig.test: open /tmp/go-build138919994/b4111/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/resourceconfig.test: open /tmp/go-build138919994/b4114/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/storage.test: open /tmp/go-build138919994/b4117/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage.test: open /tmp/go-build138919994/b4121/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.test: open /tmp/go-build138919994/b4108/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd.test: open /tmp/go-build138919994/b4127/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd/util.test: open /tmp/go-build138919994/b4130/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.test: open /tmp/go-build138919994/b4124/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/preflight.test: open /tmp/go-build138919994/b4137/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/names.test: open /tmp/go-build138919994/b4140/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory.test: open /tmp/go-build138919994/b4143/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/encryptionconfig [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/resourceconfig [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/storage [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd/util [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.test: open /tmp/go-build138919994/b4133/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value.test: open /tmp/go-build138919994/b4149/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/tests.test: open /tmp/go-build138919994/b4146/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/aes.test: open /tmp/go-build138919994/b4152/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/preflight [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/names [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope.test: open /tmp/go-build138919994/b4155/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/tests [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/aes [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/secretbox.test: open /tmp/go-build138919994/b4158/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/envelope [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/value/encrypt/secretbox [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/feature.test: open /tmp/go-build138919994/b4161/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flushwriter.test: open /tmp/go-build138919994/b4173/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/feature [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/globalflag.test: open /tmp/go-build138919994/b4176/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag.test: open /tmp/go-build138919994/b4164/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/openapi.test: open /tmp/go-build138919994/b4179/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/proxy.test: open /tmp/go-build138919994/b4182/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flag [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flushwriter [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/globalflag [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/openapi [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/proxy [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/buffered.test: open /tmp/go-build138919994/b4191/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/wsstream.test: open /tmp/go-build138919994/b4188/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/webhook.test: open /tmp/go-build138919994/b4185/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/dynamic/enforced.test: open /tmp/go-build138919994/b4198/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/log.test: open /tmp/go-build138919994/b4201/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/webhook [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/wsstream [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/buffered [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/truncate.test: open /tmp/go-build138919994/b4204/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook.test: open /tmp/go-build138919994/b4207/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/dynamic.test: open /tmp/go-build138919994/b4195/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile.test: open /tmp/go-build138919994/b4210/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/request/basicauth.test: open /tmp/go-build138919994/b4213/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook.test: open /tmp/go-build138919994/b4219/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook.test: open /tmp/go-build138919994/b4222/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/dynamic [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/dynamic/enforced [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/log [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/truncate [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/password/passwordfile [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/request/basicauth [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc.test: open /tmp/go-build138919994/b4216/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/deprecated-dynamic.test: open /tmp/go-build138919994/b4225/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/authorizer/webhook [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached.test: open /tmp/go-build138919994/b4232/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/deprecated-dynamic [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/fake.test: open /tmp/go-build138919994/b4235/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.test: open /tmp/go-build138919994/b4228/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic.test: open /tmp/go-build138919994/b4238/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamicinformer.test: open /tmp/go-build138919994/b4241/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/discovery [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/fake [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/fake.test: open /tmp/go-build138919994/b4249/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamiclister.test: open /tmp/go-build138919994/b4246/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/examples/fake-client.test: open /tmp/go-build138919994/b4252/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamicinformer [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/dynamiclister [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/dynamic/fake [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes_test.test: open /tmp/go-build138919994/b4255/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/listers/extensions/v1beta1.test: open /tmp/go-build138919994/b4258/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure.test: open /tmp/go-build138919994/b4261/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/examples/fake-client [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes_test [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/listers/extensions/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp.test: open /tmp/go-build138919994/b4267/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc.test: open /tmp/go-build138919994/b4270/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/openstack.test: open /tmp/go-build138919994/b4273/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/exec.test: open /tmp/go-build138919994/b4264/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/exec [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/openstack [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/rest/watch.test: open /tmp/go-build138919994/b4279/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper.test: open /tmp/go-build138919994/b4282/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/scale.test: open /tmp/go-build138919994/b4285/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/auth.test: open /tmp/go-build138919994/b4291/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/testing.test: open /tmp/go-build138919994/b4288/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/rest.test: open /tmp/go-build138919994/b4276/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/testing.test: open /tmp/go-build138919994/b4298/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/rest [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/rest/watch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/scale [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/testing [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/auth [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api.test: open /tmp/go-build138919994/b4304/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.test: open /tmp/go-build138919994/b4301/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/pager.test: open /tmp/go-build138919994/b4310/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.test: open /tmp/go-build138919994/b4294/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.test: open /tmp/go-build138919994/b4307/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/portforward.test: open /tmp/go-build138919994/b4313/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/reference.test: open /tmp/go-build138919994/b4319/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.test: open /tmp/go-build138919994/b4316/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/testing [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/api [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/pager [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/portforward [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand.test: open /tmp/go-build138919994/b4322/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/cert.test: open /tmp/go-build138919994/b4331/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/reference [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/tools/watch.test: open /tmp/go-build138919994/b4325/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation.test: open /tmp/go-build138919994/b4337/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/transport.test: open /tmp/go-build138919994/b4328/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/flowcontrol.test: open /tmp/go-build138919994/b4340/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/testing.test: open /tmp/go-build138919994/b4349/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/watch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/transport [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/cert [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/retry.test: open /tmp/go-build138919994/b4346/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/certificate.test: open /tmp/go-build138919994/b4334/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer.test: open /tmp/go-build138919994/b4356/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/certificate [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/connrotation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/flowcontrol [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.test: open /tmp/go-build138919994/b4343/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/retry [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/testing [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.test: open /tmp/go-build138919994/b4352/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors.test: open /tmp/go-build138919994/b4359/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/apitesting/fuzzer [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/validation/path.test: open /tmp/go-build138919994/b4372/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/errors [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/validation.test: open /tmp/go-build138919994/b4369/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion.test: open /tmp/go-build138919994/b4375/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/meta.test: open /tmp/go-build138919994/b4362/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/resource.test: open /tmp/go-build138919994/b4365/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/meta [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation.test: open /tmp/go-build138919994/b4392/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/resource [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/validation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/api/validation/path [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/internalversion [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.test: open /tmp/go-build138919994/b4383/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/testapigroup/install.test: open /tmp/go-build138919994/b4395/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion.test: open /tmp/go-build138919994/b4399/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/queryparams.test: open /tmp/go-build138919994/b4402/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.test: open /tmp/go-build138919994/b4378/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/unstructured.test: open /tmp/go-build138919994/b4405/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/fields.test: open /tmp/go-build138919994/b4409/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/labels.test: open /tmp/go-build138919994/b4412/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/testapigroup/install [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/queryparams [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/conversion/unstructured [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/fields [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/labels [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.test: open /tmp/go-build138919994/b4437/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer.test: open /tmp/go-build138919994/b4433/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/recognizer/testing.test: open /tmp/go-build138919994/b4441/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.test: open /tmp/go-build138919994/b4444/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema.test: open /tmp/go-build138919994/b4430/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/cache.test: open /tmp/go-build138919994/b4453/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/test.test: open /tmp/go-build138919994/b4450/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/clock.test: open /tmp/go-build138919994/b4456/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.test: open /tmp/go-build138919994/b4447/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/duration.test: open /tmp/go-build138919994/b4462/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/errors.test: open /tmp/go-build138919994/b4465/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/diff.test: open /tmp/go-build138919994/b4459/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/framer.test: open /tmp/go-build138919994/b4468/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream.test: open /tmp/go-build138919994/b4471/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/json.test: open /tmp/go-build138919994/b4481/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/intstr.test: open /tmp/go-build138919994/b4478/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy.test: open /tmp/go-build138919994/b4474/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch.test: open /tmp/go-build138919994/b4484/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.test: open /tmp/go-build138919994/b4415/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/naming.test: open /tmp/go-build138919994/b4490/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/mergepatch.test: open /tmp/go-build138919994/b4487/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/rand.test: open /tmp/go-build138919994/b4499/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.test: open /tmp/go-build138919994/b4502/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/recognizer/testing [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/test [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/cache [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/clock [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/diff [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/duration [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/errors [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/framer [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/intstr [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/json [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/mergepatch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/naming [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.test: open /tmp/go-build138919994/b4505/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation.test: open /tmp/go-build138919994/b4511/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net.test: open /tmp/go-build138919994/b4493/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.test: open /tmp/go-build138919994/b4496/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field.test: open /tmp/go-build138919994/b4514/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/strategicpatch.test: open /tmp/go-build138919994/b4508/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/net [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/version.test: open /tmp/go-build138919994/b4517/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/waitgroup.test: open /tmp/go-build138919994/b4523/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/rand [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/version.test: open /tmp/go-build138919994/b4529/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/strategicpatch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/validation/field [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/version [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/json.test: open /tmp/go-build138919994/b4535/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.test: open /tmp/go-build138919994/b4520/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect.test: open /tmp/go-build138919994/b4538/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/waitgroup [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml.test: open /tmp/go-build138919994/b4526/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.test: open /tmp/go-build138919994/b4532/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/version [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/json [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration.test: open /tmp/go-build138919994/b4541/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/openapi.test: open /tmp/go-build138919994/b4552/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/autoregister.test: open /tmp/go-build138919994/b4547/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.test: open /tmp/go-build138919994/b4544/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions.test: open /tmp/go-build138919994/b4558/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/status.test: open /tmp/go-build138919994/b4555/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install.test: open /tmp/go-build138919994/b4561/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/autoregister [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/openapi [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/controllers/status [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/install [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation.test: open /tmp/go-build138919994/b4574/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation.test: open /tmp/go-build138919994/b4568/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/status.test: open /tmp/go-build138919994/b4577/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1.test: open /tmp/go-build138919994/b4565/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor.test: open /tmp/go-build138919994/b4585/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.test: open /tmp/go-build138919994/b4571/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1 [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.test: open /tmp/go-build138919994/b4588/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/validation [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/status [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource.test: open /tmp/go-build138919994/b4580/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apis/wardle/install.test: open /tmp/go-build138919994/b4616/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/admission/wardleinitializer.test: open /tmp/go-build138919994/b4613/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/admission/plugin/banflunder.test: open /tmp/go-build138919994/b4591/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/admission/plugin/banflunder [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/admission/wardleinitializer [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apis/wardle/install [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions.test: open /tmp/go-build138919994/b4628/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apiserver.test: open /tmp/go-build138919994/b4620/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/sample-apiserver/pkg/apiserver [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions [build failed]
go build k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers.test: open /tmp/go-build138919994/b4631/importcfg: no such file or directory
go build k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource.test: open /tmp/go-build138919994/b4634/importcfg: no such file or directory
FAIL	k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers [build failed]
FAIL	k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource [build failed]
Makefile:184: recipe for target 'test' failed
make: *** [test] Error 1
root@ubuntu18:/go/src/k8s.io/kubernetes#
```

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/73689

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-proxy/app/server_test.go [hunk 1]
```diff
@@ -415,8 +416,11 @@ func TestProcessHostnameOverrideFlag(t *testing.T) {
 
 func TestConfigChange(t *testing.T) {
 	setUp := func() (*os.File, string, error) {
-		tempDir := os.TempDir()
-		file, err := ioutil.TempFile(tempDir, "kube-proxy-config-")
+		tempDir, err := ioutil.TempDir("", "kubeproxy-config-change")
+		if err != nil {
+			t.Errorf("Unable to create temporary directory: %v", err)
```
Comment (liggitt) [inline cmd/kube-proxy/app/server_test.go]: `return nil, "", fmt.Errorf(...`

**Comment by liggitt** [comment]
needs `hack/update-bazel.sh` run

**Comment by spiffxp** [comment]
/priority critical-urgent
/sig api-machinery
(they own cmd)

**Comment by liggitt** [comment]
> /sig api-machinery
> (they own cmd)

really? I'd have guessed kube-proxy tests would belong to sig-network
