### PR TITLE
Omit invalid affinity error in admission

### LINKED ISSUE #27645: LimitPodHardAntiAffinityTopology fails e2e test when enabled
#19914 added a topology limiter, however when enabled this admission plugin breaks the SchedulerPredicates invalid NodeAffinity test because it returns early from the admission plugin:

```
[k8s.io] SchedulerPredicates [Serial]
/Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/framework/framework.go:505
  validates that a pod with an invalid NodeAffinity is rejected
  /Users/clayton/projects/origin/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:437
```

```
	affinity, err := api.GetAffinityFromPodAnnotations(pod.Annotations)
	if err != nil {
		return err
	}
```

returns a JSON error.  Because we validate these, I think the admission controller should allow the unparseable annotations by returning nil:

```
	affinity, err := api.GetAffinityFromPodAnnotations(pod.Annotations)
	if err != nil {
		return nil
	}
```

This allows validation to handle the error.

### PR DESCRIPTION
**Pull request by resouer**
Fixes #27645  cc @smarterclayton 

Not sure if this is too aggressive, but user should expect failure if they disable validation after all.

### CODE REVIEW

File: plugin/pkg/admission/antiaffinity/admission.go [hunk 1]
```diff
@@ -59,7 +60,8 @@ func (p *plugin) Admit(attributes admission.Attributes) (err error) {
 	}
 	affinity, err := api.GetAffinityFromPodAnnotations(pod.Annotations)
 	if err != nil {
-		return err
+		glog.Warningf("Invalid NodeAffinity detected, but we will leave handling of this to validation phase")
```
Comment (smarterclayton) [inline plugin/pkg/admission/antiaffinity/admission.go]: We generally wouldn't output this at WARNING because on a large cluster there could be thousands of these and they would fill the logs.  You can rely on validation being called for the pod, because if it isn't, then lots of other very scary things can happen in the cluster.

Putting it at glog.V(4) or 5 is ok.

File: plugin/pkg/admission/antiaffinity/admission.go [hunk 2]
```diff
@@ -59,7 +60,8 @@ func (p *plugin) Admit(attributes admission.Attributes) (err error) {
 	}
 	affinity, err := api.GetAffinityFromPodAnnotations(pod.Annotations)
 	if err != nil {
-		return err
+		glog.V(5).Infof("Invalid NodeAffinity detected, but we will leave handling of this to validation phase")
```
Comment (kevin-wangzefeng) [inline plugin/pkg/admission/antiaffinity/admission.go]: s/NodeAffinity/Affinity/g

This function is to parse Affinity not NodeAffinity.

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
I guess it would be good to have a unit test to ensure this doesn't regress since I don't think we run with this enabled yet in e2e.

**Comment by resouer** [comment]
@derekwaynecarr Unit test is added, thanks for review

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076
