### PR TITLE
Fixing federation secret controller unit test flakiness

### LINKED ISSUE #36422: TestSecretController {secret}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/19368/

Failed: TestSecretController {secret}

```
<autogenerated>:10: 
                        
	Error Trace:	secret_controller_test.go:141
	
	Error:		Should be true
	
	Messages:	expected: {{ } {test-secret  ns /api/v1/namespaces/ns/secrets/test-secret   0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[A:B] [] [federation.kubernetes.io/delete-from-underlying-clusters orphan] } map[config:[109 121 99 111 110 102 105 103 117 114 97 116 105 111 110 102 105 108 101]] map[] Opaque}, actual: {{ } {test-secret  ns    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[A:B] [] [] } map[A:[97 108 97 32 109 97 32 107 111 116 97] B:[113 117 105 99 107 32 98 114 111 119 110 32 102 111 120]] map[] Opaque}
	
```

Previous issues for this test: #33880

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/36422

Adding a wait for the secret to be updated in the store to fix flakiness.
It was failing ~once in 3 to 5 runs before this change. I now have had 30 local runs without a failure.

cc @kubernetes/sig-cluster-federation @mwielgus

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36463)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Adding P1 label for the corresponding label on the issue

File: federation/pkg/federation-controller/secret/secret_controller_test.go [hunk 1]
```diff
@@ -127,15 +127,21 @@ func TestSecretController(t *testing.T) {
 	assert.Equal(t, secret1.Namespace, updatedSecret.Namespace)
 	assert.True(t, secretsEqual(secret1, *updatedSecret),
 		fmt.Sprintf("expected: %v, actual: %v", secret1, *updatedSecret))
+	// Wait for the secret to be updated in the informer store.
+	err = WaitForSecretStoreUpdate(
+		secretController.secretFederatedInformer.GetTargetStore(),
+		cluster1.Name, types.NamespacedName{Namespace: secret1.Namespace, Name: secret1.Name}.String(),
+		updatedSecret, wait.ForeverTestTimeout)
```
Comment (mwielgus) [inline federation/pkg/federation-controller/secret/secret_controller_test.go]: I guess we could stop this earlier than Forever.

Comment (nikhiljindal) [inline federation/pkg/federation-controller/secret/secret_controller_test.go]: I will prefer keeping this as is. Dont want to introduce more flakiness because of not enough wait :)

Comment (dims) [inline federation/pkg/federation-controller/secret/secret_controller_test.go]: looks like `var ForeverTestTimeout = time.Second * 30` so it's not that really forever :)

**Comment by dims** [comment]
LGTM if all the tests pass 👍

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this
namespace controller failed, secret controller passed :)

**Comment by dims** [comment]
LOL win some lose some :)

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/issues/36351 is tracking the namespace controller failures.
Looking at the test grid, it seems to be failing once every 10-15 runs: https://k8s-testgrid.appspot.com/k8s#test-go

**Comment by nikhiljindal** [comment]
GCE cluster failed to come up with `Failed to setup provider config: Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError`. Retrying as its unrelated.

@k8s-bot cvm gce e2e test this

**Comment by nikhiljindal** [comment]
Adding lgtm as per comment above. unit tests passed

**Comment by mwielgus** [comment]
LGTM to make tests greener, I will try to find more generic fix - other controllers may be affected as well.

**Comment by mwielgus** [comment]
I was unable to reproduce the issue on my laptop (without the fix).
```
for i in `seq 100`; do godep go test --race; done
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.812s
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.837s
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.759s
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.905s
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.805s
PASS
ok  	k8s.io/kubernetes/federation/pkg/federation-controller/secret	2.782s
[...]
```

However I agree that there can be a problem in this place.  It seems that sometimes we are starting the modify before add is fully completed and as a result the expected modify is in fact another add. I will add a similar fix to other controllers tomorrow as they are equally affected.

**Comment by nikhiljindal** [comment]
I was running it with `make test KUBE_GOFLAGS="-race" WHAT='federation/pkg/federation-controller/secret/'` which should be the same. I was able to repro the failure around 1 in 4 or 5 times.
