### PR TITLE
Don't run cloud IPAM controller when cloud provider is not enabled

### LINKED ISSUE #114556: NodeIPAM CloudAllocator Type on KCM panics when using external cloud provider
Cloud-providers started to move out of tree its controller, but they share some functionalities, one of them is the NodeIPAM controller.

There is a type that is GCE specific, the `CloudAllocator` type.

If this type is used, but no configuration for GCE is passed, the kcm panics.

This can be observed in the following job: https://testgrid.k8s.io/sig-testing-canaries#ingress-gce-e2e-canary

> I1217 13:13:43.823361       9 flags.go:64] FLAG: --cidr-allocator-type="CloudAllocator"

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x28a2621]

goroutine 205 [running]:
k8s.io/kubernetes/pkg/controller/nodeipam/ipam.NewCloudCIDRAllocator({0x51dd7f0, 0xc000f2c000}, {0x0, 0x0?}, {0x5194a40, 0xc000dffd40})
	pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go:98 +0x5e1
k8s.io/kubernetes/pkg/controller/nodeipam/ipam.New({0x51dd7f0, 0xc000f2c000}, {0x0, 0x0}, {0x5194a40, 0xc000dffd40}, {0x0, 0x0}, {0x7fffae6b9d76, 0xe}, ...)
	pkg/controller/nodeipam/ipam/cidr_allocator.go:138 +0xed
k8s.io/kubernetes/pkg/controller/nodeipam.NewNodeIpamController({0x5194a40, 0xc000dffd40}, {0x0, 0x0}, {0x0?, 0x0}, {0x51dd7f0, 0xc000f2c000}, {0xc000700ea0, 0x1, ...}, ...)
	pkg/controller/nodeipam/node_ipam_controller.go:134 +0x665
k8s.io/kubernetes/cmd/kube-controller-manager/app.startNodeIpamController({_, _}, {{0x51b8a40, 0xc000087e60}, {0x51d33d0, 0xc00016ac40}, {0x5196e30, 0xc000c23120}, {{{0x0, 0x0}, ...}, ...}, ...})
	cmd/kube-controller-manager/app/core.go:152 +0x666
k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers({_, _}, {{0x51b8a40, 0xc000087e60}, {0x51d33d0, 0xc00016ac40}, {0x5196e30, 0xc000c23120}, {{{0x0, 0x0}, ...}, ...}, ...}, ...)
	cmd/kube-controller-manager/app/controllermanager.go:594 +0x4e4
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1({0x51b04b0, 0xc0005d4a80}, 0xc00031a570?, 0x4b71a98)
	cmd/kube-controller-manager/app/controllermanager.go:231 +0x26e
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func3({0x51b04b0?, 0xc0005d4a80?})
	cmd/kube-controller-manager/app/controllermanager.go:291 +0xe3
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
```

The question is, should this type be removed or a noop in KCM?

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>

#### What type of PR is this?

/kind bug

If the allocator type for nodeipam controller is `CloudAllocator` and cloud provider is not enabled (either --cloud-provider is not set OR --cloud-provider=external), then kube-controller-manager should not run nodeipam controller.  

#### What this PR does / why we need it:

Fixes https://github.com/kubernetes/kubernetes/issues/114556

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kube-controller-manager will not run nodeipam controller when allocator type is CloudAllocator and the cloud provider is not enabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/cloud-controller-manager/nodeipamcontroller.go [hunk 1]
```diff
@@ -75,6 +75,12 @@ func startNodeIpamController(initContext app.ControllerInitContext, ccmConfig *c
 		return nil, false, nil
 	}
 
+	// Cannot run cloud ipam controller if cloud provider is nil (not set or 'external')
+	if cloud == nil && ccmConfig.ComponentConfig.KubeCloudShared.CIDRAllocatorType == string(ipam.CloudAllocatorType) {
+		klog.Warningf("--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured")
+		return nil, false, nil
```
Comment (andrewsykim) [inline cmd/cloud-controller-manager/nodeipamcontroller.go:81]: We can also error here and have kube-controller-manager exit, instead of just skipping the controller.

Comment (aojea) [reply cmd/cloud-controller-manager/nodeipamcontroller.go:81]: I'm not familiar with this area, why `cloud-controller-manager` should not have a cloud provider, is not that implicit?

Comment (andrewsykim) [reply cmd/cloud-controller-manager/nodeipamcontroller.go:81]: Yeah technically speaking we don't _really_ need this check in cloud-controller-manager, it should always be set -- but I added it here for consistency with kube-controller-manager

File: cmd/kube-controller-manager/app/core.go [hunk 2]
```diff
@@ -105,6 +105,12 @@ func startNodeIpamController(ctx context.Context, controllerContext ControllerCo
 		return nil, false, nil
 	}
 
+	// Cannot run cloud ipam controller if cloud provider is nil (not set or 'external')
+	if controllerContext.Cloud == nil && controllerContext.ComponentConfig.KubeCloudShared.CIDRAllocatorType == string(ipam.CloudAllocatorType) {
+		klog.Warningf("--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured")
```
Comment (jprzychodzen) [inline cmd/kube-controller-manager/app/core.go:110]: I see that in https://github.com/kubernetes/kubernetes/issues/114556#issuecomment-1358736436 you are mentioning that we can consider quitting KCM in case of misconfiguratuion. I think this is a great idea.

That would be a clear signal that KCM is misconfigured, with an explanation what configuration should be used. It seems a better solution than providing half working cluster that will generate operational load when deployed.

Comment (andrewsykim) [reply cmd/kube-controller-manager/app/core.go]: agreed -- I updated to error instead of just warning

File: cmd/cloud-controller-manager/nodeipamcontroller.go [hunk 3]
```diff
@@ -75,6 +75,11 @@ func startNodeIpamController(initContext app.ControllerInitContext, ccmConfig *c
 		return nil, false, nil
 	}
 
+	// Cannot run cloud ipam controller if cloud provider is nil (--cloud-provider not set or set to 'external')
+	if cloud == nil && ccmConfig.ComponentConfig.KubeCloudShared.CIDRAllocatorType == string(ipam.CloudAllocatorType) {
+		return nil, false, errors.New("--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured")
```
Comment (liggitt) [inline cmd/cloud-controller-manager/nodeipamcontroller.go:80]: can CIDRAllocatorType be explicitly set to an empty string or `None` or `External` or something that indicates the caller knows/intends for this process to not handle allocating these? if so, should we include those details in the error? same question in k-c-m

Comment (andrewsykim) [reply cmd/cloud-controller-manager/nodeipamcontroller.go:80]: > can CIDRAllocatorType be explicitly set to an empty string or None or External or something that indicates the caller knows/intends for this process to not handle allocating these?

I don't think so -- the current valid values are: `RangeAllocator` (default), `MultiCIDRRangeAllocator`, `CloudAllocator`, `IPAMFromCluster` (legacy) and `IPAMFromCloud` (legacy). You can opt-out of this controller entirely, by unsetting `--allocate-node-cidrs` though, are you suggesting we include a note here about using `--allocate-node-cidrs` to opt out of this controller entirely?

Comment (liggitt) [reply cmd/cloud-controller-manager/nodeipamcontroller.go:80]: > You can opt-out of this controller entirely, by unsetting --allocate-node-cidrs though

ah, ok... so this error is only presented to people invoking the binary and explicitly setting `--allocate-node-cidrs` AND setting `--cidr-allocator-type=CloudAllocator`, both of which are non-default settings?

Comment (aojea) [reply cmd/cloud-controller-manager/nodeipamcontroller.go:80]: yep 

https://github.com/kubernetes/kubernetes/blob/75e39073a3ecd975eabd8bdb4f1fff84ebad1dce/cmd/controller-manager/app/options/kubecloudshared.go#L57-L58


and not specificying the GCE config
