### PR TITLE
Fix a potential goroutine leak

### LINKED ISSUE #114070: Goroutine leak in EtcdMigrateServer
### What happened?
It's at [migrate_server.go](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/migrate/migrate_server.go) line 111

When the server stopped before timeout, the first goroutine will be block on  `timeout <- true` because the receiver in the second goroutine is not exist. 
Changing `timeout` to a buffered one may fix it. #114071 
```
	stopped := make(chan bool)
	timedout := make(chan bool)
	go func() {                                   // first goroutine
		time.Sleep(gracefulWait)
		timedout <- true                // blocked
	}()
	go func() {                                   // second goroutine
		select {
		case <-stopped:
			return                          // return here
		case <-timedout:
			klog.Infof("etcd server has not terminated gracefully after %s, killing it.", gracefulWait)
			r.cmd.Process.Kill()
			return
		}
	}()
	err = r.cmd.Wait()
	stopped <- true
```

### What did you expect to happen?

no goroutine leaks

### How can we reproduce it (as minimally and precisely as possible)?

run related test with leak checker

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
dev
</details>

### Cloud provider

<details>
unknown
</details>

### OS version

<details>
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Mskxn**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When the server stopped before timeout, the `stopped <-true` will be executed and in the select block, the first case will be chosen. This will lead to a hanging goroutine at line 111 because no receiver of `timeout` is left. Changing the `timeout` chan to a buffered one can fix it.
#### Which issue(s) this PR fixes:

Fixes #114070

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
can you add a test demonstrating the problem?

**Comment by Mskxn** [comment]
Actually, it is very similar to #102637. I think `TestMigrate` in integration_test.go can trigger it with a leak checker like [goleak](https://github.com/uber-go/goleak) which can detect partial goroutine leak

**Comment by aojea** [comment]
/ok-to-test
/lgmt
/approve

Thanks

**Comment by aojea** [comment]
> Actually, it is very similar to #102637. I think `TestMigrate` in integration_test.go can trigger it with a leak checker like [goleak](https://github.com/uber-go/goleak) which can detect partial goroutine leak

yep, thanks for the clarification, I should have paid more attention

File: cluster/images/etcd/migrate/migrate_server.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ func (r *EtcdMigrateServer) Stop() error {
 	}
 	gracefulWait := time.Minute * 2
 	stopped := make(chan bool)
-	timedout := make(chan bool)
+	timedout := make(chan bool, 1)
```
Comment (wojtek-t) [inline cluster/images/etcd/migrate/migrate_server.go:108]: Instead of that, instead of sending an item to a channel, we should simply close it.

Comment (Mskxn) [reply cluster/images/etcd/migrate/migrate_server.go]: fixed

File: cluster/images/etcd/migrate/migrate_server.go [hunk 2]
```diff
@@ -108,7 +108,7 @@ func (r *EtcdMigrateServer) Stop() error {
 	timedout := make(chan bool)
 	go func() {
 		time.Sleep(gracefulWait)
-		timedout <- true
+		close(timedout)
```
Comment (wojtek-t) [inline cluster/images/etcd/migrate/migrate_server.go:111]: Given you're touching it, can you please also fix line 72:
https://github.com/kubernetes/kubernetes/blob/96360055842db86ff883993824a9b9bd0563b58e/cluster/images/etcd/migrate/migrate_server.go#L72

?

Comment (Mskxn) [reply cluster/images/etcd/migrate/migrate_server.go:111]: done

**Comment by wojtek-t** [comment]
@Mskxn - please squash commits, one squashed, this LGTM

**Comment by Mskxn** [comment]
squashed and PTAL.
