### PR TITLE
deflake intergation test: TestEndpointHandlers

### LINKED ISSUE #130064: [Flaking-Test] [sig-scheduling] test/integration/scheduler/serving.serving
### Which jobs are flaking?

sig-release-master-blocking
- integration-master

### Which tests are flaking?

`k8s.io/kubernetes/test/integration/scheduler/serving.serving`  `TestEndpointHandlers`
[Triage](https://storage.googleapis.com/k8s-triage/index.html?text=TestEndpointHandlers&test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fscheduler%2Fserving.serving&xjob=e2e-kops)
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1887928819386421248

### Since when has it been flaking?

[1/31/2025, 7:16:04 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1885142155438067712)
[2/5/2025, 8:48:19 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1886977308703592448)
[2/4/2025, 12:56:17 PM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1886677329376186368)
[2/7/2025, 11:49:11 PM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1887928819386421248)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
{Failed  === RUN   TestEndpointHandlers//readyz_with_sched-handler-sync
        	apiVersion: kubescheduler.config.k8s.io/v1
        	clientConnection:
        	  acceptContentTypes: ""
        	  burst: 100
        	  contentType: application/vnd.kubernetes.protobuf
        	  kubeconfig: /tmp/kubeconfig174648122
        	  qps: 50
        	enableContentionProfiling: true
        	enableProfiling: true
        	kind: KubeSchedulerConfiguration
        	leaderElection:
        	  leaderElect: false
        	  leaseDuration: 15s
        	  renewDeadline: 10s
        	  resourceLock: leases
        	  resourceName: kube-scheduler
        	  resourceNamespace: kube-system
        	  retryPeriod: 2s
        	parallelism: 16
        	percentageOfNodesToScore: 0
        	podInitialBackoffSeconds: 1
        	podMaxBackoffSeconds: 10
        	profiles:
        	- pluginConfig:
        	  - args:
        	      apiVersion: kubescheduler.config.k8s.io/v1
        	      kind: DefaultPreemptionArgs
        	      minCandidateNodesAbsolute: 100
        	      minCandidateNodesPercentage: 10
        	    name: DefaultPreemption
        	  ------
        	    preEnqueue: {}
        	    preFilter: {}
        	    preScore: {}
        	    queueSort: {}
        	    reserve: {}
        	    score: {}
        	  schedulerName: default-scheduler
         >
    endpoints_test.go:179: expected http 200 at /readyz/sched-handler-sync of component, got: 500 "internal server error: waiting for handlers to sync\n"
--- FAIL: TestEndpointHandlers//readyz_with_sched-handler-sync (1.45s)

=== RUN   TestEndpointHandlers
    testserver.go:591: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing"
    testserver.go:411: runtime-config=map[api/all:true]
    testserver.go:412: Starting kube-apiserver on port 34701...
    testserver.go:447: Waiting for /healthz to be ok...
[-]poststarthook/start-apiextensions-controllers failed: not finished
[-]poststarthook/crd-informer-synced failed: not finished
[-]poststarthook/start-service-ip-repair-controllers failed: not finished
-------
-------
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
[-]poststarthook/priority-and-fairness-config-producer failed: not finished
  	Type:               "Dangling",
- 	Status:             "",
+ 	Status:             "False",
- 	LastTransitionTime: v1.Time{},
+ 	LastTransitionTime: v1.Time{Time: s"2025-02-07 19:16:00.422094455 +0000 UTC m=+2.981502501"},
- 	Reason:             "",
+ 	Reason:             "Found",
- 	Message:            "",
+ 	Message:            `This FlowSchema references the PriorityLevelConfiguration object named "system" and it exists`,
  }
--------
---------
  	Type:               "Dangling",
- 	Status:             "",
+ 	Status:             "False",
- 	LastTransitionTime: v1.Time{},
+ 	LastTransitionTime: v1.Time{Time: s"2025-02-07 19:16:00.555912642 +0000 UTC m=+3.115320528"},
- 	Reason:             "",
+ 	Reason:             "Found",
- 	Message:            "",
+ 	Message:            `This FlowSchema references the PriorityLevelConfiguration object named "catch-all" and it exists`,
  }
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
---
---
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
--- FAIL: TestEndpointHandlers (19.09s)
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig scheduling

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

image

ref: https://storage.googleapis.com/k8s-triage/index.html?text=TestEndpointHandlers

image
ref: blob:https://prow.k8s.io/77b55f0a-3738-4c05-840d-5aa237a67c8f

image

#### Which issue(s) this PR fixes:

Fixes #130064

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/scheduler/serving/endpoints_test.go [hunk 1]
```diff
@@ -175,29 +176,44 @@ func TestEndpointHandlers(t *testing.T) {
 					req.Header.Set(k, v)
 				}
 			}
-			r, err := client.Do(req)
-			if err != nil {
-				t.Fatalf("failed to GET %s from component: %v", tt.path, err)
-			}
 
-			body, err := io.ReadAll(r.Body)
+			err = retry.OnError(
```
Comment (aojea) [inline test/integration/scheduler/serving/endpoints_test.go:180]: it feels a better fix to expect that the process under test is ready after calling `kubeschedulertesting.StartTestServer(` and not have to retry in the test


https://github.com/kubernetes/kubernetes/blob/30469e180361d7da07b0fee6d47c776fa2cf3e86/cmd/kube-scheduler/app/testing/testserver.go#L159-L164

Comment (carlory) [reply test/integration/scheduler/serving/endpoints_test.go:180]: @aojea but the test case `/readyz with broken apiserver` expect the readyz endpoint to return 500 when it is started with a broken apiserver. If I add a check for readyz in the function, we have to change the func signature to accept a new parameter which is used to control whether to check for readyz or not.

Comment (carlory) [reply test/integration/scheduler/serving/endpoints_test.go:180]: but the test case `/readyz with broken apiserver` expect the readyz endpoint to return 500 when it is started with a broken apiserver. If I add a check for readyz in the function, we have to change the func signature to accept a new parameter which is used to control whether to check for readyz or not.

Comment (aojea) [reply test/integration/scheduler/serving/endpoints_test.go:180]: I see, sorry, didn;t read the test in detail , so with this change, do we only retry when the config is not broken and the error is `handlers are not fully synchronized`?

is the case we only need to retry on ready endpoints only? if affirmative, we should make that part of the retry function

Comment (carlory) [reply test/integration/scheduler/serving/endpoints_test.go:180]: updated.

**Review by sanposhiho — COMMENTED** [review]
/assign @kerthcet 

Can you take a look, @kerthcet. This might be something that we discussed before.

**Review by hashim21223445 — APPROVED** [review]

**Review by kerthcet — COMMENTED** [review]
LGTM
/approve
