### PR TITLE
leader election lock based on scheduler name

### LINKED ISSUE #39032: Running multiple-schedulers with leader-elect
**Kubernetes version** (use `kubectl version`):
```
$kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): CoreOS

**What happened**:
Running through the following example (http://kubernetes.io/docs/admin/kube-scheduler/) you cannot start a second scheduler without disabling leader-elect if the default scheduler has leader-elect enabled (default). I think the lock needs to configurable based on scheduler name.

**What you expected to happen**:
You can run subsequent schedulers with leader-elect using a separate lock.

**How to reproduce it** (as minimally and precisely as possible):
Run through -- http://kubernetes.io/docs/admin/kube-scheduler/

Yields
```
$ kubectl logs my-scheduler-3263660448-r8xfq   -n kube-system -f
W1220 18:09:43.712076       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1220 18:09:43.760718       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:47.214644       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:49.939585       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
I1220 18:09:53.178888       1 leaderelection.go:247] lock is held by ip-10-0-10-11.us-west-2.compute.internal and has not yet expired
```

Adding leader-elect=false to subsequent kube-scheduler gets round this at the moment
```
$kubectl logs my-scheduler-3263660448-wr6bc   -n kube-system -fem
W1220 18:11:13.475504       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1220 18:11:13.519262       1 event.go:217] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"annotation-second-scheduler", UID:"28908cea-c6df-11e6-b886-06f3d2138bbf", APIVersion:"v1", ResourceVersion:"977630", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods
```

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by wanghaoran1988**
**What this PR does / why we need it**:
This pr changed the leader election lock based on scheduler name.
**Which issue this PR fixes** :
fixes #39032

**Special notes for your reviewer**:

**Release note**:
```
[scheduling]Fix a bug for multiple-schedulers that you cannot start a second scheduler without disabling leader-elect if the default scheduler has leader-elect enabled(default). We changed the leader election lock based on scheduler name.
```

### CODE REVIEW

File: plugin/cmd/kube-scheduler/app/server.go [hunk 1]
```diff
@@ -114,7 +114,7 @@ func Run(s *options.SchedulerServer) error {
 	rl := &resourcelock.EndpointsLock{
 		EndpointsMeta: metav1.ObjectMeta{
 			Namespace: "kube-system",
-			Name:      "kube-scheduler",
+			Name:      s.SchedulerName,
```
Comment (k82cn) [inline plugin/cmd/kube-scheduler/app/server.go]: prefer to `"kube-scheduler-" + s.SchedulerName`

**Comment by k82cn** [comment]
@k8s-bot ok to test

File: plugin/cmd/kube-scheduler/app/server.go (hunk 1 above)
Comment (timothysc) [inline plugin/cmd/kube-scheduler/app/server.go]: +1

**Comment by timothysc** [comment]
@wanghaoran1988 please address comment and re-bazel and we can get the change in.

**Comment by wanghaoran1988** [comment]
@timothysc @k82cn Comments addressed, and I am already passed `hack/verify-bazel.sh` locally, not clear why it failed, could you point me what should I do?

**Comment by ravilr** [comment]
@timothysc IMO, this change warrants a release note. because, in HA setups with multiple instances of scheduler running and where upgrades are rolled out in a rolling manner, with this change after the upgrade, the new upgraded instance might acquire the lock while one of the old instances still holding the lock with old endpoint name. So, one should stop all old instances of scheduler before rolling out this change?

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-scheduling-pr-reviews

**Comment by timothysc** [comment]
@wanghaoran1988 please add a release note.

**Comment by wanghaoran1988** [comment]
@timothysc Release note added

**Comment by k82cn** [comment]
@wanghaoran1988 , please try /release-note command :).

**Comment by wanghaoran1988** [comment]
/release-note [scheduling]Fix a bug for multiple-schedulers that you cannot start a second scheduler without disabling leader-elect if the default scheduler has leader-elect enabled (default). We changed the leader election lock based on scheduler name.

**Comment by timothysc** [comment]
@k8s-bot test this #IGNORE

**Comment by jayunit100** [comment]
This might be why the scheduler_perf tests failed and went into lock frenzy when i tried to start them w/ a scheduling server

**Comment by wanghaoran1988** [comment]
I found that the scheduler cannot get the lock:
```
tail -f /var/log/kube-scheduler.log
E0313 16:51:57.954959       5 leaderelection.go:229] error retrieving resource lock kube-system/kube-scheduler-default-scheduler: User "system:kube-scheduler" cannot get endpoints in the n
amespace "kube-system". (get endpoints kube-scheduler-default-scheduler)
I0313 16:51:57.954984       5 leaderelection.go:185] failed to acquire lease kube-system/kube-scheduler-default-scheduler
E0313 16:52:01.242773       5 leaderelection.go:229] error retrieving resource lock kube-system/kube-scheduler-default-scheduler: User "system:kube-scheduler" cannot get endpoints in the n
amespace "kube-system". (get endpoints kube-scheduler-default-scheduler)
```

**Comment by wanghaoran1988** [comment]
Connection refused to the api server, will debug further tomorrow ...
```
I0313 16:46:44.720309       5 reflector.go:236] Listing and watching *v1.Node from k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:70
E0313 16:46:44.723957       5 reflector.go:201] k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:70: Failed to list *v1.Node: Get https://localhost:44
3/api/v1/nodes?resourceVersion=0: dial tcp [::1]:443: getsockopt: connection refused
E0313 16:46:44.724009       5 leaderelection.go:229] error retrieving resource lock kube-system/kube-scheduler-default-scheduler: Get https://localhost:443/api/v1/namespaces/kube-system/en
dpoints/kube-scheduler-default-scheduler: dial tcp [::1]:443: getsockopt: connection refused
I0313 16:46:44.724023       5 leaderelection.go:185] failed to acquire lease kube-system/kube-scheduler-default-scheduler
E0313 16:46:44.724060       5 reflector.go:201] k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:451: Failed to list *v1.Pod: Get https://localhost:443/api/v1/pods?fieldSelector=s
pec.nodeName%3D%2Cstatus.phase%21%3DFailed%2Cstatus.phase%21%3DSucceeded&resourceVersion=0: dial tcp [::1]:443: getsockopt: connection refused
```

**Comment by wanghaoran1988** [comment]
@timothysc @k82cn I found that the cluster role [system:kube-scheduler](https://github.com/kubernetes/kubernetes/blob/f7c07a121d2afadde7aa15b12a9d02858b30a0a9/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L345) are using the hard code "kube-scheduler" as the permitted sub resource of endpoints, we need update the sub resource to "kube-scheduler-default-scheduler"

**Comment by k82cn** [comment]
@k8s-bot test this #IGNORE

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go [hunk 2]
```diff
@@ -342,7 +342,7 @@ func ClusterRoles() []rbac.ClusterRole {
 				// this is for leaderlease access
 				// TODO: scope this to the kube-system namespace
 				rbac.NewRule("create").Groups(legacyGroup).Resources("endpoints").RuleOrDie(),
-				rbac.NewRule("get", "update", "patch", "delete").Groups(legacyGroup).Resources("endpoints").Names("kube-scheduler").RuleOrDie(),
+				rbac.NewRule("get", "update", "patch", "delete").Groups(legacyGroup).Resources("endpoints").Names("kube-scheduler-default-scheduler").RuleOrDie(),
```
Comment (timothysc) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: the name is redundant.  

Why wouldn't we change the pattern to: "kube-s.SchedulerName-scheduler"  - 
"kube-default-scheduler"

Comment (wanghaoran1988) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: @timothysc +1 for the new pattern, will update

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go [hunk 3]
```diff
@@ -342,7 +342,7 @@ func ClusterRoles() []rbac.ClusterRole {
 				// this is for leaderlease access
 				// TODO: scope this to the kube-system namespace
 				rbac.NewRule("create").Groups(legacyGroup).Resources("endpoints").RuleOrDie(),
-				rbac.NewRule("get", "update", "patch", "delete").Groups(legacyGroup).Resources("endpoints").Names("kube-scheduler").RuleOrDie(),
+				rbac.NewRule("get", "update", "patch", "delete").Groups(legacyGroup).Resources("endpoints").Names("kube-default-scheduler").RuleOrDie(),
```
Comment (liggitt) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: not backwards compatible with old schedulers

File: plugin/cmd/kube-scheduler/app/server.go [hunk 4]
```diff
@@ -114,7 +114,7 @@ func Run(s *options.SchedulerServer) error {
 	rl := &resourcelock.EndpointsLock{
 		EndpointsMeta: metav1.ObjectMeta{
 			Namespace: "kube-system",
-			Name:      "kube-scheduler",
+			Name:      "kube-" + s.SchedulerName,
```
Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: this also means an old a new version of the scheduler can both acquire a lock simultaneously

Comment (timothysc) [inline plugin/cmd/kube-scheduler/app/server.go]: They upgrades roll here... There should not be an old + new.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go (hunk 3 above)
Comment (timothysc) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: Is there a use case of mixed schedulers?

File: plugin/cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: if we're not running multiple instances of the scheduler, then what's the point of the lock? when upgrading, we take down all instances of the old scheduler before bringing one of the new ones up?

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go (hunk 3 above)
Comment (liggitt) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: does scheduler upgrade before master or after?

Comment (timothysc) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: shutdown scheduler + cm
shutdown apiserver 
start new apiserver 
start new scheduler + cm

Comment (liggitt) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: this just seems like change with little benefit... running schedulers with different names still won't work. it would make more sense to me to default to kube-system/kube-scheduler and put the namespace and name under the user's control

File: plugin/cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (timothysc) [inline plugin/cmd/kube-scheduler/app/server.go]: > when upgrading, we take down all instances of the old scheduler before bringing one of the new ones up? 

It's not a hard requirement to keep the CM + Sched up.  We just need to be certain that user expectations are set.

Comment (timothysc) [inline plugin/cmd/kube-scheduler/app/server.go]: /cc @justinsb are you enabling RBAC by default?

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go (hunk 3 above)
Comment (timothysc) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: He'd have to plumb through the lock through to a command-line arg and default it.  But we should also then update the multi-scheduler docs around input options and RBAC rules.

File: plugin/cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (wanghaoran1988) [inline plugin/cmd/kube-scheduler/app/server.go]: @timothysc @liggitt How about this: change the default scheduler name to "kube-scheduler" instead of "default-scheduler", then use the s.schedulerName as the lock, it will backwards compatible with old schedulers (if there is a new+ old scenario), also can support multi scheduler.

Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: +1 to leaving the default lock object the same (by whatever mechanism)

not sure about using the scheduler name as the lock object's name... there are valid annotation names that are not valid endpoint names, and I wouldn't want to accidentally stomp an existing endpoint. I still think letting them pick the endpoint to lock on (both namespace and name) is valuable.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go (hunk 3 above)
Comment (k82cn) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go]: kube-scheduler's not namespace level, multi-scheduler also uses `schedulerName` instead of namespace; so we're using different name :). But unfortunately, there's not feature to guarantee unique name (e.g. admission).

File: plugin/cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (smarterclayton) [inline plugin/cmd/kube-scheduler/app/server.go]: I want to point out that we are going to have to move away from endpoints as the "thing to lock on" to a different object, or a more restricted endpoint, that doesn't make the cluster unsafe.

There's no reason that you have to give a relatively low privileged things write access to its endpoints in order to do locking, or let it potentially alter other aspects of endpoints.

Comment (smarterclayton) [inline plugin/cmd/kube-scheduler/app/server.go]: Also, having to do this sort of manual permissions is tedious - I don't think we've got a good handle on how to safely grant this permission to a set of pods yet.

**Comment by davidopp** [comment]
I'm marking this as non-release-blocker. We can address this in 1.6.1 if it doesn't get into 1.6.

File: plugin/cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (k82cn) [inline plugin/cmd/kube-scheduler/app/server.go]: > +1 to leaving the default lock object the same (by whatever mechanism)

I think we'll deprecate kube-scheduler after several releases. We also need to document it.

**Comment by timothysc** [comment]
@wanghaoran1988 plumbing through 'lock-namespace' and 'lock-name' are the most general purpose way to solve this.  https://kubernetes.io/docs/admin/multiple-schedulers/ would also need to be updated to outline the params + RBAC changes needed to support.

**Comment by wanghaoran1988** [comment]
@k8s-bot unit test this

File: plugin/pkg/scheduler/factory/factory_test.go [hunk 5]
```diff
@@ -324,7 +324,7 @@ func TestResponsibleForPod(t *testing.T) {
 		v1.DefaultHardPodAffinitySymmetricWeight,
 	)
 	// scheduler annotations to be tested
-	schedulerFitsDefault := "default-scheduler"
+	schedulerFitsDefault := "kube-scheduler"
```
Comment (timothysc) [inline plugin/pkg/scheduler/factory/factory_test.go]: Is there a reason you don't reference the const in a couple of locations?

**Review by timothysc — CHANGES_REQUESTED** [review]
You still need to plumb this all the way through to the command line.

**Comment by wanghaoran1988** [comment]
@timothysc PTAL

File: pkg/api/types.go [hunk 6]
```diff
@@ -3808,8 +3808,8 @@ type RangeAllocation struct {
 }
 
 const (
-	// "default-scheduler" is the name of default scheduler.
-	DefaultSchedulerName = "default-scheduler"
+	// "kube-scheduler" is the name of default scheduler.
+	DefaultSchedulerName = "kube-scheduler"
```
Comment (liggitt) [inline pkg/api/types.go]: are there existing scheduler annotations or fields referencing "default-scheduler" this will break?

File: plugin/cmd/kube-scheduler/app/server.go (hunk 1 above)
Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: I still think it is unexpected the scheduler name they pick will be used as the leader lock endpoint. What happens if they have a name that is invalid as an endpoint object name (I'd sort of expect them to have used a namespaced custom scheduler name like `acme.com/fancy-scheduler`)?

File: pkg/api/types.go (hunk 6 above)
Comment (wanghaoran1988) [inline pkg/api/types.go]: @liggitt Thanks for reminder this, I think it will break.

File: plugin/cmd/kube-scheduler/app/server.go (hunk 1 above)
Comment (wanghaoran1988) [inline plugin/cmd/kube-scheduler/app/server.go]: @liggitt We can do some validation for the scheduler name I think.

Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: I would encourage namespaced names like that to avoid collisions... that's why I think making that serve double-duty as the endpoint lock object name is a bad idea...

Comment (wanghaoran1988) [inline plugin/cmd/kube-scheduler/app/server.go]: @liggitt Do you have any good  ideas? I almost exhausted on this issue, change the default scheduler name or change the lock location all have compatible problem as you said, 
how about this:
Don't change the scheduler name, don't change the default lock endpint If it's default scheduler, and if it's custom scheduler, we can create a new lock endpoint, but we need fig out what the lock object name should be.

Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: default the lock object to `kube-scheduler` in the `kube-system` namespace, let them pick a different namespace and/or name for the lock object

Comment (liggitt) [inline plugin/cmd/kube-scheduler/app/server.go]: e.g. make LockObjectNamespace and LockObjectName fields in options.SchedulerServer

Comment (wanghaoran1988) [inline plugin/cmd/kube-scheduler/app/server.go]: @liggitt Thanks for your suggestions, will add the options if @timothysc @k82cn like that. :)

Comment (timothysc) [inline plugin/cmd/kube-scheduler/app/server.go]: e.g. make LockObjectNamespace and LockObjectName fields in options.SchedulerServer ~= previous comment - https://github.com/kubernetes/kubernetes/pull/42961#issuecomment-286753197 so yeah +1 ;-)

**Comment by wanghaoran1988** [comment]
@timothysc @liggitt Would you mind take a look again, I updated it with the new way.

**Comment by enisoc** [comment]
I'm cleaning out the milestone since we're coming up on the cut. This is already marked as non-release-blocker.

File: plugin/cmd/kube-scheduler/app/options/options.go [hunk 7]
```diff
@@ -72,6 +72,8 @@ func (s *SchedulerServer) AddFlags(fs *pflag.FlagSet) {
 	fs.Float32Var(&s.KubeAPIQPS, "kube-api-qps", s.KubeAPIQPS, "QPS to use while talking with kubernetes apiserver")
 	fs.Int32Var(&s.KubeAPIBurst, "kube-api-burst", s.KubeAPIBurst, "Burst to use while talking with kubernetes apiserver")
 	fs.StringVar(&s.SchedulerName, "scheduler-name", s.SchedulerName, "Name of the scheduler, used to select which pods will be processed by this scheduler, based on pod's \"spec.SchedulerName\".")
+	fs.StringVar(&s.LockObjectNamespace, "lock-object-namespace", s.LockObjectNamespace, "Define the namespace of the lock object")
+	fs.StringVar(&s.LockObjectName, "lock-object-name", s.LockObjectName, "Define the name of the lock object")
```
Comment (k82cn) [inline plugin/cmd/kube-scheduler/app/options/options.go]: The default value from cli should be `DefaultLockObjectName `.

File: pkg/api/v1/types.go [hunk 8]
```diff
@@ -4377,4 +4377,7 @@ const (
 	// When the --failure-domains scheduler flag is not specified,
 	// DefaultFailureDomains defines the set of label keys used when TopologyKey is empty in PreferredDuringScheduling anti-affinity.
 	DefaultFailureDomains string = metav1.LabelHostname + "," + metav1.LabelZoneFailureDomain + "," + metav1.LabelZoneRegion
+
+	// "kube-scheduler" is the default lock object name
+	DefaultLockObjectName = "kube-scheduler"
```
Comment (k82cn) [inline pkg/api/v1/types.go]: Where's `DefaultLockObjectNamespace`?

**Review by k82cn — COMMENTED** [review]
please put generated codes in different commit.

File: pkg/api/v1/types.go (hunk 8 above)
Comment (wanghaoran1988) [inline pkg/api/v1/types.go]: @k82cn I am using api.NamespaceSystem, correct me if I am wrong :)

Comment (k82cn) [inline pkg/api/v1/types.go]: prefer to `DefaultLockObjectName = api.NamespaceSystem`

File: plugin/cmd/kube-scheduler/app/options/options.go (hunk 7 above)
Comment (wanghaoran1988) [inline plugin/cmd/kube-scheduler/app/options/options.go]: @k82cn Addressed

File: pkg/api/v1/types.go (hunk 8 above)
Comment (wanghaoran1988) [inline pkg/api/v1/types.go]: @k82cn Done

**Comment by wanghaoran1988** [comment]
@k8s-bot gci gce e2e test this

**Review by timothysc — APPROVED** [review]

File: pkg/api/types.go [hunk 9]
```diff
@@ -3822,4 +3822,10 @@ const (
 	// When the --failure-domains scheduler flag is not specified,
 	// DefaultFailureDomains defines the set of label keys used when TopologyKey is empty in PreferredDuringScheduling anti-affinity.
 	DefaultFailureDomains string = metav1.LabelHostname + "," + metav1.LabelZoneFailureDomain + "," + metav1.LabelZoneRegion
+
+	// "kube-system" is the default lock object namespace
+	DefaultLockObjectNamespace string = NamespaceSystem
+
+	// "kube-scheduler" is the default lock object name
+	DefaultLockObjectName = "kube-scheduler"
```
Comment (liggitt) [inline pkg/api/types.go]: if this is exported from the API package, it needs a name that indicates it is for the scheduler

Comment (liggitt) [inline pkg/api/types.go]: these really seems like they belong in the component config package, with names that scope them to the scheduler

Comment (wanghaoran1988) [inline pkg/api/types.go]: @liggitt Does `SchedulerDefaultLockObjectNamespace`, `SchedulerDefaultLockObjectNamespace` make sense to you ?

Comment (liggitt) [inline pkg/api/types.go]: sure, something like that, and moved to the component config package

**Comment by wanghaoran1988** [comment]
@k8s-bot non-cri e2e test this

File: pkg/api/v1/types.go [hunk 10]
```diff
@@ -218,6 +218,8 @@ const (
 	NamespaceDefault string = "default"
 	// NamespaceAll is the default argument to specify on a context when you want to list or filter resources across all namespaces
 	NamespaceAll string = ""
+	// NamespaceSystem is the system namespace where we place system components.
+	NamespaceSystem string = "kube-system"
```
Comment (timothysc) [inline pkg/api/v1/types.go]: Is this still needed now that you have SchedulerDefaultLockObjectNamespace ? 

It looks like this is unused.

**Comment by wanghaoran1988** [comment]
@k8s-bot non-cri e2e test this

**Comment by wanghaoran1988** [comment]
@timothysc Updated, would you mind take a look again?

**Comment by lovejoy** [comment]
looks like we need to define scheduler-name & lock-object-name if we want to run multiple not-default scheduler
