### PR TITLE
distinguish between mountpoints and symbolic link in IsNotMountPoint

### LINKED ISSUE #74871: IsLikelyNotMountPoint return false if filepath is symbolic link
**What happened**:
I realized csi local driver with the function of IsLikelyNotMountPoint in kubernetes pkg/util/mount library. The function as follows:
```
// IsLikelyNotMountPoint determines if a directory is not a mountpoint.
// It is fast but not necessarily ALWAYS correct. If the path is in fact
// a bind mount from one part of a mount to another it will not be detected.
// mkdir /tmp/a /tmp/b; mount --bin /tmp/a /tmp/b; IsLikelyNotMountPoint("/tmp/b")
// will return true. When in fact /tmp/b is a mount point. If this situation
// if of interest to you, don't use this function...
func (mounter *Mounter) IsLikelyNotMountPoint(file string) (bool, error) {
	stat, err := os.Stat(file)
	if err != nil {
		return true, err
	}
	rootStat, err := os.Lstat(filepath.Dir(strings.TrimSuffix(file, "/")))
	if err != nil {
		return true, err
	}
	// If the directory has a different device as parent, then it is a mountpoint.
	if stat.Sys().(*syscall.Stat_t).Dev != rootStat.Sys().(*syscall.Stat_t).Dev {
		return false, nil
	}

	return true, nil
}
```
We notice that If i use the symbolic link filepath, it will return false which cause the error to umount after this function. 

**What you expected to happen**:
return true

**How to reproduce it (as minimally and precisely as possible)**:
1. mkdir A directory
2. symbolic link A to someone device
3. run the function with symbolic link

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  1.15
- OS (e.g: `cat /etc/os-release`):
centos
- Kernel (e.g. `uname -a`):
Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
yum

### PR DESCRIPTION
**Pull request by smileusd**
/kind bug
fix #74871

### CODE REVIEW

**Comment by smileusd** [comment]
I signed it

File: pkg/util/mount/mount_linux.go [hunk 1]
```diff
@@ -243,6 +245,10 @@ func (mounter *Mounter) IsLikelyNotMountPoint(file string) (bool, error) {
 	if err != nil {
 		return true, err
 	}
+	// if file is symbolic file, skip that
+	if targetPath, err := filepath.EvalSymlinks(file); targetPath != file || err != nil {
+		return true, err
+	}
```
Comment (neolit123) [inline pkg/util/mount/mount_linux.go]: how do we know we are not breaking existing functionality with this change?

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @smileusd 

added a couple of comments.
please squash the commits if you push more.

/priority backlog
/kind bug

it has to be evaluated what user facing implications this has and optionally add a release note.
e.g. "CSI local drivers now ...."

File: pkg/util/mount/mount_linux.go (hunk 1 above)
Comment (smileusd) [reply pkg/util/mount/mount_linux.go]: If the file is both mountpoint and symbolic link it will be break in this change. The more security method is fix in isNotMountPoint function and add explanation.

**Comment by msau42** [comment]
/assign @cofyc
Who is also investigating this area

**Comment by msau42** [comment]
I think we may also need to consider if CSI in general needs to change to use IsNotMountPoint

**Comment by smileusd** [comment]
@msau42 Actually, I use IsNotMountPoint in the my csi driver, but it also return false:
```
func isNotMountPoint(mounter Interface, file string) (bool, error) {
	// IsLikelyNotMountPoint provides a quick check
	// to determine whether file IS A mountpoint
	notMnt, notMntErr := mounter.IsLikelyNotMountPoint(file)
	if notMntErr != nil && os.IsPermission(notMntErr) {
		// We were not allowed to do the simple stat() check, e.g. on NFS with
		// root_squash. Fall back to /proc/mounts check below.
		notMnt = true
		notMntErr = nil
	}
	if notMntErr != nil {
		return notMnt, notMntErr
	}
	// identified as mountpoint, so return this fact
	if notMnt == false {
		return notMnt, nil
	}
```

**Comment by cofyc** [comment]
Do you mean you want `IsLikelyNotMountPoint` to not follow symbolic link?

But I don't understand why this is problem, because `mount` and `umount` will follow symbolic link to mount or unmount target.

For example:

```
cd /tmp
mkdir A B
sudo mount -t tmpfs tmpfs B 
ln -s /tmp/B A/ 
# mounter.IsNotMountPoint("/tmp/A/B") will return false (mounted)
# umount operation will succeed because it following symbolic link
sudo umount A/B 
``` 

And it's also ok to mount on symbolic link.

```
cd /tmp
mkdir A B
ln -s /tmp/B A/ 
# it's ok to mount on symbloc link (A/B)
sudo mount -t tmpfs tmpfs A/B
# mounter.IsNotMountPoint("/tmp/A/B") will return false (mounted)
# umount operation will succeed because it following symbolic link
sudo umount A/B
```

**Comment by smileusd** [comment]
@cofyc It is little different. My point is that if not mount, just symbolic link to B, it also return false. You can reproduce by that:
```
cd /tmp
mkdir A B
ln -s /tmp/B A/ 
# mounter.IsNotMountPoint("/tmp/A/B") will return false (not mounted)
# umount operation will failed because it not mount
sudo umount A/B 
```

**Comment by cofyc** [comment]
Why it should return false (mounted) when it is not mounted?

**Comment by cofyc** [comment]
I see your point. The problem is if the symbolic target is on another device, because `IsLikelyNotMontpoint` checks device number, current `mounter.IsLikelyNotMountPoint` will return `false` (mounted) even if target is not a mount point.

**Comment by cofyc** [comment]
How about resolving the symbolic link first in `IsLikelyNotMountPoint`?

```
file, err = filepath.EvalSymlinks(file)
if err != nil {
    return true, err
}
```

And then test in your scenario?

Linux mounts actually don't care any symbolic links (e.g. any mount operation on symbolic links actually operates on targets), I guess for our operations we should operate (here check mount point) on its target too.

**Comment by cofyc** [comment]
`NsenterMounter.IsLikelyNotMountPoint` resolve symbolic link first to check mount point too.

https://github.com/kubernetes/kubernetes/blob/95cd1d59e4d59632a9bf296cc9cff7d9a96054f1/pkg/util/mount/nsenter_mount.go#L168-L172

Maybe we need to update comment of `IsLikelyNotMountPoint` interface to reflect this (follow symbolic link).

**Comment by smileusd** [comment]
@cofyc I think it is more security to fix in IsNotMountPoint. So I do the change last push. And I also update the comment to that.

**Comment by cofyc** [comment]
IIUC your fix is to skip `IsLikelyNotMountPoint` when the path is symbolic link in `IsNotMountPoint`. 

This will work around the issue, but `IsLikelyNotMountPoint` is still not correct.

The logic in `IsNotMountPoint` is correct, the real problem is `Mounter.IsLikelyNotMountPoint` (non-nsenter) does not work correctly for symbolic links when they are linked to files on another device.

I think we should fix `IsLikelyNotMountPoint` to operate on resolved files.

cc @jsafrane What do you think?

File: pkg/util/mount/mount.go [hunk 2]
```diff
@@ -62,7 +63,7 @@ type Interface interface {
 	// is a mountpoint.
 	// It should return ErrNotExist when the directory does not exist.
 	// IsLikelyNotMountPoint does NOT properly detect all mountpoint types
-	// most notably linux bind mounts.
+	// most notably linux bind mounts and symbolic link.
 	IsLikelyNotMountPoint(file string) (bool, error)
```
Comment (cofyc) [inline pkg/util/mount/mount.go]: `IsLikelyNotMountPoint` should work correctly on symbolic links.

**Comment by msau42** [comment]
If your CSI driver is exporting directories and not mount points, then is there a purpose to check for mount points?  If you're doing a bind mount of a local directory (and not a separate disk), then you should be using IsNotMountPoint()

**Comment by smileusd** [comment]
@msau42 Yeh, bind mount is used to filesystem mode, I am realizing a feature of block volume mode at csi driver. But both the mode are used the driver to (un)Staging/(un)Publishing path.

**Comment by jsafrane** [comment]
I am trying to understand what's the issue here. Yes, `IsLikelyNotMountPoint` will return wrong result if a path is symlink to file on another device.

But why do we care about symlinks here? No internal volume plugin will create symlinks in `/var/lib/kubelet/...`. Kubernetes always creates directories. In CSI, volume plugin just creates a directory and asks a driver to "publish" a volume there. Does any CSI driver replace the directory with a symlink? I would consider this a bug.

**Comment by smileusd** [comment]
@jsafrane Not always, the block volume will create the symlink in [MapDevice](https://github.com/kubernetes/kubernetes/blob/31c6a2ba355687363ee694611148b7c67a0ae8d4/pkg/volume/util/volumepathhandler/volume_path_handler.go#L109)

**Comment by smileusd** [comment]
@jsafrane @msau42 I have just add annotation to this function and not to change the library code, could take a look this?

**Comment by jsafrane** [comment]
@smileusd, can you please rebase this PR?

**Comment by smileusd** [comment]
@jsafrane Yes, Thank you for your mentioned. PTAL
