### PR TITLE
Up and down scale stabilize with envelope.

### LINKED ISSUE #96671: Incorrect behavior on scaling up when using behaviors config on HPA
When configuring new behaviors section in HPA I faced two scenarios that I think are incorrect.
First one:
stabilizationWindowSeconds set up to 5 minutes for both scale up and scale down
min replica count 2
Application consumes big amount of resources during warm-up
0 minute: current replica count: 2
1 minute: desired replica count: 3 - no scale up stabilization window worked
2 minute: desired replica count: 1 (!) - scale up to  3 (max number from previous recommendations during stabilization window period)
Algorithm

Second one 
Stabilization window for scale up 0
Stabilization window for scale down 5 minutes
min replica count 2
behavior set to scale up new pod in 2 minutes
scaleUp:
        policies:
        - type: Pods
          value: 1
          periodSeconds: 120
What happens:
0 minute: 2 replicas
1 minute : performance spike scale up to 3 (desired value 4)
2 minute : no spike no scale up
3 minute: no spike scale up to 4(!) - supposedly desired value 1 and supposedly worked this way because of scale down window set to 5 minutes picking max value from that 5 minutes window that was 4 replicas

Expected behaviors
1 Scenario no scale up for 5 minutes
2 Scenario correct measurement and no scale up when there is no need for it

**Environment**:
- Kubernetes version (use `kubectl version`): client 1.19.3 Server 1.19.0
- Cloud provider or hardware configuration: Azure aks

### PR DESCRIPTION
**Pull request by josephburnett**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The HPA controller keeps a flat history of recommendations for
stabilization. However when both up and down scale stabilization are
configured, the interpretation of the history changes depending on the
direction of movement. What we want is to keep the stabilized
recommendation within the envelope of the minimum and maximum over
configured stabilization windows. We should only move when the
envelope forces a move.

**Which issue(s) this PR fixes**:

Fixes #96671

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 1]
```diff
@@ -3989,20 +3990,46 @@ func TestNormalizeDesiredReplicasWithBehavior(t *testing.T) {
...
+				{5, now},
+				{9, now},
 			},
 			scaleUpStabilizationWindowSeconds: 300,
+		}, {
+			name: "scale up and down stabilization, do not scale up when prenormalized rec goes down",
+			key:  "",
+			recommendations: []timestampedRecommendation{
+				{2, now.Add(-100 * time.Minute)},
+				{2, now.Add(-100 * time.Minute)},
```
Comment (konryd) [inline pkg/controller/podautoscaler/horizontal_test.go:4012]: These two lines are identical - are you sure this is intended? I might be reading it wrong.

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 2]
```diff
@@ -3989,20 +3990,46 @@ func TestNormalizeDesiredReplicasWithBehavior(t *testing.T) {
...
+			prenormalizedDesiredReplicas:        1,
+			expectedStabilizedReplicas:          2,
+			scaleUpStabilizationWindowSeconds:   300,
+			scaleDownStabilizationWindowSeconds: 300,
+		}, {
+			name: "scale up and down stabilization, do not scale down when prenormalized rec goes up",
+			key:  "",
+			recommendations: []timestampedRecommendation{
+				{2, now.Add(-100 * time.Minute)},
+				{2, now.Add(-100 * time.Minute)},
```
Comment (konryd) [inline pkg/controller/podautoscaler/horizontal_test.go:4025]: Same here

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 1 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal_test.go]: A mistake.  Removed the duplicate.

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 2 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal_test.go]: Same.  Mistake.

File: pkg/controller/podautoscaler/horizontal.go [hunk 3]
```diff
@@ -874,44 +874,58 @@ func (a *HorizontalController) storeScaleEvent(behavior *autoscalingv2.Horizonta
...
+	recommendation := args.CurrentReplicas
+	if recommendation < upRecommendation {
+		recommendation = upRecommendation
+	}
+	if recommendation > downRecommendation {
+		recommendation = downRecommendation
+	}
+
+	// Record the unstabilized recommendation.
 	if foundOldSample {
```
Comment (umialpha) [inline pkg/controller/podautoscaler/horizontal.go:914]: Digress: Why don't we clean up all the old samples instead of the last one? I am always confused here when reading the code.

File: pkg/controller/podautoscaler/horizontal.go [hunk 4]
```diff
@@ -874,44 +874,58 @@ func (a *HorizontalController) storeScaleEvent(behavior *autoscalingv2.Horizonta
...
-		if rec.timestamp.Before(obsoleteCutoff) {
+		if rec.timestamp.Before(upCutoff) && rec.timestamp.Before(downCutoff) {
 			foundOldSample = true
 			oldSampleIndex = i
 		}
 	}
+
+	// Bring the recommendation to within the upper and lower limits (stabilize).
+	recommendation := args.CurrentReplicas
+	if recommendation < upRecommendation {
```
Comment (umialpha) [inline pkg/controller/podautoscaler/horizontal.go:906]: is variable _recommendation_ misleading here?

File: pkg/controller/podautoscaler/horizontal.go (hunk 3 above)
Comment (gjtempleton) [reply pkg/controller/podautoscaler/horizontal.go:914]: Agreed, what if we have a user initially setting very long stabilisation windows for one or both downscaling and upscaling, followed by reducing the windows significantly? 

It seems we'll end up with a long list of `timestampedRecommendation`s to loop through and evaluate the timestamp of each time we want to do stabilization, without ever replacing or removing them.

**Comment by gjtempleton** [comment]
One comment, though I think it lies outside the scope of this PR.

/lgtm

File: pkg/controller/podautoscaler/horizontal.go (hunk 3 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal.go:914]: This was a premature optimization to reduce the number of memory allocations.  As you correctly point out, it doesn't ever compact the memory.  ¯\_(ツ)_/¯

**Comment by laurovenancio** [comment]
@gjtempleton @josephburnett Are there any plans to backport this fix to Kubernetes 1.18, 1.19 and 1.20?
