### PR TITLE
Include event type in `kubectl get -w` output

### LINKED ISSUE #185: Watch flag should indicate when a resource is deleted
Feature suggestion/improvement:
`kubectl get pods --watch` should indicate when a pod is actually deleted.

Currently it just appends another line or two indicating that it has a terminating status, around when it gets deleted.

This might apply to other resource types too.

**Kubernetes version** (use `kubectl version`):
Client: 1.8.4
Server: 1.8.0 (via minikube v0.24.1)

**Environment**:

Minikube v0.24.1

Host Env:
Ubuntu 17.10
Linux Laser 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**What happened**:

    $ kubectl get pods --watch
    NAME                               READY     STATUS        RESTARTS   AGE
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6          11m
    my-pod-7bcddb9489-j4qzz   1/1       Running       0          51s
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6         11m
    my-pod-5c7dd74bcb-2xj54   0/1       Terminating   6         11m

**What you expected to happen**:
There should be some sort of 'Terminated' or 'Deleted' status.

**How to reproduce it** (as minimally and precisely as possible):

- run `kubectl get pods --watch` while deleting pods. 

**Anything else we need to know**:
- ran via bash shell
- I created/deleted pods via helm, but that shouldn't matter

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Allows the type of event (ADDED, MODIFIED, DELETED) to be seen when watching objects with `kubectl get -w --output-watch-events`

Before:
```
kubectl get ns -w
NAME              STATUS   AGE
default           Active   9h
kube-node-lease   Active   9h
kube-public       Active   9h
kube-system       Active   9h
ns1   Active   0s
ns1   Terminating   8s
ns1   Terminating   13s
ns1   Terminating   13s
```

After:
```
kubectl get ns -w --output-watch-events
EVENT      NAME              STATUS   AGE
ADDED      default           Active   84m
ADDED      kube-node-lease   Active   84m
ADDED      kube-public       Active   84m
ADDED      kube-system       Active   84m
ADDED      ns1               Active   0s
MODIFIED   ns1               Terminating   5s
MODIFIED   ns1               Terminating   10s
DELETED    ns1               Terminating   10s
```

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubectl/issues/185

Based on https://github.com/kubernetes/kubernetes/pull/79530

**Does this PR introduce a user-facing change?**:
```release-note
`kubectl get -w` now takes an `--output-watch-events` flag to indicate the event type (ADDED, MODIFIED, DELETED)
```

/cc @smarterclayton @seans3 
/sig cli

### CODE REVIEW

File: pkg/printers/humanreadable.go [hunk 1]
```diff
@@ -399,7 +406,14 @@ func PrintTable(table *metav1beta1.Table, output io.Writer, options PrintOptions
 // does not expose metadata). It returns an error if the table cannot
 // be decorated.
 func DecorateTable(table *metav1beta1.Table, options PrintOptions) error {
```
Comment (liggitt) [inline pkg/printers/humanreadable.go]: from https://github.com/kubernetes/kubernetes/pull/72418#discussion_r244656695
> @smarterclayton:
> Kind of yucky. A table should know its column structure, and an event should be <underlying printer> + event type wrapper, so I feel like this shouldn't be necessary.

File: pkg/printers/humanreadable.go [hunk 2]
```diff
@@ -279,6 +281,11 @@ func printHeader(columnNames []string, w io.Writer) error {
 
 // PrintObj prints the obj in a human-friendly format according to the type of the obj.
 func (h *HumanReadablePrinter) PrintObj(obj runtime.Object, output io.Writer) error {
+	return h.PrintObjEvent("", obj, output)
+}
+
+// PrintObj prints the obj in a human-friendly format according to the type of the obj.
+func (h *HumanReadablePrinter) PrintObjEvent(eventType string, obj runtime.Object, output io.Writer) error {
```
Comment (liggitt) [inline pkg/printers/humanreadable.go]: from https://github.com/kubernetes/kubernetes/pull/72418#discussion_r244656712:

> @smarterclayton:
> Why not just pass Event to PrintObj and have it to do the right thing? This feels like a workaround to the underlying structure, and events are runtime.Objects just like everything else.

Comment (liggitt) [reply pkg/printers/humanreadable.go]: Hrmm... I wasn't excited about teaching all the printers about unwrapping Event objects, but maybe that would be better.

File: pkg/printers/humanreadable.go (hunk 1 above)
Comment (liggitt) [reply pkg/printers/humanreadable.go]: left table output alone for now... will let you resolve that in your table output watch PR

File: pkg/printers/humanreadable.go (hunk 2 above)
Comment (liggitt) [reply pkg/printers/humanreadable.go]: well... it's different... your call if it's better

File: pkg/kubectl/cmd/get/get_test.go [hunk 3]
```diff
@@ -1301,18 +1303,205 @@ func TestWatchResource(t *testing.T) {
...
+{"type":"ADDED","object":{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":null,"name":"foo","namespace":"test","resourceVersion":"10"},"spec":{"containers":null,"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"restartPolicy":"Always","securityContext":{},"terminationGracePeriodSeconds":30},"status":{}}}
+{"type":"MODIFIED","object":{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":null,"name":"foo","namespace":"test","resourceVersion":"11"},"spec":{"containers":null,"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"restartPolicy":"Always","securityContext":{},"terminationGracePeriodSeconds":30},"status":{}}}
+{"type":"DELETED","object":{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":null,"name":"foo","namespace":"test","resourceVersion":"12"},"spec":{"containers":null,"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"restartPolicy":"Always","securityContext":{},"terminationGracePeriodSeconds":30},"status":{}}}
+`,
+		},
+		{
+			format: "yaml",
```
Comment (liggitt) [inline pkg/kubectl/cmd/get/get_test.go]: not sure what to do here... the printer for a single object doesn't know there are more objects coming, so printing a separator doesn't seem quite right

File: pkg/kubectl/cmd/get/get_test.go [hunk 4]
```diff
@@ -1301,18 +1303,205 @@ func TestWatchResource(t *testing.T) {
...
+    restartPolicy: Always
+    securityContext: {}
+    terminationGracePeriodSeconds: 30
+  status: {}
+type: DELETED
+
+`,
+		},
+		{
+			format: `jsonpath={.type},{.object.metadata.name},{.object.metadata.resourceVersion}{"\n"}`,
```
Comment (liggitt) [inline pkg/kubectl/cmd/get/get_test.go]: this is nifty... allows for `oc observe`-like invocations

File: pkg/kubectl/cmd/get/get_test.go (hunk 3 above)
Comment (smarterclayton) [reply pkg/kubectl/cmd/get/get_test.go]: yeah, I think we definitely need a separator.  PrintSingleObject is the bane of our existence, but it should be possible to wrap printSingleObject with a stateful printer that knows when you previously printed (no separator for first object, add separator for all subsequent).

File: pkg/kubectl/cmd/get/get_test.go (hunk 4 above)
Comment (smarterclayton) [reply pkg/kubectl/cmd/get/get_test.go]: yeah, good

File: pkg/printers/humanreadable.go [hunk 5]
```diff
@@ -584,15 +597,35 @@ func printRowsForHandlerEntry(output io.Writer, handler *handlerEntry, obj runti
...
 		rows := results[0].Interface().([]metav1beta1.TableRow)
-		printRows(output, rows, options)
+		printRows(output, eventType, rows, options)
 		return nil
 	}
 	return results[1].Interface().(error)
 }
 
+// formattedEventType makes known event types match width when printed
+// TODO: remove this once tabwriter is fixed to remember column widths across flushes
```
Comment (smarterclayton) [inline pkg/printers/humanreadable.go]: that's fixed now right?

File: pkg/printers/humanreadable.go [hunk 6]
```diff
@@ -691,12 +724,17 @@ func (h *HumanReadablePrinter) legacyPrinterToTable(obj runtime.Object, handler
 }
 
 // TODO: this method assumes the meta/v1 server API, so should be refactored out of this package
-func printUnstructured(unstructured runtime.Unstructured, w io.Writer, additionalFields []string, options PrintOptions) error {
+func printUnstructured(eventType string, unstructured runtime.Unstructured, w io.Writer, additionalFields []string, options PrintOptions) error {
```
Comment (smarterclayton) [inline pkg/printers/humanreadable.go]: I still feel like there is a more elegant construction.  I.e. everything goes through a table for this reason - maybe there should be a Table adapter that wraps table output and unwraps events.  The long term goal was to completely remove everything except a) things that create tables, b) things that output tables

File: staging/src/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go [hunk 7]
```diff
@@ -80,6 +95,24 @@ func (p *YAMLPrinter) PrintObj(obj runtime.Object, w io.Writer) error {
...
+		}
+		data, err = yaml.JSONToYAML(data)
+		if err != nil {
+			return err
+		}
+		_, err = w.Write(data)
+		if err != nil {
+			return err
+		}
+		_, err = w.Write([]byte("\n"))
```
Comment (smarterclayton) [inline staging/src/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go]: Make it stateful here - `if !p.first { w.write(`---`) }; p.first = true`?

File: staging/src/k8s.io/cli-runtime/pkg/genericclioptions/printers/name.go [hunk 8]
```diff
@@ -42,6 +43,11 @@ type NamePrinter struct {
 // PrintObj is an implementation of ResourcePrinter.PrintObj which decodes the object
 // and print "resource/name" pair. If the object is a List, print all items in it.
 func (p *NamePrinter) PrintObj(obj runtime.Object, w io.Writer) error {
+	switch castObj := obj.(type) {
+	case *metav1.WatchEvent:
```
Comment (smarterclayton) [inline staging/src/k8s.io/cli-runtime/pkg/genericclioptions/printers/name.go]: I wish we'd done a watch event interface.  I can take that as a future cleanup.

File: pkg/printers/humanreadable.go (hunk 6 above)
Comment (liggitt) [reply pkg/printers/humanreadable.go]: I puzzled over this a bit, and without changing the signature of PrintObj, I'm not sure how to accomplish this... the table unwrapping would lose the event type info

The included unit test coverage exercises every output format we have, with and without tables for human-readable output. It's fiddly, but I can live with it for now to get this capability.

File: pkg/kubectl/cmd/get/customcolumn.go [hunk 9]
```diff
@@ -205,6 +207,21 @@ func (s *CustomColumnsPrinter) PrintObj(obj runtime.Object, out io.Writer) error
 func (s *CustomColumnsPrinter) printOneObject(obj runtime.Object, parsers []*jsonpath.JSONPath, out io.Writer) error {
 	columns := make([]string, len(parsers))
 	switch u := obj.(type) {
+	case *metav1.WatchEvent:
+		if printers.InternalObjectPreventer.IsForbidden(reflect.Indirect(reflect.ValueOf(u.Object.Object)).Type().PkgPath()) {
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/get/customcolumn.go]: That's exciting

File: pkg/kubectl/cmd/get/table_printer.go [hunk 10]
```diff
@@ -73,5 +79,10 @@ func decodeIntoTable(obj runtime.Object) (runtime.Object, error) {
 		row.Object.Object = converted
 	}
 
-	return table, nil
+	if isEvent {
+		event.Object.Object = table
+		return event, nil
+	} else {
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/get/table_printer.go]: remove else

File: pkg/kubectl/cmd/get/table_printer.go [hunk 11]
```diff
@@ -45,6 +46,11 @@ func (t *TablePrinter) PrintObj(obj runtime.Object, writer io.Writer) error {
 }
 
 func decodeIntoTable(obj runtime.Object) (runtime.Object, error) {
+	event, isEvent := obj.(*metav1.WatchEvent)
+	if isEvent {
+		obj = event.Object.Object
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/get/table_printer.go]: I'm wondering what the odds are this is always decoded into Object

File: pkg/printers/tableprinter.go [hunk 12]
```diff
@@ -187,8 +195,11 @@ func printTable(table *metav1beta1.Table, output io.Writer, options PrintOptions
 // namespace column. It will fill empty columns with nil (if the object
 // does not expose metadata). It returns an error if the table cannot
 // be decorated.
-func decorateTable(table *metav1beta1.Table, options PrintOptions) error {
+func decorateTable(eventType string, table *metav1beta1.Table, options PrintOptions) error {
```
Comment (smarterclayton) [inline pkg/printers/tableprinter.go]: Yuck

File: staging/src/k8s.io/cli-runtime/pkg/printers/json.go [hunk 13]
```diff
@@ -79,7 +98,28 @@ func (p *YAMLPrinter) PrintObj(obj runtime.Object, w io.Writer) error {
 		return fmt.Errorf(InternalObjectPrinterErr)
 	}
 
+	count := atomic.AddInt64(&p.printCount, 1)
+	if count > 1 {
+		if _, err := w.Write([]byte("---\n")); err != nil {
```
Comment (smarterclayton) [inline staging/src/k8s.io/cli-runtime/pkg/printers/json.go]: Is this a separate commit?

File: pkg/printers/tableprinter.go (hunk 12 above)
Comment (smarterclayton) [reply pkg/printers/tableprinter.go]: Can this be a different method `decorateTableWithEventType`?

File: staging/src/k8s.io/cli-runtime/pkg/printers/json.go (hunk 13 above)
Comment (liggitt) [reply staging/src/k8s.io/cli-runtime/pkg/printers/json.go]: it isn't, can be if you want

File: pkg/printers/tableprinter.go (hunk 12 above)
Comment (liggitt) [reply pkg/printers/tableprinter.go]: refactored to an `addColumns(position, table, headers, valueFuncs)` method and called from the single place we plumb eventType. Can clean up `decorateTable` to use that as well in a follow up (prepends namespace column, appends label columns)

File: pkg/kubectl/cmd/get/table_printer.go (hunk 11 above)
Comment (liggitt) [reply pkg/kubectl/cmd/get/table_printer.go]: here in get, 100%:
```
objToPrint = &metav1.WatchEvent{Type: string(watch.Added), Object: runtime.RawExtension{Object: objToPrint}}
```

**Comment by liggitt** [comment]
addressed comments, rebased on https://github.com/kubernetes/kubernetes/pull/79530

File: pkg/kubectl/cmd/get/get.go [hunk 14]
```diff
@@ -171,6 +173,7 @@ func NewCmdGet(parent string, f cmdutil.Factory, streams genericclioptions.IOStr
 	cmd.Flags().StringVar(&o.Raw, "raw", o.Raw, "Raw URI to request from the server.  Uses the transport specified by the kubeconfig file.")
 	cmd.Flags().BoolVarP(&o.Watch, "watch", "w", o.Watch, "After listing/getting the requested object, watch for changes. Uninitialized objects are excluded if no object name is provided.")
 	cmd.Flags().BoolVar(&o.WatchOnly, "watch-only", o.WatchOnly, "Watch for changes to the requested object(s), without listing/getting first.")
+	cmd.Flags().BoolVar(&o.OutputWatchEvents, "output-watch-events", o.OutputWatchEvents, "Output watch event objects when --watch or --watch-only is used. Existing objects are output as initial ADDED events.")
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/get/get.go]: Maybe this should be `--watch-events` or `--include-events` (although I could maybe see that being confused with Events).  We're not super strict about prefixing flags though.

Comment (liggitt) [reply pkg/kubectl/cmd/get/get.go]: I like `--output` as a prefix, and since it's only allowed with `--watch` (or `--watch-only`), I thought qualifying it would be clearer

Comment (liggitt) [reply pkg/kubectl/cmd/get/get.go]: `--include-events` sounds like what describe does, separately fetching/printing related events
