### PR TITLE
kubelet/rkt: update supported rkt version

### LINKED ISSUE #15638: rkt does not work on latest k8s v1.0.6 on CoreOS
It looks like `rkt run` got changed and k8s cannot start pods, tried on latest CoreOS 833 and 766 builds:
````
kubectl describe pod my-nginx-kre94
Name:				my-nginx-kre94
Namespace:			default
Image(s):			nginx
Node:				172.19.17.99/
Labels:				run=my-nginx
Status:				Pending
Reason:				GeneralError
Message:			Query container info failed with error (cannot find status for pod: "my-nginx-kre94_default")
IP:
Replication Controllers:	my-nginx (2/2 replicas created)
Containers:
  my-nginx:
    Image:		nginx
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath	Reason		Message
  Wed, 14 Oct 2015 09:39:09 -0600	Wed, 14 Oct 2015 09:39:09 -0600	1	{scheduler }				scheduled	Successfully assigned my-nginx-kre94 to 172.19.17.99
  Wed, 14 Oct 2015 09:39:09 -0600	Wed, 14 Oct 2015 09:39:50 -0600	6	{kubelet 172.19.17.99}			failedSync	Error syncing pod, skipping: invalid output: [NAME: 	image cat-manifest - Inspect and print the image manifest  USAGE: 	rkt image cat-manifest IMAGE  DESCRIPTION: 	IMAGE should be a string referencing an image; either a hash or an image name.  OPTIONS:   -h, --help=false: help for cat-manifest       --pretty-print=false: apply indent to format the output  GLOBAL OPTIONS:       --debug=false: Print out more debug information to stderr       --dir="/var/lib/rkt": rkt data directory       --insecure-skip-verify=false: skip all TLS, image or fingerprint verification       --local-config="/etc/rkt": local configuration directory       --system-config="/usr/lib/rkt": system configuration directory]
````

### PR DESCRIPTION
**Pull request by yifan-gu**
Update the cli parameters for rkt 0.9.0.
Fix #15638

### CODE REVIEW

**Comment by eparis** [comment]
looks like you didn't use `-t` with godep.  We really should test if we can get rid of _test.go stuff now....

**Comment by yifan-gu** [comment]
godeps update just don't have the option for `-t`!

**Comment by yifan-gu** [comment]
removed the appc and redo a `godep save -t`

File: pkg/kubelet/rkt/rkt.go [hunk 1]
```diff
@@ -51,8 +51,8 @@ import (
 )
 
 const (
-	acVersion             = "0.6.1"
-	rktMinimumVersion     = "0.8.1"
+	acVersion             = "0.7.1"
+	supportedRktVersion   = "0.9.0"
```
Comment (vishh) [inline pkg/kubelet/rkt/rkt.go]: Does this mean rocket will be bundled along with kubelet?

**Comment by vishh** [comment]
LGTM

File: pkg/kubelet/rkt/rkt.go (hunk 1 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @vishh What do you mean by `bundled along`?

Comment (yujuhong) [inline pkg/kubelet/rkt/rkt.go]: Hmm....do we want to fail kubelet if rkt version is off? I think we should let user run with rkt 0.9.1 if they want to -- but we need a clear warning/event.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @yujuhong We should guarantee 0.9.1 won't break 0.9.0, but not 0.10.0 afaics. If 0.10.0 will fail in an unexpected way, I think we should just abort here?
Maybe we can loose the restriction a little bit, say support all 0.9.x? 
@jonboulle

File: pkg/kubelet/rkt/rkt.go [hunk 2]
```diff
@@ -1322,14 +1322,14 @@ func (r *Runtime) getImageByName(imageName string) (*kubecontainer.Image, error)
...
+	// Example output of 'rkt image list --fields=id,name':
 	//
-	// KEY									        NAME
+	// ID									        NAME
 	// sha512-374770396f23dd153937cd66694fe705cf375bcec7da00cf87e1d9f72c192da7	nginx:latest
 	// sha512-bead9e0df8b1b4904d0c57ade2230e6d236e8473f62614a8bc6dcf11fc924123	coreos.com/rkt/stage1:0.8.1
 	//
 	// With '--no-legend=true' the fist line (KEY NAME) will be omitted.
-	output, err := r.runCommand("image", "list", "--no-legend=true", "--fields=key,name")
+	output, err := r.runCommand("image", "list", "--no-legend=true", "--fields=id,name")
```
Comment (ppalucki) [inline pkg/kubelet/rkt/rkt.go]: one minor nit, image id is truncated by default now, I'm not how it used later (or will be in future) but potentially can cause a problem, you need to specify `--full` flag to get full output (and generally one should never truncate any data to early)

look at this:
```sh
# v 0.8.1
➜  sudo ./build-rkt-0.8.1/bin/rkt image list --fields key,name
KEY                                                                     NAME
sha512-f8df83fda2ceac2235ab6dc42043d2214aab186b5bd8e963520f17adc592744b busybox:latest

# v 0.9.0 without --full
➜  sudo ./build-rkt-0.9.0/bin/rkt image list --fields id,name
ID                      NAME
sha512-f8df83fda2ce     busybox:latest

# v 0.9.0 with --full
➜  sudo ./build-rkt-0.9.0/bin/rkt image list --fields id,name --full
ID                                                                      NAME
sha512-f8df83fda2ceac2235ab6dc42043d2214aab186b5bd8e963520f17adc592744b busybox:latest
```

File: pkg/kubelet/rkt/rkt.go (hunk 1 above)
Comment (ppalucki) [inline pkg/kubelet/rkt/rkt.go]: :+1: for relaxing dependency version (even with ["semver"](http://semver.org/) scheme doesn't guarantee anything until '1.0.0')

File: pkg/kubelet/rkt/rkt.go (hunk 2 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @ppalucki fixed, thanks :)

File: pkg/kubelet/rkt/rkt.go (hunk 1 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @ppalucki Didn't get the idea why we relax the version if it's gonna break?

**Comment by jonboulle** [comment]
LGTM

File: pkg/kubelet/rkt/rkt.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/rkt/rkt.go]: > @yujuhong rkt should guarantee 0.9.1 won't break 0.9.0, but not 0.10.0 afaics. If 0.10.0 will fail in an unexpected way, I think we should just abort here?

We've had relevant discussions several times, and we have people supporting different approaches. I will try to summarize what I *think* was the direction that we're going (@dchen1107 @bgrant0607 in case my interpretation is not accurate):

For every k8s/kubelet release, we want the following rkt/docker versions:
 - A minimum supported version: any version smaller than this is not supported, and kubelet should fail.
 - A recommended version: the version we test, verify, and potentially ship with the new kubelet in the images. 

If a user wants to use an above minimum requirement but not the recommended version for various reasons (bug fixes, or just to experiment), kubelet should warn clearly but not fail completely (i.e., use it at your own risk).

I know rkt is not yet v1.0, and is going through a lot of changes, but supporting exactly one version is too strict.
+1 for relaxing the constraint to at least support all 0.9.x versions.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: ok, added minimum version and recommended version. Fail if the version < minimum version. Print warnings if the version != recommended version.

File: pkg/kubelet/rkt/rkt.go [hunk 3]
```diff
@@ -154,13 +155,22 @@ func New(config *Config,
...
-		return nil, fmt.Errorf("rkt: Version is too old, requires at least %v", rktMinimumVersion)
+		return nil, fmt.Errorf("rkt: version is too old, requires at least %v", minimumRktVersion)
 	}
+
+	result, err = version.Compare(recommendRktVersion)
+	if err != nil {
+		return nil, err
+	}
+	if result != 0 {
+		glog.Warningf("rkt: current version %q is not recommended (recommended version %q)", version, recommendRktVersion)
```
Comment (yujuhong) [inline pkg/kubelet/rkt/rkt.go]: I think we'd want to record an event or surface this through in other ways, but we can reiterate later.

**Comment by yujuhong** [comment]
lgtm but need a rebase.

**Comment by yifan-gu** [comment]
rebased

File: pkg/kubelet/rkt/rkt.go (hunk 3 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @yujuhong Added a todo
