### PR TITLE
Honor the RevisionHistoryLimit in StatefulSetSpec

### LINKED ISSUE #85690: StatefulSet does not clean up ControllerRevisions in some situations
**What happened**:
A StatefulSet has created well over 100k ControllerRevisions when the number should be limited to 10.

**What you expected to happen**:
That the StatefulSet controller cleans up ControllerRevisions to keep the number at or below the threshold.

**How to reproduce it (as minimally and precisely as possible)**:
What happens is that the StatefulSet controller cleans up ControllerRevisions at the end of the reconcile loop. If something goes wrong during reconcile, it bails out without actually performing this step. We encountered this due to a missing PriorityClass that prevented the StatefulSet controller from creating pods.

**Anything else we need to know?**:
An example operator that reproduces this situation: https://github.com/mortent/stsbug

**Environment**:
- Kubernetes version (use `kubectl version`): GKE
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig apps

### PR DESCRIPTION
**Pull request by nan-yu**
The StatefulSet controller cleans up ControllerRevisions at the end of
the reconcile loop. If something goes wrong during reconcile, it bails
out without actually performing this step. This commit moves the cleanup
to a deferred function call to guarantee it will be executed.

Fixes issue: https://github.com/kubernetes/kubernetes/issues/85690

**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:

Make sure the statefulset's revision history is limited to 10.

**Which issue(s) this PR fixes**:

Fixes #85690

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by nan-yu** [comment]
cc @mortent

**Comment by mortent** [comment]
We probably want a test to verify that the controller will clean up ControllerRevisions
/ok-to-test

**Comment by nan-yu** [comment]
> We probably want a test to verify that the controller will clean up ControllerRevisions
Yes, I'm currently working on adding a unit test.

**Comment by nan-yu** [comment]
@barney-s This is the fix to the issue. I'm working on adding a unit test for the fix.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -87,6 +87,9 @@ func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, p
 		return err
 	}
 
+	// maintain the set's revision history limit
+	defer ssc.truncateHistory(set, pods, revisions, currentRevision, updateRevision)
```
Comment (mortent) [inline pkg/controller/statefulset/stateful_set_control.go]: Maybe this should be above the call to `getStatefulSetRevisions`? Revisions would be created inside that call, so it seems like we should make sure we check if the history should be truncated after every call.

Comment (mortent) [inline pkg/controller/statefulset/stateful_set_control.go]: We are swallowing any errors returned from `truncateHistory` here. Not sure we can do much to handle the error, but I think it should at least be logged.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 2]
```diff
@@ -1201,6 +1201,40 @@ func TestStatefulSetControlRollingUpdateWithPartition(t *testing.T) {
...
+		updateStatefulSetControl(set, ssc, spc, assertUpdateInvariants)
+		set, err = spc.setsLister.StatefulSets(set.Namespace).Get(set.Name)
+		if err != nil {
+			t.Fatalf("Error getting updated StatefulSet: %v", err)
+		}
+		revisions, err := ssc.ListRevisions(set)
+		if err != nil {
+			t.Fatalf("Error listing revisions: %v", err)
+		}
+		if len(revisions) > int(*set.Spec.RevisionHistoryLimit)+2 {
```
Comment (mortent) [inline pkg/controller/statefulset/stateful_set_control_test.go]: Why the `+2` here?

File: pkg/controller/statefulset/stateful_set_control.go (hunk 1 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: [This commit](https://github.com/kubernetes/kubernetes/pull/86097/commits/a00b9905498f2695bab35f891739fe02116eb2dd) moves `defer ssc.truncateHistory()` further up above the call to `getStatefulSetRevisions`.

However, after a second look, I've decided to keep `truncateHistory` after `getStatefulSetRevisions` because `truncateHistory` only cleans up **non-live** revisions. The revision that gets created inside `getStatefulSetRevisions` is considered as [**live** revision](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L154) and will not be cleaned up anyway. Hence, to keep the code clean, the commit (https://github.com/kubernetes/kubernetes/pull/86097/commits/a00b9905498f2695bab35f891739fe02116eb2dd) was reverted.

Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: Done in commit: https://github.com/kubernetes/kubernetes/pull/86097/commits/b0686ad740ef5e25705cac940a6e627ce81f26f9

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 2 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control_test.go]: Because `currentRevision` and `updateRevision` are considered as **live** revisions, and `truncateHistory` only cleans up non-live revisions.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 3]
```diff
@@ -87,6 +87,12 @@ func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, p
 		return err
 	}
 
+	// maintain the set's revision history limit
+	defer func() {
+		err := ssc.truncateHistory(set, pods, revisions, currentRevision, updateRevision)
+		klog.Errorf("Failed to truncate revision history for StatefulSet %s/%s, error: %v", set.Namespace, set.Name, err)
```
Comment (mortent) [inline pkg/controller/statefulset/stateful_set_control.go]: I think you need an if-statement here so we only log if `truncateHistory` actually returns an error.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 2 above)
Comment (mortent) [reply pkg/controller/statefulset/stateful_set_control_test.go]: Might be worth adding a comment here for clarity.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 3 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: Oh, thanks for catching that! DONE!

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 2 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control_test.go]: DONE

File: pkg/controller/statefulset/stateful_set_control.go [hunk 4]
```diff
@@ -23,7 +23,7 @@ import (
 	"k8s.io/klog"
 
 	apps "k8s.io/api/apps/v1"
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (barney-s) [inline pkg/controller/statefulset/stateful_set_control.go]: Why was this change made ? I dont see this being used in the patch.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 5]
```diff
@@ -87,6 +87,14 @@ func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, p
 		return err
 	}
 
+	// maintain the set's revision history limit
+	defer func() {
```
Comment (barney-s) [inline pkg/controller/statefulset/stateful_set_control.go]: The issue with using a defer is that we cannot bubble up the error inside this block to the sync loop entry. 
It would introduce a subtle bug where in if truncateHistory fails, we would not requeue the sts for trying again. 

Would recommend not using a defer.

**Review by barney-s — CHANGES_REQUESTED** [review]

File: pkg/controller/statefulset/stateful_set_control.go (hunk 5 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: Thanks for the comment. I didn't notice the requeue part and thanks for catching it!
I switched to another way instead of using `defer`. Alternatively, I invoke the `truncateHistory` function when any error occurs and return the combined errors.

FWIW, I used `go.uber.org/multierr` library. I checked `go.sum` and the library was there. I think we might be good to use it. But still want to double check with you @mortent @barney-s

File: pkg/controller/statefulset/stateful_set_control.go (hunk 4 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: It seems Intellij configuration automatically added it. To avoid reverting every time, I would prefer to leave it here.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 6]
```diff
@@ -84,21 +85,20 @@ func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, p
 	// get the current, and update revisions
 	currentRevision, updateRevision, collisionCount, err := ssc.getStatefulSetRevisions(set, revisions)
 	if err != nil {
-		return err
+		return multierr.Append(err, ssc.truncateHistory(set, pods, revisions, currentRevision, updateRevision))
```
Comment (mortent) [inline pkg/controller/statefulset/stateful_set_control.go]: I think this works, but would it be better if we split this into two functions so we only need to add the `truncatehistory` call in one place?

File: pkg/controller/statefulset/stateful_set_control.go [hunk 7]
```diff
@@ -20,12 +20,13 @@ import (
 	"math"
 	"sort"
 
-	"k8s.io/klog"
+	"go.uber.org/multierr"
```
[the remark this answers is not in the document]
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: `apimachinery errors.go` doesn't return a generic builtin `error` type with the **combined** errors. It returns either an `Aggregate`, which is a list of errors, or the **first** error in the aggregate. If we use that, we have to either change the signature of `UpdateStatefulSet` function to return an aggregate, or swallow the error returned from `truncateHistory`. Neither of them are ideal.

`multierr` is not a newly added library. It has been ported in [go.mod](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L481) and [go.sum](https://github.com/kubernetes/kubernetes/blob/master/go.sum#L510). I only added it into the `require` section.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 6 above)
Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: Do you mean creating a new function which invokes `truncateHistory` first and then merges the errors?

Comment (nan-yu) [reply pkg/controller/statefulset/stateful_set_control.go]: Like this:

```
func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, pods []*v1.Pod) error {

	// list all revisions and sort them
	revisions, err := ssc.ListRevisions(set)
	if err != nil {
		return err
	}
	history.SortControllerRevisions(revisions)

	// get the current, and update revisions
	currentRevision, updateRevision, collisionCount, err := ssc.getStatefulSetRevisions(set, revisions)
	if err != nil {
		return handleCleanup(err, ssc, set, pods, revisions, currentRevision, updateRevision)
	}

	// perform the main update function and get the status
	status, err := ssc.updateStatefulSet(set, currentRevision, updateRevision, collisionCount, pods)
	if err != nil {
		return handleCleanup(err, ssc, set, pods, revisions, currentRevision, updateRevision)
	}

	// update the set's status
	err = ssc.updateStatefulSetStatus(set, status)
	if err != nil {
		return handleCleanup(err, ssc, set, pods, revisions, currentRevision, updateRevision)
	}
	klog.V(4).Infof("StatefulSet %s/%s pod status replicas=%d ready=%d current=%d updated=%d",
		set.Namespace,
		set.Name,
		status.Replicas,
		status.ReadyReplicas,
		status.CurrentReplicas,
		status.UpdatedReplicas)

	klog.V(4).Infof("StatefulSet %s/%s revisions current=%s update=%s",
		set.Namespace,
		set.Name,
		status.CurrentRevision,
		status.UpdateRevision)

	// maintain the set's revision history limit
	return ssc.truncateHistory(set, pods, revisions, currentRevision, updateRevision)
}

func handleCleanup(
	err error,
	ssc *defaultStatefulSetControl,
	set *apps.StatefulSet,
	pods []*v1.Pod,
	revisions []*apps.ControllerRevision,
	currentRevision *apps.ControllerRevision,
	updateRevision *apps.ControllerRevision) error {
	return multierr.Append(err, ssc.truncateHistory(set, pods, revisions, currentRevision, updateRevision))
}
```

**Comment by nan-yu** [comment]
@kow3ns can you take a look at this PR and approve it when you get a chance? Thanks!

**Comment by nan-yu** [comment]
All commits squashed -> Ready to be re-reviewed and merged.

**Comment by nan-yu** [comment]
@barney-s can you re-lgtm to this PR?
