### PR TITLE
Fixed incomplete kubectl bash completion.

### LINKED ISSUE #25287: Fix incomplete kubectl bash completion
We have bash completion for some `kubectl` commands:
```console
# lists all resources that you can get
$ kubectl get [tab][tab]

# lists all pods that you can get
$ kubectl get pod [tab][tab]
```

but many other commands don't support this (or have limited support)
```console
# gives you nothing 
$ kubectl edit [tab][tab]
```

Ref:

- to enable bash completion http://kubernetes.io/docs/getting-started-guides/gce/#enabling-bash-completion-of-the-kubernetes-command-line-tools 
- cobra docs https://github.com/spf13/cobra/blob/master/bash_completions.md
- https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L32 

@kubernetes/kubectl

### PR DESCRIPTION
**Pull request by xingzhou**
Added bash completion for several kubectl commands.

Fixes #25287

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31333)

### CODE REVIEW

File: pkg/kubectl/cmd/taint.go [hunk 1]
```diff
@@ -76,16 +75,6 @@ var (
 func NewCmdTaint(f *cmdutil.Factory, out io.Writer) *cobra.Command {
 	options := &TaintOptions{}
 
-	// retrieve a list of handled resources from printer as valid args
```
Comment (brendandburns) [inline pkg/kubectl/cmd/taint.go]: @deads2k is this done for a reason here?

**Comment by brendandburns** [comment]
Most of this PR looks fine.  I'm not sure why you are removing the dynamic code in `taint`, I want to double check with @deads2k that this won't break anything upstream.

**Comment by brendandburns** [comment]
@k8s-bot ok to test

File: pkg/kubectl/cmd/taint.go (hunk 1 above)
Comment (deads2k) [inline pkg/kubectl/cmd/taint.go]: > @deads2k is this done for a reason here?

I hadn't noticed this code before.  It's definitely incorrect for this command and its not a very clean way of getting the data for the completions overall.  Removing it here is good.

**Comment by deads2k** [comment]
> I want to double check with @deads2k that this won't break anything upstream.

Thanks for the heads up.  Generally, yes, we care about being able to substitute the available types, but `kubectl taint` is a special case that only works against `nodes`.

File: pkg/kubectl/cmd/rollout/rollout_history.go [hunk 2]
```diff
@@ -49,6 +49,9 @@ var (
 func NewCmdRolloutHistory(f *cmdutil.Factory, out io.Writer) *cobra.Command {
 	options := &HistoryOptions{}
 
+	validArgs := []string{"deployment"}
```
Comment (deads2k) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: @fabianofranz You should think of a way for us to refactor this to have these completions work well for us.  I don't think it needs to be resolved in this pull, but we'll want some way to add `dc` and `deploymentconfig` here.

File: pkg/kubectl/cmd/scale.go [hunk 3]
```diff
@@ -66,6 +66,9 @@ var (
 func NewCmdScale(f *cmdutil.Factory, out io.Writer) *cobra.Command {
 	options := &ScaleOptions{}
 
+	validArgs := []string{"deployment", "replicaset", "replicationcontroller", "job"}
```
Comment (deads2k) [inline pkg/kubectl/cmd/scale.go]: @fabianofranz this should probably be hitting the API server to cache discovery for X minutes and navigating the discovered resources for a `scale` subresource, but fall back to this list if it takes too long.  You'll probably want an issue for that.  This one isn't just an openshift problem.

File: pkg/kubectl/cmd/rollout/rollout_history.go (hunk 2 above)
Comment (fabianofranz) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: @deads2k definitely. As a short-term solution could this be an argument in `NewCmdRolloutHistory`?

Comment (deads2k) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: > @deads2k definitely. As a short-term solution could this be an argument in NewCmdRolloutHistory?

I can't say that I'm a fan of that.  I think we should let this merge and you can work it out with @kargakis since he's trying to integrate these with openshift.

Comment (fabianofranz) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: Me neither, I'm ok with addressing it apart of this PR.

Comment (kargakis) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: We already have ported `rollout history`. Make sure this is configurable because it needs to work with deploymentconfigs too

File: pkg/kubectl/cmd/taint.go [hunk 4]
```diff
@@ -102,7 +91,8 @@ func NewCmdTaint(f *cmdutil.Factory, out io.Writer) *cobra.Command {
 				cmdutil.CheckErr(err)
 			}
 		},
-		ValidArgs: validArgs,
+		ValidArgs:  []string{"node"},
+		ArgAliases: []string{"nodes"},
```
Comment (kargakis) [inline pkg/kubectl/cmd/taint.go]: Use `kubectl.ResourceAliases(validArgs)`?

Comment (xingzhou) [inline pkg/kubectl/cmd/taint.go]: for this command, we do not support "no" at present. I guess this `kubectl.ResourceAliases(validArgs)` will introduce three names: "no", "node" and "nodes"

File: pkg/kubectl/cmd/rollout/rollout_history.go (hunk 2 above)
Comment (xingzhou) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: @kargakis, any suggestions to make it configurable? or @fabianofranz can take care of this in a new PR?

File: pkg/kubectl/cmd/taint.go (hunk 4 above)
Comment (kargakis) [inline pkg/kubectl/cmd/taint.go]: It doesn't make sense to support the resource name but not its alias. cc: @kubernetes/kubectl

File: pkg/kubectl/cmd/rollout/rollout_history.go (hunk 2 above)
Comment (kargakis) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: Hm, are these changes helping in fixing completion? If not, then let's just drop them. The `rollout` commands already know their valid resources via the factory:
```
$ kc rollout history no/127.0.0.1
error: no history viewer has been implemented for {"" "Node"}
```
The error message should be cleaned up in https://github.com/kubernetes/kubernetes/pull/31234

Comment (deads2k) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: > Hm, are these changes helping in fixing completion?

Doc in cobra says "yes".

Comment (kargakis) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: Just noticed it, thanks. Are we going to end up with a factory method that needs to separate between commands?

Comment (deads2k) [inline pkg/kubectl/cmd/rollout/rollout_history.go]: > Just noticed it, thanks. Are we going to end up with a factory method that needs to separate between commands?

Maybe.  I see what's been done here as strictly better than the current state of affairs.  I'd let this go in and @fabianofranz and team can fix it up in the 1.5 timeframe.

**Comment by AdoHe** [comment]
We should also support it's alias. @xingzhou

**Comment by brendandburns** [comment]
agree we should support the alias.

**Comment by xingzhou** [comment]
ok, @AdoHe  and @brendandburns, do you think we can open a new ticket for supporting the alias "no" for command taint? In my mind, this can be a separate PR, this one only can be used for fixing command bash completion. If you agree, I can provide a patch later and we can move forward for this PR?

**Comment by AdoHe** [comment]
@xingzhou anything block you add alias support in this PR?

**Comment by xingzhou** [comment]
@AdoHe, no, just curious of how to split PRs. I will add one more commit here to resolve taint alias issue.

**Comment by brendandburns** [comment]
LGTM, thanks for the PR.

**Comment by AdoHe** [comment]
@xingzhou @brendandburns please squash before we can merge.

**Comment by xingzhou** [comment]
Rebased and squashed into one commit

**Comment by brendandburns** [comment]
LGTM again.

**Comment by foxish** [comment]
This commit is in 1.4 already.

**Comment by pwittrock** [comment]
>
git branch --contains 80d6cd0a402f74afca278437d0a829b65adf92c4
  master
* release-1.4
