### PR TITLE
node: device-mgr: Handle recovery flow by checking if healthy devices exist- attempt 2

### LINKED ISSUE #109595: device manager can incorrectly recover devices on node restart
### What happened?

The following behaviour was reproduced on openshift 4.10 ("Kubelet version" kubeletVersion="v1.23.3+54654d2") but I believe the root cause is on kubernetes.

Let's consider a pod requiring resources, among them a device (point in case: dpdk network device)
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dpdk
  name: testpmd
  namespace: default
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: $DPKDK_IMAGE
      imagePullPolicy: Always
      name: dpdk
      resources:
        limits:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
        requests:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
```
the pods starts and run just fine up until the node is restarted. On restart, the device manager correctly recover its state from the checkpoint data:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.461850    2011 manager.go:247] "Starting Device Plugin manager"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.463809    2011 container_manager_linux.go:930] "Attempting to apply oom_score_adj to process" oomScoreAdj=-999 pid=2011
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464997    2011 oom_linux.go:66] attempting to set "/proc/2011/oom_score_adj" to "-999"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464269    2011 iptables.go:462] running iptables: ip6tables [-w 5 -W 100000 -N KUBE-POSTROUTING -t nat]
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.465254    2011 event.go:294] "Event occurred" object="TESTNODE" kind="Node" apiVersion="" type="Normal" reason="NodeAllocatableEnforced" message="Updated Node Allocatable limit across pods"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466379    2011 pod_devices.go:215] "Get checkpoint entry" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" containerName="dpdk" resourceName="openshift.io/dpdk_nic_1" deviceIDs=map[-1:[0000:00:05.0]] allocated="\n1\n!PCIDEVICE_OPENSHIFT_IO_DPDK_NIC_1\x12\f0000:00:05.0\x1a%\n\x0e/dev/vfio/vfio\x12\x0e/dev/vfio/vfio\x1a\x03mrw\x1a'\n\v/dev/vfio/0\x12\x13/dev/vfio/noiommu-0\x1a\x03mrw"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466823    2011 manager.go:289] "Serving device plugin registration server on socket" path="/var/lib/kubelet/device-plugins/kubelet.sock"
```
As expected, the device plugin capacity is set to zero until the device plugin correctly re-register itself:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.607362    2011 setters.go:344] "Updated capacity for device plugin" plugin="openshift.io/dpdk_nic_1" capacity=0`
```
A bit later, the recovery process from the apiserver begins:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193478    2011 config.go:278] "Setting pods for source" source="api"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193526    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-node-tuning-operator/tuned-tql4x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193541    2011 config.go:383] "Receiving a new pod" pod="openshift-sdn/sdn-fnls4"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193549    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/node-exporter-jzprg"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193557    2011 config.go:383] "Receiving a new pod" pod="openshift-ingress-canary/ingress-canary-62kq2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193565    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-87sbt"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193573    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/network-metrics-daemon-5qb5q"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193580    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/node-ca-frkhr"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193597    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193605    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193615    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193624    2011 config.go:383] "Receiving a new pod" pod="openshift-machine-config-operator/machine-config-daemon-nkqsq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193632    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/image-pruner-27496800-n4qzq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193640    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193649    2011 config.go:383] "Receiving a new pod" pod="openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193659    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-additional-cni-plugins-xwgkj"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193667    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/coredns-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193674    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/node-resolver-6n2vp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193682    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/keepalived-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193689    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/dns-default-cnlrl"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193695    2011 config.go:383] "Receiving a new pod" pod="default/testpmd"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193703    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193711    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-network-config-daemon-p94vm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193721    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-device-plugin-bw7rq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193728    2011 config.go:383] "Receiving a new pod" pod="openshift-network-diagnostics/network-check-target-2tbjs"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.195257    2011 kubelet.go:2106] "SyncLoop ADD" source="api" pods=[openshift-cluster-node-tuning-operator/tuned-tql4x openshift-sdn/sdn-fnls4 openshift-monitoring/node-exporter-jzprg openshift-ingress-canary/ingress-canary-62kq2 openshift-multus/multus-87sbt openshift-multus/network-metrics-daemon-5qb5q openshift-image-registry/node-ca-frkhr openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2 openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp openshift-machine-config-operator/machine-config-daemon-nkqsq openshift-image-registry/image-pruner-27496800-n4qzq openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6 openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x openshift-multus/multus-additional-cni-plugins-xwgkj openshift-openstack-infra/coredns-TESTNODE openshift-dns/node-resolver-6n2vp openshift-openstack-infra/keepalived-TESTNODE openshift-dns/dns-default-cnlrl default/testpmd openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm openshift-sriov-network-operator/sriov-network-config-daemon-p94vm openshift-sriov-network-operator/sriov-device-plugin-bw7rq openshift-network-diagnostics/network-check-target-2tbjs]
```
we can see already that the workload pod (testpmd) is going to be recovered BEFORE the device plugin. When the workload pod 
enters the admission flow (as per recovered pods), because the devicemanager restored its state and has data about this pod, we see:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204837    2011 topology_manager.go:200] "Topology Admit Handler"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204848    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204859    2011 topology_hints.go:49] "Resource does not have a topology preference" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204873    2011 scope_container.go:77] "TopologyHints" hints=map[openshift.io/dpdk_nic_1:[]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204880    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204928    2011 policy_static.go:437] "TopologyHints generated" pod="default/testpmd" containerName="dpdk" cpuHints=[{NUMANodeAffinity:01 Preferred:true}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204941    2011 scope_container.go:77] "TopologyHints" hints=map[cpu:[{NUMANodeAffinity:01 Preferred:true}]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204949    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204957    2011 scope_container.go:77] "TopologyHints" hints=map[] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204964    2011 policy.go:78] "Hint Provider has no preference for NUMA affinity with resource" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204971    2011 policy.go:70] "Hint Provider has no preference for NUMA affinity with any resource"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204979    2011 scope_container.go:85] "ContainerTopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true}
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204987    2011 scope_container.go:54] "Best TopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204995    2011 scope_container.go:59] "Topology Affinity" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205009    2011 manager.go:914] "Looking for needed resources" needed=1048576000 resourceName="memory"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205016    2011 manager.go:914] "Looking for needed resources" needed=1 resourceName="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205024    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205037    2011 manager.go:694] "Found pre-allocated devices for resource on pod" resourceName="openshift.io/dpdk_nic_1" containerName="dpdk" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" devices=[0000:00:05.0]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205044    2011 manager.go:914] "Looking for needed resources" needed=2 resourceName="cpu"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205050    2011 manager.go:914] "Looking for needed resources" needed=1073741824 resourceName="hugepages-1Gi"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205060    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
```
When the topology manager requests device allocation, we end up in the devicemanager's [devicesToAllocate](https://github.com/kubernetes/kubernetes/blob/v1.24.0-rc.0/pkg/kubelet/cm/devicemanager/manager.go#L686) function. This function checks if there already a pre-allocated device (and there is, thanks to the recovered data), and if so exits early, skipping the health check which would have failed, because the device plugin has not re-registered itself yet.

The end result is that containers can be admitted and start running without the requested device actually available, causing runtime errors in the workload.

### What did you expect to happen?

The kubelet should reject the admission of the pod until the device plugins re-registered themselves; then the pods requiring devices should be processed again. This seems the only meaningful way to recover pods while taking in consideration the actualy health of the devices.

### How can we reproduce it (as minimally and precisely as possible)?

The behaviour here depends on the order on which pods are recovered, so it's essentially a race.

1. run a test pod requiring devices. Make sure this test pod clearly fails if the requested devices are not available
2. restart the node (can take few attempts)
3. check the health of the test pod

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
kubelet 1.23.3
likely happening on current master
```
</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This is an attempt to merge changes proposed as part of https://github.com/kubernetes/kubernetes/pull/114640. The PR was [reverted](https://github.com/kubernetes/kubernetes/pull/116341) due to serial test [failures](https://github.com/kubernetes/kubernetes/issues/116340) and this PR updates device plugin and device manager e2e tests to avoid serial test failures.

Core changes were squshed into a single commit: [dc1a592632](https://github.com/kubernetes/kubernetes/pull/116376/commits/dc1a5926321410f141f48b9edd3397fed2d0f93e) `node: device-mgr: Handle recovery by checking if healthy devices exist` which was already approved in #114640 (https://github.com/kubernetes/kubernetes/pull/116376/commits/0aa6a5726a67edd4ffc0efd1af7179cf47e532ce, https://github.com/kubernetes/kubernetes/pull/114640/commits/a799ffb571476d7fb706009e79aaf933b7851991 and https://github.com/kubernetes/kubernetes/pull/114640/commits/5b2a3dbbdc9cd25c09b65dd8c4ca630b001ab084).

Other commits are related to device plugin and device manager e2e tests. The PR adds a bunch of test cases to ensure comprehensive testing but the main focus is to recreate a scenario (where on kubelet restart application pod requesting devices comes up before device plugin pod re-registers itself) resulting in pod admission error.

**Rationale of the PR as captured in the previous PR:**

In case of node reboot/kubelet restart, the flow of events involves obtaining the state from the checkpoint file followed by setting the `healthDevices`/`unhealthyDevices` to its zero value. This is done to allow the device plugin to re-register itself so that capacity can be updated appropriately.

During the allocation phase, we need to check if the resources requested by the pod have been registered AND healthy devices are present on the node to be allocated.

Also we need to move this check above `needed==0` where needed is required - devices allocated to the container (which is obtained from the checkpoint file) because even in cases where no additional devices have to be allocated (as they were pre-allocated), we still need to make sure that the devices that were previously allocated are healthy.

For more details refer to the comment here: https://github.com/kubernetes/kubernetes/issues/109595#issuecomment-1359882423.

#### Which issue(s) this PR fixes:

Fixes #109595 and (possibly) #107928 (TODO: need to check the latter)
#### Special notes for your reviewer:

**NOTE:** 

1. **This PR depends on https://github.com/kubernetes/kubernetes/pull/117057 for device plugin e2e test refactoring work and builds on top of that.** 

2. **This PR depends on sample device plugin changes proposed in: https://github.com/kubernetes/kubernetes/pull/115107.** 

Those changes are included here (first two commits) as they are needed for e2e test implementation.

NOTE: On node reboot, in case the application pod requesting devices starts after the device plugin pod providing those devices as has been described in https://github.com/kubernetes/kubernetes/issues/109595 and https://github.com/kubernetes/kubernetes/issues/107928 we exit early as there are pre-allocated devices without checking if the devices have registered and are healthy. This PR adds both those checks.

Because of this change, in cases where application pods are started before device plugin pod (say after node reboot),  because devices are not healthy, the pod would fail with `UnexpectedAdmissionError` error.  If the pod is part of a deployment, another pod would be created but that would stay in `Pending` state waiting for the pod to be scheduled to the node. This pod would go `Running` after the node capacity is updated followed by start up of device plugin pod and its registration.

The pod which fails at admission time continues to exist on the node and needs to be removed manually:
```
kubectl delete pods --field-selector status.phase=Failed
```

#### Does this PR introduce a user-facing change?

```release-note
During device plugin allocation, resources requested by the pod can only be allocated if the device plugin has registered itself to kubelet AND healthy devices are present on the node to be allocated. If these conditions are not sattsfied, the pod would fail with `UnexpectedAdmissionError` error.
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/device_plugin_test.go [hunk 1]
```diff
@@ -227,21 +227,13 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
-
-			ginkgo.By("Confirming that device assignment persists even after container restart")
-			devIDAfterRestart := parseLog(ctx, f, pod1.Name, pod1.Name, deviceIDRE)
-			framework.ExpectEqual(devIDAfterRestart, devID1)
-
-			ginkgo.By("Restarting Kubelet")
-			restartKubelet(true)
-
 			ginkgo.By("Wait for node to be ready again")
 			e2enode.WaitForAllNodesSchedulable(ctx, f.ClientSet, 5*time.Minute)
```
Comment (ffromani) [inline test/e2e_node/device_plugin_test.go:231]: without kubelet restart, these two lines seem redundant, surely the `gingko.By`. We may want to keep the `waitForallNodesSchedulable` for extra safety though

File: test/e2e_node/device_plugin_test.go [hunk 2]
```diff
@@ -217,7 +217,7 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 			framework.ExpectEqual(len(v1ResourcesForOurPod.Containers[0].Devices[0].DeviceIds), 1)
 		})
 
-		ginkgo.It("Keeps device plugin assignments across pod and kubelet restarts", func(ctx context.Context) {
+		ginkgo.It("Keeps device plugin assignments across pod restarts (no kubelet restart)", func(ctx context.Context) {
```
Comment (ffromani) [inline test/e2e_node/device_plugin_test.go:220]: I think it's a good idea to split the previous testcase which was testing for BOTH kubelet restart AND container (pod?) restart. We should have two `It()` blocks each corresponding to the cases, and later we should check if/how combine them.

**Review by ffromani — COMMENTED** [review]
initial review
kudos for quickly addressing the test failures. I agree that device_plugin_test can use some improvements/updates

File: test/e2e_node/device_plugin_test.go (hunk 2 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:220]: Sure, I can do that.

File: test/e2e_node/device_plugin_test.go [hunk 3]
```diff
@@ -238,7 +238,7 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 			framework.ExpectEqual(devIDRestart1, devID1)
 		})
 
-		ginkgo.It("Keeps device plugin assignments after the device plugin has been re-registered", func(ctx context.Context) {
+		ginkgo.It("Keeps device plugin assignments across kubelet restart after the device plugin has been re-registered", func(ctx context.Context) {
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:241]: So in summary you want me to have the following test cases:

File: test/e2e_node/device_plugin_test.go [hunk 4]
```diff
@@ -280,6 +284,8 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 
 			ginkgo.By("Creating another pod")
 			pod2 := e2epod.NewPodClient(f).CreateSync(ctx, makeBusyboxPod(SampleDeviceResourceName, podRECMD))
+			err = e2epod.WaitTimeoutForPodRunningInNamespace(ctx, f.ClientSet, pod2.Name, f.Namespace.Name, 1*time.Minute)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:287]: Sure, I will try to do a better job by adding more context and expressing the rationale behind changes the relevant commit messages.

File: test/e2e_node/device_plugin_test.go [hunk 5]
```diff
@@ -264,9 +264,13 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 
 			ginkgo.By("Recreating the plugin pod")
 			devicePluginPod = e2epod.NewPodClient(f).CreateSync(ctx, dptemplate)
+			err = e2epod.WaitTimeoutForPodRunningInNamespace(ctx, f.ClientSet, devicePluginPod.Name, devicePluginPod.Namespace, 1*time.Minute)
+			framework.ExpectNoError(err)
+
+			ginkgo.By("Confirming that after a kubelet restart, fake-device assignment is kept")
+			err = e2epod.WaitTimeoutForPodRunningInNamespace(ctx, f.ClientSet, pod1.Name, f.Namespace.Name, 1*time.Minute)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: I see what you mean but my intention here was to capture the fact that after kubelet restarted and the device plugin re-registered we confirm the device assignment. Admittedly, the statement in the `By` clause does not reflect that accurately. The check is not immediately after kubelet restart but it is still after kubelet restart :) Perhaps it would be better to update the statement or move the check right after kubelet restart.
I will make update to address this.

File: test/e2e_node/device_plugin_test.go [hunk 6]
```diff
@@ -236,9 +236,133 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+				WithTimeout(time.Minute).
+				Should(HaveFailedWithAdmissionError(),
+					"the pod succeeded to start, when it should fail with the admission error")
+
+			ginkgo.By("Confirming that after kubelet restart, fake-device assignment is kept")
+			devIDRestart1 := parseLog(ctx, f, pod1.Name, pod1.Name, deviceIDRE)
+			framework.ExpectEqual(devIDRestart1, devID1)
+		})
+
+		ginkgo.It("Keeps device plugin assignments across pod and kubelet restarts (no device plugin re-registration)", func(ctx context.Context) {
```
Comment (ffromani) [inline test/e2e_node/device_plugin_test.go:279]: this is a nice extra!

File: test/e2e_node/device_plugin_test.go [hunk 7]
```diff
@@ -236,9 +236,133 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+				Should(HaveFailedWithAdmissionError(),
+					"the pod succeeded to start, when it should fail with the admission error")
+
+			ginkgo.By("Confirming that after a kubelet restart, fake-device assignment is kept")
+			devIDRestart1 = parseLog(ctx, f, pod1.Name, pod1.Name, deviceIDRE)
+			framework.ExpectEqual(devIDRestart1, devID1)
+		})
+
+		ginkgo.It("Keeps device plugin assignments after the device plugin has been re-registered (no kubelet or pod restart)", func(ctx context.Context) {
+			podRECMD := "devs=$(ls /tmp/ | egrep '^Dev-[0-9]+$') && echo stub devices: $devs && sleep 60"
```
Comment (ffromani) [inline test/e2e_node/device_plugin_test.go:318]: do we want to increase the sleep period here, effectively making "forever" for the test timescale?

**Review by ffromani — COMMENTED** [review]
thanks for the updates. This is definitely moving in the right direction

File: test/e2e_node/device_plugin_test.go [hunk 8]
```diff
@@ -236,9 +236,133 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+
+			ginkgo.By("Creating another pod")
+			pod2 := e2epod.NewPodClient(f).CreateSync(ctx, makeBusyboxPod(SampleDeviceResourceName, podRECMD))
+			err = e2epod.WaitTimeoutForPodRunningInNamespace(ctx, f.ClientSet, pod2.Name, f.Namespace.Name, 1*time.Minute)
+			framework.ExpectNoError(err)
+
+			ginkgo.By("Checking that pod got a fake device")
+			devID2 := parseLog(ctx, f, pod2.Name, pod2.Name, deviceIDRE)
+
+			gomega.Expect(devID2).To(gomega.Not(gomega.Equal("")))
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:248]: Ack, sure. Will update.

File: test/e2e_node/device_plugin_test.go [hunk 9]
```diff
@@ -217,7 +217,7 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 			framework.ExpectEqual(len(v1ResourcesForOurPod.Containers[0].Devices[0].DeviceIds), 1)
 		})
 
-		ginkgo.It("Keeps device plugin assignments across pod restarts (no kubelet restart)", func(ctx context.Context) {
+		ginkgo.It("Keeps device plugin assignments across pod restarts (no kubelet restart and device plugin re-registration)", func(ctx context.Context) {
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:220]: Sure, will update.

File: test/e2e_node/device_plugin_test.go [hunk 10]
```diff
@@ -236,9 +236,133 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+			framework.ExpectNoError(err)
+
+			ginkgo.By("Checking that pod got a fake device")
+			devID2 := parseLog(ctx, f, pod2.Name, pod2.Name, deviceIDRE)
+
+			gomega.Expect(devID2).To(gomega.Not(gomega.Equal("")))
+		})
+
+		ginkgo.It("Keeps device plugin assignments across kubelet restarts (no pod restart and device plugin re-registration)", func(ctx context.Context) {
+			podRECMD := "devs=$(ls /tmp/ | egrep '^Dev-[0-9]+$') && echo stub devices: $devs && sleep 60"
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:252]: Yeah, good point. For test cases where we don't want pod restart we should change the sleep to "forever"? Let's agree on what is a suitable value here. I am thinking an hour should be reasonable here. WDYT?

File: test/e2e_node/device_plugin_test.go (hunk 7 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:318]: Sure, we should definitely do that.

File: test/e2e_node/device_plugin_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:252]: This has been a significant source of confusion for me, so yes, I believe tests which not involve the pod restart should sleep "forever".  To better convey this intent I'd use some huge value like `24h`, but indeed anything >= `1h` seems OK. Your call if you want to add a constant in the test code to convey the intent or not.

[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:252]: Ack, let's use a big value like `24h` to emphasize this idea. I will use a constant and provide a comment to express the intent .

**Comment by ffromani** [comment]
`waitForNodeReady` has to be reimplemented/replaced becayse it's linux-specific

**Comment by swatisehgal** [comment]
/assign @klueska 
for review/approval

The core changes and device manager e2e tests were cherry-picked from https://github.com/kubernetes/kubernetes/pull/114640. The changes in the PR are related to device plugin e2e test.

**Comment by ffromani** [comment]
thanks @swatisehgal for your continued work on this bug. I'll totally have a look today.

**Comment by ffromani** [comment]
> Checking the new changes versus the content of the old PR, almost everything I see here makes sense. Sure, in some areas the tests can be further improved, but the existing changes are improvements already and we'd better iterate than fixing everything in one go.
> 
> The "almost" is: it's still is not clear to me is what guarantees the app pod is always recovered before the device plugin pod. The e2e tests makes fully sense in this scenario, but is not obvious why this is always the case.
> 
> I'll have another pass later today.

The ordering in the recovering flow when kubelet is restarted is my main and only concern here. We can improve later other points.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 11]
```diff
@@ -544,16 +544,30 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
...
+
 	// Check if resource registered with devicemanager
-	if _, ok := m.healthyDevices[resource]; !ok {
+	if !hasRegistered {
 		return nil, fmt.Errorf("can't allocate unregistered device %s", resource)
 	}
 
+	// Check if registered resource has healthy devices
+	if healthyDevices.Len() == 0 {
+		return nil, fmt.Errorf("can't allocate unhealthy devices %s", resource)
```
Comment (rphillips) [inline pkg/kubelet/cm/devicemanager/manager.go:558]: This error message doesn't look correct for a zero length check.

File: test/e2e_node/device_manager_test.go [hunk 12]
```diff
@@ -266,6 +275,239 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+		register and the application pod fails with admission error.
+
+		   Breakdown of the steps implemented as part of this e2e test is as follows:
+		   1. Create a file `registration` at path `/var/lib/kubelet/device-plugins/sample/`
+		   2. Create sample device plugin with an environment variable with
+		      `REGISTER_CONTROL_FILE=/var/lib/kubelet/device-plugins/sample/registration` that
+			  waits for a client to delete the control file.
+		   3. Trigger plugin registeration by deleting the abovementioned directory.
+		   4. Create a test pod requesting devices exposed by the device plugin.
+		   5. Stop kubelet.
```
Comment (rphillips) [inline test/e2e_node/device_manager_test.go:311]: IIRC, if we stop the kubelet then we have to label the test with [Disruptive].

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 11 above)
Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:558]: This check is to ensure that we rule out cases where we don't have healthy devices that are suitable for allocation, hence the message. Would you prefer it to be more descriptive such as  `fmt.Errorf("no healthy devices present, can't allocate unhealthy devices %s", resource)`?

File: test/e2e_node/device_manager_test.go (hunk 12 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:311]: Good point, will add that. Thanks!

File: test/e2e_node/device_manager_test.go [hunk 13]
```diff
@@ -266,6 +275,239 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+			go func() {
+				// Since autoregistration is disabled for the device plugin (as REGISTER_CONTROL_FILE
+				// environment variable is specified), device plugin registration needs to be triggerred
+				// manually.
+				// This is done by deleting the control file at the following path:
+				// `/var/lib/kubelet/device-plugins/sample/registration`.
+
+				defer ginkgo.GinkgoRecover()
+				framework.Logf("Deleting the control file: %q to trigger registration", triggerPathFile)
+				err := os.Remove(triggerPathFile)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:380]: We are using a modified version of sample-device plugin for testing here. https://github.com/kubernetes/kubernetes/pull/115107. In this version we control the registration of the device plugin with an environment variable `REGISTER_CONTROL_FILE` . The deletion of the file triggers registration of the device plugin to Kubelet.  

We implemented this in a go routine because the first time the device plugin pod is deployed, we want it to register to  kubelet as normal. However, after kubelet restart we want to artificially create a scenario where application pods appears before device plugin pod by not letting the plugin re-register to kubelet.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 11 above)
Comment (rphillips) [reply pkg/kubelet/cm/devicemanager/manager.go:558]: I think that is very helpful!

File: test/e2e_node/device_manager_test.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (rphillips) [reply test/e2e_node/device_manager_test.go:380]: Thanks for that clarification!

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 11 above)
Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go]: Updated with a more descriptive error message.

File: test/e2e_node/device_manager_test.go (hunk 12 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:311]: Updated.

**Comment by ffromani** [comment]
/retest

failures are unrelated

**Comment by ffromani** [comment]
/test pull-kubernetes-e2e-kind-ipv6

unrelated sig-apps failures

**Review by ffromani — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
