### PR TITLE
fix return code when request /logs with long file name

### LINKED ISSUE #101355: Getting logs from unicode logpath via API causes internal server error
#### What happened:
Hello @viralpoetry and I were fuzzing the k8s (via [openapi-fuzzer](https://github.com/matusf/openapi-fuzzer)) and found out following bug. Getting logs from unicode logpath via API causes internal server error. The API endpoint is `/logs/{logpath}`.

#### What you expected to happen:
Response with non-500 HTTP status code

#### How to reproduce it (as minimally and precisely as possible):
We were fuzzing k8s locally via minikube. 
1. start minukube
```
minikube start --driver virtualbox
```
2. install ca certificates
```
sudo cp ~/.minikube/ca.pem /usr/local/share/ca-certificates/
sudo update-ca-certificates
```
3. get k8s IP address
```
kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}'
```
4. add the IP to `/etc/hosts` as `minikubeca`
5. get access token and export it as `token`
```
kubectl create clusterrolebinding permissive-binding \
  --clusterrole=cluster-admin \
  --user=admin \
  --user=kubelet \
  --group=system:serviceaccounts

kubectl create serviceaccount openapifuzz
kubectl get serviceaccounts openapifuzz -o json | jq -r .secrets[].name
kubectl get secret openapifuzz-token-sn9qm -o json | jq -r .data.token
 export token=<retrieved-token>
```
6. send request
```
curl -X GET -H "authorization: bearer $token" https://minikubeca:8443/logs/%F3%95%BE%A2%F4%8C%97%BC%E8%91%A0%F1%B4%82%AA%F1%8F%B6%9B%F1%BE%B2%A4%F1%84%89%94%F3%B5%BC%93%F1%A6%AE%BB%F3%81%9A%9A%F1%A6%BF%B8%F3%B7%93%83%F4%88%B4%9B%F2%AF%85%A1%F3%88%87%82%F3%A5%B7%8F%F0%BD%B4%80%E2%BC%87%F0%A9%96%A7%F3%89%B7%A8%F0%AD%B4%B5%F1%B8%AE%BA%F3%9E%A3%8A%F3%96%B7%91%F2%BE%83%A7%F3%92%83%BB%F2%BB%96%9E%F3%8F%92%AB%F2%91%AD%92%F3%86%B8%87%F0%9F%94%86%F3%94%8F%BD%F2%8F%8A%B2%F1%A2%B5%9B%F2%96%B6%81%E6%B0%9C%F1%9A%A4%85%F1%A9%9E%93%F2%9B%8D%A8%F3%A0%9D%9E%F1%9C%95%B5%F2%87%AD%B3%F2%92%85%9E%F3%B9%9A%9F%F0%B4%81%91%F1%8F%AC%A0%F0%A7%AF%9D%F4%8B%80%B9%F3%91%BA%84%E4%AA%89%F3%AC%99%9A%F2%A8%B4%AF%F1%8F%94%BC%F2%9B%BC%9A%F3%A1%B7%AF%F2%B3%B4%B0%F2%83%99%97%F2%86%A7%B0%F0%AD%8D%8D%F3%B0%B4%AC%F3%B8%B0%AA%F1%83%A9%90%F1%92%A9%B0%F3%88%AD%86%F4%80%B3%B4

500 Internal Server Error
```

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
clientVersion:
  buildDate: "2021-04-08T16:31:21Z"
  compiler: gc
  gitCommit: cb303e613a121a29364f75cc67d3d580833a7479
  gitTreeState: clean
  gitVersion: v1.21.0
  goVersion: go1.16.1
  major: "1"
  minor: "21"
  platform: linux/amd64
serverVersion:
  buildDate: "2021-01-13T13:20:00Z"
  compiler: gc
  gitCommit: faecb196815e248d3ecfb03c680a4507229c2a56
  gitTreeState: clean
  gitVersion: v1.20.2
  goVersion: go1.15.5
  major: "1"
  minor: "20"
  platform: linux/amd64
```
- Cloud provider or hardware configuration: minikube with virtual-box driver
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS (bionic)
- Kernel (e.g. `uname -a`): Linux pine 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: downloaded precompiled binary
- minikube version: v1.19.0 (commit: 15cede53bdc5fe242228853e737333b09d4336b5)

### PR DESCRIPTION
**Pull request by Haleygo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Add file name length check before /logs calling http.ServeFile, if file name too long, return 404 directly.
If not, http.ServeFile will return 500 Internal Server Error instead.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/101355

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/routes/logs.go [hunk 1]
```diff
@@ -42,6 +44,16 @@ func (l Logs) Install(c *restful.Container) {
 func logFileHandler(req *restful.Request, resp *restful.Response) {
 	logdir := "/var/log"
 	actual := path.Join(logdir, req.PathParameter("logpath"))
+
+	//pre check file, if file name has more than 255 bytes, return 404: file name too long
+	_, err := os.Stat(actual)
+	if err != nil {
+		e := err.(*os.PathError)
+		if e.Err == syscall.ENAMETOOLONG {
+			http.Error(resp, syscall.ENAMETOOLONG.Error(), http.StatusNotFound)
```
Comment (wzshiming) [inline pkg/routes/logs.go:53]:
```suggestion
			http.NotFound(resp, req)
```

File: pkg/routes/logs.go [hunk 2]
```diff
@@ -42,6 +44,16 @@ func (l Logs) Install(c *restful.Container) {
 func logFileHandler(req *restful.Request, resp *restful.Response) {
 	logdir := "/var/log"
 	actual := path.Join(logdir, req.PathParameter("logpath"))
+
+	//pre check file, if file name too long, return 404
+	_, err := os.Stat(actual)
+	if err != nil {
+		e := err.(*os.PathError)
+		if e.Err == syscall.ENAMETOOLONG {
+			http.NotFound(resp,req.Request)
```
Comment (wzshiming) [inline pkg/routes/logs.go:53]:
```suggestion
			http.NotFound(resp, req.Request)
```

**Comment by yliaog** [comment]
add a test case like what's given in https://github.com/kubernetes/kubernetes/issues/101355#issuecomment-826571720 ?

**Comment by Haleygo** [comment]
> add a test case like what's given in [#101355 (comment)](https://github.com/kubernetes/kubernetes/issues/101355#issuecomment-826571720) ?

of course, I will add one

File: pkg/routes/logs.go [hunk 3]
```diff
@@ -42,10 +44,27 @@ func (l Logs) Install(c *restful.Container) {
...
 	logdir := "/var/log"
 	http.ServeFile(resp.ResponseWriter, req.Request, logdir)
 }
+
+func preCheckLogFileNameLength(filePath string) bool{
+	_, err := os.Stat(filePath)
+	if err != nil {
+		if err.(*os.PathError).Err == syscall.ENAMETOOLONG {
+			return true
+		}
```
Comment (wzshiming) [inline pkg/routes/logs.go:67]:
```suggestion
		if e, ok := err.(*os.PathError); ok && e.Err == syscall.ENAMETOOLONG {
			return true
		}
```

File: pkg/routes/logs.go [hunk 4]
```diff
@@ -42,10 +44,27 @@ func (l Logs) Install(c *restful.Container) {
...
+	}
+	return false
+}
```
Comment (wzshiming) [inline pkg/routes/logs.go:70]:
```suggestion
}

```

File: pkg/routes/logs_test.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+import (
+	"fmt"
+	"net/http"
+	"net/http/httptest"
+	"testing"
+)
+
+func TestPreCheckLogFile(t *testing.T) {
+	logFilePath := "/var/log"
+	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath,"a")
```
Comment (wzshiming) [inline pkg/routes/logs_test.go:12]:
```suggestion
	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath, "a")
```

File: pkg/routes/logs_test.go [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+		t.Error("failed to check oversize filename")
+	}
+}
+
+func TestHttpServeFile(t *testing.T) {
+	logFilePath := "/var/log"
+	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath,"a")
+
+	w := httptest.NewRecorder()
+	request,_ := http.NewRequest("","",nil)
```
Comment (wzshiming) [inline pkg/routes/logs_test.go:25]:
```suggestion
	request, _ := http.NewRequest("", "", nil)
```

File: pkg/routes/logs_test.go [hunk 7]
```diff
@@ -0,0 +1,31 @@
...
+
+	isNameOversize := preCheckLogFileNameLength(oversizeFileName)
+	if !isNameOversize {
+		t.Error("failed to check oversize filename")
+	}
+}
+
+func TestHttpServeFile(t *testing.T) {
+	logFilePath := "/var/log"
+	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath,"a")
```
Comment (wzshiming) [inline pkg/routes/logs_test.go:22]:
```suggestion
	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath, "a")
```

File: pkg/routes/logs_test.go [hunk 8]
```diff
@@ -0,0 +1,31 @@
...
+
+	w := httptest.NewRecorder()
+	request,_ := http.NewRequest("","",nil)
+
+	http.ServeFile(w, request, oversizeFileName)
+	if w.Code != http.StatusInternalServerError {
+		t.Errorf("expected response code 500, get %d",w.Code)
```
Comment (wzshiming) [inline pkg/routes/logs_test.go:29]:
```suggestion
		t.Errorf("expected response code 500, get %d", w.Code)
```

**Review by wzshiming — COMMENTED** [review]
`go fmt ./pkg/routes`

File: pkg/routes/logs_test.go [hunk 9]
```diff
@@ -0,0 +1,45 @@
...
+	logFilePath := "/var/log"
+	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath, "a")
+	correctFileName := fmt.Sprintf("%s/%0255s", logFilePath, "a")
+
+	isOversize := preCheckLogFileNameLength(oversizeFileName)
+	if !isOversize {
+		t.Error("failed to check oversize filename")
+	}
+
+	NotOversize := preCheckLogFileNameLength(correctFileName)
```
Comment (yliaog) [inline pkg/routes/logs_test.go:20]: the file is not created, hence may not exist at all, that could cause the 'false' return

Comment (Haleygo) [reply pkg/routes/logs_test.go:20]: As I test in here, http.ServeFile will return code 500 to oversize filename, and 500 is not the code that we want here, so I did a preCheckLogFileNameLength in advance.
It's only designed to check filename length, and return true when given file path contain oversize(more than 255) string. When the file is not exist, error won't be catch and will continue to execute the old process(http.ServeFile process them).
Are you saying I should handle other err like "file not exist" in precheck?

Comment (yliaog) [reply pkg/routes/logs_test.go:20]: no, i'm not suggesting to handle other error. 

i'm trying to say the test case for correctFileName is likely not really testing the intended condition. For correctFileName case, inside preCheckLogFileNameLength, os.Stat(filePath) will return error os.ErrNotExist

Comment (Haleygo) [reply pkg/routes/logs_test.go:22]: Sorry, I get it now.
I was missing the test case for existing correct file, and I add one below that create the file first.

File: pkg/routes/logs_test.go [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+func TestHttpServeFile(t *testing.T) {
+	logFilePath := "/var/log"
+	oversizeFileName := fmt.Sprintf("%s/%0256s", logFilePath, "a")
+	correctFileName := fmt.Sprintf("%s/%0255s", logFilePath, "a")
+
+	request, _ := http.NewRequest("", "", nil)
+
+	w1 := httptest.NewRecorder()
+	http.ServeFile(w1, request, oversizeFileName)
+	if w1.Code != http.StatusInternalServerError {
```
Comment (yliaog) [inline pkg/routes/logs_test.go:48]: for oversizeFileName, the response should be 404 instead of 500, no?

File: pkg/routes/logs_test.go [hunk 11]
```diff
@@ -0,0 +1,57 @@
...
+		t.Errorf("expected response code 500, get %d", w1.Code)
+	}
+
+	w2 := httptest.NewRecorder()
+	http.ServeFile(w2, request, correctFileName)
+	if w2.Code != http.StatusNotFound {
```
Comment (yliaog) [inline pkg/routes/logs_test.go:54]: for correctFileName, the response code should be 200, no?

Comment (Haleygo) [reply pkg/routes/logs_test.go]: Sure, fixed.

File: pkg/routes/logs_test.go (hunk 10 above)
Comment (Haleygo) [reply pkg/routes/logs_test.go:47]: Actually, inside http.ServeFile, expect NotExist and Forbidden, the default error code is 500, and 500 is not the code we want here, preCheckLogFileNameLength is here to solve this particular situation. 
image
And I want to tell the reason why need preCheckLogFileNameLength by this testcase.
add some comments now, make sense?

Comment (Haleygo) [reply pkg/routes/logs_test.go]: Or should I just delete those test about http.serveFile, in case they cause misunderstanding?

**Comment by Haleygo** [comment]
@yliaog So sorry it took so long and so many times, I have passed all the test. Would you mind to review it again

**Comment by Haleygo** [comment]
@yliaog Can you take a second look, thanks a lot

**Comment by pacoxu** [comment]
/remove-lifecycle stale
looks good enough in my view.😄

**Comment by Haleygo** [comment]
@jpbetz @yliaog 
PTAL, thanks :)

File: pkg/routes/logs_test.go (hunk 10 above)
Comment (jpbetz) [reply pkg/routes/logs_test.go]: How about "422 Unprocessable Entity"? 404 seems a bit misleading here.

Comment (jpbetz) [reply pkg/routes/logs_test.go]: I would focus on tests that show the desired behavior and show that the fix results in that desired behavior. I found this test confusing.

File: pkg/routes/logs.go [hunk 12]
```diff
@@ -42,10 +44,27 @@ func (l Logs) Install(c *restful.Container) {
 func logFileHandler(req *restful.Request, resp *restful.Response) {
 	logdir := "/var/log"
 	actual := path.Join(logdir, req.PathParameter("logpath"))
+
+	// pre check file, if file name is too long, return 404
+	isNameOversize := preCheckLogFileNameLength(actual)
+	if isNameOversize {
```
Comment (jpbetz) [inline pkg/routes/logs.go:50]: Minor naming nit: Rename function so it makes sense when used inline, e.g.?

`if logFileNameIsTooLong(actual) {` ?

Comment (Haleygo) [reply pkg/routes/logs.go]: yeah, too redundant here, thanks!

File: pkg/routes/logs_test.go (hunk 10 above)
Comment (Haleygo) [reply pkg/routes/logs_test.go]: > How about "422 Unprocessable Entity"? 404 seems a bit misleading here.

sounds good!

Comment (Haleygo) [reply pkg/routes/logs_test.go]: > I would focus on tests that show the desired behavior and show that the fix results in that desired behavior. I found this test confusing.

You are absolutely right, http.server in test file is confusing. Now I remove it and add some comments in func logFileNameIsTooLong() to explain the check, should be easier to read now. What do you think?

Comment (jpbetz) [reply pkg/routes/logs_test.go]: > > How about "422 Unprocessable Entity"? 404 seems a bit misleading here.
> 
> sounds good!

Oh wait, I'm sorry. It looks like this check on a file path that is not yet matched up with an existing file.  So if the stat fails, the file cannot possibly exist?  You might have been right to use 404 to begin with. My apologies. LGTM otherwise

Comment (Haleygo) [reply pkg/routes/logs_test.go]: yeah, 404 maybe more suitable here.
Change it back now, thanks for reviewing!

File: pkg/routes/logs_test.go [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+		t.Error("failed to check oversize filename")
+	}
+
+	// check file with normal name which doesn't exist.
+	if logFileNameIsTooLong(normalFileName) {
+		t.Error("failed to check normal filename")
+	}
+
+	// check file with normal name which does exist.
+	_, err := os.Create(normalFileName)
```
Comment (yliaog) [inline pkg/routes/logs_test.go:40]: what about having a similar test case for oversizeFileName, i.e. _, err := os.Create(oversizeFileName)

File: pkg/routes/logs.go [hunk 14]
```diff
@@ -42,10 +44,28 @@ func (l Logs) Install(c *restful.Container) {
...
 
 func logFileListHandler(req *restful.Request, resp *restful.Response) {
 	logdir := "/var/log"
 	http.ServeFile(resp.ResponseWriter, req.Request, logdir)
 }
+
+// logFileNameIsTooLong checks filename length, returns true if it's longer than 255.
+// cause http.ServeFile returns default error code 500 except for NotExist and Forbidden, but we need to separate the real 500 from oversize filename here.
+func logFileNameIsTooLong(filePath string) bool {
+	_, err := os.Stat(filePath)
```
Comment (yliaog) [inline pkg/routes/logs.go:64]: does this work for platform other than linux?

Comment (jpbetz) [reply pkg/routes/logs.go:64]: I think so?

https://golang.org/src/os/:

```
stat.go |   | 733
-- | -- | --
stat_aix.go |   | 1206
stat_darwin.go |   | 1216
stat_dragonfly.go |   | 1175
stat_freebsd.go |   | 1199
stat_js.go |   | 1250
stat_linux.go |   | 1189
stat_netbsd.go |   | 1192
stat_openbsd.go |   | 1182
stat_plan9.go |   | 2353
stat_solaris.go |   | 1175
stat_test.go |   | 6121
stat_unix.go |   | 1404
stat_windows.go |   | 3641
```

I don't know how many of the OS implementations actually return this error though.

**Comment by jpbetz** [comment]
/lgtm

/assign @deads2k
for approval

**Comment by Haleygo** [comment]
@deads2k
PTAL, thanks
