### PR TITLE
Fixes the unit tests to be more tolerant with error messages

### LINKED ISSUE #96853: k8s unit tests fail with a mismatch in error message while run with master golang
**What happened**:
Below k8s UT fail when run with master-golang.
1. k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
error:=== RUN   TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
I1124 05:38:14.686883   60889 state_mem.go:36] [cpumanager] initializing new in-memory state store
    state_checkpoint_test.go:236: unexpected error while creatng checkpointState: could not restore state from checkpoint: json: unexpected end of JSON input, please drain this node and delete the CPU manager checkpoint file "/tmp/cpumanager_state_test479660663/cpumanager_checkpoint_test" before restarting Kubelet
    --- FAIL: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON (0.00s)
2. k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestStrategicMergePatchInvalid
error:=== RUN   TestStrategicMergePatchInvalid
    rest_test.go:127: expected "invalid character 'b' looking for beginning of value", got "json: invalid character 'b' looking for beginning of value"
--- FAIL: TestStrategicMergePatchInvalid (0.00s)
3. k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestJSONPatch
error:=== RUN   TestJSONPatch
    rest_test.go:175: invalid-syntax: expected error invalid character 'i' looking for beginning of value, but got json: invalid character 'i' looking for beginning of value
--- FAIL: TestJSONPatch (0.00s)
4. k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand: TestV4ErrorDecoder expand_less
error:=== RUN   TestV4ErrorDecoder
    v4_test.go:68: wrong error for message "{": want="error stream protocol error: unexpected end of JSON input in \"{\"", got="error stream protocol error: json: unexpected end of JSON input in \"{\""
--- FAIL: TestV4ErrorDecoder (0.00s

**What you expected to happen**: The tests should pass with no error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have a stable version of golang installed
2. Install master go from upstream
git clone https://github.com/golang/go.git
cd go/src
./make.bash
cd ../..
cp -r ./go /usr/local
export PATH=/usr/local/go/bin:$PATH
3. Clone kubernetes repo and run the unit tests. (https://github.com/kubernetes/kubernetes)
**Anything else we need to know?**:
These failures are occurring due to mismatch of error messages between upstream go and the k8s tests.
There is an addition "json:" prefix to SyntaxError messages after this below commit:
https://github.com/golang/go/commit/6af088bfc66c13143c9ef46b4cf0805df77a8fbe
```
In Go 1.15, scanner.go:
func (e *SyntaxError) Error() string { return e.msg }
In Go master, scanner.go:
func (e *SyntaxError) Error() string { return "json: " + e.msg }
```
**Environment**:
- Kubernetes version (use `kubectl version`): latest source code from upstream
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):  "CentOS Linux 8 (Core)"
- Kernel (e.g. `uname -a`): Linux rajalakshmi-workspace 4.18.0-193.19.1.el8_2.ppc64le #1 SMP Mon Sep 14 14:48:04 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
- Install tools: 
[root@rajalakshmi-workspace go]# go version
go version devel +c72a448881 Fri Nov 20 00:54:43 2020 +0000 linux/ppc64le
[root@rajalakshmi-workspace go]#
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
**What type of PR is this?**
Fixes the Below Unit test Failures when run with master golang. Make the error messages more tolerant to avoid failures due to mismatch in messages.

    k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
    error:=== RUN TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON
    I1124 05:38:14.686883 60889 state_mem.go:36] [cpumanager] initializing new in-memory state store
    state_checkpoint_test.go:236: unexpected error while creatng checkpointState: could not restore state from checkpoint: json: unexpected end of JSON input, please drain this node and delete the CPU manager checkpoint file "/tmp/cpumanager_state_test479660663/cpumanager_checkpoint_test" before restarting Kubelet
    --- FAIL: TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON (0.00s)
    k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestStrategicMergePatchInvalid
    error:=== RUN TestStrategicMergePatchInvalid
    rest_test.go:127: expected "invalid character 'b' looking for beginning of value", got "json: invalid character 'b' looking for beginning of value"
    --- FAIL: TestStrategicMergePatchInvalid (0.00s)
    k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers: TestJSONPatch
    error:=== RUN TestJSONPatch
    rest_test.go:175: invalid-syntax: expected error invalid character 'i' looking for beginning of value, but got json: invalid character 'i' looking for beginning of value
    --- FAIL: TestJSONPatch (0.00s)
    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand: TestV4ErrorDecoder expand_less
    error:=== RUN TestV4ErrorDecoder
    v4_test.go:68: wrong error for message "{": want="error stream protocol error: unexpected end of JSON input in "{"", got="error stream protocol error: json: unexpected end of JSON input in "{""
    --- FAIL: TestV4ErrorDecoder (0.00s

**What this PR does / why we need it**:
To run UT with latest aster golang without failures.

**Which issue(s) this PR fixes**:

Fixes #96853
```

### CODE REVIEW

**Review by dsnet — CHANGES_REQUESTED** [review]
Please don't do any form of string comparison on error messages. Using `strings.Contains` or `regexp.Match` is only marginally better than before.

Instead, this should check whether the error type is a *json.SyntaxError. It's an exported type so that code can check whether a JSON error is related to syntax or not. Tests should never depend on the exact error message, which is subject to change in the future (i.e., not covered by the Go 1 compatibility promise).

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Please don't do any form of string comparison on error messages. Using `strings.Contains` or `regexp.Match` is only marginally better than before.
> 
> Instead, this should check whether the error type is a *json.SyntaxError. It's an exported type so that code can check whether a JSON error is related to syntax or not. Tests should never depend on the exact error message, which is subject to change in the future (i.e., not covered by the Go 1 compatibility promise).

Out of the four failures that this PR is trying to fix, none of them are of error type *json.SyntaxError. I checked them using the following piece of code:
```

import json "encoding/json"
switch err := err.(type) {
                case *json.SyntaxError:
                    fmt.Printf("It is a JSON Syntax Error %s", err.Error())
                default:
                    fmt.Printf("It is not a  JSON Syntax Error %s\n", err.Error())
                }
```
Two of failures are of the error Type BadRequest. which the test case is already verifying. **_Please let me know if you intend to remove the error message verification and only keep the type verification?_**

**TestStrategicMergePatchInvalid** https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go#L123:L128
**TestJSONPatch** https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go#L173:L180

The other two have the error Type as *errors.errorString. **_Kindly suggest on how to verify these tests for the error Type?_**
remotecommand/v4_test.go
**TestV4ErrorDecoder**

state/state_checkpoint_test.go
**TestCheckpointStateRestore/Restore_checkpoint_with_invalid_JSON**

**Comment by dsnet** [comment]
I'm not a maintainer of Kubernetes so I'm not the best person to answer how this is best to solved here, but I am a maintainer of the Go standard library. The exact message for errors is outside the [Go 1 compatibility guarantees](https://golang.org/doc/go1compat) and have changed in the past. For this reason, any form string comparison on messages produced by errors from the standard library is fundamentally relying on unspecified behavior. You could fix it today, but it will likely break again in the future.

Some suggestions:
* If a custom type like `BadRequest` supports error unwrapping, then [`errors.Unwrap`](https://golang.org/pkg/errors/#Unwrap) should be used to get the original error, after which you can check whether it is a `*json.SyntaxError`. If `BadRequest` doesn't support unwrapping, it begs the question why the test is checking the exact error message if the API itself provides no means to semantically discern the underlying error value. In such a case, I would argue simply checking whether an error occurred or not is sufficient.
* In general, tests should only test for properties of errors that are guaranteed by the public API of the packages that produce those errors. Comparing error messages is only really reliable if the message is produced by code that is written by the same maintainers as the test itself. For example, in https://github.com/kubernetes/kubernetes/blob/61dc69ac2cf936ccafb51e9d946097b62b4ead07/staging/src/k8s.io/client-go/tools/remotecommand/v4_test.go#L67, the test can perform a string prefix match on the error message, where it only checks whether the error contains a prefix that is produced by the code being tested (e.g., `"error stream protocol error: "`), but not anything after that point which may be produced by packages not owned by the same maintainers.

**Comment by Rajalakshmi-Girish** [comment]
"json: " prefix to SyntaxError messages" has been reverted through  [283d654](https://github.com/golang/go/commit/283d65413db75edbc4691c4fecf23228509436f0) hence the k8s unit tests with master go have stopped failing!

File: pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go [hunk 1]
```diff
@@ -227,8 +228,9 @@ func TestCheckpointStateRestore(t *testing.T) {
 			restoredState, err := NewCheckpointState(testingDir, testingCheckpoint, tc.policyName, tc.initialContainers)
 			if err != nil {
 				if strings.TrimSpace(tc.expectedError) != "" {
-					tc.expectedError = "could not restore state from checkpoint: " + tc.expectedError
-					if strings.HasPrefix(err.Error(), tc.expectedError) {
+					tc.expectedError = "could not restore state from checkpoint: " + "(.*)" + tc.expectedError
```
Comment (liggitt) [inline pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go:231]: expectedError is not intended to be a regex (the messages have special regex characters like `.`)... would it be sufficient to check `strings.Contains(err.Error(), "could not restore state from checkpoint") && strings.Contains(err.Error(), tc.expectedError)`?

File: staging/src/k8s.io/client-go/tools/remotecommand/v4_test.go [hunk 2]
```diff
@@ -64,7 +65,9 @@ func TestV4ErrorDecoder(t *testing.T) {
 		if want == "" {
 			want = "<nil>"
 		}
-		if got := fmt.Sprintf("%v", err); got != want {
+		got := fmt.Sprintf("%v", err)
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/tools/remotecommand/v4_test.go:68]: checking `strings.Contains(got, want)` and changing the expected error to just `unexpected end of JSON input` is probably sufficient

File: pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go (hunk 1 above)
Comment (Rajalakshmi-Girish) [reply pkg/kubelet/cm/cpumanager/state/state_checkpoint_test.go]: Done
