### PR TITLE
Fix a job quota related deadlock

### LINKED ISSUE #119775: CronJob gets stuck when jobs quota is reached
### What happened?

We (in Booking.com) run CronJobs in Kubernetes clusters with ResourceQuota's defined. When quota for # of jobs is reached we observed that CronJobs:
1. stop scheduling new jobs (because quota is reached),
2. don't clean the old jobs (despite # of jobs > history allows and the fact that it would unblock the CronJob new Jobs). 

The only way to progress is to remove enough Jobs to make room for a new Job in namespace quota. When we do that manually, the CronJob kicks in.

The workaround we found around the internet is to specify `ttlSecondsAfterFinished` for the job template. But it's not ideal as it's not a history-based limit, but a time-based limit, and often you want to have the last N jobs to be around for debugging.

### What did you expect to happen?

When jobs quota is reached and # of cronjob jobs exceeds specified the history limit, these jobs are deleted giving room for new jobs to run.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: job-quota
  namespace: default
spec:
  hard:
    count/jobs.batch: "1"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  successfulJobsHistoryLimit: 0
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world
              image: bash
              command: ["bash", "-c", "sleep 80"]
          restartPolicy: OnFailure
```

1. Wait for a first Job to be created (which will fill up the jobs quota) at X minute.
2. A job for X + 1 will fail to be created (because quota won't allow, and X job is still running).
3. All future attempts to create a new job by the controller will fail (check `kubectl get events --sort-by='.lastTimestamp' | tail`, you'll see re-occuring `Error creating job: jobs.batch "hello-world-cronjob-28187648" is forbidden: exceeded quota: job-quota, requested: count/jobs.batch=1, used: count/jobs.batch=1, limited: count/jobs.batch=1`).
4. The first job will never be cleaned (although it will be eligible, since history is 0).

### Anything else we need to know?

Looks like the problem was introduced in the `cronjob_controllerv2.go` implementation: if `jm.syncCronJob` returned an error, we return from the function and never invoke `jm.cleanupFinishedJobs`.:
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/controller/cronjob/cronjob_controllerv2.go#L199-L213

In the old `cronjob_controller.go` implementation this was not the case:
https://github.com/kubernetes/kubernetes/blob/0f77da5bd4809927e15d1658fb4aa8f13ad890a5/pkg/controller/cronjob/cronjob_controller.go#L137-L138

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:06:30Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.27) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ASverdlov**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In case ResourceQuota is used and sets a max # of jobs, a CronJob may get trapped in a deadlock:
  1. Job quota for a namespace is reached.
  2. CronJob controller can't create a new job, because quota is reached.
  3. Cleanup of jobs owned by a cronjob doesn't happen, because a control loop iteration is finished because of an error to create a job.

To fix this we stop early quitting from a control loop iteration when cronjob reconciliation failed and always let old jobs to be cleaned up.

#### Which issue(s) this PR fixes:

Fixes [#119775](https://github.com/kubernetes/kubernetes/issues/119775)

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue where a CronJob could fail to clean up Jobs when the ResourceQuota for Jobs had been reached.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 1]
```diff
@@ -25,6 +25,7 @@ import (
 	"time"
 
 	"github.com/robfig/cron/v3"
+	"k8s.io/klog/v2"
```
Comment (aojea) [inline pkg/controller/cronjob/cronjob_controllerv2.go:28]: this change is unnecesary

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 2]
```diff
@@ -199,13 +200,6 @@ func (jm *ControllerV2) sync(ctx context.Context, cronJobKey string) (*time.Dura
 	cronJobCopy, requeueAfter, updateStatus, err := jm.syncCronJob(ctx, cronJob, jobsToBeReconciled)
 	if err != nil {
 		logger.V(2).Info("Error reconciling cronjob", "cronjob", klog.KObj(cronJob), "err", err)
-		if updateStatus {
```
Comment (aojea) [inline pkg/controller/cronjob/cronjob_controllerv2.go:202]: without much experience on this controller this change looks like an important behavior change in the controller

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 1 above)
Comment (ASverdlov) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: Fixed

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 2 above)
Comment (ASverdlov) [reply pkg/controller/cronjob/cronjob_controllerv2.go:202]: There is exactly the same if-statement below, which is going to be executed unless there is a panic in the code, as there are no return-statements in-between: https://github.com/kubernetes/kubernetes/blob/16173c23baa3a6a7ad19233c963d165dc7f602d9/pkg/controller/cronjob/cronjob_controllerv2.go#L208-L214

**Comment by aojea** [comment]
/ok-to-test

code owners should take a look

Thanks

**Comment by pacoxu** [comment]
The issue seems to be a valid case.
/lgtm
/cc @soltysh @alaypatel07
for cronjob controller owners

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Fix a cronjob getting stuck when jobs quota is reached
+Fixed an issue where a CronJob could fail to clean up Jobs when the ResourceQuota for Jobs had been reached.
```

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 2 above)
Comment (sftim) [reply pkg/controller/cronjob/cronjob_controllerv2.go:202]: Could we nevertheless make attempt to update the status here, but with different error handling, and a comment in both places about the situation?

Logging that the status update failed is helpful; it's just the `return` statements that create a problem.

Any other logic refactor that ensures we attempt `cleanupFinishedJobs()` is also fine by me. Ideally we don't drop any observability along with that change.

Comment (sftim) [reply pkg/controller/cronjob/cronjob_controllerv2.go:202]: Maybe we should set `updateStatus` to true, but defer the update?

I'd like to see a clear comment that shows why this change is right. It might be, but I want the code and PR to explain why.

Comment (ASverdlov) [reply pkg/controller/cronjob/cronjob_controllerv2.go:202]: We can still remove the copy-paste like this: https://github.com/ASverdlov/kubernetes/commit/675e411ae6958bc6b07e7ae104480e316e403fd4.

Attempt on a clear comment on why it would work follows: let's compare 2 versions: because the following 2 versions of code are equivalent:
```go
	cronJobCopy, requeueAfter, updateStatus, err := jm.syncCronJob(ctx, cronJob, jobsToBeReconciled)
	if err != nil {
		logger.V(2).Info("Error reconciling cronjob", "cronjob", klog.KObj(cronJob), "err", err)

                COPY_PASTE()
		return nil, err
	}

        COPY_PASTE()

	if requeueAfter != nil {
		logger.V(4).Info("Re-queuing cronjob", "cronjob", klog.KObj(cronJob), "requeueAfter", requeueAfter)
		return requeueAfter, nil
	}
	// this marks the key done, currently only happens when the cronjob is suspended or spec has invalid schedule format
	return nil, nil

```
and

```go
	cronJobCopy, requeueAfter, updateStatus, reconciliationErr := jm.syncCronJob(ctx, cronJob, jobsToBeReconciled)
	if err != nil {
		logger.V(2).Info("Error reconciling cronjob", "cronjob", klog.KObj(cronJob), "err", err)
	}
        
        COPY_PASTE()

	if requeueAfter != nil {
		logger.V(4).Info("Re-queuing cronjob", "cronjob", klog.KObj(cronJob), "requeueAfter", requeueAfter)
		return requeueAfter, reconciliationErr
	}
	// this marks the key done, currently only happens when the cronjob is suspended or spec has invalid schedule format
	return nil, reconciliationErr

```

* In case `jm.syncCronJob` doesn't return an error, they are line-by-line the same (if you ignore renaming of the error variable.
* In case `jm.syncCronJob` does return an error, the only difference is: latter code also returns a `requeueAfter` in case it was set. But `jm.syncCronJob()` never returns a `requeueAfter != nil` when it returns an error, so in practice it doesn't change the current behaviour.

**Comment by alaypatel07** [comment]
apologies for the delay, I'll take a look at this.

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 3]
```diff
@@ -435,7 +441,7 @@ func (jm *ControllerV2) syncCronJob(
 		if !found && !IsJobFinished(j) {
 			cjCopy, err := jm.cronJobControl.GetCronJob(ctx, cronJob.Namespace, cronJob.Name)
 			if err != nil {
-				return nil, nil, updateStatus, err
+				return cronJob, nil, updateStatus, err
```
[the remark this answers is not in the document]
Comment (ASverdlov) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: I changed the code following your suggestion here: https://github.com/kubernetes/kubernetes/pull/119776#discussion_r1311346986. And we no longer return `cronJobCopy` and `updateStatus` from `jm.syncCronJob()`, but rather accept the pointers to them as parameters, so there is now also no chance to mess them up by chance in this place by returning something different.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
