### PR TITLE
test: wait for nodes to be in scheduler's cache

### LINKED ISSUE #131515: TestNodeAffinityScoring / scheduler integration flake
> Pod pod-with-node-affinity got scheduled on an unexpected node: testnode-3. Expected node: testnode-4.
> --- FAIL: TestNodeAffinityScoring (7.08s)

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/131511/pull-kubernetes-integration/1916851016070860800

spotted on https://github.com/kubernetes/kubernetes/pull/131511 which should not impact this test at all

/sig scheduling
/kind flake

### PR DESCRIPTION
**Pull request by saza-ku**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

In priorities_test.go, it must wait for nodes to be added to the scheduler's cache to prevent pods are scheduled before nodes are added to the cache. This PR makes sure of it.

#### Which issue(s) this PR fixes:

Fixes #131515

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ayestoro** [comment]
Very clean code with good test coverage. This is a great example of best practices.

**Comment by fivemeyestoreserver** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

File: test/integration/scheduler/scoring/priorities_test.go [hunk 1]
```diff
@@ -296,18 +296,18 @@ func TestNodeResourcesScoring(t *testing.T) {
...
 	testCtx := initTestSchedulerForScoringTests(t, nodeaffinity.Name, nodeaffinity.Name)
-	// Add a few nodes.
-	_, err := createAndWaitForNodesInCache(testCtx, "testnode", st.MakeNode(), 4)
-	if err != nil {
-		t.Fatal(err)
-	}
 	// Add a label to one of the nodes.
 	labelKey := "kubernetes.io/node-topologyKey"
 	labelValue := "topologyvalue"
 	labeledNode, err := createNode(testCtx.ClientSet, st.MakeNode().Name("testnode-4").Label(labelKey, labelValue).Obj())
```
Comment (AxeZhan) [inline test/integration/scheduler/scoring/priorities_test.go:302]: You should also wait for this `labeledNode` to be presented in the cache, no?

Comment (saza-ku) [reply test/integration/scheduler/scoring/priorities_test.go]: Definietely. I've made sure of it.
