### PR TITLE
Ignore GCS public-read ACL set on Windows kube-up.

### LINKED ISSUE #96390: Windows kube-up for GCE breaks if GCS bucket for build artifacts is set to Uniform ACLs mode.
**What happened**:
Follow the steps via https://github.com/kubernetes/kubernetes/blob/release-1.17/cluster/gce/windows/README-GCE-Windows-kube-up.md.

```bash
+ gsutil -m -q -h 'Cache-Control:private, max-age=0' cp /usr/local/google/home/jeremyedwards/github/kubernetes/_output/release-tars/kubernetes-server-linux-amd64.tar.gz /usr/local/google/home/jeremyedwards/github/kubernetes/_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1 gs://kubernetes-staging-381fa6ca58/kubernetes-devel
+ gsutil -m acl ch -g all:R gs://kubernetes-staging-381fa6ca58/kubernetes-devel/kubernetes-server-linux-amd64.tar.gz gs://kubernetes-staging-381fa6ca58/kubernetes-devel/kubernetes-server-linux-amd64.tar.gz.sha1
+ kube::util::cleanup-temp-dir
+ rm -rf /tmp/tmp.xsm26BSC0b
```

**What you expected to happen**:

A Kubernetes cluster with Windows nodes should be running in GCE (not GKE).

**How to reproduce it (as minimally and precisely as possible)**:
Run the steps from https://github.com/kubernetes/kubernetes/blob/release-1.17/cluster/gce/windows/README-GCE-Windows-kube-up.md with a project that has https://cloud.google.com/storage/docs/org-policy-constraints#uniform-access turned on.

**Anything else we need to know?**:

The fix is simple a PR in Kubernetes v1.20 fixed it. https://github.com/kubernetes/kubernetes/commit/e99dbbde62015c15b516cdf39edb8d32fcd71729#diff-09816a4dd2fd3cf28f97bf9f34330a66336c631830b103d0c96d71eb632dab0dR244

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jeremyje**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The `kube-up` script for Windows will attempt to set `public-read` ACLs on the GCS objects it just uploaded to setup Kubernetes. If the GCS bucket is set to [uniform-access](https://cloud.google.com/storage/docs/uniform-bucket-level-access) then this will always fail. This can happen due to [org policy constraints](https://cloud.google.com/storage/docs/org-policy-constraints#uniform-access).

**Which issue(s) this PR fixes**:

Fixes #96390

**Special notes for your reviewer**:
This is a partial backport of https://github.com/kubernetes/kubernetes/commit/e99dbbde62015c15b516cdf39edb8d32fcd71729#diff-09816a4dd2fd3cf28f97bf9f34330a66336c631830b103d0c96d71eb632dab0dR244.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -241,7 +241,7 @@ function copy-to-staging() {
 
   echo "${hash}" > "${tar}.sha512"
   gsutil -m -q -h "Cache-Control:private, max-age=0" cp "${tar}" "${tar}.sha512" "${staging_path}"
-  gsutil -m acl ch -g all:R "${gs_url}" "${gs_url}.sha512" >/dev/null 2>&1
+  gsutil -m acl ch -g all:R "${gs_url}" "${gs_url}.sha512" >/dev/null 2>&1 || true
```
Comment (liggitt) [inline cluster/gce/util.sh:244]: Is this line specific to windows? I wouldn't have expected to ignore an error here

Comment (jeremyje) [reply cluster/gce/util.sh:244]: Admittedly this isn't the best way to handle this issue. This is the fix in v1.19+. The proper solution is to set public-read on the bucket if this operation fails but that also has bad side effects. All in all there's not really a great workaround here other than just making this optional. Lastly, this probably does impact Linux as well. I was mainly testing Windows clusters but this silent failure happens before cluster bringup.

Comment (jeremyje) [reply cluster/gce/util.sh:244]: Ping this still breaks. To reiterate this is the logic that newer versions of Kubernetes does so this is a backport of the awful fix.

**Comment by SergeyKanzhelev** [comment]
Since it is a cherry-pick from master,

/lgtm
/triage accepted
/priority important-soon

File: cluster/gce/util.sh (hunk 1 above)
Comment (SergeyKanzhelev) [reply cluster/gce/util.sh:244]: this is the PR where it was introduced: https://github.com/kubernetes/kubernetes/pull/92668

Comment (SergeyKanzhelev) [reply cluster/gce/util.sh:244]: @jeremyje do you need to grab a second line from the source PR?

**Comment by SergeyKanzhelev** [comment]
as the original PR approval:

/assign @BenTheElder

**Comment by BenTheElder** [comment]
cc @amwat

**Comment by marosset** [comment]
@kubernetes/release-managers to perform a cherry-pick review.
