### PR TITLE
schedule pod availability checks at the correct time in ReplicaSets

### LINKED ISSUE #108266: Kubernetes controller manager may fail to manage deployment rollout with minReadySeconds and pod restarts
### What happened?

```
kubectl rollout restart deployment alpine ; kubectl rollout status deployment alpine
``` 

may exceed the deployment rollout progress deadlines if the deployment sets `minReadySeconds` and a new pod restarts during the rollout before the minimum ready seconds.

### What did you expect to happen?

Deployment rollout is successful.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the following deployment on a 3 node cluster.  We are using 3 nodes here to simulate a multi zone cluster that spreads pods across zones.

```
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  minReadySeconds: 30
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: alpine
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpine
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["alpine"]
            topologyKey: kubernetes.io/hostname
      containers:
      - image: alpine:latest
        imagePullPolicy: IfNotPresent
        name: alpine
        command: ["sh", "-c", "if [[ ! -e /tmp/okay ]]; then touch /tmp/okay; sleep 15; exit; else sleep 100000; fi"]
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
```

then run `kubectl rollout restart deployment alpine ; kubectl rollout status deployment alpine`.

### Anything else we need to know?

Removing `minReadySeconds` from the example deployment will yield a successful rollout.  In addition, finding the Kubernetes controller manager leader via `kubectl get leases -n kube-system` and killing the leader will also allow the rollout to be successful.  The rollout will also succeed if the old replicaset is scaled down to zero replicas.

### Kubernetes version

Failure occurs on Kubernetes versions 1.20, 1.21, 1.22, 1.23 and 1.24.

### Cloud provider

N/A

### OS version

N/A

### Install tools

IBM Cloud Kubernetes Service

### Container runtime (CRI) and and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug
/sig apps

#### What this PR does / why we need it:
Replica set might skip availability checks in certain situations and not update `availableReplicas`. This also stops deployment from progressing.

This applies to pods that are struggling to become `Ready` or become Ready with a certain delay.

For more details, please see: https://github.com/kubernetes/kubernetes/issues/108266#issuecomment-1302639795

#### Which issue(s) this PR fixes:

Fixes #108266

#### Special notes for your reviewer:
Similar fix is planned for the other controllers as well.

#### Does this PR introduce a user-facing change?

```release-note
ReplicaSets and Deployments should always count `.status.availableReplicas` at the correct time without a delay. This results in faster reconciliation of Deployment conditions and faster, unblocked Deployment rollouts. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

prerequisite: https://github.com/kubernetes/kubernetes/pull/132122

```docs

```

### CODE REVIEW

**Review by hashim21223445 — APPROVED** [review]

**Comment by atiratree** [comment]
flake
/test pull-kubernetes-node-e2e-containerd

File: pkg/controller/replicaset/replica_set.go [hunk 1]
```diff
@@ -794,14 +794,19 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
 		return manageReplicasErr
 	}
-	// Resync the ReplicaSet after MinReadySeconds as a last line of defense to guard against clock-skew.
+	// Plan the next availability check as a last line of defense against queue preemption and guard against clock-skew.
 	if updatedRS.Spec.MinReadySeconds > 0 &&
 		updatedRS.Status.ReadyReplicas == *(updatedRS.Spec.Replicas) &&
 		updatedRS.Status.AvailableReplicas != *(updatedRS.Spec.Replicas) {
-		nextSyncInSeconds = ptr.To(int(updatedRS.Spec.MinReadySeconds))
+		if nextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, rsc.clock.Now()); nextCheck != nil {
+			nextSyncDuration = ptr.To(*nextCheck + time.Second) // Add a second to avoid a clock-skew.
```
Comment (mimowo) [inline pkg/controller/replicaset/replica_set.go]: Adding a second does not feel like a reliable strategy, and may cause unnecessary delays, or subtle bugs if the code is not ready for skew of >1s. 

Is it a common practice in other controllers? For example, we don't use this tactic in Job controller when handling activeDeadlineSeconds, see [here](https://github.com/kubernetes/kubernetes/blob/cc1fc3eea0e3e2b2674b6dd1cd6db01863088eee/pkg/controller/job/job_controller.go#L985-L987).

IIUC, even if the clock is skewed, we should just schedule another sync. If this is the case, I would prefer to avoid the extra 1s added.

**Comment by mimowo** [comment]
Suggestion about the release note to clarify `spec.minReadySeconds` as the preconditions, so that cluster admins can 
easier identify if the issue may be affecting them. Also, I think it is important to mention the "Available" condition, because it was IIUC the main cause of the timeout in the reported issue. 
```
Fix the bug when ReplicaSets and Deployments, when using `spec.minReadySeconds`, could update the
`.status.availableReplicas` and the "Available" condition with a significant delay, potentially causing timeouts.
```

File: pkg/api/v1/pod/util.go [hunk 2]
```diff
@@ -329,6 +330,23 @@ func IsPodAvailable(pod *v1.Pod, minReadySeconds int32, now metav1.Time) bool {
 	return false
 }
 
+func NextPodAvailabilityCheck(pod *v1.Pod, minReadySeconds int32, now time.Time) *time.Duration {
```
Comment (mimowo) [inline pkg/api/v1/pod/util.go]: nit, but I would suggest moving it as unexported helper in controller_utils.go, because Pods don't really know about the "next availability check". Making it exported expands the API surface of the package which does not seem necessary.

File: pkg/controller/replicaset/replica_set.go [hunk 3]
```diff
@@ -794,14 +794,19 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
+		} else {
+			// fall back to MinReadySeconds
```
Comment (mimowo) [inline pkg/controller/replicaset/replica_set.go]: I think this warrants a bit more of a comment. The current is self-explanatory as it is in "else".

IIUC, the fallback is just a safeguard, but should not be needed "in principle". So maybe:

```
// Safeguard fallback to MinReadySeconds. It might be used in case we are waiting for some 
// Pods to be created or scheduled while all other Pods are already available.
```

File: pkg/controller/replicaset/replica_set_test.go [hunk 4]
```diff
@@ -1618,6 +1618,80 @@ func TestDoNotAdoptOrCreateIfBeingDeletedRace(t *testing.T) {
...
+		t.Errorf("Expected updated ReplicaSet to contain available replicas %v, got %v instead",
+			0, updatedRs.Status.AvailableReplicas)
+	}
+
+	if got, want := manager.queue.Len(), 0; got != want {
+		t.Errorf("queue.Len() = %v, want %v", got, want)
+	}
+
+	// RS should be re-queued after 3s to recompute Available (1 extra second for a clock-skew, 200ms for the test).
+	time.Sleep(3*time.Second + 200*time.Millisecond)
```
Comment (mimowo) [inline pkg/controller/replicaset/replica_set_test.go]: Not blocker, but I think this sleep makes the test unnecessarily long. 

If the purpose of the test is to ensure the new logic is plugged into the RS code, then I think a single Pod would be sufficient to repro, making the test faster. 

An alternative approach would be to use passing clock instead, and shift it, but I'm not sure how much refactoring is needed.

File: pkg/api/v1/pod/util.go (hunk 2 above)
Comment (kow3ns) [reply pkg/api/v1/pod/util.go]: Agree with this. This functionality is specific to workload controllers that operate on Pods.

File: pkg/controller/replicaset/replica_set.go [hunk 5]
```diff
@@ -794,14 +794,19 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
 	if manageReplicasErr != nil {
 		return manageReplicasErr
 	}
-	// Resync the ReplicaSet after MinReadySeconds as a last line of defense to guard against clock-skew.
+	// Plan the next availability check as a last line of defense against queue preemption and guard against clock-skew.
 	if updatedRS.Spec.MinReadySeconds > 0 &&
 		updatedRS.Status.ReadyReplicas == *(updatedRS.Spec.Replicas) &&
 		updatedRS.Status.AvailableReplicas != *(updatedRS.Spec.Replicas) {
-		nextSyncInSeconds = ptr.To(int(updatedRS.Spec.MinReadySeconds))
+		if nextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, rsc.clock.Now()); nextCheck != nil {
```
Comment (kow3ns) [inline pkg/controller/replicaset/replica_set.go]: consider using a happy path to avoid the else condition altogether
```go
// Safeguard fallback to MinReadySeconds. It might be used in case we are waiting for some 
// Pods to be created or scheduled while all other Pods are already available.
nextSyncDuration = ptr.To(time.Duration(updatedRS.Spec.MinReadySeconds) * time.Second)

// Compute the next sync based on Pod availability
if nextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, rsc.clock.Now()); nextCheck != nil {
    nextSyncDuration = ptr.To(*nextCheck)
}
```

File: pkg/api/v1/pod/util.go (hunk 2 above)
Comment (atiratree) [reply pkg/api/v1/pod/util.go]: Originally I added it just below the `IsPodAvailable` function since it mostly shares the implementation for easier tracking.

But, I agree that availability is not part of the pod API and it could be confusing to have it here.

I have moved it to the controller_utils.go.

File: pkg/controller/replicaset/replica_set.go (hunk 1 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: After some testing, I think we can remove the 1s, and try to resync instead if the availability is not reached.

Btw, there are actually two skews:

- https://github.com/kubernetes/kubernetes/issues/39785#issuecomment-279959133 which I think we will fix with the repeating resyncs
- https://github.com/kubernetes/kubernetes/issues/29229 kubelet/master skew which I am not sure we can easily fix as far as I can see

File: pkg/controller/replicaset/replica_set.go (hunk 3 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: I have changed the logic in this place. PTAL, anyway I am still keeping the MinReadySeconds as a fallback.

There is actually no explanation for including it, except as a safeguard against a mistake in our time handling code.

File: pkg/controller/replicaset/replica_set_test.go (hunk 4 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set_test.go]: We need more pods to test it properly, I have updated the logic and the test. However we can lower the test runtime under 1s which I think should be manageable.

File: pkg/controller/replicaset/replica_set.go (hunk 5 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: Thanks, I have simplified the else branch as suggested. Nevertheless, I have also updated the logic to cover more edge cases, so sadly it is a bit more complicated now.

File: pkg/controller/replicaset/replica_set.go [hunk 6]
```diff
@@ -764,14 +767,23 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
 		return manageReplicasErr
 	}
-	// Resync the ReplicaSet after MinReadySeconds as a last line of defense to guard against clock-skew.
+	// Plan the next availability check as a last line of defense against queue preemption (we have one queue key for checking availability of all the pods)
+	// or early sync (see https://github.com/kubernetes/kubernetes/issues/39785#issuecomment-279959133 for more info).
 	if updatedRS.Spec.MinReadySeconds > 0 &&
-		updatedRS.Status.ReadyReplicas == *(updatedRS.Spec.Replicas) &&
-		updatedRS.Status.AvailableReplicas != *(updatedRS.Spec.Replicas) {
-		nextSyncInSeconds = ptr.To(int(updatedRS.Spec.MinReadySeconds))
+		updatedRS.Status.ReadyReplicas != updatedRS.Status.AvailableReplicas {
```
Comment (atiratree) [inline pkg/controller/replicaset/replica_set.go:773]: Running the check also in the middle of the rollout and not just at the end. This is useful if each pod has a varying readiness times.

File: pkg/controller/replicaset/replica_set.go [hunk 7]
```diff
@@ -764,14 +767,23 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
+		// Safeguard fallback to the .spec.minReadySeconds to ensure that we always end up with .status.availableReplicas updated.
+		nextSyncDuration = ptr.To(time.Duration(updatedRS.Spec.MinReadySeconds) * time.Second)
+		if nextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, now); nextCheck != nil {
+			// There must be a next check, even if the following FindMinNextPodAvailabilityCheck call returns nil.
+			nextSyncDuration = ptr.To(time.Duration(0))
+			// There is a delay since the last Now() call. Update the nextSyncDuration.
+			if updatedNextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, rsc.clock.Now()); updatedNextCheck != nil {
+				nextSyncDuration = ptr.To(*updatedNextCheck)
```
Comment (atiratree) [inline pkg/controller/replicaset/replica_set.go]: Running the check twice to reach the availability at more precise time. I am predicting a race here though...

File: pkg/controller/replicaset/replica_set.go [hunk 8]
```diff
@@ -497,13 +497,14 @@ func (rsc *ReplicaSetController) updatePod(logger klog.Logger, old, cur interfac
...
+		// If there are multiple pods with varying readiness times, we cannot correctly track it
+		// with the current queue. Further resyncs are attempted at the end of the syncReplicaSet
+		// function.
 		// Note that this still suffers from #29229, we are just moving the problem one level
 		// "closer" to kubelet (from the deployment to the replica set controller).
 		if !podutil.IsPodReady(oldPod) && podutil.IsPodReady(curPod) && rs.Spec.MinReadySeconds > 0 {
 			logger.V(2).Info("pod will be enqueued after a while for availability check", "duration", rs.Spec.MinReadySeconds, "kind", rsc.Kind, "pod", klog.KObj(oldPod))
-			// Add a second to avoid milliseconds skew in AddAfter.
-			// See https://github.com/kubernetes/kubernetes/issues/39785#issuecomment-279959133 for more info.
-			rsc.enqueueRSAfter(rs, (time.Duration(rs.Spec.MinReadySeconds)*time.Second)+time.Second)
```
Comment (atiratree) [inline pkg/controller/replicaset/replica_set.go:506]: As mentioned in https://github.com/kubernetes/kubernetes/pull/132121#discussion_r2208973438, this should be covered by the resyncs now.

File: pkg/controller/replicaset/replica_set_test.go [hunk 9]
```diff
@@ -1618,6 +1618,85 @@ func TestDoNotAdoptOrCreateIfBeingDeletedRace(t *testing.T) {
...
+	stopCh := make(chan struct{})
+	defer close(stopCh)
+
+	manager, informers := testNewReplicaSetControllerFromClient(t, client, stopCh, BurstReplicas)
+	if err := informers.Apps().V1().ReplicaSets().Informer().GetIndexer().Add(rs); err != nil {
+		t.Fatal(err)
+	}
+
+	now := time.Now()
+	pod1 := newPod("foobar-1", rs, v1.PodPending, nil, true)
```
Comment (atiratree) [inline pkg/controller/replicaset/replica_set_test.go:1638]: note the Pending status to test the partial readiness & availability updates

**Review by atiratree — COMMENTED** [review]
@mimowo @kow3ns thanks for the review - the PR is updated and covering more edge cases now.

File: pkg/controller/replicaset/replica_set.go [hunk 10]
```diff
@@ -764,14 +767,23 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
+	// or early sync (see https://github.com/kubernetes/kubernetes/issues/39785#issuecomment-279959133 for more info).
 	if updatedRS.Spec.MinReadySeconds > 0 &&
-		updatedRS.Status.ReadyReplicas == *(updatedRS.Spec.Replicas) &&
-		updatedRS.Status.AvailableReplicas != *(updatedRS.Spec.Replicas) {
-		nextSyncInSeconds = ptr.To(int(updatedRS.Spec.MinReadySeconds))
+		updatedRS.Status.ReadyReplicas != updatedRS.Status.AvailableReplicas {
+		// Safeguard fallback to the .spec.minReadySeconds to ensure that we always end up with .status.availableReplicas updated.
+		nextSyncDuration = ptr.To(time.Duration(updatedRS.Spec.MinReadySeconds) * time.Second)
+		if nextCheck := controller.FindMinNextPodAvailabilityCheck(activePods, updatedRS.Spec.MinReadySeconds, now); nextCheck != nil {
+			// There must be a next check, even if the following FindMinNextPodAvailabilityCheck call returns nil.
```
Comment (mimowo) [inline pkg/controller/replicaset/replica_set.go]: I think this comment describes the situation for `nextCheck=nil`, but is inside `nextCheck!=nil`, so I suggest moving it up and merging with the comment `// Safeguard fallback to the .spec.minReadySeconds...`.

File: pkg/controller/replicaset/replica_set.go (hunk 7 above)
Comment (mimowo) [reply pkg/controller/replicaset/replica_set.go]: I think the second call to `FindMinNextPodAvailabilityCheck` is not needed. We can achieve the very same effect by changing the first invocation of `FindMinNextPodAvailabilityCheck` from `now` to `rsc.clock.Now()`.

I'm also ok with using just `now` for simplicity. The max delay due to this would be the length of the `updateReplicaSetStatus` request, which should generally be sub-second according to the SLO: "In default Kubernetes installation, for every (resource, verb) pair, excluding virtual and aggregated resources and Custom Resource Definitions, 99th percentile per cluster-day <= 1s": https://github.com/kubernetes/community/blob/master/sig-scalability/slos/api_call_latency.md.
 
Consider the scenario:
 1. we compute `calculateStatus` using `now`
 2. we wait for `updateReplicaSetStatus` and it happens to take 3s (above SLO)
 3. we compute `FindMinNextPodAvailabilityCheck` using previous `now` and it says schedule next sync in `30`s. Using `rsc.clock.Now()` we would get `27`s (as the clocked already passed by the delay delta). I think it is ok to schedule after 30s. If the deployment already is running over SLO, then additional 3s of delay for the resync does seem to make much difference, IMO. The resync will happen anyway within reasonable time.

Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: In your example it is okay, but there are more troublesome edge cases when using `rsc.clock.Now()`.

For example, if we run a sync 1s before the availability check (note that the syncs can be randomly triggered by any pod update). And if the `updateReplicaSetStatus` call takes over 1s, `FindMinNextPodAvailabilityCheck` would return `nil` and we would fallback to `MinReadySeconds` (which is an arbitrary value and can be even couple of minutes). I believe such delay/race is too much and will lead to bug reports.  It is thus important to use the same `now` in the first `FindMinNextPodAvailabilityCheck` call as the  `calculateStatus` uses.

I agree that the second call is not needed and <= 1s delay should be okay. On the other hand `updateReplicaSetStatus` can result in multiple calls due to for example a conflict.

This piece of code affects a lot of things (e.g. completion of a Deployment rollout. I would prefer to keep it performant and add this extra check since we are aware that the delay has occurred.

File: pkg/controller/replicaset/replica_set.go (hunk 10 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: Please note the word `following`. By setting `nextSyncDuration = 0`, we ensure that the sync happens ASAP even if it got lost due to the apiserver delay (we are past the check).

Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: I have updated the comments in this block to better reflect the intent. Please let me know if you see any mistakes or have any suggestions.

File: pkg/controller/replicaset/replica_set.go (hunk 7 above)
Comment (mimowo) [reply pkg/controller/replicaset/replica_set.go]: > On the other hand updateReplicaSetStatus can result in multiple calls due to for example a conflict.

Yeah, I missed that `updateReplicaSetStatus` can retry, but `statusUpdateRetries` is hardcoded to one, so IIUC this is worst case 2 calls, which still shouldn't pile up to large delay when just using `now`.

> This piece of code affects a lot of things (e.g. completion of a Deployment rollout. I would prefer to keep it performant and add this extra check since we are aware that the delay has occurred.

I'm ok with that (though myself I prefer simplicity of using just `now`). 

Since the logic is non-trivial I would like to propose to encapsulate all the logic inside `FindMinNextPodAvailabilityCheck` which would always return time.Duration, and not ptr. Currently, the function name suggests it is the next availability check, but it may still be post-processed. Alternatively introduce another function encapsulating the logic so that we can unit test it, and unexport FindMinNextPodAvailabilityCheck. wdyt?

Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: > worst case 2 calls

nit; 3 calls ;) - there is also one get call

> encapsulate all the logic 

Creating another function to improve readability and testability sounds good to me. We can unexport FindMinNextPodAvailabilityCheck for now, but I would like to submit similar fix to other controllers so we might need to export it again later.

File: pkg/controller/controller_utils.go [hunk 11]
```diff
@@ -1030,6 +1031,59 @@ func CountTerminatingPods(pods []*v1.Pod) int32 {
...
+// passing lastOwnerStatusEvaluation. This ensures that we will not skip any pods that might become available
+// (findMinNextPodAvailabilityCheck would return nil in the future time), since the owner status evaluation.
+// clock is then used to calculate the precise time for the next availability check.
+func FindMinNextPodAvailabilityCheckAccordingToLastOwnerStatusEvaluation(pods []*v1.Pod, minReadySeconds int32, lastOwnerStatusEvaluation time.Time, clock clock.PassiveClock) *time.Duration {
+	var nextCheck *time.Duration
+	if nextCheckAccordingToOwnerStatusEvaluation, checkPod := findMinNextPodAvailabilityCheck(pods, minReadySeconds, lastOwnerStatusEvaluation); nextCheckAccordingToOwnerStatusEvaluation != nil {
+		// There must be a nextCheck. We try to calculate a more precise value for the next availability check.
+		// Fall back to 0 (immediate check) in case the following nextPodAvailabilityCheck call (with a refreshed Now) returns nil, as we might be past the check.
+		nextCheck = ptr.To(time.Duration(0))
+		if updatedNextCheck := nextPodAvailabilityCheck(checkPod, minReadySeconds, clock.Now()); updatedNextCheck != nil {
```
Comment (atiratree) [inline pkg/controller/controller_utils.go]: I hope it is more clear now, after extracting the logic into this function.

Also, the tests uncovered a small bug in the second check - we need to specify a pod we want to check. Otherwise we could be preempted by a later pod.

File: pkg/controller/replicaset/replica_set.go (hunk 7 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: Done, PTAL.

File: pkg/controller/replicaset/replica_set.go [hunk 12]
```diff
@@ -764,14 +767,19 @@ func (rsc *ReplicaSetController) syncReplicaSet(ctx context.Context, key string)
...
-		updatedRS.Status.ReadyReplicas == *(updatedRS.Spec.Replicas) &&
-		updatedRS.Status.AvailableReplicas != *(updatedRS.Spec.Replicas) {
-		nextSyncInSeconds = ptr.To(int(updatedRS.Spec.MinReadySeconds))
+		updatedRS.Status.ReadyReplicas != updatedRS.Status.AvailableReplicas {
+		// Safeguard fallback to the .spec.minReadySeconds to ensure that we always end up with .status.availableReplicas updated.
+		nextSyncDuration = ptr.To(time.Duration(updatedRS.Spec.MinReadySeconds) * time.Second)
+		// Use the same time (now) for calculating status and nextSyncDuration to have the matching pod availability data.
+		if nextCheck := controller.FindMinNextPodAvailabilityCheckAccordingToLastOwnerStatusEvaluation(activePods, updatedRS.Spec.MinReadySeconds, now, rsc.clock); nextCheck != nil {
+			nextSyncDuration = nextCheck
+		}
```
Comment (mimowo) [inline pkg/controller/replicaset/replica_set.go]: It is non-blocking, but I think the code will read better, and allow for better unit-testing (the second point):
1. rename `FindMinNextPodAvailabilityCheckAccordingToLastOwnerStatusEvaluation` as simply `FindMinNextPodAvailabilityCheck`
2. wrap the safeguard ` ptr.To(time.Duration(updatedRS.Spec.MinReadySeconds) * time.Second)` under the function, and make the function return ref (rather than ptr). 

wdyt?

Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go]: 1. Ok makes sense, but also renamed `findMinNextPodAvailabilityCheck` to `findMinNextPodAvailabilitySimpleCheck` since we might export that later as mentioned
2. I would prefer to keep it outside for 2 reasons. Firstly, it guards against a mistake in `FindMinNextPodAvailabilityCheck` and we can see from the replicaset controller that there will always be a value and what the worst case scenario is. Secondly, I would prefer not to hard code it there to allow for difference between controllers.

Regarding 2., we can decide to unify it once we implement this functionality for the other workload controllers.

Comment (mimowo) [reply pkg/controller/replicaset/replica_set.go]: (1.) sgtm, thanks!
(2a.) "... and we can see from the replicaset controller that there will always be a value and what the worst case scenario is. " - we could also see there will always be a value if the function returned reference, rather than ptr, so this particular argument is not convincing me. 
(2b.) "Secondly, I would prefer not to hard code it there to allow for difference between controllers.", yeah I can see that maybe other controllers don't want the fallback, or want a different one, in which case we will need to refactor. OTOH, we will also need to refactor (or would like to), when other controllers want to use the commonized way of doing the fallback.

> Regarding 2., we can decide to unify it once we implement this functionality for the other workload controllers.

I'm fine to defer it for later.

File: pkg/controller/controller_utils.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/controller_utils.go]: nice catch!

File: pkg/controller/controller_utils.go [hunk 13]
```diff
@@ -1030,6 +1031,59 @@ func CountTerminatingPods(pods []*v1.Pod) int32 {
...
+	}
+	return minAvailabilityCheck, checkPod
+}
+
+// FindMinNextPodAvailabilityCheck finds a duration when the next availability check should occur.
+// We should check for the availability at the same time as the status evaluation/update occurs (e.g. .status.availableReplicas) by
+// passing lastOwnerStatusEvaluation. This ensures that we will not skip any pods that might become available
+// (findMinNextPodAvailabilitySimpleCheck would return nil in the future time), since the owner status evaluation.
+// clock is then used to calculate the precise time for the next availability check.
+func FindMinNextPodAvailabilityCheck(pods []*v1.Pod, minReadySeconds int32, lastOwnerStatusEvaluation time.Time, clock clock.PassiveClock) *time.Duration {
```
Comment (mimowo) [inline pkg/controller/controller_utils.go:1073]: Is this function, along with the downsteam fully covered with the unit tests? (ideally check with the go coverage tool)

If not, what are the uncovered branches and can we cover them?

Comment (atiratree) [reply pkg/controller/controller_utils.go:1073]: It is fully covered; I have verified it with go coverage.

Also note that we also run/test this function in

https://github.com/atiratree/kubernetes/blob/3521e52110f4e29383e5b1d38febecb7e28cfde2/pkg/controller/controller_utils_test.go#L1052

File: pkg/controller/replicaset/replica_set.go (hunk 6 above)
Comment (mimowo) [reply pkg/controller/replicaset/replica_set.go:773]: It feels like out of scope for the issue?

File: pkg/api/v1/pod/util.go (hunk 2 above)
Comment (mimowo) [reply pkg/api/v1/pod/util.go]: lgtm

File: pkg/controller/replicaset/replica_set.go (hunk 6 above)
Comment (mimowo) [reply pkg/controller/replicaset/replica_set.go:773]: I know it is a bit of an open question, and I'm likely to be missing something. However, the purpose of this change is not that clear to me in the context of the issue originally posted, so it would help to summarize the following:
- is this change relevant to fix the original issue posted
- what are the scenarios affected and not affected by this change
- does it make sense to submit a separate PR focused on this fix with dedicated tests and description

File: pkg/controller/controller_utils.go [hunk 14]
```diff
@@ -1030,6 +1031,60 @@ func CountTerminatingPods(pods []*v1.Pod) int32 {
...
+	var nextCheck *time.Duration
+	if nextCheckAccordingToOwnerStatusEvaluation, checkPod := findMinNextPodAvailabilitySimpleCheck(pods, minReadySeconds, lastOwnerStatusEvaluation); nextCheckAccordingToOwnerStatusEvaluation != nil {
+		// There must be a nextCheck. We try to calculate a more precise value for the next availability check.
+		// Fall back to 0 (immediate check) in case the following nextPodAvailabilityCheck call (with a refreshed Now) returns nil, as we might be past the check.
+		nextCheck = ptr.To(time.Duration(0))
+		// Check the earliest pod to avoid being preempted by a later pod.
+		if updatedNextCheck := nextPodAvailabilityCheck(checkPod, minReadySeconds, clock.Now()); updatedNextCheck != nil {
+			// There is a delay since the last Now() call (lastOwnerStatusEvaluation). Update the nextCheck.
+			nextCheck = ptr.To(*updatedNextCheck)
```
Comment (soltysh) [inline pkg/controller/controller_utils.go]: Why this "double" pointer construct, rather than just:
```golang
nextCheck = updatedNextCheck
```

File: pkg/controller/controller_utils.go [hunk 15]
```diff
@@ -1030,6 +1031,60 @@ func CountTerminatingPods(pods []*v1.Pod) int32 {
...
+		}
+	}
+	return nextCheck
+}
```
Comment (soltysh) [inline pkg/controller/controller_utils.go:1086]: This whole method would read easier if you modify it to look like so:
```golang
func FindMinNextPodAvailabilityCheck(pods []*v1.Pod, minReadySeconds int32, lastOwnerStatusEvaluation time.Time, clock clock.PassiveClock) *time.Duration {
	nextCheckAccordingToOwnerStatusEvaluation, checkPod := findMinNextPodAvailabilitySimpleCheck(pods, minReadySeconds, lastOwnerStatusEvaluation)
	if nextCheckAccordingToOwnerStatusEvaluation == nil || checkPod == nil {
		return nil
	}
	// Check the earliest pod to avoid being preempted by a later pod.
	if updatedNextCheck := nextPodAvailabilityCheck(checkPod, minReadySeconds, clock.Now()); updatedNextCheck != nil {
		// There is a delay since the last Now() call (lastOwnerStatusEvaluation). Update the nextCheck.
		return updatedNextCheck
	}
	// There must be a nextCheck. We try to calculate a more precise value for the next availability check.
	// Fall back to 0 (immediate check) in case the following nextPodAvailabilityCheck call (with a refreshed Now) returns nil, as we might be past the check.
	return ptr.To(time.Duration(0))
}
```
I believe @kow3ns made similar comment elsewhere in this PR.

File: pkg/controller/replicaset/replica_set_test.go [hunk 16]
```diff
@@ -1618,6 +1618,85 @@ func TestDoNotAdoptOrCreateIfBeingDeletedRace(t *testing.T) {
...
+		t.Errorf("Expected updated ReplicaSet to contain available replicas %v, got %v instead",
+			0, updatedRs.Status.AvailableReplicas)
+	}
+
+	if got, want := manager.queue.Len(), 0; got != want {
+		t.Errorf("queue.Len() = %v, want %v", got, want)
+	}
+
+	// RS should be re-queued after 700ms to recompute .status.availableReplicas (200ms extra for the test).
+	time.Sleep(900 * time.Millisecond)
```
Comment (soltysh) [inline pkg/controller/replicaset/replica_set_test.go]: `time.Sleep` is something I'd be careful to use, it'd be better to use one of the `Eventually` we have, I've asked in [#sig-testing](https://kubernetes.slack.com/archives/C09QZ4DQB/p1753273834664499) which one is the preferred one. For now you can go with something like:
```golang
require.Eventually(t, func() bool {
	return manager.queue.Len() == 1
}, 2*time.Second, 10*time.Millisecond, "queue.Len != 1")
```

**Review by soltysh — COMMENTED** [review]
A few minor comments.

File: pkg/controller/controller_utils.go (hunk 14 above)
Comment (atiratree) [reply pkg/controller/controller_utils.go]: ah... Nice find!

File: pkg/controller/controller_utils.go (hunk 15 above)
Comment (atiratree) [reply pkg/controller/controller_utils.go:1086]: Makes sense, it is more readable without nesting.

File: pkg/controller/replicaset/replica_set_test.go (hunk 16 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set_test.go]: I knew we are using these, but instinctively jumped to time.Sleep. Thanks for bringing this up.

**Review by soltysh — APPROVED** [review]
/lgtm

File: pkg/controller/replicaset/replica_set.go (hunk 6 above)
Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go:773]: Sorry, I missed this thread somehow.

> is this change relevant to fix the original issue posted

Yes it is. Especially when there is a skew between each pod readiness.

> what are the scenarios affected and not affected by this change

We basically schedule availability checks even during the rollout and do not wait for all replicas to be ready before scheduling the check. The effect is faster and reliable updates for availableReplicas field and the Deployment conditions.

> does it make sense to submit a separate PR focused on this fix with dedicated tests and description

No, the fix depends on this.

Comment (atiratree) [reply pkg/controller/replicaset/replica_set.go:773]: cc @mimowo
