### PR TITLE
Errors from cgroup destroy are swallowed. Log error at warning level.

### LINKED ISSUE #84595: Errors returned from pod_container_manager_linux Destroy to remove a pods cgroup are swallowed
**What happened**:

Housekeeping sync loop finds an orphaned pod and tries to clean it up. The kubepod slice, as seen below, is not removed by `cleanupOrphanedPodCgroups -> go pcm.Destroy(val)` with no indication as to why. This leads to the docker scope timing out and entering a failed state. The returned error(s) from runc are swallowed making debugging difficult.

```
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.531606    1694 kubelet.go:1907] SyncLoop (housekeeping)
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.670054    1694 kubelet_pods.go:1082] Killing unwanted pod "test-cron-three-1571285880-bb"
Oct 16 21:18:26 server atomic-openshift-node: I1016 21:18:26.792307    1694 kubelet_pods.go:1682] Orphaned pod "20f666f1-f095-11e9-916f-0050568379a2" found, removing pod cgroups
Oct 16 21:18:26 server systemd: Stopping libcontainer container 4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.
Oct 16 21:19:57 server systemd: docker-4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.scope stopping timed out. Killing.
Oct 16 21:19:57 server systemd: Stopped libcontainer container 4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.
Oct 16 21:19:57 server systemd: Unit docker-4396d3ff70201d494fa265e1966435288d6806acb99f0d601bf56f8804f79a24.scope entered failed state.
```

**What you expected to happen**:
As per other areas of the sync loop, useful errors are logged at debug level due to the async calls.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- Kubernetes version (use `kubectl version`): master

### PR DESCRIPTION
**Pull request by mrobson**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Housekeeping sync loop finds an orphaned pod and tries to clean it up. The removal of the kubepod slice may fail. This leads to the docker scope timing out and entering a failed state. The returned error(s) from runc are swallowed making debugging difficult.

**Which issue(s) this PR fixes**:
Fixes #84595

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```

### CODE REVIEW

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 1]
```diff
@@ -197,6 +197,7 @@ func (m *podContainerManagerImpl) Destroy(podCgroup CgroupName) error {
 		ResourceParameters: &ResourceConfig{},
 	}
 	if err := m.cgroupManager.Destroy(containerConfig); err != nil {
+		klog.V(3).Infof("failed to delete cgroup paths for %v : %v", podCgroup, err)
```
Comment (tedyu) [inline pkg/kubelet/cm/pod_container_manager_linux.go]: This should be at warning or error level.

Comment (tedyu) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: Actually I have a question, in the current code, the err is wrapped and returned.
Why is the new error not logged ?

Comment (tedyu) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: I would lean toward logging this as a warning.

Comment (mrobson) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: @tedyu ok, sounds good. changed it to a warning.

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 2]
```diff
@@ -197,6 +197,7 @@ func (m *podContainerManagerImpl) Destroy(podCgroup CgroupName) error {
 		ResourceParameters: &ResourceConfig{},
 	}
 	if err := m.cgroupManager.Destroy(containerConfig); err != nil {
+		klog.Warningf("failed to delete cgroup paths for %v : %v", podCgroup, err)
```
Comment (mattjmcnaughton) [inline pkg/kubelet/cm/pod_container_manager_linux.go]: @tedyu I don't feel super strongly, but one advantage of logging this using `klog.V(3).Infof` would be that it is consistent with the logging statement on line 190. I don't have a ton of context on this part of the code base, but I do get the sense they are describing equally bad failure states... in other words, it seems sensible to me that they'd have the same log level.

Alternatively, I suppose we could change both to be a `Warning`.

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Thanks for your work here!

File: pkg/kubelet/cm/pod_container_manager_linux.go (hunk 2 above)
Comment (mrobson) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: @mattjmcnaughton that was my initial rational around consistency. I believe this error and a number of others logged at debug are generally ok to ignore as they should be self-resolving through subsequent sync loops. You would probable only want to see them when you find a definitive problem case (like what I am trying to root cause).

Comment (mattjmcnaughton) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: Gotcha! So just to be sure we're on the same page, are you planning on changing it to `klog.V(3).Infof`? Or is there a reason more important than consistency for it to be `klog.Warningf`?

Comment (mrobson) [reply pkg/kubelet/cm/pod_container_manager_linux.go]: @mattjmcnaughton In the original PR I had it at v3 info and per the discussion with @tedyu I changed it to warn. I am on the side of having it an v3 info and am happy to change it back it everyone is happy with that per my explanation.

**Comment by mattjmcnaughton** [comment]
Ok :) Let's make both warnings then - my only concern here is consistency :)

**Comment by mrobson** [comment]
@mattjmcnaughton @tedyu updates pushed with warnings for both. PTAL thanks!

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

@mrobson thank you for your patience during the discussion :)
@tedyu thank you for your insights, as always :)

**Comment by mrobson** [comment]
@vishh PTAL for approval

**Comment by mrobson** [comment]
@mattjmcnaughton seems like vish is inactive.. any thoughts on a different approver?

**Comment by mattjmcnaughton** [comment]
/assign @ConnorDoyle 

@mrobson I added a new reviewer - in the future, see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/OWNERS for a list of reviewers for the specific package :)

**Comment by mrobson** [comment]
@ConnorDoyle PTAL for approval - change is small :) thanks

**Comment by derekwaynecarr** [comment]
/approve

just noted for future: we call `go pcm.Destroy()` so the returned error is never logged.
