### PR TITLE
test: Start a pod with nc instead of execing a background command

### LINKED ISSUE #92057: HostPathType Socket e2e tests hang on containerd
**What happened**:
Once we switched over the default runtime to containerd, the slow ci and pull jobs started timing out. The tests, which used to take 13 minutes, jumped to 30 minutes. https://github.com/kubernetes/kubernetes/issues/92045

This increase in test time is only observed in the slow job, so I suspect the slow job is exercising some functionality that may not be exercised as frequently in the other jobs.

**What you expected to happen**:
No performance regression

**How to reproduce it (as minimally and precisely as possible)**:
Run the tests in the slow job with containerd

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mpatel@redhat.com>

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
The behavior for exec'ing a backgrounded command is not specified
with CRI, so modify the test to run the command directly instead
of using exec.

**Which issue(s) this PR fixes**:

Fixes #92057 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by mrunalp** [comment]
@BenTheElder @dims ptal

File: test/e2e/storage/host_path_type.go [hunk 1]
```diff
@@ -193,12 +193,9 @@ var _ = utils.SIGDescribe("HostPathType Socket [Slow]", func() {
 		ginkgo.By("Create a pod for further testing")
 		hostBaseDir = path.Join("/tmp", ns)
 		mountBaseDir = "/mnt/test"
-		basePod = f.PodClient().CreateSync(newHostPathTypeTestPod(map[string]string{}, hostBaseDir, mountBaseDir, &hostPathDirectoryOrCreate))
+		basePod = f.PodClient().CreateSync(newHostPathTypeTestPodWithCommand(map[string]string{}, hostBaseDir, mountBaseDir, &hostPathDirectoryOrCreate, fmt.Sprintf("nc -lU %s", path.Join(mountBaseDir, "asocket"))))
```
Comment (tedyu) [inline test/e2e/storage/host_path_type.go:196]: Please add a comment explaining the reason for switching to calling nc.
It would be good to leave a TODO here once the timeout discussed in #92057 is implemented.

**Comment by mrunalp** [comment]
@jsafrane ptal

File: test/e2e/storage/host_path_type.go (hunk 1 above)
Comment (mrunalp) [reply test/e2e/storage/host_path_type.go:196]: After looking at the tests in more detail, I think this is a better solution. We can have separate tests for exec with detach when we add that feature.

Comment (mikebrow) [reply test/e2e/storage/host_path_type.go:196]: @tedyu the test was calling `nc` before see the removal of lines 199-201.

once official timeout support is added we could add a test to test the timeout.

+1 to @mrunalp's suggestion for separate tests for exec with detach.

**Review by mikebrow — APPROVED** [review]
LGTM

File: test/e2e/storage/host_path_type.go (hunk 1 above)
Comment (dims) [reply test/e2e/storage/host_path_type.go:196]: this is sig-storage test. let's please have whatever new tests needed in node e2e tests and not here.
