### PR TITLE
Fix #73479 AWS NLB target groups missing tags

### LINKED ISSUE #73479: AWS NLB created without k8s tags on target groups
**What happened**:

We created a LoadBalancer service with type 'nlb' with two listeners forwarding traffic on two different ports. The service was created correctly along with the target groups and was functionning correctly.

Around 20 hours later, no traffic was flowing from clients to any k8s nodes. While troubleshooting we discovered that the k8s node instance security group was lacking the input rules allowing traffic to the node ports for this LB.

We deleted the service and recreated it. The service started working normally again, but we found out that the two target groups were missing their k8s tags. 

The logs contain the following error:
~~~
E0129 14:47:01.381032       1 service_controller.go:219] error processing service scalable/pr-testing (will retry): failed to ensure load balancer for service scalable/pr-testing: Error adding tags after modifying load balancer targets: "ValidationError: Only one resource can be tagged at a time\n\tstatus code: 400, request id: bc7a47eb-23d4-11e9-9920-b76ff2fbca55"
I0129 14:47:01.381136       1 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"scalable", Name:"pr-testing", UID:"b84f1aaf-23d4-11e9-8b3c-0a73252851de", APIVersion:"v1", ResourceVersion:"120452349", FieldPath:""}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): failed to ensure load balancer for service scalable/pr-testing: Error adding tags after modifying load balancer targets: "ValidationError: Only one resource can be tagged at a time\n\tstatus code: 400, request id: bc7a47eb-23d4-11e9-9920-b76ff2fbca55"
~~~

**What you expected to happen**:

We expected the NLB target groups to have k8s tags, so that k8s could remember it created them.

**How to reproduce it (as minimally and precisely as possible)**:

Create a k8s service with NLB:
~~~yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "300"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: pr-testing
  name: pr-testing
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: non-ssl
    port: 2345
    protocol: TCP
    targetPort: 2345
  - name: ssl
    port: 2445
    protocol: TCP
    targetPort: 2445
  selector:
    app: pr-testing
  sessionAffinity: None
  type: LoadBalancer
~~~

Add a simple deployment that is matched by this service.

**Anything else we need to know?**:

Looking at AWS cloudtrail we could see the following error event:
~~~json
{
    "eventVersion": "1.05",
    "userIdentity": {
       // elided for security reasons
    },
    "eventTime": "2019-01-29T14:47:01Z",
    "eventSource": "elasticloadbalancing.amazonaws.com",
    "eventName": "AddTags",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "34.201.38.207",
    "userAgent": "aws-sdk-go/1.12.7 (go1.9.3; linux; amd64)",
    "errorCode": "ValidationException",
    "errorMessage": "Only one resource can be tagged at a time",
    "requestParameters": {
        "tags": [
            {
                "value": "kubernetes",
                "key": "KubernetesCluster"
            },
            {
                "value": "owned",
                "key": "kubernetes.io/cluster/kubernetes"
            },
            {
                "value": "scalable/pr-testing",
                "key": "kubernetes.io/service-name"
            }
        ],
        "resourceArns": [
            "arn:aws:elasticloadbalancing:us-east-1:158809441554:targetgroup/k8s-tg-67535809ebce3-2345-30034/8051fd2606c91a15",
            "arn:aws:elasticloadbalancing:us-east-1:158809441554:targetgroup/k8s-tg-67535809ebce3-2445-31527/f32c335558de58e7"
        ]
    },
    "responseElements": null,
    "requestID": "bc7a47eb-23d4-11e9-9920-b76ff2fbca55",
    "eventID": "ec99d2d9-c6be-419c-93e1-eeb7dc81a13a",
    "eventType": "AwsApiCall",
    "apiVersion": "2015-12-01",
    "recipientAccountId": "158809441554"
}
~~~

So the `AddTags` API request was called with two Resource ARNs, which is confirmed by the code:
https://github.com/kubernetes/kubernetes/blob/30ed3b41b7b080cf37639371726a445032d5ef29/pkg/cloudprovider/providers/aws/aws_loadbalancer.go#L309-L312

Since we have two target groups, there are two resources to tag.
Except that the AWS API while allowing to send more than one resource ARNs doesn't allow it returning a validation error.

This could be solved by doing one `AddTags` per target groups.

Note that this can't happen on a Classic LB because there's no target groups.

I believe that those missing tags on the target groups are the root cause of the deletion of the security group rules allowing traffic to reach the nodeports, with this (hypothetical and unproved) scenario:

1. k8s creates the target groups, the NLB, the listeners, the sg input rules
2. k8s fails to tag the target groups, but doesn't rollback anything
3. in a subsequent convergence loops, k8s notices that there are two k8s-managed Security Group input rules, but those don't match any Target Groups or match Target Groups that are not managed by k8s (because they don't have the owner tags)
4. k8s deletes those rules

Unfortunately we don't see the rule deletion in the controller manager logs, but it appears in Cloudtrail:
~~~json
{
    "eventVersion": "1.05",
    "userIdentity": {
       // elided for security reasons
    },
    "eventTime": "2019-01-29T10:18:48Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "RevokeSecurityGroupIngress",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "34.201.38.207",
    "userAgent": "aws-sdk-go/1.12.7 (go1.9.3; linux; amd64)",
    "requestParameters": {
        "groupId": "sg-b6c7efcc",
        "ipPermissions": {
            "items": [
                {
                    "ipProtocol": "tcp",
                    "fromPort": 32443,
                    "toPort": 32443,
                    "groups": {},
                    "ipRanges": {
                        "items": [
                            {
                                "cidrIp": "10.16.0.0/16",
                                "description": "kubernetes.io/rule/nlb/health=a9acb96a5230711e98bec125cb496f33"
                            }
                        ]
                    },
                    "ipv6Ranges": {},
                    "prefixListIds": {}
                },
                {
                    "ipProtocol": "tcp",
                    "fromPort": 30346,
                    "toPort": 30346,
                    "groups": {},
                    "ipRanges": {
                        "items": [
                            {
                                "cidrIp": "10.16.0.0/16",
                                "description": "kubernetes.io/rule/nlb/health=a9acb96a5230711e98bec125cb496f33"
                            }
                        ]
                    },
                    "ipv6Ranges": {},
                    "prefixListIds": {}
                }
            ]
        }
    },
    "responseElements": {
        "requestId": "3ed62fec-3e79-4be5-a302-33b139afa49d",
        "_return": true
    },
    "requestID": "3ed62fec-3e79-4be5-a302-33b139afa49d",
    "eventID": "e5c573fa-e68d-4e7f-897f-560ec9ee1008",
    "eventType": "AwsApiCall",
    "recipientAccountId": "158809441554"
}
~~~

Let me know if you have any questions,

**Environment**:
- Kubernetes version: 1.10.7
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS 1967.3.0
- Kernel (e.g. `uname -a`): Linux 4.14.88-coreos
- Install tools: home grown
- Others:

### PR DESCRIPTION
**Pull request by masterzen**
**What type of PR is this?**

/kind bug
/sig aws

**What this PR does / why we need it**:

`elbv2.AddTags` doesn't seem to support assigning the same set of tags to multiple resources at once leading to the following error:
>  Error adding tags after modifying load balancer targets:
>  "ValidationError: Only one resource can be tagged at a time"

This can happen when using AWS NLB with multiple listeners pointing to different node ports.

When k8s creates a NLB it creates a target group per listener along with installing security group ingress rules allowing the traffic to reach the k8s nodes.

Unfortunately if those target groups are not tagged, k8s thinks the security group ingress rules are orphaned and removes them, making it impossible for external trafic to reach the cluster
nodes.

This small change assigns tags one target group at a time instead of batching them as before.

**Which issue(s) this PR fixes**:

Fixes #73479 

**Special notes for your reviewer**:

It seems that this part of the code is not covered by unit tests. I thus haven't tried to add tests of this change. If it is required to do so, please let me know and I'll amend the PR.

**Does this PR introduce a user-facing change?**:

I'm not quite sure this can qualify as a 'user-facing change' as it restores the intended behavior, but anyway here are some release notes

```release-note
Prevent AWS Network Load Balancer security groups ingress rules to be deleted by ensuring target groups are tagged.
```

### CODE REVIEW

**Comment by masterzen** [comment]
I've fixed my CNCF CLA entry to use a more correct e-mail address, this should now validate.

**Comment by masterzen** [comment]
I've fixed my CNCF CLA entry to use a more correct e-mail address, this should now validate.

/check-cla

**Comment by masterzen** [comment]
/check-cla please, it should be good now.

File: pkg/cloudprovider/providers/aws/aws_loadbalancer.go [hunk 1]
```diff
@@ -166,9 +166,14 @@ func (c *Cloud) ensureLoadBalancerv2(namespacedName types.NamespacedName, loadBa
 			})
 		}
 		if len(addTagsInput.ResourceArns) > 0 && len(addTagsInput.Tags) > 0 {
-			_, err = c.elbv2.AddTags(addTagsInput)
-			if err != nil {
-				return nil, fmt.Errorf("Error adding tags after creating Load Balancer: %q", err)
+			// elbv2.AddTags doesn't allow to tag multiple resources at once
```
Comment (M00nF1sh) [inline pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: I suggest replace the addTagsInput declaration with ResourceArns []*string, and []*elbv2.Tag{} directly, just to avoid the confusion to future ppl.

Comment (masterzen) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: Hi @M00nF1sh,

I'm not sure I understand what you mean.
Do you mean to use separate tags and arns variables prior to this code, and then build the `addTagsInput` only just before calling `AddTags` ?

Comment (masterzen) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: @M00nF1sh ,

I've pushed a new version that I think implements what you wanted.
Let me know if there's anything that needs to be changed :)

Thanks!

Comment (M00nF1sh) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: Yes, that is exactly what i want 🤣 .

would you mind do a  slightly optimization to avoid memory realloc like below:
resourceArns := make([]*string, 0, len(mappings))
targetGroupTags := make([]*elbv2.Tag, 0, len(tags))

Comment (masterzen) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: My first implementation was like that :) then I thought it wasn't probably in a performance sensible code, so I wen't to the traditional way of declaring empty slices.
I'm going to push a revised version, thanks !

Comment (masterzen) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: I've pushed the modification. Thanks!

**Comment by shyamjvs** [comment]
/retest

@krzyzacy - Any idea why presubmits haven't been triggered for more than 2 hours?

**Comment by krzyzacy** [comment]
@shyamjvs this PR needs
/ok-to-test

**Comment by masterzen** [comment]
I took the liberty to backport this fix to [1.13](https://github.com/kubernetes/kubernetes/pull/73850), [1.12](https://github.com/kubernetes/kubernetes/pull/73851) and [1.11](https://github.com/kubernetes/kubernetes/pull/73852).

Thanks for considering those PR :)

**Comment by micahhausler** [comment]
Yes please do! I'll LGTM them
