### PR TITLE
Fix flaky test depending on EndpointSlices to be ready

### LINKED ISSUE #119787: Flaky test: Kubernetes e2e suite: [It] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should reject everything except leases
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119754/pull-kubernetes-e2e-kind-ipv6/1688119121729818624

### Which tests are flaking?

Kubernetes e2e suite: [It] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should reject everything except leases 

### Since when has it been flaking?

The job was run on Aug 5th. I had a PR #119754 fixing typos in comments of kubelet source code. It is not related to api-machinery ipv6 but the test failed. The re-test passed.  

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

It seems the test is recently added.

### Relevant SIG(s)

/sig api-machinery
/sig testing

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind flake

Fixes #119787

```release-note
NONE
```

 fix the fixture that waits for the number of endpoints associated to a Service, `WaitForServiceEndpointsNum` , since EndpointSlices and Endpoints are not in sync, and the former are the ones used by kube-proxy and more modern components,  the fixture should verify both objects to avoid races

### CODE REVIEW

File: test/e2e/apimachinery/webhook.go [hunk 1]
```diff
@@ -2718,7 +2718,8 @@ func waitWebhookConfigurationReady(ctx context.Context, f *framework.Framework,
 			if strings.Contains(err.Error(), "denied") {
 				return true, nil
 			}
-			return false, err
+			framework.Logf("Unexpected error waiting for webhook configuration to be ready: %v", err)
+			return false, nil
```
Comment (liggitt) [inline test/e2e/apimachinery/webhook.go:2722]: won't tolerating random errors mask issues with webhooks? our expectation is that webhooks will either intercept and deny, or not intercept and allow

**Comment by liggitt** [comment]
addition of endpointslice logic lgtm, not sure about the masking the general error

File: test/e2e/apimachinery/webhook.go (hunk 1 above)
Comment (jpbetz) [reply test/e2e/apimachinery/webhook.go:2722]: Oh, good point. I had suggested we keep the wait going for unexpected errors because it would have prevented this from flaking..  Maybe just drop this from the PR since the below should ensure that the webhook is started and reachable?

**Comment by aojea** [comment]
> [FAILED] could not find group version resource for dynamic client and wardle/flunders (discovery error: <nil>, discovery results: map[schema.GroupVersionResource]struct {}{schema.GroupVersionResource{Group:"", Version:"v1", Resource:"bindings"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"configmaps"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"endpoints"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"limitranges"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"persistentvolumeclaims"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"pods"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"podtemplates"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"replicationcontrollers"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"resourcequotas"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"secrets"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"serviceaccounts"}:struct {}{}, schema.GroupVersionResource{Group:"", Version:"v1", Resource:"services"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"controllerrevisions"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"daemonsets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"deployments"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"replicasets"}:struct {}{}, schema.GroupVersionResource{Group:"apps", Version:"v1", Resource:"statefulsets"}:struct {}{}, schema.GroupVersionResource{Group:"authorization.k8s.io", Version:"v1", Resource:"localsubjectaccessreviews"}:struct {}{}, schema.GroupVersionResource{Group:"autoscaling", Version:"v2", Resource:"horizontalpodautoscalers"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"cronjobs"}:struct {}{}, schema.GroupVersionResource{Group:"batch", Version:"v1", Resource:"jobs"}:struct {}{}, schema.GroupVersionResource{Group:"coordination.k8s.io", Version:"v1", Resource:"leases"}:struct {}{}, schema.GroupVersionResource{Group:"crd-publish-openapi-test-foo.example.com", Version:"v1", Resource:"e2e-test-crd-publish-openapi-9175-crds"}:struct {}{}, schema.GroupVersionResource{Group:"discovery.k8s.io", Version:"v1", Resource:"endpointslices"}:struct {}{}, schema.GroupVersionResource{Group:"events.k8s.io", Version:"v1", Resource:"events"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"ingresses"}:struct {}{}, schema.GroupVersionResource{Group:"networking.k8s.io", Version:"v1", Resource:"networkpolicies"}:struct {}{}, schema.GroupVersionResource{Group:"policy", Version:"v1", Resource:"poddisruptionbudgets"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"rolebindings"}:struct {}{}, schema.GroupVersionResource{Group:"rbac.authorization.k8s.io", Version:"v1", Resource:"roles"}:struct {}{}, schema.GroupVersionResource{Group:"storage.k8s.io", Version:"v1", Resource:"csistoragecapacities"}:struct {}{}, schema.GroupVersionResource{Group:"wardle.example.com", Version:"v1beta1", Resource:"flunders"}:struct {}{}})

/test pull-kubernetes-e2e-kind-ipv6

File: test/e2e/apimachinery/webhook.go (hunk 1 above)
Comment (aojea) [reply test/e2e/apimachinery/webhook.go:2722]: let me drop the first commit then

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by liggitt** [comment]
just saw this test fail again in https://github.com/kubernetes/kubernetes/pull/119798: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119835/pull-kubernetes-e2e-kind/1688980783198375936
