### PR TITLE
CAP_NET_RAW should be NET_RAW

### LINKED ISSUE #95612: Capability set incorrectly. CAP_NET_RAW should be NET_RAW.
**Which jobs are failing**:
ci-cri-containerd-node-e2e

**Which test(s) are failing**:
Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api

**Since when has it been failing**:
2020 10-12 09:04 PDT
Since https://github.com/kubernetes/kubernetes/pull/95321

**Testgrid link**:
https://testgrid.k8s.io/sig-node-containerd#node-e2e

**Reason for failure**:
Capability set incorrectly. CAP_NET_RAW should be NET_RAW.

I1013 18:39:19.058] Oct 13 18:10:51.403: INFO: At 2020-10-13 18:09:34 +0000 UTC - event for stats-busybox-0: {kubelet tmp-node-e2e-033aeade-cos-81-12871-1210-0} Failed: Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_CAP_NET_RAW": unknown 

**Anything else we need to know**:
I have no idea where this is documented. It's a best guess.

### PR DESCRIPTION
**Pull request by MHBauer**
Format of Capability adds CAP_ prefix automatically.
Add commentary as test progress output.
Clear up some existing comments.

**What type of PR is this?**
/kind bug
/kind failing-test

**What this PR does / why we need it**:
Test currently fails 100% of the time with  `Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_CAP_NET_RAW": unknown`

**Which issue(s) this PR fixes**:
Fixes #95612

**Special notes for your reviewer**:
I have no idea where this behavior is documented, I'm reversing my understanding of the test output.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MHBauer** [comment]
Creator of code segment
/cc @harche

**Comment by MHBauer** [comment]
Triage link https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=when%20querying%20%2Fstats%2Fsummary#fd0d2dc5e869a43662b9

**Comment by harche** [comment]
It had worked fine on CRIO, but I can test it again on Monday.

**Comment by harche** [comment]
https://github.com/opencontainers/runtime-spec/blob/master/config.md#linux-process doesn't talk about specifying capabilities without CAP_, not sure why containerd is adding CAP_ then.

**Comment by MHBauer** [comment]
Alright, so, the documentation for kube seems to inherit the behavior of docker.

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#capabilities
`The following fields take a list of capabilities, specified as the capability name in ALL_CAPS without the CAP_ prefix.`

Right above this link
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-seccomp-profile-for-a-container
`Note: Linux capability constants have the form CAP_XXX. But when you list capabilities in your Container manifest, you must omit the CAP_ portion of the constant. For example, to add CAP_SYS_TIME, include SYS_TIME in your list of capabilities.`

Docker, where the first support comes from
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

File: test/e2e_node/summary_test.go [hunk 1]
```diff
@@ -356,7 +357,7 @@ func getSummaryTestPods(f *framework.Framework, numRestarts int32, names ...stri
 						Image: busyboxImage,
 						SecurityContext: &v1.SecurityContext{
 							Capabilities: &v1.Capabilities{
-								Add: []v1.Capability{"CAP_NET_RAW"},
+								Add: []v1.Capability{"NET_RAW"},
```
Comment (MHBauer) [inline test/e2e_node/summary_test.go:360]: This is the main change.

**Comment by MHBauer** [comment]
/cc @dims
maybe interested?

**Comment by mrunalp** [comment]
@MHBauer This looks good to me (CRI-O maintainer).

**Comment by MHBauer** [comment]
As part of a NodeConformance test, I'm concerned about the original change assuming our defaults are lacking CAP_NET_DEFAULT.

Reading deeper into the link:
DefaultAddCapabilities - The capabilities which are added to containers by default, in addition to the runtime defaults. See the Docker documentation for the default list of capabilities when using the Docker runtime.
https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
 By default, Docker has a default list of capabilities that are kept. The following table lists the Linux capability options which are allowed by default and can be dropped.
In that table is : NET_RAW | Use RAW and PACKET sockets.

**I think we need to roll back https://github.com/kubernetes/kubernetes/pull/95321**

**Comment by MHBauer** [comment]
Tho I suppose ` when using the Docker runtime.` is the main caveat here.

🤷

**Comment by mikebrow** [comment]
Should CRI runtimes be tolerant of linux naming for caps... vs forcing docker naming for caps? If we are tolerant and don't break on cap_ naming those specs with cap_ may break on older integrations.

On the change adding cap_net_raw to the containers for busybox for these test cases.. Do we have a defaults issue? Would it be better/possible to have some part of the test bucket script set the cap defaults in "/etc/crio/crio.conf?" We can also modify the defaults in containerd if need be. 

A more secure default security context might be warranted here. Additionally we need some more docs to reconcile the corner cases where the defaults diverge, and maybe more test cases?

**Comment by dims** [comment]
@MHBauer i am ok as long as both containerd and crio folks sign off :)

**Comment by harche** [comment]
@MHBauer @mrunalp I just tested with `CAP_NET_RAW` and `NET_RAW`, and both work fine on CRIO. So I think this PR is good to go.

**Comment by MHBauer** [comment]
Reversing my feelings on this, there may be a bunch of tests where we're assuming docker permissions, and it would be good to have them all explicitly set as requirements for the test to run.

**Comment by mikebrow** [comment]
> Reversing my feelings on this, there may be a bunch of tests where we're assuming docker permissions, and it would be good to have them all explicitly set as requirements for the test to run.

^ depends what you are testing the defaults, or that you can run tests in spite of default deltas...

Suggestion: 1) a container runs with all necessary caps explicitly set 2) container runs as it did in prior releases using defaults (e.g. on docker shim when migrating to CRI runtimes) 3) container fails to run as it failed in prior releases without additional caps set due to docker default 4) if we are going to change the k8s expected defaults, or accept different defaults for particular runtimes, document and test the differences

**Comment by MHBauer** [comment]
I'll make some long term issues to follow up on setting Capabilities in tests and updating the documentation beyond "when using docker, we use docker defaults." Seems implied that "when using a specific runtime we use the specific runtime defaults". Other things is obviously that the defaults can be configured for each runtime on each node, so consistency is probably needed on a cluster basis. It makes me wonder if there is already some explicit setting of Capabilities in kubelet and whether that can be configured to ensure that Capabilities are set consistently over a cluster without needing to explicitly set them on each node. 

Calling some other containerd people from https://github.com/containerd/project/blob/master/MAINTAINERS
/cc @AkihiroSuda @crosbymichael @estesp @dchen1107

**Comment by mikebrow** [comment]
@dims still broke here.. should be an easy merge to bring us back on-line

**Comment by dims** [comment]
/assign @sjenning @mrunalp

Seth, Mrunal,
One line change essentially. Can you please approve?

**Comment by harche** [comment]
Please let this `pull-kubernetes-node-crio-e2e` pass, just to make sure we aren't breaking anything on CRIO.

**Comment by harche** [comment]
`pull-kubernetes-node-crio-e2e` recently started passing on PRs, https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-crio-e2e?buildId=

But  here, it's failing even before starting any tests.

**Comment by harche** [comment]
I just started that test job on this PR, https://github.com/kubernetes/kubernetes/pull/96716, let's see how does that go.

**Comment by harche** [comment]
@MHBauer after checking out your PR locally and rebasing to master, the job is passing fine. 

```bash
make test-e2e-node REMOTE=true RUNTIME=remote IMAGE_CONFIG_FILE="/home/harshal/Downloads/image-config-cgrpv1.yaml" INSTANCE_PREFIX="harpatil" CLEANUP=false CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock" FOCUS="\[NodeConformance\]|\[NodeFeature:.+\]" SKIP="\[Flaky\]|\[Slow\]|\[Serial\]" TEST_ARGS='--kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --non-masquerade-cidr=0.0.0.0/0" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"'
```
</snip>

```bash
Ran 196 of 336 Specs in 727.346 seconds
SUCCESS! -- 196 Passed | 0 Failed | 0 Pending | 140 Skipped
```

I am guessing rebasing will help it pass here too.

**Comment by harche** [comment]
> I just started that test job on this PR, #96716, let's see how does that go.

It passed there.

**Comment by MHBauer** [comment]
Can I put it into the milestone or do I need a release manager?

/milestone v1.20

**Comment by MHBauer** [comment]
Phew, good.

**Comment by mikebrow** [comment]
need this revert pr on 1.20 as well can we get a cherry pick?
