### PR TITLE
test: fixing + linting gomega usage

### LINKED ISSUE #63: [BUG] automatic fixing not working
**Describe the bug**

I tried ginkgolinter through golangci-lint v1.51.2 on the Kubernetes E2E test suite. When running with `--fix`, it reported an issue, but didn't fix it.

**To Reproduce**
1. check out https://github.com/pohly/kubernetes/tree/lint-gomega
2. patch `test/e2e/storage/testsuites/subpath.go`:

```
patch -p1 <<EOF
diff --git a/test/e2e/storage/testsuites/subpath.go b/test/e2e/storage/testsuites/subpath.go
index c8c2b787d81..e56948ce7d7 100644
--- a/test/e2e/storage/testsuites/subpath.go
+++ b/test/e2e/storage/testsuites/subpath.go
@@ -1007,7 +1007,7 @@ func testSubpathReconstruction(ctx context.Context, f *framework.Framework, host
                mountPointsAfter := storageutils.FindVolumeGlobalMountPoints(ctx, hostExec, podNode)
                s1 := mountPointsAfter.Difference(mountPoints)
                s2 := mountPoints.Difference(mountPointsAfter)
-               gomega.Expect(s1).To(gomega.BeEmpty(), "global mount points leaked: %v", s1)
+               gomega.Expect(len(s1)).To(gomega.Equal(0), "global mount points leaked: %v", s1)
                gomega.Expect(s2).To(gomega.BeEmpty(), "global mount points not found: %v", s2)
        }
 }

EOF
```

3. `hack/verify-golangci-lint.sh ./test/e2e/storage/testsuites`

Once `hack/verify-golangci-lint.sh` has been used once, it is also possible to invoke `golangci-lint` manually:
```
$ _output/local/bin/golangci-lint run -v --fix ./test/e2e/storage/testsuites/
INFO [config_reader] Config search paths: [./ /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage /nvme/gopath/src/k8s.io/kubernetes/test/e2e /nvme/gopath/src/k8s.io/kubernetes/test /nvme/gopath/src/k8s.io/kubernetes /nvme/gopath/src/k8s.io /nvme/gopath/src /nvme/gopath /nvme / /home/pohly] 
INFO [config_reader] Used config file .golangci.yaml 
INFO [lintersdb] Active 6 linters: [ginkgolinter gocritic ineffassign staticcheck stylecheck unused] 
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|types_sizes|exports_file|files|imports|name) took 745.600412ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 10.598521ms 
INFO [linters_context/goanalysis] analyzers took 1m48.224534715s with top 10 stages: buildir: 1m42.856018911s, nilness: 3.116718852s, fact_purity: 828.873639ms, typedness: 527.014267ms, SA5012: 401.171985ms, ginkgolinter: 37.625298ms, directives: 31.602195ms, unused: 24.088056ms, SA4030: 21.908012ms, SA1012: 20.821358ms 
INFO [runner] Processors filtering stat (out/in): skip_files: 1/1, identifier_marker: 1/1, source_code: 1/1, path_prefixer: 1/1, sort_results: 1/1, filename_unadjuster: 1/1, autogenerated_exclude: 1/1, nolint: 1/1, uniq_by_line: 1/1, max_same_issues: 1/1, severity-rules: 1/1, cgo: 1/1, path_prettifier: 1/1, exclude: 1/1, skip_dirs: 1/1, exclude-rules: 1/1, diff: 1/1, max_per_file_from_linter: 1/1, max_from_linter: 1/1, path_shortener: 1/1 
INFO [runner] processing took 2.025624ms with stages: nolint: 1.712211ms, exclude-rules: 94.331µs, source_code: 76.895µs, identifier_marker: 49.305µs, autogenerated_exclude: 42.919µs, path_prettifier: 28.075µs, skip_files: 8.449µs, skip_dirs: 5.781µs, uniq_by_line: 1.739µs, max_from_linter: 1.209µs, cgo: 1.026µs, path_shortener: 945ns, filename_unadjuster: 856ns, max_same_issues: 634ns, exclude: 258ns, max_per_file_from_linter: 241ns, severity-rules: 212ns, path_prefixer: 198ns, diff: 187ns, sort_results: 153ns 
INFO [runner] linters took 13.03452066s with stages: goanalysis_metalinter: 13.032428247s 
INFO fixer took 0s with no stages                 
test/e2e/storage/testsuites/subpath.go:1010:3: ginkgo-linter: wrong length assertion; consider using `gomega.Expect(s1).To(gomega.BeEmpty(), "global mount points leaked: %v", s1)` instead (ginkgolinter)
		gomega.Expect(len(s1)).To(gomega.Equal(0), "global mount points leaked: %v", s1)
		^
INFO File cache stats: 1 entries of total size 37.9KiB 
INFO Memory: 137 samples, avg is 2056.4MB, max is 3978.6MB 
INFO Execution took 13.798730346s   
```

Note that the issue gets reported, which implies that https://github.com/golangci/golangci-lint/blob/7ac42b0dde93912bd521d0e89ebef8c191b1d10b/pkg/result/processors/fixer.go#L41-L73 didn't fix it - it's indeed still present in the file.

**Expected behavior**

It should fix the file.

**Environment:**
 - OS: Linux
 - Version: golangci-lint v1.51.2, ginkgolinter v0.8.1

**Additional context**

After removing the `logcheck` plugin, it is possible to run under dlv:

```patch
diff --git a/.golangci.yaml b/.golangci.yaml
index 29de7f79162..2321cd93af5 100644
--- a/.golangci.yaml
+++ b/.golangci.yaml
@@ -23,18 +23,11 @@ linters:
     - ginkgolinter
     - gocritic
     - ineffassign
-    - logcheck
     - staticcheck
     - stylecheck
     - unused
 
 linters-settings: # please keep this alphabetized
-  custom:
-    logcheck:
-      # Installed there by hack/verify-golangci-lint.sh.
-      path: _output/local/bin/logcheck.so
-      description: structured logging checker
-      original-url: k8s.io/klog/hack/tools
   gocritic:
     enabled-checks:
       - equalFold
```

```console
$ (cd hack/tools && dlv debug --wd /nvme/gopath/src/k8s.io/kubernetes github.com/golangci/golangci-lint/cmd/golangci-lint -- run --fix -v ./test/e2e/storage/testsuites )
(dlv) b fixer.go:41
...
(dlv) c
...
> github.com/golangci/golangci-lint/pkg/result/processors.Fixer.Process() /nvme/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/result/processors/fixer.go:41 (hits goroutine(1):1 total:1) (PC: 0x1af5e32)
    36:	
    37:	func (f Fixer) printStat() {
    38:		f.sw.PrintStages()
    39:	}
    40:	
=>  41:	func (f Fixer) Process(issues []result.Issue) []result.Issue {
    42:		if !f.cfg.Issues.NeedFix {
    43:			return issues
    44:		}
    45:	
    46:		outIssues := make([]result.Issue, 0, len(issues))
...
> github.com/golangci/golangci-lint/pkg/result/processors.Fixer.Process() /nvme/gopath/pkg/mod/github.com/golangci/golangci-lint@v1.51.2/pkg/result/processors/fixer.go:51 (PC: 0x1af6236)
    46:		outIssues := make([]result.Issue, 0, len(issues))
    47:		issuesToFixPerFile := map[string][]result.Issue{}
    48:		for i := range issues {
    49:			issue := &issues[i]
    50:			if issue.Replacement == nil {
=>  51:				outIssues = append(outIssues, *issue)
    52:				continue
    53:			}
    54:	
    55:			issuesToFixPerFile[issue.FilePath()] = append(issuesToFixPerFile[issue.FilePath()], *issue)
    56:		}
(dlv) p issue
*github.com/golangci/golangci-lint/pkg/result.Issue {
	FromLinter: "ginkgolinter",
	Text: "ginkgo-linter: wrong length assertion; consider using `gomega.Expect(s1).To(gomega.BeEmpty(), \"global mount points leaked: %v\", s1)` instead",
	Severity: "",
	SourceLines: []string len: 1, cap: 1, [
		"\t\tgomega.Expect(len(s1)).To(gomega.Equal(0), \"global mount points leaked: %v\", s1)",
	],
	Replacement: *github.com/golangci/golangci-lint/pkg/result.Replacement nil,
	Pkg: *golang.org/x/tools/go/packages.Package {
		ID: "k8s.io/kubernetes/test/e2e/storage/testsuites",
		Name: "testsuites",
		PkgPath: "k8s.io/kubernetes/test/e2e/storage/testsuites",
		Errors: []golang.org/x/tools/go/packages.Error len: 0, cap: 0, nil,
		TypeErrors: []go/types.Error len: 0, cap: 0, nil,
		GoFiles: []string len: 19, cap: 32, [
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/capacity.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/ephemeral.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/fsgroupchangepolicy.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/readwriteoncepod.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable_stress.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/topology.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_io.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_stress.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumelimits.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumeperf.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go",
		],
		CompiledGoFiles: []string len: 19, cap: 32, [
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/capacity.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/disruptive.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/ephemeral.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/fsgroupchangepolicy.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/readwriteoncepod.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable_stress.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/topology.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_io.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_stress.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumelimits.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumeperf.go",
			"/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go",
		],
		OtherFiles: []string len: 0, cap: 0, nil,
		EmbedFiles: []string len: 0, cap: 0, nil,
		EmbedPatterns: []string len: 0, cap: 0, nil,
		IgnoredFiles: []string len: 0, cap: 0, nil,
		ExportFile: "/home/pohly/.cache/go-build/9a/9aad1fdf1f98058a6de1e5d943ed660ef33ecc535d6e68664a073d95f053015b-d",
		Imports: map[string]*golang.org/x/tools/go/packages.Package [...],
		Types: *go/types.Package nil,
		Fset: *(*"go/token.FileSet")(0xc001530280),
		IllTyped: false,
		Syntax: []*go/ast.File len: 0, cap: 0, nil,
		TypesInfo: *go/types.Info nil,
		TypesSizes: go/types.Sizes nil,
		forTest: "",
		depsErrors: []*golang.org/x/tools/internal/packagesinternal.PackageError len: 0, cap: 0, nil,
		Module: *golang.org/x/tools/go/packages.Module nil,},
	LineRange: *github.com/golangci/golangci-lint/pkg/result.Range nil,
	Pos: go/token.Position {
		Filename: "test/e2e/storage/testsuites/subpath.go",
		Offset: 37472,
		Line: 1010,
		Column: 3,},
	HunkPos: 0,
	ExpectNoLint: false,
	ExpectedNoLintLinter: "",}
```

This shows that ginkgolinter didn't provide a replacement, and therefore fixing doesn't work.

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Gomega offers some flexibility regarding how assertions are written. But comparing the length of a slice or string is typically more complicated than checking the object directly. https://github.com/nunnatsa/ginkgolinter finds such issues and suggests better replacements.

It also suggests alternatives for error checking. However, in those cases we want to use `framework.ExpectNoError` because it has some additional logic (https://github.com/kubernetes/community/pull/7021). Enforcing that through linting will be solved via forbidigo once it is ready.

#### Which issue(s) this PR fixes:
Related-to: https://github.com/kubernetes/kubernetes/issues/115234

#### Special notes for your reviewer:

Automatically applying the suggested fix [didn't work through golangci-lint](https://github.com/nunnatsa/ginkgolinter/issues/63), so these fixes were done manually. This would have been required for error checking anyway.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/assign @oomichi 

For review, as you have some experience with gomega.

File: test/e2e/storage/vsphere/vsphere_volume_perf.go [hunk 1]
```diff
@@ -86,7 +86,7 @@ var _ = utils.SIGDescribe("vcp-performance [Feature:vsphere]", func() {
 
 		nodes, err := e2enode.GetReadySchedulableNodes(ctx, client)
 		framework.ExpectNoError(err)
-		gomega.Expect(len(nodes.Items)).To(gomega.BeNumerically(">=", 1), "Requires at least %d nodes (not %d)", 2, len(nodes.Items))
```
Comment (pohly) [inline test/e2e/storage/vsphere/vsphere_volume_perf.go:89]: Note that the explanation does not match the code (off-by-one error). As the code is what actually runs, I kept that logic and updated the explanation accordingly.

File: test/e2e/common/node/sysctl.go [hunk 2]
```diff
@@ -148,7 +148,7 @@ var _ = SIGDescribe("Sysctls [LinuxOnly] [NodeConformance]", func() {
 		client := f.ClientSet.CoreV1().Pods(f.Namespace.Name)
 		_, err := client.Create(ctx, pod, metav1.CreateOptions{})
 
-		gomega.Expect(err).NotTo(gomega.BeNil())
+		framework.ExpectNoError(err)
```
Comment (aojea) [inline test/e2e/common/node/sysctl.go:151]:
```suggestion
		framework.ExpectError(err)
```

Comment (pohly) [reply test/e2e/common/node/sysctl.go:151]: Right, will fix. However, my plan is to get rid of all useless framework gomega wrappers including `ExpectError`, so I'll use `gomega.Expect(err).To(gomega.HaveOccurred())`.

Comment (pohly) [reply test/e2e/common/node/sysctl.go:151]: Even then it's not a good assertion: instead of passing when *some* error occurs, it should be more specific and check that exactly *the* expected error occurs.

Comment (pohly) [reply test/e2e/common/node/sysctl.go:151]: It's okay here, such stricter checking follows.

Comment (pohly) [reply test/e2e/common/node/sysctl.go]: > I'll use gomega.Expect(err).To(gomega.HaveOccurred()).

`hack/verify-test-code.sh` objected against that. I'll switch to it later.

Comment (aojea) [reply test/e2e/common/node/sysctl.go]: I just suggested the contrary of the library, but feel free to choose the one you think is best

**Comment by aojea** [comment]
/lgtm

someone with more gomega experience should check it

File: test/e2e/common/node/sysctl.go (hunk 2 above)
Comment (pohly) [reply test/e2e/common/node/sysctl.go]: I switched again, now to what was suggested in https://github.com/onsi/gomega/issues/642#issuecomment-1440344286... :sweat_smile:

**Comment by pohly** [comment]
> someone with more gomega experience should check it

@nunnatsa: this PR enables your ginkgolinter in Kubernetes and (in preparation for that) fixes several findings. Does this look reasonable to you?

**Comment by nunnatsa** [comment]
> > someone with more gomega experience should check it
> 
> 
> 
> @nunnatsa: this PR enables your ginkgolinter in Kubernetes and (in preparation for that) fixes several findings. Does this look reasonable to you?
> 
> 

Yes
/lgtm

**Comment by pohly** [comment]
/assign @dims

For approval of `.golangci.yaml` and `hack` update. Or should I ask `@thockin` (not pinging him yet)?

**Comment by dims** [comment]
.golangci.yaml and hack updates look good

/approve
/hold for additional eyes as needed.

**Comment by pohly** [comment]
I'll merge on Monday unless I hear otherwise.

**Comment by nunnatsa** [comment]
:partying_face:
