### PR TITLE
Get inodes and disk usage via pure go

### LINKED ISSUE #95172: kubelet does not work with busybox `du` command
**What happened**:
Running `sonobouy` test suite on a cluster with workers on Alpine Linux, which uses busybox instead of GNU coreutils fails. The log shows that it fails to execute the `du` command.
```
E0928 14:39:57.194066    2455 cri_stats_provider.go:591] Unable to fetch container log stats for path /var/log/pods/kube-system_metrics-server-7d4bcb75dd-gvqcf_107aa715-8c80-491c-b679-532578bda180/metrics-server: failed command 'du' ($ nice -n 19 du -x -s -B 1) on path /var/log/pods/kube-system_metrics-server-7d4bcb75dd-gvqcf_107aa715-8c80-491c-b679-532578bda180/metrics-server with error exit status 1
```
**What you expected to happen**:
I expected the `du` call to exit with success.

**How to reproduce it (as minimally and precisely as possible)**:
Install and run kublet on Alpine Linux without installing `coreutils`.

**Anything else we need to know?**:
It failed due to the `-B 1` option which is not implemented in busybox.

The `-B` option is not specified in [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/du.html) so I don't think it is reasonable to expect it to implemented in busybox.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"archive", BuildDate:"2020-09-21T06:09:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-14T11:56:23Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
QEMU/KVM virtual machine
- OS (e.g: `cat /etc/os-release`):
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux aworker0 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 GNU/Linux
```
- Install tools:
custom

- Network plugin and version (if this is a network-related bug):
not network-related

- Others:

### LINKED ISSUE #95186: kubelet does not work with busybox `find` command
**What happened**:
kubelet fails to run pods on Alpine Linux with busybox find.
```
E0928 14:40:27.368735    2455 cri_stats_provider.go:591] Unable to fetch container log stats for path /var/log/pods/kube-system_kube-proxy-5qw5z_38dc981c-397a-4896-b8c5-0e0415f3eb46/kube-proxy: cmd [find /var/log/pods/kube-system_kube-proxy-5qw5z_38dc981c-397a-4896-b8c5-0e0415f3eb46/kube-proxy -xdev -printf .] failed. stderr: find: unrecognized: -printf
```

**What you expected to happen**:
I expected the `find` call to exit with success, not failure.

**How to reproduce it (as minimally and precisely as possible)**:
Install and run kublet on Alpine Linux without installing GNU findutils, so busybox implementation of `find` is used.

**Anything else we need to know?**:
`find` failed because the argument `-printf` is not implemented in busybox `find`.

The `-printf` option is not specified in [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html) so it can not be expected to be supported in all `find` implementations.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"archive", BuildDate:"2020-09-21T06:09:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-14T11:56:23Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  QEMU/KVM virtual machine
- OS (e.g: `cat /etc/os-release`):
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux aworker0 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 GNU/Linux
```
- Install tools:
custom
- Network plugin and version (if this is a network-related bug):
not network-related bug
- Others:
I think it would be better to use `filepath.Walk` instead of `exec.Command("find"...)`

Related to #95172

### LINKED ISSUE #96114: GetMetrics() calculate inodes wrong when there are hardlinks
**What happened**:
`GetMetrics()` in `pkg/volume/metrics_du.go` calculates number of inodes wrong when there are hard links.

**What you expected to happen**:
inodes with hardlinks should only be counted once.

**How to reproduce it (as minimally and precisely as possible)**:
```diff
diff --git a/pkg/volume/metrics_du_test.go b/pkg/volume/metrics_du_test.go
index 3bee08bf1ed..06f32cb4452 100644
--- a/pkg/volume/metrics_du_test.go
+++ b/pkg/volume/metrics_du_test.go
@@ -81,6 +81,21 @@ func TestMetricsDuGetCapacity(t *testing.T) {
        if e, a := (expectedEmptyDirUsage.Value() + getExpectedBlockSize(filepath.Join(tmpDir, "f1"))), actual.Used.Value(); e != a {
                t.Errorf("Unexpected Used for directory with file.  Expected %v, got %d.", e, a)
        }
+
+       // create a hardlink and expect inodes count to stay the same
+       previousInodes := actual.InodesUsed.Value()
+       err = os.Link(filepath.Join(tmpDir, "f1"), filepath.Join(tmpDir, "f2"))
+       if err != nil {
+               t.Errorf("Unexpected error when creating hard link %v", err)
+       }
+       actual, err = metrics.GetMetrics()
+       if err != nil {
+               t.Errorf("Unexpected error when calling GetMetrics %v", err)
+       }
+       if e, a := previousInodes, actual.InodesUsed.Value(); e != a {
+               t.Errorf("Unexpected Used for directory with file.  Expected %v, got %d.", e, a)
+       }
+
 }
 
 // TestMetricsDuRequireInit tests that if MetricsDu is not initialized with a path, GetMetrics
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-beta.0.145+ea32483e865610-dirty", GitCommit:"ea32483e8656109ef4b9ea6fe4ca7b363e96c3b6", GitTreeState:"dirty", BuildDate:"2020-11-02T16:15:46Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.0_alpha20200917
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux ncopa-desktop 5.4.74-0-lts #1-Alpine SMP Mon, 02 Nov 2020 07:40:30 UTC x86_64 GNU/Linux
```

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by ncopa**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Use pure go to calculate the disk usage and inodes metrics of a directory instead of executing external tools `du` and `find`.
It also adds a testcase for calculating inodes correct when there are hard links.

**Which issue(s) this PR fixes**:

Fixes #95172
Fixes #95186
Fixes #96114

**Special notes for your reviewer**:

I am not sure this needs to be mentioned in release notes.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ncopa** [comment]
I have set up a windows machine to fix the `pkg/volume/util/fs/fs_windows_test.go`, but there are multiple logical errors so I cannot understand how this has ever worked? It looks like this has only been built, but never actually run?

**Comment by ncopa** [comment]
I cleaned up various bugs in windows unit test and tested that the unit test actually runs and passes on windows while at it.

**Comment by ncopa** [comment]
The tests passed! :tada:

Would it be an idea to include this in 1.20 release? :pray:

File: pkg/volume/util/fs/fs_windows_test.go [hunk 1]
```diff
@@ -17,65 +17,71 @@ limitations under the License.
...
-		t.Fatalf("TestDiskUsage failed: %s", err.Error())
+		t.Fatalf("Lstat failed for %s: %v", file_1, err)
 	}
-	fileInfo2, err := os.Lstat(file2)
+	fileInfo2, err := os.Lstat(file_2)
 	if err != nil {
-		t.Fatalf("TestDiskUsage failed: %s", err.Error())
+		t.Fatalf("Lstat failed for %s: %v", file_2, err)
 	}
+
```
Comment (jingxu97) [inline pkg/volume/util/fs/fs_windows_test.go:65]: based on the GetDisUsage implementation, isn't total should be equal to the returned usage size of dir1 because dir1 is the top level dir?

Comment (ncopa) [reply pkg/volume/util/fs/fs_windows_test.go:65]: Possibly, but I am not very familiar with how windows disk usage calculation works, and previous test did not test for equal:
```go
    if size.Cmp(used) != 1 {
        t.Fatalf("TestDiskUsage failed: %s", err.Error())
    }
```

I though there might be something I'm not aware of on windows, so I changed it to at least accept if they are equal so the test passes.

But Yeah, I think it should be equal (and it was on my test windows test vm)

**Comment by ncopa** [comment]
FWIW, I have tested that the test actually passes on windows. (seems like nobody ever tested that before):
```
natanael copa@DESKTOP-EKHR4MH C:\Users\Natanael Copa\go\src\github.com\kubernetes>go test ./pkg/volume/util/fs       
ok      k8s.io/kubernetes/pkg/volume/util/fs    0.129s

```

File: pkg/volume/util/fs/fs_windows_test.go (hunk 1 above)
Comment (jingxu97) [reply pkg/volume/util/fs/fs_windows_test.go:65]: size.Cmp(used) != 1 means    size and used are not equal. So the original test is trying to test if size is not equal to used, it will fail.

Comment (ncopa) [reply pkg/volume/util/fs/fs_windows_test.go:65]: According the [documentation](https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity.Cmp) `size.Cmp(used) != 1` means that size is not greater than used.

> Cmp returns 0 if the quantity is equal to y, -1 if the quantity is less than y, or 1 if the quantity is greater than y.

Comment (jingxu97) [reply pkg/volume/util/fs/fs_windows_test.go:65]: oh, my mistake. So here we should test equal size.Cmp(used) == 0?

Comment (ncopa) [reply pkg/volume/util/fs/fs_windows_test.go:65]: If the intention was to test the result to be equal, then `size.Cmp(used) == 0`. I can make the refactored test check for equal if you prefer that. I need to rebase it anyway.

**Comment by ncopa** [comment]
We currently don't run any unit tests on Linux for disk size calculations. Would it make sense to have a common unit test that works for both Linux and windows?

**Comment by ncopa** [comment]
@jingxu97 @saad-ali Is there anything I can do to move this forward?

**Comment by ncopa** [comment]
I rebased and simplified the changes so they are less intrusive. I believe the windows tests are still broken, but that should be handled in separate PR.

Any chance to get this in for 1.21?

File: pkg/volume/testing/testing.go [hunk 2]
```diff
@@ -1229,15 +1229,14 @@ func FindEmptyDirectoryUsageOnTmpfs() (*resource.Quantity, error) {
 		return nil, err
 	}
 	defer os.RemoveAll(tmpDir)
-	out, err := exec.New().Command("nice", "-n", "19", "du", "-x", "-s", "-B", "1", tmpDir).CombinedOutput()
+	out, err := exec.New().Command("nice", "-n", "19", "du", "-x", "-s", "-k", tmpDir).CombinedOutput()
```
Comment (jingxu97) [inline pkg/volume/testing/testing.go:1232]: what this change for?

**Comment by jingxu97** [comment]
> I rebased and simplified the changes so they are less intrusive. I believe the windows tests are still broken, but that should be handled in separate PR.
> 
> Any chance to get this in for 1.21?

very sorry I missed this. 1.21 is frozen. But I think we could cherrypick it if it cannot get in. I will review by today.

File: pkg/volume/util/fs/fs.go [hunk 3]
```diff
@@ -55,63 +59,90 @@ func Info(path string) (int64, int64, int64, int64, int64, int64, error) {
...
-	}
-	// First check whether the quota system knows about this directory
-	// A nil quantity with no error means that the path does not support quotas
-	// and we should use other mechanisms.
-	inodes, err := fsquota.GetInodes(path)
 	if inodes != nil {
-		return inodes.Value(), nil
-	} else if err != nil {
-		return 0, fmt.Errorf("unable to retrieve inode consumption via quota for %s: %v", path, err)
+		usage.Bytes = consumption.Value()
```
Comment (jingxu97) [inline pkg/volume/util/fs/fs.go:83]: should it be if consumption != nil?

File: pkg/volume/metrics_du.go [hunk 4]
```diff
@@ -64,23 +59,14 @@ func (md *metricsDu) GetMetrics() (*Metrics, error) {
...
-	}
-	metrics.Used = used
-	return nil
-}
-
-// runFind executes the "find" command and writes the results to metrics.InodesUsed
-func (md *metricsDu) runFind(metrics *Metrics) error {
-	inodesUsed, err := fs.Find(md.path)
+// getDiskUsage writes metrics.Used and metric.InodesUsed from fs.DiskUsage
+func (md *metricsDu) getDiskUsage(metrics *Metrics) error {
```
Comment (jingxu97) [inline pkg/volume/metrics_du.go:63]: Since no longer use du command, maybe change the file name, function name etc?

File: pkg/volume/testing/testing.go (hunk 2 above)
Comment (ncopa) [reply pkg/volume/testing/testing.go:1232]: Sounds like I need to improve the commit message.

While looking at issue #95172 I grep'ed the code for other calls to `du` and found this place.

It fixes du command to run on Alpine Linux which uses busybox instead of GNU coreutils. (#95172)

The `-B 1` argument is a GNU extension, not defined in POSIX du[1] and does not work with
busybox du used by Alpine Linux. Fix this by using `-k`, which is defined in POSIX[1] and portable and append "Ki" for the ParseQuantity call so du's output is properly parsed.

`resource.ParseQuantity()` will set the format to `BinarySI` when there
is a "Ki" suffix so we can remove the explicit set of the format.

[1]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/du.html

Maybe I should do this in separate PR? I'm not sure where/when `pkg/volume/testing`  is used, but I will definitively fail on Alpine Linux unless you install coreutils. With this change it will be portable to anything POSIX.

Or maybe we should let it call the go implementation instead to get rid of the external `du` dependency?

File: pkg/volume/metrics_du.go (hunk 4 above)
Comment (ncopa) [reply pkg/volume/metrics_du.go:63]: its still "usage of disk for specified directory metrics". I can rename it but then the change becomes more intrusive. Any suggestions of new name?

Comment (jingxu97) [reply pkg/volume/metrics_du.go:63]: I am ok to leave this to future PR.

File: pkg/volume/util/fs/fs.go (hunk 3 above)
Comment (ncopa) [reply pkg/volume/util/fs/fs.go:83]: That is a good question.

Previously the code looked like this:
```go
	// First check whether the quota system knows about this directory
	// A nil quantity with no error means that the path does not support quotas
	// and we should use other mechanisms.
	data, err := fsquota.GetConsumption(path)
	if data != nil {
		return data, nil
	} else if err != nil {
		return nil, fmt.Errorf("unable to retrieve disk consumption via quota for %s: %v", path, err)
	}
```
But what happens if `fsquota.GetConsuption(path)` returns a data value that is non-nil _and_ an error? With the above code, it would gladly return the `data` even if there was an error returned. 

Normally in Go code, if there is an error returned, the other value(s) returned are invalid and must be discarded, but I'm not sure that is the case with `fsquota.GetConsumption` and `fsquota.GetInodes`? are there any valid case where those return a value _and_ an error, where we should ignore the error?

My change looks like this (which is difficult to see by just looking at the git diff):
```go
    // First check whether the quota system knows about this directory
    // A nil quantity with no error means that the path does not support quotas
    // and we should use other mechanisms.
    consumption, err := fsquota.GetConsumption(path)
    if err != nil {
        return usage, fmt.Errorf("unable to retrieve disk consumption via quota for %s: %v", path, err)
    }
    inodes, err := fsquota.GetInodes(path)
    if err != nil {
        return usage, fmt.Errorf("unable to retrieve inode consumption via quota for %s: %v", path, err)
    }

    if inodes != nil {
        usage.Bytes = consumption.Value()
    }

    if consumption != nil {
        usage.Inodes = inodes.Value()
    }

    if inodes != nil && consumption != nil {
        return usage, nil
    }
```

So, if either of `fsquota.GetConsumption` or `fsquota.GetInodes` returns error, we abort everything with that error, assuming that the return value can not be used.

Once we have tested that the return values are valid (eg no errors returned) we check if they are nil or not, and if both are non-nil we can return without walking the path.

However, if we are supposed to ignore any errors from either `fsquota.GetConsumption` or `fsquota.GetInodes` as long as the return value is non-nil, then my code is wrong and needs change.

File: pkg/volume/util/fs/fs.go [hunk 5]
```diff
@@ -55,63 +59,90 @@ func Info(path string) (int64, int64, int64, int64, int64, int64, error) {
...
 	}
-	var counter byteCounter
-	var stderr bytes.Buffer
-	findCmd := exec.Command("find", path, "-xdev", "-printf", ".")
-	findCmd.Stdout, findCmd.Stderr = &counter, &stderr
-	if err := findCmd.Start(); err != nil {
-		return 0, fmt.Errorf("failed to exec cmd %v - %v; stderr: %v", findCmd.Args, err, stderr.String())
+
+	if consumption != nil {
```
[the remark this answers is not in the document]
Comment (ncopa) [reply pkg/volume/util/fs/fs.go:86]: see my response above when  about consumption != nil.

File: pkg/volume/util/fs/fs.go [hunk 6]
```diff
@@ -55,63 +59,90 @@ func Info(path string) (int64, int64, int64, int64, int64, int64, error) {
...
+		if err != nil {
+			return fmt.Errorf("unable to count inodes for %s: %s", path, err)
+		}
+
+		// according to the docs, Sys can be nil
+		if info.Sys() == nil {
+			return fmt.Errorf("fileinfo Sys is nil")
+		}
+
+		s, ok := info.Sys().(*syscall.Stat_t)
```
[the remark this answers is not in the document]
Comment (ncopa) [reply pkg/volume/util/fs/fs.go:117]: I was in doubt if this is ok myself, but I searched the code and found it to be used various other places. looks like those are linux specific though.

But both [darwin arm64](https://github.com/golang/go/blob/master/src/syscall/ztypes_darwin_arm64.go#L66) and [darwin amd64](https://github.com/golang/go/blob/master/src/syscall/ztypes_darwin_amd64.go#L66) has both `Dev` and `NLink` fields so darwin should be fine.

Looks plan9 would need speical handling indeed. Also does not look like there are any `NLink`s for plan9? Do we need to worry about that now?

**Comment by ncopa** [comment]
I want to comment on  using os.Stat, but github thinks im adding a review for some reason and is not letting me respond witha simple comment. ... weird..

We could but then we need the `.Sys().(*syscall.Stat_t)` conversion to get the Stat_t.Dev out from it:

```diff
@@ -91,12 +91,16 @@ func DiskUsage(path string) (UsageInfo, error) {
                return usage, nil
        }
 
-       topLevelStat := &unix.Stat_t{}
-       err = unix.Stat(path, topLevelStat)
+       topLevelInfo, err := os.Stat(path)
        if err != nil {
                return usage, err
        }
 
+       topLevelStat, ok := topLevelInfo.Sys().(*syscall.Stat_t)
+       if !ok {
+               return fmt.Errorf("unsupported fileinfo; could not convert to stat_t")
+       }
+
        // dedupedInode stores inodes that could be duplicates (nlink > 1)
        dedupedInodes := make(map[uint64]struct{})
 
```

I can change it to the above if you prefer, but I found the `unix.Stat` better option, which should work for any POSIX compliant system.

File: pkg/volume/util/fs/fs.go [hunk 7]
```diff
@@ -55,63 +59,90 @@ func Info(path string) (int64, int64, int64, int64, int64, int64, error) {
...
+	if inodes != nil && consumption != nil {
+		return usage, nil
 	}
-	return counter.bytesWritten, nil
-}
 
-// Simple io.Writer implementation that counts how many bytes were written.
-type byteCounter struct{ bytesWritten int64 }
+	topLevelStat := &unix.Stat_t{}
+	err = unix.Stat(path, topLevelStat)
```
[the remark this answers is not in the document]
Comment (ncopa) [reply pkg/volume/util/fs/fs.go:95]: We could but then we need the `.Sys().(*syscall.Stat_t)` conversion to get the Stat_t.Dev out from it:

```diff
@@ -91,12 +91,16 @@ func DiskUsage(path string) (UsageInfo, error) {
                return usage, nil
        }
 
-       topLevelStat := &unix.Stat_t{}
-       err = unix.Stat(path, topLevelStat)
+       topLevelInfo, err := os.Stat(path)
        if err != nil {
                return usage, err
        }
 
+       topLevelStat, ok := topLevelInfo.Sys().(*syscall.Stat_t)
+       if !ok {
+               return fmt.Errorf("unsupported fileinfo; could not convert to stat_t")
+       }
+
        // dedupedInode stores inodes that could be duplicates (nlink > 1)
        dedupedInodes := make(map[uint64]struct{})
 
```

I can change it to the above if you prefer, but I found the `unix.Stat` better option, which should work for any POSIX compliant system.

File: pkg/volume/testing/testing.go (hunk 2 above)
Comment (jingxu97) [reply pkg/volume/testing/testing.go:1232]: I think go implementation is better. You can either change here or make a separate PR.

File: pkg/volume/util/fs/fs.go (hunk 3 above)
Comment (jingxu97) [reply pkg/volume/util/fs/fs.go:83]: >So, if either of fsquota.GetConsumption or fsquota.GetInodes returns error, we abort everything with that error, assuming that the return value can not be used.

In this case, my thought is we should use the filepath.walk approach to get the size instead of returning error directly. I checked quota function, and I don't think there will be case that data!=nil && err!=nil

```go
    // First check whether the quota system knows about this directory
    // A nil quantity with no error means that the path does not support quotas
    // and we should use other mechanisms.
    consumption, err1 := fsquota.GetConsumption(path)
    inodes, err2 := fsquota.GetInodes(path)

    if consumption != nil && inode !=nil {
             usage.Bytes = consumption.Value()
             usaga.Inodes = inode.Value()
            return usage, nil
    }

     ...

    // the following use filepath.Walk to get usage

   ```

Comment (ncopa) [reply pkg/volume/util/fs/fs.go:83]: I think you are right, looks like `fsquota.GetConsumption` returns error in case `xfs_quota` fails to execute, and we dont want return error in that case. I think we simply want fallback to `filepath.walk` on any error.

File: pkg/volume/testing/testing.go (hunk 2 above)
Comment (ncopa) [reply pkg/volume/testing/testing.go:1232]: I had a look at this, but this is only used by the unit tests. I think it makes more sense to call the external `du` to verify that the go implementation in this PR corresponds with what is expected from `du` instead of comparing two identical calls to the same function, so I don't think we should use the go implementation here.

I think my commit is slightly better than what it currently does, but I'm ok to remove it and require GNU coreutils for running the unit tests.

Comment (ncopa) [reply pkg/volume/testing/testing.go]: actually, lets deal with this in separate PR.

File: pkg/volume/util/fs/fs.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (ncopa) [reply pkg/volume/util/fs/fs.go]: > this should inode != nil?

I finally understood what you meant here, and yes, it should, and its fixed now. Thanks!

**Comment by jingxu97** [comment]
cc @ddebroy

**Comment by ddebroy** [comment]
No concerns around the refactoring for Windows. The other changes look good too.

/lgtm
