### PR TITLE
kube-proxy: fix healthz return unexpect code 200

### LINKED ISSUE #105742: kube-proxy health check doesn't fail when kube-proxy can't acquire iptables lock
### What happened?

We upgraded iptables on one of our hosts, and kube-proxy began logging errors about being unable to acquire the `xtables.lock`. However, we didn't notice this, because kube-proxy's health check (`/healthz`) was still passing (and that's generally what we look at as our sign that something is amiss.) As a result, kube-proxy ran for days without being able to update iptables rules, eventually causing an outage for one of our services.

### What did you expect to happen?

We expected that kube-proxy's health check would fail if it was not able to interface with iptables.

### How can we reproduce it (as minimally and precisely as possible)?

Our system was running Debian stretch, running kube-proxy in iptables mode with systemd, with iptables version 1.6.0. Given that starting configuration, the repro case is:

1. Upgrade iptables to 1.6.2.
2. Observe that kube-proxy begins emitting logs saying that it cannot update iptables because another process has the `xtables.lock`.
3. Observe that kube-proxy's health check endpoint (`/healthz`) does not return an error.

### Anything else we need to know?

Example health check output:

<details>

```
$ curl -vvv localhost:10256/healthz
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10256 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:10256
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Tue, 19 Oct 2021 22:21:06 GMT
< Content-Length: 149
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"lastUpdated": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255","currentTime": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255"}
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux myhost 5.4.38 #1~bt9+1 SMP Tue May 12 21:16:19 UTC 2020 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
The hard way
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker version 19.03.8, build afacb8b7f0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.18.4
</details>

### PR DESCRIPTION
**Pull request by cyclinder**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
fix when kube-proxy restore failed, but `/healthz` still return success
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/105742

#### Special notes for your reviewer:
I kept the `lastUpdated`, and I think `/healthz` should also return the time of `lastUpdated` and `currentTime`.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cyclinder** [comment]
/cc @danwinship 
Hi, Could you take a look?

File: pkg/proxy/healthcheck/proxier_health.go [hunk 1]
```diff
@@ -80,12 +80,17 @@ func newProxierHealthServer(listener listener, httpServerFactory httpServerFacto
...
 func (hs *proxierHealthServer) Updated() {
+	hs.oldestPendingQueued.Store(time.Time{})
 	hs.lastUpdated.Store(hs.clock.Now())
 }
 
 // QueuedUpdate updates the lastQueued timestamp.
 func (hs *proxierHealthServer) QueuedUpdate() {
-	hs.lastQueued.Store(hs.clock.Now())
+	if val := hs.oldestPendingQueued.Load(); val != nil {
+		if val.(time.Time).IsZero() {
```
Comment (danwinship) [inline pkg/proxy/healthcheck/proxier_health.go:90]: The docs for `atomic.Value` say "The zero value for a Value returns nil from Load."
So this is wrong

File: pkg/proxy/healthcheck/proxier_health.go [hunk 2]
```diff
@@ -147,14 +148,6 @@ func (h healthzHandler) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
 		resp.WriteHeader(http.StatusServiceUnavailable)
 	} else {
 		resp.WriteHeader(http.StatusOK)
-
-		// In older releases, the returned "lastUpdated" time indicated the last
-		// time the proxier sync loop ran, even if nothing had changed. To
-		// preserve compatibility, we use the same semantics: the returned
-		// lastUpdated value is "recent" if the server is healthy. The kube-proxy
-		// metrics provide more detailed information.
-		lastUpdated = currentTime
```
Comment (danwinship) [inline pkg/proxy/healthcheck/proxier_health.go:156]: This needs to be kept

**Review by danwinship — CHANGES_REQUESTED** [review]

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 3]
```diff
@@ -388,6 +388,8 @@ func TestHealthzServer(t *testing.T) {
 	testHealthzHandler(server, http.StatusOK, t)
 
 	// Should return 200 "OK" after first update
+	hs.QueuedUpdate()
+	fakeClock.Step(1 * time.Second)
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/proxy/healthcheck/healthcheck_test.go:392]: Thanks, Done

File: pkg/proxy/healthcheck/proxier_health.go [hunk 4]
```diff
@@ -80,12 +80,17 @@ func newProxierHealthServer(listener listener, httpServerFactory httpServerFacto
 
 // Updated updates the lastUpdated timestamp.
 func (hs *proxierHealthServer) Updated() {
+	hs.oldestPendingQueued.Store(time.Time{})
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/proxy/healthcheck/proxier_health.go:83]: Done

File: pkg/proxy/healthcheck/proxier_health.go (hunk 1 above)
Comment (cyclinder) [reply pkg/proxy/healthcheck/proxier_health.go:90]: Nope,  I made some tests, If `val.(time.Time).IsZero()` , The return value is non nil from `Load`. See the following:
```golang
// QueuedUpdate updates the lastQueued timestamp.
func (hs *proxierHealthServer) QueuedUpdate() {
	if val := hs.oldestPendingQueued.Load(); val == nil {
		hs.oldestPendingQueued.Store(hs.clock.Now())
	} else {
		fmt.Println("val: ",val.(time.Time))
		if val.(time.Time).IsZero() {
			hs.oldestPendingQueued.Store(hs.clock.Now())
		}
	}
}
```

Result:
```bash
/Users/cyclinder/Downloads/goland/go1.18.1/bin/go tool test2json -t /private/var/folders/nl/k22q6s052q76dfr61mft5stm0000gn/T/GoLand/___TestHealthzServer_in_k8s_io_kubernetes_pkg_proxy_healthcheck.test -test.v -test.paniconexit0 -test.run ^\QTestHealthzServer\E$
=== RUN   TestHealthzServer
val:  0001-01-01 00:00:00 +0000 UTC
--- PASS: TestHealthzServer (0.00s)
PASS

Process finished with the exit code 0
```

File: pkg/proxy/healthcheck/proxier_health.go (hunk 2 above)
Comment (cyclinder) [reply pkg/proxy/healthcheck/proxier_health.go:156]: Do we also kept the `lastUpdated = currentTime` ?  I don't get it 😅,  When `kube-proxy` is healthy，Users will see the time of `lastUpdated` and the time of `currentTime `(`currentTime` > `lastUpdated`), Is it better? 

If `lastUpdated = currentTime`, User may feels a little confused..

Comment (danwinship) [reply pkg/proxy/healthcheck/proxier_health.go:156]: Read the comment. It's a backward-compatibility issue. Some clients may assume that kube-proxy is unhealthy if `lastUpdated` is more than 30 seconds in the past. The data is effectively meaningless at this point, but we don't want to change it.

Comment (cyclinder) [reply pkg/proxy/healthcheck/proxier_health.go:156]: Thanks!

File: pkg/proxy/healthcheck/proxier_health.go [hunk 5]
```diff
@@ -80,12 +81,17 @@ func newProxierHealthServer(listener listener, httpServerFactory httpServerFacto
...
 }
 
 // QueuedUpdate updates the lastQueued timestamp.
 func (hs *proxierHealthServer) QueuedUpdate() {
-	hs.lastQueued.Store(hs.clock.Now())
+	if val := hs.oldestPendingQueued.Load(); val != nil {
+		if val.(time.Time).IsZero() {
+			hs.oldestPendingQueued.Store(hs.clock.Now())
+		}
+	}
```
Comment (danwinship) [inline pkg/proxy/healthcheck/proxier_health.go:94]: oh, sorry, I should have caught this before; this needs to be an atomic operation. Which actually makes it simpler anyway.

```suggestion
	// Set oldestPendingQueued only if it's currently zero
	hs.oldestPendingQueued.CompareAndSwap(zeroTime, hs.clock.Now())
```

**Review by danwinship — COMMENTED** [review]
I missed one thing before but otherwise it looks good

File: pkg/proxy/healthcheck/proxier_health.go (hunk 5 above)
Comment (cyclinder) [reply pkg/proxy/healthcheck/proxier_health.go:94]: Done

**Comment by danwinship** [comment]
/lgtm
/approved
thanks!
