### PR TITLE
Log a better error with useful info on scheduling failures.

### LINKED ISSUE #4583: Scheduler should report why scheduling failed. (aka "why pending?")
Currently we report that we couldn't find a fit for the pod, but we don't determine which predicate failed.  This makes end-user debugging harder than it needs to be.  We should figure out why things don't fit.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #4583

@bgrant0607 @lavalamp

### CODE REVIEW

**Comment by brendandburns** [comment]
@bgrant0607 I can haz mergez?

**Comment by rjnagal** [comment]
LGTM

File: pkg/scheduler/generic_scheduler.go [hunk 1]
```diff
@@ -76,21 +97,26 @@ func (g *genericScheduler) selectHost(priorityList HostPriorityList) (string, er
 
 // Filters the minions to find the ones that fit based on the given predicate functions
 // Each minion is passed through the predicate functions to determine if it is a fit
-func findNodesThatFit(pod api.Pod, podLister PodLister, predicates []FitPredicate, nodes api.NodeList) (api.NodeList, error) {
+func findNodesThatFit(pod api.Pod, podLister PodLister, predicates map[string]FitPredicate, nodes api.NodeList) (api.NodeList, FailedPredicateMap, error) {
```
Comment (lavalamp) [inline pkg/scheduler/generic_scheduler.go]: Nit: why not just return a FitError?
