### PR TITLE
[KEP - 3085] Add e2e test for PodReadyToStartContainerCondition when config map is created

### LINKED ISSUE #121317: [sig-node]  [Serial] [Feature:PodReadyToStartContainersCondition] starts to flaky
### What happened?

Two serial tests from sig-node are keep failing:

E2eNode Suite.[It] [sig-node] Pod conditions managed by Kubelet including PodReadyToStartContainers condition [Serial] [Feature:PodReadyToStartContainersCondition] a pod failing to mount volumes and with init containers should report just the scheduled condition set [sig-node][Changes](https://github.com/kubernetes/kubernetes/compare/760599db2...3ae76863a?)

E2eNode Suite.[It] [sig-node] Pod conditions managed by Kubelet including PodReadyToStartContainers condition [Serial] [Feature:PodReadyToStartContainersCondition] a pod failing to mount volumes and without init containers should report scheduled and initialized conditions set [sig-node][Changes](https://github.com/kubernetes/kubernetes/compare/760599db2...3ae76863a?)

pls see: 
[1] https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial
[2] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-arm64-ubuntu-serial/1714405982710272000/artifacts/build-log.txt

>   Oct 17 22:58:36.409: INFO: Unexpected error: 
      <*fmt.wrapError | 0x40005e7840>: 
      failed to update pod "pod-2ce9de2a-65da-42b7-a6a5-e84af20b5b51": Pod "pod-2ce9de2a-65da-42b7-a6a5-e84af20b5b51" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
        core.PodSpec{
        	Volumes: []core.Volume{
        		{
      - 			Name: "cm",
      + 			Name: "secret",
        			VolumeSource: core.VolumeSource{
        				... // 3 identical fields
        				AWSElasticBlockStore: nil,
        				GitRepo:              nil,
      - 				Secret:               nil,
      + 				Secret:               &core.SecretVolumeSource{SecretName: "secret", DefaultMode: &420},
        				NFS:                  nil,
        				ISCSI:                nil,
        				... // 9 identical fields
        				FC:        nil,
        				AzureFile: nil,
      - 				ConfigMap: &core.ConfigMapVolumeSource{
      - 					LocalObjectReference: core.LocalObjectReference{Name: "does-not-exist"},
      - 					DefaultMode:          &420,
      - 				},
      + 				ConfigMap:     nil,
        				VsphereVolume: nil,
        				AzureDisk:     nil,
        				... // 7 identical fields
        			},
        		},
        	},
        	InitContainers: {{Name: "init1", Image: "registry.k8s.io/e2e-test-images/busybox:1.36.1-1", Command: {"sh", "-c", "sleep 5s"}, TerminationMessagePath: "/dev/termination-log", ...}},
        	Containers: []core.Container{
        		{
        			... // 9 identical fields
        			ResizePolicy:  nil,
        			RestartPolicy: nil,
        			VolumeMounts: []core.VolumeMount{
        				{
      - 					Name:      "cm",
      + 					Name:      "secret",
        					ReadOnly:  false,
        					MountPath: "/config",
        					... // 3 identical fields
        				},
        			},
        			VolumeDevices: nil,
        			LivenessProbe: nil,
        			... // 10 identical fields
        		},
        	},
        	EphemeralContainers: nil,
        	RestartPolicy:       "Always",
        	... // 28 identical fields
        }

### What did you expect to happen?

happened since 18/10/23

### How can we reproduce it (as minimally and precisely as possible)?

run the e2e testcases manually

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

master branch
```

</details>

### Cloud provider

<details>
Impacts all
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by charles-chenzz**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
add e2e test for podreadytostartcontainercondition, as this is part of KEP 3085
#### Which issue(s) this PR fixes:

Fixes #121317

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/pod_conditions_test.go [hunk 1]
```diff
@@ -137,20 +138,27 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+								SecretName: &secretName,
+							},
 						},
 					},
 				},
-			}
+			},
+		}
+		e2epod.NewPodClient(f).Apply(ctx, applyConfig, metav1.ApplyOptions{})
+
```
Comment (charles-chenzz) [inline test/e2e_node/pod_conditions_test.go:157]: the original test was flaked due to I use update to create volume which is not allowed. using apply should be able to fix the flake

Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go:157]: Can you do this with `Kind` or a k8 cluster?  ie update a volume to an existing pod.  Usually pod updates are pretty locked down.

**Comment by kannon92** [comment]
@charles-chenzz I think we should revert the previous PR.  

I don't think this test actually does what we want.  I am also not exactly sure if we can do this after all.  

The test case I was thinking of:

1) Create a Pod with volumes pointed to a secret/config-map
2) Verify that PodReadyToStartContainers is false due to not existing secret/config-map
3) Create secret/config-map 
4) Wait for pod to have PodReadyToStartContainers true.

I don't think you are able to add volumes to a pod after it has been running.  I think you want to look into how to create a secret/config-map in the node_e2e tests.

**Comment by charles-chenzz** [comment]
> I don't think you are able to add volumes to a pod after it has been running. I think you want to look into how to create a secret/config-map in the node_e2e tests.

can you point out in which files?

I think we should wait the CI hints and gain more infos then decide if we need to revert the previous PR. wdyt? @kannon92

**Comment by kannon92** [comment]
> > I don't think you are able to add volumes to a pod after it has been running. I think you want to look into how to create a secret/config-map in the node_e2e tests.
> 
> can you point out in which files?
> 
> I think we should wait the CI hints and gain more infos then decide if we need to revert the previous PR. wdyt? @kannon92

I can't actually find a test in node_e2e that creates a secret or config-map.  So I am thinking that this test may be tricky than we thought.

I opened up a revert just in case

**Comment by kannon92** [comment]
/retitle WIP: Investigate flaky test for PodReadyToStartContainerCondition

File: test/e2e_node/pod_conditions_test.go [hunk 2]
```diff
@@ -206,6 +242,10 @@ func getTransitionTimeForPodConditionWithStatus(pod *v1.Pod, condType v1.PodCond
 
 func webserverPodSpec(podName, containerName, initContainerName string, addInitContainer bool) *v1.Pod {
 	p := &v1.Pod{
+		TypeMeta: metav1.TypeMeta{
+			Kind:       "Pod",
+			APIVersion: "v1",
+		},
```
Comment (aojea) [inline test/e2e_node/pod_conditions_test.go:248]: this is not needed

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:248]: good catch. will update soon. I was setting this field while investigating how to use ownerReference and localObjectReferece to combine the configmap we missing here.

File: test/e2e_node/pod_conditions_test.go [hunk 3]
```diff
@@ -134,6 +134,30 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+			},
+		}
+
+		_, err = f.ClientSet.CoreV1().ConfigMaps(p.Namespace).Create(ctx, &configmap, metav1.CreateOptions{})
+		framework.ExpectNoError(err)
+
+		// Verify PodReadyToStartContainers is set (since sandboxcreation is unblocked)
+		if checkPodReadyToStart {
+			_, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodReadyToStartContainers, true)
+			framework.ExpectNoError(err)
```
Comment (charles-chenzz) [inline test/e2e_node/pod_conditions_test.go:159]: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121321/pull-kubernetes-node-kubelet-serial-containerd/1715962446105022464

the configmap is created but the status is still false, been debug for a while and couldn't find out. any ideas? @kannon92

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go]: update with check in a eventually call. let's give it a try

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go]: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121321/pull-kubernetes-node-kubelet-serial-containerd/1716241761388466176

still couldn't fetch the status. I'll try recreating the pod after cm is up

Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go:160]: Yea I think what we would need to do is verify that the pod is recreated/restarted but I am not entirely sure how the pod lifecycle works.  

Recreating should work.

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:182]: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121321/pull-kubernetes-node-kubelet-serial-containerd/1716422537929297920

still not work I think. plus there's some unrelated error from the graceful-shutdown. however, I would try another method by using createSync(don't know if it works). but still, let's have a try

File: test/e2e_node/pod_conditions_test.go [hunk 4]
```diff
@@ -134,6 +134,55 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+			},
+		}
+		p2.Spec.Containers[0].VolumeMounts = []v1.VolumeMount{
+			{
+				Name:      "cm",
+				MountPath: "/config",
+			},
+		}
+
+		p2 = e2epod.NewPodClient(f).Create(ctx, p2)
```
Comment (kannon92) [inline test/e2e_node/pod_conditions_test.go:158]: I think you want to create the config map before you create this pod.  

1) create configmap
2) create pod that references config-map
3) verify true condition.

If that doesn't work, I'd suggest trying to test this flow manually and see if there is something wrong.

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:173]: move the configmap create before pod. waiting for CI.

**Comment by kannon92** [comment]
I tested this flow (create config map, create pod that references).  It seems to work fine so I think there is something up with the e2e tests. I can help look at this on Monday.

**Comment by kannon92** [comment]
```diff
diff --git a/test/e2e_node/pod_conditions_test.go b/test/e2e_node/pod_conditions_test.go
index 3a6cdc1b19b..9767f9fd412 100644
--- a/test/e2e_node/pod_conditions_test.go
+++ b/test/e2e_node/pod_conditions_test.go
@@ -149,11 +149,15 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
                        },
                }

-               _, err = f.ClientSet.CoreV1().ConfigMaps("default").Create(ctx, &configmap, metav1.CreateOptions{})
+               _, err = f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Create(ctx, &configmap, metav1.CreateOptions{})
                framework.ExpectNoError(err)

-               _, err = f.ClientSet.CoreV1().ConfigMaps("default").Get(ctx, "cm-does-not-exist", metav1.GetOptions{})
+               _, err = f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Get(ctx, "cm-does-not-exist", metav1.GetOptions{})
                framework.ExpectNoError(err)
+               defer func() {
+                       err := f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Delete(ctx, "cm-does-not-exist", metav1.DeleteOptions{})
+                       framework.ExpectNoError(err, "not able to delete configmap")
+               }()

                p2 := webserverPodSpec("pod2-"+string(uuid.NewUUID()), "web2", "init2", hasInitContainers)
                p2.Spec.Volumes = []v1.Volume{
@@ -174,15 +178,15 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
                }

                p2 = e2epod.NewPodClient(f).Create(ctx, p2)
-               framework.ExpectNoError(e2epod.WaitTimeoutForPodReadyInNamespace(ctx, f.ClientSet, p.Name, f.Namespace.Name, framework.PodStartTimeout))
+               framework.ExpectNoError(e2epod.WaitTimeoutForPodReadyInNamespace(ctx, f.ClientSet, p2.Name, p2.Namespace, framework.PodStartTimeout))

                p2, err = e2epod.NewPodClient(f).Get(ctx, p2.Name, metav1.GetOptions{})
                framework.ExpectNoError(err)

-               _, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodScheduled, true)
+               _, err = getTransitionTimeForPodConditionWithStatus(p2, v1.PodScheduled, true)
                framework.ExpectNoError(err)

-               _, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodInitialized, true)
+               _, err = getTransitionTimeForPodConditionWithStatus(p2, v1.PodInitialized, true)
                framework.ExpectNoError(err)

                // Verify PodReadyToStartContainers is set (since sandboxcreation is unblocked)
```

This patch should fix this test.  I ran it locally and I was able to get these jobs to pass.  

Summarizing these changes:

1) Config maps should be deleted after each and every test.
2) Config maps are not created in the default namespace but a test namespace.
3) The last checks should use the new pod that you created.

**Comment by charles-chenzz** [comment]
the fails seems unrelated to the changes we made here.

**Comment by kannon92** [comment]
/retitle Add e2e test for PodReadyToStartContainerCondition when config map is created

**Comment by kannon92** [comment]
@charles-chenzz I think this is good to go.  Didn't see these failures anymore.

**Comment by charles-chenzz** [comment]
> @charles-chenzz can you update the description of this PR? We are including this as part of the beta promotion for PodReadyToStartContainers. I added it to the KEP issue already but it would be nice for the description to reflect that.

added on the desc.

**Comment by charles-chenzz** [comment]
the fails seems unrelated to the changes

File: test/e2e_node/pod_conditions_test.go (hunk 3 above)
Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go:196]: We followed offline for this and fixed this. If I remember right, the fix was making sure that configMap was in the same namespace.

**Comment by kannon92** [comment]
/retitle [KEP -3085] Add e2e test for PodReadyToStartContainerCondition when config map is created

**Comment by kannon92** [comment]
/retitle [KEP - 3085] Add e2e test for PodReadyToStartContainerCondition when config map is created

File: test/e2e_node/pod_conditions_test.go [hunk 5]
```diff
@@ -134,6 +134,67 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
 		// Verify PodReady is not set (since sandboxcreation is blocked)
 		_, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodReady, false)
 		framework.ExpectNoError(err)
+
+		ginkgo.By("checking pod condition for a pod when volumes is created")
+
+		configmap := v1.ConfigMap{
+			ObjectMeta: metav1.ObjectMeta{
+				Name: "cm-does-not-exist",
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_conditions_test.go:142]: why is it called `cm-does-not-exist` if it exists? Either I don't understand the name or the what that test validates. Can you please clarify?

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:142]: the naming of this cm is wrong..
the test try to check pod condition for a pod when volumes is created( it's blocked due to cm doesn't exist). it tends to verify ``PodReadyToStartContainer`` condition have boolean change after the volume(configmap here)  create

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go]: renamed. please take a look when you get a chance. @SergeyKanzhelev

File: test/e2e_node/pod_conditions_test.go [hunk 6]
```diff
@@ -134,6 +134,62 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+			},
+			BinaryData: map[string][]byte{
+				"binaryKey": []byte("value"),
+			},
+		}
+
+		_, err = f.ClientSet.CoreV1().ConfigMaps("default").Create(ctx, &configmap, metav1.CreateOptions{})
+		framework.ExpectNoError(err)
+
+		_, err = f.ClientSet.CoreV1().ConfigMaps("default").Get(ctx, "cm-does-not-exist", metav1.GetOptions{})
```
Comment (kannon92) [inline test/e2e_node/pod_conditions_test.go:155]: This probably should be cm-that-unblock-pod-condition rather than cm-does-not-exist.

File: test/e2e_node/pod_conditions_test.go [hunk 7]
```diff
@@ -134,6 +134,62 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+		framework.ExpectNoError(err)
+
+		p2 := webserverPodSpec("pod2-"+string(uuid.NewUUID()), "web2", "init2", hasInitContainers)
+		p2.Spec.Volumes = []v1.Volume{
+			{
+				Name: "cm-2",
+				VolumeSource: v1.VolumeSource{
+					ConfigMap: &v1.ConfigMapVolumeSource{
+						LocalObjectReference: v1.LocalObjectReference{Name: "cm-does-not-exist"},
```
Comment (kannon92) [inline test/e2e_node/pod_conditions_test.go:164]: Same here. This config map doesn't exist anymore.

File: test/e2e_node/pod_conditions_test.go (hunk 5 above)
Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go]: @charles-chenzz please take a look at this again. I think you didn't rename all the instances of this.

The test failures seem related now.

File: test/e2e_node/pod_conditions_test.go (hunk 7 above)
Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:164]: my mistake. will update later today

**Comment by kannon92** [comment]
The PodReadyToStart test cases are successful.

Thank you @charles-chenzz 

/lgtm
/assign @SergeyKanzhelev

**Comment by kannon92** [comment]
For approvers, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121321/pull-kubernetes-node-kubelet-serial-containerd/1745075720918405120 has some known failures. I was making sure that this feature does not flake. This looks good to me.

File: test/e2e_node/pod_conditions_test.go [hunk 8]
```diff
@@ -134,6 +134,67 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
...
+			BinaryData: map[string][]byte{
+				"binaryKey": []byte("value"),
+			},
+		}
+
+		_, err = f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Create(ctx, &configmap, metav1.CreateOptions{})
+		framework.ExpectNoError(err)
+
+		_, err = f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Get(ctx, "cm-that-unblock-pod-condition", metav1.GetOptions{})
+		framework.ExpectNoError(err)
```
Comment (pacoxu) [inline test/e2e_node/pod_conditions_test.go:156]: If the create succeed, we don't have to get it.

```suggestion
```

File: test/e2e_node/pod_conditions_test.go [hunk 9]
```diff
@@ -134,6 +134,67 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
 		// Verify PodReady is not set (since sandboxcreation is blocked)
 		_, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodReady, false)
 		framework.ExpectNoError(err)
+
+		ginkgo.By("checking pod condition for a pod when volumes is created")
```
Comment (pacoxu) [inline test/e2e_node/pod_conditions_test.go:138]:
```suggestion
		ginkgo.By("checking pod condition for a pod with a created configmap volume")
```
This seems to be a success conditions test. This function is called `runPodFailingConditionsTest`. 

Move this part to `runPodReadyConditionsTest()` below.

**Review by pacoxu — CHANGES_REQUESTED** [review]
Or just add the configmap volume for the test case in `runPodReadyConditionsTest` and also the check there.

File: test/e2e_node/pod_conditions_test.go (hunk 9 above)
Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:138]: this test case need to success after the upper one was failed. can we move it to ``runPodReadyConditionsTest`` ?

Comment (pacoxu) [reply test/e2e_node/pod_conditions_test.go:138]: Or we may just rename the current `runPodFailingConditionsTest` 😄. (or just a comment for the function)

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:138]: can we add comment for L137 to specifically express the purpose?

File: test/e2e_node/pod_conditions_test.go (hunk 8 above)
Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go:158]: cc @charles-chenzz

Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go:158]: @kannon92 paco was right, I get it here to check it explicitly during research and now we can confirm that it's created, we can remove it

**Comment by charles-chenzz** [comment]
error was due to my mistake of removing wrong code 😓 fixing later today

**Comment by charles-chenzz** [comment]
error unrelated now

File: test/e2e_node/pod_conditions_test.go [hunk 10]
```diff
@@ -134,6 +134,66 @@ func runPodFailingConditionsTest(f *framework.Framework, hasInitContainers, chec
 		// Verify PodReady is not set (since sandboxcreation is blocked)
 		_, err = getTransitionTimeForPodConditionWithStatus(p, v1.PodReady, false)
 		framework.ExpectNoError(err)
+
+		// this testcase is creating the missing volume that unblock the pod above,
+		// and check PodReadyToStartContainer is setting correctly.
+		ginkgo.By("checking pod condition for a pod when volumes is created")
```
Comment (pacoxu) [inline test/e2e_node/pod_conditions_test.go:140]:
```suggestion
		ginkgo.By("checking pod condition for a pod when volume source is created")
```

**Review by pacoxu — APPROVED** [review]
/lgtm
one nit 🤣

/assign @mrunalp

File: test/e2e_node/pod_conditions_test.go (hunk 10 above)
Comment (kannon92) [reply test/e2e_node/pod_conditions_test.go:140]: @charles-chenzz while we are waiting for approval, could you apply this change?

**Comment by kannon92** [comment]
cc @SergeyKanzhelev @mrunalp

File: test/e2e_node/pod_conditions_test.go (hunk 10 above)
Comment (charles-chenzz) [reply test/e2e_node/pod_conditions_test.go]: applied

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by kannon92** [comment]
Nice work on leading this @charles-chenzz!
