### PR TITLE
Fix describe error of Successful Job History Limit

### LINKED ISSUE #77344: kubectl describe CronJobs - bad value in Successful Job History Limit
**What happened**:

The history limit in the describe display has the incorrect number

```
$ kubectl describe cronjobs
Name:                          update-cloud-images
Namespace:                     default
Labels:                        <none>
Annotations:                   kubectl.kubernetes.io/last-applied-configuration:
                                 {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"update-cloud-images","namespace":"default"},"spec":{"c...
Schedule:                      */1 * * * *
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  824642469512
Failed Job History Limit:      1
Starting Deadline Seconds:     180s

```

**What you expected to happen**:

The history limit should show the default limit (3)

**How to reproduce it (as minimally and precisely as possible)**:

Add a cronjob with default history limit settings and run `kubectl describe cronjob`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.2
- Kernel (e.g. `uname -a`):
Linux bionic-vm 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeam
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug
/sig cli

**What this PR does / why we need it**:

The history limit in the describe display has the incorrect number
```
$ kubectl describe cronjobs
Name:                          update-cloud-images
Namespace:                     default
Labels:                        <none>
Annotations:                   kubectl.kubernetes.io/last-applied-configuration:
                                 {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"update-cloud-images","namespace":"default"},"spec":{"c...
Schedule:                      */1 * * * *
Concurrency Policy:            Forbid
Suspend:                       False
Successful Job History Limit:  824642469512
Failed Job History Limit:      1
Starting Deadline Seconds:     180s
```
**Which issue(s) this PR fixes**:

Fixes #77344

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix kubectl describe CronJobs error of `Successful Job History Limit`.
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority backlog

File: pkg/kubectl/describe/versioned/describe.go [hunk 1]
```diff
@@ -2120,7 +2120,7 @@ func describeCronJob(cronJob *batchv1beta1.CronJob, events *corev1.EventList) (s
 		w.Write(LEVEL_0, "Concurrency Policy:\t%s\n", cronJob.Spec.ConcurrencyPolicy)
 		w.Write(LEVEL_0, "Suspend:\t%s\n", printBoolPtr(cronJob.Spec.Suspend))
 		if cronJob.Spec.SuccessfulJobsHistoryLimit != nil {
-			w.Write(LEVEL_0, "Successful Job History Limit:\t%d\n", cronJob.Spec.SuccessfulJobsHistoryLimit)
+			w.Write(LEVEL_0, "Successful Job History Limit:\t%d\n", *cronJob.Spec.SuccessfulJobsHistoryLimit)
```
Comment (liggitt) [inline pkg/kubectl/describe/versioned/describe.go]: check if this is null before dereferencing

Comment (danielqsj) [reply pkg/kubectl/describe/versioned/describe.go]: hi @liggitt , is the above check `if cronJob.Spec.SuccessfulJobsHistoryLimit != nil` not enough ?

Comment (liggitt) [reply pkg/kubectl/describe/versioned/describe.go]: oops, missed that :)
