### PR TITLE
kube-proxy: do not delete previously stale but currently active chains

### LINKED ISSUE #122604: kube-proxy nftables mode failed to delete rules due to "Device or resource busy" consistently in some cases
### What happened?

While validating nftable mode using conformance test, the following error logs were produced consistently:
```
E0104 17:21:56.957351       1 proxier.go:941] "Unable to delete stale chains; will retry later" err=<
        /dev/stdin:1:28-90: Error: Could not process rule: Device or resource busy
        delete chain ip kube-proxy service-QZNVUP4F-endpointslice-3291/example-named-port/tcp/http
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        /dev/stdin:3:28-109: Error: Could not process rule: Device or resource busy
        delete chain ip kube-proxy endpoint-A6Z5NSSV-endpointslice-3291/example-named-port/tcp/http__10.244.2.28/3001
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I0104 18:43:05.900199       1 proxier.go:935] "Deleting stale nftables chains" numChains=1
E0104 18:43:05.945300       1 proxier.go:941] "Unable to delete stale chains; will retry later" err=<
        /dev/stdin:1:28-93: Error: Could not process rule: Device or resource busy
        delete chain ip kube-proxy endpoint-EVHUKXWZ-services-4440/externalsvc/tcp/__10.244.1.80/9376
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 
I0104 18:43:06.986202       1 proxier.go:935] "Deleting stale nftables chains" numChains=3
I0104 18:43:16.462808       1 proxier.go:935] "Deleting stale nftables chains" numChains=1
E0104 18:43:16.517339       1 proxier.go:941] "Unable to delete stale chains; will retry later" err=<
        /dev/stdin:1:28-99: Error: Could not process rule: Device or resource busy
        delete chain ip kube-proxy endpoint-FJWEGLAR-services-6954/affinity-nodeport/tcp/__10.244.2.70/9376
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

I0104 18:50:42.968934       1 proxier.go:935] "Deleting stale nftables chains" numChains=8
I0104 18:50:55.643712       1 proxier.go:935] "Deleting stale nftables chains" numChains=1
E0104 18:50:55.677064       1 proxier.go:941] "Unable to delete stale chains; will retry later" err=<
        /dev/stdin:1:28-100: Error: Could not process rule: Device or resource busy
        delete chain ip kube-proxy endpoint-TK32CM73-services-3530/affinity-clusterip/tcp/__10.244.2.99/9376
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I thought it was because a known issue described here: https://github.com/kubernetes/kubernetes/blob/09a5049ca785024edd4955eb82e855d9b5657491/pkg/proxy/nftables/proxier.go#L1519-L1524
However, the error was produced for every run and every kube-proxy instance, which doesn't seem related to the kernel bug.

After some investigation, I think it's caused by a bug: in some cases a chain could change from stale to active, but once it's added to `staleChains` it will always be deleted once. When the proxier tries to delete a previously stale but currently active chain, it would fail and lead to these errors, though it won't cause real problem thanks to kernel's validation.

cc @danwinship 

### What did you expect to happen?

kube-proxy shouldn't try to delete active chains and produce such error logs.

### How can we reproduce it (as minimally and precisely as possible)?

The e2e test case can reproduce it consistantly:
```
sonobuoy run --e2e-focus "should create Endpoints and EndpointSlices for Pods matching a Service"
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.29.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In some cases a chain could change from stale to active, but once it's added to staleChains it would always be deleted once. When the proxier tries to delete a previously stale but currently active chain, it would fail and lead to errors, though it won't cause real problem thanks to kernel's validation.

The commit removes a chain from staleChains if it becomes active.

#### Which issue(s) this PR fixes:

Fixes #122604

#### Special notes for your reviewer:

If unit test is needed, we may need to override the clock with a fake clock as the scenario that triggers the bug is clock sensitive.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
@tnqn can you lgtm https://github.com/kubernetes/test-infra/pull/31550 ?

**Comment by tnqn** [comment]
@aojea The latest one failed due to feature gate not set. It seems test script missed a configuration?
```
2024-01-05T11:43:04.682462703Z stderr F I0105 11:43:04.682367       1 feature_gate.go:249] feature gates: &{map[]}
2024-01-05T11:43:04.682505356Z stderr F E0105 11:43:04.682459       1 run.go:74] "command failed" err="failed validate: KubeProxyConfiguration.Mode.ProxyMode: Invalid value: \"nftables\": must be iptables, ipvs or blank (blank means the best-available proxy [currently iptables])"
```

**Comment by tnqn** [comment]
`feature_gates` was overwritten: https://github.com/kubernetes/test-infra/blob/982870e0dea7cee8db347506f6e72bc63560fd77/experiment/kind-nftables-e2e.sh#L113-L119
```
+ feature_gates={NFTablesProxyMode:true}
+ runtime_config={}
+ feature_gates={}
```

File: pkg/proxy/nftables/proxier.go [hunk 1]
```diff
@@ -1522,6 +1522,13 @@ func (proxier *Proxier) syncProxyRules() {
 	// short amount of time later that the chain is now unreferenced. So we flush them
 	// now, and record the time that they become stale in staleChains so they can be
 	// deleted later.
+
+	// If a previously stale chain becomes active now, delete it from the staleChains.
+	for chain := range proxier.staleChains {
+		if activeChains.Has(chain) {
+			delete(proxier.staleChains, chain)
+		}
+	}
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go:1531]: hm... I think it would be better to modify the code a few lines down; we skip calling `tx.Flush()` if the chain is in `activeChains`, but we ought to actually be removing it from `staleChains`.

**Comment by danwinship** [comment]
> If unit test is needed, we may need to override the clock with a fake clock as the scenario that triggers the bug is clock sensitive.

Yeah, we need to test it, but I don't think you need a fake clock; `TestSyncProxyRulesRepeated` already tests the chain aging, by changing the timestamps in `staleChains` after the chains get added, to make them look older than they really are. You just need to extend the test there to cover this new case as well.

**Comment by tnqn** [comment]
> Yeah, we need to test it, but I don't think you need a fake clock; `TestSyncProxyRulesRepeated` already tests the chain aging, by changing the timestamps in `staleChains` after the chains get added, to make them look older than they really are. You just need to extend the test there to cover this new case as well.

Thanks for the pointer. Added test for the case. However, the fake runner can't reflect whether it ever tries to delete the chains when the chains are added back in the same round. So the test just checked the staleChains become empty.

File: pkg/proxy/nftables/proxier_test.go [hunk 2]
```diff
@@ -4649,6 +4649,73 @@ func TestSyncProxyRulesRepeated(t *testing.T) {
...
+
+		add chain ip kube-proxy service-LAUZTJTB-ns4/svc4/tcp/p80
+		add rule ip kube-proxy service-LAUZTJTB-ns4/svc4/tcp/p80 ip daddr 172.30.0.44 tcp dport 80 ip saddr != 10.0.0.0/8 jump mark-for-masquerade
+		add rule ip kube-proxy service-LAUZTJTB-ns4/svc4/tcp/p80 numgen random mod 1 vmap { 0 : goto endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 }
+		add chain ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80
+		add rule ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 ip saddr 10.0.4.1 jump mark-for-masquerade
+		add rule ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 meta l4proto tcp dnat to 10.0.4.1:80
+		`)
+	assertNFTablesTransactionEqual(t, getLine(), expected, nft.Dump())
+
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier_test.go:4681]: you could confirm that `staleEndpoints` has the expected contents at this point

File: pkg/proxy/nftables/proxier_test.go [hunk 3]
```diff
@@ -4649,6 +4649,73 @@ func TestSyncProxyRulesRepeated(t *testing.T) {
...
+		add rule ip kube-proxy service-LAUZTJTB-ns4/svc4/tcp/p80 numgen random mod 1 vmap { 0 : goto endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 }
+		add chain ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80
+		add rule ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 ip saddr 10.0.4.1 jump mark-for-masquerade
+		add rule ip kube-proxy endpoint-WAHRBT2B-ns4/svc4/tcp/p80__10.0.4.1/80 meta l4proto tcp dnat to 10.0.4.1:80
+		`)
+	assertNFTablesTransactionEqual(t, getLine(), expected, nft.Dump())
+	if len(fp.staleChains) != 0 {
+		t.Errorf("unexpected stale chains: %v", fp.staleChains)
+	}
+
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier_test.go:4718]: So now I'm wondering, what happens if you do:

- delete endpoints, sync
- time passes (ie, `ageStaleChains()`)
- add back endpoints, sync

that would result in the endpoints being deleted and then recreated in the same transaction... which I guess would have worked fine even before your patch, but maybe it's worth adding a check for that too anyway? (You don't even need to bother calling `assertNFTablesTransactionEqual` after the first sync; just confirm that the result after the second sync is the same as it was before the first one, right?)

File: pkg/proxy/nftables/proxier_test.go (hunk 2 above)
Comment (tnqn) [reply pkg/proxy/nftables/proxier_test.go]: done, I suppose you mean `staleChains` as there is no `staleEndpoints` in `nftables.Proxier`

File: pkg/proxy/nftables/proxier.go (hunk 1 above)
Comment (tnqn) [reply pkg/proxy/nftables/proxier.go]: got it, updated

File: pkg/proxy/nftables/proxier_test.go (hunk 3 above)
Comment (tnqn) [reply pkg/proxy/nftables/proxier_test.go:4723]: Added the case.

**Comment by danwinship** [comment]
/lgtm
/approve

excellent. thanks for the fix.
