### PR TITLE
Fix incorrect status msg in podautoscaler

### LINKED ISSUE #49256: Wrong HPA condition - ScalingLimited
**What happened**:
Wrong HPA condition - ScalingLimited
1. I have one rc with 1 replica(current have 1 pod)
2. I have one hpa with spec.minReplicas=1 and spec.maxReplicas=10
HPA condition ScalingLimited is true and described by below, I expect ScalingLimited=false at that time.
```
  ScalingLimited    True    TooFewReplicas        the desired replica count was less than the minimum replica count
```

**What you expected to happen**:
I expect ScalingLimited=false at above time

**How to reproduce it (as minimally and precisely as possible)**:
1. Start kubernetes with DNS
2. Start api server with --runtime-config="api/all=true"
3. Build binaries and images, deploy heapster, influxdb and grafana in kubernetes
4. Create a rc
```
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: hello-hpa-cpu
  name: hello-hpa-cpu
spec:
  replicas: 2
  selector:
    run: hello-hpa-cpu
  template:
    metadata:
      labels:
        run: hello-hpa-cpu
    spec:
      containers:
      - image: docker.io/ocpqe/hello-hpa:latest
        imagePullPolicy: IfNotPresent
        name: hello-hpa
        resources:
          requests:
            cpu: 200m
      restartPolicy: Always
```
5. Create a v2 hpa
```
apiVersion: autoscaling/v2alpha1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-resource-metrics-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: ReplicationController
    name: hello-hpa-cpu
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
```
6. Check hpa conditions by `kubelet describe hpa`
```
# kc describe hpa
Name:							hpa-resource-metrics-cpu
Namespace:						default
Labels:							<none>
Annotations:						<none>
CreationTimestamp:					Wed, 19 Jul 2017 05:58:14 -0400
Reference:						ReplicationController/hello-hpa-cpu
Metrics:						( current / target )
  resource cpu on pods  (as a percentage of request):	0% (0) / 50%
Min replicas:						1
Max replicas:						10
ReplicationController pods:				1 current / 1 desired
Conditions:
  Type			Status	Reason			Message
  ----			------	------			-------
  AbleToScale		True	ReadyForNewScale	the last scale time was sufficiently old as to warrant a new scale
  ScalingActive		True	ValidMetricFound	the HPA was able to succesfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited	True	TooFewReplicas		the desired replica count was less than the minimum replica count
```
I expect ScalingLimited of hpa conditions should be:
```
ScalingLimited    False    DesiredWithinRange    the desired replica count is within the acceptible range
```

**Addition info**:
```
# kubelet get hpa
NAME                       REFERENCE                             TARGETS    MINPODS   MAXPODS   REPLICAS   AGE
hpa-resource-metrics-cpu   ReplicationController/hello-hpa-cpu   0% / 50%   1         10        1          2m
# kubelet get rc
NAME            DESIRED   CURRENT   READY     AGE
hello-hpa-cpu   1         1         1         44s
# kubelet get pod
NAME                  READY     STATUS    RESTARTS   AGE
hello-hpa-cpu-97qpb   1/1       Running   0          49s
```

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**Which issue this PR fixes**

Fix #49256

**What this PR does / why we need it**:

When `ScalingLimited = true` for the `hpa`, there is an accompanying
status message, describing why scaling is limited. Previously if the desired
replica count was 0, and spec.minReplicas > 0, the status message
indicated "the desired replica count was less than the min replica
count". This was particularly confusing when `spec.MinReplicas = 1`. If
there was no `spec.minReplicas`, then the status message indicated "the
desired replica count was zero" which is more informative.

Update the calculation of status message so that if the desired replica
count is 0, we always display the clearer "the desired replica count was
zero" status message, even if spec.minReplicas > 0.

Signed-off-by: mattjmcnaughton <mattjmcnaughton@gmail.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
I think the failing `pull-kubernetes-e2e-kops-aws` test was flake - it succeeded upon retry.

File: pkg/controller/podautoscaler/horizontal.go [hunk 1]
```diff
@@ -435,17 +435,26 @@ func (a *HorizontalController) reconcileAutoscaler(hpav1Shared *autoscalingv1.Ho
 		// bogus CPU usage report from heapster/kubelet (like in issue #32304).
 		scaleUpLimit := calculateScaleUpLimit(currentReplicas)
 
+		replicaCountZeroStatusMsg := "the desired replica count was zero"
```
Comment (DirectXMan12) [inline pkg/controller/podautoscaler/horizontal.go]: I'd either a) make this a constant, or b) just inline it, since it's only used in two spots, and they're right next to each other.

**Review by DirectXMan12 — CHANGES_REQUESTED** [review]
one nit, otherwise LGTM

File: pkg/controller/podautoscaler/horizontal.go (hunk 1 above)
Comment (mattjmcnaughton) [reply pkg/controller/podautoscaler/horizontal.go]: Sounds good - think I'll go within inlining because - as you say, its only used in two spots and they're right next to each other.

Comment (mattjmcnaughton) [reply pkg/controller/podautoscaler/horizontal.go]: @DirectXMan12 - done, whenever you get a chance for another look. Thanks :)

Out of curiosity, what is the preference in k8s - amending the original commit when its only small changes, or creating a new commit with the small change and then squashing at the end?

**Comment by DirectXMan12** [comment]
> Out of curiosity, what is the preference in k8s - amending the original commit when its only small changes, or creating a new commit with the small change and then squashing at the end?

It comes down to reviewer preference and personal preference honestly.  The thing that matters in the end (post squash, before merge) is that each commit is a logical, mostly self-contained change (so you can have multiple commits in the end, but each should make sense as a piece of functionality).

Personally, for medium and small PRs, I prefer amending so that I can review 1 commit at a time and see the "finished" version of each commit when I do, but others have different preferences.

**Comment by DirectXMan12** [comment]
someone borked one of the tests in another PR (#52433), which somehow got past automated testing.  We'll have to wait until that gets un-borked.

**Comment by crassirostris** [comment]
@DirectXMan12 this suite is NOT blocking, submit queue is not happy about the milestone, not the test

**Comment by DirectXMan12** [comment]
@crassirostris ah, yeah, I knew about the milestone.  I think that test got moved to non-blocking after I left that comment (or I saw that message after).

**Comment by pquentin** [comment]
@mattjmcnaughton I believe that https://github.com/kubernetes/kubernetes/commit/e74838b6ab194d736d3c64b0959dea661848d61e has broken this fix which never made it in the 1.9.0 release. The message is still confusing today!
