### PR TITLE
Fix potential test flakes in HPA tests TestEventNotCreated and TestAvoidUncessaryUpdates

### LINKED ISSUE #76454: Deadlock causes flake in Horizontal Pod Autoscaler unit tests
**What happened**:

The unit test `TestEventNotCreated` for Horizontal Pod Autoscaler frequently deadlocked on the OpenShift CI system.

**What you expected to happen**:

The unit test should be robust and succeed without having to win a race condition to avoid deadlock.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure.

**Anything else we need to know?**:

Here are some logs of the problem happening:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22447/pull-ci-openshift-origin-master-unit/4610#githubcomopenshiftoriginvendork8siokubernetespkgcontrollerpodautoscaler-testeventnotcreated

The deadlocks seem to happen when the `tc.processed` chan fills up while waiting for events. If that happens, there's a race where immediately after an event is read but before it can acquire the lock to verify the test, 2 event reactors are able to acquire the lock and write to the chan. The second will block forever since the chan is full and there's nobody to read from it.

I've opened a PR with the fix. See #76455

### PR DESCRIPTION
**Pull request by joelsmith**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Fixes a potential deadlock in `TestEventNotCreated` which causes the test to time out and fail.

Also fixes potential correctness issue in `TestAvoidUncessaryUpdates` where test data was written without holding the lock.

**Which issue(s) this PR fixes**:
Fixes #76454

**Special notes for your reviewer**:
This one might be easier to review by adding `?w=1` to the files URL to have GitHub's diff ignore whitespace, like [this](https://github.com/kubernetes/kubernetes/pull/76455/files?w=1).
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by joelsmith** [comment]
Looks like the test infra failed to spin up
/test pull-kubernetes-kubemark-e2e-gce-big

**Comment by joelsmith** [comment]
@mwielgus PTAL when you have a moment
/assign @mwielgus

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 1]
```diff
@@ -330,38 +330,43 @@ func (tc *testCase) prepareTestClient(t *testing.T) (*fake.Clientset, *metricsfa
...
-		defer tc.Unlock()
-
-		obj := action.(core.UpdateAction).GetObject().(*autoscalingv1.HorizontalPodAutoscaler)
-		assert.Equal(t, namespace, obj.Namespace, "the HPA namespace should be as expected")
-		assert.Equal(t, hpaName, obj.Name, "the HPA name should be as expected")
-		assert.Equal(t, tc.expectedDesiredReplicas, obj.Status.DesiredReplicas, "the desired replica count reported in the object status should be as expected")
-		if tc.verifyCPUCurrent {
-			if assert.NotNil(t, obj.Status.CurrentCPUUtilizationPercentage, "the reported CPU utilization percentage should be non-nil") {
-				assert.Equal(t, tc.CPUCurrent, *obj.Status.CurrentCPUUtilizationPercentage, "the report CPU utilization percentage should be as expected")
+		handled, obj, err := func() (handled bool, ret *autoscalingv1.HorizontalPodAutoscaler, err error) {
```
Comment (josephburnett) [inline pkg/controller/podautoscaler/horizontal_test.go]: You need to apply this same fix to `legacy_horizontal_test.go` as well.

Looks like we were racing to fix the same race condition!  https://github.com/kubernetes/kubernetes/pull/76026/files

FYI: You can reliably reproduce this deadlock with `export GOMAXPROCS=1` and `go test ./pkg/controller/podautoscaler/... -timeout 60s -count 1`.  This PR fail on the legacy test, but your fix fixes this one!

Comment (joelsmith) [reply pkg/controller/podautoscaler/horizontal_test.go]: Thanks, I added the legacy test fix as well.

If it's all the same to you, I'd like to keep this PR going just because I merged a similar PR in OpenShift and referenced this PR. Our tooling that coordinates with this repo will be waiting for this PR to come through in a future OpenShift rebase so it can drop that patch.

Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal_test.go]: No problem.  Thanks for the additional fix in the legacy tests.  Passes now with GOMAXPROCS=1.

**Comment by josephburnett** [comment]
@mwielgus please lgtm and approve this pr.  Thanks!

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve
