### PR TITLE
[kubeadm] Remove nested retries

### LINKED ISSUE #1851: kubeadm init fails with no error and hangs forever
/kind bug

**kubeadm version** (use `kubeadm version`): 1.15.3

## What happened?
@vivgoyal recently spun up a lot of clusters (200) and 5% failed during kubeadm init. There were logs indicating kubeadm init started but then they hung forever and the process never finished. There were no logs and no timeout whatsoever. The environment was AWS.

Is there some code here that doesn't use context correctly?

## What you expected to happen?
I expected a timeout or some error information.

## How to reproduce it (as minimally and precisely as possible)?
It's an intermittent error. Only 10/200 kubeadm inits saw this problem.

### PR DESCRIPTION
**Pull request by chuckha**
This infinite poll can make kubeadm init/join hang forever due
to a lack of function cancelling.

Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR removes a bug in `kubeadm init/join` commands where it would hang forever if the API server never became accessible.

**Which issue(s) this PR fixes**:
Fixes kubernetes/kubeadm#1851

**Special notes for your reviewer**:
This removes the PollInfinite because the function calling PollInfinite already polls and there is no need for a second poll within a poll.

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a bug in kubeadm that caused init and join to hang indefinitely in specific conditions.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
https://github.com/kubernetes/kubeadm/issues/1851#issuecomment-553117808

/assign @neolit123

### CODE REVIEW

File: cmd/kubeadm/app/discovery/token/token.go [hunk 1]
```diff
@@ -74,16 +74,11 @@ func RetrieveValidatedConfigInfo(cfg *kubeadmapi.JoinConfiguration) (*clientcmda
...
-		wait.PollImmediateInfinite(constants.DiscoveryRetryInterval, func() (bool, error) {
-			var err error
-			insecureClusterInfo, err = insecureClient.CoreV1().ConfigMaps(metav1.NamespacePublic).Get(bootstrapapi.ConfigMapClusterInfo, metav1.GetOptions{})
-			if err != nil {
-				klog.V(1).Infof("[discovery] Failed to request cluster info, will try again: [%s]\n", err)
-				return false, nil
-			}
-			return true, nil
-		})
+		insecureClusterInfo, err := insecureClient.CoreV1().ConfigMaps(metav1.NamespacePublic).Get(bootstrapapi.ConfigMapClusterInfo, metav1.GetOptions{})
```
Comment (neolit123) [inline cmd/kubeadm/app/discovery/token/token.go]: like i've mentioned in the issue i think we should still PollImmediate with a sensible timeout:

possibly also change this infinite poll to the same to be consistent:
```
klog.V(1).Infof("[discovery] Requesting info from %q again to validate TLS against the pinned public key\n", 
...
wait.PollImmediateInfinite(constants.DiscoveryRetryInterval, func() (bool, error) {
```

@chuckha 
LMK if you are out of time for today and i can send the change?

Comment (neolit123) [reply cmd/kubeadm/app/discovery/token/token.go]: actually. i think i might be misunderstanding what is going here... :thinking:

Comment (neolit123) [reply cmd/kubeadm/app/discovery/token/token.go]: ok, so we need to change the second `PollImmediateInfinite` to a `CoreV1().ConfigMaps(metav1.NamespacePublic).Get` too.

**Comment by fabriziopandini** [comment]
Wondering if we should also remove the call to [wg.Wait](https://github.com/kubernetes/kubernetes/blob/055daafe238507073ce35218eb593b72991820a8/cmd/kubeadm/app/discovery/token/token.go#L220) when the timeout is triggered 

In fact, I found a little bit confusing the mix of waitgorup and stopchan, so IMO we should get rid of one of the two

**Review by rosti — COMMENTED** [review]
Thanks @chuckha !
I don't think, that removing the "insecure" `PollImmediateInfinite` call is a solution for a couple of reasons:
1. The poll is there for a reason. This might increase the join failures.
2. There is a "secure" `PollImmediateInfinite` and it's likely to suffer from similar problems even though I expect them to be far fewer there.

What we should ensure is, that we do have finite polls, that respect the join discovery timeout.

**Comment by neolit123** [comment]
@fabriziopandini @rosti @chuckha 

here is how the refactor of this file looks:
https://github.com/neolit123/kubernetes/commit/bbbc467e7897c20bed3a3053790d1f87fa891ba9

missing unit tests.

**Comment by chuckha** [comment]
> Thanks @chuckha !
> I don't think, that removing the "insecure" `PollImmediateInfinite` call is a solution for a couple of reasons:
> 
> 1. The poll is there for a reason. This might increase the join failures.
> 2. There is a "secure" `PollImmediateInfinite` and it's likely to suffer from similar problems even though I expect them to be far fewer there.
> 
> What we should ensure is, that we do have finite polls, that respect the join discovery timeout.

I think you've missed what is going on here. As outlined in the issue, this infinite poll is already wrapped in polling function. If the call to get the configmap fails, it will still be [retried](https://github.com/kubernetes/kubernetes/blob/1801019010dda24a634d4d5bb96162df8f1ea17b/cmd/kubeadm/app/discovery/token/token.go#L193) for the duration.

**Comment by chuckha** [comment]
> Wondering if we should also remove the call to [wg.Wait](https://github.com/kubernetes/kubernetes/blob/055daafe238507073ce35218eb593b72991820a8/cmd/kubeadm/app/discovery/token/token.go#L220) when the timeout is triggered
> 
> In fact, I found a little bit confusing the mix of waitgorup and stopchan, so IMO we should get rid of one of the two

Yes, the best solution, as outlined in the issue would be having a context piped all the way through. But second to that (as that is a MAJOR refactor), we could use a local context to manage timeouts. If that is still too heavy of a refactor, this change is the least amount of change to make the code work as it was originally designed.

I think removing stopchan and/or waitgroup is out of scope and is a different issue. The issue this PR fixes is nesting an infinite poll inside of a polling function.

File: cmd/kubeadm/app/discovery/token/token.go (hunk 1 above)
Comment (chuckha) [reply cmd/kubeadm/app/discovery/token/token.go]: Ah yes, there is another poll infinite in this function, that needs to be removed as well.

The reason I believe these should be removed is that the `wait.Until` that calls this function is being run every 5 seconds (by default). That makes me think this function should not have any polling/retry logic as the retry logic is scoped to the parent function.

**Comment by chuckha** [comment]
Perhaps to add a bit more context:

A polling function is calling this anonymous function.

This anonymous function, before this change, had infinite retries inside of it.

There is no context to cancel a function call.

If the infinite retries never succeed, the polling function would be blocking forever on the anonymous function and never exit.

The polling function had a retry interval of 5 seconds. This to me indicates the anonymous function it is calling should have no retries as if it fails it will be tried again in 5 seconds.

That is my reasoning behind this change.

**Comment by chuckha** [comment]
This is not the PR

> `I1113 15:04:43.003] unable to create gce instance with running docker daemon for image cos-73-11647-348-0.  googleapi: Error 404: The resource 'projects/k8s-c8d-pr-node-e2e/zones/us-west1-b/instances/tmp-node-e2e-703b5098-cos-73-11647-348-0' was not found, notFound`

/test pull-kubernetes-node-e2e-containerd

**Comment by neolit123** [comment]
/approve
leaving LGTM to @fabriziopandini and @rosti 

again mentioning that this should be reworked properly in the next cycle.
https://github.com/neolit123/kubernetes/commit/bbbc467e7897c20bed3a3053790d1f87fa891ba9

there is no need to pipe contexts or keep the wait group logic at all.

**Comment by neolit123** [comment]
the discovery in `pull-kubernetes-e2e-kind` should critical related problems.

File: cmd/kubeadm/app/discovery/token/token.go (hunk 1 above)
Comment (rosti) [reply cmd/kubeadm/app/discovery/token/token.go]: I would have taken the reverse approach - narrow down the retries to the actual connecting funcs. But I think, that this is good enough for the time being.

**Review by rosti — APPROVED** [review]
Thanks @chuckha !
This area of the code needs some revision and simplification. I think, that this is a step in the right direction and just enough so we can merge it before code freeze.
/lgtm

**Comment by fabriziopandini** [comment]
agreed! this is a nice change before code freeze, and also potentially something that can be backported.
/lgtm
/approve

again kudos to @chuckha for tracking down this issue

**Comment by neolit123** [comment]
> agreed! this is a nice change before code freeze, and also potentially something that can be backported.
> /lgtm
> /approve
> 
> again kudos to @chuckha for tracking down this issue

+1

once this merges i can send a cherry pick for 1.16.

**Comment by chuckha** [comment]
This test is a current known failure. Please see https://github.com/kubernetes/kubernetes/issues/85040

**Review by yastij — COMMENTED** [review]
/lgtm
