### PR TITLE
Use ProxierHealthUpdater directly to avoid panic

### LINKED ISSUE #87854: kube-proxy can panic if len(HealthzBindAddresses) == 0
**What happened**:

`kube-proxy`, from whatever combination of inputs we stuck into it, segfaulted. The segfault, which originates from a slightly modified fork of v1.17, looks as such:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3d1c786]
goroutine 149 [running]:
k8s.io/kubernetes/pkg/proxy/healthcheck.(*ProxierHealthServer).Updated(0x0)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/healthcheck/proxier_health.go:83 +0x26
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).SyncLoop(0xc00014db00)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:474 +0x62
k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run(0xc0001fc480, 0xc0004acc60, 0xc0004acc60)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:714 +0x735
k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop.func1(0xc0002b1a80)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:324 +0x34
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:323 +0x50
```

Translated to master, where the problem appears to be present, the segfault originates from this call:

https://github.com/kubernetes/kubernetes/blob/d90dd93855ab6c3ccda73dfbd3d19c81f56abca5/pkg/proxy/healthcheck/proxier_health.go#L89

And that is called from here:

https://github.com/kubernetes/kubernetes/blob/d90dd93855ab6c3ccda73dfbd3d19c81f56abca5/pkg/proxy/iptables/proxier.go#L512-L514

This seems odd, because

* The only pointer involved in the segfaulting call is `hs` itself
* The caller nil-checks before calling a method on `hs`.

I did some digging and found #49137, which is a fix for this problem. However, this fix appears to be undone in #83498. There doesn't seem to be a reason for this to have been changed in the latter PR.

**What you expected to happen**:

`kube-proxy` should not segfault from any bizarre combination of user input. If the situation is invalid, it should fail gracefully.

**How to reproduce it (as minimally and precisely as possible)**:

Honestly, I'm not 100% sure what combination of inputs we crammed into `kube-proxy`, but I can locate them and post them if necessary.

**Anything else we need to know?**:

I don't feel confident opening a PR to fix this myself, but in addition to recreating the fix from #49137, a comment should be added explaining why there is this weird, seemingly pointless layer of indirection when assigning to the interface, so that this doesn't get un-fixed again.

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As #87854 reported, when HealthzBindAddresses is empty, there would be panic calling ProxierHealthServer#Updated().

This PR lets newProxierHealthServer return the ProxierHealthUpdater directly to avoid panic.

**Which issue(s) this PR fixes**:
Fixes #87854

**Special notes for your reviewer**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
When adding test without HealthzBindAddress, I got the following error:
```
        	Error:      	Expected nil, but got: &errors.errorString{s:"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"}
        	Test:       	TestProxyServerWithoutHealthzBindAddress
```
Let me see how KUBERNETES_SERVICE_HOST should be populated.

**Comment by danwinship** [comment]
Blah. This is confusing and likely to get mistakenly cleaned up again in the future...

The current split between `ProxierHealthServer` and `ProxierHealthUpdater` is kind of stupid. I think a better fix for this problem would be:

1. add `ProxierHealthServer`'s `Run()` method to the `ProxierHealthUpdater` interface
2. rename `ProxierHealthServer` to `proxierHealthServer` (lowercase `p`)
3. change `healthzServer` in `cmd/kube-proxy/app/server_others.go` from `ProxierHealthServer` to `ProxierHealthUpdater`.

Then the variable is always of the interface type and there's no implicit conversion to mess things up.

> When adding test without HealthzBindAddress, I got the following error:

You probably won't be able to add a unit test of this code, because it's not separated out enough to be independently testable.

**Comment by tedyu** [comment]
Along @danwinship 's suggestion, I have:
```
	var healthzServer *healthcheck.ProxierHealthUpdater
	if len(config.HealthzBindAddress) > 0 {
		healthzServer = healthcheck.NewProxierHealthServer(config.HealthzBindAddress, 2*config.IPTables.SyncPeriod.Duration, recorder, nodeRef)
```
For iptables.NewDualStackProxier(), the second last parameter would be of type healthcheck.ProxierHealthUpdater. This requires de-referencing healthzServer which may be null.

Trying to figure out a good way of handling this.

**Comment by tedyu** [comment]
@danwinship 
I have done the refactoring.

If the formation looks good to you, I can refine it.

**Comment by tedyu** [comment]
Noticed the following for the failing TestHealthzServer test:
```
	healthSvr.Updated()
```
Stepping into the above call:
```
func (hs proxierHealthServer) Updated() {
	hs.lastUpdated.Store(hs.clock.Now())
```
I can see lastUpdated populated in IDE. Stepping out of the Updated() call, healthSvr.lastUpdated becomes Zero (by itself).

Trying to figure out why.

**Comment by davecheney** [comment]
You have a method on a value receiver, not a pointer. It receives a copy of the receiver, not the receiver itself, so the update to the copy is lost after the call.

**Comment by tedyu** [comment]
@davecheney 
thanks

**Comment by tedyu** [comment]
After changing proxierHealthServer#Updated() to have pointer receiver, the following code gets:
```
func newProxierHealthServer(listener listener, httpServerFactory httpServerFactory, c clock.Clock, addr string, healthTimeout time.Duration, recorder record.EventRecorder, nodeRef *v1.ObjectReference) *ProxierHealthUpdater {
	return &proxierHealthServer{
		listener:      listener,
		httpFactory:   httpServerFactory,
```
```
./proxier_health.go:83:3: cannot use &proxierHealthServer literal (type *proxierHealthServer) as type *ProxierHealthUpdater in return argument:
	*ProxierHealthUpdater is pointer to interface, not interface
```
If I use the following:
```
func newProxierHealthServer(listener listener, httpServerFactory httpServerFactory, c clock.Clock, addr string, healthTimeout time.Duration, recorder record.EventRecorder, nodeRef *v1.ObjectReference) ProxierHealthUpdater {
	return proxierHealthServer{
		listener:      listener,
```
I would get:
```
./proxier_health.go:76:28: cannot use proxierHealthServer literal (type proxierHealthServer) as type ProxierHealthUpdater in return argument:
	proxierHealthServer does not implement ProxierHealthUpdater (QueuedUpdate method has pointer receiver)
```

**Comment by tedyu** [comment]
For the following:
```
func NewProxierHealthServer(addr string, healthTimeout time.Duration, recorder record.EventRecorder, nodeRef *v1.ObjectReference) *ProxierHealthUpdater {
	svr := newProxierHealthServer(stdNetListener{}, stdHTTPServerFactory{}, clock.RealClock{}, addr, healthTimeout, recorder, nodeRef)
	return svr
}

func newProxierHealthServer(listener listener, httpServerFactory httpServerFactory, c clock.Clock, addr string, healthTimeout time.Duration, recorder record.EventRecorder, nodeRef *v1.ObjectReference) *proxierHealthServer {
	return &proxierHealthServer{
```
I would get:
```
./proxier_health.go:72:2: cannot use svr (type *proxierHealthServer) as type *ProxierHealthUpdater in return argument:
	*ProxierHealthUpdater is pointer to interface, not interface
```

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -594,7 +594,8 @@ func (s *ProxyServer) Run() error {
 
 	// Start up a healthz server if requested
 	if s.HealthzServer != nil {
-		s.HealthzServer.Run()
+		svr := *s.HealthzServer
+		svr.Run()
```
Comment (davecheney) [inline cmd/kube-proxy/app/server.go]: there is no need to dereference a pointer to call a method on it

File: pkg/proxy/healthcheck/proxier_health.go [hunk 2]
```diff
@@ -80,19 +85,19 @@ func newProxierHealthServer(listener listener, httpServerFactory httpServerFacto
 }
 
 // Updated updates the lastUpdated timestamp.
-func (hs *ProxierHealthServer) Updated() {
+func (hs proxierHealthServer) Updated() {
```
Comment (davecheney) [inline pkg/proxy/healthcheck/proxier_health.go]: hs is a *copy* of the receiver, this is effectively doing

x := 1
y := x
y++

// what is the value of x?

**Comment by tedyu** [comment]
@davecheney 
Please see my last two comments which showed different compilation errors when the receiver is a pointer.
The current PR compiles but is not what we want.

**Comment by davecheney** [comment]
I'm sorry I don't have bandwidth to do a full review on this change. Please
excuse my comments if they are not appropriate.

File: cmd/kube-proxy/app/server.go [hunk 3]
```diff
@@ -532,7 +532,7 @@ type ProxyServer struct {
 	UseEndpointSlices      bool
 	OOMScoreAdj            *int32
 	ConfigSyncPeriod       time.Duration
-	HealthzServer          *healthcheck.ProxierHealthServer
+	HealthzServer          *healthcheck.ProxierHealthUpdater
```
Comment (danwinship) [inline cmd/kube-proxy/app/server.go]: you need to remove the `*` from all references to `healthcheck.ProxierHealthUpdater`

File: pkg/proxy/healthcheck/proxier_health.go (hunk 2 above)
Comment (danwinship) [reply pkg/proxy/healthcheck/proxier_health.go]: but you want to leave the `*` on all references to `proxierHealthServer`

File: pkg/proxy/healthcheck/proxier_health.go [hunk 4]
```diff
@@ -42,13 +42,17 @@ type ProxierHealthUpdater interface {
...
 
-var _ ProxierHealthUpdater = &ProxierHealthServer{}
+var _ ProxierHealthUpdater = &proxierHealthServer{}
 
-// ProxierHealthServer returns 200 "OK" by default. It verifies that the delay between
+// proxierHealthServer returns 200 "OK" by default. It verifies that the delay between
 // QueuedUpdate() calls and Updated() calls never exceeds healthTimeout.
-type ProxierHealthServer struct {
+type proxierHealthServer struct {
+	ProxierHealthUpdater
```
Comment (danwinship) [inline pkg/proxy/healthcheck/proxier_health.go]: you don't want that there

**Review by danwinship — CHANGES_REQUESTED** [review]

File: cmd/kube-proxy/app/server.go (hunk 3 above)
Comment (tedyu) [reply cmd/kube-proxy/app/server.go]: With healthcheck.ProxierHealthUpdater as return type and pointer receiver for proxierHealthServer, the code doesn't compile:
```
./proxier_health.go:76:28: cannot use proxierHealthServer literal (type proxierHealthServer) as type ProxierHealthUpdater in return argument:
	proxierHealthServer does not implement ProxierHealthUpdater (QueuedUpdate method has pointer receiver)
```

Comment (danwinship) [reply cmd/kube-proxy/app/server.go]: you need to add the `&` back to `newProxierHealthServer`

**Comment by tedyu** [comment]
@danwinship 
This PR is ready for another review.

**Comment by tedyu** [comment]
@danwinship 
Please take another look.

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 5]
```diff
@@ -369,26 +369,27 @@ func TestHealthzServer(t *testing.T) {
 	fakeClock := clock.NewFakeClock(time.Now())
 
 	hs := newProxierHealthServer(listener, httpFactory, fakeClock, "127.0.0.1:10256", 10*time.Second, nil, nil)
-	server := hs.httpFactory.New(hs.addr, healthzHandler{hs: hs})
+	healthSvr := hs.(*proxierHealthServer)
+	server := healthSvr.httpFactory.New(healthSvr.addr, healthzHandler{hs: healthSvr})
```
Comment (danwinship) [inline pkg/proxy/healthcheck/healthcheck_test.go]: rather than doing this, just have the internal method (`newProxierHealthServer`) still return a `*ProxierHealthServer`, and only change the public method (`NewProxierHealthServer`) to return `ProxierHealthUpdater`

File: pkg/proxy/healthcheck/healthcheck_test.go [hunk 6]
```diff
@@ -369,26 +369,27 @@ func TestHealthzServer(t *testing.T) {
...
 
 	// Should return 200 "OK" by default.
 	testHealthzHandler(server, http.StatusOK, t)
 
 	// Should return 200 "OK" after first update
-	hs.Updated()
+	healthSvr.Updated()
```
Comment (danwinship) [inline pkg/proxy/healthcheck/healthcheck_test.go]: you don't need these changes

**Review by danwinship — COMMENTED** [review]
mostly looks right

**Comment by tedyu** [comment]
@danwinship 
I have simplified the test code.
Please take a look.

**Review by davecheney — COMMENTED** [review]
I don't see how this change fixes the panic. The majority of this change is renaming `ProxyHealthServer` to `proxyHealthServer` and introducing an interface in its place. This change would seem to violate the suggestion of _accept interfaces, return structs_ [0].



[0]: https://medium.com/@cep21/what-accept-interfaces-return-structs-means-in-go-2fe879e25ee8

**Comment by davecheney** [comment]
Looking at the original bug report
```
k8s.io/kubernetes/pkg/proxy/healthcheck.(*ProxierHealthServer).Updated(0x0)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/healthcheck/proxier_health.go:83 +0x26
```
Updated panicked because the receiver is nil (0x0)

**Review by davecheney — CHANGES_REQUESTED** [review]
reviewing the original bug report, I don't think this fix is in the right place
```
k8s.io/kubernetes/pkg/proxy/healthcheck.(*ProxierHealthServer).Updated(0x0)
        /go/src/kubernetes/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/healthcheck/proxier_health.go:83 +0x26
```
panicked because Update was called on a nil receiver, the code that constructed that reference needs to be checked.

**Comment by tedyu** [comment]
The reason that this PR is valid fix is that, in proxier.go, we check whether proxier.healthzServer is nil before calling Updated:
```
	if proxier.healthzServer != nil {
		proxier.healthzServer.Updated()
```
When config.HealthzBindAddress is empty, healthzServer is nil and we don't call Updated.

**Comment by davecheney** [comment]
> The reason that this PR is valid fix is that, in proxier.go, we check whether proxier.healthzServer is nil before calling Updated:
> 
> ```
> 	if proxier.healthzServer != nil {
> 		proxier.healthzServer.Updated()
> ```
> 
> When config.HealthzBindAddress is empty, healthzServer is nil and we don't call Updated.

Then the minimal fix would probably be just those lines.

**Comment by tedyu** [comment]
This PR is quite small - there is no change to test code.
The refactoring w.r.t. proxyHealthServer makes the API easier to understand / maintain.

**Comment by danwinship** [comment]
@davecheney the panic is because of weird tricky semantics with `nil` and `interface` types. (We ended up with a non-`nil` interface-type variable that contained a `nil` struct type, and thus checking `if proxier.healthzServer != nil` did not prevent a nil dereference.)

The "correct" fix is probably what was done in #49137. Except that this is completely non-obvious and resulted in someone (me) "simplifying" the code later (assuming that the extra variable was a leftover from an earlier version of the code) and reintroducing the panic.

My initial suggestion was to add back #49137 but add a comment clarifying it, but then it seemed better to just avoid the problem altogether.

**Comment by choury** [comment]
I opened a duplicate pr #88021, but I think check the nil interface properly is a better solution.

**Comment by tedyu** [comment]
@danwinship 
Can you approve this ?

**Comment by tedyu** [comment]
Tried modifying existing test to exercise the len(config.HealthzBindAddress) == 0 case:
```
diff --git a/cmd/kube-proxy/app/server_test.go b/cmd/kube-proxy/app/server_test.go
index 5887eabbb36..04cd21effae 100644
--- a/cmd/kube-proxy/app/server_test.go
+++ b/cmd/kube-proxy/app/server_test.go
@@ -52,7 +52,9 @@ func TestProxyServerWithCleanupAndExit(t *testing.T) {
                options.config = &kubeproxyconfig.KubeProxyConfiguration{
                        BindAddress: addr,
                }
-               options.CleanupAndExit = true
+               options.CleanupAndExit = false
+               os.Setenv("KUBERNETES_SERVICE_HOST", "127.0.0.1")
+               os.Setenv("KUBERNETES_SERVICE_PORT", "321")

                proxyserver, err := NewProxyServer(options)
```
But createClients() reads the following (non-existent) file and returns error:
```
/var/run/secrets/kubernetes.io/serviceaccount/token
```

**Comment by danwinship** [comment]
> Tried modifying existing test

yeah, the code is not designed in a way that it would be testable via the unit tests
