### PR TITLE
IPVS: kubelet, kube-proxy: unmark packets before masquerading …

### LINKED ISSUE #92553: Some IPVS e2e tests are failing
**Which jobs are failing**:
pull-kubernetes-e2e-gci-gce-ipvs

**Which test(s) are failing**:
Not all of these fail on every run:
[sig-network] Networking Granular Checks: Services should function for endpoint-Service: http
[sig-network] Services should allow pods to hairpin back to themselves through services
[sig-storage] Flexvolumes should be mountable when non-attachable
[sig-network] Networking Granular Checks: Services should function for endpoint-Service: udp
[sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should allow pods to hairpin back to themselves through services

**Since when has it been failing**:
Looking through job history, it looks like the last time any runs passed was on May 2.
 
**Testgrid link**:
N/A since testgrid filtered tests based on [sig-network]

**Anything else we need to know**:
This was discovered by @kumarvin123 in https://github.com/kubernetes/kubernetes/pull/90909, it also appears to be affecting other PRs.

/cc @andrewsykim @aojea 
/sig network

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:

The sig-network tests started to fail after the double nat fix.
The problem is that the IPVS proxier uses a POSTORUTING for the hairpin traffic that needs to happen before the
kubernetes specific postrouting rules. Prepending this ipvs only masquerade rule solves the issue.

**Which issue(s) this PR fixes**:

Fixes #92553 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

> @aojea catching up on this. So we're reverting the double-nat fix for IPVS only since it used ipset and was not impacted?

### CODE REVIEW

**Comment by aojea** [comment]
/assign @andrewsykim @uablrek 

This solves all the test failures reported in #92553 

```
I0628 16:24:49.389] FAIL! -- 757 Passed | 1 Failed | 0 Pending | 4355 Skipped
```

and gives us back to the original situation reported in, with the flexvolume test failure #91253

```
I0628 16:24:49.388] [Fail] [sig-storage] Flexvolumes [It] should be mountable when non-attachable 
I0628 16:24:49.388] test/e2e/framework/volume/fixtures.go:502
```

@danwinship added this fix to solve the double natting problem, I tried to backtrace the problem but seems that IPVS uses ipset too and I wasn't able to find out the problem , so reverting the change only in IPVS will solve the issue

**Comment by aojea** [comment]
/priority urgent-critical
This breaks kube-proxy in IPVS mode

/test pull-kubernetes-e2e-kind-ipv6 
/test pull-kubernetes-e2e-gci-gce-ipvs

**Comment by andrewsykim** [comment]
@aojea catching up on this. So we're reverting the double-nat fix for IPVS only since it used ipset and was not impacted?

**Comment by aojea** [comment]
> @aojea catching up on this. So we're reverting the double-nat fix for IPVS only since it used ipset and was not impacted?

I don't know if it was impacted, sorry, didn't go so far understanding the ipset - iptables relationship, however, with the fix in  IPVS  is broken per the test results.

I think that we should follow up and verify if the double-nat fix is needed for IPVS, but have it working until then.

**Comment by aojea** [comment]
/retest
it works :smile: 
> pull-kubernetes-e2e-gci-gce-ipvs — Job succeeded.

File: test/e2e/storage/flexvolume.go [hunk 1]
```diff
@@ -182,7 +182,7 @@ var _ = utils.SIGDescribe("Flexvolumes", func() {
 		suffix = ns.Name
 	})
 
-	ginkgo.It("should be mountable when non-attachable", func() {
+	ginkgo.It("should be mountable when non-attachable [Feature:Flexvolumes]", func() {
```
Comment (Lion-Wei) [inline test/e2e/storage/flexvolume.go:185]: I know this is for storage feature, but still feel inappropriate to directly add this label.

Comment (aojea) [reply test/e2e/storage/flexvolume.go:185]: This test is failing constantly, is breaking this job.

It seems a leftover from https://github.com/kubernetes/kubernetes/pull/91329, the linked issue says that these tests should have the feature tag to avoid breaking the e2e suite
https://github.com/kubernetes/kubernetes/issues/78737#issuecomment-627021732

I've added it as a separate commit so the git history is clean and can be reverted independently.

**Comment by Lion-Wei** [comment]
@aojea I think part of the problem is because `RETURN` rule in `KUBE-POSTROUTING` break the loop back logic. 
```
Chain KUBE-POSTROUTING (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            mark match ! 0x4000/0x4000
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK xor 0x4000
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */
MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0            /* Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose */ match-set KUBE-LOOP-BACK dst,dst,src
```

However, I think straightly revert the double-nat fix is not a good idea, maybe move `KUBE-LOOP-BACK` up could be an option.

**Comment by aojea** [comment]
> However, I think straightly revert the double-nat fix is not a good idea, maybe move `KUBE-LOOP-BACK` up could be an option.


agree that the best solution is to solve it, but right now IPVS mode is broken and I don't know if the double-nat issue with the random-fully flag is affecting IPVS, but if it does affect, it's only in some specific scenarios, we can see that all the test succeed now.

Honestly, I don't have more time to investigate :sweat_smile: , seems this logic was added here https://github.com/kubernetes/kubernetes/pull/54219 , my suggestion is to merge this, fix the job and IPVS so we can have a good test signal, and open a new Issue to solve/understand the double-nat issue in IPVS.

**Comment by Lion-Wei** [comment]
> > However, I think straightly revert the double-nat fix is not a good idea, maybe move `KUBE-LOOP-BACK` up could be an option.
> 
> agree that the best solution is to solve it, but right now IPVS mode is broken and I don't know if the double-nat issue with the random-fully flag is affecting IPVS, but if it does affect, it's only in some specific scenarios, we can see that all the test succeed now.
> 
> Honestly, I don't have more time to investigate 😅 , seems this logic was added here #54219 , my suggestion is to merge this, fix the job and IPVS so we can have a good test signal, and open a new Issue to solve/understand the double-nat issue in IPVS.

Agree.

**Comment by danwinship** [comment]
There were definitely people using IPVS in various places in the sprawling tangle of bug reports related to the random-fully/checksum problem.

> I think part of the problem is because `RETURN` rule in `KUBE-POSTROUTING` break the loop back logic.

> maybe move KUBE-LOOP-BACK up could be an option.

er, yeah, my fix assumed that kubelet and kube-proxy were creating identical `KUBE-POSTROUTING` rules.

This will hopefully eventually get fixed as part of #82125 but yes, it seems like for now just moving the `KUBE-LOOP-BACK` rule should fix this

**Comment by danwinship** [comment]
Also note that the unmark PR was backported back to 1.18, 1.17 and 1.16

**Comment by aojea** [comment]
> Also note that the unmark PR was backported back to 1.18, 1.17 and 1.16

/hold
that changes everything then, we have to fix it so we can backport it

**Comment by andrewsykim** [comment]
So I guess this also means IPVS is broken on the the v1.18, v1.17 and 1.16 release branches? 

> it seems like for now just moving the KUBE-LOOP-BACK rule should fix this

Do you think you can update this PR to do this?

**Comment by andrewsykim** [comment]
cc @kubernetes/release-managers

**Comment by aojea** [comment]
> So I guess this also means IPVS is broken on the the v1.18, v1.17 and 1.16 release branches?
> 
> > it seems like for now just moving the KUBE-LOOP-BACK rule should fix this
> 
> Do you think you can update this PR to do this?

@andrewsykim I can't understand the logic to move up the  KUBE-LOOP-BACK , I think that for someone more familiar with the code should be easy

**Comment by andrewsykim** [comment]
I think we want to move some of the masq mark rules in `createAndLinkeKubeChain` to `writeIptablesRules`. Not sure yet if that's the right solution but that would move the ordering of the rules so KUBE-LOOP-BACK is first, let's see if the e2es pass with that change first.

**Comment by andrewsykim** [comment]
@aojea actually it might be easier to update KUBE-LOOP-BACK to target KUBE-MARK-MASQ instead of MASQUERADE directly. This should be a one-line change here https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L171

**Comment by andrewsykim** [comment]
^ nvm cause the early return from KUBE-POSTROUTING is still there, but we should still do this in a follow-up PR

**Comment by rikatz** [comment]
Well my bad, I thought that I've tested this also in IPVS but it seems that not :/ Sorry about that

**Comment by aojea** [comment]
> Well my bad, I thought that I've tested this also in IPVS but it seems that not :/ Sorry about that

this is nobodies fault

**Comment by andrewsykim** [comment]
> this is nobodies fault

+100 

I'll add that this only impacts routing of pods back to the originating node so it is really easy to miss in testing. Good thing we had e2es to catch it :)

**Comment by thockin** [comment]
Good catch.  @rikatz these are the sorts of things that just happen.  There are and will always be corner cases that are not as well-exposed as the main paths.  Don't sweat it :)

**Comment by aojea** [comment]
ok, let's see if instead of masquerading directly the traffic, we just detect it and mark it, avoiding the return rule

**Comment by aojea** [comment]
this is how it look like now
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-SERVICES -m comment --comment "Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose" -m set --match-set KUBE-LOOP-BACK dst,dst,src -j KUBE-MARK-MASQ
-A KUBE-SERVICES ! -s 10.244.0.0/16 -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-SERVICES -m set --match-set KUBE-CLUSTER-IP dst,dst -j ACCEPT
```

**Comment by aojea** [comment]
nope, is not working :/

**Comment by aojea** [comment]
hehe, it works, I know that is not the more elegant fix but it works :smile: 
/hold cancel
/priority critical-urgent

File: test/e2e/storage/flexvolume.go (hunk 1 above)
Comment (andrewsykim) [reply test/e2e/storage/flexvolume.go:185]: cc @msau42 is this okay to do here?

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -1845,6 +1844,17 @@ func (proxier *Proxier) createAndLinkeKubeChain() {
 		}
 	}
 
+	// Handle traffic that loops back to the originator with SNAT.
+	// The rules should go before the kubernetes-specific ones
+	if !proxier.ipsetList[kubeLoopBackIPSet].isEmpty() {
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go:1849]: I don't think this would work because this is before we actually insert entries into the ipset https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1164-L1169

**Comment by andrewsykim** [comment]
@aojea could we instead move the mark masq rules added in https://github.com/kubernetes/kubernetes/pull/92035 to `writeIptableRules`?

File: pkg/proxy/ipvs/proxier.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/ipvs/proxier.go:1849]: the test are passing so it has to be working :sweat_smile: 
but yeah, it seems it can skip one cycle, I think it works because the ipset will have always the coredns endpoints so once it's written it's always going to be there

Comment (andrewsykim) [reply pkg/proxy/ipvs/proxier.go:1849]: Yeah it may be "working" but I don't think this is the correct solution. On line 1081, we reset the ipset entries, but this happens after `createAndLinkeKubeChain` so here we are checking against the ipset from the previous sync.

Comment (aojea) [reply pkg/proxy/ipvs/proxier.go]: right, just was trying to understand why it worked, definitively we can not move ahead with this,.
I'll change it

**Review by andrewsykim — COMMENTED** [review]
/approve

Thanks @aojea :bow: 

@danwinship can you give this one another review to make sure the mark/unmark logic is correct. Logic is the same, just shifting the ordering so it's after any rules we add to KUBE-POSTROUTING in the IPVS proxy.

File: pkg/proxy/ipvs/proxier.go (hunk 2 above)
Comment (andrewsykim) [reply pkg/proxy/ipvs/proxier.go]: yeah I'm curious too, I think we can assume it's from the previous sync but not 100% sure  :thinking:

**Comment by danwinship** [comment]
yup, lgtm

**Comment by andrewsykim** [comment]
@aojea are you gonna do the cherry-picks?

**Comment by Lion-Wei** [comment]
Seems like problem perfectly solved. 😄
If we want cherry-pick this pr, maybe leave the flexvolume commit alone. 
/lgtm

File: test/e2e/storage/flexvolume.go (hunk 1 above)
Comment (msau42) [reply test/e2e/storage/flexvolume.go:185]: The switch the distroless should not have impacted the "non-attachable" test case. This test case is passing fine in the normal k8s job: https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce&include-filter-by-regex=Flexvolume

So it would be interesting to figure out why it is consistently failing in this job.

**Comment by msau42** [comment]
/hold
sorry for the late response, but adding a feature tag to the flexvolume test is not ideal as it will not run in the default k8s jobs anymore.

**Comment by aojea** [comment]
> /hold
> sorry for the late response, but adding a feature tag to the flexvolume test is not ideal as it will not run in the default k8s jobs anymore.

yeah, my fault, was assuming it was a leftover, let me remove it

**Comment by aojea** [comment]
/hold cancel
flexvolume commit removed

**Comment by aojea** [comment]
@Lion-Wei do you mind lgtm again?

**Comment by aojea** [comment]
/retest
the ipvs job failure is because the flexvolume test only

**Comment by Lion-Wei** [comment]
@aojea Not at all.
/lgtm

**Comment by aojea** [comment]
/retest
:thinking:

**Comment by andrewsykim** [comment]
I thought the flex volume tests were failing because quay.io was down but that seemed to be fixed now https://github.com/kubernetes/kubernetes/issues/91242 ?

**Comment by andrewsykim** [comment]
Maybe we just need to update to use the staging CI image for quay? @BenTheElder might know?

**Review by andrewsykim — COMMENTED** [review]
/hold cancel

Removing the hold though since only the flex volume tests are failing and this is a known issue

**Comment by msau42** [comment]
I don't think root cause of flex volume test failing in this job is known. It's passing in normal k8s ci, so I suspect it is related to the configuration of this job.

This line from the test log is potentially suspicious and indicates that the test is trying to use IPs.
```
Jul  1 15:50:26.384: INFO: Getting external IP address for e2e-bc0cae53a3-2e794-minion-group-mxnp
```

File: test/e2e/storage/flexvolume.go (hunk 1 above)
Comment (aojea) [reply test/e2e/storage/flexvolume.go]: sorry about that, my mistake
