### PR TITLE
OpenStack LBaaSV2: EnsureLoadBalancer now updates instead of recreates existing LBs

### LINKED ISSUE #32794: OpenStack LBaaSV2: controller-manager failover causes service downtime.
### Bug Report

OpenStack LBaaSV2 integration

**Kubernetes version:** 1.3.7

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Centos7

**Behaviour**: Master failover causes loadbalancers to go into infinite create/delete loop and change ip addresses every time.

**Expected behaviour**: Service loadbalancers should update hosts (pool members). 

**Steps to reproduce**: Use controller-manager and scheduler election. Shutdown primary master (that runs controller-manager) and wait for election to happen. Observe loadbalancers.

**Additional info**: Behaviour in v1.3.6 was flawless. This is a critical OpenStack LBaaSV2 integration bug that will cause service downtime if not fixed.

### PR DESCRIPTION
**Pull request by suonto**
**What this PR does / why we need it**: Current LBaaSV2 integration recreates existing LBs and causes service downtime and floating ip rotation. New implementation updates LBs without service downtime or any ip rotation.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #32794 

**Special notes for your reviewer**: I really need this before we can move to production with kubernetes. Getting this to v1.4 would be really great. I have performed plenty of testing; lb and listener creation, port changing and listener update, multiple listeners for multi-port LBs, and deletion. Seems to work flawlessly.

**Release note**:

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33276)

### CODE REVIEW

**Comment by suonto** [comment]
cc @dagnello

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 1]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+				// Unknown error, retry later
+				return nil, fmt.Errorf("Error creating pool for listener %s: %v", listener.ID, err)
+			}
+			waitLoadbalancerActiveProvisioningStatus(lbaas.network, loadbalancer.ID)
 		}
 
-		waitLoadbalancerActiveProvisioningStatus(lbaas.network, loadbalancer.ID)
-
+		glog.V(4).Infof("Pool for listener %s: %s", listener.ID, pool.ID)
+		members, err := getMembersByPoolID(lbaas.network, pool.ID)
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]:
```go
members := pool.Members
```

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 2]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+			err := v2_pools.DeleteMember(lbaas.network, pool.ID, member.ID).ExtractErr()
+			if err != nil && !isNotFound(err) {
+				return nil, fmt.Errorf("Error deleting obsolete member %s for pool %s address %s: %v", member.ID, pool.ID, member.Address, err)
+			}
 			waitLoadbalancerActiveProvisioningStatus(lbaas.network, loadbalancer.ID)
 		}
 
-		if lbaas.opts.CreateMonitor {
-			_, err = v2_monitors.Create(lbaas.network, v2_monitors.CreateOpts{
+		monitor, err := getMonitorByPoolID(lbaas.network, pool.ID)
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]:
```go
monitor := pool.MonitorID
```

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 3]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
-			return nil, err
-		}
-
+	portID, err := getPortIDByIP(lbaas.network, loadbalancer.VipAddress)
+	if err != nil {
+		return nil, fmt.Errorf("Error getting port for LB vip %s: %v", loadbalancer.VipAddress, err)
+	}
+	floatIP, err := getFloatingIPByPortID(lbaas.network, portID)
+	if err != nil && err != ErrNotFound {
+		return nil, fmt.Errorf("Error getting flaoting ip for port %s: %v", portID, err)
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: typo: "floating"

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 4]
```diff
@@ -240,6 +240,173 @@ func getLoadbalancerByName(client *gophercloud.ServiceClient, name string) (*loa
...
+		if member.Address == addr {
+			return true
+		}
+	}
+
+	return false
+}
+
+
+func popListener(existingListeners []listeners.Listener, id string) ([]listeners.Listener) {
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Since order of listeners isn't important, this can be done with less copying (and typing) with:
```go
for i, listener := range listeners {
  if listener.ID == id {
    // remove index `i`
    listeners[i] = listeners[len(listeners)-1]
    listeners = listeners[:len(listeners)-1]
    break
  }
}

return listeners
```

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 5]
```diff
@@ -240,6 +240,173 @@ func getLoadbalancerByName(client *gophercloud.ServiceClient, name string) (*loa
...
+			} else {
+				existingListeners = append(existingListeners[:i], existingListeners[i+1:]...)
+			}
+		}
+	}
+
+	return existingListeners
+}
+
+func popMember(members []v2_pools.Member, addr string) ([]v2_pools.Member) {
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: ditto `popListener` comment

**Review by anguslees — CHANGES_REQUESTED** [review]

**Comment by suonto** [comment]
@anguslees About the cleanups: I'm planning on modifying the code not to ever return early anymore. Instead, I'd only mark listeners non-obsolete if their creation is completely error free. If unexpected error occurs in creation, I'd stop listener creation loop, leave the listener as obsolete and let listener cleanup execute, and finally return with the error that caused cleanup. What do you think?

**Comment by anguslees** [comment]
@suonto: I agree the existing cleanup approach needs to be changed/improved.
I _think_ I understand what you're describing.  Anything we can do to reduce the potential explosion of if/else codepaths would be great.

My attempt at a better unwind idiom is https://github.com/kubernetes/kubernetes/pull/32663/commits/e4a670501363723156ebf9fd3cf496ffa42be826#diff-2664a84db37825d4d9ddd8f8ec151c0bR250  (make `createFoo` functions also return a closure that undoes the change, then register `defer` handlers that invoke all the undo functions on failure).
I was intending to go back and refactor the LB functions in a similar way, but was waiting until there wasn't quite so many LB changes in flight that would need rebasing :(

**Comment by suonto** [comment]
@anguslees I took a look at your unwind - defer style, it looks cool. Anyway, the main issue for me is to know the optimal desired behaviour of the module. As I see it, cleanups might not be necessary at all. I understand, that in principle, it's nice to clean up after yourself. But I think it's fundamentally wrong that EnsureLoadBalancer ever deletes your loadbalancer, as it causes service downtime.

Now let's think about what happens upon an error. For an example, we create listener for TCP port 80, but pool creation failes due to OpenStack connection failure. Module exits with error, and is retried in a moment. On the retry, listener is not created but pool and associated components are. The same applies to all other components as well. The user sees the error in logs, and if they think a cleanup is required, they can easily delete and recreate the service.

The point being, I don't really think we need to do any cleanups, as existing objects cause no issues for retry attempts.

To address the obsolete listener deletion loop, the reason for it is that if I change my port 80 to 8080, I first create a listener for 8080, and at the end listener for 80 is deleted as obsolete. No service downtime.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 6]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+
+	if !exists {
+		glog.V(2).Infof("Creating loadbalancer %s", name)
+		loadbalancer, err = lbaas.createLoadBalancer(apiService, name)
 		if err != nil {
-			return nil, fmt.Errorf("error deleting existing openstack load balancer: %v", err)
+			// cleanup what was created so far
+			_ = lbaas.EnsureLoadBalancerDeleted(clusterName, apiService)
+			return nil, fmt.Errorf("Error creating loadbalancer %s: %v", name, err)
+		}
```
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: createLoadBalancer calls it. do you mean something else?

Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: aha.  Nope, I just mis-read which function you were calling.  Nothing to see here, carry on ;)

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 4 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: check

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 5 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: check

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 7]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
-		VipSubnetID: lbaas.opts.SubnetId,
-	}
-
-	loadBalancerIP := apiService.Spec.LoadBalancerIP
-	if loadBalancerIP != "" {
-		createOpts.VipAddress = loadBalancerIP
-	}
 
-	loadbalancer, err := loadbalancers.Create(lbaas.network, createOpts).Extract()
+	oldListeners, err := getListenersByLoadBalancerID(lbaas.network, loadbalancer.ID)
```
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: check

**Comment by zhouhaibing089** [comment]
I would like to take a look when I get time, and if I see what happened here, I am willing to take a followup to fix LBaaS v1..

**Comment by suonto** [comment]
@anguslees what is your final opinion considering cleanups? Is it EnsureLoadBalancer's responsibility to do cleanups?

As I see it, deleting existing LBs in a function that is supposed to ensure they exist is rather counter intuitive. Also, if users can take responsibility of this, they remain in control of detaching floating ips they want to preserve (and avoid possible flaoting ip rotation when using a pool) before deleting services.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 8]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
-			Persistence: persistence,
-		}).Extract()
-		if err != nil {
-			// cleanup what was created so far
-			_ = lbaas.EnsureLoadBalancerDeleted(clusterName, apiService)
-			return nil, err
+		// After all ports have been processed, remaining listeners are removed as obsolete.
+		// Pop valid listeners.
+		oldListeners = popListener(oldListeners, listener.ID)
+		pool, err := getPoolByListenerID(lbaas.network, loadbalancer.ID, listener.ID)
```
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Listener.Pools is always empty.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 1 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: pool.Members: [{Name: Weight:0 AdminStateUp:false TenantID: SubnetID: PoolID: Address: ProtocolPort:0 ID:54c42604-d6f3-4161-9216-07f4ddb73b8a}]

getMembersByPoolID: [{Name: Weight:1 AdminStateUp:true TenantID:6b582e30f65f4c05875851b4fc4ed3f1 SubnetID:b18da2d5-3901-422d-acdb-a219ab4c8b28 PoolID: Address:192.168.13.10 ProtocolPort:30461 ID:54c42604-d6f3-4161-9216-07f4ddb73b8a}]

**Comment by suonto** [comment]
Tested again after suggested improvements. Works flawlessly.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 1 above)
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: ah :(

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 9]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+		loadbalancer, err = lbaas.createLoadBalancer(apiService, name)
 		if err != nil {
-			return nil, fmt.Errorf("error deleting existing openstack load balancer: %v", err)
+			// cleanup what was created so far
+			_ = lbaas.EnsureLoadBalancerDeleted(clusterName, apiService)
+			return nil, fmt.Errorf("Error creating loadbalancer %s: %v", name, err)
+		}
+	} else {
+		glog.V(2).Infof("LoadBalancer %s already exists.")
+		loadbalancer, err = getLoadbalancerByName(lbaas.network, name)
```
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Fixed

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 2 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Fixed

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 3 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: fixed

**Comment by anguslees** [comment]
@suonto: ... Yes, I agree we shouldn't be deleting the entire LB on error - particularly in a change like this where the whole point was to avoid doing that :/
I _do_ think we should clean up what we have created on failure to avoid leaking a bunch of objects.  I'm fine with treating this hypothetical better cleanup as a "feature" and implementing it at some later stage.

So for _this_ PR: Do you want to remove _all_ the places in `EnsureLoadBalancer` that call `EnsureLoadBalancerDeleted` as error "recovery"?  I think it will be least surprising (for both future devs and users) to be consistent within this function with whatever strategy we choose.

**Comment by suonto** [comment]
@anguslees: That's great news, I'll remove the last remaining call.

**Comment by suonto** [comment]
@anguslees done.

**Comment by suonto** [comment]
@anguslees: any idea when we could get this to a realease? Just for motivation, the current 1.4.0 behavior upon primary master failure is this:
```
kubectl describe svc result-app
Name:  			result-app
Namespace:     		default
Labels:			run=result-app
Selector:      		run=result-app
Type:  			LoadBalancer
IP:    			10.254.106.145
LoadBalancer Ingress:  	192.168.16.12, 10.222.130.128
Port:  			<unset>	80/TCP
NodePort:      		<unset>	30177/TCP
Endpoints:     		10.1.90.4:80
Session Affinity:      	None
Events:
  FirstSeen    	LastSeen       	Count  	From   			SubobjectPath  	Type   		Reason 				Message
  ---------    	--------       	-----  	----   			-------------  	--------       	------ 				-------
  14m  		14m    		1      	{service-controller }  			Normal 		CreatingLoadBalancer   		Creating load balancer
  13m  		13m    		1      	{service-controller }  			Normal 		CreatedLoadBalancer    		Created load balancer
  11m  		2m     		7      	{service-controller }  			Normal 		CreatingLoadBalancer   		Creating load balancer
  11m  		1m     		7      	{service-controller }  			Warning		CreatingLoadBalancerFailed     	Error creating load balancer (will retry): Failed to create load balancer for service default/result-app: Failed to find object
```

**Review by anguslees — APPROVED** [review]
lgtm

(Thanks for persevering though to the end, @suonto.  This is a good improvement.)

**Comment by anguslees** [comment]
@suonto: Presumably this can get merged into master real-soon-now (depending mostly on the whim of the Jenkins gods).  That means it will go out with the 1.5 release, in 3 months (or so).  If you need it earlier than that, I'm afraid you will have to cherry pick the change yourself.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 10]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+			glog.V(4).Infof("Creating listener for port %d", int(port.Port))
+			listener, err = listeners.Create(lbaas.network, listeners.CreateOpts{
+				Name:           fmt.Sprintf("listener_%s_%d", name, portIndex),
+				Protocol:       listeners.Protocol(port.Protocol),
+				ProtocolPort:   int(port.Port),
+				LoadbalancerID: loadbalancer.ID,
+			}).Extract()
+			if err != nil {
+				// Unknown error, retry later
+				return nil, fmt.Errorf("Error creating LB listener: %v", err)
```
Comment (dagnello) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: any reason why we are not cleaning up between what was here prior to calling ensure lb and what we have created so far?

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 11]
```diff
@@ -345,136 +534,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
-			// cleanup what was created so far
-			_ = lbaas.EnsureLoadBalancerDeleted(clusterName, apiService)
-			return nil, err
+		// After all ports have been processed, remaining listeners are removed as obsolete.
+		// Pop valid listeners.
+		oldListeners = popListener(oldListeners, listener.ID)
+		pool, err := getPoolByListenerID(lbaas.network, loadbalancer.ID, listener.ID)
+		if err != nil && err != ErrNotFound {
+			// Unknown error, retry later
+			return nil, fmt.Errorf("Error getting pool for listener %s: %v", listener.ID, err)
```
Comment (dagnello) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: same here

**Review by dagnello — CHANGES_REQUESTED** [review]

**Comment by suonto** [comment]
@dagnello the cleanup strategies are discussed in this PR earlier in quite a verbose reasoning. To promote a few points:
1) The code works just the same in retry attempts independent of what lb-related objects exist
2) Users preserve control of cleanups
3) The point of this PR was to avoid too aggressive cleanups, service downtime and IP rotation

**Comment by suonto** [comment]
Incorporated host to nodeName change and retested.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 12]
```diff
@@ -340,142 +518,217 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+		return nil, fmt.Errorf("Error getting floating ip for port %s: %v", portID, err)
+	}
+	if floatIP == nil && lbaas.opts.FloatingNetworkId != "" {
+		glog.V(4).Infof("Creating floating ip for loadbalancer %s port %s", loadbalancer.ID, portID)
 		floatIPOpts := floatingips.CreateOpts{
 			FloatingNetworkID: lbaas.opts.FloatingNetworkId,
 			PortID:            portID,
 		}
-		floatIP, err := floatingips.Create(lbaas.network, floatIPOpts).Extract()
+		floatIP, err = floatingips.Create(lbaas.network, floatIPOpts).Extract()
```
Comment (FengyunPan) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: may loss ':'.

Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: What do you mean by this?

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 13]
```diff
@@ -340,142 +518,217 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+		}
+		glog.V(2).Infof("Creating loadbalancer %s", name)
+		loadbalancer, err = lbaas.createLoadBalancer(apiService, name)
 		if err != nil {
-			return nil, fmt.Errorf("error deleting existing openstack load balancer: %v", err)
+			// Unknown error, retry later
+			return nil, fmt.Errorf("Error creating loadbalancer %s: %v", name, err)
 		}
+	} else {
+		glog.V(2).Infof("LoadBalancer %s already exists", name)
```
Comment (dagnello) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: what happens if the lb already exists but is in degraded state?  If we are no creating a new lb, we need to ensure this lb operating_status is online and provisioning_status is ACTIVE.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 14]
```diff
@@ -340,142 +518,217 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
-		err := lbaas.EnsureLoadBalancerDeleted(clusterName, apiService)
+		if err != ErrNotFound {
+			return nil, fmt.Errorf("Error getting loadbalancer %s: %v", name, err)
+		}
+		glog.V(2).Infof("Creating loadbalancer %s", name)
+		loadbalancer, err = lbaas.createLoadBalancer(apiService, name)
 		if err != nil {
-			return nil, fmt.Errorf("error deleting existing openstack load balancer: %v", err)
+			// Unknown error, retry later
+			return nil, fmt.Errorf("Error creating loadbalancer %s: %v", name, err)
```
Comment (dagnello) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: again, we should clean up

**Comment by dagnello** [comment]
@suonto we should at least be deleting the differential between what was existing before calling ensure lb and what is being created during (ensure lb).  We do not want to leak resources over time with the only way to clean up is by waiting for EnsureLoadBalancerDeleted to be called.

Since we are re-using the existing lb with this change, we need to ensure the current lb is operational.  If not, the lb should be deleted and a new one created.

**Comment by suonto** [comment]
@dagnello @anguslees I'd like to resolve the issue of cleanups for good. It seems to me, that the more I think about it, the more I support the idea of never performing cleanups in EnsureLoadBalancer. Here's my reasoning:

First, a few important **assumptions**:
- Service downtime costs us 1000 $ / minute
- People running Kubernetes with OpenStack cloud are smart people like us

**Initial conclusions**:
- Avoiding service downtime is our first priority
- Cleanups are a secondary priority

**Benefits of performing cleanups** upon error in EnsureLoadBalancer:
- We don't leave objects in OpenStack

**Benefits of not ever performing cleanups** in EnsureLoadBalancer:
- Intuitive, if user creates a service, they expect to create objects in OpenStack
- We do not cause service downtime by accident
- Upon a permanent error (causing retry failure), the error state preserves and users can investigate the cause
- Users can detach floating ips before performing a cleanup

Conclusion:
Cleanups are potentially dangerous and counter intuitive. We should not prioritize cleanups, but do them only if we can **guarantee** that they won't be harmful to our services.

Further notes:
We do not need to treat existing loadbalancers like they could be in arbitrary states and have arbitrary related objects, because we do not cause such scenarios. If that is the case, then either the user has modified the LB, or there is something wrong with the environment. In these cases especially, we should not clean up and preserve the error state for the user to investigate. Also, when we leave objects with current code, they are not orphans. They are discovered and used in retry attempts, which actually improves the performance of retries.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 13 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: I don't think we need to be concerned about operating_status. To ensure provisioning_status, might move waitLoadbalancerActiveProvisioningStatus call out of createLoadBalancer and call in after the else section, that is indeed a good point.

Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Implemented.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 15]
```diff
@@ -241,6 +241,162 @@ func getLoadbalancerByName(client *gophercloud.ServiceClient, name string) (*loa
...
+		}
+	}
+
+	return nil
+}
+
+// Get pool for a listener. A listener always has exactly one pool.
+func getPoolByListenerID(client *gophercloud.ServiceClient, loadbalancerID string, listenerID string) (*v2_pools.Pool, error) {
+	listenerPools := make([]v2_pools.Pool, 0, 1)
+	err := v2_pools.List(client, v2_pools.ListOpts{LoadbalancerID: loadbalancerID}).EachPage(func(page pagination.Page) (bool, error) {
```
Comment (kiall) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: We've just discovered an preexisting issue with the LBaaS v2 API+K8. It is not possible (at least in Liberty) to filter the pool list by loadbalancer, or listener, ID. Neutron will silently ignore the parameter and return all pools from all listeners. 

Using this PR, Liberty OpenStack:

* Create 2 LB services.
* Wait for LB's to up+ready
* Inspect the LBaaS Pool list - Verify there are 2 pools, 1 for each LB.
* Delete 1 of the LB services.
* Inspect the LBaaS Pool list - Verify there 0 pools - pools for both loadbalancers have been deleted.

(Don't you just love Neutron's insistence on ignoring unexpected parameters)

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go [hunk 16]
```diff
@@ -346,136 +535,226 @@ func (lbaas *LbaasV2) EnsureLoadBalancer(clusterName string, apiService *api.Ser
...
+		oldListeners = popListener(oldListeners, listener.ID)
+		pool, err := getPoolByListenerID(lbaas.network, loadbalancer.ID, listener.ID)
+		if err != nil && err != ErrNotFound {
+			// Unknown error, retry later
+			return nil, fmt.Errorf("Error getting pool for listener %s: %v", listener.ID, err)
+		}
+		if pool == nil {
+			glog.V(4).Infof("Creating pool for listener %s", listener.ID)
+			pool, err = v2_pools.Create(lbaas.network, v2_pools.CreateOpts{
+				Name:        fmt.Sprintf("pool_%qs_%d", name, portIndex),
```
Comment (kiall) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: This results in some pretty odd looking names :)

	$ neutron lbaas-pool-list
	+--------------------------------------+--------------------------------------------+----------+----------------+
	| id                                   | name                                       | protocol | admin_state_up |
	+--------------------------------------+--------------------------------------------+----------+----------------+
	| 6f5f4cf6-a6c9-41d9-831f-98cde0a972f6 | pool_"ab8200e11858e11e687f7fa163e76dca"s_0 | TCP      | True           |
	| dd187fbe-059d-4cd4-bc8c-d68c2bad5bfc | pool_"ab5f92815858e11e687f7fa163e76dca"s_0 | TCP      | True           |
	+--------------------------------------+--------------------------------------------+----------+----------------+

**Review by kiall — CHANGES_REQUESTED** [review]

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 15 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Did you notice that the pools are filtered by listener ID in the code to append only those with correct listener ID? The function ensures you only get pools that belong to a listener. I'm aware that there are many issues that exist in the current 1.4 code; for example it always deletes all monitors in the project (previously tenant) when EnsureLoadBalancerDeleted is called.

Comment (kiall) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: I did, my original comment even said this should be OK as it's caught below, but then I tested it and found it continued to delete all the LBaaS pools upon deletion of a single service.

Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: @kiall now I understand you better. So basically, you're talking about this code in EnsureLoadBalancerDeleted:
```
// get all pools (and health monitors) associated with this loadbalancer
	var poolIDs []string
	var monitorIDs []string
	err = v2_pools.List(lbaas.network, v2_pools.ListOpts{LoadbalancerID: loadbalancer.ID}).EachPage(func(page pagination.Page) (bool, error) {
		poolsList, err := v2_pools.ExtractPools(page)
		if err != nil {
			return false, err
		}

		for _, pool := range poolsList {
			poolIDs = append(poolIDs, pool.ID)
			monitorIDs = append(monitorIDs, pool.MonitorID)
		}

		return true, nil
	})
	if err != nil {
		return err
	}
```

I will investigate, we are also running liberty. I can include the fix in this PR if confirmed.

Comment (kiall) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Possibly - I'm unsure exactly what codepath triggered the deletion, but something did :)

**Comment by kiall** [comment]
> I'd like to resolve the issue of cleanups for good. It seems to me, that the more I think about it, the more I support the idea of never performing cleanups in EnsureLoadBalancer. Here's my reasoning:
> 
> First, a few important assumptions:
> 
> * People running Kubernetes with OpenStack cloud are smart people like us

(Edited down quote)

So - Lots of people running Kubernetes with OpenStack are smart people like us, but not everyone is :) e.g. where a shipped/boxed product includes Kubernetes. 

I believe the cleanups are valuable, but can see the issues they can hide... If anything, This should IMO become a configuration flag, and should be performed only after all active LBs have been created/repaired/otherwise handled..

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 15 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: @kiall: I must correct myself, we're currently running mitaka. Can't reproduce the behavior you described. Your problem could be easily solved by adding similar explicit verification for loadbalancer id that getPoolByListenerID function has for listeners. Maybe it should be a separate PR though.

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 16 above)
Comment (suonto) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Fixed.

**Comment by dagnello** [comment]
+1 to @kiall suggestion on having a configuration flag

**Comment by dagnello** [comment]
@suonto that's fine with me, please raise an issue against it

File: pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go (hunk 15 above)
Comment (kiall) [inline pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go]: Fixed in https://github.com/kubernetes/kubernetes/pull/33768

**Comment by mikedanese** [comment]
@k8s-bot ok to test. Please squash fixup commits before merging.

**Comment by suonto** [comment]
@mikedanese: squashed.

**Comment by suonto** [comment]
Did `gofmt -s -w`

**Comment by suonto** [comment]
Do you guys know if the kubemark fail has anything to do with the code? Couldn't make much sense of the logs.

**Comment by suonto** [comment]
@anguslees do I need to be concerned about the kubemark test failure? If not, can you put the label back?

**Comment by anguslees** [comment]
@k8s-bot kubemark e2e test this

**Comment by dagnello** [comment]
@mikedanese @anguslees this is tested and ready to merge, can we get the lgtm label added again.  Thanks

**Comment by mikedanese** [comment]
Reviewer should be able to add lgtm with:

/lgtm
