### PR TITLE
Check empty zone after the validation of providers

### LINKED ISSUE #102680: misleading failures info when e2e storage testcase is running locally
#### What happened:

If the provide is `local`, run the below storage testcase, 

```
/usr/bin/e2e.test -ginkgo.focus="\[sig-storage\] Dynamic Provisioning DynamicProvisioner \[Slow\] should provision storage with different parameters"  -provider=local
```

Hit below exception, 
```
[It] should provision storage with different parameters
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:152
Jun  4 15:12:39.715: FAIL: Expected
    <int>: 0
not to equal
    <int>: 0

Full Stack Trace
k8s.io/kubernetes/test/e2e/storage.getRandomClusterZone(0x6f5edf8, 0x4002292f20, 0x664dec2, 0x4)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:1065 +0x9c
k8s.io/kubernetes/test/e2e/storage.glob..func30.2.1()
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:165 +0xb0
k8s.io/kubernetes/test/e2e.RunE2ETests(0x4000303380)
        _output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:131 +0x370
k8s.io/kubernetes/test/e2e.TestE2E(0x4000303380)
        _output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:144 +0x28
testing.tRunner(0x4000303380, 0x686c228)
        /usr/local/go/src/testing/testing.go:1193 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1238 +0x244
[AfterEach] [sig-storage] Dynamic Provisioning
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
```

At first glance, it looks like the return value is not correct, but looking into how the testcases was wrote, the root case should be that the testcase below doesn't support the `local` provide, 

- SSD PD on GCE/GKE
- gp2 EBS on AWS

We should provide the correct error message which will be useful for trouble shooting instead.

#### Environment:
- Kubernetes version (use `kubectl version`):   All
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`):  All
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
This make sure the testcase that cannot run locally will be skipped
instead of throw the misleading failure message.

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind failing-test

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/102680

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
it's really more appropriate for someone working on storage to review this and there are automatically assigned reviewers which haven't even had a day to respond yet, so i'm going to leave it to them for now.

**Comment by chendave** [comment]
@msau42 Can you help to bridge someone who is suitable to review this? thanks.

File: test/e2e/storage/volume_provisioning.go [hunk 1]
```diff
@@ -351,6 +351,10 @@ var _ = utils.SIGDescribe("Dynamic Provisioning", func() {
 					continue
 				}
 
+				if zone, ok := test.Parameters["zone"]; ok {
+					framework.ExpectNotEqual(len(zone), 0, "expect at least one zone")
```
Comment (msau42) [inline test/e2e/storage/volume_provisioning.go:355]: Do you want the test to fail, or be skipped?

Comment (chendave) [reply test/e2e/storage/volume_provisioning.go:355]: Should fail.
I should explained this more clearly, let me clarify why this change is needed.

Originally, the testcase will fail with the local provider, this does not make sense since this testcase should be skipped instead, code snippet right above this line have that logic, 
```
framework.ProviderIs(test.CloudProviders...)   // local provider is not belonged to `test.CloudProviders` which should be the provider like `gce` as an example.
```

But the testcase failed instead of skipped because the `getRandomClusterZone` is called before the checking of the provider. 

`getRandomClusterZone` check the `zones` which generate a map based on the below node labels,
```
failure-domain.beta.kubernetes.io/zone
topology.kubernetes.io/zone
```

local provider doesn't have necessary have the labels set on the host, so the testcase failed.

What I did was extracting the line of the code for zones checking out and defer this check to the end of the provider validation.

The motivation behind this is we are trying to enable a CI system locally and run all those storage testcases with local provider as the first step, so we need to cleanup all failures of testcases which should not fail at all.

Comment (chendave) [reply test/e2e/storage/volume_provisioning.go:355]: when the testcase hit this line means the provider is not `local` and zone label is not set, so the testcase should fail, this is an expected behavior.

and if the provider is `local`, the testcase won't hit this line at all, it should be skipped due to the provider check.

**Review by msau42 — COMMENTED** [review]
Thanks for the detailed explanation!

/lgtm
/approve
