### PR TITLE
Ensure that e2e tests run on gce|gke and are appropriately skipped for other cloud providers.

### LINKED ISSUE #7008: some gce/gke-specific e2e tests are being unintentionally skipped
I noticed while running e2e tests locally that some tests were apparently being incorrectly skipped:
```
Setting up for KUBERNETES_PROVIDER="gce".
Project: [project]
Zone: [zone]
STEP: Skipping guestbook, uses createExternalLoadBalancer, a (gce|gke) feature
STEP: Skipping Shell test, which is only supported for provider gce and gke (not )
I0417 15:33:42.606949   19035 driver.go:61] ***** provider is 'gce'
Running Suite: Kubernetes e2e Suite run 1 of 1
==============================================
Random Seed: 1429310022 - Will randomize all specs
Will run 34 of 39 specs
...
```

I checked, and this is also true for our Jenkins runs.

Currently it looks like test/e2e/shell.go and test/e2e/kubectl.go have this bug, though only the former actually skips the test, I think.

The issue appears to be that the code inside the top-level `Describe()` in these files is being run before the testContext struct is filled out (and before `ginkgo.RunSpecsWithDefaultAndCustomReporters` is even called), and so testContext.Provider is empty.

I'm not immediately sure what the proper fix is; I'm also worried that there might be other things broken by the fact that these blocks are called before initialization is complete.

We also probably investigate if there is a better way to mark these tests as skipped; right now, there's no indication in the test report (JUnit.xml, Jenkins test report, etc) that these tests were skipped.

### PR DESCRIPTION
**Pull request by roberthbailey**
Fixes #7008.

```
$ go run hack/e2e.go -v -test --test_args="--ginkgo.focus=Shell.*"
Random Seed: 1429397117 - Will randomize all specs
Will run 1 of 40 specs

SSSSSSSSSSSS
------------------------------
Shell
  tests that services.sh passes
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:55
[It] tests that services.sh passes
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:55
STEP: Running /Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/e2e-suite/services.sh

• [SLOW TEST:180.331 seconds]
Shell
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:57
  tests that services.sh passes
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/shell.go:55
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 40 Specs in 180.332 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 39 Skipped I0418 15:48:18.165463   92339 driver.go:96] All tests pass

$ go run hack/e2e.go -v -test --test_args="--ginkgo.focus=kubectl.*guestbook.*"
Random Seed: 1429397326 - Will randomize all specs
Will run 1 of 40 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
kubectl guestbook
  should create and stop a working application
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:112
[BeforeEach] kubectl
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:53
>>> testContext.KubeConfig: /Users/robertbailey/.kube/config
[It] should create and stop a working application
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:112
STEP: creating all guestbook components
INFO: Running '/Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/../cluster/../_output/dockerized/bin/darwin/amd64/kubectl kubectl --kubeconfig=/U
sers/robertbailey/.kube/config create -f examples/guestbook'INFO: replicationControllers/frontend-controller
services/frontend
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave

STEP: validating guestbook app
INFO: Waiting for frontend to serve content.INFO: Trying to add a new entry to the guestbook.
INFO: Verifying that added entry can be retrieved.
STEP: using stop to clean up resources
INFO: Running '/Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/../cluster/../_output/dockerized/bin/darwin/amd64/kubectl kubectl --kubeconfig=/Users/robertbailey/.kube/config stop -f examples/guestbook'
INFO: replicationControllers/frontend-controller
services/frontend
replicationControllers/redis-master-controller
services/redis-master
replicationControllers/redis-slave-controller
services/redis-slave

INFO: Running '/Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/../cluster/../_output/dockerized/bin/darwin/amd64/kubectl kubectl --kubeconfig=/Users/robertbailey/.kube/config get pods,rc,se -l name=frontend --no-headers'
INFO:
INFO: Running '/Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/../cluster/../_output/dockerized/bin/darwin/amd64/kubectl kubectl --kubeconfig=/Users/robertbailey/.kube/config get pods,rc,se -l name=redis-master --no-headers'
INFO:
INFO: Running '/Users/robertbailey/Work/go/src/github.com/roberthbailey/kubernetes/hack/../cluster/../_output/dockerized/bin/darwin/amd64/kubectl kubectl --kubeconfig=/Users/robertbailey/.kube/config get pods,rc,se -l name=redis-slave --no-headers'
INFO:

• [SLOW TEST:62.806 seconds]
kubectl
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:115
  guestbook
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:113
    should create and stop a working application
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:112
------------------------------
SSSSSSSSS
Ran 1 of 40 Specs in 62.807 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 39 Skipped I0418 15:49:49.468811   94011 driver.go:96] All tests pass
```

### CODE REVIEW

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -97,11 +97,11 @@ var _ = Describe("kubectl", func() {
 	Describe("guestbook", func() {
 		var guestbookPath = filepath.Join(testContext.RepoRoot, "examples/guestbook")
 
-		if testContext.Provider != "gce" && testContext.Provider != "gke" {
-			By(fmt.Sprintf("Skipping guestbook, uses createExternalLoadBalancer, a (gce|gke) feature"))
-		}
-
 		It("should create and stop a working application", func() {
+			if testContext.Provider != "gce" && testContext.Provider != "gke" {
+				By(fmt.Sprintf("Skipping guestbook, uses createExternalLoadBalancer, a (gce|gke) feature"))
```
Comment (ixdy) [inline test/e2e/kubectl.go]: nit: use lowercase for "Skipping" perhaps?

Comment (ixdy) [inline test/e2e/kubectl.go]: also, does this actually skip anything? It seems like all this does is print out the By line, but doesn't actually have any logic to really skip (unless that's hidden somewhere else?)

File: test/e2e/shell.go [hunk 2]
```diff
@@ -53,6 +45,12 @@ var _ = Describe("Shell", func() {
 	for _, file := range files {
 		fileName := file.Name() // Make a copy
 		It(fmt.Sprintf("tests that %v passes", fileName), func() {
+			// A number of scripts only work on gce
+			if testContext.Provider != "gce" && testContext.Provider != "gke" {
+				By(fmt.Sprintf("Skipping Shell test, which is only supported for provider gce and gke (not %s)",
```
Comment (ixdy) [inline test/e2e/shell.go]: Same nit about lowercase.
Also maybe include the fileName here?

File: test/e2e/kubectl.go (hunk 1 above)
Comment (roberthbailey) [inline test/e2e/kubectl.go]: Lowercase is used for error strings, but not log statements. See https://github.com/golang/go/wiki/CodeReviewComments#error-strings which says "This does not apply to logging, which is implicitly line-oriented and not combined inside other messages." and By() statements are logging statements.

Comment (roberthbailey) [inline test/e2e/kubectl.go]: Added a return here.

File: test/e2e/shell.go (hunk 2 above)
Comment (roberthbailey) [inline test/e2e/shell.go]: Added the filename.

File: test/e2e/kubectl.go [hunk 3]
```diff
@@ -97,11 +97,12 @@ var _ = Describe("kubectl", func() {
 	Describe("guestbook", func() {
 		var guestbookPath = filepath.Join(testContext.RepoRoot, "examples/guestbook")
 
-		if testContext.Provider != "gce" && testContext.Provider != "gke" {
-			By(fmt.Sprintf("Skipping guestbook, uses createExternalLoadBalancer, a (gce|gke) feature"))
-		}
-
 		It("should create and stop a working application", func() {
+			if testContext.Provider != "gce" && testContext.Provider != "gke" {
```
Comment (quinton-hoole) [inline test/e2e/kubectl.go]: Please add a check for testContext.Provider being empty string or nil, and Fail if it is, to prevent similar errors in the future.   We should ideally wrap this in a utility function in test/e2e/util.go so that other tests can benefit from it.

File: test/e2e/shell.go [hunk 4]
```diff
@@ -53,6 +45,12 @@ var _ = Describe("Shell", func() {
 	for _, file := range files {
 		fileName := file.Name() // Make a copy
 		It(fmt.Sprintf("tests that %v passes", fileName), func() {
+			// A number of scripts only work on gce
+			if testContext.Provider != "gce" && testContext.Provider != "gke" {
```
Comment (quinton-hoole) [inline test/e2e/shell.go]: Same comment as above.  Please check for uninitialized value and fail.

File: test/e2e/kubectl.go (hunk 3 above)
Comment (roberthbailey) [inline test/e2e/kubectl.go]: It isn't a pointer to string, so it can't be nil. I added a check here and everywhere else we use this value to make sure it isn't the empty string (which was many places other than these two files).

File: test/e2e/certs.go [hunk 5]
```diff
@@ -32,6 +32,9 @@ var _ = Describe("MasterCerts", func() {
 	})
 
 	It("should have all expected certs on the master", func() {
+		if testContext.Provider == "" {
```
Comment (quinton-hoole) [inline test/e2e/certs.go]: I would have much preferred a shared utility function along the lines of:

ProviderEquals(string) bool

... than cut-n-pasting this logic all over the place like this.  But lets get this merged now, and fix the aforementioned in a separate PR.  Please open an issue for that.

Comment (roberthbailey) [inline test/e2e/certs.go]: Created #7057.

Comment (roberthbailey) [inline test/e2e/certs.go]: Since this hasn't merged yet, I went ahead and created a shared util function in this PR. PTAL.

File: test/e2e/util.go [hunk 6]
```diff
@@ -62,6 +62,18 @@ func Failf(format string, a ...interface{}) {
 	Fail(fmt.Sprintf(format, a...), 1)
 }
 
+func providerIs(providers ...string) bool {
+	if testContext.Provider == "" {
+		Fail("testContext.Provider is not defined")
+	}
+	for _, provider := range providers {
+		if provider == testContext.Provider {
```
Comment (quinton-hoole) [inline test/e2e/util.go]: nit: Rather perform a case-insensitive comparison?

**Comment by quinton-hoole** [comment]
Other than minor nit, LGTM.

File: test/e2e/util.go (hunk 6 above)
Comment (roberthbailey) [inline test/e2e/util.go]: done.

**Comment by quinton-hoole** [comment]
LGTM, merging.
