### PR TITLE
kubeadm: statically default the "from cluster" InitConfiguration

### LINKED ISSUE #2523: failing test: kubeadm-kinder-upgrade-1-21-latest
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-21-latest
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-21-latest/1412679168415502336/artifacts/task-06-upgrade-log.txt

the problem is:
> [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: unsupported pull policy ""
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
[upgrade/version] Found 1 potential version compatibility errors but skipping since the --force flag is set: 

seems like our defaulting for the InitConfiguration.ImagePullPolicy is not happening during upgrade.

bug introduced in:
https://github.com/kubernetes/kubernetes/pull/103496

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

During operations such as "upgrade", kubeadm fetches the
ClusterConfiguration object from the kubeadm ConfigMap.
However, due to requiring node specifics it wraps it in an
InitConfiguration object. The function responsible for that is:
  app/util/config#FetchInitConfigurationFromCluster().

A problem with this function (and sub-calls) is that it ignores
the static defaults applied from versioned types
(e.g. v1beta3/defaults.go) and only applies dynamic defaults for:
- API endpoints
- node registration
- etc...

The introduction of Init|JoinConfiguration.ImagePullPolicy now
has static defaulting of the NodeRegistration object with a default
policy of "PullIfNotPresent". Respect this defaulting by constructing
a defaulted internal InitConfiguration from
FetchInitConfigurationFromCluster() and only then apply the dynamic
defaults over it.

This fixes a bug where "kubeadm upgrade ..." fails when pulling images
due to an empty ("") ImagePullPolicy. We could assume that empty
string means default policy on runtime in:
cmd/kubeadm/app/preflight/checks.go#ImagePullCheck()

but that might actually not be the user intent during "init" and "join",
due to e.g. a typo. Similarly, we don't allow empty tokens
on runtime and error out.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2523

#### Special notes for your reviewer:
i tested locally that "kubeadm upgrade apply ..." works after this change.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/config/cluster.go [hunk 1]
```diff
@@ -68,8 +69,13 @@ func getInitConfigurationFromCluster(kubeconfigDir string, client clientset.Inte
 		return nil, errors.Wrap(err, "failed to get config map")
 	}
 
-	// InitConfiguration is composed with data from different places
+	// Take an empty versioned InitConfiguration, statically default it and convert it to the internal type
+	versionedInitcfg := &kubeadmapiv1.InitConfiguration{}
+	kubeadmscheme.Scheme.Default(versionedInitcfg)
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/cluster.go:74]: FYI, this calls:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta3/defaults.go#L74-L79

the problem in the linked issue is only caused by the lack of calling:
- SetDefaults_NodeRegistration()

but also calling:
- SetDefaults_BootstrapTokens(obj)
- SetDefaults_APIEndpoint(&obj.LocalAPIEndpoint)

is fine because:
- tokens receive sane defaults, like tiimeouts
- apiendpoint receives the default port, but is later overriden by the dynamic defaults in this getInitConfigurationFromCluster() function.

File: cmd/kubeadm/app/util/config/cluster_test.go [hunk 2]
```diff
@@ -730,6 +730,9 @@ func TestGetInitConfigurationFromCluster(t *testing.T) {
 			if cfg.ClusterConfiguration.KubernetesVersion != k8sVersionString {
 				t.Errorf("invalid ClusterConfiguration.KubernetesVersion")
 			}
+			if cfg.NodeRegistration.ImagePullPolicy != kubeadmapiv1.DefaultImagePullPolicy {
+				t.Errorf("invalid cfg.NodeRegistration.ImagePullPolicy %v", cfg.NodeRegistration.ImagePullPolicy)
+			}
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/cluster_test.go:735]: this unit test:
- ensures defaulting happens
- adds test coverage for the regression / bug

Comment (pacoxu) [reply cmd/kubeadm/app/util/config/cluster_test.go:735]: UT would be valuable.

Recently, there are several PRs that pass k/k CIs and break kubeadm CI. It's hard to catch this problem during PR review.

Comment (neolit123) [reply cmd/kubeadm/app/util/config/cluster_test.go:735]: the unit test here is sufficient to catch the exact problem.

as far as CI goes, the CI here uses kind and it skips preflight (where the pre-pull failures were) and it does not do "kubeadm upgrade", ideally we'd need a kinder based CI.

**Comment by pacoxu** [comment]
/test pull-kubernetes-integration
flake a lot today
