### PR TITLE
Check for EmptyConfig errors when trying to use in-cluster config

### LINKED ISSUE #31910: Failed to create a kubernetes client: invalid configuration: no configuration has been provided
From PR #31894

Working on the addon kube-dns, but found the lastest kube-dns program failed to start with below error:
`F0901 17:39:14.914386       1 server.go:55] Failed to create a kubernetes client: invalid configuration: no configuration has been provided`

After a bit exploration, found this commit 06cbb29e9e9b10c371347d2457ff8708f4a9e9f5

kube-dns works after revert this patch.

@smarterclayton @thockin @girishkalele

### PR DESCRIPTION
**Pull request by smarterclayton**
By removing the default "localhost:8080" behavior several paths in
client config began returning err == ErrEmptyConfig rather than err ==
nil.  The code checking for in cluster config was wrong - the logic
should be:
1. If loading the underlying config returns a non-empty error, fail
2. If the underlying config is not equal to the default config,
   return that config (it has user input)
3. If it is possible to use in-cluster config, do so
4. Otherwise return the default config (and or default EmptyConfig
   error).

Fixes #31910 @thockin @lavalamp @deads2k. We introduced EmptyConfig a very long time ago, but until I removed the "localhost:8080" Kubernetes was not actually exposing it (OpenShift relies on it since we don't set an insecure default). This properly falls through to in-cluster config in the described conditions.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31947)

``` release-note
Some components like kube-dns and kube-proxy could fail to load the service account token when started within a pod. Properly handle empty configurations to try loading the service account config.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Note the controller and scheduler were not affected because they don't use a DeferredClient.  Kubectl was not affected because it uses a DeferredClient with defaulting.  OpenShift would not have been broken since we use a wrapper (which basically was there to fix this particular bug).

**Comment by smarterclayton** [comment]
I don't think this needs a release note because the issue never actually manifested in any code (kube-dns was not built).

**Comment by smarterclayton** [comment]
@deads2k can you review?

File: pkg/client/unversioned/clientcmd/client_config.go [hunk 1]
```diff
@@ -358,21 +358,21 @@ func (inClusterClientConfig) ClientConfig() (*restclient.Config, error) {
 	return restclient.InClusterConfig()
 }
 
-func (inClusterClientConfig) Namespace() (string, error) {
```
Comment (lavalamp) [inline pkg/client/unversioned/clientcmd/client_config.go]: this function never actually returns an error. Remove the error parameter or use it instead of the bool.

**Comment by lavalamp** [comment]
I still can't understand this loader code. lgtm but maybe @jlowdermilk wants to take a look?

File: pkg/client/unversioned/clientcmd/client_config.go (hunk 1 above)
Comment (deads2k) [inline pkg/client/unversioned/clientcmd/client_config.go]: > this function never actually returns an error. Remove the error parameter or use it instead of the bool.

It's implementing an interface.  Other implementors do return errors.

File: pkg/client/unversioned/clientcmd/merged_client_builder.go [hunk 2]
```diff
@@ -92,18 +99,32 @@ func (config *DeferredLoadingClientConfig) ClientConfig() (*restclient.Config, e
...
 	}
-	// Are we running in a cluster and were no other configs found? If so, use the in-cluster-config.
-	icc := inClusterClientConfig{}
-	defaultConfig, err := DefaultClientConfig.ClientConfig()
-	if icc.Possible() && err == nil && reflect.DeepEqual(mergedConfig, defaultConfig) {
-		glog.V(2).Info("No kubeconfig could be created, falling back to service account.")
-		return icc.ClientConfig()
+
+	// check for in-cluster configuration and use it
+	if config.icc.Possible() {
```
Comment (deads2k) [inline pkg/client/unversioned/clientcmd/merged_client_builder.go]: If this is going to have priority, why don't we do it first?

Comment (deads2k) [inline pkg/client/unversioned/clientcmd/merged_client_builder.go]: hrm, I see.  It doesn't have priority.  And it can't go into the switch above because of the error handling down the non-nil patch.  What sticky little bit of code.

File: pkg/client/unversioned/clientcmd/client_config.go (hunk 1 above)
Comment (deads2k) [inline pkg/client/unversioned/clientcmd/client_config.go]: Add a couple type assertions.  this dropped out of the `ClientConfig` interface at some point.

Comment (lavalamp) [inline pkg/client/unversioned/clientcmd/client_config.go]: If it's part of an interface, then change the interface, too-- (string, bool, error) is a confusing return set.

Comment (smarterclayton) [inline pkg/client/unversioned/clientcmd/client_config.go]: The interface is correct - this implementation just happens not to return an error.  The bool is "was this specified" by the user.  The string is the value.  We use the bool all over the code to determine between user passed "--namespace" on the CLI vs getting the "default" namespace.

**Comment by smarterclayton** [comment]
@deads2k any other comments?

**Comment by deads2k** [comment]
@smarterclayton no more comments from me.

lgtm, could use a squash.

**Comment by smarterclayton** [comment]
Squashed

**Comment by eparis** [comment]
removing cherrypick-candidate as this was previously merged in release-1.4
