### PR TITLE
fix: should not set default storageclass if annotation "volume.beta.kubernetes.io/storage-class" is set

### LINKED ISSUE #116028: PVs with annotations are not being dynamically provisioned on k8s 1.26.1
### What happened?

We observed that when deplying manifests to a cluster running 1.26.1-gke.200, the StorageClass and PVC get created successfully. However, the PVC is stuck in a Pending state and no PV is provisioned.

The workaround is to add storageClassName to one of the pending PVCs on cluster, and it did go from Pending to properly provisioned a PV and reaching Bound state. 

We looked at the logs and found that according to the doc: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class,

```
In the past, the annotation volume.beta.kubernetes.io/storage-class 
was used instead of the storageClassName attribute. This annotation
 is still working; however, it will become fully deprecated in a future 
Kubernetes release.
```

Is this annotation is fully deprecated in the new 1.26.1 release? If yes can we add this detail to documentation or release note?

### What did you expect to happen?

the PVC should not stuck in a Pending state and PV is provisioned in 1.26.1

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a 1.26.1-gke.200 cluster in GKE
2. Create via yaml

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sunnytest-sc
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-class-issue-test
spec:
  selector:
    matchLabels:
      app: storage-class-issue-test
  serviceName: storage-class-issue-test
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-class-issue-test
    spec:
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: local-disk
          mountPath: /data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: sunnytest-sc
      creationTimestamp: null
      name: cassandra-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
```

### Anything else we need to know?

The error comes form the code: https://github.com/kubernetes/kubernetes/blob/915924e64d08b7b2d3e6da81840e46d96304cdc9/pkg/controller/volume/persistentvolume/pv_controller_base.go#L275 and https://github.com/kubernetes/kubernetes/blob/915924e64d08b7b2d3e6da81840e46d96304cdc9/pkg/apis/core/validation/validation.go#L2259

There are some hypotheses here:

The annotation volume.beta.kubernetes.io/storage-class does not work on 1.26.1 any more, so a default storage class is being populated to the PVC.
For some reason, the [DefaultStorageClass admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#defaultstorageclass) did not work, so the PVC was deployed with an empty StorageClass nil.
Then the kube controller manager tried to update the PVC with the default StorageClass, which triggered the error:

### Kubernetes version

<details>

```console
$ kubectl version
# NA
```

</details>

### Cloud provider

<details>

GKE

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by cvvz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
No need to set default storageclass if annotation "volume.beta.kubernetes.io/storage-class" is set
#### Which issue(s) this PR fixes:

Fixes #116028

#### Does this PR introduce a user-facing change?

```release-note
Fixed a 1.26 regression where Kubernetes would apply a default StorageClass to a PersistentVolumeClaim,
even when the deprecated annotation `volume.beta.kubernetes.io/storage-class` was set.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cvvz** [comment]
cc @RomanBednar

**Comment by cvvz** [comment]
cc @RomanBednar PTAL, thanks.

**Comment by sftim** [comment]
We should also document `volume.beta.kubernetes.io/storage-class` - see https://github.com/kubernetes/website/issues/39704

**Comment by sftim** [comment]
Suggestion for the changelog entry:
```markdown
Fixed a bug where Kubernetes would apply a default StorageClass to a PersistentVolumeClaim,
even when the deprecated annotation `volume.beta.kubernetes.io/storage-class` was set.
```

File: pkg/controller/volume/persistentvolume/pv_controller.go [hunk 1]
```diff
@@ -937,7 +937,7 @@ func (ctrl *PersistentVolumeController) updateVolumePhaseWithEvent(volume *v1.Pe
 // Ignores claims that already have a storage class.
 // TODO: if resync is ever changed to a larger period, we might need to change how we set the default class on existing unbound claims
 func (ctrl *PersistentVolumeController) assignDefaultStorageClass(claim *v1.PersistentVolumeClaim) (bool, error) {
-	if claim.Spec.StorageClassName != nil {
+	if storagehelpers.GetPersistentVolumeClaimClass(claim) != "" {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/pv_controller.go:940]: Can you add a unit test for the fix?

Comment (cvvz) [reply pkg/controller/volume/persistentvolume/pv_controller.go:940]: Sure, added.

**Comment by andyzhangx** [comment]
@cvvz could you cherry-pick to the broken releases?

**Comment by cvvz** [comment]
@andyzhangx Sure.
