### PR TITLE
Fix cluster IP allocator metrics

### LINKED ISSUE #109994: The metrics for the cluster IP allocator are incorrectly reported
### What happened?

The metrics for the cluster IP allocator (`kube_apiserver_clusterip_allocator_*`) are occasionally reported incorrect values. I suspect that the metrics are overwritten by [the repair loop](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L41-L42).

The following example is the metrics on a cluster with only two services. `allocated_ips` and `allocation_total` should be 2.

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 0
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 14
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048574e+06

$ kubectl get svc --all-namespaces
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  20m
kube-system   kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   20m
```

/sig  network

### What did you expect to happen?

I expected it reports the correct metrics for the cluster IP allocator.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Kubernetes v1.24 cluster. I confirmed the issue on the minikube with the following command.

```
minikube start --kubernetes-version v1.24.0
```

2. Immediately after starting the cluster, it correctly reports that `allocated_ips` is 2 and `allocation_total` is 2.

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 2
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048572e+06
```

3. But after a while with doing nothing, it incorrectly reports that `allocation_ips` is 0 and `allocation_total` is 4

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 0
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 4
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048574e+06
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube v1.25.2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tksm**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix the bug that the metrics for the cluster IP allocator are incorrectly reported.

#### Which issue(s) this PR fixes:

Fixes #109994

#### Special notes for your reviewer:
It seems [the repair loop](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L41-L42) unintentionally overwrote the metrics. I made the metrics recording disabled by default and made it enabled in only [LegacyRESTStorage](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/rest/storage_core.go#L106).

I verified the metrics no longer changed after [the repair interval (3m)](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/controlplane/instance.go#L125-L126) on kind.

<details>
I verified with the following script after creating two dual-stack services.

```bash
echo "# $(date)"
kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator" | tee prev.txt
for i in $(seq 1 5); do
  sleep 60
  echo "# $(date)"
  kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator" > current.txt
  diff prev.txt current.txt
  cp current.txt prev.txt
done
```

#### After fix
After this fix, the metrics no longer changed within 5 minutes.

```
# Fri May 13 09:17:21 JST 2022
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/20"} 4
kube_apiserver_clusterip_allocator_allocated_ips{cidr="fd03::/112"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="dynamic"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="fd03::/112",scope="dynamic"} 2
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/20"} 4090
kube_apiserver_clusterip_allocator_available_ips{cidr="fd03::/112"} 65533
# Fri May 13 09:18:22 JST 2022
# Fri May 13 09:19:22 JST 2022
# Fri May 13 09:20:22 JST 2022
# Fri May 13 09:21:22 JST 2022
# Fri May 13 09:22:22 JST 2022
```

#### Before fix
Before this fix, the metrics was incorrectly changed after a while (0 - 3 m).

```
# Fri May 13 08:55:40 JST 2022
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/20"} 4
kube_apiserver_clusterip_allocator_allocated_ips{cidr="fd03::/112"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="dynamic"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="fd03::/112",scope="dynamic"} 2
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/20"} 4090
kube_apiserver_clusterip_allocator_available_ips{cidr="fd03::/112"} 65533
# Fri May 13 08:56:40 JST 2022
1,2c1,2
< kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/20"} 4
< kube_apiserver_clusterip_allocator_allocated_ips{cidr="fd03::/112"} 2
---
> kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/20"} 0
> kube_apiserver_clusterip_allocator_allocated_ips{cidr="fd03::/112"} 0
4c4
< kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 2
---
> kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 6
6,7c6,8
< kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/20"} 4090
< kube_apiserver_clusterip_allocator_available_ips{cidr="fd03::/112"} 65533
---
> kube_apiserver_clusterip_allocator_allocation_total{cidr="fd03::/112",scope="static"} 2
> kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/20"} 4094
> kube_apiserver_clusterip_allocator_available_ips{cidr="fd03::/112"} 65535
# Fri May 13 08:57:40 JST 2022
# Fri May 13 08:58:40 JST 2022
# Fri May 13 08:59:40 JST 2022
4c4
< kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 6
---
> kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/20",scope="static"} 10
6c6
< kube_apiserver_clusterip_allocator_allocation_total{cidr="fd03::/112",scope="static"} 2
---
> kube_apiserver_clusterip_allocator_allocation_total{cidr="fd03::/112",scope="static"} 4
# Fri May 13 09:00:40 JST 2022
```

</details>

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug that the metrics for the cluster IP allocator are incorrectly reported.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tksm** [comment]
/assign @aojea
as the author of the original code

File: pkg/registry/core/service/ipallocator/allocator.go [hunk 1]
```diff
@@ -202,7 +206,7 @@ func (r *Range) allocate(ip net.IP, dryRun bool) error {
 	ok, offset := r.contains(ip)
 	if !ok {
 		// update metrics
-		clusterIPAllocationErrors.WithLabelValues(label.String(), "static").Inc()
+		r.metrics.incrementAllocationErrors(label.String(), "static")
 		return &ErrNotInRange{ip, r.net.String()}
 	}
 	if dryRun {
```
Comment (aojea) [inline pkg/registry/core/service/ipallocator/allocator.go:212]: I've just realized that we are incrementing the metrics without checking `dryRun`, 

cc: @thockin

File: pkg/registry/core/rest/storage_core.go [hunk 2]
```diff
@@ -213,6 +213,7 @@ func (c LegacyRESTStorageProvider) NewLegacyRESTStorage(apiResourceConfigSource
 	if err != nil {
 		return LegacyRESTStorage{}, genericapiserver.APIGroupInfo{}, fmt.Errorf("cannot create cluster IP allocator: %v", err)
 	}
+	serviceClusterIPAllocator.EnableMetrics()
 	restStorage.ServiceClusterIPAllocator = serviceClusterIPRegistry
```
Comment (aojea) [inline pkg/registry/core/rest/storage_core.go:217]: I have to remember how this ends in the repair loops

https://github.com/kubernetes/kubernetes/blob/9d85e18ec0dc09f681650d04d65e3db5237bef96/pkg/controlplane/controller.go#L174

Comment (aojea) [reply pkg/registry/core/rest/storage_core.go:217]: tracing

https://github.com/kubernetes/kubernetes/blob/9d85e18ec0dc09f681650d04d65e3db5237bef96/pkg/controlplane/instance.go#L522-L548

**Comment by aojea** [comment]
I still don't have clear what is the root cause , it seems that is an interaction with the repair loop confirmed by your changes, but the repair loops receive the registry allocator, no?

> ```
> $ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
> kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 2
> kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 2
> kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048572e+06
> ```
> But after a while with doing nothing, it incorrectly reports that allocation_ips is 0 and allocation_total is 4
> ```
> $ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
> kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 0
> kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 4
> ```

**Comment by wojtek-t** [comment]
xref https://github.com/kubernetes/kubernetes/pull/109975 - might potentially help with clearing the semantics

**Comment by aojea** [comment]
> @aojea Repair's `runOnce()` creates new IP Allocators ([#L171](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L170), [#L181](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L181)). I think these allocators overwrite the metrics at [#L231](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L231), [#L236](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L236) and [#L307](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L307)

IC, so I think that is this one that should not be able to update metrics

https://github.com/kubernetes/kubernetes/blob/4ce5a8954017644c5420bae81d72b09b735c21f0/pkg/registry/core/service/ipallocator/controller/repair.go#L181

File: pkg/registry/core/service/ipallocator/allocator.go [hunk 3]
```diff
@@ -116,10 +119,11 @@ func New(cidr *net.IPNet, allocatorFactory allocator.AllocatorWithOffsetFactory)
...
 	r := Range{
-		net:    cidr,
-		base:   base,
-		max:    maximum(0, int(max)),
-		family: family,
+		net:     cidr,
+		base:    base,
+		max:     maximum(0, int(max)),
+		family:  family,
+		metrics: &emptyMetricsRecorder{}, // disabled by default
```
Comment (aojea) [inline pkg/registry/core/service/ipallocator/allocator.go:126]: then, should we `registerMetrics()` in L96, or only when we enable the metrics?

File: pkg/registry/core/service/ipallocator/allocator_test.go [hunk 4]
```diff
@@ -434,10 +434,18 @@ func TestClusterIPMetrics(t *testing.T) {
...
 	cidrIPv6 := "2001:db8::/112"
 	_, clusterCIDRv6, _ := netutils.ParseCIDRSloppy(cidrIPv6)
 	b, err := NewInMemory(clusterCIDRv6)
+	b.EnableMetrics()
+	if err != nil {
+		t.Fatalf("unexpected error creating CidrSet: %v", err)
+	}
+	// create metrics disabled IPv4 allocator
+	// this metrics should be ignored
+	c, err := NewInMemory(clusterCIDRv4)
```
Comment (aojea) [inline pkg/registry/core/service/ipallocator/allocator_test.go:448]: can we move this to an individual test instead of overloading current test?
create a with metrics
create b without metrics
check b doesn't update a's metrics

File: pkg/registry/core/service/ipallocator/allocator.go [hunk 5]
```diff
@@ -86,6 +87,8 @@ type Range struct {
 	family api.IPFamily
 
 	alloc allocator.Interface
+	// metrics is a metrics recorder that can be disabled
+	metrics metricsRecorderInterface
```
Comment (aojea) [inline pkg/registry/core/service/ipallocator/allocator.go:91]: I like this solution and seems aligned with the rest of the code base, 
@thockin what do you think?

File: pkg/registry/core/service/ipallocator/allocator.go [hunk 6]
```diff
@@ -364,6 +368,11 @@ func (r *Range) Destroy() {
 	r.alloc.Destroy()
 }
 
+// EnableMetrics enables metrics recording.
+func (r *Range) EnableMetrics() {
+	r.metrics = &metricsRecorder{}
```
Comment (aojea) [inline pkg/registry/core/service/ipallocator/allocator.go:373]: should the metrics `registerMetrics()`  be initialized here  now?

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 1 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/allocator.go:212]: this PR seems to fix this too

**Comment by tksm** [comment]
@aojea  Thank you for your comment. Please take another look.

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 5 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/allocator.go:91]: @dgrisonnet (sig-instrumentation) I'd like your opinion too, the fact that metrics are global is :grimacing: ,  what do you think about this solution ?

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 1 above)
Comment (tksm) [reply pkg/registry/core/service/ipallocator/allocator.go:212]: Thanks. I made it do not increment when `dryRun` is true.

https://github.com/kubernetes/kubernetes/compare/f2f925a67f91f496e3875b8a8131f7eb243e352e..187af7781a4d6a308ea7f73dd22d435575873396#diff-3f7680212eb37166b66a0f052153bb765c0d4b141af958d5b92543dda628d35fR206

File: pkg/registry/core/service/ipallocator/allocator_test.go (hunk 4 above)
Comment (tksm) [reply pkg/registry/core/service/ipallocator/allocator_test.go]: I moved this to an individual test.

https://github.com/kubernetes/kubernetes/compare/f2f925a67f91f496e3875b8a8131f7eb243e352e..187af7781a4d6a308ea7f73dd22d435575873396#diff-3ab73f6c7915a3abe7f79d4b8fca55b7c8ee114cbefea86e5b6b849d6c649b12R601

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 3 above)
Comment (tksm) [reply pkg/registry/core/service/ipallocator/allocator.go:124]: Thank you. I moved it to in `EnableMetrics()`

https://github.com/kubernetes/kubernetes/compare/f2f925a67f91f496e3875b8a8131f7eb243e352e..187af7781a4d6a308ea7f73dd22d435575873396#diff-3f7680212eb37166b66a0f052153bb765c0d4b141af958d5b92543dda628d35fR373

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 6 above)
Comment (tksm) [reply pkg/registry/core/service/ipallocator/allocator.go:374]: Thank you. I fixed it.

https://github.com/kubernetes/kubernetes/compare/f2f925a67f91f496e3875b8a8131f7eb243e352e..187af7781a4d6a308ea7f73dd22d435575873396#diff-3f7680212eb37166b66a0f052153bb765c0d4b141af958d5b92543dda628d35fR373

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 5 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/allocator.go:91]: I think that current proposal is good enough, maybe is a TODO for sig-instrumentation to work on standardize this ;)

**Comment by aojea** [comment]
I'm fine with this
/approve

Defer lgtm to sig-instrumentation
and final approval to @thockin

File: pkg/registry/core/service/ipallocator/allocator.go (hunk 5 above)
Comment (dgrisonnet) [reply pkg/registry/core/service/ipallocator/allocator.go:91]: Yeah, it is good enough, we haven't standardized anything for now, so the implementation is up to the component owners.

That's a good point, I'll bring it to the group.

**Comment by thockin** [comment]
@dashpole do you accept LGTM responsibility?

/approve
