### PR TITLE
Fix the ceph deploy for e2e testing for ARM64

### LINKED ISSUE #101967: [arm64] several e2e storage testcases are failed due to the ceph is not ready
#### What happened:
When I run some e2e storage testcases locally, below testcases as an example, 

```
[sig-storage] In-tree Volumes [Driver: ceph][Feature:Volumes][Serial] [Testpattern: Pre-provisioned PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow][LinuxOnly]
```

I consistently saw the below error message, 

```FAIL: Failed to find "Ceph is ready" in pod logs: Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
    Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
      May 11 16:55:33.525: Failed to find "Ceph is ready" in pod logs: Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
          Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
```

#### What you expected to happen:
ceph should be deployed successfully and testcase should pass.

#### How to reproduce it (as minimally and precisely as possible):
Run the testcases mentioned above.

e.g.
```
/usr/bin/e2e.test -ginkgo.focus="In-tree Volumes \[Driver: ceph\]\[Feature:Volumes\]\[Serial\] \[Testpattern: Pre-provisioned PV \(default fs\)\] subPath should fail if subpath with backstepping is outside the volume \[Slow\]\[LinuxOnly\]"  -provider=local
```

#### Environment:
- Kubernetes version (use `kubectl version`): ALL
- Cloud provider or hardware configuration: ARM64
- OS (e.g: `cat /etc/os-release`): ubuntu18
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
- ceph deploy on ARM64 depends on "libec_jerasure_neon.so" which is not included
in `ceph-base` package in fedora26 distro, updated the distro to fedora33 to
fix the issue

```
sh ./mon.sh "$(hostname -i)"
/usr/lib64/ceph/erasure-code/libec_jerasure_neon.so: cannot open shared object file
```

- default pool `rbd` is not created on arm64, need to created this pool manually.

```
rbd import --image-feature layering block foo
rbd: error opening default pool 'rbd'
Ensure that the default pool has been created or specify an alternate pool name.
[root@4c05206b81c2 /]# ceph osd lspools  (nothing output inside the container)
```

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/101967

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/images/volume/rbd/bootstrap.sh [hunk 1]
```diff
@@ -41,6 +41,10 @@ sh ./mds.sh
 # Prepare a RBD volume "foo" (only with layering feature, the others may
 # require newer clients).
 # NOTE: we need Ceph kernel modules on the host that runs the client!
+# As the default pool `rbd` might not be created for a non-amd64 ceph deployment,
+# always create the `rbd` pool to make sure the `rbd import` workable.
+ceph osd pool create rbd 8
+rbd pool init rbd
```
Comment (BenTheElder) [inline test/images/volume/rbd/bootstrap.sh:47]: I'm not comfortable approving this change. please have someone from sig-storage review this.

Comment (chendave) [reply test/images/volume/rbd/bootstrap.sh:47]: sure, let me find some one from sig-storage.

**Comment by msau42** [comment]
/assign @jsafrane @humblec 
who are more familiar with ceph than I am

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews

File: test/images/volume/rbd/bootstrap.sh (hunk 1 above)
Comment (humblec) [reply test/images/volume/rbd/bootstrap.sh:47]: @chendave I would rather name the `pool` with a string with gives clue about the arch or something. Also, imo, its better to check the pool exist before creating one.

**Comment by humblec** [comment]
> /assign @jsafrane @humblec
> who are more familiar with ceph than I am

Sure, mostly look good , Have a comment here though. :+1:

File: test/images/volume/rbd/bootstrap.sh (hunk 1 above)
Comment (chendave) [reply test/images/volume/rbd/bootstrap.sh]: thanks @humblec for the suggestion! As we don't have many arch specific config so far, so just add a check there to make sure the `rbd` pools is created. WDYT?

**Review by humblec — APPROVED** [review]

**Comment by humblec** [comment]
Thanks @chendave ! it looks good ! 
/approve

**Comment by humblec** [comment]
@jsafrane ptal.. Thanks!

File: test/images/volume/rbd/bootstrap.sh (hunk 1 above)
Comment (humblec) [reply test/images/volume/rbd/bootstrap.sh]: Thanks. It should be enough for now, accordingly we can modularize in future. :+1:
