### PR TITLE
Fix websocket e2e tests for https endpoints

### LINKED ISSUE #73044: e2e: Websocket tests not working with HTTPS endpoint using public CA
**What happened**: When running e2e conformance tests against a `v1.13.2` cluster using a public HTTPS endpoint for the apiserver, you get the following errors:

```
• Failure [270.975 seconds]
[k8s.io] Pods
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:694
  should support retrieving logs from the container over websockets [NodeConformance] [Conformance] [It]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:699

  Jan 17 19:59:43.264: Failed to open websocket to ws://my-apiserver.example.com:80/api/v1/namespaces/e2e-tests-pods-z49g5/pods/pod-logs-websocket-cdc21ea5-1a91-11e9-9465-0242ac110002/log?container=main: websocket.Dial ws://my-apiserver.example.com:80/api/v1/namespaces/e2e-tests-pods-z49g5/pods/pod-logs-websocket-cdc21ea5-1a91-11e9-9465-0242ac110002/log?container=main: dial tcp 3.x.x.x:80: connect: connection timed out

  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/pods.go:598
------------------------------
Jan 17 19:59:43.470: INFO: Running AfterSuite actions on all nodes
```

**What you expected to happen**:

The API server endpoint is `https://my-apiserver.example.com` so the e2e tests should use `wss://` and connect on port `443` instead of `80`.

**How to reproduce it (as minimally and precisely as possible)**: Run e2e conformance tests against a cluster with the apiserver exposed on a public endpoint with a public CA.

**Anything else we need to know?**:

When looking at the code here: https://github.com/kubernetes/kubernetes/blob/5e86fa43f59f8ed4fd353ab17dc1e65708a9ae71/test/e2e/common/pods.go#L563-L618

It looks like the tlsConfig is not correctly derived from the URL. Diving into `framework.OpenWebSocketForURL` I see that this uses `TLSConfigFor` deep down:

https://github.com/kubernetes/kubernetes/blob/5e86fa43f59f8ed4fd353ab17dc1e65708a9ae71/staging/src/k8s.io/client-go/transport/transport.go#L53-L116

And this seem to return `nil` unless the kubeconfig has a CA or other explicit TLS config configured: https://github.com/kubernetes/kubernetes/blob/5e86fa43f59f8ed4fd353ab17dc1e65708a9ae71/staging/src/k8s.io/client-go/transport/transport.go#L56

I believe if this check also checked the `scheme` of the URL, then it would be correct: https://github.com/kubernetes/kubernetes/blob/5e86fa43f59f8ed4fd353ab17dc1e65708a9ae71/test/e2e/framework/util.go#L4399

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mikkeloscar**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When running e2e conformance tests against a public https protected
APIserver the websocket tests would fail because it fell back to using
`ws://` instead of `wss://` for the websocket connection.

This happened because the code detect if HTTPS is used only looks for
HTTPS related configuration in the kubeconfig, like a custom CA or
certificates.

The fix is to always use HTTPS when the apiserver URL has the scheme `https://`.

**Which issue(s) this PR fixes**:

Fixes #73044

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

### CODE REVIEW

**Comment by hjacobs** [comment]
LGTM

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -4396,7 +4396,7 @@ func OpenWebSocketForURL(url *url.URL, config *restclient.Config, protocols []st
 	if err != nil {
 		return nil, fmt.Errorf("failed to create tls config: %v", err)
 	}
-	if tlsConfig != nil {
+	if tlsConfig != nil || url.Scheme == "https" {
```
Comment (oomichi) [inline test/e2e/framework/util.go]: As you pointed on the issue report, tlsConfig: nil condition is like https://github.com/kubernetes/kubernetes/blob/5e86fa43f59f8ed4fd353ab17dc1e65708a9ae71/staging/src/k8s.io/client-go/transport/transport.go#L56
So doesn't your kubeconfig contain `certificate-authority-data: ...`, `insecure-skip-tls-verify: true` or the other related options?

**Review by oomichi — COMMENTED** [review]
just one question

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: No, my kubeconfig just looks like this:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://cluster-1.example.org
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    namespace: default
    user: <name>
  name: cluster-1
current-context: cluster-1
kind: Config
preferences: {}
users:
- name: <name>
  user:
    token: <token>
```

The server endpoint is an AWS ELB with a "real" certificate already trusted by most systems.

**Comment by mikkeloscar** [comment]
@oomichi I replied to your comment. Anything else needed, or is this good to go? :)

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: > The above kubeconfig seems that clients(kubectl, e2e) don't verify the api server, right?

They do verify it because they use the trusted CAs from the OS (because of how golang net HTTP client works). Setting `insecure-skip-tls-verify: true` would reduce the security for no reason other than to work around the fact that the e2e tests currently makes too strong assumptions about my Kubernetes setup. i.e. that the apiserver is served with a self-signed certificate.

Comment (oomichi) [reply test/e2e/framework/util.go]: Thanks for your explanation :-)
https://tools.ietf.org/html/rfc6455#section-3 says `The port component is OPTIONAL; the default for "ws" is port 80,
   while the default for "wss" is port 443.` So the schema "https" should be changed like this as line 4402.

**Review by oomichi — COMMENTED** [review]
/lgtm

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: I don't quite follow. Do you want me to remove the code for setting the default port? I can do it, but should it be done in this PR? It's not completely related to the fix I did IMO.

Comment (oomichi) [reply test/e2e/framework/util.go]: Sorry for mess comment. I just wanted to say this change seems good for me as the default port of wss. Then I did put `/lgtm`. It is fine to wait for another review for merging this without anything.

Comment (mikkeloscar) [reply test/e2e/framework/util.go]: Ok, thanks a lot for the review!

**Comment by cblecker** [comment]
I'm not sure on this one.

/cc @kubernetes/sig-auth-pr-reviews 
Would you mind having a look sig-auth?

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikedanese) [inline test/e2e/framework/util.go]: url.Scheme without the tlsConfig is probably sufficient.

File: test/e2e/framework/util.go [hunk 2]
```diff
@@ -4396,7 +4396,7 @@ func OpenWebSocketForURL(url *url.URL, config *restclient.Config, protocols []st
...
 		url.Scheme = "wss"
 		if !strings.Contains(url.Host, ":") {
```
Comment (mikedanese) [inline test/e2e/framework/util.go]: this should just be `if url.Port() == ""`

Comment (mikedanese) [reply test/e2e/framework/util.go]: Actually it's entirely unnecessary. https://github.com/kubernetes/kubernetes/blob/91d2bd3951f3a2e7290ef0cf5ec546ba228944d7/vendor/golang.org/x/net/websocket/client.go#L66-L78

Comment (mikkeloscar) [reply test/e2e/framework/util.go]: Do you want me to change it in this PR?

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: I will change it

File: test/e2e/framework/util.go (hunk 2 above)
Comment (mikedanese) [reply test/e2e/framework/util.go]: Sure, since you are already around might as well clean things up. Thanks!

**Comment by oomichi** [comment]
/lgtm cancel

@mikkeloscar Would you update this based on @mikedanese's comment?

File: test/e2e/framework/util.go (hunk 1 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: Changed!

File: test/e2e/framework/util.go (hunk 2 above)
Comment (mikkeloscar) [reply test/e2e/framework/util.go]: I removed it!

**Comment by mikkeloscar** [comment]
@oomichi done!
