### PR TITLE
kubeadm: skip integration tests if kubeadm-cmd-skip flag passed

### LINKED ISSUE #40155: TestCmdTokenGenerate assumes built binary
go test ./cmd/kubeadm/... fails with:

```
--- FAIL: TestCmdTokenGenerate (0.00s)
	token_test.go:40: 'kubeadm ex token generate' exited uncleanly: error running cluster/kubeadm.sh [ex token generate]; got error fork/exec cluster/kubeadm.sh: no such file or directory, stdout "", stderr ""
```

it appears to be following a "RunCmd" pattern used by e2e tests, but unit tests should not require built binaries

### PR DESCRIPTION
**Pull request by dmmcquay**
Will skip integration tests for token generation if it can't find a file by the given --kubeadm-path or default value.

**What this PR does / why we need it**: Tests would fail if just running `go test` in the dir because it expects to have more values. This won't change the behavior of `make test-cmd` which gets run here:
https://github.com/kubernetes/kubernetes/blob/master/Makefile#L258

**Which issue this PR fixes**: fixes #40155 

**Special notes for your reviewer**: /cc @pires @pipejakob @liggitt 

```release-note
NONE
```

### CODE REVIEW

File: cmd/kubeadm/test/token_test.go [hunk 1]
```diff
@@ -29,12 +29,20 @@ const (
 )
 
 var kubeadmPath string
+var testCmd = true
 
 func init() {
 	flag.StringVar(&kubeadmPath, "kubeadm-path", filepath.Join(os.Getenv("KUBE_ROOT"), "cluster/kubeadm.sh"), "Location of kubeadm")
+	if _, err := os.Stat(kubeadmPath); os.IsNotExist(err) {
```
Comment (liggitt) [inline cmd/kubeadm/test/token_test.go]: this really should not be in an init() block... make it a helper that each test calls. global flag registration also does not belong in an init() block of a test file, but that can be a separate issue

Comment (dmmcquay) [inline cmd/kubeadm/test/token_test.go]: I've seen this type of check happen in `init()` blocks before, especially when trying to test subprocesses:

https://speakerdeck.com/mitchellh/advanced-testing-with-go

Comment (dmmcquay) [inline cmd/kubeadm/test/token_test.go]: I can move the flag registration out of there, shouldn't be a problem.

File: cmd/kubeadm/test/token_test.go [hunk 2]
```diff
@@ -28,12 +28,11 @@ const (
 	TokenExpectedRegex = "^\\S{6}\\:\\S{16}\n$"
 )
 
-var kubeadmPath string
+var kubeadmPath = flag.String("kubeadm-path", filepath.Join(os.Getenv("KUBE_ROOT"), "cluster/kubeadm.sh"), "Location of kubeadm")
```
Comment (liggitt) [inline cmd/kubeadm/test/token_test.go]: sorry, the global package-level flag registration is the objection, not whether it's in or out of an init() block

Comment (dmmcquay) [inline cmd/kubeadm/test/token_test.go]: I'm confused, are you suggesting not to have a package level flag? And if so, only use env variable to find kubeadm binary or helper `.sh`?

Comment (liggitt) [inline cmd/kubeadm/test/token_test.go]: correct. as a rule, package-level unit tests should be self-contained, not depend on flags or external built binaries. 

exceptions live in our e2e and integration packages, not sprinkled through the cmd or pkg packages.

these two tests really seem like they should follow the test-cmd.sh pattern, building a binary and exercising invoking and testing the output via a shell script, rather than live as package unit tests

Comment (pipejakob) [inline cmd/kubeadm/test/token_test.go]: They follow the test-cmd.sh pattern in most ways except for the fact that the tests themselves are written in Go instead of bash. As Derek pointed out, there was a lot of discussion around exactly where these tests should live and how they should work during the initial PR, and we came to this consensus then.

Also, in general the project's direction seems to favor replacing bash with Go code, so I'd prefer to keep these in Go.

**Comment by dmmcquay** [comment]
@luxas Seems like the discussion has ended, want to take a look?

**Comment by dmmcquay** [comment]
@luxas ping

**Comment by luxas** [comment]
@liggitt do you like the idea of moving these tests to `test/integration/kubeadm` instead?

**Comment by liggitt** [comment]
> @liggitt do you like the idea of moving these tests to test/integration/kubeadm instead?

yes, things that depend on external binaries and don't follow normal package unit test conventions (e.g. work with `go test ./foo/bar` without additional setup) should be under test/integration or test/e2e

**Comment by luxas** [comment]
@dmmcquay There you go then. Both I and @liggitt are of the same opinion, please move this to a integration test package.

**Comment by dmmcquay** [comment]
@luxas @liggitt I moved the tests to test/integration/kubeadm . Also moved the bazel `BUILD` file, although I am not sure that is needed. 

Please advise.

**Comment by dmmcquay** [comment]
Looks like the bazel file was throwing it off. Removed for now.

**Comment by dmmcquay** [comment]
@k8s-bot unit test this

**Comment by dmmcquay** [comment]
@liggitt any ideas why this is failing unit/integration tests?

**Comment by dmmcquay** [comment]
@liggitt I figured out what the problem was, tests should pass now.

**Comment by dmmcquay** [comment]
@k8s-bot gci gce e2e test this

**Comment by dmmcquay** [comment]
@luxas it passes all the tests, just needs a LGTM from you.

**Comment by pires** [comment]
LGTM but please squash.

**Comment by dmmcquay** [comment]
@k8s-bot cvm gce e2e test this

File: test/integration/kubeadm/token_test.go [hunk 3]
```diff
@@ -22,20 +22,29 @@ import (
 	"path/filepath"
 	"regexp"
 	"testing"
+
+	_ "github.com/golang/glog"
```
Comment (luxas) [inline test/integration/kubeadm/token_test.go]: Why vendor this?

**Review by luxas — COMMENTED** [review]
I had expected this file to start with `// +build integration`, I think that build flag should be present.

I'm now starting to think if these fit even better in on e2e tests... Maybe we should move them there instead? @liggitt @ixdy what do you think?

I just couldn't find any other exec-based tests than under `test/e2e` when I started looking into it.

File: test/integration/kubeadm/token_test.go (hunk 3 above)
Comment (dmmcquay) [inline test/integration/kubeadm/token_test.go]: its required because of the flags that `make test-integration` pass to it. 

https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-integration.sh#L66

**Comment by dmmcquay** [comment]
@luxas I can add the build tag, that makes sense. My usage of Go build tags had been more OS specific, as I mentioned before, didn't know kubernetes had specific tags in place, which makes more sense.

**Comment by dmmcquay** [comment]
I also wanted to point out that a discussion around where these tests should live has already taken place here: https://github.com/kubernetes/kubernetes/pull/35144

**Comment by spxtr** [comment]
Note that if you run unit tests with bazel this isn't a problem, since the [BUILD](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/test/BUILD#L17-L28) file explicitly declares the dependency.

**Comment by luxas** [comment]
@spxtr See https://docs.google.com/document/d/1d-xUyYe4DMjyV1-xB6xqn6FTiryN2FXnKa4JF1jKozc/edit#heading=h.fnh0z4ayjjjn (written by @dmmcquay) where we're discussing the e2e/integration and overall testing strategy for kubeadm.

File: test/integration/kubeadm/util.go [hunk 4]
```diff
@@ -1,3 +1,5 @@
+// +build integration
```
Comment (mikedanese) [inline test/integration/kubeadm/util.go]: Generally I think we should discourage and stop using build tags like this. If we use build tags, we probably won't ever check that these tests actually compile.

**Comment by mikedanese** [comment]
I don't mind the move, but skipping integration tests if binary is not present seems like a really good way to never run the tests. We should explicitly skip the tests, or build the binary.

**Comment by dmmcquay** [comment]
@mikedanese thanks for taking a look. So if I got rid of the build tag and removed the skipping of the tests, you would approve of this move? 

Currently as this stands now, this test doesn't get run during `make test-integration`, but during `make test-cmd`. During `make test-integration` it gets skipped because it doesn't provide the `--kubeadm-path` flag ,where `make test-cmd` has the correct setup to do that.

**Comment by dmmcquay** [comment]
@k8s-bot unit test this

**Comment by pires** [comment]
Can you enable it on `make test-integration`?

**Comment by spxtr** [comment]
I actually kind of like the test where it is now. Its dependency on the binary is cleanly expressed in the bazel rule. I'd rather not mangle `test/integration` any more than it currently is mangled.

**Comment by liggitt** [comment]
> I actually kind of like the test where it is now. Its dependency on the binary is cleanly expressed in the bazel rule. I'd rather not mangle test/integration any more than it currently is mangled.

requiring a package to be compiled into an externally runnable binary in order to run package-level unit tests is... unexpected. apart from this test, standard go test commands (`go test ./cmd/kubeadm/...`) work perfectly

**Comment by spxtr** [comment]
I agree it would be nice for the go tool to know what to do, but at the same time I greatly prefer this:
```
go_test(
    args = ["--kubeadm-path=../kubeadm"],
    data = ["//cmd/kubeadm"],
    (...)
)
```
over the bash that will be required to do this the other way.

**Comment by luxas** [comment]
@spxtr Is it possible to make bazel first compile the binary before testing and then passing those args to the `_test.go` files in `cmd/kubeadm/test`? If that's possible, that'd be great of course!
I had no idea it was possible to do such things in bazel...

As mentioned above, in that case we're breaking the "normal" behaviour of the Go unit tests, but on the other hand I don't see any blocker to making `cmd/kubeadm/test` special **if we document it well enough.**

@spxtr Please join our sig call tomorrow, we're gonna discuss kubeadm testing: https://docs.google.com/document/d/1d-xUyYe4DMjyV1-xB6xqn6FTiryN2FXnKa4JF1jKozc/edit?usp=sharing

**Comment by spxtr** [comment]
> @spxtr Is it possible to make bazel first compile the binary before testing and then passing those args to the _test.go files in cmd/kubeadm/test? If that's possible, that'd be great of course!
> I had no idea it was possible to do such things in bazel...

The line `data = ["//cmd/kubeadm"]` states that this test requires the output of the `//cmd/kubeadm` rule as input to the test. Bazel's build language makes this sort of dependency explicit, so if you say `bazel test //cmd/kubeadm/test/...` then it will notice that you need to build the binary before running these tests.

It also handles caching properly so you don't need to rebuild every time :)

**Comment by dmmcquay** [comment]
@luxas This now contains the changes after debating in the SIG meeting today. PTAL so that https://github.com/kubernetes/kubernetes/pull/40045 can also be changed and merge in according to these changes.

**Comment by spxtr** [comment]
Change it to `args = ["--kubeadm-path=../../kubeadm"]` in the BUILD file.

**Comment by dmmcquay** [comment]
@luxas just needs your approval.

**Comment by dmmcquay** [comment]
@jbeda can I get your approval on this PR?
