### PR TITLE
Revert "proxy startup-time config handling cleanup"

### LINKED ISSUE #2868: kubeadm init CI failed since commit d8bdddcab42932
## What happened?
kubeadm init CI failed since commit d8bdddcab42932 https://github.com/kubernetes/kubernetes/commit/d8bdddcab4293284ce9f11b12f37fb827fc56f7c

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

### PR DESCRIPTION
**Pull request by pacoxu**
Reverts kubernetes/kubernetes#117297

Fixes https://github.com/kubernetes/kubeadm/issues/2868

Fix failure in https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest and several other ci failures.

The kube-proxy 
```
2023-04-29T04:50:47.850779535Z stderr F panic: runtime error: invalid memory address or nil pointer dereference
2023-04-29T04:50:47.850808505Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c659b0]
2023-04-29T04:50:47.850814857Z stderr F 
2023-04-29T04:50:47.850821558Z stderr F goroutine 132 [running]:
2023-04-29T04:50:47.850828198Z stderr F k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run(0xc00084ecb0)
2023-04-29T04:50:47.850835219Z stderr F 	cmd/kube-proxy/app/server.go:767 +0x1130
2023-04-29T04:50:47.850841683Z stderr F k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop.func1()
2023-04-29T04:50:47.850847097Z stderr F 	cmd/kube-proxy/app/server.go:326 +0x2b
2023-04-29T04:50:47.850852342Z stderr F created by k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop
2023-04-29T04:50:47.850858125Z stderr F 	cmd/kube-proxy/app/server.go:325 +0x70
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve

Let's revert instead of fix forward

File: cmd/kube-proxy/app/server_others.go [hunk 1]
```diff
@@ -92,6 +79,10 @@ func newProxyServer(
 	config *proxyconfigapi.KubeProxyConfiguration,
 	master string) (*ProxyServer, error) {
 
+	if config == nil {
```
Comment (aojea) [inline cmd/kube-proxy/app/server_others.go:82]: I think that confirms my bias towards keeping the extra validations, this could have detected the problem IIUIC the failures

Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:82]: Just the opposite; kubeadm CI was starting kube-proxy in an invalid way for who knows who long, and no one ever noticed because it just returned an error message that no one paid attention to

Comment (danwinship) [reply cmd/kube-proxy/app/server_others.go:82]: (actually, neither; that's not the line it's crashing on)

Comment (aojea) [reply cmd/kube-proxy/app/server_others.go:82]: I was trying to get a quick win, but most probably a red herring

Comment (aojea) [reply cmd/kube-proxy/app/server_others.go:82]: we don't know the reasons yet AFAIK, that was me trying to find an explanation
