### PR TITLE
Fix vSphere Cloud Provider to handle upgrade from k8s version less than v1.9.4 to v1.9.4+

### LINKED ISSUE #62435: Disks fail to detach when upgrading from 1.9.2 to 1.9.5
/kind bug

**What happened**:
With a 1 master+3 worker node cluster (1.9.2) and 3 pods with PVs, the controller-manager fails to detach these PVs from the nodes after draining and upgrading to 1.9.5. This causes the pod to hang in the "ContainerCreating" state.
```
  Warning  FailedMount            58s (x12 over 26m)  kubelet, 84495dab-9d26-49e1-9a5a-b34d36ce12be  Unable to mount volumes for pod "sample-statefulset-1_default(eb468d21-3ddb-11e8-89ea-0050568d2fa5)": timeout expired waiting for volumes to attach/mount for pod "default"/"sample-statefulset-1". list of unattached/unmounted volumes=[www]
  Warning  FailedMount            56s (x17 over 26m)  attachdetach-controller                        AttachVolume.Attach failed for volume "pvc-92b732f7-3dd3-11e8-b882-0050568d2fa5" : Failed to add disk 'scsi1:0'.
```

**What you expected to happen**:
The disk should be detached from the nodes and the pods should be restored to the running state. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster with k8s 1.9.2
1. Deploy a workload with persistent volumes, replicated across the cluster
1. Upgrade the cluster to k8s 1.9.5, by first upgrading the master node, then by upgrading the workers in the following order:
        - Drain the node (`kubectl drain <node>`)
        - upgrade node to k8s 1.9.5
        - uncordon the node

**Anything else we need to know?**:
This seems to be occuring because of the changes to the vsphere cloudprovider in 1.9.4, which causes the master node in 1.9.5 to be unable to recognize and identify the 1.9.2 nodes, resulting in the following logs:

```
I0323 13:21:54.954344    6021 reconciler.go:231] attacherDetacher.DetachVolume started for volume "nil" (UniqueName: "kubernetes.io/vsphere-volume/[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk") on node "21a524c0-7812-4f2f-a886-1e93b80e9881" 
I0323 13:21:54.959794    6021 operation_generator.go:1165] Verified volume is safe to detach for volume "nil" (UniqueName: "kubernetes.io/vsphere-volume/[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk") on node "21a524c0-7812-4f2f-a886-1e93b80e9881" 
E0323 13:21:54.968942    6021 datacenter.go:78] Unable to find VM by UUID. VM UUID: 21a524c0-7812-4f2f-a886-1e93b80e9881
E0323 13:21:54.968960    6021 nodemanager.go:275] Error "No VM found" node info for node "21a524c0-7812-4f2f-a886-1e93b80e9881" not found
E0323 13:21:54.968970    6021 vsphere.go:475] Cannot find node "21a524c0-7812-4f2f-a886-1e93b80e9881" in cache. Node not found!!!
E0323 13:21:54.968980    6021 attacher.go:260] Error checking if volume ("[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk") is already attached to current node ("21a524c0-7812-4f2f-a886-1e93b80e9881"). Will continue and try detach anyway. err=No VM found
E0323 13:21:54.976573    6021 datacenter.go:78] Unable to find VM by UUID. VM UUID: 21a524c0-7812-4f2f-a886-1e93b80e9881
E0323 13:21:54.976589    6021 nodemanager.go:275] Error "No VM found" node info for node "21a524c0-7812-4f2f-a886-1e93b80e9881" not found
E0323 13:21:54.976597    6021 vsphere.go:475] Cannot find node "21a524c0-7812-4f2f-a886-1e93b80e9881" in cache. Node not found!!!
E0323 13:21:54.976607    6021 attacher.go:274] Error detaching volume "[***] kubevols/kubernetes-dynamic-pvc-7ece5266-2e9a-11e8-b4d2-005056b91f7a.vmdk": No VM found
```

Restarting the kube-controller-manager also causes it to hang in a state where it continuously attempts to try and mount the pvc, flooding the logs in kubelet and also in vcenter:
```
I0406 03:22:49.954013   22290 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-e517c716-3946-11e8-9efa-005056b9781f" (UniqueName: "kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk") pod "sample-storage-95d4b8495-mkx9w" (UID: "b95d83dd-3949-11e8-b2d4-005056b9781f") 

E0406 03:23:15.765047   22290 nestedpendingoperations.go:263] Operation for "\"kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk\"" failed. No retries permitted until 2018-04-06 03:23:16.264995909 +0000 UTC m=+98.801076882 (durationBeforeRetry 500ms). Error: "Volume not attached according to node status for volume \"pvc-e517c716-3946-11e8-9efa-005056b9781f\" (UniqueName: \"kubernetes.io/vsphere-volume/[vnx5600-pizza-2] kubevols/kubernetes-dynamic-pvc-e517c716-3946-11e8-9efa-005056b9781f.vmdk\") pod \"sample-storage-95d4b8495-mkx9w\" (UID: \"b95d83dd-3949-11e8-b2d4-005056b9781f\") "

```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.5
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from /etc/os-release): ubuntu 14.04.5 LTS
- Kernel (e.g. `uname -a`): 4.4.0-116-generic
- Install tools: CFCR/PKS
- Others:
/sig vmware

### PR DESCRIPTION
**Pull request by abrarshivani**
**What this PR does / why we need it**:
vSphere Cloud Provider in kubernetes master v1.9.4+ is not able to identify the kubernetes nodes of version less than 1.9.4. Hence, volume operations fail in this case. This PR fixes this.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62435

**Special notes for your reviewer**:
Internally reviewed here: https://github.com/vmware/kubernetes/pull/477

**Release note**:

```release-note
Fix in vSphere Cloud Provider to handle upgrades from kubernetes version less than v1.9.4 to v1.9.4 and above.
```

### CODE REVIEW

**Comment by abrarshivani** [comment]
//cc @kubernetes/vmware

**Review by divyenpatel — APPROVED** [review]
/lgtm

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go [hunk 1]
```diff
@@ -542,3 +548,32 @@ func GetVMUUID() (string, error) {
 func GetUUIDFromProviderID(providerID string) string {
 	return strings.TrimPrefix(providerID, ProviderPrefix)
 }
+
+func IsUUIDSupportedNode(node *v1.Node) (bool, error) {
+	newVersion, err := version.ParseSemantic("v1.9.4")
```
Comment (gnufied) [inline pkg/cloudprovider/providers/vsphere/vsphere_util.go]: @divyenpatel @abrarshivani This change seems problematic, could we have not done this in a different way? Such as if - we can't find node using `ProviderID` then we could use `SystemUUID`? Some kubernetes distributions such as Openshift do not necessarily match kubernetes versioning schemes and hence the fix will not work for them.

Comment (divyenpatel) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: @gnufied in that case `IsUUIDSupportedNode()` is throwing error?
If that is the case, then we need to correct `func GetNodeUUID(node *v1.Node) (string, error)` function.

Comment (gnufied) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: @divyenpatel no `IsUUIDSupportedNode` will always return `true` in Kubernetes distributions which do not necessarily track kube's version naming. Basically - openshift-3.9 == kube-1.9 but after initial release openshift does not follow release pattern of kubernetes and hence openshift-3.9.40 will still report kube-1.9.0..
