### PR TITLE
fix hack/update-vendor-licenses.sh on macOS

### LINKED ISSUE #79315: hack/updated-vendor-licenses.sh strips all hashes on macOS
**What happened**: run `hack/update-vendor-licenses.sh` on macOS, all md5 hashes will be stripped from the output and the script will not fail or warn.

**What you expected to happen**: The script should work or detect this issue and fail. Currently it silently ignores `md5sum` not existing on the host. 

We have some warning logic, but solely based on bash version, if the user upgraded their bash installation but did not install md5sum we don't warn them.

**How to reproduce it (as minimally and precisely as possible)**: run the script

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig testing
/priority important-longterm
/assign

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: fixes `hack/update-vendor-licenses.sh` on macOS

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/79315

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: hack/lib/util.sh [hunk 1]
```diff
@@ -702,6 +702,15 @@ function kube::util::require-jq {
   fi
 }
 
+# outputs md5 hash of $1, works on macOS and Linux
+function kube::util::md5() {
```
Comment (BenTheElder) [inline hack/lib/util.sh]: this is a 1:1 copy of `kube::release:md5`, it's such a trivial method that it didn't seem particularly worth deduping even, but we don't want to source the whole release machinery in update-vendor-licenses.sh

Comment (BenTheElder) [reply hack/lib/util.sh]: (see `build/lib/release.sh`)

I can't find any consumers of `kube::release::md5` but I'm wary of potentially breaking some script elsewhere (k/release??) and removing it would be a somewhat orthogonal change.

**Comment by cblecker** [comment]
retroactive lgtm
