### PR TITLE
mark es logging test as Feature

### LINKED ISSUE #17873: e2e flake: Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch
It failed in gce suite. I honestly have no idea under which team it falls: @bgrant0607 @thockin @ixdy @wojtek-t.

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/es_cluster_logging.go:46 Nov 27 02:50:59.145: Failed to find all 300 log lines
```

### PR DESCRIPTION
**Pull request by freehan**
closes: #17873

Will add a test for gcp logging

### CODE REVIEW

File: hack/jenkins/e2e.sh [hunk 1]
```diff
@@ -412,6 +412,17 @@ case ${JOB_NAME} in
     : ${PROJECT:="kubernetes-jenkins"}
     ;;
 
+  # Runs only the elasticsearch logging tests on GCE.
+  kubernetes-e2e-gce-es-logging)
```
Comment (ihmccreery) [inline hack/jenkins/e2e.sh]: You also need to add a config in hack/jenkins/job-configs/kubernetes-e2e.yaml

File: hack/jenkins/e2e.sh [hunk 2]
```diff
@@ -412,6 +412,17 @@ case ${JOB_NAME} in
...
+    : ${E2E_CLUSTER_NAME:="jenkins-gce-e2e-es-logging"}
+    : ${E2E_NETWORK:="e2e-es-logging"}
+    : ${GINKGO_TEST_ARGS:="--ginkgo.focus=\[Feature:Elasticsearch\]"}
+    : ${KUBE_GCE_INSTANCE_PREFIX:="e2e-es-logging"}
+    : ${PROJECT:="kubernetes-jenkins"}
```
Comment (ihmccreery) [inline hack/jenkins/e2e.sh]: Please create a new project for this; talk with me offline if you don't know how.

**Comment by freehan** [comment]
Project `kubernetes-es-logging` created
https://pantheon.corp.google.com/home/dashboard?project=kubernetes-es-logging

File: test/e2e/es_cluster_logging.go [hunk 3]
```diff
@@ -39,6 +38,12 @@ var _ = Describe("Cluster level logging using Elasticsearch [Flaky]", func() {
 		// on GCE. Once we are sure that Elasticsearch cluster level logging
 		// works for other providers we should widen this scope of this test.
 		SkipUnlessProviderIs("gce")
+
+		options := api.ListOptions{LabelSelector: labels.Set{k8sAppKey: esValue}.AsSelector()}
+		rc, err := f.Client.ReplicationControllers(api.NamespaceSystem).List(options)
+		if err != nil || len(rc.Items) <= 0 {
+			Skipf("Elasticsearch rc not found. To continue the test, please enable ES addon by setting [KUBE_LOGGING_DESTINATION=elasticsearch] ")
```
Comment (ihmccreery) [inline test/e2e/es_cluster_logging.go]: I don't feel great about ~silently skipping this.  Since this is [Feature:Elasticsearch], can we not check, and fail if someone tries to run it in a cluster that doesn't have ES?

**Comment by freehan** [comment]
Can I get a lgtm?

**Comment by freehan** [comment]
@k8s-bot unit test this

**Comment by freehan** [comment]
@ihmccreery 
It looks like somehow jenkins is not setting PROJECT and causing failure. 
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-es-logging/15/console

Did I miss anything?

**Comment by ihmccreery** [comment]
You caught us at a bad time, and your PR went in after we did a major refactoring of `e2e.sh`, and the syntax you used won't work anymore for a variety of reasons.  @spxtr should be able to pick up your job in #21524, which should land today.  Sorry about the churn!

**Comment by freehan** [comment]
I see. Thanks!
