### PR TITLE
Fix panic when kubelet register if a node object already exists with no Status.Capacity or Status.Allocatable

### LINKED ISSUE #95188: Kubelet register fail if a node object already exists with no "Status.Capacity"
**What happened**:

Kubelet not able to register on ApiServer if a node object already exists and has no "capacity" in "status"

```
kubelet[15418]: E0930 14:11:27.149098   15418 runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
kubelet[15418]: goroutine 315 [running]:
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3d4f200, 0x4b33420)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa6
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
kubelet[15418]: panic(0x3d4f200, 0x4b33420)
kubelet[15418]: /usr/local/go/src/runtime/panic.go:969 +0x175
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).reconcileHugePageResource(0xc000016a80, 0xc000024900, 0xc000bfa000, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:146 +0x47b
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).tryRegisterWithAPIServer(0xc000016a80, 0xc000024900, 0x0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:116 +0x48b
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).registerWithAPIServer(0xc000016a80)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:71 +0x205
kubelet[15418]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncNodeStatus(0xc000016a80)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:426 +0x14d
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000ff9120)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000ff9120, 0x4becee0, 0xc000d015f0, 0x1, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ff9120, 0x2540be400, 0x0, 0x1, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kubelet[15418]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000ff9120, 0x2540be400, 0xc0000b60c0)
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
kubelet[15418]: created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
kubelet[15418]: /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1337 +0x397
```

**What you expected to happen**:

Kubelet well registered, even if the node already exists and do not have any "status.capacity" filled.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a simple cluster `kubeadm init`
- Stop kubelet
- Delete node object `kubectl delete node <node_name>`
- Create manually the node 
```
# cat node.yaml 
kind: Node
apiVersion: v1
metadata:
  name: <node_name>
# kubectl apply -f node.yaml
```
- Start kubelet again
- Panic !

(Another approach, you want to extend your cluster and you create the node object before deploying/starting kubelet on the new node then the new kubelet node will not be able to register and get this Panic)

**Anything else we need to know?**:

After some investigation, it seems the `reconcileHugePageResource` function rely on the fact that "Status.Capacity" is a non-nil map, which could not be the case.
I would just add an "if" to initialize the "Capacity" map if this one is nil.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
```
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:38:53Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix panic when kubelet register if a node object already exists with no Status.Capacity or Status.Allocatable

**Which issue(s) this PR fixes**:

Fixes #95188

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix the panic when kubelet registers if a node object already exists with no Status.Capacity or Status.Allocatable
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
/lgtm
/retest

This should have a proper changelog entry, and should be backported to previous releases.
/hold

File: pkg/kubelet/kubelet_node_status.go [hunk 1]
```diff
@@ -129,6 +129,24 @@ func (kl *Kubelet) reconcileHugePageResource(initialNode, existingNode *v1.Node)
 	requiresUpdate := false
 	supportedHugePageResources := sets.String{}
 
+	if existingNode.Status.Capacity == nil {
```
Comment (NicolasT) [inline pkg/kubelet/kubelet_node_status.go:132]: Could consider factoring out this code (and the block below) which would allow for some extra unit-tests.

Comment (SataQiu) [reply pkg/kubelet/kubelet_node_status.go:132]: Thank you for your review @NicolasT . Is there any more detailed reconstruction plan?

Comment (NicolasT) [reply pkg/kubelet/kubelet_node_status.go:132]: Not sure I understand the question? You basically have two (+-) 12-line code blocks that are roughly the same, parametrized over two `Node` objects, 'returning' (so to say) some `bool`. Sounds like a good opportunity to turn that functionality into a function which then you call twice, and for which some unit-test(s) can be written.

Comment (SataQiu) [reply pkg/kubelet/kubelet_node_status.go:132]: Sounds good!

Comment (SataQiu) [reply pkg/kubelet/kubelet_node_status.go]: Done!

**Review by NicolasT — APPROVED** [review]

**Review by TeddyAndrieux — APPROVED** [review]

**Comment by SataQiu** [comment]
Sorry, but I'm not sure who should be assigned, it's been waiting for some time. 
/assign @thockin

**Comment by thockin** [comment]
@odinuge put a hold on this asking for a relnote and backports.  I am not sure about relnote but backports maybe.

Are we ok to remove the hold?

**Comment by odinuge** [comment]
Hey @thockin!

I am ok with merging this no relnote. Tho., in my experience the patch release managers prefer to have relnotes when backporting, so to actually show what changes (and therefore it is nice to have it here as well).

/lgtm

**Comment by thockin** [comment]
This seems OK to me, but I really don't know this area well.  @dchen1107 or @bobbypage or @sjenning Can you shake loose 5 minutes to look at this?

**Comment by SataQiu** [comment]
> Hey @thockin!
> 
> I am ok with merging this no relnote, so feel free to unhold. Tho., in my experience the patch release managers prefer to have relnotes when backporting, to actually show what changes (and therefore it is nice to have it here as well).
> 
> /lgtm

@odinuge Thanks for your reminding. I have added a release note. If you have a better one, please feel free to feedback.

**Comment by odinuge** [comment]
Nice @SataQiu!

/hold cancel

File: pkg/kubelet/kubelet_node_status_test.go [hunk 2]
```diff
@@ -1700,6 +1707,216 @@ func TestUpdateDefaultLabels(t *testing.T) {
...
+func TestUpdateDefaultResources(t *testing.T) {
+	cases := []struct {
+		name         string
+		initialNode  *v1.Node
+		existingNode *v1.Node
+		expectedNode *v1.Node
+		needsUpdate  bool
+	}{
+		{
+			name: "no update needed when capacity and available of the existing node are not nil",
```
Comment (bobbypage) [inline pkg/kubelet/kubelet_node_status_test.go:1719]: nit s/available/allocatable

**Comment by bobbypage** [comment]
/lgtm 

Thanks for the fix! Have you thought about also proposing cherrypicking this to 1.19?

**Comment by NicolasT** [comment]
Such backport would be appreciated: next to our original report, where we discovered the issue in 1.19 (essentially making 1.19 incompatible with our deployment mechanism), there appears to be more interest (https://github.com/kubernetes/kubernetes/issues/95188#issuecomment-713042578).

File: pkg/kubelet/kubelet_node_status_test.go (hunk 2 above)
Comment (SataQiu) [reply pkg/kubelet/kubelet_node_status_test.go]: Thanks a lot @bobbypage ! The nit has been fixed.

**Comment by SataQiu** [comment]
> Such backport would be appreciated: next to our original report, where we discovered the issue in 1.19 (essentially making 1.19 incompatible with our deployment mechanism), there appears to be more interest ([#95188 (comment)](https://github.com/kubernetes/kubernetes/issues/95188#issuecomment-713042578)).

A PR for release-1.19 has been filed.

**Comment by NicolasT** [comment]
> > Such backport would be appreciated: next to our original report, where we discovered the issue in 1.19 (essentially making 1.19 incompatible with our deployment mechanism), there appears to be more interest ([#95188 (comment)](https://github.com/kubernetes/kubernetes/issues/95188#issuecomment-713042578)).
> 
> A PR for release-1.19 has been filed. (#96297)

Much appreciated, thanks. Hope this lands soon :smiley:
