### PR TITLE
Fix ServiceIPStaticSubrange assigns duplicate IP addresses

### LINKED ISSUE #109927: The `ServiceIPStaticSubrange` assigns duplicate IP addresses when the dynamic block is exhausted
### What happened?

In a `ServiceIPStaticSubrange` enabled cluster, Kubernetes assigns duplicate IP addresses when the dynamic block is exhausted.

```
$ kubectl get svc --all-namespaces | grep "10.96.0.1 " | head
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  152m
default       svc47        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc48        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc49        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc50        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc51        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc52        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc53        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc54        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc55        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
```

### What did you expect to happen?

I expected all clusterIPs are uniquely assigned.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a `ServiceIPStaticSubrang` enabled Kubernetes v1.24 cluster with a small service-cluster-ip-range. I confirmed on the minikube with the following command.

```
minikube start \
  --kubernetes-version v1.24.0 \
  --extra-config=apiserver.service-cluster-ip-range=10.96.0.0/26 \
  --feature-gates=ServiceIPStaticSubrange=true
```

2. Create services until the dynamic block is exhausted.

```
# create a dummy pod
kubectl create deploy nginx --image nginx --port 80

# create 100 services
for I in $(seq 1 100); do
  kubectl expose --name "svc$I" deploy/nginx --port 80
done
```

3. We see some clusterIPs are duplicated.

```
kubectl get svc --all-namespaces | awk '{print $4;}' | sort | uniq -c | sort -nr | head -3
  16 10.96.0.1
   1 CLUSTER-IP
   1 10.96.0.62
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube v1.25.2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tksm**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix ServiceIPStaticSubrange assigns duplicate IP addresses when the dynamic block is exhausted.

#### Which issue(s) this PR fixes:

Fixes #109927

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug that a ServiceIPStaticSubrange enabled cluster assigns duplicate IP addresses when the dynamic block is exhausted.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tksm** [comment]
/assign aojea
as the author of [KEP-3070](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3070-reserved-service-ip-range)

File: pkg/registry/core/service/allocator/bitmap_test.go [hunk 1]
```diff
@@ -541,3 +541,23 @@ func TestPreAllocateReservedFull_BitmapReserved(t *testing.T) {
...
+	uniqueAllocated := map[int]bool{}
+	m := NewAllocationMapWithOffset(max, "test", dynamicOffset)
+
+	// Allocate all the values in both the dynamic and reserved blocks
+	for i := 0; i < max; i++ {
+		alloc, ok, _ := m.AllocateNext()
+		if !ok {
+			t.Fatalf("unexpected error")
+		}
+		uniqueAllocated[alloc] = true
```
Comment (aojea) [inline pkg/registry/core/service/allocator/bitmap_test.go:557]:
```suggestion
		if _, ok := uniqueAllocated[alloc] ; ok {
		           t.Fatalf("unexpected allocated value %d", alloc)
		}  else {
		          uniqueAllocated[alloc] = true
		}
```

**Comment by aojea** [comment]
/sig network
just one change on the test and it lgtm
Thank you very  much

File: pkg/registry/core/service/allocator/bitmap_test.go (hunk 1 above)
Comment (tksm) [reply pkg/registry/core/service/allocator/bitmap_test.go]: Thank you. I fixed it.

**Comment by wojtek-t** [comment]
Good catch!

/lgtm
/approve

**Comment by aojea** [comment]
the ipv6 job failed with 
```
error:
exit status 1
Output: 
May 10 09:47:58.016: INFO: Unable to reach the following endpoints of service fd00:10:96::273b: map[service-proxy-toggled-4rcz5:{} service-proxy-toggled-xs5dk:{} service-proxy-toggled-zmg9r:{}]
May 10 09:48:03.017: INFO: Executing cmd "for i in $(seq 1 150); do wget -q -O - -T 1 http://[fd00:10:96::273b]:80 2>&1 || true; echo; done" in pod services-7707/verify-service-up-host-exec-pod
May 10 09:48:03.017: INFO: Running '/home/prow/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://[::1]:39843 --kubeconfig=/root/.kube/kind-test-config --namespace=services-7707 exec verify-service-up-host-exec-pod -- /bin/sh -x -c for i in $(seq 1 150); do wget -q -O - -T 1 http://[fd00:10:96::273b]:80 2>&1 || true; echo; done'
May 10 09:48:03.113: INFO: rc: 1
May 10 09:48:03.113: INFO: error while kubectl execing "for i in $(seq 1 150); do wget -q -O - -T 1 http://[fd00:10:96::273b]:80 2>&1 || true; echo; done" in pod services-7707/verify-service-up-host-exec-pod: error running /home/prow/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://[::1]:39843 --kubeconfig=/root/.kube/kind-test-config --namespace=services-7707 exec verify-service-up-host-exec-pod -- /bin/sh -x -c for i in $(seq 1 150); do wget -q -O - -T 1 http://[fd00:10:96::273b]:80 2>&1 || true; echo; done:
Command stdout:

stderr:
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "3f9abfaad817efeac8344c4deda535f0fece0aa69382a526269bf25703bc8797": OCI runtime exec failed: exec failed: unable to start container process: error adding pid 146532 to cgroups: failed to write 146532: open /sys/fs/cgroup/unified/kubelet/kubepods/besteffort/pod31c6ed8a-40e5-4052-9b26-6456002988ab/b418128f0010af0fe6cb16cd9301ddc94597648d1008099dfbd13e627c906f73/cgroup.procs: no such file or directory: unknown
```
