### PR TITLE
Skip cronjob e2e test for adoption of jobs without ControllerRef

### LINKED ISSUE #52571: [upgrade test failure] CronJob should adopt Jobs it owns that don't have ControllerRef yet
https://k8s-testgrid.appspot.com/master-upgrade#gce-1.7-master-upgrade-cluster-parallel

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/567#k8sio-cronjob-should-adopt-jobs-it-owns-that-dont-have-controllerref-yet

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cronjob.go:327
wait for Job "adopt-1505507760" to be readopted
Expected success, but got an error:
    <*errors.errorString | 0xc4202b31c0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cronjob.go:322
```

/kind upgrade-test-failure

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/sig-apps-test-failures 

Assigning to the 1.8 milestone. Since we're late in the release cycle, we need to determine if this is a release blocker or not.

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
This PR adds the logic to skip cronjob e2e test for adoption of jobs without ControllerRef when testing against v1.8 cluster.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52571 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by crimsonfaith91** [comment]
/test all
The tests are very slow, so re-run them.

File: test/e2e/cronjob.go [hunk 1]
```diff
@@ -46,9 +46,10 @@ const (
 )
 
 var (
-	CronJobGroupVersionResource      = schema.GroupVersionResource{Group: batchv2alpha1.GroupName, Version: "v2alpha1", Resource: "cronjobs"}
-	ScheduledJobGroupVersionResource = schema.GroupVersionResource{Group: batchv2alpha1.GroupName, Version: "v2alpha1", Resource: "scheduledjobs"}
-	removedScheduledJobsVersion      = utilversion.MustParseSemantic("v1.8.0")
+	CronJobGroupVersionResource                = schema.GroupVersionResource{Group: batchv2alpha1.GroupName, Version: "v2alpha1", Resource: "cronjobs"}
+	ScheduledJobGroupVersionResource           = schema.GroupVersionResource{Group: batchv2alpha1.GroupName, Version: "v2alpha1", Resource: "scheduledjobs"}
+	removedScheduledJobsVersion                = utilversion.MustParseSemantic("v1.8.0")
```
Comment (crimsonfaith91) [inline test/e2e/cronjob.go]: Perhaps we can combine both `removedScheduledJobsVersion` and `skippedAdoptionWithoutControllerRefVersion`.

**Comment by crimsonfaith91** [comment]
@ericchiang It may be due to I targeted `master` branch before changing it to `release-1.7`. It should be fine as long as the codes target `release-1.7`.

**Comment by crimsonfaith91** [comment]
/test all
Is there a reason for the tests to take so long to start running?

**Comment by apelisse** [comment]
Shouldn't this be going on master? @crimsonfaith91

**Comment by crimsonfaith91** [comment]
@apelisse Thanks for retesting the PR!
