### PR TITLE
Do not replace labels of pvc with those of StastefulSet

### LINKED ISSUE #74916: StatefulSet's PersistentVolumeClaims have incorrect labels
**What happened**:  
When creating a StatefulSet that uses volumeClaimTemplates, the resulting PersistentVolumeClaims have incorrect labels.  Instead of using the labels defined in their metadata, they use the labels from the StatefulSet's selector.

**What you expected to happen**:
I expect the created PersistentVolumeClaims to have the labels defined in their metadata.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: v1
kind: Service
metadata:
  name: bugdemo-service
  labels:
    app: bugdemo-service
    extraLabel: fromService
spec:
  ports:
    - name: nginx
      targetPort: 80
      port: 80
  clusterIP: None
  selector:
    app: bugdemo-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bugdemo-statefulset
  labels:
    app: bugdemo-statefulset
    extraLabel: fromStatefulSet
spec:
  selector:
    matchLabels:
      app: bugdemo-pod
  serviceName: bugdemo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bugdemo-pod
        extraLabel: fromPodTemplate
    spec:
      containers:
      - name: bugdemo-nginx
        image: nginx:stable
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-data
            mountPath: /var/log/dummy
  volumeClaimTemplates:
    - metadata:
        name: nginx-data
        # In the resulting PersistentVolumeClaim, these
        # labels are replaced with the StatefulSet's selector
        labels:
          app: bugdemo-volumeclaim
          extraLabel: fromVolumeClaimTemplate
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: "1Gi"
```

Resulting PersistentVolumeClaim:

```
$ kubectl get pvc --show-labels
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   LABELS
nginx-data-bugdemo-statefulset-0   Bound    pvc-7917ee4f-3ec7-11e9-917f-42010aXXXXXX   1Gi        RWO            standard       1m    app=bugdemo-pod
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.4", GitCommit:"618716cbb236fb7ca9cabd822b5947e298ad09f7", GitTreeState:"clean", BuildDate:"2019-02-05T19:22:29Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GKE
- Install tools: `kubectl`
- Others:

@kubernetes/sig-apps-apps . 
/sig apps

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
Currently labels of pvc are replaced by those of StatefulSet when using claimTemple in StatefulSet if 

**Which issue(s) this PR fixes**:

Fixes #74916 
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by Pingan2017 — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by cwdsuzhou** [comment]
@kubernetes/sig-app-pr-reviews

**Comment by cwdsuzhou** [comment]
@enisoc hi, would you please help review the codes

**Comment by cwdsuzhou** [comment]
Could you please help review the codes

**Comment by cwdsuzhou** [comment]
@oomichi @liggitt  would you please help review the codes

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 1]
```diff
@@ -149,7 +149,6 @@ func getPersistentVolumeClaims(set *apps.StatefulSet, pod *v1.Pod) map[string]v1
 		claim := templates[i]
 		claim.Name = getPersistentVolumeClaimName(set, &claim, ordinal)
 		claim.Namespace = set.Namespace
-		claim.Labels = set.Spec.Selector.MatchLabels
```
Comment (oomichi) [inline pkg/controller/statefulset/stateful_set_utils.go]: This line has come since https://github.com/kubernetes/kubernetes/pull/40838/files#diff-2ad3f4a4088a7249756d1b81af193493R147 which was a huge change of refactoring.
On review history, there was not comment related to this code. And the above explanation of this method(line 141-143) just mentions the name of claim, not the label.
I'm still not sure this code is intentional or not.. I hope the specialists can help this.

Comment (cwdsuzhou) [reply pkg/controller/statefulset/stateful_set_utils.go]: @oomichi Thank you for your review. Currently, I have not found the labels of pvc used in anywhere of statefuleSets. To ensure the result intentional, I would also invite the author of these code to review it @kow3ns

**Comment by cwdsuzhou** [comment]
@kow3ns hi, would please review the codes since you are the submitter of codes, thank you very much!

File: pkg/controller/statefulset/stateful_set_utils.go (hunk 1 above)
Comment (kow3ns) [reply pkg/controller/statefulset/stateful_set_utils.go]: This code is intentional to allow the statefulset to find the PVCs it creates.

**Review by kow3ns — CHANGES_REQUESTED** [review]

**Comment by kow3ns** [comment]
This changes the behavior of the controller in a backward incompatible way. We can't accept this on a v1 API. Adding additional labels (along with those generated from the StatefulSet Selector) might be a reasonable approach that wouldn't break anyone.

**Comment by cwdsuzhou** [comment]
> This changes the behavior of the controller in a backward incompatible way. We can't accept this on a v1 API. Adding additional labels (along with those generated from the StatefulSet Selector) might be a reasonable approach that wouldn't break anyone.

@kow3ns Thank you for your advice, I have done that, it is more reasonable. When pvc labels are conflict with the statefulSet labels, they would be replaced with the statefulSet labels in order to not break anyone.

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 2]
```diff
@@ -149,7 +149,15 @@ func getPersistentVolumeClaims(set *apps.StatefulSet, pod *v1.Pod) map[string]v1
...
+		if claim.Labels != nil {
+			for key, value := range set.Spec.Selector.MatchLabels {
+				if claim.Labels != nil {
```
Comment (liggitt) [inline pkg/controller/statefulset/stateful_set_utils.go]: no need to check for non-nil again, line 152 already checked this

**Comment by liggitt** [comment]
this needs tests for the following cases:

* nil inherits statefulset labels
* non-nil, empty inherits statefulset labels
* non-nil with non-overlapping labels merge pvc and statefulset labels
* non-nil with overlapping labels merge pvc and statefulset labels and prefer statefulset labels

**Comment by cwdsuzhou** [comment]
> this needs tests for the following cases:
> 
> * nil inherits statefulset labels
> * non-nil, empty inherits statefulset labels
> * non-nil with non-overlapping labels merge pvc and statefulset labels
> * non-nil with overlapping labels merge pvc and statefulset labels and prefer statefulset labels

Thank you for your advice, I have fixed it and add some UTs

**Comment by cwdsuzhou** [comment]
ping @liggitt

**Comment by liggitt** [comment]
this looks reasonable to me, but will defer to @kow3ns / @kubernetes/sig-apps-pr-reviews for final lgtm

**Comment by cwdsuzhou** [comment]
cc @kow3ns @kubernetes/sig-apps-pr-reviews

PTAL

**Comment by cwdsuzhou** [comment]
@enisoc @janetkuo 

PTAL

**Comment by cwdsuzhou** [comment]
@kow3ns thanks, could you help add lgtm

**Comment by cwdsuzhou** [comment]
ping @liggitt @janetkuo @enisoc @oomichi  @kow3ns 
Since kow3ns has approved this PR, could any one help add `lgtm` or review the pr

**Comment by polym** [comment]
Any plan to cherry-pick for v1.14?

**Comment by cwdsuzhou** [comment]
> Any plan to cherry-pick for v1.14?

Have cherry-picked it

**Comment by cwdsuzhou** [comment]
https://github.com/kubernetes/kubernetes/pull/84234
