### PR TITLE
Fix flaky test: Metrics should grab all metrics from kubelet /metrics/resource endpoint

### LINKED ISSUE #131229: [Flaking test]Metrics should grab all metrics from kubelet /metrics/resource endpoint
### Which jobs are flaking?

https://storage.googleapis.com/k8s-triage/index.html?date=2025-03-30&text=Invalid%20Kubelet%20port%200

- ci-kubernetes-e2e-gci-gce-containerd
- ci-cos-containerd-e2e-ubuntu-gce
and more

### Which tests are flaking?

Kubernetes e2e suite [It] [sig-instrumentation] Metrics should grab all metrics from kubelet /metrics/resource endpoint

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-e2e-ubuntu-gce/1909695070752215040

### Since when has it been flaking?

started from 3/22 or 3/23.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd and more

### Reason for failure (if possible)

```
[FAILED] Invalid Kubelet port 0. Skipping Kubelet's metrics gathering
In [It] at: k8s.io/kubernetes/test/e2e/instrumentation/metrics.go:67 @ 03/28/25 02:24:18.921

```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig instrumentation

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

`Metrics should grab all metrics from kubelet /metrics/resource endpoint` select a random ready node, but the selected node might not be available for grabbing metrics. Because the kubelet port is wipped by other tests in parallel. The aduit event from kube-apiserver show that.

The nodeInfo and daemonEndpoints fields are dropped by ` Guaranteed QoS pod, one container - increase CPU & memory with an extended resource`.

```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
   ...
  "userAgent": "e2e.test/v1.34.0 (linux/amd64) kubernetes/88dfcb2 -- [sig-node] Pod InPlace Resize Container [FeatureGate:InPlacePodVerticalScaling] [Beta] Guaranteed QoS pod, one container - increase CPU & memory with an extended resource",
  "objectRef": {
    "resource": "nodes",
    "name": "bootstrap-e2e-minion-group-37cw",
    "apiVersion": "v1",
    "subresource": "status"
  },
  "responseStatus": {
    "metadata": {},
    "code": 200
  },
  "requestObject": {
    "metadata": {
      "creationTimestamp": null
    },
    "spec": {},
    "status": {
      "capacity": {
        "dummy.com/dummy": "123"
      },
      "allocatable": {
        "dummy.com/dummy": "123"
      },
      "daemonEndpoints": {
        "kubeletEndpoint": {
          "Port": 0
        }
      },
      "nodeInfo": {
        "machineID": "",
        "systemUUID": "",
        "bootID": "",
        "kernelVersion": "",
        "osImage": "",
        "containerRuntimeVersion": "",
        "kubeletVersion": "",
        "kubeProxyVersion": "",
        "operatingSystem": "",
        "architecture": ""
      }
    }
  },
  "responseObject": {
    "kind": "Node",
    "apiVersion": "v1",
    ...
    "status": {
      "capacity": {
        "cpu": "2",
        "dummy.com/dummy": "123",
        "ephemeral-storage": "101430960Ki",
        "hugepages-1Gi": "0",
        "hugepages-2Mi": "0",
        "memory": "8139160Ki",
        "pods": "110"
      },
      "allocatable": {
        "cpu": "2",
        "dummy.com/dummy": "123",
        "ephemeral-storage": "93478772582",
        "hugepages-1Gi": "0",
        "hugepages-2Mi": "0",
        "memory": "7883160Ki",
        "pods": "110"
      },
      ...
      "daemonEndpoints": {
        "kubeletEndpoint": {
          "Port": 0
        }
      },
      "nodeInfo": {
        "machineID": "",
        "systemUUID": "",
        "bootID": "",
        "kernelVersion": "",
        "osImage": "",
        "containerRuntimeVersion": "",
        "kubeletVersion": "",
        "kubeProxyVersion": "",
        "operatingSystem": "",
        "architecture": ""
      },
      ...
    }
  },
  ...
}
```

#### Which issue(s) this PR fixes:

Fixes #131229

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
image

File: test/e2e/framework/node/helper.go [hunk 1]
```diff
@@ -185,18 +183,16 @@ func AddExtendedResource(ctx context.Context, clientSet clientset.Interface, nod
...
+			return fmt.Errorf("failed to get node %s: %w", nodeName, err)
+		}
+		node.Status.Capacity[extendedResource] = extendedResourceQuantity
+		node.Status.Allocatable[extendedResource] = extendedResourceQuantity
+		_, err = clientSet.CoreV1().Nodes().UpdateStatus(ctx, node, metav1.UpdateOptions{})
+		return err
 	})
-	framework.ExpectNoError(err, "Failed to marshal node JSON")
-
-	_, err = clientSet.CoreV1().Nodes().Patch(ctx, nodeName, types.StrategicMergePatchType, []byte(patchPayload), metav1.PatchOptions{}, "status")
```
Comment (aojea) [inline test/e2e/framework/node/helper.go:199]: why the patch wipes out the other fields?

Comment (aojea) [reply test/e2e/framework/node/helper.go:199]: I see your screenshot now 🤔

File: test/e2e/framework/node/helper.go [hunk 2]
```diff
@@ -185,18 +183,16 @@ func AddExtendedResource(ctx context.Context, clientSet clientset.Interface, nod
...
 
 	ginkgo.By("Adding a custom resource")
-	extendedResourceList := v1.ResourceList{
-		extendedResource: extendedResourceQuantity,
-	}
-	patchPayload, err := json.Marshal(v1.Node{
-		Status: v1.NodeStatus{
-			Capacity:    extendedResourceList,
-			Allocatable: extendedResourceList,
-		},
```
Comment (aojea) [inline test/e2e/framework/node/helper.go:195]: so the problem seems to be how we are generating the patch payload , cc: @liggitt

Comment (pohly) [reply test/e2e/framework/node/helper.go:195]: https://github.com/kubernetes/api/blob/22c1e39ad8694905cfaad52a473d81f230d61bcb/core/v1/types.go#L6108 has an empty KubeletEndpoint, but `omitempty` does not work for structs, only for struct pointers. Therefore we get the `"kubeletEndpoint": {"port": 0}` in the patch and that field then gets set to zero.

Perhaps replace with server-side-apply or generate the patch with plain old `fmt.Sprintf`?

**Comment by carlory** [comment]
@pohly Sorry for inconvenience, I update the PR's description.

File: test/e2e/framework/node/helper.go (hunk 2 above)
Comment (liggitt) [reply test/e2e/framework/node/helper.go:195]: +1 to using patch still, but constructing the patch more correctly. JSON marshaling `map[string]any{"status":map[string]any{...}}` with just the exact status fields you want would be fine, and a little better than sprintf

Comment (carlory) [reply test/e2e/framework/node/helper.go:195]: updated.

**Review by hashim21223445 — APPROVED** [review]

**Comment by liggitt** [comment]
Seeing this flake on many PRs, I think we should merge this test deflake for 1.33

**Comment by dims** [comment]
@npolshakova let's please add milestone for this!

cc @kubernetes/release-team @npolshakova
