### PR TITLE
run make verify with python3 to fix publishing bot issue

### LINKED ISSUE #93623: Failing Test: pull-kubernetes-verify - publishing-bot
**Which jobs are failing**:
pull-kubernetes-verify

**Which test(s) are failing**:
publishing-bot

**Since when has it been failing**:
07-31 12:23 PDT

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-verify

**Reason for failure**:
missing pyyaml module

**Anything else we need to know**:
Running case: verify.publishing-bot 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes 
+++ command: python "hack/make-rules/../../hack/verify-publishing-bot.py" Please install missing pyyaml module and re-run hack/make-rules/../../hack/verify-publishing-bot.py 
+++ exit code: 1 
+++ error: 1

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

`verify` is currently failing because `verify-publishing-bot.py` cannot import `pyyaml` (https://github.com/kubernetes/kubernetes/blob/0051d65f9f30db724dfb88256f70c23e37f6b257/hack/verify-publishing-bot.py#L65). Guessing that this has to do with the recent addition of `python3` to the `kubekins-e2e` image (https://github.com/kubernetes/test-infra/pull/18531) and conflicting installs of `pyyaml`. Hopefully running with `python3` will alleviate this issue.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #93623 

**Special notes for your reviewer**:

Going to see if `pull-kubernetes-verify` passes here. If we use this fix we should circle back and clean up the `pyyaml` requirement in https://github.com/kubernetes/test-infra/blob/master/requirements2.txt

/sig testing
/priority critical-urgent
/milestone v1.19

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hasheddan** [comment]
Looks like `verify-publishing-bot` did pass despite the `pull-kubernetes-verify` failure. Will fix up commit and push again.

File: hack/make-rules/verify.sh [hunk 1]
```diff
@@ -220,7 +220,7 @@ fi
 
 ret=0
 run-checks "${KUBE_ROOT}/hack/verify-*.sh" bash
-run-checks "${KUBE_ROOT}/hack/verify-*.py" python
+run-checks "${KUBE_ROOT}/hack/verify-*.py" python3
```
Comment (MushuEE) [inline hack/make-rules/verify.sh:223]: Kinda curious why ${KUBE_ROOT} is `hack/make-rules/../../`, doesn't impact anything but just odd imo.

**Comment by MushuEE** [comment]
Looks like with the python3 run we are hitting[ yaml deprecation](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) warning. I think we can just add `Loader=yaml.FullLoader` [here](https://github.com/kubernetes/kubernetes/blob/a1e511abda610106bee439c2a2ff22b14b1b063b/hack/verify-publishing-bot.py#L48)

**Comment by hasheddan** [comment]
@MushuEE thanks for pointing that out! I will make sure to update that here after we have a `kubekins` image ready where python2 and python3 both work so that we don't have to cherry-pick back to old releases 👍

**Comment by droslean** [comment]
/retitle run make verify with python3 to fix publishing bot issue

**Comment by droslean** [comment]
/hold

@hasheddan This seems to be ready to merge. Can you check and hold cancel?

**Comment by hasheddan** [comment]
Thanks @droslean!

/hold cancel
