### PR TITLE
Fix IPVS proxier to update stale real server after restart

### LINKED ISSUE #108319: kube-proxy in ipvs mode leaves real server weight as 0 after restart
### What happened?

Entry in ipvs real sever remains at weight=0 after kube-proxy restarts. (During 1.21 -> 1.22 kubernetes cluster upgrade.)

Related to https://github.com/kubernetes/kubernetes/issues/92019

As the related issue is considered closed, I will report this issue again as the problem still persists in newer version. Might because of some corner cases.

### What did you expect to happen?

Real server weight should be 1 when endpoints is ready.

### How can we reproduce it (as minimally and precisely as possible)?

- Use kube-proxy in ipvs mode
- Deploy a service resource and its backend pods
- Make real sever not ready (or may need node not ready) so as to trigger graceful delete in kube-proxy
- Before kube-proxy deletes the entry from ipvs, restart kube-proxy
- Kube-proxy becomes ready and leave the weight=0 entry as it is
- Service is no longer accessible through cluster ip
- When accessed, dmesg shows kernel messge error of `IPVS: rr: TCP <cluster ip>:<port> - no destination available`

- Deletion of pod will trigger kube-proxy to remove weight=0 entry from ipvs so that after the entry is recreated service will become accessible
- If service is 1. .spec.type: LoadBalancer, and, 2. .spec.externalTrafficPolicy: Local, and, 3, service is accessed from loadbalancer IP, the entry in ipvs for loadbalancer IP will only have endpoints in the same node. If backends is DaemonSet, the only one endpoints will have weight=0 thus causing connection failure

### Anything else we need to know?

After kube-proxy restarts, endpoints will be processed in the following lines.

https://github.com/kubernetes/kubernetes/blob/b56e432f2191419647a6a13b9f5867801850f969/pkg/proxy/ipvs/proxier.go#L2122

Only when the entry is in the gracefuldeleteManager.InTerminationList will be deleted. Which is not the case if kube-proxy restarts before it deletes the ipvs entry.

An existing entry in the ipvs is sufficient for endpoint to be considered healthy. Weight is not considered.

kube-proxy should treat ipvs entry properly by the either the following two ways.

- kube-proxy should initiate InTerminationList and put ipvs entry with weight=0 into the termination list
- kube-proxy should also look for weight in the ipvs entry instead of only UniqueRSName

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-premises
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux hostname 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aryan9600**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Update the IPVS proxier to have a bool `updateWeights` which is set to
true during the initial syncs performed by `OnEndpointSlicesSynced` and
`OnServiceSynced` to make sure any real servers with stale weights are
updated accordingly at startup. This logic is gated behind a bool to
avoid doing this during every sync as it's an expensive operation.

#### Which issue(s) this PR fixes:

Fixes #108319

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -892,10 +897,15 @@ func (proxier *Proxier) OnServiceSynced() {
 	proxier.mu.Lock()
 	proxier.servicesSynced = true
 	proxier.setInitialized(proxier.endpointSlicesSynced)
+	proxier.updateWeights = true
 	proxier.mu.Unlock()
 
 	// Sync unconditionally - this is called once per lifetime.
 	proxier.syncProxyRules()
+
```
Comment (uablrek) [inline pkg/proxy/ipvs/proxier.go:905]: Remove the `proxier.updateWeights = false` from here and instead do it where it's checked (see below)

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -928,10 +938,15 @@ func (proxier *Proxier) OnEndpointSlicesSynced() {
 	proxier.mu.Lock()
 	proxier.endpointSlicesSynced = true
 	proxier.setInitialized(proxier.servicesSynced)
+	proxier.updateWeights = true
 	proxier.mu.Unlock()
 
 	// Sync unconditionally - this is called once per lifetime.
 	proxier.syncProxyRules()
+
+	proxier.mu.Lock()
```
Comment (uablrek) [inline pkg/proxy/ipvs/proxier.go:947]: same as above

File: pkg/proxy/ipvs/proxier.go [hunk 3]
```diff
@@ -2007,6 +2022,19 @@ func (proxier *Proxier) syncEndpoint(svcPortName proxy.ServicePortName, onlyNode
 		}
 
 		if curEndpoints.Has(ep) {
+			// if we want to update weights, loop through all current destinations and
+			// reset their weight.
+			if proxier.updateWeights {
+				for _, dest := range curDests {
```
Comment (uablrek) [inline pkg/proxy/ipvs/proxier.go:2028]: Add `proxier.updateWeights = false` here. The mutex is held so it's safe

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2028]: (btw, you may make a comment that the mutex is held)

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2028]: we can't add this here, as this is inside a loop. adding this outside the loop instead.

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2028]: Outside the "for _, ep := range newEndpoints.List() {" loop you mean? Seens reasonable.

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2028]: on second thought, is it completely safe to have `proxier.updateWeights = false` inside `syncProxyRules()` instead of `OnServicesSynced()`/`OnEndpointSynced()`?
i'm asking because in `OnServicesSynced()` we do something like:
```golang
proxier.mu.Lock()
...
proxier.updateWeights = true
proxier.mu.Unlock()

proxier.syncProxyRules()
```
so even though `proxier.syncProxyRules()` would capture the mutex first thing, theoretically another goroutine which called `syncProxyRules()` could execute `proxier.updateWeights = false` at the exact moment between `OnServiceSynced` let go of the lock and `proxier.syncProxyRules()` acquired the lock.

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2028]: But it should go into the "syncProxyRules()" function somewhere, else you got a race since the lock is released and reclaimed. The proxier.updateWeights = false should be done when holding the lock in syncProxyRules().

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2028]: You are right. To set proxier.updateWeights = false in "syncProxyRules()" makes it safer, but setting proxier.updateWeights = false outside "syncProxyRules()" and release the lock is not safe.

A safe way may be
1. Initiate the proxy struct with someBool = true
2. In "syncProxyRules()" (lock held), do the one-time stuff and set someBool = false

However this would require 2 bools

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2028]: then i'm wondering whether it makes sense to set `proxier.updateWeights = true` _only_ in `OnServicesSynced()` and not on `OnEndpointSliceSynced()`, since we only need to sync the endpoints once.

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2028]: `OnServicesSynced()` makes more sense than `OnEndpointSliceSynced()` because that's guaranteed to run once on startup: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L746, unlike `OnEndpointSliceSynced()`, which may not be run if the cluster is using only `Endpoint` and not `EndpointSlice`

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2028]: I was about to ask that :smile: If the function only needs to be called once (not one time for endpoints and one time for endpointslices), then initiate "updateWeights" to true when the proxier struct is created and set it to false immediately after "if proxier.updateWeights"

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2028]: yes, that works as well. let's go ahead with that.

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2019]: Is this possible?
```go
func (proxier *Proxier) syncProxyRules() {
	proxier.mu.Lock()
	defer proxier.mu.Unlock()
        defer proxier.updateWeights = false
```
If so, a generic bool like `firstTimeSync` may be appropriate and may be used by future one-shot functions.

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2019]: yes, this is better 👍

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2019]: I made a test but it's not working yet https://go.dev/play/p/y-HwPYW3eNa

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2019]: Silly mistake, now it works

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2019]: yes, i noticed `first` needs to be initialized to true instead of false

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2019]: Seems `go` has support for "Once"; https://golangcode.com/run-code-once-with-sync/

You may see if you can use it.

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:2019]: I am unsure if it's better since we already have the proxier.mu mutex.

Comment (aryan9600) [reply pkg/proxy/ipvs/proxier.go:2019]: I think it's better to avoid `sync.Once` because if in the future we want to do more things only on startup, the underlying function will get large. Having a flag gives us flexibility about where we want to run the one-stop logic during sync.

**Review by uablrek — APPROVED** [review]

**Comment by uablrek** [comment]
I was a bit hasty with the approve button :blush: The code looks good but it doesn't solve the problem. It seems there _is a need_ to do the update both for endpoints and endpointSlices. I found my old tests for the issue and as it is now the weight stays a 0.

I altered the code to;
```go
func (proxier *Proxier) syncProxyRules() {
	proxier.mu.Lock()
	defer proxier.mu.Unlock()
	// To ensure complete initialization we can only consider the
	// initial sync done when the proxier is initialized.
	defer func() {
		if proxier.initialized == 1 {
			proxier.initialSync = false
		}
	}()
```
_then_ it works.

**Comment by aryan9600** [comment]
okay, thanks for catching this. let me confirm this and update 👍

**Comment by aojea** [comment]
> I was a bit hasty with the approve button  The code looks good but it doesn't solve the problem. It seems there _is a need_ to do the update both for endpoints and endpointSlices. I found my old tests for the issue and as it is now the weight stays a 0.

/hold

just to avoid we merge unintentionally , once you are good unhold it, is just a precaution

**Comment by uablrek** [comment]
Taking another look and I see that `proxier.initialized` is checked just a few lines down and with an atomic operation. So the defer function _just have to be moved to after the check_;
```go
func (proxier *Proxier) syncProxyRules() {
	proxier.mu.Lock()
	defer proxier.mu.Unlock()

	// don't sync rules till we've received services and endpoints
	if !proxier.isInitialized() {
		klog.V(2).InfoS("Not syncing ipvs rules until Services and Endpoints have been received from master")
		return
	}

	defer func() {
		proxier.initialSync = false
	}()
```

**Comment by uablrek** [comment]
(the proposed fix above is tested and works)

**Comment by uablrek** [comment]
Tested and works.

/lgtm
/unhold
