### PR TITLE
exit kube-proxy when configuration file changes

### LINKED ISSUE #57144: Updating kube-proxy configmap doesn't reload/restart kube-proxy
/kind bug

**What happened**:
I've updated the kube-proxy configmap after the master IPs changed but had to delete kube-proxy pods manually for the changes to take effect.

**What you expected to happen**:
That kube-proxy reloads or get restarted on configmap changes.

**How to reproduce it (as minimally and precisely as possible)**:
- Create cluster with kube-proxy and kube-proxy configmap pointing to the apiserver
- Change the kube-proxy config map, pointing to a new apiserver
- Deleted the old apiserver

After that, the cluster should become unresponsive due to kube-proxy still talking to the old apiservers.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.4

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57144

**Special notes for your reviewer**:
/assign thockin 
/cc smarterclayton liggitt 

**Release note**:

```release-note
exit kube-proxy when configuration file changes
```

### CODE REVIEW

File: pkg/util/rerun/rerun.go [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+	stopCh := make(chan bool)
+	defer close(stopCh)
+
+	chFn := func() {
+		var isRunning bool
+		for {
+			select {
+			case <-stopCh:
+				break
+			default:
```
Comment (thockin) [inline pkg/util/rerun/rerun.go]: This is going to busy loop - I don't think that is what you want.  Why not return?

https://play.golang.org/p/AbOnhxWZFmz

File: pkg/util/rerun/rerun.go [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+			}
+		}
+	}
+
+	go chFn()
+	for {
+		select {
+		case ent = <-event:
+			if eventHandler(ent) {
+				errCh <- nil
```
Comment (thockin) [inline pkg/util/rerun/rerun.go]: rather than throw a nil across a channel, to be received 2 lines down, why don't you just call the code you want to call?

File: pkg/util/rerun/rerun.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+limitations under the License.
+*/
+
+package rerun
+
+import (
+	"github.com/golang/glog"
+)
+
+// ReRun will restart the target function when event gets changed
```
Comment (thockin) [inline pkg/util/rerun/rerun.go]: This comment is insufficient to describe the complexity that this is trying to capture.  I think this function is kind of over-complicated.  Can you write a nice comment explaining what you want to do, what all the args are for, and then see if the code can be simpler?

File: cmd/kube-proxy/app/server.go [hunk 4]
```diff
@@ -335,7 +348,33 @@ with the apiserver API to configure the proxy.`,
...
+					case e := <-opts.event:
+						switch e.Op {
+						case fsnotify.Write:
+							entCh <- true
+						}
+					}
+				}
+			}()
+
+			cmdutil.CheckErr(rerun.ReRun(
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: This seems very delicate to me.  If other goroutines are spawned, deep inside this, who is going to clean those up?  Who is going to release allocated memory?  I think you really just want to catch the event, exit cleanly, and let the kubelet restart you

File: cmd/kube-proxy/app/server.go [hunk 5]
```diff
@@ -205,15 +211,22 @@ func (o *Options) Validate(args []string) error {
 	if len(args) != 0 {
 		return errors.New("no arguments are supported")
 	}
+	return nil
+}
+
+func (o *Options) Run() error {
+	if c, err := o.loadConfigFromFile(o.ConfigFile); err != nil {
```
Comment (liggitt) [inline cmd/kube-proxy/app/server.go]: please don't mutate Options in `Run()`... goal is to do mutation in `Complete()` so that inputs are resolved prior to calling `Run()`

File: cmd/kube-proxy/app/server.go (hunk 4 above)
Comment (liggitt) [reply cmd/kube-proxy/app/server.go]: agree, this change (and the ReRun change) makes the scheduler execute flow almost incomprehensible. If the top-level kube-proxy command optionally shuts down the proxy and cleanly exits on config file change, that seems sufficient.

I expected more of the following:
* opts adds a `Stop()` function that shuts down scheduler processes cleanly (might require plumbing stop channels in `Run()`)
* opts contains an optional `OnConfigChange func()` field
* if present, it sets up the file listener and calls `OnConfigChange()` when the file changes
* top-level kube-proxy command (optionally) sets opts.OnConfigChange to `func() { opts.Stop(); os.Exit(0); }`, etc

That keeps the top-level flow very straightforward, avoids deeply embedding os.Exit() calls, allows other consumers of kubeproxy opts to hook in different behavior on config file change, etc.

**Comment by dixudx** [comment]
@liggitt @thockin Updated. PTAL. Thanks.

File: cmd/kube-proxy/app/server.go [hunk 6]
```diff
@@ -180,6 +188,13 @@ func NewOptions() *Options {
 		scheme:      scheme.Scheme,
 		codecs:      scheme.Codecs,
 		CleanupIPVS: true,
+		OnConfigChange: func(ent fsnotify.Event) {
+			switch ent.Op {
+			// exit when ConfigFile is updated
+			case fsnotify.Write:
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: Does this capture someone writing a temp file and renaming it, too?  That's how configmap generally works.

File: cmd/kube-proxy/app/server.go [hunk 7]
```diff
@@ -230,7 +260,47 @@ func (o *Options) Run() error {
...
+		var isRunning bool
+		for {
+			select {
+			case <-o.stopCh:
+				return
+			default:
+				if !isRunning {
+					isRunning = true
+					go func() {
+						err := proxyServer.Run()
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: if Run() ever returns, this will be a hotloop, won't it?

stopCh has nothing, isRunning  is true, loop as fast as possible.

This feels more complicated than it needs to be.  Can't we just assume that after OnChange() is called this whole function is going to exit?  What are you designing for here?

File: cmd/kube-proxy/app/server.go (hunk 6 above)
Comment (dixudx) [reply cmd/kube-proxy/app/server.go]: > Does this capture someone writing a temp file and renaming it, too?

No. We could add it. But supporting this will cause the flag `--config` of kube-proxy outdated when the filename get renamed.

File: cmd/kube-proxy/app/server.go (hunk 7 above)
Comment (dixudx) [reply cmd/kube-proxy/app/server.go]: @thockin Updated. PTAL. Thanks.

File: cmd/kube-proxy/app/server.go [hunk 8]
```diff
@@ -204,13 +219,26 @@ func (o *Options) Complete() error {
 		} else {
 			o.config = c
 		}
+		// Sets up the file listener and watches events on file change
+		if (o.OnConfigChange) != nil {
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: Why would it be nil?

File: cmd/kube-proxy/app/server.go [hunk 9]
```diff
@@ -237,7 +264,31 @@ func (o *Options) Run() error {
...
+	// run the proxy in goroutine
+	go func() {
+		err := proxyServer.Run()
+		errCh <- err
+	}()
+
+	for {
+		select {
+		case err := <-o.watcherError:
+			errCh <- err
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: rather than reading the error here and below and then writing to a channel, why not just `return err` ?

**Comment by thockin** [comment]
This could use some unit test

File: cmd/kube-proxy/app/server.go (hunk 8 above)
Comment (dixudx) [reply cmd/kube-proxy/app/server.go]: Just in case this function is defined.

**Comment by dixudx** [comment]
@thockin  @liggitt PTAL. Updated and tests added. Thanks.

**Comment by darxtrix** [comment]
Hi @dixudx Are there any changes pending in this PR ?  I seem some tests failing.

I would like to contribute to Kubernetes, would be happy to help here.

File: cmd/kube-proxy/app/server.go [hunk 10]
```diff
@@ -235,8 +267,37 @@ func (o *Options) Run() error {
 	if err != nil {
 		return err
 	}
+	o.proxyServer = proxyServer
+	return o.run()
+}
 
-	return proxyServer.Run()
+func (o *Options) run() error {
```
[the remark this answers is not in the document]
Comment (dixudx) [reply cmd/kube-proxy/app/server.go]: Mainly make it easier for testing.

File: cmd/kube-proxy/app/server.go [hunk 11]
```diff
@@ -186,6 +198,16 @@ func NewOptions() *Options {
 		scheme:      scheme.Scheme,
 		codecs:      scheme.Codecs,
 		CleanupIPVS: true,
+		OnConfigChange: func(ent fsnotify.Event) error {
```
[the remark this answers is not in the document]
Comment (dixudx) [reply cmd/kube-proxy/app/server.go]: Just wanna it more configurable.

**Comment by dixudx** [comment]
@darxtrix  Thanks for your help. Feel free to contribute if you've found some root causes for the failing tests.

File: cmd/kube-proxy/app/server.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (thockin) [reply cmd/kube-proxy/app/server.go]: But for what purpose?  This makes it harder to find and read and debug, so it has to be justified.

File: cmd/kube-proxy/app/server.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (thockin) [reply cmd/kube-proxy/app/server.go]: can you rename to `runLoop` or `loop` or something and add a comment to make it more obvious?

**Review by thockin — COMMENTED** [review]
Overall LG, sorry for letting this sit...

**Comment by thockin** [comment]
Ping?  Should someone else pick this up?

@vllry maybe

**Comment by dixudx** [comment]
@thockin Sorry for putting this aside for quite a long time.

I will continue working on it. Seems the CIs are not happy for this change. I will try to fix them up.

**Comment by vllry** [comment]
/retest

@dixudx you appear to have hit some known test infra issues... fingers crossed this time! (The kops infra is having issues, and the GCP infra ran out of resources earlier)

**Comment by dixudx** [comment]
> you appear to have hit some known test infra issues

@vllry I thought that was an infra issue. But after I added some debug log, I got the clue. It was my codes that got panic. Already fixed. Let's see whether that works.

**Comment by dixudx** [comment]
@thockin The tests turn green now. It's ready for review. PTAL. Thanks.

**Comment by dixudx** [comment]
pull-kubernetes-e2e-kops-aws is flaky now. Will retest it when recovered.

**Comment by vllry** [comment]
/hold

The kops test environment is still unavailable. Right now that test suite is optional for merges.

**Comment by vllry** [comment]
Whoops, I only thought hold would silence the bot :(

/hold cancel

File: cmd/kube-proxy/app/server.go [hunk 12]
```diff
@@ -217,10 +235,39 @@ func (o *Options) Complete() error {
...
 
+func (o *Options) eventHandler(ent fsnotify.Event) {
+	eventOpIs := func(Op fsnotify.Op) bool {
+		return ent.Op&Op == Op
+	}
+	if eventOpIs(fsnotify.Write) || eventOpIs(fsnotify.Rename) {
+		// error out when ConfigFile is updated
+		o.errCh <- fmt.Errorf("content of the proxy server's configuration file was updated")
+	}
+	o.errCh <- nil
```
Comment (tedyu) [inline cmd/kube-proxy/app/server.go]: If line 262 is executed, is this still needed ?

File: cmd/kube-proxy/app/server.go [hunk 13]
```diff
@@ -257,8 +304,31 @@ func (o *Options) Run() error {
...
+	go func() {
+		err := o.proxyServer.Run()
+		o.errCh <- err
+	}()
 
-	return proxyServer.Run()
+	for {
+		select {
+		case err := <-o.errCh:
+			if err != nil {
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server.go]: I _think_ this is the cause for https://github.com/kubernetes/kubernetes/issues/76727 since `kube-proxy --cleanup` returns nil error and is expected to exit. cc @vllry @thockin

Comment (vllry) [reply cmd/kube-proxy/app/server.go]: Yep. #76732 is an open change for that, will comment there.
