### PR TITLE
Make StatefulSet restart pods with phase Succeeded

### LINKED ISSUE #118310: Pod phase changed when container exits with 0 in 1.27
/sig node

After https://github.com/kubernetes/kubernetes/pull/115331 the phase of terminal pods killed with killPodFunc is determined based on the exit codes of the containers. This was discovered in the context of preemption while doing a cherry-pick to 1.26, and observing that the phase changed: https://github.com/kubernetes/kubernetes/pull/118221.

Summary of the phase transitions when the pod container exits with 0 (when restartPolicy=Always):
| scenario                                         | 1.26             |  1.27 
| -----------                                          | -----------       |  -----------
|  preemption                                  |  Failed         | Succeeded
|  eviction due to node pressure                      |  Failed         | Succeeded
| node shutdown                            | Failed | Succeeded
| active deadline exceeded           | Failed          | Failed

Note that eviction due to exceeding storage limits isn't affected because it uses grace period=0. In that case, SIGKILL is sent directly, and the containers end with 137. 

Are the changed phases a bug?
- if a bug, how to approach fixing it?
- if not a bug, we should clean up the setting of the phase as Failed in the component status updates, like here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/preemption/preemption.go#L106

Note: The change of phase for "node shutdown" was discovered earlier and uncovered a DaemonSet issue that was fixed: https://github.com/kubernetes/kubernetes/issues/117018

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
#### What type of PR is this?

/kind bug
/sig apps

#### What this PR does / why we need it:

After the changes in #115331, pod phase determination changed. It is now possible for StatefulSet pods to get in `Succeeded` pod phase. This can happen when a pod is evicted or a node is stopped and the pod container exists with 0. StatefulSet should restart such pods. It is not possible for a StatefulSet pod to ever truly complete, as validation enforces `restartPolicy=Always`.

#### Which issue(s) this PR fixes:

Part of #118310

#### Does this PR introduce a user-facing change?

```release-note
Fixes an issue where StatefulSet might not restart a pod after eviction or node failure.
```

/cc @mimowo

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -375,8 +375,17 @@ func (ssc *defaultStatefulSetControl) processReplica(
...
+	// Note that pods with phase Succeeded will also trigger this event. This is
+	// because final pod phase of evicted or otherwise forcibly stopped pods
+	// (e.g. terminated on node reboot) is determined by the exit code of the
+	// container, not by the reason for pod termination. We should restart the pod
+	// regardless of the exit code.
+	//
+	// Also note that it is impossible for StatefulSet pods to ever truly complete,
+	// as validation allows only restartPolicy=Always.
+	if isFinished(replicas[i]) {
 		ssc.recorder.Eventf(set, v1.EventTypeWarning, "RecreatingFailedPod",
```
Comment (mimowo) [inline pkg/controller/statefulset/stateful_set_control.go:389]: I think it is better to issue a dedicated event `RecreatingSucceededPod`. This is what we do for daemon set in the analogous case: https://github.com/kubernetes/kubernetes/pull/117073/files

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 2]
```diff
@@ -435,6 +436,44 @@ func RecreatesFailedPod(t *testing.T, set *apps.StatefulSet, invariants invarian
...
+	}
+	if err := invariants(set, om); err != nil {
+		t.Error(err)
+	}
+	pods, err = om.podsLister.Pods(set.Namespace).List(selector)
+	if err != nil {
+		t.Error(err)
+	}
+	if isCreated(pods[0]) {
+		t.Error("StatefulSet did not recreate failed Pod")
```
Comment (mimowo) [inline pkg/controller/statefulset/stateful_set_control_test.go:473]:
```suggestion
		t.Error("StatefulSet did not recreate succeeded Pod")
```

**Review by mimowo — COMMENTED** [review]
I would also like to have an integration test, if feasible.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/statefulset/stateful_set_control.go:389]: Potentially, but I'm concerned about backwards compatibility as this would mean renaming an existing event type. I would suggest decoupling this to a dedicated discussion / PR. @alculquicondor wdyt?

File: pkg/controller/statefulset/stateful_set_control.go [hunk 3]
```diff
@@ -375,8 +375,17 @@ func (ssc *defaultStatefulSetControl) processReplica(
...
+	// Delete and recreate pods which finished running.
+	//
+	// Note that pods with phase Succeeded will also trigger this event. This is
+	// because final pod phase of evicted or otherwise forcibly stopped pods
+	// (e.g. terminated on node reboot) is determined by the exit code of the
+	// container, not by the reason for pod termination. We should restart the pod
+	// regardless of the exit code.
+	//
+	// Also note that it is impossible for StatefulSet pods to ever truly complete,
+	// as validation allows only restartPolicy=Always.
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control.go:387]: I would remove this last paragraph. It is confusing, as we can see that it will actually complete in case of VM preemption or node pressure.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 1 above)
Comment (aleksandra-malinowska) [reply pkg/controller/statefulset/stateful_set_control.go:389]: Based on discussion on sig-apps slack:
- we need to be careful with renaming events of type warning (so, `RecreateFailedPod` stays as it is),
- just recreating a pod should be emitted as a normal event, not warning.

@alculquicondor DaemonSet events are already different - I might be missing something, but I haven't found any 'recreate' events, only `FailedDaemonPod` and `SucceededDaemonPod` informing of deleting the pod. So I'm not sure if we need to name the new event `RecreateSucceededPod`, as there's already little consistency. I think we can use `RecreateTerminatedPod` here, and it'll be much clearer to the user.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 4]
```diff
@@ -435,6 +436,44 @@ func RecreatesFailedPod(t *testing.T, set *apps.StatefulSet, invariants invarian
...
+		t.Errorf("Error updating StatefulSet %s", err)
+	}
+	if err := invariants(set, om); err != nil {
+		t.Error(err)
+	}
+	pods, err = om.podsLister.Pods(set.Namespace).List(selector)
+	if err != nil {
+		t.Error(err)
+	}
+	pods[0].Status.Phase = v1.PodSucceeded
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control_test.go:460]: Is this the only difference with RecreatesFailedPod? Can we deduplicate by adding a function that returns a function?

Comment (alculquicondor) [reply pkg/controller/statefulset/stateful_set_control_test.go:460]: let's leave it for a follow up, given the cherry-pick deadline.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
/assign @soltysh @janetkuo

**Review by janetkuo — APPROVED** [review]
/approve

**Comment by alculquicondor** [comment]
/retest
#119600
