### PR TITLE
Check first if ipvs module is builtin

### LINKED ISSUE #77493: kube_proxy running under a static kernel reports false-positive module load failures
<Reopened this valid and in-demand bug after the auto-bot expired it>

/kind bug
/sig network
/area kube-proxy

**What happened**:
Building a fully static Linux kernel with  kube_proxy's desired IP_VS (Virtual Server) modules linked statically:

CONFIG_IP_VS=y
CONFIG_IP_VS_RR=y
CONFIG_IP_VS_WRR=y
CONFIG_IP_VS_SH=y
CONFIG_NF_CONNTRACK_IPV4=y

Causes kube_proxy to believe that these features don't exist because it can't find modules for them:

```
W0923 18:20:43.979259       1 proxier.go:469] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0923 18:20:43.979848       1 proxier.go:469] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0923 18:20:43.980415       1 proxier.go:469] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0923 18:20:43.981481       1 proxier.go:469] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0923 18:20:43.982052       1 proxier.go:469] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules

```

**What you expected to happen**:

If Kube_proxy's desired kernel features are linked statically in the kernel, kube_proxy should carry on and not attempt and throw error messages about modules not being found.

Under the hood, kube_proxy should simply check for the existence of the desired kernel features in the /proc tree (ie: `/proc/sys/net/ipv4/vs`, and others) **before** attempting to look for and load modules. If, after module loads fails, then throw the error messages and switch to iptables.

**How to reproduce it (as minimally and precisely as possible)**:

1. Download and extract the current stable kernel source version (today it's 4.18.9) from kernel.org
2. Copy your existing running `/boot/config-old_kernel_version` into the source tree as `.config` 
3. Run `make oldconfig` and answer any questions
4. Run ` make localyesconfig` to switch to a fully static kernel
4. Modify `.config` and ensure the following exist, and are not `=m`:
    ```
    CONFIG_IP_VS=y
    CONFIG_IP_VS_RR=y
    CONFIG_IP_VS_WRR=y
    CONFIG_IP_VS_SH=y
    CONFIG_NF_CONNTRACK_IPV4=y
    ```
5. Run `make menuconfig` and deselect  `[ ] Enable loadable module support` (box is empty)
5. `make -j$(nproc)`
7. `cp arch/x86/boot/bzImage /boot/vmlinuz-4.18.9-kube_proxy_mods_static`
8. `cp .config /boot/config-4.18.9-kube_proxy_mods_static`
9. Regenerate your boot loader's config (`grub2-mkconfig -o /boot/grub2/grub.cfg`) or (`grub-mkconfig -o /boot/grub/grub.cfg`) depending on your distribution.
10. Reboot and select your new kernel with the kube_proxy modules linked statically.
11. Start kube_proxy and watch it throw the above errors about not finding the modules.

**Anything else we need to know?**:

Fully static kernels will not generate `/lib/modules/$kerne_version/modules.builtin` so inspecting that file will fail - as well in the kube_proxy source. The gold-standard is to simply check for the features in the active`/proc/...` tree first, and consider those as "built-in".   

The next best options is checking `/boot/config-$(uname -r)` for `CONFIG_<FEATURE>=y` statements, which tells you if they're built-in.  Note that `/boot/config-<version>` files are almost universally installed by OS maintainers.

And finally, you could try checking `/proc/config.gz`, which is a compressed version of the externally held .config text file, in a similar manner noted above, however it's up to the maintainer to build that feature into the kernel (so it might not exist). 

For reference, here's the list of modules kube_proxy wants: https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L161

Here we see kube_proxy's errant module-centric code that needs to be made compatible w/ static kernels:
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L433

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration: On premise
- OS (e.g. from /etc/os-release): Leap 15.0
- Kernel (e.g. `uname -a`): 4.18.9 statically linked
- Install tools: gcc 8.1
- Others:

<reopened as it appears still unfixed and in-demand>  See how far the team got on it before it was auto-closed here: https://github.com/kubernetes/kubernetes/issues/69006%3E

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR changes the behavior of kube-proxy ipvs module loader, first checking if the module is builtin into the Kernel or else trying to load it into the kernel.

This removes unnecessary warning messages for the user if the module is already present as a static component.

**Which issue(s) this PR fixes**:

Fixes #77493

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test

**Comment by rikatz** [comment]
/retest

Maybe failing because of #82150

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -586,15 +586,12 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 	for _, module := range ipvsModules {
 		if match, _ := regexp.Match(module+".ko", b); match {
 			bmods = append(bmods, module)
-		}
-	}
-
-	// Try to load IPVS required kernel modules using modprobe first
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go]: Can we keep this comment? 
```
// Try to load the required IPVS kernel modules if not built in
```

**Review by andrewsykim — COMMENTED** [review]
Minor comment, lgtm otherwise :)

File: pkg/proxy/ipvs/proxier.go (hunk 1 above)
Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: Sure, changing here

**Comment by andrewsykim** [comment]
After reading through https://github.com/kubernetes/kubernetes/issues/77493 I don't think this will get rid of the warnings because statically linked modules are still not in the `builtin.modules` file which we are checking before attempting to load modules. @krcroft can you confirm?

**Comment by andrewsykim** [comment]
Based on this comment in the linked issue:

> Fully static kernels will not generate /lib/modules/$kerne_version/modules.builtin so inspecting that file will fail - as well in the kube_proxy source. The gold-standard is to simply check for the features in the active/proc/... tree first, and consider those as "built-in".

From my understanding, statically linked modules should be in `/lib/modules/$kerne_version/modules.builtin` though?

**Comment by rikatz** [comment]
> Based on this comment in the linked issue:
> 
> > Fully static kernels will not generate /lib/modules/$kerne_version/modules.builtin so inspecting that file will fail - as well in the kube_proxy source. The gold-standard is to simply check for the features in the active/proc/... tree first, and consider those as "built-in".
> 
> From my understanding, statically linked modules should be in `/lib/modules/$kerne_version/modules.builtin` though?

Indeed this might fail as well. But I don't know if also relying into the existence of /proc/[...] is a good idea, as running inside a container will not be aware of this directory as well

As far as I've found, the modules.builtin should be enough, but being honest I didn't had some time to hard verify if recompiling a kernel with some modules statically compiled is coing to show them into modules.builtin.

Anyway I can try to make this lab later and see if compiling ip_vs statically would reflect into modules.builtin

**Comment by rikatz** [comment]
So:

* Dynamic Module
```
root@sausagefactory:~# uname -a; modprobe ip_vs; cat /proc/net/ip_vs
Linux sausagefactory 4.4.14-smp #2 SMP Fri Jun 24 14:44:24 CDT 2016 i686 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz GenuineIntel GNU/Linux
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port Forward Weight ActiveConn InActConn
```

* Buildin module:

```
root@sausagefactory:~# uname -a; cat /lib/modules/4.4.190-smp/modules.builtin |grep -i ip_vs; cat /proc/net/ip_vs                
Linux sausagefactory 4.4.190-smp #2 SMP Thu Sep 5 07:59:57 BRT 2019 i686 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz GenuineIntel GNU/Linux
kernel/net/netfilter/ipvs/ip_vs.ko
kernel/net/netfilter/ipvs/ip_vs_rr.ko
[...]
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port Forward Weight ActiveConn InActConn
```

* TODO: Fully statically kernel

**Comment by rikatz** [comment]
@andrewsykim @krcroft I've implemented a skip-module-check here.

Don't know if this is the best (or the prettier) way to do this, otherwise ping me and I can improve the coding :)

**Comment by rikatz** [comment]
Some loud thoughts that I'll register more here.

Even thinking about creating a new flag sounds a good idea (and I've tried and failed with api changes, deep gens and so), it will break so many things I don't think it worth.

So, by the original issue:

> Fully static kernels will not generate /lib/modules/$kerne_version/modules.builtin so inspecting that file will fail - as well in the kube_proxy source. The gold-standard is to simply check for the features in the active/proc/... tree first, and consider those as "built-in".

Yes, we can check /proc. The only problem here is that /proc registers the ip_vs existence (/proc/net/ip_vs) but not the algorithms it support. So when kube-proxy tries to use ip_vs_wrr as an example, and if this isn't present in the kernel, it will fail.

> The next best options is checking /boot/config-$(uname -r) for CONFIG_<FEATURE>=y statements, which tells you if they're built-in. Note that /boot/config-<version> files are almost universally installed by OS maintainers.

As said, files are almost universally installed by OS maintainers BUT we're talking about people who recompile it own kernel (as said [here](https://github.com/kubernetes/kubernetes/issues/77493#issuecomment-524202149) ) and not everytime they put their own config files into boot. As an example, while recompiling the kernel here in Slackware I've just forgot to make that. So this might not be reliable

> And finally, you could try checking /proc/config.gz, which is a compressed version of the externally held .config text file, in a similar manner noted above, however it's up to the maintainer to build that feature into the kernel (so it might not exist).

The same as above. Slackware compiles its Kernel with the ``CONFIG_IKCONFIG_PROC`` but others don't and actually I don't think this is required when you build a full static kernel.

So, my question here is, do we really wan't kube-proxy to check /boot/config-$(uname -r) and then /proc/config.gz (inserting a decompression process here also) to check if the running kernel is actually running with the modules builtin?

I was thinking into the following flow:

1) Check if the kernel is fully static by running ``lsmod`` command. When the kernel doesn't have modules support enabled, the command will fail. 
Another more reasonable option is to check the existence of "/proc/modules" which ALWAYS exists unless the kernel is fully static (I'm really thinking about using this one)

2) If the Kernel is not fully static, the GetModules goes one.

3) If the Kernel is fully static, check /boot/config-$(uname -r)  (or anything else) to which kernel modules has been compiled builtin. If there's no such file, this might be generated by the user (zcat /proc/config.gz if it exists, creating by hand, or whatever) and kube-proxy will assume that its content is valid and check the existence of the modules against it.

Will work on it tomorrow and see how it behaves. By now I'll rollback my commits to the working ones and not to polute the CI and etc

**Comment by andrewsykim** [comment]
I'd like to keep the IPVS module/kernel checks as simple as possible, it's quite complicated as-is. I'm wondering if we can add something to the existing warning message like "ignore if IPVS modules are built statically" and call it a day. Thoughts?

**Comment by rikatz** [comment]
> I'd like to keep the IPVS module/kernel checks as simple as possible, it's quite complicated as-is. I'm wondering if we can add something to the existing warning message like "ignore if IPVS modules are built statically" and call it a day. Thoughts?

I'm working on it and will make another PR ASAP

**Comment by rikatz** [comment]
@andrewsykim Tried to make as simpler as possible :)

Ready to review here.

Tks!!

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -577,12 +577,30 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 	}
 	ipvsModules := utilipvs.GetRequiredIPVSModules(kernelVersion)
 
+	var bmods []string
+
+	// Check if this is a full static Kernel to bypass the next checks
+	_, err = ioutil.ReadFile("/proc/modules")
+	if err != nil {
+		klog.Warningf("Failed to read file /proc/modules with error %v. Assuming this is a fully static compiled Kernel", err)
```
Comment (neolit123) [inline pkg/proxy/ipvs/proxier.go]: fully static -> fully statically

Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: :heavy_check_mark:

Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: will wait other reviews until submitting one more commit

**Comment by rikatz** [comment]
@andrewsykim friendly ping :)

File: pkg/proxy/ipvs/proxier.go [hunk 3]
```diff
@@ -577,24 +577,40 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 	}
 	ipvsModules := utilipvs.GetRequiredIPVSModules(kernelVersion)
 
+	var bmods []string
+
+	// Check if this is a full static Kernel to bypass the next checks
+	_, err = ioutil.ReadFile("/proc/modules")
+	if err != nil {
+		klog.Warningf("Failed to read file /proc/modules with error %v. Assuming this is a fully statically compiled Kernel", err)
+		kernelConfigFile := fmt.Sprintf("/boot/config-%s", kernelVersionStr)
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go]: Are we confident this check here works across all Linux distributions/kernels? I'm okay with the latter half of this PR where we don't re-run `modprobe` if there's already a match, but unsure about this part.

**Review by andrewsykim — COMMENTED** [review]
Thanks for the PR @rikatz, left a comment

File: pkg/proxy/ipvs/proxier.go (hunk 3 above)
Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: About the /proc/modules or about the /boot/config?

About the /boot/config no, I'm far away of being confident but. As I wrote [here](https://github.com/kubernetes/kubernetes/issues/77493#issuecomment-528419879) when I was recompiling the Kernel, I simply didn't copied the file to /boot so in my case this was missing.

On the other hand, this 'if' only exists on statically compiled Kernel (that lacks /proc/modules path) so this case might be pretty particular:

* A very specific distro with a full static kernel (something of IoT maybe?)
* A sysadmin who recompiles the kernel (as our original case/issue) that knows he needs to copy the file (and maybe we should put this into a better logging).

**Comment by rikatz** [comment]
Hi @andrewsykim just not to forget :) 

I want to discuss this one and see if we move forward into that /boot/config-$VERSION check, of if We assume that kube-proxy won't support kernels without module loading feature.

**Comment by andrewsykim** [comment]
@rikatz sorry for the delay. I haven't really seen scenarios where `/proc/modules` doesn't exist on the kernel so was doing my own research. Are we sure that `/proc/modules` doesn't exist rather than being an empty file?

File: pkg/proxy/ipvs/proxier.go [hunk 4]
```diff
@@ -577,24 +577,40 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 	}
 	ipvsModules := utilipvs.GetRequiredIPVSModules(kernelVersion)
 
+	var bmods []string
+
+	// Check if this is a full static Kernel to bypass the next checks
+	_, err = ioutil.ReadFile("/proc/modules")
+	if err != nil {
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/proxier.go]: if `err == os.ErrNotExist`?

Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: > @rikatz sorry for the delay. I haven't really seen scenarios where `/proc/modules` doesn't exist on the kernel so was doing my own research. Are we sure that `/proc/modules` doesn't exist rather than being an empty file?

Yes, pretty sure. I've done some tests with a Slackware compiled without supporting loadable modules and the /proc/modules doesn't exists.

I can simulate again here and paste the kernel config, the results just to be sure I'm not saying something wrong :)

Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]:
```
 ls -l /proc/modules
/bin/ls: cannot access '/proc/modules': No such file or directory
```
This is a Kernel configured without "Enable loadable module support"

**Comment by rikatz** [comment]
> @rikatz sorry for the delay. I haven't really seen scenarios where `/proc/modules` doesn't exist on the kernel so was doing my own research. Are we sure that `/proc/modules` doesn't exist rather than being an empty file?

Yes, pretty sure. I've done some tests with a Slackware compiled without supporting loadable modules and the /proc/modules doesn't exists.

I can simulate again here and paste the kernel config, the results just to be sure I'm not saying something wrong :)

```
ls -l /proc/modules
/bin/ls: cannot access '/proc/modules': No such file or directory
```
This is a Kernel configured without "Enable loadable module support"

File: pkg/proxy/ipvs/proxier.go (hunk 4 above)
Comment (rikatz) [reply pkg/proxy/ipvs/proxier.go]: Changed

**Comment by rikatz** [comment]
/retest

Prow really hates me

**Comment by andrewsykim** [comment]
@rikatz sorry for the delay. This looks good to me, I'm going to try to test/validate this on my end

**Comment by rikatz** [comment]
> @rikatz sorry for the delay. This looks good to me, I'm going to try to test/validate this on my end

no rush :) let me know if You need something else and I'll be glad to answer :)

**Comment by rikatz** [comment]
@andrewsykim friendly ping :)

**Comment by rikatz** [comment]
@andrewsykim congratulations for the paternity and welcome back. As I saw you got crowded of GH notifications, I'm just paging you again to see if we can continue with this PR.

Thank you!!

**Comment by krcroft** [comment]
Thanks for driving this to completion; on the home stretch.

**Comment by andrewsykim** [comment]
I haven't been able to test/validate this yet, but I think it's okay because it doesn't actually change the most common code path where /proc/modules does exist so the risk seems low. @lbernail can you give this a review as well? 

/assign @lbernail 
/approve

**Comment by andrewsykim** [comment]
Appreciate your patience on this PR @rikatz

**Comment by lbernail** [comment]
/lgtm
As discussed in the comment this will not cover the case where the kernel is statically compiled and the config file is not present but it still adds IPVS support for more use case.

I can think of two alternative approachesif we want to improve on this in the future:
- add a flag to bypass module load ("I compiled my kernel and I know what I'm doing")
- detect IPVS modules based on the sysctls present in the system. This will work for the main ipvs module (we just need to check for a `net.ipv4.vs` entry) and for the conntrack one (`net.netfilter.nf_conntrack_`) but not for schedulers

**Comment by rikatz** [comment]
OK, so this is annoying :/

Will make a retest tomorrow
