### PR TITLE
AddOrUpdateTaintOnNode: if node does not exists, return an error

### LINKED ISSUE #113239: Crash in AddOrUpdateTaintOnNode
### Which jobs are failing?

pkg/controller

### Which tests are failing?

`TestAddOrUpdateTaintOnNode` in `pkg/controller`
I transformed that testcase into a fuzz driver and tested it with [[go-fuzz](https://github.com/dvyukov/go-fuzz)](https://github.com/dvyukov/go-fuzz)
It crash with "invalid memory address or nil pointer dereference" when some argument related data are fuzzed.

### Since when has it been failing?

Always

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

Simplified PoC code is here:

```go
	var1 := "0k0k0"
	var2 := "k0k0"
	var3 := "k0k0k0"
	var4 := "k0k0k"
	var5 := "0k0k0k"
	var6 := "0k0k0k"

	test := struct {
		name           string
		nodeHandler    *testutil.FakeNodeHandler
		nodeName       string
		taintsToAdd    []*v1.Taint
		expectedTaints []v1.Taint
		requestCount   int
	}{

		name: "add one taint on node",
		nodeHandler: &testutil.FakeNodeHandler{
			Existing: []*v1.Node{
				{
					ObjectMeta: metav1.ObjectMeta{
						Name: var1,
					},
					Spec: v1.NodeSpec{
						Taints: []v1.Taint{
							{Key: var2, Value: var3, Effect: "NoSchedule"},
						},
					},
				},
			},
			Clientset: fake.NewSimpleClientset(&v1.PodList{Items: []v1.Pod{*testutil.NewPod("pod0", "node0")}}),
		},
		nodeName: var4,
		taintsToAdd: []*v1.Taint{
			{Key: var5, Value: var6, Effect: "NoExecute"},
		},
		expectedTaints: []v1.Taint{
			{Key: "key1", Value: "value1", Effect: "NoSchedule"},
			{Key: "key2", Value: "value2", Effect: "NoExecute"},
		},
		requestCount: 3,
	}

	AddOrUpdateTaintOnNode(context.TODO(), test.nodeHandler, test.nodeName, test.taintsToAdd...) //crash here
```

and it crashed as:

```
E1021 06:42:19.906034 2786422 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 13 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1739440, 0x2880820})
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001a6a20})
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1739440, 0x2880820})
	/home/gogen/.local/go/src/runtime/panic.go:1038 +0x215
k8s.io/kubernetes/pkg/util/taints.AddOrUpdateTaint(0x0, 0xc0001edc00)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/pkg/util/taints/taints.go:243 +0x7e
k8s.io/kubernetes/pkg/controller.AddOrUpdateTaintOnNode.func1()
	/home/gogen/workspace/gowork/src/topproj/kubernetes/pkg/controller/controller_utils.go:1056 +0x1b7
k8s.io/client-go/util/retry.OnError.func1()
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/client-go/util/retry/util.go:51 +0x33
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x40eeb4, 0xc00089d8f8})
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1b59870, 0xc0001c0008}, 0x18)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 +0x7c
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x17f9b00)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:226 +0x39
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x5f5e100, 0x0, 0x3ff0000000000000, 0x5, 0x0}, 0x40f207)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421 +0x5f
k8s.io/client-go/util/retry.OnError({0x5f5e100, 0x0, 0x3ff0000000000000, 0x5, 0x0}, 0x19f6250, 0xc0003128a0)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/client-go/util/retry/util.go:50 +0xf1
k8s.io/client-go/util/retry.RetryOnConflict(...)
	/home/gogen/workspace/gowork/src/topproj/kubernetes/vendor/k8s.io/client-go/util/retry/util.go:104
k8s.io/kubernetes/pkg/controller.AddOrUpdateTaintOnNode({0x1b59870, 0xc0001c0008}, {0x1bac458, 0xc0001c82c0}, {0x193d510, 0x5}, {0xc000695ae0, 0x1, 0x1})
	/home/gogen/workspace/gowork/src/topproj/kubernetes/pkg/controller/controller_utils.go:1037 +0x208
k8s.io/kubernetes/pkg/controller.FuzzTestAddOrUpdateTaintOnNode({0x199a51a, 0xc000614f60, 0x48bb57})
	/home/gogen/workspace/gowork/src/topproj/kubernetes/pkg/controller/controller_utils_test.go_TestAddOrUpdateTaintOnNode_test.go:259 +0x4af
```

### 

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- @secsys-go  uses [go-fuzz](https://github.com/dvyukov/go-fuzz) to find this problem.
- However, this nil pointer is never reported by end users which means that before we call AddOrUpdateTaintOnNode, the node existence is checked. 

So I think this should be a low priority.
/priority backlog

To make the code more stable, fixing it is valid. This would avoid future bugs if somewhere calls `AddOrUpdateTaintOnNode` without checking whether the node exists.

#### Which issue(s) this PR fixes:

Fixes #113239

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

File: pkg/controller/controller_utils.go [hunk 1]
```diff
@@ -1048,6 +1048,9 @@ func AddOrUpdateTaintOnNode(ctx context.Context, c clientset.Interface, nodeName
 		if err != nil {
 			return err
 		}
+		if oldNode == nil {
```
Comment (andrewsykim) [inline pkg/controller/controller_utils.go:1051]: err in line 1048 would be non-nil and return when node doesn't exist

Comment (pacoxu) [reply pkg/controller/controller_utils.go]: Got it. The problem is not here. 

https://github.com/kubernetes/kubernetes/blob/ccf57ba09dafa94906310059e42a6b896c0eaf44/pkg/controller/testutil/test_utils.go#L136-L156

The fake node handler should behave like the real server. It should return some errors when getting a node that does not exist.

Updated.

File: pkg/controller/testutil/test_utils.go [hunk 2]
```diff
@@ -152,7 +152,7 @@ func (m *FakeNodeHandler) Get(ctx context.Context, name string, opts metav1.GetO
 			return &nodeCopy, nil
 		}
 	}
-	return nil, nil
+	return nil, fmt.Errorf("node %s does not exist", name)
```
Comment (andrewsykim) [inline pkg/controller/testutil/test_utils.go:155]: Use NewNotFound https://github.com/kubernetes/apimachinery/blob/master/pkg/api/errors/errors.go#L144

Comment (pacoxu) [reply pkg/controller/testutil/test_utils.go]: Updated. Thanks for your review.

**Comment by pacoxu** [comment]
/remove-lifecycle stale
@andrewsykim do you have time to take a look again? 
/assign @kow3ns @janetkuo

**Comment by dims** [comment]
/approve

thanks @pacoxu
