### PR TITLE
Lazily initialize signal handling for hyperkube apiserver and kubelet

### LINKED ISSUE #72029: Hyperkube sigterm not working for kube-proxy, kube-controller-manager, kube-scheduler
**What happened**:
The signal SIGTERM has no effect for `hyperkube kube-proxy`, `hyperkube kube-controller-manager`, `hyperkube kube-scheduler`.

**What you expected to happen**:
Same behavior for all the components, sending SIGTERM once shuts down the components correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Start `hyperkube kube-proxy`, press Ctrl-C, doesn't work, press Ctrl-C again kills the process. Start `hyperkube kubelet`, press Ctrl-C stops the process immediately.

**Anything else we need to know?**:
For `hyperkube kubelet`, `hyperkube kube-apiserver` it seems to work fine. Sending the signal twice works as well, probably with panic.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.4, 1.12.3
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Redhat 7
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: Manual, Systemd
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by S-Chan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:
https://github.com/kubernetes/kubernetes/pull/63859/files#diff-dfaeb837c577bcd60dd9105c43427a35R52 initializes signal handling for all hyperkube commands. The function returns a stopCh that can be used by subcommands (e.g. apiserver, kubelet). However, not all subcommands make use of the stopCh. These subcommands (kube proxy, controller manager, etc) then require sending SIGTERM/SIGINT twice before exiting. Instead, we can initialize signal handling when the subcommand is actually run.

**Which issue(s) this PR fixes**:

Fixes #72029

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Signal handling is initialized within hyperkube commands that require it (apiserver, kubelet)
```

### CODE REVIEW

**Comment by S-Chan** [comment]
Signed the CLA

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Just for discussion - thoughts on if there would be a good way to unit test this? I feel like a full e2e test is overkill, but it would be interesting to think about how much lift it would be to write a unit test.

But also, I'm not sure how much that often happens for Kubernetes `cmd`.

**Comment by S-Chan** [comment]
Thanks @mattjmcnaughton for the review!

I feel like it's hard to avoid writing an integration test (maybe overkill) or testing implementation details for this fix. Definitely open to suggestions though.

**Comment by mattjmcnaughton** [comment]
On Thu, Apr 18, 2019 at 12:18:24PM -0700, Stephen Chan wrote:
> Thanks @mattjmcnaughton for the review!
> 
> I feel like it's hard to avoid writing an integration test (maybe overkill) or testing implementation details for this fix. Definitely open to suggestions though.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/76659#issuecomment-484650484

Yeah, tbh I'm not positive what is the best practice here - I defer to other
members of the community :)

**Comment by roycaihw** [comment]
/lgtm

I'm not sure about test convention for cmd

File: cmd/hyperkube/main.go [hunk 1]
```diff
@@ -84,11 +84,11 @@ func commandFor(basename string, defaultCommand *cobra.Command, commands []func(
 }
 
 // NewHyperKubeCommand is the entry point for hyperkube
-func NewHyperKubeCommand(stopCh <-chan struct{}) (*cobra.Command, []func() *cobra.Command) {
+func NewHyperKubeCommand() (*cobra.Command, []func() *cobra.Command) {
 	// these have to be functions since the command is polymorphic. Cobra wants you to be top level
 	// command to get executed
 	apiserver := func() *cobra.Command {
-		ret := kubeapiserver.NewAPIServerCommand(stopCh)
+		ret := kubeapiserver.NewAPIServerCommand(server.SetupSignalHandler)
```
Comment (mikedanese) [inline cmd/hyperkube/main.go]: Just call `kubeapiserver.NewAPIServerCommand(server.SetupSignalHandler)` here and don't modify the other files? You'll get your laziness without mucking with the signatures of the other app packages.

**Comment by sttts** [comment]
Why don't we move the SetupSignalHandler call into the commands themselves? Having this indirectional looks complex and it's not even used if I have not missed anything.

File: cmd/hyperkube/main.go (hunk 1 above)
Comment (S-Chan) [reply cmd/hyperkube/main.go]: Do you mean `kubeapiserver.NewAPIServerCommand(server.SetupSignalHandler())`? This can't be done as all command functions are called during `commandFor`.

**Comment by S-Chan** [comment]
@sttts thanks for the suggestion, I've moved SetupSignalHandler into kubelet and apiserver.

**Comment by mikedanese** [comment]
/approve

Needs a rebase.
