### PR TITLE
Fix TestUnreservePlugin flake

### LINKED ISSUE #79166: pull-kubernetes-integration#TestUnreservePlugin fails frequently
**Which jobs are failing**:

pull-kubernetes-integration

**Which test(s) are failing**:

TestUnreservePlugin

**Since when has it been failing**:

It happens frequently this week

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79164/pull-kubernetes-integration/1141308395165323264/

**Reason for failure**:

I0619 11:55:31.165887  109629 wrap.go:47] PUT /api/v1/namespaces/default/endpoints/kubernetes: (2.062872ms) 200 [scheduler.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:54252]
framework_test.go:577: test #3: Expected the unreserve plugin to be called 2 times, was called 1 times.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by alenkacz**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Fixes flakiness in TestUnreservePlugin.
For that particular test we wait for `waitForPodUnschedulable` and then assert that `unresPlugin.numUnreserveCalled != pbdPlugin.numPrebindCalled` but this assert happens asynchronously and in the meantime the pod could have been already rescheduled and prebind might have been called more times than unreserve.

This PR simplifies the test by letting it pass when unreserve was hit *AT LEAST ONCE*. That should be enough to cover the scenario.

**Which issue(s) this PR fixes**:

Fixes #79166

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling
cc. @bsalamat @draveness

### CODE REVIEW

File: test/integration/scheduler/framework_test.go [hunk 1]
```diff
@@ -581,8 +581,8 @@ func TestUnreservePlugin(t *testing.T) {
 				if err = waitForPodUnschedulable(cs, pod); err != nil {
 					t.Errorf("test #%v: Didn't expected the pod to be scheduled. error: %v", i, err)
 				}
-				if unresPlugin.numUnreserveCalled == 0 || unresPlugin.numUnreserveCalled != pbdPlugin.numPrebindCalled {
-					t.Errorf("test #%v: Expected the unreserve plugin to be called %d times, was called %d times.", i, pbdPlugin.numPrebindCalled, unresPlugin.numUnreserveCalled)
+				if unresPlugin.numUnreserveCalled < 1 {
```
Comment (ahg-g) [inline test/integration/scheduler/framework_test.go]: I don't think this is the right fix. 

The problem is that the tests in this file modify some shared state (the members in TesterPlugin above). What we need to do is reset this state for every test. As a quick fix, you can reset pbdPlugin.numPrebindCalled and unresPlugin.numUnreserveCalled to zero at the beginning of the for loop. 

But what we should really be doing is refactor this whole file to ensure that each test starts from a clean state to make sure that this doesn't happen again in the future.

Comment (alenkacz) [reply test/integration/scheduler/framework_test.go]: It does the reset here https://github.com/kubernetes/kubernetes/pull/79371/files#diff-f6b72dfe2b2c2cee201d12156e80366fL596 and the tests don't run in parallel...

I agree with the proposed refactoring, I still feel like this is the right fix at this point :)

Comment (ahg-g) [reply test/integration/scheduler/framework_test.go]: > It does the reset here https://github.com/kubernetes/kubernetes/pull/79371/files#diff-f6b72dfe2b2c2cee201d12156e80366fL596 

reset() should be called at the beginning, not the end.

> and the tests don't run in parallel...

The tests don't run in parallel, but they may run in different order. 

> 
> I agree with the proposed refactoring, I still feel like this is the right fix at this point :)

I don't think it is, we should expect bind and unreserve plugins to be executed the same number of times.

Comment (ahg-g) [reply test/integration/scheduler/framework_test.go]: The problem is that TestPrebindPlugin does not reset the counter. But a test shouldn't be relying on another, so the right fix is for this test to make sure the state it relies on is reset before it runs.

Comment (ahg-g) [reply test/integration/scheduler/framework_test.go]: on a closer look, I think you are right that we can't guarantee that they are equal because the scheduler and the test are running in parallel; what we can guarantee is that prebind counter is at most off by one :)

I still think that we have a bigger problem that the tests modify shared state and rely on each other to make sure the state is reset. 

For now, in addition to the modification you did, I would suggest that you also reset the prebind counter in TestPrebindPlugin.

Comment (alenkacz) [reply test/integration/scheduler/framework_test.go]: @ahg-g what about the race I described? I saw that in logs...

we wait for pod being unschedulable
that happens, the pod goes back to scheduling queue
then we check (at later time) that those two numbers (prebind, unreserve) equal...
but in the meantime, the pod got rescheduled and the prebind was executed, but not the unreserve one (YET)

Comment (alenkacz) [reply test/integration/scheduler/framework_test.go]: oh you replied in the meantime, good 👍 

sure I can do that! And I can work on the refactoring after if no one else is working on that

Comment (alenkacz) [reply test/integration/scheduler/framework_test.go]: @ahg-g added the reset to the other test. You can re-review

File: test/integration/scheduler/framework_test.go [hunk 2]
```diff
@@ -581,8 +582,8 @@ func TestUnreservePlugin(t *testing.T) {
...
```
Comment (Huang-Wei) [inline test/integration/scheduler/framework_test.go]: Can `unresPlugin.numUnreserveCalled` be negative? If not, I'd say `if unresPlugin.numUnreserveCalled == 0` makes more sense.

Comment (alenkacz) [reply test/integration/scheduler/framework_test.go]: fixed @Huang-Wei

**Comment by alenkacz** [comment]
@ahg-g @Huang-Wei in the meantime, this got merged https://github.com/kubernetes/kubernetes/commit/40090e85634d6d18453ec356e3435d1993e72e12#diff-f6b72dfe2b2c2cee201d12156e80366f so the reset for prebind is already in place. I removed it from this PR. Please re-review

**Comment by Huang-Wei** [comment]
@alenkacz please squashed into one commit and it'd good to be merged then.

**Comment by alenkacz** [comment]
@Huang-Wei should be ready

**Comment by alenkacz** [comment]
/remove-sig api-machinery apps architecture auth cli cloud-provider cluster-lifecycle contributor-experience instrumentation network node storage

**Comment by alenkacz** [comment]
/remove-area apiserver cloudprovider code-generation conformance dependency e2e-test-framework kubeadm kubectl kubelet release-eng
