### PR TITLE
Sync node status during kubelet node shutdown

### LINKED ISSUE #98004: GracefulNodeShutdown rescheduled to the node of shutdown state
**What happened**:

A node is in shutdown state. all the pods are down, but the pods are rescheduled to this node.

**What you expected to happen**:

No new pod will be scheduled to the node of shutdown state.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
Fix rescheduled to the node of shutdown state

**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #98004

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Sync node status during kubelet node shutdown.
Adds an pod admission handler that rejects new pods when the node is in progress of shutting down.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wzshiming** [comment]
@mrunalp @Random-Liu  @derekwaynecarr PTAL

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 1]
```diff
@@ -31,6 +31,7 @@ import (
 	"k8s.io/klog/v2"
 	"k8s.io/kubernetes/pkg/features"
 	"k8s.io/kubernetes/pkg/kubelet/eviction"
+	"k8s.io/kubernetes/pkg/kubelet/lifecycle"
```
Comment (ehashman) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:34]: Since the dependencies changed, you need to run the update-bazel.sh script. This is why the tests are failing.

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 2]
```diff
@@ -76,14 +78,31 @@ type Manager struct {
...
+	m.nodeShuttingDownMutex.Lock()
+	defer m.nodeShuttingDownMutex.Unlock()
+
+	if !m.nodeShuttingDownNow {
+		return lifecycle.PodAdmitResult{Admit: true}
+	}
+	return lifecycle.PodAdmitResult{
+		Admit:   false,
+		Reason:  nodeShutdownReason,
+		Message: nodeShutdownMessage,
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:104]: `nodeShutdownMessage` is defined as `Node is shutting, evicting pods` which doesn't seem appropriate as the admission message. 

How about defining a new message, maybe something like `Node is in progress of shutting down; not admitting any new pods`

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 3]
```diff
@@ -158,6 +177,9 @@ func (m *Manager) Start() error {
 				m.nodeShuttingDownMutex.Unlock()
 
 				if isShuttingDown {
+					// Update node state to avoid rescheduling to the current node
+					m.syncNodeStatus()
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:181]: This looks like it's a blocking call (i.e. it will block until the node is able to update the status to the api-server). 

I think we should avoid blocking here because if the shutdown is imminent (e.g. say in next 20secs), and we block until we receive response from api-server, we're wasting time that could be spent shutting down pods. 

Maybe we can run this in the background, i.e. `go m.syncNodeStatus()`? Would that work?

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -821,7 +821,11 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
 		v1.NamespaceNodeLease,
 		util.SetNodeOwnerFunc(klet.heartbeatClient, string(klet.nodeName)))
 
-	klet.shutdownManager = nodeshutdown.NewManager(klet.GetActivePods, killPodNow(klet.podWorkers, kubeDeps.Recorder), kubeCfg.ShutdownGracePeriod.Duration, kubeCfg.ShutdownGracePeriodCriticalPods.Duration)
+	// setup node shutdown manager
+	shutdownManager, shutdownAdmitHandler := nodeshutdown.NewManager(klet.GetActivePods, killPodNow(klet.podWorkers, kubeDeps.Recorder), klet.syncNodeStatus, kubeCfg.ShutdownGracePeriod.Duration, kubeCfg.ShutdownGracePeriodCriticalPods.Duration)
+
+	klet.shutdownManager = shutdownManager
+	klet.softAdmitHandlers.AddPodAdmitHandler(shutdownAdmitHandler)
```
Comment (bobbypage) [inline pkg/kubelet/kubelet.go:828]: curious why `klet.softAdmitHandlers` is used here, instead of `klet.admitHandlers`?

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 5]
```diff
@@ -76,14 +78,31 @@ type Manager struct {
...
+		syncNodeStatus:                  syncNodeStatus,
 		shutdownGracePeriodRequested:    shutdownGracePeriodRequested,
 		shutdownGracePeriodCriticalPods: shutdownGracePeriodCriticalPods,
 		clock:                           clock.RealClock{},
 	}
+	return manager, manager
+}
+
+// Admit rejects all pods if node is shutting
+func (m *Manager) Admit(attrs *lifecycle.PodAdmitAttributes) lifecycle.PodAdmitResult {
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:94]: can we please add a unit test that expires this functionality and tests:

1. pods are not admitted when `nodeShuttingDownNow == true`
2. pods are admitted when `nodeShuttingDownNow == false`

**Comment by bobbypage** [comment]
Thanks for working on this. 

For background, currently, when the node is shutting down, the status of the node will be updated to `NotReady` since the `nodestatus.ReadyCondition` takes into account `kl.shutdownManager.ShutdownStatus`

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/kubelet_node_status.go#L608

where `ShutdownStatus` checks if the node is currently shutting down:

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L181-L193

However, the issue with this is the node status will only be updated periodically, i.e. every `nodeStatusUpdateFrequency`

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/kubelet.go#L1394

which is set to 10seconds by default:

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/apis/config/v1beta1/defaults.go#L125-L127

As a result, it means there can be some delay between when the shutdown first occurs and when the kubelet will sync it's node status. I think having the kubelet explicitly sync it's status when the shutdown happens as you proposed here makes sense.

**Comment by wzshiming** [comment]
@bobbypage Thanks, updated.

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 6]
```diff
@@ -76,14 +79,31 @@ type Manager struct {
...
+	m.nodeShuttingDownMutex.Lock()
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:96]: instead of reading `nodeShuttingDownNow` directly here and dealing with the mutex, I would instead use `ShutdownStatus()` function which already takes care of locking mutex and returning the correct result. It also has a short circuit check if the the feature gate is disabled.

Something like:

```
nodeShuttingDown := m.ShutdownStatus() != nil

if nodeShuttingDown  {
    return lifecycle.PodAdmitResult{
		  Admit:   false,
		  Reason:  nodeShutdownReason,
		  Message: nodeShutdownNotAdmitMessage,
	}
}
return lifecycle.PodAdmitResult{Admit: true}
```

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 7]
```diff
@@ -158,6 +178,9 @@ func (m *Manager) Start() error {
 				m.nodeShuttingDownMutex.Unlock()
 
 				if isShuttingDown {
+					// Update node state to avoid rescheduling to the current node
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:181]: nit: Reword the comment `Update node status and ready condition`

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_others.go [hunk 8]
```diff
@@ -22,14 +22,21 @@ import (
...
 
 // NewManager returns a fake node shutdown manager for non linux platforms.
-func NewManager(getPodsFunc eviction.ActivePodsFunc, killPodFunc eviction.KillPodFunc, shutdownGracePeriodRequested, shutdownGracePeriodCriticalPods time.Duration) *Manager {
-	return &Manager{}
+func NewManager(getPodsFunc eviction.ActivePodsFunc, killPodFunc eviction.KillPodFunc, syncNodeStatus func(), shutdownGracePeriodRequested, shutdownGracePeriodCriticalPods time.Duration) (*Manager, lifecycle.PodAdmitHandler) {
+	m := &Manager{}
+	return m, m
+}
+
+// Admit rejects all pods if node is shutting
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_others.go:37]: nit: update comment to reflect this is a "fake"

```
// Admit returns a fake Pod admission which always returns true
```

**Comment by bobbypage** [comment]
thanks for the fixes, left a few small couple nits.

Can you please retitle this PR / commit as it's the current title is a bit confusing. 

Maybe something along the lines of `Sync node status during kubelet node shutdown` and a note that this PR also adds an pod admission handler that rejects new pods when the node is in progress of shutting down. Thanks again!

**Comment by wzshiming** [comment]
@bobbypage Done.

**Comment by bobbypage** [comment]
thanks!

/lgtm
/assign @mrunalp
