### PR TITLE
Fix non-semantic apply requests to ignore empty maps

### LINKED ISSUE #124050: Server-side apply has trouble with empty map
### What happened?

Every time I server-side apply a `Deployment` with `spec.template.metadata.annotations: {}`, the `resourceVersion` updates. Nothing about my manifest changes between applies; if I map `annotations` to the empty map, `kubectl apply --server-side` the same manifest updates the `resourceVersion`. With client-side apply, the `resourceVersion` stays the same as long as my manifest remains constant, even if `annotations: {}`.

I read in #70281 that Kubernetes should treat absent keys, empty values (in this case, an empty map), and `null` values the same. I observe that leaving the `annotations` key out and `annotations: null` behave as expected, not modifying the `Deployment` and leaving `resourceVersion` the same, but empty map `{}` behaves as described above.

If we cannot change this behavior, I'd at least like to understand the rationale behind it.

### What did you expect to happen?

I expected my `Deployment` object to stay the same between identical server-side applies, where the manifest file content was exactly the same, regardless of the value of `spec.template.metadata.annotations`. A different `resourceVersion` every apply indicates that the object was event type `MODIFIED`. I expect no events to fire on applying the same manifest.

### How can we reproduce it (as minimally and precisely as possible)?

1. Say `deployment.yaml` contains https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment. In actuality, any `Deployment` is fine.
2. Add `spec.template.metadata.annotatations: {}`.
3. `kubectl apply --server-side deployment.yaml`
4. `kubectl get deployment nginx-deployment -o yaml`

Every successive repeat of steps 3-4 should show different `metadata.resourceVersion` values.

Example of `Deployment` with `spec.template.metadata.annotatations: {}`:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations: {}
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

### Anything else we need to know?

This is especially a problem when I server-side apply with code in my operator. My operator is built on https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern and watches changes to the child objects it deploys. If I create a `Deployment` with `spec.template.metadata.annotations: {}`, the operator constantly reconciles because every server-side apply of the manifest registers as a type `MODIFIED` event on the object, which triggers the watching operator to reconcile.

### Kubernetes version

```console
$ kubectl version --short
Client Version: v1.27.11
Kustomize Version: v5.0.1
Server Version: v1.27.8-gke.1067004
```

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
ID=debian
$ uname -a
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jpbetz**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #124050

#### Special notes for your reviewer:

Are there cases for builtin types where we shouldn't treat `nil` and `{}` as equivalent for purposes of detecting if an apply is a nop?

#### Does this PR introduce a user-facing change?

```release-note
Fix bug where Server Side Apply causing spurious resourceVersion bumps on no-op patches containing empty maps.
```

### CODE REVIEW

**Comment by jpbetz** [comment]
@alexzielenski @apelisse Can you point out any counter examples where this fix wouldn't work?  I'm leaving this as draft while I try to hunt problem cases down..

**Comment by jpbetz** [comment]
cc @sttts

File: test/integration/apiserver/apply/apply_test.go [hunk 1]
```diff
@@ -244,6 +244,117 @@ func TestNoOpUpdateSameResourceVersion(t *testing.T) {
...
+		Name(deploymentName).
+		Body(deploymentBytes).
+		Do(context.TODO()).
+		Get()
+	if err != nil {
+		t.Fatalf("Failed to create object: %v", err)
+	}
+
+	// Sleep for one second to make sure that the times of each update operation is different.
+	time.Sleep(1 * time.Second)
```
Comment (sttts) [inline test/integration/apiserver/apply/apply_test.go:303]: not necessary here, is it?

Comment (jpbetz) [reply test/integration/apiserver/apply/apply_test.go:303]: Unfortunately it is..  The timestamp is 1s granularity, and results in this test flaking if we don't to a sleep. The other tests for nops are also doing this wait..

Comment (sttts) [reply test/integration/apiserver/apply/apply_test.go:303]: Ack. Maybe worth to mention: "This is necessary to trigger the bug."

Comment (jpbetz) [reply test/integration/apiserver/apply/apply_test.go:304]: SG, I've expanded the comment to spell it out.  We could avoid this with a fake clock, but for now, this should should hold up.

Comment (neolit123) [reply test/integration/apiserver/apply/apply_test.go:304]: > // This sleep is necessary to trigger the bug consistently because the time field in managedFields has
> // 1 second granularity and if both apply requests happen during the same second, this test would flake.

ideally, this should reference a ticket or describe "the bug" in question.

not sure i understand the quantization of the managed field in question here, but is it sufficient to just delay the second call by 1 second so that they are not within one second? what if the CI setup is slow and it ends up being exactly 2 seconds. would that flake?

File: test/integration/apiserver/apply/apply_test.go [hunk 2]
```diff
@@ -244,6 +244,118 @@ func TestNoOpUpdateSameResourceVersion(t *testing.T) {
...
+		}
+	}`)
+
+	_, err := client.AppsV1().RESTClient().Patch(types.ApplyPatchType).
+		Namespace("default").
+		Param("fieldManager", "apply_test").
+		Resource(deploymentsResource).
+		Name(deploymentName).
+		Body(deploymentBytes).
+		Do(context.TODO()).
```
Comment (neolit123) [inline test/integration/apiserver/apply/apply_test.go:296]: tests should use Background unless the TODO is relevant and there is a plant to switch to a specific context which is not clear ATM.

File: test/integration/apiserver/apply/apply_test.go [hunk 3]
```diff
@@ -244,6 +244,118 @@ func TestNoOpUpdateSameResourceVersion(t *testing.T) {
...
+	}
+
+	// Test that we can apply the same object and don't change the RV
+	_, err = client.AppsV1().RESTClient().Patch(types.ApplyPatchType).
+		Namespace("default").
+		Param("fieldManager", "apply_test").
+		Resource(deploymentsResource).
+		Name(deploymentName).
+		Body(deploymentBytes).
+		Do(context.TODO()).
```
Comment (neolit123) [inline test/integration/apiserver/apply/apply_test.go:328]: same

File: test/integration/apiserver/apply/apply_test.go (hunk 1 above)
Comment (jpbetz) [reply test/integration/apiserver/apply/apply_test.go:304]: Rephrasing this as: 

```
// This sleep is necessary to consistently produce different timestamps because the time field in managedFields has
// 1 second granularity and if both apply requests happen during the same second, this test would flake.
```

No, 2 seconds wouldn't flake. The only thing that needs to happen to prevent flakes is prevent the two apply requests from being stamped with the same exact timestamp.  Since the timestamps have 1s granularity, this should be sufficient (modulo any non-contentiousness in clocks).

File: test/integration/apiserver/apply/apply_test.go (hunk 2 above)
Comment (jpbetz) [reply test/integration/apiserver/apply/apply_test.go:296]: I don't disagree, but this was copy-pasted from adjacent tests, so this is consistent with the surrounding code.

Note that the defacto situation in the code base is:

```
g grep context.TODO | grep _test | wc -l
2581
g grep context.Background | grep _test | wc -l
1073
```

Can we stick with TODO for now and if anyone wants to make this a convention, take it on a separate project?

Comment (neolit123) [reply test/integration/apiserver/apply/apply_test.go:296]: don't mind, up to you as OWNERS.
it's just what golang recommends.

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by jpbetz** [comment]
The main risk to this change would be if there exists a map in builtin types where the difference between `nil` and `{}` matters.  We use very few maps in builtin types (preferring slices with listType=map).  So I did an additional sanity check: `git grep 'map\[' '**/types.go' | grep "json"`, which doesn't show any maps without `omitempty`.

**Comment by sttts** [comment]
Would like to see this backported to stable releases. It currently breaks SSA-based controllers to work sensibly.

**Comment by liggitt** [comment]
> Are there cases for builtin types where we shouldn't treat nil and {} as equivalent for purposes of detecting if an apply is a nop?

yes, empty marker structs like "subresources" and "emptyDir" … didn't scan all the discussion yet but did those get considered?


/hold

**Comment by jpbetz** [comment]
> yes, empty marker structs like "subresources" in CRDs and "emptyDir" in pods … didn't scan all the discussion yet but did those get considered?

This fix doesn't touch CRDs but "emptyDir" in pods sounds like a problem case. Thanks for flagging. I'll do another sweep.

**Comment by jpbetz** [comment]
> > yes, empty marker structs like "subresources" in CRDs and "emptyDir" in pods … didn't scan all the discussion yet but did those get considered?
> 
> This fix doesn't touch CRDs but "emptyDir" in pods sounds like a problem case. Thanks for flagging. I'll do another sweep.

OK, this does look safe. The equateNilAndEmpty only applies to maps, not structs: https://github.com/kubernetes/kubernetes/blob/a4819996a860066dfba5383e4fb6db2a243ad03e/staging/src/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go#L204-L212

I've also added test case for pod emptyDir. The test passes both before and after applying this change.

(Note also that this change only applies to structured types, not unstructured)

**Comment by jpbetz** [comment]
> I think it is interesting that successive applications of the same patch on an object is not idempotent in the first place - perhaps `nil/empty` is a special case, but my gut tells me adding special logic to ignore it in this deepequal check may be patching the sympton rather than the cause.

I think it is.  Note that this particular PR _disables_ the special logic for CRDs. So I it's movement in the right direction.. it's simplifying the logic, at least for CRDs.

> 
> This case is reminding me of this bug: [kubernetes-sigs/structured-merge-diff#259](https://github.com/kubernetes-sigs/structured-merge-diff/pull/259)
> 
> My initial theory as to a cause could be:
> 
> 1. `annotations: {}` in a patch is yielding `annotations: nil` due to the above bug
> 2. Object is marshalled into the store etcd store and synced back to the apiserver cache
> 3. Between marshalling and unmarshalling again as old for a new patch, something causes `annotations: nil` to become `annotations: {}`, which still compares as unequal another `annotations: nil` patch.
> 
> Do you know which of the new/old is empty vs. nil for this case?

Right, and I don't know how much better we're going to be able to do for proto encoded built-in types given that proto can't distinguish between a nil map and an empty map.

**Comment by jpbetz** [comment]
/hold cancel
Added test to verify that distinguishes between maps and structs correctly.
