### PR TITLE
Remove AppArmor loaded profile validation

### LINKED ISSUE #97273: Inconsistent behaviour of init containers when Pod has invalid security profiles (apparmor vs seccomp)
**What happened**:

Pods with invalid container-level seccomp profiles allow its init containers to be executed. Pods with unloaded apparmor profiles blocks the entire pod.

**What you expected to happen**:

Consistency between both. In one hand AppArmor blocks all pod execution regardless of the containers having or not a profile attached to it. On the other, Seccomp allows for an init container to deploy its own profile - as currently done on [kubernetes-sigs/security-profiles-operator](https://github.com/kubernetes-sigs/security-profiles-operator).

**How to reproduce it (as minimally and precisely as possible)**:

Apply the yaml below:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: apparmor-sample
  namespace: default
  annotations:
    container.apparmor.security.beta.kubernetes.io/container-with-apparmor: localhost/non-existent-profile
spec:
  initContainers:
    - name: init-test
      image: alpine
      command: [echo, "the init container was executed!"]
  containers:
    - name: container-without-apparmor
      image: alpine
    - name: container-with-apparmor
      image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-sample
  namespace: default
spec:
  initContainers:
    - name: init-test
      image: alpine
      command: [echo, "the init container was executed!"]
  containers:
    - name: container-without-seccomp
      image: alpine
    - name: container-with-seccomp
      image: alpine
      securityContext:
        seccompProfile:
          type: Localhost
          localhostProfile: non-existent-profile.json
```

Resulting in only the init container from the `seccomp-sample` being executed:
image

**Anything else we need to know?**:

AppArmor is currently being target to GA on 1.21 (https://github.com/kubernetes/enhancements/pull/1444). 

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-alpha.0.292+87984d84d18c78", GitCommit:"87984d84d18c7816835e5efedebb17ed13aa2509", GitTreeState:"clean", BuildDate:"2020-12-12T23:13:21Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.5 LTS`
- Kernel (e.g. `uname -a`):
`Linux XXXXXX 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
/area security

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

In general it could be possible that unconfined init containers deploy
security profiles. The existing AppArmor pre-validation would block the
complete workload without this patch being applied. If we now schedule a
workload which contains an unconfined init container, then we will skip
the validation. The underlying container runtime will fail if the
profile is not available after the execution of the init container.

This synchronizes the overall behavior with seccomp.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/97273

**Special notes for your reviewer**:

/cc @pjbgf 

**Does this PR introduce a user-facing change?**:

```release-note
Removed validation if AppArmor profiles are loaded on the local node. This should be handled by the
container runtime.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by pjbgf — APPROVED** [review]
that was a quick turn around @saschagrunert, really good stuff! :+1: 

/lgtm

**Comment by saschagrunert** [comment]
@ehashman who from SIG node could approve this one for us, too? :upside_down_face:

**Comment by ehashman** [comment]
/assign @dchen1107 

you could also poke anyone else on the OWNERS file

**Comment by saschagrunert** [comment]
PTAL @brendandburns @lavalamp @smarterclayton

**Comment by lavalamp** [comment]
You need someone from SIG Node and SIG Auth to sign off on this.

**Comment by deads2k** [comment]
This appears to allow a case of someone not specifying a profile for an init container to run without any enforcement.  The distinction that allows an init container to run without a profile while (presumeably) disallowing a comparable non-init container isn't obvious to me since the pod creator gets to choose in both cases.

Even if an ubuntu expert gives input that this is ok, I'd like to see that distinction explained in the comments of this method.

**Comment by setharnold** [comment]
Hello, I'm unfamiliar with Kubernetes, so forgive me if I'm entirely off base with my questions and comments.

So, I'll start by summarizing what I think I'm reading here, as a way to frame my assumptions:

- Kubernetes' AppArmor integration will fail to execute a workload if the administrator has asked for a specific profile to be used and then fails to provide the profile itself (aka fail-safe).
- Kubernetes' Seccomp integration will execute a workload if the administrator has asked for a specific profile to be used and then fails to provide the profile itself (aka fail-open).
- Kubernetes can supply AppArmor policy from "outside", what one might call the hypervisor if these were managed VMs rather than namespaces.
- A container can supply AppArmor policy from "inside", what one might call the guest if these were VMs.

Where I'm confused in this is what the goal is -- is the goal to change from a fail-safe to a fail-open approach in the event the administrator's requested policy is not available?

Or is the goal to change to a fail-open approach if the container supplies its own AppArmor policy in some fashion?

I dislike fail-open designs: if I ask a service to enforce a security policy, I want the service to either enforce the policy or tell me that it cannot. I don't want the service to carry on as if nothing has happened.

I dislike conflating the 'external' AppArmor policy that would be supplied by the container runtime environment with the 'internal' AppArmor policy that would be supplied by guest workloads. The Kubernetes policy should be loaded into its namespace, and a new AppArmor namespace created for the guest to populate itself if it has provided any. The 'external' policy feels like it would be supplied by the machine owner, to limit what containers can do, and the 'internal' policy feels like it would be supplied by the software author or maintainer, to enforce separation of their services based on their knowledge of their software's needs and requirements. As I see it, these are orthogonal needs.

I encourage fail-safe designs rather than fail-open designs.

I encourage thinking about the 'external' policy and 'internal' policy as supplied by different people to meet different goals and not consider them interchangeable.

Thanks

**Comment by saschagrunert** [comment]
Hey @deads2k @setharnold, thank you for your input and thoughts! :pray: 

The main idea behind this PR is to make the AppArmor behavior orthogonal to the seccomp one. From a use case perspective, the init container could deploy a profile, whereas the actual workload would use it.

That way we utilize the fact that the init container and the workload always run on the same node, where we could pre-check and/or guarantee that the profile is loaded on that node. In Kubernetes, the init container and the actual workload share the same Pod, which means they're fairly distinguished and only share the network and IPC namespaces.

cc @pjbgf

File: pkg/security/apparmor/validate.go [hunk 1]
```diff
@@ -78,15 +78,31 @@ func (v *validator) Validate(pod *v1.Pod) error {
...
+
 	var retErr error
 	podutil.VisitContainers(&pod.Spec, podutil.AllContainers, func(container *v1.Container, containerType podutil.ContainerType) bool {
-		retErr = validateProfile(GetProfileName(pod, container.Name), loadedProfiles)
+		profileName := GetProfileName(pod, container.Name)
+
+		// It may be possible that the init container deploys the AppArmor
+		// profile which should be used by the workload. In this case we skip
+		// further validations and let the underlying container runtime decide.
+		if containerType == podutil.InitContainers && profileName == "" {
```
Comment (sjenning) [inline pkg/security/apparmor/validate.go:90]: I think I'm with @deads2k on this.

Why is the unconfined init container special? The annotation is per-container, just as seccomp is, albiet on the `container.securityContext`.

There is no seccomp admit handler in the kubelet IIRC.  Why shouldn't we just let all non-existent profile errors fall through to the runtime and result in `CreateContainerError` like seccomp?

**Comment by pjbgf** [comment]
> This appears to allow a case of someone not specifying a profile for an init container to run without any enforcement. 

@deads2k do you mind clarifying in which scenario do you see this to be the case?
Reason being, when a profile name is not set, the container runtime's default will be used instead.
Meaning that such init container will be under an enforceable apparmor profile.

This assumes that:
- Host supports AppArmor
- AppArmor is enabled
- Runtime sets a default profile (default behaviour in `dockershim`, `CRI-O`, `LXC`)

My understanding is that, if the three assumptions above are true, a container (init or otherwise) will only run as unconfined (with or without this PR) is when it is set to `unconfined`.

File: pkg/security/apparmor/validate.go (hunk 1 above)
Comment (pjbgf) [reply pkg/security/apparmor/validate.go:90]: @sjenning I concur with the view that init containers should not be a special case. We are probably better off removing the checks against the _profile's existence_ altogether.

**Comment by pjbgf** [comment]
@setharnold I completely agree that failing-safe should be the preferred approach from a security perspective.
But there may be a mismatch in some of the assumptions. My understanding is that, if:

- a container has a custom policy attached to it
- the host and the container runtime supports the security mechanism (seccomp / apparmor)
- the custom policy does not exist

the container runtime will fail-safe and won't execute the container. The difference between them is that on AppArmor, a missing profile applied on a container fails the entire Pod.

In my view, the goal is to establish some consistancy between AppArmor and Seccomp.

So recapping, the pod below would result in the pod getting the status of `Init:Blocked`.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: apparmor-sample
  annotations:
    container.apparmor.security.beta.kubernetes.io/custom: localhost/non-existent-profile
    container.apparmor.security.beta.kubernetes.io/runtime: runtime/default
    container.apparmor.security.beta.kubernetes.io/unconfined: unconfined
spec:
  initContainers:
    - name: init-test
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "cat /proc/1/attr/current"]
  containers:
    - name: runtime
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "cat /proc/1/attr/current; sleep 30"]
    - name: unconfined
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "cat /proc/1/attr/current; sleep 30"]
    - name: custom
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "cat /proc/1/attr/current; sleep 30"]
```

With this PR, it would result in:

- `init-test` running with apparmor `runtime/default`
- `runtime` running with apparmor `runtime/default`
- `unconfined` running with apparmor disabled
- `custom` failing to start

* assumes AppArmor is supported and Kubernetes is running with dockershim.

**Comment by setharnold** [comment]
On Thu, Mar 11, 2021 at 04:28:41PM -0800, Paulo Gomes wrote:
> @setharnold I completely agree that failing-safe should be the preferred approach from a security perspective.
> But there may be a mismatch in some of the assumptions. My understanding is that, if:

Thanks Paulo for explaining where my understanding of the problem was
lacking. This is very helpful for me :) -- well, okay, I'm not currently
doing anything where this is relevant knowledge, but I like being the
person who has answers to questions, you know?

I can see benefits to both approaches. If the pod is useless because of
the one service that didn't start, the resources are probably better used
elsewhere. If the pod can continue doing the core of its job and some
ancillary function doesn't work because one service didn't start, then
it's probably better to continue on as best one can.

And doing the same thing as a similar seccomp misconfiguration makes sense to me.

I think if it were me I'd want the choice to be exposed to site operators,
but configuration complexity isn't free.

Thanks again for the explanation.

File: pkg/security/apparmor/validate.go (hunk 1 above)
Comment (saschagrunert) [reply pkg/security/apparmor/validate.go]: I agree we better remove the check if the profile exists completely.

**Comment by saschagrunert** [comment]
@sjenning I updated the PR to not check for loaded profiles any more.

**Review by pjbgf — APPROVED** [review]
/approve

**Comment by tallclair** [comment]
How do container runtimes behave if the requested profile isn't loaded?

Here is an alternative proposal:

- If the pod-wide profile (annotation) is set, then keep the current behavior (block the pod if the profile isn't loaded)
- If a per-container profile is set, then delay the validation until the container is started (optionally skip validation completely if the runtimes fail closed, per the question above)

This makes the behavior more explicit. If you want to load the profile in an init container, then don't set the profile on the init container, and just set the profile explicitly on the other containers. This would be cumbersome for pods with lots of containers, so we could maybe but a special case in when there is a pod-wide profile set, but init containers override the profile.

**Comment by saschagrunert** [comment]
> How do container runtimes behave if the requested profile isn't loaded?

They will assume that it does not exist and fail on sandbox or container creation. I think all runtimes require the profiles to be pre-loaded in memory.

> Here is an alternative proposal:
> 
> * If the pod-wide profile (annotation) is set, then keep the current behavior (block the pod if the profile isn't loaded)
> * If a per-container profile is set, then delay the validation until the container is started (optionally skip validation completely if the runtimes fail closed, per the question above)
> 
> This makes the behavior more explicit. If you want to load the profile in an init container, then don't set the profile on the init container, and just set the profile explicitly on the other containers. This would be cumbersome for pods with lots of containers, so we could maybe but a special case in when there is a pod-wide profile set, but init containers override the profile.

Thank you for the input! Do you have thoughts on that @pjbgf @sjenning?

**Comment by pjbgf** [comment]
> How do container runtimes behave if the requested profile isn't loaded?

For the runtimes I tested, they all failed closed. However, it is hard to know for sure that in the future we would not see other runtimes being sprung up with behaving differently. Having said that, I would argue that the responsibility of supporting, validating and applying such profiles is still the runtime's, and not Kubernetes'.

> Here is an alternative proposal:
> 
> * If the pod-wide profile (annotation) is set, then keep the current behavior (block the pod if the profile isn't loaded)
> * If a per-container profile is set, then delay the validation until the container is started (optionally skip validation completely if the runtimes fail closed, per the question above)
> 
> This makes the behavior more explicit. If you want to load the profile in an init container, then don't set the profile on the init container, and just set the profile explicitly on the other containers. This would be cumbersome for pods with lots of containers, so we could maybe but a special case in when there is a pod-wide profile set, but init containers override the profile.

@tallclair I would prefer your proposal to the existing behaviour. The caveats being:
1) We can't yet set pod-wide `apparmor` profile (hopefully one for the GA :crossed_fingers:)
2) It would still be a bit inconsistent with how `seccomp` works, meaning that two different workloads with similar states (profile set at pod level, having invalid profiles at container level) would lead to two different outcomes in case they are using `seccomp` or `apparmor`:

**APP ARMOR**
```
pod: valid-profile
container1: non-existent-profile
container2: not-set
```
Result: Pod blocked at creation time, no containers executed.

**SECCOMP**
```
pod: valid-profile
container1: non-existent-profile
container2: not-set
```
Result: Pod get created, but only container 2 gets executed.

I don't think that `seccomp` and `apparmor` must necessarily always behave in the same way, however, I think it would be great if some basic primitives are shared. If we are to keep the "all-or-nothing" in `apparmor`, which I can also see the benefits of, I would propose we align that with `seccomp`.

**Comment by tallclair** [comment]
Thanks @pjbgf, that all makes sense (I forgot that AppArmor doesn't have a pod-wide profile!)

As long as containerd & cri-o fail closed on a missing apparmor profile, I'm OK with this proposal. One other thing to consider in the implementation is how the error message gets surfaced to the user. Does it emit an event with a message that's adequate for identifying the missing profile?

**Comment by dims** [comment]
Looks like this is ready @saschagrunert i can approve this and leave the lgtm for @pjbgf 

/approve

**Review by pjbgf — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
/test pull-kubernetes-integration
for flake

**Comment by elfinhe** [comment]
Hi saschagrunert@, can you also update the test to fix https://github.com/kubernetes/kubernetes/issues/107342?

**Comment by saschagrunert** [comment]
> Hi saschagrunert@, can you also update the test to fix #107342?

Yes, working on a fix in https://github.com/kubernetes/kubernetes/pull/107448
