### PR TITLE
use privileged enforce level for nfs test

### LINKED ISSUE #109221: Flaky [sig-node] kubelet host cleanup with volume mounts [HostCleanup][Flaky]
##### Error text:
```
test/e2e/node/kubelet.go:421
Mar 29 00:40:32.646: Failed to create "nfs-server" pod: pods "nfs-server" is forbidden: violates PodSecurity "baseline:latest": privileged (container "nfs-server" must not set securityContext.privileged=true)
Unexpected error:
    <*errors.StatusError | 0xc000b4c820>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"nfs-server\" is forbidden: violates PodSecurity \"baseline:latest\": privileged (container \"nfs-server\" must not set securityContext.privileged=true)",
            Reason: "Forbidden",
            Details: {Name: "nfs-server", Group: "", Kind: "pods", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 403,
        },
    }
    pods "nfs-server" is forbidden: violates PodSecurity "baseline:latest": privileged (container "nfs-server" must not set securityContext.privileged=true)
occurred
test/e2e/framework/volume/fixtures.go:401
```
#### Recent failures:
[2022/4/1 10:47:37 ci-kubernetes-e2e-gci-gce-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-flaky/1509724110916161536)
[2022/4/1 10:45:36 ci-kubernetes-e2e-gci-gce-flaky-repro](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-flaky-repro/1509723607540961280)
[2022/4/1 10:38:36 ci-cri-containerd-e2e-cos-gce-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-flaky/1509721845916504064)
[2022/4/1 10:17:36 ci-kubernetes-e2e-gci-gce-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-flaky/1509716561076686848)
[2022/4/1 10:06:35 ci-kubernetes-e2e-gci-gce-flaky-repro](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-flaky-repro/1509713793314197504)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test
/kind flake

#### What this PR does / why we need it:

- createPodUsingNfs
 
https://github.com/kubernetes/kubernetes/blob/885f14d162471dfc9a3f8d4c46430805cf6be828/test/e2e/node/kubelet.go#L126-L129

https://github.com/kubernetes/kubernetes/blob/885f14d162471dfc9a3f8d4c46430805cf6be828/test/e2e/node/kubelet.go#L153-L155

#### Which issue(s) this PR fixes:

Fixes #109221

#### Special notes for your reviewer:
similar to #109097
/cc @s-urbaniak @liggitt
for https://github.com/kubernetes/kubernetes/pull/106454. (The failing is be after the pr merging)

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

File: test/e2e/node/kubelet.go [hunk 1]
```diff
@@ -271,7 +271,7 @@ var _ = SIGDescribe("kubelet", func() {
 		ns string
 	)
 	f := framework.NewDefaultFramework("kubelet")
-	f.NamespacePodSecurityEnforceLevel = admissionapi.LevelBaseline
+	f.NamespacePodSecurityEnforceLevel = admissionapi.LevelPrivileged
```
Comment (liggitt) [inline test/e2e/node/kubelet.go:274]: this is fine if needed for 1.24, but do all the tests within this require privileged, or only the nfs ones?

/lgtm
/approve

Comment (pacoxu) [reply test/e2e/node/kubelet.go:274]: Like below: 
image
