### PR TITLE
Fix flakiness in daemonset TestLaunchWithHashCollisiion

### LINKED ISSUE #67273: test/integration/daemonset TestLaunchWithHashCollision is flaking
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/22609/

```
[]v1.DaemonSetCondition(nil)}}: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
I0810 18:48:44.078211   28282 daemon_controller.go:265] Shutting down daemon sets controller
daemonset_test.go:880: Failed to update DaemonSet: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
```

/sig apps
/priority critical-urgent
/assign @mortent

PR that added the test:
https://github.com/kubernetes/kubernetes/pull/66476
/cc @janetkuo @mikedanese

### PR DESCRIPTION
**Pull request by mortent**
**What this PR does / why we need it**: Addresses flakiness in test/integration/daemonset TestLaunchWithHashCollision. It makes sure the test waits for the pod to be added to the daemonset before updating the daemonset. The should avoid the race where the daemonset gets updated in between the calls to get and update in the test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67273 

**Special notes for your reviewer**:
@janetkuo 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@mortent 
thanks for the quick reaction.

/sig apps
/ok-to-test
/kind flake

**Comment by spiffxp** [comment]
/approve
I'll leave the /lgtm to someone else

File: test/integration/daemonset/daemonset_test.go [hunk 1]
```diff
@@ -829,10 +829,14 @@ func TestLaunchWithHashCollision(t *testing.T) {
...
-	// Wait for the DaemonSet to be created before proceeding
+	// Wait for the DaemonSet and pod to be created before proceeding
 	err = waitForDaemonSetAndControllerRevisionCreated(clientset, ds.Name, ds.Namespace)
 	if err != nil {
-		t.Fatalf("Failed to create DeamonSet: %v", err)
+		t.Fatalf("Failed to create DaemonSet: %v", err)
+	}
+	err = waitForPodsCreated(podInformer, 1)
+	if err != nil {
+		t.Fatalf("Failed to create Pod for DaemonSet: %v", err)
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: From the error:
```
daemonset_test.go:880: Failed to update DaemonSet: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
```

the flakiness is introduced by the update call to DS (`dsClient.Update(ds)` in L882). `Update()` will fail if `ds` is already updated by something/someone else (e.g. DS controller). The flake can be fixed by retrying updates when there's a conflict, following this retry update pattern: if update failed due to conflict, get the latest object, apply the update again to the latest object, send update request with the updated object, repeat. Example code:
https://github.com/kubernetes/kubernetes/blob/d745508cc06fea440d83cad37ec4cb85d3d753e9/test/integration/replicaset/replicaset_test.go#L252-L262

**Review by janetkuo — CHANGES_REQUESTED** [review]

**Comment by tnozicka** [comment]
I've missed this as it was missing @kubernetes/sig-apps-pr-reviews so I wrote PATCH based fix in https://github.com/kubernetes/kubernetes/pull/67346 because I was hitting the flake.

(I've started with retry on conflict as well but using a PATCH looked cleaner to me. Also the intent in the place where you do the update is "set this value no matter what", doing a retry with get and update when you don't care about what you got doesn't seem semantically right, although it's common in tests because working with PATCH is a bit cumbersome as well.)

File: test/integration/daemonset/daemonset_test.go [hunk 2]
```diff
@@ -875,10 +892,9 @@ func TestLaunchWithHashCollision(t *testing.T) {
 
 	// Make an update of the DaemonSet which we know will create a hash collision when
 	// the next ControllerRevision is created.
-	_, err = dsClient.Update(ds)
-	if err != nil {
-		t.Fatalf("Failed to update DaemonSet: %v", err)
-	}
+	updateDS(t, dsClient, ds.Name, func(updateDS *apps.DaemonSet) {
+		updateDS.Spec.Template.Spec.TerminationGracePeriodSeconds = &one
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: Combine L874 with this

File: test/integration/daemonset/daemonset_test.go [hunk 3]
```diff
@@ -875,10 +892,9 @@ func TestLaunchWithHashCollision(t *testing.T) {
 
 	// Make an update of the DaemonSet which we know will create a hash collision when
 	// the next ControllerRevision is created.
-	_, err = dsClient.Update(ds)
-	if err != nil {
-		t.Fatalf("Failed to update DaemonSet: %v", err)
-	}
+	updateDS(t, dsClient, ds.Name, func(updateDS *apps.DaemonSet) {
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: `ds = upddateDS(...)`

File: test/integration/daemonset/daemonset_test.go (hunk 2 above)
Comment (mortent) [reply test/integration/daemonset/daemonset_test.go]: The change to `TerminationGracePeriodSeconds` on line 874 is needed to compute the hash for the controller revision that will create the hash collision when the daemonset is updated. I'm not sure there is an easy way to combine this since the controller revision will need to be created before the call to `Update`.

**Review by janetkuo — APPROVED** [review]

**Comment by neolit123** [comment]
the irony
/test pull-kubernetes-e2e-kops-aws

**Comment by janetkuo** [comment]
All recent runs of pull-kubernetes-e2e-kops-aws (across PRs) have failed: 
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws?before=101234
