### PR TITLE
Use namespace created by framework

### LINKED ISSUE #110270: Failure cluster [54e385e5...]
##### Error text:
```
test/e2e/kubectl/kubectl.go:1186
May 18 00:50:28.281: error missing unknown metadata field, got: error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.83.140.129 --kubeconfig=/workspace/.kube/config --namespace=kubectl-8939 create -f -:
Command stdout:

stderr:
error: the namespace from the provided object "my-ns" does not match the namespace "kubectl-8939". You must pass '--namespace=my-ns' to perform this operation.

error:
exit status 1
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
#### Recent failures:
[5/28/2022, 3:00:16 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1530624997146497024)
[5/28/2022, 2:20:15 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1530614930699456512)
[5/28/2022, 1:43:15 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1530605619172610048)
[5/28/2022, 1:03:15 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1530595553073696768)
[5/28/2022, 12:23:16 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1530585486324666368)

/kind failing-test

/sig cli

### LINKED ISSUE #110467: Failure cluster [05c71e0f...]
##### Error text:
```
test/e2e/kubectl/kubectl.go:1186
May 25 00:18:53.116: error missing unknown metadata field, got: error running /workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.168.238.90 --kubeconfig=/workspace/.kube/config --namespace=kubectl-2208 create -f -:
Command stdout:

stderr:
error: the namespace from the provided object "my-ns" does not match the namespace "kubectl-2208". You must pass '--namespace=my-ns' to perform this operation.

error:
exit status 1
vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
#### Recent failures:
[6/8/2022, 3:04:01 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1534612180521979904)
[6/8/2022, 2:21:43 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1534601564021329920)
[6/8/2022, 1:42:43 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1534591749555490816)
[6/8/2022, 1:00:44 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1534581179418677248)
[6/8/2022, 12:21:43 PM ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1534571364952838144)

/kind failing-test

/sig cli

### PR DESCRIPTION
**Pull request by kevindelgado**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Uses the namespace created by the testing framework instead of an erroneous hardcoded one for field validation kubectl tests

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/110270
Fixes https://github.com/kubernetes/kubernetes/issues/110467

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/kubectl/kubectl.go [hunk 1]
```diff
@@ -1150,13 +1150,13 @@ metadata:
       "metadata": {
         %s
         "name": "subobject",
-        "namespace": "my-ns"
+        "namespace": %s
```
Comment (bluecloudes) [inline test/e2e/kubectl/kubectl.go:1153]: Does namespace need to be quoted? 
```suggestion
        "namespace": "%s"
```
