### PR TITLE
Fix clientset e2e test flake

### LINKED ISSUE #21045: e2e Flake: clientset should create pods, delete pods, watch pods
```console
• Failure [12.590 seconds]
Generated release_1_2 clientset
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:154
  should create pods, delete pods, watch pods [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:153

  Expected
      <int>: 0
  to equal
      <int>: 1

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/generated_clientset.go:102
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #21045.

Add a sleep before List() to give enough time for the server-side watch cache to receive the pod creation watch notification.

I cannot reproduce the flake locally (250 runs without failure) #so I cannot be sure if this actually fixes the test on Jenkins. I'll run the tests locally overnight to see if I can reproduce.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Another thing (unrelated to this PR) I noticed during debugging is that the description of ListOptions.ResrouceVersion is inaccurate (https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1883):
```
	// The resource version to watch (no effect on list yet)
	ResourceVersion string
```
In fact it does affect watch (at least when we enable watch cache, https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L304):
```
	// List elements from cache, with at least 'listRV'.
	listPtr, err := meta.GetItemsPtr(listObj)
```
@lavalamp could you confirm if I'm right?

**Comment by madhusudancs** [comment]
@caesarxuchao I found another flake here - http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//28017.

**Comment by wojtek-t** [comment]
Removing LGTM label - I have one comment.

File: test/e2e/generated_clientset.go [hunk 1]
```diff
@@ -95,6 +95,9 @@ var _ = Describe("Generated release_1_2 clientset", func() {
 		}
 
 		By("verifying the pod is in kubernetes")
+		time.Sleep(10 * time.Second)
+		selector = labels.SelectorFromSet(labels.Set(map[string]string{"time": value}))
+		options = api.ListOptions{LabelSelector: selector}
```
Comment (wojtek-t) [inline test/e2e/generated_clientset.go]: To give you some more overview how it works.
ListOptions has "ResourceVersion" field that you can set. The semantic of this field is as following:
- if this is unset - we will forward list to etcd, without touching watchcache in apiserver
- if this is set - we will serve the result from watchcache in apiserver and guarantee that the returned result is at least as fresh as the given RV

So what was happening before this change was:
- ResourceVersion was set, to a value before "pod creation", to we were serving it from cache without waiting for the pod to be there


So there are two possible fixes:
- set ResourceVersion to 0 (and remove Sleep, because it is then not needed)
- or alternatively: set ResourceVersion in options to the ResourceVersion of create pod, i.e.

pod, err := podClient.Create(pod)
if err != nil {
    Failf("...")
}

By("verifying the pod is in kubernetes")
options.ResourceVersion = pod.ResourceVersion
pods, err := podClient.List(options)


I think the second option is preferred, but I can also live with the first one :)

@lavalamp - FYI

Comment (caesarxuchao) [inline test/e2e/generated_clientset.go]: Thank you @wojtek-t! It's very helpful.

**Comment by caesarxuchao** [comment]
@nikhiljindal I fixed the code as @wojtek-t suggested. PTAL. Thanks.

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by lavalamp** [comment]
@caesarxuchao Yes, that comment needs to be updated.

@nikhiljindal: The current PR LGTM but it seems this was primarily a sleep when you looked at it-- we should *not* be LGTMing test fixes via sleep without first giving a lot of pushback.

**Comment by wojtek-t** [comment]
>
@nikhiljindal: The current PR LGTM but it seems this was primarily a sleep when you looked at it-- we should not be LGTMing test fixes via sleep without first giving a lot of pushback.

+1 - completely agree with that

**Comment by caesarxuchao** [comment]
@lavalamp It was my fault, @nikhiljindal did give me a lot of pushback, it was late last night and I pushed him to merge it so we can see if the PR was effective.

**Comment by lavalamp** [comment]
Ah, I know how that goes :)

**Comment by wojtek-t** [comment]
@lavalamp @caesarxuchao - shouldn't we merge it manually to fix the underlying problem?

**Comment by lavalamp** [comment]
Yes. @k8s-oncall-- please merge this flake fix manually.

**Comment by caesarxuchao** [comment]
@mikedanese this is the fix. Please merge it manually. Thanks.
