### PR TITLE
fix:  Sweep and fix stat, lstat, evalsymlink usage for go1.23 on Windows

### LINKED ISSUE #129084: Sweep and adjust Stat/Lstat/EvalSymlinks to go 1.23 behavior on Windows
Context: https://github.com/kubernetes/kubernetes/issues/129080

Go 1.23 changed stdlib behavior of filesystem calls Stat / Lstat / EvalSymlinks on Windows. This broke some kubelet handling of volumes on Windows, and possibly other use of those functions. For Kubernetes 1.32, the behavior was temporarily reverted via godebug switches in https://github.com/kubernetes/kubernetes/pull/129083, but this is not a long-term solution. Libraries like [k8s.io/mount-utils](https://github.com/kubernetes/mount-utils) can be used by downstream consumers building with go 1.23 and get unintended behavior, and the godebug opt-outs will eventually become unavailable, so we need to prepare Kubernetes to not require them as soon as possible.

As soon as possible in the 1.33 development cycle, sig-storage / sig-windows / sig-node need to sweep for use of Stat / Lstat / EvalSymlinks calls that would be impacted by the go 1.23 changes, and adjust them to work properly, and drop the change in https://github.com/kubernetes/kubernetes/pull/129083 to restore default go stdlib behavior.

A prereq to doing this safely is good test coverage (both unit test level and e2e level).
- There is currently no job running unit tests on Windows
- There are some e2e jobs exercising volumes on Windows, but the one that was broken (GCE PD) does not currently have working tests (see https://github.com/kubernetes/kubernetes/issues/129080#issuecomment-2517810676 and https://github.com/kubernetes/test-infra/issues/33905)

/sig node storage windows
/priority important-soon
/milestone v1.33

### PR DESCRIPTION
**Pull request by mansikulkarni96**
**What type of PR is this?**

/kind bug
/priority important-soon
/sig storage
/sig windows
/triage accepted

**Which issue(s) this PR fixes:**
Fixes #129084

**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?**

fix: Sweep and fix stat, lstat, evalsymlink usage for go1.23 on Windows

**Additional documentation e.g., KEPs **

**Kubernetes Enhancement Proposals), usage docs, etc.:**

fix: Sweep and fix stat, lstat, evalsymlink usage for go1.23 on Windows

### CODE REVIEW

**Comment by mansikulkarni96** [comment]
@KlwntSingh thanks for helping me sweep the code for potential issues that needed fix.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -202,15 +202,12 @@ func (m *ManagerImpl) CleanupPluginDirectory(dir string) error {
 		if filePath == m.checkpointFile() {
 			continue
 		}
-		// TODO: Until the bug - https://github.com/golang/go/issues/33357 is fixed, os.stat wouldn't return the
-		// right mode(socket) on windows. Hence deleting the file, without checking whether
-		// its a socket, on windows.
-		stat, err := os.Lstat(filePath)
+		stat, err := os.Stat(filePath)
```
Comment (liggitt) [inline pkg/kubelet/cm/devicemanager/manager.go:205]: we tried making this change before in 4060ee60c1d2e5ba1fba1f8729adfc211cee1b6f and reverted it in 2454d8d4c343096845dcdab74559ba1d36f67564 because tests broke... what is different this time around?

File: pkg/util/filesystem/util_windows.go [hunk 2]
```diff
@@ -46,48 +45,35 @@ const (
...
 	// does NOT work in 1809 if the socket file is created within a bind mounted directory by a container
 	// and the FSCTL is issued in the host by the kubelet.
 
 	// If the file does not exist, it cannot be a Unix domain socket.
-	if _, err := os.Stat(filePath); os.IsNotExist(err) {
-		return false, fmt.Errorf("File %s not found. Err: %v", filePath, err)
+	info, err := os.Stat(filePath)
+	if err != nil {
+		return false, fmt.Errorf("stat file %s failed: %w", filePath, err)
 	}
```
Comment (liggitt) [inline pkg/util/filesystem/util_windows.go:57]: would it be more robust to keep ~all the existing code in this function as-is until we drop the winsymlink workaround (https://github.com/kubernetes/kubernetes/pull/130008) and do an additive check specifically for socket mode like this:

```diff
- if _, err := os.Stat(filePath); os.IsNotExist(err) {
+ if info, err := os.Stat(filePath); os.IsNotExist(err) {
		return false, fmt.Errorf("File %s not found. Err: %v", filePath, err)
- }
+ } else if err == nil && info.Mode()&os.ModeSocket != 0 {
+   klog.V(6).InfoS("File identified as a Unix domain socket", "filePath", filePath)
+   return true, nil
+ }
```

Comment (liggitt) [reply pkg/util/filesystem/util_windows.go:57]: also, do we have good unit tests for this function? can we run them and make sure they pass on this PR as-is *and* with https://github.com/kubernetes/kubernetes/pull/130008 layered in?

File: pkg/volume/util/hostutil/hostutil_windows.go [hunk 3]
```diff
@@ -143,6 +134,9 @@ func (hu *HostUtil) GetMode(pathname string) (os.FileMode, error) {
 	if err != nil {
 		return 0, err
 	}
+	if info.Mode()&os.ModeIrregular != 0 {
```
Comment (liggitt) [inline pkg/volume/util/hostutil/hostutil_windows.go:137]: this seems like a really low-level method... is ModeIrregular really an error, or is that a signal callers of this function could be looking for?

File: pkg/volume/util/hostutil/hostutil_windows.go [hunk 4]
```diff
@@ -103,14 +102,6 @@ func isSystemCannotAccessErr(err error) bool {
 func (hu *(HostUtil)) GetFileType(pathname string) (FileType, error) {
 	filetype, err := getFileType(pathname)
 
-	// os.Stat will return a 1920 error (windows.ERROR_CANT_ACCESS_FILE) if we use it on a Unix Socket
```
Comment (liggitt) [inline pkg/volume/util/hostutil/hostutil_windows.go:106]: do we need to keep this in place until we drop the symlink compat switch (e.g. merge https://github.com/kubernetes/kubernetes/pull/130008)

same question about whether we have good unit tests for this, and if we can run them on this change with and without https://github.com/kubernetes/kubernetes/pull/130008 layered in

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 1 above)
Comment (jsturtevant) [reply pkg/kubelet/cm/devicemanager/manager.go:205]: The commit in https://github.com/kubernetes/kubernetes/commit/4060ee60c1d2e5ba1fba1f8729adfc211cee1b6f was premature as the release wasn't using golang 1.23: https://github.com/kubernetes/kubernetes/issues/126965#issuecomment-2317379401

Comment (liggitt) [reply pkg/kubelet/cm/devicemanager/manager.go:205]: ah, ok...

do we have better unit tests in place now than we did then to detect if this is doing the right thing on windows now?

I'm trying to understand if we can make this change before https://github.com/kubernetes/kubernetes/pull/130008, or if there's code we can have here that works with *and* without https://github.com/kubernetes/kubernetes/pull/130008

Comment (jsturtevant) [reply pkg/kubelet/cm/devicemanager/manager.go:205]: We discussed this a bit today at sig-windows and @marosset is going to work with @mansikulkarni96 to verify this

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 3 above)
Comment (marosset) [reply pkg/volume/util/hostutil/hostutil_windows.go:137]: Recently ModeIrregular was updated so non-symlink reparse points are treated as such.
https://github.com/golang/go/issues/61893

This is a good question tho, i need to do a little bit more research

**Comment by liggitt** [comment]
This is now actively blocking update to go 1.24... resolution needs to happen as top priority, ahead of any features storage or windows are working on for 1.33. I would recommend synchronous meetings to work through review and updates with high bandwidth and drive to completion ~today

File: pkg/util/filesystem/util_windows.go [hunk 5]
```diff
@@ -46,48 +45,35 @@ const (
...
 
 	klog.V(6).InfoS("Function IsUnixDomainSocket starts", "filePath", filePath)
-	// As detailed in https://github.com/kubernetes/kubernetes/issues/104584 we cannot rely
-	// on the Unix Domain socket working on the very first try, hence the potential need to
-	// dial multiple times
-	var lastSocketErr error
-	err := wait.PollImmediate(socketDialRetryPeriod, socketDialTimeout,
```
Comment (liggitt) [inline pkg/util/filesystem/util_windows.go:67]: should the rest of this function stay as-is until we drop the `winsymlink` debug flag?

File: pkg/volume/util/subpath/subpath_windows.go [hunk 6]
```diff
@@ -201,6 +201,12 @@ func lockAndCheckSubPathWithoutSymlink(volumePath, subPath string) ([]uintptr, e
 			break
 		}
 
+		// go1.23 behavior change: https://github.com/golang/go/issues/63703#issuecomment-2535941458
+		if stat.Mode()&os.ModeIrregular != 0 {
+			errorResult = fmt.Errorf("subpath %q is an unexpected irregular file after EvalSymlinks", currentFullPath)
```
Comment (liggitt) [inline pkg/volume/util/subpath/subpath_windows.go:206]: is this error correct prior to dropping the winsymlink compat switch workaround, or should we be dropping that workaround in this PR to make this code correct?

**Comment by xing-yang** [comment]
cc @andyzhangx @mauriciopoppe

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 3 above)
Comment (mansikulkarni96) [reply pkg/volume/util/hostutil/hostutil_windows.go:137]: I couldn't find the caller of this function, so it may be okay to drop this change.

Comment (liggitt) [reply pkg/volume/util/hostutil/hostutil_windows.go]: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go/#L345, right?

**Review by mauriciopoppe — COMMENTED** [review]
What's your approach to fix the compat issue? I thought of two:

- Compat fixes + winsymlink removal in go.mod in 1 PR e.g. this PR
- Winsymlink removal in go.mod in 1 PR e.g. https://github.com/kubernetes/kubernetes/pull/130008 first, then other PRs on top to fix the compat issues e.g. this PR minus the winsymlink changes.

There are a few commits in between but unit and e2e tests are on changeset as a whole, would that be enough testing or do we need manual tests too?

**Comment by mansikulkarni96** [comment]
> What's your approach to fix the compat issue? I thought of two:
> 
> * Compat fixes + winsymlink removal in go.mod in 1 PR e.g. this PR
> * Winsymlink removal in go.mod in 1 PR e.g. [WIP: Drop winsymlink go 1.23 workaround #130008](https://github.com/kubernetes/kubernetes/pull/130008) first, then other PRs on top to fix the compat issues e.g. this PR minus the winsymlink changes.
> 
> There are a few commits in between but unit and e2e tests are on changeset as a whole, would that be enough testing or do we need manual tests too?

I am taking the first approach as of now, commit from #130008 is cherry-picked. 
For testing, @sunnylovestiramisu is helping us run PDCSI driver tests.

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 4 above)
Comment (mansikulkarni96) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: I have kept this as we have cherry-picked dropping winsymlink. But I can drop this if it is increasing the complexity and add this in a follow-up PR.

File: pkg/util/filesystem/util_windows.go (hunk 2 above)
Comment (mansikulkarni96) [reply pkg/util/filesystem/util_windows.go]: updated PTAL

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 4 above)
Comment (liggitt) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: is there a unit test showing this now works properly on windows socket files?

File: pkg/volume/util/volumepathhandler/volume_path_handler.go [hunk 7]
```diff
@@ -249,6 +250,10 @@ func (v VolumePathHandler) IsSymlinkExist(mapPath string) (bool, error) {
 	if fi.Mode()&os.ModeSymlink == os.ModeSymlink {
 		return true, nil
 	}
+	// go1.23 behavior change: https://github.com/golang/go/issues/63703#issuecomment-2535941458
+	if (runtime.GOOS == "windows") && (fi.Mode()&os.ModeIrregular != 0) {
```
Comment (liggitt) [inline pkg/volume/util/volumepathhandler/volume_path_handler.go:254]: this will make the caller thing irregular files on windows are symlinks? what is calling this and will it cause problems if the caller treats the path as a symlink when go says it is no longer a symlink?

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 4 above)
Comment (mansikulkarni96) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: We had a unit test file testing GetFileType for Windows, it was removed in https://github.com/kubernetes/kubernetes/commit/96e99f564a2e884b6d97510f76340348103e25c0
@marosset should I bring it back?

**Comment by jsturtevant** [comment]
helm didn't connect to api server so cni failed. Kubelet did start. I don't see anything obviously wrong in the logs
/test pull-kubernetes-unit-windows-master

File: pkg/volume/util/volumepathhandler/volume_path_handler.go (hunk 7 above)
Comment (mansikulkarni96) [reply pkg/volume/util/volumepathhandler/volume_path_handler.go:254]: @liggitt linking this [discussion](https://github.com/kubernetes/kubernetes/pull/129370/files#r1896043237) from @andyzhangx 's PR 
The conclusion was:
https://github.com/kubernetes/kubernetes/pull/129370/files#r1964507654

**Comment by msau42** [comment]
Once #129370 merges, please rebase

File: pkg/volume/util/volumepathhandler/volume_path_handler.go (hunk 7 above)
Comment (mansikulkarni96) [reply pkg/volume/util/volumepathhandler/volume_path_handler.go:254]: I agree @andyzhangx any objections on removing this?

Comment (msau42) [reply pkg/volume/util/volumepathhandler/volume_path_handler.go:254]: The only caller of this is the block volumemode feature. So the behavior is correct, however the function name is no longer correct. I am ok renaming the function as a followup.

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 4 above)
Comment (marosset) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: Yes, i think we should bring it back

Comment (marosset) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: it looks like it just got moved into a common test file tho?
https://github.com/kubernetes/kubernetes/blob/b84cb65f932ae02d06db26c5f9290489e97f9048/pkg/volume/util/hostutil/hostutil_test.go#L50

Comment (marosset) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: In https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-unit-windows-master/1893027447985672192/artifacts/junit_27.xml we do show the test passing for Windows and I do see a `FileTypeSocket` test case in there

Comment (marosset) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: that was run against main, let's verify it passed for this PR too

**Comment by msau42** [comment]
@mansikulkarni96 are the socket file handling changes required or related to the golang 1.23 changes? If not, then maybe we can handle the socket changes separately and make it non-blocking.

We tested https://github.com/kubernetes/kubernetes/pull/129370 and it addressed the original issue.

**Comment by liggitt** [comment]
> @mansikulkarni96 are the socket file handling changes required or related to the golang 1.23 changes? If not, then maybe we can handle the socket changes separately and make it non-blocking.

This PR is attempting to adapt k8s to be able to drop the winsymlink compat flag.

That changes stdlib behavior of the Mode() call here:
https://github.com/golang/go/blob/release-branch.go1.23/src/os/types_windows.go#L166-L168

Standard go 1.23 impl:
https://github.com/golang/go/blob/release-branch.go1.23/src/os/types_windows.go#L177-L231

Pre-go1.23 impl here:
https://github.com/golang/go/blob/release-branch.go1.23/src/os/types_windows.go#L237C1-L269C2

It's ... tough to tell whether switching from the old to the new Mode() impl by dropping the `winsymlink` compat flag *could* change how `Mode()` reports some sockets if they would also have been detected to be a reparse point, therefore [returning early and not setting the socket bit on the mode](https://github.com/golang/go/blob/release-branch.go1.23/src/os/types_windows.go#L245).

I'd probably keep the socket mode changes in this PR, make sure they're tested with unit tests and automatic / manual e2es, and merge this all together if possible.

File: pkg/volume/util/hostutil/hostutil_windows.go (hunk 4 above)
Comment (jsturtevant) [reply pkg/volume/util/hostutil/hostutil_windows.go:106]: k8s.io/kubernetes/pkg/volume/util/hostutil: TestGetFileType

did pass

**Comment by jsturtevant** [comment]
pull-kubernetes-unit-windows-master has some known failures (which are being worked on).

The main windows job passed all the tests just finishing cleaning up at this point.
/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm

lgtm for the EvalSymlinks related changes

**Comment by dims** [comment]
i think `pull-kubernetes-unit-windows-master` has known failures only.

/approve
/lgtm

**Comment by dims** [comment]
/assign @liggitt 

(for things i don't have `/approve` powers for)

**Comment by liggitt** [comment]
Are windows reviewers satisfied the e2e tests have exercised the socket changes successfully? I couldn't tell if the capz-azure failures were acceptable and if there were other tests passing that gave us confidence socket/plugin handling was working properly

**Comment by jsturtevant** [comment]
There unit tests that cover the socket changes made in device manager and fileutils packages; Those passed in the Windows unit test.  The other failures in the unit test are expected and being worked on in separate PR's.

The main capz windows tests we used for blocking signal also passed all its tests.  Unfourtunatly the capz csi tests that are failing are due to a configuration field that was removed from k/k earlier in the week.  The CAPZ team is working on a fix but it is not ready yet.

I also pulled these changes and verified the issue we saw previously with the device manager when making similar changes was not present.

/lgtm
/approve
