### PR TITLE
Unset gated podinfo InitialAttemptTimestamp in addToActiveQ

### LINKED ISSUE #117979: pod_scheduling_durating_seconds includes the time a Pod fails PreEnqueue
### What happened?

`pod_scheduling_durating_seconds` is recording the time that a Pod is gated.

We use the timestamp when the scheduler inserts the pod into the queue: https://github.com/kubernetes/kubernetes/blob/84c8abfb8bf900ce36f7ebfbc52794bad972d8cc/pkg/scheduler/internal/queue/scheduling_queue.go#L402

### What did you expect to happen?

The period of time when a Pod fails PreEnque (like being gated) shouldn't be accounted in the pod_scheduling_duration_seconds.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod with scheduling gates.
Wait some time before removing the gate.
Observe the `pod_scheduling_duration_seconds` metric

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
1.26+
```

</details>

### Cloud provider

<details>
Any
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by helayoty**
- Unset podInfo `InitialAttemptTimestamp` to exclude the preEnqueue failure time from the pod_scheduling_duration_seconds metric.
- Use a pointer to an `InitialAttemptTimestamp`.
- Add a new case for the `TestPerPodSchedulingMetrics` unit test 

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:
Fixes #117979 

#### Does this PR introduce a user-facing change?

```release-note
the `pod_scheduling_duration_seconds` metrics won't consider the time when a Pod fails PreEnqueue (like being gated). 
```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/queuesort/priority_sort.go [hunk 1]
```diff
@@ -42,7 +42,8 @@ func (pl *PrioritySort) Name() string {
 func (pl *PrioritySort) Less(pInfo1, pInfo2 *framework.QueuedPodInfo) bool {
 	p1 := corev1helpers.PodPriority(pInfo1.Pod)
 	p2 := corev1helpers.PodPriority(pInfo2.Pod)
-	return (p1 > p2) || (p1 == p2 && pInfo1.Timestamp.Before(pInfo2.Timestamp))
+	return (p1 > p2) || (p1 == p2 &&
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/queuesort/priority_sort.go:45]: It's not a good idea to change the structure of Timestamp. Per https://github.com/kubernetes/kubernetes/issues/117979#issuecomment-1548689549, I'd like to only refresh InitialAttemptTimestamp (maybe also Timestamp) on the first time a pod is queued into activeQ.

Comment (helayoty) [reply pkg/scheduler/framework/plugins/queuesort/priority_sort.go]: Reverted and refreshed the `InitialAttemptTimestamp`.

**Comment by alculquicondor** [comment]
I'll leave this review to @Huang-Wei

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 2]
```diff
@@ -900,7 +905,7 @@ func (p *PriorityQueue) newQueuedPodInfo(pod *v1.Pod, plugins ...string) *framew
 	return &framework.QueuedPodInfo{
 		PodInfo:                 podInfo,
 		Timestamp:               now,
-		InitialAttemptTimestamp: now,
+		InitialAttemptTimestamp: &now,
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go:908]: Given we want to exclude the duration spent in PreEnqueue, I'd expect it to be set as nil here. And then initialized in `addToActiveQ` when the pod is NOT gated for the first time.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 3]
```diff
@@ -382,6 +382,10 @@ func (p *PriorityQueue) runPreEnqueuePlugin(ctx context.Context, pl framework.Pr
 func (p *PriorityQueue) addToActiveQ(pInfo *framework.QueuedPodInfo) (bool, error) {
 	pInfo.Gated = !p.runPreEnqueuePlugins(context.Background(), pInfo)
 	if pInfo.Gated {
+		// Unset pod info timestamp to the initial attempt timestamp,to exclude the preEnqueue failure time, pod will be in the back of the queue.
+		if pInfo.InitialAttemptTimestamp != nil {
+			pInfo.Timestamp = *pInfo.InitialAttemptTimestamp
+		}
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go:388]: Remove this and add code above L393 b/c we just need to only set InitialAttemptTimestamp/Timestamp once - which is right after the pod is let go for the first time.

```go
		if pInfo.InitialAttemptTimestamp == nil {
		    now := time.Now()
			pInfo.InitialAttemptTimestamp = &now
			pInfo.Timestamp = now
		}
```

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 4]
```diff
@@ -578,6 +582,7 @@ func (p *PriorityQueue) flushUnschedulablePodsLeftover() {
 		if currentTime.Sub(lastScheduleTime) > p.podMaxInUnschedulablePodsDuration {
 			podsToMove = append(podsToMove, pInfo)
 		}
+
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go:585]: remote this empty line.

**Comment by Huang-Wei** [comment]
@helayoty the latest logic looks good, it's just some UTs may have assumed Timestamp/InitialAttemptTimestamp in another way, so may need to adapt those UTs.

**Comment by helayoty** [comment]
> @helayoty the latest logic looks good, it's just some UTs may have assumed Timestamp/InitialAttemptTimestamp in another way, so may need to adapt those UTs.

@Huang-Wei  , [This](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue_test.go#L1814) UT doesn’t make any sense with the change as it tests that the `InitialAttemptTimestamp` is not changed with a different number of attempts while it will change now. Should we remove it? Or reverse the logic to make sure it fails if it didn't change?

**Comment by Huang-Wei** [comment]
> @Huang-Wei , [This](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue_test.go?rgh-link-date=2023-05-16T23%3A20%3A00Z#L1814) UT doesn’t make sense with the change as it tests that the `InitialAttemptTimestamp` is not changed with a different number of attempts while it will change now. Should we remove it? Or reverse the logic to make sure it fails if it didn't change?

I'm wondering if it's possible to leverage help a fakeClock? Like, initialize the podInfo with a fakeClock to ensure the time is the same when it's created and firstly time added to activeQ, and then `step()` when it needs to do another attempt or movement.

**Review by Huang-Wei — COMMENTED** [review]
LGTM. Would you mind squashing the commits?

And could you fill the release note section? as it changes how `pod_scheduling_duration_seconds` is calculated.

cc @sanposhiho for awareness.

**Comment by alculquicondor** [comment]
can we add unit tests?

**Comment by Huang-Wei** [comment]
> can we add unit tests?

I think existing tests in pkg/scheduler/internal/queue/scheduling_queue_test.go already touched InitialAttemptTimestamp, and those UTs continue to pass can prove this PR works.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 5]
```diff
@@ -1965,7 +1965,7 @@ func checkPerPodSchedulingMetrics(name string, t *testing.T, pInfo *framework.Qu
 	if pInfo.Attempts != wantAttempts {
 		t.Errorf("[%s] Pod schedule attempt unexpected, got %v, want %v", name, pInfo.Attempts, wantAttempts)
 	}
-	if pInfo.InitialAttemptTimestamp != wantInitialAttemptTs {
+	if pInfo.InitialAttemptTimestamp != nil && *pInfo.InitialAttemptTimestamp != wantInitialAttemptTs {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1968]: do we need this nil check? I'd expect to keep the old logic.

**Comment by Huang-Wei** [comment]
> I think existing tests in pkg/scheduler/internal/queue/scheduling_queue_test.go already touched InitialAttemptTimestamp, and those UTs continue to pass can prove this PR works.

I re-read the tests a bit. Although the code path is covered, in these UTs, Timestamp and InitialAttemptTimestamp are identical. @helayoty Could you add a new UT (in TestPerPodSchedulingMetrics) to cover a case Timestamp and InitialAttemptTimestamp are different? (for example, make a pod gated in the first round when adding to queue, and then lift up the gate, and re-pop it, we should see its InitialAttemptTimestamp is different then timestamp)

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1968]: I mean this is a testing utility, so not imposing this nil check may expose some corner case that we haven't caught, with minimum cost. (running the UTs without the nil check also works)

**Comment by helayoty** [comment]
> > I think existing tests in pkg/scheduler/internal/queue/scheduling_queue_test.go already touched InitialAttemptTimestamp, and those UTs continue to pass can prove this PR works.
> 
> I re-read the tests a bit. Although the code path is covered, in these UTs, Timestamp and InitialAttemptTimestamp are identical. @helayoty Could you add a new UT (in TestPerPodSchedulingMetrics) to cover a case Timestamp and InitialAttemptTimestamp are different? (for example, make a pod gated in the first round when adding to queue, and then lift up the gate, and re-pop it, we should see its InitialAttemptTimestamp is different then timestamp)

@alculquicondor @Huang-Wei  unit test has been added.

**Comment by Huang-Wei** [comment]
Yes I've reached out to Heba offline. Let's hold this pr for now.

**Comment by Huang-Wei** [comment]
Per discussion in https://github.com/kubernetes/enhancements/pull/4065/files#r1231487092, we reached a concensus to change the semantics of `pod_scheduling_duration_seconds` to exclude PreEnqueue by default, and then cherrypick the changes along with a few follow-ups.

/lgtm
/approve

cc @alculquicondor

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 6]
```diff
@@ -1870,6 +1870,38 @@ func TestPerPodSchedulingMetrics(t *testing.T) {
 		t.Fatalf("Failed to pop a pod %v", err)
 	}
 	checkPerPodSchedulingMetrics("Attempt twice with update", t, pInfo, 2, timestamp)
+
+	// Case 4: A gated pod is created and scheduled after lifting gate. The queue operations are
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1874]: We should be using a test table for these cases or split into separate test functions. That should make tests easier to debug in the future.

This is beyond the scope of this PR, but please consider working on this after this has been merged and cherry-picked.

Although, I would prefer this new test goes into a separate function in this PR.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 7]
```diff
@@ -1870,6 +1870,38 @@ func TestPerPodSchedulingMetrics(t *testing.T) {
...
+	queue.Update(gatedPod, updateGatedPod)
+
+	pInfo, err = queue.Pop()
+	if err != nil {
+		t.Fatalf("Failed to pop a pod %v", err)
+	}
+
+	if pInfo.Timestamp == *pInfo.InitialAttemptTimestamp {
+		t.Errorf("[Gated Pod] Pod timesamp and initialAttemptTimestamp cannot be with same value when pod is gated, Timestamp %v, InitialAttemptTimestamp %v", pInfo.Timestamp, *pInfo.InitialAttemptTimestamp)
+	}
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1903]: this is an internal detail. The check below should be enough.

**Review by alculquicondor — COMMENTED** [review]
/approve

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1874]: we do have some test code not following the table-driven test style. it can be followed-up with other tests.

**Comment by Huang-Wei** [comment]
@helayoty could you squash the commits, and it will be ease cherrypicking.

**Comment by helayoty** [comment]
> @helayoty could you squash the commits, and it will be ease cherrypicking.

@Huang-Wei Done.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 6 above)
Comment (helayoty) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1900]: I agree to follow the table-driven test style. I didn't want to have an out-of-scope change in this PR. I will follow up with another PR to address this comment.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 7 above)
Comment (helayoty) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go]: Addressed.

**Comment by Huang-Wei** [comment]
/lgtm

And feel free to /unhold when the CIs are all green.

Thanks @helayoty . Sorry for the discussion back and forth, but I think it helps clarify the overall picture.

**Comment by alculquicondor** [comment]
Can you prepare a cherry-pick for the `release-1.27` branch?
