### PR TITLE
Fix requeueing of cronjobs with every-style schedule

### LINKED ISSUE #104012: CronJob controller V2: breaks "@every [interval]" jobs
#### What happened:

In K8s 1.21, CronJobs with a `.spec.schedule` with a value containing something like `@every 6h` are inconsistently scheduled, and the CronJob's `.status.lastScheduleTime` field does not match reality.

For example, I have a CronJob configured as above. It runs every 6 hours as long as the kube-controller-manager pod isn't restarted, but the `.status.lastScheduleTime` is currently some 45 minutes _before_ the Job's `.spec.metadata.creationTimestamp`. The kube-controller-manager's logs correctly show the job is created corresponding with the Job's creationTimestamp, and the CronJob's lastScheduleTime appears to be updated at the same time, but with a time stamp in the past.

In K8s 1.20 the behaviour was as expected, and the lastScheduleTime closely (possibly even exactly) matched the Job's creationTimestamp.

#### What you expected to happen:

Jobs created from CronJobs should be consistently created every 6 hours (for `@every 6h`), and the `.status.lastScheduleTime` should closely follow the last Job's `.spec.metadata.creationTimestamp` field.

#### How to reproduce it (as minimally and precisely as possible):

I see consistent behaviour on multiple clusters running 1.21 (in AWS EKS and built using Rancher RKE2), but I haven't tried with timestamps shorter than 6 hours. This is easily reproducible with `@every 6h` timestamps, however.

#### Anything else we need to know?:

The `@every` syntax is not documented in the Kubernetes [CronJob documentation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), though that mostly points at [Wikipedia](https://en.wikipedia.org/wiki/Cron) for the schedule format. However, the `@every` syntax works and is documented in [`vendor/github.com/robfig/cron/v3/doc.go`](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/robfig/cron/v3/doc.go) and at https://pkg.go.dev/github.com/robfig/cron.

The implementation for `@every` is at: https://github.com/kubernetes/kubernetes/blob/fffaadc01331cca57cafa0fc066a2a3eec23acb8/vendor/github.com/robfig/cron/v3/parser.go#L424-L431

#### Environment:
- Kubernetes version (use `kubectl version`):
  - ```version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+rke2r1", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-21T16:49:24Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}```
  - ```version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T00:59:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}```

- Cloud provider or hardware configuration: Rancher RKE2 _and_ AWS EKS
- OS (e.g: `cat /etc/os-release`): Debian Bullseye / Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10.0-8-amd64 / 5.4.129-63.229.amzn2.x86_64
- Install tools: Rancher RKE2 / n/a
- Network plugin and version (if this is a network-related bug): n/a

### PR DESCRIPTION
**Pull request by d-honeybadger**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
In CronJob ControllerV2, cronjobs need to be requeued when it's time for the next schedule. This requeueing interval is currently calculated based off the time `now`. This works fine for classic cron schedule, b/c the "next" schedule is aligned with the specific day/hour/minute from the schedule, but breaks for @every X schedule, because the "next" schedule in this case becomes simply `now + X`, and is incorrect if a) kube-controller-manager was restarted and syncing all cronjobs; b) there was an update to cronjob schedule. Instead, for @every-style schedules, it becomes important to always base the calculation of the next time relative to the last scheduled time (or cronjob creation if it wasn't scheduled before).
Note that since before controllerv2, requeueing wasn't a thing, and therefore this bug didn't exist.

#### Which issue(s) this PR fixes:
Fixes #104012

#### Special notes for your reviewer:
Verified the fix with a local cluster (`./hack/local-up-cluster.sh`). Figured an e2e test for such a specific case would be an overkill. Either way, lmk if I'm over- or under-testing this. 
There's also one unit test that has a comment on why it will fail. The reason for its failure is outside of the scope of this PR, and not introduced by this PR - lmk if it should be deleted of kept to indicate that a future fix in necessary.

#### Does this PR introduce a user-facing change?
```release-note
Fixes scheduling of cronjobs with @every X schedules.
```

### CODE REVIEW

**Comment by d-honeybadger** [comment]
@soltysh, @alculquicondor You are the two people I saw dealing with cronjobs recently, could you please take a look?

**Comment by d-honeybadger** [comment]
I fixed the commit message and force-pushed, but the label isn't going away :thinking:

**Comment by d-honeybadger** [comment]
:wave: @soltysh Could you please take a look whenever you have a minute?

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 1]
```diff
@@ -642,12 +642,26 @@ func getJobName(cj *batchv1.CronJob, scheduledTime time.Time) string {
...
 
 // nextScheduledTimeDuration returns the time duration to requeue based on
-// the schedule and current time. It adds a 100ms padding to the next requeue to account
+// the schedule and last schedule time. It adds a 100ms padding to the next requeue to account
 // for Network Time Protocol(NTP) time skews. If the time drifts are adjusted which in most
 // realistic cases would be around 100s, scheduled cron will still be executed without missing
 // the schedule.
-func nextScheduledTimeDuration(sched cron.Schedule, now time.Time) *time.Duration {
-	t := sched.Next(now).Add(nextScheduleDelta).Sub(now)
+func nextScheduledTimeDuration(cj batchv1.CronJob, sched cron.Schedule, now time.Time) *time.Duration {
```
Comment (soltysh) [inline pkg/controller/cronjob/cronjob_controllerv2.go:649]: I've noticed there's a quite a lot of similarities between this method and `getNextScheduleTime`, I'll followup with a squash. But this is very good - thank you!

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 1 above)
Comment (d-honeybadger) [reply pkg/controller/cronjob/cronjob_controllerv2.go:649]: Yeah that's true, was trying to keep changes local but that had its cons.
Thank you!
