### PR TITLE
UnmountDevice (GetMountRefs) should not fail if path does not exist

### LINKED ISSUE #68744: Failing tests: multiple In-tree Volumes failures
Failing Jobs
---
[sig-release-1.12-blocking#gce-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial)
[sig-release-1.12-blocking#gke-cos-1.12-default](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-default)
[sig-release-1.12-blocking#gke-cos-1.12-serial](https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gke-cos-1.12-serial)
[sig-release-master-blocking#gci-gce-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-serial)
[sig-release-master-blocking#gci-gke-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial)

Failing Tests
---
```
[sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]
[sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Dynamic PV (default fs)] volumes should be mountable
[sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Pre-provisioned PV (default fs)] subPath should support readOnly file specified in the volumeMount
[sig-storage] In-tree Volumes [Driver: azure] [Testpattern: Pre-provisioned PV (default fs)] volumes should be mountable
[sig-storage] In-tree Volumes [Driver: cinder] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly file specified in the volumeMount
```

Error Example
---
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:120
Persistent Volume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 not deleted by dynamic provisioner
Expected error:
    <*errors.errorString | 0xc421bbec70>: {
        s: "PersistentVolume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 still exists within 5m0s",
    }
    PersistentVolume pvc-4083b45c-b9dc-11e8-a26c-42010a8a0002 still exists within 5m0s
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:212
```

Triage
---
Tests failing across release-master-blocking, release-1.12-all and release-1.12-blocking.  More failures on GKE.  Many of the test results in testgrid are stale, most recently failing is https://k8s-testgrid.appspot.com/sig-release-1.12-blocking#gce-cos-1.12-serial

/kind bug
/kind failing-test
/sig storage
/priority critical-urgent
/milestone v1.12

### PR DESCRIPTION
**Pull request by davidz627**
Fixes #68744

I've also modified the Disruptive PV tests so that they would also catch this same class of regression in the future.

/sig storage
/kind bug
/assign @msau42 
/cc @tpepper 

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/storage/nfs_persistent_volume-disruptive.go [hunk 1]
```diff
@@ -277,11 +277,14 @@ func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framew
 }
 
 // tearDownTestCase destroy resources created by initTestCase.
-func tearDownTestCase(c clientset.Interface, f *framework.Framework, ns string, client *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume) {
+func tearDownTestCase(c clientset.Interface, f *framework.Framework, ns string, client *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume, forceDeletePV bool) {
 	// Ignore deletion errors.  Failing on them will interrupt test cleanup.
 	framework.DeletePodWithWait(f, c, client)
 	framework.DeletePersistentVolumeClaim(c, pvc.Name, ns)
-	if pv != nil {
```
Comment (msau42) [inline test/e2e/storage/nfs_persistent_volume-disruptive.go]: you may still need to check for nil in case creation fails

File: pkg/util/mount/mount_linux.go [hunk 2]
```diff
@@ -1005,6 +1005,9 @@ func (mounter *Mounter) SafeMakeDir(subdir string, base string, perm os.FileMode
 }
 
 func (mounter *Mounter) GetMountRefs(pathname string) ([]string, error) {
+	if _, err := os.Stat(pathname); os.IsNotExist(err) {
+		return nil, nil
```
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: instead of nil, you may want to return an empty array.  Not sure if all the callers will be able to handle nil return if nil error

**Comment by davidz627** [comment]
@msau42 resolved

File: pkg/util/mount/mount_linux.go [hunk 3]
```diff
@@ -1005,6 +1005,9 @@ func (mounter *Mounter) SafeMakeDir(subdir string, base string, perm os.FileMode
 }
 
 func (mounter *Mounter) GetMountRefs(pathname string) ([]string, error) {
+	if _, err := os.Stat(pathname); os.IsNotExist(err) {
```
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: Add unit test?

I think the other GetMountRefs implementations also need to be updated.

Comment (davidz627) [reply pkg/util/mount/mount_linux.go]: Updated windows and nsenter. They dont have unit tests for this so I didn't add anything. But I added a test case in `mount_linux_test.go`

File: pkg/util/mount/nsenter_mount.go [hunk 4]
```diff
@@ -337,6 +337,9 @@ func (mounter *NsenterMounter) SafeMakeDir(subdir string, base string, perm os.F
 }
 
 func (mounter *NsenterMounter) GetMountRefs(pathname string) ([]string, error) {
+	if _, err := os.Stat(pathname); os.IsNotExist(err) {
```
Comment (msau42) [inline pkg/util/mount/nsenter_mount.go]: For nsenter, I think you need to call nsenter.ExistsPath.  This is a containerized kubelet environment where we cannot check paths in the kubelet container, we need to check paths on the host.

**Comment by msau42** [comment]
/assign @jsafrane 
can you also help review and test the nsenter part?

File: pkg/util/mount/nsenter_mount.go (hunk 4 above)
Comment (jsafrane) [reply pkg/util/mount/nsenter_mount.go]: Yes, you should call `mounter.ExistsPath()` to check if a path exists or not. Otherwise LGTM.

File: pkg/util/mount/mount_windows.go [hunk 5]
```diff
@@ -459,6 +459,9 @@ func getAllParentLinks(path string) ([]string, error) {
 }
 
 func (mounter *Mounter) GetMountRefs(pathname string) ([]string, error) {
+	if _, err := os.Stat(pathname); os.IsNotExist(err) {
```
Comment (msau42) [inline pkg/util/mount/mount_windows.go]: you may need to call normalizeWindowsPath first.

cc @andyzhangx

File: pkg/util/mount/mount_linux.go (hunk 3 above)
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: if err is anything other than not exists, should we return error?

File: pkg/util/mount/nsenter_mount.go [hunk 6]
```diff
@@ -337,6 +337,13 @@ func (mounter *NsenterMounter) SafeMakeDir(subdir string, base string, perm os.F
 }
 
 func (mounter *NsenterMounter) GetMountRefs(pathname string) ([]string, error) {
+	exists, err := mounter.ExistsPath(pathname)
```
Comment (saad-ali) [inline pkg/util/mount/nsenter_mount.go]: Can we use a util method e.g. `PathExists(path string)` in `pkg/volume/util/util.go` instead?

**Review by saad-ali — COMMENTED** [review]
LGTM mod nit
/approve
