### PR TITLE
Verify iptable rules are applied for tcp, udp and icmp

### LINKED ISSUE #95905: node e2e: incorrect iptables settings during starting the tests
**Which jobs are failing**:
Before node e2e tests are started, iptables rules are applied. The rules aren't correctly applied for some OSes like, Fedora CoreOS.

**Which test(s) are failing**:
node e2e tests that depend on communication between the containers tend to fail on Fedora CoreOS where the iptable rules don't get applied properly before starting the tests.  

**Since when has it been failing**:
Probably always. I am in the process of fixing issues that I am seeing on Fedora CoreOS. 

**Testgrid link**:

**Reason for failure**:
The test infra currently checks if [existing iptable policy](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/utils.go#L88) is to `DROP` or not. But like in case of Fedora CoreOS, the iptables policy might be `ACCEPT` but it still lacks the individual rule for `tcp`, `udp` and `icmp`. In that case, since the iptables policy is not `DROP` the test infra doesn't attempt to add any required iptable rules for `tcp`, `udp` and `icmp`. 

To fix this we need to see if the iptable policy is not set to `DROP` plus check if the rules of `tcp`, `udp` and `icmp` are actually present or not.  

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:
The test infra currently checks if [existing iptable policy](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/remote/utils.go#L88) is to DROP or not.

But like in case of Fedora CoreOS, the iptables policy might be ACCEPT but it still lacks the individual rule for tcp, udp and icmp.

```bash
# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
# iptables -L FORWARD         
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination 
```
In that case, since the iptables policy is not set to `DROP` the test infra doesn't attempt to add any required iptable rules for `tcp`, `udp` and `icmp`.

To fix this we need to see if the iptable policy is not set to DROP plus check if the rules of `tcp`, `udp` and `icmp` are actually present or not. Then we see the iptable rules are correctly applied,

```bash
# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere            
ACCEPT     udp  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere            
# iptables -L FORWARD
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere            
ACCEPT     udp  --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere  
```

**Which issue(s) this PR fixes**:

Fixes #95905

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mrunalp** [comment]
@aojea ptal

**Comment by aojea** [comment]
It seems that the goal is enable connectivity without taking into account current rule, so I would just prepend the accept rules directly without any check

```
iptables -I INPUT 1 -w -p tcp -j ACCEPT
iptables -I INPUT 1 -w -p udp -j ACCEPT
iptables -I INPUT 1 -w -p icmp -j ACCEPT
iptables -I FORWARD 1 -w -p tcp -j ACCEPT
iptables -I FORWARD 1 -w -p udp -j ACCEPT
iptables -I FORWARD 1 -w -p icmp -j ACCEPT
```

File: test/e2e_node/remote/utils.go [hunk 1]
```diff
@@ -85,7 +85,8 @@ func configureFirewall(host string) error {
 	if err != nil {
 		return fmt.Errorf("failed to get iptables INPUT on %q: %v output: %q", host, err, output)
 	}
-	if strings.Contains(output, "Chain INPUT (policy DROP)") {
+	if strings.Contains(output, "Chain INPUT (policy DROP)") || !strings.Contains(output, "tcp") ||
```
Comment (aojea) [inline test/e2e_node/remote/utils.go:88]: you can use 
```func configureFirewall(host tring) error {

output, err := SSH(host, ....
iptables -I INPUT 1 -w -p tcp -j ACCEPT
iptables -I INPUT 1 -w -p udp -j ACCEPT
iptables -I INPUT 1 -w -p icmp -j ACCEPT
iptables -I FORWARD 1 -w -p tcp -j ACCEPT
iptables -I FORWARD 1 -w -p udp -j ACCEPT
iptables -I FORWARD 1 -w -p icmp -j ACCEPT
)

return err
}
```

Comment (aojea) [reply test/e2e_node/remote/utils.go:88]: this way you guarantee that the allowed rules are always at the top

Comment (harche) [reply test/e2e_node/remote/utils.go]: @aojea thanks. I just updated the PR with the suggested changes.

**Comment by harche** [comment]
> It seems that the goal is enable connectivity without taking into account current rule, so I would just prepend the accept rules directly without any check
> 
> ```
> iptables -I INPUT 1 -w -p tcp -j ACCEPT
> iptables -I INPUT 1 -w -p udp -j ACCEPT
> iptables -I INPUT 1 -w -p icmp -j ACCEPT
> iptables -I FORWARD 1 -w -p tcp -j ACCEPT
> iptables -I FORWARD 1 -w -p udp -j ACCEPT
> iptables -I FORWARD 1 -w -p icmp -j ACCEPT
> ```
> 
> those will be inserted right at the top, so you don't have to care about anything else

Thanks, I just verified on my local Fedora CoreOS setup that the suggested changes work fine with node e2e tests.

**Comment by dims** [comment]
/milestone v1.20

fix for a failing test
