### PR TITLE
Fix Storage e2e test `should assign default SC to PVCs that have no SC set`

### LINKED ISSUE #126829: Failure cluster [d3f73b56...] `should assign default SC to PVCs that have no SC set`
##### Error text:
```
[FAILED] Error updating PVC with the correct storage class: error waiting for claim retro-pvc-dlxqq to have StorageClass set to retro7s5rq: client rate limiter Wait returned an error: context deadline exceeded
In [It] at: k8s.io/kubernetes/test/e2e/storage/pvc_storageclass.go:91 @ 08/06/24 07:20:56.901

```
#### Recent failures:
[8/20/2024, 12:31:49 AM e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1825752444232011776)
[8/18/2024, 12:31:37 PM e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1825208854334410752)
[8/17/2024, 6:34:20 PM e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1824937060436283392)
[8/17/2024, 6:31:36 AM e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1824755864444080128)
[8/17/2024, 12:31:35 AM e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1824665266605264896)

/kind failing-test

/sig storage

### PR DESCRIPTION
**Pull request by torredil**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

This PR fixes a failing storage e2e test and generally improves the maintainability of this code path. 

The existing implementation is prone to race conditions and flakes quite often. Specifically, the following is problematic: https://github.com/kubernetes/kubernetes/blob/005f184ab631e52195ed6d129969ff3914d51c98/test/e2e/storage/pvc_storageclass.go#L68-L70 the test should unset default StorageClasses *before* creating a PVC/PV. However, the existing logic is incorrectly under a `defer` and this results in a default StorageClass being available at a point in time where the test expects there to be no default StorageClasses.

See the linked issue for more context.

#### Which issue(s) this PR fixes:

Fixes  https://github.com/kubernetes/kubernetes/issues/126829

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
N/A
```

### CODE REVIEW

File: test/e2e/storage/pvc_storageclass.go [hunk 1]
```diff
@@ -18,172 +18,172 @@ package storage
...
-			// Verify the PVC is bound and has the new default SC
-			claimNames := []string{pvc.Name}
-			err = e2epv.WaitForPersistentVolumeClaimsPhase(ctx, v1.ClaimBound, client, namespace, claimNames, 2*time.Second /* Poll */, t.Timeouts.ClaimProvisionShort, false)
-			framework.ExpectNoError(err)
-			updatedPVC, err := client.CoreV1().PersistentVolumeClaims(namespace).Get(ctx, pvc.Name, metav1.GetOptions{})
-			framework.ExpectNoError(err)
-			gomega.Expect(*updatedPVC.Spec.StorageClassName).To(gomega.Equal(storageClass.Name), "Expected PVC %v to have StorageClass %v, but it has StorageClass %v instead", updatedPVC.Name, prefixSC, updatedPVC.Spec.StorageClassName)
-			framework.Logf("Success - PersistentVolumeClaim %s got updated retroactively with StorageClass %v", updatedPVC.Name, storageClass.Name)
-		})
+	f.It("should assign default StorageClass to PVCs retroactively", f.WithDisruptive(), f.WithSerial(), func(ctx context.Context) {
```
Comment (RomanBednar) [inline test/e2e/storage/pvc_storageclass.go:52]: How exactly does this change help with **suspected** race with other tests? It still relies on modifying existing storage classes for the duration of the test, and also reverts SC settings via `defer`. The only thing changing is that here we don't check for specific storage class name being assigned to PVC making the test even less predictable as it would tolerate any SC being assigned - which should never happen during execution of this test. Seems like we're masking the problem without knowing the root cause.

If this test is serial and disruptive, how is it possible that it seems to be racy? Did we rule out the Prow config?

File: test/e2e/storage/pvc_storageclass.go [hunk 2]
```diff
@@ -18,172 +18,172 @@ package storage
...
+}
+
+func setStorageClassDefault(ctx context.Context, client clientset.Interface, scName string, isDefault string) {
+	sc, err := client.StorageV1().StorageClasses().Get(ctx, scName, metav1.GetOptions{})
+	framework.ExpectNoError(err, "Failed to get StorageClass %s", scName)
+
+	if sc.Annotations == nil {
+		sc.Annotations = make(map[string]string)
+	}
+	sc.Annotations["storageclass.kubernetes.io/is-default-class"] = isDefault
```
Comment (RomanBednar) [inline test/e2e/storage/pvc_storageclass.go:112]:
```suggestion
	sc.Annotations[storageutil.IsDefaultStorageClassAnnotation] = isDefault
```

File: test/e2e/storage/pvc_storageclass.go [hunk 3]
```diff
@@ -18,172 +18,172 @@ package storage
...
+	return createdSC
 }
 
-func waitForPVCStorageClass(ctx context.Context, c clientset.Interface, namespace, pvcName, scName string, timeout time.Duration) (*v1.PersistentVolumeClaim, error) {
-	var watchedPVC *v1.PersistentVolumeClaim
-
-	err := wait.PollUntilContextTimeout(ctx, 1*time.Second, timeout, false, func(ctx context.Context) (bool, error) {
-		var err error
-		watchedPVC, err = c.CoreV1().PersistentVolumeClaims(namespace).Get(ctx, pvcName, metav1.GetOptions{})
+func isPVCPending(ctx context.Context, client clientset.Interface, namespace, pvcName string, timeout time.Duration) bool {
```
Comment (RomanBednar) [inline test/e2e/storage/pvc_storageclass.go:169]: Do we need a custom function to check phase instead of `e2epv.WaitForPersistentVolumeClaimsPhase`? (same with `isPVCBound`)

File: test/e2e/storage/pvc_storageclass.go [hunk 4]
```diff
@@ -18,172 +18,172 @@ package storage
...
-	return &storagev1.StorageClass{
+func getDefaultStorageClasses(ctx context.Context, client clientset.Interface) ([]storagev1.StorageClass, error) {
+	scList, err := client.StorageV1().StorageClasses().List(ctx, metav1.ListOptions{})
+	if err != nil {
+		return nil, err
+	}
+
+	var defaultSCs []storagev1.StorageClass
+	for _, sc := range scList.Items {
+		if sc.Annotations["storageclass.kubernetes.io/is-default-class"] == "true" {
```
Comment (RomanBednar) [inline test/e2e/storage/pvc_storageclass.go:98]:
```suggestion
		if sc.Annotations[storageutil.IsDefaultStorageClassAnnotation] == "true" {
```

File: test/e2e/storage/pvc_storageclass.go (hunk 3 above)
Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go]: We could just use `e2epv.WaitForPersistentVolumeClaimsPhase` - done in latest rev.

File: test/e2e/storage/pvc_storageclass.go (hunk 1 above)
Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go:51]: Thank you for the review Roman! The latest revision now validates the StorageClass assignment as well.

> If this test is serial and disruptive, how is it possible that it seems to be racy? Did we rule out the Prow config?

The following logs can be observed in every failure:
```
0820 06:06:25.981634 15020 pvc_storageclass.go:178] PersistentVolumeClaim retro-pvc-lmzlm has unexpected StorageClass balanced-csi, expected StorageClass is: retromr8np
```

`balanced-csi` StorageClass is created by kOps during bootstrap. I believe we should be able to disable this via the `ManageStorageClasses` [parameter](https://github.com/kubernetes/kops/blob/e7be8333165b5494b00a9de634c5d687ae67daab/pkg/apis/kops/componentconfig.go#L931). Doing this, there should be no need to unset default storage classes in the test itself. 

We can either go with that approach, or introduce additional validation in the test here to address this race. As I understand the issue, it is possible for the [StorageClass lister ](https://github.com/kubernetes/kubernetes/blob/b2031b3cb46e946ee72eab7bda87b046db138d62/plugin/pkg/admission/storage/storageclass/setdefault/admission.go#L108)to return cached data if the PVC gets created immediately after the SC label has been updated.

Would love to hear your thoughts on this.

Comment (RomanBednar) [reply test/e2e/storage/pvc_storageclass.go:51]: Those are great points! I don't know much about kOps but was suspecting it of reconciling the `balanced-csi` storage class - but so far I could not find it and it seems like it's a one off action - and if it is then introducing additional validation would reveal it (test should timeout and fail if it can't ensure no SCs are default). I think this should be done anyway as it makes the test more robust.

Disabling the SC with `ManageStorageClasses` seems like a pretty good idea and I think you're right, in that case we should get a cluster with no default SCs, but relying on that in the test does not seem right. If somehow it would get re-enabled in the future, the failures would be reintroduced. Also, this might break other test, maybe some of them already rely on having a default SC :shrug:

So I'd first try the additional validation, and if the test starts failing due to SC being periodically reconciled go with disabling `ManageStorageClasses`. WDYT?

Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go:51]: Awesome, that sounds like a good plan to me, agree with all of the above. I'll put up a new revision later today and cc you when this PR is ready for review again.

File: test/e2e/storage/pvc_storageclass.go [hunk 5]
```diff
@@ -18,172 +18,177 @@ package storage
...
 	"k8s.io/kubernetes/test/e2e/framework"
 	e2epv "k8s.io/kubernetes/test/e2e/framework/pv"
-	"k8s.io/kubernetes/test/e2e/storage/testsuites"
 	"k8s.io/kubernetes/test/e2e/storage/utils"
 	admissionapi "k8s.io/pod-security-admission/api"
 )
 
-var _ = utils.SIGDescribe("Persistent Volume Claim and StorageClass", func() {
-	f := framework.NewDefaultFramework("pvc-retroactive-storageclass")
+var _ = utils.SIGDescribe("Retroactive StorageClass Assignment", feature.Kind, func() {
```
Comment (carlory) [inline test/e2e/storage/pvc_storageclass.go:40]: @RomanBednar @torredil  which job will be triggered to run this e2e if this label is applied? 

I cannot find a job from https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml

Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go:40]: This e2e test will be exercised by `pull-kubernetes-e2e-storage-kind-disruptive`  (done in this PR) and will also be periodically exercised in [e2e-ci-kubernetes-e2e-cos-gce-serial-canary](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary).

Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go]: `feature.Kind` is removed now in latest rev.

File: test/e2e/storage/pvc_storageclass.go [hunk 6]
```diff
@@ -32,158 +32,162 @@ import (
...
+	f.It("should assign default StorageClass to PVCs retroactively", f.WithDisruptive(), f.WithSerial(), func(ctx context.Context) {
+		defaultSCs, err := getDefaultStorageClasses(ctx, client)
+		framework.ExpectNoError(err, "Failed to get default StorageClasses")
+
+		defer func() {
+			// Restore existing default StorageClasses at the end of the test
+			for _, sc := range defaultSCs {
+				setStorageClassDefault(ctx, client, sc.Name, "true")
+			}
+		}()
```
Comment (carlory) [inline test/e2e/storage/pvc_storageclass.go:62]: When the e2e test runs on an existing cluster with a default storageclass, if the e2e test unexpectedly fails and the default storageclass in the cluster is not restored, it will affect the normal use of the cluster. This is a potential risk. `ginkgo.DeferCleanup` maybe preferred vs `defer`. 

For example, 

```go
package my

import (
	"fmt"
	"testing"
	"time"

	"github.com/onsi/ginkgo/v2"
)

func TestMy(t *testing.T) {
	// ginkgo.RegisterFailHandler(ginkgo.Fail)
	ginkgo.RunSpecs(t, "test my")
}

var _ = ginkgo.Describe("test my", func() {
	ginkgo.Context("test my", func() {
		ginkgo.It("test my 01", func() {
			defer func() { fmt.Println("aaa") }()
			ginkgo.DeferCleanup(func() { fmt.Println("bbbb") })
			time.Sleep(2 * time.Minute)
		})
	})
})
```

Test result: `bbbb` will be printed after the test case is executed but `aaa` will not be printed.

```
(base) ➜  my ginkgo -v .
Running Suite: test my - /tmp/demo/my
=====================================
Random Seed: 1728531653

Will run 1 of 1 specs
------------------------------
test my test my test my 01
/tmp/demo/my/my_test.go:18
^C  [INTERRUPTED] in [It] - /tmp/demo/my/my_test.go:18 @ 10/10/24 11:41:04.664
  ------------------------------
  Interrupted by User
  First interrupt received; Ginkgo will run any cleanup and reporting nodes but will skip all remaining specs.  Interrupt again to skip cleanup.
  Here's a current progress report:
    test my test my test my 01 (Spec Runtime: 10.105s)
      /tmp/demo/my/my_test.go:18
      In [It] (Node Runtime: 10.105s)
        /tmp/demo/my/my_test.go:18

      Spec Goroutine
      goroutine 8 [sleep]
        time.Sleep(0x1bf08eb000)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/time.go:285
      > demo/my.init.func1.1.1()
          /tmp/demo/my/my_test.go:21
            | 		defer func() { fmt.Println("aaa") }()
            | 		ginkgo.DeferCleanup(func() { fmt.Println("bbbb") })
            > 		time.Sleep(2 * time.Minute)
            | 	})
            | })
        github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x0?, 0x0?})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/node.go:472
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:894
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 5
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:881
  ------------------------------
bbbb
• [INTERRUPTED] [10.109 seconds]
test my test my [It] test my 01
/tmp/demo/my/my_test.go:18

  [INTERRUPTED] Interrupted by User
  In [It] at: /tmp/demo/my/my_test.go:18 @ 10/10/24 11:41:04.664

  This is the Progress Report generated when the interrupt was received:
    test my test my test my 01 (Spec Runtime: 10.105s)
      /tmp/demo/my/my_test.go:18
      In [It] (Node Runtime: 10.105s)
        /tmp/demo/my/my_test.go:18

      Spec Goroutine
      goroutine 8 [sleep]
        time.Sleep(0x1bf08eb000)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/time.go:285
      > demo/my.init.func1.1.1()
          /tmp/demo/my/my_test.go:21
            | 		defer func() { fmt.Println("aaa") }()
            | 		ginkgo.DeferCleanup(func() { fmt.Println("bbbb") })
            > 		time.Sleep(2 * time.Minute)
            | 	})
            | })
        github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x0?, 0x0?})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/node.go:472
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:894
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 5
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:881

      Other Goroutines
      goroutine 5 [running]
        github.com/onsi/ginkgo/v2/internal.extractRunningGoroutines()
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/progress_report.go:181
        github.com/onsi/ginkgo/v2/internal.NewProgressReport(_, {{0x1400012c980, 0x2, 0x2}, {0x14000123f10, 0x2, 0x2}, {0x1400016c540, 0x2, 0x2}, ...}, ...)
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/progress_report.go:75
        github.com/onsi/ginkgo/v2/internal.(*Suite).generateProgressReport(_, _)
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:381
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x3, 0x4, {0x102857f82, 0xa}, 0x14000023d50, {{0x102a3abef, 0x17}, 0x12, {0x0, ...}, ...}, ...}, ...)
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:980
        github.com/onsi/ginkgo/v2/internal.(*group).attemptSpec(0x14000225800, 0x1, {{0x14000294388?, 0x14000123f10?, 0x2?}, 0x0?})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/group.go:199
        github.com/onsi/ginkgo/v2/internal.(*group).run(0x14000225800, {0x1400012c960?, 0x0?, 0x0?})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/group.go:349
        github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0x14000170008, {0x102856d46, 0x7}, {0x102c3e1e0, 0x0, 0x0}, {0x14000010044, 0xc}, 0x0, {0x14000296060, ...})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:489
        github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {_, ...}, ...)
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/suite.go:130
        github.com/onsi/ginkgo/v2.RunSpecs({0x1029c2c28, 0x14000109520}, {0x102856d46, 0x7}, {0x0, 0x0, 0x0})
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/core_dsl.go:300
        demo/my.TestMy(0x14000109520?)
          /tmp/demo/my/my_test.go:13
        testing.tRunner(0x14000109520, 0x1029bf620)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1690
        testing.(*T).Run in goroutine 1
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1743

      goroutine 1 [chan receive]
        testing.(*T).Run(0x14000109380, {0x1028567bd?, 0x14000129b48?}, 0x1029bf620)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1751
        testing.runTests.func1(0x14000109380)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2168
        testing.tRunner(0x14000109380, 0x14000129c68)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1690
        testing.runTests(0x1400000e540, {0x102c04550, 0x1, 0x1}, {0x2000000000000000?, 0x20b79fa21d6824a5?, 0x0?})
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2166
        testing.(*M).Run(0x14000105180)
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:2034
        main.main()
          _testmain.go:45

      goroutine 33 [syscall]
        os/signal.signal_recv()
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/sigqueue.go:149
        os/signal.loop()
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/os/signal/signal_unix.go:23
        os/signal.Notify.func1.1 in goroutine 5
          /opt/homebrew/Cellar/go/1.23.1/libexec/src/os/signal/signal.go:151

      goroutine 49 [select]
        github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2(0x0?)
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/interrupt_handler/interrupt_handler.go:131
        github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts in goroutine 5
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/interrupt_handler/interrupt_handler.go:128

      goroutine 7 [select]
        github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal.func1()
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/progress_report.go:32
        github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal in goroutine 5
          /Users/kiki/workspace/golang/pkg/mod/github.com/onsi/ginkgo/v2@v2.20.1/internal/progress_report.go:30
------------------------------

Summarizing 1 Failure:
  [INTERRUPTED] test my test my [It] test my 01
  /tmp/demo/my/my_test.go:18

Ran 1 of 1 Specs in 10.112 seconds
FAIL! - Interrupted by User -- 0 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestMy (10.11s)
FAIL
You're using deprecated Ginkgo functionality:
=============================================
  --ginkgo.slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.

To silence deprecations that can be silenced set the following environment variable:
  ACK_GINKGO_DEPRECATIONS=2.20.1


Ginkgo ran 1 suite in 11.475919375s

Test Suite Failed
```

File: test/e2e/storage/pvc_storageclass.go [hunk 7]
```diff
@@ -32,158 +32,162 @@ import (
...
+		defer deletePVC(ctx, client, namespace, pvc.Name)
+		err = e2epv.WaitForPersistentVolumeClaimPhase(ctx, v1.ClaimPending, client, namespace, pvc.Name, time.Second, 30*time.Second)
+		framework.ExpectNoError(err, "PVC should be in Pending state when no default StorageClass exists")
+
+		// Create a default StorageClass
+		sc := createDefaultStorageClass(ctx, client)
+		defer deleteStorageClass(ctx, client, sc.Name)
+
+		// Create PV with the default StorageClass
+		pv := createPV(ctx, client, f, sc.Name, pvc.Spec.VolumeMode)
```
Comment (carlory) [inline test/e2e/storage/pvc_storageclass.go:87]: The e2e test aims to verify the pvc assigned to a specific storage class when the storage class is not specified in the pvc and the cluster has a default storage class, so we don't need to verify the binding of the pvc and pv in this case. @RomanBednar what do you think?

For example,

```go
gomega.Eventually(ctx, framework.GetObject(f.ClientSet.CoreV1().PersistentVolumeClaims(pvc.Namespace).Get, pvc.Name, metav1.GetOptions{})).
  WithPolling(framework.Poll).WithTimeout(framework.ClaimProvisionTimeout).Should(gomega.HaveField("Spec.StorageClassName",
  gomega.Equal(defaultSVC.Name)), "failed to wait for PVC to have the storageclass %s", defaultSVC.Name)
```

File: test/e2e/storage/pvc_storageclass.go [hunk 8]
```diff
@@ -32,158 +32,162 @@ import (
...
 }
 
-func waitForPVCStorageClass(ctx context.Context, c clientset.Interface, namespace, pvcName, scName string, timeout time.Duration) (*v1.PersistentVolumeClaim, error) {
-	var watchedPVC *v1.PersistentVolumeClaim
-
-	err := wait.PollUntilContextTimeout(ctx, 1*time.Second, timeout, false, func(ctx context.Context) (bool, error) {
-		var err error
-		watchedPVC, err = c.CoreV1().PersistentVolumeClaims(namespace).Get(ctx, pvcName, metav1.GetOptions{})
+func ensureNoDefaultStorageClasses(ctx context.Context, client clientset.Interface) error {
+	return wait.PollUntilContextTimeout(ctx, 5*time.Second, 2*time.Minute, true, func(ctx context.Context) (bool, error) {
```
Comment (carlory) [inline test/e2e/storage/pvc_storageclass.go:131]: [WaitFor<something> + ExpectError anti-pattern](https://github.com/kubernetes/kubernetes/issues/115164), please using `gomega.Eventually`

File: test/e2e/storage/pvc_storageclass.go (hunk 7 above)
Comment (RomanBednar) [reply test/e2e/storage/pvc_storageclass.go:87]: @carlory It aims to verify SC assignment while PVC with no SC is present and *after* some SC is set as default. Anyway, what you suggest could be sufficient and test could be limited to just checking SC field on PVC I think.

Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go]: Simplified test further as per the suggestion above.

File: test/e2e/storage/pvc_storageclass.go (hunk 8 above)
Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go]: Fixed.

File: test/e2e/storage/pvc_storageclass.go [hunk 9]
```diff
@@ -18,172 +18,168 @@ package storage
...
+	pvcConfig := e2epv.PersistentVolumeClaimConfig{
+		Name: "test-pvc",
+	}
 
-	if err != nil {
-		return watchedPVC, fmt.Errorf("error waiting for claim %s to have StorageClass set to %s: %w", pvcName, scName, err)
+	ginkgo.By("Creating a PVC")
+	pvcObj := e2epv.MakePersistentVolumeClaim(pvcConfig, namespace)
+	var pvc *v1.PersistentVolumeClaim
+	gomega.Eventually(ctx, func() error {
```
Comment (carlory) [inline test/e2e/storage/pvc_storageclass.go:147]: I'm unsure whether we should use the `Eventually` to wrap `create` or `delete` the PVC object. We often call `e2epv.CreatePVC` and `e2epv.DeletePersistentVolumeClaim` functions immediately in many places. 

/cc @pohly 

Can you help me to review this PR? Thanks a lot!

Comment (torredil) [reply test/e2e/storage/pvc_storageclass.go]: That makes sense - I understood https://github.com/kubernetes/kubernetes/pull/127790#discussion_r1794574457 as `ExpectNoError` to be an anti-pattern, but you are definitely right. I looked at other tests, and the only places were it makes sense to use `Eventually` are for `ensureNoDefaultStorageClasses` and verifying that the PVC is assigned the default SC. Fixed in latest rev.

Comment (pohly) [reply test/e2e/storage/pvc_storageclass.go]: Most tests rely on "simple" API calls to not fail and don't retry. There are some retry mechanisms inside client-go itself which help, so this is typically okay.

**Comment by torredil** [comment]
cc: @jingxu97

**Comment by torredil** [comment]
cc: @xing-yang need an approval 🙏

**Comment by RomanBednar** [comment]
Seems like the test is still failing, just differently: https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1848492383512039424

@torredil Any idea what's wrong? Seems like a problem with `ensureNoDefaultStorageClasses` - extra logs might help see what's going on.
