### PR TITLE
Fetch hacked easyrsa in kube-up instead of command run on master

### LINKED ISSUE #21037: cluster/ubuntu/util.sh's use of make-ca-cert.sh fails in restricted deployment environment
It is almost possible to run the cluster/ubuntu scripting on a non-cluster machine to deploy Kubernetes into a deployment environment that is restricted such that the cluster machines (master and workers (AKA "minions", "nodes")) can not open connections to arbitrary external locations.

However, there is at least one sticking point.  The one I discovered is that `provision-master` and `provision-masterandnode` use `ssh` to ask the master machine to run the `make-ca-cert.sh` script, and that script fetches https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz .

@dalanlan

### LINKED ISSUE #21092: make-ca-cert.sh is impossible to debug
cluster/saltbase/salt/generate-cert/make-ca-cert.sh sets `errexit` but does not echo what it is doing, so in the case of an error there is no evidence of which command produced the error.

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
This is good because it removes an obstacle to using the
cluster/ubuntu scripting to install Kubernetes into a restricted
environment where the machines can not open connections to arbitrary
external locations.

Also add debuggability to make-ca-cert.sh

Resolves #21037
Resolves #21092

### CODE REVIEW

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh [hunk 1]
```diff
@@ -18,6 +18,10 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+if [ "$DEBUG" == "true" ]; then
```
Comment (roberthbailey) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: nit: should be `"${DEBUG}"`

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh (hunk 1 above)
Comment (MikeSpreitzer) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: oops, right.  Will fix if/when there is a next rev.

Comment (roberthbailey) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: That's the only thing that needs changing. Can you push a new version with this fix so we can get this merged?

**Comment by MikeSpreitzer** [comment]
I'm a little unsure of the status here.  @roberthbailey do you need that little syntax fix?  You marked this as OK to merge but I see a complaint from the Submit Queue that there is no LGTM.

**Comment by roberthbailey** [comment]
ok-to-merge and lgtm are separate labels. I'll apply lgtm once you fix the code.

**Comment by MikeSpreitzer** [comment]
@roberthbailey: I fixed the syntax oversight.

**Comment by roberthbailey** [comment]
Thanks.

**Comment by MikeSpreitzer** [comment]
What's holding this up?

**Comment by roberthbailey** [comment]
It's in the queue for merging by the merge bot. You can follow along at http://submit-queue.k8s.io/.

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: #21244
