### PR TITLE
fix detach azure disk issue due to dirty cache

### LINKED ISSUE #71453: Azure Disks occasionally mounted in a way leading to I/O errors
**What happened**:

Azure Disks get randomly mounted in a way that makes then unusable, returning `Input/output error` for every disk I/O operation. Affected Pods remain in `CrashLoopBack` until someone manually recreates them.

**What you expected to happen**:

Azure Disks are consistently usable.

**How to reproduce it**:

Create the following StatefulSet. Adjust the replicas and delete the associated Pods (`kubectl delete pod -l app=azure-disk-failure`) until the problem occurs (i.e. some Pod ends up in `CrashLoopBackOff`).

<details>
<summary>sts.yaml</summary>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: azure-disk-failure
spec:
  ports:
  - port: 65535
    targetPort: 65535
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azure-disk-failure
spec:
  podManagementPolicy: Parallel
  serviceName: azure-disk-failure
  replicas: 3
  selector:
    matchLabels:
      app: azure-disk-failure
  template:
    metadata:
      labels:
        app: azure-disk-failure
    spec:
      containers:
      - image: busybox
        name: touch
        command:
        - sh
        - -c
        args:
        - "touch /vol/$(date '+%Y%m%d%H%M%S') && sleep 9999999999"
        volumeMounts:
        - mountPath: /vol
          name: azure-disk
      terminationGracePeriodSeconds: 1
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: azure-disk
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
```

</details></br>

Default StorageClass (as created by ACS-Engine):

<details>
<summary>sc.yaml</summary>

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
  name: default
parameters:
  cachingmode: None
  kind: Managed
  storageaccounttype: Standard_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

</details></br>

**Anything else we need to know?**:

According to [this document](https://github.com/andyzhangx/demo/blob/master/issues/azuredisk-issues.md#2-disk-unavailable-after-attachdetach-a-data-disk-on-a-node) written by @andyzhangx the issue is fixed, but I can still observe it quite often.

Ref Azure/acs-engine#1918

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.10
- Cloud provider or hardware configuration: Azure (westeurope)
- OS (e.g. from /etc/os-release): 16.04.4 LTS
- Kernel (e.g. `uname -a`): 4.13.0-1018-azure
- Install tools: ACS-Engine
- Others:

/kind bug
/sig storage
/sig azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix detch azure disk issue by cleaning up vm cache right after every update vm operation in disk attach/detach

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71453

**Special notes for your reviewer**:
When detaching lots of disks in one node, detach failure may happen, in the before, we use backoff mechanism to retries 6 times which is not good solution; now we switch to use k8s controller to detach disk volume, and it finally depends on `DisksAreAttached` func to decide whether one disk is attached or not: 
https://github.com/kubernetes/kubernetes/blob/5dfe48b0ff464ca1f11805079476e72d3fe8ece0/pkg/volume/azure_dd/attacher.go#L135

Unfortunately `DisksAreAttached` func is invoked right after `DetachDiskByName` failure which already make the vm cache **dirty**, this PR makes sure vm cache will be cleaned after every update vm operation in disk attach/detach operation. And this PR will also solve strange issue, e.g. detach disk failure due to the last attach disk failure.

The invocation chain for using `vmCache` in `DisksAreAttached` func:
```
DisksAreAttached --> getNodeDataDisks--> GetDataDisks --> getVirtualMachine --> vmCache.Get
```

```
I1128 05:04:58.206841       1 attacher.go:145] azureDisk - VolumesAreAttached: check volume "andy-vmss11010-dynamic-pvc-884809b5-f2ca-11e8-a757-000d3a01450e" (specName: "pvc-884809b5-f2ca-11e8-a757-000d3a01450e") is no longer attached
I1128 05:04:58.206945       1 operation_generator.go:193] VerifyVolumesAreAttached determined volume "kubernetes.io/azure-disk//subscriptions/.../resourceGroups/andy-vmss11010/providers/Microsoft.Compute/disks/andy-vmss11010-dynamic-pvc-049158b4-f2ba-11e8-ade9-000d3a01450e" (spec.Name: "pvc-049158b4-f2ba-11e8-ade9-000d3a01450e") is no longer attached to node "k8s-agentpool-39687990-vmss000000", therefore it was marked as detached.
```

**Release note**:
```
fix detach azure disk issue
```

/sig azure
/assign @feiskyer 
cc @khenidak @brendandburns 
@antoineco

### CODE REVIEW

**Comment by feiskyer** [comment]
Added to v1.13 since this is a critical bug fix.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by AishSundar** [comment]
@andyzhangx @feiskyer is this an issue introduced recently in 1.13 that we are trying to address with this fix? Are there CI tests to verify the goodness of the fix? We are very late in the 1.13 release cycle and I would like to avoid any code churn unless it is a critical urgent issue introduced in 1.13. Can this wait until 1.13.1?

/hold

**Comment by andyzhangx** [comment]
Hi @AishSundar, we are going to fix the issue right in v1.13.0, and the code change only remains in azure directory. It's important for this fix fit into v1.13.0, thanks.

File: pkg/cloudprovider/providers/azure/azure_controller_vmss.go [hunk 1]
```diff
@@ -71,8 +71,12 @@ func (ss *scaleSet) AttachDisk(isManagedDisk bool, diskName, diskURI string, nod
 
 	ctx, cancel := getContextWithCancel()
 	defer cancel()
-	klog.V(2).Infof("azureDisk - update(%s): vm(%s) - attach disk(%s)", nodeResourceGroup, nodeName, diskName)
 
+	// Invalidate the cache right after updating
+	key := buildVmssCacheKey(nodeResourceGroup, ss.makeVmssVMName(ssName, instanceID))
+	defer ss.vmssVMCache.Delete(key)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_controller_vmss.go]: here is the PR for this dirty cache issue, originally whether succeed or not, this PR clean the cache anyway.
I can move this clean cache operation `defer ss.vmssVMCache.Delete(key)` to conditions when only error happens, would that solve your issue @khenidak ?I can build one hot fix image if you wan to try this fix.
cc@feiskyer
