### PR TITLE
fix a data race in volume reconciler ut #99815

### LINKED ISSUE #99815: [flaky test] Test_Run_Positive_VolumeFSResizeControllerAttachEnabled
#### Which jobs are flaking:

pull-kubernetes-unit

#### Which test(s) are flaking:

`k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler`: `Test_Run_Positive_VolumeFSResizeControllerAttachEnabled/expand-fs-volume_with_in-use_error`

#### Testgrid link:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99810/pull-kubernetes-unit/1367610862453395456

(PR with no go code changes, should not have failed any unit tests)

#### Reason for failure:

```
=== RUN   Test_Run_Positive_VolumeFSResizeControllerAttachEnabled
=== CONT  Test_Run_Positive_VolumeFSResizeControllerAttachEnabled
    testing.go:1093: race detected during execution of test
--- FAIL: Test_Run_Positive_VolumeFSResizeControllerAttachEnabled (0.52s)
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/sig storage

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test
/kind flake

#### What this PR does / why we need it:

Try to fix the DATA RACE in #99815

I can reproduce it in local(`stress -p 10`)
14m35s: 163 runs so far, 2 failures

With the fix:(`stress -p 40`)
- 28m20s: 1080 runs so far, 0 failures

#### Which issue(s) this PR fixes:
Fixes #99815 #94568

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 1]
```diff
@@ -1138,17 +1138,18 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
...
 			}()
 			waitForMount(t, fakePlugin, volumeName, asw)
 			// Stop the reconciler.
 			close(stopChan)
 			<-stoppedChan
 
 			// Simulate what DSOWP does
-			pv.Spec.Capacity[v1.ResourceStorage] = tc.newPVSize
-			volumeSpec = &volume.Spec{PersistentVolume: pv}
+			pvWithSize := pv.DeepCopy()
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1150]: maybe add a comment briefly explained why this is needed?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 2]
```diff
@@ -1831,8 +1832,9 @@ func Test_Run_Positive_VolumeMountControllerAttachEnabledRace(t *testing.T) {
 		// Act:
 		// 3. While a volume is being unmounted, add it back to the desired state of world
 		t.Logf("UnmountDevice called")
+		volumeSpecCopy := volumeSpec.DeepCopy()
 		generatedVolumeName, err = dsw.AddPodToVolume(
-			podName, pod, volumeSpec, volumeSpec.Name(), "" /* volumeGidValue */)
+			podName, pod, volumeSpecCopy, volumeSpec.Name(), "" /* volumeGidValue */)
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1837]: is there a test failure for this?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 1 above)
Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: 👌

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 2 above)
Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1837]: similiar issue, I found it in local ‘stress’ testing.

**Comment by pacoxu** [comment]
Updated. Add comments and test locally for 1000 runs.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 2 above)
Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1839]: #94568 I checked the error message is the same.

**Comment by pacoxu** [comment]
Should this be in 1.21?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 3]
```diff
@@ -1138,17 +1140,17 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
 			// Start the reconciler to fill ASW.
 			stopChan, stoppedChan := make(chan struct{}), make(chan struct{})
 			go func() {
+				defer close(stoppedChan)
 				reconciler.Run(stopChan)
```
Comment (mauriciopoppe) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1144]: this `defer` is interesting, in what case `reconciler.Run` would throw an error so that `close` is not called?

Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1144]: I just think “defer” will avoid hanging here.

This defer is not related with the date race.

Comment (mauriciopoppe) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1144]: I was just curious about the why, I believe that if there's an error in `reconciler.Run` the test would fail and cleanup at that point wouldn't affect the result of the test, I don't think that reverting this part is necessary, thanks for the explanation

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 1 above)
Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: did you add it somewhere?

Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: I need to update the commit message later.

The comment was  updated. Would you check if it makes sense？

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: sure, The reason I care about this part is that I want to make sure the tests are doing something represent the real case. For example, we might discover sometimes in the actual code we also need to use deepcopy to avoid race condition. But in this case, only test needs to use deepcopy of object because it represents the real case, I think. Does it make sense?

Comment (pacoxu) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: I think I should go through the volume reconciling logics to figure out whether it has a potential data race problem in real cluster.

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: I checked the first fix, I think it is good, but I haven't checked the second one. Thanks!

**Comment by xing-yang** [comment]
@jingxu97 do you have more comments?

**Comment by jingxu97** [comment]
just want to confirm https://github.com/kubernetes/kubernetes/pull/100215#discussion_r595488744
