### PR TITLE
fix pod created failed when resource request is 0

### LINKED ISSUE #109191: pod created failed when devices resource request is 0
### What happened?

1 create deployment by yaml below
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jktest
spec:
  selector:
    matchLabels:
      workload.es.io: jktest
  template:
    metadata:
      labels:
        workload: jktest
    spec:
      containers:
      - image: centos:latest
        imagePullPolicy: IfNotPresent
        name: test
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: "0"
          requests:
            cpu: 250m
            memory: 512Mi
            nvidia.com/gpu: "0"
```

2 create pod failed, the reason is 

```
status:
  message: >-
    Pod Node didn't have enough resource: nvidia.com/gpu, requestd: 0, used: 1,
    capacity: 0
  phase: Failed
  reason: OutOfnvidia.com/gpu
  startTime: '2022-02-02T12:40:19Z'  
```

### What did you expect to happen?

expect the pod create success, the request resource is 0, and it must not exceed

so it failed by somewhere unreasonable judgment

### How can we reproduce it (as minimally and precisely as possible)?

1 create pod `a` which use hot pluggable device in resource.request, and the resource is 1
2 remove device
3 create pod `b` which use hot pluggable device in resource.request, and the ressource is 0

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15", GitCommit:"4a89df5617b8e1e26abb16150502d04e6c180533", GitTreeState:"clean", BuildDate:"2022-03-26T06:34:08Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

kubespray

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jlsong01**
#### What type of PR is this?
/kind bug
/sig node

#### What this PR does / why we need it:
Pod creation should not fail in case request resource is zero.

In terms of tolerating 0-requested req in scheduler, it's a good-to-have and not a root fix to this issue (https://github.com/kubernetes/kubernetes/issues/109191#issuecomment-1084540901)

#### Which issue(s) this PR fixes:

Relevant to #109191

#### Special notes for your reviewer:
This PR mitigates (when req is 0) instead of fixing the original issue.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by yxxhero** [comment]
@jlsong01 Please add some unittest for this PR. Thanks very much.

**Comment by jlsong01** [comment]
> @jlsong01 Please add some unittest for this PR. Thanks very much.

@yxxhero thanks for your comments. unit test has been added.

**Comment by yxxhero** [comment]
@jlsong01 Is it more elegant to use `switch`? Thanks very much.

**Comment by kerthcet** [comment]
Add comment at https://github.com/kubernetes/kubernetes/issues/109191#issuecomment-1202137761, I may treat this not fix the bug, but related, for request values are not right even with this patch.

File: pkg/scheduler/framework/plugins/noderesources/fit.go [hunk 1]
```diff
@@ -311,7 +311,11 @@ func fitsRequest(podRequest *preFilterState, nodeInfo *framework.NodeInfo, ignor
 				continue
 			}
 		}
-		if rQuant > (nodeInfo.Allocatable.ScalarResources[rName] - nodeInfo.Requested.ScalarResources[rName]) {
+
+		// Skip in case request quantity is zero
+		if rQuant == 0 {
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/noderesources/fit.go:316]: let's add this to the head of the loop, it's more efficient.

File: pkg/scheduler/framework/plugins/noderesources/fit_test.go [hunk 2]
```diff
@@ -462,6 +462,18 @@ func TestEnoughRequests(t *testing.T) {
...
 		},
+		{
+			pod: newResourcePod(
+				framework.Resource{
+					MilliCPU: 1,
+					Memory:   1,
+					ScalarResources: map[v1.ResourceName]int64{
+						kubernetesIOResourceA: 0,
+					}}),
+			nodeInfo:                  framework.NewNodeInfo(newResourcePod(framework.Resource{MilliCPU: 0, Memory: 0})),
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/noderesources/fit_test.go:473]: Can we cover this case with `(nodeInfo.Allocatable.ScalarResources[rName] - nodeInfo.Requested.ScalarResources[rName]) < 0`, which mocks the bug we met.

File: pkg/scheduler/framework/plugins/noderesources/fit.go (hunk 1 above)
Comment (jlsong01) [reply pkg/scheduler/framework/plugins/noderesources/fit.go]: done

File: pkg/scheduler/framework/plugins/noderesources/fit_test.go (hunk 2 above)
Comment (jlsong01) [reply pkg/scheduler/framework/plugins/noderesources/fit_test.go]: Sure. updated the case as `allocatable` 5 and `Requested` 6 for `extendedResourceA`, which should hit the bug we met.

**Comment by jlsong01** [comment]
> @jlsong01 Is it more elegant to use `switch`? Thanks very much.

@yxxhero yeah, `switch` is more elegant. since the case has been moved to the head of the loop, IMO, we need not it anymore.  anyway, thanks for the suggestion.

**Comment by kerthcet** [comment]
Totally looks good to me, so I labelled with LGTM, but we may get some advices from sig-node expert. Although we changed codes in scheduler, but this is a common function shared by scheduler and kubelet. See https://github.com/kubernetes/kubernetes/blob/cb41d5002ccde5f457989f157dd9e047e5bacdb6/pkg/kubelet/lifecycle/predicate.go#L263
cc @mrunalp
/lgtm

**Comment by kerthcet** [comment]
Besides, we're code freeze now, we may merge this PR in the next release v1.26.

**Comment by jlsong01** [comment]
/assign @huang-wei
for approval

**Comment by Huang-Wei** [comment]
@jlsong01 could you revise the description section a bit - as commented in the original issue https://github.com/kubernetes/kubernetes/issues/109191#issuecomment-1207302039: this PR mitigates (when req is 0) instead of fixing the original issue.

**Comment by jlsong01** [comment]
> @jlsong01 could you revise the description section a bit - as commented in the original issue [#109191 (comment)](https://github.com/kubernetes/kubernetes/issues/109191#issuecomment-1207302039): this PR mitigates (when req is 0) instead of fixing the original issue.

@Huang-Wei Done. If anything else needed, please let me know :-)
