### PR TITLE
1.20 Cherry-pick: Fixed the Dockerfile for the build-image to build from KUBE_BASE_IMAGE_REGISTRY

### LINKED ISSUE #99238: Add ability to pull all build images through external registry
There seems to be an environment variable called `KUBE_DOCKER_REGISTRY` which only seems to partially do what I'm asking, but it is not implemented throughout the entirety of Kubernetes.

Here are a couple of examples throughout Kubernetes that are easily greped but there are plenty more examples
- https://github.com/kubernetes/kubernetes/blob/c2e90d8baf65b23df4f2b833834916c965fb57cd/build/workspace.bzl#L128
- https://github.com/kubernetes/kubernetes/blob/e05f4a3facd4106bccdc5ef9eb9401c38391857d/build/build-image/Dockerfile#L18

/sig release

### PR DESCRIPTION
**Pull request by Joseph-Goergen**
Cherry-pick of #99592

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes the issue of with the KUBE_BASE_IMAGE_REGISTRY variable not being used for the build-image Dockerfile

#### Which issue(s) this PR fixes:

Fixes #99238

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
/ok-to-test

For `build/`:
/lgtm
/approve

**Review by hasheddan — APPROVED** [review]
/lgtm

File: build/common.sh [hunk 1]
```diff
@@ -247,27 +247,6 @@ function kube::build::ensure_rsync() {
...
-  if [[ -n "${KUBERNETES_HTTPS_PROXY:-}" ]]; then
-    echo "ENV https_proxy $KUBERNETES_HTTPS_PROXY" >> "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"
-  fi
-  if [[ -n "${KUBERNETES_HTTP_PROXY:-}" ]]; then
-    echo "ENV http_proxy $KUBERNETES_HTTP_PROXY" >> "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"
-  fi
-  if [[ -n "${KUBERNETES_NO_PROXY:-}" ]]; then
-    echo "ENV no_proxy $KUBERNETES_NO_PROXY" >> "${LOCAL_OUTPUT_BUILD_CONTEXT}/Dockerfile"
-  fi
-}
```
Comment (liggitt) [inline build/common.sh:269]: this spuriously picked up changes from https://github.com/kubernetes/kubernetes/pull/97618/files#diff-64833c91e011032ba2c7a5d17a52dd97ff3d10ecc644ffbfad15259718c75813L259
