### PR TITLE
Fix panic because VolumeSpec may be nil in volume reconstruction scenario

### LINKED ISSUE #74384: LocalVolumeType: gce-localssd-scsi-fs tests are failing
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
LocalVolumeType: gce-localssd-scsi-fs

**Since when has it been failing**:
2/20

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4710

**Reason for failure**:
unsure yet

/assign

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74384

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cofyc** [comment]
/sig storage
/priority important-soon
/assign @msau42 
cc @jingxu97

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -732,7 +732,7 @@ func (og *operationGenerator) GenerateUnmountVolumeFunc(
 	podsDir string) (volumetypes.GeneratedOperations, error) {
 
 	var pluginName string
-	if useCSIPlugin(og.volumePluginMgr, volumeToUnmount.VolumeSpec) {
+	if volumeToUnmount.VolumeSpec != nil && useCSIPlugin(og.volumePluginMgr, volumeToUnmount.VolumeSpec) {
```
Comment (msau42) [inline pkg/volume/util/operationexecutor/operation_generator.go]: I think we should return an error in ConstructVolumeSpec() instead if we can't support reconstruction, like [here](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/glusterfs/glusterfs.go#L232).

This will cause the Unmount() to happen, which will fix the filesystem-based paths, however block-based paths will not work because UnmountDevice() is still not called.

Comment (msau42) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Does raw block reconstruction have a similar issue? We don't have tests for raw block reconstruction: https://github.com/kubernetes/kubernetes/issues/74545

Comment (msau42) [reply pkg/volume/util/operationexecutor/operation_generator.go]: cc @gnufied

Comment (msau42) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I discussed some more with @jingxu97, and she pointed out that even if we return error in ConstructVolumeSpec(), the volumeSpec will still be nil here, so we still need this check.

It looks like this check was introduced as part of CSI migration. 1) This should be feature gated, and 2) can `useCSIPlugin` return false if volume spec is nil? Does that make sense for all operations? cc @davidz627

**Comment by msau42** [comment]
/lgtm
/approve
to fix the failing tests

We can followup on the remaining items, which I will open issues for

**Comment by cofyc** [comment]
/hold
to check block device

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (davidz627) [reply pkg/volume/util/operationexecutor/operation_generator.go]: for 1) I've submitted a PR to make sure we do the migration feature gate check before doing anything else.

For 2) I think I need to do some more investigation and address it in the CSI Migration Reconstruction design.
