### PR TITLE
Addon Manager: Fix parsing KUBECTL_EXTRA_PRUNE_WHITELIST

### LINKED ISSUE #85343: Addon Manager: wrong processing of KUBECTL_EXTRA_PRUNE_WHITELIST
**What happened**:
Regression in 1.17 introduced by #82237
When there are several items passed using KUBECTL_EXTRA_PRUNE_WHITELIST flag,
cluster/addons/addon-manager/kube-addons.sh generates wrong flags for kubectl:

```
kubectl ... --prune-whitelist parameter1 parameter2 ...
```

Which causes:

```
error: Unexpected args: [parameter2]
See 'kubectl apply -h' for help and examples
```

**What you expected to happen**:
It should generate:

```
kubectl ... --prune-whitelist parameter1 --prune-whitelist parameter2 ...
```

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBECTL_EXTRA_PRUNE_WHITELIST=parameter1 parameter2
cluster/addons/addon-manager/kube-addons.sh
```

**Anything else we need to know?**:
/sig release

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.*

### PR DESCRIPTION
**Pull request by jkaniuk**
When there are two or more parameters it should result in:

```
kubectl ... --prune-whitelist paramter1 --prune-whitelist parameter2 ...
```

but it wrongly generates:

```
kubectl ... --prune-whitelist parameter1 parameter2 ...
```

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes parsing of KUBECTL_EXTRA_PRUNE_WHITELIST in cluster/addons/addon-manager/kube-addons.sh

**Which issue(s) this PR fixes**:

Fixes #85343

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

/sig release

### CODE REVIEW

File: cluster/addons/addon-manager/kube-addons.sh [hunk 1]
```diff
@@ -120,7 +120,8 @@ function generate_prune_whitelist_flags() {
 # besides the default ones.
 extra_prune_whitelist=
 if [ -n "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" ]; then
-  extra_prune_whitelist=( "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" )
+  # Quotes break parsing space separated values
```
Comment (mm4tt) [inline cluster/addons/addon-manager/kube-addons.sh]: This comment might be hard to understand after some time as it hard to say what quotes it refers to.
Could you rewrite to smth like:
```
# Note: we cannot have ( "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" ) as quotes break parsing space separated values
```

Comment (jkaniuk) [reply cluster/addons/addon-manager/kube-addons.sh]: Done

File: cluster/addons/addon-manager/kube-addons.sh [hunk 2]
```diff
@@ -120,7 +120,9 @@ function generate_prune_whitelist_flags() {
 # besides the default ones.
 extra_prune_whitelist=
 if [ -n "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" ]; then
-  extra_prune_whitelist=( "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" )
+  # Note: we cannot have ( "${KUBECTL_EXTRA_PRUNE_WHITELIST:-}" )
+  # as quotes break parsing space separated values
+  extra_prune_whitelist=( ${KUBECTL_EXTRA_PRUNE_WHITELIST:-} )
```
Comment (BenTheElder) [inline cluster/addons/addon-manager/kube-addons.sh]: Space splitting is an anti-pattern though :/

Comment (BenTheElder) [reply cluster/addons/addon-manager/kube-addons.sh]: We need a `# shellcheck disable=SC2206` here

**Comment by BenTheElder** [comment]
/lgtm cancel
(To avoid /retest spam)
This is going to fail until the shellcheck exclusion is added either as a comment disabling that check here, or the file is added back to the known failures list. The former should be reasonable.

**Comment by liggitt** [comment]
and now shellcheck fails on this file again

**Comment by liggitt** [comment]
fixing a regression, release blocking

**Comment by dims** [comment]
@jkaniuk can you please fix the shellcheck?

File: cluster/addons/addon-manager/kube-addons.sh (hunk 2 above)
Comment (jkaniuk) [reply cluster/addons/addon-manager/kube-addons.sh]: Replaced with `read -ra`
