### PR TITLE
fix #40123: add a periodical polling to update pod config

### LINKED ISSUE #40123: Regression: kubelet inotify does not detect changed symlink targets
In k8s 1.4, we were able to set up a symlink from `/etc/kubernetes/manifests/etcd.manifest` to a mountpoint (`/mnt/etcd-volume/k8s.io/etcd.manifest`), to ensure that the pod could not be started before the volume was mounted.

k8s 1.5 broke this: the inotify poller does not detect when the volume is mounted, because the inotify watch does not traverse symlinks: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file_linux.go#L58

Also:

* We probably should include `IN_ATTRIB` so that users can touch the file / symlink
* We probably need to move to fsnotify, or create our own fork of inotify, because inotify has been deleted: https://github.com/golang/exp/tree/master/inotify  (It's 300 lines, mostly symbol definitions, we should probably bring it in to k8s)
* I suggest we should probably have a time based poll in addition, to catch anything the inotify misses
* It is unsafe to ignore IN_Q_OVERFLOW, I believe

cc @dchen1107

### PR DESCRIPTION
**Pull request by wu8685**
Fixes #40123

### CODE REVIEW

**Comment by wu8685** [comment]
I signed

**Comment by wu8685** [comment]
I signed it

**Comment by yujuhong** [comment]
Adding a couple more folks to see who has the bandwidth to review: @dashpole @yguo0905 @mtaufen 
In short, in 1.5, kubelet switched to using inotify to detect changes in the pod manifest directory. This is not completely reliable on its own and it needs periodic polling as a fallback.

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by wu8685** [comment]
PTAL

**Comment by wu8685** [comment]
@k8s-bot unit test this

**Comment by wu8685** [comment]
@k8s-bot verify test this

File: pkg/kubelet/config/file_linux.go [hunk 1]
```diff
@@ -115,14 +119,20 @@ func (s *sourceFile) processEvent(e *inotify.Event) error {
...
 		if objKey, keyExist := s.fileKeyMapping[e.Name]; keyExist {
 			pod, podExist, err := s.store.GetByKey(objKey)
 			if err != nil {
 				return err
 			} else if !podExist {
 				return fmt.Errorf("the pod with key %s doesn't exist in cache", objKey)
 			} else {
-				return s.store.Delete(pod)
+				err = s.store.Delete(pod)
+				if err != nil {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux.go]: does it make sense to delete it from `fileKeyMapping` if you couldn't delete from `store`?

File: pkg/kubelet/config/file_test.go [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+	defer os.RemoveAll(dirName)
+
+	ch := make(chan interface{}, 1)
+	c := new(dirName, "localhost", time.Millisecond, ch)
+	err = c.fullScan()
+	if err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	update := (<-ch).(kubetypes.PodUpdate)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: maybe `update, ok :=` form so that you can print an informative fatal error if this assertion fails, rather than a panic

File: pkg/kubelet/config/file_unsupported.go [hunk 3]
```diff
@@ -19,8 +19,11 @@ limitations under the License.
...
-import "errors"
+import (
+	"errors"
+	"time"
+)
 
-func (s *sourceFile) watch() error {
-	return errors.New("source file is unsupported in this build")
+func (s *sourceFile) watch() {
+	// watching source file is unsupported in this build
```
Comment (mtaufen) [inline pkg/kubelet/config/file_unsupported.go]: Why not at least log an error here?

File: pkg/kubelet/config/file_linux.go (hunk 1 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: Its a mistake, I correct it

File: pkg/kubelet/config/file_unsupported.go (hunk 3 above)
Comment (wu8685) [inline pkg/kubelet/config/file_unsupported.go]: On none linux platform, a periodical `reloadConfig` can also work well, so I think leaving this method empty is ok.

Comment (mtaufen) [inline pkg/kubelet/config/file_unsupported.go]: I still don't see why you wouldn't want to log an error, so anyone using watch on non-linux platform will be alerted that the watch they are using is not implemented.

Comment (wu8685) [inline pkg/kubelet/config/file_unsupported.go]: Sorry for missing your comment.
I have added the error log. PTAL.

File: pkg/kubelet/config/file_linux_test.go [hunk 4]
```diff
@@ -250,7 +223,18 @@ func (tc *testCase) writeToFile(dir, name string, t *testing.T) string {
 	return fileName
 }
 
-func watchFileAdded(watchDir bool, t *testing.T) {
+func (tc *testCase) writeSymblicLink(dir, linkedDir, name string, t *testing.T) string {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: s/Symblic/Symbolic

Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Why is this a method on testCase? It doesn't require any of the state in the testCase object.

Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Also please use clearer argument names to indicate the direction of the link, e.g. `sourcedir`, `destdir`.

File: pkg/kubelet/config/file_linux_test.go [hunk 5]
```diff
@@ -262,7 +246,17 @@ func watchFileAdded(watchDir bool, t *testing.T) {
...
+
 			fileName := fmt.Sprintf("%s_%d", fileNamePre, index)
+			var linkedDirName string
+			if isSymbol {
+				linkedDirName, err = utiltesting.MkTmpdir("linked-dir-test")
+				if err != nil {
+					t.Fatalf("unable to create temp dir for linked files: %v", err)
+				}
+				defer os.RemoveAll(linkedDirName)
+				testCase.writeSymblicLink(dirName, linkedDirName, fileName, t)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: s/Symblic/Symbolic

File: pkg/kubelet/config/file_linux_test.go [hunk 6]
```diff
@@ -250,7 +223,18 @@ func (tc *testCase) writeToFile(dir, name string, t *testing.T) string {
...
+	linkedFile := filepath.Join(linkedDir, name)
+
+	err := os.Symlink(linkedFile, linkName)
+	if err != nil {
+		t.Fatalf("unexpected error when create symbolic link: %v", err)
+	}
+	return linkName
+}
+
+func watchFileAdded(watchDir bool, isSymbol bool, t *testing.T) {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Does `isSymbol bool` indicate whether it's a symbolic link? `isSymlink bool` or even just `symlink bool` would be clearer.

File: pkg/kubelet/config/file_linux_test.go [hunk 7]
```diff
@@ -262,7 +246,17 @@ func watchFileAdded(watchDir bool, t *testing.T) {
 				t.Fatalf("unable to create temp dir: %v", err)
 			}
 			defer os.RemoveAll(dirName)
+
 			fileName := fmt.Sprintf("%s_%d", fileNamePre, index)
+			var linkedDirName string
+			if isSymbol {
+				linkedDirName, err = utiltesting.MkTmpdir("linked-dir-test")
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: I'm not a huge fan of relying on testing utilities that were written specifically for other packages and live in other repos, there's no guarantee they won't change all-of-a-sudden and break your tests.

File: pkg/kubelet/config/file_linux_test.go [hunk 8]
```diff
@@ -288,7 +286,7 @@ func watchFileAdded(watchDir bool, t *testing.T) {
 	}
 }
 
-func watchFileChanged(watchDir bool, t *testing.T) {
+func watchFileChanged(watchDir bool, isSymbol bool, t *testing.T) {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Again, I feel something like `symlink bool` would be a clearer argument name.

File: pkg/kubelet/config/file_linux_test.go [hunk 9]
```diff
@@ -302,13 +300,27 @@ func watchFileChanged(watchDir bool, t *testing.T) {
...
 			defer os.RemoveAll(dirName)
 
+			var linkedDirName string
+			if isSymbol {
+				linkedDirName, err = utiltesting.MkTmpdir("linked-dir-test")
+				if err != nil {
+					t.Fatalf("unable to create temp dir for linked files: %v", err)
+				}
+				defer os.RemoveAll(linkedDirName)
+				testCase.writeSymblicLink(dirName, linkedDirName, fileName, t)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: s/Symblic/Symbolic

File: pkg/kubelet/config/file_linux_test.go [hunk 10]
```diff
@@ -262,7 +246,17 @@ func watchFileAdded(watchDir bool, t *testing.T) {
...
 			defer os.RemoveAll(dirName)
+
 			fileName := fmt.Sprintf("%s_%d", fileNamePre, index)
+			var linkedDirName string
+			if isSymbol {
+				linkedDirName, err = utiltesting.MkTmpdir("linked-dir-test")
+				if err != nil {
+					t.Fatalf("unable to create temp dir for linked files: %v", err)
+				}
+				defer os.RemoveAll(linkedDirName)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: os.RemoveAll can return an error, you should handle it

File: pkg/kubelet/config/file_linux_test.go [hunk 11]
```diff
@@ -302,13 +300,27 @@ func watchFileChanged(watchDir bool, t *testing.T) {
 			}
 			defer os.RemoveAll(dirName)
 
+			var linkedDirName string
+			if isSymbol {
+				linkedDirName, err = utiltesting.MkTmpdir("linked-dir-test")
+				if err != nil {
+					t.Fatalf("unable to create temp dir for linked files: %v", err)
+				}
+				defer os.RemoveAll(linkedDirName)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: os.RemoveAll can return an error

File: pkg/kubelet/config/file_linux_test.go [hunk 12]
```diff
@@ -332,7 +344,11 @@ func watchFileChanged(watchDir bool, t *testing.T) {
 				pod.Spec.Containers[0].Name = "image2"
 
 				testCase.expected.Pods[0].Spec.Containers[0].Name = "image2"
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Editing the test case mid-test is unexpected, but it was already here so... maybe clean this up in a separate PR.

File: pkg/kubelet/config/file_linux_test.go [hunk 13]
```diff
@@ -370,6 +386,10 @@ func expectUpdate(t *testing.T, ch chan interface{}, testCase *testCase) {
 		select {
 		case got := <-ch:
 			update := got.(kubetypes.PodUpdate)
+			if len(update.Pods) == 0 {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: Was there a specific reason they weren't being filtered before or is this just fixing a bug in the tests?

File: pkg/kubelet/config/file_test.go [hunk 14]
```diff
@@ -0,0 +1,75 @@
+/*
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: I will swing back around to review this file tomorrow morning.

**Review by mtaufen — COMMENTED** [review]
Comments so far, I still have some more to review.

File: pkg/kubelet/config/file_test.go [hunk 15]
```diff
@@ -0,0 +1,75 @@
...
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	update, ok := (<-ch).(kubetypes.PodUpdate)
+	if !ok {
+		t.Fatalf("unexpected type")
+	}
+	expected := CreatePodUpdate(kubetypes.SET, kubetypes.FileSource)
+	if !apiequality.Semantic.DeepEqual(expected, update) {
+		t.Fatalf("expected %#v, Got %#v", expected, update)
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: nit: s/Got/got

File: pkg/kubelet/config/file_linux_test.go (hunk 13 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux_test.go]: In some test, the watched path doesn't exist at the beginning, so a empty pods will be [reported](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file.go#L92). It is what this code filter for

File: pkg/kubelet/config/file.go [hunk 16]
```diff
@@ -38,15 +39,17 @@ import (
...
 	path           string
 	nodeName       types.NodeName
+	period         time.Duration
 	store          cache.Store
 	fileKeyMapping map[string]string
 	updates        chan<- interface{}
+	locker         sync.Locker
 }
 
 func NewSourceFile(path string, nodeName types.NodeName, period time.Duration, updates chan<- interface{}) {
```
Comment (wu8685) [inline pkg/kubelet/config/file.go]: I made some changes PTAL

**Comment by wu8685** [comment]
hi @mtaufen , I have committed some fixes. How about the code review now? Shall we go on?

File: pkg/kubelet/config/file_linux_test.go [hunk 17]
```diff
@@ -274,12 +268,16 @@ func watchFileAdded(watchDir bool, t *testing.T) {
 
 			addFile := func() {
 				// Add a file
-				testCase.writeToFile(dirName, fileName, t)
+				if !symlink {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: why not flip these cases and just do `if symlink`

File: pkg/kubelet/config/file_linux_test.go [hunk 18]
```diff
@@ -288,27 +286,41 @@ func watchFileAdded(watchDir bool, t *testing.T) {
...
+			}
 
 			var file string
 			lock := &sync.Mutex{}
 			ch := make(chan interface{})
 			func() {
 				lock.Lock()
 				defer lock.Unlock()
-				file = testCase.writeToFile(dirName, fileName, t)
+				if !symlink {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: same here, why not flip the cases and just do `if symlink`

File: pkg/kubelet/config/file_linux_test.go [hunk 19]
```diff
@@ -332,7 +344,11 @@ func watchFileChanged(watchDir bool, t *testing.T) {
 				pod.Spec.Containers[0].Name = "image2"
 
 				testCase.expected.Pods[0].Spec.Containers[0].Name = "image2"
-				testCase.writeToFile(dirName, fileName, t)
+				if !symlink {
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: as above

File: pkg/kubelet/config/file_test.go [hunk 20]
```diff
@@ -0,0 +1,75 @@
...
+	"testing"
+	"time"
+
+	apiequality "k8s.io/apimachinery/pkg/api/equality"
+	utiltesting "k8s.io/client-go/util/testing"
+	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
+)
+
+func TestExtractFromBadDataFile(t *testing.T) {
+	dirName, err := utiltesting.MkTmpdir("file-test")
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: use your mkTmpdir function here too instead of relying on client-go's testing helpers

File: pkg/kubelet/config/file_test.go [hunk 21]
```diff
@@ -0,0 +1,75 @@
...
+	lw := newSourceFileListerWatcher(fileName, "localhost", time.Millisecond, ch)
+	err = lw.listConfig()
+	if err == nil {
+		t.Fatalf("expected error, got nil")
+	}
+	expectEmptyChannel(t, ch)
+}
+
+func TestExtractFromEmptyDir(t *testing.T) {
+	dirName, err := utiltesting.MkTmpdir("file-test")
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: again

File: pkg/kubelet/config/file_test.go [hunk 22]
```diff
@@ -0,0 +1,75 @@
...
+	ch := make(chan interface{}, 1)
+	lw := newSourceFileListerWatcher(dirName, "localhost", time.Millisecond, ch)
+	err = lw.listConfig()
+	if err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	update, ok := (<-ch).(kubetypes.PodUpdate)
+	if !ok {
+		t.Fatalf("unexpected type")
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: log what you actually got with `%#v`

File: pkg/kubelet/config/file_test.go [hunk 23]
```diff
@@ -0,0 +1,75 @@
...
+	err = ioutil.WriteFile(fileName, []byte{1, 2, 3}, 0555)
+	if err != nil {
+		t.Fatalf("unable to write test file %#v", err)
+	}
+
+	ch := make(chan interface{}, 1)
+	lw := newSourceFileListerWatcher(fileName, "localhost", time.Millisecond, ch)
+	err = lw.listConfig()
+	if err == nil {
+		t.Fatalf("expected error, got nil")
```
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: It would be better to test the error message to see if it matches what you expect, and also fail if you get an unexpected error.

**Review by mtaufen — COMMENTED** [review]
Sorry it took me a few days to get to this. I have some additional comments for you to address. Thanks for being patient :)

File: pkg/kubelet/config/file_linux_test.go (hunk 17 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux_test.go]: I dont really get your idea. Please check my changes.

**Comment by wu8685** [comment]
Hi @mtaufen I committed some fixes except the `if symlink` case. PTAL.

File: pkg/kubelet/config/file_linux_test.go [hunk 24]
```diff
@@ -107,69 +105,78 @@ func TestReadPodsFromFileExistAlready(t *testing.T) {
 	}
 }
 
+type WatchType int
+type FileType int
+
+const (
+	WATCH_DIR WatchType = iota
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: All-caps consts are unconventional in our codebase, please use camelCase.

File: pkg/kubelet/config/file_linux_test.go [hunk 25]
```diff
@@ -107,69 +105,78 @@ func TestReadPodsFromFileExistAlready(t *testing.T) {
...
+	WATCH_FILE
+
+	FILE FileType = iota
+	SYMLINK
+)
+
+var (
+	watchFileAddedTesters = map[WatchType]map[FileType]func(*testing.T){
```
Comment (mtaufen) [inline pkg/kubelet/config/file_linux_test.go]: You don't need all this extra delegation machinery. 
You only need two test functions:
- `TestWatchFileAdded`
- `TestWatchFileChanged`

And just pass the full boolean matrix in each.

File: pkg/kubelet/config/file_test.go (hunk 23 above)
Comment (mtaufen) [inline pkg/kubelet/config/file_test.go]: I'd still prefer if you test for the specific type of error you expect.

**Comment by wu8685** [comment]
@mtaufen I fixed, PTAL

**Comment by mtaufen** [comment]
Nice work. Please squash your commits and I'll lgtm

**Comment by mtaufen** [comment]
What's the Tune Cinder approvers commit doing in this PR now?

**Comment by wu8685** [comment]
Thanks for your help. It fixed.

**Comment by mtaufen** [comment]
/assign @tallclair
please review and approve

File: pkg/kubelet/config/file_linux.go [hunk 26]
```diff
@@ -40,7 +41,15 @@ const (
 	podDelete
 )
 
-func (s *sourceFile) watch() error {
+func (s *sourceFileListerWatcher) watch() {
+	go wait.Forever(func() {
+		if err := s.doWatch(); err != nil {
+			glog.Errorf("unable to read config path %q: %v", s.path, err)
+		}
+	}, s.period)
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: Why use `s.period` here? `doWatch` contains a watch loop, so this code here should only loop on error. I'd expect the error to be handled, and the watch to be called immediately.

File: pkg/kubelet/config/file.go [hunk 27]
```diff
@@ -62,26 +65,32 @@ func new(path string, nodeName types.NodeName, period time.Duration, updates cha
...
 		updates:        updates,
+		locker:         &sync.Mutex{},
 	}
 }
 
-func (s *sourceFile) run() {
-	if err := s.watch(); err != nil {
-		glog.Errorf("unable to read config path %q: %v", s.path, err)
-	}
+func (s *sourceFileListerWatcher) run() {
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: It's confusing to have both run & watch. Can you ad some comments about why both are used?

File: pkg/kubelet/config/file_linux.go [hunk 28]
```diff
@@ -80,7 +84,7 @@ func (s *sourceFile) watch() error {
 	}
 }
 
-func (s *sourceFile) processEvent(e *inotify.Event) error {
+func (s *sourceFileListerWatcher) processEvent(e *inotify.Event) error {
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: We should handle  IN_ATTRIB too, as described in the issue https://github.com/kubernetes/kubernetes/issues/40123

File: pkg/kubelet/config/file_linux.go [hunk 29]
```diff
@@ -80,7 +84,7 @@ func (s *sourceFile) watch() error {
 	}
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: Rather than creating a separate loop for time-based polling, I would add a ticker or timer to this loop. Then you don't need to worry about locking.

**Review by tallclair — CHANGES_REQUESTED** [review]

File: pkg/kubelet/config/file_linux.go (hunk 26 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: `s.period` could be replaced by a static duration.
A loop around `doWatch` is to keep it continue and retry after err happened like the watched path doesn't exist at the beginning.

File: pkg/kubelet/config/file_linux.go (hunk 29 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: I think its a good way to get rid of the lock. I ll have a try.

File: pkg/kubelet/config/file.go (hunk 27 above)
Comment (wu8685) [inline pkg/kubelet/config/file.go]: I ll take `run & watch` you said as `list & watch`.

Period `list` is added to fully scan files. Some special cases can not be not covered by inotify.

For example, suppose there is a symlink under the watched dir `meta_dir` which is linking a non-existing file. And the linked file is then created, after our `sourceFileWatcher` starts. The `sourceFileWatcher` only using inotify is not able to detect it. This case is tested by `file_linux_test.go.watchFileAdded` with `watchDir=true` and `symlink=true`. If commenting the `list` process, event after adding `IN_ATTRIB`, this case will fail.

File: pkg/kubelet/config/file_linux.go (hunk 28 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: I ll add it

File: pkg/kubelet/config/file_linux.go (hunk 26 above)
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: Yeah, I just meant it could be a tight loop, although if it was a non-retryable error that would be a problem. Is there a similar utility method that does an exponential backoff?

File: pkg/kubelet/config/file_linux.go (hunk 29 above)
Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: I did some fixes:
* add IN_ATTRIB for watching symlink
* introduce backoff for watching retry loop
* merge list & watch into one goroutine to get rid of lock

Comment (wu8685) [inline pkg/kubelet/config/file_linux.go]: @tallclair ptal

**Comment by wu8685** [comment]
seems there are some problem to trigger tests

**Comment by yujuhong** [comment]
/retest

Ping @tallclair to review the new changes.

**Comment by wu8685** [comment]
@tallclair @yujuhong 
please give some help to trigger tests and review my code

**Comment by yujuhong** [comment]
/retest

@tallclair is out. Ping @mtaufen for another round of review

**Comment by wu8685** [comment]
fixed the bazel issue

**Comment by wu8685** [comment]
hi @mtaufen
Could you continue this review?
There may be some problem with the auto builds that I'm not allow to trigger the tests. I'm afraid that you have to comment `/retest` for me.
Thanks.

**Comment by mtaufen** [comment]
Sorry I didn't get back to this sooner. Not sure what's up with the tests, I'll try again.
/retest

**Comment by wu8685** [comment]
thanks.
The tests seem ok now.

File: pkg/kubelet/config/file_linux.go [hunk 30]
```diff
@@ -108,22 +131,32 @@ func (s *sourceFile) processEvent(e *inotify.Event) error {
...
+	return nil
+}
+
+func (s *sourceFileListerWatcher) consumeWatchEvent(e *watchEvent) error {
+	switch e.eventType {
 	case podAdd, podModify:
-		if pod, err := s.extractFromFile(e.Name); err != nil {
-			glog.Errorf("Can't process manifest file %q: %v", e.Name, err)
+		if pod, err := s.extractFromFile(e.fileName); err != nil {
+			glog.Errorf("can't process config file %q: %v", e.fileName, err)
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: return this error, rather than logging it. I.e.
```
return fmt.Errorf("can't process config file %q: %v", e.fileName, err)
```

File: pkg/kubelet/config/file_linux.go [hunk 31]
```diff
@@ -108,22 +131,32 @@ func (s *sourceFile) processEvent(e *inotify.Event) error {
...
 		}
 	case podDelete:
-		if objKey, keyExist := s.fileKeyMapping[e.Name]; keyExist {
+		if objKey, keyExist := s.fileKeyMapping[e.fileName]; keyExist {
 			pod, podExist, err := s.store.GetByKey(objKey)
 			if err != nil {
 				return err
 			} else if !podExist {
-				return fmt.Errorf("the pod with key %s doesn't exist in cache", objKey)
+				glog.Errorf("the pod with key %s doesn't exist in cache", objKey)
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: ditto: return the error. It just gets logged at the caller.

File: pkg/kubelet/config/file_linux.go [hunk 32]
```diff
@@ -108,22 +131,32 @@ func (s *sourceFile) processEvent(e *inotify.Event) error {
...
+				return nil
 			} else {
-				return s.store.Delete(pod)
+				err = s.store.Delete(pod)
+				if err == nil {
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: nit: invert this logic (for idomatic go):
```go
if err := s.store.Delete(pod); err != nil {
  return fmt.Errorf("failed to remove deleted pod from cach: %v", err)
}
...
```

File: pkg/kubelet/config/file_linux_test.go [hunk 33]
```diff
@@ -75,7 +73,7 @@ func TestReadPodsFromFileExistAlready(t *testing.T) {
 
 	for _, testCase := range testCases {
 		func() {
-			dirName, err := utiltesting.MkTmpdir("file-test")
+			dirName, err := mkTempDir("file-test")
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux_test.go]: Why change this? The methods are basically identical.

File: pkg/kubelet/config/file_linux.go [hunk 34]
```diff
@@ -57,30 +83,25 @@ func (s *sourceFile) watch() error {
...
-	}
-
 	for {
 		select {
 		case event := <-w.Event:
-			err = s.processEvent(event)
+			err = s.produceWatchEvent(event)
 			if err != nil {
-				return fmt.Errorf("error while processing event (%+v): %v", event, err)
+				glog.Errorf("error while processing inotify event (%+v): %v", event, err)
```
Comment (tallclair) [inline pkg/kubelet/config/file_linux.go]: It looks like the only type of error that can occur here is a delete self. In that case, don't you want to break out of this loop and try to recreate the watcher?

File: pkg/kubelet/config/file.go [hunk 35]
```diff
@@ -30,30 +30,46 @@ import (
 
 	"k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/types"
-	"k8s.io/apimachinery/pkg/util/wait"
 	"k8s.io/client-go/tools/cache"
 	"k8s.io/kubernetes/pkg/api"
 	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
 )
 
-type sourceFile struct {
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: This PR has a lot going on, and it's tough to follow all the changes. Can you please try to minimize unnecessary changes like renaming the type? If you'd like, you can follow up with a refactor to cleanup things like this.

**Review by tallclair — CHANGES_REQUESTED** [review]

File: pkg/kubelet/config/file_linux_test.go (hunk 33 above)
Comment (wu8685) [reply pkg/kubelet/config/file_linux_test.go]: It is changed according to previous review. I don't have preference.

**Comment by wu8685** [comment]
@tallclair I have reversed the name changed.
ptal

File: pkg/kubelet/config/file.go [hunk 36]
```diff
@@ -30,18 +30,34 @@ import (
...
 )
 
+type podEventType int
+
+const (
+	podAdd podEventType = iota
+	podModify
+	podDelete
+
+	eventBuffer = 10
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: nit: `eventBufferLen`

File: pkg/kubelet/config/file.go [hunk 37]
```diff
@@ -65,23 +81,40 @@ func new(path string, nodeName types.NodeName, period time.Duration, updates cha
...
-		glog.Errorf("Unable to read manifest path %q: %v", s.path, err)
-	}
+	listTicker := time.NewTicker(s.period)
+
+	go func() {
+		for {
+			select {
+			case <-listTicker.C:
+				if err := s.listConfig(); err != nil {
+					glog.Errorf("unable to read config path %q: %v", s.path, err)
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: nit: Log messages start with a capital letter

File: pkg/kubelet/config/file.go [hunk 38]
```diff
@@ -193,7 +226,7 @@ func (s *sourceFile) extractFromFile(filename string) (pod *v1.Pod, err error) {
 		return pod, nil
 	}
 
-	return pod, fmt.Errorf("%v: couldn't parse as pod(%v), please check manifest file.\n", filename, podErr)
+	return pod, &parseError{fmt.Sprintf("%v: couldn't parse as pod(%v), please check config file.\n", filename, podErr)}
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: Just use `fmt.Errorf` here, I don't think there's any need for the custom type.

**Review by tallclair — COMMENTED** [review]
Just a couple nits.

**Comment by wu8685** [comment]
@tallclair 
I updated. Please take a look.

File: pkg/kubelet/config/file.go [hunk 39]
```diff
@@ -90,7 +123,7 @@ func (s *sourceFile) resetStoreFromPath() error {
 		}
 		// Emit an update with an empty PodList to allow FileSource to be marked as seen
 		s.updates <- kubetypes.PodUpdate{Pods: []*v1.Pod{}, Op: kubetypes.SET, Source: kubetypes.FileSource}
-		return fmt.Errorf("path does not exist, ignoring")
+		return fmt.Errorf("Path does not exist, ignoring")
```
Comment (tallclair) [inline pkg/kubelet/config/file.go]: Sorry for the confusion - error messages (i.e. `fmt.Errorf(...)`) should start with a lowercase letter (revert this), but log messages (i.e. `glog.Errorf(...)`) should start with a capital.

**Comment by wu8685** [comment]
I fixed, ptal

**Comment by wu8685** [comment]
It is strange that the auto test doesn't work. Should I open a new PR?

**Comment by wu8685** [comment]
@yujuhong thx. 
But it seems doesn't work. 
Could you please `/retest`

**Comment by yujuhong** [comment]
/retest

Not sure what the tests are stuck. /cc @kubernetes/sig-testing-bugs

**Comment by BenTheElder** [comment]
I think the CLAbot was stuck, though I can't verify this because we don't have any real contact with that bot. The tests are running now :confused:

**Comment by wu8685** [comment]
I fixed the ut.
please retest.
thanks:)

**Comment by BenTheElder** [comment]
pull-kubernetes-bazel is a stale entry, the other two are likely flakes|
/test pull-kubernetes-unit
/test pull-kubernetes-e2e-gce

**Comment by wu8685** [comment]
I can't reproduce the failed `pull-kubernetes-unit` case locally by 
> go test -v k8s.io/kubernetes/test/integration/garbagecollector -run TestCascadingDeletion$

On my branch, the case passed. Will the `pull-kubernetes-unit` block the PR?

By the way, on master branch, it failed:
```
=== RUN   TestCascadingDeletion
[restful] 2017/12/16 08:12:53 log.go:33: [restful/swagger] listing is available at https://10.1.10.82:46849/swaggerapi
[restful] 2017/12/16 08:12:53 log.go:33: [restful/swagger] https://10.1.10.82:46849/swaggerui/ is mapped to folder /swagger-ui/
F1216 08:12:53.396894   27879 openapi.go:37] Failed to register open api spec for root: cannot find model definition for k8s.io/api/admissionregistration/v1beta1.ValidatingWebhookConfigurationList. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again
goroutine 114 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc420dd8f00, 0xc425448380, 0x137, 0x31b)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x98bebe0, 0xc400000003, 0xc420863ad0, 0x93d56ae, 0xa, 0x25, 0x0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x322
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x98bebe0, 0x3, 0x402b1f9, 0x2d, 0xc4253b9808, 0x1, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x402b1f9, 0x2d, 0xc4253b9808, 0x1, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc4208558c0, 0xc42032a630, 0xc4202ae9a0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:37 +0xf2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc4202c8500, 0x11)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:257 +0x7a
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc42064d200, 0xc420464a20, 0x25, 0xc420a77bd0, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:173 +0x387
k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServer(0xc4204105a0, 0x0, 0x0, 0x0, 0xc42088f720, 0xc420049cc0, 0x315bb7a, 0x357ffa0, 0xc420a55ee0, 0x2, ...)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:101 +0x6ac
k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServerOrDie(0xc4204105a0, 0x0, 0x0, 0x0, 0xc42088f720, 0xe2)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:142 +0xca
k8s.io/kubernetes/test/integration/garbagecollector.setup(0xc4204105a0, 0x5, 0x502e1d)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go:203 +0x54
k8s.io/kubernetes/test/integration/garbagecollector.TestCascadingDeletion(0xc4204105a0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go:298 +0x4c
testing.tRunner(0xc4204105a0, 0x40dd6f8)
	/home/aiplatform-adm/kewu/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/aiplatform-adm/kewu/go/src/testing/testing.go:789 +0x2de
exit status 255
FAIL	k8s.io/kubernetes/test/integration/garbagecollector	1.339s
```

**Comment by BenTheElder** [comment]
This could mean the test only sometimes fails or that it is broken on
master. Your PR will be merged into master in CI before testing since we're
verifying that merging it is safe.

pull-kubernetes-unit is required and will block the PR


On Dec 16, 2017 11:23, "Kan Wu" <notifications@github.com> wrote:

I can't reproduce the failed pull-kubernetes-unit case locally by

go test -v k8s.io/kubernetes/test/integration/garbagecollector -run
TestCascadingDeletion$

On my branch, the case passed. Will the pull-kubernetes-unit block the PR?

By the way, on master branch, it failed:

=== RUN   TestCascadingDeletion
[restful] 2017/12/16 08:12:53 log.go:33: [restful/swagger] listing is
available at https://10.1.10.82:46849/swaggerapi
[restful] 2017/12/16 08:12:53 log.go:33: [restful/swagger]
https://10.1.10.82:46849/swaggerui/ is mapped to folder /swagger-ui/
F1216 08:12:53.396894   27879 openapi.go:37] Failed to register open
api spec for root: cannot find model definition for
k8s.io/api/admissionregistration/v1beta1.ValidatingWebhookConfigurationList.
If you added a new type, you may need to add +k8s:openapi-gen=true to
the package or type and run code-gen again
goroutine 114 [running]:k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0xc420dd8f00,
0xc425448380, 0x137, 0x31b)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766
+0xcfk8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x98bebe0,
0xc400000003, 0xc420863ad0, 0x93d56ae, 0xa, 0x25, 0x0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717
+0x322k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x98bebe0,
0x3, 0x402b1f9, 0x2d, 0xc4253b9808, 0x1, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655
+0x14ck8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x402b1f9,
0x2d, 0xc4253b9808, 0x1, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145
+0x67k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc4208558c0,
0xc42032a630, 0xc4202ae9a0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:37
+0xf2k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc4202c8500,
0x11)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:257
+0x7ak8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc42064d200,
0xc420464a20, 0x25, 0xc420a77bd0, 0x1)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:173
+0x387k8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServer(0xc4204105a0,
0x0, 0x0, 0x0, 0xc42088f720, 0xc420049cc0, 0x315bb7a, 0x357ffa0,
0xc420a55ee0, 0x2, ...)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:101
+0x6ack8s.io/kubernetes/cmd/kube-apiserver/app/testing.StartTestServerOrDie(0xc4204105a0,
0x0, 0x0, 0x0, 0xc42088f720, 0xe2)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing/testserver.go:142
+0xcak8s.io/kubernetes/test/integration/garbagecollector.setup(0xc4204105a0,
0x5, 0x502e1d)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go:203
+0x54k8s.io/kubernetes/test/integration/garbagecollector.TestCascadingDeletion(0xc4204105a0)
	/home/aiplatform-adm/go/src/k8s.io/kubernetes/test/integration/garbagecollector/garbage_collector_test.go:298
+0x4c
testing.tRunner(0xc4204105a0, 0x40dd6f8)
	/home/aiplatform-adm/kewu/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/home/aiplatform-adm/kewu/go/src/testing/testing.go:789 +0x2de
exit status 255
FAIL	k8s.io/kubernetes/test/integration/garbagecollector	1.339s

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/44495#issuecomment-352193423>,
or mute the thread

**Comment by wu8685** [comment]
Yes, it is required. But it look like flakes. Does this mean that i have to go on to fix pull-kubernetes-unit before the PR can be merged?
If true, pls comment a /retest to trigger the test. Thanks.

**Comment by BenTheElder** [comment]
/retest
Unfortunately it does need to pass.

**Comment by wu8685** [comment]
It seems ok now.
Considering the problem of auto test, could you pls merge it ASAP, before needing to rebase again?
Thanks :smile:

**Comment by wu8685** [comment]
Rebased.
Pls help to type `/retest` to trigger the CI.

**Comment by wu8685** [comment]
Pls help to type `/retest` to trigger the test.
Thanks.

**Comment by BenTheElder** [comment]
> Pls help to type /retest to trigger the test.Thanks.

We have a robot account that will do this automatically once the PR is LGTM.

**Comment by wu8685** [comment]
@mtaufen @tallclair
Pls continue to review this PR
Thanks.

**Comment by wu8685** [comment]
rebased
please help to type `/retest`, thx.

**Comment by wu8685** [comment]
Are there some members still working on this PR?

File: pkg/kubelet/config/file_linux_test.go (hunk 33 above)
Comment (tallclair) [reply pkg/kubelet/config/file_linux_test.go]: It's fine to depend on client-go/util/testing from here. But I won't block the review on this.

**Review by tallclair — APPROVED** [review]
/lgtm
