### PR TITLE
Check opts of cloud config file

### LINKED ISSUE #48347: The cloud-config-file is hard to use
User can not specify --cloud-config for cloudprovider correctly and failed to create/use cloud resource,  it is necessary to add document into kubernetes.github.io and add code to check file before init cloudprovider, 	instead of returning error when create/use cloud resource.

Common Problems：

nginx-service-lb2   10.254.167.38    <pending>          8000:32175/TCP   3m
-bash-4.3# kubectl describe service nginx-service-lb2
Name:			nginx-service-lb2
Namespace:		default
Labels:			<none>
Annotations:		<none>
Selector:		name=nginx
Type:			LoadBalancer
IP:			10.254.167.38
Port:			<unset>	8000/TCP
NodePort:		<unset>	32175/TCP
Endpoints:		<none>
Session Affinity:	None
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason				Message
  ---------	--------	-----	----			-------------	--------	------				-------
  3m		51s		6	service-controller			Normal		CreatingLoadBalancer		Creating load balancer
  3m		48s		6	service-controller			Warning		CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service default/nginx-service-lb2: Error creating LB pool healthmonitor: Missing input for argument [Delay]

### PR DESCRIPTION
**Pull request by FengyunPan**
Fix #48347
Check opts when register OpenStack CloudProvider rather than
returning error when use opts to create/use cloud resource.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
/test pull-kubernetes-e2e-gce-etcd3
ping @anguslees    PTAL
ping @NickrenREN   PTAL

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 1]
```diff
@@ -216,6 +221,40 @@ func readInstanceID() (string, error) {
...
+	lbOpts := openstackOpts.lbOpts
+
+	// subnet-id is required
+	if len(lbOpts.SubnetId) == 0 {
+		return ErrNoSubnetId
+	}
+
+	// if need to create health monitor for Neutron LB,
+	// monitor-delay, monitor-timeout and monitor-max-retries should be set.
+	emptyDuration := new(MyDuration)
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack.go]: No need to create a reference to a `MyDuration` only to deref it again later.  Just do: `emptyDuration := MyDuration{}` here and remove the asterisks below.

File: pkg/cloudprovider/providers/openstack/openstack_test.go [hunk 2]
```diff
@@ -144,6 +144,98 @@ func TestToAuthOptions(t *testing.T) {
 	}
 }
 
+func TestCheckOpenStackOpts(t *testing.T) {
+	delay := new(MyDuration)
+	delay.Duration = 60 * time.Second
+	timeout := new(MyDuration)
+	timeout.Duration = 30 * time.Second
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack_test.go]: Similar to earlier comment - these MyDuration objects should just be regular objects, not references.
```go
delay := MyDuration{60 * time.Second}
timeout := MyDuration{30 * time.Second}
```

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 3]
```diff
@@ -53,6 +53,11 @@ const ProviderName = "openstack"
 var ErrNotFound = errors.New("Failed to find object")
 var ErrMultipleResults = errors.New("Multiple results where only one expected")
 var ErrNoAddressFound = errors.New("No address found for host")
+var ErrNoSubnetId = errors.New("subnet-id not set in cloud provider config")
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack.go]: It's highly unlikely any caller is going to want to match against one of these different errors explicitly.
So instead of growing a huge list of pre-built errors here, delete these and just use in-line error strings in the function below:

```go
if len(lbOpts.SubnetId) == 0 {
      return fmt.Errorf("subnet-id not set in cloud provider config")
}
// etc
```

**Review by anguslees — CHANGES_REQUESTED** [review]
some minor style comments

File: pkg/cloudprovider/providers/openstack/openstack.go (hunk 3 above)
Comment (FengyunPan) [inline pkg/cloudprovider/providers/openstack/openstack.go]: Done. Thank you very much.

File: pkg/cloudprovider/providers/openstack/openstack.go (hunk 1 above)
Comment (FengyunPan) [inline pkg/cloudprovider/providers/openstack/openstack.go]: Done.

File: pkg/cloudprovider/providers/openstack/openstack_test.go (hunk 2 above)
Comment (FengyunPan) [inline pkg/cloudprovider/providers/openstack/openstack_test.go]: Done.

**Comment by FengyunPan** [comment]
／retest
