### PR TITLE
fix: validate apiserver endpoints in master lease reconciler

### LINKED ISSUE #121942: Kubernetes endpoint validation
### What happened?

Scenario:

In a setup of multiple kube-apiserver, one of the apiserver's advertise address is configured to `127.0.0.1`. When the apiserver starts up, it saves the ip into etcd registry directly without validation, followed by endpoint object update. However, the endpoint object update fails due to the validation [here](https://github.com/kubernetes/kubernetes/blob/v1.25.15/pkg/apis/core/validation/validation.go#L6176). The validation rejects the update when endpoint is localhost or link local address. 

Since the IP is already persisted into etcd registry, other apiservers cannot update the endpoint object anymore. This results in one apiserver mis/configuration to block all endpoint updates until the apiserver is taken out of service. If the other healthy apiservers restart or change IP, the kubernetes endpoint object IPs become stale.

### What did you expect to happen?

A misconfigured apiserver advertise address should not block all apiservers from updating their IP.

### How can we reproduce it (as minimally and precisely as possible)?

Sample response object from audit log
```
  "responseObject": {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Endpoints \"kubernetes\" is invalid: subsets[0].addresses[0].ip: Invalid value: \"127.0.0.1\": may not be in the loopback range (127.0.0.0/8, ::1/128)",
    "reason": "Invalid",
    "details": {
      "name": "kubernetes",
      "kind": "Endpoints",
      "causes": [
        {
          "reason": "FieldValueInvalid",
          "message": "Invalid value: \"127.0.0.1\": may not be in the loopback range (127.0.0.0/8, ::1/128)",
          "field": "subsets[0].addresses[0].ip"
        }
      ]
    },
    "code": 422
  },
```

### Anything else we need to know?

_No response_

### Kubernetes version

Any version
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kairosci**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR adds robust IP validation to the master lease reconciler. 
A misconfigured apiserver (e.g., using --advertise-address=127.0.0.1) could previously poison the master lease pool in etcd. This caused the kubernetes Service endpoint reconciliation to fail for all apiservers because the invalid address was rejected during the final Endpoints object validation.

The fix validates the local IP on startup when using the master-count or lease endpoint reconciler, to prevent invalid addresses (loopback, link-local, unspecified) from being persisted.

#### Which issue(s) this PR is related to:
Fixes #121942

#### Special notes for your reviewer:
The validation logic in pkg/controlplane/reconcilers intentionally mimics pkg/apis/core/validation.ValidateEndpointIP to avoid circular dependencies while maintaining consistent behavior for the kubernetes Service.

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver now validates the `--advertise-address` IP when using `--endpoint-reconciler-type` `master-count` or `lease` to ensure the specified IP address can be persisted to an `Endpoints` API object successfully.
```

### CODE REVIEW

File: pkg/controlplane/reconcilers/lease.go [hunk 1]
```diff
@@ -162,6 +192,10 @@ func NewLeaseEndpointReconciler(epAdapter EndpointsAdapter, masterLeases Leases)
 	}
 }
 
+func (r *leaseEndpointReconciler) ValidateIP(ip net.IP) error {
```
Comment (liggitt) [inline pkg/controlplane/reconcilers/lease.go:166]: this bit looks good, revert all the other changes in this file

Comment (kairosci) [reply pkg/controlplane/reconcilers/lease.go:166]: I believe I done

File: pkg/controlplane/reconcilers/lease_test.go
Comment (liggitt) [inline pkg/controlplane/reconcilers/lease_test.go:1]: I think this file can be reverted as well, since we're only adding validation at startup and not changing any other behavior

(go ahead and squash to a single commit once completed)

Comment (kairosci) [reply pkg/controlplane/reconcilers/lease_test.go:1]: I believe I done

**Comment by liggitt** [comment]
you'll likely need to do something like this to make the kube-apiserver integration test startup properly:
```diff
diff --git a/cmd/kube-apiserver/app/testing/testserver.go b/cmd/kube-apiserver/app/testing/testserver.go
index 221afcd4221..130dbc6cb73 100644
--- a/cmd/kube-apiserver/app/testing/testserver.go
+++ b/cmd/kube-apiserver/app/testing/testserver.go
@@ -331,6 +331,8 @@ func StartTestServer(t ktesting.TB, instanceOptions *TestServerInstanceOptions,
 
 	s.SecureServing.ExternalAddress = s.SecureServing.Listener.Addr().(*net.TCPAddr).IP // use listener addr although it is a loopback device
 
+	s.EndpointReconcilerType = "none" // disable endpoint reconciliation when using a loopback "external" address
+
 	pkgPath, err := pkgPath(t)
 	if err != nil {
 		return result, err
```
