### PR TITLE
[Bug] Handle container restarts and avoid using runtime pod cache while allocating GPUs

### LINKED ISSUE #42412: GPU allocation failed after container in Pod restart
We found a bug about GPU allocation failed with upstream code. 
If the container with GPU in a `Pod` dead and restart, the GPU is still occupied by the old container so that the new container can not get GPU anymore. You can replay the bug by the script below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gpu
  labels:
    name: gpu
spec:
  containers:
  - name: gpu
    image: nvidia/cuda:jian
    command: ["/bin/sh", "-c"]
    args: ["sleep 10"]
    resources:
      limits:
        cpu: 0.5
        memory: 128Mi
        alpha.kubernetes.io/nvidia-gpu: 4
    ports:
    - containerPort: 6379 
```
After we created the pod, we can see the output as below:
```
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
gpu       1/1       Running   0          7s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS      RESTARTS   AGE
gpu       0/1       Completed   0          20s
root@slave2:/home/zhangjian/testK8s# kubectl get pods
NAME      READY     STATUS                                                             RESTARTS   AGE
gpu       0/1       requested number of GPUs unavailable. Requested: 4, Available: 0   0          36s
```
After container completed, `Pod` try to restart a new container. But the new container can not get GPU because GPU is still unreleased by the fisrt container. Depolyment and RC controller have the same problem.

### PR DESCRIPTION
**Pull request by vishh**
Fixes #42412

**Background**
Support for multiple GPUs is an experimental feature in v1.6. 
Container restarts were handled incorrectly which resulted in stranding of GPUs
Kubelet is incorrectly using runtime cache to track running pods which can result in race conditions (as it did in other parts of kubelet). This can result in same GPU being assigned to multiple pods.

**What does this PR do**
This PR tracks assignment of GPUs to containers and returns pre-allocated GPUs instead of (incorrectly) allocating new GPUs.
GPU manager is updated to consume a list of active pods derived from apiserver cache instead of runtime cache.
Node e2e has been extended to validate this failure scenario.

**Risk**
Minimal/None since support for GPUs is an experimental feature that is turned off by default. The code is also isolated to GPU manager in kubelet.

**Workarounds**
In the absence of this PR, users can mitigate the original issue by setting `RestartPolicyNever`  in their pods.
There is no workaround for the race condition caused by using the runtime cache though.
Hence it is worth including this fix in v1.6.0.

cc @jianzhangbjz @seelam @kubernetes/sig-node-pr-reviews 

Replaces #42560

### CODE REVIEW

**Comment by dashpole** [comment]
Unrelated to the changes here, but the GPU manager likely has the same problem that #42585 had, since this also uses "runningPods".

File: pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go [hunk 1]
```diff
@@ -152,6 +152,12 @@ func (ngm *nvidiaGPUManager) AllocateGPU(pod *v1.Pod, container *v1.Container) (
 			return nil, fmt.Errorf("Failed to allocate GPUs because of issues with updating GPUs in use: %v", err)
 		}
 	}
+	// Check if GPUs have already been allocated. If so return them right away.
+	// This can happen if a container restarts for example.
+	if devices := ngm.allocated.getGPUs(string(pod.UID), container.Name); devices != nil {
+		glog.V(2).Infof("Found pre-allocated GPUs for container %q in Pod %q: %v", container.Name, pod.UID, devices.List())
+		return devices.List(), nil
```
Comment (dashpole) [inline pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go]: Just to make sure I understand this: AllocateGPU is only called when either none of the GPUs for a container have been allocated, or all of the GPUs for a container have been allocated.  There would never arise a situation where we find 3 GPUs already allocated, but require 4, right?

**Comment by dashpole** [comment]
Ill finish my review of the tests later, but the changes to the GPU manger look good.

File: pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go (hunk 1 above)
Comment (vishh) [inline pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go]: Yes. Its all or nothing

**Comment by vishh** [comment]
@dashpole Running pods vs active pods is a good catch. I incorrectly assumed that gpu manager was using active pods. Fixed it now.

File: pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go [hunk 2]
```diff
@@ -218,13 +218,14 @@ func (ngm *nvidiaGPUManager) discoverGPUs() error {
 
 // gpusInUse returns a list of GPUs in use along with the respective pods that are using it.
 func (ngm *nvidiaGPUManager) gpusInUse() (*podGPUs, error) {
```
Comment (dashpole) [inline pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go]: no longer can return an error

**Comment by dashpole** [comment]
lgtm after nit.  The unit test looks like a flake.

**Comment by vishh** [comment]
@dashpole fixed the nit

File: pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go (hunk 1 above)
Comment (jianzhangbjz) [inline pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go]: @vishh There should be return `append(devices.List(), ngm.defaultDevices...)` instead, right?

**Review by jianzhangbjz — CHANGES_REQUESTED** [review]

**Comment by dchen1107** [comment]
@vishh one you addressed @jianzhangbjz's comment, I will apply approval to the pr.

**Comment by vishh** [comment]
Good catch @JiangtianLi. @dchen1107 fixed the bug and added unit tests.

**Comment by dashpole** [comment]
took another quick look
/lgtm

**Comment by vishh** [comment]
@k8s-bot gci gce e2e test this

**Comment by jianzhangbjz** [comment]
@vishh I think you misspelled my name on the above.  \*(^_^)\*

**Comment by vishh** [comment]
@k8s-bot unit test this

**Comment by vishh** [comment]
@k8s-bot kops aws e2e test this

**Comment by vishh** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by vishh** [comment]
@jianzhangbjz Ah sorry about that.

**Comment by vishh** [comment]
@k8s-bot kops aws e2e test this

**Comment by vishh** [comment]
@justinsb kops e2e has been failing consistently. Is this a known issue? 

@k8s-bot kops aws e2e test this

**Comment by dashpole** [comment]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/
looks like it was failing, but is fixed now.
@k8s-bot kops aws e2e test this

**Comment by cmluciano** [comment]
@vishh I think it should be fixed with this change https://github.com/kubernetes/kops/commit/2a44aa0c05ccfa0beb6d96ee21a7883947664f76. It seems that a rate-limit was hit and caused a ton of builds to fail.

File: pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go [hunk 3]
```diff
@@ -141,16 +138,16 @@ func (ngm *nvidiaGPUManager) AllocateGPU(pod *v1.Pod, container *v1.Container) (
...
 	} else {
 		// update internal list of GPUs in use prior to allocating new GPUs.
-		if err := ngm.updateAllocatedGPUs(); err != nil {
-			return nil, fmt.Errorf("Failed to allocate GPUs because of issues with updating GPUs in use: %v", err)
-		}
+		ngm.updateAllocatedGPUs()
+	}
+	// Check if GPUs have already been allocated. If so return them right away.
+	// This can happen if a container restarts for example.
+	if devices := ngm.allocated.getGPUs(string(pod.UID), container.Name); devices != nil {
```
Comment (tedyu) [inline pkg/kubelet/gpu/nvidia/nvidia_gpu_manager.go]: Is it possible that devices is empty ?
