### PR TITLE
Fix #11543 - use DescribeInstances API to retrieve the correct private DNS name

### LINKED ISSUE #11543: Can't get --cloud-provider=aws to work (instance not found)
I'm trying to set up AWS ELB attach volume access and keep getting an error on the kubelet. I have some bad feeling it might be related to #9801 as these nodes are CoreOS that were brought up by Terraform with custom service files but everything else is working fine (we're running cluster monitoring, dns, and a number of our own pods without issues). I've run awscli on that instance and the privileges definitely work. What am I doing wrong?

logs from kubelet service

```
I0719 02:22:59.549444    9662 factory.go:234] Registering Docker factory
I0719 02:22:59.549826    9662 factory.go:89] Registering Raw factory
I0719 02:22:59.638468    9662 manager.go:946] Started watching for new ooms in manager
I0719 02:22:59.639054    9662 oomparser.go:183] oomparser using systemd
I0719 02:22:59.640589    9662 manager.go:243] Starting recovery of all containers
E0719 02:22:59.679107    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
I0719 02:22:59.753816    9662 manager.go:248] Recovery completed
I0719 02:22:59.816369    9662 status_manager.go:76] Starting to sync pod status with apiserver
I0719 02:22:59.816426    9662 kubelet.go:1725] Starting kubelet main sync loop.
E0719 02:22:59.953337    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:01.047929    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:01.975409    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:03.645707    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
E0719 02:23:06.917503    9662 kubelet.go:787] Unable to construct api.Node object for kubelet: failed to get external ID from cloud provider: instance not found
I0719 02:23:07.790941    9662 server.go:635] POST /stats/container/: (46.254087ms) 0 [[Go 1.1 package http] 10.0.39.222:45497]
```

kube-kubelet.service

```
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
Environment="KUBERNETES_BINARY_VERSION=1.0.0"
EnvironmentFile=/etc/environment
ExecStartPre=/usr/bin/curl -L -o /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_BINARY_VERSION}/bin/linux/amd64
ExecStartPre=/usr/bin/chmod +x /opt/bin/kubelet
ExecStart=/opt/bin/kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --cloud-provider=aws \
  --hostname-override=${COREOS_PRIVATE_IPV4} \
  --api-servers=${KUBE_MASTER_IP}:8080 \
  --allow-privileged=false \
  --cluster_dns=10.2.0.2 \
  --cluster_domain=cluster.local \
  --cadvisor_port=4194 \
  --healthz_bind_address=0.0.0.0 \
  --healthz_port=10248 \
  --v=2 \
  --logtostderr=true
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

iam policy

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "ec2:Describe*"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2:AttachVolume",
        "ec2:DetachVolume"
      ],
      "Resource": [
        "arn:aws:ec2:*:*:instance/*"
      ]
    },
  ]
}
```

### PR DESCRIPTION
**Pull request by jtblin**
Following discussion on #17643, now retrieving the private DNS name via the `DescribeInstances` API as the one retrieved from the ec2 metadata can be incorrect in the case of private zones.

cc @justinsb

### CODE REVIEW

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -654,6 +654,7 @@ func (aws *AWSCloud) NodeAddresses(name string) ([]api.NodeAddress, error) {
 		}
 		return []api.NodeAddress{
 			{Type: api.NodeInternalIP, Address: internalIP},
+			{Type: api.NodeLegacyHostIP, Address: internalIP},
```
Comment (jtblin) [inline pkg/cloudprovider/providers/aws/aws.go]: Only had to add this because of the tests.

File: pkg/cloudprovider/providers/aws/aws_test.go [hunk 2]
```diff
@@ -587,9 +589,10 @@ func TestNodeAddresses(t *testing.T) {
 	// (we test that this produces an error)
 	var instance0 ec2.Instance
 	var instance1 ec2.Instance
+	var instance2 ec2.Instance
 
 	//0
-	instance0.InstanceId = aws.String("instance-same")
+	instance0.InstanceId = aws.String("i-self")
```
Comment (jtblin) [inline pkg/cloudprovider/providers/aws/aws_test.go]: Have to use this instance id so that it matches in the test fake DescribeInstances call and `getSelfAWSInstance` doesn't return an error.

File: pkg/cloudprovider/providers/aws/aws_test.go [hunk 3]
```diff
@@ -609,7 +612,18 @@ func TestNodeAddresses(t *testing.T) {
 	}
 	instance1.State = &state1
 
-	instances := []*ec2.Instance{&instance0, &instance1}
+	//2
+	instance2.InstanceId = aws.String("i-self")
```
Comment (jtblin) [inline pkg/cloudprovider/providers/aws/aws_test.go]: Had to add this new instance because of the way the tests are setup so that it reaches the code in `NodeAddresses` when the instance name that is searched is different from the current instance node name.

The `NodeAddresses` tries to do too much imho and has a lot of dead code which made updating the tests much more complicated than it should be. I'll open a different issue for that but I think we should refactor `NodeAddresses` on the model of the `gce` one. I didn't do the refactoring here because I didn't want to "muddy" the PR.

**Comment by bgrant0607** [comment]
@justinsb Could you please suggest a reviewer?

File: pkg/cloudprovider/providers/aws/aws.go [hunk 4]
```diff
@@ -2137,7 +2138,6 @@ func (s *AWSCloud) UpdateLoadBalancer(name, region string, hosts []string) error
 }
 
 // Returns the instance with the specified ID
-// This function is currently unused, but seems very likely to be needed again
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Well that's gratifying :-)

File: pkg/cloudprovider/providers/aws/aws.go [hunk 5]
```diff
@@ -1117,16 +1118,16 @@ func (s *AWSCloud) getSelfAWSInstance() (*awsInstance, error) {
 		if err != nil {
 			return nil, fmt.Errorf("error fetching instance-id from ec2 metadata service: %v", err)
 		}
-		privateDnsName, err := s.metadata.GetMetadata("local-hostname")
+		instance, err := s.getInstanceByID(instanceId)
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Maybe leave the above line (but commented out), and explain why we have to do this in a comment?

File: pkg/cloudprovider/providers/aws/aws.go [hunk 6]
```diff
@@ -1117,16 +1118,16 @@ func (s *AWSCloud) getSelfAWSInstance() (*awsInstance, error) {
...
-			return nil, fmt.Errorf("error fetching local-hostname from ec2 metadata service: %v", err)
+			return nil, fmt.Errorf("error finding instance %s: %v", instanceId, err)
 		}
 		availabilityZone, err := getAvailabilityZone(s.metadata)
 		if err != nil {
 			return nil, fmt.Errorf("error fetching availability zone from ec2 metadata service: %v", err)
 		}
 
-		i = newAWSInstance(s.ec2, instanceId, privateDnsName, availabilityZone)
+		i = newAWSInstance(s.ec2, instanceId, *instance.PrivateDnsName, availabilityZone)
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Use aws.StringValue, just in case this is nil

File: pkg/cloudprovider/providers/aws/aws.go (hunk 1 above)
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: I would rather not do this, because this then is returned to clients via the API, and we are trying to remove NodeLegacyHostIP.  How hard would it be to change the tests?

Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Actually, on second thoughts I think I am wrong here.  The special case here should match the normal case below, so your change is good.

File: pkg/cloudprovider/providers/aws/aws.go (hunk 4 above)
Comment (jtblin) [inline pkg/cloudprovider/providers/aws/aws.go]: Yep, that made my life very easy :+1:

**Comment by jtblin** [comment]
Made the requested changes and rebased.

**Comment by justinsb** [comment]
ok to test

**Comment by justinsb** [comment]
lgtm; thanks for the fixes

**Comment by justinsb** [comment]
@k8s-bot test this github flake #20547

**Comment by justinsb** [comment]
@k8s-bot unit test this github flake #19417
