### PR TITLE
Fix Data Race in nodeshutdown restart

### LINKED ISSUE #103251: Data Race in systemDBus Unit test
### Failure cluster [78118168f2359d9363b3](https://go.k8s.io/triage#78118168f2359d9363b3)

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L121-L131

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L334-L342

##### Error text:
```
=== RUN   TestRestart
==================
WARNING: DATA RACE
Read at 0x00000427c328 by goroutine 90:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).start()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:130 +0x54
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).Start.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:120 +0xfa

Previous write at 0x00000427c328 by goroutine 65:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:334 +0x1fb
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 90 (running) created at:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*Manager).Start()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:112 +0x1f3
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:345 +0x3b9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 65 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238
```
#### Recent failures:
[2021/6/28 上午7:00:10 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1409285092316024832)
[2021/6/28 上午1:00:08 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1409194494212968448)
[2021/6/27 下午7:00:10 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1409103896361570304)
[2021/6/27 下午1:00:39 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1409013298363371520)
[2021/6/27 上午7:00:14 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1408922700419698688)

/kind failing-test

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind flake
/sig node

#### Which issue(s) this PR fixes:

Fixes #103251

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by matthyx** [comment]
@wzshiming could you just explain what's the purpose of the mutex you're adding?

**Comment by wzshiming** [comment]
> @wzshiming could you just explain what's the purpose of the mutex you're adding?

Avoid flake #103251

**Comment by matthyx** [comment]
> > @wzshiming could you just explain what's the purpose of the mutex you're adding?
> 
> Avoid flake #103251

Thanks, this I had understood :-D
More specifically why do we need to protect the assignment of the `shutdownChan`?
What's happening in the test and how the mutex helps?
(it's just to help reviewers and approvers understand your fix, remember we're not inside your head)

**Comment by wzshiming** [comment]
This is to test the shutdown management, whether it can work normally after dbus restarts,

In the shutdown management, dbus tries to reconnect after disconnection, the shutdownChan be reset a new channel. In the below loop, the shutdownChan will be closed to simulate dbus disconnection.

It is the concurrency of the two that caused the data race.

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go [hunk 1]
```diff
@@ -354,7 +358,9 @@ func TestRestart(t *testing.T) {
 		case <-connChan:
 		}
 
-		time.Sleep(time.Second)
+		time.Sleep(dbusReconnectPeriod)
```
Comment (bobbypage) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:361]: what is the this sleep required for? If I understand correctly this unit test will take at least 5 seconds, since we iterate over the loop 5 times and sleep for second each time. For unit tests, it's desirable to keep them as fast as possible and avoid sleeps if possible.

Is this sleep needed / any way we can get rid of it?

Comment (wzshiming) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go]: Updated, I reduced the number of tests and sleep time, and compared the code coverage before and after the modification is the same.

Comment (bobbypage) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go]: Nice, thanks!
