### PR TITLE
Use the last kubelet pid in the pidof command

### LINKED ISSUE #122270: [Flaking Test] [sig-node] Mount propagation should propagate mounts within defined scopes
### Failure cluster [9f8a639f4713fff6316c](https://go.k8s.io/triage#9f8a639f4713fff6316c)
https://storage.googleapis.com/k8s-triage/index.html?test=%20Mount%20propagation%20should%20propagate%20mounts%20within%20defined%20scopes

##### Error text:
```
Dec 11 21:23:08.765: INFO: ExecWithOptions: execute(POST https://[::1]:35327/api/v1/namespaces/mount-propagation-6212/pods/hostexec-kind-worker-dbbg9/exec?command=nsenter&command=--mount%3D%2Frootfs%2Fproc%2F1%2Fns%2Fmnt&command=--&command=sh&command=-c&command=pidof+kubelet&container=agnhost-container&container=agnhost-container&stderr=true&stdout=true)
Dec 11 21:23:09.156: INFO: exec kind-worker: command:   pidof kubelet
Dec 11 21:23:09.156: INFO: exec kind-worker: stdout:    ""
Dec 11 21:23:09.156: INFO: exec kind-worker: stderr:    ""
Dec 11 21:23:09.156: INFO: exec kind-worker: exit code: 0
Dec 11 21:23:09.156: INFO: Unexpected error: Checking kubelet pid: 
    <exec.CodeExitError>: 
    command terminated with exit code 1
    {
        Err: <*errors.errorString | 0xc005451e60>{
            s: "command terminated with exit code 1",
        },
        Code: 1,
    }
[FAILED] Checking kubelet pid: command terminated with exit code 1
In [It] at: test/e2e/node/mount_propagation.go:193 @ 12/11/23 21:23:09.157

```
#### Recent failures:
[2023/12/12 05:00:25 ci-kubernetes-kind-ipv6-e2e-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1734316526518931456)
[2023/12/11 22:49:08 ci-kubernetes-kind-e2e-parallel-1-29](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel-1-29/1734223160124903424)
[2023/11/29 04:10:14 ci-kubernetes-kind-e2e-parallel-1-28](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel-1-28/1729592970706948096)

/kind flake
/sig node

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #122270

#### Special notes for your reviewer:

We found that the last entry of the pidof command is the oldest process.

We decide that we can get that kubelet process for this test.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/node/mount_propagation.go [hunk 1]
```diff
@@ -191,9 +191,12 @@ var _ = SIGDescribe("Mount propagation", func() {
...
 		framework.ExpectNoError(err, "Checking kubelet pid")
-		kubeletPid = strings.TrimSuffix(kubeletPid, "\n")
-		gomega.Expect(strings.Count(kubeletPid, " ")).To(gomega.Equal(0), "kubelet should only have a single PID in the system (pidof returned %q)", kubeletPid)
-		enterKubeletMountNS := fmt.Sprintf("nsenter -t %s -m", kubeletPid)
+		// In rare cases in the CI, we are seeing two pids for kubelet.
+		// We did some investigating and the last entry of this list is the one that we want
+		// Higher pids are more likely to be created after the first one
+		kubeletPids := strings.Split(kubeletPid, " ")
+		enterKubeletMountNS := fmt.Sprintf("nsenter -t %s -m", kubeletPids[len(kubeletPids)-1])
+		ginkgo.By(enterKubeletMountNS)
```
Comment (haircommander) [inline test/e2e/node/mount_propagation.go:199]: currently this would just be the pid. Can you write what those numbers are?

Comment (haircommander) [reply test/e2e/node/mount_propagation.go:199]: also: we should write the whole output of the `kubeletPid`, not just the successful one (in case this hack breaks one day)

File: test/e2e/node/mount_propagation.go [hunk 2]
```diff
@@ -191,9 +191,13 @@ var _ = SIGDescribe("Mount propagation", func() {
...
-		kubeletPid = strings.TrimSuffix(kubeletPid, "\n")
-		gomega.Expect(strings.Count(kubeletPid, " ")).To(gomega.Equal(0), "kubelet should only have a single PID in the system (pidof returned %q)", kubeletPid)
-		enterKubeletMountNS := fmt.Sprintf("nsenter -t %s -m", kubeletPid)
+		ginkgo.By(fmt.Sprintf("pidof kubelet returns %s", kubeletPid))
+		// In rare cases in the CI, we are seeing two pids for kubelet.
+		// We did some investigating and the last entry of this list is the one that we want
+		// Higher pids are more likely to be created after the first one
+		kubeletPids := strings.Split(kubeletPid, " ")
+		enterKubeletMountNS := fmt.Sprintf("nsenter -t %s -m", kubeletPids[len(kubeletPids)-1])
+		ginkgo.By(enterKubeletMountNS)
```
Comment (SergeyKanzhelev) [inline test/e2e/node/mount_propagation.go:200]: I don't think it is the best use of a `ginkgo.By`. It is typically used to describe test steps. Perhaps `framework.Logf` can be used instead?

Comment (kannon92) [reply test/e2e/node/mount_propagation.go]: updated.

File: test/e2e/node/mount_propagation.go (hunk 1 above)
Comment (kannon92) [reply test/e2e/node/mount_propagation.go]: updated.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

Still curious why, but this should deal with the flake
