### PR TITLE
Fix volumes e2e test to check fsType

### LINKED ISSUE #70822: Volumes e2e test should check fsType
**What happened**:
Volumes test doesn't check fsType, as a result, e2e test which requires particular fsType could pass even when driver doesn't provide the right fsType 

**What you expected to happen**:
Volumes test should fail if driver doesn't provide the right fsType properly, and should pass it provides proper fsType.

**How to reproduce it (as minimally and precisely as possible)**:
Run ```[Testpattern: Dynamic PV (ext4)] volumes should be mountable``` tests with broken driver.

**Anything else we need to know?**:
/sig storage

Current ```gcePDCSIDriver.GetDynamicProvisionStorageClass``` in e2e test code is broken, so this also needs to be fixed.

**Environment**:
- Kubernetes version (use `kubectl version`):

/kind bug

### PR DESCRIPTION
**Pull request by mkimuram**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
Volumes test doesn't check fsType, as a result, e2e test which requires particular fsType could pass even when driver doesn't provide the right fsType. Also, current ```gcePDCSIDriver.GetDynamicProvisionStorageClass``` in e2e test code is broken, so this PR will also fix it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70822

**Special notes for your reviewer**:
/sig storage

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mkimuram** [comment]
@msau42 @davidz627 @pohly 

This PR will make fsType check as below:

```
STEP: Checking fsType is correct.
Nov  8 20:46:32.670: INFO: Running '/root/go/src/k8s.io/kubernetes/_output/bin/kubectl --server=https://localhost:6443/ --kubeconfig=/var/run/kubernetes/admin.
kubeconfig exec iscsi-client --namespace=e2e-tests-volumes-r8ljx -- grep  /opt/0 ext4 /proc/mounts'
Nov  8 20:46:33.002: INFO: stderr: ""
Nov  8 20:46:33.002: INFO: stdout: "/dev/sda /opt/0 ext4 rw,seclabel,relatime,block_validity,delalloc,barrier,user_xattr,acl 0 0\n"
```

I'm not sure csi gce actually works well, so I think that it would better to test ```[Testpattern: Dynamic PV (ext4)] volumes should be mountable``` with csi gce driver, before merging this PR.

File: test/e2e/common/volumes.go [hunk 1]
```diff
@@ -91,7 +91,7 @@ var _ = Describe("[sig-storage] GCP Volumes", func() {
 			}
 
 			// Must match content of test/images/volumes-tester/nfs/index.html
-			framework.TestVolumeClient(c, config, nil, tests)
```
Comment (davidz627) [inline test/e2e/common/volumes.go]: nit, add comment a la `framework.TestVolumeClient(c, config, nil, "" /* fsType */, tests)` for unnamed variables

File: test/e2e/storage/drivers/csi.go [hunk 2]
```diff
@@ -186,6 +186,9 @@ func (g *gcePDCSIDriver) GetDynamicProvisionStorageClass(fsType string) *storage
 	suffix := fmt.Sprintf("%s-sc", g.driverInfo.Name)
 
 	parameters := map[string]string{"type": "pd-standard"}
+	if fsType != "" {
+		parameters["fsType"] = fsType
```
Comment (davidz627) [inline test/e2e/storage/drivers/csi.go]: I don't think we specify fsType in the storage class for GCE PD, it's actually passed in on `NodeStageVolume` through the `VolumeCapability` field that comes from the `PVSource`.

File: test/e2e/common/volumes.go (hunk 1 above)
Comment (mkimuram) [reply test/e2e/common/volumes.go]: Thank you for your comment. I will fix all of them as suggested.

File: test/e2e/storage/drivers/csi.go (hunk 2 above)
Comment (mkimuram) [reply test/e2e/storage/drivers/csi.go]: IIUC, CSI provisioner will [add fsType to PVC]( https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L368) if fsType is set in StorageClass on provision. So, fsType should also be passed to PV, as a result, it will be passed as a ```VolumeCapability``` on ```NodeStageVolume``` when attach is requested.

Comment (davidz627) [reply test/e2e/storage/drivers/csi.go]: oh cool, I didn't know that, thanks for the explaination!

**Comment by davidz627** [comment]
@mkimuram I am testing this on the GCE PD CSI Driver now

**Comment by mkimuram** [comment]
@davidz627 

Update this PR with two commits:

1. Improve debug message to debug failure for aws with ext3
2. Skip XFS test for csi gce pd on COS

I will check 1 to see what is happening.
Meanwhile, I would like you to check if this PR works well for csi gce pd as well, for it is still tagged with ```[Serial]``` and is not tested in CI automatically triggered on every commit.

File: test/e2e/storage/drivers/csi.go [hunk 3]
```diff
@@ -348,6 +354,9 @@ func (g *gcePDExternalCSIDriver) GetDriverInfo() *DriverInfo {
 func (g *gcePDExternalCSIDriver) SkipUnsupportedTest(pattern testpatterns.TestPattern) {
 	framework.SkipUnlessProviderIs("gce", "gke")
 	framework.SkipIfMultizone(g.driverInfo.Framework.ClientSet)
+	if pattern.FsType == "xfs" {
```
Comment (davidz627) [inline test/e2e/storage/drivers/csi.go]: is there a way to put this check in the "testsuite" skip checks instead of the driver skip tests? This skip "holds" for *any* driver that runs this test suite.

**Comment by mkimuram** [comment]
> 1. Improve debug message to debug failure for aws with ext3

Below log indicates that in-tree aws driver seems to fail in formatting or mounting ext3. 

```
test/e2e/storage/testsuites/volumes.go:153
failed: getting the right fsType ext3
Expected error:
    <*errors.errorString | 0xc00021c250>: {
        s: "Failed to find \"ext3\", last result: \"/dev/xvdbu /opt/0 ext4 rw,relatime,data=ordered 0 0\n\"",
    }
    Failed to find "ext3", last result: "/dev/xvdbu /opt/0 ext4 rw,relatime,data=ordered 0 0
    "
not to have occurred
test/e2e/framework/volume_util.go:483
```

In-tree gce driver passes for both dynamic provisioning and pre-provisioned PV cases, so I suspect that this is in-tree aws driver issue. Note that in-tree aws driver doesn't run pre-provisioned PV case, because it doesn't define necessary methods like ```GetPersistentVolumeSource``` for this driver.

(I believe that https://github.com/kubernetes/kubernetes/pull/67195 has fixed aws drivers to at least not to fail when fsType is specified in provisioining, so this issue should happen after it.)

File: test/e2e/storage/drivers/csi.go (hunk 3 above)
Comment (mkimuram) [reply test/e2e/storage/drivers/csi.go]: @davidz627 

> is there a way to put this check in the "testsuite" skip checks instead of the driver skip tests? This skip "holds" for any driver that runs this test suite.

I think that moving this logic to [```skipUnsupportedTest```](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/base.go#L87) will make xfs tests skip for any drivers and any testsuites. However, to do so, we should blacklist unsupported distros instead of whitelisting just ```"ubuntu"``` and ```"custom"```, because we are not sure which distro will be passed here. (In current code, it assumes that this code path in gce driver's ```SkipUnsupportedTest``` reaches by only gce tests, so just whitelisting them is working fine.)

So, could you let me know which distro to blacklist?
(I guess that ```"gci"``` is needed here and how about ```"debian"``` and ```"coreos"```?)

Comment (mkimuram) [reply test/e2e/storage/drivers/csi.go]: @davidz627 

commit 77784a6 will do above, assuming that only ```"gci"``` should be blacklisted. If this isn't true, please point it out.
(Currently, xfs test seems running only on gce CI, so we can go ahead once we confirm that it is true in gce CI, and add blacklist when we need to add some more latter.)

**Comment by davidz627** [comment]
GCE PD CSI driver will fail because fstype parameter is not supported on CreateVolume.

This is part of a larger problem, I have a PR out here to fix. @mkimuram please keep an eye on it :)

https://github.com/kubernetes-csi/external-provisioner/pull/178

**Comment by mkimuram** [comment]
@davidz627 

e9bbab3 should fix the aws ext3 issue. 
It was caused by not making storage class parameters to lower case for checking ```fsType```, and the key is compared with ```fstype``` as defined in ```volume.VolumeParameterFSType```.

Does this fix need to be reviewed by someone maintaining aws?

File: test/e2e/storage/drivers/csi.go (hunk 2 above)
Comment (msau42) [reply test/e2e/storage/drivers/csi.go]: @davidz627 this will still cause pd csi driver to fail right?  Should we be using the new namespaced fstype parameter?

Comment (msau42) [reply test/e2e/storage/drivers/csi.go]: /hold 
My understanding is PD csi tests in serial will start failing as is

File: test/e2e/storage/drivers/csi.go (hunk 3 above)
Comment (davidz627) [reply test/e2e/storage/drivers/csi.go]: @msau42 @lookuptable do either of you know the answer to this? I am only aware of `gci` not having `xfs` support but there could be more

**Comment by davidz627** [comment]
@mkimuram once https://github.com/kubernetes-csi/external-provisioner/pull/182 is merged and new provisioner v1.0 is cut, we can update the provisioner verison in the test and use the new `csi.storage.k8s.io/fstype` parameter to specify `fstype` for all drivers

File: test/e2e/storage/drivers/csi.go (hunk 3 above)
Comment (msau42) [reply test/e2e/storage/drivers/csi.go]: For gce CI, blacklisting "gci" is fine, although we need to find a way to deal with "custom", which can be both ubuntu or gci.  Can we check for the presence of xfs tools on the node?

**Comment by mkimuram** [comment]
@davidz627 

Thank you for your explanation. I will wait for it.

**Comment by msau42** [comment]
hostpath sidecar vesions are being updated here: https://github.com/kubernetes/kubernetes/pull/71742
and pd csi driver sidecars are being updated here: https://github.com/kubernetes/kubernetes/pull/70941

**Comment by davidz627** [comment]
@mkimuram I think everything is unblocked for this PR to move forward

**Comment by mkimuram** [comment]
@davidz627 

Thank you for your reminder. I will work on it.

**Comment by mkimuram** [comment]
@davidz627 

I rebased the commits and updated ```fsType``` parameter for csi to ```csi.storage.k8s.io/fstype```.
PTAL

**Comment by davidz627** [comment]
tested and working with GCE PD CSI Driver now! Thanks @mkimuram 
/lgtm

**Comment by davidz627** [comment]
/assign @saad-ali 
for final approval

**Review by saad-ali — APPROVED** [review]
/approve
