### PR TITLE
Remove warning about resizing failed for unknown reason

### LINKED ISSUE #131397: NodeExpandVolume is getting called unexpectedly after pvc resize
### What happened?

We did a first resize of pv and pvc it was successful,
Then we did a another resize, we get a warning on pvc describe

```
failed to expand pvc with rpc error: code = Internal desc = Could not resize volume "vol-0157496f5c5f8ee9a": rpc error: code = Internal desc = Could not modify volume "vol-0157496f5c5f8ee9a": operation error EC2: ModifyVolume, https response error StatusCode: 400, RequestID: f4a49e65-d0e7-46de-b308-36ca67a9d796, api error VolumeModificationRateExceeded: You''ve reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
``` 

And after 6 hours a successful resize of pv and pvc happened on EBS volume and the pod(osd) consuming it get resized, but we are getting this warning in pod(osd) describe that is using pvc

```
Warning VolumeResizeFailed 4m55s (x45 over 80m) kubelet NodeExpandVolume.NodeExpandVolume failed to resize volume for volume "pvc-6f50163a-862b-4010-a338-3b587adf8cc1" : volume resizing failed for unknown reason
```

Driver
```
  csi:
    driver: ebs.csi.aws.com
```

StorageClass
```
  storageClassName: gp2-csi

```

### What did you expect to happen?

There should be no such warning as the pv and pvc are resized,

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a PVC resize operation with CSI Driver ebs.csi.aws.com

### Anything else we need to know?

refer https://github.com/kubernetes/kubernetes/issues/117871, https://github.com/kubernetes/kubernetes/pull/123055#issuecomment-2816240906

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

k8s version := 1.32

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://github.com/kubernetes/kubernetes/issues/131397

/sig storage

```release-note
Do not log error event when waiting for expansion on the kubelet
```

### CODE REVIEW

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -1918,10 +1918,8 @@ func (og *operationGenerator) GenerateExpandInUseVolumeFunc(
 		if resizeDone {
 			return volumetypes.NewOperationContext(nil, nil, migrated)
 		}
-		// This is a placeholder error - we should NEVER reach here.
-		err = fmt.Errorf("volume resizing failed for unknown reason")
-		eventErr, detailedErr = volumeToMount.GenerateError("NodeExpandVolume.NodeExpandVolume failed to resize volume", err)
-		return volumetypes.NewOperationContext(eventErr, detailedErr, migrated)
+		klog.InfoS("Waiting for volume to be expandable on the node", "volumeName", volumeToMount.VolumeName)
+		return volumetypes.NewOperationContext(nil, nil, migrated)
```
Comment (parth-gr) [inline pkg/volume/util/operationexecutor/operation_generator.go:1922]: if we are returning `nil`, will it re-try.

If it doesn't retry I think we can merge 1922 return with 1919 return

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go:1922]: It will retry. As long as size in ASOW doesn't match what is expected in DSOW.

**Comment by carlory** [comment]
/lgtm
/hold
for another review. 
/cc @jsafrane @xing-yang

**Comment by akankshapanse** [comment]
@gnufied will this fix be available in any K8s v1.33.X patch release ?
