### PR TITLE
Azure: account for Public IPs when reconciling LoadBalancers

### LINKED ISSUE #80571: Service Controller loop creates orphaned resources
**What happened**:
The issue has been observed on Azure but should also apply to other providers as well. On Azure we observed that there are orphaned Public IPs that don't belong to any Kubernetes LoadBalancer service but from looking at the tags and the name it is clear that Kubernetes created them. In the Azure Activity Log, you can see that the Public IP was deleted when the K8s service was deleted but recreated a few minutes later. That re-creation is also visible in the K8s controller manager logs as a reconcile of the service.

In our case, we add additional worker nodes and delete services at the same time. I think this leads to the re-creation here https://github.com/kubernetes/kubernetes/blob/41b3e60f0e4032eec2caf38348d82641395f7af6/pkg/controller/service/service_controller.go#L686

Because the service list is retrieved at the beginning of the reconcile loop, services that are deleted while the loop is reconciling a recreated by that loop and afterwards orphaned.

**What you expected to happen**:
No orphaned public IPs

**How to reproduce it (as minimally and precisely as possible)**:
Create a few Kubernetes Load Balancer services (we have around 20). Then scale your worker nodes and delete one service at the same time.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.0
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Core OS
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug
/sig cloud-provider

**What this PR does / why we need it**:
- Make sure the existence of Azure load balancer depends on the load balancer resource and public IP resource on Azure

**Which issue(s) this PR fixes**:

Fixes #80571.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update Azure load balancer to prevent orphaned public IP addresses
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
cc @MSSedusch @ritazh @andyzhangx @feiskyer

### CODE REVIEW

**Comment by andyzhangx** [comment]
cc @MSSedusch

File: pkg/controller/service/service_controller.go [hunk 1]
```diff
@@ -92,6 +92,8 @@ const (
 )
 
 type cachedService struct {
+	// Protects cached service state
+	mu sync.Mutex
```
Comment (andyzhangx) [inline pkg/controller/service/service_controller.go]: rename to `mutex`

Comment (chewong) [reply pkg/controller/service/service_controller.go]: I wanted to keep the variable name consistent with `serviceCache` 
https://github.com/kubernetes/kubernetes/blob/6f5c2507ea53612e411d550d62e2ebc6cd4a9767/pkg/controller/service/service_controller.go#L100

**Comment by andrewsykim** [comment]
Doesn't LB Finalizer support fix this? We enabled this by default starting v1.16

**Comment by andrewsykim** [comment]
Initial PR: https://github.com/kubernetes/kubernetes/pull/78262
Bump to beta in v1.16: https://github.com/kubernetes/kubernetes/pull/81691

**Comment by chewong** [comment]
@andrewsykim thanks for the information. I have modified the PR accordingly.

**Review by feiskyer — COMMENTED** [review]
thanks for the fix

/lgtm
/approve

**Comment by andrewsykim** [comment]
/re-title Azure: account for Public IPs when reconciling LoadBalancers

**Comment by andrewsykim** [comment]
/retitle Azure: account for Public IPs when reconciling LoadBalancers

**Comment by andrewsykim** [comment]
Please update the issue description as well based on the merged changes.
