### PR TITLE
Use local PX endpoint for mount, unmount, detach and attach calls

### LINKED ISSUE #49034: A pod using a Portworx volume driver PVC gets stuck in ContainerCreating phase
/kind bug

**What happened**:
A pod using a Portworx volume driver PVC gets stuck in ContainerCreating phase. The kubelet logs indicate that the Mount phase is failing.

**What you expected to happen**:
The pod goes to running and ready state.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a pod spec and restrict the POD to run on a specific minion. Let's call this minion **node1**
- Ensure Portworx node is not running on this minion (using labels and nodAffinity feature)
- Apply the pod spec
- Now observe the pod events and kubelet logs. The mount phase of the pod will keep failing and the pod will be stuck in ContainerCreating state. This will continue even after Portworx on **node1** is brought back up.

**Environment**: k8s version 1.6.5 and above running Portworx cluster. 
- Kubernetes version (use `kubectl version`): k8s version 1.6.5 and above
- Cloud provider or hardware configuration**: any
- OS (e.g. from /etc/os-release): any
- Kernel (e.g. `uname -a`): n/a
- Install tools: n.a
- Others: n/a

### PR DESCRIPTION
**Pull request by harsh-px**
**What this PR does / why we need it**:
This PR fixes an issue with Setup and TearDown of Portworx volumes which has side-effects such a Pod using a Portworx volume not being able to start on the minion.

**Which issue this PR fixes**: fixes #49034 
This PR addresses an issue that fails to mount, attach, unmount or detach a volume when Kubernetes sends these requests to Portworx when it's API server on that particular minion is down. 

Portworx mount, unmount, attach and detach requests need to be received on the minion where the pod is running. So these calls need to talk to the Portworx API server running locally on that node (and NOT to the Portworx k8s service since it may route the request to any node in the cluster). This PR explicitly makes such requests local only.

**Release note**:
```release-note
Fix Pods using Portworx volumes getting stuck in ContainerCreating phase.
```

### CODE REVIEW

File: pkg/volume/portworx/portworx.go [hunk 1]
```diff
@@ -266,7 +266,7 @@ func (b *portworxVolumeMounter) SetUp(fsGroup *int64) error {
 // SetUpAt attaches the disk and bind mounts to the volume path.
 func (b *portworxVolumeMounter) SetUpAt(dir string, fsGroup *int64) error {
 	notMnt, err := b.mounter.IsLikelyNotMountPoint(dir)
-	glog.V(4).Infof("Portworx Volume set up: %s %v %v", dir, !notMnt, err)
+	glog.Infof("Portworx Volume set up. Dir: %s %v %v", dir, !notMnt, err)
```
Comment (gnufied) [inline pkg/volume/portworx/portworx.go]: Do we really want to log these messages *always* in the log files? Looks to me that, older logging priority was more accurate.

File: pkg/volume/portworx/portworx_util.go [hunk 2]
```diff
@@ -70,12 +73,14 @@ func (util *PortworxVolumeUtil) CreateVolume(p *portworxVolumeProvisioner) (stri
...
 	}
+
+	glog.Infof("Successfully created Portworx volume for PVC: %v", p.options.PVC.Name)
 	return volumeID, requestGB, nil, err
 }
 
 // DeleteVolume deletes a Portworx volume
 func (util *PortworxVolumeUtil) DeleteVolume(d *portworxVolumeDeleter) error {
-	driver, err := util.getPortworxDriver(d.plugin.host)
+	driver, err := util.getPortworxDriver(d.plugin.host, false)
```
Comment (gnufied) [inline pkg/volume/portworx/portworx_util.go]: Everywhere we add a naked `true` or `false` argument - we should also add a comment of the form `true /*localOnly*/`

File: pkg/volume/portworx/portworx_util.go [hunk 3]
```diff
@@ -181,13 +186,24 @@ func createDriverClient(hostname string) (*osdclient.Client, error) {
 	}
 }
 
-func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost) (volumeapi.VolumeDriver, error) {
+func (util *PortworxVolumeUtil) getPortworxDriver(volumeHost volume.VolumeHost, localOnly bool) (volumeapi.VolumeDriver, error) {
```
Comment (gnufied) [inline pkg/volume/portworx/portworx_util.go]: Can you document - what that `localOnly` flag does? Why certain calls supply this as `true` while others as `false` ?

File: pkg/volume/portworx/portworx_util.go [hunk 4]
```diff
@@ -181,13 +186,24 @@ func createDriverClient(hostname string) (*osdclient.Client, error) {
...
+	var err error
+	if localOnly {
+		util.portworxClient, err = createDriverClient(volumeHost.GetHostName())
+		if err != nil {
+			return nil, err
+		} else {
+			glog.Infof("Using portworx local service at: %v as api endpoint", volumeHost.GetHostName())
```
Comment (gnufied) [inline pkg/volume/portworx/portworx_util.go]: IMO -  this log message should only appear if verbosity is set to a lower level, not always.

**Review by gnufied — CHANGES_REQUESTED** [review]
Some minor nits - mostly lgtm

File: pkg/volume/portworx/portworx_util.go (hunk 2 above)
Comment (harsh-px) [inline pkg/volume/portworx/portworx_util.go]: Done in incremental diff

File: pkg/volume/portworx/portworx_util.go (hunk 3 above)
Comment (harsh-px) [inline pkg/volume/portworx/portworx_util.go]: Added a function doc in the incremental

File: pkg/volume/portworx/portworx_util.go (hunk 4 above)
Comment (harsh-px) [inline pkg/volume/portworx/portworx_util.go]: Changed to `glog.V(4)` in the incremental

File: pkg/volume/portworx/portworx.go (hunk 1 above)
Comment (harsh-px) [inline pkg/volume/portworx/portworx.go]: We have found tracking down events for volume setup and teardown very important in debugging field issues and hence I've changed the logging level. `SetupAt` and `TearDownAt` get invoked only when pods get scheduled on a new node (new pod or existing pod getting re-scheduled). So these logs entries won't be very chatty.

**Comment by gnufied** [comment]
@k8s-bot ok to test

**Comment by harsh-px** [comment]
@gnufied the pull-kubernetes-node-e2e job is failing but this doesn't seem to anything to do with my change. How do we move forward with this?

**Comment by harsh-px** [comment]
Re-run of the failing test succeeded.

File: pkg/volume/portworx/portworx_util.go (hunk 3 above)
Comment (gnufied) [inline pkg/volume/portworx/portworx_util.go]: I read the docs - and I still don't understand why `CreateDisk` and `DeleteDisk` pass this flag as `false` while others as `true`.

Comment (gnufied) [inline pkg/volume/portworx/portworx_util.go]: Feel free to link to some external docs if the context is large enough to fit in a code comment. We frequently do that in AWS and other volume plugins (or we should be doing that).

Comment (harsh-px) [inline pkg/volume/portworx/portworx_util.go]: Please see if the update comment gives more context. I have given a high-level context on why create and delete calls can use localOnly as false while other's cannot.

Currently, we don't have external docs describing our internal algorithms (most of them are proprietary.)

**Comment by harsh-px** [comment]
@gnufied Thanks for reviewing this. I am guessing you are the only who adds the approved label?

**Comment by gnufied** [comment]
@harsh-px can you open a github issue and link this PR there?

**Comment by harsh-px** [comment]
@gnufied Created issue and linked here.

**Comment by harsh-px** [comment]
@gnufied I need to cherry-pick this into the next 1.7 and 1.6 release. However, the cherry-pick PR would need the milestone label set for these releases in this PR.

What is the process for getting these milestone labels?

**Comment by gnufied** [comment]
@harsh-px you open the PRs against the branches. Since change here is mostly a bug fix, it would be cherry picked by release manager of those branches.

**Comment by harsh-px** [comment]
/release-note Fixes an issue where a pod using a Portworx volume gets stuck in ContainerCreating phase.
