### PR TITLE
Fail Kubemark if tests fail with error.

### LINKED ISSUE #29392: Kubemark-500 run didn't run test and is green
In this run, we didn't even started tests, and the run is green:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-500-gce/4096/console

This is super frightening and should be fixed ASAP.

@kubernetes/test-infra-maintainers @gmarek 

@spxtr - maybe you can take a look or reassign?

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #29392

### CODE REVIEW

File: hack/jenkins/e2e-runner.sh [hunk 1]
```diff
@@ -421,7 +425,7 @@ if [[ "${USE_KUBEMARK:-}" == "true" ]]; then
   # exit non-0.
   # TODO: The above comment is no longer accurate. Need to fix this before
   # turning xunit off for the postsubmit tests. See: #28200
-  ./test/kubemark/run-e2e-tests.sh --ginkgo.focus="${KUBEMARK_TESTS:-starting\s30\spods}" "${KUBEMARK_TEST_ARGS:-}" || dump_cluster_logs
+  ./test/kubemark/run-e2e-tests.sh --ginkgo.focus="${KUBEMARK_TESTS:-starting\s30\spods}" "${KUBEMARK_TEST_ARGS:-}" || dump_cluster_logs_and_exit
```
Comment (wojtek-t) [inline hack/jenkins/e2e-runner.sh]: @spxtr - I know this will make the whole suite to be red, instead of producing some xunit files, but I think it is way better, that silently ignore errors and marking runs as "passed". We should fix those "xunit" files later.

**Comment by spxtr** [comment]
LGTM, thanks.
