### PR TITLE
Calculate the correct machine-type

### LINKED ISSUE #119599: ARM tests has started failing
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial

### Which tests are failing?

seems like an infra issue. No tests run

### Since when has it been failing?

7/21

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?

/kind regression

#### Which issue(s) this PR fixes:

Fixes #119599 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by upodroid** [comment]
/cc @SergeyKanzhelev @dims @chendave 

I have verified this patch by running:

```
kubetest2 noop --test=node \
  -- \
  --repo-root=. --gcp-project=borg-env --gcp-zone=us-central1-a --parallelism=1 \
  --focus-regex="\[Serial\]" --use-dockerized-build=true \
  --target-build-arch=linux/arm64 \
  --skip-regex="\[Flaky\]|\[Slow\]|\[Benchmark\]|\[NodeSpecialFeature:.+\]|\[NodeSpecialFeature\]|\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]|\[NodeFeature:Eviction\]|\[NodeFeature:NodeProblemDetector\]|\[NodeFeature:OOMScoreAdj\]|\[NodeFeature:DevicePluginProbe\]|\[NodeConformance\]|\[Feature:DynamicResourceAllocation\]" \
  --test-args='--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\":\"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"' \
  --image-config-file="${GOPATH}/src/k8s.io/test-infra/jobs/e2e_node/arm/image-config-serial.yaml"
```

It is creating a t2a-standard-2 instance instead of n1-standard-1 instance

/test pull-kubernetes-node-arm64-ubuntu-serial-gce
/test pull-kubernetes-node-crio-cgrpv2-e2e-kubetest2

**Comment by chendave** [comment]
https://testgrid.k8s.io/sig-node-containerd#pull-e2e-arm64-gce&width=90 is now green.

/test pull-kubernetes-unit   (looks like is unrelated, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119603/pull-kubernetes-unit/1684340949473300480)

**Comment by mmiranda96** [comment]
Yeah, looks like that failure was a flake.

/assign @SergeyKanzhelev

File: test/e2e_node/remote/gce/gce_runner.go [hunk 1]
```diff
@@ -768,12 +768,15 @@ func (g *GCERunner) updateKernelArguments(instance *compute.Instance, image stri
 }
 
 func (g *GCERunner) machineType(machine string) string {
+	var ret string
 	if machine == "" && *instanceType != "" {
-		machine = *instanceType
+		ret = *instanceType
+	} else if machine != "" {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/remote/gce/gce_runner.go:774]: this is OK. It may be better to have a big if statement when `machine` is empty with sub-if statement. The logic as written will work, just easier to make a mistake

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
/milestone v1.28

File: test/e2e_node/remote/gce/gce_runner.go (hunk 1 above)
Comment (upodroid) [reply test/e2e_node/remote/gce/gce_runner.go:774]: I'll revisit this after 1.28 is released
