### PR TITLE
kubeadm: add missing cluster-info context validation

### LINKED ISSUE #3250: kubeadm join segfault
Trying to add a worker node to a working cluster. Increading verbosity doesn't give more hints.

K8s: 1.33
OS: Debian Trixie
Linux: 6.12.48+deb13-amd64
Containerd: containerd github.com/containerd/containerd 1.7.24~ds1 1.7.24~ds1-6+b4

```yaml
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration

discovery:
  bootstrapToken:
    token: "zvcv...5amli"
    apiServerEndpoint: "api.mydomain.tld:6443"
    unsafeSkipCAVerification: true
    caCertHashes: ['sha256:be5089...063c10']
  tlsBootstrapToken: "zvc...5amli"

nodeRegistration:
  name: "node11"
```

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"33", EmulationMajor:"", EmulationMinor:"", MinCompatibilityMajor:"", MinCompatibilityMinor:"", GitVersion:"v1.33.5", GitCommit:"03e764d0394bdff662e960c70d25b3c30d731666", GitTreeState:"clean", BuildDate:"2025-09-09T19:50:45Z", GoVersion:"go1.24.6", Compiler:"gc", Platform:"linux/amd64"}
```

```
# kubeadm join --config ./kubeadm-join.yaml -v=5
I1019 01:22:14.894775    6381 join.go:421] [preflight] found NodeName empty; using OS hostname as NodeName
I1019 01:22:14.894828    6381 joinconfiguration.go:83] loading configuration from "./kubeadm-join.yaml"
I1019 01:22:14.895246    6381 initconfiguration.go:123] detected and using CRI socket: unix:///var/run/containerd/containerd.sock
[preflight] Running pre-flight checks
I1019 01:22:14.895292    6381 preflight.go:93] [preflight] Running general checks
I1019 01:22:14.897683    6381 checks.go:278] validating the existence of file /etc/kubernetes/kubelet.conf
I1019 01:22:14.897699    6381 checks.go:278] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I1019 01:22:14.897707    6381 checks.go:102] validating the container runtime
I1019 01:22:14.897991    6381 checks.go:637] validating whether swap is enabled or not
I1019 01:22:14.898027    6381 checks.go:368] validating the presence of executable losetup
I1019 01:22:14.898046    6381 checks.go:368] validating the presence of executable mount
I1019 01:22:14.898060    6381 checks.go:368] validating the presence of executable cp
I1019 01:22:14.898074    6381 checks.go:514] running all checks
I1019 01:22:14.907378    6381 checks.go:399] checking whether the given node name is valid and reachable using net.LookupHost
I1019 01:22:14.907737    6381 checks.go:603] validating kubelet version
I1019 01:22:14.936744    6381 checks.go:128] validating if the "kubelet" service is enabled and active
I1019 01:22:14.949234    6381 checks.go:201] validating availability of port 10250
I1019 01:22:14.949370    6381 checks.go:278] validating the existence of file /etc/kubernetes/pki/ca.crt
I1019 01:22:14.949380    6381 checks.go:428] validating if the connectivity type is via proxy or direct
I1019 01:22:14.949396    6381 join.go:551] [preflight] Discovering cluster-info
I1019 01:22:14.949408    6381 token.go:72] [discovery] Created cluster-info discovery client, requesting info from "api.mydomain.tld:6443"
I1019 01:22:14.949499    6381 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I1019 01:22:14.949509    6381 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I1019 01:22:14.949513    6381 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I1019 01:22:14.949517    6381 envvar.go:172] "Feature gate default state" feature="InOrderInformers" enabled=true
I1019 01:22:14.949520    6381 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I1019 01:22:14.949709    6381 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "zvcvj1"
I1019 01:22:14.955640    6381 token.go:127] [discovery] Requesting info from "api.mydomain.tld:6443" again to validate TLS against the pinned public key
I1019 01:22:14.955785    6381 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "zvcvj1"
I1019 01:22:14.961644    6381 token.go:150] [discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "api.mydomain.tld:6443"
I1019 01:22:14.961655    6381 discovery.go:53] [discovery] Using provided TLSBootstrapToken as authentication credentials for the join process
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x24490a9]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/discovery.For({0x0?, 0x0?}, 0xc000562d80)
        k8s.io/kubernetes/cmd/kubeadm/app/discovery/discovery.go:57 +0x169
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*joinData).TLSBootstrapCfg(0xc0004550a0)
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:552 +0xd4
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*joinData).InitCfg(0xc0004550a0)
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:562 +0x29
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runPreflight({0x2a1f840?, 0xc0004550a0})
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join/preflight.go:102 +0x1e5
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(...)
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(...)
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0xc0004e4900, {0xc000529530, 0x0, 0x3})
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234 +0x502
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1(0xc00063b900?, {0xc000529530, 0x0, 0x3})
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/join.go:185 +0x85
github.com/spf13/cobra.(*Command).execute(0xc000642608, {0xc0005294d0, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xad4
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001fa908)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x44f
github.com/spf13/cobra.(*Command).Execute(0x2fb3d40?)
        github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
k8s.io/kubernetes/cmd/kubeadm/app.Run()
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:47 +0xad
main.main()
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25 +0x13
```

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

    kubeadm: add missing cluster-info context validation

    When retrieving the cluster-info CM, ensure the cluster pointed
    out by the current context in the kubeconfig is validated.

    Add unit test for the above.

    Make the function GetClusterFromKubeConfig() to return various
    errors. Handle the errors on call sites. Add unit tests
    for the update.

    The above changes prevent panics when the users has manually
    edited and malformed the kubeconfig in the cluster-info CM.

#### Which issue(s) this PR is related to:

fixes https://github.com/kubernetes/kubeadm/issues/3250

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: avoid panicing if the user has malformed the kubeconfig in the cluster-info config map to not include a valid current context. Include proper validation at the appropriate locations and throw errors instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -104,17 +104,21 @@ func WriteToDisk(filename string, kubeconfig *clientcmdapi.Config) error {
...
 	if currentContext != nil {
-		return currentContext.Cluster, config.Clusters[currentContext.Cluster]
+		if config.Clusters[currentContext.Cluster] != nil {
+			return currentContext.Cluster, config.Clusters[currentContext.Cluster], nil
+		}
+		return "", nil, errors.Errorf("no matching cluster for the current context %q", config.CurrentContext)
 	}
-	return "", nil
+
+	return "", nil, errors.Errorf("the current context is invalid %q", config.CurrentContext)
```
Comment (carlory) [inline cmd/kubeadm/app/util/kubeconfig/kubeconfig.go]:
```suggestion
	return "", nil, errors.Errorf("the current context %q is invalid", config.CurrentContext)
```

File: cmd/kubeadm/app/util/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -146,7 +150,7 @@ func HasAuthenticationCredentials(config *clientcmdapi.Config) bool {
 		return true
 	}
 
-	// authprovider authentication
+	// authprovider authentication``
```
Comment (carlory) [inline cmd/kubeadm/app/util/kubeconfig/kubeconfig.go]: why we need ``?

File: cmd/kubeadm/app/util/kubeconfig/kubeconfig.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/kubeconfig/kubeconfig.go]: i will leave it at the end as `the current context: %s` to keep it easier to error-match in the unit test.

File: cmd/kubeadm/app/util/kubeconfig/kubeconfig.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/kubeconfig/kubeconfig.go]: just some typo.

**Review by HirazawaUi — COMMENTED** [review]
/lgtm
