### PR TITLE
Fix watchForLockfileContention memory leak

### LINKED ISSUE #94583: Inotify:memory leak due to blocked operation
**What happened**:
i wrote a shell：
```bash
#!/bin/bash

while [ true ]
do
        echo "reduce pod..."
        kubectl scale --replicas=0 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l

        echo "add pod ..."
        kubectl scale --replicas=110 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l
done

```
then the kubelet's RSS increases continuously and does not release，
i make some trace and found some watched objects have never been released  even these objects have not existed in real word
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L103-L104

i notice the fucntion readEvent  is producer for these abnormal objects 
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L135

and print the length of every event，some of which is beyond the length of buf：
https://github.com/kubernetes/kubernetes/blob/16ea9dc6bc260c37589e6b104a47009680c26772/vendor/k8s.io/utils/inotify/inotify_linux.go#L136

even when i increase the array by 10 times，the problem is still there and  the limits are broken through again and again.
so i realized the process of reading cannot be blocked.

now i added a queue for  the  buf of every inotify event and added another goroutine to consume the queue. everythings 
seems good for now.

**What you expected to happen**:
fixed the bug
**How to reproduce it (as minimally and precisely as possible)**:
running the shell :
```bash
#!/bin/bash

while [ true ]
do
        echo "reduce pod..."
        kubectl scale --replicas=0 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l

        echo "add pod ..."
        kubectl scale --replicas=50 rc ubuntu
        kubectl get pod -A | grep Running | wc -l
        sleep 60s
        kubectl get pod -A | grep Running | wc -l
done

```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.17.9 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```bash
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

```
- Kernel (e.g. `uname -a`):
```bash
uname -a
Linux k8s 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #100241: kubelet uses 120GB memory after 20,000 job created and retains 80GB memory after jobs completed and deleted
#### What happened:
1.create 20K job and each job is a java application running data monitor and analysis 
2.delete all jobs after they have been completed
3.kubelet memory usage 120GB memory:
```
Name:   kubelet
Umask:  0022
State:  S (sleeping)
Tgid:   9278
Ngid:   9278
Pid:    9278
PPid:   9274
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 1024
Groups:
VmPeak: 126307060 kB
VmSize: 126307056 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:  106238456 kB
VmRSS:  85699368 kB
RssAnon:        85675408 kB
RssFile:           23960 kB
RssShmem:              0 kB
VmData: 126179776 kB
VmStk:       132 kB
VmExe:     48260 kB
VmLib:      2072 kB
VmPTE:    210628 kB
VmSwap:    72604 kB
Threads:        362
```

#### What you expected to happen:
kubelet should use and retain less memory 

#### Anything else we need to know?:
Through pprof,we find the inuse_space size is 360MB.And 67% of 120GB is Anonymous(through mmap?).

#### Environment:
- Kubernetes version (use `kubectl version`):
- Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-22T06:47:35Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Centos 7.5
- Kernel (e.g. `uname -a`):
- 3.10.0-957.21.3.el7.x86_64 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
pprof png:
profile002

### LINKED ISSUE #101724: kubelet memory leak v1.18.1
#### What happened:
kubelet increased more than 100MB in memory in 4 days.

#### What you expected to happen:
kubelet to not used that amount of RAM

#### How to reproduce it (as minimally and precisely as possible):
I have reproduced it using 3 cronjobs which create hello world pods each minute
and another cronjob that writes a line to a file each minute.

#### Environment:
- Kubernetes version (use `kubectl version`):
v1.18.1

- Cloud provider or hardware configuration
 happens on both virtualbox and baremetal

- OS (e.g: `cat /etc/os-release`):
centos 7

- Kernel (e.g. `uname -a`):
4.18.0-147.3.1

I have seen some existing issues like #64137 but I do not have any dangling resources associated with the cgroup.

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug
/sig node

#### Which issue(s) this PR fixes:

Fixes #94583
Fixes #100241
Fixes #101724

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: cmd/kubelet/app/server_linux.go [hunk 1]
```diff
@@ -29,6 +29,7 @@ func watchForLockfileContention(path string, done chan struct{}) error {
 	}
 	if err = watcher.AddWatch(path, inotify.InOpen|inotify.InDeleteSelf); err != nil {
 		klog.ErrorS(err, "Unable to watch lockfile")
+		watcher.Close()
```
Comment (lala123912) [inline cmd/kubelet/app/server_linux.go:32]: I wonder whether this can use defer here?

Comment (wzshiming) [reply cmd/kubelet/app/server_linux.go:32]: Can't use defer here, because need to return the watcher. It is closed only when an error occurs or the first event is received.

Comment (lala123912) [reply cmd/kubelet/app/server_linux.go:32]: Got it, Thanks.

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
