### PR TITLE
kubeadm: move the "kubelet-start" phase after "kubeconfig" for "init"

### LINKED ISSUE #1986: openrc: kubeadm is starting kubelet before complete config is writte to disk
reported by @kvaster here:
https://github.com/kubernetes/kubernetes/issues/86538

> **What happened**:
> kubeadm is timing out during cluster initialization on openrc systems.
> Kubelet is failing to start cause there is no complete configuration on the disk.
> 
> **What you expected to happen**:
> It is expected to have complete config already written to disk before attempt to start kubelet.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> Bug is reproducable with no configuration just by running `kubeadm init`
> 
> **Anything else we need to know?**:
> Bug is not reproducable on systemd cause kubelet is constantly restarting until it can read all configuration files. And on openrc by default kubelet is not restarted once it fails with config. My proposition is to change order of configuration and launching:
> 
> ```
> diff --git a/cmd/kubeadm/app/cmd/init.go b/cmd/kubeadm/app/cmd/init.go
> index 57e87d6603e..942b2057909 100644
> --- a/cmd/kubeadm/app/cmd/init.go
> +++ b/cmd/kubeadm/app/cmd/init.go
> @@ -172,9 +172,9 @@ func NewCmdInit(out io.Writer, initOptions *initOptions) *cobra.Command {
> 
>         // initialize the workflow runner with the list of phases
>         initRunner.AppendPhase(phases.NewPreflightPhase())
> -       initRunner.AppendPhase(phases.NewKubeletStartPhase())
>         initRunner.AppendPhase(phases.NewCertsPhase())
>         initRunner.AppendPhase(phases.NewKubeConfigPhase())
> +       initRunner.AppendPhase(phases.NewKubeletStartPhase())
>         initRunner.AppendPhase(phases.NewControlPlanePhase())
>         initRunner.AppendPhase(phases.NewEtcdPhase())
>         initRunner.AppendPhase(phases.NewWaitControlPlanePhase())
> ```
> 
> **Environment**:
> kubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"archive", BuildDate:"2019-12-18T09:14:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by xphoniex**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

running `kubeadm init` gets stuck on alpine linux because it uses a different init system lacking re-try mechanism and for some reason `kubeadm` tries to start `kubelet` service before required conf files are copied, thus leaving the service in crashed state.
 

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubeadm/issues/1986

**Special notes for your reviewer**:

We can only run `kubelet-restart` phase in case we detect non-systemd or openrc but this would barely make any difference in performance.

**Does this PR introduce a user-facing change?**:

```release-note
action required: kubeadm: Move the "kubeadm init" phase "kubelet-start" later in the init workflow, after the "kubeconfig" phase. This makes kubeadm start the kubelet only after the KubeletConfiguration component config file (/var/lib/kubelet/config.yaml) is generated and solves a problem where init systems like OpenRC cannot crashloop the kubelet service.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
n/a
```

### CODE REVIEW

**Comment by xphoniex** [comment]
cla signed

**Comment by xphoniex** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

CLI signed

File: cmd/kubeadm/app/cmd/init.go [hunk 1]
```diff
@@ -177,6 +177,7 @@ func NewCmdInit(out io.Writer, initOptions *initOptions) *cobra.Command {
 	initRunner.AppendPhase(phases.NewKubeConfigPhase())
 	initRunner.AppendPhase(phases.NewControlPlanePhase())
 	initRunner.AppendPhase(phases.NewEtcdPhase())
+	initRunner.AppendPhase(phases.NewKubeletRestartPhase())
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/init.go:180]: why not patch the `NewKubeletStartPhase` phase to have a managed restart loop (in kubeadm, for something like 2 minutes) in the case of a detected openrc system?

would that work. adding a new phase does not seem needed for the systemd case, so we should avoid it.

also did you try that the change recommended here fixes the problem?
https://github.com/kubernetes/kubeadm/issues/1986
(moving the start phase)

Comment (xphoniex) [reply cmd/kubeadm/app/cmd/init.go:180]: > why not patch the NewKubeletStartPhase phase to have a managed restart loop (in kubeadm, for something like 2 minutes) in the case of a detected openrc system? would that work?

could work but `kubeadm` should not become another init system as this would cause sync issues and might break something in edge cases. 

unless we expect `kubelet` to fail randomly in other ways and restarting to heal those failures, a one-time restart would suffice here.

> adding a new phase does not seem needed for the systemd case, so we should avoid it.

as systemd already does the restart itself, I expect a one-time restart to not cause any harm and actually improve start time by ~a second, also we can easily turn this phase into a no-op for systemd.

> also did you try that the change recommended here fixes the problem?
kubernetes/kubeadm#1986
(moving the kubelet start phase)

I didn't try it, but it'd have been my proposed solution had I not seen this [comment](https://github.com/kubernetes/kubeadm/issues/1986#issuecomment-568599142) of yours:
```
this is something that we discussed at some point, but the problem is that 
at this point it could be a breaking change to all the users that separated 
the init process into phases.
```

I wanted my solution to change as little as possible and as a result I didn't modify existing phases like `NewKubeletStartPhase` and since moving phases could be a breaking change, I opted for creating a small, separate phase.

Comment (neolit123) [reply cmd/kubeadm/app/cmd/init.go:180]: we also have the NewKubeletFinalizePhase phase and this could be potentially a sub-phase in there called "restart".
the "restart" phase can detect the init system and A) do nothing in the case of systemd B) perform a restart if openrc is detected as the init system.

adding it as a parent phase is far from ideal.

> this is something that we discussed at some point, but the problem is that 
at this point it could be a breaking change to all the users that separated 
the init process into phases.

in any case i think i should bring this as a discussion topic in the next week meeting and see what the wider group thinks.

Comment (xphoniex) [reply cmd/kubeadm/app/cmd/init.go:180]: kubeadm gets stuck on `NewWaitControlPlanePhase` which is at line 181: https://github.com/kubernetes/kubernetes/blob/a713c8f6fb21e3f171510a104b700aef5fd88555/cmd/kubeadm/app/cmd/init.go#L180-L186

`NewKubeletFinalizePhase` is way further down at line 186.

Comment (rosti) [reply cmd/kubeadm/app/cmd/init.go:180]: Let's discuss this in the office hours. In the long term we should try to reconcile systemd, OpenRC, and Windows' Service Manager:
- A service should be installed disabled if it's not installed with a default configuration (ready to go). The same should apply to the kubelet.
- If a service is enabled, it should restart after it crashes (what it now does constantly on systemd).
- kubeadm (and any other deployment tool) should enable the service and start it after it's configured.

This required some syncing with SIG Release and SIG Arch and a huge "action required" note somewhere.

**Review by rosti — COMMENTED** [review]
Thanks for tackling this @xphoniex !

File: cmd/kubeadm/app/cmd/init.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/init.go:180]: @xphoniex 

so we had a discussion about this problem in the kubeadm meeting today.
the introduction of a new phase or reordering phases is not exactly desired to solve the openrc case for the time being.

so we discussed this:

>> why not patch the NewKubeletStartPhase phase to have a managed restart loop (in kubeadm, for something like 2 minutes) in the case of a detected openrc system? would that work?

we sort of a agreed during the meeting that this is an OK option, but now i started thinking more about the actual implementation it ended up hacky and abrupt for kubeadm to manage the restart. we may have to os.Exit(1) kubeadm from go routine and so on.

[1] so my latest proposal for a **short term** fix is to just move the kubelet-start phase before the wait-control-plane phase, and here is why it will not be that breaking:
- if users are using systemd, due to systemd supporting restarts, the location of the kublet-start phase is not important as long as they are calling it before wait-control-plane.
- systemd users can optionally adjust their phase order as long as we have an action-required release note.
- this has been bugging systemd and windows people too. as the crashlooping of kubeadm's managed kubelet is not really needed.

this solves @rosti's comment above:
> kubeadm (and any other deployment tool) should enable the service and start it after it's configured.

also solves this openrc issue https://github.com/kubernetes/kubeadm/issues/1986.

**long term**
- openrc should support [automatic restarts](https://dev.gentoo.org/~vapier/openrc/projects/openrc/ticket/120.html)? i don't know what is the state of this problem there...but an init system not-supporting programmable restarts is far from ideal.
- apply the changes @rosti suggests above to k8s packages.

**alternative option as proposed by @rosti (if we end up rejecting [1]) **
- Alpine users can try wrapping the kubelet in a shim that manages its restarts, given openrc cannot do that.

Comment (xphoniex) [reply cmd/kubeadm/app/cmd/init.go:180]: > we sort of a agreed during the meeting that this is an OK option, but now i started thinking more about the actual implementation it ended up hacky and abrupt for kubeadm to manage the restart. we may have to os.Exit(1) kubeadm from go routine and so on.

also there are places which kubeadm stops kubelet service, e.g. to write config files. it wouldn't break anything atm but if there's a need in future to stop the kubelet service, someone's going to be very confused why their code isn't working since goroutine keeps restarting it.

> [1] so my latest proposal for a short term fix is to just move the kubelet-start phase before the wait-control-plane phase

sounds good to me!

I thought the issue was some users running their kubeadm phase by phase hence why we wouldn't want to reorder it. otherwise yeah, this should not break anything but if a user was using kubeadm phase by phase then they need to modify their scripts. 

> openrc should support automatic restarts? i don't know what is the state of this problem there...but an init system not-supporting programmable restarts is far from ideal.

openrc has something called [supervise-daemon](https://wiki.gentoo.org/wiki/OpenRC/supervise-daemon) which is supposed to handle restarts for us but it's **experimental** and basically misbehaving on my VM and some older alpine releases. 

we need a simple fix for now to get this working and in the long run superviced or whatever else the gentoo/alpine community comes up with would be the answer.

> alternative options (if we end up rejecting [1])

see above ^

Comment (rosti) [reply cmd/kubeadm/app/cmd/init.go:180]: I am glad that we are having an action plan here for the time being. Let's do what @neolit123 proposed and put an "Action Required" release note on this PR.

Comment (xphoniex) [reply cmd/kubeadm/app/cmd/init.go]: done, please check @neolit123 .

**Comment by neolit123** [comment]
@xphoniex 

please change the box under `Does this PR introduce a user-facing change?` to:
> action required: kubeadm: Move the "kubeadm init" phase "kubelet-start" later in the init workflow, after the "kubeconfig" phase. This makes kubeadm start the kubelet only after the KubeletConfiguration component config file (/var/lib/kubelet/config.yaml) is generated and solves a problem where init systems like OpenRC cannot crashloop the kubelet service.

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/retest

**Comment by xphoniex** [comment]
@neolit123 is this even related to kubeadm?
```
W0515 15:12:38.071]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2
e.py", line 111, in check_env
W0515 15:12:38.071]     subprocess.check_call(cmd, env=env)
W0515 15:12:38.072]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0515 15:12:38.072]     raise CalledProcessError(retcode, cmd)
W0515 15:12:38.072] subprocess.CalledProcessError: Command '('kubetest', '--dump=/works
pace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '-
-build=bazel', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce', '--up
', '--down', '--test', '--provider=gce', '--cluster=e2e-7d24a0a517-674b9', '--gcp-netwo
rk=e2e-7d24a0a517-674b9', '--extract=local', '--gcp-node-image=gci', '--gcp-zone=us-wes
t1-b', '--ginkgo-parallel=30', '--runtime-config=batch/v2alpha1=true', '--test_args=--g
inkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minS
tartupPods=8', '--timeout=80m')' returned non-zero exit status 1
E0515 15:12:38.073] Command failed
```

**Comment by neolit123** [comment]
/retitle kubeadm: move the "kubelet-start" phase after "kubeconfig" for "init"

**Comment by neolit123** [comment]
> is this even related to kubeadm?

some test jobs are flaky. `/retest` retests them.

**Comment by xphoniex** [comment]
This is really not fun, [pull-kubernetes-verify](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/90892/pull-kubernetes-verify/1261290199460089859) ran for 2h0m22s only to fail to a seemingly unrelated issue:

```
+++ Running case: verify.openapi-spec 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-openapi-spec.sh"
Downloading https://github.com/coreos/etcd/releases/download/v3.4.7/etcd-v3.4.7-linux-a
md64.tar.gz succeed
{"component":"entrypoint","file":"prow/entrypoint/run.go:245","func":"k8s.io/test-infra
/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit befor
e 15s grace period","time":"2020-05-15T18:08:52Z"} 
```

Can someone help verify if it's related to my commit or not? Because if not, the test jobs are not just flaky, they are broken.

**Comment by neolit123** [comment]
will LGTM myself if nobody has comment until EOD today.

**Review by rosti — APPROVED** [review]
Thanks @xphoniex !
/lgtm
