### PR TITLE
GCE: Get automatically created subnetwork if none is specified for auto network

### LINKED ISSUE #57350: GCE: ILB creation can fail if subnets are manually added to automatic network and no subnetwork is specified.
/kind bug

**What happened**:
Continuation of #53409. The fix to that bug only takes the first subnetwork in the correct region. However, if the user added manual subnets in the region that the cluster exists, it's possible the cloudprovider could choose the wrong subnet. 

**What you expected to happen**:
If no subnet is specified for a non-legacy network, always take the subnet which was automatically created.

/assign
/sig network
/area platform/gce

### PR DESCRIPTION
**Pull request by nicksardo**
Fixes #57350 

**Release note**:
```release-note
GCE: Fixes ILB creation on automatic networks with manually created subnetworks.
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -499,6 +487,32 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
 	return gce, nil
 }
 
+func determineSubnetURL(service *compute.Service, networkProjectID, networkName, region string) (string, bool, error) {
+	n, err := getNetwork(service, networkProjectID, networkName)
+	if err != nil {
+		return "", false, fmt.Errorf("eould not retrieve network %q in attempt to determine if legacy network or see list of subnets; err: %v", networkName, err)
```
Comment (dividinglimits) [inline pkg/cloudprovider/providers/gce/gce.go]: what does "eould" mean in this context?

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: Typo.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 2]
```diff
@@ -499,6 +487,32 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
 	return gce, nil
 }
 
+func determineSubnetURL(service *compute.Service, networkProjectID, networkName, region string) (string, bool, error) {
```
Comment (dividinglimits) [inline pkg/cloudprovider/providers/gce/gce.go]: Under what circumstance would a return of (string, error) not be sufficient to provide the necessary data? It returns either an error, or a subnet, but never both.

```
const (
  ErrNoNetwork = fmt.Errorf("eould not retrieve network %q in attempt to determine if legacy network or see list of subnets; err: %v", networkName, err)
  ErrLegacyNetwork = fmt.Errorf("Determined network %q is of type legacy.", networkName")
  ErrSubnetList = fmt.Errorf("error listing subnets of network %q within region %v. err: %v", networkName, region, err)
  ErrNoAutoSubnets = fmt.Errorf("could not find any auto subnet in region %q within list %+v", region, subnets)
)
...

[line 442] subnetURL, err = determineSubnetURL(service, netProjID, networkName, config.Region)

  if _, ok := err.(ErrLegacyNetwork) {
    // Gracefully fail because kubelet calls CreateGCECloud without any config, and API calls will fail coming from minions.
    glog.Warningf("Could not retrieve network %q in attempt to determine if legacy network or see list of subnets, err %v", networkURL, err)
    glog.Warning(err)
  }

 ...
}
```

File: pkg/cloudprovider/providers/gce/gce_util.go [hunk 3]
```diff
@@ -211,3 +219,58 @@ func handleAlphaNetworkTierGetError(err error) (string, error) {
...
+	for i, b := range cidr.Mask {
+		ip[i] |= ^b
+	}
+	return ip
+}
+
+// subnetsInAutoCIDR takes a list of subnets for a single region and
+// returns subnets which exists in the auto CIDR range.
+func subnetsInAutoCIDR(subnets []*compute.Subnetwork) ([]*compute.Subnetwork, error) {
+	var res []*compute.Subnetwork
```
Comment (rramkumar1) [inline pkg/cloudprovider/providers/gce/gce_util.go]: I would suggest changing the signature of the function to take in a CIDR range and change the function name to something like subnetsInCIDR(). This would make the function more generic and fix the issue we discussed offline.

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce_util.go]: Good call, thanks!

File: pkg/cloudprovider/providers/gce/gce.go [hunk 4]
```diff
@@ -499,6 +502,30 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
...
+	if err != nil {
+		return "", err
+	}
+
+	if len(autoSubnets) == 0 {
+		return "", fmt.Errorf("no subnet exists in auto CIDR")
+	}
+
+	if len(autoSubnets) > 1 {
+		return "", fmt.Errorf("multiple subnetworks exist in auto CIDR")
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: "in the same region"

File: pkg/cloudprovider/providers/gce/gce_util.go [hunk 5]
```diff
@@ -211,3 +219,58 @@ func handleAlphaNetworkTierGetError(err error) (string, error) {
...
+type netType string
+
+const (
+	netTypeLegacy netType = "LEGACY"
+	netTypeAuto   netType = "AUTO"
+	netTypeCustom netType = "CUSTOM"
+)
+
+func typeOfNetwork(network *compute.Network) netType {
+	if len(network.IPv4Range) > 0 {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce_util.go]: [minor] I find `network.IPv4Range != ""` to be easier to read

File: pkg/cloudprovider/providers/gce/gce.go (hunk 4 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: Done.

File: pkg/cloudprovider/providers/gce/gce_util.go (hunk 5 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce_util.go]: Done.

**Review by bowei — APPROVED** [review]
/lgtm
