### PR TITLE
Final vet fixes; enabling vet checks in verify scripts.

### LINKED ISSUE #22523: Fix new vet issues
These creep in over time.  Fix the current batch:
https://goreportcard.com/report/k8s.io/kubernetes#go_vet

### PR DESCRIPTION
**Pull request by goltermann**
Fixes #22523, #22524

### CODE REVIEW

File: cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go [hunk 1]
```diff
@@ -65,8 +65,7 @@ func Packages(context *generator.Context, arguments *args.GeneratorArgs) generat
 	inputs := sets.NewString(arguments.InputDirs...)
 	packages := generator.Packages{}
 	header := append([]byte(
-		`
-// +build !ignore_autogenerated
+		`// +build !ignore_autogenerated
```
Comment (krousey) [inline cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go]: I would re-run the deep copy generator if you do this.

File: cmd/libs/go2idl/conversion-gen/generators/conversion.go [hunk 2]
```diff
@@ -131,8 +131,7 @@ func Packages(context *generator.Context, arguments *args.GeneratorArgs) generat
 	inputs := sets.NewString(arguments.InputDirs...)
 	packages := generator.Packages{}
 	header := append([]byte(
-		`
-// +build !ignore_autogenerated
+		`// +build !ignore_autogenerated
```
Comment (krousey) [inline cmd/libs/go2idl/conversion-gen/generators/conversion.go]: Also re-run the conversion generator.

File: cmd/libs/go2idl/import-boss/generators/import_restrict.go [hunk 3]
```diff
@@ -132,27 +131,6 @@ type importRuleFile struct{}
 
 func (importRuleFile) AssembleFile(f *generator.File, path string) error {
```
Comment (krousey) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: @lavalamp Can this whole function just go away?

File: contrib/mesos/pkg/scheduler/queuer/pod.go [hunk 4]
```diff
@@ -86,7 +86,7 @@ func (p *Pod) GetUID() string {
 
 // implements Deadlined
 func (dp *Pod) Deadline() (time.Time, bool) {
-	if dp.Deadline != nil {
+	if dp.deadline != nil {
```
Comment (krousey) [inline contrib/mesos/pkg/scheduler/queuer/pod.go]: Wow. What was the vet error that caught this one?

File: examples/examples_test.go [hunk 5]
```diff
@@ -128,7 +128,8 @@ func validateObject(obj runtime.Object) (errors field.ErrorList) {
 		}
 		errors = expvalidation.ValidateDaemonSet(t)
 	default:
-		return field.ErrorList{field.InternalError(field.NewPath(""), fmt.Errorf("no validation defined for %#v", obj))}
+		errors = field.ErrorList{}
+		errors = append(errors, field.InternalError(field.NewPath(""), fmt.Errorf("no validation defined for %#v", obj)))
```
Comment (krousey) [inline examples/examples_test.go]: Why? Didn't `godep go vet` fix the list alias issue?

File: contrib/mesos/pkg/scheduler/queuer/pod.go (hunk 4 above)
Comment (goltermann) [inline contrib/mesos/pkg/scheduler/queuer/pod.go]: Yeah, bad news.  "comparison of function Deadline != nil is always true"

File: hack/verify-govet.sh [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+for arg; do
+  if [[ "${arg}" == -* ]]; then
+    goflags+=("${arg}")
+  else
+    targets+=("${arg}")
+  fi
+done
+
+if [[ ${#targets[@]} -eq 0 ]]; then
+  targets=`go list -f '{{.ImportPath}}' ./...`
```
Comment (krousey) [inline hack/verify-govet.sh]: Isn't this format string the default?

Comment (krousey) [inline hack/verify-govet.sh]: Also, use `$(go list ./...)` instead of back ticks.

Comment (krousey) [inline hack/verify-govet.sh]: You could also filter out `third_party` here instead of having to do a for loop below.

File: hack/verify-govet.sh [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+    # Remove any lines go vet or godep outputs with the exit status.
+    # Remove any lines godep outputs about the vendor experiment.
+    #
+    # If go vet fails (produces output), grep will succeed, but if go vet
+    # succeeds (produces no output) grep will fail. Then we just use
+    # PIPESTATUS[0] which is go's exit code.
+    #
+    # The intended result is that each incantation of this line returns
+    # either 0 (pass) or 1 (fail).
+    godep go vet "${goflags[@]:+${goflags[@]}}" $i 2>&1 \
```
Comment (krousey) [inline hack/verify-govet.sh]: Should double quote `$i` to prevent globbing and word splitting.

**Comment by krousey** [comment]
```console
Verifying ./hack/../hack/verify-govet.sh
cmd/libs/go2idl/parser/parse_test.go:41: k8s.io/kubernetes/cmd/libs/go2idl/namer.Orderer composite literal uses unkeyed fields
cmd/libs/go2idl/client-gen/main.go:97: k8s.io/kubernetes/cmd/libs/go2idl/client-gen/args.Args composite literal uses unkeyed fields
cmd/libs/go2idl/client-gen/main.go:116: k8s.io/kubernetes/cmd/libs/go2idl/client-gen/args.Args composite literal uses unkeyed fields
cmd/libs/go2idl/generator/generator.go:187: k8s.io/kubernetes/cmd/libs/go2idl/namer.Orderer composite literal uses unkeyed fields
cmd/libs/go2idl/client-gen/generators/client_generator.go:198: k8s.io/kubernetes/cmd/libs/go2idl/namer.Orderer composite literal uses unkeyed fields
pkg/client/clientset_generated/internalclientset/fake/clientset_generated.go:59: k8s.io/kubernetes/pkg/client/typed/discovery/fake.FakeDiscovery composite literal uses unkeyed fields
pkg/client/clientset_generated/internalclientset/fake/clientset_generated.go:66: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake.FakeCore composite literal uses unkeyed fields
pkg/client/clientset_generated/internalclientset/fake/clientset_generated.go:71: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/extensions/unversioned/fake.FakeExtensions composite literal uses unkeyed fields
pkg/client/clientset_generated/release_1_2/fake/clientset_generated.go:59: k8s.io/kubernetes/pkg/client/typed/discovery/fake.FakeDiscovery composite literal uses unkeyed fields
pkg/client/clientset_generated/release_1_2/fake/clientset_generated.go:66: k8s.io/kubernetes/pkg/client/clientset_generated/release_1_2/typed/core/v1/fake.FakeCore composite literal uses unkeyed fields
pkg/client/clientset_generated/release_1_2/fake/clientset_generated.go:71: k8s.io/kubernetes/pkg/client/clientset_generated/release_1_2/typed/extensions/v1beta1/fake.FakeExtensions composite literal uses unkeyed fields
contrib/mesos/pkg/node/registrator_test.go:54: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake.FakeNodes composite literal uses unkeyed fields
contrib/mesos/pkg/node/registrator_test.go:87: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake.FakeNodes composite literal uses unkeyed fields
contrib/mesos/pkg/node/registrator_test.go:125: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake.FakeNodes composite literal uses unkeyed fields
pkg/kubectl/scale_test.go:350: k8s.io/kubernetes/pkg/client/unversioned/testclient.FakeExperimental composite literal uses unkeyed fields
pkg/kubectl/scale_test.go:589: k8s.io/kubernetes/pkg/client/unversioned/testclient.FakeExperimental composite literal uses unkeyed fields
pkg/kubectl/stop_test.go:707: arg fake.Actions in printf call is a function value, not a function call
federation/cmd/federated-apiserver/app/server_test.go:223: arg expectedConfig for printf verb %q of wrong type: *k8s.io/kubernetes/pkg/genericapiserver.ResourceConfig
cmd/kube-apiserver/app/server_test.go:223: arg expectedConfig for printf verb %q of wrong type: *k8s.io/kubernetes/pkg/genericapiserver.ResourceConfig
FAILED   ./hack/../hack/verify-govet.sh	135s
```

Looks like you're not done.

File: examples/examples_test.go (hunk 5 above)
Comment (goltermann) [inline examples/examples_test.go]: Yeah, I did expect the addition of godep to fix this and the one in cmd_test.go, but it still complained.

File: cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go (hunk 1 above)
Comment (goltermann) [inline cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go]: The newline at the beginning doesn't actually make a difference in output.  Same with the conversion one.

**Comment by goltermann** [comment]
https://travis-ci.org/kubernetes/kubernetes/builds/122572394 worked just fine.

It's possible I'm racing against brand new code submitted.  Where did you get that output?

File: cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go (hunk 1 above)
Comment (krousey) [inline cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go]: Hmm.. I would have imagined at least a textual difference. But if there is none, OK.

File: examples/examples_test.go (hunk 5 above)
Comment (krousey) [inline examples/examples_test.go]: If I run go vet in this directory, I get no errors.

File: hack/verify-govet.sh (hunk 7 above)
Comment (goltermann) [inline hack/verify-govet.sh]: fixed

File: hack/verify-govet.sh (hunk 6 above)
Comment (goltermann) [inline hack/verify-govet.sh]: fixed all

File: hack/verify-govet.sh [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+    targets+=("${arg}")
+  fi
+done
+
+if [[ ${#targets[@]} -eq 0 ]]; then
+  # Do not run on third_party directories.
+  targets=$(go list ./... | grep -v "third_party")
+fi
+
+# Do this in parallel; results in 5-10x speedup.
```
Comment (krousey) [inline hack/verify-govet.sh]: It also launches a lot of processes. What is the runtime? And is the speed up worth it?

Comment (goltermann) [inline hack/verify-govet.sh]: Locally - from ~71s to ~14s.

**Comment by krousey** [comment]
@goltermann I got that from the Jenkins unit/integration failure.

File: examples/examples_test.go (hunk 5 above)
Comment (krousey) [inline examples/examples_test.go]: Any update on this? I don't see this vet issue from my client.

Comment (goltermann) [inline examples/examples_test.go]: ah, you're right, no repro now

File: cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go (hunk 1 above)
Comment (lavalamp) [inline cmd/libs/go2idl/deepcopy-gen/generators/deepcopy.go]: The autogenerated stuff is run through gofmt.

File: cmd/libs/go2idl/import-boss/generators/import_restrict.go [hunk 9]
```diff
@@ -132,27 +131,6 @@ type importRuleFile struct{}
...
 	return nil
-
-	// If the file exists, populate its current imports. This is mostly to help
```
Comment (lavalamp) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: Oh, I'd actually like this code to not go away. Uh...

File: cmd/libs/go2idl/import-boss/generators/import_restrict.go (hunk 3 above)
Comment (lavalamp) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: No, it implements an interface.

File: examples/examples_test.go [hunk 10]
```diff
@@ -128,7 +128,7 @@ func validateObject(obj runtime.Object) (errors field.ErrorList) {
 		}
 		errors = expvalidation.ValidateDaemonSet(t)
 	default:
-		return field.ErrorList{field.InternalError(field.NewPath(""), fmt.Errorf("no validation defined for %#v", obj))}
+		return field.InternalError(field.NewPath(""), fmt.Errorf("no validation defined for %#v", obj))
```
Comment (krousey) [inline examples/examples_test.go]: You say no repro now, but this is different from what was there.

File: cmd/libs/go2idl/import-boss/generators/import_restrict.go (hunk 9 above)
Comment (krousey) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: Why? It's never used. Should it be?

Comment (lavalamp) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: Can you put it into a function?

```
// TODO: make a flag to enable this, or expose this information in some other way.
func (importRuleFile) listEntireImportTree(f *generator.File, path string) error {
```

Comment (lavalamp) [inline cmd/libs/go2idl/import-boss/generators/import_restrict.go]: This is useful if you want to see the list of imports that your rule will run against.

File: examples/examples_test.go (hunk 10 above)
Comment (goltermann) [inline examples/examples_test.go]: Oops, too many revisions going on.  I do see the vet error on my client:

$ head -131 examples/examples_test.go | tail -1
                return field.ErrorList{field.InternalError(field.NewPath(""), fmt.Errorf("no validation defined for %#v", obj))}

$ godep go vet ./examples/
godep: WARNING: Go version (go1.6) & $GO15VENDOREXPERIMENT= wants to enable the vendor experiment, but disabling because a Godep workspace (Godeps/_workspace) exists
examples/examples_test.go:131: field.ErrorList composite literal uses unkeyed fields
exit status 1
godep: go exit status 1

File: pkg/kubectl/cmd/cmd_test.go [hunk 11]
```diff
@@ -221,9 +221,12 @@ func NewTestFactory() (*cmdutil.Factory, *testFactory, runtime.Codec) {
 
 func NewMixedFactory(apiClient resource.RESTClient) (*cmdutil.Factory, *testFactory, runtime.Codec) {
 	f, t, c := NewTestFactory()
+	multiRESTMapper := meta.MultiRESTMapper{}
```
Comment (krousey) [inline pkg/kubectl/cmd/cmd_test.go]: This could just be `var multiRESTMapper meta.MultiRESTMapper` to prevent an empty slice allocation. Appending to a nil slice is fine.

File: pkg/kubectl/stop_test.go [hunk 12]
```diff
@@ -704,7 +704,7 @@ func TestSimpleStop(t *testing.T) {
 		}
 		actions := fake.Actions()
 		if len(test.actions) != len(actions) {
-			t.Errorf("unexpected actions: %v; expected %v (%s)", fake.Actions, test.actions, test.test)
+			t.Errorf("unexpected actions: %v; expected %v (%s)", fake.Actions(), test.actions, test.test)
```
Comment (krousey) [inline pkg/kubectl/stop_test.go]: maybe just use `actions` instead?

File: pkg/kubectl/cmd/cmd_test.go (hunk 11 above)
Comment (goltermann) [inline pkg/kubectl/cmd/cmd_test.go]: fixed

File: pkg/kubectl/stop_test.go (hunk 12 above)
Comment (goltermann) [inline pkg/kubectl/stop_test.go]: fixed

File: hack/verify-govet.sh [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+
+# Count and return the number of failed files (non-zero is a failed vet run).
+failedfiles=0
+for p in $pids; do
+  wait $p || let "failedfiles+=1"
+done
+
+# hardcode a healthy exit until all vet errors can be fixed
+#exit $failedfiles
+exit 0
```
Comment (goltermann) [inline hack/verify-govet.sh]: I can't keep up with the handful of vet errors that are added each day.  Let me get this PR in, then do one more clean up round.

Comment (krousey) [inline hack/verify-govet.sh]: Yea that sounds fair.
