### PR TITLE
Terminate restartable init containers ignoring not-started containers

### LINKED ISSUE #125880: Termination signals not sent to Native Sidecars when multiple Native Sidecars
### What happened?

In a situation where during the init phase of a `Pod`, a native sidecar never becomes ready (because its `startupProbe` is failing), then the `Pod` is terminated, if there are multiple startup containers, a termination signal is never received by the init container and the Pod is stuck (until `terminationGracePeriodSeconds` is hit).

### What did you expect to happen?

All running initContainer to receive the termination signal correctly.  

### How can we reproduce it (as minimally and precisely as possible)?

Create a `Dockerfile` with this bash script as an entrypoint:

```
#!/bin/bash
set -e 
trap 'echo "saw an exit signal"; sleep 5; exit' EXIT

while true; do
  echo "hello"
  sleep 1
done
```

Create a deployment with two init containers (one normal one sidecar).  Add an probe which means the startupProbe never passes

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: karl-test
  template:
    metadata:
      labels:
        app2: karl-test 
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: init-1
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'init container 1'"]
      - name: init-2
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      containers:
      - name: karl-test
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
```

Create the deployment, and it'll be stuck in Init, as you'd expect:

```
karl-test-deployment-c979948d8-xghf4   0/2     Init:1/2   0          5s
```

`kubectl delete` the pod and you'll see the exit signal has been sent to `init-2`:
```
hello
hello
hello
saw an exit signal
```

Delete the deployment / clean everything up.  Now, add a third `initContainer`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app2: karl-test
  template:
    metadata:
      labels:
        app2: karl-test 
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: init-1
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'init container 1'"]
      - name: init-2
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      - name: init-3
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
        restartPolicy: Always 
        startupProbe:                                                                                                                                                                                                          
          failureThreshold: 600 
          httpGet:
            path: /whatever
            port: 1234
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 3
      containers:
      - name: karl-test
        image: eu.gcr.io/at-artefacts/karl-test
        imagePullPolicy: IfNotPresent
```

As before, the `init` process will be stuck on `init-2` because of the bad probe:
```
karl-test-deployment-5c547f8f86-s8nqh   0/3     Init:1/3   0          1s
```

However when you delete the pod this time, no exit signal is sent to `init-2`, the pod is now stuck until `terminationGracePeriodSeconds` is reached.

### Anything else we need to know?

_No response_

### Kubernetes version

```
Client Version: v1.28.5
Server Version: v1.29.4-gke.1043002
```

### Cloud provider

GKE v1.29.4-gke.1043002

### OS version

Core OS on GCP

### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently, the restartable init container (native sidecar container) may not receive SIGTERM if the last restartable init container hasn't run.

This PR ensures that the restartable init containers receive a termination signal even if there are any not-started restartable init containers, by ignoring the not-running containers.

#### Which issue(s) this PR fixes:

Fixes #125880

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug that init containers with `Always` restartPolicy may not terminate gracefully if the pod hasn't initialized yet.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/container_lifecycle_test.go [hunk 1]
```diff
@@ -3115,6 +3115,106 @@ var _ = SIGDescribe(nodefeature.SidecarContainers, "Containers Lifecycle", func(
...
+
+		client := e2epod.NewPodClient(f)
+		pod = client.Create(ctx, pod)
+
+		err := e2epod.WaitForPodCondition(ctx, f.ClientSet, pod.Namespace, pod.Name, "the second init container is running", 2*time.Minute, func(pod *v1.Pod) (bool, error) {
+			if pod.Status.Phase != v1.PodPending {
+				return false, fmt.Errorf("pod should be in pending phase")
+			}
+			if len(pod.Status.InitContainerStatuses) < 2 {
+				return false, nil
```
Comment (toVersus) [inline test/e2e_node/container_lifecycle_test.go:3198]: From the first event, InitContainerStatuses will have three entries matching the number of initContainers, and they should all be in the `state.waiting.reason: PodInitializing` state. So, we might just need to check for something like the following here:

```suggestion
			if len(pod.Status.InitContainerStatuses) != 3 {
				return false, fmt.Errorf("pod should have the same number of statuses as init containers")
```

File: test/e2e_node/container_lifecycle_test.go [hunk 2]
```diff
@@ -3115,6 +3115,106 @@ var _ = SIGDescribe(nodefeature.SidecarContainers, "Containers Lifecycle", func(
...
+			}
+			containerStatus := pod.Status.InitContainerStatuses[1]
+			return containerStatus.State.Running != nil, nil
```
Comment (toVersus) [inline test/e2e_node/container_lifecycle_test.go:3201]: You might also want to check if the startup probe failed.

```suggestion
			return containerStatus.State.Running != nil && containerStatus.Ready == false, nil
```

File: test/e2e_node/container_lifecycle_test.go [hunk 3]
```diff
@@ -3115,6 +3115,106 @@ var _ = SIGDescribe(nodefeature.SidecarContainers, "Containers Lifecycle", func(
...
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Deleting the pod")
+		err = client.Delete(ctx, pod.Name, metav1.DeleteOptions{GracePeriodSeconds: &podTerminationGracePeriodSeconds})
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Waiting for the pod to terminate gracefully before its terminationGracePeriodSeconds")
+		err = e2epod.WaitForPodNotFoundInNamespace(ctx, f.ClientSet, pod.Name, pod.Namespace,
+			// The duration should be less than the pod's
+			// terminationGracePeriodSecondsadd while adding a buffer(60s) to
```
Comment (toVersus) [inline test/e2e_node/container_lifecycle_test.go:3212]:
```suggestion
			// terminationGracePeriodSeconds while adding a buffer(60s) to
```

File: test/e2e_node/container_lifecycle_test.go [hunk 4]
```diff
@@ -3115,6 +3115,106 @@ var _ = SIGDescribe(nodefeature.SidecarContainers, "Containers Lifecycle", func(
...
+			// the timeout duration to account for the time it takes to delete
+			// the pod.
+			time.Duration(containerTerminationSeconds+60)*time.Second)
```
Comment (toVersus) [inline test/e2e_node/container_lifecycle_test.go:3215]: When I first read the comment, I imagined the following timeout duration:

```suggestion
			time.Duration(podTerminationGracePeriodSeconds+60)*time.Second)
```

But, does it mean that adding a 60s buffer to the containerTerminationSeconds (1s) is enough for the Pod to be deleted? If so, the following comment may be clearer.

```go
			// The timeout duration should be less than the pod's
			// terminationGracePeriodSeconds while adding a buffer (60s) to
			// the container termination seconds (1s) to account for the time
			// it takes to delete the pod.
```

File: test/e2e_node/container_lifecycle_test.go [hunk 5]
```diff
@@ -3115,6 +3115,106 @@ var _ = SIGDescribe(nodefeature.SidecarContainers, "Containers Lifecycle", func(
...
+				},
+			},
+		}
+
+		preparePod(pod)
+
+		client := e2epod.NewPodClient(f)
+		pod = client.Create(ctx, pod)
+
+		err := e2epod.WaitForPodCondition(ctx, f.ClientSet, pod.Namespace, pod.Name, "the second init container is running", 2*time.Minute, func(pod *v1.Pod) (bool, error) {
```
Comment (toVersus) [inline test/e2e_node/container_lifecycle_test.go:3193]:
```suggestion
		err := e2epod.WaitForPodCondition(ctx, f.ClientSet, pod.Namespace, pod.Name, "the second init container is running but not ready", 2*time.Minute, func(pod *v1.Pod) (bool, error) {
```

File: test/e2e_node/container_lifecycle_test.go (hunk 4 above)
Comment (gjkim42) [reply test/e2e_node/container_lifecycle_test.go:3216]: > But, does it mean that adding a 60s buffer to the containerTerminationSeconds (1s) is enough for the Pod to be deleted?

yes, it does. fixed it.

File: pkg/kubelet/kuberuntime/kuberuntime_termination_order.go [hunk 6]
```diff
@@ -67,7 +68,14 @@ func newTerminationOrdering(pod *v1.Pod, runningContainerNames []string) *termin
 		// get the init containers in reverse order
 		ic := pod.Spec.InitContainers[len(pod.Spec.InitContainers)-i-1]
 
-		to.terminated[ic.Name] = make(chan struct{})
+		channel := make(chan struct{})
+		to.terminated[ic.Name] = channel
+
+		// if it's not a running container, pre-close the channel so nothing
+		// waits on it
+		if _, isRunning := runningContainers[ic.Name]; !isRunning {
```
Comment (matthyx) [inline pkg/kubelet/kuberuntime/kuberuntime_termination_order.go:76]: nice

**Review by matthyx — APPROVED** [review]
/lgtm

**Comment by Stono** [comment]
Hello, forgive my nativity in the release process for kubernetes!
Will this be back ported to 1.29?
I'm trying to work out when this will land on GKE vs working around it as we probably hit it a couple of times a week.  It's usually when a workload is rolling out but a pod also gets pre-empted

**Comment by matthyx** [comment]
> Hello, forgive my nativity in the release process for kubernetes! Will this be back ported to 1.29? I'm trying to work out when this will land on GKE vs working around it as we probably hit it a couple of times a week. It's usually when a workload is rolling out but a pod also gets pre-empted

for 1.30 it will probably be cherry-picked
for 1.29 there is little chance: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

**Comment by Stono** [comment]
OK thanks @matthyx - will look into a workaround then!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by matthyx** [comment]
we need a cherry pick for 1.29 and 1.30 here

**Comment by gjkim42** [comment]
> we need a cherry pick for 1.29 and 1.30 here

I'll make PRs for them.
