### PR TITLE
Skip memory pressure PSI test for CRI-O

### LINKED ISSUE #134141: Sig-node-cri-o Serial Tests Failing for Cgroupv2 on Fedora Coreos
### Which jobs are failing?

pr-node-kubelet-serial-crio-cgroupv2: [testgrid](https://testgrid.k8s.io/sig-node-cri-o#pr-node-kubelet-serial-crio-cgroupv2)
prowjob_name: `pull-kubernetes-node-kubelet-serial-crio-cgroupv2` 
prowjob_config_url: https://git.k8s.io/test-infra/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml

### Which tests are failing?

PSI Summary API test
pull-kubernetes-node-kubelet-serial-crio-cgroupv2 Overall

### Since when has it been failing?

since 9/05/2025 from what the testgrid shows, not sure how far back past that date.

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#pr-node-kubelet-serial-crio-cgroupv2

### Reason for failure (if possible)

From my conversation with @kannon92 : 
- this test is only failing on Fedora OS; it does not fail on Ubuntu or Containerd
- this could be a kernel or OS issue we are running into
- kubernetes-ci-logs artifacts: https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-serial-containerd/1968708022570061824/artifacts/

### Anything else we need to know?

Me and RedHat folks are looking into this! 

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Skip the memory pressure PSI test when running with CRI-O (used on Fedora CoreOS in test CI) until automatic memory.high configuration is available in the runtime.

The test fails on Fedora CoreOS due to different page cache reclaim behavior between kernels. In cgroup v2, memory.max is a hard limit that triggers OOM kills, while memory.high is a soft limit that triggers aggressive reclaim. Without memory.high configured, Fedora CoreOS doesn't reclaim page cache fast enough, causing instant OOM instead of sustained memory pressure.

CRI-O is implementing a fix to automatically set memory.high to 95% of memory.max for cgroup v2 containers, which will resolve this issue. Once that's available, this skip can be removed.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/134141

#### Special notes for your reviewer:

Testgrid: https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio

Related:
- CRI-O fix: https://github.com/cri-o/cri-o/pull/9714
- CoreOS tracker: https://github.com/coreos/fedora-coreos-tracker/issues/2094

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

File: test/e2e_node/summary_test.go [hunk 1]
```diff
@@ -367,7 +367,7 @@ var _ = SIGDescribe("Summary API", framework.WithNodeConformance(), func() {
 		})
 	})
 
-	framework.Context("when querying /stats/summary under pressure", framework.WithSerial(), framework.WithNodeConformance(), framework.WithFeatureGate(features.KubeletPSI), func() {
+	framework.Context("when querying /stats/summary under pressure", framework.WithSerial(), framework.WithNodeConformance(), framework.WithFeatureGate(features.KubeletPSI), framework.WithFeatureGate(features.MemoryQoS), func() {
```
Comment (saschagrunert) [inline test/e2e_node/summary_test.go]: The test is now skipped since the feature is not enabled by test-infra. We can enable it via https://github.com/kubernetes/test-infra/pull/36227

File: test/e2e_node/summary_test.go [hunk 2]
```diff
@@ -405,25 +405,62 @@ var _ = SIGDescribe("Summary API", framework.WithNodeConformance(), func() {
...
+					Requests: v1.ResourceList{
+						v1.ResourceMemory: resource.MustParse("200M"),
+					},
+				}
+				podSpec.ObjectMeta.Annotations = map[string]string{
+					// Set memory.high to 180MB (188743680 bytes = 180 * 1024 * 1024)
+					// Allocating 185MB exceeds memory.high, triggering reclaim and PSI metrics
+					// while staying safely below memory.max to avoid OOMkill.
+					"io.kubernetes.cri-o.UnifiedCgroup." + containerName: "memory.high=188743680",
+				}
```
Comment (saschagrunert) [inline test/e2e_node/summary_test.go]: Requires https://github.com/kubernetes/test-infra/pull/36234

**Comment by saschagrunert** [comment]
Alternative approach in CRI-O: https://github.com/cri-o/cri-o/pull/9714

**Comment by saschagrunert** [comment]
Green when skipping this single test https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136191/pull-kubernetes-node-kubelet-serial-crio/2012073451287744512

/hold 
for discussion

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

I am relying on CRI-O owners recommendation here
