### PR TITLE
Delete static pod gracefully and fix mirrorPodTerminationMap leak

### LINKED ISSUE #97722: Static pod should be updated by respecting terminationGracePeriodSeconds
**What happened**:
Let's say, I have a following sample static pod yaml,
<details>
<summary>Click to expand pod yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - args:
    - -c
    - trap "sleep inf" SIGINT SIGTERM SIGHUP &&  nc -k -l -p 4444
    command:
    - /bin/sh
    image: docker.io/library/busybox:latest
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - name: test
      containerPort: 4444
      hostPort: 4444
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
```
</details>

I want to simulate the pod update, so we will change the container image tag from `latest` to `1.33.0`  
<details>
<summary>Click to expand modified pod yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - args:
    - -c
    - trap "sleep inf" SIGINT SIGTERM SIGHUP &&  nc -k -l -p 4444
    command:
    - /bin/sh
    image: docker.io/library/busybox:1.33.0
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - name: test
      containerPort: 4444
      hostPort: 4444
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
```
</details>

When I replace the original pod yaml with the modified pod yaml in `/etc/kubernetes/manifests`, the original pod gets terminated and is replaced with the modified pod. 

But when the modified pod is coming up I see following errors in `pod describe` 

```bash
Events:
  Type     Reason                  Age                     From                                                                     Message
  ----     ------                  ----                    ----                                                                     -------
  Warning  FailedCreatePodSandBox  3m46s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(26989e9ffecc95d4f51a18f35c1600d927dde37ff4d6fd58df64604f1225b1fc): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m44s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(657a359cb276d5cbabddacddf63ced5e5ed048fbf89f4b6215745a0eea320037): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m41s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(6cfd5725fbb489b58d63d3da18b5e84239abccb24e32cffdd0707d51e46abdc0): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m40s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(92455c67bfccfe4b4e2eaddda734548c82763302497d4a6cdcb09aab7ab92183): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
```

This is happening because the original pod has `terminationGracePeriodSeconds` set to 60 seconds. So the original pod stays up for 60 seconds while the replace pod is also brought up causing the errors we see above. Ideally, the modified pod should not come up until the original pod is completely terminated. 

This behaviour is observed only with static pods. If I use the same pod yamls above to provision and update a regular pod I don't see any errors.

<details>
<summary> Click to see behaviour with regular pods </summary>

```bash
Events:
  Type    Reason          Age                  From                                                                     Message
  ----    ------          ----                 ----                                                                     -------
  Normal  Scheduled       <unknown>                                                                                     Successfully assigned default/test to testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal
  Normal  AddedInterface  2m47s                multus                                                                   Add eth0 [10.128.2.143/23]
  Normal  Pulled          2m46s                kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container image "docker.io/library/busybox:1.33.0" already present on machine
  Normal  Killing         2m26s                kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container test definition changed, will be restarted
  Normal  Created         86s (x2 over 2m46s)  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Created container test
  Normal  Started         86s (x2 over 2m46s)  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Started container test
  Normal  Pulled          86s                  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container image "docker.io/library/busybox:latest" already present on machine
```

</details>

**What you expected to happen**:
The static pod should be updated by respecting `terminationGracePeriodSeconds`

**How to reproduce it (as minimally and precisely as possible)**:
Take the original pod yaml and create the static pod. Then take the modified pod yaml to simulate the update. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by gjkim42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

- Delete static pod gracefully by adding a new static pod after checking if its mirror pod is pending termination.
- Fix mirrorPodTerminationMap leak

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/97722

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Static pods will be deleted gracefully.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @ehashman @rphillips @harche

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1765,6 +1769,9 @@ func (kl *Kubelet) deletePod(pod *v1.Pod) error {
 	}
 	podPair := kubecontainer.PodPair{APIPod: pod, RunningPod: &runningPod}
 
+	if _, ok := kl.podManager.GetMirrorPodByPod(pod); ok {
+		kl.podKiller.MarkMirrorPodPendingTermination(pod)
```
Comment (gjkim42) [inline pkg/kubelet/kubelet.go:1773]: For reviewer: ensure call podKiller.KillPod

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1765,6 +1769,9 @@ func (kl *Kubelet) deletePod(pod *v1.Pod) error {
...
+	}
 	kl.podKiller.KillPod(&podPair)
```
Comment (gjkim42) [inline pkg/kubelet/kubelet.go:1775]: For reviewer: ensure call podKiller.KillPod

**Comment by rphillips** [comment]
Nice! We will give this a test today or Monday.

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -2103,9 +2110,6 @@ func (kl *Kubelet) HandlePodRemoves(pods []*v1.Pod) {
 			kl.handleMirrorPod(pod, start)
 			continue
 		}
-		if _, ok := kl.podManager.GetMirrorPodByPod(pod); ok {
-			kl.podKiller.MarkMirrorPodPendingTermination(pod)
-		}
```
Comment (ehashman) [inline pkg/kubelet/kubelet.go:2108]: Ahh, I think I see what's happening here. This code never even gets executed because we'll hit the `continue` above before ever executing this.

My next question was "should this then go in `handleMirrorPod` instead?" but that code looks like it's in need of a refactor since 2015... https://github.com/kubernetes/kubernetes/issues/17251

**Review by ehashman — COMMENTED** [review]
I think this LGTM...

/assign @harche

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (gjkim42) [reply pkg/kubelet/kubelet.go:2108]: The problem I am pointing out is that this code was executed but the kl.deletePod below may return an error before executing podKiller.KillPod. And then we don't have a chance to delete the pending state from the podKiller.mirrorPodTerminationMap(a leak problem). What I fixed is ensuring to call the podKiller.KillPod.
https://github.com/kubernetes/kubernetes/blob/b6958b2b1bb2cdf9a7c1ef78f525a5305e455f54/pkg/kubelet/kubelet.go#L1738-L1772

**Comment by harche** [comment]
I verified this PR using the pods mentioned in https://github.com/kubernetes/kubernetes/issues/97722 and it this PR seems to be fixing the issue. I do not see `listen tcp4 :4444: bind: address already in use` when I update the static pod indicating the static pod was restarted by respecting `terminationGracePeriodSeconds`

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -1499,6 +1499,10 @@ func (kl *Kubelet) syncPod(o syncPodOptions) error {
 		return nil
 	}
 
+	if kl.podKiller.IsMirrorPodPendingTerminationByPodName(kubecontainer.GetPodFullName(pod)) {
```
Comment (sjenning) [inline pkg/kubelet/kubelet.go:1502]: Can you add a comment here on why we are doing this?  Something like:
```
If the pod is a static pod and is still gracefully terminating, we do not want to start the new static pod until the old static pod is gracefully terminated.
```
otherwise, lgtm

Comment (gjkim42) [reply pkg/kubelet/kubelet.go]: commented !
Thanks.

**Comment by ehashman** [comment]
/test pull-kubernetes-e2e-gce-100-performance

debian iptables flake

**Comment by rphillips** [comment]
doh! I forgot the bot is not setup for cherry picks.

**Comment by ehashman** [comment]
@rphillips should this also be pulled into 1.18? is it affected?

**Comment by hasheddan** [comment]
@rphillips echoing @ehashman's question here. I believe it is applicable to 1.18, but please correct me if I am incorrect.

**Comment by ehashman** [comment]
I will TAL
