### PR TITLE
Fix missing cadvisor machine metrics

### LINKED ISSUE #95204: Missing cadvisor machine metrics (v1.19)
**What happened**:
prometheus cadvisor machine metrics from kubelet are missing
```
# kubectl get --raw "/api/v1/nodes/NODE_NAME/proxy/metrics/cadvisor" | grep -i machine_cpu_cores
```

**What you expected to happen**:
```
# kubectl get --raw "/api/v1/nodes/NODE_NAME/proxy/metrics/cadvisor" | grep -i machine_cpu_cores
# HELP machine_cpu_cores Number of CPU cores on the machine.
# TYPE machine_cpu_cores gauge
machine_cpu_cores 4
```

**How to reproduce it (as minimally and precisely as possible)**:
install k8s 1.19, compare behavior to k8s <1.19

**Anything else we need to know?**:
Looks like missing call to `NewPrometheusMachineCollector` in `pkg/kubelet/server/server.go`, machine metrics collection was split out in cadvisor 0.37

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-29T20:53:06Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2+k3s1", GitCommit:"d38505b124c92bffd45f6e0654adb9371cae9610", GitTreeState:"clean", BuildDate:"2020-09-29T20:53:06Z", GoVersion:"go1.15.1", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fix missing cadvisor machine metrics.

From #95210 and [comment](https://github.com/kubernetes/kubernetes/pull/95210#issuecomment-726143798) since the author has not been active recently.

Should be backported to 1.19.

**Which issue(s) this PR fixes**:

Fixes #95204

**Special notes for your reviewer**:

1. Although the missing machine metrics data can now be provided normally, [its format has been changed](https://github.com/kubernetes/kubernetes/issues/95204#issuecomment-722929087)
2. According to [this comment](https://github.com/kubernetes/kubernetes/pull/95210#issuecomment-726143798), the timestamp is set to zero.

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a regression in 1.19+ missing cadvisor machine metrics.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -551,6 +551,7 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
 	if err != nil {
 		return nil, err
 	}
+	machineInfo.Timestamp = time.Time{}
```
Comment (dashpole) [inline pkg/kubelet/kubelet.go:554]: Just to refresh my memory, does this cause timestamps not to be set for metrics, or does it set the timestamp at 0?

**Review by dashpole — COMMENTED** [review]
lgtm

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (basvdlei) [reply pkg/kubelet/kubelet.go:554]: The collector will not include a timestamp because it is set to zero: https://github.com/google/cadvisor/blob/65fa5b44d3840d465a5c004a0f6722e0fd540137/metrics/prometheus_machine.go#L240

Comment (dashpole) [reply pkg/kubelet/kubelet.go:554]: makes sense.  A comment would be helpful for future readers.

Comment (lingsamuel) [reply pkg/kubelet/kubelet.go:556]: Added. Leaving this unresolved so others can find this.

**Comment by dashpole** [comment]
/lgtm
/priority critical-urgent
/kind bug

This is a regression from a previous version, so labeling it appropriately.

**Comment by lingsamuel** [comment]
Can someone approve this?

**Comment by ehashman** [comment]
ping @sjenning @mrunalp @derekwaynecarr -- serious metric regression that needs backporting ASAP

**Comment by abhi1git** [comment]
I am currently using Kubernetes **v1.19.1** and facing this missing **machine_*** metrics issue. Can I please get to know to which version I need to in which this issue is fixed.
TIA.

**Comment by ehashman** [comment]
Looks like this landed in 1.19.6: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1196
