### PR TITLE
fix the error when cleaning up finished jobs for cronjob

### LINKED ISSUE #103607: "Error Cleaning Up Jobs" From Cronjob, Which is Not Really an Error
#### What happened:

This started happening when we upgraded to Kubernetes 1.21. The following message occurs:

```
Jul 08 07:00:01        1 cronjob_controllerv2.go:193] "error cleaning up jobs" cronjob="default/vet-messenger-batch-prod-hourly" resourceVersion="160274892" err="Operation cannot be fulfilled on cronjobs.batch \"vet-messenger-batch-prod-hourly\": the object has been modified; please apply your changes to the latest version and try again"
Jul 08 07:00:01        1 cronjob_controllerv2.go:154] error syncing CronJobController default/vet-messenger-batch-prod-hourly, requeuing: Operation cannot be fulfilled on cronjobs.batch "vet-messenger-batch-prod-hourly": the object has been modified; please apply your changes to the latest version and try again
```

The Cronjob is pretty simple:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vet-messenger-batch-prod-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: vet-messenger-batch-prod
              image: REDACTED/vet-messenger:prod
              command: ["yarn", "batch:start:prod"]
              imagePullPolicy: Always
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: k8s-container-runner-prod
                      key: aws_access_key_id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: k8s-container-runner-prod
                      key: aws_secret_access_key
                - name: AWS_REGION
                  value: us-east-1
          restartPolicy: Never
      backoffLimit: 1
```

#### What you expected to happen:

No error.  But in fact, it does appear jobs ARE being removed properly regardless of the error message.  

#### How to reproduce it (as minimally and precisely as possible):

Use the above.

#### Anything else we need to know?:

We tried deleting and recreating the cronjob both with `kubectl create -f` and `kubectl apply -f` and neither seems to work. Note the API version was at batch/v1beta1 before we upgraded, and we did change it to batch/v1 to squelch the deprecation notice.

#### Environment:
- Kubernetes version (use `kubectl version`): 
```Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): From nodes (master is identical):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`): `Linux ip-10-92-217-104 5.4.0-1047-aws #49-Ubuntu SMP Wed Apr 28 22:47:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Kops
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by RyanAoh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Before this change, the updated cronjob is not recived and returned in function `syncCronJob`, as shown below: 
https://github.com/kubernetes/kubernetes/blob/eb729620c522753bc7ae61fc2c7b7ea19d4aad2f/pkg/controller/cronjob/cronjob_controllerv2.go#L603-L609
So, it will pass the cronjob object with old resource version to update its status when cleaning up the finished jobs, which results in an error with message "Operation cannot be fulfilled on cronjobs.batch 'xxxxx': the object has been modified; please apply your changes to the latest version and try again".
https://github.com/kubernetes/kubernetes/blob/eb729620c522753bc7ae61fc2c7b7ea19d4aad2f/pkg/controller/cronjob/cronjob_controllerv2.go#L185-L195

As for testing, I modified the integration test code of cronjob to catch this error through `runtime.ErrorHandlers`.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103607

#### Does this PR introduce a user-facing change?

```release-note
Fix regression in 1.21 cleaning up finished cronjobs
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 1]
```diff
@@ -600,13 +600,14 @@ func (jm *ControllerV2) syncCronJob(
 	}
 	cj.Status.Active = append(cj.Status.Active, *jobRef)
 	cj.Status.LastScheduleTime = &metav1.Time{Time: *scheduledTime}
-	if _, err := jm.cronJobControl.UpdateStatus(cj); err != nil {
+	updatedCJ, err = jm.cronJobControl.UpdateStatus(cj)
```
Comment (kerthcet) [inline pkg/controller/cronjob/cronjob_controllerv2.go:603]: I was confused as the `cj` is a `reference type`,  whether this  will happen? correct me if not.

Comment (RyanAoh) [reply pkg/controller/cronjob/cronjob_controllerv2.go:603]: It updates status by sending a http request to the apiserver, which doesn't change the value of `cj`.

Comment (kerthcet) [reply pkg/controller/cronjob/cronjob_controllerv2.go:603]: oh yeah, forgive me.

Comment (kerthcet) [reply pkg/controller/cronjob/cronjob_controllerv2.go:603]: another question, as the referred issue mentioned, with new created cronjob, this error will not occur. But if the root cause is what you said, I think this error will always happen, right?

Comment (RyanAoh) [reply pkg/controller/cronjob/cronjob_controllerv2.go:603]: Actually,  yes. I reproduced this in my cluster.

**Comment by johnSchnake** [comment]
Seems fine to me.

/lgtm

**Review by soltysh — APPROVED** [review]
/approve

**Comment by caleb15** [comment]
@RyanAoh @soltysh thanks for working on this! Looing forward to the next release :)
