### PR TITLE
Use gsutil to download kube binaries and release artifacts

### LINKED ISSUE #19386: Extract test step periodically failing
**What happened**:

The `Extract` test step is periodically failing across pipelines since 2020-09-11.

The extract step downloads binaries from https://storage.googleapis.com/kubernetes-release-dev/ci/fast/v1.xxxxxx using curl with a retry of 3. The download makes progress and then fails 3 times with: 

```
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

image

**What you expected to happen**:

I expect the download to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

Still flaking as of opening this.

**Please provide links to example occurrences, if any**:

[Timeline of aggregated failures](https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2020-09-23&text=error%20during%20.%2Fget-kube.sh%3A%20exit%20status%2056).

The following boards run this test (still more to add - will update):

* [Conformance - GCE - master](https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master&include-filter-by-regex=Extract&width=90)
* [gce-cos-master-alpha-features](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&include-filter-by-regex=Extract&width=90)
* [gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=Extract&width=90)
* [gce-cos-master-reboot](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-reboot&include-filter-by-regex=Extract&width=90)
* [gce-cos-master-scalability-100](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100&include-filter-by-regex=Extract&width=90)
* [gce-ubuntu-master-containerd](https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd&include-filter-by-regex=Extract&width=90)
* [gci-gce-ingress](https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress&include-filter-by-regex=Extract&width=90)
* [gce-cos-master-slow](https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-slow&include-filter-by-regex=Extract&width=90)
* [gce-cos-1.19-scalability-100](https://testgrid.k8s.io/sig-release-1.19-blocking#gce-cos-1.19-scalability-100&include-filter-by-regex=Extract&width=90)
* [gce-cos-k8sbeta-alphafeatures](https://testgrid.k8s.io/sig-release-1.19-blocking#gce-cos-k8sbeta-alphafeatures&include-filter-by-regex=Extract&width=90)

[Sample failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest/1310268563860230144).
[Sample log](https://gist.github.com/eddiezane/13a029d413b779f999b31ca89c8bee55).

**Anything else we need to know?**:

[curl command](https://github.com/kubernetes/kubernetes/blob/db9f1e91d977c45fe7df8e1e1bd415a3292995e1/cluster/get-kube-binaries.sh#L166).

Does not appear to be flaking on the windows pipelines.

Related to https://github.com/kubernetes/kubernetes/issues/95011

/cc @thejoycekung @RobertKielty @hasheddan @jeremyrickard

### PR DESCRIPTION
**Pull request by eddiezane**
**What type of PR is this?**

/kind cleanup
/kind flake

**What this PR does / why we need it**:

This PR defaults to using `gsutil` if available to download kube binaries and release artifacts inside of `cluster/get-kube.sh` and `cluster/get-kube-binaries.sh`.

This will hopefully resolve test flakes related to network instability when downloading with curl.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/test-infra/issues/19386

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/priority important-soon

Thanks @eddiezane! Did you get a chance to test this locally?

**Comment by eddiezane** [comment]
@hasheddan I tested the actual `gsutil` line locally inside `kubekins-e2e` but not the whole script.

File: cluster/get-kube-binaries.sh [hunk 1]
```diff
@@ -156,7 +156,10 @@ function download_tarball() {
   fi
   url="${DOWNLOAD_URL_PREFIX}/${file}"
   mkdir -p "${download_path}"
-  if [[ $(which curl) ]]; then
+
+  if [[ $(which gsutil) ]] && [[ "$url" =~ ^https://storage.googleapis.com.* ]]; then
```
Comment (eddiezane) [inline cluster/get-kube-binaries.sh:160]: Should these work with a `gs://` url as well?

**Comment by thejoycekung** [comment]
That UDP traffic/NodePort service failure is a known flake (#91236) so just gonna re-run it

/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
/retest
flake https://github.com/kubernetes/kubernetes/issues/95344

**Comment by eddiezane** [comment]
/test pull-kubernetes-node-e2e

Looks like the pod was oom killed. I'll try and dig in.

**Comment by eddiezane** [comment]
Opened https://github.com/kubernetes/test-infra/pull/19615 to try and address.
