### PR TITLE
fix auto upgraded preferDual-Stack services (in cluster upgrade)

### LINKED ISSUE #101681: Dual-stack updates w/ PreferDualStack changes IP assignments
1) start with a single stack cluster
2) create a PreferDualStack service
3) configure API server with a 2nd service CIDR
4) Confirm the above service is not dual-stack
5) Add a label to the above service
6) Observe that the service becomes dual-stack

I think the correct answer is to have a "repair loop" that upgrades (and downgrades!) PreferDualStack Services to match the config.

I think this is a GA blocker.

### PR DESCRIPTION
**Pull request by khenidak**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fixes #101681 replaces #101914

`PreferDualstack` services were automatically upgraded to dual-stack if:
1. They were created before the cluster was upgraded AND
2. user performed any update on them (e.g., updating labels).

This PR ensures that `preferDualstack` services are not upgraded automatically (nor downgraded)

#### Which issue(s) this PR fixes:
Fixes #101681

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?
```release-note
The current behavior for Services that `IPFamilyPolicy` set as `PreferDualstack`. The current behavior when the cluster is upgraded to dual-stack is:
- Services that have been set to IPFamilyPolicy = PreferDualstack will be upgraded when the service object is updated. e.g., when a user change a label.

This behavior will change to:
- Services that have been set  IPFamilyPolicy = PreferDualstack will not be upgraded when the service object is updated. User can still change policy, type etc and existing behaviors remain the same.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

File: pkg/registry/core/service/storage/rest.go [hunk 1]
```diff
@@ -846,9 +859,77 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
 	return rs.releaseClusterIPs(toRelease)
 }
 
+// tests if two prefered dual-stack service have matching ClusterIPFields
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:862]: the verify job is not happy with this :)
```
pkg/registry/core/service/storage/rest.go:862:16: "prefered" is a misspelling of "preferred"
```

File: pkg/registry/core/service/storage/rest.go [hunk 2]
```diff
@@ -846,9 +859,77 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
...
+	}
+
+	// both must be type == ClusterIP
+	if service.Spec.Type != api.ServiceTypeClusterIP {
+		return false
+	}
+
+	if oldService.Spec.Type != api.ServiceTypeClusterIP {
+		return false
+	}
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:880]: NodePort and LoadBalancer types does have ClusterIPs too, should this be?

"if Type in [ClusterIP, NodePort, Loadbalancer] && and sevice.Spec.ClusterIP is an IP address (avoid headless services with clusterip=None"

File: pkg/registry/core/service/storage/rest.go [hunk 3]
```diff
@@ -846,9 +859,77 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
...
+	match := true
+	for i, ip := range service.Spec.ClusterIPs {
+		if oldService.Spec.ClusterIPs[i] != ip {
+			match = false
+			break
+		}
+	}
+	if !match {
+		return false
+	}
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:905]:
```suggestion
	for i, ip := range service.Spec.ClusterIPs {
		if oldService.Spec.ClusterIPs[i] != ip {
			return false
		}
	}
```

File: pkg/registry/core/service/storage/rest.go [hunk 4]
```diff
@@ -846,9 +859,77 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
...
+	for i, family := range service.Spec.IPFamilies {
+		if oldService.Spec.IPFamilies[i] != family {
+			match = false
+			break
+		}
+	}
+
+	if !match {
+		return false
+	}
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:921]: another nit as in https://github.com/kubernetes/kubernetes/pull/102898/files#r652552160 , but no strong opinion if you feel this reads better

File: pkg/registry/core/service/storage/rest.go (hunk 2 above)
Comment (aojea) [reply pkg/registry/core/service/storage/rest.go:880]: I think that if you change the service type on purpose it makes sense to add/remove the ClusterIP, but not if you keep the same type (i.e, I add a label to a loadbalancer, nodeport or clusterIP service)

File: pkg/registry/core/service/storage/rest_test.go [hunk 5]
```diff
@@ -5086,6 +5087,109 @@ func TestDefaultingValidation(t *testing.T) {
...
+			svc: api.Service{
+				Spec: api.ServiceSpec{
+					Type:           api.ServiceTypeClusterIP,
+					ClusterIPs:     []string{"1.1.1.1", "2001::1"},
+					IPFamilies:     []api.IPFamily{api.IPv4Protocol, api.IPv6Protocol},
+					IPFamilyPolicy: &preferDualStack,
+				},
+			},
+			expectedIPFamilyPolicy: &preferDualStack,
+			expectedIPFamilies:     []api.IPFamily{api.IPv4Protocol, api.IPv6Protocol},
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest_test.go:5140]: The downgrade is the more complex thing, we end with a dual-stack service in a single stack cluster.
The funny thing is that I think that the IPv6 family may still work ... :)

Comment (khenidak) [reply pkg/registry/core/service/storage/rest_test.go:5140]: This is no different from changing service CIDR. services with allocated IP from wrong family will always be there until user fixes them.

Comment (aojea) [reply pkg/registry/core/service/storage/rest_test.go:5140]: are they not fixed by the repair loop?

for downgrade the problem seems that the repair loop will only run with the configured cluster cidr, leaving the second one as is ... but I'm talking from the top of my head, I didn't have time to check it

File: pkg/registry/core/service/storage/rest.go [hunk 6]
```diff
@@ -846,9 +859,72 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
...
+		service.Spec.Type != api.ServiceTypeLoadBalancer {
+		return false
+	}
+
+	if oldService.Spec.Type != api.ServiceTypeClusterIP &&
+		oldService.Spec.Type != api.ServiceTypeNodePort &&
+		oldService.Spec.Type != api.ServiceTypeLoadBalancer {
+		return false
+	}
+
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:885]: do we allow mutations on the type?
```
if oldService.Spec.Type != service.Spec.Type {
    return false
}
```

**Comment by aojea** [comment]
are the integration tests or at least some of them from https://github.com/kubernetes/kubernetes/pull/101914/commits/4b484a2c8765d5a68b05a9a906cee5b9f69b6ca0
still valid? I'll be more confident with them :smile: 

/assign @thockin

File: pkg/registry/core/service/storage/rest.go (hunk 6 above)
Comment (khenidak) [reply pkg/registry/core/service/storage/rest.go:890]: Yes we do. Thanks for catching this one.

**Comment by khenidak** [comment]
> are the integration tests or at least some of them from [4b484a2](https://github.com/kubernetes/kubernetes/commit/4b484a2c8765d5a68b05a9a906cee5b9f69b6ca0)
> still valid? I'll be more confident with them 😄
> 
> /assign @thockin

The thing about re-running api-server from integration test framework is that it is a hit or a miss. Sometimes it works, sometimes it just hangs. I am yet to look into it.

File: pkg/registry/core/service/storage/rest_test.go (hunk 5 above)
Comment (thockin) [reply pkg/registry/core/service/storage/rest_test.go:5140]: If we find IPs allocated outside the known CIDRs, what are we supposed to do?  We can't just change them (I think?) and we can't just delete them.  I think the root of the discussion is that changing CIDRs, especially deactivating them, needs to be carefully managed.

In this regard, your IP ranges change is superior - we can at least put a finalizer on it :)

Comment (khenidak) [reply pkg/registry/core/service/storage/rest_test.go:5140]: no fix. it will loop will generate an event for the user to fix. Which usually means delete/re-create due to immutability rules. Hence changing service-cidr is generally a bad idea.

Comment (thockin) [reply pkg/registry/core/service/storage/rest_test.go:5140]: Even if we allowed `clusterIPs[0]` to change, we could still end up with Services that should not be possible.  E.g.

* create a PreferDualStack, get v4
* upgrade to dual-stack cluster
* change to RequireDualStack, get v4,v6
* downgrade to single-stack

That Service is RequireDual.  We can't automatically change that to Prefer.   If you created a new service with that config it would be rejected.  With the finalizer, the CIDR it draws from would be stuck in delete-pending, so at least we know something is wrong.

File: pkg/registry/core/service/storage/rest_test.go [hunk 7]
```diff
@@ -5086,6 +5087,109 @@ func TestDefaultingValidation(t *testing.T) {
...
+			expectError:            false,
+		},
+
+		{
+			name:       "changed preferDualStack-1 (cluster upgraded)",
+			modifyRest: fnMakeDualStackStackIPv4IPv6Allocator,
+			oldSvc: &api.Service{
+				Spec: api.ServiceSpec{
+					Type:           api.ServiceTypeClusterIP,
+					ClusterIPs:     []string{"1.1.1.1"},
```
Comment (thockin) [inline pkg/registry/core/service/storage/rest_test.go:5150]: This is a weird setup - oldSvc is not really valid since it has 2 families but 1 IP?

**Review by thockin — COMMENTED** [review]
This is surprisingly straight-forward.  LGTM except one bit of test clarity

File: pkg/registry/core/service/storage/rest_test.go (hunk 5 above)
Comment (khenidak) [reply pkg/registry/core/service/storage/rest_test.go:5140]: Let us assume it is a single stack with ClusterIP outside the range (as in service-cidr has changed cluster wide). Today we let the repair loop deal with it (broadcasts an event) and user must delete and recreate it. Same applies for dual-stack. 

am i misunderstanding something?

Comment (aojea) [reply pkg/registry/core/service/storage/rest_test.go:5140]: if you move from dual to single, you will only run the repair in the single clusterIP cidr family, the existent secondary ClusterIPs  would not go through the repair loop, right?

Comment (khenidak) [reply pkg/registry/core/service/storage/rest_test.go:5140]: no, repair loop has been modified to work with IPs in `spec.ClusterIPs` as part of the dual stack work.

Comment (aojea) [reply pkg/registry/core/service/storage/rest_test.go:5140]: awesome , I see it now
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/registry/core/service/ipallocator/controller/repair.go#L221-L226

**Comment by aojea** [comment]
/retest
failed because lack of resources
```
 - The zone 'projects/k8s-infra-e2e-boskos-scale-27/zones/us-east1-b' does not have enough resources available to fulfill the request.  Try a different zone, or try again later.
```

**Comment by aojea** [comment]
I think we need release note explaining the behaviour on upgrade/downgrade

**Comment by aojea** [comment]
@khenidak I've adapted the test from your previous PR, do you think you can include it?
```diff
diff --git a/test/integration/dualstack/dualstack_test.go b/test/integration/dualstack/dualstack_test.go
index eeeba0219e6..4feacacf7fe 100644
--- a/test/integration/dualstack/dualstack_test.go
+++ b/test/integration/dualstack/dualstack_test.go
@@ -1479,3 +1479,190 @@ func validateServiceAndClusterIPFamily(svc *v1.Service, expectedIPFamilies []v1.
 
        return nil
 }
+
+func TestUpgradeServicePreferToDualStack(t *testing.T) {
+       // Create an IPv4 only dual stack control-plane
+       serviceCIDR := "192.168.0.0/24"
+       defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.IPv6DualStack, true)()
+
+       cfg := framework.NewIntegrationTestControlPlaneConfig()
+       _, cidr, err := net.ParseCIDR(serviceCIDR)
+       if err != nil {
+               t.Fatalf("bad cidr: %v", err)
+       }
+       cfg.ExtraConfig.ServiceIPRange = *cidr
+       _, s, closeFn := framework.RunAnAPIServer(cfg)
+
+       client := clientset.NewForConfigOrDie(&restclient.Config{Host: s.URL})
+
+       // Wait until the default "kubernetes" service is created.
+       if err = wait.Poll(250*time.Millisecond, time.Minute, func() (bool, error) {
+               _, err := client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), "kubernetes", metav1.GetOptions{})
+               if err != nil && !apierrors.IsNotFound(err) {
+                       return false, err
+               }
+               return !apierrors.IsNotFound(err), nil
+       }); err != nil {
+               t.Fatalf("creating kubernetes service timed out")
+       }
+
+       preferDualStack := v1.IPFamilyPolicyPreferDualStack
+       svc := &v1.Service{
+               ObjectMeta: metav1.ObjectMeta{
+                       Name: "svc-prefer-dual",
+               },
+               Spec: v1.ServiceSpec{
+                       Type:           v1.ServiceTypeClusterIP,
+                       ClusterIPs:     nil,
+                       IPFamilies:     nil,
+                       IPFamilyPolicy: &preferDualStack,
+                       Ports: []v1.ServicePort{
+                               {
+                                       Name:       "svc-port-1",
+                                       Port:       443,
+                                       TargetPort: intstr.IntOrString{IntVal: 443},
+                                       Protocol:   "TCP",
+                               },
+                       },
+               },
+       }
+
+       // create the service
+       _, err = client.CoreV1().Services(metav1.NamespaceDefault).Create(context.TODO(), svc, metav1.CreateOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error: %v", err)
+       }
+       // validate the service was created correctly if it was not expected to fail
+       svc, err = client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), svc.Name, metav1.GetOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error to get the service %s %v", svc.Name, err)
+       }
+       if err := validateServiceAndClusterIPFamily(svc, []v1.IPFamily{v1.IPv4Protocol}); err != nil {
+               t.Fatalf("Unexpected error validating the service %s %v", svc.Name, err)
+       }
+
+       // reconfigure the apiserver to be dual-stack
+       closeFn()
+
+       secondaryServiceCIDR := "2001:db8:1::/48"
+       _, secCidr, err := net.ParseCIDR(secondaryServiceCIDR)
+       if err != nil {
+               t.Fatalf("bad cidr: %v", err)
+       }
+       cfg.ExtraConfig.SecondaryServiceIPRange = *secCidr
+       _, s, closeFn = framework.RunAnAPIServer(cfg)
+       defer closeFn()
+
+       client = clientset.NewForConfigOrDie(&restclient.Config{Host: s.URL})
+
+       // Wait until the default "kubernetes" service is created.
+       if err = wait.Poll(250*time.Millisecond, time.Minute, func() (bool, error) {
+               _, err := client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), "kubernetes", metav1.GetOptions{})
+               if err != nil && !apierrors.IsNotFound(err) {
+                       return false, err
+               }
+               return !apierrors.IsNotFound(err), nil
+       }); err != nil {
+               t.Fatalf("creating kubernetes service timed out")
+       }
+       // validate the service was created correctly if it was not expected to fail
+       svc, err = client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), svc.Name, metav1.GetOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error to get the service %s %v", svc.Name, err)
+       }
+       // service should remain single stack
+       if err = validateServiceAndClusterIPFamily(svc, []v1.IPFamily{v1.IPv4Protocol}); err != nil {
+               t.Fatalf("Unexpected error validating the service %s %v", svc.Name, err)
+       }
+}
+
+func TestDowngradeServicePreferToDualStack(t *testing.T) {
+       // Create a dual stack control-plane
+       serviceCIDR := "192.168.0.0/24"
+       secondaryServiceCIDR := "2001:db8:1::/48"
+       defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.IPv6DualStack, true)()
+       dualStackCfg := framework.NewIntegrationTestControlPlaneConfig()
+       _, cidr, err := net.ParseCIDR(serviceCIDR)
+       if err != nil {
+               t.Fatalf("bad cidr: %v", err)
+       }
+       dualStackCfg.ExtraConfig.ServiceIPRange = *cidr
+       _, secCidr, err := net.ParseCIDR(secondaryServiceCIDR)
+       if err != nil {
+               t.Fatalf("bad cidr: %v", err)
+       }
+       dualStackCfg.ExtraConfig.SecondaryServiceIPRange = *secCidr
+       _, s, closeFn := framework.RunAnAPIServer(dualStackCfg)
+       client := clientset.NewForConfigOrDie(&restclient.Config{Host: s.URL})
+       // Wait until the default "kubernetes" service is created.
+       if err = wait.Poll(250*time.Millisecond, time.Minute, func() (bool, error) {
+               _, err := client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), "kubernetes", metav1.GetOptions{})
+               if err != nil && !apierrors.IsNotFound(err) {
+                       return false, err
+               }
+               return !apierrors.IsNotFound(err), nil
+       }); err != nil {
+               t.Fatalf("creating kubernetes service timed out")
+       }
+       preferDualStack := v1.IPFamilyPolicyPreferDualStack
+       svc := &v1.Service{
+               ObjectMeta: metav1.ObjectMeta{
+                       Name: "svc-prefer-dual01",
+               },
+               Spec: v1.ServiceSpec{
+                       Type:           v1.ServiceTypeClusterIP,
+                       ClusterIPs:     nil,
+                       IPFamilies:     nil,
+                       IPFamilyPolicy: &preferDualStack,
+                       Ports: []v1.ServicePort{
+                               {
+                                       Name:       "svc-port-1",
+                                       Port:       443,
+                                       TargetPort: intstr.IntOrString{IntVal: 443},
+                                       Protocol:   "TCP",
+                               },
+                       },
+               },
+       }
+       // create the service
+       _, err = client.CoreV1().Services(metav1.NamespaceDefault).Create(context.TODO(), svc, metav1.CreateOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error: %v", err)
+       }
+       // validate the service was created correctly if it was not expected to fail
+       svc, err = client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), svc.Name, metav1.GetOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error to get the service %s %v", svc.Name, err)
+       }
+       if err := validateServiceAndClusterIPFamily(svc, []v1.IPFamily{v1.IPv4Protocol, v1.IPv6Protocol}); err != nil {
+               t.Fatalf("Unexpected error validating the service %s %v", svc.Name, err)
+       }
+       // reconfigure the apiserver to be sinlge stack
+       closeFn()
+       // reset secondary
+       var emptyCidr net.IPNet
+       dualStackCfg.ExtraConfig.SecondaryServiceIPRange = emptyCidr
+
+       _, s, closeFn = framework.RunAnAPIServer(dualStackCfg)
+       defer closeFn()
+       client = clientset.NewForConfigOrDie(&restclient.Config{Host: s.URL})
+       // Wait until the default "kubernetes" service is created.
+       if err = wait.Poll(250*time.Millisecond, time.Minute, func() (bool, error) {
+               _, err := client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), "kubernetes", metav1.GetOptions{})
+               if err != nil && !apierrors.IsNotFound(err) {
+                       return false, err
+               }
+               return !apierrors.IsNotFound(err), nil
+       }); err != nil {
+               t.Fatalf("creating kubernetes service timed out")
+       }
+       // validate the service is still there.
+       svc, err = client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), svc.Name, metav1.GetOptions{})
+       if err != nil {
+               t.Fatalf("Unexpected error to get the service %s %v", svc.Name, err)
+       }
+       // service should be single stack
+       if err = validateServiceAndClusterIPFamily(svc, []v1.IPFamily{v1.IPv4Protocol, v1.IPv6Protocol}); err != nil {
+               t.Fatalf("Unexpected error validating the service %s %v", svc.Name, err)
+       }
+}
```

File: pkg/registry/core/service/storage/rest.go [hunk 8]
```diff
@@ -846,9 +859,77 @@ func (rs *REST) releaseServiceClusterIPs(service *api.Service) (released map[api
...
+		service.Spec.Type != api.ServiceTypeNodePort &&
+		service.Spec.Type != api.ServiceTypeLoadBalancer {
+		return false
+	}
+
+	if oldService.Spec.Type != api.ServiceTypeClusterIP &&
+		oldService.Spec.Type != api.ServiceTypeNodePort &&
+		oldService.Spec.Type != api.ServiceTypeLoadBalancer {
+		return false
+	}
```
Comment (aojea) [inline pkg/registry/core/service/storage/rest.go:889]: this is a nit, but one of this is redundant since we check that `oldService.Spec.Type == service.Spec.Type`

**Comment by khenidak** [comment]
this hangs when i run it. if it is just my setup then I will try to push it and see.

> @khenidak I've adapted the test from your previous PR, do you think you can include it?
> 
> ```diff
> diff --git a/test/integration/dualstack/dualstack_test.go b/test/integration/dualstack/dualstack_test.go
> index eeeba0219e6..4feacacf7fe 100644
> ...

**Comment by aojea** [comment]
> this hangs when i run it. if it is just my setup then I will try to push it and see.
> 
> > @khenidak I've adapted the test from your previous PR, do you think you can include it?
> > ```diff
> > diff --git a/test/integration/dualstack/dualstack_test.go b/test/integration/dualstack/dualstack_test.go
> > index eeeba0219e6..4feacacf7fe 100644
> > ...
> > ```

have you rebased over master, there were some changes on the integration framework , that is one of the reasons I had to adapt it :)

File: pkg/registry/core/service/storage/rest.go (hunk 8 above)
Comment (khenidak) [reply pkg/registry/core/service/storage/rest.go:889]: the first if statement 
```golang
 875   if oldService.Spec.Type != service.Spec.Type {                                                                                  
 876     return false                                                                                                                   
 877   }
```
validates that type has changed, if it is then it should go through the process of alloc/release as needed. the following if statements check if old/new is in fact something that we need we need to alloc/release for.

**Comment by khenidak** [comment]
@aojea  added your tests.. let us see how it goes.

File: test/integration/dualstack/dualstack_test.go [hunk 9]
```diff
@@ -1479,3 +1479,190 @@ func validateServiceAndClusterIPFamily(svc *v1.Service, expectedIPFamilies []v1.
...
+		return !apierrors.IsNotFound(err), nil
+	}); err != nil {
+		t.Fatalf("creating kubernetes service timed out")
+	}
+	// validate the service is still there.
+	svc, err = client.CoreV1().Services(metav1.NamespaceDefault).Get(context.TODO(), svc.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("Unexpected error to get the service %s %v", svc.Name, err)
+	}
+	// service should be single stack
```
Comment (aojea) [inline test/integration/dualstack/dualstack_test.go:1664]: this is my fault, the comment is wrong, 
```suggestion
	// service should remain dual stack
```

Comment (thockin) [reply test/integration/dualstack/dualstack_test.go:1664]: yep

**Comment by thockin** [comment]
Other than Antonio's 1 comment nit, I am good with this

/approve

File: pkg/registry/core/service/storage/rest.go (hunk 8 above)
Comment (dcbw) [reply pkg/registry/core/service/storage/rest.go:889]: @khenidak I think what Antonio is saying is, if we already know that service.Spec.Type == oldService.Spec.Type (because line 875) and then we just ensured that service.Spec.Type is OK, why do we need to check that oldService.Spec.Type is OK? we just checked that (by equivalence to service.Spec.Type) in line 879, right?

**Comment by dcbw** [comment]
/approve
Same as Tim, some nits but good to go. I'll register my approval too :)

**Comment by thockin** [comment]
woops, I assumed we were waiting for the comment fix - @khenidak or @aojea can you please followup?

**Comment by aojea** [comment]
> woops, I assumed we were waiting for the comment fix - @khenidak or @aojea can you please followup?

done https://github.com/kubernetes/kubernetes/pull/103220
