### PR TITLE
Fix dumping docker images log

### LINKED ISSUE #88011: Dump list of test containers on Windows test nodes
When a test run completes it would be useful to have a list of all the test containers that were pulled onto the node - see https://github.com/kubernetes-sigs/windows-testing/pull/126#discussion_r377413135 for the motivation. Let's add a call to `docker image list` at https://github.com/kubernetes/kubernetes/blob/master/cluster/log-dump/log-dump.sh#L249 - just after `export-windows-docker-event-log` seems like it should work fine. We can dump the output to a file and gather it from each node just like we do for docker.log.

### PR DESCRIPTION
**Pull request by YangLu1031**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Added the function to dump docker image list after e2e test job to provide container images info for prepulling, but missed collecting the log file.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/88011

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cluster/log-dump/log-dump.sh [hunk 1]
```diff
@@ -54,7 +54,7 @@ readonly systemd_services="kubelet kubelet-monitor kube-container-runtime-monito
 readonly extra_log_files="${LOG_DUMP_EXTRA_FILES:-}"
 readonly dump_systemd_journal="${LOG_DUMP_SYSTEMD_JOURNAL:-false}"
 # Log files found in WINDOWS_LOGS_DIR on Windows nodes:
-readonly windows_node_logfiles="kubelet.log kube-proxy.log docker.log"
+readonly windows_node_logfiles="kubelet.log kube-proxy.log docker.log docker_images.log"
```
Comment (mm4tt) [inline cluster/log-dump/log-dump.sh]: QQ, do we use logexporter for dumping logs from windows nodes or only ssh?

Comment (YangLu1031) [reply cluster/log-dump/log-dump.sh]: Only ssh, as we don't have a good logexporter for windows yet.

Comment (mm4tt) [reply cluster/log-dump/log-dump.sh]: SG, thanks for explaining!

**Review by mm4tt — COMMENTED** [review]
/lgtm
/approve
