### PR TITLE
Skip safe to detach check if node API object no longer exists

### LINKED ISSUE #29358: GCE PD Detach fails if node no longer exists
**Problem:**

If a node with a GCE PD attached is deleted (before the volume is detached), subsequent attempts by the attach/detach controller to detach it continuously fail, and prevent the controller from attaching the volume to another node.

**Repro steps:**

1. Create a pod referencing a GCE PD
2. Wait for pod to get scheduled and running.
3. Delete the node VM (using gcloud) that the pod is scheduled to.
4. Check if volume is detached by attach/detach controller:
  * *Expected:* Volume detached.
  * *Actual:* Volume continuously fails detach.

**Logs:**
<details>
From `/var/log/kube-controller-manager.log`:
```
I0721 03:21:43.464087       7 reconciler.go:134] Started DetachVolume for volume "X" from node "Y" due to maxWaitForUnmountDuration expiry.
E0721 03:21:43.591941       7 gce.go:2580] getInstanceByName/single-zone: failed to get instance Y; err: googleapi: Error 404: The resource 'projects/[project]/zones/[zone]/instances/Y' was not found, notFound
E0721 03:21:43.591985       7 attacher.go:215] Error checking if PD ("[pdname]") is already attached to current node ("Y"). Will continue and try detach anyway. err=instance not found
E0721 03:21:43.698786       7 gce.go:2580] getInstanceByName/single-zone: failed to get instance Y; err: googleapi: Error 404: The resource 'projects/[project]/zones/[zone]/instances/Y' was not found, notFound
E0721 03:21:43.698828       7 attacher.go:225] Error detaching PD "[pdname]" from node "Y": error getting instance "Y"
```
</details>

**Workarounds:**

* Restart the kube-controller-manager binary on the master.

-or-

* Recreate a node with the same name.

**Proposed Fix:**

If GCE PD detach fails with `instance not found`, assume successful detach.

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #29358

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30737)

### CODE REVIEW

**Comment by matchstick** [comment]
👍

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 1]
```diff
@@ -607,6 +578,54 @@ func (oe *operationExecutor) generateDetachVolumeFunc(
...
+	volumeToDetach AttachedVolume) error {
+	// Fetch current node object
+	node, fetchErr := oe.kubeClient.Core().Nodes().Get(volumeToDetach.NodeName)
+	if fetchErr != nil {
+		if errors.IsNotFound(fetchErr) {
+			glog.Warningf("Node %q not found on API server. DetachVolume will skip safe to detach check.",
+				volumeToDetach.NodeName,
+				volumeToDetach.VolumeName,
+				volumeToDetach.VolumeSpec.Name())
+			return nil
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_executor.go]: By returning nil here, it can unblock DetachVolume in operation_executor. But from our current workflow, it is not clear to me how DetachVolume can block AttachVolume. No matter detach fails or not, reconciler will try to attach the volume through gce service. The following cases might happen
1. If the volume is still attached by another node, attach will fail. 
2. If the node to which the volume is originally attached is deleted, attach will succeed (I think no matter detach failed or not)
3. If the node to which the volume is originally attached is removed from API server (by kubectl delete), attach failed at first but succeed eventually    because volume is detached after timeout (waiting for unmount status update).
So it is not clear to me that in the issue #29903, during upgrading, if the old node is deleted, the following attach to the new node should succeed. (from the kubelet log I checked, kubelet verifyVolumeAttached succeed because the volume is in the attached list of the new node), but failed on checking the devicePath before trying to mount volume.

So I just want to make sure we cover all the cases.

Comment (saad-ali) [inline pkg/volume/util/operationexecutor/operation_executor.go]: > By returning nil here, it can unblock DetachVolume in operation_executor. 

Returning nil will not block the operation_executor, returning an error will.

> 1. If the volume is still attached by another node, attach will fail. 

Correct.

> 2. If the node to which the volume is originally attached is removed from API server (by kubectl delete), attach failed at first but succeed eventually because volume is detached after timeout (waiting for unmount status update). In this case verifySafeToDetach is set to false

Detach from the original node would fail because of the bug this PR is fixing. After this PR, what you stated will be correct.

> 3. If the node to which the volume is originally attached is deleted (by gcloud command), attach will succeed? I am not quite sure in this situation verifySafeToDetach is set to true or false in reconciler.

Yes, volume will be detached thanks to PR #29485, and be ok to reattach to another node.

> 4. If the previous operation on the volume failed, it will block on backoff

Not sure what you mean here.

> So it is not clear to me that in the issue #29903, during node upgrading, if the old node is deleted, the following attach to the new node should succeed. Also from the kubelet log I checked, kubelet verifyVolumeAttached succeed because the volume is in the attached list of the new node, but failed on checking the devicePath before trying to mount volume. I am thinking there might be some race condition issue in the attachdetach controller

The issue was that when the cluster is updated the old machine is deleted/removed from API server. Then the master would 1) unable to correctly update the list of attached volumes and 2) not be able to detach the volume with the node obj missing from the API server. This PR fixes those bugs.

**Comment by saad-ali** [comment]
@k8s-bot e2e test this issue: #27524

**Comment by jingxu97** [comment]
The PR LGTM, but I am not very sure about the logic of setting verifySafeToDetach. In what situation we should verify and what situation we don't need to. But we can discuss in different thread.

**Comment by saad-ali** [comment]
> The PR LGTM, but I am not very sure about the logic of setting verifySafeToDetach. In what situation we should verify and what situation we don't need to. But we can discuss in different thread.

Yes, we can follow up offline. Adding LGTM label to get this merged

**Comment by fabioy** [comment]
@saad-ali Given the comment above, do you still want to cherrypick this PR? Or should I wait?

**Comment by saad-ali** [comment]
Yes, this PR fixes an existing issue and needs to be cherry picked (I'll prepare one). We'll debug and triage any other issues that we discover independent of this.
