### PR TITLE
check server version at correct point in e2e flow

### LINKED ISSUE #60769: [test failed] [1.10 upgrade] Proxy version v1
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig network
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus
/assign @thockin @dcbw @caseydavenport

### PR DESCRIPTION
**Pull request by liggitt**
in ginkgo, skip check needed to be done inside the `It("...", func(){ ... })` blocks

fixes #60769 for real this time

### CODE REVIEW

File: test/e2e/network/proxy.go [hunk 1]
```diff
@@ -77,19 +77,30 @@ var _ = SIGDescribe("Proxy", func() {
 			    Description: Ensure that proxy on node logs works with generic top
 				level prefix proxy and explicit kubelet port.
 		*/
-		if !skipPrefixProxyTests {
-			framework.ConformanceIt("should proxy logs on node with explicit kubelet port ", func() { nodeProxyTest(f, prefix+"/proxy/nodes/", ":10250/logs/") })
-		}
+		framework.ConformanceIt("should proxy logs on node with explicit kubelet port ", func() {
+			if skipPrefixProxyTests {
```
Comment (liggitt) [inline test/e2e/network/proxy.go]: the value is set in BeforeEach, so is only valid to check inside the It() blocks

**Comment by dims** [comment]
LGTM 👍

**Comment by cblecker** [comment]
This pattern looks good, and is used in many other places in the e2e tests.

/lgtm
/approve
