### PR TITLE
kubelet(dra): fix handling of multiple ResourceClaims when one is already prepared

### LINKED ISSUE #135901: Kubelet cannot handle multiple ResourceClaims if one is already prepared
### What happened?

When using Dynamic Resource Allocation (DRA) with ResourceClaims, kubelet fails with:

    Error: internal error: unable to get claim info for ResourceClaim <name>

The error occurs when:
1. A first pod is created that references a single ResourceClaim.
2. A second pod is created that references the same ResourceClaim plus an additional one.

The failure happens during container creation, after scheduling succeeded.

The issue is reproducible using the dra-example-driver from kubernetes-sigs.

Potential spots where log may occurs:
https://github.com/kubernetes/kubernetes/blob/release-1.34/pkg/kubelet/cm/dra/manager.go#L417
https://github.com/kubernetes/kubernetes/blob/release-1.34/pkg/kubelet/cm/dra/manager.go#L442
https://github.com/kubernetes/kubernetes/blob/release-1.34/pkg/kubelet/cm/dra/manager.go#L498

### What did you expect to happen?

The second pod should successfully start with both ResourceClaims prepared.

Notably, the same set of ResourceClaims works correctly when requested in the opposite order:
- When the first pod uses both ResourceClaims, and the second pod uses only one - Works ✅ 
- When the first pod uses one ResourceClaim, and the second pod then uses both - Not working 🔴 

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy the dra-example-driver:
   https://github.com/kubernetes-sigs/dra-example-driver

2. Create two ResourceClaims:
```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: first-resource-claim
spec:
  devices:
    requests:
    - name: request
      exactly:
        deviceClassName: gpu.example.com
        allocationMode: ExactCount
        count: 1
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: second-resource-claim
spec:
  devices:
    requests:
    - name: request
      exactly:
        deviceClassName: gpu.example.com
        allocationMode: ExactCount
        count: 1
```

3. Create a first pod that references only the first ResourceClaim:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep", "infinity"]
    resources:
      claims:
      - name: first
  resourceClaims:
  - name: first
    resourceClaimName: first-resource-claim
  restartPolicy: Never
```

4. Wait until the pod is running.
5. Create a second pod that references both ResourceClaims:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
spec:
  containers:
  - name: container
    image: busybox
    command: ["sleep", "infinity"]
    resources:
      claims:
      - name: first
      - name: second
  resourceClaims:
  - name: first
    resourceClaimName: first-resource-claim
  - name: second
    resourceClaimName: second-resource-claim
  restartPolicy: Never
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Version: v1.34.1+k3s1
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ uname -a
Linux 6.11.0-17-generic #17~24.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 20 22:48:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by rogowski-piotr**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes an issue in the kubelet DRA (Dynamic Resource Allocation) manager where preparing multiple ResourceClaims fails if one of the claims is already prepared.  
Previously, if a claim was already prepared, the loop would exit early, causing subsequent claims not to be prepared.  
Now, the kubelet continues preparing remaining claims even if some claims are already prepared.

#### Which issue(s) this PR is related to:
Fixes #135901

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?
```release-note
kubelet(dra): correctly handles multiple ResourceClaims even if one is already prepared
```

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
Can you add test cases for this?

/assign @bart0sh

**Comment by bart0sh** [comment]
@rogowski-piotr Thank you for the fix! Can you add a node e2e test for this use case?

File: test/e2e/dra/dra.go [hunk 1]
```diff
@@ -1071,6 +1071,61 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
...
+			b.Create(ctx, firstClaim, secondClaim)
+
+			// First pod uses only firstClaim
+			firstPod := b.PodExternal()
+			b.Create(ctx, firstPod)
+			b.TestPod(ctx, f, firstPod)
+
+			// Second pod uses firstClaim (already prepared) + secondClaim (new)
+			secondPod := firstPod.DeepCopy()
+			secondPod.Name = "second-pod"
```
Comment (bart0sh) [inline test/e2e/dra/dra.go]:
```suggestion
			secondPod := b.PodExternal()
```

File: test/e2e/dra/dra.go [hunk 2]
```diff
@@ -1071,6 +1071,61 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
...
+		expectedEnv := []string{"admin_x", "y"}
+		_, expected := b.ParametersEnv()
+		expectedEnv = append(expectedEnv, expected...)
+
+		ginkgo.It("requests an already allocated and a new claim for a pod", func(ctx context.Context) {
+			// This test covers a situation when a pod references a mix of already-prepared and new claims.
+			firstClaim := b.ExternalClaim()
+
+			secondClaim := firstClaim.DeepCopy()
+			secondClaim.Name = "second-external-claim" + driver.NameSuffix
```
Comment (bart0sh) [inline test/e2e/dra/dra.go]:
```suggestion
			secondClaim := b.ExternalClaim()
```

File: test/e2e/dra/dra.go [hunk 3]
```diff
@@ -1071,21 +1071,55 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
 				return f.ClientSet.ResourceV1().ResourceClaims(f.Namespace.Name).Get(ctx, claim.Name, metav1.GetOptions{})
 			}).WithTimeout(f.Timeouts.PodDelete).Should(gomega.HaveField("Status.Allocation", (*resourceapi.AllocationResult)(nil)))
 		})
+	}
 
-		if withKubelet {
-			// Serial because the example device plugin can only be deployed with one instance at a time.
-			f.It("supports extended resources together with ResourceClaim", f.WithSerial(), func(ctx context.Context) {
```
Comment (bart0sh) [inline test/e2e/dra/dra.go:1086]: why this is deleted? It looks like a part of another test to me.

File: test/e2e/dra/dra.go [hunk 4]
```diff
@@ -1071,21 +1071,55 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
...
 
-				pod := b.PodExternal()
-				resources := v1.ResourceList{extendedResourceName: resource.MustParse("1")}
-				pod.Spec.Containers[0].Resources.Requests = resources
-				pod.Spec.Containers[0].Resources.Limits = resources
-				claim := b.ExternalClaim()
-				b.Create(ctx, claim, pod)
-				b.TestPod(ctx, f, pod)
-			})
-		}
```
Comment (bart0sh) [inline test/e2e/dra/dra.go:1098]: the same here.

File: test/e2e/dra/dra.go (hunk 3 above)
Comment (rogowski-piotr) [reply test/e2e/dra/dra.go:1086]: yes you are right, I accidentally deleted it but already restored.

File: test/e2e/dra/dra.go (hunk 2 above)
Comment (rogowski-piotr) [reply test/e2e/dra/dra.go]: Thanks, fixed

File: test/e2e/dra/dra.go (hunk 1 above)
Comment (rogowski-piotr) [reply test/e2e/dra/dra.go]: Thanks, fixed

**Comment by rogowski-piotr** [comment]
Ok the only remaining failure is `pull-kubernetes-kind-dra-n-1`, which I think is expected.
@bart0sh Please let me know if there is anything else you’d like me to change.

**Comment by rogowski-piotr** [comment]
> > I might be misunderstanding the intent of pull-kubernetes-kind-dra-n-1. Is this job validating behavior on Kubernetes version N-1? If so, the failure is expected since this PR fixes a bug in the current Kubernetes version (N) and the behavior on N-1 remains unchanged right?
> 
> According to the job description "Runs E2E tests for Dynamic Resource Allocation beta features against a Kubernetes master cluster created with sigs.k8s.io/kind with kubelet from the "current - 1" release." you may be right. However, all jobs are expected to succeed, so we need to do something about it.
> 
> And one more thing - did you see any job where this new test succeeded. I looked at the logs of other dra jobs, but didn't find it.

Ok, so is there a way to skip / disable this specific test when running against a previous version?

Also, yes this test did succeed here: [pull-kubernetes-kind-dra-all](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/135919/pull-kubernetes-kind-dra-all/2008126968150626304)

File: test/e2e/dra/dra.go [hunk 5]
```diff
@@ -1088,6 +1088,55 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
...
+		// Allow allocating more than one device so that multiple claims can be prepared on the same node.
+		maxAllocations := 2
+		driver := drautils.NewDriver(f, nodes, drautils.DriverResources(maxAllocations)) // All tests get their own driver instance.
+		driver.WithKubelet = true
+		b := drautils.NewBuilder(f, driver)
+		// We have to set the parameters *before* creating the class.
+		b.ClassParameters = `{"x":"y"}`
+		expectedEnv := []string{"admin_x", "y"}
+		_, expected := b.ParametersEnv()
+		expectedEnv = append(expectedEnv, expected...)
```
Comment (bart0sh) [inline test/e2e/dra/dra.go]: Do we really need this?

File: test/e2e/dra/dra.go [hunk 6]
```diff
@@ -1088,6 +1088,55 @@ var _ = framework.SIGDescribe("node")(framework.WithLabel("DRA"), func() {
...
+				{
+					Name:              "second",
+					ResourceClaimName: &secondClaim.Name,
+				},
+			}
+
+			secondPod.Spec.Containers[0].Resources.Claims = []v1.ResourceClaim{
+				{Name: "first"},
+				{Name: "second"},
+			}
```
Comment (bart0sh) [inline test/e2e/dra/dra.go:1142]: Instead of rewriting pod and container claims, would it make sense to add a second one as the first one is already there, created by `b.PodExternal()`?

Comment (rogowski-piotr) [reply test/e2e/dra/dra.go:1142]: Yes, we could do something like this:
```go
secondPod.Spec.ResourceClaims = append(
    secondPod.Spec.ResourceClaims,
    v1.PodResourceClaim{
        Name:              "second",
        ResourceClaimName: &secondClaim.Name,
    },
)

secondPod.Spec.Containers[0].Resources.Claims = append(
    secondPod.Spec.Containers[0].Resources.Claims,
    v1.ResourceClaim{Name: "second"},
)
```

However, I think the current form where we explicitly set both claims makes it clearer what the test is actually exercising. So please let me know which version you prefer.

File: test/e2e/dra/dra.go (hunk 5 above)
Comment (rogowski-piotr) [reply test/e2e/dra/dra.go]: Fixed here: https://github.com/kubernetes/kubernetes/pull/135919/commits/5f1d95e648644d045bb75282b5fb7e70a10f5189

File: test/e2e/dra/dra.go (hunk 6 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:1142]: Both are ok from my point of view. You can keep yours if you think it's better.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

File: pkg/kubelet/cm/dra/manager.go [hunk 7]
```diff
@@ -360,10 +359,10 @@ func (m *Manager) prepareResources(ctx context.Context, pod *v1.Pod) error {
 				return fmt.Errorf("checkpoint ResourceClaim cache: %w", err)
 			}
 
-			// If this claim is already prepared, there is no need to prepare it again.
+			// If this claim is already prepared, continue preparing for any remaining claims.
 			if claimInfo.isPrepared() {
 				logger.V(5).Info("Resources already prepared", "pod", klog.KObj(pod), "podClaim", podClaim.Name, "claim", klog.KObj(resourceClaim))
-				return nil
+				continue
```
Comment (pohly) [inline pkg/kubelet/cm/dra/manager.go:366]: The E2E test is useful, but can we also have a unit test in the package which covers this case?

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing-strategy.md explains why test coverage should start with unit testing and only fall back to integration or E2E testing when necessary.

Comment (pohly) [reply pkg/kubelet/cm/dra/manager.go:366]: /hold

Comment (rogowski-piotr) [reply pkg/kubelet/cm/dra/manager.go:366]: Thanks for the suggestion! I added a unit test here: https://github.com/kubernetes/kubernetes/pull/135919/commits/3b556a0d9a74f447c332e4676d03ac1e68b221b5

File: pkg/kubelet/cm/dra/manager_test.go [hunk 8]
```diff
@@ -913,6 +913,118 @@ func TestPrepareResources(t *testing.T) {
 	}
 }
 
+// TestPrepareResourcesWithPreparedAndNewClaim verifies that PrepareResources
+// correctly handles a pod that references a mix of ResourceClaims:
+// - one claim already prepared in the cache
+// - one new claim that needs to be prepared
+func TestPrepareResourcesWithPreparedAndNewClaim(t *testing.T) {
+	backgroundCtx, cancel := context.WithCancel(context.Background())
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go]: Do we really need the second context? Would it be enough to get test context and a logger with `logger, tCtx := ktesting.NewTestContext(t)` and pass them where they're needed?

Comment (rogowski-piotr) [reply pkg/kubelet/cm/dra/manager_test.go]: Fixed here: https://github.com/kubernetes/kubernetes/commit/bc6fb77db9111658d1f103ac2b144fad8ea45759

File: pkg/kubelet/cm/dra/manager_test.go [hunk 9]
```diff
@@ -1053,6 +913,114 @@ dra_operations_duration_seconds_count{is_error="false",operation_name="PrepareRe
...
+		Create(tCtx, secondClaim, metav1.CreateOptions{})
+	require.NoError(t, err)
+
+	// first claim already prepared in cache
+	preparedClaimInfo := genTestClaimInfo(
+		firstClaim.UID,
+		[]string{podUID},
+		true,
+	)
+	manager.cache.add(preparedClaimInfo)
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go]: Just wondering would it be a bit more straightforward to create a pod with first resource claim and call `PrepareResources` for it? Manipulating internal cache directly looks a bit low level to me.

Comment (rogowski-piotr) [reply pkg/kubelet/cm/dra/manager_test.go]: Sure, fixed here: https://github.com/kubernetes/kubernetes/commit/6c2f6d23c6e9c0ade267f47492c277eb20391892

File: pkg/kubelet/cm/dra/manager_test.go [hunk 10]
```diff
@@ -1053,6 +913,153 @@ dra_operations_duration_seconds_count{is_error="false",operation_name="PrepareRe
...
+	)
+
+	_, err = fakeKubeClient.ResourceV1().ResourceClaims(namespace).Create(tCtx, firstClaim, metav1.CreateOptions{})
+	require.NoError(t, err)
+
+	_, err = fakeKubeClient.ResourceV1().ResourceClaims(namespace).Create(tCtx, secondClaim, metav1.CreateOptions{})
+	require.NoError(t, err)
+
+	// prepare resources for first pod (firstClaim only)
+	firstPod := &v1.Pod{
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go]: Can we use `genTestPod` helper for this?

Comment (rogowski-piotr) [reply pkg/kubelet/cm/dra/manager_test.go]: I proposed an approach with a new helper `genTestPodWithClaims` that allows adding multiple resource claims and makes it possible to create a second pod as well. https://github.com/kubernetes/kubernetes/commit/67149d28eb132f86b669616e4ebda24c2417dff8

**Review by pohly — APPROVED** [review]
/approve

File: pkg/kubelet/cm/dra/manager.go (hunk 7 above)
Comment (rogowski-piotr) [reply pkg/kubelet/cm/dra/manager.go:366]: > /hold

@pohly the `do-not-merge/hold` label is still present. Is this intended?

**Comment by bart0sh** [comment]
/lgtm

@pohly please, approve, thanks!
