### PR TITLE
e2e: waiting for scheduler pod to expose metrics once

### LINKED ISSUE #101894: [Flaky Test] [sig-instrumentation] MetricsGrabber should grab all metrics from a Scheduler
### Failure cluster [94211b5f97dae0d51701](https://go.k8s.io/triage#94211b5f97dae0d51701)
image

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:81
Apr 29 19:10:43.698: Unexpected error:
    <*errors.StatusError | 0xc002d9a280>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server rejected our request for an unknown reason (get pods kube-scheduler-bootstrap-e2e-master:10251)",
            Reason: "BadRequest",
            Details: {
                Name: "kube-scheduler-bootstrap-e2e-master:10251",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "unknown",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 400,
        },
    }
    the server rejected our request for an unknown reason (get pods kube-scheduler-bootstrap-e2e-master:10251)
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:88
```
#### Recent failures:
[2021/5/11 上午6:59:59 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391890754812514304)
[2021/5/11 上午6:58:56 ci-kubernetes-e2e-gci-gce-network-proxy-http-connect](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-http-connect/1391890503502401536)
[2021/5/11 上午4:59:55 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391860556041818112)
[2021/5/11 上午4:58:58 ci-kubernetes-e2e-gci-gce-network-proxy-http-connect](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-http-connect/1391860303720878080)
[2021/5/11 上午3:00:01 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391830356272877568)

/kind failing-test

/sig instrumentation
/assign

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
This is a similar fix to #88982. 

The reason is that `scheduler pod` is not ready before getting the metrics.

#### Which issue(s) this PR fixes:
Fixes #101894

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 1]
```diff
@@ -149,6 +150,29 @@ func (g *Grabber) GrabFromScheduler() (SchedulerMetrics, error) {
 	if g.kubeScheduler == "" {
 		return SchedulerMetrics{}, fmt.Errorf("kube-scheduler pod is not registered. Skipping Scheduler's metrics gathering")
 	}
+
+	var err error
+	podName := g.kubeScheduler
+	g.waitForSchedulerReadyOnce.Do(func() {
+		if readyErr := e2epod.WaitForPodsReady(g.client, metav1.NamespaceSystem, podName, 0); readyErr != nil {
```
Comment (dashpole) [inline test/e2e/framework/metrics/metrics_grabber.go:157]: You shouldn't rely on pods being registered with the API Server if possible.  I believe the other fix you referenced waited until it could fetch metrics instead.

Comment (dashpole) [reply test/e2e/framework/metrics/metrics_grabber.go:157]: Oh, looks like you do that below.  In that case, I don't think you need this initial pod ready check

Comment (pacoxu) [reply test/e2e/framework/metrics/metrics_grabber.go]: Thanks for the review.

I removed the `waiting for pod ready` here.
Updated.

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 2]
```diff
@@ -149,6 +150,23 @@ func (g *Grabber) GrabFromScheduler() (SchedulerMetrics, error) {
 	if g.kubeScheduler == "" {
 		return SchedulerMetrics{}, fmt.Errorf("kube-scheduler pod is not registered. Skipping Scheduler's metrics gathering")
 	}
+
+	var err error
+	g.waitForSchedulerReadyOnce.Do(func() {
+		var lastMetricsFetchErr error
+		if metricsWaitErr := wait.PollImmediate(time.Second, time.Minute, func() (bool, error) {
+			_, lastMetricsFetchErr = g.getMetricsFromPod(g.client, metricsProxyPod, metav1.NamespaceSystem, kubeSchedulerPort)
```
Comment (dashpole) [inline test/e2e/framework/metrics/metrics_grabber.go:158]: In addition to recording the error, should we also record the output from this call, instead of calling getMetricsFromPod again below?

Comment (pacoxu) [reply test/e2e/framework/metrics/metrics_grabber.go:158]: Good catch. I will update it.

Comment (pacoxu) [reply test/e2e/framework/metrics/metrics_grabber.go]: I updated GrabFromControllerManager below as well.

**Comment by dims** [comment]
thanks @pacoxu @dashpole

**Comment by jingxu97** [comment]
https://github.com/kubernetes/kubernetes/pull/102050#issuecomment-855016546

@pacoxu
