### PR TITLE
Fix TestServeExecInContainerIdleTimeout flake

### LINKED ISSUE #5628: TestServeExecInContainerIdleTimeout is Flaky
I've had a few of my latest submits fail because of this test being flaky:

```
W0318 23:49:08.262989    2801 docker.go:728] found a container with the "k8s" prefix, but too few fields (2): "k8s_unidentified"
I0318 23:49:08.265061    2801 container_gc.go:104] Removing unidentified dead container "/k8s_unidentified" with ID "2876"
I0318 23:49:08.278875    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 1024 bytes
I0318 23:49:08.280209    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 1024 bytes
I0318 23:49:08.281372    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 1024 bytes
I0318 23:49:08.282354    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 1024 bytes
I0318 23:49:08.284508    2801 image_manager.go:186] [ImageManager]: Disk usage on "" () is at 95% which is over the high threshold (90%). Trying to free 150 bytes
I0318 23:49:08.291075    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 450 bytes
I0318 23:49:08.292083    2801 image_manager.go:186] [ImageManager]: Disk usage on "" () is at 95% which is over the high threshold (90%). Trying to free 150 bytes
I0318 23:49:08.292338    2801 image_manager.go:240] [ImageManager]: Removing image "image-0" to free 50 bytes
W0318 23:49:08.306996    2801 kubelet.go:321] Data dir for pod "bothpod" exists in both old and new form, using new
W0318 23:49:08.319499    2801 kubelet.go:361] Data dir for pod "newpod", container "bothctr" exists in both old and new form, using new
W0318 23:49:08.337750    2801 kubelet.go:1029] No ref for pod '1234'
W0318 23:49:08.342927    2801 kubelet.go:1029] No ref for pod '1234'
I0318 23:49:08.347996    2801 kubelet.go:1371] probe success: bar
I0318 23:49:08.353109    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
I0318 23:49:08.854629    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
I0318 23:49:08.868693    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
I0318 23:49:08.894820    2801 kubelet.go:1371] probe success: bar2
W0318 23:49:08.895567    2801 kubelet.go:1029] No ref for pod '1234'
I0318 23:49:08.895983    2801 kubelet.go:1512] Creating pod infra container for "foo1_new"
W0318 23:49:08.914872    2801 kubelet.go:1029] No ref for pod '1234'
W0318 23:49:08.915306    2801 kubelet.go:1029] No ref for pod '9876'
W0318 23:49:08.927940    2801 kubelet.go:1029] No ref for pod '1234'
W0318 23:49:08.928092    2801 kubelet.go:1029] No ref for pod '9876'
I0318 23:49:08.937546    2801 kubelet.go:2323] Query docker container info for pod bar_new failed with error (no containers exist for this pod)
I0318 23:49:08.938116    2801 kubelet.go:1371] probe success: foo
W0318 23:49:08.938226    2801 kubelet.go:1029] No ref for pod '1234'
I0318 23:49:08.938380    2801 kubelet.go:2323] Query docker container info for pod bar_new failed with error (no containers exist for this pod)
I0318 23:49:08.954379    2801 kubelet.go:2323] Query docker container info for pod foo_new failed with error (no containers exist for this pod)
I0318 23:49:08.955061    2801 kubelet.go:1380] pod "foo_new" container "bar" hash changed (4660 vs 358204163). Pod will be killed and re-created.
W0318 23:49:08.955343    2801 kubelet.go:1029] No ref for pod '9876'
W0318 23:49:08.955858    2801 kubelet.go:1029] No ref for pod '1234'
I0318 23:49:08.956096    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
I0318 23:49:08.964022    2801 kubelet.go:2323] Query docker container info for pod foo_new failed with error (no containers exist for this pod)
W0318 23:49:08.991855    2801 probe.go:147] Failed to find probe builder for bar &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:0 TimeoutSeconds:0}
W0318 23:49:08.992252    2801 probe.go:147] Failed to find probe builder for bar &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:0 TimeoutSeconds:0}
W0318 23:49:08.992532    2801 probe.go:147] Failed to find probe builder for bar &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:0 TimeoutSeconds:0}
I0318 23:49:08.992890    2801 kubelet.go:1376] pod "foo_new" container "bar" is unhealthy (probe result: unknown). Container will be killed and re-created.
W0318 23:49:08.993197    2801 kubelet.go:1029] No ref for pod '1234'
I0318 23:49:08.994545    2801 kubelet.go:2323] Query docker container info for pod foo_new failed with error (No pod infra container exists for this pod)
W0318 23:49:09.032094    2801 kubelet.go:570] Unknown protocol "": defaulting to TCP
W0318 23:49:09.033911    2801 kubelet.go:570] Unknown protocol "foobar": defaulting to TCP
E0318 23:49:09.116595    2801 kubelet.go:639] Invalid handler: &{<nil> <nil> <nil>}
I0318 23:49:09.132495    2801 kubelet.go:2323] Query docker container info for pod foo_new failed with error (no containers exist for this pod)
E0318 23:49:09.134217    2801 kubelet.go:1298] Error running pod "foo_new" container "bar": failed to call event handler: test error
I0318 23:49:09.134463    2801 kubelet.go:2323] Query docker container info for pod foo_new failed with error (no containers exist for this pod)
I0318 23:49:09.152971    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
E0318 23:49:09.174420    2801 kubelet.go:1442] Unable to generate status for pod with name "foo_new" and uid "12345678" info with error(Couldn't find spec for pod foo_new)
E0318 23:49:09.320293    2801 kubelet.go:1850] Pod "_": HostPort is already allocated, ignoring: [[0].port: duplicate value '81']
E0318 23:49:09.322227    2801 kubelet.go:1850] Pod "newpod_foo": HostPort is already allocated, ignoring: [[0].port: duplicate value '80']
E0318 23:49:09.329512    2801 kubelet.go:1850] Pod "_": HostPort is already allocated, ignoring: [[0].port: duplicate value '80']
E0318 23:49:09.413563    2801 kubelet.go:2094] error updating node status, will retry: error getting node testnode: Minions "testnode" not found
E0318 23:49:09.413739    2801 kubelet.go:2094] error updating node status, will retry: error getting node testnode: Minions "testnode" not found
E0318 23:49:09.413829    2801 kubelet.go:2094] error updating node status, will retry: error getting node testnode: Minions "testnode" not found
E0318 23:49:09.413938    2801 kubelet.go:2094] error updating node status, will retry: error getting node testnode: Minions "testnode" not found
E0318 23:49:09.414041    2801 kubelet.go:2094] error updating node status, will retry: error getting node testnode: Minions "testnode" not found
I0318 23:49:09.416919    2801 kubelet.go:2323] Query docker container info for pod bar_foo failed with error (no containers exist for this pod)
W0318 23:49:09.554258    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.554583    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.554700    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.555666    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.555771    2801 probe.go:147] Failed to find probe builder for  <nil>
W0318 23:49:09.555844    2801 probe.go:147] Failed to find probe builder for  <nil>
W0318 23:49:09.555908    2801 probe.go:147] Failed to find probe builder for  <nil>
W0318 23:49:09.555990    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.556180    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.556390    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.556551    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.556660    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.556747    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:100 TimeoutSeconds:0}
W0318 23:49:09.556861    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:100 TimeoutSeconds:0}
W0318 23:49:09.556975    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:100 TimeoutSeconds:0}
W0318 23:49:09.557108    2801 probe.go:59] No ref for pod 'foobar' - ''
W0318 23:49:09.557185    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.557284    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.557387    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.557537    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.557638    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
W0318 23:49:09.557743    2801 probe.go:147] Failed to find probe builder for  &{Handler:{Exec:<nil> HTTPGet:<nil> TCPSocket:<nil>} InitialDelaySeconds:-100 TimeoutSeconds:0}
I0318 23:49:09.568445    2801 runonce.go:62] waiting for 1 pods
I0318 23:49:09.568785    2801 runonce.go:139] container "bar" not found
I0318 23:49:09.568867    2801 runonce.go:112] pod "foo" containers not running: syncing
I0318 23:49:09.570685    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
E0318 23:49:09.584318    2801 kubelet.go:1442] Unable to generate status for pod with name "foo_new" and uid "12345678" info with error(Couldn't find spec for pod foo_new)
I0318 23:49:09.584510    2801 runonce.go:125] pod "foo" containers synced, waiting for 1ms
I0318 23:49:09.585970    2801 runonce.go:139] container "bar" not found
I0318 23:49:09.586045    2801 runonce.go:112] pod "foo" containers not running: syncing
W0318 23:49:09.587383    2801 docker.go:728] found a container with the "k8s" prefix, but too few fields (5): "k8s_net_foo.new.test_abcdefgh_42"
I0318 23:49:09.587719    2801 kubelet.go:1512] Creating pod infra container for "foo_new"
E0318 23:49:09.590339    2801 kubelet.go:1442] Unable to generate status for pod with name "foo_new" and uid "12345678" info with error(Couldn't find spec for pod foo_new)
I0318 23:49:09.590430    2801 runonce.go:125] pod "foo" containers synced, waiting for 2ms
I0318 23:49:09.593147    2801 runonce.go:108] pod "foo" containers running
I0318 23:49:09.593308    2801 runonce.go:75] started pod "foo"
I0318 23:49:09.593383    2801 runonce.go:84] 1 pods started
I0318 23:49:10.200987    2801 server.go:127] HTTP InternalServerError: Internal Error: pod level status currently unimplemented
E0318 23:49:12.291530    2801 server.go:618] Timed out waiting for client to create streams
--- FAIL: TestServeExecInContainerIdleTimeout (2.18 seconds)
	server_test.go:670: error creating input stream: Timeout occured
W0318 23:49:14.832974    2801 connection.go:126] Stream rejected: Unable to parse '' as a port: strconv.ParseUint: parsing "": invalid syntax
W0318 23:49:14.954697    2801 connection.go:126] Stream rejected: Unable to parse 'abc' as a port: strconv.ParseUint: parsing "abc": invalid syntax
W0318 23:49:15.115169    2801 connection.go:126] Stream rejected: Unable to parse '-1' as a port: strconv.ParseUint: parsing "-1": invalid syntax
W0318 23:49:15.215886    2801 connection.go:126] Stream rejected: Unable to parse '65536' as a port: strconv.ParseUint: parsing "65536": value out of range
W0318 23:49:15.307982    2801 connection.go:126] Stream rejected: Port '0' must be greater than 0
FAIL
coverage: 69.8% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet	9.254s
```

### PR DESCRIPTION
**Pull request by ncdc**
Remove creation of stream from TestServeExecInContainerIdleTimeout as
it's not necessary to very idle timeout.

Increase stream creation and ack timeouts to 30 seconds.

Fixes #5628

### CODE REVIEW

**Comment by lavalamp** [comment]
Will merge on green because this flake happens way too much

But curious: is this functionality tested elsewhere?

**Comment by ncdc** [comment]
@lavalamp which functionality?

**Comment by lavalamp** [comment]
creating a stream, I guess?

**Comment by ncdc** [comment]
@lavalamp yes, it's in the following test case (TestServeExecInContainer).

**Comment by lavalamp** [comment]
Seems like there's another source of this problem? from one of the shippable runs:

```
I0409 19:52:56.123995   20473 runonce.go:141] container "bar" not found
I0409 19:52:56.124137   20473 runonce.go:114] pod "foo" containers not running: syncing
I0409 19:52:56.132643   20473 kubelet.go:2259] Query docker container info for pod "foo_new" failed with error (no containers exist for this pod)
I0409 19:52:56.133918   20473 kubelet.go:1436] Creating pod infra container for "foo_new"
I0409 19:52:56.191717   20473 kubelet.go:2259] Query docker container info for pod "foo_new" failed with error (no containers exist for this pod)
I0409 19:52:56.192185   20473 runonce.go:127] pod "foo" containers synced, waiting for 1ms
W0409 19:52:56.200178   20473 docker.go:489] found a container with the "k8s" prefix, but too few fields (5): "k8s_net_foo.new.test_abcdefgh_42"
W0409 19:52:56.200342   20473 docker.go:603] Parse docker container name "/k8s_net_foo.new.test_abcdefgh_42" error: Docker container name "k8s_net_foo.new.test_abcdefgh_42" has less parts than expected [k8s net foo.new.test abcdefgh 42]
I0409 19:52:56.200696   20473 runonce.go:110] pod "foo" containers running
I0409 19:52:56.200800   20473 runonce.go:76] started pod "foo"
I0409 19:52:56.200886   20473 runonce.go:85] 1 pods started
I0409 19:52:56.342066   20473 server.go:146] HTTP InternalServerError: Internal Error: pod level status currently unimplemented
E0409 19:52:58.941056   20473 server.go:613] Timed out waiting for client to create streams
E0409 19:52:58.941647   20473 server.go:613] Timed out waiting for client to create streams
--- FAIL: TestServeExecInContainer (4.36 seconds)
	server_test.go:831: 3: error creating error stream: Timeout occured
```

**Comment by ncdc** [comment]
@lavalamp I'm starting to feel like the test environments are running the code super slowly. The server waits 2 seconds for the client to create streams. Is that value too small?

**Comment by lavalamp** [comment]
In general, waiting a fixed amount of time is a bad idea, because the testing environments are really wildly varying in the amount of time stuff takes. Should really use some form of synchronization instead of waiting.

**Comment by ncdc** [comment]
As discussed on irc, I am increasing the server stream creation wait times to 30 seconds, and the client stream ack wait time to 30 seconds.

File: pkg/kubelet/server.go [hunk 1]
```diff
@@ -641,7 +640,7 @@ func waitForPortForwardDataStreamAndRun(pod string, uid types.UID, errorStream h
 
 	select {
 	case dataStream = <-dataStreamChan:
-	case <-time.After(1 * time.Second):
+	case <-time.After(30 * time.Second):
```
Comment (lavalamp) [inline pkg/kubelet/server.go]: nit: perhaps replace with a constant, as in the client code? Since it appears two places.

Comment (ncdc) [inline pkg/kubelet/server.go]: will do, thanks

**Comment by lavalamp** [comment]
Yay, shippable is green. Thanks!

**Comment by ncdc** [comment]
Thanks for bearing with me!

**Comment by lavalamp** [comment]
no problem, flaky test fixes greatly appreciated!
