### PR TITLE
DRA kubelet: validation pass before changing claim info cache

### LINKED ISSUE #131957: DRA: pod deletion delayed although NodePrepareResources was never issued
### What happened?

I am revamping our E2E tests so that they run through test cases without DRA drivers. Those tests then can become conformance tests.

Here's one scenario:
- ResourceSlices published by control plane (e.g. network-attached)
- pod scheduled
- pod startup fails (cannot call NodePrepareResources)
- delete pod
-> hangs

There is this event:
```
  Warning  FailedPrepareDynamicResources  81s   kubelet            Failed to prepare dynamic resources: failed to get gRPC client for driver dra-1411.k8s.io: plugin name dra-1411.k8s.io not found in the list of registered DRA plugins
```

It looks like the kubelet assumes that NodePrepareResources might have been called and therefore blocks pod termination while trying to call NodeUnprepareResources. 

cc @bart0sh 

### What did you expect to happen?

The kubelet should track whether it really issued a `NodePrepareResources`, not just that it tried to do that. Then deleting the pod should proceed.

Rationale: if a pod lands on a node by mistake, then deleting the pod should be sufficient to recover from that mistake.

Also, the error message is a bit too verbose. The driver name should be given once, and "not found in the list" could be shortened? Also, don't repeat the word "failed". The innermost error can use it if there truly was a failure, but wrapping an error should then only add context.

```
prepare dynamic resources: get gRPC client for driver dra-1411.k8s.io: plugin not registered
```

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/kubernetes/pull/131956

```
dlv test ./test/e2e -- -ginkgo.focus "control plane with single node.*supports external claim referenced by multiple containers of multiple pods"  -test.v -ginkgo.v -v=3
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If preparing for a pod failed because the driver was not registered, it failed after already having added the pod and claim to the claim info cache. The effect was that deletion of the pod was blocked until the driver got installed. Other errors had a similar effect. Now as many errors as possible are checked in a read-only loop before proceeding to changing the claim info cache.

The error message that was surfaced for the problem was not very readable:

     Failed to prepare dynamic resources: failed to get gRPC client for driver dra-1411.k8s.io: plugin name dra-1411.k8s.io not found in the list of registered DRA plugins

To address this, error messages and wrapping get updated according to these guidelines:

    // Most errors returned by the manager show up in the context of a pod.
    // They try to adher to the following convention:
    // - Don't include the pod.
    // - Use terms that are familiar to users.
    // - Don't include the namespace, it can be inferred from the context.
    // - Avoid repeated "failed to ...: failed to ..." when wrapping errors.
    // - Avoid wrapping when it does not provide relevant additional information to keep the user-visible error short.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/131957

#### Special notes for your reviewer:

Testing this will follow through the updated E2E tests in https://github.com/kubernetes/kubernetes/pull/131956. Those are what revealed the issue.

#### Does this PR introduce a user-facing change?
```release-note
DRA kubelet: recovery from mistakes like scheduling a pod onto a node with the required driver not running is a bit simpler now because the kubelet does not block pod deletion unnecessarily.
```

/assign @klueska

### CODE REVIEW

File: pkg/kubelet/cm/dra/claiminfo.go [hunk 1]
```diff
@@ -156,9 +156,8 @@ func (cache *claimInfoCache) withRLock(f func() error) error {
 }
 
 // add adds a new claim info object into the claim info cache.
-func (cache *claimInfoCache) add(info *ClaimInfo) *ClaimInfo {
+func (cache *claimInfoCache) add(info *ClaimInfo) {
 	cache.claimInfo[info.Namespace+"/"+info.ClaimName] = info
-	return info
```
Comment (pohly) [inline pkg/kubelet/cm/dra/claiminfo.go:161]: The semantic of returning the ClaimInfo instance was unclear (is it the same or potentially a different instance?), so to avoid the ambiguity I removed this.

File: pkg/kubelet/cm/dra/manager_test.go [hunk 2]
```diff
@@ -408,13 +408,13 @@ func TestPrepareResources(t *testing.T) {
...
 			pod:            genTestPod(),
-			expectedErrMsg: "failed to fetch ResourceClaim ",
+			expectedErrMsg: "fetch ResourceClaim ",
 		},
 		{
 			description:    "unknown driver",
 			pod:            genTestPod(),
-			claim:          genTestClaim(claimName, "unknown driver", deviceName, podUID),
-			expectedErrMsg: "plugin name unknown driver not found in the list of registered DRA plugins",
+			claim:          genTestClaim(claimName, "unknown.driver", deviceName, podUID),
```
Comment (pohly) [inline pkg/kubelet/cm/dra/manager_test.go:416]: I added the dot to make this more obviously a single driver name and not part of the error message.

File: pkg/kubelet/cm/dra/manager.go [hunk 3]
```diff
@@ -76,10 +76,18 @@ type ManagerImpl struct {
...
 
 // NewManagerImpl creates a new manager.
+//
+// Most errors returned by the manager show up in the context of a pod.
+// They try to adhere to the following convention:
+// - Don't include the pod.
+// - Use terms that are familiar to users.
+// - Don't include the namespace, it can be inferred from the context.
+// - Avoid repeated "failed to ...: failed to ..." when wrapping errors.
+// - Avoid wrapping when it does not provide relevant additional information to keep the user-visible error short.
```
Comment (harche) [inline pkg/kubelet/cm/dra/manager.go:86]: These are really great improvements, but once those fixes are in, this comment lingering in the code doesn't serve much purpose to the future readers about the implementation details as it focuses on the past shortcomings that have been now fixed. I see that you have already documented this in a commit message, which is the best place to describe the past and future behaviour due to this change.

**Comment by harche** [comment]
cc @ffromani for approval.

**Review by ffromani — COMMENTED** [review]
/approve

nothing looks suspicious from my admittedly limited DRA experience
