### PR TITLE
ipallocator: handle errors correctly

### LINKED ISSUE #135333: Creating a Service without Name creates an invalid IPAddress
When creating k8s Service without name it tries to create an invalid IPAddress.

This is because the Service apiserver registry tries to allocate the ClusterIP, if not set, before the object name has been validated.

We could/should validate that the IPAddress object we are going to be create is correct, and fail fast avoiding the penalty of failing an API request, something like

```diff
diff --git a/pkg/registry/core/service/ipallocator/ipallocator.go b/pkg/registry/core/service/ipallocator/ipallocator.go
index d7d66b0744d..9490d237cd1 100644
--- a/pkg/registry/core/service/ipallocator/ipallocator.go
+++ b/pkg/registry/core/service/ipallocator/ipallocator.go
@@ -139,6 +139,13 @@ func NewIPAllocator(
 }
 
 func (a *Allocator) createIPAddress(name string, svc *api.Service, scope string) error {
+       // obtain the Parent Reference, since IPAddress is generated before the Service object is created,
+       // the Service reference can be nil and fail later during the creation of the IPAddress object.
+       ipRef, err := serviceToRef(svc)
+       if err != nil {
+               return err
+       }
+
        ipAddress := networkingv1.IPAddress{
                ObjectMeta: metav1.ObjectMeta{
                        Name: name,
@@ -148,10 +155,10 @@ func (a *Allocator) createIPAddress(name string, svc *api.Service, scope string)
                        },
                },
                Spec: networkingv1.IPAddressSpec{
-                       ParentRef: serviceToRef(svc),
+                       ParentRef: ipRef,
                },
        }
-       _, err := a.client.IPAddresses().Create(context.Background(), &ipAddress, metav1.CreateOptions{})
+       _, err = a.client.IPAddresses().Create(context.Background(), &ipAddress, metav1.CreateOptions{})
        if err != nil {
                // update metrics
                a.metrics.incrementAllocationErrors(a.metricLabel, scope)
@@ -604,9 +611,13 @@ func broadcastAddress(subnet netip.Prefix) (netip.Addr, error) {
 }
 
 // serviceToRef obtain the Service Parent Reference
-func serviceToRef(svc *api.Service) *networkingv1.ParentReference {
+func serviceToRef(svc *api.Service) (*networkingv1.ParentReference, error) {
        if svc == nil {
-               return nil
+               return nil, nil
+       }
+
+       if len(svc.Name) == 0 || len(svc.Namespace) == 0 {
+               return nil, fmt.Errorf("invalid Service reference: %v/%v", svc.Namespace, svc.Name)
        }
 
        return &networkingv1.ParentReference{
@@ -614,5 +625,5 @@ func serviceToRef(svc *api.Service) *networkingv1.ParentReference {
                Resource:  "services",
                Namespace: svc.Namespace,
                Name:      svc.Name,
-       }
+       }, nil
 }
```

/sig network

We should also add an integration test and corresponding unit test.

### PR DESCRIPTION
**Pull request by aojea**
The ipallocator was blindly assuming that all errors are retryable, that causes that the allocator tries to exhaust all the possibilities to allocate an IP address.

If the error is not retryable this means the allocator will generate as many API calls as existing available IPs are in the allocator, causing CPU exhaustion since this requests are coming from inside the apiserver.

In addition to handle the error correctly, this patch also interpret the error to return the right status code depending on the error type.

/kind bug
/kind regression

```release-note
fix a bug in the kube-apiserver where a malformed Service without name can cause high CPU usage. The bug is present on the new Cluster IP allocators enabled with the feature MultiCIDRServiceAllocator (enabled by default since 1.33)
```

/assign @thockin @liggitt @carlory @danwinship 

Fixes: #135333 

/sig network

missing unit tests, just running it through CI and for early review

### CODE REVIEW

File: test/integration/servicecidr/allocator_test.go [hunk 1]
```diff
@@ -572,3 +574,77 @@ func TestFlagsIPAllocator(t *testing.T) {
 	}
 
 }
+
+// regression test for https://issues.k8s.io/135333
```
Comment (aojea) [inline test/integration/servicecidr/allocator_test.go:578]: this reproduces it perfectly

File: pkg/registry/core/service/ipallocator/cidrallocator.go [hunk 2]
```diff
@@ -391,6 +392,9 @@ func (c *MetaAllocator) AllocateNextService(service *api.Service) (net.IP, error
 		ip, err := item.allocator.AllocateNextService(service)
 		if err == nil {
 			return ip, nil
+			// only keep trying if the allocator is full or not ready
+		} else if !errors.Is(err, ErrFull) && !errors.Is(err, ErrNotReady) {
+			return nil, err
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/cidrallocator.go]: indentation of comment is wrong

```suggestion
		}
		// only keep trying if the allocator is full or not ready
		if !errors.Is(err, ErrFull) && !errors.Is(err, ErrNotReady) {
			return nil, err
```

(I find it slightly annoying that the comment describes that the `if` statement _doesn't_ do as well, but it would be awkward to rewrite either the comment or the code...)

File: pkg/registry/core/service/ipallocator/cidrallocator_test.go [hunk 3]
```diff
@@ -849,3 +850,140 @@ func TestCIDRAllocatorClusterIPAllocatedMetrics(t *testing.T) {
...
+		return allocator.ready.Load(), nil
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	calls := 0
+	// we can not test the client because is not exposed
+	// so we hijack the existing client to inject the reactor
+	fakeclient, ok := r.client.(*networkingv1fake.FakeNetworkingV1)
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/cidrallocator_test.go:904]: I don't understand the comment. You hijack the client which was not exposed?

File: pkg/registry/core/service/ipallocator/cidrallocator_test.go [hunk 4]
```diff
@@ -849,3 +850,140 @@ func TestCIDRAllocatorClusterIPAllocatedMetrics(t *testing.T) {
...
+		allocator, err := r.getAllocator(netutils.ParseIPSloppy("192.168.0.1"), true)
+		if err != nil {
+			return false, nil
+		}
+		allocator.ipAddressSynced = func() bool { return false }
+		return allocator.ready.Load(), nil
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/cidrallocator_test.go:950]: (helper function?)

File: pkg/registry/core/service/ipallocator/cidrallocator_test.go [hunk 5]
```diff
@@ -849,3 +850,140 @@ func TestCIDRAllocatorClusterIPAllocatedMetrics(t *testing.T) {
...
+		allocator.ipAddressSynced = func() bool { return true }
+		return allocator.ready.Load(), nil
+	})
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// make the first allocator not ready
+	r.allocators["192.168.0.0/24"].allocator.ready.Store(false)
+	_, subnet, err := netutils.ParseCIDRSloppy("192.168.1.0/24")
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/cidrallocator_test.go]:
```suggestion
	_, secondSubnet, err := netutils.ParseCIDRSloppy("192.168.1.0/24")
```

?

File: pkg/registry/core/service/ipallocator/ipallocator.go [hunk 6]
```diff
@@ -279,9 +280,13 @@ func (a *Allocator) allocateNextService(svc *api.Service, dryRun bool) (net.IP,
 			return ip, nil
 		}
 	}
-	// update metrics
+	// no IP available
+	if err == nil {
+		klog.Info("IT CAN NOT HAPPEN No IP Allocated and no error")
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/ipallocator.go]: leftover debugging?

File: pkg/registry/core/service/ipallocator/ipallocator.go [hunk 7]
```diff
@@ -343,11 +348,15 @@ func (a *Allocator) allocateFromRange(iterator func() netip.Addr, svc *api.Servi
 		}
 		// address is not present on the cache, try to allocate it
 		err = a.createIPAddress(name, svc, "dynamic")
-		// an error can happen if there is a race and our informer was not updated
-		// swallow the error and try with the next IP address
+		// only continue if there is an error caused by a race condition.
+		// Ref: https://issues.k8s.io/135333
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/ipallocator.go:354]: That makes it sound like #135333 talks about the race condition, but it actually talks about the _non_-race-condition case.

```
		// an error can happen if there is a race and our informer was not updated
		// in that case, swallow the error and try with the next IP address,
		// but abort on other errors. Ref: https://issues.k8s.io/135333
```

File: pkg/registry/core/service/storage/alloc.go [hunk 8]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package storage
 
 import (
+	stderrors "errors"
```
Comment (danwinship) [inline pkg/registry/core/service/storage/alloc.go]: it would be more consistent to rename `"k8s.io/apimachinery/pkg/api/errors"` to `apierrors` instead

File: pkg/registry/core/service/storage/alloc.go [hunk 9]
```diff
@@ -414,6 +415,10 @@ func (al *Allocators) allocIPs(service *api.Service, toAlloc map[api.IPFamily]st
 				allocatedIP, err = allocator.AllocateNext()
 			}
 			if err != nil {
+				if !stderrors.Is(err, ipallocator.ErrFull) {
+					el := field.ErrorList{field.Invalid(field.NewPath("spec", "clusterIPs"), service.Spec.ClusterIPs, fmt.Sprintf("failed to allocate IP %v: %v", ip, err))}
```
Comment (danwinship) [inline pkg/registry/core/service/storage/alloc.go]: `ip` is always `""` at this point?

File: test/integration/servicecidr/allocator_test.go [hunk 10]
```diff
@@ -572,3 +574,77 @@ func TestFlagsIPAllocator(t *testing.T) {
...
+		if err != nil {
+			return false, err
+		}
+		return isServiceCIDRReady(cidr), nil
+	}); err != nil {
+		t.Fatalf("waiting for service cidr ready condition %v", err)
+	}
+
+	// A service without a name keeps failing to allocate an IP address because
+	// it tries to create the IPAddress object with an invalid reference.
```
Comment (danwinship) [inline test/integration/servicecidr/allocator_test.go:627]: So... the IP allocation happens before the Service gets validated? Are there any other ways that the IP allocator might be implicitly assuming that the Service is valid? Should it be explicitly validating any data it gets?

File: test/integration/servicecidr/allocator_test.go [hunk 11]
```diff
@@ -572,3 +574,77 @@ func TestFlagsIPAllocator(t *testing.T) {
...
+	svc := &v1.Service{
+		Spec: v1.ServiceSpec{
+			Type: v1.ServiceTypeClusterIP,
+			Ports: []v1.ServicePort{
+				{Port: 80},
+			},
+		},
+	}
+
+	// The request will time out on the allocator
```
Comment (danwinship) [inline test/integration/servicecidr/allocator_test.go]: That was true before the fix, but not after, right?

File: pkg/registry/core/service/ipallocator/cidrallocator_test.go (hunk 3 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/cidrallocator_test.go:904]: ai agent nonsense, it is about overriding

File: pkg/registry/core/service/storage/alloc.go (hunk 8 above)
Comment (aojea) [reply pkg/registry/core/service/storage/alloc.go]: yeah, but since we need to backport it will make the diff larger, I do not mind changing it

File: pkg/registry/core/service/storage/alloc.go (hunk 9 above)
Comment (aojea) [reply pkg/registry/core/service/storage/alloc.go]: I guess it is, now that you mention it

File: test/integration/servicecidr/allocator_test.go (hunk 10 above)
Comment (aojea) [reply test/integration/servicecidr/allocator_test.go:627]: > the IP allocation happens before the Service gets validated? 

yes, historical context in order

- #96393
- #96684
- #112063
- #110646

> Are there any other ways that the IP allocator might be implicitly assuming that the Service is valid? Should it be explicitly validating any data it gets?

We explored bringing validation earlier in https://github.com/kubernetes/kubernetes/pull/135364 and during that review is when I found the allocator bug ... I do not think we can move the entire validation before without risk or making the current bespoke logic more complex and hard to maintain. The invalid service problem is ok, the existing BeginCreate and BeginUpdate hooks allow transactions and that is working fine and as expected.

In this particular case, the problem is that the IPAddress object reference is wrong because the Service name is empty, we can fail fast here and save one API call, but that does not seem much of a problem

File: test/integration/servicecidr/allocator_test.go (hunk 11 above)
Comment (aojea) [reply test/integration/servicecidr/allocator_test.go]: yes, I should change it to make it clear

File: test/integration/servicecidr/allocator_test.go (hunk 10 above)
Comment (danwinship) [reply test/integration/servicecidr/allocator_test.go:627]: Right, I get that we can't actually fix it to do validation-before-allocation, but this is a pretty surprising foot-gun. It is very unusual to have to work with an unvalidated API object, and given that we apparently forgot that we were doing that in one place in the IP allocator code, it's reasonable to wonder if we also forgot about it in other places, and what we could do to make this less dangerous.

Comment (aojea) [reply test/integration/servicecidr/allocator_test.go:627]: ah, I misunderstood, the IPAddress only need to build the ParentReference, in this case the problem is not really the use of unvalidated data, is that the ParentReference we build is invalid (name is empty) and we could have detected that

```
 apiVersion: networking.k8s.io/v1
  kind: IPAddress
  metadata:
    creationTimestamp: "2025-11-28T12:42:23Z"
    labels:
      ipaddress.kubernetes.io/ip-family: IPv4
      ipaddress.kubernetes.io/managed-by: ipallocator.k8s.io
    name: 10.96.140.184
    resourceVersion: "3086"
    uid: ba6b6d42-1bc0-4d4f-8c99-f7d0ab895ec0
  spec:
    parentRef:
      name: test
      namespace: default
      resource: services
```

So, if we failed when building the reference https://github.com/kubernetes/kubernetes/issues/135333#issue-3636381742 we should not have this issue, but then there will be some other situations less evident that will may trigger the same problem (temporary unavailability of apiserver)

TL;DE  an invalid Service name is not a problem, an empty service name is because the IPAddress validation requires the ParentReference to always have a name

Comment (danwinship) [reply test/integration/servicecidr/allocator_test.go:627]: Right, but we were only constructing an invalid ParentReference because the code was making the _completely reasonable_ assumption that if you have a Service, then you can construct a ParentReference pointing to that Service. It just forgot that it didn't actually have a Service, it just had something that _might_ be a Service.

File: pkg/registry/core/service/ipallocator/cidrallocator_test.go (hunk 4 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/cidrallocator_test.go:950]: the other tests have this format too, if we use a helper it will be better to change the entire file ... and that will generate a larger diff for the backport

File: pkg/registry/core/service/ipallocator/ipallocator.go (hunk 6 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator.go]: we have some of this because we should not panic but it will be good to inform about it
```
grep -r "HAPPEN" pkg/
pkg/controller/servicecidrs/servicecidrs_controller.go:                         logger.Info("[SHOULD NOT HAPPEN] unexpected error parsing IPAddress", "IPAddress", ip.Name, "error", err)
pkg/controller/volume/persistentvolume/pv_controller.go:                                        logger.V(4).Info("Synchronizing unbound PersistentVolumeClaim, volume already bound to different claim by controller, THIS SHOULD NEVER HAPPEN", "PVC", klog.KObj(claim), "boundClaim", klog.KRef(volume.Spec.ClaimRef.Namespace, volume.Spec.ClaimRef.Name))
```

File: pkg/registry/core/service/ipallocator/ipallocator.go (hunk 7 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator.go:354]: yeah , is a TOCTOU kind of race

File: pkg/registry/core/service/storage/alloc.go (hunk 8 above)
Comment (aojea) [reply pkg/registry/core/service/storage/alloc.go]: updated

File: pkg/registry/core/service/ipallocator/ipallocator.go [hunk 12]
```diff
@@ -343,11 +348,16 @@ func (a *Allocator) allocateFromRange(iterator func() netip.Addr, svc *api.Servi
 		}
 		// address is not present on the cache, try to allocate it
 		err = a.createIPAddress(name, svc, "dynamic")
-		// an error can happen if there is a race and our informer was not updated
-		// swallow the error and try with the next IP address
+	// an error can happen if there is a race and our informer was not updated
+		// in that case, swallow the error and try with the next IP address,
+		// but abort on other errors. Ref: https://issues.k8s.io/135333
 		if err != nil {
+			if apierrors.IsAlreadyExists(err) {
```
Comment (carlory) [inline pkg/registry/core/service/ipallocator/ipallocator.go]: The `createIPAddress` function return a `ErrAllocated` error when the kube-apiserver returns an AlreadyExists error. 

https://github.com/aojea/kubernetes/blob/63a664a27e6d94e896a448e5e05e87bff8372db8/pkg/registry/core/service/ipallocator/ipallocator.go#L159

File: pkg/registry/core/service/storage/alloc.go [hunk 13]
```diff
@@ -414,13 +415,17 @@ func (al *Allocators) allocIPs(service *api.Service, toAlloc map[api.IPFamily]st
 				allocatedIP, err = allocator.AllocateNext()
 			}
 			if err != nil {
-				return allocated, errors.NewInternalError(fmt.Errorf("failed to allocate a serviceIP: %v", err))
+				if !errors.Is(err, ipallocator.ErrFull) {
+					el := field.ErrorList{field.Invalid(field.NewPath("spec", "clusterIPs"), service.Spec.ClusterIPs, fmt.Sprintf("failed to allocate IP: %v", err))}
+					return allocated, apierrors.NewInvalid(api.Kind("Service"), service.Name, el)
```
Comment (carlory) [inline pkg/registry/core/service/storage/alloc.go]: If the invalid field is empty name or generateName with unexpected char, the user can not get correct error message?

File: pkg/registry/core/service/ipallocator/ipallocator.go (hunk 12 above)
Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator.go]: uppps

Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator.go]: updated and added unit test, great catch

File: pkg/registry/core/service/ipallocator/ipallocator_test.go [hunk 14]
```diff
@@ -1228,3 +1229,89 @@ func TestUsedWithInvalidIPs(t *testing.T) {
...
+			return true, nil, apierrors.NewAlreadyExists(networkingv1.Resource("ipaddresses"), action.(k8stesting.CreateAction).GetObject().(*networkingv1.IPAddress).Name)
+		}
+		ip := action.(k8stesting.CreateAction).GetObject().(*networkingv1.IPAddress)
+		_, exists, err := ipStore.GetByKey(ip.Name)
+		if exists && err != nil {
+			return false, nil, fmt.Errorf("ip already exist")
+		}
+		ip.Generation = 1
+		err = ipStore.Add(ip)
+		return false, ip, err
```
Comment (carlory) [inline pkg/registry/core/service/ipallocator/ipallocator_test.go:1299]: This code block can not be executed according to the test case.

And `if exists && err != nil {` might need to be changed to `if exists && err == nil {`

Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator_test.go:1299]: it is actually the first condition the one that gets executed

> if collisionCount == 0 {
			collisionCount++
			// Simulate ErrAllocated (AlreadyExists)
			return true, nil, apierrors.NewAlreadyExists(networkingv1.Resource("ipaddresses"), action.(k8stesting.CreateAction).GetObject().(*networkingv1.IPAddress).Name)
		}

, this error should fail the test if is triggered, but I make it more explicit now

File: pkg/registry/core/service/ipallocator/ipallocator.go [hunk 15]
```diff
@@ -343,11 +348,17 @@ func (a *Allocator) allocateFromRange(iterator func() netip.Addr, svc *api.Servi
...
 		err = a.createIPAddress(name, svc, "dynamic")
-		// an error can happen if there is a race and our informer was not updated
-		// swallow the error and try with the next IP address
+		// an error can happen if there is a TOCTOU race and the IP address
+		// was allocated by another instance, in that case, swallow the error
+		// and try with the next IP address, but abort on other errors.
+		// Ref: https://issues.k8s.io/135333
 		if err != nil {
+			if errors.Is(err, ErrAllocated) {
+				klog.Infof("IP %s already exists", name)
```
Comment (danwinship) [inline pkg/registry/core/service/ipallocator/ipallocator.go]: That's not going to be very helpful if it shows up in the log. ("Why are you telling me that this random IP already exists?")

Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator.go]: let me add more context then

**Comment by aojea** [comment]
@carlory I think we forget to backport this, IPAllocator was GA in 1.33
