### PR TITLE
ignore nonexistent ns net file error when deleting container network

### LINKED ISSUE #57465: "Error deleting network: failed to Statfs" during pod shutdown
/kind bug

**What happened**:

During pod teardown, we sometimes see the following error-level kubelet logs:

```
time="2017-12-20T15:42:07Z" level=info msg="Released address using workloadID" Workload=mynamespace.my-cron-pz1b7
Calico CNI deleting device in netns /proc/115577/ns/net
E1220 15:42:09.401448    1396 cni.go:278] Error deleting network: failed to Statfs "/proc/115577/ns/net": no such file or directory
E1220 15:42:09.554117    1396 remote_runtime.go:109] StopPodSandbox "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "my-cron-pz1b7_mynamespace" network: failed to Statfs "/proc/115577/ns/net": no such file or directory
E1220 15:42:09.554162    1396 kuberuntime_manager.go:784] Failed to stop sandbox {"docker" "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
E1220 15:42:09.554192    1396 kubelet_pods.go:920] Failed killing the pod "my-cron-pz1b7": failed to "KillPodSandbox" for "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"my-cron-pz1b7_mynamespace\" network: failed to Statfs \"/proc/115577/ns/net\": no such file or directory"
```

**What you expected to happen**:

Clean pod shutdown, no error-level logs.

**How to reproduce it (as minimally and precisely as possible)**:

We've got two kube crons that run every minute, across 12 regions in production -- so 34560 related pods daily -- and we see this about 3-12 times per day.

**Anything else we need to know?**:

Relevant kubelet log context of a cron pod that manifested this error:
```
I1220 15:42:02.636144    1396 kubelet.go:1808] SyncLoop (ADD, "api"): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)"
I1220 15:42:02.824020    1396 reconciler.go:242] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (spec.Name: "etc-ssh") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5")
I1220 15:42:02.824039    1396 reconciler.go:242] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5")
I1220 15:42:02.824205    1396 reconciler.go:242] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5")
I1220 15:42:02.924419    1396 reconciler.go:318] MountVolume operation started for volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (spec.Name: "etc-ssh") to pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:02.924479    1396 reconciler.go:318] MountVolume operation started for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") to pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:02.924637    1396 reconciler.go:318] MountVolume operation started for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") to pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:02.927428    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (spec.Name: "etc-ssh") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:02.932912    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:02.935035    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:04.230307    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:04.233500    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:04.459932    1396 kuberuntime_manager.go:370] No sandbox for pod "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)" can be found. Need to start a new one
time="2017-12-20T15:42:04Z" level=info msg="Extracted identifiers" Node=knode7 Orchestrator=k8s Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:04Z" level=info msg="Loaded CNI NetConf" NetConfg={ calico-k8s-network calico { calico-ipam  <nil> <nil> [] []} 0     http://127.0.0.1:4001 info {     } { kubeconfig } {{{ {[]}}}}    } Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:04Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=ADD CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS=/proc/115577/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:42:04Z" level=info msg="Extracted identifiers for CmdAddK8s" Node=knode7 Orchestrator=k8s Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:04Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=ADD CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS=/proc/115577/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:42:04Z" level=info msg="Auto assigning IP" Workload=mynamespace.my-cron-123-1513784520-pz1b7 assignArgs={1 0 0xc420306270 map[]  [] []}
time="2017-12-20T15:42:04Z" level=info msg="Creating new handle: mynamespace.my-cron-123-1513784520-pz1b7"
time="2017-12-20T15:42:04Z" level=info msg="Decremented handle 'mynamespace.my-cron-123-1513784520-pz1b7' by 1"
time="2017-12-20T15:42:04Z" level=info msg="Creating new handle: mynamespace.my-cron-123-1513784520-pz1b7"
time="2017-12-20T15:42:04Z" level=info msg="IPAM Result" Workload=mynamespace.my-cron-123-1513784520-pz1b7 result.IPs=[{Version:4 Interface:0 Address:{IP:1.2.3.5 Mask:ffffffff} Gateway:<nil>}]
time="2017-12-20T15:42:04Z" level=info msg="Populated endpoint" Workload=mynamespace.my-cron-123-1513784520-pz1b7 endpoint=&{{workloadEndpoint v1} {{<nil>} eth0 mynamespace.my-cron-123-1513784520-pz1b7 k8s knode7 159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e map[]} {[1.2.3.5/32] [] <nil> <nil> [calico-k8s-network]  <nil>}}
time="2017-12-20T15:42:04Z" level=info msg="Added Mac and interface name to endpoint" Workload=mynamespace.my-cron-123-1513784520-pz1b7 endpoint=&{{workloadEndpoint v1} {{<nil>} eth0 mynamespace.my-cron-123-1513784520-pz1b7 k8s knode7 159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e map[]} {[1.2.3.5/32] [] <nil> <nil> [calico-k8s-network] cali2c05b40c93f e6:5c:b8:41:b5:04}}
time="2017-12-20T15:42:04Z" level=info msg="Wrote updated endpoint to datastore" Workload=mynamespace.my-cron-123-1513784520-pz1b7
I1220 15:42:05.007393    1396 kubelet.go:1842] SyncLoop (PLEG): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)", event: &pleg.PodLifecycleEvent{ID:"52d9b9b4-e59c-11e7-b6c8-005056ae60f5", Type:"ContainerStarted", Data:"159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
I1220 15:42:06.047444    1396 kubelet.go:1842] SyncLoop (PLEG): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)", event: &pleg.PodLifecycleEvent{ID:"52d9b9b4-e59c-11e7-b6c8-005056ae60f5", Type:"ContainerStarted", Data:"f056efb76b15d038a4f30b3e42f8d52557e83da7a7e9391e12e81bc261e0cf0a"}
I1220 15:42:06.146032    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:06.147526    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.063207    1396 kubelet.go:1842] SyncLoop (PLEG): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)", event: &pleg.PodLifecycleEvent{ID:"52d9b9b4-e59c-11e7-b6c8-005056ae60f5", Type:"ContainerDied", Data:"f056efb76b15d038a4f30b3e42f8d52557e83da7a7e9391e12e81bc261e0cf0a"}
I1220 15:42:07.125113    1396 kubelet_pods.go:917] Killing unwanted pod "my-cron-123-1513784520-pz1b7"
I1220 15:42:07.129145    1396 kuberuntime_container.go:545] Killing container "docker://f056efb76b15d038a4f30b3e42f8d52557e83da7a7e9391e12e81bc261e0cf0a" with 30 second grace period
I1220 15:42:07.155666    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.156450    1396 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.243117    1396 reconciler.go:201] UnmountVolume operation started for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") from pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.243520    1396 reconciler.go:201] UnmountVolume operation started for volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (spec.Name: "etc-ssh") from pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.243801    1396 reconciler.go:201] UnmountVolume operation started for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") from pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5").
I1220 15:42:07.245697    1396 operation_generator.go:672] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (OuterVolumeSpecName: "etc-ssh") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5"). InnerVolumeSpecName "etc-ssh". PluginName "kubernetes.io/host-path", VolumeGidValue ""
I1220 15:42:07.252149    1396 operation_generator.go:672] UnmountVolume.TearDown succeeded for volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (OuterVolumeSpecName: "configmap-mount") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5"). InnerVolumeSpecName "configmap-mount". PluginName "kubernetes.io/configmap", VolumeGidValue ""
time="2017-12-20T15:42:07Z" level=info msg="Extracted identifiers" Node=knode7 Orchestrator=k8s Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:07Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS=/proc/115577/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
I1220 15:42:07.265518    1396 operation_generator.go:672] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (OuterVolumeSpecName: "default-token-wphxs") pod "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" (UID: "52d9b9b4-e59c-11e7-b6c8-005056ae60f5"). InnerVolumeSpecName "default-token-wphxs". PluginName "kubernetes.io/secret", VolumeGidValue ""
I1220 15:42:07.344049    1396 reconciler.go:363] Detached volume "kubernetes.io/host-path/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-etc-ssh" (spec.Name: "etc-ssh") devicePath: ""
I1220 15:42:07.344187    1396 reconciler.go:363] Detached volume "kubernetes.io/secret/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-default-token-wphxs" (spec.Name: "default-token-wphxs") devicePath: ""
I1220 15:42:07.344202    1396 reconciler.go:363] Detached volume "kubernetes.io/configmap/52d9b9b4-e59c-11e7-b6c8-005056ae60f5-configmap-mount" (spec.Name: "configmap-mount") devicePath: ""
time="2017-12-20T15:42:07Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS=/proc/115577/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:42:07Z" level=info msg="Releasing address using workloadID" Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:07Z" level=info msg="Releasing all IPs with handle 'mynamespace.my-cron-123-1513784520-pz1b7'"
time="2017-12-20T15:42:07Z" level=info msg="Decremented handle 'mynamespace.my-cron-123-1513784520-pz1b7' by 1"
time="2017-12-20T15:42:07Z" level=info msg="Released address using workloadID" Workload=mynamespace.my-cron-123-1513784520-pz1b7
Calico CNI deleting device in netns /proc/115577/ns/net
E1220 15:42:09.401448    1396 cni.go:278] Error deleting network: failed to Statfs "/proc/115577/ns/net": no such file or directory
E1220 15:42:09.554117    1396 remote_runtime.go:109] StopPodSandbox "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "my-cron-123-1513784520-pz1b7_mynamespace" network: failed to Statfs "/proc/115577/ns/net": no such file or directory
E1220 15:42:09.554162    1396 kuberuntime_manager.go:784] Failed to stop sandbox {"docker" "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
E1220 15:42:09.554192    1396 kubelet_pods.go:920] Failed killing the pod "my-cron-123-1513784520-pz1b7": failed to "KillPodSandbox" for "52d9b9b4-e59c-11e7-b6c8-005056ae60f5" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"my-cron-123-1513784520-pz1b7_mynamespace\" network: failed to Statfs \"/proc/115577/ns/net\": no such file or directory"
W1220 15:42:10.108168    1396 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "my-cron-123-1513784520-pz1b7_mynamespace": Cannot find the network namespace, skipping pod network status for container {"docker" "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
I1220 15:42:10.112898    1396 kubelet.go:1842] SyncLoop (PLEG): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)", event: &pleg.PodLifecycleEvent{ID:"52d9b9b4-e59c-11e7-b6c8-005056ae60f5", Type:"ContainerDied", Data:"159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
W1220 15:42:10.112936    1396 pod_container_deletor.go:77] Container "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e" not found in pod's containers
I1220 15:42:11.125066    1396 kubelet_pods.go:917] Killing unwanted pod "my-cron-123-1513784520-pz1b7"
W1220 15:42:11.127222    1396 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "my-cron-123-1513784520-pz1b7_mynamespace": Cannot find the network namespace, skipping pod network status for container {"docker" "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
time="2017-12-20T15:42:11Z" level=info msg="Extracted identifiers" Node=knode7 Orchestrator=k8s Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:11Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:42:11Z" level=warning msg="WorkloadEndpoint does not exist in the datastore, moving forward with the clean up" Workload=mynamespace.my-cron-123-1513784520-pz1b7 WorkloadEndpoint={{<nil>} eth0 mynamespace.my-cron-123-1513784520-pz1b7 k8s knode7  map[]}
time="2017-12-20T15:42:11Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:42:11Z" level=info msg="Releasing address using workloadID" Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:11Z" level=info msg="Releasing all IPs with handle 'mynamespace.my-cron-123-1513784520-pz1b7'"
time="2017-12-20T15:42:11Z" level=warning msg="Asked to release address but it doesn't exist. Ignoring" Workload=mynamespace.my-cron-123-1513784520-pz1b7 workloadId=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:42:11Z" level=info msg="Teardown processing complete." Workload=mynamespace.my-cron-123-1513784520-pz1b7 endpoint=<nil>
E1220 15:44:07.063669    1396 kubelet.go:1549] Unable to mount volumes for pod "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)": timeout expired waiting for volumes to attach/mount for pod "mynamespace"/"my-cron-123-1513784520-pz1b7". list of unattached/unmounted volumes=[etc-ssh configmap-mount default-token-wphxs]; skipping pod
E1220 15:44:07.063698    1396 pod_workers.go:182] Error syncing pod 52d9b9b4-e59c-11e7-b6c8-005056ae60f5 ("my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)"), skipping: timeout expired waiting for volumes to attach/mount for pod "mynamespace"/"my-cron-123-1513784520-pz1b7". list of unattached/unmounted volumes=[etc-ssh configmap-mount default-token-wphxs]
I1220 15:44:14.104154    1396 kubelet.go:1824] SyncLoop (DELETE, "api"): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)"
I1220 15:44:14.110689    1396 kubelet.go:1818] SyncLoop (REMOVE, "api"): "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)"
I1220 15:44:14.110726    1396 kubelet.go:2002] Failed to delete pod "my-cron-123-1513784520-pz1b7_mynamespace(52d9b9b4-e59c-11e7-b6c8-005056ae60f5)", err: pod not found
W1220 15:45:01.989628    1396 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "my-cron-123-1513784520-pz1b7_mynamespace": Cannot find the network namespace, skipping pod network status for container {"docker" "159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e"}
time="2017-12-20T15:45:02Z" level=info msg="Extracted identifiers" Node=knode7 Orchestrator=k8s Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:45:02Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:45:02Z" level=warning msg="WorkloadEndpoint does not exist in the datastore, moving forward with the clean up" Workload=mynamespace.my-cron-123-1513784520-pz1b7 WorkloadEndpoint={{<nil>} eth0 mynamespace.my-cron-123-1513784520-pz1b7 k8s knode7  map[]}
time="2017-12-20T15:45:02Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HYPERKUBE_IMAGE=myregistry:5000/hyperkube:v1.6.8 PAUSE_IMAGE=myregistry:5000/pause:3.0 API_ENDPOINT=1.2.3.4 CADVISOR_PORT=4194 KUBE_API_SECURE_PORT=6443 KUBE_CONFIG=kubeconfig KUBELET_PORT=10250 LOGLEVEL=2 POD_MANIFEST_DIR=/etc/kubernetes/manifests SELF_HOSTNAME=knode7 CNI_COMMAND=DEL CNI_CONTAINERID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=mynamespace;K8S_POD_NAME=my-cron-123-1513784520-pz1b7;K8S_POD_INFRA_CONTAINER_ID=159b8a23dccc9a3e8747309b4ba0e968493cc216197dc44046ff0e688989074e CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=http://127.0.0.1:4001 KUBECONFIG=kubeconfig]"
time="2017-12-20T15:45:02Z" level=info msg="Releasing address using workloadID" Workload=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:45:02Z" level=info msg="Releasing all IPs with handle 'mynamespace.my-cron-123-1513784520-pz1b7'"
time="2017-12-20T15:45:02Z" level=warning msg="Asked to release address but it doesn't exist. Ignoring" Workload=mynamespace.my-cron-123-1513784520-pz1b7 workloadId=mynamespace.my-cron-123-1513784520-pz1b7
time="2017-12-20T15:45:02Z" level=info msg="Teardown processing complete." Workload=mynamespace.my-cron-123-1513784520-pz1b7 endpoint=<nil>
```

Controller manager for the pod:
```
I1220 15:42:02.588094       1 event.go:217] Event(v1.ObjectReference{Kind:"Job", Namespace:"mynamespace", Name:"my-cron-123-1513784520", UID:"52d4c52e-e59c-11e7-b6c8-005056ae60f5", APIVersion:"batch", ResourceVersion:"104511222", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: my-cron-123-1513784520-pz1b7
I1220 15:44:14.091244       1 cronjob_controller.go:370] CronJob controller is deleting Pod mynamespace/my-cron-123-1513784520-pz1b7
```

Scheduler for the pod:
```
I1220 15:42:02.630681       1 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"mynamespace", Name:"my-cron-123-1513784520-pz1b7", UID:"52d9b9b4-e59c-11e7-b6c8-005056ae60f5", APIVersion:"v1", ResourceVersion:"104511225", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned my-cron-123-1513784520-pz1b7 to knode7
```

Cron yaml:
```
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl create --kubeconfig=kubeconfig --namespace=mynamespace --filename=mytemplate.yaml --record=true
  creationTimestamp: 2017-12-12T22:28:54Z
  labels:
    name: my-cron
    version: 123
  name: my-cron-123
  namespace: mynamespace 
  resourceVersion: "104537731"
  selfLink: /apis/batch/v2alpha1/namespaces/mynamespace/cronjobs/my-cron-123 
  uid: d63bdd94-df8b-11e7-a687-005056ae60f5
spec:
  concurrencyPolicy: Forbid 
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: hosting_platform
            name: my-cron
            version: 123
        spec:
          containers:
          - command:
            - task.py
            image: myregistry:5000/mycronimage:tag
            imagePullPolicy: IfNotPresent
            livenessProbe:
              exec:
                command: 
                - /control-scripts/livenessCheck.sh
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 1
            name: my-cron
            resources:
              limits:
                cpu: 1500m
                memory: 250Mi
              requests:
                cpu: 500m
                memory: 150Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /tmp/ssh
              name: etc-ssh
            - mountPath: /configs
              name: configmap-mount
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /etc/ssh
            name: etc-ssh
          - configMap:
              defaultMode: 420
              items: ...
              name: 1ed50810899225c2955984cc360e87dd
            name: configmap-mount
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 2
  suspend: false
status:       
  lastScheduleTime: 2017-12-20T17:36:00Z
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:12:08Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.8", GitCommit:"d74e09bb4e4e7026f45becbed8310665ddcb8514", GitTreeState:"clean", BuildDate:"2017-08-03T18:01:01Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): 16.04.1 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-89-generic #112-Ubuntu
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
The pod may not get deleted completely at the first time. Such `no such file or directory` error should be ignored for retry logic.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57465

**Special notes for your reviewer**:
/cc @kubernetes/sig-network-misc 

**Release note**:

```release-note
ignore nonexistent ns net file error when deleting container network in case a retry
```

### CODE REVIEW

**Comment by yujuhong** [comment]
@kubernetes/sig-network-misc

File: pkg/kubelet/network/cni/cni.go [hunk 1]
```diff
@@ -273,7 +273,7 @@ func (plugin *cniNetworkPlugin) deleteFromNetwork(network *cniNetwork, podName s
 	netConf, cniNet := network.NetworkConfig, network.CNIConfig
 	glog.V(4).Infof("About to del CNI network %v (type=%v)", netConf.Name, netConf.Plugins[0].Network.Type)
 	err = cniNet.DelNetworkList(netConf, rt)
-	if err != nil {
+	if err != nil && !strings.Contains(err.Error(), "no such file or directory") {
```
Comment (thockin) [inline pkg/kubelet/network/cni/cni.go]: PLEASE PLEASE comment why this is acceptable.

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 2]
```diff
@@ -765,7 +765,7 @@ func (plugin *kubenetNetworkPlugin) delContainerFromNetwork(config *libcni.Netwo
 	}
 
 	glog.V(3).Infof("Removing %s/%s from '%s' with CNI '%s' plugin and runtime: %+v", namespace, name, config.Network.Name, config.Network.Type, rt)
-	if err := plugin.cniConfig.DelNetwork(config, rt); err != nil {
+	if err := plugin.cniConfig.DelNetwork(config, rt); err != nil && !strings.Contains(err.Error(), "no such file or directory") {
```
Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: Same as above - this NEEDS a comment.

File: pkg/kubelet/network/cni/cni.go (hunk 1 above)
Comment (dixudx) [reply pkg/kubelet/network/cni/cni.go]: @thockin Addressed. PTAL. Thanks.
