### PR TITLE
Fix PodTopologySpread matching pods counts for constraints with the same topologyKey

### LINKED ISSUE #129067: PodTopologySpread plugin with multiple constraints with the same topology key incorrectly counts matching pods on node
### What happened?

In PodTopologySpread PreFilter, while processing the nodes, their count is not aggregated, but overwritten by the last constraint with the same topologyKey:
https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L276-L285

Probably, PreScore counting is also wrong, as it probably duplicate the pods:
https://github.com/kubernetes/kubernetes/blob/810e9e212ec5372d16b655f57b9231d8654a2179/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L164-L180

### What did you expect to happen?

`countPodsMatchSelector` should process all constraints per topologyKey at once to aggregate, but not duplicate the counts for pods on node.

### How can we reproduce it (as minimally and precisely as possible)?

I found the issue refactoring the plugin's code, but probably unexpected behavior of topology spreading will happen when defining multiple topology spread constraints with the same topologyKey on a single pod.

### Anything else we need to know?

/sig scheduling
/assign

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It is allowed to create a pod with constraints that share the same topologyKey, but the code didn't fully support this. In particular, in some places it assumed that the topologyKey was unique among constraints and was able to overwrite the results of one constraint with the results of another. This PR makes the PodTopologySpread plugin's data structures indexed by the constraint, isolating them.

Additionally, it was easier to make the change by replacing map to slice in PreFilter when iterating through nodes (like in #129025 which will be closed eventually). 

Fix does not affect scheduling throughput of PodTopologySpread plugin. Replacing map to slice increases the scheduling throughput of pods with topology spreading by up to **25%**.

scheduler_perf benchmarks (local):
Benchmark | Before [pods/s avg] | After [pods/s avg]
--- | --- | ---
TopologySpreading/5000Nodes | 223 | 269

#### Which issue(s) this PR fixes:

Fixes #129067

#### Special notes for your reviewer:

I added new test cases that would not have passed before this fix.

#### Does this PR introduce a user-facing change?

```release-note
Improved scheduling performance of pods with required topology spreading.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
@dom4ha @AxeZhan can either of you take a first reviewing path?

**Comment by sanposhiho** [comment]
@macsko the release note is missing.

**Comment by AxeZhan** [comment]
/lgtm
Both implementation and tests look good to me.

**Comment by macsko** [comment]
> @macsko the release note is missing.

Done

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go [hunk 1]
```diff
@@ -37,8 +37,9 @@ type preScoreState struct {
 	Constraints []topologySpreadConstraint
 	// IgnoredNodes is a set of node names which miss some Constraints[*].topologyKey.
 	IgnoredNodes sets.Set[string]
-	// TopologyPairToPodCounts is keyed with topologyPair, and valued with the number of matching pods.
-	TopologyPairToPodCounts map[topologyPair]*int64
+	// TopologyValueToPodCounts is a slice indexed by constraint index.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring.go:40]: Fix comment below, which still refers to 'TopologyPairToPodCounts'

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go [hunk 2]
```diff
@@ -161,17 +165,17 @@ func (pl *PodTopologySpread) PreScore(
 			return
 		}
 
-		for _, c := range state.Constraints {
+		for j, c := range state.Constraints {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring.go:168]: same here; if 'i' is renamed to 'n', then 'i' could be used here consistently.

**Review by dom4ha — COMMENTED** [review]
Only nits

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go (hunk 1 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring.go:40]: I think the comment is correct

**Review by dom4ha — COMMENTED** [review]
/lgtm

**Comment by sanposhiho** [comment]
@macsko Please change the release note a bit to mention that it happens when two constraints are the same topology key, _but with the different label selector._  We don't see a bug on just two constraints with the same topology key and with the same label selector (right?).

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering.go [hunk 3]
```diff
@@ -31,37 +32,31 @@ import (
...
+	TpValueToMatchNum []map[string]int
 }
 
 // minMatchNum returns the global minimum for the calculation of skew while taking MinDomains into account.
-func (s *preFilterState) minMatchNum(tpKey string, minDomains int32) (int, error) {
-	paths, ok := s.TpKeyToCriticalPaths[tpKey]
-	if !ok {
-		return 0, fmt.Errorf("failed to retrieve path by topology key")
-	}
+func (s *preFilterState) minMatchNum(constraintID int, minDomains int32) (int, error) {
```
Comment (sanposhiho) [inline pkg/scheduler/framework/plugins/podtopologyspread/filtering.go:55]: This comment is not a PR blocker, but a further discussion that can be a follow-up.
So, when I looked at this, I first noticed that it looked like we can cache `minMatchNum` result because we now have a map per constraint. (TpValueToMatchNum)

And, that led me to a further idea, should we pre-calculate and filter a result per topology value per constraint? 
I mean, we now almost pre-calculate all the Filter() results per domain/constraint, why not we don't pre-calculate all like:

```go
type preFilterState struct {
  // ToValueToFilterResult has a pre-calculated filter result. 
  // It's a slice indexed by constraint index, and map is keyed with topology value and valued with the filtering result.
  ToValueToFilterResult []map[string]bool
}

func (pl *PodTopologySpread) Filter(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {

...

	for i, c := range s.Constraints {
		tpKey := c.TopologyKey
		tpVal, ok := node.Labels[c.TopologyKey]
		if !ok {
			logger.V(5).Info("Node doesn't have required label", "node", klog.KObj(node), "label", tpKey)
			return framework.NewStatus(framework.UnschedulableAndUnresolvable, ErrReasonNodeLabelNotMatch)
		}

		if !c.ToValueToFilterResult[i][tpVal] {
			return framework.NewStatus(framework.UnschedulableAndUnresolvable, ErrReasonConstraintsNotMatch)
		}
	}

	return nil
}
```

What do you think?

**Review by sanposhiho — APPROVED** [review]
Looks awesome. I left one comment for a further improvement.

/approve
/lgtm

**Comment by sanposhiho** [comment]
@kubernetes/sig-scheduling-leads Should we cherry-pick it or not? We found this bug on our own ([ref](https://github.com/kubernetes/kubernetes/pull/129025#discussion_r1864096185)), not a user report.

**Comment by alculquicondor** [comment]
I think validation would prevent this
https://github.com/kubernetes/api/blob/9603cdf39dd3adb19382c6832da8f79ab1548d8c/core/v1/types.go#L4003-L4004

**Comment by sanposhiho** [comment]
Whoa!

**Comment by alculquicondor** [comment]
Please double check the validation code, as I'm not sure if apiserver does validation for the schema automatically.

**Comment by sanposhiho** [comment]
✅ 

```
sanposhiho@Kenseis-MacBook-Pro kube-scheduler-simulator % cat pod.yaml             

kind: Pod
apiVersion: v1
metadata:
  name: mypod2
  labels:
    foo: bar
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.1

sanposhiho@Kenseis-MacBook-Pro kube-scheduler-simulator % kubectl apply -f pod.yaml   
The Pod "mypod2" is invalid: spec.topologySpreadConstraints[0].{topologyKey, whenUnsatisfiable}: Duplicate value: "{zone, DoNotSchedule}"
```

**Comment by Huang-Wei** [comment]
> It is allowed to create a pod with constraints that share the same topologyKey

@macsko This statement doesn't seem right. Each spread constraint is guaranteed to have different {TopologyKey, WhenUnsatisfiable} tuple:

https://github.com/kubernetes/kubernetes/blob/6746df77f2376c6bc1fd0de767d2a94e6bd6cec1/pkg/apis/core/validation/validation.go#L7840-L7841

https://github.com/kubernetes/kubernetes/blob/6746df77f2376c6bc1fd0de767d2a94e6bd6cec1/pkg/apis/core/validation/validation.go#L7900-L7910

**Comment by alculquicondor** [comment]
If it's a feature, it should probably have a release note. The note can focus on the performance improvement.

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering.go (hunk 3 above)
Comment (sanposhiho) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering.go:55]: @macsko @dom4ha thoughts?

Comment (macsko) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering.go:55]: I think we can. It won't give us noticeable speedup, but will simplify the Filter code a bit.

Comment (sanposhiho) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering.go:55]: Hmm, right. I missed that point. Okay, then let's just leave it as it is for now. We can revisit this idea if needed.
