### PR TITLE
Fix image inspection and matching

### LINKED ISSUE #30710: failed to pull image
I cannot create pod. `kubectl describe pod` shows the following error
```bash
 18m		2m		8	{kubelet rootfs-dev}	spec.containers{web}	Normal		Pulling		pulling image "kubernetes/pause"
  18m		2m		8	{kubelet rootfs-dev}	spec.containers{web}	Warning		Failed		Failed to pull image "kubernetes/pause": image pull failed for unknown error
  18m		2m		8	{kubelet rootfs-dev}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "web" with ErrImagePull: "image pull failed for unknown error"

  18m	12s	73	{kubelet rootfs-dev}	spec.containers{web}	Normal	BackOff		Back-off pulling image "kubernetes/pause"
  18m	12s	73	{kubelet rootfs-dev}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "web" with ImagePullBackOff: "Back-off pulling image \"kubernetes/pause\""
```

`kubelet.log` shows the following message
```text
I0816 20:28:50.953268   46840 kube_docker_client.go:298] Stop pulling image "kubernetes/pause:latest": ""
I0816 20:28:50.954275   46840 docker.go:196] Inspected image ("c80eebea8921a5e97f82fcf60da84f4de6399b9fc0ba683ceff67cd0dd319644") does not match kubernetes/pause:latest
E0816 20:28:50.954352   46840 docker_manager.go:2196] container start failed: ErrImagePull: image pull failed for unknown error
E0816 20:28:50.954462   46840 pod_workers.go:184] Error syncing pod b7f4fd2e-63ef-11e6-b8e8-000d3a12e034, skipping: failed to "StartContainer" for "web" with ErrImagePull: "image pull failed for unknown error"
I0816 20:28:50.954517   46840 server.go:679] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nfs-web-xs364", UID:"b7f4fd2e-63ef-11e6-b8e8-000d3a12e034", APIVersion:"v1", ResourceVersion:"577", FieldPath:"spec.containers{web}"}): type: 'Warning' reason: 'Failed' Failed to pull image "kubernetes/pause": image pull failed for unknown error
I0816 20:28:50.954547   46840 server.go:679] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nfs-web-xs364", UID:"b7f4fd2e-63ef-11e6-b8e8-000d3a12e034", APIVersion:"v1", ResourceVersion:"577", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "web" with ErrImagePull: "image pull failed for unknown error"
```

Tracing back to the source, the newly added image check function from 875fd16e1e1958b95ab96c4c9c9f672817bb9cfe prints the message

@kubernetes/sig-node @dims

### PR DESCRIPTION
**Pull request by yujuhong**
An image string could contain a hostname (e.g., "docker.io") or not. The same
applies to the RepoTags returned from an image inspection. To determine whether
the image docker pulled matches what the user ask for, we check if the either
string is the suffix of the other.

/cc @dims @dchen1107 @Random-Liu

This fixes #30710

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30789)

### CODE REVIEW

**Comment by yujuhong** [comment]
By the way, the `SplitHostname` logic is flawed, so I didn't use it. For example, with an image string `kubernetes/pause:latest`, `SplitHostname` will return `kubernetes` as the hostname, and `pause` as the rest of the name. What we really want for it is to return no hostname in this case.

**Comment by yujuhong** [comment]
@Random-Liu care to review?

**Comment by Random-Liu** [comment]
@yujuhong Reviewing~ :)

File: pkg/kubelet/dockertools/docker_test.go [hunk 1]
```diff
@@ -184,6 +184,12 @@ func TestMatchImageTagOrSHA(t *testing.T) {
 			Output:    true,
 		},
 		{
+			Inspected: dockertypes.ImageInspect{RepoTags: []string{"docker.io/kubernetes/pause:latest"}},
+			Image:     "kubernetes/pause:latest",
+			Output:    true,
+		},
+
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/docker_test.go]: Extra space.

**Comment by Random-Liu** [comment]
LGTM with one nit.

File: pkg/kubelet/dockertools/docker_test.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker_test.go]: Done!

**Comment by dims** [comment]
LGTM 👍

**Comment by yujuhong** [comment]
Bug fix. Needs to get in 1.4.

**Comment by dchen1107** [comment]
LGTM. Thanks for fixing.

File: pkg/kubelet/dockertools/docker.go [hunk 2]
```diff
@@ -166,24 +166,19 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
...
-
-			} else {
-				if tag == image {
-					// We found a specific tag that we were looking for
-					return true
-				}
+			// An image name (without the tag/digest) can be [hostname '/'] component ['/' component]*
+			// Because either the RepoTag or the name *may* contain the
+			// hostname or not, we only check for the suffix match.
+			if strings.HasSuffix(image, tag) || strings.HasSuffix(tag, image) {
```
Comment (lavalamp) [inline pkg/kubelet/dockertools/docker.go]: Sorry for the drive by, I'm looking for things to add retest-not-required to...

but won't this give false positives? like "docker.io/foobar/myimage:1" and "bar/myimage:1" probably shouldn't match but I think they will with this code?

Comment (yujuhong) [inline pkg/kubelet/dockertools/docker.go]: Yes, they will. Docker allows users to specify an image string without the registry name (i.e., the hostname in the comment), and supplies a default registry (`docker.io`) in this case. The same applies to tagging the image. Therefore, both the image and the tag could contain the registry or not, and that's why I use the suffix check.

One way to make this more resilient is probably hard-code the default docker registry in kubelet for comparison, I entertained the idea but didn't like it too much. If you think that makes more sense, I can change this PR to do that. By the way, this is a sanity check after docker supposedly pulled the image. If the image doesn't exist, kubelet wouldn't be able to create the container whether the check passes or not.
