### PR TITLE
fix master service endpoint system for multiple masters

### LINKED ISSUE #6572: Provide an option on the apiserver to specify apiserver address for services
Trying to load-balance apiservers through an external proxy/load-balancer results in the apiservers having a war trying to set the endpoint address for the kubernetes and kubernetes-ro services.  We need to be able to specify what the endpoint address should be for these services.

### PR DESCRIPTION
**Pull request by lavalamp**
Closes #6572.

@thockin I can't see any reason why the old system won't still work?

### CODE REVIEW

**Comment by lavalamp** [comment]
Also, @davidopp

File: pkg/master/publish.go [hunk 1]
```diff
@@ -147,11 +151,53 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+			Addresses: []api.EndpointAddress{{IP: ip.String()}},
+			Ports:     []api.EndpointPort{{Port: port, Protocol: api.ProtocolTCP}},
+		}}
+		glog.Infof("Resetting endpoints for master service %q to %v", serviceName, e)
+		return m.endpointRegistry.UpdateEndpoints(ctx, e)
+	} else if !foundIP {
+		// So we *always* add our own IP address to the end, and if
+		// there are too many IP addresses, we remove from the
+		// beginning. Given the requirements stated at the top of this
+		// function, this should cause the list of IP addresses to
```
Comment (thockin) [inline pkg/master/publish.go]: Address structures are sorted by IP - what am I missing?  I guess it could NOT sort, but that would potentially trigger false updates.

Why not just detect that you have too many and remove one at random.  That should still converge, no?

File: pkg/master/publish.go [hunk 2]
```diff
@@ -128,15 +127,20 @@ func (m *Master) createMasterServiceIfNeeded(serviceName string, serviceIP net.I
...
+// requirements and the body of this function.
+//
+// Requirements:
+//  * All apiservers MUST use the same ports for their {rw, ro} services.
+//  * All apiservers MUST use setEndpoints and only setEndpoints to manage the
+//      endpoints for their {rw, ro} services.
+//  * All apiservers MUST know and agree on the number of apiservers expected
+//      to be running (m.masterCount).
+//  * setEndpoints is called periodically from all apiservers.
+//
```
Comment (davidopp) [inline pkg/master/publish.go]: The first sentence of your comment ("setEndpoint sets...") makes this function sound like it is generic, while the Requirements section makes it clear that really this is only for registering the apiserver services. Can you add that caveat to the first paragraph as well, so people who aren't paying close attention don't get confused and think this should be used for other services?

File: pkg/master/publish.go (hunk 1 above)
Comment (lavalamp) [inline pkg/master/publish.go]: We sort by IP? Why? What component does that?

Comment (lavalamp) [inline pkg/master/publish.go]: I will make it sort and then delete the address(es) that come after it's own address. I think that has faster convergence properties than deleting a random one.

Comment (thockin) [inline pkg/master/publish.go]: The sorting is done in the RepackSubsets function.

File: pkg/master/publish.go (hunk 2 above)
Comment (lavalamp) [inline pkg/master/publish.go]: first line changed.

**Comment by lavalamp** [comment]
Comments addressed, PTAL

File: pkg/master/publish.go [hunk 3]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+		}}
+		glog.Infof("Resetting endpoints for master service %q to %v", serviceName, e)
+		return m.endpointRegistry.UpdateEndpoints(ctx, e)
+	} else if !ipCorrect {
+		// So we *always* add our own IP address; if there are too many
+		// IP addresses, we remove the one lexicographically after our
+		// own IP address.  Given the requirements stated at the top of
+		// this function, this should cause the list of IP addresses to
+		// become eventually correct.
+		e.Subsets[0].Addresses = append(e.Subsets[0].Addresses, api.EndpointAddress{IP: ip.String()})
```
Comment (thockin) [inline pkg/master/publish.go]: This does not seem to verify that the ports are the same.  You could sort of get that for free by appending a whole subset (port and addr) here, then calling RepackSubsets().  If that result does not pass checkEndpointSubsetFormat() LOG something scary..

Just an idea

File: pkg/master/publish.go [hunk 4]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+		e.Subsets = endpoints.RepackSubsets(e.Subsets)
+		addrs := &e.Subsets[0].Addresses
+		for i, addr := range *addrs {
```
Comment (thockin) [inline pkg/master/publish.go]: It's minor, but this will make copies of every address struct.  I've gotten into the habit (as suggested by r) to do

```
for i := range *addrs {
    addr := &(*addrs)[i]
    //...
}

Comment (thockin) [inline pkg/master/publish.go]: wrap this loop with a test for len > masterCount?

File: pkg/master/publish.go [hunk 5]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+		return m.endpointRegistry.UpdateEndpoints(ctx, e)
+	} else if !ipCorrect {
+		// So we *always* add our own IP address; if there are too many
+		// IP addresses, we remove the one lexicographically after our
+		// own IP address.  Given the requirements stated at the top of
+		// this function, this should cause the list of IP addresses to
+		// become eventually correct.
+		e.Subsets[0].Addresses = append(e.Subsets[0].Addresses, api.EndpointAddress{IP: ip.String()})
+		e.Subsets = endpoints.RepackSubsets(e.Subsets)
+		addrs := &e.Subsets[0].Addresses
```
Comment (thockin) [inline pkg/master/publish.go]: Subsets.Addresses is a slice - no need to take a pointer to it.

Comment (thockin) [inline pkg/master/publish.go]: unless you plan to mutate it through that pointer, as you do later.  NM.  Maybe a comment?

File: pkg/master/publish.go [hunk 6]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+		for i, addr := range *addrs {
+			if addr.IP == ip.String() {
+				for len(*addrs) > m.masterCount {
+					remove := (i + 1) % len(*addrs)
+					*addrs = append((*addrs)[:remove], (*addrs)[remove+1:]...)
```
Comment (thockin) [inline pkg/master/publish.go]: This appears to offer an out-of-bounds access.  Consider len() == 4, i = 2.  remove = 3%4 = 3.  remove+1 is OOB.

File: pkg/master/publish.go (hunk 3 above)
Comment (thockin) [inline pkg/master/publish.go]: NM you do checkport

File: pkg/master/publish.go [hunk 7]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+	// First, determine if the endpoint is in the format we expect (one
+	// subset, one port, N IP addresses).
+	formatCorrect, ipCorrect := m.checkEndpointSubsetFormat(e, ip.String(), port)
+	if !formatCorrect {
+		// Something is egregiously wrong, just re-make the endpoints record.
+		e.Subsets = []api.EndpointSubset{{
+			Addresses: []api.EndpointAddress{{IP: ip.String()}},
+			Ports:     []api.EndpointPort{{Port: port, Protocol: api.ProtocolTCP}},
+		}}
+		glog.Infof("Resetting endpoints for master service %q to %v", serviceName, e)
```
Comment (davidopp) [inline pkg/master/publish.go]: Warning instead of Info?

File: pkg/master/publish.go [hunk 8]
```diff
@@ -147,11 +152,61 @@ func (m *Master) setEndpoints(serviceName string, ip net.IP, port int) error {
...
+		return m.endpointRegistry.UpdateEndpoints(ctx, e)
+	} else if !ipCorrect {
+		// So we *always* add our own IP address; if there are too many
```
Comment (davidopp) [inline pkg/master/publish.go]: The "So" is extraneous

File: pkg/master/publish.go (hunk 4 above)
Comment (lavalamp) [inline pkg/master/publish.go]: Meh, the struct is like two words, it's hard for me to get excited about not copying it. Two word copy vs an indirection everywhere is not even a clear victory for the latter. That pattern is really only useful when you're worried about a reference escaping the loop.

File: pkg/master/publish.go (hunk 6 above)
Comment (lavalamp) [inline pkg/master/publish.go]: Nope... Try it out: http://play.golang.org/p/ZUDCPg_h5D

Also if you look at my test cases you'll see I already added one that exercises that condition...

**Comment by lavalamp** [comment]
Comments disputed or addressed :) PTAL

File: pkg/master/publish.go (hunk 6 above)
Comment (thockin) [inline pkg/master/publish.go]: interesting...

**Comment by thockin** [comment]
LGTM

File: pkg/master/publish.go (hunk 6 above)
Comment (davidopp) [inline pkg/master/publish.go]: I didn't understand a couple of things:
* what is the motivation for the policy "remove the one lexicographically after our own IP address" as opposed to removing a random one? please mention in comment.
* to address Tim's comment and make the code more understandable, I'd suggest setting "remove" like this:
```
remove := i+1
if (remove == len(*addrs)) remove = 0
```

Comment (davidopp) [inline pkg/master/publish.go]: Never mind my comment above.

**Comment by davidopp** [comment]
LGTM

**Comment by lavalamp** [comment]
Shippable is a flake; I can haz merge?
