### PR TITLE
Follow-up of #71136: Switch system priority class usage to versioned (v1) api

### LINKED ISSUE #84246: kube-apiserver fails to start if scheduling.k8s.io/v1beta1 is disabled
1. Run the apiserver with `--runtime-config=scheduling.k8s.io/v1beta1=false`
2. View the log

```
I1023 11:50:17.991961   69307 httplog.go:90] GET /apis/scheduling.k8s.io/v1beta1/priorityclasses/system-node-critical: (301.559µs) 404 [kube-apiserver/v1.17.0 (darwin/amd64) kubernetes/20870f5 127.0.0.1:65027]
I1023 11:50:17.992656   69307 httplog.go:90] POST /apis/scheduling.k8s.io/v1beta1/priorityclasses: (239.11µs) 404 [kube-apiserver/v1.17.0 (darwin/amd64) kubernetes/20870f5 127.0.0.1:65027]
I1023 11:50:17.992759   69307 httplog.go:90] GET /api/v1/namespaces/kube-system: (1.097959ms) 200 [kube-apiserver/v1.17.0 (darwin/amd64) kubernetes/20870f5 127.0.0.1:65027]
I1023 11:50:17.992805   69307 httplog.go:90] GET /apis/rbac.authorization.k8s.io/v1/clusterroles: (1.115336ms) 200 [kube-apiserver/v1.17.0 (darwin/amd64) kubernetes/20870f5 127.0.0.1:65027]
F1023 11:50:17.992836   69307 hooks.go:202] PostStartHook "scheduling/bootstrap-system-priority-classes" failed: unable to add default system priority classes: the server could not find the requested resource
```

/sig scheduling
/milestone v1.17

xref https://github.com/kubernetes/enhancements/pull/1332

Fixed by https://github.com/kubernetes/kubernetes/pull/76362

### PR DESCRIPTION
**Pull request by yue9944882**
/kind cleanup
/cc @liggitt

Fixes https://github.com/kubernetes/kubernetes/issues/84246

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/apis/scheduling/v1/helpers.go [hunk 1]
```diff
@@ -0,0 +1,66 @@
+/*
```
Comment (liggitt) [inline pkg/apis/scheduling/v1/helpers.go]: can we remove the pkg/apis/scheduling/helpers.go file?

**Comment by liggitt** [comment]
one comment on removing the internal-typed helpers.go file, lgtm otherwise

cc @bsalamat @kubernetes/sig-scheduling-pr-reviews

File: pkg/apis/scheduling/v1/helpers.go (hunk 1 above)
Comment (yue9944882) [reply pkg/apis/scheduling/v1/helpers.go]: we're still using the helper funcs in the validation here: 

https://github.com/kubernetes/kubernetes/blob/ef830e2bcf7a23a0ae74e8d8b9e8811a83142f38/pkg/apis/scheduling/validation/validation.go#L37-L39

removing the file will make us do a explicit conversion to v1 api here which looks a bit odd to me. wdyt?

Comment (liggitt) [reply pkg/apis/scheduling/v1/helpers.go]: no conversion needed, that method is checking name (string), value (int), and default (bool) matches

**Comment by ravisantoshgudimetla** [comment]
Thanks for the PR @yue9944882. 

I am ok with helpers too but I will wait for Bobby to give his review.

/cc @bsalamat 

/approve

**Comment by yue9944882** [comment]
thanks @ravisantoshgudimetla , ping @bsalamat for review

File: pkg/apis/scheduling/v1/helpers.go [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+Copyright 2018 The Kubernetes Authors.
```
Comment (bsalamat) [inline pkg/apis/scheduling/v1/helpers.go]: 2019

File: staging/src/k8s.io/api/scheduling/v1alpha1/types.go [hunk 3]
```diff
@@ -20,6 +20,27 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+const (
```
Comment (bsalamat) [inline staging/src/k8s.io/api/scheduling/v1alpha1/types.go]: Do we need these consts in v1alpha1 and v1beta1?

Comment (yue9944882) [reply staging/src/k8s.io/api/scheduling/v1alpha1/types.go]: i removed them all from the external apis. now there's no copy of these consts.

**Comment by liggitt** [comment]
can we remove the SystemPriorityClasses() function from pkg/apis/scheduling/helpers.go and switch all usage to the v1 version?

**Comment by yue9944882** [comment]
@liggitt now i switched the helpers to v1 completely and removed the internal ones. but there's still usage of internal helpers left in the priority class validation, i switched them too, not sure if it looks good.

https://github.com/kubernetes/kubernetes/blob/1409ff38e5828f55bf0e57fa32f93f6ef5b63a25/pkg/apis/scheduling/validation/validation.go#L37

File: pkg/apis/scheduling/v1/helpers.go [hunk 4]
```diff
@@ -1,5 +1,5 @@
 /*
-Copyright 2018 The Kubernetes Authors.
+Copyright 2019 The Kubernetes Authors.
```
Comment (bsalamat) [inline pkg/apis/scheduling/v1/helpers.go]: Do we need to change the copyright year?

File: pkg/apis/scheduling/v1/helpers.go [hunk 5]
```diff
@@ -14,43 +14,62 @@ See the License for the specific language governing permissions and
...
+			}
+			return true, nil
+		}
+	}
+	return false, fmt.Errorf("%v is not a known system priority class", pc.Name)
+}
+
+// IsKnownSystemInternalPriorityClass checks that "pc" is equal to one of the system PriorityClasses.
+// It ignores "description", labels, annotations, etc. of the PriorityClass.
+func IsKnownSystemInternalPriorityClass(pc *scheduling.PriorityClass) (bool, error) {
```
Comment (bsalamat) [inline pkg/apis/scheduling/v1/helpers.go]: Why do we need to distinguish "internal" from other system priority classes?

File: pkg/apis/scheduling/v1/helpers.go (hunk 4 above)
Comment (yue9944882) [reply pkg/apis/scheduling/v1/helpers.go]: mmm am not sure, actually i was copy-pasting the versioned apis to a new pkg but the github insists it's a renaming 🤷🏻‍♂️

File: pkg/apis/scheduling/v1/helpers.go (hunk 5 above)
Comment (yue9944882) [reply pkg/apis/scheduling/v1/helpers.go]: it's the validation of priority-class using the internal helpers so we can't completely strip this.

Comment (bsalamat) [reply pkg/apis/scheduling/v1/helpers.go]: I am not sure if I understand what problem you are trying to solve here. It looks like `IsKnownSystemPriorityClass` is no longer used. Couldn't have we made the necessary changes to  `IsKnownSystemPriorityClass` and not added `IsKnownSystemInternalPriorityClass`?

Comment (yue9944882) [reply pkg/apis/scheduling/v1/helpers.go]: the both is being used. i'm trying to avoid doing explicit conversion between internal types and versioned types. 

`IsKnownSystemPriorityClass` is in the post-start-hook, and `IsKnownSystemInternalPriorityClass` is in the validation [https://github.com/kubernetes/kubernetes/blob/eaf89cfbb483f99411141f70c294e8a014e49cec/pkg/apis/scheduling/validation/validation.go#L37](https://github.com/kubernetes/kubernetes/blob/eaf89cfbb483f99411141f70c294e8a014e49cec/pkg/apis/scheduling/validation/validation.go#L37)

Comment (liggitt) [reply pkg/apis/scheduling/v1/helpers.go]: Alternately, make IsKnownSystemPriorityClass take the name, value, globalDefault and preemptionPolicy fields as parameters, rather than the entire object. Then both callers can collapse onto a single method

**Comment by liggitt** [comment]
This is needed to allow the API server to start with the beta API version turned off

**Comment by ahg-g** [comment]
This may have broke scheduler_perf:

ahg@ahg1:~/go/src/k8s.io/kubernetes$ make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -bench=BenchmarkScheduling/5000Nodes/1000Pods -cpuprofile cpu.out" &> /tmp/test

```
make[1]: *** No rule to make target '/usr/local/google/home/ahg/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/apis/scheduling/helpers.go', needed by 'pkg/apis/scheduling/zz_generated.deepcopy.go'.  Stop.
make: *** [Makefile:559: generated_files] Error 2

```

**Comment by liggitt** [comment]
I cannot reproduce on master with a clean checkout:

```
$ git show
commit 5238e1c80fea02891e1804b346d24faa7c13da07 (HEAD -> master, upstream/master, upstream/HEAD, origin/master)
Merge: 31b7e3d9053 09cf42d67c0

$ make clean

$ make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-alsologtostderr=false -logtostderr=false -run=^$$ -bench=None -cpuprofile cpu.out"
```

> ```
> +++ [1024 08:52:18] Building go targets for darwin/amd64:
>     ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
> +++ [1024 08:52:30] Building go targets for darwin/amd64:
>     ./vendor/k8s.io/code-generator/cmd/defaulter-gen
> +++ [1024 08:52:38] Building go targets for darwin/amd64:
>     ./vendor/k8s.io/code-generator/cmd/conversion-gen
> +++ [1024 08:52:52] Building go targets for darwin/amd64:
>     ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
> +++ [1024 08:53:06] Building go targets for darwin/amd64:
>     ./vendor/github.com/go-bindata/go-bindata/go-bindata
> +++ [1024 08:53:08] Checking etcd is on PATH
> /Users/liggitt/go/src/k8s.io/kubernetes/third_party/etcd/etcd
> +++ [1024 08:53:08] Starting etcd instance
> etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /var/folders/h8/3dzrjpfj76d93vbhc5f2r8tw00kjgb/T/tmp.22gcXzY5 --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
> Waiting for etcd to come up.
> +++ [1024 08:53:09] On try 1, etcd: : http://127.0.0.1:2379
> {"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
> +++ [1024 08:53:09] Running integration test cases
> ```

**Comment by ahg-g** [comment]
Thanks Jordan, doing ```make clean``` solved the issue for me.

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. Code freeze is Nov. 18th. Will this PR be merged by then? If not, can we move it out of the milestone?
