### PR TITLE
DRA kubelet: avoid deadlock when gRPC connection to driver goes idle

### LINKED ISSUE #133920: Regression 1.34 -- Kubelet requires restart after gRPC connection to DRA driver goes idle
## Steps to reproduce

* Install the NVIDIA DRA driver for GPUs

```shell
helm install nvidia-dra-driver-gpu deployments/helm/nvidia-dra-driver-gpu \
    --create-namespace \
    --namespace nvidia-dra-driver-gpu \
    --set nvidiaDriverRoot=/run/nvidia/driver \
    --set gpuResourcesEnabledOverride=true
```

* Run a workload

```shell
kubectl apply -f demo/specs/imex/mn-channel-injection.yaml
```

* See the relevant pods running

```shell
$ kubectl get pod -A
...
default                 mn-imex-channel-injection-57b546bc47-6mngm                    1/1     Running     0             7s
default                 mn-imex-channel-injection-57b546bc47-96nqm                    1/1     Running     0             7s
default                 mn-imex-channel-injection-57b546bc47-s6jwt                    1/1     Running     0             7s
nvidia-dra-driver-gpu   imex-channel-injection-62rcp-5dwcr                            1/1     Running     0             6s
nvidia-dra-driver-gpu   imex-channel-injection-62rcp-9mdhf                            1/1     Running     0             6s
nvidia-dra-driver-gpu   imex-channel-injection-62rcp-c8jxb                            1/1     Running     0             6s
```

* Wait for a long time (not sure how long but I waited around 2 hours) and delete the workload

```shell
kubectl delete -f demo/specs/imex/mn-channel-injection.yaml
```

* Workload stuck in the terminating state forever

```shell
$ kubectl get pod -A
...
   default                 mn-imex-channel-injection-57b546bc47-2tpxk                    1/1     Terminating   0             125m
default                 mn-imex-channel-injection-57b546bc47-cjl85                    1/1     Terminating   0             125m
default                 mn-imex-channel-injection-57b546bc47-xj8zs                    1/1     Terminating   0             125m
nvidia-dra-driver-gpu   imex-channel-injection-szkpc-qrhkb                            1/1     Terminating   0             125m
nvidia-dra-driver-gpu   imex-channel-injection-szkpc-qtkn2                            1/1     Terminating   0             125m
nvidia-dra-driver-gpu   imex-channel-injection-szkpc-tsmml                            1/1     Terminating   0             125m
```

* Observe DRA driver still healthy

```shell
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-controller-7c74cfc844-bkgxr             1/1     Running       0             14h
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-kubelet-plugin-l9sb6                    2/2     Running       0             3h8m
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-kubelet-plugin-qkzx4                    2/2     Running       0             3h9m
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-kubelet-plugin-spxfn                    2/2     Running       0             3h8m
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-webhook-56f486fdbc-9blwb                1/1     Running       0             14h
nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-webhook-56f486fdbc-p97nd                1/1     Running       0             14h
```

* DRA driver logs don’t show any incoming `NodeUnprepareResources()` calls

```shell
$ kubectl logs -n nvidia-dra-driver-gpu   nvidia-dra-driver-gpu-kubelet-plugin-l9sb6
                                                                                    ...
```

* However the kubelet logs show the following lines around the time the workload was deleted

```shell

-- Workload pod
               Sep 06 04:41:10 gb-nvl-043-compute04 kubelet[2245881]: I0906 04:41:10.227717 2245881 dra_plugin_manager.go:295] "Preferring connected plugin" logger="DRA registration handler" driverName="compute-domain.nvidia.com" endpoint="/var/lib/kubelet/plugins/compute-domain.nvidia.com/dra.sock"
Sep 06 04:41:10 gb-nvl-043-compute04 kubelet[2245881]: I0906 04:41:10.227738 2245881 dra_plugin.go:173] "Calling NodeUnprepareResource rpc" request="&NodeUnprepareResourcesRequest{Claims:[]*Claim{&Claim{Namespace:default,UID:670dc9f1-4bee-463a-b2ec-fecf07b5a1fb,Name:mn-imex-channel-injection-57b546bc47-xj8zs-imex-channel-ndhtz,},},}"

-- IMEX Daemon pod
                  Sep 06 04:41:14 gb-nvl-043-compute04 kubelet[2245881]: I0906 04:41:14.573225 2245881 dra_plugin_manager.go:295] "Preferring connected plugin" logger="DRA registration handler" driverName="compute-domain.nvidia.com" endpoint="/var/lib/kubelet/plugins/compute-domain.nvidia.com/dra.sock"
                                                                                                                 Sep 06 04:41:14 gb-nvl-043-compute04 kubelet[2245881]: I0906 04:41:14.573239 2245881 dra_plugin.go:173] "Calling NodeUnprepareResource rpc" request="&NodeUnprepareResourcesRequest{Claims:[]*Claim{&Claim{Namespace:nvidia-dra-driver-gpu,UID:5cb193b8-4ad4-4821-b841-fa3ada037b9b,Name:imex-channel-injection-szkpc-tsmml-compute-domain-daemon-sgvz8,},},}"
```

* With *no* matching log lines similar to the following (from a different, successful iteration of this call)

```shell
Sep 05 06:33:57 gb-nvl-043-compute02 kubelet[1739058]: I0905 06:33:57.933433 1739058 dra_plugin.go:194] "Done calling NodeUnprepareResources rpc" driverName="compute-domain.nvidia.com" endpoint="/var/lib/kubelet/plugins/compute-domain.nvidia.com/dra.sock" response="&NodeUnprepareResourcesResponse{Claims:map[string]*NodeUnprepareResourceResponse{f627927a-b39a-4fd1-9f0d-0f2851a015ce: &NodeUnprepareResourceResponse{Error:,},},}" err=null
```

* Relevant code snippet from [here](https://github.com/kubernetes/kubernetes/blob/d9b31d602d833b8a45b31f720eed4534c769772b/pkg/kubelet/cm/dra/plugin/dra_plugin.go#L167)

```go
func (p *DRAPlugin) NodeUnprepareResources(
    ctx context.Context,
    req *drapbv1.NodeUnprepareResourcesRequest,
    opts ...grpc.CallOption,
) (*drapbv1.NodeUnprepareResourcesResponse, error) {
    logger := klog.FromContext(ctx)
    logger.V(4).Info("Calling NodeUnprepareResource rpc", "request", req)
    logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
    ctx = klog.NewContext(ctx, logger)

    ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
    defer cancel()

    var err error
    var response *drapbv1.NodeUnprepareResourcesResponse
    switch p.chosenService {
    case drapbv1beta1.DRAPluginService:
        client := drapbv1beta1.NewDRAPluginClient(p.conn)
        response, err = drapbv1beta1.V1Beta1ClientWrapper{DRAPluginClient: client}.NodeUnprepareResources(ctx, req)
    case drapbv1.DRAPluginService:
        client := drapbv1.NewDRAPluginClient(p.conn)
        response, err = client.NodeUnprepareResources(ctx, req)
    default:
        // Shouldn't happen, validateSupportedServices should only
        // return services we support here.
        return nil, fmt.Errorf("internal error: unsupported chosen service: %q", p.chosenService)
    }
    logger.V(4).Info("Done calling NodeUnprepareResources rpc", "response", response, "err", err)
    return response, err
}
```

It should not be possible for the first log line to be called without the second.

It suggests the call to `client.NodeUnprepareResources(ctx, req)` never returns (despite the context with the timeout). Note that the call into `client.NodeUnprepareResources()` is into the *generated* PB code (which feels unlikely to be incorrect). We also *never* see `"internal error: unsupported chosen service"` anywhere in the logs.

Not sure how this is possible or what is going on here.

The only way to recover from this is to trigger a kubelet restart.

Once the kubelet is restarted, it rediscovers the DRA driver and issues a `NodeUnprepareResources()`, which the DRA driver receives and carries out the deletion.

## Reproducibility

After a bunch of the remediation attempts listed below, I zeroed in on the fact that this issue happens when the gRPC connection goes into the Idle state. In the original code I would have to wait up 30 minutes to see the issue (because the default idle timeout is 30min). However, if I tweak `WithIdleTimeout` to 1 minute I am able to trigger the issue much more quickly. This suggests, the issue truly is related to the connection going idle, and I now have way to run with a smaller debug loop.

```go
       target := "unix:" + p.endpoint
       logger.V(4).Info("Creating new gRPC connection", "target", target)
       conn, err := grpc.NewClient(
               target,
               grpc.WithTransportCredentials(insecure.NewCredentials()),
               grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
               grpc.WithStatsHandler(mp),
+              grpc.WithIdleTimeout(time.Minute),
       )
       if err != nil {
               return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
       }
```

## Remediation attempts

* Add a fallback timeout that waits twice as long as the original timeout. In a normal operating state, it should **never** get called because it gets canceled if this function ever ends (which should happen if either the call completed or the original timeout was reached). Unfortunately, I see it get triggered, suggesting that we truly are hung in the `client.NodePrepareResources()` call. We also still never see the call ever complete, suggesting that my manual calls to `conn.Close()` and `cancel()` when the fallback timeout expires don’t trigger the hang to unblock.

```go
func (p *DRAPlugin) NodeUnprepareResources(
        ctx context.Context,
        req *drapbv1.NodeUnprepareResourcesRequest,
        opts ...grpc.CallOption,
) (*drapbv1.NodeUnprepareResourcesResponse, error) {
        logger := klog.FromContext(ctx)
        logger.V(4).Info("Calling NodeUnprepareResource rpc", "request", req)
        logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
        ctx = klog.NewContext(ctx, logger)

        // Force the gRPC connection to be reestablished if necessary
        conn, err := p.getOrCreateGRPCConn()
        if err != nil {
                return nil, err
        }

        // Start the gRPC call with a timeout
        ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
        defer cancel()

        // Force close the plugin connection if the underlying gRPC call hangs.
        // Wait twice the length of a p.clientCallTimeout.
        fallbackCtx, fallbackCancel := context.WithTimeout(ctx, 2*p.clientCallTimeout)
        defer fallbackCancel()

        go func() {
                <-fallbackCtx.Done()
                if fallbackCtx.Err() == context.DeadlineExceeded {
                        logger.V(4).Info("Force closing plugin connection due to hanging rpc", "plugin", p.driverName, "request", req)
                        conn.Close()
                        cancel()
                }
        }()

        var err error
        var response *drapbv1.NodeUnprepareResourcesResponse
        switch p.chosenService {
        case drapbv1beta1.DRAPluginService:
                client := drapbv1beta1.NewDRAPluginClient(p.conn)
                logger.V(4).Info("Calling NodeUnprepareResources from V1Beta1Client")
                response, err = drapbv1beta1.V1Beta1ClientWrapper{DRAPluginClient: client}.NodeUnprepareResources(ctx, req)
        case drapbv1.DRAPluginService:
                client := drapbv1.NewDRAPluginClient(p.conn)
                logger.V(4).Info("Calling NodeUnprepareResources from V1Client")
                response, err = client.NodeUnprepareResources(ctx, req)
        default:
                // Shouldn't happen, validateSupportedServices should only
                // return services we support here.
                return nil, fmt.Errorf("internal error: unsupported chosen service: %q", p.chosenService)
        }
        logger.V(4).Info("Done calling NodeUnprepareResources rpc", "response", response, "err", err)
        return response, err
}
```

* Add a keepalive to the gRPC connection created for the client. I was hoping this would trigger the connection to stay alive so that it never gets a chance to hang. This did not help though, and we see the same issue.

```go
        logger.V(4).Info("Creating new gRPC connection", "target", target)
        conn, err := grpc.NewClient(
                target,
                grpc.WithTransportCredentials(insecure.NewCredentials()),
                grpc.WithChainUnaryInterceptor(newMetricsInterceptor(driverName)),
                grpc.WithStatsHandler(mp),
                grpc.WithKeepaliveParams(keepalive.ClientParameters{
                        Time:                30 * time.Second, // Send keepalive pings every 30 seconds
                        Timeout:             5 * time.Second,  // Wait 5 seconds for ping ack
                        PermitWithoutStream: true,             // Send pings even when no active RPCs
                }),
        )
```

* Enable the `ResourceHealthStatus` feature gate. This feature gate is designed to keep the connection alive. It continuously validates the gRPC connection is working and automatically retries stream connection every 5 seconds if it fails. **This fixed the problem(\!)**, but at the cost of having to enable an alpha feature gate. We need something that can be added to the existing code without a feature gate.

```go
        ResourceHealthStatus: {
                {Version: version.MustParse("1.31"), Default: true, PreRelease: featuregate.Alpha},
        },
```

* Force a new connection at the top of every call to `NodePrepareResources` / `NodeUnprepareResources` whenever we detect that the existing connection is unhealthy. This also does not fix the issue, unfortunately. My call to `reconnect()` is never triggered, meaning the state changes I check never happen. I know this because the log within the reconnect call does not appear in the kubelet logs.

```go
diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin.go b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
index 1529bdcc3af..95c2f65d4fe 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
@@ -68,6 +68,8 @@ type DRAPlugin struct {
 	healthClient       drahealthv1alpha1.DRAResourceHealthClient
 	healthStreamCtx    context.Context
 	healthStreamCancel context.CancelFunc
+
+	reconnect func() error
 }

 func (p *DRAPlugin) getOrCreateGRPCConn() (*grpc.ClientConn, error) {
@@ -143,6 +145,17 @@ func (p *DRAPlugin) NodePrepareResources(
 	ctx = klog.NewContext(ctx, logger)
 	logger.V(4).Info("Calling NodePrepareResources rpc", "request", req)

+	// Force the gRPC connection to be reestablished if necessary
+	state := p.conn.GetState()
+	if state == connectivity.Shutdown || state == connectivity.TransientFailure {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

@@ -174,6 +187,17 @@ func (p *DRAPlugin) NodeUnprepareResources(
 	logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
 	ctx = klog.NewContext(ctx, logger)

+	// Force the gRPC connection to be reestablished if necessary
+	state := p.conn.GetState()
+	if state == connectivity.Shutdown || state == connectivity.TransientFailure {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
index 2b76d3bd348..0ef95cf2b2c 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
@@ -359,18 +359,24 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 	}

 	// The gRPC connection gets created once. gRPC then connects to the gRPC server on demand.
-       target := "unix:" + endpoint
-       logger.V(4).Info("Creating new gRPC connection", "target", target)
-       conn, err := grpc.NewClient(
-               target,
-               grpc.WithTransportCredentials(insecure.NewCredentials()),
-               grpc.WithChainUnaryInterceptor(newMetricsInterceptor(driverName)),
-               grpc.WithStatsHandler(mp),
-       )
-       if err != nil {
-               return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", driverName, endpoint, err)
+       p.reconnect = func() error {
+               target := "unix:" + p.endpoint
+               logger.V(4).Info("Creating new gRPC connection", "target", target)
+               conn, err := grpc.NewClient(
+                       target,
+                       grpc.WithTransportCredentials(insecure.NewCredentials()),
+                       grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
+                       grpc.WithStatsHandler(mp),
+               )
+               if err != nil {
+                       return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
+               }
+
+               // Ensure that gRPC tries to connect even if we don't call any gRPC method.
+               // This is necessary to detect early whether a plugin is really available.
+               // This is currently an experimental gRPC method. Should it be removed we
+               // would need to do something else, like sending a fake gRPC method call.
+               conn.Connect()
+
+               p.conn = conn
+               return nil
+       }
+       if err := p.reconnect(); err != nil {
+               return err
        }
-       p.conn = conn

        if utilfeature.DefaultFeatureGate.Enabled(features.ResourceHealthStatus) {
                pm.wg.Add(1)
@@ -396,12 +409,6 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
                }()
        }

-       // Ensure that gRPC tries to connect even if we don't call any gRPC method.
-       // This is necessary to detect early whether a plugin is really available.
-       // This is currently an experimental gRPC method. Should it be removed we
-       // would need to do something else, like sending a fake gRPC method call.
-       conn.Connect()
-
        pm.store[p.driverName] = append(pm.store[p.driverName], mp)
        logger.V(3).Info("Registered DRA plugin", "driverName", p.driverName, "endpoint", p.endpoint, "chosenService", p.chosenService, "numPlugins", len(pm.store[p.driverName]))
        pm.sync(p.driverName)
```

* Nuclear option – always establish a new connection for every call to `NodePrepareResources` / `NodeUnprepareResources`. **This resolves the issue\!**
  However, it comes at the cost of establishing a brand new gRPC connection every single time we make a call to `NodePrepareResources` / `NodeUnprepareResources`. It makes me wonder if we can get away with just calling `conn.Connect()` in these calls to kick the gRPC connection back to life.

```go
diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin.go b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
index 1529bdcc3af..e7fbf492b38 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
@@ -68,6 +68,8 @@ type DRAPlugin struct {
 	healthClient       drahealthv1alpha1.DRAResourceHealthClient
 	healthStreamCtx    context.Context
 	healthStreamCancel context.CancelFunc
+
+	reconnect func() error
 }

 func (p *DRAPlugin) getOrCreateGRPCConn() (*grpc.ClientConn, error) {
@@ -143,6 +145,14 @@ func (p *DRAPlugin) NodePrepareResources(
 	ctx = klog.NewContext(ctx, logger)
 	logger.V(4).Info("Calling NodePrepareResources rpc", "request", req)

+	// Force the gRPC connection to be reestablished
+	p.mutex.Lock()
+	if err := p.reconnect(); err != nil {
+		p.mutex.Unlock()
+		return nil, err
+	}
+	p.mutex.Unlock()
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

@@ -174,6 +184,14 @@ func (p *DRAPlugin) NodeUnprepareResources(
 	logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
 	ctx = klog.NewContext(ctx, logger)

+	// Force the gRPC connection to be reestablished
+	p.mutex.Lock()
+	if err := p.reconnect(); err != nil {
+		p.mutex.Unlock()
+		return nil, err
+	}
+	p.mutex.Unlock()
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
index 2b76d3bd348..176357be56e 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
@@ -359,18 +359,31 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 	}

 	// The gRPC connection gets created once. gRPC then connects to the gRPC server on demand.
-	target := "unix:" + endpoint
-	logger.V(4).Info("Creating new gRPC connection", "target", target)
-	conn, err := grpc.NewClient(
-		target,
-		grpc.WithTransportCredentials(insecure.NewCredentials()),
-		grpc.WithChainUnaryInterceptor(newMetricsInterceptor(driverName)),
-		grpc.WithStatsHandler(mp),
-	)
-	if err != nil {
-		return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", driverName, endpoint, err)
+	p.reconnect = func() error {
+		target := "unix:" + p.endpoint
+		logger.V(4).Info("Creating new gRPC connection", "target", target)
+		conn, err := grpc.NewClient(
+			target,
+			grpc.WithTransportCredentials(insecure.NewCredentials()),
+			grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
+			grpc.WithStatsHandler(mp),
+		)
+		if err != nil {
+			return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
+		}
+
+		// Ensure that gRPC tries to connect even if we don't call any gRPC method.
+		// This is necessary to detect early whether a plugin is really available.
+		// This is currently an experimental gRPC method. Should it be removed we
+		// would need to do something else, like sending a fake gRPC method call.
+		conn.Connect()
+
+		p.conn = conn
+		return nil
+	}
+	if err := p.reconnect(); err != nil {
+		return err
 	}
-	p.conn = conn

 	if utilfeature.DefaultFeatureGate.Enabled(features.ResourceHealthStatus) {
 		pm.wg.Add(1)
@@ -396,12 +409,6 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 		}()
 	}

-	// Ensure that gRPC tries to connect even if we don't call any gRPC method.
-	// This is necessary to detect early whether a plugin is really available.
-	// This is currently an experimental gRPC method. Should it be removed we
-	// would need to do something else, like sending a fake gRPC method call.
-	conn.Connect()
-
 	pm.store[p.driverName] = append(pm.store[p.driverName], mp)
 	logger.V(3).Info("Registered DRA plugin", "driverName", p.driverName, "endpoint", p.endpoint, "chosenService", p.chosenService, "numPlugins", len(pm.store[p.driverName]))
 	pm.sync(p.driverName)
```

* Call `conn.Connect()` at the top of every call to `NodePrepareResources` / `NodeUnprepareResources`. Unfortunately, this doesn’t work on its own. The only thing that has worked so far is the recreation of a new connection on each RPC attempt. Next, I will do something similar to the last iteration, but only reconnect when the connection is in a non-READY state.

```go
diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin.go b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
index 1529bdcc3af..f30a500cc4e 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
@@ -143,6 +143,10 @@ func (p *DRAPlugin) NodePrepareResources(
        ctx = klog.NewContext(ctx, logger)
        logger.V(4).Info("Calling NodePrepareResources rpc", "request", req)

+       // Kick the gRPC connection to reconnect in cases where all of its
+       // subchannels have gone idle.
+       p.conn.Connect()
+
        ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
        defer cancel()

@@ -174,6 +178,10 @@ func (p *DRAPlugin) NodeUnprepareResources(
        logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
        ctx = klog.NewContext(ctx, logger)

+       // Kick the gRPC connection to reconnect in cases where all of its
+       // subchannels have gone idle.
+       p.conn.Connect()
+
        ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
        defer cancel()
```

* Do the same as above where we force a new connection at the top of every call to `NodePrepareResources` / `NodeUnprepareResources` whenever we detect that the existing connection is unhealthy.  However, detection of “unhealthy” is now determined as `state != connectivity.Ready`. Note, we also force old connections to be closed (but don’t wait for them), which was missing from the code above. **This resolves the issue\!**

```go
diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin.go b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
index 1529bdcc3af..969a4e131f8 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
@@ -68,6 +68,8 @@ type DRAPlugin struct {
 	healthClient       drahealthv1alpha1.DRAResourceHealthClient
 	healthStreamCtx    context.Context
 	healthStreamCancel context.CancelFunc
+
+	reconnect func() error
 }

 func (p *DRAPlugin) getOrCreateGRPCConn() (*grpc.ClientConn, error) {
@@ -143,6 +145,18 @@ func (p *DRAPlugin) NodePrepareResources(
 	ctx = klog.NewContext(ctx, logger)
 	logger.V(4).Info("Calling NodePrepareResources rpc", "request", req)

+	// Create a new gRPC connection cases where it has become non-READY
+	state := p.conn.GetState()
+	logger.V(4).Info("Plugin connection state", "state", state)
+	if state != connectivity.Ready {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

@@ -174,6 +188,18 @@ func (p *DRAPlugin) NodeUnprepareResources(
 	logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
 	ctx = klog.NewContext(ctx, logger)

+	// Create a new gRPC connection cases where it has become non-READY
+	state := p.conn.GetState()
+	logger.V(4).Info("Plugin connection state", "state", state)
+	if state != connectivity.Ready {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
index 2b76d3bd348..1bca9ce6599 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
@@ -358,19 +358,41 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 		pm:        pm,
 	}

-	// The gRPC connection gets created once. gRPC then connects to the gRPC server on demand.
-	target := "unix:" + endpoint
-	logger.V(4).Info("Creating new gRPC connection", "target", target)
-	conn, err := grpc.NewClient(
-		target,
-		grpc.WithTransportCredentials(insecure.NewCredentials()),
-		grpc.WithChainUnaryInterceptor(newMetricsInterceptor(driverName)),
-		grpc.WithStatsHandler(mp),
-	)
-	if err != nil {
-		return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", driverName, endpoint, err)
+	// The gRPC connection gets created once. gRPC then connects to the
+	// gRPC server on demand. We wrap the call in a reconnect() function to
+	// allow us to reestablish the connection if / when necessary.
+	p.reconnect = func() error {
+		// Close any existing connection
+		if p.conn != nil {
+			go p.conn.Close()
+		}
+
+		// Create the new connection
+		target := "unix:" + p.endpoint
+		logger.V(4).Info("Creating new gRPC connection", "target", target)
+		conn, err := grpc.NewClient(
+			target,
+			grpc.WithTransportCredentials(insecure.NewCredentials()),
+			grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
+			grpc.WithStatsHandler(mp),
+		)
+		if err != nil {
+			return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
+		}
+
+		// Ensure that gRPC tries to connect even if we don't call any gRPC method.
+		// This is necessary to detect early whether a plugin is really available.
+		// This is currently an experimental gRPC method. Should it be removed we
+		// would need to do something else, like sending a fake gRPC method call.
+		conn.Connect()
+
+		p.conn = conn
+		return nil
+	}
+	if err := p.reconnect(); err != nil {
+		return err
 	}
-	p.conn = conn

 	if utilfeature.DefaultFeatureGate.Enabled(features.ResourceHealthStatus) {
 		pm.wg.Add(1)
@@ -396,12 +418,6 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 		}()
 	}

-	// Ensure that gRPC tries to connect even if we don't call any gRPC method.
-	// This is necessary to detect early whether a plugin is really available.
-	// This is currently an experimental gRPC method. Should it be removed we
-	// would need to do something else, like sending a fake gRPC method call.
-	conn.Connect()
-
 	pm.store[p.driverName] = append(pm.store[p.driverName], mp)
 	logger.V(3).Info("Registered DRA plugin", "driverName", p.driverName, "endpoint", p.endpoint, "chosenService", p.chosenService, "numPlugins", len(pm.store[p.driverName]))
 	pm.sync(p.driverName)
```

* Set an idle timeout of 0\. According to the [gRPC docs](https://pkg.go.dev/google.golang.org/grpc#WithIdleTimeout), this should cause the open gRPC channel to never transition to idle. **This also fixes the issue\!**, but I’m not sure if I trust it, and would probably err on the side of what’s above to reestablish a new connection if it is not in the `Ready` state. Maybe a combination of both.

```go
       target := "unix:" + p.endpoint
       logger.V(4).Info("Creating new gRPC connection", "target", target)
       conn, err := grpc.NewClient(
               target,
               grpc.WithTransportCredentials(insecure.NewCredentials()),
               grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
               grpc.WithStatsHandler(mp),
+              grpc.WithIdleTimeout(0),
       )
       if err != nil {
               return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
       }
```

So with all of this discussion in mind, my proposal for a final fix for this issue is the following (i.e. a combination of the last 2 working solutions):

```go
diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin.go b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
index 1529bdcc3af..969a4e131f8 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin.go
@@ -68,6 +68,8 @@ type DRAPlugin struct {
 	healthClient       drahealthv1alpha1.DRAResourceHealthClient
 	healthStreamCtx    context.Context
 	healthStreamCancel context.CancelFunc
+
+	reconnect func() error
 }

 func (p *DRAPlugin) getOrCreateGRPCConn() (*grpc.ClientConn, error) {
@@ -143,6 +145,18 @@ func (p *DRAPlugin) NodePrepareResources(
 	ctx = klog.NewContext(ctx, logger)
 	logger.V(4).Info("Calling NodePrepareResources rpc", "request", req)

+	// Create a new gRPC connection cases where it has become non-READY
+	state := p.conn.GetState()
+	logger.V(4).Info("Plugin connection state", "state", state)
+	if state != connectivity.Ready {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

@@ -174,6 +188,18 @@ func (p *DRAPlugin) NodeUnprepareResources(
 	logger = klog.LoggerWithValues(logger, "driverName", p.driverName, "endpoint", p.endpoint)
 	ctx = klog.NewContext(ctx, logger)

+	// Create a new gRPC connection cases where it has become non-READY
+	state := p.conn.GetState()
+	logger.V(4).Info("Plugin connection state", "state", state)
+	if state != connectivity.Ready {
+		p.mutex.Lock()
+		if err := p.reconnect(); err != nil {
+			p.mutex.Unlock()
+			return nil, err
+		}
+		p.mutex.Unlock()
+	}
+
 	ctx, cancel := context.WithTimeout(ctx, p.clientCallTimeout)
 	defer cancel()

diff --git a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
index 2b76d3bd348..b104b1e92b3 100644
--- a/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
+++ b/pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go
@@ -358,19 +358,41 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 		pm:        pm,
 	}

-	// The gRPC connection gets created once. gRPC then connects to the gRPC server on demand.
-	target := "unix:" + endpoint
-	logger.V(4).Info("Creating new gRPC connection", "target", target)
-	conn, err := grpc.NewClient(
-		target,
-		grpc.WithTransportCredentials(insecure.NewCredentials()),
-		grpc.WithChainUnaryInterceptor(newMetricsInterceptor(driverName)),
-		grpc.WithStatsHandler(mp),
-	)
-	if err != nil {
-		return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", driverName, endpoint, err)
+	// The gRPC connection gets created once. gRPC then connects to the
+	// gRPC server on demand. We wrap the call in a reconnect() function to
+	// allow us to reestablish the connection if / when necessary.
+	p.reconnect = func() error {
+		// Close any existing connection
+		if p.conn != nil {
+			go p.conn.Close()
+		}
+
+		// Create the new connection
+		target := "unix:" + p.endpoint
+		logger.V(4).Info("Creating new gRPC connection", "target", target)
+		conn, err := grpc.NewClient(
+			target,
+			grpc.WithTransportCredentials(insecure.NewCredentials()),
+			grpc.WithChainUnaryInterceptor(newMetricsInterceptor(p.driverName)),
+			grpc.WithStatsHandler(mp),
+			grpc.WithIdleTimeout(0),
+		)
+		if err != nil {
+			return fmt.Errorf("create gRPC connection to DRA driver %s plugin at endpoint %s: %w", p.driverName, p.endpoint, err)
+		}
+
+		// Ensure that gRPC tries to connect even if we don't call any gRPC method.
+		// This is necessary to detect early whether a plugin is really available.
+		// This is currently an experimental gRPC method. Should it be removed we
+		// would need to do something else, like sending a fake gRPC method call.
+		conn.Connect()
+
+		p.conn = conn
+		return nil
+	}
+	if err := p.reconnect(); err != nil {
+		return err
 	}
-	p.conn = conn

 	if utilfeature.DefaultFeatureGate.Enabled(features.ResourceHealthStatus) {
 		pm.wg.Add(1)
@@ -396,12 +418,6 @@ func (pm *DRAPluginManager) add(driverName string, endpoint string, chosenServic
 		}()
 	}

-	// Ensure that gRPC tries to connect even if we don't call any gRPC method.
-	// This is necessary to detect early whether a plugin is really available.
-	// This is currently an experimental gRPC method. Should it be removed we
-	// would need to do something else, like sending a fake gRPC method call.
-	conn.Connect()
-
 	pm.store[p.driverName] = append(pm.store[p.driverName], mp)
 	logger.V(3).Info("Registered DRA plugin", "driverName", p.driverName, "endpoint", p.endpoint, "chosenService", p.chosenService, "numPlugins", len(pm.store[p.driverName]))
 	pm.sync(p.driverName)
```

### What did you expect to happen?

Covered above

### How can we reproduce it (as minimally and precisely as possible)?

Covered above

### Anything else we need to know?

_No response_

### Kubernetes version

1.34

### Cloud provider

On prem

### OS version

_No response_

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When gRPC notifies the kubelet that a connection ended, the kubelet tries to reconnect because it needs to know when a DRA driver comes back. The same code gets called when a connection goes idle, by default after 30 minutes. In that and only that case the conn.Connect call deadlocks while calling into the gRPC idle manager.

This can be reproduced with a new unit test which artificially shortens the idle timeout. This fix is to move the Connect call into a goroutine because then both HandleConn and Connect can proceed. It's sufficient that Connect finishes at some point, it doesn't need to be immediately.

#### Which issue(s) this PR is related to:

Fixes: https://github.com/kubernetes/kubernetes/issues/133920

#### Special notes for your reviewer:

This is a regression, caused by adding https://github.com/kubernetes/kubernetes/pull/132058 in 1.34.

#### Does this PR introduce a user-facing change?
```release-note
kubelet: the connection to a DRA driver became unusable because of an internal deadlock when a connection was idle for 30 minutes.
```

/assign @klueska 
/cc @bart0sh

### CODE REVIEW

**Comment by bart0sh** [comment]
/triage accepted
/priority important-soon
/lgtm

/assign @klueska @SergeyKanzhelev @mrunalp 
for approval

File: pkg/kubelet/cm/dra/plugin/dra_plugin_test.go [hunk 1]
```diff
@@ -186,6 +186,44 @@ func TestGRPCConnIsReused(t *testing.T) {
...
+	draPlugins.withIdleTimeout = 5 * time.Second
+	tCtx.ExpectNoError(draPlugins.add(driverName, addr, service, defaultClientCallTimeout), "add plugin")
+	plugin, err := draPlugins.GetPlugin(driverName)
+	tCtx.ExpectNoError(err, "get plugin")
+
+	// The connection doesn't really become idle because HandleConn
+	// kicks it back to ready by calling Connect. Just sleep long
+	// enough here, the code should be reached...
+	tCtx.Log("Waiting for idle timeout...")
+	time.Sleep(2 * draPlugins.withIdleTimeout)
```
Comment (klueska) [inline pkg/kubelet/cm/dra/plugin/dra_plugin_test.go:210]: Can you add an assertion that we are in the idle state after this? Or does it make sense to avoid the sleep altogether and instead use https://pkg.go.dev/google.golang.org/grpc#ClientConn.WaitForStateChange before using https://pkg.go.dev/google.golang.org/grpc#ClientConn.GetState to assert on the Idle state?

File: pkg/kubelet/cm/dra/plugin/dra_plugin_test.go [hunk 2]
```diff
@@ -186,6 +186,44 @@ func TestGRPCConnIsReused(t *testing.T) {
...
+				Namespace: "dummy-namespace",
+				Uid:       "dummy-uid",
+				Name:      "dummy-claim",
+			},
+		},
+	}
+
+	callCtx := ktesting.WithTimeout(tCtx, 10*time.Second, "call timed out")
+	_, err = plugin.NodePrepareResources(callCtx, req)
+	tCtx.ExpectNoError(err, "NodePrepareResources")
```
Comment (klueska) [inline pkg/kubelet/cm/dra/plugin/dra_plugin_test.go:224]: Without the fix, won't this hang forever like we observed in the reported issue?  Can we do something smarter here to make sure this test exits quickly even in the face of the deadlock?

**Review by klueska — APPROVED** [review]
Small comments. Feel free to ignore if you don't think they are necessary.

File: pkg/kubelet/cm/dra/plugin/dra_plugin_test.go (hunk 1 above)
Comment (pohly) [reply pkg/kubelet/cm/dra/plugin/dra_plugin_test.go:210]: With the fix in place, the connection never stays idle long enough for the test to notice. `WaitForStateChange` might have been viable, but as this PR has merged I prefer to keep it as-is for backporting purposes.

File: pkg/kubelet/cm/dra/plugin/dra_plugin_test.go (hunk 2 above)
Comment (pohly) [reply pkg/kubelet/cm/dra/plugin/dra_plugin_test.go:224]: Yes, it'll hang until the overall unit test timeout is reached. Given that this shouldn't happen, I prefer to keep the test simple.

**Comment by pohly** [comment]
Cherry-pick is in https://github.com/kubernetes/kubernetes/pull/133934.
