### PR TITLE
Fix that PodIP field is temporarily removed for a terminal pod

### LINKED ISSUE #125370: Pod IP temporarily removed from status when pod transitions to a terminal state
### What happened?

My pod completes (success or failure). The IP temporarily is removed on one of the status updates.

### What did you expect to happen?

The IP is persistent .

### How can we reproduce it (as minimally and precisely as possible)?

Apply:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: howardjohn/shell
        command:
        - bash
        - -c
        - |
          sleep 2
          exit 0
      restartPolicy: Never
  backoffLimit: 1
```

Watch:
```shell
$ kubectl get pod -ojson -w > res
$ cat res |jq -c '.status.phase + " " +.status.podIP' -r
Pending
Pending
Pending
Running 10.244.0.6
Running 10.244.0.6
Succeeded
Succeeded 10.244.0.6
Succeeded 10.244.0.6
```

The initial 'succeeded' should have the IP still.

On older versions:
```
Pending 
Pending 
Pending 
Running 10.244.0.6
Running 10.244.0.6
Succeeded 10.244.0.6
```

### Anything else we need to know?

|Version|Status|
|-|-|
|1.22|IP retained|
|1.26|IP retained|
|1.27|IP Lost|
|1.28|IP lost|
|1.30|IP lost|

Full pod state, from 1.27:

<details>

```json
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "357",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "phase": "Pending",
        "qosClass": "BestEffort"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "362",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:19Z",
                "message": "0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..",
                "reason": "Unschedulable",
                "status": "False",
                "type": "PodScheduled"
            }
        ],
        "phase": "Pending",
        "qosClass": "BestEffort"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "420",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "phase": "Pending",
        "qosClass": "BestEffort"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "431",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "message": "containers with unready status: [pi]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "message": "containers with unready status: [pi]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "image": "howardjohn/shell",
                "imageID": "",
                "lastState": {},
                "name": "pi",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "waiting": {
                        "reason": "ContainerCreating"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Pending",
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "483",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:23Z",
                "status": "True",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:23Z",
                "status": "True",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                "image": "docker.io/howardjohn/shell:latest",
                "imageID": "docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f",
                "lastState": {},
                "name": "pi",
                "ready": true,
                "restartCount": 0,
                "started": true,
                "state": {
                    "running": {
                        "startedAt": "2024-06-06T19:34:22Z"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Running",
        "podIP": "10.244.0.2",
        "podIPs": [
            {
                "ip": "10.244.0.2"
            }
        ],
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "495",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                "image": "docker.io/howardjohn/shell:latest",
                "imageID": "docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f",
                "lastState": {},
                "name": "pi",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                        "exitCode": 0,
                        "finishedAt": "2024-06-06T19:34:24Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-06T19:34:22Z"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Running",
        "podIP": "10.244.0.2",
        "podIPs": [
            {
                "ip": "10.244.0.2"
            }
        ],
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "498",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                "image": "docker.io/howardjohn/shell:latest",
                "imageID": "docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f",
                "lastState": {},
                "name": "pi",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                        "exitCode": 0,
                        "finishedAt": "2024-06-06T19:34:24Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-06T19:34:22Z"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Succeeded",
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "finalizers": [
            "batch.kubernetes.io/job-tracking"
        ],
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "501",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                "image": "docker.io/howardjohn/shell:latest",
                "imageID": "docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f",
                "lastState": {},
                "name": "pi",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                        "exitCode": 0,
                        "finishedAt": "2024-06-06T19:34:24Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-06T19:34:22Z"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Succeeded",
        "podIP": "10.244.0.2",
        "podIPs": [
            {
                "ip": "10.244.0.2"
            }
        ],
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "creationTimestamp": "2024-06-06T19:34:19Z",
        "generateName": "pi-",
        "labels": {
            "batch.kubernetes.io/controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "batch.kubernetes.io/job-name": "pi",
            "controller-uid": "824325a8-6d11-4160-bcd7-206fe31620c3",
            "job-name": "pi"
        },
        "name": "pi-72qn6",
        "namespace": "default",
        "ownerReferences": [
            {
                "apiVersion": "batch/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "Job",
                "name": "pi",
                "uid": "824325a8-6d11-4160-bcd7-206fe31620c3"
            }
        ],
        "resourceVersion": "503",
        "uid": "6a2bd1d2-63b8-4580-8e30-adadacf5ae6d"
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "bash",
                    "-c",
                    "sleep 2\nexit 0\n"
                ],
                "image": "howardjohn/shell",
                "imagePullPolicy": "Always",
                "name": "pi",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-qlm5h",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "old-control-plane",
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 0,
        "restartPolicy": "Never",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "default",
        "serviceAccountName": "default",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "kube-api-access-qlm5h",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "reason": "PodCompleted",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:25Z",
                "reason": "PodCompleted",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2024-06-06T19:34:20Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                "image": "docker.io/howardjohn/shell:latest",
                "imageID": "docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f",
                "lastState": {},
                "name": "pi",
                "ready": false,
                "restartCount": 0,
                "started": false,
                "state": {
                    "terminated": {
                        "containerID": "containerd://5fb7d18767aa7f1057590743426cd7596ccf1c623534475885c6a630c1ddd78d",
                        "exitCode": 0,
                        "finishedAt": "2024-06-06T19:34:24Z",
                        "reason": "Completed",
                        "startedAt": "2024-06-06T19:34:22Z"
                    }
                }
            }
        ],
        "hostIP": "172.18.0.3",
        "phase": "Succeeded",
        "podIP": "10.244.0.2",
        "podIPs": [
            {
                "ip": "10.244.0.2"
            }
        ],
        "qosClass": "BestEffort",
        "startTime": "2024-06-06T19:34:20Z"
    }
}
```

</details>

Prior discussion https://github.com/kubernetes/kubernetes/issues/82268

### Kubernetes version

many, see above

### Cloud provider

Tested on kind

### OS version

Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Additionally, due to the bug there is one more unnecessary API call sent by Kubelet.

#### Which issue(s) this PR fixes:

Fixes #125370

#### Special notes for your reviewer:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: howardjohn/shell
        command:
        - bash
        - -c
        - |
          sleep 3
          exit 0
      restartPolicy: Never
  backoffLimit: 1
```

Output to `> kubectl get pod -w -ocustom-columns=NAME:.metadata.name,PHASE:.status.phase,IP:.status.podIP | ts "%Y-%m-%d %H:%M:%.S"`:
before:
```
2024-06-10 09:43:05.083475 NAME       PHASE     IP
2024-06-10 09:43:05.083657 pi-bslsx   Pending   <none>
2024-06-10 09:43:05.087107 pi-bslsx   Pending   <none>
2024-06-10 09:43:05.095358 pi-bslsx   Pending   <none>
2024-06-10 09:43:07.197929 pi-bslsx   Running   10.244.1.21
2024-06-10 09:43:10.203104 pi-bslsx   Running   10.244.1.21
2024-06-10 09:43:11.324259 pi-bslsx   Succeeded   <none>
2024-06-10 09:43:12.208545 pi-bslsx   Succeeded   10.244.1.21
2024-06-10 09:43:12.219699 pi-bslsx   Succeeded   10.244.1.21
```
after fix (note there is no extra API status update):
```
2024-06-10 09:38:16.270212 NAME       PHASE     IP
2024-06-10 09:38:16.270374 pi-xgtw6   Pending   <none>
2024-06-10 09:38:16.275953 pi-xgtw6   Pending   <none>
2024-06-10 09:38:16.283406 pi-xgtw6   Pending   <none>
2024-06-10 09:38:17.954194 pi-xgtw6   Running   10.244.1.20
2024-06-10 09:38:20.960806 pi-xgtw6   Running   10.244.1.20
2024-06-10 09:38:22.130329 pi-xgtw6   Succeeded   10.244.1.20
2024-06-10 09:38:22.974978 pi-xgtw6   Succeeded   10.244.1.20
```
Note that the last status update in both cases is the removal of the Job finalizer.

Some questions potential questions based on my priv chats:
1. why in the broken version the last status update contains the IP?
This is because the last status update is triggered by [`syncTerminatedPod`](https://github.com/kubernetes/kubernetes/blob/291378cd33cb89342fa876e201030172bb33d3b9/pkg/kubelet/kubelet.go#L2161C20-L2161C37) which generates the `apiPodStatus` based on the `podStatus` which is passed from the cache in [pod_workers](https://github.com/kubernetes/kubernetes/blob/291378cd33cb89342fa876e201030172bb33d3b9/pkg/kubelet/pod_workers.go#L1256). In contrary, the status update triggered by `syncTerminating` pods was just based on the container runtime `containerRuntime.GetPodStatus`.
2. Why does the container runtime not populate the IP information for stopped pods? 
Because of the explicit check for SANDBOX_READY [here](https://github.com/kubernetes/kubernetes/blob/291378cd33cb89342fa876e201030172bb33d3b9/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1460-L1462)
3. Why does the `podStatus` cache contains the IP information when `syncTerminatedPod` is called. Because it gets updated inside [updateCache](https://github.com/kubernetes/kubernetes/blob/dae1859c896d742de1ee60a349475f8e28b61995/pkg/kubelet/pleg/generic.go#L432). Note that, in that case we also fallback to `oldPodStatus.IP` for stopped containers, see [here](https://github.com/kubernetes/kubernetes/blob/dae1859c896d742de1ee60a349475f8e28b61995/pkg/kubelet/pleg/generic.go#L424-L426).  
4. Are there more fields that need to be copied? 
It seems not. When calling `containerRuntime.GetPodStatus` on a stopped pod all fields except for [podStatus](https://github.com/kubernetes/kubernetes/blob/dae1859c896d742de1ee60a349475f8e28b61995/pkg/kubelet/container/runtime.go#L307C3-L323) except for `IP` and `Timestamp` are returned. The `Timestamp` field seems only be used when storing in cache, see [here](https://github.com/kubernetes/kubernetes/blob/dae1859c896d742de1ee60a349475f8e28b61995/pkg/kubelet/pleg/generic.go#L478-L482), and [here](https://github.com/kubernetes/kubernetes/blob/dae1859c896d742de1ee60a349475f8e28b61995/pkg/kubelet/container/cache.go#L102-L117) . However, we don't store this status in cache.
5. Why copy the information at the `podStatus` (*kubecontainer.PodStatus) level, not at the `apiPodStatus` (v1.PodStatus) level?
Both would work, but adjusting the underlying structure is less code (single field vs two), and keeps them consistent as commented [here](https://github.com/kubernetes/kubernetes/pull/125404#discussion_r1634560821)
6. Is a more generic approach possible, rather than fixing a specific field? 
Possibly, we could fallback the IPs inside `generateAPIPodStatus` or `convertStatusToAPIStatus`, which also have access to `oldPodStatus`, containing the IPs, but this would affect many more code paths. The proposed fix is minimal to only fix the new status update introduced in https://github.com/kubernetes/kubernetes/pull/115331/: https://github.com/kubernetes/kubernetes/pull/115331/files#diff-67dd9e8f3ee257072765326cb4f242852554a2c0753563fa51e292c0a63a7b94R2022
7. Why after the fix there is one less status update? Because kubelet skips sending status update if there is no difference (skips sending patch if empty inside [PatchPodStatus](https://github.com/kubernetes/kubernetes/blob/a4b8edd0f7131f0979d1f7168de1bfa5cb838d01/pkg/kubelet/status/status_manager.go#L873)). The only difference between the 2 status updates triggered by `syncTerminatingPod` and `syncTerminatedPod` was the presence of the `IP` fields, so `syncTerminatedPod` is skipped.

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug where PodIP field is temporarily removed for a terminal pod
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @bobbypage

File: test/e2e_node/pod_ips.go [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+			pod := podClient.Create(ctx, podSpec)
+
+			ctxUntil, cancel := context.WithTimeout(ctx, f.Timeouts.PodStart)
+			defer cancel()
+
+			ginkgo.By(fmt.Sprintf("Started watch for pod (%v/%v) to enter terminal phase", pod.Namespace, pod.Name))
+			_, err = watchtools.Until(ctxUntil, podsList.ResourceVersion, w, func(event watch.Event) (bool, error) {
+				if pod, ok := event.Object.(*v1.Pod); ok {
+					found := pod.ObjectMeta.Name == podName &&
+						pod.ObjectMeta.Namespace == f.Namespace.Name
```
Comment (ffromani) [inline test/e2e_node/pod_ips.go:87]: just asking, would it make sense to match for UID?

**Review by ffromani — COMMENTED** [review]
/lgtm

/cc @aojea

**Comment by ffromani** [comment]
/hold

waiting for review from @bobbypage - feel free to remove anytime

File: test/e2e_node/pod_ips.go (hunk 1 above)
Comment (mimowo) [reply test/e2e_node/pod_ips.go:87]: I just got inspired by the test [here](https://github.com/kubernetes/kubernetes/blob/d145bf09074fcd9b884daa582e0f19f60450a39d/test/e2e_node/restart_test.go#L290-L307).

Matching by UID is pretty much equivalent to matching by name + namespace, unless the pod can be recreated. Since the test isn't using higher level controllers which could recreate the pod, I think both ways are valid.

Comment (ffromani) [reply test/e2e_node/pod_ips.go:87]: thanks, fine for me.

**Comment by mimowo** [comment]
/test pull-kubernetes-unit 
Seems like an unrelated flake in unit tests, opened issue: https://github.com/kubernetes/kubernetes/issues/125406

**Comment by bobbypage** [comment]
cc @tallclair

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -2067,11 +2067,14 @@ func (kl *Kubelet) SyncTerminatingPod(_ context.Context, pod *v1.Pod, podStatus
...
 	//  cache immediately
-	podStatus, err := kl.containerRuntime.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
+	stoppedPodStatus, err := kl.containerRuntime.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
 	if err != nil {
 		klog.ErrorS(err, "Unable to read pod status prior to final pod termination", "pod", klog.KObj(pod), "podUID", pod.UID)
 		return err
 	}
+	// Copy the IPs from the previous status, because containerRuntime.GetPodStatus
+	// only returns IPs for a running pod.
+	stoppedPodStatus.IPs = podStatus.IPs
```
Comment (aojea) [inline pkg/kubelet/kubelet.go:2077]: `podStatus` or `apiPodStatus` that is generated in  L2037?
`apiPodStatus := kl.generateAPIPodStatus(pod, podStatus, false)`

File: test/e2e_node/pod_ips.go [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+							`,
+							},
+						},
+					},
+				},
+			})
+
+			w := &cache.ListWatch{
+				WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
+					return f.ClientSet.CoreV1().Pods(f.Namespace.Name).Watch(ctx, options)
```
Comment (aojea) [inline test/e2e_node/pod_ips.go:70]: use a selector to reduce the watch to just the pod in this test

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (tallclair) [reply pkg/kubelet/kubelet.go:2077]: Doesn't really matter, the generated status is taken from the `podStatus`. Only difference is it's sorted. I guess technically using the genertade version here would make the next conversion slightly faster, but I think it's probably better to use `podStatus` since the types are the same.

File: test/e2e_node/pod_ips.go [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+	"k8s.io/kubernetes/test/e2e/framework"
+	e2epod "k8s.io/kubernetes/test/e2e/framework/pod"
+	"k8s.io/kubernetes/test/e2e/network/common"
+	imageutils "k8s.io/kubernetes/test/utils/image"
+	admissionapi "k8s.io/pod-security-admission/api"
+)
+
+var _ = common.SIGDescribe("Pod IPs", framework.WithSerial(), func() {
+	f := framework.NewDefaultFramework("pod-ips")
+	f.NamespacePodSecurityLevel = admissionapi.LevelPrivileged
```
Comment (tallclair) [inline test/e2e_node/pod_ips.go:41]: nit: looks like this can be `LevelRestricted`. You're already using the restricted pod mixin

File: test/e2e_node/pod_ips.go [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+			ctxUntil, cancel := context.WithTimeout(ctx, f.Timeouts.PodStart)
+			defer cancel()
+
+			ginkgo.By(fmt.Sprintf("Started watch for pod (%v/%v) to enter terminal phase", pod.Namespace, pod.Name))
+			_, err = watchtools.Until(ctxUntil, podsList.ResourceVersion, w, func(event watch.Event) (bool, error) {
+				if pod, ok := event.Object.(*v1.Pod); ok {
+					found := pod.ObjectMeta.Name == podName &&
+						pod.ObjectMeta.Namespace == f.Namespace.Name
+					if !found {
+						ginkgo.By(fmt.Sprintf("Observed Pod (%s/%s) in phase %v", pod.ObjectMeta.Namespace, pod.ObjectMeta.Name, pod.Status.Phase))
```
Comment (tallclair) [inline test/e2e_node/pod_ips.go:89]: This should never happen, right?
```suggestion
						ginkgo.By(fmt.Sprintf("Found unexpected Pod (%s/%s) in phase %v", pod.ObjectMeta.Namespace, pod.ObjectMeta.Name, pod.Status.Phase))
```

**Review by tallclair — COMMENTED** [review]
LGTM once the test comments are cleaned up.

File: test/e2e_node/pod_ips.go (hunk 3 above)
Comment (mimowo) [reply test/e2e_node/pod_ips.go:74]: Done, using field selector

File: test/e2e_node/pod_ips.go (hunk 5 above)
Comment (mimowo) [reply test/e2e_node/pod_ips.go]: I think it could happen before using fieldSelector, now it shouldn't. Adjusted.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (mimowo) [reply pkg/kubelet/kubelet.go:2077]: Correct, we could copy the IP both from `podStatus` or from `apiPodStatus` (both contain the IP). 

My preference for copying IP from `podStatus` is that:
1. `apiPodStatus` is derived from `podStatus` in `generateAPIPodStatus`, so adjusting the underlying structure keeps them consistent, 
2. `apiPodStatus` has two fields `IP` and `IPs` which would need both be copied, so it would be slightly more code

**Comment by mimowo** [comment]
@tallclair thanks for reviewing. I have also updated the PR description to answer some questions based on my chat with @bobbypage .

**Comment by Vyom-Yadav** [comment]
Hey @mimowo @aojea 
I see this is marked as a regression. Would this be a blocker for the upcoming `v1.31.0-alpha.2` release cut on 18th June 2024?

**Comment by aojea** [comment]
> Hey @mimowo @aojea I see this is marked as a regression. Would this be a blocker for the upcoming `v1.31.0-alpha.2` release cut on 18th June 2024?

this has been regressing since 1.27 https://github.com/kubernetes/kubernetes/issues/125370 , so it should not be a blocked IMHO

**Comment by aojea** [comment]
/approve

for the e2e test, defer to @tallclair final LGTM

**Comment by mimowo** [comment]
We synced with @bobbypage and @tallclair and discussed an alternative approach of copying the IPs inside `convertStatusToAPIStatus`, and copy from the previous pod server API status. This would work in the scenario too, but it is more code as to copy both IP and IPs fields, and do this conditionally only for terminal pods requires passing `podIsTerminal` from `generateAPIPodStatus`.

File: pkg/kubelet/kubelet.go [hunk 6]
```diff
@@ -2067,11 +2067,14 @@ func (kl *Kubelet) SyncTerminatingPod(_ context.Context, pod *v1.Pod, podStatus
 	// catch race conditions introduced by callers updating pod status out of order.
 	// TODO: have KillPod return the terminal status of stopped containers and write that into the
 	//  cache immediately
-	podStatus, err := kl.containerRuntime.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
+	stoppedPodStatus, err := kl.containerRuntime.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
 	if err != nil {
 		klog.ErrorS(err, "Unable to read pod status prior to final pod termination", "pod", klog.KObj(pod), "podUID", pod.UID)
 		return err
 	}
+	// Copy the IPs from the previous status, because containerRuntime.GetPodStatus
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet.go:2075]: I wonder if kubelet restart in a very precise moment will break this? Even if so - the chance is slim. I just wonder if this was a problem before this regression?

File: test/e2e_node/pod_ips.go [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+
+	ginkgo.Context("when pod gets terminated", func() {
+		ginkgo.It("should contain podIPs in status for terminal pod", func(ctx context.Context) {
+			podName := "pod-ips-" + string(uuid.NewUUID())
+
+			podSpec := e2epod.MustMixinRestrictedPodSecurity(&v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: podName,
+				},
+				Spec: v1.PodSpec{
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_ips.go:53]: can you please add two more tests:

1. Let the container crash instead of exiting normally. Variations may be oom kill, error in PostStart hook, and never even started because of the image pull problem. But simple crash will likely suffice.
2. Ensure PodIP is available while container is terminating (executing preStop hook). This is not affected by your change, but nice to test anyways for future regressions

**Comment by bobbypage** [comment]
LGTM, but +1 on the test suggestions that @SergeyKanzhelev mentioned

/lgtm

File: pkg/kubelet/kubelet.go (hunk 6 above)
Comment (tallclair) [reply pkg/kubelet/kubelet.go:2075]: To avoid that, we might want to update [`mergePodStatus`](https://github.com/kubernetes/kubernetes/blob/8c508c5480844682eab8a4172526b6db3476fdc0/pkg/kubelet/status/status_manager.go#L1049) to reuse the IPs from the `oldPodStatus` if:
1. `newPodStatus` is terminated
2. `newPodStatus` IPs are empty

Then we can at least make sure we're never overwriting the IPs stored in the API after a pod has terminated.

Comment (smarterclayton) [reply pkg/kubelet/kubelet.go:2075]: Can I ask a very general question?

When is the podIP "released" by the Kubelet?  

Is it when the sandbox is stopped (https://github.com/kubernetes/kubernetes/blob/9895910846eeccf0694c577ac439f492ae2dfc3c/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1374-L1375)?  Or is it later?

I'm trying to determine the earliest point during termination at which a pod is considered to not "own" that podIP, such that CNI might give out that IP to another pod (not a specific CNI provider, but any CNI provider). Once CNI might give a terminal pod's IP out to another pod is when subsequent apiserver pod status updates should no longer contain that podIP - preserving the podIP in status would *not* be desirable.

So if killPod ensures that a podIP is "released" from the perspective of CNI, then when this function exits we statusManager should consider the pod as having no IP since it is now officially "terminal" (exiting SyncTerminatingPod is a state transition for the pod worker).

Comment (aojea) [reply pkg/kubelet/kubelet.go:2075]: I don't think we should remove the PodIP from status, I'm trying to find more information from previous conversations,  but I think we concluded the expectations are that the pods keep the IP reported https://github.com/kubernetes/kubernetes/issues/109414#issuecomment-1126203054

A IP reported multiple times is not a problem, is only a problem if there are multiple Pods that are active with the same IP

File: test/e2e_node/pod_ips.go (hunk 7 above)
Comment (mimowo) [reply test/e2e_node/pod_ips.go:90]: I added two new test cases to hopefully capture the intention. They all fail on `master` and pass on the branch:

> * Let the container crash instead of exiting normally. Variations may be oom kill, error in PostStart hook, and never even started because of the image pull problem. But simple crash will likely suffice.

Here I simulate the crash by simply returning a non-zero exit code. 

I tested manually OOM (it fails on master, and works ok on the branch), and image pull issue (works ok both on master and the branch, a deleted pod transitions directly from Pending to Failed in that case).

> * Ensure PodIP is available while container is terminating (executing preStop hook). This is not affected by your change, but nice to test anyways for future regressions

Here I delete the pod to trigger the termination, and use a finalizer to be sure I can inspect the status.

File: pkg/kubelet/kubelet.go (hunk 6 above)
Comment (mimowo) [reply pkg/kubelet/kubelet.go:2080]: > I wonder if kubelet restart in a very precise moment will break this? 

I tested kubelet restart by inducing kubelet crash with a snippet like this:
```golang
   if strings.HasPrefix(pod.Name, "pod-") {
       markerFile := "/tmp/restarted"
       _, err := os.Stat(markerFile)
       if os.IsNotExist(err) {
           if file, err := os.Create(markerFile); err != nil {
               file.Close()
           }
           os.Exit(1)
       } else {
           if err := os.Remove(markerFile); err != nil {
               klog.ErrorS(err, "MYDEBUGError removign marker file", "pod", klog.KObj(pod), "podUID", pod.UID)
           }
       }
   }
```
And indeed the `PodIP` is lost if I inject it between [after killed](https://github.com/kubernetes/kubernetes/blob/e832b7023066a6f386634ad5d99e574281e1e6b4/pkg/kubelet/kubelet.go#L2064) and [before TerminatePod](https://github.com/kubernetes/kubernetes/blob/e832b7023066a6f386634ad5d99e574281e1e6b4/pkg/kubelet/kubelet.go#L2228) (it would not fail 100% of times though). 

> Even if so - the chance is slim. I just wonder if this was a problem before this regression?

Yes, I also tested on 1.26 by injecting the same snippet, and it also fails, I think with a slightly more frequently, but don't have enough repeats to be definitive about the frequency.

Comment (mimowo) [reply pkg/kubelet/kubelet.go:2080]: > To avoid that, we might want to update [`mergePodStatus`](https://github.com/kubernetes/kubernetes/blob/8c508c5480844682eab8a4172526b6db3476fdc0/pkg/kubelet/status/status_manager.go#L1049) to reuse the IPs from the `oldPodStatus` if:
> 
> 1. `newPodStatus` is terminated
> 2. `newPodStatus` IPs are empty
> 
> Then we can at least make sure we're never overwriting the IPs stored in the API after a pod has terminated.

This does not work by itself, because in that case we have one interim update when phase=Running, which clears the IP at the API server, here is the example watch output:

```
> kubectl get pods -w --output-watch-events -ocustom-columns=EVENT:.type,NAME:.object.metadata.name,IP:.object.status.podIP,PHASE:.object.status.phase,STATUS:.object.status | ts "%Y-%m-%d %H:%M:%.S"
2024-06-28 13:46:42.455092 EVENT   NAME           IP       PHASE     STATUS
2024-06-28 13:46:42.455310 ADDED   pod-pi-f4v4d   <none>   Pending   map[phase:Pending qosClass:BestEffort]
2024-06-28 13:46:42.459023 MODIFIED   pod-pi-f4v4d   <none>   Pending   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] phase:Pending qosClass:BestEffort]
2024-06-28 13:46:42.469784 MODIFIED   pod-pi-f4v4d   <none>   Pending   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:False type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z message:containers with unready status: [pi] reason:ContainersNotReady status:False type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z message:containers with unready status: [pi] reason:ContainersNotReady status:False type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[image:howardjohn/shell imageID: lastState:map[] name:pi ready:false restartCount:0 started:false state:map[waiting:map[reason:ContainerCreating]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Pending qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
2024-06-28 13:46:46.101598 MODIFIED   pod-pi-f4v4d   10.244.1.2   Running   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:46Z status:True type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:46Z status:True type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:46Z status:True type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 image:docker.io/howardjohn/shell:latest imageID:docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f lastState:map[] name:pi ready:true restartCount:0 started:true state:map[running:map[startedAt:2024-06-28T11:46:45Z]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Running podIP:10.244.1.2 podIPs:[map[ip:10.244.1.2]] qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
2024-06-28 13:46:48.106098 MODIFIED   pod-pi-f4v4d   10.244.1.2   Running   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:46Z status:True type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z reason:PodCompleted status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 image:docker.io/howardjohn/shell:latest imageID:docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f lastState:map[] name:pi ready:false restartCount:0 started:false state:map[terminated:map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 exitCode:0 finishedAt:2024-06-28T11:46:47Z reason:Completed startedAt:2024-06-28T11:46:45Z]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Running podIP:10.244.1.2 podIPs:[map[ip:10.244.1.2]] qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
2024-06-28 13:46:51.658728 MODIFIED   pod-pi-f4v4d   <none>       Running   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:51Z status:False type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z reason:PodCompleted status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 image:docker.io/howardjohn/shell:latest imageID:docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f lastState:map[] name:pi ready:false restartCount:0 started:false state:map[terminated:map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 exitCode:0 finishedAt:2024-06-28T11:46:47Z reason:Completed startedAt:2024-06-28T11:46:45Z]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Running qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
2024-06-28 13:46:52.689228 MODIFIED   pod-pi-f4v4d   <none>       Succeeded   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:51Z status:False type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z reason:PodCompleted status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 image:docker.io/howardjohn/shell:latest imageID:docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f lastState:map[] name:pi ready:false restartCount:0 started:false state:map[terminated:map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 exitCode:0 finishedAt:2024-06-28T11:46:47Z reason:Completed startedAt:2024-06-28T11:46:45Z]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Succeeded qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
2024-06-28 13:46:53.700212 MODIFIED   pod-pi-f4v4d   <none>       Succeeded   map[conditions:[map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:51Z status:False type:PodReadyToStartContainers] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z reason:PodCompleted status:True type:Initialized] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:Ready] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:48Z reason:PodCompleted status:False type:ContainersReady] map[lastProbeTime:<nil> lastTransitionTime:2024-06-28T11:46:42Z status:True type:PodScheduled]] containerStatuses:[map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 image:docker.io/howardjohn/shell:latest imageID:docker.io/howardjohn/shell@sha256:23546d7e285397394c46f44ecb503309096a24724cd1b20b841dfb49d8d6fb6f lastState:map[] name:pi ready:false restartCount:0 started:false state:map[terminated:map[containerID:containerd://7451597e9b3a1f9705ab6c87e3de2534f19ac89d21066f1c971b32b768932988 exitCode:0 finishedAt:2024-06-28T11:46:47Z reason:Completed startedAt:2024-06-28T11:46:45Z]] volumeMounts:[map[mountPath:/var/run/secrets/kubernetes.io/serviceaccount name:kube-api-access-5nnd6 readOnly:true recursiveReadOnly:Disabled]]]] hostIP:192.168.8.2 hostIPs:[map[ip:192.168.8.2]] phase:Succeeded qosClass:BestEffort startTime:2024-06-28T11:46:42Z]
```
it would work if we remove the check that `newPodStatus is terminated` but it might have negative consequences in other scenarios (not sure though).

Comment (mimowo) [reply pkg/kubelet/kubelet.go:2080]: > When is the podIP "released" by the Kubelet?
> Is it when the sandbox is stopped (
> 
https://github.com/kubernetes/kubernetes/blob/9895910846eeccf0694c577ac439f492ae2dfc3c/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1374-L1375
> )? Or is it later?

That is correct, I tested it by calling `m.runtimeService.PodSandboxStatus(ctx, podSandbox.ID.ID, false)` just before and after `m.runtimeService.StopPodSandbox` in the link. It contains the IP before, at least on containerd.

We also have this guard [here](https://github.com/kubernetes/kubernetes/blob/e832b7023066a6f386634ad5d99e574281e1e6b4/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1460) to only lookup IP is the standbox is ready, but at least from my testing it is redundant.

**Comment by mimowo** [comment]
> /hold
> 
> waiting for review from @bobbypage - feel free to remove anytime

/hold cancel
Since the pr has lgtm from @bobbypage per https://github.com/kubernetes/kubernetes/pull/125404#issuecomment-2183560459
@SergeyKanzhelev @tallclair @smarterclayton I  believe all comments are addressed either by code changes or discussion. PTAL.

File: pkg/kubelet/kubelet.go (hunk 6 above)
Comment (smarterclayton) [reply pkg/kubelet/kubelet.go:2080]: Ok.  I would prefer this happen inside a specifically named function that generically preserves data from before the pod is stopped to keep the clarity of the method high.

Comment (mimowo) [reply pkg/kubelet/kubelet.go:2080]: > Ok. I would prefer this happen inside a specifically named function that generically preserves data from before the pod is stopped to keep the clarity of the method high.

Sure, but let me clarify to make sure we are on the same page, are you suggesting to wrap just this line in a function `stoppedPodStatus.IPs = podStatus.IPs` like `restoreDataForSoppedPod`? or maybe it is better to wrap [this](https://github.com/kubernetes/kubernetes/blob/338edd427d1ff27696bfd505ee7e743854ac54f5/pkg/kubelet/kubelet.go#L2070-L2082) in `getStatusForStoppedContainer`?

Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go:2080]: explictly naming a function that preserves a field would be best from my perspective

Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go:2080]: also please add a comment to that function suggesting that kubelet restart may cause to lose those fields.

Comment (mimowo) [reply pkg/kubelet/kubelet.go]: Sure, PTAL: 66eccac7753cf08af0af1436c7f3a75048f95912.

Comment (mimowo) [reply pkg/kubelet/kubelet.go]: @smarterclayton @SergeyKanzhelev let me know if this addresses the comment: https://github.com/kubernetes/kubernetes/pull/125404#discussion_r1670710478

File: pkg/kubelet/kubelet.go [hunk 8]
```diff
@@ -2075,6 +2076,15 @@ func (kl *Kubelet) SyncTerminatingPod(_ context.Context, pod *v1.Pod, podStatus
 	return nil
 }
 
+// preserveDataFromBeforeStopping preserves data, like IPs, which are expected
+// to be sent to the API server after termination, but are no longer returned by
+// containerRuntime.GetPodStatus for a stopped pod.
+// Note that Kubelet restart, after the pod is stopped, may still cause losing
+// track of the data.
+func preserveDataFromBeforeStopping(stoppedPodStatus, podStatus *kubecontainer.PodStatus) {
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet.go:2084]: +1 this LGTM

**Comment by smarterclayton** [comment]
/approve

LGTM but will let David or Sergey drive the final ack.

**Comment by mimowo** [comment]
Thank you, so the remaining question is about cherry-pick. I'm not sure we have enough signal based on https://github.com/kubernetes/kubernetes/issues/125370#issuecomment-2220439886. However, I would vote for it because: 
1. it is a regression
2. the behavior when IP gets lost for one request and returns back will be confusing for debugging, like oncalling
3. there is one request to the API server per pod lifetime to gain
4. the change is small so the risk is minimal

**Comment by aojea** [comment]
@mimowo you may need to squash the commits for the backport

LGTM , defer to @SergeyKanzhelev final lgtm

I'm +1 on the backport because the fix is contained and there are a lot of informers that depend on PodIPs field, missing the field can lead to corner and complex cases

**Comment by mimowo** [comment]
> @mimowo you may need to squash the commits for the backport

Thanks! done

**Comment by SergeyKanzhelev** [comment]
/lgtm

thank you!

**Comment by mimowo** [comment]
Thank you! I have prepared the cherry-picks for review since 1.27 when the regression started, even though 1.27 is EOL currently. It probably does not hurt to cherry-pick there, otherwise I will just close that PR.
