### PR TITLE
Fix bug of missing random watch events in the event stream

### LINKED ISSUE #39072: Scheduler is ignoring some pods in large clusters and they hang in "pending" state for hours
There seeem to be a regression in apiserver/scheduler which leads to the situation that scheduler in not scheduling some pods in large clusters.
So what is happening is that in 5000-node kubemark, pretty much every run of Density test in the last few days is ending with the following error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:721
Expected error:
    <*errors.errorString | 0xc49b9b2640>: {
        s: "Only 2994 pods started out of 3000",
    }
    Only 2994 pods started out of 3000
not to have occurred
```

The first such failure is this one:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/114

However, we have broken kubemark just before that, so the last run without such failure before this one is:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/108

So the regression was somewhere between those two runs.

It's not even in which part of code the regression is - e.g. it may potentially be in watch.

However, what is suspicious is that it is always about the scheduler that doesn't schedule pods. If the pod is scheduled, then it is also successfully picked by kubelet. 

@kubernetes/sig-api-machinery-misc @kubernetes/sig-scheduling-misc @kubernetes/sig-scalability-misc 
@davidopp @gmarek @shyamjvs

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #39072

### CODE REVIEW

File: pkg/storage/cacher.go [hunk 1]
```diff
@@ -859,10 +859,19 @@ func (c *cacheWatcher) sendWatchCacheEvent(event *watchCacheEvent) {
...
 	}
+
+	// We don't want to block on c.result if c.done is already closed.
+	//
+	// TODO: This doesn't protect with the situation when c.result is
+	// already full and we are handing on it and in the meantime c.done
+	// is being closed and noone will clear the result channel.
+	// However, we can't heve select of two cases, as this may lead to
+	// delivering random part of events after c.done is closed but we
+	// are still sending them for a moment.
```
Comment (liggitt) [inline pkg/storage/cacher.go]: we could drain `c.result` in cacheWatcher#stop()

Comment (wojtek-t) [inline pkg/storage/cacher.go]: There is no good way to ensure that noone (iowatcher) else will be draining it at the same time and part of it will be drained here and part there which will lead to exactly the same problem.

File: pkg/storage/cacher.go [hunk 2]
```diff
@@ -859,10 +859,19 @@ func (c *cacheWatcher) sendWatchCacheEvent(event *watchCacheEvent) {
...
 	select {
-	case c.result <- watchEvent:
-	// don't block on c.result if c.done is closed
 	case <-c.done:
+	default:
```
Comment (xiang90) [inline pkg/storage/cacher.go]: I do not quite understand this. If the sending buffer is full, c.done will be triggered.

Comment (xiang90) [inline pkg/storage/cacher.go]: > We don't want to block on c.result if c.done is already closed.

We wont be blocked on c.done. but if c.result is not full, we might try to send over it.

this pr changes the priority to always evaluate c.done first no matter what. is that what you want? can you explain why and fix the comment? or i am missing something?

File: pkg/storage/cacher.go (hunk 1 above)
Comment (liggitt) [inline pkg/storage/cacher.go]: I assumed you didn't care about delivery of events after done is closed, since you're skipping delivering them here. two readers can drain without ill effects if you don't care about post-done delivery, and that would ensure we didn't infinitely block

Comment (wojtek-t) [inline pkg/storage/cacher.go]: I don't care about being delivered or not. But it cannot happen that e.g. if events 1, 2 and 3 are queued, event 1 and will be deliver, but 2 not. And this is what is happening now and won't happen with this PR.

Comment (caesarxuchao) [inline pkg/storage/cacher.go]: I don't understand why event 2 not being delivered is a problem. I think the reflector will start a new watch from the resourceVersion of the last event it has received, so event 2 will be delivered in the next watch request.

Comment (xiang90) [inline pkg/storage/cacher.go]: @caesarxuchao Since this function is called in a for loop. The deliver to done or result chan is not deterministic. This current code is wrong. @wojtek-t is on the right path to fix it I believe.

File: pkg/storage/cacher.go (hunk 2 above)
Comment (xiang90) [inline pkg/storage/cacher.go]: @wojtek-t 

So I read https://github.com/kubernetes/kubernetes/issues/39072. Now I understand the problem. The comment is very misleading. We need to fix it.

Also how about

``` go
c.Lock
stopped := c.stopped
c.Unlock
if stopped {
    return
}

// keep previous logic
```

not sure if the lock adds up latency. but it would help the race between close(done) and the default case here. or we might end up with leaking routine again.

File: pkg/storage/cacher.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/storage/cacher.go]: I understand it's non-deterministic, but I still fail to see why it's a problem. If the event is not sent to the client, client will see the event in its next Watch request, right?

Comment (wojtek-t) [inline pkg/storage/cacher.go]: >I understand it's non-deterministic, but I still fail to see why it's a problem. If the event is not sent to the client, client will see the event in its next Watch request, right?

@caesarxuchao assuming that any event after this one also won't be delivered then yes that's the case. However, the client is starting the next watch from the last even it has seen. That said if we deliver to him events 1 and 3 (and drop 2), it will start the next watch from 4.

That said, the real problem is that when "c.done" is close we have completely no control and guarantee whever the items in the ResultChan will or will not be delivered to the watcher.

File: pkg/storage/cacher.go (hunk 2 above)
Comment (wojtek-t) [inline pkg/storage/cacher.go]: I'm happy to change the comment, but in my opinion it's not misleading. So if you can suggest something else, I'm happy to change that.

Regarding your proposal about changing to use lock - I don't see how this is fixing the problem. The watcher can still be stopped right after you are calling c.Unlock, which will again decrease the probability but will not fix the problem completely. And you are adding Lock for every (watch event , watcher) pair.

Comment (xiang90) [inline pkg/storage/cacher.go]: > // We don't want to block on c.result if c.done is already closed.

This is true previously. Now the code is

```go
c.result <- watchEvent
```

c.done has nothing to do with c.result blocks or not. Even if c.result does not block, we wont reach there. If we reach there and c.result blocks, we cannot help.

Comment (xiang90) [inline pkg/storage/cacher.go]: >  The watcher can still be stopped right after you are calling c.Unlock

This is fine. All we need to ensure is that 1, (missing 2), 3, 4 wont happen. Adding the stop check will completely solve it since it makes all checking deterministic and serializable.

We do not want to ensure we deliver everything sent before done is called.

Comment (wojtek-t) [inline pkg/storage/cacher.go]: Sorry I wasn't clear enough. I agree this solves the problem that my PR is solving. However, this potentially also doesn't solve the problem that was supposed to be solved by the original PR which is leaking go-routines. By that I mean that if noone is draining the ResultChan, then we can still block on the ``` c.result <- watchEvent ``` forever in that case.

That said, I think that what you are suggesting is equally good as my PR and adds additional locking. Or am I missing something and what you suggested is somehow better?

Comment (xiang90) [inline pkg/storage/cacher.go]: > Or am I missing something and what you suggested is somehow better?

```go
c.Lock
stopped := c.stopped
c.Unlock
if stopped {
    return
}

// keep previous logic
```

This is what I suggested. The previous logic already handle the case you mentioned, which is

```go
select {
    case c.result <- watchEvent:
    // don't block on c.result if c.done is closed
    case <-c.done:
}
```

the stop thing is a safe guard we can add upon the previous logic.

Comment (liggitt) [inline pkg/storage/cacher.go]: instead of locking and checking `stopped`, why not just attempt to select from done before using the existing logic?

```go
// short-circuit if done is already closed
select {
  case <-c.done:
    return
  default:
}

// existing logic
select {
    case c.result <- watchEvent:
    case <-c.done:
}
```

Comment (xiang90) [inline pkg/storage/cacher.go]: > why not just attempt to select from done before using the existing logic?

@wojtek-t wont like something more expensive. :P Based on previous experiments, select evaluation is more expensive than un-contention lock checking. But, sure, we can do a quick benchmark for this. I do not really know since go changed a few things around this.

Comment (wojtek-t) [inline pkg/storage/cacher.go]: OK - thank you for comments. I changed the code (and the comments) to the one that @liggitt suggested as this is the most consistent one. We can evaluate performance of both suggestions after Christmas, but I think we should merge this ASAP.

**Comment by wojtek-t** [comment]
@liggitt @xiang90 @caesarxuchao - PTAL

**Comment by caesarxuchao** [comment]
The current approach looks right. Can we let "sendWatchCacheEvent" returns if c.done wins the select, and break the for-loop if so? That's more intuitive to me.

File: pkg/storage/cacher.go [hunk 3]
```diff
@@ -859,9 +859,27 @@ func (c *cacheWatcher) sendWatchCacheEvent(event *watchCacheEvent) {
 	case !curObjPasses && oldObjPasses:
 		watchEvent = watch.Event{Type: watch.Deleted, Object: object}
 	}
+
+	// We need to ensure that if we put event X to the c.result, all
+	// previous events were already put into it before, no matter whether
+	// c.done is close or not.
+	// Thus we cannot simply select from c.done and c.result and this
+	// would give us non-terminism.
```
Comment (caesarxuchao) [inline pkg/storage/cacher.go]: typo: non-determinism

**Comment by liggitt** [comment]
> Alternatively, can we let "sendWatchCacheEvent" returns if c.done wins the select, and break the for-loop if so?

You have the possibility of done never winning the select if the watch stream is busy enough. I prefer explicitly checking done

File: pkg/storage/cacher.go (hunk 3 above)
Comment (wojtek-t) [inline pkg/storage/cacher.go]: done

**Comment by wojtek-t** [comment]
>> Alternatively, can we let "sendWatchCacheEvent" returns if c.done wins the select, and break the for-loop if so?

> You have the possibility of done never winning the select if the watch stream is busy enough. I prefer explicitly checking done

Technically, I think Go guarantees sme fairness, so if both are ready, we should finally choose c.done. But I kind of agree that explicit checking done is a bit safer here (though potentially a bit less intuitive).

**Comment by davidopp** [comment]
I assume this will be cherry-picked into the next patch release?

**Comment by davidopp** [comment]
(And thanks @wojtek-t for debugging and fixing!)

**Comment by smarterclayton** [comment]
The select guarantee is:

If one or more of the communications can proceed, a single one that can
proceed is chosen via a uniform pseudo-random selection.

On Sat, Dec 24, 2016 at 3:36 AM, David Oppenheimer <notifications@github.com

**Comment by wojtek-t** [comment]
>I assume this will be cherry-picked into the next patch release?

@davidopp - the PR that introduced this bug wasn't yet cherrypicked to 1.5. So I will create a cherrypick PR with both PRs in few minutes.

**Comment by wojtek-t** [comment]
Cherrypick is out for review.

File: pkg/storage/cacher.go [hunk 4]
```diff
@@ -859,9 +859,27 @@ func (c *cacheWatcher) sendWatchCacheEvent(event *watchCacheEvent) {
...
+
+	// This ensures that with c.done already close, we at most once go
+	// into the next select after this. With that, no matter which
+	// statement we choose there, we will deliver only consecutive
+	// events.
+	select {
+	case <-c.done:
+		return
+	default:
+	}
```
Comment (lavalamp) [inline pkg/storage/cacher.go]: Doesn't this just make problem rarer? What if c.done gets set after the above select and before the below select?

Comment (xiang90) [inline pkg/storage/cacher.go]: Yes. The first (racing with close(c.done)) one might still be non-deterministic. But it is OK. We only want to ensure if we ever drop a event due to the close of c.done, we drop all following events. 

In this case, if one event goes through default all events after it will goes through default for sure.

Comment (wojtek-t) [inline pkg/storage/cacher.go]: As @xiang90 wrote, what you wrote can happen, but this is ok for us.
Basically, we only need to avoid situation when we from 2 consecutive events A, B, we don't deliver A, but then deliver B. (Either delivering both or neither of them is fine). 
If c.done will be satisfied after the above select, but before the one below, we don't know what will happen with A, but in the next round, we are sure that B won't be delivered. So we will be in the situation that we are fine with.
