### PR TITLE
Fix test:Probing container should have monotonically increasing restart

### LINKED ISSUE #108504: Failure cluster [9680dae9...] 	[sig-node] Probing container should have monotonically increasing restart count [NodeConformance] [Conformance]
### Failure cluster [9680dae909cbef5f1b13](https://go.k8s.io/triage#9680dae909cbef5f1b13)

In
```
[sig-node] Probing container should have monotonically increasing restart count [NodeConformance] [Conformance]
```

</span>

##### Error text:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
Feb 23 01:49:10.712: pod container-probe-1437/liveness-9c4af6bc-7ef0-4db5-b45b-d6520130fcff - expected number of restarts: 5, found restarts: 2
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:195
```
#### Recent failures:
[2/26/2022, 7:33:20 PM ci-kubernetes-kind-conformance-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/1497731538819747840)
[2/26/2022, 4:09:22 PM ci-kubernetes-kind-conformance-parallel-ipv6](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1497679696429584384)
[2/26/2022, 12:31:34 PM ci-kubernetes-kind-network-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-parallel/1497624834375421952)
[2/26/2022, 11:09:31 AM ci-kubernetes-kind-conformance-parallel-ipv6](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1497604199062441984)
[2/26/2022, 5:09:24 AM ci-kubernetes-kind-conformance-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel/1497513600296685568)

/kind failing-test

/sig node

I believe the issue here is that the test is trying to get 5 restarts, but if we don't start the loop until after a few failures have occurred we start getting caught up in exponential backoff.  The 6th backoff iteration is a 2m30s wait (i believe), so we exceed the default timeout of 5m for the test.  We may need to change the test so that we are watching for pod status updates and catch the first one.  HOWEVER - there's also some head of line blocking in pod status manager updates that I suspect might result in updates getting delayed, leading to timeout.  Either way, the test has too little margin with exponential failure backoff to be reliable, and needs to be improved.

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:

```
STEP: Creating pod liveness-e9027a63-3ab6-4aa8-8a06-999eb1cbbe34 in namespace container-probe-960
Feb 26 16:37:15.670: INFO: Started pod liveness-e9027a63-3ab6-4aa8-8a06-999eb1cbbe34 in namespace container-probe-960
STEP: checking the pod's current state and verifying that restartCount is present
Feb 26 16:37:15.674: INFO: Initial restart count of pod liveness-e9027a63-3ab6-4aa8-8a06-999eb1cbbe34 is 0
Feb 26 16:40:32.438: INFO: Restart count of pod container-probe-960/liveness-e9027a63-3ab6-4aa8-8a06-999eb1cbbe34 is now 1 (3m16.764015028s elapsed)
Feb 26 16:42:16.696: FAIL: pod container-probe-960/liveness-e9027a63-3ab6-4aa8-8a06-999eb1cbbe34 - expected number of restarts: 5, found restarts: 1
Full Stack Trace
k8s.io/kubernetes/test/e2e/common/node.glob..func2.8()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:195 +0x117
k8s.io/kubernetes/test/e2e.RunE2ETests(0x23bf257)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x687
k8s.io/kubernetes/test/e2e.TestE2E(0x2336919)
```

```
Feb 26 17:55:32.662: INFO: Started pod liveness-f7ae0bae-3a90-4dda-9aea-06043e48b9fb in namespace container-probe-4436
STEP: checking the pod's current state and verifying that restartCount is present
Feb 26 17:55:32.668: INFO: Initial restart count of pod liveness-f7ae0bae-3a90-4dda-9aea-06043e48b9fb is 0
Feb 26 17:57:29.484: INFO: Restart count of pod container-probe-4436/liveness-f7ae0bae-3a90-4dda-9aea-06043e48b9fb is now 1 (1m56.8151682s elapsed)
Feb 26 17:59:07.965: INFO: Restart count of pod container-probe-4436/liveness-f7ae0bae-3a90-4dda-9aea-06043e48b9fb is now 2 (3m35.297103774s elapsed)
Feb 26 18:00:34.363: FAIL: pod container-probe-4436/liveness-f7ae0bae-3a90-4dda-9aea-06043e48b9fb - expected number of restarts: 5, found restarts: 2
Full Stack Trace
k8s.io/kubernetes/test/e2e/common/node.glob..func2.8()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:195 +0x117
k8s.io/kubernetes/test/e2e.RunE2ETests(0x23bf257)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x687
k8s.io/kubernetes/test/e2e.TestE2E(0x2336919)
```

Saw the failed log, the sync was very slow some circumstance, so I think no need 5 restarts,  maybe set to 3 and extend waiting time.

#### Which issue(s) this PR fixes:

Fixes #108504

#### Special notes for your reviewer:
/cc @SergeyKanzhelev @ehashman 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
is not relaxing too much the condition?

**Comment by 249043822** [comment]
> is not relaxing too much the condition?

any suggestions? Thx

File: test/e2e/common/node/container_probe.go [hunk 1]
```diff
@@ -192,7 +192,7 @@ var _ = SIGDescribe("Probing container", func() {
 			FailureThreshold:    1,
 		}
 		pod := livenessPodSpec(f.Namespace.Name, nil, livenessProbe)
-		RunLivenessTest(f, pod, 5, time.Minute*5)
+		RunLivenessTest(f, pod, 3, time.Minute*10)
```
Comment (SergeyKanzhelev) [inline test/e2e/common/node/container_probe.go:195]: only backoffs for 5 retries combined is almost 2 minutes. Plus, the default timeout for a single restart is 4 minutes. So clearly the timeout is not adequate here, should be at least 6 minutes. Since the first restart must be the longest as it involves the pod scheduling, I'd expect 14 minutes can be enough delay for 5 retries (assuming half of time is needed to restart the pod than schedule and start).

```suggestion
                 // ~2 minutes backoff timeouts + 4 minutes defaultObservationTimeout + 2 minutes for each pod restart
		RunLivenessTest(f, pod, 5, 2 * time.Minute + defaultObservationTimeout + 4 * 2 * time.Minute)
```

I think 14 minutes is ok timeout for conformance test.

If we switching to 3 retries, following the same logic we need 30 sec + 4 minutes + 2 * 2 minutes = 8.5 minutes, no need for 10 minutes. I'd prefer 5 retries though just to be on a safe side and not change the conformance test.

Comment (249043822) [reply test/e2e/common/node/container_probe.go]: Done

**Comment by andyli029** [comment]
> is not relaxing too much the condition?

?

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

let's see if this will make it
