### PR TITLE
bugfix(mount): lstat with abs path of parent instead of '/..'

### LINKED ISSUE #57095: Pods created with an NFS volume with specific ownership get stuck in "Terminating" when deleted
/kind bug
/sig storage

**What happened**:

I created a pod that mounts a NFS backed volume.
The particular NFS export is owned by user and group 1001 and has root squash.

When applying `kubectl delete` (or causing a pod termination by any other means), the pod gets stuck in state "terminating"

**What you expected to happen**:

Expected the pod to terminate properly.

**How to reproduce it (as minimally and precisely as possible)**:

* Create NFS export with ownership set to a particular user and group
* Create pod with NFS volume mount using the above export (changing the user to match the ownership)
* `kubectl delete pod`

**Anything else we need to know?**:

I think this happens because `IsLikelyNotMountPoint(file string) ` in `mount_linux.go` is `lstat`ing the mount's path with a `/..` appended.
This causes the lstat to go through NFS, rather than actually using the local path, thus failing with "permission denied": the actual log from the kubelet is
```
12/12/2017 11:12:22 AME1212 11:12:22.601313   18419 nestedpendingoperations.go:264] Operation for "\"kubernetes.io/nfs/cfb07a81-dea2-11e7-9392-02e3d8a1a011-nfs\" (\"cfb07a81-dea2-11e7-9392-02e3d8a1a011\")" failed. No retries permitted until 2017-12-12 11:14:24.601260829 +0000 UTC (durationBeforeRetry 2m2s). Error: UnmountVolume.TearDown failed for volume "jenkins-home" (UniqueName: "kubernetes.io/nfs/cfb07a81-dea2-11e7-9392-02e3d8a1a011-nfs") pod "cfb07a81-dea2-11e7-9392-02e3d8a1a011" (UID: "cfb07a81-dea2-11e7-9392-02e3d8a1a011") : lstat /var/lib/kubelet/pods/cfb07a81-dea2-11e7-9392-02e3d8a1a011/volumes/kubernetes.io~nfs/nfs/..: permission denied
```

Canonicalizing the path would solve the issue, although I'm not sure what other impact it might have.

**Environment**:
- Server Version: `version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.3-rancher3", GitCommit:"772c4c54e1f4ae7fc6f63a8e1ecd9fe616268e16", GitTreeState:"clean", BuildDate:"2017-11-27T19:51:43Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from /etc/os-release): `Container-Linux 1576.4.0`
- Kernel (e.g. `uname -a`): `Linux host-172-16-0-10 4.13.16-coreos-r2 #1 SMP Wed Dec 6 04:27:34 UTC 2017 x86_64 Intel Core Processor (Broadwell) GenuineIntel GNU/Linux`

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

If a nfs volume with improper permission is mounted on a Pod, operation of deleting this Pod will fail and the pod itself will be stuck at a 'TERMINATING' status. Kubelet cannot reconcile it correctly.

This is because kubelet will try to find the mount-point with '..' file which needs `x` permission of dir.  When it's forbidden, the nfs volume will never umount without a correct mount-point finded.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57095

**Special notes for your reviewer**:

**Release note**:

```release-note
Get parent dir via canonical absolute path when trying to judge mount-point
```

### CODE REVIEW

File: pkg/util/mount/mount_linux.go [hunk 1]
```diff
@@ -265,7 +265,7 @@ func (mounter *Mounter) IsLikelyNotMountPoint(file string) (bool, error) {
 	if err != nil {
 		return true, err
 	}
-	rootStat, err := os.Lstat(file + "/..")
+	rootStat, err := os.Lstat(filepath.Dir(strings.TrimSuffix("/")))
```
Comment (yue9944882) [inline pkg/util/mount/mount_linux.go]: I'm not sure whether trying to remove tailing slash here is necessary

**Comment by yue9944882** [comment]
@jingxu97 @saad-ali PTAL thx

**Comment by yue9944882** [comment]
@jingxu97 @saad-ali @jsafrane How do you think about approving this plz? :-)
