### PR TITLE
Check PV requirements before scheduling

### LINKED ISSUE #69928: Pod scheduled in node without considering PV requirements
**What happened**:

1. Started a single-node Kubernetes cluster with the `CSINodeInfo` feature gate disabled (default)
2. Tried to create a pod that uses a claim that uses a storage class with `volumeBindingMode: WaitForFirstConsumer`
3. Got this message (`kubectl describe pod/mypod`):

```
  Warning  FailedScheduling    25s   default-scheduler        pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           21s   default-scheduler        Successfully assigned default/app to ip-172-18-15-56.ec2.internal
  Warning  FailedAttachVolume  20s   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2" : rpc error: code = Internal desc = Could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": IncorrectState: vol-0feca9e2e21660115 is not 'available'.
		   status code: 400, request id: 96e5c6cf-79dd-4273-889f-1bc526f5f280
  Warning  FailedAttachVolume  20s  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2" : rpc error: code = Internal desc = Could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": IncorrectState: vol-0feca9e2e21660115 is not 'available'.
		   status code: 400, request id: 5a8a4553-5c0c-446e-8e51-04dee0c1d807
  Warning  FailedAttachVolume  19s  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2" : rpc error: code = Internal desc = Could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": IncorrectState: vol-0feca9e2e21660115 is not 'available'.
		   status code: 400, request id: d2a05dbe-6673-456c-95ad-fd8582e923cb
  Warning  FailedAttachVolume  17s  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2" : rpc error: code = Internal desc = Could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": could not attach volume "vol-0feca9e2e21660115" to node "i-0a647985e4981fee6": IncorrectState: vol-0feca9e2e21660115 is not 'available'.
		   status code: 400, request id: 28a9ca4e-6305-471f-b744-36535bd2cada
  Normal   SuccessfulAttachVolume  13s               attachdetach-controller                AttachVolume.Attach succeeded for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2"
  Warning  FailedMount             3s (x25 over 5s)  kubelet, ip-172-18-15-56.ec2.internal  MountVolume.NodeAffinity check failed for volume "pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2" : No matching NodeSelectorTerms
```

The `MountVolume.NodeAffinity` check failed because of a missing label in the node (i.e., `com.amazon.aws.csi.ebs/zone=us-east-1d`). This happened because of #69869.

However, the scheduler shouldn't have scheduled the pod because any node matched the PV requirements.

**What you expected to happen**:

The scheduler shouldn't schedule the pod and a proper message is emitted.

**Anything else we need to know?**:

PV:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: com.amazon.aws.csi.ebs
  creationTimestamp: "2018-10-17T07:52:30Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/com-amazon-aws-csi-ebs
  name: pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  resourceVersion: "639"
  selfLink: /api/v1/persistentvolumes/pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  uid: 995153d2-d1e1-11e8-a49a-0ecfa83a9ab2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: claim1
    namespace: default
    resourceVersion: "625"
    uid: 970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  csi:
    driver: com.amazon.aws.csi.ebs
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1539762711928-8081-com.amazon.aws.csi.ebs
    volumeHandle: vol-0feca9e2e21660115
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: com.amazon.aws.csi.ebs/zone
          operator: In
          values:
          - us-east-1d
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
status:
  phase: Bound
```

Storage class:

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: com.amazon.aws.csi.ebs
  creationTimestamp: "2018-10-17T07:52:30Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/com-amazon-aws-csi-ebs
  name: pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  resourceVersion: "639"
  selfLink: /api/v1/persistentvolumes/pvc-970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  uid: 995153d2-d1e1-11e8-a49a-0ecfa83a9ab2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: claim1
    namespace: default
    resourceVersion: "625"
    uid: 970102a5-d1e1-11e8-a49a-0ecfa83a9ab2
  csi:
    driver: com.amazon.aws.csi.ebs
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1539762711928-8081-com.amazon.aws.csi.ebs
    volumeHandle: vol-0feca9e2e21660115
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: com.amazon.aws.csi.ebs/zone
          operator: In
          values:
          - us-east-1d
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
status:
  phase: Bound

```

/kind bug
/sig storage
/sig scheduling
CC @msau42

### PR DESCRIPTION
**Pull request by bertinatto**
**What this PR does / why we need it**:

/sig storage
/sig scheduling
/kind bug

This patch checks for PV requirements before scheduling the pod on the
node.

**Which issue(s) this PR fixes**:

Fixes #69928.

**Release note**:
```release-note
None
```

### CODE REVIEW

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 1]
```diff
@@ -277,12 +276,30 @@ func (b *volumeBinder) BindPodVolumes(assumedPod *v1.Pod) error {
...
 		// Get cached values every time in case the pod gets deleted
 		bindings = b.podBindingCache.GetBindings(assumedPod, assumedPod.Spec.NodeName)
 		claimsToProvision = b.podBindingCache.GetProvisionedPVCs(assumedPod, assumedPod.Spec.NodeName)
 		return b.checkBindings(assumedPod, bindings, claimsToProvision)
-	})
+	}); err != nil {
+		return err
+	}
+
+	node, err := b.ctrl.kubeClient.CoreV1().Nodes().Get(assumedPod.Spec.NodeName, metav1.GetOptions{})
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Can we avoid making api calls? Maybe we need to plumb through the node informer during initialization.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 2]
```diff
@@ -277,12 +276,30 @@ func (b *volumeBinder) BindPodVolumes(assumedPod *v1.Pod) error {
...
+		return err
+	}
+
+	// Check node affinity on bound volumes
+	if ok, err := b.checkBoundClaims(claimsToProvision, node, assumedPod.GetName()); !ok {
+		errMsg := "failed validating PV node affinity"
+		if err != nil {
+			return fmt.Errorf("%s: %v", errMsg, err)
+		}
+		return fmt.Errorf(errMsg)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: would prefer this error message to be a little more detailed, like "PV %v node affinity does not match node %v"

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 3]
```diff
@@ -1412,6 +1421,12 @@ func TestBindPodVolumes(t *testing.T) {
 			}()
 		}
 
+		// This is used for checking the node affinity on bound volumes
+		if scenario.updateProvisionedPVCs {
+			pvc := pvcSetSelectedNode(scenario.cachedPVC, pod.Spec.NodeName)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: I'm not sure how this test case is validating PV.NodeAffinity since it only modifies the PVC.  Also, would prefer this test case to be implemented through delayFunc

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 1 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Done.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 2 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: From here, I don't have access to the PV that failed the validation. Seems like I'd have to make `checkBoundClaims` return this info (for now it only logs it).

I updated the message to include the node name, but let me know if you think this isn't enough.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 3 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: > Also, would prefer this test case to be implemented through delayFunc

Done.

> I'm not sure how this test case is validating PV.NodeAffinity since it only modifies the PVC.

AFAIU, the PVs are taken from the `pvAssumeCache` object. This is only necessary because `volumeBinder.checkBoundClaims()` takes in a list of PVCs, but it fetches the PVs referenced in these PVCs from `volumeBinder.pvCache` (which already contains the PVs).

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 4]
```diff
@@ -1383,6 +1402,38 @@ func TestBindPodVolumes(t *testing.T) {
...
+				}
+
+				pvcCache := internalBinder.pvcCache
+				internalPVCCache, ok := pvcCache.(*pvcAssumeCache)
+				if !ok {
+					t.Fatalf("Failed to convert to internal PVC cache")
+				}
+				internalPVCCache.add(newPVC)
+
+				// Update pod binding cache
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: why does pod binding cache need to be updated?  `checkBoundClaims` should only need to look at the pvc and pv cache

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 2 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: If I understand correctly, there could be more than one PVC in `claims` (which is a list of PVCs) that can fail the node affinity check. From here I only know that something failed, it could be only one or even all of them.

`checkBoundClaims` doesn't return which ones failed, it only logs them. I'd have to change this method (and everything that's using it). Perhaps is that what you are suggesting?

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 5]
```diff
@@ -126,6 +127,7 @@ func NewVolumeBinder(
 
 	b := &volumeBinder{
 		ctrl:            ctrl,
+		nodeCache:       NewNodeAssumeCache(nodeInformer.Informer()),
```
[the remark this answers is not in the document]
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Done.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 4 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Ah I see, in that case, it should be added to pod binding cache during test setup, not the delay func.  The testEnv.assumeVolumes call currently passes in no PVCs, but it can be modified.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 2 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: I think it is fine to checkBoundClaims to also return the first failed PV.  There's only one other caller.

Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Perfect! Done.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 4 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: It seems like `testEnv.assumeVolumes` do passes in PVCs. I missed that.

Unfortunately I can't update the pod binding cache in all cases, so I see a few options to solve this. I implemented the third one, but let me know if you have a better idea:

1. Update the pod binding cache only in the delay function (which we don't want)
2. Add a flag in the test case to update the pod binding cache (which we probably don't want as well, as per a previous comment in this PR)
3. Add to the test case a list of provisioned PVCs, just like other tests are doing :)

Just for the record, here's why I can't update the pod binding cache in all cases: `boundPVCNode1a` doesn't have the field `boundPVCNode1a.Spec.VolumeName` set, and it seems like that's intentional [1]. However, if I update the pod binding cache without this field set, this [2] validation in `volumeBinder.checkBindings` will fail. I believe that's the main reason why this test isn't updating the cache.

[1] https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/scheduler_binder_test.go#L452-L461
[2] https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/scheduler_binder.go#L418-L421

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Can we do something like this?
* the test PVC has selectedNode set to nodeX, not bound
* delayFunc updates the PVC to be bound to the wrong PV with different node

Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Do you mean something like this?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 6]
```diff
@@ -1383,6 +1395,47 @@ func TestBindPodVolumes(t *testing.T) {
...
+
+				pvcCache := internalBinder.pvcCache
+				internalPVCCache, ok := pvcCache.(*pvcAssumeCache)
+				if !ok {
+					t.Fatalf("Failed to convert to internal PVC cache")
+				}
+				internalPVCCache.add(newPVC)
+
+				// Wrong PV isn't added to the PV cache during setup, so add it now
+				pvCache := internalBinder.pvCache
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: can this be added in the setup under cachedPV?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 7]
```diff
@@ -1383,6 +1395,47 @@ func TestBindPodVolumes(t *testing.T) {
...
+			cachedPVC: selectedNodePVC,
+			delayFunc: func(t *testing.T, testEnv *testEnv, pod *v1.Pod, pv *v1.PersistentVolume, pvc *v1.PersistentVolumeClaim) {
+				// Update PVC to be fully bound to a PV with a different node
+				newPVC := pvc.DeepCopy()
+				newPVC.ResourceVersion = "100"
+				newPVC.Spec.VolumeName = pvNode2.Name
+				metav1.SetMetaDataAnnotation(&newPVC.ObjectMeta, annBindCompleted, "yes")
+
+				// Update the pod binding cache with the new PVC
+				bindingsCache := testEnv.binder.GetBindingsCache()
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: I think you don't need to update the bindings cache.  We only use the pvc.name and namespace from the pod bindings cache, but then in `checkBindings`, we will actually look up the pvc object from the pvc assume cache.  Trying to mirror the "binding succeeds after time" test case as close as possible.

Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: > in checkBindings, we will actually look up the pvc object from the pvc assume cache

Right, `checkBindings` looks up the object from the assume cache, however, `checkBoundClaims` doesn't do that currently; it relies on the list of `v1.PersistentVolumeClaim` passed in to it [1].

In fact, we may need to update the binding cache in other tests as well. For example, `checkBindings` is only succeeding in _binding succeeds after time_ because both `claimsToProvision` and `bindings` are empty lists [2] (since they are not present in the pod binding cache).

Maybe am I missing something?

[1] https://github.com/bertinatto/kubernetes/blob/2e1ef482336791e5a984729227153bf756a47410/pkg/controller/volume/persistentvolume/scheduler_binder.go#L320
[2] https://github.com/bertinatto/kubernetes/blob/2e1ef482336791e5a984729227153bf756a47410/pkg/controller/volume/persistentvolume/scheduler_binder.go#L397

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 6 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Yes, but I think I'd need to create a new field. Note that I'm adding to the cache an arbitrary PV bound to a wrong node.

**Comment by jsafrane** [comment]
I may not understand all implications in scheduler, but it looks good to me.
@msau42, WDYT?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 7 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: I want to use the assume cache as the source of truth for API objects, not the pod binding cache, which is only meant to store binding/provisioning decisions wrt the the pvc and pv names.

Instead of calling `checkBoundClaims` directly, can you get the PVC object from the assume cache like [this](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/controller/volume/persistentvolume/scheduler_binder.go#L409), and then call `CheckNodeAffinity` directly?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 6 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: That is fine

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 7 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: `claimsToProvision` [is always empty](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/controller/volume/persistentvolume/scheduler_binder.go#L294) during unit tests execution (because we don't update the pod binding cache), so I can't get any PVC objects from the assume cache because I don't know their names.

I could get the PVC/PV names from [bindings instead](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/controller/volume/persistentvolume/scheduler_binder.go#L293), but that sounds incorrect. Here's [sketch](https://gist.github.com/bertinatto/7b4d870c6c1dd14adf6301c4155db77a) of that.

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Can you modify the test case to also populate the Pod binding cache with initial PVC objects?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 4 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Done

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 8]
```diff
@@ -1296,20 +1324,21 @@ func TestBindPodVolumes(t *testing.T) {
...
+			binding:    binding1aBound,
+			cachedPVs:  []*v1.PersistentVolume{pvNode1a},
+			cachedPVCs: []*v1.PersistentVolumeClaim{unboundPVC},
 			delayFunc: func(t *testing.T, testEnv *testEnv, pod *v1.Pod, pv *v1.PersistentVolume, pvc *v1.PersistentVolumeClaim) {
 				// Update PVC to be fully bound to PV
 				newPVC := pvc.DeepCopy()
 				newPVC.ResourceVersion = "100"
 				newPVC.Spec.VolumeName = pv.Name
 				metav1.SetMetaDataAnnotation(&newPVC.ObjectMeta, annBindCompleted, "yes")
+				metav1.SetMetaDataAnnotation(&newPVC.ObjectMeta, annSelectedNode, pod.Spec.NodeName)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: is this necessary?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 9]
```diff
@@ -1380,22 +1409,53 @@ func TestBindPodVolumes(t *testing.T) {
...
+		if scenario.apiPVs == nil {
+			scenario.apiPVs = scenario.cachedPVs
 		}
 		testEnv := newTestBinder(t)
 		if !scenario.bindingsNil {
+			if scenario.nodes == nil {
+				scenario.nodes = []*v1.Node{node1}
+			}
+			testEnv.initNodes(scenario.nodes)
 			if scenario.binding != nil {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: I would add a new field to the test case for provisioned pvcs.  Then for the call to `assumeVolumes`, the bindings argument is determined by `scenario.binding`, and the provisioned pvcs argument is determined by `scenario.provisionedPVCs`.  That way, the arguments can be independent.

There can even be two test cases to test wrong binding.  One for static binding, and one for dynamic provisioning.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 10]
```diff
@@ -99,8 +98,9 @@ type SchedulerVolumeBinder interface {
 type volumeBinder struct {
 	ctrl *PersistentVolumeController
 
-	pvcCache PVCAssumeCache
-	pvCache  PVAssumeCache
+	nodeInformer coreinformers.NodeInformer
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Can you add a comment here that this nodeInformer cannot be used in FindPodVolumes?  Because the predicate is reused for cluster autoscaler, which passes in fake Node objects to the predicate.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 8 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Yes, otherwise it'd fail in [this condition](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/scheduler_binder.go#L419).

It wasn't necessary before because the execution never made it inside [that loop](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/scheduler_binder.go#L408-L426) (the pod binding cache wasn't updated, resulting in an emtpy `claimsToProvision`).

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 10 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Added the comment in `FindPodVolumes` instead. Let me know if you disagree.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 9 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Done.

> There can even be two test cases to test wrong binding. One for static binding, and one for dynamic provisioning.

Do you mean something like this?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 11]
```diff
@@ -1380,22 +1410,64 @@ func TestBindPodVolumes(t *testing.T) {
...
 		},
+		"node-affinity-fails": {
+			binding:    binding1aBound,
+			cachedPVs:  []*v1.PersistentVolume{pvNode1aBound},
+			cachedPVCs: []*v1.PersistentVolumeClaim{boundPVCNode1a},
+			nodes:      []*v1.Node{node1NoLabels},
+			shouldFail: true,
+		},
+		"node-affinity-fails-dynamic-provisioning": {
+			binding:         binding1aBoundSelectedNode,
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: bindings is for static binding, and provisioned PVCs is for dynamic provisioning.  So this test case shouldn't need to set binding.

**Review by msau42 — COMMENTED** [review]
lgtm, just a minor test comment

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 12]
```diff
@@ -391,6 +400,11 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
 			return false, fmt.Errorf("failed to check pv binding: %v", err)
 		}
 
+		// Check PV's node affinity (the node might not have the proper label)
+		if err := volumeutil.CheckNodeAffinity(pv, node.Labels); err != nil {
+			return false, fmt.Errorf("pv %q node affinity doesn't match node %q: %v", pv.Name, node.Name, err)
+		}
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: For static PV binding, PV has been checked in finding, this is used to double check before scheduling?

https://github.com/kubernetes/kubernetes/blob/98b3e4212797f87410ec8b12a836c289b2e68102/pkg/controller/volume/persistentvolume/index.go#L178-L186`

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 11 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: The delay function takes in the pv/pvc from the binding, so it's currently needed. Or do you mean I should change its input? (It doesn't look [great](https://gist.github.com/bertinatto/5e6cf3ffa8c6c01b6634ef589262298f))

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 12 above)
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Not because of the node labels, but because because of the new static binding [test added](https://github.com/kubernetes/kubernetes/pull/70026#discussion_r244380476).

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 13]
```diff
@@ -420,6 +434,17 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
...
 		}
 
+		// If the PVC is bound to a PV, check its node affinity
+		if pvc.Spec.VolumeName != "" {
+			pv, err := b.pvCache.GetPV(pvc.Spec.VolumeName)
+			if err != nil {
+				return false, fmt.Errorf("failed to get pv %q from cache: %v", pvc.Spec.VolumeName, err)
+			}
+			if err := volumeutil.CheckNodeAffinity(pv, node.Labels); err != nil {
+				return false, fmt.Errorf("pv %q node affinity doesn't match node %q: %v", pv.Name, node.Name, err)
```
[the remark this answers is not in the document]
Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: I would say that the main point of having this check here is to prevent the scheduler from scheduling the pod rather than leaving the job to the kubelet.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 12 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: The check here is more of a safety guard in case the user ends up manually binding to a different PV on a different node than what the scheduler chose

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 11 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: What if the delay function takes in both binding and provisionedPVCs?

Comment (bertinatto) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Done. Had to re-organize the setup part because `BindPodVolumes` will [fail](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/scheduler_binder.go#L321-L323) if we pass in a `nil` binding (e.g., `nothing-to-bind-nil` test).
