### PR TITLE
Honor starting resourceVersion in watch cache

### LINKED ISSUE #24194: Unit flake in pkg/storage: TestFiltering
```
--- FAIL: TestFiltering (0.97s)
	cacher_test.go:167: (called from line 342)
	cacher_test.go:168: Expected: DELETED, got: ADDED
	cacher_test.go:167: (called from line 343)
	cacher_test.go:168: Expected: ADDED, got: DELETED
	cacher_test.go:171: (called from line 343)
	cacher_test.go:172: Expected (ADDED): &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8203ae650), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc82089ec80), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}, got: &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"5", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8206ffed0), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc8206c4c40), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
	cacher_test.go:167: (called from line 344)
	cacher_test.go:168: Expected: MODIFIED, got: ADDED
	cacher_test.go:171: (called from line 344)
	cacher_test.go:172: Expected (MODIFIED): &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc8203ae660), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"fakeNode", SecurityContext:(*api.PodSecurityContext)(0xc82089ed00), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}, got: &api.Pod{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo", GenerateName:"", Namespace:"ns", SelfLink:"", UID:"", ResourceVersion:"6", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"filter":"foo"}, Annotations:map[string]string(nil)}, Spec:api.PodSpec{Volumes:[]api.Volume(nil), Containers:[]api.Container(nil), RestartPolicy:"Always", TerminationGracePeriodSeconds:(*int64)(0xc820386e28), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"", NodeName:"", SecurityContext:(*api.PodSecurityContext)(0xc8201893c0), ImagePullSecrets:[]api.LocalObjectReference(nil)}, Status:api.PodStatus{Phase:"", Conditions:[]api.PodCondition(nil), Message:"", Reason:"", HostIP:"", PodIP:"", StartTime:(*unversioned.Time)(nil), ContainerStatuses:[]api.ContainerStatus(nil)}}
	cacher_test.go:167: (called from line 345)
	cacher_test.go:168: Expected: DELETED, got: MODIFIED
FAIL
FAIL	k8s.io/kubernetes/pkg/storage	12.878s
```

Running in an endless loop, I wasn't able to immediately reproduce, BUT I was able to reproduce as soon as I started running `stress -c 4` in a separate terminal.

### PR DESCRIPTION
**Pull request by ncdc**
Compare the requested resourceVersion to each event's resourceVersion to ensure events that occurred
in the past are not sent to the client.

Fixes #24194 

cc @liggitt @wojtek-t

### CODE REVIEW

**Comment by ncdc** [comment]
I'd like to add a unit test for this but I've got a question about it at https://github.com/kubernetes/kubernetes/issues/24194#issuecomment-209545755

File: pkg/storage/cacher.go [hunk 1]
```diff
@@ -555,6 +555,10 @@ func (c *cacheWatcher) process(initEvents []watchCacheEvent) {
 		if !ok {
 			return
 		}
+		if event.ResourceVersion <= resourceVersion {
```
Comment (liggitt) [inline pkg/storage/cacher.go]: can we just make the send conditional?
```
// only send events newer than resourceVersion
if event.ResourceVersion > resourceVersion {
  c.sendWatchCacheEvent(event)
}
```

Comment (ncdc) [inline pkg/storage/cacher.go]: Sure

**Comment by ncdc** [comment]
@k8s-bot e2e test this github issue: #23974

**Comment by timothysc** [comment]
Are there a positive and negative checks in the tests for this?

**Comment by wojtek-t** [comment]
Code changes LGTM - we just need some test for it.

**Comment by ncdc** [comment]
@timothysc will have units for it - just need to figure out how to write them w/o having them flake or take 30+ seconds

**Comment by wojtek-t** [comment]
@timothysc - see #24194 for discussion about test

File: pkg/storage/cacher_test.go [hunk 2]
```diff
@@ -344,3 +345,51 @@ func TestFiltering(t *testing.T) {
...
+	server, etcdStorage := newEtcdTestStorage(t, testapi.Default.Codec(), etcdtest.PathPrefix())
+	defer server.Terminate(t)
+	cacher := newTestCacher(etcdStorage)
+	defer cacher.Stop()
+
+	// add 1 object
+	podFoo := makeTestPod("foo")
+	fooCreated := updatePod(t, etcdStorage, podFoo, nil)
+
+	// Set up Watch starting at fooCreated.ResourceVersion + 1
```
Comment (liggitt) [inline pkg/storage/cacher_test.go]: update comment

Comment (ncdc) [inline pkg/storage/cacher_test.go]: fixed

**Comment by ncdc** [comment]
@timothysc test added, PTAL

**Comment by ncdc** [comment]
Hmm the test might still pass without my fix... investigating.

**Comment by ncdc** [comment]
Fixed the test. Helps if you generate events for the right etcd path :-)

File: pkg/storage/cacher_test.go [hunk 3]
```diff
@@ -344,3 +345,53 @@ func TestFiltering(t *testing.T) {
...
+	defer server.Terminate(t)
+	cacher := newTestCacher(etcdStorage)
+	defer cacher.Stop()
+
+	// add 1 object
+	podFoo := makeTestPod("foo")
+	fooCreated := updatePod(t, etcdStorage, podFoo, nil)
+
+	// Set up Watch starting at fooCreated.ResourceVersion + 10
+	rv, err := storage.ParseWatchResourceVersion(fooCreated.ResourceVersion)
```
Comment (timothysc) [inline pkg/storage/cacher_test.go]: this logic could probably be reduced but it's a test so whatevers... re: parse + addition + convert

Comment (ncdc) [inline pkg/storage/cacher_test.go]: Yeah, I considered that but decided to be lazy :smile:

File: pkg/storage/cacher_test.go [hunk 4]
```diff
@@ -344,3 +345,53 @@ func TestFiltering(t *testing.T) {
...
+		if e, a := strconv.Itoa(int(rv+1)), o.ResourceVersion; e != a {
+			t.Errorf("expected event with resourceVersion %q, got %q", e, a)
+		}
+		if !api.Semantic.DeepEqual(updatedFoo, o) {
+			t.Errorf("updatedFoo didn't match the event object: %s", diff.ObjectDiff(updatedFoo, o))
+		}
+	case <-time.After(wait.ForeverTestTimeout):
+		t.Errorf("timed out waiting for event")
+	}
+}
```
Comment (timothysc) [inline pkg/storage/cacher_test.go]: could nit, not going to, will let @wojtek-t decide.

File: pkg/storage/cacher_test.go (hunk 3 above)
Comment (wojtek-t) [inline pkg/storage/cacher_test.go]: SGTM

Comment (wojtek-t) [inline pkg/storage/cacher_test.go]: I would do the same :)

File: pkg/storage/cacher_test.go [hunk 5]
```diff
@@ -344,3 +345,53 @@ func TestFiltering(t *testing.T) {
...
+
+	podFooForUpdate := makeTestPod("foo")
+	podFooForUpdate.Labels = map[string]string{"foo": "bar"}
+	updatedFoo := updatePod(t, etcdStorage, podFooForUpdate, lastFoo)
+
+	select {
+	case e := <-watcher.ResultChan():
+		o := e.Object.(*api.Pod)
+		// event should have rv + 1, since we're starting the watch at rv
+		if e, a := strconv.Itoa(int(rv+1)), o.ResourceVersion; e != a {
```
Comment (wojtek-t) [inline pkg/storage/cacher_test.go]: I remember that at some point we have unit test flakes because etcd itself is internally increasing ResourceVersion (without any external action on it). This is still true during startup (RV from the first external action is usually 3).

@xiang90 @hongchaodeng - is that safe to assume that of we have 12 creates/updates to etcd, these will have consecutive RV numbers?

@ncdc - to be on the safe side, I would just check whether the RV is >rv, not exactly equal rv+1 (and then just ignore checking equality of objects)

Comment (ncdc) [inline pkg/storage/cacher_test.go]: Updated, PTAL

**Comment by wojtek-t** [comment]
@ncdc - can you please squash commits and rebase?

**Comment by ncdc** [comment]
Rebased & squashed

**Comment by wojtek-t** [comment]
LGTM - thanks for fixing this!
