### PR TITLE
[Controller Manager] Fix endpoint controller hot loop and use utilruntime.HandleError to replace glog.Errorf

### LINKED ISSUE #32843: Endpoint controller hot-loops on failure
Endpoint controller hot-loops when etcd is down-- in one cluster I saw 5 digits worth of failed POST requests.

#32461 fixes a log message but not the actual problem.

### PR DESCRIPTION
**Pull request by m1093782566**
**Why**:

Fix endpoint controller hot loop and use `utilruntime.HandleError` to replace `glog.Errorf`

**What**
1. Fix endpoint controller hot loop in `pkg/controller/endpoint`
2.  Fix endpoint controller hot loop in `contrib/mesos/pkg/service`
3. Sweep cases of `glog.Errorf` and use `utilruntime.HandleError` instead.

**Which issue this PR fixes**

Fixes #32843
Related issue is #30629 

**Special notes for your reviewer**:

@deads2k @derekwaynecarr 

The changes on `pkg/controller/endpoints_controller.go` and `contrib/mesos/pkg/service/endpoints_controller.go` are almost the same except `contrib/mesos/pkg/service/endpoints_controller.go` does not pass `podInformer` as the parameter of `NewEndpointController()`. 

So, I didn't wait `podStoreSynced` before `syncService()`(Just leave it as it was). Will it lead to a problem?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32776)

### CODE REVIEW

**Comment by deads2k** [comment]
> contrib/mesos/pkg/service/endpoints_controller.go are almost the same except

Thanks for fix it up, but I don't worry too much about the mesos controllers.  We keep them compiling, but I don't think its incumbent upon us to keep them at the latest and greatest.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 1]
```diff
@@ -299,36 +307,39 @@ func (e *EndpointController) enqueueService(obj interface{}) {
...
 	}
 }
 
-func (e *EndpointController) syncService(key string) {
+func (e *EndpointController) processNextWorkItem() bool {
+	eKey, quit := e.queue.Get()
+	if quit {
+		return false
+	}
+	// Use defer: in the unlikely event that there's a
```
Comment (deads2k) [inline pkg/controller/endpoint/endpoints_controller.go]: nit: I don't think there's a need to preserve this comment.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 2]
```diff
@@ -338,33 +349,32 @@ func (e *EndpointController) syncService(key string) {
...
+			utilruntime.HandleError(fmt.Errorf("Need to delete endpoint with key %q, but couldn't understand the key: %v", key, err))
 			// Don't retry, as the key isn't going to magically become understandable.
-			return
+			return nil
 		}
 		err = e.client.Endpoints(namespace).Delete(name, nil)
 		if err != nil && !errors.IsNotFound(err) {
-			glog.Errorf("Error deleting endpoint %q: %v", key, err)
-			e.queue.Add(key) // Retry
+			utilruntime.HandleError(fmt.Errorf("Error deleting endpoint %q: %v", key, err))
```
Comment (deads2k) [inline pkg/controller/endpoint/endpoints_controller.go]: Don't call `HandleError` here since returning an error will produce the same message.

File: pkg/controller/endpoint/endpoints_controller.go (hunk 1 above)
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Okay, fixed.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 3]
```diff
@@ -458,19 +468,17 @@ func (e *EndpointController) syncService(key string) {
...
 	}
 
 	serializedPodHostNames := ""
 	if len(podHostNames) > 0 {
 		b, err := json.Marshal(podHostNames)
 		if err != nil {
-			glog.Errorf("Error updating endpoints. Marshalling of hostnames failed.: %v", err)
-			e.queue.Add(key) // Retry
-			return
+			utilruntime.HandleError(fmt.Errorf("Error updating endpoints. Marshalling of hostnames failed.: %v", err))
```
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Fixed.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 4]
```diff
@@ -458,19 +468,17 @@ func (e *EndpointController) syncService(key string) {
 				},
 			}
 		} else {
-			glog.Errorf("Error getting endpoints: %v", err)
-			e.queue.Add(key) // Retry
-			return
+			utilruntime.HandleError(fmt.Errorf("Error getting endpoints: %v", err))
```
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Fixed.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 5]
```diff
@@ -338,33 +349,32 @@ func (e *EndpointController) syncService(key string) {
...
 
 	glog.V(5).Infof("About to update endpoints for service %q", key)
 	pods, err := e.podStore.Pods(service.Namespace).List(labels.Set(service.Spec.Selector).AsSelectorPreValidated())
 	if err != nil {
 		// Since we're getting stuff from a local cache, it is
 		// basically impossible to get this error.
-		glog.Errorf("Error syncing service %q: %v", key, err)
-		e.queue.Add(key) // Retry
-		return
+		utilruntime.HandleError(fmt.Errorf("Error syncing service %q: %v", key, err))
```
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Fixed.

File: pkg/controller/endpoint/endpoints_controller.go (hunk 2 above)
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Fixed.

File: pkg/controller/endpoint/endpoints_controller.go [hunk 6]
```diff
@@ -513,8 +521,9 @@ func (e *EndpointController) syncService(key string) {
 		} else {
 			utilruntime.HandleError(err)
```
Comment (m1093782566) [inline pkg/controller/endpoint/endpoints_controller.go]: Will remove
```
else {
                        utilruntime.HandleError(err)
                }
```

File: contrib/mesos/pkg/service/endpoints_controller.go [hunk 7]
```diff
@@ -219,7 +219,7 @@ func (e *endpointController) deletePod(obj interface{}) {
 func (e *endpointController) enqueueService(obj interface{}) {
 	key, err := keyFunc(obj)
 	if err != nil {
-		glog.Errorf("Couldn't get key for object %+v: %v", obj, err)
+		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", obj, err))
```
Comment (deads2k) [inline contrib/mesos/pkg/service/endpoints_controller.go]: This was bugged before.  If you don't have a key, you need to return here.

File: contrib/mesos/pkg/service/endpoints_controller.go [hunk 8]
```diff
@@ -230,24 +230,35 @@ func (e *endpointController) enqueueService(obj interface{}) {
...
+	for e.processNextWorkItem() {
+	}
+}
+
+func (e *endpointController) processNextWorkItem() bool {
+	eKey, quit := e.queue.Get()
+	if quit {
+		return false
 	}
+	// Use defer: in the unlikely event that there's a
```
Comment (deads2k) [inline contrib/mesos/pkg/service/endpoints_controller.go]: no need for this comment

File: contrib/mesos/pkg/service/endpoints_controller.go [hunk 9]
```diff
@@ -261,33 +272,32 @@ func (e *endpointController) syncService(key string) {
...
+			utilruntime.HandleError(fmt.Errorf("Need to delete endpoint with key %q, but couldn't understand the key: %v", key, err))
 			// Don't retry, as the key isn't going to magically become understandable.
-			return
+			return nil
 		}
 		err = e.client.Endpoints(namespace).Delete(name, nil)
 		if err != nil && !errors.IsNotFound(err) {
-			glog.Errorf("Error deleting endpoint %q: %v", key, err)
-			e.queue.Add(key) // Retry
+			utilruntime.HandleError(fmt.Errorf("Error deleting endpoint %q: %v", key, err))
```
Comment (deads2k) [inline contrib/mesos/pkg/service/endpoints_controller.go]: don't output here since we'll report it later.

**Comment by deads2k** [comment]
lgtm, squash for merge.

**Comment by deads2k** [comment]
huh, I can't seem to figure out how to clear outdated comments with the new interface.

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by m1093782566** [comment]
There should be a "x" in the upper right of comments, did you try it?

**Comment by m1093782566** [comment]
code rebased.

**Comment by m1093782566** [comment]
@deads2k 

CI passed.

**Comment by m1093782566** [comment]
k8s.io/kubernetes/pkg/registry/poddisruptionbudget/etcd TestWatch 33s

go test -v k8s.io/kubernetes/pkg/registry/poddisruptionbudget/etcd -run TestWatch$

resttest.go:1251: unexpected timeout from result channelfrom 
junit_05d5a39770f1e642b026f49319438a74d93cb6bb_20160916-075244.xml

**Comment by kevin-wangzefeng** [comment]
@k8s-bot unit test this please, issue #32770
