### PR TITLE
Issue 79147: Do not delete an incorrect pod when replacing a mirror pod

### LINKED ISSUE #79147: kubectl delete of a static pod results in multiple attempts to re-create the mirror pod before succeeding
**What happened**: `kubectl delete` of a static pod (really the mirror pod) results in multiple attempts to re-create the mirror pod before it finally succeeds (note that in some runs it goes into Running or Terminating state -- it just depends upon the exact timing of the `kubectl get pod`.
Note that in the below trace the pod name is elided from the `kubectl get pod` output.

Note that the actual static pod continues to run as normal.

```
pod "static-test-ip-10-0-133-116.ec2.internal" deleted
 1: Mon 17 Jun 2019 10:27:28 AM EDT    0/2   Pending   0     0s
 2: Mon 17 Jun 2019 10:27:29 AM EDT    0/2   Pending   0     1s
 3: Mon 17 Jun 2019 10:27:31 AM EDT    0/2   Pending   0     0s
 4: Mon 17 Jun 2019 10:27:32 AM EDT    0/2   Pending   0     0s
 5: Mon 17 Jun 2019 10:27:33 AM EDT    0/2   Pending   0     1s
 6: Mon 17 Jun 2019 10:27:35 AM EDT    0/2   Pending   0     0s
 7: Mon 17 Jun 2019 10:27:36 AM EDT    2/2   Running   0     0s
 8: Mon 17 Jun 2019 10:27:37 AM EDT    2/2   Running   0     1s
 9: Mon 17 Jun 2019 10:27:38 AM EDT    2/2   Running   0     3s
10: Mon 17 Jun 2019 10:27:40 AM EDT    2/2   Running   0     4s
11: Mon 17 Jun 2019 10:27:41 AM EDT    2/2   Running   0     5s
12: Mon 17 Jun 2019 10:27:42 AM EDT    2/2   Running   0     7s
13: Mon 17 Jun 2019 10:27:44 AM EDT    2/2   Running   0     8s
14: Mon 17 Jun 2019 10:27:45 AM EDT    2/2   Running   0     9s
15: Mon 17 Jun 2019 10:27:46 AM EDT    2/2   Running   0     11s
16: Mon 17 Jun 2019 10:27:48 AM EDT    2/2   Running   0     12s
```

**What you expected to happen**:
Mirror pod should start without additional state transitions

**How to reproduce it (as minimally and precisely as possible)**:
Create a static pod, `kubectl delete` it, and 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14/OpenShift 4.2 (master has the same code)
- Cloud provider or hardware configuration: AWS (not relevant)
- OS (e.g: `cat /etc/os-release`): Not relevant
- Kernel (e.g. `uname -a`): Not relevant
- Install tools: Not relevant
- Network plugin and version (if this is a network-related bug): N/A
- Others:

### PR DESCRIPTION
**Pull request by RobertKrawitz**
/kind bug

**What this PR does / why we need it**: `kubectl delete` of a static pod results in the mirror pod being re-created multiple times prior to finally settling down.

**Which issue(s) this PR fixes**:

Fixes #79147

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

File: pkg/kubelet/pod/mirror_client.go [hunk 1]
```diff
@@ -82,6 +85,16 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string) error {
...
 		return err
 	}
+	if uid != nil {
+		if apiPod, err := mc.apiserverClient.CoreV1().Pods(namespace).Get(name, metav1.GetOptions{}); err == nil {
+			klog.Infof("DeleteMirrorPod %s: requested UID %s actual %s", podFullName, *uid, apiPod.ObjectMeta.UID)
+			if apiPod.ObjectMeta.UID != *uid {
+				return fmt.Errorf("UID of pod %q (%s) does not match requested UID (%s); not deleting mirror pod", podFullName, apiPod.ObjectMeta.UID, *uid)
+			}
+		} else {
+			return fmt.Errorf("Unable to retrieve pod %s", podFullName)
```
Comment (tedyu) [inline pkg/kubelet/pod/mirror_client.go]: Should err be included in the message ?

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1629,10 +1630,12 @@ func (kl *Kubelet) syncPod(o syncPodOptions) error {
 			if mirrorPod.DeletionTimestamp != nil || !kl.podManager.IsMirrorPodOf(mirrorPod, pod) {
 				// The mirror pod is semantically different from the static pod. Remove
 				// it. The mirror pod will get recreated later.
-				klog.Warningf("Deleting mirror pod %q because it is outdated", format.Pod(mirrorPod))
-				if err := kl.podManager.DeleteMirrorPod(podFullName); err != nil {
-					klog.Errorf("Failed deleting mirror pod %q: %v", format.Pod(mirrorPod), err)
+				if err := kl.podManager.DeleteMirrorPod(podFullName, &mirrorPod.ObjectMeta.UID); err != nil {
+					if !strings.Contains(err.Error(), "does not match requested UID") {
```
Comment (tedyu) [inline pkg/kubelet/kubelet.go]: I searched codebase but didn't seem to find where the "does not match requested" message came from.

File: pkg/kubelet/pod/testing/fake_mirror_client.go [hunk 3]
```diff
@@ -52,7 +53,7 @@ func (fmc *FakeMirrorClient) CreateMirrorPod(pod *v1.Pod) error {
 	return nil
 }
 
-func (fmc *FakeMirrorClient) DeleteMirrorPod(podFullName string) error {
+func (fmc *FakeMirrorClient) DeleteMirrorPod(podFullName string, _ *types.UID) error {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/pod/testing/fake_mirror_client.go]: Based on https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79148/pull-kubernetes-verify/1141115008302714880, I think we may be missing some updates to `DeleteMirrorPod`.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (mattjmcnaughton) [reply pkg/kubelet/kubelet.go]: +1 at a high level, it seems like relying on the string content of error messages to stay the same is fairly risky. Is there a different way we can determine if we failed to delete the mirror pod?

File: pkg/kubelet/pod/mirror_client.go [hunk 4]
```diff
@@ -82,6 +85,16 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string) error {
...
+		}
+	}
 	klog.V(2).Infof("Deleting a mirror pod %q", podFullName)
 	// TODO(random-liu): Delete the mirror pod with uid precondition in mirror pod manager
```
Comment (mattjmcnaughton) [inline pkg/kubelet/pod/mirror_client.go]: Can we delete this TODO? Am I understanding correctly that this is what you are doing?

File: pkg/kubelet/pod/mirror_client.go [hunk 5]
```diff
@@ -82,6 +85,16 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string) error {
...
 	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(name, metav1.NewDeleteOptions(0)); err != nil && !errors.IsNotFound(err) {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/pod/mirror_client.go]: Is there not still a race condition in that while we check that the pod with the name we will use for the delete has the proper uid, there is then a small window between when we perform that check and when we actually delete the pod?

Is there anyway to use both name and uid as a filter when we delete the pod?

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your careful thought on this and the quick fix after the issue was filed!

File: pkg/kubelet/pod/mirror_client.go (hunk 1 above)
Comment (sjenning) [reply pkg/kubelet/pod/mirror_client.go]: also we should probably say "mirror pod"

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (sjenning) [reply pkg/kubelet/kubelet.go]: @tedyu it is added in this PR on (new) line 92 of `mirror_client.go`

File: pkg/kubelet/pod/mirror_client.go (hunk 1 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yes and yes.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (RobertKrawitz) [reply pkg/kubelet/kubelet.go]: I don't like relying on string content of error messages myself; I've seen it done all too often.  A routine to check the error (so abstracting away the error message) may be the way to go.

There's still a potential race condition here; the window is just much smaller.

File: pkg/kubelet/pod/testing/fake_mirror_client.go (hunk 3 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/testing/fake_mirror_client.go]: Looking at that today.

File: pkg/kubelet/pod/mirror_client.go (hunk 4 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yes, that's why I'd like @Random-Liu to comment.

File: pkg/kubelet/pod/mirror_client.go (hunk 5 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yes, that race condition still exists; the window is just much smaller.  In this context I think that's a reasonable tradeoff if I can't find anything better.  I didn't find a way to use both the name and UID, but I do intend to research this a bit more.

Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: ...that, of course, is what the preconditions are for...

File: pkg/kubelet/pod/mirror_client.go [hunk 6]
```diff
@@ -82,6 +85,16 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string) error {
 		klog.Errorf("Failed to parse a pod full name %q", podFullName)
 		return err
 	}
+	if uid != nil {
+		if apiPod, err := mc.apiserverClient.CoreV1().Pods(namespace).Get(name, metav1.GetOptions{}); err == nil {
+			klog.Infof("DeleteMirrorPod %s: requested UID %s actual %s", podFullName, *uid, apiPod.ObjectMeta.UID)
+			if apiPod.ObjectMeta.UID != *uid {
+				return fmt.Errorf("UID of pod %q (%s) does not match requested UID (%s); not deleting mirror pod", podFullName, apiPod.ObjectMeta.UID, *uid)
```
Comment (tedyu) [inline pkg/kubelet/pod/mirror_client.go]: Along with error, you can also return whether the error was due to UID mismatch.
This way, we don't rely on string content for this condition.

File: pkg/kubelet/pod/mirror_client.go (hunk 1 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: This goes away; it's all in DeleteMirrorPod now.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (RobertKrawitz) [reply pkg/kubelet/kubelet.go]: Unfortunately, I may have to rely on the error message within DeleteMirrorPod.  There are a lot of generic errors, but the one generated by a failed precondition isn't one of them.  I don't know the rules about making changes to staging, but if I can change `staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go` I could add this as a generic error.

File: pkg/kubelet/pod/testing/fake_mirror_client.go (hunk 3 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/testing/fake_mirror_client.go]: Finally got to that this morning.  We'll see in this test run where there are any further updates I need to make.

File: pkg/kubelet/pod/mirror_client.go (hunk 4 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Doing so, because I'm using the uid precondition.

File: pkg/kubelet/pod/mirror_client.go (hunk 5 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: ...and using the precondition eliminates the race (I presume).

File: pkg/kubelet/pod/mirror_client.go (hunk 6 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: See above comment about string content (which I've moved, for now at least, into DeleteMirrorPod).

I'm returning two values from DeleteMirrorPod, a bool to indicate whether the pod was actually deleted (so the caller knows whether it should try to recreate it) and an error if something other than not found or UID mismatch (which is really the same thing) happened.

File: pkg/kubelet/pod/mirror_client.go [hunk 7]
```diff
@@ -73,21 +76,29 @@ func (mc *basicMirrorClient) CreateMirrorPod(pod *v1.Pod) error {
 	return err
 }
 
-func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string) error {
+func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string, uid *types.UID) (bool, error) {
```
Comment (tedyu) [inline pkg/kubelet/pod/mirror_client.go]: Better add godoc explaining the bool return value.

File: pkg/kubelet/pod/mirror_client.go [hunk 8]
```diff
@@ -73,21 +76,29 @@ func (mc *basicMirrorClient) CreateMirrorPod(pod *v1.Pod) error {
...
-	// TODO(random-liu): Delete the mirror pod with uid precondition in mirror pod manager
-	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(name, metav1.NewDeleteOptions(0)); err != nil && !errors.IsNotFound(err) {
-		klog.Errorf("Failed deleting a mirror pod %q: %v", podFullName, err)
+	klog.V(2).Infof("Deleting a mirror pod %q (uid %#v)", podFullName, uid)
+	var GracePeriodSeconds int64
+	GracePeriodSeconds = 0
+	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(name, &metav1.DeleteOptions{GracePeriodSeconds: &GracePeriodSeconds, Preconditions: &metav1.Preconditions{UID: uid}}); err != nil {
+		// Unfortunately, there's no generic error for failing a precondition
+		if !(errors.IsNotFound(err) ||
+			strings.Contains(err.Error(), "object might have been deleted and then recreated")) {
```
Comment (tedyu) [inline pkg/kubelet/pod/mirror_client.go]: This message comes from BeforeDelete(), right ?

Please consider refactoring BeforeDelete() so that a new flag is returned and we don't need to depend on string content.

File: pkg/kubelet/pod/mirror_client.go (hunk 7 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Done.

File: pkg/kubelet/pod/mirror_client.go (hunk 8 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yes, it comes from BeforeDelete.  I may be able to solve this a different way, but I won't be able to check until tomorrow.  Refactoring BeforeDelete on its own won't be sufficient; the problem is with its callers also.

File: pkg/kubelet/kubelet.go [hunk 9]
```diff
@@ -1629,11 +1629,14 @@ func (kl *Kubelet) syncPod(o syncPodOptions) error {
...
-				klog.Warningf("Deleting mirror pod %q because it is outdated", format.Pod(mirrorPod))
-				if err := kl.podManager.DeleteMirrorPod(podFullName); err != nil {
-					klog.Errorf("Failed deleting mirror pod %q: %v", format.Pod(mirrorPod), err)
-				} else {
+				klog.Infof("Trying to delete pod %s %v", podFullName, mirrorPod.ObjectMeta.UID)
+				var err error
+				deleted, err = kl.podManager.DeleteMirrorPod(podFullName, &mirrorPod.ObjectMeta.UID)
+				if deleted {
+					klog.Warningf("Deleted mirror pod %q because it is outdated", format.Pod(mirrorPod))
 					deleted = true
```
Comment (tedyu) [inline pkg/kubelet/kubelet.go]: This is redundant (deleted is already true).

File: pkg/kubelet/pod/mirror_client.go (hunk 7 above)
Comment (tedyu) [reply pkg/kubelet/pod/mirror_client.go]: and UID mismatch are -> or UID mismatch is

since the two conditions may not hold at the same time.

File: pkg/kubelet/kubelet.go (hunk 9 above)
Comment (RobertKrawitz) [reply pkg/kubelet/kubelet.go]: Yes, left over from earlier code.

File: pkg/kubelet/pod/mirror_client.go (hunk 7 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yeah, OK...

File: pkg/kubelet/pod/mirror_client.go (hunk 8 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: OK, found the right way to do it.

File: pkg/kubelet/pod/mirror_client.go [hunk 10]
```diff
@@ -73,21 +74,35 @@ func (mc *basicMirrorClient) CreateMirrorPod(pod *v1.Pod) error {
...
-	klog.V(2).Infof("Deleting a mirror pod %q", podFullName)
-	// TODO(random-liu): Delete the mirror pod with uid precondition in mirror pod manager
-	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(name, metav1.NewDeleteOptions(0)); err != nil && !errors.IsNotFound(err) {
-		klog.Errorf("Failed deleting a mirror pod %q: %v", podFullName, err)
+	klog.V(2).Infof("Deleting a mirror pod %q (uid %#v)", podFullName, uid)
+	var GracePeriodSeconds int64
+	GracePeriodSeconds = 0
+	if err := mc.apiserverClient.CoreV1().Pods(namespace).Delete(name, &metav1.DeleteOptions{GracePeriodSeconds: &GracePeriodSeconds, Preconditions: &metav1.Preconditions{UID: uid}}); err != nil {
+		// Unfortunately, there's no generic error for failing a precondition
+		if ! (errors.IsNotFound(err) || errors.IsConflict(err)) {
```
Comment (tedyu) [inline pkg/kubelet/pod/mirror_client.go]: Is there a test covering the errors.IsConflict() condition ?

Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Yes, `staging/src/k8s.io/apimachinery/pkg/api/errors/errors_test.go` (this is an existing routine).

**Comment by mattjmcnaughton** [comment]
/test pull-kubernetes-bazel-test

Gonna let @tedyu finish out the review from here. Imo this is heading in a great direction. I'll let @tedyu and an approver give the final sign off. Thanks again for your work on this :)

File: pkg/kubelet/kubelet.go (hunk 9 above)
Comment (RobertKrawitz) [reply pkg/kubelet/kubelet.go]: Fixed.

File: pkg/kubelet/pod/mirror_client.go (hunk 8 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

File: pkg/kubelet/pod/mirror_client.go (hunk 7 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

File: pkg/kubelet/pod/mirror_client.go (hunk 6 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

File: pkg/kubelet/pod/mirror_client.go (hunk 5 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

File: pkg/kubelet/pod/mirror_client.go (hunk 4 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

File: pkg/kubelet/pod/testing/fake_mirror_client.go (hunk 3 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/testing/fake_mirror_client.go]: Fixed.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (RobertKrawitz) [reply pkg/kubelet/kubelet.go]: Fixed -- no need to rely on error messages.

File: pkg/kubelet/pod/mirror_client.go (hunk 1 above)
Comment (RobertKrawitz) [reply pkg/kubelet/pod/mirror_client.go]: Fixed.

**Review by derekwaynecarr — APPROVED** [review]
nice job debugging this!

/approve
