### PR TITLE
Fix resource leaking PDs for volume mode test

### LINKED ISSUE #74380: Volume mode test is leaking PDs
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce

**Which test(s) are failing**:
I0221 20:48:18.462] [sig-storage] In-tree Volumes
I0221 20:48:18.462] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:22[0m
I0221 20:48:18.462]   [Driver: gcepd]
I0221 20:48:18.462]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/in_tree_volumes.go:65[0m
I0221 20:48:18.462]     [Testpattern: Dynamic PV (filesystem volmode)] volumeMode
I0221 20:48:18.463]     [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:75[0m
I0221 20:48:18.463]       should create sc, pod, pv, and pvc, read/write to the pv, and delete all created resources

**Since when has it been failing**:
unsure

**Testgrid link**:
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/35080

**Reason for failure**:
From the logs, it looks like it's deleting both PVC and PV objects at the same time, which is not correct.
I0221 20:48:18.460] Feb 21 20:48:09.866: INFO: Deleting PersistentVolumeClaim "pvc-cjv2l"
I0221 20:48:18.460] Feb 21 20:48:09.923: INFO: Deleting PersistentVolume "pvc-ec76793b-3619-11e9-b923-42010a8a0002"

[This call](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/testsuites/volumemode.go#L149:22) should be changed to only delete PVC and wait for PV to be deleted by the driver.  Can it just call [CleanupResource](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/testsuites/base.go#L221) which does it correctly? 

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by mkimuram**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
This PR fixes resource leaking PDs for volume mode test. This issue is caused by deleting both PVC and PV objects at the same time, so it is fixed by calling ```genericVolumeTestResource.CleanupResource```, which does it correctly.

**Which issue(s) this PR fixes**:

Fixes #74380

**Special notes for your reviewer**:
@kubernetes/sig-storage-test-failures
cc @pohly @gnufied @msau42 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mkimuram** [comment]
@msau42 

I've checked the code and confirmed that the cause was as you indicated.
So, this PR is fixing by the way that you suggested. PTAL

@pohly 

I intended to apply the same logic used in testsuites which call ```genericVolumeTestResource```,
to utilize its ```cleanupResource``` in the volumeMode testsuite. I would appreciate it if you could check that I'm doing it correctly.

File: test/e2e/storage/testsuites/volumemode.go [hunk 1]
```diff
@@ -89,80 +85,16 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
...
-			deleteStorageClass(f.ClientSet, l.sc.Name)
-			l.sc = nil
-		}
-
-		if l.volume != nil {
-			l.volume.DeleteVolume()
-			l.volume = nil
+		if l.resource != nil {
+			l.resource.cleanupResource()
+			l.resource = nil
```
Comment (msau42) [inline test/e2e/storage/testsuites/volumemode.go]: does this need to be set to nil every time?  `l` should be recreated for every test right?

File: test/e2e/storage/testsuites/volumemode.go [hunk 2]
```diff
@@ -67,12 +66,9 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
...
 
-		cs     clientset.Interface
-		ns     *v1.Namespace
-		sc     *storagev1.StorageClass
-		pvc    *v1.PersistentVolumeClaim
-		pv     *v1.PersistentVolume
-		volume TestVolume
+		cs       clientset.Interface
+		ns       *v1.Namespace
+		resource *volumeModeTestResource
```
Comment (msau42) [inline test/e2e/storage/testsuites/volumemode.go]: you may be able to save one layer if you embed `genericVolumeTestResource` directly.

**Review by msau42 — COMMENTED** [review]
Thanks for looking at this so quickly!

File: test/e2e/storage/testsuites/volumemode.go (hunk 1 above)
Comment (mkimuram) [reply test/e2e/storage/testsuites/volumemode.go]: Thank you for quick your review.

I think @pohly 's intention was https://github.com/kubernetes/kubernetes/pull/72434#discussion_r257174085 , and I followed the same way.

File: test/e2e/storage/testsuites/volumemode.go (hunk 2 above)
Comment (mkimuram) [reply test/e2e/storage/testsuites/volumemode.go]: Actually, I moved ```cs``` and ```ns``` to ```volumeModeTestResource``` once and moved back here, because they aren't used in ```createVolumeModeTestResource``` and ```cleanupResource```. 

If your intention is different to above, or it's better to move there even above situation. Please point me out. I will update.

Comment (msau42) [reply test/e2e/storage/testsuites/volumemode.go]: What I meant was it is possible to just have `genericVolumeTestResource` directly in `local`, like this:
```
type local struct {
  config *PerTestConfig
  ...
  genericVolumeTestResource
}
```

Then you don't need to add a `.resource` everytime you need to access the pvc, pv, sc.

File: test/e2e/storage/testsuites/volumemode.go (hunk 1 above)
Comment (pohly) [reply test/e2e/storage/testsuites/volumemode.go]: If reviewers find this confusing, perhaps we should remove it everywhere? It's a bit of defensive programming, it shouldn't be absolutely needed.

**Comment by pohly** [comment]
Moving the initialization into `createVolumeModeTestResource` separates test setup and test code again, which was what was confusing before. `volumeModeTestResource` is also identical to `genericVolumeTestResource`. I suspect it might be simpler to setup a `genericVolumeTestResource` in `init` and not introduce `genericVolumeTestResource`.

What @msau42 suggested probably also helps.

Having said that, thanks a lot indeed for working on  this.

File: test/e2e/storage/testsuites/volumemode.go (hunk 2 above)
Comment (mkimuram) [reply test/e2e/storage/testsuites/volumemode.go]: Thank you for your detailed explanation. I will fix as suggested.

**Comment by mkimuram** [comment]
@msau42 @pohly 

I've refactored as suggested. PTAL
(Although the diff from the original code will be easier to be reviewed, I kept the last commit just in case. And will squash it, once this change turns out to be good.)

**Comment by mkimuram** [comment]
It seems that ```cleanupResource``` doesn't work well if pvc or pv is nil.
I'm working on fixing it.

**Comment by mkimuram** [comment]
@msau42 @pohly 

All the tests pass now. PTAL

File: test/e2e/storage/testsuites/volumemode.go [hunk 3]
```diff
@@ -104,8 +100,14 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
...
 
+		l.resource = &genericVolumeTestResource{
+			driver:  driver,
+			config:  l.config,
+			pattern: pattern,
+		}
+
 		// Create volume for pre-provisioned volume tests
-		l.volume = CreateVolume(driver, l.config, pattern.VolType)
+		l.resource.volume = CreateVolume(driver, l.config, pattern.VolType)
```
Comment (pohly) [inline test/e2e/storage/testsuites/volumemode.go]: As @msau42 had pointed out, it is possible to embed `genericVolumeTestResource` directly in `local`. Then all of these `l.resource.` variable accesses can be replaced with  `l.` (as before), and the diff becomes much smaller. However, I personally find the code easier to read the way you wrote it, so I'm in favor of merging it as proposed after squashing.

FWIW, here's a patch on top  of your PR which demonstrates the other approach:
```
diff --git a/test/e2e/storage/testsuites/volumemode.go b/test/e2e/storage/testsuites/volumemode.go
index d4d12b6094..760ab0a830 100644
--- a/test/e2e/storage/testsuites/volumemode.go
+++ b/test/e2e/storage/testsuites/volumemode.go
@@ -66,9 +66,9 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 		config      *PerTestConfig
 		testCleanup func()
 
-		cs       clientset.Interface
-		ns       *v1.Namespace
-		resource *genericVolumeTestResource
+		cs clientset.Interface
+		ns *v1.Namespace
+		genericVolumeTestResource
 	}
 	var (
 		dInfo = driver.GetDriverInfo()
@@ -100,14 +100,14 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 			volumeNodeAffinity *v1.VolumeNodeAffinity
 		)
 
-		l.resource = &genericVolumeTestResource{
+		l.genericVolumeTestResource = genericVolumeTestResource{
 			driver:  driver,
 			config:  l.config,
 			pattern: pattern,
 		}
 
 		// Create volume for pre-provisioned volume tests
-		l.resource.volume = CreateVolume(driver, l.config, pattern.VolType)
+		l.volume = CreateVolume(driver, l.config, pattern.VolType)
 
 		switch pattern.VolType {
 		case testpatterns.PreprovisionedPV:
@@ -117,28 +117,28 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 				scName = fmt.Sprintf("%s-%s-sc-for-file", l.ns.Name, dInfo.Name)
 			}
 			if pDriver, ok := driver.(PreprovisionedPVTestDriver); ok {
-				pvSource, volumeNodeAffinity = pDriver.GetPersistentVolumeSource(false, fsType, l.resource.volume)
+				pvSource, volumeNodeAffinity = pDriver.GetPersistentVolumeSource(false, fsType, l.volume)
 				if pvSource == nil {
 					framework.Skipf("Driver %q does not define PersistentVolumeSource - skipping", dInfo.Name)
 				}
 
 				storageClass, pvConfig, pvcConfig := generateConfigsForPreprovisionedPVTest(scName, volBindMode, pattern.VolMode, *pvSource, volumeNodeAffinity)
-				l.resource.sc = storageClass
-				l.resource.pv = framework.MakePersistentVolume(pvConfig)
-				l.resource.pvc = framework.MakePersistentVolumeClaim(pvcConfig, l.ns.Name)
+				l.sc = storageClass
+				l.pv = framework.MakePersistentVolume(pvConfig)
+				l.pvc = framework.MakePersistentVolumeClaim(pvcConfig, l.ns.Name)
 			}
 		case testpatterns.DynamicPV:
 			if dDriver, ok := driver.(DynamicPVTestDriver); ok {
-				l.resource.sc = dDriver.GetDynamicProvisionStorageClass(l.config, fsType)
-				if l.resource.sc == nil {
+				l.sc = dDriver.GetDynamicProvisionStorageClass(l.config, fsType)
+				if l.sc == nil {
 					framework.Skipf("Driver %q does not define Dynamic Provision StorageClass - skipping", dInfo.Name)
 				}
-				l.resource.sc.VolumeBindingMode = &volBindMode
+				l.sc.VolumeBindingMode = &volBindMode
 
 				claimSize := dDriver.GetClaimSize()
-				l.resource.pvc = getClaim(claimSize, l.ns.Name)
-				l.resource.pvc.Spec.StorageClassName = &l.resource.sc.Name
-				l.resource.pvc.Spec.VolumeMode = &pattern.VolMode
+				l.pvc = getClaim(claimSize, l.ns.Name)
+				l.pvc.Spec.StorageClassName = &l.sc.Name
+				l.pvc.Spec.VolumeMode = &pattern.VolMode
 			}
 		default:
 			framework.Failf("Volume mode test doesn't support: %s", pattern.VolType)
@@ -146,10 +146,7 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 	}
 
 	cleanup := func() {
-		if l.resource != nil {
-			l.resource.cleanupResource()
-			l.resource = nil
-		}
+		l.cleanupResource()
 
 		if l.testCleanup != nil {
 			l.testCleanup()
@@ -169,22 +166,22 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 				var err error
 
 				By("Creating sc")
-				l.resource.sc, err = l.cs.StorageV1().StorageClasses().Create(l.resource.sc)
+				l.sc, err = l.cs.StorageV1().StorageClasses().Create(l.sc)
 				Expect(err).NotTo(HaveOccurred())
 
 				By("Creating pv and pvc")
-				l.resource.pv, err = l.cs.CoreV1().PersistentVolumes().Create(l.resource.pv)
+				l.pv, err = l.cs.CoreV1().PersistentVolumes().Create(l.pv)
 				Expect(err).NotTo(HaveOccurred())
 
 				// Prebind pv
-				l.resource.pvc.Spec.VolumeName = l.resource.pv.Name
-				l.resource.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.resource.pvc)
+				l.pvc.Spec.VolumeName = l.pv.Name
+				l.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.pvc)
 				Expect(err).NotTo(HaveOccurred())
 
-				framework.ExpectNoError(framework.WaitOnPVandPVC(l.cs, l.ns.Name, l.resource.pv, l.resource.pvc))
+				framework.ExpectNoError(framework.WaitOnPVandPVC(l.cs, l.ns.Name, l.pv, l.pvc))
 
 				By("Creating pod")
-				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.resource.pvc},
+				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.pvc},
 					false, "", false, false, framework.SELinuxLabel,
 					nil, l.config.ClientNodeName, framework.PodStartTimeout)
 				defer func() {
@@ -200,22 +197,22 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 				var err error
 
 				By("Creating sc")
-				l.resource.sc, err = l.cs.StorageV1().StorageClasses().Create(l.resource.sc)
+				l.sc, err = l.cs.StorageV1().StorageClasses().Create(l.sc)
 				Expect(err).NotTo(HaveOccurred())
 
 				By("Creating pv and pvc")
-				l.resource.pv, err = l.cs.CoreV1().PersistentVolumes().Create(l.resource.pv)
+				l.pv, err = l.cs.CoreV1().PersistentVolumes().Create(l.pv)
 				Expect(err).NotTo(HaveOccurred())
 
 				// Prebind pv
-				l.resource.pvc.Spec.VolumeName = l.resource.pv.Name
-				l.resource.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.resource.pvc)
+				l.pvc.Spec.VolumeName = l.pv.Name
+				l.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.pvc)
 				Expect(err).NotTo(HaveOccurred())
 
-				framework.ExpectNoError(framework.WaitOnPVandPVC(l.cs, l.ns.Name, l.resource.pv, l.resource.pvc))
+				framework.ExpectNoError(framework.WaitOnPVandPVC(l.cs, l.ns.Name, l.pv, l.pvc))
 
 				By("Creating pod")
-				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.resource.pvc},
+				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.pvc},
 					false, "", false, false, framework.SELinuxLabel,
 					nil, l.config.ClientNodeName, framework.PodStartTimeout)
 				defer func() {
@@ -240,14 +237,14 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 				var err error
 
 				By("Creating sc")
-				l.resource.sc, err = l.cs.StorageV1().StorageClasses().Create(l.resource.sc)
+				l.sc, err = l.cs.StorageV1().StorageClasses().Create(l.sc)
 				Expect(err).NotTo(HaveOccurred())
 
 				By("Creating pv and pvc")
-				l.resource.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.resource.pvc)
+				l.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.pvc)
 				Expect(err).NotTo(HaveOccurred())
 
-				err = framework.WaitForPersistentVolumeClaimPhase(v1.ClaimBound, l.cs, l.resource.pvc.Namespace, l.resource.pvc.Name, framework.Poll, framework.ClaimProvisionTimeout)
+				err = framework.WaitForPersistentVolumeClaimPhase(v1.ClaimBound, l.cs, l.pvc.Namespace, l.pvc.Name, framework.Poll, framework.ClaimProvisionTimeout)
 				Expect(err).To(HaveOccurred())
 			})
 		} else {
@@ -258,24 +255,24 @@ func (t *volumeModeTestSuite) defineTests(driver TestDriver, pattern testpattern
 				var err error
 
 				By("Creating sc")
-				l.resource.sc, err = l.cs.StorageV1().StorageClasses().Create(l.resource.sc)
+				l.sc, err = l.cs.StorageV1().StorageClasses().Create(l.sc)
 				Expect(err).NotTo(HaveOccurred())
 
 				By("Creating pv and pvc")
-				l.resource.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.resource.pvc)
+				l.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.ns.Name).Create(l.pvc)
 				Expect(err).NotTo(HaveOccurred())
 
-				err = framework.WaitForPersistentVolumeClaimPhase(v1.ClaimBound, l.cs, l.resource.pvc.Namespace, l.resource.pvc.Name, framework.Poll, framework.ClaimProvisionTimeout)
+				err = framework.WaitForPersistentVolumeClaimPhase(v1.ClaimBound, l.cs, l.pvc.Namespace, l.pvc.Name, framework.Poll, framework.ClaimProvisionTimeout)
 				Expect(err).NotTo(HaveOccurred())
 
-				l.resource.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.resource.pvc.Namespace).Get(l.resource.pvc.Name, metav1.GetOptions{})
+				l.pvc, err = l.cs.CoreV1().PersistentVolumeClaims(l.pvc.Namespace).Get(l.pvc.Name, metav1.GetOptions{})
 				Expect(err).NotTo(HaveOccurred())
 
-				l.resource.pv, err = l.cs.CoreV1().PersistentVolumes().Get(l.resource.pvc.Spec.VolumeName, metav1.GetOptions{})
+				l.pv, err = l.cs.CoreV1().PersistentVolumes().Get(l.pvc.Spec.VolumeName, metav1.GetOptions{})
 				Expect(err).NotTo(HaveOccurred())
 
 				By("Creating pod")
-				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.resource.pvc},
+				pod, err := framework.CreateSecPodWithNodeName(l.cs, l.ns.Name, []*v1.PersistentVolumeClaim{l.pvc},
 					false, "", false, false, framework.SELinuxLabel,
 					nil, l.config.ClientNodeName, framework.PodStartTimeout)
 				defer func() {
```

**Comment by mkimuram** [comment]
@pohly 

Thank you for your explanation. And your approach looks much simpler, after I know that only embedded struct could be initialized by that way. I prefer to apply this change.

**Comment by pohly** [comment]
> I prefer to apply this change.

Okay. When you do that, can you add a short comment like this:
```
typedef local struct {
   ...
   genericVolumeTestResource // contains pv, pvc, sc, etc., owns cleaning that up
}
```

That'll help future readers who don't know what a `genericVolumeTestResource` is and why we use it here. Also avoids the confusion when someone looks for `l.pv`...

**Comment by mariantalla** [comment]
The failures seem to be due to gcp account issues, is this one for [test-infra](https://github.com/kubernetes/test-infra)?

**Comment by msau42** [comment]
Serial csi failures are known flakes: https://github.com/kubernetes/kubernetes/issues/72500
