### PR TITLE
probeAttachedVolume improvement in Cinder

### LINKED ISSUE #55007: kubelet starts too many `udevadm trigger`
/kind bug

**What happened**:
kubelet creates too many udev "change" events during Cinder volume attachment.
If volume attachement takes long, then udev event queue gets full, therefore
udev does not answer requests from docker, and PLEG makes the k8s node unhealthy.

**What you expected to happen**:
  * kubelet should not run `udevadm trigger` so often.
  * kubelet should run `udevadm settle --timeout=1 && udevadm trigger`

**How to reproduce it (as minimally and precisely as possible)**:
Deploy k8s on Openstack. Configure k8s cluster with --cloud_provider=openstack.
  * Cordon all nodes except one.
  * SSH into that node. Start `udevadm monitor` and let it run.
  * Create StorateClass for Cinder volumes.
  * Deploy StatefulSet with volumeClaimTemplate pointing to that StorageClass.
  * Optionally, immediately detatch the newly-created cinder volume manually
    through openstack CLI or web interface to simulate a slow cinder attachment.
  * Look back to the `udevadm monitor` to find thousands of udev events.
    In case of the "show" attachement, the "change" udev events will never stop.
  * Also run `top` to find that systemd-udevd consumes 100% CPU.
  * Also run `docker ps` to find that it hangs and never answers.

**Anything else we need to know?**:
Attachment of a new cinder volume includes execution of `udevadm trigger`
command, see links (1-3) below. The `udevadm trigger` generates a "change"
event for every single device on the /sys/devices SysFS. This can be seen by
running `udevadm monitor`.

The execution stack is as follows:
  * Volume Attacher Interface (1) runs WaitForAttach(), which is implemented in (2).
  * The Cinder's WaitForAttach() runs probeAttachedVolume() 2 times per second
    (lines 243 and 247). The "1 second" retry timeout is defined by (3).
  * The probeAttachedVolume() is defined in (4). It triggers SCSI rescan and
    generates udev "change" event on all devices by running `udevadm trigger`.

As you see, both scsi rescan and full udev rescan are triggered 2 times per second.

The scsi bus rescan leads to considerable latency of runnig I/O operations.

The sysemd-udevd is unable to process so many "change" events. The udev queue
gets full, leading to frozen `docker ps` operation that cAdvisor runs every 2 seconds.
After 3 minutes, kubelet marks itself unhealthy (5) due to PLEG (6).

(1) [Volume Attacher interface runs WaitForAttach()](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/volume.go#L176)
(2) [Cinder Attacher implementation of WaitForAttach()](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/cinder/attacher.go#L224)
(3) [1 second retry timeout](https://github.com/kubernetes/kubernetes/blob/2723e06a251a4ec3ef241397217e73fa782b0b98/pkg/volume/cinder/attacher.go#L237)
(4) [probeAttachedVolume()](https://github.com/kubernetes/kubernetes/blob/fc8bfe2d8929e11a898c4557f9323c482b5e8842/pkg/volume/cinder/cinder_util.go#L222)
(5) [PLEG healthcheck](https://github.com/kubernetes/kubernetes/blob/eb658d699ac074ef2a6f3808b13aacc6adfca786/pkg/kubelet/kubelet.go#L748)
(6) [PLEG implementation](https://github.com/kubernetes/kubernetes/blob/d196a4abbbf3f1ca458908abd42267b521a6faff/pkg/kubelet/pleg/generic.go#L133)

**Environment**:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: VmWare-integrated Openstack (ViO)
- OS (e.g. from /etc/os-release): PRETTY_NAME="CentOS Linux 7 (Core)"
- Kernel (e.g. `uname -a`): Linux os1pi013-kube-node02.novalocal 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: saltstack scripts.
- Others: docker-1.12.5-14.el7.centos

### PR DESCRIPTION
**Pull request by edisonxiang**
What this PR does / why we need it:

During OpenStack Cinder volume attachment, kubelet creates too many udev "change" events.
If volume attachement takes long, then udev event queue gets full,therefore
udev does not answer requests from docker, and makes Kubernetes node unhealthy.

This patch will extend the udevadm trigger period,
and use the udevadm settle to ensure that any device nodes
have been created successfully before proceeding.

Fixes #55007

Release note:

```release-note
None
```

/cc @dims @kabakaev

### CODE REVIEW

**Comment by dims** [comment]
cc @jungleboyj @stmcginnis

File: pkg/volume/cinder/attacher.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ var _ volume.Attacher = &cinderDiskAttacher{}
 var _ volume.AttachableVolumePlugin = &cinderPlugin{}
 
 const (
-	checkSleepDuration       = 1 * time.Second
+	checkSleepDuration       = 5 * time.Second
```
Comment (jsafrane) [inline pkg/volume/cinder/attacher.go]: Should there be an exponential backoff instead of linear? Start with 1 second, then 2, 4, 8, ...

Comment (jungleboyj) [reply pkg/volume/cinder/attacher.go]: Agree that doing this as a backoff is a good idea.

File: pkg/volume/cinder/cinder_util.go [hunk 2]
```diff
@@ -224,6 +224,18 @@ func probeAttachedVolume() error {
...
+
+	// udevadm settle waits for udevd to process the device creation
+	// events for all hardware devices, thus ensuring that any device
+	// nodes have been created successfully before proceeding.
+	argsSettle := []string{"settle", "--timeout=1"}
+	cmdSettle := executor.Command("udevadm", argsSettle...)
+	_, errSettle := cmdSettle.CombinedOutput()
+	if errSettle != nil {
+		glog.Errorf("error running udevadm settle %v\n", errSettle)
+		return errSettle
```
Comment (rootfs) [inline pkg/volume/cinder/cinder_util.go]: I don't see any reference about errors in udevadm man page, but I don't think it should exit here (devices could settle later)

Comment (stmcginnis) [reply pkg/volume/cinder/cinder_util.go]: The default for settle is 120 seconds. 1 second is still an eternity at runtime, but would be good to increase that or have some retries on here before giving up.

File: pkg/volume/cinder/attacher.go (hunk 1 above)
Comment (stmcginnis) [reply pkg/volume/cinder/attacher.go]: Agreed. Most of the time it's fine, but I've seen cases where things get in a weird state where we haven't been able to get things in the right state after multiple retries with increasing backoff times.

Comment (edisonxiang) [reply pkg/volume/cinder/attacher.go]: @jsafrane, @jungleboyj, stmcginnis, Thanks your suggestions.
The latest commit has used an exponential backoff instead of linear.

File: pkg/volume/cinder/cinder_util.go (hunk 2 above)
Comment (edisonxiang) [reply pkg/volume/cinder/cinder_util.go]: @rootfs @stmcginnis Thanks very much. 
The latest commit has removed the exit for udevadm settle error,
and used the default settle command without --timeout.

**Comment by dims** [comment]
@edisonxiang - not sure if you saw this other PR - https://github.com/kubernetes/kubernetes/pull/55217/commits/85c458e2118d8ae1352a1deb95a9bb14e1c1a2f8

File: pkg/volume/cinder/attacher.go [hunk 3]
```diff
@@ -234,33 +271,8 @@ func (attacher *cinderDiskAttacher) WaitForAttach(spec *volume.Spec, devicePath
...
-			} else {
-				// Log an error, and continue checking periodically
-				glog.Errorf("Error: could not find attached Cinder disk %q (path: %q): %v", volumeID, devicePath, err)
-			}
-		case <-timer.C:
-			return "", fmt.Errorf("Could not find attached Cinder disk %q. Timeout waiting for mount paths to be created.", volumeID)
-		}
-	}
+	// Using exponential backoff instead of linear
+	return attacher.waitProbeVolume(devicePath, volumeID)
```
Comment (jsafrane) [inline pkg/volume/cinder/attacher.go]: previously, the `timeout` parameter was taken into account and now it is not. The max. wait time is 1023 seconds now.

File: pkg/volume/cinder/cinder_util.go (hunk 2 above)
Comment (kabakaev) [reply pkg/volume/cinder/cinder_util.go]: @edisonxiang, running the `udevadm settle` without the `--timeout=1` option will result in too many running `udevadm settle` processes and higher RAM and CPU usage. As mentioned in the #55007 , the func probeAttachedVolume() is run from WaitForAttach() every second, no matter if it returns anything or continues running. Therefore, the default udevadm timeout of 120 seconds makes no sense, and actually nothing longer than 1 second makes no sense either.

Comment (kabakaev) [reply pkg/volume/cinder/cinder_util.go]: @rootfs , i quite liked the original solution proposed by @edisonxiang with `udevadm settle --timeout=1`. The settle seems to be designed specifically for our case, and it does return non-zero exit code if udevd is busy processing the kernel message queue. The last command in the example given below returns exit code = 1. @stmcginnis, retries and timeouts are implemented in the calling functions.

```
# time udevadm settle ; echo $?
real    0m0.002s
user    0m0.002s
sys     0m0.000s
0

# for i in `seq 100`; do udevadm trigger; done & sleep 1; time udevadm settle ; echo $?
[1] 13262
[1]+  Done                    for i in `seq 100`;
do
    udevadm trigger;
done
real    0m11.074s
user    0m0.174s
sys     0m0.699s
0

# for i in `seq 100`; do udevadm trigger; done & sleep 1; time udevadm settle --timeout=1 ; echo $?
[1] 14106

real    0m1.046s
user    0m0.000s
sys     0m0.001s
1
```

Comment (jsafrane) [reply pkg/volume/cinder/cinder_util.go]: @kabakaev, I am not able to see where this code runs too many `udevadm settle` processes. Looking at `WaitForAttach` and `probeAttachedVolume`, they will run sequentially, I can't see any parallelism there.

Every 1, 2, 4, 8, ... seconds SCSI rescan happens, we wait until it's processed by udev and then check if the device is present. With `--timeout=1`, we don't give udev enough time to process old events and start a new SCSI rescan, which will load udev even more.

**Comment by jsafrane** [comment]
/lgtm cancel
For sake of the discussion about settle timeout.

File: pkg/volume/cinder/cinder_util.go (hunk 2 above)
Comment (kabakaev) [reply pkg/volume/cinder/cinder_util.go]: @jsafrane , i stand corrected, the `WaitForAttach` indeed calls `probeAttachedVolume()` synchronously and waits for it to finish. So yes, the timeout of 120 seconds is reasonable. lgtm! 
Sorry for unnecessary notifications to edisonxiang, stmcginnis, and rootfs.

Comment (edisonxiang) [reply pkg/volume/cinder/cinder_util.go]: Thanks @jsafrane.
Hi @kabakaev, hope this patch will resolve your issue.

**Comment by edisonxiang** [comment]
Hi @dims, Thanks for remind [the other PR](https://github.com/kubernetes/kubernetes/commit/85c458e2118d8ae1352a1deb95a9bb14e1c1a2f8) ,
This PR will do better improvement for the use case:)

File: pkg/volume/cinder/attacher.go [hunk 4]
```diff
@@ -44,7 +44,8 @@ var _ volume.Attacher = &cinderDiskAttacher{}
 var _ volume.AttachableVolumePlugin = &cinderPlugin{}
 
 const (
-	checkSleepDuration       = 1 * time.Second
+	probeVolumeInitDealy     = 1 * time.Second
```
Comment (kabakaev) [inline pkg/volume/cinder/attacher.go]: @edisonxiang 
Typo: probeVolumeInitDealy
Should be: probeVolumeInitDelay
Also please rename in other places below.

**Comment by kabakaev** [comment]
@edisonxiang , not sure if you've received my inline comment. There is a typo: probeVolumeInitDealy

**Review by dims — APPROVED** [review]

**Comment by dims** [comment]
cc @FengyunPan @anguslees

File: pkg/volume/cinder/attacher.go (hunk 4 above)
Comment (edisonxiang) [reply pkg/volume/cinder/attacher.go]: @kabakaev Thanks, I will submit another commit.
