### PR TITLE
kubeadm: add support of imagePullPolicy to kubeadm

### LINKED ISSUE #524: support imagePullPolicy when pulling kubeadm images
## Is this a request for help?
Bug / Help and possibly implement a fix for the bug 

similar closed issue : https://github.com/kubernetes/kubeadm/issues/34 

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version = kubeadm_1.8.2-00
```
ubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:38:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T19:48:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**: AWS in isolated vpc.
- **OS** (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`): 
Linux ip-10-205-78-6 4.4.0-1039-aws #48-Ubuntu SMP Wed Oct 11 15:15:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Others**:

## What happened?
`kubeadm init` doesn't support arg = `imagePullPolicy=never or local`. This impose a problem when using kubeadm with no internet access since, it defaults trying to pull images from gcr. 

kubeadm errors:
command : `kubeadm init --kubernetes-version v1.8.2 --pod-network-cidr=10.244.0.0/16`

```
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10255/healthz' failed with error: Get http://localhost:10255/healthz: dial tcp 127.0.0.1:10255: getsockopt: connection refused.
```
What i have done . Downloaded all google_containers related to kubernetes 1.8.2 and then scp to the host and used docker to load the containers . kubeadm default policy imagePullPolicy=always . Therefore it was failing 

```
docker images
REPOSITORY                                               TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kube-apiserver-amd64            v1.8.2              6278a1092d08        12 days ago         194 MB
gcr.io/google_containers/kube-controller-manager-amd64   v1.8.2              5eabb0eae58b        12 days ago         129.2 MB
gcr.io/google_containers/kube-scheduler-amd64            v1.8.2              b48970f8473e        12 days ago         54.9 MB
gcr.io/google_containers/kube-proxy-amd64                v1.8.2              88e2c85d3d02        12 days ago         93.13 MB
gcr.io/google_containers/k8s-dns-sidecar-amd64           1.14.4              38bac66034a6        4 months ago        41.82 MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64          1.14.4              a8e00546bcf3        4 months ago        49.39 MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64     1.14.4              f7f45b9cb733        4 months ago        41.42 MB
gcr.io/google_containers/etcd-amd64                      3.0.17              243830dae7dd        8 months ago        168.9 MB
gcr.io/google_containers/pause-amd64                     3.0     
```
To work around it . I have added imagePullPolicy=never to manifests and used kubelet to start the the pods .

```
docker ps 
CONTAINER ID        IMAGE                                                                                                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
3469f8d57f49        gcr.io/google_containers/kube-controller-manager-amd64@sha256:c2cd4acd4238b2f2526abf5ba546d4e6f4a46618ad5747a539e8a72c294a7482   "kube-controller-mana"   5 minutes ago       Up 5 minutes                            k8s_kube-controller-manager_kube-controller-manager-ip-10-205-78-6_kube-system_a2384e51c277f0dc61222c242361a42d_0
9233a987f5ac        gcr.io/google_containers/kube-apiserver-amd64@sha256:3e980f4b57292568ea8c87be462cf0583e40bbc2dbfff71d0d9e19beda3cb74b            "kube-apiserver --sec"   5 minutes ago       Up 5 minutes                            k8s_kube-apiserver_kube-apiserver-ip-10-205-78-6_kube-system_52115e8757d49c532b9f9253a995f4c6_0
50574a1badf2        gcr.io/google_containers/kube-scheduler-amd64@sha256:7c920b718509e8cf811c69178526d84ebfab2bdbb95949f6e82eb5233e7b5f0e            "kube-scheduler --kub"   5 minutes ago       Up 5 minutes                            k8s_kube-scheduler_kube-scheduler-ip-10-205-78-6_kube-system_c277372d3697e2f5d4038d02914e31d8_0
aa7eb7294220        gcr.io/google_containers/etcd-amd64@sha256:d83d3545e06fb035db8512e33bd44afb55dea007a3abd7b17742d3ac6d235940                      "etcd --listen-client"   5 minutes ago       Up 5 minutes                            k8s_etcd_etcd-ip-10-205-78-6_kube-system_07f2b34fc77ee86c936d12f9da37f985_0
5a7251468f60        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_kube-scheduler-ip-10-205-78-6_kube-system_c277372d3697e2f5d4038d02914e31d8_0
9ec41787b709        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_kube-controller-manager-ip-10-205-78-6_kube-system_a2384e51c277f0dc61222c242361a42d_0
7e8ceedab55c        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_kube-apiserver-ip-10-205-78-6_kube-system_52115e8757d49c532b9f9253a995f4c6_0
7d1ee4d69ca6        gcr.io/google_containers/pause-amd64:3.0                                                                                         "/pause"                 5 minutes ago       Up 5 minutes                            k8s_POD_etcd-ip-10-205-78-6_kube-system_07f2b34fc77ee86c936d12f9da37f985_0
```

master was up after that 
```
kubectl cluster-info
Kubernetes master is running at https://10.205.78.6:6443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

etcd responding
```
curl 127.0.0.1:2379/version
{"etcdserver":"3.0.17","etcdcluster":"3.0.0"}
```

API
```
curl https://10.205.78.6:6443/api/ -k
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.205.78.6:6443"
    }
  ]
```

## What you expected to happen?

expected kueadm to work if container-images are present locally.

## How to reproduce it (as minimally and precisely as possible)?
reproduce by following the steps above.

## Anything else we need to know?
not sure if it would it make sense to add hook kubeadm to talk to a private registry instead !

### PR DESCRIPTION
**Pull request by wangyysde**
Signed-off-by: wangyysde <net_use@bzhy.com>

#### What type of PR is this?
/kind feature
/kind design
/area kubeadm

#### What this PR does / why we need it:
kubeadm might have to support image pull policy for it's CP images on the API side.

#### Which issue(s) this PR fixes:

 Fixes kubernetes/kubeadm#524 
#### Does this PR introduce a user-facing change?

```release-note
kubeadm: add the "imagePullPolicy" field in the "nodeRegistration" section of InitConfiguration and JoinConfiguration in v1beta3. This allows the user to specify the image pull policy during "kubeadm init" and "kubeadm join". The value of this field must be one of "Always", "IfNotPresent" or "Never". The default behavior continues to be "IfNotPresent".
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/apis/kubeadm/types.go [hunk 1]
```diff
@@ -217,6 +217,10 @@ type NodeRegistrationOptions struct {
 
 	// IgnorePreflightErrors provides a slice of pre-flight errors to be ignored when the current node is registered.
 	IgnorePreflightErrors []string
+
+	// ImagePullPolicy specifies the policy of pull image. The value of this field is one of Always,IfNotPresent or Never
+	// if this field is unset, i.e. nil, kubeadm will pull the requested images if then not exist on the node.
+	ImagePullPolicy string `json:"imagePullPolicy,omitempty"`
```
Comment (SataQiu) [inline cmd/kubeadm/app/apis/kubeadm/types.go:223]: How about just using `v1.PullPolicy` instead of string here?

File: cmd/kubeadm/app/apis/kubeadm/types.go [hunk 2]
```diff
@@ -217,6 +217,10 @@ type NodeRegistrationOptions struct {
 
 	// IgnorePreflightErrors provides a slice of pre-flight errors to be ignored when the current node is registered.
 	IgnorePreflightErrors []string
+
+	// ImagePullPolicy specifies the policy of pull image. The value of this field is one of Always,IfNotPresent or Never
+	// if this field is unset, i.e. nil, kubeadm will pull the requested images if then not exist on the node.
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/types.go:222]:
```suggestion
	// ImagePullPolicy specifies the policy for image pulling during kubeadm "init" and "join" operations.
	// The value of this field must be one of "Always", "IfNotPresent" or "Never".
	// If this field is unset kubeadm will default it to "IfNotPresent", or pull the required images if not present on the host.
```

File: cmd/kubeadm/app/apis/kubeadm/types.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/apis/kubeadm/types.go:223]:
```suggestion
	ImagePullPolicy v1.PullPolicy
```

- internal types should not have JSON tags.
- use v1.PullPolicy instead of `string`

> How about just using v1.PullPolicy instead of string here?

i think we should avoid API binding between kubeadm types even to Core v1 or Meta v1, if possible, but given we are already embedding v1.Taint, v1.HostPathType and metav1.TypeMeta i think this is fine for v1beta3 and for the time being.

File: cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go [hunk 3]
```diff
@@ -118,6 +124,8 @@ func fuzzJoinConfiguration(obj *kubeadm.JoinConfiguration, c fuzz.Continue) {
 		Timeout:           &metav1.Duration{Duration: 1234},
 	}
 	obj.SkipPhases = nil
+	obj.NodeRegistration = kubeadm.NodeRegistrationOptions{}
+	obj.NodeRegistration.ImagePullPolicy = string(v1.PullIfNotPresent)
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go:128]: if `ImagePullPolicy` is of type `v1.PullPolicy` this cast will not be needed.

File: cmd/kubeadm/app/apis/kubeadm/v1beta2/conversion.go [hunk 4]
```diff
@@ -43,3 +43,8 @@ func Convert_v1beta2_ClusterConfiguration_To_kubeadm_ClusterConfiguration(in *Cl
 func Convert_kubeadm_JoinConfiguration_To_v1beta2_JoinConfiguration(in *kubeadm.JoinConfiguration, out *JoinConfiguration, s conversion.Scope) error {
 	return autoConvert_kubeadm_JoinConfiguration_To_v1beta2_JoinConfiguration(in, out, s)
 }
+
+// Convert_kubeadm_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOption is required since v1beta2 does not have _NodeRegistrationOption.ImagePullPolicy
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta2/conversion.go:47]:
```suggestion
// Convert_kubeadm_NodeRegistrationOptions_To_v1beta2_NodeRegistrationOption is required since v1beta2 does not have_NodeRegistrationOptions.ImagePullPolicy
```

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/doc.go [hunk 5]
```diff
@@ -31,6 +31,8 @@ limitations under the License.
 // This would result in the field values to be omitted when API structures are printed with klog.
 // - Add "InitConfiguration.SkipPhases", "JoinConfiguration.SkipPhases" to allow skipping
 // a list of phases during kubeadm init/join command execution.
+// - Add "InitConfiguration.NodeRegistration.ImagePullPolicy", "JoinConfiguration.NodeRegistration.ImagePullPolicy"
+// to specifies images pull policy. Pull policy must be one of Always,Never or IfNotPresent. IfNotPresent is default
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta3/doc.go:35]:
```suggestion
// - Add "InitConfiguration.NodeRegistration.ImagePullPolicy" and "JoinConfiguration.NodeRegistration.ImagePullPolicy"
// to allow specifying the images pull policy during kubeadm "init" and "join". The value must be one of "Always", "Never" or
// "IfNotPresent". "IfNotPresent" is the default, which has been the existing behavior prior to this addition.
```

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go [hunk 6]
```diff
@@ -220,6 +220,11 @@ type NodeRegistrationOptions struct {
 	// IgnorePreflightErrors provides a slice of pre-flight errors to be ignored when the current node is registered.
 	// +optional
 	IgnorePreflightErrors []string `json:"ignorePreflightErrors,omitempty"`
+
+	// ImagePullPolicy specifies the policy of pull image. The value of this field is one of Always,IfNotPresent or Never
+	// if this field is unset, i.e. nil, kubeadm will pull the requested images if then not exist on the node.
+	// +optional
+	ImagePullPolicy string `json:"imagePullPolicy,omitempty"`
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go:227]:
```suggestion
	// ImagePullPolicy specifies the policy for image pulling during kubeadm "init" and "join" operations.
	// The value of this field must be one of "Always", "IfNotPresent" or "Never".
	// If this field is unset kubeadm will default it to "IfNotPresent", or pull the required images if not present on the host.
	// +optional
	ImagePullPolicy v1.PullPolicy `json:"imagePullPolicy,omitempty"`
```

File: cmd/kubeadm/app/preflight/checks.go [hunk 7]
```diff
@@ -819,8 +820,9 @@ func getEtcdVersionResponse(client *http.Client, url string, target interface{})
 
 // ImagePullCheck will pull container images used by kubeadm
 type ImagePullCheck struct {
-	runtime   utilruntime.ContainerRuntime
-	imageList []string
+	runtime          utilruntime.ContainerRuntime
+	imageList        []string
+	NodeRegistration kubeadmapi.NodeRegistrationOptions
```
Comment (neolit123) [inline cmd/kubeadm/app/preflight/checks.go:825]:
```suggestion
	imagePullPolicy v1.PullPolicy
```

instead of adding the whole NodeRegistration object we are only interested in the pull policy.

File: cmd/kubeadm/app/preflight/checks.go [hunk 8]
```diff
@@ -831,8 +833,11 @@ func (ImagePullCheck) Name() string {
 // Check pulls images required by kubeadm. This is a mutating check
 func (ipc ImagePullCheck) Check() (warnings, errorList []error) {
 	for _, image := range ipc.imageList {
+		if ipc.NodeRegistration.ImagePullPolicy == string(v1.PullNever) {
```
Comment (neolit123) [inline cmd/kubeadm/app/preflight/checks.go:836]: - the string casts are not needed if ImagePullPolicy is of type v1.PullPolicy
- you should refactor this code to use a switch because it makes it easier to read:

```
switch ipc.imagePullPolicy {
case ...
}
```

**Comment by neolit123** [comment]
thanks for the PR @wangyysde 
this looks mostly fine, suggested some minor changes.


for the release note please use:
> kubeadm: add the "imagePullPolicy" field in the "nodeRegistration" section of InitConfiguration  and JoinConfiguration in v1beta3. This allows the user to specify the image pull policy during "kubeadm init" and "kubeadm join". The value of this field must be one of "Always", "IfNotPresent" or "Never". The default behavior continues to be "IfNotPresent".

File: cmd/kubeadm/app/apis/kubeadm/types.go (hunk 1 above)
Comment (wangyysde) [reply cmd/kubeadm/app/apis/kubeadm/types.go:223]: Ok, I will change it.

File: cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go [hunk 9]
```diff
@@ -57,13 +57,16 @@ func fuzzInitConfiguration(obj *kubeadm.InitConfiguration, c fuzz.Continue) {
...
+	obj.NodeRegistration.ImagePullPolicy = ""
 }
 
 func fuzzNodeRegistration(obj *kubeadm.NodeRegistrationOptions, c fuzz.Continue) {
 	c.FuzzNoCustom(obj)
 
 	// Pinning values for fields that get defaults if fuzz value is empty string or nil (thus making the round trip test fail)
 	obj.IgnorePreflightErrors = nil
+
+	// Pinning values for fields that get defaults if fuzz value is empty string or nil
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go:69]: can we remove these two lines?

**Comment by neolit123** [comment]
/approve

the change looks good to me @wangyysde 
added one minor comment.

File: cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go (hunk 9 above)
Comment (wangyysde) [reply cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go]: Thanks . I have remove these two lines.

**Review by pacoxu — APPROVED** [review]
/lgtm
