### PR TITLE
Fix race on unit test "kube-proxy ipvs: fix to prevent concurrent map read and map w…

### LINKED ISSUE #107811: [flake] Test_RaceTerminateRSList seems to be flaking
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

k8s.io/kubernetes/pkg/proxy/ipvs.Test_RaceTerminateRSList

### Since when has it been flaking?

~1 day since merging of https://github.com/kubernetes/kubernetes/pull/107748

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Anything else we need to know?

Test introduced in https://github.com/kubernetes/kubernetes/pull/107748

### Relevant SIG(s)

/sig network

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind failing-test
/kind flake
/kind regression

The test is wrong:
1. the inner loop iterates over `i` instead of `j` , creating an infinite loop
2. the delete is not exercised because it fails in the handler, we have to mock it

Fixes: #107811

```release-note
NONE
```

The test detects the race without the fix running with the race flag `go test -timeout 100s -run ^Test_RaceTerminateRSList$ k8s.io/kubernetes/pkg/proxy/ipvs -v -race` 
```
I0127 09:54:36.303854 3667010 graceful_termination.go:102] "Removed real server from graceful delete real server list" realServer="1.1.1.1:80/tcp/1.1.1.11:80"
I0127 09:54:36.303893 3667010 graceful_termination.go:102] "Removed real server from graceful delete real server list" realServer="1.1.1.1:80/tcp/1.1.1.15:80"
    testing.go:1152: race detected during execution of test
--- FAIL: Test_RaceTerminateRSList (0.00s)
=== CONT  
    testing.go:1152: race detected during execution of test
```

There is no flakes under the stress tool 
```
tress ./ipvs.test 
5s: 304 runs so far, 0 failures
10s: 626 runs so far, 0 failures
15s: 949 runs so far, 0 failures
20s: 1267 runs so far, 0 failures
25s: 1594 runs so far, 0 failures
30s: 1919 runs so far, 0 failures
35s: 2243 runs so far, 0 failures
```

### CODE REVIEW

**Comment by aojea** [comment]
/sig network

@cyclinder we have to rework the test, I've should checked it during the review but your change seemed so simple that :shrug: 

I've tried to get it working but is taking more time than I expected, I left you a snippet in the PR description if you still want to pursue on getting this in

/assign @MadhavJivrajani @uablrek @andrewsykim

**Comment by aojea** [comment]
/hold
I think I got it right now

**Comment by cyclinder** [comment]
hi @aojea, Is there something I can do?

**Comment by aojea** [comment]
/hold cancel
@cyclinder just review and lgtm , I found the problem and a solution :)

File: pkg/proxy/ipvs/graceful_termination.go [hunk 1]
```diff
@@ -80,6 +80,14 @@ func (q *graceTerminateRSList) remove(rs *listItem) bool {
 	return false
 }
 
+// return the size of the list
```
Comment (aojea) [inline pkg/proxy/ipvs/graceful_termination.go:83]: this is needed for the test, we have to wait until we have some elements we can delete, and the check of the len has to be locked

File: pkg/proxy/ipvs/graceful_termination_test.go [hunk 2]
```diff
@@ -403,18 +404,28 @@ func Test_GracefulDeleteRS(t *testing.T) {
...
 
 func Test_RaceTerminateRSList(t *testing.T) {
-	ipvs := &utilipvstest.FakeIPVS{}
+	ipvs := utilipvstest.NewFake()
 	gracefulTerminationManager := NewGracefulTerminationManager(ipvs)
 
+	// run in parallel to cause the race
 	go func() {
 		for i := 1; i <= 10; i++ {
-			for j := 1; i <= 100; j++ {
```
Comment (aojea) [inline pkg/proxy/ipvs/graceful_termination_test.go:411]: this was one sublte bug :smile: s/i/j/

File: pkg/proxy/ipvs/graceful_termination_test.go [hunk 3]
```diff
@@ -403,18 +404,28 @@ func Test_GracefulDeleteRS(t *testing.T) {
...
 		}
 	}()
 
-	if !gracefulTerminationManager.rsList.flushList(gracefulTerminationManager.deleteRsFunc) {
+	// wait until the list has some elements
+	for gracefulTerminationManager.rsList.len() < 20 {
+	}
+
+	// fake the handler to avoid the check against the IPVS virtual servers
+	fakeHandler := func(rsToDelete *listItem) (bool, error) {
```
Comment (aojea) [inline pkg/proxy/ipvs/graceful_termination_test.go:425]: the other handler was doing some checks against the ipvs objects and failing, so it never tried to delete anything form the list, this test doesn't need that checks

Comment (cyclinder) [reply pkg/proxy/ipvs/graceful_termination_test.go:425]: in the test, we only test race and don't care other thing

File: pkg/proxy/ipvs/graceful_termination.go (hunk 1 above)
Comment (cyclinder) [reply pkg/proxy/ipvs/graceful_termination.go:83]: we really need this function? let me see, Is there another way?

File: pkg/proxy/ipvs/graceful_termination_test.go (hunk 2 above)
Comment (uablrek) [reply pkg/proxy/ipvs/graceful_termination_test.go:411]: Good catch

File: pkg/proxy/ipvs/graceful_termination_test.go (hunk 3 above)
Comment (aojea) [reply pkg/proxy/ipvs/graceful_termination_test.go:425]: yeah, but is racy and sometimes it gets to delete the list and other no
