### PR TITLE
Set better default commands for loading images

### LINKED ISSUE #17929: containerd-e2e-gci broken recently
**What happened**:
On May 29, https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-gci started to fail when creating cluster. 

First failed log:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270494318632636417/build-log.txt

Last Succeed log:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270478968641818625/build-log.txt

**What you expected to happen**:
Succeed

**How to reproduce it (as minimally and precisely as possible)**:

After the last success run, it continuously failed.

**Please provide links to example occurrences, if any**:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-gci-gce/1270494318632636417/build-log.txt

**Anything else we need to know?**:

Take a look, and looks the cluster master can't be reached. Wonder any test infra is changed recently.

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Do not default to `docker`, check the runtime and use correct command for each runtime.

**Which issue(s) this PR fixes**:
 
Fixes https://github.com/kubernetes/test-infra/issues/17929

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

File: cluster/gce/gci/configure.sh [hunk 1]
```diff
@@ -376,7 +376,16 @@ function try-load-docker-image {
...
+    load_image_command=${LOAD_IMAGE_COMMAND:-docker load -i}
+  elif [[ "${CONTAINER_RUNTIME_NAME:-}" == "containerd" ]]; then
+    load_image_command=${LOAD_IMAGE_COMMAND:-ctr -n=k8s.io images import}
+  else
+    load_image_command="${LOAD_IMAGE_COMMAND:-}"
+  fi
+
+  until timeout 30 ${load_image_command} "${img}"; do
     if [[ "${attempt_num}" == "${max_attempts}" ]]; then
       echo "Fail to load docker image file ${img} after ${max_attempts} retries. Exit!!"
```
Comment (bsdnet) [inline cluster/gce/gci/configure.sh:390]: Nit:
Can we add  "using ${load_image_command}" after '${max_attempts} retries'?

That is what I struggled when looking at the logs as a new member.

**Review by bsdnet — COMMENTED** [review]
/lgtm

Thanks for fixing the issue.

File: cluster/gce/gci/configure.sh (hunk 1 above)
Comment (dims) [reply cluster/gce/gci/configure.sh:390]: @bsdnet Excellent idea! How about we fix it up in a follow up PR? (would you like to file it please?)

**Comment by dims** [comment]
test

**Comment by dims** [comment]
test<br/>temprary

File: cluster/gce/gci/configure.sh (hunk 1 above)
Comment (bsdnet) [reply cluster/gce/gci/configure.sh:390]: Sure, I can come out a fix after you commit current fix. 
I want to enable future contributors to avoid my confusion.

**Comment by bsdnet** [comment]
I saw the tests are still failing. Are we waiting for an image update with latest script?

**Comment by dims** [comment]
@bsdnet why don't you file the follow up PR printing the ${load_image_command} so we can be sure what we are executing? we'll merge that and then re-evaluate.

**Comment by bsdnet** [comment]
> @bsdnet why don't you file the follow up PR printing the ${load_image_command} so we can be sure what we are executing? we'll merge that and then re-evaluate.

I did not see your changes after I did a 'git pull'. That is weird. 

377   local -r max_attempts=5
378   local -i attempt_num=1
379   until timeout 30 ${LOAD_IMAGE_COMMAND:-docker load -i} "${img}"; do
380     if [[ "${attempt_num}" == "${max_attempts}" ]]; then
381       echo "Fail to load docker image file ${img} after ${max_attempts} retries. Exit!!"
