### PR TITLE
[FG:InPlacePodVerticalScaling] Add back `AllocatedResources` and use it for scheduling

### LINKED ISSUE #129532: [FG:InPlacePodVerticalScaling] Inconsistency between scheduler & kubelet admission logic
The scheduler uses `max(spec...resources, status...resources)` to determine the resources requested by a pod, but when the Kubelet is making internal fit decisions it just uses the allocated resources.

In most cases, disagreement between these two approaches would be due to a pending upsize, where the spec...resources are higher than the allocated resources (desired > allocated == actual). This case is working as intended: the scheduler should not schedule over a pending resize, but the Kubelet needs to be able to admit resizes when there are 2 competing resizes.

This is only problematic if there is a case where the scheduler thinks there are _more_ available resources than the Kubelet does, which could lead to a pod being rejected with `OutOf{CPU,Memory}` . In other words, if `max(spec...resources, status...resources) < allocated resources`. This can only happen if both of the following are true:
1. There is a pending (or deferred) downsize (spec...resources < allocated)
2. There is an in-progress upsize (actual resources < allocated)

**Repro steps:**
This repro hits the above conditions for CPU requests, and manipulates memory requests & limits to make the condition persistent.

1. Create a pod with memory & cpu requests & limits
2. In a single resize request, shrink the memory limit below usage, and increase the CPU request
    - Setting the memory limit below the usage will cause the resize to be stuck in progress, without the memory or CPU changes having been actuated.
    - Allocated CPU requests are now higher than the actual CPU requests (shares)
3. In a single resize request, shrink the CPU request back to the original amount, and increase memory requests & limits to more than the available memory (but below the allocatable capacity).
    - The resize will be deferred since there is insufficient available memory for the request
    - The desired CPU is now below the allocated amount
    - For CPU requests, desired == actual < allocated
4. Create a burstable pod with a CPU request, such that the CPU request is `allocatable cpu - sum(desired cpu)`
    - The scheduler will see this pod as fitting, but the kubelet will reject it with OutOfCPU

Moving the memory usage > limit check to allocation time (option 3 in [Handling Memory Limit Decreases for In-Place Pod Resize](https://docs.google.com/document/d/1cEFLXKwNOSNLAkzyhoJUgkBW0OiX-9bXB_aJV7OAypw/edit?tab=t.0#heading=h.y6xkh6jc1iat)) will mitigate this by making a persistent in-progress resize (step 2 above) less likely, but it doesn't entirely eliminate the issue.

/sig node
/priority important-soon

### PR DESCRIPTION
**Pull request by tallclair**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Deprecate the `InPlacePodVerticalScalingAllocatedStatus` feature gate, and always include `AllocatedResources` when the `InPlacePodVerticalScaling` feature gate is enabled. The `AllocatedResources` are now included in the calculation for totalling the pod requests.

Fixes an inconsistency with scheduler & Kubelet resource accounting. See https://github.com/kubernetes/kubernetes/issues/129532.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/129532

#### Does this PR introduce a user-facing change?
```release-note
The feature gate InPlacePodVerticalScalingAllocatedStatus is deprecated and no longer used. The AllocatedResources field in ContainerStatus is now guarded by the InPlacePodVerticalScaling feature gate.
```

/sig node
/priority important-soon
/milestone v1.33

### CODE REVIEW

File: pkg/api/pod/util_test.go [hunk 1]
```diff
@@ -2740,64 +2740,55 @@ func TestDropInPlacePodVerticalScaling(t *testing.T) {
 		t.Run(fmt.Sprintf("InPlacePodVerticalScaling=%t", ippvsEnabled), func(t *testing.T) {
 			featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.InPlacePodVerticalScaling, ippvsEnabled)
 
-			for _, allocatedStatusEnabled := range []bool{true, false} {
```
Comment (tallclair) [inline pkg/api/pod/util_test.go:2743]: Note to reviewers: this just removes this outer for each allocatedStatusEnabled condition. This is much easier to review if you enable the `Hide whitespace` option.

**Comment by tico88612** [comment]
Hello @tallclair @thockin @ndixita 
Appreciate all of your efforts with this PR!
A gentle reminder that the code freeze has started [02:00 UTC Friday 21st March 2025](https://everytimezone.com/s/2c5e9275) . Please make sure any PRs have both lgtm and approved labels ASAP, and file an [Exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md) if you haven't done it yet.
Thanks!

**Comment by esotsal** [comment]
I suspect `pull-kubernetes-unit` to be a flaky failure.  Retesting to make sure it passes to give lgtm.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by tallclair** [comment]
Rebased (versioned_features was merged into kube_features)

**Comment by ndixita** [comment]
@tallclair Not necessarily a blocker for this PR, but can we please update the KEP as well?
