### PR TITLE
Re-introduce 126599: fix: preserve options after remount for bind mounting

### LINKED ISSUE #124863: NFS PV mountOptions does not work when Volume SubPath option is set
### What happened?

Setting the Volume subpath option at deployment with an NFS PV with a mount option (e.g. nosuid) does not mount accordingly. If no SubPath is set and the NFS PV is set to the /nfs_share/directory the mount works with the nosuid.

### What did you expect to happen?

should be mounted with correct mountoptions

### How can we reproduce it (as minimally and precisely as possible)?

- create KIND cluster and install nfs client packages
- create a PV and PVC with below options: 

```
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc01
    namespace: default
    resourceVersion: '53505'
    uid: 0b3736ac-bbb6-4539-95c1-854ddcb36114
  mountOptions:
    - nfsvers=4.2
    - sec=sys
    - nosuid
  nfs:
    path: /nfs
    server: 172.31.40.82
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem  
```
-  Update the deployment with the volume and mount information: 

```
          volumeMounts:
            - mountPath: /data
              name: vol-oirnd
              subPath: share01

      volumes:
        - name: vol-oirnd
          persistentVolumeClaim:
            claimName: pvc01
          __newPvc:
            type: persistentvolumeclaim
            metadata:
              namespace: default
            spec:
              storageClassName: ''
              volumeName: ''
              resources:
                requests: {} 
```

### Anything else we need to know?

```
**Not using SubPath**

root@kind-2-control-plane:/# mount | grep nfs
192.168.100.217:/nfs on /var/lib/kubelet/pods/c29b33d8-3709-4082-892c-def5efbba86f/volumes/kubernetes.io~nfs/pv type nfs4 (rw,nosuid,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.18.0.2,local_lock=none,addr=192.168.100.217)

**When not using SubPath**


192.168.100.217:/nfs/hello/world on /var/lib/kubelet/pods/c29b33d8-3709-4082-892c-def5efbba86f/volume-subpaths/pv/httpd/0 type nfs4 (rw,relatime,vers=4.2,rsize=524288,wsize=524288,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.18.0.2,local_lock=none,addr=192.168.100.217)
root@kind-2-control-plane:/# 

root@kind-2-control-plane:/# kubectl get nodes
NAME                   STATUS   ROLES           AGE   VERSION
kind-2-control-plane   Ready    control-plane   49m   v1.29.2
root@kind-2-control-plane:/# 
```

### Kubernetes version

<details>

```console
$ kubectl version
 v1.29.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Ubuntu

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yaroslavborbat**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Re-introduce  pr [126599](https://github.com/kubernetes/kubernetes/pull/126599)

#### Which issue(s) this PR fixes:

Fixes #124863

#### Special notes for your reviewer:
The previous pr was revert because it caused the ci tests to fail. see #127867

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/storage/drivers/in_tree.go [hunk 1]
```diff
@@ -1223,6 +1224,14 @@ func (l *localDriver) PrepareTest(ctx context.Context, f *framework.Framework) *
...
 
 	l.hostExec = utils.NewHostExec(f)
+	// It is recommended to mount /tmp with options noexec, nodev, nosuid.
+	// tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,inode64)
+	// This prevents scripts and binaries from being executed from the /tmp directory.
+	// This can cause errors like "Permission denied" when executing files from `/tmp`.
+	// To pass the test that verifies the execution of files on a volume, we remount `/tmp` with the exec option.
+	remountCmd := `mount | awk '{if ($3 == "/tmp") print $0}' | grep -q "noexec" && mount -o remount,exec /tmp || true`
+	err = l.hostExec.IssueCommand(ctx, remountCmd, l.node)
+	framework.ExpectNoError(err)
```
Comment (jsafrane) [inline test/e2e/storage/drivers/in_tree.go:1234]: Sorry I did not re-check it sooner. It's not great to modify the host, it may be a real cluster.

If it's hard not to do so, then let's skip exec tests for **some** local volumes. There are all local volume "types" we have in CI:

https://github.com/kubernetes/kubernetes/blob/af41aa1d9f7f347c85aba629963941a8ce6a95fd/test/e2e/storage/utils/local.go#L40-L57

Some of them can't support exec because they're on /tmp (all the bind-mounts, directories etc), but some always can, because they get a fresh mount (like LocalVolumeBlockFS, LocalVolumeTmpfs, LocalVolumeGCELocalSSD, please check the others). I think it's enough if we test exec only for those.

The tests framework has a list of all "exceptional" local volume types, currently with only one entry for LocalVolumeBlock tha can support block volume:
https://github.com/kubernetes/kubernetes/blob/af41aa1d9f7f347c85aba629963941a8ce6a95fd/test/e2e/storage/drivers/in_tree.go#L1149-L1158

The defaults are used for all others:
https://github.com/kubernetes/kubernetes/blob/af41aa1d9f7f347c85aba629963941a8ce6a95fd/test/e2e/storage/drivers/in_tree.go#L1140-L1147

So, you can make the default with `CapExec: false` and then add exception for LocalVolumeBlockFS, LocalVolumeTmpfs, LocalVolumeGCELocalSSD with `CapExec: true`, with some smart comment why false there and true here.
