### PR TITLE
disable caching for authoritative zone to comply with rfc-1035 section 6.1.2

### LINKED ISSUE #92559: Headless Service not publishing not ready addresses for statefulset
**What happened**:

Deploying a StatefulSet with a headless service and properly configured `spec.serviceName` doesn't publish the underlying pod's on the internal Kube-DNS for at least 30 seconds after pod creation, even if the headless service has explicit `publishNotReadyAddresses: true` and even if a pod has a `readinessProbe` of 1 second which shouldn't matter if the publishNotReadyAddresses is set to true according to [documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields) .

This causes that if the stateful application, which relies on a pod being able to communicate to it's peer for bootstrapping, doesn't start for at least 30 seconds due to this delay.

**What you expected to happen**:

I'm expecting the fully qualified names of the pods under the statefulset to become avaiable in the DNS so the pods in the statefulset can find it's own peers via their dns name (i.e. `pod-0.statefulset-svc` can connect to `pod-1.statefulset-svc`)

**How to reproduce it (as minimally and precisely as possible)**:

I've designed a simple application that since starting it tries to ping it's own peers under the same application, you can clearly see that for the first 30 seconds of the pod existance, it cannot reach it's peers, not even itself, this is because the pod's name is not being announced in the internal KubeDNS.

Using the following statefulset you can observe the behavior:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    controller: message-dist
  name: message-dist
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: minio-port
      port: 8090
      protocol: TCP
      targetPort: 8090
  publishNotReadyAddresses: true
  selector:
    app: minio
    controller: message-dist
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: message-dist
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 4
  selector:
    matchLabels:
      app: minio
      controller: message-dist
  serviceName: message-dist
  template:
    metadata:
      labels:
        app: minio
        controller: message-dist
    spec:
      containers:
        - name: message
          command:
            - /message
            - http://message-dist-{0...3}.message-dist:8090/
          env:
            - name: MESSAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: dvaldivia/message:dist
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8090
              name: minio-port
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data1
              name: data1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```

Or simply apply this file:

```
kubectl apply -f https://raw.githubusercontent.com/dvaldivia/message/master/message-dist.yaml
```

**Anything else we need to know?**:

This problem could be avoided if the Kube-DNS made the service subdomains for the pods available sooner than 30 seconds, I cannot find anywhere in the documentation where it specifies this 30 seconds delay.

**Environment**:
- Kubernetes version (use `kubectl version`):  `client 1.18.4 ` `server 1.18.2`
- Cloud provider or hardware configuration: kind, gke

### LINKED ISSUE #128325: DNS seems flaky?
### What happened?

I created a headless service without a selector and defined an endpointslice using podIPs. Inside the pods I queried DNS. It seemed to take ~20 seconds for the first successful response. Following this a subsequent response apparently failed unexpectedly (line 9 of the massaged core dns log file snippet).

```
     1	2024-10-25T00:53:46.182233945Z [INFO] 10.244.0.82:44628 - 30082 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.000117891s
     2	2024-10-25T00:53:46.253100368Z [INFO] 10.244.0.93:52617 - 56694 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.000105911s
     3	2024-10-25T00:53:46.480963630Z [INFO] 10.244.0.92:52986 - 22363 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.000093061s
     4	2024-10-25T00:53:47.204138260Z [INFO] 10.244.0.82:51733 - 7928 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.00015467s
     5	2024-10-25T00:53:47.272560170Z [INFO] 10.244.0.93:53722 - 42551 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 142 0.00012205s
     6	2024-10-25T00:53:47.273148393Z [INFO] 10.244.0.93:45857 - 16439 "AAAA IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 165 0.000229791s
     7	2024-10-25T00:53:47.500587592Z [INFO] 10.244.0.92:52084 - 56243 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 142 0.000108021s
     8	2024-10-25T00:53:47.500996354Z [INFO] 10.244.0.92:34111 - 60259 "AAAA IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 165 0.000133821s
     9	2024-10-25T00:53:48.224163794Z [INFO] 10.244.0.82:54103 - 17526 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.000114871s
    10	2024-10-25T00:53:49.185290159Z [INFO] 10.244.0.93:43947 - 32139 "AAAA IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 165 0.00013564s
    11	2024-10-25T00:53:49.185316049Z [INFO] 10.244.0.93:43947 - 45961 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NXDOMAIN qr,aa,rd 165 0.000196601s
    12	2024-10-25T00:53:49.232650565Z [INFO] 10.244.0.92:60294 - 21062 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 142 0.00012781s
    13	2024-10-25T00:53:49.232726915Z [INFO] 10.244.0.92:60294 - 4419 "AAAA IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 165 0.000216891s
    14	2024-10-25T00:53:49.257686390Z [INFO] 10.244.0.82:36243 - 39800 "A IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 142 0.00010856s
    15	2024-10-25T00:53:49.258035902Z [INFO] 10.244.0.82:33934 - 27151 "AAAA IN node0.pod.namespace.svc.cluster.local. udp 72 false 512" NOERROR qr,aa,rd 165 0.000153311s
```

### What did you expect to happen?

I expected that once the DNS started providing successful responses all responses would be successful, but I observed one that wasn't.

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure how easily I can reproduce this myself.

### Anything else we need to know?

Kubernetes resources were created using fabric8 client version 6.13.1.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.29.2
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
NAME="Fedora Linux"
VERSION="40 (Toolbx Container Image)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Toolbx Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Toolbx Container Image"
VARIANT_ID=toolbx
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by matteriben**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
It changes the kubernetes plugin configuration in the coredns Corefile to disable caching for the domain which the plugin is authoritative for.

Coredns delegates responsibility to plugins which it chains together. Currently a `cache` plugin is earlier in the chain than the `kubernetes` plugin. This combined with the current Corefile has undesirable consequences such as being slow to reflect changes in the environment and the possibility of providing conflicting responses around the time of a cache update.

Without this change coredns will be misconfigured according to RFC 1035 (6.1.2 name server implementation, database):
> With the proper search procedures, authoritative data in zones
     will always "hide", and hence take precedence over, cached
     data.

#### Which issue(s) this PR fixes:

Fixes #128325
Fixes #92559

See also:
https://github.com/kubernetes/kubernetes/issues/92559#issuecomment-1203320093
https://github.com/coredns/coredns/issues/6937#issuecomment-2439731989
https://github.com/coredns/coredns/pull/6939#issuecomment-2439756769
https://github.com/coredns/coredns/pull/5540

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: added "disable success" and "disable denial" as parameters of the "cache" plugin in the Corefile managed by kubeadm. This is to prevent conflicting responses during CoreDNS cache updates.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
The issue was closed by @neolit123, please see https://github.com/kubernetes/kubernetes/issues/128325#issuecomment-2438002098. 

> a better place to ask would be on the support channels. please see:
> https://git.k8s.io/kubernetes/SUPPORT.md

I can't get the answer from the PR's description. @neolit123, could you please help me to review the PR? Thanks.

IMO, it will reduce the performance of the coredns if we disable it.

File: cmd/kubeadm/app/phases/addons/dns/manifests.go [hunk 1]
```diff
@@ -177,7 +177,10 @@ data:
         forward . /etc/resolv.conf {
            max_concurrent 1000
         }
-        cache 30
+        cache 30 {
+           disable success {{ .DNSDomain }}
+           disable denial {{ .DNSDomain }}
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/addons/dns/manifests.go:182]: no other users have ever reported the need for these params. so based on that it seems setup specific to me.

@chrisohaver could you please review this change to determine if this is something to add by default in kubeadm? related to:
- https://github.com/kubernetes/kubernetes/issues/128325

**Comment by matteriben** [comment]
Without this configuration change coredns will fail to comply with RFC 1035 which states:
> With the proper search procedures, authoritative data in zones
     will always "hide", and hence take precedence over, cached
     data.

**Comment by chrisohaver** [comment]
I think this is a good addition.  I have also recommended this configuration in the past to users concerned with cluster domain record lag induced by caching. This is better than setting the TTL to zero for all cluster domain responses since some clients may mishandle ttl 0 responses. 

It doesn’t avert caching of reverse zone answers produced by the Kubernetes plugin, but I think that’s ok for now.

A compelling alternate solution suggested by @matteriben is to change the order of plugin execution in the coredns build such that kubernetes comes before cache. This would also prevent the reverse zone responses from entering cache, but it’s a bigger change and may introduce backward incompatibility or other complications resulting from changing the Kubernetes plugin relative to other plugins (other than cache). … needs further thought and comparison with other potential solutions such as adding a mechanism for plugins to internally tag responses as authoritative so that cache can skip them.

For now, I think this configmap change solution is low risk and is good for inclusion as the default.

**Review by neolit123 — COMMENTED** [review]
thanks @chrisohaver !

/lgtm
/approve
/ok-to-test

this might fail unit tests @matteriben

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: added "disable success" and "disable denial" as parameters of the "cache" plugin in the Corefile managed by kubeadm. This is to prevent conflicting responses during CoreDNS cache updates.
```

**Comment by neolit123** [comment]
@matteriben kubeadm unit tests needs some minor updates after this change. see
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128359/pull-kubernetes-unit/1851256639726817280

**Comment by neolit123** [comment]
> @matteriben kubeadm unit tests needs some minor updates after this change. see https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128359/pull-kubernetes-unit/1851256639726817280

/lgtm cancel

**Review by neolit123 — COMMENTED** [review]
/lgtm
