### PR TITLE
Improve tests and fix bugs in container validation

### LINKED ISSUE #111028: Ephemeral Container validation prints incorrect path to ephemeral container
### What would you like to be added?

`validateEphemeralContainers` will add a superfuous index to validation errors for ephemeral containers due to the way container validation code is reused.

### Why is this needed?

Resolving this cosmetic issue is required for [Ephemeral Containers GA Graduation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/277-ephemeral-containers#beta---ga-graduation)

### PR DESCRIPTION
**Pull request by verb**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This fixes a bug in container validation caused by reusing the previously existing container validation methods that results in validation adding an extra index in the path of errors (e.g. `pod.spec.ephemeralcontainers[0][0].image` instead of `pod.spec.ephemeralcontainers[0].image`).

#### Which issue(s) this PR fixes:

Fixes #111028

#### Special notes for your reviewer:

I arranged the commits to try to make this PR easier to review.

1. The first commit changes the format (but not the content) of unit tests in order to make it easier to see what's changing in later commits.
2. The second commit expands unit test coverage based on gaps in `KUBE_COVER` and fixes tests that had multiple validation errors that would potentially mask the error under test.
3. The third commit refactors validation and fixes the bugs described in the unit tests.

I checked that unit tests are successful at each commit, and each commit has a description that describes the changes in more detail. Unfortunately I couldn't find a way to make github show better diffs for the line moves in commit 3 that introduced whitespace changes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by verb** [comment]
Hi @thockin, you're the chosen one! By k8s-ci-robot, at least.

This is a PR to improve test coverage and fix a few cosmetic issues in container validation. I think it's a pretty straightforward refactor, but it's XXL because I added test cases and Github isn't as good at diffing whitespace and moves as I hoped. I've tried to make it easier to review by putting the mechanical refactor in a separate commit from the ones that introduce changes. See the PR and commit descriptions for more details.

Since you're both a suggested reviewer and approver, I hope you don't mind if I assign this to you directly. Please let me know if you'd prefer me to find another first-level reviewer. Thanks!

/assign @thockin

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -3024,10 +3022,70 @@ func validateInitContainers(containers []core.Container, otherContainers []core.
 			allErrs = append(allErrs, field.Invalid(idxPath.Child("startupProbe"), ctr.StartupProbe, "must not be set for init containers"))
 		}
 	}
+
+	return allErrs
+}
+
+func validateContainer(ctr *core.Container, volumes map[string]core.VolumeSource, path *field.Path, opts PodValidationOptions) field.ErrorList {
```
Comment (verb) [inline pkg/apis/core/validation/validation.go:3029]: FYI, there's nothing new in `validateContainer()`, it's just the contents of the container loop in `validateContainers()`.

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -3007,10 +3000,15 @@ func validateInitContainers(containers []core.Container, otherContainers []core.
 		idxPath := fldPath.Index(i)
 		if allNames.Has(ctr.Name) {
 			allErrs = append(allErrs, field.Duplicate(idxPath.Child("name"), ctr.Name))
-		}
-		if len(ctr.Name) > 0 {
+		} else if len(ctr.Name) > 0 {
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3003]: What if Name == "" ?  Is that allowed?  This implies it is...

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -3024,10 +3022,70 @@ func validateInitContainers(containers []core.Container, otherContainers []core.
...
+	if ctr.StartupProbe != nil && ctr.StartupProbe.SuccessThreshold != 1 {
+		allErrs = append(allErrs, field.Invalid(path.Child("startupProbe", "successThreshold"), ctr.StartupProbe.SuccessThreshold, "must be 1"))
+	}
+
+	switch ctr.TerminationMessagePolicy {
+	case core.TerminationMessageReadFile, core.TerminationMessageFallbackToLogsOnError:
+	case "":
+		allErrs = append(allErrs, field.Required(path.Child("terminationMessagePolicy"), "must be 'File' or 'FallbackToLogsOnError'"))
+	default:
+		allErrs = append(allErrs, field.Invalid(path.Child("terminationMessagePolicy"), ctr.TerminationMessagePolicy, "must be 'File' or 'FallbackToLogsOnError'"))
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3070]: should this be `field.NotSupported()` ?

File: pkg/apis/core/validation/validation.go [hunk 4]
```diff
@@ -3024,10 +3022,70 @@ func validateInitContainers(containers []core.Container, otherContainers []core.
...
+	// Readiness-specific validation
+	if ctr.ReadinessProbe != nil && ctr.ReadinessProbe.TerminationGracePeriodSeconds != nil {
+		allErrs = append(allErrs, field.Invalid(path.Child("readinessProbe", "terminationGracePeriodSeconds"), ctr.ReadinessProbe.TerminationGracePeriodSeconds, "must not be set for readinessProbes"))
+	}
+	allErrs = append(allErrs, validateProbe(ctr.StartupProbe, path.Child("startupProbe"))...)
+	// Liveness-specific validation
+	if ctr.LivenessProbe != nil && ctr.LivenessProbe.SuccessThreshold != 1 {
+		allErrs = append(allErrs, field.Invalid(path.Child("livenessProbe", "successThreshold"), ctr.LivenessProbe.SuccessThreshold, "must be 1"))
+	}
+	allErrs = append(allErrs, validateProbe(ctr.StartupProbe, path.Child("startupProbe"))...)
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3059]: Why are we validating startupProbe twice?

Comment (thockin) [reply pkg/apis/core/validation/validation.go:3059]: In fact this whole section is suspect (3049-3063) - the comments on which probe is being validated do not match the code?

File: pkg/apis/core/validation/validation.go [hunk 5]
```diff
@@ -3037,73 +3095,18 @@ func validateContainers(containers []core.Container, isInitContainers bool, volu
...
-		volDevices := GetVolumeDeviceMap(ctr.VolumeDevices)
 
-		if len(ctr.Name) == 0 {
-			allErrs = append(allErrs, field.Required(namePath, ""))
-		} else {
-			allErrs = append(allErrs, ValidateDNS1123Label(ctr.Name, namePath)...)
-		}
 		if allNames.Has(ctr.Name) {
-			allErrs = append(allErrs, field.Duplicate(namePath, ctr.Name))
+			allErrs = append(allErrs, field.Duplicate(idxPath.Child("name"), ctr.Name))
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3100]: Do we care if there is a dup name across init/ephemeral/real containers?

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3029]: Since you are in here - some comments detailing how the container validation flow runs from pod->... thru these helper functions would be lovely? Even just a one-liner at each function explaining it..

File: pkg/apis/core/validation/validation.go [hunk 6]
```diff
@@ -2930,18 +2930,14 @@ func validateEphemeralContainers(ephemeralContainers []core.EphemeralContainer,
 		}
 
 		if ec.Name == "" {
-			allErrs = append(allErrs, field.Required(idxPath, "ephemeralContainer requires a name"))
+			allErrs = append(allErrs, field.Required(idxPath.Child("name"), "ephemeralContainer requires a name"))
```
[the remark this answers is not in the document]
Comment (verb) [reply pkg/apis/core/validation/validation.go]: This one was probably my fault, anyway. I fixed here and checked `field.Required()` for the rest of the container validation but stopped short of trying to fix every occurrence in this file.

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (verb) [reply pkg/apis/core/validation/validation.go]: Done :+1:

File: pkg/apis/core/validation/validation.go (hunk 5 above)
Comment (verb) [reply pkg/apis/core/validation/validation.go]: We do care, but we check for it later to avoid duplicate error messages. I've added comments explaining how the checks work.

File: pkg/apis/core/validation/validation_test.go [hunk 7]
```diff
@@ -7169,255 +7169,342 @@ func TestValidateContainers(t *testing.T) {
...
 	})
-	errorCases := map[string][]core.Container{
-		"zero-length name":     {{Name: "", Image: "image", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"}},
-		"zero-length-image":    {{Name: "abc", Image: "", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"}},
-		"name > 63 characters": {{Name: strings.Repeat("a", 64), Image: "image", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"}},
-		"name not a DNS label": {{Name: "a.b.c", Image: "image", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"}},
-		"name not unique": {
-			{Name: "abc", Image: "image", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"},
-			{Name: "abc", Image: "image", ImagePullPolicy: "IfNotPresent", TerminationMessagePolicy: "File"},
+	errorCases := []struct {
```
[the remark this answers is not in the document]
Comment (verb) [reply pkg/apis/core/validation/validation_test.go:7299]: I copied this here to give it a try. I think I agree that it's better than searching for test names, and I can see how it's way, way better for the nested tables you linked :+1:

**Comment by verb** [comment]
@thockin thanks for the review! I pushed new commit with a bunch of improvements you did and didn't ask for. It should be ready for you to take another look now.

File: pkg/apis/core/validation/validation.go [hunk 8]
```diff
@@ -2907,51 +2907,49 @@ func validatePullPolicy(policy core.PullPolicy, fldPath *field.Path) field.Error
 	return allErrors
 }
 
+// validateEphemeralContainers is called by pod spec and template validation to validate the list of ephemeral containers.
+// Note that this is called for pod template even though ephemeral containers aren't allowed in pod templates.
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:2911]: Should we fix the fact that this is run for templates?  It might require more plumbing, in a different PR?

File: pkg/apis/core/validation/validation.go (hunk 4 above)
Comment (thockin) [reply pkg/apis/core/validation/validation.go]: I agree that is ugly.  Why can't we pass down enough information to skip the "inner" validations when then probe itself is not allowed?

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
