### PR TITLE
kubeadm: fix join bug where kubeletconfig was not patched in memory

### LINKED ISSUE #3091: "kubeletconfiguration" patch target patches not respected on kubeadm join
slack
https://kubernetes.slack.com/archives/C2P1JHS2E/p1721299761889029

users are reporting that 1.30.2 does not respect a custom kubeletconfiguration.yaml patch that looks like this:
```
healthzBindAddress: foobar
healthzPort: 4321
```

reporduction steps:
- create a kubeadm init single node
- call kubeadm join ... --patches some-dir that has the above patch

what happens:
- kubeadm join still uses the values for healthz in the kubelet-config config map and ignores the patches
- /var/lib/kubelet/config.yaml is patched correctly.

i will investigate the problem.
cc @SataQiu i think we tried to fix a recent bug about that.

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

During kubeadm join in 1.30 kubeadm started respecting the kubeletconfiguration healthz address/port. Previously it hardcoded the health check to localhost:defaultport.

A corner case was not handled where the user applies --patches on join to modify the local kubeletconfiguration. This results in kubeletconfiguration patch target patches not being applied to the KubeletConfiguration in memory and the health check running on the address:port which are present in the kubelet-config configmap.

Fix that by explicitly calling a new function to patch the KubeletConfiguration in memory. This is scoped to only handle the healthz checks *after* the kubelet config.yaml was already patched and written to disk.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3091

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fixed a bug on 'kubeadm join' where using patches with a kubeletconfiguration target was not respected when performing the local kubelet healthz check.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @SataQiu 
PTAL when possible
i tried to keep this minimal so that it can be backported to 1.30.

/triage accepted
/priorty backlog

**Review by neolit123 — COMMENTED** [review]
/hold for review

File: cmd/kubeadm/app/util/apiclient/wait.go [hunk 1]
```diff
@@ -250,7 +250,8 @@ func (w *KubeWaiter) WaitForKubelet(healthzAddress string, healthzPort int32) er
 		healthzEndpoint = fmt.Sprintf("http://%s:%d/healthz", healthzAddress, healthzPort)
 	)
 
-	fmt.Printf("[kubelet-check] Waiting for a healthy kubelet. This can take up to %v\n", w.timeout)
+	fmt.Printf("[kubelet-check] Waiting for a healthy kubelet at %s. This can take up to %v\n",
+		healthzEndpoint, w.timeout)
```
Comment (neolit123) [inline cmd/kubeadm/app/util/apiclient/wait.go:254]: this is useful to have.

**Review by SataQiu — COMMENTED** [review]
/lgtm

File: cmd/kubeadm/app/util/apiclient/wait.go (hunk 1 above)
Comment (dipesh-rawat) [reply cmd/kubeadm/app/util/apiclient/wait.go:254]: Do we also want consider adding a check in here to ensure this healthz endpoint check is only done when the `HealthzPort` is set to a value other than ‘0’? If the `HealthzPort` is set to ‘0’ then healthz endpoint would be [disabled](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L235) and this would cause this check to timeout. Apologies for any confusion on my part.

Comment (neolit123) [reply cmd/kubeadm/app/util/apiclient/wait.go:254]: makes sense to skip if the port is 0. i will update.

**Comment by neolit123** [comment]
updated https://github.com/kubernetes/kubernetes/compare/f7d4eb68a12bb99a7ba462b39b591fc0135abaaa..b90b280c5ad41481f701c13a537a8c7319839e6f after https://github.com/kubernetes/kubernetes/pull/126224#discussion_r1685454873
needs LGTM again.

**Review by neolit123 — COMMENTED** [review]
/hold cancel
