### PR TITLE
Use native Ginkgo test runner instead of cmd/e2e

### LINKED ISSUE #5670: Move from `cmd/e2e` runner to native Ginkgo runner
This is an off-shoot of https://github.com/onsi/ginkgo/issues/146#issuecomment-83699596. I actually think that the structure of the existing `cmd/e2e` runner is wrong, and that we need to work towards getting the native Ginkgo runner working with our suite(s). This has the following advantages:

* Right now, we pretty much just generate [one suite](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/driver.go#L83). We really want to target at least a second group, a stress group. We could do this hackily with `--ginkgo.focus`, but we should have a better tool.
*  We've extended our own runner a couple of times just to add things the base runner already has. We should stop doing that.
* We're eventually going to want things the normal runner already has, like parallelism.

I'm not as well versed in the blockers. I remember part of it is as simple as the command-line flags: we take a host of flags to the tests and didn't want to take them as environment variables, but I think this one was easily solved? But I think the other blockers were just someone taking the time to actually do the work.

cc @onsi @rrati @roberthbailey @filbranden @fabioy

### PR DESCRIPTION
**Pull request by ixdy**
This PR deletes cmd/e2e and updates hack/ginkgo-e2e.sh to use the `ginkgo` command instead. All logic from cmd/e2e/e2e.go and test/e2e/driver.go have been combined into the new file test/e2e/e2e_test.go.

Additionally, several tests which made poor assumptions about cwd or used testContext before it was set have been fixed.

This change is generally intended to have no externally visible changes,
aside from the following caveats:
- Developers must run `go get github.com/onsi/ginkgo/ginkgo` once
- The `-t`/`--tests`, `--times`, and `--orderseed` flags have been removed (such functionality is already provided by Ginkgo itself)
- Calling cmd/e2e/e2e directly obviously won't work, but that was never
  supported anyway
- If the `GINKGO_PARALLEL` environment variable is set to `y`, then ginkgo will run test specs in pa rallel. (Currently defaults to `n`, since some tests are broken in this mode.)

Fixes #5670.

### CODE REVIEW

**Comment by ixdy** [comment]
@quinton-hoole @zmerlynn 

I'll note that I'm not particularly happy about requiring a `go get github.com/onsi/ginkgo/ginkgo` to be run manually. There's probably some way to get the `ginkgo` binary built as part of the rest of the build, but I'm not really sure how to get our "build system" to build stuff in Godeps etc and then reference that from our test scripts. I'm welcome to suggestions/feedback, though.

**Comment by ixdy** [comment]
I figured out how to use godep to build the checked-in version of Ginkgo and use it each time.

**Comment by quinton-hoole** [comment]
Excellent Jeff.  I'll start reviewing shortly.

**Comment by ixdy** [comment]
I've run e2e tests locally (via `go run hack/e2e.go -v --test` or `hack/ginkgo-e2e.sh`). They are still passing.

**Comment by ixdy** [comment]
Updated with a few fixes to ensure that Godeps are used when building the e2e tests.

Additionally, I added support to run Ginkgo in parallel mode (with `GINKGO_PARALLEL=y`), though this is turned off by default.

File: test/e2e/e2e_test.go [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+	"github.com/onsi/ginkgo/reporters"
+	"github.com/onsi/gomega"
+)
+
+type testResult bool
+
+var (
+	cloudConfig = &testContext.CloudConfig
+
+	orderseed = flag.Int64("orderseed", 0, "If non-zero, seed of random test shuffle order. (Otherwise random.)")
```
Comment (zmerlynn) [inline test/e2e/e2e_test.go]: I don't think this will ever be needed again. The gomega command already has support for a fixed seed.

File: test/e2e/e2e_test.go [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+	reportDir = flag.String("report-dir", "", "Path to the directory where the JUnit XML reports should be saved. Default is empty, which doesn't generate these reports.")
+	times     = flag.Int("times", 1, "Number of times each test is eligible to be run. Individual order is determined by shuffling --times instances of each test using --orderseed (like a multi-deck shoe of cards).")
```
Comment (zmerlynn) [inline test/e2e/e2e_test.go]: Do we still need this?

File: test/e2e/e2e_test.go [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+	flag.StringVar(&cloudConfig.ProjectID, "gce-project", "", "The GCE project being used, if applicable")
+	flag.StringVar(&cloudConfig.Zone, "gce-zone", "", "GCE zone being used, if applicable")
+}
+
+func (t *testResult) Fail() { *t = false }
+
+func TestE2E(t *testing.T) {
+	defer util.FlushLogs()
+
+	// Disable density test unless it's explicitly requested.
```
Comment (zmerlynn) [inline test/e2e/e2e_test.go]: I assume after this we can actually just split density off into its own directory and stop skipping it this BS way?

**Comment by zmerlynn** [comment]
This is awesome. Now that the release is cut and we're a little more stable, let's maybe get this in tomorrow morning?

File: test/e2e/e2e_test.go (hunk 1 above)
Comment (ixdy) [inline test/e2e/e2e_test.go]: good point. I'll remove it, along with its corresponding TODO.

File: test/e2e/e2e_test.go (hunk 2 above)
Comment (ixdy) [inline test/e2e/e2e_test.go]: I didn't remove it because I didn't want to remove any functionality in this change, but I'm fine to remove it if we think it isn't worthwhile to keep. (Ginkgo has a builtin --untilItFails option which will keep running until tests fail, which may be a better option anyway.)

File: test/e2e/e2e_test.go (hunk 3 above)
Comment (ixdy) [inline test/e2e/e2e_test.go]: Yes, we should be easily able to split off tests into their own packages and then choose which tests to run via the cmdline - we could have test/e2e/density or whatever which will include only those tests. (Would need a separate density_test.go file, in that case, so we might need to refactor some of the code here in e2e_test.go, but very feasible.)

File: test/e2e/e2e_test.go (hunk 2 above)
Comment (zmerlynn) [inline test/e2e/e2e_test.go]: I actually don't mind removing it because of `--untilItFails`, because that's the thing I'm usually trying to do if I want to run a set of tests multiple times. Also because it decreases the size of the entry code here, which looks like something we'd have to share with each "suite" - unless there's a different way to organize that you see? (After moving to the Ginkgo runner, I'd really like to pick off the density/long tests and get them out of e2e/hackiness, and I think it can be done with a minor refactor here.)

**Comment by ixdy** [comment]
OK, I added a new commit which removes `--times` and `--orderseed`. (Separate commit so you can see what changed, but I'm happy to squash, too.)

I left in the density hackiness and AWS stuff for now, though these should probably also get cleaned up at some point (maybe not in this change though?).

**Comment by zmerlynn** [comment]
Yeah, no problem with incremental changes. This change alone is pretty breaking and I just want to see it soak. It's also pretty enabling given the parallel e2e.

Have you figured out how to block parallelism at all?

**Comment by zmerlynn** [comment]
(Those buttons are too damn close.)

**Comment by ixdy** [comment]
Note that as currently written, it's not particularly easy to pass `--untilItFails` since this needs to be passed to the ginkgo runner binary, not to the e2e tests - similar to what I needed to do for parallel tests. I can add another argument to hack/ginkgo-e2e.sh, or I can leave it as is for now...

What do you mean by "block parallelism"? By default this still won't run tests in parallel.

**Comment by zmerlynn** [comment]
Just thinking for later. We're going to need a way to indicate that some tests can't run in parallel, and I didn't know if Ginkgo already had that facility. The way may be a sledgehammer, though: We could just organize it so that `services.sh`, our last real holdout that I *know* won't work, goes in a "long" suite, along with the reboot test that @mbforbes is working on (for example), etc., and that stuff just never gets executed in parallel.

**Comment by zmerlynn** [comment]
But this all LGTM. I'd prefer to wait 'til morning.

**Comment by ixdy** [comment]
Oddly enough, in my limited testing of parallel mode, it seemed like `services.sh` was doing just fine, though I don't have 100% confidence in that. (There were a few other tests which seemed less parallel-safe, likely due to not using namespaces.)

Overall I think we need a better strategy for selecting which tests to run. For example, all of the manual checking of cloud provider is an antipattern that causes bugs like #7008, and none of Ginkgo's metadata even indicates that such tests are skipped.

**Comment by ixdy** [comment]
@justinsb FYI, this shouldn't break your Jenkins instance, but it might be worth keeping an eye on as soon as it gets merged.

**Comment by a-robinson** [comment]
> The -t/--tests, --times, and --orderseed flags have been removed (such functionality is already provided by Ginkgo itself)

Which ginkgo flag replaces --times? For some reason the --times flag kept working for me until today, and I don't see anything related in the list of flags spit out when it complains about the unknown flag.

**Comment by ixdy** [comment]
Ginkgo has `--untilItFails`, which is similar to the functionality (usually) desired by `--times`.

**Comment by a-robinson** [comment]
I apparently have no idea how to run e2e tests anymore, since that flag also isn't recognized. This is what I used to run (as a modified hack/e2e-test.sh):
```
go run "$(dirname $0)/e2e.go" -v -test --check_version_skew=false --test_args="--ginkgo.focus=Services.*external* --times=10"
```
This is one of the variations I've tried just now:
```
go run "$(dirname $0)/e2e.go" -v -test --check_version_skew=false --test_args="--ginkgo.focus=Services.*external* --untilItFails=true"
```
It gives the error `flag provided but not defined: -untilItFails`. What should I be running to make this work?

**Comment by ixdy** [comment]
Oh, it seems like it needs to be specified as one of the args in $ginkgo_args in hack/ginkgo-e2e.sh. We probably need to allow adding these with an environment variable or something.
