### PR TITLE
Switch kubectl convert back to use legacyscheme and add tests

### LINKED ISSUE #54873: Flaky pre-submit: pull-kubernetes-unit - test-cmd.run_recursive_resources_tests
Test Grid: https://k8s-testgrid.appspot.com/presubmits-kubernetes#pull-kubernetes-unit&include-filter-by-regex=run_recursive_resources_tests
Last good: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50627/pull-kubernetes-unit/61621/
First bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/61622/
Suspected commit range: https://github.com/kubernetes/kubernetes/compare/bd28e6d...d0c4c56
Probable PR: https://github.com/kubernetes/kubernetes/pull/54533

Example [Build Log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/54790/pull-kubernetes-unit/61777/build-log.txt):
```
I1031 13:38:57.449] Recording: run_recursive_resources_tests
I1031 13:38:57.450] Running command: run_recursive_resources_tests
I1031 13:38:57.466] 
I1031 13:38:57.467] +++ Running case: test-cmd.run_recursive_resources_tests 
I1031 13:38:57.469] +++ working dir: /go/src/k8s.io/kubernetes
I1031 13:38:57.471] +++ command: run_recursive_resources_tests
I1031 13:38:57.478] +++ [1031 13:38:57] Testing recursive resources
I1031 13:38:57.483] +++ [1031 13:38:57] Creating namespace namespace1509457137479932506
I1031 13:38:57.610] namespace "namespace1509457137479932506" created
I1031 13:38:57.714] Context "test" modified.
I1031 13:38:57.849] test-cmd-util.sh:1858: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: 
I1031 13:38:58.227] (Btest-cmd-util.sh:1862: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:38:58.229] (BSuccessful
I1031 13:38:58.229] message:pod "busybox0" created
I1031 13:38:58.229] pod "busybox1" created
I1031 13:38:58.229] error: error validating "hack/testdata/recursive/pod/pod/busybox-broken.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
I1031 13:38:58.229] has:error validating data: kind not set
I1031 13:38:58.394] test-cmd-util.sh:1867: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:38:58.680] (Btest-cmd-util.sh:1875: Successful get pods {{range.items}}{{(index .spec.containers 0).image}}:{{end}}: busybox:busybox:
I1031 13:38:58.682] (BSuccessful
I1031 13:38:58.682] message:error: unable to decode "hack/testdata/recursive/pod/pod/busybox-broken.yaml": Object 'Kind' is missing in '{"apiVersion":"v1","ind":"Pod","metadata":{"labels":{"app":"busybox2"},"name":"busybox2"},"spec":{"containers":[{"command":["sleep","3600"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"busybox"}],"restartPolicy":"Always"}}'
I1031 13:38:58.682] has:Object 'Kind' is missing
I1031 13:38:58.851] test-cmd-util.sh:1882: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:38:59.235] (Btest-cmd-util.sh:1886: Successful get pods {{range.items}}{{.metadata.labels.status}}:{{end}}: replaced:replaced:
I1031 13:38:59.237] (BSuccessful
I1031 13:38:59.237] message:pod "busybox0" replaced
I1031 13:38:59.238] pod "busybox1" replaced
I1031 13:38:59.238] error: error validating "hack/testdata/recursive/pod-modify/pod/busybox-broken.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
I1031 13:38:59.238] has:error validating data: kind not set
I1031 13:38:59.406] test-cmd-util.sh:1891: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:38:59.578] (BSuccessful
I1031 13:38:59.599] unable to decode "hack/testdata/recursive/pod/pod/busybox-broken.yaml": Object 'Kind' is missing in '{"apiVersion":"v1","ind":"Pod","metadata":{"labels":{"app":"busybox2"},"name":"busybox2"},"spec":{"containers":[{"command":["sleep","3600"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"busybox"}],"restartPolicy":"Always"}}'
I1031 13:38:59.599] has:Object 'Kind' is missing
I1031 13:38:59.749] test-cmd-util.sh:1901: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:39:00.042] (Btest-cmd-util.sh:1905: Successful get pods {{range.items}}{{.metadata.annotations.annotatekey}}:{{end}}: annotatevalue:annotatevalue:
I1031 13:39:00.044] (BSuccessful
I1031 13:39:00.045] message:pod "busybox0" annotated
I1031 13:39:00.045] pod "busybox1" annotated
I1031 13:39:00.045] error: unable to decode "hack/testdata/recursive/pod/pod/busybox-broken.yaml": Object 'Kind' is missing in '{"apiVersion":"v1","ind":"Pod","metadata":{"labels":{"app":"busybox2"},"name":"busybox2"},"spec":{"containers":[{"command":["sleep","3600"],"image":"busybox","imagePullPolicy":"IfNotPresent","name":"busybox"}],"restartPolicy":"Always"}}'
I1031 13:39:00.045] has:Object 'Kind' is missing
I1031 13:39:00.212] test-cmd-util.sh:1910: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: busybox0:busybox1:
I1031 13:39:00.575] (Btest-cmd-util.sh:1914: Successful get pods {{range.items}}{{.metadata.labels.status}}:{{end}}: replaced:replaced:
I1031 13:39:00.577] (BSuccessful
I1031 13:39:00.577] message:Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
I1031 13:39:00.577] pod "busybox0" configured
I1031 13:39:00.577] Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
I1031 13:39:00.577] pod "busybox1" configured
I1031 13:39:00.578] error: error validating "hack/testdata/recursive/pod-modify/pod/busybox-broken.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
I1031 13:39:00.578] has:error validating data: kind not set
I1031 13:39:00.707] test-cmd-util.sh:1920: Successful get deployment {{range.items}}{{.metadata.name}}:{{end}}: 
I1031 13:39:00.896] (Bdeployment "nginx" created
W1031 13:39:00.996] I1031 13:39:00.897117   15215 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"namespace1509457137479932506", Name:"nginx", UID:"da5eb3ec-be40-11e7-b109-0242ac110002", APIVersion:"extensions", ResourceVersion:"781", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set nginx-5cb7fb9f96 to 3
W1031 13:39:00.997] I1031 13:39:00.905030   15215 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"namespace1509457137479932506", Name:"nginx-5cb7fb9f96", UID:"da5f4858-be40-11e7-b109-0242ac110002", APIVersion:"extensions", ResourceVersion:"782", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: nginx-5cb7fb9f96-vn6l6
W1031 13:39:00.997] I1031 13:39:00.907985   15215 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"namespace1509457137479932506", Name:"nginx-5cb7fb9f96", UID:"da5f4858-be40-11e7-b109-0242ac110002", APIVersion:"extensions", ResourceVersion:"782", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: nginx-5cb7fb9f96-wlxhx
W1031 13:39:00.997] I1031 13:39:00.908780   15215 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"namespace1509457137479932506", Name:"nginx-5cb7fb9f96", UID:"da5f4858-be40-11e7-b109-0242ac110002", APIVersion:"extensions", ResourceVersion:"782", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: nginx-5cb7fb9f96-6wk2n
I1031 13:39:01.098] test-cmd-util.sh:1924: Successful get deployment {{range.items}}{{.metadata.name}}:{{end}}: nginx:
I1031 13:39:01.231] (Btest-cmd-util.sh:1925: Successful get deployment {{range.items}}{{(index .spec.template.spec.containers 0).image}}:{{end}}: gcr.io/google-containers/nginx:test-cmd:
I1031 13:39:01.388] (Bextensions/v1beta1
I1031 13:39:01.568] test-cmd-util.sh:1930: Successful get deployment nginx {{ .apiVersion }}: extensions/v1beta1
I1031 13:39:01.570] (BFAIL!
I1031 13:39:01.570] message:extensions/v1beta1
I1031 13:39:01.570] has not:apps/v1beta1
I1031 13:39:01.570] 1931 /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh
I1031 13:39:01.598] +++ exit code: 1
I1031 13:39:01.603] +++ error: 1
I1031 13:39:01.629] Error when running run_recursive_resources_tests
```

---
cc: @kubernetes/sig-cli-test-failures @mengqiy @monopole @smarterclayton @sttts @pwittrock

### PR DESCRIPTION
**Pull request by mengqiy**
Revert the change of `convert.go` in #54533.
Add tests for kubectl convert.

Fixes #54873 

```release-note
NONE
```

cc: @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
How does this not break the point of kubectl convert (which needs to have access to internal types in order to work)?

**Comment by smarterclayton** [comment]
I can't think of a case where you'd end up with an internal object but not be able to convert it back?  Can you describe when that would happen?  Are you seeing unstructured objects in the internal type?

File: pkg/kubectl/cmd/convert.go [hunk 1]
```diff
@@ -254,16 +254,21 @@ func asVersionedObject(infos []*resource.Info, forceList bool, version schema.Gr
 func asVersionedObjects(infos []*resource.Info, version schema.GroupVersion, encoder runtime.Encoder) ([]runtime.Object, error) {
 	objects := []runtime.Object{}
 	for _, info := range infos {
-		if info.Object == nil {
+		var obj runtime.Object
+		if info.VersionedObject != nil {
+			obj = info.VersionedObject
```
Comment (liggitt) [inline pkg/kubectl/cmd/convert.go]: there's no guarantee the versioned object is convertible to the desired output. It usually isn't.

**Comment by mengqiy** [comment]
Part of the kubectl code has switched to use kubectl's own instance of scheme and registry. See: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scheme/scheme.go#L30-L43

Only external types are registered. See: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/scheme/install.go#L58-L60

The issue here is that the new scheme (also a converter) doesn't know the internal types.

An simple fix can be switch back to use pkg/api/legacyscheme.Scheme that has registered with internal types.

> there's no guarantee the versioned object is convertible to the desired output. It usually isn't.

But the eventual state is no kubectl code depends on internal types, including `kubectl convert`.
Do we have a apimachinery to convert from an external version to another external version???

**Comment by smarterclayton** [comment]
No, we don't.  Removing internal versions means convert is now broken.  The internal version is the "hub" between which all objects pass back and forth.

You have a couple of options - you can split it out into a standalone command that continues to use the internal versions.  You can add the internal versions to kubectl.  You can remove convert entirely (after determining which users are affected).

**Comment by dims** [comment]
@mengqiy @smarterclayton @liggitt - Should we revert https://github.com/kubernetes/kubernetes/pull/54533 until a better way is found/agreed?

**Comment by smarterclayton** [comment]
Also, printers still need internal versions until we move to server side get, and even then, we'll have to support client side internal version printers for at least a release or two.

**Comment by liggitt** [comment]
> Should we revert #54533 until a better way is found/agreed?

Scanning through that PR, the `convert.go` change is the only obvious break I see (thought the internal printer issue @smarterclayton mentioned still requires internal objects... not sure where master is at with respect to that)

For the moment, I'd recommend:
* revert just the change to `convert.go`
* add tests that actually exercise `kubectl convert`, which should have caught the break... to do that, you need to test conversion that does not succeed using reflection/field-copy (like one of the objects with schema differences from extensions/v1beta1 to apps/v1beta2 or something

**Comment by mengqiy** [comment]
> - revert just the change to convert.go
> - add tests that actually exercise kubectl convert, which should have caught the break... to do that, you need to test conversion that does not succeed using reflection/field-copy (like one of the objects with schema differences from extensions/v1beta1 to apps/v1beta2 or something

SG. I will update the PR shortly.

**Comment by mengqiy** [comment]
> to do that, you need to test conversion that does not succeed using reflection/field-copy (like one of the objects with schema differences from extensions/v1beta1 to apps/v1beta2 or something

Added a test that is not exactly as described above, because I can't find an resource meet that requirement.

**Comment by liggitt** [comment]
> Added a test that is not exactly as described above, because I can't find an resource meet that requirement.

HorizontalPodAutoscaler spec changed shape between v1 and v2beta1… you can use that

File: pkg/kubectl/cmd/convert_test.go [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+	tf.Namespace = "test"
+	buf := bytes.NewBuffer([]byte{})
+
+	cmd := NewCmdConvert(f, buf)
+	cmd.Flags().Set("filename", "../../../test/fixtures/pkg/kubectl/cmd/convert/appsdeployment.yaml")
+	cmd.Flags().Set("output-version", "extensions/v1beta1")
+	cmd.Flags().Set("local", "true")
+	cmd.Run(cmd, []string{})
+
+	if !strings.Contains(buf.String(), "extensions/v1beta1") {
```
Comment (liggitt) [inline pkg/kubectl/cmd/convert_test.go]: Not just the kind/version… need to make sure the conversion was actually correct. Check a field that depends on an internal conversion to be correct (can’t just be done by reflection between field names and types)

A good example is a v1 HPA object with targetCPUUtilizationPercentage converting to the corresponding v2beta1 metric spec source

Comment (mengqiy) [reply pkg/kubectl/cmd/convert_test.go]: I will add another one to check field are correct.
I want to keep this one to make sure cross-group conversion works.

**Comment by mengqiy** [comment]
PTAL

**Comment by liggitt** [comment]
/lgtm
great test
