### PR TITLE
Azure disk volume fixes

### LINKED ISSUE #36571: Azure disk: dynamic pv get failed status before deleted
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.345+0f082c66630097-dirty", GitCommit:"0f082c6663009733a8192b63ca4052308889bfc8", GitTreeState:"dirty", BuildDate:"2016-11-10T06:07:31Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.345+0f082c66630097-dirty", GitCommit:"0f082c6663009733a8192b63ca4052308889bfc8", GitTreeState:"dirty", BuildDate:"2016-11-10T06:07:31Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**: Linux
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): RHEL 7.3
- **Install tools**: hack/local-up-cluster.sh

**What happened**:
1. Create storage class
```
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: slow
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_ZRS
  location: eastus
  storageAccount: someaccount
```
2. Create pvc annotated with this storage class
```
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1",
    "annotations": {
      "volume.beta.kubernetes.io/storage-class": "slow"
    }
  },
  "spec": {
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "1Gi"
      }
    }
  }
}
```
3. Create a pod consume this pvc
4. Check read/write function with the mounted path
5. Delete pod/pvc
6. Check the pv status which is "Failed"
```
$ kc describe pv pvc-b878db4c-a719-11e6-834b-000d3a14b644
Name:		pvc-b878db4c-a719-11e6-834b-000d3a14b644
Labels:		<none>
StorageClass:	slow
Status:		Failed
Claim:		default/claim1
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	1Gi
Message:	failed to delete vhd https://someaccount.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd, account someaccount, blob kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd, err: storage: service returned error: StatusCode=412, ErrorCode=LeaseIdMissing, ErrorMessage=There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:a244715f-0001-013b-3828-3b2cf6000000
Time:2016-11-10T08:02:09.5143459Z, RequestId=a244715f-0001-013b-3828-3b2cf6000000, QueryParameterName=, QueryParameterValue=
Source:
    Type:		AzureDisk (an Azure Data Disk mount on the host and bind mount to the pod)
    DiskName:		kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd
    DiskURI:		https://someaccount.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd
    FSType:		ext4
    CachingMode:	None
    ReadOnly:		false
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  10s		10s		1	{persistentvolume-controller }			Warning		VolumeFailedDelete	failed to delete vhd https://someaccount.blob.core.windows.net/vhds/kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd, account someaccount, blob kubernetes-dynamic-pvc-b878db4c-a719-11e6-834b-000d3a14b644.vhd, err: storage: service returned error: StatusCode=412, ErrorCode=LeaseIdMissing, ErrorMessage=There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:a244715f-0001-013b-3828-3b2cf6000000
Time:2016-11-10T08:02:09.5143459Z, RequestId=a244715f-0001-013b-3828-3b2cf6000000, QueryParameterName=, QueryParameterValue=

```

**What you expected to happen**:
PV should not have "Failed" status before deleted

**How to reproduce it** (as minimally and precisely as possible):
Always

**Anything else do we need to know**:

### LINKED ISSUE #38362: Azure disk:  Fail to find storage account if there is no "vhds" container in it
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1011+42d5a1a9cd4aca", GitCommit:"42d5a1a9cd4acae9c7b258c21bfc4fb4955d7be3", GitTreeState:"clean", BuildDate:"2016-11-30T07:19:12Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.1011+42d5a1a9cd4aca", GitCommit:"42d5a1a9cd4acae9c7b258c21bfc4fb4955d7be3", GitTreeState:"clean", BuildDate:"2016-11-30T07:19:12Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): RHEL 7.3
- **Install tools**: Ansible

**What happened**:
PVC keeps pending with a new created storage account

**What you expected to happen**:
Storage class can find storage account and then create a dynamic pv for pvc to bind

**How to reproduce it** (as minimally and precisely as possible):
1. Create a new storage account without create any container
2. Create a storage class as below
```
[root@wehe-master1 azure]# cat azscw-LRS.yaml 
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: wlrs 
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: westus 
  storageAccount: qewestus 

[root@wehe-master1 azure]# kubectl describe storageclass wlrs
Name:		wlrs
IsDefaultClass:	No
Annotations:	<none>
Provisioner:	kubernetes.io/azure-disk
Parameters:	location=westus,skuName=Standard_LRS,storageAccount=qewestus
No events.

```
3. Create a pvc annotating this storage class
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azpvcwest
  annotations:        
    volume.beta.kubernetes.io/storage-class: wlrs 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
```
4. Check pvc status is pending
```
[root@wehe-master1 ~]# kubectl describe pvc azpvcwest
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  16h		11s		3940	{persistentvolume-controller }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "wlrs": failed to find a matching storage account
```

**Anything else do we need to know**:
After I create a new container "vhds" in storage account of "qewestus", storage class works and pvc is bound
```
[root@wehe-master1 ~]# kubectl get pvc
NAME        STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
azpvcwest   Bound     pvc-703fc37c-bc65-11e6-b2be-000d3a194418   1Gi        RWO           16h
```

### PR DESCRIPTION
**Pull request by rootfs**
fix #36571: Do not report error when deleting an attached volume
fix #38362: create blob vhds container if not exists

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37845)

**Comment by rootfs** [comment]
@colemickens PTAL, thanks

File: pkg/cloudprovider/providers/azure/azure_blob.go [hunk 1]
```diff
@@ -41,8 +42,19 @@ func (az *Cloud) createVhdBlob(accountName, accountKey, name string, sizeGB int6
 	name = name + ".vhd"
 	err = blobClient.PutPageBlob(vhdContainerName, name, vhdSize, tags)
 	if err != nil {
+		// if container doesn't exist, create one and retry PutPageBlob
```
Comment (colemickens) [inline pkg/cloudprovider/providers/azure/azure_blob.go]: any reason you do this rather than just querying for the storage container to see if it exists, rather than handling it as an error?

**Review by colemickens — APPROVED** [review]
small question, but LGTM

**Comment by colemickens** [comment]
@rootfs one question about why you handle the missing container in the error scenario rather than explicitly checking to see if it exists first.

**Comment by rootfs** [comment]
@colemickens yes checking container existence is a good idea. The create-if-not-exist idea here saves me an API call though.

File: pkg/cloudprovider/providers/azure/azure_blob.go (hunk 1 above)
Comment (rootfs) [inline pkg/cloudprovider/providers/azure/azure_blob.go]: I am frugal with API quota :)

**Comment by colemickens** [comment]
@rootfs I can't edit labels, easiest way forward is for you to add a release note, I believe. Thanks.

**Comment by rootfs** [comment]
@colemickens thanks!
