### PR TITLE
Fix concurrent read/write to map error in kubelet

### LINKED ISSUE #37560: kubelet: concurrent map read & write
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-cri/644

bootstrap-e2e-minion-group-22bp/kubelet.log

```
fatal error: concurrent map read and map write
goroutine 79 [running]:
runtime.throw(0x29b56bd, 0x21)
/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420b41660 sp=0xc420b41640
runtime.mapaccess1_faststr(0x2491400, 0xc4215c0780, 0x29c7833, 0x27, 0x3efc2e0)
/usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc420b416c0 sp=0xc420b41660
k8s.io/kubernetes/pkg/api/v1/pod.SetInitContainersAndStatuses(0xc421227340, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/v1/pod/util.go:67 +0x57 fp=0xc420b41738 sp=0xc420b416c0
k8s.io/kubernetes/pkg/kubelet/config.newSourceApiserverFromLW.func1(0xc4204dd7a0, 0x11, 0x11)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:44 +0xa4 fp=0xc420b41818 sp=0xc420b41738
k8s.io/kubernetes/pkg/client/cache.(*UndeltaStore).Update(0xc4209d6a40, 0x2903dc0, 0xc4200d3340, 0xc4200d3340, 0x1)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/undelta_store.go:57 +0x9b fp=0xc420b41850 sp=0xc420b41818
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc420287c00, 0x3e15700, 0xc4208b0570, 0xc420b41c40, 0xc420bce4e0, 0xc42005e900, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:368 +0x8a3 fp=0xc420b41b18 sp=0xc420b41850
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc420287c00, 0xc42005e900, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:313 +0xa6f fp=0xc420b41e20 sp=0xc420b41b18
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:187 +0x36 fp=0xc420b41e50 sp=0xc420b41e20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420335140)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e fp=0xc420b41e88 sp=0xc420b41e50
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420335140, 0x3b9aca00, 0x0, 0x1, 0xc42005e900)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad fp=0xc420b41f50 sp=0xc420b41e88
k8s.io/kubernetes/pkg/util/wait.Until(0xc420335140, 0x3b9aca00, 0xc42005e900)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d fp=0xc420b41f88 sp=0xc420b41f50
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420b41f90 sp=0xc420b41f88
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:190 +0x1ad
```

The offending line was added by #36673

/cc @dchen1107

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #37560.

The concurrent read/write is to the pod annotations. The call in apiserver.go reads the annotations, and the config.go writes the annotations. I moved the reads to config.go to avoid the race.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37569)

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot test this

File: pkg/kubelet/config/config.go [hunk 1]
```diff
@@ -254,6 +255,17 @@ func (s *podStorage) merge(source string, change interface{}) (adds, updates, de
 	}
 
 	update := change.(kubetypes.PodUpdate)
+	// The InitContainers and InitContainerStatuses fields are lost during
```
Comment (caesarxuchao) [inline pkg/kubelet/config/config.go]: It is called before updatePodFunc() gets called, so should be ok.

Comment (Random-Liu) [inline pkg/kubelet/config/config.go]: It should be fine to put the code here. :)

**Comment by yujuhong** [comment]
@k8s-bot gci gke e2e test this

**Comment by yujuhong** [comment]
@k8s-bot cvm gke e2e test this

**Comment by caesarxuchao** [comment]
Fix #37482.

**Comment by caesarxuchao** [comment]
```
ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1]
```
Looks like a test infra problem.

**Comment by caesarxuchao** [comment]
@k8s-bot gce etcd3 e2e test this
