### PR TITLE
fix cpumanager reconcileState without sourceready 

### LINKED ISSUE #81324: cpumanager will remove all entries in state file after restart.
**What happened**:
PR #68619 , it will remove "inactive containers" while reconciling. But the cpumanager started very beginning, it will get empty activePods at it first run. This make state file no sense.

**What you expected to happen**:
We should wait a moment or  notification from podmanager before starting reconcile.
 Some log may be added before remove "inactive containers".

**How to reproduce it (as minimally and precisely as possible)**:
restart kubelet

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug

**What this PR does / why we need it**:
We should check sourceReady  before starting reconcile.

**Which issue(s) this PR fixes**:

Fixes #81324

**Special notes for your reviewer**:
sourcesReady provides the readiness of kubelet configuration sources such as apiserver update readiness.
We use it to determine when we can purge inactive pods from checkpointed state.

**Does this PR introduce a user-facing change?**:

```release-note
sourcesReady provides the readiness of kubelet configuration sources such as apiserver update readiness.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zouyee** [comment]
/sig node
/area kubelet
@kubernetes/sig-node-bugs

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 1]
```diff
@@ -147,13 +157,14 @@ func NewManager(cpuPolicyName string, reconcilePeriod time.Duration, machineInfo
 		machineInfo:                machineInfo,
 		nodeAllocatableReservation: nodeAllocatableReservation,
 	}
+	manager.sourcesReady = &sourcesReadyStub{}
```
Comment (choury) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go]: Why add this line when constructing manager?

Comment (zouyee) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: initializes sourcesReady to perform no-op operations.

Comment (choury) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: I mean why not add this line after [L163](https://github.com/kubernetes/kubernetes/pull/81344/files#diff-67c46e7cbb41ea5e675000a3298e6b32R163)

**Comment by neolit123** [comment]
@zouyee
LGTM on a quick look, but it's better to assign the folks that maintain this are of the code base. try pinging #sig-node or #pr-reviews on slack if needed.

thanks
/unassign

**Comment by zouyee** [comment]
thank you @neolit123 
/assign @derekwaynecarr

**Comment by choury** [comment]
@zouyee Any updates?

**Comment by zouyee** [comment]
@derekwaynecarr PTAL
/retest

**Comment by zouyee** [comment]
@ConnorDoyle @odinuge PTAL 😄

**Comment by zouyee** [comment]
gentle ping @derekwaynecarr

**Comment by klueska** [comment]
@zouyee Thanks for your PR. Sorry I'm just now seeing it.

Would it be possible for you to include an e2e test that fails before this fix, but succeeds after? I haven't actually run into this issue myself, so I'm curious exactly what triggers it.

It's not just a simple kubelet restart because I test this scenario manually quite often, and we also have an e2e test that verifies that the state remains in tact across kubelet restarts:  https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/cpu_manager_test.go#L479

I could maybe see this bug being triggered by the following sequence of events:
1) Kubelet stopped
2) API server becomes unreachable
3) Kubelet start --> State file wiped
4) API server reachable again

It would be good to have a test that verifies this though.

Also, this patch will need a rebase one https://github.com/kubernetes/kubernetes/pull/84196 lands since the logic to remove stale state is being abstracted out into its own function.

**Comment by zouyee** [comment]
@klueska OK

**Comment by klueska** [comment]
I have independently verified this issue and the proposed fix.

The issue was first introduced by the following commit and included as part of kubernetes v1.14.0: https://github.com/kubernetes/kubernetes/commit/10995f661d0d025b6f1ed6ad0fb5c858b1b5ef76

The problematic commit adds support to garbage collect any stale state the CPUManager maintains for containers not in the `activePods` list. However, this list is typically out-of-date (e.g. empty) when a kubelet restart occurs, essentially emptying out *all* stored state for the CPUManager as it comes online.

the proposed fix makes sure that this cleanup doesn't happen until *after* the activePods list has been populated.

/lgtm

**Comment by ConnorDoyle** [comment]
Let’s proceed with this change, given that it mirrors the current behavior of the device manager.

/approve
