### PR TITLE
skip re-allocate logic if pod is already removed to avoid panic

### LINKED ISSUE #103838: DeviceManager panic on Allocate()
#### What happened:
Pod worker panic when trying to re-allocating the device plugin resource during the node restart. 

The issue is potentially caused by [m.devicesToReuse map deleting](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/manager.go#L376) an un-matching pod id. The map will be later used in an [assignment](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/pod_devices.go#L158), which caused panic. ([Allocate()](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/manager.go#L369) func by itself is not thread-safe)

Stack trace:
```
runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 1419 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3cd4a80, 0x4c848b0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3cd4a80, 0x4c848b0)
 /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.podDevices.removeContainerAllocatedResources(0xc000960000, 0xc00140e240, 0x24, 0xc000c789f0, 0x9, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/pod_devices.go:109 +0x1b2
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000995790, 0xc001475800, 0xc001302dc0, 0x42, 0xc001a21d88)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:388 +0x373
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).GetDeviceRunContainerOptions(0xc000995790, 0xc001475800, 0xc001302dc0, 0x0, 0x0, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:881 +0x5af
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).GetResources(0xc000430fc0, 0xc001475800, 0xc001302dc0, 0x70, 0x70, 0x42f7840)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:661 +0x83
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).GenerateRunContainerOptions(0xc000ec2a80, 0xc001475800, 0xc001302dc0, 0xc001d0a904, 0xb, 0xc00221d0c0, 0x1, 0x1, 0x3, 0x0, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:455 +0x6c
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).generateContainerConfig(0xc0000ff900, 0xc001302dc0, 0xc001475800, 0x1, 0xc001d0a904, 0xb, 0xc0014aeeb0, 0x47, 0xc00221d0c0, 0x1, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:247 +0xa7
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).startContainer(0xc0000ff900, 0xc00219c000, 0x40, 0xc0001985b0, 0xc00221d190, 0xc001475800, 0xc0009a1b00, 0xc000191180, 0x1, 0x1, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:166 +0x5bf
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod.func1(0x458330a, 0x9, 0xc00221d190, 0xc000198500, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:816 +0x8e3
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc0000ff900, 0xc001475800, 0xc0009a1b00, 0xc000191180, 0x1, 0x1, 0xc000d20dc0, 0xc0021afda0, 0x4, 0x4, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:855 +0xc24
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc000ec2a80, 0x0, 0xc001475800, 0x0, 0xc0009a1b00, 0x0, 0xc000db1440, 0xc000604660)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1719 +0x1018
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc0021fdea0, 0xc00036a460, 0xc000f4fe88, 0x4d35e00, 0xc000a354c0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:175 +0x25d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc00036a460, 0xc001c947e0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:184 +0x13f
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0xc00036a460, 0xc001c947e0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:222 +0x6c
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:220 +0x3d3
```

#### What you expected to happen:
DeviceManager Allocate() should be able to handle such race safely. 

#### How to reproduce it (as minimally and precisely as possible):
Customer reported issue after upgrading to 1.18+. 

#### Anything else we need to know?:
This is the new behavior introduced since 1.18+ from [this commit](https://github.com/kubernetes/kubernetes/commit/cb9fdc49db8ed56aea6569e1a9ab69920ae8cc2e).

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by waynepeking348**
**What type of PR is this?**

/kind bug   

**What this PR does / why we need it**:

as reported in issue #103838 and discussed in #102525, a concurrent read-and-write for calling Allocate in device manager may cause Kubelet to panic, all because of the re-allocating logic if a pod has already been removed from activePods

**Which issue(s) this PR fixes**:

Fixes #103838, and I also add some test cases

**Special notes for your reviewer**:

we can reproduce it by this steps:
1. pod-1 request for a device, and is successfully admitted
2. before  pod-1 is successfully started, a deletion is called for it, but one go-routine has already started to create containers for it; in that cases, pod-1 is removed from PodManager, and activePods will not find it anymore
3.  pod-2 request for a device, and is successfully admitted; in that case, during Allocate process of pod-2, it will call UpdateAllocatedDevices and set pendingAdmissionPod=pod-2 instead of pod-1, and clear pod-1 from podDevices
4. pod-1 goes to the logic of GetDeviceRunContainerOptions, it will find that podDevices doesn't contain pod-1, since it calls Allocate again
5. when pod-1 goes to allocateContainerResources function, pod-3 request for a device, and goes to admission logic; so when it calls Allocate, it will remove pod-1 from deviceToResue
6. when pod-1 comes back from  allocateContainerResources function, deviceToResue for pod-1 is nil, which will cause the panic in addContainerAllocatedResources and removeContainerAllocatedResources

**Does this PR introduce a user-facing change?**:
```release-note
Skip re-allocate logic if pod is already removed to avoid panic
```

### CODE REVIEW

**Comment by waynepeking348** [comment]
@klueska hi, could you please have a look at this fix? I saw that you have lots of comments and discussion in #102525 for this issue

**Comment by klueska** [comment]
I can see how this PR would avoid a panic, but I don't see how it addresses the underlying issue. As I mentioned in https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-989967170 my hunch is that this issue is already addressed by https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-989967170, but that has not yet been verified.

**Comment by klueska** [comment]
Thanks for clarifying. Yes I can see how the race is still possible in the current code base. My overall question, however, is more related to the following comment I had in https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-989967170:

> From what I can tell the code in GetDeviceRunContainerOptions() that actually calls Allocate() was added at a time before we actually did allocation at pod-admit time. We used to do device allocation only upon container start, which meant that UpdatePod() might end up being called before the "normal" path for allocate was called, triggering it to do it "on-demand" in the GetDeviceRunContainerOptions() call and then skipping it in the "normal" path.

I'm of the opinion that we probably should remove the call to `Allocate()` in `GetDeviceRunContainerOptions()` altogether because there should no longer be a race on having it called on node restart (all pods go through re-admission on node restart, so we are now guaranteed to call `Allocate()` there on all containers).

So I think the real race now is between these two calls:
```
        err := m.callPreStartContainerIfNeeded(podUID, contName, resource)
        if err != nil {
            return nil, err
        }

        // Pod deleted

        if m.podDevices.containerDevices(podUID, contName, resource) == nil {
            needsReAllocate = true
        }
```

Because the body of `m.callPrestartContainerIfNeeded()` has a call for:
```
    devices := m.podDevices.containerDevices(podUID, contName, resource)
    if devices == nil {
        m.mutex.Unlock()
        return fmt.Errorf("no devices found allocated in local cache for pod %s, container %s, resource %s", string(podUID), contName, resource)
    }
```

Which means that if it would never hit the call to `if m.podDevices.containerDevices(podUID, contName, resource) == nil` if it was already `nil` before calling `m.callPrestartContainerIfNeeded()`.

I guess what'm getting at here, is that I think the proper fix is to actually just remove the `if m.podDevices.containerDevices(podUID, contName, resource) == nil` check altogether (as well as the `Allocate()` call below it) and just let `m.podDevices.deviceRunContainerOptions()` return `nil`.

**Comment by waynepeking348** [comment]
> Thanks for clarifying. Yes I can see how the race is still possible in the current code base. My overall question, however, is more related to the following comment I had in [#102525 (comment)](https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-989967170):
> 
> > From what I can tell the code in GetDeviceRunContainerOptions() that actually calls Allocate() was added at a time before we actually did allocation at pod-admit time. We used to do device allocation only upon container start, which meant that UpdatePod() might end up being called before the "normal" path for allocate was called, triggering it to do it "on-demand" in the GetDeviceRunContainerOptions() call and then skipping it in the "normal" path.
> 
> I'm of the opinion that we probably should remove the call to `Allocate()` in `GetDeviceRunContainerOptions()` altogether because there should no longer be a race on having it called on node restart (all pods go through re-admission on node restart, so we are now guaranteed to call `Allocate()` there on all containers).
> 
> So I think the real race now is between these two calls:
> 
> ```
>         err := m.callPreStartContainerIfNeeded(podUID, contName, resource)
>         if err != nil {
>             return nil, err
>         }
> 
>         // Pod deleted
> 
>         if m.podDevices.containerDevices(podUID, contName, resource) == nil {
>             needsReAllocate = true
>         }
> ```
> 
> Because the body of `m.callPrestartContainerIfNeeded()` has a call for:
> 
> ```
>     devices := m.podDevices.containerDevices(podUID, contName, resource)
>     if devices == nil {
>         m.mutex.Unlock()
>         return fmt.Errorf("no devices found allocated in local cache for pod %s, container %s, resource %s", string(podUID), contName, resource)
>     }
> ```
> 
> Which means that if it would never hit the call to `if m.podDevices.containerDevices(podUID, contName, resource) == nil` if it was already `nil` before calling `m.callPrestartContainerIfNeeded()`.
> 
> I guess what'm getting at here, is that I think the proper fix is to actually just remove the `if m.podDevices.containerDevices(podUID, contName, resource) == nil` check altogether (as well as the `Allocate()` call below it) and just let `m.podDevices.deviceRunContainerOptions()` return `nil`.


hi～ I have changed code and test cases according to this comment, could you please help with this new mr? I think I need both /lgtm and /appoved label to make it merged, thx~

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -1013,6 +1025,12 @@ func (m *ManagerImpl) GetDeviceRunContainerOptions(pod *v1.Pod, container *v1.Co
 		if err != nil {
 			return nil, err
 		}
+
+		if !m.checkPodActive(pod) {
+			klog.ErrorS(nil, "pod deleted from activePods, skip to reAllocate", "podUID", podUID)
+			continue
+		}
+
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager.go:1033]: I don't believe we need this check at all. I think we just need to remove the entire code block below:
```
		// This is a device plugin resource yet we don't have cached
		// resource state. This is likely due to a race during node
		// restart. We re-issue allocate request to cover this race.
		if m.podDevices.containerDevices(podUID, contName, resource) == nil {
			needsReAllocate = true
		}
```
As well as this one:
```
	if needsReAllocate {
		klog.V(2).InfoS("Needs to re-allocate device plugin resources for pod", "pod", klog.KObj(pod), "containerName", container.Name)
		if err := m.Allocate(pod, container); err != nil {
			return nil, err
		}
	}
```
Without any additional checks or errors being propagated back up from this function.

Comment (waynepeking348) [reply pkg/kubelet/cm/devicemanager/manager.go:1033]: @klueska the reason why I keep this logic is that I can only reproduce the panic by steps showing above, but I can't tell for sure whether there is another scenario that we may need to re-allocate devices. in order to make sure any pod requesting for devices won't be running without them (which may cause a unexpected error for online services), we prefer to panic in our production environment, so I add this check rather than just remove them all. but if you insist, please make me know, I can try to delete . thx

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:1033]: Yes. Please remove it as suggested.

As I mentioned before, now that we do allocation at pod admit time (rather than during container start) calling `Allocate()` in this function is actually incorrect.

Specifically, the changes in 0d68bffd03f1af15fc8cbb3eaeda9ff95a47eeab moved allocation from the container start path to the pod admit path, at which point this code in `GetDeviceRunContainerOptions()` should have been removed (but was overlooked).

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:1033]: Actually thinking about this a bit more, let's go with your proposal (to at least mask the underlying issue) and then reevaluate if it makes sense to make the change I propose above at a later time.
