### PR TITLE
Fix spurious statefulset rollout from 1.33 → 1.34

### LINKED ISSUE #134773: Upgrading from 1.33 → 1.34 triggers a spurious rollout of existing StatefulSets
### What happened?

Since 1.34 upgrade we detected pods rollout of all our statefulset in the cluster.

After checking the diff before/after it seems that the rollout is coming from the removal of this field `creationTimestamp: null` in spec.template.metadata part.

Related PR: https://github.com/kubernetes/kubernetes/pull/130989/files#diff-852b629be7dedc81069c59d93e421333ed7bba4f35fdca69dfad9d8ca9c16e8b

### What did you expect to happen?

No rollout of the pods.

### How can we reproduce it (as minimally and precisely as possible)?

Create a statefulset in a 1.33 cluster and upgrade it to 1.34.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.1-eks-d96d92f
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Fixes an issue with statefulsets spuriously triggering a rollout when upgrading the control plane from 1.33 to 1.34.

#### Which issue(s) this PR is related to:

Fixes #134773

#### Special notes for your reviewer:

Results of running the unit test and benchmark on 1.33.0 and 1.34.0

1.33.0
```
go test ./pkg/controller/statefulset -run Compat -v

--- FAIL: TestStatefulSetCompatibility (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.33_set,_1.33_rev (0.00s)
    --- FAIL: TestStatefulSetCompatibility/1.34_set,_1.34_rev (0.00s)
    --- FAIL: TestStatefulSetCompatibility/1.34_set,_1.33+1.34_rev (0.00s)

go test ./pkg/controller/statefulset -run X -bench Compat/1.33.*1.33 -benchmem -count 10
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
cpu: Apple M4 Pro
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   63850	     17801 ns/op	   17703 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   66964	     17929 ns/op	   17703 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   66476	     18099 ns/op	   17706 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   65877	     18251 ns/op	   17705 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   65268	     18207 ns/op	   17705 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   65715	     17983 ns/op	   17705 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   67746	     18028 ns/op	   17706 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   66454	     18065 ns/op	   17704 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   66105	     18141 ns/op	   17705 B/op	     342 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14         	   65481	     18308 ns/op	   17705 B/op	     342 allocs/op
PASS
ok  	k8s.io/kubernetes/pkg/controller/statefulset	14.328s

```

1.34.0
```
go test ./pkg/controller/statefulset -run Compat -v

--- FAIL: TestStatefulSetCompatibility (0.00s)
    --- FAIL: TestStatefulSetCompatibility/1.33_set,_1.33_rev (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.34_set,_1.34_rev (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.34_set,_1.33+1.34_rev (0.00s)

go test ./pkg/controller/statefulset -run X -bench Compat/1.34.*1.34 -benchmem -count 10

goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
cpu: Apple M4 Pro
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63721             18802 ns/op           17537 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63518             18753 ns/op           17535 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63938             19615 ns/op           17531 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    60384             18810 ns/op           17536 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    64057             18719 ns/op           17534 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    64388             18741 ns/op           17537 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    64256             18770 ns/op           17537 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    64424             18770 ns/op           17535 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63849             19759 ns/op           17534 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63900             18795 ns/op           17536 B/op        336 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               63714             18985 ns/op           17695 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62809             19146 ns/op           17695 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62428             19301 ns/op           17696 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61831             19272 ns/op           17695 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62383             19326 ns/op           17695 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62678             19317 ns/op           17698 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61628             19278 ns/op           17698 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61836             19404 ns/op           17695 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62208             19283 ns/op           17697 B/op        342 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62386             19190 ns/op           17693 B/op        342 allocs/op
PASS
ok      k8s.io/kubernetes/pkg/controller/statefulset    29.461s

```

HEAD
```
go test ./pkg/controller/statefulset -run Compat -v

--- PASS: TestStatefulSetCompatibility (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.33_set,_1.33_rev (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.34_set,_1.34_rev (0.00s)
    --- PASS: TestStatefulSetCompatibility/1.34_set,_1.33+1.34_rev (0.00s)

go test ./pkg/controller/statefulset -run X -bench Compat -benchmem -count 10

goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
cpu: Apple M4 Pro
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    62960             19145 ns/op           17247 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    62541             19761 ns/op           17245 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    63562             18843 ns/op           17241 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    64172             18810 ns/op           17247 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    63615             19219 ns/op           17246 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    62222             19435 ns/op           17245 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    61900             19359 ns/op           17240 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    61851             20072 ns/op           17248 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    61839             23228 ns/op           17245 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.33_set,_1.33_rev-14                    52710             19805 ns/op           17255 B/op        325 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    56888             21007 ns/op           17251 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    55178             27663 ns/op           17246 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    59791             22902 ns/op           17253 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    60820             27964 ns/op           17241 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    62756             19753 ns/op           17253 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63621             19069 ns/op           17253 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63433             18890 ns/op           17250 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63006             19156 ns/op           17250 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    60891             19016 ns/op           17256 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.34_rev-14                    63313             18928 ns/op           17250 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               63318             18936 ns/op           17248 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               63534             19528 ns/op           17251 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               64078             18841 ns/op           17253 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62408             19231 ns/op           17250 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               62041             19242 ns/op           17245 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               63009             19322 ns/op           17253 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61960             19521 ns/op           17257 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61326             19341 ns/op           17251 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               60400             20110 ns/op           17249 B/op        326 allocs/op
BenchmarkStatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14               61687             19416 ns/op           17254 B/op        326 allocs/op
PASS
ok      k8s.io/kubernetes/pkg/controller/statefulset    43.762s

```

```
benchstat 1.33.txt fix.txt 
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
cpu: Apple M4 Pro
                                                    │  1.33.txt   │               fix.txt               │
                                                    │   sec/op    │    sec/op     vs base               │
StatefulSetCompatibility/1.33_set,_1.33_rev-14        18.11µ ± 4%   19.40µ ±  3%  +7.11% (p=0.000 n=10)
StatefulSetCompatibility/1.34_set,_1.34_rev-14                      19.45µ ± 42%
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14                 19.33µ ±  2%
geomean                                               18.11µ        19.39µ        +7.11%

                                                    │   1.33.txt   │               fix.txt               │
                                                    │     B/op     │     B/op      vs base               │
StatefulSetCompatibility/1.33_set,_1.33_rev-14        17.29Ki ± 0%   16.84Ki ± 0%  -2.59% (p=0.000 n=10)
StatefulSetCompatibility/1.34_set,_1.34_rev-14                       16.85Ki ± 0%
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14                  16.85Ki ± 0%
geomean                                               17.29Ki        16.84Ki       -2.59%

                                                    │  1.33.txt  │              fix.txt              │
                                                    │ allocs/op  │ allocs/op   vs base               │
StatefulSetCompatibility/1.33_set,_1.33_rev-14        342.0 ± 0%   325.0 ± 0%  -4.97% (p=0.000 n=10)
StatefulSetCompatibility/1.34_set,_1.34_rev-14                     326.0 ± 0%
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14                326.0 ± 0%
geomean                                               342.0        325.7       -4.97%
```

```
benchstat 1.34.txt fix.txt 
goos: darwin
goarch: arm64
pkg: k8s.io/kubernetes/pkg/controller/statefulset
cpu: Apple M4 Pro
                                                    │  1.34.txt   │               fix.txt               │
                                                    │   sec/op    │    sec/op     vs base               │
StatefulSetCompatibility/1.34_set,_1.34_rev-14        18.78µ ± 4%   19.45µ ± 42%  +3.58% (p=0.002 n=10)
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14   19.28µ ± 1%   19.33µ ±  2%       ~ (p=0.353 n=10)
StatefulSetCompatibility/1.33_set,_1.33_rev-14                      19.40µ ±  3%
geomean                                               19.03µ        19.39µ        +1.91%

                                                    │   1.34.txt   │               fix.txt               │
                                                    │     B/op     │     B/op      vs base               │
StatefulSetCompatibility/1.34_set,_1.34_rev-14        17.12Ki ± 0%   16.85Ki ± 0%  -1.63% (p=0.000 n=10)
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14   17.28Ki ± 0%   16.85Ki ± 0%  -2.51% (p=0.000 n=10)
StatefulSetCompatibility/1.33_set,_1.33_rev-14                       16.84Ki ± 0%
geomean                                               17.20Ki        16.84Ki       -2.07%

                                                    │  1.34.txt  │              fix.txt              │
                                                    │ allocs/op  │ allocs/op   vs base               │
StatefulSetCompatibility/1.34_set,_1.34_rev-14        336.0 ± 0%   326.0 ± 0%  -2.98% (p=0.000 n=10)
StatefulSetCompatibility/1.34_set,_1.33+1.34_rev-14   342.0 ± 0%   326.0 ± 0%  -4.68% (p=0.000 n=10)
StatefulSetCompatibility/1.33_set,_1.33_rev-14                     325.0 ± 0%
geomean                                               339.0        325.7       -3.83%
```

#### Does this PR introduce a user-facing change?
```release-note
kube-controller-manager: Fixes a 1.34 regression, which triggered a spurious rollout of existing statefulsets when upgrading the control plane from 1.33 → 1.34. This fix is guarded by a `StatefulSetSemanticRevisionComparison` feature gate, which is enabled by default.
```

/sig apps

### CODE REVIEW

**Comment by liggitt** [comment]
/retest
/hold cancel

This is ready for review

**Comment by liggitt** [comment]
/assign @soltysh @janetkuo 
for sig-apps-approvers

File: pkg/features/kube_features.go [hunk 1]
```diff
@@ -1140,6 +1146,12 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 		{Version: version.MustParse("1.33"), Default: false, PreRelease: featuregate.Alpha},
 	},
 
+	StatefulSetSemanticRevisionComparison: {
+		// This is a mitigation for a 1.34 regression due to serialization differences that cannot be feature-gated,
+		// so this mitigation should not auto-disable even if emulating versions prior to 1.34 with --emulation-version.
```
Comment (BenTheElder) [inline pkg/features/kube_features.go]: Is this the first time we've done that? 

Completely non-blocking to this PR, this part feels like something we should generalize (at least document the pattern somewhere?)

Comment (liggitt) [reply pkg/features/kube_features.go]: I... think so? cc @Jefftree @siyuanfoundation @jpbetz for visibility to an edge with emulation-version and gates around things that are inherent to the binary version

Comment (Jefftree) [reply pkg/features/kube_features.go]: Is this intended to be backported to previous versions? If so there should be no problems, we have prior art with OrderedNamespaceDeletion https://github.com/kubernetes/kubernetes/pull/130507. You could mark the introduced version as the earliest version that contains the backport.  If not, what is the desired behavior when emulating previous versions?

Comment (liggitt) [reply pkg/features/kube_features.go]: > If not, what is the desired behavior when emulating previous versions?

This will only be backported to 1.34.

We want this mitigation to default to being enabled in all the same configurations that had the spurious rollout bug, which is dependent only on the binary version, not the emulation version.

Comment (siyuanfoundation) [reply pkg/features/kube_features.go]: since [Omit null creationTimestamp](https://github.com/kubernetes/kubernetes/pull/130989/files#top) is not feature gated, it makes sense to not attach a version to this mitigation ( it needs to be on even if we are emulating 1.32)

Comment (Jefftree) [reply pkg/features/kube_features.go]: ack. LGTM

I think one of our emulated version checks will fail though, would it make sense to backport the feature gate as a noop so we don't have inconsistencies in the feature gate check? Alternative we can just special case and ignore this feature gate for our emulated version test cases (which seems like the more convenient option).

Comment (liggitt) [reply pkg/features/kube_features.go]: we plan to backport the entire PR to 1.34 ... what test are you envisioning will fail?

Comment (Jefftree) [reply pkg/features/kube_features.go]: We have a periodic test that checks that the same set of default feature gate enablements is present on something like (bv=1.33, ev=1.33) and (bv=1.35, ev=1.33). https://testgrid.k8s.io/sig-api-machinery-emulated-version#compatibility-versions-feature-gate-test

This will fail but it shouldn't affect the backport and we can fix it on our side in test-infra.

**Review by janetkuo — APPROVED** [review]
/lgtm

Thanks for the fix!

File: pkg/features/kube_features.go (hunk 1 above)
Comment (BenTheElder) [reply pkg/features/kube_features.go]: was fixed in https://github.com/kubernetes/test-infra/pull/35880
