### PR TITLE
Don't filter items when resources requested by name

### LINKED ISSUE #41150: kubectl get pod <pod_name> should return the pod even if if it's terminated
**What happened**:

Pod `foo` failed. I want to inspect the status of the pod, but getting the pod directly returns nothing.
```console
$ kubectl get pod foo
$
```
Adding the `--show-all` (`-a`) option shows the pod.
```console
$ kubectl get pod foo -a
NAME      READY     STATUS    RESTARTS   AGE
foo       0/1       Error     0          12m
```

**What you expected to happen**:

I understand by default `get pod` only shows non-terminated resources, but since I specified the pod name explicitly, I'd expect to get the pod regardless of its state.

### PR DESCRIPTION
**Pull request by smarterclayton**
Add tracking on resource.Builder if a "named" item is requested (from
file, stream, url, or resource args) and use that in `get` to accurately
determine whether to filter resources. Add tests.

Fixes #41150, #40492

```release-note
Completed pods should not be hidden when requested by name via `kubectl get`.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-pr-reviews

File: pkg/kubectl/resource/builder.go [hunk 1]
```diff
@@ -567,25 +567,34 @@ func (b *Builder) visitorResult() *Result {
 }
 
 func (b *Builder) visitBySelector() *Result {
+	result := &Result{
+		targetsSingleItems: false,
+	}
+
 	if len(b.names) != 0 {
-		return &Result{err: fmt.Errorf("name cannot be provided when a selector is specified")}
+		result.err = fmt.Errorf("name cannot be provided when a selector is specified")
```
Comment (deads2k) [inline pkg/kubectl/resource/builder.go]: if names were specified, you know it targeted single items.

File: pkg/kubectl/resource/builder.go [hunk 2]
```diff
@@ -567,25 +567,34 @@ func (b *Builder) visitorResult() *Result {
...
+		return result
 	}
 	if len(b.resourceTuples) != 0 {
-		return &Result{err: fmt.Errorf("selectors and the all flag cannot be used when passing resource/name arguments")}
+		result.err = fmt.Errorf("selectors and the all flag cannot be used when passing resource/name arguments")
```
Comment (deads2k) [inline pkg/kubectl/resource/builder.go]: if names were specified, you know it targeted single items.

File: pkg/kubectl/resource/builder.go [hunk 3]
```diff
@@ -567,25 +567,34 @@ func (b *Builder) visitorResult() *Result {
 }
 
 func (b *Builder) visitBySelector() *Result {
+	result := &Result{
```
Comment (deads2k) [inline pkg/kubectl/resource/builder.go]: I don't think this change made the method more readable.

File: pkg/kubectl/resource/builder.go [hunk 4]
```diff
@@ -607,14 +619,21 @@ func (b *Builder) visitByResource() *Result {
 		isSingleItemImplied = len(b.resourceTuples) == 1
 	}
 
+	result := &Result{
+		singleItemImplied:  isSingleItemImplied,
+		targetsSingleItems: true,
```
Comment (deads2k) [inline pkg/kubectl/resource/builder.go]: This never mutates.  Again, I find the value questionable in a method this size.

File: pkg/kubectl/resource/builder.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/kubectl/resource/builder.go]: I don't want every exit to declare the whole struct though.  I think that's not a consistent pattern.

File: pkg/kubectl/resource/builder.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/kubectl/resource/builder.go]: I'm not sure what you're arguing for.  I don't want each line to have 40 characters that are exactly the same that someone will cut and paste incorrectly.

File: pkg/kubectl/cmd/get.go [hunk 5]
```diff
@@ -308,7 +306,9 @@ func RunGet(f cmdutil.Factory, out, errOut io.Writer, cmd *cobra.Command, args [
 	if err != nil {
 		return err
 	}
-
+	if r.TargetsSingleItems() {
```
Comment (deads2k) [inline pkg/kubectl/cmd/get.go]: If I'm reading correctly, doesn't this remove the filter if I run `kubectl get svc/foo pods`?

File: pkg/kubectl/resource/builder.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/kubectl/resource/builder.go]: These methods are expected to be single path invocations with err dominating the return (an error short circuits).  Callers are expected to handle error first, rather than later.  So not altering the target state with an error is just another form of short-circuit (which is how single item implied worked today).

File: pkg/kubectl/cmd/get.go (hunk 5 above)
Comment (smarterclayton) [inline pkg/kubectl/cmd/get.go]: It does, but that's not allowed.

**Comment by deads2k** [comment]
> It does, but that's not allowed.

Didn't see that coming. Alright, this lgtm.

File: pkg/kubectl/resource/builder.go (hunk 4 above)
Comment (deads2k) [inline pkg/kubectl/resource/builder.go]: > I'm not sure what you're arguing for. I don't want each line to have 40 characters that are exactly the same that someone will cut and paste incorrectly.

I'd prefer a `.with` construct, but I won't stick on it.  There already be dragons here.

**Comment by smarterclayton** [comment]
Added a fluent style call for error at david's request, tagging.

**Comment by smarterclayton** [comment]
@k8s-bot unit test this
@k8s-bot gci gce e2e test this
