### PR TITLE
kubeadm: Allows to specify custom flag values for control plane components

### LINKED ISSUE #58072: Kubeadm: customize control plane flags on init
/kind feature

**What happened**:

When calling `kubeadm init`, there is no way to override default flag values for the different components of the controlplane. This is surprising, as in the config structure (and in controlplane phase codebase itself), there are explicit settings for doing that (APIServerExtraArgs, ControllerManagerExtraArgs, SchedulerExtraArgs).

**What you expected to happen**:

Those config fields should be exposed as flags on `kubeadm init` and `kubeadm phase controlplane`

**How to reproduce it (as minimally and precisely as possible)**:

Try to deploy K8s using Kubeadm with a custom Admission Control setting

(I'll follow up on this issue with a PR)

### PR DESCRIPTION
**Pull request by simonferquel**
This makes it possible to override / add flag values to the k8s api server, controller manager and scheduler components on `kubeadm init` and `kubeadm alpha controlplane <component>`

**What this PR does / why we need it**:
This PR makes kubeadm a little more flexible by allowing to specify flag values (or override kubeadm defaults) for the control plane components.
One good example is to deploy Kubernetes with a different admission-control flag on API server

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58072

**Special notes for your reviewer**:
Not sure about what should be fixed. The PR merely adds flags to the CLI exposing existing functionality (which I suppose is already tested)

**Release note**:
```release-note
kubeadm now accept `--apiserver-extra-args`, `--controller-manager-extra-args` and `--scheduler-extra-args` to override / specify additional flags for control plane components
```

### CODE REVIEW

**Comment by simonferquel** [comment]
CLA signed

**Comment by dims** [comment]
/ok-to-test

the change looks good to me! 👍

**Comment by errordeveloper** [comment]
The build errors look a little odd, also the change looks simple enough and I don't see how it could relate to those build errors...

**Comment by simonferquel** [comment]
@errordeveloper I have added an import in init and controlplane subcommands. I think it did not get automatically added to the bazel BUILD file in cmd/kubeadm/app/phase. I submitted a corrective commit. I'll squash them if it succeeds

**Comment by errordeveloper** [comment]
> I think it did not get automatically added to the bazel BUILD file in cmd/kubeadm/app/phase

Ah, that's right! I'm still new to bazel.

**Comment by errordeveloper** [comment]
@simonferquel have you tried creating a config file actually? I sort of recollect that these flags were considered too low-level to be exposed in `kubeadm init`, hence could only be accessed via the config file...

**Comment by dims** [comment]
@simonferquel : if you run `hack/update-bazel.sh` it fixes up the bazel build files.

**Comment by errordeveloper** [comment]
> I sort of recollect that these flags were considered too low-level to be exposed in `kubeadm init`...

But I don't know if there was a discuss about exposing these in the `controlplane` phase subcommand, which seems like a good idea to me.

**Comment by simonferquel** [comment]
I am aware that the config file exposes the feature, but I thought it would be far easier if this was exposed trough init (would make our CI scripts simpler for spawning clusters with custom admission control)

**Comment by simonferquel** [comment]
@errordeveloper maybe we could define a set of flags on each control plane component that are frequently customized, and surface them instead of surfacing the whole extra-args settings. WDYT?

**Comment by errordeveloper** [comment]
@simonferquel we are gonna have a kubeadm office hours today, feel free to add this to the agenda :)

https://groups.google.com/d/msg/kubernetes-sig-cluster-lifecycle/Gh4HK-Z_oSQ/lF3dgusUBwAJ

File: cmd/kubeadm/app/cmd/phases/controlplane.go [hunk 1]
```diff
@@ -147,12 +148,16 @@ func getControlPlaneSubCommands(outDir, defaultKubernetesVersion string) []*cobr
 			cmd.Flags().StringVar(&cfg.Networking.ServiceSubnet, "service-cidr", cfg.Networking.ServiceSubnet, "The range of IP address used for service VIPs")
 			cmd.Flags().StringVar(&featureGatesString, "feature-gates", featureGatesString, "A set of key=value pairs that describe feature gates for various features. "+
 				"Options are:\n"+strings.Join(features.KnownFeatures(&features.InitFeatureGates), "\n"))
+			cmd.Flags().Var(utilflag.NewMapStringString(&cfg.APIServerExtraArgs), "apiserver-extra-args", "A set of extra flags to pass to the API Server or override default ones in form of <flagname>=<value>")
 		}
 
 		if properties.use == "all" || properties.use == "controller-manager" {
 			cmd.Flags().StringVar(&cfg.Networking.PodSubnet, "pod-network-cidr", cfg.Networking.PodSubnet, "The range of IP addresses used for the Pod network")
+			cmd.Flags().Var(utilflag.NewMapStringString(&cfg.ControllerManagerExtraArgs), "controller-manager-extra-args", "A set of extra flags to pass to the Controller Manager or override default ones in form of <flagname>=<value>")
+		}
```
Comment (dixudx) [inline cmd/kubeadm/app/cmd/phases/controlplane.go]: Add a newline here?

**Review by dixudx — COMMENTED** [review]
A small nit. Others lgtm.

**Comment by simonferquel** [comment]
Fixed @dixudx nit + squashed

**Comment by dixudx** [comment]
/lgtm

ping @luxas for approval.

File: cmd/kubeadm/app/cmd/init.go [hunk 2]
```diff
@@ -192,6 +193,10 @@ func AddInitConfigFlags(flagSet *flag.FlagSet, cfg *kubeadmapiext.MasterConfigur
 	)
 	flagSet.StringVar(featureGatesString, "feature-gates", *featureGatesString, "A set of key=value pairs that describe feature gates for various features. "+
 		"Options are:\n"+strings.Join(features.KnownFeatures(&features.InitFeatureGates), "\n"))
+
+	flagSet.Var(utilflag.NewMapStringString(&cfg.APIServerExtraArgs), "apiserver-extra-args", "A set of extra flags to pass to the API Server or override default ones in form of <flagname>=<value>")
```
Comment (timothysc) [inline cmd/kubeadm/app/cmd/init.go]: Do we need this now, could we push for component config in order to resolve this in the long-term?

Comment (errordeveloper) [reply cmd/kubeadm/app/cmd/init.go]: I also realised that this would be the best fit for component config, but in the mean time we could add this to phases command.

**Review by timothysc — COMMENTED** [review]
@dims Would this work for you for the time being?

**Review by timothysc — APPROVED** [review]
/approve

**Comment by simonferquel** [comment]
Just rebased, hoping it will fix flaky tests

**Comment by simonferquel** [comment]
@dixudx can you re-lgtm
Otherwise, if it gets merged eventually, should I create a cherry-picking PR to sub;it it for an upcoming 1.9 revision, or is there something automagic for that ?

**Comment by timothysc** [comment]
/lgtm 

This is not a PR that should be cherry-picked back to 1.9 according to policy.

**Review by timothysc — APPROVED** [review]

**Review by luxas — COMMENTED** [review]
I'm happy with this if others are, but IIRC we had frozen the UX of `kubeadm init` to not clutter things up with too many options...

I see this would be convenient and useful for users though so I'm torn.

We need a longer-term plan what to do with flags for components project-wide, and see how/if this PR fits into that model.

Thoughts?

**Comment by errordeveloper** [comment]
@luxas I 100% agree. Let's discuss.

**Comment by simonferquel** [comment]
I think this 3 flags (especially the 1 for apiserver) cover such a wide spectrum of customization (admission control, authentication customization, and runtime config, etc.) that the added value counter-balance the added complexity by large (and brings a much simpler ux than having to write a config file).

Actually I wrote this pr out of frustration as a day to day user of kubeadm :).

**Comment by luxas** [comment]
@simonferquel I totally get you. Please line it up for the next SIG meeting and discuss it there, and LMK what you all decide. I'm not gonna be able to attend sadly, but anyway...

**Comment by timothysc** [comment]
IMO these are temporary, long-term it's all configmaps.

**Comment by errordeveloper** [comment]
In which case, I'm not entierely sure about adding these to top-level
commands. I'd rather see this appear in phases for now.

**Comment by timothysc** [comment]
Per sig discussion, we should either move to phases or feature gated flag.

**Comment by luxas** [comment]
Thanks @timothysc, please open an issue to track that

**Comment by kris-nova** [comment]
I am going to be working on https://github.com/kubernetes/kubeadm/issues/676 and will follow up here as soon as I wrap my head around it 😄
