### PR TITLE
Log a warning if a ImagePullSecrets does not exist

### LINKED ISSUE #104432: imagePullSecrets should log warning if secret does not exist
#### What happened:

imagePullSecrets can added to a pod manifest to reference a secret containing registry credentials. Currently, if you add the name of a secret that does not exist, there is no warning or error. 

#### What you expected to happen:

I would expect there to be an error and a failed deployment if the secret does not exist/cannot be found in the namespace. 
If people are pulling public images, they may still wish to authenticate to a registry, for example dockerhub, before pulling the image, in order to utilise their subscription account rate limits. Currently if they use imagePullSecrets and the referenced secret does not exist, they may assume they are authenticating to their account when they are not, and will still be able to pull public images without any warning that authentication is not taking place. 

#### How to reproduce it (as minimally and precisely as possible):

Add `imagePullSecrets: myfakesecret` to a pod spec, and pull images from docker.io.

### PR DESCRIPTION
**Pull request by kaisoz**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently, if a pod references a secret containing registry credentials (in the `ImagePullSecrets` field) and the secret doesn't exist, there's no warning message. This PR addresses that problem by logging a warning event in that case.

#### Which issue(s) this PR fixes:

Fixes #104432

#### Special notes for your reviewer:

This is my first PR on Kubernetes. Thanks for the review! 😊 

#### Does this PR introduce a user-facing change?

```release-note
Added a new event `FailedToRetrieveImagePullSecret` which will be generated when a pod references an `ImagePullSecret` that doesn't exist.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```

```

### CODE REVIEW

File: pkg/kubelet/kubelet_pods_test.go [hunk 1]
```diff
@@ -3390,6 +3391,8 @@ func TestGetPortForward(t *testing.T) {
 		port         int32     = 5000
 	)
```
Comment (kannon92) [inline pkg/kubelet/kubelet_pods_test.go:3393]: Please remove.

Comment (kaisoz) [reply pkg/kubelet/kubelet_pods_test.go]: 🤦🏻 Done, thanks @kannon92

**Comment by bart0sh** [comment]
@kaisoz please [sign the CLA](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md#sign-the-cla)

**Comment by kaisoz** [comment]
> @kaisoz please [sign the CLA](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md?rgh-link-date=2023-05-11T11%3A36%3A04Z#sign-the-cla)

Thanks for your answer @bart0sh . I'm waiting for my company to sign the CLA as I'll be a corporate contributor

File: pkg/kubelet/kubelet_pods.go [hunk 2]
```diff
@@ -886,12 +887,17 @@ func (kl *Kubelet) getPullSecretsForPod(pod *v1.Pod) []v1.Secret {
...
 			klog.InfoS("Unable to retrieve pull secret, the image pull may not succeed.", "pod", klog.KObj(pod), "secret", klog.KObj(secret), "err", err)
+			failedPullSecrets = append(failedPullSecrets, secretRef.Name)
 			continue
 		}
 
 		pullSecrets = append(pullSecrets, *secret)
 	}
 
+	if len(failedPullSecrets) > 0 {
+		kl.recorder.Eventf(pod, v1.EventTypeWarning, "FailedToRetrieveImagePullSecret", "Unable to retrieve image pull secrets %s, the image pull may not succeed.", strings.Join(failedPullSecrets, ", "))
```
Comment (kannon92) [inline pkg/kubelet/kubelet_pods.go:898]: Is this message misleading?

unable to retrieve image pull secrets, image pull may not succeed?  

Is it possible for a image to succeed if you can’t retrieve this?

this is mostly a question but is there anything security related around naming of image pull secrets?

**Comment by kaisoz** [comment]
> > @kaisoz please [sign the CLA](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md?rgh-link-date=2023-05-11T11%3A39%3A31Z#sign-the-cla)
> 
> Thanks for your answer @bart0sh . I'm waiting for my company to sign the CLA as I'll be a corporate contributor

@bart0sh CLA signed 💪🏻

**Comment by sftim** [comment]
Related idea: at Pod admission time, serve a [Warning](https://kubernetes.io/blog/2020/09/03/warnings/) as part of the response, either always or only for Pods with no owner reference set.

**Comment by kannon92** [comment]
I'm mostly tagging this so I remember to mention this case.  https://github.com/kubernetes/enhancements/issues/3815

I'm working on a condition to catch issues like this.

File: pkg/kubelet/kubelet_pods.go (hunk 2 above)
Comment (seh) [inline pkg/kubelet/kubelet_pods.go:898]:
```suggestion
		kl.recorder.Eventf(pod, v1.EventTypeWarning, "FailedToRetrieveImagePullSecret", "Unable to retrieve image pull secrets %s; attempting to pull the image may not succeed.", strings.Join(failedPullSecrets, ", "))
```

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -886,12 +887,17 @@ func (kl *Kubelet) getPullSecretsForPod(pod *v1.Pod) []v1.Secret {
...
 			klog.InfoS("Unable to retrieve pull secret, the image pull may not succeed.", "pod", klog.KObj(pod), "secret", klog.KObj(secret), "err", err)
+			failedPullSecrets = append(failedPullSecrets, secretRef.Name)
 			continue
 		}
 
 		pullSecrets = append(pullSecrets, *secret)
 	}
 
+	if len(failedPullSecrets) > 0 {
+		kl.recorder.Eventf(pod, v1.EventTypeWarning, "FailedToRetrieveImagePullSecret", "Unable to retrieve image pull secrets %s; attempting to pull the image may not succeed.", strings.Join(failedPullSecrets, ", "))
```
Comment (seh) [inline pkg/kubelet/kubelet_pods.go:898]: I recognize that this message started out as a copy of the one above at line 889. It doesn't read well for the case when there's only one _Secret_ that we couldn't fetch, as the word "secrets" is still pluralized when it should not be. Rather than trying to correct that word conditionally based on the _Secret_ count, consider the following rewording:
```suggestion
		kl.recorder.Eventf(pod, v1.EventTypeWarning, "FailedToRetrieveImagePullSecret", "Unable to retrieve some image pull secrets (%s); attempting to pull the image may not succeed.", strings.Join(failedPullSecrets, ", "))
```

Comment (kaisoz) [reply pkg/kubelet/kubelet_pods.go:898]: Yeah, the message was indeed taken from the info log but I agree that this case is different since there might be more than one. Thanks @seh I'll fix it right away 😊

**Review by seh — APPROVED** [review]
Thank you for all of the updates along the way.

**Review by seh — APPROVED** [review]
Thank you for all of the updates along the way.

File: pkg/kubelet/kubelet_pods.go [hunk 4]
```diff
@@ -886,12 +887,17 @@ func (kl *Kubelet) getPullSecretsForPod(pod *v1.Pod) []v1.Secret {
...
 		if err != nil {
 			klog.InfoS("Unable to retrieve pull secret, the image pull may not succeed.", "pod", klog.KObj(pod), "secret", klog.KObj(secret), "err", err)
+			failedPullSecrets = append(failedPullSecrets, secretRef.Name)
 			continue
 		}
 
 		pullSecrets = append(pullSecrets, *secret)
 	}
 
+	if len(failedPullSecrets) > 0 {
```
Comment (kannon92) [inline pkg/kubelet/kubelet_pods.go:897]: One thing I notice is that you only display the secret name but other cases in this file also display both namespace and name.  

```
			if len(invalidKeys) > 0 {
				sort.Strings(invalidKeys)
				kl.recorder.Eventf(pod, v1.EventTypeWarning, "InvalidEnvironmentVariableNames", "Keys [%s] from the EnvFrom configMap %s/%s were skipped since they are considered invalid environment variable names.", strings.Join(invalidKeys, ", "), pod.Namespace, name)
			}
```

You could cause a confusing error message where a secret exists but not in the same namespace as the pod.

**Comment by kaisoz** [comment]
> Thank you for all of the updates along the way.

Thank you for your review @seh ! 😊

File: pkg/kubelet/kubelet_pods.go (hunk 4 above)
Comment (kaisoz) [reply pkg/kubelet/kubelet_pods.go:897]: I considered this but discarded it when I read this discussion between @SergeyKanzhelev  and @liggitt  https://github.com/kubernetes/kubernetes/pull/104535#discussion_r747254800. This PR is based on that PR, which got the `lgtm` label before it rot.

They don't think it necessary to add the namespace, because the events are already namespaced and the secrets can only be within that namespace.

Comment (kannon92) [reply pkg/kubelet/kubelet_pods.go:897]: I see.  That sounds good.  

/lgtm

**Comment by kannon92** [comment]
/assign @bart0sh

I know you have reviewed some of this area for me.  Care to take a look?

**Comment by pacoxu** [comment]
@sftim this pr added a new event, and do we have a place to describe all events? Do we have a need to create a doc for that?

**Comment by sftim** [comment]
> do we have a place to describe all events? Do we have a need to create a doc for that?

We don't have that document. There are so many events that I think we'd need to have k/k _and other repos_ export the list as an artefact, and then use a generator to produce the new doc.
Managing such a page manually doesn't feasible even with, I'd say, an extra 100% of contributor capacity.

However, it would be nice - not required - to specifically update https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ and show an example of what happens if you create a Pod that doesn't have a valid `imagePullSecrets`.

Extra credit: also edit https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/

**Comment by kaisoz** [comment]
> 



> > do we have a place to describe all events? Do we have a need to create a doc for that?
> 
> We don't have that document. There are so many events that I think we'd need to have k/k _and other repos_ export the list as an artefact, and then use a generator to produce the new doc. Managing such a page manually doesn't feasible even with, I'd say, an extra 100% of contributor capacity.
> 
> However, it would be nice - not required - to specifically update https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ and show an example of what happens if you create a Pod that doesn't have a valid `imagePullSecrets`.
> 
> Extra credit: also edit https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/

That's reasonable! I can take care of that. Should I create a new issue for this, or just with a new PR is enough ? cc @pacoxu

**Comment by sftim** [comment]
@kaisoz an issue is nice; just a PR should be fine, as the change wouldn't be controversial

**Comment by kaisoz** [comment]
> @kaisoz an issue is nice; just a PR should be fine, as the change wouldn't be controversial

ok! I'll have it ready for when this PR gets merged 👍🏻
