### PR TITLE
Don't fail if iface is being used by iSCSI session

### LINKED ISSUE #74523: iscsi plugin fails if iface already exists
**What happened**:

In order to communicate with the target, [at some point](https://github.com/bertinatto/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L688) the iscsi plugin creates a new iface. If for some reason an iface with the same name already exists in the node, this command will re-create it and no error will be reported.

However, if the iface already exists **and** is being used by a session, this command will fail and report the error code 15 ([ISCSI_ERR_SESS_EXISTS](https://linux.die.net/man/8/iscsiadm)). That's because it can't *re-create* the iface while it's in use by a session.

**What you expected to happen**:

The plugin could go ahead and use the existing iface instead of failing.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create pod1

2. Create pod2
Here, `iscsiadm` will re-use the session/iface from the step above.

3. Delete pod1
At this point, k8s will try to delete the session/iface used by pv1. However, it'll fail because the session is currently in use by pv2.

4. Create pod1
Here the pod's status will be stuck at `ContainerCreating`:
```
$ kubectl describe pod/iscsi-pod1
  Type     Reason                  Age                From                                  Message
  ----     ------                  ----               ----                                  -------
  Warning  FailedScheduling        34s (x2 over 34s)  default-scheduler                     persistentvolumeclaim "iscsi-pvc1" not found
  Warning  FailedScheduling        5s (x5 over 34s)   default-scheduler                     pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               4s                 default-scheduler                     Successfully assigned default/iscsi-pod1 to ip-172-18-3-52.ec2.internal
  Normal   SuccessfulAttachVolume  3s                 attachdetach-controller               AttachVolume.Attach succeeded for volume "iscsi-pv1"
  Warning  FailedMount             0s                 kubelet, ip-172-18-3-52.ec2.internal  MountVolume.WaitForAttach failed for volume "iscsi-pv1" : iscsi: failed to create new iface: iscsiadm: Could not create new interface 127.0.0.1:3260:iscsi-pv1.
 (exit status 15)
```

Templates used:

pod1/pod.yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: iscsi-pod1
spec:
  volumes:
- name: storage
  persistentVolumeClaim:
   claimName: iscsi-pvc1
  containers:
- name: container
  image: nginx
  ports:
- containerPort: 80
  name: "http-server"
  volumeMounts:
- mountPath: "/usr/share/nginx/html"
  name: storage
```

pod1/pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-pvc1
spec:
  accessModes:
- ReadWriteOnce
  resources:
requests:
  storage: 1Gi
  volumeName: "iscsi-pv1"
  storageClassName: ""
```

pod1/pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv1
spec:
  capacity:
storage: 1Gi
  accessModes:
- ReadWriteOnce
  iscsi:
  targetPortal: 172.18.0.44:3260
  portals:
  iqn: iqn.2003-01.io.k8s:e2e.27924
  lun: 0
  fsType: ext4
  initiatorName: "iqn.1994-05.com.redhat:dfa42debbbf"

```

pod2/pod.yaml
```
kind: Pod
apiVersion: v1
metadata:
  name: iscsi-pod2
spec:
  volumes:
- name: storage
  persistentVolumeClaim:
   claimName: iscsi-pvc2
  containers:
- name: container
  image: nginx
  ports:
- containerPort: 80
  name: "http-server"
  volumeMounts:
- mountPath: "/usr/share/nginx/html"
  name: storage
```

pod2/pvc.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-pvc2
spec:
  accessModes:
- ReadWriteOnce
  resources:
requests:
  storage: 1Gi
  volumeName: "iscsi-pv2"
  storageClassName: ""
```

pod2/pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv2
spec:
  capacity:
storage: 1Gi
  accessModes:
- ReadWriteOnce
  iscsi:
  targetPortal: 172.18.0.44:3260
  portals:
  iqn: iqn.2003-01.io.k8s:e2e.27924
  lun: 1
  fsType: ext4
  initiatorName: "iqn.1994-05.com.redhat:dfa42debbbf"
```

**Anything else we need to know?**:

1. This problem happens when a custom initiator is used, and it was reported to me that it's necessary in some set-ups in order to "restrict access to LUNs of the storage".

2. How to reproduce manually (assuming there's a session using the iface):

```
$ sudo iscsiadm -m session -P 1
Target: iqn.2003-01.io.k8s:e2e.8154 (non-flash)
        Current Portal: 127.0.0.1:3260,1
        Persistent Portal: 127.0.0.1:3260,1
                **********
                Interface:
                **********
                Iface Name: 127.0.0.1:3260:iscsi-pv1
                Iface Transport: tcp
                Iface Initiatorname: iqn.1994-05.com.redhat:dfa42debbbf
                Iface IPaddress: 127.0.0.1
                Iface HWaddress: <empty>
                Iface Netdev: <empty>
                SID: 2
                iSCSI Connection State: LOGGED IN
                iSCSI Session State: LOGGED_IN
                Internal iscsid Session State: NO CHANGE

$ sudo iscsiadm -m iface -I 127.0.0.1:3260:iscsi-pv1 -o new 
iscsiadm: Could not create new interface 127.0.0.1:3260:iscsi-pv1.

$ echo $?
15

$ sudo iscsiadm -m iface -P 1
Iface: default
Iface: iser
Iface: 127.0.0.1:3260:iscsi-pv1
        Target: iqn.2003-01.io.k8s:e2e.8154
                Portal: 127.0.0.1:3260,1

sudo iscsiadm -m node -p 127.0.0.1:3260 -u                                                                                                                                                               
Logging out of session [sid: 2, target: iqn.2003-01.io.k8s:e2e.8154, portal: 127.0.0.1,3260]
Logout of [sid: 2, target: iqn.2003-01.io.k8s:e2e.8154, portal: 127.0.0.1,3260] successful.

$ sudo iscsiadm -m session -P 1                                                                                                                                                                            
iscsiadm: No active sessions.

$ sudo iscsiadm -m iface -P 1                                                                                                                                                                              
Iface: default
Iface: iser
Iface: 127.0.0.1:3260:iscsi-pv1
        Target: iqn.2003-01.io.k8s:e2e.8154
                Portal: 127.0.0.1:3260,1

$ sudo iscsiadm -m iface -I 127.0.0.1:3260:iscsi-pv1 -o new                                                                                                                                                
New interface 127.0.0.1:3260:iscsi-pv1 added
```

/sig storage
/CC @jsafrane, @CristianPop, @bswartz, @rootfs

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR prevents k8s failing to create a PV if an iscsi iface already exists and is being used by a session.

**Which issue(s) this PR fixes**:

Fixes #74523.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @bswartz

@bertinatto, did you test it with containerized kubelet? I hope that exit codes are not lost somewhere there.

File: pkg/volume/iscsi/iscsi_util.go [hunk 1]
```diff
@@ -51,6 +52,9 @@ const (
 
 	// How many seconds to wait for a multipath device if at least two paths are available.
 	multipathDeviceTimeout = 10
+
+	// 'iscsiadm' error code stating that a session is logged in
+	iscsiadmErrorSessExists = 15
```
Comment (redbaron) [inline pkg/volume/iscsi/iscsi_util.go]: For reviewers, iscsiadm use code per error:

https://github.com/open-iscsi/open-iscsi/blob/7d121d12ad6ba7783308c25ffd338a9fa0cc402b/include/iscsi_err.h#L37-L38

**Comment by jsafrane** [comment]
I check containerized kubelet code and we execute iscsiadm in the container with kubelet, so kubelet gets authentic iscsiadm exit code, without any nsenter translation.

**Comment by jsafrane** [comment]
So code-wise lgtm from me, anyone from iscsi side has has opinion?

File: pkg/volume/iscsi/iscsi_util.go [hunk 2]
```diff
@@ -872,8 +876,14 @@ func cloneIface(b iscsiDiskMounter, newIface string) error {
 	// create new iface
 	out, err = b.exec.Run("iscsiadm", "-m", "iface", "-I", newIface, "-o", "new")
 	if err != nil {
-		lastErr = fmt.Errorf("iscsi: failed to create new iface: %s (%v)", string(out), err)
-		return lastErr
+		if exit, ok := err.(utilexec.ExitError); ok {
+			if exit.ExitStatus() == iscsiadmErrorSessExists {
+				klog.Infof("iscsi: there is a session is logged in with iface %s", newIface)
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: nit: `there is a session already logged in with iface`

File: pkg/volume/iscsi/iscsi_util.go (hunk 1 above)
Comment (rootfs) [reply pkg/volume/iscsi/iscsi_util.go]: thanks @redbaron 
@bertinatto please add this reference in your comment

File: pkg/volume/iscsi/iscsi_util.go [hunk 3]
```diff
@@ -872,8 +877,14 @@ func cloneIface(b iscsiDiskMounter, newIface string) error {
 	// create new iface
 	out, err = b.exec.Run("iscsiadm", "-m", "iface", "-I", newIface, "-o", "new")
 	if err != nil {
-		lastErr = fmt.Errorf("iscsi: failed to create new iface: %s (%v)", string(out), err)
-		return lastErr
+		if exit, ok := err.(utilexec.ExitError); ok {
+			if exit.ExitStatus() == iscsiadmErrorSessExists {
+				klog.Infof("iscsi: there is a session already logged in with iface %s", newIface)
+			}
```
Comment (bswartz) [inline pkg/volume/iscsi/iscsi_util.go]: If the case to ExitError succeeds, but the error code doesn't match, this won't return an error like it should.

File: pkg/volume/iscsi/iscsi_util.go [hunk 4]
```diff
@@ -27,13 +27,14 @@ import (
 	"strings"
 	"time"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (bswartz) [inline pkg/volume/iscsi/iscsi_util.go]: Why this change?

**Review by bswartz — CHANGES_REQUESTED** [review]

File: pkg/volume/iscsi/iscsi_util.go (hunk 3 above)
Comment (bertinatto) [reply pkg/volume/iscsi/iscsi_util.go]: Fixed.

File: pkg/volume/iscsi/iscsi_util.go (hunk 4 above)
Comment (bertinatto) [reply pkg/volume/iscsi/iscsi_util.go]: `goreturns` added this one. Removed it.

**Review by bswartz — APPROVED** [review]
