### PR TITLE
fix Azure Container Registry anonymous repo image pull error

### LINKED ISSUE #74714: cannot access Azure Container Registry public repo
**What happened**:
Currently we cannot pull image from Azure Container Registry repo which provides anonymous pull access since when do image pull, it will always use service pincipal for * .azurecr. *

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Currently we cannot pull image from ACR repo which provides anonymous image pull access since when do image pull, it will always use service principal for all ACR repos, and finally image pull will fail with error authentication.

This PR fix this issue by allowing * .azurecr. * with two secrets, 1. service principal 2. empty username/password, as I have tested in both acr private and public repos, it works well.

**Which issue(s) this PR fixes**:

Fixes #74714

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix Azure Container Registry anonymous repo image pull error
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
Let's hold for a moment, let ACR team review this code first, e.g. empty username/password means anonymous authentication.

File: pkg/credentialprovider/azure/azure_credentials.go [hunk 1]
```diff
@@ -206,6 +206,13 @@ func (a *acrProvider) Provide() credentialprovider.DockerConfig {
 			cfg[url] = *cred
 		}
 	}
+
+	// add ACR anonymous repo support: use empty username and password for anonymous access
+	cfg["*.azurecr.*"] = credentialprovider.DockerConfigEntry{
```
Comment (sivagms) [inline pkg/credentialprovider/azure/azure_credentials.go]: What all does this match? does this match "foo.azurecr.bar.com" ?

Comment (yuwaMSFT2) [inline pkg/credentialprovider/azure/azure_credentials.go]: What's the order of trying the matching? Will it always first try the empty user name one, or always the SP one? 
Which is most likely usage here? I mean depending on the usage, you may want to optimize for the most common scenario.

Comment (andyzhangx) [reply pkg/credentialprovider/azure/azure_credentials.go]: @sivagms Yes, it match, but I think it does not matter since if user use private repo, suppose they should provide pull image secret by themselves.

Comment (andyzhangx) [reply pkg/credentialprovider/azure/azure_credentials.go]: @yuwaMSFT2 good question, now it's this order: "*.azurecr.io", "*.azurecr.*", which means use SP first, and then empty username/password, SP first should be the better choice in a long period.

**Comment by andyzhangx** [comment]
/hold cancel
@yuwaMSFT2 @sivagms Let me know if you have any question, to make sure it works on AKS, I tested again. The error message is without this PR, and after this PR, you could see it works well:
```
 Type     Reason          Age                  From                               Message
  ----     ------          ----                 ----                               -------
  Normal   Scheduled       10m                  default-scheduler                  Successfully assigned default/apache to k8s-agentpool-34398540-1
  Normal   Pulling         10m (x3 over 10m)    kubelet, k8s-agentpool-34398540-1  pulling image "xxx.azurecr.io/bitnami/apache:2.4.38"
  Warning  Failed          10m (x3 over 10m)    kubelet, k8s-agentpool-34398540-1  Failed to pull image "xxx.azurecr.io/bitnami/apache:2.4.38": rpc error: code = Unknown desc = Error response from daemon: Get https://xxx.azurecr.io/v2/bitnami/apache/manifests/2.4.38: unauthorized: authentication required
  Warning  Failed          10m (x3 over 10m)    kubelet, k8s-agentpool-34398540-1  Error: ErrImagePull
  Normal   BackOff         9m28s (x3 over 10m)  kubelet, k8s-agentpool-34398540-1  Back-off pulling image "xxx.azurecr.io/bitnami/apache:2.4.38"
  Warning  Failed          9m28s (x3 over 10m)  kubelet, k8s-agentpool-34398540-1  Error: ImagePullBackOff
  Normal   SandboxChanged  9m27s (x7 over 10m)  kubelet, k8s-agentpool-34398540-1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         9m17s                kubelet, k8s-agentpool-34398540-1  Pulling image "marketplace.azurecr.io/bitnami/apache:2.4.38"
  Normal   Pulled          9m1s                 kubelet, k8s-agentpool-34398540-1  Successfully pulled image "marketplace.azurecr.io/bitnami/apache:2.4.38"
  Normal   Created         8m58s                kubelet, k8s-agentpool-34398540-1  Created container apache
  Normal   Started         8m58s                kubelet, k8s-agentpool-34398540-1  Started container apache
```

**Review by yuwaMSFT2 — APPROVED** [review]

**Review by feiskyer — COMMENTED** [review]
/lgtm

File: pkg/credentialprovider/azure/azure_credentials.go (hunk 1 above)
Comment (sivagms) [reply pkg/credentialprovider/azure/azure_credentials.go]: That’s a bit scary. Some malicious user can just change the registry name in the chart to receive the AKS SP and password

Comment (andyzhangx) [reply pkg/credentialprovider/azure/azure_credentials.go]: currently the matching patterns are like following:
( *. azurecr.io, SP) ( *. azurecr.cn, SP)  ( * . azurecr .* , empty password)
Per offline discussion, it's safe
Thanks for the good point!
