### PR TITLE
Handle empty perferredVersion

### LINKED ISSUE #23799: GroupVersion not present in src
I have been having the kube-controller-manager (running in a container) crash quite frequently with this error:

```
F0403 14:47:52.372732       1 controllermanager.go:277] Failed to get supported resources from server: converting (unversioned.APIGroupList) to (unversioned.APIResourceList): GroupVersion not present in src
```

I cant fathom what seems to cause it. It seems to happen consistently for a while (CrashLoopBackoff occurs) and then fixes itself after an undetermined amount of time.

Kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```

Docker version:

```
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64
OS Version: Ubuntu 16.04
```

Networking: Calico (with the calico k8s policy agent)

Please do let me know if there is any other information that I can supply. I appreciate I haven't given much to go off of. I am not sure what the steps to reproduce are...

### PR DESCRIPTION
**Pull request by caesarxuchao**
fix #23799 

@microadam @lavalamp @nikhiljindal

### CODE REVIEW

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 1]
```diff
@@ -461,6 +461,13 @@ func ServerPreferredNamespacedGroupVersionResources(discoveryClient discovery.Di
 	}
 	for _, apiGroup := range serverGroupList.Groups {
 		preferredVersion := apiGroup.PreferredVersion
```
Comment (lavalamp) [inline pkg/controller/namespace/namespace_controller_utils.go]: I'd prefer for you to make a "GetPreferredVersion" function somewhere for reuse.

Comment (caesarxuchao) [inline pkg/controller/namespace/namespace_controller_utils.go]: Done, extracted to a function in the discovery package. PTAL, thank you.

**Comment by lavalamp** [comment]
LGTM. Please send a separate PR to fix the server.

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this, issue #14968

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 2]
```diff
@@ -460,7 +460,10 @@ func ServerPreferredNamespacedGroupVersionResources(discoveryClient discovery.Di
 		return results, err
 	}
 	for _, apiGroup := range serverGroupList.Groups {
-		preferredVersion := apiGroup.PreferredVersion
+		preferredVersion, err := discovery.GetPreferredVersion(apiGroup)
+		if err != nil {
+			return results, err
```
Comment (liggitt) [inline pkg/controller/namespace/namespace_controller_utils.go]: shouldn't this continue? otherwise we lose all information after the group that encountered an error

Comment (caesarxuchao) [inline pkg/controller/namespace/namespace_controller_utils.go]: I'll modify it to aggregate the error and continue.

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 3]
```diff
@@ -459,11 +460,18 @@ func ServerPreferredNamespacedGroupVersionResources(discoveryClient discovery.Di
 	if err != nil {
 		return results, err
 	}
+
+	allErrs := []error{}
 	for _, apiGroup := range serverGroupList.Groups {
-		preferredVersion := apiGroup.PreferredVersion
+		preferredVersion, err := discovery.GetPreferredVersion(apiGroup)
+		if err != nil {
+			allErrs = append(allErrs, err)
```
Comment (caesarxuchao) [inline pkg/controller/namespace/namespace_controller_utils.go]: @liggitt PTAL, thanks.

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 4]
```diff
@@ -459,11 +460,18 @@ func ServerPreferredNamespacedGroupVersionResources(discoveryClient discovery.Di
 	if err != nil {
 		return results, err
 	}
+
+	allErrs := []error{}
 	for _, apiGroup := range serverGroupList.Groups {
-		preferredVersion := apiGroup.PreferredVersion
```
Comment (liggitt) [inline pkg/controller/namespace/namespace_controller_utils.go]: it seems worrying that this can be empty... shouldn't we fix that instead of compensating here?

Comment (caesarxuchao) [inline pkg/controller/namespace/namespace_controller_utils.go]: #24006 is the server-side fix. But the client needs to handle the old server, thus the compensation here.

Comment (liggitt) [inline pkg/controller/namespace/namespace_controller_utils.go]: kubectl didn't have thirdparty resource support in 1.2, did it?

Comment (liggitt) [inline pkg/controller/namespace/namespace_controller_utils.go]: hmm, this is namespace controller

Comment (caesarxuchao) [inline pkg/controller/namespace/namespace_controller_utils.go]: On second thought, perhaps we don't need the compensation here, because usually people upgrade the controller manager along with the apiserver. What do you think?

Comment (liggitt) [inline pkg/controller/namespace/namespace_controller_utils.go]: if thirdpartyresources are the only type affected by this, and the version that would contain this workaround would also contain the fix on the API side to make the workaround no longer needed, I'd rather not add the workaround

**Comment by caesarxuchao** [comment]
@liggitt, I remove the workaround. PTAL. Thanks.

**Comment by liggitt** [comment]
LGTM

**Comment by caesarxuchao** [comment]
Thanks. Squashed and re-applied the label.

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this, issue #24194

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23985/kubernetes-pull-test-unit-integration/21145/

**Comment by zmerlynn** [comment]
This PR (and #23985) accidentally didn't follow the cherrypick procedure, so I didn't notice it until just now. We were literally about to cut the release when I saw a report of the PRs targeting `release-1.2` directly (I've been using the [cherrypick dashboard](http://cherrypick.k8s.io/#/queue), which this now shows up on because I marked it). Please speak now if we need to hold v1.2.3 for this.

**Comment by zmerlynn** [comment]
I'm going to go ahead and let this through, since the original bug was reported a while ago. We'll do some light testing and get this out ASAP.
