### PR TITLE
Fix HPA feedback from writing status.replicas to spec.replicas.

### LINKED ISSUE #72775: pod hpa would create extra pods during deployment rolling update when there is no load at all during the rolling upgrade
**What happened**:
I have deployment with following upgrade strategy

>     strategy:
>       rollingUpdate:
>         maxSurge: 1
>         maxUnavailable: 0
>       type: RollingUpdate
> 

and hpa:

>  spec:
>     maxReplicas: 3
>     minReplicas: 1
>     scaleTargetRef:
>       apiVersion: extensions/v1beta1
>       kind: Deployment
>       name: xxxx
>     targetCPUUtilizationPercentage: 80

When sending patch command to update container image, (current replicas is 1),  following happended
1. new pod created and getting ready
2. after the new pod ready, the old pod is terminating.
3. hpa make a judgement call to set desired replica to 2
4. after a while, hpa readjust to desired replica back to 1

**What you expected to happen**:
1. new pod created and getting ready
2. after the new pod ready, the old pod is terminating.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a deployment with replica set to 1, maxSurge 1, maxUnavailable: 0
2. create a hpa targeting the deployment with replica 1 from 3, 80% cpu target
3. change container image via kubectl edit or other approach
4. keep checking pod count changes

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #78712: HPA scales up with no reason / blank reason
**What happened**:
HPA scales up a deployment without a reason.

```
Events:
  Type     Reason             Age                   From                       Message
  ----     ------             ----                  ----                       -------
  Normal   SuccessfulRescale  57m (x3 over 3d9h)    horizontal-pod-autoscaler  New size: 250; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale  43m (x3 over 30h)     horizontal-pod-autoscaler  New size: 313; reason:
  Normal   SuccessfulRescale  42m                   horizontal-pod-autoscaler  New size: 391; reason:
  Normal   SuccessfulRescale  42m                   horizontal-pod-autoscaler  New size: 481; reason:
  Normal   SuccessfulRescale  41m                   horizontal-pod-autoscaler  New size: 518; reason:
  Normal   SuccessfulRescale  36m (x2 over 6d3h)    horizontal-pod-autoscaler  New size: 288; reason: All metrics below target
  Normal   SuccessfulRescale  32m                   horizontal-pod-autoscaler  New size: 284; reason: All metrics below target
  Normal   SuccessfulRescale  31m (x4 over 6d2h)    horizontal-pod-autoscaler  New size: 230; reason: All metrics below target
  Normal   SuccessfulRescale  25m                   horizontal-pod-autoscaler  New size: 230; reason:
  Normal   SuccessfulRescale  24m                   horizontal-pod-autoscaler  New size: 288; reason:
  Warning  FailedRescale      15m (x2 over 15m)     horizontal-pod-autoscaler  New size: 457; reason: ; error: Operation cannot be fulfilled on deployments.apps "prod": the object has been modified; please apply your changes to the latest version and try again
  Normal   SuccessfulRescale  51s (x123 over 6d5h)  horizontal-pod-autoscaler  (combined from similar events): New size: 218; reason: All metrics below target
```

**What you expected to happen**:
There should always be a reason for a scale up or scale down.

**How to reproduce it (as minimally and precisely as possible)**:
Not exactly sure. But we did notice this behavior during a rolling update.

Here's what the deployment strategy looks like:
```
...
strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 5%
    type: RollingUpdate
...
```

And the hpa:
```
...
spec:
  maxReplicas: 3000
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod
  targetCPUUtilizationPercentage: 20
...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Metrics server: 0.3.2 or 0.3.3
- Cloud provider or hardware configuration: AWS m4.10xlarge
- OS (e.g: `cat /etc/os-release`): CoreOS 2079.4.0
- Kernel (e.g. `uname -a`): 4.19.43

### LINKED ISSUE #78761: HPA doesn't scale down to minReplicas even though metric is under target
**What happened**:

HPA scales to `Spec.MaxReplicas` even though metric is always under target.

Here's the HPA in YAML:

```yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"ReadyForNewScale","message":"recommended
      size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2019-06-06T10:46:13Z","reason":"TooManyReplicas","message":"the
      desired replica count is more than the maximum replica count"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"9m"}}]'
  creationTimestamp: "2019-06-06T10:45:58Z"
  name: my-app-1
  namespace: default
  resourceVersion: "55041251"
  selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/my-app-1
  uid: 44fedc1a-8848-11e9-8465-025acf90d81e
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-app-1
  targetCPUUtilizationPercentage: 40
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 4
  desiredReplicas: 4
```

And here's a description output:

```
$ kubectl describe hpa my-app-1
  Name:                                                  my-app-1
  Namespace:                                             default
  Labels:                                                <none>
  Annotations:                                           <none>
  CreationTimestamp:                                     Thu, 06 Jun 2019 12:45:58 +0200
  Reference:                                             Deployment/my-app-1
  Metrics:                                               ( current / target )
    resource cpu on pods  (as a percentage of request):  0% (9m) / 40%
  Min replicas:                                          2
  Max replicas:                                          4
  Deployment pods:                                       4 current / 4 desired
  Conditions:
    Type            Status  Reason            Message
    ----            ------  ------            -------
    AbleToScale     True    ReadyForNewScale  recommended size matches current size
    ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
    ScalingLimited  True    TooManyReplicas   the desired replica count is more than the maximum replica count
  Events:           <none>
```

**What you expected to happen**:

HPA only scales up when metric is above target and scales down when under until `Spec.MinReplicas` is reached.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure. We have 9 HPAs and only one has this problem. I can't see anything unique about this HPA when comparing to the others. If I delete and recreate the HPA using Helm, same problem. Also if I recreate the HPA using `kubectl autoscale Deployment/my-app-1 --min=2 --max=4 --cpu-percent=40` same problem.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.12.6-eks-d69f1b`
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): EKS AMI release `v20190327`
- Kernel (e.g. `uname -a`): `4.14.104-95.84.amzn2.x86_64`
- Network plugin and version (if this is a network-related bug): AWS CNI
- Metrics-server version: `0.3.2`

### PR DESCRIPTION
**Pull request by josephburnett**
> /kind bug

**What this PR does / why we need it**:

There are various reasons that the HPA will decide not the change the current scale.  Two important ones are when missing metrics might change the direction of scaling, and when the recommended scale is within tolerance of the current scale.

The way that `ReplicaCalculator` signals it's desire to not change the current scale is by returning the current scale.  However the current scale is from `scale.Status.Replicas` and can be larger than `scale.Spec.Replicas` (e.g. during Deployment rollout with configured surge).  This causes a positive feedback loop because `scale.Status.Replicas` is written back into `scale.Spec.Replicas`, further increasing the current scale.

This PR fixes the feedback loop by plumbing the replica count from spec through `horizontal.go` and `replica_calculator.go` so the calculator can punt with the right value.

It also introduces separate types for replica counts derived from `scale.Spec` and `scale.Status` (`specReplicas` and `statusReplicas` respectively) to guard against this kind of cross-talk.  When returning a desired scale to be written into spec, the calculator must either return the given, current scale, or explicitly call `newSpecReplicas`.

With separate types, other sources of cross-talk became compiler errors.  E.g. [recording Status.Replicas as an initial recommendation](https://github.com/kubernetes/kubernetes/blob/cb862e332329736dc1b893da6f757b808fa802aa/pkg/controller/podautoscaler/horizontal.go#L573-L574).  This would manifest if a deployment was in the process of rolling out when the HPA reboots.

**Which issue(s) this PR fixes**:

Fixes #78712
Fixes #72775

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by josephburnett** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

New comment.

**Comment by josephburnett** [comment]
> If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.

Done.

**Comment by josephburnett** [comment]
[/batman](https://www.youtube.com/watch?v=44-RsrF_V_w)

**Comment by soggiest** [comment]
@kubernetes/sig-autoscaling-pr-reviews Can someone take a look at this
@claurence Do you think this can still make it into the release of should we punt?

**Comment by josephburnett** [comment]
@krzysztof-jastrzebski could you also take a look, since you dug into this a little bit.  Did I address all the defects which you noticed?  Thanks!

Once this lands, I will want to patch it into all the recent major versions.

File: pkg/controller/podautoscaler/horizontal.go [hunk 1]
```diff
@@ -229,13 +229,28 @@ func (a *HorizontalController) processNextWorkItem() bool {
 	return true
 }
 
+// Types to help keep status and spec separate and avoid a positive
+// feedback loop.  Generally, nothing from status should go back into
+// spec.
+type specReplicas int32
```
Comment (mwielgus) [inline pkg/controller/podautoscaler/horizontal.go]: Where does specReplicas go? To Deployment/RS specification (scale subresource)?

**Review by mwielgus — CHANGES_REQUESTED** [review]
In multiple places in the code you pass statusReplicas as a function argument but you make no use of it. They are not needed by any interface or so. At least for me, it is confusing why would you need to ever pass statusReplicas to a function that gets a metrics. 
Please remove these parameters.

File: pkg/controller/podautoscaler/horizontal.go (hunk 1 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal.go]: specReplicas goes to the scale subresource (spec).

Re: statusReplicas, I removed it from all the places it wasn't needed.  I tried a few different approaches to fixing this problem and that plumbing was just a leftover.

File: pkg/controller/podautoscaler/horizontal.go [hunk 2]
```diff
@@ -229,13 +229,27 @@ func (a *HorizontalController) processNextWorkItem() bool {
...
+
 // computeReplicasForMetrics computes the desired number of replicas for the metric specifications listed in the HPA,
 // returning the maximum of the computed replica counts, a description of the associated metric, and the statuses of
 // all metrics computed.
 func (a *HorizontalController) computeReplicasForMetrics(hpa *autoscalingv2.HorizontalPodAutoscaler, scale *autoscalingv1.Scale,
-	metricSpecs []autoscalingv2.MetricSpec) (replicas int32, metric string, statuses []autoscalingv2.MetricStatus, timestamp time.Time, err error) {
+	metricSpecs []autoscalingv2.MetricSpec) (replicas specReplicas, metric string, statuses []autoscalingv2.MetricStatus, timestamp time.Time, err error) {
 
-	currentReplicas := scale.Status.Replicas
+	specReplicas := specReplicas(scale.Spec.Replicas)
```
Comment (mwielgus) [inline pkg/controller/podautoscaler/horizontal.go]: What implication does this change has?

File: pkg/controller/podautoscaler/replica_calculator_test.go [hunk 3]
```diff
@@ -972,8 +1066,30 @@ func TestReplicaCalcToleranceCMObject(t *testing.T) {
...
+			},
+		},
+	}
+	tc.runTest(t)
+}
+
+func TestReplicaCalcTolerancePerPodCMObjectSurge(t *testing.T) {
+	tc := replicaCalcTestCase{
+		currentSpecReplicas:   4,
+		currentStatusReplicas: 8,
```
Comment (mwielgus) [inline pkg/controller/podautoscaler/replica_calculator_test.go]: What would happen if we had 0 in either spec or status (or both)?

**Comment by mwielgus** [comment]
Please describe what manual tests did you perform on this change. In particular, please confirm that you built a Kubernetes version with this PR included, deployed it, created HPA and made sure it doesn't crash.

File: pkg/controller/podautoscaler/horizontal.go (hunk 2 above)
Comment (mwielgus) [reply pkg/controller/podautoscaler/horizontal.go]: Nevermind, it's explained in the PR description :).

File: pkg/controller/podautoscaler/replica_calculator_test.go (hunk 3 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator_test.go]: These test case fields are misleading.  We don't do anything with `statusReplicas` except write it down any more.  So a zero value is uninteresting.  Likewise, `specReplicas` is either left unmodified (in which case no big deal) or set to the desired scale.  In this case, zero already has the meaning, don't scale.  So nothing will happen anyway.  We already have a unit tests for this: https://github.com/kubernetes/kubernetes/blob/9120d427dab4a69ddcf22597f81b574fb1af96bc/pkg/controller/podautoscaler/horizontal_test.go#L1633

I've renamed these as `specReplicas` and `actualPodCount`.  The actual pod count is just used by the test to setup mocks.

File: pkg/controller/podautoscaler/horizontal.go (hunk 2 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/horizontal.go]: This is the root of the bug.  Writing status back into spec.

**Comment by josephburnett** [comment]
> Please describe what manual tests did you perform on this change. In particular, please confirm that you built a Kubernetes version with this PR included, deployed it, created HPA and made sure it doesn't crash.

The PR test automation includes a least one HPA e2e test, so I did no manual testing:

image

**Comment by mwielgus** [comment]
I know that there are e2e test. AFAIR I wrote some of them ;). The thing is that we are well in the code freeze and the PR is quite large. I want to be double sure that we won't have to rollback or send subsequent last minute patches or postpone the K8S release. Not everything is checked by e2e and an eye of an engineer can make a difference. Please do the build :).

**Comment by krzysztof-jastrzebski** [comment]
I think it would be easier to review if you split PR into:
1. PR adding specReplica type and all refactors.
2. PR fixing the bug.

**Comment by krzysztof-jastrzebski** [comment]
I think it would be easier to review if you split PR into:
1. PR adding specReplica type and all refactors.
2. PR fixing the bug.

**Comment by josephburnett** [comment]
> easier to review if you split PR

@krzysztof-jastrzebski yes, I think you're right.  I started with the type change and let the compiler guide me to all the places we did it wrong.  But now that I know exactly where, I could pull out a more surgical fix.

@mwielgus, ack.  I'll start working on a manual build and test.  ETA tomorrow.

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 4]
```diff
@@ -252,26 +252,26 @@ func (c *ReplicaCalculator) GetObjectMetricReplicas(currentReplicas int32, targe
...
-	replicaCount = currentReplicas
+	replicaCount = specReplicas
 	usageRatio := float64(utilization) / (float64(targetAverageUtilization) * float64(replicaCount))
 	if math.Abs(1.0-usageRatio) > c.tolerance {
 		// update number of replicas if change is large enough
-		replicaCount = int32(math.Ceil(float64(utilization) / float64(targetAverageUtilization)))
+		replicaCount = newSpecReplicas(int32(math.Ceil(float64(utilization) / float64(targetAverageUtilization))))
 	}
-	utilization = int64(math.Ceil(float64(utilization) / float64(currentReplicas)))
+	utilization = int64(math.Ceil(float64(utilization) / float64(specReplicas)))
```
Comment (gliush) [inline pkg/controller/podautoscaler/replica_calculator.go]: I'm not sure that this is a good idea.
I mean, scale.Status.Replicas and scale.Spec.Replicas might change a lot.
If I'm not mistaken these numbers might differ a lot. And in this case the utilization here ^^ will be calculated incorrectly.

**Review by gliush — CHANGES_REQUESTED** [review]

**Comment by claurence** [comment]
@josephburnett this item is tagged against 1.15 release - our release date is today - is this issue release blocking in the opinion of the SIGs impacted?  It doesn't sound like it is fixing a regression - just fixing an issue in 1.14 - can you let us know why this issue can't go in either a 1.15.x patch or 1.16?

**Comment by tpepper** [comment]
@janetkuo @kow3ns @mattfarina @prydonius looking for confirmation here ASAP whether this is 1.15 release blocking since it was added to the milestone and release is today.

**Comment by kow3ns** [comment]
@tpepper imo sig-autoscaling not sig-apps should be the decider for blocking the release. However, my personal opinion FWIW is that this is not a release blocking.

**Comment by tpepper** [comment]
@mwielgus can you confirm whether this should be treated as 1.15 release blocking or not?

**Comment by tpepper** [comment]
> @mwielgus can you confirm whether this should be treated as 1.15 release blocking or not?

From slack:
#79035 is not a release blocker. It fixes a problem that has been there for a while. It can go in the first patch release.

Once this PR merges to master, please open a [cherry-pick](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) against release-1.15 branch.

**Comment by Bubblemelon** [comment]
As discussed on https://kubernetes.slack.com/archives/C18NZM5K9/p1560793182057800 , this is not release blocking.

**Comment by gliush** [comment]
@josephburnett : I don't like the idea when replicaCalculator returns "the same replica number" at all.
I believe we should differentiate the "number of replicas" int32 and "if we should change the number of replicas" boolean.

**Comment by josephburnett** [comment]
> I believe we should differentiate the "number of replicas" int32 and "if we should change the number of replicas" boolean.

That was my first approach.  But it substantially increased the amount of refactoring necessary because most callers throw the value right into variable to return.  Adds a lot of checks.  E.g. https://github.com/kubernetes/kubernetes/blob/eaf89cfbb483f99411141f70c294e8a014e49cec/pkg/controller/podautoscaler/horizontal.go#L285-L330

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 4 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: You are correct.  I'm using the wrong denominator.  I'll plumb statusReplicas back through.

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: And my use of `replicaCount` (which is `specReplicas`) when calculating the original `usageRatio` is wrong too.  I don't think `specReplicas` should ever be in the denominator of a ratio calculation because it doesn't relate directly to the metrics and pods found.  Does that sound right?

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: @gliush I've been thinking about the per-pod object metrics use case.  And trying to make the unit tests make sense.

If I divide by `statusReplicas` then the utilization changes enough to exceed the tolerance and enter the conditional to update `replicaCount`.  However the calculation divides the object metric by the configured target, not taking replica counts into account.  So it will always come up with the `statusReplicas` (and maybe +1 because of the ceiling).  There is nothing else for it to do because adding or removing Pods will not change the object metric.

So dividing by `statusReplicas` is pointless.  In this particular case, I think dividing by `statusReplicas` is the right thing to do.

**Comment by josephburnett** [comment]
@krzysztof-jastrzebski and @mwielgus, I have reverted all the type changes to get a minimal diff for patching.  I'll submit the type safety changes as a separate pull request after.  This minimal change is the one I will test manually.

**Comment by krzysztof-jastrzebski** [comment]
You need to change also reconcileAutoscaler function as it also uses status.Replicas. 
I think we should never scale up based on:
desiredReplicas = a.normalizeDesiredReplicas(hpa, key, currentReplicas, desiredReplicas)
If someone changes number of replicas manually for a moment then HPA can store the value and scale up to it for 5 minute even if user manually scales down. This mechanism was to slow down scale down not do scale ups.
Also rescaleReason probably should be updated if 
desiredReplicas = a.normalizeDesiredReplicas(hpa, key, currentReplicas, desiredReplicas)
changes desiredReplicas.

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 4 above)
Comment (gliush) [reply pkg/controller/podautoscaler/replica_calculator.go]: >  I don't think specReplicas should ever be in the denominator of a ratio calculation because it doesn't relate directly to the metrics and pods found. 

Right.

> However the calculation divides the object metric by the configured target, not taking replica counts into account. 

It does take it into account. Let me show it:
1. `usageRatio := float64(utilization) / float64(targetUtilization)`
https://github.com/kubernetes/kubernetes/blob/b8b1720f127f9a4e6784bc652faafb256322353f/pkg/controller/podautoscaler/replica_calculator.go#L243

2. `replicaCount = int32(math.Ceil(usageRatio * float64(readyPodCount)))`
https://github.com/kubernetes/kubernetes/blob/b8b1720f127f9a4e6784bc652faafb256322353f/pkg/controller/podautoscaler/replica_calculator.go#L255

3. `return replicaCount ...`

I.e. the `utilizationRatio` is indeed calculated without the current number of pods. But the desired number of pods is calculated by multiplying the current number of pods by that `utilizationRatio`. That is where the current `statusReplicas` is used.

Another argument, more conceptual.
The idea of HPA itself is to autoscale pods under control of some metric value.
It means that we should always consider current load to be influenced (formed) by a current number of pods. And that increased number of pods will reduce the metric value.

As a result, it doesn't make sense to use the `specReplicas` in any calculation, because current state depends only on `statusReplicas`.

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 5]
```diff
@@ -259,19 +259,19 @@ func (c *ReplicaCalculator) GetObjectMetricReplicas(currentReplicas int32, targe
...
 // for the given object in the given namespace, and the current replica count.
-func (c *ReplicaCalculator) GetObjectPerPodMetricReplicas(currentReplicas int32, targetAverageUtilization int64, metricName string, namespace string, objectRef *autoscaling.CrossVersionObjectReference, metricSelector labels.Selector) (replicaCount int32, utilization int64, timestamp time.Time, err error) {
+func (c *ReplicaCalculator) GetObjectPerPodMetricReplicas(specReplicas, statusReplicas int32, targetAverageUtilization int64, metricName string, namespace string, objectRef *autoscaling.CrossVersionObjectReference, metricSelector labels.Selector) (replicaCount int32, utilization int64, timestamp time.Time, err error) {
 	utilization, timestamp, err = c.metricsClient.GetObjectMetric(metricName, namespace, objectRef, metricSelector)
 	if err != nil {
 		return 0, 0, time.Time{}, fmt.Errorf("unable to get metric %s: %v on %s %s/%s", metricName, objectRef.Kind, namespace, objectRef.Name, err)
 	}
 
-	replicaCount = currentReplicas
+	replicaCount = specReplicas
```
Comment (gliush) [inline pkg/controller/podautoscaler/replica_calculator.go]: It is not clear to me why we didn't use
```
readyPodCount, err := c.getReadyPodsCount(namespace, podSelector
```
as we do in all other functions in this file.

Comment (gliush) [reply pkg/controller/podautoscaler/replica_calculator.go]: I mean, the "currentReplicas" and "readyReplicas" may differ.

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 4 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: Your example above is a link to `GetObjectMetricReplicas` which does indeed consider pod count.  So of course we should divide by `statusReplicas` or `readyPodCount`.

https://github.com/kubernetes/kubernetes/blob/b8b1720f127f9a4e6784bc652faafb256322353f/pkg/controller/podautoscaler/replica_calculator.go#L255

However your initial comment and the interesting case here is in `GetObjectPerPodMetricReplicas`.  We don't divide by the number of pods.  Just the metric by the target.

https://github.com/kubernetes/kubernetes/blob/b8b1720f127f9a4e6784bc652faafb256322353f/pkg/controller/podautoscaler/replica_calculator.go#L272

File: pkg/controller/podautoscaler/replica_calculator.go (hunk 5 above)
Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: Yes, it looks weird.  But I think the answer is pod count doesn't matter, whether they are ready or not.

See my explanation above: https://github.com/kubernetes/kubernetes/pull/79035#discussion_r294995711

**Comment by josephburnett** [comment]
> You need to change also reconcileAutoscaler function as it also uses status.Replicas.

This is part of the larger pull request which uses types to make sure I don't do something stupid like this.  However when I stripped out the types, I accidentally reverted this fix.

https://github.com/josephburnett/kubernetes/blob/1f1461887b7de67616ab18de953bdd418472196f/pkg/controller/podautoscaler/horizontal.go#L60

and

https://github.com/josephburnett/kubernetes/blob/1f1461887b7de67616ab18de953bdd418472196f/pkg/controller/podautoscaler/horizontal.go#L588-L589

Good catch @krzysztof-jastrzebski!  I've added a commit to apply that change again.

**Comment by josephburnett** [comment]
@mwielgus I have good new and bad news.  This PR appears to indeed fix the issues with positive feedback from writing status replicas to spec replicas.  I've patched this minimal PR without additional types into GKE 1.12.9 and ran the patched controller manager in a GKE 1.12.9 cluster.  I put a deployment under load and then removed it.  It scaled up and then down as expected, so I think this PR is good-to-go.  And I can continue patching other GKE major versions with the same fix.

However, I have discovered another bug.  When a Deployment is comprised of a sufficient number of Pending unscheduled pods (e.g. due to lack of cluster capacity) we generate enough false 100% metrics to keep the utilization ratio at 1.0 or higher.  Actual utilization is 0 because load has been removed.  With an apparent change in direction due to the missing metrics, the autoscaler punts and returns the current scale.  So we never scale down, even when utilization is 0%.

I ran into this when testing a Deployment rollout that created a lot of Pending pods.  However I think I will address that issue in a separate PR.

**Comment by josephburnett** [comment]
Also, we should definitely write an E2E test for this.  Deploying new code under load without the HPA losing it's mind is an important use case.

**Comment by josephburnett** [comment]
@mwielgus I have run one additional manual test.  I scaled the cluster up to 10 nodes to have sufficient capacity and then made several changes to the Deployment under load.  In each case, the Deployment made additional pods (above the HPA max of 10) but the HPA didn't enter the feedback loop.  So again, I think this PR is good-to-go.

Re: the stuck HPA on missing metrics bug (https://github.com/kubernetes/kubernetes/pull/79035#issuecomment-503326840), I have opened a separate issue: https://github.com/kubernetes/kubernetes/issues/79158 and I'll work on that next.

**Comment by gliush** [comment]
I still believe that we should use only "ReadyPods" in all the calculations.
Consider the following example that I run on my `minikube`:

```$ cat /tmp/d.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 100
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "1000m"

$ kubectl create -f /tmp/d.yaml

$ kubectl get deployments nginx -o=jsonpath='{.spec.replicas}{"\t"}{.status.replicas}{"\n"}'
100 100

$ kubectl get pods | grep "Running" | wc -l 
2
```

So, I have 100 pods in Spec and in Status, while I have only 2 of them running. (In minikube I have only 2 cpus, but it may be caused by plenty of different reasons).

All other pods are in “Pending” state
If metrics show that we need to double the number of pods, HPA controller will set “Replicas: 200”. 

While only 2 pods are working, and in reality we need 4 of them

The next `reconcile` will increase it to “400” again, because the real number of pods was not changed, and the metric won’t change. 

This is the main problem with “specReplicas”, I believe. That it is not connected to reality.

**Comment by josephburnett** [comment]
> I still believe that we should use only "ReadyPods" in all the calculations.

@gliush and I had a conversation about this behavior and came to agreement.  In particular the difference between specifying `Value` or `AverageValue` and how the implementation treats the current number of Pods.  I believe that the correct behavior is to divide by `specReplicas` not by `statusReplicas` or ready pods.  That's because specifying an `AverageValue` doesn't put the autoscaler into a feedback loop like `Value`--it just reconciles to the current metric value by the target value.  This is not at all clear from the documentation, so I've opened https://github.com/kubernetes/kubernetes/issues/79272 to clarify.

However since the current implementation is using `statusReplicas` when calculating the `usageRatio` (by accident I think) I will change this PR to do the same.  That means we needlessly update `replicaCount` whenever `statusReplicas` exceeds `specReplicas` (e.g. a Deployment rollout is going on).  But the effect is minimal.  I will open a separate PR to fix that bug separately, dividing by `specReplicas` instead.

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 6]
```diff
@@ -334,7 +334,7 @@ func (c *ReplicaCalculator) GetExternalMetricReplicas(currentReplicas int32, tar
 // GetExternalPerPodMetricReplicas calculates the desired replica count based on a
 // target metric value per pod (as a milli-value) for the external metric in the
 // given namespace, and the current replica count.
-func (c *ReplicaCalculator) GetExternalPerPodMetricReplicas(currentReplicas int32, targetUtilizationPerPod int64, metricName, namespace string, metricSelector *metav1.LabelSelector) (replicaCount int32, utilization int64, timestamp time.Time, err error) {
+func (c *ReplicaCalculator) GetExternalPerPodMetricReplicas(statusReplicas int32, targetUtilizationPerPod int64, metricName, namespace string, metricSelector *metav1.LabelSelector) (replicaCount int32, utilization int64, timestamp time.Time, err error) {
```
Comment (krzysztof-jastrzebski) [inline pkg/controller/podautoscaler/replica_calculator.go]: Why "statusReplica". Is increasing number of pods during rolling upgrade increasing external metric? Additional pods  added during upgrade shouldn't serve as if they are healthy then old pods are deleted.

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: Incidentally, it doesn't make a difference whether we use status or spec replicas here.  It's technically a bug to use status replicas, but I left it as-is in order to fix one bug at a time.  https://github.com/kubernetes/kubernetes/issues/79274 tracks fixing the bug to use spec replicas.

Comment (josephburnett) [reply pkg/controller/podautoscaler/replica_calculator.go]: Also, it's super confusing that we pass in spec replicas at all.  We only use that value in order to signal a decision to not scale by returning the current desired replica count.  Better would be to return a boolean.  https://github.com/kubernetes/kubernetes/issues/79275 tracks that improvement.

**Comment by MaciekPytel** [comment]
/approve
Great stuff, sorry to be so unresponsive on review.

**Comment by josephburnett** [comment]
I need someone who can manually remove the needs-kind label.

image

**Comment by josephburnett** [comment]
/hold

I would like to squash these commits.

**Comment by josephburnett** [comment]
/hold cancel.

I've squashed and force pushed all the commits in this PR.  The original commits can be found in my repo: https://github.com/josephburnett/kubernetes/compare/hparunaway-base...josephburnett:hparunaway-original

**Comment by juanpmarin** [comment]
Hi, is this currently released ?

**Comment by austinpray** [comment]
> Hi, is this currently released ?

@juanpmarin it looks like this is gonna be in 1.16+

```
λ  kubernetes master ✓ git tag --contains 39c4875321991f305d51e30481a66701b6b76f5f
v1.16.0-alpha.1
v1.16.0-alpha.2
v1.16.0-alpha.3
v1.16.0-beta.0
v1.16.0-beta.1
v1.17.0-alpha.0
```

**Comment by kimxogus** [comment]
@juanpmarin This is also cherry picked to 1.13(#79707), 1.14(#79708), 1.15(#79709). Latest version of them may have this fix too.

**Comment by paalkr** [comment]
I would just like to draw some attention to https://github.com/kubernetes/kubernetes/issues/72775. Many are still facing issues with rolling updates.
