### PR TITLE
[#115501] Fix for issue with missing Loadbalancer policies for IPV6 endpoints in Dualstack mode.

### LINKED ISSUE #115501: [Winkernel Proxier] Issue with Loadbalancer policy creation for IPV6 endpoints in Dualstack mode.
### What happened?

When a service is created with ipFamilyPolicy: RequireDualStack, Kubeproxy is creating only Loadbalancer policies for IPV4 and not for IPV6.

### What did you expect to happen?

Loadbalancer policies should be created for both IPV4 and IPV6 in Dualstack mode.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a service with following configuration (configuration given at the end)
- Use the IPV4 cluster IP for accessing the service. It works.
- Use the IPV6 cluster IP for accessing the service and it will not work.
- Login to the node and execute "Get-HnsPolicylist". You will see the IPV6 policies are missing.

**Service Configuration**

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipv6-2
  name: ipv6-2
  namespace: demo
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  selector:
    app: windows-container
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 80

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

1.24 and above

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by princepereira**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

If the ipFamilyPolicy is RequireDualStack, then the ip list of each endpoint coming from hns will have 2 IPs (IPV4 and IPV6). Existing Kubeproxy was only picking up first IP which is IPV4 and ignoring IPV6. Hence Loadbalancer creation with IPV6 endpoints were failing. With new changes, KubeProxy will pick the second IP also (IPV6) and create one more loadbalancer policy with IPV6.

#### Which issue(s) this PR fixes:

Fixes #115501

#### Does this PR introduce a user-facing change?

```release-note
Fixing issue with Winkernel Proxier - IPV6 load balancer policies are missing when service is configured with ipFamilyPolicy: RequireDualStack
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig network
/sig windows

### CODE REVIEW

File: pkg/proxy/winkernel/hns.go [hunk 1]
```diff
@@ -112,8 +112,28 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
...
 		}
 		endpointInfos[ep.IpConfigurations[0].IpAddress] = endpointInfos[ep.Id]
+
+		if len(ep.IpConfigurations) == 1 {
+			continue
+		}
+
+		// If ipFamilyPolicy is RequireDualStack or PreferDualStack, then there will be 2 IPS (iPV4 and IPV6)
+		// in the endpoint list
+		endpointDualstack := &endpointsInfo{
```
Comment (feiskyer) [inline pkg/proxy/winkernel/hns.go:122]: Any possible to add some unit tests to avoid regressions in the future?
