### PR TITLE
Fixed the lease endpoint reconciler creation of kubernetes endpoint and lease file ttl. #53803

### LINKED ISSUE #53803: Lease reconciler creates incorrect kubernetes endpoint and lease files
/kind bug

The lease reconciler creates the kubernetes endpoint with a prefix of kube-apiserver-endpoint, however that is not the prefix that the rest of kube uses.  The end result is that the kubernetes service doesn't have an endpoint, and kubectl won't list the kubernetes endpoint.

The lease reconciler also creates lease files with a really long lease time instead of the default 15 seconds.

@liggitt @kubernetes/sig-api-machinery-bugs @sttts

### PR DESCRIPTION
**Pull request by rrati**
Fixed the prefix used to create the kubernetes endpoint and the ttl value used for lease files.

Fixes: #53803

### CODE REVIEW

**Comment by rrati** [comment]
@ncdc @rphillips

File: pkg/master/reconcilers/lease.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func (s *storageLeases) UpdateLease(ip string) error {
 			},
 		}
 
-		leaseTime := uint64(s.leaseTime)
+		leaseTime := uint64(s.leaseTime / time.Second)
```
Comment (ncdc) [inline pkg/master/reconcilers/lease.go]: Worth commenting that leaseTime has to be in seconds and hence the division?

File: pkg/master/master.go [hunk 2]
```diff
@@ -94,7 +94,7 @@ const (
 	// DefaultEndpointReconcilerTTL is the default TTL timeout for the storage layer
 	DefaultEndpointReconcilerTTL = 15 * time.Second
 	// DefaultStorageEndpoint is the default storage endpoint for the lease controller
-	DefaultStorageEndpoint = "kube-apiserver-endpoint"
+	DefaultStorageEndpoint = "services/endpoints"
```
Comment (ncdc) [inline pkg/master/master.go]: @deads2k @sttts @liggitt is there any better way to get at this value?

File: pkg/master/master.go [hunk 3]
```diff
@@ -94,7 +94,7 @@ const (
 	// DefaultEndpointReconcilerTTL is the default TTL timeout for the storage layer
 	DefaultEndpointReconcilerTTL = 15 * time.Second
 	// DefaultStorageEndpoint is the default storage endpoint for the lease controller
```
Comment (ncdc) [inline pkg/master/master.go]: This comment doesn't really make sense insofar as what it's really used for, and we should probably change the name of the constant too.

Comment (rrati) [reply pkg/master/master.go]: Agreed.  What about EndpointPrefix?

File: pkg/master/master.go (hunk 2 above)
Comment (liggitt) [reply pkg/master/master.go]: we shouldn't need this at all. this is getting passed like this:
```
ResourcePrefix:          c.ExtraConfig.StorageFactory.ResourcePrefix(kapi.Resource(DefaultStorageEndpoint)),
```

that should be 
```
ResourcePrefix:          c.ExtraConfig.StorageFactory.ResourcePrefix(kapi.Resource("endpoints")),
```

File: pkg/master/reconcilers/lease.go (hunk 1 above)
Comment (rrati) [reply pkg/master/reconcilers/lease.go]: Yep, will add a comment

**Comment by ncdc** [comment]
As best I can tell, the lease endpoint reconciler is only on master and not in 1.8, therefore:

/release-note-none

**Comment by ncdc** [comment]
@kubernetes/sig-api-machinery-pr-reviews

**Comment by liggitt** [comment]
> As best I can tell, the lease endpoint reconciler is only on master and not in 1.8, therefore:

Yes, merged after 1.8 was cut

File: pkg/master/master.go (hunk 2 above)
Comment (rphillips) [reply pkg/master/master.go]: Partial diff [here](https://github.com/kubernetes/kubernetes/compare/master...rphillips:fixes/lease_endpoint_fix)

Comment (rphillips) [reply pkg/master/master.go]: ah, the api.Resource("endpoints") is even better

Comment (rrati) [reply pkg/master/master.go]: I think we can get it from StorageFactory.ResourcePrefix(api.Resource("endpoints"))

File: pkg/master/master.go (hunk 3 above)
Comment (rrati) [reply pkg/master/master.go]: Actually, I think we can get rid of this const alltogether

Comment (liggitt) [reply pkg/master/master.go]: exactly

**Comment by ncdc** [comment]
@rrati I assume you've tested this locally and it's all good?

@liggitt any other comments?

File: pkg/master/master.go [hunk 4]
```diff
@@ -206,18 +204,19 @@ func (c *Config) createLeaseReconciler() reconcilers.EndpointReconciler {
 	if err != nil {
 		glog.Fatalf("Error creating storage factory: %v", err)
 	}
-	endpointConfig, err := c.ExtraConfig.StorageFactory.NewConfig(kapi.Resource(DefaultStorageEndpoint))
+	endpointPrefix := c.ExtraConfig.StorageFactory.ResourcePrefix(api.Resource("endpoints"))
+	endpointConfig, err := c.ExtraConfig.StorageFactory.NewConfig(kapi.Resource(endpointPrefix))
```
Comment (liggitt) [inline pkg/master/master.go]: `endpointPrefix := c.ExtraConfig.StorageFactory.ResourcePrefix(api.Resource("endpoints"))` looks right

`c.ExtraConfig.StorageFactory.NewConfig(kapi.Resource(endpointPrefix))` definitely does not look right... why are you passing the prefix into `kapi.Resource(endpointPrefix)`?

File: pkg/master/master.go [hunk 5]
```diff
@@ -206,18 +204,19 @@ func (c *Config) createLeaseReconciler() reconcilers.EndpointReconciler {
...
 	if err != nil {
 		glog.Fatalf("Error getting storage config: %v", err)
 	}
 	endpointsStorage := endpointsstorage.NewREST(generic.RESTOptions{
 		StorageConfig:           endpointConfig,
 		Decorator:               generic.UndecoratedStorage,
 		DeleteCollectionWorkers: 0,
-		ResourcePrefix:          c.ExtraConfig.StorageFactory.ResourcePrefix(kapi.Resource(DefaultStorageEndpoint)),
+		ResourcePrefix:          c.ExtraConfig.StorageFactory.ResourcePrefix(kapi.Resource(endpointPrefix)),
```
Comment (liggitt) [inline pkg/master/master.go]: should be `ResourcePrefix: endpointPrefix`, right?

File: pkg/master/master.go [hunk 6]
```diff
@@ -206,18 +204,19 @@ func (c *Config) createLeaseReconciler() reconcilers.EndpointReconciler {
...
 	})
 	endpointRegistry := endpoint.NewRegistry(endpointsStorage)
-	masterLeases := reconcilers.NewLeases(leaseStorage, "/masterleases/", ttl)
+	masterLeases := reconcilers.NewLeases(leaseStorage, "/masterleases", ttl)
```
Comment (liggitt) [inline pkg/master/master.go]: do `path.Join` internally to ensure we normalize joining with or without leading/trailing slashes?

Comment (liggitt) [reply pkg/master/master.go]: also, does `List` depend on a trailing slash? does removing this mean we could see things at `/masterleases1`?

Comment (rrati) [reply pkg/master/master.go]: Internally the prefix is appended with a / and a key for specific keys or just the prefix, so shouldn't have an issue with /masterleases1.  It is currently hard-coded so "masterleases/" would result in "masterleases//" on lookup.  Using path.join is the better way to handle the filename.

File: pkg/master/master.go (hunk 4 above)
Comment (rrati) [reply pkg/master/master.go]: Yes, should remove the kapi.Resource for endpointConfig.

File: pkg/master/master.go (hunk 5 above)
Comment (rrati) [reply pkg/master/master.go]: Yes

File: pkg/master/master.go (hunk 6 above)
Comment (liggitt) [reply pkg/master/master.go]: > or just the prefix, so shouldn't have an issue with /masterleases1

my question was whether `List("/masterleases")` would return `/masterleases1`

Comment (rrati) [reply pkg/master/master.go]: Updated the internals to use path.join when hunting for a key

Comment (rrati) [reply pkg/master/master.go]: > my question was whether List("/masterleases") would return /masterleases1 if it existed

I believe it would.  The list function is just using a prefix.  In my experience List("masterleases") would return /masterleses1 and/or /masterleases/1

Comment (liggitt) [reply pkg/master/master.go]: so this needs to change back to "/masterleases/"

Comment (rrati) [reply pkg/master/master.go]: You're right.  I'll fix

File: pkg/master/master.go (hunk 4 above)
Comment (liggitt) [reply pkg/master/master.go]: the output of `c.ExtraConfig.StorageFactory.ResourcePrefix` is an etcd prefix, the location in etcd where we want to store that resource.

taking that value and making a `schema.GroupResource` out of it doesn't make any sense. this should be 
```
endpointConfig, err := c.ExtraConfig.StorageFactory.NewConfig(kapi.Resource("endpoints"))
```

File: pkg/master/master.go (hunk 5 above)
Comment (liggitt) [reply pkg/master/master.go]: same response as above :)

**Comment by rrati** [comment]
@ncdc Yes, I've tested on a 3 node apiserver setup and verified the lease files are created, expire, and that the endpoint is created in the proper location and attached to the kubernetes service

**Comment by ncdc** [comment]
LGTM. Will defer to @liggitt to tag
