### PR TITLE
Fix DaemonSet status update retry

### LINKED ISSUE #99397: Many error logs in kube-controller-manager about storing status for daemon set
#### What happened:
Almost every update to a DaemonSet can lead to 2~3 error logs in kube-controller-manager even when the DaemonSet manages very few Pods, for example, there were 3 error logs when updating a daemonset in a small cluster of 2 Nodes.
```
E0224 11:45:58.101426       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
E0224 11:46:43.871336       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
E0224 11:46:43.906964       1 daemon_controller.go:320] kube-system/antrea-agent failed with : error storing status for daemon set &v1.DaemonSet{...} :Operation cannot be fulfilled on daemonsets.apps "antrea-agent": the object has been modified; please apply your changes to the latest version and try again
```
Other controllers like deployment don't have this issue when they manage much more Pods.

After looking at DaemonSet controller code, it seems the retry logic in "storeDaemonSetStatus" was not implemented correctly. It never really retried and always made an useless GET call.
https://github.com/kubernetes/kubernetes/blob/4cc1127e9251fff364d5c77e2a9a9c3ad42383ab/pkg/controller/daemon/daemon_controller.go#L1043-L1065

#### What you expected to happen:
DaemonSet controller should produce less error logs in normal case.

#### How to reproduce it (as minimally and precisely as possible):
Create or update a DaemonSet to trigger Pod recreation.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
It's easy to get update conflict when processing a DaemonSet
continuously. storeDaemonSetStatus had a retry logic that it gets the
resource from apiserver to update the DaemonSet with the latest resource
version. However, it never really retried because of a wrong check and
always made an useless get call. This patch fixes the logic to allow
the function retry once on update error.

#### Which issue(s) this PR fixes:

Fixes #99397

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/daemon/daemon_controller.go [hunk 1]
```diff
@@ -1040,7 +1040,7 @@ func storeDaemonSetStatus(dsClient unversionedapps.DaemonSetInterface, ds *apps.
 	toUpdate := ds.DeepCopy()
 
 	var updateErr, getErr error
-	for i := 0; i < StatusUpdateRetries; i++ {
+	for i := 0; ; i++ {
 		if updateObservedGen {
 			toUpdate.Status.ObservedGeneration = ds.Generation
 		}
```
Comment (wangyysde) [inline pkg/controller/daemon/daemon_controller.go:1046]: As if updateObserveGen has been called in storeDaemonSetStatus function :
1041 
   1042         var updateErr, getErr error
   1043         for i := 0; i < StatusUpdateRetries; i++ {
   1044                 if updateObservedGen {
   1045                         toUpdate.Status.ObservedGeneration = ds.Generation
   1046                 }

Comment (tnqn) [reply pkg/controller/daemon/daemon_controller.go:1046]: Sorry, could you explain what you mean?

**Comment by tnqn** [comment]
@kubernetes/sig-apps-pr-reviews hi, could you please review this one?

**Comment by tnqn** [comment]
@soltysh @tnozicka could you take a look? thanks!

**Review by soltysh — APPROVED** [review]
Yeah it looks like this retry mechanism was broken in https://github.com/kubernetes/kubernetes/pull/26931/files#diff-b8f230dad30a6ff060d68f33bacabe4a61dbbeccf252252740cbc91c87142c37R577 

/triage accepted
/priority backlog
/lgtm
/approve
