### PR TITLE
fix: fixes update CRD check

### LINKED ISSUE #123921: [Flaking Test] integration TestStorageVersionMigrationWithCRD
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1767480303611285504

### Which tests are flaking?

k8s.io/kubernetes/test/integration: storageversionmigrator TestStorageVersionMigrationWithCRD

### Since when has it been flaking?

Added with https://github.com/kubernetes/kubernetes/pull/123344 03-09.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
E0312 10:10:59.700953  118731 watcher.go:471] failed to prepare current and previous objects: request to convert CR from an invalid group/version: stable.example.com/v2

```

### Anything else we need to know?

/cc @nilekhc @deads2k @jpbetz 

### Relevant SIG(s)

/sig api-machinery

### PR DESCRIPTION
**Pull request by nilekhc**
#### What type of PR is this?

/kind cleanup
/kind failing-test
/kind flake

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/123921

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig api-machinery

### CODE REVIEW

**Comment by nilekhc** [comment]
@benluddy fyi

File: test/integration/storageversionmigrator/util.go [hunk 1]
```diff
@@ -26,14 +26,14 @@ import (
...
 	"path/filepath"
+	"reflect"
 	"regexp"
 	"strconv"
 	"strings"
 	"testing"
 	"time"
 
 	clientv3 "go.etcd.io/etcd/client/v3"
-
```
Comment (enj) [inline test/integration/storageversionmigrator/util.go:36]: Undo since third party and kube imports should be separated.

File: test/integration/storageversionmigrator/util.go [hunk 2]
```diff
@@ -768,15 +745,30 @@ func (svm *svmTest) updateCRD(
 		t.Fatalf("Failed to update CRD: %v", err)
 	}
 
-	crd, err := svm.apiextensionsclient.ApiextensionsV1().CustomResourceDefinitions().Get(ctx, crdName, metav1.GetOptions{})
+	// wait for CRD to be updated with desired versions
```
Comment (enj) [inline test/integration/storageversionmigrator/util.go:748]: This is checking the wrong thing.  What you need to check is that the Kube API server has caught up to the config change _in memory_.

**Review by enj — CHANGES_REQUESTED** [review]

**Comment by enj** [comment]
Linter error is related, otherwise LGTM.
