### PR TITLE
fix unsafe JSON construction

### LINKED ISSUE #81134: Unsafe JSON construction
This issue was reported in the [Kubernetes Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Description**
Kubernetes uses JavaScript Object Notation (JSON) and similarly structured data sources throughout the codebase. This supports inter-component communications, both internally and externally to the cluster. However, a number of locations within the codebase use unsafe methods of constructing JSON:

```
pkg/kubectl/cmd/taint/taint.go:218:				conflictTaint := fmt.Sprintf("{\"%s\":\"%s\"}", taintRemove.Key, taintRemove.Effect)

pkg/apis/rbac/helpers.go:109:	formatString := "{" + strings.Join(formatStringParts, ", ") + "}"
```
Figure 24.1: Examples of incorrect JSON and JSON-like construction

**Exploit Scenario**
Alice runs a Kubernetes cluster in her organization. Bob, a user in Alice’s organization, attempts to add an RBAC permission that he is not entitled to, which causes his entire RBAC construction to be written to logs, and potentially improperly consumed elsewhere.

**Recommendation**
Short term, use proper format-specific encoders for all areas of the application, regardless of where the information is used. 

Long term, unify the encoding method to ensure encoded values are validated before use, and that no portion of the application produces values with different validations.

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix unsafe JSON construction
**Which issue(s) this PR fixes**:

xref #81134

**Special notes for your reviewer**:
Kubernetes uses JavaScript Object Notation (JSON) and similarly structured data sources throughout the codebase. This supports inter-component communications, both internally and externally to the cluster. However, a number of locations within the codebase use unsafe methods of constructing JSON.

Exploit Scenario
Alice runs a Kubernetes cluster in her organization. Bob, a user in Alice’s organization, attempts to add an RBAC permission that he is not entitled to, which causes his entire RBAC construction to be written to logs, and potentially improperly consumed elsewhere.

**Does this PR introduce a user-facing change?**:

```release-note
Fix unsafe JSON construction in a number of locations in the codebase
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
@zouyee 
thanks for the PR,
please have a look at the failing unit tests:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81158/pull-kubernetes-bazel-test/1159405661419737088

**Comment by neolit123** [comment]
as the linked issue outlines there are more instances of this problem:
```
kg/kubectl/cmd/taint/taint.go:218:				conflictTaint := fmt.Sprintf("{\"%s\":\"%s\"}", taintRemove.Key, taintRemove.Effect)

pkg/apis/rbac/helpers.go:109:	formatString := "{" + strings.Join(formatStringParts, ", ") + "}"
```

could you try solving all of them in this PR?

instead of NONE under `Does this PR introduce a user-facing change?:` please add:
> Fix unsafe JSON construction in a number of locations in the codebase

**Comment by zouyee** [comment]
Because different components are involved, should they be split into multiple PR？@neolit123

**Comment by neolit123** [comment]
please send them all as part of this PR and if they are way to many we can decide to split.
thanks.

**Comment by neolit123** [comment]
@zouyee 
please have a look at the govet failures:
```
# k8s.io/kubernetes/pkg/controller
pkg/controller/controller_ref_manager.go:219:45: call of ownerRefControllerPatch copies lock value: k8s.io/kubernetes/pkg/controller.BaseControllerRefManager contains sync.Once contains sync.Mutex
pkg/controller/controller_ref_manager.go:344:45: call of ownerRefControllerPatch copies lock value: k8s.io/kubernetes/pkg/controller.BaseControllerRefManager contains sync.Once contains sync.Mutex
pkg/controller/controller_ref_manager.go:482:45: call of ownerRefControllerPatch copies lock value: k8s.io/kubernetes/pkg/controller.BaseControllerRefManager contains sync.Once contains sync.Mutex
pkg/controller/controller_ref_manager.go:534:34: ownerRefControllerPatch passes lock by value: k8s.io/kubernetes/pkg/controller.BaseControllerRefManager contains sync.Once contains sync.Mutex
make[1]: *** [vet] Error 1
```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81158/pull-kubernetes-verify/1161197154933411840

File: pkg/controller/garbagecollector/patch.go [hunk 1]
```diff
@@ -30,12 +29,21 @@ import (
 )
 
 func deleteOwnerRefStrategicMergePatch(dependentUID types.UID, ownerUIDs ...types.UID) []byte {
```
Comment (liggitt) [inline pkg/controller/garbagecollector/patch.go]: consider using a typed struct with json annotations to avoid map allocation. see the objectForFinalizersPatch type and use in this package as an example

Comment (zouyee) [reply pkg/controller/garbagecollector/patch.go]: done

**Comment by zouyee** [comment]
gentle ping @liggitt

**Comment by zouyee** [comment]
ping @neolit123

**Review by liggitt — COMMENTED** [review]
just made it through the node function

File: pkg/controller/history/controller_history.go [hunk 2]
```diff
@@ -290,17 +291,41 @@ func (rh *realHistory) DeleteControllerRevision(revision *apps.ControllerRevisio
...
+}
+
 func (rh *realHistory) AdoptControllerRevision(parent metav1.Object, parentKind schema.GroupVersionKind, revision *apps.ControllerRevision) (*apps.ControllerRevision, error) {
+	blockOwnerDeletion := true
+	isController := true
 	// Return an error if the parent does not own the revision
 	if owner := metav1.GetControllerOf(revision); owner != nil {
 		return nil, fmt.Errorf("attempt to adopt revision owned by %v", owner)
 	}
+	addControllerPatch := ObjectMetaForPatch{}
```
Comment (liggitt) [inline pkg/controller/history/controller_history.go]: would be easier to see the structure as:
```go
addControllerPatch := objectForPatch{
  Metadata: objectMetaForPatch{
    UID: revision.UID,
    OwnerReferences: []metav1.OwnerReference{{
      APIVersion:         parentKind.GroupVersion().String(),
      Kind:               parentKind.Kind,
      Name:               parent.GetName(),
      UID:                parent.GetUID(),
      Controller:         &isController,
      BlockOwnerDeletion: &blockOwnerDeletion,
    }},
  }
}
```

(same comment applies elsewhere)

**Comment by zouyee** [comment]
@liggitt Please take another look

File: pkg/util/node/node.go [hunk 3]
```diff
@@ -193,18 +220,18 @@ func PatchNodeCIDR(c clientset.Interface, node types.NodeName, cidr string) erro
...
 // PatchNodeCIDRs patches the specified node.CIDR=cidrs[0] and node.CIDRs to the given value.
 func PatchNodeCIDRs(c clientset.Interface, node types.NodeName, cidrs []string) error {
-	rawCidrs, err := json.Marshal(cidrs)
-	if err != nil {
-		return fmt.Errorf("failed to json.Marshal CIDRs: %v", err)
+	// set the pod cidrs list and set the old pod cidr field
+	patch := nodeForMergePatch{
+		Spec: nodeSpecForMergePatch{
+			PodCIDR:  cidrs[0],
+			PodCIDRs: cidrs[:],
```
Comment (liggitt) [inline pkg/util/node/node.go]:
```suggestion
			PodCIDRs: cidrs,
```

File: pkg/util/node/node.go [hunk 4]
```diff
@@ -158,14 +158,29 @@ func GetZoneKey(node *v1.Node) string {
 	return region + ":\x00:" + failureDomain
 }
 
+type nodeForPatch struct {
```
Comment (liggitt) [inline pkg/util/node/node.go]: the types are getting a bit confusing, naming the top level per use might be easier to follow

```suggestion
type nodeForConditionPatch struct {
```

File: pkg/util/node/node.go [hunk 5]
```diff
@@ -176,15 +191,27 @@ func SetNodeCondition(c clientset.Interface, node types.NodeName, condition v1.N
 	return err
 }
 
+type nodeForMergePatch struct {
```
Comment (liggitt) [inline pkg/util/node/node.go]:
```suggestion
type nodeForCIDRMergePatch struct {
```

File: pkg/controller/garbagecollector/patch.go [hunk 6]
```diff
@@ -29,13 +28,31 @@ import (
 	"k8s.io/kubernetes/pkg/controller/garbagecollector/metaonly"
 )
 
+type objectForStrategicMergePatch struct {
```
Comment (liggitt) [inline pkg/controller/garbagecollector/patch.go]:
```suggestion
type objectForDeleteOwnerRefStrategicMergePatch struct {
```

File: pkg/controller/controller_ref_manager.go [hunk 7]
```diff
@@ -499,3 +512,64 @@ func (m *ControllerRevisionControllerRefManager) ReleaseControllerRevision(histo
 	}
 	return err
 }
+
+type objectForStrategicMergePatch struct {
```
Comment (liggitt) [inline pkg/controller/controller_ref_manager.go]:
```suggestion
type objectForDeleteOwnerRefStrategicMergePatch struct {
```

File: pkg/controller/controller_ref_manager.go [hunk 8]
```diff
@@ -499,3 +512,64 @@ func (m *ControllerRevisionControllerRefManager) ReleaseControllerRevision(histo
...
+		},
+	}
+	patchBytes, err := json.Marshal(&patch)
+	if err != nil {
+		return nil, err
+	}
+	return patchBytes, nil
+}
+
+type objectForPatch struct {
```
Comment (liggitt) [inline pkg/controller/controller_ref_manager.go]:
```suggestion
type objectForAddOwnerRefPatch struct {
```

**Review by liggitt — COMMENTED** [review]
one final round of comments, and go ahead and squash commits, then this lgtm. thanks for your patience.

**Comment by zouyee** [comment]
commit squashed, and thanks for your guidance！
