### PR TITLE
Make each new instance of kubelet generate a new event channel

### LINKED ISSUE #5327: Event failed to update
Seen in integration test output:

```
E0311 14:09:25.955280   99741 event.go:127] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"127.0.0.1.13ca8dd23271fd55", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"starting", Message:"Starting kubelet.", Source:api.EventSource{Component:"kubelet", Host:"127.0.0.1"}, FirstTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, LastTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, Count:1}': 'events "127.0.0.1.13ca8dd23271fd55" already exists' (will not retry!)
```

### PR DESCRIPTION
**Pull request by saad-ali**
Fixes #5327

Integration test shows a bunch of `Unable to write event` errors:

```
E0311 14:09:25.955280   99741 event.go:127] Unable to write event '&api.Event{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"127.0.0.1.13ca8dd23271fd55", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", CreationTimestamp:util.Time{Time:time.Time{sec:0, nsec:0x0, loc:(*time.Location)(nil)}}, Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Minion", Namespace:"default", Name:"127.0.0.1", UID:"127.0.0.1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"starting", Message:"Starting kubelet.", Source:api.EventSource{Component:"kubelet", Host:"127.0.0.1"}, FirstTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, LastTimestamp:util.Time{Time:time.Time{sec:63561704965, nsec:0x38560b55, loc:(*time.Location)(0x12138e0)}}, Count:1}': 'events "127.0.0.1.13ca8dd23271fd55" already exists' (will not retry!)
```

This error, `events ... already exists`, indicates that an event with the same key already exists in etcd.

This happens because the integration test [creates two kubelet instances](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L223) (on two different ports), however the setup process creates two different event listeners that listen to the [same event channel](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L167). Thus, when an event is generated by either instance of kubelet, it is passed through the shared channel, and is [consumed by both instances of kubelet](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L149), both of which [issue calls to the API server to create the same exact event](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/record/event.go#L73) in rapid succession (which ever call arrives first, succeeds, and the subsequent call fails with this error). Because etcd is called two times to create the same exact event it returns this error.

The fix ensures that each instance of kubelet creates its own event channel (`EventBroadcaster`) (instead of reusing existing).

### CODE REVIEW

**Comment by erictune** [comment]
@saad-ali thanks for fixing this.   I think I complained about it last week at the sprint.

I'm going to reassign to lavalamp who has more attachment to the events code.

**Comment by saad-ali** [comment]
@lavalamp is out of office. @dchen1107 could you take a look

**Comment by saad-ali** [comment]
Ping

**Comment by saad-ali** [comment]
Rebased and mereged.

**Comment by lavalamp** [comment]
Sorry for delay.

I think my initial thought on how to solve this would be to make sure that event broadcasting was turned on once per *binary*, not once per component. Then you wouldn't have to do most of this, I think. I'm reading through this now to try and figure out how it's supposed to work after this change.

File: pkg/client/record/event.go [hunk 1]
```diff
@@ -44,50 +46,94 @@ type EventSink interface {
...
+	// 'message' is intended to be human readable.
+	//
+	// The resulting event will be created in the same namespace as the reference object.
+	Event(object runtime.Object, reason, message string)
+
+	// Eventf is just like Event, but with Sprintf for the message field.
+	Eventf(object runtime.Object, reason, messageFmt string, args ...interface{})
+}
+
+// EventBroadcaster knows how to recieve events and send them to various sources.
```
Comment (lavalamp) [inline pkg/client/record/event.go]: // EventBroadcaster knows how to receive events and send them to any EventSink, watcher, or log.

?

File: pkg/client/record/event.go [hunk 2]
```diff
@@ -44,50 +46,94 @@ type EventSink interface {
...
+	// sink. The return value can be ignored or used to stop recording, if desired.
+	StartRecordingToSink(sink EventSink) watch.Interface
+
+	// StartLogging starts sending events recieved from this EventBroadcaster to the given logging
+	// function. The return value can be ignored or used to stop recording, if desired.
+	StartLogging(logf func(format string, args ...interface{})) watch.Interface
+
+	// NewRecorder returns an EventRecorder that can be used to send events to this EventBroadcaster
+	// with the event source set to the given event source.
+	NewRecorder(source api.EventSource) EventRecorder
```
Comment (lavalamp) [inline pkg/client/record/event.go]: Will more than one recorder ever be made for a broadcaster? Can we collapse those to be one object?

Comment (saad-ali) [inline pkg/client/record/event.go]: I would prefer to leave recorder and broadcaster as separate objects. Although we only have one recorder per broadcaster so far, I'd like to leave the flexibility of having multiple recorders. The way I see it the broadcaster is a pipe, it can support multiple inputs via recorders, and multiple outputs via sinks. However, if you feel strongly, let me know--I can change it.

File: pkg/client/record/event.go (hunk 1 above)
Comment (saad-ali) [inline pkg/client/record/event.go]: Done.

File: pkg/client/record/event.go (hunk 2 above)
Comment (lavalamp) [inline pkg/client/record/event.go]: OK-- I don't have a super strong opinion, but creating one broadcaster per server object (instead of per binary) just seems a little inconsistent. Like presumably one server object won't ever want to send events from more than one source.

**Comment by lavalamp** [comment]
LGTM - I guess I have a slight preference (2 on a scale from 1-10) for a single broadcaster per binary, with passing recorders into individual server objects. Seems like it might be slightly more testable. But I won't ask you to change it unless you really want to.

**Comment by saad-ali** [comment]
Thanks @lavalamp! I'll leave recorder and broadcaster as separate objects for now. I rebased, so merge should be green now.

**Comment by lavalamp** [comment]
LGTM
