### PR TITLE
EventedPLEG: Set Timestamp in PodStatus for Generic PLEG more accurate

### LINKED ISSUE #126414: EventedPLEG: Timestamp in PodStatus for Generic PLEG should be more accurate
### What happened?

When the `EventedPLEG` feature is enabled, GenericPLEG also works for backing up the EventedPLEG. In case both PLEGs update the same pod status in the cache at the almost same time, `Timestamp` was introduced to `PodSandboxStatusResponse` in the CRI API ([KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3386-kubelet-evented-pleg#timestamp-of-the-pod-status)). This timestamp (`PodSandboxStatusResponse.Timestamp`) is recorded in seconds while the timestamp in an event (`ContainerEventResponse.CreatedAt`) is recorded in nanoseconds. So, these timestamps cannot be compared accurately.

- Evented PLEG uses a timestamp in `ContainerEventResponse.CreatedAt` for the cache. This is set in nanoseconds in runtimes ([CRI-O code](https://github.com/cri-o/cri-o/blob/74d54cd3071c51225055df91121ebf77618e86a8/server/server.go#L934)) (though there is a bug (#124297) that kubelet treats it as seconds).
- Generic PLEG uses a timestamp in `PodSandboxStatusResponse.Timestamp` for the cache:
  https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1583
  This value is set in seconds by [CRI-O](https://github.com/cri-o/cri-o/blob/74d54cd3071c51225055df91121ebf77618e86a8/server/sandbox_status.go#L43-L65) while [containerd](https://github.com/containerd/containerd/blob/2ddd3db9524b14000208862e2e578e567b391a06/internal/cri/server/sandbox_status.go#L85-L88) does not look to set it (though there is another issue (https://github.com/kubernetes/kubernetes/issues/125624#issuecomment-2254396844) regarding containerd case). 

### What did you expect to happen?

`PodSandboxStatusResponse.Timestamp` should be recorded in nanoseconds.

### How can we reproduce it (as minimally and precisely as possible)?

It is difficult to reproduce this race intentionally on Kubernetes.

The following sample code simulates the problem:
```
package main

import (
	"fmt"
	"time"
)

func main() {
	eventedTime := time.Now().UnixNano()
	time.Sleep(100 * time.Millisecond)
	genericTime := time.Now().Unix()

	cachedEventedTime := time.Unix(0, eventedTime)
	cachedGenericTime := time.Unix(genericTime, 0)

	if cachedEventedTime.Before(cachedGenericTime) {
		fmt.Printf("Expected: evented:%v, generic:%v\n", cachedEventedTime, cachedGenericTime)
	} else {
		fmt.Printf("Unexpected: evented:%v, generic:%v\n", cachedEventedTime, cachedGenericTime)
	}
}
```

```
$ go run timestamp.go 
Unexpected: evented:2024-07-28 13:57:26.329366032 +0200 CEST, generic:2024-07-28 13:57:26 +0200 CEST
```

### Anything else we need to know?

_No response_

### Kubernetes version

Current master (1.31)

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

This issue could happen with CRI-O, which sets `Timestamp` to `PodSandboxStatusResponse`.

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yaojunyu**
**What type of PR is this?**
/kind bug
/kind cleanup
/kind sig-node

**What this PR does / why we need it:**
Ref: https://github.com/kubernetes/kubernetes/pull/127195#discussion_r1759704491
Timestamp returned by PodSandboxStatus should be more accurate. PR https://github.com/cri-o/cri-o/pull/8582 has already changed timestamp to nanoseconds so kubelet should change it.
BTW, timestamp is not return by runtime Containerd, we should set timestamp as now  in `GetPodStatus()` for Generic PLEG to set cache by `status.timestamp` regardless of whether EventedPLEG is enabled or not.

**Which issue(s) this PR fixes:**
Fixes https://github.com/kubernetes/kubernetes/issues/126414

**Special notes for your reviewer:**
Follow https://github.com/kubernetes/kubernetes/pull/124297

**Does this PR introduce a user-facing change?**
NONE

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
NONE

### CODE REVIEW

**Review by HirazawaUi — COMMENTED** [review]
We already have a PR to address this issue, ref: #124297.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -1580,7 +1580,7 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety
 			} else {
 				// Get the statuses of all containers visible to the pod and
 				// timestamp from sandboxStatus.
-				timestamp = time.Unix(resp.Timestamp, 0)
+				timestamp = time.Unix(0, resp.Timestamp)
```
Comment (hshiina) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1583]: CRI-O sets this timestamp in seconds. I don't think this is related to the problem mentioned in this PR. There is another issue (#126414) regarding this timestamp, though.

**Comment by haircommander** [comment]
do we still need this given https://github.com/kubernetes/kubernetes/pull/127195#pullrequestreview-2286731004 @HirazawaUi @yaojunyu ?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (hshiina) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1583]: If you are interested in, could you please update this PR to fix here for #126414? I think we should fix here in v1.32 because CRI-O has been fixed to set nanoseconds to this timestamp for v1.32. Otherwise, I guess EventedPLEG would not work.

**Comment by HirazawaUi** [comment]
Some changes are still required. @yaojunyu should only fix the code in `pkg/kubelet/kuberuntime/kuberuntime_manager.go`.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (yaojunyu) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1584]: @hshiina I updated this PR. Please have a review.

**Comment by yaojunyu** [comment]
Based on @hshiina 's suggestions, I have updated the PR again and revised the description of the PR. cc @HirazawaUi @haircommander

File: pkg/kubelet/pleg/generic.go [hunk 2]
```diff
@@ -475,7 +475,9 @@ func (g *GenericPLEG) updateCache(ctx context.Context, pod *kubecontainer.Pod, p
 	// Evented PLEG after the event has been received by the Kubelet.
 	// For more details refer to:
 	// https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3386-kubelet-evented-pleg#timestamp-of-the-pod-status
-	if utilfeature.DefaultFeatureGate.Enabled(features.EventedPLEG) && isEventedPLEGInUse() && status != nil {
+	// Regardless of whether EventedPLEG is enabled or not, status.TimeStamp will be calculated by
+	// runtime.GetPodStatus() as long as it does return none-null PodStatus.
+	if status != nil {
```
Comment (HirazawaUi) [inline pkg/kubelet/pleg/generic.go:480]: This seems reasonable, but you should not make changes here, as it may break the existing behavior of the Generic PLEG. You should revert this commit and narrow the scope of this PR to only modifying the timestamp.

If you still feel that this change is necessary, please open a new PR for review.

**Comment by HirazawaUi** [comment]
/lgtm

This fix seems harmless.

It is worth noting that there was a bug in CRI-O where the returned timestamp was in seconds, but they have already fixed it and picked the fix to version 1.31.
ref: https://github.com/cri-o/cri-o/pull/8582

Additionally, I tested with the following code, and regardless of whether the timestamp returned by the container runtime is in seconds or nanoseconds, converting it to nanoseconds does not break our behavior:
ref: https://go.dev/play/p/8pwa3CwFlTE

I am not sure if this PR should be approved immediately based on the above two conditions, or if we need to wait for the version skew between Kubelet and CRI-O.

/cc @SergeyKanzhelev

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -1536,7 +1536,7 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety
 
 	sandboxStatuses := []*runtimeapi.PodSandboxStatus{}
 	containerStatuses := []*kubecontainer.Status{}
-	var timestamp time.Time
+	timestamp := time.Now()
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1539]: what the story here? How it worked for non-Evented PLEG? I don't see this field initialized outside the evented pleg feature gate

Comment (yaojunyu) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1539]: This timestamp variable was introduced in the EventedPLEG feature [PR#111318](https://github.com/kubernetes/kubernetes/pull/111384/files#diff-0e1a8d22b0f1dc42d412749c6a916b4c76394ead739d4bfbf26564faedd74a2f) to address timestamp race conditions when updating pod status cache. It should ideally correspond to the time the container runtime retrieves the pod status and should be returned through the CRI `PodSandboxStatus()`. When using generic pleg, this variable is not used, so it does not affect the existing non-EventedPLEG logic. However, when EventedPLEG is enabled and the CRI `PodSandboxStatus()` does not return a timestamp (as with containerd, which I believe should also return it to reduce the overhead of an additional request), timestamp in PodStatus returned by `GetPodStatus()` will always be zero. This means that the pod status cache will never be updated when running a generic pleg Relist() to call `updateCache()`, because timestamp overwritten  to zero is impossible newer than exist cached timestamp. In this scenario, running the generic pleg at longer intervals(5 minutes) is futile and meaningless when EventePLEG is enabled. So I changed the zero timestamp to now for making it possible to update the cache.

Comment (yaojunyu) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1539]: This timestamp variable was introduced in the EventedPLEG feature [PR#111318](https://github.com/kubernetes/kubernetes/pull/111384/files#diff-0e1a8d22b0f1dc42d412749c6a916b4c76394ead739d4bfbf26564faedd74a2f) to address timestamp race conditions when updating pod status cache. It should ideally correspond to the time the container runtime retrieves the pod status and should be returned through the CRI `PodSandboxStatus()`. When using generic pleg, this variable is not used, so it does not affect the existing non-EventedPLEG logic. However, when EventedPLEG is enabled and the CRI `PodSandboxStatus()` does not return a timestamp (as with containerd, which I believe should also return it to reduce the overhead of an additional request), timestamp in PodStatus returned by `GetPodStatus()` will always be zero. This means that the pod status cache will never be updated when running a generic pleg Relist() to call `updateCache()`, because timestamp overwritten  to zero is impossible newer than exist cached timestamp. In this scenario, running the generic pleg at longer intervals(5 minutes) is futile and meaningless when EventePLEG is enabled. So I changed the zero timestamp to now for making it possible to update the cache.

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1539]: I see that timestamp is initialized here and then used in a return object unconditionally. Is it not being used for generic PLEG? Any sideeffects for the generic pleg?

Comment (yaojunyu) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1539]: The timestamp is only used in updateCache(), ref: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go#L483.
```go
	if utilfeature.DefaultFeatureGate.Enabled(features.EventedPLEG) && isEventedPLEGInUse() && status != nil {
		timestamp = status.TimeStamp
	}
``` 
 I also checked all other places where this function `GetPodStatus` called and none of them use this timestamp field. I believe this changed is safe for generic pleg.

**Review by SergeyKanzhelev — COMMENTED** [review]
following the https://github.com/kubernetes/kubernetes/pull/124297/ I want to merge this. The only thing - we need a test that will demonstrate the bad behavior and how it is fixed with this change.

The fact that Evented PLEG introduces logic and field that only needed for it, but exposed to the Generic PLEG makes things 1000 times harder to review and approve.

We need to seriously consider removing the whole Evented PLEG feature unless we have a clear KEP ownership and commitment to clean up code.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

another one we merge with just a code analysis and no tests to catch the regression if any. Unblocking https://github.com/kubernetes/kubernetes/issues/127814
