### PR TITLE
fix azureDisk warns about disk format failure

### LINKED ISSUE #53713: azureDisk warns about disk format failure when successfull
While trying to resolve some azure-disk issues I am encountering I noticed some strange logs:

Oct 11 10:37:49 smblab-we-worker-0 kubelet-wrapper[1264]: I1011 10:37:49.508797    1264 azure_common_linux.go:153] azureDisk - Disk successfully formatted (mkfs): ext4 - /dev/sdd tt
Oct 11 10:37:49 smblab-we-worker-0 kubelet-wrapper[1264]: W1011 10:37:49.509230    1264 azure_common_linux.go:155] azureDisk - format of disk "/dev/sdd" failed: type:("ext4") target:("tt") options:("o")error:(<nil>)

Looking at the code it seem like an else clause is missing:

https://github.com/kubernetes/kubernetes/blob/0564d5298504cb57ec4d35cf4878e383f9504ed6/pkg/volume/azure_dd/azure_common_linux.go#L155

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53713

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

File: pkg/volume/azure_dd/azure_common_linux.go [hunk 1]
```diff
@@ -151,8 +151,9 @@ func formatIfNotFormatted(disk string, fstype string, exec mount.Exec) {
 		if err == nil {
 			// the disk has been formatted successfully try to mount it again.
 			glog.Infof("azureDisk - Disk successfully formatted (mkfs): %s - %s %s", fstype, disk, "tt")
+		} else {
+			glog.Warningf("azureDisk - format of disk %q failed: type:(%q) target:(%q) options:(%q)error:(%v)", disk, fstype, "tt", "o", err)
```
Comment (jsafrane) [inline pkg/volume/azure_dd/azure_common_linux.go]: What about `"error formatting volume with 'mkfs.%s %v': %v", fstype, args, err`? You're hiding "lazy_itable_init" and such.  (Applies also to `glog.Infof` few lines above).
