### PR TITLE
Re-enable Kubelet Pod Readiness Probes on Termination and Pod probes should be handled by pod worker 

### LINKED ISSUE #102537: Pod does not go into unready state while terminating
#### What happened:

Pod that requires a certain time to drain remains in READY state while terminating, until just before it becomes fully terminated.

#### What you expected to happen:

Once a Pod is deleted, it should go into unready state (within a short time), as the documentation says:

>  If you want to be able to drain requests when the Pod is deleted, you do not necessarily need a readiness probe; **on deletion, the Pod automatically puts itself into an unready state regardless of whether the readiness probe exists. The Pod remains in the unready state while it waits for the containers in the Pod to stop.**
>
> https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-readiness-probe  (Emphasis is mine.)

#### How to reproduce it (as minimally and precisely as possible):

1. Create a Pod resource

```console
$ cat test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - "1000000"
    image: busybox
    name: test

$ kubectl apply -f ./test.yaml
```

`sleep` command is a good example here because `sleep` command does not handle SIGTERM and will keep running until it is killed.

2. Delete the Pod

```console
$ kubectl delete pod test
```

3. Pod keeps READY state while it waits for the container in the Pod to stop, against the doc

```console
$ kubectl get pods
NAME   READY   STATUS        RESTARTS   AGE
test   1/1     Terminating   0          44s
```

The values of Pod Condition `Ready` and `ContainersReady` also remain `true`.

#### Environment:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-gke.1000", GitCommit:"3ae0998c5052f420a17cb96bacf860ec5d6822a3", GitTreeState:"clean", BuildDate:"2021-04-29T09:17:16Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```

I also confirmed with `v1.19.9-gke.1400`.

- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`)

```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=c19d150c6bd658510ec786390aec80ad476c7578
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=89
VERSION_ID=89
BUILD_ID=16108.403.15
```

- Kernel (e.g. `uname -a`):

```
Linux cs-291166234657-default-boost-vqzbq 5.4.104+ #1 SMP Fri Apr 30 09:52:02 PDT 2021 x86_64 GNU/Linux
```

- Install tools: GKE
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #110309: Kubelet Readiness Probes do not run during pod termination
### What happened?

Kubelet probes are stopped during pod termination. Readiness probes should run during termination to allow for load balancers and other controllers to observe the pod shutting down, so the pod is removed from various endpoints and services.

### What did you expect to happen?

I expect readiness probes to run during termination within the Kubelet. If the Pod has a readiness probe defined, then it should run during the pod termination and be reflected within the API.

### How can we reproduce it (as minimally and precisely as possible)?

Test pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: bash
spec:
  containers:
  - name: bash
    image: bash
    command:
    - bash
    - -c
    - "_term() { rm -f /tmp/ready ; sleep 30; exit 0; } ; trap _term SIGTERM; touch /tmp/ready ; while true; do echo \"hello\"; sleep 10; done"
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      failureThreshold: 1
      initialDelaySeconds: 5
      periodSeconds: 2
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
1.19+
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by rphillips**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
This PR builds off of @smarterclayton 's #107893 PR to fix `kubelet: Pod probes should be handled by pod worker`. The pod refactor in 2021 disabled [all probes on pod deletion](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2272-L2275). @deads2k also reported to me an [issue](https://github.com/kubernetes/kubernetes/pull/110115) where Pods were failing to report readiness status on termination. Readiness probes are important for controllers and load balancers to know when to take a pod out of service. Not reporting readiness can cause a load balancer (or controller) to react slower to a terminating pod producing 500s and other ill effects. This PR now reports the correct readiness status during termination. 

#107893 needed a test case, which this PR adds. 

#### Which issue(s) this PR fixes:
Fixes #110309

#### Does this PR introduce a user-facing change?
```release-note
Fix 1.22 regression so pods will now post their readiness during termination.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by rphillips** [comment]
cc @aojea

File: test/e2e_node/node_probe.go [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+
+			// Create Pod
+			podClient.Create(&v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: podName,
+				},
+				Spec: v1.PodSpec{
+					Containers: []v1.Container{
+						{
+							Image:   imageutils.GetE2EImage(imageutils.Perl),
```
Comment (aojea) [inline test/e2e_node/node_probe.go:52]: can we use Agnhost image instead?

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1766,10 +1772,16 @@ func (kl *Kubelet) syncTerminatingPod(ctx context.Context, pod *v1.Pod, podStatu
 	kl.statusManager.SetPodStatus(pod, apiPodStatus)
 
 	if gracePeriod != nil {
+		if *gracePeriod <= 1 {
+			// If we plan to terminate quickly, stop probes immediately, otherwise we will  wait until the pod is completely done
+			kl.probeManager.RemovePod(pod)
```
Comment (aojea) [inline pkg/kubelet/kubelet.go:1777]: should we try to optimize this?

Comment (rphillips) [reply pkg/kubelet/kubelet.go:1777]: If they are short grace period pods, then I think this is ok.

File: test/e2e_node/node_probe.go (hunk 1 above)
Comment (rphillips) [reply test/e2e_node/node_probe.go]: Fixed

File: test/e2e_node/node_probe.go [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+			podClient.Create(&v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{
+					Name: podName,
+				},
+				Spec: v1.PodSpec{
+					Containers: []v1.Container{
+						{
+							Image:   imageutils.GetE2EImage(imageutils.Agnhost),
+							Name:    podName,
+							Command: []string{"/bin/bash", "-c", "_term() { rm -f /tmp/ready ; sleep 30; exit 0; } ; trap _term SIGTERM; touch /tmp/ready ; while true; do echo \"hello\"; sleep 10; done"},
```
Comment (smarterclayton) [inline test/e2e_node/node_probe.go:54]: since this is long enough, it would be better to put it in heredoc form

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (smarterclayton) [reply pkg/kubelet/kubelet.go:1777]: Technically this is to allow a user visible difference between “stop as fast as possible”, and every other kind of stop.  We do that by clamping the grace period to this “less than or equal to one second” range, and since probe periods are quantized by seconds, 1 or below is effectively the same.  And, when someone wants to shut a bunch of pods down as fast as possible, that usually involves freeing up resources or other urgent behavior.

This should also reduce the frequency of noise on shutdown due to probes racing with termination, so it has a net benefit.

I think as long as the comment includes a bit more context about why this is ok, it should be fine.

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -1778,6 +1790,12 @@ func (kl *Kubelet) syncTerminatingPod(ctx context.Context, pod *v1.Pod, podStatu
 		return err
 	}
 
+	// Once the containers are stopped, we can stop probing for liveness and readiness.
+	// TODO: once a pod is terminal, certain probes (liveness exec) could be stopped immediately after
+	//   the detection of a container shutdown or (for readiness) after the first failure. Tracked as
+	//   https://github.com/kubernetes/kubernetes/issues/107894 although may not be worth optimizing.
+	kl.probeManager.RemovePod(pod)
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet.go:1797]: Adding this invariant to the unit tests would be good.  SyncTerminatingPod should clear probe status, and if kill container returns an error, we should have only stopped liveness probes.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (rphillips) [reply pkg/kubelet/kubelet.go]: I updated the comment in the latest push. Thanks!

File: test/e2e_node/node_probe.go (hunk 3 above)
Comment (rphillips) [reply test/e2e_node/node_probe.go]: Fixed.

File: pkg/kubelet/kubelet.go (hunk 4 above)
Comment (rphillips) [reply pkg/kubelet/kubelet.go:1801]: Thank you for the feedback. This is a good ide and I added a second test to this PR.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (aojea) [reply pkg/kubelet/kubelet.go]: @smarterclayton I've found the related issue https://github.com/kubernetes/kubernetes/pull/102025 , is 0 still having a special meaning? and we keeping its behavior with this change?

Comment (aojea) [reply pkg/kubelet/kubelet.go]: main concern is this last comment https://github.com/kubernetes/kubernetes/pull/102025#issuecomment-896327232

**Comment by aojea** [comment]
ok, the bug is worse than I thought, the pods never get unready breaking all apps that depend on the graceful shutdown 

I've verified that the test passes with this fix and fail without.

@rphillips I think that you should incorporate this commit with the e2e tests for Services in this PR
https://github.com/kubernetes/kubernetes/pull/110247/commits/cc6e7857d1f00b9dc5a760fcefcca1420d0b35e3

cc: @deads2k

**Comment by bobbypage** [comment]
Hi Ryan! Thanks for your work on this!

I tested the PR locally with the example provided in https://github.com/kubernetes/kubernetes/issues/102537

I don't think it addresses the case mentioned in https://github.com/kubernetes/kubernetes/issues/102537#issue-909658949 (i.e. a pod without a probes).

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (aojea) [reply pkg/kubelet/kubelet.go]: I've tried to follow all the graceperiods paths but I'm not able to fully comprehend it , there is this function that seems to always set it to 1
https://github.com/kubernetes/kubernetes/blob/3eadd1a9ead7a009a9abfbd603a5efd0560473cc/pkg/kubelet/pod_workers.go#L641-L671

should we make the optimization at least in a different commit, so we don't mix it with the bugfix?

File: pkg/kubelet/kubelet.go [hunk 5]
```diff
@@ -1713,6 +1713,9 @@ func (kl *Kubelet) syncPod(ctx context.Context, updateType kubetypes.SyncPodType
 	// Fetch the pull secrets for the pod
 	pullSecrets := kl.getPullSecretsForPod(pod)
 
+	// Ensure the pod is being probed
+	kl.probeManager.AddPod(pod)
```
Comment (249043822) [inline pkg/kubelet/kubelet.go:1717]: https://github.com/kubernetes/kubernetes/blob/c6970e64528ba78b74bf77b86f9b78b7b61bd0cd/pkg/kubelet/prober/prober_manager.go#L188
the `syncPod ` is reentrant, so shall we set the log level above more friendly?

Comment (rphillips) [reply pkg/kubelet/kubelet.go:1717]: This patch does not change the logic within the AddPod function.

**Comment by rphillips** [comment]
@bobbypage I looked into pods without readiness probes. From what I can find within the code, K8S has always assumed that a pod without a readiness probe stays in ready=true until it has fully terminated. This PR fixes the case where a pod is defined with a readiness probe, is being terminated, and needs to run the readiness probe on termination.

If we want to change the behavior of readiness for pods without readiness probes, then I believe we will need a different enhancement.

File: pkg/kubelet/kubelet.go (hunk 5 above)
Comment (rphillips) [reply pkg/kubelet/kubelet.go:1717]: Good point. I bumped the log level to 4 for these.

**Comment by rphillips** [comment]
Updated the issue to be https://github.com/kubernetes/kubernetes/issues/110309

File: pkg/kubelet/kubelet_pods.go [hunk 6]
```diff
@@ -1105,8 +1105,8 @@ func (kl *Kubelet) HandlePodCleanups() error {
 	}
 
 	// Stop probing pods that are not running
-	klog.V(3).InfoS("Clean up probes for terminating and terminated pods")
-	kl.probeManager.CleanupPods(runningPods)
+	klog.V(3).InfoS("Clean up probes for terminated pods")
+	kl.probeManager.CleanupPods(possiblyRunningPods)
```
Comment (bobbypage) [inline pkg/kubelet/kubelet_pods.go:1109]: just for my own understanding - `possiblyRunningPods` refers to pods which are in progress of terminating right? Why do we want need to stop probing here in addition to logic in `syncPod`?

**Comment by bobbypage** [comment]
> @bobbypage I looked into pods without readiness probes. From what I can find within the code, K8S has always assumed that a pod without a readiness probe stays in ready=true until it has fully terminated. This PR fixes the case where a pod is defined with a readiness probe, is being terminated, and needs to run the readiness probe on termination.
> 
> If we want to change the behavior of readiness for pods without readiness probes, then I believe we will need a different enhancement.

ack, makes sense. Thanks for creating dedicated issue to track the particular fix in this PR. small nit: the issue in the pr description links to the PR, not the github issue (#110309) which is what you intend :)

File: pkg/kubelet/kubelet.go [hunk 7]
```diff
@@ -1743,6 +1746,9 @@ func (kl *Kubelet) syncTerminatingPod(ctx context.Context, pod *v1.Pod, podStatu
 	// manager or refresh the status of the cache, because a successful killPod will ensure we do
 	// not get invoked again
 	if runningPod != nil {
+		// Stop probing runtime pods immediately
+		kl.probeManager.RemovePod(pod)
```
[the remark this answers is not in the document]
Comment (249043822) [reply pkg/kubelet/kubelet.go:1750]: I also think this line may be useless, the reason is:
1. a runningPod which is synced from runtime could not exists in podmanager, it has no chance to run `syncPod`, so it should has no probes running
2. a runningPod terminating would not update status manager, so it would not report probe results

File: pkg/kubelet/kubelet_pods.go (hunk 6 above)
Comment (rphillips) [reply pkg/kubelet/kubelet_pods.go:1109]: HandlePodCleanups() is a goroutine which is running periodically to make sure pods are cleaned up. In my testing, 'runningPods' does not include terminating pods. This would cause the probes to be terminated prematurely (due to the natural race condition between the termination pod_worker logic and HandlePodCleanups).

I didn't want to change the logic of removing the probeManager call from HandlePodCleanups due to unknown side effects.

File: pkg/kubelet/kubelet.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (rphillips) [reply pkg/kubelet/kubelet.go:1750]: I suspect both are of you a right. I removed this line from the current patch.

File: test/e2e_node/node_probe.go [hunk 8]
```diff
@@ -0,0 +1,194 @@
...
+				return podutil.IsPodReady(pod) == false, nil
+			})
+			framework.ExpectNoError(err)
+
+			// Verify there are zero liveness failures since they are turned off
+			// during pod termination
+			items, _ := f.ClientSet.EventsV1().Events(f.Namespace.Name).List(context.Background(), metav1.ListOptions{})
+			for _, event := range items.Items {
+				if strings.Contains(event.Note, "failed liveness probe") {
+					framework.Fail("should not see liveness probe failures")
```
[the remark this answers is not in the document]
Comment (rphillips) [reply test/e2e_node/node_probe.go]: Fixed

**Comment by rphillips** [comment]
@bobbypage @249043822 I added all the requested changes. Thanks!

File: test/e2e/common/node/container_probe.go [hunk 9]
```diff
@@ -551,6 +553,168 @@ var _ = SIGDescribe("Probing container", func() {
...
+		})
+		framework.ExpectNoError(err)
+
+		// Verify there are zero liveness failures since they are turned off
+		// during pod termination
+		items, err := f.ClientSet.EventsV1().Events(f.Namespace.Name).List(context.Background(), metav1.ListOptions{})
+		framework.ExpectNoError(err)
+		for _, event := range items.Items {
+			// Search only for the pod we are interested in
+			if event.Name != podName {
```
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:710]: Is this accurate? I thought to filter for events for pod, it was necessary to check involvedObject.name == podName?

**Comment by bobbypage** [comment]
One more small question about the test added, thanks for your work on this. 

/lgtm

**Comment by aojea** [comment]
/kind regression

folks, this is a regression and has to be backported, pod readiness probes were working in 1.21

https://github.com/kubernetes/kubernetes/pull/110366#issuecomment-1145745415

I still think that the optimization should be a different commit to avoid possible regressions on the backport
https://github.com/kubernetes/kubernetes/pull/110191#discussion_r884282561

**Comment by rphillips** [comment]
@dashpole Could you do a final review pass for a lgtm? I'll create backports once we get approvals on this PR.

**Comment by rphillips** [comment]
Sorry, @bobbypage ... :)

File: test/e2e/common/node/container_probe.go [hunk 10]
```diff
@@ -551,6 +553,168 @@ var _ = SIGDescribe("Probing container", func() {
...
+							PeriodSeconds:       1,
+						},
+					},
+				},
+				TerminationGracePeriodSeconds: &terminationGracePeriod,
+			},
+		})
+
+		// verify pods are running and ready
+		err := e2epod.WaitForPodsRunningReady(f.ClientSet, f.Namespace.Name, 1, 0, 90*time.Second, map[string]string{})
```
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:687]: suggest to use framework's timeout constants f.Timeouts.PodStart instead of custom 90 seconds - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/timeouts.go#L44

File: test/e2e/common/node/container_probe.go [hunk 11]
```diff
@@ -551,6 +553,168 @@ var _ = SIGDescribe("Probing container", func() {
...
+		framework.ExpectNoError(err)
+
+		// Shutdown pod. Readiness should change to false
+		podClient.Delete(context.Background(), podName, metav1.DeleteOptions{})
+
+		// Wait for pod to go unready
+		err = wait.PollImmediate(2*time.Second, 30*time.Second, func() (bool, error) {
```
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:694]: Maybe use `f.Timeouts.PodDelete` here? - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/timeouts.go#L26

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (bobbypage) [reply pkg/kubelet/kubelet.go]: +1. As @aojea mentioned, perhaps we should include this optimization in a followup PR (or separate commit) entirely. 

https://github.com/kubernetes/kubernetes/pull/102025 did not actually merge so we don't consider "1" as a special grace period and since we plan to backport this PR to 1.23 and 1.22, it probably makes sense to avoid adding this optimization since #102025 was not merged. What do you think @rphillips ? Or is there some unintended side affects without this optimization?

File: test/e2e/common/node/container_probe.go [hunk 12]
```diff
@@ -551,6 +553,168 @@ var _ = SIGDescribe("Probing container", func() {
...
+			},
+		})
+
+		// verify pods are running and ready
+		err := e2epod.WaitForPodsRunningReady(f.ClientSet, f.Namespace.Name, 1, 0, 90*time.Second, map[string]string{})
+		framework.ExpectNoError(err)
+
+		// Shutdown pod. Readiness should change to false
+		podClient.Delete(context.Background(), podName, metav1.DeleteOptions{})
+		err = wait.PollImmediate(2*time.Second, 60*time.Second, func() (bool, error) {
```
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:611]: replace `2*time.Second` with `f.Poll` - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L113

File: test/e2e/common/node/container_probe.go (hunk 11 above)
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:694]: replace `2*time.Second` with `f.Poll` - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L113

File: test/e2e/common/node/container_probe.go [hunk 13]
```diff
@@ -551,6 +553,168 @@ var _ = SIGDescribe("Probing container", func() {
...
+				return false, err
+			}
+			// verify the pod ready status has reported not ready
+			return podutil.IsPodReady(pod) == false, nil
+		})
+		framework.ExpectNoError(err)
+
+		// Verify there are zero liveness failures since they are turned off
+		// during pod termination
+		items, err := f.ClientSet.CoreV1().Events(f.Namespace.Name).List(context.Background(), metav1.ListOptions{})
```
Comment (bobbypage) [inline test/e2e/common/node/container_probe.go:706]: nit: I think there is some latency for events to be generated, so maybe it makes sense to wrap the event check in a `gomega.Consistently` and run it for a bit of time (minute?) to ensure the event won't be generated.

**Comment by bobbypage** [comment]
Couple small nits regarding tests and also +1 to the question that @aojea raised here -  https://github.com/kubernetes/kubernetes/pull/110191#discussion_r890569998

**Comment by rphillips** [comment]
@bobbypage Thank you for the review.

I updated the tests to the constants you references and added the gomega.Consistently tweak.

I removed the graceperiod optimization since I do not know of any limitations to it.

**Comment by bobbypage** [comment]
Thanks for all the fixes and updates!

/lgtm

**Review by mrunalp — APPROVED** [review]

**Comment by aojea** [comment]
/approve

Thank you very much
