### PR TITLE
fix flake on Conformance test should ResourceQuota apply changes to a…

### LINKED ISSUE #121911: [Flaking Test] Conformance-GCE-master-kubetest2 (client rate limiter Wait returned an error)
##### Error text:
```
[FAILED] client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline
In [It] at: test/e2e/apimachinery/resource_quota.go:1191 @ 11/09/23 14:53:30.003

```

TestGrid: https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

#### Recent failures:
[11/15/2023, 5:50:05 PM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1724764199302729728)
[11/15/2023, 1:48:47 PM ci-kubernetes-gce-conformance-latest-kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1724702794104967168)
[11/15/2023, 10:47:10 AM ci-kubernetes-gce-conformance-latest-kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1724657243439239168)
[11/15/2023, 4:20:04 AM ci-kubernetes-e2e-ubuntu-gce-network-policies](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1724560355511767040)
[11/15/2023, 3:54:04 AM ci-cos-containerd-e2e-cos-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-e2e-cos-gce/1724553810191323136)

/kind flake

/sig api-machinery

### PR DESCRIPTION
**Pull request by aojea**
… resourcequota status

The test flakes when trying to verify that, after modifying the ResourceQuota status, the controller reconciles the value to the spec. However, this reconcilation only happens periodically and the default value of this loop is 12h, so is hard to test this reliably in all clusters.

/kind failing-test
/kind flake

Fixes #121911

#### Special notes for your reviewer:

See https://github.com/kubernetes/kubernetes/issues/121911#issuecomment-1817473968

```release-note
NONE
```

/priority critical-urgent

ping @kubernetes/release-managers 
/assign @liggitt @jpbetz

### CODE REVIEW

File: test/e2e/apimachinery/resource_quota.go [hunk 1]
```diff
@@ -1186,21 +1186,11 @@ var _ = SIGDescribe("ResourceQuota", func() {
 		})
 		framework.ExpectNoError(err, "failed to locate ResourceQuota %q in namespace %q", patchedResourceQuota.Name, ns)
 
-		err = wait.PollUntilContextTimeout(ctx, 5*time.Second, 5*time.Minute, true, func(ctx context.Context) (bool, error) {
```
Comment (aojea) [inline test/e2e/apimachinery/resource_quota.go:1189]: gce tests use a 3 mins value for min-sync period, kind uses kubeadm and uses a 12h value for the min-sync period.
My reading of the code is that the resource-quota-controller ignore changes to the status and reconciles it every ResyncPeriod, and this is a random value obtained from the kube-controller-manager flag min-sync-period and  is a value between min-sync-period and 2*min-sync-period.

Comment (neolit123) [reply test/e2e/apimachinery/resource_quota.go:1189]: cc @Riaankl 
https://github.com/kubernetes/kubernetes/commit/168fa73b60b625ed1e69f2cd62f850ba46a24efc
(conformance promotion)

Comment (neolit123) [reply test/e2e/apimachinery/resource_quota.go:1189]: if the resync period averages at 18h on kubeadm jobs and this part of the test is supposed to fail on the stock defaults, why is the test 99% green on kubeadm jobs?
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1189]: that part I don't understand it too, that is why I asked for reviewers that know better the resource controller, but you can follow the codepath in https://github.com/kubernetes/kubernetes/issues/121911#issuecomment-1817473968

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1189]: /hold
we should be able to answer this question, there is a `pkg/controller/resourcequota/resource_quota_monitor.go` that I don't have clear what is doing

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1189]: /hold cancel
@neolit123 now I think I got it right, thanks for the great question

File: test/e2e/apimachinery/resource_quota.go [hunk 2]
```diff
@@ -1186,21 +1186,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
 			resourceQuotaResult, err := rqClient.Get(ctx, rqName, metav1.GetOptions{})
-			framework.ExpectNoError(err)
+			if err != nil {
+				return false, nil
+			}
 
-			if apiequality.Semantic.DeepEqual(resourceQuotaResult.Spec.Hard.Cpu(), resourceQuotaResult.Status.Hard.Cpu()) {
-				gomega.Expect(*resourceQuotaResult.Status.Hard.Cpu()).To(gomega.Equal(resource.MustParse("1")), "Hard cpu value for ResourceQuota %q is %s not 1.", repatchedResourceQuota.Name, repatchedResourceQuota.Status.Hard.Cpu().String())
-				gomega.Expect(*resourceQuotaResult.Status.Hard.Memory()).To(gomega.Equal(resource.MustParse("1Gi")), "Hard memory value for ResourceQuota %q is %s not 1Gi.", repatchedResourceQuota.Name, repatchedResourceQuota.Status.Hard.Memory().String())
+			if *resourceQuotaResult.Spec.Hard.Cpu() != *resourceQuotaResult.Status.Hard.Cpu() {
```
Comment (neolit123) [inline test/e2e/apimachinery/resource_quota.go:1200]: was the semantic equality causing a problem for these Quantity structs from Cpu()?
https://github.com/kubernetes/apimachinery/blob/master/pkg/api/equality/semantic.go#L29
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L100
 
comparison by value should work fine, but it would also include the format string.

**Review by neolit123 — COMMENTED** [review]
the assertion refactor and timeout change LGTM

File: test/e2e/apimachinery/resource_quota.go [hunk 3]
```diff
@@ -1186,21 +1186,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
-
 				return true, nil
 			}
-
+			framework.Logf("ResourceQuota %q Spec and Status does not match: %#v", resourceQuotaResult.Name, resourceQuotaResult)
 			return false, nil
 		})
-		framework.ExpectNoError(err)
+		if err != nil {
+			framework.Failf("Error waiting for ResourceQuota %q to reset its Status", patchedResourceQuota.Name, err)
```
Comment (neolit123) [inline test/e2e/apimachinery/resource_quota.go:1216]:
```suggestion
			framework.Failf("Error waiting for ResourceQuota %q to reset its Status: %v", patchedResourceQuota.Name, err)
```

File: test/e2e/apimachinery/resource_quota.go (hunk 1 above)
Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1189]: updated the PR, it turns out the resyn period i other option https://github.com/kubernetes/kubernetes/issues/121911#issuecomment-1817593892

File: test/e2e/apimachinery/resource_quota.go (hunk 2 above)
Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go]: this code is much more easier to read and is much simpler

**Comment by aojea** [comment]
/retest

known flake https://github.com/kubernetes/kubernetes/issues/121865

ping @kubernetes/release-managers 

this just needs lgtm and milestone

**Review by neolit123 — COMMENTED** [review]
/lgtm
/milestone v1.29
the diff SGTM, as is.

/hold
drop the hold if you don't want to wait for release-managers or more review.

**Review by jeremyrickard — COMMENTED** [review]
/lgtm

will leave dropping the hold to @Priyankasaggu11929 and team for the release.

**Comment by Priyankasaggu11929** [comment]
/approve
(from 1.29 Release Team)

/unhold

File: test/e2e/apimachinery/resource_quota.go [hunk 4]
```diff
@@ -1186,21 +1186,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
 
-		err = wait.PollUntilContextTimeout(ctx, 5*time.Second, 5*time.Minute, true, func(ctx context.Context) (bool, error) {
+		// the resource_quota_controller ignores changes to the status so we have to wait for a full resync of the controller
+		// to reconcile the status again, this full resync is set every 5 minutes by default so we need to poll at least one
+		// minute more just in case we we start to poll just after the full resync has happened and he have to wait until
+		// next full resync.
+		// Ref: https://issues.k8s.io/121911
+		err = wait.PollUntilContextTimeout(ctx, 5*time.Second, 6*time.Minute, true, func(ctx context.Context) (bool, error) {
 			resourceQuotaResult, err := rqClient.Get(ctx, rqName, metav1.GetOptions{})
-			framework.ExpectNoError(err)
```
Comment (liggitt) [inline test/e2e/apimachinery/resource_quota.go:1191]: we don't expect the get to error, right? when would that be expected / ok?

File: test/e2e/apimachinery/resource_quota.go [hunk 5]
```diff
@@ -1186,21 +1186,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
+			if err != nil {
+				return false, nil
+			}
 
-			if apiequality.Semantic.DeepEqual(resourceQuotaResult.Spec.Hard.Cpu(), resourceQuotaResult.Status.Hard.Cpu()) {
-				gomega.Expect(*resourceQuotaResult.Status.Hard.Cpu()).To(gomega.Equal(resource.MustParse("1")), "Hard cpu value for ResourceQuota %q is %s not 1.", repatchedResourceQuota.Name, repatchedResourceQuota.Status.Hard.Cpu().String())
-				gomega.Expect(*resourceQuotaResult.Status.Hard.Memory()).To(gomega.Equal(resource.MustParse("1Gi")), "Hard memory value for ResourceQuota %q is %s not 1Gi.", repatchedResourceQuota.Name, repatchedResourceQuota.Status.Hard.Memory().String())
+			if *resourceQuotaResult.Spec.Hard.Cpu() == *resourceQuotaResult.Status.Hard.Cpu() {
```
Comment (liggitt) [inline test/e2e/apimachinery/resource_quota.go:1200]: dereferencing and comparing rather than using Quantity#Equal seems fragile

**Comment by liggitt** [comment]
did this flake just start? do we know why? this test hasn't changed in ~6 months, right?

File: test/e2e/apimachinery/resource_quota.go (hunk 4 above)
Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1191]: this is inside the poll loop,  why should we fail hard here? usually we always retry in these cases

File: test/e2e/apimachinery/resource_quota.go (hunk 5 above)
Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1200]: that is something I was wondering about, when I read the library I saw the euqality function but then in the same test I saw it was comparing the values, just for learning, what is the difference?

**Comment by aojea** [comment]
> did this flake just start? do we know why? this test hasn't changed in ~6 months, right?

my guess is that it was failing always, the analyzed failure seems correct https://github.com/kubernetes/kubernetes/issues/121911#issuecomment-1817473968 , it reconcile every 5 minutes and if the loop poll starts about that time it will not be able to sync the status on time

File: test/e2e/apimachinery/resource_quota.go (hunk 4 above)
Comment (liggitt) [reply test/e2e/apimachinery/resource_quota.go:1191]: The poll is to give the reconciler time to make the status value what we want. An unstable API server here is unexpected

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1191]: I  stand corrected, after a quick grep  I have to fully agree with you, I expected to see more retries on other tests, but it seems the norm is to fail here

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1191]: https://github.com/kubernetes/kubernetes/pull/121972

File: test/e2e/apimachinery/resource_quota.go (hunk 5 above)
Comment (neolit123) [reply test/e2e/apimachinery/resource_quota.go:1200]: my earlier comment:
https://github.com/kubernetes/kubernetes/pull/121951#discussion_r1398261216

the comparison by value is fine for now, but if the struct introduces pointer objects it would fail.

```go
package main

import "fmt"

type bar struct { i int }
type foo struct { b *bar }

func main() {
	a := &foo{b: &bar{i: 10}}
	b := &foo{b: &bar{i: 10}}
	fmt.Printf("a == b = %v", *a == *b) // a == b = false
}
```

File: test/e2e/apimachinery/resource_quota.go (hunk 4 above)
Comment (neolit123) [reply test/e2e/apimachinery/resource_quota.go:1191]: if this GET API call must be one shot and not fail then this:
```go
resourceQuotaResult, err := rqClient.Get(ctx, rqName, metav1.GetOptions{})
framework.ExpectNoError(err)
```
must be outside of the poll loop.

Comment (aojea) [reply test/e2e/apimachinery/resource_quota.go:1191]: but you have to try to get everytime, or you don't get the new data, returning an error makes the same efect and avoid panicing inside https://github.com/kubernetes/kubernetes/pull/121972

Comment (neolit123) [reply test/e2e/apimachinery/resource_quota.go:1191]: yes, and that's why this part of this PR, LGTM.

the change in https://github.com/kubernetes/kubernetes/pull/121972 is an improvement where the overall poll will know about the reported GET errors. that LGTM as well.

File: test/e2e/apimachinery/resource_quota.go (hunk 5 above)
Comment (liggitt) [reply test/e2e/apimachinery/resource_quota.go:1200]: .Equal compares equality of the values, which may or may not be identical to struct equality, depending on normalization and whether the string rendering is cached

```go
func TestCPUComparison(t *testing.T) {
	l1 := ResourceList{"cpu": resource.MustParse("1m")}
	l2 := ResourceList{"cpu": resource.MustParse(".001")}

	cpu1 := l1.Cpu()
	cpu2 := l2.Cpu()

	t.Logf("%#v", cpu1)
	t.Logf("%#v", cpu2)

	if cpu1.Equal(*cpu2) {
		t.Log("passed Equal()")
	} else {
		t.Fatal("failed Equal()")
	}

	if *cpu1 == *cpu2 {
		t.Log("passed ==")
	} else {
		t.Fatal("failed ==")
	}
}
```

outputs

```sh
=== RUN   TestCPUComparison
    resource_test.go:16: &resource.Quantity{i:resource.int64Amount{value:1, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"1m", Format:"DecimalSI"}
    resource_test.go:17: &resource.Quantity{i:resource.int64Amount{value:1, scale:-3}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"", Format:"DecimalSI"}
    resource_test.go:20: passed Equal()
    resource_test.go:28: failed ==
--- FAIL: TestCPUComparison (0.00s)
```
