### PR TITLE
Fix issue #44757: Flaky Test_AttachDetachControllerRecovery

### LINKED ISSUE #44757: Test_AttachDetachControllerRecovery is flaky
```
attach_detach_controller_test.go:275: Waiting for the volumes to attach/detach timed out: attached 2 (expected 3); detached 5 (5)
```

See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/44755/pull-kubernetes-unit/27264/ for details

### PR DESCRIPTION
**Pull request by tsmetana**
This is a fix for the issue #44757: the new attach/detach controller tests are flaky. The problem was that the testing nodes and pods were added to the API but the test was not waiting for the informers caches to sync and it might happened that some of the objects were not found since the tests use shared informers to list them.

Fixes: #44757 

cc: @jsafrane 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/attach_detach_controller_test.go [hunk 1]
```diff
@@ -196,6 +196,12 @@ func attachDetachRecoveryTestCase(t *testing.T, extraPods1 []*v1.Pod, extraPods2
 		i++
 	}
 
+	if !controller.WaitForCacheSync("attach detach", stopCh,
```
Comment (wojtek-t) [inline pkg/controller/volume/attachdetach/attach_detach_controller_test.go]: I think this should be moved above. Next to `informerFactory.Start(stopCh)`

Comment (tsmetana) [inline pkg/controller/volume/attachdetach/attach_detach_controller_test.go]: Will fix that. Thanks.

**Comment by wojtek-t** [comment]
I'm merging it manually to fix extremely flaky build.
