### PR TITLE
Deny pod admission for static pods referencing API objects

### LINKED ISSUE #103587: Kubelet should enforce that static pods do not reference other API objects
#### What happened:
I put into `/etc/kubernetes/manifests/` one defining a static pod with a `serviceAccount`, because I was wondering if this is supported (the documentation does not say, see https://github.com/kubernetes/website/issues/28611#issuecomment-876537379).  The kubelet created the pod but without giving it the relevant mount.  The kubelet did _not_ create the corresponding mirror pod.

Here is the manifest I created:
```
apiVersion: v1
kind: Pod
metadata:
  name: test5
spec:
  containers:
  - name: bb
    image: busybox
    command:
    - sleep
    - "864001"
  serviceAccountName: default
```
Here are some relevant log entries from the kubelet:
```
Jul 08 15:55:05 init1 kubelet[4229]: I0708 15:55:05.335792    4229 kubelet.go:1681] "Creating a mirror pod for static pod" pod="default/test5-init1"

Jul 08 15:55:05 init1 kubelet[4229]: E0708 15:55:05.343771    4229 kubelet.go:1683] "Failed creating a mirror pod for" err="pods \"test5-init1\" is forbidden: a mirror pod may not reference service accounts" pod="default/test5-init1"
```

#### What you expected to happen:
I expected consistent treatment --- real pod and mirror pod both exist or both do not exist.

#### How to reproduce it (as minimally and precisely as possible):
I think the above is pretty minimal.

#### Environment:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: VirtualBox x86_64 VMs with 2 virtual CPUs and 2 GB of memory
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux init1 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm v1.21.2
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sreeram-venkitesh**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Currently, mirror pod reconciliation for static pods which reference API objects will fail. However the pod itself is not denied admission and the node would be silently running the static pod's container. As discussed in https://github.com/kubernetes/kubernetes/issues/103587#issuecomment-2433035095, we want to tighten the validation here so that pod would not be running at all in the node. Currently the static pod would be running in the node while the mirror pod would not be created (which is enforced in the API as per https://github.com/kubernetes/kubernetes/issues/103587#issuecomment-1456581669). This PR updates the validation logic so that the pod is denied admission for static pods referencing API objects and make sure that the container is not created in the node.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103587

#### Special notes for your reviewer:

Notes:
- I've added a new StaticPodAdmitHandler so that this validation is done from `canAdmitPod`. This is based on @gjkim42's comment https://github.com/kubernetes/kubernetes/pull/105368#issuecomment-984576615.
- The structure of the handler and the tests were inspired from the `PredicateAdmitHandler` in [pkg/kubelet/lifecycle/predicate.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L116-L242)
- Only `hostPath` and `emptyDir` volume mounts are made valid for static pods based on @enj's comment: https://github.com/kubernetes/kubernetes/issues/103587#issuecomment-1448211779
- I've added a `StaticPodStrictValidation` feature gate with which we can toggle the changes to the validation.

Question:
- I wanted to add an e2e_node test. I was going through [test/e2e_node/mirror_pod_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/mirror_pod_test.go) since it has helpers for static pod creation etc, but I'm still figuring out the failure case where we need to assert that the pod was denied admission from the kubelet logs?

#### Does this PR introduce a user-facing change?

```release-note
Static pods that reference API objects are now denied admission by the kubelet so that static pods would not be silently running even after the mirror pod creation fails.
ACTION REQUIRED: Prior to upgrade, ensure static pods are not referencing API objects such as ServiceAccounts, ConfigMaps, Secrets, ResourceClaims, CSIDrivers, PersistentVolumeClaims, or ClusterTrustBundles.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

(The feature gate should be documented. I will update the docs PR here once opened.)
```docs

```

### CODE REVIEW

**Comment by sreeram-venkitesh** [comment]
CC @haircommander @liggitt Tagging from the discussion in the original issue. I'd love to hear what you folks think! Thanks!

**Review by lmktfy — COMMENTED** [review]
Thanks for the PR.

Should we also deny static Pods that specify `.spec.resources.claims ` and / or `.spec.resourceClaims`?

(We perhaps shouldn't assume that these claims will fail anyway).

File: pkg/kubelet/lifecycle/handlers.go [hunk 1]
```diff
@@ -231,6 +231,84 @@ func (a *appArmorAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult {
...
+			Reason:  "StaticPodInvalid",
+			Message: "Static pod cannot reference ServiceAccount",
+		}
+	}
+
+	if rejectStaticPodAdmissionBasedOnVolume(pod) {
+		return PodAdmitResult{
+			Admit:   false,
+			Reason:  "StaticPodInvalid",
+			Message: "Static pod can only have hostPath or emptyDir volume moun",
```
[the remark this answers is not in the document]
Comment (sreeram-venkitesh) [reply pkg/kubelet/lifecycle/handlers.go]: Thanks, fixed in https://github.com/kubernetes/kubernetes/pull/131837/commits/9f146455f7722b77c23b4d4b6e9424967b6a446f.

**Comment by sreeram-venkitesh** [comment]
> (We perhaps shouldn't assume that these claims will fail anyway).

True, but if they don't make sense for static pods I'm okay with denying pods with `.spec.resources.claims`  and / or `.spec.resourceClaims` too. I wonder if we'd want to let users create static pods with resource claims.

File: pkg/features/kube_features.go [hunk 2]
```diff
@@ -938,6 +938,11 @@ const (
 	// Enables the image volume source.
 	ImageVolume featuregate.Feature = "ImageVolume"
 
+	// owner: @sreeram-venkitesh
+	//
+	// Denies pod admission if static pods reference other API objects.
+	StaticPodStrictValidation featuregate.Feature = "StaticPodStrictValidation"
```
Comment (liggitt) [inline pkg/features/kube_features.go:944]: "strict" is pretty ambiguous ... let's target this specifically at static pods referencing API objects, so call this "PreventStaticPodAPIReferences" or something similar.

That will also let us make use of the same gate in the kubelet *and* in NodeRestriction admission

File: pkg/features/kube_features.go [hunk 3]
```diff
@@ -1783,6 +1788,10 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 		{Version: version.MustParse("1.31"), Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // GA in 1.31, remove in 1.33
 	},
 
+	StaticPodStrictValidation: {
+		{Version: version.MustParse("1.34"), Default: false, PreRelease: featuregate.Alpha},
```
Comment (liggitt) [inline pkg/features/kube_features.go:1792]: I would consider starting this as beta and on-by-default ... this is a bugfix with an escape hatch mitigation for a few releases

File: test/e2e/feature/feature.go [hunk 4]
```diff
@@ -445,6 +445,10 @@ var (
 	// TODO: document the feature (owning SIG, when to use this feature for a test)
 	StatefulSet = framework.WithFeature(framework.ValidFeatures.Add("StatefulSet"))
 
+	// Owner: sig-node
+	// Denies pod admission if static pods reference other API objects.
+	StaticPodStrictValidation = framework.WithFeature(framework.ValidFeatures.Add("StaticPodStrictValidation"))
```
Comment (liggitt) [inline test/e2e/feature/feature.go:450]: we don't need an e2e feature for this, there's no other configuration associated with it, *if* you write an e2e test, use `framework.WithFeatureGate(features.PreventStaticPodAPIReferences)`, etc

File: pkg/kubelet/lifecycle/handlers.go [hunk 5]
```diff
@@ -231,6 +231,84 @@ func (a *appArmorAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult {
...
 
+type StaticPodAdmitHandler struct{}
+
+func (s *StaticPodAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult {
+	pod := attrs.Pod
+
+	if !kubetypes.IsStaticPod(pod) {
+		return PodAdmitResult{Admit: true}
+	}
+
```
Comment (liggitt) [inline pkg/kubelet/lifecycle/handlers.go:242]: I think a single method that takes a pod and returns an error if the pod references API objects will be easier to ensure is called correctly. It might make sense to extract the checks done at https://github.com/kubernetes/kubernetes/blob/889cd833a2d77c32aaffaf03c0ba58b471c63309/plugin/pkg/admission/noderestriction/admission.go#L307-L340 to a method in pkg/api/pod that deals with an internal Pod.

Then the NodeRestriction admission plugin could call that, *and* the kubelet could call it from tryDecodeSinglePod / tryDecodePodList where it has an internal pod, and only hits that code path when loading static pods.

File: pkg/features/kube_features.go (hunk 3 above)
Comment (sreeram-venkitesh) [reply pkg/features/kube_features.go]: Understood. Fixed this in https://github.com/kubernetes/kubernetes/pull/131837/commits/8f86d9dd093ebfd7d4e94b7de2916a807afa17e8.

**Review by hashim21223445 — APPROVED** [review]

File: pkg/kubelet/lifecycle/handlers.go (hunk 5 above)
Comment (sreeram-venkitesh) [reply pkg/kubelet/lifecycle/handlers.go]: @liggitt Please check https://github.com/kubernetes/kubernetes/pull/131837/commits/4809d0f02193401e1f28ece8fa6569f10de525f4. I've extracted the logic to a method in `pkg/api/pod/util.go`. This is then called from both NodeRestriction admission's `admitPodCreate` and `tryDecodeSinglePod` for static pods. 

I have a question about `tryDecodeSinglePod`. Does this only process static pods? I see that this is called from `pkg/kubelet/config/file.go` and `pkg/kubelet/config/http.go`. The file one makes sense - reading static pod manifests, but I was not sure about the tryDecodeSinglePod call [here in extractFromURL](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/http.go#L115) in pkg/kubelet/config/http.go. 

One more question: Compared to my earlier approach of adding a new AdmitHandler, this logic would now be executed only when parsing static pods. The AdmitHandler approach is redundant because,it would process all pods and _then_ inside the handler check if the pod is a static pod. But we can avoid checking all the pods. Am I correct?

Comment (liggitt) [reply pkg/kubelet/lifecycle/handlers.go]: The kubelet can load static pods from file or from a non-API server URL. Both of those should have this enforcement.

doing the enforcement there would be instead of a kubelet admission handler

File: pkg/api/pod/util.go [hunk 6]
```diff
@@ -1488,3 +1489,52 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+	ErrStaticPodSecrets             = errors.New("can not create static pods that reference secrets")
+	ErrStaticPodConfigmaps          = errors.New("can not create static pods that reference configmaps")
+	ErrStaticPodClusterTrustBundles = errors.New("can not create static pods that reference clustertrustbundles")
+	ErrStaticPodInvalidVolumes      = errors.New("can not create static pods that reference volume mounts other than hostPath and emptyDir")
+	ErrStaticPodResourceClaims      = errors.New("can not create static pods that reference resourceclaims")
+)
+
+func HasAPIObjectReferences(pod *api.Pod) (bool, error) {
+	if pod.Spec.ServiceAccountName != "" {
+		return true, ErrStaticPodServiceAccount
```
Comment (liggitt) [inline pkg/api/pod/util.go:1504]:
```suggestion
		return true, "serviceaccounts"
```

File: pkg/api/pod/util.go [hunk 7]
```diff
@@ -1488,3 +1489,52 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+	}
+
+	hasSecrets := false
+	VisitPodSecretNames(pod, func(name string) (shouldContinue bool) { hasSecrets = true; return false }, AllContainers)
+	if hasSecrets {
+		return true, ErrStaticPodSecrets
```
Comment (liggitt) [inline pkg/api/pod/util.go:1510]:
```suggestion
		return true, "secrets"
```

File: pkg/api/pod/util.go [hunk 8]
```diff
@@ -1488,3 +1489,52 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+	}
+
+	for _, v := range pod.Spec.Volumes {
+		if v.HostPath == nil && v.EmptyDir == nil {
+			return true, ErrStaticPodInvalidVolumes
+		}
+	}
+
+	if len(pod.Spec.ResourceClaims) > 0 {
+		return true, ErrStaticPodResourceClaims
```
Comment (liggitt) [inline pkg/api/pod/util.go:1536]:
```suggestion
		return true, "resourceclaims"
```

File: pkg/kubelet/config/common.go [hunk 9]
```diff
@@ -144,19 +149,11 @@ func tryDecodeSinglePod(data []byte, defaultFn defaultFunc) (parsed bool, pod *v
 		return true, nil, err
 	}
 
-	for _, v := range v1Pod.Spec.Volumes {
```
Comment (liggitt) [inline pkg/kubelet/config/common.go:147]: this code is already unconditional, we don't want to drop these checks if the PreventStaticPodAPIReferences gate is toggled off, leave this in an `else` block with a comment to remove once PreventStaticPodAPIReferences is GA and locked on

File: pkg/kubelet/config/common.go [hunk 10]
```diff
@@ -144,19 +149,11 @@ func tryDecodeSinglePod(data []byte, defaultFn defaultFunc) (parsed bool, pod *v
...
-		if v.Projected == nil {
-			continue
+	if utilfeature.DefaultFeatureGate.Enabled(features.PreventStaticPodAPIReferences) {
+		// Check if pod has references to API objects
+		if _, err = podutil.HasAPIObjectReferences(newPod); err != nil {
+			return true, nil, err
```
Comment (liggitt) [inline pkg/kubelet/config/common.go:155]: wrap the returned resource in an error here, e.g.: `fmt.Errorf("static pods may not reference %s API objects")`

File: plugin/pkg/admission/noderestriction/admission.go [hunk 11]
```diff
@@ -305,38 +305,9 @@ func (p *Plugin) admitPodCreate(nodeName string, a admission.Attributes) error {
...
-		if v.PersistentVolumeClaim != nil {
-			return admission.NewForbidden(a, fmt.Errorf("node %q can not create pods that reference persistentvolumeclaims", nodeName))
-		}
-	}
-
-	if len(pod.Spec.ResourceClaims) > 0 {
-		return admission.NewForbidden(a, fmt.Errorf("node %q can not create pods that reference resourceclaims", nodeName))
+	isPodReferencingAPIObjects, err := podutil.HasAPIObjectReferences(pod)
+	if isPodReferencingAPIObjects {
+		return admission.NewForbidden(a, fmt.Errorf("node %q is not allowed to create pods referencing API objects: %w", nodeName, err))
```
Comment (liggitt) [inline plugin/pkg/admission/noderestriction/admission.go:310]:
```suggestion
		return admission.NewForbidden(a, fmt.Errorf("node %q can not create pods that reference %s API objects", nodeName, resource))
```

File: pkg/api/pod/util.go [hunk 12]
```diff
@@ -1488,3 +1489,52 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+			for _, src := range vol.Projected.Sources {
+				if src.ClusterTrustBundle != nil {
+					return true, ErrStaticPodClusterTrustBundles
+				}
+			}
+		}
+	}
+
+	for _, v := range pod.Spec.Volumes {
+		if v.HostPath == nil && v.EmptyDir == nil {
```
[the remark this answers is not in the document]
Comment (sreeram-venkitesh) [reply pkg/api/pod/util.go]: @liggitt I've fixed all the comments in https://github.com/kubernetes/kubernetes/pull/131837/commits/99fc7fa9477003f9dd6ce3d0a7831f3c2fb8c3da. 

For the list of volumes, the only new volume which isn't already in your list is the `Image` volume. I've added this to the list of volumes usable volumes without referencing API objects. Please correct me if I'm wrong here.

File: pkg/api/pod/util.go [hunk 13]
```diff
@@ -1488,3 +1489,72 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+		switch {
+		case v.AWSElasticBlockStore != nil, v.AzureDisk != nil, v.AzureFile != nil, v.CephFS != nil, v.Cinder != nil,
+			v.DownwardAPI != nil, v.EmptyDir != nil, v.FC != nil, v.FlexVolume != nil, v.Flocker != nil, v.GCEPersistentDisk != nil,
+			v.GitRepo != nil, v.Glusterfs != nil, v.HostPath != nil, v.Image != nil, v.ISCSI != nil, v.NFS != nil, v.PhotonPersistentDisk != nil,
+			v.PortworxVolume != nil, v.Quobyte != nil, v.RBD != nil, v.ScaleIO != nil, v.StorageOS != nil, v.VsphereVolume != nil:
+			return false, "", nil
+		case v.ConfigMap != nil:
+			return true, "configmap volumes", nil
+		case v.Secret != nil:
+			return true, "secret volumes", nil
```
Comment (liggitt) [inline pkg/api/pod/util.go:1522]:
```suggestion
			return true, "secrets (via secret volumes)", nil
```

File: pkg/kubelet/config/common.go [hunk 14]
```diff
@@ -144,19 +151,31 @@ func tryDecodeSinglePod(data []byte, defaultFn defaultFunc) (parsed bool, pod *v
...
-		if v.Projected == nil {
-			continue
+	if utilfeature.DefaultFeatureGate.Enabled(features.PreventStaticPodAPIReferences) {
+		// Check if pod has references to API objects
+		_, resource, err := podutil.HasAPIObjectReference(newPod)
+		if err != nil {
+			return true, nil, err
 		}
+		if resource != "" {
+			return true, nil, fmt.Errorf("static pods may not reference %s API objects", resource)
```
Comment (liggitt) [inline pkg/kubelet/config/common.go:161]:
```suggestion
			return true, nil, fmt.Errorf("static pods may not reference %s", resource)
```

**Comment by sreeram-venkitesh** [comment]
@liggitt Please take a look!

File: pkg/api/pod/util.go [hunk 15]
```diff
@@ -1488,3 +1489,73 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+			v.PortworxVolume != nil, v.Quobyte != nil, v.RBD != nil, v.ScaleIO != nil, v.StorageOS != nil, v.VsphereVolume != nil:
+			continue
+		case v.ConfigMap != nil:
+			return true, "configmaps (via configmap volumes)", nil
+		case v.Secret != nil:
+			return true, "secrets (via secret volumes)", nil
+		case v.CSI != nil:
+			return true, "csidrivers (via CSI volumes)", nil
+		case v.Glusterfs != nil:
+			return true, "glusterfs volumes", nil
```
Comment (liggitt) [inline pkg/api/pod/util.go]:
```suggestion
			return true, "endpoints (via glusterFS volumes)", nil
```

File: pkg/kubelet/config/common.go [hunk 16]
```diff
@@ -144,19 +147,31 @@ func tryDecodeSinglePod(data []byte, defaultFn defaultFunc) (parsed bool, pod *v
...
+	if utilfeature.DefaultFeatureGate.Enabled(features.PreventStaticPodAPIReferences) {
+		// Check if pod has references to API objects
+		_, resource, err := podutil.HasAPIObjectReference(newPod)
+		if err != nil {
+			return true, nil, err
 		}
+		if resource != "" {
+			return true, nil, fmt.Errorf("static pods may not reference %s", resource)
+		}
+	} else {
```
Comment (liggitt) [inline pkg/kubelet/config/common.go:159]: also add this block to `tryDecodePodList`, looping over the pods decoded from the list and checking each one

File: pkg/api/pod/util.go [hunk 17]
```diff
@@ -1488,3 +1489,73 @@ func hasRestartableInitContainerResizePolicy(podSpec *api.PodSpec) bool {
...
+		return true, "configmaps", nil
+	}
+
+	if len(pod.Spec.ResourceClaims) > 0 {
+		return true, "resourceclaims", nil
+	}
+
+	for _, v := range pod.Spec.Volumes {
+		switch {
+		case v.AWSElasticBlockStore != nil, v.AzureDisk != nil, v.AzureFile != nil, v.CephFS != nil, v.Cinder != nil,
```
Comment (liggitt) [inline pkg/api/pod/util.go]: double-checking this list, it looks like AzureFile requires specifying a secret:

https://github.com/kubernetes/kubernetes/blob/0154f8a222c38d5808f1aecf218379cedf15e8a7/pkg/apis/core/validation/validation.go#L1501-L1505

so move that to a forbidden case

```go
case v.AzureFile != nil:
  return true, "secrets (via azureFile volumes)", nil
```

**Comment by sreeram-venkitesh** [comment]
@liggitt Can I squash and clean up the commits here?

**Comment by liggitt** [comment]
yup, looks good to squash, thanks!

**Comment by BenTheElder** [comment]
> As discussed in https://github.com/kubernetes/kubernetes/issues/103587#issuecomment-2433035095, we want to tighten the validation here so that pod would not be running at all in the node. Currently the static pod would be running in the node while the mirror pod would not be created (which is enforced in the API as per https://github.com/kubernetes/kubernetes/issues/103587#issuecomment-1456581669). This PR updates the validation logic so that the pod is denied admission for static pods referencing API objects and make sure that the container is not created in the node.

Were these pods working correctly, other than the mirror pod not showing? 

IIRC we kinda indicated that mirror pods were best effort and not necessarily 100% up to date previously.

I think there's a big difference if these references never worked or if they just weren't reflected as mirror pods..

It sounds like in https://github.com/kubernetes/kubernetes/issues/103587 the context is that these pods never worked as intended.

I think we should clarify that in the release note, IMHO "the mirror pod fails to create" is far less interesting as a user (consider also [standalone kubelet](https://kubernetes.io/docs/tutorials/cluster-management/kubelet-standalone/)) than "the pod never actually mounted this and now we'll fail if you make an invalid reference" (needs some word-smithing)

**Comment by BenTheElder** [comment]
This is also probably an "action required" and/or "urgent upgrade notes" release note @kubernetes/release-team-docs  since those pods were silently permitted before and will now fail to admit?

And you likely need to take action before upgrade, since these are static pods on disk that may e.g. be hosting your control plane.

**Comment by liggitt** [comment]
Updated the description to add an "Action required" line and label.

**Comment by BenTheElder** [comment]
> Updated the description to add an "Action required" line and label.

Does that get synced into the 1.34 changelog automatically at this stage in the cycle?

Should we mention that these would've been silently ignored previously and therefore are safe to drop?

**Comment by BenTheElder** [comment]
x-ref: https://github.com/kubernetes/website/pull/51877#discussion_r2277577623

I think at least the release blog should make it clear that users can just remove these because they weren't doing anything before anyhow.

**Comment by lmktfy** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/133535 because I think we should clear up the story about `.spec.priority` vs `.spec.priorityClassName` for static Pods.

Doesn't need resolving for the release notes, but it is an open problem area (even if the answer is "we've already decided what to do, now let's document that properly").

**Comment by liggitt** [comment]
(fwiw, this PR didn't modify any behavior related to priority or priorityClassName ... agree we should think through what *should* happen and make it clear in documentation / tested behavior, etc)

**Comment by BenTheElder** [comment]
I still don't see this highlighted in action-required /urgent upgrade notice for: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.34.md#changelog-since-v1330

cc @kubernetes/release-team-docs @kubernetes/release-team
