### PR TITLE
Scheduler: Fix GatedPods metric desync in unschedulable queue

### LINKED ISSUE #133464: GatedPods metric negative
### What happened?

Kube-Scheduler currently provides a PreEnqueue plugin that prevents pods from entering ActiveQ or BackoffQ before they meet the scheduling requirements. This plugin is currently used to support the SchedulingGate feature. However, the Kube-Scheduler implementation does not seem to account for the possibility of pods becoming Gated from non-Gated state, resulting in some anomalies in GatedPods metrics. 

The problematic code is as follows. When GatedBefore is false and PreEnqueue returns a failure, a pod is generated with the metric "UnschedulablePods" but the actual podInfo.Gated = true. When this pod is deleted, the Gated metric may become negative.

```go
func (p *PriorityQueue) moveToActiveQ(logger klog.Logger, pInfo *framework.QueuedPodInfo, event string) bool {
	gatedBefore := pInfo.Gated()
	// If SchedulerPopFromBackoffQ feature gate is enabled,
	// PreEnqueue plugins were called when the pod was added to the backoffQ.
	// Don't need to repeat it here when the pod is directly moved from the backoffQ.
	if !p.isPopFromBackoffQEnabled || event != framework.BackoffComplete {
		p.runPreEnqueuePlugins(context.Background(), pInfo)
	}

	added := false
	p.activeQ.underLock(func(unlockedActiveQ unlockedActiveQueuer) {
		if pInfo.Gated() {
			// Add the Pod to unschedulablePods if it's not passing PreEnqueuePlugins.
			if unlockedActiveQ.has(pInfo) {
				return
			}
			if p.backoffQ.has(pInfo) {
				return
			}
			if p.unschedulablePods.get(pInfo.Pod) != nil {
				return
			}
			p.unschedulablePods.addOrUpdate(pInfo, event)
			logger.V(5).Info("Pod moved to an internal scheduling queue, because the pod is gated", "pod", klog.KObj(pInfo.Pod), "event", event, "queue", unschedulableQ)
			return
		}
		if pInfo.InitialAttemptTimestamp == nil {
			now := p.clock.Now()
			pInfo.InitialAttemptTimestamp = &now
		}

		unlockedActiveQ.add(pInfo, event)
		added = true

		p.unschedulablePods.delete(pInfo.Pod, gatedBefore)
		p.backoffQ.delete(pInfo)
		logger.V(5).Info("Pod moved to an internal scheduling queue", "pod", klog.KObj(pInfo.Pod), "event", event, "queue", activeQ)
		if event == framework.EventUnscheduledPodAdd.Label() || event == framework.EventUnscheduledPodUpdate.Label() {
			p.AddNominatedPod(logger, pInfo.PodInfo, nil)
		}
	})
	return added
}
```

### What did you expect to happen?

GatedPods Metric should be correct!

### How can we reproduce it (as minimally and precisely as possible)?

Implement a custom PreEnqueue Plugin, attempting to update it to make it gated from ungated, then delete it.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by vshkrabkov**
Previously, when a Pod residing in the 'unschedulablePods' queue was updated and subsequently rejected by PreEnqueue plugins (returning 'Wait'), the logic in 'moveToActiveQ' would return early because the Pod was already present in the queue.

This caused the 'scheduler_gated_pods_total' metric to fail to increment, leading to metric inconsistencies (and potentially negative values upon Pod deletion).

This change adds a check to detect the transition from Ungated to Gated. If detected, the Pod is removed and re-added to the queue to ensure metrics are correctly swapped (Unschedulable-- and Gated++).

Added regression test 'TestSchedulingQueueMetrics_UngatedToGated' to verify the fix.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes a logic error where the Gated pods metric failed to increment when a Pod transitioned from Ungated to Gated while residing in the unschedulablePods queue.

Previously, the moveToActiveQ function would return early if the pod was already present in unschedulablePods. This optimization incorrectly assumed that the pod's state had not changed. However, if an Update() event causes PreEnqueue plugins to reject the pod (returning Wait), the pod logically transitions from "Unschedulable" to "Gated." The early return caused the scheduler to skip the necessary metric swap (decrementing unschedulable metric and incrementing gated metric), leading to metric inconsistencies.

This change explicitly handles the Ungated -> Gated transition by re-adding the pod to the queue to update the metrics correctly.

#### Which issue(s) this PR is related to:
Fixes #133464

#### Special notes for your reviewer:
Added a reproduction test case TestSchedulingQueueMetrics_UngatedToGated which manually injects a pod into the unschedulable queue to simulate the specific state transition where the bug manifests.

#### Does this PR introduce a user-facing change?
```release-note
Fixed a bug where the Gated pods metric was not updated when a Pod transitioned from Unschedulable to Gated during an update.
```

### CODE REVIEW

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 1]
```diff
@@ -656,6 +656,11 @@ func (p *PriorityQueue) moveToActiveQ(logger klog.Logger, pInfo *framework.Queue
...
 			}
 			if p.unschedulablePods.get(pInfo.Pod) != nil {
+				// If the pod changed from Ungated to Gated, re-add it to update metrics (Unschedulable-- -> Gated++).
+				if !gatedBefore {
+					p.unschedulablePods.delete(pInfo.Pod, gatedBefore)
+					p.unschedulablePods.addOrUpdate(pInfo, event)
+				}
 				return
 			}
 			p.unschedulablePods.addOrUpdate(pInfo, event)
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: Maybe we could split the `unschedulablePods.addOrUpdate` method to `add` and `update` and handle the metric appropriately within these methods?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 2]
```diff
@@ -1544,6 +1545,70 @@ func (pl *preEnqueuePlugin) PreEnqueue(ctx context.Context, p *v1.Pod) *fwk.Stat
 	return fwk.NewStatus(fwk.UnschedulableAndUnresolvable, "pod name not in allowlists")
 }
 
+// TestSchedulingQueueMetrics_UngatedToGated verifies that metrics are correctly updated (Unschedulable--/Gated++)
+// when an Update event causes a Pod to transition from the unschedulable queue to the gated queue,
+// preventing the "silent return" bug where GatedPods failed to increment.
+func TestSchedulingQueueMetrics_UngatedToGated(t *testing.T) {
+	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SchedulerPopFromBackoffQ, false)
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: What about SchedulerPopFromBackoffQ enabled and the moveToBackoffQ method?

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 1 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: I believe the issue is specifically about the metric accounting during the `Unschedulable <-> Gated` transition, rather than the `addOrUpdate` logic itself. Since the Pod is already in the queue, we don't need a full update, we only need to correct the metrics. I opted for a dedicated helper function to handle this transition explicitly to avoid adding complexity to the generic storage method. WDYT?

Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: In general, I don't like having multi-purpose function like this `addOrUpdate`. Moreover, do we need to expose the information about metric to the caller? How to be sure, the contributor that would add next unschedulablePods mutation place remember to call updateMetricsOnStateChange?

I think the full update is not a problem, as it's just writing to a map and the pod is in fact updated. Its `Gated` field changes 😄

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 3]
```diff
@@ -656,6 +656,7 @@ func (p *PriorityQueue) moveToActiveQ(logger klog.Logger, pInfo *framework.Queue
 				return
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go:656]: This doesn't belong to this PR, but:
Every time I read this func (especially this anonymous func here) I have trouble understanding what it does, and once I figure it out, I forget it before the next time :face_with_diagonal_mouth:

Do you think you could add some comments explaining what this code does?
Could be a separate PR, could be here - I don't mind either way.
Thanks!

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 4]
```diff
@@ -1544,6 +1545,112 @@ func (pl *preEnqueuePlugin) PreEnqueue(ctx context.Context, p *v1.Pod) *fwk.Stat
 	return fwk.NewStatus(fwk.UnschedulableAndUnresolvable, "pod name not in allowlists")
 }
 
+func TestSchedulingQueueMetrics_UngatedToGated_Transitions(t *testing.T) {
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: I'm not an expert on style guide, so this is more of a question than a comment - why do you put an underscore between `UngatedToGated` and `Transitions`?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 5]
```diff
@@ -1544,6 +1545,112 @@ func (pl *preEnqueuePlugin) PreEnqueue(ctx context.Context, p *v1.Pod) *fwk.Stat
...
+	tests := []struct {
+		name           string
+		featureEnabled bool
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]:
```suggestion
		popFromBackoffQEnabled bool
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 6]
```diff
@@ -1544,6 +1545,112 @@ func (pl *preEnqueuePlugin) PreEnqueue(ctx context.Context, p *v1.Pod) *fwk.Stat
...
+			name:           "Feature Enabled, Backoff active, moves to BackoffQ",
+			featureEnabled: true,
+			forceBackoff:   true, // Feature is ON, pod is waiting, so it hits Backoff path
+		},
+	}
+
+	for _, tc := range tests {
+		t.Run(tc.name, func(t *testing.T) {
+			featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SchedulerPopFromBackoffQ, tc.featureEnabled)
+			legacyregistry.Reset()
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: how about initializing and resetting particular metrics similar to other tests, for consistency?
https://github.com/kubernetes/kubernetes/blob/5bcb7599736327cd8c6d23e398002354a6e40f68/pkg/scheduler/backend/queue/scheduling_queue_test.go#L3782

`metrics.Register()` is called in init() so the line above would be sufficient

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 7]
```diff
@@ -1544,6 +1545,112 @@ func (pl *preEnqueuePlugin) PreEnqueue(ctx context.Context, p *v1.Pod) *fwk.Stat
...
 }
 
+func TestSchedulingQueueMetrics_UngatedToGated_Transitions(t *testing.T) {
+	tests := []struct {
+		name           string
+		featureEnabled bool
+		forceBackoff   bool // If true, sets timestamps to FUTURE to force moveToBackoffQ
+	}{
+		{
+			name:           "Feature Disabled, always moves to ActiveQ",
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: What if you tested all gated/ungated transitions here? There is a test that verifies some parts of this logic here
https://github.com/kubernetes/kubernetes/blob/5bcb7599736327cd8c6d23e398002354a6e40f68/pkg/scheduler/backend/queue/scheduling_queue_test.go#L3294

but it would be nice to have the specific logic related to the "gated" metric all tested here.

**Review by ania-borowiec — COMMENTED** [review]
Welcome to kubernetes! :)
My comments below

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 3 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go:656]: Btw, these checks for presence in activeQ or backoffQ seem unnecessary - the pod shouldn't be there. Maybe this could be removed to simplify the code.

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 4 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: I separated the transition types to improve readability and make them easier to recognize at a glance. However, I am not a style expert too 😄. If this violates standard conventions, I am happy to merge them.

Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Haha, no need to change it - I don't think there are strict rules for test naming within pkg/scheduler :)  Thanks for explaining!

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 6 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: There isn't `Reset()` method for `GaugeMetric` interface. I can reset value using `*.Set(0.0)`.

Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: That should work for the purpose of this test :+1:

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 7 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Good point. Reused existing testing logic.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 3 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go:656]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 7 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Cool! Are you able to use these tests to verify the Gated -> Ungated transition as well? As in, to check that after ungating the metric value is 0?

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 1 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Sorry for a late reply. Generally speaking, I don't like multi-purpose functions such as `addOrUpdate` and that's why the activeQ and backoffQ now have this split into `add` and `update`.

How can we be sure that the contributor who adds another unschedulablePods mutation remembers to call `updateMetricsOnStateChange` and understand when it's really needed? Do we even need to share metric information outside the unschedulablePods data structure?

I think a full update is not a problem, because it only involves writing data to the map

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 7 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Good point, It's doable. So I added 3 additional test cases to verify Ungated -> Gated -> Ungated transition.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 1 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: I agree with you that we should strictly hide `updateMetricsOnStateChange` inside the `unschedulableQ`. It’s risky to rely on contributors to remember to call it externally every time they mutate the state.

However, I believe keeping `addOrUpdate` is the right move here for two main reasons:
1. Encapsulation of State Logic: If we remove `addOrUpdate`, we force every high-level caller to implement the 'Check-Then-Act' logic (check if it exists, then decide to call Add or Update).
2. Code Duplication: Internally, the logic for adding and updating is nearly identical - getting the key and inserting it into the map (as you can see the map is working into the similar manner, it doesn't have specific method for updating or adding). Since a full map update is cheap, `addOrUpdate` solves the duplicate code problem efficiently without performance penalties.

WDYT?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 8]
```diff
@@ -3516,32 +3525,191 @@ scheduler_pending_pods{queue="unschedulable"} 20
...
+		},
+		{
+			name: "Gated metric should be 0 when Ungated -> Gated -> Ungated (ActiveQ) transition",
+			operations: []operation{
+				addPodUnschedulablePods,
+				moveClockForward,
+				updatePluginToGateAllPods,
+				updatePodQueueable,
+				updatePluginToUngateAllPods,
+				updatePodQueueable,
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go:3635]: IIUC we repeat updatePodQueueable to update the pod and make it re-enter Preenqueue.
But in this case the second updatePodQueueable would be a no-op, because the labels are already there?

If my understanding is correct, how about using flushUnscheduledQ instead of the second updatePodQueueable for clarity?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 9]
```diff
@@ -3516,32 +3525,191 @@ scheduler_pending_pods{queue="unschedulable"} 20
...
+`,
+		},
+		{
+			name: "Gated metric should be 0 when Ungated -> Gated -> Ungated (BackoffQ) transition",
+			operations: []operation{
+				addPodUnschedulablePods,
+				updatePluginToGateAllPods,
+				updatePodQueueable,
+				updatePluginToUngateAllPods,
+				updatePodQueueable,
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go:3663]: Flush wouldn't work here, though, because it moves the clock :(

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 7 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Thank you! :smile:

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 3 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go:656]:
```
			operations: []operation{
				addPodActiveQ,
				updatePluginToGateAllPods,
				addPodActiveQ,
				updatePluginToUngateAllPods,
				updatePodQueueable,
			},
			operands: [][]*framework.QueuedPodInfo{
				pInfos[:1],
				{nil},
				pInfos[:1],
				{nil},
				pInfos[:1],
			},
```
In this test case, I add the same pod twice. Between the two additions, I change the state from Ungated to Gated.

Without the `unclockedActiveQ.has` check, the same pod ends up in both `activeQ` and `UnschedulableQ` simultaneously. 

While mentioned check prevents the pod from occupying two queues, it causes the second addition to ignore the fact that the Plugin was updated to gate the pod. Consequently, we end up with a result of Active: 1 and Gated: 0 after the second `Add` method invocation.

I am not sure if this represents a real-world scenario.
For `backoffQ.has` I didn't find any strange cases.

@ania-borowiec, @macsko

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 10]
```diff
@@ -850,7 +846,7 @@ func (p *PriorityQueue) addUnschedulableWithoutQueueingHint(logger klog.Logger,
 			}
 		}
 	} else {
-		p.unschedulablePods.addOrUpdate(pInfo, framework.ScheduleAttemptFailure)
+		p.unschedulablePods.addOrUpdate(pInfo, false, framework.ScheduleAttemptFailure)
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go]:
```suggestion
		p.unschedulablePods.addOrUpdate(pInfo, false /* pod was not gated before */, framework.ScheduleAttemptFailure)
```

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 11]
```diff
@@ -1100,7 +1096,7 @@ func (p *PriorityQueue) Update(logger klog.Logger, oldPod, newPod *v1.Pod) {
 		}
 
 		// Pod update didn't make it schedulable, keep it in the unschedulable queue.
-		p.unschedulablePods.addOrUpdate(pInfo, framework.EventUnscheduledPodUpdate.Label())
+		p.unschedulablePods.addOrUpdate(pInfo, false, framework.EventUnscheduledPodUpdate.Label())
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: same as above

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 12]
```diff
@@ -1192,7 +1188,7 @@ func (p *PriorityQueue) MoveAllToActiveOrBackoffQueue(logger klog.Logger, event
 // NOTE: this function assumes lock has been acquired in caller
 func (p *PriorityQueue) requeuePodWithQueueingStrategy(logger klog.Logger, pInfo *framework.QueuedPodInfo, strategy queueingStrategy, event string) string {
 	if strategy == queueSkip {
-		p.unschedulablePods.addOrUpdate(pInfo, event)
+		p.unschedulablePods.addOrUpdate(pInfo, false, event)
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: same as above

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 10 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Please also add a comment justifying that this in fact will always be `false`

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 13]
```diff
@@ -1198,7 +1198,7 @@ func TestPriorityQueue_Update(t *testing.T) {
 				pInfo := q.newQueuedPodInfo(medPriorityPodInfo.Pod, queuePlugin)
 				// needs to increment to make the pod backing off
 				pInfo.UnschedulableCount++
-				q.unschedulablePods.addOrUpdate(pInfo, framework.EventUnscheduledPodAdd.Label())
+				q.unschedulablePods.addOrUpdate(pInfo, false, framework.EventUnscheduledPodAdd.Label())
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go:1201]: I know that you just updated the function call here with the additional arg, but :smile: 
I had a lot of trouble understanding the title of this test and the next. Because I didn't understand how a pod can be "backing off" when it's not in BackoffQ. Then I realized that it's not about an operation / state in unschedulable queue, but it's about re-entering activeQ after a failed attempt.

Can you please rephrase those titles, or add some comments there? Something along the suggestion below, or something else you find appropriate

```
name: "when updating a pod which is in unschedulable queue and the pod's backoff period has not yet passed since its last failed scheduling attempt, it will be moved to backoff queue",
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 9 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:3663]: Okay, so... For the sake of clarity:
Please use flush in the test "Gated metric should be 0 when Ungated -> Gated -> Ungated (ActiveQ) transition"
and please leave updatePodQueueable here, with a short comment why flush can't work here
and the same for the test "Gated metric should be 0 when Ungated -> Gated -> Ungated transition, when popFromBackoffQ is disabled"

Thank you!

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 3 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go:656]: `addPodActiveQ` can be only called by an event handler when the pod is added to the cluster. It can't happen twice for the same pod, so I think this test case is impossible

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go:656]: Ah, ok in this case I didn't find any other possibilities where we can reach these states, so make sense to remove these checks.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 10 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 12 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 13 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:1201]: Done

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 11 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 14]
```diff
@@ -648,18 +648,10 @@ func (p *PriorityQueue) moveToActiveQ(logger klog.Logger, pInfo *framework.Queue
 	added := false
 	p.activeQ.underLock(func(unlockedActiveQ unlockedActiveQueuer) {
 		if pInfo.Gated() {
-			// Add the Pod to unschedulablePods if it's not passing PreEnqueuePlugins.
-			if unlockedActiveQ.has(pInfo) {
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go:652]: Since we don't use the `unlockedActiveQ.has` method in the current version, you can consider changing the activeQ interface and just use `activeQ.add` below without using `activeQ.underLock`. This could be done in a separate PR. Maybe you could also move these activeQ, backoffQ and unschedulablePods checks removal to that new PR as they are not totally related to this PR.

File: pkg/scheduler/backend/queue/unschedulable_pods.go [hunk 15]
```diff
@@ -43,9 +43,35 @@ func newUnschedulablePods(unschedulableRecorder, gatedRecorder metrics.MetricRec
...
+		}
+	}
+}
+
 // addOrUpdate adds a pod to the unschedulable podInfoMap.
 // The event should show which event triggered the addition and is used for the metric recording.
-func (u *unschedulablePods) addOrUpdate(pInfo *framework.QueuedPodInfo, event string) {
+func (u *unschedulablePods) addOrUpdate(pInfo *framework.QueuedPodInfo, gatedBefore bool, event string) {
 	podID := u.keyFunc(pInfo.Pod)
 	if _, exists := u.podInfoMap[podID]; !exists {
```
Comment (macsko) [inline pkg/scheduler/backend/queue/unschedulable_pods.go]: Maybe flip the logic, i.e. check the `true` case first:
```go
	if _, exists := u.podInfoMap[podID]; exists {
		u.updateMetricsOnStateChange(gatedBefore, pInfo.Gated())
	} else {
		if pInfo.Gated() && u.gatedRecorder != nil {
			u.gatedRecorder.Inc()
		} else if !pInfo.Gated() && u.unschedulableRecorder != nil {
			u.unschedulableRecorder.Inc()
		}
		metrics.SchedulerQueueIncomingPods.WithLabelValues("unschedulable", event).Inc()
	}
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 8 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:3635]: The second update will trigger `moveToActiveQ` via the requeue method because of enabled `SchedulingQueueHint`.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/backend/queue/scheduling_queue.go#L1073

File: pkg/scheduler/backend/queue/unschedulable_pods.go [hunk 16]
```diff
@@ -43,9 +43,35 @@ func newUnschedulablePods(unschedulableRecorder, gatedRecorder metrics.MetricRec
...
 		if pInfo.Gated() && u.gatedRecorder != nil {
```
Comment (macsko) [inline pkg/scheduler/backend/queue/unschedulable_pods.go:79]: Possible future improvement: get rid of the nil checks for the `gatedRecorder` and `unschedulableRecorder`. These cna be nil only in the test, so we could mock them instead. This could be done in a separate PR

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 17]
```diff
@@ -1190,9 +1185,9 @@ func (p *PriorityQueue) MoveAllToActiveOrBackoffQueue(logger klog.Logger, event
 // It returns the queue name Pod goes.
 //
 // NOTE: this function assumes lock has been acquired in caller
-func (p *PriorityQueue) requeuePodWithQueueingStrategy(logger klog.Logger, pInfo *framework.QueuedPodInfo, strategy queueingStrategy, event string) string {
+func (p *PriorityQueue) requeuePodWithQueueingStrategy(logger klog.Logger, pInfo *framework.QueuedPodInfo, strategy queueingStrategy, event string, gatedBefore bool) string {
 	if strategy == queueSkip {
-		p.unschedulablePods.addOrUpdate(pInfo, event)
+		p.unschedulablePods.addOrUpdate(pInfo, gatedBefore, event)
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: Can't we just do?
```suggestion
		p.unschedulablePods.addOrUpdate(pInfo, pInfo.Gated(), event)
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 18]
```diff
@@ -3342,13 +3351,13 @@ func TestPendingPodsMetric(t *testing.T) {
...
-scheduler_pending_pods{queue="gated"} 10
-scheduler_pending_pods{queue="unschedulable"} 20
-`,
+		# HELP scheduler_pending_pods [STABLE] Number of pending pods, by the queue type. 'active' means number of pods in activeQ; 'backoff' means number of pods in backoffQ; 'unschedulable' means number of pods in unschedulablePods that the scheduler attempted to schedule and failed; 'gated' is the number of unschedulable pods that the scheduler never attempted to schedule because they are gated.
+		# TYPE scheduler_pending_pods gauge
+		scheduler_pending_pods{queue="active"} 30
+		scheduler_pending_pods{queue="backoff"} 0
+		scheduler_pending_pods{queue="gated"} 10
+		scheduler_pending_pods{queue="unschedulable"} 20
+		`,
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Do we need these indentation changes?

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 17 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: We can miss metrics in this case, If pod doesn't belong to any queue and has `gated = true`.

Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: What metrics do you have in mind? This new arg is not used for the add path, but only for update.

Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Is there a scenario where we should pass a different value than `pInfo.Gated()` when calling `requeuePodWithQueueingStrategy`?

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: In `AddUnschedulableIfNotPresent`, if execution reaches the bottom, we know the Pod is not currently in any queue.

If we pass `gatedBefore = pInfo.Gated()` (and the pod is effectively Gated), the updateMetrics function receives `old=true` and `new=true`. Because the values match, it assumes no state change occurred and fails to increment the 'Gated' metric.

We must pass false to ensure the metric transitions correctly from 'Non-existent' to 'Gated'.

```
	queue := p.requeuePodWithQueueingStrategy(logger, pInfo, schedulingHint, framework.ScheduleAttemptFailure)
	logger.V(3).Info("Pod moved to an internal scheduling queue", "pod", klog.KObj(pod), "event", framework.ScheduleAttemptFailure, "queue", queue, "schedulingCycle", podSchedulingCycle, "hint", schedulingHint, "unschedulable plugins", rejectorPlugins)
	if queue == activeQ || (p.isPopFromBackoffQEnabled && queue == backoffQ) {
		// When the Pod is moved to activeQ, need to let p.cond know so that the Pod will be pop()ed out.
		p.activeQ.broadcast()
	}
```

This assumes that pInfo can carry a Gated state (via GatingPlugin) before it is actually added to `unschedulablePods`.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 14 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go:652]: Good point. We can create refactoring issue and propose described changes.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 17 above)
Comment (macsko) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Maybe I don't understand something, but in `AddUnschedulableIfNotPresent` the pod is **not** in any queue. In that case, in `requeuePodWithQueueingStrategy`, the `unschedulablePods.addOrUpdate` is expected to **add** a pod to the `unschedulablePods`, not update it there. In case of adding, we **only increment** the metrics based on the `Gated()` value, i.e., don't care about the `gatedBefore`.

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Yes, sure, my bad. You are correct, we have empty check into `addOrUpdate`. Will clear this code snippet.

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 9 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:3663]: Nvm this is resolved

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 8 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:3635]: Thank you for bearing with me :smile: and for pointing me to the code. Yes, this is what I was missing :slightly_smiling_face: 
This comment is resolved

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 13 above)
Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:1201]: not done?

**Review by ania-borowiec — COMMENTED** [review]
Looks good, just the leftover comment

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 19]
```diff
@@ -1192,7 +1193,7 @@ func (p *PriorityQueue) MoveAllToActiveOrBackoffQueue(logger klog.Logger, event
 // NOTE: this function assumes lock has been acquired in caller
 func (p *PriorityQueue) requeuePodWithQueueingStrategy(logger klog.Logger, pInfo *framework.QueuedPodInfo, strategy queueingStrategy, event string) string {
 	if strategy == queueSkip {
-		p.unschedulablePods.addOrUpdate(pInfo, event)
+		p.unschedulablePods.addOrUpdate(pInfo, false /* the Pod was absent from all queues */, event)
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: Why this really can't be `p.unschedulablePods.addOrUpdate(pInfo, pInfo.Gated(), event)`?

When calling this in `PriorityQueue.Update()`, pod exists in `unschedulablePods` and can be gated. So, when passing `false` here, the metrics can be incorrectly updated

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Make sense, fixed

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 13 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:1201]: Apologies, I got a bit lost in the comment thread 😄. I've updated it now. PTAL and let me know if this works

Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:1201]: Yes it's great, thank you!

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 20]
```diff
@@ -3543,6 +3552,167 @@ scheduler_plugin_execution_duration_seconds_sum{extension_point="PreEnqueue",plu
...
+scheduler_pending_pods{queue="active"} 0
+scheduler_pending_pods{queue="backoff"} 0
+scheduler_pending_pods{queue="gated"} 1
+scheduler_pending_pods{queue="unschedulable"} 0
+`,
+		},
+		{
+			name: "Gated metric should be 1 when Ungated to Gated transition when popFromBackoffQ is disabled",
+			operations: []operation{
+				disablePopFromBackoffQ,
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Let's add `disablePopFromBackoffQ` as a field to the test spec (alongside name, operations etc.) and disable it directly in `t.Run`

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 14 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue.go:652]: @macsko 
PTAL: https://github.com/kubernetes/kubernetes/pull/135756

File: pkg/scheduler/backend/queue/unschedulable_pods.go (hunk 16 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/unschedulable_pods.go:79]: @macsko PTAL:
https://github.com/kubernetes/kubernetes/pull/135769
