### PR TITLE
Fix loadbalancer e2e udp: Part 2 

### LINKED ISSUE #98427: [Failing Test] [sig-network] LoadBalancers should be able to change the type and ports of a UDP service [Slow]
**Which jobs are failing**:
- `ci-kubernetes-e2e-gci-gce-slow` (`gce-cos-master-slow`)

**Which test(s) are failing**:
- `[sig-network] LoadBalancers should be able to change the type and ports of a UDP service [Slow]`

**Since when has it been failing**:
https://github.com/kubernetes/kubernetes/commit/16ed85a6d55efc7af34f6d32e00066f7d9dc0b63
Jan 25 6:25AM PST was the first unsuccessful run

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-cos-master-slow&include-filter-by-regex=LoadBalancers%20should%20be%20able

**Reason for failure**:
`FAIL: UDP Spec.Ports[0].Port (81) did not change`. These are the logs from [this run](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1353710386313957376) after the `mutability-test-*` pod was `running-and-ready`.
```
ï¿½[1mSTEPï¿½[0m: changing the UDP service to type=NodePort
Jan 25 14:47:42.236: INFO: UDP node port: 32658
ï¿½[1mSTEPï¿½[0m: hitting the UDP service's NodePort
Jan 25 14:47:42.237: INFO: Poking udp://34.77.16.203:32658
Jan 25 14:47:42.345: INFO: Poke("udp://34.77.16.203:32658"): success
ï¿½[1mSTEPï¿½[0m: creating a static load balancer IP
Jan 25 14:47:44.259: INFO: Allocated static load balancer IP: 35.187.25.3
ï¿½[1mSTEPï¿½[0m: changing the UDP service to type=LoadBalancer
ï¿½[1mSTEPï¿½[0m: demoting the static IP to ephemeral
ï¿½[1mSTEPï¿½[0m: waiting for the UDP service to have a load balancer
Jan 25 14:47:47.343: INFO: Waiting up to 10m0s for service "mutability-test" to have a LoadBalancer
Jan 25 14:50:15.603: INFO: UDP load balancer: 35.187.25.3
ï¿½[1mSTEPï¿½[0m: hitting the UDP service's NodePort
Jan 25 14:50:15.603: INFO: Poking udp://34.77.16.203:32658
Jan 25 14:50:15.712: INFO: Poke("udp://34.77.16.203:32658"): success
ï¿½[1mSTEPï¿½[0m: hitting the UDP service's LoadBalancer
Jan 25 14:50:15.712: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:15.813: INFO: Poke("udp://35.187.25.3:80"): read udp 10.32.255.47:50687->35.187.25.3:80: read: connection refused
Jan 25 14:50:17.813: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:17.915: INFO: Poke("udp://35.187.25.3:80"): read udp 10.32.255.47:45066->35.187.25.3:80: read: connection refused
Jan 25 14:50:19.813: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:19.918: INFO: Poke("udp://35.187.25.3:80"): read udp 10.32.255.47:50250->35.187.25.3:80: read: connection refused
Jan 25 14:50:21.813: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:21.918: INFO: Poke("udp://35.187.25.3:80"): read udp 10.32.255.47:39870->35.187.25.3:80: read: connection refused
Jan 25 14:50:23.813: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:23.923: INFO: Poke("udp://35.187.25.3:80"): success
ï¿½[1mSTEPï¿½[0m: changing the UDP service's NodePort
Jan 25 14:50:24.162: INFO: UDP node port: 32659
ï¿½[1mSTEPï¿½[0m: hitting the UDP service's new NodePort
Jan 25 14:50:24.162: INFO: Poking udp://34.77.16.203:32659
Jan 25 14:50:24.266: INFO: Poke("udp://34.77.16.203:32659"): read udp 10.32.255.47:56360->34.77.16.203:32659: read: connection refused
Jan 25 14:50:26.266: INFO: Poking udp://34.77.16.203:32659
Jan 25 14:50:26.370: INFO: Poke("udp://34.77.16.203:32659"): read udp 10.32.255.47:45621->34.77.16.203:32659: read: connection refused
Jan 25 14:50:28.266: INFO: Poking udp://34.77.16.203:32659
Jan 25 14:50:28.370: INFO: Poke("udp://34.77.16.203:32659"): read udp 10.32.255.47:44056->34.77.16.203:32659: read: connection refused
Jan 25 14:50:30.266: INFO: Poking udp://34.77.16.203:32659
Jan 25 14:50:30.367: INFO: Poke("udp://34.77.16.203:32659"): read udp 10.32.255.47:51933->34.77.16.203:32659: read: connection refused
Jan 25 14:50:32.266: INFO: Poking udp://34.77.16.203:32659
Jan 25 14:50:32.376: INFO: Poke("udp://34.77.16.203:32659"): success
ï¿½[1mSTEPï¿½[0m: checking the old UDP NodePort is closed
Jan 25 14:50:32.376: INFO: Poking udp://34.77.16.203:32658
Jan 25 14:50:32.480: INFO: Poke("udp://34.77.16.203:32658"): read udp 10.32.255.47:52421->34.77.16.203:32658: read: connection refused
ï¿½[1mSTEPï¿½[0m: hitting the UDP service's LoadBalancer
Jan 25 14:50:32.480: INFO: Poking udp://35.187.25.3:80
Jan 25 14:50:32.586: INFO: Poke("udp://35.187.25.3:80"): success
ï¿½[1mSTEPï¿½[0m: changing the UDP service's port
Jan 25 14:50:32.825: FAIL: UDP Spec.Ports[0].Port (81) did not change
```

**Anything else we need to know**:
Related to #98333 and (possibly?) #98387 

Latest failing run as of writing: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-slow/1354044314744786944

/sig network
/cc @aojea

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind failing-test

**What this PR does / why we need it**:

The test mutates the port and uses it later to poll the service, so we need to store the new port or the test will fail trying to poll the old port

https://testgrid.k8s.io/sig-network-gce#gci-gce-ipvs

**Which issue(s) this PR fixes**:

Fixes #98427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @wojtek-t 

another fix, we fixed the previous error but it fails later because ues the old port to test the service reachability,
is there any presubmit job that we can run here to avoid the roundtrip?

**Comment by wojtek-t** [comment]
/lgtm
/approve

thanks!

**Comment by aojea** [comment]
/retest
known flake

File: test/e2e/network/loadbalancer.go [hunk 1]
```diff
@@ -422,8 +422,10 @@ var _ = SIGDescribe("LoadBalancers", func() {
 			s.Spec.Ports[0].Port++
 		})
 		framework.ExpectNoError(err)
-		if int(udpService.Spec.Ports[0].Port) == svcPort {
-			framework.Failf("UDP Spec.Ports[0].Port (%d) did not change", udpService.Spec.Ports[0].Port)
+		svcPortOld := svcPort
+		svcPort = int(udpService.Spec.Ports[0].Port)
+		if svcPort == svcPortOld {
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:427]: I carried over the old bug, it has to fail if the ports are the same

**Comment by aojea** [comment]
/hold cancel
:face_with_head_bandage: it needs lgtm again @wojtek-t

File: test/e2e/network/loadbalancer.go (hunk 1 above)
Comment (wojtek-t) [reply test/e2e/network/loadbalancer.go:427]: :)
