### PR TITLE
fix kube-scheduler cannot send event because the Note field is too large

### LINKED ISSUE #98175: Kube-scheduler can't send event because Note field too large
**What happened**:
When a pod can't be scheduled and the cardinality of taints on nodes is high, the Note field in the event can become bigger than the 1024 allowed and the event isn't sent. The pod stays in a state of `Pending` without en event which makes the User Experience very bad

**What you expected to happen**:
I would expect the Kube-scheduler to be able to send the event no matter how many different taints are on nodes

**How to reproduce it (as minimally and precisely as possible)**:
add many different taints to nodes and then trying to schedule something which can't be successfully scheduled (higher CPU/memory than any node has)

**Anything else we need to know?**:
```
E0108 16:18:50.017679  762538 event_broadcaster.go:238] Server rejected event '&v1beta1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"<redacted: Pod name>", GenerateName:"", Namespace:"<redacted: Namespace>", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, EventTime:v1.MicroTime{Time:time.Time{wall:0xbff63f5a80f49a60, ext:65938071707113, loc:(*time.Location)(0x2b40280)}}, Series:(*v1beta1.EventSeries)(nil), ReportingController:"default-scheduler", ReportingInstance:"default-scheduler-<redacted: Hostname>", Action:"Scheduling", Reason:"FailedScheduling", Regarding:v1.ObjectReference{Kind:"Pod", Namespace:"<redacted: Namespace>", Name:"<redacted: Podname>", UID:"<redacted: UUID>", APIVersion:"v1", ResourceVersion:"<redacted: Rev version>", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"0/100 nodes are available: 1 node(s) had taint {<redacted: Taint Key>}, that the pod didn't tolerate, 1 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 1 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 11 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 11 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 87 Insufficient cpu, 34 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 12 pod has unbound immediate PersistentVolumeClaims, 12 Too many pods, 2 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 21 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 65 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 39 node(s) had taint {<redacted: Taint Key>: true}, that the pod didn't tolerate, 39 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 5 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 6 Insufficient memory, 8 node(s) had taint {<redacted: Taint Key>: }, that the pod didn't tolerate, 23 node(s) were unschedulable, 9 node(s) had taint {<redacted: Taint Key>}, that the pod didn't tolerate.", Type:"Warning", DeprecatedSource:v1.EventSource{Component:"default-scheduler", Host:""}, DeprecatedFirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedLastTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedCount:0}': 'Event "<redacted: event ID>" is invalid: message: Invalid value: "": can have at most 1024 characters' (will not retry!)
```

In this case the length of the message was 1334 characters.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.9
- Cloud provider or hardware configuration: bare metal

**Possible solutions**:
- make event `Note` size configurable, it's now hardcoded to 1024 characters [here](https://github.com/kubernetes/kubernetes/blob/564b0e55c7007745500d579356897848aaacb9dd/pkg/apis/core/validation/events.go#L38)
- make scheduler note aware of that limit and work around I, if length > 1024 then
  - truncate the string (so at least something is shown)
  - produce N events splitting the text
  - (preferred one): change event Note to be to something like: `Couldn't schedule pod because of this taint, this taint and N more taints` (the whole complete information would still be present in the pod status field. for debugging purposes)

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

I would expect the Kube-scheduler to be able to send the event no matter how many different taints are on nodes

**Which issue(s) this PR fixes**:

Fixes #98175

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
truncates a message if it hits the NoteLengthLimit when the scheduler records an event for the pod that indicates the pod has failed to schedule.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/assign @alculquicondor @gitirabassi 

It's ready for review. Any feedback is welcome.

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -328,17 +329,28 @@ func (sched *Scheduler) recordSchedulingFailure(fwk framework.Framework, podInfo
...
 	pod := podInfo.Pod
-	fwk.EventRecorder().Eventf(pod, nil, v1.EventTypeWarning, "FailedScheduling", "Scheduling", err.Error())
+	msg := truncateMessage(err.Error())
+	fwk.EventRecorder().Eventf(pod, nil, v1.EventTypeWarning, "FailedScheduling", "Scheduling", msg)
 	if err := updatePod(sched.client, pod, &v1.PodCondition{
 		Type:    v1.PodScheduled,
 		Status:  v1.ConditionFalse,
 		Reason:  reason,
-		Message: err.Error(),
+		Message: msg,
```
Comment (gitirabassi) [inline pkg/scheduler/scheduler.go:338]: For the pod message there shouldn't be any message size limit

Comment (gitirabassi) [reply pkg/scheduler/scheduler.go:338]: https://github.com/kubernetes/api/blob/master/core/v1/types.go#L2559 (would be best to have the full message)

Comment (carlory) [reply pkg/scheduler/scheduler.go]: @gitirabassi reverted

**Review by gitirabassi — APPROVED** [review]
LGTM

**Comment by alculquicondor** [comment]
Please add a release note

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -339,6 +341,16 @@ func (sched *Scheduler) recordSchedulingFailure(fwk framework.Framework, podInfo
 	}
 }
 
+// truncateMessage decides if the message should be truncated, based on the event's NoteLengthLimit
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:344]: `truncateMessage truncates a message if it hits the NoteLengthLimit.`

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -339,6 +341,16 @@ func (sched *Scheduler) recordSchedulingFailure(fwk framework.Framework, podInfo
...
+func truncateMessage(message string) string {
+	max := validation.NoteLengthLimit
+	if len(message) <= max {
+		return message
+	}
+	suffix := " [truncated]"
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:350]: `...` would give us some extra characters

**Comment by carlory** [comment]
@alculquicondor It's ready for review

**Comment by alculquicondor** [comment]
/approve
/lgtm

please submit a cherry-pick request to all supported versions https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Comment by carlory** [comment]
@alculquicondor thanks for your guide, I will submit a cherry-pick request today.
