### PR TITLE
fix issue(11233)enhance kubectl config command

### LINKED ISSUE #11233: Alias 'kubectl config use-context' to 'kubectl config use'
The '-context' does not seem to add any value

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
Fixes #11233

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/config/use_context.go [hunk 1]
```diff
@@ -45,7 +45,7 @@ func NewCmdConfigUseContext(out io.Writer, configAccess clientcmd.ConfigAccess)
 	options := &useContextOptions{configAccess: configAccess}
 
 	cmd := &cobra.Command{
-		Use:     "use-context CONTEXT_NAME",
+		Use:     "use CONTEXT_NAME",
```
Comment (dixudx) [inline pkg/kubectl/cmd/config/use_context.go]: I don't think we can change this now. That issue is years ago. We have other **"-context"** subcommands as well.  

@mengqiy @pwittrock PTAL.

File: pkg/kubectl/cmd/util/helpers.go [hunk 2]
```diff
@@ -302,6 +302,12 @@ func UsageErrorf(cmd *cobra.Command, format string, args ...interface{}) error {
 	return fmt.Errorf("%s\nSee '%s -h' for help and examples.", msg, cmd.CommandPath())
 }
 
+func HelpErrorf(cmd *cobra.Command, format string, args ...interface{}) error {
```
Comment (dixudx) [inline pkg/kubectl/cmd/util/helpers.go]: I don't think we need to wrap it as a new method.

**Review by dixudx — CHANGES_REQUESTED** [review]

File: pkg/kubectl/cmd/config/use_context.go (hunk 1 above)
Comment (zjj2wry) [reply pkg/kubectl/cmd/config/use_context.go]: we don't have use-cluster command. this will enhance usability.

File: pkg/kubectl/cmd/util/helpers.go (hunk 2 above)
Comment (zjj2wry) [reply pkg/kubectl/cmd/util/helpers.go]: i think when check ```args``` occur err, print help() info very reasonable. this will reduce repetition code

File: pkg/kubectl/cmd/config/use_context.go (hunk 1 above)
Comment (ericchiang) [reply pkg/kubectl/cmd/config/use_context.go]: It's a backwards incompatible change. We can't modify it.

File: pkg/kubectl/cmd/util/helpers.go (hunk 2 above)
Comment (ericchiang) [reply pkg/kubectl/cmd/util/helpers.go]: If kubectl is going to include more utilities, I'd expect them to be used way more places than just the two sections replaced here.

File: pkg/kubectl/cmd/config/use_context.go (hunk 1 above)
Comment (zjj2wry) [reply pkg/kubectl/cmd/config/use_context.go]: yes, i modify it to ``` Aliases: []string{"use"}```.
actually i want 
```
kubectl config use-context --> kubectl config use
kubectl config current-context --> kubectl config get
kubectl config get-contexts --> kubectl config list
```
i create a issue for this

File: pkg/kubectl/cmd/util/helpers.go (hunk 2 above)
Comment (zjj2wry) [reply pkg/kubectl/cmd/util/helpers.go]: updated

**Comment by zjj2wry** [comment]
#52072

File: pkg/kubectl/cmd/config/use_context.go [hunk 3]
```diff
@@ -47,6 +47,7 @@ func NewCmdConfigUseContext(out io.Writer, configAccess clientcmd.ConfigAccess)
 	cmd := &cobra.Command{
 		Use:     "use-context CONTEXT_NAME",
 		Short:   i18n.T("Sets the current-context in a kubeconfig file"),
+		Aliases: []string{"use"},
```
Comment (ericchiang) [inline pkg/kubectl/cmd/config/use_context.go]: I don't know if this alias fits with the existing sub-commands which explicitly use `(action)-context`

```
  current-context Displays the current-context
  delete-cluster  Delete the specified cluster from the kubeconfig
  delete-context  Delete the specified context from the kubeconfig
  get-clusters    Display clusters defined in the kubeconfig
  get-contexts    Describe one or many contexts
  rename-context  Renames a context from the kubeconfig file.
  set             Sets an individual value in a kubeconfig file
  set-cluster     Sets a cluster entry in kubeconfig
  set-context     Sets a context entry in kubeconfig
  set-credentials Sets a user entry in kubeconfig
  unset           Unsets an individual value in a kubeconfig file
  use-context     Sets the current-context in a kubeconfig file
  view            Display merged kubeconfig settings or a specified kubeconfig file
```

Should probably get some buy-in from sig-cli UX. Shorter isn't always better.

Comment (dixudx) [reply pkg/kubectl/cmd/config/use_context.go]: > Shorter isn't always better.

Agreed. I'd prefer to keep it unchanged.

Current aliases in kubectl are only used as shortcuts for various resources, such as `deploy`, `rs`.  We'd better not breaking the rules only for this subcommand.

Comment (zjj2wry) [reply pkg/kubectl/cmd/config/use_context.go]: not sure current aliases in kubectl are only used as shortcuts for various resources. but this shortcuts just used for cli. we can not set  ```deploy```,```rs``` in yaml, so maybe we don't have limit for use shortcuts.

Comment (mengqiy) [reply pkg/kubectl/cmd/config/use_context.go]: I'm neutral on this change. Adding an alias `use` for `use-context` is not bad, since we don't have other command prefix with `use`.

@fabianofranz thoughts?

Comment (fabianofranz) [reply pkg/kubectl/cmd/config/use_context.go]: We indeed avoid the use of aliases as much as possible. We verified in past that its leads to confusion in the head of users (was it `delete` or `remove`??) much more often than convenience, so we prefer to use suggestions and educate our users to the one single command available that does each thing.

That said, in some very specific areas they are valid and in my opinion this one (`use` specifically) is a good one. Switching contexts is a very common action if you use multiple of them. In OpenShift in past we had it as a top-level command and I remember using `rhc use dev`, `rhc use stg`, `rhc use prod` a lot.

So I'm in favor of `use` → `use-context`, but only this one.

File: pkg/kubectl/cmd/util/helpers.go (hunk 2 above)
Comment (fabianofranz) [reply pkg/kubectl/cmd/util/helpers.go]: > I don't think we need to wrap it as a new method.

+1, I struggle to see the valid in this. We're trying to reduce the amount of utils external to core packages, not increase. So I'd say make it private in `pkg/kubectl/cmd/config` and use it in the `config ...` commands.

File: pkg/kubectl/cmd/config/use_context.go (hunk 3 above)
Comment (zjj2wry) [reply pkg/kubectl/cmd/config/use_context.go]: great~ at least have became easy for me～.～ thanks you for everyone viewpoint:)  i ‘d like just add use-->use-context.

Comment (ericchiang) [reply pkg/kubectl/cmd/config/use_context.go]: Want to chime in that if we ever get a way to manage multiple kubeconfigs  (https://github.com/kubernetes/kubernetes/issues/38791) then `kubectl config use` seems like the natural way to switch between them.
