### PR TITLE
fix: mirroring of last-applied-configuration annotation in EndpointSlices

### LINKED ISSUE #102684: Endpoint slice mirroring controller mirrors kubectl  kubectl.kubernetes.io/last-applied-configuration
#### What happened:

If I modify a custom endpoint, the kubectl kubectl.kubernetes.io/last-applied-configuration annotation is mirrored to the generated endpoint slice

#### What you expected to happen:

Since the kubect last-applied-configuration tracks the status of the object, it shouldn't be mirrored since it doesn't apply to the generated object

#### How to reproduce it (as minimally and precisely as possible):

1. Create a custom endpoint
1. Apply an update on any of the fields
1. Check the generated endpoint slice annotations

```yaml
kubectl get endpointslices ep-test-ljgn7 -o yaml                                                                                                                                                    
addressType: IPv4                                                                                                                                                                                                     
apiVersion: discovery.k8s.io/v1                                                                                                                                                                                       
endpoints:                                                                                                                                                                                                            
- addresses:                                                                                                                                                                                                          
  - 193.99.144.80                                                                                                                                                                                                     
  conditions:                                                                                                                                                                                                         
    ready: true                                                                                                                                                                                                       
- addresses:                                                                                                                                                                                                          
  - 195.54.164.39
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Endpoints","metadata":{"annotations":{},"name":"ep-test","namespace":"default"},"subsets":[{"addresses":[{"ip":"193.99.144.80"}],"notReadyAddresses":[{"ip":"195.54.164.39"}],"ports":[{"name":"http","port":80,"protocol":"TCP"},{"name":"https","port":443,"protocol":"TCP"}]}]}
  creationTimestamp: "2021-06-08T07:35:24Z"
  generateName: ep-test-
  generation: 1
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslicemirroring-controller.k8s.io
    kubernetes.io/service-name: ep-test
  managedFields:
  - apiVersion: discovery.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:addressType: {}
      f:endpoints: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:endpointslice.kubernetes.io/managed-by: {}
          f:kubernetes.io/service-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"21dc11be-4794-4db8-93c2-8c9fb208e75e"}: {}
      f:ports: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-06-08T07:35:24Z"
  name: ep-test-ljgn7

```

/sig network

### PR DESCRIPTION
**Pull request by sharmarajdaksh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fixes the Issue reported in #102684

#### Which issue(s) this PR fixes:

Fixes #102684

#### Does this PR introduce a user-facing change?

```release-note
Endpoint slices mirroring controller no longer mirrors the last-applied-configuration annotation created by kubectl to updated endpoint slices
```

### CODE REVIEW

**Comment by sharmarajdaksh** [comment]
I signed it

**Comment by sharmarajdaksh** [comment]
I signed it

**Comment by aojea** [comment]
/ok-to-test
@sharmarajdaksh if you don't ping us this goes unnoticed :smile: 
/assign @robscott @aojea

**Comment by BenTheElder** [comment]
@aojea perhaps time to update owners for endpointslice? https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpointslice/OWNERS

**Comment by sharmarajdaksh** [comment]
@aojea I'm sorry I didn't know for sure where to ping/mention this PR!

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 1]
```diff
@@ -791,6 +791,116 @@ func TestReconcile(t *testing.T) {
...
+				IP:       "10.0.1.3",
+				Hostname: "pod-13",
+				NodeName: utilpointer.StringPtr("node-3"),
+			}},
+		}},
+		existingEndpointSlices: []*discovery.EndpointSlice{{
+			ObjectMeta: metav1.ObjectMeta{
+				Name: "test-ep-1",
+				Annotations: map[string]string{
+					corev1.LastAppliedConfigAnnotation: "{\"apiVersion\":\"v1\",\"kind\":\"Endpoints\",\"metadata\":{\"annotations\":{},\"name\":\"ep-test\",\"namespace\":\"default\"},\"subsets\":[{\"addresses\":[{\"ip\":\"193.99.144.80\"}],\"notReadyAddresses\":[{\"ip\":\"195.54.164.39\"}],\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\"},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\"}]}]}",
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:843]: I'm not sure this is the primary issue you want to be testing here. If I'm understanding this correctly, it ensures that an EndpointSlice that has this annotation will have it removed after a mirroring sync has occurred. That's helpful for cleanup, but what I think we actually need to test is that an Endpoints resource with this annotation is not translated to a mirrored EndpointSlice resource.

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 2]
```diff
@@ -837,6 +947,8 @@ func TestReconcile(t *testing.T) {
 				expectMetrics(t, *tc.expectedMetrics)
 			}
 
+			expectAnnotations(t, endpoints, tc.existingEndpointSlices)
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:950]: This is not actually what you want here. You're comparing the two test inputs (Endpoints and EndpointSlices that exist before controller syncs), not the actual output (fetched below).

Comment (robscott) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: Actually, I think you could just expand `expectEndpointSlices` to always expect this annotation to be unset. This would be similar to how it always expects the service name label to be set: https://github.com/kubernetes/kubernetes/blob/576457ac2508d2e06782805f9b3cb27dbbcf7324/pkg/controller/endpointslicemirroring/reconciler_test.go#L988-L991.

**Review by robscott — COMMENTED** [review]
Thanks for your work on this @sharmarajdaksh!

File: pkg/controller/endpointslicemirroring/reconciler_test.go (hunk 2 above)
Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: I see my mistake. Thank you for the pointers. I'll update my PR

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: @robscott 
If i understand you correctly, all that should be needed at the line you specified inside `reconciler_test.go` is:
```
if epSlice.Annotations[corev1.LastAppliedConfigAnnotation] != "" {
        t.Errorf("Expected LastAppliedConfig Annotation to be unser, got %s", epSlice.Annotations[corev1.LastAppliedConfigAnnotation])
}
```

Comment (robscott) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: Yep, exactly something like that. We'd also need some way for a test case to actually set that annotation on the original Endpoints and EndpointSlice resources as well. You've already got the EndpointSlice use case covered, but it will be a bit more difficult to do the same for the Endpoints in the test case since we just have a `subsets` object instead of the full resource. Maybe just add a new `endpointsAnnotations` struct to the testCase struct?

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: Yes, a map[string]string should work for that, I believe?

Comment (robscott) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:950]: Yep, that sounds ideal.

**Comment by BenTheElder** [comment]
this branch will need cleanup to merge, the project does not allow merging merge commits, versus a rebase flow.

https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md has some pointers 😬

**Comment by sharmarajdaksh** [comment]
Fixed the merge mess! apologies.

File: pkg/controller/endpointslicemirroring/utils.go [hunk 3]
```diff
@@ -87,9 +87,9 @@ func newEndpointSlice(endpoints *corev1.Endpoints, ports []discovery.EndpointPor
 	epSlice.Labels[discovery.LabelServiceName] = endpoints.Name
 	epSlice.Labels[discovery.LabelManagedBy] = controllerName
 
-	// clone all annotations but EndpointsLastChangeTriggerTime
+	// clone all annotations but EndpointsLastChangeTriggerTime and LastAppliedConfigAnnotation
 	for annotation, val := range endpoints.Annotations {
-		if annotation == corev1.EndpointsLastChangeTriggerTime {
+		if annotation == corev1.EndpointsLastChangeTriggerTime || annotation == corev1.LastAppliedConfigAnnotation {
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/controller/endpointslicemirroring/utils.go:92]: yep, good catch

File: pkg/controller/endpointslicemirroring/reconciler_test.go (hunk 1 above)
Comment (aojea) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:847]: agreed

Comment (aojea) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:847]: so, let's test:
1. endpoint with corev1.LastAppliedConfigAnnotation: "_data_here" is notmirrored
2. endpoint with corev1.LastAppliedConfigAnnotation: empty is notmirrored
3. endpoint with 2 annotations:  corev1.LastAppliedConfigAnnotation: "_data_here" and foo:bar only mirrors foo bar

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 4]
```diff
@@ -791,6 +792,122 @@ func TestReconcile(t *testing.T) {
...
+			Addresses: []corev1.EndpointAddress{{
+				IP:       "10.0.1.1",
+				Hostname: "pod-11",
+				NodeName: utilpointer.StringPtr("node-1"),
+			}, {
+				IP:       "10.0.1.2",
+				Hostname: "pod-12",
+				NodeName: utilpointer.StringPtr("node-2"),
+			}, {
+				IP:       "10.0.1.3",
```
Comment (aojea) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:838]: for these specific uses cases we only want to test the annotations, you can keep the other fields with the minimum necessary

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 5]
```diff
@@ -880,6 +997,10 @@ func expectEndpointSlices(t *testing.T, num, maxEndpointsPerSubset int, endpoint
 		if serviceNameVal != endpoints.Name {
 			t.Errorf("Expected EndpointSlice to have %s label set to %s, got %s", discovery.LabelServiceName, endpoints.Name, serviceNameVal)
 		}
+
+		if epSlice.Annotations[corev1.LastAppliedConfigAnnotation] != "" {
```
Comment (aojea) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:1001]: this doesn't fail if the annotation is set but doesn't return any value
https://play.golang.org/p/1wIZNGroJCT
```suggestion
		_,ok = epSlice.Annotations[corev1.LastAppliedConfigAnnotation] 
		if ok {
```

File: pkg/controller/endpointslicemirroring/reconciler_test.go (hunk 4 above)
Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go]: Alright

File: pkg/controller/endpointslicemirroring/reconciler_test.go (hunk 1 above)
Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go]: Sounds good

**Comment by sharmarajdaksh** [comment]
@aojea @robscott I think I've covered all of the points you mentioned now

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 6]
```diff
@@ -791,6 +792,64 @@ func TestReconcile(t *testing.T) {
 		expectedClientActions:  2,
 		maxEndpointsPerSubset:  2,
 		expectedMetrics:        &expectedMetrics{desiredSlices: 2, actualSlices: 2, desiredEndpoints: 4, addedPerSync: 4, updatedPerSync: 0, removedPerSync: 0, skippedPerSync: 1, numCreated: 2, numUpdated: 0},
+	}, {
+		testName: "Annotation mirroring when LastAppliedCondifAnnotation is set",
```
Comment (dims) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:796]: typo ... LastAppliedCondifAnnotation -> LastAppliedConfigAnnotation ?

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go]: Yikes, fixed!

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 7]
```diff
@@ -791,6 +792,64 @@ func TestReconcile(t *testing.T) {
...
+				IP:       "10.0.0.1",
+				Hostname: "pod-1",
+			}},
+		}},
+		existingEndpointSlices: []*discovery.EndpointSlice{{}},
+		expectedNumSlices:      1,
+		expectedClientActions:  2,
+		expectedMetrics:        &expectedMetrics{addedPerSync: 1, numCreated: 1, desiredEndpoints: 1, desiredSlices: 1, actualSlices: 1, numDeleted: 1},
+	}, {
+		testName: "Annotation mirroring when LastAppliedConfigAnnotation is not set",
```
Comment (aojea) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:816]: this is `LastAppliedConfigAnnotation` annotation is present but doesn't have any value

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:816]: Not sure I follow @aojea 
Are you suggesting that I add epAnnotations to this test case?
Or perhaps it would be better to have a separate test case for what you're suggesting, leaving this one as is, with the annotation staying unset?

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:816]: @aojea I've added a seperate test case for the case you mentioned

Comment (aojea) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:816]: :+1:

**Comment by aojea** [comment]
this LGTM
can you please squash all the commits?

**Comment by sharmarajdaksh** [comment]
Done @aojea

**Comment by aojea** [comment]
/lgtm
@sharmarajdaksh please add a release note. something like 
```
endpointslices mirroring controller no longer mirrors the endpoint annotation created by kubectl with the "last-applied-configuration"
```

defer approval to RobScott

**Comment by sharmarajdaksh** [comment]
Added the release note

**Review by neolit123 — COMMENTED** [review]
/remove-sig cluster-lifecycle
/remove-area kubeadm

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 8]
```diff
@@ -791,6 +792,84 @@ func TestReconcile(t *testing.T) {
 		expectedClientActions:  2,
 		maxEndpointsPerSubset:  2,
 		expectedMetrics:        &expectedMetrics{desiredSlices: 2, actualSlices: 2, desiredEndpoints: 4, addedPerSync: 4, updatedPerSync: 0, removedPerSync: 0, skippedPerSync: 1, numCreated: 2, numUpdated: 0},
+	}, {
+		testName: "Annotation mirroring when LastAppliedConfigAnnotation is set",
+		epAnnotations: map[string]string{
+			corev1.LastAppliedConfigAnnotation: "{\"apiVersion\":\"v1\",\"kind\":\"Endpoints\",\"metadata\":{\"annotations\":{},\"name\":\"ep-test\",\"namespace\":\"default\"},\"subsets\":[{\"addresses\":[{\"ip\":\"193.99.144.80\"}],\"notReadyAddresses\":[{\"ip\":\"195.54.164.39\"}],\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\"},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\"}]}]}",
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:798]: This is a tiny nit, but could this annotation be a bit shorter? I don't think it needs to be very long, and a shorter one would make editing this test slightly easier in the future.

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 9]
```diff
@@ -791,6 +792,84 @@ func TestReconcile(t *testing.T) {
...
+			}},
+		}},
+		existingEndpointSlices: []*discovery.EndpointSlice{},
+		expectedNumSlices:      1,
+		expectedClientActions:  1,
+		expectedMetrics:        &expectedMetrics{addedPerSync: 1, numCreated: 1, desiredEndpoints: 1, desiredSlices: 1, actualSlices: 1},
+	}, {
+		testName: "Annotation mirroring when multiple annotations are set",
+		epAnnotations: map[string]string{
+			corev1.LastAppliedConfigAnnotation: "{\"apiVersion\":\"v1\",\"kind\":\"Endpoints\",\"metadata\":{\"annotations\":{},\"name\":\"ep-test\",\"namespace\":\"default\"},\"subsets\":[{\"addresses\":[{\"ip\":\"193.99.144.80\"}],\"notReadyAddresses\":[{\"ip\":\"195.54.164.39\"}],\"ports\":[{\"name\":\"http\",\"port\":80,\"protocol\":\"TCP\"},{\"name\":\"https\",\"port\":443,\"protocol\":\"TCP\"}]}]}",
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:855]: Same comment about annotation length.

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 10]
```diff
@@ -791,6 +792,84 @@ func TestReconcile(t *testing.T) {
...
+				Name:     "http",
+				Port:     80,
+				Protocol: corev1.ProtocolTCP,
+			}},
+			Addresses: []corev1.EndpointAddress{{
+				IP:       "10.0.0.1",
+				Hostname: "pod-1",
+			}},
+		}},
+		existingEndpointSlices: []*discovery.EndpointSlice{},
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:869]: Can you add a test case to ensure that an existing slice with this annotation has it cleared out? I think you may have had that test case covered earlier in this PR.

**Review by robscott — COMMENTED** [review]
Thanks for your work on this @sharmarajdaksh! Just a couple tiny nits, otherwise LGTM.

**Comment by sharmarajdaksh** [comment]
Sure no problem, I'll sort the issues you mentioned

**Comment by sharmarajdaksh** [comment]
@robscott lmk if it looks good now!

File: pkg/controller/endpointslicemirroring/reconciler_test.go [hunk 11]
```diff
@@ -791,6 +792,118 @@ func TestReconcile(t *testing.T) {
...
+		expectedNumSlices:      1,
+		expectedClientActions:  1,
+		expectedMetrics:        &expectedMetrics{addedPerSync: 1, numCreated: 1, desiredEndpoints: 1, desiredSlices: 1, actualSlices: 1},
+	}, {
+		testName: "Annotation mirroring and updation when the last-applied-configuration annotation is present on an existing endpoint slice",
```
Comment (robscott) [inline pkg/controller/endpointslicemirroring/reconciler_test.go:874]: Test name is confusing to me, maybe something like this:
```suggestion
		testName: "Annotation mirroring should remove last-applied-configuration annotation from existing endpoint slice",
```

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go:874]: Hmm, actually now that you mention it I think the test names for all the tests I added could be better

Comment (sharmarajdaksh) [reply pkg/controller/endpointslicemirroring/reconciler_test.go]: Updated

**Comment by robscott** [comment]
Thanks!

/lgtm
/approve
