### PR TITLE
Do not clear state of pods pending admission for CPU/Memory/Device manager

### LINKED ISSUE #103952: The CPU manager does not work correctly for the guaranteed pod with multiple containers
#### What happened:

The CPU manager removes the allocation for previous containers under the guaranteed pod once the next container allocation started.

The CPU manager test fails because of it
```
E2eNode Suite: [sig-node] CPU Manager [Serial] [Feature:CPUManager] With kubeconfig updated with static CPU Manager policy run the CPU Manager tests should assign CPUs as expected based on the Pod spec
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cpu-manager/1420014879246389248

#### What you expected to happen:

The CPU manager should keep previous containers allocations.

#### How to reproduce it (as minimally and precisely as possible):

- Start the guaranteed pod with two containers
- Verify the CPU pining for the first container

#### Anything else we need to know?:

I think the problem introduced by recent refactor under https://github.com/kubernetes/kubernetes/commit/3eadd1a9ead7a009a9abfbd603a5efd0560473cc

So what happens:
```
27 13:11:05.510153    4328 kubelet.go:2053] "SyncLoop ADD" source="api" pods=[cpu-manager-test-660/gu-pod]
27 13:11:05.510196    4328 topology_manager.go:200] "Topology Admit Handler"
27 13:11:05.510220    4328 manager.go:872] "Looking for needed resources" needed=1 resourceName="cpu"
27 13:11:05.510234    4328 manager.go:872] "Looking for needed resources" needed=104857600 resourceName="memory"
27 13:11:05.510274    4328 policy_static.go:251] "Static policy: Allocate" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container1"
27 13:11:05.510298    4328 policy_static.go:277] "Topology Affinity" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container1" affinity={NUMANodeA
27 13:11:05.510309    4328 policy_static.go:304] "AllocateCPUs" numCPUs=1 socket=<nil>
27 13:11:05.510368    4328 cpu_assignment.go:166] "takeRemainingCPUs: claiming CPU" cpu=2
27 13:11:05.510391    4328 state_mem.go:88] "Updated default CPUSet" cpuSet="0-1,3"
27 13:11:05.513807    4328 policy_static.go:339] "AllocateCPUs" result="2"
27 13:11:05.513844    4328 state_mem.go:80] "Updated desired CPUSet" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1" cpuSet=
27 13:11:05.516331    4328 manager.go:872] "Looking for needed resources" needed=1 resourceName="cpu"
27 13:11:05.516373    4328 manager.go:872] "Looking for needed resources" needed=104857600 resourceName="memory"
27 13:11:05.516394    4328 cpu_manager.go:363] "RemoveStaleState: removing container" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-co
27 13:11:05.516404    4328 policy_static.go:294] "Static policy: RemoveContainer" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-contai
27 13:11:05.516416    4328 state_mem.go:107] "Deleted CPUSet assignment" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1"
27 13:11:05.518811    4328 state_mem.go:88] "Updated default CPUSet" cpuSet="0-3"
27 13:11:05.521226    4328 state_mem.go:107] "Deleted CPUSet assignment" podUID="0ea44149-552f-42ed-9d38-60e374249dca" containerName="gu-test-container1"
27 13:11:05.521268    4328 policy_static.go:251] "Static policy: Allocate" pod="cpu-manager-test-660/gu-pod" containerName="gu-test-container2"
```
- the CPU manager allocates the CPU for the first container
- Part of the second container allocation the CPU manager calls to [removeStaleState](https://github.com/kubernetes/kubernetes/blob/d92b788faa2521a937acc5fdcb66bfdb960dbd48/pkg/kubelet/cm/cpumanager/cpu_manager.go#L240)
- The kubelet does not recognize our new pod as running one and as a result, `removeStaleState` removes the first container from the state file

The issues affect the memory manager as well.

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Do not remove admitted pods from the state until the pod passed the admission phase.

- [x] CPU manager
- [x] Memory manager
- [x] Device manager

#### Which issue(s) this PR fixes:

Fixes #103952

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.22 regression in kubelet pod admission
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@smarterclayton @klueska @fromanirh FYI

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 1]
```diff
@@ -343,11 +359,14 @@ func (m *manager) removeStaleState() {
 	defer m.Unlock()
 
 	// Get the list of active pods.
-	activePods := m.activePods()
+	activeAndAdmittedPods := m.activePods()
+	for _, pod := range m.admittedPods {
+		activeAndAdmittedPods = append(activeAndAdmittedPods, pod)
+	}
```
Comment (smarterclayton) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: I think this is only partially correct.  You need to prune the admitted pods map to only include those that are still in either config or pod worker but not in both (a pod that is in the pod worker is by definition admitted).  You also want to exclude pods that are no longer running due to termination (which means we will never start the container again, thus we can reuse those CPUs).  You then need to take that pruned list of admitted pods and add it to active pods to get the list of "pods that should be considered to be allocated guaranteed resources"

I think we'll need to add a method on kubelet to make this easier - looking at what that would be right now.

**Review by smarterclayton — CHANGES_REQUESTED** [review]

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (smarterclayton) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: Looking at this, I think we have a bug in that these components need to know about pods that are terminating that have been force deleted (which activePods() does not include).  @Random-Liu I think that components like the cpu_manager, memory_manager, qos_container_manager, and device_manager actually need to know pods that have been force deleted but are still running.  To do that, I'm going to need to enable the pod worker to share that info safely (and consistently, i think).

**Comment by fromanirh** [comment]
/assign @klueska 
Kevin, this is the current direction for fixing the resource managers.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: I'm not sure what you suggest here is necessary. As you mentioned in your comment [here](https://github.com/kubernetes/kubernetes/issues/103952#issuecomment-888387811), all we should really need to care about is whether the pod is:

(1) in the active pods list; or
(2) some pod currently waiting to be admitted

Assuming logic exists to _atomically_ add an admitted pod to the active pod list before starting the next admission loop, I believe this should be sufficient.

We just then need to track a single variable to hold the "currently being admitting" pod that gets overwritten each time a new iteration of the admit loop starts.

The check in `removeStaleState()` would then remove any state not currently associated with a pod in the active list + this new variable.

Of course this is all contingent on what I said before:
> Assuming logic exists to _atomically_ add an admitted pod to the active pod list before starting the next admission loop, I believe this should be sufficient.

Maybe there's good reason not to do this?

Comment (smarterclayton) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: > (1) in the active pods list; or

The bug is that the active pods list does not include force deleted pods that may take tens of minutes to complete that may still have running containers that are pinned to certain CPUs.

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: Is that a problem though? I would think we can safely remove the CPUs assigned to them then, and the next time around the reconcile loop, their containers will be moved onto non-exclusive CPUs.

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: Ah, nevermind, the reconcile loop also relies on the activePods List, so there is no way to know we should move these deleted pods to non-exclusive CPUs.

File: pkg/kubelet/cm/memorymanager/memory_manager.go [hunk 2]
```diff
@@ -430,3 +452,19 @@ func (m *manager) GetAllocatableMemory() []state.Block {
 func (m *manager) GetMemory(podUID, containerName string) []state.Block {
 	return m.state.GetMemoryBlocks(podUID, containerName)
 }
+
+func (m *manager) updateAdmittedPods(pod *v1.Pod) {
```
Comment (fromanirh) [inline pkg/kubelet/cm/memorymanager/memory_manager.go:456]: minor: should we try to generalize this logic?

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: On thing to consider here -- while I agree that this would be nice to have -- it's not something we supported before, so not including it now would not be a regression. It should be in it's own PR.

I also still think there's a way to handle this without adding a new function (i.e. track which pods' state was removed from `removeStaleState()` and check each of it's container statuses one last time the next time it is in the reconcile loop). If any of them are still running, it will trigger the `Update()` call at the bottom of the loop to remove it's exclusive CPUs.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: @smarterclayton Do you know if the `GetActivePods()` returned force deleted pods before the refactoring? If no, for now, we can at least fix the code to have old behavior and once we will have an option to get force deleted pods, we can refactor the code again.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 2 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:456]: We can try to generalize it, but it is a small chunk of code so for now, I do not want to overcomplicate it with additional structures and interfaces.
We have some additional places that we can generalize and it is worth creating a separate PR for all generalization changes.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: It doesn’t matter if it included these pods or not before — we’ve never had logic to actually call ‚update()‘ on the containers associated with these types of pods to remove CPUs  from them if they were still running. That is the new logic we would need to add.

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: Although, I guess if activePods() did include terminated (but still running) pods before, then we never would have removed stale state about them here, making us „think“ their CPUs were free (even though containers are still running on them).

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 2 above)
Comment (fromanirh) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:456]: fine for me.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (fromanirh) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: > Although, I guess if activePods() used to include terminated (but still running) pods before, then we never would have removed stale state about them here, making us „think“ their CPUs were free (even though containers are still running on them).
AFAIU/CT this is the most pressing question now. I fully agree about the general idea to restore the old (and, we learned, not covering some important cases) behaviour and iterating later to actually cover them. The former is important and urgent, the later important as well but less urgent.

Comment (smarterclayton) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: ActivePods() never returned pods that were force deleted.  So you have always been broken on that.

**Review by ehashman — COMMENTED** [review]
/priority important-soon
/triage accepted

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 1 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: In this case, can we restore at least the old behavior under the current PR, and once we will have the infrastructure to get force deleted pods we can improve the logic under resource managers.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: I opened an issue to monitor force deleted pods problem - https://github.com/kubernetes/kubernetes/issues/104099#issuecomment-891796528

Comment (smarterclayton) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:365]: I agree this does not block this change, and probably the fix for 104099 should make the code changes here simpler (but we don't have to do it now).

File: pkg/kubelet/cm/memorymanager/memory_manager.go [hunk 3]
```diff
@@ -206,6 +210,9 @@ func (m *manager) AddContainer(pod *v1.Pod, container *v1.Container, containerID
 
 		m.policyRemoveContainerByRef(string(pod.UID), initContainer.Name)
 	}
+
+	// the pod passed the admit phase and we can remove the pod from the admitted pods
+	delete(m.admittedPods, string(pod.UID))
```
Comment (fromanirh) [inline pkg/kubelet/cm/memorymanager/memory_manager.go:215]: this seems unnecessary - cleanup is performed in `updatedAdmittedPods` anyway but should be harmless as well

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 4]
```diff
@@ -619,14 +627,18 @@ func (m *ManagerImpl) readCheckpoint() error {
 
 // UpdateAllocatedDevices frees any Devices that are bound to terminated pods.
 func (m *ManagerImpl) UpdateAllocatedDevices() {
-	activePods := m.activePods()
+	activeAndAdmittedPods := m.activePods()
+	for _, pod := range m.admittedPods {
+		activeAndAdmittedPods = append(activeAndAdmittedPods, pod)
+	}
```
Comment (fromanirh) [inline pkg/kubelet/cm/devicemanager/manager.go:633]: here we don't need locks because this function is always called synchronously in the allocation flow, right?

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:633]: ...except for podresources API servers, so we need locks here as well.

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:633]: just move the 4 lines above inside the lock; the `if !m.sourcesReady.AllReady()` line should stay like this I believe.
AFAIK/AFAICT, querying for the active pods after the `AllReady` check should have no negative effect.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 5]
```diff
@@ -493,3 +512,19 @@ func (m *manager) updateContainerCPUSet(containerID string, cpus cpuset.CPUSet)
...
+	for podUID := range m.admittedPods {
+		if podUID != string(pod.UID) {
+			delete(m.admittedPods, podUID)
+		}
+	}
+
+	if _, ok := m.admittedPods[string(pod.UID)]; !ok {
+		m.admittedPods[string(pod.UID)] = pod
+	}
+}
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:530]: I don't quite understand why we need all of the extra logic in this function.

It currently says:
1) If the pod being considered is not in the `admittedPods` map, then remove it
2) If the pod being considered is not yet in the `admittedPods` map, put it in it

Which means that at any given time, only one pod should ever be present in the `admittedPods` map.

As such, we can just use a single variable (instead of a map) to hold the "currently being admitted pod", reducing the logic to:
```
func (m *manager) updatePodPendingAdmission(pod *v1.Pod) {
	m.Lock()
	defer m.Unlock()
	m.pendingAdmissionPod = pod
```

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 6]
```diff
@@ -236,6 +240,10 @@ func (m *manager) Start(activePods ActivePodsFunc, sourcesReady config.SourcesRe
 }
 
 func (m *manager) Allocate(p *v1.Pod, c *v1.Container) error {
+	// The pod during the admission phase, we need to add the pod to admitted pods
+	// to avoid the pod deletion from the state
+	m.updateAdmittedPods(p)
+
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:246]: It feels awkward to have this function called in 3 places. It makes sense for `removeStaleState()` because pods could disappear at any time and we want to make sure we remove the stale state before continuing with the logic in any of these functions. But for updating a state variable about which pod is currently being admitted -- it feels weird to have a "catch all" function that is called in multiple places like this.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 5 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:530]: True, I just somehow was affected by the re-use memory variable.

Comment (fromanirh) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:530]: > Which means that at any given time, only one pod should ever be present in the admittedPods map.
I thought the same, but IIUC (and @cynepco3hahue please correct me if I'm wrong) this holds true iff we can remove the pod from the internal map once the admission is complete. The current code (hence the IIUC) seems to prefer to keep the pod lingering a bit while, and perform the cleanup once a new pod gets admitted. If I got it right I don't have strong feelings about this approach, besides wasting a bit of memory it should be safe.

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:530]: My approach also leaves it "lingering" -- you only overwrite the variable the next time this function is called (which is at the admission of the next pod).

The main issue I see with the `map` approach is that we will also need to add a "getter" function since the `reconcileState()` function runs asynchronous to this one. Otherwise, we will run into concurrent map access panics.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 6 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:246]: I can refactor `removeStaleState()` easily to pass the pod to it because it is called under the CPU manager reconcile loop. And I need to call pod update because it is possible that the code will call all three methods as a first method.
1. Allocate - No topology manager, CPU manager with the static policy
2. GetTopologyHints - Topology manager with the container scope
3. GetPodTopologyHints - Topology manager with the pod scope

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:246]: I wonder if it makes sense to track this variable in the `TopologyManager` instead and add a function to the `HintProvider` (or even introduce a new interface) to return it for use in these components.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:246]: But the interface will not call it for you, you still will need to call the interface method. And I think your question is somehow related to the comment https://github.com/kubernetes/kubernetes/pull/103979#discussion_r679909749

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:245]: I’m not sure what you mean about “the interface will not call it for you”. The idea is that the topology manager would track the variable and the interface call would be something like “GetPodBeingAdmitted()” to just grab access to it when needed.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/devicemanager/manager.go]: SO I think we can return the stale data under calls to the CPU and memory manager.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 6 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:245]: I'd rather have a (possibly undesired) API call creep into the internal `HintProvider` interface (that we can refactor later), than have 9 unnecessary calls spread across 3 different components that all do the same thing.

Especially since the change to implement this new call is to add a single state variable to the `TopologyManager` and `FakeTopologyManager` that gets assigned in the `Admit()` call and then extracted via the new API call (by the original three components).

I picture a refactor later that abstracts how we get the list of pods we actually care about tracking state for (i.e. an interface that returns (1) the currently being admitted pod, (2) active pods, and (3) terminated but still running pods). Having (1) in a single place already, will help make this refactoring easier down the road, for just a little bit more effort now.

Comment (fromanirh) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:245]: Since we are discussing this topic, I just want to make sure we take the case "topology manager disabled" into account:
https://github.com/kubernetes/kubernetes/blob/v1.22.0-rc.0/pkg/kubelet/cm/container_manager_linux.go#L747
sorry if being redundant, was bite by this case lately and just trying to save us some more pain :)

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:245]: Right ... that adds a complication to what I suggested before (since it's possible that the feature gate is disabled so *neither* the normal topology manager or the fake topology manager is in use).

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:245]: OK. I'll concede not to do this generalization now until we figure out a better abstraction for it.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 7]
```diff
@@ -493,3 +511,10 @@ func (m *manager) updateContainerCPUSet(containerID string, cpus cpuset.CPUSet)
 func (m *manager) GetCPUs(podUID, containerName string) cpuset.CPUSet {
 	return m.state.GetCPUSetOrDefault(podUID, containerName)
 }
+
+func (m *manager) updateAdmittedPods(pod *v1.Pod) {
+	m.Lock()
+	defer m.Unlock()
+
+	m.pendingAdmissionPod = pod
+}
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:520]: Do we actually even need this function anymore (in any of the components)? Unless I'm missing something, no one should be calling this asynchrounously so no lock should be necesssary. If it is still necessary, we should rename it to  something more appropriate (e.g. `setPodPendingAdmission()`).

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/devicemanager/manager.go]: We do not call the `RemoveContainer` under the post stop internal hook, I think it is still used somewhere internally, but in general it redundant method now. We stopped running it to prevent the problem with container restarts - https://github.com/kubernetes/kubernetes/pull/90377/files

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 7 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:520]: I think we need this one at least for the CPU manager and device manager:
1. CPU manager - we have the reconcile loop that can happen in the middle of the other methods
2. Device manager - it possible to call pod resource API that calls to `UpdateAllocatedDevices` during other device managers methods

Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: Both the reconcile loop and `UpdateAllocatedDevices ()` should not be updating this variable though (only consuming it).

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/devicemanager/manager.go]: It is still questionable why do we need to call `UpdateAllocatedDevices`, I can see we get pods here https://github.com/kubernetes/kubernetes/blob/9ff3b7e744b34c099c1405d9add192adbef0b6b1/pkg/kubelet/apis/podresources/server_v1.go#L54, so we do not really fetch whole pod state information but we do it for a specific set of pods.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 7 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: Renamed.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: But it is not an atomic variable so if you will read it in the middle of the write operation you can get some unexpected results(never encounter it, but I know it possible in theory)

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go]: How do we ensure a (reasonnably) consistent view of device allocations without calling `UpdateAllocatedDevices`?

Comment (cynepco3hahue) [reply pkg/kubelet/cm/devicemanager/manager.go]: Why the pod allocated devices should be different from one provided during the admission phase?

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 7 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: It’s a pointer, so it should be OK (on most systems), but I agree it is not guaranteed in general. Are all reads protected by the same lock used for the writes?

Comment (cynepco3hahue) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go]: Yes, we are using the same lock for the whole manager.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go]: Because `GetPods` returns *all* the pods (it's https://github.com/kubernetes/kubernetes/blob/9ff3b7e744b34c099c1405d9add192adbef0b6b1/pkg/kubelet/pod/pod_manager.go#L260) - the real loop which takes into account the active pods and the actual allocation, like excluding the terminate pods, happens in `UpdateAllocatedDevices`. This code is quite old - it is inherited from the server_v1alpha1.go and we can probably make it smarter taking into account the things we learned in between, but would need a separate PR and some testing. I'm not sure we would need to be bug-compatible with `v1alpha1` API or not.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/devicemanager/manager.go]: I see, I was sure it should return only active pods. Thanks for the info.

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go]: Well, you're right we can improve this flow, like a lot. But just not quickly enough to make this PR simpler, unfortunately :\

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 8]
```diff
@@ -304,13 +311,21 @@ func (m *manager) State() state.Reader {
 }
 
 func (m *manager) GetTopologyHints(pod *v1.Pod, container *v1.Container) map[string][]topologymanager.TopologyHint {
+	// The pod during the admission phase, we need to add the pod to admitted pods
+	// to avoid the pod deletion from the state
+	m.setPodPendingAdmission(pod)
+
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:317]: nit: can we remove this line to stay consistent with the rest of the function

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 9]
```diff
@@ -304,13 +311,21 @@ func (m *manager) State() state.Reader {
...
 	m.removeStaleState()
 	// Delegate to active policy
 	return m.policy.GetTopologyHints(m.state, pod, container)
 }
 
 func (m *manager) GetPodTopologyHints(pod *v1.Pod) map[string][]topologymanager.TopologyHint {
+	// The pod during the admission phase, we need to add the pod to admitted pods
+	// to avoid the pod deletion from the state
+	m.setPodPendingAdmission(pod)
+
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:328]: nit: can we remove this line to stay consistent with the rest of the function

File: pkg/kubelet/cm/cpumanager/topology_hints_test.go [hunk 10]
```diff
@@ -188,6 +188,11 @@ func TestGetTopologyHints(t *testing.T) {
 		if len(tc.expectedHints) == 0 && len(hints) == 0 {
 			continue
 		}
+
+		if m.pendingAdmissionPod == nil {
+			t.Errorf("The admittedPods should include the current pod after call to GetTopologyHints()")
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/topology_hints_test.go:193]: should the variable in this string be renamed?

File: pkg/kubelet/cm/memorymanager/memory_manager_test.go [hunk 11]
```diff
@@ -2112,10 +2112,6 @@ func TestGetTopologyHints(t *testing.T) {
 						NUMANodeAffinity: newNUMAAffinity(1),
 						Preferred:        true,
 					},
-					{
-						NUMANodeAffinity: newNUMAAffinity(0, 1),
-						Preferred:        false,
-					},
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/memory_manager_test.go:2118]: Why does this need to be removed? Is there an alternative test to put in its place?

File: pkg/kubelet/cm/memorymanager/memory_manager_test.go [hunk 12]
```diff
@@ -2126,10 +2122,6 @@ func TestGetTopologyHints(t *testing.T) {
...
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/memory_manager_test.go:2132]: Why does this need to be removed? Is there an alternative test to put in its place?

File: pkg/kubelet/cm/memorymanager/memory_manager_test.go [hunk 13]
```diff
@@ -2144,14 +2136,32 @@ func TestGetTopologyHints(t *testing.T) {
...
+										Name: "fakeContainer1",
+									},
+									{
+										Name: "fakeContainer2",
+									},
+								},
+							},
+						},
+					}
+				},
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/memory_manager_test.go:2157]: I think we should leave the old logic in place (to continue testing with no active pods list), and then add this as a second `Run()` loop in this function to test with something in the active pods list (and an admitting pod).

**Review by klueska — COMMENTED** [review]
Almost there, a few more comments.

**Review by klueska — COMMENTED** [review]
/approve
/lgtm

**Comment by klueska** [comment]
Can you change the title of this PR to:
> Do not clear state of pods pending admission for CPU/Memory/Device manager

And then create a backport cherry-pick to 1.22.

**Comment by cynepco3hahue** [comment]
@klueska Done

**Comment by cynepco3hahue** [comment]
@ehashman Hi, can you please help to cherry-pick the PR to release-1.22?

**Comment by ehashman** [comment]
> @ehashman Hi, can you please help to cherry-pick the PR to release-1.22?

There's no bot support in upstream k8s, you can run the ./hack/cherry_pick_pull.sh script (or I can)

**Comment by cynepco3hahue** [comment]
> There's no bot support in upstream k8s, you can run the ./hack/cherry_pick_pull.sh script (or I can)

Thanks for the information, I will do it.

**Comment by smarterclayton** [comment]
Note that I have a PR I'll open soon that correctly accounts for all admitted and still running pods from the pod worker (I.e. any force deleted pod may still be terminating, so GetActivePods is incorrect today).  When that lands it will fix the problem mentioned in the review threads where GetActivePods() is currently not broad enough.

**Comment by cynepco3hahue** [comment]
> Note that I have a PR I'll open soon that correctly accounts for all admitted and still running pods from the pod worker (I.e. any force deleted pod may still be terminating, so GetActivePods is incorrect today). When that lands it will fix the problem mentioned in the review threads where GetActivePods() is currently not broad enough.

Great, thanks for the update.
