### PR TITLE
fix command that is supposed to kill kube-proxy

### LINKED ISSUE #17583: Flake: Services should work after restarting kube-proxy
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gke-ci/9596/

@thockin, please find an owner.

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #17583

Testing this now.

cc @thockin @ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
This probably fixes the test, though there are a few other places that probably need to be updated too:
```console
$ ag "/etc/init.d/kube-proxy" .
test/e2e/util.go
2196:   _, _, code, err := SSH("sudo /etc/init.d/kube-proxy restart", host, testContext.Provider)

cluster/aws/util.sh
1380:  ssh-to-node "$1" "sudo /etc/init.d/kube-proxy restart"

cluster/gce/util.sh
1222:    ssh-to-node "$1" "sudo /etc/init.d/kube-proxy restart"

cluster/saltbase/salt/supervisor/kube-proxy-checker.sh
21:/etc/init.d/kube-proxy stop
22:/etc/init.d/kube-proxy start

cluster/gke/util.sh
276:  ssh-to-node "$1" "sudo /etc/init.d/kube-proxy restart"
```

**Comment by thockin** [comment]
this is good, I have a PR to make SSh output easier to debug.  we should push this ASAP and fix the others in a followup

File: test/e2e/util.go [hunk 1]
```diff
@@ -2193,7 +2193,7 @@ func restartKubeProxy(host string) error {
 	if !providerIs("gce", "gke", "aws") {
 		return fmt.Errorf("unsupported provider: %s", testContext.Provider)
 	}
-	_, _, code, err := SSH("sudo /etc/init.d/kube-proxy restart", host, testContext.Provider)
```
Comment (ixdy) [inline test/e2e/util.go]: also, a minor suggestion (maybe to consider along with a larger cleanup of `SSH` calls): including stderr in the error message probably would've made tracking down this failure much easier (rather than just getting the cryptic "code 1" error message).

**Comment by thockin** [comment]
I am still confused why my e2e cluster came up without the breaking change...

File: test/e2e/util.go [hunk 2]
```diff
@@ -2193,10 +2193,28 @@ func restartKubeProxy(host string) error {
...
+	_, _, code, err := SSH("sudo /bin/sh -c 'pgrep kube-proxy | xargs kill'", host, testContext.Provider)
```
Comment (liggitt) [inline test/e2e/util.go]: not `pkill`? also what is restarting the proxy, now that we're not calling restart ourselves? a comment would probably be helpful

**Comment by mikedanese** [comment]
@thockin I updated this to wait for kube-proxy to recover as well.

@ixdy thanks for the heads up. I will go through those instances in a followup

**Comment by thockin** [comment]
LGTM

File: test/e2e/util.go [hunk 3]
```diff
@@ -2193,10 +2193,28 @@ func restartKubeProxy(host string) error {
...
+			return false, err
+		}
+		if code != 0 {
+			return false, fmt.Errorf("failed to run command, exited %v: %v", code, stderr)
+		}
+		if stdout == "0\n" {
+			return false, nil
+		}
+		Logf("kube-proxy is back up.")
+		return ture, nil
```
Comment (thockin) [inline test/e2e/util.go]: s/ture/true

Comment (mikedanese) [inline test/e2e/util.go]: Fixed

**Comment by mikedanese** [comment]
@liggitt Fixed

File: test/e2e/util.go (hunk 1 above)
Comment (mikedanese) [inline test/e2e/util.go]: Agree, but will defer to a later PR

Comment (ixdy) [inline test/e2e/util.go]: looks like @thockin is doing this in #17591.

**Comment by liggitt** [comment]
thanks

**Comment by lavalamp** [comment]
@mikedanese Are you confident enough that I should merge this instead of #17593?

**Comment by lavalamp** [comment]
@thockin voted for merging this one. I will wait for at least one more thing to pass first though.
