### PR TITLE
Change ImageGCManage to consume ImageFS stats from StatsProvider

### LINKED ISSUE #53083: Consume ImageFS stats from StatsProvider in ImageGCManager
`ImageGCManager` currently uses the ImageFS stats from cadvisor during image garbage collection. This will not work for containerd, where such stats are provided via CRI instead of cadvisor. We should change the `ImageGCManager` to get the stats from the `StatsProvider`, which abstracts away of cadvisor stats vs CRI stats.

/sig node
/assign
/cc @Random-Liu

### PR DESCRIPTION
**Pull request by yguo0905**
Fixes #53083.

**Release note**:

```
Change ImageGCManage to consume ImageFS stats from StatsProvider
```

/assign @Random-Liu

### CODE REVIEW

**Comment by yguo0905** [comment]
@Random-Liu, how do we test this in the containerd integration?

File: pkg/kubelet/images/image_gc_manager.go [hunk 1]
```diff
@@ -244,20 +253,27 @@ func (im *realImageGCManager) detectImages(detectTime time.Time) error {
...
+
 	if available > capacity {
 		glog.Warningf("available %d is larger than capacity %d", available, capacity)
 		available = capacity
 	}
 
 	// Check valid capacity.
 	if capacity == 0 {
-		err := fmt.Errorf("invalid capacity %d on device %q at mount point %q", capacity, fsInfo.Device, fsInfo.Mountpoint)
+		err := goerrors.New("image filesystem has 0 capacity")
```
Comment (Random-Liu) [inline pkg/kubelet/images/image_gc_manager.go]: nit: invalid capacity 0 on image filesystem

**Review by Random-Liu — COMMENTED** [review]
LGTM with one nit.

**Comment by Random-Liu** [comment]
This should be cherrypicked into 1.8 after release.

**Comment by yguo0905** [comment]
without the fix:
```
E0927 10:16:59.263901   19801 kubelet.go:1234] Image garbage collection failed once. Stats initialization may not have completed yet: no imagefs label for configured runtime
...
E0927 10:21:59.264122   19801 kubelet.go:1230] Image garbage collection failed multiple times in a row: no imagefs label for configured runtime
```
with the fix:
```
E0927 10:26:09.554515   15998 cri_stats_provider.go:189] Failed to get the info of the filesystem with id "87cbe5bc-d330-493d-a7bb-1ef0066b8e39": unable to find data for container /.
E0927 10:26:09.554525   15998 kubelet.go:1234] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
...
I0927 10:31:09.555376   15998 kubelet.go:1244] Image garbage collection succeeded
```

File: pkg/kubelet/images/image_gc_manager.go (hunk 1 above)
Comment (yguo0905) [reply pkg/kubelet/images/image_gc_manager.go]: Done.
