### PR TITLE
Fix extended resource flake

### LINKED ISSUE #136696: Test flake: [sig-node] [DRA] kubelet [Feature:DynamicResourceAllocation] on single node supports extended resources together with ResourceClaim [Serial]
### Which jobs are flaking?

https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-kind-dra-all

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/136088/pull-kubernetes-kind-dra-all/2018389374084845568

```
FAILED] FATAL ERROR:
	start pod: Told to stop trying after 2.010s.
	Expected pod to reach phase "Running", got final phase "Failed" instead:
	    <*v1.Pod | 0xc0053b1908>: 
	        metadata:
	          creationTimestamp: "2026-02-02T18:48:12Z"
	          generation: 1
	          managedFields:
	          - apiVersion: v1
	            fieldsType: FieldsV1
	            fieldsV1:
	              f:spec:
	                f:containers:
	                  k:{"name":"with-resource"}:
	                    .: {}
	                    f:command: {}
	                    f:image: {}
	                    f:imagePullPolicy: {}
	                    f:name: {}
	                    f:resources:
	                      .: {}
	                      f:claims:
	                        .: {}
	                        k:{"name":"resource-claim"}:
	                          .: {}
	                          f:name: {}
	                      f:limits:
	                        .: {}
	                        f:example.com/resource: {}
	                      f:requests:
	                        .: {}
	                        f:example.com/resource: {}
	                    f:securityContext:
	                      .: {}
	                      f:allowPrivilegeEscalation: {}
	                      f:capabilities:
	                        .: {}
	                        f:drop: {}
	                    f:terminationMessagePath: {}
	                    f:terminationMessagePolicy: {}
	                f:dnsPolicy: {}
	                f:enableServiceLinks: {}
	                f:resourceClaims:
	                  .: {}
	                  k:{"name":"resource-claim"}:
	                    .: {}
	                    f:name: {}
	                    f:resourceClaimName: {}
	                f:restartPolicy: {}
	                f:schedulerName: {}
	                f:securityContext:
	                  .: {}
	                  f:runAsNonRoot: {}
	                  f:runAsUser: {}
	                  f:seccompProfile:
	                    .: {}
	                    f:type: {}
	                f:terminationGracePeriodSeconds: {}
	            manager: e2e.test
	            operation: Update
	            time: "2026-02-02T18:48:12Z"
	          - apiVersion: v1
	            fieldsType: FieldsV1
	            fieldsV1:
	              f:status:
	                f:nominatedNodeName: {}
	            manager: kube-scheduler
	            operation: Update
	            subresource: status
	            time: "2026-02-02T18:48:12Z"
	          - apiVersion: v1
	            fieldsType: FieldsV1
	            fieldsV1:
	              f:status:
	                f:message: {}
	                f:observedGeneration: {}
	                f:phase: {}
	                f:reason: {}
	                f:startTime: {}
	            manager: kubelet
	            operation: Update
	            subresource: status
	            time: "2026-02-02T18:48:12Z"
	          name: tester-1
	          namespace: dra-1815
	          resourceVersion: "10854"
	          uid: 00ba089d-34c2-4ef6-98e6-0e136e5dc27a
	        spec:
	          containers:
	          - command:
	            - /bin/sh
	            - -c
	            - trap exit TERM; while true; do sleep 1; done
	            image: registry.k8s.io/e2e-test-images/busybox:1.37.0-1
	            imagePullPolicy: IfNotPresent
	            name: with-resource
	            resources:
	              claims:
	              - name: resource-claim
	              limits:
	                example.com/resource: "1"
	              requests:
	                example.com/resource: "1"
	            securityContext:
	              allowPrivilegeEscalation: false
	              capabilities:
	                drop:
	                - ALL
	            terminationMessagePath: /dev/termination-log
	            terminationMessagePolicy: File
	            volumeMounts:
	            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
	              name: kube-api-access-9dwcw
	              readOnly: true
	          dnsPolicy: ClusterFirst
	          enableServiceLinks: true
	          nodeName: kind-worker
	          preemptionPolicy: PreemptLowerPriority
	          priority: 0
	          resourceClaims:
	          - name: resource-claim
	            resourceClaimName: external-claim
	          restartPolicy: Never
	          schedulerName: default-scheduler
	          securityContext:
	            runAsNonRoot: true
	            runAsUser: 1000
	            seccompProfile:
	              type: RuntimeDefault
	          serviceAccount: default
	          serviceAccountName: default
	          terminationGracePeriodSeconds: 30
	          tolerations:
	          - effect: NoExecute
	            key: node.kubernetes.io/not-ready
	            operator: Exists
	            tolerationSeconds: 300
	          - effect: NoExecute
	            key: node.kubernetes.io/unreachable
	            operator: Exists
	            tolerationSeconds: 300
	          volumes:
	          - name: kube-api-access-9dwcw
	            projected:
	              defaultMode: 420
	              sources:
	              - serviceAccountToken:
	                  expirationSeconds: 3607
	                  path: token
	              - configMap:
	                  items:
	                  - key: ca.crt
	                    path: ca.crt
	                  name: kube-root-ca.crt
	              - downwardAPI:
	                  items:
	                  - fieldRef:
	                      apiVersion: v1
	                      fieldPath: metadata.namespace
	                    path: namespace
	        status:
	          message: 'Pod was rejected: Allocate failed due to no healthy devices present; cannot
	            allocate unhealthy devices example.com/resource, which is unexpected'
	          observedGeneration: 1
	          phase: Failed
	          qosClass: BestEffort
	          reason: UnexpectedAdmissionError
	          startTime: "2026-02-02T18:48:12Z"
```

### Which tests are flaking?

[sig-node] [DRA] kubelet [Feature:DynamicResourceAllocation] on single node supports extended resources together with ResourceClaim [Serial]

### Since when has it been flaking?

Only seen once on 2026-02-02

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
/wg device-management
/assign @yliaog 
/cc @bart0sh

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup
/kind flake

#### What this PR does / why we need it:

Refactors device plugin deployment code for DRA tests. Fixes test flake.

#### Which issue(s) this PR is related to:

Fixes: #136696

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig node
/assign @yliaog @pohly
/cc @ffromani

### CODE REVIEW

File: test/e2e/dra/utils/builder.go [hunk 1]
```diff
@@ -45,6 +45,7 @@ import (
 	"k8s.io/kubernetes/test/e2e/dra/test-driver/app"
 	"k8s.io/kubernetes/test/e2e/framework"
 	e2epod "k8s.io/kubernetes/test/e2e/framework/pod"
+	e2enode "k8s.io/kubernetes/test/e2e_node"
```
Comment (pohly) [inline test/e2e/dra/utils/builder.go]: I don't like that this package depends on `k8s.io/kubernetes/test/e2e_node`. That's the E2E node suite, not some helper package that is meant to be imported.

Perhaps reverse the dependency and define the constant here?

Comment (pohly) [reply test/e2e/dra/utils/builder.go]: Or find some neutral package?

File: test/e2e/dra/deploy_device_plugin.go [hunk 2]
```diff
@@ -17,24 +17,26 @@ limitations under the License.
...
 	v1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/kubernetes/test/e2e/framework"
 	"k8s.io/kubernetes/test/e2e/storage/utils"
+	e2enode "k8s.io/kubernetes/test/e2e_node"
+	"k8s.io/kubernetes/test/utils/ktesting"
 )
 
-// deployDevicePlugin deploys https://github.com/kubernetes/kubernetes/tree/111a2a0d2dfe13639724506f674bc4f342ccfbab/test/images/sample-device-plugin
+// deployDevicePlugin deploys https://github.com/kubernetes/kubernetes/tree/v1.35.0/test/images/sample-device-plugin
```
Comment (pohly) [inline test/e2e/dra/deploy_device_plugin.go]: Is v1.35.0 somehow "better" than a revision?

I picked a revision instead of "master' because the file might get moved and I wanted a stable link.

With v1.35.0 it might be tempting to bump it up occassionally, which is just unnecessary churn.

Comment (bart0sh) [reply test/e2e/dra/deploy_device_plugin.go]: It's shorter, but I don't mind keeping the revision.

File: test/e2e/dra/utils/builder.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e/dra/utils/builder.go]: moved to test/e2e/framework/node

**Review by SergeyKanzhelev — APPROVED** [review]
/approve

waiting for allocatable sounds like a good idea

File: test/e2e/framework/node/util_sampledevice.go [hunk 3]
```diff
@@ -32,6 +32,10 @@ const (
 	SampleDeviceResourceName = "example.com/resource"
 
 	SampleDeviceEnvVarNamePluginSockDir = "PLUGIN_SOCK_DIR"
+
+	// TODO(vikasc): Instead of hard-coding number of devices, provide number of devices in the sample-device-plugin using configmap
+	// and then use the same here
+	SampleDevsAmount int64 = 2
```
Comment (pohly) [inline test/e2e/framework/node/util_sampledevice.go:38]: If you are just moving the file, why is there this additional TODO comment?

Comment (pohly) [reply test/e2e/framework/node/util_sampledevice.go:38]: I'm not a fan of TODO comments in the code. They tend to never get resolved. Either create a tracking issue or remove the TODO, accepting that this is how it will be forever.

Comment (bart0sh) [reply test/e2e/framework/node/util_sampledevice.go:38]: The comment is still relevant, that's why I moved it as well. This constant was taken from [another file](https://github.com/kubernetes/kubernetes/blob/v1.35.1/test/e2e_node/device_plugin_test.go#L82-L84).

Comment (pohly) [reply test/e2e/framework/node/util_sampledevice.go:38]: But the TODO is basically broken: do we seriously think that "vikasc" will work on this?

What am I as maintainer of test/e2e/framework supposed to do with this TODO? I don't have a choice for code that was added when I wasn't involved, but for new code that I am reviewing I want to know what the plan is to resolve the TODO.

Comment (bart0sh) [reply test/e2e/framework/node/util_sampledevice.go:38]: > do we seriously think that "vikasc" will work on this?

No, but it doesn't have to be him. Anybody can fix it. I can create an issue if it helps, but I doubt it will, to be honest.

Comment (pohly) [reply test/e2e/framework/node/util_sampledevice.go:38]: `TODO(<person>)` are personal TODOs that someone has assigned to themselves - at least that's how I read it.

Please create an issue and link to it here instead.

Comment (pohly) [reply test/e2e/framework/node/util_sampledevice.go:38]: But I'm also fine with not marking this as TODO at all. Instead document where that constant comes from.

Comment (bart0sh) [reply test/e2e/framework/node/util_sampledevice.go:38]: Done

File: test/e2e/framework/node/util_sampledevice.go [hunk 4]
```diff
@@ -32,6 +32,10 @@ const (
 	SampleDeviceResourceName = "example.com/resource"
 
 	SampleDeviceEnvVarNamePluginSockDir = "PLUGIN_SOCK_DIR"
+
+	// SampleDevsAmount is an amount of devices provided by the sample device plugin:
```
Comment (pohly) [inline test/e2e/framework/node/util_sampledevice.go:36]: Language nit (consistent with the constants above):

```suggestion
	// SampleDevsAmount is the amount of devices provided by the sample device plugin:
```

Don't bother changing it.

**Review by pohly — APPROVED** [review]
/lgtm
/approve
