### PR TITLE
handle failed mounts for fc volumes

### LINKED ISSUE #50502: fc disk manager doesn't handle failed mounts
Fc disk manager doesn't handle failed mounts see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/fc/disk_manager.go#L58)

/sig storage
/assign

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**: handles failed mounts for fc

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50502

**Special notes for your reviewer**: 

**Release note**:

```release-note
None
```

### CODE REVIEW

File: pkg/volume/fc/disk_manager.go [hunk 1]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
 	}
 	err = mounter.Mount(globalPDPath, volPath, "", options)
 	if err != nil {
-		glog.Errorf("failed to bind mount:%s", globalPDPath)
+		glog.V(4).Infof("Mount failed: %v", err)
+		noMnt, err = b.mounter.IsLikelyNotMountPoint(volPath)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: This should use mntERR instead of err.
noMnt, mntERR := b.mounter.IsLikelyNotMountPoint(volPath)

File: pkg/volume/fc/disk_manager.go [hunk 2]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+		if err != nil {
+			glog.Errorf("IsLikelyNotMountPoint check failed: %v", err)
+			return err
+		}
+		if !noMnt {
+			if err = b.mounter.Unmount(volPath); err != nil {
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: This should use mntERR instead of err.
if mntERR = b.mounter.Unmount(volPath); mntERR != nil {

File: pkg/volume/fc/disk_manager.go [hunk 3]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+				glog.Errorf("Failed to unmount: %v", err)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: ditto.

File: pkg/volume/fc/disk_manager.go [hunk 4]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
 	}
 	err = mounter.Mount(globalPDPath, volPath, "", options)
 	if err != nil {
-		glog.Errorf("failed to bind mount:%s", globalPDPath)
+		glog.V(4).Infof("Mount failed: %v", err)
+		noMnt, err = b.mounter.IsLikelyNotMountPoint(volPath)
+		if err != nil {
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: ditto.

File: pkg/volume/fc/disk_manager.go [hunk 5]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+			glog.Errorf("IsLikelyNotMountPoint check failed: %v", err)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: ditto.

File: pkg/volume/fc/disk_manager.go [hunk 6]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+			return err
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: This return should return original error. So this line is ok.

File: pkg/volume/fc/disk_manager.go [hunk 7]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+		}
+		if !noMnt {
+			if err = b.mounter.Unmount(volPath); err != nil {
+				glog.Errorf("Failed to unmount: %v", err)
+				return err
+			}
+			noMnt, err = b.mounter.IsLikelyNotMountPoint(volPath)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: This should use mntERR instead of err.

File: pkg/volume/fc/disk_manager.go [hunk 8]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+			if err != nil {
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: ditto.

File: pkg/volume/fc/disk_manager.go [hunk 9]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+				glog.Errorf("IsLikelyNotMountPoint check failed: %v", err)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: ditto.

File: pkg/volume/fc/disk_manager.go [hunk 10]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+				return err
+			}
+			if !noMnt {
+				//  will most likely retry on next sync loop.
+				glog.Errorf("%s is still mounted, despite call to unmount().  Will try again next sync loop.", b.GetPath())
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: Are there any reason to use b.GetPath() here instead of volPath?

File: pkg/volume/fc/disk_manager.go [hunk 11]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
 	}
 	err = mounter.Mount(globalPDPath, volPath, "", options)
 	if err != nil {
-		glog.Errorf("failed to bind mount:%s", globalPDPath)
+		glog.V(4).Infof("Mount failed: %v", err)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: I prefer to log error like this instead of log info.
```
glog.Errorf("Failed to bind mount: source:%s, target:%s, err:%v", globalPDPath, volPath, err)
```

File: pkg/volume/fc/disk_manager.go [hunk 12]
```diff
@@ -57,7 +57,31 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+			}
+			if !noMnt {
+				//  will most likely retry on next sync loop.
+				glog.Errorf("%s is still mounted, despite call to unmount().  Will try again next sync loop.", b.GetPath())
+				return err
+			}
+		}
+		os.Remove(volPath)
+
+		glog.Errorf("Failed to mount %s: %v", volPath, err)
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: If we log error on the top, we don't need this log error.

File: pkg/volume/fc/disk_manager.go (hunk 1 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Thanks for the review, i'll adress your comments asap

**Comment by yastij** [comment]
PTAL @mtanino

File: pkg/volume/fc/disk_manager.go (hunk 11 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 1 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 4 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 12 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 10 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 9 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 8 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 7 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 3 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 2 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 6 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go (hunk 5 above)
Comment (yastij) [inline pkg/volume/fc/disk_manager.go]: Fixed.

File: pkg/volume/fc/disk_manager.go [hunk 13]
```diff
@@ -57,31 +56,30 @@ func diskSetUp(manager diskManager, b fcDiskMounter, volPath string, mounter mou
...
+			glog.Errorf("IsLikelyNotMountPoint check failed: %v", mntErr)
 			return err
 		}
 		if !noMnt {
-			if err = b.mounter.Unmount(volPath); err != nil {
-				glog.Errorf("Failed to unmount: %v", err)
-				return err
+			if mntErr = b.mounter.Unmount(volPath); mntErr != nil {
+				glog.Errorf("Failed to unmount: %v", mntErr)
+				return mntErr
```
Comment (mtanino) [inline pkg/volume/fc/disk_manager.go]: I think it's better to return original "err" here instead of returning mntErr.

Comment (mtanino) [reply pkg/volume/fc/disk_manager.go]: @yastij Could you change above?

**Comment by yastij** [comment]
@mtanino - sorry for the delay, commits squashed, this LGTY ? do we need a release note for this ?

 also ping @rootfs for approval.

**Comment by mtanino** [comment]
@yastij 
Thank you for the update. Look good to me.
