### PR TITLE
Use UnmountMountPoint util to clean up subpaths

### LINKED ISSUE #71584: Pod using subpath with nfs is stuck in terminating
**What happened**:
NFS server got restarted and caused the nfs mounts to be stale.  Pod deletion hung with:
```
Error: "error cleaning subPath mounts for volume \"nfs-content\": error reading /var/lib/kubelet/pods/redacted/volume-subpaths/nfs-content/redacted: lstat /var/lib/kubelet/pods/redacted/volume-subpaths/nfs-content/redacted/2: stale NFS file handle"
```

**What you expected to happen**:
I think the [subpath directory traversing](https://github.com/kubernetes/kubernetes/blob/v1.9.7/pkg/util/mount/mount_linux.go#L780) needs to check for a [stale mount](https://github.com/kubernetes/kubernetes/blob/v1.9.7/pkg/volume/util/util.go#L184)

**How to reproduce it (as minimally and precisely as possible)**:
I have not been able to repro the stale nfs mount.  These are the steps I tried:
1. start a nfs-server using https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs
2. create a pod using subpath with nfs. write data into the subpath.
3. restart the nfs-server pod
4. Write more data into the subpath
5. delete pod

In my test, the nfs mount is able to recover from the nfs server restarting.  Maybe my next attempt to repro should bring the nfs server down for longer.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
UnmountMountPoint is a wrapper util that handles corrupt and stale mounts.  Cleaning subpaths mounts should use the util instead of directly calling Unmount.

**Which issue(s) this PR fixes**:

Fixes #71584

**Special notes for your reviewer**:
To make this small for backporting, I've tried to do the minimum changes required and will look into refactoring/cleanup afterwards. 

**Does this PR introduce a user-facing change?**:

```release-note
Fixes issue with cleaning up stale NFS subpath mounts
```

### CODE REVIEW

File: pkg/util/mount/mount_linux.go [hunk 1]
```diff
@@ -1329,3 +1330,107 @@ func searchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
...
+		}
+
+		if notMnt {
+			klog.Warningf("Warning: %q is not a mountpoint, deleting", mountPath)
+			return os.Remove(mountPath)
+		}
+	}
+
+	// Unmount the mount path
+	// TODO: MSAU does unmounting a stale nfs mount actually succeed?
```
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: I need to repro the stale nfs error on a real system to confirm

File: pkg/util/mount/mount_linux.go [hunk 2]
```diff
@@ -1329,3 +1330,107 @@ func searchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
...
+func PathExists(path string, mounter Interface) (bool, error) {
+	_, err := mounter.ExistsPath(path)
+	if err == nil {
+		return true, nil
+	} else if os.IsNotExist(err) {
+		return false, nil
+	} else if IsCorruptedMnt(err) {
+		return true, err
+	} else {
+		// TODO: MSAU: should unknown err return pathExists=true for safety?
```
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: The original function returned false. I think it should actually return true otherwise we may return cleanup success for unknown errors.

File: pkg/util/mount/mount_linux.go [hunk 3]
```diff
@@ -1329,3 +1330,107 @@ func searchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
...
+		klog.V(4).Infof("%q is unmounted, deleting the directory", mountPath)
+		return os.Remove(mountPath)
+	}
+	return fmt.Errorf("Failed to unmount path %v", mountPath)
+}
+
+// PathExists returns true if the specified path exists.
+// TODO: MSAU this is not a good name
+func PathExists(path string, mounter Interface) (bool, error) {
+	_, err := mounter.ExistsPath(path)
```
Comment (msau42) [inline pkg/util/mount/mount_linux.go]: This may not work for containerized kubelet because it would cause the path to be checked based on the host, not inside the kubelet container.

I will change it back to os.Stat().  I will need to figure out a different way to unit test this.

File: pkg/util/mount/mount_linux.go (hunk 2 above)
Comment (msau42) [reply pkg/util/mount/mount_linux.go]: changed it back to original for now.  I see util/file/FileExists also returns false for all errors.

**Comment by msau42** [comment]
Still todo:
* Figure out a way to unit test this
* Write an e2e test
* Open up issues for refactoring/cleanup

File: pkg/util/mount/mount_linux.go [hunk 4]
```diff
@@ -926,19 +933,13 @@ func doCleanSubPath(mounter Interface, fullContainerDirPath, subPathIndex string
...
-		}
-		klog.V(5).Infof("Unmounted %s", fullSubPath)
+
+	if err := UnmountMountPoint(fullSubPath, mounter, true); err != nil {
+		return fmt.Errorf("error unmounting %s: %s", fullSubPath, err)
 	}
+
 	// Remove it *non*-recursively, just in case there were some hiccups.
-	if err = os.Remove(fullSubPath); err != nil {
+	if err := os.Remove(fullSubPath); err != nil && !os.IsNotExist(err) {
```
Comment (saad-ali) [inline pkg/util/mount/mount_linux.go]: Is this necessary now that `UnmountMountPoint` is used which deletes the path?

File: test/e2e/storage/subpath.go [hunk 5]
```diff
@@ -116,4 +120,56 @@ var _ = utils.SIGDescribe("Subpath", func() {
...
+		BeforeEach(func() {
+			_, nfsServerPod, nfsServerIP = framework.NewNFSServer(f.ClientSet, f.Namespace.Name, []string{"-G", "777", "/exports"})
+
+		})
+
+		AfterEach(func() {
+			framework.DeletePodWithWait(f, f.ClientSet, nfsServerPod)
+		})
+
+		It("should be able to unmount a stale NFS handle", func() {
```
Comment (msau42) [inline test/e2e/storage/subpath.go]: Other than the nfs driver setup, I think this test case actually can work across any volume type (remove the subpath directory while it's still bind mounted to the container).  Will look into moving this into the framework

File: pkg/util/mount/mount_linux.go (hunk 4 above)
Comment (msau42) [reply pkg/util/mount/mount_linux.go]: good catch, removed

File: test/e2e/storage/subpath.go (hunk 5 above)
Comment (msau42) [reply test/e2e/storage/subpath.go]: done

**Comment by msau42** [comment]
/hold
I need help testing this against containerized kubelet cc @jsafrane @gnufied

File: test/e2e/storage/subpath.go [hunk 6]
```diff
@@ -17,7 +17,7 @@ limitations under the License.
 package storage
 
 import (
-	"k8s.io/api/core/v1"
```
Comment (msau42) [inline test/e2e/storage/subpath.go]: revert this file

**Comment by jsafrane** [comment]
Tested with containerized kubelet, it does not clean up NFS with deleted subpath before the patch and cleans it up correctly after the patch.

File: pkg/util/mount/mount_helper.go [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+func UnmountPath(mountPath string, mounter Interface) error {
+	return UnmountMountPoint(mountPath, mounter, false /* extensiveMountPointCheck */)
+}
+
+// UnmountMountPoint is a common unmount routine that unmounts the given path and
+// deletes the remaining directory if successful.
+// if extensiveMountPointCheck is true
+// IsNotMountPoint will be called instead of IsLikelyNotMountPoint.
+// IsNotMountPoint is more expensive but properly handles bind mounts.
+func UnmountMountPoint(mountPath string, mounter Interface, extensiveMountPointCheck bool) error {
```
Comment (jingxu97) [inline pkg/util/mount/mount_helper.go]: As we discussed offline, since this function includes both unmounting and deleting dirs, maybe rename the function to make it more clear?

File: pkg/util/mount/mount_helper.go [hunk 8]
```diff
@@ -0,0 +1,129 @@
...
+// if extensiveMountPointCheck is true
+// IsNotMountPoint will be called instead of IsLikelyNotMountPoint.
+// IsNotMountPoint is more expensive but properly handles bind mounts.
+// if corruptedMnt is true, it means that the mountPath is a corrupted mountpoint, Take it as an argument for convenience of testing
+func doUnmountMountPoint(mountPath string, mounter Interface, extensiveMountPointCheck bool, corruptedMnt bool) error {
+	if !corruptedMnt {
+		var notMnt bool
+		var err error
+		if extensiveMountPointCheck {
+			notMnt, err = IsNotMountPoint(mounter, mountPath)
```
[the remark this answers is not in the document]
Comment (msau42) [reply pkg/util/mount/mount_helper.go]: We can investigate as part of https://github.com/kubernetes/kubernetes/issues/72347

File: pkg/util/mount/mount_helper.go (hunk 7 above)
Comment (msau42) [reply pkg/util/mount/mount_helper.go]: renamed to "CleanupMountPoint"

File: pkg/util/mount/mount_linux.go [hunk 9]
```diff
@@ -926,21 +933,11 @@ func doCleanSubPath(mounter Interface, fullContainerDirPath, subPathIndex string
...
-			return fmt.Errorf("error unmounting %s: %s", fullSubPath, err)
-		}
-		klog.V(5).Infof("Unmounted %s", fullSubPath)
-	}
-	// Remove it *non*-recursively, just in case there were some hiccups.
-	if err = os.Remove(fullSubPath); err != nil {
-		return fmt.Errorf("error deleting %s: %s", fullSubPath, err)
+
+	if err := CleanupMountPoint(fullSubPath, mounter, true); err != nil {
+		return fmt.Errorf("error unmounting %s: %s", fullSubPath, err)
```
Comment (jingxu97) [inline pkg/util/mount/mount_linux.go]: Since it includes both unmounting and deleting, maybe update the error msg to error in cleaning up ...

File: pkg/util/mount/mount_helper.go [hunk 10]
```diff
@@ -0,0 +1,124 @@
...
+
+	notMnt, mntErr := mounter.IsLikelyNotMountPoint(mountPath)
+	if mntErr != nil {
+		return mntErr
+	}
+	if notMnt {
+		klog.V(4).Infof("%q is unmounted, deleting the directory", mountPath)
+		return os.Remove(mountPath)
+	}
+	return fmt.Errorf("Failed to unmount path %v", mountPath)
```
Comment (tedyu) [inline pkg/util/mount/mount_helper.go]: The message here seems inaccurate : the path is likely mount point

File: pkg/util/mount/mount_helper.go [hunk 11]
```diff
@@ -0,0 +1,124 @@
...
+}
+
+// TODO: clean this up to use pkg/util/file/FileExists
```
Comment (tedyu) [inline pkg/util/mount/mount_helper.go]: There are more than one version of FileExists:

pkg/kubelet/kubeletconfig/util/files/files.go
vendor/golang.org/x/tools/go/buildutil/util.go

I wonder which one we should use.
