### PR TITLE
No timeout when Kubelet Calling cni plugin

### LINKED ISSUE #65743: No timeout when Kubelet Calling cni plugin
**BUG REPORT**:

/kind bug

**What happened**:
When the kubelet create sandbox by cni plugin.
It will just use exec.Cmd to call the cni binary file.
In some cni plugin,such as contiv,the cni binary file may be locked and no return.
In this case, when kubelet first time call RunPodSandbox got a ctx timeout. the next time kubelet re-creates PodSandbox, it will always report this timeout.

image

**What you expected to happen**:
Next time  kubelet re-creates PodSandbox it will do call cni again.

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod in a node,and make the cni binary file not return.

**Environment**:
- Kubernetes version (use `kubectl version`):v.1.9.2

@kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by liucimin**
**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65743

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
The docker container runtime now enforces a 220 second timeout on container network operations.
```

### CODE REVIEW

**Review by bboreham — COMMENTED** [review]
Code looks plausible; where is the test that shows this fixes the problem?

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 1]
```diff
@@ -34,6 +36,7 @@ import (
 	"k8s.io/kubernetes/pkg/kubelet/dockershim/network"
 	"k8s.io/kubernetes/pkg/util/bandwidth"
 	utilexec "k8s.io/utils/exec"
+
```
Comment (dcbw) [inline pkg/kubelet/dockershim/network/cni/cni.go]: Spurious newline...

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 2]
```diff
@@ -280,14 +283,17 @@ func (plugin *cniNetworkPlugin) SetUpPod(namespace string, name string, id kubec
 		return fmt.Errorf("CNI failed to retrieve network namespace path: %v", err)
 	}
 
+	// Because the default remote runtime request timeout is 2 min
+	// Todo get the timeout from parent ctx
```
Comment (dcbw) [inline pkg/kubelet/dockershim/network/cni/cni.go]: Should it be slightly less than 2m so that we ensure the network timeout triggers before the remote runtime one does?

File: pkg/kubelet/dockershim/network/cni/cni_test.go [hunk 3]
```diff
@@ -45,6 +46,7 @@ import (
 	networktest "k8s.io/kubernetes/pkg/kubelet/dockershim/network/testing"
 	"k8s.io/utils/exec"
 	fakeexec "k8s.io/utils/exec/testing"
+
```
Comment (dcbw) [inline pkg/kubelet/dockershim/network/cni/cni_test.go]: Another blank line that could be removed.

File: pkg/kubelet/dockershim/network/cni/cni_windows.go [hunk 4]
```diff
@@ -43,7 +45,10 @@ func (plugin *cniNetworkPlugin) GetPodNetworkStatus(namespace string, name strin
 		return nil, fmt.Errorf("CNI failed to retrieve network namespace path: %v", err)
 	}
 
-	result, err := plugin.addToNetwork(plugin.getDefaultNetwork(), name, namespace, id, netnsPath, nil, nil)
+	// Because the default remote runtime request timeout is 2 min
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, _ := context.WithTimeout(context.Background(), 2 * time.Minute)
```
Comment (dcbw) [inline pkg/kubelet/dockershim/network/cni/cni_windows.go]: Same here; maybe slightly less than 2m?

**Review by dcbw — COMMENTED** [review]
Just a couple small comments/nits.

**Comment by dcbw** [comment]
@liucimin a couple other things:

1. could you run gofmt on the files to fix the bazel test?
2. looks like the 'pull-kubernetes-verify' test failed too in one of the testcases, could you take a look at that and see if it's an easy fix?
3. Also a release note in the PR description might be worthwhile (see https://github.com/kubernetes/kubernetes/pull/71653#issuecomment-443619767 for more details); perhaps just mention that dockershim network plugin operations are now time-bounded to about 2 minutes

File: pkg/kubelet/dockershim/network/cni/cni_test.go (hunk 3 above)
Comment (liucimin) [reply pkg/kubelet/dockershim/network/cni/cni_test.go]: Thx

File: pkg/kubelet/dockershim/network/cni/cni.go (hunk 2 above)
Comment (liucimin) [reply pkg/kubelet/dockershim/network/cni/cni.go]: The remote timeout is 2 times longer timeout for sandbox operation (4 mins by default).
And the RuntimeRequestTimeout is configurable.
So is hard to choose the cni timeout .
Now i choose 220s to slightly less than 4mins.
Maybe next time i can find a method to get the RuntimeRequestTimeout in grpc server.

**Comment by liucimin** [comment]
pull-kubernetes-bazel-test failed 
image


setCachedResult in libcni will use a default dir to set cached.but the default dir is read only in test mechine.
Have u get any suggestion to  fix these problem.?

@dcbw

**Comment by bboreham** [comment]
File that as an issue against the CNI project.

**Comment by liucimin** [comment]
> File that as an issue against the CNI project.

Ok i have open a issue in the CNI project

**Comment by dcbw** [comment]
> setCachedResult in libcni will use a default dir to set cached.but the default dir is read only in test mechine.
> Have u get any suggestion to fix these problem.?

@liucimin you can set the cachedir to a test directory that the testcases create, that will be writable, by setting the CacheDir field in RuntimeConf.  So you could add a cacheDir parameter to buildCNIRuntimeConf() and addToNetwork/deleteFromNetwork(). Then perhaps add a field in cniNetworkPlugin for the cachedir which probeNetworkPluginsWithVendorCNIDirPrefix() would accept and set. Testcases would set their test dir there, while dockershim would pass "".

**Comment by liucimin** [comment]
@dcbw 

Finally i pass all the test..
Thx for your suggestion.

**Comment by dcbw** [comment]
@liucimin could you update the PR description to add a release note?  See https://git.k8s.io/community/contributors/guide/release-notes.md for more details. Perhaps "The docker container runtime now enforces a 220 second timeout on container network operations."

/lgtm

**Comment by dcbw** [comment]
@yujuhong @bowei @freehan could you take a look at this one too?  Thanks!

**Comment by dcbw** [comment]
> You are referencing an alpha version of CNI from the Godeps. Is this on purpose?

@bowei we're pretty close to releasing CNI, just waiting on dogfooding the CHECK functionality in the CNI reference plugins which is in-progress. The timeout/context stuff that this PR relies on is only in the alpha version, and it will not change before the release.

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 5]
```diff
@@ -124,6 +127,7 @@ func ProbeNetworkPlugins(confDir string, binDirs []string) []network.NetworkPlug
 		execer:         utilexec.New(),
 		confDir:        confDir,
 		binDirs:        binDirs,
+		cacheDir:       cacheDir,
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/network/cni/cni.go]: What does `cahceDir` do? Should it be configurable?

File: pkg/kubelet/dockershim/network/cni/cni.go (hunk 2 above)
Comment (yujuhong) [reply pkg/kubelet/dockershim/network/cni/cni.go]: Should we just use the parent context? It seems more complicated to derive and set the timeout from the parent context?

File: pkg/kubelet/dockershim/network/cni/cni.go (hunk 5 above)
Comment (liucimin) [reply pkg/kubelet/dockershim/network/cni/cni.go]: It transfer to the libcni.
if the value is empty,the libcni will use a default cache dir to save the network result.

**Comment by nikopen** [comment]
@liucimin @dcbw Code Freeze lands in 7 days, can this be merged in 2 weeks from now?

**Comment by liucimin** [comment]
@nikopen 
The upstrem cni have not realease a new version.
Although i think it can be merged first to fix hanging bug.
When the cni realease a new version,i will upgrade the vendor again.

**Comment by nikopen** [comment]
@dcbw any updates on a new CNI release? or can this just be merged?

**Comment by spiffxp** [comment]
/milestone clear
v1.14 release lead here, as we have now entered Code Freeze and this seems nowhere near completion nor aimed at fixing a release blocking bug or test failure/flake, I’m removing it from the milestone. Please talk to the relevant SIG to add this back in if you feel this was done in error.

**Comment by calder** [comment]
@spiffxp: It makes sense not to block release on this since it exists in the current Kubernetes release, but this has dragged on for close to a year now and is causing serious pain. What can all the folks over in https://github.com/kubernetes/kubernetes/issues/45419 do to get this prioritized higher? (CC @thockin)

**Comment by nikopen** [comment]
Indeed it's been a very pesky bug in all production environments, but it's depending on cni which seems to be rather stale for a while now? If this can be prioritized for post-release cherry picking that would be great (1.14.1 and 1.13 1.12).

CNI people seem to be quite unresponsive on that - @kubernetes/sig-network-bugs @dcbw @bboreham ?

**Comment by calder** [comment]
@kubernetes/sig-network-bugs @thockin @dcbw @bboreham: Friendly ping.

**Comment by calder** [comment]
@kubernetes/sig-network-bugs @dcbw @bboreham ?

**Comment by nikopen** [comment]
@liucimin CNI 0.7.5 is released?

**Comment by liucimin** [comment]
@nikopen 
CNI 0.7.5 is the cni plugins.
But we need the libcni,and Unfortunately it still at 0.6.0.

**Comment by bboreham** [comment]
As I’ve said multiple times in the linked issues there was never any need to wait for a CNI release. I see that you might choose to for final release, but currently it is inconvenient to stamp libcni because a new feature in the Spec in the same repo isn’t fully tested. 

If you’d like to find out how to help the CNI project, please inquire.

**Comment by bboreham** [comment]
At today's CNI maintainers meeting we decided libcni is ready to release - you can use tag `v0.7.0-rc2` to check what that release will contain.

**Comment by calder** [comment]
@kubernetes/sig-network-bugs @dcbw @bboreham: Friendly ping.

**Comment by bboreham** [comment]
Libcni v0.7.0 is now released.

**Comment by nikopen** [comment]
@liucimin let's fix this when convenient

/milestone v1.15

**Comment by liucimin** [comment]
@nikopen 
Thx for the remind.
I have update the libcni to v0.7.0.

**Comment by nikopen** [comment]
/assign @liggitt @lavalamp 

approval needed

**Comment by liggitt** [comment]
/hold 

the same bump is being attempted in https://github.com/kubernetes/kubernetes/pull/69821 and there is an unresolved question about whether the cache dir change is ok (https://github.com/kubernetes/kubernetes/pull/69821#discussion_r280274171). It assumes a hard-coded cache-dir is writeable and fails if it is not.

**Comment by liggitt** [comment]
@thockin deferred that one to @freehan, so
/cc @freehan

**Comment by soggiest** [comment]
Hello! Code Freeze is just about on us. We'll be entering into Freeze tomorrow, May 31st. Is this still planned to land in 1.15?

**Comment by nikopen** [comment]
this is a good stability fix, let's get it in.

@soggiest let's find and ping @freehan if there's capacity to review it in time

**Comment by soggiest** [comment]
@freehan will you have time to review this?

**Comment by dims** [comment]
@cblecker @thockin this has an update of github.com/containernetworking/cni to v0.7.0 PTAL

cc @kubernetes/dep-approvers

**Comment by cblecker** [comment]
Approved for dep. No concerns for the CRI bump.

**Comment by soggiest** [comment]
@thocking If this is release blocking can you please approve this PR so we can merge it?

File: pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go [hunk 6]
```diff
@@ -570,7 +571,11 @@ func (plugin *kubenetNetworkPlugin) addContainerToNetwork(config *libcni.Network
 	// The network plugin can take up to 3 seconds to execute,
 	// so yield the lock while it runs.
 	plugin.mu.Unlock()
-	res, err := plugin.cniConfig.AddNetwork(config, rt)
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (thockin) [inline pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go]: Can 220 be a const somewhere, please

**Comment by thockin** [comment]
I am OK with the change in theory - @dcbw - ok with CNI and kubenet?

File: pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go (hunk 6 above)
Comment (dcbw) [reply pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go]: @liubin @thockin const yes please :)

Comment (dcbw) [reply pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go]: Just put the const into pkg/kubelet/dockershim/network/network.go and use it from everywhere else that needs it.

**Comment by dcbw** [comment]
@thockin yep CNI and kubenet look OK in theory. So:

/approve

but not lgtm yet pending update for const thing.

**Comment by liggitt** [comment]
did the open question about writeable hard-coded cache dir get resolved?

**Comment by dcbw** [comment]
> did the open question ([#69821 (comment)](https://github.com/kubernetes/kubernetes/pull/69821#discussion_r280274171)) about writeable hard-coded cache dir get resolved?

No, it didn't. Kubenet (because it uses host-local) already requires /var/lib/cni/networks to be writable, so this isn't hugely different. Should this be noted somewhere in release notes then?

**Comment by dcbw** [comment]
Since both this and another issue need to bump CNI, I pushed PR https://github.com/kubernetes/kubernetes/pull/78908 to do this and address @liggit's directory question.

**Comment by dcbw** [comment]
@liucimin can you rebase to pick up the CNI 0.7.1 changes from https://github.com/kubernetes/kubernetes/pull/78908? thanks!

**Comment by liucimin** [comment]
@dcbw 
Of course i will~
Thx for your suggestions.

**Comment by cblecker** [comment]
Failures are legitimate. Please review and fix.

**Comment by liucimin** [comment]
@dcbw 
Friendly ping.
This pr have someone help me to review?

**Comment by dims** [comment]
@liucimin looks like one suggestion is still to be done? `Just put the const into pkg/kubelet/dockershim/network/network.go and use it from everywhere else that needs it.`?

**Comment by xmudrii** [comment]
@liucimin @dcbw Hello! I'm the bug triage lead for the 1.16 release cycle and considering this PR is tagged for 1.16, I'd like to check its status. The code freeze is starting on August 29th EOD PST (about 5 days from now) and once the code freeze starts, only release-blocking PRs will be considered to be merged. Is this PR still planned for the 1.16 release?

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 7]
```diff
@@ -292,15 +292,18 @@ func (plugin *cniNetworkPlugin) SetUpPod(namespace string, name string, id kubec
 	if err != nil {
 		return fmt.Errorf("CNI failed to retrieve network namespace path: %v", err)
 	}
-
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/cni/cni.go]:
```suggestion
```

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 8]
```diff
@@ -292,15 +292,18 @@ func (plugin *cniNetworkPlugin) SetUpPod(namespace string, name string, id kubec
...
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/cni/cni.go]:
```suggestion
	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), network.CNITimeoutSec*time.Second)
```

File: pkg/kubelet/dockershim/network/cni/cni_windows.go [hunk 9]
```diff
@@ -43,8 +45,11 @@ func (plugin *cniNetworkPlugin) GetPodNetworkStatus(namespace string, name strin
 		return nil, fmt.Errorf("CNI failed to retrieve network namespace path: %v", err)
 	}
 
-	result, err := plugin.addToNetwork(plugin.getDefaultNetwork(), name, namespace, id, netnsPath, nil, nil)
-
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/cni/cni_windows.go]:
```suggestion
	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), network.CNITimeoutSec*time.Second)
```

File: pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go [hunk 10]
```diff
@@ -691,8 +691,11 @@ func (plugin *kubenetNetworkPlugin) addContainerToNetwork(config *libcni.Network
 	}
 
 	klog.V(3).Infof("Adding %s/%s to '%s' with CNI '%s' plugin and runtime: %+v", namespace, name, config.Network.Name, config.Network.Type, rt)
-
-	res, err := plugin.cniConfig.AddNetwork(context.TODO(), config, rt)
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go]:
```suggestion
	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), network.CNITimeoutSec*time.Second)
```

File: pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go [hunk 11]
```diff
@@ -706,7 +709,11 @@ func (plugin *kubenetNetworkPlugin) delContainerFromNetwork(config *libcni.Netwo
 	}
 
 	klog.V(3).Infof("Removing %s/%s from '%s' with CNI '%s' plugin and runtime: %+v", namespace, name, config.Network.Name, config.Network.Type, rt)
-	err = plugin.cniConfig.DelNetwork(context.TODO(), config, rt)
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go]:
```suggestion
	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), network.CNITimeoutSec*time.Second)
```

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 12]
```diff
@@ -315,14 +318,18 @@ func (plugin *cniNetworkPlugin) TearDownPod(namespace string, name string, id ku
 		klog.Warningf("CNI failed to retrieve network namespace path: %v", err)
 	}
 
-	return plugin.deleteFromNetwork(plugin.getDefaultNetwork(), name, namespace, id, netnsPath, nil)
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
+	// Todo get the timeout from parent ctx
+	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), 220*time.Second)
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/cni/cni.go]:
```suggestion
	cniTimeoutCtx, cancelFunc := context.WithTimeout(context.Background(), network.CNITimeoutSec*time.Second)
```

File: pkg/kubelet/dockershim/network/cni/cni.go [hunk 13]
```diff
@@ -315,14 +318,18 @@ func (plugin *cniNetworkPlugin) TearDownPod(namespace string, name string, id ku
 		klog.Warningf("CNI failed to retrieve network namespace path: %v", err)
 	}
 
-	return plugin.deleteFromNetwork(plugin.getDefaultNetwork(), name, namespace, id, netnsPath, nil)
+	// Because the default remote runtime request timeout is 4 min,so set slightly less than 240 seconds
```
Comment (nikopen) [inline pkg/kubelet/dockershim/network/cni/cni.go]:
```suggestion
```

**Comment by nikopen** [comment]
opened #81912 to push this forward, let's merge it before freeze
@liucimin @dcbw @dims

**Comment by nikopen** [comment]
As the author is absent, I have opened another PR that moves 220 to a constant and applies the suggestions above. Let's merge this.

**Comment by liucimin** [comment]
Sorry for the absent
I will change this to constant var today

发自我的iPhone


------------------ Original ------------------

**Comment by nikopen** [comment]
Thanks for the response!

/hold

**Comment by liucimin** [comment]
@nikopen 
I have fix the review recommed.

**Comment by nikopen** [comment]
Excellent! Let's get this in.

Thank you for your lengthy work on this!

/lgtm

**Comment by nikopen** [comment]
@liucimin there's a last minute conflict... can you resolve it?

**Comment by nikopen** [comment]
@liucimin I've resolved the conflicts, still you'll need to rebase your branch...

**Comment by nikopen** [comment]
missed a change... you also have to change line 337 of cni.go:
`		if err := plugin.deleteFromNetwork(plugin.loNetwork, name, namespace, id, netnsPath, nil); err != nil {`
to:
`		if err := plugin.deleteFromNetwork(**cniTimeoutCtx**, plugin.loNetwork, name, namespace, id, netnsPath, nil); err != nil {`

**Comment by guineveresaenger** [comment]
Hi @liucimin and @nikopen - I'm shadowing the 1.16 Release Lead and we'd like this merged before EOD 9/9 for the rc release cut.

I see it's already approved and there's some rebasing going on, so anything you can do to get this across the finish line would be 💯 .

Thank you!

**Comment by guineveresaenger** [comment]
@liucimin - can you rebase and try running the test again?

**Comment by nikopen** [comment]
@liucimin sorry for all the hassle! You'll need to squash the commits (the last two ones) and resolve the new conflict at cni_test.go. With that, hopefully it can finally merge.

I think we can just leave this out for 1.16.0 and cherrypick it to 1.14, 1.15, 1.16.1 etc which have a CNI version that supports this feature. The eclipsing 1.13 has an older CNI version anyway.
The branch hit last minute conflicts like 3 times now and takes a while...

/milestone 1.17

**Comment by nikopen** [comment]
almost there... needs a newline at the end of /pkg/kubelet/dockershim/network/network.go

File: pkg/kubelet/dockershim/network/cni/cni.go (hunk 2 above)
Comment (tedyu) [reply pkg/kubelet/dockershim/network/cni/cni.go]: Created #82913 for this TODO

**Comment by jberkus** [comment]
Hey, the release note here is a bit confusing for users; can you clarify what the impact is for devs and admins?

File: pkg/kubelet/dockershim/network/cni/cni.go (hunk 2 above)
Comment (snowplayfire) [reply pkg/kubelet/dockershim/network/cni/cni.go]: > The remote timeout is 2 times longer timeout for sandbox operation (4 mins by default).
> And the RuntimeRequestTimeout is configurable.
> So is hard to choose the cni timeout .
> Now i choose 220s to slightly less than 4mins.
> Maybe next time i can find a method to get the RuntimeRequestTimeout in grpc server.

Can you tell me why the remote timeout is 2 times longer timeout for sandbox operation？ Thanks very much!

**Comment by jmf0526** [comment]
Hi there, I'm hitting the no timeout issue in 1.15, is there any change that this PR would be backported to 1.15?

**Comment by jmf0526** [comment]
> I think we can just leave this out for 1.16.0 and cherrypick it to 1.14, 1.15, 1.16.1 etc which have a CNI version that supports this feature. The eclipsing 1.13 has an older CNI version anyway.

@nikopen  Hi there, I'm hitting the no timeout issue in 1.15,  I noticed that this PR has not been cherrypicked to 1.15 yet, and it's not in 1.15 milestone either, is there any plans for the cherrypick?

**Comment by adampl** [comment]
@nikopen Are you actually going to CP this into the previous versions?

**Comment by nikopen** [comment]
PR created for 1.16. 1.15 runs into nasty conflicts unfortunately, feel free to try cherry picking: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick
