### PR TITLE
Make MIG deletion during GCE kube down blocking, so that subsequent template deletion doesn't fail.

### LINKED ISSUE #8014: Make template Deletion/Creation more robust
'kubernetes-soak-weekly-deploy' sometimes fails to deploy because the clean-up cluster `down` step fails to delete the template:
```
go run ./hack/e2e.go -v --down
...
Bringing down cluster
Managed instance group e2e-soak-minion-group is being deleted. Operation: operation-1431129917493-5159ae65c0f09-cd441be6-481553bf
ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
 - The instance_template resource 'e2e-soak-minion-template' is already being used by 'e2e-soak-minion-group'

```

Then the subsequent cluster `up` step fails to create the template, because it already exists:
```
go run ./hack/e2e.go -v --up
...
Created [...e2e-soak-master-https].
Created [...e2e-soak-master-pd].
Created [...e2e-soak-master-ip].
Created [...e2e-soak-minion-all].
Created [...e2e-soak-master].
...
Creating minions.
...
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins/global/instanceTemplates/e2e-soak-minion-template' already exists
...
[0;33mAttempt 1 failed to create instance template e2e-soak-minion-template. Retrying.
...
ERROR: (gcloud.compute.instance-templates.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins/global/instanceTemplates/e2e-soak-minion-template' already exists
```

It keeps retrying and failing, because the template already exists, until it times out and the deployment fails.

Suggested fixes:
* Cluster down should try harder to delete the template (maybe wait/retry).
* Cluster up should recognize that the template exists, and try to delete/recreate, or just re-use the existing.

### PR DESCRIPTION
**Pull request by saad-ali**
Make managed instance group (MIG) deletion during GCE kube down blocking, so that subsequent template deletion doesn't fail.

Fixes #8014

Tested locally:

```
>./cluster/kube-down.sh 
Bringing down cluster using provider: gce
All components are up to date.
Project: saad-dev-vms
Zone: us-central1-b
Bringing down cluster
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  PENDING
Waiting for MIG deletion to complete. Current status:  DONE
Deleted [https://www.googleapis.com/compute/v1/projects/saad-dev-vms/global/instanceTemplates/kubernetes-minion-template].
```

CC @quinton-hoole

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -644,10 +644,24 @@ function kube-down {
 
   echo "Bringing down cluster"
 
-  gcloud preview managed-instance-groups --zone "${ZONE}" delete \
+  deleteCmdOutput=$(gcloud preview managed-instance-groups --zone "${ZONE}" delete \
     --project "${PROJECT}" \
     --quiet \
-    "${NODE_INSTANCE_PREFIX}-group" || true
+    "${NODE_INSTANCE_PREFIX}-group" || true)
```
Comment (quinton-hoole) [inline cluster/gce/util.sh]: Why the "or true"?  I think that you need to keep trying until it returns success?

File: cluster/gce/util.sh [hunk 2]
```diff
@@ -644,10 +644,24 @@ function kube-down {
...
+  if [[ "$deleteCmdOutput" != ""  ]]; then
```
Comment (quinton-hoole) [inline cluster/gce/util.sh]: Similar to the above comment, isn't this if statement just going to skip over the checks if the deletion above failed?

File: cluster/gce/util.sh [hunk 3]
```diff
@@ -644,10 +644,24 @@ function kube-down {
...
+      do
+	sleep 5
+        deleteCmdOperationOutput=$(gcloud preview managed-instance-groups --zone "${ZONE}" get-operation $deleteCmdOperationId)
+        deleteCmdStatus=$(echo $deleteCmdOperationOutput | grep -i "status:" | sed "s/.*status:\s//" | sed "s/\s.*//" | sed "s/ //g")
+        echo "Waiting for MIG deletion to complete. Current status: " $deleteCmdStatus
+      done
+    fi
+  fi
 
   gcloud compute instance-templates delete \
```
Comment (quinton-hoole) [inline cluster/gce/util.sh]: Similar comments to above. What if this fails?  In it's current state it looks like we just naively assume success, which is also wrong?

**Comment by quinton-hoole** [comment]
My bash is not the best in the world, but I'd say we need a different approach here along the lines of:

1. repeat instance group deletion until it succeeds
2. repeat instance group deletion operation get status until it's DONE
3. repeat instance group template deletion until it succeeds

Or am I missing something here?

**Comment by quinton-hoole** [comment]
PS: You could of course omit step 2 above and rely on step 3 instead.  The code will be simpler.

**Comment by saad-ali** [comment]
I believe the reason they did the `|| true`, is so if any gcloud command fails (because, for example, the MIG being deleted doesn't exist) the remaining script continues to execute and removes the remaining components without issues.

Basically what my change is doing is if a MIG deletion request is successfully created, wait for it to complete before continuing, because subsequent template deletion step depends on it.

File: cluster/gce/util.sh (hunk 2 above)
Comment (saad-ali) [inline cluster/gce/util.sh]: Yes, both statements skip over the deletion check, which is intended--if the group ID doesn't exist, for example, it doesn't make sense to wait for deletion to complete.

File: cluster/gce/util.sh (hunk 1 above)
Comment (saad-ali) [inline cluster/gce/util.sh]: If there is an error, the remaining script should continue to execute and removes the remaining components (instead of terminating on the first error).

**Comment by saad-ali** [comment]
PTAL. Did some clean up of `|| true`. Our hands are tied by the response that gcloud gives us in terms of being more proactive on retries.

File: cluster/gce/util.sh [hunk 4]
```diff
@@ -643,16 +643,33 @@ function kube-down {
   detect-project
 
   echo "Bringing down cluster"
+  set +e  # Do not stop on error
 
-  gcloud preview managed-instance-groups --zone "${ZONE}" delete \
+  # The gcloud APIs don't return machine parsable error codes/retry infromation. Therefore the best we can
```
Comment (quinton-hoole) [inline cluster/gce/util.sh]: nit: typo - "infrom..."

**Comment by quinton-hoole** [comment]
LGTM

**Comment by saad-ali** [comment]
Thanks, nit fixed.

**Comment by quinton-hoole** [comment]
Travis and Shippable ain't going to build this anyway, so merging to give it some milage on our continuous integration e2e platform.

**Comment by roberthbailey** [comment]
Hey @saad-ali - I just rebased onto head and now I'm seeing a crazy gcloud stack trace when running kube-down.sh:

```
Waiting for MIG deletion to complete. Current status: 
Traceback (most recent call last):
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 211, in <module>
    main()
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 207, in main
    _cli.Execute()
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 617, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1110, in Run
    result = command_instance.Run(args)
  File "/Users/robertbailey/Work/google-cloud-sdk/lib/googlecloudsdk/preview/commands/managed_instance_groups/get_operation.py", line 50, in Run
    operation=args.operation)
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/apiclient/discovery.py", line 643, in method
    (name, pvalue, regex))
TypeError: Parameter "operation" value "Managedin" does not match the pattern "[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?"
Waiting for MIG deletion to complete. Current status: 
Traceback (most recent call last):
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 211, in <module>
    main()
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/gcloud/gcloud.py", line 207, in main
    _cli.Execute()
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/calliope/cli.py", line 617, in Execute
    result = args.cmd_func(cli=self, args=args)
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/googlecloudsdk/calliope/backend.py", line 1110, in Run
    result = command_instance.Run(args)
  File "/Users/robertbailey/Work/google-cloud-sdk/lib/googlecloudsdk/preview/commands/managed_instance_groups/get_operation.py", line 50, in Run
    operation=args.operation)
  File "/Users/robertbailey/Work/google-cloud-sdk/./lib/apiclient/discovery.py", line 643, in method
    (name, pvalue, regex))
TypeError: Parameter "operation" value "Managedin" does not match the pattern "[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?"
Waiting for MIG deletion to complete. Current status: 
```

It repeated long enough that I finally hit Ctrl-C.

**Comment by saad-ali** [comment]
@roberthbailey That's strange. I just re-tested it on Abhi's system by syncing to head and it seems to be working fine.  I'm waiting for jenkins e2e for more info as well. I have a revert ready just in case. But I'm going to hold off on that until I can verify this is not a one off issue: I'll ping you offline to debug.

**Comment by saad-ali** [comment]
Confirmed, Jenkins is happy:
```
Project: kubernetes-jenkins
Zone: us-central1-f
Bringing down cluster
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  RUNNING
Waiting for MIG deletion to complete. Current status:  DONE
Deleted [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins/global/instanceTemplates/e2e-test-jenkins-minion-template].
```

**Comment by roberthbailey** [comment]
I saw this again today. Created a cluster. Updated gcloud. Deleted the cluster and hit this error. I hit ctrl-c quickly and a subsequent run produced the same output. It looks like once the MIG is actually gone (and gcloud.preview.managed-instance-groups.delete returns a 404) the error goes away. 

I tried again with a fresh cluster (created/deleted after gcloud was updated) and I get the same error and see the same behavior: the error repeats until I ctrl-c and once the MIG is gone kube-down finishes.

**Comment by quinton-hoole** [comment]
@robertbailey Are your gcloud tools up to date?  Those errors are in your gcloud tools.

**Comment by saad-ali** [comment]
It doesn't look like it's caused by gcloud tools, it looks like the `$deleteCmdOperationId` is not being parsed correctly--not sure why though. Opened up #8193 to track it.

**Comment by robertbailey** [comment]
@quinton-hoole I believe you meant to ask @roberthbailey

**Comment by roberthbailey** [comment]
@saad-ali and I talked out of band. It's a problem with sed on mac os.
