### PR TITLE
Call Dial in blocking mode

### LINKED ISSUE #58281: deviceplugin unit test failure
This is not 100% reproducable in my cluster.

There is 20% chance of failing in my environment.

```
$ make test WHAT=k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin



Running tests for APIVersion: v1,admissionregistration.k8s.io/v1alpha1,admissionregistration.k8s.io/v1beta1,admission.k8s.io/v1beta1,apps/v1beta1,apps/v1beta2,apps/v1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,events.k8s.io/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,storage.k8s.io/v1alpha1,
+++ [0115 17:59:27] Running tests without code coverage
2018/01/15 17:59:30 Starting to serve on /tmp/mock.sock
2018/01/15 17:59:30 Starting to serve on /tmp/mock.sock
E0115 17:59:30.481555   29183 endpoint.go:101] listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = grpc: the connection is unavailable
panic: test timed out after 4m0s

goroutine 42 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc4203bc000, 0x13342fd, 0x7, 0x13b9570, 0x481901)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4203bc000)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4203bc000, 0xc4204e1de0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc42015fb20, 0x1b9ce20, 0xb, 0xb, 0x115f4a0)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420397f18, 0xc4204e1f70)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin/_test/_testmain.go:64 +0xdb

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1ba9220)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.0
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 14 [chan receive, 4 minutes]:
k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin.TestRun(0xc4203bc2d0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin/endpoint_test.go:93 +0x4af
testing.tRunner(0xc4203bc2d0, 0x13b9570)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de

goroutine 15 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f38f9f09eb0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420182798, 0x72, 0xc420050400, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc420182798, 0xffffffffffffff00, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420182780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc420182780, 0x18, 0xc4200505f0, 0x13ba3d8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*UnixListener).accept(0xc42017e360, 0xc4200506a0, 0x18, 0x7e30bd)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x32
net.(*UnixListener).Accept(0xc42017e360, 0x13ba388, 0xc4200ee500, 0x1b4bfa0, 0xc42017e360)
	/usr/local/go/src/net/unixsock.go:241 +0x49
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Serve(0xc4200ee500, 0x1b4bfa0, 0xc42017e360, 0x0, 0x0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:475 +0x196
created by k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin.(*Stub).Start
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin/device_plugin_stub.go:88 +0x15c

goroutine 50 [select]:
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc420264200, 0x0, 0x0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:994 +0xbd6
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc420264200)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:695 +0x2f
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).connect
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d
FAIL	k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin	240.014s
Makefile:182: recipe for target 'test' failed
make: *** [test] Error 1

```

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
# Tests which uncover underlying problem
On the current master code:
1. comment out stub plugin server start [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/deviceplugin/endpoint_test.go#L127-L128)
2. run `go test  -v k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin --run TestNewEndpoint --count 1`. Test succeeds.
3. run `go test  -v k8s.io/kubernetes/pkg/kubelet/cm/deviceplugin --run TestRun --count 1`. Test hangs with:
> listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = grpc: the connection is unavailable

`2` does not fail even though it invokes Dial and no listening server is running. It is because currently Dial is not waiting till the connection turns to Ready state. And this case does not invokes any RPC call over the `conn` returned by `Dial`

`3` hangs because this tests involves actual usage of `conn`(client) and there it does not find listening server because we dint start and deliberately stopped in `1`.

`Dial` should be using `WithBlock` option which ensures that `conn` is returned only when connection is in `Ready` state.

After using `WithBlock` in the `Dial`, in this PR, if `1`, `2` and `3` are repeated. Both, `2` and `3`, fails at `Dial`, which is expected behavior. By `fail`, I meant Dial blocks forever if `WithTimeout` is not used or otherwise, a timeout failure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58281

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```
/area hw-accelerators
/sig node
/cc  @jiayingz @RenaudWasTaken @vishh @ScorpioCPH @sjenning @derekwaynecarr @jeremyeder @lichuqiang @tengqm

### CODE REVIEW

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go [hunk 1]
```diff
@@ -86,14 +86,6 @@ func (m *Stub) Start() error {
...
 
 	go m.server.Serve(sock)
-	// Wait till grpc server is ready.
-	for i := 0; i < 10; i++ {
-		services := m.server.GetServiceInfo()
-		if len(services) > 0 {
-			break
-		}
-		time.Sleep(1 * time.Second)
-	}
```
Comment (ScorpioCPH) [inline pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: Should we dial here to wait grpc server is ready?

**Review by ScorpioCPH — COMMENTED** [review]
@vikaschoudhary16 Hi, thanks for this PR, I try this on my local, `2` always passed without `1`, and `3` passed with rpc message: `Unavailable` and `FailedPrecondition` (as you mentioned: which is expected behavior).

LGTM.

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go (hunk 1 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: No, no need. Now `WithBlock` in `Dial` will ensure this for us.

File: pkg/kubelet/cm/deviceplugin/endpoint.go [hunk 2]
```diff
@@ -188,7 +188,8 @@ func (e *endpointImpl) stop() {
 
 // dial establishes the gRPC communication with the registered device plugin.
 func dial(unixSocketPath string) (pluginapi.DevicePluginClient, *grpc.ClientConn, error) {
```
Comment (RenaudWasTaken) [inline pkg/kubelet/cm/deviceplugin/endpoint.go]: How about moving this function to device_plugin_stub.go add a timeout parameter and return only a *grpc.ClientConn ?
Add a comment about why we are using WithBlock()

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go (hunk 1 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: I think it's actually better to have the Start() call guarantee that the server is ready.
That's a saner pattern and the cost isn't very high compared to the `sleep(10)` we've had for the past 3 monts.

File: pkg/kubelet/cm/deviceplugin/manager_test.go [hunk 3]
```diff
@@ -498,7 +498,6 @@ type TestResource struct {
 func TestPodContainerDeviceAllocation(t *testing.T) {
 	flag.Set("alsologtostderr", fmt.Sprintf("%t", true))
 	var logLevel string
-	flag.StringVar(&logLevel, "logLevel", "4", "test")
 	flag.Lookup("v").Value.Set(logLevel)
```
Comment (RenaudWasTaken) [inline pkg/kubelet/cm/deviceplugin/manager_test.go]: What is this doing in the `TestPodContainerDeviceAllocation` function why is it not in the `init` function ?

**Review by RenaudWasTaken — CHANGES_REQUESTED** [review]

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go (hunk 1 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: 1. How would you guarantee that? keeping the `for` loop?
2. What would we gain by this guarantee other than losing some cpu cycles?

File: pkg/kubelet/cm/deviceplugin/endpoint.go (hunk 2 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/endpoint.go]: Why is the rationale behind the suggestion of moving this function to stub.go? Since it is being invoked from within this file, https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/deviceplugin/endpoint.go#L58,
I think this file is the right place for this function.

IMO, `WithBlock` is self explanatory. As far as scope of this PR goes, i think enough details have already been added in PR description.

File: pkg/kubelet/cm/deviceplugin/manager_test.go (hunk 3 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/cm/deviceplugin/manager_test.go]: Yeah, should not be here. Thats why removed it.

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go (hunk 1 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: > How would you guarantee that? keeping the for loop?
```
c, err := dial(socket, timeout)
...
c.Close()
```

Comment (RenaudWasTaken) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: > What would we gain by this guarantee other than losing some cpu cycles?
 
Code robustness. When you create a stub device plugin you have the guarantee that the gRPC server is online. Thus preventing bugs we are currently solving.

File: pkg/kubelet/cm/deviceplugin/endpoint.go (hunk 2 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/cm/deviceplugin/endpoint.go]: > Why is the rationale behind the suggestion of moving this function to stub.go? Since it is being invoked from within this file.

Rational is to call it on the stub. Wether we move it or not is not really the important thing here.

> IMO, WithBlock is self explanatory. As far as scope of this PR goes, i think enough details have already been added in PR description.

When people read the code, they don't read the PRs. Adding a comment explaining why this is required and what this is fixing helps understands why these options are here.

File: pkg/kubelet/cm/deviceplugin/manager_test.go (hunk 3 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/cm/deviceplugin/manager_test.go]: Probably remove the next line then :)

**Comment by jiayingz** [comment]
/lgtm
/approve

@vikaschoudhary16  Thanks a lot for the nice work of tracking it down and fixing the underlying issue so quickly!
cc @chakri-nelluri 
I think we may review some of the grpc options used here in the generic kubelet plugin communication model work, like the use of WithInSecure() option (would be nice to have a way to support secure communication) and WithTimeout() option (it has a Deprecated note of chaning to use DialContext and context.WithTimeout in the grpc doc).

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go [hunk 4]
```diff
@@ -109,7 +106,8 @@ func (m *Stub) Stop() error {
 
 // Register registers the device plugin for the given resourceName with Kubelet.
 func (m *Stub) Register(kubeletEndpoint, resourceName string) error {
-	conn, err := grpc.Dial(kubeletEndpoint, grpc.WithInsecure(),
+	conn, err := grpc.Dial(kubeletEndpoint, grpc.WithInsecure(), grpc.WithBlock(),
```
Comment (RenaudWasTaken) [inline pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: can we use the dial function here ?

**Review by RenaudWasTaken — CHANGES_REQUESTED** [review]

**Comment by RenaudWasTaken** [comment]
@jiayingz can we hold this PR for one more simple change ?

File: pkg/kubelet/cm/deviceplugin/device_plugin_stub.go (hunk 4 above)
Comment (jiayingz) [reply pkg/kubelet/cm/deviceplugin/device_plugin_stub.go]: I will leave this up-to @vikaschoudhary16 to decide. Note that this part will change once we have a generic kubelet plugin model, which will use probe instead of registration.
