### PR TITLE
tests: creates HostPath pods as unprivileged

### LINKED ISSUE #75292: Some HostPath tests do not require privileged Containers to pass
/sig testing
/sig windows

/area conformance

**Which jobs are failing**:

N/A

**Which test(s) are failing**:

    [sig-storage] HostPath should support r/w [NodeConformance]
    [sig-storage] HostPath should support subPath [NodeConformance]

**Since when has it been failing**:

Before 2019-03-07. Since then, the Windows nodes' kubelet service has been passed the ``--allow-privileged=true``, which allows the test to pass.

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#cfcr-vsphere-windows-master (older than 2019-03-07)

**Reason for failure**:

The tests are trying to spawn pods with a HostPath volume (``/tmp`` folder) and with ``priviledged = true`` SecurityContext. The Windows Kubelet does not support privileged containers, causing the tests to fail on Windows. The test cases' containers do not have to be privileged. The containers have to create a file on the HostPath volume, but the ``/tmp`` folder has 777 file permissions by default, meaning it should pass without privileged access.

The tests have turned green in the linked testgrid because the Windows Kubelet flag ``--allow-privileged`` has been set to true, but it shouldn't have been necessary in the first place.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test

/sig testing
/sig windows
/area conformance

**What this PR does / why we need it**:

The containers are mounted the /tmp folder as a HostPath volume
and they are supposed to create a new file in it.

The /tmp folder has 777 file permissions, so there shouldn't be any
problems creating a file, even if the container is unprivileged.

**Which issue(s) this PR fixes**:

Fixes #75292

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/common/host_path.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ var _ = Describe("[sig-storage] HostPath", func() {
 		source := &v1.HostPathVolumeSource{
 			Path: "/tmp",
 		}
-		pod := testPodWithHostVol(volumePath, source, true)
+		pod := testPodWithHostVol(volumePath, source, false)
```
Comment (oomichi) [inline test/e2e/common/host_path.go]: After applying this change, all callers of testPodWithHostVol() pass false as privileged argument.
How about removing the argument for cleanup?

**Review by oomichi — COMMENTED** [review]
Most part seems good for me, just one comment

**Comment by oomichi** [comment]
@pontiyaraja Could you take a look at this? The argument has been added since your https://github.com/kubernetes/kubernetes/pull/71550 So it would be nice to get feedback from you.

**Comment by pontiyaraja** [comment]
@oomichi I think you need to test it with SELinux enabled.please refer the PR #69935

**Comment by oomichi** [comment]
@pontiyaraja Thank you, I see that. We need to keep them as https://github.com/kubernetes/kubernetes/pull/69935#issuecomment-440996923
Maybe it is better to put NOTE which explains SELinux enabled environments require it.

**Comment by bclau** [comment]
I've updated the tests so they will spawn pods as privileged on linux and unprivileged on Windows.
