### PR TITLE
Bugfix: Use local JSON log buffer in parseDockerJSONLog.

### LINKED ISSUE #47800: kubectl logs -f failed with 'unexpected stream type "" '
I was running a kubectl logs -f, not for long, that broke unexpectedly with
```
{"level":"info","msg":"Sync time: 2.276207ms","time":"2017-06-20T17:30:02Z"}
{"level":"info","msg":"Sync time: 5.663623ms","time":"2017-06-20T17:30:32Z"}
unexpected stream type ""
```
Doesn't seem normal. 

```
$ kc version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.0.533+1168552fade5fd", GitCommit:"1168552fade5fd138e4af664ed7b31ec40c6a20f", GitTreeState:"clean", BuildDate:"2017-06-10T16:56:39Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

@kubernetes/sig-node-bugs 
@kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by sczizzo**
**What this PR does / why we need it**:
The issue described in #47800 is due to a race condition in `ReadLogs`: Because the JSON log buffer (`dockerJSONLog`) is package-scoped, any two goroutines modifying the buffer could race and overwrite the other's changes. In particular, one goroutine could unmarshal a JSON log line into the buffer, then another goroutine could `Reset()` the buffer, and the resulting `Stream` would be empty (`""`). This empty `Stream` is caught in a `case` block and raises an `unexpected stream type` error.

This PR creates a new buffer for each execution of `parseDockerJSONLog`, so each goroutine is guaranteed to have a local instance of the buffer.

**Which issue this PR fixes**: fixes #47800

**Release note**:
```release-note
Fixed an issue (#47800) where `kubectl logs -f` failed with `unexpected stream type ""`.
```

### CODE REVIEW

**Comment by thockin** [comment]
This seems horribly broken to start with, which makes me suspicious of whether something deeper is happening.

@Random-Liu  ?

**Comment by smarterclayton** [comment]
@derekwaynecarr

File: pkg/kubelet/kuberuntime/kuberuntime_logs.go [hunk 1]
```diff
@@ -280,16 +280,14 @@ func parseCRILog(log []byte, msg *logMessage) error {
...
-
 // parseDockerJSONLog parses logs in Docker JSON log format. Docker JSON log format
 // example:
 //   {"log":"content 1","stream":"stdout","time":"2016-10-20T18:39:20.57606443Z"}
 //   {"log":"content 2","stream":"stderr","time":"2016-10-20T18:39:20.57606444Z"}
 func parseDockerJSONLog(log []byte, msg *logMessage) error {
-	dockerJSONLog.Reset()
-	l := dockerJSONLog
+	var l = &jsonlog.JSONLog{}
+	l.Reset()
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_logs.go]: The reset is not needed then.

**Review by Random-Liu — COMMENTED** [review]
Sorry for the stupid bug. Don't know what I was thinking at that time...
@sczizzo Thanks for the fix!

**Comment by yujuhong** [comment]
We should cherry-pick this to 1.7 and 1.6.

File: pkg/kubelet/kuberuntime/kuberuntime_logs.go (hunk 1 above)
Comment (yujuhong) [reply pkg/kubelet/kuberuntime/kuberuntime_logs.go]: @sczizzo could you fix this? Thanks!

**Comment by yujuhong** [comment]
/lgtm

Let's get this merged.

**Comment by CaoShuFeng** [comment]
oops, my pull request was much earlier than this.
https://github.com/kubernetes/kubernetes/pull/47164

Thanks  for fix it as well. :+1:

**Comment by smparkes** [comment]
Will this get cherry-picked into 1.6 and 1.7? Causing a bunch of problems for us ...

**Comment by sczizzo** [comment]
@smparkes, yeah check out #51872 for `release-1.6` and #51871 for `release-1.7`
