### PR TITLE
Fix client IP preservation for NodePort service with protocol SCTP

### LINKED ISSUE #104755: ipvs mode doesn't preserve client IP for NodePort Service with protocol SCTP and ExternalTrafficPolicy Local
#### What happened:
ipvs mode didn't preserve client IP for NodePort Service with protocol SCTP and ExternalTrafficPolicy Local.

iptables mode works fine.
ipvs mode with TCP and UDP protocol works fine. 

#### What you expected to happen:
Client IP for NodePort Service should be preseved when ExternalTrafficPolicy is Local regardless of the mode and the protocol.

#### How to reproduce it (as minimally and precisely as possible):

1. Set kube-proxy mode to ipvs
2. Create a NodePort service with protocol SCTP and ExternalTrafficPolicy Local
3. Access the NodePort service, the client IP was not preserved

#### Anything else we need to know?:

This is caused by wrong order of iptables rules that match kubeNodePortLocalSetSCTP and kubeNodePortSetSCTP:
```
-A KUBE-NODE-PORT -p sctp -m comment --comment "Kubernetes nodeport SCTP port for masquerade purpose with type \'hash ip:port\'" -m set --match-set KUBE-NODE-PORT-SCTP-HASH dst,dst -j KUBE-MARK-MASQ
-A KUBE-NODE-PORT -p sctp -m comment --comment "Kubernetes nodeport SCTP port with externalTrafficPolicy=local with type \'hash ip:port\'" -m set --match-set KUBE-NODE-PORT-LOCAL-SCTP-HASH dst,dst -j RETURN
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.22.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The iptables rule that matches kubeNodePortLocalSetSCTP must be inserted before the one matches kubeNodePortSetSCTP, otherwise all SCTP traffic would be masqueraded regardless of whether its ExternalTrafficPolicy is Local or not.

Besides, it adds unit test to verify the iptables rules are in expected order.

#### Which issue(s) this PR fixes:

Fixes #104755

#### Does this PR introduce a user-facing change?

```release-note
Fixed client IP preservation for NodePort service with protocol SCTP in ipvs mode
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -191,8 +191,8 @@ var ipsetWithIptablesChain = []struct {
 	{kubeNodePortSetTCP, string(KubeNodePortChain), string(KubeMarkMasqChain), "dst", utilipset.ProtocolTCP},
 	{kubeNodePortLocalSetUDP, string(KubeNodePortChain), "RETURN", "dst", utilipset.ProtocolUDP},
 	{kubeNodePortSetUDP, string(KubeNodePortChain), string(KubeMarkMasqChain), "dst", utilipset.ProtocolUDP},
-	{kubeNodePortSetSCTP, string(KubeNodePortChain), string(KubeMarkMasqChain), "dst,dst", utilipset.ProtocolSCTP},
 	{kubeNodePortLocalSetSCTP, string(KubeNodePortChain), "RETURN", "dst,dst", utilipset.ProtocolSCTP},
+	{kubeNodePortSetSCTP, string(KubeNodePortChain), string(KubeMarkMasqChain), "dst,dst", utilipset.ProtocolSCTP},
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier.go:195]: I'm not familiar with the ipset implementation, why sctp `matchType` is `dst,dst` but udp and tcp ar eonly `dst`?

File: pkg/proxy/ipvs/proxier_test.go [hunk 2]
```diff
@@ -652,12 +652,29 @@ func TestNodePortIPv4(t *testing.T) {
 				}},
 			},
 			expectedIptablesChains: netlinktest.ExpectedIptablesChain{
-				string(KubeNodePortChain): {{
-					JumpChain: string(KubeMarkMasqChain), MatchSet: kubeNodePortSetUDP,
-				}},
-				string(kubeServicesChain): {{
-					JumpChain: string(KubeNodePortChain), MatchSet: "",
-				}},
+				string(KubeNodePortChain): {
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier_test.go:655]: why is this test affected if we only have changed the SCTP rules order?

File: pkg/proxy/ipvs/proxier.go (hunk 1 above)
Comment (tnqn) [reply pkg/proxy/ipvs/proxier.go:195]: It's because `bitmap:port` ipset doesn't support matching SCTP port: https://github.com/kubernetes/kubernetes/pull/74341
https://ipset.netfilter.org/ipset.man.html#lbAV:
> The set match and SET target netfilter kernel modules interpret the stored numbers as TCP or UDP port numbers.

File: pkg/proxy/ipvs/proxier_test.go (hunk 2 above)
Comment (tnqn) [reply pkg/proxy/ipvs/proxier_test.go:655]: Previously the test only checked whether the target iptables rule exists or not and didn't care about the extra rules got from the system and their order, by using `checkIptables`. If we just add the two sctp related rules to `expectedIptablesChains`, it's not going to validate one rule is after the other and can be broken in the future without any test failure. So I add a new method `checkIptablesInOrder` which validates the `expectedIptablesChains` have the same number and order of rules as the ones got from the system. As a result, we need to add missing chains of this test accordingly.

**Review by tnqn — COMMENTED** [review]
@aojea thanks for the review. Answered your questions.

File: pkg/proxy/ipvs/proxier_test.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/ipvs/proxier_test.go:655]: hmm, shouldn't that be the default behavior of ` checkIptables` ? 
that method is used in other places and order matters, i.e. we can't have a RETURN as first rule and mark the test as valid XD

Comment (tnqn) [reply pkg/proxy/ipvs/proxier_test.go]: I was trying to touch less code. But making `checkIptables` check rule order for all tests makes sense to me. I have updated `checkIptables` and other tests accordingly.

**Comment by uablrek** [comment]
/lgtm

I have tested with and without the PR on IPv4 and IPv6 and it works as expected.

And for completeness I also tested that the src was preserved for `type: LoadBalancer` and it works with and without this PR.

**Comment by tnqn** [comment]
@aojea @uablrek @andrewsykim if there is no new comment, could you please approve it?

**Comment by JornShen** [comment]
@tnqn  shall we cherry-pick this to 1.22 or event earlier branch ? cc @aojea

**Comment by tnqn** [comment]
> @tnqn shall we cherry-pick this to 1.22 or even earlier branch ? cc @aojea

@JornShen I could backport it to 1.22, but will there be new patch releases for 1.21? @aojea

**Comment by aojea** [comment]
1.21 EOL is `2022-06-28`  based on https://kubernetes.io/releases/
