### PR TITLE
Fix wrapped volume race

### LINKED ISSUE #29297: Mounting configmap as volume sometimes causes FailedMount error
For some reason, while trying to create a deployment with a configmap mounted as a volume, I will _sometimes_ have a pod stuck in ContainerCreating and describing the pod gives an error like so:

    FirstSeen	LastSeen	Count	From							SubobjectPath	Type		Reason		Message
      ---------	--------	-----	----							-------------	--------	------		-------
      3m		3m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned core-deployment-214446676-kp9k6 to gke-cluster-main-default-pool-6482d459-fjzn
      1m		1m		1	{kubelet gke-cluster-main-default-pool-6482d459-fjzn}			Warning		FailedMount	Unable to mount volumes for pod "core-deployment-214446676-kp9k6_default(63a2ee79-4e8d-11e6-92bf-42010af001cd)": timeout expired waiting for volumes to attach/mount for pod "core-deployment-214446676-kp9k6"/"default". list of unattached/unmounted volumes=[core-config-files]
      1m		1m		1	{kubelet gke-cluster-main-default-pool-6482d459-fjzn}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "core-deployment-214446676-kp9k6"/"default". list of unattached/unmounted volumes=[core-config-files]

Here is the yaml I'm working with:

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: core-deployment
    spec:
      replicas: 2
      template:
        metadata:
          name: core
          labels:
            app: core
        spec:
          containers:
            - name: core
              image: gcr.io/infrastructure-1373/hello-node:v3
              ports:
                - containerPort: 5000
              volumeMounts:
                - name: core-config-files
                  mountPath: /etc/core-config
          volumes:
            - name: core-config-files
              configMap:
                name: core-config-files

and output of kubectl describe configmaps core-config-files:

    Name:		core-config-files
    Namespace:	default
    Labels:		<none>
    Annotations:    kubectl.kubernetes.io/last-applied-configuration={"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"core-config-files","creationTimestamp":null},"data":{...long...}

    Data
    ====
    saml.yml:	381 bytes
    general.yml:	1109 bytes
    saml-meta.xml:	4432 bytes

and the output of kubectl version:

    Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
    Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.2", GitCommit:"9bafa3400a77c14ee50782bb05f9efc5c91b3185", GitTreeState:"clean"}

### PR DESCRIPTION
**Pull request by ivan4th**
**EDIT:** now covers configmap, secret, downwardapi & git_repo volume plugins.

Fixes #29297.

wrappedVolumeSpec used by configMapVolumeMounter and
configMapVolumeUnmounter contained a pointer to api.Volume which was
being patched by NewWrapperMounter/NewWrapperUnmounter, causing race
condition during configmap volume mounts.

See https://github.com/kubernetes/kubernetes/issues/29297#issuecomment-235403806 for complete explanation.
The subtle bug was introduced by #18445, it also can affect other volume plugins utilizing `wrappedVolumeSpec` technique, if this PR is correct/accepted will make more PRs for secrets etc. Although tmpfs variety of inner `emptyDir` volume appears to be less susceptible to this race, there's chance it can fail too.

The errors produced by this race look like this:
`Jul 19 17:05:21 ubuntu1604 kubelet[17097]: I0719 17:05:21.854303   17097 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/configmap/foo-files"
 (spec.Name: "files") to pod "11786582-4dbf-11e6-9fc9-64cca009c636" (UID: "11786582-4dbf-11e6-9fc9-64cca009c636").
Jul 19 17:05:21 ubuntu1604 kubelet[17097]: I0719 17:05:21.854842   17097 reconciler.go:253] MountVolume operation started for volume "kubernetes.io/configmap/bar-file
s" (spec.Name: "files") to pod "117d2c22-4dbf-11e6-9fc9-64cca009c636" (UID: "117d2c22-4dbf-11e6-9fc9-64cca009c636").
Jul 19 17:05:21 ubuntu1604 kubelet[17097]: E0719 17:05:21.860796   17097 configmap.go:171] Error creating atomic writer: stat /var/lib/kubelet/pods/117d2c22-4dbf-11e6-9fc9-64cca009c636/volumes/kubernetes.io~configmap/files: no such file or directory
Jul 19 17:05:21 ubuntu1604 kubelet[17097]: E0719 17:05:21.861070   17097 goroutinemap.go:155] Operation for "kubernetes.io/configmap/bar-files" failed. No retries permitted until 2016-07-19 17:07:21.861036886 +0200 CEST (durationBeforeRetry 2m0s). error: MountVolume.SetUp failed for volume "kubernetes.io/configmap/bar-files" (spec.Name: "files") pod "117d2c22-4dbf-11e6-9fc9-64cca009c636" (UID: "117d2c22-4dbf-11e6-9fc9-64cca009c636") with: stat /var/lib/kubelet/pods/117d2c22-4dbf-11e6-9fc9-64cca009c636/volumes/kubernetes.io~configmap/files: no such file or directory
Jul 19 17:05:21 ubuntu1604 kubelet[17097]: E0719 17:05:21.861271   17097 configmap.go:171] Error creating atomic writer: stat /var/lib/kubelet/pods/11786582-4dbf-11e6-9fc9-64cca009c636/volumes/kubernetes.io~configmap/files: no such file or directory
Jul 19 17:05:21 ubuntu1604 kubelet[17097]: E0719 17:05:21.862284   17097 goroutinemap.go:155] Operation for "kubernetes.io/configmap/foo-files" failed. No retries permitted until 2016-07-19 17:07:21.862275753 +0200 CEST (durationBeforeRetry 2m0s). error: MountVolume.SetUp failed for volume "kubernetes.io/configmap/foo-files" (spec.Name: "files") pod "11786582-4dbf-11e6-9fc9-64cca009c636" (UID: "11786582-4dbf-11e6-9fc9-64cca009c636") with: stat /var/lib/kubelet/pods/11786582-4dbf-11e6-9fc9-64cca009c636/volumes/kubernetes.io~configmap/files: no such file or directory`

Note "Error creating atomic writer" errors.
This problem can be reproduced by making kubelet mount multiple config map volumes in parallel.

### CODE REVIEW

**Comment by ncdc** [comment]
cc @pmorie

**Comment by asalkeld** [comment]
looks ok to me.

**Comment by dims** [comment]
@ivan4th @asalkeld : The same exact construct is in 3 more locations should we fix them all?

https://github.com/kubernetes/kubernetes/search?utf8=%E2%9C%93&q=wrappedVolumeSpec&type=Code

**Comment by pmorie** [comment]
@dims @ivan4th yes, anywhere else that uses wrapped volume specs should be addressed in this PR, please

**Comment by saad-ali** [comment]
@ivan4th Thanks debugging and the fix. Go ahead and make this change for the other wrapped volumes in this PR (that way we have one PR to merge and cherry pick).

**Comment by pmorie** [comment]
@ivan4th Do you think it's possible to create an E2E that will reliably fail without this patch?  If so it would be great to have a guard against this in our tests.  

Btw, this is a great PR and I appreciate the fix :)

**Comment by pmorie** [comment]
cc @resouer

**Comment by ivan4th** [comment]
@saad-ali Updated the PR to cover other occurrences of the race.
@pmorie It is probably possible to create an e2e test that reproduces the problem for configmaps in a more or less reliable way by creating many pods w/configmap volumes at once, but there's chance it will be [Slow] (will check). As of other volume types, it will be harder to trigger the problem because the race is much less frequent for tmpfs-based emptyDir that is used there. It's also possible to write unit tests that reliably trigger the bugs by using a fake mounter that has `IsLikelyNotMountPoint()` which blocks, but it will be somewhat unrealistic. (It's also probably possible to induce data race in unit tests for `KUBE_RACE="-race"` case)

File: pkg/volume/secret/secret.go [hunk 1]
```diff
@@ -45,8 +45,10 @@ type secretPlugin struct {
 
 var _ volume.VolumePlugin = &secretPlugin{}
 
-var wrappedVolumeSpec = volume.Spec{
-	Volume: &api.Volume{VolumeSource: api.VolumeSource{EmptyDir: &api.EmptyDirVolumeSource{Medium: api.StorageMediumMemory}}},
+func wrappedVolumeSpec() volume.Spec {
```
Comment (dims) [inline pkg/volume/secret/secret.go]: Is it possible to create a common wrappedVolumeSpec method (say in pkg/volume/util.go) and use that in all the 4 locations? (Looks like you may need to pass in a parameter)?

Thanks,
Dims

Comment (ivan4th) [inline pkg/volume/secret/secret.go]: Well I could do this by adding say `WrappedVolumeSpec()` to pkg/volume/util.go, but that would be a kind of `volume` -> `volume/empty_dir` quasi-dependency which is probably not very pretty.

Comment (dims) [inline pkg/volume/secret/secret.go]: ouch. never mind. scratch that then :)

**Comment by dims** [comment]
Looks good to me 👍

File: pkg/volume/secret/secret.go (hunk 1 above)
Comment (saad-ali) [inline pkg/volume/secret/secret.go]: I think it's ok/expected for util packages to live at the same level as the package that consumes them. So as long it doesn't result in circular dependencies that would be a good cleanup.

Regardless, any cleanup/refactoring can be done in a follow up.

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
@ivan4th Thanks for the fix. Once this is merged. Could you prepare a cherry-pick to the release-1.3 branch? If not, I can do it on your behalf, let me know.

**Comment by ivan4th** [comment]
@saad-ali: thanks! Will prepare the cherry-pick PR after merge. Will make followup PR with refactoring and tests after that.

**Comment by pmorie** [comment]
Thanks for the patch @ivan4th

**Comment by ivan4th** [comment]
@pmorie you're welcome 😄

**Comment by fabioy** [comment]
@ivan4th Cherrypick approved. Please create a cherrypick PR. Thanks.

**Comment by ivan4th** [comment]
@fabioy Thanks! Cherrypick PR is already here https://github.com/kubernetes/kubernetes/issues/29704
