### PR TITLE
kubeadm: fix the bug that 'kubeadm init --dry-run --upload-certs' command failed with 'secret not found' error

### LINKED ISSUE #2649: kubeadm init --dry-run --upload cert fails in upload-certs phase with 'secret not found'
### What happened?

Executing the command `kubeadm init --dry-run  --upload-certs`,  the command fails with

```
[upload-certs] Storing the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[dryrun] Would perform action GET on resource "secrets" in API group "core/v1"
[dryrun] Resource name: "bootstrap-token-xtr0u0"
[dryrun] Would perform action CREATE on resource "secrets" in API group "core/v1"
[dryrun] Attached object:
	apiVersion: v1
	data:
	  description: UHJveHkgZm9yIG1hbmFnaW5nIFRUTCBmb3IgdGhlIGt1YmVhZG0tY2VydHMgc2VjcmV0
	  expiration: MjAyMi0wMi0wM1QxNToxNToxMlo=
	  token-id: eHRyMHUw
	  token-secret: NWUxYWNobmdvNWRnMWFvMQ==
	kind: Secret
	metadata:
	  creationTimestamp: null
	  name: bootstrap-token-xtr0u0
	  namespace: kube-system
	type: bootstrap.kubernetes.io/token
[dryrun] Would perform action GET on resource "secrets" in API group "core/v1"
[dryrun] Resource name: "bootstrap-token-xtr0u0"
error execution phase upload-certs: error uploading certs: error to get token reference: secrets "secret not found" not found
```

### What did you expect to happen?

I would expect the dry run with upload-certs to have succeeded.  

### How can we reproduce it (as minimally and precisely as possible)?

Execute the command `kubeadm init --dry-run  --upload-certs`

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
1.22.5
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME=<redacted name>
VERSION=0.0.0
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux <redacted hostname> 5.4.0-90-generic kubernetes/kubernetes#101-Ubuntu SMP Fri Oct 15 19:59:45 UTC 2021 s390x s390x s390x GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubeadm: fix the bug that `kubeadm init --dry-run --upload-certs` command failed with `secret not found` error

#### Which issue(s) this PR fixes:

Fixes kubernetes/kubeadm#2649

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/phases/copycerts/copycerts.go [hunk 1]
```diff
@@ -159,11 +160,26 @@ func createRBAC(client clientset.Interface) error {
...
+			ObjectMeta: metav1.ObjectMeta{
+				Namespace: metav1.NamespaceSystem,
+				Name:      secretName,
+				UID:       uuid.NewUUID(),
+			},
+		}
+	} else {
+		secret, err = client.CoreV1().Secrets(metav1.NamespaceSystem).Get(context.TODO(), secretName, metav1.GetOptions{})
+		if err != nil {
+			return nil, errors.Wrap(err, "error to get token reference")
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/copycerts/copycerts.go:181]: we can fix this typo

```suggestion
			return nil, errors.Wrap(err, "error getting token reference")
```

File: cmd/kubeadm/app/phases/copycerts/copycerts.go [hunk 2]
```diff
@@ -159,11 +160,26 @@ func createRBAC(client clientset.Interface) error {
...
+	if isDryRun {
+		// If dry-running, just generate a fake bootstrap token Secret instead of doing a real query
+		secret = &v1.Secret{
+			ObjectMeta: metav1.ObjectMeta{
+				Namespace: metav1.NamespaceSystem,
+				Name:      secretName,
+				UID:       uuid.NewUUID(),
+			},
+		}
+	} else {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/copycerts/copycerts.go:178]: i think the better way to do this is modifying the "init getter".
this will result in no need to pass the isDryRun bool to functions in the stack.

here https://github.com/kubernetes/kubernetes/blob/f104ae885fb100278d9cbf2ec3a15b11f465872c/cmd/kubeadm/app/cmd/init.go#L533-L534
kubeadm constructs an init getter and dry run client.

inside the init getter there are some handlers:
https://github.com/kubernetes/kubernetes/blob/b0bc8adbc2178e15872f9ef040355c51c45d04bb/cmd/kubeadm/app/util/apiclient/init_dryrun.go#L61-L64

we can add a new handler for resource type "secret" called something like `handleCopyCertsSecret`
and in the handler we can make sure the secret name matches the prefix as defined here:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/cluster-bootstrap/token/util/helpers.go#L109-L111
and return a usable / blank secret object for dryrun.

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @SataQiu

File: cmd/kubeadm/app/phases/copycerts/copycerts.go (hunk 2 above)
Comment (SataQiu) [reply cmd/kubeadm/app/phases/copycerts/copycerts.go:178]: Thank you for your patient explanation @neolit123 

But according to the following code:
```
// handleGetBootstrapToken handles the case where kubeadm init creates the default token; and the token code GETs the
// bootstrap token secret first in order to check if it already exists
func (idr *InitDryRunGetter) handleGetBootstrapToken(action core.GetAction) (bool, runtime.Object, error) {
	if !strings.HasPrefix(action.GetName(), "bootstrap-token-") || action.GetNamespace() != metav1.NamespaceSystem || action.GetResource().Resource != "secrets" {
		// We can't handle this event
		return false, nil, nil
	}
	// We can safely return a NotFound error here as the code will just proceed normally and create the Bootstrap Token
	return true, nil, apierrors.NewNotFound(action.GetResource().GroupResource(), "secret not found")
}
```
It looks like the handler will always return a `NotFound` error whether or not the bootstrap token Secret has already been created. It's hard to decide when to return the `NotFound` error and when to return the fake Secret.

And we never actually store objects to the backend, because of :
https://github.com/kubernetes/kubernetes/blob/0d46aee44eeb4062584469144ff6d8a543a5d1fa/cmd/kubeadm/app/util/apiclient/dryrunclient.go#L162-L166
https://github.com/kubernetes/kubernetes/blob/0d46aee44eeb4062584469144ff6d8a543a5d1fa/cmd/kubeadm/app/util/apiclient/dryrunclient.go#L199-L206

Another approach might be to allow the bootstrap token Secret to be stored on the backend and then remove the handleGetBootstrapToken handler.

Comment (SataQiu) [reply cmd/kubeadm/app/phases/copycerts/copycerts.go]: I tried the above approach. It also works. @neolit123

**Review by neolit123 — COMMENTED** [review]
/lgtm
i tested it locally and this does fix the problem. thanks.

it seems that it happens if users do `kubeadm init --dry-run --upload-certs` as well.
that is because --upload-certs executes into optional code.

i've logged this, because we need e2e tests for dry-run in kubeadm:
https://github.com/kubernetes/kubeadm/issues/2653

in terms of the handlers in the dry-run client, i must admit i'm not very familiar with this area of the code, but i think they are a bit strange. maybe we can remove the handlers entirely...
for a dry-run client, i would expect it to always return some fake object...or allow an object to be pushed to the fake storage.
