### PR TITLE
Work around the etcd watch issue

### LINKED ISSUE #32770: TestWatch {etcd}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/17026/

Failed: TestWatch {etcd}

```
resttest.go:1251: unexpected timeout from result channel
```

Previous issues for this test: #31262

### PR DESCRIPTION
**Pull request by hongchaodeng**
fix #32770

Underlyingly, differentiating context will unshare the grpc stream.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33101)

### CODE REVIEW

**Comment by hongchaodeng** [comment]
cc @timothysc @xiang90

**Comment by timothysc** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by hongchaodeng** [comment]
I have verified that the failure wouldn't happen with this fix with the repro steps in https://github.com/kubernetes/kubernetes/pull/32948#issuecomment-248163683

File: pkg/api/rest/resttest/resttest.go [hunk 1]
```diff
@@ -1233,6 +1235,7 @@ func (t *Tester) testWatchFields(obj runtime.Object, emitFn EmitFunc, fieldsPass
 	for _, field := range fieldsPass {
 		for _, action := range actions {
 			options := &api.ListOptions{FieldSelector: field.AsSelector(), ResourceVersion: "1"}
+			ctx = context.WithValue(context.WithValue(ctx, "field", field), "action", action)
```
Comment (hongchaodeng) [inline pkg/api/rest/resttest/resttest.go]: We copy the context in the same way. We want different context. The difference is not judged by object pointer.

**Comment by hongchaodeng** [comment]
kubemark test isn't relevant:
```
(gcloud.compute.firewall-rules.delete) Some requests did not succeed:
```

**Comment by hongchaodeng** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by hongchaodeng** [comment]
This should be P0

**Comment by hongchaodeng** [comment]
@pwittrock 
The "Jenkins Kubemark GCE e2e" keeps being red.

**Comment by pwittrock** [comment]
Alright, I let our testing team know about the issue

**Comment by hongchaodeng** [comment]
@pwittrock Thanks!
How can we re-trigger this now?

**Comment by hongchaodeng** [comment]
@k8s-bot kubemark test this issue: #IGNORE
