### PR TITLE
ignore update pod without new image in alwayspullimages admission controller 

### LINKED ISSUE #96624: Enabling AlwaysPullImages admission causes existing Pods cannot be updated
**What happened**:
We enabled AlwaysPullImages admission in an existing cluster, and found annotations/labels/finalizers of existing Pods whose  imagePullPolicy configured as `IfNotPresent` could not be updated.

AlwaysPullImages admission mutated containerSpec by [changing imagePullPolicy from `IfNotPresent` to `Always`](https://github.com/kubernetes/kubernetes/blob/205d5c58296357365bfa834ecabb384c1c1042c3/plugin/pkg/admission/alwayspullimages/admission.go#L69). And this change later got denied by Pod validation. 
```
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
#   core.PodSpec{
#       Containers: []core.Container{
#               {
#                       ... // 15 identical fields
#                       TerminationMessagePath:   "/dev/termination-log",
#                       TerminationMessagePolicy: "File",
# -                     ImagePullPolicy:          "Always",
# +                     ImagePullPolicy:          "IfNotPresent",
```
It also caused terminating Pods with finalizers stuck forever until we removed AlwaysPullImages admission. 

**What you expected to happen**:
Existing Pods are not affected by AlwaysPullImages admission controller.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure the kube-apiserver with AlwaysPullImages admission controller disabled
2. Create a Pod with imagePullPolicy configured as `IfNotPresent` in its containers
3. Enable AlwaysPullImages admission controller
4. Add annotation to Pod

**Anything else we need to know?**:
If this is confirmed a bug, I can submit a PR to fix this.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-290+09322e8676124e", GitCommit:"09322e8676124e3928db73ebdf5238f3c562dda7", GitTreeState:"clean", BuildDate:"2020-11-05T23:18:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When AlwaysPullImages is enabled,  the annotations/labels/finalizers of existing(old) pod(ImagePullPolicy=IfNotPresent) can not be updated.

The reason is that ImagePullPolicy is immutable container attribute. When we try to update the image of the pod, the ImagePullPolicy will be changed as AlwaysPullImages is enabled. The image change update will failed.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core
```
Fixed the `AlwaysPullImages` admission plugin to tolerate updates of pods with an imagePullPolicy other than `Always` already set
```

**Which issue(s) this PR fixes**:

Fixes #96624 

**Special notes for your reviewer**:
As @bjrara and liggit commented in 96624, This pr tries to ignore update pod when alwayspullimages is enabled.

Another workaround would be that pod need to be recreated after enabling AlwaysPullImages.

> The pod will be still ifNotPresent after updating,  even if the AlwaysPullImages is enabled.
 

**Does this PR introduce a user-facing change?**:

```release-note
ignore update pod with no new images in alwaysPullImages admission controller
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -3972,17 +3974,19 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
 
 	// handle updateable fields by munging those fields prior to deep equal comparison.
 	mungedPod := *newPod
-	// munge spec.containers[*].image
+	// munge spec.containers[*].image and imagePullPolicy for AlwaysPullImages admission controller
 	var newContainers []core.Container
 	for ix, container := range mungedPod.Spec.Containers {
 		container.Image = oldPod.Spec.Containers[ix].Image
+		container.ImagePullPolicy = oldPod.Spec.Containers[ix].ImagePullPolicy
```
Comment (bjrara) [inline pkg/apis/core/validation/validation.go:3981]: Allow changing ImagePullPolicy will cause kubelet to restart container. Is it reasonable?

**Comment by liggitt** [comment]
rather than allowing the imagePullPolicy to be updated, I'd expect the AlwaysPullImages admission plugin to be fixed to ignore/tolerate updates to pods which do not change the container images, even if the pull policy is not `Always`.

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (pacoxu) [reply pkg/apis/core/validation/validation.go]: I changed the solution to `ignore update pod in alwayspullimages admission controller` now. 
Thanks for your comments.

**Comment by pacoxu** [comment]
> rather than allowing the imagePullPolicy to be updated, I'd expect the AlwaysPullImages admission plugin to be fixed to ignore/tolerate updates to pods which do not change the container images, even if the pull policy is not `Always`.

changed to the other solution, ignore update pod in alwayspullimages.

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (bjrara) [reply pkg/apis/core/validation/validation.go]: I guess removing Update from operation would do the same and is easier:
https://github.com/kubernetes/kubernetes/blob/e51d3c92398b31d405483d66b0ebd7b33c5271a2/plugin/pkg/admission/alwayspullimages/admission.go#L120

Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: > I guess removing Update from operation would do the same and is easier:

we should only ignore Update if no images were changed in the new pod spec

**Comment by liggitt** [comment]
we can ignore update requests if no images change like this:

```go
if attributes.GetOperation() == admission.Update {
  oldImages := sets.NewString()
  pods.VisitContainersWithPath(&oldPod.Spec, field.NewPath("spec"), func(c *api.Container, _ *field.Path) bool {
    oldImages.Insert(c.Image)
    return true
  })
  newImages := sets.NewString()
  pods.VisitContainersWithPath(&newPod.Spec, field.NewPath("spec"), func(c *api.Container, _ *field.Path) bool {
    newImages.Insert(c.Image)
    return true
  })
  if oldImages.HasAll(newImages) {
    // ignore updates that don't change the images referenced by the pod spec
    return nil
  }
}
```

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (bjrara) [reply pkg/apis/core/validation/validation.go]: Didn't expect your quick response to my deleting comment. LOL. I agree. Taking the image change into the consideration is a better approach.

**Comment by zhouhaibing089** [comment]
> we can ignore update requests if no images change like this:

Could this strategy be applied to other admissions as well? For example:

1. [LimitRanger][1] which might defaults `resources.limits` on updates.
1. [PodSecurityPolicy][2] which might defaults `securityContexts` on updates.

[1]: https://github.com/kubernetes/kubernetes/blob/1df1f882c4421d313abb468fef5c15f89983471c/plugin/pkg/admission/limitranger/admission.go#L204
[2]: https://github.com/kubernetes/kubernetes/blob/1df1f882c4421d313abb468fef5c15f89983471c/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L92

**Comment by pacoxu** [comment]
> > we can ignore update requests if no images change like this:
> 
> Could this strategy be applied to other admissions as well? For example:
> 
> 1. [LimitRanger](https://github.com/kubernetes/kubernetes/blob/1df1f882c4421d313abb468fef5c15f89983471c/plugin/pkg/admission/limitranger/admission.go#L204) which might defaults `resources.limits` on updates.
> 2. [PodSecurityPolicy](https://github.com/kubernetes/kubernetes/blob/1df1f882c4421d313abb468fef5c15f89983471c/plugin/pkg/admission/security/podsecuritypolicy/admission.go#L92) which might defaults `securityContexts` on updates.

I will test it later to see whether there are bugs in it

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 2]
```diff
@@ -65,6 +66,27 @@ func (a *AlwaysPullImages) Admit(ctx context.Context, attributes admission.Attri
 	if !ok {
 		return apierrors.NewBadRequest("Resource was marked with kind Pod but was unable to be converted")
 	}
+	oldPod, ok := attributes.GetOldObject().(*api.Pod)
```
Comment (bjrara) [inline plugin/pkg/admission/alwayspullimages/admission.go:69]: `getOldObject()` only populates for `Update`. It fails in `Create` operation.

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 3]
```diff
@@ -65,6 +66,27 @@ func (a *AlwaysPullImages) Admit(ctx context.Context, attributes admission.Attri
...
+	if !ok {
+		return apierrors.NewBadRequest("Resource was marked with kind Pod but old object was unable to be converted")
+	}
+
+	if attributes.GetOperation() == admission.Update {
```
Comment (bjrara) [inline plugin/pkg/admission/alwayspullimages/admission.go:74]: Can we add test cases to cover this change?

Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go:70]: Try add some

File: plugin/pkg/admission/alwayspullimages/admission.go (hunk 2 above)
Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go]: fixed. thanks

File: plugin/pkg/admission/alwayspullimages/admission.go (hunk 3 above)
Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go:70]: added

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 4]
```diff
@@ -66,6 +67,28 @@ func (a *AlwaysPullImages) Admit(ctx context.Context, attributes admission.Attri
 		return apierrors.NewBadRequest("Resource was marked with kind Pod but was unable to be converted")
 	}
```
Comment (liggitt) [inline plugin/pkg/admission/alwayspullimages/admission.go:69]: also need to apply the same fix to the Validate() method

Comment (liggitt) [reply plugin/pkg/admission/alwayspullimages/admission.go:69]: suggest factoring this into a `isUpdateWithNoNewImages(attributes) bool` method and calling it both from Admit() and Validate()

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 5]
```diff
@@ -66,6 +67,28 @@ func (a *AlwaysPullImages) Admit(ctx context.Context, attributes admission.Attri
...
+		}
+
+		oldImages := sets.NewString()
+		pods.VisitContainersWithPath(&oldPod.Spec, field.NewPath("spec"), func(c *api.Container, _ *field.Path) bool {
+			oldImages.Insert(c.Image)
+			return true
+		})
+		newImages := sets.NewString()
+		pods.VisitContainersWithPath(&pod.Spec, field.NewPath("spec"), func(c *api.Container, _ *field.Path) bool {
+			newImages.Insert(c.Image)
```
Comment (liggitt) [inline plugin/pkg/admission/alwayspullimages/admission.go:83]: I guess we can check and short-circuit here as soon as we see a new image, rather than accumulating the full set of new images:
```
hasNewImage := false
pods.VisitContainersWithPath(&pod.Spec, field.NewPath("spec"), func(c *api.Container, _ *field.Path) bool {
  if !oldImages.Has(c.Image) {
    hasNewImage = true
  }
  // keep checking additional containers as long as we haven't seen a new image yet
  return !hasNewImage
})
```

Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go]: thanks, nice improvement.

File: plugin/pkg/admission/alwayspullimages/admission.go (hunk 4 above)
Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go:71]: fixed

File: plugin/pkg/admission/alwayspullimages/admission.go (hunk 5 above)
Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go]: the ut finished in 0.6s on my mac now, better than 0.9s before the change.

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 6]
```diff
@@ -101,12 +103,46 @@ func (*AlwaysPullImages) Validate(ctx context.Context, attributes admission.Attr
 	return nil
 }
 
+// check if it's update and it doesn't change the images referenced by the pod spec
+func isUpdateWithNoNewImages(attributes admission.Attributes) bool {
+	if attributes.GetOperation() == admission.Update {
```
Comment (liggitt) [inline plugin/pkg/admission/alwayspullimages/admission.go:108]: nit, prefer returning early and unnesting the rest of the function:

```go
if attributes.GetOperation() != admission.Update {
  return false
}
```

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 7]
```diff
@@ -101,12 +103,46 @@ func (*AlwaysPullImages) Validate(ctx context.Context, attributes admission.Attr
...
+		return !hasNewImage
+	}
+	return false
+}
+
 func shouldIgnore(attributes admission.Attributes) bool {
 	// Ignore all calls to subresources or resources other than pods.
 	if len(attributes.GetSubresource()) != 0 || attributes.GetResource().GroupResource() != api.Resource("pods") {
 		return true
+	} else if isUpdateWithNoNewImages(attributes) {
```
Comment (liggitt) [inline plugin/pkg/admission/alwayspullimages/admission.go:143]: no need to chain the else since the if block returns. simplify to:

```suggestion
	}
	
	if isUpdateWithNoNewImages(attributes) {
```

**Review by liggitt — COMMENTED** [review]
thanks, looks good, just a couple stylistic comments

go ahead and squash to a single commit as well

File: plugin/pkg/admission/alwayspullimages/admission.go (hunk 7 above)
Comment (pacoxu) [reply plugin/pkg/admission/alwayspullimages/admission.go]: @liggitt  Thanks for your patience and detailed comments. Appreciated.

**Comment by pacoxu** [comment]
squashed and fixed

File: plugin/pkg/admission/alwayspullimages/admission.go [hunk 8]
```diff
@@ -101,12 +103,49 @@ func (*AlwaysPullImages) Validate(ctx context.Context, attributes admission.Attr
 	return nil
 }
 
+// check if it's update and it doesn't change the images referenced by the pod spec
+func isUpdateWithNoNewImages(attributes admission.Attributes) bool {
```
Comment (zhouhaibing089) [inline plugin/pkg/admission/alwayspullimages/admission.go:107]: I guess this could be extracted as a utility function and then can be shared in other admissions. :)

**Comment by pacoxu** [comment]
> Could this strategy be applied to other admissions as well? For example:
> 
> LimitRanger which might defaults resources.limits on updates.
> PodSecurityPolicy which might defaults securityContexts on updates.

@zhouhaibing089  
I will extract isUpdateWithNoNewImages as util and check whether it can add to plugin PodSecurityPolicy and LimitRanger recently.
