### PR TITLE
e2e: wrap DRA ResourceQuota Forbidden claim check in gomega.Eventually

### LINKED ISSUE #128410: Failure cluster [e15e458b...]:  cluster supports count/resourceclaims.resource.k8s.io ResourceQuota
##### Error text:
```
[FAILED] creating second claim not allowed
Expected an error, got nil
In [It] at: k8s.io/kubernetes/test/e2e/dra/dra.go:845 @ 10/24/24 09:13:47.98
```

It looks like creating a ResourceQuota object is not having an effect immediately, causing a race that (very rarely!) goes wrong.

#### Recent failures:
[10/29/2024, 1:01:24 AM pr:pull-kubernetes-kind-dra-all](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128298/pull-kubernetes-kind-dra-all/1851051398490230784)
[10/24/2024, 10:54:29 AM pr:pull-kubernetes-kind-dra](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/127550/pull-kubernetes-kind-dra/1849373678001721344)

/kind failing-test
/kind flake

/sig node
/wg device-management

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:

This PR de-flakes the DRA e2e that ensures a ResourceQuota correctly forbids a ResourceClaim that exceeds its defined `count/resourceclaims.resource.k8s.io` quota. #128410 describes that some flakes occurred where the ResourceClaim was admitted without error, likely due to the API server's cache not being up to date like #128899 simulates. This PR updates the check that newly ResourceClaims are rejected with the expected HTTP 403 message eventually, rather than always as soon as possible on the first try.

#### Which issue(s) this PR fixes:

Fixes #128410

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/dra/dra.go [hunk 1]
```diff
@@ -1004,11 +1004,18 @@ var _ = framework.SIGDescribe("node")("DRA", feature.DynamicResourceAllocation,
...
 					})})))
 
-			// Now creating another claim should fail.
-			claim2 := claim.DeepCopy()
-			claim2.Name = "claim-1"
-			_, err = f.ClientSet.ResourceV1beta1().ResourceClaims(f.Namespace.Name).Create(ctx, claim2, metav1.CreateOptions{})
-			gomega.Expect(err).Should(gomega.MatchError(gomega.ContainSubstring("exceeded quota: object-count, requested: count/resourceclaims.resource.k8s.io=1, used: count/resourceclaims.resource.k8s.io=1, limited: count/resourceclaims.resource.k8s.io=1")), "creating second claim not allowed")
+			// Now creating another claim should eventually fail. The quota may not be enforced immediately if
+			// it hasn't yet landed in the API server's cache.
+			gomega.Eventually(func(g gomega.Gomega) {
```
Comment (jackfrancis) [inline test/e2e/dra/dra.go:1009]: I think if we're passing in `g gomega.Gomega` we would need to use `g` to invoke all the gomega foo within the Eventually func. We can probably just skip that and do something like this instead:

```golang
gomega.Eventually(func() err {
claim2 := claim.DeepCopy()
	// If creating a claim erroneously succeeds, we don't want to immediately fail on the next try
	// with an "already exists" error, so use a new name each time.
	claim2.GenerateName = "claim-1-"
	claim2.Name = ""

	_, err := f.ClientSet.ResourceV1beta1().ResourceClaims(f.Namespace.Name).Create(ctx, claim2, metav1.CreateOptions{})
	return err
}).Should(gomega.Expect(err).Should(gomega.MatchError(gomega.ContainSubstring("exceeded quota: object-count, requested: count/resourceclaims.resource.k8s.io=1, used: count/resourceclaims.resource.k8s.io=1, limited: count/resourceclaims.resource.k8s.io=1")), "creating second claim not allowed"))
```

Comment (nojnhuh) [reply test/e2e/dra/dra.go:1009]: Yes, you're right. Thanks!

I'm less confident in that exact syntax, but I'll push the fix to use the `g` inside the `Eventually` now and see if what you had there works.

Comment (nojnhuh) [reply test/e2e/dra/dra.go:1009]: Oh I think I see what you meant. I'll try that out and push that.

**Review by jackfrancis — APPROVED** [review]
/lgtm

File: test/e2e/dra/dra.go [hunk 2]
```diff
@@ -1004,11 +1004,18 @@ var _ = framework.SIGDescribe("node")("DRA", feature.DynamicResourceAllocation,
...
 
-			// Now creating another claim should fail.
-			claim2 := claim.DeepCopy()
-			claim2.Name = "claim-1"
-			_, err = f.ClientSet.ResourceV1beta1().ResourceClaims(f.Namespace.Name).Create(ctx, claim2, metav1.CreateOptions{})
-			gomega.Expect(err).Should(gomega.MatchError(gomega.ContainSubstring("exceeded quota: object-count, requested: count/resourceclaims.resource.k8s.io=1, used: count/resourceclaims.resource.k8s.io=1, limited: count/resourceclaims.resource.k8s.io=1")), "creating second claim not allowed")
+			// Now creating another claim should eventually fail. The quota may not be enforced immediately if
+			// it hasn't yet landed in the API server's cache.
+			gomega.Eventually(ctx, func() error {
+				claim2 := claim.DeepCopy()
```
Comment (pohly) [inline test/e2e/dra/dra.go:1010]: There's no need for the DeepCopy. You can modify the `claim` before the `gomega.Eventually` and then use it over and over again.

Comment (nojnhuh) [reply test/e2e/dra/dra.go]: Good call, updated.

**Comment by pohly** [comment]
/test pull-kubernetes-unit

Because of flake (https://github.com/kubernetes/kubernetes/issues/128962).

File: test/e2e/dra/dra.go [hunk 3]
```diff
@@ -1004,11 +1004,17 @@ var _ = framework.SIGDescribe("node")("DRA", feature.DynamicResourceAllocation,
...
-			_, err = f.ClientSet.ResourceV1beta1().ResourceClaims(f.Namespace.Name).Create(ctx, claim2, metav1.CreateOptions{})
-			gomega.Expect(err).Should(gomega.MatchError(gomega.ContainSubstring("exceeded quota: object-count, requested: count/resourceclaims.resource.k8s.io=1, used: count/resourceclaims.resource.k8s.io=1, limited: count/resourceclaims.resource.k8s.io=1")), "creating second claim not allowed")
+			// Now creating another claim should eventually fail. The quota may not be enforced immediately if
+			// it hasn't yet landed in the API server's cache.
+			//
+			// If creating a claim erroneously succeeds, we don't want to immediately fail on the next try
+			// with an "already exists" error, so use a new name each time.
+			claim.GenerateName = "claim-1-"
+			claim.Name = ""
+			gomega.Eventually(ctx, func() error {
```
[the remark this answers is not in the document]
Comment (jackfrancis) [reply test/e2e/dra/dra.go:1014]: Do we have the appetite to clean up the many instances of `gomega.Eventually` in the k/k codebase that are not using context properly? (there are a lot! :/)

Let me know if there are any SIGs in particular that have an appetite for this and I'd be happy to drive that work.

[the remark this answers is not in the document]
Comment (pohly) [reply test/e2e/dra/dra.go:1014]: > Do we have the appetite to clean up the many instances of gomega.Eventually in the k/k codebase that are not using context properly?

I don't, but I will point it out in new code when I spot it. OTOH, such a search/replace should be safe, so why not?

The biggest issue is that even if we clean up once, developers will keep adding this back unless we provide some linter which warns about this. Reviewers do not always spot this. Such a linter would be [more work](https://github.com/nunnatsa/ginkgolinter/issues/117).

> Let me know if there are any SIGs in particular that have an appetite for this

I'd say "writing better tests" falls under SIG Testing and I've been the TL there who did most of that work in the last years.

[the remark this answers is not in the document]
Comment (jackfrancis) [reply test/e2e/dra/dra.go:1014]: Let's use this PR as a reference, then after it merges I'll submit a PR that cleans up similar usage gaps in the codebase.

[the remark this answers is not in the document]
Comment (nojnhuh) [reply test/e2e/dra/dra.go]: > We should get a new context from `gomega.Eventually` because that honors the timeout set for `gomega.Eventually`.

Just pushed this change.

**Review by pohly — APPROVED** [review]
/lgtm
/approve
