### PR TITLE
Fix flaky hugepages tests by decreasing page count

### LINKED ISSUE #81726: [Flaky tests] NodeFeature:HugePage in ci-kubernetes-node-kubelet-serial
**Which jobs are failing**:
`ci-kubernetes-node-kubelet-serial`

**Which test(s) are failing**:
`NodeFeature:HugePage`-tests

**Since when has it been failing**:
Unsure

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&include-filter-by-regex=Huge&show-stale-tests=

**Reason for failure**:
Unable to pre allocate 50x2MiB huge pages, probably due to memory pressure caused by kernel level caching. If requesting an substantial amount of huge page memory (like the tests), it is recommended to to it as early after boot as possible, or by using the kernel cmd line.

Eg. this one: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1159710677724565504

**Anything else we need to know**:

https://github.com/kubernetes/kubernetes/pull/79241 will fix this issue, but in awaiting for that, we can just decrease the page count in the tests.

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

If requesting an substantial amount of huge page memory
(like the tests), it is recommended to to it as early
after boot as possible, or by using the kernel cmd line.

This pr decrease the amount of pages from 50 to 5.

**Which issue(s) this PR fixes**:

Fixes #81726

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e_node/hugepages_test.go [hunk 1]
```diff
@@ -154,7 +154,7 @@ func runHugePagesTests(f *framework.Framework) {
 							Limits: v1.ResourceList{
 								v1.ResourceName("cpu"):           resource.MustParse("10m"),
 								v1.ResourceName("memory"):        resource.MustParse("100Mi"),
-								v1.ResourceName("hugepages-2Mi"): resource.MustParse("50Mi"),
+								v1.ResourceName("hugepages-2Mi"): resource.MustParse("6Mi"),
```
Comment (mattjmcnaughton) [inline test/e2e_node/hugepages_test.go]: Nit: I may be missing something obvious, but how come this is `6Mi` instead of `5Mi`?

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for the fix! let's monitor this and ensure it has the expected impact.

File: test/e2e_node/hugepages_test.go (hunk 1 above)
Comment (odinuge) [reply test/e2e_node/hugepages_test.go]: `5Mi` will work, but imo. it is a bit strange to say that we want 2.5 huge pages (since their size is 2Mi). k8s will not complain, same with the kernel. In reality you can then only use `4Mi`, since the kernel will floor the page count.

**Comment by mattjmcnaughton** [comment]
On Thu, Aug 22, 2019 at 04:55:41AM -0700, Odin Ugedal wrote:
> odinuge commented on this pull request.
> 
> 
> 
> > @@ -154,7 +154,7 @@ func runHugePagesTests(f *framework.Framework) {
>  							Limits: v1.ResourceList{
>  								v1.ResourceName("cpu"):           resource.MustParse("10m"),
>  								v1.ResourceName("memory"):        resource.MustParse("100Mi"),
> -								v1.ResourceName("hugepages-2Mi"): resource.MustParse("50Mi"),
> +								v1.ResourceName("hugepages-2Mi"): resource.MustParse("6Mi"),
> 
> `5Mi` will work, but imo. it is a bit strange to say that we want 2.5 huge pages (since their size is 2Mi). k8s will not complain, same with the kernel. In reality you can then only use `4Mi`, since the kernel will floor the page count.
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/81727#discussion_r316636960

Ahh, ok ignore me and carry on :)

**Review by oomichi — COMMENTED** [review]
This seems good for me according to https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1159710677724565504 which says hugepage allocation wasn't done in the test clearly:
```

[sig-node]  HugePages [Serial] [Feature:HugePages][NodeFeature:HugePages] With  config updated with hugepages feature enabled should assign hugepages as  expected based on the Pod spec

_output/local/go/src/k8s.io/kubernetes/test/e2e_node/hugepages_test.go:178
 Timed out after 30.000s. Expected
     <*errors.errorString \| 0xc000c63170>: {
         s: "expected hugepages 50, but found 42",
     }
 to be nil
 _output/local/go/src/k8s.io/kubernetes/test/e2e_node/hugepages_test.go:191
```
/lgtm
/approve
