### PR TITLE
kubelet should use the value of the cri container runtime endpoint fr…

### LINKED ISSUE #57005: Mismatch between crio.sock location in crio and kubelet
BUG REPORT

While configuring the kubelet with:
`--container-runtime-endpoint="unix:///var/run/crio.sock"`
And having the sock file on that location (default location from cri), the following error occurs:

`Dec 10 18:30:52 kubeworker01 kubelet[15060]: W1210 18:30:52.739721   15060 manager.go:291] Registration of the crio container factory failed: Get http://%2Fvar%2Frun%2Fcrio%2Fcrio.sock/info: dial unix /var/run/crio/crio.sock: connect: no such file or directory`

Later line:
`Dec 10 18:30:50 kubeworker01 kubelet[15060]: I1210 18:30:50.712558   15060 remote_runtime.go:43] Connecting to runtime service unix:///var/run/crio.sock`

Uses the correct socket.

Result:
Disruptive in understanding other failures.
Containers still start.

**Environment**:
- Kubernetes version: 1.8.0-5, 1.9.0-beta.2
- Cloud provider: gce
- OS: Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux kubeworker01 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: The hard way
- Others:
Full kubelet config (as of now):
```
/usr/local/bin/kubelet 
--allow-privileged=true 
--cluster-dns=10.32.0.10 
--cluster-domain=cluster.local 
--container-runtime=remote 
--container-runtime-endpoint=unix:///var/run/crio.sock 
--image-pull-progress-deadline=2m 
--image-service-endpoint=unix:///var/run/crio.sock 
--kubeconfig=/var/lib/kubelet/kubeconfig 
--cni-conf-dir=/etc/cni/net.d 
--cni-bin-dir=/opt/cni/bin 
--network-plugin=kubenet 
--register-node=true 
--runtime-request-timeout=10m 
--tls-cert-file=/var/lib/kubelet/kubeworker01.pem 
--tls-private-key-file=/var/lib/kubelet/kubeworker01-key.pem 
--v=2
```

Internal log reference: syslog.v6.3

### PR DESCRIPTION
**Pull request by dims**
…om cadvisor

**What this PR does / why we need it**:
To make cri container runtime endpoint consistent, kubelet (currently using "/var/run/crio.sock" ) should use value of CrioSocket exactly as defined in cadvisor.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57005

**Special notes for your reviewer**:

**Release note**:

```release-note
Use the same value for cri container runtime endpoint as defined in cadivsor/crio
```

### CODE REVIEW

**Comment by dims** [comment]
Alternative take on https://github.com/kubernetes/kubernetes/pull/57023

File: pkg/kubelet/cadvisor/util.go [hunk 1]
```diff
@@ -29,6 +29,12 @@ import (
 	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
 )
 
+const (
+	// Please keep this in sync with the one in:
+	// github.com/google/cadvisor/container/crio/client.go
+	CrioSocket = "/var/run/crio/crio.sock"
```
Comment (dixudx) [inline pkg/kubelet/cadvisor/util.go]: This would somehow help solve the building errror. But I still prefer not to have two copies of `CrioSocket`.

Comment (dims) [reply pkg/kubelet/cadvisor/util.go]: @dixudx yes, me too. but since we are really short on time for 1.9 .... i logged it just in case you wanted to chase it. i can abandon this tomorrow

**Comment by sjenning** [comment]
/assign @derekwaynecarr 

Alternative take on #57023 which breaks the kubeadm build for some reason.

**Comment by runcom** [comment]
duplicate of https://github.com/kubernetes/kubernetes/pull/54136 ?

**Comment by mrunalp** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
I think this should make the 1.9 release.

It fixes a regression where the crio socket was moved but the fix in kubelet was not made after the cadvisor rebase.  The impact of not having this fix is kubelet stats summary endpoint will not be correct and autoscaling will not function.
