### PR TITLE
fix: corrupted mount point in csi driver node stage/publish

### LINKED ISSUE #70013: No easy way how to update CSI driver that uses fuse
We recommend to use DaemonSet to run CSI drivers on node. If a driver runs fuse daemon, it's almost impossible to update it, as killing a pod with the driver kills the fuse daemons too and it will kill all mounts, possibly corrupting application data.

We need a documented and supported way how to update such CSI drivers. Note that the update process can be manual or the code can live somewhere else, we just need it to to be documented and supported so people don't loose data.

/sig storage
@msau42 @davidz627 @saad-ali @pohly @vladimirvivien @verult @lpabon @jingxu97 @gnufied

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixed the corrupted mount point in csi driver. Detailed description of this issue could be found here: [No easy way how to update CSI driver that uses fuse](https://github.com/kubernetes/kubernetes/issues/70013)
"
We recommend to use DaemonSet to run CSI drivers on node. If a driver runs fuse daemon, it's almost impossible to update it, as killing a pod with the driver kills the fuse daemons too and it will kill all mounts, possibly corrupting application data.

We need a documented and supported way how to update such CSI drivers. Note that the update process can be manual or the code can live somewhere else, we just need it to to be documented and supported so people don't loose data.
"

With this PR, when fuse based CSI driver daemonset is restarted on the node, original blobfuse mount is broken, this PR would handle broken mount in both `NodeStage` and `NodePublish`
 - detect the broken mount path
 - unmount broken mount path
 - remount mount path

And I think this issue is not only related to fuse based CSI driver, there could be lots of possibilities that stage, publish mount path is broken, we should leave CSI driver itself to handle corrupted mount point, while current behavior is return error directly, there is no way to let CSI driver to handle corrupted mount point.
E.g. in flexvolume, it would leave flexvol driver to handle corrupted mount point:
https://github.com/kubernetes/kubernetes/blob/e4a5012de6b49ca7c3b10c4647205fdca66014ee/pkg/volume/flexvolume/detacher.go#L60-L61

And as I could recall, original in-tree driver could also handle corrupted mount point, and now CSI driver changed this behavior, if it's already a corrupted mount point, there is no way in CSI driver to handle this now.

**Which issue(s) this PR fixes**:

Fixes #70013

**Special notes for your reviewer**:
/assign @msau42 @davidz627 @saad-ali @gnufied
/priority important-soon

**Does this PR introduce a user-facing change?**:

```release-note
fix: corrupted mount point in csi driver
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/volume/csi/csi_attacher.go [hunk 1]
```diff
@@ -228,13 +228,19 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
 		return errors.New(log("attacher.MountDevice failed, deviceMountPath is empty"))
 	}
 
+	corruptedDir := false
 	mounted, err := isDirMounted(c.plugin, deviceMountPath)
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go]: I think actually we may want to skip this check altogether and just always call StagePublish. @gnufied @jsafrane do you see any problems with that? Ref https://github.com/kubernetes/kubernetes/issues/86784

**Comment by msau42** [comment]
/assign @jsafrane 
@kubernetes/sig-storage-pr-reviews

File: pkg/volume/csi/csi_attacher.go (hunk 1 above)
Comment (andyzhangx) [reply pkg/volume/csi/csi_attacher.go]: yes, we don't even need to do `os.MkdirAll(deviceMountPath, 0750)`, all leave csi driver to handle that logic:
https://github.com/kubernetes/kubernetes/blob/e4a5012de6b49ca7c3b10c4647205fdca66014ee/pkg/volume/csi/csi_attacher.go#L290-L293
this looks like a big behavior change, is it ok to do this in this PR?

**Comment by andyzhangx** [comment]
@jsafrane could you take a look? thanks.

File: pkg/volume/csi/csi_attacher.go (hunk 1 above)
Comment (andyzhangx) [reply pkg/volume/csi/csi_attacher.go]: I would like to back port this fix to old release, so shall we go with this PR now?
about `removing the mounted check`, I could work out another PR that won't be back ported, is that ok?  @gnufid thanks.

**Comment by andyzhangx** [comment]
BTW, https://github.com/kubernetes-sigs/blobfuse-csi-driver/pull/117 is an example fix in fuse based driver about how to handle corrupted mount point, so with these two PRs, even fuse driver daemonset is restarted, driver could also work after pod with fuse volume mount restarted.

Also this PR not only mitigated fuse driver issues, e.g. for other remote network file system based csi driver, if remote server does not respond transiently, the mount point could be broken, and new pod mount on the same mount point(using same PV) will fail, this PR could also fix also those  issues.

**Comment by smourapina** [comment]
@andyzhangx, @jsafrane, @msau42:
Bug Triage for release 1.18 checking in. We are a few days away from code freeze (which happens next Thursday, 5 March). Will this PR be merged on time?

**Comment by andyzhangx** [comment]
> @andyzhangx, @jsafrane, @msau42:
> Bug Triage for release 1.18 checking in. We are a few days away from code freeze (which happens next Thursday, 5 March). Will this PR be merged on time?

@smourapina thanks, we are trying. 
@jsafrane, @msau42 @gnufied could you take a look? thanks.

**Comment by jsafrane** [comment]
I think we can merge this PR as it is so it is safe to backport and then, as a separate PR, remove mount check for releases that have reliable uncertain state of mount.

/lgtm
/approve

**Review by feiskyer — APPROVED** [review]
/retest
