### PR TITLE
Ensure that Reason and Message are preserved on pod status

### LINKED ISSUE #103623: [Failing test] [sig-node] InodeEviction [Slow] [Serial] [Disruptive][NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods
##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/eviction_test.go:475
pod memory-hog-pod failed; expected Status.Reason to be Evicted, but got 
Expected
    <string>: 
to equal
    <string>: Evicted
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/eviction_test.go:632
```
#### Recent failures:
[7/9/2021, 3:24:55 AM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413444022743076864)
[7/8/2021, 10:54:57 PM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413376073223114752)
[7/8/2021, 6:24:54 PM ci-kubernetes-node-kubelet-eviction](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-eviction/1413308123812204544)

/kind failing-test

Appears to have started failing after ~6pm 07/08.

/sig node

### PR DESCRIPTION
**Pull request by smarterclayton**
The Kubelet always clears reason and message in generateAPIPodStatus even when the phase is unchanged. It is reasonable that we preserve the previous values when the phase does not change, and clear it when the phase does change.

When a pod is evicted, this ensures that the eviction message and reason are propagated even in the face of subsequent updates. It also preserves the message and reason if components beyond the Kubelet choose to set that value.  If reason/message are changed (due to preemption -> eviction) the most recent value is preserved.

To preserve the value we need to know the old phase, which requires a change to convertStatusToAPIStatus so that both methods have access to it.

/kind bug

#### Which issue(s) this PR fixes:

Fixes #103623

#### Does this PR introduce a user-facing change?

```release-note
The reason and message fields for pod status are no longer reset unless the phase also changes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/assign @Random-Liu 

Since we are not explicitly refreshing the pod status cache after #102344, the sequential status updates in syncTerminatedPod (once at beginning before volume detach, and once after in TerminatePod) result in clearing the message and reason during eviction. This preserves Reason/Message in the `generateAPIPodStatus` unless phase changes, which can occur when soft admission failures move from Running -> Pending (where we want to preserve the message even if other status updates happen).

This also makes the Kubelet more tolerant to other controllers writing reason/message, although that's not a primary goal of this change.

The third commit is a cleanup change but I can move that to the next release if it's concerning.

**Comment by smarterclayton** [comment]
Also note the first commit ensures that soft eviction can't cause the Kubelet to attempt to change a `PodSucceeded` phase to a `PodFailed` phase

**Comment by endocrimes** [comment]
Looks like it fixes the related eviction failures 👍   (remaining ones need unrelated investigation)

**Comment by smarterclayton** [comment]
Looking at some of the tests, my fixes *may* have corrected previous race bugs that might not have been visible:

```
ï¿½[1mSTEPï¿½[0m: making sure we can start a new pod after the test
Jul 20 13:01:59.020: INFO: The status of Pod test-admit-pod is Pending, waiting for it to be Running (with Ready = true)
Jul 20 13:02:01.023: INFO: The status of Pod test-admit-pod is Failed which is unexpected
```

Let me try to reproduce locally here to eliminate my changes as the cause (or conversely, identify whether this is now fixed).

**Comment by Random-Liu** [comment]
The fix makes sense to me. :)

/lgtm
/approve

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -1490,11 +1515,6 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *v1.Pod, podStatus *kubecontaine
 	// set status for Pods created on versions of kube older than 1.6
 	apiPodStatus.QOSClass = v1qos.GetPodQOS(pod)
 
-	oldPodStatus, found := kl.statusManager.GetPodStatus(pod.UID)
-	if !found {
-		oldPodStatus = pod.Status
-	}
```
Comment (ehashman) [inline pkg/kubelet/kubelet_pods.go:1496]: :+1: Lifting this up one call makes a ton of sense to me.

**Review by ehashman — APPROVED** [review]
`[sig-node] InodeEviction [Slow] [Serial] [Disruptive][NodeFeature:Eviction] when we run containers that should cause DiskPressure should eventually evict all of the correct pods` did not fail.

/lgtm
/milestone v1.22
