### PR TITLE
fix flaky test on dra TestPrepareResources/should_timeout

### LINKED ISSUE #119701: pkg/kubelet/cm/dra TestPrepareResources/should_timeout is flaking
### Which jobs are flaking?

https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

### Which tests are flaking?

"TestPrepareResources/should_timeout" in pkg/kubelet/cm/dra/manager_test.go

### Since when has it been flaking?

Not sure.

### Testgrid link

https://testgrid.k8s.io/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

### Reason for failure (if possible)

```
[root@toad1 ~]# git clone https://github.com/kubernetes/kubernetes
Cloning into 'kubernetes'...
remote: Enumerating objects: 1461261, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (74/74), done.
remote: Total 1461261 (delta 68), reused 77 (delta 59), pack-reused 1461128
Receiving objects: 100% (1461261/1461261), 949.88 MiB | 26.76 MiB/s, done.
Resolving deltas: 100% (1070279/1070279), done.
Updating files: 100% (24214/24214), done.
[root@toad1 ~]# cd kubernetes/
[root@toad1 kubernetes]# go version
go version go1.20.6 linux/amd64
[root@toad1 kubernetes]# go test ./pkg/kubelet/cm/dra/ -c -count=1 -race
[root@toad1 kubernetes]# /root/go/bin/stress ./dra.test -test.run TestPrepareResources/should_timeout
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 0 runs so far, 0 failures
20s: 0 runs so far, 0 failures
25s: 0 runs so far, 0 failures
30s: 0 runs so far, 0 failures
35s: 0 runs so far, 0 failures
40s: 0 runs so far, 0 failures
45s: 0 runs so far, 0 failures

/tmp/go-stress-20230731T214323-3184089083
I0731 21:43:24.051801   80582 plugin.go:47] "Register new DRA plugin" name="test-cdi-device" endpoint="/tmp/dra1781754243/server.sock"
I0731 21:44:09.121441   80582 plugin.go:158] "DeRegister DRA plugin" name="test-cdi-device"
--- FAIL: TestPrepareResources (45.11s)
    --- FAIL: TestPrepareResources/should_timeout (45.11s)
        manager_test.go:670:
                Error Trace:    /root/kubernetes/pkg/kubelet/cm/dra/manager_test.go:670
                Error:          An error is expected but got nil.
                Test:           TestPrepareResources/should_timeout
FAIL


ERROR: exit status 1

50s: 4 runs so far, 1 failures (25.00%)
55s: 4 runs so far, 1 failures (25.00%)
^C
[root@toad1 kubernetes]#
```

### Anything else we need to know?

This flakiness was reproducible on ppc64le and x86 architectures.

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by charles-chenzz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix flaky test on dra manager_test.go
#### Which issue(s) this PR fixes:

Fixes #119701

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
@bart0sh: you are better qualified to review this piece of code. Can you take this PR?

@charles-chenzz: I'll leave this to the final review, but if I were to review, I would point out that your change comes with no explanation why it solves the problem and why this is the right way of fixing it.

/unassign

**Comment by bart0sh** [comment]
@pohly my bad. I thought it's fixing dra e2e tests. 
/assign

@charles-chenzz I agree with @pohly. Can you provide an explanation for this PR?

**Comment by charles-chenzz** [comment]
imo the reason why the test will flaky is because we set ``wantTimeOut`` and ``wantError`` and the same time and while the test hit the if-else block, the ``wantTimeOut`` will be catch by ``wantError`` and that's what we don't want to see, it should be catch by ``if wantTimeout`` block

File: pkg/kubelet/cm/dra/manager_test.go [hunk 1]
```diff
@@ -672,6 +671,9 @@ func TestPrepareResources(t *testing.T) {
 			} else if test.wantResourceSkipped {
 				assert.NoError(t, err)
 				return // resource skipped so no need to continue
+			} else if test.wantTimeout {
+				assert.Error(t, err)
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go:675]: Can you explain what's the difference between calling `assert.Error` before and after your changes and why it fixes the flake?

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:675]: First of all I'd like to apologize because I am the one responsible for having introduced this flaky test. However I'm a bit puzzled here because I am not sure to understand how this change is supposed to fix it. [NodePrepareResources](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/pkg/apis/dra/v1alpha3/api.pb.go#L501-L508) is supposed to return an error as soon as the [context deadline](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/plugin/client.go#L91-L113) is exceeded. The call should return an error and fall into the `wantErr` condition. From my understanding the flake is due to expecting an error when nil is received and thus adding this condition should not fix it as it ends to the same situation we are expecting an error but will receive nil. The outcome will be the same except the error trace will point at this new condition instead the former. Could it be possible that the [setup](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/manager_test.go#L95-L98) is responsible of that ? waiting one millisecond longer than the timeout isn't enough ?
Screenshot 2023-08-02 at 23 52 37

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:675]: > Could it be possible that the [setup](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/manager_test.go#L95-L98) is responsible of that ?
Most probably.

Comment (charles-chenzz) [reply pkg/kubelet/cm/dra/manager_test.go:675]: > Can you explain what's the difference between calling `assert.Error` before and after your changes and why it fixes the flake?

I base on the assumption that Thomas said ``setup`` was right, and the reason why it flake is we didn't catch the error right. but I might be wrong didn't consider well enough

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:675]: @charles-chenzz @bart0sh Well I am truly sorry for this because I think my assumption was right, it's all my fault.
I stressed test the case for 1 hour and no fail...

Screenshot 2023-08-03 at 10 28 49

@charles-chenzz I have this open PR #119464 , I can update it to bring the fix or you can do it here in yours, your call.
If you want to do it, here is my change:

```bash
❯ git --no-pager diff HEAD
diff --git a/pkg/kubelet/cm/dra/manager_test.go b/pkg/kubelet/cm/dra/manager_test.go
index 9adb2463d26..22a791ee105 100644
--- a/pkg/kubelet/cm/dra/manager_test.go
+++ b/pkg/kubelet/cm/dra/manager_test.go
@@ -93,7 +93,7 @@ func setupFakeDRADriverGRPCServer(shouldTimeout bool) (string, tearDown, error)
 		driverName: driverName,
 	}
 	if shouldTimeout {
-		timeout := plugin.PluginClientTimeout + time.Millisecond
+		timeout := plugin.PluginClientTimeout + time.Second
 		fakeDRADriverGRPCServer.timeout = &timeout
 	}
```

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:675]: Can you stress test for a 10 Milliseconds? You've increased timeout 1000 times. Not sure it's needed. Let's start from 10x.

Comment (charles-chenzz) [reply pkg/kubelet/cm/dra/manager_test.go:675]: @TommyStarK please go ahead and update and bring to fix in your PR

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:675]: @bart0sh You assumption was correct, 10 Milliseconds seems to be enough.

Screenshot 2023-08-03 at 13 08 04

@charles-chenzz I really don't mind if you do it here, I'm not chasing commits :) I would rather wait to know what Ed thinks it's better. Usually we want to keep specific PR to address specific thing so he might want to have two separate PRs one for cleaning the variables that aren't needed and another to deflake the test

Comment (charles-chenzz) [reply pkg/kubelet/cm/dra/manager_test.go:675]: @TommyStarK yes let's wait for Ed

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:675]: I'd suggest to either update this PR or create new that really fixes the flake.

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:675]: @charles-chenzz  I'd prefer to keep this one and update it, we have the history of our thoughts, it's already triaged and correctly labeled.

```bash
❯ git --no-pager diff HEAD
diff --git a/pkg/kubelet/cm/dra/manager_test.go b/pkg/kubelet/cm/dra/manager_test.go
index 9adb2463d26..e25fb855b89 100644
--- a/pkg/kubelet/cm/dra/manager_test.go
+++ b/pkg/kubelet/cm/dra/manager_test.go
@@ -93,7 +93,7 @@ func setupFakeDRADriverGRPCServer(shouldTimeout bool) (string, tearDown, error)
 		driverName: driverName,
 	}
 	if shouldTimeout {
-		timeout := plugin.PluginClientTimeout + time.Millisecond
+		timeout := plugin.PluginClientTimeout + 10*time.Millisecond
 		fakeDRADriverGRPCServer.timeout = &timeout
 	}
```

**Review by tmilox — APPROVED** [review]

**Review by bart0sh — COMMENTED** [review]
/lgtm

**Comment by bart0sh** [comment]
/assign @klueska @pohly @mrunalp 
For the final approval

File: pkg/kubelet/cm/dra/manager_test.go [hunk 2]
```diff
@@ -93,7 +93,7 @@ func setupFakeDRADriverGRPCServer(shouldTimeout bool) (string, tearDown, error)
 		driverName: driverName,
 	}
 	if shouldTimeout {
-		timeout := plugin.PluginClientTimeout + time.Millisecond
+		timeout := plugin.PluginClientTimeout + 10*time.Millisecond
```
Comment (pohly) [inline pkg/kubelet/cm/dra/manager_test.go:96]: I'm wondering whether this is large enough for the CI. We'll see...

/approve

**Comment by pohly** [comment]
@klueska: please approve. This test flake keeps coming up in different unrelated PRs.

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/119670 might not have been merged yet, perhaps the OOMKiller flake is gone now.
