### PR TITLE
AWS: Allow cross-region image pulling with ECR

### LINKED ISSUE #23298: Cross-region ECR support
I’m having trouble to pull images from ECR on K8S 1.2. Before I was doing it with the imagePullSecrets field, but now I wanted to try the [new feature](http://kubernetes.io/docs/user-guide/images/#using-aws-ec2-container-registry) which sadly didn't work.

The policy for the minion IAM role I have looks just like the one on the [template](https://github.com/kubernetes/kubernetes/blob/master/cluster/aws/templates/iam/kubernetes-minion-policy.json) but it’s failing to pull the image:

```
$ kubectl describe pod myapp-api-celery-deployment-2551798148-bakj7
Name:		myapp-api-celery-deployment-2551798148-bakj7
Namespace:	default
Node:		ip-172-20-0-249.us-west-2.compute.internal/172.20.0.249
Start Time:	Mon, 21 Mar 2016 15:09:49 -0600
Labels:		app=myapp,component=api-celery,pod-template-hash=2551798148
Status:		Pending
IP:		10.244.1.3
Controllers:	ReplicaSet/myapp-api-celery-deployment-2551798148
Containers:
  myapp:
    Container ID:
    Image:		ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
    Image ID:
    Ports:		5672/TCP, 443/TCP, 80/TCP
    QoS Tier:
      cpu:	Burstable
      memory:	BestEffort
    Requests:
      cpu:		100m
    State:		Waiting
      Reason:		ImagePullBackOff
    Ready:		False
    Restart Count:	0
    Environment Variables:
      ENVIRONMENT:	aws
Conditions:
  Type		Status
  Ready 	False
Volumes:
  myapp-secret:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	myapp-secret
  default-token-0r10y:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-0r10y
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath		Type		Reason		Message
  ---------	--------	-----	----							-------------		--------	------		-------
  1m		1m		1	{default-scheduler }								Normal		Scheduled	Successfully assigned myapp-api-celery-deployment-2551798148-bakj7 to ip-172-20-0-249.us-west-2.compute.internal
  1m		35s		4	{kubelet ip-172-20-0-249.us-west-2.compute.internal}	spec.containers{myapp}	Normal		Pulling		pulling image "ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/myapp:latest"
  1m		33s		4	{kubelet ip-172-20-0-249.us-west-2.compute.internal}	spec.containers{myapp}	Warning		Failed		Failed to pull image "ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/myapp:latest": Error: Status 403 trying to pull repository myapp: "Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one."
  1m		33s		4	{kubelet ip-172-20-0-249.us-west-2.compute.internal}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "myapp" with ErrImagePull: "Error: Status 403 trying to pull repository myapp: \"Your Authorization Token has expired. Please run 'aws ecr get-login' to fetch a new one.\""

  1m	7s	7	{kubelet ip-172-20-0-249.us-west-2.compute.internal}	spec.containers{myapp}	Normal	BackOff		Back-off pulling image "ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/myapp:latest"
  1m	7s	7	{kubelet ip-172-20-0-249.us-west-2.compute.internal}				Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "myapp" with ImagePullBackOff: "Back-off pulling image \"ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/myapp:latest\""
```

Maybe it's worth noting the following:
1. The cluster was created with `kube-up.sh` but when it was created there was an existing `kubernetes-minion` role on AWS which didn't have that GetAuthorizationToken policy.
2. I added the policy after creating the cluster, but it didn't work.
3. I terminated the minion instances so that the autoscaler recreated them to see if maybe the policy was not refreshed for those instances. But that didn't work either.

**UPDATE**: as I mentioned on a comment below I didn't know ECR was available on `us-west-2` as well now. It seems that this works fine if both the ECR registry and the cluster are in the same region.

@justinsb

### PR DESCRIPTION
**Pull request by therc**
Fixes #23298
Definitely should be in the release notes; should maybe get merged in 1.2 along with #23594 after some soaking. Documentation changes to follow.

cc @justinsb @erictune @rata @miguelfrde

This is step two. We now create long-lived, lazy ECR providers in all regions.
When first used, they will create the actual ECR providers doing the work
behind the scenes, namely talking to ECR in the region where the image lives,
rather than the one our instance is running in.

Also:
- moved the list of AWS regions out of the AWS cloudprovider and into the
  credentialprovider, then exported it from there.
- improved logging

Behold, running in us-east-1:

```
aws_credentials.go:127] Creating ecrProvider for us-west-2
aws_credentials.go:63] AWS request: ecr:GetAuthorizationToken in us-west-2
aws_credentials.go:217] Adding credentials for user AWS in us-west-2
Successfully pulled image "123456789012.dkr.ecr.us-west-2.amazonaws.com/test:latest"
```

_"One small step for a pod, one giant leap for Kube-kind."_

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24369)

### CODE REVIEW

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 1]
```diff
@@ -59,56 +76,96 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
+// Enabled implements DockerConfigProvider.Enabled for the lazy provider.
+func (p *lazyEcrProvider) Enabled() bool {
+	return true
+}
+
+// LazyProvide implements DockerConfigProvider.LazyProvide. It will be called
+// by the client when attempting to pull an image and it will create the actual
+// provider only when we actually need it the first time.
+func (p *lazyEcrProvider) LazyProvide() *credentialprovider.DockerConfigEntry {
+	if p.actualProvider == nil {
```
Comment (rata) [inline pkg/credentialprovider/aws/aws_credentials.go]: What do you think instead of having the code here inside the if, to create the actualProvider, move it to another function and do something like:

```
if p.actualProvider == nil {
  p.actualProvider = <func to create the actualProvider here>
}
entry := p.actualProvider.Provide()[p.regionURL]
return &entry
```

I'm not sure how the k8s code styling is (will check next week :)), but this is a small detail but it seems slightly more readable for me

File: pkg/credentialprovider/aws/aws_credentials_test.go [hunk 2]
```diff
@@ -58,12 +58,15 @@ func (p *testTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationToken
...
 	registry := "123456789012.dkr.ecr.lala-land-1.amazonaws.com"
-	otherRegistries := []string{"private.registry.com",
+	otherRegistries := []string{
+		"private.registry.com",
 		"gcr.io",
 	}
 	image := "foo/bar"
 
 	provider := &ecrProvider{
+		region: "lala-land-1",
```
Comment (rata) [inline pkg/credentialprovider/aws/aws_credentials_test.go]: Just curious, is there something about the region string that is expected? Do you used a string with "-" 2 times because that is the expected format?

**Comment by rata** [comment]
@therc: nice! I did two small questions, but looks great for me (will test it next week :))

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 1 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: Yes, I was going to try a helper function next. And perhaps, instead of creating N lazy providers, just one, which does a string match against the image getting loaded, figuring the region, then maintaining a map of ecrProviders.

File: pkg/credentialprovider/aws/aws_credentials_test.go (hunk 2 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials_test.go]: I used it because it looks a bit like a real region, but isn't one. It's a old habit, to guard against those rare times when test code ends up running unexpectedly against production.

File: pkg/cloudprovider/providers/aws/aws.go [hunk 3]
```diff
@@ -566,20 +566,7 @@ func getAvailabilityZone(metadata EC2Metadata) (string, error) {
...
-		"eu-central-1",
-		"ap-southeast-1",
-		"ap-southeast-2",
-		"ap-northeast-1",
-		"cn-north-1",
-		"us-gov-west-1",
-		"sa-east-1",
-	}
-	for _, r := range regions {
+	for _, r := range aws_credentials.AWSRegions {
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Nice find!

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 4]
```diff
@@ -59,56 +76,96 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
 	return p.svc.GetAuthorizationToken(input)
 }
 
+// lazyEcrProvider is a DockerConfigProvider that creates on demand an
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: Tip: I personally like to do this:

```
var _ DockerConfigProvider = &lazyEcrProvider{}
```

Apparently there's some debate as to whether or not to do it, but I like that it makes the intent very clear and that it is then checked immediately by the golang compiler.

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 5]
```diff
@@ -59,56 +76,96 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
-	credentialprovider.RegisterCredentialProvider("aws-ecr-key",
-		&credentialprovider.CachingDockerConfigProvider{
-			Provider: &ecrProvider{},
-			// Refresh credentials a little earlier before they expire
+	for _, region := range AWSRegions {
+		credentialprovider.RegisterCredentialProvider("aws-ecr-"+region,
+			&credentialprovider.CachingDockerConfigProvider{
+				Provider: &lazyEcrProvider{
+					region:    region,
+					regionURL: fmt.Sprintf(registryURLTemplate, region),
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: I do wonder if there is value to declaring this as a constant, vs just inlining it.  I find this harder to read, and the constant seems to only be used once.  Up to you.

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 6]
```diff
@@ -59,56 +76,96 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
+				},
+				// This is going to be just a lazy proxy to the real ecrProvider.
+				// It holds no real credentials, so refresh practically never.
+				Lifetime: 365 * 24 * time.Hour,
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: I'm a little confused about why this "extra" CachingDockerConfigProvider is needed (vs just using lazyEcrProvider)?  I'm sure it's just that I'm not (yet) overly familiar with this code, but I'm doubly confused by never refreshing the token...

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 7]
```diff
@@ -59,56 +76,96 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
+			})
+	}
+
+}
+
+// Enabled implements DockerConfigProvider.Enabled for the lazy provider.
+func (p *lazyEcrProvider) Enabled() bool {
+	return true
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: actualProvider.Enabled?

**Comment by justinsb** [comment]
A few code nits/questions, but also:

How does cross-region ECR work in terms of authentication?  Are the IAM instance credentials for us-east-1 valid against a us-west ECR?

Do we now construct an ECR provider against every region?  I don't quite understand how the laziness works...

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 1 above)
Comment (rata) [inline pkg/credentialprovider/aws/aws_credentials.go]: I'm not sure about that. The code this way is pretty simple and the N lazy providers shouldn't make noticiable difference in mem or cpu, and as no real provider is created for the unused, not even messages with the cloud provider are used.

So, I'd do it only if it is equally or more readable than now, and equally or less error prone. If the code gets more messy, I don't think it's worth the effort.

But your call :)

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 6 above)
Comment (rata) [inline pkg/credentialprovider/aws/aws_credentials.go]: Didn't checked the code in credentialprovider, but I *guess* it is not an optional argument. And is registering this lazy provider as the provider. If one is actually used, then the real provider is created.

But maybe I'm not understanding correctly. But this makes me wonder, why not do the lazyness on credentialprovider? Or we don't want the lazyness at that abstraction level? (never even looked at the code, so it might be a totally stupid question, sorry in advance)

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 7 above)
Comment (rata) [inline pkg/credentialprovider/aws/aws_credentials.go]: The actual provider (p.actualProvider) may not exist, IIUC. So, the lazy provider reports as "always enabled" to the credentialprovider and when it is used, the lazy provider creates an actual provider. *IIUC*

**Comment by therc** [comment]
@justinsb in my testing, it looks like my IAM instance credentials in us-east-1 were enough to invoke GetAuthorizationToken in us-west.

We only create empty lazy providers in every region. This layered approach is a compromise between two extremes:

1. Create a real ecrProvider in every region, which obtains and refreshes credentials on a regular basis. This is wasteful for every node to do, especially for the vast majority of people who'll tend to use a local registry. In addition to being more likely to trigger throttling, this might cause timeouts in regions where are there no registries (and there might be none for a long time).
1. Get credentials for every image pulled.

The real ECR provider is only created the first time we try to pull an actual image.

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 7 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: @rata is correct. actualProvider is only created the first time an image is pulled. Enabled() gets called much earlier than that.

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 6 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: You're right, @justinsb, perhaps the CachingDockerConfigProvider is unnecessary, unless we need it for type safety. I'll look into that. We never refresh the token for the lazy provider because it's just a shell for another provider (ecrProvider) that gets created on demand. There are no real credentials inside it to refresh anyway.

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 1 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: Helper/constructor added. I'm still tempted to have one lazy provider (which would definitely require more tests).

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 4 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: Added both.

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 5 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: Well, with the constructor, it's used twice now. :-)

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 6 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: Removed the caching wrapper.

File: pkg/credentialprovider/aws/aws_credentials.go (hunk 7 above)
Comment (therc) [inline pkg/credentialprovider/aws/aws_credentials.go]: I added a comment explaining why we always return true.

**Comment by therc** [comment]
Feedback addessed. I'm still on the fence on whether we should have just one lazy provider vs one for each and every region.

**Comment by rata** [comment]
@therc: great!

**Comment by rata** [comment]
@therc: I'm not familiar with the code at all, but I'm unsure why it's not better to move the lazy-ness to  the "credentialprovider.CachingDockerConfigProvider". I'll try to have a look next week, but don't worry about me. Thanks! :)

**Comment by therc** [comment]
@k8s-bot retest this issue: #21484

**Comment by therc** [comment]
Rebased to pick up ap-northeast-2 from #24457

**Comment by therc** [comment]
Ping?

**Comment by rata** [comment]
@therc IMHO, I don't know if the laziness can be moved a layer up, or even if it makes sense. But in any case, I'm fine with this and improve later if there is room for improvement.

In any case, it doesn't really counts what I say. Probably the best is to ping @justinsb ? :)

**Comment by therc** [comment]
I think this should be reassigned to @justinsb after the bot went crazy the other day. Rebased in the meantime.

**Comment by therc** [comment]
@k8s-bot test this #22655

**Comment by therc** [comment]
@k8s-bot test this issue: #22655

File: pkg/cloudprovider/providers/aws/aws.go [hunk 8]
```diff
@@ -42,7 +42,7 @@ import (
 
 	"k8s.io/kubernetes/pkg/api"
 	"k8s.io/kubernetes/pkg/cloudprovider"
-	"k8s.io/kubernetes/pkg/credentialprovider/aws"
+	aws_credentials "k8s.io/kubernetes/pkg/credentialprovider/aws"
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: This is a confusing alias (I would have guessed "github.com/aws/aws-sdk-go/aws/credentials", but I can't think of a better one that isn't 30 characters long).

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 9]
```diff
@@ -26,23 +27,40 @@ import (
...
 	service := req.ClientInfo.ServiceName
+	region := req.Config.Region
 
 	name := "?"
 	if req.Operation != nil {
 		name = req.Operation.Name
 	}
 
-	glog.V(4).Infof("AWS request: %s %s", service, name)
+	glog.V(3).Infof("AWS request: %s:%s in %s", service, name, *region)
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: I think we probably should guard against the region being nil, but there's only a tiny number of non-regional calls AFAIK, and I think they are all S3 calls.

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 10]
```diff
@@ -59,56 +77,101 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
+			Provider: newEcrProvider(p.region, nil),
+			// Refresh credentials a little earlier than expiration time
 			Lifetime: 11*time.Hour + 55*time.Minute,
-		})
+		}
+		if !p.actualProvider.Enabled() {
+			return nil
+		}
+	}
+	entry := p.actualProvider.Provide()[p.regionURL]
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: I think we should probably guard against an error meaning the region is not present in the DockerConfig map.

File: pkg/credentialprovider/aws/aws_credentials.go [hunk 11]
```diff
@@ -59,56 +77,101 @@ func (p *ecrTokenGetter) GetAuthorizationToken(input *ecr.GetAuthorizationTokenI
...
+	return &entry
+}
+
+// Provide implements DockerConfigProvider.Provide, creating dummy credentials.
+// Client code will call Provider.LazyProvide() at image pulling time.
```
Comment (justinsb) [inline pkg/credentialprovider/aws/aws_credentials.go]: Should we remove the Provide() method from the DockerConfigProvider interface?  I find it confusing that there are now two methods on the interface - it really isn't clear (to me) what is called when.  But I guess that isn't this PR.

**Comment by justinsb** [comment]
I do find this very confusing, so I'm tempted to attempt a refactor, but let's get this merged!  Thanks for implementing - will be very helpful to a lot of people.

File: pkg/cloudprovider/providers/aws/aws.go (hunk 8 above)
Comment (rata) [inline pkg/cloudprovider/providers/aws/aws.go]: aws_cred_provider?

**Comment by therc** [comment]
I'll create another PR with a mini design doc, a link to it and miscellaneous remaining fixes, but yes, it has to be either confusing like this or very inefficient, given the existing design of credential providers.

**Comment by justinsb** [comment]
@therc let's get the AWS PR backlog (of my fault) merged, and then maybe let's look at reworking the design of the credentials provider?  I'm certainly game to take a look, and there's no point doing a lot of documentation it if we're going to change it.  If/when I/we discover this is actually harder than I think and the design must stay, then more documentation is very welcome :-)
