### PR TITLE
Propagate backoff duration for crashloop backoff.

### LINKED ISSUE #123602: Pod Crashloop backoff requeue issues
When stepping through the pod crashloop backoff implementation, I noticed a few issues:

1. Backoff errors are unsuccessfully suppressed:
  - This code is non-functional, since there will always be a non-error result present (`ConfigPodSandbox`) with a nil error: https://github.com/kubernetes/kubernetes/blob/5cf4fbe524ca1479607a4880949a032064556f76/pkg/kubelet/kubelet.go#L1964-L1971
2. The propogated backoff error means that the pod worker always immediately requeues the pod: https://github.com/kubernetes/kubernetes/blob/5cf4fbe524ca1479607a4880949a032064556f76/pkg/kubelet/pod_workers.go#L1495-L1497
  - If the backoff error were suppressed, then the default 1m sync frequency would be used, which would cause very long initial backoffs.

The result of these issues are:
1. Log spam: `E0301 01:06:01.286649    1869 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"alpine\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=alpine pod=restarting-pod_default(ca0d5836-1435-497e-9a41-547fbcc10484)\"" pod="default/restarting-pod" podUID=ca0d5836-1435-497e-9a41-547fbcc10484` get's logged in a frequent loop
2. Kubelet does unnecessary work to reexamine pods and containers in backoff
3. (minor) the error retry period is 10s, which adds up to 10s to the backoff time

I think the ideal fix is to propagate the backoff retry time up from SyncPod [1] to the pod worker [2], so that the pod can be requeued with the exact (jittered) right amount of retry time. One option is to use a custom error type to encapsulate the backoff time, which I started working on here: https://github.com/tallclair/kubernetes/commit/5d89eb2538cc8929540476f436d4a1b92c9babee

Of course, there is very little test coverage across these code paths too.

[1]: https://github.com/kubernetes/kubernetes/blob/5cf4fbe524ca1479607a4880949a032064556f76/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1325
[2]: https://github.com/kubernetes/kubernetes/blob/5cf4fbe524ca1479607a4880949a032064556f76/pkg/kubelet/pod_workers.go#L1484

/sig node
/kind bug

### PR DESCRIPTION
**Pull request by hankfreund**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This pull request introduces a mechanism to allow the container management layer to propagate a specific backoff duration up to the Kubelet's pod sync loop, particularly for containers in CrashLoopBackOff.

Currently, when a container enters a CrashLoopBackOff state, the Kubelet's container manager calculates a backoff to delay restarts. However, this specific backoff duration is not communicated back to the pod worker that schedules the pod syncs. The pod worker then uses its own default backoff value, leading to a disconnect between the calculated delay and the actual delay.

This PR addresses this by introducing a new error type, `BackoffError`, which embeds a backoff duration. This allows the container start logic to return this specialized error when a container restart should be backed off, specifying the exact duration. The Kubelet's pod sync loop is updated to use a new `MinBackoff` function on the sync result. If a specific backoff duration is found, it is used for the backoff, ensuring the precisely calculated delay is respected.

#### Which issue(s) this PR is related to:

Fixes #123602

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/container/sync_result.go [hunk 1]
```diff
@@ -19,14 +19,62 @@ package container
...
+func NewBackoffError(err error, backoffTime time.Duration) *BackoffError {
+	return &BackoffError{
+		err:         err,
+		backoffTime: backoffTime,
+	}
+}
+
+func (e *BackoffError) Error() string {
+	return e.err.Error()
+}
```
Comment (tallclair) [inline pkg/kubelet/container/sync_result.go]: optional: you could just embed the error in the backoff struct, and omit this method. i.e.

```go
type BackoffError struct {
  error
  backoffTime time.Duration
}
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -1550,9 +1550,10 @@ func (m *kubeGenericRuntimeManager) doBackOff(pod *v1.Pod, container *v1.Contain
 			m.recorder.Eventf(containerRef, v1.EventTypeWarning, events.BackOffStartContainer,
 				fmt.Sprintf("Back-off restarting failed container %s in pod %s", container.Name, format.Pod(pod)))
 		}
-		err := fmt.Errorf("back-off %s restarting failed container=%s pod=%s", backOff.Get(key), container.Name, format.Pod(pod))
+		backoff := backOff.Get(key)
```
Comment (tallclair) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1637]: I think what you want here is the remaining backoff, which would be
```go
remainingBackoff := backoff - time.Since(ts)
```

Although, I wonder if it's better to use an absolute timestamp in case the rest of the SyncPod work is slow? I.e.
```
backoffTime := ts.Add(backoff)
```

File: pkg/kubelet/container/sync_result.go [hunk 3]
```diff
@@ -19,14 +19,62 @@ package container
...
+					min = backoff
+					found = true
+				}
+			}
+		}
+		return min, found
+	default:
+		if e := errors.Unwrap(err); e != nil {
+			return MinBackoff(e)
+		}
```
Comment (tallclair) [inline pkg/kubelet/container/sync_result.go:69]: I don't think you need to call `Unwrap` here, since `errors.As` already does that.

File: pkg/kubelet/pod_workers_test.go [hunk 4]
```diff
@@ -882,6 +885,88 @@ func TestUpdatePod(t *testing.T) {
...
+
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			podWorkers, _, _ := createPodWorkers()
+			fakeQueue := podWorkers.workQueue.(*fakeQueue)
+			podUID := types.UID("12345")
+
+			podWorkers.backOffPeriod = defaultBackoff
+
+			podWorkers.podLock.Lock()
```
Comment (HirazawaUi) [inline pkg/kubelet/pod_workers_test.go]: The lock here is unnecessary, right?

File: pkg/kubelet/pod_workers_test.go [hunk 5]
```diff
@@ -882,6 +885,88 @@ func TestUpdatePod(t *testing.T) {
 	}
 }
 
+func TestCompleteWorkWithSyncError(t *testing.T) {
```
Comment (HirazawaUi) [inline pkg/kubelet/pod_workers_test.go]: Since you've added unit tests for this function, why not consider covering other scenarios? e.g.

* phaseTransition is true

* syncErr is nil

* syncErr is NetworkNotReady

* status.pendingUpdate is not nil

.....

File: pkg/kubelet/pod_workers_test.go [hunk 6]
```diff
@@ -18,12 +18,15 @@ package kubelet
...
 import (
 	"context"
+	"errors"
 	"reflect"
 	"strconv"
 	"sync"
 	"testing"
 	"time"
 
+	utilerrors "k8s.io/apimachinery/pkg/util/errors"
```
Comment (HirazawaUi) [inline pkg/kubelet/pod_workers_test.go]: Super nit: please group the imports by organization.

ref: https://go.dev/wiki/CodeReviewComments#imports

**Review by HirazawaUi — COMMENTED** [review]
This is definitely a positive improvement. Do we have a way to validate it through testing?

e.g.

* Add an e2e test to verify whether the pod's backoff interval falls within our expected range?

* Or based on the current PR, have you verified:

  * Whether kubelet still produces noisy logs when a pod crashes?
  
  * And whether the pod's backoff time meets expectations?

File: pkg/kubelet/container/sync_result.go (hunk 1 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go]: Done!

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (hankfreund) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1637]: The absolute timestamp makes more sense. Updated accordingly.

File: pkg/kubelet/container/sync_result.go (hunk 3 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go:69]: The first two cases in the select apply to specific errors, the default case will hit if neither matches, so I think the unwrap is necessary for the unknown error type?

File: pkg/kubelet/pod_workers_test.go (hunk 4 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers_test.go]: Right! Removed.

File: pkg/kubelet/pod_workers_test.go (hunk 5 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers_test.go]: Added more test cases to round out this test and added a second test for the pendingUpdate checks.

File: pkg/kubelet/pod_workers_test.go (hunk 6 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers_test.go]: Re-ordered.

**Comment by hankfreund** [comment]
Experimentally, there are fewer logs with the default crashloopbackoff because the task isn't being enqueued for 10s at a time. The log spam will ultimately depend on the max setting of crashloopbackoff (which is configurable with a feature gate now).

**Comment by HirazawaUi** [comment]
> Experimentally, there are fewer logs with the default crashloopbackoff because the task isn't being enqueued for 10s at a time. The log spam will ultimately depend on the max setting of crashloopbackoff (which is configurable with a feature gate now).

Since the backoff time is quantifiable, this seems valuable to add an e2e test case:

* Start a quick-fail pod.

* Wait for the pod to enter CrashLoopBackOff and trigger a restart.

* Calculate whether the backoff time the pod requires is within our expected.

**Comment by hankfreund** [comment]
After spending the day trying to get a test working for this, I've observed:
1. This change specifically deals with when and how often the pod will be enqueued to potentially do work. Within an e2e test, the only observability I have is after the pod has been scheduled, attempted to start, failed, and logged its termination time. The amount of slop in that intervening time causes a fair bit of flakiness.
2. I noticed that the pod worker will enqueue the pod twice in rapid succession the first time it "crashes" (observed even without this change). This leads to occasional reporting by the pod that it has terminated twice within a second or two of the last (as if it had been enqueued to run again immediately). This also leads to flakes.

I haven't looked into the second issue yet since it's outside the scope of this change. What do you say we leave this PR as-is and revisit the test after the second issue is investigated/resolved?


Relevant log demonstrating the issue, in case you were curious:
```
Jul 22 21:42:36 kind-worker kubelet[233]: E0722 21:42:36.871699     233 pod_workers.go:1324] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"crasher\" with back-off 10s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc): \"back-off 10s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc)\"" pod="crashloop-backoff-test-8752/crashloop-pod" podUID="3c35cad2-f2c9-4181-824c-e7e3ca628efc"
...
Jul 22 21:42:37 kind-worker kubelet[233]: E0722 21:42:37.877788     233 pod_workers.go:1324] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"crasher\" with back-off 10s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc): \"back-off 10s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc)\"" pod="crashloop-backoff-test-8752/crashloop-pod" podUID="3c35cad2-f2c9-4181-824c-e7e3ca628efc"
...
Jul 22 21:42:49 kind-worker kubelet[233]: E0722 21:42:49.918823     233 pod_workers.go:1324] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"crasher\" with back-off 20s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc): \"back-off 20s restarting failed container=crasher pod=crashloop-pod_crashloop-backoff-test-8752(3c35cad2-f2c9-4181-824c-e7e3ca628efc)\"" pod="crashloop-backoff-test-8752/crashloop-pod" podUID="3c35cad2-f2c9-4181-824c-e7e3ca628efc"
```
Note the first two logs indicate a 10s backoff, within ~1s of each other. The next backoff for 20s is seen ~10s later, as expected.

File: pkg/kubelet/container/sync_result.go [hunk 7]
```diff
@@ -19,14 +19,59 @@ package container
 import (
 	"errors"
 	"fmt"
+	"time"
 
 	utilerrors "k8s.io/apimachinery/pkg/util/errors"
 )
 
 // TODO(random-liu): We need to better organize runtime errors for introspection.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/container/sync_result.go]: move comment to the errs declaration

**Comment by SergeyKanzhelev** [comment]
pls squash commits

File: pkg/kubelet/container/sync_result.go [hunk 8]
```diff
@@ -19,14 +19,59 @@ package container
...
+// to the Kubelet.
+type BackoffError struct {
+	error
+	backoffTime time.Time
+}
+
+func NewBackoffError(err error, backoffTime time.Time) *BackoffError {
+	return &BackoffError{
+		error:       err,
+		backoffTime: backoffTime,
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/container/sync_result.go:37]: why not operate with durations instead of a time. using time and then waiting on `time-time.Now` can potentially lead to panic

File: pkg/kubelet/container/sync_result.go [hunk 9]
```diff
@@ -19,14 +19,59 @@ package container
...
+					found = true
+				}
+			}
+		}
+		return min, found
+	default:
+		if e := errors.Unwrap(err); e != nil {
+			return MinBackoffExpiration(e)
+		}
+		return time.Time{}, false
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/container/sync_result.go:70]: it this is returned, than it would be a large negative number when substituted from now? Can we ever get to this point? If so - would time.Now be a better thing to return from here?

**Review by SergeyKanzhelev — COMMENTED** [review]
is there any test can be written that demonstrates the problem (failing with existing code and passing with the new code)?

File: pkg/kubelet/container/sync_result.go (hunk 8 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go:37]: I originally had a duration. @tallclair commented above it would probably be better to use an absolute expiration time to avoid adding extra delay between when the error is returned and the pod worker tries to schedule it.

File: pkg/kubelet/container/sync_result.go (hunk 9 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go:70]: If we reach here, we also return `false`, so the caller shouldn't use the time value at all.

File: pkg/kubelet/container/sync_result.go (hunk 7 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go]: Done.

**Comment by hankfreund** [comment]
I commented above about the difficulties in writing a test to check for this. It's pretty flaky to rely on imprecise times -- though it can probably be done with some wide tolerations. I also (think I) uncovered a bug (described above) which makes testing even more flaky.

The previous behavior which this change fixes is not deterministic, so writing a test that consistently fails with it is infeasible.

File: pkg/kubelet/pod_workers.go [hunk 10]
```diff
@@ -1519,8 +1519,15 @@ func (p *podWorkers) completeWork(podUID types.UID, phaseTransition bool, syncEr
...
-		// Error occurred during the sync; back off and then retry.
-		p.workQueue.Enqueue(podUID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		// Error occurred during the sync; back off and then retry. If the error includes a backoff expiration,
+		// wait until then instead of the default to avoid adding extra time to the backoff.
+		var backoffAt time.Time
+		var isBackoffErr bool
+		if backoffAt, isBackoffErr = kubecontainer.MinBackoffExpiration(syncErr); !isBackoffErr {
+			backoffAt = p.clock.Now().Add(p.backOffPeriod)
+		}
+		backoff := backoffAt.Sub(p.clock.Now())
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/pod_workers.go]: so perhaps we should test that this is a positive number

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1637]: the problem with absolute value is that the time shift (synchronization with the time server for example) can lead to unexpected consequences. So if we switch to absolute - we definitely need to check for `>0` and `<some-max-value`

File: pkg/kubelet/pod_workers.go (hunk 10 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go]: Yeah, that makes sense. Added the check + test.

File: pkg/kubelet/pod_workers.go [hunk 11]
```diff
@@ -1519,8 +1519,18 @@ func (p *podWorkers) completeWork(podUID types.UID, phaseTransition bool, syncEr
 		// Network is not ready; back off for short period of time and retry as network might be ready soon.
 		p.workQueue.Enqueue(podUID, wait.Jitter(backOffOnTransientErrorPeriod, workerBackOffPeriodJitterFactor))
 	default:
-		// Error occurred during the sync; back off and then retry.
-		p.workQueue.Enqueue(podUID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		// Error occurred during the sync; back off and then retry. If the error includes a backoff expiration,
+		// wait until then instead of the default to avoid adding extra time to the backoff.
+		var backoffAt time.Time
+		var isBackoffErr bool
+		if backoffAt, isBackoffErr = kubecontainer.MinBackoffExpiration(syncErr); !isBackoffErr {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/pod_workers.go]: so if the `isBackoffErr` is `false` than we keep the `backoffAt` to be zero? should the  `backoffAt` be initialized differently?

I think the code will work as written (with the zero check added now). But I am concerned with the style.

File: pkg/kubelet/pod_workers.go [hunk 12]
```diff
@@ -1519,8 +1519,18 @@ func (p *podWorkers) completeWork(podUID types.UID, phaseTransition bool, syncEr
...
+			backoffAt = p.clock.Now().Add(p.backOffPeriod)
+		}
+		backoff := backoffAt.Sub(p.clock.Now())
+		if backoff < 0 {
+			backoff = 0
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/pod_workers.go:1529]: is `0` handled well by `wait.Jitter` and queue processor? Was it zero ever before?

File: pkg/kubelet/pod_workers.go [hunk 13]
```diff
@@ -1519,8 +1519,18 @@ func (p *podWorkers) completeWork(podUID types.UID, phaseTransition bool, syncEr
...
-		p.workQueue.Enqueue(podUID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		// Error occurred during the sync; back off and then retry. If the error includes a backoff expiration,
+		// wait until then instead of the default to avoid adding extra time to the backoff.
+		var backoffAt time.Time
+		var isBackoffErr bool
+		if backoffAt, isBackoffErr = kubecontainer.MinBackoffExpiration(syncErr); !isBackoffErr {
+			backoffAt = p.clock.Now().Add(p.backOffPeriod)
+		}
+		backoff := backoffAt.Sub(p.clock.Now())
+		if backoff < 0 {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/pod_workers.go:1528]: I am a bit worried if we need to check for some max value as well. I want to make sure we are protected from some crazy big values.

File: pkg/kubelet/pod_workers.go (hunk 12 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go:1529]: 0 is used (without jitter) above in the switch, so the queue processor can definitely handle it. The unit tests don't seem to have an issue with the jitter + 0 delay.

File: pkg/kubelet/pod_workers.go (hunk 11 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go]: No, if `isBackoffErr` is `false`, we set `backoffAt` to the (previous default) `p.backOffPeriod` (which is 10s). There is a unit test for this case.

Comment (hankfreund) [reply pkg/kubelet/pod_workers.go]: Slight clarification: we set `backoffAt` to `now() + p.backOffPeriod`, which will be 10s from now.

Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go]: ok, I misread the code.

Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go]: for me it would be more logical to initialize backoff differently depending on `isBackoffErr`. So we do not do Add and Subtract. It is ok I guess as written, just harder to read

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go:1528]: I've added a max enqueue duration of 5 minutes + relevant test.

File: pkg/kubelet/pod_workers.go (hunk 11 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go]: That's fair. I re-ordered the logic the way I think you'd prefer.

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: so my understanding is that it used to be 10 seconds all the time. Now we are switching to some longer value up to 5 minutes. So we are not only optimizing against the "adding extra time to the backoff". But also optimizing how often we sync up if backoff period is high.

Off the top of my head I do not know if it may break something. Likely it is ok since the container is not suppose to be changed while in backoff. But merging the last day of a code freeze is not something I am comfortable with. At minimum it should be no longer than 10 seconds - original sync period.

File: pkg/kubelet/container/sync_result.go [hunk 14]
```diff
@@ -19,14 +19,59 @@ package container
...
+	}
+}
+
+// BackoffTime returns the expected expiration time of the backoff.
+func (e *BackoffError) BackoffTime() time.Time {
+	return e.backoffTime
+}
 
-// ErrCrashLoopBackOff returned when a container Terminated and Kubelet is backing off the restart.
-var ErrCrashLoopBackOff = errors.New("CrashLoopBackOff")
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/container/sync_result.go:29]: is this string not used anywhere any longer? I see this string being used in the test in test/e2e_node/container_restart_test.go and I wonder if that string is coming from here.

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go:1528]: Part of the reason for the change was to reduce both log spam and the amount of work done to check a pod in backoff unnecessarily. Putting the max at 10 seconds removes both of those benefits entirely. 
Let's wait for @tallclair to return and discuss further with him.

File: pkg/kubelet/container/sync_result.go (hunk 14 above)
Comment (hankfreund) [reply pkg/kubelet/container/sync_result.go:29]: Ah, yeah, probably. I'll put the string back and return it appropriately.

**Comment by lmktfy** [comment]
Does this PR introduce a user-facing change?

**Comment by hankfreund** [comment]
> Does this PR introduce a user-facing change?

No, this is not a user-facing change.

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: ok, the PR description was not mentioning the savings from less calls to sync. I wonder if there are any other things that may need a sync while it is in crash loop backoff? Can container image or request/limit be changed? Will we need to sync in this case or it will be forced somehow?

Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: definitely need more tests if we increase 10s -> 5 min

File: pkg/kubelet/pod_workers.go [hunk 15]
```diff
@@ -1519,8 +1522,18 @@ func (p *podWorkers) completeWork(podUID types.UID, phaseTransition bool, syncEr
...
+		// Error occurred during the sync; back off and then retry. If the error includes a backoff expiration,
+		// wait until then instead of the default to avoid adding extra time to the backoff.
+		backoff := p.backOffPeriod
+		if backoffAt, isBackoffErr := kubecontainer.MinBackoffExpiration(syncErr); isBackoffErr {
+			backoff = backoffAt.Sub(p.clock.Now())
+		}
+		if backoff < 0 {
+			backoff = 0
+		} else if backoff > maxEnqueueDuration {
+			backoff = maxEnqueueDuration
```
Comment (tallclair) [inline pkg/kubelet/pod_workers.go]: maybe we should just use the default sync interval (`p.resyncInterval`) as the max? That is the interval that we want to be checking the pod in steady-state, so I think it makes sense as a cap.

Comment (tallclair) [reply pkg/kubelet/pod_workers.go]: The resync interval is usually 1 minute, so it's effectively the same as what you have.

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (tallclair) [reply pkg/kubelet/pod_workers.go:1528]: What kind of tests are you looking for, @SergeyKanzhelev ? It's basically impossible to test this in E2E because the timing is so imprecise in that environment.

**Review by tallclair — COMMENTED** [review]
This LGTM (minor nit about the max backoff interval), but I think Sergey should explicitly ACK the change before merging based on his comments.

File: pkg/kubelet/pod_workers.go (hunk 15 above)
Comment (hankfreund) [reply pkg/kubelet/pod_workers.go]: Removed `maxEnqueueDuration` and used `p.resyncInterval` instead.

File: pkg/kubelet/pod_workers.go (hunk 13 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: The tests I was looking for is about what's possible during the backoff interval. Can somebody do in-place resize? Change an image? And whether this logic can change this ability.

Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: with the check below of `backoff > p.resyncInterval` it doesn't look that critical. But if we are switching higher value, we will need to understand if dynamic container update scenarios scenarios may be affected.

Comment (SergeyKanzhelev) [reply pkg/kubelet/pod_workers.go:1528]: /lgtm
/approve
