### PR TITLE
fix bug iscsi volume attach failed of /sys/class/iscsi_host dir not e…

### LINKED ISSUE #74640: standalone cinder provisioner use iscsi raw pv can not attach the k8s minion
**What happened**:
i use the standalone-cinder-provisioner and the backend storage is iscsi,the pv and volume can dynamic created,but the device can not attached the k8s minion

the standalone-cinder-provisioner pod yaml use the web :https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/provisioner/deployment.yaml

and the pod running:
kube-system standalone-cinder-provisioner-7c4649c886-5x6x6 1/1 Running 7 5d5h

[root@hpa-vm:/home/ubuntu/jlx]$ kubectl get pv
NAME CAPACITY ACCESS MODES RECLAIM POLICY STATUS CLAIM STORAGECLASS REASON AGE
pvc-1dff02aa-3140-11e9-bde3-002dc92800b3 1Gi RWO Delete Bound kube-system/keystone-sc-pvc standard 6d4h

the pv infomation:
[root@hpa-vm:/home/ubuntu/jlx]$ kubectl get pv pvc-1dff02aa-3140-11e9-bde3-002dc92800b3 -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
annotations:
cinderVolumeId: c6daa97f-0bc7-4e8a-879d-1800ba51264a
pv.kubernetes.io/provisioned-by: openstack.org/standalone-cinder
standaloneCinderProvisionerIdentity: openstack.org/standalone-cinder
creationTimestamp: "2019-02-15T16:38:33Z"
finalizers:

    external-provisioner.volume.kubernetes.io/finalizer
    kubernetes.io/pv-protection
    name: pvc-1dff02aa-3140-11e9-bde3-002dc92800b3
    resourceVersion: "5776760"
    selfLink: /api/v1/persistentvolumes/pvc-1dff02aa-3140-11e9-bde3-002dc92800b3
    uid: 225064bd-3140-11e9-bde3-002dc92800b3
    spec:
    accessModes:
    ReadWriteOnce
    capacity:
    storage: 1Gi
    claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: keystone-sc-pvc
    namespace: kube-system
    resourceVersion: "5776739"
    uid: 1dff02aa-3140-11e9-bde3-002dc92800b3
    iscsi:
    initiatorName: iqn.2018-01.io.k8s:a13fc3d1cc22
    iqn: iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:54
    iscsiInterface: default
    lun: 1
    targetPortal: 19.19.19.252:3260
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
    status:
    phase: Bound

[root@host-12-12-12-30 standalone]# kubectl get po --all-namespaces -w 
NAMESPACE     NAME                                             READY   STATUS              RESTARTS   AGE
default       iscsi-standalone                                 0/1     ContainerCreating   0          2s

[root@host-12-12-12-30 standalone]# kubectl describe pod iscsi-standalone 
Name:               iscsi-standalone
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               12.12.12.30/12.12.12.30
Start Time:         Tue, 26 Feb 2019 17:15:19 +0800
Labels:             <none>
Annotations:        <none>
Status:             Pending
IP:                 
Containers:
  iscsi:
    Container ID:   
    Image:          gcr.io/google_containers/nginx:1.7.9
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-frzl8 (ro)
      /var/www/html from mypd (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mypd:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  keystone-sc-pvc-storage13
    ReadOnly:   false
  default-token-frzl8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-frzl8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                   From                     Message
  ----     ------                  ----                  ----                     -------
  Normal   Scheduled               4m48s                 default-scheduler        Successfully assigned default/iscsi-standalone to 12.12.12.30
  Normal   SuccessfulAttachVolume  4m48s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9121a7b1-39a5-11e9-b3a9-fa163e2d9049"
  Warning  FailedMount             30s (x10 over 4m40s)  kubelet, 12.12.12.30     MountVolume.WaitForAttach failed for volume "pvc-9121a7b1-39a5-11e9-b3a9-fa163e2d9049" : open /sys/class/iscsi_host: no such file or directory
  Warning  FailedMount             29s (x2 over 2m45s)   kubelet, 12.12.12.30     Unable to mount volumes for pod "iscsi-standalone_default(096dfc21-39a7-11e9-bb03-fa163e2d9049)": timeout expired waiting for volumes to attach or mount for pod "default"/"iscsi-standalone". list of unmounted volumes=[mypd]. list of unattached volumes=[mypd default-token-frzl8]

**What you expected to happen**:
the pod can running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:k8s v1.13
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jianglingxia**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
the iscsi volume can not attached the minion,because the iscsi modules haven't even been loaded yet, the /sys/class/iscsi_host directory won't exist
**Which issue(s) this PR fixes**:
Fixes #74640

**Special notes for your reviewer**:
@bswartz
**Does this PR introduce a user-facing change?**:

```release-note
iscsi modules haven't even been loaded /sys/class/iscsi_host directory won't exist
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
i have tested in my enviroment,that the pod can attached and mounted running

[root@host-12-12-12-30 standalone]# kubectl get po -w
NAME                      READY   STATUS              RESTARTS   AGE
iscsi-standalone-modify   0/1     ContainerCreating   0          5s
iscsi-standalone-modify   1/1   Running   0     37s


I0301 13:46:45.008924    5877 reconciler.go:237] Starting operationExecutor.MountVolume for volume "pvc-9121a7b1-39a5-11e9-b3a9-fa163e2d9049" (UniqueName: "kubernetes.io/iscsi/10.62.101.137:3260:iqn.2099-01.cn.com.zte:usp.spr11-74:4a:a4:01:fd:5d:4") pod "iscsi-standalone-modify" (UID: "51f19fb7-3be5-11e9-aaab-fa163e2d9049")

File: pkg/volume/util/device_util_linux.go [hunk 1]
```diff
@@ -99,7 +99,7 @@ func (handler *deviceHandler) GetISCSIPortalHostMapForTarget(targetIqn string) (
 	sysPath := "/sys/class/iscsi_host"
 	hostDirs, err := io.ReadDir(sysPath)
 	if err != nil {
-		return nil, err
+		return portalHostMap, nil
```
Comment (bswartz) [inline pkg/volume/util/device_util_linux.go]: We need to distinguish between does-not-exist and cant-read types of error here. It's only correct to return the empty map when the directory doesn't exist.

**Review by bswartz — CHANGES_REQUESTED** [review]

File: pkg/volume/util/device_util_linux.go (hunk 1 above)
Comment (jianglingxia) [reply pkg/volume/util/device_util_linux.go]: thanks for your review,and i have remodify it for your review!

**Review by bswartz — APPROVED** [review]

**Comment by jianglingxia** [comment]
/assign @saad-ali
@bswartz need approve label? thanks

**Comment by jianglingxia** [comment]
PTAL @saad-ali for approve thanks
