### PR TITLE
Get filesystem stats for files on Windows

### LINKED ISSUE #99173: sig-windows - Unable to fetch container log stats: failed to get fsstats
#### What happened:

Since 1.21+ the logs have the following error:

```
kubelet.err.log:55217:E0217 22:31:38.504066    5040 cri_stats_provider.go:583] Unable to fetch container log stats: 
failed to get fsstats for  "\\var\\log\\pods\\default_iis-1809-668c5b9c87-44vpx_195e99c4-a5d0-4908-9835-9b89a9b3e453\\iis\\0.log": 
failed to get FsInfo due to error The directory name is invalid.                                                           
```

#### What you expected to happen:
no error for pods

#### How to reproduce it (as minimally and precisely as possible):
Deploy iis image and check the kubelet logs:

```
k apply -f https://gist.githubusercontent.com/jsturtevant/5f49c3bd9218666af877927a674b7645/raw/fb042ff14b689c308c9404422e08cf85c56b6ff1/deployment.yaml
```

#### Anything else we need to know?:

looks like it is erroring out here:

https://github.com/kubernetes/kubernetes/blob/b2860a360441d15a2f1a7b63e9ca247e5b0ec784/pkg/kubelet/stats/host_stats_provider.go#L133-L135

looks like it might be related to changes in https://github.com/kubernetes/kubernetes/pull/97042

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21+
- Cloud provider or hardware configuration: aks-engine
- OS (e.g: `cat /etc/os-release`): windows 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: containerd 1.4.3 or Docker EE 19.03.11

/sig windows
/assign

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Pod log stats for Windows doesn't work.  With this update the stats for log files are included in summary:

http://localhost:8001/api/v1/nodes/2733k8s01000000/proxy/stats/summary (output truncated, two containers 1 with log output, 1 without)
```
 "pods": [
  {
   "podRef": {
    "name": "iis-1809-668c5b9c87-fqqml",
    "namespace": "default",
    "uid": "84ff19a1-f0bb-4ff9-bc0b-b291d0f86818"
   },
   "startTime": "2021-02-19T00:59:15Z",
   "containers": [
    {
     "name": "iis",
     "startTime": "2021-02-19T00:59:16Z",
     "cpu": {
      "time": "2021-02-19T01:14:27Z",
      "usageNanoCores": 4680917,
      "usageCoreNanoSeconds": 16203125000
     },
     "memory": {
      "time": "2021-02-19T01:14:27Z",
      "workingSetBytes": 59080704
     },
     "rootfs": {
      "time": "2021-02-19T01:14:27Z",
      "availableBytes": 7994449920,
      "capacityBytes": 31687962624,
      "usedBytes": 71303168,
      "inodesUsed": 0
     },
     "logs": {
      "time": "2021-02-19T01:14:27Z",
      "availableBytes": 7994449920,
      "capacityBytes": 31687962624,
      "usedBytes": 0,
      "inodesUsed": 0
     }
    }
   ],
  },
  {
   "podRef": {
    "name": "logger-f76f4d988-k5n9m",
    "namespace": "default",
    "uid": "6a3c95d2-27cf-4439-927e-724f069aee89"
   },
   "startTime": "2021-02-19T01:12:34Z",
   "containers": [
    {
     "name": "testwin",
     "startTime": "2021-02-19T01:13:06Z",
     "cpu": {
      "time": "2021-02-19T01:14:27Z",
      "usageNanoCores": 190263476,
      "usageCoreNanoSeconds": 19796875000
     },
     "memory": {
      "time": "2021-02-19T01:14:27Z",
      "workingSetBytes": 66772992
     },
     "rootfs": {
      "time": "2021-02-19T01:14:27Z",
      "availableBytes": 7994449920,
      "capacityBytes": 31687962624,
      "usedBytes": 37748736,
      "inodesUsed": 0
     },
     "logs": {
      "time": "2021-02-19T01:14:27Z",
      "availableBytes": 7994449920,
      "capacityBytes": 31687962624,
      "usedBytes": 172746066,
      "inodesUsed": 0
     }
    }
```

#### Which issue(s) this PR fixes:

Fixes #99173

#### Does this PR introduce a user-facing change?

```release-note
Pod Log stats for windows now reports metrics
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsturtevant** [comment]
Reviewing the logs I am also finding the following error which is also related to the changes with the `host_stats_provider`

```
E0218 23:30:13.293729    4360 cri_stats_provider.go:407] unable to fetch pod etc hosts stats: failed to get stats CreateFile \var\lib\kubelet\pods\830b35a0-d8f3-421f-afc7-2861ace4ff20/etc-hosts: The system cannot find the file specified.
```

/etc/hosts file isn't used in windows: https://github.com/kubernetes/kubernetes/blob/f49385d05a38d0dec06be6a324fb4fe3a720f4db/pkg/kubelet/kubelet_pods.go#L144-L150

pushing a fix for this as well

**Comment by jingxu97** [comment]
is that possible to add a test for it?

**Comment by jsturtevant** [comment]
@jingxu97 unit tests for the windows are not run on the builds (https://github.com/kubernetes/kubernetes/issues/51540).  I looked and the https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/fs/fs_windows_test.go is actually running on linux  (there is no build tag for windows) and doesn't tests windows functionality :-( 


I did find a windows stats tests and added a test case to the sanity checks:

```
 k get nodes        
NAME                    STATUS   ROLES    AGE   VERSION
4120k8s000              Ready    agent    20h   v1.21.0-alpha.3.326+fcda55e7cb1491-dirty

{"msg":"PASSED [sig-windows] [Feature:Windows] Kubelet-Stats [Serial] Kubelet stats collection for Windows nodes when running 10 pods should return within 10 seconds","total":1,"completed":1,"skipped":653,"failed":0}
```

```

**Review by aravindhp — COMMENTED** [review]
Thanks for working on this, @jsturtevant 

/lgtm

**Comment by BenTheElder** [comment]
>  is actually running on linux (there is no build tag for windows) and doesn't tests windows functionality :-(

Windows definitely has a build tag. Do you mean that the file is missing a build constraint comment?
We should probably fix this.

**Comment by jsturtevant** [comment]
@BenTheElder   Yes I meant the file is missing the build constraint.  I've opened https://github.com/kubernetes/kubernetes/issues/99409 to track fixing it

**Comment by liggitt** [comment]
commented in https://github.com/kubernetes/kubernetes/issues/99409, but `_windows_test.go` is *supposed* to have an implicit windows build constraint

**Comment by jsturtevant** [comment]
@jingxu97 I've added a check in the end to end test and opened https://github.com/kubernetes/kubernetes/pull/99474 to fix the unit tests.  Would you perfer me to pull in the fixes from #99474 into this PR and add a unit tests for file path dir check?

This makes the kubelet logs really noisy for Windows so would like to get this in for 1.21

File: pkg/kubelet/stats/host_stats_provider.go [hunk 1]
```diff
@@ -79,6 +80,11 @@ func (h hostStatsProvider) getPodContainerLogStats(podNamespace, podName string,
 
 // getPodEtcHostsStats gets status for pod etc hosts usage
 func (h hostStatsProvider) getPodEtcHostsStats(podUID types.UID, rootFsInfo *cadvisorapiv2.FsInfo) (*statsapi.FsStats, error) {
+	if runtime.GOOS == "windows" {
+		// /etc/hosts file is not mounted for windows
```
Comment (marosset) [inline pkg/kubelet/stats/host_stats_provider.go:84]: This reminded me that we should probably get https://github.com/kubernetes/kubernetes/pull/83730 merged.
That PR adds support for /etc/hosts mapping for non dockershim configurations on Windows.

Comment (jsturtevant) [reply pkg/kubelet/stats/host_stats_provider.go:84]: Is there a way to determine if that functionality is enabled and we should add an additional check here?

Comment (marosset) [reply pkg/kubelet/stats/host_stats_provider.go:84]: 83730 added a method to check if the node supports /etc/hosts mapping (`supportsSingleFileMapping := kl.containerRuntime.SupportsSingleFileMapping()`) you could use the same function here.

Comment (jsturtevant) [reply pkg/kubelet/stats/host_stats_provider.go]: I've updated this to included support for containerd on windows.

**Comment by jsturtevant** [comment]
Added support for etc hosts file on windows now that #83730 merged and added more tests.  

/cc @jingxu97

**Comment by erismaster** [comment]
Hi 👋 Bug Triage here, just a reminder that code freeze is end of day, tomorrow the 9th! PRs need to be merged in before then, or they will require an approved exception to go into the 1.21 milestone.

**Comment by jsturtevant** [comment]
The flakes for tests `pull-kubernetes-e2e-azure-file-windows-containerd` and `/test pull-kubernetes-e2e-azure-disk-windows`  should be resolved by #95018

File: pkg/kubelet/stats/host_stats_provider.go [hunk 2]
```diff
@@ -30,7 +30,7 @@ import (
 )
 
 // PodEtcHostsPathFunc is a function to fetch a etc hosts path by pod uid.
```
Comment (marosset) [inline pkg/kubelet/stats/host_stats_provider.go:32]: Can you update the comment to reflect the new return value to clarify usage?

**Comment by jsturtevant** [comment]
Without these updates the kubelet logs for Windows are really noisy with error messages.  Hope we can get it in for into the release. Thanks!

/assign @jingxu97 @dashpole @saad-ali @ehashman

**Comment by dchen1107** [comment]
@saad-ali will take a look soon. Thanks!

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by jsturtevant** [comment]
Thanks @saad-ali @jingxu97 

@dchen1107  it looks like we need an approval from Kubelet owners as well.  Would you be able to take a quick look?

**Comment by jsturtevant** [comment]
`pull-kubernetes-e2e-aks-engine-azure-windows` is a known test issue with an open fix: https://github.com/kubernetes/kubernetes/pull/99860

looks like `pull-kubernetes-integration` is unrealted and has flake open: https://github.com/kubernetes/kubernetes/issues/98606
/test pull-kubernetes-integration
