### PR TITLE
Disable localhost:nodeport for proxy-mode=ipvs

### LINKED ISSUE #96879: Ipvs: NodePort entries for localhost (127.0.0.1, ::1) are created but can't be used
**What happened**:

For services with type NodePort (and LoadBalancer) ipvs entries for localhost (ipv4 and ipv6) are created. Here is an example for a service with `ipFamilyPolicy: PreferDualStack` so the same nodeport is used for ipv4 and ipv6;

```
$ ipvsadm -Ln | grep 31201
TCP  192.168.0.2:31201 rr
TCP  192.168.1.2:31201 rr
TCP  11.0.2.1:31201 rr
TCP  127.0.0.1:31201 rr
TCP  [::1]:31201 rr
TCP  [1000::1:c0a8:2]:31201 rr
TCP  [1000::1:c0a8:102]:31201 rr
TCP  [1100::201]:31201 rr
$ curl -s -D - http://192.168.1.2:31201 | grep -F "200 OK"
HTTP/1.1 200 OK
$ curl -s -D - http://127.0.0.1:31201
(hangs)
$ curl -s -D - http://[1000::1:c0a8:102]:31201 | grep -F "200 OK"
HTTP/1.1 200 OK
$ curl -s -D - http://[::1]:31201
(hangs)
```

The localhost entries can't be used and most likely they never will.

**What you expected to happen**:

Since "::1" most likely will never work and 127.0.0.1 will not work without an unlikely Linux kernel update these entries must not be created.

Further, since the use of localhost addresses for nodeports is the only know reason to require `net.ipv4.conf.all.route_localnet=1` (#90259), this requirement shall be removed for proxy-mode=ipvs.

**How to reproduce it (as minimally and precisely as possible)**:

* Start a cluster with proxy-mode=ipvs and some services
* Do; `ipvsadm -Ln | grep 127.0.0.1`

**Anything else we need to know?**:

That ipv6 access to [::1]:nodeport does not work (and most likely never will) is discussed in https://github.com/kubernetes/kubernetes/issues/90236.

For 127.0.0.1 is is a bit more complicated as discussed in https://github.com/kubernetes/kubernetes/issues/67730, with the excellent deep-dive into the kernel by @chendotjs in https://github.com/kubernetes/kubernetes/issues/67730#issuecomment-578859752.

This may seem like a minor issue but clean-up of useless things is always good. I also have (vague) plans to propose improvements for the address handling for proxy-mode=ipvs and the localhost entries becomes an unwanted problem.

If this issue is accepted as a bug I'll be happy to do a PR.

**Environment**:

- Kubernetes version (use `kubectl version`): all supporting proxy-mode=ipvs
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Install tools: none
- Network plugin and version (if this is a network-related bug): any
- Others:

/kind cleanup
/sig network
/area ipvs

### PR DESCRIPTION
**Pull request by uablrek**
This will never work for ipv6 and not for ipv4 without an unlikely kernel modification.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Described in #96879

#### Which issue(s) this PR fixes:

Fixes #96879

#### Special notes for your reviewer:

localhost:nodeport has never worked for proxy-mode=ipvs.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

File: pkg/proxy/ipvs/netlink_linux.go [hunk 1]
```diff
@@ -182,6 +182,9 @@ func (h *netlinkHandle) GetLocalAddresses(dev, filterDev string) (sets.String, e
 		if route.LinkIndex == filterLinkIndex {
 			continue
 		}
+		if route.Dst.IP.IsLoopback() {
+			continue
```
Comment (aojea) [inline pkg/proxy/ipvs/netlink_linux.go:186]: do you want to log something?
like "loopback addresses no supported for nodeports on ipvs mode"
?

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:186]: No, not really. There is no good place to log something since this is not a configuration.

Perhaps for nodePortAddresses settings, but nah... we set nodePortAddresses to loopback to avoid exposing nodePorts on port scans, and that is still a valid use-case I would say. No need for logging.

Comment (aojea) [reply pkg/proxy/ipvs/netlink_linux.go:186]: IMHO semantically `GetLocalAddresses()` is correct returning the loopback .

shouldn't be better to filter the loopback in the proxier.go code ? it is only used in 2 places.
You can do it here
https://github.com/kubernetes/kubernetes/blob/57459ebd3e56eb0747e4697422e8ac24f7d113c6/pkg/proxy/ipvs/proxier.go#L304-L314

the other place that is being used is 
https://github.com/kubernetes/kubernetes/blob/57459ebd3e56eb0747e4697422e8ac24f7d113c6/pkg/proxy/ipvs/proxier.go#L317-L320
not familiar with Bind but seems legit to bind to loopbacks

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go:186]: Good point :+1:  I will fix that (and squash the commits at the same time).

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -1131,14 +1131,18 @@ func (proxier *Proxier) syncProxyRules() {
 		} else {
 			nodeAddresses = nodeAddrSet.List()
 			for _, address := range nodeAddresses {
+				a := net.ParseIP(address)
+				if a.IsLoopback() {
+					continue
+				}
```
Comment (aojea) [inline pkg/proxy/ipvs/proxier.go:1137]: Should we reject the loopbacks in validation too? or is excessive? `proxier.nodePortAddresses`
https://github.com/kubernetes/kubernetes/blob/57459ebd3e56eb0747e4697422e8ac24f7d113c6/pkg/proxy/apis/config/validation/validation.go#L107

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:1137]: No, it is a valid use-case now (that we are using), and it is still necessary for proxy-mode=iptables. The reason for adding loopback in NodePortAddresses is to limit/disable nodeports, not that anybody _wants_ to use loopback for nodeport. I think have different validations for different proxy-modes must be avoided.

File: pkg/proxy/ipvs/netlink_linux.go (hunk 1 above)
Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: Update pushed. Thanks for spotting this :+1:  It exposed a mistake that I updated only `netlink_linux.go`. Now I had to update the unit-tests which I was suprised that I didn't have to do before.

Comment (uablrek) [reply pkg/proxy/ipvs/netlink_linux.go]: I have also changed the comment to "Disable loopback:nodeport for proxy-mode=ipvs" which is better than "localhost:nodeport" which is not exactly the same.

**Comment by uablrek** [comment]
@aojea Do you think the failing `pull-kubernetes-e2e-gci-gce-ipvs` test is caused by this PR?

I can't really see myself but a possible reason may be som white-box test that actually make `ipvsadm -Ln` and checks for the loopback address.

**Comment by aojea** [comment]
> @aojea Do you think the failing `pull-kubernetes-e2e-gci-gce-ipvs` test is caused by this PR?

doesn't seem related

File: pkg/proxy/ipvs/proxier.go [hunk 3]
```diff
@@ -309,7 +309,11 @@ func (r *realIPGetter) NodeIPs() (ips []net.IP, err error) {
 	}
 	// translate ip string to IP
 	for _, ipStr := range nodeAddress.UnsortedList() {
-		ips = append(ips, net.ParseIP(ipStr))
+		a := net.ParseIP(ipStr)
+		if a.IsLoopback() {
+			continue
+		}
+		ips = append(ips, a)
```
Comment (JornShen) [inline pkg/proxy/ipvs/proxier.go:316]: we should also modify the comment of this func correspondingly,.
https://github.com/kubernetes/kubernetes/blob/8edda782f30a377afd031d5d7f4d62551785c441/pkg/proxy/ipvs/proxier.go#L303

Comment (uablrek) [reply pkg/proxy/ipvs/proxier.go:317]: Comment updated.

**Comment by aojea** [comment]
/retest
This should be approved now that Lars is in the owners file

**Review by thockin — COMMENTED** [review]
/lgtm
/approve
