### PR TITLE
Examples/rethinkdb fixes - namespaces, api update, curl params

### LINKED ISSUE #10744: RethinkDB images & configs (examples/rethinkdb) have hardcoded namespace

### PR DESCRIPTION
**Pull request by mwielgus**
- Removes the hardcoded namespace and allows to create RethinkDB in any namespace. Readme.md uses the default one (no context switching). 
- Namespace is passed to pod through downward api
- Fixes IP -> ip change in API
- Adds ca/bearer based on #8843
- Uses images from gcr.io/google_containers (to be created once you preLGTM the PR)
- Fixes #10744

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @lavalamp @gmarek

File: examples/rethinkdb/image/run.sh [hunk 1]
```diff
@@ -16,14 +16,21 @@
...
-  URL="${KUBERNETES_RO_SERVICE_HOST}/api/v1/namespaces/${NAMESPACE}/endpoints/rethinkdb-driver"
-  IP=$(curl -s ${URL} | jq -s -r --arg h "${MYHOST}" '.[0].subsets | .[].addresses | [ .[].IP ] | map(select(. != $h)) | .[0]') || exit 1
+  echo My host: ${MYHOST}
+
+  URL="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/namespaces/${POD_NAMESPACE}/endpoints/rethinkdb-driver"
+  echo "Endpont url: ${URL}"
+  echo "Looking for IPs..."
+  token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)  
+  # try to pick up first different ip from endpoints
+  IP=$(curl -s ${URL} --insecure --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt --header "Authorization: Bearer ${token}" \
```
Comment (lavalamp) [inline examples/rethinkdb/image/run.sh]: Can you remove the --insecure? Feel free to steal from my PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/8843/files#diff-73babbf5a99d61668cc5b4fd5babf2faR29

File: examples/rethinkdb/admin-pod.yaml [hunk 2]
```diff
@@ -4,12 +4,16 @@ metadata:
   labels:
     db: rethinkdb
     role: admin
-  name: rethinkdb-admin-1.16.0
-  namespace: rethinkdb
+  name: rethinkdb-admin
 spec:
   containers:
-  - image: antmanler/rethinkdb:1.16.0
+  - image: gcr.io/google_containers/rethinkdb
```
Comment (lavalamp) [inline examples/rethinkdb/admin-pod.yaml]: Please use a version tag.

File: examples/rethinkdb/rc.yaml [hunk 3]
```diff
@@ -17,8 +16,13 @@ spec:
         role: replicas
     spec:
       containers:
-      - image: antmanler/rethinkdb:1.16.0
+      - image: gcr.io/google_containes/rethinkdb
```
Comment (lavalamp) [inline examples/rethinkdb/rc.yaml]: Version tag, please.

File: examples/rethinkdb/image/run.sh (hunk 1 above)
Comment (gmarek) [inline examples/rethinkdb/image/run.sh]: I think Marcin tried it and it didn't work for some reason.

File: examples/rethinkdb/admin-pod.yaml (hunk 2 above)
Comment (mwielgus) [inline examples/rethinkdb/admin-pod.yaml]: Added

File: examples/rethinkdb/rc.yaml (hunk 3 above)
Comment (mwielgus) [inline examples/rethinkdb/rc.yaml]: Added

File: examples/rethinkdb/image/run.sh (hunk 1 above)
Comment (mwielgus) [inline examples/rethinkdb/image/run.sh]: Yep, I actually stole this line from you and tried it but unfortunately I was getting empty output without --insecure.

Comment (lavalamp) [inline examples/rethinkdb/image/run.sh]: It worked for me--I tested it--so can you give it another shot?

Comment (mwielgus) [inline examples/rethinkdb/image/run.sh]: Client Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-453-gf2adea25276de8-dirty", GitCommit:"f2adea25276de84232c2a9ea9ef8821a3d3753e9", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-453-gf2adea25276de8-dirty", GitCommit:"f2adea25276de84232c2a9ea9ef8821a3d3753e9", GitTreeState:"dirty"}

Checking for other nodes
My host: 10.245.1.7
Endpont url: https://10.0.0.1:443/api/v1/namespaces/default/endpoints/rethinkdb-driver
Looking for IPs...
jq: error: Cannot iterate over null

Comment (mwielgus) [inline examples/rethinkdb/image/run.sh]: @lavalamp  I also tried using your images, with the same result (on GCE).

Comment (lavalamp) [inline examples/rethinkdb/image/run.sh]: Did you start the admin service/rc first? You need to start that first.

Comment (mwielgus) [inline examples/rethinkdb/image/run.sh]: Well I did, but apparently I lost it while fighting with the startup script. Now I did everything once more and everything was in order. Removed --insecure. Sorry for confusion.

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
@davidopp for ok-to-merge. It's just an example, I think it should be fine.

**Comment by davidopp** [comment]
LGTM
