### PR TITLE
Fixing spark e2e test failures.

### LINKED ISSUE #36102: [k8s.io] [Feature:Example] [k8s.io] Spark should start spark master, driver and workers {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17028

Failed: [k8s.io] [Feature:Example] [k8s.io] Spark should start spark master, driver and workers 6.17s

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:205
Expected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.133.46 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-hg287] []  <nil>  error: the namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-hg287\". You must pass '--namespace=spark-cluster' to perform this operation.\n [] <nil> 0xc42013e570 exit status 1 <nil> <nil> true [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564e0 0xc420656500] [0x932a70 0x932a70] 0xc420d10e40 <nil>}:\nCommand stdout:\n\nstderr:\nerror: the namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-hg287\". You must pass '--namespace=spark-cluster' to perform this operation.\n\nerror:\nexit status 1\n",
        },
        Code: 1,
    }
    error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.133.46 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-hg287] []  <nil>  error: the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-hg287". You must pass '--namespace=spark-cluster' to perform this operation.
     [] <nil> 0xc42013e570 exit status 1 <nil> <nil> true [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564d0 0xc4206564e8 0xc420656518] [0xc4206564e0 0xc420656500] [0x932a70 0x932a70] 0xc420d10e40 <nil>}:
    Command stdout:
    
    stderr:
    error: the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-hg287". You must pass '--namespace=spark-cluster' to perform this operation.
    
    error:
    exit status 1
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2066
```

This test has been consistently failing for a long time
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17027
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17026
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17024
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/17028

### PR DESCRIPTION
**Pull request by foxish**
**What this PR does / why we need it**: Fixes e2e test failures in the spark tests. These failures were caused by an update to the examples in https://github.com/kubernetes/kubernetes/pull/33604

**Which issue this PR fixes** : fixes https://github.com/kubernetes/kubernetes/issues/36102

**Release note**:
```release-note
NONE
```

cc @calebamiles @elsonrodriguez @saad-ali 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36548)

### CODE REVIEW

**Comment by foxish** [comment]
@jimmycuadra @elsonrodriguez PTAL

**Comment by foxish** [comment]
@k8s-bot cvm gke e2e test this

**Comment by jimmycuadra** [comment]
Did you mean to assign me on this one? I don't have any context for this code.

**Comment by foxish** [comment]
@k8s-bot kubemark e2e test this

**Comment by foxish** [comment]
@jimmycuadra Unassigned. I assigned you as you dealt with the e2e tests for cassandra recently.

**Comment by jimmycuadra** [comment]
Ah. That was just a follow up to a previous PR I made finishing some of the petset rename stuff.

**Comment by elsonrodriguez** [comment]
@foxish looks good, but next time don't shy away from asking for an example fix if it makes sense.

**Comment by foxish** [comment]
@elsonrodriguez I felt that the way the examples are written right now makes sense, with the namespace. Perhaps we could have kept the namespace from the example YAMLs, and just changed the instructions to specify `--namespace=` with each kubectl command. I'm not sure which I prefer.

File: test/e2e/examples.go [hunk 1]
```diff
@@ -142,39 +142,61 @@ var _ = framework.KubeDescribe("[Feature:Example]", func() {
 	})
 
 	framework.KubeDescribe("Spark", func() {
+		nsSpark := "spark-cluster" // TODO: find a way to infer this from the yaml.
+		AfterEach(func() {
+			// clean up the spark namespace.
+			err := c.Core().Namespaces().Delete(nsSpark, nil)
```
Comment (chrislovecnm) [inline test/e2e/examples.go]: We just throwing a pain here if the build framework is borked?

File: test/e2e/examples.go [hunk 2]
```diff
@@ -142,39 +142,61 @@ var _ = framework.KubeDescribe("[Feature:Example]", func() {
...
 			mkpath := func(file string) string {
 				return filepath.Join(framework.TestContext.RepoRoot, "examples/spark", file)
 			}
-
 			// TODO: Add Zepplin and Web UI to this example.
 			serviceYaml := mkpath("spark-master-service.yaml")
 			masterYaml := mkpath("spark-master-controller.yaml")
 			workerControllerYaml := mkpath("spark-worker-controller.yaml")
-			nsFlag := fmt.Sprintf("--namespace=%v", ns)
+			nsYaml := mkpath("namespace-spark-cluster.yaml")
```
Comment (chrislovecnm) [inline test/e2e/examples.go]: Can we check that this file exists.  This bit me in a C* e2e test.

**Review by chrislovecnm — CHANGES_REQUESTED** [review]
A couple of recommendation.  Thank for addressing this!!

**Comment by janetkuo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e/examples.go, line 145 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548#-KWJgiwbCljhvdoi81UV:-KWJgiwbCljhvdoi81UW:b-wx87ll) ([raw file](https://github.com/kubernetes/kubernetes/blob/81dde54c17f88484c44eeb1da03d45f62e2ab2f3/test/e2e/examples.go#L145)):*
> ```Go
> 
> 	framework.KubeDescribe("Spark", func() {
> 		nsSpark := "spark-cluster" // TODO: find a way to infer this from the yaml.
> ```

Can we just remove the namespace in all spark yaml files? In the examples, the namespace is already set to `spark-cluster`, therefore, specifying namespace in the yaml isn't necessary. Plus the namespace used in test should be unique.

---

*[test/e2e/examples.go, line 148 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548#-KWJiy-AQ3ZDPAJZ12WS:-KWJiy-AQ3ZDPAJZ12WT:bnouga) ([raw file](https://github.com/kubernetes/kubernetes/blob/81dde54c17f88484c44eeb1da03d45f62e2ab2f3/test/e2e/examples.go#L148)):*
> ```Go
> 		AfterEach(func() {
> 			// clean up the spark namespace.
> 			err := c.Core().Namespaces().Delete(nsSpark, nil)
> ```

Need to change this if removing nsSpark

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36548)*

**Comment by foxish** [comment]
@janetkuo I misunderstood how the example worked. You're right, this change would be unnecessary; and removing the `namespace` from the example YAMLs should suffice. Will update. Thanks!

**Comment by foxish** [comment]
@janetkuo PTAL. Updated.

File: test/e2e/examples.go (hunk 1 above)
Comment (chrislovecnm) [inline test/e2e/examples.go]: Panic not pain ...
