### PR TITLE
fix(scheduler): fix incorrect loop logic in MultiPoint to avoid a plugin being loaded multiple times

### LINKED ISSUE #122066: Scheduler's default plugin returns an invalid score that is not in the range of [0, 100], resulting in no Pods being scheduled
### What happened?

Scheduler's default plugin returns an invalid score that is not in the range of [0, 100], resulting in no Pods being scheduled:
```
E1127 19:48:13.221979   66549 schedule_one.go:130] "Error selecting node for pod" err="applying score defaultWeights on Score plugins: plugin \"PodTopologySpread\" returns an invalid score 300, it should in the range of [0, 100] after normalizing" pod="default/test-multi-point-xxxxxxxx"
```

After investigation, I found that there was a bug in the code that built the framework when the scheduler started. When using the plugins declared in the regular extension point to override the plugins declared in the MultiPoint, the traversed variable `enabledSet` will be modified in the following loop:
https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/scheduler/framework/runtime/framework.go#L523-L534

This may cause **a same scoring plugin** (e.g. `PodTopologySpread`) **to be loaded multiple times**:
```
f.scorePlugins: []framework.ScorePlugin{(*noderesources.Fit)(0xc000922e10), (*podtopologyspread.PodTopologySpread)(0xc0000ab100), (*podtopologyspread.PodTopologySpread)(0xc0000ab100), (*tainttoleration.TaintToleration)(0xc0003f3690), (*nodeaffinity.NodeAffinity)(0xc0003997a0), (*volumebinding.VolumeBinding)(0xc0003db7a0), (*interpodaffinity.InterPodAffinity)(0xc00038f3b0), (*noderesources.BalancedAllocation)(0xc000063680), (*imagelocality.ImageLocality)(0xc000b45320)}
```

Further, this results in **a node being processed multiple times by a plugin's** (e.g. `PodTopologySpread`'s) **`NormalizeScore` method**, resulting in an invalid score that is not in the range of [0, 100]:
https://github.com/kubernetes/kubernetes/blob/ad9b60e2c9ddb21e8b00cabbe27e639638a0ea88/pkg/scheduler/framework/runtime/framework.go#L1095-L1108

### What did you expect to happen?

If the scheduler's MultiPoint feature is used (by the default plugins or by ) 

If the scheduler's MultiPoint feature is used (either through the default plugin or through manual configuration), and the configuration (e.g. the scoring weight) of a certain plugin is overridden in a regular extension point, the plugin will only be loaded once in this extension point, and no illegal scores will be returned.

### How can we reproduce it (as minimally and precisely as possible)?

An example KubeSchedulerConfiguration:

```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta3
...
profiles:
- schedulerName: default-scheduler
  plugins:
    score:
      enabled:
      - name: PodTopologySpread
        weight: 3
...
```

### Anything else we need to know?

_No response_

### Kubernetes version

K8s v1.24.15 or higher

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by caohe**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fix incorrect loop logic in MultiPoint to avoid a plugin being loaded multiple times.

#### Which issue(s) this PR fixes:

Fixes #122066 

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression since 1.24 in the scheduling framework when overriding MultiPoint plugins (e.g. default plugins).
The incorrect loop logic might lead to a plugin being loaded multiple times, consequently preventing any Pod from being scheduled, which is unexpected.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lianghao208** [comment]
Can you add a test case to cover this corner case?

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -526,11 +526,9 @@ func (f *frameworkImpl) expandMultiPointPlugins(logger klog.Logger, profile *con
 		// - part 3: other plugins (excluded by part 1 & 2) in regular extension point.
 		newPlugins := reflect.New(reflect.TypeOf(e.slicePtr).Elem()).Elem()
 		// part 1
-		for _, name := range enabledSet.list {
```
Comment (lianghao208) [inline pkg/scheduler/framework/runtime/framework.go:529]: cc @Huang-Wei 
Any purpose of iterating through enabledSet instead of overrodePlugins in #108613?

**Comment by AxeZhan** [comment]
Can we add a UT for this fix? Reduce the occurrence of similar incidents in the future.

File: pkg/scheduler/framework/runtime/framework.go (hunk 1 above)
Comment (NoicFank) [reply pkg/scheduler/framework/runtime/framework.go:529]: Traversing `enabledSet` instead of `overridePlugins` directly is to allow the plugins in `overridePlugins` to maintain their original order in `enabledSet` when they were added to the `newPlugins`.

Comment (caohe) [reply pkg/scheduler/framework/runtime/framework.go:529]: Thanks for your information. I think it would be better to iterate over a copy of `enabledSet` than iterate over `overridePlugins`. After testing, this method can also solve the problem of plugins being loaded multiple times.

Comment (lianghao208) [reply pkg/scheduler/framework/runtime/framework.go:529]: @caohe we still need a unit test to cover this, can you add a test case in `pkg/scheduler/framework/runtime/framework_test.go#TestNewFrameworkMultiPointExpansion`? After addint a test case, we are able to make sure this bug can be reproduced and fixed.

Comment (caohe) [reply pkg/scheduler/framework/runtime/framework.go:529]: Yes, I'm doing this.

**Comment by caohe** [comment]
@lianghao208 @AxeZhan Hello, I have added a test case named `Override_MultiPoint_plugins_weights_and_avoid_a_plugin_being_loaded_multiple_times`.

Before this fix, it will fail:
```
=== RUN   TestNewFrameworkMultiPointExpansion/Override_MultiPoint_plugins_weights_and_avoid_a_plugin_being_loaded_multiple_times
    framework.go:509: I1129 17:24:29.029130] MultiPoint plugin is explicitly re-configured; overriding plugin="test-plugin"
    framework.go:509: I1129 17:24:29.029173] MultiPoint plugin is explicitly re-configured; overriding plugin="score-plugin-1"
    framework_test.go:899: Unexpected eventToPlugin map (-want,+got):  &config.Plugins{
          	... // 4 identical fields
          	PostFilter: {Enabled: {{Name: "test-plugin"}}},
          	PreScore:   {Enabled: {{Name: "test-plugin"}, {Name: "score-plugin-1"}}},
          	Score: config.PluginSet{
          		Enabled: []config.Plugin{
          			{Name: "score-plugin-1", Weight: 5},
          			{Name: "test-plugin", Weight: 3},
        + 			{Name: "test-plugin", Weight: 3},
          			{Name: "score-plugin-2", Weight: 5},
          		},
          		Disabled: nil,
          	},
          	Reserve: {Enabled: {{Name: "test-plugin"}}},
          	Permit:  {Enabled: {{Name: "test-plugin"}}},
          	... // 4 identical fields
          }
--- FAIL: TestNewFrameworkMultiPointExpansion (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/plugin_expansion (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_MultiPoint_plugin_at_some_extension_points (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Multiple_MultiPoint_plugins (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_MultiPoint_extension (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Reorder_MultiPoint_plugins_(specified_extension_takes_precedence) (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Reorder_MultiPoint_plugins_(specified_extension_only_takes_precedence_when_it_exists_in_MultiPoint) (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Override_MultiPoint_plugins_weights (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_and_enable_MultiPoint_plugins_with_'*' (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_and_enable_MultiPoint_plugin_by_name (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Expect_'already_registered'_error (0.00s)
    --- FAIL: TestNewFrameworkMultiPointExpansion/Override_MultiPoint_plugins_weights_and_avoid_a_plugin_being_loaded_multiple_times (0.00s)
```
Also, I have printed the got and want results:
```
tc.wantPlugins.Score: config.PluginSet{Enabled:[]config.Plugin{config.Plugin{Name:"score-plugin-1", Weight:5}, config.Plugin{Name:"test-plugin", Weight:3}, config.Plugin{Name:"score-plugin-2", Weight:5}}, Disabled:[]config.Plugin(nil)}
fw.ListPlugins().Score: config.PluginSet{Enabled:[]config.Plugin{config.Plugin{Name:"score-plugin-1", Weight:5}, config.Plugin{Name:"test-plugin", Weight:3}, config.Plugin{Name:"test-plugin", Weight:3}, config.Plugin{Name:"score-plugin-2", Weight:5}}, Disabled:[]config.Plugin(nil)}
```
We can see from the result, `test-plugin` was loaded 2 times.

After this fix, it will pass:
```
--- PASS: TestNewFrameworkMultiPointExpansion (0.01s)
    --- PASS: TestNewFrameworkMultiPointExpansion/plugin_expansion (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_MultiPoint_plugin_at_some_extension_points (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Multiple_MultiPoint_plugins (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_MultiPoint_extension (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Reorder_MultiPoint_plugins_(specified_extension_takes_precedence) (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Reorder_MultiPoint_plugins_(specified_extension_only_takes_precedence_when_it_exists_in_MultiPoint) (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Override_MultiPoint_plugins_weights (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_and_enable_MultiPoint_plugins_with_'*' (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/disable_and_enable_MultiPoint_plugin_by_name (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Expect_'already_registered'_error (0.00s)
    --- PASS: TestNewFrameworkMultiPointExpansion/Override_MultiPoint_plugins_weights_and_avoid_a_plugin_being_loaded_multiple_times (0.00s)
```

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -526,7 +527,7 @@ func (f *frameworkImpl) expandMultiPointPlugins(logger klog.Logger, profile *con
...
+		for _, name := range slice.CopyStrings(enabledSet.list) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/runtime/framework.go:530]: the root cause is that during orderedset.delete(), the length of the list get changed, so some item missed its chance to be iterated in the outer for loop.

The fix can be snapshotting this list in the outer for loop - as you're proposing here. Could you help check if slice.CopyStrings is available in all supported versions 1.25? ~ 1.28? as we want to cherrypick this fix.

Or, another fix is to make the for loop logic accurate w/o copying/snapshotting the list:

```diff
diff --git a/pkg/scheduler/framework/runtime/framework.go b/pkg/scheduler/framework/runtime/framework.go
index 8caa8ec1cb4..f238bcbdfb7 100644
--- a/pkg/scheduler/framework/runtime/framework.go
+++ b/pkg/scheduler/framework/runtime/framework.go
@@ -450,12 +450,10 @@ func (os *orderedSet) has(s string) bool {
 	return found
 }
 
-func (os *orderedSet) delete(s string) {
-	if i, found := os.set[s]; found {
-		delete(os.set, s)
-		os.list = append(os.list[:i-os.deletionCnt], os.list[i+1-os.deletionCnt:]...)
-		os.deletionCnt++
-	}
+func (os *orderedSet) delete(i int) {
+	delete(os.set, os.list[i])
+	os.list = append(os.list[:i], os.list[i+1:]...)
+	os.deletionCnt++
 }
 
 func (f *frameworkImpl) expandMultiPointPlugins(logger klog.Logger, profile *config.KubeSchedulerProfile, pluginsMap map[string]framework.Plugin) error {
@@ -526,10 +524,12 @@ func (f *frameworkImpl) expandMultiPointPlugins(logger klog.Logger, profile *con
 		// - part 3: other plugins (excluded by part 1 & 2) in regular extension point.
 		newPlugins := reflect.New(reflect.TypeOf(e.slicePtr).Elem()).Elem()
 		// part 1
-		for _, name := range enabledSet.list {
+		for i := range enabledSet.list {
+			j := i - enabledSet.deletionCnt
+			name := enabledSet.list[j]
 			if overridePlugins.has(name) {
 				newPlugins = reflect.Append(newPlugins, reflect.ValueOf(pluginsMap[name]))
-				enabledSet.delete(name)
+				enabledSet.delete(j)
 			}
 		}
 		// part 2
```

**Review by Huang-Wei — COMMENTED** [review]
Thanks @caohe a lot for the catch and fix!

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (caohe) [reply pkg/scheduler/framework/runtime/framework.go:530]: Thank you for the detailed explanation! Yes, git blame shows that the code for `slice.CopyStrings` has not been modified in almost 6 years. I have tested this fix on our 1.24 cluster and it works fine.
image

Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:530]: thanks for confirming. Could you help cherrypick it to all supported lower k8s versions?

**Comment by Huang-Wei** [comment]
We may wait until v1.29 release is out. And then cherrypick.

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (caohe) [reply pkg/scheduler/framework/runtime/framework.go:530]: Sure, I will cherrypick it after this PR is merged.

Comment (caohe) [reply pkg/scheduler/framework/runtime/framework.go:530]: Hi, I have cherry-picked it to 1.26-1.29. Could you PTAL?
#122366
#122368
#122370
#122371

**Comment by kerthcet** [comment]
Please also fill the bug info in the cherry-picked PRs. @caohe

**Comment by caohe** [comment]
> Please also fill the bug info in the cherry-picked PRs. @caohe

Thanks, I have added release notes to this PR and the cherry-picked PRs.  cc @kerthcet
