### PR TITLE
kubelet/cm: fix bug where kubelet restarts from missing cpuset cgroup

### LINKED ISSUE #122955: Kubelet - failed to initialize top level QOS containers: root container [kubepods] doesn't exist
### What happened?

Starting the kubelet the first time after a system reboot,  the kubelet fails with:
`E0125 00:20:56.003890    2172 kubelet.go:1466] "Failed to start ContainerManager" err="failed to initialize top level QOS containers: root container [kubepods] doesn't exist"`

Which, sort of is a lie.   The root cause is actually that `cpuset` does not exist in `/sys/fs/cgroup/cgroup.subtree_control` 

After the kubelet exits, systemd restarts in,  and then all is fine after that,  until the next time the OS is restarted.  

I tried to track it down,  create.go does add the cpuset to `cgroup.subtree_control`,  and it remains there until `common.go:setUnitProperties()` is executed,  at which time `cpuset` appears to be disabled and disappears.  The other controllers are unaffected.   On the subsequent kubelet restart, `cpuset` does get added again,  and remains after the call to setUnitProperties().   

### What did you expect to happen?

I would expect the kubelet to start and not exit on all starts of the kubelet. 

### How can we reproduce it (as minimally and precisely as possible)?

The OS I am using is RHEL 9 on s390x.   
1) Boot the OS
2) Start the kubelet (I start with `kubeadm init` or `kubeadm join`.
3) Observer the kubelet starts,  fails, and then restarts.   Subsequent restarts of the kubelet are successful until the OS rebooted. (Likely due to after a reboot, the /sys/fs/cgroups is fresh,  unlike subsequent restarts of the kubelet)

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/s390x"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

RHEL 9 kernel 5.14.0-162.22.2.el9.s390x
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O 1.26.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
on None cpumanager policy, cgroupv2, and systemd cgroup manager, kubelet could get into a situation where it believes the cpuset cgroup was created (by libcontainer in the cgroupfs) but systemd has deleted it, as it wasn't requested to create it. This causes one unnecessary restart, as kubelet fails with

`failed to initialize top level QOS containers: root container [kubepods] doesn't exist.`

This only causes one restart because the kubelet skips recreating the cgroup if it already exists, but it's still a bother and is fixed this way

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/122955

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where the kubelet ephemerally fails with `failed to initialize top level QOS containers: root container [kubepods] doesn't exist`, due to the cpuset cgroup being deleted on v2 with systemd cgroup manager.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/node_container_manager_linux.go [hunk 1]
```diff
@@ -183,9 +187,37 @@ func getCgroupConfig(rl v1.ResourceList) *ResourceConfig {
 	}
 	rc.HugePageLimit = HugePageLimits(rl)
 
+	// In the case of a None policy, cgroupv2 and systemd cgroup manager, we must make sure systemd is aware of the cpuset cgroup.
+	// By default, systemd will not create it, as we've not chosen to delegate it, and we haven't included it in the Apply() request.
+	// However, this causes a bug where kubelet restarts unnecessarily (cpuset cgroup is created in the cgroupfs, but systemd
+	// doesn't know about it and deletes it, and then kubelet doesn't continue because the cgroup isn't configured as expected).
+	// An alternative is to delegate the `cpuset` cgroup to the kubelet, but that would require some plumbing in libcontainer,
```
Comment (kolyshkin) [inline pkg/kubelet/cm/node_container_manager_linux.go:194]: Just curious, what plumbing do you refer to here? IOW what's missing?

File: pkg/kubelet/cm/types.go [hunk 2]
```diff
@@ -19,12 +19,15 @@ package cm
...
 	v1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/types"
+	"k8s.io/utils/cpuset"
 )
 
 // ResourceConfig holds information about all the supported cgroup resource parameters.
 type ResourceConfig struct {
 	// Memory limit (in bytes).
 	Memory *int64
+	// CPU set (number of cpus the cgroup has access to)
```
Comment (kolyshkin) [inline pkg/kubelet/cm/types.go:29]: nit: missing period

File: pkg/kubelet/cm/container_manager_linux.go [hunk 3]
```diff
@@ -131,6 +132,10 @@ type containerManagerImpl struct {
 	topologyManager topologymanager.Manager
 	// Interface for Dynamic Resource Allocation management.
 	draManager dra.Manager
+	// The full set of CPUs on the node. This field is set lazily, and is used to make sure
+	// the `cpuset` cgroup hierarchy is created on cgroup v2 when cpumanager is using a
+	// None policy
```
Comment (kolyshkin) [inline pkg/kubelet/cm/container_manager_linux.go:137]: nit: missing period.

File: pkg/kubelet/cm/node_container_manager_linux.go [hunk 4]
```diff
@@ -183,9 +187,37 @@ func getCgroupConfig(rl v1.ResourceList) *ResourceConfig {
...
+	if err != nil {
+		klog.V(4).InfoS("Failed to get machine info to get default cpuset", "error", err)
+		return cpuset.CPUSet{}
+	}
+	topo, err := topology.Discover(machineInfo)
+	if err != nil {
+		klog.V(4).InfoS("Failed to get topology info to get default cpuset", "error", err)
+		return cpuset.CPUSet{}
+	}
+	return topo.CPUDetails.CPUs()
```
Comment (kolyshkin) [inline pkg/kubelet/cm/node_container_manager_linux.go:218]: A weird idea: what if we just take the contents of `/sys/fs/cgroup/cpuset.cpus.effective`?

File: pkg/kubelet/cm/node_container_manager_linux.go (hunk 1 above)
Comment (haircommander) [reply pkg/kubelet/cm/node_container_manager_linux.go:194]: we currently use libcontainer for all of our cgroup management and there's no way to set a systemd property through the libcontainer manager. we could just use a godbus instance ourselves but it'd take some setup and copied code

File: pkg/kubelet/cm/node_container_manager_linux.go (hunk 4 above)
Comment (haircommander) [reply pkg/kubelet/cm/node_container_manager_linux.go:218]: that's an option. I opted for this because it matches what the cpumanager does to initialize the full set of CPUs, which i figure may be more consistent to have the kubelet gather the cpu list one way. I am open though.

File: pkg/kubelet/cm/node_container_manager_linux.go [hunk 5]
```diff
@@ -183,9 +187,37 @@ func getCgroupConfig(rl v1.ResourceList) *ResourceConfig {
...
+		if cm.allCPUs.IsEmpty() {
+			cm.allCPUs = cm.getAllCPUs()
+		}
+		rc.CPUSet = cm.allCPUs
+	}
+
 	return &rc
 }
 
+func (cm *containerManagerImpl) getAllCPUs() cpuset.CPUSet {
```
Comment (ffromani) [inline pkg/kubelet/cm/node_container_manager_linux.go:207]: just thinking aloud, are we in the container manager flow before the cpumanager is initialized?
I'd like to explore the option to put this logic inside cpumanager, so we can avoid to peek on its options from the outside and to duplicate the topology discovery logic.
Note: I'm _NOT_ suggesting to pivot to this approach in this PR, just exploring (myself) the option to see how it looks.

Comment (ffromani) [reply pkg/kubelet/cm/node_container_manager_linux.go:207]: ok, after a quick check we do have a `cpumanager` instance in the `containerManagerImpl` when we reach this code, so moving the functionality inside `cpumanager` and remove quite some duplication is at least possible.

Comment (ffromani) [reply pkg/kubelet/cm/node_container_manager_linux.go:207]: sketch (utterly untested, for demo purposes only): 
```
diff --git a/pkg/kubelet/cm/cpumanager/cpu_manager.go b/pkg/kubelet/cm/cpumanager/cpu_manager.go
index 8b5049d7d74..e7fb1cdb8aa 100644
--- a/pkg/kubelet/cm/cpumanager/cpu_manager.go
+++ b/pkg/kubelet/cm/cpumanager/cpu_manager.go
@@ -93,6 +93,10 @@ type Manager interface {
 	// GetCPUAffinity returns cpuset which includes cpus from shared pools
 	// as well as exclusively allocated cpus
 	GetCPUAffinity(podUID, containerName string) cpuset.CPUSet
+
+	// GetAllCPUs returns all the CPUs known by cpumanager, as reported by the
+	// hardware discovery. Maps to the CPU capacity.
+	GetAllCPUs() cpuset.CPUSet
 }
 
 type manager struct {
@@ -136,7 +140,11 @@ type manager struct {
 	// stateFileDirectory holds the directory where the state file for checkpoints is held.
 	stateFileDirectory string
 
-	// allocatableCPUs is the set of online CPUs as reported by the system
+	// allCPUs is the set of online CPUs as reported by the system
+	allCPUs cpuset.CPUSet
+
+	// allocatableCPUs is the set of online CPUs as reported by the system,
+	// and available for allocation, minus the reserved set
 	allocatableCPUs cpuset.CPUSet
 
 	// pendingAdmissionPod contain the pod during the admission phase
@@ -156,6 +164,11 @@ func NewManager(cpuPolicyName string, cpuPolicyOptions map[string]string, reconc
 	var policy Policy
 	var err error
 
+	topo, err = topology.Discover(machineInfo)
+	if err != nil {
+		return nil, err
+	}
+
 	switch policyName(cpuPolicyName) {
 
 	case PolicyNone:
@@ -165,10 +178,6 @@ func NewManager(cpuPolicyName string, cpuPolicyOptions map[string]string, reconc
 		}
 
 	case PolicyStatic:
-		topo, err = topology.Discover(machineInfo)
-		if err != nil {
-			return nil, err
-		}
 		klog.InfoS("Detected CPU topology", "topology", topo)
 
 		reservedCPUs, ok := nodeAllocatableReservation[v1.ResourceCPU]
@@ -205,6 +214,7 @@ func NewManager(cpuPolicyName string, cpuPolicyOptions map[string]string, reconc
 		topology:                   topo,
 		nodeAllocatableReservation: nodeAllocatableReservation,
 		stateFileDirectory:         stateFileDirectory,
+		allCPUs:                    topo.CPUDetails().CPUs(),
 	}
 	manager.sourcesReady = &sourcesReadyStub{}
 	return manager, nil
@@ -339,6 +349,10 @@ func (m *manager) GetAllocatableCPUs() cpuset.CPUSet {
 	return m.allocatableCPUs.Clone()
 }
 
+func (m *manager) GetAllCPUs() cpuset.CPUSet {
+	return m.allCPUs.Clone()
+}
+
 type reconciledContainer struct {
 	podName       string
 	containerName string
diff --git a/pkg/kubelet/cm/node_container_manager_linux.go b/pkg/kubelet/cm/node_container_manager_linux.go
index 9c9c91bc6f2..42d5f8939e3 100644
--- a/pkg/kubelet/cm/node_container_manager_linux.go
+++ b/pkg/kubelet/cm/node_container_manager_linux.go
@@ -31,12 +31,9 @@ import (
 	utilfeature "k8s.io/apiserver/pkg/util/feature"
 	"k8s.io/klog/v2"
 	kubefeatures "k8s.io/kubernetes/pkg/features"
-	"k8s.io/kubernetes/pkg/kubelet/cm/cpumanager"
-	"k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/topology"
 	"k8s.io/kubernetes/pkg/kubelet/events"
 	"k8s.io/kubernetes/pkg/kubelet/stats/pidlimit"
 	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
-	"k8s.io/utils/cpuset"
 )
 
 const (
@@ -194,9 +191,10 @@ func (cm *containerManagerImpl) getCgroupConfig(rl v1.ResourceList) *ResourceCon
 	// An alternative is to delegate the `cpuset` cgroup to the kubelet, but that would require some plumbing in libcontainer,
 	// and this is sufficient.
 	// Only do so on None policy, as Static policy will do its own updating of the cpuset.
-	if cm.NodeConfig.CPUManagerPolicy == string(cpumanager.PolicyNone) {
+	// Please see the comment on policy none's GetAllocatableCPUs
+	if cm.cpuManager.GetAllocatableCPUs().IsEmpty() {
 		if cm.allCPUs.IsEmpty() {
-			cm.allCPUs = cm.getAllCPUs()
+			cm.allCPUs = cm.cpuManager.GetAllCPUs()
 		}
 		rc.CPUSet = cm.allCPUs
 	}
@@ -204,20 +202,6 @@ func (cm *containerManagerImpl) getCgroupConfig(rl v1.ResourceList) *ResourceCon
 	return &rc
 }
 
-func (cm *containerManagerImpl) getAllCPUs() cpuset.CPUSet {
-	machineInfo, err := cm.cadvisorInterface.MachineInfo()
-	if err != nil {
-		klog.V(4).InfoS("Failed to get machine info to get default cpuset", "error", err)
-		return cpuset.CPUSet{}
-	}
-	topo, err := topology.Discover(machineInfo)
-	if err != nil {
-		klog.V(4).InfoS("Failed to get topology info to get default cpuset", "error", err)
-		return cpuset.CPUSet{}
-	}
-	return topo.CPUDetails.CPUs()
-}
-
 // GetNodeAllocatableAbsolute returns the absolute value of Node Allocatable which is primarily useful for enforcement.
 // Note that not all resources that are available on the node are included in the returned list of resources.
 // Returns a ResourceList.
```

Comment (haircommander) [reply pkg/kubelet/cm/node_container_manager_linux.go]: yeah this is better I've pushed an adapted version, PTAL

File: pkg/kubelet/cm/types.go [hunk 6]
```diff
@@ -19,12 +19,15 @@ package cm
...
 	v1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/types"
+	"k8s.io/utils/cpuset"
 )
 
 // ResourceConfig holds information about all the supported cgroup resource parameters.
 type ResourceConfig struct {
 	// Memory limit (in bytes).
 	Memory *int64
+	// CPU set (number of cpus the cgroup has access to).
```
Comment (kwilczynski) [inline pkg/kubelet/cm/types.go:29]: Nit.

```suggestion
	// CPU set (number of CPUs the cgroup has access to).
```

For consistency.

Comment (haircommander) [reply pkg/kubelet/cm/types.go]: fixed!

**Comment by mrunalp** [comment]
@ffromani Can you make a pass before I approve?

File: pkg/kubelet/cm/cgroup_manager_linux.go [hunk 7]
```diff
@@ -298,6 +298,9 @@ func (m *cgroupCommon) toResources(resourceConfig *ResourceConfig) *libcontainer
 	if resourceConfig.PidsLimit != nil {
 		resources.PidsLimit = *resourceConfig.PidsLimit
 	}
+	if !resourceConfig.CPUSet.IsEmpty() {
+		resources.CpusetCpus = resourceConfig.CPUSet.String()
+	}
```
Comment (ffromani) [inline pkg/kubelet/cm/cgroup_manager_linux.go:303]: non-blocking question for better understanding: what would be the drawback, if any, in always setting the `CpusetCpus`?
this PR covers the `none` policy flow
the exclusively-allocated CPUs should be wanting to set this value anyway (we do in the hooks IIRC?)
the `static` policy without exclusively allocated CPUs should be not too hard.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 8]
```diff
@@ -339,6 +349,10 @@ func (m *manager) GetAllocatableCPUs() cpuset.CPUSet {
 	return m.allocatableCPUs.Clone()
 }
 
+func (m *manager) GetAllCPUs() cpuset.CPUSet {
+	return m.allCPUs.Clone()
+}
+
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:355]: Thinking aloud (so totally not blocking) we will need some refactoring cleanup about available/allocatable/all/reserved cpusets in the future

**Review by ffromani — COMMENTED** [review]
the implemenation looks reasonnable. Let's make sure we have tests coverage (e2e also) for this change; I'm mostly interested in the non-regression flow for starters.
Few non-blocking questions inside

**Comment by ffromani** [comment]
/retest

the lane failure seems unrelated

File: pkg/kubelet/cm/cgroup_manager_linux.go (hunk 7 above)
Comment (haircommander) [reply pkg/kubelet/cm/cgroup_manager_linux.go:303]: mostly as a very targeted change because I don't immediately know the consequences of setting it in the other cases and I'd rather get the bug fix through

Comment (ffromani) [reply pkg/kubelet/cm/cgroup_manager_linux.go:303]: that's fair and reasonnable, let's keep it this way.

**Comment by ffromani** [comment]
@haircommander LGTM if we have test coverage, I strongly prefer e2e coverage, at least non-regression testing.

**Comment by haircommander** [comment]
hey @ffromani I am struggling to write a test (even a unit) that verifies we can create a cgroup with the cgroup manager and then call Validate() on it and have that succeed. I will spend a bit more time on it but I think the value of this change is high enough that we may want to push through the fix without a test for now. WDYT?

**Comment by ffromani** [comment]
> hey @ffromani I am struggling to write a test (even a unit) that verifies we can create a cgroup with the cgroup manager and then call Validate() on it and have that succeed. I will spend a bit more time on it but I think the value of this change is high enough that we may want to push through the fix without a test for now. WDYT?

I hear you, but how can we check at least non-regression?

**Comment by haircommander** [comment]
I'm gonna carry the second commit here https://github.com/kubernetes/kubernetes/pull/126602 . I am pretty sure it passes on master, which means it doesn't test this situation :cry: I'm about at my wits-end on catching the kubelet restart issue.

**Review by ffromani — COMMENTED** [review]
@haircommander I'd like to try writing a e2e test to cover this flow if you don't mind. I want to try my hardest before to give up because this flow is pretty critical - `policy: none` is AFAIK the default. If I can't converge in a week or so we will re-evaluate.

**Comment by ffromani** [comment]
> @haircommander I'd like to try writing a e2e test to cover this flow if you don't mind. I want to try my hardest before to give up because this flow is pretty critical - `policy: none` is AFAIK the default. If I can't converge in a week or so we will re-evaluate.

contributed the e2e test which @haircommander graciosuly agreed to pick up. From my perspective this is the best we can do testwise, so my concerns are addressed (explained more details in the test proper)

I'll have a final pass before to add my formal LGTM.

**Review by ffromani — COMMENTED** [review]
/lgtm

**Comment by bart0sh** [comment]
/assign @SergeyKanzhelev @mrunalp 
for approval

File: cmd/kubelet/app/server.go [hunk 9]
```diff
@@ -713,6 +713,8 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 		}
 	}
 
+	klog.InfoS("Using cgroup driver", "cgroupDriver", s.CgroupDriver)
```
Comment (SergeyKanzhelev) [inline cmd/kubelet/app/server.go:716]: is `KubeletCgroupDriverFromCRI` enabled, this will be double-logged. Maybe put it in `else` statement or remove it from https://github.com/kubernetes/kubernetes/blob/a7702cb47babcff60518b510293dbb41ba8eab35/cmd/kubelet/app/server.go#L1431

Comment (ffromani) [reply cmd/kubelet/app/server.go:716]: Another option would be bumping to `V(4)` or so. It was added mostly for debugging, it will indeed possibly double logged but exactly once, which should not be a big deal.
But also removing this line entirely is not a big deal at all.

**Comment by SergeyKanzhelev** [comment]
> it believes the cpuset cgroup was created (by libcontainer in the cgroupfs) but systemd has deleted it, as it wasn't requested to create it.

is there any way to differentiate the wrong state and systemd delaying creation? I am not quite familiar with the logic and when systemd will create it. Will there be a possibility of a race condition if we are proceeding instead of keep restarting before it is created?

**Comment by haircommander** [comment]
from my understanding the race happened because we created the cpuset cgroup without telling systemd we were (because there were no cpus in the cpuset), and thus systemd deleted it after it was created. adding the cpuset to the request will cause libcontainer to request systemd create it, and then it won't clobber it.

File: cmd/kubelet/app/server.go (hunk 9 above)
Comment (ffromani) [reply cmd/kubelet/app/server.go:716]: it seems to me the log is still present in the last upload, can we please check again?

Comment (haircommander) [reply cmd/kubelet/app/server.go]: whoops, rebased wrong

**Comment by SergeyKanzhelev** [comment]
@ffromani lgtm?

**Comment by ffromani** [comment]
/lgtm

sorry folks, this feel through the cracks. I think is good as we can make it, I'm happy with the change as-is now.

File: test/e2e_node/node_container_manager_test.go [hunk 10]
```diff
@@ -76,6 +76,82 @@ var _ = SIGDescribe("Node Container Manager", framework.WithSerial(), func() {
...
+					ginkgo.By("Stopping the kubelet")
+					startKubelet := stopKubelet()
+
+					// wait until the kubelet health check will fail
+					gomega.Eventually(ctx, func() bool {
+						return kubeletHealthCheck(kubeletHealthCheckURL)
+					}).WithTimeout(time.Minute).WithPolling(time.Second).Should(gomega.BeFalseBecause("expected kubelet health check to be failed"))
+					ginkgo.By("Stopped the kubelet")
+
+					framework.ExpectNoError(e2enodekubelet.WriteKubeletConfigFile(oldCfg))
```
Comment (SergeyKanzhelev) [inline test/e2e_node/node_container_manager_test.go:110]: is it the right ordering? Should we write file first and then restart? Presumably it will be faster

Comment (SergeyKanzhelev) [reply test/e2e_node/node_container_manager_test.go:110]: I mean you will not need to do separate stop and start and will just do `restartKubelet`.

Comment (SergeyKanzhelev) [reply test/e2e_node/node_container_manager_test.go:110]: We likely not run it as systemd daemon now, but if we will, it also will be more reliable =). But this is hypothetical at this stage

Comment (haircommander) [reply test/e2e_node/node_container_manager_test.go]: ah I see, done

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
