### PR TITLE
fix label selector parser in case no value (or only whitespaces) is specified after the key

### LINKED ISSUE #14622: HTTP 500 errors with some label selectors
When polling a k8s master with

    https://xx.xx.xx.xx/api/v1/namespaces/default/replicationcontrollers?labelSelector=environment%3D

the response is an HTTP 500.  But even if this selector is invalid, it should return a 4xx code instead.

### PR DESCRIPTION
**Pull request by caesarxuchao**
fix #14622.

Now it will return an empty list if one visits

```
https://xx.xx.xx.xx/api/v1/namespaces/default/replicationcontrollers?labelSelector=environment%3D
```

or 3D+ or 3D%20

@bronger @lavalamp @brendandburns

### CODE REVIEW

File: pkg/labels/selector.go [hunk 1]
```diff
@@ -600,7 +600,12 @@ func (p *Parser) parseIdentifiersList() (sets.String, error) {
 // parseExactValue parses the only value for exact match style
 func (p *Parser) parseExactValue() (sets.String, error) {
 	s := sets.NewString()
-	tok, lit := p.consume(Values)
+	tok, lit := p.lookahead(Values)
```
Comment (lavalamp) [inline pkg/labels/selector.go]: Please add a test!

File: pkg/labels/selector.go [hunk 2]
```diff
@@ -600,7 +600,12 @@ func (p *Parser) parseIdentifiersList() (sets.String, error) {
...
+	if tok == EndOfStringToken {
+		s.Insert(lit)
+		return s, nil
+	}
+	tok, lit = p.consume(Values)
```
Comment (lavalamp) [inline pkg/labels/selector.go]: can you not just test the tok this returns? (I don't know how this code works!)

Comment (caesarxuchao) [inline pkg/labels/selector.go]: No. `consume()` will increments the position in the token array. Later this will cause an `index out of range` panic because the EndoOfStringToken is consumed.

File: pkg/labels/selector.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/labels/selector.go]: Test cases added

File: pkg/labels/selector.go [hunk 3]
```diff
@@ -600,7 +600,12 @@ func (p *Parser) parseIdentifiersList() (sets.String, error) {
 // parseExactValue parses the only value for exact match style
 func (p *Parser) parseExactValue() (sets.String, error) {
 	s := sets.NewString()
-	tok, lit := p.consume(Values)
+	tok, lit := p.lookahead(Values)
+	if tok == EndOfStringToken || tok == CommaToken {
```
Comment (caesarxuchao) [inline pkg/labels/selector.go]: I missed the `tok == CommaToken` case at first.

**Comment by lavalamp** [comment]
LGTM
