### PR TITLE
Fixes volume predicate handler for equiv class

### LINKED ISSUE #58797: Revisit invalidation of volume related predicate in equivalence class
**What happened**:

When cleanup the existing equivalence class code. I noticed there may be duplication in handlers of Pod, PV, PVC change.

For now we will invalidate volume related predicates for all nodes on PV  and  PVC add. 

Can we assume that volumes will only be attached to Node during Pod add? So we can just deal with those predicates on Pod add/delete. Don't need to bother PV/PVC at all.

@misterikkit @msau42 Any comments?

**Anything else we need to know?**:

Part of #58222

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by resouer**
**What this PR does / why we need it**:

Per discussion in #58797 , we are missing some predicate handler in factory.go.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58797

Ref #58222

**Special notes for your reviewer**:

Kindly ping @msau42

**Release note**:

```release-note
Fixes volume predicate handler for equiv class
```

### CODE REVIEW

File: pkg/scheduler/factory/factory.go [hunk 1]
```diff
@@ -491,8 +534,6 @@ func (c *configFactory) invalidatePredicatesForPvcUpdate(old, new *v1.Persistent
 		}
 		// The bound volume type may change
 		invalidPredicates.Insert(maxPDVolumeCountPredicateKeys...)
-		// The bound volume's label may change
-		invalidPredicates.Insert("NoVolumeZoneConflict")
```
Comment (resouer) [inline pkg/scheduler/factory/factory.go]: This only happen for PV update

File: pkg/scheduler/factory/factory.go [hunk 2]
```diff
@@ -358,6 +360,47 @@ func (c *configFactory) onPvAdd(obj interface{}) {
...
+			glog.Errorf("cannot convert to *v1.PersistentVolume: %v", old)
+			return
+		}
+		c.invalidatePredicatesForPvUpdate(old, new)
+	}
+}
+
+func (c *configFactory) invalidatePredicatesForPvUpdate(old, new *v1.PersistentVolume) {
+	invalidPredicates := sets.NewString()
+	for k, v := range newPV.Labels {
```
Comment (wgliang) [inline pkg/scheduler/factory/factory.go]: newPV should new.

File: pkg/scheduler/factory/factory.go [hunk 3]
```diff
@@ -358,6 +360,47 @@ func (c *configFactory) onPvAdd(obj interface{}) {
...
+		// If PV update modifies the zone/region labels.
+		if isZoneRegionLabel(k) && !reflect.DeepEqual(v, oldPV.Labels[k]) {
```
Comment (wgliang) [inline pkg/scheduler/factory/factory.go]: old

**Review by wgliang — COMMENTED** [review]
Need fix tests failed.

File: pkg/scheduler/factory/factory.go (hunk 2 above)
Comment (resouer) [reply pkg/scheduler/factory/factory.go]: OH! bad rebase, fixing!

**Comment by resouer** [comment]
@msau42 The bazel test is flaky due to https://github.com/kubernetes/kubernetes/issues/59432

I think you can go ahead to review whenever got time :)

**Comment by resouer** [comment]
cc @kubernetes/sig-scheduling-pr-reviews for final pass

**Comment by resouer** [comment]
@bsalamat for final pass and approve

**Comment by resouer** [comment]
Kindly ping @bsalamat for final pass and approve.

This fix is straightfoward, PTAL :)

File: pkg/scheduler/factory/factory.go [hunk 4]
```diff
@@ -358,6 +360,56 @@ func (c *configFactory) onPvAdd(obj interface{}) {
...
+		c.invalidatePredicatesForPvUpdate(oldPV, newPV)
+	}
+}
+
+func (c *configFactory) invalidatePredicatesForPvUpdate(oldPV, newPV *v1.PersistentVolume) {
+	invalidPredicates := sets.NewString()
+	for k, v := range newPV.Labels {
+		// If PV update modifies the zone/region labels.
+		if isZoneRegionLabel(k) && !reflect.DeepEqual(v, oldPV.Labels[k]) {
+			invalidPredicates.Insert("NoVolumeZoneConflict")
```
Comment (bsalamat) [inline pkg/scheduler/factory/factory.go]: Please use `predicates.NoVolumeZoneConflictPred` instead of the string literal.

**Review by bsalamat — COMMENTED** [review]
Looks generally good to me, but I would like @msau42 to take a look as well.

**Comment by msau42** [comment]
Yup, I already looked at it, thanks!

File: pkg/scheduler/factory/factory.go (hunk 4 above)
Comment (resouer) [reply pkg/scheduler/factory/factory.go]: Yep, and I will also replace all predicate key names to const in this file.
