### PR TITLE
Ensure that the pod has proper phase upon re-initialization

### LINKED ISSUE #127793: [SidecarContainers] Failed to get proper phase after the node reboot
### What happened?

If a pod has an init container with restartPolicy "Always" (sidecar), it may lose the pending phase after the node reboot and start the regular containers before initializing the init containers.

/sig node
/priority important-soon
/kind bug

This is similar to https://github.com/kubernetes/kubernetes/issues/126650, but separated as it only affects the pod with restartable init containers.

### What did you expect to happen?

After the node reboot, the remaining pod should start from the pending phase and run the init containers one by one to initialize.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create and initialize the pod with an init container with "Always" container restart policy.
2. Restart the node.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

xref: #127793

This PR fixes the pod with restartable init containers to have a proper phase after the pod sandbox re-creation.

Currently, the `runtime.PodStatus` cannot retrieve the active container statuses, which are the container statuses associated with the current pod sandbox. This adds the `ActiveContainerStatuses` to `runtime.PodStatus`, allowing it to include the container statuses of the current pod sandbox, and fixes the kubelet to correctly set the pod Phase to `Pending` when no active regular containers are present.

#### Which issue(s) this PR fixes:

Fixes #127793

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue where pods did not correctly have a Pending phase after the node reboot.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/issues/128835
^
The failing test is unrelated to this PR.

**Comment by gjkim42** [comment]
squashed commits with no changes.

**Review by matthyx — APPROVED** [review]
/lgtm

File: pkg/kubelet/container/runtime.go [hunk 1]
```diff
@@ -317,6 +317,8 @@ type PodStatus struct {
 	IPs []string
 	// Status of containers in the pod.
 	ContainerStatuses []*Status
+	// Statuses of containers in the pod by podSandBoxID.
+	ContainerStatusesMap map[string][]*Status
```
Comment (toVersus) [inline pkg/kubelet/container/runtime.go:321]:
```suggestion
	ActiveSandboxContainerStatuses []*Status
```

Container statuses are currently stored as a map for each PodSandbox ID, but it seems like only the statuses tied to the currently active PodSandbox are actually needed. Would it be sufficient to maintain a slice, like `ActiveSandboxContainerStatuses`, that holds just the container statuses tied to the active PodSandbox? As it stands, entries are only added to the map, with no mechanism to remove old ones. This makes me think the map could grow indefinitely each time a Pod Sandbox is recreated.

This is just a rough example, but the idea is something like the following:

```diff
diff --git a/pkg/kubelet/container/helpers.go b/pkg/kubelet/container/helpers.go
index 77f59353cec..87889d6fdef 100644
--- a/pkg/kubelet/container/helpers.go
+++ b/pkg/kubelet/container/helpers.go
@@ -433,7 +433,7 @@ func HasAnyActiveRegularContainerStarted(spec *v1.PodSpec, podStatus *PodStatus)
                containerNames[c.Name] = struct{}{}
        }

-       for _, status := range podStatus.getActiveContainerStatuses() {
+       for _, status := range podStatus.ActiveSandboxContainerStatuses {
                if _, ok := containerNames[status.Name]; !ok {
                        continue
                }
diff --git a/pkg/kubelet/container/runtime.go b/pkg/kubelet/container/runtime.go
index 27f3659b8fb..1f130bd889d 100644
--- a/pkg/kubelet/container/runtime.go
+++ b/pkg/kubelet/container/runtime.go
@@ -319,6 +319,8 @@ type PodStatus struct {
        ContainerStatuses []*Status
        // Statuses of containers in the pod by podSandBoxID.
        ContainerStatusesMap map[string][]*Status
+       // Container statuses in the current active pod sandbox.
+       ActiveSandboxContainerStatuses []*Status
        // Status of the pod sandbox.
        // Only for kuberuntime now, other runtime may keep it nil.
        SandboxStatuses []*runtimeapi.PodSandboxStatus
@@ -425,23 +427,6 @@ func (podStatus *PodStatus) GetRunningContainerStatuses() []*Status {
        return runningContainerStatuses
 }

-func (podStatus *PodStatus) getActiveContainerStatuses() []*Status {
-       if len(podStatus.SandboxStatuses) == 0 {
-               return nil
-       }
-
-       currentSandboxStatus := podStatus.SandboxStatuses[0]
-       if currentSandboxStatus.State != runtimeapi.PodSandboxState_SANDBOX_READY {
-               return nil
-       }
-
-       if podStatus.ContainerStatusesMap == nil {
-               return nil
-       }
-
-       return podStatus.ContainerStatusesMap[currentSandboxStatus.Id]
-}
-
 // Image contains basic information about a container image.
 type Image struct {
        // ID of the image.
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_container.go b/pkg/kubelet/kuberuntime/kuberuntime_container.go
index 44f005a9cf7..10e519e029f 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_container.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_container.go
@@ -577,18 +577,19 @@ func (m *kubeGenericRuntimeManager) convertToKubeContainerStatus(status *runtime
 }

 // getPodContainerStatuses gets all containers' statuses for the pod.
-func (m *kubeGenericRuntimeManager) getPodContainerStatuses(ctx context.Context, uid kubetypes.UID, name, namespace string) ([]*kubecontainer.Status, map[string][]*kubecontainer.Status, error) {
+func (m *kubeGenericRuntimeManager) getPodContainerStatuses(ctx context.Context, uid kubetypes.UID, name, namespace, activePodSandboxID string) ([]*kubecontainer.Status, map[string][]*kubecontainer.Status, []*kubecontainer.Status, error) {
        // Select all containers of the given pod.
        containers, err := m.runtimeService.ListContainers(ctx, &runtimeapi.ContainerFilter{
                LabelSelector: map[string]string{kubelettypes.KubernetesPodUIDLabel: string(uid)},
        })
        if err != nil {
                klog.ErrorS(err, "ListContainers error")
-               return nil, nil, err
+               return nil, nil, nil, err
        }

        statuses := []*kubecontainer.Status{}
        statusesMap := make(map[string][]*kubecontainer.Status)
+       activeSandboxContainerStatuses := []*kubecontainer.Status{}
        // TODO: optimization: set maximum number of containers per container name to examine.
        for _, c := range containers {
                resp, err := m.runtimeService.ContainerStatus(ctx, c.Id, false)
@@ -602,15 +603,18 @@ func (m *kubeGenericRuntimeManager) getPodContainerStatuses(ctx context.Context,
                if err != nil {
                        // Merely log this here; GetPodStatus will actually report the error out.
                        klog.V(4).InfoS("ContainerStatus return error", "containerID", c.Id, "err", err)
-                       return nil, nil, err
+                       return nil, nil, nil, err
                }
                status := resp.GetStatus()
                if status == nil {
-                       return nil, nil, remote.ErrContainerStatusNil
+                       return nil, nil, nil, remote.ErrContainerStatusNil
                }
                cStatus := m.convertToKubeContainerStatus(status)
                statuses = append(statuses, cStatus)
                statusesMap[c.PodSandboxId] = append(statusesMap[c.PodSandboxId], cStatus)
+               if c.PodSandboxId == activePodSandboxID {
+                       activeSandboxContainerStatuses = append(activeSandboxContainerStatuses, cStatus)
+               }
        }

        sort.Sort(containerStatusByCreated(statuses))
@@ -618,7 +622,7 @@ func (m *kubeGenericRuntimeManager) getPodContainerStatuses(ctx context.Context,
                sort.Sort(containerStatusByCreated(statuses))

        }
-       return statuses, statusesMap, nil
+       return statuses, statusesMap, activeSandboxContainerStatuses, nil
 }

 func toKubeContainerStatus(status *runtimeapi.ContainerStatus, runtimeName string) *kubecontainer.Status {
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_container_test.go b/pkg/kubelet/kuberuntime/kuberuntime_container_test.go
index 9e5fc4b0dad..895af01c689 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_container_test.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_container_test.go
@@ -959,7 +959,7 @@ func TestUpdateContainerResources(t *testing.T) {
        assert.Len(t, fakeContainers, 1)

        ctx := context.Background()
-       cStatus, _, err := m.getPodContainerStatuses(ctx, pod.UID, pod.Name, pod.Namespace)
+       cStatus, _, _, err := m.getPodContainerStatuses(ctx, pod.UID, pod.Name, pod.Namespace, "sandboxID")
        assert.NoError(t, err)
        containerID := cStatus[0].ID

diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index cb1cf4909f6..993b9507b65 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -1605,9 +1605,11 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety
        sandboxStatuses := []*runtimeapi.PodSandboxStatus{}
        containerStatuses := []*kubecontainer.Status{}
        containerStatusesMap := make(map[string][]*kubecontainer.Status)
+       activeSandboxContainerStatuses := []*kubecontainer.Status{}
        timestamp := time.Now()

        podIPs := []string{}
+       activePodSandboxID := ""
        for idx, podSandboxID := range podSandboxIDs {
                resp, err := m.runtimeService.PodSandboxStatus(ctx, podSandboxID, false)
                // Between List (getSandboxIDByPodUID) and check (PodSandboxStatus) another thread might remove a container, and that is normal.
@@ -1629,6 +1631,7 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety
                // Only get pod IP from latest sandbox
                if idx == 0 && resp.Status.State == runtimeapi.PodSandboxState_SANDBOX_READY {
                        podIPs = m.determinePodSandboxIPs(namespace, name, resp.Status)
+                       activePodSandboxID = podSandboxID
                }

                if idx == 0 && utilfeature.DefaultFeatureGate.Enabled(features.EventedPLEG) {
@@ -1639,7 +1642,7 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety
                                // features gate enabled, which includes Evented PLEG, but uses the
                                // runtime without Evented PLEG support.
                                klog.V(4).InfoS("Runtime does not set pod status timestamp", "pod", klog.KObj(pod))
-                               containerStatuses, containerStatusesMap, err = m.getPodContainerStatuses(ctx, uid, name, namespace)
+                               containerStatuses, containerStatusesMap, activeSandboxContainerStatuses, err = m.getPodContainerStatuses(ctx, uid, name, namespace, activePodSandboxID)
                                if err != nil {
                                        if m.logReduction.ShouldMessageBePrinted(err.Error(), podFullName) {
                                                klog.ErrorS(err, "getPodContainerStatuses for pod fail
ed", "pod", klog.KObj(pod))
@@ -1660,7 +1663,7 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety

        if !utilfeature.DefaultFeatureGate.Enabled(features.EventedPLEG) {
                // Get statuses of all containers visible in the pod.
-               containerStatuses, containerStatusesMap, err = m.getPodContainerStatuses(ctx, uid, name, namespace)
+               containerStatuses, containerStatusesMap, activeSandboxContainerStatuses, err = m.getPodContainerStatuses(ctx, uid, name, namespace, activePodSandboxID)
                if err != nil {
                        if m.logReduction.ShouldMessageBePrinted(err.Error(), podFullName) {
                                klog.ErrorS(err, "getPodContainerStatuses for pod failed", "pod", klog.KObj(pod))
@@ -1671,14 +1674,15 @@ func (m *kubeGenericRuntimeManager) GetPodStatus(ctx context.Context, uid kubety

        m.logReduction.ClearID(podFullName)
        return &kubecontainer.PodStatus{
-               ID:                   uid,
-               Name:                 name,
-               Namespace:            namespace,
-               IPs:                  podIPs,
-               SandboxStatuses:      sandboxStatuses,
-               ContainerStatuses:    containerStatuses,
-               ContainerStatusesMap: containerStatusesMap,
-               TimeStamp:            timestamp,
+               ID:                             uid,
+               Name:                           name,
+               Namespace:                      namespace,
+               IPs:                            podIPs,
+               SandboxStatuses:                sandboxStatuses,
+               ContainerStatuses:              containerStatuses,
+               ContainerStatusesMap:           containerStatusesMap,
+               ActiveSandboxContainerStatuses: activeSandboxContainerStatuses,
+               TimeStamp:                      timestamp,
        }, nil
 }
```

File: pkg/kubelet/container/helpers.go [hunk 2]
```diff
@@ -396,6 +396,8 @@ func MakePortMappings(container *v1.Container) (ports []PortMapping) {
 
 // HasAnyRegularContainerStarted returns true if any regular container has
 // started, which indicates all init containers have been initialized.
+// FIXME: This function is not accurate when its pod sandbox is recreated. Use
```
Comment (toVersus) [inline pkg/kubelet/container/helpers.go:399]: nit: I think this function won't be fixed as stated in the comment, so using `Deprecated:` might be more appropriate than `FIXME:`.

Comment (gjkim42) [reply pkg/kubelet/container/helpers.go]: fixed.

File: pkg/kubelet/container/helpers.go [hunk 3]
```diff
@@ -417,3 +419,26 @@ func HasAnyRegularContainerStarted(spec *v1.PodSpec, statuses []v1.ContainerStat
...
+
+// HasAnyActiveRegularContainerStarted returns true if any regular container of
+// the current pod sandbox has started, which indicates all init containers
+// have been initialized.
+func HasAnyActiveRegularContainerStarted(spec *v1.PodSpec, podStatus *PodStatus) bool {
+	if podStatus == nil {
+		return false
+	}
+
+	containerNames := make(map[string]struct{})
```
Comment (toVersus) [inline pkg/kubelet/container/helpers.go:431]: nit: I don’t have a strong stance on this, but I think the [sets](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/sets) library could be used here.

```diff
diff --git a/pkg/kubelet/container/helpers.go b/pkg/kubelet/container/helpers.go
index 44fd6f09d7c..9e6780310e6 100644
--- a/pkg/kubelet/container/helpers.go
+++ b/pkg/kubelet/container/helpers.go
@@ -428,13 +428,13 @@ func HasAnyActiveRegularContainerStarted(spec *v1.PodSpec, podStatus *PodStatus)
                return false
        }

-       containerNames := make(map[string]struct{})
+       containerNames := sets.New[string]()
        for _, c := range spec.Containers {
-               containerNames[c.Name] = struct{}{}
+               containerNames.Insert(c.Name)
        }

        for _, status := range podStatus.ActiveContainerStatuses {
-               if _, ok := containerNames[status.Name]; !ok {
+               if !containerNames.Has(status.Name) {
                        continue
                }
                return true
```

File: pkg/kubelet/container/helpers_test.go [hunk 4]
```diff
@@ -989,3 +990,118 @@ func TestHashContainerWithoutResources(t *testing.T) {
...
 }
+
+func TestHasAnyActiveRegularContainerStarted(t *testing.T) {
+	testCases := []struct {
+		desc      string
+		spec      *v1.PodSpec
+		podStatus *PodStatus
+		expected  bool
+	}{
+		{
```
Comment (toVersus) [inline pkg/kubelet/container/helpers_test.go:1001]: nit: It might not actually happen in reality, but it could be worthwhile to include a test case for when `ActiveContainerStatuses` is empty, if only to improve test coverage.

```diff
diff --git a/pkg/kubelet/container/helpers_test.go b/pkg/kubelet/container/helpers_test.go
index 87537096283..4e2afd20230 100644
--- a/pkg/kubelet/container/helpers_test.go
+++ b/pkg/kubelet/container/helpers_test.go
@@ -998,6 +998,30 @@ func TestHasAnyActiveRegularContainerStarted(t *testing.T) {
                podStatus *PodStatus
                expected  bool
        }{
+               {
+                       desc: "no active container statuses",
+                       spec: &v1.PodSpec{
+                               InitContainers: []v1.Container{
+                                       {
+                                               Name: "init",
+                                       },
+                               },
+                               Containers: []v1.Container{
+                                       {
+                                               Name: "regular",
+                                       },
+                               },
+                       },
+                       podStatus: &PodStatus{
+                               SandboxStatuses: []*runtimeapi.PodSandboxStatus{
+                                       {
+                                               Id:    "old",
+                                               State: runtimeapi.PodSandboxState_SANDBOX_NOTREADY,
+                                       },
+                               },
+                       },
+                       expected: false,
+               },
                {
                        desc: "pod is initializing",
                        spec: &v1.PodSpec{
```

**Review by toVersus — APPROVED** [review]
I just have a few minor comments, and no fixes are mandatory. LGTM

File: pkg/kubelet/container/helpers.go (hunk 3 above)
Comment (gjkim42) [reply pkg/kubelet/container/helpers.go]: done

File: pkg/kubelet/container/helpers_test.go (hunk 4 above)
Comment (gjkim42) [reply pkg/kubelet/container/helpers_test.go:1001]: done

**Comment by gjkim42** [comment]
/assign @SergeyKanzhelev 
Could you PTAL?

**Comment by gjkim42** [comment]
rebased and removed the feature gate checking as the feature was promoted to the GA

**Comment by toVersus** [comment]
> ctr: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/kindest/local-path-helper/blobs/sha256:fa83b000a99208739ae6d75e9f70cd341ceb204d77892deb4ce7c478019f2f13: 500 Internal Server Error

Failed due to a DockerHub incident.
https://www.dockerstatus.com/

image

/retest

**Comment by gjkim42** [comment]
@SergeyKanzhelev 
Could you PTAL?
This will address https://github.com/kubernetes/kubernetes/issues/127793.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go [hunk 5]
```diff
@@ -1691,7 +1691,7 @@ func TestUpdatePodSandboxResources(t *testing.T) {
 	assert.Len(t, fakeContainers, 1)
 
 	ctx := context.Background()
-	_, err := m.getPodContainerStatuses(ctx, pod.UID, pod.Name, pod.Namespace)
+	_, _, err := m.getPodContainerStatuses(ctx, pod.UID, pod.Name, pod.Namespace, "")
```
Comment (gjkim42) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go:1694]: rebased to fix the conflict due to the function signature change.

@SergeyKanzhelev @toVersus
Can you re-lgtm on this?

Comment (toVersus) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go:1694]: I'm not a member of kubernetes org yet, so I don't have permission to use /lgtm.

@SergeyKanzhelev @matthyx 
Could one of you handle it instead?

File: pkg/kubelet/container/helpers.go [hunk 6]
```diff
@@ -396,6 +396,8 @@ func MakePortMappings(container *v1.Container) (ports []PortMapping) {
 
 // HasAnyRegularContainerStarted returns true if any regular container has
 // started, which indicates all init containers have been initialized.
+// Deprecated: This function is not accurate when its pod sandbox is recreated.
+// Use HasAnyActiveRegularContainerStarted instead.
```
Comment (gjkim42) [inline pkg/kubelet/container/helpers.go:400]: for future me.
