### PR TITLE
Fix podIP validation

### LINKED ISSUE #90625: status.podIP validation is not run during pod/status updates
**What happened**:
PodIP validation for well-formedness was added in 1.16 in https://github.com/kubernetes/kubernetes/commit/54d42e6a658f84ea66593d3107f41db6931a5fbf

However, it was added to the ValidatePod() validation method, which is called for create/update requests to the main pod resource, not status update requests to the pods/status subresource, which is where pod IPs are actually set by the kubelet.

/sig network
/kind bug
/priority important-soon
/assign

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #90625

* Reduces the number of exported pod validation methods to match 1:1 to those called to validate API requests
* Tolerates updates to pod status for pods which already have malformed podIPs
* Updates unit tests to exercise valid -> valid, valid -> invalid, invalid -> valid, and invalid -> invalid podIP cases

**Does this PR introduce a user-facing change?**:
```release-note
Updates to pod status via the status subresource now validate that `status.podIP` and `status.podIPs` fields are well-formed.
```

/priority important-soon
/sig network
/assign @khenidak @thockin 
/cc @smarterclayton

### CODE REVIEW

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -3850,6 +3859,13 @@ func ValidatePodStatusUpdate(newPod, oldPod *core.Pod) field.ErrorList {
 	allErrs = append(allErrs, ValidateContainerStateTransition(newPod.Status.ContainerStatuses, oldPod.Status.ContainerStatuses, fldPath.Child("containerStatuses"), oldPod.Spec.RestartPolicy)...)
 	allErrs = append(allErrs, ValidateContainerStateTransition(newPod.Status.InitContainerStatuses, oldPod.Status.InitContainerStatuses, fldPath.Child("initContainerStatuses"), oldPod.Spec.RestartPolicy)...)
 
+	if newIPErrs := validatePodIPs(newPod); len(newIPErrs) > 0 {
+		// Tolerate IP errors if IP errors already existed in the old pod. See http://issue.k8s.io/90625
```
Comment (lavalamp) [inline pkg/apis/core/validation/validation.go:3863]: Add a TODO stating when this toleration can be removed?

**Comment by lavalamp** [comment]
lgtm other than that

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (liggitt) [reply pkg/apis/core/validation/validation.go:3863]: hmm, it'll read like "TODO: stop tolerating this once we can guarantee the existing pod was not created prior to 1.19"... I'm not aware of a plan to accomplish that

Comment (lavalamp) [reply pkg/apis/core/validation/validation.go:3863]: Kubelet maintains these, I think? Invalid pods shouldn't persist more than a few seconds. I think you just need to tolerate for one release?

**Comment by aojea** [comment]
/retest
the test timed out, unrelated

**Review by mattjmcnaughton — APPROVED** [review]
/retest

/lgtm
from a sig-node perspective.

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (liggitt) [reply pkg/apis/core/validation/validation.go:3863]: added a TODO for 1.20

**Comment by liggitt** [comment]
added TODO as requested, retagged
