### PR TITLE
Change structure of NodeToStatus map in scheduler

### LINKED ISSUE #125345: [scheduler] Improve Handling of Node Status
### What would you like to be added?

This issue is to track follow-ups from #125197, which addressed a performance issue related to the NodeToStatusMap. There are latent issues which we would like to address to prevent future regressions. We can either improve NodeToStatusMap to support some of the below operations more efficiently, or come up with different way to propagate these statuses through the scheduler.

current problems:
- we loop through all nodes to set the [same status](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/schedule_one.go#L458-L462)
  - w/ current implementation, only need to set Unschedulable status - see [comment](https://github.com/kubernetes/kubernetes/pull/125197#discussion_r1621723775)
- we [loop through all nodes](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/framework/preemption/preemption.go#L419-L430) when determining preemption candidates, so that we can create an [error message](https://github.com/kubernetes/kubernetes/blob/dae37c21645c0fc04bbb0202ad1eba6ba4438d23/pkg/scheduler/framework/types.go#L392-L397) based on the UnschedulableAndUnresolvable status. this error message can be generated more efficiently. also see [comment](https://github.com/kubernetes/kubernetes/pull/125197/files#r1621778045)

other considerations:
- when operating over many nodes, hashing node name string is hotspot when doing hashmap gets/sets. consider creating a lightweight `NodeKey` type, which, for a scheduling cycle, references an existing node. This type should be cheap to hash  (+allow lookup in [flat data structure](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/internal/cache/snapshot.go#L33)), and is safer than string node name, as it is guaranteed to reference a valid node.
- consider updating scheduler to not call postfilter plugins when all nodes are `UnschedulableAndUnresolvable`. at least, we should  reconcile the documented behavior [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L454-L456) and [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L90) and [here](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L97-L98)
- consider changing [Status](https://github.com/kubernetes/kubernetes/blob/a2911e06a7cd393f7cce088b8399f889527b517f/pkg/scheduler/framework/interface.go#L181) to an immutable type, so it can be safely shared.

/sig scheduling

### Why is this needed?

The current implementation includes some operations which may cause future performance regression. Additionally, there is some room for simplification.

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

It is a follow up of #125197, reducing populating of NodeToStatus map when possible. The structure of NodeToStatus is changed by introducing AbsentNodesStatus to pass the status message for absent nodes in the map.

Note: This PR breaks the interface of post filter plugins.  It's a second option to consider. In #125954 the solution proposed is not affecting the interface, but gives less flexibility. 

#### Which issue(s) this PR fixes:

Fixes #125345

#### Special notes for your reviewer:

Only one of #125954 and this PR should be merged.

#### Does this PR introduce a user-facing change?

```release-note
Changed NodeToStatusMap from map to struct and exposed methods to access the entries. Added absentNodesStatus, which inform what is the status of nodes that are absent in the map. 

ACTION REQUIRED: For developers of out-of-tree PostFilter plugins, make sure to update usage of NodeToStatusMap. Additionally, NodeToStatusMap should be eventually renamed to NodeToStatusReader.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/interface.go [hunk 1]
```diff
@@ -50,9 +50,54 @@ type NodeScore struct {
...
+	return len(m.nodeToStatus)
+}
+
+func (m *NodeToStatus) AbsentNodesStatus() *Status {
+	return m.absentNodesStatus
+}
+
+func (m *NodeToStatus) SetAbsentNodesStatus(status *Status) {
+	m.absentNodesStatus = status
+}
```
Comment (gabesaba) [inline pkg/scheduler/framework/interface.go:94]: Do we need to worry about the case where multiple plugins set this to different values in the same scheduling cycle? If so, we may consider the absent node status to either stay the same, or become progressively less schedulable - `Unschedulable` to `UnschedulableAndUnresolvable` is fine, but not the reverse

Comment (macsko) [reply pkg/scheduler/framework/interface.go:94]: Only post filter plugins use `NodeToStatus` (receive it as an argument), but as I understand, they treat it as a read-only data structure. It means that `absentNodesStatus` shouldn't be overwritten in any place.

@sanposhiho @alculquicondor Am I right that the post filter plugins shouldn't modify the `NodeToStatus` map?

Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:94]: `NodeToStatus` should be read-only in PostFilter from my memory, yes. 
But, this PR actually uses `SetAbsentNodesStatus` in preemption.go, right? Could other postfilter plugins want to do the same?

Comment (macsko) [reply pkg/scheduler/framework/interface.go:94]: `preemption.go` creates new NodeToStatus, but treats the PostFilter's arg as read-only. I think, to emphasize the desired way, we could create an interface with read-only methods and pass it to post filter plugins. Then, they would be able to create their own new maps (by instantiating NodeToStatus directly), but not break the current one (because of the interface).

```go
type NodeToStatusReader interface {
    Get(nodeName string) *Status
    Len() int
    AbsentNodesStatus() *Status
    ForEach(fn func(nodeName string, status *Status))
}
```

We could even name the interface `NodeToStatusMap` not to break the post filter plugins that doesn't use the map at all.

Comment (macsko) [reply pkg/scheduler/framework/interface.go:114]: Created `NodeToStatusReader` interface and `NodeToStatusMap` as its alias (not to break all the plugins as described above)

Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:114]: Got it regarding  `SetAbsentNodesStatus` in preemption.go (Sorry I didn't read through the PR very well).

Regarding `NodeToStatusReader`, I know if we had come up with the idea at day 1, it'd have been a better idea to emphasize it's read-only though, 
to introduce this change now looks so big that the merit (emphasize it's read-only) doesn't overcome the demerit (huge effort is required for custom preemption developers).
I'm -1 for it.

Comment (macsko) [reply pkg/scheduler/framework/interface.go:114]: I think that passing the `NodeToStatusReader` interface (aliased as `NodeToStatusMap`) won't break more plugins than solution without the interface (i.e. passing the `NodeToStatus` struct directly). 

Plugins that doesn't read the map or those that only pass it e.g. to the `Preempt` method, won't break, because the type name `framework.NodeToStatusMap` will match the previous one. 

The only plugins that will require attention are those that read the map, but passing the struct directly will force the same, since all operations on map are hidden under the methods.

Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:114]: > won't break more plugins than solution without the interface

Just looked at the previous commit. Okay, as you said, the previous commit also broke existing preemption plugins as much as the current version with `Reader` interface too.

Then, another angle though, how about just adding a status to PostFilter interface, rather than managing it in NodeToStatusMap in the first place?

```
// ...
// filterStatus is a status aggregated from prefilter or filter plugins status.  
// If the pod was rejected completely at PreFilter phase, filterStatus would be the same status as the one returned from RunPreFilterPlugins.
// And, if the Pod was rejected at Filter phase, it'd be Unschedulable if any Node was rejected with Unschedulable, otherwise UnschedulableAndUnresolvable.
PostFilter(ctx context.Context, state *CycleState, pod *v1.Pod, filteredNodeStatusMap NodeToStatusMap, filterStatus *Status) (*PostFilterResult, *Status)
```

Then, preemption PostFilter plugins can just return early when filterStatus is UnschedulableAndUnresolvable.
Would this idea reduce a required change + eliminate all the change to NodeToStatusMap? 
We, either way, break-change PostFilter interface with a new param though, people can just ignore a new param if they don't need it.

Comment (macsko) [reply pkg/scheduler/framework/interface.go:114]: > Then, another angle though, how about just adding a status to PostFilter interface, rather than managing it in NodeToStatusMap in the first place?

I'm not sure if this will give us any noticeable advantage. It would still require the same changes as in this PR, except modification of the map. By managing the absent status in `NodeToStatus` as proposed in this PR, it could be more straightforward to use, as both map and absent status are coupled naturally. Especially, absent status won't be accidentally ignored in the future, which could happen if handled separately. 

Your proposal would also break more PostFilter plugins, as the new arg would need to be added for each of them. In this PR `dynamicresources` plugin could not be changed at all, but did this to use the more preferable interface name over the alias.

We could even try to optimize the `NodeToStatus` in the future, by tracking changes of statuses and stating explicitly if all the nodes are `UnschedulableAndUnresolvable`, even if the map is non-empty (e.g. when filter plugins mark all the nodes as `UnschedulableAndUnresolvable`).

Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:114]: Yeah, I meant, it's a wider blast radius but smaller change (my proposal) vs a narrower blast radius but bigger change (yours), and I preferr **_ed_** mine a lot more for that point.

> Especially, absent status won't be accidentally ignored in the future, which could happen if handled separately.

But, this is a critical point. Mine would require people to be aware of a new `filterStatus` for a correct preemption, which we can easily imagine people miss it.

Okay, I'm now convinced. Let's go with the current `Reader` interface design.

Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:114]: @macsko Please update a release note with `Action required`.

File: pkg/scheduler/framework/interface.go [hunk 2]
```diff
@@ -50,9 +50,75 @@ type NodeScore struct {
...
 
-// NodeToStatusMap contains the statuses of the Nodes where the incoming Pod was not schedulable.
-// A PostFilter plugin that uses this map should interpret absent Nodes as UnschedulableAndUnresolvable.
-type NodeToStatusMap map[string]*Status
+// NodeToStatusReader is a read-only interface of NodeToStatus passed to each PostFilter plugin.
+type NodeToStatusReader interface {
+	Get(nodeName string) *Status
+	Len() int
+	AbsentNodesStatus() *Status
+	ForEach(fn func(nodeName string, status *Status))
```
[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:58]: In addition to ForEachStatus, for performant `nodesWherePreemptionMightHelp`, we may also want to have `Filter`

```go
type NodeToStatusReader interface {
...
	// O(n) where n = len(m.nodeToStatus)
	// which is more performant than iterating all nodes with Get().
	Filter(nodenames []string, fn func(status *Status) bool) []string
}
```

File: pkg/scheduler/framework/preemption/preemption.go [hunk 3]
```diff
@@ -410,25 +408,33 @@ func (ev *Evaluator) prepareCandidate(ctx context.Context, c Candidate, pod *v1.
...
-		if status.Code() == framework.Unschedulable {
-			potentialNodes = append(potentialNodes, node)
-		} else if !ok || status.Code() == framework.UnschedulableAndUnresolvable {
-			nodeStatuses[nodeName] = unresolvableStatus
+
+	if m.AbsentNodesStatus().Code() == framework.Unschedulable {
+		if m.Len() == 0 {
+			return allNodes
+		}
+		for _, node := range allNodes {
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/framework/preemption/preemption.go:420]: I think it would be hard to filter out the nodes using `ForEach` in this case faster than iterating through all the nodes. 

In this case, we want to filter the `Unschedulable` nodes when `Unschedulable` is also an `absentNodesStatus`, so we need to know all absent node names. I see only two solutions for this:
- My solution: Go through all the nodes and put into the result slice only these nodes, that are explicitly or implicitly `Unschedulable` (using `Get()` on `NodeToStatus`).
- Go through the nodes existing in `NodeToStatus` map and delete from the result these, that are not `Unschedulable`. The issue here is deleting the nodes, what would affect the performance significantly (transforming allNodes to set for faster delete ops and transform again to the final slice).

File: pkg/scheduler/framework/interface.go [hunk 4]
```diff
@@ -50,9 +50,75 @@ type NodeScore struct {
...
+}
+
+// NewDefaultNodeToStatus creates NodeToStatus without any node in the map.
+// The absentNodesStatus is set by default to UnschedulableAndUnresolvable.
+func NewDefaultNodeToStatus() *NodeToStatus {
+	return NewNodeToStatus(make(map[string]*Status), NewStatus(UnschedulableAndUnresolvable))
+}
+
+// NewNodeToStatus creates NodeToStatus initialized with given nodeToStatus and absentNodesStatus.
+func NewNodeToStatus(nodeToStatus map[string]*Status, absentNodesStatus *Status) *NodeToStatus {
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/framework/interface.go:81]: Not for all cases `NewNodeToStatus` is called with the same status. All codes are `UnschedulableAndUnresolvable` for sure, but the `reasons` differ depending on the usage. I think removing `absentNodesStatus` arg from `NewNodeToStatus` doesn't give us that much advantage.

File: pkg/scheduler/framework/interface.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/framework/interface.go:58]: Okay, understood (along with [this one](https://github.com/kubernetes/kubernetes/pull/126022#discussion_r1682894392) too). 
Then, performance pov aside, I'd still love to see if we could handle absent node status implicitly under `NodeToStatusReader` and eliminate `AbsentNodesStatus`.

As I wrote in [another comment](https://github.com/kubernetes/kubernetes/pull/126022#discussion_r1681032547), the current `NodeToStatusReader` requires people to be aware of `AbsentNodesStatus()` and handle it separately, which implies the same problem you pointed out in my previous proposal.

> Especially, absent status won't be accidentally ignored in the future, which could happen if handled separately.

Noticing the need to use a new parameter for a correct preemption vs the need to use `AbsentNodesStatus()` for a correct preemption, both include the same cognitive cost. 
(I'm not trying to stick to and revive my previous proposal here, it's just that I'd like to explore the possibility to eliminate this cognitive cost for users by adjusting an interface.)

[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/framework/interface.go]: You're right, removing `AbsentNodeStatus()` from the interface can reduce possible risks. 

I added a new method `NodesForStatusCode` which behaves like `nodesWherePreemptionMightHelp`, so it is returning all nodes that have a given status code, both explicitly and implicitly set. Now the `NodeToStatusReader` contains only `Get` and `NodesForStatusCode` methods.

I also renamed `ForEach` to `ForEachExplicitNode` to emphasize it's called only for the nodes explicitly set in the map. It is removed from the `NodeToStatusReader` so the risks of misusing it are lower.

Thanks for the pseudocode as well. I think, that keeping `NodeInfo` in `NodeToStatus` might overcomplicate the usage of the map (`Set` method), because in most cases we don't have corresponding `NodeInfo` available, so would need to get it from the snapshot then. Overall the `Filter` method structure is similar to the `NodesForStatusCode`.

File: pkg/scheduler/framework/interface.go [hunk 5]
```diff
@@ -50,9 +50,121 @@ type NodeScore struct {
...
-// NodeToStatusMap contains the statuses of the Nodes where the incoming Pod was not schedulable.
-// A PostFilter plugin that uses this map should interpret absent Nodes as UnschedulableAndUnresolvable.
-type NodeToStatusMap map[string]*Status
+// NodeToStatusReader is a read-only interface of NodeToStatus passed to each PostFilter plugin.
+type NodeToStatusReader interface {
+	// Get returns the status for given nodeName.
+	// If the node is not in the map, the AbsentNodesStatus is returned.
+	Get(nodeName string) *Status
+	// NodesForStatusCode returns a list of NodeInfos for the nodes that have a given status code.
+	// It returns the NodeInfos for all matching nodes denoted by AbsentNodesStatus as well.
```
Comment (sanposhiho) [inline pkg/scheduler/framework/interface.go:59]: nit: clarify it fetches all Nodes first and then filter them out based on status

```suggestion
	// NodesForStatusCode fetches all existing Nodes and returns the nodes that either explicitly have a given status code, 
	// or nodes that don't have a status explicitly when absentNodesStatus matches a given status code.
```

File: pkg/scheduler/framework/interface.go [hunk 6]
```diff
@@ -50,9 +50,121 @@ type NodeScore struct {
...
+				resultNodes = append(resultNodes, node)
+			}
+		}
+		return resultNodes, nil
+	}
+
+	if m.Len() == 0 {
+		// All nodes are absent and status code is not matching, so can return empty slice.
+		return nil, nil
+	}
```
Comment (sanposhiho) [inline pkg/scheduler/framework/interface.go:157]:
```suggestion
```

File: pkg/scheduler/framework/interface.go (hunk 5 above)
Comment (macsko) [reply pkg/scheduler/framework/interface.go:59]: Moved fetching all nodes to the branch where `absentNodesStatus` is matching given code, so altered the comment differently.

File: pkg/scheduler/framework/interface.go [hunk 7]
```diff
@@ -50,9 +50,120 @@ type NodeScore struct {
...
+		fn(nodeName, status)
+	}
+}
+
+// NodesForStatusCode returns a list of NodeInfos for the nodes that matches a given status code.
+// If the absentNodesStatus matches the code, all existing nodes are fetched using nodeLister
+// and filtered using NodeToStatus.Get.
+// If the absentNodesStatus doesn't match the code, nodeToStatus map is used to create a list of nodes
+// and nodeLister.Get is used to obtain NodeInfo for each.
+func (m *NodeToStatus) NodesForStatusCode(nodeLister NodeInfoLister, code Code) ([]*NodeInfo, error) {
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/framework/interface.go:135]: We want to hide `absentNodesStatus` in `NodeToStatusReader` to reduce the risks of not handling this field (see [comment](https://github.com/kubernetes/kubernetes/pull/126022#discussion_r1683123490)). If we move contents of this method back to the preemption.go, we would need to expose `AbsentNodesStatus()` and `ForEachExplicitNode()` in the interface, what we don't want to do.

File: pkg/scheduler/schedule_one.go [hunk 8]
```diff
@@ -735,11 +734,9 @@ func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Exten
...
 				continue
 			}
-			if _, found := statuses[failedNodeName]; !found {
-				statuses[failedNodeName] = framework.NewStatus(framework.Unschedulable, failedMsg)
-			} else {
-				statuses[failedNodeName].AppendReason(failedMsg)
-			}
+			status := statuses.Get(failedNodeName)
+			aggregatedReasons := append(status.Reasons(), failedMsg)
+			statuses.Set(failedNodeName, framework.NewStatus(framework.Unschedulable, aggregatedReasons...))
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/schedule_one.go:739]: I think it's correct. Using `statuses.Get` we obtain reasons for both explicitly and implicitly set status. We don't need to do any additional checks.

File: pkg/scheduler/framework/interface.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (gabesaba) [reply pkg/scheduler/framework/interface.go:135]: Ack. Thanks for the explaination.

**Comment by gabesaba** [comment]
/lgtm

Nice work. These types should make NodeToStatus much easier to understand and to use for plugin developers and k8 maintainers

File: pkg/scheduler/schedule_one.go [hunk 9]
```diff
@@ -721,12 +723,9 @@ func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Exten
 		}
 
 		for failedNodeName, failedMsg := range failedAndUnresolvableMap {
-			var aggregatedReasons []string
-			if _, found := statuses[failedNodeName]; found {
-				aggregatedReasons = statuses[failedNodeName].Reasons()
-			}
-			aggregatedReasons = append(aggregatedReasons, failedMsg)
-			statuses[failedNodeName] = framework.NewStatus(framework.UnschedulableAndUnresolvable, aggregatedReasons...)
+			status := statuses.Get(failedNodeName)
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go:726]: What if `failedNodeName` was _not_ rejected by PreFilter/Filter extension point?
Doesn't `statuses.Get(failedNodeName)` return absent node status incorrectly?

Comment (macsko) [reply pkg/scheduler/schedule_one.go]: You're right, `absentNodesStatus` reasons should not be used here, so added 
`if status != statuses.AbsentNodesStatus()` there. 

I also modified the tests to catch this issue.

File: pkg/scheduler/schedule_one.go [hunk 10]
```diff
@@ -735,11 +743,8 @@ func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Exten
 				// note that this only happens if the extender returns the node in both maps
 				continue
 			}
-			if _, found := statuses[failedNodeName]; !found {
-				statuses[failedNodeName] = framework.NewStatus(framework.Unschedulable, failedMsg)
-			} else {
-				statuses[failedNodeName].AppendReason(failedMsg)
-			}
+			aggregatedReasons := aggregateReasons(failedNodeName, failedMsg)
+			statuses.Set(failedNodeName, framework.NewStatus(framework.Unschedulable, aggregatedReasons...))
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go:747]: This is an existing issue unrelated to this PR though, what if extender-1 sets UnschedulableAndUnresolvable and then extender-2 sets Unschedulable afterwards? 
Should we not overwrite the status with `Unschedulable`, but only overwrite the reason with aggregated one?

File: pkg/scheduler/schedule_one.go [hunk 11]
```diff
@@ -693,8 +695,18 @@ func (sched *Scheduler) numFeasibleNodesToFind(percentageOfNodesToScore *int32,
...
 }
 
-func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Extender, pod *v1.Pod, feasibleNodes []*framework.NodeInfo, statuses framework.NodeToStatusMap) ([]*framework.NodeInfo, error) {
+func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Extender, pod *v1.Pod, feasibleNodes []*framework.NodeInfo, statuses *framework.NodeToStatus) ([]*framework.NodeInfo, error) {
 	logger := klog.FromContext(ctx)
+
+	aggregateReasons := func(nodeName string, failedMsg string) []string {
+		status := statuses.Get(nodeName)
+		if status != statuses.AbsentNodesStatus() {
+			// Only explicitly set node reasons should be added.
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go:704]:
```suggestion
			// Only explicitly set node reasons should be added.
			// If statuses.Get returns an absent status, it means this node isn't rejected by any extenders yet and hence we don't have to merge the reasons.
```

File: pkg/scheduler/schedule_one.go [hunk 12]
```diff
@@ -693,8 +695,18 @@ func (sched *Scheduler) numFeasibleNodesToFind(percentageOfNodesToScore *int32,
 	return numNodes
 }
 
-func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Extender, pod *v1.Pod, feasibleNodes []*framework.NodeInfo, statuses framework.NodeToStatusMap) ([]*framework.NodeInfo, error) {
+func findNodesThatPassExtenders(ctx context.Context, extenders []framework.Extender, pod *v1.Pod, feasibleNodes []*framework.NodeInfo, statuses *framework.NodeToStatus) ([]*framework.NodeInfo, error) {
 	logger := klog.FromContext(ctx)
+
+	aggregateReasons := func(nodeName string, failedMsg string) []string {
+		status := statuses.Get(nodeName)
+		if status != statuses.AbsentNodesStatus() {
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/schedule_one.go]: It will work anyway, but replaced with `status.Equal` for correctness.

File: pkg/scheduler/schedule_one.go (hunk 10 above)
Comment (macsko) [reply pkg/scheduler/schedule_one.go:748]: I think this scenario is not possible. `extender.Filter` returns list of feasible nodes ([ref](https://github.com/kubernetes/kubernetes/blob/8e0f2e83498d91b698b548ca165a0a9880f18fc5/pkg/scheduler/schedule_one.go#L727)), which denotes on which nodes the pod can be scheduled (after this filter). The `feasibleNodes` list is updated after each filter ([ref](https://github.com/kubernetes/kubernetes/blob/8e0f2e83498d91b698b548ca165a0a9880f18fc5/pkg/scheduler/schedule_one.go#L751)), so the next `extender.Filter` will get nodes that are neither `Unschedulable` nor `UnschedulableAndUnresolvable`.

If extender-1 will set `UnschedulableAndUnresolvable` for some node, this node won't be passed to the extender-2, so it won't get overwritten in the `NodeToStatus` as well.

Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:748]: > If extender-1 will set UnschedulableAndUnresolvable for some node, this node won't be passed to the extender-2, so it won't get overwritten in the NodeToStatus as well.

..wait, then why do we need to agrregate reasons? Could one Node get more than one reason?

- `findNodesThatPassExtenders()` receives Nodes that didn't get rejected at PreFilter/Filter phase.
- Once an extender rejects a Node, the Node isn't passed to a next extender.

Comment (macsko) [reply pkg/scheduler/schedule_one.go]: That's right! None of `feasibleNodes` can has a status in `statuses` in each step in `findNodesThatPassExtenders`. It is sufficient just to write the status into map without any redundant aggregation.

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

It's a great improvement!
