### PR TITLE
Fix Retry-After in clients

### LINKED ISSUE #26871: "Retry-After" in client doesn't work
During weekend, one of our kubemark runs failed with the following error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:187 scaling rc load-small-rc-3541 for the first time Expected error: <*errors.errorString | 0xc8637efb20>: { s: "error while scaling RC load-small-rc-3541 to 3 replicas: the server has received too many requests and has asked us to try again later (get replicationControllers load-small-rc-3541)", } error while scaling RC load-small-rc-3541 to 3 replicas: the server has received too many requests and has asked us to try again later (get replicationControllers load-small-rc-3541) not to have occurred
```
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-kubemark-gce-scale/1196/

This is super strange, because we are retrying  429 errors 10 times in client library.

So I looked into the logs, and what I see is:
```
I0603 20:32:02.537682    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (9.779µs) 429 [[e2e.test/v1.3.0 (linux/amd6    4) kubernetes/81c5cfc] 104.197.236.78:48896]
I0603 20:32:02.555134    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (11.266µs) 429 [[e2e.test/v1.3.0 (linux/amd    64) kubernetes/81c5cfc] 104.197.236.78:49194]
I0603 20:32:02.563122    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (10.84µs) 429 [[e2e.test/v1.3.0 (linux/amd6    4) kubernetes/81c5cfc] 104.197.236.78:48708]
I0603 20:32:02.575100    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (11.374µs) 429 [[e2e.test/v1.3.0 (linux/amd    64) kubernetes/81c5cfc] 104.197.236.78:49213]
I0603 20:32:02.586701    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (12.889µs) 429 [[e2e.test/v1.3.0 (linux/amd    64) kubernetes/81c5cfc] 104.197.236.78:49231]
I0603 20:32:02.591956    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (8.88µs) 429 [[e2e.test/v1.3.0 (linux/amd64    ) kubernetes/81c5cfc] 104.197.236.78:49229]
I0603 20:32:02.593688    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (9.82µs) 429 [[e2e.test/v1.3.0 (linux/amd64    ) kubernetes/81c5cfc] 104.197.236.78:49247]
I0603 20:32:02.597754    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (12.893µs) 429 [[e2e.test/v1.3.0 (linux/amd    64) kubernetes/81c5cfc] 104.197.236.78:49251]
I0603 20:32:02.607054    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (11.129µs) 429 [[e2e.test/v1.3.0 (linux/amd    64) kubernetes/81c5cfc] 104.197.236.78:49242]
I0603 20:32:02.610551    3507 handlers.go:135] GET /api/v1/namespaces/e2e-tests-load-30-nodepods-6-gd2g7/replicationcontrollers/load-small-rc-3541: (8.466µs) 429 [[e2e.test/v1.3.0 (linux/amd6    4) kubernetes/81c5cfc] 104.197.236.78:49264]
```

So we are retrying those requests one by one without and "retry-after".

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #26871

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek

**Comment by dims** [comment]
Looks good to me :)

**Comment by smarterclayton** [comment]
What's the point of the backoff mgr now?

**Comment by wojtek-t** [comment]
@smarterclayton - it's used in bunch of other places (e.g. line 807).

We may consider a different fix, but currently "Retry-After" simply doesn't work at all - see #26871

**Comment by smarterclayton** [comment]
So maybe we shouldn't be using NoBackoff, we should be using a new
ZeroBackoff which does sleep, but always returns CalculateBackoff of 0.
That would then keep the paths unified.  I think we would want retries to
be governed by a backoff abstraction (I think)>

**Comment by krousey** [comment]
Maybe the backoff interface doesn't need `Sleep` at all because they should all call `time.Sleep`

However, in the test, I would like a way to stub out sleep with a function that can record the number of times it was called and with what arguments for testing. I don't want to introduce actual sleeps into the tests.

**Comment by wojtek-t** [comment]
@krousey - your proposal sounds reasonable for me - I will fix the PR tomorrow.

**Comment by wojtek-t** [comment]
@krousey @smarterclayton - I changed it (not really as you suggested, but hopefully it's good enough).

PTAL

**Comment by wojtek-t** [comment]
@k8s-bot test this please, issue: #23545

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue:  #23545

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #23545

**Comment by smarterclayton** [comment]
Change LGTM (in terms of what we discussed)

**Comment by wojtek-t** [comment]
@k8s-bot test this please, issue: #23545

File: pkg/client/restclient/request_test.go [hunk 1]
```diff
@@ -838,6 +838,36 @@ func TestBackoffLifecycle(t *testing.T) {
...
+			b.t.Errorf("incorrect sleep: expected %v, got %v", expected, d)
+		}
+	}
+}
+
+func (b *testBackoffManager) Verify() {
+	if len(b.expectedSleeps) != 0 {
+		b.t.Errorf("some sleeps weren't called: %v", b.expectedSleeps)
+	}
+}
```
Comment (krousey) [inline pkg/client/restclient/request_test.go]: `testBackoffManager` should probably just record the sleep calls and leave the verification to the caller. This would allow for more test specific verification, put the error messages in the test cases, and de-tangle this struct from a `*testing.T` member.

File: pkg/client/restclient/request_test.go [hunk 2]
```diff
@@ -838,6 +838,36 @@ func TestBackoffLifecycle(t *testing.T) {
 	}
 }
 
+type testBackoffManager struct {
+	t              *testing.T
```
Comment (krousey) [inline pkg/client/restclient/request_test.go]: If you're going to do this, I would suggest using the `testing.TB` interface.

File: pkg/client/restclient/request_test.go [hunk 3]
```diff
@@ -849,12 +879,20 @@ func TestCheckRetryClosesBody(t *testing.T) {
...
+		http.Error(w, "Too many requests, please try again later.", apierrors.StatusTooManyRequests)
 	}))
 	defer testServer.Close()
 
+	backoffMgr := &testBackoffManager{t: t, expectedSleeps: make([]time.Duration, 0, 8)}
+	for i := 0; i < 4; i++ {
+		backoffMgr.expectedSleeps = append(backoffMgr.expectedSleeps, time.Duration(0))
+		backoffMgr.expectedSleeps = append(backoffMgr.expectedSleeps, time.Duration(1)*time.Second)
+	}
+	backoffMgr.expectedSleeps = append(backoffMgr.expectedSleeps, time.Duration(0))
```
Comment (krousey) [inline pkg/client/restclient/request_test.go]: Why not just:

```go
exp := []time.Duration{0, time.Second, 0, time.Second, 0, time.Second, 0, time.Second, 0}
```
?

Also, you call make with a capacity of 8, but append 9 items.

**Comment by wojtek-t** [comment]
@krousey - comments applied. PTAL

File: pkg/client/restclient/request_test.go [hunk 4]
```diff
@@ -838,6 +838,24 @@ func TestBackoffLifecycle(t *testing.T) {
...
+func (b *testBackoffManager) UpdateBackoff(actualUrl *url.URL, err error, responseCode int) {
+}
+
+func (b *testBackoffManager) CalculateBackoff(actualUrl *url.URL) time.Duration {
+	return time.Duration(0)
+}
+
+func (b *testBackoffManager) Sleep(d time.Duration) {
+	if b.sleeps == nil {
+		b.sleeps = make([]time.Duration, 0)
```
Comment (krousey) [inline pkg/client/restclient/request_test.go]: You can append to a nil slice. No need to explicitly allocate.

**Comment by krousey** [comment]
One minor nit, but LGTM otherwise.

**Comment by wojtek-t** [comment]
@krousey - thanks a lot for review - the last comment applied
