### PR TITLE
fix: assign default value for pod.Status.StartTime in TestSelectNodes…

### LINKED ISSUE #78348: TestSelectNodesForPreemption should assign pod.Status.StartTime for test Pod
**What would you like to be added**:
TestSelectNodesForPreemption should assign pod.Status.StartTime for test Pod

**Why is this needed**:
We can see the following in the output of TestSelectNodesForPreemption:
```
E0525 20:52:18.093682      17 utils.go:79] pod.Status.StartTime is nil for pod a. Should not reach here.
E0525 20:52:18.111788      17 utils.go:79] pod.Status.StartTime is nil for pod m1.2. Should not reach here.
```
This is due to test.pod missing assignment to Status.StartTime

### PR DESCRIPTION
**Pull request by draveness**
/kind bug
/priority backlog

**What this PR does / why we need it**:

> TestSelectNodesForPreemption should assign pod.Status.StartTime for test Pod
>
> We can see the following in the output of TestSelectNodesForPreemption:
>
> E0525 20:52:18.093682      17 utils.go:79] pod.Status.StartTime is nil for pod a. Should not reach here.
> E0525 20:52:18.111788      17 utils.go:79] pod.Status.StartTime is nil for pod m1.2. Should not reach here.
>
> ref: #78348

**Which issue(s) this PR fixes**:

Fixes #78348

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
cc/ @tedyu

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 1]
```diff
@@ -1198,6 +1206,14 @@ func TestPickOneNodeForPreemption(t *testing.T) {
 	}
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
+			now := metav1.Now()
```
Comment (hex108) [inline pkg/scheduler/core/generic_scheduler_test.go]: These code are same as line#980, perhaps we could create a function for it.

Comment (draveness) [reply pkg/scheduler/core/generic_scheduler_test.go]: done

**Comment by draveness** [comment]
Kindly ping @wojtek-t for approval
