### PR TITLE
Fix disappearing pods in scheduler

### LINKED ISSUE #29098: Scheduler can drop unscheduled pods and never scheduler them
If the first scheduling failed (whatever the reason is), the Error() func is called. However, the default Error function is wrong and in case of some errors may drop the pod and never requeue it for scheduling again.
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L539

The problem is that if the Get() function:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L534

return an error (for me it was "dial tcp 127.0.0.1:8080: connect: cannot assign requested address", but it doesn't really matter), then we simply forget about a pod and will never schedule it again.

We should retry those requests (with some backoff).

@davidopp

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #29098

### CODE REVIEW

File: plugin/pkg/scheduler/factory/factory.go [hunk 1]
```diff
@@ -531,12 +531,21 @@ func (factory *ConfigFactory) makeDefaultErrorFunc(backoff *podBackoff, podQueue
 			}
 			// Get the pod again; it may have changed/been scheduled already.
 			pod = &api.Pod{}
-			err := factory.Client.Get().Namespace(podID.Namespace).Resource("pods").Name(podID.Name).Do().Into(pod)
-			if err != nil {
-				if !errors.IsNotFound(err) {
-					glog.Errorf("Error getting pod %v for retry: %v; abandoning", podID, err)
+			backoff := time.Duration(100*time.Millisecond)
```
Comment (lukaszo) [inline plugin/pkg/scheduler/factory/factory.go]: Why are you overwriting the backoff variable?

File: plugin/pkg/scheduler/factory/factory.go [hunk 2]
```diff
@@ -531,12 +531,21 @@ func (factory *ConfigFactory) makeDefaultErrorFunc(backoff *podBackoff, podQueue
...
+			for {
```
Comment (lukaszo) [inline plugin/pkg/scheduler/factory/factory.go]: This may be an infinite loop

File: plugin/pkg/scheduler/factory/factory.go [hunk 3]
```diff
@@ -531,12 +531,21 @@ func (factory *ConfigFactory) makeDefaultErrorFunc(backoff *podBackoff, podQueue
...
+				if err == nil {
+					break
+				}
+				if errors.IsNotFound(err) {
+					glog.Warning("A pod %v no longer exists", podID)
+					return
+				}
+				glog.Errorf("Error getting pod %v for retry: %v; retrying...")
+				backoff = backoff * 2
+				if backoff > time.Minute {
```
Comment (lukaszo) [inline plugin/pkg/scheduler/factory/factory.go]: What's the goal here?

File: plugin/pkg/scheduler/factory/factory.go (hunk 1 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: Will fix

File: plugin/pkg/scheduler/factory/factory.go (hunk 2 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: Yes - it may be - otherwise we will loose the pod and it will never be scheduled. This is on purpose.

File: plugin/pkg/scheduler/factory/factory.go (hunk 3 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: We don't want super long backoff - we want to check it at least once per minute. This is pretty standard trick.

Comment (lukaszo) [inline plugin/pkg/scheduler/factory/factory.go]: Yeah, but shouldn't you add here some kind of sleep or something?

Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: Yeah - sure. Sleep is missing.

File: plugin/pkg/scheduler/factory/factory.go [hunk 4]
```diff
@@ -531,12 +531,20 @@ func (factory *ConfigFactory) makeDefaultErrorFunc(backoff *podBackoff, podQueue
 			}
 			// Get the pod again; it may have changed/been scheduled already.
 			pod = &api.Pod{}
-			err := factory.Client.Get().Namespace(podID.Namespace).Resource("pods").Name(podID.Name).Do().Into(pod)
-			if err != nil {
-				if !errors.IsNotFound(err) {
-					glog.Errorf("Error getting pod %v for retry: %v; abandoning", podID, err)
+			getBackoff := time.Duration(100 * time.Millisecond)
```
Comment (gmarek) [inline plugin/pkg/scheduler/factory/factory.go]: Make it a constant.

File: plugin/pkg/scheduler/factory/factory.go [hunk 5]
```diff
@@ -531,12 +531,20 @@ func (factory *ConfigFactory) makeDefaultErrorFunc(backoff *podBackoff, podQueue
...
+				if err := factory.Client.Get().Namespace(podID.Namespace).Resource("pods").Name(podID.Name).Do().Into(pod); err == nil {
+					break
 				}
-				return
+				if errors.IsNotFound(err) {
+					glog.Warning("A pod %v no longer exists", podID)
+					return
+				}
+				glog.Errorf("Error getting pod %v for retry: %v; retrying...", podID)
+				if getBackoff = getBackoff * 2; getBackoff > time.Minute {
```
Comment (gmarek) [inline plugin/pkg/scheduler/factory/factory.go]: Make a max a constant as well.

Comment (gmarek) [inline plugin/pkg/scheduler/factory/factory.go]: Maybe:
```
if getBackoff < time.Minute {
  getBackoff = getBackoff * 2
}
```

File: plugin/pkg/scheduler/factory/factory.go (hunk 4 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: done

File: plugin/pkg/scheduler/factory/factory.go (hunk 5 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: constant done

Regarding the second comment, I think it's easier to understand when you have a clear maximum. I don't understand the "endless multiplication" argument.

Comment (gmarek) [inline plugin/pkg/scheduler/factory/factory.go]: You'll be multiplying it all the time which will possibly cause the overflow of the integer, which in turn may make the backoff period negative (duration is a signed type).

Comment (wojtek-t) [inline plugin/pkg/scheduler/factory/factory.go]: That's not true. If it exceeds 1 minute, then I'm decreasing it to 1 minute. So I will never exceed 2 minutes during multiplication.

Comment (gmarek) [inline plugin/pkg/scheduler/factory/factory.go]: Right, sorry - but you'll still multiply it all the time, even when there's no need for it.

**Comment by gmarek** [comment]
govet is unhappy

**Comment by davidopp** [comment]
I may not be able to review this in the next 24 hours (I realize it's a small change but I need to look into the code that it's changing). If you need the review sooner, please reassign. Sorry for the trouble.

**Comment by davidopp** [comment]
Reviewing now -- didn't realize this was new code, not changing existing code.

**Comment by davidopp** [comment]
LGTM
