### PR TITLE
Fallback to ExternalIP in tests.

### LINKED ISSUE #136626: [sig-network] Tests fail if Node has no InternalIP
### What happened?

/sig network 

Our nodes don't have an InternalIP, they just have external IPs.

These tests fail:
> Summarizing 4 failures:
> [FAIL] [sig-network] HostPort [It] validates that there is no conflict between pods with the same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] [sig-network, Conformance]
> [k8s.io/kubernetes/test/e2e/network/hostport.go:82](http://k8s.io/kubernetes/test/e2e/network/hostport.go:82)
> [FAIL] [sig-network] Services [It] should be able to switch session affinity for a NodePort service [LinuxOnly] [Conformance] [sig-network, Conformance]
> [k8s.io/kubernetes/test/e2e/network/service.go:4461](http://k8s.io/kubernetes/test/e2e/network/service.go:4461)
> [FAIL] [sig-network] Services [It] should have session affinity work for a NodePort service [LinuxOnly] [Conformance] [sig-network, Conformance]
> [k8s.io/kubernetes/test/e2e/network/service.go:4461](http://k8s.io/kubernetes/test/e2e/network/service.go:4461)
> [FAIL] [sig-scheduling] SchedulerPredicates [Serial] [It] validates that there exists a conflict between pods with the same hostPort and protocol but one using 0.0.0.0 hostIP [Conformance] [sig-scheduling, Serial, Conformance]
> [k8s.io/kubernetes/test/e2e/scheduling/predicates.go:1270](http://k8s.io/kubernetes/test/e2e/scheduling/predicates.go:1270)

All four tests fail because there is no `InternalIP`.

sig-network said I should create an issue for that ([Slack Thread](https://kubernetes.slack.com/archives/C09QYUH5W/p1769693199795519))

```console
❯ k get nodes -o wide
NAME                                          STATUS   ROLES           AGE    VERSION   INTERNAL-IP   EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
thomas-sonobuoy2-md-amd64-dp4t2-bnkvb-2xx6r   Ready    <none>          119m   v1.34.3   <none>        46.225.15.183     Ubuntu 24.04.3 LTS   6.14.0-37-generic   containerd://2.2.1
thomas-sonobuoy2-md-amd64-dp4t2-bnkvb-gql7n   Ready    <none>          118m   v1.34.3   <none>        46.225.30.252     Ubuntu 24.04.3 LTS   6.14.0-37-generic   containerd://2.2.1
thomas-sonobuoy2-mxgbl-7fc9m                  Ready    control-plane   122m   v1.34.3   <none>        138.199.216.132   Ubuntu 24.04.3 LTS   6.14.0-37-generic   containerd://2.2.1
```

IPs of a node:

```console
root@thomas-sonobuoy2-md-amd64-dp4t2-bnkvb-2xx6r:~# ip a | grep 'inet '
    inet 127.0.0.1/8 scope host lo
    inet 46.225.15.183/32 metric 100 scope global dynamic eth0
    inet 192.168.1.115/32 scope global cilium_host
```

### What did you expect to happen?

I expect that tests pass. Afaik it is ok if a node has only an ExternalIP but no InternalIP.

### How can we reproduce it (as minimally and precisely as possible)?

Let KUBECONFIG point to a cluster without InternalIP, then:

in clone of k/k repo:

```
❯ ./_output/bin/e2e.test \
        --provider=local \
        --kubeconfig="$KUBECONFIG" \
        --ginkgo.focus="REGEX MATCHING ABOVE TEST"
```

### Anything else we need to know?

complete sonobuoy output:

[e2e-2026-01-17-scs-e2e.log](https://github.com/user-attachments/files/24940483/e2e-2026-01-17-scs-e2e.log)

### Kubernetes version

```console
$ kubectl version

Client Version: v1.35.0
Kustomize Version: v5.7.1
Server Version: v1.34.3

```

### Cloud provider

Cluster API Provider Hetzner (Syself) - Kubeadm

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Cilium v1.18.6

### PR DESCRIPTION
**Pull request by guettli**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Make test code behave like [GetNodeHostIPs()](https://pkg.go.dev/k8s.io/kubernetes/pkg/util/node#GetNodeHostIPs)

First try InternalIP, then ExternalIP.

#### Which issue(s) this PR is related to:
Fixes #136626

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -4215,6 +4215,9 @@ func execAffinityTestForSessionAffinityTimeout(ctx context.Context, f *framework
 			family = v1.IPv6Protocol
 		}
 		svcIP = e2enode.FirstAddressByTypeAndFamily(nodes, v1.NodeInternalIP, family)
+		if svcIP == "" {
+			svcIP = e2enode.FirstAddressByTypeAndFamily(nodes, v1.NodeExternalIP, family)
```
Comment (danwinship) [inline test/e2e/network/service.go]: This should also just use `GetNodeHostIPs()`.
Also, you need to update the wording of the error message just below.

File: test/e2e/framework/node/resource.go [hunk 2]
```diff
@@ -254,6 +254,28 @@ func FirstAddressByTypeAndFamily(nodelist *v1.NodeList, addrType v1.NodeAddressT
 	return ""
 }
 
+// GetIPAddressesByFamily returns a list of ip addresses of the given node filtered by IPFamily.
+// Return InternalIPs followed by ExternalIPs. Similar to GetNodeHostIPs().
+func GetIPAddressesByFamily(node *v1.Node, family v1.IPFamily) (ips []string) {
```
Comment (danwinship) [inline test/e2e/framework/node/resource.go]: Let's remove this; eventually everyone ought to be using a helper that just calls `GetNodeHostIPs()` underneath, so let's not add new helpers that don't.

File: test/e2e/network/hostport.go [hunk 3]
```diff
@@ -77,7 +77,7 @@ var _ = common.SIGDescribe("HostPort", func() {
 		}
 		randomNode := &nodes.Items[rand.Intn(len(nodes.Items))]
 
-		ips := e2enode.GetAddressesByTypeAndFamily(randomNode, v1.NodeInternalIP, family)
+		ips := e2enode.GetIPAddressesByFamily(randomNode, family)
```
Comment (danwinship) [inline test/e2e/network/hostport.go]: just make two calls to `GetAddressesByTypeAndFamily` like you did in `test/e2e/scheduling/predicates.go` below

File: test/e2e/network/hostport.go [hunk 4]
```diff
@@ -216,6 +216,6 @@ func createHostPortPodOnNode(ctx context.Context, f *framework.Framework, podNam
 	}
 
 	if err := e2epod.WaitTimeoutForPodReadyInNamespace(ctx, f.ClientSet, podName, ns, framework.PodStartTimeout); err != nil {
-		framework.Failf("wait for pod %s timeout, err:%v", podName, err)
+		framework.Failf("createHostPortPodOnNode: pod %s (%s:%d) failed or timeout, err:%v", podName, hostIP, port, err)
```
Comment (danwinship) [inline test/e2e/network/hostport.go]: not related to the PR?

File: test/e2e/network/service.go [hunk 5]
```diff
@@ -4215,6 +4215,9 @@ func execAffinityTestForSessionAffinityTimeout(ctx context.Context, f *framework
...
+		}
 		gomega.Expect(svcIP).NotTo(gomega.BeEmpty(), "failed to get Node internal IP for family: %s", family)
```
Comment (danwinship) [inline test/e2e/network/service.go]: update this error message

File: test/e2e/scheduling/predicates.go [hunk 6]
```diff
@@ -1267,6 +1267,9 @@ func getNodeHostIP(ctx context.Context, f *framework.Framework, nodeName string)
 	node, err := f.ClientSet.CoreV1().Nodes().Get(ctx, nodeName, metav1.GetOptions{})
 	framework.ExpectNoError(err)
 	ips := e2enode.GetAddressesByTypeAndFamily(node, v1.NodeInternalIP, family)
+	if len(ips) == 0 {
+		ips = e2enode.GetAddressesByTypeAndFamily(node, v1.NodeExternalIP, family)
+	}
 	if len(ips) == 0 {
 		framework.Failf("No address by type (%s) and family (%s) on node (%s) found.",
 			v1.NodeInternalIP, family, nodeName)
```
Comment (danwinship) [inline test/e2e/scheduling/predicates.go]: update this error message

**Review by danwinship — APPROVED** [review]
This updates the conformance tests (I assume?) but it still leaves a bunch of non-conformance tests unfixed.

There are like 18 different "get node IPs" helper functions in different parts of test/e2e and they're all varying degrees of wrong, but that's going to take a bigger PR to fix which I don't know if you're interested in working on.

Anyway, I'll approve but leave to Antonio to lgtm (after you fix it).

File: test/e2e/framework/node/resource.go (hunk 2 above)
Comment (guettli) [reply test/e2e/framework/node/resource.go]: ok, removed.

File: test/e2e/network/hostport.go (hunk 3 above)
Comment (guettli) [reply test/e2e/network/hostport.go]: done.

File: test/e2e/network/hostport.go (hunk 4 above)
Comment (guettli) [reply test/e2e/network/hostport.go]: yes, not related. Removed from PR.

File: test/e2e/network/service.go (hunk 5 above)
Comment (guettli) [reply test/e2e/network/service.go]: done.

File: test/e2e/scheduling/predicates.go (hunk 6 above)
Comment (guettli) [reply test/e2e/scheduling/predicates.go]: done.
