### PR TITLE
Fix panic in kube-proxy when iptables-save prints to stderr

### LINKED ISSUE #78443: kube-proxy panics when parsing iptables-save output
On some systems, iptables-save outputs the following warning to stderr: 
```
# Warning: iptables-legacy tables present, use iptables-legacy-save to see them
```

Note that the error message includes a newline. 

Because kube-proxy captures both stdout and stderr when calling `iptables-save`, the newline might cause rules to be garbled. For example, the output might contain the following line:
```
:8443
```

The parser treats this as a chain line, and panics, as predicted in https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/save_restore.go#L62-L63

### PR DESCRIPTION
**Pull request by luksa**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes kube-proxy so it doesn't panic when parsing iptables-save output corrupted by warnings printed to stderr.

**Which issue(s) this PR fixes**:
Fixes #78443 

**Does this PR introduce a user-facing change?**:
```release-note
Fixed panic in kube-proxy when parsing iptables-save output
```

### CODE REVIEW

File: pkg/util/iptables/iptables.go [hunk 1]
```diff
@@ -332,7 +333,7 @@ func (runner *runner) SaveInto(table Table, buffer *bytes.Buffer) error {
 	// creates a new buffer, redirects stdout and stderr to it and also
 	// calls Run()].
 	cmd.SetStdout(buffer)
-	cmd.SetStderr(buffer)
+	cmd.SetStderr(ioutil.Discard)
```
Comment (dcbw) [inline pkg/util/iptables/iptables.go]: @luksa it looks like this will just drop stderr on the floor even if the command resulted in an error. Instead, could we put stderr into another buffer, and return *that* buffer if cmd.Run() returns an error?

**Review by dcbw — CHANGES_REQUESTED** [review]

File: pkg/util/iptables/iptables.go (hunk 1 above)
Comment (luksa) [reply pkg/util/iptables/iptables.go]: @dcbw Done. PTAL

File: pkg/util/iptables/iptables.go [hunk 2]
```diff
@@ -326,14 +326,15 @@ func (runner *runner) SaveInto(table Table, buffer *bytes.Buffer) error {
...
-	// calls Run()].
 	cmd.SetStdout(buffer)
-	cmd.SetStderr(buffer)
-	return cmd.Run()
+	stderrBuffer := bytes.NewBuffer(nil)
+	cmd.SetStderr(stderrBuffer)
+
+	err := cmd.Run()
+	if err != nil {
+		stderrBuffer.WriteTo(buffer) // ignore error, since we need to return the original error
```
Comment (dcbw) [inline pkg/util/iptables/iptables.go]: @luksa do we want a buffer.Reset() here? If we don't, then the error output will be appended to the end of the stdout buffer, right?

Comment (luksa) [reply pkg/util/iptables/iptables.go]: I thought it was best to leave anything that came in through stdout intact. I can add the reset if you think it makes more sense. The current callers never use the buffer if an error occurs, so it doesn't matter much right now.

File: pkg/util/iptables/save_restore.go [hunk 3]
```diff
@@ -61,7 +61,11 @@ func GetChainLines(table Table, save []byte) map[Chain][]byte {
 		} else if line[0] == ':' && len(line) > 1 {
 			// We assume that the <line> contains space - chain lines have 3 fields,
 			// space delimited. If there is no space, this line will panic.
-			chain := Chain(line[1:bytes.Index(line, spaceBytes)])
+			spaceIndex := bytes.Index(line, spaceBytes)
+			if spaceIndex == -1 {
+				panic(fmt.Sprintf("Unexpected chain line in iptables-save output: %v", string(line)))
```
Comment (vllry) [inline pkg/util/iptables/save_restore.go]: Is a panic preferable to introducing an error return?

File: pkg/util/iptables/iptables.go [hunk 4]
```diff
@@ -326,14 +326,15 @@ func (runner *runner) SaveInto(table Table, buffer *bytes.Buffer) error {
 	args := []string{"-t", string(table)}
 	klog.V(4).Infof("running %s %v", iptablesSaveCmd, args)
 	cmd := runner.exec.Command(iptablesSaveCmd, args...)
-	// Since CombinedOutput() doesn't support redirecting it to a buffer,
-	// we need to workaround it by redirecting stdout and stderr to buffer
-	// and explicitly calling Run() [CombinedOutput() underneath itself
-	// creates a new buffer, redirects stdout and stderr to it and also
-	// calls Run()].
 	cmd.SetStdout(buffer)
```
[the remark this answers is not in the document]
Comment (luksa) [reply pkg/util/iptables/iptables.go]: But if the command fails, stderr is written to the buffer, so renaming it would be misleading.

File: pkg/util/iptables/save_restore.go (hunk 3 above)
Comment (luksa) [reply pkg/util/iptables/save_restore.go]: The original code panicked, but with a non-useful message. This change keeps the panic, but improves the message, so it's easier to see what the problem with the iptables-save output is. 

Returning an error would require a bigger change to all the callers. Plus, it's impossible to know how to handle the error.

File: pkg/util/iptables/iptables.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (vllry) [reply pkg/util/iptables/iptables.go]: Ah, gotcha.
