### PR TITLE
Made tracing of calls and container lifecycle steps in FakeDockerClient optional

### LINKED ISSUE #39717: BUG REPORT: FakeDockerClient will caused memory leak
When I try to use kubemark to do some perf-tests.I found that some kubemark(hollow-kubelet) will be OOM. Then I kept one kubemark running which I added pprof. 

```
root@k8s-node-perf3-15:/home/log/kubelet98# go tool pprof http://localhost:6060/debug/pprof/heap
Fetching profile from http://localhost:6060/debug/pprof/heap
Saved profile in /root/pprof/pprof.localhost:6060.inuse_objects.inuse_space.006.pb.gz
Entering interactive mode (type "help" for commands)
(pprof) top10
8066.61kB of 8066.61kB total (  100%)
Dropped 392 nodes (cum <= 40.33kB)
Showing top 10 nodes out of 106 (cum >= 512.04kB)
      flat  flat%   sum%        cum   cum%
 2072.09kB 25.69% 25.69%  2072.09kB 25.69%  k8s.io/kubernetes/vendor/github.com/beorn7/perks/quantile.NewTargeted
 1184.27kB 14.68% 40.37%  1184.27kB 14.68%  bytes.makeSlice
 1066.16kB 13.22% 53.59%  1066.16kB 13.22%  k8s.io/kubernetes/pkg/kubelet/dockertools.(*FakeDockerClient).ListContainers
  650.62kB  8.07% 61.65%   650.62kB  8.07%  k8s.io/kubernetes/vendor/github.com/golang/glog.(*syncBuffer).rotateFile
  524.09kB  6.50% 68.15%   524.09kB  6.50%  k8s.io/kubernetes/pkg/runtime.(*Scheme).AddKnownTypes
  516.01kB  6.40% 74.54%   516.01kB  6.40%  k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.newDefaultRegistry
     515kB  6.38% 80.93%      515kB  6.38%  reflect.Value.call
     514kB  6.37% 87.30%  2586.09kB 32.06%  k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.newSummary
  512.31kB  6.35% 93.65%   512.31kB  6.35%  net/http.(*Transport).tryPutIdleConn
  512.04kB  6.35%   100%   512.04kB  6.35%  net/http.(*persistConn).roundTrip
```

We found that `(*FakeDockerClient).ListContainers` use 1066.16kB and the number of `flat` in it is inscreasing. I add some log in this function:

```
var calltime = 0
// ListContainers is a test-spy implementation of DockerInterface.ListContainers.
// It adds an entry "list" to the internal method call record.
func (f *FakeDockerClient) ListContainers(options dockertypes.ContainerListOptions) ([]dockertypes.Container, error) {
	f.Lock()
	defer f.Unlock()
	f.called = append(f.called, calledDetail{name: "list"})
	err := f.popError("list")
	containerList := append([]dockertypes.Container{}, f.RunningContainerList...)
	if options.All {
		// Although the container is not sorted, but the container with the same name should be in order,
		// that is enough for us now.
		// TODO(random-liu): Is a fully sorted array needed?
		containerList = append(containerList, f.ExitedContainerList...)
	}
	calltime++
	glog.Warningf("[HY] f.called: len: %d, size: %d ; cont len: %d, size: %d ; calltime: %d", len(f.called), reflect.TypeOf(f.called).Size(), len(containerList), reflect.TypeOf(containerList).Size(), calltime)
	return containerList, err
}
```
and found that log:
```
2017-01-11 14:27:32.558310 W fake_docker_client.go:273] [HY] f.called: len: 20486, size: 24 ; cont len: 0, size: 24 ; calltime: 19544
2017-01-11 14:27:33.314934 W fake_docker_client.go:273] [HY] f.called: len: 20487, size: 24 ; cont len: 0, size: 24 ; calltime: 19545
2017-01-11 14:27:34.315221 W fake_docker_client.go:273] [HY] f.called: len: 20488, size: 24 ; cont len: 0, size: 24 ; calltime: 19546
```
We saw that the array  `f.called`  won't be released. It is used to record operation of fakedockerclient and only be check in unit test.

I think it be removed or periodically cleaned.

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes #39717 

Slightly refactored the FakeDockerClient code and made tracing optional (but enabled by default).

@yujuhong @Random-Liu

### CODE REVIEW

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 1]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+		// default this to an empty result, so that we never have a nil non-error response from InspectImage
+		Image: &dockertypes.ImageInspect{},
+		// default this to true, so that we trace calls, image pulls and container lifecycle
+		EnableTrace: true,
+	}
 }
 
-func NewFakeDockerClientWithClock(c clock.Clock) *FakeDockerClient {
-	return newClientWithVersionAndClock(fakeDockerVersion, minimumDockerAPIVersion, c)
+func (f *FakeDockerClient) WithClock(c clock.Clock) *FakeDockerClient {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: We need to lock here and the following.

**Comment by shyamjvs** [comment]
@yujuhong There are also some unused functions like AssertCreated, AssertStarted, AssertStopped, etc. Should we just let them stay there as available features?

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 2]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+	f.Clock = c
+	return f
 }
 
-func NewFakeDockerClientWithVersion(version, apiVersion string) *FakeDockerClient {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: There are some other places using this function. You also need to update them.
For example https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/pkg/kubelet/dockertools/images_test.go#L27.

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 3]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
-		ContainerMap: make(map[string]*dockertypes.ContainerJSON),
-		Clock:        c,
-		// default this to an empty result, so that we never have a nil non-error response from InspectImage
-		Image: &dockertypes.ImageInspect{},
+func (f *FakeDockerClient) WithTraceDisabled() *FakeDockerClient {
+	f.EnableTrace = false
+	return f
+}
+
+func (f *FakeDockerClient) AppendCalledWith(callDetail calledDetail) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: `AppendCalled`

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 4]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+	if f.EnableTrace == true {
+		f.called = append(f.called, callDetail)
+	}
+}
+
+func (f *FakeDockerClient) AppendPulledWith(pull string) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: `AppendPulled`

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 5]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+	if f.EnableTrace == true {
+		f.pulled = append(f.pulled, pull)
+	}
+}
+
+func (f *FakeDockerClient) AppendContainerTraceWithEntry(traceCategory string, containerName string) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: `AppendContainerTrace`

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 6]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+	if f.EnableTrace == false {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: nit: `!f.EnableTrace`.

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 7]
```diff
@@ -74,25 +75,58 @@ type FakeDockerClient struct {
...
+}
+
+func (f *FakeDockerClient) AppendCalledWith(callDetail calledDetail) {
+	if f.EnableTrace == true {
+		f.called = append(f.called, callDetail)
+	}
+}
+
+func (f *FakeDockerClient) AppendPulledWith(pull string) {
+	if f.EnableTrace == true {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: nit: `if f.EnableTrace {`

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 1 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done.

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 2 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Oops! Sorry for the blooper.

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 3 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 4 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 7 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 5 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 6 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 1 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Nice catch!

**Comment by shyamjvs** [comment]
@Random-Liu There is a very weird reason why the unit tests are failing. So in this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/container_gc_test.go#L33) in container_gc_test.go file, we do a new(FakeDockerClient) which initializes the struct with all fields set to their zero value. So this disables tracing and hence these tests fail later on, when they assert non-empty expected traces to be same as these actual empty traces.

Should we change the field in FakeDockerClient to DisableTrace or just change the line from `fakeDocker := new(FakeDockerClient)` to `fakeDocker := FakeDockerClient()`? Second option seems more reasonable but first one might be safer for future. @Random-Liu

**Comment by Random-Liu** [comment]
@shyamjvs Just change this line should be fine. I don't think the original code is right. We should always use initializer to create the object.

**Comment by shyamjvs** [comment]
@Random-Liu Can you PTAL now? Fixed the issue.

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 8]
```diff
@@ -74,25 +75,64 @@ type FakeDockerClient struct {
...
-		// default this to an empty result, so that we never have a nil non-error response from InspectImage
-		Image: &dockertypes.ImageInspect{},
+func (f *FakeDockerClient) WithTraceDisabled() *FakeDockerClient {
+	f.Lock()
+	defer f.Unlock()
+	f.EnableTrace = false
+	return f
+}
+
+func (f *FakeDockerClient) AppendCalled(callDetail calledDetail) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Use private function, because this function should only be used internally.

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 9]
```diff
@@ -74,25 +75,64 @@ type FakeDockerClient struct {
...
+	if f.EnableTrace {
+		f.called = append(f.called, callDetail)
+	}
+}
+
+func (f *FakeDockerClient) AppendPulled(pull string) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Ditto.

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 10]
```diff
@@ -74,25 +75,64 @@ type FakeDockerClient struct {
...
+	if f.EnableTrace {
+		f.pulled = append(f.pulled, pull)
+	}
+}
+
+func (f *FakeDockerClient) AppendContainerTrace(traceCategory string, containerName string) {
```
Comment (Random-Liu) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Ditto.

**Review by Random-Liu — COMMENTED** [review]
LGTM with one nit

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 8 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done. Thanks for pointing.

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 9 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done.

File: pkg/kubelet/dockertools/fake_docker_client.go (hunk 10 above)
Comment (shyamjvs) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Done.

**Comment by shyamjvs** [comment]
Adding lgtm label based on @Random-Liu 's comment.

**Comment by Random-Liu** [comment]
@k8s-bot test this please.
