### PR TITLE
Fix 7 broken example e2e tests

### LINKED ISSUE #27325: kubernetes-e2e-gce-examples: broken test run
@janetkuo is fixing this in #27577 

---

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/11852/

Multiple broken tests:

Failed: [k8s.io] [Feature:Example] [k8s.io] Hazelcast should create and scale hazelcast {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:478
Jun 13 13:12:02.870: No pods matched the filter.
```

Failed: [k8s.io] [Feature:Example] [k8s.io] Redis should create and stop redis servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:116
Expected error:
    <*errors.errorString | 0xc820077f80>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

Failed: [k8s.io] [Feature:Example] [k8s.io] Cassandra should create and scale cassandra {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:257
Expected error:
    <*errors.errorString | 0xc820f78420>: {
        s: "Failed to get entpoints for e2e-tests-examples-bo22d/cassandra",
    }
    Failed to get entpoints for e2e-tests-examples-bo22d/cassandra
not to have occurred
```

Failed: [k8s.io] [Feature:Example] [k8s.io] Spark should start spark master, driver and workers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:220
Expected error:
    <*errors.errorString | 0xc8208cef10>: {
        s: "Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.199.182 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-7bcy1] []  <nil>  the namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-7bcy1\". You must pass '--namespace=spark-cluster' to perform this operation.\n [] <nil> 0xc820709080 exit status 1 <nil> true [0xc82008c390 0xc82008c3b8 0xc82008c3d8] [0xc82008c390 0xc82008c3b8 0xc82008c3d8] [0xc82008c3b0 0xc82008c3c8] [0xa63db0 0xa63db0] 0xc8207a6360}:\nCommand stdout:\n\nstderr:\nthe namespace from the provided object \"spark-cluster\" does not match the namespace \"e2e-tests-examples-7bcy1\". You must pass '--namespace=spark-cluster' to perform this operation.\n\nerror:\nexit status 1\n",
    }
    Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.199.182 --kubeconfig=/workspace/.kube/config create -f /workspace/kubernetes/examples/spark/spark-master-service.yaml --namespace=e2e-tests-examples-7bcy1] []  <nil>  the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-7bcy1". You must pass '--namespace=spark-cluster' to perform this operation.
     [] <nil> 0xc820709080 exit status 1 <nil> true [0xc82008c390 0xc82008c3b8 0xc82008c3d8] [0xc82008c390 0xc82008c3b8 0xc82008c3d8] [0xc82008c3b0 0xc82008c3c8] [0xa63db0 0xa63db0] 0xc8207a6360}:
    Command stdout:
    
    stderr:
    the namespace from the provided object "spark-cluster" does not match the namespace "e2e-tests-examples-7bcy1". You must pass '--namespace=spark-cluster' to perform this operation.
    
    error:
    exit status 1
    
not to have occurred
```

Failed: [k8s.io] [Feature:Example] [k8s.io] Celery-RabbitMQ should create and stop celery+rabbitmq servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:161
Jun 13 13:06:55.120: No pods matched the filter.
```

Failed: [k8s.io] [Feature:Example] [k8s.io] Storm should create and stop Zookeeper, Nimbus and Storm worker servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:311
Jun 13 13:08:50.520: No pods matched the filter.
```

Failed: [k8s.io] [Feature:Example] [k8s.io] RethinkDB should create and stop rethinkdb servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:447
Jun 13 13:11:16.772: No pods matched the filter.
```

### LINKED ISSUE #27727: [k8s.io] [Feature:Example] [k8s.io] Redis should create and stop redis servers {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-examples/12122/

Failed: [k8s.io] [Feature:Example] [k8s.io] Redis should create and stop redis servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:125
Expected error:
    <*errors.errorString | 0xc8200e00c0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #27325, Fixes #27727

7 broken example e2e tests:
- [x] Spark  
  - `namespace` is specified in example yaml files which conflict with e2e test namespaces, fixed by removing the namespace in yaml (the yaml files of [spark example](https://github.com/kubernetes/kubernetes/tree/master/examples/spark) doesn't need the namespace specified since it's specified in its context)  -- cc @k82 who added namespace to Spark example in #23807
  - wait for pods to exist before determining if it's running
- [x] Hazelcast
  - wait for pods to exist before determining if it's running
- [x] Redis
  - image `kubernetes/redis:v2` is not found, changed to `kubernetes/redis:v1` instead
  - wait for pods to exist before determining if it's running
- [x] Celery-RabbitMQ
  - remove 1 redundant call to `forEachPod`
  - wait for pods to exist before determining if it's running
- [x] Cassandra
  - fix `kubectl exec` on incorrect pod name 
  - fix getting endpoint ip addresses before creating pods 
  - wait for pods to exist before determining if it's running
- [x] Storm
  - wait for pods to exist before determining if it's running
- [x] RethinkDB
  - wait for pods to exist before determining if it's running

[Analytics]()

### CODE REVIEW

**Comment by janetkuo** [comment]
I'll keep fixing other example test failures (either in this PR or subsequent PRs).

**Comment by janetkuo** [comment]
cc @k82 who added namespace to Spark example in #23807

**Comment by janetkuo** [comment]
All broken example tests fixed. Tested locally against GCE cluster. Detail fix documented in PR description. @pwittrock ptal

**Comment by janetkuo** [comment]
cc @kubernetes/examples

**Comment by chrislovecnm** [comment]
Cassandra needs to be rewritten ... It does not verify anything. Kinda on my plate.

File: test/e2e/examples.go [hunk 1]
```diff
@@ -39,13 +39,18 @@ const (
 
 var _ = framework.KubeDescribe("[Feature:Example]", func() {
 	f := framework.NewDefaultFramework("examples")
-	// Customized ForEach wrapper for this test.
-	forEachPod := func(selectorKey string, selectorValue string, fn func(api.Pod)) {
-		f.NewClusterVerification(
+
+	// Reustable cluster state function.  This won't be adversly affected by lazy initialization of framework.
```
Comment (pwittrock) [inline test/e2e/examples.go]: nit: typo Reusable

**Comment by jayunit100** [comment]
Thanks for doing this. I haven't been working on kube the last month, I'll be circling back in July.

**Comment by chrislovecnm** [comment]
Yes @janetkuo we appreciate you doing this very much, these examples have not been happy for a long time.

**Comment by janetkuo** [comment]
cc @goltermann and @dims who's also fixing these broken tests
Please let me know which tests you havn't fix yet before I continue, to prevent further rebase and/or dup works

**Comment by dims** [comment]
@janetkuo the only PR i have for this is under issue https://github.com/kubernetes/kubernetes/issues/27683 the PR itself is https://github.com/kubernetes/kubernetes/pull/27717

**Comment by goltermann** [comment]
From here out, I think just Redis and Spark need help

**Comment by janetkuo** [comment]
> From here out, I think just Redis and Spark need help

Great! I'll fix those two.

**Comment by chrislovecnm** [comment]
@janetkuo is the current C* image passing e2e? I ask because we have another issue open, and I am concerned we have an old image in gcr.io

**Comment by janetkuo** [comment]
@chrislovecnm current test results: https://k8s-testgrid.appspot.com/google-gce#gce-examples&width=20

File: examples/redis/redis-controller.yaml [hunk 2]
```diff
@@ -13,7 +13,7 @@ spec:
     spec:
       containers:
       - name: redis
-        image: kubernetes/redis:v2
+        image: kubernetes/redis:v1
```
Comment (fejta) [inline examples/redis/redis-controller.yaml]: Any chance we can move these images somewhere in gcr.io?

**Comment by fejta** [comment]
@goltermann I'm tagging this as 1.3 because it will fix https://github.com/kubernetes/kubernetes/issues/27727

**Comment by chrislovecnm** [comment]
@janetkuo I bet we are not doing a test with a PV Persistent disk ...  It is a permission with the Docker.  I will have time in about a week to update the image.

**Comment by janetkuo** [comment]
@pwittrock update; ptal 
@chrislovecnm suggest adding those test improvement you proposed in follow-up PRs since those are less urgent

**Comment by chrislovecnm** [comment]
@janetkuo was not implying ... just working out what is going on, and yes we need to tweak a bunch of stuff with e2e and examples.

**Comment by chrislovecnm** [comment]
@pwittrock this looks great.  Who is giving the LGTM?

**Comment by janetkuo** [comment]
@chrislovecnm thanks, applying tag

**Comment by goltermann** [comment]
LGTM from me too, btw.  Really happy to get these working.  Do we need a bug to elevate these to critical builds (or consider elevating)?

**Comment by goltermann** [comment]
@k8s-bot verify this issue: #27797

File: examples/redis/redis-controller.yaml (hunk 2 above)
Comment (janetkuo) [inline examples/redis/redis-controller.yaml]: fixing in #27805

**Comment by k82cn** [comment]
@janetkuo , got that. Thanks for your effort :).
