### PR TITLE
Fix job tracking leaving pods with finalizers

### LINKED ISSUE #109485: Job tracking might leave pods with finalizers when backoff limit is reached
### What happened?

A job reached it's backoff limit and pods were left with finalizers.

The `.status.uncountedTerminatedPods` was left empty.

### What did you expect to happen?

The pods to not have a finalizer

### How can we reproduce it (as minimally and precisely as possible)?

We don't have a low scale repro. But we observe this:

```
spec:
  backoffLimit: 0
  completionMode: Indexed
  completions: 5000
  parallelism: 5000
status:
  completedIndexes: 0-4003,4005
  conditions:
  - lastProbeTime: "2022-04-14T14:09:23Z"
    lastTransitionTime: "2022-04-14T14:09:23Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 1
  startTime: "2022-04-14T13:57:54Z"
  succeeded: 4005
  uncountedTerminatedPods: {}
```

1 Pod failed, potentially 4004. What happened to 4006 and beyond? The job controller creates pods in batches of 500, so it looks like the job was declared finished before observing all the pods that it created.
I confirmed from the kcm logs that the pod was created:

```
"Event occurred" object="default/job-foo" kind="Job" apiVersion="batch/v1" type="Normal" reason="SuccessfulCreate" message="Created pod: job-foo-4006-zjrqh"
```

### Anything else we need to know?

This cluster doesn't have the patch #109020. However, the job still exists, so it doesn't sound like it's the same bug.

### Kubernetes version

<details>

1.23.5

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

- Add a repro in integration (it's very hard to make it fail, but it does fail)
- Fix the underlying bug: Do not declare a job as finished until the pod expectations are satisfied.
- Fix side problem: clusters running with the bug might have left pods with finalizers that belong to finished jobs. Also related to #109429
- Enable integration test Foreground job deletion + GC.

#### Which issue(s) this PR fixes:

Fixes #109485 

#### Special notes for your reviewer:

This PR does not re-enable the feature. We can do so after we get good signal from the integration tests in CI.

#### Does this PR introduce a user-facing change?

```release-note
Fix JobTrackingWithFinalizers that:
- was declaring a job finished before counting all the created pods in the status
- was leaving pods with finalizers, blocking pod and job deletions

JobTrackingWithFinalizers is still disabled by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/job/job_test.go [hunk 1]
```diff
@@ -575,29 +575,76 @@ func TestOrphanPodsFinalizersClearedWithGC(t *testing.T) {
...
+}
+
+func validateNoOrphanPodsWithFinalizers(ctx context.Context, t *testing.T, clientSet clientset.Interface, jobObj *batchv1.Job) {
+	t.Helper()
+	orphanPods := 0
+	if err := wait.Poll(waitInterval, wait.ForeverTestTimeout, func() (done bool, err error) {
+		pods, err := clientSet.CoreV1().Pods(jobObj.Namespace).List(ctx, metav1.ListOptions{
+			LabelSelector: metav1.FormatLabelSelector(jobObj.Spec.Selector),
+		})
+		if err != nil {
```
Comment (aojea) [inline test/integration/job/job_test.go:632]: do you need to discard that err is different than notFound? or is not a possibility in these tests?

Comment (alculquicondor) [reply test/integration/job/job_test.go:632]: Even if the list has zero items, the query doesn't return a NotFound error.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/triage accepted
/priority important-longterm

File: pkg/controller/job/job_controller.go [hunk 2]
```diff
@@ -384,7 +384,8 @@ func (jm *Controller) deletePod(obj interface{}, final bool) {
 		return
 	}
 	job := jm.resolveControllerRef(pod.Namespace, controllerRef)
-	if job == nil {
+	if job == nil || IsJobFinished(job) {
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:387]: this doesn't consider deletionTimestamp, right? only the JobComplete or JobFailed status? does the controller always set that status on Jobs that are actively being deleted? for example, a job with a finalizer that prevents removal, and with a deletion timestamp

Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:387]: Correct, it doesn't consider the deletionTimestamp, only the job conditions Complete or Failed.

syncJob, the main job-controller worker, continues to synchronize a job until it sets the Complete or Failed condition. So in these cases, we let this worker take care of the finalizers.

File: pkg/controller/job/job_controller.go [hunk 3]
```diff
@@ -782,17 +783,17 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
 		if uncounted == nil {
 			// Legacy behavior: pretend all active pods were successfully removed.
 			deleted = active
-		} else if deleted != active {
+		} else if deleted != active || !satisfiedExpectations {
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:786]: I don't have context to review this line... if we skip this because we haven't satisfied expectations yet, are we relying on a retry and eventually satisfying those expectations, or is this a one-time short-circuit

File: pkg/controller/job/job_controller.go [hunk 4]
```diff
@@ -782,17 +783,17 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (forget bool, rEr
...
 			// Can't declare the Job as finished yet, as there might be remaining
-			// pod finalizers.
+			// pod finalizers or pods that are not in the informer's cache yet.
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:788]: the informer cache bit makes it sound like we're waiting for the informer to catch up so that expectations are satisfied... is that always going to happen (for example, if the namespace has been deleted and no new pods can be created)?

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:786]: We are not relying on retry per-se. We are relying on the pod creation events to add the job to the workqueue again. This is the same thing we do when starting a job to avoid creating extra pods.

File: pkg/controller/job/job_controller.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:788]: The expectations are based on successful pod creations. If the namespace gets deleted in between, we would at least get a pod creation, because the pod is created with a finalizer.

**Comment by alculquicondor** [comment]
> /milestone v1.24

We are too late for 1.24.0, so we are aiming to get this in 1.25 and 1.24.1

**Comment by helayoty** [comment]
> > /milestone v1.24
> 
> We are too late for 1.24.0, so we are aiming to get this in 1.25 and 1.24.1

👋  Bug Triage Shadow for 1.24 here, We discussed this issue on the `sig-release` channel and we see it's best to be removed from `1.24.0`, instead you can target `1.24.1` or `1.25`.

**Comment by JamesLaverack** [comment]
/minestone clear

To avoid accidental merge into `master` before the 1.24 freeze finishes.

**Comment by alculquicondor** [comment]
/hold cancel

Is code-freeze over soon?
