### PR TITLE
node: device-mgr: Handle recovery flow by checking if healthy devices exist

### LINKED ISSUE #109595: device manager can incorrectly recover devices on node restart
### What happened?

The following behaviour was reproduced on openshift 4.10 ("Kubelet version" kubeletVersion="v1.23.3+54654d2") but I believe the root cause is on kubernetes.

Let's consider a pod requiring resources, among them a device (point in case: dpdk network device)
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dpdk
  name: testpmd
  namespace: default
spec:
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep INF
      image: $DPKDK_IMAGE
      imagePullPolicy: Always
      name: dpdk
      resources:
        limits:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
        requests:
          memory: 1000Mi
          hugepages-1Gi: 1Gi
          cpu: '2'
          openshift.io/dpdk_nic_1: 1
      securityContext:
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
```
the pods starts and run just fine up until the node is restarted. On restart, the device manager correctly recover its state from the checkpoint data:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.461850    2011 manager.go:247] "Starting Device Plugin manager"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.463809    2011 container_manager_linux.go:930] "Attempting to apply oom_score_adj to process" oomScoreAdj=-999 pid=2011
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464997    2011 oom_linux.go:66] attempting to set "/proc/2011/oom_score_adj" to "-999"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.464269    2011 iptables.go:462] running iptables: ip6tables [-w 5 -W 100000 -N KUBE-POSTROUTING -t nat]
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.465254    2011 event.go:294] "Event occurred" object="TESTNODE" kind="Node" apiVersion="" type="Normal" reason="NodeAllocatableEnforced" message="Updated Node Allocatable limit across pods"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466379    2011 pod_devices.go:215] "Get checkpoint entry" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" containerName="dpdk" resourceName="openshift.io/dpdk_nic_1" deviceIDs=map[-1:[0000:00:05.0]] allocated="\n1\n!PCIDEVICE_OPENSHIFT_IO_DPDK_NIC_1\x12\f0000:00:05.0\x1a%\n\x0e/dev/vfio/vfio\x12\x0e/dev/vfio/vfio\x1a\x03mrw\x1a'\n\v/dev/vfio/0\x12\x13/dev/vfio/noiommu-0\x1a\x03mrw"
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.466823    2011 manager.go:289] "Serving device plugin registration server on socket" path="/var/lib/kubelet/device-plugins/kubelet.sock"
```
As expected, the device plugin capacity is set to zero until the device plugin correctly re-register itself:
```
Apr 13 09:53:14 TESTNODE hyperkube[2011]: I0413 09:53:14.607362    2011 setters.go:344] "Updated capacity for device plugin" plugin="openshift.io/dpdk_nic_1" capacity=0`
```
A bit later, the recovery process from the apiserver begins:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193478    2011 config.go:278] "Setting pods for source" source="api"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193526    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-node-tuning-operator/tuned-tql4x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193541    2011 config.go:383] "Receiving a new pod" pod="openshift-sdn/sdn-fnls4"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193549    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/node-exporter-jzprg"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193557    2011 config.go:383] "Receiving a new pod" pod="openshift-ingress-canary/ingress-canary-62kq2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193565    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-87sbt"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193573    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/network-metrics-daemon-5qb5q"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193580    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/node-ca-frkhr"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193597    2011 config.go:383] "Receiving a new pod" pod="openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193605    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193615    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193624    2011 config.go:383] "Receiving a new pod" pod="openshift-machine-config-operator/machine-config-daemon-nkqsq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193632    2011 config.go:383] "Receiving a new pod" pod="openshift-image-registry/image-pruner-27496800-n4qzq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193640    2011 config.go:383] "Receiving a new pod" pod="openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193649    2011 config.go:383] "Receiving a new pod" pod="openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193659    2011 config.go:383] "Receiving a new pod" pod="openshift-multus/multus-additional-cni-plugins-xwgkj"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193667    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/coredns-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193674    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/node-resolver-6n2vp"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193682    2011 config.go:383] "Receiving a new pod" pod="openshift-openstack-infra/keepalived-TESTNODE"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193689    2011 config.go:383] "Receiving a new pod" pod="openshift-dns/dns-default-cnlrl"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193695    2011 config.go:383] "Receiving a new pod" pod="default/testpmd"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193703    2011 config.go:383] "Receiving a new pod" pod="openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193711    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-network-config-daemon-p94vm"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193721    2011 config.go:383] "Receiving a new pod" pod="openshift-sriov-network-operator/sriov-device-plugin-bw7rq"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.193728    2011 config.go:383] "Receiving a new pod" pod="openshift-network-diagnostics/network-check-target-2tbjs"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.195257    2011 kubelet.go:2106] "SyncLoop ADD" source="api" pods=[openshift-cluster-node-tuning-operator/tuned-tql4x openshift-sdn/sdn-fnls4 openshift-monitoring/node-exporter-jzprg openshift-ingress-canary/ingress-canary-62kq2 openshift-multus/multus-87sbt openshift-multus/network-metrics-daemon-5qb5q openshift-image-registry/node-ca-frkhr openshift-monitoring/prometheus-adapter-689c895f8f-zpsx2 openshift-operator-lifecycle-manager/collect-profiles-27497370-6vd5b openshift-operator-lifecycle-manager/collect-profiles-27497385-mwtfp openshift-machine-config-operator/machine-config-daemon-nkqsq openshift-image-registry/image-pruner-27496800-n4qzq openshift-cluster-csi-drivers/openstack-cinder-csi-driver-node-qklm6 openshift-marketplace/246a7cd23747989b8f475c6ffc04f7e523236656eaac2249a6d4ddf03bvpl6x openshift-multus/multus-additional-cni-plugins-xwgkj openshift-openstack-infra/coredns-TESTNODE openshift-dns/node-resolver-6n2vp openshift-openstack-infra/keepalived-TESTNODE openshift-dns/dns-default-cnlrl default/testpmd openshift-operator-lifecycle-manager/collect-profiles-27497355-cdncm openshift-sriov-network-operator/sriov-network-config-daemon-p94vm openshift-sriov-network-operator/sriov-device-plugin-bw7rq openshift-network-diagnostics/network-check-target-2tbjs]
```
we can see already that the workload pod (testpmd) is going to be recovered BEFORE the device plugin. When the workload pod 
enters the admission flow (as per recovered pods), because the devicemanager restored its state and has data about this pod, we see:
```
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204837    2011 topology_manager.go:200] "Topology Admit Handler"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204848    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204859    2011 topology_hints.go:49] "Resource does not have a topology preference" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204873    2011 scope_container.go:77] "TopologyHints" hints=map[openshift.io/dpdk_nic_1:[]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204880    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204928    2011 policy_static.go:437] "TopologyHints generated" pod="default/testpmd" containerName="dpdk" cpuHints=[{NUMANodeAffinity:01 Preferred:true}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204941    2011 scope_container.go:77] "TopologyHints" hints=map[cpu:[{NUMANodeAffinity:01 Preferred:true}]] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204949    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204957    2011 scope_container.go:77] "TopologyHints" hints=map[] pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204964    2011 policy.go:78] "Hint Provider has no preference for NUMA affinity with resource" resource="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204971    2011 policy.go:70] "Hint Provider has no preference for NUMA affinity with any resource"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204979    2011 scope_container.go:85] "ContainerTopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true}
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204987    2011 scope_container.go:54] "Best TopologyHint" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.204995    2011 scope_container.go:59] "Topology Affinity" bestHint={NUMANodeAffinity:01 Preferred:true} pod="default/testpmd" containerName="dpdk"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205009    2011 manager.go:914] "Looking for needed resources" needed=1048576000 resourceName="memory"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205016    2011 manager.go:914] "Looking for needed resources" needed=1 resourceName="openshift.io/dpdk_nic_1"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205024    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205037    2011 manager.go:694] "Found pre-allocated devices for resource on pod" resourceName="openshift.io/dpdk_nic_1" containerName="dpdk" podUID="c7dcb25a-6b71-4f80-9482-053ea597230c" devices=[0000:00:05.0]
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205044    2011 manager.go:914] "Looking for needed resources" needed=2 resourceName="cpu"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205050    2011 manager.go:914] "Looking for needed resources" needed=1073741824 resourceName="hugepages-1Gi"
Apr 13 09:53:17 TESTNODE hyperkube[2011]: I0413 09:53:17.205060    2011 config.go:97] "Looking for sources, have seen" sources=[api file] seenSources=map[file:{}]
```
When the topology manager requests device allocation, we end up in the devicemanager's [devicesToAllocate](https://github.com/kubernetes/kubernetes/blob/v1.24.0-rc.0/pkg/kubelet/cm/devicemanager/manager.go#L686) function. This function checks if there already a pre-allocated device (and there is, thanks to the recovered data), and if so exits early, skipping the health check which would have failed, because the device plugin has not re-registered itself yet.

The end result is that containers can be admitted and start running without the requested device actually available, causing runtime errors in the workload.

### What did you expect to happen?

The kubelet should reject the admission of the pod until the device plugins re-registered themselves; then the pods requiring devices should be processed again. This seems the only meaningful way to recover pods while taking in consideration the actualy health of the devices.

### How can we reproduce it (as minimally and precisely as possible)?

The behaviour here depends on the order on which pods are recovered, so it's essentially a race.

1. run a test pod requiring devices. Make sure this test pod clearly fails if the requested devices are not available
2. restart the node (can take few attempts)
3. check the health of the test pod

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
kubelet 1.23.3
likely happening on current master
```
</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In case of node reboot/kubelet restart, the flow of events involves obtaining the state from the checkpoint file followed by setting the `healthDevices`/`unhealthyDevices` to its zero value. This is done to allow the device plugin to re-register itself so that capacity can be updated appropriately.

During the allocation phase, we need to check if the resources requested by the pod have been registered AND healthy devices are present on the node to be allocated.

Also we need to move this check above `needed==0` where needed is required - devices allocated to the container (which is obtained from the checkpoint file) because even in cases where no additional devices have to be allocated (as they were pre-allocated), we still need to make sure that the devices that were previously allocated are healthy.

For more details refer to the comment here: https://github.com/kubernetes/kubernetes/issues/109595#issuecomment-1359882423.

#### Which issue(s) this PR fixes:

Fixes #109595 and (possibly) #107928 (TODO: need to check the latter)
#### Special notes for your reviewer:

**NOTE: This PR depends on sample device plugin changes proposed in: https://github.com/kubernetes/kubernetes/pull/115107**. 
Those changes are included here (first two commits) as they are needed for e2e test implementation.

NOTE: On node reboot, in case the application pod requesting devices starts after the device plugin pod providing those devices as has been described in https://github.com/kubernetes/kubernetes/issues/109595 and https://github.com/kubernetes/kubernetes/issues/107928 we exit early as there are pre-allocated devices without checking if the devices have registered and are healthy. This PR adds both those checks.

Because of this change, in cases where application pods are started before device plugin pod (say after node reboot),  because devices are not healthy, the pod would fail with `UnexpectedAdmissionError` error.  If the pod is part of a deployment, another pod would be created but that would stay in `Pending` state waiting for the pod to be scheduled to the node. This pod would go `Running` after the node capacity is updated followed by start up of device plugin pod and its registration.

The pod which fails at admission time continues to exist on the node and needs to be removed manually:
```
kubectl delete pods --field-selector status.phase=Failed
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

original release note:
```
During device plugin allocation, resources requested by the pod can only be allocated if the device plugin has registered itself to kubelet AND healthy devices are present on the node to be allocated. If these conditions are not sattsfied, the pod would fail with `UnexpectedAdmissionError` error.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fromanirh** [comment]
partially replaces #110729 - I'm going to close the latter when tests are added here

File: test/e2e_node/device_manager_test.go [hunk 1]
```diff
@@ -266,6 +272,181 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+				return nodes == 1
+			}, 2*time.Minute, time.Second).Should(gomega.BeTrue())
+
+			// TODO: here we need to tolerate pods waiting to be recreated
+
+			ginkgo.By("making sure all the pods are ready after the recovery")
+
+			var devicePluginPodAfterRestart, tmpPod *v1.Pod
+
+			devicePluginPodAfterRestart, err = e2epod.NewPodClient(f).Get(ctx, devicePluginPod.Name, metav1.GetOptions{})
```
Comment (yanirq) [inline test/e2e_node/device_manager_test.go:404]: lint error: ineffectual assignment to err (ineffassign)

File: test/e2e_node/device_manager_test.go [hunk 2]
```diff
@@ -266,6 +272,131 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 		})
 
 	})
+
+	ginkgo.Context("With sample device plugin", func(ctx context.Context) {
```
Comment (Tal-or) [inline test/e2e_node/device_manager_test.go:276]: You should not pass context as an argument to the anonymous function.
From the `node-e2e-containerd` CI lane failure:
```
W1227 11:58:05.859]   Invalid Function
W1227 11:58:05.859]   test/e2e_node/device_manager_test.go:276
W1227 11:58:05.859]     [Container] node must be passed func() - i.e. functions that take nothing and
W1227 11:58:05.860]     return nothing.  You passed func(context.Context) instead.
W1227 11:58:05.860] 
W1227 11:58:05.860]     Learn more at: http://onsi.github.io/ginkgo/#node-decorators-overview
```

File: test/e2e_node/device_manager_test.go [hunk 3]
```diff
@@ -266,6 +272,131 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+		var deviceCount int = 2
+		var devicePluginPod *v1.Pod
+		var testPods []*v1.Pod
+
```
Comment (Tal-or) [inline test/e2e_node/device_manager_test.go:279]: add `ctx := context.Background()` in order to use context across the test

**Comment by klueska** [comment]
The description says this is still WIP. Please let me know when it it ready for me to do a final review.

**Comment by swatisehgal** [comment]
> The description says this is still WIP. Please let me know when it it ready for me to do a final review.

Thanks @klueska for pointing that out. I have updated the description as tests have been added and the  PR is ready for review.

**Comment by SergeyKanzhelev** [comment]
/assign @fromanirh

Can you do initial review?

**Comment by ffromani** [comment]
> /assign @fromanirh
> 
> Can you do initial review?

on it (Renamed fromanirh -> ffromani)

File: test/images/sample-device-plugin/sampledeviceplugin.go [hunk 4]
```diff
@@ -84,14 +92,59 @@ func main() {
...
+
+		klog.InfoS("Starting to accept connections")
+		// Accept new connections
+		conn, err := l.Accept()
+		if err != nil {
+			panic(err)
+		}
+
+		defer conn.Close()
+		io.Copy(conn, conn)
```
Comment (ffromani) [inline test/images/sample-device-plugin/sampledeviceplugin.go:144]: why is this needed?

File: test/e2e_node/image_list.go [hunk 5]
```diff
@@ -47,7 +47,8 @@ const (
 	maxParallelImagePullCount = 5
 
 	// SampleDevicePluginDSYAML is the path of the daemonset template of the sample device plugin. // TODO: Parametrize it by making it a feature in TestFramework.
-	SampleDevicePluginDSYAML = "test/e2e/testing-manifests/sample-device-plugin.yaml"
+	SampleDevicePluginDSYAML  = "test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-auto-registration.yaml"
+	SampleDevicePluginDS2YAML = "test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml"
```
Comment (ffromani) [inline test/e2e_node/image_list.go:51]: `DS2` is a bit cryptic :) Perhaps `SampleDevicePluginControlRegistrationDSYAML`?
In general let's pick a name which is a bit more explicit about the purpose, at cost of being longer.
I think it's ok to keep the old name to cover the simpler existing cases on which the auto-registering DP is fine: tests that will need this amount of control are gonna be fewer.

File: test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+        hostPath:
+          path: /var/lib/kubelet/device-plugins
+      - name: plugins-registry-probe-mode
+        hostPath:
+          path: /var/lib/kubelet/plugins_registry
+      - name: dev
+        hostPath:
+          path: /dev
+      containers:
+      - image: registry.k8s.io/e2e-test-images/sample-device-plugin:1.3
```
Comment (ffromani) [inline test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml:35]: I think we will need to bump the device plugin version, which can complicate the matters, but let's check.

File: test/e2e_node/device_manager_test.go [hunk 7]
```diff
@@ -266,6 +272,131 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+			restartKubelet(true)
+
+			ginkgo.By("Waiting for devices to become unavailable on the local node")
+			gomega.Eventually(func() bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready && numberOfSampleResources(node) <= 0
+			}, 5*time.Minute, framework.Poll).Should(gomega.BeTrue())
+		})
+
+		ginkgo.It("should recover device plugin pod first, then pod consuming devices", func() {
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go]: disclosure: I authored the original commit.
The problem here is handling races. I didn't find a good way to handle them, thus give a reliable signal with this test. Let's see how subsequent commits address this problem.

**Review by ffromani — COMMENTED** [review]
initial review. I need to spend more time digesting the e2e test

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 8]
```diff
@@ -544,16 +544,25 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
...
 
+	// Check if registered resource has healthy devices
+	if healthyDevices.Len() == 0 {
+		return nil, fmt.Errorf("can't allocate unhealthy devices %s", resource)
+	}
+
+	if needed == 0 {
+		// No change, no work.
+		return nil, nil
+	}
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:564]: I am open to pursuing alternative approaches. I wanted us to have a starting point to convey the idea with the least invasive approach to tackle the issue. Will have a bit more about this in the coming days.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 9]
```diff
@@ -544,16 +544,25 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
...
-		// No change, no work.
-		return nil, nil
-	}
+
 	klog.V(3).InfoS("Need devices to allocate for pod", "deviceNumber", needed, "resourceName", resource, "podUID", string(podUID), "containerName", contName)
+	healthyDevices, hasRegistered := m.healthyDevices[resource]
+
 	// Check if resource registered with devicemanager
-	if _, ok := m.healthyDevices[resource]; !ok {
+	if !hasRegistered {
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:552]: Sure, we can do that and these are feasible options option but wanted to propose the least invasive change and go from there.

I believe, above and near `isDevicePluginResource` shouldn't be any problem but if we perform this check _in_  the `isDevicePluginResource`, we would be modifying the semantics and there are a few considerations:

1. If we return false for a device plugin resource that had previously registered and are not healthy, we are silently changing the semantics of `isDevicePluginResource`. The problem with this approach could be that  we are changing the semantics of this function and with the current implementation the pod would silently skip resource allocation rather than an explicit admission error (as it also includes cases corresponding to extended resources). 

1. If we modify `isDevicePluginResource`  to return an err and add the check there we should be okay. This way the case would manifest itself as an admission error but  we would have to perform this check at multiple places but we are expanding the scope from just allocation to hint generation logic as well which is not a problem but it is something worth noting.

File: test/images/sample-device-plugin/sampledeviceplugin.go [hunk 10]
```diff
@@ -84,14 +92,59 @@ func main() {
...
+		autoRegister = true
+	} else {
+
+		autoRegister, err = strconv.ParseBool(autoRegisterString)
+		if err != nil {
+			klog.Errorf("invalid boolean value specified")
+			panic(err)
+		}
+
+	}
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go:107]: Absolutely, Thanks!

File: test/images/sample-device-plugin/sampledeviceplugin.go (hunk 4 above)
Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go:144]: I recall playing around with handling connections in separate goroutines but later made changes and this might be a reminiscence of that. Will remove it.

File: test/e2e_node/image_list.go (hunk 5 above)
Comment (swatisehgal) [reply test/e2e_node/image_list.go:51]: Sure, will update.

File: test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml (hunk 6 above)
Comment (swatisehgal) [reply test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml:35]: I am not very familiar with the sample-device-plugin image build process, will look into that. We would have to make sure that the image gets built with right tag is provided here.

File: test/e2e_node/device_manager_test.go (hunk 7 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go]: I  summarize the steps involved in the e2e test implementation in the commit message. Let me know if I can help in better understanding here.

File: test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml (hunk 6 above)
Comment (ffromani) [reply test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml:35]: ok, the trick here is that tests will consume the existing image already pushed in the registry. It's possible we will need to split the related commits to its own PR, then once merged, push a new sample-device-plugin image and finally consume it in the e2e tests here.
I'm not sure we can just bundle the changes and consume them in the same PR. Let's check.

File: test/e2e_node/device_manager_test.go [hunk 11]
```diff
@@ -302,6 +302,17 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 
 			devicePluginPod = e2epod.NewPodClient(f).CreateSync(ctx, dp)
 
+			go func() {
+				// Write to the Unix socket to trigger registration in a separate thread
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:306]: let's spend words describing "why" (if not obvious) rather than "how"

File: test/e2e_node/device_manager_test.go [hunk 12]
```diff
@@ -319,45 +330,20 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
-
-			ginkgo.By("Waiting for devices to become unavailable on the local node")
-			gomega.Eventually(func() bool {
-				node, ready := getLocalTestNode(ctx, f)
-				return ready && numberOfSampleResources(node) <= 0
-			}, 5*time.Minute, framework.Poll).Should(gomega.BeTrue())
-		})
-
-		ginkgo.It("should recover device plugin pod first, then pod consuming devices", func() {
+		ginkgo.It("should recover device plugin pod first, then pod consuming devices", func(ctx context.Context) {
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:333]: is the `It` description still faithful to the intent of the code?

File: test/e2e_node/device_manager_test.go [hunk 13]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
-			waitForPodConditionBatch(ctx, f, testPods, "Ready", 120*time.Second, testutils.PodRunningReady)
 
-			ginkgo.By("removing all the pods")
-			deleteBatch(ctx, f, testPods)
+			var devicePluginPodAfterRestart, tmpPod *v1.Pod
+
+			devicePluginPodAfterRestart, err = e2epod.NewPodClient(f).Get(ctx, devicePluginPod.Name, metav1.GetOptions{})
+			framework.ExpectNoError(err)
+
+			err = e2epod.WaitForPodCondition(ctx, f.ClientSet, devicePluginPodAfterRestart.Namespace, testPod.Name, "Ready", 120*time.Second, testutils.PodRunningReady)
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:384]: is this correct? we are mixing Namespace and Name and is not obvious why. Perhaps you meant to use `devicePluginPodAfterRestart.Name` here?

File: test/e2e_node/device_manager_test.go [hunk 14]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+			framework.ExpectNoError(err, "pod %s/%s did not go running", devicePluginPodAfterRestart.Namespace, devicePluginPodAfterRestart.Name)
+			framework.Logf("pod %s/%s running", devicePluginPodAfterRestart.Namespace, devicePluginPodAfterRestart.Name)
+
+			var devsLen int64
+			ginkgo.By("Waiting for the resource capacity/allocatable exported by the sample device plugin to become zero")
+			gomega.Eventually(func() bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready &&
+					numberOfDevicesCapacity(node, resourceName) == devsLen &&
+					numberOfDevicesAllocatable(node, resourceName) == devsLen
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:394]: this looks correct, but I'd use explicit 0 to be more obvious

File: test/e2e_node/device_manager_test.go [hunk 15]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 				nodes, err := e2enode.TotalReady(ctx, f.ClientSet)
 				framework.ExpectNoError(err)
 				return nodes == 1
-			}, time.Minute, time.Second).Should(gomega.BeTrue())
+			}, 2*time.Minute, time.Second).Should(gomega.BeTrue())
 
 			// TODO: here we need to tolerate pods waiting to be recreated
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:375]: not sure this TODO is still relevant

File: test/e2e_node/device_manager_test.go [hunk 16]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+			var devsLen int64
+			ginkgo.By("Waiting for the resource capacity/allocatable exported by the sample device plugin to become zero")
+			gomega.Eventually(func() bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready &&
+					numberOfDevicesCapacity(node, resourceName) == devsLen &&
+					numberOfDevicesAllocatable(node, resourceName) == devsLen
+			}, 30*time.Second, framework.Poll).Should(gomega.BeTrue())
+
+			ginkgo.By("Checking that pod requesting devices failed to start because of admission error")
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:397]: I'd add a comment to emphasize that the registration won't happen again. We did it (racingly?) in the `beforeeach` block, which runs once the registration of the restarted device plugin won't happen unless we explicitely issue the command - and we don't want to!

File: test/e2e_node/device_manager_test.go [hunk 17]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+
+				if tmpPod.Status.Phase != v1.PodFailed {
+					return false
+				}
+
+				if tmpPod.Status.Reason != "UnexpectedAdmissionError" {
+					return false
+				}
+
+				if !strings.Contains(tmpPod.Status.Message, "Allocate failed due to can't allocate unhealthy devices") {
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:410]: this is a bit ugly and fragile, but I don't have better suggestions at this point :\

File: test/e2e_node/device_manager_test.go [hunk 18]
```diff
@@ -384,15 +370,78 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+			ginkgo.By("Waiting for the resource capacity/allocatable exported by the sample device plugin to become zero")
+			gomega.Eventually(func() bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready &&
+					numberOfDevicesCapacity(node, resourceName) == devsLen &&
+					numberOfDevicesAllocatable(node, resourceName) == devsLen
+			}, 30*time.Second, framework.Poll).Should(gomega.BeTrue())
+
+			ginkgo.By("Checking that pod requesting devices failed to start because of admission error")
+			gomega.Eventually(ctx, func() bool {
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:398]: we should also probably spend few lines explaining what is the expected scenario is and how it unfolds. For example:
we now have exactly two pods running, device plugin pod and test pod. We can't control the recovery order.
if the test pod is recovered before the device plugin pod, great: that's exactly the scenario we want to exercise.
If the device plugin pod is recovered before the test pod, we still can meaningfully reproduce the scenario by NOT sending the registration command.

File: test/e2e_node/device_manager_test.go [hunk 19]
```diff
@@ -483,41 +532,10 @@ func stringifyContainerDevices(devs []*kubeletpodresourcesv1.ContainerDevices) s
...
-		}(pod.Namespace, pod.Name)
-	}
-	wg.Wait()
-}
-
 func makeBusyboxDeviceRequiringPod(resourceName, cmd string) *v1.Pod {
 	podName := "device-manager-test-" + string(uuid.NewUUID())
 	rl := v1.ResourceList{
-		v1.ResourceName(resourceName): *resource.NewQuantity(1, resource.DecimalSI),
+		v1.ResourceName(resourceName): *resource.NewQuantity(2, resource.DecimalSI),
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:538]: could you please elaborate why we need 2 here?

**Review by ffromani — COMMENTED** [review]
completed the review. The pending question now is if this fix can have unintended consequences, which I think boil down to have previosuly silently broken recovery now explicitely broken. I would call this an improvement, but still can cause some surprises.

File: test/e2e_node/device_manager_test.go (hunk 12 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:333]: Thanks for identifying this, will fix.

File: test/e2e_node/device_manager_test.go (hunk 13 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:384]: That's right! Thanks.

File: test/e2e_node/device_manager_test.go (hunk 14 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:394]: Sure, will do that.

File: test/e2e_node/device_manager_test.go (hunk 15 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:375]: Yes, it needs to be removed.

File: test/e2e_node/device_manager_test.go (hunk 16 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:397]: Sure! Will do.

File: test/e2e_node/device_manager_test.go (hunk 17 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:410]: Yeah, unfortunately. I couldn't come up with a better solution for this either.

File: test/e2e_node/device_manager_test.go (hunk 18 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:398]: Sure, I will explain this in more detail.

File: test/e2e_node/device_manager_test.go (hunk 19 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:538]: We don't HAVE to provide it 2 resources but since the the sample device plugin exposes 2 devices and we have a single testpod, I give it all the resources.  

We had requested a single device in the previous commit ([5919f](https://github.com/kubernetes/kubernetes/pull/114640/commits/5919faacad20bff699c95b632875833f99773dd8)) where 2 test pods were created requesting a device each. But for this e2e a single test pod is enough.

**Comment by swatisehgal** [comment]
> completed the review. The pending question now is if this fix can have unintended consequences, which I think boil down to have previosuly silently broken recovery now explicitely broken. I would call this an improvement, but still can cause some surprises.

This is a valid point. Perhaps we should update the release note with this information to avoid surprises.

File: test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml (hunk 6 above)
Comment (swatisehgal) [reply test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml:35]: Yes, that could be the case here. I will look into how this was done previously.

Comment (swatisehgal) [reply test/e2e/testing-manifests/sample-device-plugin/sample-device-plugin-control-registration.yaml:35]: I will bump the sample device plugin version, point to that in the manifests and let's see how the CI reacts. That should give us an indication if the changes related to sample device plugin should be moved to a separate PR.

**Review by ffromani — COMMENTED** [review]
/lgtm
Few inline non-blocking comments. I can't think of any improvement to better tackle this issue.
The only missing item is: what's the best way to make changes to the sample device plugin? do we need to split them to a separate PR, have it merged, update the image in the registry and only then consume the changes in the e2e test? I dunno myself

File: test/e2e_node/device_manager_test.go [hunk 20]
```diff
@@ -328,7 +328,7 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 			}, time.Minute, time.Second).Should(gomega.BeTrue())
 
 			ginkgo.By("Scheduling a sample device plugin pod")
-			data, err := e2etestfiles.Read(SampleDevicePluginDS2YAML)
+			data, err := e2etestfiles.Read(SampleDevicePluginControlRegistrationDSYAML)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:331]: Ack, will do!

File: test/images/sample-device-plugin/sampledeviceplugin.go [hunk 21]
```diff
@@ -84,14 +91,54 @@ func main() {
...
+		defer l.Close()
+
+		sigc := make(chan os.Signal, 1)
+		signal.Notify(sigc, os.Interrupt, syscall.SIGTERM)
+		go func(ln net.Listener, c chan os.Signal) {
+			sig := <-c
+			klog.Infof("Received termination signal %s: shutting down.", sig)
+			ln.Close()
+			os.Exit(0)
+		}(l, sigc)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/images/sample-device-plugin/sampledeviceplugin.go:129]: Added it primarily to comply with best practices.

**Comment by swatisehgal** [comment]
> The only missing item is: what's the best way to make changes to the sample device plugin? do we need to split them to a separate PR, have it merged, update the image in the registry and only then consume the changes in the e2e test? I dunno myself

I don't understand the process about pushing images in great detail but after a bit of digging came across an [Image Promoter KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/1734-k8s-image-promoter) that describes the image promotion [process](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/1734-k8s-image-promoter#promotion-process) which says that that maintainers are supposed to submit a PR to add a new image. I am not sure at what stage that happens and would need some guidance here.

Splitting this into two PRs is not a problem given that we are preserving the default behavior (auto-registration). My concern is that sample device plugin change made here is motivated by being able to reproduce this bug and without the rationale captured and solved in this bug, the changes independently might be hard to digest and justify?

Since splitting this into two PRs is straightforward, I will reorganized the commits and move the sample device plugin changes to a separate PR. We can proceed further based on approach suggested by other reviewers/approvers.

**Comment by ffromani** [comment]
> > The only missing item is: what's the best way to make changes to the sample device plugin? do we need to split them to a separate PR, have it merged, update the image in the registry and only then consume the changes in the e2e test? I dunno myself
> 
> I don't understand the process about pushing images in great detail but after a bit of digging came across an [Image Promoter KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/1734-k8s-image-promoter) that describes the image promotion [process](https://github.com/kubernetes/enhancements/tree/master/keps/sig-release/1734-k8s-image-promoter#promotion-process) which says that that maintainers are supposed to submit a PR to add a new image. I am not sure at what stage that happens and would need some guidance here.
> 
> Splitting this into two PRs is not a problem given that we are preserving the default behavior (auto-registration). My concern is that sample device plugin change made here is motivated by being able to reproduce this bug and without the rationale captured and solved in this bug, the changes independently might be hard to digest and justify?
> 
> Since splitting this into two PRs is straightforward, I will reorganized the commits and move the sample device plugin changes to a separate PR. We can proceed further based on approach suggested by other reviewers/approvers.

SGTM, thanks for look into this.

File: test/e2e_node/device_manager_test.go [hunk 22]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+		meaningfully reproduce the scenario by NOT sending the registration command.
+		To do so sample device plugin is enhanced. For implementation details, refer to:
+		`test/images/sample-device-plugin/sampledeviceplugin.go`. This enhancement
+		allows auto-registration of the plugin to be controlled with the help of an environment
+		variable: AUTO_REGISTER. By default AUTO_REGISTER=true allowing the device plugin
+		to autoregister to kubelet. For this e2e test, we use sample device plugin
+		spec with AUTO_REGISTER=false to first manually register the plugin to allow
+		an application pod (requesting devices) to successfully run on the node
+		followed by kubelet restart where device plugin doesn't register and the
+		application pod fails with admission error.
```
Comment (bart0sh) [inline test/e2e_node/device_manager_test.go:299]: Can we achieve the same result by not starting device plugin after the kubelet restart?

Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:299]: The device plugin and the application pod are recovered automatically after kubelet restart. We cannot influence the device plugin pod start-up as the order in which the pods are recovered is not in our control.

Comment (bart0sh) [reply test/e2e_node/device_manager_test.go:299]: Now it makes sense to me. Thanks for the explanations.

Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:299]: No problem!

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 23]
```diff
@@ -544,16 +544,25 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
...
+	// Check if registered resource has healthy devices
+	if healthyDevices.Len() == 0 {
+		return nil, fmt.Errorf("can't allocate unhealthy devices %s", resource)
+	}
+
+	if needed == 0 {
+		// No change, no work.
+		return nil, nil
+	}
+
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager.go:565]: As far as I can tell, this is the only "core" change (and it seems reasonable / logical).
The rest are changes to testing, is that correct?

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: Actually, I have one question here -- your PR description mentioned that you wanted to check that all already-allocated devices were in fact healthy (and error out otherwise). I don't see this logic here. What you have in this PR is strictly better than what we had before, but I'm curious if this check was left out on purpose or overlooked.

Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: > As far as I can tell, this is the only "core" change (and it seems reasonable / logical).
The rest are changes to testing, is that correct?

Yes, this is accurate. Please note that https://github.com/kubernetes/kubernetes/pull/115107 would need to merge first as we need that for e2e tests implementation here. Also, due to some suggestions on that PR I have proposed a file based synchronization approach (as [3rd commit](https://github.com/kubernetes/kubernetes/pull/115107/commits/2aabf15c370ca727067f550a7ff225ec6d85af57) on that PR) diverging slightly sample device plugin changes in these two PRs temporarily. Once we reach consensus on that, I will rebase.

> Actually, I have one question here -- your PR description mentioned that you wanted to check that all already-allocated devices were in fact healthy (and error out otherwise). I don't see this logic here. What you have in this PR is strictly better than what we had before, but I'm curious if this check was left out on purpose or overlooked.

The change here: 
https://github.com/kubernetes/kubernetes/pull/114640/commits/6d80d27b8204b32b82da4e6ad3c10855327d36b0#diff-623f1164bd7d648ee0421742187c76b5071b44315aee695f29edc0203b6c762dR556-R559 is implementing that logic.
Previously, while iterating through `m.healthyDevices` we **only** checked if devices had registered which meant that it was okay to proceed forward with allocation if we had devices that previously registered even if they are unhealthy (and therefore unsuitable to be allocated after reboot either because the device plugin pod didn't started or didn't register itself yet to kubelet) .
Now, we obtain the list of `healthyDevices`, check its length to validate the presence of healthy devices and rule out `healthyDevices` with zero length as that is the case that corresponds to registered **unhealthy** devices. We only proceed to allocation if both these conditions are met ensuring that these devices are actually healthy and don't just appear to be because at some stage they had registered to kubelet.

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: Maybe I misinterpreted what you meant then.

I thought you were saying you planned to validate that all of the already-allocated devices (i.e. those present in the `devices` variable at this point in the code) are healthy. The check you have in place just ensures that "at least one" device is healthy, but not that the full set of already-allocated devices are all healthy.

Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: I see what you mean, we can add a check to make sure that the `devices` retrieved from the checkpoint file are healthy as well.

I had been working under the assumption that nothing changes in the environment and once the device plugin has registered we would have enough devices to fulfill the pod resource requirement. I now see you have a valid point, we could have a case where a device plugin might have  re-registered but there aren't enough healthy devices e.g. a node had two NICs and devices are allocated from two NIC to a pod but one of them was removed before node reboot.

We can improve the current implementation by checking that there are at least `devices.Len()` number of devices instead of the current naive check of "at least one" healthy device. Also, we would have to check if `devices` is a subset of `healthyDevices`.

The only case that I want like to explicitly point out is where devices previously allocated (and thus retrieved from the checkpoint) are not healthy anymore but there are enough devices that can be allocated to the pod. In that case as well we would be returning an admission error. I think that is fair because without that we would proceed as normal but the pod would fail when it will try to access unhealthy devices "allocated" to it.

Let me know if that makes sense.

Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: Thought about this a bit more...
After node reboot, for all the registered devices  `m.healthyDevices` field is reset to zero because of which device capacity is 0. This is intentional as we want to prevent additional pods requesting devices to be scheduled on the node.  

Since `devices` is not empty, we check if additional resources need to be allocated`needed = needed - devices.Len()`

it is sufficient to check if healthyDevices.len is zero as that is an indication of the device plugin not being registered.

Since `healthyDevices` is empty we can't cross check if the devices retrieved are healthy or not.

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: I was talking about the state of things after ensuring that healthyDevices.Len() > 0 (and consequently before checking if needed == 0).

The set of already-allocated-devices at this point are just assumed to all be healthy if we don’t explicitly check for this. 

I’m just wondering if we want to cross check them against the set of devices in healthyDevices and if they are not all there, we error out.

Comment (swatisehgal) [reply pkg/kubelet/cm/devicemanager/manager.go:565]: I see, I will handle that case as well. Thanks.

**Comment by klueska** [comment]
/approve
/hold

The core change looks good to me. I haven't looked closely at the updates to the tests, but if other sig-node reviewers are happy with the changes there, feel free to add an LGTM and remove the hold.

**Comment by swatisehgal** [comment]
> /approve /hold
> 
> The core change looks good to me. I haven't looked closely at the updates to the tests, but if other sig-node reviewers are happy with the changes there, feel free to add an LGTM and remove the hold.

Thanks @klueska!

/assign @pohly @aojea
for review/approval on test related changes

File: test/e2e_node/device_manager_test.go [hunk 24]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+
+				_, err = conn.Write([]byte("registering"))
+				framework.ExpectNoError(err)
+			}()
+
+			ginkgo.By("Waiting for devices to become available on the local node")
+			gomega.Eventually(func() bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready && numberOfSampleResources(node) > 0
+			}, 5*time.Minute, framework.Poll).Should(gomega.BeTrue())
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:365]: `BeTrue` is not going to be informative. You can use https://pkg.go.dev/github.com/onsi/gomega/gcustom to write a better one for this particular check.

**Review by pohly — CHANGES_REQUESTED** [review]
I pointed out some areas where the tests could be improved. The same comments apply in multiple places, I stopped repeating them at some point.

File: test/e2e_node/device_manager_test.go [hunk 25]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+		   11. Delete the sample device plugin pod.
+	*/
+	ginkgo.Context("With sample device plugin", func() {
+		var deviceCount int = 2
+		var devicePluginPod *v1.Pod
+
+		// this test wants to reproduce what happened in https://github.com/kubernetes/kubernetes/issues/109595
+		ginkgo.BeforeEach(func(ctx context.Context) {
+			ginkgo.By("Wait for node to be ready")
+			gomega.Eventually(func() bool {
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:324]: Ack, Thanks!

File: test/e2e_node/device_manager_test.go [hunk 26]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+				ObjectMeta: metav1.ObjectMeta{
+					Name: sampleDevicePluginName,
+				},
+				Spec: ds.Spec.Template.Spec,
+			}
+
+			devicePluginPod = e2epod.NewPodClient(f).CreateSync(ctx, dp)
+
+			go func() {
+				// Since autoregistration is disabled for the device plugin (as AUTO_REGISTER=false),
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:347]: Thanks, will address.

File: test/e2e_node/device_manager_test.go [hunk 27]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+				// device plugin registration needs to be triggerred manually.
+				// This is done by writing to the Unix socket exposed at:
+				// `/var/lib/kubelet/device-plugins/registered`.
+
+				triggerPath := devicePluginDir + "/registered"
+				conn, err := net.Dial("unix", triggerPath)
+				framework.ExpectNoError(err)
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:354]: Yes, that is what I was hoping for.

File: test/e2e_node/device_manager_test.go [hunk 28]
```diff
@@ -266,6 +272,231 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+		var devicePluginPod *v1.Pod
+
+		// this test wants to reproduce what happened in https://github.com/kubernetes/kubernetes/issues/109595
+		ginkgo.BeforeEach(func(ctx context.Context) {
+			ginkgo.By("Wait for node to be ready")
+			gomega.Eventually(func() bool {
+				nodes, err := e2enode.TotalReady(ctx, f.ClientSet)
+				framework.ExpectNoError(err)
+				return nodes == 1
+			}, time.Minute, time.Second).Should(gomega.BeTrue())
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:328]: Thanks, I will address this.

File: test/e2e_node/device_manager_test.go (hunk 24 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:365]: Can you elaborate on what you would like to be done here. You want me to write up a custom matcher here?

We come to the conclusion that a node is ready if:

1. node status is ready
2. network is setup ( which is done by checking `NetworkUnavailable` condition is not true) 
3. node is not unschedulable
4. device plugin advertises resources on the node

Point 1-3 are exactly what [getLocatTestNode](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/util.go#L263-L270) does for us. I know it is not ideal that this is returned as a boolean and it would probably be better to have a custom matcher that allows us to `.Should(BeReady)` but that would mean we are reimplmenting a lot of code and I am not sure if that is the best approach.

Comment (pohly) [reply test/e2e_node/device_manager_test.go:365]: I see that [getLocatTestNode](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/util.go#L263-L270) is basically a combination of "get node",  `e2enode.IsNodeReady` and `e2enode.IsNodeSchedulable`.

A good solution would be to:
- get the node in the `Eventually` callback
- rewrite `IsNodeReady` and `IsNodeSchedulable` as gomega matchers
- use `gomega.SatisfyAll` with those

But I understand that this is probably more work than you can afford or want to invest.

Some intermediate solution would be to get the node, then use a matcher based on gcustom which invokes `getLocatTestNode` with a failure message that explains the boolean.

Comment (pohly) [reply test/e2e_node/device_manager_test.go:365]: You can look at e2epod for inspiration. It was recently rewritten to use such a pattern.

File: test/e2e_node/device_manager_test.go [hunk 29]
```diff
@@ -351,3 +579,98 @@ func stringifyContainerDevices(devs []*kubeletpodresourcesv1.ContainerDevices) s
...
+	}
+
+	if numberOfSampleResources(node) <= 0 {
+		return false, fmt.Errorf("Expected devices to be advertised")
+	}
+	return true, nil
+}
+
+// HaveAllocatableDevices verifies that a node has allocatable devices.
+func HaveAllocatableDevices(ctx context.Context, f *framework.Framework) types.GomegaMatcher {
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:642]: The parameters are unused?

File: test/e2e_node/device_manager_test.go [hunk 30]
```diff
@@ -351,3 +579,98 @@ func stringifyContainerDevices(devs []*kubeletpodresourcesv1.ContainerDevices) s
...
+					Limits:   rl,
+					Requests: rl,
+				},
+			}},
+		},
+	}
+}
+
+// BeReady verifies that a node is ready and devices have registered.
+func BeReady(ctx context.Context, f *framework.Framework) types.GomegaMatcher {
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:609]: The parameters are unused?

File: test/e2e_node/device_manager_test.go [hunk 31]
```diff
@@ -266,6 +273,227 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+
+				framework.Logf("Deleting pod: %s", p.Name)
+				e2epod.NewPodClient(f).DeleteSync(ctx, p.Name, metav1.DeleteOptions{}, 2*time.Minute)
+			}
+
+			ginkgo.By("Waiting for devices to become unavailable on the local node")
+			gomega.Eventually(ctx, func(ctx context.Context) bool {
+				node, ready := getLocalTestNode(ctx, f)
+				return ready && numberOfSampleResources(node) <= 0
+			}, 5*time.Minute, framework.Poll).Should(gomega.BeTrue())
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:492]: Here's another candidate for replacing `gomega.BeTrue` with a matcher :sweat_smile:

File: test/e2e_node/device_manager_test.go [hunk 32]
```diff
@@ -266,6 +273,227 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+					return false
+				}
+
+				if !strings.Contains(tmpPod.Status.Message, "Allocate failed due to can't allocate unhealthy devices") {
+					return false
+				}
+
+				return true
+			}, time.Minute, 5*time.Second).Should(
+				gomega.Equal(true),
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:464]: Here's another candidate for replacing gomega.BeTrue with a matcher sweat_smile

File: test/e2e_node/device_manager_test.go (hunk 29 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:642]: Right, will update.

File: test/e2e_node/device_manager_test.go (hunk 31 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go:492]: I missed this one, will update now.

**Comment by swatisehgal** [comment]
Force pushed as I rebased the PR.

File: test/e2e_node/device_manager_test.go [hunk 33]
```diff
@@ -266,6 +273,211 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
...
+				defer ginkgo.GinkgoRecover()
+				triggerPath := devicePluginDir + "/registered"
+				err := os.RemoveAll(triggerPath)
+				framework.ExpectNoError(err)
+			}()
+
+			ginkgo.By("Waiting for devices to become available on the local node")
+
+			gomega.Eventually(ctx, isNodeReadyWithSampleResources).
+				WithArguments(ctx, f).
```
Comment (pohly) [inline test/e2e_node/device_manager_test.go:361]: Don't pass `ctx` as argument. `gomega.Eventually` will handle that automatically.

I find it easier to write:
```
gomega.Eventually(ctx, isNodeReadyWithSampleResources, f).
```
without the `WithArguments`

Comment (pohly) [reply test/e2e_node/device_manager_test.go:361]: This also applies below.

**Review by pohly — CHANGES_REQUESTED** [review]
One small nit, otherwise very nice usage of `gomega.Eventually`.

But someone else will have to LGTM, there are too many parts that I am not familiar with.

File: test/e2e_node/device_manager_test.go (hunk 33 above)
Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go]: Thanks, I am not passing `ctx` as argument in the `WithArguments` anymore. 

I tried playing around with the approach of not using `WithArguments` as per your suggestion but the test fails without it.

**Comment by swatisehgal** [comment]
> But someone else will have to LGTM, there are too many parts that I am not familiar with

@klueska reviewed this PR and [approved](https://github.com/kubernetes/kubernetes/pull/114640#issuecomment-1415840405) the core changes.

@fromani reviewed this PR gave his [LGTM](https://github.com/kubernetes/kubernetes/pull/114640#pullrequestreview-1247388149). It got removed as I was addressing some review comments and had to rebase.

With regard to tackling the consumption of sample device plugin changes in e2e tests here, the sample device plugin changes were split into a separate [PR](https://github.com/kubernetes/kubernetes/pull/115107) which would need to merge first. @bart0sh has been reviewing that PR and gave his [LGTM](https://github.com/kubernetes/kubernetes/pull/115107#pullrequestreview-1286820735) and indicated that he is [okay](https://github.com/kubernetes/kubernetes/pull/115107#issuecomment-1438932149) with the approach taken.

If you are happy enough with these these two PRs from test perspective and can approve, we should be able to move forward.

**Comment by ffromani** [comment]
> @fromani reviewed this PR gave his [LGTM](https://github.com/kubernetes/kubernetes/pull/114640#pullrequestreview-1247388149). It got removed as I was addressing some review comments and had to rebase.

And I'll review again before end of day (EOD)

**Comment by swatisehgal** [comment]
> > @fromani reviewed this PR gave his [LGTM](https://github.com/kubernetes/kubernetes/pull/114640#pullrequestreview-1247388149). It got removed as I was addressing some review comments and had to rebase.
> 
> And I'll review again before end of day (EOD)

Thank you!

File: test/e2e_node/device_manager_test.go (hunk 33 above)
Comment (pohly) [reply test/e2e_node/device_manager_test.go]: Fails how? I'm curious because the approach with directly passing the arguments is used everywhere else, `WithArguments` is not used anywhere.

Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go]: Yep, I thought so too when I referred to other areas in the code base that used eventually the way you suggested. Here is what I get:

```
  Feb 28 19:06:07.615: INFO: 
  Logging kubelet events for node swsehgal-node
  Feb 28 19:06:07.618: INFO: 
  Logging pods the kubelet thinks is on node swsehgal-node
  W0228 19:06:07.623862  111282 metrics_grabber.go:111] Can't find any pods in namespace kube-system to grab metrics from
  Feb 28 19:06:07.657: INFO: 
  Latency metrics for node swsehgal-node
  STEP: Destroying namespace "devicemanager-test-3328" for this suite. @ 02/28/23 19:06:07.658
  << Timeline

  [FAILED] &framework.Framework{BaseName:"devicemanager-test", UniqueName:"devicemanager-test-3328", clientConfig:(*rest.Config)(0xc001ab0240), ClientSet:(*kubernetes.Clientset)(0xc0001a0b60), KubemarkExternalClusterClientSet:kubernetes.Interface(nil), DynamicClient:(*dynamic.DynamicClient)(0xc00061d570), ScalesGetter:(*scale.scaleClient)(0xc001b09a80), SkipNamespaceCreation:false, Namespace:(*v1.Namespace)(0xc000f68420), namespacesToDelete:[]*v1.Namespace{(*v1.Namespace)(0xc000f68420)}, NamespaceDeletionTimeout:0, NamespacePodSecurityEnforceLevel:"privileged", flakeReport:(*framework.FlakeReport)(0xc001b09dc0), Options:framework.Options{ClientQPS:20, ClientBurst:50, GroupVersion:(*schema.GroupVersion)(nil)}, TestSummaries:[]framework.TestDataSummary(nil), Timeouts:(*framework.TimeoutContext)(0xc000ecb180), DumpAllNamespaceInfo:(framework.DumpAllNamespaceInfoAction)(0x4679320)} is not a valid interval. Must be a time.Duration, a parsable duration string, or a number.
  In [BeforeEach] at: test/e2e_node/device_manager_test.go:386 @ 02/28/23 19:06:03.575
------------------------------
SSSSSSSSSSSSS

Summarizing 1 Failure:
  [FAIL] [sig-node] Device Manager  [Serial] [Feature:DeviceManagerBug][NodeFeature:DeviceManager] With sample device plugin [BeforeEach] should deploy pod consuming devices first but fail with admission error after kubelet restart in case device plugin hasn't re-registered
  test/e2e_node/device_manager_test.go:386

Ran 1 of 389 Specs in 16.926 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 388 Skipped
--- FAIL: TestE2eNode (16.96s)
```

Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go]: The only change I made was:
```
diff --git a/test/e2e_node/device_manager_test.go b/test/e2e_node/device_manager_test.go
index 68eeb85b2d2..6fc60fc5ed0 100644
--- a/test/e2e_node/device_manager_test.go
+++ b/test/e2e_node/device_manager_test.go
@@ -383,8 +383,7 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 
                        ginkgo.By("Waiting for devices to become available on the local node")
 
-                       gomega.Eventually(ctx, isNodeReadyWithSampleResources).
-                               WithArguments(f).
+                       gomega.Eventually(ctx, isNodeReadyWithSampleResources, f).
                                WithTimeout(5 * time.Minute).
                                Should(BeReady())
```

**Review by ffromani — COMMENTED** [review]
first two commits reviewed on https://github.com/kubernetes/kubernetes/pull/115107 - conditional LGTM here, but they need to be merged separately anyway
next three commits already approved, and LGTM anyway
the rest of the commits are about e2e changes which LGTM - nice use of custom gomega matchers!

**Comment by ffromani** [comment]
/lgtm

for the test changes.
*please* don't remove the hold just yet: for this PR to merge we need to merge https://github.com/kubernetes/kubernetes/pull/115107 and promote the sample device plugin image. I see the approval was removed somehow (!?) so it should be OK.

**Comment by ffromani** [comment]
> /lgtm
> 
> for the test changes. _please_ don't remove the hold just yet: for this PR to merge we need to merge #115107 and promote the sample device plugin image. I see the approval was removed somehow (!?) so it should be OK.

proof:
image

File: test/e2e_node/device_manager_test.go (hunk 33 above)
Comment (pohly) [reply test/e2e_node/device_manager_test.go]: I was wrong about  `Eventually` taking a function + parameters. The additional arguments after the function are timeout and poll interval. Your approach with `WithArguments` is correct.

Comment (swatisehgal) [reply test/e2e_node/device_manager_test.go]: Thanks for double checking this.

**Comment by swatisehgal** [comment]
> /lgtm
> 
> for the test changes. _please_ don't remove the hold just yet: for this PR to merge we need to merge #115107 and promote the sample device plugin image.

Thanks! Correct, the PR with sample device changes has to merge first.

> I see the approval was removed somehow (!?) so it should be OK.

I'm not 100% sure but maybe the label was never added because we need approval from both kubelet owners and test owners. See the image below:
image

File: test/e2e_node/device_manager_test.go [hunk 34]
```diff
@@ -287,7 +327,7 @@ var _ = SIGDescribe("Device Manager  [Serial] [Feature:DeviceManager][NodeFeatur
 			}, time.Minute, time.Second).Should(gomega.BeTrue())
 
 			ginkgo.By("Scheduling a sample device plugin pod")
-			data, err := e2etestfiles.Read(SampleDevicePluginDS2YAML)
+			data, err := e2etestfiles.Read(SampleDevicePluginControlRegistrationDSYAML)
```
Comment (ffromani) [inline test/e2e_node/device_manager_test.go:331]: this manifest correctly uses the 1.5 plugin version, which is not promoted yet. This is just fine for now. Let's promote the plugin and we can move forward.

**Review by ffromani — COMMENTED** [review]
Thanks for the rebase! LGTM. Holding the formal LGTM label until the new sample-device-plugin image is promoted. Ping me anytime once this happens so I can tag this PR.

**Comment by ffromani** [comment]
/test pull-kubernetes-unit

apiserver failures can't be cause by this PR

File: test/e2e_node/device_manager_test.go (hunk 34 above)
Comment (ffromani) [reply test/e2e_node/device_manager_test.go:331]: Thanks for getting the image promoted (https://github.com/kubernetes/k8s.io/pull/4862). I'll run a final check very shortly and review (and likely LGTM) again. I see no issues at all, just the last bit of due diligence.

**Comment by ffromani** [comment]
@swatisehgal ok, the last check found a couple issues. Good news is I think there are both easy to fix.
1. I know you made changes to make to update the e2e test work with the latest iteration (which got merged) of the sample device plugin, moving all the file handling in the e2e test (previously it was mixed between the plugin and the e2e test). Could you please check this PR is up to date and includes all your recent work?
2. we took most care to use the newer sampledevice plugin ONLY in this new test to minimize the chance of regressions, deferring cleanups to later PR. I think this is the right call. Unfortunately we missed an update, I think the following should be enough to fix:
```
diff --git a/test/e2e_node/image_list.go b/test/e2e_node/image_list.go
index 611590642bc..e6e7da29766 100644
--- a/test/e2e_node/image_list.go
+++ b/test/e2e_node/image_list.go
@@ -87,11 +87,16 @@ func updateImageAllowList(ctx context.Context) {
        } else {
                e2epod.ImagePrePullList.Insert(gpuDevicePluginImage)
        }
-       if samplePluginImage, err := getSampleDevicePluginImage(); err != nil {
+       if samplePluginImage, err := getContainerImageFromE2ETestDaemonset(SampleDevicePluginDSYAML); err != nil {
                klog.Errorln(err)
        } else {
                e2epod.ImagePrePullList.Insert(samplePluginImage)
        }
+       if samplePluginImageCtrlReg, err := getContainerImageFromE2ETestDaemonset(SampleDevicePluginControlRegistrationDSYAML); err != nil {
+               klog.Errorln(err)
+       } else {
+               e2epod.ImagePrePullList.Insert(samplePluginImageCtrlReg)
+       }
 }
 
 func getNodeProblemDetectorImage() string {
@@ -222,19 +227,19 @@ func getGPUDevicePluginImage(ctx context.Context) (string, error) {
        return ds.Spec.Template.Spec.Containers[0].Image, nil
 }
 
-func getSampleDevicePluginImage() (string, error) {
-       data, err := e2etestfiles.Read(SampleDevicePluginDSYAML)
+func getContainerImageFromE2ETestDaemonset(dsYamlPath string) (string, error) {
+       data, err := e2etestfiles.Read(dsYamlPath)
        if err != nil {
-               return "", fmt.Errorf("failed to read the sample plugin yaml: %w", err)
+               return "", fmt.Errorf("failed to read the daemonset yaml: %w", err)
        }
 
        ds, err := e2emanifest.DaemonSetFromData(data)
        if err != nil {
-               return "", fmt.Errorf("failed to parse daemon set for sample plugin: %w", err)
+               return "", fmt.Errorf("failed to parse daemonset yaml: %w", err)
        }
 
        if len(ds.Spec.Template.Spec.Containers) < 1 {
-               return "", fmt.Errorf("failed to parse the sample plugin image: cannot extract the container from YAML")
+               return "", fmt.Errorf("failed to parse the container image: cannot extract the container from YAML")
        }
        return ds.Spec.Template.Spec.Containers[0].Image, nil
 }
```

**Comment by swatisehgal** [comment]
Thanks @ffromani for your thorough review. Appreciate it! I have addressed your review comments.

> 1. I know you made changes to make to update the e2e test work with the latest iteration (which got merged) of the sample device plugin, moving all the file handling in the e2e test (previously it was mixed between the plugin and the e2e test). Could you please check this PR is up to date and includes all your recent work?

Thanks for identifying this. I think I must have rebased an older version of the code. Fixed it now.
> 2. we took most care to use the newer sampledevice plugin ONLY in this new test to minimize the chance of regressions, deferring cleanups to later PR. I think this is the right call. Unfortunately we missed an update, I think the following should be enough to fix:

Thanks, fixed.

**Comment by ffromani** [comment]
/lgtm

thanks for quickly addressing my comments. Codewise looks good to me now, and the tests on my local env are now fine as well.

**Comment by swatisehgal** [comment]
/unhold
as all the review comments have been addressed and both the prerequisite PRs (https://github.com/kubernetes/kubernetes/pull/115107 and https://github.com/kubernetes/k8s.io/pull/4862) have merged.

**Comment by ffromani** [comment]
/test pull-kubernetes-integration

apiserver test failures can't be caused by this PR

**Comment by liggitt** [comment]
cleared release note and reopened issue marked as fixed due to revert of this PR in https://github.com/kubernetes/kubernetes/pull/116341

**Comment by swatisehgal** [comment]
Here is a PR with updates to ensure that the device plugin tests pass: https://github.com/kubernetes/kubernetes/pull/116376.
