### PR TITLE
Disambiguate unsupported metrics from metrics errors

### LINKED ISSUE #20676: Volume metrics calculation - disambiguate error during collection from "not supported"
Many volumes do not support GetMetrics and return an error when called.  Because this returns an error, we cannot differentiate from an actual error condition when a volume that does support metrics fails to gather metrics.  The latter should be logged and investigated, whereas the former should be silently ignored.

### LINKED ISSUE #27373: Spammy log messages in kubelet: metrics are not supported for MetricsNil Volumes
These volumes don't support stats metrics, and yet the errors got printed out periodically for each pod. 

```
I0614 17:01:54.337456   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod kube-proxy-e2e-test-yjhong-minion-group-21rr_kube-system(b7c4ad73450e2cf13c9cb849231754c2) volume kubeconfig: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337464   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod kube-proxy-e2e-test-yjhong-minion-group-21rr_kube-system(b7c4ad73450e2cf13c9cb849231754c2) volume varlog: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337544   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod e2e-image-puller-e2e-test-yjhong-minion-group-21rr_kube-system(0d136a4468db307b8063df140402a70e) volume socket: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337563   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod e2e-image-puller-e2e-test-yjhong-minion-group-21rr_kube-system(0d136a4468db307b8063df140402a70e) volume docker: metrics are not supported for MetricsNil Volumes
I0614 17:01:54.337591   30118 volume_stat_caculator.go:103] Failed to calculate volume metrics for pod node-problem-detector-v0.1-oa8xn_kube-system(b9edf393-3187-11e6-8f11-42010af00002) volume log: metrics are not supported for MetricsNil Volumes
```

### PR DESCRIPTION
**Pull request by asalkeld**
**What this PR does / why we need it**:
Stop logging "metrics are not supported for MetricsNil Volumes" as it spams the log.

**Which issue this PR fixes** 
fixes #20676, fixes #27373

**Special notes for your reviewer**:
None

**Release note**:

``` release-note
Don't log "metrics are not supported for MetricsNil Volumes"
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32348)

### CODE REVIEW

File: pkg/volume/metrics_errors.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+package volume
+
+import (
+	"fmt"
+)
+
+const (
+	// ErrCodeNotSupported code for NotSupported Errors.
+	ErrCodeNotSupported int = iota + 1
```
Comment (pmorie) [inline pkg/volume/metrics_errors.go]: The names look a little weird to me but there is precedent for this naming convention in `pkg/storage`, so, fine

Comment (asalkeld) [inline pkg/volume/metrics_errors.go]: Yeah, that is what I followed. I could change both at the same time if you have a better naming scheme in mind.

Comment (pmorie) [inline pkg/volume/metrics_errors.go]: Nah, it's fine.

**Comment by pmorie** [comment]
@asalkeld tend the E2E failure and I'll LGTM on green.  Thanks for fixing this!

**Comment by asalkeld** [comment]
Hi @pmorie thanks. I haven't seen "Jenkins GKE smoke e2e — Error in queue. " before (#32428). The E2E tests look like they pass, I might just rebase the PR to force a retest.

**Comment by pmorie** [comment]
LGTM, thanks for the patch @asalkeld
