### PR TITLE
Fix Node initialization for GCP cloud provider

### LINKED ISSUE #90056: gcp cloud-controller-manager cannot initialize a new Node
**What happened**:
https://github.com/kubernetes/kubernetes/pull/85735 introduces a regression that `getNodeAddressesByProviderIDOrName` func is invoked on a Node obj without `.spec.providerID`, hence it can fail fetching the node addresses when the `.spec.providerID` is not set. 

**What you expected to happen**:
I would expect cloud-controller-manager to be able to initialize new Node.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start the gcp legacy-cloud-controller v1.18.1 (`--cloud-provider="gce"`)

2. Ensure that the node-controller cannot initialize a new Node. Logs of the cloud-controller-manager repeated multiple times:
```
I0410 15:48:51.287480       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.295679       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.541680       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
I0410 15:48:51.541710       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.547318       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.762648       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
```

Ensure that the Node is with the `node.cloudprovider.kubernetes.io/uninitialized:NoSchedule` taint. Ensure that the `.spec.providerID` of the Node is not set.

The cloud-controller-manager is not running on the host machine and that's why it cannot call the gce matadata. But it was never a hard requirement for cloud-controller-manager to run on the host machine.

**Anything else we need to know?**:
The legacy cloud-controller-manager v1.17.x is working perfectly fine.

**Environment**:
- Kubernetes version (use `kubectl version`):v1.18.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The legacy GCP cloud-controller-manager is not able to initialize new Nodes. Logs:
```
I0410 15:48:51.287480       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.295679       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.541680       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
I0410 15:48:51.541710       1 node_controller.go:325] Initializing node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 with cloud provider
E0410 15:48:51.547318       1 gce_instances.go:575] Failed to fetch instanceID via Metadata: metadata: GCE metadata "instance/hostname" not defined
E0410 15:48:51.762648       1 node_controller.go:370] failed to initialize node shoot--foo--bar-cpu-worker-z1-68f57cffcd-dbq47 at cloudprovider: error fetching node by provider ID: error splitting providerID, and error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
```

The `getNodeAddressesByProviderIDOrName` tries to call `NodeAddressesByProviderID` and `NodeAddresses` funcs.
https://github.com/kubernetes/kubernetes/blob/5bfe8fe2b9024f0319c053d5514b491f7c18aad8/pkg/controller/cloud/node_controller.go#L534-L544

`NodeAddressesByProviderID` func will always fail to split empty providerID.
https://github.com/kubernetes/kubernetes/blob/5bfe8fe2b9024f0319c053d5514b491f7c18aad8/staging/src/k8s.io/legacy-cloud-providers/gce/gce_instances.go#L113-L120

`NodeAddresses` func will fail to fetch the gce metadata if the cloud-controller-manager is not running on the Node.
https://github.com/kubernetes/kubernetes/blob/5bfe8fe2b9024f0319c053d5514b491f7c18aad8/staging/src/k8s.io/legacy-cloud-providers/gce/gce_instances.go#L86-L90

**Which issue(s) this PR fixes**:

Fixes #90056

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
An issue preventing GCP cloud-controller-manager running out-of-cluster to initialize new Nodes is now fixed.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/cloud/node_controller.go [hunk 1]
```diff
@@ -412,11 +412,7 @@ func (cnc *CloudNodeController) getNodeModifiersFromCloudProvider(ctx context.Co
 	if node.Spec.ProviderID == "" {
 		providerID, err := cloudprovider.GetInstanceProviderID(ctx, cnc.cloud, types.NodeName(node.Name))
 		if err == nil {
-			nodeModifiers = append(nodeModifiers, func(n *v1.Node) {
```
Comment (alvaroaleman) [inline pkg/controller/cloud/node_controller.go:415]: @ialidzhikov unless I am missing something completely, this change will result in the `providerID` never being set on the node, because the node is updated via a `Get` -> `Modify` -> `Update`.

Comment (alvaroaleman) [reply pkg/controller/cloud/node_controller.go:415]: And also please add a oneline godoc on why it has to be set on the `node`, this is super unintuitive and as we can see untested

Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:415]: > @ialidzhikov unless I am missing something completely, this change will result in the providerID never being set on the node, because the node is updated via a Get -> Modify -> Update.

Yep, you are right. The providerID won't be set but the Node will be initiliazed. Then I would suggest to keep the nodeModifiers append but also set the .spec.providerID for the `node` variable. WDYT?

Comment (alvaroaleman) [reply pkg/controller/cloud/node_controller.go:415]: yes, sgtm

Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:415]: > And also please add a oneline godoc on why it has to be set on the node, this is super unintuitive and as we can see untested

@alvaroaleman , I updated the PR, it should be more intuitive now.

**Comment by alvaroaleman** [comment]
I've written a unittest for this so we don't regress again: https://github.com/kubernetes/kubernetes/compare/master...alvaroaleman:b-test?expand=1
I can PR it in after this merges, it obviously doesn't pass against current master

**Comment by ialidzhikov** [comment]
> I've written a unittest for this so we don't regress again: https://github.com/kubernetes/kubernetes/compare/master...alvaroaleman:b-test?expand=1
> I can PR it in after this merges, it obviously doesn't pass against current master

Thank you @alvaroaleman .

/kind regression

**Comment by thockin** [comment]
This SEEMS ok, but I am not that familiar with the surrounding code any more.  IMO it could do with some explanatory comments when providerID != node.Spec.ProviderID

Assigning to @cheftako because he is closer to it than I am.

File: pkg/controller/cloud/node_controller.go [hunk 2]
```diff
@@ -531,11 +535,11 @@ func ensureNodeExistsByProviderID(ctx context.Context, instances cloudprovider.I
 	return instances.InstanceExistsByProviderID(ctx, providerID)
 }
 
-func getNodeAddressesByProviderIDOrName(ctx context.Context, instances cloudprovider.Instances, node *v1.Node) ([]v1.NodeAddress, error) {
-	nodeAddresses, err := instances.NodeAddressesByProviderID(ctx, node.Spec.ProviderID)
```
Comment (andrewsykim) [inline pkg/controller/cloud/node_controller.go:535]: There are more places in this controller where we check the provider ID from the node object directly. I wonder if we should update all of those If we want to make this optimization? I think checking node.Spec.ProviderID is simpler but on first initialization clearly that field is not set yet so we can't use it. 

Could we instead add the provider ID modifier as a separate step prior to the other modifiers and set `Spec.ProviderID` to the local node object passed into getNodeModifiersFromCloudProvider?

Comment (andrewsykim) [reply pkg/controller/cloud/node_controller.go:535]: I can see this being a bad idea because we would make assumptions that the field is set in the API when we haven't committed it yet. @cheftako thoughts?

File: pkg/controller/cloud/node_controller.go [hunk 3]
```diff
@@ -430,7 +434,7 @@ func (cnc *CloudNodeController) getNodeModifiersFromCloudProvider(ctx context.Co
 		}
 	}
 
-	nodeAddresses, err := getNodeAddressesByProviderIDOrName(ctx, instances, node)
+	nodeAddresses, err := getNodeAddressesByProviderIDOrName(ctx, instances, providerID, node.Name)
```
Comment (cheftako) [inline pkg/controller/cloud/node_controller.go:437]: I don't believe its guaranteed that the providerID field has been set. In that case we are going to have a problem with this.

File: pkg/controller/cloud/node_controller.go (hunk 2 above)
Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:535]: > I can see this being a bad idea because we would make assumptions that the field is set in the API when we haven't committed it yet.

That's why I modified the func to accept `providerID, nodeName string` instead of `node v1.Node` (with the assumption that `.Spec.ProviderID` is set on the `node` arg).

File: pkg/controller/cloud/node_controller.go (hunk 3 above)
Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:437]: @cheftako , can you elaborate details? What would be a problem?

Comment (cheftako) [reply pkg/controller/cloud/node_controller.go:437]: providerID is only set if node.Spec.ProviderID is not set. So as example if we go through this method twice for the same node, the second time the method is called, node.Spec.ProviderID will be set. As a result providerID on the second pass will *not* have been set here. Now we will fail to look up the node addresses because we aren't using the correct providerID...

Comment (alvaroaleman) [reply pkg/controller/cloud/node_controller.go:437]: Yeah, going through this multiple times should not happen after https://github.com/kubernetes/kubernetes/pull/85735 but its not impossible if the updating fails on all attempts

Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:439]: @cheftako , with the latest force-push the `providerID` should be set to `node.Spec.ProviderID` when `node.Spec.ProviderID != nil`

**Review by andrewsykim — COMMENTED** [review]
We probably want to make similar changes to `getInstanceTypeByProviderIDOrName` and `getZoneByProviderIDOrName`

**Comment by alvaroaleman** [comment]
> We probably want to make similar changes to getInstanceTypeByProviderIDOrName and getZoneByProviderIDOrName

@andrewsykim At this point this PR is a fix for a change that breaks all cloud providers that rely on the providerID being present in the `getNodeAddressesByProviderIDOrName` call that is done during initialization in 1.18 and onwards.

Could we maybe keep this PR scoped to just fix this issue, have it cherypicked and do further refactorings in follow-ups to make sure we do not break something else with this change?

**Comment by ialidzhikov** [comment]
> We probably want to make similar changes to `getInstanceTypeByProviderIDOrName` and `getZoneByProviderIDOrName`

It makes sense because a cloud provider can rely `providerID` to be set for `getInstanceTypeByProviderIDOrName` and `getZoneByProviderIDOrName` invocations.

**Comment by andrewsykim** [comment]
> @andrewsykim At this point this PR is a fix for a change that breaks all cloud providers that rely on the providerID being present in the getNodeAddressesByProviderIDOrName call that is done during initialization in 1.18 and onwards.

I'm not sure this is a problem for all providers yet. From what I can tell, most providers would return err if an empty provider ID is passed to `NodeAddressesByProviderID` in which case `NodeAddresses` (by node name) would succeed. For the GCP case the node address by name seems to be failing with:
```
error by node name: couldn't get internal IP: metadata: GCE metadata "instance/network-interfaces/0/ip" not defined
```

My guess there is that it always assumes `NodeAddress` is called by the kubelet. Maybe the correct fix here is to update the GCP cloud provider so that `NodeAddress` checks the cloud API for the out-of-tree case.

**Comment by ialidzhikov** [comment]
> My guess there is that it always assumes NodeAddress is called by the kubelet. Maybe the correct fix here is to update the GCP cloud provider so that NodeAddress checks the cloud API for the out-of-tree case.

This sounds as a separate enhancement which is out of context of this PR.

@cheftako , @andrewsykim could you please check the PR once again?

File: pkg/controller/cloud/node_controller.go (hunk 3 above)
Comment (cheftako) [reply pkg/controller/cloud/node_controller.go:439]: Looks good

File: pkg/controller/cloud/node_controller.go (hunk 2 above)
Comment (cheftako) [reply pkg/controller/cloud/node_controller.go:535]: I think andrewsykim's point about wanting this fixed everywhere is legit, but I don't think it all has to be fixed in this PR. We should probably file a bug to do the follow on work.

File: pkg/controller/cloud/node_controller.go [hunk 4]
```diff
@@ -531,11 +537,11 @@ func ensureNodeExistsByProviderID(ctx context.Context, instances cloudprovider.I
...
 }
 
-func getNodeAddressesByProviderIDOrName(ctx context.Context, instances cloudprovider.Instances, node *v1.Node) ([]v1.NodeAddress, error) {
-	nodeAddresses, err := instances.NodeAddressesByProviderID(ctx, node.Spec.ProviderID)
+func getNodeAddressesByProviderIDOrName(ctx context.Context, instances cloudprovider.Instances, providerID, nodeName string) ([]v1.NodeAddress, error) {
+	nodeAddresses, err := instances.NodeAddressesByProviderID(ctx, providerID)
 	if err != nil {
 		providerIDErr := err
-		nodeAddresses, err = instances.NodeAddresses(ctx, types.NodeName(node.Name))
+		nodeAddresses, err = instances.NodeAddresses(ctx, types.NodeName(nodeName))
```
Comment (cheftako) [inline pkg/controller/cloud/node_controller.go:544]: This isn't going to work for GCP using the existing GCE cloud provider implementation. (https://github.com/kubernetes/legacy-cloud-providers/blob/master/gce/gce_instances.go#L86) The gce implementation has the  issue detailed in the todo of the interface (https://github.com/kubernetes/cloud-provider/blob/master/cloud.go#L160). It was written back when this was only called from the Kubelet and is written such that it will only do the right thing, when called from the Kubelet.

**Review by cheftako — COMMENTED** [review]
/lgtm

File: pkg/controller/cloud/node_controller.go (hunk 4 above)
Comment (andrewsykim) [reply pkg/controller/cloud/node_controller.go:544]: Agreed and I think this is the proper fix. `node.Spec.ProviderID` being empty is acceptable which is why we have checks for getting by name.

Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:544]: Yes, but this is not something related to this PR. That's why I propose this PR to fix the `providerID` passing to `getNodeAddressesByProviderIDOrName` and in this way prevent the fallback call to `NodeAddresses` which fails for gce when the cloud-controller-manager is not running on the host.

Comment (cheftako) [reply pkg/controller/cloud/node_controller.go:544]: Agreed, which is why I lgtm'd it. I just wanted to make sure you were aware of the issue. 

The Kubelet usage of the cloud provider implementation should be going away soon. We should fix the GCE implementation to do the right thing in non Kubelet use cases.

Comment (andrewsykim) [reply pkg/controller/cloud/node_controller.go:544]: > Yes, but this is not something related to this PR. 

This is the part I'm a bit confused about. I think it is related because implementing the GCP fallback makes this a non-issue. We should treat `node.Spec.ProviderID` as the source of truth because we don't know yet if the provider ID from `GetInstanceProviderID` is valid. There are also some cases where `node.Spec.ProviderID` can be set from another source and `GetInstanceProviderID` returns `cloudprovider.NotImplemented`.

Comment (ialidzhikov) [reply pkg/controller/cloud/node_controller.go:544]: > This is the part I'm a bit confused about. I think it is related because implementing the GCP fallback makes this a non-issue. 

I don't agree here. Currently all `getNodeAddressesByProviderIDOrName`, `getInstanceTypeByProviderIDOrName`, `getZoneByProviderIDOrName` are called with `node.Spec.ProviderID=""` which makes pointless all of the provideID usage in these funcs such as `instances.NodeAddressesByProviderID(ctx, node.Spec.ProviderID)`, `instances.InstanceTypeByProviderID(ctx, providerID)`, `zones.GetZoneByProviderID(ctx, providerID)`.

Generally I agree that the GCE provider handling for `NodeAddresses` func can be improved to do not rely that the cloud-controller-manager is running on the Node. But this is something different.

Comment (andrewsykim) [reply pkg/controller/cloud/node_controller.go:544]: > I don't agree here. Currently all getNodeAddressesByProviderIDOrName, getInstanceTypeByProviderIDOrName, getZoneByProviderIDOrName are called with node.Spec.ProviderID="" which makes pointless all of the provideID usage in these funcs such as instances.NodeAddressesByProviderID(ctx, node.Spec.ProviderID), instances.InstanceTypeByProviderID(ctx, node.Spec.ProviderID), zones.GetZoneByProviderID(ctx, node.Spec.ProviderID).

The ProviderID can be preset if kubelet has `--provider-id` set, but I see this doesn't break that since `node.Spec.ProviderID` takes precedent.

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

Thanks @ialidzhikov

File: pkg/controller/cloud/node_controller.go (hunk 4 above)
Comment (cheftako) [reply pkg/controller/cloud/node_controller.go:544]: https://github.com/kubernetes/kubernetes/issues/90185
