### PR TITLE
kubeadm: preflight check for incorrect FQDN

### LINKED ISSUE #135: Add preflight check for incorrect FQDN?
There are a variety of system configuration errors (such as cloud-init bugs when deploying on AWS) which can cause hostname and uname -n to be wrong for a given host.  This will cause kubeadm setup to fail in interesting and hard-to-figure-out ways (it doesn't fail until you start trying to set up DNS on the master, for example).

Given this, would it be worth adding a preflight check for this?  Or would it be very hard to determine?

### PR DESCRIPTION
**Pull request by dmmcquay**
**What this PR does / why we need it**: There are a variety of system configuration errors (such as cloud-init bugs when deploying on AWS) which can cause hostname and uname -n to be wrong for a given host. This will cause kubeadm setup to fail in interesting and hard-to-figure-out ways (it doesn't fail until you start trying to set up DNS on the master, for example).

This PR adds a preflight check to test whether or not the server can reach itself using that name. This does not catch the case that the FQDN belongs to a different but valid server, but it would catch some of the cases. 

**Which issue this PR fixes** : fixes https://github.com/kubernetes/kubeadm/issues/135

**Special notes for your reviewer**: /cc @luxas 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dmmcquay** [comment]
@k8s-bot gce etcd3 e2e test this

File: cmd/kubeadm/app/preflight/checks.go [hunk 1]
```diff
@@ -243,6 +243,10 @@ func (hc HostnameCheck) Check() (warnings, errors []error) {
 	for _, msg := range validation.ValidateNodeName(hostname, false) {
 		errors = append(errors, fmt.Errorf("hostname \"%s\" %s", hostname, msg))
 	}
+	addr, err := net.LookupHost(hostname)
+	if addr == nil || err != nil {
```
Comment (luxas) [inline cmd/kubeadm/app/preflight/checks.go]: minor nit: if addr is nil here the error would be `hostname "{hostname}" ` which isn't very descriptive.
I think you can split that out to two cases.

**Review by luxas — COMMENTED** [review]
Basically LGTM.

cc @jberkus Do you think this solves your issue?

**Comment by luxas** [comment]
/lgtm
/approve

I think this will pass the tests

**Comment by dmmcquay** [comment]
@luxas do you know why this is being held up?

**Comment by mikedanese** [comment]
What class of errors is this actually validating against? Can you give me an example of something that could go wrong that would cause this to fail?

**Comment by jberkus** [comment]
The test case I have is bad cloud-init on AWS causing /etc/hostname to be a non-resolvable name.  There's a number of different sysadmin errors which would cause that to be the case, including poor DNS setup on the external network.

I'll post an example test case after FOSDEM.

**Comment by mikedanese** [comment]
This doesn't check DNS or anything external...
