### PR TITLE
Do not log entire pod struct while attaching the volume

### LINKED ISSUE #114483: AttachVolume could crash kube-controller-manager if volume metadata is too long
### What happened?

```
Dec 14 14:00:49 WIZPRESSO-13-linux k0s[1984674]: time="2022-12-14 14:00:49" level=info msg="I1214 14:00:49.732984  761087 reconciler.go:346] \"attacherDetacher.AttachVolume started\" volume=<" component=kube-controller-manager
Dec 14 14:00:49 WIZPRESSO-13-linux k0s[1984674]: time="2022-12-14 14:00:49" level=error msg="Error while reading from Writer: bufio.Scanner: token too long" component=kube-controller-manager
Dec 14 14:00:49 WIZPRESSO-13-linux k0s[1984674]: time="2022-12-14 14:00:49" level=info msg="E1214 14:00:49.943237 1984865 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:\"client disconnected\"}: client disconnected" component=kube-apiserver
Dec 14 14:00:49 WIZPRESSO-13-linux k0s[1984674]: time="2022-12-14 14:00:49" level=info msg="E1214 14:00:49.943313 1984865 writers.go:118] apiserver was unable to write a JSON response: http: Handler timeout" component=kube-apiserver
Dec 14 14:00:49 WIZPRESSO-13-linux k0s[1984674]: time="2022-12-14 14:00:49" level=info msg="E1214 14:00:49.943318 1984865 wrap.go:53] timeout or abort while handling: method=PUT URI=\"/apis/apps/v1/namespaces/default/deployments/function-gitea-repo-cd69f97b74158194d8fa0b568776ad6c-deploy
ment/status\" audit-ID=\"01673068-1403-4de4-997e-a25acb873eae\"" component=kube-apiserver
```

### What did you expect to happen?

Keep running but not crashing

### How can we reproduce it (as minimally and precisely as possible)?

Have a long volume attach path

This corresponds to these lines
https://github1s.com/kubernetes/kubernetes/blob/HEAD/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L343-L352

### Anything else we need to know?

We are using k0s

### Kubernetes version

<details>

```console
(base) PS C:\Users\steve\git> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k0s", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-17T13:46:59Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

bare metal

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Prevents logging entire Pod struct, instead it only logs the pod metadata which is sufficient to uniquely identify the pod. 

#### Which issue(s) this PR fixes:

Fixes #114483 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 1]
```diff
@@ -343,12 +343,12 @@ func (rc *reconciler) attachDesiredVolumes() {
 		klog.V(5).InfoS("Starting attacherDetacher.AttachVolume", "volume", volumeToAttach)
 		err := rc.attacherDetacher.AttachVolume(volumeToAttach.VolumeToAttach, rc.actualStateOfWorld)
 		if err == nil {
-			klog.InfoS("attacherDetacher.AttachVolume started", "volume", volumeToAttach)
+			klog.InfoS("attacherDetacher.AttachVolume started", "volume name", volumeToAttach.VolumeName, "node name", volumeToAttach.NodeName, "scheduled pods", klog.KObjSlice(volumeToAttach.ScheduledPods))
```
Comment (sunnylovestiramisu) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go:346]: Do we care about information for VolumeSpec?

Comment (harche) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go:346]: If the volume attachment fails then it would be helpful to let user know about the name of the volume, which node it failed to attach and which pod were going to use it.

**Comment by xing-yang** [comment]
@harche Please rebase.

**Comment by jsafrane** [comment]
/approve

@harche sorry it took so long, can you please rebase?

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 1 above)
Comment (sunnylovestiramisu) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: /lgtm
