### PR TITLE
Increasing maximum number of ports allowed in EndpointSlice

### LINKED ISSUE #99382: EndpointSlice Controllers should use multiple slices for Services with many ports
#### What happened:
The EndpointSlice controllers are unaware of the limit on the number of EndpointSlice ports. When a Service has more than 100 ports, the EndpointSlice controllers try to create/update EndpointSlices as usual but fail.

#### What you expected to happen:
The EndpointSlice controller should probably have some support for subsetting EndpointSlices into groups of 100 ports in these instances. Alternatively we could remove the [EndpointSlice validation](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/discovery/validation/validation.go#L43) for this but that would result in yet another unbounded list in k8s APIs.

#### How to reproduce it (as minimally and precisely as possible):
Create a Service with >100 ports.

/cc @swetharepakula @thockin

### PR DESCRIPTION
**Pull request by robscott**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
Increases maximum number of ports allowed in EndpointSlices from 100 to 20,000.

#### Which issue(s) this PR fixes:
Helps with #99382

#### Does this PR introduce a user-facing change?
```release-note
Fixes a regression in 1.18+ where endpoint slice controller would attempt to create endpoint slices with too many ports; the maximum number of ports allowed in EndpointSlices has been increased from 100 to 20,000
```

/sig network
/priority important-soon
/triage accepted
/cc @freehan
/assign @thockin

### CODE REVIEW

File: pkg/apis/discovery/validation/validation.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ var (
 	)
 	maxTopologyLabels = 16
 	maxAddresses      = 100
-	maxPorts          = 100
+	maxPorts          = 16000
```
Comment (robscott) [inline pkg/apis/discovery/validation/validation.go:43]: Despite the small diff, there is test coverage for this, it just uses this variable.

Comment (robscott) [reply pkg/apis/discovery/validation/validation.go:43]: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/discovery/validation/validation_test.go#L269 and https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/discovery/validation/validation_test.go#L168

**Comment by thockin** [comment]
If we are doing base-10 maybe 20K makes more sense?

**Comment by robscott** [comment]
@thockin makes sense, updated to 20k.

**Comment by thockin** [comment]
Is there a followup bug filed to fix the slice controllers to consider ports?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by robscott** [comment]
>Is there a followup bug filed to fix the slice controllers to consider ports?

@thockin I removed the `fixes` keyword from this PR and will leave the original issue open since I think it's still applicable, just with a higher number. I'll add some more detail there as far as what additional steps we could take.

**Comment by tengqm** [comment]
Pls check if this change should be mentioned in the `content/en/docs/concepts/services-networking/endpoint-slices.md` on k8s/website.
