### PR TITLE
Fix "go test -count=2 ./pkg/proxy/iptables"

### LINKED ISSUE #121794: Kube-proxy/iptables: unit tests fails for count>1
### What happened?

When unit tests in `kubernetes/pkg/proxy/iptables` are invoked with `--count` > 1, it fails

### What did you expect to happen?

Unit tests should work for any `count`. This is important for troubleshooting flaking tests.

### How can we reproduce it (as minimally and precisely as possible)?

```
cd kubernetes/pkg/proxy/iptables
go test -count=2
I1108 09:09:52.713245  154009 proxier.go:809] "Sync failed" retryingTime="0s"
--- FAIL: TestSyncProxyRulesRepeated (0.00s)
    proxier_test.go:6685: Already did a partial resync? Something failed earlier!
FAIL
exit status 1
FAIL    k8s.io/kubernetes/pkg/proxy/iptables    0.432s
# count=1 works
go test 
ok      k8s.io/kubernetes/pkg/proxy/iptables    0.198s
```

### Anything else we need to know?

Discovered when I tried to add parallel execution as described in https://github.com/kubernetes/kubernetes/pull/121791

### Kubernetes version

master

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
`TestSyncProxyRulesRepeated` was making assertions about the value of the "partial restore failures" metric that assumed that it would be 0 at the start of the test, so it failed if you ran the test twice in one run.

#### Which issue(s) this PR fixes:
Fixes #121794

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/priority important-soon
/triage accepted
/assign @uablrek

### CODE REVIEW

**Comment by uablrek** [comment]
/lgtm

I also tested to add `t.Parallel()`, and the gain is small:
```
go test -count=100
ok      k8s.io/kubernetes/pkg/proxy/iptables    15.947s
go test -count=100 -parallel=1
ok      k8s.io/kubernetes/pkg/proxy/iptables    22.038s
```
All metric test cases omitted, but in `TestDeleteEndpointConnections()` the `t.Parallel()` _must_ be placed in the `t.Run()` function. There is something I don't understand ...

@aroradaman maybe you were on to something here https://github.com/kubernetes/kubernetes/pull/121791#discussion_r1386129138.

**Comment by danwinship** [comment]
> All metric test cases omitted, but in `TestDeleteEndpointConnections()` the `t.Parallel()` _must_ be placed in the `t.Run()` function. There is something I don't understand ...

I think placing it in the `t.Run()` just has no effect, and so it prevents parallelism. The problem is that the test checks `klog.Stats.Error.Lines()` to see how many messages got logged, so it's not parallel-safe. We'd have to rewrite that test (which would probably be an improvement...)

**Comment by danwinship** [comment]
> I think placing it in the `t.Run()` just has no effect

This is apparently not true: each `testing.T` context has its own parallelizability, so putting `t.Parallel()` at the start of the test says that the test can be run in parallel with other top-level tests, but does not cause its subtests to be run in parallel with each other, while `t.Parallel()` inside the `t.Run()` allows the subtests to be run in parallel with each other, but does not cause the parent test to be run in parallel with other top-level tests. (And `t.Parallel()` in both places allows both.)

(This may be why your changes didn't help `pkg/proxy/iptables` as much as `pkg/proxy/ipvs`; because more of the iptables tests use `t.Run()`, so you got less actual parallelization.)

At any rate, the problem with `TestDeleteEndpointConnections` is still that it's non-parallel-safe because it checks how many times klog has been called since it started.

**Comment by aojea** [comment]
for test with metrics the convention is to reset them https://github.com/kubernetes/kubernetes/pull/100218 and they must not never run in parallel

File: pkg/proxy/iptables/proxier_test.go [hunk 1]
```diff
@@ -6151,6 +6151,11 @@ func TestSyncProxyRulesRepeated(t *testing.T) {
 	fp := NewFakeProxier(ipt)
 	metrics.RegisterMetrics()
```
Comment (aojea) [inline pkg/proxy/iptables/proxier_test.go:6152]: just  reset them once the test finish

```suggestion
	metrics.RegisterMetrics()
         defer Metrics.reset()
	defer legacyregistry.Reset()
```

**Comment by aojea** [comment]
I don't encourage using t.Parallel unless we are hitting serious problems with timeouts, we had a bad time last time it was tried as it introduced a lot of flakiness in the CI and we had to revert them https://github.com/kubernetes/kubernetes/pull/112289#issuecomment-1256395695

**Comment by uablrek** [comment]
I closed https://github.com/kubernetes/kubernetes/pull/121791, but I still think it _must_ be possible to run unit-tests with `--count>1`, so this PR should be merged.

File: pkg/proxy/iptables/proxier_test.go (hunk 1 above)
Comment (uablrek) [reply pkg/proxy/iptables/proxier_test.go:6152]: If this makes it possible to run metric test in parallel in general, I think this should be a "standard pattern".

**Comment by uablrek** [comment]
Reasons that prevents parallel execution as I see it are:
1. Common data is used (as in the metrics tests)
2. A test-case relies on a previously executed test-case

The later is considered to be heresy if I understand correctly, but I have found it irresistible at times. IMO the test functions ("func test*") should be possible to run in parallel (unless common data is used), but not necessarily tests in `t.Run()`.

File: pkg/proxy/iptables/proxier_test.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:6152]: tests that use metrics can never run in parallel because store data in global variables

Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:6152]: This will work for running them sequentially multiple times, the test has to clear the state once it finish

**Comment by aojea** [comment]
> I closed #121791, but I still think it _must_ be possible to run unit-tests with `--count>1`, so this PR should be merged.

that is a must, I have a job to identify those and start fixing them, but it was removed because we never fixed all the tests and it was polluting the stats https://github.com/kubernetes/test-infra/pull/28869

/milestone v1.29

This is fixing a test so it qualifies to merge during the test freeze windows
