### PR TITLE
Skip kubectl tests that don't work before v1.1 when running against a pre-v1.1 cluster

### LINKED ISSUE #18581: Many Kubectl e2e tests in master are broken against 1.0 cluster
Googlers can find results here:

http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.0-master-step2-kubectl-e2e-new/

P0 for triaging impact, then we can go from there.

### PR DESCRIPTION
**Pull request by ikehz**
Fixes #18581.

We want signal when a newer Kubectl isn't working properly against an older cluster, but these tests make use of functionality that didn't exist pre-v1.1, so they aren't expected to work.  Skip them if we're running against a server that is pre-v1.1.

Some precedent in #18773.

cc @kubernetes/goog-csi for how I'm doing this, in case you hate it.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Reassigning to @krousey.

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -72,7 +73,30 @@ const (
...
+	proxyRegexp = regexp.MustCompile("Starting to serve on 127.0.0.1:([0-9]+)")
+
+	// Jobs were introduced in v1.1.0, so we don't expect tests that rely
+	// on jobs to work on clusters before that.
+	//
+	// TODO(ihmccreery): remove once we don't care about v1.0 anymore, (tentatively
+	// in v1.3).
+	jobsVersion = version.MustParse("v1.1.0")
+
+	// NodePorts were introduced in v1.1.0, so we don't expect tests that rely
```
Comment (krousey) [inline test/e2e/kubectl.go]: This is misleading. NodePorts always existed. They were made optional in v1.1.0. The errors you're guarding against are validation errors when clients omit them and servers expect them.

**Comment by krousey** [comment]
Fix the comments and add LGTM when you do. :fire_engine: 

If you want to do a follow up PR that changes all the subresource proxy check skipping and others to this new utility function, I would review that. :dango:

**Comment by ihmccreery** [comment]
Fixes #19608.

File: test/e2e/util.go [hunk 2]
```diff
@@ -287,6 +287,16 @@ func providerIs(providers ...string) bool {
 	return false
 }
 
+func SkipUnlessServerVersionGTE(v semver.Version, c client.VersionInterface) {
```
Comment (lavalamp) [inline test/e2e/util.go]: Name ideas:

RelevantAsOf
SkipOlderServers
SkipServerVersionsLT
FeatureAddedInVersion
FeaturePresentAfter

**Comment by lavalamp** [comment]
LGTM with fix for @krousey's comment

**Comment by ihmccreery** [comment]
Done, applying LGTM per @krousy.

**Comment by ihmccreery** [comment]
Had to re-rebase to get it to build, since `VersionInterface` changed to `ServerVersionInterface`.

**Comment by lavalamp** [comment]
I do have a minor preference for changing "SkipUnlessServerVersionGTE" to something else, so readers know that the version marks the addition of the feature and not something done just to get the test to pass.

**Comment by ihmccreery** [comment]
> I do have a minor preference for changing "SkipUnlessServerVersionGTE" to something else, so readers know that the version marks the addition of the feature and not something done just to get the test to pass.

Unfortunately, some of these are just to get the test to pass: the tests that don't contain a NodePorts would be expected to pass except for the NodePorts issue, AFAIK.

Maybe we should try to get those tests to be backward-compatible?

**Comment by lavalamp** [comment]
Oh, in that case I'm glad I said something. I think in such cases there has to be a comment explaining the situation, and there also needs to be an issue filed to fix the test.

**Comment by ihmccreery** [comment]
@k8s-bot unit test this again please

**Comment by krousey** [comment]
From what I recall, these failures fell into 3 categories:

 1) example spec files in master not being backward compatible, but still being used in tests with old versions (e.g. node port was removed, but is still a required field in 1.0)
 2) actually testing features that didn't exist
 3) underlying e2e utility functions switched to using features that didn't exist in 1.0 (e.g. exec util now specifies --restart=never on the kubectl command line, which in turn tries to create a job, which didn't exist in 1.0)

1 can be fixed by using different spec files. Perhaps create a set of compliance specs for each version. 2 is fine to just skip them. 3 is a little tricky. To me it seems we might just want to build kubectl at master, then check out the release we want, and run the e2e tests defined there.

**Comment by ihmccreery** [comment]
Let's continue this discussion back on https://github.com/kubernetes/kubernetes/issues/18581#issuecomment-164011158.

**Comment by ihmccreery** [comment]
@lavalamp would you mind reviewing since @krousey is out today?  Once this is in, I'll also need to backport to `release-1.1`.

**Comment by krousey** [comment]
@ihmccreery I didn't realize this was ready for review again. I can still do it. It looks as though you and @lavalamp are ok with this general approach?

**Comment by krousey** [comment]
This still looks good to me. Unless you want to address the naming suggestion that @lavalamp had, you can add my LGTM.

**Comment by ihmccreery** [comment]
I prefer my name because I think it's more accurate than @lavalamp's suggestions, but I'm happy to resolve in the reviewers' favor, (that's the usual policy).

... Also it seems like this isn't building.

File: test/e2e/util.go (hunk 2 above)
Comment (krousey) [inline test/e2e/util.go]: client.ServerVersionInterface I think...

Comment (krousey) [inline test/e2e/util.go]: https://github.com/kubernetes/kubernetes/pull/19300

**Comment by krousey** [comment]
Yea, @caesarxuchao moved and renamed an interface on you.

**Comment by ihmccreery** [comment]
Rebased, re-added LGTM.

**Comment by lavalamp** [comment]
My name suggestions are an attempt to get some semantic info into the test.
5 months from now when I look at this, I'd like to know *why* that version
comparison is being done. Comments can serve that purpose, too, but people
use them less consistently :)
