### PR TITLE
Ensure EndpointSlice exist if Endpoint is found

### LINKED ISSUE #84419: EndpointSlice is not created after enabling EndpointSlice on a pre-existing cluster
**What happened**:
EndpointSlice **for masters** was not created after enabling EndpointSlice on a pre-existing cluster. Only those EndpointSlices managed by kube-controller-manager were created.
```
# kubectl get endpointslice --all-namespaces
NAMESPACE     NAME             ADDRESSTYPE   PORTS     ENDPOINTS   AGE
kube-system   kube-dns-g25zd   IP            <unset>   <unset>     15m
```

**What you expected to happen**:
EndpointSlice for masters should be created after enabling EndpointSlice on a pre-existing cluster, the same as the EndpointSlices managed by kube-controller-manager.
```
# kubectl get endpointslice --all-namespaces
NAMESPACE     NAME             ADDRESSTYPE   PORTS     ENDPOINTS     AGE
default       kubernetes       IP            6443      XXXXX         0s
kube-system   kube-dns-g25zd   IP            <unset>   <unset>       15m
```
**How to reproduce it (as minimally and precisely as possible)**:

1. Use kubeadm to create a cluster: `kubeadm init`
2. Enable the EndpointSlice feature by editing the kube-apiserver, kube-controller-manager, kube-proxy manifest
3. After kube-apiserver and kube-controller-manager is restarted, the EndpointSlice `kubernetes` in `default` namespace will be missing.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
v1.16.2
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
```
kubeadm
```
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The EndpointSlice for masters was not created after enabling EndpointSlice feature on a pre-existing cluster. This was because the Endpoint object had been created and ReconcileEndpoints would skip creating or updating it after EndpointSlice feature is enabled.

This patch ensures EndpointSlice is consistent with Endpoints after the reconciler reconciles Endpoints even if Endpoints is unchanged. It also avoids an update if the desired EndpointSlice matches the existing one.

**Which issue(s) this PR fixes**:

Fixes #84419

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix the bug that EndpointSlice for masters wasn't created after enabling EndpointSlice feature on a pre-existing cluster.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
Hey @tnqn, thanks for catching this! Looks like a good fix on first glance, will try to take a closer look at this tomorrow.
/ok-to-test

**Comment by tnqn** [comment]
@robscott thanks for reviewing it.
/retest

File: pkg/master/reconcilers/endpointsadapter_test.go [hunk 1]
```diff
@@ -98,6 +108,28 @@ func TestEndpointsAdapterGet(t *testing.T) {
 			if !apiequality.Semantic.DeepEqual(endpoints, testCase.expectedEndpoints) {
 				t.Errorf("Expected endpoints: %v, got: %v", testCase.expectedEndpoints, endpoints)
 			}
+
+			epSliceList, err := client.DiscoveryV1alpha1().EndpointSlices(testCase.namespaceParam).List(metav1.ListOptions{})
```
Comment (robscott) [inline pkg/master/reconcilers/endpointsadapter_test.go]: All of this test logic can actually be simplified because the EndpointSlice created here will always have a consistent name (nameParam here, but generally just `kubernetes`). I think it would make sense to test based on the existence of that EndpointSlice specifically with a `Get` call instead of a `List`.

**Review by robscott — COMMENTED** [review]
Hey @tnqn, this looks great, just have a suggestion on how to simplify the tests you're adding. I spun up an e2e cluster with this branch and the upgrade worked as expected simply by toggling the EndpointSlice feature flag on the apiserver manifest. Thanks for the fix!

File: pkg/master/reconcilers/endpointsadapter_test.go (hunk 1 above)
Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter_test.go]: Makes sense. I have updated, PTAL.

**Comment by tnqn** [comment]
@robscott thanks for the suggestion!

File: pkg/master/reconcilers/endpointsadapter_test.go (hunk 1 above)
Comment (robscott) [reply pkg/master/reconcilers/endpointsadapter_test.go]: Hey @tnqn, this looks great, I think it could be simplified one more step to just use the deepEqual whether or not the expected value was nil. Something like what's done above for Endpoints: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/reconcilers/endpointsadapter_test.go#L262-L264

Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter_test.go]: Sure, done.

**Comment by robscott** [comment]
Thanks for catching this @tnqn! This fix works well for me. @liggit are you able to take a look here? I think you helped review/approve my initial PR here back in the day.

/lgtm

**Comment by robscott** [comment]
@liggitt are you able to take a look here? I think you helped review/approve my initial PR here back in the day. This looks like a good fix that should help anyone upgrading to a cluster with EndpointSlices enabled.

/assign @liggitt

File: pkg/master/reconcilers/endpointsadapter.go [hunk 2]
```diff
@@ -48,8 +48,14 @@ func NewEndpointsAdapter(endpointClient corev1client.EndpointsGetter, endpointSl
 
 // Get takes the name and namespace of the Endpoints resource, and returns a
 // corresponding Endpoints object if it exists, and an error if there is any.
+// If an Endpoints object is found and an endpointSliceClient exists, a
+// matching EndpointSlice will be created or updated.
 func (adapter *EndpointsAdapter) Get(namespace, name string, getOpts metav1.GetOptions) (*corev1.Endpoints, error) {
-	return adapter.endpointClient.Endpoints(namespace).Get(name, getOpts)
+	endpoints, err := adapter.endpointClient.Endpoints(namespace).Get(name, getOpts)
+	if err == nil && adapter.endpointSliceClient != nil {
+		_, err = adapter.ensureEndpointSliceFromEndpoints(namespace, endpoints)
```
Comment (liggitt) [inline pkg/master/reconcilers/endpointsadapter.go]: Doing a write in a Get method doesn't seem proper. I'd expect these to be written in the same place we persist the Endpoints object. 

Also, is endpointSliceClient when the feature is disabled?

Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter.go]: Thanks for reviewing.

The problem is when the Endpoints object is persisted, the EndpointSlice feature might not be enabled yet, like bootstrapping a cluster with kubeadm (which doesn't have a feature gate for endpointslice) or upgrading from a version that doesn't have EndpointSlice.  
Then after enabling this feature, when EndpointReconciler reconciles the endpoint, it will skip the creation as it finds an existing one. The Create method which is supposed to sync Endpoints and EndpointSlice gets no chance to run. 

Since the EndpointsAdapter is in charge of reading and writing both Endpoints and EndpointSlices and keeping reconciler EndpointSlices agnostic, I thought it might be better to not break it so make Endpoints and EndpointSlices consistent in Get method in the same way as Create/Update methods do. Otherwise the EndpointReconciler might need to be adjusted to call epAdaptor.Create even if epAdaptor.Get finds one. https://github.com/kubernetes/kubernetes/blob/362e17ff9fdc2639de7cc465bfea2150d7d56a40/pkg/master/reconcilers/lease.go#L162-L170

endpointSliceClient is nil when the feature is disabled, the added code follows the way in which Create/Update method decides whether to sync EndpointSlice.
https://github.com/kubernetes/kubernetes/blob/362e17ff9fdc2639de7cc465bfea2150d7d56a40/pkg/master/master.go#L240-L244

Please let me know if the explanation makes sense to you. If not, could you suggest a proper way to fix it?

Comment (robscott) [reply pkg/master/reconcilers/endpointsadapter.go]: I hadn't thought that through, but you're completely right that a `Get` method really shouldn't be writing anything. An approach with the least required change would be to rename the method, but it's hard to come up with a reasonable name - `GetEndpointsAndEnsureEndpointSlices` seems like it would be too long. 

What might make more sense would be to modify each of the reconcilers to call `r.epAdapter.ensureEndpointSliceFromEndpoints(namespace, endpoints)` at the end of their `ReconcileEndpoints` methods. That would require adding a check inside that method to ensure an `endpointSliceClient` was set on the adapter, but otherwise would be relatively straightforward I think.

**Comment by liggitt** [comment]
> This was because the Endpoint object had been created and ReconcileEndpoints would skip creating or updating it after EndpointSlice feature is enabled.

Can you clarify this point? Does the endpoints controller not reconcile the `kube-system`/`kubernetes` Endpoints object to an EndpointsSlice object?

File: pkg/master/reconcilers/endpointsadapter.go (hunk 2 above)
Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter.go]: > What might make more sense would be to modify each of the reconcilers to call `r.epAdapter.ensureEndpointSliceFromEndpoints(namespace, endpoints)` at the end of their `ReconcileEndpoints` methods. That would require adding a check inside that method to ensure an `endpointSliceClient` was set on the adapter, but otherwise would be relatively straightforward I think.
> 
I tried not to break the current EndpointAdaptor's effort that minimizes change to reconcilers and keeps it EndpointSlice agnostic. If adding`r.epAdapter.ensureEndpointSliceFromEndpoints` to the end of `ReconcileEndpoints` methods, I'm not sure whether it still makes sense to keep the adapter because calling `ensureEndpointSliceFromEndpoints` in `r.epAdapter.Create` and `r.epAdapter.Update` would be unnecessary (because it might get called twice each time). There could just be a ensureEndpointSliceFromEndpoints call after reconciling the endpoint no matter the endpoint is created/update/not changed.

To keep the change small, I updated the method name to `GetAndSync`, does it make sense to you? Or you would prefer adding this explicit call `ensureEndpointSliceFromEndpoints` to [doReconcile](https://github.com/kubernetes/kubernetes/blob/8d8a0684866d75aa195de20871a6164794b11ebc/pkg/master/reconcilers/lease.go#L162)?

**Comment by tnqn** [comment]
> > This was because the Endpoint object had been created and ReconcileEndpoints would skip creating or updating it after EndpointSlice feature is enabled.
> 
> Can you clarify this point? Does the endpoints controller not reconcile the `kube-system`/`kubernetes` Endpoints object to an EndpointsSlice object? 
Or is the issue that the masters must bootstrap their EndpointsSlice object just like their Endpoints object in order to make sure the API server is reachable from wherever the kube-controller-manager is running?

The endpoints controller is not in charge of the `default/kubernetes` Endpoints and EndpointSlice:
https://github.com/kubernetes/kubernetes/blob/8d8a0684866d75aa195de20871a6164794b11ebc/pkg/controller/endpointslice/endpointslice_controller.go#L260-L264
It's the `EndpointReconciler` (leaseEndpointReconciler by default) in masters reconciling its Endpoints and EndpointSlice: https://github.com/kubernetes/kubernetes/blob/8d8a0684866d75aa195de20871a6164794b11ebc/pkg/master/reconcilers/lease.go#L162
I think it's the same issue you mentioned that EndpointSlices for masters must be created by themselves to make kube-controller-manager reach them.

File: pkg/master/reconcilers/endpointsadapter.go (hunk 2 above)
Comment (liggitt) [reply pkg/master/reconcilers/endpointsadapter.go]: we should not change this from a getter to a getter+writer. syncing from endpoints to endpointslices in the getter means that a single invocation of doReconcile will complete with the two resources not matching (and the endpointslice won't be corrected until the **next** invocation of doReconcile, which is not what we want).

Comment (liggitt) [reply pkg/master/reconcilers/endpointsadapter.go]: > If addingr.epAdapter.ensureEndpointSliceFromEndpoints to the end of ReconcileEndpoints methods, I'm not sure whether it still makes sense to keep the adapter

yeah... unfortunately, a lot of the logic in doReconcile makes assumptions about the endpoint implementation (the short-circuiting logic assumes that only a single resource is being managed, for example).

> There could just be a ensureEndpointSliceFromEndpoints call after reconciling the endpoint no matter the endpoint is created/update/not changed.

calling ensureEndpointSliceFromEndpoints() just before all non-error returns from doReconcile (even short-circuits) seems like it could work.

Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter.go]: I have updated as you suggested, PTAL. Thanks!

File: pkg/master/reconcilers/endpointsadapter.go [hunk 3]
```diff
@@ -69,18 +70,21 @@ func (adapter *EndpointsAdapter) Create(namespace string, endpoints *corev1.Endp
...
 }
 
-// ensureEndpointSliceFromEndpoints accepts a namespace and Endpoints resource
-// and creates or updates a corresponding EndpointSlice. The EndpointSlice
-// and/or an error will be returned.
-func (adapter *EndpointsAdapter) ensureEndpointSliceFromEndpoints(namespace string, endpoints *corev1.Endpoints) (*discovery.EndpointSlice, error) {
+// EnsureEndpointSliceFromEndpoints accepts a namespace and Endpoints resource
+// and creates or updates a corresponding EndpointSlice if an endpointSliceClient
+// exists. The EndpointSlice and/or an error will be returned.
+func (adapter *EndpointsAdapter) EnsureEndpointSliceFromEndpoints(namespace string, endpoints *corev1.Endpoints) (*discovery.EndpointSlice, error) {
```
Comment (liggitt) [inline pkg/master/reconcilers/endpointsadapter.go]: the `*discovery.EndpointSlice` return value is never used, and can be nil if the endpointsslice client is not set. I'd suggest omitting the return value.

Comment (tnqn) [reply pkg/master/reconcilers/endpointsadapter.go]: Done

**Comment by tnqn** [comment]
Thanks! @liggitt

/retest

**Comment by robscott** [comment]
Thanks for all your work on this @tnqn!

/lgtm
