### PR TITLE
Make reapers set DeleteOptions.OrphanDependents=false

### LINKED ISSUE #44508: Deployment tests on 1.4 GKE upgrade suites fail
https://storage.googleapis.com/k8s-gubernator/triage/index.html#19be14db86cdc1fad53e

Fails 3 builds and 30 tests every hour.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.4-gci-latest-upgrade-master/788

https://k8s-testgrid.appspot.com/google-gke-latest-upgrade#Summary

/assign @liggitt @michelleN @mattfarina 

FYI one way to solve this is to just delete these jobs: https://github.com/kubernetes/test-infra/pull/2489

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #44508

### CODE REVIEW

File: pkg/kubectl/stop.go [hunk 1]
```diff
@@ -509,3 +507,7 @@ func (reaper *ServiceReaper) Stop(namespace, name string, timeout time.Duration,
 	}
 	return services.Delete(name)
 }
+
+func getNonOrphanDeleteOptions() *api.DeleteOptions {
+	return &api.DeleteOptions{OrphanDependents: new(bool)}
```
Comment (krmayankk) [inline pkg/kubectl/stop.go]: i am guessing , this sets the OrphanDependents to false. Why not explicitly say false, rather having the reader guess that its false ? That will improve readability in imo

**Comment by caesarxuchao** [comment]
@janetkuo failing unit test looks relevant.

**Comment by janetkuo** [comment]
Can't reproduce unit test failure locally so re-run the test 
@k8s-bot unit test this

File: pkg/kubectl/stop.go (hunk 1 above)
Comment (janetkuo) [inline pkg/kubectl/stop.go]: @krmayankk thanks for the comment. From https://golang.org/doc/effective_go.html#allocation_new: `new(T)` returns a `*T` pointer to a zero value of type `T`. In this case, `new(bool)` returns a `*bool` pointer to `false`. I don't think it's not readable, and the function name also tells you what'll be returned.

**Comment by janetkuo** [comment]
Jobs don't like `api.DeletionOptions` so removing it from job reaper. This PR is mainly for Deployment reaper anyways.

**Comment by janetkuo** [comment]
Applying lgtm since it's just reverting the change to job reaper which broke the tests and wasn't the target of this fix

File: pkg/kubectl/stop.go (hunk 1 above)
Comment (krmayankk) [inline pkg/kubectl/stop.go]: Yep agreed about the documentation, but readability wise 
`return &api.DeleteOptions{OrphanDependents: false}` vs `return &api.DeleteOptions{OrphanDependents: new(bool)}`, i would always pick the former :-). I agree the function name should be helpful as well.

**Review by krmayankk — APPROVED** [review]

File: pkg/kubectl/stop.go (hunk 1 above)
Comment (kargakis) [inline pkg/kubectl/stop.go]: `&api.DeleteOptions{OrphanDependents: false}` won't work because the boolean passed to `OrphanDependents` needs to be a pointer. Hence, the use of `new`.

Comment (krmayankk) [inline pkg/kubectl/stop.go]: how about `&api.DeleteOptions{OrphanDependents: &falseVar}`

**Comment by fejta** [comment]
/assign @jessfraz 

Thanks Jess!!
