### PR TITLE
skip checking nodeport on external addrs in conformance tests

### LINKED ISSUE #90764: NodePort service creation e2e test relies on insecure cluster configuration
**What happened**:
We ran sonobuoy on one of our clusters running on AWS and it reported two failed tests:

```
Failed tests:
[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
[sig-network] Services should be able to create a functioning NodePort service [Conformance]
```

This happened because the pod employed to conduct the tests wasn't able to reach the service using the node's public IP address:

```
May  5 13:06:53.749: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 nodeport-test 80'
May  5 13:06:54.184: INFO: stderr: "+ nc -zv -t -w 2 nodeport-test 80\nConnection to nodeport-test 80 port [tcp/http] succeeded!\n"
May  5 13:06:54.184: INFO: stdout: ""
May  5 13:06:54.185: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 10.0.52.70 80'
May  5 13:06:54.463: INFO: stderr: "+ nc -zv -t -w 2 10.0.52.70 80\nConnection to 10.0.52.70 80 port [tcp/http] succeeded!\n"
May  5 13:06:54.463: INFO: stdout: ""
May  5 13:06:54.463: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 10.0.129.65 30953'
May  5 13:06:54.734: INFO: stderr: "+ nc -zv -t -w 2 10.0.129.65 30953\nConnection to 10.0.129.65 30953 port [tcp/30953] succeeded!\n"
May  5 13:06:54.734: INFO: stdout: ""
May  5 13:06:54.734: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 10.0.130.112 30953'
May  5 13:06:55.007: INFO: stderr: "+ nc -zv -t -w 2 10.0.130.112 30953\nConnection to 10.0.130.112 30953 port [tcp/30953] succeeded!\n"
May  5 13:06:55.007: INFO: stdout: ""
May  5 13:06:55.007: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 34.222.171.25 30953'
May  5 13:06:57.265: INFO: rc: 1
May  5 13:06:57.266: INFO: Service reachability failing with error: error running /usr/local/bin/kubectl --kubeconfig=/tmp/kubeconfig-494270924 exec --namespace=services-4785 execpodcn228 -- /bin/sh -x -c nc -zv -t -w 2 34.222.171.25 3095
Command stdout:

stderr:
+ nc -zv -t -w 2 34.222.171.25 30953
nc: connect to 34.222.171.25 port 30953 (tcp) timed out: Operation in progress
command terminated with exit code 1
```

**What you expected to happen**:
The security groups on that cluster don't allow for connections to arbitrary ports through the public IP address. The tests should still succeed because that configuration is seen as a security feature.

**How to reproduce it (as minimally and precisely as possible)**:
Spin up a Kubernetes cluster on AWS EC2 instances, configure SGs to only allow traffic to the instances from other instances (or from an ELB). Run sonobuoy.

**Anything else we need to know?**:

**Environment**: AWS
- Kubernetes version (use `kubectl version`): 1.16.8
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug
/sig testing
/sig network

**What this PR does / why we need it**:
In some user scenarios, the external IP nodeport is for access from APPs outside this cluster/zone.

- However, in most scenarios, external IP is just for SSH or special use(Ingress Gateway, etc.)

Different users have different proposals.

> most of the network tests now run from the cluster, no need to reach externalIPs.

Per https://github.com/kubernetes/kubernetes/issues/90764#issuecomment-775833055, I prefer to remove it before a clear definition for the external IPs.

> **move ExternalIP from Conformance entirely until it has a clear definition**

**Which issue(s) this PR fixes**:
Fixes #90764

**Special notes for your reviewer**:
And @BenTheElder suggestion is like adding a feature filter. I will work on it if this is needed.
> Per https://github.com/kubernetes/kubernetes/pull/98791#discussion_r572480431, I will add new test with `[Feature:ExternalNodeAccess]` and remove current case. [WIP]

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

File: test/e2e/framework/service/jig.go [hunk 1]
```diff
@@ -858,15 +858,20 @@ func testReachabilityOverNodePorts(nodes *v1.NodeList, sp v1.ServicePort, pod *v
...
-		if isClusterIPV4 != isNodeExternalIPV4 {
-			framework.Logf("skipping testEndpointReachability() for external adddress %s as it does not match clusterIP (%s) family", externalAddr, clusterIP)
-			continue
-		}
-		err := testEndpointReachability(externalAddr, sp.NodePort, sp.Protocol, pod)
-		if err != nil {
-			return err
+
+	// By default, skip node port checking with node external ips
+	if os.Getenv("CHECK_NODEPORT_WITH_EXTERNALADDR") == "true" {
```
Comment (aojea) [inline test/e2e/framework/service/jig.go:863]: let me ask about this, I´m not sure how @BenTheElder @spiffxp prefer to parameterise these things?

Comment (pacoxu) [reply test/e2e/framework/service/jig.go:863]: I'm not sure whether it is rude to remove this directly.

BTW, we should decide the default behavior: skip or check?

Comment (aojea) [reply test/e2e/framework/service/jig.go:863]: ah yeah, but there is a miriad of flags, skips, checks, ... just what I prefer to wait for them so we can align all the test to behave the same

Comment (BenTheElder) [reply test/e2e/framework/service/jig.go:863]: I think this is usually done with a flag? though this seems awfully specific.

Also conformance tests should not have variable behavior, so IMO the correct answer is actually to split this out into another test and give it tag to filter on if we're keeping this test.

Changes to conformance tests behavior should also be approved by the conformance subproject.

Comment (BenTheElder) [reply test/e2e/framework/service/jig.go:863]: so like `[Feature:ExternalNodeAccess]` on the new tests or something.

But also why are we changing this? commenting back on the issue.
Just because some clusters can fail it doesn't necessarily mean we change conformance 😕

Comment (pacoxu) [reply test/e2e/framework/service/jig.go:863]: for the PR, I will update as you suggest later after the holiday(maybe a week later😄)

for the issue, we can disscuss it in #90764.

**Comment by pacoxu** [comment]
I updated the PR. We may remove it as this is not clear.( I should be removed for "secured clusters"  )

> most of the network tests now run from the cluster, no need to reach externalIPs.

Per https://github.com/kubernetes/kubernetes/issues/90764#issuecomment-775833055, I prefer to remove it before a clear definition for the external IPs.

**Comment by aojea** [comment]
> I prefer to remove it before a clear definition for the external IPs.

> I personally, would move ExternalIP from Conformance entirely until it has a clear definition

from conformance, not from sig-network tests :smile: 

but that is a call that conformance people has to do, my point is that verifying in Conformance something that is not well-defined is not very conformant :upside_down_face:

**Comment by pacoxu** [comment]
> > I prefer to remove it before a clear definition for the external IPs.
> 
> > I personally, would move ExternalIP from Conformance entirely until it has a clear definition
> 
> from conformance, not from sig-network tests 😄
> 
> but that is a call that conformance people has to do, my point is that verifying in Conformance something that is not well-defined is not very conformant 🙃

I think that I got it. Sorry for misunderstanding. 😂

- test case with `framework.ConformanceIt()`  will be included in conformance test.
- test case with `framework.It()`  will not be included

What we should do is removing it from Conformance test cases and check it in other cases.

**Comment by aojea** [comment]
let's hold until the discussion ends, Conformance has to make the call, and then we'll talk with sig-testing to see what is the best way to implement it

**Comment by aojea** [comment]
I think that this makes it, but I think that it will be better to add it as a new field part of the TestJig
```
// TestJig is a test jig to help service testing.
type TestJig struct {
	Client    clientset.Interface
	Namespace string
	Name      string
	ID        string
	Labels    map[string]string
        ExternalIPs bool
}
```
something like `TestJig.ExternalIPs=true`  or `TestJig.Conformance=true`, so consumers of the TestJig can define it's behaviour in the object.

It sounds more scalable and intuitive to me, what do you think?

**Comment by spiffxp** [comment]
Yeah I like that approach. I prefer ExternalIPs as the field name, it's more explicit about what's being enabled or disabled.

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/milestone v1.21
