### PR TITLE
Fixed using reference in for loop

### LINKED ISSUE #105425: Report a coding issue that uses reference to loop iterator variable.
#### What happened:

At https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/cluster_size_autoscaling.go#L1251-L1253,
within the loop `for _, node := range nodeList.Items`, variable `node` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of &node within the loop may refer to the last node item updated by the loop. As a consequence, `nodes` may hold multiple instances of the same node.
```
	for _, node := range nodeList.Items {
		if node.Labels[gkeNodepoolNameKey] == poolName {
			nodes = append(nodes, &node)
		}
	}
```

Note that the following unit test checks only the number of nodes rather than the nodes themselves (otherwise the bug may be revealed):
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/autoscaling/cluster_size_autoscaling.go#L262

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

#### What you expected to happen:

A fixe is to avoid reusing the shared variable `node`:

```
	for i, node := range nodeList.Items {
		if node.Labels[gkeNodepoolNameKey] == poolName {
			nodes = append(nodes, &nodeList.Items[i])
		}
	}
```

Found by #deepgo.

### LINKED ISSUE #105426: Report a coding issue that uses reference to loop iterator variable
#### What happened:

At https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L969-L971,
within the loop `for _, pv := range allPVs.Items`, variable `pv` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of &pv within the loop may refer to the last tem updated by the loop. As a consequence, `remainingPVs` may hold multiple instances of the same item.
```
		for _, pv := range allPVs.Items {
			if pv.Spec.StorageClassName == scName {
				remainingPVs = append(remainingPVs, &pv)
			}
		}
```
Later on these remaining PVs are deleted, so it is possible that the same `pv` is deleted multiple times:
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/storage/volume_provisioning.go#L462-L464
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/storage/volume_provisioning.go#L999-L1001

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

#### What you expected to happen:

A fix is to avoid reusing the shared variable node:
```
		for i, pv := range allPVs.Items {
			if pv.Spec.StorageClassName == scName {
				remainingPVs = append(remainingPVs, &allPVs.Items[i])
			}
		}
```

**Found by #deepgo.**

### PR DESCRIPTION
**Pull request by shivanshuraj1333**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Current code incorrectly uses for loop and passes wrong value as reference
Guide to refer https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/105426
Fixes https://github.com/kubernetes/kubernetes/issues/105425

#### Special notes for your reviewer:
Please refer to sample code to understand the bug https://goplay.space/#TIT_IZEAEud

```
package main

import "fmt"

type st struct {
	it []string
}

func main() {
	rp := &st{[]string{"value1", "value2"}}
	ownedReplicaSets1 := make([]*string, 0, len(rp.it))
	ownedReplicaSets2 := make([]*string, 0, len(rp.it))

	// similar to current implementation
	for _, t := range rp.it {
		ownedReplicaSets1 = append(ownedReplicaSets1, &t)
	}

	fmt.Println(ownedReplicaSets1)
	fmt.Println(*ownedReplicaSets1[0], *ownedReplicaSets1[1])

	// similar new change
	for i := range rp.it {
		ownedReplicaSets2 = append(ownedReplicaSets2, &rp.it[i])
	}

	fmt.Println(ownedReplicaSets2)
	fmt.Println(*ownedReplicaSets2[0], *ownedReplicaSets2[1])
}
```

```
output:
value2 value2
[0xc000054020 0xc000054030]
value1 value2
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by shivanshu1333** [comment]
ping @pohly

File: test/e2e/autoscaling/cluster_size_autoscaling.go [hunk 1]
```diff
@@ -778,8 +778,8 @@ var _ = SIGDescribe("Cluster size autoscaling [Slow]", func() {
 		}.AsSelector().String()})
 		framework.ExpectNoError(err)
 
-		for _, node := range nodes.Items {
-			err = makeNodeUnschedulable(f.ClientSet, &node)
+		for i, node := range nodes.Items {
+			err = makeNodeUnschedulable(f.ClientSet, &nodes.Items[i])
```
Comment (pohly) [inline test/e2e/autoscaling/cluster_size_autoscaling.go:782]: You can drop this change.

File: test/e2e/autoscaling/cluster_size_autoscaling.go [hunk 2]
```diff
@@ -1656,8 +1657,8 @@ func buildAntiAffinity(labels map[string]string) *v1.Affinity {
 // 3b. increase number of replicas in RC by podsPerNode
 func runReplicatedPodOnEachNode(f *framework.Framework, nodes []v1.Node, namespace string, podsPerNode int, id string, labels map[string]string, memRequest int64) error {
 	ginkgo.By("Run a pod on each node")
-	for _, node := range nodes {
-		err := makeNodeUnschedulable(f.ClientSet, &node)
+	for i, node := range nodes {
+		err := makeNodeUnschedulable(f.ClientSet, &nodes[i])
```
Comment (pohly) [inline test/e2e/autoscaling/cluster_size_autoscaling.go:1661]: You can drop this change.

File: test/e2e/autoscaling/cluster_size_autoscaling.go [hunk 3]
```diff
@@ -1686,7 +1687,7 @@ func runReplicatedPodOnEachNode(f *framework.Framework, nodes []v1.Node, namespa
 		return err
 	}
 	for i, node := range nodes {
-		err = makeNodeSchedulable(f.ClientSet, &node, false)
+		err = makeNodeSchedulable(f.ClientSet, &nodes[i], false)
```
Comment (pohly) [inline test/e2e/autoscaling/cluster_size_autoscaling.go:1690]: You can drop this change.

File: test/e2e/autoscaling/cluster_size_autoscaling.go [hunk 4]
```diff
@@ -1719,7 +1720,7 @@ func runReplicatedPodOnEachNode(f *framework.Framework, nodes []v1.Node, namespa
 		if err != nil {
 			return fmt.Errorf("failed to coerce RC into spawning a pod on node %s within timeout", node.Name)
 		}
-		err = makeNodeUnschedulable(f.ClientSet, &node)
+		err = makeNodeUnschedulable(f.ClientSet, &nodes[i])
```
Comment (pohly) [inline test/e2e/autoscaling/cluster_size_autoscaling.go:1723]: You can drop this change.

**Review by pohly — CHANGES_REQUESTED** [review]

**Comment by shivanshu1333** [comment]
ping @pohly for approval

**Review by pohly — APPROVED** [review]
/lgtm
/retest

**Comment by pohly** [comment]
/assign @bskiba

For approval as suggested by bot.
