### PR TITLE
kube-scheduler: Fix a misleading error message in the VolumeRestrictions plugin

### LINKED ISSUE #129143: Kube scheduler has a confusing error message when scheduling pods that use claims with `ReadWriteOncePod` access mode
### What happened?

When we deploy a claim like:
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
  - ReadWriteOncePod
  resources:
    requests:
      storage: 4Gi
```

And then deploy two pods:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```
Second pod is rightfully not scheduled.
It has the following error message:
```
 k describe po app2

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  5s    default-scheduler  0/5 nodes are available: 5 node has pod using PersistentVolumeClaim with the same name and ReadWriteOncePod access mode. preemption: 0/5 nodes are available: 5 No preemption victims found for incoming pod.
  Warning  FailedScheduling  2s    default-scheduler  0/5 nodes are available: 5 node has pod using PersistentVolumeClaim with the same name and ReadWriteOncePod access mode. preemption: 0/5 nodes are available: 5 No preemption victims found for incoming pod.
```
This error message is misleading - there are no 5 nodes that have pods using this PersistentVolumeClaim.

Error message comes from https://github.com/kubernetes/kubernetes/blob/v1.30.5/pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go#L55.
It's set in the following method - https://github.com/kubernetes/kubernetes/blob/v1.30.5/pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go#L280
It's raised upon calling the `Filter` method - https://github.com/kubernetes/kubernetes/blob/v1.30.5/pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go#L314

### What did you expect to happen?

I expect that we get an error message that reads something like:
```
  Warning  FailedScheduling  5s    default-scheduler  0/5 nodes are available: 5 nodes were not able to schedule a pod using PersistentVolumeClaim <PVC-Name> name, ReadWriteOncePod access mode. preemption: 0/5 nodes are available: 5 No preemption victims found for incoming pod.
```

or similar message, that points the operator to the actual reason for not scheduling the pod.

### How can we reproduce it (as minimally and precisely as possible)?

Build a cluster with 3 or more nodes and apply the following manifests:
```ymal
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
  - ReadWriteOncePod
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
k version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.30.5
```

</details>

but I believe it's applicable for other versions as well.

### Cloud provider

Message is the same, regardless of the provider.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/issues/129143

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/129143

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
ping @sig-storage-approvers

File: pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go [hunk 1]
```diff
@@ -54,8 +54,8 @@ const (
 
 	// ErrReasonDiskConflict is used for NoDiskConflict predicate error.
 	ErrReasonDiskConflict = "node(s) had no available disk"
-	// ErrReasonReadWriteOncePodConflict is used when a pod is found using the same PVC with the ReadWriteOncePod access mode.
-	ErrReasonReadWriteOncePodConflict = "node has pod using PersistentVolumeClaim with the same name and ReadWriteOncePod access mode"
+	// ErrReasonReadWriteOncePodConflict is used when a PVC with ReadWriteOncePod access mode is already in-use by another pod.
+	ErrReasonReadWriteOncePodConflict = "node(s) unavailable due to PersistentVolumeClaim with ReadWriteOncePod access mode already in-use by another pod"
```
Comment (haosdent) [inline pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go:58]: Should we change the var name as well?

**Review by googs1025 — COMMENTED** [review]
node(s) are unschedulable due to PersistentVolumeClaim with ReadWriteOncePod access mode already in-use by another pod.

File: pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go (hunk 1 above)
Comment (googs1025) [reply pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go:58]: `node(s) are unschedulable due to PersistentVolumeClaim with ReadWriteOncePod access mode already in-use by another pod`

Comment (ialidzhikov) [reply pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go:58]: With this PR we are just explaining the error in a better format so that the error message does not confuse the users.
Do you have a suggestion for better naming?

Comment (ialidzhikov) [reply pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go:58]: > node(s) are unschedulable due to PersistentVolumeClaim with ReadWriteOncePod access mode already in-use by another pod.

@googs1025  I used `unavailable` instead of `unschedulable` to be consistent with the following already existing error message: https://github.com/kubernetes/kubernetes/blob/3a6a4830df003d8efcad7bd8e4f0cce609aee2ca/pkg/scheduler/framework/plugins/volumebinding/binder.go#L71-L72

I couldn't find a similar error message where `unschedulable` instead of `unavailable`. If you see such, I am open to change it.

Comment (googs1025) [reply pkg/scheduler/framework/plugins/volumerestrictions/volume_restrictions.go:58]: got this. I am fine with both

**Review by hashim21223445 — APPROVED** [review]

**Comment by ialidzhikov** [comment]
Hi folks,

Can someone please review this PR?
