### PR TITLE
logcheck update and golangci-lint integration

### LINKED ISSUE #106746: logcheck: not applied to packages under staging
### What happened?

I recently added a benchmark to staging/src/k8s.io/component-base/logs/benchmark which has code that triggers an error from current logcheck (`ErrorS` is passed a slice with `...` - valid, but not handled by the tool). See https://github.com/kubernetes/kubernetes/pull/106594

I did not get an error for that from `pull-kubernetes-verify`.

I did get it only after moving the benchmark to `test/integration/logs/benchmark`.

/wg structured-logging
/sig instrumentation

### What did you expect to happen?

`pull-kubernetes-verify` should check staging repos.

### How can we reproduce it (as minimally and precisely as possible)?

Add broken code:
```
diff --git a/staging/src/k8s.io/component-base/logs/logs.go b/staging/src/k8s.io/component-base/logs/logs.go
index 0f494deedd0..9a9cc890e6f 100644
--- a/staging/src/k8s.io/component-base/logs/logs.go
+++ b/staging/src/k8s.io/component-base/logs/logs.go
@@ -203,3 +203,7 @@ func GlogSetter(val string) (string, error) {
        }
        return fmt.Sprintf("successfully set klog.logging.verbosity to %s", val), nil
 }
+
+func thisIsBroken() {
+       klog.InfoS("hello world", "missingValue")
+}
```

Run `hack/verify-structured-logging.sh`. It should complain about that code.

### Anything else we need to know?

This invocation covers vendor:
https://github.com/kubernetes/kubernetes/blob/c1153d3353bd4f4b68d85245d53d2745586be474/hack/verify-structured-logging.sh#L86-L88

In my case, one of the parameters is `/nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/...`.

### Kubernetes version

master

### Cloud provider

NA

### OS version

Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The [updated logcheck](https://github.com/kubernetes/klog/pull/297) finds additional problems and thanks to the integration into golangci-lint runs more efficiently and correctly (didn't check staging before).

#### Which issue(s) this PR fixes:
Fixes #106746, https://github.com/kubernetes/kubernetes/issues/108854, https://github.com/kubernetes/kubernetes/issues/106276, https://github.com/kubernetes/kubernetes/issues/105841, https://github.com/kubernetes/klog/issues/214

#### Special notes for your reviewer:

The lack of tagging for logcheck is tracked in https://github.com/kubernetes/klog/issues/312

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-scheduler/app/options/configfile.go [hunk 1]
```diff
@@ -93,7 +93,7 @@ func LogOrWriteConfig(fileName string, cfg *config.KubeSchedulerConfiguration, c
 	}
 
 	if klogV.Enabled() {
-		klogV.Info("Using component config", "\n-------------------------Configuration File Contents Start Here---------------------- \n", buf.String(), "\n------------------------------------Configuration File Contents End Here---------------------------------\n")
+		klogV.InfoS("Using component config", "config", buf.String())
```
Comment (serathius) [inline cmd/kube-scheduler/app/options/configfile.go:96]: I think there was some discussion about line for multi line logging. Have it been resolved, or we are just fixing this due to logcheck? 

If we haven't resolved the multi line discussion it would be better to not mark this directory for logcheck.

File: hack/logcheck.conf [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+structured k8s.io/kubernetes/pkg/proxy/.*
+structured k8s.io/kubernetes/pkg/scheduler/apis/.*
+structured k8s.io/kubernetes/pkg/scheduler/framework/.*
+structured k8s.io/kubernetes/pkg/scheduler/internal/cache/fake/.*
+structured k8s.io/kubernetes/pkg/scheduler/internal/heap/.*
+structured k8s.io/kubernetes/pkg/scheduler/internal/queue/.*
+structured k8s.io/kubernetes/pkg/scheduler/metrics/.*
+structured k8s.io/kubernetes/pkg/scheduler/profile/.*
+structured k8s.io/kubernetes/pkg/scheduler/testing/.*
+structured k8s.io/kubernetes/pkg/scheduler/util/.*
```
Comment (serathius) [inline hack/logcheck.conf:30]: Could we mark parent directory as migrated instead? We could not do it previously due to limitations of the logcheck before.

File: pkg/kubelet/pleg/generic.go [hunk 3]
```diff
@@ -406,6 +406,9 @@ func (g *GenericPLEG) updateCache(pod *kubecontainer.Pod, pid types.UID) error {
 	// all containers again.
 	status, err := g.runtime.GetPodStatus(pod.ID, pod.Name, pod.Namespace)
 	if err != nil {
+		// nolint:logcheck // Not using the result of klog.V inside the
+		// if branch is okay, we just use it to determine whether the
+		// additional parameter should be used.
```
Comment (serathius) [inline pkg/kubelet/pleg/generic.go:411]: Don't understand the commend about `additional parameter`

File: cmd/kube-scheduler/app/options/configfile.go (hunk 1 above)
Comment (serathius) [reply cmd/kube-scheduler/app/options/configfile.go:96]: sg

File: hack/logcheck.conf (hunk 2 above)
Comment (pohly) [reply hack/logcheck.conf:30]: You are right, a single line is enough now.

File: pkg/kubelet/pleg/generic.go (hunk 3 above)
Comment (pohly) [reply pkg/kubelet/pleg/generic.go:411]: That refers to the `"podStatus", status` key/value pair which only gets included at higher log levels. Comment updated.

File: hack/logcheck.conf (hunk 2 above)
Comment (pohly) [reply hack/logcheck.conf]: Argh, I fell into that trap that is mentioned in the file (stale golangci-lint cache). After cleaning the cache, logcheck (correctly) points out [the remaining work](https://github.com/kubernetes/kubernetes/issues/105841):
```
pkg/scheduler/internal/cache/debugger/dumper.go:49:3: unstructured logging function "Info" should not be used (logcheck)
		klog.Info(d.printNodeInfo(name, nodeInfo))
		^
pkg/scheduler/internal/cache/debugger/dumper.go:60:2: unstructured logging function "Infof" should not be used (logcheck)
	klog.Infof("Dump of scheduling queue:\n%s", podData.String())
```

I think we concluded that a text dump is okay here, also for JSON. I'll include a conversion of these lines to `klog.InfoS`.

Comment (pohly) [reply hack/logcheck.conf]: Done.

The current kube-scheduler output with these changes is in the updated commit message of the first commit.

File: hack/logcheck.conf [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+# those calls is not required. That is changed on a per-file basis.
+#
+# Remember to clean the golangci-lint cache when changing the configuration and
+# running the verify-golangci-lint.sh script multiple times, otherwise
+# golangci-lint will report stale results:
+#    _output/local/bin/golangci-lint cache clean
+
+# At this point we don't enforce the usage structured logging calls except in
+# those packages that were migrated. This disables the check for other files.
+-structured *
```
Comment (serathius) [inline hack/logcheck.conf:14]: Is just a `*` correct regexp to match any? Should it not be `.*`?

Comment (pohly) [reply hack/logcheck.conf:14]: True.

Compiling that regexp should have failed. Let me check that.

/hold

Comment (pohly) [reply hack/logcheck.conf:14]: `*` fails to compile, but logcheck surrounds and `^*$` compiles. `^(*)$` then fails again. The latter is probably what I'll use.

Comment (pohly) [reply hack/logcheck.conf:14]: @serathius : can you merge https://github.com/kubernetes/klog/pull/315?

Comment (serathius) [reply hack/logcheck.conf:14]: d

Comment (pohly) [reply hack/logcheck.conf]: Fixed and PR updated.

Comment (pohly) [reply hack/logcheck.conf]: /hold cancel

**Comment by pohly** [comment]
/retest

containerd job [should be fixed now](https://github.com/kubernetes/test-infra/pull/25742).

**Comment by pohly** [comment]
/hold

Let's merge https://github.com/kubernetes/kubernetes/pull/108902 first, then I'll rebase: the two PRs have a minor conflict in `hack/tools/go.mod` and the other PR is needed for this one here.

**Comment by dims** [comment]
> /hold
> 
> Let's merge #108902 first, then I'll rebase: the two PRs have a minor conflict in `hack/tools/go.mod` and the other PR is needed for this one here.

Sounds like a good plan!

**Comment by pohly** [comment]
/hold cancel

https://github.com/kubernetes/kubernetes/pull/108902 was merged and I rebased on top of it. Manually introducing a regression confirms that the desired check is active:

```console
$ git diff
diff --git a/pkg/scheduler/scheduler.go b/pkg/scheduler/scheduler.go
index 8dd20b8881c..01e68bb8c4f 100644
--- a/pkg/scheduler/scheduler.go
+++ b/pkg/scheduler/scheduler.go
@@ -1085,7 +1085,7 @@ func findNodesThatPassExtenders(extenders []framework.Extender, pod *v1.Pod, fea
                feasibleList, failedMap, failedAndUnresolvableMap, err := extender.Filter(pod, feasibleNodes)
                if err != nil {
                        if extender.IsIgnorable() {
-                               klog.InfoS("Skipping extender as it returned error and has ignorable flag set", "extender", extender, "err", err)
+                               klog.Info("Skipping extender as it returned error and has ignorable flag set", "extender", extender, "err", err)
                                continue
                        }
                        return nil, err
                      
$ hack/verify-golangci-lint.sh 
installing golangci-lint and logcheck plugin from hack/tools into /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin
running golangci-lint 
pkg/scheduler/scheduler.go:1088:5: unstructured logging function "Info" should not be used (logcheck)
				klog.Info("Skipping extender as it returned error and has ignorable flag set", "extender", extender, "err", err)
				^
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/api
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/client-go
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/code-generator
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/component-base
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/component-helpers
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/controller-manager
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/cri-api
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kubectl
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kubelet
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kube-proxy
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/metrics
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/mount-utils
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/pod-security-admission
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/sample-cli-plugin
running golangci-lint for /nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/sample-controller

Please review the above warnings. You can test via "./hack/verify-golangci-lint.sh"
If the above warnings do not make sense, you can exempt this warning with a comment
 (if your reviewer is okay with it).
In general please prefer to fix the error, we have already disabled specific lints
 that the project chooses to ignore.
See: https://golangci-lint.run/usage/false-positives/
```

**Comment by pohly** [comment]
/priority important-soon

Without this PR, log checking is disabled because of https://github.com/kubernetes/kubernetes/pull/108901

**Comment by dims** [comment]
/approve
/lgtm

/assign @liggitt 

(needs root OWNERS approval)

File: cmd/kube-scheduler/app/options/configfile.go (hunk 1 above)
Comment (liggitt) [reply cmd/kube-scheduler/app/options/configfile.go:96]: doesn't this escape the contents of the config file, making it ~unreadable?

File: hack/verify-golangci-lint.sh [hunk 5]
```diff
@@ -36,14 +36,25 @@ PATH="${GOBIN}:${PATH}"
 export GO111MODULE=on
 
 # Install golangci-lint
-echo 'installing golangci-lint '
+echo "installing golangci-lint and logcheck plugin from hack/tools into ${GOBIN}"
 pushd "${KUBE_ROOT}/hack/tools" >/dev/null
   go install github.com/golangci/golangci-lint/cmd/golangci-lint
+  go build -o "${GOBIN}/logcheck.so" -buildmode=plugin k8s.io/klog/hack/tools/logcheck/plugin
```
Comment (liggitt) [inline hack/verify-golangci-lint.sh:42]: I still don't think we should be consuming/compiling a hack tool from klog this way, but this PR is just relocating the existing use, so it's not making things *worse*

Comment (pohly) [reply hack/verify-golangci-lint.sh:42]: I'm fine with moving it to a separate repo. Tracked in https://github.com/kubernetes/klog/issues/312.

Comment (liggitt) [reply hack/verify-golangci-lint.sh:42]: agreed

**Comment by dims** [comment]
/retest

(not sure if it helps!)

**Comment by liggitt** [comment]
fwiw, the flaky unit test is getting skipped in https://github.com/kubernetes/kubernetes/pull/108981 until we resolve the issue

had one low priority comment about a change to the config logging escaping/garbling the config file content - https://github.com/kubernetes/kubernetes/pull/108159#discussion_r834292846 - won't block this PR on it, but I'm pretty sure that change makes that log line very unusable

File: cmd/kube-scheduler/app/options/configfile.go (hunk 1 above)
Comment (pohly) [reply cmd/kube-scheduler/app/options/configfile.go:96]: No, I added more readable formatting of multi-line strings in https://github.com/kubernetes/klog/pull/273

The commit message in this PR shows what the updated log output looks like in this case here: https://github.com/kubernetes/kubernetes/pull/108159/commits/0f4d0660a7674f816d4f60791b1cfe191fab7050

Comment (liggitt) [reply cmd/kube-scheduler/app/options/configfile.go:96]: ah, cool
