### PR TITLE
Fix a few places where source field is empty when creating events via events/v1

### LINKED ISSUE #92795: [Failing test] kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)
**Which jobs are failing**:
kubeadm-kinder-master (ci-kubernetes-e2e-kubeadm-kinder-master)

**Which test(s) are failing**:
`[sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running [Conformance]`

**Since when has it been failing**:
`07-03 07:04 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-master

**Reason for failure**:
```
 Jul  4 12:37:29.246: FAIL: Unexpected error:
    <*errors.errorString | 0xc0002ec210>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
Full Stack Trace
k8s.io/kubernetes/test/e2e/node.glob..func3.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/node/events.go:97 +0xa07
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000e3dc20)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x337
k8s.io/kubernetes/test/e2e.TestE2E(0xc000e3dc20)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:145 +0x2b
testing.tRunner(0xc000e3dc20, 0x4cb0590)
	/usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x357 

```

**Anything else we need to know**:
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.19
/sig testing

### LINKED ISSUE #92870: Add AddFieldLabelConversionsForEvent for new events/{v1beta1, v1} conversions
**What happened**:

We're missing for events/v1 and events/v1beta1.

**What you expected to happen**:

We should add a similar function as introduced in core/v1: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/conversion.go#L449

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### LINKED ISSUE #92882: EventAggregatorByReasonFunc doesn't consider reportingController, only source
**What happened**:

Events reported with an empty source.component/source.host and with distinct reportingController/reportingInstance values are considered identical by EventAggregatorByReasonFunc

events.k8s.io/v1 events will not set source fields.

/assign @wojtek-t

### PR DESCRIPTION
**Pull request by chelseychen**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

New events API conversion is missing AddFieldLabelConversionsForEvent (#92870). Also it lacks conversion between `Source.Component` and `ReportingController` fields.

Since `DeprecatedSource` field assignment was removed in #92662, which means `Source` field becomes empty when converting to internal, which would cause e2e tests fail when listing events with `source` fieldSelector.

So `source` fieldSelector should be set with `reportingController` when `source` is empty.

This PR also resolves the aggregation issue in `EventAggregatorMessageFunc` (#92882).

**Which issue(s) this PR fixes**:

Fixes #92870 
Fixes #92882 
Fixes #92795 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: <https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/383-new-event-api-ga-graduation>
```

### CODE REVIEW

File: pkg/registry/events/event/strategy.go [hunk 1]
```diff
@@ -85,8 +85,21 @@ func (eventStrategy) AllowUnconditionalUpdate() bool {
...
+	specificFieldsSet := fields.Set{
+		"involvedObject.kind":            event.InvolvedObject.Kind,
+		"involvedObject.namespace":       event.InvolvedObject.Namespace,
+		"involvedObject.name":            event.InvolvedObject.Name,
+		"involvedObject.uid":             string(event.InvolvedObject.UID),
+		"involvedObject.apiVersion":      event.InvolvedObject.APIVersion,
+		"involvedObject.resourceVersion": event.InvolvedObject.ResourceVersion,
+		"involvedObject.fieldPath":       event.InvolvedObject.FieldPath,
+		"reason":                         event.Reason,
+		"source":                         event.ReportingController,
```
Comment (liggitt) [inline pkg/registry/events/event/strategy.go:99]: this should use events/{v1beta1,v1} field names:

* instead of `involvedObject`, use `regarding`
* instead of `source`, use `reportingController`

File: pkg/registry/core/event/strategy.go [hunk 2]
```diff
@@ -113,7 +113,7 @@ func ToSelectableFields(event *api.Event) fields.Set {
 		"involvedObject.resourceVersion": event.InvolvedObject.ResourceVersion,
 		"involvedObject.fieldPath":       event.InvolvedObject.FieldPath,
 		"reason":                         event.Reason,
-		"source":                         event.Source.Component,
+		"source":                         event.ReportingController,
```
Comment (liggitt) [inline pkg/registry/core/event/strategy.go:116]: don't change the core/v1 selectable fields

File: pkg/apis/events/v1/conversion.go [hunk 3]
```diff
@@ -54,5 +63,34 @@ func Convert_core_Event_To_v1_Event(in *k8s_api.Event, out *v1.Event, s conversi
...
+	// clear DeprecatedSource fields if they match the ReportingController field
+	if out.DeprecatedSource.Component == out.ReportingController {
+		out.DeprecatedSource.Component = ""
+	}
+
 	return nil
 }
+
+func AddFieldLabelConversionsForEvent(scheme *runtime.Scheme) error {
+	return scheme.AddFieldLabelConversionFunc(SchemeGroupVersion.WithKind("Event"),
```
Comment (liggitt) [inline pkg/apis/events/v1/conversion.go:76]: this is responsible for matching field selector keys in the events/v1 API to fieldset keys set by `event/strategy.go#SelectableFields`... use `regarding` instead of `involvedObject`, and `reportingController` instead of `source`

File: pkg/apis/events/v1beta1/conversion.go [hunk 4]
```diff
@@ -54,5 +63,34 @@ func Convert_core_Event_To_v1beta1_Event(in *k8s_api.Event, out *v1beta1.Event,
...
+				"involvedObject.uid",
+				"involvedObject.apiVersion",
+				"involvedObject.resourceVersion",
+				"involvedObject.fieldPath",
+				"reason",
+				"source",
+				"type",
+				"metadata.namespace",
+				"metadata.name":
+				return label, value, nil
```
Comment (liggitt) [inline pkg/apis/events/v1beta1/conversion.go:91]: this is responsible for matching field selector keys in the events/v1beta1 API to fieldset keys set by `event/strategy.go#SelectableFields`... use `regarding` instead of `involvedObject`, and `reportingController` instead of `source`

File: pkg/registry/core/event/strategy.go (hunk 2 above)
Comment (chelseychen) [reply pkg/registry/core/event/strategy.go]: Done.

**Comment by liggitt** [comment]
updating the events e2e test to exercise this conversion and field selection might be good:

```diff
diff --git a/test/e2e/instrumentation/events.go b/test/e2e/instrumentation/events.go
index 34d8769be52..4f3ef9ed0a8 100644
--- a/test/e2e/instrumentation/events.go
+++ b/test/e2e/instrumentation/events.go
@@ -22,11 +22,12 @@ import (
        "fmt"
        "time"
 
-       "k8s.io/api/core/v1"
+       v1 "k8s.io/api/core/v1"
        eventsv1 "k8s.io/api/events/v1"
        apiequality "k8s.io/apimachinery/pkg/api/equality"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/util/diff"
+       corev1 "k8s.io/client-go/kubernetes/typed/core/v1"
        typedeventsv1 "k8s.io/client-go/kubernetes/typed/events/v1"
        "k8s.io/kubernetes/test/e2e/framework"
        "k8s.io/kubernetes/test/e2e/instrumentation/common"
@@ -73,10 +74,12 @@ func eventExistsInList(client typedeventsv1.EventInterface, namespace, name stri
 
 var _ = common.SIGDescribe("Events API", func() {
        f := framework.NewDefaultFramework("events")
+       var coreClient corev1.EventInterface
        var client typedeventsv1.EventInterface
        var clientAllNamespaces typedeventsv1.EventInterface
 
        ginkgo.BeforeEach(func() {
+               coreClient = f.ClientSet.CoreV1().Events(f.Namespace.Name)
                client = f.ClientSet.EventsV1().Events(f.Namespace.Name)
                clientAllNamespaces = f.ClientSet.EventsV1().Events(metav1.NamespaceAll)
        })
@@ -103,6 +106,20 @@ var _ = common.SIGDescribe("Events API", func() {
                foundCreatedEvent = eventExistsInList(client, f.Namespace.Name, eventName)
                framework.ExpectEqual(foundCreatedEvent, true, "failed to find test event in list with namespace scope")
 
+               // test field selection filtering on reportingController
+               filteredEventsV1List, err := client.List(context.TODO(), metav1.ListOptions{FieldSelector: "reportingController=test-controller"})
+               framework.ExpectNoError(err, "failed to get filtered list")
+               if len(filteredEventsV1List.Items) != 1 || filteredEventsV1List.Items[0].Name != eventName {
+                       framework.Failf("expected single event, got %#v", filteredEventsV1List.Items)
+               }
+
+               // test field selection filtering on source
+               filteredCoreV1List, err := coreClient.List(context.TODO(), metav1.ListOptions{FieldSelector: "source=test-controller"})
+               framework.ExpectNoError(err, "failed to get filtered list")
+               if len(filteredCoreV1List.Items) != 1 || filteredCoreV1List.Items[0].Name != eventName {
+                       framework.Failf("expected single event, got %#v", filteredCoreV1List.Items)
+               }
+
                ginkgo.By("getting the test event")
                testEvent, err := client.Get(context.TODO(), eventName, metav1.GetOptions{})
                framework.ExpectNoError(err, "failed to get test event")
```

File: pkg/apis/events/v1/conversion.go [hunk 5]
```diff
@@ -37,6 +40,12 @@ func Convert_v1_Event_To_core_Event(in *v1.Event, out *k8s_api.Event, s conversi
 	out.FirstTimestamp = in.DeprecatedFirstTimestamp
 	out.LastTimestamp = in.DeprecatedLastTimestamp
 	out.Count = in.DeprecatedCount
+
+	// translate reportingController to out.Source.Component field if it is empty
+	if len(out.Source.Component) == 0 {
+		out.Source.Component = out.ReportingController
+	}
```
Comment (liggitt) [inline pkg/apis/events/v1/conversion.go:47]: ugh, this is going to make validation (which runs on internal events) fail here:

https://github.com/kubernetes/kubernetes/blob/5afc42de9501ac7b06bbb349e03a666efd5e3bd7/pkg/apis/core/validation/events.go#L68-L70

Comment (chelseychen) [reply pkg/apis/events/v1/conversion.go]: As we discussed offline, we would revert this conversion

File: pkg/printers/internalversion/printers.go [hunk 6]
```diff
@@ -2181,8 +2181,12 @@ func layoutContainerCells(containers []api.Container) (names string, images stri
 	return namesBuffer.String(), imagesBuffer.String()
 }
 
-// formatEventSource formats EventSource as a comma separated string excluding Host when empty
-func formatEventSource(es api.EventSource) string {
+// formatEventSource formats EventSource as a comma separated string excluding Host when empty,
+// or returns reportingController when EventSource is empty
+func formatEventSource(es api.EventSource, reportingController string) string {
```
Comment (liggitt) [inline pkg/printers/internalversion/printers.go:2186]: IIUC, source.{component,host} is deprecated in favor of reportingController/reportingInstance

so I think this should look more like:

```go
func formatEventSource(es api.EventSource, reportingController, reportingInstance string) string {
  return formatEventSourceComponentInstance(
    firstNonEmpty(es.Component, reportingController),
    firstNonEmpty(es.Host, reportingInstance),
  )
}

func firstNonEmpty(ss ...string) string {
  for _, s := range ss {
    if len(s) > 0 {
      return s
    }
  }
  return ""
}

func formatEventSourceComponentInstance(component, instance string) string {
  if len(instance) == 0 {
    return component
  }
  return component + ", " + instance
}
```

Comment (chelseychen) [reply pkg/printers/internalversion/printers.go]: Make sense. Done.

**Comment by liggitt** [comment]
/hold

looks like a compile issue needs fixing

File: pkg/apis/events/v1/register.go [hunk 7]
```diff
@@ -41,5 +41,5 @@ func init() {
 	// We only register manually written functions here. The registration of the
 	// generated functions takes place in the generated files. The separation
 	// makes the code compile even when the generated files are missing.
-	localSchemeBuilder.Register(RegisterDefaults)
```
Comment (liggitt) [inline pkg/apis/events/v1/register.go:44]: should this have removed RegisterDefaults?

File: pkg/apis/events/v1beta1/register.go [hunk 8]
```diff
@@ -41,5 +41,5 @@ func init() {
 	// We only register manually written functions here. The registration of the
 	// generated functions takes place in the generated files. The separation
 	// makes the code compile even when the generated files are missing.
-	localSchemeBuilder.Register(RegisterDefaults)
```
Comment (liggitt) [inline pkg/apis/events/v1beta1/register.go:44]: should this have removed RegisterDefaults?

Comment (chelseychen) [reply pkg/apis/events/v1beta1/register.go:44]: Didn't know Default shouldn't be removed. I've added it back. Not sure if e2e test failure is related to this..

**Comment by chelseychen** [comment]
@liggitt Looks like the e2e test failed for the case when listing events with field selection filtering on reportingController. The error message said `expected single event, got []v1.Event(nil)`. I dug into codes but couldn't figure out why it couldn't fetch the event with `"reportingController=test-controller"`. I did register the field selector and define SelectableFields for events/v1 correctly as well. Could you please TAL? Did I miss something?

**Comment by liggitt** [comment]
It looks like the events REST storage initialization is using the core events registry, which uses the core events strategy. The events strategy (at `pkg/registry/events/event/strategy.go`) is unreferenced and unused.

I was able to get the `regarding...` and `reportingController` field selectors to work by doing the following:
1. removing `pkg/registry/events/event/...`
2. add `reportingController` to the field set generated by `pkg/registry/core/event/strategy.go#ToSelectableFields`
3. adjust the `AddFieldLabelConversionsForEvent` in `pkg/apis/events/{v1,v1beta1}/conversion.go` to map from events.k8s.io field names to the fieldset names constructed in `pkg/registry/core/event/strategy.go#ToSelectableFields`:

```go

func AddFieldLabelConversionsForEvent(scheme *runtime.Scheme) error {
	mapping := map[string]string{
		"reason":                    "reason",
		"regarding.kind":            "involvedObject.kind",
		"regarding.namespace":       "involvedObject.namespace",
		"regarding.name":            "involvedObject.name",
		"regarding.uid":             "involvedObject.uid",
		"regarding.apiVersion":      "involvedObject.apiVersion",
		"regarding.resourceVersion": "involvedObject.resourceVersion",
		"regarding.fieldPath":       "involvedObject.fieldPath",
		"reportingController":       "reportingController",
		"type":                      "type",
		"metadata.namespace":        "metadata.namespace",
		"metadata.name":             "metadata.name",
	}
	return scheme.AddFieldLabelConversionFunc(SchemeGroupVersion.WithKind("Event"),
		func(label, value string) (string, string, error) {
			mappedLabel, ok := mapping[label]
			if !ok {
				return "", "", fmt.Errorf("field label not supported: %s", label)
			}
			return mappedLabel, value, nil
		})
}
```

**Comment by chelseychen** [comment]
Thank you so much for the help! I've updated the codes and hopefully the tests can pass this time..

> It looks like the events REST storage initialization is using the core events registry, which uses the core events strategy. The events strategy (at `pkg/registry/events/event/strategy.go`) is unreferenced and unused.

BTW, I'm curious about how you found out this - did you have a way to test it or just some sort of guess?

**Comment by liggitt** [comment]
one last thing... it looks like the `reportingController` field was added to core/v1 as well, but with a different field name of `reportingComponent`... looks like we'll need to do the following:

```diff
diff --git a/pkg/apis/core/v1/conversion.go b/pkg/apis/core/v1/conversion.go
index a6ba99cc895..974a0a62ee4 100644
--- a/pkg/apis/core/v1/conversion.go
+++ b/pkg/apis/core/v1/conversion.go
@@ -434,6 +434,7 @@ func AddFieldLabelConversionsForEvent(scheme *runtime.Scheme) error {
 				"involvedObject.apiVersion",
 				"involvedObject.resourceVersion",
 				"involvedObject.fieldPath",
+				"reportingComponent",
 				"reason",
 				"source",
 				"type",
diff --git a/pkg/apis/events/v1/conversion.go b/pkg/apis/events/v1/conversion.go
index c3c5b1ab251..a45baf2f61f 100644
--- a/pkg/apis/events/v1/conversion.go
+++ b/pkg/apis/events/v1/conversion.go
@@ -63,14 +63,14 @@ func Convert_core_Event_To_v1_Event(in *k8s_api.Event, out *v1.Event, s conversi
 func AddFieldLabelConversionsForEvent(scheme *runtime.Scheme) error {
 	mapping := map[string]string{
 		"reason":                    "reason",
-		"regarding.kind":            "involvedObject.kind",
-		"regarding.namespace":       "involvedObject.namespace",
-		"regarding.name":            "involvedObject.name",
-		"regarding.uid":             "involvedObject.uid",
-		"regarding.apiVersion":      "involvedObject.apiVersion",
-		"regarding.resourceVersion": "involvedObject.resourceVersion",
-		"regarding.fieldPath":       "involvedObject.fieldPath",
-		"reportingController":       "reportingController",
+		"regarding.kind":            "involvedObject.kind",            // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.namespace":       "involvedObject.namespace",       // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.name":            "involvedObject.name",            // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.uid":             "involvedObject.uid",             // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.apiVersion":      "involvedObject.apiVersion",      // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.resourceVersion": "involvedObject.resourceVersion", // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.fieldPath":       "involvedObject.fieldPath",       // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"reportingController":       "reportingComponent",             // map events.k8s.io field to fieldset returned by ToSelectableFields
 		"type":                      "type",
 		"metadata.namespace":        "metadata.namespace",
 		"metadata.name":             "metadata.name",
diff --git a/pkg/apis/events/v1beta1/conversion.go b/pkg/apis/events/v1beta1/conversion.go
index 449739e7012..8c28cd7e581 100644
--- a/pkg/apis/events/v1beta1/conversion.go
+++ b/pkg/apis/events/v1beta1/conversion.go
@@ -63,14 +63,14 @@ func Convert_core_Event_To_v1beta1_Event(in *k8s_api.Event, out *v1beta1.Event,
 func AddFieldLabelConversionsForEvent(scheme *runtime.Scheme) error {
 	mapping := map[string]string{
 		"reason":                    "reason",
-		"regarding.kind":            "involvedObject.kind",
-		"regarding.namespace":       "involvedObject.namespace",
-		"regarding.name":            "involvedObject.name",
-		"regarding.uid":             "involvedObject.uid",
-		"regarding.apiVersion":      "involvedObject.apiVersion",
-		"regarding.resourceVersion": "involvedObject.resourceVersion",
-		"regarding.fieldPath":       "involvedObject.fieldPath",
-		"reportingController":       "reportingController",
+		"regarding.kind":            "involvedObject.kind",            // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.namespace":       "involvedObject.namespace",       // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.name":            "involvedObject.name",            // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.uid":             "involvedObject.uid",             // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.apiVersion":      "involvedObject.apiVersion",      // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.resourceVersion": "involvedObject.resourceVersion", // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"regarding.fieldPath":       "involvedObject.fieldPath",       // map events.k8s.io field to fieldset returned by ToSelectableFields
+		"reportingController":       "reportingComponent",             // map events.k8s.io field to fieldset returned by ToSelectableFields
 		"type":                      "type",
 		"metadata.namespace":        "metadata.namespace",
 		"metadata.name":             "metadata.name",
diff --git a/pkg/registry/core/event/strategy.go b/pkg/registry/core/event/strategy.go
index dcfe74008a3..bc57da36809 100644
--- a/pkg/registry/core/event/strategy.go
+++ b/pkg/registry/core/event/strategy.go
@@ -117,7 +117,7 @@ func ToSelectableFields(event *api.Event) fields.Set {
 		"involvedObject.resourceVersion": event.InvolvedObject.ResourceVersion,
 		"involvedObject.fieldPath":       event.InvolvedObject.FieldPath,
 		"reason":                         event.Reason,
-		"reportingController":            event.ReportingController,
+		"reportingComponent":             event.ReportingController, // use the core/v1 field name
 		"source":                         source,
 		"type":                           event.Type,
 	}
diff --git a/pkg/registry/core/event/strategy_test.go b/pkg/registry/core/event/strategy_test.go
index f7f538fdc95..1f7010e0dc4 100644
--- a/pkg/registry/core/event/strategy_test.go
+++ b/pkg/registry/core/event/strategy_test.go
@@ -61,7 +61,7 @@ func TestGetAttrs(t *testing.T) {
 		"involvedObject.resourceVersion": "0",
 		"involvedObject.fieldPath":       "",
 		"reason":                         "ForTesting",
-		"reportingController":            "",
+		"reportingComponent":             "",
 		"source":                         "test",
 		"type":                           api.EventTypeNormal,
 	}
@@ -99,7 +99,7 @@ func TestGetAttrs(t *testing.T) {
 		"involvedObject.resourceVersion": "0",
 		"involvedObject.fieldPath":       "",
 		"reason":                         "ForTesting",
-		"reportingController":            "test",
+		"reportingComponent":             "test",
 		"source":                         "test",
 		"type":                           api.EventTypeNormal,
 	}
```

**Comment by liggitt** [comment]
> BTW, I'm curious about how you found out this - did you have a way to test it or just some sort of guess?

I was trying to make sure that field set method was being used, and realized there were no imports of that package anywhere

**Comment by chelseychen** [comment]
@liggitt 
I added `reportingController` to `core/event/strategy.go#ToSelectableFields`, and I have to add it to `pkg/apis/core/v1/conversion.go#AddFieldLabelConversionsForEvent` as well in order to pass `TestSelectableFieldLabelConversions` test under strategy_test.go since that test is testing against `core/v1` field label conversion. I know it's a bit weird to add `reportingController` to core/v1 as it's not a field for that, but I guess it's better than removing `TestSelectableFieldLabelConversions` test, right? Or maybe there's other better solutions? What do you think?

**Comment by chelseychen** [comment]
Thanks Jordan!

**Comment by chelseychen** [comment]
@liggitt
This PR is still pending the tests, which would block the merge. The code freeze cut is today, I wonder if this would be affected?

**Comment by liggitt** [comment]
It has lgtm+approval and is in the milestone, which meets the requirements for freeze.

**Comment by chelseychen** [comment]
Got it, thanks for confirming!
