### PR TITLE
memory manager: handling init containers

### LINKED ISSUE #100838: Memory manager should re-use memory allocated for init containers
#### What happened:

Start the pod with init containers will consume appContainersMemory + initContainersMemory.
You can see it explicitly under the memory manager state file(`/var/lib/kubelet/memory_manager_state`)

#### What you expected to happen:

The Memory manager should re-use the memory allocated for the init containers.

#### How to reproduce it (as minimally and precisely as possible):

- enable Memory Manager feature gate and set Memory manager policy to static
- configured --reserved-memory flag to reflect 
- start the pod with init containers
- check the memory manager state file via (`cat /var/lib/kubelet/memory_manager_state`)

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The memory manager will re-use the memory allocated for init containers that should increase the density of containers.

The idea that during the allocation phase we will:

- during the allocation we will take into account the init containers reusable memory, which means that we will re-use the memory and update container memory blocks accordingly. For example for the pod with two init containers that requested: 1Gi and 2Gi, and app container that requested 4Gi, we can re-use 2Gi of memory.
- remove init containers from the state file once the app container started, it will release the memory allocated for the init container and can intense the density of containers on the NUMA node in cases when the memory allocated for init containers is bigger than the memory allocated for app containers.

TODO:
- [x] implementation
- [x] unittests

#### Which issue(s) this PR fixes:

Fixes #100838

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Will provide e2e tests under the separate PR.

**Comment by cynepco3hahue** [comment]
@klueska Can you please review?

**Comment by klueska** [comment]
I haven't started looking through the code yet (will do that later today).
Quick question though, which is unclear from the description....

Is memory reused across init containers? Meaning, if init container 1 asks for 2Gi and init container 2 also asks for 2Gi, will the same memory region be used? In theory it should, otherwise you (unnecessarily) run the risk of running out of memory if the sum across all init containers is more than what's available on the system. Since init containers run serially though, it should be reclaimable.

**Comment by cynepco3hahue** [comment]
> I haven't started looking through the code yet (will do that later today).
> Quick question though, which is unclear from the description....
> 
> Is memory reused across init containers? Meaning, if init container 1 asks for 2Gi and init container 2 also asks for 2Gi, will the same memory region be used? In theory it should, otherwise you (unnecessarily) run the risk of running out of memory if the sum across all init containers is more than what's available on the system. Since init containers run serially though, it should be reclaimable.

It will re-use the same memory region(the same NUMA node), but it true only for cases when `initContainer2Memory <= initContainer2Memory`.

File: pkg/kubelet/cm/memorymanager/memory_manager.go [hunk 1]
```diff
@@ -182,6 +182,14 @@ func (m *manager) AddContainer(pod *v1.Pod, container *v1.Container, containerID
...
 
 	m.containerMap.Add(string(pod.UID), container.Name, containerID)
+
+	if isInitContainer(pod, container) {
+		return
+	}
+
+	// if the app container started and pod has init containers we should remove it
+	// to release memory requested by init containers
+	m.removeInitContainers(pod)
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/memory_manager.go:192]: Why does this need to be special cased for `app` containers. I would expect an init container to also want to remove the memory of previous init containers in the sequence before having memory allocated to it.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 2]
```diff
@@ -767,3 +837,120 @@ func findBestHint(hints []topologymanager.TopologyHint) *topologymanager.Topolog
...
+						requestedSize -= containerBlock.Size
+						containerBlocks[j].Size = 0
+					}
+				}
+			}
+		}
+	}
+}
+
+func isNUMAAffinitiesEqual(numaAffinity1, numaAffinity2 []int) bool {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:931]: When / why are this affinities converted from a `bitmask.BitMask` type to an `[]int`? I ask because if they were still their original `bitmask` type, then you could just use `IsEqual()`:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/topologymanager/bitmask/bitmask.go#L135

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 3]
```diff
@@ -45,6 +46,10 @@ type staticPolicy struct {
 	systemReserved systemReservedMemory
 	// topology manager reference to get container Topology affinity
 	affinity topologymanager.Store
+	// reusableState contains the state before applying init containers allocations
+	reusableState map[string]state.NUMANodeMap
+	// initContainersReusableMemory contains the memory allocated for init containers that can be reused
+	initContainersReusableMemory reusableMemory
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:52]: Maybe it's just the naming, but I'm confused as to the purpose of `reusableState`. Can you elaborate on what it is and why it's necessary in addition to `initContainersReusableMemory`?

Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:52]: **reusableState**
Because init containers start once the previous init containers finished to run and the same true for the first app container I find it much easier to save the state during the first pod container allocation under `reusableState` and pass this state to GetTopologyHints, so Allocation for init containers will not affect hints calculation for others init containers and the first app container under the same pod, than updating the `calculateHints` method to be aware of re-usable memory.

**initContainersReusableMemory**
I still need to track the init containers re-usable memory because, in the end, I will need to reflect correctly this amount of allocated memory under the state file.

Please give me know if you need more information.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 1 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/memory_manager.go]: The allocation for init containers and the first app will always use a saved state that will not include init container allocations. Also, be aware that `AddContainer` will run after all pod containers allocations, so it can not affect in any way pod containers allocations.
But anyway it can be a good thing to remove init containers allocations from the state file quicker because it will release memory for other containers.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 2 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:952]: Maybe keep this function, but implement the body of it as a conversion to `bitmask` and a call to `isEqual()`.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:952]: makes sense, will do it

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 4]
```diff
@@ -146,41 +162,88 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
+		// the node does not have enough memory, use the node remaining memory and move to the next node
+		requestedSize -= nodeResourceMemoryState.Free
+		nodeResourceMemoryState.Reserved += nodeResourceMemoryState.Free
+		nodeResourceMemoryState.Free = 0
 	}
+}
 
-	s.SetMachineState(machineState)
-	s.SetMemoryBlocks(string(pod.UID), container.Name, containerBlocks)
+func (p *staticPolicy) getPodReusableMemory(pod *v1.Pod, numaAffinity []int, resourceName v1.ResourceName) uint64 {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:224]: This function makes alot of sense.  It walks through all blocks in all `init` containers from `p.initContainersReusableMemory[string(pod.UID)]` and if those blocks match the current resource type, it returns the amount of memory that can be reused from those blocks.

I assume an update to `p.initContainersReusableMemory[string(pod.UID)][containerName]` is made in a call just after this to account for the memory being pulled from it? Does it make sense to just do it inline or are there conditions where we would make this call to see how much we can reuse, but then failout before actually allocating it?

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 5]
```diff
@@ -788,3 +857,120 @@ func (p *staticPolicy) GetAllocatableMemory(s state.State) []state.Block {
 	}
 	return allocatableMemory
 }
+
+func (p *staticPolicy) updateStateToReuse(s state.State, pod *v1.Pod, container *v1.Container, memoryBlocks []state.Block) {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:862]: If I understand things correctly, this function is actually doing 2 things.
1. If the current container is an `init` container, assume the "original" state file (i.e. before any memory allocations have been made).
2. If it is an app container, update `reusableState` to reflect the new memory blocks allocated to it.

I guess the assumption here is that we are only maintaining this "temporary" state file so that init containers can pretend that no memory has been allocated to any other containers since they always run 1-by-1 to completion (so have all memory available to them when they are about to run). Once we start considering `app` containers, we have to track it differently because the memory they get allocated cannot be reused.

Once we are working with `app` containers, is there any point in time that `reusableState` != `machineState`? It feels as if things are being overcomplicated here to track this state, if it's really just about making sure that `init` containers see the original memory state. Maybe there's something better we can do to make it clearer.

**Review by klueska — COMMENTED** [review]
Still not quite done with the full review, but making more progress on it. Left some comments for now.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 6]
```diff
@@ -788,3 +857,120 @@ func (p *staticPolicy) GetAllocatableMemory(s state.State) []state.Block {
...
+	}
+
+	// Otherwise it is an app container.
+	// Update the re-usable machine state
+	for _, memoryBlock := range memoryBlocks {
+		p.updateMachineState(p.reusableState[podUID], memoryBlock.NUMAAffinity, memoryBlock.Type, memoryBlock.Size)
+	}
+}
+
+func (p *staticPolicy) updateInitContainersReusableMemory(pod *v1.Pod, container *v1.Container, memoryBlocks []state.Block) {
```
[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:891]: yes exactly!

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 4 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:224]: The logic is:
- Hints generated when the re-usable memory taken into the account 
- Container blocks generated when the re-usable memory taken into the account
- The re-usable memory updated with generated container blocks

Because we call `GetTopologyHints` and `Allocate` sequentially for each container our calculations aligned and we have synced values between getting and updating the re-usable memory.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:224]: > Does it make sense to just do it inline or are there conditions where we would make this call to see how much we can reuse, but then failout before actually allocating it?

Can you please clarify this sentence?

**Comment by cynepco3hahue** [comment]
/test pull-kubernetes-node-kubelet-serial-memory-manager
--


<br class="Apple-interchange-newline">

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 4 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:212]: I'm asking if it makes sense to just do the logic for part (2) of https://github.com/kubernetes/kubernetes/pull/99640/files#r659842084 inline in this function.

That way we both calculate how much memory to reuse as well as subtract it out from the proper `init` container's memory blocks all at the same time.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: I'm wondering if there is a better way to abstract this. Although I get what it's doing, it's not intuitive that these two things should happen together, nor is it obvious from the name of the function that this is what is going on.

As mentioned in another comment. I wonder if part (2) of this can be folded into `getPodReusableMemory()` and then this function just renamed / reduced to:
```
func (p *staticPolicy) addInitContainersReusableMemory(pod *v1.Pod, container *v1.Container, memoryBlocks []state.Block) {

	podUID := string(pod.UID)

	if isInitContainer(pod, container) {
		if _, ok := p.initContainersReusableMemory[podUID]; !ok {
			p.initContainersReusableMemory[podUID] = []map[string][]state.Block{}
		}

		p.initContainersReusableMemory[podUID] = append(p.initContainersReusableMemory[podUID], map[string][]state.Block{
			container.Name: memoryBlocks,
		})
	}
}
```

File: pkg/kubelet/cm/memorymanager/memory_manager.go [hunk 7]
```diff
@@ -308,22 +307,25 @@ func (m *manager) removeStaleState() {
...
-	err := m.policy.RemoveContainer(m.state, podUID, containerName)
-	if err == nil {
-		m.containerMap.RemoveByContainerRef(podUID, containerName)
+func (m *manager) removeInitContainers(pod *v1.Pod, container *v1.Container) {
+	for _, initContainer := range pod.Spec.InitContainers {
+		if initContainer.Name == container.Name {
+			break
+		}
+
+		m.policyRemoveContainerByRef(string(pod.UID), initContainer.Name)
```
[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:322]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 4 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:212]: The problem that we calling `getPodReusableMemory` also from the `GetTopologyHints`, and it should not update the re-usable memory because it can create some inconsistency if it will be some error between the call to `GetTopologyHints` and `Allocate`. I will try to see if it possible to move some common code into a separate method.

Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:212]: I can move
```
if resourceName != containerBlock.Type {
                                        continue
                                }

                                if containerBlock.Size == 0 {
                                        continue
                                }

                                if !isNUMAAffinitiesEqual(numaAffinity, containerBlock.NUMAAffinity) {
                                        continue
                                }
```
to the separate method, but IMHO it not a big improvement

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: see my comment above, we can not join fetch and update under the same method because it called from two different methods `GetTopologyHints`(should not update anything) and `Allocate`
btw CPU manager has similar method https://github.com/kubernetes/kubernetes/blob/756203fda0f22a093b4f71022e2aa6d12743e840/pkg/kubelet/cm/cpumanager/policy_static.go#L194 just calculation is much simpler :(

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 4 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:212]: Let me take another pass tomorrow before changing anything then.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: Hey. Looking again at `updateInitContainersReusableMemory()`. Sorry, still trying to wrap my head around why it needs to do anything different than what the CPUManager’s updateCPUsToReuse() does (except for with memory instead of CPUs).

In the CPUManager’s implementation, we:
1. Track the total reusable CPUs at the pod level (not per container)
2. Unconditionally union any CPUs allocated to init containers into the reusable set
3. Unconditionally subtract out and CPUs allocated to app containers

In the memory manager, you track the reusable memory blocks allocated to each init container separately, which I think unnecessarily complicates the logic (and has likely been the source of alot of my confusion). Is there any reason you can’t follow some similar logic for memory that tracks "total" reusable memory instead of per init container? That would turn the `updateInitContainersReusableMemory()` function into something like:
```
func (p *staticPolicy) updateInitContainersReusableMemory(pod *v1.Pod, container *v1.Container, memoryBlocks []state.Block) {
	// If pod entries to p.initContainersReusableMemory other than the current pod exist, delete them.
	for podUID := range p.initContainersReusableMemory {
		if podUID != string(pod.UID) {
			delete(p.initContainersReusableMemory, podUID)
		}
	}
	// If no memory blocks map exists in initContainersReusableMemory by this pod yet, create one.
	if _, ok := p.initContainersReusableMemory[string(pod.UID)]; !ok {
		p.initContainersReusableMemory[string(pod.UID)] = []map[string][]state.Block{}
	}
	// Check if the container is an init container.
	// If so, "merge" it with the set of memory blocks already passed in by other init containers
	// i.e. keep the larger of the two allocations for each matching block
	if isInitContainer(pod, container) {
		// Walk through `memoryBlocks` and `p.initContainersReusableMemory[string(pod.UID)]`
		// If the blocks match by type and NUMA affinity
		//     If memoryBlocks.size > initContainersReusableMemory[string(pod.UID)].size
		//         initContainersReusableMemory[string(pod.UID)].size = memoryBlocks.size
	}
	// Otherwise it is an app container.
	// Remove memory from the matching blocks of reusable memory for any new allocations.
		// Walk through `memoryBlocks` and `p.initContainersReusableMemory[string(pod.UID)]`
		// If the blocks match by type and NUMA affinity
		//     if memoryBlocks.size >= p.initContainersReusableMemory[string(pod.UID)].size {
		//         p.initContainersReusableMemory[string(pod.UID)].size = 0
		//     } else {
		//         p.initContainersReusableMemory[string(pod.UID)].size -= memoryBlocks.size
		//     }
}
```
To me this feels much more intuitive as we keep a running tally of how much memory is being consumed for each matching block type, rather than trying to (artifically) consolidate things across the init containers they were originally allocated to.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 4 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:212]: Yes. After reviewing the `CPUManager` code for this, I remember/understand why this separation is necessary.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: To reuse the logic of detecting matching blocks you could write a helper like:
```
func walkMatchingMemoryBlocks(m1, m2 map[string][]state.Block, f func(b1, b2 state.Block)) {
	for _, b1s := range m1 {
		for b2s:= range m2 {
			for i, b1 := range b1s {
				for j, b2 := range b2s {
					if b1.Type != b2.Type {
						continue
					}
					if !isNUMAAffinitiesEqual(b1.NUMAAffinity, b2.NUMAAffinity) {
						continue
					}
					f(b1s[i], b2s[j])
				}
			}
		}
	}
}
```
And then use it in the logic in the previous comment as:
```
walkMatchingMemoryBlocks(memoryBlocks, initContainersReusableMemory[string(pod.UID)], func(b1, b2 state.Block)) {
	...
})
```

[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: But under your implementation, you do not really know from which NUMA how many memory you can reuse. Because in general when we are talking about the container scope each init container can start on the different NUMA node(depends on the memory fragmentation). Also take into account that you have different memory types(memory, hugepages-2Mi, hugepages-1Gi).
IIRC under the CPU manager, the hint calculation will reject any hints that do not re-use the memory so you will end with the admission error - https://github.com/kubernetes/kubernetes/issues/94220.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 8]
```diff
@@ -146,53 +152,101 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
 	if blocks == nil {
-		return nil
+		return
 	}
 
+	klog.InfoS("RemoveContainer", "podUID", podUID, "containerName", containerName)
 	s.Delete(podUID, containerName)
 
+	// delete pod re-usable memory
+	delete(p.initContainersReusableMemory, podUID)
```
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:248]: Hmm. I guess it will work solely because `initContainersReusableMemory ` is only used during allocation, and *all* allocations happen before `AddContainer` (or subsequently RemoveContainer`) are called. It still feels unintuitive though (especially since it will only do anything when it is called on the first cpntainer, and then be a no-op for all other containers).

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: > you do not really know from which NUMA how many memory you can reuse. Because in general when we are talking about the container scope each init container can start on the different NUMA node(depends on the memory fragmentation).

That should not be a concern of this function -- the memory has already been allocated to the container before this function is ever called (i.e. by `getPodReusableMemory()`) -- this function just cleans up the state in `initContainersReusableMemory` to the set of reusable memory from any new allocations that have just been made.

> Also take into account that you have different memory types(memory, hugepages-2Mi, hugepages-1Gi).

As written, this should account for that. That is what is meant by the comment about:
```
If the blocks match by type and NUMA affinity
...
```

[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: Maybe this is where the confusion is, but I'm expecting the following:
1. `initContainersReusableMemory` contains the current state of reusable memory that a container can reusse when making allocation decisions
2. `getPodReusableMemory()` uses `initContainersReusableMemory` (plus other logic) to decide exaclty what memory to allocate to a container
3. Later on `updateInitContainersReusableMemory()` is called with the *actual* set of memory blocks allocated to the container so that the state of `initContainersReusableMemory()` can be updated appropriately.

[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: I currently trying to update the code according to the comment, and one problem that I encounter, I still need to update the init container memory assignments once I start new init or app container.

Like for the CPU manager, something like `{init1: 4-7, app1: 4-7}` makes total sense and reflects correct the machine state.
But for the memory manager `{init1: 1G, app1: 1G}` does not reflect the real machine state, so during the allocation of the container app1 we need to update init1 memory to 0(memory re-used).

[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: Why does that not reflect the real machine state? They are both allocated that much memory at the the time they each run.

Is it because of the way memory accounting is done internally? I.e. there is no way to „discretely“ divide up the memory (it is just a count/size), so there is no way to know that that memory is the „same“ memory (rather than being additive).

[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: If so, that feels like a Limitation of the data structure used to represent the memory allocations (I.e. it wasn’t designed to account for memory reuse across containers).

Althogh the accounting would be „correct“ in terms of total memory allocated if you set the init containers allocation to 0, I find it equally confusing to see that set to 0 the b the final machine state even though it clearly had/has some memory allocated to it.

[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:847]: > Is it because of the way memory accounting is done internally? I.e. there is no way to „discretely“ divide up the memory (it is just a count/size), so there is no way to know that that memory is the „same“ memory (rather than being additive).

Yes, it exactly the reason, the allocation with 0 value will stay under the state file only until the next container started.
I can avoid setting it to 0 and it will make logic much simplier, but in this case, we will have different numbers for `sum(requests_accross_all_containers)` and machine free memory.

File: pkg/kubelet/cm/memorymanager/memory_manager.go [hunk 9]
```diff
@@ -193,6 +193,17 @@ func (m *manager) AddContainer(pod *v1.Pod, container *v1.Container, containerID
...
+	// we know that init containers start in the same order as they present
+	// under the pod.spec.initContainers, so we delete all init containers until we
+	// reach one with the same name as the current one
+	for _, initContainer := range pod.Spec.InitContainers {
+		if initContainer.Name == container.Name {
+			break
+		}
+
+		m.policyRemoveContainerByRef(string(pod.UID), initContainer.Name)
+	}
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/memory_manager.go:206]: Why is this needed exactly? Why can't we just wait for `RemoveContainer` to clean this up for all containers? As it stands, things will be removed for all init containers (except that last one), which feels a little awkward (especially since it's not clear why it's necessary to remove this state here).

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 10]
```diff
@@ -146,53 +152,88 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
-			if nodeResourceMemoryState.Free >= requestedSize {
-				nodeResourceMemoryState.Reserved += requestedSize
-				nodeResourceMemoryState.Free -= requestedSize
-				requestedSize = 0
-				continue
-			}
+	// update init containers memory blocks to reflect the fact that we re-used init containers memory
+	// it possible that the size of the init container memory block will have 0 value, when all memory
+	// allocated for it was re-used
+	p.updateInitContainersMemoryBlocks(s, pod)
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:174]: Can you expand this comment a bit. Saying that we only do this so that the sum(memory_for_all_containers) == total amount of allocated memory to the pod (even though the fine state here doesn't accurately reflect what was (in reality) allocated to each container). Then add a TODO to update the data structure to handle this better in the future.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 11]
```diff
@@ -146,53 +152,88 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
+		// the node does not have enough memory, use the node remaining memory and move to the next node
+		requestedSize -= nodeResourceMemoryState.Free
+		nodeResourceMemoryState.Reserved += nodeResourceMemoryState.Free
+		nodeResourceMemoryState.Free = 0
 	}
+}
 
-	s.SetMachineState(machineState)
-	s.SetMemoryBlocks(string(pod.UID), container.Name, containerBlocks)
+func (p *staticPolicy) getPodReusableMemory(pod *v1.Pod, bitMask bitmask.BitMask, resourceName v1.ResourceName) uint64 {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:210]: can we call the second parameter `numaAffinity` for consistency with other places.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 12]
```diff
@@ -788,3 +830,102 @@ func (p *staticPolicy) GetAllocatableMemory(s state.State) []state.Block {
...
+		if _, ok := updatedPodReusableMemory[numaAffinity]; !ok {
+			updatedPodReusableMemory[numaAffinity] = map[v1.ResourceName]uint64{}
+		}
+
+		for resourceName, size := range resourceReusable {
+			updatedPodReusableMemory[numaAffinity][resourceName] = size
+		}
+	}
+
+	for i := len(pod.Spec.InitContainers) - 1; i >= 0; i-- {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:891]: Is there any particular reason to walk backwards?

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 13]
```diff
@@ -788,3 +830,102 @@ func (p *staticPolicy) GetAllocatableMemory(s state.State) []state.Block {
...
+				p.initContainersReusableMemory[podUID][blockBitMask.String()][block.Type] -= block.Size
+			}
+		}
+	}
+}
+
+func (p *staticPolicy) updateInitContainersMemoryBlocks(s state.State, pod *v1.Pod) {
+	podUID := string(pod.UID)
+	updatedPodReusableMemory := map[string]map[v1.ResourceName]uint64{}
+	for numaAffinity, resourceReusable := range p.initContainersReusableMemory[podUID] {
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:881]: I wouldn't expect this to have to look at `initContainersReusableMemory` at all. I would expect it to have a signature of:
```
updateInitContainersMemoryBlocks(s state.State, pod *v1.Pod, container *v1.Container, memoryBlocks []state.Block)
```
Where `container` is the current container, and `memoryBlocks` are the set of memory blocks just allocated to this container in this iteration of `Allocate()`.

The logic in this function would then loop over all the memory blocks for all init containers (that are not the current container) and subtract out what it can from them, given the set of memory blocks passed in.

**Review by klueska — COMMENTED** [review]
This flow is much easier to follow than how it was written before. Just a few small comments, but the overall PR is looking good now.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 9 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:206]: The `RemoveContainer` is a redundant method that we do not really use under the container manager, see - https://github.com/kubernetes/kubernetes/pull/90377. So in general we clean things only during calls to
`GetTopologyHints`, `Allocate` or `AddContainer`

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 10 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:174]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 11 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:210]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 12 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:891]: The init containers started in the order specified under `pod.Spec.InitContainers`, so first, we want to re-use the memory allocated for the first init container, so the update of the re-usable memory should go backward.

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 13 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:881]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 12 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go:891]: Changed the logic, no need anymore.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 9 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:206]: Would it be possible to make an explicit call to `removeStaleState()` here instead?  I know it will end up doing a bit more redundant work, but at least it will be intuitive as to why we might be calling something like that here. As it stands it still feels awkward to just explicitly be removing some containers here in the way you are doing.

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 14]
```diff
@@ -146,53 +152,91 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
 
-			// the node has enough memory to satisfy the request
-			if nodeResourceMemoryState.Free >= requestedSize {
-				nodeResourceMemoryState.Reserved += requestedSize
-				nodeResourceMemoryState.Free -= requestedSize
-				requestedSize = 0
-				continue
-			}
+	// update init containers memory blocks to reflect the fact that we re-used init containers memory
+	// it possible that the size of the init container memory block will have 0 value, when all memory
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:172]: s/it possible/it is possible/

File: pkg/kubelet/cm/memorymanager/policy_static.go [hunk 15]
```diff
@@ -146,53 +152,91 @@ func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Contai
...
+	// allocated for it was re-used
+	// we only do this so that the sum(memory_for_all_containers) == total amount of allocated memory to the pod, even
+	// though the fine state here doesn't accurately reflect what was (in reality) allocated to each container
```
Comment (klueska) [inline pkg/kubelet/cm/memorymanager/policy_static.go:175]: s/fine/final

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/policy_static.go:238]: It doesn't seem like this was moved yet?

**Review by klueska — COMMENTED** [review]
Just a few lingering comments. Looking good though.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 9 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:206]: The problem that `removeStaleState()` remove only containers for dead pods.
```
// Build a list of (podUID, containerName) pairs for all containers in all active Pods.
	activeContainers := make(map[string]map[string]struct{})
	for _, pod := range activePods {
		activeContainers[string(pod.UID)] = make(map[string]struct{})
		for _, container := range append(pod.Spec.InitContainers, pod.Spec.Containers...) {
			activeContainers[string(pod.UID)][container.Name] = struct{}{}
		}
	}
```
it does not really filter terminated containers. Do you want to refactor it?

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 14 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 15 above)
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go]: done

File: pkg/kubelet/cm/memorymanager/policy_static.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (cynepco3hahue) [reply pkg/kubelet/cm/memorymanager/policy_static.go]: I added it under `updateInitContainersReusableMemory`, but forgot to delete it here.

File: pkg/kubelet/cm/memorymanager/memory_manager.go (hunk 9 above)
Comment (klueska) [reply pkg/kubelet/cm/memorymanager/memory_manager.go:206]: Dsicussed offline, and decided this is OK, so long as we add a more descriptive comment. Something like:
```
	// Since we know that each init container always runs to completion before
	// the next container starts, we can safely remove references to any previously
	// started init containers. This will free up the memory from these init containers
	// for use in other pods. If the current container happens to be an init container,
	// we skip deletion of it until the next container is added, and this is called again.
```

**Comment by klueska** [comment]
@cynepco3hahue
Thank you for your patience in making all of the requested changes for this PR. It was simplified quite a bit after we iterated on it for a while, so I hope you agree it was worth the extra effort / time. I didn't check the test coverage to verify that it is exhaustive, but given that this is still a beta feature, we can add more tests over time as issues come up or we notice any gaps.

/lgtm
/approve

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue
> Thank you for your patience in making all of the requested changes for this PR. It was simplified quite a bit after we iterated on it for a while, so I hope you agree it was worth the extra effort / time. I didn't check the test coverage to verify that it is exhaustive, but given that this is still a beta feature, we can add more tests over time as issues come up or we notice any gaps.

A lot of thanks for the great review, I definitely agree it was worth the extra effort and time!
