### PR TITLE
Fixes device plugin re-registration handling logic to make sure:

### LINKED ISSUE #52510: resources exported by a device plugin are not removed from kubelet node status after the device plugin is removed
> /kind bug

**What happened**:
When we delete a device plugin, its exported resources are still listed in node status.

**What you expected to happen**:
The resource should be removed after its device plugin is deleted.

**How to reproduce it (as minimally and precisely as possible)**:
The existing test/e2e/scheduling/nvidia-gpus.go has already been extended to reproduce this bug.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jiayingz**
- If a device plugin exits, its exported resource will be removed.
- No capacity change if a new device plugin instance comes up to replace the old instance.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/52510

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test

k8s-ci-robot hasn't noticed that you're already a member :)

**Comment by vishh** [comment]
Can we have a unit test for this PR?

File: pkg/kubelet/deviceplugin/manager.go [hunk 1]
```diff
@@ -189,48 +189,48 @@ func (m *ManagerImpl) Register(ctx context.Context,
...
 		glog.Errorf("Failed to List devices for plugin %v: %v", r.ResourceName, err)
 		return
 	}
 
+	// Associates the newly created endpoint with the corresponding resource name.
+	// Stops existing endpoint if there is any.
+	m.mutex.Lock()
+	old, ok := m.endpoints[r.ResourceName]
+	m.endpoints[r.ResourceName] = e
+	glog.V(2).Infof("Registered endpoint %v", e)
```
Comment (RenaudWasTaken) [inline pkg/kubelet/deviceplugin/manager.go]: Nit: Log outside the mutex lock / unlock

Comment (jiayingz) [reply pkg/kubelet/deviceplugin/manager.go]: done.

File: pkg/kubelet/deviceplugin/manager_test.go [hunk 2]
```diff
@@ -17,43 +17,75 @@ limitations under the License.
...
+func TestDevicePluginReRegistration(t *testing.T) {
+	devs := []*pluginapi.Device{
+		{ID: "Dev1", Health: pluginapi.Healthy},
+		{ID: "Dev2", Health: pluginapi.Healthy},
+	}
+
+	var callbackCount int32 = 0
+	callback := func(n string, a, u, r []*pluginapi.Device) {
+		// Should be called twice, one for each plugin.
+		if atomic.LoadInt32(&callbackCount) > 1 {
```
Comment (RenaudWasTaken) [inline pkg/kubelet/deviceplugin/manager_test.go]: why do we need an int32 and a call to `atomic.LoadInt32`

File: pkg/kubelet/deviceplugin/manager_test.go [hunk 3]
```diff
@@ -17,43 +17,75 @@ limitations under the License.
...
+			t.FailNow()
+		}
+		atomic.AddInt32(&callbackCount, 1)
+	}
+	m, p1 := setup(t, devs, callback)
+	p1.Register(socketName, testResourceName)
+	// Wait for the first callback to be issued.
+	for i := 0; i < 10; i++ {
```
Comment (RenaudWasTaken) [inline pkg/kubelet/deviceplugin/manager_test.go]: This seems prone to flack. Wondering if we could use channels instead ? What do you think ?

File: pkg/kubelet/deviceplugin/manager_test.go [hunk 4]
```diff
@@ -17,43 +17,75 @@ limitations under the License.
...
 }
 
 func TestNewManagerImplStart(t *testing.T) {
-	wd, _ := os.Getwd()
-	socket := path.Join(wd, msocketName)
+	setup(t, []*pluginapi.Device{}, func(n string, a, u, r []*pluginapi.Device) {})
+}
 
-	_, err := NewManagerImpl(socket, func(n string, a, u, r []*pluginapi.Device) {})
+func TestDevicePluginReRegistration(t *testing.T) {
```
Comment (mindprince) [inline pkg/kubelet/deviceplugin/manager_test.go]: Can you add a comment specifying what is the expected behavior and what condition(s) in re-registration logic this test is guarding against? It's not clear from the comments in the test.

File: pkg/kubelet/deviceplugin/device_plugin_stub.go [hunk 5]
```diff
@@ -86,6 +87,30 @@ func (m *Stub) Stop() error {
 	return m.cleanup()
 }
 
+// Register registers the device plugin for the given resourceName with Kubelet.
+func (m *Stub) Register(kubeletEndpoint, resourceName string) error {
```
Comment (mindprince) [inline pkg/kubelet/deviceplugin/device_plugin_stub.go]: Does this method need to be exported?

**Review by rohitagarwal003 — CHANGES_REQUESTED** [review]

File: pkg/kubelet/deviceplugin/device_plugin_stub.go (hunk 5 above)
Comment (jiayingz) [reply pkg/kubelet/deviceplugin/device_plugin_stub.go]: Right now, this stub is not used outside but it could be if we want to test integration with device plugin, at which point we will want to have this API exported.

File: pkg/kubelet/deviceplugin/manager_test.go (hunk 4 above)
Comment (jiayingz) [reply pkg/kubelet/deviceplugin/manager_test.go]: done.

**Comment by lichuqiang** [comment]
The change itself looks good to me, what I wonder is if it is needed to add the logic `that prioritizes the registration for a given resource if it has been registered multiple times in a short period` as you mentioned in #52190, or just subject to the latest registration?

File: pkg/kubelet/kubelet_node_status.go [hunk 6]
```diff
@@ -602,9 +602,19 @@ func (kl *Kubelet) setNodeStatusMachineInfo(node *v1.Node) {
...
 			for k, v := range initialCapacity {
 				if v1helper.IsExtendedResourceName(k) {
+					glog.V(2).Infof("Update capacity for %s to %d", k, v.Value())
 					node.Status.Capacity[k] = v
 				}
 			}
+			// Remove stale extended resources.
+			for k := range node.Status.Capacity {
+				if v1helper.IsExtendedResourceName(k) {
+					if _, ok := initialCapacity[k]; !ok {
```
Comment (vishh) [inline pkg/kubelet/kubelet_node_status.go]: nit: `initialCapacity` should be named as `currentCapacity`.

**Comment by vishh** [comment]
/lgtm
/approve

Just a nit, would be great if you can fix it. If not address it in a future PR.

File: pkg/kubelet/kubelet_node_status.go (hunk 6 above)
Comment (jiayingz) [reply pkg/kubelet/kubelet_node_status.go]: done. PTAL.
