### PR TITLE
Fix the defaultServerImage name of hyperkube in kubefed

### LINKED ISSUE #53430: Kubernetes federation invalid reference format
/kind bug

**What happened**:
Federation set up using kubefed uses invalid reference format, breaking the Federation control plane.

```
r}   Warning   InspectFailed   kubelet, gke-kubernetes-cluster-pool-1-76a09ebd-b587   Failed to apply default image tag "gcr.io/google_containers/hyperkube-amd64:v1.8.0+0b9efaeb34a2f": couldn't parse image reference "gcr.io/google_containers/hyperkube-amd64:v1.8.0+0b9efaeb34a2f": invalid reference format
2017-10-04 14:07:14 +0200 CEST   2017-10-04 14:00:47 +0200 CEST   31        fed-zone-europe-controller-manager-4130961042-m9c3z.14ea5c3e2a63466e   Pod                 Warning   FailedSync   kubelet, gke-kubernetes-cluster-pool-1-76a09ebd-b587   Error syncing pod
```
**What you expected to happen**:
That it works.

**How to reproduce it (as minimally and precisely as possible)**:
Try to set up a control plane using kubefed.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0+0b9efaeb34a2f", GitCommit:"638b0a06d928e7a12fa29bb12610158a235585d7", GitTreeState:"dirty", BuildDate:"2017-10-02T09:48:25Z", GoVersion:"go1.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.6-gke.1", GitCommit:"407dbfe965f3de06b332cc22d2eb1ca07fb4d3fb", GitTreeState:"clean", BuildDate:"2017-09-27T21:21:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
GCP
- OS (e.g. from /etc/os-release):
Ubuntu Xenial
- Kernel (e.g. `uname -a`): Irrelevant
- Install tools: GKE

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**:
Fixes the issue mentioned in https://github.com/kubernetes/kubernetes/issues/53430

Docker images cannot contain special characters like '+' in the tags. So while uploading the federation container images we replace '+' character by '_'. This should have been taken care by kubefed too while consuming the federation container image.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53430

**Special notes for your reviewer**:
This PR fixes the "invalid reference format" issue for the docker image. But am not sure if the version of hyperkube image is available in registry. The version is got from `version.Get()`. So if a user has built the kubefed from source it may be possible that the hyperkube version referenced by that commit is not available in registry. Ideally this issue should not arise on released versions of kubefed.

We need to cherry-pick this fix to all previous supported k8s versions too.

**Release note**:
```release-note
NONE
```

/cc @kubernetes/sig-multicluster-bugs

### CODE REVIEW

File: federation/cmd/kubefed/app/kubefed.go [hunk 1]
```diff
@@ -34,7 +35,7 @@ const (
 )
 
 func GetDefaultServerImage() string {
-	return fmt.Sprintf("%s:%s", hyperkubeImageName, version.Get())
+	return fmt.Sprintf("%s:%s", hyperkubeImageName, strings.Replace(version.Get().String(), "+", "_", 1))
```
Comment (dims) [inline federation/cmd/kubefed/app/kubefed.go]: Are there other chars that will show up that will need special handling? Is using a standard mechanism like the url encoding be useful here?

Comment (shashidharatd) [reply federation/cmd/kubefed/app/kubefed.go]: @dims, AFAIK there will be no other characters which need special handling. Also note that the docker image tag should follow the naming convention as below: (taken from the docker documentation)
```
A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
```
Since our `version.Get()` returns an image with '+' character, we chose to replace it with '_' character in [here](https://github.com/kubernetes/kubernetes/blob/master/build/util.sh#L31), while pushing the docker image to gcr in [here](https://github.com/kubernetes/kubernetes/blob/master/federation/develop/develop.sh#L118:L136)

Comment (dims) [reply federation/cmd/kubefed/app/kubefed.go]: LGTM 👍
