### PR TITLE
Fix initialization of volume controller caches.

### LINKED ISSUE #28076: TestControllerSync {persistentvolume}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/13471/

Failed: TestControllerSync {persistentvolume}

```
framework_test.go:810: Test "5-6 - update bound volume from 1.2": Claim check failed [A-expected, B-got result]: {"claim5-6":{"metadata":{"name":"claim5-6","namespace":"default","selfLink":"/api/v1/pvc/claim5-6","uid":"uid5-6","creationTimestamp":null
	
	A: ,"annotations":{"pv.kubernetes.io/bind-completed":"yes"}},"spec":{"accessModes":["ReadWriteOnce","ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"volumeName":"volume5-6"},"status":{"phase":"Bound"}}}
	
	B: },"spec":{"accessModes":["ReadWriteOnce","ReadOnlyMany"],"resources":{"requests":{"storage":"1Gi"}},"volumeName":"volume5-6"},"status":{"phase":"Bound"}}}
	
```

### PR DESCRIPTION
**Pull request by jsafrane**
Fix `PersistentVolumeController.initializeCaches()` to pass pointers to volume or claim to  `storeObjectUpdate()` and add extra functions to enforce that the right types are checked in the future.

Fixes #28076

### CODE REVIEW

**Comment by jsafrane** [comment]
This should be cherry picked together with #28002

**Comment by jsafrane** [comment]
cc @kubernetes/sig-storage @lavalamp @asalkeld

File: pkg/controller/persistentvolume/controller_base.go [hunk 1]
```diff
@@ -148,7 +149,12 @@ func (ctrl *PersistentVolumeController) initializeCaches(volumeSource, claimSour
 		// Ignore template volumes from kubernetes 1.2
 		deleted := ctrl.upgradeVolumeFrom1_2(&volume)
 		if !deleted {
-			storeObjectUpdate(ctrl.volumes.store, volume, "volume")
+			clone, err := conversion.NewCloner().DeepCopy(&volume)
+			if err != nil {
+				glog.Errorf("error cloning volume %q: %v", volume.Name, err)
```
Comment (lavalamp) [inline pkg/controller/persistentvolume/controller_base.go]: If you get this error, you continue to use clone right below?

File: pkg/controller/persistentvolume/controller_base.go [hunk 2]
```diff
@@ -163,11 +169,24 @@ func (ctrl *PersistentVolumeController) initializeCaches(volumeSource, claimSour
 		return
 	}
 	for _, claim := range claimList.Items {
-		storeObjectUpdate(ctrl.claims, claim, "claim")
+		clone, err := conversion.NewCloner().DeepCopy(&claim)
+		if err != nil {
+			glog.Errorf("error cloning claim %q: %v", claimToClaimKey(&claim), err)
```
Comment (lavalamp) [inline pkg/controller/persistentvolume/controller_base.go]: same

File: pkg/controller/persistentvolume/controller_base.go [hunk 3]
```diff
@@ -163,11 +169,24 @@ func (ctrl *PersistentVolumeController) initializeCaches(volumeSource, claimSour
...
+		}
+		claimClone := clone.(*api.PersistentVolumeClaim)
+		ctrl.storeClaimUpdate(claimClone)
 	}
 	glog.V(4).Infof("controller initialized")
 }
 
+func (ctrl *PersistentVolumeController) storeVolumeUpdate(volume *api.PersistentVolume) (bool, error) {
```
Comment (lavalamp) [inline pkg/controller/persistentvolume/controller_base.go]: +1 for strongly typed functions like this, thanks

**Comment by lavalamp** [comment]
The added type checking makes me feel a LOT better about this code, thanks.

**Comment by timothysc** [comment]
Umm this is effecting nearly every PR atm.

**Comment by jlowdermilk** [comment]
Anything we can do to accelerate this? PV controller unit test flake (#28076) is dominating cause of submit queue blockage.

**Comment by lavalamp** [comment]
I'm ok with merging now and fixing my comments in a follow-up if this is blocking merges.

**Comment by jlowdermilk** [comment]
Yeah, the issue this (hopefully) fixes is blocking merges and causing pr builder flakes.

**Comment by lavalamp** [comment]
LGTM

**Comment by jsafrane** [comment]
Thanks for review, I filled #28108 with fixed error checks.

**Comment by lavalamp** [comment]
@jsafrane I think you meant #28147, which I just LGTMed and requested a cherry-pick for. Thanks!
