### PR TITLE
Listing pods only once when getting pods for RS in deployment

### LINKED ISSUE #26834: [k8s.io] Deployment deployment should support rollover {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce/18111/

Failed: [k8s.io] Deployment deployment should support rollover {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:70
Expected error:
    <*errors.errorString | 0xc8204c54a0>: {
        s: "error waiting for deployment test-rollover-deployment status to match expectation: total pods available: 2, less than the min required: 3",
    }
    error waiting for deployment test-rollover-deployment status to match expectation: total pods available: 2, less than the min required: 3
not to have occurred
```

Previous issues for this test: #26509

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #26834
1. Avoid ranging over RSes and then `List` pods of each RS. Instead, `List` pods of the deployment once, and then filter pods of each RS. 
2. Avoid using clientset to `List` pods in deployment controller. Use podStore instead. (TODO in some functions because the unit tests don't have podStore.)

@kubernetes/deployment 

[Analytics]()

### CODE REVIEW

File: pkg/util/deployment/deployment.go [hunk 1]
```diff
@@ -288,22 +288,30 @@ func GetActualReplicaCountForReplicaSets(replicaSets []*extensions.ReplicaSet) i
...
-	allPods, err := GetPodsForReplicaSets(c, rss)
+func GetAvailablePodsForReplicaSets(c clientset.Interface, deployment *extensions.Deployment, rss []*extensions.ReplicaSet, minReadySeconds int32) (int32, error) {
+	podList, err := listPods(deployment, c)
+	if err != nil {
+		return 0, err
+	}
+	return FindAvailablePodsForReplicaSets(rss, minReadySeconds, podList)
+}
+
+func FindAvailablePodsForReplicaSets(rss []*extensions.ReplicaSet, minReadySeconds int32, podList *api.PodList) (int32, error) {
```
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: Nit: Consider naming this either `CountAvailablePodsInReplicaSets`.  Also I would put the PodList as the first argument to the function.

File: pkg/util/deployment/deployment.go [hunk 2]
```diff
@@ -288,22 +288,30 @@ func GetActualReplicaCountForReplicaSets(replicaSets []*extensions.ReplicaSet) i
...
 	if err != nil {
 		return 0, err
 	}
-	return getReadyPodsCount(allPods, minReadySeconds), nil
+	return getAvailablePodsCount(allPods, minReadySeconds), nil
 }
 
-func getReadyPodsCount(pods []api.Pod, minReadySeconds int32) int32 {
-	readyPodCount := int32(0)
+func getAvailablePodsCount(pods []api.Pod, minReadySeconds int32) int32 {
```
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: nit: Consider naming this in a consistent way with the other filter function.

File: test/e2e/framework/util.go [hunk 3]
```diff
@@ -3042,8 +3042,16 @@ func WaitForObservedDeployment(c *clientset.Clientset, ns, deploymentName string
 	return deploymentutil.WaitForObservedDeployment(func() (*extensions.Deployment, error) { return c.Extensions().Deployments(ns).Get(deploymentName) }, desiredGeneration, Poll, 1*time.Minute)
 }
 
-func logPodsOfReplicaSets(c clientset.Interface, rss []*extensions.ReplicaSet, minReadySeconds int32) {
-	allPods, err := deploymentutil.GetPodsForReplicaSets(c, rss)
+func logPodsOfReplicaSets(c clientset.Interface, deployment *extensions.Deployment, rss []*extensions.ReplicaSet, minReadySeconds int32) {
+	podList, err := deploymentutil.ListPods(deployment,
+		func(namespace string, options api.ListOptions) (*api.PodList, error) {
+			return c.Core().Pods(namespace).List(options)
```
Comment (pwittrock) [inline test/e2e/framework/util.go]: Why do we use the options.LabelSelector in the production code, and just the raw options here?

File: pkg/util/deployment/deployment.go [hunk 4]
```diff
@@ -327,21 +335,19 @@ func IsPodAvailable(pod *api.Pod, minReadySeconds int32) bool {
...
-			options := api.ListOptions{LabelSelector: selector}
-			podList, err := c.Core().Pods(rs.ObjectMeta.Namespace).List(options)
-			if err != nil {
-				return nil, fmt.Errorf("error listing pods: %v", err)
-			}
 			for _, pod := range podList.Items {
-				allPods[pod.Name] = pod
+				podLabelsSelector := labels.Set(pod.ObjectMeta.Labels)
+				if selector.Matches(podLabelsSelector) {
+					allPods[pod.Name] = pod
```
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: When could there already be a pod with the same name?  Does this mean 2 RS have overlapping label selectors?  Is this an error condition we should be logging as Errorf?

File: test/e2e/framework/util.go (hunk 3 above)
Comment (pwittrock) [inline test/e2e/framework/util.go]: Nevermind, I see these are different client types.

File: pkg/util/deployment/deployment.go [hunk 5]
```diff
@@ -288,22 +288,30 @@ func GetActualReplicaCountForReplicaSets(replicaSets []*extensions.ReplicaSet) i
...
+func GetAvailablePodsForReplicaSets(c clientset.Interface, deployment *extensions.Deployment, rss []*extensions.ReplicaSet, minReadySeconds int32) (int32, error) {
+	podList, err := listPods(deployment, c)
+	if err != nil {
+		return 0, err
+	}
+	return FindAvailablePodsForReplicaSets(rss, minReadySeconds, podList)
+}
+
+func FindAvailablePodsForReplicaSets(rss []*extensions.ReplicaSet, minReadySeconds int32, podList *api.PodList) (int32, error) {
+	allPods, err := GetPodsForReplicaSets(rss, podList)
```
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: Under what conditions will allPods != podList?  This would mean there is a Pod that matches the deployment that does not belong in a RS?

File: pkg/util/deployment/deployment.go (hunk 4 above)
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: Is it still necessary to use a map for deduping here since the list of Pods is passed in, and presumably does not contain the same Pod multiple times?

File: pkg/util/deployment/deployment.go [hunk 6]
```diff
@@ -327,21 +335,19 @@ func IsPodAvailable(pod *api.Pod, minReadySeconds int32) bool {
 	return false
 }
 
-func GetPodsForReplicaSets(c clientset.Interface, replicaSets []*extensions.ReplicaSet) ([]api.Pod, error) {
+func GetPodsForReplicaSets(replicaSets []*extensions.ReplicaSet, podList *api.PodList) ([]api.Pod, error) {
```
Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: WDYT of renaming this something like 'FilterPodsMatchingReplicaSets' since it is now just filtering the list?  Consider using [collection functions such as these](https://gobyexample.com/collection-functions) to do the heavy lifting.

File: pkg/util/deployment/deployment.go (hunk 1 above)
Comment (janetkuo) [inline pkg/util/deployment/deployment.go]: fixed

File: pkg/util/deployment/deployment.go (hunk 2 above)
Comment (janetkuo) [inline pkg/util/deployment/deployment.go]: renamed to countAvailablePods

File: pkg/util/deployment/deployment.go (hunk 4 above)
Comment (janetkuo) [inline pkg/util/deployment/deployment.go]: Removed this

File: pkg/util/deployment/deployment.go (hunk 5 above)
Comment (janetkuo) [inline pkg/util/deployment/deployment.go]: for example, when we only want available pods of the new replicaset

File: pkg/util/deployment/deployment.go (hunk 6 above)
Comment (janetkuo) [inline pkg/util/deployment/deployment.go]: done

**Comment by janetkuo** [comment]
@pwittrock ptal

**Comment by pwittrock** [comment]
Looks like the tests panic

>
--- FAIL: TestDeploymentController_reconcileOldReplicaSets (0.00s)
	deployment_controller_test.go:287: executing scenario 0
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x60 pc=0x89291b]

**Comment by janetkuo** [comment]
"unable to create test archive failed to copy ginkgo exit status 1.."
@k8s-bot node e2e test this issue: #IGNORE

**Comment by pwittrock** [comment]
@k8s-bot node e2e test this issue: #27104

**Comment by janetkuo** [comment]
> 2.Avoid using clientset to `List` pods in deployment controller. Use podStore instead.

I had to undo some of these changes since deployment controller unit test doesn't support podStore. See the 3rd commit for more.

File: pkg/util/replicaset/replicaset.go [hunk 7]
```diff
@@ -91,3 +93,18 @@ func GetPodTemplateSpecHash(rs extensions.ReplicaSet) string {
 		Spec:       rs.Spec.Template.Spec,
 	}))
 }
+
+// MatchingPodsFunc returns a filter function for pods with matching labels
+func MatchingPodsFunc(rs *extensions.ReplicaSet) (func(api.Pod) bool, error) {
+	if rs != nil {
```
Comment (kargakis) [inline pkg/util/replicaset/replicaset.go]: Blacklist instead to reduce indentation
```go
if rs == nil {
   return nil, nil
}
...
```

File: pkg/controller/deployment/deployment_controller.go [hunk 8]
```diff
@@ -986,7 +997,8 @@ func (dc *DeploymentController) reconcileOldReplicaSets(allRSs []*extensions.Rep
 
 	minReadySeconds := deployment.Spec.MinReadySeconds
 	allPodsCount := deploymentutil.GetReplicaCountForReplicaSets(allRSs)
-	newRSAvailablePodCount, err := deploymentutil.GetAvailablePodsForReplicaSets(dc.client, []*extensions.ReplicaSet{newRS}, minReadySeconds)
+	// TODO: use dc.getAvailablePodsForReplicaSets instead
```
Comment (kargakis) [inline pkg/controller/deployment/deployment_controller.go]: Why can't you switch to it now?

Comment (janetkuo) [inline pkg/controller/deployment/deployment_controller.go]: explained in https://github.com/kubernetes/kubernetes/pull/27012#issuecomment-224801601

File: pkg/util/replicaset/replicaset.go (hunk 7 above)
Comment (janetkuo) [inline pkg/util/replicaset/replicaset.go]: thanks, fixed

File: pkg/util/deployment/deployment.go [hunk 9]
```diff
@@ -354,29 +374,20 @@ func IsPodAvailable(pod *api.Pod, minReadySeconds int32) bool {
...
-			podList, err := c.Core().Pods(rs.ObjectMeta.Namespace).List(options)
-			if err != nil {
-				return nil, fmt.Errorf("error listing pods: %v", err)
-			}
-			for _, pod := range podList.Items {
-				allPods[pod.Name] = pod
-			}
+		matchingFunc, err := rsutil.MatchingPodsFunc(rs)
+		if err != nil {
+			return nil, err
```
Comment (kargakis) [inline pkg/util/deployment/deployment.go]: Do you really need to return here? If a replica set has an invalid label selector then isn't it fine to just ignore it and try to update the deployment status anyway?

Comment (pwittrock) [inline pkg/util/deployment/deployment.go]: @kargakis You may be right, but since this keeps the old behavior w.r.t. handling errors and today is the last day to get 1.3 stuff in, I vote that we should do it in a follow up if at all.

**Comment by pwittrock** [comment]
@janetkuo LGTM.  Please squash and apply LGTM label

**Comment by janetkuo** [comment]
Aborted by user anonymous
@k8s-bot test this issue: #IGNORE

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #24476
