### PR TITLE
delete node from aws if it is terminated

### LINKED ISSUE #69409: Node doesn't get deleted after being terminated in AWS (1.12 only)
/kind bug

**What happened**:
After upgrading 1.11.1 -> 1.12.0 , when a node gets terminated in AWS, the controller-manager doesn't delete the node in the API. 
This has lead to several side effect for us : 
* pods don't get GC
* Prometheus alerts firing because 100 of nodes are in the NotReady state for a long period

**What you expected to happen**:
kube-controller-manager deletes the node when it stops reporting, after checking with the cloud provider.

**How to reproduce it (as minimally and precisely as possible)**:
Looking at the code, I believe this is what introduced the behaviour change : 
https://github.com/kubernetes/kubernetes/issues/58635 - https://github.com/kubernetes/kubernetes/pull/60009

The node gets tainted with `node.cloudprovider.kubernetes.io/shutdown:NoSchedule` because it's in a Terminated state. But it doesn't get removed because it still "exists" in the cloud provider.

The behaviour is probably correct for a shutdown node, but in AWS a terminated node can't be restarted so there's no good reason to keep it there ?

**Environment**:
- Kubernetes version : 1.2.0
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CoreOS

(sorry for the all the sigs, not sure who it belongs to)
/sig aws
/sig cloud-provider
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by zetaab**
**What this PR does / why we need it**: currently (1.12 ->) nodes are not deleted from cluster if those are terminated

**Which issue(s) this PR fixes**: 
Fixes #69409

**Special notes for your reviewer**: When we remove terminated state from shutdown function. Then it does not add shutdown taint if node is terminated - instead it will delete node. 

Also if we see that instance does not exist already in shutdown function, we should continue forward. Otherwise the node is not deleted either. It is little bit stupid to retrieve same instance status twice but thats not easy to modify because all cloudproviders are using it.

**Release note**:
```release-note
NONE
```
/sig aws
/kind bug
/cc @sjenning @gnufied

### CODE REVIEW

**Comment by zetaab** [comment]
/test pull-kubernetes-integration
--

**Comment by zetaab** [comment]
@gnufied could you check this

**Comment by mvisonneau** [comment]
I've tested it and it seems to fix properly indeed 👍thanks for the patch. Perhaps some additional testing would be interesting too in order to not get this regression again in the future as it can be quite impactful.

**Comment by sjenning** [comment]
It seems weird to me to return `false` for `ShutdownInCloudProvider` when the instance is `Terminated`.  In my mind, `Terminated` is implicitly `Shutdown` (i.e. permanently shutdown).

However, looking at the other cloud providers, it does seem that they do not return true unless the instance 1) exists and 2) can be positively identified as being shutdown.

/lgtm

**Comment by zetaab** [comment]
can someone add approve label as well

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -1386,7 +1386,9 @@ func (c *Cloud) InstanceShutdownByProviderID(ctx context.Context, providerID str
 	}
 	if len(instances) == 0 {
 		glog.Warningf("the instance %s does not exist anymore", providerID)
-		return true, nil
+		// returns false, because otherwise node is not deleted from cluster
+		// false means that continue to to check InstanceExistsByProviderID
```
Comment (mikkeloscar) [inline pkg/cloudprovider/providers/aws/aws.go]: Something is wrong with this sentence. *to* is twice and it feels like a word is missing between *that* and *continue* :)

**Comment by sjenning** [comment]
trivial comment change. re-lgtm'ing
/lgtm

**Review by yastij — APPROVED** [review]
/lgtm

**Comment by jrake-revelant** [comment]
Is there an ETA for merging this? It is blocking our cluster upgrade process. If we can help in any way please let me know.
