### PR TITLE
Switch to e2 machine types

### LINKED ISSUE #116114: Kubelet e2e tests are failing on public ubuntu-2204 AWS AMIs
### What happened?

I'm working with @dims and @tzneal on enabling e2e tests on AWS. We want to run many e2e tests on there as we have alot of AWS credits to consume. As part of that journey, we need to start building on public AWS ubuntu AMIs and add features to `test/e2e_node/runner/run_remote.go` to build instances in AWS.

I'm using cloud-init to bootstrap the linux node before the test is run but I seem to be missing some configuration as I have some 20+ broken tests.

cloud-init file + configure.sh is available at https://github.com/containerd/containerd/pull/8170
`run_remote.go` changes: https://github.com/tzneal/kubernetes/pull/1

We'll refine `run_remote.go` and raise a PR that adds support for creation of AWS VMs and then initially insert a CI job and then eventually promote it to a presubmit + master-blocking

/sig node

### What did you expect to happen?

Build Args

```
REDACTED@knative-e2e:~/tz-kubernetes$ make test-e2e-node REMOTE=true REMOTE_MODE=aws IMAGES="ami-02a6a91c1d29fc428" DELETE_INSTANCES=true SSH_USER=ubuntu CLOUD_INIT_FILE=~/k8s-test-infra/jobs/e2e_node/containerd/containerd-main/ubuntu-init.yaml
go version go1.20.1 linux/amd64
+++ [0227 23:08:48] Building go targets for linux/amd64
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
go version go1.20.1 linux/amd64
Creating artifacts directory at /tmp/_artifacts/230227T230850
Test artifacts will be written to /tmp/_artifacts/230227T230850
Running tests remotely using
Account: 760591208458
Region: eu-west-2
Images: ami-02a6a91c1d29fc428
Ginkgo Flags: -timeout=24h -nodes=8  -skip="\[Flaky\]|\[Slow\]|\[Serial\]"  -untilItFails=false 
Cloud Init File: /home/REDACTED/k8s-test-infra/jobs/e2e_node/containerd/containerd-main/ubuntu-init.yaml
Kubelet Config File: test/e2e_node/jenkins/default-kubelet-config.yaml
Initializing e2e tests using image ami-02a6a91c1d29fc428.
I0227 23:08:56.234860  224408 remote.go:72] Building archive...
I0227 23:08:56.235092  224408 build.go:43] Building k8s binaries...
+++ [0227 23:08:56] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubelet (non-static)
    k8s.io/kubernetes/test/e2e_node/e2e_node.test (test)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/cluster/gce/gci/mounter (non-static)
    k8s.io/kubernetes/test/e2e_node/plugins/gcp-credential-provider (non-static)
I0227 23:08:58.202629  224408 run_remote.go:954] successfully created aws instance i-0a6fb23c7dd54334a
I0227 23:09:43.669423  224408 run_remote.go:1035] detected cloud-init is being used, waiting for instance i-0a6fb23c7dd54334a to be ready.
I0227 23:09:43.867439  224408 run_remote.go:400] registering i-0a6fb23c7dd54334a/3.8.175.128 and ssh key /tmp/.ssh-key-2977924823
I0227 23:09:43.867510  224408 remote.go:106] Staging test binaries on "i-0a6fb23c7dd54334a"
```

Result

```
Summarizing 20 Failures:
  [FAIL] [sig-node] Sysctls [LinuxOnly] [NodeConformance] [It] should not launch unsafe, but not explicitly enabled sysctls on the node [MinimumKubeletVersion:1.21]
  test/e2e/common/node/sysctl.go:176
  [FAIL] [sig-node] Pods [It] should delete a collection of pods [Conformance]
  test/e2e/common/node/pods.go:877
  [FAIL] [sig-storage] Downward API volume [It] should set mode on item file [LinuxOnly] [NodeConformance] [Conformance]
  test/e2e/framework/pod/output/output.go:238
  [FAIL] [sig-node] Security Context When creating a pod with HostUsers [It] must create the user namespace if set to false [LinuxOnly] [Feature:UserNamespacesStatelessPodsSupport]
  test/e2e/common/node/security_context.go:106
  [FAIL] [sig-node] Security Context When creating a container with runAsNonRoot [It] should run with an image specified user ID
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-storage] EmptyDir volumes [It] should support (non-root,0777,default) [LinuxOnly] [NodeConformance] [Conformance]
  test/e2e/framework/pod/output/output.go:238
  [FAIL] [sig-node] Security Context When creating a container with runAsUser [It] should run the container with uid 65534 [LinuxOnly] [NodeConformance] [Conformance]
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-node] Security Context when creating containers with AllowPrivilegeEscalation [It] should allow privilege escalation when not explicitly set and uid != 0 [LinuxOnly] [NodeConformance]
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-node] Security Context when creating a pod in the host IPC namespace [It] should not show the shared memory ID in the non-hostIPC containers [NodeFeature:HostAccess]
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-storage] Projected downwardAPI [It] should provide podname as non-root with fsgroup and defaultMode [LinuxOnly] [NodeFeature:FSGroup]
  test/e2e/framework/pod/output/output.go:238
  [FAIL] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics [It] should report resource usage through the resource metrics api
  test/e2e_node/resource_metrics_test.go:111
  [FAIL] [sig-node] Security Context when creating containers with AllowPrivilegeEscalation [It] should allow privilege escalation when true [LinuxOnly] [NodeConformance]
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-node] Pods [It] should patch a pod status [Conformance]
  test/e2e/common/node/pods.go:1108
  [FAIL] [sig-node] Hostname of Pod [NodeConformance] [It] a pod configured to set FQDN as hostname will remain in Pending state generating FailedCreatePodSandBox events when the FQDN is longer than 64 bytes
  test/e2e_node/pod_hostnamefqdn_test.go:202
  [FAIL] [sig-node] Security Context when creating containers with AllowPrivilegeEscalation [It] should not allow privilege escalation when false [LinuxOnly] [NodeConformance] [Conformance]
  test/e2e/framework/pod/pod_client.go:238
  [FAIL] [sig-node] Summary API [NodeConformance] when querying /stats/summary [It] should report resource usage through the stats api
  test/e2e_node/summary_test.go:332
  [FAIL] [sig-node] Pods [It] should run through the lifecycle of Pods and PodStatus [Conformance]
  test/e2e/common/node/pods.go:959
  [FAIL] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
  test/e2e/framework/network/utils.go:876
  [FAIL] [sig-storage] Projected downwardAPI [It] should update annotations on modification [NodeConformance] [Conformance]
  test/e2e/framework/pod/pod_client.go:106
  [FAIL] [sig-node] ImageID [NodeFeature: ImageID] [It] should be set to the manifest digest (from RepoDigests) when available
  test/e2e_node/image_id_test.go:57

Ran 261 of 390 Specs in 1205.830 seconds
FAIL! -- 241 Passed | 20 Failed | 0 Pending | 129 Skipped
```

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

_No response_

### Kubernetes version

n/a

### Cloud provider

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by upodroid**
/cc @dims 

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It is "discouraged" to use n1 as they are based on older architectures and e2 machine type is cheaper with the better CPU options.

I also need a PR to test AWS Node e2e tests.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/116114

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster/gce/config-common.sh [hunk 1]
```diff
@@ -43,9 +40,6 @@ function get-master-size {
   if [[ "$(get-num-nodes)" -gt "500" ]]; then
     suggested_master_size=32
   fi
-  if [[ "$(get-num-nodes)" -gt "2000" ]]; then
```
Comment (upodroid) [inline cluster/gce/config-common.sh:46]: I'm assuming the control plane has been optimised after this change: https://github.com/kubernetes/kubernetes/pull/95947

**Comment by upodroid** [comment]
I'm doing the testing on @dims PR #118628  as we need some code changes. This PR can be merged now. The tests on GCE are passing.

**Comment by upodroid** [comment]
Can we squeeze this in before the code freeze? Thanks
