### PR TITLE
Write checkAPIGroupPreferredVersion Test - +16 Endpoint coverage

### LINKED ISSUE #92158: Write checkAPIGroupPreferredVersion Test +Promote - +16 Endpoint coverage
# Progress <code>[5/6]</code>

-   [X] APISnoop org-flow: [checkAPIGroupPreferredVersionTest.org](https://github.com/cncf/apisnoop/blob/master/tickets/k8s/checkAPIGroupPreferredVersionTest.org)
-   [x] Test approval issue: [[kubernetes/kubernetes#92158](https://github.com/kubernetes/kubernetes/issues/92158)]
-   [x] Test pr: kuberenetes/kubernetes [#92619](https://github.com/kubernetes/kubernetes/pull/92619) 
-   [x] Two weeks soak start date: [testgrid-link](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&include-filter-by-regex=should%20validate%20PreferredVersion%20for%20each%20APIGroup) 20 July 2020
-   [ ] Two weeks soak end date: 3 August 2020
-   [X] Test promotion pr: [kubernetes/kubernetes#93271](https://github.com/kubernetes/kubernetes/pull/93271)

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still an endpoint which is untested.

```sql-mode
SELECT
  operation_id,
  -- k8s_action,
  path,
  description
  -- kind
  -- FROM untested_stable_core_endpoints
  FROM untested_stable_endpoints
  where path not like '%volume%'
  -- and kind like ''
  and operation_id ilike '%APIGroup'
 ORDER BY operation_id
 LIMIT 25
       ;
```

```example
          operation_id           |                path                 |        description         
---------------------------------+-------------------------------------+----------------------------
 getApiregistrationAPIGroup      | /apis/apiregistration.k8s.io/       | get information of a group
 getAppsAPIGroup                 | /apis/apps/                         | get information of a group
 getAuthenticationAPIGroup       | /apis/authentication.k8s.io/        | get information of a group
 getAuthorizationAPIGroup        | /apis/authorization.k8s.io/         | get information of a group
 getAutoscalingAPIGroup          | /apis/autoscaling/                  | get information of a group
 getBatchAPIGroup                | /apis/batch/                        | get information of a group
 getCoordinationAPIGroup         | /apis/coordination.k8s.io/          | get information of a group
 getDiscoveryAPIGroup            | /apis/discovery.k8s.io/             | get information of a group
 getEventsAPIGroup               | /apis/events.k8s.io/                | get information of a group
 getExtensionsAPIGroup           | /apis/extensions/                   | get information of a group
 getFlowcontrolApiserverAPIGroup | /apis/flowcontrol.apiserver.k8s.io/ | get information of a group
 getNodeAPIGroup                 | /apis/node.k8s.io/                  | get information of a group
 getPolicyAPIGroup               | /apis/policy/                       | get information of a group
 getRbacAuthorizationAPIGroup    | /apis/rbac.authorization.k8s.io/    | get information of a group
 getSchedulingAPIGroup           | /apis/scheduling.k8s.io/            | get information of a group
 getSettingsAPIGroup             | /apis/settings.k8s.io/              | get information of a group
 getStorageAPIGroup              | /apis/storage.k8s.io/               | get information of a group
(17 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/kubernetes-api/)
-   [Kubernetes API: v1.18](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#)
-   [client-go](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/)

# The mock test

## Test outline

1.  Get a list of all group /apis

2.  Iterate through list

3.  Query each endpoint

4.  List the PreferredVersion for the endpoint

## Test the functionality in Go

```go
package main

import (
  "context"
  "flag"
  "fmt"
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  "k8s.io/client-go/kubernetes"
  "k8s.io/client-go/tools/clientcmd"
  "os"
)

func main() {
  // uses the current context in kubeconfig
  kubeconfig := flag.String("kubeconfig", fmt.Sprintf("%v/%v/%v", os.Getenv("HOME"), ".kube", "config"), "(optional) absolute path to the kubeconfig file")
  flag.Parse()
  config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
  if err != nil {
    fmt.Println(err)
    return
  }
  // make our work easier to find in the audit_event queries
  config.UserAgent = "live-test-writing"
  // creates the clientset
  ClientSet, _ := kubernetes.NewForConfig(config)

  // TEST BEGINS HERE
  fmt.Println("[status] begin")

  // get list of APIGroup endpoints
  list := &metav1.APIGroupList{}
  err = ClientSet.Discovery().RESTClient().Get().AbsPath("/apis/").Do(context.TODO()).Into(list)

  if err != nil {
    fmt.Println("Failed to find /apis/", err)
    os.Exit(1)
  }

  for _, group := range list.Groups {
    fmt.Println("Checking APIGroup:", group.Name)

    // hit APIGroup endpoint
    checkGroup := &metav1.APIGroup{}
    apiPath := "/apis/" + group.Name + "/"
    err = ClientSet.Discovery().RESTClient().Get().AbsPath(apiPath).Do(context.TODO()).Into(checkGroup)

    if err != nil {
      fmt.Printf("Fail to access: %s | Error: %v\n", apiPath, err)
      os.Exit(1)
    }

    // get PreferredVersion for endpoint
    fmt.Println("PreferredVersion:", checkGroup.PreferredVersion, "\n")
  }

  // TEST ENDS HERE
  fmt.Println("[status] complete")
}
```

```go
[status] begin
Checking APIGroup: apiregistration.k8s.io
PreferredVersion: {apiregistration.k8s.io/v1 v1} 

Checking APIGroup: extensions
PreferredVersion: {extensions/v1beta1 v1beta1} 

Checking APIGroup: apps
PreferredVersion: {apps/v1 v1} 

Checking APIGroup: events.k8s.io
PreferredVersion: {events.k8s.io/v1beta1 v1beta1} 

Checking APIGroup: authentication.k8s.io
PreferredVersion: {authentication.k8s.io/v1 v1} 

Checking APIGroup: authorization.k8s.io
PreferredVersion: {authorization.k8s.io/v1 v1} 

Checking APIGroup: autoscaling
PreferredVersion: {autoscaling/v1 v1} 

Checking APIGroup: batch
PreferredVersion: {batch/v1 v1} 

Checking APIGroup: certificates.k8s.io
PreferredVersion: {certificates.k8s.io/v1beta1 v1beta1} 

Checking APIGroup: networking.k8s.io
PreferredVersion: {networking.k8s.io/v1 v1} 

Checking APIGroup: policy
PreferredVersion: {policy/v1beta1 v1beta1} 

Checking APIGroup: rbac.authorization.k8s.io
PreferredVersion: {rbac.authorization.k8s.io/v1 v1} 

Checking APIGroup: storage.k8s.io
PreferredVersion: {storage.k8s.io/v1 v1} 

Checking APIGroup: admissionregistration.k8s.io
PreferredVersion: {admissionregistration.k8s.io/v1 v1} 

Checking APIGroup: apiextensions.k8s.io
PreferredVersion: {apiextensions.k8s.io/v1 v1} 

Checking APIGroup: scheduling.k8s.io
PreferredVersion: {scheduling.k8s.io/v1 v1} 

Checking APIGroup: coordination.k8s.io
PreferredVersion: {coordination.k8s.io/v1 v1} 

Checking APIGroup: auditregistration.k8s.io
PreferredVersion: {auditregistration.k8s.io/v1alpha1 v1alpha1} 

Checking APIGroup: node.k8s.io
PreferredVersion: {node.k8s.io/v1beta1 v1beta1} 

Checking APIGroup: discovery.k8s.io
PreferredVersion: {discovery.k8s.io/v1beta1 v1beta1} 

[status] complete
```

# Verifying increase in coverage with APISnoop

Discover useragents:

```sql-mode
select distinct useragent from audit_event where bucket='apisnoop' and useragent not like 'kube%' and useragent not like 'coredns%' and useragent not like 'kindnetd%' and useragent like 'live%';
```

```example
     useragent     
-------------------
 live-test-writing
(1 row)

```

List endpoints hit by the test:

```sql-mode
select * from endpoints_hit_by_new_test where useragent like 'live%';
```

```example
     useragent     |           operation_id           | hit_by_ete | hit_by_new_test 
-------------------+----------------------------------+------------+-----------------
 live-test-writing | getAdmissionregistrationAPIGroup | t          |               1
 live-test-writing | getApiextensionsAPIGroup         | t          |               1
 live-test-writing | getApiregistrationAPIGroup       | f          |               1
 live-test-writing | getAPIVersions                   | t          |               1
 live-test-writing | getAppsAPIGroup                  | f          |               1
 live-test-writing | getAuthenticationAPIGroup        | f          |               1
 live-test-writing | getAuthorizationAPIGroup         | f          |               1
 live-test-writing | getAutoscalingAPIGroup           | f          |               1
 live-test-writing | getBatchAPIGroup                 | f          |               1
 live-test-writing | getCertificatesAPIGroup          | t          |               1
 live-test-writing | getCoordinationAPIGroup          | f          |               1
 live-test-writing | getDiscoveryAPIGroup             | f          |               1
 live-test-writing | getEventsAPIGroup                | f          |               1
 live-test-writing | getExtensionsAPIGroup            | f          |               1
 live-test-writing | getNetworkingAPIGroup            | t          |               1
 live-test-writing | getNodeAPIGroup                  | f          |               1
 live-test-writing | getPolicyAPIGroup                | f          |               1
 live-test-writing | getRbacAuthorizationAPIGroup     | f          |               1
 live-test-writing | getSchedulingAPIGroup            | f          |               1
 live-test-writing | getStorageAPIGroup               | f          |               1
(20 rows)

```

Display endpoint coverage change:

```sql-mode
select * from projected_change_in_coverage;
```

```example
   category    | total_endpoints | old_coverage | new_coverage | change_in_number 
---------------+-----------------+--------------+--------------+------------------
 test_coverage |             458 |          206 |          222 |               16
(1 row)

```

# Final notes

If a test with these calls gets merged, ****test coverage will go up by 15 points****

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture
/area conformance

### PR DESCRIPTION
**Pull request by riaankleinhans**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
This PR adds a test to test the following untested endpoints:
getApiregistrationAPIGroup
getAppsAPIGroup
getAuthenticationAPIGroup
getAuthorizationAPIGroup
getAutoscalingAPIGroup
getBatchAPIGroup
getCoordinationAPIGroup
getDiscoveryAPIGroup
getEventsAPIGroup
getExtensionsAPIGroup
getNodeAPIGroup
getPolicyAPIGroup
getRbacAuthorizationAPIGroup
getSchedulingAPIGroup
getStorageAPIGroup

**Which issue(s) this PR fixes:**
Fixes #92158

**Special notes for your reviewer:**
Adds +16 endpoint test coverage (good for conformance)

**Does this PR introduce a user-facing change?:**
```
NONE

```

**Release note:**
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```
NONE

```

/sig testing
/sig architecture
/area conformance

### CODE REVIEW

**Comment by heyste** [comment]
@oomichi Based on the your comment [here](https://github.com/kubernetes/kubernetes/pull/92532#discussion_r448068921), any suggestions on renaming `get_apigroup_list.go` too? Thanks

File: test/e2e/apimachinery/get_apigroup_list.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
+/*
+Copyright 2019 The Kubernetes Authors.
```
Comment (oomichi) [inline test/e2e/apimachinery/get_apigroup_list.go:2]: nit: s/2019/2020/

**Review by oomichi — COMMENTED** [review]
> @oomichi Based on the your comment here, any suggestions on renaming get_apigroup_list.go too? Thanks

Thanks for taking care of that.
It is nice to rename this file also as you said.

File: test/e2e/apimachinery/get_apigroup_list.go (hunk 1 above)
Comment (heyste) [reply test/e2e/apimachinery/get_apigroup_list.go]: Fixed. Renamed file to `apigroup_list.go`

File: test/e2e/apimachinery/apigroup_list.go [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+
+	"github.com/onsi/ginkgo"
+)
+
+var _ = SIGDescribe("apigroup list", func() {
+	f := framework.NewDefaultFramework("apigroup-list")
+	ginkgo.It("should locate PreferredVersion for each APIGroup", func() {
+
+		// TEST BEGINS HERE
+		ginkgo.By("[status] begin")
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_list.go:32]: I don't think it is worth to put this begining message here because the above test name will be output just before this.

File: test/e2e/apimachinery/apigroup_list.go [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+
+		framework.ExpectNoError(err, "Failed to find /apis/")
+
+		for _, group := range list.Groups {
+			framework.Logf("Checking APIGroup: %v", group.Name)
+
+			// hit APIGroup endpoint
+			checkGroup := &metav1.APIGroup{}
+			apiPath := "/apis/" + group.Name + "/"
+			err = f.ClientSet.Discovery().RESTClient().Get().AbsPath(apiPath).Do(context.TODO()).Into(checkGroup)
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_list.go:46]: I have one question about this testing way.
This test just checks the API endpoint is available without checking actual API behaviors like what API response(resource detail) can be gotten on each API.
Why don't we add actual API behavior instead of just touching API by checking return non-error?

File: test/e2e/apimachinery/apigroup_list.go (hunk 2 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_list.go:32]: Agree. Will remove it.

File: test/e2e/apimachinery/apigroup_list.go (hunk 3 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_list.go:46]: The idea for this test was to check that all endpoints have a `PreferredVersion` set which is checked with `framework.Logf("PreferredVersion: %v", checkGroup.PreferredVersion)`. The contents of `PreferredVersion` isn't checked though.

An idea would be to check that `PreferredVersion` matches an available `versions`, which would then confirm the behavior for this setting.

File: test/e2e/apimachinery/apigroup_list.go (hunk 2 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_list.go]: Removed

**Comment by heyste** [comment]
@oomichi The test description/naming has been updated to clarify the goal of the test. It now requires a valid `PreferredVersion` to be found for each apigroup. 

Is there anything to address before getting a /lgtm?

File: test/e2e/apimachinery/apigroup_preferred_version.go [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+)
+
+var _ = SIGDescribe("apigroup preferred version", func() {
+	f := framework.NewDefaultFramework("apigroup-preferred-version")
+	ginkgo.It("should validate PreferredVersion for each APIGroup", func() {
+
+		// get list of APIGroup endpoints
+		list := &metav1.APIGroupList{}
+		err := f.ClientSet.Discovery().RESTClient().Get().AbsPath("/apis/").Do(context.TODO()).Into(list)
+
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_preferred_version.go:34]: nit: unnecessary blank line for error handling.

File: test/e2e/apimachinery/apigroup_preferred_version.go [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+		framework.ExpectNoError(err, "Failed to find /apis/")
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_preferred_version.go:35]: Why don't we check `list.Groups` is not empty? 
If empty, the following test code can be passed without checking anything at current PR.

File: test/e2e/apimachinery/apigroup_preferred_version.go [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+
+		for _, group := range list.Groups {
+			framework.Logf("Checking APIGroup: %v", group.Name)
+
+			// locate APIGroup endpoint
+			checkGroup := &metav1.APIGroup{}
+			apiPath := "/apis/" + group.Name + "/"
+			err = f.ClientSet.Discovery().RESTClient().Get().AbsPath(apiPath).Do(context.TODO()).Into(checkGroup)
+			framework.ExpectNoError(err, "Fail to access: %s", apiPath)
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_preferred_version.go:44]: It is necessary to check `checkGroup.Versions` is not empty here.

File: test/e2e/apimachinery/apigroup_preferred_version.go [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+
+			framework.Logf("PreferredVersion.GroupVersion: %s", checkGroup.PreferredVersion.GroupVersion)
+			framework.Logf("Versions found %v", checkGroup.Versions)
+
+			// confirm that the PreferredVersion is a valid version
+			match := false
+			for _, version := range checkGroup.Versions {
+				if version.GroupVersion == checkGroup.PreferredVersion.GroupVersion {
```
Comment (oomichi) [inline test/e2e/apimachinery/apigroup_preferred_version.go:52]: Just question: Why don't this code fail if `version.GroupVersion != checkGroup.PreferredVersion.GroupVersion` ?

File: test/e2e/apimachinery/apigroup_preferred_version.go (hunk 4 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_preferred_version.go]: Fixed.

File: test/e2e/apimachinery/apigroup_preferred_version.go (hunk 5 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_preferred_version.go:34]: Nice catch. Fixed.

File: test/e2e/apimachinery/apigroup_preferred_version.go (hunk 6 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_preferred_version.go:44]: Added `framework.ExpectNotEqual(len(checkGroup.Versions), 0, "No version found for %v", group.Name)`

File: test/e2e/apimachinery/apigroup_preferred_version.go (hunk 7 above)
Comment (heyste) [reply test/e2e/apimachinery/apigroup_preferred_version.go:52]: Switching Line 52 for `version.GroupVersion != checkGroup.PreferredVersion.GroupVersion` when tested locally does fail.

I was using the `match = true` to break out of the loop as the `PreferredVersion` has found a matching pair. If not, then it will be still false when `framework.ExpectEqual(true, match, "failed to find a valid version for PreferredVersion")` is processed.

**Comment by oomichi** [comment]
Thanks for updating

/lgtm

**Comment by Riaankl** [comment]
/assign @derekwaynecarr  @caesarxuchao 
Can you please review

**Comment by Riaankl** [comment]
/assign @derekwaynecarr 
Can you please review

**Comment by Riaankl** [comment]
/assign @caesarxuchao 
Can you please review

**Comment by Riaankl** [comment]
@spiffxp can you please add /milestone v1.19 for this PR

**Comment by Riaankl** [comment]
@spiffxp can you please add /milestone v1.19 for this PR

**Comment by fedebongio** [comment]
/cc @roycaihw @Jefftree 
(maybe you guys can take a look?)

**Comment by caesarxuchao** [comment]
Hi @Riaankl,  thanks for adding the test! However I'm not sure if we need the test as an e2e test, which is expensive to run.

The test seems to verify two things:
1. the discovery endpoints work,
2. the preferredVersion is one of the versions listed in the discovery document.

For 1, this is already indirectly verified by other e2e tests, as many functions rely on the discovery endpoints.

For 2, since for built-in types, the PreferredVersion and Versions are setup in the same [function](https://github.com/kubernetes/kubernetes/blob/1f4da99f696efa30246e02221e3f85b92b7a8a5e/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L495-L496), how about verifying this by a unit test instead? We can similarly adds a unit test for CRD.

**Comment by hh** [comment]
[GA/stable APIs must have conformance tests](https://github.com/kubernetes/community/pull/1806) which end up being e2e test with the [Conformance] tag. 

Any endpoints lacking e2e conformance tests are part of the technical debt we are working to reduce.

While they may currently be indirectly verified, our metric for considering endpoints hit/tested is for the gingko framework itself to directly test (be part of the UserAgent).

According to our exploration in ticket #92158, which uses APISnoop to analyze e2e audit logs to match tests to endpoints:

Only the four most recently added apis appear to have existing e2e test hitting their relevant discovery endpoints.

The remaining sixteen have no detectable e2e test currently exercising them.

https://apisnoop.cncf.io/1.19.0/stable/core

List endpoints hit by this test vs existing e2e:

```
select * from endpoints_hit_by_new_test where useragent like 'live%';
     useragent     |           operation_id           | hit_by_e2e | hit_by_new_test 
-------------------+----------------------------------+------------+-----------------
 live-test-writing | getAdmissionregistrationAPIGroup | t          |               1
 live-test-writing | getApiextensionsAPIGroup         | t          |               1
 live-test-writing | getApiregistrationAPIGroup       | f          |               1
 live-test-writing | getAPIVersions                   | t          |               1
 live-test-writing | getAppsAPIGroup                  | f          |               1
 live-test-writing | getAuthenticationAPIGroup        | f          |               1
 live-test-writing | getAuthorizationAPIGroup         | f          |               1
 live-test-writing | getAutoscalingAPIGroup           | f          |               1
 live-test-writing | getBatchAPIGroup                 | f          |               1
 live-test-writing | getCertificatesAPIGroup          | t          |               1
 live-test-writing | getCoordinationAPIGroup          | f          |               1
 live-test-writing | getDiscoveryAPIGroup             | f          |               1
 live-test-writing | getEventsAPIGroup                | f          |               1
 live-test-writing | getExtensionsAPIGroup            | f          |               1
 live-test-writing | getNetworkingAPIGroup            | t          |               1
 live-test-writing | getNodeAPIGroup                  | f          |               1
 live-test-writing | getPolicyAPIGroup                | f          |               1
 live-test-writing | getRbacAuthorizationAPIGroup     | f          |               1
 live-test-writing | getSchedulingAPIGroup            | f          |               1
 live-test-writing | getStorageAPIGroup               | f          |               1
(20 rows)
```

**Comment by caesarxuchao** [comment]
Thanks @hh for the extra info. 

I think it's a good idea to e2e test that discovery endpoints are working in general. But I think that test should live in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/discovery.go.

I'm still not sure why we test the `preferredVersion` field specifically. I still think that can be better tested in a unit test. Maybe I miss the big picture. Are we planning to write individual test for every field in the discovery document?

**Comment by hh** [comment]
@heyste thanks for moving the test where @caesarxuchao suggested.

> I'm still not sure why we test the preferredVersion field specifically.

The idea is ensure `get*APIGroup` returns something usable by API consumers. Since the call returns a list of available APIs, it's most likely consumers will want to use the `preferredVersion`. We want to ensure that it is available.

> I still think that can be better tested in a unit test.

The purpose of the conformance tests is to ensure the behaviour we export as `GA` can be e2e tested against consumer deployments like k3s, EKS, GCS. This requirement keeps us from being able to promote unit tests as a requirement for all Certified K8s Conformant clusters.

> Maybe I miss the big picture. Are we planning to write individual test for every field in the discovery document?

Not all fields of the discovery document, but definiately all endpoints.

Most of this technical endpoint testing debt likely came prior to 1.9.

See https://apisnoop.cncf.io/conformance-progress#coverage-by-release

If we get this test merged and promoted within 1.19, we will hope to get closer to 50% GA conformance coverage.

https://apisnoop.cncf.io/1.19.0/stable

If you feel the *preferredVersion* should be verifiably available to consumers within the *get%APIGroup* calls, it would be great to get that `/approve` and `/lgtm`.

Thanks again for you :eyes:!

**Comment by oomichi** [comment]
Thanks for updating this PR for better place.
I'd like to leave lgtm label to wait for @caesarxuchao's confirmation.

/approve

**Comment by Riaankl** [comment]
Thank you @oomichi  for the /approve
@caesarxuchao thank you for your feedback.
The test freeze is 6 Aug 2020 and test must run flake free for two weeks before it can merge.
Looking forward to the /LGTM

**Comment by hh** [comment]
That puts our `/lgtm` and merge date for 1.19 at 23rd of July at the latest.

**Comment by caesarxuchao** [comment]
Thanks for the explanation @hh! I see why we need it as an e2e test now. And @heyste thanks for moving the test.

/lgtm

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92619/pull-kubernetes-node-e2e/1283873018757517312 flake was #93210

**Comment by liggitt** [comment]
This test is flaking, see https://github.com/kubernetes/kubernetes/issues/93215

**Comment by liggitt** [comment]
workaround opened at https://github.com/kubernetes/kubernetes/pull/93216
