### PR TITLE
cleanup: fix missed HandleError replacement with contextual logging

### LINKED ISSUE #91633: Do contextual logging for scheduler
The kube-scheduler is currently difficult to debug through logs. Logging is inconsistent and sparse, and critically helpful information is in some spots logged at too high of a level to be practically accessible (such as [node scores](https://github.com/kubernetes/kubernetes/blob/b618411f1edb98afe807866fb3a607356d72ba24/pkg/scheduler/core/generic_scheduler.go#L703), which are `V(10)`. At this level logs are flooded with low-level information too quickly to even grep).

**What would you like to be added**:
Standardize scheduler logging to useful, documented levels to improve debuggability and diagnoses of scheduling anomalies. This information should be accessible at reasonable levels so as not to be flooded by irrelevant low-level process and network logs (ie, `v=2,3,4..`) and consistent across the scheduler.

Specifically, information that is necessary includes, but is not limited to:
* Filter plugins
  * Per plugin/per node
* Preemption attempts (/postfilter plugins)
* Score plugins
  * Normalized results
    * Per plugin/per node
* Nominated node result
(sub-lists to indicate potential logging hierarchies. these are just some examples)

In addition, these logs should be able to be easily traced through a scheduling cycle. That is, all logs related to a specific scheduling cycle should have a unique identifier so that relevant information can be efficiently gathered with common search tools like grep.

**Why is this needed**:
The most common issues with the scheduler are questions related to the scheduling cycle ("Why did/didn't my pod get scheduled here/there?"). While the scheduler does currently report `FailedScheduling` events, these can lack information (https://github.com/kubernetes/kubernetes/issues/91340, https://github.com/kubernetes/kubernetes/issues/91601) and do not provide any insight to successful scheduling that does not land on the expected node (eg, scoring interference).

There is demand to be able to easily debug the steps of the scheduling cycle, and the lack of that ability frequently confuses users. It would be very helpful to be able to say, "If you set `v=2`, you'll be able to see each plugin's results" for example.

/sig scheduling

### PR DESCRIPTION
**Pull request by togettoyou**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR addresses a missed spot in [#116849](https://github.com/kubernetes/kubernetes/pull/116849), completing the replacement of `utilruntime.HandleError` with `HandleErrorWithContext` or `HandleErrorWithLogger` in places where contextual logging is available.

#### Which issue(s) this PR fixes:

Fixes #91633

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hashim21223445 — APPROVED** [review]

**Comment by macsko** [comment]
Please update the other `utilruntime.HandleError` usages in the pkg/scheduler as well.

@sanposhiho I see we have some inconsistencies in the code, i.e. some places call `utilruntime.HandleError` and some just log the error through `logger.Error`.

**Comment by sanposhiho** [comment]
As documented, `HandleErrorWithXXX` is for the code that cannot return errors and needs to ignore errors.

So, for our cases, for example, when plugins are returning errors, they don't have to use `HandleErrorWithXXX` because the errors are not ignored (it'll be propagated and handled at backoffQ). But, for places like this PR changed, we just ignore errors, so we should use `HandleErrorWithXXX`.
We can check `logger.Error` and change them to `HandleErrorWithXXX` appropriately, based on this criterion.

**Comment by macsko** [comment]
> We can check `logger.Error` and change them to `HandleErrorWithXXX` appropriately, based on this criterion.

Yes, I think we should migrate to a consistent way of logging, i.e. use `HandleError` where it suits. This could be done in another PR.

**Comment by togettoyou** [comment]
Does this mean that all `logger.Error` calls inside the `ResourceEventHandlerFuncs` in [pkg/scheduler/eventhandlers.go](https://github.com/kubernetes/kubernetes/blob/5a450884b127f7b8e477d48cf3967a2a5eca9126/pkg/scheduler/eventhandlers.go) should be replaced with `HandleErrorWithXXX`?

For example:
[https://github.com/kubernetes/kubernetes/blob/5a450884b127f7b8e477d48cf3967a2a5eca9126/pkg/scheduler/eventhandlers.go#L52-L66](https://github.com/kubernetes/kubernetes/blob/5a450884b127f7b8e477d48cf3967a2a5eca9126/pkg/scheduler/eventhandlers.go#L52-L66)

**Comment by macsko** [comment]
> Does this mean that all `logger.Error` calls inside the `ResourceEventHandlerFuncs` in [pkg/scheduler/eventhandlers.go](https://github.com/kubernetes/kubernetes/blob/5a450884b127f7b8e477d48cf3967a2a5eca9126/pkg/scheduler/eventhandlers.go) should be replaced with `HandleErrorWithXXX`?

Looks like the answer should be yes. @sanposhiho WDYT?

**Comment by sanposhiho** [comment]
Yes, sounds right

**Comment by togettoyou** [comment]
> Yes, sounds right

OK, I’ll check all the relevant parts later and evaluate whether a separate PR is needed to handle it consistently.

**Comment by togettoyou** [comment]
Hi @macsko @sanposhiho , Would you mind taking a look at this [PR](https://github.com/kubernetes/kubernetes/pull/132717) ?

Thanks!

**Comment by togettoyou** [comment]
/cc @macsko
/cc @sanposhiho

thanks.

**Comment by togettoyou** [comment]
It should all be replaced now.

**Comment by togettoyou** [comment]
@macsko It still needs an `lgtm` label.

**Comment by macsko** [comment]
Let's defer it to @sanposhiho

**Comment by togettoyou** [comment]
Friendly ping @sanposhiho — do you think there's anything else that needs to be addressed?

File: pkg/scheduler/eventhandlers.go [hunk 1]
```diff
@@ -188,11 +187,11 @@ func (sched *Scheduler) deletePodFromSchedulingQueue(obj interface{}) {
 		var ok bool
 		pod, ok = t.Obj.(*v1.Pod)
 		if !ok {
-			utilruntime.HandleError(fmt.Errorf("unable to convert object %T to *v1.Pod in %T", obj, sched))
+			utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t.Obj)
 			return
 		}
 	default:
-		utilruntime.HandleError(fmt.Errorf("unable to handle object in %T: %T", sched, obj))
+		utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t)
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go]: mistake? the error message is changed

File: pkg/scheduler/eventhandlers.go [hunk 2]
```diff
@@ -390,10 +391,10 @@ func addAllEventHandlers(
 						// it's assigned or not. Attempting to cleanup anyways.
 						return true
 					}
-					utilruntime.HandleError(fmt.Errorf("unable to convert object %T to *v1.Pod in %T", obj, sched))
+					utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t.Obj)
 					return false
 				default:
-					utilruntime.HandleError(fmt.Errorf("unable to handle object in %T: %T", sched, obj))
+					utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t)
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go]: same

File: pkg/scheduler/eventhandlers.go [hunk 3]
```diff
@@ -421,10 +422,10 @@ func addAllEventHandlers(
 						// it's assigned or not.
 						return responsibleForPod(pod, sched.Profiles)
 					}
-					utilruntime.HandleError(fmt.Errorf("unable to convert object %T to *v1.Pod in %T", obj, sched))
+					utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t.Obj)
 					return false
 				default:
-					utilruntime.HandleError(fmt.Errorf("unable to handle object in %T: %T", sched, obj))
+					utilruntime.HandleErrorWithLogger(logger, nil, "Cannot convert to *v1.Pod", "obj", t)
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go]: same

File: pkg/scheduler/eventhandlers.go (hunk 1 above)
Comment (togettoyou) [reply pkg/scheduler/eventhandlers.go]: Because I based it on this:

https://github.com/kubernetes/kubernetes/blob/729cf120026bcd40eb5fd8884335f22f97fe1a81/pkg/scheduler/eventhandlers.go#L308-L327

Comment (togettoyou) [reply pkg/scheduler/eventhandlers.go]: Perhaps it would be better to maintain consistency?

Comment (sanposhiho) [reply pkg/scheduler/eventhandlers.go]: "Cannot convert to ***v1.Pod**" is not quite right because here we try to convert to Pod or cache.DeletedFinalStateUnknown, and fail. So, I prefer the previous message. I think you can fix `deletePodFromCache`'s error message in `default`

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve
