### PR TITLE
Fix create secret docker-registry compatibility

### LINKED ISSUE #571: kubectl create secret docker-registry omits auth key in dockerconfigjson
**BUG REPORT**

**Kubernetes version** (use `kubectl version`): 1.13.x

**Environment**:
- **OS**: kubectl on MacOS/hyperkube container

**What happened**:

I try to create a docker pull secret like: 
```
kubectl create secret docker-registry test --docker-server=registry.example.com  --docker-username=username --docker-password=password --docker-email=test@example.com --dry-run -oyaml
```
This creates an object like:
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJVc2VybmFtZSI6InVzZXJuYW1lIiwiUGFzc3dvcmQiOiJwYXNzd29yZCIsIkVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: test
type: kubernetes.io/dockerconfigjson
```
And the base64-decoded string looks like this:
```
# echo 'eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJVc2VybmFtZSI6InVzZXJuYW1lIiwiUGFzc3dvcmQiOiJwYXNzd29yZCIsIkVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9fX0=' |base64 -D
{"auths":{"registry.example.com":{"Username":"username","Password":"password","Email":"test@example.com"}}}
```
Mind the missing auth key.

**What you expected to happen**:
When I run the same command with the kubelet 1.12.0 everything works as expected:
```
kubectl create secret docker-registry test --docker-server=registry.example.com  --docker-username=username --docker-password=password --docker-email=test@example.com --dry-run -oyaml
```
This creates an object like:
```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: test
type: kubernetes.io/dockerconfigjson
```
And the base64-decoded string looks like this:
```
# echo 'eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwicGFzc3dvcmQiOiJwYXNzd29yZCIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImF1dGgiOiJkWE5sY201aGJXVTZjR0Z6YzNkdmNtUT0ifX19' |base64 -D
{"auths":{"registry.example.com":{"username":"username","password":"password","email":"test@example.com","auth":"dXNlcm5hbWU6cGFzc3dvcmQ="}}}
```
This one creates the auth key.

**How to reproduce it** (as minimally and precisely as possible):
Run the command above with kubectl v1.12.x and 1.13.x 

**Anything else we need to know**:
I can reproduce it on my Mac and in the hyperkube docker container.
I ran it against an 1.11.5 cluster, ~~but try to test agains an newer cluster soon.~~
Same result against a 1.13.1 cluster.

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes the secrets produced by `kubectl create secret docker-registry` to restore auth segment and produce the correct case.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubectl/issues/571

**Special notes for your reviewer**:

https://github.com/kubernetes/kubernetes/pull/68441 didn't preserve the json marshaling behavior of the original struct

**Does this PR introduce a user-facing change?**:

```release-note
Fixes `kubectl create secret docker-registry` compatibility
```

/assign @smarterclayton 
/sig cli

### CODE REVIEW

File: pkg/kubectl/generate/versioned/secret_for_docker_registry_test.go [hunk 1]
```diff
@@ -73,7 +73,7 @@ func TestSecretForDockerRegistryGenerate(t *testing.T) {
 			},
 			expected: &v1.Secret{
 				ObjectMeta: metav1.ObjectMeta{
-					Name: "foo-7566tc6mgc",
+					Name: "foo-548cm7fgdh",
```
Comment (liggitt) [inline pkg/kubectl/generate/versioned/secret_for_docker_registry_test.go]: the original PR [changed this](https://github.com/kubernetes/kubernetes/pull/68441/files#diff-9afb1c73ad1f8cedbf9b93c7c1942397R76), this is reverting to the original value

**Comment by dims** [comment]
LGTM 👍

**Comment by smarterclayton** [comment]
Just spectacular.  I’ll add a test that verifies the actual content later.

**Comment by liggitt** [comment]
> I’ll add a test that verifies the actual content later.

I added a stop-gap one to the test-cmd invocation
