### PR TITLE
Stop container before remove for Docker

### LINKED ISSUE #94584: kubeadm reset with docker, containers are killed instead of exiting normally.
**What happened**:
Run `kubeadm reset` on a work node of kubernetes. Containers are killed, instead of exiting normally. Some resources are not released such as vips created by keepalived.

**What you expected to happen**:
The container exits properly so that system resources are released correctly 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

kubernetes/cmd/kubeadm/app/util/runtime/runtime.go, line 139:

```golang
// RemoveContainers removes running containers
func (runtime *DockerRuntime) RemoveContainers(containers []string) error {
	errs := []error{}
	for _, container := range containers {
		out, err := runtime.exec.Command("docker", "rm", "--force", "--volumes", container).CombinedOutput()
		if err != nil {
			// don't stop on errors, try to remove as many containers as possible
			errs = append(errs, errors.Wrapf(err, "failed to remove running container %s: output: %s, error", container, string(out)))
		}
	}
	return errorsutil.NewAggregate(errs)
}
```

Can I try to stop containers before removing them?

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS 7.4.1708
- Kernel (e.g. `uname -a`): 3.10.0-1127.18.2.el7.x86_64
- Install tools: kubeadm

### PR DESCRIPTION
**Pull request by BedivereZero**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Stop containers before remove them when using docker as runtime. Containers that are running when kubeadm reset are properly exited, preventing resources used by the container from being freed, because `docker rm --force` stops containers by SIGKILL.

**Which issue(s) this PR fixes**:

Fixes #94584

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: for Docker as the container runtime, make the "kubeadm reset" command stop containers before removing them
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BedivereZero** [comment]
Comment after sign CLA

**Comment by BedivereZero** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Signed CLA

**Comment by BedivereZero** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Comment after sign CLA

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 1]
```diff
@@ -140,10 +140,15 @@ func (runtime *CRIRuntime) RemoveContainers(containers []string) error {
...
 	errs := []error{}
 	for _, container := range containers {
-		out, err := runtime.exec.Command("docker", "rm", "--force", "--volumes", container).CombinedOutput()
+		out, err := runtime.exec.Command("docker", "stop", container).CombinedOutput()
 		if err != nil {
 			// don't stop on errors, try to remove as many containers as possible
-			errs = append(errs, errors.Wrapf(err, "failed to remove running container %s: output: %s, error", container, string(out)))
+			errs = append(errs, errors.Wrapf(err, "failed to stop running container %s: output: %s, error", container, string(out)))
+		} else {
+			out, err = runtime.exec.Command("docker", "rm", "--volumes", container).CombinedOutput()
```
Comment (neolit123) [inline cmd/kubeadm/app/util/runtime/runtime.go:148]: the question here is, should we remove a container even if stop failed?

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 2]
```diff
@@ -140,10 +140,15 @@ func (runtime *CRIRuntime) RemoveContainers(containers []string) error {
 func (runtime *DockerRuntime) RemoveContainers(containers []string) error {
 	errs := []error{}
 	for _, container := range containers {
-		out, err := runtime.exec.Command("docker", "rm", "--force", "--volumes", container).CombinedOutput()
+		out, err := runtime.exec.Command("docker", "stop", container).CombinedOutput()
```
Comment (neolit123) [inline cmd/kubeadm/app/util/runtime/runtime.go:143]: AFAIK this can block for 10 seconds for a container (default -t)
does that mean that if a lot of containers are running the overall process will take a lot of time?

do we need additional output messages indicating what is going on here?

**Review by neolit123 — COMMENTED** [review]
thanks for the PR.
this change probably needs some discussion.

/cc @rosti @bart0sh 
/priority backlog

PTAL.

File: cmd/kubeadm/app/util/runtime/runtime.go (hunk 1 above)
Comment (BedivereZero) [reply cmd/kubeadm/app/util/runtime/runtime.go:148]: My point is that ContainerRuntime behaves in the same way. DockerRuntime should return error on container stopping failures just like CRIRuntime.

**Comment by yagonobre** [comment]
Maybe we can make the docker stop optional

**Comment by neolit123** [comment]
@yagonobre 

> Maybe we can make the docker stop optional

since we don't want more flags then i guess this has to be a separate phase.

**Comment by neolit123** [comment]
@BedivereZero i tested the change locally and it seems fine.
users that face long stop times during "kubeadm reset" can remove the containers manually.

one request, under "Does this PR introduce a user-facing change?" please use this text:
> kubeadm: for Docker as the container runtime, make the "kubeadm reset" command stop containers before removing them

/approve

**Review by neolit123 — COMMENTED** [review]
/lgtm
no objections by others, so applying LGTM.
