### PR TITLE
Fix controller setup in storage version unit testcases

### LINKED ISSUE #131745: Failure cluster [56b62216...] Test_StorageVersionUpdatedWithAllEncodingVersionsEqualOnLeaseDeletion
##### Error text:
```
Failed
=== RUN   Test_StorageVersionUpdatedWithAllEncodingVersionsEqualOnLeaseDeletion
    gc_controller_test.go:127: unexpected storage version object
    gc_controller_test.go:128: got: &StorageVersion{ObjectMeta:{k8s.test.resources      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:StorageVersionSpec{},Status:StorageVersionStatus{StorageVersions:[]ServerStorageVersion{ServerStorageVersion{APIServerID:kube-apiserver-1,EncodingVersion:v1,DecodableVersions:[v1],ServedVersions:[],},ServerStorageVersion{APIServerID:kube-apiserver-2,EncodingVersion:v2,DecodableVersions:[v2],ServedVersions:[],},ServerStorageVersion{APIServerID:kube-apiserver-3,EncodingVersion:v2,DecodableVersions:[v2],ServedVersions:[],},},CommonEncodingVersion:*v1,Conditions:[]StorageVersionCondition{},},}
    gc_controller_test.go:129: expected: [{APIServerID:kube-apiserver-2 EncodingVersion:v2 DecodableVersions:[v2] ServedVersions:[]} {APIServerID:kube-apiserver-3 EncodingVersion:v2 DecodableVersions:[v2] ServedVersions:[]}]
    gc_controller_test.go:133: unexpected common encoding version
    gc_controller_test.go:134: got: "v1"
    gc_controller_test.go:135: expected: "v2"
    gc_controller_test.go:139: expected 1 condition, got: 0
--- FAIL: Test_StorageVersionUpdatedWithAllEncodingVersionsEqualOnLeaseDeletion (2.01s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 137 [running]:
testing.tRu
```
#### Recent failures:
[5/11/2025, 5:11:18 AM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1921401449628045312)
[5/6/2025, 7:18:04 AM ci-kubernetes-unit-1-33](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-33/1919622457946279936)

/kind failing-test
/kind flake
/sig api-machinery

### PR DESCRIPTION
**Pull request by vikasbolla**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
This PR tries to fix the test flakes
There is an issue during the controller setup in the test file. Controller depends on the informer cache and in this case  I can see that the controller call is not controlled based on the informer cache sync, due to which, when the controller is called even before the informer execution, then the worker queue on which the controller is depended on will be empty and the reconciliation logic will timeout.

So added the cache check before calling the controller to make sure the informer cache is properly updated with latest objects state.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/131745

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/storageversiongc/gc_controller_test.go [hunk 1]
```diff
@@ -39,8 +41,12 @@ func setupController(ctx context.Context, clientset kubernetes.Interface) {
 	storageVersionInformer := informerFactory.Internal().V1alpha1().StorageVersions()
 
 	controller := NewStorageVersionGC(ctx, clientset, leaseInformer, storageVersionInformer)
+	informerFactory.Start(ctx.Done())
+	// Using this ensure informer caches are fully populated before starting the controller.
+	if !cache.WaitForCacheSync(ctx.Done(), controller.leasesSynced, controller.storageVersionSynced) {
```
Comment (Jefftree) [inline pkg/controller/storageversiongc/gc_controller_test.go:47]: Don't think this is strictly necessary. We wait for the sync in `controller.Run()` already. https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/storageversiongc/gc_controller.go#L103-L106

+1 to polling instead of checking condition once though.

File: pkg/controller/storageversiongc/gc_controller_test.go [hunk 2]
```diff
@@ -122,7 +120,29 @@ func Test_StorageVersionUpdatedWithAllEncodingVersionsEqualOnLeaseDeletion(t *te
 			DecodableVersions: []string{"v2"},
 		},
 	}
+	// Wait up to 5 seconds, checking every 100ms to ensure controller had a chance to reconcile
+	err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, 5*time.Second, true, func(ctx context.Context) (bool, error) {
```
Comment (Jefftree) [inline pkg/controller/storageversiongc/gc_controller_test.go:127]: imo it seems to make more sense to wrap the entire reflection check from L126-148 within the `wait.PollUntilContextTimeout`. Feels a bit weird that we're just checking the CommonEncodingVersion

File: pkg/controller/storageversiongc/gc_controller_test.go (hunk 1 above)
Comment (vikasbolla) [reply pkg/controller/storageversiongc/gc_controller_test.go:47]: Thanks @Jefftree, but controller.Run() is sometimes called even before the informer cache is synced with the object state as controller.Run() is a goroutine, so in that case I think the flakiness is observed

Comment (Jefftree) [reply pkg/controller/storageversiongc/gc_controller_test.go:47]: The PollWithContextTimeout addition should catch those flakes though? Overall I don't have a strong opinion so will defer to the approvers.

Comment (vikasbolla) [reply pkg/controller/storageversiongc/gc_controller_test.go:47]: actually I have tried only with polling and saw that it alone does not solve issue, when I future investigated got to know that since informer cache never get updates and controller never knows the lease deletion, reconciliation never happens and polling eventually time out

File: pkg/controller/storageversiongc/gc_controller_test.go (hunk 2 above)
Comment (vikasbolla) [reply pkg/controller/storageversiongc/gc_controller_test.go:127]: Thanks @Jefftree , made the changes, PTAL

**Comment by Jefftree** [comment]
/lgtm

Thanks!

File: pkg/controller/storageversiongc/gc_controller_test.go [hunk 3]
```diff
@@ -39,8 +42,12 @@ func setupController(ctx context.Context, clientset kubernetes.Interface) {
 	storageVersionInformer := informerFactory.Internal().V1alpha1().StorageVersions()
 
 	controller := NewStorageVersionGC(ctx, clientset, leaseInformer, storageVersionInformer)
+	informerFactory.Start(ctx.Done())
+	// Using this ensure informer caches are fully populated before starting the controller.
+	if !cache.WaitForCacheSync(ctx.Done(), controller.leasesSynced, controller.storageVersionSynced) {
+		panic("timed out waiting for caches to sync")
```
Comment (soltysh) [inline pkg/controller/storageversiongc/gc_controller_test.go:48]: Nit: it's fine to just `t.Fatalf` rather than `panic`.

**Review by soltysh — APPROVED** [review]
/approve

**Comment by soltysh** [comment]
I've tried this locally and couldn't reproduce for 15+ minutes, whereas previously would fail in less than 3m.

File: pkg/controller/storageversiongc/gc_controller_test.go (hunk 3 above)
Comment (vikasbolla) [reply pkg/controller/storageversiongc/gc_controller_test.go:48]: Thank you, noted
