### PR TITLE
kubeadm: remove nodefs.inodesFree test defaulting on non-Linux

### LINKED ISSUE #1398: fix broken initconfiguration unit tests on non-linux
this PR broke unit tests in cmd/kubeadm/app/util/config/initconfiguration_test.go on non Linux:
https://github.com/kubernetes/kubernetes/pull/67709/files

we need separate YAML files for non-linux that have the minor difference in kublet defaults.

/assign
cc @chuckha @feiskyer

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
Add test files that exclude the field in question
under KubeletConfiguration -> evictionHard for non-Linux.

Add runtime abstraction for the test files in initconfiguration_tests.go

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1398

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @chuckha @feiskyer 
/assign @fabriziopandini @rosti 
/kind bug
/priority important-soon

### CODE REVIEW

**Comment by neolit123** [comment]
/area kubeadm
/sig cluster-lifecycle

@chuckha 
could you please try this PR?

e.g:
```
wget https://github.com/kubernetes/kubernetes/pull/73945.diff
git apply 73945.diff
go test cmd/kubeadm/app/util/config/...
```

on windows i'm getting import path problems and i don't have a mac.

**Comment by yagonobre** [comment]
@neolit123 I tested on osx 10.14.3 and it's work
```
go test k8s.io/kubernetes/cmd/kubeadm/app/util/config/...
ok      k8s.io/kubernetes/cmd/kubeadm/app/util/config   9.625s
ok      k8s.io/kubernetes/cmd/kubeadm/app/util/config/strict    (cached)
```

**Comment by neolit123** [comment]
thanks @yagonobre !

File: cmd/kubeadm/app/util/config/initconfiguration_test.go [hunk 1]
```diff
@@ -126,6 +131,18 @@ func TestLoadInitConfigurationFromFile(t *testing.T) {
 }
 
 func TestInitConfigurationMarshallingFromFile(t *testing.T) {
+
```
Comment (feiskyer) [inline cmd/kubeadm/app/util/config/initconfiguration_test.go]: nit: remove empty line

**Review by feiskyer — COMMENTED** [review]
lgtm, thanks for the fix

File: cmd/kubeadm/app/util/config/initconfiguration_test.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go]: updated.

**Review by chuckha — APPROVED** [review]
/lgtm
