### PR TITLE
Don't create a new sandbox for pod with RestartPolicyOnFailure if all containers succeeded

### LINKED ISSUE #92613: kubelet always creates sandbox twice for Pods with RestartPolicyOnFailure
**What happened**:
For a Pod with `RestartPolicyOnFailure`, kubelet would attempt to create a new sandbox for it even after all container succeeded. Logs as below:
```
# Created the first sandbox and a container
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.521118   28625 kubelet.go:1907] SyncLoop (ADD, "api"): "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.549173   28625 kubelet.go:1920] SyncLoop (RECONCILE, "api"): "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847022   28625 kuberuntime_manager.go:478] Syncing Pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)": &Pod{ObjectMeta:{testpod  default /api/v1/namespaces/default/pods/testpod a724c60f-4f8e-4f16-acd3-d47ff56bd650 3841748 0 2020-06-29 10:11:09 -0700 PDT <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"testpod","namespace":"default"},"spec":{"containers":[{"args":["/bin/sh","-c","echo hello"],"image":"busybox","name":"test"}],"restartPolicy":"OnFailure"}}
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847281   28625 kuberuntime_manager.go:422] No sandbox for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" can be found. Need to start a new one
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847294   28625 kuberuntime_manager.go:650] computePodActions got {KillPod:true CreateSandbox:true SandboxID: Attempt:0 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[] EphemeralContainersToStart:[]} for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847336   28625 kuberuntime_manager.go:659] SyncPod received new pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", will create a sandbox for it
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847345   28625 kuberuntime_manager.go:666] Stopping PodSandbox for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", will start new one
Jun 29 10:11:16 k8s-02 kubelet[28625]: I0629 10:11:16.847370   28625 kuberuntime_manager.go:721] Creating sandbox for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:17 k8s-02 kubelet[28625]: I0629 10:11:17.061043   28625 kuberuntime_manager.go:735] Created PodSandbox "5b006c9a8056ddcfc702f2ccd279741c830bce525b1097ceb22d71dc9090098a" for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:17 k8s-02 kubelet[28625]: I0629 10:11:17.061425   28625 kuberuntime_manager.go:754] Determined the ip [172.30.1.150] for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" after sandbox changed
Jun 29 10:11:17 k8s-02 kubelet[28625]: I0629 10:11:17.061526   28625 kuberuntime_manager.go:791] Creating container &Container{Name:test,Image:busybox,Command:[],Args:[/bin/sh -c echo hello],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-24hfm,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} in pod testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)

# The container ran to completion and succeeded, stopping sandbox because all containers are done.
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164329   28625 kubelet.go:1952] SyncLoop (PLEG): "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", event: &pleg.PodLifecycleEvent{ID:"a724c60f-4f8e-4f16-acd3-d47ff56bd650", Type:"ContainerDied", Data:"84aba5078b5bfd61b95d01fb65bb98451317c159a8b23efa820eb9d1cc5b323a"}
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164367   28625 kubelet_pods.go:1355] Generating status for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164467   28625 helpers.go:91] Already successfully ran container "test" of pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", do nothing
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164555   28625 kubelet_pods.go:1355] Generating status for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164674   28625 helpers.go:91] Already successfully ran container "test" of pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", do nothing
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.164913   28625 kuberuntime_manager.go:478] Syncing Pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)": &Pod{ObjectMeta:{testpod  default /api/v1/namespaces/default/pods/testpod a724c60f-4f8e-4f16-acd3-d47ff56bd650 3841748 0 2020-06-29 10:11:09 -0700 PDT <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"testpod","namespace":"default"},"spec":{"containers":[{"args":["/bin/sh","-c","echo hello"],"image":"busybox","name":"test"}],"restartPolicy":"OnFailure"}}
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.165263   28625 helpers.go:91] Already successfully ran container "test" of pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", do nothing
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.165323   28625 kuberuntime_manager.go:650] computePodActions got {KillPod:true CreateSandbox:false SandboxID:5b006c9a8056ddcfc702f2ccd279741c830bce525b1097ceb22d71dc9090098a Attempt:0 NextInitContainerToStart:nil ContainersToStart:[] ContainersToKill:map[] EphemeralContainersToStart:[]} for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:19 k8s-02 kubelet[28625]: I0629 10:11:19.165393   28625 kuberuntime_manager.go:668] Stopping PodSandbox for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" because all other containers are dead.

# Received ContainerDied event of the sandbox, but it then created a new sandbox even there's no container to start 
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.166430   28625 kubelet.go:1952] SyncLoop (PLEG): "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", event: &pleg.PodLifecycleEvent{ID:"a724c60f-4f8e-4f16-acd3-d47ff56bd650", Type:"ContainerDied", Data:"5b006c9a8056ddcfc702f2ccd279741c830bce525b1097ceb22d71dc9090098a"}
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.166560   28625 kubelet.go:2016] Pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" has completed, ignoring remaining sync work: sync
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.166657   28625 kubelet_pods.go:1355] Generating status for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.166757   28625 helpers.go:91] Already successfully ran container "test" of pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", do nothing
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.166542   28625 kubelet_pods.go:1355] Generating status for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.167049   28625 helpers.go:91] Already successfully ran container "test" of pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", do nothing
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.167799   28625 kuberuntime_manager.go:440] No ready sandbox for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" can be found. Need to start a new one
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.167896   28625 kuberuntime_manager.go:650] computePodActions got {KillPod:true CreateSandbox:true SandboxID:5b006c9a8056ddcfc702f2ccd279741c830bce525b1097ceb22d71dc9090098a Attempt:1 NextInitContainerToStart:nil ContainersToStart:[] ContainersToKill:map[] EphemeralContainersToStart:[]} for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.168010   28625 kuberuntime_manager.go:666] Stopping PodSandbox for "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)", will start new one
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.231935   28625 kuberuntime_manager.go:721] Creating sandbox for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.539335   28625 kuberuntime_manager.go:735] Created PodSandbox "7b46fbe3c3db623f1e211eba6bf25ace2f53ac083900befdac6c3121bb569a19" for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)"
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.539683   28625 kuberuntime_manager.go:754] Determined the ip [172.30.1.151] for pod "testpod_default(a724c60f-4f8e-4f16-acd3-d47ff56bd650)" after sandbox changed
Jun 29 10:11:20 k8s-02 kubelet[28625]: I0629 10:11:20.843953   28625 kubelet_pods.go:1117] Killing unwanted pod "testpod"
```

This issue is similar to https://github.com/kubernetes/kubernetes/pull/68980 which fixed the case of pods whose RestartPolicy are Never.

It caused unnecessary CRI and CNI calls, confusing logs and conflicts between the routine that creates the new sandbox and the routine that kills the Pod.
It's likely also the root cause of https://github.com/kubernetes/kubernetes/issues/72044 because sometimes the routine that creates the second sandbox and the routine that kills unwanted pod run concurrently, then the netns would be gone when calling CNI.

**What you expected to happen**:
kubelet shouldn't create a new sandbox for pod with RestartPolicyOnFailure if all containers succeeded

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod like this:
```
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  restartPolicy: OnFailure
  containers:
  - name: test
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo hello
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The kubelet would attempt to create a new sandbox for a pod whose RestartPolicy is OnFailure even after all container succeeded. It caused unnecessary CRI and CNI calls, confusing logs and conflicts between the routine that creates the new sandbox and the routine that kills the Pod.

This patch checks the containers to start and stops creating sandbox if no container is supposed to start.

**Which issue(s) this PR fixes**:

Fixes #92613

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed kubelet creating extra sandbox for pods with RestartPolicyOnFailure after all containers succeeded
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
> Does this PR introduce a user-facing change?:

^ please add a release note that explains the change in the kubelet

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -499,19 +499,27 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
 			changes.CreateSandbox = false
 			return changes
 		}
+
+		// Get the containers to start, excluding the ones that succeeded if RestartPolicy is OnFailure.
+		// We should not create a sandbox for a Pod if there is no container to start.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:504]: nit: move this comment to the corresponding if statement: `if len(containersToStart) == 0 {`

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -499,19 +499,27 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
...
 		}
-		// Start all containers by default but exclude the ones that succeeded if
-		// RestartPolicy is OnFailure.
-		for idx, c := range pod.Spec.Containers {
-			if containerSucceeded(&c, podStatus) && pod.Spec.RestartPolicy == v1.RestartPolicyOnFailure {
-				continue
-			}
-			changes.ContainersToStart = append(changes.ContainersToStart, idx)
-		}
+		changes.ContainersToStart = containersToStart
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: another nit: wouldn't it be more logical to move the loop back here - after the `Init` containers check.

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: I think it's important to change ordering back to make sure that any changes related to containers start/stop are only applied after all Init container complete. Just to avoid potential issues in a future if more logic will be added

Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: `containersToStart` is also used to determine whether there's a need to create a sandbox. Wouldn't it cause repeated computation if moving the loop back here?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:504]: done

**Comment by tnqn** [comment]
> > Does this PR introduce a user-facing change?:
> 
> ^ please add a release note that explains the change in the kubelet

Done, thanks.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: From the logic here - if the `if len(pod.Spec.InitContainers) != 0 {` than we need to start an `Init` container. So this condition check should go before any container-related ones. I was imagining situation when  `len(pod.Spec.Containers)` is `0`, i.e. pod has no containers, but has Init containers. In this case if order of checks will be as it's written, Init containers wouldn't run. The situation when there are no containers in a pod seems to be impossible today, thus it's just a recommendation to swap these checks. In anticipation that one day more conditions may be added above which semantically needs to run after all Init containers logic complete.

Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: Thanks for the explanation. I understand the concern now, but swapping them back could cause sandbox still being recreated if any initContainer is present. The current workflow of a Pod with initContainer is and would be kept as below:
1. create sandbox, create init container, create container (expected actions)
2. all containers succeeded, delete sandbox (expected actions)
3. create sandbox, create init container (unexpected actions)

If taking potential no container case into consideration, could we add a condition to ensure this is not the first time to create sandbox like https://github.com/kubernetes/kubernetes/blob/e7ca64fbe16d0c4b6c7b36aecde9cd75042b2828/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L490

**Comment by tedyu** [comment]
Is it possible to add an e2e node test (under test/e2e_node) that covers the scenario ?

Thanks

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:522]: w.r.t. Sergey's comment, is it possible that a pod has:

some init containers (> 0)
no container
some Ephemeral Containers (> 0)

Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:525]: To ensure all initContainers can run once successfully regardless of there are containers to start, I added one more condition for not creating sandbox. It should address the potential case "init containers (> 0), no container".

For the case of Ephemeral Containers (> 0), I think it's not affected by this PR. It was never created along with (re-)creating sandbox, and was handled when `createPodSandbox` is false after initContainer or normal container became running. The behavior is kept as it is.

**Comment by tnqn** [comment]
> Is it possible to add an e2e node test (under test/e2e_node) that covers the scenario ?
> 
> Thanks

Thanks for the suggestion. I didn't find similar tests under `test/e2e_node` so not sure where it should be added, but I added a e2e test to `test/e2e/node/pods.go` which ensures there are no extra events like `SandboxChanged` for a Pod whose RestartPolicy is OnFailure and all containers succeeded, which is the issue this PR is fixing.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -499,19 +499,30 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
...
+				continue
+			}
+			containersToStart = append(containersToStart, idx)
+		}
+		// We should not create a sandbox for a Pod if initialization is done and there is no container to start.
+		if len(containersToStart) == 0 {
+			_, _, done := findNextInitContainerToRun(pod, podStatus)
+			if done {
+				changes.CreateSandbox = false
+				return changes
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:516]: perhaps this can be simplified. If you will remove the return statement from here and the new condition with the call to `findNextInitContainerToRun`, everything suppose to be working just fine. If there are Init containers, `changes` will be returned from the next if condition with the `changes.CreateSandbox = false` and `changes.NextInitContainerToStart` populated. It will save on additional call to `findNextInitContainerToRun ` and will minimize the new changes

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:525]: I made a comment above. Suggestion is to minimize the introduced changes.

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:525]: Also, maybe introducing a test with the situaiton @tedyu outlined will be beneficial. So future changes will take it into account.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 3 above)
Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:516]: In this branch `if createPodSandbox`, it's supposed to (re-)create sandbox because it doesn't exist or it's dead or a changed is detected, and we are only adding exceptions to stop that if all things are done, like the existing exception: `if !shouldRestartOnFailure(pod) && attempt != 0 && len(podStatus.ContainerStatuses) != 0`  for the case that a Pod whose RestartPolicy is Never and have created sandbox and containers before.
It's supposed to either return `CreateSandbox = false` or `CreateSandbox = true` with `NextInitContainerToStart` or `ContainersToStart`.
If the returned changes is `CreateSandbox = false` with `NextInitContainerToStart`, there would be no sandbox for the init container.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (tnqn) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:525]: There are already some tests to cover a Pod in `TestComputePodActionsWithInitAndEphemeralContainers` for example:
https://github.com/kubernetes/kubernetes/blob/e7ca64fbe16d0c4b6c7b36aecde9cd75042b2828/pkg/kubelet/kuberuntime/kuberuntime_manager_test.go#L1265
And I have added `Create a new pod sandbox if the pod sandbox is dead, init container failed and RestartPolicy == OnFailure` to it to ensure sandbox can be recreated as long as initialization is not done regardless of regular containers and ephemeral containers' status.
I didn't really delete regular containers from the pod spec of the tests, thinking it sounds strange to have a case with illegal input, but I think they should cover the situation @tedyu outlined implicitly

File: test/e2e/node/pods.go [hunk 4]
```diff
@@ -445,5 +447,124 @@ var _ = SIGDescribe("Pods Extended", func() {
...
+					return false, err
+				}
+				if len(eventList.Items) > 0 {
+					framework.Logf("Got events for the pod")
+					return true, nil
+				}
+				return false, nil
+			}))
+
+			// Ensure there are no extra events like SandboxChanged.
```
Comment (dashpole) [inline test/e2e/node/pods.go:524]: should we just check directly to make sure we don't get a sandboxchanged event?  The below seems fragile to any event changes related to pod lifecycle.

**Comment by dashpole** [comment]
/approve
/priority important-soon

I'll leave it to @SergeyKanzhelev to lgtm, once he is satisfied with it.

File: test/e2e/node/pods.go (hunk 4 above)
Comment (tnqn) [reply test/e2e/node/pods.go:524]: done, thanks!

**Comment by SergeyKanzhelev** [comment]
I don't have permissions to lgtm, for what it worth:

/lgtm

**Review by dims — APPROVED** [review]

**Comment by tnqn** [comment]
@SergeyKanzhelev @dashpole @dims could this PR get into 1.20 milestone?

**Comment by alex-vmw** [comment]
@tnqn @dims Would it be possible to also backport this into 1.18/1.19? Thanks.

**Comment by SergeyKanzhelev** [comment]
If you want 1.19.1 cutoff is Friday I think. So need to do it today

**Comment by SergeyKanzhelev** [comment]
failure doesn't seem to be related

/retest

**Comment by tnqn** [comment]
@alex-vmw @SergeyKanzhelev I just created #94725 to backport to 1.19, hope it can catch 1.19.2.

**Comment by alex-vmw** [comment]
@tnqn How about for 1.18.x? Any plans to backport there?

**Comment by cpanato** [comment]
@tnqn @SergeyKanzhelev this only need for 1.18 and 1.19, not for 1.17?

**Comment by tnqn** [comment]
> @tnqn @SergeyKanzhelev this only need for 1.18 and 1.19, not for 1.17?

@cpanato I just checked the issue can be reproduced on 1.17.12 as well, created https://github.com/kubernetes/kubernetes/pull/95508 for 1.17.
