### PR TITLE
API-initiated eviction: handle deleteOptions correctly

### LINKED ISSUE #116552: API-initiated eviction does not work on first try in certain scenarios, but does work on second try
### What happened?

Scenarios that require setting resourceVersion either

- explicitly to the eviction request
- or when the eviction API needs to make sure that the pod has not become ready when deleting unready pods https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L232

fails to evict a pod. This is caused by a conflict with PodDisruptionConditions feature, which adds a condition to a pod, and the delete itself fails. The second eviction works correctly and results in a pod deletion.

### What did you expect to happen?

eviction should succeed on a first try 

### How can we reproduce it (as minimally and precisely as possible)?

1. create a simple pod

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name:  nginx
      image: registry.k8s.io/nginx-slim:0.8
```

```
$ kubectl apply -f nginx.yaml
```

2. obtain its resource version

```
$ kubectl get pod nginx -oyaml | grep resourceVersion
> resourceVersion: "313"
```

3. try to evict it

```
$ kubectl create -f - <<EOF --raw /api/v1/namespaces/default/pods/nginx/eviction
{"apiVersion": "policy/v1", "kind": "Eviction", "metadata": {"name": "nginx"}, "deleteOptions": {"preconditions": {"resourceVersion": "313"}}}
EOF
$ Error from server (Conflict): Operation cannot be fulfilled on Pod "nginx": the ResourceVersion in the precondition (313) does not match the ResourceVersion in record (425). The object might have been modified
```

the eviction request fails, but we can see that the DisruptionTarget condition has been added to the pod

```
$ oc get pod nginx -oyaml | grep DisruptionTarget -B 5
>   - lastProbeTime: null
>    lastTransitionTime: "2023-03-13T21:29:04Z"
>    message: 'Eviction API: evicting'
>    reason: EvictionByEvictionAPI
>    status: "False"
>    type: DisruptionTarget
```

4. second eviction with updated resouce version succeeds

```
$ kubectl create -f - <<EOF --raw /api/v1/namespaces/default/pods/nginx/eviction
{"apiVersion": "policy/v1", "kind": "Eviction", "metadata": {"name": "nginx"}, "deleteOptions": {"preconditions": {"resourceVersion": "520"}}}
EOF
> {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","code":201}
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"archive", BuildDate:"2023-03-01T12:14:03Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.3.489+de9ce03f19e8b1", GitCommit:"de9ce03f19e8b1ace1e79fae17119820c4232b67", GitTreeState:"clean", BuildDate:"2023-03-13T21:11:26Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

when adding a DisruptionTarget condition into a pod that will be deleted by an eviction

- handle ResourceVersion and Preconditions correctly
- handle DryRun option correctly

#### Which issue(s) this PR fixes:

Fixes #116552

#### Special notes for your reviewer:

more details in the issue

#### Does this PR introduce a user-facing change?

```release-note
Fixed two regressions introduced by the PodDisruptionConditions feature (on by default in 1.26):
* pod eviction API calls returned spurious precondition errors and required a second evict API call to succeed
* dry-run eviction API calls persisted a DisruptionTarget condition into the pod being evicted
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/issues/3329
```

### CODE REVIEW

**Comment by atiratree** [comment]
cc @ravisantoshgudimetla

**Comment by liggitt** [comment]
> This is a regression since, it requires more eviction requests for the kubectl drain to drain a node. And it could affect other tools that do eviction.

what PR regressed this?

File: pkg/registry/core/pod/storage/eviction.go [hunk 1]
```diff
@@ -325,12 +326,22 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
 		}
 
 		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, conditionAppender)
+		podCopyUpdatedWithDeletePreconditions := &updatedObjectInfoWithOverridePreconditions{podCopyUpdated, deleteOptions.Preconditions}
 
-		if _, _, err = r.store.Update(ctx, name, podCopyUpdated, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{}); err != nil {
+		updatedPodObject, _, err := r.store.Update(ctx, name, podCopyUpdatedWithDeletePreconditions, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{DryRun: deleteOptions.DryRun})
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:331]: oof... this means we were actually updating the pod with a condition as part of handling a dry-run evict previously? I'm not sure there's any point in adding the condition if we're in dry run mode, since the whole point of that is to be observed by other API callers

**Comment by atiratree** [comment]
it was added in https://github.com/kubernetes/kubernetes/pull/110959 as an alpha and promoted to a beta and changed to default in https://github.com/kubernetes/kubernetes/pull/113360

File: pkg/registry/core/pod/storage/eviction.go [hunk 2]
```diff
@@ -325,12 +326,22 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
 		}
 
 		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, conditionAppender)
+		podCopyUpdatedWithDeletePreconditions := &updatedObjectInfoWithOverridePreconditions{podCopyUpdated, deleteOptions.Preconditions}
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:329]: I don't understand why we need a custom updatedObjectInfoWithOverridePreconditions wrapper / impl here for the update ... if deleteOptions.Preconditions.ResourceVersion and pod.ResourceVersion are both set and are different, we can reject with a conflict error without proceeding to update or delete, right?

File: pkg/registry/core/pod/storage/eviction.go [hunk 3]
```diff
@@ -307,7 +308,7 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
 	return &metav1.Status{Status: metav1.StatusSuccess}, nil
 }
 
-func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, validation rest.ValidateObjectFunc, options *metav1.DeleteOptions) error {
+func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, validation rest.ValidateObjectFunc, deleteOptions *metav1.DeleteOptions) error {
 	if feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
 		pod, err := getPod(r, ctx, name)
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:313]: we should not be re-getting the pod here, we already got it in EvictionREST#Create and did logic based on it... the pod we're updating/deleting should be passed in

File: pkg/registry/core/pod/storage/eviction.go [hunk 4]
```diff
@@ -325,12 +326,22 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
...
+		if err != nil {
 			return err
 		}
+		if !resourceVersionIsUnset(deleteOptions) {
+			newResourceVersion, err := meta.NewAccessor().ResourceVersion(updatedPodObject)
+			if err != nil {
+				return err
+			}
+			// bump the resource version, since we are the one who modified it via the update
+			deleteOptions.Preconditions.ResourceVersion = &newResourceVersion
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:341]: mutating the input options is not something I'd recommend... work with a copy of deleteOptions and update it locally only.

if we need to propagate a resource version change to other invocations of this method (which I'm not sure we do), return it as a return value instead of mutating input variables

File: pkg/registry/core/pod/storage/eviction.go (hunk 3 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:313]: something like:

1. when we're calling from a place we already have the current pod in EvictionREST#Create, pass in the pod
2. when we did not already fetch the pod, pass in nil
3. in this function, only call getPod() if the passed-in pod is nil

File: pkg/registry/core/pod/storage/eviction.go (hunk 1 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: yeah, not great.. Ok, I suppose we can skip the whole block to simplify the execution.

File: pkg/registry/core/pod/storage/eviction.go (hunk 2 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: Thanks for the suggestion. I was just looking for a way to pass the preconditions somehow, but setting the values directly is more pragmatic and works as well. And I put a comment in the code to make it clearer.

File: pkg/registry/core/pod/storage/eviction.go (hunk 3 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: from what I can tell we always have a reference to the pod, so we can just pass it

File: pkg/registry/core/pod/storage/eviction.go (hunk 4 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: +1, we do not need to propagate, I just overlooked this

File: pkg/registry/core/pod/storage/eviction.go [hunk 5]
```diff
@@ -324,13 +333,22 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
...
+			newResourceVersion, err := meta.NewAccessor().ResourceVersion(updatedPodObject)
+			if err != nil {
+				return err
+			}
+			// bump the resource version, since we are the one who modified it via the update
+			deleteOptionsCopy.Preconditions.ResourceVersion = &newResourceVersion
+		}
 	}
-	_, _, err := r.store.Delete(ctx, name, rest.ValidateAllObjectFunc, options)
+	_, _, err = r.store.Delete(ctx, name, rest.ValidateAllObjectFunc, deleteOptionsCopy)
```
Comment (atiratree) [inline pkg/registry/core/pod/storage/eviction.go:351]: one think that could be problematic is if somebody does update after our update, before we try to delete the pod. In that case we should do a rollback of the condition. Do we care about such a race? Should I implement the rollback? @liggitt

File: pkg/registry/core/pod/storage/eviction_test.go [hunk 6]
```diff
@@ -765,7 +765,7 @@ func (ms *mockStore) Watch(ctx context.Context, options *metainternalversion.Lis
 }
 
 func (ms *mockStore) Update(ctx context.Context, name string, objInfo rest.UpdatedObjectInfo, createValidation rest.ValidateObjectFunc, updateValidation rest.ValidateObjectUpdateFunc, forceAllowCreate bool, options *metav1.UpdateOptions) (runtime.Object, bool, error) {
-	return nil, false, nil
+	return ms.pod, false, nil
```
Comment (atiratree) [inline pkg/registry/core/pod/storage/eviction_test.go:768]: I did not have time to play with this more, but as a followup we could also take into account pod update resource version in the unit tests.

File: pkg/registry/core/pod/storage/eviction.go [hunk 7]
```diff
@@ -307,12 +308,20 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
 }
 
-func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, validation rest.ValidateObjectFunc, options *metav1.DeleteOptions) error {
-	if feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
-		pod, err := getPod(r, ctx, name)
-		if err != nil {
-			return err
+func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, pod *api.Pod, deleteOptions *metav1.DeleteOptions) error {
+	var err error
+	deleteOptionsCopy := deleteOptions.DeepCopy()
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:313]: I'd suggest copying this in place and doing it inside the `if` block only if we need to update conditions


```go
if !dryrun.IsDryRun(deleteOptionsCopy.DryRun) && feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
  options = options.DeepCopy()
  ...
```

File: pkg/registry/core/pod/storage/eviction.go (hunk 5 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:351]: I don't know... I thought we had a controller reconciling bogus conditions

File: pkg/registry/core/pod/storage/eviction.go [hunk 8]
```diff
@@ -291,7 +292,7 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
 	}
 
 	// Try the delete
-	err = addConditionAndDeletePod(r, ctx, eviction.Name, rest.ValidateAllObjectFunc, deleteOptions)
+	err = addConditionAndDeletePod(r, ctx, eviction.Name, pod, deleteOptions)
 	if err != nil {
 		if errors.IsConflict(err) && updateDeletionOptions &&
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:297]: if `updateDeletionOptions == false`, and we hit a conflict adding the condition, do we retry or return an error to the user? if we return an error, is it an error that prompts a retry as commented in this block or not?

File: pkg/registry/core/pod/storage/eviction.go [hunk 9]
```diff
@@ -307,12 +308,20 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
+
+	if !dryrun.IsDryRun(deleteOptionsCopy.DryRun) && feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
+		podCopy := pod.DeepCopy()
+		// morph the pod into the pod requested by preconditions and let Update fail in case they do not pass
+		if !resourceVersionIsUnset(deleteOptionsCopy) {
+			podCopy.ResourceVersion = *deleteOptionsCopy.Preconditions.ResourceVersion
 		}
+		if deleteOptionsCopy.Preconditions != nil && deleteOptionsCopy.Preconditions.UID != nil {
+			podCopy.UID = *deleteOptionsCopy.Preconditions.UID
+		}
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:323]: oh! I just got oriented to what's happening here, and there's a much more elegant approach that gets rid of the race between `getPod` and `Update` entirely

Update already gets from etcd internally, then hands a copy of the old pod to the UpdatedObjectInfo getter and passes it through the transformer chain

Rather than plumbing `pod` to addConditionAndDeletePod`, update our transformer chain to transform the pod coming from etcd, adding in the resourceVersion and UID precondition if applicable, along with our conditions:

```go
setPreconditions := func(_ context.Context, _, oldObj runtime.Object) (runtime.Object, error) {
  oldPodCopy := oldObj.(*api.Pod).DeepCopy()
  if options.Preconditions != nil {
    if uid := options.Preconditions.UID; uid != nil && len(*uid) > 0 {
      oldPodCopy.UID = *uid
    }
    if rv := options.Preconditions.ResourceVersion; rv != nil && len(*rv) > 0 {
      oldPodCopy.ResourceVersion = *rv
    }
  }
  return oldPodCopy, nil
}
conditionAppender := ...
conditionedPod := rest.DefaultUpdatedObjectInfo(nil, setPreconditions, conditionAppender)
```

if the precondition uid or resourceVersion conflicts with what's already in etcd, Update will return a conflict appropriately

if there was no precondition uid or resourceVersion, Update will handle retrying internally as needed

then continue with what you have here, updating the resourceVersion in `options` with the resulting resourceVersion from our Update call

File: pkg/registry/core/pod/storage/eviction.go (hunk 5 above)
Comment (mimowo) [reply pkg/registry/core/pod/storage/eviction.go:351]: We have a disruption controller which cleans up stale DisruptionTarget conditions: https://github.com/kubernetes/kubernetes/blob/152876a3eb9c6211c48bb159c87e2bf834e4eedc/pkg/controller/disruption/disruption.go#L729. By stale we mean conditions which are 2min old if there was no deletion in the meanwhile.

**Comment by mimowo** [comment]
@atiratree thank you for working on the fix. I think we should cherry-pick it to 1.26.

File: pkg/registry/core/pod/storage/eviction.go (hunk 5 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: Cool, I think, because it is an unlikely race, it should be enough to leave it to the controller

File: pkg/registry/core/pod/storage/eviction.go (hunk 7 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: +1, moved only to the place where we need to change the options

File: pkg/registry/core/pod/storage/eviction.go (hunk 9 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:330]: Nice, this makes more sense. Thanks a lot for digging into this. I have used your code snippet and added some  comments. Can you please let me know if the comments make sense or if I should make them more verbose? Eg. mentioning the logic of the Update function?

File: pkg/registry/core/pod/storage/eviction.go (hunk 8 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:298]: After implementing the https://github.com/kubernetes/kubernetes/pull/116554/files/4ca6333cc16e3995c3b3a3a6b158ad2d9f53d845#diff-6105105bc4d40e3d45b9cc38165516be0205f0329929421fd7df65df7abaeb2c to remove the conflict race, it seems to me we can keep the old logic here. That is, retry only if we made an eviction decision based on stale information (readiness of the pod), that could have changed  in the meantime.

**Comment by atiratree** [comment]
+1 for the cherry-pick

File: test/integration/evictions/evictions_test.go [hunk 10]
```diff
@@ -20,6 +20,7 @@ import (
 	"context"
 	"encoding/json"
 	"fmt"
+	"k8s.io/apimachinery/pkg/util/uuid"
```
Comment (alculquicondor) [inline test/integration/evictions/evictions_test.go:23]: separate import block

File: test/integration/evictions/evictions_test.go [hunk 11]
```diff
@@ -502,6 +530,116 @@ func TestEvictionWithUnhealthyPodEvictionPolicy(t *testing.T) {
...
+			waitToObservePods(t, informers.Core().V1().Pods().Informer(), 1, v1.PodRunning)
+
+			updatedPod, err := clientSet.CoreV1().Pods(ns.Name).Get(context.TODO(), pod.Name, metav1.GetOptions{})
+			if err != nil {
+				t.Fatalf("Failed to get the pod %q with error: %q", klog.KObj(pod), err)
+			}
+
+			deleteOption := metav1.DeleteOptions{}
+
+			if deleteOption.Preconditions == nil {
```
Comment (mimowo) [inline test/integration/evictions/evictions_test.go:598]: nit: this `if` doesn't seem needed, it would always be true at that point.

**Comment by alculquicondor** [comment]
Definitely cherry-pick. We do so for beta features.

File: pkg/registry/core/pod/storage/eviction.go [hunk 12]
```diff
@@ -307,12 +310,25 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
+func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, pod *api.Pod, deleteOptions *metav1.DeleteOptions) error {
+	if !dryrun.IsDryRun(deleteOptions.DryRun) && feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
+		setPreconditions := func(_ context.Context, _, oldObj runtime.Object) (runtime.Object, error) {
+			// Throwaway the newObj. We care only about the latest pod obtained from etcd (oldObj).
+			// So we can add DisruptionTarget condition in conditionAppender without conflicts.
+			oldPodCopy := oldObj.(*api.Pod).DeepCopy()
+			if deleteOptions.Preconditions != nil {
+				// Insert preconditions into the pod object if we or the user specifically requested them,
+				// and let the update fail in case they do not pass.
+				if uid := deleteOptions.Preconditions.UID; uid != nil && len(*uid) > 0 {
```
Comment (mimowo) [inline pkg/registry/core/pod/storage/eviction.go:322]: I'm wondering if the check `len(*uid) > 0` is needed. Shouldn't "" be just treated as an invalid value at the validation level and rejected?

File: pkg/registry/core/pod/storage/eviction.go [hunk 13]
```diff
@@ -307,12 +310,25 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
+					oldPodCopy.UID = *uid
+				}
+				if rv := deleteOptions.Preconditions.ResourceVersion; rv != nil && len(*rv) > 0 {
```
Comment (mimowo) [inline pkg/registry/core/pod/storage/eviction.go:325]: As above, wondering if `len(*rv) > 0)` is needed here, and if there isn't another layer that validates it.

**Review by mimowo — COMMENTED** [review]
Just a nit and questions from me about handling of empty UID / ResourceVersion values. Overall looks sensible to me, but I prefer to leave it to API reviewers.

File: test/integration/evictions/evictions_test.go [hunk 14]
```diff
@@ -491,7 +508,18 @@ func TestEvictionWithUnhealthyPodEvictionPolicy(t *testing.T) {
...
-			err := clientSet.PolicyV1().Evictions(ns.Name).Evict(ctx, eviction)
+			err := clientSet.CoreV1().RESTClient().Post().
+				AbsPath("/api/v1").
+				Namespace(eviction.Namespace).
+				Resource("pods").
+				Name(eviction.Name).
+				SubResource("eviction").
+				Body(eviction).
+				// Eviction API can return http.StatusTooManyRequests (429) with retryAfterSeconds == 10s
+				// Do not retry - we want to test that the first request succeeds and make sure it doesn't unnecessarily block the test for 10s
```
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:519]: Normally the client would retry on 429 or 500+ for POST requests with `Retry-After` header:

https://github.com/kubernetes/client-go/blob/b5e4a5a9c356d800639ba18f67ae30aef96855f3/rest/with_retry.go#L309

https://github.com/kubernetes/client-go/blob/b5e4a5a9c356d800639ba18f67ae30aef96855f3/rest/request.go#L1267

which we can also send: StatusGatewayTimeout (504)

will update the description

Nevertheless we want to test the absence of the retry here.

File: pkg/registry/core/pod/storage/eviction.go [hunk 15]
```diff
@@ -324,13 +340,25 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
...
+		// pass the potentially stale pod here only to trigger the default UID precondition
+		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, setPreconditions, conditionAppender) // order important
 
-		if _, _, err = r.store.Update(ctx, name, podCopyUpdated, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{}); err != nil {
+		updatedPodObject, _, err := r.store.Update(ctx, name, podCopyUpdated, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{})
+		if err != nil {
 			return err
 		}
+
+		if !resourceVersionIsUnset(deleteOptions) {
```
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:351]: ack, better to resolve after so we don't have to backport it

File: test/integration/evictions/evictions_test.go [hunk 16]
```diff
@@ -404,10 +414,17 @@ func TestEvictionWithFinalizers(t *testing.T) {
...
+				if cond == nil && !tc.dryRun {
+					t.Errorf("Pod %q does not have the expected condition: %q", klog.KObj(updatedPod), v1.DisruptionTarget)
+				}
+				if cond != nil && tc.dryRun {
+					t.Errorf("Pod %q has an unexpected condition in dry-run mode: %q", klog.KObj(updatedPod), v1.DisruptionTarget)
+				}
+			} else {
+				if cond != nil {
+					t.Errorf("Pod %q has an unexpected condition: %q", klog.KObj(updatedPod), v1.DisruptionTarget)
+				}
```
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go]: +1 and the diff looks better now

File: test/integration/evictions/evictions_test.go [hunk 17]
```diff
@@ -502,6 +530,116 @@ func TestEvictionWithUnhealthyPodEvictionPolicy(t *testing.T) {
...
+			pod := newPod("pod")
+			pod, err := clientSet.CoreV1().Pods(ns.Name).Create(context.TODO(), pod, metav1.CreateOptions{})
+			if err != nil {
+				t.Errorf("Failed to create pod: %q", err)
+			}
+
+			pod.Status.Phase = v1.PodRunning
+			addPodConditionReady(pod)
+
+			if _, err := clientSet.CoreV1().Pods(ns.Name).UpdateStatus(ctx, pod, metav1.UpdateOptions{}); err != nil {
```
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go]: yes, simplified the code and added a comment

**Comment by alculquicondor** [comment]
Please add a release note
/priority critical-urgent

File: test/integration/evictions/evictions_test.go (hunk 11 above)
Comment (atiratree) [reply test/integration/evictions/evictions_test.go]: forgot to change this to `tc.enforceResourceVersion || tc.enforceUID`. Fixed

File: pkg/registry/core/pod/storage/eviction.go (hunk 12 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:322]: it seems we have only these validations for DeleteOptions:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go#L116

which does not include Preconditions. 

@liggitt is it reasonable and can we make the validation stricter?

File: test/integration/evictions/evictions_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: We need the 0 retries and not to retry on conflict to potentially catch the regression where eviction unnecessarily fails (https://github.com/kubernetes/kubernetes/issues/116552).

Also, I am not sure if it would help against connection errors, since POST requests do not normally retry on these:

https://github.com/kubernetes/client-go/blob/b5e4a5a9c356d800639ba18f67ae30aef96855f3/rest/request.go#L983

And if we observe retries generated by us:
429 - bad and we should fail
504 - possibly also bad since we use it to detect too many retries in the eviction API: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L57

File: pkg/registry/core/pod/storage/eviction.go (hunk 12 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:322]: no, don't change the validation there

when deleting and sending delete options via URL query parameter, preconditions are only created if greater than zero length:
```go
	if len(uid) > 0 || len(resourceVersion) > 0 {
		if out.Preconditions == nil {
			out.Preconditions = &Preconditions{}
		}
		if len(uid) > 0 {
			out.Preconditions.UID = &uid
		}
		if len(resourceVersion) > 0 {
			out.Preconditions.ResourceVersion = &resourceVersion
		}
	}
```

When sending delete options in the body of a delete request, you could set resourceVersion or UID to non-nil zero-length strings, though that would be a weird thing to do. Setting zero-length UID or resourceVersion strings in a pod while updating it will not have the same effect as those zero-length preconditions.

The UID would get copied from the existing pod
* https://github.com/kubernetes/kubernetes/blob/1cb334960c4288fc7830a16c97f5f8489f140b5b/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L131-L134

Setting an empty resourceVersion in the pod would circumvent optimistic locking and mean we would stomp whatever was in etcd if we raced with another write
* https://github.com/kubernetes/kubernetes/blob/1cb334960c4288fc7830a16c97f5f8489f140b5b/pkg/registry/core/pod/strategy.go#L154-L157
https://github.com/kubernetes/kubernetes/blob/1cb334960c4288fc7830a16c97f5f8489f140b5b/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L576-L584

File: test/integration/evictions/evictions_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/evictions/evictions_test.go:518]: My question is whether a resourceVersion conflict would be retried. If it wouldn't I don't think we should reset it.

Most clients wouldn't change the retry settings, so I don't see a point on testing something different.

File: pkg/registry/core/pod/storage/eviction.go (hunk 12 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:322]: keep the checks to only set UID / resourceVersion in the pod if they are non-empty

File: pkg/registry/core/pod/storage/eviction.go (hunk 13 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:325]: there is not, see above comment for why we should keep this (setting a "" resourceVersion actually makes the pod write less safe)

File: test/integration/evictions/evictions_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: The resourceVersion conflict would be retried here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L301

That is why we didn't catch the bug before for example in `TestEvictionWithUnhealthyPodEvictionPolicy` test where we run into this issue, so I am removing the retries there as well.

[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: the client would handle the retry for the `NewTooManyRequests` response

File: pkg/registry/core/pod/storage/eviction.go (hunk 12 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:322]: ack, thanks for the explanation

File: test/integration/evictions/evictions_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/evictions/evictions_test.go:518]: Ahh, I understand now. I wonder why it returns such response, it doesn't sound right to me.
@liggitt ?

[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: the reasoning behind the 429 one: we might be trying to delete only an unready pod and if something changes to the pod (readiness or something unimportant), we give the client an option to try again and it may succeed/fail depending on the pod change

[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/evictions/evictions_test.go:518]: But we only send TooManyRequests if `originalDeleteOptions.Preconditions == nil || originalDeleteOptions.Preconditions.ResourceVersion == nil`.

[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: yes, I think it is mostly for the client to achieve success. When eviction of the pod fails, the client might move on to the next pod and we give it a chance to evict the pod on a 2nd try.

When client sets a precondition, the request will not succeed on a 2nd try.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/evictions/evictions_test.go:518]: Ah, I see. The bug was that we issued retries for `Preconditions.UID != nil`.

Is there an alternative way of disabling retries without having to copy the implementation of `Evict`?

[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go:518]: on the other hand UID conflict might not be that often, so I changed the condition to compare with the pod UID, added another if statement and comments for better readability 

PTAL @alculquicondor @liggitt

[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/evictions/evictions_test.go:518]: uhm... it looks like retries are not part of the kubeconfig.

Too many changes for this PR, so expanding the implementation should be ok for now.

File: pkg/registry/core/pod/storage/eviction.go [hunk 18]
```diff
@@ -179,7 +180,7 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
 			deleteOptions = deleteOptions.DeepCopy()
 			setPreconditionsResourceVersion(deleteOptions, &pod.ResourceVersion)
 		}
-		err = addConditionAndDeletePod(r, ctx, eviction.Name, rest.ValidateAllObjectFunc, deleteOptions)
+		err = addConditionAndDeletePod(r, ctx, pod, deleteOptions)
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:183]: revert the signature change here, we're not using the looked-up pod at all any more inside addConditionAndDeletePod

File: pkg/registry/core/pod/storage/eviction.go [hunk 19]
```diff
@@ -291,14 +292,19 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
 	}
 
 	// Try the delete
-	err = addConditionAndDeletePod(r, ctx, eviction.Name, rest.ValidateAllObjectFunc, deleteOptions)
+	err = addConditionAndDeletePod(r, ctx, pod, deleteOptions)
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:295]: revert the signature change here, we're not using the looked-up pod at all any more inside addConditionAndDeletePod

File: pkg/registry/core/pod/storage/eviction.go [hunk 20]
```diff
@@ -291,14 +292,19 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
-			// If we encounter a resource conflict error, we updated the deletion options to include them,
-			// and the original deletion options did not specify ResourceVersion, we send back
-			// TooManyRequests so clients will retry.
-			return nil, createTooManyRequestsError(pdbName)
+		// retry is useful if we made a decision on a stale information
+		if errors.IsConflict(err) && updateDeletionOptions {
+			// check that the original preconditions do not conflict with a pod resourceVersion or UID
+			hasConflictingOriginalPreconditions := originalDeleteOptions.Preconditions != nil && (originalDeleteOptions.Preconditions.ResourceVersion != nil ||
+				(originalDeleteOptions.Preconditions.UID != nil && *originalDeleteOptions.Preconditions.UID != pod.UID))
+			if !hasConflictingOriginalPreconditions {
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:302]: I think we should revert this change, for a couple reasons:
1. we only want clients to retry on a resourceVersion conflict, a uid conflict means this is a completely different pod
2. this is too difficult to reason about if we want to backport this

File: pkg/registry/core/pod/storage/eviction.go [hunk 21]
```diff
@@ -324,13 +343,25 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
 			return podObj, nil
 		}
 
-		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, conditionAppender)
+		// pass the potentially stale pod here only to trigger the default UID precondition
+		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, setPreconditions, conditionAppender) // order important
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:347]: pass in `nil` for the new pod, `setPreconditions` is throwing away the newObj so it's not used at all

File: pkg/registry/core/pod/storage/eviction.go [hunk 22]
```diff
@@ -307,12 +313,25 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
 	return &metav1.Status{Status: metav1.StatusSuccess}, nil
 }
 
-func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string, validation rest.ValidateObjectFunc, options *metav1.DeleteOptions) error {
-	if feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
-		pod, err := getPod(r, ctx, name)
-		if err != nil {
-			return err
+func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, pod *api.Pod, deleteOptions *metav1.DeleteOptions) error {
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:316]: revert the signature change here, we don't need the looked-up pod any more

File: pkg/registry/core/pod/storage/eviction.go [hunk 23]
```diff
@@ -307,12 +313,25 @@ func (r *EvictionREST) Create(ctx context.Context, name string, obj runtime.Obje
...
+	if !dryrun.IsDryRun(deleteOptions.DryRun) && feature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
+		setPreconditions := func(_ context.Context, _, oldObj runtime.Object) (runtime.Object, error) {
+			// Throwaway the newObj. We care only about the latest pod obtained from etcd (oldObj).
+			// So we can add DisruptionTarget condition in conditionAppender without conflicts.
+			oldPodCopy := oldObj.(*api.Pod).DeepCopy()
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go:321]: maybe rename this for clarity to `podWithPreconditions`

File: pkg/registry/core/pod/storage/eviction.go (hunk 21 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: I was mostly concerned about the case if pod and its uid changes midflight since we last obtained it from get - should we fail on that? But can change this to nil, if this isn't a real concern.

File: pkg/registry/core/pod/storage/eviction.go (hunk 22 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: reverted the name back to options for a smaller diff. Pod up for a discussion in https://github.com/kubernetes/kubernetes/pull/116554#discussion_r1139283729

File: pkg/registry/core/pod/storage/eviction.go (hunk 21 above)
Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go]: > I was mostly concerned about the case if pod and its uid changes midflight since we last obtained it from get

Yeah, go ahead and change this to nil. if the uid/resourceVersion matching is important, the passed-in DeleteOptions will tell us that, and we can honor those using our `podWithPreconditions` transformer

File: pkg/registry/core/pod/storage/eviction.go (hunk 18 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:183]: up for a discussion in https://github.com/kubernetes/kubernetes/pull/116554#discussion_r1139283729

File: pkg/registry/core/pod/storage/eviction.go (hunk 21 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: ok, changed this to nil. And let's honor only the delete options

File: pkg/registry/core/pod/storage/eviction.go (hunk 18 above)
Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go]: reverted

File: pkg/registry/core/pod/storage/eviction.go [hunk 24]
```diff
@@ -324,11 +338,23 @@ func addConditionAndDeletePod(r *EvictionREST, ctx context.Context, name string,
 			return podObj, nil
 		}
 
-		podCopyUpdated := rest.DefaultUpdatedObjectInfo(pod, conditionAppender)
+		// obj will be obtained in setPreconditions transformer
+		podUpdatedObjectInfo := rest.DefaultUpdatedObjectInfo(nil, setPreconditions, conditionAppender) // order important
 
-		if _, _, err = r.store.Update(ctx, name, podCopyUpdated, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{}); err != nil {
+		updatedPodObject, _, err := r.store.Update(ctx, name, podUpdatedObjectInfo, rest.ValidateAllObjectFunc, rest.ValidateAllObjectUpdateFunc, false, &metav1.UpdateOptions{})
+		if err != nil {
```
Comment (atiratree) [inline pkg/registry/core/pod/storage/eviction.go:345]: I did some more testing, and a bit problematic part here is that we are getting different errors now:

when trying to evict pod with `.deleteOptions.preconditions.uid`

before we were getting: `Error from server (Conflict): Operation cannot be fulfilled on Pod "nginx": the UID in the precondition (596f4808-3fd2-4de3-b028-4980faa3ba29) does not match the UID in record (7d9eec6a-0e46-498f-94c3-578299306a31). The object might have been deleted and then recreated`

now we get: `The Pod "nginx" is invalid: metadata.uid: Invalid value: "596f4808-3fd2-4de3-b028-4980faa3ba29": field is immutable`

which could be confusing to get during an eviction request.

It is much better when using `.deleteOptions.preconditions.resourceVersion`

before we got: `Error from server (Conflict): Operation cannot be fulfilled on Pod "nginx": the ResourceVersion in the precondition (469) does not match the ResourceVersion in record (522539). The object might have been modified`

now we are getting: `Error from server (Conflict): Operation cannot be fulfilled on pods "nginx": the object has been modified; please apply your changes to the latest version and try again`

This one is not that confusing but the before message was more appropriate.

We could try to reintroduce the preconditions, or do some processing/validation after when we get an error and generate our messsages (at least for the uid one).

thoughts?

Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:345]: rather than setting the uid / resourceVersion into podWithPreconditions, we can do the comparison directly and return the conflict errors we want that exactly match the delete uid/rv errors:

```go
podWithPreconditions := oldObj.(*api.Pod).DeepCopy()
if uid := options.Preconditions.UID; uid != nil && len(*uid) > 0 && *uid != podWithPreconditions.UID {
  return nil, errors.NewConflict(
    schema.GroupResource{Group: "", Resource: "Pod"},
    podWithPreconditions.Name,
    fmt.Errorf("the UID in the precondition (%s) does not match the UID in record (%s). The object might have been deleted and then recreated", *uid, podWithPreconditions.UID),
  )
}
if rv := options.Preconditions.ResourceVersion; rv != nil && len(*rv) > 0 && *rv != podWithPreconditions.ResourceVersion {
  return nil, errors.NewConflict(
    schema.GroupResource{Group: "", Resource: "Pod"},
    podWithPreconditions.Name,
    fmt.Errorf("the ResourceVersion in the precondition (%s) does not match the ResourceVersion in record (%s). The object might have been modified", *rv, podWithPreconditions.ResourceVersion),
  )
}
return podWithPreconditions, nil
```

Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go:345]: thanks for checking the user-facing behavior in conflicts

Comment (atiratree) [reply pkg/registry/core/pod/storage/eviction.go:351]: ah, we can just return the error from the transformer ^^. Works well now. Thanks

**Comment by bobbypage** [comment]
@liggitt do you have a prow link to the job where that race was detected?

**Comment by liggitt** [comment]
Yup, available in the PR history for this PR: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=116554

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116554/pull-kubernetes-unit/1636476265563164672

**Comment by bobbypage** [comment]
Thanks for the link. Is this a kubelet or issue with the kubemark?

It seems like the test that failed is `=== FAIL: cmd/kubemark/app TestHollowNode/kubelet (3.00s)` and possibly related to kubemark, which is a new test added as part of https://github.com/kubernetes/kubernetes/pull/116645

**Comment by bobbypage** [comment]
Filed https://github.com/kubernetes/kubernetes/issues/116696 for the race

**Comment by liggitt** [comment]
> kubemark

I think it's kubemark or the kubemark unit test

File: test/integration/evictions/evictions_test.go [hunk 25]
```diff
@@ -502,6 +529,113 @@ func TestEvictionWithUnhealthyPodEvictionPolicy(t *testing.T) {
...
+				if tc.injectWrongUID {
+					newUID := uuid.NewUUID()
+					deleteOption.Preconditions.UID = &newUID
+				} else {
+					deleteOption.Preconditions.UID = &updatedPod.UID
+				}
+			}
+
+			eviction := newV1Eviction(ns.Name, updatedPod.Name, deleteOption)
+			err = clientSet.CoreV1().RESTClient().Post().
```
Comment (liggitt) [inline test/integration/evictions/evictions_test.go:616]: can use noRetriesRESTClient here as well and call the normal clientset Evict method

File: test/integration/evictions/evictions_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/evictions/evictions_test.go]: I have remove the duplicated logic from evictions client in favor of this approach - looks better now

**Review by alculquicondor — COMMENTED** [review]
not an apiserver expert, but:
/lgtm

File: test/integration/evictions/evictions_test.go [hunk 26]
```diff
@@ -38,12 +38,14 @@ import (
 	"k8s.io/apimachinery/pkg/types"
```
Comment (liggitt) [inline test/integration/evictions/evictions_test.go:38]: I thought of one more scenario where the update and delete behavior could differ, which was if the pod we were trying to manipulate was already gone from etcd. The Delete function has some compensation for that which Update does not (since if you are asking to delete an object, and it doesn't exist, Delete could plausibly return success)

To prove that addConditionAndDeletePod returns identical responses with/without the feature gate enabled, I made this test:

```go
func TestAddConditionAndDelete(t *testing.T) {
	cases := []struct {
		name              string
		initialPod        bool
		makeDeleteOptions func(*api.Pod) *metav1.DeleteOptions
		expectErr         string
	}{
		{
			name:              "simple",
			initialPod:        true,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions { return &metav1.DeleteOptions{} },
		},
		{
			name:              "missing",
			initialPod:        false,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions { return &metav1.DeleteOptions{} },
			expectErr:         "not found",
		},
		{
			name:       "valid uid",
			initialPod: true,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions {
				return &metav1.DeleteOptions{Preconditions: &metav1.Preconditions{UID: &pod.UID}}
			},
		},
		{
			name:       "invalid uid",
			initialPod: true,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions {
				badUID := pod.UID + "1"
				return &metav1.DeleteOptions{Preconditions: &metav1.Preconditions{UID: &badUID}}
			},
			expectErr: "The object might have been deleted and then recreated",
		},
		{
			name:       "valid resourceVersion",
			initialPod: true,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions {
				return &metav1.DeleteOptions{Preconditions: &metav1.Preconditions{ResourceVersion: &pod.ResourceVersion}}
			},
		},
		{
			name:       "invalid resourceVersion",
			initialPod: true,
			makeDeleteOptions: func(pod *api.Pod) *metav1.DeleteOptions {
				badRV := pod.ResourceVersion + "1"
				return &metav1.DeleteOptions{Preconditions: &metav1.Preconditions{ResourceVersion: &badRV}}
			},
			expectErr: "The object might have been modified",
		},
	}

	testContext := genericapirequest.WithNamespace(genericapirequest.NewContext(), metav1.NamespaceDefault)

	storage, _, _, server := newStorage(t)
	defer server.Terminate(t)
	defer storage.Store.DestroyFunc()

	client := fake.NewSimpleClientset()
	evictionRest := newEvictionStorage(storage.Store, client.PolicyV1())

	for _, tc := range cases {
		for _, conditionsEnabled := range []bool{true, false} {
			name := fmt.Sprintf("%s_conditions=%v", tc.name, conditionsEnabled)
			t.Run(name, func(t *testing.T) {
				defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.PodDisruptionConditions, conditionsEnabled)()
				var deleteOptions *metav1.DeleteOptions
				if tc.initialPod {
					newPod := validNewPod()
					createdObj, err := storage.Create(testContext, newPod, rest.ValidateAllObjectFunc, &metav1.CreateOptions{})
					if err != nil {
						t.Fatal(err)
					}
					t.Cleanup(func() {
						zero := int64(0)
						storage.Delete(testContext, newPod.Name, rest.ValidateAllObjectFunc, &metav1.DeleteOptions{GracePeriodSeconds: &zero})
					})
					deleteOptions = tc.makeDeleteOptions(createdObj.(*api.Pod))
				} else {
					deleteOptions = tc.makeDeleteOptions(nil)
				}
				if deleteOptions == nil {
					deleteOptions = &metav1.DeleteOptions{}
				}

				err := addConditionAndDeletePod(evictionRest, testContext, "foo", rest.ValidateAllObjectFunc, deleteOptions)
				if err == nil {
					if tc.expectErr != "" {
						t.Fatalf("expected err containing %q, got none", tc.expectErr)
					}
					return
				}
				if tc.expectErr == "" {
					t.Fatalf("unexpected err: %v", err)
				}
				if !strings.Contains(err.Error(), tc.expectErr) {
					t.Fatalf("expected err containing %q, got %v", tc.expectErr, err)
				}
			})
		}
	}
}
```

That shows we're consistent in the missing pod case as well, so no changes to `pkg/registry/core/pod/storage/eviction.go` are needed, but if you want to add that test, I think that's a good way to exercise that function with/without the feature gate on and make sure the same inputs produce the same outputs.

Comment (atiratree) [reply test/integration/evictions/evictions_test.go:38]: I have included the test, thanks! Good to be thorough and compare the possible scenarios.

**Comment by liggitt** [comment]
once this passes tests, go ahead and open a cherry-pick to release-1.26

**Comment by atiratree** [comment]
flaky test [Test_Run_OneVolumeDetachFailNodeWithReadWriteOnce](https://github.com/kubernetes/kubernetes/issues/107414)
/test pull-kubernetes-unit

**Comment by atiratree** [comment]
opened a cherry-pick https://github.com/kubernetes/kubernetes/pull/116750
