### PR TITLE
Fix discovery/deletion of iscsi block devices

### LINKED ISSUE #59946: iSCSI should be deleting scsi devices on PV unmount to prevent data corruption
> /kind bug

**What happened**:

I am not an iSCSI expert, but it looks like there is data corruption  possible on iSCSI LUN reuse.

In the following sequence of events on a given node:

1. Provision iSCSI volume , map to host, LUN X will be assigned to it
2. let node discover that LUN (lets say mount another iSCSI PV, which would trigger iSCSI rescan)
3. delete iSCSI volume (LUN X will be unmapped from host)
4. Create new iSCSI volume, map to host, same LUN X will be assigned to it, following warning will be printed on a console:
```
Warning! Received an indication that the LUN assignments on this target have changed. 
The Linux SCSI layer does not automatically remap LUN assignments.
```
5. create PV for that iSCSI volume
6. run pod with that PV on this node

What is going to happen, is that even though `iscsi` volume plugin rescans scsi bus, rescan doesn't delete previously existing SCSI devices, so it can (will?) use OLD LUN X scsi device and then attempt to mount it with unknown consequences. On our systems we definitely saw how freshly formatted dynamically  provisioned volume couldn't be mounted due to ext4 errors , with  LUN warnings reported just before. I'll try to prepare reproducer for this case, but this "analytical proof" looks pretty scary already :-/

Steps 1, 3 can be done by dynamic provisioner such as netapp Trident, these volumes can be mounted on another node and never be mouted on a node in  question, what important is that they are created and node discovers them.

Extra information on LUN reuse, where solid advice on device deletion is given by kernel devs:

https://www.redhat.com/archives/dm-devel/2018-January/msg00493.html
https://www.redhat.com/archives/dm-devel/2016-October/msg00409.html

/sig storage
/cc @mtanino

### PR DESCRIPTION
**Pull request by bswartz**
This PR modifies the iSCSI attach/detatch codepaths in the following
ways:
1) After unmounting a filesystem on an iSCSI block device, always
flush the multipath device mapper entry (if it exists) and delete
all block devices so the kernel forgets about them.
2) When attaching an iSCSI block device, instead of blindly
attempting to scan for the new LUN, first determine if the target
is already logged into, and if not, do the login first. Once every
portal is logged into, the scan is done.
3) Scans are now done for specific devices, instead of the whole
bus. This avoids discovering LUNs that kubelet has no interest in.
4) Additions to the underlying utility interfaces, with new tests
for the new functionality.
5) Some existing code was shifted up or down, to make the new logic
work.
6) A typo in an existing exec call on the attach path was fixed.

Fixes #59946

```release-note
When attaching iSCSI volumes, kubelet now scans only the specific
LUNs being attached, and also deletes them after detaching. This avoids
dangling references to LUNs that no longer exist, which used to be the
cause of random I/O errors/timeouts in kernel logs, slowdowns during
block-device related operations, and very rare cases of data corruption.
```

### CODE REVIEW

**Comment by bswartz** [comment]
CLA issue should be fixed

**Comment by rootfs** [comment]
cc @bmarzins

**Comment by rootfs** [comment]
I am not a multipath expert, looping in @bmarzins

File: pkg/volume/util/device_util_linux.go [hunk 1]
```diff
@@ -80,3 +83,202 @@ func (handler *deviceHandler) FindSlaveDevicesOnMultipath(dm string) []string {
...
+			// Only if the session matches the target we were looking for,
+			// add it to the map
+			if strings.TrimSpace(string(targetName)) != targetIqn {
+				continue
+			}
+
+			// The list of block devices on the scsi bus will be in a
+			// directory called "target%d:%d:%d".
+			// See drivers/scsi/scsi_scan.c in Linux
+			// We assume the channel/bus and device/controller are always zero for iSCSI
```
Comment (redbaron) [inline pkg/volume/util/device_util_linux.go]: is it true for iSCSI offloading cards?

**Comment by rootfs** [comment]
@humblec do you have a multipath setup to test this?

File: pkg/volume/util/device_util_linux.go (hunk 1 above)
Comment (bswartz) [reply pkg/volume/util/device_util_linux.go]: I'm trying to determine this. I don't have an offload card but I've ordered some and when I get them installed I'll do experiments.

**Comment by humblec** [comment]
@bswartz Thanks.. I am starting the review with a question :) 

` After unmounting a filesystem on an iSCSI block device, always
    flush the multipath device mapper entry (if it exists) and delete
    all block devices so the kernel forgets about them.`

Is it really required to flush the device mapper multipath entries ? afaik, the device mapper will take care of flushing stale device entries after a time stamp/period. I am trying to understand why we need to do it by code , if its required all storage admin has to do this operation manually as soon as an unmount occurs which I think not the case. Also without 'mandatory' flushing are we seeing any functional issues in iscsi workflow ?

**Comment by redbaron** [comment]
@humblec , AFAIK multipathd reacts to udev events and therefore can lag behind processing them. IMHO it is best to delete multipath device explicitly to avoid any potential issues and bugs in other parts of the chain.

**Comment by bswartz** [comment]
@humblec What redbaron says is true. Also, I was following RedHat's recommended practices from this document:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/online_storage_reconfiguration_guide/removing_devices

**Comment by humblec** [comment]
@redbaron @bswartz its definitely good to have, however my attempt was to find out whether its mandatory or any potential issues in absense of it. The guide which was pointed above belongs to RHEL 5, the device mapper and other software stack would have got good amount of changes in latest versions, somehow I was not able to find out this section in RHEL 7 guide here https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/dm_multipath/ or https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/index.

File: pkg/volume/iscsi/iscsi_util.go [hunk 2]
```diff
@@ -242,12 +263,79 @@ func (util *ISCSIUtil) AttachDisk(b iscsiDiskMounter) (string, error) {
 		b.Iface = newIface
 	}
 
+	// Build a map of SCSI hosts for each target portal. We will need this to
+	// issue the bus rescans.
+	portalHostMap, err := b.deviceUtil.GetIscsiPortalHostMapForTarget(b.Iqn)
+	if nil != err {
```
Comment (humblec) [inline pkg/volume/iscsi/iscsi_util.go]: `err != nil` looks consistent.

File: pkg/volume/iscsi/iscsi_util.go [hunk 3]
```diff
@@ -242,12 +263,79 @@ func (util *ISCSIUtil) AttachDisk(b iscsiDiskMounter) (string, error) {
...
+		return "", err
+	}
+	glog.V(6).Infof("AttachDisk portal->host map for %s is %v", b.Iqn, portalHostMap)
```
Comment (humblec) [inline pkg/volume/iscsi/iscsi_util.go]: We can place this on v3 or v4.

File: pkg/volume/util/device_util_linux.go [hunk 4]
```diff
@@ -80,3 +83,202 @@ func (handler *deviceHandler) FindSlaveDevicesOnMultipath(dm string) []string {
 	}
 	return devices
 }
+
+// GetIscsiPortalHostMapForTarget given a target iqn, find all the scsi hosts logged into
+// that target. Returns a map by target portal to
```
Comment (humblec) [inline pkg/volume/util/device_util_linux.go]: Can you please expand the source code comment on how the portalmap looks like ?

File: pkg/volume/iscsi/iscsi_util.go [hunk 5]
```diff
@@ -242,12 +263,79 @@ func (util *ISCSIUtil) AttachDisk(b iscsiDiskMounter) (string, error) {
...
+
 	for _, tp := range bkpPortal {
-		// Rescan sessions to discover newly mapped LUNs. Do not specify the interface when rescanning
-		// to avoid establishing additional sessions to the same target.
-		out, err := b.exec.Run("iscsiadm", "-m", "node", "-p", tp, "-T", b.Iqn, "-R")
-		if err != nil {
-			glog.Errorf("iscsi: failed to rescan session with error: %s (%v)", string(out), err)
+		hostNumber, loggedIn := portalHostMap[tp]
+		if !loggedIn {
```
Comment (humblec) [inline pkg/volume/iscsi/iscsi_util.go]: How are we addressing the race condition here, I mean before we login another routine does login or we assume its already logged in and before performing next operation, it was logged out.

**Comment by redbaron** [comment]
@humblec I dont think it is necessary  and ideally multipathd would remove device once all paths are deleted. 

Removing device explicitly in the code has following benefits in my view:
 - it is less likely to trigger bugs in interaction between multipathd, udev and kernel. There are so many combination spanning  number of years in development between them, there bound to be differences in behaviour which hard to predict. 
 - it  generates much more visible kubelet log entry should  flush operation fail, for instance if device is still open for whatever reason
 - explicit is better than implicit. it is good to have code for every effect we anticipate to happen. Not everybody (==me) is fluent with iSCSI and things which are obvious once you dive deep in the topic might be surprising, when someone else try to debug another instance of odd behaviour.

File: pkg/volume/iscsi/iscsi_util.go [hunk 6]
```diff
@@ -242,12 +263,79 @@ func (util *ISCSIUtil) AttachDisk(b iscsiDiskMounter) (string, error) {
...
+				continue
+			}
+			out, err = b.exec.Run("iscsiadm", "-m", "discoverydb", "-t", "sendtargets", "-p", tp, "-I", b.Iface, "--discover")
+			if err != nil {
+				// delete discoverydb record
+				b.exec.Run("iscsiadm", "-m", "discoverydb", "-t", "sendtargets", "-p", tp, "-I", b.Iface, "-o", "delete")
+				lastErr = fmt.Errorf("iscsi: failed to sendtargets to portal %s output: %s, err %v", tp, string(out), err)
+				continue
+			}
+			err = updateISCSINode(b, tp)
```
Comment (humblec) [inline pkg/volume/iscsi/iscsi_util.go]: Does updateISCSIDIscoverydb() or updateISCSINode() can have a inconsistent view of portal map compared to iscsi db ?

File: pkg/volume/iscsi/iscsi_util.go (hunk 2 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: Fixed

File: pkg/volume/iscsi/iscsi_util.go (hunk 3 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: Fixed

File: pkg/volume/util/device_util_linux.go (hunk 4 above)
Comment (bswartz) [reply pkg/volume/util/device_util_linux.go]: Fixed

File: pkg/volume/iscsi/iscsi_util.go (hunk 5 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: I'm not sure the old code addressed that case. When I wrote this I had assumed there was locking at a higher level. I can add proper protection from races here in attach/detach but it will either require a Big Giant Lock or some very complex locking on the individual portals.

File: pkg/volume/iscsi/iscsi_util.go (hunk 6 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: I didn't write that code -- my changed just moved it. Based on what I know about iscsiadm, it stores some things in its databases, but probably not the SCSI hosts -- those it gets at runtime.

Are you worried about a new bug here, or are you considering an alternative implementation?

File: pkg/volume/iscsi/iscsi_util.go [hunk 7]
```diff
@@ -447,6 +547,22 @@ func (util *ISCSIUtil) DetachDisk(c iscsiDiskUnmounter, mntPath string) error {
...
+	if err = deleteDevices(c); err != nil {
+		glog.Warningf("iscsi detach disk: failed to delete devices\nError: %v", err)
+		// Fall through -- even if deleting fails, a logout may fix problems
+	}
+	cnt--
+	if cnt != 0 {
+		return nil
+	}
+	// if device is no longer used, see if need to logout the target
+	refCount, err := getDevicePrefixRefCount(c.mounter, prefix)
```
Comment (redbaron) [inline pkg/volume/iscsi/iscsi_util.go]: not sure if it is in scope of this PR, but IMHO kubelet shouldn't try to logout from iSCSI target. iSCSI session could be initiated at the host level before kubelet starts, logging out would yank iSCSI devices which are needed for host, but not needed by kubelet.

Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: This is a reasonable point, but the counter argument is that if kubelet never logs out of sessions, then we will leak iscsi sessions over time. Some storage controllers (Solidfire, for example) create a new session for each PV, so over the course of several weeks of running workloads, hundreds or thousands of defunct iSCSI sessions could accumulate.

It think it's better to document that, if you're using iSCSI for the root FS or some other host service that kubernetes doesn't know about, it must not share the iSCSI session with any storage backend. It would not be hard for an admin to set up multiple iSCSI targets to avoid that type of sharing.

**Comment by rootfs** [comment]
@bswartz following up. Some volumes prevent simultaneous setup and teardown. Please find an example [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder.go#L70)

**Comment by redbaron** [comment]
It would be really good  to see it in 1.11. @rootfs , @saad-ali do you think it is possible to add it to the milestone?

File: pkg/volume/iscsi/iscsi_util.go [hunk 8]
```diff
@@ -438,6 +544,22 @@ func (util *ISCSIUtil) DetachDisk(c iscsiDiskUnmounter, mntPath string) error {
 		// Logout may fail as no session may exist for the portal/IQN on the specified interface.
 		iface, found = extractIface(mntPath)
 	}
+
+	// Delete all the scsi devices and any multipath devices after unmounting
+	if err = deleteDevices(c); err != nil {
+		glog.Warningf("iscsi detach disk: failed to delete devices\nError: %v", err)
+		// Fall through -- even if deleting fails, a logout may fix problems
+	}
+	cnt--
```
[the remark this answers is not in the document]
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: Thanks, I was too hasty with my rebase and I didn't test it

**Comment by redbaron** [comment]
@bswartz , closed? :-/

**Comment by bswartz** [comment]
@redbaron Sorry it looks like I keep fat-fingering my git pushes, and I somehow pushed master instead of the bugfix branch. I need to figure out how to reopen this.

**Comment by bswartz** [comment]
Okay I finally sorted out the branch.

**Comment by redbaron** [comment]
1.11 has been released without this fix included :(   I don't even know who to CC to ask to track it for 1.12 :(

**Comment by redbaron** [comment]
@mohammedzee1000 , I saw you were adding milestone 1.12 to other tickets, how this issue can be added to a future release to be tracked?  I fear without it it is going to rot forever

**Comment by jsafrane** [comment]
@humblec @rootfs, I don't see any serious objections and this PR seems to fix a real problem. Any objections against merging it?

File: pkg/volume/iscsi/iscsi_util.go [hunk 9]
```diff
@@ -394,6 +448,67 @@ func globalPDPathOperation(b iscsiDiskMounter) func(iscsiDiskMounter, string, *I
 	}
 }
 
+// Delete 1 block device of the form "sd*"
+func deleteDevice(deviceName string) error {
+	filename := fmt.Sprintf("/sys/block/%s/device/delete", deviceName)
+	fd, err := os.OpenFile(filename, os.O_WRONLY, 0)
+	if err != nil {
+		return err
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: if the file doesn't exit, the device is already gone, don't error out here.

File: pkg/volume/iscsi/iscsi_util.go [hunk 10]
```diff
@@ -212,6 +213,26 @@ func (util *ISCSIUtil) loadISCSI(conf *iscsiDisk, mnt string) error {
...
+// scanLun scans a single LUN on one SCSI bus
+func scanLun(hostNumber int, lunNumber int) error {
+	filename := fmt.Sprintf("/sys/class/scsi_host/host%d/scan", hostNumber)
+	fd, err := os.OpenFile(filename, os.O_WRONLY, 0)
+	if err != nil {
+		return err
+	}
+	defer fd.Close()
+
+	scanCmd := fmt.Sprintf("0 0 %d", lunNumber)
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: why `0 0 l`? if the channel and target are not 0, 0, this won't work. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/online_storage_reconfiguration_guide/adding_storage-device-or-path

does this function help? https://github.com/NetApp/kubernetes/blob/04cac2212bdfa65ce717cf72242a189d96878352/pkg/volume/fc/fc_util.go#L123

File: pkg/volume/util/device_util_linux.go [hunk 11]
```diff
@@ -80,3 +83,206 @@ func (handler *deviceHandler) FindSlaveDevicesOnMultipath(dm string) []string {
...
+			}
+		}
+	}
+
+	return portalHostMap, nil
+}
+
+// FindDevicesForLun given an iqn, and lun number, find all the devices
+// corresponding to that LUN.
+func (handler *deviceHandler) FindDevicesForLun(targetIqn string, lun int) ([]string, error) {
```
Comment (rootfs) [inline pkg/volume/util/device_util_linux.go]: nit: `FindDevicesForISCSILun` since this is specific for iscsi

File: pkg/volume/util/device_util_linux.go [hunk 12]
```diff
@@ -80,3 +83,206 @@ func (handler *deviceHandler) FindSlaveDevicesOnMultipath(dm string) []string {
...
+	portalHostMap := make(map[string]int)
+	io := handler.get_io
+
+	// Iterate over all the iSCSI hosts in sysfs
+	sysPath := "/sys/class/iscsi_host"
+	hostDirs, err := io.ReadDir(sysPath)
+	if err != nil {
+		return nil, err
+	}
+	for _, hostDir := range hostDirs {
```
Comment (rootfs) [inline pkg/volume/util/device_util_linux.go]: Can [Glob](https://golang.org/pkg/path/filepath/#Glob) help to simply the flow here?

File: pkg/volume/util/device_util_linux.go [hunk 13]
```diff
@@ -80,3 +83,206 @@ func (handler *deviceHandler) FindSlaveDevicesOnMultipath(dm string) []string {
...
+	devices := make([]string, 0)
+	io := handler.get_io
+
+	// Iterate over all the iSCSI hosts in sysfs
+	sysPath := "/sys/class/iscsi_host"
+	hostDirs, err := io.ReadDir(sysPath)
+	if err != nil {
+		return nil, err
+	}
+	for _, hostDir := range hostDirs {
```
Comment (rootfs) [inline pkg/volume/util/device_util_linux.go]: same Glob question

**Comment by rootfs** [comment]
@bswartz thanks, some questions and nit. 

/approve

**Comment by rootfs** [comment]
status/approved-for-milestone

**Comment by bswartz** [comment]
@rootfs I think the command is "/status approved-for-milestone"

File: pkg/volume/iscsi/iscsi_util.go (hunk 10 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: The FC scan function you linked is equivalent to the old behavior, and is what causes the bug. Writing 3 hypens "- - -" to the scan file causes the SCSI subsystem to scan the whole bus, finding disks that are not relevant to the current attach operation. The whole point of this new method is that is scans only a single LUN. I can expand the comment to make this more clear.

File: pkg/volume/iscsi/iscsi_util.go (hunk 9 above)
Comment (bswartz) [reply pkg/volume/iscsi/iscsi_util.go]: Good point.

File: pkg/volume/util/device_util_linux.go (hunk 11 above)
Comment (bswartz) [reply pkg/volume/util/device_util_linux.go]: Will do

File: pkg/volume/util/device_util_linux.go (hunk 12 above)
Comment (bswartz) [reply pkg/volume/util/device_util_linux.go]: I'd have to write it both ways and compare the complexity. I suspect that using globs would make some of the parsing logic more complex, and also require a rewrite of the unit tests.

**Comment by bswartz** [comment]
Squashed 5 commits down to 1

**Comment by redbaron** [comment]
Big thanks to everybody who was involved fixing it
