### PR TITLE
test/e2e/node: tolerate exit code 2 in pod status flake

### LINKED ISSUE #135713: [Flaky test] [sig-node] Pods Extended Pod Container Status should never report container start when an init container fails
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-ipv6/1998907708706656256

### Which tests are flaking?

Kubernetes e2e suite.[It] [sig-node] Pods Extended Pod Container Status should never report container start when an init container fails

### Since when has it been flaking?

[2025-12-11 00:08:52 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-ipv6/1998907708706656256)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master

### Reason for failure (if possible)

{ failed [FAILED] 1 errors:
pod pod-terminate-status-0-6 on node kind-worker container unexpected exit code 2: start=2025-12-11 00:21:17 +0000 UTC end=2025-12-11 00:21:17 +0000 UTC reason=Error message=
In [It] at: k8s.io/kubernetes/test/e2e/node/pods.go:1381 @ 12/11/25 00:21:49.467
}

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig testing

### PR DESCRIPTION
**Pull request by dims**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The fast-delete pod status tests intentionally run a container that should fail and then verify the real invariant: the workload container must never start.

In CI, some runtimes occasionally surface that intentionally failing container with `exitCode: 2` and `reason: Error` instead of `exitCode: 1`, even though the pod state still satisfies the behavior under test. The latest `dims/test-k8s` failure showed exactly that: the pod stayed `Failed`, `Initialized=False`, the blocked container remained `started=false`, and only the failing init container drifted from exit code 1 to 2.

This change accepts that known flaky signature so the test keeps asserting the behavior it is actually meant to cover instead of a lower-layer exit-code detail.

Fixes #135713
Related-to #131605

#### Which issue(s) this PR fixes:
Fixes #135713

#### Special notes for your reviewer:
Public reproduction from `dims/test-k8s`:
- https://github.com/dims/test-k8s/actions/runs/23092972391

Local validation:
- `hack/verify-gofmt.sh`
- `hack/verify-test-code.sh`
- `hack/verify-typecheck.sh ./test/e2e/node/...`
- `go test ./test/e2e/node -run TestNonExistent -count=1`

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Public reproduction from test-k8s:
- dims/test-k8s alpha/beta kind run: https://github.com/dims/test-k8s/actions/runs/23092972391

This failed in `[sig-node] Pods Extended Pod Container Status should never report container start when an init container fails` with the tracked `unexpected exit code 2` signature on the intentionally failing container.

File: test/e2e/node/pods.go [hunk 1]
```diff
@@ -1001,6 +1001,9 @@ func (v *podStartVerifier) Verify(event watch.Event) error {
 		switch {
 		case t.ExitCode == 1:
 			// expected
+		case t.ExitCode == 2 && t.Reason == "Error":
```
Comment (SergeyKanzhelev) [inline test/e2e/node/pods.go]: @dims do you understand the reason for it? I remember looking into it and I don't think we ever got to the root cause for it. Same as comment from @BenTheElder : https://github.com/kubernetes/kubernetes/issues/131605#issuecomment-3664982241

I am fine ignoring it. But understanding it will be great. For example, can `/bin/true` return `2`?

File: test/e2e/node/pods.go [hunk 2]
```diff
@@ -1001,6 +1001,9 @@ func (v *podStartVerifier) Verify(event watch.Event) error {
...
+			// Some runtimes occasionally surface /bin/false as exit code 2 in these
+			// fast-delete scenarios. The test only cares that the container failed.
```
Comment (SergeyKanzhelev) [inline test/e2e/node/pods.go]: > fast-delete scenarios

there is no fast delete in test as I understand it. It is fast fail. But nothing makes it run faster or fail faster. It should just take it's time to get to the failure.

Should we say "fast fail" instead of "fast-delete" at a minimum?

File: test/e2e/node/pods.go (hunk 1 above)
Comment (BenTheElder) [reply test/e2e/node/pods.go]: /bin/true cannot

https://github.com/coreutils/coreutils/blob/master/src/true.c#L79

@samuelkarp any ideas?

Comment (liggitt) [reply test/e2e/node/pods.go]: seems like we should *really* understand why this increased in frequency significantly 5 days ago before we suppress it

Comment (SergeyKanzhelev) [reply test/e2e/node/pods.go]: @dims and @mikebrow looking into https://github.com/containerd/containerd/pull/13049

This PR is on hold to understand it

Comment (tallclair) [reply test/e2e/node/pods.go]: The real source of the exit code 2 is probably a pause container: https://github.com/kubernetes/kubernetes/blob/master/build/pause/linux/pause.c#L58

File: test/e2e/node/pods.go (hunk 2 above)
Comment (tallclair) [reply test/e2e/node/pods.go]: The "fast delete" is the action in the podFastDeleteScenario: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/node/pods.go#L845

File: test/e2e/node/pods.go (hunk 1 above)
Comment (liggitt) [reply test/e2e/node/pods.go]: there's a working theory (https://github.com/kubernetes/kubernetes/issues/135713#issuecomment-4092666900) that when the stop races with the actual underlying `runc create`, an exit code of 2 can result

the PLEGOnDemand feature makes the kubelet react instantly to delete requests instead of coalescing them on a 2 second poll boundary, so makes a fast create-then-delete much more likely to translate into a race between runc creating and stopping the container

once we prove this is what is happening, tolerating a slightly different non-zero exit here seems ~ok to me (even if we want to pursue improving containerd / runc to produce a more consistent error code in that scenario)

Comment (liggitt) [reply test/e2e/node/pods.go]: it's looking more and more like runc handling of the term signal prior to handoff to the underlying process is the cause of the 2 exit code, I think this PR to add that to the list of non-zero exit codes we accept is fine.

Maybe also limit this to the `t.Message == ""` case? If some other non-empty message shows up that doesn't match this pattern, we don't want to ignore it

```suggestion
		case t.ExitCode == 2 && t.Reason == "Error" && t.Message == "":
```

Comment (liggitt) [reply test/e2e/node/pods.go]: This is the shape of the container status in this scenario, with no message set:

```
  "containerStatuses": [
    {
      "name": "fail",
      "state": {
        "terminated": {
          "exitCode": 2,
          "reason": "Error",
          "startedAt": "2026-03-21T00:57:40Z",
          "finishedAt": "2026-03-21T00:57:40Z",
          "containerID": "containerd://802462ca937c705a039ef991ea1b4fa25fb0bb92f4515aa08dcd920ffd9fb9ae"
        }
      },
```

File: test/e2e/node/pods.go (hunk 2 above)
Comment (liggitt) [inline test/e2e/node/pods.go]: let's also log that this is happening (similar to the reBug88766 logging below), and point to a specific runc issue with details

File: test/e2e/node/pods.go [hunk 3]
```diff
@@ -1001,6 +1001,9 @@ func (v *podStartVerifier) Verify(event watch.Event) error {
 		switch {
 		case t.ExitCode == 1:
 			// expected
+		case t.ExitCode == 2 && t.Reason == "Error":
+			// Some runtimes occasionally surface /bin/false as exit code 2 in these
```
Comment (liggitt) [inline test/e2e/node/pods.go]:
```suggestion
			// Some runtimes occasionally surface exit code 2 if stopped before execve makes it to launching /bin/false in
```

Comment (dims) [reply test/e2e/node/pods.go]: Fixed both @liggitt

File: test/e2e/node/pods.go (hunk 2 above)
Comment (dims) [reply test/e2e/node/pods.go]: Done
