### PR TITLE
fix flaky test:  ResourceQuota should verify ResourceQuota with terminating scopes through scope selectors

### LINKED ISSUE #131834: Failure cluster [0772932a...]: ResourceQuota should verify ResourceQuota with terminating scopes through scope selectors.
##### Error text:
```
[FAILED] pods "terminating-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1611 @ 05/16/25 15:37:16.803

```
#### Recent failures:
[5/18/2025, 6:42:33 AM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1923962387451351040)
[5/18/2025, 6:38:24 AM ci-kubernetes-e2e-kind-alpha-beta-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1923961129487306752)
[5/18/2025, 4:03:25 AM ci-kubernetes-kind-ipv6-e2e-parallel](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1923922121751269376)
[5/18/2025, 4:01:33 AM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1923921870046892032)
[5/18/2025, 3:18:33 AM ci-kubernetes-e2e-prow-canary](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-prow-canary/1923911048969064448)

/kind failing-test
/kind flake
/sig api-machinery

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

After pod1 (terminating scope) is deleted, the quota will be updated by controller. We need to wait for this change. I wanted to wait for the terminating quota to be updated, not the non-terminating one because we have checked it before deleting the pod1 when I wrote that PR.

#### Which issue(s) this PR fixes:

Fixes #131834

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/apimachinery/resource_quota.go [hunk 1]
```diff
@@ -1613,7 +1607,7 @@ var _ = SIGDescribe("ResourceQuota", func() {
 		usedResources[v1.ResourceRequestsMemory] = resource.MustParse("0")
 		usedResources[v1.ResourceLimitsCPU] = resource.MustParse("0")
 		usedResources[v1.ResourceLimitsMemory] = resource.MustParse("0")
-		err = waitForResourceQuota(ctx, f.ClientSet, f.Namespace.Name, resourceQuotaNotTerminating.Name, usedResources)
+		err = waitForResourceQuota(ctx, f.ClientSet, f.Namespace.Name, resourceQuotaTerminating.Name, usedResources)
```
Comment (pohly) [inline test/e2e/apimachinery/resource_quota.go:1610]: This is what I suspected.

/lgtm
/approve

**Review by hashim21223445 — APPROVED** [review]
