### PR TITLE
Fix PullImage and add corresponding node e2e test

### LINKED ISSUE #24101: Pod in RunContainerError Status
I am using image `gcr.io/mixia-kube/udptest:v1`. The pod event shows `Successfully pulled image "gcr.io/mixia-kube/udptest:v1"`. But I got to the node and found the image is not in `docker images` list. When I manually pull  the image, pod got created successfully.

This used to work for me. Not sure if anything changes with kubelet or gcr. 

```console
Name:		my-udp-rc-ld468
Namespace:	default
Node:		e2e-test-mixia-minion-9ou9/10.240.0.5
Start Time:	Mon, 11 Apr 2016 10:51:02 -0700
Labels:		app=udp
Status:		Pending
IP:		10.245.3.5
Controllers:	ReplicationController/my-udp-rc
Containers:
  udp-echo:
    Container ID:	
    Image:		gcr.io/mixia-kube/udptest:v1
    Image ID:		
    Port:		8888/UDP
    QoS Tier:
      memory:	BestEffort
      cpu:	Burstable
    Requests:
      cpu:			100m
    State:			Waiting
      Reason:			RunContainerError
    Ready:			False
    Restart Count:		0
    Environment Variables:	<none>
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-ic1hj:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-ic1hj
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  34s		34s		1	{default-scheduler }							Normal		Scheduled	Successfully assigned my-udp-rc-ld468 to e2e-test-mixia-minion-9ou9
  34s		7s		4	{kubelet e2e-test-mixia-minion-9ou9}	spec.containers{udp-echo}	Normal		Pulling		pulling image "gcr.io/mixia-kube/udptest:v1"
  33s		7s		4	{kubelet e2e-test-mixia-minion-9ou9}	spec.containers{udp-echo}	Normal		Pulled		Successfully pulled image "gcr.io/mixia-kube/udptest:v1"
  33s		7s		4	{kubelet e2e-test-mixia-minion-9ou9}	spec.containers{udp-echo}	Warning		Failed		Failed to create docker container with error: Error: No such image: gcr.io/mixia-kube/udptest:v1
  33s		7s		4	{kubelet e2e-test-mixia-minion-9ou9}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "udp-echo" with RunContainerError: "runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1"
```

kubelet.log:

```console
I0411 17:51:02.867797    3391 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-udp-rc-ld468", UID:"f4d5367c-000d-11e6-95cc-42010af00002", APIVersion:"v1", ResourceVersion:"252", FieldPath:"spec.containers{udp-echo}"}): type: 'Normal' reason: 'Pulling' pulling image "gcr.io/mixia-kube/udptest:v1"
I0411 17:51:02.869585    3391 config.go:155] body of failing http response: &{0xc820c4e640 {0 0} false <nil> 0x665ae0 0x665a80}
E0411 17:51:02.869642    3391 metadata.go:112] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
I0411 17:51:02.869684    3391 provider.go:91] Refreshing cache for provider: *gcp_credentials.dockerConfigUrlKeyProvider
I0411 17:51:02.871350    3391 config.go:155] body of failing http response: &{0xc820c4eac0 {0 0} false <nil> 0x665ae0 0x665a80}
E0411 17:51:02.871379    3391 metadata.go:124] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
I0411 17:51:03.046191    3391 kubelet.go:1237] container: default/my-udp-rc-ld468/udp-echo podIP: "10.245.3.5" creating hosts mount: true
I0411 17:51:03.046786    3391 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-udp-rc-ld468", UID:"f4d5367c-000d-11e6-95cc-42010af00002", APIVersion:"v1", ResourceVersion:"252", FieldPath:"spec.containers{udp-echo}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "gcr.io/mixia-kube/udptest:v1"
I0411 17:51:03.047303    3391 manager.go:625] Container default/my-udp-rc-ld468/udp-echo: setting entrypoint "[]" and command "[]"
E0411 17:51:03.049129    3391 manager.go:1915] Error running pod "my-udp-rc-ld468_default(f4d5367c-000d-11e6-95cc-42010af00002)" container "udp-echo": runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1
E0411 17:51:03.049180    3391 pod_workers.go:138] Error syncing pod f4d5367c-000d-11e6-95cc-42010af00002, skipping: failed to "StartContainer" for "udp-echo" with RunContainerError: "runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1"
I0411 17:51:03.049219    3391 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-udp-rc-ld468", UID:"f4d5367c-000d-11e6-95cc-42010af00002", APIVersion:"v1", ResourceVersion:"252", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "StartContainer" for "udp-echo" with RunContainerError: "runContainer: Error: No such image: gcr.io/mixia-kube/udptest:v1"
I0411 17:51:03.049234    3391 server.go:609] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"my-udp-rc-ld468", UID:"f4d5367c-000d-11e6-95cc-42010af00002", APIVersion:"v1", ResourceVersion:"252", FieldPath:"spec.containers{udp-echo}"}): type: 'Warning' reason: 'Failed' Failed to create docker container with error: Error: No such image: gcr.io/mixia-kube/udptest:v1
```

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes #24101. This is a bug introduced by #23506, since ref #23563.

The root cause of #24101 is described [here](https://github.com/kubernetes/kubernetes/issues/24101#issuecomment-208547623).

This PR
1) Fixes #24101 by decoding the messages returned during pulling image, and return error if any of the messages contains error.
2) Add the node e2e test to detect this kind of failure.
3) Get present check out of `ConformanceImage.Remove()` and `ConformanceImage.Pull()`. Because sometimes we may expect error to occur in `PullImage()` and `RemoveImage()`, but even that doesn't happen, the `Present()` check will still return error and let the test pass.

@yujuhong @freehan @liangchenye 

Also /cc @resouer, because he is doing the image related functions refactoring.

### CODE REVIEW

File: test/e2e_node/conformance_test.go [hunk 1]
```diff
@@ -72,30 +77,43 @@ var _ = Describe("Container Conformance Test", func() {
...
+					present, err := image.Present()
+					Expect(err).NotTo(HaveOccurred())
+					Expect(present).To(BeFalse())
 				}
 			})
 		})
 		Context("when testing image that does not exist", func() {
-			var invalidImage ConformanceImage
-			var invalidImageTag string
 			It("it should not pull successfully [Conformance]", func() {
```
Comment (yujuhong) [inline test/e2e_node/conformance_test.go]: Remove "it": 
`It("should not pull`

File: test/e2e_node/conformance_test.go [hunk 2]
```diff
@@ -72,30 +77,43 @@ var _ = Describe("Container Conformance Test", func() {
...
+					err := invalidImage.Pull()
+					Expect(err).Should(HaveOccurred())
+
+					By("check image present")
+					present, err := invalidImage.Present()
+					Expect(err).ShouldNot(HaveOccurred())
+					Expect(present).To(BeFalse())
+
+					By("listing image")
+					tags, err := invalidImage.List()
```
Comment (yujuhong) [inline test/e2e_node/conformance_test.go]: The `ConformanceImage.List()` method is a little bit confusing but it's not really part of this PR...

BTW, I don't think we need to check image listing, but I'd be okay if you want to keep it.

**Comment by yujuhong** [comment]
Looks good overall with some nits.

File: test/e2e_node/conformance_test.go (hunk 1 above)
Comment (Random-Liu) [inline test/e2e_node/conformance_test.go]: ACK

File: test/e2e_node/conformance_test.go (hunk 2 above)
Comment (Random-Liu) [inline test/e2e_node/conformance_test.go]: @yujuhong I think @liangchenye just want to cover all the image related methods in the runtime interface. I'll leave this to him~ :)

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments. Thanks for reviewing! :)
