### PR TITLE
set umask on linux and darwin when testing kubeadm copycerts

### LINKED ISSUE #104265: `k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts` `TestDownloadCerts` fails
#### Which jobs are failing:

Running `make test` locally.

#### Which test(s) are failing:

`k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts` `TestDownloadCerts`

#### Since when has it been failing:

Today?

#### Testgrid link:

There is none, but I'm not filing this as a flaking test because it's a dependable failure, not a flake.

#### Reason for failure:

I suspect this depends on the user's umask given the error:
```
--- FAIL: TestDownloadCerts (0.15s)
    copycerts_test.go:255: cert "ca.crt" should have mode 0644, has 0640
    copycerts_test.go:255: cert "front-proxy-ca.crt" should have mode 0644, has 0640
    copycerts_test.go:255: cert "sa.pub" should have mode 0644, has 0640
    copycerts_test.go:255: cert "etcd/ca.crt" should have mode 0644, has 0640
FAIL
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts	0.612s
ok  	k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd	(cached)
```

#### Anything else we need to know:
originally https://github.com/kubernetes/kubernetes/issues/102607#issuecomment-895753987

/area kubeadm
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Makes the kubeadm copycerts unit tests independent of the system umask.

#### Which issue(s) this PR fixes:

Fixes #104265

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Tested on Linux and macOS locally.

File: cmd/kubeadm/app/phases/copycerts/testutil_umask.go [hunk 1]
```diff
@@ -0,0 +1,27 @@
+//+build darwin linux
```
Comment (pacoxu) [inline cmd/kubeadm/app/phases/copycerts/testutil_umask.go:1]:
```
+++ b/cmd/kubeadm/app/phases/copycerts/testutil_umask.go
@@ -1,4 +1,4 @@
-//+build darwin linux
+// +build darwin linux

+++ b/cmd/kubeadm/app/phases/copycerts/testutil_umask_noop.go
@@ -1,4 +1,4 @@
-//+build !darwin,!linux
+// +build !darwin,!linux
```

Comment (BenTheElder) [reply cmd/kubeadm/app/phases/copycerts/testutil_umask.go:1]: I will appease the robots! 🙃

File: cmd/kubeadm/app/phases/copycerts/testutil_umask.go [hunk 2]
```diff
@@ -0,0 +1,27 @@
+// +build darwin linux
```
Comment (BenTheElder) [inline cmd/kubeadm/app/phases/copycerts/testutil_umask.go:1]: there's no `// +build unix` (I hallucinated it I swear) and we don't currently actively support platforms other than these + windows, with these two being the only known platforms we support that do. 

I didn't find many comparable examples in the existing codebase, mostly code that targets linux or windows specifically (for e.g. kubelet).

File: cmd/kubeadm/app/phases/copycerts/testutil_umask_noop.go [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package copycerts
+
+func setNoUmask() {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/copycerts/testutil_umask_noop.go:21]: Like i've mentioned on the issue these file mask unit tests are broken on windows, since the OS simply does not have mode bits for files. Some of the go stdlib logic is no-op on windows. I think we cross compile the kubeadm binary for windows, but we never run unit tests on windows.
If we do, this change is accurate and probably more tests would fail in cmd/kubeadm.

Thanks
/approve
/triage accepted
/priority backlog
@pacoxu please apply LGTM given you were already reviewing.

Comment (BenTheElder) [reply cmd/kubeadm/app/phases/copycerts/testutil_umask_noop.go:21]: Yeah, I think maybe some limited windows unit test running occurs, but not in CI or the release and I would be surprised if it didn't have many issues similar to https://github.com/kubernetes/kubernetes/issues/102607 already ...
