### PR TITLE
Use force umount for nfs volumes

### LINKED ISSUE #96678: Use force unmount for nfs if regular unmount fails
This is a long standing issue and we  did not manage to come to a conclusion before -  https://github.com/kubernetes/kubernetes/pull/72049/files

But previously the problem was changes to umount code was affecting all volume drivers and not just NFS but I think a localized fix to just NFS intree driver is reasonable which uses regular umount first and if that fails it uses force unmount. 

Something like this was done in https://github.com/openshift/csi-driver-nfs/pull/31/files 

cc @kubernetes/sig-storage-bugs 

/sig storage

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://github.com/kubernetes/kubernetes/issues/96678

/sig storage

```release-note
Use force unmount for NFS volumes if regular mount fails after 1 minute timeout
```

### CODE REVIEW

**Comment by jingxu97** [comment]
One concern is unmount timeout might caused by different reasons, e.g.,
1. NFS server is down (lost network connection with server)
2. Some other process are using this dir

In case the 1, the recommended way is to use unmount with force. But how about the second case?

Normally the volume is only used by associated Pods. The workflow is to kill the containers which are using the volume, and then cleanup volumes. So in this aspect, maybe case 2 should not happen?

**Comment by jsafrane** [comment]
> 2. Some other process are using this dir

It is not possible to unmount a directory if something uses it, even with `-f`. You still get `device is busy`.

File: pkg/volume/nfs/nfs.go [hunk 1]
```diff
@@ -61,7 +62,8 @@ var _ volume.PersistentVolumePlugin = &nfsPlugin{}
 var _ volume.RecyclableVolumePlugin = &nfsPlugin{}
 
 const (
-	nfsPluginName = "kubernetes.io/nfs"
+	nfsPluginName  = "kubernetes.io/nfs"
+	unMountTimeout = time.Minute
```
Comment (jingxu97) [inline pkg/volume/nfs/nfs.go:66]: just want to double check whether this is optimal timeout setting in this case..

File: staging/src/k8s.io/mount-utils/mount_helper_common.go [hunk 2]
```diff
@@ -40,6 +41,39 @@ func CleanupMountPoint(mountPath string, mounter Interface, extensiveMountPointC
 	return doCleanupMountPoint(mountPath, mounter, extensiveMountPointCheck, corruptedMnt)
 }
 
+func CleanupMountWithForce(mountPath string, mounter MounterForceUnmounter, extensiveMountPointCheck bool, umountTimeout time.Duration) error {
+	pathExists, pathErr := PathExists(mountPath)
+	if !pathExists {
+		klog.Warningf("Warning: Unmount skipped because path does not exist: %v", mountPath)
+		return nil
+	}
+	corruptedMnt := IsCorruptedMnt(pathErr)
```
Comment (jingxu97) [inline staging/src/k8s.io/mount-utils/mount_helper_common.go:50]: At this point, pathExists == true. Based on the logic of PathExists, only two cases
1. pathExists and error == nil
2. if error != nil, then is must be corruptedMnt == true

So I think there is no need to check IsCorruptedMnt again here ..

File: pkg/volume/nfs/nfs.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/nfs/nfs.go:66]: there is no 100% sure way to know the answer. We have deployed some CSI driver with this value and it appears to be working fine. Unlike block devices - NFS volumes don't have to fsync on umount, so I think it should be fine.

File: staging/src/k8s.io/mount-utils/mount_helper_common.go (hunk 2 above)
Comment (gnufied) [reply staging/src/k8s.io/mount-utils/mount_helper_common.go:50]: hmm, good point. but I think there is a logic error in this code. 

1. If pathExists is false and `pathErr` is nil. then and then only it should skip unmounting. 
2. If pathExists is false but `pathErr` is somehow nil-nil, then unmounting should not succeed and should result in error and I think we have had this bug in the code for awhile now. :(

I have pushed an update that fixes this PTAL.

File: staging/src/k8s.io/mount-utils/mount_helper_common.go [hunk 3]
```diff
@@ -40,6 +41,39 @@ func CleanupMountPoint(mountPath string, mounter Interface, extensiveMountPointC
...
+	if pathErr != nil && !corruptedMnt {
+		return fmt.Errorf("Error checking path: %v", pathErr)
+	}
+	var notMnt bool
+	var err error
+	if !corruptedMnt {
+		_, err = removePathIfNotMountPoint(mountPath, mounter, extensiveMountPointCheck)
```
[the remark this answers is not in the document]
Comment (gnufied) [reply staging/src/k8s.io/mount-utils/mount_helper_common.go]: Can you update this comment. You have commented on a outdated diff and I have changed this code.

File: staging/src/k8s.io/mount-utils/mount_helper_common.go (hunk 2 above)
Comment (jingxu97) [reply staging/src/k8s.io/mount-utils/mount_helper_common.go:50]: Still feel there are some cleanup can be done related to the checking before and after actual unmount execution and path removal. Especially the checking logic before actually executing unmount or dir deletion has some issues. We have seen issues around this with some kind of corrupted dir (even though dir still exist, but PathExists show it does not..).  Also since pathExists has redundant check on IsCorruptedMnt. 

But this further cleanup can be done in a different PR. For this one, let's focus on adding Force option.

**Comment by jingxu97** [comment]
CleanupMountWithForce and CleanupMountPoint should have the exact logic except the former uses mounter.UnmountWithForce and latter uses mounter.Unmount() function. So do you think passing a parameter option e.g. "bool useForceUnmount" passed to CleanupMountPoint() function is easier?

**Comment by gnufied** [comment]
`CleanupMountPoint` function is part of public interface of mount utils package. It is used in many cases in k8s and potentially outside core k8s. I did not wanted to break any existing usage if I could help. But also it is just one boolean flag, we also have to potentially supply timeout. I think it is bit more cleaner to have separate function for this, so as we don't break existing usage.

File: staging/src/k8s.io/mount-utils/mount_helper_common.go (hunk 2 above)
Comment (gnufied) [reply staging/src/k8s.io/mount-utils/mount_helper_common.go:50]: Why do you say - `PathExists` has a redundant check of `IsCorruptedMnt`? But if it was - then I think it was always there and I am not changing any of that code. If anything - this PR I think fixes the bug with ignoring errors from `PathExists` check.

Comment (jingxu97) [reply staging/src/k8s.io/mount-utils/mount_helper_common.go:50]: got it.  for this change it is good for me.

File: staging/src/k8s.io/mount-utils/mount_linux.go [hunk 4]
```diff
@@ -573,3 +591,34 @@ func SearchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
...
+	}
+
+	if cmderr != nil {
+		return fmt.Errorf("unmount failed: %v\nUnmounting arguments: %s\nOutput: %s", cmderr, path, string(out))
+	}
+	return nil
+}
+
+func forceUmount(path string) error {
+	cmd := exec.Command("umount", "-f", path)
```
Comment (jingxu97) [inline staging/src/k8s.io/mount-utils/mount_linux.go:617]: so should we consider to have a timeout even for force unmount?

Comment (jingxu97) [reply staging/src/k8s.io/mount-utils/mount_linux.go:617]: the same question for normal Unmount function

**Comment by jingxu97** [comment]
just a coupe of questions which can be followed up later. 

This change is good for me.
/lgtm

File: staging/src/k8s.io/mount-utils/mount_linux.go (hunk 4 above)
Comment (gnufied) [reply staging/src/k8s.io/mount-utils/mount_linux.go:617]: > the same question for normal Unmount function.

For normal unmount it is bit problematic to change behaviour for all existing drivers. As we know that some storage types flush pending writes when a volume is unmounted - and hence unmount time could vary and it is not safe to kill unmount process when this happens. So I think we never want to use a universal timeout for normal unmount function for all drivers. 

> so should we consider to have a timeout even for force unmount?

force works best for unreachable NFS system. It is documented directly in the man page. But it is not guaranteed to not hang  and as far as I know if it hangs in other cases, it could be hanging for a legitimate reason (such as volume being used or something else) and in those cases using a timeout will basically kill the unmount process and it could be problematic. So, I think I would not want to use a timeout for force unmount. It could result in a leaked goroutine but that is okay, we always leaked goroutines in this code paths.
