### PR TITLE
made independent test cases ginkgo.It for checking connectivity

### LINKED ISSUE #107078: Remove or parameterize google.com from test cases
### What happened?

We added pinging google.com to the original E2Es, however in airgapped environments, these tests fail for obvious reasons:

```
Get http://google.com: dial tcp: lookup google.com on 192.48.0.10:53: server misbehaving
```

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/hybrid_network.go 
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns.go

In general, we need to parameterize this if possible.

### What did you expect to happen?

Running the `sig-network` or `sig-windows` tests should pass in air-gapped environments, especially those that dont explicitly declare external connectivity.  
For example:

```

[sig-network] Networking Granular Checks: Services 
  should function for client IP based session affinity: udp [LinuxOnly]
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:283
[BeforeEach] [sig-network] Networking
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:178
STEP: Creating a kubernetes client
Dec 15 06:29:14.990: INFO: >>> kubeConfig: /tmp/kubeconfig-609614051
STEP: Building a namespace api object, basename nettest
STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in nettest-7422
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Networking
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:94
STEP: Executing a successful http request from the external internet
Dec 15 06:29:19.125: FAIL: Unable to connect/talk to the internet: Get http://google.com: dial tcp: lookup google.com on 192.48.0.10:53: server misbehaving
```

### How can we reproduce it (as minimally and precisely as possible)?

Run the `sig-network` test suites inside of a kuberentes cluster which has no internet connection.

```
sonobuoy run --e2e-focus=“sig-network” --e2e-skip="Distruptive|Slow|ExternalLoadBalancer"
```

### Anything else we need to know?

pointing finger at @rrati :)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?
Bug Fixer

#### What this PR does / why we need it:
made independent test cases ginkgo.It for checking internet connectivity for Windows and Linux nodes.
#### Which issue(s) this PR fixes:

Fixes #107078

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/windows/hybrid_network.go [hunk 1]
```diff
@@ -37,7 +38,7 @@ const (
 
 var (
 	windowsBusyBoximage = imageutils.GetE2EImage(imageutils.Agnhost)
-	linuxBusyBoxImage   = imageutils.GetE2EImage(imageutils.Nginx)
+	linuxBusyBoxImage   = imageutils.GetE2EImage(imageutils.BusyBox)
```
Comment (aojea) [inline test/e2e/windows/hybrid_network.go:41]: I understand why it fails now, the busybox image requires to set a `sleep` command or the containers crash loops

Comment (aojea) [reply test/e2e/windows/hybrid_network.go:41]: bring back the previous image by now, I'll figure it out later

**Comment by aojea** [comment]
/lgtm

Thanks for your patience @NikhilSharmaWe , there was a lot of hidden issues here :upside_down_face: 

/assign @claudiubelu @jsturtevant 

Claudiu , James , this makes these test consistent with the sig-network tests and users can skip the test that require internet connectivity with a simple regex like `-skip should provide Internet connection`

I defer to you the approval since these are in the sig-windows folder

File: test/e2e/windows/hybrid_network.go [hunk 2]
```diff
@@ -79,6 +72,28 @@ var _ = SIGDescribe("Hybrid cluster network", func() {
...
 
+		ginkgo.It("should provide Internet connection for containers using DNS [Feature:Networking-DNS]", func() {
+			linuxPod := createTestPod(f, linuxBusyBoxImage, linuxOS)
+			ginkgo.By("creating a linux pod and waiting for it to be running")
+			linuxPod = f.PodClient().CreateSync(linuxPod)
+
+			ginkgo.By("verifying pod external connectivity to the internet")
+
+			ginkgo.By("checking connectivity to 8.8.8.8 53 (google.com) from Linux")
+			assertConsistentConnectivity(f, linuxPod.ObjectMeta.Name, linuxOS, linuxCheck("8.8.8.8", 53))
```
Comment (claudiubelu) [inline test/e2e/windows/hybrid_network.go:83]: Hmm, I'm not sure why we had ``assertConsistentConnectivity`` from the Linux container to ``8.8.8.8`` before, but I think it would make more sense to have it from the Windows container to ``8.8.8.8`` instead, since this is ``test/e2e/windows`` after all.

Comment (NikhilSharmaWe) [reply test/e2e/windows/hybrid_network.go:83]: @claudiubelu as it is mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/hybrid_network.go#L52) that here we are checking internet connectivity for both Windows and Linux pods that's why have` assertConsistentConnectivity from the Linux container to 8.8.8.8`. Please correct me if I am wrong here. And also thanks for your input.

Comment (aojea) [reply test/e2e/windows/hybrid_network.go:83]: I was confused at the beginning too, but seems this whole test block is for hybrid, not windows only

Comment (claudiubelu) [reply test/e2e/windows/hybrid_network.go:83]: > @claudiubelu as it is mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/hybrid_network.go#L52) that here we are checking internet connectivity for both Windows and Linux pods that's why have `assertConsistentConnectivity from the Linux container to 8.8.8.8`. Please correct me if I am wrong here. And also thanks for your input.

Right, but in that case, it was testing Linux -> Internet (8.8.8.8), Windows -> Internet (google.com), and after that Linux -> Windows, and then Windows -> Linux. After all, I think it made sense in that scenario; it was a good idea to make sure both Linux and Windows network connections were properly set up before testing the Linux - Windows connection. If you'd test the Linux - Windows connection directly and it'd fail, you wouldn't know who's fault it is.

Looking back in history, the most important part is testing out the Linux -> Windows and Windows -> Linux connectivity (https://github.com/kubernetes/kubernetes/issues/74377), the other checks were made to ensure networking works in both pods in the first place. I don't think that connecting to 8.8.8.8 or google.com is relevant for the test, IMO. I think connecting to the Kubernetes API instead should be sufficient. @jayunit100 , what do you think?

Comment (aojea) [reply test/e2e/windows/hybrid_network.go:83]: > , it was testing Linux -> Internet (8.8.8.8), Windows -> Internet (google.com), and after that Linux -> Windows, and then Windows -> Linux. After all, I think it made sense in that scenario; it was a good idea to make sure both Linux and Windows network connections were properly set up before testing the Linux - Windows connection.

> the other checks were made to ensure networking works in both pods in the first place

internet connectivity from pods doesn't guarantee that intra-pod communication works, internet connectivity should be a separate test case that can be filtered,  this is why the bug was opened, doesn't it?

Comment (BenTheElder) [reply test/e2e/windows/hybrid_network.go:83]: right, we want to test both of these things. In some contexts it makes sense not to expect internet connectivity, but it is a useful check to see that we didn't royally break something in say, kube-proxy :-)

putting external network connectivity in a separate tagged test will allow excluding them in environments where the test failing is working as intended

**Comment by NikhilSharmaWe** [comment]
@BenTheElder @aojea 
Could you please give some info about what should be done in this PR further. This PR is inactive for 2 months now, it would be nice to accomplish for what this PR was formed.

**Comment by aojea** [comment]
> @BenTheElder @aojea Could you please give some info about what should be done in this PR further. This PR is inactive for 2 months now, it would be nice to accomplish for what this PR was formed.

it depends on sig-windows  now

**Comment by NikhilSharmaWe** [comment]
@jsturtevant Could you please confirm the changes made in this PR (as reviewers above mentioned the PR depends on sig-windows now).

File: test/e2e/windows/hybrid_network.go [hunk 3]
```diff
@@ -79,6 +72,28 @@ var _ = SIGDescribe("Hybrid cluster network", func() {
 
 		})
 
+		ginkgo.It("should provide Internet connection for containers using DNS [Feature:Networking-DNS]", func() {
```
Comment (jsturtevant) [inline test/e2e/windows/hybrid_network.go:75]:
```suggestion
		ginkgo.It("should provide Internet connection for Linux containers using DNS [Feature:Networking-DNS]", func() {
```

File: test/e2e/windows/hybrid_network.go [hunk 4]
```diff
@@ -79,6 +72,28 @@ var _ = SIGDescribe("Hybrid cluster network", func() {
...
+			ginkgo.By("creating a linux pod and waiting for it to be running")
+			linuxPod = f.PodClient().CreateSync(linuxPod)
+
+			ginkgo.By("verifying pod external connectivity to the internet")
+
+			ginkgo.By("checking connectivity to 8.8.8.8 53 (google.com) from Linux")
+			assertConsistentConnectivity(f, linuxPod.ObjectMeta.Name, linuxOS, linuxCheck("8.8.8.8", 53))
+		})
+
+		ginkgo.It("should provide Internet connection for containers using DNS [Feature:Networking-DNS]", func() {
```
Comment (jsturtevant) [inline test/e2e/windows/hybrid_network.go:86]:
```suggestion
		ginkgo.It("should provide Internet connection for Windows containers using DNS [Feature:Networking-DNS]", func() {
```

**Review by jsturtevant — CHANGES_REQUESTED** [review]
The tests cases for linux and windows would have the same test name.  I think this would be confusing so suggested a minor update

**Comment by jsturtevant** [comment]
Flakes are not related
/retest

/lgtm 
/approve
