### PR TITLE
Fix TerminationGracePeriodSeconds is negative (part 1)

### LINKED ISSUE #98506: Force deleting pods not working after deletionGracePeriodSeconds set to a negative value
**What happened**:
Some k8s client tried to evict a pod by setting negative value for deletionGracePeriodSeconds. But all eventual delete calls (and force-delete calls) made by kubelet, pod-garbage-collector, etc were not able to delete that pod, because apiserver doesnt allow deletionGracePeriodSeconds to be increased once it is set. So force-delete (which set it to 0) doesn't take effect when it's already negative. Not even kubectl is able to call delete with negative grace-period. But curl with an even more negative grace-period value worked.

**What you expected to happen**:
force-delete works.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I think the issue is in the code below

```
	if objectMeta.GetDeletionTimestamp() != nil {
		// if we are already being deleted, we may only shorten the deletion grace period
		// this means the object was gracefully deleted previously but deletionGracePeriodSeconds was not set,
		// so we force deletion immediately
		// IMPORTANT:
		// The deletion operation happens in two phases.
		// 1. Update to set DeletionGracePeriodSeconds and DeletionTimestamp
		// 2. Delete the object from storage.
		// If the update succeeds, but the delete fails (network error, internal storage error, etc.),
		// a resource was previously left in a state that was non-recoverable.  We
		// check if the existing stored resource has a grace period as 0 and if so
		// attempt to delete immediately in order to recover from this scenario.
		if objectMeta.GetDeletionGracePeriodSeconds() == nil || *objectMeta.GetDeletionGracePeriodSeconds() == 0 {
			return false, false, nil
		}
		// only a shorter grace period may be provided by a user
		if options.GracePeriodSeconds != nil {
			period := int64(*options.GracePeriodSeconds)
			if period >= *objectMeta.GetDeletionGracePeriodSeconds() {
				return false, true, nil
			}
```

https://github.com/kubernetes/apiserver/blame/d4c9a195921609cf81e3e950beaf246f934e0f4c/pkg/registry/rest/delete.go#L96-L110

As the comment suggest, in phase 1, the `DeletionGracePeriodSeconds` was set to a negative value (meaning `DeletionTimestamp` was **in the past**), and in phase 2, `options.GracePeriodSeconds` has to be set even lower, otherwise, it will be considered as pending graceful deletion and not performing the immediate delete. 

I think there're two possible fixes. 

1. Consider not allowing setting `DeletionTimestamp` in the past (`DeletionGracePeriodSeconds` should be non-negative). In that case, we could convert `options.GracePeriodSeconds` to 0 if negative. 
2. Accept that `DeletionTimestamp` could be set in the past. In that case, in phase 2, we treat negative value of `objectMeta.GetDeletionGracePeriodSeconds()` the same as 0, and allow immediate delete. 

Thoughts? 

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**

/kind bug
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #98506
xref #98507
xref #103476

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
ACTION REQUIRED: TerminationGracePeriodSeconds on pod specs and container probes should not be negative.
Negative values of TerminationGracePeriodSeconds will be treated as the value `1s` on the delete path.
Immutable field validation will be relaxed in order to update negative values. 
In a future release, negative values will not be permitted.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 1]
```diff
@@ -638,6 +638,9 @@ func (m *kubeGenericRuntimeManager) killContainer(pod *v1.Pod, containerID kubec
 	}
 	if gracePeriodOverride != nil {
 		gracePeriod = *gracePeriodOverride
+		if gracePeriod < 0 {
+			gracePeriod = 0
```
Comment (rphillips) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:642]: In this case the gracePeriod is an error. It makes sense to me to default this back to the original value of gracePeriod instead of setting it to zero (which is no grace period).

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 2]
```diff
@@ -240,6 +240,9 @@ func (m *Manager) processShutdownEvent() error {
 			// If the pod's spec specifies a termination gracePeriod which is less than the gracePeriodOverride calculated, use the pod spec termination gracePeriod.
 			if pod.Spec.TerminationGracePeriodSeconds != nil && *pod.Spec.TerminationGracePeriodSeconds <= gracePeriodOverride {
 				gracePeriodOverride = *pod.Spec.TerminationGracePeriodSeconds
+				if gracePeriodOverride < 0 {
+					gracePeriodOverride = 0
```
Comment (rphillips) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:244]: ditto here.

**Review by rphillips — CHANGES_REQUESTED** [review]

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (rphillips) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:642]: There are a few more placed within the PR where the gracePeriodOveride should be ignored - on error - and the gracePeriod should be preserved.

Comment (wzshiming) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:642]: This is to deal with existing negative values, which have a meaning more like 0.

https://github.com/kubernetes/kubernetes/pull/98507#issuecomment-769327287
https://github.com/kubernetes/kubernetes/issues/98506#issuecomment-774598217
@liggitt recommended is clip to 0

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -3327,6 +3327,13 @@ func ValidatePodSpec(spec *core.PodSpec, podMeta *metav1.ObjectMeta, fldPath *fi
 		}
 	}
 
+	if spec.TerminationGracePeriodSeconds != nil {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3330]: This needs to deal with invalid existing persisted data. As-is, this would prevent any existing invalid pods from being deleted.

Comment (liggitt) [reply pkg/apis/core/validation/validation.go:3330]: something like this is needed to avoid invalidating existing data:

```diff
diff --git a/pkg/api/pod/util.go b/pkg/api/pod/util.go
index 27398b53fc4..0d28a5dbde3 100644
--- a/pkg/api/pod/util.go
+++ b/pkg/api/pod/util.go
@@ -319,6 +319,10 @@ func usesHugePagesInProjectedEnv(item api.Container) bool {
 	return false
 }
 
+func hasNegativeTerminationGracePeriodSeconds(podSpec *api.PodSpec) bool {
+	return podSpec.TerminationGracePeriodSeconds != nil && *podSpec.TerminationGracePeriodSeconds < 0
+}
+
 // usesMultipleHugePageResources returns true if the pod spec uses more than
 // one size of hugepage
 func usesMultipleHugePageResources(podSpec *api.PodSpec) bool {
@@ -345,6 +349,8 @@ func GetValidationOptionsFromPodSpec(podSpec, oldPodSpec *api.PodSpec) apivalida
 	if oldPodSpec == nil {
 		return opts
 	}
+	// if old spec had negative terminationGracePeriodSeconds, we must allow it
+	opts.AllowNegativeTerminationGracePeriodSeconds = hasNegativeTerminationGracePeriodSeconds(oldPodSpec)
 	// if old spec used multiple huge page sizes, we must allow it
 	opts.AllowMultipleHugePageResources = opts.AllowMultipleHugePageResources || usesMultipleHugePageResources(oldPodSpec)
 	// if old spec used hugepages in downward api, we must allow it
diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
index 8f6ce285ce5..68e540a5cad 100644
--- a/pkg/apis/core/validation/validation.go
+++ b/pkg/apis/core/validation/validation.go
@@ -3185,6 +3185,8 @@ type PodValidationOptions struct {
 	AllowMultipleHugePageResources bool
 	// Allow pod spec to use hugepages in downward API
 	AllowDownwardAPIHugePages bool
+	// Allow negative termination grace period seconds
+	AllowNegativeTerminationGracePeriodSeconds bool
 }
 
 // ValidatePodSingleHugePageResources checks if there are multiple huge
@@ -3327,7 +3329,7 @@ func ValidatePodSpec(spec *core.PodSpec, podMeta *metav1.ObjectMeta, fldPath *fi
 		}
 	}
 
-	if spec.TerminationGracePeriodSeconds != nil {
+	if !opts.AllowNegativeTerminationGracePeriodSeconds && spec.TerminationGracePeriodSeconds != nil {
 		value := *spec.TerminationGracePeriodSeconds
 		if value < 0 || value > math.MaxInt32 {
 			allErrs = append(allErrs, field.Invalid(fldPath.Child("terminationGracePeriodSeconds"), value, validation.InclusiveRangeError(0, math.MaxInt32)))
```

File: pkg/registry/core/pod/strategy.go [hunk 4]
```diff
@@ -133,6 +133,9 @@ func (podStrategy) CheckGracefulDelete(ctx context.Context, obj runtime.Object,
 		// use the default value if set, or deletes the pod immediately (0)
 		if pod.Spec.TerminationGracePeriodSeconds != nil {
 			period = *pod.Spec.TerminationGracePeriodSeconds
+			if period < 0 {
+				period = 0
+			}
```
Comment (liggitt) [inline pkg/registry/core/pod/strategy.go:138]: shouldn't this be moved to line 141 so it happens regardless of whether the value came from the request or the pod spec?

File: staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go [hunk 5]
```diff
@@ -90,6 +90,9 @@ func ValidateDeleteOptions(options *metav1.DeleteOptions) field.ErrorList {
 		*options.PropagationPolicy != metav1.DeletePropagationOrphan {
 		allErrs = append(allErrs, field.NotSupported(field.NewPath("propagationPolicy"), options.PropagationPolicy, []string{string(metav1.DeletePropagationForeground), string(metav1.DeletePropagationBackground), string(metav1.DeletePropagationOrphan), "nil"}))
 	}
+	if options.GracePeriodSeconds != nil && *options.GracePeriodSeconds < 0 {
```
Comment (liggitt) [inline staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go:93]: similarly, it's unclear what clients this will break. I would expect values less than zero to clip to zero

**Comment by liggitt** [comment]
the `BeforeDelete` implementation currently recalculates and updates DeletionGracePeriodSeconds:

https://github.com/kubernetes/kubernetes/blob/217a1c48531438ac2f4a202e828092a8ce19f4e6/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L105-L123

There are two things that need changing here (with unit tests that exercise each change):
* if the existing grace period is already less than zero we should delete immediately
* if the new period is less than zero we should clip to zero

```diff
diff --git a/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go b/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go
index 3e7ca85b761..7f90e5e18be 100644
--- a/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go
+++ b/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go
@@ -103,9 +103,9 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
 		// 2. Delete the object from storage.
 		// If the update succeeds, but the delete fails (network error, internal storage error, etc.),
 		// a resource was previously left in a state that was non-recoverable.  We
-		// check if the existing stored resource has a grace period as 0 and if so
+		// check if the existing stored resource has a grace period <= 0 and if so
 		// attempt to delete immediately in order to recover from this scenario.
-		if objectMeta.GetDeletionGracePeriodSeconds() == nil || *objectMeta.GetDeletionGracePeriodSeconds() == 0 {
+		if objectMeta.GetDeletionGracePeriodSeconds() == nil || *objectMeta.GetDeletionGracePeriodSeconds() <= 0 {
 			return false, false, nil
 		}
 		// only a shorter grace period may be provided by a user
@@ -113,10 +113,13 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
 			period := int64(*options.GracePeriodSeconds)
 			if period >= *objectMeta.GetDeletionGracePeriodSeconds() {
 				return false, true, nil
+			} else if period < 0 {
+				// clip to zero
+				period = 0
 			}
 			newDeletionTimestamp := metav1.NewTime(
 				objectMeta.GetDeletionTimestamp().Add(-time.Second * time.Duration(*objectMeta.GetDeletionGracePeriodSeconds())).
-					Add(time.Second * time.Duration(*options.GracePeriodSeconds)))
+					Add(time.Second * time.Duration(period)))
 			objectMeta.SetDeletionTimestamp(&newDeletionTimestamp)
 			objectMeta.SetDeletionGracePeriodSeconds(&period)
 			return true, false, nil
```

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 6]
```diff
@@ -103,20 +103,23 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
 		// 2. Delete the object from storage.
 		// If the update succeeds, but the delete fails (network error, internal storage error, etc.),
 		// a resource was previously left in a state that was non-recoverable.  We
-		// check if the existing stored resource has a grace period as 0 and if so
+		// check if the existing stored resource has a grace period <= 0 and if so
```
Comment (michaelgugino) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:106]: This is incorrect and not the desired behavior.  metav1.DeleteOptions.GracePeriodSeconds is allowed to be negative.  This should be interpreted as "use pod's value" and should be handled differently than GracePeriodSeconds in the podspec.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 7]
```diff
@@ -103,20 +103,23 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
...
 		// attempt to delete immediately in order to recover from this scenario.
-		if objectMeta.GetDeletionGracePeriodSeconds() == nil || *objectMeta.GetDeletionGracePeriodSeconds() == 0 {
+		if objectMeta.GetDeletionGracePeriodSeconds() == nil || *objectMeta.GetDeletionGracePeriodSeconds() <= 0 {
```
Comment (michaelgugino) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:108]: We don't want this change as we'll go from graceful to forceful shutdown with a negative number.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 8]
```diff
@@ -103,20 +103,23 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
...
 			return false, false, nil
 		}
 		// only a shorter grace period may be provided by a user
 		if options.GracePeriodSeconds != nil {
 			period := int64(*options.GracePeriodSeconds)
 			if period >= *objectMeta.GetDeletionGracePeriodSeconds() {
 				return false, true, nil
+			} else if period < 0 {
```
Comment (michaelgugino) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:116]: We don't want this behavior.

**Review by michaelgugino — CHANGES_REQUESTED** [review]
There are a few different things going on in this PR.

I'm not sure this change is safe to make.  In particular, the eviction API passes through the -1 value by default.  This is supposed to be interpreted as "use the pod's value".  Looking at the kubectl/delete command, it appears only values >= 0 are actually passed to the API, unlike eviction.

We need to investigate/sanitize this code path prior to implementing this change: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/pod/storage/eviction.go#L160

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 6 above)
Comment (liggitt) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:106]: > This should be interpreted as "use pod's value"

Where is that defined? I'm not seeing anything that passed -1 to the API to meant that

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 7 above)
Comment (liggitt) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:108]: A negative grace period passed to the delete API is not valid. 0 is the closest valid value, so is what I would expect.

Comment (liggitt) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:108]: A negative grace period passed to the delete API is not valid. 0 is the closest valid value, so is what I would expect.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 6 above)
Comment (michaelgugino) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:106]: Looks like you are correct: https://github.com/kubernetes/apimachinery/blob/v0.20.4/pkg/apis/meta/v1/types.go#L492

According to the API, it must be non-negative, so we should reject any call with a negative value rather than overwrite it.

Comment (liggitt) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:106]: > According to the API, it must be non-negative, so we should reject any call with a negative value rather than overwrite it.

Accepting calls and trimming to 0 is more compatible. If there are clients issuing deletes with a -1, actually deleting the resource is closer to the intent than letting it hang forever or requiring an update to the API client.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 7 above)
Comment (michaelgugino) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:108]: I disagree.  If you were looking at the drain command as a reference rather than the API and missed the bit where only non-negative integers are passed, you might assume that sending a negative is valid: https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/drain/drain.go#L194

To me, a negative value is clearly intended to use the pod's default value.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 6 above)
Comment (michaelgugino) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:106]: If the API says non-negative only, we should reject, otherwise the API documentation is wrong, at the very least we should update it.

As I mentioned in my other comment, negative values are probably an indication that someone want's the pod's default value rather than a 'delete now' value.  If they wanted to delete now, they would set a 0 or a 1.

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go (hunk 7 above)
Comment (ehashman) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:108]: FWIW in the kubelet I don't think it's possible to delete with a grace period below the minimum default, this gets validated and overridden here:

https://github.com/kubernetes/kubernetes/blob/1fb27c4b5d6c9d8f508c7b4bbcf96244d6b65449/pkg/kubelet/pod_workers.go#L302-L309

https://github.com/kubernetes/kubernetes/blob/1fb27c4b5d6c9d8f508c7b4bbcf96244d6b65449/pkg/kubelet/kuberuntime/kuberuntime_container.go#L635-L638

File: pkg/kubelet/pod_workers.go [hunk 9]
```diff
@@ -298,6 +298,9 @@ func killPodNow(podWorkers PodWorkers, recorder record.EventRecorder) eviction.K
 		} else if pod.Spec.TerminationGracePeriodSeconds != nil {
 			gracePeriod = *pod.Spec.TerminationGracePeriodSeconds
 		}
+		if gracePeriod < 0 {
+			gracePeriod = 0
+		}
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:303]: Note there is similar logic in `pkg/kubelet/kuberuntime/kuberuntime_container.go` (no I don't know why there are two code paths) that would potentially also need an update. I ran into this because the `terminationGracePeriodSeconds` is used there when terminating on e.g. a failed probe.

https://github.com/kubernetes/kubernetes/blob/1fb27c4b5d6c9d8f508c7b4bbcf96244d6b65449/pkg/kubelet/kuberuntime/kuberuntime_container.go#L612-L619

**Comment by wzshiming** [comment]
@michaelgugino @liggitt 
Maybe add non-negative integer verification on the client side, and then crop it to 0 elsewhere

**Comment by michaelgugino** [comment]
> @michaelgugino @liggitt
> Maybe add non-negative integer verification on the client side, and then crop it to 0 elsewhere.
> This ensures that the API documentation is correct, and that existing persisted data containing negative values can be handled correctly

Current conforming clients don't send the negative value, so there's not much to change there.  Cropping to 0 is what I'm saying we shouldn't do, we should reject the value at the API.  Most likely, the user intent was 'use pod default' as that's what the delete/drain command help text specifies.

If we want to still accept the API call, then we should drop the field and default to nil instead.  This would allow users to shorten the time if they choose after the call succeeds.

**Comment by erismaster** [comment]
Hello! I am from the Bug Triage team! Friendly reminder that code freeze is starting March 9th, 2021 (about 1 week from now). We want to ensure that each PR has a chance to be merged before code freeze.
As the PR is tagged for 1.21, is it still planned for this release?

**Comment by erismaster** [comment]
Hi 👋 Friendly reminder that code freeze is end of the day (Pacific timezone) today!

File: pkg/apis/core/validation/validation.go [hunk 10]
```diff
@@ -3346,6 +3348,13 @@ func ValidatePodSpec(spec *core.PodSpec, podMeta *metav1.ObjectMeta, fldPath *fi
 		}
 	}
 
+	if !opts.AllowNegativeTerminationGracePeriodSeconds && spec.TerminationGracePeriodSeconds != nil {
+		value := *spec.TerminationGracePeriodSeconds
+		if value < 0 || value > math.MaxInt32 {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3353]: this is rejecting values over math.MaxInt32 without considering existing data (the AllowNegativeTerminationGracePeriodSeconds compatibility bit only gets set for negative values)

**Comment by derekwaynecarr** [comment]
Is there a summary of the behavior we saw across dockershim, containerd, cri-o for how it handled receiving a negative value?

The provided value was passthrough from kubelet if I recall, and only overridden to be 'now' when we do eviction.

**Review by liggitt — COMMENTED** [review]
There are three distinct APIs I'm aware of where we could encounter issues:
1. PodSpec spec.terminationGracePeriodSeconds values less than 0 (applies to all podspec-containing types)
2. ObjectMeta deletionGracePeriodSeconds values less than 0 (applies to all objects)
3. DeleteOptions gracePeriodSeconds (applies to all delete requests)

We know negative values were able to be persisted previously for PodSpec spec.terminationGracePeriodSeconds and ObjectMeta deletionGracePeriodSeconds. If there are clients reading and echoing those values back to the API in DeleteOptions gracePeriodSeconds (does the kubelet do that?), I don't think we can safely reject negative values in DeleteOptions gracePeriodSeconds.

For PodSpec spec.terminationGracePeriodSeconds, disallowing new negative values in those fields while tolerating negative values in existing objects via ratcheting validation (like this PR does) seems like a good approach.

For persisted ObjectMeta deletionGracePeriodSeconds values less than 0 and DeleteOptions gracePeriodSeconds values less than 0, clipping those to 0 still seems like the right approach to me (it's the closest valid value and avoids breaking clients who are simply passing through negative values from elsewhere and may not be able to be updated).

**Comment by derekwaynecarr** [comment]
Just following up, the kubelet -> cri flow sets a minGracePeriod of 2s unless explicitly overriden by the override.

**Comment by ehashman** [comment]
/milestone clear

I think this is too big of a change to land 1wk before test freeze. Let's aim for merging this early in 1.22 and consider backporting.

slack: https://kubernetes.slack.com/archives/C0BP8PW9G/p1616090128021100

**Comment by wzshiming** [comment]
PING

File: pkg/apis/core/validation/validation.go (hunk 10 above)
Comment (liggitt) [reply pkg/apis/core/validation/validation.go:3353]: this is still outstanding

**Comment by ehashman** [comment]
@wzshiming I think this is large enough to warrant discussion at a SIG Node meeting, if you don't hear anything I'll put it on the agenda.

File: pkg/api/pod/util.go [hunk 11]
```diff
@@ -332,6 +332,10 @@ func usesHugePagesInProjectedEnv(item api.Container) bool {
 	return false
 }
 
+func hasNegativeTerminationGracePeriodSeconds(podSpec *api.PodSpec) bool {
+	return podSpec.TerminationGracePeriodSeconds != nil && *podSpec.TerminationGracePeriodSeconds < 0
```
Comment (ehashman) [inline pkg/api/pod/util.go:336]: Can we also validate the probe-level `TerminationGracePeriodSeconds`? That landed in the previous release and has the same issue now.

We should also update the documentation on the API.

Comment (wzshiming) [reply pkg/api/pod/util.go:335]: Updated, added  validate the probe-level `TerminationGracePeriodSeconds`.

I have checked the relevant documents, and all documents contain hints that cannot be negative, so I don’t think there is any need to update this document or i understand wrong.

Comment (wzshiming) [reply pkg/api/pod/util.go:335]: I've added non-negative value validation for probes

**Comment by smarterclayton** [comment]
As per https://github.com/kubernetes/kubernetes/pull/102025 I think when a user provides a negative deletion time it should be equal to 1 seconds, to be consistent and backwards compatible.

**Comment by liggitt** [comment]
> As per #102025 I think when a user provides a negative deletion time it should be equal to 1 seconds, to be consistent and backwards compatible. I'm concerned that tightening validation is a breaking change to a v1 api here.

That sounds reasonable at first glance. A couple questions:
* Which fields are you envisioning that applying to?
* At what point in the request are you envisioning the `if x < 0 { x = 1 }` translation happening?

These are the fields I see, and the points I could imagine doing the translation at:

* Probe#TerminationGracePeriodSeconds
  * in the API as an overriding defaulter
  * in the kubelet when reading the termination grace period
* PodSpec#TerminationGracePeriodSeconds
  * in the API as an overriding defaulter
  * in the API pod strategy when processing delete requests
* ObjectMeta#DeletionGracePeriodSeconds
  * in the API as an overriding defaulter on read
  * in the API rest handler when processing delete requests
* DeleteOptions#GracePeriodSeconds
  * when decoding DeleteOptions
  * in the storage delete handler

**Comment by liggitt** [comment]
> I can't see how a client (kubelet, namespace controller, etc) who sees 1 instead of -1 would be worse off.

The multi-server skew case could cause problems for fields which are immutable (Probe#TerminationGracePeriodSeconds or PodSpec#TerminationGracePeriodSeconds
inside a pod) or required to be monotonically decreasing (metadata.DeletionGracePeriodSeconds)

immutable scenario:

1. Object is persisted with negative value in TerminationGracePeriodSeconds  field
2. Client reads from 1.22 server that replaces the negative value with 1 on read
3. Client changes an unrelated field and writes to a 1.21 server
4. 1.21 server rejects request because an immutable field was changed

metadata.DeletionGracePeriodSeconds scenarios:

* update: [stomped by old DeletionGracePeriodSeconds server-side](https://github.com/kubernetes/kubernetes/blob/release-1.21/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L131-L134); no multi-server skew issue
* delete: if a client read a negative-normalized-to-1 metadata.deletionGracePeriodSeconds from a 1.22 server and copied it into DeleteOptions sent to a delete call made to a 1.21 server, the 1.21 server would reject it in the `only a shorter grace period may be provided by a user` check. practically, I think this would only apply to pods, and I'm not aware of first-party clients that copy from metadata.deletionGracePeriodSeconds into deleteoptions

**Comment by msau42** [comment]
> The multi-server skew case could cause problems for fields which are immutable

To solve the multi-server skew issue, the change could be rolled out over 2 releases:
 * First release: 
     * Treat negative as 1 in delete path (pod/strategy.go, apiserver delete.go)
     * Allow delete with grace period 0 even if metadata period is negative (apiserver delete.go). This allows kubelet to delete pods.
     * Relax validation of immutable fields to allow it to be set to 1 if it was previously negative. This allows us to update read path in the next release. All consumers would also need to be able to handle this change in a sane manner.
 * Second release:
     * Treat negative as 1 in read path (defaulting or conversion)
     * Returning an error on Pod create could break things like Deployment updates. But if we update defaulting, then I think we won't hit this issue.

**Comment by msau42** [comment]
While we're on the topic of pod termination period, this was another problematic scenario where we set grace period = 0: https://github.com/kubernetes/kubernetes/issues/74372. At the time we didn't go through with changing it because we were concerned about the potential impact to pod deletion time, but maybe we can revisit again.

**Comment by smarterclayton** [comment]
> Allow delete with grace period 0 even if metadata period is negative (apiserver delete.go). This allows kubelet to delete pods.

Neither this change nor 102025 should prevent kubelet from deleting pods.  The rule of 0 is disallowed is ONLY as a default deletion value on pod.spec (DELETE with 0 is still valid).

**Comment by liggitt** [comment]
> Neither this change nor 102025 should prevent kubelet from deleting pods. The rule of 0 is disallowed is ONLY as a default deletion value on pod.spec (DELETE with 0 is still valid).

agreed. I think that was saying we could fix the "delete with 0 is disallowed because it technically increases an existing negative objectmeta grade period" bug in release 1 as well

**Comment by liggitt** [comment]
The two release rollout makes sense to me

**Comment by smarterclayton** [comment]
> I think that was saying we could fix the "delete with 0 is disallowed because it technically increases an existing negative objectmeta grace period" bug in release 1 as well

My brain hurts on this one, but I think I agree then.

Dawn was mentioning she thought there was a reason for allowing 0 as the default on a pod, but the ones she remembered were latency related, which are roughly the same arguments those against allowing some garbage collection to happen after pod is deleted in etcd, except worse (force deleting a pod has the largest possible impact on background kubelet load).  Once context cancelling is tested in #102344 it's likely that total termination latency will come down significantly on moderate loaded clusters.

**Comment by wzshiming** [comment]
> First release:
>  - Treat negative as 1 in delete path (pod/strategy.go, apiserver delete.go)
>  - Allow delete with grace period 0 even if metadata period is negative (apiserver delete.go). This allows kubelet to delete pods.
>  - Relax validation of immutable fields to allow it to be set to 1 if it was previously negative. This allows us to update read path in the next release. All consumers would also need to be able to handle this change in a sane manner.


@liggitt PTAL

File: pkg/apis/core/validation/validation.go [hunk 12]
```diff
@@ -4039,11 +4039,17 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
 	// tolerations are checked before the deep copy, so munge those too
 	mungedPodSpec.Tolerations = oldPod.Spec.Tolerations // +k8s:verify-mutation:reason=clone
 
+	// Relax validation of immutable fields to allow it to be set to 1 if it was previously negative.
+	if oldPod.Spec.TerminationGracePeriodSeconds != nil && *oldPod.Spec.TerminationGracePeriodSeconds < 0 &&
```
Comment (ehashman) [inline pkg/apis/core/validation/validation.go:4043]: We should ensure we're validating this for the liveness/startup probe TerminationGracePeriodSeconds too

**Review by ehashman — COMMENTED** [review]
I think we need a clear ACTION REQUIRED release note for this. I'd suggest (open to further improvements):

```release-note
ACTION REQUIRED: TerminationGracePeriodSeconds on pod specs and container probes should not be negative.
Negative values of TerminationGracePeriodSeconds will be treated as the value `1s` on the delete path.
Immutable field validation will be relaxed in order to update negative values. 
In a future release, negative values will not be permitted.
```

File: pkg/apis/core/validation/validation.go (hunk 12 above)
Comment (wzshiming) [reply pkg/apis/core/validation/validation.go:4079]: Thanks, updated

File: pkg/apis/core/validation/validation.go [hunk 13]
```diff
@@ -4016,17 +4048,21 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
...
 	// handle updateable fields by munging those fields prior to deep equal comparison.
 	mungedPodSpec := *newPod.Spec.DeepCopy()
-	// munge spec.containers[*].image
+	// munge spec.containers[*].image, spec.containers[*].StartupProbe, spec.containers[*].LivenessProbe
 	var newContainers []core.Container
 	for ix, container := range mungedPodSpec.Containers {
-		container.Image = oldPod.Spec.Containers[ix].Image // +k8s:verify-mutation:reason=clone
+		container.Image = oldPod.Spec.Containers[ix].Image                 // +k8s:verify-mutation:reason=clone
+		container.StartupProbe = oldPod.Spec.Containers[ix].StartupProbe   // +k8s:verify-mutation:reason=clone
+		container.LivenessProbe = oldPod.Spec.Containers[ix].LivenessProbe // +k8s:verify-mutation:reason=clone
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4056]: double check this does not mutate the new pod

File: pkg/apis/core/validation/validation.go [hunk 14]
```diff
@@ -4016,17 +4048,21 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
...
 	}
 	mungedPodSpec.Containers = newContainers
-	// munge spec.initContainers[*].image
+	// munge spec.initContainers[*].image, spec.initContainers[*].StartupProbe, spec.initContainers[*].LivenessProbe
 	var newInitContainers []core.Container
 	for ix, container := range mungedPodSpec.InitContainers {
-		container.Image = oldPod.Spec.InitContainers[ix].Image // +k8s:verify-mutation:reason=clone
+		container.Image = oldPod.Spec.InitContainers[ix].Image                 // +k8s:verify-mutation:reason=clone
+		container.StartupProbe = oldPod.Spec.InitContainers[ix].StartupProbe   // +k8s:verify-mutation:reason=clone
+		container.LivenessProbe = oldPod.Spec.InitContainers[ix].LivenessProbe // +k8s:verify-mutation:reason=clone
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4065]: double check this does not mutate the new pod

File: pkg/apis/core/validation/validation.go [hunk 15]
```diff
@@ -3873,9 +3873,37 @@ func ValidateContainerUpdates(newContainers, oldContainers []core.Container, fld
...
+	if mungedProbe != nil && oldProbe != nil {
+		if oldProbe.TerminationGracePeriodSeconds != nil && *oldProbe.TerminationGracePeriodSeconds < 0 &&
+			mungedProbe.TerminationGracePeriodSeconds != nil && *mungedProbe.TerminationGracePeriodSeconds == 1 {
+			mungedProbe = mungedProbe.DeepCopy()
+			mungedProbe.TerminationGracePeriodSeconds = oldProbe.TerminationGracePeriodSeconds
+		}
+	}
+
+	// validate updated probe
+	if !reflect.DeepEqual(mungedProbe, oldProbe) {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3899]: use apiequality.Semantic.DeepEqual

File: pkg/apis/core/validation/validation.go [hunk 16]
```diff
@@ -3873,9 +3873,37 @@ func ValidateContainerUpdates(newContainers, oldContainers []core.Container, fld
...
+		probeDiff := diff.ObjectDiff(mungedProbe, oldProbe)
+		allErrs = append(allErrs, field.Forbidden(fldPath, fmt.Sprintf("probe updates may not change fields other than `terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n%v", probeDiff)))
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3901]: I would drop ` (allow it to be set to 1 if it was previously negative)` here, especially if we're planning to convert negative to 1 on read

Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3901]: is changing a negative TerminationGracePeriodSeconds to 1 to fixup invalid data the only change allowed? if so, I would recommend just saying "probe updates may not change fields"

File: pkg/apis/core/validation/validation.go [hunk 17]
```diff
@@ -3873,9 +3873,37 @@ func ValidateContainerUpdates(newContainers, oldContainers []core.Container, fld
...
+	// validate updated container probe
+	for i, ctr := range newContainers {
+		allErrs = append(allErrs, validateProbeUpdates(ctr.StartupProbe, oldContainers[i].StartupProbe, fldPath.Index(i).Child("startupProbe"))...)
+		allErrs = append(allErrs, validateProbeUpdates(ctr.LivenessProbe, oldContainers[i].LivenessProbe, fldPath.Index(i).Child("livenessProbe"))...)
+	}
+
 	return allErrs, false
 }
 
+func validateProbeUpdates(newProbe, oldProbe *core.Probe, fldPath *field.Path) (allErrs field.ErrorList) {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3886]: this is a bigger question than just the negative value validation, but won't a client with an old v1.Pod definition drop probe TerminationGracePeriodSeconds field values when it does a read/update/write and fail the immutability check?

should we be copying TerminationGracePeriodSeconds values from the old pod's probes in if the new pod has nil values for those to keep existing clients working?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 18]
```diff
@@ -111,12 +111,19 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
 		// only a shorter grace period may be provided by a user
 		if options.GracePeriodSeconds != nil {
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:112]: this definitely needs associated unit tests exercising all the combinations of:

1. objectmeta grace period: nil, -1, 0, 1, 2
2. delete options grace period: nil, -1, 0, 1, 2

File: pkg/registry/core/pod/strategy.go [hunk 19]
```diff
@@ -167,6 +167,11 @@ func (podStrategy) CheckGracefulDelete(ctx context.Context, obj runtime.Object,
 	if pod.Status.Phase == api.PodFailed || pod.Status.Phase == api.PodSucceeded {
 		period = 0
 	}
+
+	if period < 0 {
```
Comment (liggitt) [inline pkg/registry/core/pod/strategy.go:171]: this needs a comment and associated unit test

File: pkg/apis/core/validation/validation.go [hunk 20]
```diff
@@ -3973,6 +4001,10 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
 	// 1.  spec.containers[*].image
 	// 2.  spec.initContainers[*].image
 	// 3.  spec.activeDeadlineSeconds
+	// 4.  spec.containers[*].startupProbe.terminationGracePeriodSeconds
+	// 5.  spec.containers[*].livenessProbe.terminationGracePeriodSeconds
+	// 6.  spec.initContainers[*].startupProbe.terminationGracePeriodSeconds
+	// 7.  spec.initContainers[*].livenessProbe.terminationGracePeriodSeconds
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4008]: don't we need the same change for podSpec.TerminationGracePeriodSeconds (tolerate update from negative to 1)?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 21]
```diff
@@ -111,12 +111,19 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
...
 			period := int64(*options.GracePeriodSeconds)
-			if period >= *objectMeta.GetDeletionGracePeriodSeconds() {
+			if period < 0 {
+				period = 1
+			}
+			metadataPeriod := *objectMeta.GetDeletionGracePeriodSeconds()
+			if metadataPeriod < 0 {
+				metadataPeriod = 0
```
[the remark this answers is not in the document]
Comment (wzshiming) [reply staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:119]: https://github.com/kubernetes/kubernetes/pull/98866#issuecomment-849203505
> First release:
> * Treat negative as 1 in delete path (pod/strategy.go, apiserver delete.go)
> * Allow delete with grace period 0 even if metadata period is negative (apiserver delete.go). This allows kubelet to delete pods.
> * Relax validation of immutable fields to allow it to be set to 1 if it was previously negative. This allows us to update read path in the next release. All consumers would also need to be able to handle this change in a sane manner.

> Allow delete with grace period 0 even if metadata period is negative

File: pkg/apis/core/validation/validation.go [hunk 22]
```diff
@@ -3973,12 +4016,20 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
 	// 1.  spec.containers[*].image
 	// 2.  spec.initContainers[*].image
 	// 3.  spec.activeDeadlineSeconds
+	// 4.  spec.terminationGracePeriodSeconds
+	// 5.  spec.containers[*].startupProbe.terminationGracePeriodSeconds
+	// 6.  spec.containers[*].livenessProbe.terminationGracePeriodSeconds
```
Comment (wzshiming) [inline pkg/apis/core/validation/validation.go:4021]: https://github.com/kubernetes/kubernetes/blob/5ec7b49299ec838ede7f6c064aca95378871f1ec/pkg/apis/core/validation/validation.go#L2793-L2825

No need to veridate initContainers

File: pkg/apis/core/validation/validation.go [hunk 23]
```diff
@@ -3873,9 +3873,52 @@ func ValidateContainerUpdates(newContainers, oldContainers []core.Container, fld
...
+		allErrs = append(allErrs, validateProbeUpdates(ctr.LivenessProbe, oldContainers[i].LivenessProbe, fldPath.Index(i).Child("livenessProbe"))...)
+	}
+
+	return allErrs, false
+}
+
+func validateProbeUpdatesOnContainer(newContainers, oldContainers []core.Container, fldPath *field.Path) (allErrs field.ErrorList, stop bool) {
+	allErrs = field.ErrorList{}
+	if len(newContainers) != len(oldContainers) {
+		//TODO: Pinpoint the specific container that causes the invalid error after we have strategic merge diff
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3889]: drop this TODO, I don't expect we'll ever do this

File: pkg/apis/core/validation/validation.go [hunk 24]
```diff
@@ -3973,12 +4016,20 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
...
+	// 4.  spec.terminationGracePeriodSeconds
+	// 5.  spec.containers[*].startupProbe.terminationGracePeriodSeconds
+	// 6.  spec.containers[*].livenessProbe.terminationGracePeriodSeconds
 
 	containerErrs, stop := ValidateContainerUpdates(newPod.Spec.Containers, oldPod.Spec.Containers, specPath.Child("containers"))
 	allErrs = append(allErrs, containerErrs...)
 	if stop {
 		return allErrs
 	}
+	containerErrs, stop = validateProbeUpdatesOnContainer(newPod.Spec.Containers, oldPod.Spec.Containers, specPath.Child("containers"))
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4028]: why isn't this part of ValidateContainerUpdates?

File: pkg/registry/core/pod/strategy_test.go [hunk 25]
```diff
@@ -267,53 +268,68 @@ func TestCheckGracefulDelete(t *testing.T) {
...
+			out:         &metav1.DeleteOptions{GracePeriodSeconds: &defaultGracePeriod},
 			gracePeriod: defaultGracePeriod,
 		},
 		{
 			in: &api.Pod{
 				Spec:   api.PodSpec{NodeName: "something"},
 				Status: api.PodStatus{Phase: api.PodFailed},
 			},
+			out:         &metav1.DeleteOptions{GracePeriodSeconds: &defaultGracePeriod},
 			gracePeriod: 0,
```
Comment (liggitt) [inline pkg/registry/core/pod/strategy_test.go:288]: if we pass in gracePeriod 0, shouldn't the result be grace period 0, not defaultGracePeriod? (same question applies to the next several test cases)

File: pkg/registry/core/pod/strategy_test.go [hunk 26]
```diff
@@ -267,53 +268,68 @@ func TestCheckGracefulDelete(t *testing.T) {
 	defaultGracePeriod := int64(30)
 	tcs := []struct {
 		in          *api.Pod
+		out         *metav1.DeleteOptions
```
Comment (liggitt) [inline pkg/registry/core/pod/strategy_test.go:271]: this is confusing... this is the delete options passed *in*, right? would be clearer to have `deleteGracePeriod *int64` and continue constructing deleteoptions inside the test

File: pkg/registry/core/pod/strategy_test.go [hunk 27]
```diff
@@ -267,53 +268,68 @@ func TestCheckGracefulDelete(t *testing.T) {
 	defaultGracePeriod := int64(30)
 	tcs := []struct {
```
Comment (liggitt) [inline pkg/registry/core/pod/strategy_test.go:269]: add `name string` to these test cases and document what condition each is testing so it's easy to follow why we expect the given output gracePeriod result

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 28]
```diff
@@ -0,0 +1,245 @@
...
+			GracePeriodSeconds: &gracePeriodSeconds,
+		}
+	}
+
+	tests := []struct {
+		name                string
+		args                args
+		wantGraceful        bool
+		wantGracefulPending bool
+		wantErr             bool
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:74]: should we also assert what the resulting GracePeriodSeconds on the object/deleteoptions are?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 29]
```diff
@@ -0,0 +1,245 @@
...
+	}{
+		{
+			name: "when DeletionGracePeriodSeconds=-1, GracePeriodSeconds=-1",
+			args: args{
+				obj:     makePod(-1),
+				options: makeOption(-1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:83]: I'd expect gracePeriodSeconds to be 1 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 30]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=-1, GracePeriodSeconds=0",
+			args: args{
+				obj:     makePod(-1),
+				options: makeOption(0),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:92]: I'd expect gracePeriodSeconds to be 0 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 31]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=-1, GracePeriodSeconds=1",
+			args: args{
+				obj:     makePod(-1),
+				options: makeOption(1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:101]: I'd expect gracePeriodSeconds to be 1 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 32]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=-1, GracePeriodSeconds=2",
+			args: args{
+				obj:     makePod(-1),
+				options: makeOption(2),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:110]: I *think* I'd expect gracePeriodSeconds to be 1 after this call (-1 → 1, and is not allowed to be lengthened to 2)

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 33]
```diff
@@ -0,0 +1,245 @@
...
+		},
+
+		{
+			name: "when DeletionGracePeriodSeconds=0, GracePeriodSeconds=-1",
+			args: args{
+				obj:     makePod(0),
+				options: makeOption(-1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:120]: 0 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 34]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=0, GracePeriodSeconds=0",
+			args: args{
+				obj:     makePod(0),
+				options: makeOption(0),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:129]: 0 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 35]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=0, GracePeriodSeconds=1",
+			args: args{
+				obj:     makePod(0),
+				options: makeOption(1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:138]: 0 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 36]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=0, GracePeriodSeconds=2",
+			args: args{
+				obj:     makePod(0),
+				options: makeOption(2),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:147]: 0 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 37]
```diff
@@ -0,0 +1,245 @@
...
+		},
+
+		{
+			name: "when DeletionGracePeriodSeconds=1, GracePeriodSeconds=-1",
+			args: args{
+				obj:     makePod(1),
+				options: makeOption(-1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:157]: 1 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 38]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=1, GracePeriodSeconds=0",
+			args: args{
+				obj:     makePod(1),
+				options: makeOption(0),
+			},
+			wantGraceful:        true,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:166]: 0 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 39]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=1, GracePeriodSeconds=1",
+			args: args{
+				obj:     makePod(1),
+				options: makeOption(1),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:175]: 1 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 40]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=1, GracePeriodSeconds=2",
+			args: args{
+				obj:     makePod(1),
+				options: makeOption(2),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:184]: 1 after this call?

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 41]
```diff
@@ -0,0 +1,245 @@
...
+		},
+
+		{
+			name: "when DeletionGracePeriodSeconds=2, GracePeriodSeconds=-1",
+			args: args{
+				obj:     makePod(2),
+				options: makeOption(-1),
+			},
+			wantGraceful:        true,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:194]: 1 after this call (-1 → 1 and is allowed to shorten existing grace period)

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 42]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=2, GracePeriodSeconds=0",
+			args: args{
+				obj:     makePod(2),
+				options: makeOption(0),
+			},
+			wantGraceful:        true,
+			wantGracefulPending: false,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:203]: 0 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 43]
```diff
@@ -0,0 +1,245 @@
...
+		},
+		{
+			name: "when DeletionGracePeriodSeconds=2, GracePeriodSeconds=1",
+			args: args{
+				obj:     makePod(2),
+				options: makeOption(1),
+			},
+			wantGraceful:        true,
+			wantGracefulPending: false,
+		},
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:213]: 1 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go [hunk 44]
```diff
@@ -0,0 +1,245 @@
...
+		{
+			name: "when DeletionGracePeriodSeconds=2, GracePeriodSeconds=2",
+			args: args{
+				obj:     makePod(2),
+				options: makeOption(2),
+			},
+			wantGraceful:        false,
+			wantGracefulPending: true,
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete_test.go:221]: 2 after this call

File: staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go [hunk 45]
```diff
@@ -86,6 +87,15 @@ func BeforeDelete(strategy RESTDeleteStrategy, ctx context.Context, obj runtime.
 			return false, false, errors.NewConflict(schema.GroupResource{Group: gvk.Group, Resource: gvk.Kind}, objectMeta.GetName(), fmt.Errorf("the ResourceVersion in the precondition (%s) does not match the ResourceVersion in record (%s). The object might have been modified", *options.Preconditions.ResourceVersion, objectMeta.GetResourceVersion()))
 		}
 	}
+
+	// Negative values will be treated as the value `1s` on the delete path.
+	if gracePeriodSeconds := options.GracePeriodSeconds; gracePeriodSeconds != nil && *gracePeriodSeconds < 0 {
+		options.GracePeriodSeconds = utilpointer.Int64(1)
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go:93]: adding another options mutation looks like it will exacerbate the issue being fixed in https://github.com/kubernetes/kubernetes/pull/100101

@deads2k, is that PR close? is there something this PR should do differently to avoid that issue?

File: pkg/apis/core/validation/validation.go [hunk 46]
```diff
@@ -3873,9 +3873,35 @@ func ValidateContainerUpdates(newContainers, oldContainers []core.Container, fld
 			allErrs = append(allErrs, field.Invalid(fldPath.Index(i).Child("image"), ctr.Image, "must not have leading or trailing whitespace"))
 		}
 	}
+
+	// validate updated container probe
+	for i, ctr := range newContainers {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:3878]: if probe.TerminationGracePeriodSeconds is still alpha, can we add the validation to require non-negative values before promotion to beta, rather than making the update validation more complicated/expensive?

File: pkg/apis/core/validation/validation.go [hunk 47]
```diff
@@ -4039,13 +4070,26 @@ func ValidatePodUpdate(newPod, oldPod *core.Pod, opts PodValidationOptions) fiel
 	// tolerations are checked before the deep copy, so munge those too
 	mungedPodSpec.Tolerations = oldPod.Spec.Tolerations // +k8s:verify-mutation:reason=clone
 
+	// Relax validation of immutable fields to allow it to be set to 1 if it was previously negative.
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4073]: this lgtm

File: pkg/apis/core/validation/validation.go (hunk 46 above)
Comment (wzshiming) [reply pkg/apis/core/validation/validation.go]: Sure. Update and I sent a new patch to follow this #103245
