### PR TITLE
Retry fetching http urls passed to '-f' in kubectl.

### LINKED ISSUE #24089: kubectl validation fails when creating a non-v1 object in a v1 list
In other words, you can't create/replace/delete/apply deployments with kubectl if they're in a list.

Works as expected:

```console
$ cat nginx-rc.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: nginx
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: nginx
        spec:
          containers:
            - name: nginx
              image: nginx
$ kubectl create -f nginx-rc.yaml
replicationcontroller "nginx" created
```

Does not work as expected:

```
$ cat nginx-dpl.yaml
apiVersion: v1
kind: List
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: nginx
        spec:
          containers:
            - name: nginx
              image: nginx
$ kubectl create -f nginx-dpl.yaml
error validating "nginx-dpl.yaml": error validating data: couldn't find type: v1beta1.Deployment; if you choose to ignore these errors, turn validation off with --validate=false
$ kubectl create -f nginx-dpl.yaml --validate=false
deployment "nginx" created
```

This is a high priority issue for us, since it means we can't (easily) use apply (or any kubectl command) with lists of JSON objects since we've moved all our replication controllers over to deployment objects, which is hampering the UX of our config efforts.

### PR DESCRIPTION
**Pull request by pwittrock**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* kubectl now retries failed http gets for urls passed through the '-f' flag.
```

[Analytics]()

Closes #24089.

### CODE REVIEW

File: pkg/kubectl/resource/visitor.go [hunk 1]
```diff
@@ -224,17 +225,60 @@ type URLVisitor struct {
...
+	defer body.Close()
+	v.StreamVisitor.Reader = body
+	return v.StreamVisitor.Visit(fn)
+}
+
+// readHttpWithRetries tries to http.Get the v.URL 3 times before giving up.
+func (v *URLVisitor) readHttpWithRetries(get httpget, duration time.Duration, u string) (io.ReadCloser, error) {
+	var err error
+	var body io.ReadCloser
+	for i := 0; i < 3; i++ {
```
Comment (zhouhaibing089) [inline pkg/kubectl/resource/visitor.go]: maybe the retries count should be a parameter?

Comment (pwittrock) [inline pkg/kubectl/resource/visitor.go]: A parameter or the method or a flag?

Comment (smarterclayton) [inline pkg/kubectl/resource/visitor.go]: parameter to method at minimum.  Stick it on the body of the visitor and set it by resource builder (which at least hoists this up a few levels).

File: pkg/kubectl/resource/visitor.go [hunk 2]
```diff
@@ -224,17 +225,60 @@ type URLVisitor struct {
...
-	defer res.Body.Close()
-	if res.StatusCode != 200 {
-		return fmt.Errorf("unable to read URL %q, server reported %d %s", v.URL, res.StatusCode, res.Status)
+	defer body.Close()
+	v.StreamVisitor.Reader = body
+	return v.StreamVisitor.Visit(fn)
+}
+
+// readHttpWithRetries tries to http.Get the v.URL 3 times before giving up.
+func (v *URLVisitor) readHttpWithRetries(get httpget, duration time.Duration, u string) (io.ReadCloser, error) {
```
Comment (smarterclayton) [inline pkg/kubectl/resource/visitor.go]: If there's no values being read off v, make this a straight function (not attached to the visitor type).

File: pkg/kubectl/resource/visitor.go (hunk 1 above)
Comment (pwittrock) [inline pkg/kubectl/resource/visitor.go]: What is the benefit of making this configurable if it is going to be hard-coded somewhere else?  What do you think of making it a const?

File: pkg/kubectl/resource/visitor.go (hunk 2 above)
Comment (pwittrock) [inline pkg/kubectl/resource/visitor.go]: Done

File: pkg/kubectl/resource/visitor.go (hunk 1 above)
Comment (pwittrock) [inline pkg/kubectl/resource/visitor.go]: I prototyped my understanding of this suggestion.  It makes the code look less hacky, but I think this is mainly because it obfuscates that it is actually hardcoded to a const.  If we plan to expose this in the future it makes sense.  It could also be indication to the caller that the http requests will be retried.  I don't have a strong opinion about this so I will push the changes to see what you think about it.

**Comment by pwittrock** [comment]
PTAL

File: pkg/kubectl/resource/visitor.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/kubectl/resource/visitor.go]: We generally try to keep magic number constants out of method bodies,
primarily for testability but also to make clear that it's a chosen
default value vs an arbitrary constant (makes code review easier).

Comment (pwittrock) [inline pkg/kubectl/resource/visitor.go]: SGTM.  WDYT about giving the same treatment to sleep duration?

**Comment by pwittrock** [comment]
@k8s-bot this this: #IGNORE tests haning

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by pwittrock** [comment]
@k8s-bot e2e test this issue: #21990

File: pkg/kubectl/resource/visitor.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/kubectl/resource/visitor.go]: Yes I think that makes sense.  Sorry for the inattention, been trying to
sort out the proto issues this morning.

**Comment by smarterclayton** [comment]
LGTM - anything else you wanted to add to this?

**Comment by pwittrock** [comment]
@smarterclayton If you think it meets the bar as is, I'd rather not add anything to it.  I am focussed on completing Templates May 20, and won't have any cycles to think about this until that is complete.
