### PR TITLE
fix windows container root validate

### LINKED ISSUE #91482: PodSecurityPolicy rule: 'MustRunAsNonRoot' and windowsOptions: runAsUserName not working
Hello, 

**What happened**:
When we apply PodSecurityPolicy with rule:

```
runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
```

WIndows containers are still blocked instead we put: 

```
  securityContext:
   windowsOptions:
      runAsUserName: "ContainerUser"
```

the pod is still blocked with logs: 

`  Warning  Failed          1s (x10 over 72s)  kubelet, kubenodewin04  Error: container has runAsNonRoot and image will run as root `

**What you expected to happen**:

the Container should start

**How to reproduce it (as minimally and precisely as possible)**:
Create Psp disableling Root Users:

```
runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
```

Create a pod Windows with runAsUserName:

```
apiVersion: v1
kind: Pod
metadata:
  name: run-as-username-pod-demo
spec:
  securityContext:
    windowsOptions:
      runAsUserName: "ContainerUser"
  containers:
  - name: run-as-username-demo
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["ping", "-t", "localhost"]
  nodeSelector:
    kubernetes.io/os: windows
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.3
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core) / windows server 2019 version 1809
- Kernel (e.g. `uname -a`):  3.10.0-514.10.2.el7.x86_64
- Others:
/sig windows

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind bug
/kind feature

**What this PR does / why we need it**:

From https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md#v1container

Windows container does not have a root user,but kubelet will still check the user of the windows container when creating the pod.

The current inspection conditions are based on the `RunAsNonRoot` and `RunAsUser` of the Linux container, and the results checked based on these conditions are incorrect

**Which issue(s) this PR fixes**:

Fixes #91482 #91414 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Ignore root user check when windows pod starts
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig windows
/assign @dchen1107

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 1]
```diff
@@ -240,12 +240,16 @@ func (m *kubeGenericRuntimeManager) generateContainerConfig(container *v1.Contai
...
 		return nil, cleanupAction, err
 	}
-
-	// Verify RunAsNonRoot. Non-root verification only supports numeric user.
-	if err := verifyRunAsNonRoot(pod, container, uid, username); err != nil {
-		return nil, cleanupAction, err
+	// https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190103-windows-node-support.md#v1container
+	// Windows does not have a root user, we cannot judge the root identity of the windows container by the way to judge the root of the linux container
+	// SecurityContext.RunAsUser, and SecurityContext.RunAsNonRoot These are Linux-specific attributes and cannot be used on windows containers
+	// Therefore, the judgment logic here does not apply to windows container
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:246]: would it be helpful to report an error back that configuration may be incorrect? Not necessarily by failing this verification, but maybe with the log message?

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 2]
```diff
@@ -240,12 +240,16 @@ func (m *kubeGenericRuntimeManager) generateContainerConfig(container *v1.Contai
...
+	if goruntime.GOOS != "windows" {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:247]: would it be possible to add a test?

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:246]: Both windows container and linux will cover this piece of code, but it only makes sense to execute on linux. Therefore, I feel that there is no need to output some confusing logs on windows

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:246]: why do you think it will be confusing? If these settings were set by user, it may be important to know that settings were ignored. Or the assumption here that those log messages will never be seen by the person who set these configuration settings?

Comment (wawa0210) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:246]: The processing logic of `verifyRunAsNonRoot` is not suitable for windows containers. Many of the judgment fields are based on Linux containers, such as `SecurityContext.RunAsUser`, `image.uid`, `SecurityContext.RunAsNonRoot`. So I have circumvented this logic~ Maybe Windows container should be judged separately and used for user input check. Is this better? Do you think?

Comment (jsturtevant) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:246]: I think it would be cleaner to split it out and judge differently.  Could use file suffix for the implementation as is done for [applyPlatformSpecificContainerConfig](https://github.com/kubernetes/kubernetes/blob/ee53488f19ff2fdd94cf311662e8a62845162871/pkg/kubelet/kuberuntime/kuberuntime_container.go#L277) in the [windows](https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/kuberuntime/kuberuntime_container_windows.go#L37) and [linux](https://github.com/kubernetes/kubernetes/blob/442a69c3bdf6fe8e525b05887e57d89db1e2f3a5/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L36) files.  For windows this can be a noop and if later there are privileged containers we would be able to add logic cleanly.

File: pkg/kubelet/kuberuntime/security_context_others.go [hunk 3]
```diff
@@ -0,0 +1,51 @@
+// +build !windows
+
+/*
+Copyright 2016 The Kubernetes Authors.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_others.go:4]: nit 

```suggestion
Copyright 2020 The Kubernetes Authors.
```

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 4]
```diff
@@ -0,0 +1,31 @@
+// +build windows
+
+/*
+Copyright 2016 The Kubernetes Authors.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_windows.go:4]:
```suggestion
Copyright 2020 The Kubernetes Authors.
```

File: pkg/kubelet/kuberuntime/security_context_others.go [hunk 5]
```diff
@@ -0,0 +1,51 @@
+// +build !windows
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_others.go:1]: same in `security_context_test.go`?

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 3 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go:4]: done .

File: pkg/kubelet/kuberuntime/security_context_others.go [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+
+/*
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_others.go:3]: the pattern in file naming is `security_context_windows.go` and `security_context.go` In couple places I saw `_unix` or `_linux` suffices. I'd vote for consistency and drop `_other`

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 5 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go:1]: I didn't get what you meant.

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 6 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go:3]: Here I have a very uncertain thing is that other platforms besides Linux and Windows support this feature, so I chose to use others~~

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 5 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go:1]: the file security_context_test.go calls into the method you modified. If you compile different version on windows - running these tests on windows would fail. So I suggest to add the same `build !windows` to the file containing tests

Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go:1]: Also worth renaming the test file with the same pattern as the product code. With `_other` or `_non_windows` suffix.

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 6 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go:3]: thank you for pointing out. Somehow all examples I saw was not using this pattern. I guess it's ok. If not previous examples my suggestion would be `security_context_non_windows.go`. It may be the most descriptive name

Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go:3]: About this, I went to look at some of the existing designs of kubernetes.

- If the platform support is very clear, it is generally `*_linux.go`, `*_windows.go`, `*_unspport.go`. 
- If it is possible to distinguish between windows and others, it is generally `*_others.go`, `*_windows.go`.

I think it’s better to follow the existing naming rules, otherwise it will confuse people , what do you think?

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 5 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_others.go:1]: changed.

File: pkg/kubelet/kuberuntime/security_context_others.go (hunk 6 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_others.go:3]: sure, lets keep it. It looks consistent with the pattern. Thank you for looking into it

**Review by SergeyKanzhelev — APPROVED** [review]
I still think it may be valuable to log warning if unsupported setting was set for windows. But this is an additional feature to log this warning and PR is ok.

**Comment by ddebroy** [comment]
From a sig-windows perspective, I wonder if it makes sense to bar `runAsUsername` from being `ContainerAdministrator` (https://kubernetes.io/docs/tasks/configure-pod-container/configure-runasusername/). `ContainerAdministrator` does somewhat emulate `root` user in Linux contexts. Let's discuss this is a bit in sig-windows.

**Comment by dashpole** [comment]
@ddebroy let me know the outcome of the sig-windows discussions.  I can approve once sig-windows has decided how to handle this.

**Comment by jsturtevant** [comment]
We [discussed this at sig-windows today](https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#) and came to the consensus we should be more restrictive initially as it will be hard to constrain later.  Rather than ignore `RunAsUserName` we should block when the user is `ContainerAdministrator`. 

@wawa0210 could you make those updates?

/cc @ddebroy @michmike

**Comment by wawa0210** [comment]
> We [discussed this at sig-windows today](https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#) and came to the consensus we should be more restrictive initially as it will be hard to constrain later. Rather than ignore `RunAsUserName` we should block when the user is `ContainerAdministrator`.

Of course, I can try to change. Originally I planned to participate in this sig-windows discussion too, unfortunately I missed it due to time constraints. I will go to watch the video on youtube, the details of your discussion, and then make changes

**Comment by jsturtevant** [comment]
thanks! feel free to ask questions in the sig-windows slack channel if you have any

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+	if effectiveSc.WindowsOptions != nil {
+		if effectiveSc.WindowsOptions.RunAsUserName != nil {
+			if *effectiveSc.WindowsOptions.RunAsUserName == windowsRootUserName {
+				return fmt.Errorf("container's runAsUser (%s) which will be regarded as root identity and will be break non-root policy", username)
+			}
+		}
+
+	}
+	if len(username) > 0 && username == windowsRootUserName {
+		return fmt.Errorf("container's runAsUser (%s) which will be regarded as root identity and will be break non-root policy", username)
```
Comment (jsturtevant) [inline pkg/kubelet/kuberuntime/security_context_windows.go:52]:
```suggestion
		return fmt.Errorf("container's runAsUser is (%s) which will be regarded as root identity and will break non-root policy", username)
```

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+func verifyRunAsNonRoot(pod *v1.Pod, container *v1.Container, uid *int64, username string) error {
+	effectiveSc := securitycontext.DetermineEffectiveSecurityContext(pod, container)
+	// If the option is not set, or if running as root is allowed, return nil.
+	if effectiveSc == nil || effectiveSc.RunAsNonRoot == nil || !*effectiveSc.RunAsNonRoot {
+		return nil
+	}
+	if effectiveSc.WindowsOptions != nil {
+		if effectiveSc.WindowsOptions.RunAsUserName != nil {
+			if *effectiveSc.WindowsOptions.RunAsUserName == windowsRootUserName {
+				return fmt.Errorf("container's runAsUser (%s) which will be regarded as root identity and will be break non-root policy", username)
```
Comment (jsturtevant) [inline pkg/kubelet/kuberuntime/security_context_windows.go:46]:
```suggestion
				return fmt.Errorf("container's runAsUser is (%s) which will be regarded as root identity and will break non-root policy", username)
```

**Comment by jsturtevant** [comment]
It would be nice to see an e2e test for this added: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/security_context.go#L15

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+			}
+		}
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_windows.go:48]: linux version of this method will return nil here. Meaning that if `WindowsOptions.RunAsUserName` was set to a value that is not root, it will OK that independently from values of `uid ` and `username `. Why is this one different?

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+
+	}
+	if len(username) > 0 && username == windowsRootUserName {
+		return fmt.Errorf("container's runAsUser (%s) which will be regarded as root identity and will be break non-root policy", username)
+	}
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/security_context_windows.go:53]: Do you want to report a warning or error if `*effectiveSc.RunAsUser` was set to some (any) value? This configuration may indicate an intent to configure security that cannot be satisfied on windows

Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_windows.go:57]: Adding this warning message is indeed friendly for windows

File: pkg/kubelet/kuberuntime/security_context_windows.go (hunk 9 above)
Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_windows.go:53]: Already fixed
The logic of linux container is to judge by the security context of pod and container first, if the user does not input, judge by mirror metadata. Windows reuses this logic

**Comment by wawa0210** [comment]
> It would be nice to see an e2e test for this added: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/security_context.go#L15

I have some doubts about adding e2e test here. I am adjusting `verifyRunAsNonRoot` judgment logic. This function is only to verify whether the current parameters are legal, and does not include the real pod creation logic. I don't know how to write this e2e

**Comment by michmike** [comment]
@jsturtevant and @wawa0210 , is this supposed to go in for v1.19?
i don't see a milestone set

**Comment by wawa0210** [comment]
> @jsturtevant and @wawa0210 , is this supposed to go in for v1.19?
> i don't see a milestone set

I think this pr can be released with 1.19, what is your opinion? @jsturtevant

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by wawa0210** [comment]
@michmike @jsturtevant 

If you agree, I suggest this pr can be released with v1.19

**Comment by jsturtevant** [comment]
Yes it is a bug fix so I think it should be in 1.19

/milestone v1.19

**Comment by jsturtevant** [comment]
@michmike can you help asign the milestone?

**Comment by wawa0210** [comment]
> @michmike can you help asign the milestone?

I think this `verifyRunAsNonRoot` method is not a typical e2e scenario, it just acts as a checker and will not eventually change the pod parameters. Is unit testing enough?

**Comment by jsturtevant** [comment]
> I have some doubts about adding e2e test here. I am adjusting verifyRunAsNonRoot judgment logic. This function is only to verify whether the current parameters are legal, and does not include the real pod creation logic. I don't know how to write this e2e.

I think there are two scenarios for this, which are tested for linux (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/pod_security_policy.go)

- if the psp with `runasroot` is applied the pod should be scheduled if ContainerUser
- if the psp is applied and ContainerAdministrator it should be in `CreateContainerConfigError` state with the message `Error: container has runAsNonRoot `

That said I think the unit tests are probably enough and given the [current state of of psp](https://github.com/kubernetes/enhancements/issues/5) I think this can probably move ahead and we could open a separate issue for the adding end to end tests and add as good-first-issue.  We don't have a ton of those for windows and would be nice to have more for new contributors.

thoughts?

**Comment by jsturtevant** [comment]
It looks like the test `pull-kubernetes-e2e-azure-file-windows` is failing due to the schedule windows pods which your fixing on https://github.com/kubernetes/kubernetes/pull/93063

**Comment by wawa0210** [comment]
> I think there are two scenarios for this, which are tested for linux (https://github.com/kubernetes/kubernetes/blob/master/test/e2e/auth/pod_security_policy.go)
> 
> * if the psp with `runasroot` is applied the pod should be scheduled if ContainerUser
> * if the psp is applied and ContainerAdministrator it should be in `CreateContainerConfigError` state with the message `Error: container has runAsNonRoot `
> 
> That said I think the unit tests are probably enough and given the [current state of of psp](https://github.com/kubernetes/enhancements/issues/5) I think this can probably move ahead and we could open a separate issue for the adding end to end tests and add as good-first-issue. We don't have a ton of those for windows and would be nice to have more for new contributors.
> 
> thoughts?

I agree with you, I will recreate an issue for e2e later, I hope more contributors will participate

**Comment by liggitt** [comment]
since this hasn't been reviewed/approved and we're at the end of 1.19 code freeze, moving to 1.20

/milestone v1.20

**Comment by liggitt** [comment]
this will be moved back into the milestone as part of the [phased reopen for 1.20 merges](https://docs.google.com/document/d/1yI7o7R2bOB7QtkHUFMHMb5XObiJmzIAnJPuxhdAX-CA/edit)

**Comment by immuzz** [comment]
SIG Windows Backlog Meeting

Next Step: Need 1.20 Tag and merging. @marosset to work on that

**Comment by wawa0210** [comment]
@jsturtevant @michmike @SergeyKanzhelev 
Can you take the time to help review this pr again?

File: pkg/kubelet/kuberuntime/security_context_windows.go [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+	effectiveSc := securitycontext.DetermineEffectiveSecurityContext(pod, container)
+	// If the option is not set, or if running as root is allowed, return nil.
+	if effectiveSc == nil || effectiveSc.RunAsNonRoot == nil || !*effectiveSc.RunAsNonRoot {
+		return nil
+	}
+	if effectiveSc.RunAsUser != nil {
+		klog.Warningf("Windows container does not support SecurityContext.RunAsUser, please use SecurityContext.WindowsOptions")
+	}
+	if effectiveSc.SELinuxOptions != nil {
+		klog.Warningf("Windows container does not support SecurityContext.SELinuxOptions, please use SecurityContext.WindowsOptions")
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/security_context_windows.go:48]: This is a big deal, right?  Someone thinks they are running with security options that we aren't applying.  Should this fail more loudly?

If i'm interpreting this correctly, I would suggest emiting an event, or even returning an error here.  Same comment for other unsupported options.

**Review by dashpole — COMMENTED** [review]
Should setting WindowsOptions on linux containers also fail more loudly?

File: pkg/kubelet/kuberuntime/security_context_windows.go (hunk 11 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: I think the argumentation here is that these settings were likely set by some plugin. See https://github.com/kubernetes/kubernetes/pull/93475#discussion_r486666465

This is why warning was good enough from my perspective, but I'd like somebody from windows sig to confirm

Comment (marosset) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: Maybe we should add a check to https://github.com/kubernetes/kubernetes/blob/360659102c8ae94a5bee6e9cbbc3d1160db58428/pkg/apis/core/validation/validation.go#L3769 that verifies only only of SecurityContext.SELinuxOptions or SecurityContext.WindowsOptions are set.

From my perspective we should encourage plugin/automation authors to use node selectors if they are going to blanket apply security policy to pods rather than working around that assumption in the kubelet.
@jsturtevant thoughts?

Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: Because these do not cause cri errors, it is just that the features of linux container on windows container cannot take effect, and vice versa. If kubelet fails more loudly, it will affect existing applications (adding wrong WindowsOptions or LinuxOptions). So I think the warning level log may be a way to make sense (may need to be more detailed)

Comment (wawa0210) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: @marosset 

I think this is a very good idea. When apiserver pre-verification, if the user explicitly sets `SecurityContext.SELinuxOptions` or `SecurityContext.WindowsOptions` for verification, if the discussion passes, I can try to open another A pr. 
But kubelet is really responsible for calling cri to create pod logic. Should it also have its own necessary verification logic?

Comment (liggitt) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: > Maybe we should add a check to https://github.com/kubernetes/kubernetes/blob/360659102c8ae94a5bee6e9cbbc3d1160db58428/pkg/apis/core/validation/validation.go#L3769 that verifies only one of SecurityContext.SELinuxOptions or SecurityContext.WindowsOptions are set.

Tightening API validation is not generally possible (see https://github.com/kubernetes/kubernetes/issues/64841). If that combination of settings is never legitimate (is a multi-OS image possible?), we could add that to the list of things we want to warn about (https://github.com/kubernetes/kubernetes/issues/94626)

Comment (dashpole) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: Thanks @liggitt, that addresses my concern.

Comment (dashpole) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: Thanks @liggitt, that addresses my concern.

Comment (marosset) [reply pkg/kubelet/kuberuntime/security_context_windows.go:48]: This also addresses my concern.
