### PR TITLE
Use federated namespace instead of the bootstrap cluster's namespace in Ingress e2e tests.

### LINKED ISSUE #31825: [k8s.io] Federated ingresses [Feature:Federation] Federated Ingresses should create and update matching ingresses in underlying clusters {Kubernetes e2e suite}
The addition of the federated namespace adminssion controllers broke this test.  It's an easy fix.  e2e test needs to create the required namespace before trying to create things in it.

@madhusudancs @nikhiljindal FYI. @madhusudancs has volunteered to fix this.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-federation/3660/

Failed: [k8s.io] Federated ingresses [Feature:Federation] Federated Ingresses should create and update matching ingresses in underlying clusters {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federated-ingress.go:115
Creating ingress "federated-ingress" in namespace "e2e-tests-federated-ingress-vkzbl"
Expected error:
    <*errors.StatusError | 0xc820db0300>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "namespaces \"e2e-tests-federated-ingress-vkzbl\" not found",
            Reason: "NotFound",
            Details: {
                Name: "e2e-tests-federated-ingress-vkzbl",
                Group: "",
                Kind: "namespaces",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    namespaces "e2e-tests-federated-ingress-vkzbl" not found
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/federated-ingress.go:289
```

### PR DESCRIPTION
**Pull request by madhusudancs**
This should fix #31825.

cc @kubernetes/sig-cluster-federation @quinton-hoole

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32105)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
I remember fixing this test in my admission control PR (https://github.com/kubernetes/kubernetes/pull/31139)

Looks like https://github.com/kubernetes/kubernetes/pull/29773 is the culprit PR?

File: test/e2e/federated-ingress.go [hunk 1]
```diff
@@ -94,24 +93,24 @@ var _ = framework.KubeDescribe("Federated ingresses [Feature:Federation]", func(
 			jig = newFederationTestJig(f.FederationClientset_1_4)
 			clusters = map[string]*cluster{}
 			primaryClusterName = registerClusters(clusters, UserAgentName, federationName, f)
-			ns = f.Namespace.Name
+			ns = f.FederationNamespace.Name
```
Comment (nikhiljindal) [inline test/e2e/federated-ingress.go]: nit: At other places in this test, we use nsName. Should be consistent.

**Comment by nikhiljindal** [comment]
LGTM, thanks!
