### PR TITLE
fix flaky TestVolumeBinding unit test

### LINKED ISSUE #93009: The unit test TestVolumeBinding is flaky
**Which jobs are flaking**:

The unit test `TestVolumeBinding`

**Which test(s) are flaking**:

```
--- FAIL: TestVolumeBinding (0.71s)
    --- FAIL: TestVolumeBinding/bound_and_unbound_unsatisfied (0.10s)
        volume_binding_test.go:282: call PreFilter and check status
        volume_binding_test.go:291: check state after prefilter phase
        volume_binding_test.go:299: call Filter and check status
        volume_binding_test.go:302: filter status does not match: &{1 [could not find v1.PersistentVolume "pv-a"]}, want: &{3 [node(s) had volume node affinity conflict node(s) didn't find available persistent volumes to bind]}
FAIL
```

**Testgrid link**:

**Reason for failure**:

In volume scheduling, we maintain internal cache which listens on PV/PVC events. However, we don't have a method to wait for them to be synced in UT. 

In production, this is not a problem. Even if the scheduler marks the pod uncacheable due to the stale cache in PVAssumeCache/PVCAssumeCache, the pod will be moved to the active queue later as the scheduler [will move unschedulable pods to the active queue if they are not retried for more than 1 minute](https://github.com/kubernetes/kubernetes/pull/72558).

related:

- https://github.com/kubernetes/kubernetes/pull/73305
- https://github.com/kubernetes/kubernetes/pull/72558

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
fixes #93009 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go [hunk 1]
```diff
@@ -267,19 +264,25 @@ func TestVolumeBinding(t *testing.T) {
 			for _, pv := range item.pvs {
 				client.CoreV1().PersistentVolumes().Create(ctx, pv, metav1.CreateOptions{})
 			}
+
+			t.Log("Start informer factory after initialization")
+			informerFactory.Start(ctx.Done())
```
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:269]: see explanation here: https://github.com/kubernetes/kubernetes/issues/93009#issuecomment-667527689

In my understanding, with a real client and the real API Server events should not be lost.

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:269]: > However, with the fake client, events may be lost in testing.

If you need to act upon the API change events on a UT, I think you have to try prepend/add reactor for a fake client. You can search:

- client.PrependReactor()
- client.PrependWatchReactor()

However, if the test just relies on the a fixed state of all initialized API objects (i think it's the case, correct me if I'm wrong), the current change (start informerFactory and wait for its cache to be synced) should be good enough.

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go [hunk 2]
```diff
@@ -267,19 +264,25 @@ func TestVolumeBinding(t *testing.T) {
...
+
 			caches := informerFactory.WaitForCacheSync(ctx.Done())
 			for _, synced := range caches {
 				if !synced {
 					t.Errorf("error waiting for informer cache sync")
 				}
 			}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:276]: Just for curiosity, is this logic necessary? IMO a common pattern is just:

```go
informerFactory.Start(ctx.Done())
informerFactory.WaitForCacheSync(ctx.Done())
```

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go (hunk 1 above)
Comment (cofyc) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:269]: > However, if the test just relies on the a fixed state of all initialized API objects
yes, it is

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go (hunk 2 above)
Comment (cofyc) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:276]: practically, not necessary. In the current implementation, this function returns with the cache not synced only if the `ctx.Done()` is closed early, which will not happen in our testing.

However, I think it's good practice to check all returned results and fail if something is not expected. This may seem redundant sometimes, but it does not assume anything. For example, controllers in kube-controller-manager may exit if the informers they care can't be synced;

https://github.com/kubernetes/kubernetes/blob/2b9837fdcda0163712a439b71211e34a3f27bd34/pkg/controller/volume/persistentvolume/pv_controller_base.go#L306-L308

Comment (cofyc) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go]: I removed this logic since it's not necessary in our testing. The code is more concise now.

**Comment by Huang-Wei** [comment]
/lgtm
@ahg-g do you want to tag it to 1.19?
