### PR TITLE
Fix a bug that PostFilter plugin may don't function if previous PreFilter plugins return Skip

### LINKED ISSUE #119767: sched: CycleState.SkipFilterPlugins not always injected into cycleState
### What happened?

In k8s 1.27, scheduler introduced a new "short circuit" semantics in PreFilter to bypass a Pod quickly. A change introduced here is it relies on that plugin to be stored in `CycleState.SkipFilterPlugins`, which makes sense as what it was explained [here](https://github.com/kubernetes/kubernetes/pull/114125/files#r1062646736).

However, the `SkipFilterPlugins` info, although is populated upon each plugin's PreFilter invocation, is not injected into `CycleState` when some PreFilter returns unschedulable:

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/scheduler/framework/runtime/framework.go#L655-L661

So think about this workflow:

- pluginA returns Skip in its PreFilter
- pluginB return Unschedulable in its PreFilter
- note: pluginA is not included in `CycleState.SkipFilterPlugins` due to aforementioned bug
- a Pod is claimed as unschedulable (failed by pluginB)
- during PostFilter, it's **supposed** to bypass pluginA's PreEnqueueExtension's AddPod/RemovePod, but it doesn't
- calling a "skipped" Plugin's AddPod/RemovePod during preemption, sometimes will abort the whole preemption as the logic tries to read info from cycleState, and some plugin's "skip" version doesn't fill cycleState properly, e.g., InterPodAffinity (skip immediately w/o write preFilterStateKey).

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L257-L262

### What did you expect to happen?

Short circuiting using Skip is fine, but `CycleState.SkipFilterPlugins` should injected properly at all cases.

### How can we reproduce it (as minimally and precisely as possible)?

Described in the workflow above.

It's firstly captured in an out-of-tree PostFilter plugin: https://github.com/kubernetes-sigs/scheduler-plugins/pull/608#issuecomment-1665855370, but can also happen in in-tree plugins.

### Anything else we need to know?

_No response_

### Kubernetes version

v1.27

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/kind regression
/sig scheduling

#### What this PR does / why we need it:

Ensure SkipFilterPlugins is always injected into cycleState as it's essential for PreFilter plugin to return Skip w/o instantiate their cycleState keys.

#### Which issue(s) this PR fixes:

Fixes #119767

#### Special notes for your reviewer:

Needs to cherry-pick to v1.27

#### Does this PR introduce a user-facing change?

```release-note
Fixed a 1.27 scheduling regression that PostFilter plugin may not function if previous PreFilter plugins return Skip
```

### CODE REVIEW

File: test/integration/scheduler/preemption/preemption_test.go [hunk 1]
```diff
@@ -274,6 +283,32 @@ func TestPreemption(t *testing.T) {
 			}),
 			preemptedPodIndexes: map[int]struct{}{0: {}},
 		},
+		{
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption/preemption_test.go:286]: this duplicates the previous sub-test by just set `enablePreFilter` to true.

**Review by sanposhiho — COMMENTED** [review]
Thanks. This change LGTM. So, the core of this Skip problem is that:
- [before introducing Skip] PreFilter plugin returns Success while storing empty with prefilter key in state.
- [after introducing Skip] PreFilter plugin returns Skip while not storing anything in state.

e.g., Skip introduction in TopologySpread: https://github.com/kubernetes/kubernetes/pull/114889/files

So, after introducing Skip, in PostFilter, AddPod/RemovePod tries to read data from state but cannot find sometimes like [your scenario](https://github.com/kubernetes/kubernetes/issues/119767#issue-1837387143)...

---

And.... apart from this particular Skip problem, I'm now wondering what if this scenario:
- pluginA returns Unschedulable in its PreFilter.
- (Because pluginA returns unschedulable, RunPreFilterPlugins() is aborted at that point and pluginB PreFIlter isn't executed)
- a Pod is claimed as unschedulable (failed by pluginA)
- calling a pluginB's AddPod/RemovePod during preemption, sometimes will abort the whole preemption as the logic tries to read info from cycleState.

What do you think, maybe we've got a similar problem since the older version than introducing Skip...?

**Comment by Huang-Wei** [comment]
> What do you think, maybe we've got a similar problem since the older version than introducing Skip...?

This reminds me of some symptom I spot before... it's likely a general issue. Let me look into the code to check the severity.

**Comment by sanposhiho** [comment]
Anyways, I'm OK to have this change separate from a general bug. It benefits us for the performance reason by skipping.

**Comment by Huang-Wei** [comment]
> Anyways, I'm OK to have this change separate from a general bug. It benefits us for the performance reason by skipping.

Yup, let me create a new issue so we don't derail this PR.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 2]
```diff
@@ -123,6 +124,13 @@ func (fp *tokenFilter) Filter(ctx context.Context, state *framework.CycleState,
 }
 
 func (fp *tokenFilter) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
+	if fp.EnablePreFilter {
+		if fp.Tokens > 0 {
+			return nil, nil
+		} else {
+			return nil, framework.NewStatus(framework.Unschedulable)
+		}
+	}
```
Comment (sanposhiho) [inline test/integration/scheduler/preemption/preemption_test.go:133]: reduce nest

```suggestion
	if !fp.EnablePreFilter {
		return nil
	}
	if fp.Tokens > 0 {
			return nil, nil
	}
	return nil, framework.NewStatus(framework.Unschedulable)
	}
```

**Review by sanposhiho — COMMENTED** [review]
one small nit, LGTM others.

**Comment by sanposhiho** [comment]
And no longer need to cherry-pick for this one? since we'll probably cherry-pick the general bug fix PR to older versions. 
Then we can call it a performance enhancement PR rather than a bug fix.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 2 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption/preemption_test.go]: updated using a slightly different style:

```go
	if !fp.EnablePreFilter || fp.Tokens > 0 {
		return nil, nil
	}
	return nil, framework.NewStatus(framework.Unschedulable)
```

**Comment by Huang-Wei** [comment]
> EDIT: Sorry, we're not sure yet. We need to cherry-pick it if we go with https://github.com/kubernetes/kubernetes/issues/119770#issuecomment-1666390395. And may not need if we choose another way.

Basically we will have 3 PRs fixing their own problems:

1. this one is to fix the bug that preemption may not function for out-of-tree plugins (PreFilter returns `Unschedulable`). This needs to be cherry-picked to v1.27
2. another one is to fix the regression that `UnschedulableAndUnresolvable` is [not honored](https://github.com/kubernetes/kubernetes/issues/119770#issuecomment-1666424312) in default_preempiton. Needs to be cherry-picked to v1.26 and v1.27
3. the last fix is to TBD, which is described in issue [#119770](https://github.com/kubernetes/kubernetes/issues/119770) and exist in all scheduler versions

File: pkg/scheduler/framework/runtime/framework_test.go [hunk 3]
```diff
@@ -1509,8 +1509,8 @@ func TestRunPreFilterPlugins(t *testing.T) {
 					inj:  injectedResult{PreFilterStatus: int(framework.Error)},
 				},
 			},
-			wantPreFilterResult: nil,
-			wantStatusCode:      framework.Error,
+			wantSkippedPlugins: sets.New("skip"),
+			wantStatusCode:     framework.Error,
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework_test.go:1513]: add a test case for a Skip, followed by Unschedulable

File: test/integration/scheduler/preemption/preemption_test.go [hunk 4]
```diff
@@ -100,8 +100,9 @@ func waitForNominatedNodeName(cs clientset.Interface, pod *v1.Pod) error {
 const tokenFilterName = "token-filter"
 
 type tokenFilter struct {
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption/preemption_test.go:102]: add a comment for what this plugin does

File: test/integration/scheduler/preemption/preemption_test.go [hunk 5]
```diff
@@ -123,7 +124,10 @@ func (fp *tokenFilter) Filter(ctx context.Context, state *framework.CycleState,
 }
 
 func (fp *tokenFilter) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
-	return nil, nil
+	if !fp.EnablePreFilter || fp.Tokens > 0 {
+		return nil, nil
+	}
+	return nil, framework.NewStatus(framework.Unschedulable)
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption/preemption_test.go:130]: If this function is never returning Skip, how is it related to the issue?

Comment (Huang-Wei) [reply test/integration/scheduler/preemption/preemption_test.go:130]: Because the testing scheduling profile is atop default one, and default profile includes 3 plugin that return Skip (VolumeRestrictions, PodTopologySpread and InterPodAffinity).

File: pkg/scheduler/framework/runtime/framework_test.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework_test.go:1513]: Default plugins exercised the path already.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 5 above)
Comment (alculquicondor) [reply test/integration/scheduler/preemption/preemption_test.go:130]: Please add a comment in the subtest description about the intention of the test and why it works

File: test/integration/scheduler/preemption/preemption_test.go (hunk 4 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption/preemption_test.go:102]: added.

File: test/integration/scheduler/preemption/preemption_test.go (hunk 5 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption/preemption_test.go:136]: added.

**Comment by Huang-Wei** [comment]
> /lgtm

Squashed. @alculquicondor could you re-lgtm?

I will wait for this PR to get merged (once code freeze lifts), and then create cherry-pick PRs to v1.27 and v1.28.
