### PR TITLE
Use token file for in cluster config during e2e tests

### LINKED ISSUE #69234: 1.12 Running in-cluster e2es no longer respects service account RBAC rules.
**Is this a BUG REPORT**:
Sonobuoy runs the kubernetes e2e's differently then test-infra.  It constructs an in-cluster config vs. being handed a kubeconfig from the infra.  

In 1.12 something has broken this behavior, I'm still digging into the details. 

**What happened**:
Run tests from within the cluster error occurs - 
https://paste.fedoraproject.org/paste/D559nyX6SlGhA3tLPtWt5A

**What you expected to happen**:
Works fine, just like it had in 1.11 

**How to reproduce it (as minimally and precisely as possible)**:
Run tests from within the cluster given proper RBAC rules. 

**Anything else we need to know?**:
Discovered when updating sonobuoy for 1.12.

/sig testing
/kind bug 
/cc @kubernetes/sig-cluster-lifecycle @dims @BenTheElder @kubernetes/cncf-conformance-wg

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I08e792d7c4db2d81861eec6f91028ebf26dea8db

**What this PR does / why we need it**:

In https://github.com/kubernetes/kubernetes/commit/287f6a564fb8c264f281056011f4a66f197b18f4#diff-063e73bab84834a4187b1ad4865050adL337, we stopped initializing BearerToken. We did this because the token file mounted into the container is likely to change, so that PR had a mechanism to re-load the file and pick up new tokens when appropriate. So what we should do to keep the old functionality is to use the token file directly in the temporary kubeconfig we generate.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69234

**Special notes for your reviewer**:

**Release note**:

```release-note
Use the mounted "/var/run/secrets/kubernetes.io/serviceaccount/token" as the token file for running in-cluster based e2e testing.
```

### CODE REVIEW

**Comment by dims** [comment]
based on discussion with @liggitt and @darxkies in https://github.com/kubernetes/kubernetes/pull/69270

**Comment by timothysc** [comment]
@dims did you verify this patch works properly?

**Comment by dims** [comment]
Doing that right now @timothysc

**Comment by dims** [comment]
tested using https://paste.fedoraproject.org/paste/2uDC5PK6UDQQBu5QgJyIoA/raw the change looks good - https://paste.fedoraproject.org/paste/Yx51HND8kz~otYPjl~JGGA/raw

**Review by timothysc — APPROVED** [review]
/approve 

I would like those who made the client-go changes to lgtm this.

**Comment by dims** [comment]
/assign @mikedanese 
/assign @liggitt 

cc @darxkies

File: test/e2e/framework/test_context.go [hunk 1]
```diff
@@ -335,14 +335,17 @@ func ViperizeFlags() {
 }
 
 func createKubeConfig(clientCfg *restclient.Config) *clientcmdapi.Config {
+	const (
+		tokenFile = "/var/run/secrets/kubernetes.io/serviceaccount/token"
```
Comment (mikedanese) [inline test/e2e/framework/test_context.go]: No need for a full const block (or for this to be a const in general)

**Comment by mikedanese** [comment]
lgtm, thanks for fixing!

File: test/e2e/framework/test_context.go (hunk 1 above)
Comment (dims) [reply test/e2e/framework/test_context.go]: Done. thanks @mikedanese

**Comment by liggitt** [comment]
this seems ok as a quick fix, though it's unclear where this file is expected to be used from, and whether it is intended to be portable outside the generating environment.

/lgtm

**Comment by smarterclayton** [comment]
Follow up in https://github.com/kubernetes/kubernetes/pull/71713
