### PR TITLE
Kubelet: Better-defined Container Waiting state

### LINKED ISSUE #17971: ContainerState may be set to Terminated when it should be Waiting.
In kubelet/dockertools/manager.go:

In [`SyncPod()`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1911-L1956), when a container fails to be restarted, we'll store the error reason in the reason cache, and set the container to `Waiting` state in `GetPodStatus()`.

But in [`GetPodStatus()`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L519-L531), when there are historical containers (which means that the corresponding `statuses` will be set in the loop above), only container with `kubecontainer.ErrCrashLoopBackOff.Error()` is set to `Waiting`, while the container fails with other reasons will be set to `Terminated` because of the historical exited containers.

Is this the expected behavior?

/cc @yujuhong @dchen1107

### LINKED ISSUE #20478: Kubelet: Add unit test for PodSyncResult and convertStatusToAPIStatus
We moved **reason cache** and **status convert function** from `dockertools` to `kubelet` by #18172, #19579, #20192 and #20205.

After this, we should also migrate related old unit test to kubelet level.

For `PodSyncResult` we should add test for:
- [x] Different image pull policy.
- [x] Pod creation failure.
- [x] Pod image failure. 

For `convertStatusToAPIStatus` we should add test for:
- [ ] ContainerStatuses order.
- [ ] Last termination state.
- [ ] How reason cache will affect the PodPhase:
  - [ ] Pull image failure reason
  - [ ] Pod creation failure reason

### PR DESCRIPTION
**Pull request by Random-Liu**
For issue #20478 and #21125.

This PR corrected logic and add unit test for `ShouldContainerBeRestarted()`, cleaned up `Waiting` state related code and added unit test for `generateAPIPodStatus()`.

Fixes #20478
Fixes #17971

@yujuhong

### CODE REVIEW

**Comment by Random-Liu** [comment]
@yujuhong I'll think more about this PR. Will ping you if this is ready.

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -3354,65 +3352,54 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *api.Pod, podStatus *kubecontain
...
-			reason == kubecontainer.ErrImagePull ||
-			reason == kubecontainer.ErrImageNeverPull ||
-			reason == kubecontainer.RegistryUnavailable {
-			// mark it as waiting, reason will be filled bellow
-			containerStatus.State = api.ContainerState{Waiting: &api.ContainerStateWaiting{}}
-		} else if reason == kubecontainer.ErrRunContainer {
-			// mark it as waiting, reason will be filled bellow
-			containerStatus.State = api.ContainerState{Waiting: &api.ContainerStateWaiting{}}
+			reason = fmt.Errorf("ContainerCreating")
+			message = fmt.Sprintf("Image: %s is ready, container is creating", container.Image)
```
Comment (derekwaynecarr) [inline pkg/kubelet/kubelet.go]: Do we know for sure that the image is ready here?  This could occur before image pull, no?

File: pkg/kubelet/kubelet_test.go [hunk 2]
```diff
@@ -4303,4 +4303,231 @@ func TestGetPodsToSync(t *testing.T) {
...
+	}
+	podStatus := &kubecontainer.PodStatus{
+		ID:        pod.UID,
+		Name:      pod.Name,
+		Namespace: pod.Namespace,
+	}
+	tests := []struct {
+		containers                   []api.Container
+		statuses                     []*kubecontainer.ContainerStatus
+		reasons                      map[string]error
```
Comment (derekwaynecarr) [inline pkg/kubelet/kubelet_test.go]: can we add an example that has common reasons enumerated?  i.e. RegistryUnavailable, ImagePullBackoff, etc.?

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (Random-Liu) [inline pkg/kubelet/kubelet.go]: @derekwaynecarr Yeah, after some thinking, I found that there is still problems in this PR. I'll think about it and finish the PR soon. Thanks! :)

File: pkg/kubelet/kubelet_test.go (hunk 2 above)
Comment (Random-Liu) [inline pkg/kubelet/kubelet_test.go]: @derekwaynecarr With this PR, we won't rely on specific error enumeration. :)

**Comment by Random-Liu** [comment]
@yujuhong @derekwaynecarr Ready for review.

**Comment by derekwaynecarr** [comment]
The first pass lgtm, I will take a more detailed look this afternoon.  I am really happy to see the if check gone ;-)

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -3315,104 +3313,80 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *api.Pod, podStatus *kubecontain
...
+		}
+		statuses[container.Name] = status
 	}
 
-	containerDone := sets.NewString()
+	// Make the latest container status comes first.
+	sort.Sort(sort.Reverse(kubecontainer.SortContainerStatusesByCreationTime(podStatus.ContainerStatuses)))
+
+	// Set container statuses according to the statuses seen in pod status
+	containerSeen := map[string]int{}
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: What's the reason of counting the containers?

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -3315,104 +3313,80 @@ func (kl *Kubelet) convertStatusToAPIStatus(pod *api.Pod, podStatus *kubecontain
...
-			reason == kubecontainer.ErrImagePull ||
-			reason == kubecontainer.ErrImageNeverPull ||
-			reason == kubecontainer.RegistryUnavailable {
-			// mark it as waiting, reason will be filled bellow
-			containerStatus.State = api.ContainerState{Waiting: &api.ContainerStateWaiting{}}
-		} else if reason == kubecontainer.ErrRunContainer {
-			// mark it as waiting, reason will be filled bellow
-			containerStatus.State = api.ContainerState{Waiting: &api.ContainerStateWaiting{}}
+			// In fact, we could also apply Waiting state here, but it is less informative,
+			// and the container will be restarted soon, so we prefer the original state here.
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: Is the original state "Terminated"?

File: pkg/kubelet/kubelet.go (hunk 3 above)
Comment (Random-Liu) [inline pkg/kubelet/kubelet.go]: Because we've already set the default status in the statuses, we can't rely on `_, found = statuses` + `containerDone` now.

File: pkg/kubelet/kubelet.go (hunk 4 above)
Comment (Random-Liu) [inline pkg/kubelet/kubelet.go]: In fact, could also be waiting or even running, if we don't make any assumption of the implementation of `ShouldContainerBeRestarted`.
But considering the current implementation of `ShouldContainerBeRestarted`, it could be `Waiting` or `Terminated`.

Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: The comment seems to suggest that the original state is a "non-waiting" state. Could you add the potential states to the comment? That'd help people understand the code.

**Comment by yujuhong** [comment]
Thanks for the cleanup! Looks good over all with a nit (comment).

I'll wait for @derekwaynecarr to take a look again.

File: pkg/kubelet/kubelet.go (hunk 4 above)
Comment (Random-Liu) [inline pkg/kubelet/kubelet.go]: Sure! :) Will do that.

Comment (Random-Liu) [inline pkg/kubelet/kubelet.go]: Done.

**Comment by Random-Liu** [comment]
@derekwaynecarr Do you still want to take another look? :)

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #23361.
