### PR TITLE
fix: change default timeout value in csi plugin

### LINKED ISSUE #79528: attach/WaitForAttach timeout value is too small in CSI driver
**What happened**:
attach/WaitForAttach timeout value is too small in CSI driver, it's all 15s which is really too small:
https://github.com/kubernetes/kubernetes/blob/967b23c727c5240bea78dfbcc9dfb09a973defd4/pkg/volume/csi/csi_plugin.go#L57

Compared to built-in driver timeout, it's really too small:
 `podAttachAndMountTimeout` is [2 minutes](https://github.com/kubernetes/kubernetes/blob/b812eaa172804739283e6e8723cbca3ed293e7ff/pkg/kubelet/volumemanager/volume_manager.go#L78), total `waitForAttachTimeout` is [10 minutes](https://github.com/kubernetes/kubernetes/blob/b812eaa172804739283e6e8723cbca3ed293e7ff/pkg/kubelet/volumemanager/volume_manager.go#L86)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13 - 1.15
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig storage
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR changes timeout value in csi plugin from 15s to 2min which fixes the timeout issue

attach/WaitForAttach timeout value is too small in CSI driver, it's all 15s which is really too small:
https://github.com/kubernetes/kubernetes/blob/967b23c727c5240bea78dfbcc9dfb09a973defd4/pkg/volume/csi/csi_plugin.go#L57

Compared to built-in driver timeout, it's really too small:
 `podAttachAndMountTimeout` is [2 minutes](https://github.com/kubernetes/kubernetes/blob/b812eaa172804739283e6e8723cbca3ed293e7ff/pkg/kubelet/volumemanager/volume_manager.go#L78), total `waitForAttachTimeout` is [10 minutes](https://github.com/kubernetes/kubernetes/blob/b812eaa172804739283e6e8723cbca3ed293e7ff/pkg/kubelet/volumemanager/volume_manager.go#L86)

**Which issue(s) this PR fixes**:

Fixes #79528

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
changes timeout value in csi plugin from 15s to 2min which fixes the timeout issue
```

/kind bug
/assign @msau42
/priority important-soon
/sig storage

### CODE REVIEW

**Comment by andyzhangx** [comment]
cc @davidz627

File: pkg/volume/csi/csi_plugin.go [hunk 1]
```diff
@@ -54,7 +54,7 @@ const (
 	// TODO (vladimirvivien) would be nice to name socket with a .sock extension
 	// for consistency.
 	csiAddrTemplate = "/var/lib/kubelet/plugins/%v/csi.sock"
-	csiTimeout      = 15 * time.Second
+	csiTimeout      = 2 * time.Minute
```
Comment (hoyho) [inline pkg/volume/csi/csi_plugin.go]: Not sure what is the best default value. If the csiTimeout can be configurable like other csi sidecar do that will be better.

Comment (andyzhangx) [reply pkg/volume/csi/csi_plugin.go]: @hoyho yes, but now I would like cherry-pick this fix to old release from 1.13 to 1.15, 15s is really too small, it makes the timeout a lot. And when user switch to use CSI driver, they won't be happy to  see that timeout issue every time.

Comment (hoyho) [reply pkg/volume/csi/csi_plugin.go]: agree with you. For our CSI driver, 15s is not enough.

**Comment by davidz627** [comment]
The same timeout is used for `Attach/Mount/Stage/Block` etc. Do we want to split it up into different timeouts for different operations that tend to take different amount of times? I also agree with the premise 15 seconds is far too short.

**Comment by msau42** [comment]
Also keep in mind that the CSI driver should be idempotent and handle another call coming in on the same volume even if one is already in progress.

**Comment by andyzhangx** [comment]
> The same timeout is used for `Attach/Mount/Stage/Block` etc. Do we want to split it up into different timeouts for different operations that tend to take different amount of times? I also agree with the premise 15 seconds is far too short.

I think currently let's change the default timeout value to 2min, for other operations, like Mount, 15s is still too short if there is a large disk to format, 2min is much safer. If we found we need different timeouts in the future, then let's split them up at that time.

File: pkg/volume/csi/csi_plugin.go (hunk 1 above)
Comment (cwdsuzhou) [reply pkg/volume/csi/csi_plugin.go]: I also meet some issues caused by the default time. 

LGTM

**Review by cwdsuzhou — COMMENTED** [review]
could you also cherrypick it to 1.12 1.11

**Comment by andyzhangx** [comment]
cc @jsafrane @saad-ali for approval, thanks.

**Comment by andyzhangx** [comment]
> could you also cherrypick it to 1.12 1.11

1.12, 1.11 is already code freezed, so the latest cherry pick version should be 1.13. @cwdsuzhou

**Comment by jsafrane** [comment]
I must miss something. The linked issue mentions Attach/WaitForAttach timeouts. Taking Attach as example, each `Attach()` call waits for 15 seconds for a volume to get attached and then it returns an error to A/D controller. A/D controller waits for an exponential backoff and re-tries calling `Attach()`. Initial backoff delay is 0.5s and doubles with each error. So for the first two minutes we have:

15s waiting for attachment
0.5s sleep
15s waiting for attachment
1s sleep
...
15s waiting for attachment
16s sleep

(=121.5s total)
In these two minutes, 90 seconds the controller is actively waiting for the attachment and only 31.5s sleeping.

If the volume is attached in first 48.5 seconds, it takes only 2 second max for the controller to notice a volume is attached (that's the max sleep in 3 iterations).

The real difference is the last sleep. If a volume gets attached 90.5s after start, the controller waits for extra 16 seconds to notice it. Is it **really** the case we are trying to fix here? What storage backend takes 90s to attach a volume?

`WaitForAttach`: I may be mistaken here, I think kubelet calls `WaitForAttach` **after** A/D controller reports a volume as attached. A VolumeAttachment should already be in the right state and it should be only a matter of syncing API server `watch()`, which should take fraction of a second in average case.

**Comment by andyzhangx** [comment]
> 15s waiting for attachment

Hi @jsafrane we are talking about the `15s` waiting for attachment value, for a few CSI drivers, the first 15s is too short, there would be timeout error, while it could succeed finally by retry. So make the default timeout value as 120s(identical to built-in driver) would be better.

**Comment by cwdsuzhou** [comment]
@jsafrane @andyzhangx  

I have sent a PR https://github.com/kubernetes/kubernetes/pull/75963 in the past to expose the maxBackoff time which may help  decrease the time `mount` waitis if `attach` lasts for long time.  However, it is hard to be merged.

**Comment by andyzhangx** [comment]
> @jsafrane @andyzhangx
> 
> I have sent a PR #75963 in the past to expose the maxBackoff time which may help decrease the time `mount` waitis if `attach` lasts for long time. However, it is hard to be merged.

Actually timeout value in the built-in driver is 2min (per https://github.com/kubernetes/kubernetes/blob/b812eaa172804739283e6e8723cbca3ed293e7ff/pkg/kubelet/volumemanager/volume_manager.go#L65-L74), while csi driver plugin makes it as only 15s, I think this is a regression. 2min is a suitable value for most drivers, although retry will succeed in the end.

**Comment by jsafrane** [comment]
So the only problem here is a timeout error visible in `kubectl describe pod`?

**Comment by andyzhangx** [comment]
> So the only problem here is a timeout error visible in `kubectl describe pod`?

Yes

**Comment by jsafrane** [comment]
Oh, I expected there is some real issue :-)

/approve

**Comment by andyzhangx** [comment]
> Oh, I expected there is some real issue :-)
> 
> /approve

Thanks, this will make some users nervous if first attach volume failed every time.
