### PR TITLE
There is a rule in using go channel: never close a channel in the

### LINKED ISSUE #45215: no need to close eventCh channel in threshold_notifier_linux.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/threshold_notifier_linux.go#L114

close it may make kubelet crash, though the possibility is small.
keep it open is just ok.
And to avoid getThresholdEvents blocked for ever, stopCh should be passed in it.

```golang
func getThresholdEvents(eventfd int, eventCh chan<- int, stopCh <-chan struct{}) {
	for {
		buf := make([]byte, 8)
		_, err := syscall.Read(eventfd, buf)
		if err != nil {
			return
		}
		
		select {
		case eventCh <- 0:
		case <-stopCh:
			return
		}
	}
}
```

### PR DESCRIPTION
**Pull request by yaxinlx**
receiver side.

fix https://github.com/kubernetes/kubernetes/issues/45215

### CODE REVIEW

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 1]
```diff
@@ -90,28 +90,33 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+	go getThresholdEvents(n.eventfd, eventCh, stopCh)
 	for {
 		select {
 		case <-stopCh:
 			glog.V(2).Infof("eviction: stopping threshold notifier")
 			syscall.Close(n.watchfd)
 			syscall.Close(n.controlfd)
 			syscall.Close(n.eventfd)
-			close(eventCh)
+			// close(eventCh) // may make getThresholdEvents panic
```
Comment (ncdc) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Please delete instead of commenting out

**Comment by ncdc** [comment]
@k8s-bot ok to test

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 1 above)
Comment (go101) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 2]
```diff
@@ -90,28 +90,32 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		select {
+		case eventCh <- 0:
+		case <-stopCh:
+			return
+		}
 	}
 }
 
 func (n *memcgThresholdNotifier) Start(stopCh <-chan struct{}) {
 	eventCh := make(chan int, 1)
```
Comment (timstclair) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: nit: while you're at it can you change this to a `chan struct{}`?

Comment (yaxinlx) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 3]
```diff
@@ -90,28 +90,32 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		case <-stopCh:
+			return
+		}
 	}
 }
 
 func (n *memcgThresholdNotifier) Start(stopCh <-chan struct{}) {
-	eventCh := make(chan int, 1)
-	go getThresholdEvents(n.eventfd, eventCh)
+	eventCh := make(chan struct{}, 1)
```
Comment (timstclair) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Actually, I don't think this channel should be buffered. With the buffer, this is what could happen:

1. stop channel is triggered, causing this function to exit
2. the go function `getThresholdEvents` reads an event (I'm assuming this syscall can block for a long time?)
3. the `eventCh` case is randomly selected in the select statement
4. it goes back to waiting for an event...

Without the buffer, the `eventCh` case will never be selected since there wouldn't be a receiver

Comment (yaxinlx) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Using an unbuffered channel can't avoid the situation too.
However, `syscall.Read(eventfd, buf)` is expected to return an error if `syscall.Close(n.eventfd)` is called.  So `getThresholdEvents` will not wait for ever if stop channel is closed.

But here the buffer for the `eventCh` is really not essential.

**Comment by timstclair** [comment]
lgtm. please squash your commits.

Thanks!

**Comment by yaxinlx** [comment]
squash done.
