### PR TITLE
[kubelet]: fixed container restart due to pod spec field changes

### LINKED ISSUE #122028: Enabling InPlacePodVerticalScaling feature gate causes restart of containers within the cluster
### What happened?

We recently enabled the InPlacePodVerticalScaling feature gate which caused the container spec of our containers to change which in turn triggered container restart logic on the kubelet. All the containers in our cluster we restarted at the same time.

### What did you expect to happen?

Containers shouldn't restart when the InPlacePodVerticalScaling feature gate is enabled

### How can we reproduce it (as minimally and precisely as possible)?

Enable InPlacePodVerticalScaling feature gate, observe k8s events for pods after restarting apiserver:
```
1h39m  Normal   Killing    Container XXX definition changed, will be restarted
```

### Anything else we need to know?

This issue is caused since enabling the feature gate causes the apiserver to update the container spec with a default policy here: https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/apis/core/v1/defaults.go#L181

That causes the logic here to restart the container since the container spec changed: https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L991

You can also easily verify that the container spec changed using kubectl:
```
# before apiserver restart with InPlacePodVerticalScaling feature gate 
$ kubectl get pod XXX -n NNN -o json | grep resize

# after apiserver restart with InPlacePodVerticalScaling feature gate 
$ kubectl get pod XXX -n NNN -o json | grep resize
                "resizePolicy": [
```

### Kubernetes version

<details>

```console
v1.27.5
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd version 1.7.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
The kubelet should hash on fields that it consider as mutable for the life of the container. 

This can prevent pod restarts caused by modification of the pod spec default value in the following two situations:
1. If an alpha field that is not defaulted graduates to adding a default in beta, an API server upgrade from alpha->beta will modify this data.
2. If an field is enabled through feature gate, if we disable the gate or enable the gate, the data will also be modified.

According to https://github.com/kubernetes/website/issues/12326#issuecomment-704469840, we know that pods will be drained when upgrading kubelet, so we can change this mechanism on a minor version boundary.
#### Which issue(s) this PR fixes:

Fixes #122028 #63814

#### Does this PR introduce a user-facing change?

```release-note
Kubelet will not restart the container when fields other than image in the pod spec change.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
@liggitt Could you please tell me if I'm on the right track?

File: pkg/kubelet/container/helpers.go [hunk 1]
```diff
@@ -117,6 +117,22 @@ func HashContainer(container *v1.Container) uint64 {
...
+func HashContainerForContainerChange(container *v1.Container) uint64 {
+	hash := fnv.New32a()
+	containerJSON, _ := json.Marshal(pickFieldToHash(container))
+	hashutil.DeepHashObject(hash, containerJSON)
+	return uint64(hash.Sum32())
+}
+
+// pickFieldToHash pick fields that will affect the running status of the container for hash,
+// currently this field range only contains `image`.
+func pickFieldToHash(container *v1.Container) *v1.Container {
```
Comment (liggitt) [inline pkg/kubelet/container/helpers.go:129]: structurally, this looks plausible to me

I'd like node folks to weigh in on whether there are any other fields that should be conditionally included, especially if the VPA feature is enabled

File: pkg/kubelet/container/helpers.go [hunk 2]
```diff
@@ -117,6 +117,22 @@ func HashContainer(container *v1.Container) uint64 {
...
+	return &v1.Container{
+		Name:  container.Name,
+		Image: container.Image,
+	}
+}
+
 // HashContainerWithoutResources returns the hash of the container with Resources field zero'd out.
 func HashContainerWithoutResources(container *v1.Container) uint64 {
```
Comment (liggitt) [inline pkg/kubelet/container/helpers.go:137]: I think HashContainerWithoutResources should probably go away and HashContainerForContainerChange be made feature-aware so it includes the resources if the feature is enabled and does not include them if the feature is disabled

File: pkg/kubelet/container/helpers.go [hunk 3]
```diff
@@ -117,6 +117,22 @@ func HashContainer(container *v1.Container) uint64 {
 	return uint64(hash.Sum32())
```
[the remark this answers is not in the document]
Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go:117]: It's still called by the `getStableKey` function, I was worried that just name and image wouldn't uniquely identify as container , but double checking the context I think it's ok, because `pod.UUID` is also used in `getStableKey` so we just need to keep a hash function.

File: pkg/kubelet/container/helpers.go (hunk 2 above)
Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go]: Similarly, we only need to keep one hash function, because the intention of `HashContainerWithoutResources` is to prevent container `resource` field changes from restarting the container, and the intention of `HashContainerForContainerChange` (now the name has been changed to `HashContainer`) is the same.

The question now is, do we need to remove [HashWithoutResources](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/kubelet/container/runtime.go#L298-L302) and its related code? Because its content is already the same as [Hash](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/kubelet/container/runtime.go#L297), or is it to be kept until GA+1 as per the comments?

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go]: @kubernetes/sig-node-pr-reviews Would appreciate any advice.

File: pkg/kubelet/container/helpers.go (hunk 1 above)
Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go:120]: @kubernetes/sig-node-pr-reviews Would appreciate any advice.

File: pkg/kubelet/container/helpers.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubelet/container/helpers.go]: > The question now is, do we need to remove [HashWithoutResources](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/kubelet/container/runtime.go#L298-L302) and its related code? Because its content is already the same as [Hash](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/kubelet/container/runtime.go#L297), or is it to be kept until GA+1 as per the comments?

I think we should remove it, the single hash is informed by whether the kubelet has the feature enabled

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go]: removed

File: pkg/kubelet/container/container_hash_test.go [hunk 4]
```diff
@@ -68,7 +68,7 @@ var (
 }
 `
 
-	sampleV115HashValue = uint64(0x311670a)
+	sampleV115HashValue = uint64(0x9c2e6b2f)
 	sampleV116HashValue = sampleV115HashValue
```
Comment (liggitt) [inline pkg/kubelet/container/container_hash_test.go:72]: I'd suggest renaming this to `sampleV131HashValue` and dropping `sampleV116HashValue`

File: pkg/kubelet/container/helpers.go [hunk 5]
```diff
@@ -110,28 +110,18 @@ func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus
...
-	hashWithoutResources := fnv.New32a()
-	containerCopy := container.DeepCopy()
-	containerCopy.Resources = v1.ResourceRequirements{}
-	containerJSON, _ := json.Marshal(containerCopy)
-	hashutil.DeepHashObject(hashWithoutResources, containerJSON)
-	return uint64(hashWithoutResources.Sum32())
+// pickFieldToHash pick fields that will affect the running status of the container for hash,
+// currently this field range only contains `image`.
+func pickFieldToHash(container *v1.Container) *v1.Container {
+	return &v1.Container{
```
Comment (liggitt) [inline pkg/kubelet/container/helpers.go:121]: I have a slight preference for not relying on v1.Container marshaling... can this shift to accumulate into a `map[string]string` we can easily see what will marshal? That means if a new field shows up in Container that marshals by default, it won't destabilize our hash across minor versions

```go
func pickFieldToHash(container *v1.Container) map[string]any {
  retval := map[string]string{
    "name": container.Name,
    "image": container.Image,
  }
  return retval
}
```

File: pkg/kubelet/container/helpers.go (hunk 1 above)
Comment (rphillips) [reply pkg/kubelet/container/helpers.go:120]: There is [this](https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/apis/core/validation/validation.go#L5250-L5259) validation logic which correlates closely to [Pod update and replacement](https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement) documentation. @liggitt map suggestion needs to take into account the fields found in the validation logic+documentation.

Comment (rphillips) [reply pkg/kubelet/container/helpers.go:120]: Hmm. Actually, after thinking about this a bit more, we probably want to leave these additional fields out.

I do think we need to mixin the UID within the hash. Thoughts?

Comment (liggitt) [reply pkg/kubelet/container/helpers.go:120]: only image and resources (when the VPA feature is enabled) can mutate inside containers:

https://github.com/kubernetes/kubernetes/blob/9791f0d1f39f3f1e0796add7833c1059325d5098/pkg/apis/core/validation/validation.go#L5147-L5179

my understanding is that `resources` changing is not expected to instantly restart the container (as would happen if the hash changed) but restart in a controlled way via a separate code path

Comment (liggitt) [reply pkg/kubelet/container/helpers.go:120]: > I do think we need to mixin the UID within the hash. Thoughts?

uid wasn't included before... this is a hash of just the `container` substanza

Comment (liggitt) [reply pkg/kubelet/container/helpers.go:120]: > My general concern is that this change might effect static pods.

Hmm... static pod ingestion generates uids for static pods based on a full hash of the full pod content, which should make modified static manifests show up as a completely different pod uid, right?:
https://github.com/kubernetes/kubernetes/blob/be4b7176dc131ea842cab6882cd4a06dbfeed12a/pkg/kubelet/config/common.go#L58-L71

Also, the kubelet isn't really expecting to handle changes to a container other than image on an update, so I think if static pods are making changes the API wouldn't permit AND hard-coding the uid to skip the unique uid generation for static pods, they're in bug territory already

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 6]
```diff
@@ -982,9 +982,7 @@ func (m *kubeGenericRuntimeManager) computePodActions(ctx context.Context, pod *
 		var reason containerKillReason
 		restart := shouldRestartOnFailure(pod)
 		// Do not restart if only the Resources field has changed with InPlacePodVerticalScaling enabled
-		if _, _, changed := containerChanged(&container, containerStatus); changed &&
-			(!isInPlacePodVerticalScalingAllowed(pod) ||
-				kubecontainer.HashContainerWithoutResources(&container) != containerStatus.HashWithoutResources) {
+		if _, _, changed := containerChanged(&container, containerStatus); changed {
```
Comment (thockin) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:985]: Does this properly handle the case of a Pod's UID appearig to change?  For example, we miss an event (or are down while it happens) which deletes the Pod and recreates it with the same name, but slightly different config?  This has happened in ther places where the object was supposed to be immutable but people find ways around it, on purpose or otherwise.

**Review by thockin — COMMENTED** [review]
Thanks for tagging me.  So so so glad to see this get fixed!!

**Comment by thockin** [comment]
Does this warrant a gate?  Following @wojtek-t discussion on gates, I could MAYBE see this with a starts-beta, on-by-default gate?  Or notm I don't feel too strongly about it.  It's clearly a bugfix, but non-zero risk.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 6 above)
Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:985]: From the defensive programming perspective, we seem to have to do this.

Comment (liggitt) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: We don't need to factor in pod UID here.

The containerStatus we're comparing against comes from podStatus, which is looked up by pod UID.

If the pod uid changes, we won't even have a containerStatus to compare against.

Comment (thockin) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:984]: Great!  Maybe we can drop a comment there so that future readers know this?

Comment (HirazawaUi) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:988]: Comment added

**Comment by thockin** [comment]
Am I the only one who thinks this might need a gate, so if something unforeseen goes wrong, a user can disable this?

**Comment by SergeyKanzhelev** [comment]
> Am I the only one who thinks this might need a gate, so if something unforeseen goes wrong, a user can disable this?

yes. We had many discussions when we were changing this for InPlace VPA. This change seems to be safe, but I need to refresh on what was the discussion before. @HirazawaUi did you check what was the discussion when this was changed for inplace VPA?

**Comment by HirazawaUi** [comment]
> yes. We had many discussions when we were changing this for InPlace VPA. This change seems to be safe, but I need to refresh on what was the discussion before. @HirazawaUi did you check what was the discussion when this was changed for inplace VPA?

After taking a closer look at the comments in https://github.com/kubernetes/enhancements/pull/686 and https://github.com/kubernetes/kubernetes/pull/102884, I see that we didn't cover this area in the comments, but we still had a lot of discussion in the sig-node meetings as well as slack that I can't trace back any further.

/cc @derekwaynecarr @dashpole  @vinaykul 
I would like to ask you to clarify whether I have missed any details. (because you have had a lot of discussions in the KEP of the [In-Place Pod Vertical Scaling feature](https://github.com/kubernetes/enhancements/pull/686))

**Comment by vinaykul** [comment]
Thanks for adding me to the review. At first glance, this looks right. I vaguely recall arguing in a node meeting for similar design where fields that need an action should be included in the hash, and exclude mutable fields that don't ... but I have to dig into the discussion threads to jog my memory. 

I do want to explicitly ask the question whether we should grandfather the currently covered fields? (I don't think it is needed given that upgrade requires node drain .. but there is always the possibility of that one corner-case hiding somewhere). Do we have E2E tests that can validate upgrade workflow with alpha features turned on?

/cc @mikebrow @haircommander to review and verify if any additional fields need to be covered.

**Comment by thockin** [comment]
I am eager to see this go in, and I think it has ripple effects on other KEPs (which can't set default values for new fields without this).  Who owns the final approval on it?

File: pkg/kubelet/container/helpers.go [hunk 7]
```diff
@@ -110,28 +110,20 @@ func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus
...
-	containerCopy.Resources = v1.ResourceRequirements{}
-	containerJSON, _ := json.Marshal(containerCopy)
-	hashutil.DeepHashObject(hashWithoutResources, containerJSON)
-	return uint64(hashWithoutResources.Sum32())
+// pickFieldToHash pick fields that will affect the running status of the container for hash,
+// currently this field range only contains `image` and `name`.
+// Note: this list must be updated if ever kubelet wants to allow mutations to other fields.
+func pickFieldToHash(container *v1.Container) map[string]string {
+	retval := map[string]string{
+		"name":  container.Name,
```
Comment (haircommander) [inline pkg/kubelet/container/helpers.go:123]: why not include fields like ID, or ImageID? These should also be immutable. Are you finding the smallest set of fields that don't require a restart?

Comment (liggitt) [reply pkg/kubelet/container/helpers.go:123]: This is picking the smallest set of mutable fields in the REST API v1.Container that *do* require a restart.

ID and ImageID are not in the v1.Container type

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go:123]: > why not include fields like ID, or ImageID?


We already had some discussion above about not include the pod ID.
ref: https://github.com/kubernetes/kubernetes/pull/124220#discussion_r1577037684 https://github.com/kubernetes/kubernetes/pull/124220#discussion_r1559888960



> Are you finding the smallest set of fields that don't require a restart?

Yes, we would like your help in reviewing and verifying whether other fields in `v1.Container` need to be covered.

Comment (haircommander) [reply pkg/kubelet/container/helpers.go:123]: gotcha, thanks!

**Comment by HirazawaUi** [comment]
/cc @AkihiroSuda @mrunalp @dchen1107 @SergeyKanzhelev  for approve

And do we need to discuss adding gates to control risk proposed by @thockin?

**Comment by mrunalp** [comment]
I am making a pass for node approval.

File: pkg/kubelet/container/helpers.go [hunk 8]
```diff
@@ -110,28 +110,19 @@ func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus
...
-	//TODO(vinaykul,InPlacePodVerticalScaling): Remove this in GA+1 and make HashContainerWithoutResources to become Hash.
-	hashWithoutResources := fnv.New32a()
-	containerCopy := container.DeepCopy()
-	containerCopy.Resources = v1.ResourceRequirements{}
-	containerJSON, _ := json.Marshal(containerCopy)
-	hashutil.DeepHashObject(hashWithoutResources, containerJSON)
-	return uint64(hashWithoutResources.Sum32())
+// pickFieldToHash pick fields that will affect the running status of the container for hash,
+// currently this field range only contains `image`.
+func pickFieldToHash(container *v1.Container) map[string]string {
```
Comment (mrunalp) [inline pkg/kubelet/container/helpers.go:121]: nit: `pickFieldsToHash`

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go]: fixed.

**Review by mrunalp — APPROVED** [review]

**Review by vinaykul — APPROVED** [review]
/lgtm

File: pkg/kubelet/container/helpers.go [hunk 9]
```diff
@@ -110,28 +110,20 @@ func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus
 // Note: remember to update hashValues in container_hash_test.go as well.
 func HashContainer(container *v1.Container) uint64 {
 	hash := fnv.New32a()
-	// Omit nil or empty field when calculating hash value
-	// Please see https://github.com/kubernetes/kubernetes/issues/53644
-	containerJSON, _ := json.Marshal(container)
+	containerJSON, _ := json.Marshal(pickFieldsToHash(container))
```
Comment (dixudx) [inline pkg/kubelet/container/helpers.go:113]: A breaking change here.

This definitely changed the hash value of existing pods. When upgrading from lower version to v1.31, all pods would be restarted.

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go:113]: Upgrading kubelet requires draining the pods on the node. In-place upgrade is not a community-supported upgrade method :)

ref: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#drain-the-node

Comment (dixudx) [reply pkg/kubelet/container/helpers.go:113]: @HirazawaUi This is a breaking change. No additional warning/message is given in the changelog/PR/Kubernetes docs. This is not acceptable!!!

File: pkg/kubelet/container/helpers.go [hunk 10]
```diff
@@ -110,28 +110,20 @@ func ShouldContainerBeRestarted(container *v1.Container, pod *v1.Pod, podStatus
...
-	hashWithoutResources := fnv.New32a()
-	containerCopy := container.DeepCopy()
-	containerCopy.Resources = v1.ResourceRequirements{}
-	containerJSON, _ := json.Marshal(containerCopy)
-	hashutil.DeepHashObject(hashWithoutResources, containerJSON)
-	return uint64(hashWithoutResources.Sum32())
+// pickFieldsToHash pick fields that will affect the running status of the container for hash,
+// currently this field range only contains `image` and `name`.
+// Note: this list must be updated if ever kubelet wants to allow mutations to other fields.
+func pickFieldsToHash(container *v1.Container) map[string]string {
```
Comment (seamounts) [inline pkg/kubelet/container/helpers.go:121]: Does this change not consider compatibility? Clusters with versions lower than 1.32 cannot be upgraded.

File: pkg/kubelet/container/helpers.go (hunk 9 above)
Comment (pacoxu) [reply pkg/kubelet/container/helpers.go:113]: @dixudx Could you open an issue to discuss on the potential regression?

Comment (HirazawaUi) [reply pkg/kubelet/container/helpers.go:113]: Ah, since this is not a community-supported behavior, I didn’t include it in the release note.

I do know that some users in private cloud environments are using in-place upgrade solutions (although, as far as I know, public clouds typically drain pods when upgrading nodes). You’re more than welcome to open an issue so we can discuss this. :)

Comment (thockin) [reply pkg/kubelet/container/helpers.go:113]: We always assume node drains, and we do not spend much effort to make things like cgroups changes safe for in-place updates.

Comment (liggitt) [reply pkg/kubelet/container/helpers.go:113]: Upgrading kubelets across minor versions without draining containers has never been supported and is explicitly not supported in documentation. We don't need to repeat all the things that aren't supported in every minor's release notes.

File: pkg/kubelet/container/helpers.go (hunk 10 above)
Comment (liggitt) [reply pkg/kubelet/container/helpers.go:121]: Clusters can be upgraded following the documented order / procedure at https://kubernetes.io/releases/version-skew-policy/#kubelet-1

Upgrading the kubelet across minor versions in a supported way has always required draining running containers

File: pkg/kubelet/container/helpers.go (hunk 9 above)
Comment (liggitt) [reply pkg/kubelet/container/helpers.go:113]: Let's gather discussion in https://github.com/kubernetes/kubernetes/issues/129385 about whether to try to modify the current behavior in 1.31/1.32 or not.

I'd be strongly inclined not to, since backporting changes for this to patch releases of 1.31 and 1.32 risks breaking people who follow the documented guidelines for upgrading kubelets across minors, in an attempt to support in-place kubelet minor upgrades with running containers, which have never been supported.
