### PR TITLE
RateLimitedQueue TestTryOrdering could fail under load

### LINKED ISSUE #24125: rate_limited_queue_test TestTryOrdering can fail under CPU load
It's possible for TestTryOrdering to flake:

```
--- FAIL: TestTryOrdering (0.02s)
	rate_limited_queue_test.go:179: order was wrong: [first third second]
FAIL
coverage: 61.4% of statements
```

because the test doesn't send back synthetic time.Now() values via the nowFn.  Test should be changed so that it can't fail no matter how slow the CPU is.

### PR DESCRIPTION
**Pull request by smarterclayton**
Remove the possibility of contention in the test by providing a
synthetic Now() function.

Fixes #24125

### CODE REVIEW

File: pkg/controller/node/rate_limited_queue_test.go [hunk 1]
```diff
@@ -152,25 +152,58 @@ func TestTry(t *testing.T) {
 }
 
 func TestTryOrdering(t *testing.T) {
+	defer func() { now = time.Now }()
+	current := time.Unix(0, 0)
+	delay := 0
+	// the current time is incremented by 1ms every time now is invoked
+	now = func() time.Time {
+		if delay > 0 {
```
Comment (liggitt) [inline pkg/controller/node/rate_limited_queue_test.go]: does this need a lock, or is now() only called from a single goroutine?

File: pkg/controller/node/rate_limited_queue_test.go [hunk 2]
```diff
@@ -152,25 +152,58 @@ func TestTry(t *testing.T) {
 }
 
 func TestTryOrdering(t *testing.T) {
+	defer func() { now = time.Now }()
+	current := time.Unix(0, 0)
```
Comment (liggitt) [inline pkg/controller/node/rate_limited_queue_test.go]: start at t=1 and keep the addedAt zero check below?

File: pkg/controller/node/rate_limited_queue_test.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/controller/node/rate_limited_queue_test.go]: Single threaded, Try is a for {} with a rate limiter and a check.

File: pkg/controller/node/rate_limited_queue_test.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/controller/node/rate_limited_queue_test.go]: The addedAt check isn't needed any more (the equivalent exists), and we guarantee that t=0 only matches the "first" entry

**Comment by smarterclayton** [comment]
Any other comments?

**Comment by deads2k** [comment]
@smarterclayton rebase is flaking on this.  Is this in a state I can pick it?

**Comment by smarterclayton** [comment]
Yes

**Comment by smarterclayton** [comment]
Derek needs to review, but I haven't seen flakes without.

**Comment by derekwaynecarr** [comment]
LGTM
