### PR TITLE
Fix:Static pod status is always Init:0/1 if unable to get init container status

### LINKED ISSUE #108537: Static pod status is always Init:0/1 when init container GC'd before kubelet restart.
### What happened?

When init container of static pod was GC'd and kubelet was restarted. The status of the static pod is alway Init:0/1 and never come back to Running.

```shell

kube-controller-manager-paas-192-168-16-112     0/1     Init:0/1                0          11d     192.168.16.112   paas-192-168-16-112   <none>           <none>
kube-controller-manager-paas-192-168-16-113     1/1     Running                 1          11d     192.168.16.113   paas-192-168-16-113   <none>           <none>

```

### What did you expect to happen?

The pod status is Running

### How can we reproduce it (as minimally and precisely as possible)?

1. remove exited init contianer of one static pod.
2. restart kubelet

### Anything else we need to know?

I noticed #96572 makes containers not restarting after init container GC'd. Non-static pod has no problem, but static seems to be affected by it.

### Kubernetes version

<details>

v1.22.1

</details>

### Cloud provider

<details>
Local Cluster
</details>

### OS version

<details>
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR is recreation of old PR #122897 and #108583

> Since static pod has no podstatus saved except in mirror pod, so while init container GC'd and kubelet restarts, static pod can only generate its pod status from current runtime, but after https://github.com/kubernetes/kubernetes/pull/96572 merged, init containers would not be re-created again, so we should reset init-container status for static pod correctly.

#### Which issue(s) this PR fixes:

Fixes #108537

#### Does this PR introduce a user-facing change?

```release-note
Fix static pod status is always Init:0/1 if unable to get init container status from container runtime.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by HirazawaUi** [comment]
Do we have a reliable way to reproduce this issue and present the reproduction process in an e2e test case? Since this is a bug fix, we need to ensure that we’ve fixed it and that future changes won’t break this fix.

**Comment by bitoku** [comment]
@HirazawaUi 

We have a reliable way to reproduce the issue.

https://github.com/kubernetes/kubernetes/issues/108537
> How can we reproduce it (as minimally and precisely as possible)?
    remove exited init contianer of one static pod.
    restart kubelet

But it needs kubelet restart and direct container manipulation. Do we have the existing tests that do those operations?

**Comment by bart0sh** [comment]
/triage accepted

@bitoku please, fix CI failures, thanks!

**Comment by bitoku** [comment]
All tests are green. Can you PTAL?

**Review by hashim21223445 — APPROVED** [review]

**Comment by bitoku** [comment]
Hi! I addressed the comments. PTAL.

**Comment by bitoku** [comment]
The test failure is a known issue.
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/131317/pull-kubernetes-node-kubelet-serial-containerd/1968354120024723456

https://github.com/kubernetes/kubernetes/issues/131703

**Comment by haircommander** [comment]
/lgtm

note to reviewers: I had to read through the [linked PR](https://github.com/kubernetes/kubernetes/pull/96572) to figure out why we weren't re-running the init container in this case (I had thought we may want to do that instead, but the pod has moved past that stage).

**Comment by bitoku** [comment]
/assign @sjenning 
Could you PTAL as an approver?

**Comment by ffromani** [comment]
/assign @mrunalp 

we need a top-level approver it seems

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -2430,6 +2431,16 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
 			if s != nil && s.State == kubecontainer.ContainerStateExited && s.ExitCode == 0 {
 				continue
 			}
+			if s == nil && kubetypes.IsStaticPod(pod) && kuberuntime.HasAnyRegularContainerCreated(pod, podStatus) && statuses[container.Name].State.Waiting != nil {
+				statuses[container.Name].State = v1.ContainerState{
+					Terminated: &v1.ContainerStateTerminated{
+						Reason:   "Completed",
+						Message:  "Unable to get init container status from container runtime and pod has been initialized, treat it as exited normally",
+						ExitCode: 0,
```
Comment (ffromani) [inline pkg/kubelet/kubelet_pods.go:2644]: *non blocking comment*. Reading the code this makes sense. Lacking information, this seems the best available guess about the current state. But assuming good tends to make me wary. So, question: what do we risk here if ignore errors?

Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2644]: Thank you for the comment.
I thought there was no risk, but we may need to take care of sidecar containers differently here.

Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2644]: I removed the sidecar case, so afaict there's no risk here.

**Comment by bitoku** [comment]
pull-kubernetes-unit-windows-master never succeeded recently.
pull-kubernetes-node-kubelet-serial-containerd failure is a known one.
https://github.com/kubernetes/kubernetes/pull/131317#issuecomment-3318740011

Can you PTAL again? @haircommander @ffromani @SergeyKanzhelev

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (swatisehgal) [reply pkg/kubelet/kubelet_pods.go:2644]: > non blocking comment. Reading the code this makes sense. Lacking information, this seems the best available guess about the current state. But assuming good tends to make me wary. So, question: what do we risk here if ignore errors?

This is a great point! While the assumption makes sense given the lack of information, it makes me wonder if there’s a more explicit way to verify that the init container has actually completed. Right now, we’re relying on a heuristic (that if the init container’s status is nil and the app containers are running, it must have finished) but I’m curious if there’s a stronger, more reliable signal we could use to confirm that instead?

File: pkg/kubelet/kubelet_pods.go [hunk 2]
```diff
@@ -2435,6 +2436,24 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
...
+			// We can assume that the init containers are already completed if the main containers are created.
+			// When the init container is a sidecar container, it should be waiting (and will be restarted).
+			isSidecar := container.RestartPolicy != nil && *container.RestartPolicy == v1.ContainerRestartPolicyAlways
+			if s == nil &&
+				kubetypes.IsStaticPod(pod) &&
+				kuberuntime.HasAnyRegularContainerCreated(pod, podStatus) &&
+				!isSidecar &&
+				statuses[container.Name].State.Waiting != nil {
+				statuses[container.Name].State = v1.ContainerState{
+					Terminated: &v1.ContainerStateTerminated{
```
Comment (swatisehgal) [inline pkg/kubelet/kubelet_pods.go:2641]: Might be helpful to add a log message here to indicate that the init container had terminated. WDYT?

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -2435,6 +2436,24 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
...
 				continue
 			}
+			// When the pod is static, init container status might be lost.
+			// We can assume that the init containers are already completed if the main containers are created.
+			// When the init container is a sidecar container, it should be waiting (and will be restarted).
+			isSidecar := container.RestartPolicy != nil && *container.RestartPolicy == v1.ContainerRestartPolicyAlways
+			if s == nil &&
+				kubetypes.IsStaticPod(pod) &&
+				kuberuntime.HasAnyRegularContainerCreated(pod, podStatus) &&
+				!isSidecar &&
```
Comment (swatisehgal) [inline pkg/kubelet/kubelet_pods.go:2638]: Given that sidecar containers are a subset of init containers, how does this logic interact with pods that include sidecars? Does the fallback remain valid when app containers are running alongside both sidecars and init containers? Additionally, are we guaranteed to always retrieve the status of sidecars, or could their status also be missing in some cases?

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2644]: > we’re relying on a heuristic (that if the init container’s status is nil and the app containers are running, it must have finished)

I'd say this is not a heuristic, but the specification of the init container. If init container's status was other than 0, it should be a bug, isn't it?
I'd happy to use that signal if there's any though.

One thing I thought was to store information in the mirror pod, but considering the nature of static pod (it runs separately from api server) the source of truth should be fetched from container runtime, not kube API.

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2638]: > Does the fallback remain valid when app containers are running alongside both sidecars and init containers?

This logic is based on the specification that all regular containers must be running after all non-sidecar init containers are terminated. Whether the pod has sidecar containers doesn't matter. (correct me if I'm wrong)

> Additionally, are we guaranteed to always retrieve the status of sidecars, or could their status also be missing in some cases?

It should be guaranteed to always run, but I think we don't have to care about it because this change doesn't affect sidecar containers' status.
This PR changes only container status decision logic for non-sidecar init containers in static pods, and doesn't change anything else.

File: pkg/kubelet/kubelet_pods.go (hunk 2 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2641]: Actually, this can be called many times, and it may keep logging until the pod is restarted.
Since users can check the status from the pod object, I think we don't want to log here.

File: pkg/kubelet/kubelet_pods.go [hunk 4]
```diff
@@ -2435,6 +2436,24 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
 			if s != nil && s.State == kubecontainer.ContainerStateExited && s.ExitCode == 0 {
 				continue
 			}
+			// When the pod is static, init container status might be lost.
+			// We can assume that the init containers are already completed if the main containers are created.
+			// When the init container is a sidecar container, it should be waiting (and will be restarted).
+			isSidecar := container.RestartPolicy != nil && *container.RestartPolicy == v1.ContainerRestartPolicyAlways
+			if s == nil &&
+				kubetypes.IsStaticPod(pod) &&
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_pods.go]: is there a theoretical possibility that this also can happen with the regular Pod that failed to update Pods status with API server before kubelet restart. Limiting this to static Pods makes the fix less risky, but also creates false perception that this is static Pod-only problem.

File: pkg/kubelet/kubelet_pods.go [hunk 5]
```diff
@@ -2435,6 +2436,24 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
...
+				kuberuntime.HasAnyRegularContainerCreated(pod, podStatus) &&
+				!isSidecar &&
+				statuses[container.Name].State.Waiting != nil {
+				statuses[container.Name].State = v1.ContainerState{
+					Terminated: &v1.ContainerStateTerminated{
+						Reason:   "Completed",
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_pods.go:2642]: Is the effect of this is that kubelet will restart the main container to run the Init container again?

File: test/e2e_node/static_pod_test.go [hunk 6]
```diff
@@ -0,0 +1,222 @@
...
+	"k8s.io/kubernetes/test/e2e/framework"
+	imageutils "k8s.io/kubernetes/test/utils/image"
+	admissionapi "k8s.io/pod-security-admission/api"
+	"k8s.io/utils/ptr"
+
+	"github.com/onsi/ginkgo/v2"
+	"github.com/onsi/gomega"
+)
+
+var _ = SIGDescribe("StaticPod", framework.WithSerial(), func() {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/static_pod_test.go:38]: would be nice to include a subset of these tests to the StandaloneMode tests

File: pkg/kubelet/kubelet_pods.go (hunk 5 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2642]: No, kubelet doesn't restart the init containers and it shouldn't. Even without this change, it doesn't.
This just changes the state of the init containers.
Since the main containers are already running, we can safely assume that the init containers are already terminated successfully.

Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet_pods.go:2642]: ok, so current behavior is a wrong status, not the restart of a main container? just confirming

File: pkg/kubelet/kubelet_pods.go (hunk 4 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go]: It won't happen with regular pods because regular pods' status are stored in api server.
It happens only with static pods because when the kubelet restarts, the pod is created from its static file which doesn't contain pod status.

File: pkg/kubelet/kubelet_pods.go (hunk 5 above)
Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go:2642]: > ok, so current behavior is a wrong status, not the restart of a main container? just confirming

Correct, the current behavior is not restarting the init containers nor the pod.
This PR explains well https://github.com/kubernetes/kubernetes/pull/108583.
> Since static pod has no podstatus saved except in mirror pod, so while init container GC'd and kubelet restarts, static pod can only generate its pod status from current runtime, but after https://github.com/kubernetes/kubernetes/pull/96572 merged, init containers would not be re-created again, so we should reset init-container status for static pod correctly.

File: test/e2e_node/static_pod_test.go (hunk 6 above)
Comment (bitoku) [reply test/e2e_node/static_pod_test.go:38]: You mean we should have the duplicate test in standalone_test, or we should move the test to standalone_test?

File: pkg/kubelet/kubelet_pods.go (hunk 4 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet_pods.go]: it will happen with regular containers if API server was unavailable or status was not updated quickly enough. It is just harder to repro for the regular containers

Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go]: ah right. yes, I can reproduce it. I killed api server while running init container and removed the container after the main container started. I relaunched the api server and it showed Init:0/1.

I'll remove this condition, because it's also true for regular containers that if the main container is running, the init containers should be terminated successfully.

Comment (bitoku) [reply pkg/kubelet/kubelet_pods.go]: Any way to test apiserver disruption in e2e?

Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet_pods.go]: > Any way to test apiserver disruption in e2e?

it is hard, I do not know if we have any examples of it. Please add a comment into code explaining this logic in more details since we cannot create a test for it.

File: test/e2e_node/static_pod_test.go (hunk 6 above)
Comment (SergeyKanzhelev) [reply test/e2e_node/static_pod_test.go:38]: duplicate. I thought the effect of this may be worse - the container will be killed. In Standalone Mode there is no "status" of a Pod. So we mostly need to check that the kubelet restart will not lead to killing of a container or rerunning of an Init container

**Comment by HirazawaUi** [comment]
The failure of the test case "when creating a static pod and restarting kubelet the pod should be running and kubelet not panic" in the `pull-kubernetes-node-e2e-containerd-standalone-mode-serial-all-alpha` test job will be resolved in PR #135165.

The test job added in this PR has also failed, and you'll need to fix it as well.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
