### PR TITLE
Fix nil pointer error in nodevolumelimits csi logging

### LINKED ISSUE #115178: Seg Fault in nodeVolumeLimits of scheduler plugin causing panic
https://github.com/kubernetes/kubernetes/blob/cc68c06f9cb6c70cbb840a8d7b9ca49eb223cb3f/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L233

`isCSIMigrationOn` handles cases when csiNode is nil. This is condition is used by cluster-autoscaler internal working. However, the log line refers to `csiNode.Name` causing seg fault

### PR DESCRIPTION
**Pull request by sunnylovestiramisu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix nil pointer error in logging: https://github.com/kubernetes/kubernetes/issues/115178

#### Which issue(s) this PR fixes:
Fixes #115178

#### Does this PR introduce a user-facing change?

```release-note
Fix 1.25 regression causing a nil pointer error in nodevolumelimits csi logging
```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 1]
```diff
@@ -231,8 +231,12 @@ func (pl *CSILimits) checkAttachableInlineVolume(vol v1.Volume, csiNode *storage
 		return fmt.Errorf("looking up provisioner name for volume %v: %w", vol, err)
 	}
 	if !isCSIMigrationOn(csiNode, inTreeProvisionerName) {
+		csiNodeName := ""
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:234]: Can a unit test with nil CSINode be added?

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:234]: There is no existing test set up but we can add a new TestCheckAttachableInlineVolume

Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:234]: I think the existing test may need some tweaks to be able to pass in a nil CSIDriver:
https://github.com/kubernetes/kubernetes/blob/818dfc6f4147d36522dd4bf18146efec4832f1c1/pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go#L483

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:234]: Modified the test and now if it is a nil node the unit test throws the ```node not found```.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go [hunk 2]
```diff
@@ -661,7 +674,10 @@ func getNodeWithPodAndVolumeLimits(limitSource string, pods []*v1.Pod, limit int
 	default:
 		// Do nothing.
 	}
-
-	nodeInfo.SetNode(node)
+	if isNilNode {
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:677]: We want `csiNode` to be nil, not `node`

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:677]: Then we should modify the getFakeCSIPVLister so that when we call Get the csiNode is nil.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 1 above)
Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:235]: Actually I needed to modify the getFakeCSINodeLister to fake returning a nil csi node.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go [hunk 3]
```diff
@@ -598,8 +610,8 @@ func getFakeCSIStorageClassLister(scName, provisionerName string) fakeframework.
 	}
 }
 
-func getFakeCSINodeLister(csiNode *storagev1.CSINode) fakeframework.CSINodeLister {
-	if csiNode != nil {
+func getFakeCSINodeLister(csiNode *storagev1.CSINode, isNilCsiNode bool) fakeframework.CSINodeLister {
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:613]: It looks like the function already handles a nil `csiNode` input. Do you need to add this extra field?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 4]
```diff
@@ -97,6 +97,7 @@ func (pl *CSILimits) Filter(ctx context.Context, _ *framework.CycleState, pod *v
 	if err != nil {
 		// TODO: return the error once CSINode is created by default (2 releases)
 		klog.V(5).InfoS("Could not get a CSINode object for the node", "node", klog.KObj(node), "err", err)
+		return framework.AsStatus(err)
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:100]: This will cause the scheduler/cluster-autoscaler to retry immediately, as opposed to returning an UnschedulableAndUnresolvable status.

Is retrying the expected behavior?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:235]: I guess this change is not necessary if we return the error?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 4 above)
Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:100]: I think the comment is incorrect as discussed in https://github.com/kubernetes/kubernetes/pull/107787#discussion_r1080559721.

Autoscaler doesn't simulate CSINode objects today, so we can't return an error otherwise autoscaler will fail forever.

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:100]: Oh wait, sorry, this is my miss, I return the error here to checkout the logs I added in the test. But I only removed the logs but forgot to remove this line.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go (hunk 3 above)
Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:613]: Because we cannot set the csiNode to nil before this function, there is a set up step for csiNode.spec.Something. The setup will fail?

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:613]: I just tried to modify the test case for limitSource as node in the **master branch**:

```
{
			newPod:           inTreeOneVolPod,
			existingPods:     []*v1.Pod{inTreeTwoVolPod},
			filterName:       "csi",
			maxVols:          2,
			driverNames:      []string{csilibplugins.AWSEBSInTreePluginName, ebsCSIDriverName},
			migrationEnabled: true,
			limitSource:      "node",
			test:             "should count in-tree volumes if migration is enabled",
		},
```
The test just passed

Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:613]: The test case should use a pod specification using an inline volume.

Also it looks like the FakeLister doesn't return nil in a "not found" scenario: https://github.com/kubernetes/kubernetes/blob/6ec579904c6120b961ed0a1752cd9f92dfb5124c/pkg/scheduler/framework/fake/listers.go#L264

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 5]
```diff
@@ -231,8 +231,15 @@ func (pl *CSILimits) checkAttachableInlineVolume(vol v1.Volume, csiNode *storage
 		return fmt.Errorf("looking up provisioner name for volume %v: %w", vol, err)
 	}
 	if !isCSIMigrationOn(csiNode, inTreeProvisionerName) {
+		csiNodeName := ""
+		if csiNode != nil {
+			csiNodeName = csiNode.Name
+			fmt.Println("===== csiNode lister does not return nil =====")
```
Comment (sunnylovestiramisu) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:237]: Not ready for review yet, just sharing code.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go (hunk 3 above)
Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:613]: inTreeInlineVolPod on master branch testing also did not trigger the painc. Made the change for the fake lister, some other existing tests start to fail:

```
    --- FAIL: TestCSILimits/should_count_in-tree_volumes_if_migration_is_enabled (0.00s)
    --- FAIL: TestCSILimits/should_count_unbound_in-tree_volumes_if_migration_is_enabled (0.00s)
    --- FAIL: TestCSILimits/should_count_in-tree_inline_volumes_if_migration_is_enabled (0.00s)
    --- FAIL: TestCSILimits/should_count_in-tree_and_csi_volumes_if_migration_is_enabled_(when_scheduling_in-tree_volumes) (0.00s)
    --- FAIL: TestCSILimits/should_count_in-tree,_inline_and_csi_volumes_if_migration_is_enabled_(when_scheduling_in-tree_volumes) (0.00s)
    --- FAIL: TestCSILimits/should_count_in-tree_and_csi_volumes_if_migration_is_enabled_(when_scheduling_csi_volumes) (0.00s)

```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 6]
```diff
@@ -231,8 +232,12 @@ func (pl *CSILimits) checkAttachableInlineVolume(vol v1.Volume, csiNode *storage
 		return fmt.Errorf("looking up provisioner name for volume %v: %w", vol, err)
 	}
 	if !isCSIMigrationOn(csiNode, inTreeProvisionerName) {
+		csiNodeName := ""
+		if csiNode != nil {
```
Comment (sunnylovestiramisu) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:236]: The mock is working as expected even in the master code, even the test case said that migration is enabled, on line old 291, new 296:

```
if !isCSIMigrationOn(csiNode, pluginName) {
  klog.V(5).InfoS("CSI Migration of plugin is not enabled", "plugin", pluginName)
  return "", ""
}
```

This got returned.

**Comment by sunnylovestiramisu** [comment]
It turned out the original test setup did not reflect the reality, the name of csi-node and node should be the same.

Added extra logs locally( please see [here](https://github.com/kubernetes/kubernetes/compare/master...sunnylovestiramisu:kubernetes:localTest#diff-6946ee8d41a5c420ad3217a1f66b472427fc333bca35d2029406ba398682c02aR237) ) to test the csi node == nil: 

```
// go test -v -run TestCSILimits
=== RUN   TestCSILimits/nil_csi_node
===== haha I am a nil csi node  =====
```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go [hunk 7]
```diff
@@ -305,6 +306,17 @@ func TestCSILimits(t *testing.T) {
...
 		},
+		{
+			newPod:           inTreeInlineVolPod,
+			existingPods:     []*v1.Pod{inTreeTwoVolPod},
+			filterName:       "csi",
+			maxVols:          2,
+			driverNames:      []string{csilibplugins.AWSEBSInTreePluginName, ebsCSIDriverName},
+			migrationEnabled: true,
+			isNilCsiNode:     true,
+			limitSource:      "csinode",
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: are you able to repro the error if you set `limitSource` to `node` and without needing `isNilCsiNode`?

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: We need the isNilCsiNode to generate the nil pointer exception? If I commented out the csiNodeName and log the csiNode.Name the test returns error:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13ba74d]
```

Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: when `limitSource == node`, I believe that should also cause csiNode to be nil: https://github.com/kubernetes/kubernetes/blob/250497ebca681fa8c054cac45bb5d8438b67d7a4/pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go#L663

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: I tried again the same test case as the comment above:

```
{
    newPod:           inTreeOneVolPod,
    existingPods:     []*v1.Pod{inTreeTwoVolPod},
    filterName:       "csi",
    maxVols:          2,
    driverNames:      []string{csilibplugins.AWSEBSInTreePluginName, ebsCSIDriverName},
    migrationEnabled: true,
    limitSource:      "node",
    test:             "should count in-tree volumes if migration is enabled",
    wantStatus:       framework.NewStatus(framework.Unschedulable, ErrReasonMaxVolumeCountExceeded),
}
```

It did not trigger the csiNode == nil, it did not go into the ```if !isCSIMigrationOn(csiNode, inTreeProvisionerName)``` code path.

Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: I checked out your PR, reverted csi.go, and tweaked the test inputs and was able to repro the crash:
```
--- a/pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go
+++ b/pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go
@@ -313,8 +313,8 @@ func TestCSILimits(t *testing.T) {
                        maxVols:          2,
                        driverNames:      []string{csilibplugins.AWSEBSInTreePluginName, ebsCSIDriverName},
                        migrationEnabled: true,
-                       isNilCsiNode:     true,
-                       limitSource:      "csinode",
+                       isNilCsiNode:     false,
+                       limitSource:      "node",
                        test:             "nil csi node",
                },
```

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: > We need the isNilCsiNode to generate the nil pointer exception? I commented out the csiNodeName and log the csiNode.Name the test returns error:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13ba74d]
> ```

This was ran with:

```
{
			newPod:           inTreeInlineVolPod,
			existingPods:     []*v1.Pod{inTreeTwoVolPod},
			filterName:       "csi",
			maxVols:          2,
			driverNames:      []string{csilibplugins.AWSEBSInTreePluginName, ebsCSIDriverName},
			migrationEnabled: true,
			isNilCsiNode:     true,
			limitSource:      "csinode",
}
```

without the change:

```
csiNodeName := ""
if csiNode != nil {
	csiNodeName = csiNode.Name
}
```

also generated the nil pointer exception, do we need another test case specific to
```
 isNilCsiNode:     false,
limitSource:      "node",
```?

Comment (msau42) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go:317]: correct

Comment (sunnylovestiramisu) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go]: Updated

**Comment by sunnylovestiramisu** [comment]
Tests failed with ```bytes-like object, not str```, which looks like a python2 vs python3 issue, a few other PRs also running into the same error:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1116

**Comment by msau42** [comment]
Can you add a release note for the fix? We'll want to cherry pick this.

**Review by alculquicondor — COMMENTED** [review]
LGTM from scheduling
