### PR TITLE
forbid sysctls for pod sharing the respective namespaces with the host

### LINKED ISSUE #118702: HostNet Pod with sysctl changing ip_local_port_range should be refused by apiserver
_Originally posted by @cheese39 in https://github.com/kubernetes/kubernetes/issues/72593#issuecomment-1594111801_
            

> Should such a deployment be rejected created? Because after the deployment is successfully created, pods are generated crazy and my k8s cluster crashes.I looked at the other cases in the issue and it didn't feel the same as mine.

```
apiVersion: v1
kind: Pod
metadata:
  name: sysctl-2
spec:
  hostNetwork: true
  securityContext:
    sysctls:
    - name: net.ipv4.ip_local_port_range
      value: "40000 65535"
  containers:
  - name: sysctl
    image: docker.m.daocloud.io/library/nginx:1.14.1
    securityContext:
      privileged: true
```

pod will be created, but rejected by kubelet.
```
 Events:
  Type     Reason           Age   From               Message
  ----     ------           ----  ----               -------
  Normal   Scheduled        98s   default-scheduler  Successfully assigned default/sysctl-2 to daocloud
  Warning  SysctlForbidden  99s   kubelet            forbidden sysctl: "net.ipv4.ip_local_port_range" not allowed with host net enabled
```

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/118702
 @cheese39  meet in https://github.com/kubernetes/kubernetes/issues/72593#issuecomment-1594132992

#### Special notes for your reviewer:

If a pod with a such case is already created, the pod should be rejected by kubelet in `SysctlForbiden` status.
- Users should delete those pods.

Validation only fails when creating a pod or updating a pod pod without the forbid sysctls. If the pod already has forbid sysctls, the update will not fail. 

#### Does this PR introduce a user-facing change?

```release-note
forbid sysctls for pod sharing the respective namespaces with the host when creating and update pod without such sysctls
```

### CODE REVIEW

**Comment by pacoxu** [comment]
I will rebase after https://github.com/kubernetes/kubernetes/pull/118707 is merged.

**Comment by liggitt** [comment]
/hold

until the question at https://github.com/kubernetes/kubernetes/issues/118702#issuecomment-1633127718 is resolved

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -4422,7 +4423,7 @@ func IsValidSysctlName(name string) bool {
 	return sysctlContainSlashRegexp.MatchString(name)
 }
 
-func validateSysctls(sysctls []core.Sysctl, fldPath *field.Path) field.ErrorList {
+func validateSysctls(sysctls []core.Sysctl, fldPath *field.Path, hostNetwork, hostIPC bool) field.ErrorList {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4426]: /hold

standard questions when we want to tighten validation:
* does it prevent a no-op update of existing persisted objects that would fail this new validation? (would block storage migration tasks)
* does it prevent deletion of existing persisted objects with finalizers that would fail this new validation? (update is required to remove finalizers to allow deletion)
* does it prevent controllers from updating status of existing persisted objects that would fail this new validation?

we could consider ratcheting validation:
* apply this tightened validation on create
* apply this tightened validation on update where the old object passed this validation (don't let a valid object become invalid)
* skip this tightened validation on update where the old object fails this validation

c.f. https://github.com/kubernetes/kubernetes/issues/59984

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -4433,11 +4434,43 @@ func validateSysctls(sysctls []core.Sysctl, fldPath *field.Path) field.ErrorList
 		} else if _, ok := names[s.Name]; ok {
 			allErrs = append(allErrs, field.Duplicate(fldPath.Index(i).Child("name"), s.Name))
 		}
+		// The parameters hostNet and hostIPC are used to forbid sysctls for pod sharing the
+		// respective namespaces with the host.
+		if !isValidSysctlWithHostNetIPC(s.Name, hostNetwork, hostIPC) {
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply pkg/apis/core/validation/validation.go]: Good point. It will make the logic much clear

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (pacoxu) [reply pkg/apis/core/validation/validation.go]: I have thought about it at first and most pod attributes are mutable. 

Yes, we should follow the process to tighten the update to add invalid sysctl and creation.

I updated the PR based on your comments.

As Pod spec'ssysctl can not be updated, we only need to handle pod template parts.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 3]
```diff
@@ -25,24 +25,24 @@ type Namespace string
 
 const (
 	// the Linux IPC namespace
-	ipcNamespace = Namespace("ipc")
+	IpcNamespace = Namespace("ipc")
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Updated.

File: pkg/apis/apps/validation/validation.go [hunk 4]
```diff
@@ -357,8 +357,11 @@ func ValidateDaemonSetSpec(spec, oldSpec *apps.DaemonSetSpec, fldPath *field.Pat
 	if spec.Selector != nil && len(spec.Selector.MatchLabels)+len(spec.Selector.MatchExpressions) == 0 {
 		allErrs = append(allErrs, field.Invalid(fldPath.Child("selector"), spec.Selector, "empty selector is invalid for daemonset"))
 	}
-
-	allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(&spec.Template, fldPath.Child("template"), opts)...)
+	var existingTemplate *api.PodTemplateSpec
+	if oldSpec != nil {
+		existingTemplate = &oldSpec.Template
+	}
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply pkg/apis/apps/validation/validation.go]: The options help to make things easier.

Updated.

**Comment by pacoxu** [comment]
> /hold
> 
> until the question at [#118702 (comment)](https://github.com/kubernetes/kubernetes/issues/118702#issuecomment-1633127718) is resolved

I think we can unhold it.
/unhold

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 5]
```diff
@@ -25,24 +25,24 @@ type Namespace string
 
 const (
 	// the Linux IPC namespace
-	ipcNamespace = Namespace("ipc")
+	IPCNamespace = Namespace("ipc")
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:28]: Constants are usually named in caps.  `Namespace("IPC")`, `Namespace("Net")` - do these string literals need to be lower-case for some reason?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 6]
```diff
@@ -56,5 +56,16 @@ func NamespacedBy(val string) Namespace {
 			return ns
 		}
 	}
-	return unknownNamespace
+	return UnknownNamespace
+}
+
+// sysctlOrPrefix is prefix if the suffix is *, and sysctlOrPrefix will be trimed and `_` will be replace by dots.
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:62]: a) This comment should be go-doc style ("GetNamespace does some stuff...")

b) I can't tell what this does from the comment.  Please explain it more clearly, and even include an example if needed.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 7]
```diff
@@ -25,24 +25,24 @@ type Namespace string
...
 	// the network namespace
-	netNamespace = Namespace("net")
+	NetNamespace = Namespace("net")
 
 	// the zero value if no namespace is known
-	unknownNamespace = Namespace("")
+	UnknownNamespace = Namespace("")
 )
 
 var namespaces = map[string]Namespace{
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:37]: Can you comment each of these maps, explaining wht they are?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go [hunk 8]
```diff
@@ -98,3 +98,31 @@ func (*procSysctl) GetSysctl(sysctl string) (int, error) {
...
+func ConvertSysctlVariableToDotsSeparator(val string) string {
+	if val == "" {
+		return val
+	}
+	firstSepIndex := strings.IndexAny(val, "./")
+	if firstSepIndex == -1 || val[firstSepIndex] == '.' {
+		return val
+	}
+
+	f := func(r rune) rune {
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:118]: Can you please comment why this is flipping dots and slashes?   I don't get it.

Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:118]:
```
		{in: "net.ipv4.conf.eno2/100.rp_filter", out: "net.ipv4.conf.eno2/100.rp_filter"},
		{in: "net/ipv4/conf/eno2.100/rp_filter", out: "net.ipv4.conf.eno2/100.rp_filter"},
```
The `ConvertSysctlVariableToDotsSeparator` will return directly if the first found  `.` or `/` is `.`. Line 1 above. I will keep the val as it.

It will convert all `.` to `/` and all `/` to `.` for the second line. If the first found `.` or `/` is `/`.
It will do a `swap` behavior.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 6 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Add some comments.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 5 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Updated.

File: pkg/apis/core/validation/validation.go [hunk 9]
```diff
@@ -4572,22 +4575,50 @@ func IsValidSysctlName(name string) bool {
...
 }
 
+// ValidateHostSysctl will return error if namespaced sysctls is applied to pod sharing the respective namespaces with the host.
+func ValidateHostSysctl(sysctl string, securityContext *core.PodSecurityContext, fldPath *field.Path) *field.Error {
+	ns, _, _ := utilsysctl.GetNamespace(sysctl)
+	switch {
+	case securityContext.HostNetwork && ns == utilsysctl.NetNamespace:
+		return field.Invalid(fldPath, sysctl, "not allowed with host net enabled")
+	case securityContext.HostIPC && ns == utilsysctl.IPCNamespace:
+		return field.Invalid(fldPath, sysctl, "not allowed with host ipc enabled")
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply pkg/apis/core/validation/validation.go]: A validation error message: `may` implies `uncertainty`. However, the message already includes `Invalid`, so this is OK.

I updated the message.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go (hunk 8 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:121]: BTW, the original place of this function is https://github.com/opencontainers/runc/blob/cf4c7c902b4529904a51f85785b61bf04d7351d1/libcontainer/configs/validate/validator.go#L134-L161.

I moved it here from https://github.com/kubernetes/kubernetes/blob/2f270bd99609561be53893d3c7fc77d8efe7ac4e/pkg/kubelet/sysctl/util.go#L25-L52.

File: pkg/apis/core/validation/validation.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/apis/core/validation/validation.go]: We have conventions for error messages.  :)

English is a little too ambiguous, but "may not" usually implies permission rather than probability.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go (hunk 8 above)
Comment (thockin) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:121]: I get WHAT it does, just not WHY

File: pkg/apis/core/validation/validation.go [hunk 10]
```diff
@@ -4572,22 +4575,50 @@ func IsValidSysctlName(name string) bool {
 	return sysctlContainSlashRegexp.MatchString(name)
 }
 
-func validateSysctls(sysctls []core.Sysctl, fldPath *field.Path) field.ErrorList {
+// Contains returns true if the specified item is in the list of items
+func Contains(items []core.Sysctl, item core.Sysctl) bool {
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:4579]: Does this need to be a public function?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+
+	// refer to https://man7.org/linux/man-pages/man7/network_namespaces.7.html
+	// the network namespace
+	NetNamespace = Namespace("Net")
+
+	// the zero value if no namespace is known
+	UnknownNamespace = Namespace("")
+)
+
+var namespaces = map[string]Namespace{
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:39]: What I really waned (want) is good names that indicate what this is.  "namespaces" suggests a list or something, but it's a map.

`sysctlToNamespace` or `sysctlNamespaceMap` or `nameToNamespace` or something would be clearer.

I kind of like `nameToNamespace`  ?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+	// kernel semaphore parameters: SEMMSL, SEMMNS, SEMOPM, and SEMMNI.
+	"kernel.sem": IPCNamespace,
+}
+
+var prefixNamespaces = map[string]Namespace{
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:44]: `prefixToNamespace`

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 13]
```diff
@@ -0,0 +1,92 @@
...
+	// kernel shared memory limits include shmall, shmmax, shmmni, and shm_rmid_forced.
+	"kernel.shm": IPCNamespace,
+	// kernel messages include msgmni, msgmax and msgmnb.
+	"kernel.msg": IPCNamespace,
+	// mqueue filesystem provides the necessary kernel features to enable the creation
+	// of a user space library that implements the POSIX message queues API.
+	"fs.mqueue.": IPCNamespace,
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:51]: Why do some end in dots and some not?  This is basically an API - document it.

Edit: I see what is going on and I hate it.  I'd rather see msgmni, msgmax and msgmnb called out explicitly and require that prefixes be "directories" only.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 14]
```diff
@@ -0,0 +1,92 @@
...
+	"net.":       NetNamespace,
+}
+
+// NamespacedBy returns the namespace of the Linux kernel for a sysctl, or
+// unknownNamespace if the sysctl is not known to be namespaced.
+func NamespacedBy(val string) Namespace {
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:57]: This is a sort of awkward name.  Maybe `NamespaceOf` or `GetNamespace` ?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 15]
```diff
@@ -0,0 +1,92 @@
...
+		}
+	}
+	return UnknownNamespace
+}
+
+// GetNamespace extracts information from a sysctl string. It returns:
+//  1. The sysctl namespace, which can be one of the following: IPC, Net, or unknown.
+//  2. sysctlOrPrefix: the prefix of the sysctl parameter, excluding the trailing '*'.
+//     If there is no '*' suffix, it will be an empty string.
+//  3. 'prefixed' is set to true if the sysctl parameter has a prefix with a colon (':').
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:73]: I don't see colons in the example below, but it sets `prefixed` ?

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go [hunk 16]
```diff
@@ -0,0 +1,92 @@
...
+//
+// For example, if the input sysctl is 'net.ipv6.neigh.*', GetNamespace will return:
+// - The Net namespace
+// - The sysctlOrPrefix as 'net.ipv6.neigh'
+// - 'prefixed' set to true
+//
+// For the input sysctl 'net.ipv6.conf.all.disable_ipv6', GetNamespace will return:
+// - The Net namespace
+// - An empty sysctlOrPrefix
```
Comment (thockin) [inline staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:82]: This return value is weird... is says "sysctl or prefix".  Why is it empty?  Empty is neither the sysctl nor the prefix.

The bar for public APIs needs to be pretty high

**Review by thockin — COMMENTED** [review]
Why are we jamming sysctl related functions into component-helpers ?  This is becoming  another dumping ground for random stuff.  These are all public APIs...

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go (hunk 8 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:121]: > I get WHAT it does, just not WHY

This is a kernel implementation IMO.

> Note that either "/" or "."  may be used as separators within
>        sysctl variable names. If the first separator is a slash,
>        remaining slashes and dots are left intact. If the first
>        separator is a dot, dots and slashes are interchanged.
>        "kernel.domainname=foo" and "kernel/domainname=foo" are
>        equivalent and will cause "foo" to be written to
>        /proc/sys/kernel/domainname. Either
>        "net.ipv4.conf.enp3s0/200.forwarding" or
>        "net/ipv4/conf/enp3s0.200/forwarding" may be used to refer to
>        /proc/sys/net/ipv4/conf/enp3s0.200/forwarding. A glob [glob(7)](https://man7.org/linux/man-pages/man7/glob.7.html)
>        pattern may be used to write the same value to all matching keys.
>        Keys for which an explicit pattern exists will be excluded from
>        any glob matching. In addition, a key may be explicitly excluded
>        from being set by any matching glob patterns by specifying the
>        key name prefixed with a "-" character and not followed by "=",
>        see SYNOPSIS.

from https://man7.org/linux/man-pages/man5/sysctl.d.5.html

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 12 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Updated.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 11 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Use `nameToNamespace`.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 14 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: Use `NamespaceOf` here.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 15 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: This is a wrong comment. Updated.

**Comment by pacoxu** [comment]
> Why are we jamming sysctl-related functions into component-helpers ? This is becoming another dumping ground for random stuff. These are all public APIs...

The function should be used in both kubelet and apis pkg, and I found `staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go` which already contains some sysctl related utils. This is the reason I moved them here.
- `pkg/kubelet/sysctl/allowlist.go`
- `pkg/apis/core/validation/validation.go`

I don't have a better/suggested pkg for such functions.

> The bar for public APIs needs to be pretty high

Probably, we can move it somewhere else.

File: pkg/kubelet/sysctl/allowlist_test.go [hunk 17]
```diff
@@ -1,3 +1,6 @@
+//go:build linux
+// +build linux
+
```
Comment (pacoxu) [inline pkg/kubelet/sysctl/allowlist_test.go:3]: - `SafeSysctlAllowlist`  
https://github.com/kubernetes/kubernetes/blob/015297a5776aa036c334c89740f89f74cb83190c/pkg/kubelet/sysctl/safe_sysctls.go#L76-L80

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 13 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:51]: Agree.

I am afraid that we have to keep it as is until we have a better solution.

Comment (thockin) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go:51]: ?

Why isn't the better solution to put `msgmni`, `msgmax`, and `msgmnb` into the `nameToNamespace` map ?  Then you can append `.` when comparing the val to the prefix map.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go (hunk 8 above)
Comment (thockin) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:121]: Thanks....BARF!

Can we rename this func to `Normalize` or `NormalizeName` ?

File: pkg/apis/core/validation/validation.go (hunk 10 above)
Comment (pacoxu) [reply pkg/apis/core/validation/validation.go]: Removed.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go (hunk 13 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/namespace.go]: That sounds good as there are only 7 items. 
- shmall, shmmax, shmmni, and shm_rmid_forced
- msgmni, msgmax and msgmnb.

File: staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go (hunk 8 above)
Comment (pacoxu) [reply staging/src/k8s.io/component-helpers/node/util/sysctl/sysctl.go:121]: Updated.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

File: staging/src/k8s.io/component-helpers/go.mod [hunk 18]
```diff
@@ -6,6 +6,7 @@ go 1.20
 
 require (
 	github.com/google/go-cmp v0.5.9
+	github.com/stretchr/testify v1.8.3
```
Comment (pacoxu) [inline staging/src/k8s.io/component-helpers/go.mod:9]: Rebase for this updatedz.

**Comment by thockin** [comment]
Still conflict

**Comment by pacoxu** [comment]
Rebased

The `needs-rebase` label is still there 🤣
