### PR TITLE
fix: Truncate too long Deployment name in RS name

### LINKED ISSUE #116447: Deployment names can be too long, such that ReplicaSet creation fails
This Deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: use-a-very-long-name-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-12
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamyouare
  template:
    metadata:
      labels:
        app: iamyouare
    spec:
      containers:
      - image: thockin/iamyouare
        name: iamyouare
```

...is accepted but always fails:

```
Events:
  Type     Reason                 Age                From                   Message
  ----     ------                 ----               ----                   -------
  Warning  ReplicaSetCreateError  1s (x13 over 22s)  deployment-controller  Failed to create new replica set "use-a-very-long-name-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-12-6bb58d578b": ReplicaSet.apps "use-a-very-long-name-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-12-6bb58d578b" is invalid: metadata.name: Invalid value: "use-a-very-long-name-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-12-6bb58d578b": must be no more than 253 characters
```

Deployment controller needs to truncate it's own name to make room for the ReplicaSet suffix and eventually the pod suffix.

### PR DESCRIPTION
**Pull request by hdp617**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When generating a replica set name, truncate the deployment name if it is too long. This fixes #116447 that fails to create a replica set when a deployment name is too long.

#### Which issue(s) this PR is related to:
Fixes #116447

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug that fails to create a replica set when a deployment name is too long.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by hdp617** [comment]
@janetkuo @aaron-prindle Going with Option 1 as mentioned in https://github.com/kubernetes/kubernetes/issues/116447#issuecomment-3001843496. Could you take a look? Thanks!

File: pkg/controller/deployment/sync.go [hunk 1]
```diff
@@ -549,3 +550,15 @@ func (dc *DeploymentController) isScalingEvent(ctx context.Context, d *apps.Depl
 	}
 	return false, nil
 }
+
+// generateReplicaSetName generates a ReplicaSet name by adding a pod template spec hash
+// to a Deployment name, optionally truncating it to ensure the ReplicaSet name is within the limit.
+func generateReplicaSetName(deploymentName, podTemplateSpecHash string) string {
+	maxDeploymentNameLength := validation.DNS1123SubdomainMaxLength - 1 - len(podTemplateSpecHash)
```
Comment (janetkuo) [inline pkg/controller/deployment/sync.go]: Handle the case when `maxDeploymentNameLength <= 0`. It should not happen, but it's safer to handle that to avoid panics just in case.

File: pkg/controller/deployment/sync.go [hunk 2]
```diff
@@ -549,3 +550,15 @@ func (dc *DeploymentController) isScalingEvent(ctx context.Context, d *apps.Depl
...
+
+	if len(deploymentName) <= maxDeploymentNameLength {
+		return deploymentName + "-" + podTemplateSpecHash
+	}
+
+	return deploymentName[:maxDeploymentNameLength] + "-" + podTemplateSpecHash
```
Comment (janetkuo) [inline pkg/controller/deployment/sync.go]: nit: it's slightly more readable to put the special case (deployment name too long) in the `if` and return the common case. Suggest swapping the returns.

File: pkg/controller/deployment/sync_test.go [hunk 3]
```diff
@@ -592,3 +594,74 @@ func TestDeploymentController_cleanupDeploymentOrder(t *testing.T) {
...
+			name:             "very long name truncated",
+			deploymentName:   strings.Repeat("a", 250),
+			wantRSNamePrefix: strings.Repeat("a", 242) + "-",
+		},
+		{
+			name:             "very long name not truncated",
+			deploymentName:   strings.Repeat("a", 242),
+			wantRSNamePrefix: strings.Repeat("a", 242) + "-",
+		},
+	}
```
Comment (janetkuo) [inline pkg/controller/deployment/sync_test.go:619]: nit: Test the edge case of hash length. If the hash implementation were to change, this test might silently pass while the actual name generation breaks. You can do that in a direct unit test of `generateReplicaSetName`.

File: pkg/controller/deployment/sync_test.go [hunk 4]
```diff
@@ -592,3 +594,74 @@ func TestDeploymentController_cleanupDeploymentOrder(t *testing.T) {
...
+					}
+				}
+			}
+		}
+
+		if len(rsName) > validation.DNS1123SubdomainMaxLength {
+			t.Errorf("generated name length %d, want <= %d", len(rsName), validation.DNS1123SubdomainMaxLength)
+		}
+
+		if !strings.HasPrefix(rsName, test.wantRSNamePrefix) {
```
Comment (aaron-prindle) [inline pkg/controller/deployment/sync_test.go]: nit: This test should likely verify the complete ReplicaSet name format and hash preservation is as expected, not just the prefix.  Below is an example of some possible additional validations:

https://gist.github.com/aaron-prindle/d831cfa6dce6a7d072f7449d76f433e9

File: pkg/controller/deployment/sync_test.go (hunk 3 above)
Comment (aaron-prindle) [reply pkg/controller/deployment/sync_test.go:619]: +1, for adding a direct unit test for generateReplicaSetName

File: pkg/controller/deployment/sync.go (hunk 1 above)
Comment (aaron-prindle) [inline pkg/controller/deployment/sync.go]: nit: The number 1 (for the hyphen separator IIUC) should likely have a comment explaining what the 1 represents.

alternatively the separator could be a constant and referenced that way in the code here:
```
const (
	// replicaSetNameSeparator is the character used to separate deployment name from hash
	replicaSetNameSeparator = "-"
)
```

File: pkg/controller/deployment/sync_test.go (hunk 3 above)
Comment (hdp617) [reply pkg/controller/deployment/sync_test.go:619]: Done.

File: pkg/controller/deployment/sync.go (hunk 1 above)
Comment (hdp617) [reply pkg/controller/deployment/sync.go]: Done.

File: pkg/controller/deployment/sync.go (hunk 2 above)
Comment (hdp617) [reply pkg/controller/deployment/sync.go]: Done.

File: pkg/controller/deployment/sync_test.go (hunk 4 above)
Comment (hdp617) [reply pkg/controller/deployment/sync_test.go]: Thanks! Added to the validation logic.

File: pkg/controller/deployment/sync.go (hunk 1 above)
Comment (hdp617) [reply pkg/controller/deployment/sync.go]: I like the latter. Updated.

File: pkg/controller/deployment/sync_test.go [hunk 5]
```diff
@@ -592,3 +594,124 @@ func TestDeploymentController_cleanupDeploymentOrder(t *testing.T) {
...
+			name:           "maximum length without truncating",
+			deploymentName: strings.Repeat("a", 242),
+			hash:           "abcde12345",
+			want:           strings.Repeat("a", 242) + "-abcde12345",
+		},
+		{
+			name:           "too long need truncating",
+			deploymentName: strings.Repeat("b", 250),
+			hash:           "abcde12345",
+			want:           strings.Repeat("b", 242) + "-abcde12345",
```
Comment (janetkuo) [inline pkg/controller/deployment/sync_test.go:708]: Would you add a case when hash is very long?

Comment (hdp617) [reply pkg/controller/deployment/sync_test.go:708]: Done.

File: pkg/controller/deployment/sync_test.go [hunk 6]
```diff
@@ -592,3 +594,130 @@ func TestDeploymentController_cleanupDeploymentOrder(t *testing.T) {
 		}
 	}
 }
+
+func TestDeploymentController_generateReplicaSetName(t *testing.T) {
+	tests := []struct {
+		name             string
+		deploymentName   string
+		wantRSNamePrefix string
```
Comment (janetkuo) [inline pkg/controller/deployment/sync_test.go]: This isn't used

File: pkg/controller/deployment/sync_test.go [hunk 7]
```diff
@@ -592,3 +594,130 @@ func TestDeploymentController_cleanupDeploymentOrder(t *testing.T) {
...
+		deploymentPortion := strings.Join(parts[:len(parts)-1], "-")
+		if len(test.deploymentName) <= 242 {
+			if deploymentPortion != test.deploymentName {
+				t.Errorf("Deployment name portion mismatch: got %q, want %q", deploymentPortion, test.deploymentName)
+			}
+		} else {
+			if len(deploymentPortion) != 242 {
+				t.Errorf("Truncated deployment name should be 242 chars, got %d", len(deploymentPortion))
+			}
+			if want := test.deploymentName[:242]; deploymentPortion != want {
```
Comment (janetkuo) [inline pkg/controller/deployment/sync_test.go]: While generating want values might seem convenient, especially for complex outputs, it introduces unnecessary risk and reduces the clarity of your tests. Explicitly defining your expected outcomes is a cornerstone of writing effective and maintainable unit tests.

Comment (hdp617) [reply pkg/controller/deployment/sync_test.go]: Thanks for the feedback. I've adjusted this test to explicitly define the expected Deployment name portion.

**Review by janetkuo — APPROVED** [review]
/lgtm
