### PR TITLE
[ubuntu] fix etcd flag 

### LINKED ISSUE #17205: [ubuntu] etcd error during upstart process
Since we have bumped etcd version to 2.2.1, there exists a problem with etcd when deploying the cluster [ubuntu]. 
I'm not positive whether it's fatal or not, and file this issue in case some one would love to pick it up. Or i'll follow this thread early next week. 

- Case 1
```
etcd start/running, process 336
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:4001: getsockopt: connection refused

Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused
error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused

Error:  100: Key not found (/coreos.com) [10]
{"Network":"172.19.0.0/16"}
{"Network":"172.19.0.0/16"}
```
- Case 2
```
etcd start/running, process 425
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [10]
{"Network":"172.16.0.0/16"}

```
For case 2, adding param `--no-sync` for `etcdctl` would fix this.

This may apply to all other platforms.

/cc @resouer  @WIZARD-CXY

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #17205

### CODE REVIEW

**Comment by dalanlan** [comment]
ping @davidopp

**Comment by davidopp** [comment]
@resouer @yichengq @xiang90

**Comment by resouer** [comment]
I did not see error in kube-in-docker, but as #17422 was in. I'm ok with this.

File: cluster/ubuntu/util.sh [hunk 1]
```diff
@@ -188,8 +188,8 @@ function create-etcd-opts() {
   cat <<EOF > ~/kube/default/etcd
 ETCD_OPTS="\
  -name infra\
- -listen-client-urls http://0.0.0.0:4001\
- -advertise-client-urls http://127.0.0.1:4001"
+ -listen-client-urls http://127.0.0.1:4001,http://${1}:4001\
```
Comment (xiang90) [inline cluster/ubuntu/util.sh]: Not sure why you want to listen on localhost and also advertise localhost.

Comment (dalanlan) [inline cluster/ubuntu/util.sh]: 'cuz i can barely understand the relationship between these two flags(from doc).Shame on me:-/
If you could give more details on this, it would be highly appreciated. 
` -listen-client-urls http://127.0.0.1:4001,http://${1}:4001 -advertise-client-urls http://${1}:4001` would work.

Comment (dalanlan) [inline cluster/ubuntu/util.sh]: Tried to file an [issue](https://github.com/coreos/etcd/issues/3886) and didn't get what i need :-/ FYI

Comment (xiang90) [inline cluster/ubuntu/util.sh]: @dalanlan What do you want to know about? Listen addr is the addr your etcd process listening on. 0.0.0.0 means on all interfaces. Advertise addr is the addr to advertise.

Comment (dalanlan) [inline cluster/ubuntu/util.sh]: > Not sure why you want to listen on localhost and also advertise localhost.

Why should we avoid this? Does it apply to all situations? 
Say i wanna to bring up a cluster, all locating in a single (and the same) machine (kinda odd, i'll give you that), isn't it suppose to advertise localhost(different port though)? 
Thanks ahead:)

Comment (xiang90) [inline cluster/ubuntu/util.sh]: If you advertise localhost, you should not expect clients outside the local machine to reach you. `localhost` on Machine A means differently from `localhost` on Machine B.

Comment (dalanlan) [inline cluster/ubuntu/util.sh]: yeah, i mean all of the clients which want to talk to the etcd locates locally as with etcd cluster in my use case

Comment (xiang90) [inline cluster/ubuntu/util.sh]: That is fine.

**Comment by dalanlan** [comment]
Based on @xiang90 's comment, i think it would be fine to set `advertise-client-urls` 
- 1. http://${master_ip}:4001
- 2. http://127.0.0.1:4001, given that there is single etcd, and `--no-sync` for `etcdctl` 
I'm comfortable with either and adopt option 1 for now.

**Comment by resouer** [comment]
lgtm  cc @davidopp

**Comment by davidopp** [comment]
LGTM
