### PR TITLE
kubeadm: use the localAPIEndpoint for all API calls in 'init'

### LINKED ISSUE #3294: [regression in v1.34.2+] kubeadm init fails at upload-config when control plane endpoint is a load balancer
### Issue

After PR https://github.com/kubernetes/kubernetes/pull/134265 (cherry-picked to v1.34.2 via https://github.com/kubernetes/kubernetes/pull/134270), `kubeadm init` can
intermittently fail during the `upload-config/kubeadm` phase when a load balancer
is used as the control plane endpoint:

```
error execution phase upload-config/kubeadm: could not bootstrap the admin user
in file admin.conf: unable to create ClusterRoleBinding: Post
"https://<lb-endpoint>:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=10s":
context deadline exceeded
```

The `addons` phase (which deploys kube-proxy and CoreDNS) is never reached,
leaving the node permanently `NotReady`.

This regression blocks Kubernetes v1.34.2+ version bumps for at least two Cluster
API infrastructure providers:
- **Cluster API Provider AWS (CAPA)** [PR #5857](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5857)
- **Cluster API Provider GCP (CAPG)** [PR #1598](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1598)

### Root cause

PR https://github.com/kubernetes/kubernetes/pull/134265 correctly changed `wait-control-plane` to use `WaitControlPlaneClient()`
(which points to `localhost`) instead of `ClientWithoutBootstrap()` (which pointed
to the control plane endpoint / load balancer). This was the right fix for
kubernetes/kubeadm#3242.

However, in v1.29 through v1.34.1, the `wait-control-plane` phase had an
**implicit side effect**: by polling the API server health through the load
balancer with a generous 4-minute `ControlPlaneComponentHealthCheck` timeout, it
acted as a gate that ensured the load balancer was routing traffic before the
subsequent phases ran.

After the change, `upload-config/kubeadm` is the **first phase** to make an API
call through the load balancer. It calls `Client()` →
`EnsureAdminClusterRoleBinding()`, which uses `PollUntilContextTimeout` with the
`KubernetesAPICall` timeout of **only 1 minute**.

For cloud load balancers, the health check cycle alone can exceed this 1-minute
window:

| Cloud Provider | LB Type | Default Health Check Cycle | Observed Convergence |
|---|---|---|---|
| AWS | Classic ELB | 5 checks × 10s = **50s** | 50–70s |
| GCP | TCP Proxy Network LB | 5 checks × 10s = **50s** | 50–90s |

Combined with the time needed to register the target/instance in the backend
service, the 1-minute window in `EnsureAdminClusterRoleBinding` is routinely too
tight, causing a race condition.

**Before v1.34.2:**

```
wait-control-plane (via LB, 4min timeout) → LB confirmed healthy
  → upload-config → EnsureAdminClusterRoleBinding (LB already works) → OK
```

**After v1.34.2:**

```
wait-control-plane (via localhost, ~3s) → LB health unknown
  → upload-config → EnsureAdminClusterRoleBinding (via LB, 1min timeout) → RACE
```

### How to reproduce

1. Use `kubeadm init` with a `controlPlaneEndpoint` pointing to a load balancer
   (AWS ELB, GCP TCP Proxy LB, HAProxy, etc.)
2. Use Kubernetes v1.34.2 or v1.34.3
3. On a fast-booting node (e.g. < 30s to kubeadm start), the load balancer may
   not have completed its health checks by the time `upload-config` runs
4. The failure is intermittent - observed rates:
   - ~35% in CAPA CI with AWS Classic ELB
   - ~75% in CAPG CI with GCP TCP Proxy Network LB

### Expected behavior

`kubeadm init` should succeed even when the load balancer takes up to several
minutes to start routing traffic, as it did in v1.34.1 and earlier.

### Workarounds

I tested a workaround using `preKubeadmCommands` to
wrap the kubeadm binary with a retry script. The workaround replaces
`/usr/bin/kubeadm` with a wrapper that, on `init` failure, waits 30s and re-runs
`kubeadm init --skip-phases=preflight,certs,kubeconfig,etcd,control-plane,kubelet-start,wait-control-plane`
to retry only the phases from `upload-config` onwards without disrupting the
already-running API server.

Note: a naive `kubeadm reset -f` + full re-init workaround does **not** work in
Cluster API environments because the reset kills the API server while the
KubeadmControlPlane controller has an active connection, causing it to enter a
broken state it cannot recover from.

### Possible solutions

1. **Increase `EnsureAdminClusterRoleBinding` timeout** to match
   `ControlPlaneComponentHealthCheck` (4 min) instead of `KubernetesAPICall`
   (1 min), since this is called during init and not a regular API call.

2. **Add an explicit LB readiness check** before `upload-config`, e.g. a new
   hidden phase that polls the control plane endpoint until it responds, with the
   same 4-minute timeout that `wait-control-plane` previously provided implicitly.

### Kubernetes version

```
v1.34.2, v1.34.3 (regression from v1.34.1)
```

### Environment

- **Cloud provider:** AWS (Classic ELB), GCP (TCP Proxy Network LB)
- **OS:** Ubuntu 22.04/24.04
- **Deployment:** Cluster API Provider AWS (CAPA), Cluster API Provider GCP (CAPG)
- **CAPI version:** v1.12.2

/kind bug
/area kubeadm
/sig cluster-lifecycle
/priority important-soon

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug cleanup

#### What this PR does / why we need it:

```
Historicaly the kubeadm clients have used the 'admin.conf'
and 'super-admin.conf' directly, which makes all API calls
go trough the CPE (control plane endpoint). This can create
problems for scenarios when the LB is provisioned only after
'init' starts the kube-apiserver.

Instead of using the '.conf' as they are, modify them
in memory to point to the LAE (localAPIEndpoint).
This was already done by the WaitControlPlaneClient for
the WaitControlPlane phase, which required it. This separate
client is no longer needed.

However, do pass a unmodified kubeconfig to the init phase
bootstrap-token, since this is the phase that creates
the cluster-info CM, and for that we need the original CPE
server address.
```

#### Which issue(s) this PR is related to:

fixes https://github.com/kubernetes/kubeadm/issues/3294

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: during 'kubeadm init', if the default 'admin.conf' and 'super-admin.conf' paths are used, load the files, but construct in memory kubeconfigs that point to the InitConfiguration.localAPIEndpoint instead of the ClusterConfiguration.controlPlaneEndpoint. This would resolve issues with delayed load balancers which are provisioned only after the first kube-apiserver instance starts.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
running external e2e here:
https://github.com/neolit123/kubeadm-test/actions

EDIT: tests are passing.

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -615,22 +615,34 @@ type EnsureRBACFunc func(context.Context, clientset.Interface, clientset.Interfa
...
 // usable client from admin.conf with RBAC properly constructed or an error.
-func EnsureAdminClusterRoleBinding(outDir string, ensureRBACFunc EnsureRBACFunc) (clientset.Interface, error) {
+func EnsureAdminClusterRoleBinding(outDir string, adminKubeconfigPath string, lae *kubeadmapi.APIEndpoint, ensureRBACFunc EnsureRBACFunc) (clientset.Interface, error) {
 	var (
 		err                           error
 		adminClient, superAdminClient clientset.Interface
 	)
 
 	// Create a client from admin.conf.
-	adminClient, err = kubeconfigutil.ClientSetFromFile(filepath.Join(outDir, kubeadmconstants.AdminKubeConfigFileName))
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:625]: i think this was a bug as it was ignoring the configured `--kubeconfig` and always using a file named 'admin.conf' in the given directory.

some `init` phases do have the `--kubeconfig` flag:

```
 grep "options\.KubeconfigPath" ./cmd/kubeadm/app/cmd/phases/init/* -rnI | grep -v _test.go
./cmd/kubeadm/app/cmd/phases/init/addons.go:127:                options.KubeconfigPath,
./cmd/kubeadm/app/cmd/phases/init/bootstraptoken.go:56:                 options.KubeconfigPath,
./cmd/kubeadm/app/cmd/phases/init/uploadcerts.go:38:                    options.KubeconfigPath,
./cmd/kubeadm/app/cmd/phases/init/uploadconfig.go:97:           options.KubeconfigPath,
```

and this function `EnsureAdminClusterRoleBinding()`
does get called every time a client is constructed from `init.go#Client()`.

Comment (neolit123) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:625]: hmm, NVM the function only called if the kubeocnfig is the default `/etc/kubernetes/admin.conf`

```
if !d.adminKubeConfigBootstrapped && isDefaultKubeConfigPath {
				// Call EnsureAdminClusterRoleBinding() to obtain a working client from admin.conf.
				d.client, err = kubeconfigphase.EnsureAdminClusterRoleBinding(...
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -615,22 +615,28 @@ type EnsureRBACFunc func(context.Context, clientset.Interface, clientset.Interfa
...
+	adminClient, err = kubeconfigutil.ToClientSet(kubeconfig)
 	if err != nil {
 		return nil, err
 	}
 
 	// Create a client from super-admin.conf.
-	superAdminPath := filepath.Join(outDir, kubeadmconstants.SuperAdminKubeConfigFileName)
-	if _, err := os.Stat(superAdminPath); err == nil {
-		superAdminClient, err = kubeconfigutil.ClientSetFromFile(superAdminPath)
+	kubeconfig, err = clientcmd.LoadFromFile(filepath.Join(outDir, kubeadmconstants.SuperAdminKubeConfigFileName))
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:636]: Why can't we, like in 'Create a client from admin.conf', not ignore the error returned by `clientcmd.LoadFromFile`?

Comment (neolit123) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go]: i agree, it is better to have the Stat here and continue returning relevant Load errors.

**Comment by damdo** [comment]
Hey @neolit123 thanks a ton for this!

I tested this PR by cherry-picking it onto `v1.34.3` locally and running the CAPA e2e suite.
The test passes the kubeadm init upload-config phase, so that's great!

However, I found an issue in kubeadm join scenarios after control plane node replacement (e.g. rolling upgrades). New nodes fail to join with:

```
[preflight] Reading configuration from the "kubeadm-config" ConfigMap in namespace "kube-system"...
error: unable to fetch the kubeadm-config ConfigMap: failed to get config map:
  Get "https://10.0.92.29:6443/.../kubeadm-config?timeout=10s":
  dial tcp 10.0.92.29:6443: connect: no route to host
```

Where 10.0.92.29 was the original control plane node's private IP (now replaced).

I wonder if it is because the bootstrap-token init phase calls `data.KubeConfig()`, which now returns the admin kubeconfig already rewritten to the localAPIEndpoint. This rewritten kubeconfig is then passed to `CreateBootstrapConfigMapIfNotExists()`:
```
// cmd/kubeadm/app/cmd/phases/init/bootstraptoken.go
kubeconfig, err := data.KubeConfig()  // server: https://<localIP>:6443
// ...
clusterinfophase.CreateBootstrapConfigMapIfNotExists(client, kubeconfig)
```
Which copies the cluster server URL directly into `kube-public/cluster-info`:

```
// cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go
bootstrapConfig := &clientcmdapi.Config{
    Clusters: map[string]*clientcmdapi.Cluster{
        "": adminConfig.Clusters[adminCluster],  // server: https://<localIP>:6443
    },
}
```

So cluster-info advertises `https://<localIP>:6443` instead of `https://<LB-DNS>:6443`.
After a control plane rolling replacement, the old IP no longer exists, and all new kubeadm join operations fail.

 kubeadm-config is unaffected upload-config correctly uses cfg.ClusterConfiguration.controlPlaneEndpoint.

Does the bootstrap-token phase need the original controlPlaneEndpoint for cluster-info, not the rewritten localAPIEndpoint?

- Could we pass the original (un-rewritten) admin kubeconfig to `CreateBootstrapConfigMapIfNotExists`
Build the cluster-info cluster entry from `ClusterConfiguration.controlPlaneEndpoint` instead of from the kubeconfig
or
- Add a method like `OriginalKubeConfig()` that returns the un-rewritten kubeconfig for data-plane writes vs client-connection uses

CI evidence: [CAPA Prow run 2046137158200201216](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api-provider-aws/5898/pull-cluster-api-provider-aws-e2e/2046137158200201216) , where 4 upgrade tests fail with no route to host to the old CP's private IP during kubeadm join.

**Comment by neolit123** [comment]
> I wonder if it is because the bootstrap-token init phase calls data.KubeConfig(), which now returns the admin kubeconfig already rewritten to the localAPIEndpoint. This rewritten kubeconfig is then passed to CreateBootstrapConfigMapIfNotExists()

yep, that's a bug. i will address it tomorrow.

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go]: updated.

**Comment by neolit123** [comment]
> > I wonder if it is because the bootstrap-token init phase calls data.KubeConfig(), which now returns the admin kubeconfig already rewritten to the localAPIEndpoint. This rewritten kubeconfig is then passed to CreateBootstrapConfigMapIfNotExists()
> 
> yep, that's a bug. i will address it tomorrow.

updated.

**Comment by damdo** [comment]
Hi @neolit123, thanks for the update!

I've been testing the latest changes from this PR by cherry-picking it onto v1.34.3 (both in CAPA and CAPG).

With the previous commit (948fd8e) we got all 22 tests running in our E2Es successfully completing the kubeadm init phase.
However, after switching to b68b696 we see failures with the error:

```
error execution phase wait-control-plane: cannot obtain client without bootstrap:
  could not bootstrap the admin user in file admin.conf:
  unable to create the kubeadm:cluster-admins ClusterRoleBinding by using super-admin.conf:
  Post "https://<nlb-dns>:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=10s":
  context deadline exceeded
```

I think it is due to the change in EnsureAdminClusterRoleBinding.
In 948fd8e, both admin.conf and super-admin.conf were rewritten to point to the local API endpoint.
In b68b696, only admin.conf is rewritten and super-admin.conf is loaded as-is and still points to the control plane endpoint (the NLB).

During kubeadm init, EnsureAdminClusterRoleBindingImpl tries to create the kubeadm:cluster-admins ClusterRoleBinding using the superAdminClient.
Since that client still targets the NLB, the request times out.

Could EnsureAdminClusterRoleBinding also use the local API endpoint?

Thanks!

**Comment by neolit123** [comment]
> I think it is due to the change in EnsureAdminClusterRoleBinding.
In https://github.com/kubernetes/kubernetes/commit/948fd8e4cac7cdee144506020ac4f9945895ee50, both admin.conf and super-admin.conf were rewritten to point to the local API endpoint.
In https://github.com/kubernetes/kubernetes/commit/b68b696da5e060608bef35d6cfc1c32d1b6899db, only admin.conf is rewritten and super-admin.conf is loaded as-is and still points to the control plane endpoint (the NLB).

yes, that's true. me doing 3 different  things and parallel and not having too much time for this PR. also us not having e2e tests with a broken LB doesn't help.

all clients should be using LAE, even the super admin one, so i will roll-back that change.

**Comment by neolit123** [comment]
@damdo please try testing again.

**Comment by neolit123** [comment]
/cc @SataQiu @HirazawaUi 
PTAL. this should be ideally backported too, to unblock various CAPI infra providers that suffer from unpredictable / poorly designed LB provisioning.

**Comment by damdo** [comment]
Hey @neolit123 

Thanks a lot!

I've tested it and it works as expected.
- For CAPG it completely resolves the issue
- For CAPA, as we lowkey expected, it works, but now the `kubeadm join` sometime fails as that's the next element that uses the external API endpoint for the joining. But this was kind of expected. I think it puts CAPA in a better spot at least. We'll need to further investigate on our side.

So I'm happy for this to merge and be backported! Thanks a lot for all your help here! :)

**Comment by neolit123** [comment]
> Hey @neolit123
> 
> Thanks a lot!
> 
> I've tested it and it works as expected.
> 
> * For CAPG it completely resolves the issue
> * For CAPA, as we lowkey expected, it works, but now the `kubeadm join` sometime fails as that's the next element that uses the external API endpoint for the joining. But this was kind of expected. I think it puts CAPA in a better spot at least. We'll need to further investigate on our side.
> 
> So I'm happy for this to merge and be backported! Thanks a lot for all your help here! :)

thanks for testing, @damdo .

/cc @SataQiu @pacoxu @carlory @HirazawaUi 

any objections to this change and the backport?

**Review by pacoxu — COMMENTED** [review]
/lgtm

File: cmd/kubeadm/app/cmd/init.go
Comment (carlory) [inline cmd/kubeadm/app/cmd/init.go:464]: The func comment need to be updated.

Comment (neolit123) [reply cmd/kubeadm/app/cmd/init.go:464]: moved the comment that was inside the function:
```
// If the default kubeconfig path is used (admin.conf), instead of constructing
// a kubeconfig that points to the control plane endpoint, make it point to the localAPIEndpoint.
// This would allow 'kubeadm init' to only talk to the local kube-apiserver instance.
```

to be as part of the comment on top of the function, like so:

```
// KubeConfig returns a kubeconfig after loading it from KubeConfigPath().
// If the default kubeconfig path is used (admin.conf), instead of constructing
// a kubeconfig that points to the control plane endpoint, make it point to the localAPIEndpoint.
// This would allow 'kubeadm init' to only talk to the local kube-apiserver instance.
````

**Comment by neolit123** [comment]
if there is agreement for this, someone please add the approve label. thanks

**Comment by damdo** [comment]
Thanks all!
Could we backport this back to 1.34.z so it matches the same backport we had [for the other LAE change](https://github.com/kubernetes/kubernetes/pull/134270)?
Thanks!

**Comment by neolit123** [comment]
> Thanks all! Could we backport this back to 1.34.z so it matches the same backport we had [for the other LAE change](https://github.com/kubernetes/kubernetes/pull/134270)? Thanks!

i will send backports to all versions in support.
that's how it's done usually.

**Comment by neolit123** [comment]
cherry picks:
- https://github.com/kubernetes/kubernetes/pull/138682
- https://github.com/kubernetes/kubernetes/pull/138683
- https://github.com/kubernetes/kubernetes/pull/138685
- https://github.com/kubernetes/kubernetes/pull/138686

there were some conflicts, so please double check the diff.
