### PR TITLE
Suppress registering GCE LB provider flag if missing on CommandLine.

### LINKED ISSUE #76205: Cloud-controller-manager won't build for out-of-tree external providers
**What happened**:

panic: failed to find flag in global flagset (flag): cloud-provider-gce-lb-src-cidrs

goroutine 1 [running]:
k8s.io/component-base/cli/globalflag.Register(0xc0000ba900, 0x17df195, 0x1f)
	/home/neil/Go/pkg/mod/k8s.io/component-base@v0.0.0-20190405092941-79a63e28c077/cli/globalflag/globalflags.go:66 +0x1a9
k8s.io/kubernetes/cmd/cloud-controller-manager/app.NewCloudControllerManagerCommand(0xc00008e150)
	/home/neil/Go/pkg/mod/k8s.io/kubernetes@v1.14.0/cmd/cloud-controller-manager/app/controllermanager.go:91 +0x438
main.main()
	/home/neil/Dev/brightbox-cloud-controller-manager/main.go:39 +0x90

**What you expected to happen**:

The controller should run and stop with a '--cloud-provider cannot be empty' message

**How to reproduce it (as minimally and precisely as possible)**:

Follow the out of tree instructions here https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/

Comment out the _ "k8s.io/kubernetes/pkg/cloudprovider/providers" import line and build the cloud-controller-manager

**Anything else we need to know?**:

This worked fine prior to 1.14.0 

**Environment**:
- Kubernetes version (use `kubectl version`):
lient Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g: `cat /etc/os-release`):
Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`):
Linux bionic-vm 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linu
- Install tools:
kubeadm
- Others:

### PR DESCRIPTION
**Pull request by timoreimann**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes an issue with the GCE-specific `cloud-provider-gce-lb-src-cidrs` flag being added by default that breaks external cloud providers.

**Which issue(s) this PR fixes**:
Fixes #76205

**Does this PR introduce a user-facing change?**:
```release-note
GCE-only flag `cloud-provider-gce-lb-src-cidrs` becomes optional for external cloud providers.
```

/sig cloud-provider

Verified on DigitalOcean's CCM [currently being updated to 1.14.1](https://github.com/digitalocean/digitalocean-cloud-controller-manager/pull/209).

/cc @dims @andrewsykim

### CODE REVIEW

File: cmd/cloud-controller-manager/app/controllermanager.go [hunk 1]
```diff
@@ -86,9 +87,12 @@ the cloud specific control loops shipped with Kubernetes.`,
 	namedFlagSets := s.Flags(KnownControllers(), ControllersDisabledByDefault.List())
 	verflag.AddFlags(namedFlagSets.FlagSet("global"))
 	globalflag.AddGlobalFlags(namedFlagSets.FlagSet("global"), cmd.Name())
-	// hoist this flag from the global flagset to preserve the commandline until
-	// the gce cloudprovider is removed.
-	globalflag.Register(namedFlagSets.FlagSet("generic"), "cloud-provider-gce-lb-src-cidrs")
+
+	if flag.CommandLine.Lookup("cloud-provider-gce-lb-src-cidrs") != nil {
```
Comment (andrewsykim) [inline cmd/cloud-controller-manager/app/controllermanager.go]: cc @cheftako @mikedanese this was breaking implementations that didn't import the GCE provider
