### PR TITLE
fix upgrade test for 1.2->1.4

### LINKED ISSUE #32700: GKE: Kubectl client Kubectl run job should create a job from an image when restart is Never [Conformance]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

### PR DESCRIPTION
**Pull request by jessfraz**
**What this PR does / why we need it**: fixes #32700 upgrade test since jobs started with --restart=Never after v1.3.0 are considered pods.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
None
```

fix #32700

Signed-off-by: Jess Frazelle me@jessfraz.com

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32895)

### CODE REVIEW

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -1107,6 +1107,14 @@ var _ = Describe("Kubectl client", func() {
 
 		It("should create a job from an image when restart is Never [Conformance]", func() {
 			SkipUnlessServerVersionGTE(jobsVersion, c)
+			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
+			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
+			if err != nil {
+				Failf("Failed version check: %v", err)
+			}
+			if isPod {
+				Skipf("Skipping test for version >= v1.3.0 since jobs started with --restart=Never are pods")
```
Comment (janetkuo) [inline test/e2e/kubectl.go]: We're skipping test for version <1.3, right?

File: test/e2e/kubectl.go [hunk 2]
```diff
@@ -1107,6 +1107,14 @@ var _ = Describe("Kubectl client", func() {
 
 		It("should create a job from an image when restart is Never [Conformance]", func() {
 			SkipUnlessServerVersionGTE(jobsVersion, c)
+			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
+			isPod, err := serverVersionGTE(version.MustParse("v1.3.0"), c)
```
Comment (janetkuo) [inline test/e2e/kubectl.go]: Suggest creating `jobGeneratorVersion = version.MustParse("v1.3.0-alpha.5")` (or better name) and change `SkipUnlessServerVersionGTE(jobsVersion, c)` to `SkipUnlessServerVersionGTE(jobGeneratorVersion, c)`. And add comments there as other var xxxVersion does

**Review by janetkuo — CHANGES_REQUESTED** [review]

File: test/e2e/kubectl.go (hunk 1 above)
Comment (jfrazelle) [inline test/e2e/kubectl.go]: the server is 1.4 and the tests being run are the 1.2 tests. So we are skipping if the server version is above 1.3

File: test/e2e/kubectl.go (hunk 2 above)
Comment (jfrazelle) [inline test/e2e/kubectl.go]: that wont work because we need to skip when the server version is greater than 1.3

Comment (janetkuo) [inline test/e2e/kubectl.go]: Ah, I see. So the comment `if the version is <= 1.3.0 the job with --restart=Never is a pod` should be `>1.3.0`? Can we add `SkipUnlessServerVersionLTE` and use that instead?

**Comment by jfrazelle** [comment]
sure yeah, just didn't know how much I could change old tests haha

**Comment by janetkuo** [comment]
Or at least update the comment and use `v1.3.0-alpha.5` instead

File: test/e2e/kubectl.go (hunk 2 above)
Comment (jfrazelle) [inline test/e2e/kubectl.go]: added :) will be helpful in the other fix too

File: test/e2e/kubectl.go [hunk 3]
```diff
@@ -1107,6 +1107,8 @@ var _ = Describe("Kubectl client", func() {
 
 		It("should create a job from an image when restart is Never [Conformance]", func() {
 			SkipUnlessServerVersionGTE(jobsVersion, c)
+			// if the version is <= 1.3.0 the job with --restart=Never is a pod, see: https://github.com/kubernetes/kubernetes/commit/d76fa8a1197a6329da3125c8bfb2202dfead1273
```
Comment (janetkuo) [inline test/e2e/kubectl.go]: `>=`

**Review by janetkuo — APPROVED** [review]

File: test/e2e/kubectl.go (hunk 3 above)
Comment (jfrazelle) [inline test/e2e/kubectl.go]: good catch

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE
