### PR TITLE
Terminated pod should not be re-admitted

### LINKED ISSUE #126341: Terminated but not GC'd Pods should not be re-admitted on kubelet restart
### What happened?

Pods that already succeeded and waiting for finalizer are being readmitted, fail to be admitted and moving from Succeeded Phase to Failed (admission failed) phase.

### What did you expect to happen?

The correct behavior would be to not try to re-admit the succeeded (or failed) Pod.

### How can we reproduce it (as minimally and precisely as possible)?

Specific case:

- Node is exposing Devices using device plugin. Device plugin is implemented as a Pod
- Job's pod that is using the Device run to completion and waiting for Job Status finalizer
- kubelet is being restarted
- DevicePlugin pod is reconnecting to the kubelet. While it is reconnecting, kubelet don't have availability of devices
- kubelet re-admits the Pod, even though it is terminated already
- kubelet marks the pod as "failed to be admitted"

But the same can happen with the variations of GC speed and other admission handlers.

### Anything else we need to know?

/sig node
/priority important-soon
/cc @bobbypage @smarterclayton 

There is also a wider issue: https://github.com/kubernetes/kubernetes/issues/123980, that concentrates on running pods. This issue is about terminated Pods, which is less controversial.

### Kubernetes version

<details>

For sure on master, may be on earlier versions.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind bug
/sig node
/priority important-soon

#### What this PR does / why we need it:

Terminated pods should not be re-admitted on kubelet restart.

#### Which issue(s) this PR fixes:

Fixes #126341

#### Special notes for your reviewer:

This PR copies some things that can be re-used, mostly to enable the cherry-pick if we will decide to do it.

#### Does this PR introduce a user-facing change?

```release-note
Terminated Pods on a node will not be re-admitted on kubelet restart. This fixes the problem of Completed Pods awaiting for the finalizer marked as Failed after the kubelet restart.
```

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2567,7 +2571,8 @@ func (kl *Kubelet) HandlePodAdditions(pods []*v1.Pod) {
 		// shutting it down. If the pod hasn't started yet, we know that when
 		// the pod worker is invoked it will also avoid setting up the pod, so
 		// we simply avoid doing any work.
-		if !kl.podWorkers.IsPodTerminationRequested(pod.UID) {
+		// We also do not try to admit the pod that is already in terminated state.
+		if (!kl.podWorkers.IsPodTerminationRequested(pod.UID) && !isPodStateTerminated(pod)) {
```
Comment (bobbypage) [inline pkg/kubelet/kubelet.go:2575]: nit: can use `IsPodPhaseTerminal` - https://github.com/kubernetes/kubernetes/blob/6ac20677c781e72346ccc56daafb161d6750cbbd/pkg/api/v1/pod/util.go#L317-L319

File: test/e2e_node/device_plugin_test.go [hunk 2]
```diff
@@ -428,6 +465,56 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+
+			ginkgo.By("Waiting for pod to succeed")
+			gomega.Expect(e2epod.WaitForPodSuccessInNamespace(ctx, f.ClientSet, pod.Name, pod.Namespace)).To(gomega.Succeed())
+
+
+			ginkgo.By("Deleing the device plugin")
+			gp := int64(0)
+			deleteOptions := metav1.DeleteOptions{
+				GracePeriodSeconds: &gp,
+			}
```
Comment (bobbypage) [inline test/e2e_node/device_plugin_test.go:495]: We probably don't need to do a force delete here right? Can use non zero grace period.

Comment (SergeyKanzhelev) [reply test/e2e_node/device_plugin_test.go:495]: mostly following the pattern in this file. Are you suggesting to make code easier to reason about or because of some concerns?

Comment (bobbypage) [reply test/e2e_node/device_plugin_test.go:495]: Force deletion is handled differently in kubelet. My comment was that unless we are trying to specifically test force deletion, it probably makes sense to use a non zero grace period.

File: test/e2e_node/device_plugin_test.go [hunk 3]
```diff
@@ -428,6 +465,56 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+			framework.ExpectNoError(err)
+
+			ginkgo.By("Wait for node to be ready")
+			e2enode.WaitForAllNodesSchedulable(ctx, f.ClientSet, 5*time.Minute)
+
+			ginkgo.By("Waiting for pod to succeed")
+			gomega.Expect(e2epod.WaitForPodSuccessInNamespace(ctx, f.ClientSet, pod.Name, pod.Namespace)).To(gomega.Succeed())
+
+
+			ginkgo.By("Deleing the device plugin")
```
Comment (bobbypage) [inline test/e2e_node/device_plugin_test.go:491]: nit: deleting

File: test/e2e_node/device_plugin_test.go [hunk 4]
```diff
@@ -428,6 +465,56 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 			framework.ExpectNoError(err, "inconsistent device assignment after pod restart")
 		})
 
+		ginkgo.It("will not attempt to admit the succeeded pod after the kubelet restart and device plugin removed", func(ctx context.Context) {
+			podRECMD := fmt.Sprintf("devs=$(ls /tmp/ | egrep '^Dev-[0-9]+$') && echo stub devices: $devs && sleep %s", sleepIntervalWithRestart)
+			podSpec := makeBusyboxPod(SampleDeviceResourceName, podRECMD)
+			podSpec.Spec.RestartPolicy = v1.RestartPolicyNever
+			podSpec.ObjectMeta.Finalizers = []string{testFinalizer}
```
Comment (bobbypage) [inline test/e2e_node/device_plugin_test.go:472]: Just curious -- why do we need a finalizer here? What will delete the pod if finalizer is not set?

**Comment by ffromani** [comment]
/triage approved

THANKS! this is something I had on the radar since long long time but never managed to deep dive into it.
IMHO it never made sense for the kubelet to retry admission of terminated pods and I was surprised when I found it still do.

File: test/e2e_node/device_plugin_test.go (hunk 4 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:472]: +1 to the question, thanks!

File: test/e2e_node/device_plugin_test.go (hunk 2 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:495]: I can't remember why we use force deletion in the existing tests. I can't rule out it was a bad habit which was carried around without much scrutiny over time.

File: test/e2e_node/device_plugin_test.go [hunk 5]
```diff
@@ -428,6 +465,56 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+
+			ginkgo.By("Wait for node to be ready again")
+			e2enode.WaitForAllNodesSchedulable(ctx, f.ClientSet, 5*time.Minute)
+
+			ginkgo.By("Pod should still be in Succeed state")
+
+			gomega.Consistently(func() v1.PodPhase {
+				pod, err = f.ClientSet.CoreV1().Pods(f.Namespace.Name).Get(ctx, pod.Name, metav1.GetOptions{})
+				return pod.Status.Phase
+			}, 1*time.Minute, f.Timeouts.Poll).Should(gomega.Equal(v1.PodSucceeded))
```
Comment (ffromani) [inline test/e2e_node/device_plugin_test.go:512]: I'm not completely sure how this exercise the changes. Perhaps it is because without the fix, the pod will move from succeeded to failed because of the very bug being fixed? if so, worth a comment to make the intention explicit and save some head-scratching to our future selves.

File: test/e2e_node/device_plugin_test.go (hunk 4 above)
Comment (SergeyKanzhelev) [reply test/e2e_node/device_plugin_test.go:477]: I have added a comment. Not sure why it is cleaning up fast in my set up. With finalizers it is guarantee to hang around

File: test/e2e_node/device_plugin_test.go (hunk 5 above)
Comment (SergeyKanzhelev) [reply test/e2e_node/device_plugin_test.go:514]: Added a comment before the call. I cannot think of any other ways to confirm that it was re-admitted by the kubelet. Unfortunately it makes the test longer to run =(. If you have a suggestion - please let me know.

File: test/e2e_node/device_plugin_test.go (hunk 2 above)
Comment (SergeyKanzhelev) [reply test/e2e_node/device_plugin_test.go]: removed it and it worked.

File: test/e2e_node/device_plugin_test.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply test/e2e_node/device_plugin_test.go]: fixed

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go]: thanks, yes, this is better

**Comment by SergeyKanzhelev** [comment]
@smarterclayton suggested to look whether this will break static pods. But I cannot think of a way to have a terminated static pod on kubelet restart. So not adding any new tests here for now. Please let me know if you have some scenarios in mind so I can validate those.

**Comment by smarterclayton** [comment]
> But I cannot think of a way to have a terminated static pod on kubelet restart

I think this will reproduce the scenario I'm concerned about (if we can prove via code review this doesn't happen, that's great):

1. Create a static pod, wait for mirror pod to exist
2. Stop kubelet
3. Set phase on mirror pod to terminal via API server status update
4. Start kubelet

Expect: static pod to go through admission (it's not actually terminal from the perspective of a static pod, since static pods cannot be marked terminal)

Looking at the code, I don't see how the static pod using a file source could have a status that is terminal (only the mirror pod would).  However, we probably need to review the code path to ensure phase can't get copied over to static pods in between config handler and HandlePodAdditions.

I can't think of any other scenarios which would impact static pods in this code path though.

**Comment by dsxing** [comment]
https://github.com/kubernetes/kubernetes/issues/117955
