### PR TITLE
Fix #74900 - kubectl logs --selector supports --tail=-1

### LINKED ISSUE #74900: "kubectl logs --selector" ignores "--tail=-1"
**What happened**:

When attempting to get all log lines using `kubectl logs -l app=my.app --tail=-1` only 10 lines of logs are returned

**What you expected to happen**:

All log lines should be returned

**How to reproduce it (as minimally and precisely as possible)**:

`kubectl logs -l app=my.app --tail=-1`

**Anything else we need to know?**:

This was introduced in ea7065d47187356f442ed2722c59833b8c4bf067 in an attempt to fix another issue where selectors would ignore tail values !=-1. I think the problem here is the logic cannot tell if the `-1` was set explicitly by the command line or is simply the initial default value.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3
- Cloud provider or hardware configuration: Kubeadm
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by JishanXing**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix #74900 - kubectl logs --selector supports --tail=-1

**Which issue(s) this PR fixes**:
#74900

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubectl logs --selector will support --tail=-1.
```

### CODE REVIEW

File: pkg/kubectl/cmd/logs/logs.go [hunk 1]
```diff
@@ -192,6 +192,7 @@ func (o *LogsOptions) ToLogOptions() (*corev1.PodLogOptions, error) {
 	}
 
 	if len(o.Selector) > 0 && o.Tail == -1 {
+	} else if len(o.Selector) > 0 && o.Tail < -1 {
```
Comment (soltysh) [inline pkg/kubectl/cmd/logs/logs.go]: This is not a good solution, you should be checking whether a flag was changed, through its `.Changed` attribute in `Complete` method and set a bool flag to tell the difference.

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/kubectl/cmd/logs/logs.go (hunk 1 above)
Comment (JishanXing) [reply pkg/kubectl/cmd/logs/logs.go]: Hi soltysh,

Thanks for your reviewing. Please help review again. Thanks.

if len(o.Selector) > 0 && o.Tail == -1 && o.TailSpecified {
		logOptions.TailLines = nil  <====if user specify -1, it means show all lines
	} else if len(o.Selector) > 0 && o.Tail < -1 {
		logOptions.TailLines = &o.Tail  <===== tail must greater than -1
	} else if o.Tail != -1 {
		logOptions.TailLines = &o.Tail
	}

Regards,
Jishan

Comment (soltysh) [reply pkg/kubectl/cmd/logs/logs.go]: I think you have the condition backwards.

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/kubectl/cmd/logs/logs.go (hunk 1 above)
Comment (JishanXing) [reply pkg/kubectl/cmd/logs/logs.go]: Hi soltysh,

Thanks for your review. 
I changed the code according to your suggestion. It will pass the -1 to the server side, so we need change the API's validation too.
   if o.TailSpecified {
        logOptions.TailLines = &o.Tail
    }
Please help review again. Thanks.

File: pkg/apis/core/v1/validation/validation.go [hunk 2]
```diff
@@ -124,8 +124,8 @@ func validateResourceName(value string, fldPath *field.Path) field.ErrorList {
 
 func ValidatePodLogOptions(opts *v1.PodLogOptions) field.ErrorList {
 	allErrs := field.ErrorList{}
-	if opts.TailLines != nil && *opts.TailLines < 0 {
```
Comment (soltysh) [inline pkg/apis/core/v1/validation/validation.go]: You can't change the validation on the API side, leave it as it was before.

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -5192,8 +5192,8 @@ func ValidateSecurityContext(sc *core.SecurityContext, fldPath *field.Path) fiel
 
 func ValidatePodLogOptions(opts *core.PodLogOptions) field.ErrorList {
 	allErrs := field.ErrorList{}
-	if opts.TailLines != nil && *opts.TailLines < 0 {
```
Comment (soltysh) [inline pkg/apis/core/validation/validation.go]: Ditto.

File: pkg/kubectl/cmd/logs/logs.go [hunk 4]
```diff
@@ -191,9 +193,7 @@ func (o *LogsOptions) ToLogOptions() (*corev1.PodLogOptions, error) {
 		logOptions.SinceSeconds = &sec
 	}
 
-	if len(o.Selector) > 0 && o.Tail == -1 {
-		logOptions.TailLines = &selectorTail
-	} else if o.Tail != -1 {
+	if o.TailSpecified {
```
Comment (soltysh) [inline pkg/kubectl/cmd/logs/logs.go]: The first condition should be left untouched. You can eventually change it to `!o.TailSpecified`

File: pkg/kubectl/cmd/logs/logs.go [hunk 5]
```diff
@@ -290,8 +291,8 @@ func (o LogsOptions) Validate() error {
 		return fmt.Errorf("--since must be greater than 0")
 	}
 
-	if logsOptions.TailLines != nil && *logsOptions.TailLines < 0 {
-		return fmt.Errorf("TailLines must be greater than or equal to 0")
+	if logsOptions.TailLines != nil && *logsOptions.TailLines < -1 {
+		return fmt.Errorf("TailLines must be greater than or equal to -1")
```
Comment (soltysh) [inline pkg/kubectl/cmd/logs/logs.go]: the flag name is `--tail` and that's what should be in the error.

**Review by soltysh — CHANGES_REQUESTED** [review]

**Comment by JishanXing** [comment]
Hi @soltysh,

Thank you for your review. I have addressed your comments, please help review again.

Regards,
Jishan

**Review by soltysh — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Review by soltysh — APPROVED** [review]
/lgtm
@JishanXing please update release notes since this is a user facing change
