### PR TITLE
Allocating CIDRs for Pods works without a cloud provider.

### LINKED ISSUE #11866: Allocating CIDRs for Pods should work without a cloud provider
Currently setting the `--allocate-node-cidrs` flag to true with an empty cloud provider cause the kube-controller-manager to crash during startup.

### PR DESCRIPTION
**Pull request by kelseyhightower**
Currently setting the `--allocate-node-cidrs` flag to true with an
empty cloud provider causes the kube-controller-manager to crash during
startup.

Fix the issue by checking for an empty cloud provider before setting
up route management on the cloud provider. This change introduces a
change in behavior. The kube-controller-manager now supports allocating
pod CIDRs without a cloud provider. This means users must manage routes
through some other mechanism.

The controller manager logs a warning if `--allocate-node-cidrs` is set,
but not a cloud provider:

```
I0725 17:10:41.587888   43185 plugins.go:70] No cloud provider specified.
I0725 17:10:41.588036   43185 nodecontroller.go:114] Sending events to api server.
E0725 17:10:41.588122   43185 controllermanager.go:201] Failed to start service controller: ServiceController should not be run without a cloudprovider.
W0725 17:10:41.588136   43185 controllermanager.go:213] allocate-node-cidrs is set, but no cloud provider specified. Will not manage routes.
E0725 17:10:41.589703   43185 nodecontroller.go:187] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1
```

Fixes #11866

### CODE REVIEW

File: cmd/kube-controller-manager/app/controllermanager.go [hunk 1]
```diff
@@ -202,12 +202,16 @@ func (s *CMServer) Run(_ []string) error {
 	}
 
 	if s.AllocateNodeCIDRs {
-		routes, ok := cloud.Routes()
-		if !ok {
-			glog.Fatal("Cloud provider must support routes if allocate-node-cidrs is set")
+		if cloud != nil {
```
Comment (cjcullen) [inline cmd/kube-controller-manager/app/controllermanager.go]: I think it'd also make sense to just warn and then run in allocate-only mode for clouds that don't support the Routes interface.
To clean up the if block a little bit, how about:
```
if s.AllocateNodeCIDRs {
	if cloud == nil {
		glog.Warningf("allocate-node-cidrs is set, but no cloud provider specified. Will not manage routes.")
	} else if routes, ok := cloud.Routes(); !ok {
		glog.Warningf("allocate-node-cidrs is set, but cloud provider does not support routes. Will not manage routes.")
	} else {
		routeController := routecontroller.New(routes, kubeClient, s.ClusterName, (*net.IPNet)(&s.ClusterCIDR))
		routeController.Run(s.NodeSyncPeriod)
	}
}
```

It might violate Go's "only indent the exceptional case" rule, but I think it's reasonable here where there isn't necessarily an "exceptional" case, and it looks way cleaner to me.

**Comment by cjcullen** [comment]
LGTM after my 1 nit. I think there are solid use cases both for 1) allocating CIDRs without a cloudprovider, and 2) allocating CIDRs where your cloudprovider doesn't explicitly support it (BYO network reconciler).

File: cmd/kube-controller-manager/app/controllermanager.go (hunk 1 above)
Comment (kelseyhightower) [inline cmd/kube-controller-manager/app/controllermanager.go]: @cjcullen Are you sure routes will be in scope for the following else block?

Comment (cjcullen) [inline cmd/kube-controller-manager/app/controllermanager.go]: Should be in scope from the point of initialization through the rest of the if-else block.
My simple test here appears to work: http://play.golang.org/p/CwUM1SPgCK

**Comment by kelseyhightower** [comment]
@cjcullen PTAL

File: cmd/kube-controller-manager/app/controllermanager.go [hunk 2]
```diff
@@ -202,12 +202,14 @@ func (s *CMServer) Run(_ []string) error {
 	}
 
 	if s.AllocateNodeCIDRs {
-		routes, ok := cloud.Routes()
-		if !ok {
+		if cloud == nil {
+			glog.Warningf("allocate-node-cidrs is set, but no cloud provider specified. Will not manage routes.")
+		} else if routes, ok := cloud.Routes(); !ok {
 			glog.Fatal("Cloud provider must support routes if allocate-node-cidrs is set")
```
Comment (cjcullen) [inline cmd/kube-controller-manager/app/controllermanager.go]: I think it should be okay to set --allocate-node-cidrs without having your cloudprovider support it.
Instead of the glog.Fatal here, what do you think about: 
```glog.Warning("allocate-node-cidrs is set, but cloud provider does not support routes. Will not manage routes.")```

Also, super-nit: The `glog.Warningf` above could just be `glog.Warning`.

**Comment by kelseyhightower** [comment]
@cjcullen I like the idea of only warning if the cloud provider does not support routes. Changes made PTAL.

**Comment by cjcullen** [comment]
Thanks for entertaining my nits. LGTM.
