### PR TITLE
scheduler: fix inFlightPods leak when pod is recreated during scheduling failure

### LINKED ISSUE #138316: Race in scheduler can cause infinite growth of inFlightEvents
### What happened?

During the scheduling cycle if pod gets recreated with the same name during filtering there is a potential race condition causing the pod to stay in inFlightPods/inFlightEvents forever. 

Exact steps:

## Step 1: The Initial Lock-in
- Pop: The scheduler pops Pod-X (UID: AAAA) from the top of the scheduling queue.
- Record: The queue pushes Pod-X to the tail of the mixed doubly-linked `inFlightEvents` list to track when it started.
- Map: The queue stores the exact memory pointer to that list node inside `inFlightPods[AAAA]`.

## Step 2: The Synchronous Failure
- Execute: The scheduler begins running synchronous Filter plugins (e.g. checking NodeSelector, Taints, or custom filters).
- Fail: One of the filter plugins returns Unschedulable.
- Abort: Because scheduling cannot proceed, the scheduler aborts the cycle immediately and jumps straight to the failure handler. It skips `sched.SchedulingQueue.Done(assumedPod.UID)` done before bindingCycle.

## Step 3: The Recreation Overwrite (The Race Condition)
- Delete & Recreate: Just milliseconds before the failure handler runs, an external controller deletes Pod-X and immediately recreates a brand new instance with the exact same name/namespace, generating a new UID (BBBB).
- Fetch: The failure handler queries the local Informer cache for the latest state of the pod using its string name (Pod-X).
- Retrieve: The cache naturally returns the newly created instance with UID BBBB.
- Overwrite: The internal reference in the scheduler is updated to hold the new pod reference (BBBB).

## Step 4: Missing the Target
- Queue Push: The failure handler attempts to put the pod back into the queue using `AddUnschedulableIfNotPresent(BBBB)`.
- Deferred Done: The very first line of `AddUnschedulableIfNotPresent` function unconditionally executes:
``` go
       // In any case, this Pod will be moved back to the queue and we should call Done.
	defer p.Done(pInfo.Pod.UID)
```
- The Miss: `Done(BBBB)` looks inside the `inFlightPods` tracking map, sees that UID BBBB does not exist, and does absolutely nothing.
- The Ghost: The original UID (AAAA) is entirely forgotten by the system and remains permanently trapped inside the `inFlightPods` map and the doubly-linked list!

# Step 5: The Catastrophic Dam
- Drift: Over the next few seconds, as other unrelated pods complete their cycles normally, they get removed from the front of the list. The trapped ghost pod (AAAA) eventually shifts all the way to the Front() position of the list.
- The Blockade: Because `Done(AAAA)` is never called, this node can never be removed from Front().
- Paralysis: Every time the cleanup routine attempts to run, it looks at the very first element of the list, sees the ghost pod (AAAA), and completely halts all pruning to protect it.
- The Explosion: Meanwhile, standard background updates (Node usage, endpoint slices, system leases) continuously append thousands of new *clusterEvent nodes to the tail of the linked list. Because the front node is anchored forever, none of those incoming events can ever be deleted—causing your InFlightEvents metric to grow infinitely 

### What did you expect to happen?

The Done method of scheduling queue should be called on the old UID. 

### How can we reproduce it (as minimally and precisely as possible)?

Integration test `TestInFlightPodLeak` added in https://github.com/kubernetes/kubernetes/compare/master...Argh4k:kubernetes:potential-memory-leak reproduces that locally. 

### Anything else we need to know?

_No response_

### Kubernetes version

Observed on a cluster running v1.34.1, but still reproducible with the HEAD.

### Cloud provider

Observed on a cluster running on GKE but reproducible on a HEAD.

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by MaybeSam05**
/kind bug

#### What this PR does / why we need it:

When scheduling fails before the binding cycle, `handleSchedulingFailure` reloads the pod from the shared informer by namespace/name and rebuilds `podInfo`. If the workload was **deleted and recreated with the same name** in that window, the informer returns a **new UID** while the scheduling queue still tracks the **original popped UID** in `inFlightPods` / `inFlightEvents`.

`AddUnschedulableIfNotPresent` always deferred `Done` on `pInfo.Pod.UID` after the refresh. If that UID no longer matched the in-flight map entry, `Done` became a no-op and the old UID could **never be removed**, eventually blocking pruning of `inFlightEvents` and allowing related metrics to grow without bound ([issue #138316](https://github.com/kubernetes/kubernetes/issues/138316)).

This PR:

- Adds `schedulingCycleInFlightUID` to `SchedulingQueue.AddUnschedulableIfNotPresent`. The **empty string** preserves existing behavior (use `pInfo.Pod.UID`).
- Captures the popped scheduling UID in `handleSchedulingFailure` **before** replacing `podInfo` from the informer and passes it into `AddUnschedulableIfNotPresent`.
- Uses that UID for `Done` and threads it through `determineSchedulingHintForInFlightPod` → `clusterEventsForPod` so in-flight list lookups stay consistent when `pInfo.Pod.UID` has changed.
- Adds `TestPriorityQueue_AddUnschedulableIfNotPresent_PodRecreatedSameName` (with `SchedulerQueueingHints` enabled).

**Tests run:** `go test -short ./pkg/scheduler/backend/queue/ ./pkg/scheduler/`

#### Which issue(s) this PR is related to:

Fixes #138316

#### Special notes for your reviewer:

- Main behavior change is in `pkg/scheduler/schedule_one.go` (`handleSchedulingFailure`) plus `pkg/scheduler/backend/queue/scheduling_queue.go` and `active_queue.go`.
- All other call sites pass `""` for the new parameter so behavior is unchanged unless the pod object was refreshed to a different UID for the same scheduling attempt.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a scheduler bug where replacing a Pod with the same name during a failed scheduling attempt could leave stale in-flight queue state and unbounded growth of in-flight event tracking. The scheduler now clears in-flight state using the UID from the scheduling attempt, not only the UID on the refreshed Pod object.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/scheduler/queueing/queue_test.go [hunk 1]
```diff
@@ -341,8 +341,11 @@ func TestCustomResourceEnqueue(t *testing.T) {
 	testCtx.Scheduler.FailureHandler(ctx, schedFramework, podInfo, fwk.NewStatus(fwk.Unschedulable).WithError(fitError), nil, time.Now())
 
 	// Scheduling cycle is incremented from 0 to 1 after NextPod() is called, so
-	// pass a number larger than 1 to move Pod to unschedulablePods.
-	testCtx.Scheduler.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, 10)
+	// pass a number larger than 1 to move Pod to unschedulablePods. FailureHandler above may have
+	// already requeued the Pod, in which case the duplicate AddUnschedulableIfNotPresent call is benign.
+	if err := testCtx.Scheduler.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, 10, ""); err != nil && err.Error() != fmt.Sprintf("Pod %v is already present in the active queue", klog.KObj(podInfo.Pod)) {
```
Comment (macsko) [inline test/integration/scheduler/queueing/queue_test.go]: Call to the `AddUnschedulableIfNotPresent` here doesn't make sense at all since it's a noop. Could you just remove it from here?

File: pkg/scheduler/schedule_one.go [hunk 2]
```diff
@@ -1256,12 +1256,16 @@ func (sched *Scheduler) handleSchedulingFailure(ctx context.Context, podFwk fram
 			logger.Info("Pod has been assigned to node. Abort adding it back to queue.", "pod", klog.KObj(pod), "node", cachedPod.Spec.NodeName)
 			// We need to call DonePod here because we don't call AddUnschedulableIfNotPresent in this case.
 		} else {
+			// Remember the UID under which this pod is tracked as in-flight (from Pop) before we
+			// replace podInfo with the informer copy. A delete+recreate with the same name can change
+			// the UID; Done and queueing hints must still target the popped UID (kubernetes/kubernetes#138316).
```
Comment (macsko) [inline pkg/scheduler/schedule_one.go]:
```suggestion
			// the UID; Done and queueing hints must still target the popped UID (#138316).
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 3]
```diff
@@ -994,6 +994,37 @@ func TestPriorityQueue_AddUnschedulableIfNotPresent(t *testing.T) {
...
+	q := NewTestQueueWithObjects(ctx, newDefaultQueueSort(), []runtime.Object{pod})
+	q.Add(ctx, pod)
+	popped, err := q.Pop(logger)
+	if err != nil {
+		t.Fatalf("Pop: %v", err)
+	}
+	if popped.Pod.UID != oldUID {
+		t.Fatalf("unexpected popped UID: got %v want %v", popped.Pod.UID, oldUID)
+	}
+
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Add here `expectInFlightPods` call to show that they are expected at this point

File: pkg/scheduler/backend/queue/active_queue.go [hunk 4]
```diff
@@ -396,16 +398,21 @@ func (aq *activeQueue) listInFlightPods() []*v1.Pod {
 	return pods
 }
 
-// clusterEventsForPod gets all cluster events that have happened during pod for pInfo is being scheduled.
-func (aq *activeQueue) clusterEventsForPod(logger klog.Logger, pInfo *framework.QueuedPodInfo) ([]*clusterEvent, error) {
+// clusterEventsForPod gets all cluster events that have happened while the scheduling attempt
+// for the pod keyed by inFlightListUID (in inFlightPods) was in flight.
+func (aq *activeQueue) clusterEventsForPod(logger klog.Logger, pInfo *framework.QueuedPodInfo, inFlightListUID types.UID) ([]*clusterEvent, error) {
```
Comment (macsko) [inline pkg/scheduler/backend/queue/active_queue.go]: Maybe just name inFlightUID?

File: pkg/scheduler/backend/queue/active_queue.go [hunk 5]
```diff
@@ -396,16 +398,21 @@ func (aq *activeQueue) listInFlightPods() []*v1.Pod {
...
 	aq.lock.RLock()
 	defer aq.lock.RUnlock()
 	logger.V(5).Info("Checking events for in-flight pod", "pod", klog.KObj(pInfo.Pod), "unschedulablePlugins", pInfo.UnschedulablePlugins, "inFlightEventsSize", aq.inFlightEvents.Len(), "inFlightPodsSize", len(aq.inFlightPods))
 
+	listUID := inFlightListUID
+	if listUID == "" {
+		listUID = pInfo.Pod.UID
+	}
```
Comment (macsko) [inline pkg/scheduler/backend/queue/active_queue.go]: You can just do:

```suggestion
	if inFlightListUID == "" {
		inFlightListUID = pInfo.Pod.UID
	}
```

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 6]
```diff
@@ -902,12 +907,18 @@ func (p *PriorityQueue) addUnschedulableWithoutQueueingHint(logger klog.Logger,
 // the queue, unless it is already in the queue. Normally, PriorityQueue puts
 // unschedulable pods in `unschedulablePods`. But if there has been a recent move
 // request, then the pod is put in `backoffQ`.
-func (p *PriorityQueue) AddUnschedulableIfNotPresent(logger klog.Logger, pInfo *framework.QueuedPodInfo, podSchedulingCycle int64) error {
+func (p *PriorityQueue) AddUnschedulableIfNotPresent(logger klog.Logger, pInfo *framework.QueuedPodInfo, podSchedulingCycle int64, schedulingCycleInFlightUID types.UID) error {
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: Just name inFlightUID?

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 7]
```diff
@@ -108,7 +108,11 @@ type SchedulingQueue interface {
 	// AddUnschedulableIfNotPresent adds an unschedulable pod back to scheduling queue.
 	// The podSchedulingCycle represents the current scheduling cycle number which can be
 	// returned by calling SchedulingCycle().
-	AddUnschedulableIfNotPresent(logger klog.Logger, pod *framework.QueuedPodInfo, podSchedulingCycle int64) error
+	// schedulingCycleInFlightUID is the UID under which the pod is registered in inFlightPods (from Pop).
+	// Use the empty string to mean pInfo.Pod.UID. When the pod object is refreshed from the API/informer
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: Couldn't it just always take non-empty UID?

File: pkg/scheduler/schedule_one.go [hunk 8]
```diff
@@ -1256,12 +1256,16 @@ func (sched *Scheduler) handleSchedulingFailure(ctx context.Context, podFwk fram
...
+			poppedInFlightUID := podInfo.Pod.UID
 			// As <cachedPod> is from SharedInformer, we need to do a DeepCopy() here.
 			// ignore this err since apiserver doesn't properly validate affinity terms
 			// and we can't fix the validation for backwards compatibility.
 			podInfo.PodInfo, _ = framework.NewPodInfo(cachedPod.DeepCopy())
 			pod = podInfo.Pod
-			if err := sched.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, sched.SchedulingQueue.SchedulingCycle()); err != nil {
+			if err := sched.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, sched.SchedulingQueue.SchedulingCycle(), poppedInFlightUID); err != nil {
```
Comment (Argh4k) [inline pkg/scheduler/schedule_one.go]: What if, instead of calling `AddUnschedulableIfNotPresent` with `poppedInFlightUID` we would check whether `poppedInFlightUID == podInfo.Pod.UID` and if they are different we just call `sched.SchedulingQueue.Done(podInfo.Pod.UID)` here?  The new pod should be added to the queue via the event handler on the informer, so we do not have to add it via this `AddUnschedulableIfNotPresent` call. Probably we should also skip `sched.SchedulingQueue.AddNominatedPod(logger, podInfo.PodInfo, nominatingInfo)` in this case. 

Even from the correctness perspective calling AddUnschedulableIfNotPresent with the pod with different UID probably can cause some issues, like putting a new pod in unschedulable/backoff queue even when they have different spec than the previous pod with same name.

File: test/integration/scheduler/queueing/queue_test.go (hunk 1 above)
Comment (MaybeSam05) [reply test/integration/scheduler/queueing/queue_test.go]: Removed this noop call in the latest push. You're right, FailureHandler already handles requeueing here, so the extra AddUnschedulableIfNotPresent was redundant.

File: pkg/scheduler/schedule_one.go (hunk 2 above)
Comment (MaybeSam05) [reply pkg/scheduler/schedule_one.go]: Updated in the latest push. I also ended up changing the recreated-pod handling a bit more: if the informer copy has a different UID, we now skip requeueing/status updates entirely and just Done() the original in-flight UID, so I rewrote the comment to match that behavior.

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 3 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: I ended up removing this test in the latest push. Since the recreated-pod handling now happens in handleSchedulingFailure, I moved the coverage there instead of keeping a queue-level test.

File: pkg/scheduler/backend/queue/active_queue.go (hunk 4 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/active_queue.go]: I changed the approach in the latest push and removed the extra UID parameter from the queue path entirely, so this rename is no longer applicable. The recreated-pod case is now handled in schedule_one.go instead.

File: pkg/scheduler/backend/queue/active_queue.go (hunk 5 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/active_queue.go]: I changed the implementation in the latest push and removed this fallback path entirely, so this simplification is no longer applicable.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 6 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: I removed this extra parameter in the latest push, so this rename is no longer needed.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 7 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: I removed this parameter in the latest push, so this is no longer applicable.

File: pkg/scheduler/schedule_one.go (hunk 8 above)
Comment (MaybeSam05) [reply pkg/scheduler/schedule_one.go]: Thanks, I updated this in the latest push along those lines. When the informer copy has a different UID, we now Done() the original in-flight UID and skip requeueing/nominating/status updates for the recreated pod; it should come back through the informer path instead.

File: test/integration/scheduler/queueing/queue_test.go [hunk 9]
```diff
@@ -340,10 +339,6 @@ func TestCustomResourceEnqueue(t *testing.T) {
 	}
 	testCtx.Scheduler.FailureHandler(ctx, schedFramework, podInfo, fwk.NewStatus(fwk.Unschedulable).WithError(fitError), nil, time.Now())
 
-	// Scheduling cycle is incremented from 0 to 1 after NextPod() is called, so
-	// pass a number larger than 1 to move Pod to unschedulablePods.
-	testCtx.Scheduler.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, 10)
```
Comment (Argh4k) [inline test/integration/scheduler/queueing/queue_test.go:345]: Why do we have to remove that?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 10]
```diff
@@ -4030,7 +4030,9 @@ func TestPerPodSchedulingMetrics(t *testing.T) {
 				}
 
 				pInfo.UnschedulablePlugins = sets.New("plugin")
-				queue.AddUnschedulableIfNotPresent(logger, pInfo, 1)
```
Comment (Argh4k) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go:4033]: Do we need to change this in this PR? I would prefer to keep the scope of this PR as small as possible.

File: test/integration/scheduler/queueing/queue_test.go (hunk 9 above)
Comment (macsko) [reply test/integration/scheduler/queueing/queue_test.go:345]: Calling `AddUnschedulableIfNotPresent` here is a noop. Pod is already re-added to the queue in the `FailureHandler `call above. This removal is not related to the fix itself. Since the `AddUnschedulableIfNotPresent` is finally not modified, this change can be reverted and delivered in a separate PR.

File: pkg/scheduler/backend/queue/active_queue.go
Comment (macsko) [inline pkg/scheduler/backend/queue/active_queue.go:1]: I think you can undo the changes in this file

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 11]
```diff
@@ -906,7 +906,7 @@ func (p *PriorityQueue) AddUnschedulableIfNotPresent(logger klog.Logger, pInfo *
 	p.lock.Lock()
 	defer p.lock.Unlock()
 
-	// In any case, this Pod will be moved back to the queue and we should call Done.
+	// In any case, this scheduling attempt will be moved back to the queue and we should call Done.
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue.go]: I think you can undo this

File: pkg/scheduler/schedule_one.go [hunk 12]
```diff
@@ -1256,11 +1256,21 @@ func (sched *Scheduler) handleSchedulingFailure(ctx context.Context, podFwk fram
...
 			pod = podInfo.Pod
+			if pod.UID != poppedInFlightUID {
+				logger.V(2).Info("Pod was recreated while handling scheduling failure. Skip requeueing and status updates.", "pod", klog.KObj(pod), "oldUID", poppedInFlightUID, "newUID", pod.UID)
+				sched.SchedulingQueue.Done(poppedInFlightUID)
+				calledDone = true
+				return
+			}
 			if err := sched.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, sched.SchedulingQueue.SchedulingCycle()); err != nil {
 				utilruntime.HandleErrorWithContext(ctx, err, "Error occurred")
 			}
```
Comment (macsko) [inline pkg/scheduler/schedule_one.go:1270]: You can just do:
```go
			// ...
			if cachedPod.UID != podInfo.Pod.UID {
				logger.V(2).Info("Pod was recreated while handling scheduling failure. Skip requeueing and status updates.", "pod", klog.KObj(pod), "oldUID", podInfo.Pod.UID, "newUID", cachedPod.UID)
				return
			}
			// As <cachedPod> is from SharedInformer, we need to do a DeepCopy() here.
			// ignore this err since apiserver doesn't properly validate affinity terms
			// and we can't fix the validation for backwards compatibility.
			podInfo.PodInfo, _ = framework.NewPodInfo(cachedPod.DeepCopy())
			pod = podInfo.Pod
			if err := sched.SchedulingQueue.AddUnschedulableIfNotPresent(logger, podInfo, sched.SchedulingQueue.SchedulingCycle()); err != nil {
				utilruntime.HandleErrorWithContext(ctx, err, "Error occurred")
			}
```
When you just return, the deferred Done will be called with the `podInfo.Pod.UID`. So if you don't overwrite it, it will use the old UID.

File: pkg/scheduler/schedule_one_test.go [hunk 13]
```diff
@@ -1318,6 +1318,76 @@ func TestSchedulerScheduleOne(t *testing.T) {
...
+	informerFactory.WaitForCacheSync(ctx.Done())
+
+	queue.Add(ctx, oldPod)
+	popped, err := queue.Pop(logger)
+	if err != nil {
+		t.Fatalf("Pop: %v", err)
+	}
+
+	nominatingInfo := &fwk.NominatingInfo{NominatingMode: fwk.ModeOverride, NominatedNodeName: "node1"}
+	sched.handleSchedulingFailure(ctx, schedFramework, popped, fwk.NewStatus(fwk.Unschedulable, "no fit"), nominatingInfo, time.Now())
```
Comment (macsko) [inline pkg/scheduler/schedule_one_test.go:1368]: Can you verify that before calling the `handleSchedulingFailure`, the `InFlightPods` is non-empty?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 10 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go:4033]: I reverted this change in the latest push to keep the PR scoped to the recreated-pod fix only.

File: pkg/scheduler/backend/queue/active_queue.go
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/active_queue.go:1]: Reverted in the latest push.

File: pkg/scheduler/backend/queue/scheduling_queue.go (hunk 11 above)
Comment (MaybeSam05) [reply pkg/scheduler/backend/queue/scheduling_queue.go]: Reverted in the latest push.

File: pkg/scheduler/schedule_one.go (hunk 12 above)
Comment (MaybeSam05) [reply pkg/scheduler/schedule_one.go:1270]: Updated in the latest push. I now check `cachedPod.UID != podInfo.Pod.UID` before overwriting `podInfo`, so the deferred `Done` still uses the old in-flight UID when the pod was recreated.

File: pkg/scheduler/schedule_one_test.go (hunk 13 above)
Comment (MaybeSam05) [reply pkg/scheduler/schedule_one_test.go:1368]: Added in the latest push. The test now verifies that `InFlightPods` contains the popped pod before calling `handleSchedulingFailure`.

File: test/integration/scheduler/queueing/queue_test.go (hunk 9 above)
Comment (MaybeSam05) [reply test/integration/scheduler/queueing/queue_test.go:345]: You're right. I restored it in the latest push to keep this PR focused. As @macsko pointed out, this is a noop here because the pod is already re-added in FailureHandler, so any cleanup can be done separately.

**Comment by rytswd** [comment]
This seems to be well contained.

/milestone v1.36
