### PR TITLE
e2e: MakePod() should support block and inline volumes

### LINKED ISSUE #99152: e2e: block volumes incorrectly added to pod's volumeMounts field
#### Which test(s) are failing:

```
External Storage [Testpattern: Dynamic PV (block volmode)] provisioning should provision storage with pvc data source in parallel
```

#### Reason for failure:

Apparently volumes with `volumeMode=Block` are incorrectly added to `pod.Spec.Containers[].VolumeMounts`:

```
FailedMount: Unable to attach or mount volumes: unmounted volumes=[volume1], unattached volumes=[default-token-2xpwr volume1]: volume volume1 has volumeMode Block, but is specified in volumeMounts
```

/sig storage
/assign

### PR DESCRIPTION
**Pull request by bertinatto**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Currently, `MakePod()` is incorrectly adding volumes  with `volumeMode=Block` to the pod's `.spec.Containers[].VolumeMounts. Also, it's not currently handling inline volumes.

This PR fixes that by unifying the code used by `MakePod()` and `MakeSecPod()`.

#### Which issue(s) this PR fixes:

Fixes #99152

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bertinatto** [comment]
/assign @pohly 
Patrick, would you take a look, please?

File: test/e2e/framework/pod/create.go [hunk 1]
```diff
@@ -223,33 +215,47 @@ func MakePodSpec(podConfig *Config) *v1.PodSpec {
 		podSpec.SecurityContext.FSGroupChangePolicy = podConfig.PodFSGroupChangePolicy
 	}
 
+	setVolumes(podSpec, podConfig.PVCs, podConfig.InlineVolumeSources, podConfig.PVCsReadOnly)
+
+	if runtime.GOOS != "windows" {
+		podSpec.SecurityContext.SELinuxOptions = podConfig.SeLinuxLabel
+	}
```
Comment (pohly) [inline test/e2e/framework/pod/create.go:222]: This assignment to `podSpec.SecurityContext.SELinuxOptions` seems unrelated to this PR. Should it be included?

Comment (bertinatto) [reply test/e2e/framework/pod/create.go]: Right, this has been removed in d9c4d8bff833e288a9b366b3b4b69920e35aaaca.

File: test/e2e/framework/pod/create.go [hunk 2]
```diff
@@ -154,15 +154,7 @@ func MakePod(ns string, nodeSelector map[string]string, pvclaims []*v1.Persisten
...
 	}
-	var volumeMounts = make([]v1.VolumeMount, len(pvclaims))
-	var volumes = make([]v1.Volume, len(pvclaims))
-	for index, pvclaim := range pvclaims {
-		volumename := fmt.Sprintf("volume%v", index+1)
-		volumeMounts[index] = v1.VolumeMount{Name: volumename, MountPath: "/mnt/" + volumename}
-		volumes[index] = v1.Volume{Name: volumename, VolumeSource: v1.VolumeSource{PersistentVolumeClaim: &v1.PersistentVolumeClaimVolumeSource{ClaimName: pvclaim.Name, ReadOnly: false}}}
-	}
-	podSpec.Spec.Containers[0].VolumeMounts = volumeMounts
-	podSpec.Spec.Volumes = volumes
```
Comment (bertinatto) [inline test/e2e/framework/pod/create.go:165]: Noticed that `podSpec.Spec.Containers[0].VolumeDevices` wasn't set.

File: test/e2e/framework/pod/create.go [hunk 3]
```diff
@@ -223,33 +215,42 @@ func MakePodSpec(podConfig *Config) *v1.PodSpec {
 		podSpec.SecurityContext.FSGroupChangePolicy = podConfig.PodFSGroupChangePolicy
 	}
 
+	setVolumes(podSpec, podConfig.PVCs, podConfig.InlineVolumeSources, podConfig.PVCsReadOnly)
+	SetNodeSelection(podSpec, podConfig.NodeSelection)
+	return podSpec
+}
+
+func setVolumes(podSpec *v1.PodSpec, pvcs []*v1.PersistentVolumeClaim, inlineVolumeSources []*v1.VolumeSource, pvcsReadOnly bool) {
```
Comment (bertinatto) [inline test/e2e/framework/pod/create.go:223]: `MakePodSec` was setting block and inline volumes correctly, so instead of copying the code to `MakePod`, I moved it to a separate function (`setVolumes`) that can be called from `MakePod` and `MakePodSec`.

**Review by pohly — APPROVED** [review]
/lgtm
