### PR TITLE
 Manually read verbosity before kubectl command construction

### LINKED ISSUE #1731: It's not possible to get logs during command construction
**What happened**:
While preparing for KubeCon EU SIG CLI presentation I've wanted to show how users can see the logs when using [kubectl preferences](https://github.com/kubernetes/enhancements/issues/3104). 
So I've run:
```
KUBECTL_KUBERC=true kubectl -v=5 get po -A
```
with an empty `$HOME/.kube/kuberc` file, hoping to see this message
https://github.com/kubernetes/kubernetes/blob/bdda0a530ed26fd5b9f389ae4333a748de861f32/staging/src/k8s.io/kubectl/pkg/kuberc/marshal.go#L99
but sadly I didn't get any. I started looking around and due to how we create commands [we only initialize logging when running command](https://github.com/kubernetes/kubernetes/blob/bdda0a530ed26fd5b9f389ae4333a748de861f32/cmd/kubectl/kubectl.go#L30). 

**What you expected to happen**:
I'd like to see the output for all log messages even during command construction. 

**How to reproduce it (as minimally and precisely as possible)**:
```
KUBECTL_KUBERC=true kubectl -v=5 get po -A
```

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind bug
/sig cli

#### What this PR does / why we need it:
kubectl command construction is slowly getting more functionality which sometimes requires to log certain actions. Currently we parse the verbosity only when actually running the command, so all of construction code is not able to use `-v=5`. This commit adds the manual parsing and loglevel setting before we even start creating the kubectl command.

The 2nd commit with tests is coming from https://github.com/kubernetes/kubernetes/pull/131290 courtesy of @ardaguclu 

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubectl/issues/1731

#### Special notes for your reviewer:
/assign @ardaguclu 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
<!--
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/3104-introduce-kuberc
```

### CODE REVIEW

File: cmd/kubectl/kubectl.go [hunk 1]
```diff
@@ -26,6 +29,13 @@ import (
 )
 
 func main() {
+	// We need to manually parse the arguments looking for verbosity flag and
+	// set appropriate level here, because in the normal flow the flag parsing,
+	// including the logging verbosity, happens inside cli.RunNoErrOutput.
+	// Doing it here ensures we can continue using klog during kubectl command
+	// construction, which includes handling plugins and parsing .kuberc file,
+	// for example.
+	logs.GlogSetter(cmd.GetLogVerbosity(os.Args))
```
Comment (ardaguclu) [inline cmd/kubectl/kubectl.go:38]: I think, this piece is much nicer comparing to my PoC looking workaround solution. More importantly, we don't need to call `ParseFlags` which I was worried about that can cause real headaches for us.

Besides this should be idempotent, because os.Args will be parsed to exact same log level in command execution anyway. Only real issue would be `GetLogVerbosity` has a bug, so that t`GetLogVerbosity` may set the incorrect log verbosity level. But it would be very unlikely.

Comment (soltysh) [reply cmd/kubectl/kubectl.go:38]: > Besides this should be idempotent, because os.Args will be parsed to exact same log level in command execution anyway. Only real issue would be `GetLogVerbosity` has a bug, so that t`GetLogVerbosity` may set the incorrect log verbosity level. But it would be very unlikely.

Even if so, that will only apply to the command construction, and the rest of the commands will get the correct logic, b/c proper flag parsing will happen when running commands - tested it :sweat_smile: . So the surface is relatively small and if that happens we should be able to quickly fix it.

Comment (ardaguclu) [reply cmd/kubectl/kubectl.go:38]: yes, I agree. Thank you.

**Comment by soltysh** [comment]
With lint error now fixed this should be good to go.
