### PR TITLE
Kubectl: support inline csi volume

### LINKED ISSUE #75512: Kubectl describe does not support inline csi volume
**What happened**:

kubectl describe pod  xxx  not show csi inline volume, it shows <unknow>

image

**What you expected to happen**:
show csi inline volume normally like this 

image

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a pod with inline csi volume
2. kubectl describe pod  xxx  not show csi inline volume
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14 beta2 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Kubectl can not describe inline csi volume correctly.
image

**Which issue(s) this PR fixes**:

Fixes #75512 

**Special notes for your reviewer**:
cc @liggitt 
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/sig cli

### CODE REVIEW

**Comment by juanvallejo** [comment]
@cwdsuzhou Thanks! Could you add some sample output of what it looks like with this patch?

/lgtm

cc @soltysh or @seans3 for approval

**Comment by cwdsuzhou** [comment]
@juanvallejo thanks for your review. I would add some sample output later.

**Comment by cwdsuzhou** [comment]
ping @soltysh @seans3,  would you please help review this pr.

File: pkg/kubectl/describe/versioned/describe.go [hunk 1]
```diff
@@ -1208,6 +1210,23 @@ func printFlockerVolumeSource(flocker *corev1.FlockerVolumeSource, w PrefixWrite
 		flocker.DatasetName, flocker.DatasetUUID)
 }
 
+func printCSIVolumeSource(csi *corev1.CSIVolumeSource, w PrefixWriter) {
+	var readOnly bool
+	var fsType string
+	if csi.ReadOnly != nil && *csi.ReadOnly {
```
Comment (soltysh) [inline pkg/kubectl/describe/versioned/describe.go]: Next time do:
```
readOnly := csi.ReadOnly != nil && *csi.ReadOnly
```
less typing :wink:

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

File: pkg/kubectl/describe/versioned/describe.go (hunk 1 above)
Comment (cwdsuzhou) [reply pkg/kubectl/describe/versioned/describe.go]: Thanks
