### PR TITLE
Check getNodeInfoError against nil

### LINKED ISSUE #87806: Kubelet Panic if nodeId is empty and no error provided
**What happened**:
Kubelet dies with a panic exception if CSI plugin returns NodeId == "" and nil error. 

Exception log see at the end of the message

**What you expected to happen**:
Kubelet should just raise an error to the plugin and ignore the registration.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a CSI plugin with only Node that would implement GetNodeInfo as follows:
```go
func (d *GCSDriver) NodeGetInfo(ctx context.Context, req *csi.NodeGetInfoRequest) (*csi.NodeGetInfoResponse, error) {
	return &csi.NodeGetInfoResponse{NodeId: ""}, nil
}
```
* Register it as a DaemonSet and see kublet crush

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.10-gke.17
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Container-Optimized OS (cos)
- Kernel (e.g. `uname -a`): -
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Related exception
```
Feb 04 10:44:17 xxx kubelet[42861]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 04 10:44:17 xxx kubelet[42861]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2510ff7]
Feb 04 10:44:17 xxx kubelet[42861]: goroutine 1640 [running]:
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*csiDriverClient).NodeGetInfo.func1(0x44282a0, 0x3c15101, 0xc0016f6280)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_client.go:200 +0x77
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x3b9aca00, 0x4000000000000000, 0x0, 0x5, 0x0, 0xc0016f6280, 0x2a
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265 +0x51
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*csiDriverClient).NodeGetInfo(0xc0009d3620, 0x4fb5cc0, 0xc0013ac240, 0x4fb5cc0, 0xc0013ac240, 0xc001482ff0, 0
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_client.go:189 +0x1e3
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*RegistrationHandler).RegisterPlugin(0x81aa4c0, 0xc0015ea1d0, 0xe, 0xc000c30300, 0x30, 0xc001482f50, 0x1, 0x1
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:154 +0x2e9
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).handlePluginRegistration(0xc0004a57a0, 0xc001153a40, 0x39, 0x0, 0x0)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:306 +0x798
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).handleCreateEvent(0xc0004a57a0, 0xc001153a40, 0x39, 0xc000000001, 0xc0016226fa, 0xc
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:256 +0x50b
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start.func1.1(0xc0004a57a0, 0xc001153a40, 0x39, 0x1)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:118 +0x1da
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start.func1(0xc0004a57a0, 0xc0010b0960)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:129 +0x26e
Feb 04 10:44:17 xxx kubelet[42861]: created by k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:106 +0x24b
Feb 04 10:44:17 xxx dockerd[1103]: time="2020-02-04T10:44:17.432143154Z" level=error msg="Handler for GET /v1.38/images/json returned error: write unix /var/run/docker.sock->@: wr
Feb 04 10:44:17 xxx dockerd[1103]: http: multiple response.WriteHeader calls
```
Related line of code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L161 - no check whether error is not nil before calling Error() on it.

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As #87806 reported, csiDriverClient#NodeGetInfo would crash calling getNodeInfoError.Error() because getNodeInfoError may be nil.

The cloud provider may not give facility for determining the cause of error when kubelet segfault's

This PR adds check for getNodeInfoError against nil.

**Which issue(s) this PR fixes**:
Fixes #87806

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
wait.ExponentialBackoff() is used by csiDriverClient#NodeGetInfo where it continues to wait for non-empty nodeID.
I added a test for the empty nodeId case.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority important-soon

File: pkg/volume/csi/csi_client.go [hunk 1]
```diff
@@ -162,7 +162,7 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
 			return true, nil
 		}
 		// kubelet plugin registration service not implemented is a terminal error, no need to retry
-		if strings.Contains(getNodeInfoError.Error(), "no handler registered for plugin type") {
+		if getNodeInfoError != nil && strings.Contains(getNodeInfoError.Error(), "no handler registered for plugin type") {
```
Comment (msau42) [inline pkg/volume/csi/csi_client.go]: I'm not sure actually where "no handler registered for plugin type" comes from. I don't think it's an error from the csi client. We may be able to remove this case. cc @saad-ali 

Can we also log getNodeInfoError for the non-fatal case?

Comment (tedyu) [reply pkg/volume/csi/csi_client.go]: There are 3 places in pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go where this error is generated.

Comment (tedyu) [reply pkg/volume/csi/csi_client.go]: @msau42 
I have added the log for non-fatal error.

**Comment by tedyu** [comment]
@msau42 
Tests passed.
Please take another look.

File: pkg/volume/csi/csi_client.go [hunk 2]
```diff
@@ -162,8 +162,11 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
 			return true, nil
 		}
 		// kubelet plugin registration service not implemented is a terminal error, no need to retry
-		if strings.Contains(getNodeInfoError.Error(), "no handler registered for plugin type") {
-			return false, getNodeInfoError
+		if getNodeInfoError != nil {
+			if strings.Contains(getNodeInfoError.Error(), "no handler registered for plugin type") {
```
Comment (msau42) [inline pkg/volume/csi/csi_client.go]: Thanks for pointing out that this error gets generated from pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go.

However, this getNodeInfoError is from nodeGetInfoV1() which I shouldn't go through that path. So I think this check is unnecessary.

File: pkg/volume/csi/csi_client.go [hunk 3]
```diff
@@ -162,8 +162,11 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
...
+				return false, getNodeInfoError
+			}
+			klog.V(4).Info(getNodeInfoError.Error())
```
Comment (msau42) [inline pkg/volume/csi/csi_client.go]: Can you add some more context to the log message, like "Error calling CSI NodeGetInfo(): %v".  Also I think this could be a warning.

File: pkg/volume/csi/csi_client.go [hunk 4]
```diff
@@ -162,8 +162,11 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
...
 		}
 		// Continue with exponential backoff
```
Comment (saad-ali) [inline pkg/volume/csi/csi_client.go]: nit: Worth logging something here?

**Comment by tedyu** [comment]
@msau42 
I have addressed your comments.

File: pkg/volume/csi/csi_client.go (hunk 2 above)
Comment (saad-ali) [reply pkg/volume/csi/csi_client.go]: This check does look unnecessary to me. It doesn't look like anything inside `nodeGetInfoV1` would return that error. I can't recall why it was added. @taragu do you remember?

File: pkg/volume/csi/csi_client.go (hunk 4 above)
Comment (tedyu) [reply pkg/volume/csi/csi_client.go]: Please take a look at the updated PR.
If there is no error, probably we don't need extra logging.

File: pkg/volume/csi/csi_client.go (hunk 2 above)
Comment (taragu) [reply pkg/volume/csi/csi_client.go]: Yeah I agree this is unnecessary since that error doesn't come from `nodeGetInfoV1`. I think it was added by mistake and can be safely removed.

**Review by taragu — COMMENTED** [review]
/lgtm
If you are interested in doing a followup PR to rewrite method `func (c *csiDriverClient) NodeGetInfo(ctx context.Context)` to remove the exponential backoff since it's now done at the operation executor layer (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pluginmanager/operationexecutor/operation_executor.go#L82), please feel free to do so and let me know if you have any questions.

**Comment by tedyu** [comment]
@taragu 
I have patch ready which removes the exponential backoff.

I will submit PR once this goes in.

File: pkg/volume/csi/csi_client.go [hunk 5]
```diff
@@ -162,8 +161,8 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
 			return true, nil
 		}
 		// kubelet plugin registration service not implemented is a terminal error, no need to retry
```
Comment (msau42) [inline pkg/volume/csi/csi_client.go]: this comment should be removed

Comment (tedyu) [reply pkg/volume/csi/csi_client.go]: @msau42 
Your comment has been addressed.
