### PR TITLE
Fix for duplicate revisions created by StatefulSet

### LINKED ISSUE #55159: Statefulset : CreateControllerRevision function bug
**Is this a BUG REPORT**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

When a statefulset object is created, a lot of controllerrevisions are created at the same time.
the controllerrevisions have differenct hash value but the same Data.Raw.

**How to fix it**:

two controllerrevisions are seen as the same , when Controllerrevision.labels[ControllerRevisionHashLabel] , Controllerrevision.Data.Raw , Controllerrevision.Data.Object are strictly the same 

 // this line shoud be added to fix the bug
```
clone.Labels[ControllerRevisionHashLabel] = strconv.FormatInt(int64(hash), 10)
```

like below: 

```
func (rh *realHistory) CreateControllerRevision(parent metav1.Object, revision *apps.ControllerRevision, collisionCount *int32) (*apps.ControllerRevision, error) {
    if collisionCount == nil {
        return nil, fmt.Errorf("collisionCount should not be nil")
    }

    // Clone the input
    clone := revision.DeepCopy()

    // Continue to attempt to create the revision updating the name with a new hash on each iteration
    for {
        hash := HashControllerRevision(revision, collisionCount)
        // Update the revisions name and labels
        clone.Name = ControllerRevisionName(parent.GetName(), hash)
        clone.Labels[ControllerRevisionHashLabel] = strconv.FormatInt(int64(hash), 10)
        created, err := rh.client.AppsV1beta1().ControllerRevisions(parent.GetNamespace()).Create(clone)
        if errors.IsAlreadyExists(err) {
            *collisionCount++
            continue
        }
        return created, err
    }
}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.8
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mortent**
**What this PR does / why we need it**: This PR replaces PR #65038 as a fix to issue #55159. The statefulset controller can in some situations create more controller revisions than necessary and this change makes sure the controller checks with the API server and only create new revision if the raw data is different.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55159

**Special notes for your reviewer**:

**Release note**:

```release-note
Avoid creating new controller revisions for statefulsets when cache is stale
```

### CODE REVIEW

File: pkg/controller/history/controller_history_test.go [hunk 1]
```diff
@@ -258,8 +258,8 @@ func TestRealHistory_CreateControllerRevision(t *testing.T) {
 		history := NewHistory(client, informer.Lister())
 
 		var collisionCount int32
-		for i := range test.existing {
-			_, err := history.CreateControllerRevision(test.existing[i].parent, test.existing[i].revision, &collisionCount)
+		for _, exst := range test.existing {
```
Comment (neolit123) [inline pkg/controller/history/controller_history_test.go]: `exst` -> `exists`

File: pkg/controller/history/controller_history.go [hunk 2]
```diff
@@ -252,6 +252,13 @@ func (rh *realHistory) CreateControllerRevision(parent metav1.Object, revision *
 		clone.Name = ControllerRevisionName(parent.GetName(), hash)
 		created, err := rh.client.AppsV1().ControllerRevisions(parent.GetNamespace()).Create(clone)
 		if errors.IsAlreadyExists(err) {
+			existed, err := rh.client.AppsV1().ControllerRevisions(parent.GetNamespace()).Get(clone.Name, metav1.GetOptions{})
+			if err != nil {
+				return nil, err
+			}
+			if bytes.Equal(existed.Data.Raw, clone.Data.Raw) {
+				return existed, err
```
Comment (neolit123) [inline pkg/controller/history/controller_history.go]: `existed, err` -> `existed, nil` to make an explicit statement here.
or `exists, nil` as per the above comment about tense.

File: pkg/controller/history/controller_history.go [hunk 3]
```diff
@@ -252,6 +252,13 @@ func (rh *realHistory) CreateControllerRevision(parent metav1.Object, revision *
 		clone.Name = ControllerRevisionName(parent.GetName(), hash)
 		created, err := rh.client.AppsV1().ControllerRevisions(parent.GetNamespace()).Create(clone)
 		if errors.IsAlreadyExists(err) {
+			existed, err := rh.client.AppsV1().ControllerRevisions(parent.GetNamespace()).Get(clone.Name, metav1.GetOptions{})
```
Comment (neolit123) [inline pkg/controller/history/controller_history.go]: `existed` -> `exists` present tense?

**Review by neolit123 — COMMENTED** [review]
/sig apps
/kind bug

**Comment by neolit123** [comment]
thank you for your first PR @mortent :+1: 
added a couple of review comments.

File: pkg/controller/history/controller_history_test.go (hunk 1 above)
Comment (mortent) [reply pkg/controller/history/controller_history_test.go]: Renamed the iteration variable to` item`. I think exists just sounds too much like a boolean variable and the name is also used by another variable in the function.

**Comment by mortent** [comment]
@neolit123 Thanks for the comments. I have updated the PR.

File: pkg/controller/history/controller_history_test.go [hunk 4]
```diff
@@ -302,7 +302,11 @@ func TestRealHistory_CreateControllerRevision(t *testing.T) {
 		t.Fatal(err)
 	}
 	ss1Rev1.Namespace = ss1.Namespace
-	ss1Rev2, err := NewControllerRevision(ss1, parentKind, ss1.Spec.Template.Labels, rawTemplate(&ss1.Spec.Template), 2, ss1.Status.CollisionCount)
+	modTemplate := ss1.Spec.Template.DeepCopy()
+	modTemplate.Labels["foo"] = "not_bar"
+	ss1Rev2, err := NewControllerRevision(ss1, parentKind, ss1.Spec.Template.Labels, rawTemplate(modTemplate), 2, ss1.Status.CollisionCount)
+	ss1Rev2.Name = ss1Rev1.Name
```
Comment (crimsonfaith91) [inline pkg/controller/history/controller_history_test.go]: By modifying labels of `modTemplate`, the hash for populating name and labels fields will change, so I think it is incorrect to set `ss1Rev2.Name = ss1Rev1.Name` (same with `.Labels` below).

Comment (mortent) [reply pkg/controller/history/controller_history_test.go]: The labels are being manipulated in this way in order to set up the scenario where there are two controller revisions with the same name and hash label, but which are not identical. This is done by creating a new controller revision which is slightly different than an existing one (change the value of a label) and then give it the same name and label as the existing one. This will create a controller revision where the name and hash are "incorrect" for the content, but it works for setting up the data for the test. Normally this would be the result of a hash collision, we don't have a way to create those in the test.

Comment (crimsonfaith91) [reply pkg/controller/history/controller_history_test.go]: Noted. As this is a unit test, I think this can be made clearer by creating the 2nd `ControllerRevision` (with the same name and labels) before modifying it's labels.

**Comment by crimsonfaith91** [comment]
/lgtm

Other than the nit comments, everything looks good to me.

File: pkg/controller/history/controller_history_test.go (hunk 4 above)
Comment (crimsonfaith91) [reply pkg/controller/history/controller_history_test.go]: As sync by person, `ControllerRevision` is immutable once created, so this "hack" is necessary. I will LGTM again once comments are added. Thanks for the work!
