### PR TITLE
[InPlacePodLevelResourcesVerticalScaling] fix erroneously reporting a PLR resize in progress on pod creation

### LINKED ISSUE #137858: [InPlacePodVerticalScaling] Unnecessary ResizeCompleted event emitted when PLR FG is enabled
### What happened?

After I create a pod using a Kubernetes deployment in an empty Kind cluster, I see an in-place update event that seems unnecessary:

```bash
kubectl get events --watch -A

default              0s          Normal    ResizeCompleted           pod/hamster-deployment-57445548f6-r27rn          Pod resize completed: {"containers":[{"name":"hamster1","resources":{"requests":{"cpu":"10m","memory":"10Mi"}}},{"name":"hamster2","resources":{}},{"name":"hamster3","resources":{}}],"generation":1}
```

### What did you expect to happen?

I don't expect to see an in-place update after deploying the pod to the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

```bash
KIND_VERSION="kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f"

kind create cluster --image=${KIND_VERSION} --config <(cat <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "InPlacePodLevelResourcesVerticalScaling": true
  "NodeDeclaredFeatures": true
EOF
)
```

```yaml
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hamster
  name: hamster-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster
  template:
    metadata:
      labels:
        app: hamster
    spec:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      containers:
      - name: hamster1
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      - image: registry.k8s.io/pause:3.1
        name: hamster2
      - image: registry.k8s.io/pause:3.1
        name: hamster3
EOF
```

### Anything else we need to know?

* I don't have anything like Vertical Pod Autoscaler that should trigger in-place updates at any level (container or pod).
* related slack thread: https://kubernetes.slack.com/archives/C06FSK01BGU/p1773818099854269

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.1
Kustomize Version: v5.7.1
Server Version: v1.35.0
```

</details>

### Cloud provider

<details>
kind cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
$ uname -a
Linux 6.14.6-2-MANJARO #1 SMP PREEMPT_DYNAMIC Wed, 14 May 2025 14:56:34 +0000 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://2.2.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by natasha41575**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When a pod is first created and goes through its first sync loop iteration, the actuated resources != allocated resources, because neither the containers nor pod cgroups have been set up yet. The pod-level resize in-progress check is erroneously reporting in this scenario that a resize is in progress; on the next sync loop iteration it corrects itself - however this results in an unnecessary ResizeCompleted event being emitted due to the status manager believing that the PodResizeInProgress condition has been flipped from `true` to `false`.

For container-level resize, we have a check to prevent this exact circumstance here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L2198-L2200.

This PR adds an analogous check for pod-level resize, where a pod-level resize in-progress check reports false if none of the containers are running. I have confirmed the fix using the reproduction steps reported in https://github.com/kubernetes/kubernetes/issues/137858.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/137858.

#### Special notes for your reviewer:

~I don't think this is critical for 1.36, but we should try to merge this prior to PLR resize GA.~

ETA: This was deemed important for 1.36 because it impacts every pod that is created with pod-level resources, and both features are now beta and enabled by default.

#### Does this PR introduce a user-facing change?

```release-note
Fix erroneously reporting a pod-level resize in progress on pod creation when InPlacePodLevelResourcesVerticalScaling is enabled.
```

/sig node
/assign @ndixita @tallclair 
/priority important-longterm

### CODE REVIEW

**Comment by natasha41575** [comment]
@kubernetes/release-managers This will be a widespread issue that occurs for every pod that is created with pod-level resources and is a regression. Let me know if we can take it for 1.36.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go
Comment (tallclair) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:2240]: A simpler fix might be to just return false if there isn't any actuated state saved yet.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -2218,7 +2218,22 @@ func (m *kubeGenericRuntimeManager) isPodLevelResourcesResizeInProgress(allocate
...
+		func(allocatedContainer *v1.Container, containerType podutil.ContainerType) (shouldContinue bool) {
+			if !isResizableContainer(allocatedContainer, containerType) {
+				return true
+			}
+			containerStatus := podStatus.FindContainerStatusByName(allocatedContainer.Name)
+			return containerStatus == nil || containerStatus.State != kubecontainer.ContainerStateRunning
+		},
+	)
+
+	if !isAnyContainerRunning {
```
Comment (bitoku) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:2236]: We can remove double negation.
Can we have the common function for this and `isContainerResourceResizeInProgress` ?

```suggestion
	allResizableContainersNotRunning := podutil.VisitContainers(&allocatedPod.Spec, podutil.InitContainers|podutil.Containers,
		func(allocatedContainer *v1.Container, containerType podutil.ContainerType) (shouldContinue bool) {
		    // ignore if the container is not resizable.
			if !isResizableContainer(allocatedContainer, containerType) {
				return true
			}
			containerStatus := podStatus.FindContainerStatusByName(allocatedContainer.Name)
			return containerStatus == nil || containerStatus.State != kubecontainer.ContainerStateRunning
		},
	)

	if allResizableContainersNotRunning {
```
