### PR TITLE
When --grace-period=0 is provided, wait for deletion

### LINKED ISSUE #37117: kubectl --force deletion is breaking upgrade tests
In 1.5, kubectl now requires --force when --grace-period=0 for deletion. This is causing 1.3 e2e tests to fail when running with a 1.5 kubectl in the upgrade tests. This was added in #35484. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster/143?log

```console
Expected error:
    <*errors.errorString | 0xc820019820>: {
        s: "Error running &{/workspace/kubernetes_skew/cluster/kubectl.sh [/workspace/kubernetes_skew/cluster/kubectl.sh --server=https://199.223.235.243 --kubeconfig=/workspace/.kube/config delete --grace-period=0 -f - --namespace=e2e-tests-kubectl-up6nc] []  0xc8207b9b60  error: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely. You must pass --force to delete with grace period 0.\n [] <nil> 0xc8206fe440 exit status 1 <nil> true [0xc820ea4718 0xc820ea4740 0xc820ea4750] [0xc820ea4718 0xc820ea4740 0xc820ea4750] [0xc820ea4720 0xc820ea4738 0xc820ea4748] [0xa97840 0xa979a0 0xa979a0] 0xc82027b800}:\nCommand stdout:\n\nstderr:\nerror: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely. You must pass --force to delete with grace period 0.\n\nerror:\nexit status 1\n",
    }
    Error running &{/workspace/kubernetes_skew/cluster/kubectl.sh [/workspace/kubernetes_skew/cluster/kubectl.sh --server=https://199.223.235.243 --kubeconfig=/workspace/.kube/config delete --grace-period=0 -f - --namespace=e2e-tests-kubectl-up6nc] []  0xc8207b9b60  error: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely. You must pass --force to delete with grace period 0.
     [] <nil> 0xc8206fe440 exit status 1 <nil> true [0xc820ea4718 0xc820ea4740 0xc820ea4750] [0xc820ea4718 0xc820ea4740 0xc820ea4750] [0xc820ea4720 0xc820ea4738 0xc820ea4748] [0xa97840 0xa979a0 0xa979a0] 0xc82027b800}:
    Command stdout:
    
    stderr:
    error: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely. You must pass --force to delete with grace period 0.
    
    error:
    exit status 1
    
not to have occurred
```

### PR DESCRIPTION
**Pull request by smarterclayton**
The grace-period is automatically set to 1 unless --force is provided, and the client waits until the object is deleted.

This preserves backwards compatibility with 1.4 and earlier. It does not handle scenarios where the object is deleted and a new object is created with the same name because we don't have the initial object loaded (and that's a larger change for 1.5).

Fixes #37117 by relaxing the guarantees provided.

```release-note
When deleting an object with `--grace-period=0`, the client will begin a graceful deletion and wait until the resource is fully deleted.  To force deletion, use the `--force` flag.
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37263)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Proposed for 1.5 to avoid backwards compatibility.

**Comment by smarterclayton** [comment]
@k8s-bot bazel test this

**Comment by fabianofranz** [comment]
@smarterclayton so both `--grace-period=0` and `--now` will set `gracePeriod` to `1`, but the difference is that the first waits?

File: pkg/kubectl/cmd/delete.go [hunk 1]
```diff
@@ -169,25 +170,35 @@ func RunDelete(f cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []stri
...
+	wait := false
+	if gracePeriod == 0 {
+		if force {
+			fmt.Fprintf(errOut, "warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.\n")
+		} else {
+			// To preserve backwards compatibility, but prevent accidental data loss, we convert --grace-period=0
+			// into --grace-period=1 and wait until the object is successfully deleted. Users may provide --force
+			// to bypass this wait.
+			wait = true
+			gracePeriod = 1
```
Comment (fabianofranz) [inline pkg/kubectl/cmd/delete.go]: `--grace-period=0` may now be mutually exclusive with `--timeout`

Comment (smarterclayton) [inline pkg/kubectl/cmd/delete.go]: It's not, timeout is still respected.

**Comment by smarterclayton** [comment]
> so both --grace-period=0 and --now will set gracePeriod to 1, but the difference is that the first waits?

To avoid breaking old scripts, --grace-period=0 continues to not return (waits) until the object is gone.  --now continues to behave as it did before.

**Comment by fabianofranz** [comment]
LGTM

File: pkg/client/restclient/request.go [hunk 2]
```diff
@@ -818,10 +818,12 @@ func (r *Request) request(fn func(*http.Request, *http.Response)) error {
 			// connection.
 			defer func() {
 				const maxBodySlurpSize = 2 << 10
-				if resp.ContentLength <= maxBodySlurpSize {
-					io.Copy(ioutil.Discard, &io.LimitedReader{R: resp.Body, N: maxBodySlurpSize})
+				if resp.Body != nil {
```
Comment (krousey) [inline pkg/client/restclient/request.go]: This check should not be required.

```
        // The http Client and Transport guarantee that Body is always
        // non-nil, even on responses without a body or responses with
        // a zero-length body.
```

File: pkg/kubectl/cmd/delete_test.go [hunk 3]
```diff
@@ -131,6 +135,81 @@ func TestDeleteObject(t *testing.T) {
...
+		Client: fake.CreateHTTPClient(func(req *http.Request) (*http.Response, error) {
+			t.Logf("got request %s %s", req.Method, req.URL.Path)
+			switch p, m := req.URL.Path, req.Method; {
+			case p == "/namespaces/test/pods/nginx" && m == "GET":
+				count++
+				switch count {
+				case 1, 2, 3:
+					return &http.Response{StatusCode: 200, Header: defaultHeader(), Body: objBody(codec, &pods.Items[0])}, nil
+				default:
+					return &http.Response{StatusCode: 404, Header: defaultHeader(), Body: nil}, nil
```
Comment (krousey) [inline pkg/kubectl/cmd/delete_test.go]: This should provide a non-nil body, even if it is empty.

**Review by krousey — CHANGES_REQUESTED** [review]

File: pkg/client/restclient/request.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/client/restclient/request.go]: Test cases were passing nil in, and we guard against it in other places.  I'll remove both guards and hunt down the bug.

**Comment by krousey** [comment]
cc @roberthbailey

**Comment by smarterclayton** [comment]
Updated with all comments.

**Comment by saad-ali** [comment]
@k8s-bot test this

**Comment by dchen1107** [comment]
This pr might need more attention, and I decided not manually merge it for holiday code freeze in favor to merge two large prs: https://github.com/kubernetes/kubernetes/pull/36673
and https://github.com/kubernetes/kubernetes/pull/36782

**Comment by smarterclayton** [comment]
Yes, that's fine with me.

**Comment by eparis** [comment]
@k8s-bot gce node e2e test this

**Review by krousey — APPROVED** [review]

**Comment by eparis** [comment]
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
@foxish can you review. Let's get this merged ASAP, so we can unblock upgrade testing

**Comment by foxish** [comment]
LGTM except for the one comment.

File: pkg/kubectl/cmd/replace.go [hunk 4]
```diff
@@ -213,10 +213,18 @@ func forceReplace(f cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []s
...
+		gracePeriod = 1
+		waitForDeletion = true
+	}
 	// By default use a reaper to delete all related resources.
 	if cmdutil.GetFlagBool(cmd, "cascade") {
 		glog.Warningf("\"cascade\" is set, kubectl will delete and re-create all resources managed by this resource (e.g. Pods created by a ReplicationController). Consider using \"kubectl rolling-update\" if you want to update a ReplicationController together with its Pods.")
-		err = ReapResult(r, f, out, cmdutil.GetFlagBool(cmd, "cascade"), ignoreNotFound, timeout, cmdutil.GetFlagInt(cmd, "grace-period"), shortOutput, mapper, false)
+		err = ReapResult(r, f, out, cmdutil.GetFlagBool(cmd, "cascade"), ignoreNotFound, timeout, gracePeriod, waitForDeletion, shortOutput, mapper, false)
 	} else {
 		err = DeleteResult(r, out, ignoreNotFound, shortOutput, mapper)
```
Comment (foxish) [inline pkg/kubectl/cmd/replace.go]: It seems like this should go through ReapResult as well? Currently, we would print out "pod is deleted" prior to its actual deletion, and then eventually hit the timeout condition a few lines below.

File: pkg/kubectl/cmd/delete.go [hunk 5]
```diff
@@ -254,3 +270,24 @@ func deleteResource(info *resource.Info, out io.Writer, shortOutput bool, mapper
...
+// objectDeletionWaitInterval is the interval to wait between checks for deletion. Exposed for testing.
+var objectDeletionWaitInterval = time.Second
+
+// waitForObjectDeletion refreshes the object, waiting until it is deleted, a timeout is reached, or
+// an error is encountered. It checks once a second.
+func waitForObjectDeletion(info *resource.Info, timeout time.Duration) error {
+	copied := *info
+	info = &copied
+	// TODO: refactor Reaper so that we can pass the "wait" option into it, and then check for UID change.
+	return wait.PollImmediate(objectDeletionWaitInterval, timeout, func() (bool, error) {
```
Comment (foxish) [inline pkg/kubectl/cmd/delete.go]: I think in the timeout case, we should return a better error than "timed out waiting for the condition" because we surface 
that error to the user.

File: pkg/kubectl/cmd/replace.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/kubectl/cmd/replace.go]: We don't actually even do graceful deletion in this code path (we use the server default) so it's not backwards incompatible.  Definitely something we need to fix in the future, but not for 1.5

**Comment by smarterclayton** [comment]
Follow up issue opened as
https://github.com/kubernetes/kubernetes/issues/37637

**Comment by dims** [comment]
@k8s-bot node e2e test this

**Comment by dims** [comment]
@k8s-bot unit test this

**Comment by saad-ali** [comment]
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
@k8s-bot kops aws e2e test this

**Comment by dims** [comment]
@k8s-bot node e2e test this
