### PR TITLE
switch scheduler to generate the merge patch on pod status instead of the full pod

### LINKED ISSUE #101697: Empty imagePullSecrets leads to status.conditions never being set
I am aware that the following is a corner case that does not occur in day-to-day business, but it took me a long while to debug, so I thought I would raise this issue to save others from the same pain.

#### What happened:

Deploying the following job with empty imagePullSecrets leads to it being stuck in `Pending` forever, and status looking the following way:
```json
"status": {
    "phase": "Pending",
    "qosClass": "BestEffort"
}
```

```yaml 
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      imagePullSecrets:
        - {}
      containers:
        - name: hello
          image: busybox
          command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure
      tolerations:
        - key: "jobs"
          operator: "Equal"
          value: "1"
          effect: "NoSchedule"
      nodeSelector:
        jobs: "1"
```

#### What you expected to happen:

The status should look something like:
```json
"status": {
    "phase": "Pending",
    "conditions": [
           {
                "type": "PodScheduled",
                "status": "False",
                "lastProbeTime": null,
                "lastTransitionTime": "2021-05-02T18:34:25Z",
                "reason": "Unschedulable",
                "message": "0/8 nodes are available: 8 node(s) didn't match node selector."
           }
    ],
    "qosClass": "BestEffort"
}
```
This would allow my autoscaler to kick in and add the corresponding nodes.

#### How to reproduce it (as minimally and precisely as possible):

Run `kubectl apply -f <file-with-above-yaml-as-content>`

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS EKS
- OS (e.g: `cat /etc/os-release`): MacOSX 11.3
- Kernel (e.g. `uname -a`): Darwin Kernel Version 20.4.0
- Install tools: brew

### PR DESCRIPTION
**Pull request by marwanad**
#### What type of PR is this?

/kind bug
/sig scheduling
#### What this PR does / why we need it:
When the scheduler fails to schedule pods (due to insufficient resources for example) and calls into `recordSchedulingFailure`, it attempts to update pod conditions through a strategic merge patch. This patching logic fails if the pod has ImagePullSecrets with no `name` since the `patchMergeKey` is set to the `name` field. An `imagePullSecrets` input of `[{}]` is valid in k8s.

As a result certain components that depend on those scheduler conditions to issue a scale-up, fail to do so or even acknowledge the pending pods (for example cluster-autoscaler).

This switches scheduler patching logic to generate the 2-way merge patch on the pod.Status instead of the full pod object.

#### Which issue(s) this PR fixes:

Fixes #101697

#### Does this PR introduce a user-facing change?

```release-note
Switch scheduler to generate the merge patch on pod status instead of the full pod
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -347,6 +347,16 @@ func updatePod(client clientset.Interface, pod *v1.Pod, condition *v1.PodConditi
 	if nominatedNode != "" {
 		podCopy.Status.NominatedNodeName = nominatedNode
 	}
+	// See issue: #94626. This is to handle the case with empty name field in spec.ImagePullSecrets
+	// which is also the patchMergeKey and would fail the two-way merge patch generation and prevent scheduler from updating
+	// the pod conditions
+	var pullSecrets []v1.LocalObjectReference
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:353]: This is solving the symptom, rather than the root cause.

The root cause is that the produced 2-way merge patch includes changes to the ImagePullSecrets where it shouldn't.

Why? We are serializing the same values for secrets. Can you show the output of the marshaling and the produced patch?

Comment (marwanad) [reply pkg/scheduler/scheduler.go:353]: The root-cause is that producing the two merge way patch fails due to the missing`name` field. I'd expect modifying the strategic merge patch code to clear empty slices would be a breaking change - hence this proposal.

https://github.com/kubernetes/kubernetes/blob/06dfe683cefe06ee1cd09ab14b9c890b1c651786/staging/src/k8s.io/api/core/v1/types.go#L3072-L3074

This pod spec is valid on create:
```
...
imagePullSecrets:
- {}
...
```
Inside `PatchPod`:

oldData:
```
{"metadata":{"name":"pod1","namespace":"ns","creationTimestamp":null},"spec":{"containers":null,"imagePullSecrets":[{}]},"status":{}}
```
newData:
```
{"metadata":{"name":"pod1","namespace":"ns","creationTimestamp":null},"spec":{"containers":null,"imagePullSecrets":[{}]},"status":{"conditions":[{"type":"PodScheduled","status":"False","lastProbeTime":null,"lastTransitionTime":"2021-06-24T15:56:56Z"}]}}
```

Calling CreateTowoWayMergePatch(oldData, newData) will fail with:

```
map: map[] does not contain declared merge key: name
```

One way to avoid the patch creation failure is to drop the imagePullSecrets from the new pod which is what this change is doing:

With the change, newData becomes:
```
{"metadata":{"name":"pod1","namespace":"ns","creationTimestamp":null},"spec":{"containers":null},"status":{"conditions":[{"type":"PodScheduled","status":"False","lastProbeTime":null,"lastTransitionTime":"2021-06-24T16:03:26Z"}]}}
```

This wouldn't be an issue if that "bad input" was blocked on creates but that ship has long sailed and it seems the way it will be addressed is through warnings (https://github.com/kubernetes/kubernetes/issues/94626) to be backwards compatible.

I'm open to other suggestions for fixing that here.

Comment (marwanad) [reply pkg/scheduler/scheduler.go:353]: I always realized that `ClearNominatedNodeName` will call PatchPod and will likely hit the same issue so I can move that fix to happen inside `PatchPod` (which seems slightly odd to have in there), once we settle on an approach.

Comment (alculquicondor) [reply pkg/scheduler/scheduler.go:353]: Thanks for the context (#94626)

`PatchPod` is within the scheduler package, so it might be fine to do changes there. The scheduler is only concerned very few things, in terms of patching: conditions and nominated nodename, both part of the status.

I think a better alternative is to do some kind of allow list: instead of doing a DeepCopy of the entire pod, we just do it for the status. And we use the statuses for the creating the patch. Then, you probably have to add some extra formatting to create the Pod patch.

Comment (marwanad) [reply pkg/scheduler/scheduler.go:353]: Good point. That would be a lot cleaner since we only care about status. I'll adjust the change.

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -1488,3 +1488,80 @@ func TestUpdatePod(t *testing.T) {
 		})
 	}
 }
+
+func TestUpdatePodWithSecrets(t *testing.T) {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1492]: Fine for now, but can you open a follow up PR to merge this with the test above into a single test table?

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -1488,3 +1488,80 @@ func TestUpdatePod(t *testing.T) {
...
+
+			if retrievedPod.Status.Conditions[0].Status != pod.Status.Conditions[0].Status || retrievedPod.Status.Conditions[0].Type != pod.Status.Conditions[0].Type {
+				t.Errorf("unexpected conditions set on pod: %v", retrievedPod.Status.Conditions)
+			}
+
+			if retrievedPod.Status.Conditions[1].Status != tc.conditionToSet.Status || retrievedPod.Status.Conditions[1].Type != tc.conditionToSet.Type {
+				t.Errorf("unexpected conditions set on pod: %v", retrievedPod.Status.Conditions)
+			}
+
+			if len(retrievedPod.Spec.ImagePullSecrets) > 0 {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler_test.go:1560]: I think this check is too specific. For this bug, it was enough to check that updatePod doesn't return an error.

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm

/hold
in case you want to solve the recommendations I left.

File: pkg/scheduler/scheduler_test.go (hunk 3 above)
Comment (marwanad) [reply pkg/scheduler/scheduler_test.go:1560]: yeah fair enough. Was mostly ensuring we don't wipe secrets but I agree not needed.

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (marwanad) [reply pkg/scheduler/scheduler_test.go:1492]: I'll adjust it in this PR.

File: pkg/scheduler/scheduler_test.go (hunk 3 above)
Comment (marwanad) [reply pkg/scheduler/scheduler_test.go]: @alculquicondor I moved the test to be under utils and test for `PatchPodStatus` instead since that's where the changed logic is now. lmk what you think.

File: pkg/scheduler/util/utils_test.go [hunk 4]
```diff
@@ -173,3 +174,72 @@ func TestRemoveNominatedNodeName(t *testing.T) {
...
+	tests := []struct {
+		name           string
+		podName        string
+		secrets        []v1.LocalObjectReference
+		statusToUpdate v1.PodStatus
+	}{
+		{
+			name:    "Should update pod conditions successfully",
+			podName: "pod2",
+			secrets: []v1.LocalObjectReference{{Name: "foo"}},
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:188]: This makes the test table specific to this bug. Better to accept a Pod.

File: pkg/scheduler/util/utils_test.go [hunk 5]
```diff
@@ -173,3 +174,72 @@ func TestRemoveNominatedNodeName(t *testing.T) {
...
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			retrievedPod, err := client.CoreV1().Pods(ns).Get(context.TODO(), tc.podName, metav1.GetOptions{})
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			if retrievedPod.Status.Conditions[0].Status != tc.statusToUpdate.Conditions[0].Status || retrievedPod.Status.Conditions[0].Type != tc.statusToUpdate.Conditions[0].Type {
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:240]: Use `cmp.Diff` and compare the entire status.

File: pkg/scheduler/util/utils_test.go [hunk 6]
```diff
@@ -173,3 +174,72 @@ func TestRemoveNominatedNodeName(t *testing.T) {
...
+				Conditions: []v1.PodCondition{
+					{
+						Type:   v1.PodScheduled,
+						Status: v1.ConditionFalse,
+					},
+				},
+			},
+		},
+		{
+			name:    "Should update pod conditions successfully on a pod Spec with secrets with empty name",
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:199]: Add a comment with a link to the relevant k/k issue, so that future readers understand why this test case is important.

File: pkg/scheduler/util/utils_test.go (hunk 4 above)
Comment (marwanad) [reply pkg/scheduler/util/utils_test.go]: yeah I realized what you meant by having the secret as part of the test table. updated now :)

**Comment by alculquicondor** [comment]
Please cherry pick to all supported versions (1.19, 1.20, 1.21) https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md
