### PR TITLE
Fix OpenAPI aggregation cleanup

### LINKED ISSUE #120107: kube-apiserver doesn't clean up OpenAPI properly after deleting an APIService/CRD
### What happened?

I noticed some odd behaviors/logs after deleting APIServices and CRDs.

First, only CRDs were removed from the response of `/openapi/v3` and APIServices were not removed. Not only the root path, the APIService's specific paths were also available, e.g. `/openapi/v3/apis/foo.bar.com/v1alpha1`, as if they were not deleted.

Second, there were some confusing logs in kube-apiserver, indicating it failed to do some cleanup, and every failure was duplicated once:
```
E0822 15:24:36.314675       1 controller.go:159] removing "v1alpha1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.314705       1 controller.go:159] removing "v1alpha1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.316316       1 controller.go:159] removing "v1beta1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.317664       1 controller.go:159] removing "v1beta1.crd.antrea.io" from AggregationController failed with: resource not found
```

After checking the code, I found the above observations were caused by the same code in kube-apiserver which didn't handle the removal of APIService correctly:
https://github.com/kubernetes/kubernetes/blob/aa8cb97f65fe1d24e96eda129337d86109615570/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L563-L568

Basically apiserver was calling wrong AggregationController when removing APIService, which caused OpenAPI v3 not cleaned up and the duplicate errors. There was another issue in v2 AggregationController which caused the error. 

Besides, just correcting L567 didn't fix the problem totally, there were some other issues in the implementation.

### What did you expect to happen?

kube-apiserver should clean up OpenAPI correctly, shoud not generate confusing errors.

### How can we reproduce it (as minimally and precisely as possible)?

Install some APIServices and CRDs and remove all of them, then check the response of "/openapi/v3" and kube-apiserver logs.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.0", GitCommit:"855e7c48de7388eb330da0f8d9d2394ee818fb8d", GitTreeState:"clean", BuildDate:"2023-08-15T21:24:51Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

There were four issues in OpenAPI aggregation cleanup:
1. When removing an APIService, openAPIAggregationController was called twice while openAPIV3AggregationController was never called, leading to OpenAPI v3 for the APIService not cleaned up.
2. When removing a local APIService, v2 specAggregator should not return ErrAPIServiceNotFound when it doesn't find the APIService because local APIServices were never added to its cache, otherwise confusing error logs would be generated. Besides, the method's comment indicates that the desired behavior is that no error is returned if the APIService does not exist.
3. When removing an APIService, v3 specProxier should update openapiv2converter's cache, like when updating an APIService, otherwise the API would not be removed from "/openapi/v3".
4. When v3 AggregationController reconciles an APIService, it should stop requeueing it if it fails with ErrAPIServiceNotFound as the APIService has been removed, like what v2 AggregationController does, otherwise it would keep reconciling the APIService forever.

#### Which issue(s) this PR fixes:

Fixes #120107

#### Does this PR introduce a user-facing change?

```release-note
Fix OpenAPI v3 not being cleaned up after deleting APIServices
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/apimachinery/openapiv3.go [hunk 1]
```diff
@@ -163,5 +173,17 @@ var _ = SIGDescribe("OpenAPIV3", func() {
 			diff := cmp.Diff(*openAPISpec, spec2)
 			framework.Failf("%s", diff)
 		}
+
+		cleanupSampleAPIServer(ctx, f.ClientSet, aggrclient, names, "v1beta1.wardle.example.com")
```
Comment (Jefftree) [inline test/e2e/apimachinery/openapiv3.go:177]: Line 153 `defer cleanupSampleAPIServer(ctx, f.ClientSet, aggrclient, names, "v1beta1.wardle.example.com")` shouldn't be needed anymore since it's moved here?

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go [hunk 2]
```diff
@@ -236,7 +236,7 @@ func (s *specAggregator) RemoveAPIService(apiServiceName string) error {
 	defer s.mutex.Unlock()
 
 	if _, exists := s.specsByAPIServiceName[apiServiceName]; !exists {
-		return ErrAPIServiceNotFound
+		return nil
```
Comment (Jefftree) [inline staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:239]: This function cannot return an error anymore right? Would it make sense to to change the function signature so it's more clear?

**Review by Jefftree — COMMENTED** [review]
Thanks for reporting and fixing this! A couple small nits

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go (hunk 2 above)
Comment (tnqn) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:239]: Sure, changed the signature.

File: test/e2e/apimachinery/openapiv3.go (hunk 1 above)
Comment (tnqn) [reply test/e2e/apimachinery/openapiv3.go:177]: Do we need to ensure the resources created by the test get cleaned up regardless of success or failure? I kept the defer statement for that, otherwise the resources would be left over if `ExpectNoError` above fails and terminates the test.

**Review by tnqn — COMMENTED** [review]
@Jefftree thanks for your review and comments.

File: test/e2e/apimachinery/openapiv3.go [hunk 3]
```diff
@@ -97,13 +100,33 @@ var _ = SIGDescribe("OpenAPIV3", func() {
 		framework.ExpectNoError(err)
 		dynamicClient, err := dynamic.NewForConfig(config)
 		framework.ExpectNoError(err)
-		crd := fixtures.NewRandomNameV1CustomResourceDefinition(apiextensionsv1.NamespaceScoped)
+		resourceName := "testcrd"
+		// Generate a CRD with random group name to avoid group conflict with other tests that run in parallel.
```
Comment (tnqn) [inline test/e2e/apimachinery/openapiv3.go:104]: The change is necessary to avoid flaky test like this one: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120108/pull-kubernetes-e2e-kind/1694014809265147904, which failed because "should support orphan deletion of custom resources" created a CRD with the same group name during this test's execution.
```
"LeafNodeText": "should support orphan deletion of custom resources",
"State": "passed",
"StartTime": "2023-08-22T16:15:51.500448107Z",
"EndTime": "2023-08-22T16:17:29.67599027Z",
...
"LeafNodeText": "should publish OpenAPI V3 for CustomResourceDefinition",
"State": "failed",
"StartTime": "2023-08-22T16:15:57.342871504Z",
"EndTime": "2023-08-22T16:16:34.691586543Z",
```

File: test/e2e/apimachinery/openapiv3.go (hunk 1 above)
Comment (Jefftree) [reply test/e2e/apimachinery/openapiv3.go:203]: Ah good catch. What about this entire section in a defer statement? I'd just like to avoid calling the function twice.

File: test/e2e/apimachinery/openapiv3.go (hunk 3 above)
Comment (Jefftree) [reply test/e2e/apimachinery/openapiv3.go:104]: Thanks for catching this!

File: test/e2e/apimachinery/openapiv3.go (hunk 1 above)
Comment (tnqn) [reply test/e2e/apimachinery/openapiv3.go]: sure, done

**Comment by tnqn** [comment]
> I think we should backport this at least to 1.27

Will backport it after merged.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go [hunk 4]
```diff
@@ -133,10 +133,12 @@ func (c *AggregationController) processNextWorkItem() bool {
...
-	err := c.openAPIAggregationManager.UpdateAPIServiceSpec(key)
-	switch {
-	case err != nil:
-		return syncRequeueRateLimited, err
+	if err := c.openAPIAggregationManager.UpdateAPIServiceSpec(key); err != nil {
+		if err == aggregator.ErrAPIServiceNotFound {
+			return syncNothing, nil
+		} else {
+			return syncRequeueRateLimited, err
+		}
```
Comment (sttts) [inline staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go:141]:
```suggestion
		if err == aggregator.ErrAPIServiceNotFound {
			return syncNothing, nil
		}
		return syncRequeueRateLimited, err
```

File: test/e2e/apimachinery/openapiv3.go [hunk 5]
```diff
@@ -97,16 +100,49 @@ var _ = SIGDescribe("OpenAPIV3", func() {
...
+			},
+		}
+		c := openapi3.NewRoot(f.ClientSet.Discovery().OpenAPIV3())
 		gv := schema.GroupVersion{Group: crd.Spec.Group, Version: crd.Spec.Versions[0].Name}
 		_, err = fixtures.CreateNewV1CustomResourceDefinition(crd, apiExtensionClient, dynamicClient)
 		defer func() {
 			err = fixtures.DeleteV1CustomResourceDefinition(crd, apiExtensionClient)
 			framework.ExpectNoError(err, "deleting CustomResourceDefinition")
+			// Poll for the OpenAPI to be updated with the deleted CRD
+			err = wait.PollUntilContextTimeout(ctx, time.Second*1, wait.ForeverTestTimeout, true, func(_ context.Context) (bool, error) {
```
Comment (sttts) [inline test/e2e/apimachinery/openapiv3.go:134]: this is fishy. Why shold we wait for anything? That suggests that these tests are coupled and we have to serialize them.

File: test/e2e/apimachinery/openapiv3.go [hunk 6]
```diff
@@ -138,12 +174,24 @@ var _ = SIGDescribe("OpenAPIV3", func() {
...
 		framework.ExpectNoError(err)
+		c := openapi3.NewRoot(f.ClientSet.Discovery().OpenAPIV3())
+		gv := schema.GroupVersion{Group: samplev1beta1.GroupName, Version: "v1beta1"}
 		names := generateSampleAPIServerObjectNames(f.Namespace.Name)
 		SetUpSampleAPIServer(ctx, f, aggrclient, imageutils.GetE2EImage(imageutils.APIServer), names, samplev1beta1.GroupName, "v1beta1")
-		defer cleanupSampleAPIServer(ctx, f.ClientSet, aggrclient, names, "v1beta1.wardle.example.com")
+		defer func() {
+			cleanupSampleAPIServer(ctx, f.ClientSet, aggrclient, names, "v1beta1.wardle.example.com")
+			// Poll for the OpenAPI to be updated with the deleted aggregated apiserver.
+			err = wait.PollUntilContextTimeout(ctx, time.Second*1, wait.ForeverTestTimeout, true, func(_ context.Context) (bool, error) {
```
Comment (sttts) [inline test/e2e/apimachinery/openapiv3.go:184]: same as above. Waiting here probably means coupling of tests that we rather avoid in the first place.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go [hunk 7]
```diff
@@ -161,7 +164,7 @@ func (s *specProxier) UpdateAPIServiceSpec(apiServiceName string) error {
 func (s *specProxier) updateAPIServiceSpecLocked(apiServiceName string) error {
 	apiService, exists := s.apiServiceInfo[apiServiceName]
 	if !exists {
-		return fmt.Errorf("APIService %s does not exist for update", apiServiceName)
+		return ErrAPIServiceNotFound
```
Comment (sttts) [inline staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go:167]: we exchange a nice error message with context with one without context. Looks suspicious.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go (hunk 4 above)
Comment (sttts) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go:141]: If we care so much about not found, maybe we should make it explicit in the signature? `found bool, err error`

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go [hunk 8]
```diff
@@ -45,7 +45,7 @@ var ErrAPIServiceNotFound = errors.New("resource not found")
 type SpecAggregator interface {
 	AddUpdateAPIService(apiService *v1.APIService, handler http.Handler) error
 	UpdateAPIServiceSpec(apiServiceName string) error
-	RemoveAPIService(apiServiceName string) error
```
Comment (sttts) [inline staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:48]: you introduced a special error. This is becoming part of the interface and needs documentation. Or better: get rid of the error and use `found bool, err error`

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go (hunk 7 above)
Comment (tnqn) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go:167]: This was to be consistent with the handling in openapi v2: https://github.com/kubernetes/kubernetes/blob/1144c85a929bb7a7d30e3343c660286511afb1e3/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go#L189-L192
Should we change them together in this PR or keep it as is to focus on bugfix only?

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go (hunk 4 above)
Comment (tnqn) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go:141]: ditto, this was to be consistent with https://github.com/kubernetes/kubernetes/blob/1144c85a929bb7a7d30e3343c660286511afb1e3/staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/controller.go#L119-L125
Should we change them together or keep it as is?

File: test/e2e/apimachinery/openapiv3.go (hunk 5 above)
Comment (tnqn) [reply test/e2e/apimachinery/openapiv3.go:134]: The new test code is to verify the OpenAPI for the deleted CRD is cleaned up which was not done before. 
The test workflow is:
1. Create the CRD
2. Ensure the OpenAPI schema is present in the response
3. Delete the CRD
4. Ensure the OpenAPI schema is not present in the response (newly added)

Do you suggest to have a separate test to check the 4th? My concern was a new test would be kind of duplicated with the existing one as it also needs to create the CRD first then delete it.

**Comment by tnqn** [comment]
Thanks @sttts for your review. The code was mainly to be consistent with OpenAPI v2, please let me know if we should change them together or focus on bugfix in the PR.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go (hunk 7 above)
Comment (sttts) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/aggregator/aggregator.go:167]: another commit for v2 would be great.

File: test/e2e/apimachinery/openapiv3.go (hunk 5 above)
Comment (sttts) [reply test/e2e/apimachinery/openapiv3.go:134]: Would prefer to have it explicit, not in a defer. Defers are for cleanup.

Comment (tnqn) [reply test/e2e/apimachinery/openapiv3.go:134]: It was not in defer statement and moved to defer as @Jefftree's suggested (https://github.com/kubernetes/kubernetes/pull/120108#discussion_r1303171436) to avoid two calls of cleanup: one is in defer to ensure the CRD is deleted regardless of success or failure, another is part of the test workflow to ensure the OpenAPI is cleaned up after deleting CRD.
cc @Jefftree to see if he has strong opinion about this.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go (hunk 4 above)
Comment (tnqn) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapiv3/controller.go]: updated

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go (hunk 8 above)
Comment (tnqn) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:48]: updated

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go [hunk 9]
```diff
@@ -44,8 +44,10 @@ var ErrAPIServiceNotFound = errors.New("resource not found")
 // known specs including the http etag.
 type SpecAggregator interface {
 	AddUpdateAPIService(apiService *v1.APIService, handler http.Handler) error
-	UpdateAPIServiceSpec(apiServiceName string) error
-	RemoveAPIService(apiServiceName string) error
+	// UpdateAPIServiceSpec updates the APIService. It returns a bool which indicates whether the APIService exists and
+	// the actual error.
+	UpdateAPIServiceSpec(apiServiceName string) (bool, error)
```
Comment (sttts) [inline staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:49]: this is not what I meant. If you make "not found" explicit, it is not an error anymore. So we would return `false, nil`.

File: staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go (hunk 8 above)
Comment (Jefftree) [reply staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/aggregator/aggregator.go:48]: just a note that adding a return parameter will probably make backporting slightly more involved

File: test/e2e/apimachinery/openapiv3.go (hunk 5 above)
Comment (tnqn) [reply test/e2e/apimachinery/openapiv3.go]: Sure, reverted to explicitly test the cleanup in regular workflow

**Comment by sttts** [comment]
/approve

Leaving final lgtm to @Jefftree

**Comment by tnqn** [comment]
> I think we should backport this at least to 1.27

@Jefftree I found there are some conflicts when backporting it to 1.27 due to the change: https://github.com/kubernetes/kubernetes/pull/118212, just want to check with you if it's still worth to backport in this situation. If yes, I would need to add ErrAPIServiceNotFound to 1.27.

There is no conflict with 1.28.

**Comment by Jefftree** [comment]
@tnqn: OpenAPIV3 went GA in 1.27 so I think it'd be worth it. Let me know if you need help with it.
