### PR TITLE
fix: skip isPodWorthRequeuing only when SchedulingGates gates the pod

### LINKED ISSUE #125223: [Flaking Test] integration-master (scheduler_perf tests)
### Which jobs are flaking?

master-blocking:
- integration-master

### Which tests are flaking?

`k8s.io/kubernetes/test/integration/scheduler_perf.scheduler_perf`

### Since when has it been flaking?

The only run that failed on master-blocking was: [5/17/2024, 9:22:18 AM](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1791315518829891584)

But [Triage](https://storage.googleapis.com/k8s-triage/index.html?test=k8s.io%2Fkubernetes%2Ftest%2Fintegration%2Fscheduler_perf.scheduler_perf) shows this test to be failing across different jobs with an extremely high rate. 

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

The complete build log can be found here: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1795650509529419776/build-log.txt

There are numerous errors, highlighting some of them:

```
E0529 03:48:46.793158  117977 controller.go:159] "Unhandled Error" err="unable to sync kubernetes service: Endpoints \"kubernetes\" is invalid: subsets[0].addresses[0].ip: Invalid value: \"127.0.0.1\": may not be in the loopback range (127.0.0.0/8, ::1/128)" logger="UnhandledError"
...
    schedule_one.go:1052: E0529 03:48:37.463675] Error scheduling pod; retrying err="waiting for resource driver" pod="test/test-drac5bhg"
...
E0529 03:09:54.849485   25438 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/metadata/metadatainformer/informer.go:138: Failed to watch *v1.PartialObjectMetadata: failed to list *v1.PartialObjectMetadata: the server could not find the requested resource" logger="UnhandledError"
...
E0529 03:08:16.849871   25438 replica_set.go:560] "Unhandled Error" err="sync \"namespace-1716952096-8804/cassandra\" failed with replicationcontrollers \"cassandra\" not found" logger="UnhandledError"
...
E0529 03:07:37.755211   25438 replica_set.go:236] "Unhandled Error" err="ReplicaSet has no controller: &ReplicaSet{ObjectMeta:{frontend  namespace-1716952054-23531  228ae60e-495d-445c-955c-2b4280009709 3244 2 2024-05-29 03:07:36 +0000 UTC <nil> <nil> map[app:guestbook tier:frontend] map[] [] [] []},Spec:ReplicaSetSpec{Replicas:*2,Selector:&v1.LabelSelector{MatchLabels:map[string]string{app: guestbook,tier: frontend,},MatchExpressions:[]LabelSelectorRequirement{},},Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[app:guestbook tier:frontend] map[] [] [] []} {[] [] [{php-redis gcr.io/google_samples/gb-frontend:v3 [] []  [{ 0 80 TCP }] [] [{GET_HOSTS_FROM dns nil}] {map[] map[cpu:{{100 -3} {<nil>} 100m DecimalSI} memory:{{104857600 0} {<nil>} 100Mi BinarySI}] []} [] <nil> [] [] nil nil nil nil /dev/termination-log File IfNotPresent nil false false false}] [] Always 0xc00442e218 <nil> ClusterFirst map[]   <nil>  false false false <nil> PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,SeccompProfile:nil,AppArmorProfile:nil,} []   nil default-scheduler [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil <nil> [] []}},MinReadySeconds:0,},Status:ReplicaSetStatus{Replicas:3,FullyLabeledReplicas:3,ObservedGeneration:1,ReadyReplicas:0,AvailableReplicas:0,Conditions:[]ReplicaSetCondition{},},}" logger="UnhandledError"
```

### Anything else we need to know?

https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf is 🔴 

### Relevant SIG(s)

/sig scalability
@kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

[This path](https://github.com/kubernetes/kubernetes/blob/c3689b9f8b8c1a1ac2bbc4e3b3cda28d83849ec2/pkg/scheduler/internal/queue/scheduling_queue.go#L1196-L1200) is problematic for PreEnqueue plugins that could change its result by a change in resources apart from Pods. DRA is an example in in-tree (https://github.com/kubernetes/kubernetes/issues/125223#issuecomment-2170470530), and we may have broken more custom PreEnqueue plugins with the same reason.

But, we cannot just remove this path because it's important to keep the scheduling throughput with schedulinggated Pods (https://github.com/kubernetes/kubernetes/issues/124384).
This PR add a check whether the unscheduled Pod is rejected by schedulinggate plugin or not before skipping `isPodWorthRequeuing`

#### Which issue(s) this PR fixes:

Fixes #125223

#### Special notes for your reviewer:

This PR needs to be cherry-picked.

#### Does this PR introduce a user-facing change?

Fixes an in-release regression introduced by https://github.com/kubernetes/kubernetes/pull/124618 during 1.31 cycle

```release-note
Fix a bug that Pods could stuck in the unschedulable pod pool 
if they're rejected by PreEnqueue plugins that could change its result by a change in resources apart from Pods.

DRA plugin is the only plugin that meets the criteria of the bug in in-tree, 
and hence if you have `DynamicResourceAllocation` feature flag enabled, 
your DRA Pods could be affected by this bug.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/hold
To go through an approver's review.

**Comment by pohly** [comment]
One unit test is failing.

**Comment by sanposhiho** [comment]
I'll check the failures by Monday.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 1]
```diff
@@ -1499,13 +1500,21 @@ func TestPriorityQueue_MoveAllToActiveOrBackoffQueueWithQueueingHint(t *testing.
...
 			},
 			expectedQ: unschedulablePods,
 		},
+		{
+			name:    "QueueHintFunction is called when Pod is gated by a plugin other than SchedulingGates",
+			podInfo: setQueuedPodInfoGated(&framework.QueuedPodInfo{PodInfo: mustNewPodInfo(p), UnschedulablePlugins: sets.New("foo")}),
+			hint:    queueHintReturnQueue,
+			// FIXME: This should be backoffQ.
+			// https://github.com/kubernetes/kubernetes/issues/125538
+			expectedQ: activeQ,
```
Comment (sanposhiho) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: Found one minor bug, which can be follow-up.
https://github.com/kubernetes/kubernetes/issues/125538

File: test/integration/scheduler/plugins/plugins_test.go [hunk 2]
```diff
@@ -2686,7 +2687,7 @@ func TestSchedulingGatesPluginEventsToRegister(t *testing.T) {
 		{
 			name:              "preEnqueue plugin with event registered",
 			withEvents:        true,
-			count:             2,
+			count:             3,
```
Comment (sanposhiho) [inline test/integration/scheduler/plugins/plugins_test.go:2690]: This is a correct change -
This test uses a custom PreEnqueue plugin, and thus this PR makes the test case not go through a shortcut.
Actually before https://github.com/kubernetes/kubernetes/pull/124618, the value here was 3.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 3]
```diff
@@ -1518,14 +1527,13 @@ func TestPriorityQueue_MoveAllToActiveOrBackoffQueueWithQueueingHint(t *testing.
 					QueueingHintFn: test.hint,
 				},
 			}
-			test.podInfo.UnschedulablePlugins = sets.New("foo")
```
Comment (sanposhiho) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1521]: This was wrong as each test case sets UnschedulablePlugins (or PendingPlugins) as necessary.

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (kerthcet) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: Let's merge this first https://github.com/kubernetes/kubernetes/pull/124783, no need to worry about this anymore. Can you take a look.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 4]
```diff
@@ -1195,9 +1196,10 @@ func (p *PriorityQueue) movePodsToActiveOrBackoffQueue(logger klog.Logger, podIn
 	for _, pInfo := range podInfoList {
 		// Since there may be many gated pods and they will not move from the
 		// unschedulable pool, we skip calling the expensive isPodWorthRequeueing.
-		if pInfo.Gated {
+		if pInfo.Gated && pInfo.UnschedulablePlugins.Has(names.SchedulingGates) {
```
Comment (kerthcet) [inline pkg/scheduler/internal/queue/scheduling_queue.go:1199]: Seems we're target the optimization for scheduling gates plugin, can we make this more clear like checking the pod.spec.schedulingGates.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (kerthcet) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: I guess this is intended, Pods rejected by preEnqueue shouldn't enter into backoffQ, because semantically the Pod hasn't been scheduled yet. cc @Huang-Wei

**Review by kerthcet — COMMENTED** [review]
I think this is a regression, we need to cherry pick. Then we should make minimal changes here, cleanup could be a follow up. I guess.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: No, it's definitely a bug. 
That behavior, assuming "Pods rejected by preEnqueue shouldn't enter into backoffQ, because semantically the Pod hasn't been scheduled yet", is only correct for the schedulinggate plugin, but not correct for any other PreEnqueue plugins.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 4 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: I prefer the current version; I wouldn't like to make any part of scheduling queue depend on the implementation detail of the scheduling gate plugin.

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (sanposhiho) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: OK, I'll review that one though, can we regard this PR as independent from that one?
I don't think it's necessary to block this PR waiting for your PR. This PR is high-prioritized to resolve master-blocking job failure https://github.com/kubernetes/kubernetes/issues/125223.

**Comment by sanposhiho** [comment]
Agree to cherry-pick; it's breaking a specific scenario of DRA, and also possibly custom PreEnqueue plugins.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (kerthcet) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: That's what I mean is for intended. https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/3521-pod-scheduling-readiness/README.md#implementation

```
A Pod can be moved to activeQ only when all Enqueue plugins returns Success. 
Otherwise, it's moved and parked in the internal unschedulable Pods pool
```

Would like to hear from Wei.

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (kerthcet) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: I'm ok to merge this first, just let you know you don't have to focus on this. 

Maybe we should merge this first if we want to cherry pick.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: Do we say that PreEnqueue plugins, **_in general_**, cannot change their decision once after they allow Pods to go to scheduling cycles? I couldn't find that specification.
So, what could happen, in my understanding, is:
1. A Pod that isn't gated goes to scheduling cycles, which means a Pod is supposed to go through backoff before proceeding to activeQ when it's retried.
2. Something gets changed and a custom PreEnqueue plugin now gates the Pod.
3. Something gets changed again, and a custom PreEnqueue plugin now allows the Pod to get scheduling again.
4. The Pod directly goes to activeQ, without going through backoff.

I know the scheduling gate plugin doesn't cause this because of-
> After creation, each schedulingGate can be removed in arbitrary order, but addition of a new scheduling gate is disallowed.
https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/3521-pod-scheduling-readiness/README.md#notesconstraintscaveats-optional

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (sanposhiho) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: Actually, after taking a look at https://github.com/kubernetes/kubernetes/pull/124783, I now understand your PR wouldn't take so much time to merge :) Let's see anyway.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 4 above)
Comment (gabesaba) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: Is it accurate that we're considering the pod `Gated` if [any of the plugins return unschedulable](https://github.com/kubernetes/kubernetes/blob/ef9965ebc66dafda37800bb04f5e284535bbba10/pkg/scheduler/internal/queue/scheduling_queue.go#L560)? I suppose that it should be true IFF the SchedulingGates plugin returns unschedulable.

Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: The scheduling queue considers a Pod to be `Gated` if any PreEnqueue returns Unschedulable, yes. And, there could be multiple PreEnqueue plugins; actually we have two PreEnqueue plugins (when the DRA feature gate is enabled)

Comment (gabesaba) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: I understand that that is the current behavior, but my question was more: is that the desired future state? From its name, `Gated` seems to refer to `Pod.Spec.SchedulingGates` being set. But the concept of Gated (at least in scheduling queue) is now mixed with any `PreEnqueuePlugin` returning unschedulable. I see how this became to be the state - as the first and only (at the time) `PreEnqueuePlugin` was the `SchedulingGates` plugin - added in the same [commit](https://github.com/kubernetes/kubernetes/pull/113275/commits/0b27f25252d827afe2cac2d9ab67595275315608) which defined the logic of `pInfo.Gated = !p.runPreEnqueuePlugins(...)`

Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: > is that the desired future state?

I agree that `Gated` comes from scheduling gates and may be confusing (For this point, we can rename the field if necessary), but I think the current way of implementing PreEnqueue logic in the scheduling queue is OK with it.

Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: So, whether is your point; we should rename it, or we should use `Gated` only for the scheduling gate plugin and do something another for other PreEnqueue plugins? (or anything else?)

Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: > In this PR, however, we are introducing a potentially expensive operation (set membership) into a performance critical section, rather than just reading a boolean.

So, (leaving the naming issue aside) is your core concern in this PR having `pInfo.UnschedulablePlugins.Has` in this shortcut path from a performance perspective? 

I'm not sure if we could see a visible performance difference between `pInfo.UnschedulablePlugins.Has` (= O(1) map access [internally](https://github.com/kubernetes/kubernetes/blob/fb7bbd2e5df36212ca5133bcbaa46dcdb4d18f0e/staging/src/k8s.io/apimachinery/pkg/util/sets/set.go#L78)) vs `pInfo.SchedulingGated` (= new field to cache a result of schedulinggate plugin).

With a test case https://github.com/kubernetes/kubernetes/pull/125550, I checked the throughput in each case and didn't see a difference actually. (You can try on your machine too.)

<details><summary>results</summary>

**Revert https://github.com/kubernetes/kubernetes/pull/124618**

(In order to ensure the test case could reproduce the degradation you reported in https://github.com/kubernetes/kubernetes/issues/124384.)

```
    {
      "data": {
        "Average": 220.9635550403882,
        "Perc50": 214.9945877262486,
        "Perc90": 262.0829689158846,
        "Perc95": 262.0829689158846,
        "Perc99": 262.0829689158846
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
    {
      "data": {
        "Average": 2371.50060887,
        "Perc50": 2345.0626566416036,
        "Perc90": 4528.77598152425,
        "Perc95": 4824.387990762125,
        "Perc99": 5060.877598152425
      },
      "unit": "ms",
      "labels": {
        "Metric": "scheduler_pod_scheduling_duration_seconds",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```

**Current master** 

sample1:

```
    {
      "data": {
        "Average": 525.6099658687274,
        "Perc50": 525.6099658687274,
        "Perc90": 525.6099658687274,
        "Perc95": 525.6099658687274,
        "Perc99": 525.6099658687274
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
    {
      "data": {
        "Average": 884.6911246259998,
        "Perc50": 904.0471512770139,
        "Perc90": 1923.18407960199,
        "Perc95": 2241.5920398009953,
        "Perc99": 2496.318407960199
      },
      "unit": "ms",
      "labels": {
        "Metric": "scheduler_pod_scheduling_duration_seconds",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```

sample2:

```
    {
      "data": {
        "Average": 571.9668219205608,
        "Perc50": 571.9668219205608,
        "Perc90": 571.9668219205608,
        "Perc95": 571.9668219205608,
        "Perc99": 571.9668219205608
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
    {
      "data": {
        "Average": 961.9552155919993,
        "Perc50": 1011.3989637305698,
        "Perc90": 2061.9455252918287,
        "Perc95": 2310.9727626459144,
        "Perc99": 2510.1945525291826
      },
      "unit": "ms",
      "labels": {
        "Metric": "scheduler_pod_scheduling_duration_seconds",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```

**This PR**

sample1:

```
    {
      "data": {
        "Average": 629.98727425706,
        "Perc50": 629.98727425706,
        "Perc90": 629.98727425706,
        "Perc95": 629.98727425706,
        "Perc99": 629.98727425706
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
    {
      "data": {
        "Average": 838.6084798769984,
        "Perc50": 849.5971978984238,
        "Perc90": 1456.5517241379312,
        "Perc95": 2008.2758620689658,
        "Perc99": 2449.6551724137935
      },
      "unit": "ms",
      "labels": {
        "Metric": "scheduler_pod_scheduling_duration_seconds",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    }
```

sample2:

```
    {
      "data": {
        "Average": 481.7783482353274,
        "Perc50": 481.7783482353274,
        "Perc90": 481.7783482353274,
        "Perc95": 481.7783482353274,
        "Perc99": 481.7783482353274
      },
      "unit": "pods/s",
      "labels": {
        "Metric": "SchedulingThroughput",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
    {
      "data": {
        "Average": 831.9787021770011,
        "Perc50": 832.9241877256318,
        "Perc90": 1427.2566371681417,
        "Perc95": 1993.628318584071,
        "Perc99": 2446.7256637168143
      },
      "unit": "ms",
      "labels": {
        "Metric": "scheduler_pod_scheduling_duration_seconds",
        "Name": "SchedulingGatedPodsImpactsThroughput/5000Nodes/namespace-2",
        "extension_point": "not applicable",
        "plugin": "not applicable",
        "result": "not applicable"
      }
    },
```


</details>

Comment (gabesaba) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: Just reran tests with https://github.com/kubernetes/kubernetes/pull/125504, and got similar results to the ones you posted. Units are average pods/s

base run1: 166.7
base run2: 167.1

#125527 run1: 153.9
#125527 run2: 156.4

Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1199]: Results from a new version of https://github.com/kubernetes/kubernetes/pull/125550:

Revert #124618: 59 pods/s (avg) / 12ms scheduler_scheduling_algorithm_duration_seconds (avg)
master: 149 pods/s (avg) / 4.19 ms scheduler_scheduling_algorithm_duration_seconds (avg)
This PR: 145 pods/s (avg) / 4ms scheduler_scheduling_algorithm_duration_seconds (avg)

Anyways, I think we can say this PR (= `pInfo.UnschedulablePlugins.Has`) wouldn't make any visible degradation from the master branch.

**Comment by pohly** [comment]
You can ignore `pull-kubernetes-scheduler-perf` failures for now. It looks like the run itself is successful, but summarizing it with gotestsum then fails to produce a correct result. I need to look into this a bit more and have an open issue against gotestsum.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 5]
```diff
@@ -1499,13 +1500,21 @@ func TestPriorityQueue_MoveAllToActiveOrBackoffQueueWithQueueingHint(t *testing.
...
 				return framework.Queue, fmt.Errorf("QueueingHintFn should not be called as pod is gated")
 			},
 			expectedQ: unschedulablePods,
 		},
+		{
+			name:    "QueueHintFunction is called when Pod is gated by a plugin other than SchedulingGates",
+			podInfo: setQueuedPodInfoGated(&framework.QueuedPodInfo{PodInfo: mustNewPodInfo(p), UnschedulablePlugins: sets.New("foo")}),
+			hint:    queueHintReturnQueue,
+			// FIXME: This should be backoffQ.
+			// https://github.com/kubernetes/kubernetes/issues/125538
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:1515]: I'd remove this comment, as it potentially depends on whether the Pod went through the scheduling cycle.

Or you can leave it as a TODO, instead of FIXME.

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (alculquicondor) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: #124783 should not be cherry-picked, to avoid any unforeseen problems.

Now this change is very confusing, because the test and comment refer specifically to SchedulingGates.
Let's change those.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 5 above)
Comment (kerthcet) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1515]: Prefer to remove this, we have another issue for tracking.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 3 above)
Comment (kerthcet) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1521]: If possible, these can also be a follow up to avoid potential code conflicts, I mean we 're intent to cherry-pick, right?

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (kerthcet) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1516]: I don't know if we have such case, but if a pod is gated again, it means it's not ready, maybe it should restart the scheduling lifecycle.. my two cents. Let's track this under your issue then.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 3 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1521]: Good point.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 5 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1515]: I'll just remove it for now.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 3 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:1521]: Ah, wait. But, actually we have to remove it in this PR to test a scenario when test.podInfo.UnschedulablePlugins includes the scheduling gate (`"QueueHintFunction is not called when Pod is gated by SchedulingGates plugin"`).

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (sanposhiho) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: @alculquicondor 
Sorry, so what are you expecting me to change? If we don't cherry-pick #124783, we have to change this number to make the test case pass, right?

Comment (alculquicondor) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: yes, change the number, but also change the name of the test and corresponding comment.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 4 above)
Comment (sanposhiho) [reply pkg/scheduler/internal/queue/scheduling_queue.go:1205]: updated the comment.

File: test/integration/scheduler/plugins/plugins_test.go (hunk 2 above)
Comment (sanposhiho) [reply test/integration/scheduler/plugins/plugins_test.go:2690]: Now I got it, updated the test name and the comment on top of that.

**Comment by sanposhiho** [comment]
I believe all comments that require my fix are addressed.

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve
/hold
I think there is a presubmit for perf-tests that we can run.

**Comment by alculquicondor** [comment]
uhm... can't tell if the test passed at all. There is nothing useful in the artifacts.

See https://github.com/gotestyourself/gotestsum/issues/413 for the issue that @pohly opened related to this.

**Comment by kerthcet** [comment]
> Maybe we should merge this first if we want to cherry pick.

What I mean to cherry pick is this one, not https://github.com/kubernetes/kubernetes/pull/124783, because the https://github.com/kubernetes/kubernetes/pull/124618 cherry-picked to 1.27 ~ 1.30, which is a regression I think. Before, it's a performance issue, now it's a bug.
