### PR TITLE
Do not report error when deleting an attached volume

### LINKED ISSUE #31511: Race condition during cinder volume detach and delete
# Problem

Using a dynamic provisioned cinder volume, when the PVC is deleted, PV entered **FAILED** status. It looks like volume detaching and deleting happened at the same time. After a while, I found my PV and volume eventually deleted. I feel obligated to post the issue I have met here.
# Version

```
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3.61+f73c68440408fa-dirty", GitCommit:"f73c68440408fa507234c28dbb4b4d48735df56e", GitTreeState:"dirty", BuildDate:"2016-08-26T08:32:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3.61+f73c68440408fa-dirty", GitCommit:"f73c68440408fa507234c28dbb4b4d48735df56e", GitTreeState:"dirty", BuildDate:"2016-08-26T08:32:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```
# kube-controller-manager.log

```
I0826 06:03:36.681789    1146 controller.go:450] volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" is released and reclaim policy "Delete" will be executed
I0826 06:03:36.684934    1146 controller.go:670] volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" entered phase "Released"
I0826 06:03:36.686426    1146 controller.go:1131] isVolumeReleased[pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be]: volume is released
E0826 06:03:36.840736    1146 openstack_volumes.go:195] Cannot delete volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5: Expected HTTP response code [202 204] when accessing [DELETE http://10.8.188.11:8776/v1/fba689ab76d44366ac463280bb51bfd5/volumes/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5], but got 400 instead
{"badRequest": {"message": "Volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5 is still attached, detach volume first.", "code": 400}}
I0826 06:03:36.840782    1146 cinder_util.go:127] Error deleting cinder volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5: Expected HTTP response code [202 204] when accessing [DELETE http://10.8.188.11:8776/v1/fba689ab76d44366ac463280bb51bfd5/volumes/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5], but got 400 instead
{"badRequest": {"message": "Volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5 is still attached, detach volume first.", "code": 400}}
I0826 06:03:36.840800    1146 controller.go:1069] deletion of volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" failed: Delete of volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" failed: Expected HTTP response code [202 204] when accessing [DELETE http://10.8.188.11:8776/v1/fba689ab76d44366ac463280bb51bfd5/volumes/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5], but got 400 instead
{"badRequest": {"message": "Volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5 is still attached, detach volume first.", "code": 400}}
I0826 06:03:36.843695    1146 controller.go:670] volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" entered phase "Failed"
I0826 06:03:36.843713    1146 controller.go:692] volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" changed status to "Failed": Delete of volume "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be" failed: Expected HTTP response code [202 204] when accessing [DELETE http://10.8.188.11:8776/v1/fba689ab76d44366ac463280bb51bfd5/volumes/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5], but got 400 instead
{"badRequest": {"message": "Volume 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5 is still attached, detach volume first.", "code": 400}}
I0826 06:03:39.198523    1146 reconciler.go:115] Started DetachVolume for volume "kubernetes.io/cinder/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5" from node "jhoukube"
I0826 06:03:39.200263    1146 operation_executor.go:633] Verified volume is safe to detach for volume "kubernetes.io/cinder/06c4c4fd-a36e-49df-88f6-b4f93e32d0d5" (spec.Name: "pvc-94e36100-6b71-11e6-8eda-fa163ee4c2be") from node "jhoukube".
I0826 06:03:39.258935    1146 openstack_instances.go:78] Found 26 compute flavors
I0826 06:03:39.258949    1146 openstack_instances.go:79] Claiming to support Instances
I0826 06:03:41.263209    1146 openstack_volumes.go:92] Successfully detached volume: 06c4c4fd-a36e-49df-88f6-b4f93e32d0d5 from compute: c649e11e-4bed-4c41-bc0b-fc60517a8fca
I0826 06:03:41.263225    1146 attacher.go:240] detatached volume "06c4c4fd-a36e-49df-88f6-b4f93e32d0d5" from instance "c649e11e-4bed-4c41-bc0b-fc60517a8fca"
```

### PR DESCRIPTION
**Pull request by jsafrane**
Persistent volume controller should not send warning events to a PV and mark the PV as failed when the volume is still attached.

This happens when a user quickly deletes a pod and associated PVC - PV is slowly detaching, while the PVC is already deleted and the PV enters Failed phase.

`Deleter.Deleter` can now return `tryAgainError`, which is sent as INFO to the PV to let the user know we did not forget to delete the PV, however the PV stays in Released state. The controller tries again in the next sync (15 seconds by default).

Fixes #31511

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31978)

### CODE REVIEW

**Comment by jsafrane** [comment]
cc @kubernetes/sig-storage

**Comment by thockin** [comment]
Do we want this in 1.4 (maybe 1.4.1) ?

File: pkg/controller/volume/persistentvolume/controller.go [hunk 1]
```diff
@@ -1067,11 +1067,20 @@ func (ctrl *PersistentVolumeController) deleteVolumeOperation(arg interface{}) {
 	if err = ctrl.doDeleteVolume(volume); err != nil {
 		// Delete failed, update the volume and emit an event.
 		glog.V(3).Infof("deletion of volume %q failed: %v", volume.Name, err)
-		if _, err = ctrl.updateVolumePhaseWithEvent(volume, api.VolumeFailed, api.EventTypeWarning, "VolumeFailedDelete", err.Error()); err != nil {
-			glog.V(4).Infof("deleteVolumeOperation [%s]: failed to mark volume as failed: %v", volume.Name, err)
-			// Save failed, retry on the next deletion attempt
-			return
+		if vol.IsTryAgain(err) {
```
Comment (saad-ali) [inline pkg/controller/volume/persistentvolume/controller.go]: How frequent is the retry? Is it worth doing exponential backoff?

File: pkg/controller/volume/persistentvolume/controller.go [hunk 2]
```diff
@@ -1172,7 +1181,7 @@ func (ctrl *PersistentVolumeController) doDeleteVolume(volume *api.PersistentVol
 
 	if err = deleter.Delete(); err != nil {
 		// Deleter failed
-		return fmt.Errorf("Delete of volume %q failed: %v", volume.Name, err)
+		return err
```
Comment (saad-ali) [inline pkg/controller/volume/persistentvolume/controller.go]: Why remove the details of the volume from the error message?

File: pkg/volume/volume.go [hunk 3]
```diff
@@ -171,6 +177,29 @@ type Detacher interface {
 	UnmountDevice(deviceMountPath string) error
 }
 
+// NewTryAgainError returns a new instance of TryAgainError error.
+func NewTryAgainError(message string) error {
```
Comment (saad-ali) [inline pkg/volume/volume.go]: nit: I'm going to be pedantic about naming here--errors should describe what happened, not what the handlers should do. Consumers that handle the error can decide what to do based on what the error was.

Comment (saad-ali) [inline pkg/volume/volume.go]: To be more concrete, I would have the various plugins return a common `DeletedVolumeInUse` error in this case. And then have the controller implement retry in response to that error.

File: pkg/cloudprovider/providers/openstack/openstack_volumes.go [hunk 4]
```diff
@@ -182,6 +184,14 @@ func (os *OpenStack) GetDevicePath(diskId string) string {
 }
 
 func (os *OpenStack) DeleteVolume(volumeName string) error {
+	used, err := os.diskIsUsed(volumeName)
+	if err != nil {
+		return err
+	}
+	if used {
+		return volume.NewTryAgainError("Cannot delete the volume, it's still attached to a node")
```
Comment (saad-ali) [inline pkg/cloudprovider/providers/openstack/openstack_volumes.go]: Put volume name in the error.

File: pkg/controller/volume/persistentvolume/controller.go (hunk 1 above)
Comment (jsafrane) [inline pkg/controller/volume/persistentvolume/controller.go]: Every controller sync, which is 15 seconds by default. And it does not start new delete until an old one (on the same PV) returns.

File: pkg/controller/volume/persistentvolume/controller.go (hunk 2 above)
Comment (jsafrane) [inline pkg/controller/volume/persistentvolume/controller.go]: Because it would replace `deletedVolumeInUseError` with a generic one. The error message is sent to the PV as event (=volume name does not need to be logged there) and in logs there is "deletion of volume %q failed: %v"" at https://github.com/jsafrane/kubernetes/blob/master/pkg/controller/volume/persistentvolume/controller.go#L1069

File: pkg/volume/volume.go (hunk 3 above)
Comment (jsafrane) [inline pkg/volume/volume.go]: Renamed to `deletedVolumeInUseError`.

File: pkg/cloudprovider/providers/openstack/openstack_volumes.go (hunk 4 above)
Comment (jsafrane) [inline pkg/cloudprovider/providers/openstack/openstack_volumes.go]: volume name added

**Comment by jsafrane** [comment]
rebased

**Comment by jsafrane** [comment]
@k8s-bot: test this issue: #32772

**Comment by jsafrane** [comment]
@k8s-bot: test this issue: #32772

**Comment by jsafrane** [comment]
@k8s-bot: unit test this issue: #32772

**Comment by jsafrane** [comment]
@k8s-bot test this issue: #32772

**Comment by gnufied** [comment]
I am shadowing this review. lgtm!

**Comment by saad-ali** [comment]
LGTM
