### PR TITLE
csi: add nodeExpandSecret support for CSI client & add unit test

### LINKED ISSUE #95367: Pass secret in NodeExpansion Call for the CSI driver
In different use cases we need "secret" passed to the CSI driver to perform NodeExpansion which is missing atm .  One of the very visible use case is that, the expansion on LUKS enabled device, which needs the passphrase in order to resize the device on the node.

One other use case is that, at times we need to check the actual size of the image ( for ex: RBD image size in Ceph Cluster) before proceeding on FS resize to avoid false positive returns on fs resize operation. For that we have to connect to the backend cluster which need secret in the request.

Reference#
CSI spec issue # https://github.com/container-storage-interface/spec/issues/445
CSI spec PR # https://github.com/container-storage-interface/spec/pull/457 

**What happened**:

**What you expected to happen**:

CSI plugin/driver get `NodeExpandSecret` which is same as `ControllerExpandSecret`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by zhucan**
CSI spec 1.5 enhanced the spec to add optional secrets field to
NodeExpandVolumeRequest. This commit adds NodeExpandSecret to the
CSI PV source and also derive the expansion secret in csiclient to
send it out as part of the nodeexpand request.

#### What type of PR is this?
/kind feature

Optionally add one or more of the following kinds if applicable:
/kind api-change

#### Which issue(s) this PR fixes:

Fixes #95367 

#### Does this PR introduce a user-facing change?

```release-note
This release add support for NodeExpandSecret for CSI driver client which enables the CSI drivers to make use of this secret while performing node expansion operation based on the user request. Previously there was no secret  provided as part of the nodeexpansion call, thus CSI drivers were not make use of the same while expanding the volume at node side. 
```
KEP reference：https://github.com/kubernetes/enhancements/pull/3173/

### CODE REVIEW

**Comment by humblec** [comment]
This PR has the changes from https://github.com/kubernetes/kubernetes/pull/105958 and good for review. We have also tested the workflow of hostpath driver with the changes in external provisioner and its working . Please review with the target release of 1.23

File: pkg/apis/core/types.go [hunk 1]
```diff
@@ -1680,6 +1680,15 @@ type CSIPersistentVolumeSource struct {
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference
+
+	// NodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an alpha field and requires enabling ExpandCSIVolumes feature gate.
```
Comment (jsafrane) [inline pkg/apis/core/types.go:1687]: `ExpandCSIVolumes` is beta, not alpha.

**Comment by jsafrane** [comment]
You also need to drop `NodeExpandSecretRef` from a PV when the feature is disabled, like for `ControllerExpandSecretRef`: https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/pkg/api/persistentvolume/util.go#L27-L33

Actually, please check where ExpandCSIVolumes feature is used, there may be more places like this.

File: pkg/apis/core/types.go (hunk 1 above)
Comment (zhucan) [reply pkg/apis/core/types.go]: done, both modify the ControllerExpandSecretRef

**Comment by zhucan** [comment]
> You also need to drop `NodeExpandSecretRef` from a PV when the feature is disabled, like for `ControllerExpandSecretRef`:
> 
> https://github.com/kubernetes/kubernetes/blob/76694983a1c50532206504e2b5e2b9767851354e/pkg/api/persistentvolume/util.go#L27-L33
> 
> Actually, please check where ExpandCSIVolumes feature is used, there may be more places like this.

done

File: pkg/api/persistentvolume/util.go [hunk 2]
```diff
@@ -28,6 +28,7 @@ func DropDisabledFields(pvSpec *api.PersistentVolumeSpec, oldPVSpec *api.Persist
 	if !utilfeature.DefaultFeatureGate.Enabled(features.ExpandCSIVolumes) && !hasExpansionSecrets(oldPVSpec) {
 		if pvSpec.CSI != nil {
 			pvSpec.CSI.ControllerExpandSecretRef = nil
+			pvSpec.CSI.NodeExpandSecretRef = nil
```
Comment (jsafrane) [inline pkg/api/persistentvolume/util.go:31]: Please update the unit tests too.

File: pkg/api/persistentvolume/util.go [hunk 3]
```diff
@@ -28,6 +28,7 @@ func DropDisabledFields(pvSpec *api.PersistentVolumeSpec, oldPVSpec *api.Persist
 	if !utilfeature.DefaultFeatureGate.Enabled(features.ExpandCSIVolumes) && !hasExpansionSecrets(oldPVSpec) {
```
Comment (jsafrane) [inline pkg/api/persistentvolume/util.go:28]: With this code, if there is ControllerExpandSecretRef  the old object and does not have `NodeExpandSecretRef`, the code does not clear `NodeExpandSecretRef` in the new object. Which is IMO wrong.

I think you should completely split `ControllerExpandSecretRef` and `NodeExpandSecretRef` handling, i.e. have `hasControllerExpansionSecrets()` and `hasNodeExpansionSecrets()` as separate functions and separate `if` here.

File: pkg/api/persistentvolume/util.go (hunk 2 above)
Comment (zhucan) [reply pkg/api/persistentvolume/util.go]: added

File: pkg/api/persistentvolume/util.go (hunk 3 above)
Comment (zhucan) [reply pkg/api/persistentvolume/util.go]: good suggestion

File: pkg/apis/core/types.go [hunk 4]
```diff
@@ -1675,11 +1675,20 @@ type CSIPersistentVolumeSource struct {
...
+	// This is an beta field and requires enabling ExpandCSIVolumes feature gate.
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference
+
+	// NodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an beta field and requires enabling ExpandCSIVolumes feature gate.
```
Comment (jsafrane) [inline pkg/apis/core/types.go:1687]: Heads up for an API reviewer: a new field goes straight to beta. From storage point of view, the field is needed and useful and it's basically a copy of well established `ControllerExpandSecretRef`.

**Comment by jsafrane** [comment]
/lgtm
from storage perspective. It needs API review. Reading the [requirements](https://github.com/kubernetes/community/blob/master/sig-architecture/api-review-process.md#mechanics), you should update [CSI expansion KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/556-csi-volume-resizing/README.md#supporting-per-pvc-secret-refs), it still says that NodeExpand does not accept secrets.

**Comment by smarterclayton** [comment]
Can you link the KEP in here (maybe I just missed it) so I can review that?

**Comment by jsafrane** [comment]
@smarterclayton 
full KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/556-csi-volume-resizing/README.md
changes for the node secrets: https://github.com/kubernetes/enhancements/pull/3038

File: pkg/apis/core/types.go (hunk 4 above)
Comment (msau42) [reply pkg/apis/core/types.go:1687]: We may need to add the field in alpha first. Otherwise a n-1 controller could drop the field on an update.

**Comment by humblec** [comment]
@zhucan can you please rebase to master?

**Comment by zhucan** [comment]
> @zhucan can you please rebase to master?

done

File: staging/src/k8s.io/api/core/v1/types.go [hunk 5]
```diff
@@ -1804,11 +1804,20 @@ type CSIPersistentVolumeSource struct {
...
 	// sensitive information to pass to the CSI driver to complete the CSI
 	// ControllerExpandVolume call.
-	// This is an alpha field and requires enabling ExpandCSIVolumes feature gate.
+	// This is an beta field and requires enabling ExpandCSIVolumes feature gate.
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference `json:"controllerExpandSecretRef,omitempty" protobuf:"bytes,9,opt,name=controllerExpandSecretRef"`
+
+	// NodeExpandSecretRef is a reference to the secret object containing
```
Comment (smarterclayton) [inline staging/src/k8s.io/api/core/v1/types.go:1813]: None of the field names in godoc in this struct are correct - they should all be `camelCase`, not `CamelCase`.  Can you open a follow up to make that change (not critical for this PR).

File: pkg/apis/core/types.go (hunk 4 above)
Comment (smarterclayton) [reply pkg/apis/core/types.go:1728]: Yes, during an upgrade to "release with this" if someone set the field right away (because it was on by default) then it would get cleared if someone hit the not yet upgraded server.

Is there a justification for "straight to beta" recorded in the KEP discussion or other format?

File: staging/src/k8s.io/api/core/v1/types.go (hunk 5 above)
Comment (humblec) [reply staging/src/k8s.io/api/core/v1/types.go:1813]: sure, will track it with a follow up change. thanks!

File: pkg/apis/core/types.go (hunk 4 above)
Comment (smarterclayton) [reply pkg/apis/core/types.go:1728]: I would prefer not to create the exception here to allow a field to go to beta ungated unless there is a decision by other api reviewers recorded already to do so.  It's unusual enough to give me pause, and michelle is right that it will have unusual implications for upgrades.

Comment (humblec) [reply pkg/apis/core/types.go:1728]: Thanks all for the review and thoughts. As we are in a conclusion that this has to go through the feature gate starting with Alpha, this has to be tracked for next release.

**Comment by humblec** [comment]
This PR followed the model of controllerExpandSecretRef and no separate feature gate was introduced. However based on the review and also based on the community  discussion, the decision is to put this under feature gate and take it from alpha from next release.  Thanks all ! will refresh the PR and continue on this .

**Comment by reylejano** [comment]
/milestone clear
Release Managers are cutting 1.23.0-rc.0 and creating the `release-1.23` branch

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by humblec** [comment]
> Is this PR still needed, please rebase if so (or we can close it?)

we will be revamping this PR for a KEP @dims , can we take a decision to close or rebase in a few days?

**Comment by humblec** [comment]
KEP #3107 track the enhancement requested here as `alpha` feature while `CSINodeExpandSecret` feature flag is enabled .

This PR will be updated soon to enable the feature flag as discussed in the KEP. 

Cc @zhucan

**Comment by humblec** [comment]
@gnufied @msau42 @xing-yang @jsafrane this is an updated version of the PR with feature flag in place, could you please take a look at this so that,  API review can be requested accordingly ?

**Comment by xing-yang** [comment]
@zhucan Can you resolve the merge conflict?

File: staging/src/k8s.io/api/core/v1/types.go (hunk 5 above)
Comment (xing-yang) [reply staging/src/k8s.io/api/core/v1/types.go:1810]: @zhucan Can you please address this comment?  Change "NodeExpandSecretRef" to "nodeExpandSecretRef".

**Comment by zhucan** [comment]
> @zhucan Can you resolve the merge conflict?

ok

File: pkg/api/v1/persistentvolume/util_test.go [hunk 6]
```diff
@@ -149,6 +149,13 @@ func TestPVSecrets(t *testing.T) {
 					ControllerExpandSecretRef: &corev1.SecretReference{
 						Name:      "Spec.PersistentVolumeSource.CSI.ControllerExpandSecretRef",
 						Namespace: "csi"}}}}},
+		{Spec: corev1.PersistentVolumeSpec{
+			ClaimRef: &corev1.ObjectReference{Namespace: "claimrefns", Name: "claimrefname"},
+			PersistentVolumeSource: corev1.PersistentVolumeSource{
+				CSI: &corev1.CSIPersistentVolumeSource{
+					ControllerExpandSecretRef: &corev1.SecretReference{
```
Comment (xing-yang) [inline pkg/api/v1/persistentvolume/util_test.go:156]: Should be NodeExpandSecretRef.

**Comment by msau42** [comment]
Can you put the generated files into a separate commit? That will make it easier to review

File: pkg/api/persistentvolume/util.go [hunk 7]
```diff
@@ -25,14 +25,19 @@ import (
...
 func DropDisabledFields(pvSpec *api.PersistentVolumeSpec, oldPVSpec *api.PersistentVolumeSpec) {
-	if !utilfeature.DefaultFeatureGate.Enabled(features.ExpandCSIVolumes) && !hasExpansionSecrets(oldPVSpec) {
+	if !utilfeature.DefaultFeatureGate.Enabled(features.ExpandCSIVolumes) {
 		if pvSpec.CSI != nil {
-			pvSpec.CSI.ControllerExpandSecretRef = nil
+			if !hasControllerExpansionSecrets(oldPVSpec) {
+				pvSpec.CSI.ControllerExpandSecretRef = nil
+			}
+			if !hasNodeExpansionSecrets(oldPVSpec) {
+				pvSpec.CSI.NodeExpandSecretRef = nil
```
Comment (msau42) [inline pkg/api/persistentvolume/util.go:34]: This field check should be toggled by CSINodeExpandSecret feature gate

File: pkg/apis/core/types.go [hunk 8]
```diff
@@ -1716,11 +1716,20 @@ type CSIPersistentVolumeSource struct {
...
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference
+
+	// NodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an alpha field and requires enabling CSINodeExpand feature gate.
```
Comment (msau42) [inline pkg/apis/core/types.go:1728]: CSINodeExpandSecret feature gate

File: staging/src/k8s.io/api/core/v1/types.go [hunk 9]
```diff
@@ -1801,11 +1801,20 @@ type CSIPersistentVolumeSource struct {
...
+	// This is an beta field and requires enabling ExpandCSIVolumes feature gate.
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference `json:"controllerExpandSecretRef,omitempty" protobuf:"bytes,9,opt,name=controllerExpandSecretRef"`
+
+	// nodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an alpha field and requires enabling CSINodeExpand feature gate.
```
Comment (msau42) [inline staging/src/k8s.io/api/core/v1/types.go:1813]: update CSINodeExpandSecret feature gate here too

File: pkg/volume/csi/expander.go [hunk 10]
```diff
@@ -86,6 +86,15 @@ func (c *csiPlugin) nodeExpandWithClient(
 	if pv == nil {
 		return false, fmt.Errorf("Expander.NodeExpand failed to find associated PersistentVolume for plugin %s", c.GetPluginName())
 	}
+	nodeExpandSecrets := map[string]string{}
+	expandClient := c.host.GetKubeClient()
+	if csiSource.NodeExpandSecretRef != nil {
```
Comment (msau42) [inline pkg/volume/csi/expander.go:91]: I think we need to check the feature gate here too

File: pkg/apis/core/validation/validation.go [hunk 11]
```diff
@@ -1598,6 +1598,18 @@ func validateCSIPersistentVolumeSource(csi *core.CSIPersistentVolumeSource, fldP
 			allErrs = append(allErrs, ValidateDNS1123Label(csi.NodePublishSecretRef.Namespace, fldPath.Child("namespace"))...)
 		}
 	}
+	if csi.NodeExpandSecretRef != nil {
```
Comment (msau42) [inline pkg/apis/core/validation/validation.go:1601]: Add unit test

File: pkg/apis/core/types.go (hunk 8 above)
Comment (zhucan) [reply pkg/apis/core/types.go:1728]: Your means update the "NodeExpandSecretRef" to  CSINodeExpandSecret? @msau42

File: pkg/volume/csi/expander.go (hunk 10 above)
Comment (zhucan) [reply pkg/volume/csi/expander.go:91]: your means we should check the  CSINodeExpandSecret feature gate not  NodeExpandSecretRef?

File: pkg/apis/core/types.go (hunk 8 above)
Comment (msau42) [reply pkg/apis/core/types.go:1728]: The feature gate name in the comment is not correct. It should be "CSINodeExpandSecret"

File: pkg/volume/csi/expander.go (hunk 10 above)
Comment (msau42) [reply pkg/volume/csi/expander.go:91]: In addition to checking `NodeExpandSecretRef`, also check the feature gate.

File: pkg/api/persistentvolume/util.go (hunk 7 above)
Comment (zhucan) [reply pkg/api/persistentvolume/util.go]: I had remove this change, I think it's not needed.

**Comment by zhucan** [comment]
> /label api-review



> Can you put the generated files into a separate commit? That will make it easier to review

done

**Comment by zhucan** [comment]
> Can you put the generated files into a separate commit? That will make it easier to review

done

File: pkg/api/v1/persistentvolume/util.go [hunk 12]
```diff
@@ -147,6 +147,11 @@ func VisitPVSecretNames(pv *corev1.PersistentVolume, visitor Visitor) bool {
 				return false
 			}
 		}
+		if source.CSI.NodeExpandSecretRef != nil {
```
Comment (gnufied) [inline pkg/api/v1/persistentvolume/util.go:150]: Don't we need something in `DropDisabledFields` function of pv type, so as if feature is disabled and users try to set it, it gets dropped?

File: pkg/volume/csi/expander.go [hunk 13]
```diff
@@ -95,6 +106,7 @@ func (c *csiPlugin) nodeExpandWithClient(
 		fsType:            csiSource.FSType,
 		accessMode:        api.ReadWriteOnce,
 		mountOptions:      pv.Spec.MountOptions,
+		secrets:           nodeExpandSecrets,
 	}
```
Comment (gnufied) [inline pkg/volume/csi/expander.go:110]: ideally we should have some tests for it.

File: pkg/api/v1/persistentvolume/util.go (hunk 12 above)
Comment (zhucan) [reply pkg/api/v1/persistentvolume/util.go:150]: No needed,  if the feature-gates is disabled, we don't pass it to external-provisioner.

Comment (gnufied) [reply pkg/api/v1/persistentvolume/util.go:150]: Not sure I understand. Regardless of what we do in external-provisioner, we need to drop the field if feature gate is not enabled. We carried similar logic for every other field while feature was in alpha.

Comment (gnufied) [reply pkg/api/v1/persistentvolume/util.go:150]: See examples of other alpha fields being handled - https://github.com/kubernetes/kubernetes/commit/2c1b74376691cacf7b56904fe696df45753a8f99

**Comment by gnufied** [comment]
@zhucan @humblec looks like the PR needs rebase?

**Review by msau42 — COMMENTED** [review]
/lgtm
/approve

I have some minor nits but can be followed up later.

**Comment by humblec** [comment]
> @zhucan @humblec looks like the PR needs rebase?

Sure, will rebase.. thanks.

**Comment by humblec** [comment]
@msau42 the rebase took away `lgtm` .. could you please bring back..

**Comment by humblec** [comment]
Cc @smarterclayton

File: pkg/features/kube_features.go [hunk 14]
```diff
@@ -1004,5 +1011,6 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 	genericfeatures.ServerSideFieldValidation:           {Default: true, PreRelease: featuregate.Beta},
 	// features that enable backwards compatibility but are scheduled to be removed
 	// ...
-	HPAScaleToZero: {Default: false, PreRelease: featuregate.Alpha},
+	HPAScaleToZero:      {Default: false, PreRelease: featuregate.Alpha},
+	CSINodeExpandSecret: {Default: false, PreRelease: featuregate.Alpha},
```
[the remark this answers is not in the document]
Comment (zhucan) [reply pkg/features/kube_features.go]: done

File: staging/src/k8s.io/api/core/v1/types.go [hunk 15]
```diff
@@ -1800,11 +1800,20 @@ type CSIPersistentVolumeSource struct {
...
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference `json:"controllerExpandSecretRef,omitempty" protobuf:"bytes,9,opt,name=controllerExpandSecretRef"`
+
+	// nodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an alpha field and requires enabling CSINodeExpandSecret feature gate.
+	// This field is optional, and may be empty if no secret is required. If the
```
[the remark this answers is not in the document]
Comment (smarterclayton) [reply staging/src/k8s.io/api/core/v1/types.go:1813]: (I realize we're just copying the other fields, but it doesn't make sense to me as an API user what you mean by empty, so I'm trying to understand what it means so we can decide on a follow up)

[the remark this answers is not in the document]
Comment (msau42) [reply staging/src/k8s.io/api/core/v1/types.go:1813]: probably should be "nil"

[the remark this answers is not in the document]
Comment (zhucan) [reply staging/src/k8s.io/api/core/v1/types.go]: done

[the remark this answers is not in the document]
Comment (humblec) [reply staging/src/k8s.io/api/core/v1/types.go]: @smarterclayton addressed this too.. ptal.. thanks !

**Comment by humblec** [comment]
PR had to be rebased which took away lgtm... 

Cc @msau42 @smarterclayton @gnufied

File: staging/src/k8s.io/api/core/v1/types.go [hunk 16]
```diff
@@ -1800,11 +1800,20 @@ type CSIPersistentVolumeSource struct {
...
 	// This field is optional, and may be empty if no secret is required. If the
 	// secret object contains more than one secret, all secrets are passed.
 	// +optional
 	ControllerExpandSecretRef *SecretReference `json:"controllerExpandSecretRef,omitempty" protobuf:"bytes,9,opt,name=controllerExpandSecretRef"`
+
+	// nodeExpandSecretRef is a reference to the secret object containing
+	// sensitive information to pass to the CSI driver to complete the CSI
+	// NodeExpandVolume call.
+	// This is an alpha field and requires enabling CSINodeExpandSecret feature gate.
+	// This field is optional, and may be nil if no secret is required. If the
```
Comment (smarterclayton) [inline staging/src/k8s.io/api/core/v1/types.go:1813]: Sorry for this - but we wouldn't use `nil` because this apidoc is intended for JSON users (I should have clarified).  Now that I think you've answered the question of "the field is absent / omitted" I'd suggest this sentence (And all the others in this file, which can be done later) as:

> This field is optional, may be omitted if no secret is required.

Comment (humblec) [reply staging/src/k8s.io/api/core/v1/types.go:1813]: @smarterclayton sure,  will address this  in a follow up PR . Thanks!

Comment (zhucan) [reply staging/src/k8s.io/api/core/v1/types.go]: done @humblec @smarterclayton

Comment (humblec) [reply staging/src/k8s.io/api/core/v1/types.go]: Awesome. thanks @zhucan :+1:

**Comment by smarterclayton** [comment]
/approve

for api changes and field gate
