### PR TITLE
Fix kubectl flake: Simple pod should return command exit codes

### LINKED ISSUE #98854: [Flaky Test] [[sig-cli] Kubectl client Simple pod should return command exit codes
**Which jobs are flaking**:  `ci-kubernetes-kind-ipv6-e2e-parallel`

**Which test(s) are flaking**: 
- `Kubectl client Simple pod should return command exit codes`
- `Kubectl client Simple pod should support inline execution and attach`

**Testgrid link**:  https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master-parallel&include-filter-by-regex=%20Kubectl%20client%20Simple%20pod%20should%20return%20command%20exit%20codes

**Reason for failure**:

```
• Failure [83.784 seconds]
[sig-cli] Kubectl client
test/e2e/kubectl/framework.go:23
  Simple pod
  test/e2e/kubectl/kubectl.go:382
    should return command exit codes [It]
    test/e2e/kubectl/kubectl.go:502
    Feb  7 16:23:48.033: Unexpected error:
      
        <exec.CodeExitError>: {
            Err: {
                s: "error running /home/prow/go/src/k8s.io/kubernetes/bazel-out/k8-fastbuild-ST-5e46445d989a/bin/cmd/kubectl/kubectl_/kubectl --server=https://[::1]:37209 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-7185 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:\nCommand stdout:\n\nstderr:\nerror: timed out waiting for the condition\n\nerror:\nexit status 1",
            },
            Code: 1,
        }
        error running /home/prow/go/src/k8s.io/kubernetes/bazel-out/k8-fastbuild-ST-5e46445d989a/bin/cmd/kubectl/kubectl_/kubectl --server=https://[::1]:37209 --kubeconfig=/root/.kube/kind-test-config --namespace=kubectl-7185 run -i --image=docker.io/library/busybox:1.29 --restart=Never success -- /bin/sh -c exit 0:
        Command stdout:
        
        stderr:
        error: timed out waiting for the condition
        
        error:
        exit status 1
    occurred
skipped 55993 lines unfold_more
[Fail] [sig-cli] Kubectl client Simple pod [It] should return command exit codes 
test/e2e/kubectl/kubectl.go:515
```

**Anything else we need to know**:

> NOTE: 7 clusters of 86 failures (8 in last day) out of 146571 builds from **_1/23/2021_**

Test Owner: **yifan-gu** -> https://github.com/kubernetes-csi/driver-registrar/blob/master/vendor/k8s.io/kubernetes/test/test_owners.csv#L216

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Kubectl%20client%20Simple%20pod%20should%20return%20command%20exit%20codes

Spyglass failures: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1358448260980674560

/sig cli

### PR DESCRIPTION
**Pull request by eddiezane**
#### What type of PR is this?

/kind cleanup
/kind flake

#### What this PR does / why we need it:

These tests are flaking because the [default](https://github.com/kubernetes/kubernetes/blob/2c1b0573c479d213f64db0e83c7d93d7895b8b4b/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L92) kubectl pod running timeout is 1 minute. That is the time that kubectl will wait for a pod created by `kubectl run` or `kubectl create` to be started before it delete it.

There is an expectation that these e2e tests may require a little bit more time to start due to the busy testing environment. That is why the [default](https://github.com/kubernetes/kubernetes/blob/2c1b0573c479d213f64db0e83c7d93d7895b8b4b/test/e2e/framework/util.go#L92) pod start timeout in the e2e framework is 5 minutes.

We can see from the [kubelet logs](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/100490/pull-kubernetes-e2e-kind/1384412652561764352/artifacts/logs/kind-worker/) of [this job](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100490/pull-kubernetes-e2e-kind/1384412652561764352) that the `kuberuntime_manager` starts creating the pod sandbox at `08:13:26`.  A minute later at `08:14:33` the kubelet receives the delete request from the default timeout in kubectl. Shortly after at `08:14:35` the `kuberuntime_manager` is ready to start the container with the created sandbox but the delete is now in progress.

This particular test is using a 1mb busybox image so I think it's safe to say the issue with the scheduling and starting of the pod is external.

```
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.531887     249 config.go:383] "Receiving a new pod" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.532165     249 kubelet.go:1939] "SyncLoop ADD" source="api" pods=[kubectl-9107/failure-4]
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.532524     249 kubelet_pods.go:1520] "Generating pod status" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.538799     249 volume_manager.go:373] "Waiting for volumes to attach and mount for pod" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.550183     249 status_manager.go:586] "Patch status for pod" pod="kubectl-9107/failure-4" patchBytes=[123 34 109 101 116 97 100 97 116 97 34 58 123 34 117 105 100 34 58 34 55 52 102 101 53 52 55 56 45 98 99 51 53 45 52 100 57 51 45 97 48 49 50 45 53 49 56 54 53 53 97 100 54 102 50 50 34 125 44 34 115 116 97 116 117 115 34 58 123 34 36 115 101 116 69 108 101 109 101 110 116 79 114 100 101 114 47 99 111 110 100 105 116 105 111 110 115 34 58 91 123 34 116 121 112 101 34 58 34 73 110 105 116 105 97 108 105 122 101 100 34 125 44 123 34 116 121 112 101 34 58 34 82 101 97 100 121 34 125 44 123 34 116 121 112 101 34 58 34 67 111 110 116 97 105 110 101 114 115 82 101 97 100 121 34 125 44 123 34 116 121 112 101 34 58 34 80 111 100 83 99 104 101 100 117 108 101 100 34 125 93 44 34 99 111 110 100 105 116 105 111 110 115 34 58 91 123 34 108 97 115 116 80 114 111 98 101 84 105 109 101 34 58 110 117 108 108 44 34 108 97 115 116 84 114 97 110 115 105 116 105 111 110 84 105 109 101 34 58 34 50 48 50 49 45 48 52 45 50 48 84 48 56 58 49 51 58 50 54 90 34 44 34 115 116 97 116 117 115 34 58 34 84 114 117 101 34 44 34 116 121 112 101 34 58 34 73 110 105 116 105 97 108 105 122 101 100 34 125 44 123 34 108 97 115 116 80 114 111 98 101 84 105 109 101 34 58 110 117 108 108 44 34 108 97 115 116 84 114 97 110 115 105 116 105 111 110 84 105 109 101 34 58 34 50 48 50 49 45 48 52 45 50 48 84 48 56 58 49 51 58 50 54 90 34 44 34 109 101 115 115 97 103 101 34 58 34 99 111 110 116 97 105 110 101 114 115 32 119 105 116 104 32 117 110 114 101 97 100 121 32 115 116 97 116 117 115 58 32 91 102 97 105 108 117 114 101 45 52 93 34 44 34 114 101 97 115 111 110 34 58 34 67 111 110 116 97 105 110 101 114 115 78 111 116 82 101 97 100 121 34 44 34 115 116 97 116 117 115 34 58 34 70 97 108 115 101 34 44 34 116 121 112 101 34 58 34 82 101 97 100 121 34 125 44 123 34 108 97 115 116 80 114 111 98 101 84 105 109 101 34 58 110 117 108 108 44 34 108 97 115 116 84 114 97 110 115 105 116 105 111 110 84 105 109 101 34 58 34 50 48 50 49 45 48 52 45 50 48 84 48 56 58 49 51 58 50 54 90 34 44 34 109 101 115 115 97 103 101 34 58 34 99 111 110 116 97 105 110 101 114 115 32 119 105 116 104 32 117 110 114 101 97 100 121 32 115 116 97 116 117 115 58 32 91 102 97 105 108 117 114 101 45 52 93 34 44 34 114 101 97 115 111 110 34 58 34 67 111 110 116 97 105 110 101 114 115 78 111 116 82 101 97 100 121 34 44 34 115 116 97 116 117 115 34 58 34 70 97 108 115 101 34 44 34 116 121 112 101 34 58 34 67 111 110 116 97 105 110 101 114 115 82 101 97 100 121 34 125 93 44 34 99 111 110 116 97 105 110 101 114 83 116 97 116 117 115 101 115 34 58 91 123 34 105 109 97 103 101 34 58 34 107 56 115 46 103 99 114 46 105 111 47 101 50 101 45 116 101 115 116 45 105 109 97 103 101 115 47 98 117 115 121 98 111 120 58 49 46 50 57 45 49 34 44 34 105 109 97 103 101 73 68 34 58 34 34 44 34 108 97 115 116 83 116 97 116 101 34 58 123 125 44 34 110 97 109 101 34 58 34 102 97 105 108 117 114 101 45 52 34 44 34 114 101 97 100 121 34 58 102 97 108 115 101 44 34 114 101 115 116 97 114 116 67 111 117 110 116 34 58 48 44 34 115 116 97 114 116 101 100 34 58 102 97 108 115 101 44 34 115 116 97 116 101 34 58 123 34 119 97 105 116 105 110 103 34 58 123 34 114 101 97 115 111 110 34 58 34 67 111 110 116 97 105 110 101 114 67 114 101 97 116 105 110 103 34 125 125 125 93 44 34 104 111 115 116 73 80 34 58 34 49 55 50 46 49 56 46 48 46 50 34 44 34 115 116 97 114 116 84 105 109 101 34 58 34 50 48 50 49 45 48 52 45 50 48 84 48 56 58 49 51 58 50 54 90 34 125 125]
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.550485     249 status_manager.go:595] "Status for pod updated successfully" pod="kubectl-9107/failure-4" statusVersion=1 status={Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-04-20 08:13:26 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-04-20 08:13:26 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [failure-4]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-04-20 08:13:26 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [failure-4]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-04-20 08:13:26 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:172.18.0.2 PodIP: PodIPs:[] StartTime:2021-04-20 08:13:26 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:failure-4 State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-1 ImageID: ContainerID: Started:0xc00184c2dc}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.552344     249 kubelet.go:1952] "SyncLoop RECONCILE" source="api" pods=[kubectl-9107/failure-4]
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.586397     249 desired_state_of_world_populator.go:349] "Added volume to desired state" pod="kubectl-9107/failure-4" volumeName="kube-api-access-9zv2c" volumeSpecName="kube-api-access-9zv2c"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.668666     249 reconciler.go:224] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-9zv2c\" (UniqueName: \"kubernetes.io/projected/74fe5478-bc35-4d93-a012-518655ad6f22-kube-api-access-9zv2c\") pod \"failure-4\" (UID: \"74fe5478-bc35-4d93-a012-518655ad6f22\") "
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.769337     249 reconciler.go:254] "Starting operationExecutor.MountVolume for volume \"kube-api-access-9zv2c\" (UniqueName: \"kubernetes.io/projected/74fe5478-bc35-4d93-a012-518655ad6f22-kube-api-access-9zv2c\") pod \"failure-4\" (UID: \"74fe5478-bc35-4d93-a012-518655ad6f22\") "
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.769514     249 reconciler.go:269] "operationExecutor.MountVolume started for volume \"kube-api-access-9zv2c\" (UniqueName: \"kubernetes.io/projected/74fe5478-bc35-4d93-a012-518655ad6f22-kube-api-access-9zv2c\") pod \"failure-4\" (UID: \"74fe5478-bc35-4d93-a012-518655ad6f22\") "
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.779833     249 atomic_writer.go:178] pod kubectl-9107/failure-4 volume kube-api-access-9zv2c: performed write of new data to ts data directory: /var/lib/kubelet/pods/74fe5478-bc35-4d93-a012-518655ad6f22/volumes/kubernetes.io~projected/kube-api-access-9zv2c/..2021_04_20_08_13_26.526605850
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.779946     249 operation_generator.go:698] MountVolume.SetUp succeeded for volume "kube-api-access-9zv2c" (UniqueName: "kubernetes.io/projected/74fe5478-bc35-4d93-a012-518655ad6f22-kube-api-access-9zv2c") pod "failure-4" (UID: "74fe5478-bc35-4d93-a012-518655ad6f22")
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840608     249 volume_manager.go:404] "All volumes are attached and mounted for pod" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840673     249 kuberuntime_manager.go:460] "No sandbox for pod can be found. Need to start a new one" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840707     249 kuberuntime_manager.go:705] "computePodActions got for pod" podActions={KillPod:true CreateSandbox:true SandboxID: Attempt:0 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[] EphemeralContainersToStart:[]} pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840750     249 kuberuntime_manager.go:714] "SyncPod received new pod, will create a sandbox for it" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840772     249 kuberuntime_manager.go:721] "Stopping PodSandbox for pod, will start new one" pod="kubectl-9107/failure-4"
Apr 20 08:13:26 kind-worker kubelet[249]: I0420 08:13:26.840792     249 kuberuntime_manager.go:776] "Creating PodSandbox for pod" pod="kubectl-9107/failure-4"
Apr 20 08:14:33 kind-worker kubelet[249]: I0420 08:14:33.102274     249 kubelet.go:1955] "SyncLoop DELETE" source="api" pods=[kubectl-9107/failure-4]
Apr 20 08:14:33 kind-worker kubelet[249]: I0420 08:14:33.102487     249 kubelet.go:2043] "Pod has completed execution and should be deleted from the API server" pod="kubectl-9107/failure-4" syncType="update"
Apr 20 08:14:33 kind-worker kubelet[249]: I0420 08:14:33.104760     249 kubelet.go:1949] "SyncLoop REMOVE" source="api" pods=[kubectl-9107/failure-4]
Apr 20 08:14:33 kind-worker kubelet[249]: I0420 08:14:33.104836     249 kubelet.go:2148] "Failed to delete pod" pod="kubectl-9107/failure-4" err="pod not found"
Apr 20 08:14:33 kind-worker kubelet[249]: I0420 08:14:33.105621     249 status_manager.go:558] "Pod does not exist on the server" podUID=74fe5478-bc35-4d93-a012-518655ad6f22 pod="kubectl-9107/failure-4"
Apr 20 08:14:34 kind-worker kubelet[249]: I0420 08:14:34.855342     249 desired_state_of_world_populator.go:290] "Removing volume from desired state" pod="kubectl-9107/failure-4" podUID=74fe5478-bc35-4d93-a012-518655ad6f22 volumeName="kube-api-access-9zv2c"
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.673223     249 kuberuntime_manager.go:798] "Created PodSandbox for pod" podSandboxID="e958992b1d3417b9905d75ff4be6b236655cdabf1b0b9688435b7c3b5552d2d8" pod="kubectl-9107/failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.673920     249 kuberuntime_manager.go:817] "Determined the ip for pod after sandbox changed" IPs=[10.244.1.149] pod="kubectl-9107/failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.674156     249 kuberuntime_manager.go:854] "Creating container in pod" containerType="container" container="&Container{Name:failure-4,Image:k8s.gcr.io/e2e-test-images/busybox:1.29-1,Command:[],Args:[/bin/sh -c exit 42],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-9zv2c,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:true,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}" pod="kubectl-9107/failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.674792     249 kubelet_pods.go:152] "Creating hosts mount for container" pod="kubectl-9107/failure-4" containerName="failure-4" podIPs=[10.244.1.149] path=true
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.674828     249 event.go:291] "Event occurred" object="kubectl-9107/failure-4" kind="Pod" apiVersion="v1" type="Normal" reason="Pulled" message="Container image \"k8s.gcr.io/e2e-test-images/busybox:1.29-1\" already present on machine"
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.674846     249 kubelet_pods.go:160] "Mount cannot be satisfied for the container, because the volume is missing or the volume mounter (vol.Mounter) is nil" containerName="failure-4" ok=false volumeMounter={Name:kube-api-access-9zv2c ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil> SubPathExpr:}
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.674931     249 kuberuntime_manager.go:864] container &Container{Name:failure-4,Image:k8s.gcr.io/e2e-test-images/busybox:1.29-1,Command:[],Args:[/bin/sh -c exit 42],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-9zv2c,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:true,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod failure-4_kubectl-9107(74fe5478-bc35-4d93-a012-518655ad6f22): CreateContainerConfigError: cannot find volume "kube-api-access-9zv2c" to mount into container "failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.674979     249 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"failure-4\" with CreateContainerConfigError: \"cannot find volume \\\"kube-api-access-9zv2c\\\" to mount into container \\\"failure-4\\\"\"" pod="kubectl-9107/failure-4" podUID=74fe5478-bc35-4d93-a012-518655ad6f22
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.675023     249 event.go:291] "Event occurred" object="kubectl-9107/failure-4" kind="Pod" apiVersion="v1" type="Warning" reason="Failed" message="Error: cannot find volume \"kube-api-access-9zv2c\" to mount into container \"failure-4\""
Apr 20 08:14:35 kind-worker kubelet[249]: I0420 08:14:35.693332     249 kuberuntime_manager.go:996] "getSandboxIDByPodUID got sandbox IDs for pod" podSandboxID=[e958992b1d3417b9905d75ff4be6b236655cdabf1b0b9688435b7c3b5552d2d8] pod="kubectl-9107/failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.694269     249 generic.go:389] "PLEG: Write status" pod="kubectl-9107/failure-4"
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.733996     249 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"failure-4.167782dcbf2b1f76", GenerateName:"", Namespace:"kubectl-9107", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kubectl-9107", Name:"failure-4", UID:"74fe5478-bc35-4d93-a012-518655ad6f22", APIVersion:"v1", ResourceVersion:"36213", FieldPath:"spec.containers{failure-4}"}, Reason:"Pulled", Message:"Container image \"k8s.gcr.io/e2e-test-images/busybox:1.29-1\" already present on machine", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc017c13ae836b176, ext:863612218864, loc:(*time.Location)(0x7534580)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc017c13ae836b176, ext:863612218864, loc:(*time.Location)(0x7534580)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "kubectl-9107" not found' (will not retry!)
Apr 20 08:14:35 kind-worker kubelet[249]: E0420 08:14:35.789232     249 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"failure-4.167782dcbf2e198c", GenerateName:"", Namespace:"kubectl-9107", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kubectl-9107", Name:"failure-4", UID:"74fe5478-bc35-4d93-a012-518655ad6f22", APIVersion:"v1", ResourceVersion:"36213", FieldPath:"spec.containers{failure-4}"}, Reason:"Failed", Message:"Error: cannot find volume \"kube-api-access-9zv2c\" to mount into container \"failure-4\"", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc017c13ae839ab8c, ext:863612413950, loc:(*time.Location)(0x7534580)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc017c13ae839ab8c, ext:863612413950, loc:(*time.Location)(0x7534580)}}, Count:1, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "kubectl-9107" not found' (will not retry!)
Apr 20 08:14:36 kind-worker kubelet[249]: I0420 08:14:36.699112     249 kuberuntime_manager.go:996] "getSandboxIDByPodUID got sandbox IDs for pod" podSandboxID=[e958992b1d3417b9905d75ff4be6b236655cdabf1b0b9688435b7c3b5552d2d8] pod="kubectl-9107/failure-4"
Apr 20 08:14:36 kind-worker kubelet[249]: E0420 08:14:36.699786     249 generic.go:389] "PLEG: Write status" pod="kubectl-9107/failure-4"
```

This PR sets the kubectl `--pod-running-timeout` to match the 5 minutes of the e2e framework - giving the kubelet a bit more time to start up the pod.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/98854

#### Special notes for your reviewer:

[These 3 tests](https://github.com/kubernetes/kubernetes/compare/master...eddiezane:ez/fix-kubectl-error-code-e2e-test?expand=1#diff-2427c9864b2b37563ae47e0f73d048c1bb4ea9ab367f803e9e044c117eb38f25R518-R539) rely on the kubectl timeout to kill the restarted pod. Fixing this has the unfortunate side effect of making these tests take the maximum 5 minutes each to run. We may need to rework or remove these tests.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
There are more execs and run commands in this, shouldn't we need to modify them too?

**Comment by eddiezane** [comment]
Probably a good call. I'll take a look at the others. I'm curious if they currently flake so I'll start there.

**Comment by aojea** [comment]
> Probably a good call. I'll take a look at the others. I'm curious if they currently flake so I'll start there.

bear in mind not all tests are exercised in all jobs ... I only took a quick look though

**Comment by rikatz** [comment]
I was taking a better look into the framework, and wondering if maybe we should add something in framework util as: 

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/framework/util.go#L579

Like 
```
func (b *KubectlBuilder) WithPodRunningTimeout(timeout string) *KubectlBuilder {
	b.cmd.Args = append(b.cmd.Args, "--pod-running-timeout", timeout)
	return b
}
```

And  then calling via 
```
_, err := framework.NewKubectlCommand(ns, "exec", "httpd", "--pod-running-timeout", framework.PodStartTimeout.String(), "--", "/bin/sh", "-c", "exit 0").WithPodRunningTimeout.Exec()
```

But then I realized that exec and run have positional args, so this might fail.

Another thing I was thinking, just for some clearness was to create a var on the top of the file like 
```
var podRunningTimeoutArg = fmt.Sprintf("--pod-running-timeout=%s", framework.PodStartTimeout.String())
```

And then start adding this in all exec and run commands.

Anyway, both IMO are nits and mostly focused on keeping things clear :D
```

**Comment by eddiezane** [comment]
I dug in deeper and the other tests that use `run` or `exec` do in fact flake.

https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Kubectl%20client

Adding the timeout flag to those tests that rely on the timeout (to check restarts and exit codes) adds ~9 minutes total to the run time for the suite. Not really ideal but I'm not seeing a different way to get both flexibility with environment start time and these particular test cases.

@rikatz good call. I wound up doing your 2nd suggestion but I do like the first one. I'll test it with the positional args.

**Comment by aojea** [comment]
> Adding the timeout flag to those tests that rely on the timeout (to check restarts and exit codes) adds ~9 minutes total to the run time for the suite. Not really ideal but I'm not seeing a different way to get both flexibility with environment start time and these particular test cases.

let's fix then the ones we now that are wrong, 
/lgtm
/retest

**Comment by eddiezane** [comment]
> let's fix then the ones we now that are wrong,

The ones we know are wrong (Simple pod should return command exit codes) are the ones that add this extra time :(

**Comment by aojea** [comment]
hmm, this s a timeout before kubectl gives up, if the pod runs in 30s, the test takes 30 s, no?

**Comment by eddiezane** [comment]
This test (and the ones below it):

* start a pod with `run --restart=OnFailure`
* Run `/bin/sh -c "cat && exit 42"` with `abcd1234` provided as stdin
* Pod receives the stdin, exits 42
* Pod is restarted because of exit 42
* There isn't anymore stdin data so pod waits for input at `cat`
* Pod is eventually killed based on the timeout
* Test asserts that the error was from this time out

https://github.com/kubernetes/kubernetes/blob/1e4388964eaa3e68a4dd40452820581304d5a797/test/e2e/kubectl/kubectl.go#L517-L525

**Comment by aojea** [comment]
> This test (and the ones below it):

I see thanks, I also checked the results and the whole blocks takes 11m now
```

Then one options is to wrap

**Review by rikatz — COMMENTED** [review]
/lgtm

Thanks Eddie

File: test/e2e/kubectl/kubectl.go [hunk 1]
```diff
@@ -495,27 +496,27 @@ var _ = SIGDescribe("Kubectl client", func() {
 
 		ginkgo.It("should return command exit codes", func() {
```
Comment (aojea) [inline test/e2e/kubectl/kubectl.go:497]: this will run all the test in this block in serial, maybe we can split it and run the commands that depend on pods restasrts in its own block so they run in parallel with the other tests?

Comment (eddiezane) [reply test/e2e/kubectl/kubectl.go:497]: I'm having a hard time figuring this out.

The ginkgo docs say "`Its` can be randomized and parallelized across multiple nodes". 

So assuming I move these tests to their own `ginkgo.It` blocks that should be enough?

Testing locally I haven't been able to get these to run concurrently.

I'm probably missing a flag?

```
make WHAT=test/e2e/e2e.test

_output/bin/e2e.test --ginkgo.focus="eddie test" --provider=local --kubeconfig=/Users/ezaneski/.kube/config --ginkgo.parallel.total=30 --test.parallel=30
```

Comment (aojea) [reply test/e2e/kubectl/kubectl.go:497]: Yeah, you need to run the Gingko binary to parallelize not the e2e binary ,
Check the script used in ci https://github.com/kubernetes/kubernetes/blob/1f87e3fe0069eccaa0b0c5885022290c84b7799c/hack/ginkgo-e2e.sh#L171

Comment (eddiezane) [reply test/e2e/kubectl/kubectl.go]: Ahh I got it - thank you!

```
_output/bin/ginkgo --nodes 3 --focus="Simple pod" --skip="should support exec through kubectl proxy|should support exec through an HTTP proxy|should handle in-cluster config" _output/bin/e2e.test -- --provider=local --kubeconfig=/Users/ezaneski/.kube/config
```

Run time is down to 6.5 minutes now.

I pushed up my changes but not sure if that's the correct blocks to use. I'll play with it more when I wake up.

Comment (aojea) [reply test/e2e/kubectl/kubectl.go]: this is a simplified version
```
# setting this env prevents ginkgo e2e from trying to run provider setup
export KUBERNETES_CONFORMANCE_TEST='y'
# setting these is required to make RuntimeClass tests work ... :/
export KUBE_CONTAINER_RUNTIME=remote
export KUBE_CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
export KUBE_CONTAINER_RUNTIME_NAME=containerd
# FIXME we should not tolerate flakes
# but until then, we retry the test in the same job
# to stop PR retriggers for totally broken code
export FLAKE_ATTEMPTS=5
export NUM_NODES=20
# Kind clusters are three node clusters
export NUM_WORKER_NODES=3
ginkgo --nodes=${NUM_NODES} \
	--focus=${FOCUS} \
	--skip=${SKIPPED_TESTS} \
	--flakeAttempts=${FLAKE_ATTEMPTS} \
	/usr/local/bin/e2e.test \
	-- \
	--kubeconfig=${HOME}/admin.conf \
	--provider=local \
	--dump-logs-on-failure=false \
	--report-dir=${E2E_REPORT_DIR}	\
	--disable-log-dump=true \
	--num-nodes=${NUM_WORKER_NODES}
```

File: test/e2e/kubectl/kubectl.go [hunk 2]
```diff
@@ -109,6 +109,9 @@ var (
 	httpdImage    = imageutils.GetE2EImage(imageutils.Httpd)
 	busyboxImage  = imageutils.GetE2EImage(imageutils.BusyBox)
 	agnhostImage  = imageutils.GetE2EImage(imageutils.Agnhost)
+
+	// If this suite still flakes due to timeouts we should change this to framework.PodStartTimeout
+	podRunningTimeoutArg = fmt.Sprintf("--pod-running-timeout=%s", framework.PodStartShortTimeout.String())
```
Comment (eddiezane) [inline test/e2e/kubectl/kubectl.go:114]: @aojea made this change. It's 2 minutes now. Will monitor and bump if needed.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by eddiezane** [comment]
Flake is https://github.com/kubernetes/kubernetes/issues/99979
