### PR TITLE
Ensure new tags are created on existing ELBs

### LINKED ISSUE #54642: Adding tag annotations on service manifest for ELB does not trigger update on AWS
**BUG REPORT**:
/kind bug
/sig aws

**What happened**:
Adding this annotation to an existing service: `{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}}` did not trigger an update on AWS ELB (no new tags).

**What you expected to happen**:
Expected to see those 2 new tags under the existing ELB:  `team=devops,env=qa`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a service without annotation
2. Add the annotation `{"metadata":{"annotations":{"service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags":"team=devops,env=qa"}}}`
3. No tags on AWS

**Anything else we need to know?**:
Creating a new service WITH the annotation will create the expected tags on AWS.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.9
- Cloud provider or hardware configuration**: AWS
- OS (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- Kernel (e.g. `uname -a`): Linux ip-xxxxx 4.4.78-k8s #1 SMP Fri Jul 28 01:28:39 UTC 2017 x86_64 GNU/Linux
- Install tools:
- Others: Using Kops

### PR DESCRIPTION
**Pull request by georgebuckerfield**
**What this PR does / why we need it**:

When editing an existing service of type LoadBalancer in an AWS environment and adding the `service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags` annotation, you would expect the new tags to be set on the load balancer, however this doesn't happen currently. The annotation only takes effect if specified when the service is created.

This PR adds an AddTags method to the ELB interface and uses this to ensure tags set in the annotation are present on the ELB. If the tag key is already present, the value will be updated.

This PR does not remove tags that have been removed from the annotation, it only add/updates tags.

**Which issue(s) this PR fixes**:
Fixes #54642 

**Special notes for your reviewer**:
The change requires that the IAM policy of the master instance(s) has the `elasticloadbalancing:AddTags` permission.

**Release note**:

```release-note
Ensure additional resource tags are set/updated AWS load balancers
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

@kubernetes/sig-aws-misc

**Comment by georgebuckerfield** [comment]
Don't think that failed test has anything to do with the changes, see https://github.com/kubernetes/kubernetes/issues/55652.

/retest

File: pkg/cloudprovider/providers/aws/aws_loadbalancer.go [hunk 1]
```diff
@@ -314,6 +314,18 @@ func (c *Cloud) ensureLoadBalancer(namespacedName types.NamespacedName, loadBala
 				}
 			}
 		}
+
+		{
+			// Add additional tags
+			glog.V(2).Infof("Creating additional load balancer tags for %s", loadBalancerName)
```
Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: It would be nice to check that the tags aren't already present, both to avoid using up all our API operations quota, and to avoid this log message confusing users.  Perhaps in a follow up PR?

Comment (justinsb) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: (And that might allow harmonization with the existing create-map-of-tags code...)

Comment (georgebuckerfield) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: Yes, I did actually go down that route initially, adding a DescribeTags method and using the results of that to work out which tags were missing. But I stripped it out as I realised I was doing at best one API call each time (if nothing missing) and possibly two API calls (if something needed to be added). Whereas just adding them all each time is a single call, no matter what. Unless I've misunderstood something? 

I'd be happy to add the checking logic back in another PR though (would also allow, with a bit more work to make sure default tags were unaffected, for removing tags that are removed from the annotation).

Comment (justinsb) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: Ah - you're right.  I was thinking tags were returned by DescribeLoadBalancer.

Rate limits for read operations are typically much higher than for write operations, but I think we can wait and see if it's a problem in practice - particularly as when there are no additional tags we don't hit this case.

Comment (georgebuckerfield) [reply pkg/cloudprovider/providers/aws/aws_loadbalancer.go]: Cool, I have all the code still, so if it's useful to add in, let me know.
