### PR TITLE
fix bugs in get-kube scripts

### LINKED ISSUE #68305: get-kube-binaries.sh: fails when there's space in path
/kind bug

**What happened**:

Tried to download v1.12.0-beta.1 via `cluster/get-kube-binaries.sh`.

Failed with error:

```

Extracting /Users/ahmetb/Downloads/kubernetes 2/client/kubernetes-client-darwin-amd64.tar.gz into /Users/ahmetb/Downloads/kubernetes 2/platforms/darwin/amd64
ln: failed to create symbolic link '/Users/ahmetb/Downloads'$'\n''2/client/bin': No such file or directory
```

**What you expected to happen**: Work as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Extract release kubernetes.tar.gz to a path with space in it, like `/Users/ahmetb/Downloads/kubernetes 2`

```
cd /Users/ahmetb/Downloads/kubernetes\ 2
yes | cluster/get-kube-binaries.sh
```

**Anything else we need to know?**:

Doesn't reproduce if I extract tar to a directory without spaces in name.

**Environment**:
- Kubernetes version (use `kubectl version`): not applicable
- Cloud provider or hardware configuration: not applicable
- OS (e.g. from /etc/os-release): macOS, `/usr/bin/env bash` pointing to GNU bash4.4.23
- Kernel (e.g. `uname -a`): not applicable

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: fixes various bugs and shellcheck lints in `./cluster/get-kube.*`

**Which issue(s) this PR fixes**:

Fixes #68305 

**Special notes for your reviewer**: Now that we have a lint presubmit to prevent regressions (#68438), I think it is worthwhile to eliminate these bugs bit by bit. In particular we have a _lot_ of incorrect string quoting throughout out shell scripts causing bugs like #68305.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @spiffxp @mikedanese
For cluster/

File: cluster/get-kube.sh [hunk 1]
```diff
@@ -143,10 +144,10 @@ fi
 kernel=$(uname -s)
 case "${kernel}" in
   Darwin)
-    platform="darwin"
+    #platform="darwin"
```
Comment (roberthbailey) [inline cluster/get-kube.sh]: Did you mean to comment this (and the next one) out? If so, should we just delete the whole case statement?

File: cluster/get-kube.sh [hunk 2]
```diff
@@ -158,16 +159,16 @@ esac
 machine=$(uname -m)
 case "${machine}" in
   x86_64*|i?86_64*|amd64*)
-    arch="amd64"
+    #arch="amd64"
```
Comment (roberthbailey) [inline cluster/get-kube.sh]: Same with these.

File: cluster/get-kube.sh (hunk 1 above)
Comment (BenTheElder) [reply cluster/get-kube.sh]: SGTM, this block of code is copied throughout the codebase currently, but here these values are unused. I'll delete them. (also thanks for review!)

Comment (BenTheElder) [reply cluster/get-kube.sh]: done

File: cluster/get-kube.sh (hunk 2 above)
Comment (BenTheElder) [reply cluster/get-kube.sh]: done

File: cluster/get-kube.sh [hunk 3]
```diff
@@ -143,10 +144,8 @@ fi
 kernel=$(uname -s)
```
Comment (ixdy) [inline cluster/get-kube.sh]: you could also just execute the TODO and remove these checks entirely

File: cluster/get-kube.sh [hunk 4]
```diff
@@ -85,10 +85,11 @@ KUBE_CI_VERSION_REGEX="^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)-([a
 #   KUBE_VERSION
 function set_binary_version() {
   if [[ "${1}" =~ "/" ]]; then
-    export KUBE_VERSION=$(curl -fsSL --retry 5 "https://dl.k8s.io/${1}.txt")
+    KUBE_VERSION=$(curl -fsSL --retry 5 "https://dl.k8s.io/${1}.txt")
```
Comment (ixdy) [inline cluster/get-kube.sh]: I don't understand these changes

Comment (BenTheElder) [reply cluster/get-kube.sh]: fixed. the export below is now correct

File: cluster/get-kube.sh (hunk 3 above)
Comment (BenTheElder) [reply cluster/get-kube.sh]: rough summary from offline discussion:
- this check causes us to avoid unnecessary download, extract, and run of the next script if the platform is not supported
- this check might also be out of date wrt supported platforms, but:
a) this script should probably go away at some point (when CI no longer depends on it? :grimacing:)
b) probably we should keep this PR scoped to bash lints only

Comment (roberthbailey) [reply cluster/get-kube.sh]: I also thought that this looked weird (a bunch of case statements that are empty) but am in favor of lint cleanup and not rocking the boat too much.

Comment (BenTheElder) [reply cluster/get-kube.sh]: yeah, in general this _script_ is gross because it's basically a roundabout curl | bash k8s install, but unfortunately CI depends on it and I want to be careful to not break it.

I would be inclined to file a follow-up to refactor this check further, but I think we should focus on not depending on this script. In the meantime though, getting it out of `hack/.shellcheck_failures` will help ensure it doesn't regress in other PRs.

Comment (BenTheElder) [reply cluster/get-kube.sh]: cc @krzyzacy we should probably get a "re-implement kubetest extracting kubernetes tarballs to not depend on get-kube.sh" objective planned soon.

**Comment by BenTheElder** [comment]
this _should_ be fine now :-)

**Comment by ixdy** [comment]
Friday, Friday
gotta merge code on Friday
/lgtm
/hold cancel

**Comment by BenTheElder** [comment]
to be clear https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72861/pull-kubernetes-typecheck/37259/ typecheck did not fail, i'd guess the pod-utils failed the job for some other reason ...

**Comment by ixdy** [comment]
that prow update may have been bad...

**Comment by BenTheElder** [comment]
Thank you @ixdy :-)
