### PR TITLE
Disable kubelet local endpoints on windows

### LINKED ISSUE #78628: Windows kubelet won't start "Failed to create listener for podResources endpoint"
**What happened**:

I replaced the kubelet on one of my 1.14 nodes with a build from master, and now I'm getting this error starting up.

Test passes since 5/31/2019 commit b7fa33ec1 have been failing on testgrid. If you look at the logs, the Windows nodes are not coming up. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows/1134583855047512068

```
F0602 02:35:46.663366   12224 server.go:179] Failed to create listener for podResources endpoint: parse npipe://%5Cvar%5Clib%5Ckubelet%5Cpod-resources//./pipe/kubelet: invalid URL escape "%5C"
goroutine 156 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0x72b9d01, 0x3, 0xc00041c280, 0xc1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:900 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x72b9d80, 0xc000000003, 0xc0003b6b60, 0x71c6d2d, 0x9, 0xb3, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:815 +0xed
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printf(0x72b9d80, 0x3, 0x40f4965, 0x37, 0xc000a4bea0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:727 +0x155
k8s.io/kubernetes/vendor/k8s.io/klog.Fatalf(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1309
k8s.io/kubernetes/pkg/kubelet/server.ListenAndServePodResources(0xc0002a9740, 0x3e, 0x9a1abb0, 0xc000289300, 0x9a1abd0, 0xc00078d320)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:179 +0x175
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).ListenAndServePodResources(0xc0002c0900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2216 +0x220
created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1103 +0x123

```

**What you expected to happen**:
No errors starting up kubelet

**How to reproduce it (as minimally and precisely as possible)**:
Build master, then try to run the kubelet on Windows

**Anything else we need to know?**:

/sig windows

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Windows Server 2019
- Kernel (e.g. `uname -a`): 10.0.17763.529
- Install tools: aks-engine

### PR DESCRIPTION
**Pull request by dashpole**
**What type of PR is this?**
/kind bug
/sig node
/priority critical-urgent

**What this PR does / why we need it**:
This PR removes the local endpoint support for windows, and allows the kubelet to start up without the endpoint on unsupported OS's.  The LocalEndpoint support for windows added in previous releases did not work and did not have adequate testing.

Disabling this broken functionality was discussed and approved at sig-windows on June 4th, 2019.  [Notes](https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#)

**Which issue(s) this PR fixes**:
Fixes #78628

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @yujuhong @PatrickLang

### CODE REVIEW

File: pkg/kubelet/util/util_windows.go [hunk 1]
```diff
@@ -107,13 +107,9 @@ func parseEndpoint(endpoint string) (string, string, error) {
...
-// LocalEndpoint returns the full path to a windows named pipe
-func LocalEndpoint(path, file string) string {
-	u := url.URL{
-		Scheme: npipeProtocol,
-		Path:   path,
-	}
-	return u.String() + "//./pipe/" + file
+// LocalEndpoint empty implementation
+func LocalEndpoint(path, file string) (string, error) {
+	return "", fmt.Errorf("LocalEndpoints are unsupported in this build")
```
Comment (PatrickLang) [inline pkg/kubelet/util/util_windows.go]: Can we keep the error message consistent between _windows and _unsupported?

Comment (PatrickLang) [reply pkg/kubelet/util/util_windows.go]: prefer plural version for both

**Comment by PatrickLang** [comment]
Other than the error message consistency nit, LGTM

**Comment by PatrickLang** [comment]
/sig windows
FYI - we also discussed this in the SIG-Windows meeting today and didn't have any objections to disabling this feature as its untested on Windows. agenda: https://docs.google.com/document/d/1Tjxzjjuy4SQsFSUVXZbvqVb64hjNAG5CQX8bK7Yda9w/edit#

File: pkg/kubelet/util/util_windows.go (hunk 1 above)
Comment (dashpole) [reply pkg/kubelet/util/util_windows.go]: done

**Comment by yujuhong** [comment]
/approve
Leaving lgtm to @PatrickLang to see if he wants to test this manually.

**Comment by PatrickLang** [comment]
Thanks for all the help on this!
