### PR TITLE
Renews cached NodeInfo with new vSphere connection

### LINKED ISSUE #404: Attach failing with NotAuthenticated error.
Pod is not getting created successfully with statically created disk, attached to pod directly as volume or via PVC.

Steps to reproduce
1. Deployed Kubernetes cluster based off multi-vc-upstream branch.  Tried both custom hyperkube build as well as 1.9.0-alpha for Project Octopus.
2. Tried workflows https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/kubernetes-volumes.html and https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/persistent-vols-claims.html, few minutes after cluster creation. Both failed. Got following message in events log:

AttachVolume.Attach failed for volume "test-volume" : NotAuthenticated

Unable to mount volumes for pod "test-vmdk_default(5467bfc6-d6f4-11e7-8b4c-005056ae23f1)": timeout expired waiting for volumes to attach/mount for pod "default"/"test-vmdk". list of unattached/unmounted volumes=[test-volume]

Will be attaching logs shortly.

======================================

Pasting 'events' for reference:

Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----				-------------			--------	------			-------
  28m		28m		1	{default-scheduler }						Normal		Scheduled		Successfully assigned test-vmdk to kubernetes-node2
  28m		28m		1	{kubelet kubernetes-node2}					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "default-token-b99km" 
  26m		5m		10	{kubelet kubernetes-node2}					Warning		FailedMount		Unable to mount volumes for pod "test-vmdk_default(5467bfc6-d6f4-11e7-8b4c-005056ae23f1)": timeout expired waiting for volumes to attach/mount for pod "default"/"test-vmdk". list of unattached/unmounted volumes=[test-volume]
  28m		5m		19	{attachdetach-controller }					Warning		FailedMount		AttachVolume.Attach failed for volume "test-volume" : NotAuthenticated
  3m		3m		1	{kubelet kubernetes-node2}					Normal		SuccessfulMountVolume	MountVolume.SetUp succeeded for volume "test-volume" 
  3m		3m		1	{kubelet kubernetes-node2}	spec.containers{test-container}	Normal		Pulling			pulling image "gcr.io/google_containers/test-webserver"
  3m		3m		1	{kubelet kubernetes-node2}	spec.containers{test-container}	Normal		Pulled			Successfully pulled image "gcr.io/google_containers/test-webserver"
  3m		3m		1	{kubelet kubernetes-node2}	spec.containers{test-container}	Normal		Created			Created container
  3m		3m		1	{kubelet kubernetes-node2}	spec.containers{test-container}	Normal		Started			Started container

### PR DESCRIPTION
**Pull request by prashima**
**What this PR does / why we need it**:
This PR modifies two public functions of nodemanager.go- GetNodeInfo and GetNodeDetails. For both these functions NodeInfo object is renewed with new GoVmomiClient and new vclib VirtualMachine and Datacenter.

**Which issue(s) this PR fixes** :
Fixes vmware#404 

**Special notes for your reviewer**:
Code has been structured to minimize impact on existing 1.9 release code and any side-effects due to NodeInfo modification. This is a quick solution for vSphere connection renewal  problem. A more enhanced solution is target for upcoming major release.

Testing:

- [x] Successfully tried out pod creation, deletion with dynamic volume.
- [x] Successfully ran e2e tests.
 

**Release note**:
```release-note
Fixes authentication problem faced during various vSphere operations.
```

### CODE REVIEW

File: pkg/cloudprovider/providers/vsphere/nodemanager.go [hunk 1]
```diff
@@ -317,3 +334,23 @@ func (nm *NodeManager) GetVSphereInstance(nodeName k8stypes.NodeName) (VSphereIn
...
+		err := fmt.Errorf("vSphereInstance for vSphere %q not found while refershing NodeInfo for VM %q", nodeInfo.vcServer, nodeInfo.vm)
+		return nil, err
+	}
+	if reconnect {
+		err := vsphereInstance.conn.Connect(ctx)
+		if err != nil {
+			return nil, err
+		}
+	}
+	vm := nodeInfo.vm.RenewVM(vsphereInstance.conn.GoVmomiClient)
```
Comment (luomiao) [inline pkg/cloudprovider/providers/vsphere/nodemanager.go]: It looks like you have created a new VM object and new datacenter object and replaced the old nodeinfo. Then do you need to release/destroy the old VM and datacenter object? There is a DeleteVM method in virtualmachine.go. I am wondering if replace current NodeInfo with new objects will leave dangling objects behind.

Comment (prashima) [reply pkg/cloudprovider/providers/vsphere/nodemanager.go]: @luomiao the DeleteVM function does deletion of actual vSphere VM. We don't want to do that. Our intention here is just to renew the vclib VirtualMachine struct, which in turn extends govmomi VirtualMachine, by setting up new client object. The vSphere VM should remain intact. 

Any on going operation that still has handle to older vclib VirtualMachine object can continue to use it without any foreseeable race condition (for now at least :)). Once those operations finish the older VirtualMachine struct instance, which is no longer being referenced by NodeInfo or any other ongoing operation, will get garbage collected. 

Hope that answers your concern.

Comment (luomiao) [reply pkg/cloudprovider/providers/vsphere/nodemanager.go]: Got it, thanks for the explanation :)

**Comment by gmarek** [comment]
Looks good generally. The only thing missing is some unit tests.

**Comment by prashima** [comment]
@gmarek I can add some unit tests once  https://github.com/kubernetes/kubernetes/pull/55918 goes in.

**Comment by mbohlool** [comment]
In the rest of kubernetes code, we do not capitalize start of error messages as they may be merged together. It is not critical to fix this for cherry pick but please fix it for the main repo PR.
