### PR TITLE
e2e_node: remote: fix getting pod logs

### LINKED ISSUE #130369: e2e: remote.go fails to copy pod logs
### What happened?

/var/log/pods permissons don't allow e2e runner to copy logs from **fedora-coreos** instances. It fails with this error:
```
I0213 15:47:50.870841  901711 ssh.go:146] Running the command scp, with args: [-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -i /home/ed/.ssh/google_compute_engine -r ed@34.169.181.247:/var/log/pods/ _artifacts/tmp-node-e2e-43c8c248-cos-beta-117-18613-164-28]
E0213 15:47:54.250634  901711 ssh.go:149] failed to run SSH command: out: scp: /var/log/pods/pods-4991_pod-logs-websocket-604bd213-08c1-43d3-a957-83f639a496bc_56c9e6de-c882-4880-87ce-1fb6ef8f19d0: Permission denied
, err: exit status 1
```

### What did you expect to happen?

pod logs copied successfully

### How can we reproduce it (as minimally and precisely as possible)?

Run e2e tests from linux machine this way:
```
kubetest2-gce --test=node --down=false -- --parallelism=1 --gcp-zone=us-west1-a --gcp-project=<put your project name here> --repo-root=. --image-config-file=/home/prow/go/src/k8s.io/test-infra/jobs/e2e_node/crio/latest/image-config-cgroupv1.yaml --delete-instances=false --test-args='--container-runtime-endpoint=unix:///var/run/crio/crio.sock --container-runtime-process-name=/usr/local/bin/crio --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/crio.service --kubelet-cgroups=/system.slice/kubelet.service" --extra-log="{\"name\": \"crio.log\", \"journalctl\": [\"-u\", \"crio\"]}"' --skip-regex='' --focus-regex='ImageGCNoEviction' --v 10 --timeout=300m 2>&1 | tee /tmp/log
```

I believe it's easily reproducible with kubetest as well.

### Anything else we need to know?

The fix is underway.

### Kubernetes version

<details>

```console
k/k@master
```

</details>

### Cloud provider

<details>
google
</details>

### OS version

<details>

not relevant

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It changes permissions for /var/log/pods sub-directories so that e2e remote runner can copy them.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/130369

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e_node/remote/remote.go [hunk 1]
```diff
@@ -239,9 +239,11 @@ func getTestArtifacts(host, testDir string) error {
 		}
 	}
 	// Copy container logs to artifacts/hostname
-	if _, err := SSH(host, "chmod", "-R", "a+r", "/var/log/pods"); err == nil {
-		if _, err = runSSHCommand(host, "scp", "-r", fmt.Sprintf("%s:/var/log/pods/", GetHostnameOrIP(host)), logPath); err != nil {
-			return err
+	if _, err := SSH(host, "find", "/var/log/pods", "-type", "d", "-exec", "chmod +x"); err == nil {
```
Comment (ffromani) [inline test/e2e_node/remote/remote.go:242]: do we know why permissions changed in the first place?

**Review by ffromani — COMMENTED** [review]
/triage accepted
/priority important-soon

restoring our ability of getting logs is surely something we should fix quickly

File: test/e2e_node/remote/remote.go (hunk 1 above)
Comment (ffromani) [reply test/e2e_node/remote/remote.go:242]: fair enough. The only other concern is that we should make sure to not relax permissions too much. I'll try to verify the expected permissions on fedora/coreos and report.
Note I'm not blocking this PR (but I'd like to do extra verification before).

Comment (ffromani) [reply test/e2e_node/remote/remote.go:242]: It seems the expected permissions are
- `0750` for `/var/log/pods/` proper
- `0755` for all the subdirectories in `/var/log/pods`

Now: if we are fine with the permissions of `/var/log/pods`, which I'm not sure (that may be the culprit in the first place!)

Can we:
1. document with a comment the expected permissions? (feel free to cite me and quote I checked against `CoreOS 4.18`)
2. add the `-mindepth 1` option to the `find` commandline above so the permission change won't affect `/var/log/pods` ?

I think point 1 is safe to do anyway

Comment (bart0sh) [reply test/e2e_node/remote/remote.go:242]: Here is how permissions look on Fedora CoreOS 41.20250130.3.0. It's what's used to run node eviction tests.
```
core@test-fedora-coreos-41-20250130-3-0-gcp-x86-64:~$ ls -la /var/log |grep pods
drwxr-x---.  3 root   root               109 Feb 26 08:32 pods

core@test-fedora-coreos-41-20250130-3-0-gcp-x86-64:~$ sudo ls -la /var/log/pods/
total 4
drwxr-x---.  4 root root 4096 Feb 26 08:34 .
drwxr-xr-x. 11 root root  183 Feb 26 08:27 ..
drwxr-xr-x.  3 root root  104 Feb 26 08:28 priority-memory-eviction-ordering-test-8570_guaranteed-pod_cb285fd6-5abd-4201-ba93-c65e7eb510d6
drwxr-xr-x.  2 root root   82 Feb 26 08:34 priority-memory-eviction-ordering-test-8570_test-admit-pod_af695713-8d74-4441-8391-16e47b158e84
```

So, you're right, /var/log/pods is a culprit here. Simpler solution would be to change permissions for /var/log/pods:
`sudo chmod o+rx /var/log/pods`.
WDYT?

Comment (ffromani) [reply test/e2e_node/remote/remote.go:242]: When I find myself in the need of relaxing permissions, I learned the hard way the best ROI investment is usually pause and think.

I think the intention here is to make it harder/impossible for users to peek in _other_ pod logs. This is likely why the top directory is group-traversable but not world-traversable.
But a trusted user would need to traverse it to fetch all logs.

Now, the e2e suite does a lot of changes anyway, so naively changing permissions (but at least I'd loudly log it) is probably OK.

But thinking out loud: which are the UID and GID the log collecting step uses? Can we make it run with GID=0 (but making sure to drop all privileges?)
Alternatively: what about restoring the `/var/log/pods` permissions once the copy is done?

If all the above turns upractical/too hard, I'd at least add a loud log warning and move on, again the e2e suite does a lot of changes to the cluster/worker nodes anyway so it's unwise to run it anywhere besides dev environments and/or CI.

Comment (bart0sh) [reply test/e2e_node/remote/remote.go:242]: That permissions change happens at the end, when all tests are done. After that a test instance is usually deleted, so I'd say it's harmless to change /var/log/pods permissions. However, considering that pod and container logs are deleted from that directory on pod termination, I start to think we don't need to copy them at all.

> But thinking out loud: which are the UID and GID the log collecting step uses? Can we make it run with GID=0 (but making sure to drop all privileges?)

That's much bigger change and can cause unpredictable test failures, I guess. I wouldn't go that far, considering my above observations.

Comment (ffromani) [reply test/e2e_node/remote/remote.go:242]: > That permissions change happens at the end, when all tests are done. After that a test instance is usually deleted, so I'd say it's harmless to change /var/log/pods permissions. However, considering that pod and container logs are deleted from that directory on pod termination, I start to think we don't need to copy them at all.

OK if this is the case I'm fine with the current change but I'd really really like to add a log about the permission change, and then we can move on.

File: test/e2e_node/remote/remote.go [hunk 2]
```diff
@@ -239,9 +239,11 @@ func getTestArtifacts(host, testDir string) error {
...
+		if _, err := SSH(host, "chmod", "-R", "a+r", "/var/log/pods"); err == nil {
```
Comment (haircommander) [inline test/e2e_node/remote/remote.go:243]: why do we do both?

**Review by ffromani — COMMENTED** [review]
/lgtm

thanks @bart0sh !

**Comment by bart0sh** [comment]
/assign @SergeyKanzhelev @mrunalp
for approval

**Review by simonfogliato — APPROVED** [review]
/lgtm

**Comment by ffromani** [comment]
/approve

considering the quite extensive convo we had in the comments, this seems to be a good fix. Thanks!

**Review by hashim21223445 — APPROVED** [review]
