### PR TITLE
Fix StatefulSet e2e flake

### LINKED ISSUE #41889: [k8s.io] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy 21m14s
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41821/pull-kubernetes-e2e-gce-gci/18753/

`go run hack/e2e.go -v -test --test_args='--ginkgo.focus=StatefulSet\s\[k8s\.io\]\sBasic\sStatefulSet\sfunctionality\s\[StatefulSetBasic\]\sScaling\sshould\shappen\sin\spredictable\sorder\sand\shalt\sif\sany\sstateful\spod\sis\sunhealthy$'`

@ncdc do you know the statefulset owners?

### PR DESCRIPTION
**Pull request by kow3ns**
**What this PR does / why we need it**:
Fixes StatefulSet e2e flake by ensuring that the StatefulSet controller has observed the unreadiness of Pods prior to attempting to exercise scale functionality.
**Which issue this PR fixes** 
fixes #41889
```release-note
NONE
```

### CODE REVIEW

**Comment by kow3ns** [comment]
@k8s-bot kops aws e2e test this

File: test/e2e/statefulset.go [hunk 1]
```diff
@@ -217,6 +217,7 @@ var _ = framework.KubeDescribe("StatefulSet", func() {
 
 			By("Before scale up finished setting 2nd pod to be not ready by breaking readiness probe")
 			sst.BreakProbe(ss, testProbe)
+			sst.WaitForStatus(ss, 0)
```
Comment (foxish) [inline test/e2e/statefulset.go]: Shouldn't this be `WaitForStatus(ss, 2)`?

Comment (kargakis) [inline test/e2e/statefulset.go]: status.Replicas should always be 1 here regardless of the pod being ready or not. It seems that this is not the case actually and we treat this field as ReadyReplicas for ReplicaSets/Deployments (DaemonSets have a different name but there is still a separation between created and ready in the status). So the test seems fine but API-wise I think there is an unnecessary incosistency between the workload apis.

**Comment by kargakis** [comment]
/lgtm
/approve

Opened https://github.com/kubernetes/kubernetes/issues/42410 to discuss the api issue.

**Comment by kargakis** [comment]
Labeling as a test bug and adding the 1.6 milestone

File: test/e2e/framework/statefulset_utils.go [hunk 2]
```diff
@@ -355,7 +355,8 @@ func (s *StatefulSetTester) SetHealthy(ss *apps.StatefulSet) {
 	}
 }
 
-func (s *StatefulSetTester) waitForStatus(ss *apps.StatefulSet, expectedReplicas int32) {
+// WaitForStatus waits for the ss.Status.Replicas to be equal to expectedReplicas
+func (s *StatefulSetTester) WaitForStatus(ss *apps.StatefulSet, expectedReplicas int32) {
```
Comment (kargakis) [inline test/e2e/framework/statefulset_utils.go]: Update this to also check that ss.Status.ObservedGeneration >= ss.Generation.

**Comment by kargakis** [comment]
@kubernetes/test-infra-maintainers the bot shouldn't suggest (ping) others if the PR is approved.

**Comment by kow3ns** [comment]
@enisoc Can we set the milestone to this release (its break fix)?

**Comment by enisoc** [comment]
@kow3ns It's already in the milestone, so it should be good once it gets lgtm, which it seems @kargakis removed due to an additional change requested.

File: test/e2e/framework/statefulset_utils.go (hunk 2 above)
Comment (kargakis) [inline test/e2e/framework/statefulset_utils.go]: I just realized that observedGeneration is not working for StatefulSets and sent a PR: https://github.com/kubernetes/kubernetes/pull/42429

**Comment by ixdy** [comment]
@apelisse @grodrigues3 is https://github.com/kubernetes/kubernetes/pull/42367#issuecomment-283613866 on your list?

**Comment by apelisse** [comment]
@ixdy @kargakis Yes, I think it's similar to https://github.com/kubernetes/test-infra/issues/2076

File: test/e2e/framework/statefulset_utils.go (hunk 2 above)
Comment (kow3ns) [inline test/e2e/framework/statefulset_utils.go]: @kargakis Using this code 
```golang
if ss.Status.ObservedGeneration == nil { 
        Logf("ss observed generation is nil")
} else {
        Logf("ss observed generation %d",ss.Status.ObservedGeneration)
}
Logf("ss generation %d",ss.Generation)
if ssGet.Status.ObservedGeneration == nil {
        Logf("ssGet observed generation is nil")
} else {
        Logf("ssGet observed generation %d",ssGet.Status.ObservedGeneration)
}
Logf("ssGet generation %d",ssGet.Generation)
```
The observed generation of both ss and ssGet are always nil. However the generation appears to increment consistently.

what about the following
```golang
if  ssGet.Generation < ss.Generation {
     return false, nil
}
```

Comment (kow3ns) [inline test/e2e/framework/statefulset_utils.go]: @kargakis just saw the above do you want to wait until  #42429 merges before submitting this?

Comment (kargakis) [inline test/e2e/framework/statefulset_utils.go]: Yes, I just tagged it with a manual approval since the hack changes were minimal and it should be merged when you get back online:) Once you update this helper with the new check feel free to apply lgtm

**Comment by kow3ns** [comment]
@k8s-bot cvm gke e2e test this

**Comment by kow3ns** [comment]
@k8s-bot gci gke e2e test this

**Comment by kow3ns** [comment]
@k8s-bot cvm gke e2e test this
