### PR TITLE
Continue admitting the pod regardless of return value from killPodFunc

### LINKED ISSUE #78405: Failed to admit critical pod due to "timeout waiting to kill pod" while handling admission failure
**What happened**:

Kops runs `kube-proxy` from a pod manifest stored on the node, having the `scheduler.alpha.kubernetes.io/critical-pod` annotation.

We've experienced the case where the cluster autoscaler turned on a new node and, once the node has been added to the cluster, application pods have been admitted before `kube-proxy`. Once it was the turn of `kube-proxy`, all system resources were utilized, so the pod has not been regularly admitted.

However, since it's a critical pod, the `kubelet` executed the `HandleAdmissionFailure`, which has tried to kill (`killPodNow`)  a pod whose container wasn't started yet (it was downloading the Docker image), which has caused `killPodNow` to timeout and return the error `"timeout waiting to kill pod"`.

The admission of `kube-proxy` failed with the following error:
```
Unexpected error while attempting to recover from admission failure: preemption: pod worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c) failed to evict timeout waiting to kill pod
```

The `kube-proxy` pod execution has not been retried, so we've got a node without `kube-proxy` running and its networking broken.

**What you expected to happen**:

The `kube-proxy` should be eventually admitted.

**Anything else we need to know?**:

A minimal log extraction for comprehension:

```
14:27:17.909755 kubelet.go:1833] SyncLoop (ADD, "api"): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)"
14:27:27.318348 kubelet.go:1833] SyncLoop (ADD, "file"): "kube-proxy-ip-REDACTED.eu-west-1.compute.internal_kube-system(a1808f36adc75b3585b0951a00ac3102)"
14:27:42.456247 predicate.go:107] Failed to admit pod kube-proxy-ip-REDACTED.eu-west-1.compute.internal_kube-system(a1808f36adc75b3585b0951a00ac3102) - Unexpected error while attempting to recover from admission failure: preemption: pod worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c) failed to evict timeout waiting to kill pod
14:27:42.479469 kubelet.go:1878] SyncLoop (PLEG): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)", event: &pleg.PodLifecycleEvent{ID:"829b7759-7c9d-11e9-ac16-06903246ae0c", Type:"ContainerStarted", Data:"6721ad58d43a97348b00dbca545df21da98242315bcd74740331964d828adb67"}
14:28:17.000000 kubelet.go:1878] SyncLoop (PLEG): "worker-async-ad-stitching-tracking-5f89bb489d-mvdq4_www(829b7759-7c9d-11e9-ac16-06903246ae0c)", event: &pleg.PodLifecycleEvent{ID:"829b7759-7c9d-11e9-ac16-06903246ae0c", Type:"ContainerStarted", Data:"4725d1fbeb24e46b13d3a19290b61929f4cb14cb4398ee455b3f1ffa8a7cbc17"}
```

From the "Failed to admit pod" log I have been able to trace back the core code involved:

- `HandleAdmissionFailure` (`pkg/kubelet/preemption.go`)
  Logs: "Failed to admit pod [POD] - [ERROR]"
  - `evictPodsToFreeRequests` (`pkg/kubelet/preemption.go`)
    Error message: "preemption: pod [POD] failed to evict [ERROR]"
    - `getPodsToPreempt` (`pkg/kubelet/preemption.go`)
    - `killPodFunc` -> `killPodNow` (`pkg/kubelet/pod_workers.go`)
      Error message: "timeout waiting to kill pod"

**Environment**:
- Kubernetes version: `1.11.7`
- Cloud provider: AWS
- OS: ubuntu 16.04.6 LTS (Xenial Xerus)
- Kernel: `Linux 4.4.0-1083-aws`
- Install tools: kops
- Network plugin and version: kubenet

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Over #78405, @dashpole suggested we ignore the error return from killPodFunc and continue admitting the Pod.

In future syncPod loops, the kubelet will retry the pod deletion steps that it was stuck on.

Fixes #78405

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @dashpole

**Comment by tedyu** [comment]
cc @yujuhong

File: pkg/kubelet/preemption/preemption.go [hunk 1]
```diff
@@ -107,7 +107,9 @@ func (c *CriticalPodAdmissionHandler) evictPodsToFreeRequests(admitPod *v1.Pod,
 		// this is a blocking call and should only return when the pod and its containers are killed.
 		err := c.killPodFunc(pod, status, nil)
 		if err != nil {
-			return fmt.Errorf("preemption: pod %s failed to evict %v", format.Pod(pod), err)
+			klog.Warningf("preemption: pod %s failed to evict %v", format.Pod(pod), err)
+			// In future syncPod loops, the kubelet will retry the pod deletion steps that it was stuck on.
```
Comment (mattjmcnaughton) [inline pkg/kubelet/preemption/preemption.go]: Can you update this comment with what happens if the `kubelet` is never able to kill the pod it is stuck on? Or is there no chance of that happening?

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for this change :)

Can you confirm my thought that this would be difficult (and most likely not worth it) to integration test? I'm struggling to think of a way we could effectively ensure the kubelet gets stuck evicting a pod.

**Comment by dashpole** [comment]
Seeing as you could simply pass in a killPodFunc that returns an error, we probably could test this.

File: pkg/kubelet/preemption/preemption.go (hunk 1 above)
Comment (dashpole) [reply pkg/kubelet/preemption/preemption.go]: The kubelet will continue to retry the deletion indefinitely.  It is obscure enough of a case where it probably doesn't belong in a comment here...

For example, we have encountered this in the past in cases where docker believes a container exists, but containerd doesn't.  In such cases, container deletions always fail, but docker continues to report that the container exists.

**Comment by tedyu** [comment]
With the following change, TestEvictPodsToFreeRequests still passes - it would fail without this PR:
```
diff --git a/pkg/kubelet/preemption/preemption_test.go b/pkg/kubelet/preemption/preemption_test.go
index 132ffdb659..906c811275 100644
--- a/pkg/kubelet/preemption/preemption_test.go
+++ b/pkg/kubelet/preemption/preemption_test.go
@@ -63,7 +63,7 @@ func (f *fakePodKiller) getKilledPods() []*v1.Pod {

 func (f *fakePodKiller) killPodNow(pod *v1.Pod, status v1.PodStatus, gracePeriodOverride *int64) error {
        f.killedPods = append(f.killedPods, pod)
-       return nil
+       return fmt.Errorf("problem killing pod %v", pod)
 }

 type fakePodProvider struct {
```
If the above seems Okay, I can add it to the PR.

**Comment by dashpole** [comment]
That seems reasonable.  This should purely _add_ a new test case, rather than modifying an existing one.

**Comment by tedyu** [comment]
@dashpole 
I have added new test.

**Comment by tedyu** [comment]
ping @tallclair @vishh for review

**Comment by hoegaarden** [comment]
@dashpole Is there a reason why you didn't open a cherry-pick PR to `release-1.15`? Wouldn't we want this fix in `release-1.15` too?

**Comment by dashpole** [comment]
I thought this had made the 1.15 release... Thanks @tedyu for opening one to 1.15.

**Comment by tedyu** [comment]
But the cherry pick needs rebase.
Let me know if I should open another PR for 1.15

**Comment by dashpole** [comment]
@tedyu I don't see any indicator that it needs a rebase.  It may just not be possible to cherry-pick directly onto 1.15.  You may need to add some additional changes to get it to build.

**Comment by dashpole** [comment]
The failure looks unrelated to the PR.  Says there is a conflict in a file you didn't change...
