### PR TITLE
Use node addresses from informer in kubelet certificate manager

### LINKED ISSUE #130001: Kubelet serving CSR never created
### What happened?

We are seeing an issue occasionally where the kubelet never gets the server certificate (`serverTLSBootstrap: true`).
We have an auto-approver for the server certificates and detect this issue because we are waiting for the certificate to appear in `/var/lib/kubelet/pki/kubelet-server-current.pem`. When we hit it, not even the CSR is created.
It started happening after upgrading to v1.32 so we believe it could be from a change that was introduced in v1.32.
Restarting the kubelet does not help. It happily continues without the server certificate, even though it is configured to bootstrap it.

In healthy clusters, we see this:

```console
$ kubectl get csr
NAME        AGE   SIGNERNAME                                    REQUESTOR                           REQUESTEDDURATION   CONDITION
csr-8dql4   29s   kubernetes.io/kubelet-serving                 system:node:lennart-kubelet-debug   <none>              Pending
csr-r8ztr   17s   kubernetes.io/kubelet-serving                 system:node:lennart-kubelet-debug   <none>              Pending
csr-xtwpf   30s   kubernetes.io/kube-apiserver-client-kubelet   system:node:lennart-kubelet-debug   <none>              Approved,Issued
```

In faulty clusters, there is just the client CSR.
~~We are not sure why two CSRs are created for the server either, but it works when we approve the newer of them.~~

Edit: The two server CSRs happen because kubeadm restarts the kubelet as part of initializing. This is how it picks up the client certificate. After the restart, the kubelet does not "remember" its old server CSR so it creates a new. This is not an issue.

Here is the kubelet config from an affected node: [kubelet-config.txt](https://github.com/user-attachments/files/18688742/kubelet-config.txt)

### What did you expect to happen?

When configured, the kubelet should always create the server CSR.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately we do not have any guaranteed reproduction steps.
In general, this is what is needed to trigger the issue:

1. Kubelet is configured to rotate certificates (default) and to use server certificate.
2. Node status is stable, i.e. there are no changes of any kind that would cause the kubelet to update the status.
3. Kubelet is restarted and the server certificate does not exist (e.g. because it was removed or it wasn't issued yet).

In this specific case you should be able to see that the CSR is not created:

```console
$ kubectl get csr
NAME        AGE   SIGNERNAME                                    REQUESTOR                           REQUESTEDDURATION   CONDITION
csr-2mq8h   22s   kubernetes.io/kube-apiserver-client-kubelet   system:node:lennart-kubelet-debug   <none>              Approved,Issued
$ kubectl get nodes
NAME                    STATUS   ROLES           AGE   VERSION
lennart-kubelet-debug   Ready    control-plane   28s   v1.32.1
```

### Anything else we need to know?

I believe the culprit is https://github.com/kubernetes/kubernetes/pull/128640. Not the randomization of the interval, but the change in how the [zero case for the lastStatusReportTime](https://github.com/kubernetes/kubernetes/pull/128640/files#diff-f39bb531745e5658a65143c9054c3fa92aa3ac9f41e9e627ac61b7ff08808153R607) is handled.
It used to be treated as expired and trigger an update. After the PR it is treated the opposite.
This means that `patchNodeStatus` is never called and consequently neither is `setLastObservedNodeAddresses`.
The latter is initializing the kubelets internal node address state (not node status).
This internal state is what the server certificate manager is relying on to create the CSR. As long as it is `nil`, i.e. as long as the node status hasn't been patched, it cannot progress.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.1
```

</details>

### Cloud provider

<details>
Happens both with and without external cloud provider
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aojea**
The kubelet certificate manager was using a closure to get the node addresses, but this closure depended on a static field that was only updated during the node status update. This created a twisted dependency between the node.status reconcile loops and the certificate manager.

This commit fixes this issue by using the node informer to get the node addresses directly. This ensures that the kubelet always requests a certificate with the latest node addresses.

/kind bug
/kind cleanup

Fixes #130001

```release-note
NONE
```

/sig node
/sig network

### CODE REVIEW

**Comment by dims** [comment]
cc @cartermckinnon @mmerkes @tzneal

File: pkg/kubelet/certificate/kubelet.go [hunk 1]
```diff
@@ -70,9 +72,32 @@ func newGetTemplateFn(nodeName types.NodeName, getAddresses func() []v1.NodeAddr
...
+// remove the taint, since the node may start with some initial addresses that are changed
+// later by the cloud provider and we need to use only the definitive addresses for the
+// certificate request.
+func getNodeAddressesFromInformer(nodeName types.NodeName, nodeLister corelisters.NodeLister) []v1.NodeAddress {
+	node, err := nodeLister.Get(string(nodeName))
+	if err != nil {
+		klog.ErrorS(err, "fail to obtain node from local cache", "node", nodeName)
+		return nil
+	}
+	if len(node.Status.Addresses) == 0 {
```
Comment (adrianmoisey) [inline pkg/kubelet/certificate/kubelet.go:86]: This is my lack of experience with the Kubernetes codebase, is it possible that `node.Status` is nil at this stage?

Comment (adrianmoisey) [reply pkg/kubelet/certificate/kubelet.go:86]: Looking at other parts of the code base, it seems to be safe to assume that `node.Status` isn't nil

Comment (aojea) [reply pkg/kubelet/certificate/kubelet.go:86]: if no node is found we get an err NotFound IIRC, so at this point we should have a node object

Comment (adrianmoisey) [reply pkg/kubelet/certificate/kubelet.go:86]: The part I was wondering about, is then a node is returned but doesn't yet contain status, that way `node.Status` would be nil, and `node.Status.Addresses` would return a nil pointer exception.

But I see that this is safe (I think I was confused with pointer references), since this can't happen.

**Review by lentzi90 — COMMENTED** [review]
This is such a nice improvement! Thanks!
LGTM from my side

File: pkg/kubelet/certificate/kubelet.go [hunk 2]
```diff
@@ -70,9 +72,32 @@ func newGetTemplateFn(nodeName types.NodeName, getAddresses func() []v1.NodeAddr
...
+		if taint.Key == cloudproviderapi.TaintExternalCloudProvider {
+			return nil
+		}
+	}
+	return node.Status.Addresses
+}
+
 // NewKubeletServerCertificateManager creates a certificate manager for the kubelet when retrieving a server certificate
 // or returns an error.
-func NewKubeletServerCertificateManager(kubeClient clientset.Interface, kubeCfg *kubeletconfig.KubeletConfiguration, nodeName types.NodeName, getAddresses func() []v1.NodeAddress, certDirectory string) (certificate.Manager, error) {
```
Comment (liggitt) [inline pkg/kubelet/certificate/kubelet.go:75]: you shouldn't need to change this file, just change the function passed in to get node addresses, right?

File: pkg/kubelet/certificate/kubelet.go [hunk 3]
```diff
@@ -70,9 +72,32 @@ func newGetTemplateFn(nodeName types.NodeName, getAddresses func() []v1.NodeAddr
...
+	node, err := nodeLister.Get(string(nodeName))
+	if err != nil {
+		klog.ErrorS(err, "fail to obtain node from local cache", "node", nodeName)
+		return nil
+	}
+	if len(node.Status.Addresses) == 0 {
+		return nil
+	}
+	// wait for the cloud provider to initialize the node addresses
+	for _, taint := range node.Spec.Taints {
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/kubelet/certificate/kubelet.go]: @liggitt updated

File: pkg/kubelet/kubelet_getters.go [hunk 4]
```diff
@@ -466,3 +467,28 @@ func (kl *Kubelet) setCachedMachineInfo(info *cadvisorapiv1.MachineInfo) {
...
+	if len(node.Status.Addresses) == 0 {
+		return nil
+	}
+	if !kl.externalCloudProvider {
+		return node.Status.Addresses
+	}
+	// wait for the cloud provider to initialize the node addresses
+	for _, taint := range node.Spec.Taints {
+		if taint.Key == cloudproviderapi.TaintExternalCloudProvider {
+			return nil
```
Comment (cartermckinnon) [inline pkg/kubelet/kubelet_getters.go:490]: So kubelet will no longer request a cert until the taint is removed? I think that makes sense, given the external cloud provider "owns" the address list, but this will lengthen the period when kubelet is ready/accepting pods without having a serving cert. Can you add a log line here?

Somewhat related to the discussion in: https://github.com/kubernetes/kubernetes/pull/73047

Comment (aojea) [reply pkg/kubelet/kubelet_getters.go:490]: yeah, related to this https://github.com/kubernetes/kubernetes/pull/125813

The node addresses are updated just after the taint is removed when the node is initialized by the cloud controller manager

https://github.com/kubernetes/kubernetes/blob/8cca6d98a4fb855979d2a0642391b7a441673d78/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L463-L472

Bear in mind that the CSR requires to have at least one IP , that mean there should be one IP in node.Status.Addresses

https://github.com/kubernetes/kubernetes/blob/8cca6d98a4fb855979d2a0642391b7a441673d78/pkg/kubelet/certificate/kubelet.go#L50-L51

But I'm not sure of what path we want to follow:

- no external cloud provider, everything is the same
- external cloud provider
   -  no --node-ip specified, effectively the behavior should be the same, as there will be no IPs on node.status.addresses
   - node-ip specified, this is the tricky part per https://github.com/kubernetes/kubernetes/pull/121028
       - ip matches cloud-provider addresses, only one CSR is sent and we'll regress on node startup
       - ip partially matches, two CSR are sent, but it may regress or not
       - ip does not match, two CSR are sent but only the last one will be the one matching the actual addresses.

We have been so many times back and forth with node.status.address that now I think we should remove this check, and keep the existing behavior, if someone is specifies the --node-ip with the flag, then it may want to send the CSR with that IP ...

**Comment by aojea** [comment]
Pushed last version based on discussion with @cartermckinnon in https://github.com/kubernetes/kubernetes/pull/130362#discussion_r1973629179, this keeps the same behavior, just removes the dependency on the node status loops by using the local informer. Based on the last year experience _better the devil you know than the devil you don't_

File: pkg/kubelet/kubelet_getters.go [hunk 5]
```diff
@@ -466,3 +466,13 @@ func (kl *Kubelet) setCachedMachineInfo(info *cadvisorapiv1.MachineInfo) {
 	defer kl.machineInfoLock.Unlock()
 	kl.machineInfo = info
 }
+
+// getLastStableNodeAddresses returns the last observed node addresses.
+func (kl *Kubelet) getLastObservedNodeAddresses() []v1.NodeAddress {
+	node, err := kl.GetNode()
```
Comment (aojea) [inline pkg/kubelet/kubelet_getters.go:472]: let's be defensive in case GetNode() changes and returns nil in the future in some cases

File: pkg/kubelet/kubelet_node_status.go [hunk 6]
```diff
@@ -644,7 +644,6 @@ func (kl *Kubelet) patchNodeStatus(originalNode, node *v1.Node) (*v1.Node, error
 		return nil, err
 	}
 	kl.lastStatusReportTime = kl.clock.Now()
-	kl.setLastObservedNodeAddresses(updatedNode.Status.Addresses)
```
Comment (aojea) [inline pkg/kubelet/kubelet_node_status.go:647]: @cartermckinnon this will also improve the latency on cloud providers, since it will not have to wait for the patch of the kubelet,

**Comment by cartermckinnon** [comment]
Thanks @aojea!

/lgtm

**Comment by aojea** [comment]
/test pull-kubernetes-integration


> {Failed  === RUN   TestKMSv2ProviderKeyIDStaleness/regular_gcm

**Comment by liggitt** [comment]
> > {Failed  === RUN   TestKMSv2ProviderKeyIDStaleness/regular_gcm

cc @enj @aramase

**Comment by enj** [comment]
> > > {Failed  === RUN   TestKMSv2ProviderKeyIDStaleness/regular_gcm
> 
> cc @enj @aramase

I see the bug (in the test), will sort it out soon.

**Comment by aramase** [comment]
@aojea does this PR fix https://github.com/kubernetes/kubernetes/issues/130415?

**Comment by aojea** [comment]
> @aojea does this PR fix #130415?

I don't have very clear the entire issue there, node readiness is more complex that cni only, what this does is to decouple the gathering of the node.addresses needed for the CSR generation from the complex loop that happens on nodeUpdateStatus and it returns the actual ips existing in the node.

Since nodeUpdateStatus runs periodically it guaranteed that the address will be eventually set, but as we found out, depending on that loop is very brittle and not really necessary, since the kubelet has access to the existing node object and can return the addresses directly

File: pkg/kubelet/kubelet_getters.go [hunk 7]
```diff
@@ -466,3 +466,13 @@ func (kl *Kubelet) setCachedMachineInfo(info *cadvisorapiv1.MachineInfo) {
...
+	if err != nil || node == nil {
+		klog.ErrorS(err, "fail to obtain node from local cache", "node", kl.nodeName)
```
Comment (liggitt) [inline pkg/kubelet/kubelet_getters.go:474]: I'm on the fence about logging an error here... on init while the node is getting its client cert and registering the node, this will be nil

Comment (aojea) [reply pkg/kubelet/kubelet_getters.go:474]: did I copied this from some place?

Comment (aojea) [reply pkg/kubelet/kubelet_getters.go:474]: let me add verbosity so it can be toggled

Comment (aojea) [reply pkg/kubelet/kubelet_getters.go]: updated to V(4)

**Comment by aojea** [comment]
@liggitt pushed a change to increase the logging verbosity

https://github.com/kubernetes/kubernetes/compare/269cf8b38436ad2f467fd3101a018ab1b70466f8..b6334ae0542d74327d41538996d27b097630cac9

File: pkg/kubelet/kubelet_getters.go [hunk 8]
```diff
@@ -466,3 +466,13 @@ func (kl *Kubelet) setCachedMachineInfo(info *cadvisorapiv1.MachineInfo) {
 	defer kl.machineInfoLock.Unlock()
 	kl.machineInfo = info
 }
+
+// getLastStableNodeAddresses returns the last observed node addresses.
+func (kl *Kubelet) getLastObservedNodeAddresses() []v1.NodeAddress {
+	node, err := kl.GetNode()
+	if err != nil || node == nil {
+		klog.V(4).InfoS("fail to obtain node from local cache", "node", kl.nodeName)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_getters.go:474]: can you please output the error here

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
this unit windows tests failing does not seem related but to require some attention
```
{Failed  === RUN   TestMemoryPressure_VerifyPodStatus
--- FAIL: TestMemoryPressure_VerifyPodStatus (0.03s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x23dd824]

goroutine 50 [running]:
testing.tRunner.func1.2({0x25f6540, 0x3cb4ac0})
	C:/Program Files/Go/src/testing/testing.go:1632 +0x225
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1635 +0x359
panic({0x25f6540?, 0x3cb4ac0?})
	C:/Program Files/Go/src/runtime/panic.go:785 +0x132
k8s.io/kubernetes/pkg/kubelet/eviction.makeMemoryAvailableSignalObservation(0xc0005de630)
	C:/kubernetes/pkg/kubelet/eviction/helpers_windows.go:35 +0x144
k8s.io/kubernetes/pkg/kubelet/eviction.makeSignalObservations(0xc0005de630)
	C:/kubernetes/pkg/kubelet/eviction/helpers.go:845 +0x1a5
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc0005b1600, {0x2bf2a40, 0xc00040c650}, 0xc000063ba0)
	C:/kubernetes/pkg/kubelet/eviction/eviction_manager.go:306 +0x8d7
k8s.io/kubernetes/pkg/kubelet/eviction.TestMemoryPressure_VerifyPodStatus(0xc000356680)
	C:/kubernetes/pkg/kubelet/eviction/eviction_manager_test.go:322 +0x9ed
testing.tRunner(0xc000356680, 0x29e3df8)
	C:/Program Files/Go/src/testing/testing.go:1690 +0xcb
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1743 +0x377
```

**Comment by tuminoid** [comment]
Uhh, it looks like the recently enabled Windows merge blocking job isn't very stable :(

**Comment by aojea** [comment]
> @aojea: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-unit-windows-master	[174a9c8](https://github.com/kubernetes/kubernetes/commit/174a9c86528766bae7dbe9508c8886d5019dd70e)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/130362/pull-kubernetes-unit-windows-master/1904083847360811008)	false	`/test pull-kubernetes-unit-windows-master`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=130362). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aaojea). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

indeed https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-unit-windows-master , I see it failing in a lot of PRs

/cc @BenTheElder @marosset

**Comment by marosset** [comment]
> Uhh, it looks like the recently enabled Windows merge blocking job isn't very stable :(

That job isn't merge blocking and apologies for the failure, we've been putting a lot of effort into stabilizing the job in the v1.33 release

**Comment by BenTheElder** [comment]
> a rebase should fix that signal up (but feel free to merge without a rebase)

rebase shouldn't be necessary when testing in prow, we locally merge the PR as it would be if merged on github before running the tests (and record the commit)

just /retest will use the latest of (PR branch, Target branch)

**Comment by BenTheElder** [comment]
> Ah, we don't do that with the Windows unit test jobs.
We just pull the PR changes and run the tests

We should be using the clone provided by prow, because otherwise we're recording the wrong metadata about what we tested, in periodic release signal AND in presubmit.

the commits are recorded and used by the merge robot and testgrid

**Comment by aojea** [comment]
and also we are consistent, we should not have to rebase our PRs

**Comment by marosset** [comment]
> should be using the clone provided by prow, because otherwise we're record

In order to run the Windows unit tests, we need to provision a Windows machine in an Azure sub hosted for kubernetes community work, and run the tests on that machine. 
If the commits are recorded and used by the merge bot and testgrid, we should be able to fetch them from the windows machine too, correct?

Looking at [podinfo.json](https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/130362/pull-kubernetes-unit-windows-master/1904221755271024640/podinfo.json), is `PULL_PULL_SHA` the SHA of the recorded merge commit?
If so we can try pulling that (right now we are pulling `PULL_NUMBER`

**Comment by enj** [comment]
/lgtm cancel

To stop CI spam.

**Comment by cartermckinnon** [comment]
Might need a rebase to fix the tests?

**Comment by aojea** [comment]
> Might need a rebase to fix the tests?

it shouldn't but it will retrigger the jobs, @cartermckinnon can you lgtm again?

**Comment by aojea** [comment]
/retest

>    streamtranslator_test.go:249:  # HELP apiserver_stream_translator_requests_total [ALPHA] Total number of requests that were handled by the StreamTranslatorProxy, which processes streaming RemoteCommand/V5
         # TYPE apiserver_stream_translator_requests_total counter
         apiserver_stream_translator_requests_total{code="200"} 1
        -apiserver_stream_translator_requests_total{code="400"} 1


the window unit test are panicing and look very unstable https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-unit-windows-master , they should not be informing in current state since create confusion

**Comment by aojea** [comment]
> /lgtm cancel
> 
> To stop CI spam.

someone can lgtm again, the windows job does not seem related and is also not very stable

**Comment by BenTheElder** [comment]
/lgtm
re-applying

**Review by hashim21223445 — APPROVED** [review]
