### PR TITLE
Fix script for updating protobufs.

### LINKED ISSUE #25351: Code generators doesn't work
Well - one work, but all subsequent ones doesn't:
```
Updating generated-protobuf
Updating codegen
go install k8s.io/kubernetes/third_party/forked/reflect: mkdir gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/third_party/forked/: permission denied
go install k8s.io/kubernetes/third_party/golang/go/token: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/third_party/golang/go/token.a: permission denied
go install k8s.io/kubernetes/cmd/libs/go2idl/types: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/cmd/libs/go2idl/types.a: permission denied
go install k8s.io/kubernetes/pkg/util/validation: mkdir gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/pkg: permission denied
go install k8s.io/kubernetes/vendor/github.com/google/gofuzz: mkdir gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/vendor/github.com/google/: permission denied
go install k8s.io/kubernetes/vendor/github.com/golang/glog: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/vendor/github.com/golang/glog.a: permission denied
go install k8s.io/kubernetes/third_party/golang/go/build: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/third_party/golang/go/build.a: permission denied
go install k8s.io/kubernetes/vendor/github.com/spf13/pflag: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/vendor/github.com/spf13/pflag.a: permission denied
go install k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto: open gmarek/go/src/k8s.io/kubernetes/_output/local/go/pkg/linux_amd64/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.a: permission denied
```

cc @wojtek-t @smarterclayton

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #25351

@thockin

### CODE REVIEW

**Comment by soltysh** [comment]
Other possible fix for that is in https://github.com/kubernetes/kubernetes/pull/25346

File: hack/update-generated-protobuf.sh [hunk 1]
```diff
@@ -37,7 +37,13 @@ function prereqs() {
   KUBE_BUILD_CONTAINER_NAME="kube-build-${KUBE_ROOT_HASH}"
   KUBE_BUILD_DATA_CONTAINER_NAME="kube-build-data-${KUBE_ROOT_HASH}"
   DOCKER_MOUNT_ARGS=(
-    --volume "${REPO_DIR:-${KUBE_ROOT}}:/go/src/${KUBE_GO_PACKAGE}"
+    --volume "${REPO_DIR:-${KUBE_ROOT}}/cluster:/go/src/${KUBE_GO_PACKAGE}/cluster"
```
Comment (thockin) [inline hack/update-generated-protobuf.sh]: 1) PLEASE add a comment explaining why the *obvious* cleanup doesn't work.

2) Please explain to me why it doesn't work?  From the error you pasted before it looks like a root/non-root issue.  I didn't have any such issue here - did someone just need to run 'make clean' or 'sudo make clean'.  Nothing in our build should actually require root.

Comment (soltysh) [inline hack/update-generated-protobuf.sh]: @thockin see #25343 for explanation.

Comment (soltysh) [inline hack/update-generated-protobuf.sh]: In short, it's related to SELinux re-labeling happening to mount directory inside the container. All the directories/fies that are then created inside the container are owned by root, which causes problems @gmarek mentioned in his issue. The other possible approach is to build the binaries outside the container, then there's no problem (see my proposed solution for that: #25346.

Comment (thockin) [inline hack/update-generated-protobuf.sh]: Is it selinux or simply "container runs as root" ?

Comment (wojtek-t) [inline hack/update-generated-protobuf.sh]: The latter.

The problem is basically, that we want to avoid mounting the k8s.io/kubernetes/_output directory. If there is an easier way to mount all but this one, then it would be preferred. But I don't know how to do it.

Comment (thockin) [inline hack/update-generated-protobuf.sh]: There is not a way to all-but-one.  But we should just make all the tooling
not run as root in the first place.  I tried it, it's a little more than
trivial.  First PR is in flight.  Not sure how much time I'll get...

Comment (wojtek-t) [inline hack/update-generated-protobuf.sh]: Yeah - that would be great. (And would fix this problem). Thanks!
