### PR TITLE
fix(e2e-node-tests): project and zone in the prerequisites check

### LINKED ISSUE #127362: test-e2e-node prerequisites check are incorrectly calculated
### What happened?

The compute project and zone in the prerequisites check are incorrectly calculated: https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-e2e-node.sh#L134-L145 

`!!! Error in hack/make-rules/test-e2e-node.sh:214
  Error in hack/make-rules/test-e2e-node.sh:214. 'tee -i "${artifacts}/build-log.txt"' exited with status 1 0
Call stack:
  1: hack/make-rules/test-e2e-node.sh:214 main(...)
Exiting with status 1`

### What did you expect to happen?

blocked by the following errors in each case:
1- Could not find gcloud compute/zone when running: .... 
2- Could not find gcloud project when running: .....

### How can we reproduce it (as minimally and precisely as possible)?

1- gcloud config unset compute/zone
2- gcloud config unset project
3- make test-e2e-node REMOTE=true LIST_IMAGES=true

### Anything else we need to know?

gcloud --version

Google Cloud SDK 453.0.0
alpha 2023.10.27
beta 2023.10.27
bq 2.0.98
core 2023.10.27
gcloud-crc32c 1.0.0

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bouaouda-achraf**
/kind bug
/kind e2e

#### What this PR does / why we need it:
fix : e2e test on https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-e2e-node.sh#L134-L145 
 The compute project and zone in the prerequisites check are incorrectly calculated.

#### Which issue(s) this PR fixes:
*Automatically closes linked issue when PR is merged.
Usage: `Fixes https://github.com/kubernetes/kubernetes/issues/127362.

Fixes #

#### Does this PR introduce a user-facing change?
no

```release-note
n/a
```

/sig node

### CODE REVIEW

File: hack/make-rules/test-e2e-node.sh [hunk 1]
```diff
@@ -131,14 +131,14 @@ if [ "${remote}" = true ] && [ "${remote_mode}" = gce ] ; then
   fi
 
   # Get the compute zone
-  zone=${ZONE:-"$(gcloud info --format='value(config.properties.compute.zone.value)')"}
+  zone=${ZONE:-"$(gcloud info --format='value(config.properties.compute.zone.value)' | tr -d '[:space:]')"}
```
Comment (bart0sh) [inline hack/make-rules/test-e2e-node.sh:134]: Can you explain the fix? 
In my environment both values are equal:
```
$ gcloud config unset compute/zone
Unset property [compute/zone].

$ [ $(gcloud info --format='value(config.properties.compute.zone.value)') == $(gcloud info --format='value(config.properties.compute.zone.value)' | tr -d '[:space:]') ] && echo equal
equal
```

Comment (bouaouda-achraf) [reply hack/make-rules/test-e2e-node.sh:134]: thanks for your comment . 
fix explanation : removing all whitespaces  (tr -d '[:space:]' ) ref : https://linuxcommand.org/lc3_man_pages/tr1.html [:space:]  all horizontal or vertical whitespace . 

1-can you check on your env (you will see the diff ) : 
```bash
GCLOUD_TEST=$(gcloud info --format='value(config.properties.compute.zone.value)' )
re="[[:space:]]+"
if [[ $GCLOUD_TEST =~ $re ]]; then
  echo "before fix: WITH space"
else
  echo "before fix: NO space"
fi

GCLOUD_TEST=$(gcloud info --format='value(config.properties.compute.zone.value)' | tr -d '[:space:]' )
re="[[:space:]]+"
if [[ $GCLOUD_TEST =~ $re ]]; then
  echo "after fix: WITH space"
else
  echo "after fix: NO space"
fi
```
output on my machine : 
before fix: WITH space
after fix: NO space
2- can you reproduce the bug on your env ?  
3- your gcloud --version ?

Comment (bart0sh) [reply hack/make-rules/test-e2e-node.sh:134]: 1.  
```
$ bash <<EOF
> GCLOUD_TEST=$(gcloud info --format='value(config.properties.compute.zone.value)' )
re="[[:space:]]+"
if [[ $GCLOUD_TEST =~ $re ]]; then
  echo "before fix: WITH space"
else
  echo "before fix: NO space"
fi

GCLOUD_TEST=$(gcloud info --format='value(config.properties.compute.zone.value)' | tr -d '[:space:]' )
re="[[:space:]]+"
if [[ $GCLOUD_TEST =~ $re ]]; then
  echo "after fix: WITH space"
else
  echo "after fix: NO space"
fi
> EOF
before fix: WITH space
after fix: WITH space
```
3. no, I can't
4. 
```
$ gcloud --version
Google Cloud SDK 493.0.0
alpha 2024.09.13
beta 2024.09.13
bq 2.1.8
bundled-python3-unix 3.11.9
core 2024.09.13
gsutil 5.30
```

Comment (bouaouda-achraf) [reply hack/make-rules/test-e2e-node.sh:134]: I just test it with 493.0.0 & 453.0.0  downloaded from https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz and **it works.** 
the issue appears when we use gcloud binary installed using scoop (powershell / windows ) and  run it with WSL : 
``` bash
# which gcloud
/mnt/c/Users/XXXX/scoop/shims/gcloud
```bash 
# cat /mnt/c/Users/XXXXscoop/shims/gcloud
#!/bin/sh
# C:\Users\XXXX\scoop\apps\gcloud\current\bin\gcloud.cmd
MSYS2_ARG_CONV_EXCL=/C cmd.exe /C "C:\Users\XXXX\scoop\apps\gcloud\current\bin\gcloud.cmd"  "$@" 
``

It will not impact the existing setup but it will handle this case (local running development case).

Comment (bart0sh) [reply hack/make-rules/test-e2e-node.sh:134]: nit: since this is a bash script, we may want to strip unwanted characters using bash string manipulations, e.g.
```
zone=${ZONE:-"$(gcloud info --format='value(config.properties.compute.zone.value)')"}
zone=${zone// /}
```

Comment (bart0sh) [reply hack/make-rules/test-e2e-node.sh]: /lgtm

**Comment by bart0sh** [comment]
/assign @SergeyKanzhelev @mrunalp 
for approval

**Comment by bouaouda-achraf** [comment]
/retest-required 
( Flake )

File: hack/make-rules/test-e2e-node.sh [hunk 2]
```diff
@@ -132,13 +132,15 @@ if [ "${remote}" = true ] && [ "${remote_mode}" = gce ] ; then
 
   # Get the compute zone
   zone=${ZONE:-"$(gcloud info --format='value(config.properties.compute.zone.value)')"}
+  zone=${zone// /}
```
Comment (SergeyKanzhelev) [inline hack/make-rules/test-e2e-node.sh:135]: so you set it to a space? Or space somehow was set by some automation? I am trying to understand how one can enter this state?

**Review by SergeyKanzhelev — APPROVED** [review]
whatever the case, it looks good to me. Sounds like some WSL involved there based on other comments.

/lgtm

File: hack/make-rules/test-e2e-node.sh (hunk 2 above)
Comment (bouaouda-achraf) [reply hack/make-rules/test-e2e-node.sh:135]: the space was set by cli  : 
---
the issue appears when we use gcloud binary installed using scoop (powershell / windows ) and run it with WSL :

# which gcloud
/mnt/c/Users/XXXX/scoop/shims/gcloud
```bash 
# cat /mnt/c/Users/XXXXscoop/shims/gcloud
#!/bin/sh
# C:\Users\XXXX\scoop\apps\gcloud\current\bin\gcloud.cmd
MSYS2_ARG_CONV_EXCL=/C cmd.exe /C "C:\Users\XXXX\scoop\apps\gcloud\current\bin\gcloud.cmd"  "$@" 
The PR will not impact the existing setup but it will handle this case (local running development case).
---

Comment (SergeyKanzhelev) [reply hack/make-rules/test-e2e-node.sh:135]: thx!

I lgtm-ed, but not an approver here.

@dims are you an approver here? This is simple quality of life change

Comment (dims) [reply hack/make-rules/test-e2e-node.sh:135]: happy to!
