### PR TITLE
ipallocator bug if ips has leading zeros

### LINKED ISSUE #118723: Service IP Allocator doesn't handle certain IPv6 ranges
### What happened?

We ran into an issue with an old version of k8s 1.18 that we were running where subnet for cluster IP is given as `fc::/112`. 

The control plane comes up just fine but then when you try to create a k8s service, it fails due to a broken behavior with the IP Allocator 

```bash
# kubectl apply -f /etc/kubernetes/etcd-service.yaml
The Service "etcd" is invalid: spec.clusterIP: Invalid value: "?fc00000000000000000000000077a5": must be empty, 'None', or a valid IP address
```
Since this is not really a supported version of the k8s, I went around digging up a bit more to see what is the regular behavior and found this to be very inconsistent across a few release branches. 

> All of the example below are the output of the test case `TestAllocateNextFC` referenced below. 

### On master Branch
```bash
k8s/kubernetes/pkg/registry/core/service/ipallocator/ipallocator_test.go:82: invalid address [252 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
--- FAIL: TestAllocateNextFC (0.00s)
FAIL
FAIL	k8s.io/kubernetes/pkg/registry/core/service/ipallocator	2.040s
```

### On `release-1.27`
```bash
k8s/kubernetes/pkg/registry/core/service/ipallocator/ipallocator_test.go:82: invalid address [252 0 0 0 0 0 0 0 0 0 0 0 0 1 1]
--- FAIL: TestAllocateNextFC (0.00s)
FAIL
FAIL	k8s.io/kubernetes/pkg/registry/core/service/ipallocator	1.599s
```

### on `release-1.26`
```bash
=== RUN   TestAllocateNextFC
fc::2c23
--- PASS: TestAllocateNextFC (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/registry/core/service/ipallocator	1.533s
```

### On `release-1.24`
```bash
go test -timeout 30m -run ^TestAllocateNextFC$ k8s.io/kubernetes/pkg/registry/core/service/ipallocator -v

=== RUN   TestAllocateNextFC
fc::a06e
--- PASS: TestAllocateNextFC (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/registry/core/service/ipallocator	0.566s
```

### On `release-1.18`
```bash
```bash
go test -timeout 30m -run ^TestAllocateNextFC$ k8s.io/kubernetes/pkg/registry/core/service/ipallocator -v

=== RUN   TestAllocateNextFC
?fc00000000000000000000000077a5
--- PASS: TestAllocateNextFC (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/registry/core/service/ipallocator	0.566s
```

### What did you expect to happen?

IP Allocator should return a valid IP address or return an error if the CIDR ranges are invalid. 

### How can we reproduce it (as minimally and precisely as possible)?

```go
func TestAllocateNextFC(t *testing.T) {
	_, cidr, err := netutils.ParseCIDRSloppy("fc::/112")
	if err != nil {
		t.Fatal(err)
	}
        // Need to be replaced with the suitable handler for that version of the branch
	r, err := newTestAllocator(cidr)
	if err != nil {
		t.Fatal(err)
	}
	defer r.Destroy()
	ip, err := r.AllocateNext()
	if err != nil {
		t.Fatalf("%s", err.Error())
	}
	fmt.Println(ip.String())
}
```
Add the above Test case under the IP allocator test case 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

NA

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>
NA
</details>

### Install tools

<details>
NA
</details>

### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

### PR DESCRIPTION
**Pull request by aojea**
The ipallocator for the new IPAddress object use the golang big.Int library for some math operations, like adding an offset to an IP address.

We use the bytes array to convert between big.Int and IP addresses, however, IP addresses are always represented as 4 or 16 bytes arrays. Big int bytes representations just return the byte array until the most representative number, this requires that we need to prepend these extra bytes for IPs with leading zeros.

Change-Id: I9d539f582cae1f9f4e373b28c5b94d7a342f09c7

/kind bug
Fixes #118723

```release-note
NONE
```

This logic is only used for the new allocator that uses IPAddress object, that is still alpha, so no need to backport or regression

Big thanks and all credit to @harshanarayana for detecting and explaining this subtle bug.

### CODE REVIEW

File: pkg/registry/core/service/ipallocator/ipallocator_test.go [hunk 1]
```diff
@@ -587,6 +587,18 @@ func Test_addOffsetAddress(t *testing.T) {
...
 		},
+		{
+			name:    "IPv4 with leading zeros",
+			address: netip.MustParseAddr("0.0.1.8"),
+			offset:  138,
+			want:    netip.MustParseAddr("0.0.1.146"),
+		},
+		{
+			name:    "IPv6 with leading zeros",
+			address: netip.MustParseAddr("fc::1"),
```
Comment (thockin) [inline pkg/registry/core/service/ipallocator/ipallocator_test.go:598]: should we denote this as "00fc" to make it clear?  It took me a minute to figure out what was missing here

**Review by thockin — COMMENTED** [review]
/approve
/lgtm
/hold

just one question, feel free to unhold or fix or just comment it in code

File: pkg/registry/core/service/ipallocator/ipallocator_test.go (hunk 1 above)
Comment (harshanarayana) [reply pkg/registry/core/service/ipallocator/ipallocator_test.go:598]: +1 from me. That `00` prefix is what lead to the issue. So, unless there is some standard of how the IPs are denoted that prevents it, it would be nice to have `00` prefixed.

Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator_test.go:598]: agree, the problem of this bug is this subtle details, 00fc vs fc00

Comment (aojea) [reply pkg/registry/core/service/ipallocator/ipallocator_test.go]: done

**Comment by aojea** [comment]
updated , @harshanarayana I need lgtm again

**Comment by harshanarayana** [comment]
/lgtm 

@aojea thanks for taking care of this

**Comment by aojea** [comment]
/hold cancel

concern addressed
