### PR TITLE
Sanitize hostname in network proxy test

### LINKED ISSUE #112760: remove duplicate slash in test/e2e/network/proxy.go
### Which jobs are failing?

e2e conformance

### Which tests are failing?

Hi！I use local-up-cluster.sh to deploy the kubernetes cluster v1.25.0 . When I was performing a `A set of valid responses are returned for both pod and service Proxy` conformance test, I noticed that the request sent to kube-apiserver was 

> https://localhost:6443//api/v1/namespaces/proxy-xxx/pods/agnhost/proxy?method=DELETE

As you can see, the duplication slashes appear in request. And the error 

> Failed to process jsonResponse. invalid character'p' after top-level value.

keeps outputing in log file. 
I then looked at the corresponding kube-apiserver log and found that the other request urls contained a single slash and the error request url contained two slashes.
`I0928 11:21:48.011677   34616 httplog.go:131] "HTTP" verb="GET" URI="//api/v1/namespaces/proxy-xxx/services/test-service/proxy/some/path/with/HEAD" latency="377.066µs" userAgent="v1.25.0-e2e.test/v0.0.0 (linux/amd64) kubernetes/a866cbe -- [sig-network] Proxy version v1 A set of valid responses are returned for both pod and service ProxyWithPath [Conformance]" audit-ID="" srcIP="" resp=404`

`I0928 11:21:48.011990   34616 httplog.go:131] "HTTP" verb="PUT" URI="/api/v1/namespaces/job-xxx/status" latency="1.761526ms" userAgent="kube-controller-manager/v1.25.0 (linux/amd64) kubernetes/6f2ad5b/system:serviceaccount:kube-system:namespace-controller" audit-ID="" srcIP="" apf_pl="workload-high" apf_fs="kube-system-service-accounts" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="1.504044ms" resp=200`

`I0928 11:21:48.012816   34616 httplog.go:131] "HTTP" verb="DELETE" URI="//api/v1/namespaces/proxy-xxx/pods/agnhost/proxy?method=DELETE" latency="369.426µs" userAgent="v1.25.0-e2e.test/v0.0.0 (linux/amd64) kubernetes/a866cbe -- [sig-network] Proxy version v1 A set of valid responses are returned for both pod and service Proxy [Conformance]" audit-ID="" srcIP="" resp=404`

According to the code in `test/e2e/network/proxy.go`, [https://localhost:6443/] comes from the kubeConfig configuration file and is set by hack/lib/util.sh. The related code is as follows:
> clusters:
> - cluster:
> certificate-authority: ${ca_file}
> server: https://${api_host}:${api_port}/
> name: local-up-cluster

The request sent to kube-apiserver in `test/e2e/network/proxy.go` is as follows:
`urlString := f.ClientConfig().Host + "/api/v1/namespaces/" + ns + "/pods/agnhost/proxy/some/path/with/" + httpVerb`

This results in two slashes. So maybe we need to remove the duplicate slash symbols in the above code?

### Since when has it been failing?

.

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by akankshakumari393**
Signed-off-by: Akanksha Kumari <akankshakumari393@gmail.com>
Fixes  #112760

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

I don't have clear from the issue if this is a problem of the kubeconfig used , or if we should sanitize the host field, but removing the additional slash will make fail setups that have a Host field without a trailing slash

Let's comment on the issue first, please

File: test/e2e/network/proxy.go [hunk 1]
```diff
@@ -350,7 +350,7 @@ var _ = common.SIGDescribe("Proxy", func() {
 			httpVerbs := []string{"DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"}
 			for _, httpVerb := range httpVerbs {
 
-				urlString := f.ClientConfig().Host + "/api/v1/namespaces/" + ns + "/pods/agnhost/proxy/some/path/with/" + httpVerb
+				urlString := f.ClientConfig().Host + "api/v1/namespaces/" + ns + "/pods/agnhost/proxy/some/path/with/" + httpVerb
```
Comment (aojea) [inline test/e2e/network/proxy.go:353]:
```suggestion
				urlString := strings.TrimRight(f.ClientConfig().Host, "/") + "/api/v1/namespaces/" + ns + "/pods/agnhost/proxy/some/path/with/" + httpVerb
```

**Comment by aojea** [comment]
ok, I see, so the problem here is that we can have:

Host = http://localhost:6443
or 
Host = http://localhost:6443/

it seems that we should consider this, my suggestion is to always trim the last slash 

https://github.com/kubernetes/kubernetes/pull/112763/files#r982089562

https://go.dev/play/p/tA97Z4bijRc

/hold cancel

**Comment by aojea** [comment]
/test pull-kubernetes-integration

unrelated failure
