### PR TITLE
Tolerate pod not found errors in storage e2e

### LINKED ISSUE #91195: [Failing test] gce-cos-master-serial (ci-kubernetes-e2e-gci-gce-serial)
**Which jobs are failing**:
> gce-cos-master-serial (ci-kubernetes-e2e-gci-gce-serial)

**Which test(s) are failing**:
>- Test
>- Overall
>- [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow][LinuxOnly] 
>- [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly] 
>- [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly] 
>- [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow][LinuxOnly] 

**Since when has it been failing**:
> 05-14 03:55 PDT

**Testgrid link**:
> https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

**Reason for failure**:

**Anything else we need to know**:
/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing
/sig storage

### PR DESCRIPTION
**Pull request by gnufied**
Tolerate pod not found errors in e2e.

Fixes https://github.com/kubernetes/kubernetes/issues/91195

/sig storage

cc @kubernetes/sig-storage-bugs

### CODE REVIEW

File: test/e2e/framework/pod/delete.go [hunk 1]
```diff
@@ -39,6 +39,12 @@ const (
 func DeletePodOrFail(c clientset.Interface, ns, name string) {
 	ginkgo.By(fmt.Sprintf("Deleting pod %s in namespace %s", name, ns))
 	err := c.CoreV1().Pods(ns).Delete(context.TODO(), name, metav1.DeleteOptions{})
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			return
+		}
+	}
```
Comment (hasheddan) [inline test/e2e/framework/pod/delete.go:46]:
```suggestion
	if apierrors.IsNotFound(err) {
 		return
	}
```

I believe the out `err != nil` check can be omitted :+1:

**Review by hasheddan — CHANGES_REQUESTED** [review]

File: test/e2e/framework/pod/delete.go [hunk 2]
```diff
@@ -39,6 +39,12 @@ const (
 func DeletePodOrFail(c clientset.Interface, ns, name string) {
```
Comment (pohly) [inline test/e2e/framework/pod/delete.go:39]: Please document the change of semantics, for example as in `DeletePodWithWait` by adding "Resilient to the pod
not existing.".

File: test/e2e/framework/pod/delete.go (hunk 1 above)
Comment (pohly) [reply test/e2e/framework/pod/delete.go:46]: That isn't documented, is it? It just follows from how https://github.com/kubernetes/apimachinery/blob/ab1231685bfe66237a116092641da00923cc00ca/pkg/api/errors/errors.go#L641-L648 is implemented.

I prefer defensive programming and thus keeping the nil check. The two if statements can be combined, though.

Comment (pohly) [reply test/e2e/framework/pod/delete.go:46]: The other functions below could also be simplified; a clean approach would be to first fix that in one commit, then add the same code here in a second one.

File: test/e2e/storage/drivers/csi.go [hunk 3]
```diff
@@ -222,6 +221,9 @@ func (h *hostpathCSIDriver) PrepareTest(f *framework.Framework) (*testsuites.Per
 
 		ginkgo.By(fmt.Sprintf("deleting the driver namespace: %s", ns2))
 		tryFunc(deleteNamespaceFunc(f.ClientSet, ns2, framework.DefaultNamespaceDeletionTimeout))
+		// we need to remove the cleanupHandle at last so as if AfterEach and AfterSuite races with
+		// each other and AfterEach(or defer) run gets killed then it still cleanups.
+		framework.RemoveCleanupAction(h.cleanupHandle)
```
Comment (pohly) [inline test/e2e/storage/drivers/csi.go:226]: The original logic was "if cleanupFunc fails, then don't try to run it again because it'll just fail again". Is this logic flawed?

How can cleanupFunc be invoked and get interrupted while it is still running? That part is not clear to me; mention a race doesn't explain it.

**Comment by pohly** [comment]
> Fixes #91195

Can you explain why this change fixes that bug?

**Comment by gnufied** [comment]
@pohly if you see the e2e failure:


```
pods "hostexec-bootstrap-e2e-minion-group-08bj-cmgx2" not found
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/pod/delete.go:42
```

So this would fix pod not found errors when pod is being deleted and hence fixes https://github.com/kubernetes/kubernetes/issues/91195

**Comment by pohly** [comment]
> if you see the e2e failure: [...]

That explains why ignoring "not found" makes sense.

But why is the second commit needed? That's not obvious. It seems unrelated, unless it somehow causes the situation. I'm sure you know what you are doing, but I'd like to understand it, too.

**Comment by gnufied** [comment]
@pohly only first commit fixes the flake. The second commit was more like for while I am at it. I can drop second commit and move to a new PR.

File: test/e2e/framework/pod/delete.go (hunk 1 above)
Comment (gnufied) [reply test/e2e/framework/pod/delete.go:46]: the second function below already tolerates `pod not found` errors by the looks of it.

**Comment by pohly** [comment]
> The second commit was more like for while I am at it. I can drop second commit and move to a new PR.

Please do.

File: test/e2e/storage/drivers/csi.go (hunk 3 above)
Comment (gnufied) [reply test/e2e/storage/drivers/csi.go]: Here is how Ginkgo handles interrupts:

1. It starts running `AfterSuite` hooks in a separate goroutine (this includes cleanupAction hooks)
2. Once `AfterSuite` hook is done executing it calls `os.Exit(1)`  on test suite.

So how cleanupFunc() that runs via `defer` in test can be interrupted is:
1. `cleanupFunc` starts running via `defer` (or `AfterEach` hook) but first thing that function does is to remove cleanupHandle from `framework.RemoveCleanupAction`.
2. Test suite receives interrupt from user and `AfterSuite` block starts executing 
3. remember that while `cleanupFunc` is running in goroutine#1, `AfterSuite` is running concurrently in goroutine#2.  
4. AfterSuite hook has bunch of `CleanupActions` it needs to run which were registered via `framework.AddCleanupAction(cleanupFunc)` but once `cleanupFunc` starts executing via `defer` in the test, it will remove the cleanupHandle from framework's aftersuite hooks.
5. So if `AfterSuite` did not had anything to run (because those actions were removed via `framework.RemoveCleanupAction` then it will simply go to the last `framework.AfterEach` action and call `os.Exit(1)`
6. So if `os.Exit(1)` is called before `cleanupFunc` has a chance to finish in `defer`, it will not complete.

Naturally to see this race,you will have to interrupt the test suite but even then it may not happen always.  But I will bring this in another PR. This change does not belong here.

File: test/e2e/framework/pod/delete.go (hunk 2 above)
Comment (gnufied) [reply test/e2e/framework/pod/delete.go:40]: done

File: test/e2e/framework/pod/delete.go [hunk 4]
```diff
@@ -35,10 +35,15 @@ const (
 	PodDeleteTimeout = 5 * time.Minute
 )
 
-// DeletePodOrFail deletes the pod of the specified namespace and name.
+// DeletePodOrFail deletes the pod of the specified namespace and name.Resilient to the pod
+// not existing.
```
Comment (pohly) [inline test/e2e/framework/pod/delete.go:39]: nit: missing space between sentences

File: test/e2e/storage/drivers/csi.go (hunk 3 above)
Comment (pohly) [reply test/e2e/storage/drivers/csi.go]: That's a useful explanation, please include it in the commit message so that it gets recorded for others.

Comment (gnufied) [reply test/e2e/storage/drivers/csi.go]: I will add this in the follow up PR. cheers.

File: test/e2e/framework/pod/delete.go (hunk 4 above)
Comment (gnufied) [reply test/e2e/framework/pod/delete.go:39]: fixed
