### PR TITLE
make node lease renew interval more heuristic

### LINKED ISSUE #80172: node status is flapping between ready and not ready state because of long interval at which node lease renew
**What happened**:
The node lease feature becomes beta and enables by default in v1.14. After upgrading our cluster to v1.14, we found some nodes become not ready occasionally and later become ready again after a few seconds. 
In order to have a quick failure detection and recovery, our kubelet has a flag setting `--node-status-update-frequency=5s` and controller-manager has another flag setting `--node-monitor-grace-period=10s`. 

If we use node lease feature, the kubelet doesn't report it's status as frequently as specified by flag `--node-status-update-frequency`, and use node lease mechanism to report that node is alive.
the default interval at which node lease renew is hardcoded 10s,  but it can't be exactly 10s and may be a little bit more than 10s because of some network latency.  when controller-manager doesn't receive messages from kubelet in every 10s in our case, it will mark this node as unreachable and not ready state, but in the next reconcile cycle, it receives the lease update message and mark this node as reachable again,  so the node status is flapping between ready and not ready state.

This seems a breaking change that setting kubelet's lease renewing interval to a hardcoded 10s,  even though our node status update frequency has a little bit small value, node lease should align kubelet's previous behavior and renew as frequently as  `--node-status-update-frequency` to reporting alive message, otherwise controller-manager will mark this node as unreachable.

**What you expected to happen**:
So we should not merely set node lease renewing interval to 10s, maybe depending on the `--node-status-update-frequency` has a more heuristic value.

**How to reproduce it (as minimally and precisely as possible)**:
1. setup a v1.14 kubernetes cluster
2. then set flag `--node-status-update-frequency=5s` to kubelet and `--node-monitor-grace-period=10s` to controller-manager. 
3. then wait a few minute, 
4. you'll find some log regarding `node unreachable` in controller-manager's log.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node
/kind bug
/assign

### PR DESCRIPTION
**Pull request by gaorong**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The node lease feature becomes beta and enables by default in v1.14. After upgrading our cluster to v1.14, we found some nodes become not ready occasionally and later become ready again after a few seconds.
In order to have a quick failure detection and recovery, our kubelet has a flag setting --node-status-update-frequency=5s and controller-manager has another flag setting --node-monitor-grace-period=10s.

If we use node lease feature, the kubelet doesn't report it's status as frequently as specified by flag --node-status-update-frequency, and use node lease mechanism to report that node is alive.
the default interval at which node lease renew is hardcoded 10s, but it can't be exactly 10s and may be a little bit more than 10s because of some network latency. when controller-manager doesn't receive messages from kubelet in every 10s in our case, it will mark this node as unreachable and not ready state, but in the next reconcile cycle, it receives the lease update message and mark this node as reachable again, so the node status is flapping between ready and not ready state.

This seems a breaking change that setting kubelet's lease renewing interval to a hardcoded 10s, even though our node status update frequency has a little bit small value, node lease should align kubelet's previous behavior and renew as frequently as --node-status-update-frequency to reporting alive message, otherwise controller-manager will mark this node as unreachable.

**Which issue(s) this PR fixes**:

Fixes #80172

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
make node lease renew interval more heuristic based on node-status-update-frequency in kubelet
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @wojtek-t

**Comment by liggitt** [comment]
@wojtek-t can you confirm the interaction between the NodeStatusUpdateFrequency/NodeStatusReportFrequency/NodeLeaseDurationSeconds settings in the kubelet and how the node lease feature interacts with them?

**Comment by wojtek-t** [comment]
> @wojtek-t can you confirm the interaction between the NodeStatusUpdateFrequency/NodeStatusReportFrequency/NodeLeaseDurationSeconds settings in the kubelet and how the node lease feature interacts with them?

Described that the issue: #80172

I think the cleanest way would be add a field to KubeletConfig to allow configuring it by users.

@liggitt but that can't be cherrypicked back IIUC (because it introduces new fields to api type that KubeletConfig is). So maybe we actually should:
- add the field to KubeletConfig at head
- cherrypick a PR like that to 1.14 and 1.15 ?
WDYT?

@wangzhen127

**Comment by gaorong** [comment]
I volunteer to implement this feature，if wangzhen127@ has no bandwidth with this.

File: pkg/kubelet/nodelease/controller.go [hunk 1]
```diff
@@ -60,11 +60,17 @@ type controller struct {
 }
 
 // NewController constructs and returns a controller
-func NewController(clock clock.Clock, client clientset.Interface, holderIdentity string, leaseDurationSeconds int32, onRepeatedHeartbeatFailure func()) Controller {
+func NewController(clock clock.Clock, client clientset.Interface, holderIdentity string, leaseDurationSeconds int32, nodeStatusUpdateFrequency time.Duration, onRepeatedHeartbeatFailure func()) Controller {
 	var leaseClient coordclientset.LeaseInterface
 	if client != nil {
 		leaseClient = client.CoordinationV1().Leases(corev1.NamespaceNodeLease)
 	}
+	var renewInterval time.Duration
```
Comment (liggitt) [inline pkg/kubelet/nodelease/controller.go]: is there ever a valid case for renewInterval being >= leaseDurationSeconds? 

protecting against a mismatch between leaseDurationSeconds and nodeStatusUpdateFrequency by forcing renewInterval to be at least X seconds before or < X% of leaseDurationSeconds would make sense to me

Comment (gaorong) [reply pkg/kubelet/nodelease/controller.go]: personally, not found that case. 

IIUC, the `leaseDurationSeconds` seems to be a redundancy filed and not been used by node healthy-related work at least for now. 
As may be used in the future, I agree we should have some restriction to make renewInterval being smaller than `leaseDurationSeconds`

Comment (gaorong) [reply pkg/kubelet/nodelease/controller.go]: > forcing renewInterval to be at least X seconds before or < X% of leaseDurationSeconds

I found it difficult to generate a smart enough `renewInterval` value based on the `leaseDurationSeconds`, because different user may have different `leaseDurationSeconds`. 

As  `leaseDurationSeconds` have not been used by node healthy-related work for now, we may ignore this restriction. only forcing this value based on `nodeStatusUpdateFrequency` is enough.   

so we can cherry-pick this PR to v1.14 and 1.15 safely.

After this fix, we should add a new field to KubeletConfig at head, let user customize the `renewInterval`  value based on their own circumstance. we don't need to worry about this value anymore other than write some documents.

Comment (gaorong) [reply pkg/kubelet/nodelease/controller.go]: @wojtek-t  what do you think about my proposal?

Comment (wojtek-t) [reply pkg/kubelet/nodelease/controller.go]: > is there ever a valid case for renewInterval being >= leaseDurationSeconds?

No - I don't see any usecase for that.
But yeah - as @gaorong pointed out, leaseDuriationSeconds is currently only propagated as part of Lease object and not really used in any meaningful way.

I'm personally not 100% convinced that connecting "renewInterval" with "nodeStatusUpdateFrequency" is exactly what we want. In the ideal world, this should be connected with "node-monitor-grace-period", but that's not even parameter to kubelet, so we don't have any way to reasonably validate it.

So as a workaround, I'm temporarily fine with the logic you proposed in the PR, if we add a very explicit comment of why we're doing that.
So let's change it something like:

```
renewInterval := defaultRenewInterval
// Users are able to decrease the timeout after which nodes are being
// marked as Ready: Unknown by NodeLifecycleController to values
// smaller than defaultRenewInterval. Until the knob to configure
// lease renew interval is exposed to user, we temporarily decrease
// renewInterval based on the NodeStatusUpdateFrequency.
if renewInterval > nodeStatusUpdateFrequency {
  renewInterval = nodeStatusUpdateFrequency
}
```

In the meantime if you could also work on exposing it via kubelet config, it would be great.

Comment (gaorong) [reply pkg/kubelet/nodelease/controller.go]: changed as comments.

I'm going to working on exposing it via kubelet config.

**Comment by wojtek-t** [comment]
/ok-to-test
/lgtm
/approve

Holding to let Jordan also take a look if he wants.
/hold

**Comment by gaorong** [comment]
As all 'parent' PRs of a cherry-pick PR must have one of the "release-note" or "release-note-action-required" labels, I changed the release note and cherry-pickied to the previous release.
