### PR TITLE
kube-proxy: Only open ipv4 sockets for ipv4 clusters

### LINKED ISSUE #66766: kube-proxy: node-port ipv6 port open on v4 cluster
/kind bug

**What happened**:

When creating a node port application (in this case the example guestbook) on a host server that is dual stacked and has AAAA and A DNS entries, the node port on the v6 address is open to kube-proxy and hangs. 

**What you expected to happen**:

The v6 address would refuse the connection and the client would fall back onto the v4 address which would connect correctly.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
clusterName: kubernetes
api:
  advertiseAddress: <ipv4 address>
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 172.30.0.0/16
bootstrapTokens:
  - token: v315ij.jrg9nu08ayho78q7
kubeProxy:
  config:
    mode: ipvs
    ipvs:
      scheduler: lc
```

kubeadm init with the above, and join in some workers. Then install the guestbook application https://kubernetes.io/docs/tutorials/stateless-application/guestbook/

Obtain the node port with `kubectl get services frontend` and telnet to one of the servers on that port from a dual stacked client. The client will connect and refuse to respond to 'GET /'

telnet directly to the IPv4 address of the server on the port and all works as expected. 

**Anything else we need to know?**:

kube-proxy is noted as listening on the port. 

```
ubuntu@srv-jidtj:~$ sudo ss -l -t -p | grep 31759
LISTEN   0         128                       *:31759                   *:*       users:(("kube-proxy",pid=2268,fd=7))
```

**Environment**:
- Kubernetes version (use `kubectl version`):
ubuntu@srv-jidtj:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
Brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.1 LTS
- Kernel (e.g. `uname -a`):
Linux srv-jidtj 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm 1.11
- Others:

### PR DESCRIPTION
**Pull request by michaelbeaumont**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/66766

**Special notes for your reviewer**:

In the code comment and the issue it's mentioned that a `listen` and not just a `bind` is necessary for the e2e tests to pass, but I should think we can at the very least out the `listen` in the case of a IPv6 socket/IPv4 cluster since I don't think the tests will even attempt a connection.
But this PR assumes we don't even want to bind a socket for the other IP version, which to me makes sense.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
The bugs only mentions IPVS, is this happening with `iptables`too?
https://github.com/kubernetes/kubernetes/issues/66766#issuecomment-432426630

Also, seems that the functions `net.Listen` and `net.ListenUDP` that you are changing are receiving an IP address as a parameter, are they not obtaining the IP family from there? why do we need to specify the socket family too?

**Comment by michaelbeaumont** [comment]
I'll test to see if it's happening with `iptables`.

The reason we need to specify the family is if the host is the empty string, it listens on [all local addresses](https://golang.org/pkg/net/#Listen).

**Comment by aojea** [comment]
@michaelbeaumont here is my rationale and my doubts regarding this PR, mainly on how this going to intersect with dual-stack clusters ... dual-stack pods may require this? :thinking: 

Basically the problem is that using a "zero" address opens a port in all interfaces AND in all IP families, then the question is: if I have a single IP family cluster, should not be the server admin responsibility disable the other IP family?
If the server, in this case with a single-stack IPv4 cluster, disables IPv6, it won't have this problem.

I have a similar discussion with @thockin in the opposite situation, a single IPv6 cluster and the OS with dual-stack enabled. In that case, the conclusion was to close it as work as intended but I have to recognize that the zero addresses and dual-stack are scenarios difficult to handle.

/assign @thockin @danwinship

**Comment by michaelbeaumont** [comment]
If I'm understanding the code correctly, a cluster with the new dual stack feature would have the `DualStackProxier` and therefore 2 proxiers, one with ipv6 and one with v4, so this should work itself out.

I suspect it's an unintentional bug. The code takes a zero CIDR, which always has exactly one ip family e.g. `0.0.0.0/0` and turns it into `""` which the `Listen` function interprets as both families. I was surprised to see that jump being made, at the very least a comment would help I think.

But I agree, I'm not sure of the implications on real clusters of changing such behavior

**Comment by danwinship** [comment]
> The code takes a zero CIDR, which always has exactly one ip family e.g. `0.0.0.0/0` and turns it into `""` which the `Listen` function interprets as both families. I was surprised to see that jump being made

No, not quite. The `""` is for proxy-internal stuff. `0.0.0.0` is what gets passed to `Listen`, but that actually means "both families" in golang when you pass `tcp`/`udp` as the network rather than `tcp4`/`tcp6`/`udp4`/`udp6`.

`OpenLocalPort` opens a port that doesn't actually do anything, so there's no big visible effect of this change. But it does make things more correct...

Of course having to fix the bug in two places reminds me of #80720. Would you be interested in redoing this to move the function to kubernetes/utils instead?

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -1612,7 +1612,7 @@ func writeBytesLine(buf *bytes.Buffer, bytes []byte) {
 	buf.WriteByte('\n')
 }
 
-func openLocalPort(lp *utilproxy.LocalPort) (utilproxy.Closeable, error) {
+func openLocalPort(lp *utilproxy.LocalPort, isIPv6 bool) (utilproxy.Closeable, error) {
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go]: you don't need `isIPv6` here; you can just call `utilnet.IsIPv6String(lp.IP)`... oh... except you can't because it might be `""`. Well, you could just add an `IPFamily` field to `LocalPort` then.

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1628,17 +1628,25 @@ func openLocalPort(lp *utilproxy.LocalPort) (utilproxy.Closeable, error) {
 	var socket utilproxy.Closeable
 	switch lp.Protocol {
 	case "tcp":
-		listener, err := net.Listen("tcp", net.JoinHostPort(lp.IP, strconv.Itoa(lp.Port)))
+		network := "tcp4"
+		if isIPv6 {
+			network = "tcp6"
+		}
+		listener, err := net.Listen(network, net.JoinHostPort(lp.IP, strconv.Itoa(lp.Port)))
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go]: it'd be a little simpler to just have like `family = "4"` / `family = "6"` outside of the switch and then `net.Listen("tcp" + family, ...`. (So there's less duplication between the tcp and udp cases.)

**Comment by michaelbeaumont** [comment]
Definitely, I really wanted to reduce the code duplication but wanted feedback first.

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go]: or maybe set `Protocol` to `tcp4`/`tcp6` rather than just `tcp`? (I didn't look deeply to see if that would make sense...)

Comment (michaelbeaumont) [reply pkg/proxy/iptables/proxier.go]: You're right, that also seemed cleaner to me but wasn't sure about `LocalPort`s outside of `openLocalPort` but I'll just ignore it in those cases (i.e. with protocols not tcp or udp).

Comment (michaelbeaumont) [reply pkg/proxy/iptables/proxier.go]: oh yeah `tcp4`/`tcp6` is better! although I'm not sure how many `protocol == "tcp"` kinda checks there are in the code. I'll look into it.

**Comment by michaelbeaumont** [comment]
@danwinship I opened a [PR to utils](https://github.com/kubernetes/utils/pull/136) and went with the `IPFamily` solution

**Comment by thockin** [comment]
This is a fun little corner case.

@danwinship 

> No, not quite. The "" is for proxy-internal stuff. 0.0.0.0 is what gets passed to Listen

Where is that happening?  I don't see it.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
/ok-to-test

**Comment by andrewsykim** [comment]
Folks, should this be cherry-picked to previous versions?

**Comment by danwinship** [comment]
So part of https://github.com/kubernetes/kubernetes/pull/87699#issuecomment-580725254 was incorrect but I believe this part is still right:

> `OpenLocalPort` opens a port that doesn't actually do anything, so there's no big visible effect of this change. But it does make things more correct...

There are some actual minor bugs that are fixed by this, like "If I create a NodePort service on port N in my single-stack IPv4 kubernetes cluster, then I can't later start up an IPv6-only non-kubernetes-based server on port N on the same node". (I'm pretty sure the reverse case was never a problem; if you started the IPv6-only server first, it will not block you from creating the IPv4-only NodePort service.)

It definitely doesn't _need_ to be backported.
