### PR TITLE
Change nodeInfolist building logic in scheduler

### LINKED ISSUE #91601: Daemonset does not provision to all nodes, 0 nodes available
**What happened**: We upgraded 15 kubernetes clusters from 1.17.5 to 1.18.2/1.18.3 and started to see that daemonsets does not work properly anymore.

The problem is that all daemonset pods does not provision. It will return following error message to events:

```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  9s (x5 over 71s)  default-scheduler  0/13 nodes are available: 12 node(s) didn't match node selector.
```

However, all nodes are available and it does not have node selector. Nodes does not have taints either.

daemonset https://gist.github.com/zetaab/4a605cb3e15e349934cb7db29ec72bd8

```
% kubectl get nodes
NAME                                   STATUS   ROLES    AGE   VERSION
e2etest-1-kaasprod-k8s-local           Ready    node     46h   v1.18.3
e2etest-2-kaasprod-k8s-local           Ready    node     46h   v1.18.3
e2etest-3-kaasprod-k8s-local           Ready    node     44h   v1.18.3
e2etest-4-kaasprod-k8s-local           Ready    node     44h   v1.18.3
master-zone-1-1-1-kaasprod-k8s-local   Ready    master   47h   v1.18.3
master-zone-2-1-1-kaasprod-k8s-local   Ready    master   47h   v1.18.3
master-zone-3-1-1-kaasprod-k8s-local   Ready    master   47h   v1.18.3
nodes-z1-1-kaasprod-k8s-local          Ready    node     47h   v1.18.3
nodes-z1-2-kaasprod-k8s-local          Ready    node     47h   v1.18.3
nodes-z2-1-kaasprod-k8s-local          Ready    node     46h   v1.18.3
nodes-z2-2-kaasprod-k8s-local          Ready    node     46h   v1.18.3
nodes-z3-1-kaasprod-k8s-local          Ready    node     47h   v1.18.3
nodes-z3-2-kaasprod-k8s-local          Ready    node     46h   v1.18.3

% kubectl get pods -n weave -l weave-scope-component=agent -o wide
NAME                      READY   STATUS    RESTARTS   AGE     IP           NODE                                   NOMINATED NODE   READINESS GATES
weave-scope-agent-2drzw   1/1     Running   0          26h     10.1.32.23   e2etest-1-kaasprod-k8s-local           <none>           <none>
weave-scope-agent-4kpxc   1/1     Running   3          26h     10.1.32.12   nodes-z1-2-kaasprod-k8s-local          <none>           <none>
weave-scope-agent-78n7r   1/1     Running   0          26h     10.1.32.7    e2etest-4-kaasprod-k8s-local           <none>           <none>
weave-scope-agent-9m4n8   1/1     Running   0          26h     10.1.96.4    master-zone-1-1-1-kaasprod-k8s-local   <none>           <none>
weave-scope-agent-b2gnk   1/1     Running   1          26h     10.1.96.12   master-zone-3-1-1-kaasprod-k8s-local   <none>           <none>
weave-scope-agent-blwtx   1/1     Running   2          26h     10.1.32.20   nodes-z1-1-kaasprod-k8s-local          <none>           <none>
weave-scope-agent-cbhjg   1/1     Running   0          26h     10.1.64.15   e2etest-2-kaasprod-k8s-local           <none>           <none>
weave-scope-agent-csp49   1/1     Running   0          26h     10.1.96.14   e2etest-3-kaasprod-k8s-local           <none>           <none>
weave-scope-agent-g4k2x   1/1     Running   1          26h     10.1.64.10   nodes-z2-2-kaasprod-k8s-local          <none>           <none>
weave-scope-agent-kx85h   1/1     Running   2          26h     10.1.96.6    nodes-z3-1-kaasprod-k8s-local          <none>           <none>
weave-scope-agent-lllqc   0/1     Pending   0          5m56s   <none>       <none>                                 <none>           <none>
weave-scope-agent-nls2h   1/1     Running   0          26h     10.1.96.17   master-zone-2-1-1-kaasprod-k8s-local   <none>           <none>
weave-scope-agent-p8njs   1/1     Running   2          26h     10.1.96.19   nodes-z3-2-kaasprod-k8s-local          <none>           <none>
```

I have tried to restart apiserver/schedulers/controller-managers but it does not help. Also I have tried to restart that single node that is stuck (nodes-z2-1-kaasprod-k8s-local) but it does not help either. Only deleting that node and recreating it helps.

```
% kubectl describe node nodes-z2-1-kaasprod-k8s-local
Name:               nodes-z2-1-kaasprod-k8s-local
Roles:              node
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=59cf4871-de1b-4294-9e9f-2ea7ca4b771f
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=regionOne
                    failure-domain.beta.kubernetes.io/zone=zone-2
                    kops.k8s.io/instancegroup=nodes-z2
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=nodes-z2-1-kaasprod-k8s-local
                    kubernetes.io/os=linux
                    kubernetes.io/role=node
                    node-role.kubernetes.io/node=
                    node.kubernetes.io/instance-type=59cf4871-de1b-4294-9e9f-2ea7ca4b771f
                    topology.cinder.csi.openstack.org/zone=zone-2
                    topology.kubernetes.io/region=regionOne
                    topology.kubernetes.io/zone=zone-2
Annotations:        csi.volume.kubernetes.io/nodeid: {"cinder.csi.openstack.org":"faf14d22-010f-494a-9b34-888bdad1d2df"}
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.1.64.32/19
                    projectcalico.org/IPv4IPIPTunnelAddr: 100.98.136.0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 28 May 2020 13:28:24 +0300
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  nodes-z2-1-kaasprod-k8s-local
  AcquireTime:     <unset>
  RenewTime:       Sat, 30 May 2020 12:02:13 +0300
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Fri, 29 May 2020 09:40:51 +0300   Fri, 29 May 2020 09:40:51 +0300   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Sat, 30 May 2020 11:59:53 +0300   Fri, 29 May 2020 09:40:45 +0300   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Sat, 30 May 2020 11:59:53 +0300   Fri, 29 May 2020 09:40:45 +0300   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Sat, 30 May 2020 11:59:53 +0300   Fri, 29 May 2020 09:40:45 +0300   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Sat, 30 May 2020 11:59:53 +0300   Fri, 29 May 2020 09:40:45 +0300   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.1.64.32
  Hostname:    nodes-z2-1-kaasprod-k8s-local
Capacity:
  cpu:                4
  ephemeral-storage:  10287360Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8172420Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  9480830961
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8070020Ki
  pods:               110
System Info:
  Machine ID:                 c94284656ff04cf090852c1ddee7bcc2
  System UUID:                faf14d22-010f-494a-9b34-888bdad1d2df
  Boot ID:                    295dc3d9-0a90-49ee-92f3-9be45f2f8e3d
  Kernel Version:             4.19.0-8-cloud-amd64
  OS Image:                   Debian GNU/Linux 10 (buster)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.8
  Kubelet Version:            v1.18.3
  Kube-Proxy Version:         v1.18.3
PodCIDR:                      100.96.12.0/24
PodCIDRs:                     100.96.12.0/24
ProviderID:                   openstack:///faf14d22-010f-494a-9b34-888bdad1d2df
Non-terminated Pods:          (3 in total)
  Namespace                   Name                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                        ------------  ----------  ---------------  -------------  ---
  kube-system                 calico-node-77pqs                           100m (2%)     200m (5%)   100Mi (1%)       100Mi (1%)     46h
  kube-system                 kube-proxy-nodes-z2-1-kaasprod-k8s-local    100m (2%)     200m (5%)   100Mi (1%)       100Mi (1%)     46h
  volume                      csi-cinder-nodeplugin-5jbvl                 100m (2%)     400m (10%)  200Mi (2%)       200Mi (2%)     46h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                300m (7%)   800m (20%)
  memory             400Mi (5%)  400Mi (5%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:
  Type    Reason                   Age    From                                    Message
  ----    ------                   ----   ----                                    -------
  Normal  Starting                 7m27s  kubelet, nodes-z2-1-kaasprod-k8s-local  Starting kubelet.
  Normal  NodeHasSufficientMemory  7m26s  kubelet, nodes-z2-1-kaasprod-k8s-local  Node nodes-z2-1-kaasprod-k8s-local status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    7m26s  kubelet, nodes-z2-1-kaasprod-k8s-local  Node nodes-z2-1-kaasprod-k8s-local status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     7m26s  kubelet, nodes-z2-1-kaasprod-k8s-local  Node nodes-z2-1-kaasprod-k8s-local status is now: NodeHasSufficientPID
  Normal  NodeAllocatableEnforced  7m26s  kubelet, nodes-z2-1-kaasprod-k8s-local  Updated Node Allocatable limit across pods
```

We are seeing this randomly in all of our clusters.

**What you expected to happen**: I expect that daemonset will provision to all nodes.

**How to reproduce it (as minimally and precisely as possible)**: No idea really, install 1.18.x kubernetes and deploy daemonset and after that wait days(?)

**Anything else we need to know?**: When this happens we cannot provision any other daemonsets to that node either. Like you can see logging fluent-bit is also missing. I cannot see any errors in that node kubelet logs and like said, restarting does not help.

```
% kubectl get ds --all-namespaces
NAMESPACE     NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
falco         falco-daemonset            13        13        12      13           12          <none>                            337d
kube-system   audit-webhook-deployment   3         3         3       3            3           node-role.kubernetes.io/master=   174d
kube-system   calico-node                13        13        13      13           13          kubernetes.io/os=linux            36d
kube-system   kops-controller            3         3         3       3            3           node-role.kubernetes.io/master=   193d
kube-system   metricbeat                 6         6         5       6            5           <none>                            35d
kube-system   openstack-cloud-provider   3         3         3       3            3           node-role.kubernetes.io/master=   337d
logging       fluent-bit                 13        13        12      13           12          <none>                            337d
monitoring    node-exporter              13        13        12      13           12          kubernetes.io/os=linux            58d
volume        csi-cinder-nodeplugin      6         6         6       6            6           <none>                            239d
weave         weave-scope-agent          13        13        12      13           12          <none>                            193d
weave         weavescope-iowait-plugin   6         6         5       6            5           <none>                            193d
```

Like you can see, most of the daemonsets are missing one pod

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.3
- Cloud provider or hardware configuration: openstack
- OS (e.g: `cat /etc/os-release`): debian buster
- Kernel (e.g. `uname -a`): Linux nodes-z2-1-kaasprod-k8s-local 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
- Install tools: kops
- Network plugin and version (if this is a network-related bug): calico
- Others:

### PR DESCRIPTION
**Pull request by maelk**
**What type of PR is this?**

/kind cleanup
/sig scheduling

**What this PR does / why we need it**:

This commit transforms the next() function of the scheduler node
tree into a listNodes() function that directly returns a list of
nodes, going through the zones in a round-robin fashion. This
removes the flawed logic of the next() function.

**Which issue(s) this PR fixes**:

Fixes #91601 

**Special notes for your reviewer**:

This PR does some cleanup after the bug hotfix, to remove the possibility of such bug happening again

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maelk** [comment]
@ahg-g and @alculquicondor Here is a first attempt at the refactoring of the next() function we discussed on the issue. Please take a look.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 1]
```diff
@@ -49,8 +51,10 @@ func (na *nodeArray) next() (nodeName string, exhausted bool) {
 		return "", false
 	}
 	if na.lastIndex >= len(na.nodes) {
+		na.exhausted = true
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree.go:54]: could you put this in a method instead? then you don't need to store it as a boolean

File: pkg/scheduler/internal/cache/node_tree_test.go [hunk 2]
```diff
@@ -353,42 +353,42 @@ func TestNodeTree_Next(t *testing.T) {
...
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
 			nt := newNodeTree(test.nodesToAdd)
 
-			var output []string
-			for i := 0; i < test.numRuns; i++ {
-				output = append(output, nt.next())
+			_, err := nt.listNodes()
+			if err != nil {
+				t.Errorf("Unexpected error : %v", err.Error())
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree_test.go:386]: Use Fatalf when the test can't continue.

File: pkg/scheduler/internal/cache/node_tree_test.go [hunk 3]
```diff
@@ -353,42 +353,42 @@ func TestNodeTree_Next(t *testing.T) {
...
+			}
+			// Run it twice to make sure there is no interferences
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree_test.go:388]: Could you elaborate? I don't think we should be doing this.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 4]
```diff
@@ -41,6 +42,7 @@ type nodeTree struct {
 type nodeArray struct {
 	nodes     []string
 	lastIndex int
+	exhausted bool
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/node_tree.go:45]: I feel think we don't need private fields (`index` as well as `exhausted`) anymore to record the "state", as the listNode() can serve as a stateless function.

`nodeTree` can be simplified a lot, maybe a simple `map[string][]string` is enough. We just iterator the `nodeTree` like the Python `zip()` function like this: https://play.golang.org/p/g4kmgbFp2_X.

With this, if needed, we even can return the nodes on demand. Just like Python `for ... in xrange` vs. `for ... in range`.

**Review by Huang-Wei — COMMENTED** [review]
I feel like the `listNodes()` is qualified to serve in a stateless manner now. Some comments below.

File: pkg/scheduler/internal/cache/node_tree.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/node_tree.go:45]: I like the simplification, but we better don't introduce intermediate lists. We should just be returning a single list. Or a single element, but that's actually the implementation before this PR that we want to get rid of.

Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go:45]: I was also expecting that all state related to node iteration be removed, but also without intermediate lists, here is an example: https://play.golang.org/p/6Mf9OrMJCnn

Comment (alculquicondor) [reply pkg/scheduler/internal/cache/node_tree.go:45]: aren't 2 nested loops, like proposed in this PR, minus the state, more readable?

Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go:45]: I feel that both just as readable, note that we only need the `list` and `next` functions, and both seem  straightforward.

**Comment by maelk** [comment]
Thank you for all the comments. I have taken ideas from all to simplify as much as possible and keep it easily readable. What do you think of the new version ?

File: pkg/scheduler/internal/cache/node_tree.go [hunk 5]
```diff
@@ -135,36 +121,32 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
-		// that if more nodes are added to a zone after it is exhausted, we iterate over the new nodes.
-		nodeName, exhausted := nt.tree[zone].next()
-		if exhausted {
-			numExhaustedZones++
-			if numExhaustedZones >= len(nt.zones) { // all zones are exhausted. we should reset.
-				nt.resetExhausted()
+	allocatedNodes := 0
+	nodeIndex := 0
+	for allocatedNodes < nt.numNodes {
+		for zoneIndex := 0; zoneIndex < len(nt.zones); zoneIndex++ {
```
Comment (ahg-g) [inline pkg/scheduler/internal/cache/node_tree.go:135]: This doesn't sound correct to me, we need to start from the last used zone, not from zoneIndex=0.

Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go:135]: with this loop, we iterate over all the zones, adding a node from each non exhausted loop until we have gone through all the zones. then we go through the loop again. The change did not modify the output of the list() function. 

Or do you mean to say that a new run of list() should pick up from where the last list() run ended ?

Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go:135]: ah, ok, I missed that the append happens inside the zone loop.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 6]
```diff
@@ -135,36 +139,39 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
 
-func (nt *nodeTree) resetExhausted() {
-	for _, na := range nt.tree {
-		na.lastIndex = 0
-	}
-	nt.zoneIndex = 0
-}
-
-// next returns the name of the next node. NodeTree iterates over zones and in each zone iterates
+// listNodes returns the list of namesof the node. NodeTree iterates over zones and in each zone iterates
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/node_tree.go:124]: "list" now

File: pkg/scheduler/internal/cache/node_tree.go [hunk 7]
```diff
@@ -135,36 +121,32 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
 // over nodes in a round robin fashion.
-func (nt *nodeTree) next() string {
+func (nt *nodeTree) list() ([]string, error) {
+	nodesList := make([]string, 0, nt.numNodes)
 	if len(nt.zones) == 0 {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree.go:128]: nit: `return nil, nil`, before making the allocation in the line before.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 8]
```diff
@@ -19,7 +19,8 @@ package cache
 import (
 	"fmt"
 
-	"k8s.io/api/core/v1"
+	"github.com/pkg/errors"
```
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go:22]: can you address this as well please

File: pkg/scheduler/internal/cache/node_tree.go [hunk 9]
```diff
@@ -135,36 +121,32 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
-		nodeName, exhausted := nt.tree[zone].next()
-		if exhausted {
-			numExhaustedZones++
-			if numExhaustedZones >= len(nt.zones) { // all zones are exhausted. we should reset.
-				nt.resetExhausted()
+	allocatedNodes := 0
+	nodeIndex := 0
+	for allocatedNodes < nt.numNodes {
+		for zoneIndex := 0; zoneIndex < len(nt.zones); zoneIndex++ {
+			zone := nt.zones[zoneIndex]
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree.go:136]: `zone := nt.tree[nt.zones[zoneIndex]]` so that we avoid extra map accesses

File: pkg/scheduler/internal/cache/cache_test.go [hunk 10]
```diff
@@ -1090,7 +1090,11 @@ func TestNodeOperators(t *testing.T) {
 			if !found {
 				t.Errorf("Failed to find node %v in internalcache.", node.Name)
 			}
-			if cache.nodeTree.numNodes != 1 || cache.nodeTree.next() != node.Name {
+			nodesList, err := cache.nodeTree.list()
+			if err != nil {
+				t.Errorf("Unexpected error :%v", err.Error())
```
Comment (ahg-g) [inline pkg/scheduler/internal/cache/cache_test.go:1095]: lets use Fatal for this.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 11]
```diff
@@ -1510,8 +1522,11 @@ func compareCacheWithNodeInfoSnapshot(cache *schedulerCache, snapshot *Snapshot)
 
 	expectedNodeInfoList := make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
 	expectedHavePodsWithAffinityNodeInfoList := make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
-	for i := 0; i < cache.nodeTree.numNodes; i++ {
-		nodeName := cache.nodeTree.next()
+	nodesList, err := cache.nodeTree.list()
+	if err != nil {
+		return fmt.Errorf("Unexpected error : %v", err.Error())
```
Comment (ahg-g) [inline pkg/scheduler/internal/cache/cache_test.go:1527]: Fatal for this as well pls.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 12]
```diff
@@ -135,36 +121,32 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
+				}
+				continue
 			}
-		} else {
-			return nodeName
+			nodesList = append(nodesList, nt.tree[zone].nodes[nodeIndex])
+			allocatedNodes++
+		}
+		nodeIndex++
+		if numExhaustedZones >= len(nt.zones) { // all zones are exhausted.
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree.go:147]: given the implementation, I think it's possible this is true, when we have already reached `allocatedNodes = nt.numNodes`.

Maybe just move it to the beginning of the loop (below `for allocatedNodes < nt.NumNodes`)

File: pkg/scheduler/internal/cache/node_tree.go [hunk 13]
```diff
@@ -135,36 +121,32 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
-		zone := nt.zones[nt.zoneIndex]
-		nt.zoneIndex++
-		// We do not check the exhausted zones before calling next() on the zone. This ensures
-		// that if more nodes are added to a zone after it is exhausted, we iterate over the new nodes.
-		nodeName, exhausted := nt.tree[zone].next()
-		if exhausted {
-			numExhaustedZones++
-			if numExhaustedZones >= len(nt.zones) { // all zones are exhausted. we should reset.
-				nt.resetExhausted()
+	allocatedNodes := 0
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/node_tree.go:132]: `len(nodesList)` should be enough.

**Review by ahg-g — COMMENTED** [review]
Thanks, the logic looks good to me.

File: pkg/scheduler/internal/cache/cache_test.go (hunk 11 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache_test.go:1527]: This is fmt, it is supposed to return an error.

File: pkg/scheduler/internal/cache/node_tree.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go]: done, sorry

File: pkg/scheduler/internal/cache/node_tree.go (hunk 7 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go:127]: should it return nil or an empty list ?

File: pkg/scheduler/internal/cache/node_tree.go (hunk 12 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go]: good catch, thank you

Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go]: UT didn't catch that?

File: pkg/scheduler/internal/cache/node_tree.go (hunk 7 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/node_tree.go:127]: nil is equivalent to empty list

File: pkg/scheduler/internal/cache/cache_test.go [hunk 14]
```diff
@@ -1090,7 +1090,11 @@ func TestNodeOperators(t *testing.T) {
 			if !found {
 				t.Errorf("Failed to find node %v in internalcache.", node.Name)
 			}
-			if cache.nodeTree.numNodes != 1 || cache.nodeTree.next() != node.Name {
+			nodesList, err := cache.nodeTree.list()
+			if err != nil {
+				t.Fatalf("Unexpected error :%v", err.Error())
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1095]: nit: no need for "unexpected error", that's what Fatal is for :)

File: pkg/scheduler/internal/cache/cache_test.go (hunk 11 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache_test.go:1527]: You can pass `testing.T` as an argument

File: pkg/scheduler/internal/cache/node_tree.go (hunk 7 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go:127]: fixed, thanks

File: pkg/scheduler/internal/cache/cache_test.go (hunk 11 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache_test.go]: done, thank you

File: pkg/scheduler/internal/cache/node_tree.go (hunk 12 above)
Comment (ahg-g) [reply pkg/scheduler/internal/cache/node_tree.go]: >UT didn't catch that? if not, we should add one.

ping on this.

File: pkg/scheduler/internal/cache/node_tree_test.go [hunk 15]
```diff
@@ -406,39 +410,39 @@ func TestNodeTreeMultiOperations(t *testing.T) {
...
 			nodesToRemove:  nil,
-			operations:     []string{"add", "add", "add", "add", "add", "next", "next", "next", "next", "add", "next", "next", "next"},
-			expectedOutput: []string{"node-4", "node-6", "node-7", "node-8", "node-3", "node-4", "node-6"},
+			operations:     []string{"add", "add", "add", "add", "add", "add"},
+			expectedOutput: []string{"node-4", "node-6", "node-3", "node-7", "node-8"},
 		},
 		{
-			name:           "remove zone and add new to ensure exhausted is reset correctly",
+			name:           "remove zone and add new",
 			nodesToAdd:     append(allNodes[3:5], allNodes[6:8]...),
```
Comment (soulxu) [inline pkg/scheduler/internal/cache/node_tree_test.go:442]: I found this is a wrong usage for the append. It will modify the variable 'allNodes' directly. After this line, the 'node-5' is removed from the 'allNodes'. We should copy the data from allNodes, not modify the allNodes directly. I submit a patch for it https://github.com/kubernetes/kubernetes/pull/93516.

Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree_test.go:442]: thanks. The two PRs will conflict though. Should we first merge this one and fix the conflict / rebase yours on top, or reverse ?

Comment (soulxu) [reply pkg/scheduler/internal/cache/node_tree_test.go:442]: @Maelk, np! I'm ok with both way, I'm a little prefer to merge https://github.com/kubernetes/kubernetes/pull/93516 first, since it makes this patch's unittests are more clear for the reviewers. But I'm really ok for any way, just let us see what is the preference from the reviewers.

File: pkg/scheduler/internal/cache/cache.go [hunk 16]
```diff
@@ -280,9 +280,11 @@ func (cache *schedulerCache) updateNodeInfoSnapshotList(snapshot *Snapshot, upda
...
 		// Take a snapshot of the nodes order in the tree
 		snapshot.nodeInfoList = make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
-		cache.nodeTree.resetExhausted()
-		for i := 0; i < cache.nodeTree.numNodes; i++ {
-			nodeName := cache.nodeTree.next()
+		nodesList, err := cache.nodeTree.list()
+		if err != nil {
+			klog.Error(err.Error())
+		}
+		for _, nodeName := range nodesList {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:287]: whether the loop against `nodesList` here is needed when you get a error from `cache.nodeTree.list()`?

File: pkg/scheduler/internal/cache/cache.go [hunk 17]
```diff
@@ -280,9 +280,11 @@ func (cache *schedulerCache) updateNodeInfoSnapshotList(snapshot *Snapshot, upda
 	if updateAll {
 		// Take a snapshot of the nodes order in the tree
 		snapshot.nodeInfoList = make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
-		cache.nodeTree.resetExhausted()
-		for i := 0; i < cache.nodeTree.numNodes; i++ {
-			nodeName := cache.nodeTree.next()
+		nodesList, err := cache.nodeTree.list()
+		if err != nil {
+			klog.Error(err.Error())
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:285]: change this to `Fatal` to align with what you did in the `cache_test.go`?

File: pkg/scheduler/internal/cache/cache.go (hunk 16 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache.go:287]: The idea was that an error in listing the node would not fully prevent the scheduler to work properly, it would work with whatever partial list of nodes it got, and log an error to not let it go unnoticed. Is that problematic ?

File: pkg/scheduler/internal/cache/cache.go (hunk 17 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache.go:285]: because it is not actually fatal for the scheduler run. It is fatal in the tests as it should not happen at all, but for the logging, from the user perspective, it should not be fatal for the scheduler, and not perceived as such. It just means we got less nodes than we expected.

Comment (chendave) [reply pkg/scheduler/internal/cache/cache.go:285]: Go you, thank!

File: pkg/scheduler/internal/cache/cache.go (hunk 16 above)
Comment (chendave) [reply pkg/scheduler/internal/cache/cache.go:287]: sound good, thank for the response.

File: pkg/scheduler/internal/cache/node_tree_test.go (hunk 15 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/node_tree_test.go:442]: Note that we are in freeze. But I'm also inclined to merge #93516 first.

Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree_test.go:442]: ok, let's proceed with the other one first then.

File: pkg/scheduler/internal/cache/node_tree.go [hunk 18]
```diff
@@ -29,31 +30,16 @@ import (
...
-		klog.Error("The nodeArray is empty. It should have been deleted from NodeTree.")
-		return "", false
-	}
-	if na.lastIndex >= len(na.nodes) {
-		return "", true
-	}
-	nodeName = na.nodes[na.lastIndex]
-	na.lastIndex++
-	return nodeName, false
+	nodes []string
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/node_tree.go:42]: I'd like to define `nodeTree.tree` as `map[string][]string`, so `nodeArray` can be eliminated.

File: pkg/scheduler/internal/cache/cache.go (hunk 17 above)
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:285]: nit: (applies elsewhere)

```suggestion
			klog.Error(err)
```

File: pkg/scheduler/internal/cache/node_tree.go [hunk 19]
```diff
@@ -135,36 +121,30 @@ func (nt *nodeTree) updateNode(old, new *v1.Node) {
...
 	}
+	nodesList := make([]string, 0, nt.numNodes)
 	numExhaustedZones := 0
-	for {
-		if nt.zoneIndex >= len(nt.zones) {
-			nt.zoneIndex = 0
+	nodeIndex := 0
+	for len(nodesList) < nt.numNodes {
+		if numExhaustedZones >= len(nt.zones) { // all zones are exhausted.
+			return nodesList, errors.New("All zones exhausted before reaching count of nodes expected")
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/node_tree.go:135]: Error string usually not start with a capitalized letter:

```suggestion
			return nodesList, errors.New("all zones exhausted before reaching count of nodes expected")
```

File: pkg/scheduler/internal/cache/cache.go (hunk 17 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache.go]: I only found this occurence. which elsewhere are you referring to ? would you mind clarifying ?

File: pkg/scheduler/internal/cache/node_tree.go (hunk 18 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/node_tree.go]: done, thank you

File: pkg/scheduler/internal/cache/cache.go (hunk 17 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go]: I noticed the other occurrences in *_test.go.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 20]
```diff
@@ -1090,7 +1090,11 @@ func TestNodeOperators(t *testing.T) {
 			if !found {
 				t.Errorf("Failed to find node %v in internalcache.", node.Name)
 			}
-			if cache.nodeTree.numNodes != 1 || cache.nodeTree.next() != node.Name {
+			nodesList, err := cache.nodeTree.list()
+			if err != nil {
+				t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache_test.go:1095]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 21]
```diff
@@ -1134,7 +1138,11 @@ func TestNodeOperators(t *testing.T) {
 				t.Errorf("Failed to update node in schedulertypes:\n got: %+v \nexpected: %+v", got, expected)
 			}
 			// Check nodeTree after update
-			if cache.nodeTree.numNodes != 1 || cache.nodeTree.next() != node.Name {
+			nodesList, err = cache.nodeTree.list()
+			if err != nil {
+				t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache_test.go:1143]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 22]
```diff
@@ -1146,7 +1154,11 @@ func TestNodeOperators(t *testing.T) {
 				t.Errorf("The node %v should be removed.", node.Name)
 			}
 			// Check node is removed from nodeTree as well.
-			if cache.nodeTree.numNodes != 0 || cache.nodeTree.next() != "" {
+			nodesList, err = cache.nodeTree.list()
+			if err != nil {
+				t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache_test.go:1159]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 23]
```diff
@@ -1510,8 +1522,11 @@ func compareCacheWithNodeInfoSnapshot(cache *schedulerCache, snapshot *Snapshot)
 
 	expectedNodeInfoList := make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
 	expectedHavePodsWithAffinityNodeInfoList := make([]*framework.NodeInfo, 0, cache.nodeTree.numNodes)
-	for i := 0; i < cache.nodeTree.numNodes; i++ {
-		nodeName := cache.nodeTree.next()
+	nodesList, err := cache.nodeTree.list()
+	if err != nil {
+		t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache_test.go:1527]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

File: pkg/scheduler/internal/cache/node_tree_test.go [hunk 24]
```diff
@@ -349,46 +349,41 @@ func TestNodeTree_UpdateNode(t *testing.T) {
...
 	for _, test := range tests {
 		t.Run(test.name, func(t *testing.T) {
 			nt := newNodeTree(test.nodesToAdd)
 
-			var output []string
-			for i := 0; i < test.numRuns; i++ {
-				output = append(output, nt.next())
+			output, err := nt.list()
+			if err != nil {
+				t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/node_tree_test.go:386]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

File: pkg/scheduler/internal/cache/node_tree_test.go [hunk 25]
```diff
@@ -464,12 +467,14 @@ func TestNodeTreeMultiOperations(t *testing.T) {
...
 					}
-				case "next":
-					output = append(output, nt.next())
 				default:
 					t.Errorf("unknow operation: %v", op)
 				}
 			}
+			output, err := nt.list()
+			if err != nil {
+				t.Fatalf(err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/node_tree_test.go:476]: > Re https://github.com/kubernetes/kubernetes/pull/93473#discussion_r463735426

Here is one.

**Comment by maelk** [comment]
I am currently out of office, but I will take care of the rebase and fixes on the 10th

File: pkg/scheduler/internal/cache/cache_test.go (hunk 20 above)
Comment (maelk) [reply pkg/scheduler/internal/cache/cache_test.go:1095]: ah ok, I didn't get what you meant sorry, I changed this to t.Fatal(err)

**Comment by Huang-Wei** [comment]
Thanks!

/lgtm
/approve

**Comment by maelk** [comment]
@alculquicondor and @ahg-g How does this look to you ? 
On a side note, it seems to be missing the milestone, if any of you have the rights to set it, please do.

**Comment by ahg-g** [comment]
This will go in once the master branch is open, it doesn't need a milestone. Hopefully it will open on the 25th when 1.19 is released.

**Comment by borgerli** [comment]
@maelk 
Does this PR fix the same issue as  [PR93355](https://github.com/kubernetes/kubernetes/pull/93355), and replace that PR?  Thanks!

**Comment by alculquicondor** [comment]
Yes, it's a more robust fix
