### PR TITLE
[v1.16.1] TokenCleaner#evalSecret should enqueue the key

### LINKED ISSUE #82854: [v1.16.1] Panic in controller manager
**What happened**:

Recent installation of 1.16 kubernetes using kubeadm, controller manager panics frequently

```golang
E0919 03:22:37.000231       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x38d8420), concrete:(*runtime._type)(0x4171300), asserted:(*runtime._type)(0x371f240), missingMethod:""} (interface conversion: interface {} is *v1.Secret, not string)
goroutine 1485 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a23160, 0xc0019b5350)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3a23160, 0xc0019b5350)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).processNextWorkItem(0xc000a8bc20, 0xc0000c5100)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:152 +0x2c9
k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).worker(0xc000a8bc20)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:140 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00140c370)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00140c370, 0x2540be400, 0x0, 0x45d201, 0xc000282840)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00140c370, 0x2540be400, 0xc000282840)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/pkg/controller/bootstrap.(*TokenCleaner).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/bootstrap/tokencleaner.go:124 +0x1d0
panic: interface conversion: interface {} is *v1.Secret, not string [recovered]
	panic: interface conversion: interface {} is *v1.Secret, not string
```

**What you expected to happen**:

Expect controller manager to run with no panics

**How to reproduce it (as minimally and precisely as possible)**:

install 1.16 cluster using kubeadm

**Anything else we need to know?**:

None

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`): ubuntu 18
- Kernel (e.g. `uname -a`): 5.0.0-1018-azure
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes the panic reported in #82854
```
runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x38d8420), concrete:(*runtime._type)(0x4171300), asserted:(*runtime._type)(0x371f240), missingMethod:""} (interface conversion: interface {} is *v1.Secret, not string)
```

**Which issue(s) this PR fixes**:
xref #82854

```release-note
Fixes a panic in kube-controller-manager cleaning up bootstrap tokens
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/bootstrap/tokencleaner.go [hunk 1]
```diff
@@ -149,7 +149,11 @@ func (tc *TokenCleaner) processNextWorkItem() bool {
 	}
 	defer tc.queue.Done(key)
 
-	if err := tc.syncFunc(key.(string)); err != nil {
+	if secret, ok := key.(*v1.Secret); ok {
```
Comment (liggitt) [inline pkg/controller/bootstrap/tokencleaner.go]: this is not correct. only strings should be added to the queue

Comment (liggitt) [reply pkg/controller/bootstrap/tokencleaner.go]: this line should be fixed (the evalSecret method should take the key and requeue it, not enqueue the secret):
```
tc.queue.AddAfter(o, ttl)
```

we also need a test exercising processing the queue after enqueueing because of a ttl

cc @zjj2wry

Comment (tedyu) [reply pkg/controller/bootstrap/tokencleaner.go]: evalSecret checks whether the secret has expired. If not, it enqueues it with ttl.

Comment (liggitt) [reply pkg/controller/bootstrap/tokencleaner.go]: correct, but it should enqueue the key, not the secret

**Comment by liggitt** [comment]
this change will exercise the requeue code:
```diff
diff --git a/pkg/controller/bootstrap/tokencleaner_test.go b/pkg/controller/bootstrap/tokencleaner_test.go
index 6eea6321ba0..df56ea8a86c 100644
--- a/pkg/controller/bootstrap/tokencleaner_test.go
+++ b/pkg/controller/bootstrap/tokencleaner_test.go
@@ -110,10 +110,11 @@ func TestCleanerExpiredAt(t *testing.T) {

        secret := newTokenSecret("tokenID", "tokenSecret")
        addSecretExpiration(secret, timeString(2*time.Second))
+       secrets.Informer().GetIndexer().Add(secret)
+       cleaner.enqueueSecrets(secret)
        expected := []core.Action{}
        verifyFunc := func() {
-               secrets.Informer().GetIndexer().Add(secret)
-               cleaner.evalSecret(secret)
+               cleaner.processNextWorkItem()
                verifyActions(t, expected, cl.Actions())
        }
        // token has not expired currently
```

**Comment by tedyu** [comment]
Thanks for the test change suggestion, @liggitt 

Please take another look.

**Comment by liggitt** [comment]
/lgtm
/approve

go ahead and open the cherry-pick to release-1.16

**Comment by tedyu** [comment]
#82888 had too many changes.
I used this command:

GITHUB_USER=yutedz hack/cherry_pick_pull.sh upstream/release-1.16 82887
