### PR TITLE
fix bug not check error before defer conn.Close()

### LINKED ISSUE #68335: Wrong position of defer
/kind bug
/sig release
when we use `defer xxx.close()`, we must make sure xxx is not nil. So before we use it, we should check err value first.

Such as:
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/util/mount/mount_linux.go#L409
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/pkg/kubelet/network/dns/dns.go#L395
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/staging/src/k8s.io/client-go/tools/clientcmd/validation.go#L188
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/staging/src/k8s.io/client-go/tools/clientcmd/validation.go#L226
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/staging/src/k8s.io/client-go/tools/clientcmd/validation.go#L233
https://github.com/kubernetes/kubernetes/blob/4bc9e94feec17d1980e733a08699255482d15f4e/test/images/netexec/netexec.go#L360

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
fix bug not checkou err before defer conn.Close()

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68335

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/images/netexec/netexec.go [hunk 1]
```diff
@@ -357,6 +357,10 @@ func startUDPServer(udpPort int) {
 	serverAddress, err := net.ResolveUDPAddr("udp", fmt.Sprintf(":%d", udpPort))
 	assertNoError(err)
 	serverConn, err := net.ListenUDP("udp", serverAddress)
+	if err != nil {
+		assertNoError(err)
+		return
```
Comment (dixudx) [inline test/images/netexec/netexec.go]: `return` is not needed here, which will not be run.

Comment (wgliang) [reply test/images/netexec/netexec.go]: Oh, I didn't notice log.Fatal(), thank you for the review.

Comment (qzyse2017) [reply test/images/netexec/netexec.go]: Seems ```assertNoError(err)```  is just enough?

Comment (wgliang) [reply test/images/netexec/netexec.go]: sure

**Comment by ixdy** [comment]
maybe update `test/images/netexec/VERSION` too?

**Comment by wgliang** [comment]
@ixdy 
What are the rules or instructions for the update of test/images/netexec/VERSION? I did not find the relevant information.

**Comment by spiffxp** [comment]
bump version to 1.1 and update tests to use that new version?

**Comment by spiffxp** [comment]
I still see netexec 1.0 referenced in a few places, such as `test/utils/image/manifest.go` and `test/images/netexec/pod.yaml`

**Comment by wgliang** [comment]
@spiffxp  
I want to know, is there a script that updates the version information?

**Comment by spiffxp** [comment]
@wgliang as far as I know it's all done manually, I'm not aware of a script to do this

**Comment by wgliang** [comment]
@spiffxp 
Ok, got it. Thanks. I will manually modify the relevant files.

**Comment by wgliang** [comment]
Maybe we should update the image of https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/netexec?gcrImageListsize=50
update one image lable as 1.1
@spiffxp 
How to do it? It seems that I don't have permission.

**Comment by spiffxp** [comment]
Unfortunately AFAIK this still needs to be done manually by someone with access.  Fortunately I am one of those people.

Making sure it builds
```
spiffxp@spiffxp-macbookpro:images (fixbug/handle-close-not-check-err %)$ make all WHAT=netexec
./image-util.sh build netexec
Building image for netexec ARCH: amd64...
../image-util.sh bin netexec
Unable to find image 'golang:1.10.3' locally
1.10.3: Pulling from library/golang
55cbf04beb70: Pull complete
1607093a898c: Pull complete
9a8ea045c926: Pull complete
d4eee24d4dac: Pull complete
9c35c9787a2f: Pull complete
6a66653f6388: Pull complete
102f6b19f797: Pull complete
Digest: sha256:3c54fa85d6262d2ef7695ee2f8793f1f4f9809ce4a08ca2e213235ef4cfdcb66
Status: Downloaded newer image for golang:1.10.3
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.sMg86z ~/w/kubernetes/kubernetes/test/images
Sending build context to Docker daemon  5.573MB
Step 1/6 : FROM busybox
latest: Pulling from library/busybox
90e01955edcd: Pull complete
Digest: sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
Status: Downloaded newer image for busybox:latest
 ---> 59788edf1f3e
Step 2/6 : ADD netexec netexec
 ---> e01bfe663019
Step 3/6 : EXPOSE 8080
 ---> Running in 4a2a19bd3555
Removing intermediate container 4a2a19bd3555
 ---> 7d589b4a3256
Step 4/6 : EXPOSE 8081
 ---> Running in f63cd7834d02
Removing intermediate container f63cd7834d02
 ---> ce77e40653f6
Step 5/6 : RUN mkdir /uploads
 ---> Running in 1c6487528a59
Removing intermediate container 1c6487528a59
 ---> 578b0381ad84
Step 6/6 : ENTRYPOINT ["/netexec"]
 ---> Running in 64b296305512
Removing intermediate container 64b296305512
 ---> 6fdf724405da
Successfully built 6fdf724405da
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-amd64:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: arm...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.LNQtLo ~/w/kubernetes/kubernetes/test/images
Unable to find image 'multiarch/qemu-user-static:register' locally
register: Pulling from multiarch/qemu-user-static
8c5a7da1afbc: Already exists
a3c4e765880e: Pull complete
c5b8d71a345e: Pull complete
Digest: sha256:8ce841fa89e779be4ef78aa866a5fc1adcefce3210f59b928d2b120f87cc4641
Status: Downloaded newer image for multiarch/qemu-user-static:register
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  8.224MB
Step 1/7 : FROM arm32v6/busybox
latest: Pulling from arm32v6/busybox
98dadc80d278: Pull complete
Digest: sha256:d4ae670481a474fda03b2e026a111972a5f459b86e0c57af1ec72d6045f57a27
Status: Downloaded newer image for arm32v6/busybox:latest
 ---> edc53726e077
Step 2/7 : COPY qemu-arm-static /usr/bin/
 ---> 983a75e000ad
Step 3/7 : ADD netexec netexec
 ---> ff3a06bdd200
Step 4/7 : EXPOSE 8080
 ---> Running in e95a3d708871
Removing intermediate container e95a3d708871
 ---> 2c1d327f422e
Step 5/7 : EXPOSE 8081
 ---> Running in c54e80effcc0
Removing intermediate container c54e80effcc0
 ---> c745debc9281
Step 6/7 : RUN mkdir /uploads
 ---> Running in 3bcaf967c4ec
Removing intermediate container 3bcaf967c4ec
 ---> 3f215819f6c0
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Running in 1f38fa432f45
Removing intermediate container 1f38fa432f45
 ---> ef482e1e5218
Successfully built ef482e1e5218
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-arm:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: arm64...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.DdgpgT ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  8.902MB
Step 1/7 : FROM arm64v8/busybox
latest: Pulling from arm64v8/busybox
acafde7ce2e7: Pull complete
Digest: sha256:adeafb67bdeab6f8ab07a46bc7b789d9ae508aac3b0933fb165e3ceb1f36e3e2
Status: Downloaded newer image for arm64v8/busybox:latest
 ---> 0de9620ecdd2
Step 2/7 : COPY qemu-aarch64-static /usr/bin/
 ---> 6c57dee9385a
Step 3/7 : ADD netexec netexec
 ---> db99102b91fb
Step 4/7 : EXPOSE 8080
 ---> Running in f72a96d8dbf8
Removing intermediate container f72a96d8dbf8
 ---> 15ec7489c7b3
Step 5/7 : EXPOSE 8081
 ---> Running in 343a3bc274e1
Removing intermediate container 343a3bc274e1
 ---> 9d2563fb1d1d
Step 6/7 : RUN mkdir /uploads
 ---> Running in 97b5d071de56
Removing intermediate container 97b5d071de56
 ---> 3ff360d63ec8
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Running in 2c1c5d1a0ccb
Removing intermediate container 2c1c5d1a0ccb
 ---> 9084dbb64936
Successfully built 9084dbb64936
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-arm64:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: ppc64le...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.2v6IxA ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  9.637MB
Step 1/7 : FROM ppc64le/busybox
latest: Pulling from ppc64le/busybox
4af4b9131647: Pull complete
Digest: sha256:f7d5e9a7fa573052bbce9ad2d59b1c63b848f091a246a8c1e54ccc8178e1b794
Status: Downloaded newer image for ppc64le/busybox:latest
 ---> 613e7cc45e39
Step 2/7 : COPY qemu-ppc64le-static /usr/bin/
 ---> beb4ad60e74f
Step 3/7 : ADD netexec netexec
 ---> 2cc502b0f3d4
Step 4/7 : EXPOSE 8080
 ---> Running in 7433c4e24122
Removing intermediate container 7433c4e24122
 ---> 9fa3e2a0fef9
Step 5/7 : EXPOSE 8081
 ---> Running in 6c21bc810c17
Removing intermediate container 6c21bc810c17
 ---> 93d66fee5ffc
Step 6/7 : RUN mkdir /uploads
 ---> Running in 42f83f1c521b
Removing intermediate container 42f83f1c521b
 ---> c0acab8269be
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Running in 607be877ba99
Removing intermediate container 607be877ba99
 ---> a689fb00b0d6
Successfully built a689fb00b0d6
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-ppc64le:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: s390x...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.vN1Kdc ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  9.015MB
Step 1/7 : FROM s390x/busybox
latest: Pulling from s390x/busybox
827411563e2c: Pull complete
Digest: sha256:d6d388d3ef21f3a75e49606dc0da5ec92da6f181bea347473b7f01904da09175
Status: Downloaded newer image for s390x/busybox:latest
 ---> 03148d60c37a
Step 2/7 : COPY qemu-s390x-static /usr/bin/
 ---> 086cc96c7bb3
Step 3/7 : ADD netexec netexec
 ---> b6e49e083e60
Step 4/7 : EXPOSE 8080
 ---> Running in 4b378f8c6e7f
Removing intermediate container 4b378f8c6e7f
 ---> 8fc571c1d20e
Step 5/7 : EXPOSE 8081
 ---> Running in 5056b6a0b767
Removing intermediate container 5056b6a0b767
 ---> 8ff5df7a385e
Step 6/7 : RUN mkdir /uploads
 ---> Running in 31adf3715aec
Removing intermediate container 31adf3715aec
 ---> d0ad359e265e
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Running in 9adfb7a1aa91
Removing intermediate container 9adfb7a1aa91
 ---> cd0942197c06
Successfully built cd0942197c06
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-s390x:1.1
~/w/kubernetes/kubernetes/test/images
```

Pushing
```
spiffxp@spiffxp-macbookpro:images (fixbug/handle-close-not-check-err %)$ make all-push WHAT=netexec
./image-util.sh build netexec
Building image for netexec ARCH: amd64...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.cwbA8z ~/w/kubernetes/kubernetes/test/images
Sending build context to Docker daemon  5.573MB
Step 1/6 : FROM busybox
latest: Pulling from library/busybox
Digest: sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
Status: Image is up to date for busybox:latest
 ---> 59788edf1f3e
Step 2/6 : ADD netexec netexec
 ---> Using cache
 ---> e01bfe663019
Step 3/6 : EXPOSE 8080
 ---> Using cache
 ---> 7d589b4a3256
Step 4/6 : EXPOSE 8081
 ---> Using cache
 ---> ce77e40653f6
Step 5/6 : RUN mkdir /uploads
 ---> Using cache
 ---> 578b0381ad84
Step 6/6 : ENTRYPOINT ["/netexec"]
 ---> Using cache
 ---> 6fdf724405da
Successfully built 6fdf724405da
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-amd64:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: arm...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.1gbCrX ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  8.224MB
Step 1/7 : FROM arm32v6/busybox
latest: Pulling from arm32v6/busybox
Digest: sha256:d4ae670481a474fda03b2e026a111972a5f459b86e0c57af1ec72d6045f57a27
Status: Image is up to date for arm32v6/busybox:latest
 ---> edc53726e077
Step 2/7 : COPY qemu-arm-static /usr/bin/
 ---> Using cache
 ---> 983a75e000ad
Step 3/7 : ADD netexec netexec
 ---> Using cache
 ---> ff3a06bdd200
Step 4/7 : EXPOSE 8080
 ---> Using cache
 ---> 2c1d327f422e
Step 5/7 : EXPOSE 8081
 ---> Using cache
 ---> c745debc9281
Step 6/7 : RUN mkdir /uploads
 ---> Using cache
 ---> 3f215819f6c0
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Using cache
 ---> ef482e1e5218
Successfully built ef482e1e5218
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-arm:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: arm64...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.S7sBTD ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  8.902MB
Step 1/7 : FROM arm64v8/busybox
latest: Pulling from arm64v8/busybox
Digest: sha256:adeafb67bdeab6f8ab07a46bc7b789d9ae508aac3b0933fb165e3ceb1f36e3e2
Status: Image is up to date for arm64v8/busybox:latest
 ---> 0de9620ecdd2
Step 2/7 : COPY qemu-aarch64-static /usr/bin/
 ---> Using cache
 ---> 6c57dee9385a
Step 3/7 : ADD netexec netexec
 ---> Using cache
 ---> db99102b91fb
Step 4/7 : EXPOSE 8080
 ---> Using cache
 ---> 15ec7489c7b3
Step 5/7 : EXPOSE 8081
 ---> Using cache
 ---> 9d2563fb1d1d
Step 6/7 : RUN mkdir /uploads
 ---> Using cache
 ---> 3ff360d63ec8
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Using cache
 ---> 9084dbb64936
Successfully built 9084dbb64936
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-arm64:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: ppc64le...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.7GyqBI ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  9.637MB
Step 1/7 : FROM ppc64le/busybox
latest: Pulling from ppc64le/busybox
Digest: sha256:f7d5e9a7fa573052bbce9ad2d59b1c63b848f091a246a8c1e54ccc8178e1b794
Status: Image is up to date for ppc64le/busybox:latest
 ---> 613e7cc45e39
Step 2/7 : COPY qemu-ppc64le-static /usr/bin/
 ---> Using cache
 ---> beb4ad60e74f
Step 3/7 : ADD netexec netexec
 ---> Using cache
 ---> 2cc502b0f3d4
Step 4/7 : EXPOSE 8080
 ---> Using cache
 ---> 9fa3e2a0fef9
Step 5/7 : EXPOSE 8081
 ---> Using cache
 ---> 93d66fee5ffc
Step 6/7 : RUN mkdir /uploads
 ---> Using cache
 ---> c0acab8269be
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Using cache
 ---> a689fb00b0d6
Successfully built a689fb00b0d6
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-ppc64le:1.1
~/w/kubernetes/kubernetes/test/images
Building image for netexec ARCH: s390x...
../image-util.sh bin netexec
~/w/go/src/k8s.io/kubernetes/_tmp/test-images-build.dFX7oF ~/w/kubernetes/kubernetes/test/images
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Sending build context to Docker daemon  9.015MB
Step 1/7 : FROM s390x/busybox
latest: Pulling from s390x/busybox
Digest: sha256:d6d388d3ef21f3a75e49606dc0da5ec92da6f181bea347473b7f01904da09175
Status: Image is up to date for s390x/busybox:latest
 ---> 03148d60c37a
Step 2/7 : COPY qemu-s390x-static /usr/bin/
 ---> Using cache
 ---> 086cc96c7bb3
Step 3/7 : ADD netexec netexec
 ---> Using cache
 ---> b6e49e083e60
Step 4/7 : EXPOSE 8080
 ---> Using cache
 ---> 8fc571c1d20e
Step 5/7 : EXPOSE 8081
 ---> Using cache
 ---> 8ff5df7a385e
Step 6/7 : RUN mkdir /uploads
 ---> Using cache
 ---> d0ad359e265e
Step 7/7 : ENTRYPOINT ["/netexec"]
 ---> Using cache
 ---> cd0942197c06
Successfully built cd0942197c06
Successfully tagged gcr.io/kubernetes-e2e-test-images/netexec-s390x:1.1
~/w/kubernetes/kubernetes/test/images
./image-util.sh push netexec
The push refers to repository [gcr.io/kubernetes-e2e-test-images/netexec-amd64]
274641cbc38a: Pushed
dd0aa6eab046: Pushed
8a788232037e: Layer already exists
1.1: digest: sha256:09180b40bf33b8a3018d0b0d462291c9344b47f51e7df12d77a971f35c95354f size: 944
The push refers to repository [gcr.io/kubernetes-e2e-test-images/netexec-arm]
1b788b6a29bb: Pushed
9ff42c1f5053: Pushed
2e11dface710: Pushed
712a9a7b4765: Pushed
1.1: digest: sha256:a8c571d59470aae5cf21b37a724ba2b41f336b7252e0ad053ff20f3f52067e24 size: 1155
The push refers to repository [gcr.io/kubernetes-e2e-test-images/netexec-arm64]
2fc5fb6f5b99: Pushed
77d43427b794: Pushed
49a4625eae37: Pushed
d74829304bab: Pushed
1.1: digest: sha256:2fb678b4bffe4feecd6d423d1d2429619d6baba55df79734b87e5a9e5f502050 size: 1155
The push refers to repository [gcr.io/kubernetes-e2e-test-images/netexec-ppc64le]
c089bf9b95fd: Pushed
664188e7c5da: Pushed
50406dbe0bce: Pushed
a6b05ee58c1c: Pushed
1.1: digest: sha256:99384b27b4f15388f83d538a2688c83bb2e2170aa97f8640f6b15ccb13de3e08 size: 1156
The push refers to repository [gcr.io/kubernetes-e2e-test-images/netexec-s390x]
efb03d2018a2: Pushed
9f307bb68102: Pushed
2f282e2d856e: Pushed
184b0e5a69c3: Pushed
1.1: digest: sha256:07b5b600eabb483fe5a5863e85df52fff962425cb476010a4a41eeca1aadf5c6 size: 1156
Created manifest list gcr.io/kubernetes-e2e-test-images/netexec:1.1
Pushed ref gcr.io/kubernetes-e2e-test-images/netexec@sha256:09180b40bf33b8a3018d0b0d462291c9344b47f51e7df12d77a971f35c95354f with digest: sha256:09180b40bf33b8a3018d0b0d462291c9344b47f51e7df12d77a971f35c95354f
Pushed ref gcr.io/kubernetes-e2e-test-images/netexec@sha256:a8c571d59470aae5cf21b37a724ba2b41f336b7252e0ad053ff20f3f52067e24 with digest: sha256:a8c571d59470aae5cf21b37a724ba2b41f336b7252e0ad053ff20f3f52067e24
Pushed ref gcr.io/kubernetes-e2e-test-images/netexec@sha256:2fb678b4bffe4feecd6d423d1d2429619d6baba55df79734b87e5a9e5f502050 with digest: sha256:2fb678b4bffe4feecd6d423d1d2429619d6baba55df79734b87e5a9e5f502050
Pushed ref gcr.io/kubernetes-e2e-test-images/netexec@sha256:99384b27b4f15388f83d538a2688c83bb2e2170aa97f8640f6b15ccb13de3e08 with digest: sha256:99384b27b4f15388f83d538a2688c83bb2e2170aa97f8640f6b15ccb13de3e08
Pushed ref gcr.io/kubernetes-e2e-test-images/netexec@sha256:07b5b600eabb483fe5a5863e85df52fff962425cb476010a4a41eeca1aadf5c6 with digest: sha256:07b5b600eabb483fe5a5863e85df52fff962425cb476010a4a41eeca1aadf5c6
sha256:203f0e11dde4baf4b08e27de094890eb3447d807c8b3e990b764b799d3a9e8b7
```

/retest

**Comment by wgliang** [comment]
@spiffxp 
awesome, thanks.

**Comment by wgliang** [comment]
/ping @luxas
for approve

**Comment by spiffxp** [comment]
/approve
sorry for the delay I wanted to wait until I had more than mobile access to double-checking before approving
