### PR TITLE
kube-scheduler: Support extender managed extended resources in kube-scheduler

### LINKED ISSUE #53616: After 1.8, scheduler could reject unknown extended resource names
> /kind bug

**What happened**:
Not sure yet whether this should be considered as a regression or WAI.

Basically, with PR https://github.com/kubernetes/kubernetes/pull/48922, we introduced ExtendedResources that covers all resources outside the default kubernetes.io namespace. In scheduler PodFitsResources(), for every extended resource, we check whether the node has enough resource quantity for it. This introduced a behavior change for non OIR resources outside the default kubernetes.io namespace. I.e., before PR 48922, scheduler wouldn't reject them even if there was no actual resource advertised by the node, but after PR 48922, scheduler will reject them with InsufficientResourceError.

I am opening this issue to discuss whether this behavior change is ok. Please feel free to add any related folks to the discussion.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8+
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yguo0905**
**What this PR does / why we need it**:

This is the continuation of https://github.com/kubernetes/kubernetes/pull/58851.

- This PR adds new extender configurations in scheduler policy config.
    - A set of extended resource names can be specified in an extender config. They are the resources that are managed by the extender. The scheduler will only send pods to the extender if the pod requests at least one of the extended resources in the set.
    - An `IgnoredByScheduler` flag can be set along with each of such resources. If this flag is set to true, the scheduler will not check the resource in the `PodFitsResources` predicate.
- This PR also changes the default behavior of the `PodFitsResources` predicate. Now, by default, `PodFitsResources` will ignore the extended resources that are not in node status. This is required to support extender managed extended resources (including cluster-level resources) on node. Note that in kube-scheduler we override the default behavior by not ignoring such missing extended resources.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/53616 https://github.com/kubernetes/kubernetes/issues/58850 

**Special notes for your reviewer**:

**Release note**:

```
Support extender managed extended resources in kube-scheduler
```

### CODE REVIEW

File: pkg/scheduler/algorithm/predicates/metadata.go [hunk 1]
```diff
@@ -71,6 +77,15 @@ func RegisterPredicateMetadataProducer(predicateName string, precomp PredicateMe
 	predicateMetadataProducers[predicateName] = precomp
 }
 
+// RegisterPredicateMetadataProducerWithIgnoredExtendedResources registers a
+// PredicateMetadataProducer that creates predicate metadata with the provided
+// ignoredExtendedResources.
+func RegisterPredicateMetadataProducerWithIgnoredExtendedResources(ignoredExtendedResources sets.String) {
+	RegisterPredicateMetadataProducer("PredicateWithIgnoredExtendedResources", func(pm *predicateMetadata) {
```
Comment (yguo0905) [inline pkg/scheduler/algorithm/predicates/metadata.go]: I changed the predicate name from `PodFitsResources` to `PredicateWithIgnoredExtendedResources`.

IIUC, the "precomp" function that sets the `ignoredExtendedResources` will override the one for the same predicate created here: https://github.com/kubernetes/kubernetes/blob/01bd3c4b743137f62b00d21ecd6f1559470de92f/pkg/scheduler/factory/plugins.go#L217

Is this the case? And I don't see why `predicateMetadataProducers` is not a slice here: https://github.com/kubernetes/kubernetes/blob/01bd3c4b743137f62b00d21ecd6f1559470de92f/pkg/scheduler/algorithm/predicates/metadata.go#L65

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -172,6 +174,12 @@ func TestScheduler(t *testing.T) {
 			sendPod:     deletingPod("foo"),
 			algo:        mockScheduler{"", nil},
 			eventReason: "FailedScheduling",
+		}, {
+			sendPod:          podWithID(testBindingPodName, ""),
+			algo:             mockScheduler{testNode.Name, nil},
+			expectBind:       testBinding, // testBinding has a name different than testBindingPodName
```
Comment (bsalamat) [inline pkg/scheduler/scheduler_test.go]: I am confused. Why is the name different?

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 3]
```diff
@@ -713,8 +714,19 @@ func PodFitsResources(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *s
 	}
 
 	var podRequest *schedulercache.Resource
+	// No extended resources should be ignored by default unless specified via
+	// extender configuration.
+	ignoredExtendedResources := sets.NewString()
+	// Missing extended resources will be ignored by default unless specified
+	// in predicate metadata. Note that kube-scheduler sets this flag to false
+	// in predicate metadata.
+	ignoreMissingExtendedResources := true
```
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Thanks for looking into this over the weekend!

Yes, this is a backward incompatible change but I haven't come up with a promising solution yet.

In `PodFitsResources`, we cast `algorithm.PredicateMetadata` to `predicate.predicateMetadata` and then use the metadata, including `ignoreMissingExtendedResources` in this PR.
https://github.com/kubernetes/kubernetes/blob/0394ffba6de860ece173a9a485d3518d3a8d37f2/pkg/scheduler/algorithm/predicates/predicates.go#L716-L717

This is how the predicate is invoked in pod admission on node. https://github.com/kubernetes/kubernetes/blob/0394ffba6de860ece173a9a485d3518d3a8d37f2/pkg/kubelet/lifecycle/predicate.go#L80 Here we pass `nil` as the predicate metadata, which means we use the defaults in pod admission on node. That's why I set  `ignoreMissingExtendedResources` default to `true`.

Ideally, kubelet should create a predicate metadata with `ignoreMissingExtendedResources` set to `true` and pass it to the predicate. But this is not possible because of the type cast in the predicate function.

I think the type cast should be removed, and the metadata should be accessed via the `algorithm.PredicateMetadata` interface. kube-scheduler/node/clusterautoscalar can provide their own metadata implementation. But this will be a larger change. Maybe I'm missing some thing. WDYT?

File: pkg/scheduler/algorithm/predicates/metadata.go [hunk 4]
```diff
@@ -95,6 +134,7 @@ func (pfactory *PredicateMetadataFactory) GetMetadata(pod *v1.Pod, nodeNameToInf
 		podRequest:                GetResourceRequest(pod),
 		podPorts:                  schedutil.GetContainerPorts(pod),
 		matchingAntiAffinityTerms: matchingTerms,
+		ignoredExtendedResources:  sets.NewString(),
```
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/metadata.go]: Not needed. Will remove this.

File: pkg/scheduler/factory/factory_test.go [hunk 5]
```diff
@@ -533,3 +535,85 @@ func newConfigFactory(client *clientset.Clientset, hardPodAffinitySymmetricWeigh
...
+func (f *fakeExtender) IsInterested(pod *v1.Pod) bool {
+	return pod != nil && pod.Name == f.interestedPodName
+}
+
+func TestGetBinderFunc(t *testing.T) {
+	for _, test := range []struct {
+		podName   string
+		extenders []algorithm.SchedulerExtender
+
+		expectedBinderType string
```
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/factory/factory_test.go]: I don't have access to the pointer to the default binder.

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (yguo0905) [reply pkg/scheduler/scheduler_test.go]: This is confusing and not that useful. I already added full tests in `TestGetBinderFunc` in `pkg/scheduler/factory/factory_test.go` so this should have been removed.

File: pkg/scheduler/factory/factory_test.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (bsalamat) [reply pkg/scheduler/factory/factory_test.go]: Ah, right. Never mind.

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (bsalamat) [reply pkg/scheduler/algorithm/predicates/predicates.go]: I see. So, for now please add a comment and explain that this default value is chosen so that the kubelet code works fine and add the details.
My only concern right now is that this is backward incompatible from the kubelet side. It is however, backward compatible on the scheduler side, because if scheduler's policy config does not exists or misses this field, the default value of the field will be false and overrides the default value provided here.

File: pkg/scheduler/algorithm/predicates/metadata.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/metadata.go]: Done.

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Done.

Besides scheduler and kubelet, cluster autoscaler and damonset controller also use this predicate. But I don't see any negative impacts from this change. This is also the behavior before 1.8 https://github.com/kubernetes/kubernetes/issues/53616.

@vishh @jiayingz

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 6]
```diff
@@ -713,8 +714,34 @@ func PodFitsResources(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *s
 	}
 
 	var podRequest *schedulercache.Resource
+	// No extended resources should be ignored by default unless specified via
+	// extender configuration.
+	ignoredExtendedResources := sets.NewString()
+	// Missing extended resources will be ignored by default unless a predicate
+	// metadata is provided.
+	//
+	// This predicate is used by scheduler, kubelet, cluster autoscaler and
```
Comment (bsalamat) [inline pkg/scheduler/algorithm/predicates/predicates.go]: @dchen1107 @mwielgus 
This is a backward incompatible change in kubelet and autoscaler, but it applies only to Pods that have extended resources missing on the node. Do you guys approve such a change?

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 7]
```diff
@@ -713,8 +714,34 @@ func PodFitsResources(pod *v1.Pod, meta algorithm.PredicateMetadata, nodeInfo *s
...
+	//     extended resources.
+	//   - In kubelet/cluster autoscaler/daemonset controller, we pass nil
+	//     predicate metadata to this function, so these component will ignore
+	//     missing extended resources.
+	//
+	// To support cluster-level resources, we don't want kubelet/cluster
+	// autoscaler/daemonset controller to reject pods requesting missing
+	// extended resources, which includes cluster-level resources, so we need
+	// to set the default value of this flag to true. This is to fix the issue
+	// https://github.com/kubernetes/kubernetes/issues/53616 before we have
```
Comment (jiayingz) [inline pkg/scheduler/algorithm/predicates/predicates.go]: I thought for cluster autoscaler, we do NOT want to ignore missing extended resources. Otherwise, it may cause problem with gpu autoscaling as a template node created from non-gpu nodepool would also pass this predicate checking.

Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Oh, if we don't have the GPU resources in such node template, we will have to address the issue in https://github.com/kubernetes/kubernetes/pull/60332#discussion_r170441667 in order to support defaulting to `false`.

File: pkg/kubelet/kubelet_node_status.go [hunk 8]
```diff
@@ -606,8 +606,16 @@ func (kl *Kubelet) setNodeStatusMachineInfo(node *v1.Node) {
 		}
 
 		for _, removedResource := range removedDevicePlugins {
-			glog.V(2).Infof("Remove capacity for %s", removedResource)
-			delete(node.Status.Capacity, v1.ResourceName(removedResource))
+			glog.V(2).Infof("Set capacity for %s to 0 on device removal", removedResource)
```
Comment (yguo0905) [inline pkg/kubelet/kubelet_node_status.go]: @jiayingz, please take a look.

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/scheduler/algorithm/predicates/predicates.go]: I created `algorithm.PredicateMetadataProducer` in kubelet using `predicates.NewPredicateMetadataFactory()`.

It turned out that `NewPredicateMetadataFactory`'s `podLister` argument is not used at all so I can just use this function in kubelet.

**Comment by yguo0905** [comment]
@bsalamat and @vishh. I changed the default behavior for cluster autoscaler back to what it does for now.

I keep `ignoreMissingExtendedResources` as a flag rather than a list of resources that are required. I think ff we need to support new extended resources in cluster autoscaler, it's very likely that we will add the support in its cloud provider on a case by case basis.

File: pkg/kubelet/kubelet_node_status.go (hunk 8 above)
Comment (vikaschoudhary16) [reply pkg/kubelet/kubelet_node_status.go]: should allocatable also be set to 0 ?

Comment (yguo0905) [reply pkg/kubelet/kubelet_node_status.go]: Allocatable will be set to capacity at line 644.

**Comment by yguo0905** [comment]
Per discussion with @vishh offline, I removed the `ignoreMissingExtendedResource` flag. Instead, we remove the requests of the extended resources from pod if the resources are missing from node status in kubelet.

File: pkg/kubelet/lifecycle/predicate.go [hunk 9]
```diff
@@ -84,8 +79,13 @@ func (w *predicateAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult
 			Message: message,
 		}
 	}
-	meta := w.metadataProducer(pod, map[string]*schedulercache.NodeInfo{node.Name: nodeInfo})
-	fit, reasons, err := predicates.GeneralPredicates(pod, meta, nodeInfo)
+
+	// Remove the requests of the extended resources that are missing in the
+	// node info. This is required to support cluster-level resources, which
+	// are extended resources unknown to nodes.
```
Comment (vishh) [inline pkg/kubelet/lifecycle/predicate.go]: There is an issue where if a pod was manually (or incorrectly) bound to a node where a node level extended resource it requires is not found, then kubelet will not fail admission. We should document this as known issue and fix it with resource APIs.

File: pkg/scheduler/algorithmprovider/defaults/defaults.go [hunk 10]
```diff
@@ -39,7 +39,7 @@ func init() {
 	// Register functions that extract metadata used by predicates and priorities computations.
 	factory.RegisterPredicateMetadataProducerFactory(
 		func(args factory.PluginFactoryArgs) algorithm.PredicateMetadataProducer {
-			return predicates.NewPredicateMetadataFactory()
+			return predicates.NewPredicateMetadataFactory(args.PodLister)
```
Comment (vishh) [inline pkg/scheduler/algorithmprovider/defaults/defaults.go]: Is that argument even necessary? @bsalamat can this be removed?

**Comment by vishh** [comment]
/lgtm
/approve
@yguo0905 please update [public documentation](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/) with the repercussions of this PR. It enables cluster level resources, but with a few caveats (lack of support for daemonsets, requires scheduler extender config, etc.)

File: pkg/kubelet/lifecycle/predicate_test.go [hunk 11]
```diff
@@ -0,0 +1,108 @@
...
+			pod: makeTestPod(
+				v1.ResourceList{},
+				v1.ResourceList{"foo.com/bar": quantity},
+			),
+			node: makeTestNode(
+				v1.ResourceList{"foo.com/baz": quantity},
+			),
+			expectedPod: makeTestPod(
+				v1.ResourceList{},
+				v1.ResourceList{"foo.com/bar": quantity},
```
Comment (jiayingz) [inline pkg/kubelet/lifecycle/predicate_test.go]: Hmm, shouldn't this resource request be removed?

Comment (yguo0905) [reply pkg/kubelet/lifecycle/predicate_test.go]: The request is in `Limits` which is skipped in this logic. I will refine this test once the overall design is LGTM'd.

Comment (jiayingz) [reply pkg/kubelet/lifecycle/predicate_test.go]: Oh I see. So this is limit and we leave limit unchanged. For extended resources, we actually require limits to equal to requests and in devicemanager, we actually examine resource Limits during resource allocation. Can we make sure to also remove limits for non-existing extended resources?

File: pkg/kubelet/lifecycle/predicate.go (hunk 9 above)
Comment (yguo0905) [reply pkg/kubelet/lifecycle/predicate.go]: Will do.

File: pkg/scheduler/algorithmprovider/defaults/defaults.go (hunk 10 above)
Comment (yguo0905) [reply pkg/scheduler/algorithmprovider/defaults/defaults.go]: I think this can be removed. If yes, I can do that in a separate PR in 1.11.

File: pkg/kubelet/lifecycle/predicate_test.go (hunk 11 above)
Comment (jiayingz) [reply pkg/kubelet/lifecycle/predicate_test.go]: Never mind. Whether we have Limit or not doesn't affect GeneralPredicate evaluation.

**Comment by vishh** [comment]
Can you squash the commits @yguo0905 ?

/lgtm
