### PR TITLE
Fix data race in volume controller unit test.

### LINKED ISSUE #26345: unit flake: TestControllerSync data race
```
WARNING: DATA RACE
Read by goroutine 147:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:298 +0x0
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*volumeReactor).React()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/framework_test.go:189 +0xd8a
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*volumeReactor).React-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/framework_test.go:483 +0x61
  k8s.io/kubernetes/pkg/client/testing/core.(*SimpleReactor).React()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/testing/core/fixture.go:276 +0x7c
  k8s.io/kubernetes/pkg/client/testing/core.(*Fake).Invokes()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/testing/core/fake.go:124 +0x36f
  k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake.(*FakePersistentVolumes).UpdateStatus()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/unversioned/fake/fake_persistentvolume.go:54 +0x30a
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*PersistentVolumeController).updateVolumePhase()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller.go:557 +0x90b
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*PersistentVolumeController).syncVolume()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller.go:399 +0x11ac
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*PersistentVolumeController).addVolume()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller_base.go:136 +0x1b0
  k8s.io/kubernetes/pkg/controller/persistentvolume.(*PersistentVolumeController).(k8s.io/kubernetes/pkg/controller/persistentvolume.addVolume)-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller_base.go:105 +0x41
  k8s.io/kubernetes/pkg/controller/framework.ResourceEventHandlerFuncs.OnAdd()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:170 +0x47
  k8s.io/kubernetes/pkg/controller/framework.(*ResourceEventHandlerFuncs).OnAdd()
      <autogenerated>:25 +0xd9
  k8s.io/kubernetes/pkg/controller/framework.NewIndexerInformer.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:314 +0x450
  k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:128 +0xa4
  k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103 +0x2d
  k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:86 +0x58
  k8s.io/kubernetes/pkg/util/wait.JitterUntil()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87 +0xc9
  k8s.io/kubernetes/pkg/util/wait.Until()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x50
  k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103 +0x25d

Previous write by goroutine 116:
  runtime.mapdelete()
      /usr/local/go/src/runtime/hashmap.go:545 +0x0
  k8s.io/kubernetes/pkg/controller/persistentvolume.TestControllerSync.func4()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller_test.go:112 +0x16b
  k8s.io/kubernetes/pkg/controller/persistentvolume.TestControllerSync()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/persistentvolume/controller_test.go:152 +0x1db0
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/26301/kubernetes-pull-test-unit-integration/27919/build-log.txt

### PR DESCRIPTION
**Pull request by jsafrane**
Reactor must be locked when fiddling with reactor.volumes and reactor.claims. Therefore add new functions to add/delete volume/claim with sending an event.

Fixes #26345

### CODE REVIEW

**Comment by jsafrane** [comment]
Raising priority to get merged sooner, everybody likes fixed flakes, right?

**Comment by jsafrane** [comment]
And I wonder, what does ' e2e-not-required` label means, does it skip **only** e2e tests? I'm fixing unit test only.

**Comment by saad-ali** [comment]
Assigning to @jingxu97 for review.

File: pkg/controller/persistentvolume/framework_test.go [hunk 1]
```diff
@@ -471,6 +471,62 @@ func (r *volumeReactor) waitTest() {
...
+func (r *volumeReactor) deleteClaimWithEvent(claim *api.PersistentVolumeClaim) {
+	r.lock.Lock()
+	defer r.lock.Unlock()
+
+	// Remove the claim from list of resulting claims.
+	delete(r.claims, claim.Name)
+
+	// Generate deletion event. Cloned volume is needed to prevent races (and we
+	// would get a clone from etcd too).
+	clone, _ := conversion.NewCloner().DeepCopy(claim)
```
Comment (jingxu97) [inline pkg/controller/persistentvolume/framework_test.go]: I am wondering whether the clone operation in this func and deleteVolumeWithEvent function can be put before the lock?

File: pkg/controller/persistentvolume/framework_test.go [hunk 2]
```diff
@@ -471,6 +471,62 @@ func (r *volumeReactor) waitTest() {
 	}
 }
 
+// deleteVolumeWithEvent simulates that a volume has been deleted in etcd and
+// the controller receives 'volume deleted' event.
+func (r *volumeReactor) deleteVolumeWithEvent(volume *api.PersistentVolume) {
```
Comment (jingxu97) [inline pkg/controller/persistentvolume/framework_test.go]: Could we remove WithEvent from the function name unless it may cause confusion?

File: pkg/controller/persistentvolume/framework_test.go (hunk 1 above)
Comment (jsafrane) [inline pkg/controller/persistentvolume/framework_test.go]: It could, however... would the code be more effective? I doubt so. Would it be more readable? IMO it's clearer as it is.

File: pkg/controller/persistentvolume/framework_test.go (hunk 2 above)
Comment (jsafrane) [inline pkg/controller/persistentvolume/framework_test.go]: These functions do not really add/delete volumes/claims, they generate fake events. , `addClaim` would be confusing. I'll rename them to `addClaimEvent`.

**Comment by jsafrane** [comment]
rebased and renamed functions

File: pkg/controller/persistentvolume/controller_test.go [hunk 3]
```diff
@@ -92,14 +83,7 @@ func TestControllerSync(t *testing.T) {
...
 				volume := obj.(*api.PersistentVolume)
-				// Remove the volume from list of resulting volumes.
-				delete(reactor.volumes, volume.Name)
-				// Poke the controller with deletion event. Cloned volume is
-				// needed to prevent races (and we would get a clone from etcd
-				// too).
-				clone, _ := conversion.NewCloner().DeepCopy(volume)
-				volumeClone := clone.(*api.PersistentVolume)
-				reactor.volumeSource.Delete(volumeClone)
+				reactor.deleteVolumeEvent(volume)
```
Comment (jingxu97) [inline pkg/controller/persistentvolume/controller_test.go]: Just want to make sure, we don't need add any lock on line 103 and 107 (in your new version), right?

Comment (jsafrane) [inline pkg/controller/persistentvolume/controller_test.go]: no, we do not need any lock there.

**Comment by jingxu97** [comment]
LGTM
