### PR TITLE
Recover CSI volumes from dangling attachments

### LINKED ISSUE #77324: Garbage collect VolumeAttachment objects to trigger detach
**What happened**:

*Background:* The attach/detach controller create `VolumeAttachment` objects for CSI Volumes to indicate that a volume needs to be attached to a node. It deletes the object to indicate that the volume should be detached.

*Problem:* If the Attach/Detach controller crashes, and in the meantime the pod using that volume is deleted, when the AD controller restarts, it won't know that the volume was previously attached and should be cleaned up.

**What you expected to happen**:

*Proposal:* We should have the AD controller periodically list all `VolumeAttachment` objects and for any that are not accounted for, update its internal actual/desired state caches so that the volume is gracefully detached.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
/sig storage

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #80488: Dangling volume mechanism for CSI does not exist
The dangling volume mechanism we currently use for recovering volumes that are incorrectly attached will not work for CSI.

This mechanism is in use by Cinder and EBS drivers at present - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L338 and solves real issues where a volume may be erroneously attached to the node. 

In past building exact state of the world after controller-manager recovers from a crash was kinda not very precise which results in bugs like this. I am wondering if for CSI we should be able to use `VolumeAttachment` objects to rebuild the state and workaround/fix problems like this.

/sig storage

cc @jsafrane @msau42 @jingxu97 @davidz627

### LINKED ISSUE #94912: Pod recreation gets stuck due to dangling attach
**What happened**:
New pod creation gets stuck in `"Container creating"`

**What you expected to happen**:
Pod recreation should have succeeded. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a statefulset application
2. While the pod creation is in-progress, restart kube-controller-manager and delete the pod
3. New pod creation gets stuck in `"Container creating"`
4. `kubectl describe pod` shows the below failure:
```kubelet, node-khjt  Unable to attach or mount volumes: unmounted volumes=[test-pv], unattached volumes=[test-pv]: timed out waiting for the condition```

Note: To increase the likelihood of hitting the race, you can introduce delay [here](https://github.com/kubernetes/kubernetes/blob/e23d83eead3b5ae57731afb0209f4a2aaa4009dd/pkg/volume/util/operationexecutor/operation_generator.go#L338).  While the kube-controller hits this logic, restart the kube-controller and delete the pod. 

**Anything else we need to know?**:
If kube-controller is restarted after the volume is attached to the node, but before the node.status is updated, the restarted kube-controller doesn't know about this volume attachment (as the incore state is lost). If the pod is deleted before kube-controller re-initializes its incore state, the volume-attachment doesn't make into the DSW for that node. Eventually, when statefulset creates the pod on a different node, it will be stuck waiting for the volume to be attached.

Note that the in-tree volume plugins that implement danglingAttach error handling (eg: [here](https://github.com/kubernetes/kubernetes/blob/f4e39afea082afac7bf6f6936c34e012b7cb3c25/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2550)) will auto-recover from the failure. The issue would likely hit all other in-tree volume types that support `attach`.

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by yuga711**
Change-Id: I72105d67d8a4069ab19bfa4638a7ac365cf4194c

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
This PR recovers from certain type of dangling CSI attachments by detaching them from the undesired nodes. In the current design, if kube-controller-manager crashes/restarts while attach/detach is in-progress, the volume may be left attached to an undesired node (eg., when the pod using the volume is deleted during the restart window). This PR fixes such dangling attachments by using the presence of  VolumeAttachment objects during Attach/Detach Controller initialization.

This solution relies on the existence of the VA object. While this solution would recover dangling volumes caused because of certain races, it will not recover from other dangling scenarios where VA object itself is gone

**Which issue(s) this PR fixes**:
Partially addresses #94912
Partially addresses #80488
Fixes #77324

**Special notes for your reviewer**:
Verified the fix through reproduce steps in #94912

**Does this PR introduce a user-facing change?**:
NONE

```release-note
Fix to recover CSI volumes from certain dangling attachments
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 1]
```diff
@@ -475,6 +475,50 @@ func (adc *attachDetachController) populateDesiredStateOfWorld() error {
...
+				err)
+			continue
+		}
+		volumeName, err := volumeutil.GetUniqueVolumeNameFromSpec(plugin, volumeSpec)
+		if !adc.actualStateOfWorld.IsVolumeAttachedToNode(volumeName, nodeName) {
+			klog.V(1).Infof("Marking volume attachment as uncertain as volume:%q (%q) is not in ASW", volumeName, nodeName)
+			err = adc.actualStateOfWorld.MarkVolumeAsUncertain(volumeName, volumeSpec, nodeName)
+			if err != nil {
+				klog.Errorf("MarkVolumeAsUncertain fail to add the volume %q (%q) to ASW. err: %s", volumeName, nodeName, err)
+				continue
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:518]: just a nit: is this continue needed?

Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:518]: ack

**Comment by gnufied** [comment]
Have we considered if we can use following error from CSI:

> | Volume published to another node | 9 FAILED_PRECONDITION | Indicates that a volume corresponding to the specified `volume_id` has already been published at another node and does not have MULTI_NODE volume capability. If this error code is returned, the Plugin SHOULD specify the `node_id` of the node at which the volume is published as part of the gRPC `status.message`. | Caller SHOULD ensure the specified volume is not published at any other node before retrying with exponential back off. |

and use it to return dangling volume errors so as *all* plugins that implement `ControllerPublishVolume` correctly can benefit.  Using VA to track attachment status is okay but not 100% fullproof.

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews 

I think we'll need to look at both solutions. Relying on attach failure code means that the pod had to be rescheduled.

**Comment by yuga711** [comment]
> @kubernetes/sig-storage-pr-reviews
> 
> I think we'll need to look at both solutions. Relying on attach failure code means that the pod had to be rescheduled.

Yes, that's right. We need both solutions as they have their own limitations. Attach failure code approach will not fix until next attach and may not fix in multi-attach case.

**Comment by jingxu97** [comment]
> Have we considered if we can use following error from CSI:
> 
> > | Volume published to another node | 9 FAILED_PRECONDITION | Indicates that a volume corresponding to the specified `volume_id` has already been published at another node and does not have MULTI_NODE volume capability. If this error code is returned, the Plugin SHOULD specify the `node_id` of the node at which the volume is published as part of the gRPC `status.message`. | Caller SHOULD ensure the specified volume is not published at any other node before retrying with exponential back off. |
> 
> and use it to return dangling volume errors so as _all_ plugins that implement `ControllerPublishVolume` correctly can benefit. Using VA to track attachment status is okay but not 100% fullproof.

Here I think the code does not rely on VA attachment status. As long as there is a VA, no matter the status is attached or not, the code will add volume as uncertain status to make sure following attach or detach will be triffered.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 2]
```diff
@@ -475,6 +475,58 @@ func (adc *attachDetachController) populateDesiredStateOfWorld() error {
...
+	vas, err := adc.volumeAttachmentLister.List(labels.Everything())
+	if err != nil {
+		klog.Errorf("failed to list VolumeAttachment objects: %v", err)
+		return err
+	}
+	for _, va := range vas {
+		nodeName := types.NodeName(va.Spec.NodeName)
+		pvName := va.Spec.Source.PersistentVolumeName
+		if pvName == nil {
+			klog.V(5).Infof("Skipping the va as its pvName is nil, va.Name: %q, nodeName: %q",
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:493]: this should not happen normally, right? maybe make it a warning

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 3]
```diff
@@ -475,6 +475,58 @@ func (adc *attachDetachController) populateDesiredStateOfWorld() error {
...
+		pv, err := adc.pvLister.Get(*pvName)
+		if err != nil {
+			klog.Errorf("Unable to lookup pv object for: %q, err: %v", *pvName, err)
+			continue
+		}
+		volumeSpec := volume.NewSpecFromPersistentVolume(pv, false)
+		plugin, err := adc.volumePluginMgr.FindAttachablePluginBySpec(volumeSpec)
+		if err != nil || plugin == nil {
+			klog.V(5).Infof(
+				"Skipping processing the volume %q on nodeName: %q, no attacher interface found. err=%v",
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:506]: also a waring?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 4]
```diff
@@ -475,6 +475,58 @@ func (adc *attachDetachController) populateDesiredStateOfWorld() error {
...
+		if err != nil {
+			klog.Errorf(
+				"Failed to find unique name for volume:%q, va.Name:%q, nodeName:%q: %v",
+				*pvName,
+				va.Name,
+				nodeName,
+				err)
+			continue
+		}
+		if !adc.actualStateOfWorld.IsVolumeAttachedToNode(volumeName, nodeName) {
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:522]: I am thinking to remove this, putting into uncertain state is even safer considering the attach status might not be the true status.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 5]
```diff
@@ -475,6 +475,58 @@ func (adc *attachDetachController) populateDesiredStateOfWorld() error {
 		}
 	}
 
+	// Process Volume-Attachment objects.
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/attach_detach_controller.go:478]: this process should belong to populateActualStateofWorld?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 4 above)
Comment (jingxu97) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:522]: also I am thinking it is better to mark as uncertain when processing from node status volumeAttached list.

Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:522]: Sorry, I didnt understand. Do you mean add volume to uncertain unconditionally? That means we will move all volumes to uncertain. I dont think we want that.
Note that during attach, volume is added to node->VolumesAttached when the transaction ends, and during detach, the volume is removed from node->VolumesAttached when the transaction begins. So, if we have a VA object, but the volume is not in VolumesAttached that means it is a dangling-attach candidate, so we mark as uncertain.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 2 above)
Comment (jingxu97) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:493]: I see VA might be used for inline volumes for CSI migration feature. I actually not sure whether we need to deal with InlineVolume here. If needed, we can work on it in a separate PR, comment it here and make an issue to track it?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 4 above)
Comment (jingxu97) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:522]: Since this is part of populate actual state when controller restarts, it is triggered before reconciler starts to work. At this point, the controller first to use node status to update asw, and you are adding here to use VA to further update asw. Because controller is restarting, it might be possible that node status volumeattached list is not representing the real state. For example, node is deleted and recreated while node object still exist. So volume is automatically detached, but it is. still on volumeAttached list..

I think putting uncertain will make sure that attach/detach will be triggered which is safer. Controller might trigger unnecessary attach/detach, but I think it is ok. It is better cover all corner cases with a little bit overhead.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 2 above)
Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:493]: Ack. Will add a comment and convert to warning.

File: pkg/controller/volume/attachdetach/attach_detach_controller.go (hunk 4 above)
Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:522]: >> For example, node is deleted and recreated while node object still exist. 
When a node is deleted, isn't the node object deleted? Are you saying the node deletion happened after asw processed the node, but before the node->event handler is setup? If so, then this volume wont be in DSW (as no pods are running on the node), so will be detached and cleared? Isnt it? Are you saying a dangling attach is possible?

Anyways, I think marking every VA as uncertain will lead to issuing attach for every good volume! I still think this may be undesired as there could be other implications of doing this.

Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go]: Discussed offline with jingxu97@ and msau@. The conclusion is to create a separate issue to investigate the need for marking all the volumes as 'uncertain' and potential implications of such a change. We discussed that it may result in cloud-provider attach or get calls for all good (intree) volumes too. Theoretically, attach() should be idempotent, but could be risky in some drivers. We need to validate these risks and understand the scale implications. Also, if a node object remains while the underlying machine is recreated, the ADC's periodic VerifyVolumesAreAttached() would potentially detect the volumes are not attached to this machine and fix it.  jingxu97@ will create an issue to followup on this. Thanks!

**Comment by jeremyrickard** [comment]
/hold 

Hey there, 1.20 release lead here. We are way too close to the release date to land anything but the most critical, release blocking items. This does not appear to meet that criteria. Could you explain why this absolutely needs to be in 1.20? Or move it to 1.21?

**Comment by yuga711** [comment]
> /hold
> 
> Hey there, 1.20 release lead here. We are way too close to the release date to land anything but the most critical, release blocking items. This does not appear to meet that criteria. Could you explain why this absolutely needs to be in 1.20? Or move it to 1.21?

I agree. Moving to 1.21 is Ok.

**Comment by jingxu97** [comment]
> > /hold
> > Hey there, 1.20 release lead here. We are way too close to the release date to land anything but the most critical, release blocking items. This does not appear to meet that criteria. Could you explain why this absolutely needs to be in 1.20? Or move it to 1.21?
> 
> I agree. Moving to 1.21 is Ok.

This is a fix to some of the dangling volumes problem we have encountered. (mentioned in a number of issues e.g., #94912 #80488. It is important, but might not qualified as release blocking. If move it to 1.21, we should consider cherrypick it.

**Comment by jeremyrickard** [comment]
@jingxu97 sure, I think it is appropriate to discuss a CP of that back into 1.20.x, but as you've indicated this wasn't introduced as part of 1.20 so I wouldn't classify it as blocking. I'll move it to 1.21 for you and ya'll can work on a CP for 1.20.x once it lands. 

/milestone v1.21

**Comment by ialidzhikov** [comment]
@jeremyrickard, can you cancel the hold as v1.20 is out? 
We should get this in for v1.21 and start working on cherry-picks.

/cc @msau42

**Comment by jeremyrickard** [comment]
/hold cancel

Thank you for your understanding while we worked through getting 1.20 out.

**Review by gnufied — COMMENTED** [review]
Is there a way to e2e test this?

**Comment by yuga711** [comment]
> Is there a way to e2e test this?
I think such test would involve creating a race between kube-controller restart and pod deletion. If needed, how about doing it separately?

File: pkg/controller/volume/attachdetach/attach_detach_controller.go [hunk 6]
```diff
@@ -391,6 +391,61 @@ func (adc *attachDetachController) populateActualStateOfWorld() error {
 			adc.addNodeToDswp(node, types.NodeName(node.Name))
 		}
 	}
+
+	// Process Volume-Attachment objects.
```
[the remark this answers is not in the document]
Comment (yuga711) [reply pkg/controller/volume/attachdetach/attach_detach_controller.go:395]: Ok. Ack. Will consider if I am making other changes in this PR.

**Comment by gnufied** [comment]
>  I think such test would involve creating a race between kube-controller restart and pod deletion. If needed, how about doing it separately?

We will have to also restart ADC because this mechanism only looks for orphaned VAs only on startup.  I think it might be tricky to e2e test this properly.

/lgtm

**Comment by yuga711** [comment]
The tests seems to be failing because a function name (IsVolumeAttachedToNode) was replaced after this PR was posted. I will need to rework a bit and will repost the change.

**Comment by msau42** [comment]
/lgtm cancel

to fix merge conflict

**Comment by jingxu97** [comment]
consider to cherrypick this PR?

**Comment by msau42** [comment]
I think that's a good idea. @gnufied any concerns?

**Comment by gnufied** [comment]
@msau42 should be fine to cherry-pick.
