### PR TITLE
Fix node not rejoining cluster on reboot

### LINKED ISSUE #10368: kubelet does not recover from machine reboot
I started a cluster running on GCE last week, using `go run hack/e2e.go -build -up`. Today I noticed today that both of my minion nodes were stuck in the NotReady state:
```
$ kubectl get nodes
NAME                           LABELS                                                STATUS
e2e-test-stclair-minion-cu9a   kubernetes.io/hostname=e2e-test-stclair-minion-cu9a   NotReady
e2e-test-stclair-minion-i5b9   kubernetes.io/hostname=e2e-test-stclair-minion-i5b9   NotReady
```
Inspecting the logs yields the same error message over and over again:
```
stclair@e2e-test-stclair-minion-cu9a:~$ tail /var/log/kubelet.log      
W0625 21:18:55.371135    2928 request.go:292] field selector: v1 - pods - spec.host - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
E0625 21:18:55.371813    2928 reflector.go:136] Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
E0625 21:18:55.371940    2928 reflector.go:136] Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
E0625 21:18:55.737900    2928 kubelet.go:1591] error getting node: node e2e-test-stclair-minion-cu9a not found
E0625 21:18:55.748663    2928 kubelet.go:1212] Failed creating a mirror pod "fluentd-elasticsearch-e2e-test-stclair-minion-cu9a_default": the server has asked for the client to provide credentials (post pods)
E0625 21:18:56.202222    2928 reflector.go:136] Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
W0625 21:18:56.371997    2928 request.go:292] field selector: v1 - nodes - metadata.name - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 21:18:56.372199    2928 request.go:292] field selector: v1 - pods - spec.host - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
E0625 21:18:56.372828    2928 reflector.go:136] Failed to list *api.Node: the server has asked for the client to provide credentials (get nodes)
E0625 21:18:56.373378    2928 reflector.go:136] Failed to list *api.Pod: the server has asked for the client to provide credentials (get pods)
```
Same with the proxy:
```
stclair@e2e-test-stclair-minion-cu9a:~$ tail -n 5 /var/log/kube-proxy.log 
E0625 21:18:44.957584    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
E0625 21:19:31.023914    2968 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
E0625 21:20:08.662204    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
E0625 21:20:43.884667    2968 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
E0625 21:21:15.108205    2968 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
```

Version:
```
$ kubectl describe nodes e2e-test-stclair-minion-cu9a
W0625 14:05:10.463312   16838 request.go:291] field selector: v1beta3 - events - involvedObject.uid - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 14:05:10.463428   16838 request.go:291] field selector: v1beta3 - events - involvedObject.name - e2e-test-stclair-minion-cu9a: need to check if this is versioned correctly.
W0625 14:05:10.463441   16838 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - : need to check if this is versioned correctly.
W0625 14:05:10.463451   16838 request.go:291] field selector: v1beta3 - events - involvedObject.kind - Node: need to check if this is versioned correctly.
Name:			e2e-test-stclair-minion-cu9a
Labels:			kubernetes.io/hostname=e2e-test-stclair-minion-cu9a
CreationTimestamp:	Thu, 18 Jun 2015 18:10:36 -0700
Conditions:
  Type		Status		LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	Unknown 	Fri, 19 Jun 2015 13:52:08 -0700 	Fri, 19 Jun 2015 13:52:53 -0700 	Kubelet stopped posting node status. 	
Addresses:	10.240.179.67,146.148.78.88
Capacity:
 cpu:		1
 memory:	3800808Ki
 pods:		100
Version:
 Kernel Version:		3.16.0-0.bpo.4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://1.6.2
 Kubelet Version:		v0.19.0-634-g2fab19a748fabb-dirty
 Kube-Proxy Version:		v0.19.0-634-g2fab19a748fabb-dirty
PodCIDR:			10.245.1.0/24
ExternalID:			1522119118968509696
Pods:				(0 in total)
No events.
```

### PR DESCRIPTION
**Pull request by lavalamp**
Also improve logging. Fixes #10368.

GCE's external ID apparently can change after a reboot.

### CODE REVIEW

**Comment by lavalamp** [comment]
@dchen1107 manually tested this, it works-- but is it a good idea?

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -762,8 +766,11 @@ func (kl *Kubelet) initialNodeStatus() (*api.Node, error) {
 	return node, nil
 }
 
-// registerWithApiserver registers the node with the cluster master.
+// registerWithApiserver registers the node with the cluster master. It is safe to call multiple times.
 func (kl *Kubelet) registerWithApiserver() {
+	if kl.registrationCompleted {
```
Comment (roberthbailey) [inline pkg/kubelet/kubelet.go]: Do we need a lock around this bool? If folks read the func doc they might call it simultaneously from multiple go routines.

**Comment by roberthbailey** [comment]
Can you include some output of the old/new external ID fields from when you saw it change?

**Comment by zmerlynn** [comment]
Do we know any way to exacerbate this so we can test it a little more rigorously with an e2e?

**Comment by lavalamp** [comment]
We don't need to exacerbate this, the reboot test triggers it 100% of the time for me on at least one of my four nodes.

**Comment by lavalamp** [comment]
Log output:

```
I0701 01:46:19.929564    2825 kubelet.go:1920] Recording NodeNotReady event message for node kubernetes-minion-0rxb
I0701 01:46:19.929594    2825 kubelet.go:787] Attempting to register node kubernetes-minion-0rxb
E0701 01:46:20.051358    2825 kubelet.go:810] Previously "kubernetes-minion-0rxb" had externalID "7206479615736337042"; now it is "14924252374946362911"; will delete and recreate.
...
I0701 01:46:21.767025    2995 kubelet.go:787] Attempting to register node kubernetes-minion-0rxb
I0701 01:46:21.796773    2995 kubelet.go:816] Successfully registered (or updated) node kubernetes-minion-0rxb
```

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (lavalamp) [inline pkg/kubelet/kubelet.go]: I will document.

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -762,8 +766,13 @@ func (kl *Kubelet) initialNodeStatus() (*api.Node, error) {
 	return node, nil
 }
 
-// registerWithApiserver registers the node with the cluster master.
+// registerWithApiserver registers the node with the cluster master. It is safe
+// to call multiple times, but not concurrently (kl.registrationCompleted is
+// not locked).
```
Comment (dchen1107) [inline pkg/kubelet/kubelet.go]: nit: Can you add a comment on why the method is safe to  be called multiple times, but not concurrently?

**Comment by dchen1107** [comment]
LGTM

Also above Jenkins GCE redness is misleading: 0 failed.

**Comment by dchen1107** [comment]
@roberthbailey second TL's lgmt?

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (lavalamp) [inline pkg/kubelet/kubelet.go]: It's already there ```(kl.registrationCompleted is not locked)```

**Comment by lavalamp** [comment]
jenkins timed out while shutting down the cluster.

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Comment by roberthbailey** [comment]
I don't understand why we are using an ID that isn't the node name (and doesn't persist across reboots). This seems like it must have changed recently, because this registration flow used to work fine when @mbforbes originally wrote the reboot tests. :(

**Comment by roberthbailey** [comment]
That being said, this is clearly a bug and this fix seems reasonable. We still register with the master using the same name, so pods won't be moved around. 

LGTM.

**Comment by dchen1107** [comment]
@roberthbailey I am a little bit surprised about ID is changed during reboot too. 

Can we have this merged?
