### PR TITLE
Remove potentially unhealthy symlink only for dead containers

### LINKED ISSUE #52172: Kubelet is not creating the log symlink
/kind bug

**What happened**:
Kubelet is not creating the log symlink for some containers at '/var/log/containers'

**What you expected to happen**:

The symlink is a requirement for fluentd, we expect to have a symlink for any running container inside a pod.

**How to reproduce it (as minimally and precisely as possible)**:

We run test with the following script and found many cases, but we could not reproduced in a dev environment.
```
#!/bin/bash 
docker ps -q | while read line;
do
  if [ `find /var/log/containers -name *$line* | wc -l` = "0" ]
  then
    name=`docker inspect --format {{.Name}} $line | head -c 8 `
    if [ $name != "/k8s_POD" ] 
    then
      docker inspect --format {{.Name}} $line 
    fi 
  fi  
done
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T10:00:30Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.7", GitCommit:"8eb75a5810cba92ccad845ca360cf924f2385881", GitTreeState:"clean", BuildDate:"2017-04-27T09:42:05Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux master0 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
Containers: 26
 Running: 18
 Paused: 0
 Stopped: 8
Images: 20
Server Version: 1.12.6
Storage Driver: aufs
```

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As the discussion over #52172 showed, there is race condition between the container log rotation and the kubelet GC which may result in the loss of symlink.

Here is how container log rotation works (see containerLogManager#rotateLatestLog):

1. rename current log to rotated log file whose filename contains current timestamp (fmt.Sprintf("%s.%s", log, timestamp))
2. reopen the container log
3. if #2 fails, rename rotated log file back to container log

There is small but indeterministic amount of time during which log file doesn't exist (between steps #1 and #2, between #1 and #3). Hence the symlink may be deemed unhealthy during that period.

This PR resorts to runtimeService.ContainerStatus() to check whether the container corresponding to the potentially unhealthy symlink is alive or not. The symlink would only be removed for dead containers.

There is an issue that the filename may grow too long, that is a known issue.

-----

Previous patch introduced locking between containerGC and containerLogManager#rotateLatestLog w.r.t. symlink removal.
However, after extensive discussion, it seems we can reduce the complexity of the solution based on empirical knowledge of symlink filename parsing.

Ref: #52172

**Which issue(s) this PR fixes**:
Fixes 

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 1]
```diff
@@ -37,6 +37,7 @@ type containerGC struct {
 	client           internalapi.RuntimeService
 	manager          *kubeGenericRuntimeManager
 	podStateProvider podStateProvider
+	symlinkFirstSeen map[string]time.Time
```
Comment (rphillips) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: symlinkFirstSeen is actually when the symlink is first 'not' seen, perhaps a name change for this variable?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 2]
```diff
@@ -354,11 +355,20 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
 	// Remove dead container log symlinks.
 	// TODO(random-liu): Remove this after cluster logging supports CRI container log path.
 	logSymlinks, _ := osInterface.Glob(filepath.Join(legacyContainerLogsDir, fmt.Sprintf("*.%s", legacyLogSuffix)))
+	now := time.Now()
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
-			err := osInterface.Remove(logSymlink)
-			if err != nil {
-				klog.Errorf("Failed to remove container log dead symlink %q: %v", logSymlink, err)
+			if firstSeen, ok := cgc.symlinkFirstSeen[logSymlink]; ok {
```
Comment (rphillips) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Is there a case when the logging symlink is restored, and the map variable would need to be deleted?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 1 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: How does symlinkFirstObservedMissing sound ?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 2 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Fixed with a comment in code.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 3]
```diff
@@ -354,12 +356,25 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
 	// TODO(random-liu): Remove this after cluster logging supports CRI container log path.
 	logSymlinks, _ := osInterface.Glob(filepath.Join(legacyContainerLogsDir, fmt.Sprintf("*.%s", legacyLogSuffix)))
+	now := time.Now()
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
-			err := osInterface.Remove(logSymlink)
-			if err != nil {
-				klog.Errorf("Failed to remove container log dead symlink %q: %v", logSymlink, err)
+			if firstSeen, ok := cgc.symlinkFirstObservedMissing[logSymlink]; ok {
+				if now.Sub(firstSeen) > 30*time.Second {
```
Comment (mattjmcnaughton) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: If I'm reading this correctly, we are trying to resolve the race condition by adding a wait for X seconds... tbh that strategy makes me a little nervous. In particular, it feels very difficult to effectively write tests for.

Is there instead some expected state of the world that we could wait for before we remove the `logSymlink`? I.e. a state of the world that would allow us to be confident that we avoided the race condition.

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: The current formation does not introduce locking between pkg/kubelet/kuberuntime and pkg/kubelet/logs .
I think this is extensible compared to the locking approach.

Here is how log rotation works (see containerLogManager#rotateLatestLog):

1. rename current log to rotated log file (fmt.Sprintf("%s.%s", log, timestamp))
2. reopen container log
3. if #2 fails, rename rotated log file back

There is small but indeterministic amount of time during which log file doesn't exist.
This was why I chose the current approach.

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Currently logSymlinks is empty for tests from kuberuntime_gc_test :
```
	logSymlinks, _ := osInterface.Glob(filepath.Join(legacyContainerLogsDir, fmt.Sprintf("*.%s", legacyLogSuffix)))
```
We can make legacyContainerLogsDir a var so that the test can override.
The GC interval should also be made configurable (for testing).

For the new test, a goroutine would constantly rotate log file (with GC active). We can assert that the symlink to the log file is never gone.

@mattjmcnaughton 
What do you think ?

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: @mattjmcnaughton @rphillips 
I have updated the PR with a new unit test.

If you think using mock is the way to go, I will refine the test.

Thanks

Comment (mattjmcnaughton) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: I'd love to get the thoughts of another one of the folks tagged here - @Random-Liu @dims @derekwaynecarr . This diff has moved outside my area of expertise, so I'm not sure I have much to offer beyond my initial comment :)

**Comment by tedyu** [comment]
A variant of this fix is to spin off a goroutine which waits for short period of time and checks whether the symlinks with missing file are still eligible for GC.
Once the GC is done, the goroutine would finish running.

This allows the additional map to be localized to the goroutine and achieve faster GC compared with the current formation.

**Comment by mattjmcnaughton** [comment]
> A variant of this fix is to spin off a goroutine which waits for short period of time (3 seconds e.g.) and checks whether the symlinks with missing file are still eligible for GC.
> Once the GC is done, the goroutine would finish running.
> 
> This would achieve faster GC compared with the current formation.

Going to hold off on reviewing, because I'd love to hear from some other sig-node reviewers/approvers on the overall approach.

**Comment by tedyu** [comment]
Another option is for containerLogManager to scan legacyContainerLogsDir and find the symlink which points to the log file to be rotated.
If such symlink is found, re-create the symlink after the log rotation (if the symlink is removed by GC).

However, there is still race condition.
In containerGC#evictPodLogsDirectories :
```
		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
			err := osInterface.Remove(logSymlink)
```
1. containerLogManager starts log rotation, renaming current log to rotated log file
2. containerGC finds that symlink doesn't point to existing file
3. containerLogManager opens container log (and sees that symlink exists)
4. containerGC removes the symlink

**Comment by tedyu** [comment]
w.r.t. using lock to synchronize symlink gc and log rotation, currently containerLogManager is under feature gate.
```
	if containerRuntime == kubetypes.RemoteContainerRuntime && utilfeature.DefaultFeatureGate.Enabled(features.CRIContainerLogRotation) {
		// setup containerLogManager for CRI container runtime
		containerLogManager, err := logs.NewContainerLogManager(
```
It seems #89439 should be done first before introducing the lock.
Otherwise the lock would be of no use if the feature gate is off.

**Comment by tedyu** [comment]
[symlink-rm-prot.txt](https://github.com/kubernetes/kubernetes/files/4377312/symlink-rm-prot.txt)

**Comment by tedyu** [comment]
Here was the original proposal where grace period was used before removing symlink:

[symlink-grace-period-89160.txt](https://github.com/kubernetes/kubernetes/files/4377399/symlink-grace-period-89160.txt)

**Comment by rphillips** [comment]
I asked Ted to bring this to next week's sig-node meeting. It's on the agenda.

**Comment by tedyu** [comment]
If we can add some delay in containerLogManager#rotateLatestLog between renaming and reopening:
```
	if err := os.Rename(log, rotated); err != nil {
		return fmt.Errorf("failed to rotate log %q to %q: %v", log, rotated, err)
	}
	if err := c.runtimeService.ReopenContainerLog(id); err != nil {
```
there is chance the original race condition would be exposed.

**Comment by Random-Liu** [comment]
The lock seems a bit too complex to me.

Actually kubelet creates the symlink after the container is started. We should be able to check whether the container is running before removing symlink to fix the issue.

**Comment by tedyu** [comment]
@Random-Liu 
I was looking at the following interface where StartContainer and StopContainer are declared:
```
type ContainerManager interface {
```
I don't see method which tells us whether given container is gone.

For osInterface.Glob() call in containerGC#evictPodLogsDirectories, it seems to be general purpose.
We need to parse the filename for extracting container Id.
Please confirm whether the filename parsing can be replaced with other means of obtaining container Id.

Thanks

**Comment by tedyu** [comment]
[symlink-chk-container.txt](https://github.com/kubernetes/kubernetes/files/4411103/symlink-chk-container.txt)

**Comment by tedyu** [comment]
@Random-Liu @dchen1107 
Please see symlink-chk-container.txt attached above which follows your suggestion.
It is simpler than my previous proposal. However, in logSymlink():
```
	// Length of a filename cannot exceed 255 characters in ext4 on Linux.
	if len(logPath) > ext4MaxFileNameLen-len(suffix) {
		logPath = logPath[:ext4MaxFileNameLen-len(suffix)]
```
This means that there is a chance that the symlink filename doesn't give us the container Id.

Please let me know what you think.

**Comment by tedyu** [comment]
@Random-Liu @dchen1107
Let me know if I missed something in the above analysis

**Comment by Random-Liu** [comment]
`containers, err := cgc.manager.getKubeletContainers(true)` should return all (running) containers, and then we can just check that.

1) The symlink is created after container is started [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L211), so when the symlink is created, the container can only be in 3 states: running, exited, deleted.
2) We can make sure that we only remove the symlink when the container is deleted, which should be safe.

**Comment by derekwaynecarr** [comment]
thinking out loud after sig-node discussion:

we appear to lack a node e2e test that induces a rotation of log.
existing node_e2e test in log_path_test has no coverage in this space.
it would be great to add a test that verifies log rotation before fixing any edge cases around log rotation.

/cc @dchen1107

**Comment by tedyu** [comment]
```
we only remove the symlink when the container is deleted
```
@Random-Liu 
Can you confirm that the above is dependent on the parsing of container name out of the symlink filename ?
Is there possibility that part of the container name is truncated due to the length limitation of the symlink filename ?

**Comment by tedyu** [comment]
[symlink-lock-prot.txt](https://github.com/kubernetes/kubernetes/files/4446235/symlink-lock-prot.txt)

**Comment by tedyu** [comment]
Looking at log_path_test.go, the tests verify log is printed correctly.
To reproduce the race condition between log rotation and GC, there should be certain amount of logging which triggers log rotation. Another ingredient is container termination.

Let me think about how to setup test so that the race condition has a chance to surface.

**Comment by tedyu** [comment]
@Random-Liu 
Based on your comment above w.r.t. the ability of retrieving container with partial container Id, wouldn't calling cgc.client.ContainerStats(containerId) be more efficient compared to calling cgc.manager.getKubeletContainers() ?
This is based on the following:
* removing unhealthy symlink is not frequent operation
* if we use cgc.manager.getKubeletContainers(), it would be called outside the loop over symlinks. Meaning we always incur the extra cost of retrieving containers
* if we use cgc.client.ContainerStats(containerId), it would only be called when potentially unhealthy symlink is found.

With amortization, it seems calling cgc.client.ContainerStats(containerId) is more economical.

**Comment by tedyu** [comment]
@Random-Liu @dchen1107 
I have modified the description of the PR and refreshed the PR to reflect the result of discussion.

I chose cgc.client.ContainerStats(containerId) because of better amortized cost. See https://github.com/kubernetes/kubernetes/pull/89160#issuecomment-610639558

**Comment by tedyu** [comment]
@derekwaynecarr 
By shortening GC period and making parsedMaxSize small (1K), I was able to see the following in kubelet.log :
```
Apr 07 22:45:37 kind-worker kubelet[717]: I0407 22:45:37.611200     717 kuberuntime_gc.go:362] container still exists, not removing symlink: /var/log/containers/busybox-e8f88ccb-0a3f-4e40-af4a-cb504655c17d_container-probe-5751_busybox-3fa2103324039b46844069221408013eee39f4801c9032072dc187bc57700449.log
...
Apr 07 22:46:02 kind-worker kubelet[717]: I0407 22:46:02.672998     717 topology_manager.go:219] [topologymanager] RemoveContainer - Container ID: 3fa2103324039b46844069221408013eee39f4801c9032072dc187bc57700449
```
We can see that the actual removal of the container was 25 seconds after the check of the symlink.

Without the help of cgc.client.ContainerStats(), the symlink would have been removed at 22:45:37

**Comment by tedyu** [comment]
[kubelet-gc-race.log](https://github.com/kubernetes/kubernetes/files/4447386/kubelet-gc-race.log)

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 4]
```diff
@@ -356,9 +356,20 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
 	logSymlinks, _ := osInterface.Glob(filepath.Join(legacyContainerLogsDir, fmt.Sprintf("*.%s", legacyLogSuffix)))
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
+			if containerID, err := getContainerIDFromLegacyLogSymlink(logSymlink); err == nil {
+				if _, err := cgc.client.ContainerStats(containerID); err == nil {
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:360]: It seems weird to use `ContainerStats` here, it is to get container statistics data, not the file system `stats`. :)

Even we want something like `InspectContainer`, we should probably use `ContainerStatus` instead.

Container runtime calls are expensive. 10 `ContainerStatus` is more expensive than 1 `ListContainers`, because:
1) `ContainerStats` contains much more unused information than `ListContainers`, which means more marshal/unmarshal;
2) 10 rpc round trip is more expensive than one.

I think it is preferred to run `getKubeletContainers` once and use the result. :)

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: @Random-Liu 
Your comment has been addressed.

Comment (Random-Liu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Sorry, I was talking about `ContainerStatus`. :P

Comment (Random-Liu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: > Though we wouldn't find unhealthy symlink in each invocation of evictPodLogsDirectories()

Hm, that is true. I think you are right. Because the function will only be called when the symlink is unhealthy, even we do `ContainerStatus`, the overhead shouldn't be high (and could be even lower). :P 

If so, I think either `ContainerStatus` or `ListContainers` are good to me. Please feel free to change back to your original code, but please use `ContainerStatus` instead of `ContainerStats`. :)

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: This was the method called in the previous iteration:
```
	ContainerStats(containerID string) (*runtimeapi.ContainerStats, error)
```
I don't see ContainerStatus involved.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 5]
```diff
@@ -354,11 +355,36 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+		var err error
+		if containers, err = cgc.manager.getKubeletContainers(true); err != nil {
+			klog.V(5).Infof("unable to obtain containers: %v", err)
+			return nil
+		}
+	}
+outer:
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
+			if containerID, err := getContainerIDFromLegacyLogSymlink(logSymlink); err == nil {
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:369]: It is my bad, sorry. Feel free to change back to `ContainerStatus`, which is cleaner here.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 6]
```diff
@@ -354,11 +355,36 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+						if container.State != runtimeapi.ContainerState_CONTAINER_EXITED {
+							// the container still exists, don't remove the symlink
+							klog.V(5).Infof("container still exists, not removing symlink: %s", logSymlink)
+							continue outer
+						}
+						break
+					}
+				}
+			} else {
+				klog.V(5).Infof("unable to obtain container Id: %v", err)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:381]: Maybe log with higher level? This doesn't seem to be a normal case.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 7]
```diff
@@ -354,11 +355,36 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+	}
+outer:
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
+			if containerID, err := getContainerIDFromLegacyLogSymlink(logSymlink); err == nil {
+				for _, container := range containers {
+					if strings.HasPrefix(container.Id, containerID) {
+						if container.State != runtimeapi.ContainerState_CONTAINER_EXITED {
+							// the container still exists, don't remove the symlink
+							klog.V(5).Infof("container still exists, not removing symlink: %s", logSymlink)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:374]: `Container %q is still running, not removing symlink %q.`

And please add comment about why we are doing this.

Probably link to the issue, and explain the race condition with log rotation.

**Review by Random-Liu — COMMENTED** [review]
LGTM with several nits.

File: pkg/kubelet/kuberuntime/legacy.go [hunk 8]
```diff
@@ -44,6 +45,24 @@ func legacyLogSymlink(containerID string, containerName, podName, podNamespace s
...
+	if len(parts) == 0 {
+		return "", fmt.Errorf("unable to find separator in %s", logSymlink)
+	}
+	containerIDWithSuffix := parts[len(parts)-1]
+	suffix := fmt.Sprintf(".%s", legacyLogSuffix)
+	if !strings.HasSuffix(containerIDWithSuffix, suffix) {
+		return "", fmt.Errorf("%s doesn't end with %s", logSymlink, suffix)
+	}
+	containerIDWithoutSuffix := strings.TrimSuffix(containerIDWithSuffix, suffix)
+	if len(containerIDWithoutSuffix) < 6 {
```
[the remark this answers is not in the document]
Comment (tedyu) [reply pkg/kubelet/kuberuntime/legacy.go:60]: This is from docker's shortId def

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 6 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:381]: Changed to level 4

**Comment by tedyu** [comment]
@Random-Liu 
I have addressed your review comments.

**Comment by tedyu** [comment]
@dashpole @Random-Liu 
Your comments have been addressed.

Please take another look.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 9]
```diff
@@ -356,9 +356,34 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+						// There is small but indeterministic amount of time during which log file doesn't exist (between steps #1 and #2, between #1 and #3).
+						// Hence the symlink may be deemed unhealthy during that period.
+						// See https://github.com/kubernetes/kubernetes/issues/52172
+						//
+						// We only remove unhealthy symlink for dead containers
+						klog.V(5).Infof("Container %q is still running, not removing symlink %q.", containerID, logSymlink)
+						continue
+					}
+				} else {
+					klog.Infof("runtime returned: %v", err)
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:377]: Can we add contextual information to this?  E.g. `Error getting ContainerStatus for containerID %q: %v`

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 10]
```diff
@@ -356,9 +356,34 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+				}
+			} else {
+				klog.V(4).Infof("unable to obtain container Id: %v", err)
+			}
 			err := osInterface.Remove(logSymlink)
 			if err != nil {
 				klog.Errorf("Failed to remove container log dead symlink %q: %v", logSymlink, err)
+			} else {
+				klog.Infof("removed symlink %s", logSymlink)
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:386]: This seems quite verbose.  This probably belongs at V(4), if it is needed at all...

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 11]
```diff
@@ -356,9 +356,34 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
+			if containerID, err := getContainerIDFromLegacyLogSymlink(logSymlink); err == nil {
+				if status, err := cgc.manager.runtimeService.ContainerStatus(containerID); err == nil {
+					if status.State != runtimeapi.ContainerState_CONTAINER_EXITED {
+						// Here is how container log rotation works (see containerLogManager#rotateLatestLog):
+						//
+						// 1. rename current log to rotated log file whose filename contains current timestamp (fmt.Sprintf("%s.%s", log, timestamp))
+						// 2. reopen the container log
+						// 3. if #2 fails, rename rotated log file back to container log
```
Comment (sftim) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:366]: Here's how I'd do it:
1. Create blank log file in the same directory as the rename target, with a temporary name.
2. Atomically swap the current log file with the blank log file - Linux has a `RENAME_EXCHANGE` flag to `renameat2()` that could be helpful.

Does that seem like it'd work?
3. Rename the temporary name to the rotated name. If that fails, copy the file contents and unlink the rotated name.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 12]
```diff
@@ -356,9 +356,34 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
 	logSymlinks, _ := osInterface.Glob(filepath.Join(legacyContainerLogsDir, fmt.Sprintf("*.%s", legacyLogSuffix)))
 	for _, logSymlink := range logSymlinks {
 		if _, err := osInterface.Stat(logSymlink); os.IsNotExist(err) {
+			if containerID, err := getContainerIDFromLegacyLogSymlink(logSymlink); err == nil {
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:359]: nit: This is fairly deeply nested.  You should consider reducing this by replacing:
```golang
if err := ...; err == nil {
        // do things
} else {
        klog
}
```
with 
```golang
err := ...
if err != nil {
        klog
        continue
}
// do things
```

Here and below.  It also moves error handling closer to the call that generates the error

**Comment by tedyu** [comment]
@dashpole 
Your comment has been addressed.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 11 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Let me think about it.
Normally, with more intermediate files, we need to consider more error cases.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 13]
```diff
@@ -356,9 +356,33 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+				status, err := cgc.manager.runtimeService.ContainerStatus(containerID)
+				if err != nil {
+					klog.Infof("Error getting ContainerStatus for containerID %q: %v", containerID, err)
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:362]: This means if we can't get the container status (e.g. container runtime is down), then we remove the symlink.  Does this re-introduce the bug you were trying to fix?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 12 above)
Comment (dashpole) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:359]: Looks like you did it below, but not on this line.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 13 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:362]: runtimeService.ContainerStatus() returning error, in most cases, means that the container is gone.
We should treat such error the same as State == runtimeapi.ContainerState_CONTAINER_EXITED.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 12 above)
Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:359]: It would be very rare that log filename for container cannot be parsed (I have relaxed the length for container Id by 64-6 = 58 characters).
If short container Id cannot be obtained, the file should be allowed to be GC'ed.
So switching the if / else wouldn't yield change in indentation.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 13 above)
Comment (dashpole) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:362]: Ah, right.  Can you add a TODO saying that we should handle container not found (i.e. container was deleted) differently from other errors once we have https://github.com/kubernetes/kubernetes/issues/63336

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go:364]: @dashpole 
I have added the TODO

**Comment by tedyu** [comment]
Thanks for the quick turnaround in reviews, @dashpole

**Comment by tedyu** [comment]
@dchen1107
Can you take another look ?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 11 above)
Comment (sftim) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: On Windows you might need another approach: [`ReplaceFile()`](https://docs.microsoft.com/en-gb/windows/win32/api/winbase/nf-winbase-replacefilea?redirectedfrom=MSDN)

Maybe an idea for a future pull request?

Comment (tedyu) [reply pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Let me search for the golang equivalent.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 14]
```diff
@@ -356,9 +356,35 @@ func (cgc *containerGC) evictPodLogsDirectories(allSourcesReady bool) error {
...
+					continue
+				}
+			} else {
+				klog.V(4).Infof("unable to obtain container Id: %v", err)
+			}
 			err := osInterface.Remove(logSymlink)
 			if err != nil {
 				klog.Errorf("Failed to remove container log dead symlink %q: %v", logSymlink, err)
+			} else {
+				klog.V(4).Infof("removed symlink %s", logSymlink)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go:387]: %q

**Review by Random-Liu — COMMENTED** [review]
/lgtm
/approve

**Comment by matthias50** [comment]
@tedyu, would you mind creating cherry picks for 1.17 and 1.18 for this? We are seeing this in older k8s versions.
