### PR TITLE
validate AdvertiseAddress in kubeadm init and other case

### LINKED ISSUE #590: kube-proxy configmap not using apiserver-advertise-address
BUG REPORT
## Versions

**kubeadm version** (use `kubeadm version`):
```
kubeadm version: &version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.0.724+160270800f0995", GitCommit:"160270800f099538d9ba888201737b4dbab7587a", GitTreeState:"clean", BuildDate:"2017-11-30T03:05:52Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version**: 1.8.4
*I know this isn't really supported but shouldn't matter for this issue. Had to use the version since I depend on other changes*

## What happened?
I've created a cluster with kubeadm and a config specifying api / advertiseAddress. When looking at the kube-proxy config map I see the generated kubeconfig does not contain the advertiseAddress but one of the apiservers IPs.

## What you expected to happen?
As far as I understand https://github.com/kubernetes/kubernetes/blob/64ccd7665f6bc4792bf7263b7de88ce4a155e46c/cmd/kubeadm/app/phases/addons/proxy/proxy.go#L56, the generated config is supposed to use the advertiseAddress which is exactly what I need since my apiservers are behind a load balancer and have dynamic IPs.

## How to reproduce it (as minimally and precisely as possible)?
I haven't tried it but I assume all that is needed is running `kubeadm init --apiserver-advertise-address example.com`. The generated kube-proxy kubeconfig should use example.com but it doesn't.

## Anything else we need to know?
I just now realize the help for kubeadm init says this is suppose to be "The IP address the API Server will advertise it's listening on. 0.0.0.0 means the default network interface's address.". Which sounds like it's more a bind address than something that's advertised. This is a bit confusing. Can someone clarify?

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:

When using `kubeadm init --apiserver-advertise-address=****, `apiserver-advertise-address` can only be ipv4 or ipv6 address, if people use domain name in this field, will not use it and silently get hostIP.

Add a warning in this case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#590

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
/sig kubeadm
/cc @luxas 
@discordianfish

**Comment by fabriziopandini** [comment]
@Lion-Wei, thanks for this PR!
Before reviewing it, I was wandering if, instead of giving users an advice that kubeadm used the hostIP instead of the given dns name, we can:
1) improve `--apiserver-advertise-address` in order to handle dns names as well (if this is a use case we want to support)
or
2) block the init sequence before it starts if a dns name is passed to `--apiserver-advertise-address` (basically raise an error in validation phase)

What do you think about?
/cc @luxas

**Comment by Lion-Wei** [comment]
@fabriziopandini Thanks for replying. I'm not sure if make `--apiserver-advertise-address` accept dns name is a good idea, it's lots work, and I don't know weather there are other consideration, maybe need some discuss.
Add validation for `--apiserver-advertise-address` is a good idea for now, I think. There don't have any validate tight now, you can pass any string to this flag.

**Comment by discordianfish** [comment]
@Lion-Wei I'm not completely sure where apiserver-advertise-address is used. I know it's used in the kube-proxy config where supporting a DNS name should be trivial and is required to connect to a ELB on AWS since they don't have static IPs. The apiserver-advertise-address might be used in other place where it's harder to support this. If that's the case, maybe we should have a different flag for 'everything it can use a DNS name'?

**Comment by discordianfish** [comment]
So this is a requirement for HA and probably blocking #261 /cc @luxas

**Comment by petergardfjall** [comment]
@discordianfish : you're refering to https://github.com/kubernetes/kubeadm/issues/261, right?

**Comment by discordianfish** [comment]
@petergardfjall Oops, right. Thanks, fixed it!

**Comment by fabriziopandini** [comment]
@Lion-Wei @discordianfish 
I propose to discuss this at the next sig-meeting

Even if the advertise address is used in few parts of the kubeadm codebase, in the majority of cases no change are required because the value is used as a string. 
However there are two tricky cases that should be addressed:
- ipv4 or ipv6 tests
- api server probe address

**Comment by Lion-Wei** [comment]
@fabriziopandini

**Comment by fabriziopandini** [comment]
@Lion-Wei as discussed in SIG-meeting today, we should go for raising a validation error if a dns name is passed to `--apiserver-advertise-address`; the `apiserver-advertise-address` should be a valid ipv4 or ipv6 address.

If the user should use dns names he can always use `APIServerCertSANs`.

Thanks again for your availability to change the PR in this direction; if you need additional info or help in changing the PR feel free to ping me on slack.

**Comment by discordianfish** [comment]
@fabriziopandini Should I open a new issue for a option to set the kube-proxy endpoint?

**Comment by Lion-Wei** [comment]
@fabriziopandini Thanks for your attention. I will do that ASAP.
@discordianfish I'm not very familiar with `APIServerCertSANs`, I will look into it, to see if this flag can solve the problem.

**Comment by discordianfish** [comment]
To clarify this:
- --apiserver-advertise-address is the *bind address*. So it needs to be an IP on some interface or 0.0.0.0 to listen on all. Validating this was decided 👍 
- APIServerCertSANs specifies for which names the certificates generated are valid for. I'm already using this and it works fine 👍 
- TBH new flag would specify where kube-proxy is suppose to connect to (and this should support DNS names to use a ELB on AWS for example). Without this it's not possible to just run kubeadm init on every new master in a multi master setup, since it will always put in the IP of the last provisioned server in the kube-proxy configmap. 👎

**Comment by fabriziopandini** [comment]
@discordianfish please open a issue for the the kube-proxy endpoint in https://github.com/kubernetes/kubeadm/issues

**Comment by Lion-Wei** [comment]
@fabriziopandini , I found it's little complicated. Because we will set `cfg.API.AdvertiseAddress` to default in `SetInitDynamicDefaults` before pre-flight check. And need this args for http proxy check and other thins.
I think maybe use should check this args in `SetInitDynamicDefaults` part

**Comment by fabriziopandini** [comment]
@Lion-Wei 
I think that checking this arg in `SetInitDynamicDefaults` is acceptable (by the way we are already doing this for KubernetesVersion); please check that this apply to all the commands with `--advetise-address` in input.

**Review by fabriziopandini — COMMENTED** [review]
Thanks! 

One final question to be addressed: it is really necessary to validate parameters inside each phases or it is enough to implement the validation in `SetInitDynamicDefaults` (which is execute before each phases)?

File: cmd/kubeadm/app/phases/addons/proxy/proxy.go [hunk 1]
```diff
@@ -51,6 +52,10 @@ func EnsureProxyAddon(cfg *kubeadmapi.MasterConfiguration, client clientset.Inte
 		return fmt.Errorf("error when creating kube-proxy service account: %v", err)
 	}
 
+	// validate cfg.API.AdvertiseAddress.
+	if err := validation.ValidateApiserverAdvertiseAddress(cfg.API.AdvertiseAddress); err != nil {
```
Comment (fabriziopandini) [inline cmd/kubeadm/app/phases/addons/proxy/proxy.go]: The addon phase is called by three commands: init, upgrade, and phase addon; all this command executes 
`SetInitDynamicDefaults` (that executes a first validation of the apiserver) before invoking `EnsureProxyAddon` (that execute a second validation)
If possible, please remove the second validation

Comment (Lion-Wei) [reply cmd/kubeadm/app/phases/addons/proxy/proxy.go]: That't true, thanks, sorry didn't notice. : (
Then I guess there don't have other case to validate this flag.

Comment (Lion-Wei) [reply cmd/kubeadm/app/phases/addons/proxy/proxy.go]: @fabriziopandini Besides, need I add unit test of this case? Seems like `masterconfig.go` don't have any unit test.

**Comment by cblecker** [comment]
@Lion-Wei Please read the logs before requesting retesting. There is a lint error that's causing the verify job to fail:
```
I0103 06:36:21.459] Verifying verify-golint.sh
W0103 06:37:43.166] Errors from golint:
W0103 06:37:43.167] cmd/kubeadm/app/util/config/masterconfig.go:42:21: error strings should not be capitalized or end with punctuation or a newline
W0103 06:37:43.167] 
W0103 06:37:43.167] Please review the above warnings. You can test via "golint" and commit the result.
W0103 06:37:43.168] If the above warnings do not make sense, you can exempt this package from golint
W0103 06:37:43.168] checking by adding it to hack/.golint_failures (if your reviewer is okay with it).
W0103 06:37:43.168] 
I0103 06:37:43.268] FAILED   verify-golint.sh	82s
```

**Comment by Lion-Wei** [comment]
I think it's ready to review. 
I modified the validation, error out only in case of people use this flag but without ipv4 or ipv6 address. Does this logic make sense? @fabriziopandini 
Besides, in `kubeadm alpha phase controlplane all ` command, `apiserver-advertise-address` have hint said : "The IP address or DNS name the API server is accessible on", does this means we can use this flag with a DNA name in design?

**Comment by fabriziopandini** [comment]
@Lion-Wei  good catch about the flag description in phase controlplane! the same apply also to addons phase. 

Please change the flag description in both phases to "The IP address the API server is accessible on" and then this is lgtm for me 👍

**Review by fabriziopandini — APPROVED** [review]
/lgtm
Thanks!

**Comment by Lion-Wei** [comment]
@fabriziopandini , kindly ping, need another /lgtm. : )

**Comment by cblecker** [comment]
ping @krousey @luxas @timothysc for approval

**Comment by Lion-Wei** [comment]
Friendly ping @fabriziopandini @krousey . Since this has been ready for a while.

**Comment by fabriziopandini** [comment]
@Lion-Wei sorry I missed the lgtm removed
/lgtm
/CC @kubernetes/sig-cluster-lifecycle-pr-reviews for approval

**Comment by Lion-Wei** [comment]
friendly ping @jbeda @timothysc  ,looking forward for approve. : )

**Review by timothysc — APPROVED** [review]
/approve
