### PR TITLE
Make get-password robust against invalid kubeconfig entries

### LINKED ISSUE #5423: kube-up.sh failed with template error
```
$ cluster/kube-up.sh
Starting cluster using provider: gce
... calling verify-prereqs
... calling kube-up
Project: kubernetes-satnam2
Zone: us-central1-b
current-context: "kubernetes-satnam2_kubernetes/"
Running: cluster/../cluster/gce/../../cluster/../cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/darwin/amd64/kubectl config view -o template --template={{$dot := .}}{{with $ctx := index $dot "current-context"}}{{$user := index $dot "contexts" $ctx "user"}}{{index $dot "users" $user "username"}}{{end}}
F0312 21:55:41.334190   20430 command.go:399] error executing template '{{$dot := .}}{{with $ctx := index $dot "current-context"}}{{$user := index $dot "contexts" $ctx "user"}}{{index $dot "users" $user "username"}}{{end}}': 'template: output:1:69: executing "output" at <index $dot "contexts...>: error calling index: index of nil pointer'
----data----
map[contexts:map[kubernetes-satnam2_e2e-test-satnam:map[cluster:kubernetes-satnam2_e2e-test-satnam user:kubernetes-satnam2_e2e-test-satnam-admin]] current-context:kubernetes-satnam2_kubernetes/ preferences:map[] clusters:map[kubernetes-satnam2_e2e-test-satnam:map[server:https://23.251.158.195 certificate-authority:/Users/satnam/.kube/kubernetes-satnam2_e2e-test-satnam/kubernetes.ca.crt]] users:map[kubernetes-satnam2_kubernetes-admin:map[auth-path:/Users/satnam/.kube/kubernetes-satnam2_kubernetes/kubernetes_auth] kubernetes-satnam2_e2e-test-satnam-admin:map[auth-path:/Users/satnam/.kube/kubernetes-satnam2_e2e-test-satnam/kubernetes_auth]]]
```

### PR DESCRIPTION
**Pull request by j3ffml**
Properly close #5423, by making `get-password` do the right thing even if kubeconfig is borked.

cc @satnam6502

### CODE REVIEW

File: cluster/common.sh [hunk 1]
```diff
@@ -73,3 +73,31 @@ function clear-kubeconfig() {
...
+# KUBE_USER,KUBE_PASSWORD will be empty if no current-context is set, or
+# the current-context user does not exist or contain basicauth entries.
+function get-kubeconfig-basicauth() {
+  # Templates to safely extract the username,password for the current-context
+  # user.  The long chain of 'with' commands avoids indexing nil if any of the
+  # entries ("current-context", "contexts"."current-context", "users", etc)
+  # is missing.
+  # Note: we save dot ('.') to $root because the 'with' action overrides it.
+  # See http://golang.org/pkg/text/template/.
+  local username='''{{$root := .}}{{with index $root "current-context"}}{{with index $root "contexts" .}}{{with index . "user"}}{{with index $root "users" .}}{{index . "username"}}{{end}}{{end}}{{end}}{{end}}'''
```
Comment (filbranden) [inline cluster/common.sh]: Three single quotes `'''` does nothing, it's an empty string `''` followed by a normal `'`. Did you need something different here?

**Comment by filbranden** [comment]
One small nitpick, otherwise looks good.

File: cluster/common.sh (hunk 1 above)
Comment (jlowdermilk) [inline cluster/common.sh]: I forgot I added those; removed now. Was trying to do multiline, but that adds unwanted linebreaks in the output.

**Comment by filbranden** [comment]
Looks good, merging.
