### PR TITLE
Apiserver don't log stacktrace when proxying

### LINKED ISSUE #32747: kube-apiserver: httplog: don't print stack traces when proxies return 304s
I noticed that the code that prints stack traces when we return an unexpected status code runs even if we're just proxying that code from a service or pod. We should probably not do that.

### PR DESCRIPTION
**Pull request by PhilibertDugas**
**What this PR does / why we need it**:

When we are proxying unexpected status from a service or a pod, we print the stack traces (which is not the wanted behaviour). This is an attempt at fixing the issue #32747,

With the `RequestInfoResolver` struct, it's possible to inspect the request and get the `Verb`. In this case, the `proxy` value is what I was looking for to avoid logging stack traces.

I'm wrapping the `.Log()` call with an `if` statement to remove all stack traces logging when the call is a proxy from a service or a pod

Another approach would have been to add another kind of `StacktracePred` in the `httplog` package. I found this path to be trickier to code as it's currently only accepting int values.

**Which issue this PR fixes** : fixes #32747

**Special notes for your reviewer**: N/A

**Release note**:

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33286)

### CODE REVIEW

File: pkg/apiserver/handlers.go [hunk 1]
```diff
@@ -134,30 +134,33 @@ func tooManyRequests(req *http.Request, w http.ResponseWriter) {
...
-				http.StatusForbidden,
-				http.StatusNotModified,
-				errors.StatusUnprocessableEntity,
-				http.StatusSwitchingProtocols,
-			),
-		).Log()
 
+		requestInfo, err := resolver.GetRequestInfo(req)
+		if err != nil || requestInfo.Verb != "proxy" {
+			defer httplog.NewLogged(req, &w).StacktraceWhen(
```
Comment (lavalamp) [inline pkg/apiserver/handlers.go]: When it's a proxy, we still need to log it-- but we should omit the stack trace part.

e.g. something like this:

```go
logger := httplog.NewLogged(req, &w)
if proxy {
  logger.stacktracewhen(...)
}
defer logger.log()
```

Comment (PhilibertDugas) [inline pkg/apiserver/handlers.go]: Oops, makes sense 👍, pushed another commit

**Comment by lavalamp** [comment]
LGTM

@deads2k just fyi
