### PR TITLE
Fix service load balancer may not be cleaned up on corner case of type change

### LINKED ISSUE #78954: Service Load balancer may not be cleaned up on type change
**What happened**:
Service Load balancer may not be cleaned up on type change if below sequence happen:
1. Service type changes from `LoadBalancer` to `ClusterIP`
2. Service controller restarts/crashes before it gets a chance to process the update from 1.
3. Service controller starts up again and sees the service doesn't want load balancer, hence skips it.
4. The load balancer resource sticks around even if it is no longer needed by the service.

Note that this is a different issue than https://github.com/kubernetes/kubernetes/issues/53451, as load balancer resource will still be cleaned up when the service object is deleted, just not when the type change happens.

**Anything else we need to know?**:
This is a corner case that is not covered by the initial service load balancer finalizer implementation (https://github.com/kubernetes/kubernetes/pull/78262).

This can probably be fixed in a trivial way --- make sure the `addFunc` handler takes in service with non-LoadBalancer type but has finalizer attached:
https://github.com/kubernetes/kubernetes/blob/aa3f81d657c1d4b7c789352af7179c08508adc3c/pkg/controller/service/service_controller.go#L140-L145

I will put more thoughts later.

cc @bowei @andrewsykim

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #78954 

**Special notes for your reviewer**:
For service that don't want loadBalancers but has finalizer means need to be cleaned up.
So, it should be include in function `needsCleanup(...)`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority important-soon

File: pkg/controller/service/service_controller_test.go [hunk 1]
```diff
@@ -833,45 +833,59 @@ func TestProcessServiceDeletion(t *testing.T) {
 
 }
 
+// Test cases:
```
Comment (MrHohn) [inline pkg/controller/service/service_controller_test.go]: Not sure if it is worth it to put excessive description. I'm hoping the test case description itself would be clear enough. But since you have added it, let's keep it then.

**Review by MrHohn — APPROVED** [review]
Thanks, SG to have this in `needsCleanup`.
/approve

File: pkg/controller/service/service_controller_test.go (hunk 1 above)
Comment (RainbowMango) [reply pkg/controller/service/service_controller_test.go]: There are three factors, finalizer, timestamp and type, means we need 8 testcases. But some cases can be aggregated together. Comment here maybe make sense for readers.

File: pkg/controller/service/service_controller.go [hunk 2]
```diff
@@ -136,6 +136,7 @@ func New(
 		cache.ResourceEventHandlerFuncs{
 			AddFunc: func(cur interface{}) {
 				svc, ok := cur.(*v1.Service)
+				// Check cleanup here can provide a remedy when controller failed to handle changes before it exiting (e.g. crashing, restart, etc.).
```
Comment (MrHohn) [inline pkg/controller/service/service_controller.go]: nit: Could you wrap the comment into two lines?
```golang
// Check cleanup here can provide a remedy when controller failed to handle
// changes before it exiting (e.g. crashing, restart, etc.).
```

**Review by MrHohn — APPROVED** [review]
Sorry one final nit, otherwise looks good

File: pkg/controller/service/service_controller.go (hunk 2 above)
Comment (RainbowMango) [reply pkg/controller/service/service_controller.go]: Sure.

**Comment by MrHohn** [comment]
Thanks!
/lgtm
