### PR TITLE
DRA: refactor checkpointing

### LINKED ISSUE #123552: DRA: kubelet: checkpoint checksum changes when API gets extended
### What happened?

When adding the `StructuredData` field to `resourcev1alpha2.ResourceHandle`, old checkpoint files became invalid because the checksum that gets calculated by hashing the `spew` output in `pkg/util/hash` no longer matches. This caused kubelet to fail to start with:
```
E0228 10:46:47.293483  363727 run.go:74] "command failed" err="failed to run Kubelet: failed to create claimInfo cache: error calling GetOrCreate() on checkpoint state: failed to get checkpoint dra_manager_state: checkpoint is corrupted"
```

Here's what the checksum in a unit test gets calculcated for:
```
"(*state.DRAManagerCheckpoint){Version:(string)v1 Entries:(state.ClaimInfoStateList)[{DriverName:(string)[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/) ClassName:(string)class-name ClaimUID:(types.UID)067798be-454e-4be4-9047-1aa06aea63f7 ClaimName:(string)example Namespace:(string)default PodUIDs:(sets.Set[string])map[139cdb46-f989-4f17-9561-ca10cfb509a6:{}] ResourceHandles:([]v1alpha2.ResourceHandle)[{DriverName:(string)[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/) Data:(string){\"a\": \"b\"} StructuredData:(*v1alpha2.StructuredResourceHandle)<nil>}] CDIDevices:(map[string][]string)map[[test-driver.cdi.k8s.io](http://test-driver.cdi.k8s.io/):[[example.com/example=cdi-example]]}]](http://example.com/example=cdi-example]]%7D]) Checksum:(checksum.Checksum)0}"
```

Note the new `StructuredData:(*v1alpha2.StructuredResourceHandle)<nil>`.

### What did you expect to happen?

Not sure what the right behavior is. Perhaps kubelet should have ignored the invalid checkpoint?

### How can we reproduce it (as minimally and precisely as possible)?

Revert the pkg/kubelet/cm/dra/state/state_checkpoint_test.go update in https://github.com/kubernetes/kubernetes/pull/123516.

### Anything else we need to know?

The state.DRAManagerCheckpoint contains a version field, which is set to v1.I think that's where things fall apart: that version must exactly match the type that gets serialized, which is not the case here. The type changes over time, but the version is fixed.

Let's reconsider what should get checkpointed and how we can make that stable. Also, is checkpointing really worth it? What bad things happen if we remove it?

### Kubernetes version

master

### Cloud provider

n/a

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

/sig node
/cc @bart0sh @klueska

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

Current implementation of the DRA checkpointing doesn't guarantee that checkpointing would work after changing DRA data structures and doesn't support Kubelet downgrades.

This PR reimplements DRA checkpointing implementation by isolating DRA checkpointing structures into a separate versioned internal API.

#### Which issue(s) this PR fixes:

Fixes #123552

#### Special notes for your reviewer:

This is a continuation of the work done in https://github.com/pohly/kubernetes/pull/51

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/cm/dra/checkpoint/checkpointer.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+import (
+	"fmt"
+	"sync"
+
+	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager"
+	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager/errors"
+	state "k8s.io/kubernetes/pkg/kubelet/cm/dra/state/v1"
+)
+
+type Checkpointer interface {
```
Comment (pohly) [inline pkg/kubelet/cm/dra/checkpoint/checkpointer.go:28]: Why is this an interface? A struct with no external fields would be simpler.

File: pkg/kubelet/cm/dra/checkpoint/checkpoint.go [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+// Checkpoint represents a structure to store DRA checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
+	// See state.CheckpointData for the details
+	Data string
+	// Checksum is a checksum of Data
+	Checksum checksum.Checksum
+}
+
+type CheckpointData struct {
```
Comment (pohly) [inline pkg/kubelet/cm/dra/checkpoint/checkpoint.go:42]: From an architectural perspective it looks like this struct and the API group and version should be in the v1 package.

Then this file could be completely agnostic of the underlying type by using a scheme. But I understand that this is too much for now and doesn't pay off unless we actually need conversion, so fine with me.

File: pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go [hunk 3]
```diff
@@ -0,0 +1,339 @@
...
+	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager"
+	testutil "k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/state/testing"
+	state "k8s.io/kubernetes/pkg/kubelet/cm/dra/state/v1"
+)
+
+const testingCheckpoint = "dramanager_checkpoint_test"
+
+// TODO (https://github.com/kubernetes/kubernetes/issues/123552): reconsider what data gets stored in checkpoints and whether that is really necessary.
+//
+// As it stands now, a "v1" checkpoint contains data for types like the resourceapi.ResourceHandle
```
Comment (pohly) [inline pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go:37]: This comment is out-dated. There is no such ResourceHandle anymore.

File: pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go [hunk 4]
```diff
@@ -0,0 +1,339 @@
...
+// which may change over time as new fields get added in a backward-compatible way (not unusual
+// for API types). That breaks checksuming with pkg/util/hash because it is based on spew output.
```
Comment (pohly) [inline pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go:39]: Also out-dated.

**Review by pohly — COMMENTED** [review]
Some nits, but overall this looks okay.

I'll leave the final LGTM and approval to @klueska.

**Comment by pohly** [comment]
@bart0sh: there are linter issues. Check with `hack/verify-golangci-lint.sh ./pkg/kubelet/...`. Those have to be fixed.

Additional things pointed out by `hack/verify-golangci-lint.sh -a -n ./pkg/kubelet/...` are hints and can be fixed at your own discretion.

**Comment by klueska** [comment]
Since we don't have a good separation for this yet, I'd rather just move all the new logic into a single unversioned package called 'state'. We can then refactor it for 1.32 once we have a better feel for how to use apimachnwry for helping with any conversion code.

File: pkg/kubelet/cm/dra/checkpoint/checkpoint.go [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+	CheckpointAPIVersion = CheckpointAPIGroup + "/" + state.Version
+)
+
+// Checkpoint represents a structure to store DRA checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
+	// See state.CheckpointData for the details
+	Data string
+	// Checksum is a checksum of Data
+	Checksum checksum.Checksum
```
Comment (pohly) [inline pkg/kubelet/cm/dra/checkpoint/checkpoint.go:39]: One more thing (a bit more than a nit): can we use some checksum algorithm from the Go standard library instead of `checksum.Checksum`?

I know it's based on a standard Kubernetes util package (https://github.com/kubernetes/kubernetes/blob/master/pkg/util/hash/hash.go), but under the hood it depends on third-party code (spew, see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/dump/dump.go).

I can't help thinking that this is going to break at some point, and it's complete overkill here because a string is sequence of bytes that can be easily hashed without "spewing" it first back into another string.

File: pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go (hunk 4 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/checkpoint/checkpointer_test.go]: removed

File: pkg/kubelet/cm/dra/checkpoint/checkpoint.go (hunk 5 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/checkpoint/checkpoint.go]: changed to hash/crc32.ChecksumIEEE from standard library, PTAL.

File: pkg/kubelet/cm/dra/claiminfo.go [hunk 6]
```diff
@@ -25,7 +25,7 @@ import (
 	resourceapi "k8s.io/api/resource/v1alpha3"
 	"k8s.io/apimachinery/pkg/types"
 	"k8s.io/apimachinery/pkg/util/sets"
-	"k8s.io/kubernetes/pkg/kubelet/cm/dra/state"
+	state "k8s.io/kubernetes/pkg/kubelet/cm/dra/state"
```
Comment (klueska) [inline pkg/kubelet/cm/dra/claiminfo.go:28]: unnecessary, since the package name is already `state`

File: pkg/kubelet/cm/dra/claiminfo.go [hunk 7]
```diff
@@ -40,7 +40,7 @@ type ClaimInfo struct {
 // claimInfoCache is a cache of processed resource claims keyed by namespace/claimname.
 type claimInfoCache struct {
 	sync.RWMutex
-	state     state.CheckpointState
+	state     state.Checkpointer
```
Comment (klueska) [inline pkg/kubelet/cm/dra/claiminfo.go:43]: is it too invasive to rename this variable to `checkpointer`?

File: pkg/kubelet/cm/dra/state/checkpoint.go [hunk 8]
```diff
@@ -18,51 +18,88 @@ package state
...
-	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager/checksum"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager/errors"
 )
 
-var _ checkpointmanager.Checkpoint = &DRAManagerCheckpoint{}
+const (
+	CheckpointAPIGroup   = "checkpoint.dra.kubelet.k8s.io"
+	CheckpointKind       = "DRACheckpoint"
+	CheckpointAPIVersion = CheckpointAPIGroup + "/" + Version
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpoint.go:30]: I think we should get rid of the `Version` variable now and just hard-code this as `/v1` now that we have refactored to a single package

File: pkg/kubelet/cm/dra/state/checkpoint.go [hunk 9]
```diff
@@ -18,51 +18,88 @@ package state
...
+}
 
-// DRAManagerCheckpoint struct is used to store pod dynamic resources assignments in a checkpoint
-type DRAManagerCheckpoint struct {
-	Version  string             `json:"version"`
-	Entries  ClaimInfoStateList `json:"entries,omitempty"`
-	Checksum checksum.Checksum  `json:"checksum"`
+type CheckpointData struct {
+	metav1.TypeMeta
+	Entries ClaimInfoStateList
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpoint.go:43]: Let's be explicit and call the field the same name as the type, i.e. `ClaimInfoStateList`. This makes it more obvious how / what fields to ignore as we evolve this struct with new fields in the future.

File: pkg/kubelet/cm/dra/state/checkpoint.go [hunk 10]
```diff
@@ -18,51 +18,88 @@ package state
...
 
-// VerifyChecksum verifies that current checksum of checkpoint is valid
-func (dc *DRAManagerCheckpoint) VerifyChecksum() error {
-	ck := dc.Checksum
-	dc.Checksum = 0
-	err := ck.Verify(dc)
-	dc.Checksum = ck
-	return err
+// GetEntries returns list of claim info states from checkpoint
+func (cp *Checkpoint) GetEntries() (ClaimInfoStateList, error) {
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpoint.go:98]:
```suggestion
func (cp *Checkpoint) GetClaimInfoStateList() (ClaimInfoStateList, error) {
```

File: pkg/kubelet/cm/dra/state/checkpointer.go [hunk 11]
```diff
@@ -0,0 +1,97 @@
...
+func NewCheckpointer(stateDir, checkpointName string) (Checkpointer, error) {
+	if len(checkpointName) == 0 {
+		return nil, fmt.Errorf("received empty string instead of checkpointName")
+	}
+
+	checkpointManager, err := checkpointmanager.NewCheckpointManager(stateDir)
+	if err != nil {
+		return nil, fmt.Errorf("failed to initialize checkpoint manager: %w", err)
+	}
+	checkpointer := &checkpointer{
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpointer.go:49]: net: newline between these two lines

```suggestion
	}
	
	checkpointer := &checkpointer{
```

File: pkg/kubelet/cm/dra/state/state.go [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+package state
+
+import (
+	"k8s.io/apimachinery/pkg/types"
+	"k8s.io/apimachinery/pkg/util/sets"
+)
+
+const (
+	Version = "v1"
+)
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/state.go:26]: drop this

File: pkg/kubelet/cm/dra/state/state.go [hunk 13]
```diff
@@ -0,0 +1,63 @@
...
+// DriverState is used to store per-device claim info state in a checkpoint
+// +k8s:deepcopy-gen=true
+type DriverState struct {
+	Devices []Device
+}
+
+// Device is how a DRA driver described an allocated device in a claim
+// to kubelet. RequestName and CDI device IDs are optional.
+// +k8s:deepcopy-gen=true
+type Device struct {
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/state.go:58]:
```suggestion
type DeviceState struct {
```

File: pkg/kubelet/cm/dra/state/checkpoint.go [hunk 14]
```diff
@@ -18,51 +18,88 @@ package state
...
+	var cpData CheckpointData
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpoint.go:99]: nit
```suggestion
	var data CheckpointData
```

File: pkg/kubelet/cm/dra/state/checkpoint.go [hunk 15]
```diff
@@ -18,51 +18,88 @@ package state
...
-		Entries: ClaimInfoStateList{},
+	cpDataBytes, err := json.Marshal(cpData)
+	if err != nil {
+		return nil, err
 	}
+
+	return &Checkpoint{
+		Data:     string(cpDataBytes),
+		Checksum: crc32.ChecksumIEEE(cpDataBytes),
+	}, nil
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpoint.go:64]:
```suggestion
	cp := &Checkpoint{
		Data:     string(cpDataBytes),
		Checksum: crc32.ChecksumIEEE(cpDataBytes),
	}
	
	return cp, nil
```

File: pkg/kubelet/cm/dra/claiminfo.go (hunk 6 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/claiminfo.go]: done

File: pkg/kubelet/cm/dra/claiminfo.go (hunk 7 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/claiminfo.go]: done

File: pkg/kubelet/cm/dra/state/checkpoint.go (hunk 8 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpoint.go]: done

File: pkg/kubelet/cm/dra/state/checkpoint.go (hunk 9 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpoint.go]: done

File: pkg/kubelet/cm/dra/state/checkpoint.go (hunk 10 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpoint.go]: done

File: pkg/kubelet/cm/dra/state/checkpointer.go (hunk 11 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpointer.go]: done

File: pkg/kubelet/cm/dra/state/state.go (hunk 12 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/state.go]: done

File: pkg/kubelet/cm/dra/state/checkpoint.go (hunk 14 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpoint.go]: done

File: pkg/kubelet/cm/dra/state/checkpoint.go (hunk 15 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpoint.go]: done

**Comment by bart0sh** [comment]
all done, PTAL again, thanks!

File: pkg/kubelet/cm/dra/state/checkpointer.go [hunk 16]
```diff
@@ -0,0 +1,98 @@
...
+		return nil, fmt.Errorf("failed to create new checkpoint: %w", err)
+	}
+
+	err = sc.checkpointManager.GetCheckpoint(sc.checkpointName, checkpoint)
+	if errors.Is(err, checkpointerrors.ErrCheckpointNotFound) {
+		err = sc.store(checkpoint)
+		if err != nil {
+			return nil, fmt.Errorf("failed to store checkpoint %v: %w", sc.checkpointName, err)
+		}
+		return NewCheckpoint(ClaimInfoStateList{})
```
Comment (klueska) [inline pkg/kubelet/cm/dra/state/checkpointer.go:75]: Can we just return `checkpoint` here, or does it somehow get corrupted by the call to `GetCheckpoint()`?

Comment (klueska) [reply pkg/kubelet/cm/dra/state/checkpointer.go:75]: Also, what is the difference between `NewCheckpoint(nil)` (as you have above) and `NewCheckpoint(ClaimInfoStateList{})` (as you have here).

File: pkg/kubelet/cm/dra/checkpoint/checkpoint.go (hunk 2 above)
Comment (klueska) [reply pkg/kubelet/cm/dra/checkpoint/checkpoint.go]: I had ed move everything into an unversioned package for now (but keep the APIGroup and v1 versioning in the type). That way we can figure out the right way to move things around for 1.32 without overcomplicating things for now.

**Comment by klueska** [comment]
I have one outstanding comment, but its minor, so I'm going to go ahead and approve this now, pending it being addressed (at which point I'll LGTM).

Thanks for your patience with all the back-and-forth on this @bart0sh 

/approve

File: pkg/kubelet/cm/dra/state/checkpointer.go (hunk 16 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpointer.go:75]: I don't think it gets corrupted. I've changed the code to return checkpoint there.

Comment (bart0sh) [reply pkg/kubelet/cm/dra/state/checkpointer.go:75]: > Also, what is the difference between NewCheckpoint(nil) (as you have above) and NewCheckpoint(ClaimInfoStateList{}) (as you have here).

`ClaimInfoStateList` field is set to whatever is passed to NewCheckpoint. As we don't modify this field directly, I don't think it's harmless to let it be nil. However, if you think it's safer to set it to empty list when `NewCheckpoint` is called with `nil` parameter, I can do that.

**Review by klueska — COMMENTED** [review]
/lgtm

File: pkg/kubelet/cm/dra/state/checkpointer.go (hunk 16 above)
Comment (klueska) [reply pkg/kubelet/cm/dra/state/checkpointer.go]: The difference is that it will turn up in the checkpoint file as `nil` vs. `[]`. I think either is fine so long as we only ever support one or the other.

**Comment by bart0sh** [comment]
@klueska @pohly can you lgtm, please? last change was a fix for typo in a comment.
