### PR TITLE
Do not fail on error when deleting ingress

### LINKED ISSUE #48239: ingress-upgrade failed after changing subnetwork
Last night, all upgrade tests failed with 1.7 builds https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.7/38. For example, the upgrade build https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster-new&include-filter-by-regex=-upgrade

started failing with build 79. We identified the culprit is subnetwork change: https://github.com/kubernetes/kubernetes/pull/48143#issuecomment-311607056

After merging the fix https://github.com/kubernetes/kubernetes/pull/48202, all upgrade tests passed as showing with build 86 and above at 

https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gce-upgrade-cluster-new&include-filter-by-regex=-upgrade

@gmarek @nicksardo @MrHohn Could you guys triage this issue?

### PR DESCRIPTION
**Pull request by nicksardo**
Fixes #48239

If the api server or master is unavailable, the test should manually teardown load balancer resources. 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/framework/ingress_utils.go [hunk 1]
```diff
@@ -882,9 +882,12 @@ func (j *IngressTestJig) GetRootCA(secretName string) (rootCA []byte) {
 	return
 }
 
-// DeleteIngress deletes the ingress resource
+// DeleteIngress attempts to delete the ingress resource and logs errors if they occur.
 func (j *IngressTestJig) DeleteIngress() {
```
Comment (bowei) [inline test/e2e/framework/ingress_utils.go]: probably should rename this to TryToDeleteIngress

**Comment by nicksardo** [comment]
@dchen1107 informs me that we can merge this to master anytime, but we will cherry pick to 1.7 branch after release since this is only test changes.
