### PR TITLE
clear pod's .status.nominatedNodeName when necessary

### LINKED ISSUE #106780: scheuler not always clear a preemptor's nominatedNodeName as expected
A pod's `.status.nominatedNodeName` is set by the scheduler to mark this pod as a preemptor (let's call it P1), with a cost of preempting low-priority pods (let's call it P0). The preemptor doesn't get scheduled instantly; instead, it has to wait for the victims to be fully terminated and then deleted physically. During the waiting period, some cases may happen:

#### Case 1

A high-priority pod P2 comes in, and it needs to preempt some victims (P0) to make room for itself. In this case, P1's `.status.nominatedNodeName` is also cleared as it may not fit anymore.

https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/pkg/scheduler/framework/preemption/preemption.go#L340-L341

We're good on this case.

#### Case 2

A high-priority pod P2 comes in. It doesn't need to preempt any victim to be schedulable. For example, let's say a node has 4 CPUs, P0/P1/P2 requests 2/3/1.5 CPUs respectively. In this case, P2's placement actually makes P1 no longer schedulable. But note here, P1's `.status.nominatedNodeName` **stays forever** unless it's deleted physically.

```
# Suppose a node has 4 cpus
# p0 requests 2 cpus
NAME   READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Running   0          6s    10.244.2.10   kind-worker   <none>           <none>

# p1 requests 3 cpus
NAME   READY   STATUS        RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Terminating   0          15s   10.244.2.10   kind-worker   <none>           <none>
p1     0/1     Pending       0          4s    <none>        <none>        kind-worker      <none>

# p2 requests 1.5 cpus
NAME   READY   STATUS        RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Terminating   0          22s   10.244.2.10   kind-worker   <none>           <none>
p1     0/1     Pending       0          11s   <none>        <none>        kind-worker      <none>
p2     1/1     Running       0          4s    10.244.2.11   kind-worker   <none>           <none>
......<after p0's grace termination period ends>......
NAME   READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p1     0/1     Pending   0          93s   <none>        <none>        kind-worker      <none>
p2     1/1     Running   0          86s   10.244.2.11   kind-worker   <none>           <none>

# re-apply p0
NAME   READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
p0     0/1     Pending   0          2s      <none>        <none>        <none>           <none>
p1     0/1     Pending   0          2m50s   <none>        <none>        kind-worker      <none>
p2     1/1     Running   0          2m43s   10.244.2.11   kind-worker   <none>           <none>
# p0 cannot be scheduled unless p1 gets physically deleted, which is not desired
```

Because P1's `.status.nominatedNodeName` is not cleared, it reserved 2 CPUs in the internal scheduler cache, which will block further low-priority Pods' scheduling.

There are some other variants of this case:

- a regular (not necessarily high-priority) pod's placement on another node makes P1's inter-pod constraints (e.g., podantiaffinity, podtopologyspread) no longer satisfied
- without intervention of other pods, P1 failed the scheduling due to unexpected failures like "Node not found" (reported in #85677)

#### Case 3

P1 does get through the Filter phase and gets assumed, but it's controller by a Permit plugin, and afterwards timed out (or rejected) in the WaitOnPermit() phase (in binding cycle). This case doesn't happen in the vanilla default scheduler, but is reported in coscheduling pluign (https://github.com/kubernetes-sigs/scheduler-plugins/issues/293)

#### Expection

In both case 2 and 3, the Pod's `.status.nominatedNodeName` should be cleared properly.

/kind bug
/sig scheduling

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/sig scheduling

#### What this PR does / why we need it:

Clear a pod's .status.nominatedNodeName when needed.

#### Which issue(s) this PR fixes:

Fixes #106780 #85677

#### Special notes for your reviewer:

We may consider back-porting this as it's a bug fix.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug that a pod's .status.nominatedNodeName is not cleared properly, and thus over-occupied system resources.
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
cc @alculquicondor @mateuszlitwin

File: test/integration/scheduler/preemption_test.go [hunk 1]
```diff
@@ -932,98 +933,209 @@ func TestPreemptionRaces(t *testing.T) {
...
+					st.MakePod().Name("medium").Priority(mediumPriority).Req(map[v1.ResourceName]string{v1.ResourceCPU: "1"}).Obj(),
+				},
+			},
+			postChecks: []func(cs clientset.Interface, pod *v1.Pod) error{
+				testutils.WaitForPodToSchedule,
+				waitForNominatedNodeName,
+			},
+			// Delete the node to simulate an ErrNoNodesAvailable error.
+			deleteNode:       true,
+			podNamesToDelete: []string{"low"},
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption_test.go:1038]: In a real cluster, this is actually optional.

However, in an integration test it may flake without this - a node deletion event wouldn't trigger moving the preemptor back to activeQ, so if the preemptor happens to be backoffed and the 30 seconds timeout may not be enough. So add a pod deletion here to actively trigger retrying the preemptor.

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -466,18 +471,20 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
 			// Pod did not fit anywhere, so it is counted as a failure. If preemption
 			// succeeds, the pod should get counted as a success the next time we try to
 			// schedule it. (hopefully)
 			metrics.PodUnschedulable(fwk.ProfileName(), metrics.SinceInSeconds(start))
 		} else if err == ErrNoNodesAvailable {
+			nominatedNode = pointer.StringPtr("")
 			// No nodes available is counted as unschedulable rather than an error.
 			metrics.PodUnschedulable(fwk.ProfileName(), metrics.SinceInSeconds(start))
 		} else {
+			nominatedNode = pointer.StringPtr("")
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:487]: in theory, this is the case of a transient error. Perhaps we shouldn't clear the nominated node here?

File: pkg/scheduler/framework/preemption/preemption.go [hunk 3]
```diff
@@ -123,8 +123,15 @@ type Evaluator struct {
 	Interface
 }
 
+// Preempt returns a PostFilterResult carrying suggested nominatedNodeName, along with a Status.
+// The semantics of returned <PostFilterResult, Status> varies on different scenarios:
+// - <nil, Unschedulable/Error>. This denotes it's a transient/rare error that may be self-healed in future cycles.
```
Comment (alculquicondor) [inline pkg/scheduler/framework/preemption/preemption.go:128]: <nil, Unschedulable> also happens when there are already other pods being terminated by the preemptor. That's not an error.

Should the nominated node name be cleared in that case? If not, can you add an integration test to make sure it's not cleared?

File: pkg/scheduler/scheduler.go [hunk 4]
```diff
@@ -299,15 +300,19 @@ func (sched *Scheduler) Run(ctx context.Context) {
...
+func (sched *Scheduler) recordSchedulingFailure(fwk framework.Framework, podInfo *framework.QueuedPodInfo, err error, reason string, nominatedNode *string) {
 	sched.Error(podInfo, err)
 
 	// Update the scheduling queue with the nominated pod information. Without
 	// this, there would be a race condition between the next scheduling cycle
 	// and the time the scheduler receives a Pod Update for the nominated pod.
 	// Here we check for nil only for tests.
 	if sched.SchedulingQueue != nil {
-		sched.SchedulingQueue.AddNominatedPod(podInfo.PodInfo, nominatedNode)
+		var nnn string
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:311]: It looks like `nil` and empty string have the same result here. Why use a pointer?

File: pkg/scheduler/scheduler.go [hunk 5]
```diff
@@ -333,17 +338,17 @@ func truncateMessage(message string) string {
 	return message[:max-len(suffix)] + suffix
 }
 
-func updatePod(client clientset.Interface, pod *v1.Pod, condition *v1.PodCondition, nominatedNode string) error {
+func updatePod(client clientset.Interface, pod *v1.Pod, condition *v1.PodCondition, nominatedNode *string) error {
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:341]: Document that `nil` nominatedNode means not to update.

File: pkg/scheduler/scheduler.go [hunk 6]
```diff
@@ -466,18 +471,20 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
+				if result != nil {
+					nominatedNode = &result.NominatedNodeName
 				}
 			}
 			// Pod did not fit anywhere, so it is counted as a failure. If preemption
 			// succeeds, the pod should get counted as a success the next time we try to
 			// schedule it. (hopefully)
 			metrics.PodUnschedulable(fwk.ProfileName(), metrics.SinceInSeconds(start))
 		} else if err == ErrNoNodesAvailable {
+			nominatedNode = pointer.StringPtr("")
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:483]: nit: `pointer.String`

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go:311]: Ah, it's more about `updatePod` below.

However, it looks like `AddNominatedPod` looks at the existing `nominatedNode` in the status when you pass empty string. This means that the nominated node name is not actually cleared from the cache.

File: pkg/scheduler/framework/preemption/preemption.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/preemption/preemption.go:128]: I think it's not cleared in this case, which should be correct.

Comment (Huang-Wei) [reply pkg/scheduler/framework/preemption/preemption.go:128]: > Should the nominated node name be cleared in that case?

Nope, it shouldn't be cleared and that's the happy path.

> If not, can you add an integration test to make sure it's not cleared?

I think it's covered already. We have integration as well as e2e tests to cover the basics of preemption.

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler.go:311]: > Ah, it's more about updatePod below.

Yes.

> However, it looks like AddNominatedPod looks at the existing nominatedNode in the status when you pass empty string.

Not quite. The entry in internal nominator implementation will be cleared first in all cases:

https://github.com/kubernetes/kubernetes/blob/4cc1abf2474efee4e358626856b5fc8a5675baed/pkg/scheduler/internal/queue/scheduling_queue.go#L834-L845

File: pkg/scheduler/scheduler.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler.go:341]: done.

File: pkg/scheduler/scheduler.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler.go:483]: done.

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler.go:487]: It's a bit debatable depends how we interpret this kind of error. If we believe it can be auto-healed, we shouldn't clear it; otherwise clear it to prevent the pod from occupying resources.

I don't have a strong option as personally, I don't have real-world data points to determine if it's transient and how transient it is... I'm giving a pessimistic judgment here :(

File: pkg/scheduler/scheduler.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go:311]: I think the problem is this line:

https://github.com/kubernetes/kubernetes/blob/4cc1abf2474efee4e358626856b5fc8a5675baed/pkg/scheduler/internal/queue/scheduling_queue.go#L841

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler.go]: I also don't have a strong opinion. But I think that if the pod really needs preemption, it would get a nominated node in the next scheduling attempt. So it seems safer for utilization to clear.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 7]
```diff
@@ -692,7 +693,7 @@ func (npm *nominator) DeleteNominatedPodIfExists(pod *v1.Pod) {
 // This is called during the preemption process after a node is nominated to run
 // the pod. We update the structure before sending a request to update the pod
 // object to avoid races with the following scheduling cycles.
-func (npm *nominator) AddNominatedPod(pi *framework.PodInfo, nodeName string) {
+func (npm *nominator) AddNominatedPod(pi *framework.PodInfo, nodeName *string) {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue.go:696]: Document the semantics of `nil` vs empty string.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 8]
```diff
@@ -831,17 +839,13 @@ type nominator struct {
...
 	// one instance of the pod.
 	npm.delete(pi.Pod)
 
-	nnn := nodeName
-	if len(nnn) == 0 {
-		nnn = NominatedNodeName(pi.Pod)
-		if len(nnn) == 0 {
-			return
-		}
+	if nodeName == nil {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue.go:847]: so `nil` removes the nominated node name?
Wasn't that supposed to be empty string?

File: pkg/scheduler/framework/preemption/preemption.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/preemption/preemption.go:128]: <nil, Unschedulable> and <nil, Error> are the same - nil PostFilterResult (the first returned param) indicates we keep the nominatedNodeName unchanged. Any wordings you think is not clear?

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 8 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:847]: In the before, if an empty string is passed in, we always look at and honor the nominatedNodeName if it carries. Now the logic gets tweaked:

- if you want to follow the old logic, on the caller side, use `adaptiveNominatedNodeName()` to always honor nominatedNodeName
- if you want to enforce overriding, pass in a non-nil string pointer (no matter it's empty or a concrete string).

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:696]: I updated to compare nil vs. non-nil. PTAL.

File: pkg/scheduler/framework/preemption/preemption.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/preemption/preemption.go:128]: well, it's saying that "Unschedulable" is an error. Even if we don't clear the name in both scenarios, that comment is innacurate.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 8 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue.go:847]: I'm not liking `adaptiveNominatedNodeName`, as it could be forgotten. I think it should be handled within this function: if passing nil, leave; otherwise override

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:847]: > if passing nil, leave; otherwise override

Passing the string pointer still needs to be decided at the caller side - whether it's a pod with empty nominatedNodeName, so we interpreted it as nil; or, the caller have baked the string pointer properly (like `recordSchedulingFailure()`)

File: pkg/scheduler/framework/preemption/preemption.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/preemption/preemption.go]: I see the point. Reworded the comments.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 8 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue.go:847]: Here is my proposal:
- `nil` means do not change anything. Then, we would query the nominatedNodeName from the pod status.
- `""` means clear
- `"foo"` is override

I think that logic can be handled here.

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:840]: It makes sense to me and can save the efforts on the caller side.

One question on `"" means clear`: to keep the behavior with before, "" and "regular string" are treated the same. If we really want to clear the entry, we can do it in a follow-up.

Comment (ahg-g) [reply pkg/scheduler/internal/queue/scheduling_queue.go:840]: I think distinguishing between nil and empty is asking for trouble. I also didn't like the old code that implicitly treated an empty nodeName as a fallback to the value in the pod. Lots of implicit behavior that one can't figure out without carefully parsing the code.

Not sure if this was the old code, but why not simply have the following:

```
// Call the following in the places were you are currently passing in nil.
add(pi) {
 addToNode(pi, pi.Pod.Status.NominatedNodeName)
}
```

```
// Alway adds the pod to the passed nodeName
addToNode(pi, nodeName) {
 ...
}
```

File: pkg/scheduler/framework/interface.go [hunk 9]
```diff
@@ -617,7 +617,11 @@ type PostFilterResult struct {
 type PodNominator interface {
 	// AddNominatedPod adds the given pod to the nominator or
 	// updates it if it already exists.
-	AddNominatedPod(pod *PodInfo, nodeName string)
+	// Notes for the semantics of `nodeName`:
+	// - if it's nil, the backing nominator aborts if the pod doesn't carry a nominatedNodeName; otherwise
+	//   sets the carried nominatedNodeName.
+	// - if it's non-nil, the internal nominating bits will be updated with the given `nodeName`.
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:623]:
```suggestion
	// - if it's non-nil, the internal cache will be updated with the given `nodeName`.
```

File: pkg/scheduler/framework/interface.go [hunk 10]
```diff
@@ -617,7 +617,11 @@ type PostFilterResult struct {
...
+	AddNominatedPod(pod *PodInfo, nodeName *string)
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:624]: Overloading the parameter nodeName to signal more than simply the nodeName is problematic, I suggest making the interface explicit. Here are some options:

1) Is there really a legitimate case where the nodeName is different from the one set in the passed pod if one is set? If so, I think we need to revisit that because I don't think there should be one.

2) If we fail with option 1, I think this function should have consistent semantics and always adds pod to the passed nodeName, no exceptions and fail on an empty `nodeName`. The caller of this function can do 
use a wrapper function as follows (not part of this interface):

```
func AddNominatedPodIfSet(pod) {
 if pi.Pod.Status.NominatedNodeName != "" {
  AddNominatedPod(pod, pi.Pod.Status.NominatedNodeName)
 }
}
```

File: pkg/scheduler/framework/preemption/preemption.go [hunk 11]
```diff
@@ -123,8 +123,18 @@ type Evaluator struct {
...
 }
 
+// Preempt returns a PostFilterResult carrying suggested nominatedNodeName, along with a Status.
+// The semantics of returned <PostFilterResult, Status> varies on different scenarios:
+// - <nil, Error>. This denotes it's a transient/rare error that may be self-healed in future cycles.
+// - <nil, Unschedulable>. This status is mostly as expected like the preemptor is waiting for the
+//   victims to be fully terminated.
+// - In both cases above, a nil PostFilterResult is returned to keep the pod's nominatedNodeName unchanged.
+//
+// - <PostFilterResult{}, Unschedulable>. It indicates the pod cannot be scheduled even with preemption.
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/preemption/preemption.go:133]: I thought of option 1, but it's sort of non-trivial work. Let me think about it.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 8 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:840]: > Not sure if this was the old code, but why not simply have the following

This is basically the previous version except for that some places needs to inject NominatedNodeName adapatively.

File: pkg/scheduler/framework/interface.go (hunk 10 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:624]: Re 1: yes, it can be empty in recordSchedulingFailure() to clear the entry, or UpdateNominatedPod() which reveals a special case that right after a preemptor is marked as nominated in memory, and at the same time a podUpdate event (doesn't carry nominatedNodeName) comes in.

Re 2: the wrapper can help refactor the code for better readability. Thanks.

File: pkg/scheduler/framework/preemption/preemption.go [hunk 12]
```diff
@@ -123,8 +123,18 @@ type Evaluator struct {
...
+//   In this case, an empty PostFilterResult is returned to clear the pod's nominatedNodeName (if it carries).
+// - <PostFilterResult{non-empty nominatedNodeName}, Unschedulable>. It's the regular happy path
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/preemption/preemption.go:135]: Typo.. Will update along with further changes.

**Comment by Huang-Wei** [comment]
I appended a commit to use `NominatingInfo` to simply the manipulation on nominatedNodeName. @ahg-g @alculquicondor PTAL.

File: pkg/scheduler/framework/interface.go [hunk 13]
```diff
@@ -608,16 +608,44 @@ type Handle interface {
...
+	NominatingMode    NominatingMode
+}
+
 // PostFilterResult wraps needed info for scheduler framework to act upon PostFilter phase.
 type PostFilterResult struct {
-	NominatedNodeName string
+	*NominatingInfo
+}
+
+func NewPostFilterResultWithNominatedNodeName(name string) *PostFilterResult {
```
Comment (alculquicondor) [inline pkg/scheduler/framework/interface.go:628]: nit: `NewPostFilterResultWithNominatedNode`

File: pkg/scheduler/framework/runtime/framework.go [hunk 14]
```diff
@@ -711,18 +711,22 @@ func (f *frameworkImpl) RunPostFilterPlugins(ctx context.Context, state *framewo
...
+	// `result` records the last meaningful(non-noop) PostFilterResult.
+	var result *framework.PostFilterResult
 	for _, pl := range f.postFilterPlugins {
 		r, s := f.runPostFilterPlugin(ctx, pl, state, pod, filteredNodeStatusMap)
 		if s.IsSuccess() {
 			return r, s
 		} else if !s.IsUnschedulable() {
 			// Any status other than Success or Unschedulable is Error.
 			return nil, framework.AsStatus(s.AsError())
+		} else if r != nil && r.Mode() != framework.ModeNoop {
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:723]: perhaps `r.Mode` could support `r==nil`

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 15]
```diff
@@ -886,21 +888,24 @@ func (npm *nominator) UpdateNominatedPod(oldPod *v1.Pod, newPodInfo *framework.P
...
+	var nominatingInfo *framework.NominatingInfo
 	// We won't fall into below `if` block if the Update event represents:
 	// (1) NominatedNode info is added
 	// (2) NominatedNode info is updated
 	// (3) NominatedNode info is removed
 	if NominatedNodeName(oldPod) == "" && NominatedNodeName(newPodInfo.Pod) == "" {
 		if nnn, ok := npm.nominatedPodToNode[oldPod.UID]; ok {
 			// This is the only case we should continue reserving the NominatedNode
-			nodeName = nnn
+			nominatingInfo = &framework.NominatingInfo{
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue.go:899]: Use the `New` function

File: test/integration/scheduler/preemption_test.go [hunk 16]
```diff
@@ -932,98 +933,209 @@ func TestPreemptionRaces(t *testing.T) {
...
-	// Initialize scheduler.
-	testCtx := initTest(t, "preemption")
-	defer testutils.CleanupTest(t, testCtx)
+const (
+	alwaysFailPlugin = "alwaysFailPlugin"
+	doNotFailMe      = "do-not-fail-me"
+)
 
-	cs := testCtx.ClientSet
+type alwaysFail struct{}
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:941]: Add a comment for the functionality of this plugin

File: test/integration/scheduler/preemption_test.go [hunk 17]
```diff
@@ -932,98 +933,209 @@ func TestPreemptionRaces(t *testing.T) {
...
+		podsToCreate [][]*v1.Pod
+		// Each postCheck function is run after each batch of pods' creation.
+		postChecks []func(cs clientset.Interface, pod *v1.Pod) error
+		// Delete the fake node or not. Optional.
+		deleteNode bool
+		// Pods to be deleted. Optional.
+		podNamesToDelete []string
+
+		// Register dummy plugin to simulate particular scheduling failures. Optional.
+		outOfTreePlugins  *v1beta3.Plugins
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:974]: `customPlugins`

File: test/integration/scheduler/preemption_test.go [hunk 18]
```diff
@@ -932,98 +933,209 @@ func TestPreemptionRaces(t *testing.T) {
...
+				}
+			}
+
+			// Verify if .status.nominatedNodeName is cleared.
+			if err := wait.Poll(100*time.Millisecond, wait.ForeverTestTimeout, func() (bool, error) {
+				pod, err := cs.CoreV1().Pods(ns).Get(context.TODO(), "medium", metav1.GetOptions{})
+				if err != nil {
+					t.Errorf("Error getting the medium pod: %v", err)
+				}
+				if len(pod.Status.NominatedNodeName) == 0 {
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:1131]: should we have test cases for when the nnn is not cleared?

Alternatively, instead of special casing "medium", is it worth having a map of the expected nnn or assigned nodes for all the pods not removed? Then you can do a `cmp.Diff`.

File: pkg/scheduler/framework/interface.go [hunk 19]
```diff
@@ -608,16 +608,44 @@ type Handle interface {
...
+
+type NominatingInfo struct {
+	NominatedNodeName string
+	NominatingMode    NominatingMode
+}
+
 // PostFilterResult wraps needed info for scheduler framework to act upon PostFilter phase.
 type PostFilterResult struct {
-	NominatedNodeName string
+	*NominatingInfo
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:625]: Not mandatory. But it can simplify the code on caller side. (just pass in a nil to indicate its mode is Noop)

File: pkg/scheduler/framework/runtime/framework.go (hunk 14 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:723]: Nope, r.Mode() is a simplified form of r.NominatingInfo.Mode(). Only NominatingInfo has the logic for nil tolerance. `r`, which is PostFilterResult, doesn't have.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 15 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:899]: I didn't add a New functin for NominatingInfo. The NewPostFilterResultWithNominatedNode is for simplifying instantiation of PostFilterResult.

File: pkg/scheduler/framework/interface.go (hunk 13 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:628]: done.

File: pkg/scheduler/framework/interface.go [hunk 20]
```diff
@@ -608,16 +608,44 @@ type Handle interface {
 	Parallelizer() parallelize.Parallelizer
 }
 
+type NominatingMode string
+
+var (
+	ModeNoop     NominatingMode = "ModeNoop"
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:614]: done.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 21]
```diff
@@ -1691,11 +1687,14 @@ func TestPreempt(t *testing.T) {
 			if !status.IsSuccess() && !status.IsUnschedulable() {
 				t.Errorf("unexpected error in preemption: %v", status.AsError())
 			}
-			if res != nil && len(res.NominatedNodeName) != 0 && res.NominatedNodeName != test.expectedNode {
-				t.Errorf("expected node: %v, got: %v", test.expectedNode, res.NominatedNodeName)
-			}
-			if res != nil && len(res.NominatedNodeName) == 0 && len(test.expectedNode) != 0 {
-				t.Errorf("expected node: %v, got: nothing", test.expectedNode)
+			if res != nil && res.NominatingInfo != nil {
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:1690]: sure.

File: test/integration/scheduler/preemption_test.go (hunk 16 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go:941]: done.

File: test/integration/scheduler/preemption_test.go (hunk 18 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go:1131]: probably, but I won't bother here until we have a valid requirement in the future.

File: pkg/scheduler/framework/runtime/framework.go (hunk 14 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/framework.go:723]: got it.

File: pkg/scheduler/framework/interface.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:625]: > But when returning a Noop result, we are just using `PostFilterResult=nil`, no?

A Noop result equals a nil `NominatingInfo`, but not quite equivalent to `PostFilterResult` as `NominatingInfo` is a sub-field of `PostFilterResult`.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/interface.go:625]: What I'm saying is that you are already using `PostFilterResult=nil` to signal Noop, so I don't see much point on having a pointer here. However, it's such a minor detail that I don't feel strongly about it.

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:625]: I see. Given a pointer NominatingInfo can be carried over directly to other places (like recordSchedulingFailure()) that need a pointer, I'm inclined to keep it as-is.

File: test/integration/scheduler/preemption_test.go (hunk 18 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go:1133]: > should we have test cases for when the nnn is not cleared?

We have e2e test covers this, like `PreemptionExecutionPath`. But I'm going to add an integration test for this specifically.

Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go:1186]: I did add a new integration test, but it needs to consistently verify if the pod's nomiantedNode is _NOT_ cleared. It adds up the test time by 15 Seconds * 2 (the first check is to ensure an upcoming low-priority doesn't get scheduled, the second check is to ensure the preemptor's nnn is not cleared).

File: test/integration/scheduler/preemption_test.go [hunk 22]
```diff
@@ -932,98 +959,248 @@ func TestPreemptionRaces(t *testing.T) {
...
+				if err := deletePod(cs, podName, ns); err != nil {
+					t.Fatalf("Pod %v cannot be deleted: %v", podName, err)
+				}
+			}
+
+			// Verify if .status.nominatedNodeName is cleared/uncleared as expected.
+			err := wait.Poll(100*time.Millisecond, 15*time.Second, func() (bool, error) {
+				pod, err := cs.CoreV1().Pods(ns).Get(context.TODO(), "medium", metav1.GetOptions{})
+				if err != nil {
+					// t.Errorf("Error getting the medium pod: %v", err)
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:1183]: leftover?

File: test/integration/scheduler/preemption_test.go (hunk 18 above)
Comment (alculquicondor) [reply test/integration/scheduler/preemption_test.go:1186]: Uhm... sad that there is no way to know if there was a scheduling attempt that includes all the pod/node updates.

Maybe we shouldn't commit a test that is expected to stay idle for 15 seconds?

Which leave us with an untested path, but we still have the e2e and unit tests. WDYT? Sorry for the back and forth.

Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go:1186]: > Maybe we shouldn't commit a test that is expected to stay idle for 15 seconds?

That's my concern as well.

> Which leave us with an untested path, but we still have the e2e and unit tests. WDYT?

I think we can remove this integration test. The e2e test `PreemptionExecutionPath` has ensured the same path coverage.

File: test/integration/scheduler/preemption_test.go (hunk 22 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption_test.go]: reverted the most recent integration test and this should be gone.

**Comment by ahg-g** [comment]
/lgtm

thanks Wei, the explicit api for how to deal with nominatedNodeName feels more readable and easier to reason about.

**Comment by Huang-Wei** [comment]
/retest

Thanks @alculquicondor and @ahg-g for pushing me on the readability refactoring :)

Given this is going to benefit CA (#85677) and scheduler plugins (#106780), I'm going to back port this fix if no objections.

**Comment by alculquicondor** [comment]
SGTM

**Comment by Huang-Wei** [comment]
Interesting, the log (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106816/pull-kubernetes-integration/1471554622542843904) says all tests passed but the CI job failed.

/retest

**Comment by cpanato** [comment]
@Huang-Wei @ahg-g this fix is only needed on the release-1.23 branch? not in 1.22/1.21/1.20? thanks

**Comment by mateuszlitwin** [comment]
I think 1.22 and 1.21 would benefit - https://github.com/kubernetes-sigs/scheduler-plugins/releases which is affected is on 1.21.

**Comment by ahg-g** [comment]
I find the fix too large to patch back.

btw, I think this issue existed for a long time, it is not a new bug.

**Comment by alculquicondor** [comment]
you mean, to patch back beyond 1.23, right?

+1 to just backporting to 1.23

**Comment by ahg-g** [comment]
yeah, the patch to 1.23 should probably be automatic, but beyond that it will likely face conflicts.

**Comment by cpanato** [comment]
thanks for the update and clarifications

**Comment by Huang-Wei** [comment]
@ahg-g's comment is valid, and that's why I hesitated to backport to 1.21/1.22, instead only raised #107109 for 1.23.
