### PR TITLE
Fixed incorrect Min replicas value in kubectl describe

### LINKED ISSUE #16019: When describe a HorizontalPodAutoscaler the "Min pods" number is overflow
```
Description of problem:
Create a hpa then describe it, the "Min pods" number is overflow.

Version-Release number of selected component (if applicable):
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.90+360d0e0a7e92dc", GitCommit:"360d0e0a7e92dcc4d00b4c555e166a2a71a7e713", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.90+360d0e0a7e92dc", GitCommit:"360d0e0a7e92dcc4d00b4c555e166a2a71a7e713", GitTreeState:"clean"}

How reproducible:
Always.

Steps to Reproduce:
1.Create a hpa
[root@ip-172-18-12-2 horizontal-pod-autoscaling]# cat hpa-php-apache.yaml
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleRef:
    kind: ReplicationController
    name: php-apache
    namespace: default
  cpuUtilization:
    targetPercentage: 10
[root@ip-172-18-12-2 horizontal-pod-autoscaling]# kubectl create -f hpa-php-apache.yaml
horizontalpodautoscaler "php-apache" created

2.Get the hpa
[root@ip-172-18-12-2 horizontal-pod-autoscaling]# kubectl get hpa
NAME         REFERENCE                                   TARGET    CURRENT     MINPODS   MAXPODS   AGE
php-apache   ReplicationController/default/php-apache/   10%       <waiting>   1         10        6s

3.Describe the hpa
[root@ip-172-18-12-2 horizontal-pod-autoscaling]# kubectl describe hpa/php-apache
Name:                php-apache
Namespace:            default
Labels:                <none>
CreationTimestamp:        Wed, 21 Oct 2015 08:58:22 +0000
Reference:            ReplicationController/default/php-apache/
Target CPU utilization:        10%
Current CPU utilization:    <not available>
Min pods:            859532872368
Max pods:            10
ReplicationController pods:    failed to check Replication Controller

Actual results:
3.The "Min pods" number is 859532872368

Expected results:
3.The "Min pods" number is 1

Additional info:
```

### PR DESCRIPTION
**Pull request by piosz**
fixes #16019
related to #15997

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM

File: pkg/kubectl/describe.go [hunk 1]
```diff
@@ -1272,8 +1272,12 @@ func (d *HorizontalPodAutoscalerDescriber) Describe(namespace, name string) (str
 				fmt.Fprintf(out, "<not available>\n")
 			}
 		}
-		fmt.Fprintf(out, "Min pods:\t%d\n", hpa.Spec.MinReplicas)
-		fmt.Fprintf(out, "Max pods:\t%d\n", hpa.Spec.MaxReplicas)
+		minReplicas := "<unknown>"
```
Comment (JanetKuo) [inline pkg/kubectl/describe.go]: Should we show "" (nothing) or "<unknown>" when MinReplicas is nil?

**Comment by piosz** [comment]
Made the output consistent with kubectl get #15997. @gmarek PTAL
