### PR TITLE
Fix:  kubelet will not output logs after log file is rotated

### LINKED ISSUE #115701: kubectl logs will not output logs after the log file is rotated.
### What happened?

`kubectl logs POD_NAME -f ` won't output logs after kubelet rotate log filer of the container. 

### What did you expect to happen?

kubectl output logs correctly after the log file is rotated. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Add the config  `containerLogMaxSize: 5Mi` to  `kubelet.yaml`. So kubelet will rotate the log soon.
2.  Build a image with this program
   ```
package main

 import (
        "fmt"
        "time"
 )

 func main() {
        i := 0
        for range time.Tick(10 * time.Microsecond) {
                fmt.Printf("print log to stand out %d\n", i)
                i++
        }
 }
   ```
3. Create a deploy with the previous image.
4. Run the command `kubectl logs POD_NAME -f`

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-26T10:58:54Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Linux andrewli 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by xyz-li**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
kubectl logs POD_NAME -f  won't output logs after kubelet rotate log file of the container .

#### Which issue(s) this PR fixes:

Fixes #115701

#### Special notes for your reviewer:
Comment from the method Wacher.Add
```
// # Watching directories
//
// All files in a directory are monitored, including new files that are created
// after the watcher is started. Subdirectories are not watched (i.e. it's
// non-recursive).
//
// # Watching files
//
// Watching individual files (rather than directories) is generally not
// recommended as many tools update files atomically. Instead of "just" writing
// to the file a temporary file will be written to first, and if successful the
// temporary file is moved to to destination removing the original, or some
// variant thereof. The watcher on the original file is now lost, as it no
// longer exists.
//
// Instead, watch the parent directory and use Event.Name to filter out files
// you're not interested in. There is an example of this in [cmd/fsnotify/file.go].
```

#### Does this PR introduce a user-facing change?

```release-note
Fixed the bug that kubelet could't output logs after log file rotated when kubectl logs POD_NAME -f is running.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — COMMENTED** [review]
Can we add a unit test to `TestReadLogs` to cover the failure scenario?

File: pkg/kubelet/kuberuntime/logs/logs.go [hunk 1]
```diff
@@ -344,16 +346,16 @@ func ReadLogs(ctx context.Context, path, containerID string, opts *LogOptions, r
 						return fmt.Errorf("failed to create fsnotify watcher: %v", err)
 					}
 					defer watcher.Close()
-					if err := watcher.Add(f.Name()); err != nil {
-						return fmt.Errorf("failed to watch file %q: %v", f.Name(), err)
+					if err := watcher.Add(dir); err != nil {
+						return fmt.Errorf("failed to watch directory %q: %v", dir, err)
```
[the remark this answers is not in the document]
Comment (xyz-li) [reply pkg/kubelet/kuberuntime/logs/logs.go]: done

**Comment by xyz-li** [comment]
> Can we add a unit test to `TestReadLogs` to cover the failure scenario?

Working on it.

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 2]
```diff
@@ -210,6 +212,138 @@ func TestReadLogs(t *testing.T) {
...
+	return b.b.Write(p)
+}
+func (b *syncBuffer) String() string {
+	b.Lock()
+	defer b.Unlock()
+	return b.b.String()
+}
+
+func TestReadRotatedLog(t *testing.T) {
+	file, err := os.CreateTemp("/tmp", "TestFollowLogs")
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:237]: will it make test to watch the whole `/tmp`? 

Also, maybe rely on the default temp folder instead of setting to `/tmp` explicitly

Comment (xyz-li) [reply pkg/kubelet/kuberuntime/logs/logs_test.go]: Done.

File: pkg/kubelet/kuberuntime/logs/logs.go [hunk 3]
```diff
@@ -454,15 +450,15 @@ func waitLogs(ctx context.Context, id string, w *fsnotify.Watcher, runtimeServic
...
 			case fsnotify.Rename:
-				fallthrough
+				return true, false, nil
 			case fsnotify.Remove:
 				fallthrough
 			case fsnotify.Chmod:
-				return true, true, nil
+				fallthrough
+			case fsnotify.Create:
+				return true, filepath.Base(e.Name) == logName, nil
```
Comment (s-kawamura-w664) [inline pkg/kubelet/kuberuntime/logs/logs.go:461]: Please tell me about the concept of the return value for each notify.
I thought that the return value should be `return true, true, nil` only when the fsnotify.Create of the current log file (filepath) is notified.
Why do fsnotify.Remove and fsnotify.Chmod also need to `return true,true,nil`?

Comment (Andrew-Liggitt) [reply pkg/kubelet/kuberuntime/logs/logs.go]: You are right. There is no necessity to return true when  fsnotify.Remove and fsnotify.Chmod .

Comment (xyz-li) [reply pkg/kubelet/kuberuntime/logs/logs.go]: You are right. There is no necessity to return true when fsnotify.Remove and fsnotify.Chmod.

**Comment by bart0sh** [comment]
@xyz-li This looks like a user-visible change. Can you provide release notes, please?

**Comment by xyz-li** [comment]
> @xyz-li This looks like a user-visible change. Can you provide release notes, please?

How about this?
```
Fixed the bug that kubelet will not output logs after log file is rotated.
```

**Comment by s-kawamura-w664** [comment]
> Fixed the bug that kubelet could't output logs after log file rotated.

How about adding as a condition, "when `kubectl logs POD_NAME -f` is run" ?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 4]
```diff
@@ -210,6 +212,144 @@ func TestReadLogs(t *testing.T) {
...
+	}
+	defer os.RemoveAll(tmpDir)
+
+	file, err := os.CreateTemp(tmpDir, "logfile")
+	if err != nil {
+		t.Fatalf("unable to create temp file")
+	}
+
+	fileName := file.Name()
+	defer os.Remove(fileName)
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:249]:
```suggestion
```

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 5]
```diff
@@ -210,6 +212,144 @@ func TestReadLogs(t *testing.T) {
...
+	opts := NewLogOptions(&podLogOptions, time.Now())
+	stdoutBuf := &syncBuffer{}
+	stderrBuf := &syncBuffer{}
+
+	expected := "line1\nline2\nline3\nline4\nline5\n"
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	evaluated, err := filepath.EvalSymlinks(file.Name())
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:281]: Do we really need to evaluate symlinks for the file that we've just created and know that it's not a symlink?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 6]
```diff
@@ -210,6 +212,144 @@ func TestReadLogs(t *testing.T) {
...
+		}
+	}()
+
+	go func(ctx context.Context) {
+		if err = ReadLogs(ctx, file.Name(), containerID, opts, fakeRuntimeService, stdoutBuf, stderrBuf); err != nil {
+			if err.Error() != "context cancelled" {
+				fmt.Printf("readlog failed, err %v", err)
+				return
+			}
+		}
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:342]: Would it make sense to check if the context of stdoutBuf and stderrBuf matches to the test content we wrote?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 7]
```diff
@@ -210,6 +212,144 @@ func TestReadLogs(t *testing.T) {
...
+	}
+
+	fileName := file.Name()
+	defer os.Remove(fileName)
+
+	file.WriteString(`{"log":"line1\n","stream":"stdout","time":"2023-02-14T11:18:01.00000000Z"}` + "\n")
+	file.WriteString(`{"log":"line2\n","stream":"stdout","time":"2023-02-14T11:18:02.00000000Z"}` + "\n")
+	file.WriteString(`{"log":"line3\n","stream":"stdout","time":"2023-02-14T11:18:03.00000000Z"}` + "\n")
+	// Rotate marker
+	file.WriteString(`{"log":"__ROTATE_MARKER__\n","stream":"stderr","time":"2023-02-14T11:18:04.00000000Z"}` + "\n")
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:255]: Can we write the file while we're reading it? It would more realistically simulate `tail`-ing.

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 8]
```diff
@@ -210,6 +212,144 @@ func TestReadLogs(t *testing.T) {
...
+						file.Close()
+
+						newF := filepath.Join(dir, baseName)
+						if f, err := os.Create(newF); err != nil {
+							fmt.Printf("unable to create the file")
+							return
+						} else {
+							// Write new logs to log file
+							f.WriteString(`{"log":"line4\n","stream":"stdout","time":"2023-02-14T11:18:05.00000000Z"}` + "\n")
+							f.WriteString(`{"log":"line5\n","stream":"stdout","time":"2023-02-14T11:18:06.00000000Z"}` + "\n")
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:317]: Would it make sense to write to stderr as well?

File: pkg/kubelet/kuberuntime/logs/logs.go [hunk 9]
```diff
@@ -454,15 +450,15 @@ func waitLogs(ctx context.Context, id string, w *fsnotify.Watcher, runtimeServic
...
 				fallthrough
 			case fsnotify.Rename:
 				fallthrough
 			case fsnotify.Remove:
 				fallthrough
 			case fsnotify.Chmod:
-				return true, true, nil
+				return true, false, nil
+			case fsnotify.Create:
+				return true, filepath.Base(e.Name) == logName, nil
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs.go:461]: fallthrough looks a bit strange here. Isn't it the same as
```
case fsnotify.Write, fsnotify.Rename, snotify.Chmod:
        return true, false, nil
```
?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 10]
```diff
@@ -210,6 +212,157 @@ func TestReadLogs(t *testing.T) {
...
+	file, err := os.CreateTemp(tmpDir, "logfile")
+	if err != nil {
+		t.Errorf("unable to create temp file")
+		t.Fail()
+	}
+
+	fileName := file.Name()
+	podLogOptions := v1.PodLogOptions{
+		Follow: true,
+	}
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:255]: Can you move this down to the place where it's used?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 11]
```diff
@@ -210,6 +212,157 @@ func TestReadLogs(t *testing.T) {
...
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+
+	dir := filepath.Dir(file.Name())
+	baseName := filepath.Base(file.Name())
+
+	stopped := make(chan struct{})
+	go func() {
+		timeout := time.NewTimer(30 * time.Second)
+		ticker := time.NewTicker(10 * time.Millisecond)
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:286]: I don't fully get the idea of using timer and ticker. Can you elaborate?

Would it be simpler to simply write to the file, rotate it and then write to it again in one goroutine and call ReadLogs in another one?

File: pkg/kubelet/kuberuntime/logs/logs.go (hunk 9 above)
Comment (xyz-li) [reply pkg/kubelet/kuberuntime/logs/logs.go:458]: Just followed the previous code style.  I have changed.

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 12]
```diff
@@ -210,6 +213,144 @@ func TestReadLogs(t *testing.T) {
...
+			if !timeout.Stop() {
+				<-timeout.C
+			}
+			ticker.Stop()
+		}()
+
+		for {
+			select {
+			// When podLogOptions.Follow is true, the function ReadLogs will not end.
+			// So we should check whether stdoutBuf && stderrBuf match the expects periodically.
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:297]: Would it end if we delete the file? If so, we can test it without timer, timeout and context, I hope.

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 13]
```diff
@@ -210,6 +213,122 @@ func TestReadLogs(t *testing.T) {
...
+				time.Sleep(20 * time.Millisecond)
+			}
+		}
+
+		time.Sleep(20 * time.Millisecond)
+		// Make the function ReadLogs end.
+		fakeRuntimeService.Lock()
+		fakeRuntimeService.Containers[containerID].State = runtimeapi.ContainerState_CONTAINER_EXITED
+		fakeRuntimeService.Unlock()
+	}()
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:325]: Do we really need to run this code asynchronously?

File: pkg/kubelet/kuberuntime/logs/logs_test.go [hunk 14]
```diff
@@ -210,6 +213,122 @@ func TestReadLogs(t *testing.T) {
 	}
 }
 
+type syncBuffer struct {
+	b bytes.Buffer
+	sync.Mutex
+}
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs_test.go:219]: Why do we need to have a separate syncBuffer structure if we have access to the file? Can we just read it and compare with the expected content?

File: pkg/kubelet/kuberuntime/logs/logs.go [hunk 15]
```diff
@@ -453,16 +449,13 @@ func waitLogs(ctx context.Context, id string, w *fsnotify.Watcher, runtimeServic
 			return false, false, fmt.Errorf("context cancelled")
 		case e := <-w.Events:
 			switch e.Op {
-			case fsnotify.Write:
+			case fsnotify.Write,
+				fsnotify.Rename,
+				fsnotify.Remove,
+				fsnotify.Chmod:
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/logs/logs.go:455]: nit: fsnotify.Write looks separated. Having all items in one line would be more readable.

File: pkg/kubelet/kuberuntime/logs/logs_test.go (hunk 14 above)
Comment (bart0sh) [reply pkg/kubelet/kuberuntime/logs/logs_test.go:219]: I take it back. We need a buffer to verify what ReadLogs writes to it, but do we need a special buffer with locks?

**Comment by bart0sh** [comment]
@xyz-li looks good. Please, squash all commits into one, otherwise lgtm.

**Comment by tuibeovince** [comment]
I was able to confirm that this patch/fix allows continuous output of `kubectl logs -f` even after log rotation. I would love to have this patch merged soon.

**Comment by tuibeovince** [comment]
I also did a confirmation of the performance of this fix by recursively executing the kubectl logs command over 100 times. A stuck log during rotation didn't occur even once using this fix.

I used the reproduction method in https://github.com/kubernetes/kubernetes/issues/115701

* As supplimentary info:

As of the the release of v1.28, executing `kubectl logs POD_NAME -f` numerous times may also trigger a "failed to watch file" error.

Specifically speaking, I executed the logging command for the pod 100 times. It occurs very very rarely, about once in one hundred executions. **This PR also addresses and fixes this error's occurence as far as my reproduction methodology is concerned.**

Stdout:
```
...
print log to stand out 1064678
print log to stand out 1064679
print log to stand out 1064680
failed to watch file "/var/log/pods/default_testlogrotator_41df37c5-02e3-4687-a237-329bec3b2d25/testlogrotator/0.log": no such file or directory
```

**Comment by dims** [comment]
this has waited long enough. let's see if something shakes up in the CI

/approve
/lgtm

**Comment by tuibeovince** [comment]
> this has waited long enough. let's see if something shakes up in the CI
> 
> /approve /lgtm

Thank you very much for this approval. I believe this log rotation problem has been an issue for other people for a while now.

**Comment by zwpaper** [comment]
as this fixes a bug many people had met in production environments, will this be cherry-picked to the previous releases?
