### PR TITLE
kubeadm: fix a regression in "kubeadm init" where --kubeconfig is ignored

### LINKED ISSUE #2992: kubeadm init phase bootstrap-token ignores --kubeconfig in 1.29
### What happened?

Using `kubeadm init phase bootstrap-token` no longer works stand-alone in 1.29. The `--kubeconfig` flag is ignored and it requires `/etc/kubernetes/admin.conf` or `super-admin.conf` to exist.

```
$ kubeadm init phase bootstrap-token --kubeconfig kubeconfig.yaml
error execution phase bootstrap-token: could not bootstrap the admin user in file admin.conf: failed to load admin kubeconfig: open /etc/kubernetes/admin.conf: no such file or directory
To see the stack trace of this error execute with --v=5 or higher
```

The release notes did not mention this behavior change.

### What did you expect to happen?

In 1.28 it used to be possible to create a bootstrap-token using: `kubeadm init phase bootstrap-token --kubeconfig someconfig.yaml`.

For example using kubeadm 1.28.5 from https://dl.k8s.io/v1.28.5/kubernetes-node-linux-amd64.tar.gz:

```
./kubernetes/node/bin/kubeadm init phase bootstrap-token --kubeconfig kubeconfig.yaml
I0112 11:23:27.072367   27957 version.go:256] remote version is much newer: v1.29.0; falling back to: stable-1.28
[bootstrap-token] Using token: cmyl7h.z7egm8ygdbymguln
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
```

### How can we reproduce it (as minimally and precisely as possible)?

Set up a kind cluster to get a working kubeconfig file:

```
kind create cluster --name kubeadm-test --kubeconfig kubeconfig.yaml
```

Run this command with kubeadm 1.28.5 and 1.29.0:

```
kubeadm init phase bootstrap-token --kubeconfig kubeconfig.yaml
```

### Anything else we need to know?

To me it looks like the problem is that the codepath where --kubeconfig is used is unreachable. https://github.com/kubernetes/kubernetes/blob/v1.29.0/cmd/kubeadm/app/cmd/init.go#L529
The only place where `adminKubeConfigBootstrapped` is set is in the if block above, so the else is never taken.

This change was introduced in https://github.com/kubernetes/kubernetes/pull/121305.

### Kubernetes version

1.29.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by avorima**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Don't create admin rolebindings when `--kubeconfig` is set to a non-default value.
This allows `kubeadm init` to be invoked with a custom kubeconfig again.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2992

#### Special notes for your reviewer:

I built and tested the kubeadm binary.

@neolit123 

#### Does this PR introduce a user-facing change?

```release-note
fixes a 1.29 regression in "kubeadm init" that caused a user-specified --kubeconfig file to be ignored.
```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/init_test.go [hunk 1]
```diff
@@ -349,3 +363,26 @@ func expectedInitIgnorePreflightErrors(expectedItems ...string) func(t *testing.
...
+
+	data, err := newInitData(cmd, nil, initOptions, nil)
+	if err != nil {
+		t.Fatalf("newInitData returned unexpected error: %v", err)
+	}
+
+	// This only works if the client that is constructed from the kubeconfig is not used.
+	if _, err := data.Client(); err != nil {
+		t.Fatalf("data.Client returned unexpected error: %v", err)
+	}
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/init_test.go:387]: can we actually verify that the initOptions.kubeconfigPath is used here?
one way would be with httptest, i guess.

**Review by neolit123 — COMMENTED** [review]
/hold for review
/cc @SataQiu 

/ok-to-test

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: fix a regression in "kubeadm init" that caused a user-specified --kubeconfig file to be ignored.
```

File: cmd/kubeadm/app/cmd/init_test.go (hunk 1 above)
Comment (avorima) [reply cmd/kubeadm/app/cmd/init_test.go:387]: something like this?

```go
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodHead {
			w.WriteHeader(http.StatusMethodNotAllowed)
		}
	}))
	defer ts.Close()

...

	result := client.Discovery().RESTClient().Verb("HEAD").Do(context.Background())
	if err := result.Error(); err != nil {
		t.Fatalf("REST client request returned unexpected error: %v", err)
	}
```

Comment (neolit123) [reply cmd/kubeadm/app/cmd/init_test.go:387]: SGTM!

**Comment by neolit123** [comment]
please squash the commits to 1
/approve

leaving LGTM to @SataQiu 
do you think this is good, as is and we can backport it?

**Comment by avorima** [comment]
I suppose this change won't make it into 1.29.1, right? @neolit123 @SataQiu
https://kubernetes.io/releases/patch-releases/

**Review by neolit123 — COMMENTED** [review]
/lgtm

let's go ahead and merge this.
it can catch the next cherry pick deadline
https://kubernetes.io/releases/patch-releases/#upcoming-monthly-releases

@avorima 
would you like to send the cherry pick for `release-1.29` as well?
you can try https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh
if not a manual cherry pick PR can work too.

**Comment by avorima** [comment]
sure, i'll do the cherry pick

**Comment by liggitt** [comment]
Thanks for the PR, please update the release note with the minor version the regression was introduced (for example, "fixes a 1.29 regression…")

**Comment by liggitt** [comment]
And update the release note in the cherry-pick(s) as well

**Comment by avorima** [comment]
@liggitt  Thanks for you feedback. I updated both release notes
