### PR TITLE
kubeadm: Wait for node before updating labels and taints

### LINKED ISSUE #221: kubeadm-dind-cluster fails on k8s master
kubeadm-dind-cluster CI started failing on master [like this](https://travis-ci.org/Mirantis/kubeadm-dind-cluster/jobs/218064515#L3234) after merging kubernetes/kubernetes#43881 (bisected)
`kubeadm init` fails:

```
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 19.541550 seconds
failed to update master node - [no nodes found]
```

Here's an [explanation](https://github.com/kubernetes/kubernetes/pull/43881#issuecomment-291201384) by @jellonek of what's going on.

@jellonek will work on that & post a PR to fix it.

cc @luxas

### PR DESCRIPTION
**Pull request by jellonek**
**What this PR does / why we need it**:
Adds again (removed in #43881) waiting for at last single node appearance during kubeadm attempt to update master role labels and taints.

**Which issue this PR fixes**:
fixes kubernetes/kubeadm#221

**Release note**:
```NONE
```

### CODE REVIEW

**Comment by jellonek** [comment]
@mikedanese @luxas @ivan4th PTAL

**Comment by jellonek** [comment]
After looking on #43835 I have to rethink this a bit.

**Comment by jellonek** [comment]
Ok. PR updated.

**Comment by ivan4th** [comment]
Looks ok now, also kubeadm-dind-cluster started working after this patch.

File: cmd/kubeadm/app/phases/apiconfig/setupmaster.go [hunk 1]
```diff
@@ -49,6 +50,8 @@ func findMyself(client *clientset.Clientset) (*v1.Node, error) {
 }
 
 func attemptToUpdateMasterRoleLabelsAndTaints(client *clientset.Clientset) error {
+	validate.WaitForNode(client)
```
Comment (mikedanese) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: This won't be ready until the network daemonset is applied. Has that already happened here?

**Review by nhlfr — APPROVED** [review]
LGTM, and solves an issue with kubeadm-dind-cluster for me as well

File: cmd/kubeadm/app/phases/apiconfig/setupmaster.go (hunk 1 above)
Comment (jellonek) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: Earlier (before #43881) this was tested during client create, so this was even earlier.
Without this - list queried in `findMyself` can be empty - what leads to fail described in https://github.com/kubernetes/kubernetes/pull/43881#issuecomment-291195835

Comment (mikedanese) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: I understand why we need to wait for the master node to register here. My question is: why are we also waiting for it to be ready? That won't happen until a network daemonset is applied. This seems like it would cause the same deadlock as https://github.com/kubernetes/kubernetes/issues/43815.

Comment (pires) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: The master components don't depend on CNI - or they didn't when I implemented self-hosted. They run on the host network.

Comment (ivan4th) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: Actually yes, I think node readiness check must be removed. BTW is `validate.Validate()` dead code currently?

**Comment by jellonek** [comment]
This can probably reintroduce issue with CNI race - so i'll split `WaitForNode` to 2 parts - real `WaitForNode` and  `verifyReadiness` separatelly called by `Verify`. First is needed by `findMyself`, second only by `Verify`.

File: cmd/kubeadm/app/phases/apiconfig/setupmaster.go (hunk 1 above)
Comment (luxas) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: Hmm, I'm also sceptical whether that will actually work. It still waits for the node to be ready

**Comment by mikedanese** [comment]
@jellonek great thanks.

File: cmd/kubeadm/app/phases/apiconfig/setupmaster.go (hunk 1 above)
Comment (jellonek) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: This is why I commented in PR that I'll rewrite this to separate steps. I'm starting this right now.

**Comment by jellonek** [comment]
Splitting this func seems to be wrong there, because waiting for readiness would require the same loop with getting node list, so I only parametrized this func.

File: cmd/kubeadm/app/phases/validate/validate.go [hunk 2]
```diff
@@ -50,20 +65,17 @@ func Validate(kubeconfigPath string) error {
...
+		if waitForReadiness {
+			n := &nodeList.Items[0]
+			if !v1.IsNodeReady(n) {
+				fmt.Println("[validate] First node has registered, but is not ready yet")
+				return false, nil
+			}
 		}
 
-		fmt.Printf("[validate] First node is ready after %f seconds\n", time.Since(start).Seconds())
+		fmt.Printf("[validate] First node is registered after %f seconds\n", time.Since(start).Seconds())
```
Comment (ivan4th) [inline cmd/kubeadm/app/phases/validate/validate.go]: The message should be different in case if `waitForReadiness` is `true`.
Maybe the check above should look like
```
if !waitForReadiness {
	fmt.Printf("[validate] First node registered after %f seconds\n", time.Since(start).Seconds())
	return true, nil
}
```
and in this place, revert it back to "is ready"

Comment (jellonek) [inline cmd/kubeadm/app/phases/validate/validate.go]: Yeah, this seems to be better. Doing update.

**Review by luxas — APPROVED** [review]
LGTM, thanks @jellonek

**Comment by luxas** [comment]
@k8s-bot kubeadm test this

/approve

**Comment by jellonek** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/kubeadm/app/phases/apiconfig/setupmaster.go, line 53 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44031#-KgsaZq51ll_0cS2a1Dn-r1-53:-Kgy4newFOI34utkfKWD:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/14bae56bf19e389125b69dedd016b71a0fc5d30f/cmd/kubeadm/app/phases/apiconfig/setupmaster.go#L53)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

This is why I commented in PR that I'll rewrite this to separate steps. I'm starting this right now. 
</blockquote></details>

Done.

---

*[cmd/kubeadm/app/phases/validate/validate.go, line 76 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44031#-KgsNT09tov_ZJNqO3Ex-r2-76:-Kgy4u9OXQ-NAZnbQLMe:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/22f533406f6ac3daad3fc1755374e37d85630a5b/cmd/kubeadm/app/phases/validate/validate.go#L76)):*
<details><summary><i>Previously, jellonek (Piotr Skamruk) wrote…</i></summary><blockquote>

Yeah, this seems to be better. Doing update.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44031)*

**Comment by ivan4th** [comment]
https://travis-ci.org/Mirantis/kubeadm-dind-cluster/builds/218905882 -- `src-master-*` jobs are based on this PR there. So all of flannel, calico and preconfigured CNI bridge work with kubeadm-dind-cluster after applying this patch. (In case of flannel extra hack was necessary to work around the problem described in kubernetes/kubernetes#39701 - but this is not related to this PR)

**Comment by luxas** [comment]
@mikedanese I'm ready to merge this, can you apply the lgtm label please?

**Comment by mikedanese** [comment]
@luxas I will review this today again.

File: cmd/kubeadm/app/phases/apiconfig/setupmaster.go [hunk 3]
```diff
@@ -49,6 +50,8 @@ func findMyself(client *clientset.Clientset) (*v1.Node, error) {
 }
 
 func attemptToUpdateMasterRoleLabelsAndTaints(client *clientset.Clientset) error {
+	validate.WaitForNode(client, false)
```
Comment (mikedanese) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: This seems less racy but still racy. What if a non-master node registers before the master node? We will get the same crash. It's also strange that we have a phase depending on another phase. What if you just:
```go
wait.PollInfinite(kubeadmconstants.APICallRetryInterval, func() (bool, error) {
    if _, err := client.Nodes().Get(masterNodeName); err != nil {
        return true, nil
    }
    return false, nil
}
```
And leave validate as is? I also don't see value in sharing code with WaitForNode if the change requires adding significantly more lines of code then just adding a PollInfinite inline here.

Comment (jellonek) [inline cmd/kubeadm/app/phases/apiconfig/setupmaster.go]: Hmmm... That would be much better and simpler. Will change this right now.

**Comment by jellonek** [comment]
Ok, used different approach also eliminating element from TODO list.
