### PR TITLE
Detect backsteps correctly in base path detection

### LINKED ISSUE #61076: "CreateContainerConfigError: failed to prepare subPath for volumeMount" error with configMap volume
/kind bug

**Fix status:**
- [x] merged in master in https://github.com/kubernetes/kubernetes/pull/61080, will be in 1.10.0-rc.1
- [x] merged in release-1.9 branch in https://github.com/kubernetes/kubernetes/pull/61107, in [v1.9.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.9.5)
- [x] merged in release-1.8 branch in https://github.com/kubernetes/kubernetes/pull/61108, in [v1.8.10](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.10)
- [x] merged in release-1.7 branch in https://github.com/kubernetes/kubernetes/pull/61109, in [v1.7.15](https://github.com/kubernetes/kubernetes/releases/tag/v1.7.15)

**What happened**:
Upgraded from v1.9.2 to v1.9.4. I began to bring up the cluster (still messing with different strategies on upgrade) and noticed that every pod that would mount a configMap via subPath would throw a similar error to the one below:

```
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537327    1124 kubelet_pods.go:248] failed to prepare subPath for volumeMount "config" of container "mumble": subpath "/var/lib/kubelet/pods/66fa673c-266d-11e8-8ebf-00155d00a406/volumes/kubernetes.io~configmap/config/..2018_03_13_03_19_55.572152209/mumble.ini" not within volume path "/var/lib/kubelet/pods/66fa673c-266d-11e8-8ebf-00155d00a406/volumes/kubernetes.io~configmap/config"
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537452    1124 kuberuntime_manager.go:734] container start failed: CreateContainerConfigError: failed to prepare subPath for volumeMount "config" of container "mumble"
Mar 12 22:30:27 node02 kubelet[1124]: E0312 22:30:27.537548    1124 pod_workers.go:186] Error syncing pod 66fa673c-266d-11e8-8ebf-00155d00a406 ("mumble-74798bc4c-xjwrn_default(66fa673c-266d-11e8-8ebf-00155d00a406)"), skipping: failed to "StartContainer" for "mumble" with CreateContainerConfigError: "failed to prepare subPath for volumeMount \"config\" of container \"mumble\""
```

**What you expected to happen**:
To mount the configMap.

_Existing behavior:_ 
https://stackoverflow.com/questions/48561338/how-to-correctly-mount-configmap-with-subpath-in-kubernetes-not-update-configs
https://stackoverflow.com/questions/44325048/kubernetes-configmap-only-one-file

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mumble-config
data:
  mumble.ini: |
    # Murmur configuration file.
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mumble
  labels:
    app: mumble
spec:
  template:
    metadata:
      labels:
        app: mumble
    spec:
      containers:
      - image: custom-image
        name: mumble
        volumeMounts:
        - name: config
          mountPath: /data/mumble.ini
          subPath: mumble.ini
      volumes:
      - name: config
        configMap:
          name: mumble-config
```

**Anything else we need to know?**:

Looking further into it it looks like a possible regression caused by #60813?

https://github.com/kubernetes/kubernetes/pull/61045/files#diff-16665fc8caff20aa7d63896dc4e3dd7fR295

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-12T16:29:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Self-hosted - 3 VM's - 1 master, two nodes.
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux master 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
Avoids false positives with atomic writer `..<timestamp>` directories

Fixes #61076

/assign @msau42 @jsafrane

```release-note
Fix a regression that prevented using `subPath` volume mounts with secret, configMap, projected, and downwardAPI volumes
```

### CODE REVIEW

**Comment by liggitt** [comment]
@jsafrane @msau42 can you add a commit expanding the subpath tests to test secret, configmap, downwardAPI, and projected volumes? the existing test assumes volumes are writeable, so the atomic writer volumes will need their own test

**Comment by liggitt** [comment]
@kubernetes/sig-storage-pr-reviews @kubernetes/sig-storage-bugs

**Comment by liggitt** [comment]
cc @tallclair

File: pkg/util/mount/mount.go [hunk 1]
```diff
@@ -325,7 +325,7 @@ func pathWithinBase(fullPath, basePath string) bool {
 	if err != nil {
```
Comment (tallclair) [inline pkg/util/mount/mount.go]: This function is also implemented in Kubelet, although I'm not sure it's used anywhere? https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/util/util.go#L51

**Review by tallclair — COMMENTED** [review]
@msau42 is OOO. I can find someone else tomorrow if @jsafrane doesn't beat me to it.

File: pkg/util/mount/mount.go (hunk 1 above)
Comment (ericchiang) [reply pkg/util/mount/mount.go]: I don't see any uses of that method.

Comment (liggitt) [reply pkg/util/mount/mount.go]: removed the unused function. similar faulty logic exists in `pkg/util/mount/mount_windows.go` lockAndCheckSubPathWithoutSymlink and findExistingPrefix

File: pkg/util/mount/mount_windows.go [hunk 2]
```diff
@@ -291,7 +291,7 @@ func lockAndCheckSubPathWithoutSymlink(volumePath, subPath string) ([]uintptr, e
 	if err != nil {
 		return []uintptr{}, fmt.Errorf("Rel(%s, %s) error: %v", volumePath, subPath, err)
 	}
-	if strings.HasPrefix(relSubPath, "..") {
+	if relSubPath == ".." || strings.HasPrefix(relSubPath, ".."+string(filepath.Separator)) {
```
Comment (liggitt) [inline pkg/util/mount/mount_windows.go]: @andyzhangx, can you verify this is correct? (does filepath.Rel always produce `..\` backstep paths on windows or would a subPath of `../...` get preserved and fail this check?

File: pkg/util/mount/mount_windows.go [hunk 3]
```diff
@@ -552,7 +552,7 @@ func findExistingPrefix(base, pathname string) (string, []string, error) {
 		return base, nil, err
 	}
 
-	if strings.HasPrefix(rel, "..") {
+	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
```
Comment (liggitt) [inline pkg/util/mount/mount_windows.go]: @andyzhangx same here

**Comment by liggitt** [comment]
added an e2e that tests subpath with the  four atomic writer volume types

**Review by andyzhangx — APPROVED** [review]
/lgtm
@liggitt I have checked in `filepath.Rel` func in Windows, it has same return as in Linux except for the slash differency.

File: test/e2e/storage/subpath.go [hunk 4]
```diff
@@ -78,6 +79,116 @@ var _ = utils.SIGDescribe("Subpath", func() {
...
+			}
+			By(fmt.Sprintf("Creating pod %s", pod.Name))
+			f.TestContainerOutput("downward", pod, 0, []string{"content of file \"" + volumePath + "\": " + pod.Name})
+		})
+
+		It("should support subpaths with projected pod", func() {
+			pod := &v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{Name: "pod-subpath-test-secret"},
+				Spec: v1.PodSpec{
+					Containers: []v1.Container{{
```
Comment (jsafrane) [inline test/e2e/storage/subpath.go]:
```
Pod "pod-subpath-test-secret" is invalid: spec.containers[0].name: Required value
```

**Comment by jsafrane** [comment]
Tested with fixed container names in https://github.com/kubernetes/kubernetes/pull/61095 (see the second commit there for necessary fix), all e2e tests passed.

lgtm to the fixes outside of test/e2e.

**Comment by liggitt** [comment]
Will fixup the test commit. Thanks for the review

**Comment by lorenz** [comment]
Will this be released as 1.9.5 (for the 1.9 series)? Or is it better to downgrade for the time being?

**Comment by liggitt** [comment]
> Will this be released as 1.9.5 (for the 1.9 series)? Or is it better to downgrade for the time being?

yes, this will be cherry-picked to 1.7.x, 1.8.x, and 1.9.x

**Comment by liggitt** [comment]
fyi @kubernetes/sig-release-misc

File: test/e2e/storage/subpath.go [hunk 5]
```diff
@@ -78,6 +79,120 @@ var _ = utils.SIGDescribe("Subpath", func() {
 
 	f := framework.NewDefaultFramework("subpath")
 
+	Context("Atomic writer volumes", func() {
+		var err error
+
+		BeforeEach(func() {
```
Comment (dims) [inline test/e2e/storage/subpath.go]: nit - Do we need an AfterEach to cleanup the secret and configmap? How about the pods? (where do they get cleaned up?)

Comment (liggitt) [reply test/e2e/storage/subpath.go]: the entire namespace gets deleted at the end of the test

Comment (dims) [reply test/e2e/storage/subpath.go]: thanks @liggitt !

**Comment by ericchiang** [comment]
/assign @tallclair 

For `pkg/kubelet/OWNERS` approval.

**Comment by tallclair** [comment]
/lgtm
Thanks!
