### PR TITLE
normalize ephemeral container statuses

### LINKED ISSUE #124873: Status manager does not normalize ephemeral container statuses
### What happened?

`EphemeralContainerStatuses` is not normalized in 	`normalizeStatus()` in the status manager:
https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/status/status_manager.go#L1026-L1043

This does not seem to cause any user facing problem because `EphemeralContainerStatuses` is sorted before passed to the status manager and timestamps are normalized at marshaling to create a patch:
https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/kubelet_pods.go#L2336

https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/status/status_manager.go#L873

However, an unexpected behavior is caused internally because timestamps are not normalized. If the log verbosity is 3 or larger, the following messages are logged periodically in kubelet when an ephemeral container exists:

```
May 14 20:10:33 kind-control-plane kubelet[720]: I0514 20:10:33.437155 	720 status_manager.go:230] "Syncing all statuses"
May 14 20:10:33 kind-control-plane kubelet[720]: I0514 20:10:33.438512 	720 status_manager.go:984] "Pod status is inconsistent with cached status for pod, a reconciliation should be triggered" pod="default/ephemeral-demo" statusDiff=<
May 14 20:10:33 kind-control-plane kubelet[720]:     	  &v1.PodStatus{
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	... // 8 identical fields
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	PodIPs:            	{{IP: "10.244.0.5"}},
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	StartTime:         	s"2024-05-14 20:09:21 +0000 UTC",
May 14 20:10:33 kind-control-plane kubelet[720]:     	-     	InitContainerStatuses: nil,
May 14 20:10:33 kind-control-plane kubelet[720]:     	+     	InitContainerStatuses: []v1.ContainerStatus{},
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	ContainerStatuses: 	{{Name: "ephemeral-demo", State: {Running: &{StartedAt: {Time: s"2024-05-14 20:09:23 +0000 UTC"}}}, Ready: true, Image: "registry.k8s.io/pause:3.1", ...}},
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	QOSClass:          	"BestEffort",
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	EphemeralContainerStatuses: []v1.ContainerStatus{
May 14 20:10:33 kind-control-plane kubelet[720]:     	              	{
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	Name: "debugger-qk87g",
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	State: v1.ContainerState{
May 14 20:10:33 kind-control-plane kubelet[720]:     	                              	Waiting:	nil,
May 14 20:10:33 kind-control-plane kubelet[720]:     	-                             	Running:	&v1.ContainerStateRunning{StartedAt: v1.Time{Time: s"2024-05-14 20:09:35 +0000 UTC"}},
May 14 20:10:33 kind-control-plane kubelet[720]:     	+                             	Running:	&v1.ContainerStateRunning{StartedAt: v1.Time{Time: s"2024-05-14 20:09:35.697513091 +0000 UTC"}},
May 14 20:10:33 kind-control-plane kubelet[720]:     	                              	Terminated: nil,
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	},
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	LastTerminationState: {},
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	Ready:            	false,
May 14 20:10:33 kind-control-plane kubelet[720]:     	                      	... // 7 identical fields
May 14 20:10:33 kind-control-plane kubelet[720]:     	              	},
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	},
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	Resize:            	"",
May 14 20:10:33 kind-control-plane kubelet[720]:     	      	ResourceClaimStatuses: nil,
May 14 20:10:33 kind-control-plane kubelet[720]:     	  }
May 14 20:10:33 kind-control-plane kubelet[720]:  >

```

This message is emitted here:
https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/status/status_manager.go#L984-L988

After `needsReconcile()` returns `true`, `syncPod()` is called. This does not look so harmful because `unchaged` gets `true` eventually:

https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/status/status_manager.go#L873-L881

API is called once unnecessarily in `syncPod()`, though:
https://github.com/kubernetes/kubernetes/blob/cade1dddd81eba338df85de7b5d17324a87243b5/pkg/kubelet/status/status_manager.go#L843

### What did you expect to happen?

It might be better to normalize ephemeral container statuses, at least timestamps, in the status manager to avoid this unexpected behavior.

### How can we reproduce it (as minimally and precisely as possible)?

Set the log verbosity of kubelet to 3 or larger. Then, create an ephemeral container like [this](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container-example).

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by zhifei92**
#### What type of PR is this?
/kind bug
/sig node

#### What this PR does / why we need it:
When a pod contains ephemeral containers , status manager don't to normalize ephemeral container statuses, leading to kubelet invoking the apiserver every 10 seconds in an attempt to complete the state synchronization, yet the status remains unsynchronized indefinitely.

When a pod contains ephemeral containers, the status manager does not normalize their statuses, causing the kubelet to repeatedly query the apiserver every 10 seconds in an attempt to synchronize the state. However, this effort is futile.
#### Which issue(s) this PR fixes:

Fixes #124873

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
do we need an explicit release note? I tend to believe we do not

File: pkg/kubelet/status/status_manager.go [hunk 1]
```diff
@@ -1038,8 +1038,18 @@ func normalizeStatus(pod *v1.Pod, status *v1.PodStatus) *v1.PodStatus {
 		normalizeContainerState(&cstatus.State)
 		normalizeContainerState(&cstatus.LastTerminationState)
 	}
-	// Sort the container statuses, so that the order won't affect the result of comparison
+	// Sort the init container statuses, so that the order won't affect the result of comparison
 	kubetypes.SortInitContainerStatuses(pod, status.InitContainerStatuses)
+
+	// update ephtemeral container statuses
+	for i := range status.EphemeralContainerStatuses {
```
Comment (HirazawaUi) [inline pkg/kubelet/status/status_manager.go:1045]: I think we can use one function to handle `InitContainerStatuses` `EphemeralContainerStatuses` and `ContainerStatuses` so that we can avoid duplication of code.

**Comment by HirazawaUi** [comment]
It may be helpful for us to add the usecase of `EphemeralContainerStatuses` in `TestStatusEquality`.

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (zhifei92) [reply pkg/kubelet/status/status_manager.go:1045]: Agreed, thx~

**Comment by zhifei92** [comment]
@ffromani Can you please review this PR again？Thx

File: pkg/kubelet/status/status_manager.go [hunk 2]
```diff
@@ -1023,23 +1023,26 @@ func normalizeStatus(pod *v1.Pod, status *v1.PodStatus) *v1.PodStatus {
...
-	sort.Sort(kubetypes.SortedContainerStatuses(status.ContainerStatuses))
 
-	// update init container statuses
-	for i := range status.InitContainerStatuses {
-		cstatus := &status.InitContainerStatuses[i]
-		normalizeContainerState(&cstatus.State)
-		normalizeContainerState(&cstatus.LastTerminationState)
-	}
-	// Sort the container statuses, so that the order won't affect the result of comparison
+	// Normalize and sort container statuses
```
Comment (ffromani) [inline pkg/kubelet/status/status_manager.go:1036]: these comments (for all the three invocations) look pretty redundant, but please do NOT resubmit just to fix this

**Review by ffromani — COMMENTED** [review]
is the testing code added sufficient to ensure we won't have unnecessary reconciliations? I see a unit test, do we need e2e tests?

**Comment by ffromani** [comment]
LGTM once test questions have been addressed

**Comment by zhifei92** [comment]
> LGTM once test questions have been addressed

I think the unit test is okay, but for e2e tests, currently, it seems that we can only verify correctness by filtering logs `Pod status is inconsistent with cached status for pod, a reconciliation should be triggere`. Once the logs are modified, the tests will become ineffective

**Comment by zhifei92** [comment]
Hello @ffromani, if you still think e2e testing is needed, could you help provide some ideas? I haven't come up with a good method to validate the test results yet.

**Review by ffromani — COMMENTED** [review]
/lgtm

but I'd value a second opinion about both the code and adding the e2e test or not.

**Comment by zhifei92** [comment]
> When we attempt to reconcile the status because of this bug, the object should be updated every time but never converge, leading to constant updates. This means the `resourceVersion` of the object should keep changing even if no actual semantic change is made.
> 
> A e2e test which cover this case could be to create a pod with ephemeral containers, triggering the issue reproducer, reach steady state, and observe the object for a small multiple of the status reconciliation interval (so if it is 10s, for like 30s + some extra grace time, like 3-5s). If the object never changes once reached steady state, the issue is confirmed fixed.
> 
> If it keeps changing because of the issue, then the bug is not fixed.
> 
> All the above said, tests which wait "long enough" are usually frowned upon, but in this case I think the steady state wait would be in the ballpark of 30-40s, thus manageable. But that's a fair concern indeed, so I'd defer the final call to other reviewers/the approvers.

Thank you very much for your suggestion. I agree that this is feasible to a certain extent. If the other reviewers concur, I will complete the e2e according to your approach.

**Comment by HirazawaUi** [comment]
> All the above said, tests which wait "long enough" are usually frowned upon, but in this case I think the steady state wait would be in the ballpark of 30-40s, thus manageable.


This test can be run in parallel, and we can further reduce the waiting time.

I believe adding e2e test requirements is reasonable, as it's a bug fix, and we need a definitive way to verify that it has been resolved.

**Comment by SergeyKanzhelev** [comment]
> /release-note-none

We may need to mention the bug this is fixing in release notes

File: pkg/kubelet/status/status_manager.go [hunk 3]
```diff
@@ -1023,23 +1023,26 @@ func normalizeStatus(pod *v1.Pod, status *v1.PodStatus) *v1.PodStatus {
...
+	normalizeContainerStatuses(status.ContainerStatuses)
+
+	// Normalize and sort init container statuses
+	normalizeContainerStatuses(status.InitContainerStatuses)
 	kubetypes.SortInitContainerStatuses(pod, status.InitContainerStatuses)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/status/status_manager.go:1041]: I thought you moved sorting to `normalizeContainerStatuses`? Am I missing something?

File: pkg/kubelet/status/status_manager.go (hunk 2 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/status/status_manager.go:1036]: +1, remove redundant comments

File: pkg/kubelet/status/status_manager.go (hunk 3 above)
Comment (zhifei92) [reply pkg/kubelet/status/status_manager.go:1041]: > I thought you moved sorting to `normalizeContainerStatuses`? Am I missing something?

Yes, this does lead to an unnecessary sorting of InitContainerStatuses. Would it be better to take the sorting out of normalizeContainerStatuses?

Comment (SergeyKanzhelev) [reply pkg/kubelet/status/status_manager.go:1041]: either remove it from normalizeContainerStatuses and add to ephemeral or delete from here. I think deleting it from here is the best

Comment (zhifei92) [reply pkg/kubelet/status/status_manager.go:1041]: > either remove it from normalizeContainerStatuses and add to ephemeral or delete from here. I think deleting it from here is the best

Do you prefer deleting `kubetypes.SortInitContainerStatuses`? Would this affect the order in which initContainers's statuses are displayed?

Comment (SergeyKanzhelev) [reply pkg/kubelet/status/status_manager.go:1041]: You have introduced a new func `normalizeContainerStatuses` that normilizes time and then sorts the collection. You removed the loop that normilizes the time on init contianers. But kept sorting here. So now init containers will be sorted once in `normalizeContainerStatuses`  and then again here. I suggest to remove it from here

Comment (SergeyKanzhelev) [reply pkg/kubelet/status/status_manager.go:1041]: Also make sure there is a test for forting of statuses

Comment (zhifei92) [reply pkg/kubelet/status/status_manager.go:1041]: `kubetypes.SortInitContainerStatuses` and `sort.Sort` have different sorting rules. `kubetypes.SortInitContainerStatuses` sorts initContainerStatuses based on the order initContainers were created, while `sort.Sort` sorts containers by their names. I'm concerned that if `kubetypes.SortInitContainerStatuses` is removed, it might affect the order of initContainerStatuses. `normalizeStatus` is called within `updateStatusInternal`, and the normalized status is then added to `podStatuses`. The `statusManager` will synchronize `podStatuses` to the apiserver.

https://github.com/kubernetes/kubernetes/blob/f0f7ff989a948389247e628c4c5a43e915f51daa/pkg/kubelet/status/status_manager.go#L654

Comment (SergeyKanzhelev) [reply pkg/kubelet/status/status_manager.go:1041]: I see. Let's remove the sort from the `normalizeContainerStatuses` and call sort for each collection separately. I wonder how they needs to be sorted for the ephemeral containers

**Comment by zhifei92** [comment]
> This means the resourceVersion of the object should keep changing even if no actual semantic change is made.

@ffromani Because the status hasn't changed, the patch status actually didn't occur. The main overhead here is getting the pod from the kube-apiserver every time syncPod is called.


related code:
https://github.com/kubernetes/kubernetes/blob/f0f7ff989a948389247e628c4c5a43e915f51daa/pkg/kubelet/status/status_manager.go#L839-L842

https://github.com/kubernetes/kubernetes/blob/f0f7ff989a948389247e628c4c5a43e915f51daa/pkg/kubelet/status/status_manager.go#L871-L880

kubelet logs：
```
Sep 14 07:57:14   218 status_manager.go:874] "Patch status for pod" pod="default/ephemeral-demo" podUID="2c115c12-0da2-491a-a807-9051a79b3642" patch="{\"metadata\":{\"uid\":\"2c115c12-0da2-491a-a807-9051a79b3642\"}}"
Sep 14 07:57:14   218 status_manager.go:881] "Status for pod is up-to-date" pod="default/ephemeral-demo" statusVersion=5
```

File: pkg/kubelet/status/status_manager.go (hunk 3 above)
Comment (zhifei92) [reply pkg/kubelet/status/status_manager.go:1041]: > I see. Let's remove the sort from the `normalizeContainerStatuses` and call sort for each collection separately. I wonder how they needs to be sorted for the ephemeral containers

The sorting rule for ephemeral containers is the same as that for regular containers, which is fine because their startup rules are similar, and neither requires ensuring that one is running before starting the next. However, it's worth noting that the existing ephemeral container statuses in the cluster have not been sorted. Updating this PR will cause the ephemeral container statuses to be sorted, but this isn't a problem.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
