### PR TITLE
Remove watching Endpoints of Headless Services

### LINKED ISSUE #81060: Kube-proxy should not watch endpoints from headless services
**What happened**:
With several large headless services in the cluster providing DNS records for statefulset pods, we see about 1TB of watch traffic for Endpoints per day! Some of these Endpoints objects approach 1MB in size and we have thousands of nodes, so a single update to the Endpoints object results in gigabytes of broadcast.

**What you expected to happen**:
kube-proxy does not need to receive any updates for headless services.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Big headless services like this are a stand-in for the lack of other pod-addressable DNS features. There's a lot of improvements that could be made to prevent this, but it seems like an extremely easy change to prevent kube-proxy from receiving updates for headless services.

A simple solution:
1. Make the Service controller propagate `ClusterIP: None` to a label on the Endpoints object like `service.k8s.io/headless: "true"` or similar.
2. Add a filter in kube-proxy's endpoints watch to exclude the headless label.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: EC2
- OS (e.g: `cat /etc/os-release`): custom distro
- Kernel (e.g. `uname -a`): 4.14.133
- Install tools: custom

### PR DESCRIPTION
**Pull request by rikatz**
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@serpro.gov.br>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**: This PR makes two changes:

* In the Endpoint Controller, if the parent Service is Headless, the child Endpoint will have a new annotation: ``service.kubernetes.io/headless``

* In the Kube-Proxy code, if this annotation exists and it's true the Endpoint Object will be ignored, not spending network bandwidth of Kube-Proxy with Headless Services

**Which issue(s) this PR fixes**:

Fixes #81060 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
Obs.: This is a WIP, as I still need to improve the tests related to this change
/sig network

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
/ok-to-test

File: pkg/controller/endpoint/endpoints_controller.go [hunk 1]
```diff
@@ -68,6 +69,12 @@ const (
 	// This field is deprecated. v1.Service.PublishNotReadyAddresses will replace it
 	// subsequent releases.  It will be removed no sooner than 1.13.
 	TolerateUnreadyEndpointsAnnotation = "service.alpha.kubernetes.io/tolerate-unready-endpoints"
+
+	// IsHeadlessServiceAnnotation is an annotation on the Endpoint denoting if its parent
+	// Service is Headless. This annotation can be used further by other controllers and
+	// kube-proxy to check if the Endpoint objects should be replicated when using Headless
+	// Services
+	IsHeadlessServiceAnnotation = "service.kubernetes.io/headless"
```
Comment (thockin) [inline pkg/controller/endpoint/endpoints_controller.go]: @freehan @robscott PTAL at this wrt EndpointSlice, specifically let's agree on naming.

I think you were planning on `kubernetes.io/service` ? 

Because we have manual service-endpoint pairs, we can't really make this a positive test (has a VIP), so I think it has to stay in this polarity (has no VIP).  The question is whether this should be `service.kubernetes.io` or `endpoints.kubernetes.io` or `svc-ctrl.kubernetes.io` or `kube-proxy.kubernetes.io`?   I think I lean towards `service.kubernetes.io` but not strongly.

Thoughts?

File: pkg/proxy/endpoints.go [hunk 2]
```diff
@@ -34,6 +34,8 @@ import (
 	utilnet "k8s.io/utils/net"
 )
 
+const isHeadlessServiceAnnotation = "service.kubernetes.io/headless"
```
Comment (thockin) [inline pkg/proxy/endpoints.go]: Can we make this a const somewhere?

File: pkg/proxy/endpoints.go [hunk 3]
```diff
@@ -237,6 +239,12 @@ func (ect *EndpointChangeTracker) endpointsToEndpointsMap(endpoints *v1.Endpoint
 		return nil
 	}
 
+	if endpoints.Annotations[isHeadlessServiceAnnotation] == "true" {
```
Comment (thockin) [inline pkg/proxy/endpoints.go]: What happens if you get "false" or "TRUE" or "True" or "1" ?

Let's be clear to document either `Only the exact value "true" (as a string) is considered true.` or else `The existence of this annotation is the signal and the value, while conventionally "true" (as a string) is not meaningful."

**Comment by rikatz** [comment]
/cc @nicksardo 
/cc @vllry 

Need some review here :)

Tks!

**Review by thockin — COMMENTED** [review]
This is not going to change the watch traffic, which was the original issue.  You'll need to update `ProxyServer.Run` (cmd/kube-proxy/app/server.go) to filter at the Informer (search for `WithTweakListOptions`).

Sadly, I don't see the documented grammar for that string field.  Sigh.  I found this: https://github.com/kubernetes/apimachinery/issues/47

File: pkg/controller/endpoint/endpoints_controller.go (hunk 1 above)
Comment (rikatz) [reply pkg/controller/endpoint/endpoints_controller.go]: @thockin Agree! Actually I've just put something that came to my mind in this annotation name, with the hope that someone with far more experience (in this case, YOU) could put some more coherent annotation naming.

I do agree it could be something like ``service.kubernetes.io/has-no-vip`` as naming through kube-proxy or svc-ctrl could lead to something not directly related to what this does (as this annotation could be used not only by kube-proxy, etc etc).

Anyway I'll wait until the folks working into the EndpointSlice take a look into this to agree on naming :)

File: pkg/proxy/endpoints.go (hunk 2 above)
Comment (rikatz) [reply pkg/proxy/endpoints.go]: Yes we can! I was looking for a better place to this const, as this is used in two different places of the code (controller and proxy) but couldn't find myself with a good solution that doesn't touches other critical parts of the code. 

Maybe, is there somewhere in Kubernetes Code a place (like some sort of types.go) with all the constants? Otherwise, I could import  the controller package into kube-proxy (don't think it's a good idea) or into apimachinery/pkg/types and import it into the endpoints_controller.go code.

File: pkg/proxy/endpoints.go (hunk 3 above)
Comment (rikatz) [reply pkg/proxy/endpoints.go]: So the idea here is to use this annotation the same way scheduler uses the ``scheduler.alpha.kubernetes.io/critical-pod``, with the simple existence of it representing that this is a Non VIP'ed service, right? Will take a look and improve this!

Thanks for your time :D

File: pkg/controller/endpoint/endpoints_controller.go (hunk 1 above)
Comment (robscott) [reply pkg/controller/endpoint/endpoints_controller.go]: We were planning on `kubernetes.io/service`, though that really doesn't look ideal after looking through what else is in use. Cloud load balancers are using a `kubernetes.io/service-name` annotation already which would match nicely with our EndpointSlice use case, so instead of creating a new annotation, it likely makes the most sense for us to stick with what's already in use. 

With that said, newer service related annotations seem to match the `service.kubernetes.io` scheme, including `service.kubernetes.io/service-proxy-name` and `service.kubernetes.io/load-balancer-cleanup`, so I'd agree with using something with that prefix here.

Comment (thockin) [reply pkg/controller/endpoint/endpoints_controller.go]: An annotation should indicate who owns it's meaning (organizationally) and have enough context that someone could figure it out.

Pardon while I think out loud for a moment:

wrt EndpointSlice there's not a "backlink" per se, but there *IS* OwnerReference, which we should make SURE to set.  That allows someone to back-track from an EPS to the Service that owns it.  That is not selectable, so we need something in labels.  BUT the thing that we stick in labels doesn't have to be friendly or generic, it just has to be discoverable.   What `kubernetes.io/service` or `kubernetes.io/service-name` has going for it is that it is implicit and known a priori.  I don't need to write anything into Service to say "here's how you find my endpoints".  One MIGHT argue that we should use UUID or something, but I don't know that it adds any value.  So at the end of this, I think `kubernetes.io/service-name` is fine.  We really just need to document the relationship.

Back to this PR.

We already have a const `LabelServiceProxyName` which uses `service.kubernetes.io/service-proxy-name` so I think `service.kubernetes.io/headless` is a reasonable name for this.

the existing `service-proxy-name` label is functionally identical to this, just semantically different meaning.  In other words, I should be able to specify `service.kubernetes.io/service-proxy-name: not-kube-proxy` on a headless Service today, and get the same result.

File: pkg/proxy/endpoints.go (hunk 2 above)
Comment (thockin) [reply pkg/proxy/endpoints.go]: pkg/proxy/apis/well_known_labels.go

File: pkg/proxy/endpoints.go (hunk 3 above)
Comment (thockin) [reply pkg/proxy/endpoints.go]: It's up to you, but that's how I would lean.  The value is "true" by convention, but even setting it to "false" or "" would still be true.

File: pkg/controller/endpoint/endpoints_controller.go (hunk 1 above)
Comment (rikatz) [reply pkg/controller/endpoint/endpoints_controller.go]: So, my understanding is that I can follow with this service.kubernetes.io/headless, as the idea is similar but the objective is different, right?

File: pkg/proxy/endpoints.go (hunk 2 above)
Comment (rikatz) [reply pkg/proxy/endpoints.go]: OK, got it. About the same annotation into pkg/controller/endpoint/endpoint_controller.go, should I declare it again (as an unexported constant) or import the pkg/proxy/apis into it?

My opinion about this is to redeclare it to keep the code from controller decoupled from proxy, but I may be wrong.

**Comment by rikatz** [comment]
@thockin Another thing I've figured out here is that I'm using annotations instead of labels. Will change some things here to reflect the Label usage (changing this to WIP again) and then report when it's ready

File: pkg/controller/endpoint/endpoints_controller.go (hunk 1 above)
Comment (thockin) [reply pkg/controller/endpoint/endpoints_controller.go]: yes, sorry to be confusing :)

File: pkg/proxy/endpoints.go (hunk 2 above)
Comment (thockin) [reply pkg/proxy/endpoints.go]: How about staging/src/k8s.io/api/core/v1/well_known_labels.go instead?

Comment (rikatz) [reply pkg/proxy/endpoints.go]: Changed here

File: pkg/proxy/endpoints.go (hunk 3 above)
Comment (rikatz) [reply pkg/proxy/endpoints.go]: So I'm assuming the existence of the Label is enough to ignore it into the informer. 

I've also described this into the const comment, is this enough? Otherwise I can be more descriptive

**Comment by rikatz** [comment]
I'm just trying to figure out how to test also this annotation. Probably I've to change something related to the e2e test (generate a headless service, check if kube-proxy watches it) but don't know where to start.

**Comment by rikatz** [comment]
@thockin Sorry for bothering you, but need some light here. While writing the e2e tests I've faced some lexical problem. 

While testing if a ClusterIP exists in all nodes of a cluster isn't hard, testing if something doesn't exists is pretty tricky.  

I can create a Service, but after it's created I cannot change it's ClusterIP to none. So do you have any idea on how to check if something DOESN'T happen in the cluster?

Clarifying, (here)[https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1885]  the tests check if a Service is Up. But when I create a Headless, no ClusterIP is allocated, so how can I check into a node its kube-proxy doesn't watches, fetch or whatever Endpoints from a Headless Service Object?

I was thinking about writing a test that tries to connect to headless name and check if the returned CIDR reflects the Pod Cidr (and not a serviceIP), but this doesn't solves the problem to check kube-proxy behavior.

Any ideas? Anything like checking kube-proxy's metrics to see if the object exists inside its existence is something plausible, or it might break more things than fix in future tests?

Thanks!!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
