### PR TITLE
fix ContainerRestartRules error message

### LINKED ISSUE #137135: ContainerRestartRules: exitCodes.values validation incorrectly reports "bytes" instead of "items"
### What happened?

When a container's `restartPolicyRules[].exitCodes.values` length exceeds 255 elements, the validation error message says:

```bash
containers[0].restartPolicyRules[0].exitCodes.values: Too long: may not be more than 255 bytes
```

The validation uses field.TooLong (byte length checks) instead of field.TooMany (slice length checks).

### What did you expect to happen?

The field is []int32, and the length limit is at most 255 elements, not 255 bytes.
If I am not wrong, I think the correct error message should be:
```bash
containers[0].restartPolicyRules[0].exitCodes.values: Too many: 256: must have at most 255 items
```

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L3716

### Anything else we need to know?

_No response_

### Kubernetes version

v1.35

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kfess**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

`restartPolicyRules[].exitCodes.values` validation uses `field.TooLong` (designed for byte length) instead of `field.TooMany` (designed for slice length), producing an incorrect error message:

```
containers[0].restartPolicyRules[0].exitCodes.values: Too long: may not be more than 255 bytes
```

This PR replaces it with `field.TooMany` to correctly report:

```
containers[0].restartPolicyRules[0].exitCodes.values: Too many: 256: must have at most 255 items
```

#### Which issue(s) this PR is related to:

Fixes #137135

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
Fixed validation error messages for restartPolicyRules and exitCodes.values to report "items" instead of "bytes"
```

### CODE REVIEW

**Review by kannon92 — COMMENTED** [review]
/lgtm

/label api-review

File: pkg/apis/core/validation/validation_test.go [hunk 1]
```diff
@@ -29606,6 +29606,44 @@ func TestValidateContainerRestartPolicy(t *testing.T) {
 				BadValue: core.ContainerRestartRuleOnExitCodesOperator(""),
 			}},
 		},
+		{
+			Name:          "restart-policy-rules with too many exit codes",
```
Comment (NIRANJAN0125) [inline pkg/apis/core/validation/validation_test.go:29610]: Nit: Can we keep formatting consistent.

**Review by NIRANJAN0125 — APPROVED** [review]
lgtm

**Review by yuanwang04 — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
