### PR TITLE
Fix to handle hash collisions correctly for DaemonSets

### LINKED ISSUE #62519: Add DaemonSet integration test for hash collision avoidance
/sig apps 

Ref #62145, #62146

### PR DESCRIPTION
**Pull request by mortent**
**What this PR does / why we need it**: This adds an integration test for the case where there is a hash collision when creating a ControllerRevision for a DaemonSet. It also fixes a shadowed variable that prevented this functionality from working as intended.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62519 

**Special notes for your reviewer**:
/sig apps

**Release note**:

```release-note
Fixes issue when updating a DaemonSet causes a hash collision.
```

### CODE REVIEW

**Comment by mortent** [comment]
CLA should be fixed now

File: pkg/controller/daemon/update.go [hunk 1]
```diff
@@ -337,9 +337,9 @@ func (dsc *DaemonSetsController) snapshot(ds *apps.DaemonSet, revision int64) (*
 			return nil, getErr
 		}
 		// Check if we already created it
-		done, err := Match(ds, existedHistory)
-		if err != nil {
-			return nil, err
+		done, matchErr := Match(ds, existedHistory)
```
Comment (mikedanese) [inline pkg/controller/daemon/update.go]: I feel like this is bound to happen again. Can you do something like
```go
if outerErr := err; errors.IsAlreadExists(outerErr) {
  ...
  return outerErr
}
```

File: test/integration/daemonset/daemonset_test.go [hunk 2]
```diff
@@ -740,3 +758,79 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+	if err != nil {
+		t.Fatalf("Failed to create ControllerRevision: %v", err)
+	}
+
+	_, err = dsClient.Update(ds)
+	if err != nil {
+		t.Fatalf("Failed to update DaemonSet: %v", err)
+	}
+
+	validateDaemonSetPodsAndMarkReady(podClient, podInformer, 1, t)
```
Comment (mikedanese) [inline test/integration/daemonset/daemonset_test.go]: should you validate that the collision counter is bumped and that the pod has TerminationGracePeriodSeconds set to one?

**Comment by mortent** [comment]
Updated to address comments from @mikedanese.

File: test/integration/daemonset/daemonset_test.go [hunk 3]
```diff
@@ -740,3 +782,90 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+	validateDaemonSetStatus(dsClient, ds.Name, 1, t)
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: `validateDaemonSetPodsAndMarkReady` checks DS has X number of pods and mark them Ready. It doesn't check if the Pods are updated or not. We can skip this step because we don't care if the pods are ready or not. 

`validateDaemonSetStatus` checks whether the status matches or not, but it doesn't check if the Pods are updated or not, either. 

There's a possible race that the Pods haven't been updated before we validate collision count and Pods. Suggest instead wait for new pods and new controllerrevision to be created, and then check DS's collision count.

File: test/integration/daemonset/daemonset_test.go [hunk 4]
```diff
@@ -740,3 +782,90 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+	_, name := hashAndNameForDaemonSet(ds)
+	revision, err := clientset.AppsV1().ControllerRevisions(ds.Namespace).Get(name, metav1.GetOptions{})
+	if err != nil || revision == nil {
+		t.Fatalf("Failed to look up ControllerRevision: %v", err)
+	}
+
+	one := int64(1)
+	ds.Spec.Template.Spec.TerminationGracePeriodSeconds = &one
+
+	newHash, newName := hashAndNameForDaemonSet(ds)
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: Suggest add comments for each step (or some steps).

**Review by janetkuo — COMMENTED** [review]
Thanks for catching the bug!

**Comment by mortent** [comment]
@janetkuo Thanks for the detailed review. 
I have updated the validation part of the test to wait for a pod to come up with the updated value for TerminationGracePeriodSeconds and then check that the CollisionCount is the expected value. I think this should avoid the race.
Also added some comments on the key steps in the test code.

File: test/integration/daemonset/daemonset_test.go [hunk 5]
```diff
@@ -740,3 +769,108 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+		for _, object := range objects {
+			pod := object.(*v1.Pod)
+			if *pod.Spec.TerminationGracePeriodSeconds == int64(1) {
+				return true, nil
+			}
+		}
+		return false, nil
+	})
+	if err != nil {
+		t.Fatal(err)
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: t.Fatalf("Failed to wait for Pods with the latest Spec to be created: %v", err)

File: test/integration/daemonset/daemonset_test.go [hunk 6]
```diff
@@ -740,3 +769,108 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+			OwnerReferences: []metav1.OwnerReference{*metav1.NewControllerRef(ds, apps.SchemeGroupVersion.WithKind("DaemonSet"))},
+		},
+		Data:     revision.Data,
+		Revision: revision.Revision + 1,
+	}
+	_, err = clientset.AppsV1().ControllerRevisions(ds.Namespace).Create(newRevision)
+	if err != nil {
+		t.Fatalf("Failed to create ControllerRevision: %v", err)
+	}
+
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: nit: save `ds`'s collision count here for comparison later. The count should be count+1 at the end of this test.

File: test/integration/daemonset/daemonset_test.go [hunk 7]
```diff
@@ -372,6 +374,33 @@ func waitForPodsCreated(podInformer cache.SharedIndexInformer, num int) error {
 	})
 }
 
+func waitForDaemonSetCreated(c clientset.Interface, name string, namespace string) error {
+	return wait.Poll(2*time.Second, 30*time.Second, func() (bool, error) {
```
[the remark this answers is not in the document]
Comment (mortent) [reply test/integration/daemonset/daemonset_test.go]: I've updated the test to use PollImmediate and shorter intervals and timeouts. I can do a separate PR to pull out the constants and switch the other tests in the file to use PollImmediate.

**Comment by mortent** [comment]
@janetkuo I have updated the PR based on the comments.

File: test/integration/daemonset/daemonset_test.go [hunk 8]
```diff
@@ -740,3 +788,112 @@ func TestInsufficientCapacityNodeWhenScheduleDaemonSetPodsEnabled(t *testing.T)
...
+		},
+	}
+	ds, err := dsClient.Create(orgDs)
+	if err != nil {
+		t.Fatalf("Failed to create DaemonSet: %v", err)
+	}
+	var orgCollisionCount int32
+	if ds.Status.CollisionCount != nil {
+		orgCollisionCount = *ds.Status.CollisionCount
+	}
```
Comment (janetkuo) [inline test/integration/daemonset/daemonset_test.go]: Move this down to L846 after DS's CR is created and a fresh DS is got back from the server. This is because collision count might change after CR creation.

**Review by janetkuo — APPROVED** [review]
