### PR TITLE
Print progress updates to stdout and publish to URL

### LINKED ISSUE #78535: Improved test progress reporting
**What would you like to be added**:
I would like a method of seeing more clear data while tests are running, e.g.:
 - How many tests will be run, have been run, have passed, have failed, etc.
 - Name of the tests passed/failed/skipped

**Why is this needed**:
While a run is going we _only_ have the output from stdout to investigate. There is a LOT of noise in those logs which is great for debugging after the fact, but difficult to consume most of the time.
 - you can't tell how many tests have been run or get a sense of how much time is left
 - you cant easily get a list of all tests that have failed so far

**My proposal**
 - Adding a new, custom ginkgo reporter that will post the data to a given URL (passed via a flag)
 - if the URL isn't set, the reporter is a noop and doesn't waste time/resources

Use cases:
 - A user runs the tests dumps stdout to a file for debugging later, meanwhile they run a local server that will just echo the status updates it gets. At any point they look at the output they can get good data about what would be run, how far along it is, how successful it has been so far.
 - Using the conformance test image and Sonobuoy, the Sonobuoy worker can act as the server, taking those status updates and reporting them to the aggregator. This would allow Sonobuoy to present that information to users on demand or stream it depending on the context.

The work of adding this is pretty minimal and is clearly useful.  In the case of Sonobuoy; this has been the most requested feature for a long time showing that people in the community really do want to have a better high-level picture of the progress of these tests. I think emitting the data to an endpoint like this is a flexible implementation that can help any consumer of the tests (not just Sonobuoy).

### PR DESCRIPTION
**Pull request by johnSchnake**
**What type of PR is this?**
/kind feature

Minor testing feature to clarify/surface progress of a test run.

**What this PR does / why we need it**:
One common frustration of end-users running the e2e suite is that
they take a significant amount of time and it is difficult to
gauge progress.

Even if tailing the logs it can be difficult to see where one
test starts and another ends or understand the if there have been
failures in the past 1h of logs.

This change adds a new custom reporter that prints summary information
as tests complete. This includes the number of tests to run and how
many have been passed/failed/skipped along with which tests have failed.

A new flag can be set which pushes these values to an endpoint. This is
intended for integration with Sonobuoy but any endpoint could consume and
surface this data to the user so they can better understand the state
of the current test run.

**Which issue(s) this PR fixes**:
Fixes #78535

**Special notes for your reviewer**:
I've published an image that utilizes this; see the `sonobuoy run` command below. It is based on the v1.16.0 conformance image but swaps out the e2e.test binary for my own from this PR.

**Does this PR introduce a user-facing change?**:
Only for testing; does not impact k8s users themselves.

```release-note
A new flag "progress-report-url" has been added to the test context which allows progress information about the test run to be sent to a webhook. In addition, this information is printed to stdout to aid in users watching the logs.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
Example output in logs:
```
{"msg":"PASSED [sig-storage] Downward API volume should update annotations on modification [NodeConformance] [Conformance]","total":277,"completed":5,"numFailures":0,"numSkipped":98}
```

Example command to utilize this with Sonobuoy (will have some more Sonobuoy improvements to make this a default and such, but wanted to show existing value):
```
sonobuoy run --kube-conformance-image=schnake/conformance:progressv4 --plugin-env e2e.E2E_EXTRA_ARGS="--progress-report-url=http://localhost:8099/progress"
```

And this leads to the value being readable from `sonobuoy status --json`:
```
{"plugins":[{"plugin":"e2e","node":"global","status":"running","result-status":"","result-counts":null,"progress":{"name":"e2e","node":"global","timestamp":"2019-10-29T15:29:48.0908739Z","msg":"PASSED [sig-cli] Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods  [Conformance]","total":277,"completed":24}}],"status":"running","tar-info":{"name":"","created":"0001-01-01T00:00:00Z","sha256":"","size":0}}
```

### CODE REVIEW

**Comment by johnSchnake** [comment]
/sig testing
/area e2e-test-framework
/priority important-longterm

- Marking as import-longterm but I'm hoping to get this merged for the v1.17 release.
- Technically a feature but is so small and is just a testing "feature" that a KEP does not seem necessary/appropriate.
- Happy to take feedback about tweaks to the printed data but I'm hoping we don't bikeshed too much at this time. We can tweak this over time if need-be but the basics about how many tests pass/fail are invaluable.

@dims @andrewsykim

File: test/e2e/reporters/progress.go [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+	default:
+		return
+	}
+
+	reporter.sendUpdates(msg)
+}
+
+// sendUpdates serializes the current progress and prints it to stdout and also posts it to the configured endpoint if set.
+func (reporter *ProgressReporter) sendUpdates(msg string) {
+	b := reporter.serializeWithMsg(msg, true)
```
Comment (johnSchnake) [inline test/e2e/reporters/progress.go]: As the other comment mentions, I opted to default to print the whole list of failures each time. This helps if you have just one of those values to parse and don't want to have to dig through all the log history to catch the list of the other failures.

**Comment by neolit123** [comment]
/approve
i like the idea!

File: test/e2e/reporters/progress.go [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+	Failures []string `json:"failures,omitempty"`
+
+	progressURL string
+	client      *http.Client
+}
+
+// NewProgressReporter returns a progress reporter which posts updates to the given URL.
+func NewProgressReporter(progressUpdateURL string) *ProgressReporter {
+	c := &http.Client{
+		Timeout: time.Second * 10,
```
Comment (SataQiu) [inline test/e2e/reporters/progress.go]: It looks great! But are you thinking about making `Timeout ` configurable?

File: test/e2e/reporters/progress.go [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+
+	Failures []string `json:"failures,omitempty"`
+
+	progressURL string
+	client      *http.Client
+}
+
+// NewProgressReporter returns a progress reporter which posts updates to the given URL.
+func NewProgressReporter(progressUpdateURL string) *ProgressReporter {
+	c := &http.Client{
```
Comment (SataQiu) [inline test/e2e/reporters/progress.go]: IMO, If the `progressUpdateURL` is empty, we don't have to create a http client.

**Review by SataQiu — APPROVED** [review]

File: test/e2e/reporters/progress.go (hunk 2 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: I don't really anticipate something like that being particularly configurable. It is really just specifying a timeout so it doesn't hang forever. And regardless, the penalty for one slow request is that it gets dropped effectively which is OK IMO for one or two events.

Do you see a reason it should be a higher value? I wouldn't care about increasing it to a high, but reasonable, value.

File: test/e2e/framework/test_context.go [hunk 4]
```diff
@@ -292,6 +295,8 @@ func RegisterCommonFlags(flags *flag.FlagSet) {
 
 	flags.BoolVar(&TestContext.ListImages, "list-images", false, "If true, will show list of images used for runnning tests.")
 	flags.StringVar(&TestContext.KubectlPath, "kubectl-path", "kubectl", "The kubectl binary to use. For development, you might use 'cluster/kubectl.sh' here.")
+
+	flags.StringVar(&TestContext.ProgressUpdateURL, "progress-report-url", "", "The URL to POST progress updates to as the suite runs to assist in aiding integrations. If empty, no messages sent.")
```
Comment (oomichi) [inline test/e2e/framework/test_context.go]: nit: just a question.
Why don't we name `ProgressReportURL` instead?
Most test context variables consist of the same words from the option names like the above.
That could be easy to search the code from the option name.

File: test/e2e/reporters/progress.go [hunk 5]
```diff
@@ -0,0 +1,148 @@
...
+		reporter.NumFailed++
+		reporter.LastMsg = fmt.Sprintf("FAILED %v", testname)
+	case types.SpecStatePassed:
+		reporter.NumCompleted++
+		reporter.LastMsg = fmt.Sprintf("PASSED %v", testname)
+	case types.SpecStateSkipped:
+		reporter.NumSkipped++
+		return
+	default:
+		return
```
Comment (oomichi) [inline test/e2e/reporters/progress.go]: just a question: This `default` case is unexpected, right?

File: test/e2e/reporters/progress.go [hunk 6]
```diff
@@ -0,0 +1,148 @@
...
+	"encoding/json"
+	"fmt"
+	"io/ioutil"
+	"net/http"
+	"strings"
+	"time"
+
+	"github.com/onsi/ginkgo/config"
+	"github.com/onsi/ginkgo/types"
+	"k8s.io/klog"
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: nit: split this import into a separate group

File: test/e2e/reporters/progress.go [hunk 7]
```diff
@@ -0,0 +1,148 @@
...
+)
+
+// ProgressReporter is a ginkgo reporter which tracks the total number of tests to be run/passed/failed/skipped.
+// As new tests are completed it updates the values and prints them to stdout and optionally, sends the updates
+// to the configured URL.
+type ProgressReporter struct {
+	LastMsg string `json:"msg"`
+
+	NumToBeRun   int `json:"total"`
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: Thoughts on `TestsTotal`?

File: test/e2e/reporters/progress.go [hunk 8]
```diff
@@ -0,0 +1,148 @@
...
+	NumCompleted int `json:"completed"`
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: Thoughts on `TestsCompleted`?

File: test/e2e/reporters/progress.go [hunk 9]
```diff
@@ -0,0 +1,148 @@
...
+	NumSkipped   int `json:"skipped"`
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: Thoughts on `TestsSkipped`

File: test/e2e/reporters/progress.go [hunk 10]
```diff
@@ -0,0 +1,148 @@
...
+	NumFailed    int `json:"failed"`
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: Thoughts on `TestsFailed`?

File: test/e2e/reporters/progress.go [hunk 11]
```diff
@@ -0,0 +1,148 @@
...
+// sendUpdates serializes the current progress and prints it to stdout and also posts it to the configured endpoint if set.
+func (reporter *ProgressReporter) sendUpdates() {
+	b := reporter.serialize()
+	fmt.Println(string(b))
+	go reporter.postProgressToURL(b)
+}
+
+func (reporter *ProgressReporter) postProgressToURL(b []byte) {
+	// If a progressURL and client is set/available then POST to it. Noop otherwise.
+	if reporter.client != nil && len(reporter.progressURL) > 0 {
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: nit: Can we return eraly here instead?
```
if report.client == nil || len(reporter.progressURL) == 0 {
      return
}

rest of the function...
```

File: test/e2e/reporters/progress.go [hunk 12]
```diff
@@ -0,0 +1,148 @@
...
+		return
+	}
+
+	reporter.sendUpdates()
+}
+
+// sendUpdates serializes the current progress and prints it to stdout and also posts it to the configured endpoint if set.
+func (reporter *ProgressReporter) sendUpdates() {
+	b := reporter.serialize()
+	fmt.Println(string(b))
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: Is this log line intentional?

**Review by andrewsykim — COMMENTED** [review]
Overall LGTM and seems useful, should probably be discussed in SIG testing or Testing Commons meeting (again) before approving?

File: test/e2e/reporters/progress.go (hunk 5 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: Correct; we are just parsing for success/failure/skip. There are other types but they aren't really applicable at this time for how we're using this (https://github.com/onsi/ginkgo/blob/000d317071340972710dc1da9ae3c2c016a7a560/types/types_test.go#L10-L16)

File: test/e2e/reporters/progress.go (hunk 7 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: The naming of total/failed/skipped all comes from the desired integration with Sonobuoy which has already defined these fields.

File: test/e2e/reporters/progress.go (hunk 12 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: Yes; one of the conditions/goals for doing this came from @timothysc during our testing commons meeting and it was to print out something useful to the user to get the same sort of feedback. Currently, when looking at the logs you can't make much sense of how the run as a whole is going or how close it is to finishing until it is done.

This solves that problem.

**Comment by johnSchnake** [comment]
@andrewsykim Our next meeting for testing commons is on the 11th (this coming monday) correct? If that's the case then I'm OK waiting to merge until then. I brought this up months ago when the ticket was filed but it had come up at the Aug5th meeting (some time ago!) and feedback was positive and I was given the green light to do this as long as I added stdout printing in additino to the webhook.

The only question implementation-wise I have is whether or not I should print the full list of failures to stdout as well. The way the Sonobuoy webhook is right now it expects the full status each time so we need to POST it that way. However, if you have a busted run with hundreds of failures it will definitely be sub-optimal to reprint the failed tests each time. The downside of changing the way its printed in each case is (1) it removes a benefit of this approach where you can grep for one of these progress lines and each one will be self-contained and really tell you the full state of affairs (2) it complicates the code a bit (3) may be less performant if we have to serialize a second time but the items are small most of the time so not a huge deal

File: test/e2e/reporters/progress.go (hunk 7 above)
Comment (andrewsykim) [reply test/e2e/reporters/progress.go]: Okay, figured it's fine to change it here since we only care about the json tags

File: test/e2e/reporters/progress.go [hunk 13]
```diff
@@ -0,0 +1,152 @@
...
+	client      *http.Client
+}
+
+// NewProgressReporter returns a progress reporter which posts updates to the given URL.
+func NewProgressReporter(progressReportURL string) *ProgressReporter {
+	rep := &ProgressReporter{
+		Failures:    []string{},
+		progressURL: progressReportURL,
+	}
+	if len(progressReportURL) == 0 {
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: This seems weird, should this be > 0?

File: test/e2e/reporters/progress.go (hunk 7 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: Oh I wa shrinking you meant the json tags; I’ll change the names of the variable Lea that’s fine.

File: test/e2e/reporters/progress.go (hunk 13 above)
Comment (johnSchnake) [reply test/e2e/reporters/progress.go]: Thanks! This was one of the lines I just updated and didn’t retest. Will update

File: test/e2e/e2e.go [hunk 14]
```diff
@@ -100,8 +101,11 @@ func RunE2ETests(t *testing.T) {
 			r = append(r, reporters.NewJUnitReporter(path.Join(framework.TestContext.ReportDir, fmt.Sprintf("junit_%v%02d.xml", framework.TestContext.ReportPrefix, config.GinkgoConfig.ParallelNode))))
 		}
 	}
-	klog.Infof("Starting e2e run %q on Ginkgo node %d", framework.RunID, config.GinkgoConfig.ParallelNode)
 
+	// Stream the progress to stdout and optionally a URL accepting progress updates.
+	r = append(r, e2ereporters.NewProgressReporter(framework.TestContext.ProgressReportURL))
```
Comment (andrewsykim) [inline test/e2e/e2e.go]: Can we just skip appending the progress reporter if the URL is empty?

Comment (andrewsykim) [reply test/e2e/e2e.go]: That means we also don't log to stdout but maybe that's okay?

Comment (andrewsykim) [reply test/e2e/e2e.go]: Or maybe logging to stdout should be a separate ginko reporter?

**Comment by johnSchnake** [comment]
I refreshed the image just to be sure we were testing the latest code; you can run:
```
sonobuoy run --plugin e2e --kube-conformance-image=schnake/conformance:demo --plugin-env e2e.E2E_EXTRA_ARGS="--progress-report-url=http://localhost:8099/progress" --image-pull-policy=IfNotPresent
```
to see it in action. Then wait a bit and start watching `sonobuoy status --json` to see the progress.

File: test/e2e/e2e.go (hunk 14 above)
Comment (johnSchnake) [reply test/e2e/e2e.go]: I'm not sure I understand the motivation to decouple the URL and stdout printing; all the logic to count/gather/serialize would be the same. Even if we reused this datatype and had one for stdout printing and one for posting to URLs, then the memory footprint and processing overhead would be double (one for each of the reporters).

What is the desired endgoal; you want the ability to disable this functionality?

Comment (andrewsykim) [reply test/e2e/e2e.go]: Yes --  it sounds like the new progress reporter is actually doing two things: reporting progress via stdout and reporting progress by sending a POST request to a URL. Based on how ginkgo deals with custom reports, it sounds like they should be decoupled. Reporting to stdout can be on by default but still optional. 

I won't block on this though but something we should consider in the future.

File: test/e2e/reporters/progress.go [hunk 15]
```diff
@@ -0,0 +1,153 @@
...
+
+	"github.com/onsi/ginkgo/config"
+	"github.com/onsi/ginkgo/types"
+)
+
+// ProgressReporter is a ginkgo reporter which tracks the total number of tests to be run/passed/failed/skipped.
+// As new tests are completed it updates the values and prints them to stdout and optionally, sends the updates
+// to the configured URL.
+type ProgressReporter struct {
+	LastMsg string `json:"msg"`
```
Comment (andrewsykim) [inline test/e2e/reporters/progress.go]: For a future PR, I think a `LastReported` timestamp would be useful.
