### PR TITLE
Fix scheduler performance regression after adding plugin metrics

### LINKED ISSUE #117592: Performance degradation in scheduler after adding metrics for counting plugin evaluation
### What happened?

We observed degradation in scheduling throughput, putting it under 100 pods/s.

Respective pprof of kube-scheduler points it to https://github.com/kubernetes/kubernetes/pull/115082:
image

/sig scheduling
/kind regression

### What did you expect to happen?

100 pods/node

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tosi3k**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In https://github.com/kubernetes/kubernetes/issues/117592 we see that the `WithLabelValues` generates visible CPU load in scheduler, negatively impacting the pod scheduling throughput.

Instead of performing metric lookup unnecessarily many times, let's cache the particular streams inside the filter and prefilter plugins.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/117592.

#### Special notes for your reviewer:

/assign @alculquicondor
/assign @mborsz
/kind bug
/sig scheduling

#### Does this PR introduce a user-facing change?

```release-note
Fix 1.27 performance regression in scheduler caused by frequent metric lookup on critical code path.
```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -73,6 +74,9 @@ type frameworkImpl struct {
 	postBindPlugins      []framework.PostBindPlugin
 	permitPlugins        []framework.PermitPlugin
 
+	instrumentedPreFilterPlugins []instrumentedPreFilterPlugin
+	instrumentedFilterPlugins    []instrumentedFilterPlugin
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:78]: let's get rid of the other lists.

```suggestion
	preFilterPlugins []instrumentedPreFilterPlugin
	filterPlugins    []instrumentedFilterPlugin
```

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -88,6 +92,18 @@ type frameworkImpl struct {
 	parallelizer parallelize.Parallelizer
 }
 
+type instrumentedFilterPlugin struct {
```
Comment (mborsz) [inline pkg/scheduler/framework/runtime/framework.go:95]: I think we can get rid of special slice by:
* changing filterPlugins back to []framework.FilterPlugin
* allowing getExtensionPoints to write there "raw" plugin
* later, in the same place as now you create `instrumentedFilterPlugins` slice, write (pseudocode) `i.filterPlugin[i] = &instrumentedFilterPlugin{i.filterPlugin[i], cachedMetric(i.filterPlugin[i]}`

instrumentedFilterPlugins can implement framework.FilterPlugin and increment the metric internally:

```suggestion
type instrumentedFilterPlugin struct {
	framework.FilterPlugin

	cachedMetric compbasemetrics.CounterMetric
}

func (i *instrumentedFilterPlugin) Filter(ctx context.Context, state *CycleState, pod *v1.Pod, nodeInfo *NodeInfo) *Status {
  i.cachedMetric.Inc()
  return i.instrumentedFilterPlugin.Filter(ctx, state, pod, nodeInfo)
}

var _ framework.FilterPlugin = &instrumentedFilterPlugin{}
```

Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/framework.go:95]: I'm happy with the above. Just make sure we don't report the metric increment if the plugin is supposed to be skipped.

File: pkg/scheduler/framework/runtime/framework.go (hunk 1 above)
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go]: Done.

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go:92]: Thanks for the suggestion Maciej. Done.

**Comment by mborsz** [comment]
Thanks!

File: pkg/scheduler/framework/runtime/framework.go [hunk 3]
```diff
@@ -88,6 +89,35 @@ type frameworkImpl struct {
...
+
+	cachedMetric compbasemetrics.CounterMetric
+}
+
+func (i *instrumentedFilterPlugin) Filter(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
+	i.cachedMetric.Inc()
+	return i.FilterPlugin.Filter(ctx, state, pod, nodeInfo)
+}
+
+var _ framework.FilterPlugin = &instrumentedFilterPlugin{}
```
Comment (kerthcet) [inline pkg/scheduler/framework/runtime/framework.go:103]: Nit: I guess we can have a separate file to contain these codes because we may have more wrapped plugins in the future but not strictly, we can do this later if we do.

Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go]: Done.

File: pkg/scheduler/framework/runtime/framework.go [hunk 4]
```diff
@@ -88,6 +89,35 @@ type frameworkImpl struct {
...
+
+func (i *instrumentedPreFilterPlugin) PreFilter(ctx context.Context, state *framework.CycleState, p *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
+	result, status := i.PreFilterPlugin.PreFilter(ctx, state, p)
+	if !status.IsSkip() {
+		i.cachedMetric.Inc()
+	}
+	return result, status
+}
+
+var _ framework.PreFilterPlugin = &instrumentedPreFilterPlugin{}
```
[the remark this answers is not in the document]
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go]: I see that the code flow for other plugins is rather:

* definition of struct
* static check that the struct satisfies the interface (`var _ ...`)
* implementation of receiver methods

Did the same in the separate file.

File: pkg/scheduler/framework/runtime/instrumented_plugins.go [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+
+	v1 "k8s.io/api/core/v1"
+	compbasemetrics "k8s.io/component-base/metrics"
+	"k8s.io/kubernetes/pkg/scheduler/framework"
+)
+
+type instrumentedFilterPlugin struct {
+	framework.FilterPlugin
+
+	cachedMetric compbasemetrics.CounterMetric
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/instrumented_plugins.go:30]:
```suggestion
	metric compbasemetrics.CounterMetric
```

File: pkg/scheduler/framework/runtime/framework.go [hunk 6]
```diff
@@ -358,6 +358,20 @@ func NewFramework(r Registry, profile *config.KubeSchedulerProfile, stopCh <-cha
 		options.captureProfile(outputProfile)
 	}
 
+	// Cache metric streams for prefilter and filter plugins.
+	for i, pl := range f.preFilterPlugins {
+		f.preFilterPlugins[i] = &instrumentedPreFilterPlugin{
+			f.preFilterPlugins[i],
+			metrics.PluginEvaluationTotal.WithLabelValues(pl.Name(), metrics.PreFilter, f.profileName),
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:365]: use named field for consistency with the codebase:

```suggestion
			PreFilterPlugin: pl,
			metric: metrics.PluginEvaluationTotal.WithLabelValues(pl.Name(), metrics.PreFilter, f.profileName),
```

File: pkg/scheduler/framework/runtime/instrumented_plugins.go [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+}
+
+var _ framework.FilterPlugin = &instrumentedFilterPlugin{}
+
+func (i *instrumentedFilterPlugin) Filter(ctx context.Context, state *framework.CycleState, p *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/instrumented_plugins.go:35]: `i` and `j` are usually iteration variables.

**Review by alculquicondor — COMMENTED** [review]
just nits for code consistency

/approve

File: pkg/scheduler/framework/runtime/instrumented_plugins.go (hunk 5 above)
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/instrumented_plugins.go]: Done.

File: pkg/scheduler/framework/runtime/framework.go (hunk 6 above)
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go]: Done.

File: pkg/scheduler/framework/runtime/instrumented_plugins.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/instrumented_plugins.go]: Done.

File: pkg/scheduler/framework/runtime/framework.go [hunk 8]
```diff
@@ -614,7 +658,6 @@ func (f *frameworkImpl) RunPreFilterPlugins(ctx context.Context, state *framewor
 			skipPlugins.Insert(pl.Name())
 			continue
 		}
-		metrics.PluginEvaluationTotal.WithLabelValues(pl.Name(), metrics.PreFilter, f.profileName).Inc()
```
[the remark this answers is not in the document]
Comment (tosi3k) [reply pkg/scheduler/framework/runtime/framework.go:617]: Not an expert in scheduler plugins but if we were to change the metric counting logic, I'd prefer for it to be a separate change from this PR.

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/framework.go:617]: +1, we need to keep this PR simple so it can be cherry-picked

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
Please open a cherry-pick for release-1.27

File: pkg/scheduler/framework/runtime/framework.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/runtime/framework.go]: That's how we did generally but not a big deal. https://github.com/kubernetes/kubernetes/blob/c4f6c4716990e05863b8817d8127b73111438843/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L42-L46

File: pkg/scheduler/framework/runtime/framework.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/runtime/framework.go:617]: Not related to this PR, just some discussions.
