### PR TITLE
Fixed check in kubectl autoscale.

### LINKED ISSUE #25815: kubectl autoscale prevents CPU percentages over 100%
In #18294, it was decided that CPU percentages over 100% on the HPA were valid, but should be warned about.  However, `kubectl autoscale` prevents you from passing `--cpu-percent=X` when X is over 100.

It seems confusing that if you create an autoscaler with `autoscale` it will prevent target CPU percentages over 100%, but after you create it, you can go in and edit it to be over 100% (or you could just create it with a value over 100% by creating via YAML).

We should probably change `kubectl autoscale` to just warn to be consistent.

cc @janetkuo @piosz @kubernetes/autoscaling @ncdc

### PR DESCRIPTION
**Pull request by jszczepkowski**
``` release-note
Fixed check in kubectl autoscale: cpu consumption can be higher than 100%.
```

[Analytics]()

Fixed check in kubectl autoscale: cpu consumption can be higher than 100%. Fixes #25815.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @mwielgus @piosz

**Comment by piosz** [comment]
cc @janetkuo

File: pkg/kubectl/cmd/autoscale.go [hunk 1]
```diff
@@ -192,12 +192,9 @@ func RunAutoscale(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []
 
 func validateFlags(cmd *cobra.Command) error {
 	errs := []error{}
-	max, min, cpu := cmdutil.GetFlagInt(cmd, "max"), cmdutil.GetFlagInt(cmd, "min"), cmdutil.GetFlagInt(cmd, "cpu-percent")
+	max, min := cmdutil.GetFlagInt(cmd, "max"), cmdutil.GetFlagInt(cmd, "min")
 	if max < 1 || max < min {
 		errs = append(errs, fmt.Errorf("--max=MAXPODS is required, and must be at least 1 and --min=MINPODS"))
 	}
-	if cpu > 100 {
-		errs = append(errs, fmt.Errorf("CPU utilization (%%) cannot exceed 100"))
```
Comment (DirectXMan12) [inline pkg/kubectl/cmd/autoscale.go]: Should we keep a warning in here, or just rely on the server-side warning proposed in #18294

Comment (jszczepkowski) [inline pkg/kubectl/cmd/autoscale.go]: AFAIK, there are no warning logged to output by kubectl. So, I didn't want to introduce them.

Comment (DirectXMan12) [inline pkg/kubectl/cmd/autoscale.go]: ACK

**Comment by DirectXMan12** [comment]
LGTM :+1:
