### PR TITLE
Use unix.EpollWait to determine when memcg events are available to be Read

### LINKED ISSUE #62808: Pod-startup performance related failures on 2k/5k-node tests
The latest runs of our gce-(large/scale)-performance jobs failed during the density test:
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/140 (this one failed due to pod-startup latency crossing 5s slo)
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-large-performance/83 (this one failed while waiting for some pod to come up)

These may be related, but need to dig in further.

cc @kubernetes/sig-scalability-bugs @wojtek-t 
/assign
/priority failing-test

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
This fixes a file descriptor leak introduced in https://github.com/kubernetes/kubernetes/pull/60531 when the `--experimental-kernel-memcg-notification` kubelet flag is enabled.  The root of the issue is that `unix.Read` blocks indefinitely when reading from an event file descriptor and there is nothing to read.  Since we refresh the memcg notifications, these reads accumulate until the memcg threshold is crossed, at which time all reads complete.  However, if the node never comes under memory pressure, the node can run out of file descriptors.

This PR changes the eviction manager to use `unix.EpollWait` to wait, with a 10 second timeout, for events to be available on the eventfd.  We only read from the eventfd when there is an event available to be read, preventing an accumulation of `unix.Read` threads, and allowing the event file descriptors to be reclaimed by the kernel.

This PR also breaks the creation, and updating of the memcg threshold into separate portions, and performs creation before starting the periodic synchronize calls.  It also moves the logic of configuring memory thresholds into memory_threshold_notifier into a separate file.

This also reverts https://github.com/kubernetes/kubernetes/pull/64582, as the underlying leak that caused us to disable it for testing is fixed here.

Fixes #62808

**Release note**:
```release-note
NONE
```

/sig node
/kind bug
/priority critical-urgent

### CODE REVIEW

**Comment by dashpole** [comment]
/assign @mtaufen @filbranden 
for review
/assign @dchen1107 
for approval, milestone, status in progress, and approved for milestone

**Comment by dashpole** [comment]
cc @shyamjvs @wojtek-t 
FYI

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+	cgroups, err := cm.GetCgroupSubsystems()
+	if err != nil {
+		return nil, err
+	}
+	cgpath, found := cgroups.MountPoints["memory"]
+	if !found || len(cgpath) == 0 {
+		return nil, fmt.Errorf("memory cgroup mount point not found")
+	}
+	if isAllocatableEvictionThreshold(threshold) {
+		cgpath += cgroupRoot
```
Comment (mtaufen) [inline pkg/kubelet/eviction/memory_threshold_notifier.go]: Can you add a comment noting why this transformation is necessary for allocatable eviction thresholds, but not other thresholds?

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+	}
+	memoryNotifier := &memoryThresholdNotifier{
+		threshold:  threshold,
+		cgroupPath: cgpath,
+	}
+	message := fmt.Sprintf("eviction manager: %s crossed", memoryNotifier.Description())
```
Comment (mtaufen) [inline pkg/kubelet/eviction/memory_threshold_notifier.go]: This var is only used once, maybe just inline the expression.

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+	memoryStats := summary.Node.Memory
+	if isAllocatableEvictionThreshold(m.threshold) {
+		allocatableContainer, err := getSysContainer(summary.Node.SystemContainers, statsapi.SystemContainerPods)
+		if err != nil {
+			return err
+		}
+		memoryStats = allocatableContainer.Memory
+	}
+	if memoryStats == nil || memoryStats.UsageBytes == nil || memoryStats.WorkingSetBytes == nil || memoryStats.AvailableBytes == nil {
+		return fmt.Errorf("summary was incomplete")
```
Comment (mtaufen) [inline pkg/kubelet/eviction/memory_threshold_notifier.go]: Would it be worth reporting which part was missing?

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+	// since we want to be notified when working_set = capacity - eviction_hard
+	inactiveFile := resource.NewQuantity(int64(*memoryStats.UsageBytes-*memoryStats.WorkingSetBytes), resource.BinarySI)
+	capacity := resource.NewQuantity(int64(*memoryStats.AvailableBytes+*memoryStats.WorkingSetBytes), resource.BinarySI)
+	evictionThresholdQuantity := evictionapi.GetThresholdQuantity(m.threshold.Value, capacity)
+	memcgThreshold := capacity.DeepCopy()
+	memcgThreshold.Sub(*evictionThresholdQuantity)
+	memcgThreshold.Add(*inactiveFile)
+	threshold := strconv.FormatInt(memcgThreshold.Value(), 10)
+	glog.V(3).Infof("eviction manager: setting %s to %s\n", m.Description(), threshold)
+	return m.notifier.UpdateThreshold(m.cgroupPath, memoryUsageAttribute, threshold)
```
Comment (mtaufen) [inline pkg/kubelet/eviction/memory_threshold_notifier.go]: Would it be better for UpdateThreshold to take a numerical argument for the threshold, instead of a string (potentially more type-safe)?

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 5]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		eventfd:   eventfd,
+		stop:      make(chan struct{}),
+	}
+	go notifier.getThresholdEvents(eventCh)
+	return notifier, nil
 }
 
-func getThresholdEvents(eventfd int, eventCh chan<- struct{}, stop ThresholdStopCh) {
+// getThresholdEvents waits for events on the eventfd and passes a struct into the eventCh when an event occurrs.
+func (n *cgroupNotifier) getThresholdEvents(eventCh chan<- struct{}) {
```
Comment (mtaufen) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: TODO(mtaufen): I haven't reviewed the rest of this file yet.

File: cluster/gce/config-test.sh [hunk 6]
```diff
@@ -191,6 +191,12 @@ TEST_CLUSTER_RESYNC_PERIOD="${TEST_CLUSTER_RESYNC_PERIOD:---min-resync-period=3m
 TEST_CLUSTER_API_CONTENT_TYPE="${TEST_CLUSTER_API_CONTENT_TYPE:-}"
```
[the remark this answers is not in the document]
Comment (dashpole) [reply cluster/gce/config-test.sh]: yeah, just in testing.  We wont turn it on by default in prod ever, as it can interact poorly with some kernel configs.  We will only enable it in GKE, not GCE

File: cluster/gce/config-test.sh [hunk 7]
```diff
@@ -191,6 +191,12 @@ TEST_CLUSTER_RESYNC_PERIOD="${TEST_CLUSTER_RESYNC_PERIOD:---min-resync-period=3m
...
 
 KUBELET_TEST_ARGS="${KUBELET_TEST_ARGS:-} --serialize-image-pulls=false ${TEST_CLUSTER_API_CONTENT_TYPE}"
+if [[ "${NODE_OS_DISTRIBUTION}" == "gci" ]] || [[ "${NODE_OS_DISTRIBUTION}" == "ubuntu" ]] || [[ "${NODE_OS_DISTRIBUTION}" == "custom" ]]; then 
+  NODE_KUBELET_TEST_ARGS=" --experimental-kernel-memcg-notification=true"  
+fi 
+if [[ "${MASTER_OS_DISTRIBUTION}" == "gci" ]] || [[ "${MASTER_OS_DISTRIBUTION}" == "ubuntu" ]]; then
```
[the remark this answers is not in the document]
Comment (dashpole) [reply cluster/gce/config-test.sh]: yes.  This is just a revert of #64582

File: pkg/kubelet/eviction/types.go [hunk 8]
```diff
@@ -132,19 +132,22 @@ type nodeReclaimFunc func() error
...
 type ThresholdNotifier interface {
-	Start(ThresholdStopCh)
+	// UpdateThreshold removes the previous threshold and adds the specified threshold to the specified attribute
+	// in the cgroup specified by the path.
+	UpdateThreshold(path, attribute, threshold string) error
+}
+
+// MemoryThresholdNotifier manages ThresholdNotifiers based on memory eviction thresholds, and performs a function
+// when memory eviction thresholds are crossed
+type MemoryThresholdNotifier interface {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/types.go]: Maybe a better name is `NotifierManager` or something.  I wanted to separate out the management of thresholds (I.E. taking eviction concepts like thresholds and the summary API and turning them into a set of kernel changes (using cgroup control, and managing event file descriptors)

[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/types.go]: Let me know what you think, and ill update it

File: pkg/kubelet/eviction/memory_threshold_notifier.go (hunk 4 above)
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 9]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+				return true, nil
+			}
+		}
+	}
+	// An event occurred that we don't care about.
+	return false, nil
+}
+
+// close closes all file descriptors associated with the cgroup notifier, and ensures all goroutines associated with it exit
+func (n *cgroupNotifier) close() {
```
Comment (mtaufen) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: I think you also need to close the `epfd` here?

File: pkg/kubelet/eviction/testing/mock_memory_threshold_notifier.go [hunk 10]
```diff
@@ -0,0 +1,52 @@
+/*
```
Comment (mtaufen) [inline pkg/kubelet/eviction/testing/mock_memory_threshold_notifier.go]: Would it be worth writing some kind of stress test that checks for file descriptor leaks? It looks like there may be a lot of opportunities for leaks given how many different fds need to be managed by this feature.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 11]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
 	for {
-		buf := make([]byte, 8)
-		_, err := unix.Read(eventfd, buf)
+		event, err := wait(epfd, n.eventfd)
 		if err != nil {
+			glog.Warningf("eviction manager: error while waiting for memcg events: %v", err)
 			return
+		} else if event {
+			// Consume the event from the eventfd
+			buf := make([]byte, 8)
```
Comment (mtaufen) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Is there a constant somewhere in the standard lib that describes how big this buffer should be?

**Comment by mtaufen** [comment]
@dashpole are you targeting 1.11 for this?

File: pkg/kubelet/eviction/types.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/types.go]: Having 2 interfaces (one that integrates with cgroups, and one that configures it specifically for the memory eviction thresholds) allows me to mock the one that does all of the integration with linux, and do unit tests on the one that does the configuration based on the eviction thresholds.

I am not sure the ThresholdNotifierSet would actually make the eviction manager code simpler.  It would just mean removing a single for loop from `synchronize`.  Or maybe I am missing something.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 12]
```diff
@@ -18,24 +18,57 @@ package eviction
...
+		<-n.events
+		n.handler(n.message)
+	}
+}
+
+func (n *thresholdNotifier) UpdateThreshold(path, attribute string, threshold int64) (err error) {
+	if n.notifier != nil {
+		n.notifier.close()
+	}
+	n.notifier, err = newCgroupNotifier(n.events, path, attribute, threshold)
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 13]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+			case <-n.stop:
+				return
+			case eventCh <- struct{}{}:
+			}
 		}
 
-		select {
-		case eventCh <- struct{}{}:
-		case <-stop.Ch():
+		if _, ok := <-n.stop; !ok {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: The eventCh may no longer be read from.  If stop is closed, we shouldn't block on sending the event.
If we get a timeout (wait returned `event=false`), we skip the above select statement, but need to exit if `stop` is closed.  I couldn't figure out a cleaner way to do it.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 14]
```diff
@@ -18,24 +18,57 @@ package eviction
...
-// is crossed (in either direction) for a given cgroup attribute
-func NewMemCGThresholdNotifier(path, attribute, threshold, description string, handler thresholdNotifierHandlerFunc) (ThresholdNotifier, error) {
+// NewThresholdNotifier returns an implementation of ThresholdNotifier for linux builds
+func NewThresholdNotifier(message string, handler thresholdNotifierHandlerFunc) ThresholdNotifier {
+	n := &thresholdNotifier{
+		handler: handler,
+		message: message,
+		events:  make(chan struct{}),
+	}
+	go n.processEvents()
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I moved it to the UpdateThreshold function.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: order doesnt matter

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 15]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
-		handler:     handler,
-		description: description,
-	}, nil
+	notifier := &cgroupNotifier{
+		watchfd:   watchfd,
+		controlfd: controlfd,
+		eventfd:   eventfd,
+		stop:      make(chan struct{}),
+	}
+	go notifier.getThresholdEvents(eventCh)
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: moved to a start method

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 16]
```diff
@@ -18,24 +18,57 @@ package eviction
...
+		events:  make(chan struct{}),
+	}
+	go n.processEvents()
+	return n
+}
+
+func (n *thresholdNotifier) processEvents() {
+	for {
+		<-n.events
+		n.handler(n.message)
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I now generate the message there, rather than storing it, since it is just based on the description

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 17]
```diff
@@ -67,51 +100,105 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+	}
+	go notifier.getThresholdEvents(eventCh)
+	return notifier, nil
 }
 
-func getThresholdEvents(eventfd int, eventCh chan<- struct{}, stop ThresholdStopCh) {
+// getThresholdEvents waits for events on the eventfd and passes a struct into the eventCh when an event occurrs.
+func (n *cgroupNotifier) getThresholdEvents(eventCh chan<- struct{}) {
+	epfd, err := unix.EpollCreate1(0)
+	if epfd == -1 {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I believe there is, but i'll just check err

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 9 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: done

File: pkg/kubelet/eviction/testing/mock_memory_threshold_notifier.go (hunk 10 above)
Comment (dashpole) [reply pkg/kubelet/eviction/testing/mock_memory_threshold_notifier.go]: I am hoping this is caught by our soak tests...

**Comment by dashpole** [comment]
I would like to target 1.11 for this, as it is an important bug-fix (fixes a file-descriptor leak) when the feature gate is enabled.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 11 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: not sure.  This is part of the current implementation: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/threshold_notifier_linux.go#L87

File: pkg/kubelet/eviction/eviction_manager.go [hunk 18]
```diff
@@ -85,10 +83,12 @@ type managerImpl struct {
...
 	// last observations from synchronize
 	lastObservations signalObservations
-	// notifierStopCh is a channel used to stop all thresholdNotifiers
-	notifierStopCh ThresholdStopCh
 	// dedicatedImageFs indicates if imagefs is on a separate device from the rootfs
 	dedicatedImageFs *bool
+	// thresholdNotifiers is a list of memory threshold notifiers which each notify for a memory eviction threshold
+	thresholdNotifiers []MemoryThresholdNotifier
+	// notifierLastUpdated is the time at which the memory cgroup notifiers were last configured
+	notifierLastUpdated time.Time
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/eviction_manager.go]: done

File: pkg/kubelet/eviction/eviction_manager.go [hunk 19]
```diff
@@ -85,10 +83,12 @@ type managerImpl struct {
 	signalToNodeReclaimFuncs map[evictionapi.Signal]nodeReclaimFuncs
 	// last observations from synchronize
 	lastObservations signalObservations
-	// notifierStopCh is a channel used to stop all thresholdNotifiers
-	notifierStopCh ThresholdStopCh
 	// dedicatedImageFs indicates if imagefs is on a separate device from the rootfs
 	dedicatedImageFs *bool
+	// thresholdNotifiers is a list of memory threshold notifiers which each notify for a memory eviction threshold
+	thresholdNotifiers []MemoryThresholdNotifier
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/eviction_manager.go]: now that the interface is named ThresholdNotifier, it makes more sense :)

File: cluster/gce/config-test.sh (hunk 7 above)
[the remark this answers is not in the document]
Comment (filbranden) [reply cluster/gce/config-test.sh]: nitpick: Pre-existing, but I'm wondering if this should preserve the previous value of the variable (if there's any):

```
NODE_KUBELET_TEST_ARGS="${NODE_KUBELET_TEST_ARGS:-} --experimental-kernel-memcg-notification=true"  
```

(And same for `MASTER_KUBELET_TEST_ARGS`.)

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 20]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+	if err != nil {
+		glog.Warningf("eviction manager: error creating epoll: %v", err)
+		return nil, err
+	}
+	if epfd < 0 {
+		err = fmt.Errorf("EpollCreate1 call failed")
+		return nil, err
+	}
+	defer func() {
+		if err != nil {
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: nitpick: I find this approach of checking `if err != nil` in a defer to be error-prone, since it leads to artificial code (`err = fmt.Errorf("EpollCreate1 call failed")`) and can easily break if `err` is not properly managed. Go's scoping can also make this worse.

My suggestion, instead, would be to initialize the fd variables to -1, then install a single defer function like so:

```go
defer func() {
  if watchfd >= 0 {
    unix.Close(watchfd)
  }
  if controlfd >= 0 {
    unix.Close(controlfd)
  }
  if eventfd >= 0 {
    unix.Close(eventfd)
  }
  if epfd >= 0 {
    unix.Close(epfd)
  }
}()
```

And then wrap up the code by setting these all to -1 again after transferring them to the linuxCgroupNotifier:

```go
notifier := &linuxCgroupNotifier{...}
// Prevent deferred cleanup function from closing these fds.
watchfd = -1
controlfd = -1
eventfd = -1
epfd = -1
```

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 11 above)
Comment (filbranden) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: This is part of the Linux eventfd API. See [the man page](http://man7.org/linux/man-pages/man2/eventfd.2.html), which says:

```
       read(2)
              Each successful read(2) returns an 8-byte integer.  A read(2)
              fails with the error EINVAL if the size of the supplied buffer
              is less than 8 bytes.
```

I'm not sure a constant exists for this size... It doesn't seem to exist in the C API either...

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 21]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		return
+	}
 	for {
-		buf := make([]byte, 8)
-		_, err := unix.Read(eventfd, buf)
+		event, err := wait(n.epfd, n.eventfd)
 		if err != nil {
+			glog.Warningf("eviction manager: error while waiting for memcg events: %v", err)
 			return
+		} else if event {
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: nitpick: Handle the case where event is false with a continue, that way you can unindent the main part of the code. Also, should we log/warn on that case? Or is it expected?

```golang
if err != nil {
  glog.Warningf(...)
  return
}
if !event {
  glog.Warningf(...)  // Should we warn in this case?
  continue
}
// Consume the event from the eventfd
```

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 13 above)
[the remark this answers is not in the document]
Comment (filbranden) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I'm not sure I follow... In any case, this probably belongs in a comment on the code, since I'd say it's far from obvious to the reader of this code.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 22]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+
+				// EPOLLERR: If an error is waiting on the file descriptor, we should pretend
+				// something is ready to read, and let unix.Read pick up the error.
+
+				// EPOLLIN: There is data to read.
+				return true, nil
+			}
+		}
+	}
+	// An event occurred that we don't care about.
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Oh, I see... But why not keep waiting in this case? Since that seems to be what the caller is doing anyways, just call wait() again...

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 23]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+			// Interrupt, ignore the error
+			return false, nil
 		}
+		return false, err
+	}
+	if n == 0 {
+		// Timeout
+		return false, nil
+	}
+	if n > 6 {
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Please add a comment to explain why 6 is the magic number here...

You might want to declare a function, since you also use 6+1 when creating the events slice.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 24]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		err = fmt.Errorf("EpollCreate1 call failed")
+		return nil, err
+	}
+	defer func() {
+		if err != nil {
+			unix.Close(epfd)
+		}
+	}()
+	config := fmt.Sprintf("%d %d %d", eventfd, watchfd, threshold)
 	_, err = unix.Write(controlfd, []byte(config))
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: I'm fairly sure you don't need to keep controlfd around after you do this write, so you could just close it and not store the fd in &linuxCgroupNotifier...

I'm also like 99% sure you don't need the watchfd either, could be closed here too, no need to store it.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 25]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+	}
+	if n == 0 {
+		// Timeout
+		return false, nil
+	}
+	if n > 6 {
+		return false, fmt.Errorf("epoll_wait returned more events than we know what to do with")
+	}
+	for _, event := range events[:n] {
+		if event.Fd == int32(eventfd) {
```
Comment (filbranden) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: Should you log/warn when `event.Fd != int32(eventfd)`?

**Review by filbranden — APPROVED** [review]
Sorry for the delay in reviewing this code...

I have some suggestions, but none of them is really blocking, I'd be happy enough if this gets submitted as it is. But feel free to adopt some of the suggestions if you like them.

Cheers,
Filipe

File: cluster/gce/config-test.sh (hunk 7 above)
[the remark this answers is not in the document]
Comment (dashpole) [reply cluster/gce/config-test.sh]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 11 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: doen

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 21 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: done.  We expect wait to return false most of the time, as we are setting a 10 sec timeout.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 22 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: It gives us the opportunity to check the stop channel in the main loop.  I could pass the stop channel in, and have it do that itself, but we would still need to keep the loop in the `Start` function anyways to handle multiple events.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 23 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: added a constant.

File: pkg/kubelet/eviction/types.go [hunk 26]
```diff
@@ -131,20 +131,31 @@ type nodeReclaimFunc func() error
...
+	NewCgroupNotifier(path, attribute string, threshold int64) (CgroupNotifier, error)
+}
+
+// ThresholdNotifier manages CgroupNotifiers based on memory eviction thresholds, and performs a function
+// when memory eviction thresholds are crossed
 type ThresholdNotifier interface {
-	Start(ThresholdStopCh)
+	// HandleEvents creates a goroutine to call the notifier function when the CgroupNotifier notifies
+	// the ThresholdNotifier that an event occurred
+	HandleEvents(handler func(string))
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/types.go]: Changed to start, with function passed in at construction time.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 25 above)
Comment (filbranden) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: The inotify_poller.go code you mentioned says:

```golang
// 3 possible events per fd, and 2 fds, makes a maximum of 6 events.
```

In our case, we're only looking at one single fd... so maybe this should be 3 and 3+1?

> multiple goroutines or processes on the host call `Epoll` functions that they could see events for each other ...

I'm not sure that's the case... unless the Go implementation is totally broken in that sense. I mean, you tell it specifically which fd's you're watching...

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 27]
```diff
@@ -0,0 +1,143 @@
...
+		cgpath += cgroupRoot
+	}
+	memoryNotifier := &memoryThresholdNotifier{
+		threshold:  threshold,
+		cgroupPath: cgpath,
+		events:     make(chan struct{}),
+		factory:    factory,
+		clock:      clock,
+	}
+	glog.Infof("eviction manager: created %s", memoryNotifier.Description())
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: done

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 28]
```diff
@@ -0,0 +1,143 @@
...
+	return memoryNotifier, nil
+}
+
+func (m *memoryThresholdNotifier) HandleEvents(handler func(string)) {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: updated the comment

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 29]
```diff
@@ -0,0 +1,143 @@
...
+	for range m.events {
+		handler(fmt.Sprintf("eviction manager: %s crossed", m.Description()))
+	}
+}
+
+func (m *memoryThresholdNotifier) UpdateThreshold(summary *statsapi.Summary) error {
+	if m.clock.Since(m.lastUpdated) < notifierRefreshInterval {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: moved back to the eviction manager controlling when UpdateThreshold is called

File: pkg/kubelet/eviction/mock_threshold_notifier.go [hunk 30]
```diff
@@ -0,0 +1,98 @@
...
+	statsapi "k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1"
+)
+
+// MockCgroupNotifier is a mock implementation of the CgroupNotifier interface
+type MockCgroupNotifier struct {
+	mock.Mock
+}
+
+// Start implements the NotifierFactory interface
+func (_m *MockCgroupNotifier) Start(_a0 chan<- struct{}) {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/mock_threshold_notifier.go]: removed all the underscores

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 31]
```diff
@@ -0,0 +1,143 @@
...
+	if isAllocatableEvictionThreshold(m.threshold) {
+		allocatable = "allocatable "
+	}
+	return fmt.Sprintf("%s%smemory eviction threshold", hard, allocatable)
+}
+
+var _ NotifierFactory = &RealNotifierFactory{}
+
+// RealNotifierFactory knows how to make CgroupNotifiers which integrate with the kernel
+type RealNotifierFactory struct{}
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: done

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 32]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
-			unix.Close(n.controlfd)
-			unix.Close(n.eventfd)
-			return
-		case <-eventCh:
-			glog.V(2).Infof("eviction: threshold crossed")
-			n.handler(n.description)
+// wait waits up to notifierRefreshInterval for an event on the Epoll FD for the
+// eventfd we are concerned about.  It returns an error if one occurrs, and true
+// if the consumer should read from the eventfd.
+func wait(epfd, eventfd int) (bool, error) {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: done

**Comment by tallclair** [comment]
From the verify build log:
```
I0607 02:42:51.454] Found bad symbol 'httptest':
I0607 02:42:51.455] 00000000037cc850 t net/http/httptest.init
I0607 02:42:51.455] 00000000089b42c5 b net/http/httptest.initdone.
I0607 02:42:51.455] 0000000008988ac8 b net/http/httptest.serve
I0607 02:42:52.051] Found bad symbol 'testify':
I0607 02:42:52.052] 000000000898c420 b k8s.io/kubernetes/vendor/github.com/stretchr/testify/assert.AnError
I0607 02:42:52.053] 00000000037cc970 t k8s.io/kubernetes/vendor/github.com/stretchr/testify/assert.init
I0607 02:42:52.053] 00000000089b408d b k8s.io/kubernetes/vendor/github.com/stretchr/testify/assert.initdone.
I0607 02:42:52.054] 00000000037cca80 t k8s.io/kubernetes/vendor/github.com/stretchr/testify/mock.init
I0607 02:42:52.054] 00000000089b408e b k8s.io/kubernetes/vendor/github.com/stretchr/testify/mock.initdone.
```

It looks like something is importing test libraries.

File: pkg/kubelet/eviction/memory_threshold_notifier_test.go [hunk 33]
```diff
@@ -0,0 +1,305 @@
...
+					Quantity: quantityMustParse("1Gi"),
+				},
+			},
+			expectedThreshold:  resource.MustParse("4Gi"),
+			updateThresholdErr: fmt.Errorf("unexpected error"),
+			expectErr:          true,
+		},
+	}
+
+	for _, tc := range testCases {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier_test.go]: done

File: pkg/kubelet/eviction/mock_threshold_notifier.go [hunk 34]
```diff
@@ -0,0 +1,98 @@
...
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+package eviction
+
+import (
+	mock "github.com/stretchr/testify/mock"
```
Comment (tallclair) [inline pkg/kubelet/eviction/mock_threshold_notifier.go]: Here's your problem. Mocks need to either: be in a separate package (`package eviction_test`), separate directory (`testing` subdir & package), or file with the `_test.go` suffix.

File: pkg/kubelet/eviction/memory_threshold_notifier_test.go [hunk 35]
```diff
@@ -0,0 +1,305 @@
...
+		}
+	}
+	return &statsapi.Summary{
+		Node: statsapi.NodeStats{
+			Memory: &memoryStats,
+		},
+	}
+}
+
+func newTestMemoryThresholdNotifier(threshold evictionapi.Threshold, cgpath string, factory NotifierFactory, clock clock.Clock) (*memoryThresholdNotifier, error) {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier_test.go]: we need the reference to the original factory and clock so that we can call methods on them that are not in the interface, e.g. clock.Step or notifierFactory.On.
But we can assume we are using the testCgroupPath.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 22 above)
Comment (filbranden) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I actually think passing this a channel is a slightly better API (also would get immediate notifications instead of depending on the timeout to poll "stop".)

But I can see how it might be hard to implement that, since you need to bridge Go channels and Linux epoll...

I guess the way to do that would be to open a pipe here and add the read side of the pipe to the epoll you're blocking on.

Then launch a goroutine that would block on the channel and, if it gets anything from it, write to the write end of the pipe (therefore leaving the epoll.)

But that's a lot of code, for little gain...

So I guess fine to keep this as is.

I'm not too pleased about the return of `(bool, error)`... Would there be a better way to return "timeout" as a specific error and check for that condition?

In that case, you might only want to return that on "timeout", in all other cases where you're currently returning false, you could just loop inside this function again...

But maybe that's too much bikeshedding and we should leave this alone... Up to you, whatever you prefer is fine with me.

Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: Ill change to a timeout error

Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: or err... There are a lot of cases where we just want to retry the wait... I think I am just going to leave it alone

File: pkg/kubelet/eviction/memory_threshold_notifier.go [hunk 36]
```diff
@@ -0,0 +1,143 @@
...
+	factory     NotifierFactory
+	clock       clock.Clock
+	lastUpdated time.Time
+	notifier    CgroupNotifier
+}
+
+var _ ThresholdNotifier = &memoryThresholdNotifier{}
+
+// NewMemoryThresholdNotifier creates a ThresholdNotifier which is designed to respond to the given threshold.
+// UpdateThreshold must be called once before the threshold will be active.
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier.go]: I have thought about this.  The problem is that we frequently fail to construct the summary API when the node is initializing.  If I added the summary as an argument to the constructor, the constructor would likely fail when the node first starts up.  In that case, I would want to add retries, which I would rather not do...

File: pkg/kubelet/eviction/mock_threshold_notifier.go (hunk 34 above)
Comment (dashpole) [reply pkg/kubelet/eviction/mock_threshold_notifier.go]: yeah, moved to a _test.go file

**Comment by tpepper** [comment]
Reminder: if this will target 1.11, @kubernetes/sig-node-bugs please set the milestone and SIG approval.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 24 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: nice catch.  Removed (and tested to make sure it is safe)

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 20 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: I think i'll stick with the current design.  I think it is more readable.

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 37]
```diff
@@ -67,51 +70,118 @@ func NewMemCGThresholdNotifier(path, attribute, threshold, description string, h
...
+		// Timeout
+		return false, nil
+	}
+	if n > 6 {
+		return false, fmt.Errorf("epoll_wait returned more events than we know what to do with")
+	}
+	for _, event := range events[:n] {
+		if event.Fd == int32(eventfd) {
+			if event.Events&unix.EPOLLHUP != 0 || event.Events&unix.EPOLLERR != 0 || event.Events&unix.EPOLLIN != 0 {
+				// EPOLLHUP: should not happen, but if it does, treat it as a wakeup.
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: From http://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html
`A device has been disconnected, or a pipe or FIFO has been closed by the last process that had it open for writing. Once set, the hangup state of a FIFO shall persist until some process opens the FIFO for writing or until all read-only file descriptors for the FIFO are closed. This event and POLLOUT are mutually-exclusive; a stream can never be writable if a hangup has occurred. However, this event and POLLIN, POLLRDNORM, POLLRDBAND, or POLLPRI are not mutually-exclusive. This flag is only valid in the revents bitmask; it shall be ignored in the events member.`
I think this would only happen if the kernel closed the eventfd?  It should be the only process that has it open for writing...

File: pkg/kubelet/eviction/eviction_manager.go (hunk 19 above)
[the remark this answers is not in the document]
Comment (mtaufen) [reply pkg/kubelet/eviction/eviction_manager.go]: yup :)

File: pkg/kubelet/eviction/mock_threshold_notifier_test.go [hunk 38]
```diff
@@ -0,0 +1,98 @@
...
+	}
+	return r0, r1
+}
+
+// MockThresholdNotifier is a mock implementation of the ThresholdNotifier interface
+type MockThresholdNotifier struct {
+	mock.Mock
+}
+
+// HandleEvents implements the ThresholdNotifier interface
```
Comment (mtaufen) [inline pkg/kubelet/eviction/mock_threshold_notifier_test.go]: fix rename in comment

File: pkg/kubelet/eviction/memory_threshold_notifier_test.go [hunk 39]
```diff
@@ -0,0 +1,270 @@
...
+				t.Errorf("Expected error updating threshold, but got nil")
+			}
+			if !tc.expectErr {
+				notifierFactory.AssertNumberOfCalls(t, "NewCgroupNotifier", 1)
+			}
+		})
+	}
+}
+
+func TestHandleEvents(t *testing.T) {
```
Comment (mtaufen) [inline pkg/kubelet/eviction/memory_threshold_notifier_test.go]: fix to match rename

File: pkg/kubelet/eviction/threshold_notifier_linux.go [hunk 40]
```diff
@@ -18,42 +18,44 @@ package eviction
...
-type memcgThresholdNotifier struct {
-	watchfd     int
-	controlfd   int
-	eventfd     int
-	handler     thresholdNotifierHandlerFunc
-	description string
+const (
+	// eventfdSize is the number of bytes returned by a successful read from an eventfd
+	// see http://man7.org/linux/man-pages/man2/eventfd.2.html for more information
+	eventfdSize = 8
```
Comment (mtaufen) [inline pkg/kubelet/eviction/threshold_notifier_linux.go]: nit: it's the size of the event, not the size of the fd, right?

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 20 above)
Comment (mtaufen) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: Another alternative, that might be more readable than `>=` would be to name the errors 1:1 with the fds.

File: pkg/kubelet/eviction/threshold_notifier_linux.go (hunk 40 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_linux.go]: done

File: pkg/kubelet/eviction/memory_threshold_notifier_test.go (hunk 39 above)
Comment (dashpole) [reply pkg/kubelet/eviction/memory_threshold_notifier_test.go]: done

File: pkg/kubelet/eviction/mock_threshold_notifier_test.go (hunk 38 above)
Comment (dashpole) [reply pkg/kubelet/eviction/mock_threshold_notifier_test.go]: done

**Comment by dashpole** [comment]
I created a script that calls into linux_threshold_notifier.go and verified two things:
* Creating, starting and stopping linux threshold notifiers does not leak file descriptors (after running the loop thousands of times, still just a single eventfd open).
* Calling `Stop()` on the notifier does not cause an epollhup

**Comment by dashpole** [comment]
I think this should be good to go.

File: pkg/kubelet/eviction/threshold_notifier_unsupported.go [hunk 41]
```diff
@@ -18,10 +18,16 @@ limitations under the License.
...
-import "fmt"
+import "github.com/golang/glog"
 
-// NewMemCGThresholdNotifier sends notifications when a cgroup threshold
-// is crossed (in either direction) for a given cgroup attribute
-func NewMemCGThresholdNotifier(path, attribute, threshold, description string, handler thresholdNotifierHandlerFunc) (ThresholdNotifier, error) {
-	return nil, fmt.Errorf("threshold notification not supported")
+// NewCgroupNotifier creates a cgroup notifier that does nothing because cgroups do not exist on non-linux systems.
+func NewCgroupNotifier(path, attribute string, threshold int64) (CgroupNotifier, error) {
+	glog.V(5).Infof("cgroup notifications not supported")
```
Comment (mtaufen) [inline pkg/kubelet/eviction/threshold_notifier_unsupported.go]: Use Errorf, not Infof.

**Review by mtaufen — COMMENTED** [review]
One comment then LGTM

File: pkg/kubelet/eviction/threshold_notifier_unsupported.go (hunk 41 above)
Comment (dashpole) [reply pkg/kubelet/eviction/threshold_notifier_unsupported.go]: oh, right.  There is no such thing as `glog.V(5).Errorf`, only `glog.Errorf`.  Ill need to revert back to what I had.

Comment (mtaufen) [reply pkg/kubelet/eviction/threshold_notifier_unsupported.go]: Huh, how about that.

**Comment by dchen1107** [comment]
/lgtm

approve the pr based on @filbranden and @mtaufen's reviews.
