### PR TITLE
Persist Bindings annotations alongside pod Host assignment

### LINKED ISSUE #4103: Binding annotations should be preserved alongside Host assignment
Recap of related tangent in #2483 follows.

Use case:  I need to implement mesos task reconciliation in the kubernetes-mesos scheduler. If it crashes and then restarts, I want to be able to recover things like taskID, slaveID, offerID, etc. so as to rebuild the internal state of the scheduler. Once state is recovered, I can reconcile the against the tasks that the mesos master knows about.

If I can't use binding annotations for this, then I need to store state some other (super inconvenient) way. Currently the etcd registry assignPod() implementation drops binding annotations on the floor. It should not, and instead they should be preserved for later access.

Proposal: Store binding-related annotations in a new field: Pod.Status.Annotations
* When setting Pod.Status.Host="{some-host-name}" via assignPod(), binding annotations are copied in from Binding
* When cloning Pod.Status.Host in UpdatePod() (for an already-scheduled pod), the Pod.Status.Annotations are also cloned.

I don't think /bindings has to be a readable apiserver endpoint, as long as the binding metadata is exposed some other way, as proposed above.

I'd also like to propose that once binding annotations are "bound" to Pod.Status they become read-only. So they're essentially write-once, just like Pod.Status.Host is meant to be.

cc @smarterclayton @bgrant0607 @erictune 
xref https://github.com/mesosphere/kubernetes-mesos/issues/73

### PR DESCRIPTION
**Pull request by jdef**
- resolves #4103

as per @bgrant0607:

> Status must be completely reconstructable based on observations. The proposed Pod.Status.Annotations would not be. Furthermore, I don't think we should introduce another annotations field to Pod. I'd prefer to add a podAnnotations field to Binding, and then merge them into the pod. As for clearing the annotations, I'd prefer to simply fail a pod that was rejected by a node so as not to have to deal with that.

In this PR, Bindings.Annotations are merged with those of the Pod, overwriting the values of any pre-existing keys. If the binding fails, the pod is flagged as failed.

Also added error checking in Binding creation, returning a more appropriate Status object on errors.

cc @smarterclayton @erictune

### CODE REVIEW

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/73

**Comment by jdef** [comment]
FWIW I've already signed the CLA

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/162

**Comment by smarterclayton** [comment]
I can do the review on this

**Comment by jdef** [comment]
I applied this patch to the k8s code that I'm running in kubernetes-mesos and the annotations are still not showing up in the pod: they're missing in the pod json returned by the apiserver and are also not present in etcd. Digging in...

File: pkg/registry/pod/etcd/etcd.go [hunk 1]
```diff
@@ -191,10 +205,23 @@ func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) e
 		return boundPodList, nil
 	})
 	if err != nil {
-		// Put the pod's host back the way it was. This is a terrible hack, but
-		// can't really be helped, since there's not really a way to do atomic
-		// multi-object changes in etcd.
-		if _, err2 := r.setPodHostTo(ctx, podID, machine, ""); err2 != nil {
+		glog.V(1).Infof("failing pod %v because constraint checks failed", podID)
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: Please don't make this v1. It will happen too frequently. I suggest v4.

**Comment by bgrant0607** [comment]
Gratefully punting review to @smarterclayton, who is also touching /bindings right now.

This behavior needs to be documented, ideally somewhere that would appear in the swagger (e.g., in the description on the ObjectMeta field for Binding), as well as in a .md doc. Note that descriptions on fields for v1beta3 are in flight.

**Comment by jdef** [comment]
related work in #5054

**Comment by smarterclayton** [comment]
Sorry for the delay, will get to this very soon.

File: pkg/registry/pod/etcd/etcd.go [hunk 2]
```diff
@@ -191,10 +205,23 @@ func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) e
...
+		podKey, err2 := r.store.KeyFunc(ctx, podID)
+		if err2 == nil {
+			err2 = r.store.Helper.AtomicUpdate(podKey, &api.Pod{}, false, func(obj runtime.Object) (runtime.Object, error) {
+				if pod, ok := obj.(*api.Pod); !ok {
+					return nil, fmt.Errorf("unexpected object: %#v", obj)
+				} else if pod.Status.Host != machine {
```
Comment (smarterclayton) [inline pkg/registry/pod/etcd/etcd.go]: Can you remove the else's here?  Since you're returning they're not necessary and it fits our style more (if the if block returns, never use else).

**Comment by smarterclayton** [comment]
Just my comment and Brian's I think.  Sorry again for the delay.

**Comment by bgrant0607** [comment]
Fails gofmt:
```
!! gofmt needs to be run on the following files: 
./pkg/registry/pod/etcd/etcd.go
```

File: pkg/registry/pod/etcd/etcd.go [hunk 3]
```diff
@@ -191,10 +205,24 @@ func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) e
...
+				pod, ok := obj.(*api.Pod)
+				if !ok {
+					return nil, fmt.Errorf("unexpected object: %#v", obj)
+				}
+				if pod.Status.Host != machine {
+					return nil, fmt.Errorf("pod %v is already assigned to host %v", pod.Name, pod.Status.Host)
+				} 
+				pod.Status.Host = "" //TODO(jdef) get rid of this once BoundPods goes away
+				pod.Status.Phase = api.PodFailed
+				pod.Status.Message = fmt.Sprintf("Assignment to host %v failed", machine)
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: Sorry, I was too terse last time. Please also populate Reason with something like `HostAssignmentFailed`. The more detailed message is useful, but the concise form (in particular, without the hostname) is useful for stats collection.

**Comment by jdef** [comment]
@bgrant0607 It looks like reason codes are pretty specific and should closely track HTTP codes. So I changed the pod.status.message to what you suggested, and set the api.status.reason to Conflict. The api.status.message will include a more detailed description of what went wrong.

Sound ok?

File: pkg/registry/pod/etcd/etcd.go [hunk 4]
```diff
@@ -142,15 +142,24 @@ func (r *BindingREST) New() runtime.Object {
 // Create ensures a pod is bound to a specific host.
 func (r *BindingREST) Create(ctx api.Context, obj runtime.Object) (out runtime.Object, err error) {
 	binding := obj.(*api.Binding)
-	err = r.assignPod(ctx, binding.PodID, binding.Host)
+	err = r.assignPod(ctx, binding.PodID, binding.Host, binding.Annotations)
 	err = etcderr.InterpretCreateError(err, "binding", "")
-	out = &api.Status{Status: api.StatusSuccess}
+	if err != nil {
```
Comment (smarterclayton) [inline pkg/registry/pod/etcd/etcd.go]: Hrm, this is somewhat wrong, because InterpretCreateError may already create an appropriate api.Status.  If assignPod needs to return special errors, that should happen in that method (using errors.NewConflict)

**Comment by jdef** [comment]
@smarterclayton just re-read your comment after I pushed the "clean up error handling" change. PTAL and let me know if you still think I should create NewConflict errors in assignPod.

File: pkg/registry/pod/etcd/etcd.go [hunk 5]
```diff
@@ -146,15 +147,20 @@ func (r *BindingREST) New() runtime.Object {
 // Create ensures a pod is bound to a specific host.
 func (r *BindingREST) Create(ctx api.Context, obj runtime.Object) (out runtime.Object, err error) {
 	binding := obj.(*api.Binding)
-	err = r.assignPod(ctx, binding.PodID, binding.Host)
-	err = etcderr.InterpretCreateError(err, "binding", "")
+	err = r.assignPod(ctx, binding.PodID, binding.Host, binding.Annotations)
+	if err = etcderr.InterpretCreateError(err, "binding", ""); err != nil {
+		if _, ok := err.(*errors.StatusError); !ok {
```
Comment (smarterclayton) [inline pkg/registry/pod/etcd/etcd.go]: This is fine for now.  Bindings internal storage will be cleanup up over successive iterations so we don't need the perfect solution now.

**Comment by smarterclayton** [comment]
This looks good to me - can you go ahead and squash?

**Comment by jdef** [comment]
squashed

On Mon, Mar 9, 2015 at 11:30 AM, Clayton Coleman <notifications@github.com>
wrote:

> This looks good to me - can you go ahead and squash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005#issuecomment-77875688>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by smarterclayton** [comment]
Will merge after tests pass again.

**Comment by smarterclayton** [comment]
Hrm, seeing a transient failure that looks related to this pull (not sure if it's coincidence or enemy action):

```
--- FAIL: TestEtcdCreateBindingNoPod (0.00s)
	<autogenerated>:29: returning /registry/pods/default/foo: &etcd.Response{Action:"", Node:(*etcd.Node)(nil), PrevNode:(*etcd.Node)(nil), EtcdIndex:0x0, RaftIndex:0x0, RaftTerm:0x0} &etcd.EtcdError{ErrorCode:100, Message:"", Cause:"", Index:0x0}
	etcd_test.go:873: Unexpected error returned: &errors.StatusError{ErrStatus:api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"binding \"\" cannot be updated: 100:  () [0]", Reason:"Conflict", Details:(*api.StatusDetails)(0xc20817eec0), Code:409}}
FAIL
coverage: 87.1% of statements
```

**Comment by jdef** [comment]
Funny, I think it's related to another PR of mine that was just merged. I'll take a look

**Comment by jdef** [comment]
@smarterclayton I'm not sure what's holding up the coveralls test. From what I can see the tests pass.

**Comment by smarterclayton** [comment]
K, will look in a bit

File: pkg/registry/pod/etcd/etcd.go [hunk 6]
```diff
@@ -203,14 +218,28 @@ func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) e
...
+				pod, ok := obj.(*api.Pod)
+				if !ok {
+					return nil, fmt.Errorf("unexpected object: %#v", obj)
+				}
+				if pod.Status.Host != machine {
+					return nil, fmt.Errorf("pod %v is already assigned to host %v", pod.Name, pod.Status.Host)
+				}
+				pod.Status.Host = "" //TODO(jdef) get rid of this once BoundPods goes away
+				pod.Status.Phase = api.PodFailed
+				pod.Status.Message = "HostAssignmentFailed"
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: Pod status message should be more informative, such as including the host. Search the code for examples.

File: pkg/registry/pod/etcd/etcd.go [hunk 7]
```diff
@@ -183,14 +189,23 @@ func (r *BindingREST) setPodHostTo(ctx api.Context, podID, oldMachine, machine s
...
-func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) error {
-	finalPod, err := r.setPodHostTo(ctx, podID, "", machine)
-	if err != nil {
+func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string, annotations map[string]string) error {
+	translateError := func(err error) error {
+		err = etcderr.InterpretCreateError(err, "binding", "")
+		err = etcderr.InterpretGetError(err, "pod", podID)
+		err = etcderr.InterpretUpdateError(err, "pod", podID)
+		if _, ok := err.(*errors.StatusError); !ok && err != nil {
+			err = errors.NewConflict("binding", "", err)
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: I'm concerned about returning conflict for constraint failures. Clients may retry assuming it's a resourceVersion mismatch.

Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: We should create a new StatusReason -- we already support 2 different reasons for 409. How about "ResourceConflict"? It's a bit unfortunate that "resource" is ambiguous due to usage in the REST context, but I can envision conflicts on other underlying infrastructure resources (e.g., networking) in the future.

**Comment by bgrant0607** [comment]
Don't worry about coveralls. It appears to be wedged.

**Comment by jdef** [comment]
Thanks for the feedback @bgrant0607. I've pushed some changes to address your concerns.

**Comment by jdef** [comment]
PTAL @bgrant0607 @smarterclayton

File: pkg/api/types.go [hunk 8]
```diff
@@ -1025,6 +1025,13 @@ const (
 	// Status code 409
 	StatusReasonConflict StatusReason = "Conflict"
 
+	// StatusReasonResourceConflict means the requested update operation cannot be completed
+	// due to a resource conflict in the operation. The client may need to alter the request.
```
Comment (bgrant0607) [inline pkg/api/types.go]: How about "due to conflicting usage of underlying system/infrastructure resources".

File: pkg/api/types.go [hunk 9]
```diff
@@ -1025,6 +1025,13 @@ const (
...
+	// Each resource may define custom details that indicate the nature of the
```
Comment (bgrant0607) [inline pkg/api/types.go]: "Each API resource..."

This is confusing because we're using the term "resource" with 2 different meanings, but I couldn't think of a better word.

File: pkg/registry/pod/etcd/etcd.go [hunk 10]
```diff
@@ -203,12 +215,31 @@ func (r *BindingREST) assignPod(ctx api.Context, podID string, machine string) e
...
 	})
 	if err != nil {
-		// Put the pod's host back the way it was. This is a terrible hack, but
-		// can't really be helped, since there's not really a way to do atomic
-		// multi-object changes in etcd.
-		if _, err2 := r.setPodHostTo(ctx, podID, machine, ""); err2 != nil {
+		glog.V(4).Infof("failing pod %v because constraint checks failed", podID)
+		podKey, err2 := r.store.KeyFunc(ctx, podID)
+		if err2 == nil {
+			err2 = r.store.Helper.AtomicUpdate(podKey, &api.Pod{}, false, func(obj runtime.Object) (runtime.Object, error) {
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: Why can't you use setPodHostAndAnnotations?

File: pkg/registry/pod/etcd/etcd.go [hunk 11]
```diff
@@ -176,6 +176,12 @@ func (r *BindingREST) setPodHostTo(ctx api.Context, podID, oldMachine, machine s
 			return nil, fmt.Errorf("pod %v is already assigned to host %v", pod.Name, pod.Status.Host)
 		}
 		pod.Status.Host = machine
```
Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: You'll need to rebase this FYI.

File: pkg/registry/pod/etcd/etcd.go (hunk 10 above)
Comment (jdef) [inline pkg/registry/pod/etcd/etcd.go]: I'll consolidate. I thought it would be uglier adding an extra `failed` or `rollback` parameter to `setPodHostAndAnnotations`, but it would keep the pod host & status update code all in one place -- which I think is what you're aiming for, yes?

Comment (bgrant0607) [inline pkg/registry/pod/etcd/etcd.go]: Yes, thanks.

**Comment by jdef** [comment]
addressed your concerns @bgrant0607 PTAL

File: pkg/registry/pod/etcd/etcd.go (hunk 11 above)
Comment (jdef) [inline pkg/registry/pod/etcd/etcd.go]: done

On Wed, Mar 11, 2015 at 6:33 PM, Brian Grant <notifications@github.com>
wrote:

> In pkg/registry/pod/etcd/etcd.go
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005#discussion_r26263030>
> :
>
> > @@ -176,6 +176,12 @@ func (r *BindingREST) setPodHostTo(ctx api.Context, podID, oldMachine, machine s
> >  			return nil, fmt.Errorf("pod %v is already assigned to host %v", pod.Name, pod.Status.Host)
> >  		}
> >  		pod.Status.Host = machine
>
> You'll need to rebase this FYI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005/files#r26263030>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

File: pkg/api/types.go (hunk 8 above)
Comment (jdef) [inline pkg/api/types.go]: done

On Wed, Mar 11, 2015 at 6:29 PM, Brian Grant <notifications@github.com>
wrote:

> In pkg/api/types.go
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005#discussion_r26262653>
> :
>
> > @@ -1025,6 +1025,13 @@ const (
> >  	// Status code 409
> >  	StatusReasonConflict StatusReason = "Conflict"
> >
> > +	// StatusReasonResourceConflict means the requested update operation cannot be completed
> > +	// due to a resource conflict in the operation. The client may need to alter the request.
>
> How about "due to conflicting usage of underlying system/infrastructure
> resources".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005/files#r26262653>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by bgrant0607** [comment]
Code LGTM.

Are you able to run the e2e test? The change to write Spec.Host in setPodHostTo broke it, due to somewhat fragile assumptions.

We just added documentation of status codes to docs/api-conventions.md. Could you please add documentation on ResourceConflict there?

**Comment by bgrant0607** [comment]
Alternatively, we could remove ResourceConflict and change back to Conflict. Host mismatch or etcd collision are the only reasons for failure now, since we removed hostport conflict detection.

We'll likely want to add back some best-effort constraint checking at some point. See:
https://github.com/GoogleCloudPlatform/kubernetes/issues/5207#issuecomment-78613182

But we don't have it now.

I'll leave it up to you.

cc @jszczepkowski

**Comment by jdef** [comment]
Removed ResourceConflict. I don't want to muddy the water with additional
constraint checking here.

On Thu, Mar 12, 2015 at 9:43 PM, Brian Grant <notifications@github.com>
wrote:

> Alternatively, we could remove ResourceConflict and change back to
> Conflict. Host mismatch or etcd collision are the only reasons for failure
> now, since we removed hostport conflict detection.
>
> We'll likely want to add back some best-effort constraint checking at some
> point. See:
> #5207 (comment)
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/5207#issuecomment-78613182>
>
> But we don't have it now.
>
> I'll leave it up to you.
>
> cc @jszczepkowski <https://github.com/jszczepkowski>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/5005#issuecomment-78739798>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jdef** [comment]
@bgrant0607 any final thoughts?

**Comment by jdef** [comment]
PTAL @bgrant0607 @smarterclayton

**Comment by bgrant0607** [comment]
LGTM
