### PR TITLE
Ignore the available volume when calling DetachDisk

### LINKED ISSUE #50207: DetachDisk should not fail if status is available in OpenStach volume
When detaching disk, if the volume status is already available, detach should return true instead of error. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L261

### PR DESCRIPTION
**Pull request by FengyunPan**
Fix #50207
If user detachs the volume by nova in openstack env, volume becomes
available. If nova instance is been deleted, nova will detach it
automatically and become available. So the "available" is fine since that means the
volume is detached from instance already.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/cloudprovider/providers/openstack/openstack_volumes.go [hunk 1]
```diff
@@ -258,10 +254,10 @@ func (os *OpenStack) DetachDisk(instanceID, volumeID string) error {
 	if err != nil {
 		return err
 	}
-	if volume.Status != VolumeInUseStatus {
-		errmsg := fmt.Sprintf("can not detach volume %s, its status is %s.", volume.Name, volume.Status)
-		glog.Errorf(errmsg)
-		return errors.New(errmsg)
+	if volume.Status == VolumeAvailableStatus {
```
Comment (kars7e) [inline pkg/cloudprovider/providers/openstack/openstack_volumes.go]: What about statuses other than in-use or available? Shouldn't we return an error if volume is in error state?

Comment (FengyunPan) [inline pkg/cloudprovider/providers/openstack/openstack_volumes.go]: Yeah, I should restore the original codes, thank for your comment, I will update it soon.
