### PR TITLE
fix binary check for nfs.go

### LINKED ISSUE #56479: exec.Run didn't return an error when ls has a non-zero exit code
Some code uses `ls` to check if binary exist. But it does not work as expected.
use `test -x file`  instead.
/kind bug

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
err check can't show that the binary does not exist.
If the binary does not exist, the err still be nil ever. 
we should add print check to show if the binary exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/56479

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
ping @saad-ali

**Comment by zhangxiaoyu-zidif** [comment]
@jingxu97  PTAL

**Comment by saad-ali** [comment]
/cancel lgtm
/cancel approve

lgtm'd the wrong pr :) Taking a look at this one again

**Comment by saad-ali** [comment]
Wouldn't binary not existing cause non-0 exit code and `exec.Run` to return an error?

**Comment by zhangxiaoyu-zidif** [comment]
@saad-ali , binary not existing would not return an error. So the check here does not work.

**Comment by jsafrane** [comment]
Shouldn't we use `test -x /sbin/mount.nfs` then? Checking ls output is weird.

**Comment by zhangxiaoyu-zidif** [comment]
Hi， @jsafrane 
you mean using ‘test -x /sbin/mount.nfs’ and then check exit code?

**Comment by jsafrane** [comment]
@zhangxiaoyu-zidif, yes.
```
if retBytes, err := exec.Run("test", "-x", "/sbin/mount.nfs"); err != nil {
    thrown error
}
```

**Comment by msau42** [comment]
When I run ls on my machine, it does have a non zero return code

**Comment by zhangxiaoyu-zidif** [comment]
@msau42  yes, its exit code is non 0, but err is NIL

**Comment by msau42** [comment]
/lgtm

I'm still curious why `exec.Run` didn't return an error when `ls` has a non-zero exit code.

File: pkg/volume/nfs/nfs.go [hunk 1]
```diff
@@ -194,15 +194,15 @@ func (nfsMounter *nfsMounter) CanMount() error {
 	exec := nfsMounter.plugin.host.GetExec(nfsMounter.plugin.GetPluginName())
 	switch runtime.GOOS {
 	case "linux":
-		if _, err := exec.Run("/bin/ls", "/sbin/mount.nfs"); err != nil {
+		if _, err := exec.Run("test", "-x", "/sbin/mount.nfs"); err != nil {
```
Comment (dims) [inline pkg/volume/nfs/nfs.go]: Can't we just do os.Stat("/path/to/whatever") ?

Comment (jsafrane) [reply pkg/volume/nfs/nfs.go]: No, `mount.nfs` can be in a container. `exec.Run` runs the command in the right place.

**Comment by zhangxiaoyu-zidif** [comment]
@msau42 @jsafrane  should this PR cherry-pick to v1.9?
