### PR TITLE
VSAN support for VSphere Volume Plugin

### LINKED ISSUE #28625: VSphere Volume doesn't unmount
While deleting the pod the vsphere volume doesn't unmount. Kubelet log is as follows,

435 goroutinemap.go:156] Operation for "kubernetes.io/vsphere-volume/[vsanDatastore]volumes/test3" failed. No retries permitted until 2016-07-07 12:33:32.757609336 -0700 PDT (durationBeforeRetry 500ms). error: UnmountVolume.TearDown failed for volume "kubernetes.io/vsphere-volume/[vsanDatastore]volumes/test3" (volume.spec.Name: "vmdk-storage") pod "f4b7fbce-4300-11e6-a11a-005056a5d06d" (UID: "f4b7fbce-4300-11e6-a11a-005056a5d06d") with: Unmount failed: exit status 1
Unmounting arguments: /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/test3
Output: umount: /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/test3: not found

Let me know if anyone is already fixing this issue otherwise I will work on it.

### PR DESCRIPTION
**Pull request by abrarshivani**
This PR does the following,
- Fixes #28625 (VSphere Volume doesn't unmount): modified vmdk namespace path parsing so it accurately handles VMs in folders. See file pkg/volume/vsphere_volume/vsphere_volume.go.
- Updates vmware/govmomi dependency. It was quite behind. The majority of files in the change are in this category.
- Adds support for VSAN datastore. Handle namespace to uuid mapping to assist unmount and detach in VSAN case as well. See file pkg/cloudprovider/providers/vsphere/vsphere.go.

Tested:
    - Created a K8s cluster on VSphere with VSAN datastore. Created a vmdk in VSAN datastore and created pod which uses this vmdk. Before fix (VSphere Volume doesn't unmount) it failed. After fix the volume gets successfully unmounted and detached.
    - Created a K8s cluster on VSphere with VMFS datastore. Created a vmdk in subdirectory of root in VMFS datastore and created pod which uses this vmdk. Before fix (VSphere Volume doesn't unmount) it failed.  After fix the volume gets successfully unmounted and detached.

### CODE REVIEW

**Comment by frapposelli** [comment]
Ping @googlebot as I've just added @abrarshivani in the vmware contributors group.

**Comment by abrarshivani** [comment]
ping @googlebot

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 1]
```diff
@@ -667,22 +668,58 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
+func formatVirtualDiskUUID(uuid string) string {
+
+	uuidwithNoSpace := strings.Replace(uuid, " ", "", -1)
+	uuidWithNoHypens := strings.Replace(uuidwithNoSpace, "-", "", -1)
+	uuid = strings.ToLower(uuidWithNoHypens)
+
+	return uuid
+}
+
+//Gets virtual disk uuid by datastore path. Here, datastore path can be both containing vsan object name or uuid.
```
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: whats a vsan object name, is it a datastore vmdk path? does this mean volPath argument can be a uuid as well?

**Comment by abrarshivani** [comment]
//cc @dagnello @imkin

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 1 above)
Comment (abrarshivani) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Good catch @abhitap.  I will adjust the comments to this:

```
// Gets virtual disk uuid by datastore (namespace) path
//
// volPath can be namespace path (e.g. "[vsanDatastore] volumes/test.vmdk") or 
// uuid path (e.g. "[vsanDatastore] 59427457-6c5a-a917-7997-0200103eedbc/test.vmdk").
// `volumes` in this case would be a symlink to 
// `59427457-6c5a-a917-7997-0200103eedbc`.  
//
// We want users to use namespace path. It is good for attaching the disk, 
// but for detaching the API requires uuid path.  Hence, to detach the right 
// device we have to convert the namespace path to uuid path. 
```

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 2]
```diff
@@ -667,22 +668,67 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
-		return strings.ToLower(uuidWithNoHypens), nil
+		uuid := formatVirtualDiskUUID(b.Uuid)
+		return uuid, nil
 	}
 	return "", ErrNoDiskUUIDFound
 }
 
-func getVirtualDiskID(volPath string, vmDevices object.VirtualDeviceList) (string, error) {
+func formatVirtualDiskUUID(uuid string) string {
+
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: spurious newline

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 3]
```diff
@@ -667,22 +668,67 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
+	uuidwithNoSpace := strings.Replace(uuid, " ", "", -1)
+	uuidWithNoHypens := strings.Replace(uuidwithNoSpace, "-", "", -1)
+	uuid = strings.ToLower(uuidWithNoHypens)
+
+	return uuid
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: nit, you could just return the result of `strings.ToLower`, but the compiler will probably be smart enough to optimize your code to that.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 4]
```diff
@@ -667,22 +668,67 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
+// volPath can be namespace path (e.g. "[vsanDatastore] volumes/test.vmdk") or
+// uuid path (e.g. "[vsanDatastore] 59427457-6c5a-a917-7997-0200103eedbc/test.vmdk").
+// `volumes` in this case would be a symlink to
+// `59427457-6c5a-a917-7997-0200103eedbc`.
+//
+// We want users to use namespace path. It is good for attaching the disk,
+// but for detaching the API requires uuid path.  Hence, to detach the right
+// device we have to convert the namespace path to uuid path.
+func getVirtualDiskUUIDByPath(volPath string, dc *object.Datacenter, client *govmomi.Client) (string, error) {
+
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: spurious newline

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 2 above)
Comment (abrarshivani) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Thanks for the comments! The newline is not needed.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 4 above)
Comment (abrarshivani) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Thanks for the comments! The newline is not needed.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 5]
```diff
@@ -667,22 +668,63 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
+		return "", ErrNoDiskUUIDFound
+	}
+
+	diskUUID = formatVirtualDiskUUID(diskUUID)
+
+	return diskUUID, nil
+}
+
+func getVirtualDiskID(volPath string, vmDevices object.VirtualDeviceList, dc *object.Datacenter, client *govmomi.Client) (string, error) {
+
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: spurious newline

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 6]
```diff
@@ -667,22 +668,63 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
+	if err != nil {
+		return "", ErrNoDiskUUIDFound
+	}
+
+	diskUUID = formatVirtualDiskUUID(diskUUID)
+
+	return diskUUID, nil
+}
+
+func getVirtualDiskID(volPath string, vmDevices object.VirtualDeviceList, dc *object.Datacenter, client *govmomi.Client) (string, error) {
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Godoc?  In general I think it's a good idea for this type of method, which deals with things that are not obvious to someone who knows the kube code but not the vsphere API, to get godoc so that people doing refactors understand the significance of the method.

File: pkg/volume/vsphere_volume/vsphere_volume.go [hunk 7]
```diff
@@ -292,11 +292,13 @@ func (v *vsphereVolumeUnmounter) TearDownAt(dir string) error {
 		return fmt.Errorf("directory %s is not mounted", dir)
 	}
 
+	mountPath := refs[0]
+	//Assumption: No file or folder is named starting with '[' in datastore
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: Nit, add a space after `//`.  Also, +1 to documenting assumptions like this.

**Comment by pmorie** [comment]
Just a couple nits and this LGTM.  Does it need a release note?  It sounds to me like it might be worthy of release note, but I'm not certain.

**Comment by abrarshivani** [comment]
@pmorie This PR needs release note.

**Comment by pmorie** [comment]
@k8s-bot ok to test
