### PR TITLE
Respect PodTopologySpread after rolling upgrades

### LINKED ISSUE #98215: Rolling updates interfere with Pod Topology Spread Constraints
**Background**:
We define Pod Topology Spread Constraints on our Deployment (labeled `app: app1`), as follows:
>       topologySpreadConstraints:
>       - maxSkew: 1
>         topologyKey: kubernetes.io/hostname
>         whenUnsatisfiable: DoNotSchedule
>         labelSelector:
>           matchLabels:
>             app: app1

The deployment is defined with 5 replicas.

**What happened**:
Triggering a rolling update on the running deployment will sometimes result in a skewed spread, not honoring the maxSkew=1.
Our theory is that the scheduler "sees" the old pods when deciding how to spread the new pods over nodes. When the old nodes are eventually terminated, we sometimes see three pods in node-1, two pods in node-2 and none in node-3.

**What you expected to happen**:
The maxSkew value in Pod Topology Spread Constraints should always be honored.

**How to reproduce it (as minimally and precisely as possible)**:
It reproduces randomly, so it takes a few attempts until reproduced.
I'm running `kubectl rollout restart deployment <deployment-name>` a few times until it reproduces.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.7
- Cloud provider or hardware configuration: self deployed cluster with kubeadm on on-premises VMs (vmware)
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.6.1.el7.x86_64
- Other: cluster consists of 3 master nodes which also act as workers

### LINKED ISSUE #105661: Topology spreading can become imbalanced during deployment rollout
### What happened?

When restarting a rolling deployment, the new pods can end up in imbalanced topologies that violate their specified `MaxSkew`. This is due to interference from the old, `Terminating` pods in the scheduler's topology size calculation. At scheduling time, the constraints are technically satisfied. However, once the old pods are removed, the topology size difference can be greater than `MaxSkew`

/sig scheduling

### What did you expect to happen?

Topology spread constraints should be valid during and after a deployment rollout

### How can we reproduce it (as minimally and precisely as possible)?

Create a Kind cluster with the following config for 2 worker nodes:
```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "topology.kubernetes.io/zone=A"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "topology.kubernetes.io/zone=B"
```

Next, create a sample deployment to take up some cluster utilization (this may not be necessary)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fat
  name: fat
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      app: fat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fat
    spec:
      nodeSelector:
        kubernetes.io/hostname: "kind-worker2"
      containers:
        - command:
            - sh
            - -c
            - "trap : TERM INT; sleep 9999999999d & wait"
          image: alpine
          imagePullPolicy: Always
          name: alpine
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

Finally, create the required deployment with topology spread constraints:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: required
  name: required
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: required
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: required
    spec:
      containers:
        - command:
            - sh
            - -c
            - "trap : TERM INT; sleep 9999999999d & wait"
          image: alpine
          imagePullPolicy: Always
          name: alpine
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: required
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
```

Once all pods are running, the required pods should initially be spread on different nodes:
```
$ kubectl get po -o wide
required-7d47b8d88b-kxqnv   1/1     Running   0          3s      10.244.1.25   kind-worker2   <none>           <none>
required-7d47b8d88b-wd5k5   1/1     Running   0          3s      10.244.2.5    kind-worker    <none>           <none>
```

However, restarting the deployment causes them to end up unbalanced:
```
$ kubectl rollout restart deployment.apps/required
deployment.apps/required restarted

$ kubectl get po -o wide
required-784d4c6d48-p8jnj   1/1     Running   0          43s   10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running   0          45s   10.244.2.3    kind-worker    <none>           <none>
```

By checking the pods during the rollout, you can see they are scheduled in accordance with the topology constraints to include Terminating nodes into the calculation. For example:
```
$ kubectl get po -o wide
required-595b4ddfc-8hpmz    1/1     Running             0          46s   10.244.1.22   kind-worker2   <none>           <none>
required-595b4ddfc-bh2tf    1/1     Terminating         0          46s   10.244.2.2    kind-worker    <none>           <none>
required-784d4c6d48-p8jnj   0/1     ContainerCreating   0          1s    <none>        kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running             0          3s    10.244.2.3    kind-worker    <none>           <none>

$ kubectl get po -o wide
required-595b4ddfc-8hpmz    0/1     Terminating   0          50s   10.244.1.22   kind-worker2   <none>           <none>
required-784d4c6d48-p8jnj   1/1     Running       0          5s    10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running       0          7s    10.244.2.3    kind-worker    <none>           <none>

$ kubectl get po -o wide
required-784d4c6d48-p8jnj   1/1     Running   0          43s   10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running   0          45s   10.244.2.3    kind-worker    <none>           <none>
```

This leads to the imbalanced cluster state.

### Anything else we need to know?

This may be intentional, and there are existing solutions for this issue. For example, the [Descheduler](https://github.com/kubernetes-sigs/descheduler#removepodsviolatingtopologyspreadconstraint) can be run to re-balance the domains.

Alternatively, a soft pod anti-affinity can be added to help steer pods away from each other. This is not a guarantee though.

### Kubernetes version

<details>

Reproduced as far back as 1.19

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by denkensk**
#### What type of PR is this?

/kind feature
/kind api-change

#### What this PR does / why we need it:
PodTopologySpread is widely used in production environments, especially in service type workloads which employ Deployments. However, currently it has a limitation that manifests during rolling updates which causes the deployment to end up out of balance ([98215](https://github.com/kubernetes/kubernetes/issues/98215), [105661](https://github.com/kubernetes/kubernetes/issues/105661),[k8s-pod-topology spread is not respected after rollout](https://stackoverflow.com/questions/66510883/k8s-pod-topology-spread-is-not-respected-after-rollout)). 

The root cause is that PodTopologySpread constraints allow defining a key-value label selector, which applies to all pods in a Deployment irrespective of their owning ReplicaSet. As a result, when a new revision is rolled out, spreading will apply across pods from both the old and new ReplicaSets, and so by the time the new ReplicaSet is completely rolled out and the old one is rolled back, the actual spreading we are left with may not match expectations because the deleted pods from the older ReplicaSet will cause skewed distribution for the remaining pods.

#### Which issue(s) this PR fixes:

Fixes #98215
Fixes #105661

#### Does this PR introduce a user-facing change?

```release-note
Respect PodTopologySpread after rolling upgrades
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- [KEP]: https://github.com/kubernetes/enhancements/issues/3243)

### CODE REVIEW

**Comment by ahg-g** [comment]
We need to split this into api and implementation commits or separate PRs. It will be hard to review like this.

**Comment by denkensk** [comment]
> We need to split this into api and implementation commits or separate PRs. It will be hard to review like this.

@ahg-g  Give me some minutes. I will split this into api and implementation commits

**Comment by denkensk** [comment]
> > We need to split this into api and implementation commits or separate PRs. It will be hard to review like this.
> 
> @ahg-g Give me some minutes. I will split this into api and implementation commits

Done

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go [hunk 1]
```diff
@@ -87,14 +87,26 @@ func nodeLabelsMatchSpreadConstraints(nodeLabels map[string]string, constraints
 	return true
 }
 
-func filterTopologySpreadConstraints(constraints []v1.TopologySpreadConstraint, action v1.UnsatisfiableConstraintAction, enableMinDomainsInPodTopologySpread, enableNodeInclusionPolicyInPodTopologySpread bool) ([]topologySpreadConstraint, error) {
+func filterTopologySpreadConstraints(constraints []v1.TopologySpreadConstraint, podLabels map[string]string, action v1.UnsatisfiableConstraintAction, enableMinDomainsInPodTopologySpread, enableNodeInclusionPolicyInPodTopologySpread bool, enableMatchLabelKeysInPodTopologySpread bool) ([]topologySpreadConstraint, error) {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/podtopologyspread/common.go:90]: can we just make the function a member of PodTopologySpread instead of passing all those flags? I worry we will mix them up since they are a list of back-to-back boolean parameters

**Review by ahg-g — COMMENTED** [review]
quick few comments on the api, will continue to review the implementation

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go [hunk 2]
```diff
@@ -1180,6 +1181,162 @@ func TestPreFilterState(t *testing.T) {
...
+				st.MakePod().Name("p-b1").Node("node-b").Label("foo", "").Obj(),
+				st.MakePod().Name("p-y1").Node("node-y").Label("foo", "").Label("bar", "").Obj(),
+				st.MakePod().Name("p-y2").Node("node-y").Label("bar", "").Obj(),
+			},
+			want: &preFilterState{
+				Constraints: []topologySpreadConstraint{
+					{
+						MaxSkew:            1,
+						TopologyKey:        "zone",
+						Selector:           mergeLabelSetWithSelector(labels.Set{"bar": ""}, mustConvertLabelSelectorAsSelector(t, fooSelector)),
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1246]: using `mergeLabelSetWithSelector` here is not correct, basically we are using the same function that we are trying to test :)

we should have an explicitly created selector here with the expected semantics

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go [hunk 3]
```diff
@@ -55,8 +55,8 @@ func TestPreScoreStateEmptyNodes(t *testing.T) {
 		{
 			name: "normal case",
 			pod: st.MakePod().Name("p").Label("foo", "").
-				SpreadConstraint(1, "zone", v1.ScheduleAnyway, fooSelector, nil, nil, nil).
-				SpreadConstraint(1, v1.LabelHostname, v1.ScheduleAnyway, fooSelector, nil, nil, nil).
+				SpreadConstraint(1, "zone", v1.ScheduleAnyway, fooSelector, nil, nil, nil, nil).
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go:58]: can we add some tests for scoring?

File: test/integration/scheduler/filters/filters_test.go [hunk 4]
```diff
@@ -1430,11 +1435,57 @@ func TestPodTopologySpreadFilter(t *testing.T) {
...
+			existingPods: []*v1.Pod{
+				st.MakePod().Name("p1a").Node("node-0").Label("foo", "").Container(pause).Obj(),
+				st.MakePod().Name("p2a").Node("node-1").Label("foo", "").Container(pause).Obj(),
+				st.MakePod().Name("p3a").Node("node-2").Label("foo", "").Container(pause).Obj(),
+			},
+			fits:                 true,
+			nodes:                defaultNodes,
+			candidateNodes:       []string{"node-2", "node-3"},
+			enableMatchLabelKeys: true,
+		},
```
Comment (chendave) [inline test/integration/scheduler/filters/filters_test.go:1482]: Add one test here which proves that `matchLabelKeys` is ignored when if it's doesn't exist in the pod's labels.

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go [hunk 5]
```diff
@@ -120,6 +132,22 @@ func filterTopologySpreadConstraints(constraints []v1.TopologySpreadConstraint,
 	return result, nil
 }
 
+func mergeLabelSetWithSelector(matchLabels labels.Set, s labels.Selector) labels.Selector {
+	matchLabelSelector := labels.SelectorFromSet(matchLabels)
```
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go:136]: I guess it matches everything. It's consistent with the document.
```
Keys that don't exist in the incoming pod labels will be ignored.
```

[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go:136]: Better to document this in the case of empty MatchLabelKeys.

File: pkg/apis/core/types.go [hunk 6]
```diff
@@ -5732,6 +5732,14 @@ type TopologySpreadConstraint struct {
...
 	// +optional
 	NodeTaintsPolicy *NodeInclusionPolicy
+	// MatchLabelKeys is a set of pod label keys to select the pods over which
+	// spreading will be calculated. The keys are used to lookup values from the
+	// incoming pod labels, those key-value labels are ANDed with `LabelSelector`
+	// to select the group of existing pods over which spreading will be calculated
+	// for the incoming pod. Keys that don't exist in the incoming pod labels will
+	// be ignored.
+	// +optional
+	MatchLabelKeys []string
```
Comment (kerthcet) [inline pkg/apis/core/types.go:5742]: Since the rolling update not working as expected, shouldn't we add some keys like `pod-template-hash` as default values. Yes it will change the current behavior, but considering we are recreating pods, it's actually what end-users wants.

Comment (denkensk) [reply pkg/apis/core/types.go:5742]: Can be considered in a later version maybe beta.

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go [hunk 7]
```diff
@@ -1180,6 +1182,162 @@ func TestPreFilterState(t *testing.T) {
...
+				st.MakePod().Name("p-b1").Node("node-b").Label("foo", "").Obj(),
+				st.MakePod().Name("p-y1").Node("node-y").Label("foo", "").Obj(),
+				st.MakePod().Name("p-y2").Node("node-y").Label("foo", "").Obj(),
+			},
+			want: &preFilterState{
+				Constraints: []topologySpreadConstraint{
+					{
+						MaxSkew:            1,
+						TopologyKey:        "zone",
+						Selector:           mustConvertLabelSelectorAsSelector(t, st.MakeLabelSelector().In("foo", []string{"b"}).Label("foo", "a").Obj()),
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: what does that mean? what exactly is the constraint? `foo in {b, a}`?

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go:137]: I thinks it should like this:
1. If matchLabels is empty. It match all. So we won't need to AND with selector. Just keep it unchanged.
2. If matchLabels isn't empty, the list and the selector are being ANDed. The Pod needs to match matchLabels and selector at the same time.

File: test/integration/scheduler/filters/filters_test.go (hunk 4 above)
Comment (denkensk) [reply test/integration/scheduler/filters/filters_test.go:1482]: Done

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go (hunk 3 above)
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go:58]: Added

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go (hunk 1 above)
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go]: Done make it as the member function

File: pkg/apis/core/types.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/apis/core/types.go:5742]: Done

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go (hunk 7 above)
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: It means like user set the same key in Selector and MatchLabelKeys at the same time. But the value in Selector isn't as the value get for pod.labels. Like this 
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    foo: a  ---> foo=a
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchExpressions:   --> foo in {b}
      - key: foo
        operator: In
        values:
        - b
    matchLabelKeys:
    - foo   --> foo
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
```
If like this no pod will match this conditions.

Comment (ahg-g) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: I meant how will that translate as a selector? two contradicting requirements?

Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: Yes. Selector will be translated as two contradicting requirements for this case.

like this ---->   foo in {b}; foo=a

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go [hunk 8]
```diff
@@ -134,18 +135,14 @@ func filterTopologySpreadConstraints(constraints []v1.TopologySpreadConstraint,
...
-	if s == nil || s.Empty() {
-		s = matchLabelSelector
-	} else {
-		requirements, ok := matchLabelSelector.Requirements()
-		if ok {
-			for _, r := range requirements {
-				s = s.Add(r)
-			}
+	requirements, ok := s.Requirements()
+	if ok {
```
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go]: Done

File: pkg/apis/core/types.go [hunk 9]
```diff
@@ -5732,6 +5732,14 @@ type TopologySpreadConstraint struct {
 	// This is a alpha-level feature enabled by the NodeInclusionPolicyInPodTopologySpread feature flag.
 	// +optional
 	NodeTaintsPolicy *NodeInclusionPolicy
+	// MatchLabelKeys is a set of pod label keys to select the pods over which
+	// spreading will be calculated. The keys are used to lookup values from the
+	// incoming pod labels, those key-value labels are ANDed with `LabelSelector`
+	// to select the group of existing pods over which spreading will be calculated
+	// for the incoming pod. Keys that don't exist in the incoming pod labels will
+	// be ignored.
```
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/apis/core/types.go]: Done

File: pkg/api/pod/util.go [hunk 10]
```diff
@@ -626,6 +627,33 @@ func dropDisabledNodeInclusionPolicyFields(podSpec, oldPodSpec *api.PodSpec) {
 	}
 }
 
+// dropDisableMatchLabelKeysField removes disabled fields from PodSpec related
+// to MatchLabelKeys only if it is not already used by the old spec.
+func dropDisableMatchLabelKeysField(podSpec, oldPodSpec *api.PodSpec) {
```
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/api/pod/util.go]: Done

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go (hunk 7 above)
Comment (denkensk) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: It's awkward, but users may indeed write as such by mistake, so add a UT to simulate

File: pkg/apis/core/types.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/apis/core/types.go:5742]: We probably better validate that a key in matchLabelKeys don't exist in labelSelector. It doesn't seem like there is a use case for it, so better block it.

File: pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go (hunk 7 above)
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go:1364]: As mentioned on the validation comment, lets just validate that keys are not shared between matchLabelKeys and labelSelector

File: pkg/apis/core/types.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/apis/core/types.go:5742]: I feel that this is too strict and lacks flexibility. Maybe like labelSelector, it will also may be contradicted with the use of the same key in both labelSelector and matchExpressions. But we don't block it? right? 
```go
kind: Pod
apiVersion: v1
metadata:
  name: mypod
  labels:
    foo: a  
spec:
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels: ---> foo = a
        foo: a
      matchExpressions:   --> foo in {b}
      - key: foo
        operator: In
        values:
        - b
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
```
The keys in matchLabelKeys and labelSelector do not necessarily contradict each other. Maybe just some cases.

Comment (kerthcet) [reply pkg/apis/core/types.go:5742]: Then from a different perspective, we may treat this as providing a configurable way for end-users to prevent the unexpected results without breaking current behaviors. (Still weird for I would like to treat this as a bug.)

Besides, IIRC, we'll meet this problem the same with podAffinity/podAntiAffinity, that's part of the reason why descheduler incubated. right? If so, we should look for a mechanism cover these scenarios consistently, about distinguishing between current and rolling-out versions. This is somehow outside the scope of scheduling, but related.

File: pkg/scheduler/framework/plugins/podtopologyspread/common.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/plugins/podtopologyspread/common.go]: Exactly what I think.

File: pkg/apis/core/types.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/apis/core/types.go:5742]: But lacks flexibility to do what? What is the use case? The example you gave above translates to a selector that matches nothing, which probably isn't what the user intended to do.

File: pkg/apis/core/validation/validation_test.go [hunk 11]
```diff
@@ -19033,6 +19034,18 @@ func TestValidateTopologySpreadConstraints(t *testing.T) {
...
+			name: "key in MatchLabelKeys isn't correctly defined.",
+			constraints: []core.TopologySpreadConstraint{
+				{
+					MaxSkew:           1,
+					TopologyKey:       "k8s.io/zone",
+					WhenUnsatisfiable: core.DoNotSchedule,
+					MatchLabelKeys:    []string{"/simple"},
+				},
+			},
+			wantFieldErrors: []*field.Error{field.Invalid(fieldPathMatchLabelKeys, "/simple", "prefix part must be non-empty")},
```
Comment (chendave) [inline pkg/apis/core/validation/validation_test.go:19047]: `prefix part must be non-empty` this error msg is hard to understand at the first glance until I checked the source which split the string by '/'. 

you may want to add another test string, such as an empty string, I am fine with this as is though.

File: pkg/features/kube_features.go [hunk 12]
```diff
@@ -515,6 +515,13 @@ const (
 	// Enables scaling down replicas via logarithmic comparison of creation/ready timestamps
 	LogarithmicScaleDown featuregate.Feature = "LogarithmicScaleDown"
 
+	// owner: @denkensk
+	// kep: http://kep.k8s.io/3243
+	// alpha: v1.25
+	//
+	// Enable MatchLabelKeys in Pod Topology Spread.
```
Comment (chendave) [inline pkg/features/kube_features.go:522]: pls use the plugin name "PodTopologySpread" instead of "Pod Topology Spread"

File: pkg/apis/core/types.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/apis/core/types.go:5742]: Yes. You are right. This case is not the user intend to do. 
I added the validation for this.

File: pkg/api/pod/util.go [hunk 13]
```diff
@@ -626,6 +627,33 @@ func dropDisabledNodeInclusionPolicyFields(podSpec, oldPodSpec *api.PodSpec) {
 	}
 }
 
+// dropDisabledMatchLabelKeysField removes disabled fields from PodSpec related
+// to MatchLabelKeys only if it is not already used by the old spec.
+func dropDisabledMatchLabelKeysField(podSpec, oldPodSpec *api.PodSpec) {
+	if !utilfeature.DefaultFeatureGate.Enabled(features.MatchLabelKeysInPodTopologySpread) && podSpec != nil {
```
[the remark this answers is not in the document]
Comment (denkensk) [reply pkg/api/pod/util.go]: Done

**Comment by ahg-g** [comment]
looks good to me 

@liggitt this is ready.

File: api/api-rules/violation_exceptions.list [hunk 14]
```diff
@@ -161,6 +161,7 @@ API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceSpec,ExternalIPs
 API rule violation: list_type_missing,k8s.io/api/core/v1,ServiceSpec,LoadBalancerSourceRanges
 API rule violation: list_type_missing,k8s.io/api/core/v1,TopologySelectorLabelRequirement,Values
 API rule violation: list_type_missing,k8s.io/api/core/v1,TopologySelectorTerm,MatchLabelExpressions
+API rule violation: list_type_missing,k8s.io/api/core/v1,TopologySpreadConstraint,MatchLabelKeys
```
Comment (liggitt) [inline api/api-rules/violation_exceptions.list:164]: Please define a list type for the new field, to avoid adding new lint exceptions. If you expect a single actor to control the whole list, then `+listType=atomic` seems most appropriate for this field.

File: pkg/apis/core/types.go [hunk 15]
```diff
@@ -5732,6 +5732,14 @@ type TopologySpreadConstraint struct {
 	// This is a alpha-level feature enabled by the NodeInclusionPolicyInPodTopologySpread feature flag.
 	// +optional
 	NodeTaintsPolicy *NodeInclusionPolicy
+	// MatchLabelKeys is a set of pod label keys to select the pods over which
+	// spreading will be calculated. The keys are used to lookup values from the
+	// incoming pod labels, those key-value labels are ANDed with `LabelSelector`
```
Comment (liggitt) [inline pkg/apis/core/types.go:5737]: nit: use the serialized name of the fields in docs, e.g. `labelSelector`

File: pkg/apis/core/validation/validation.go [hunk 16]
```diff
@@ -6490,6 +6490,7 @@ func validateTopologySpreadConstraints(constraints []core.TopologySpreadConstrai
 		if err := validateNodeInclusionPolicy(subFldPath.Child("nodeTaintsPolicy"), constraint.NodeTaintsPolicy); err != nil {
 			allErrs = append(allErrs, err)
 		}
+		allErrs = append(allErrs, validateMatchLabelKeys(subFldPath.Child("matchLabelKeys"), constraint.MatchLabelKeys, constraint.LabelSelector)...)
 	}
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:6494]: pre-existing, but I noticed validateTopologySpreadConstraints doesn't seem to validate constraint.LabelSelector at all... @ahg-g, can you open a separate issue to track that (need to make sure the scheduler is robust against completely invalid selectors, and consider how to fix this validation in the least disruptive way possible)

File: pkg/apis/core/validation/validation.go [hunk 17]
```diff
@@ -6563,6 +6564,33 @@ func validateNodeInclusionPolicy(fldPath *field.Path, policy *core.NodeInclusion
...
+			labelSelectorKeys.Insert(key)
+		}
+		for _, matchExpression := range labelSelector.MatchExpressions {
+			labelSelectorKeys.Insert(matchExpression.Key)
+		}
+	}
+
+	allErrs := field.ErrorList{}
+	for _, key := range matchLabelKeys {
+		allErrs = append(allErrs, unversionedvalidation.ValidateLabelName(key, fldPath)...)
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:6585]:
```suggestion
	for i, key := range matchLabelKeys {
		allErrs = append(allErrs, unversionedvalidation.ValidateLabelName(key, fldPath.Index(i))...)
```

File: pkg/apis/core/validation/validation.go [hunk 18]
```diff
@@ -6563,6 +6564,33 @@ func validateNodeInclusionPolicy(fldPath *field.Path, policy *core.NodeInclusion
...
+		if labelSelectorKeys.Has(key) {
+			allErrs = append(allErrs, field.Invalid(fldPath, key, "exists in both matchLabelKeys and labelSelector"))
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:6587]:
```suggestion
			allErrs = append(allErrs, field.Invalid(fldPath.Index(i), key, "exists in both matchLabelKeys and labelSelector"))
```

File: pkg/apis/core/validation/validation.go [hunk 19]
```diff
@@ -6563,6 +6564,33 @@ func validateNodeInclusionPolicy(fldPath *field.Path, policy *core.NodeInclusion
 	return nil
 }
 
+// validateMatchLabelKeys tests that the elements are a valid label name.
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:6567]:
```suggestion
// validateMatchLabelKeys tests that the elements are a valid label name and are not already included in labelSelector.
```

**Review by liggitt — COMMENTED** [review]
API bits look good, just a few doc/lint/message nits

I didn't review the pkg/scheduler and test changes, will defer to scheduling reviewers/approvers for those changes

File: pkg/apis/core/types.go (hunk 15 above)
Comment (denkensk) [reply pkg/apis/core/types.go]: Done

File: api/api-rules/violation_exceptions.list (hunk 14 above)
Comment (denkensk) [reply api/api-rules/violation_exceptions.list]: updated

**Comment by liggitt** [comment]
/approve
API change lgtm

/hold looks like commits need squashing
will let @ahg-g lgtm once that is done

**Comment by sftim** [comment]
@denkensk, could we also link to the relevant docs?

See https://github.com/kubernetes/kubernetes/pull/111194 for an example of a detailed release note that includes a link to docs.

File: pkg/apis/core/validation/validation.go (hunk 16 above)
Comment (chendave) [reply pkg/apis/core/validation/validation.go:6494]: Some update on this comments, the validation is actually done when the `labels.Selector` is built. e.g. 
https://github.com/kubernetes/kubernetes/blob/891cbede96ab4b64c48edf25f8bbd331d8731622/pkg/scheduler/framework/plugins/podtopologyspread/common.go#L94

And it is validated here, 
https://github.com/kubernetes/kubernetes/blob/891cbede96ab4b64c48edf25f8bbd331d8731622/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L191-L194

I think the original comment is still valid and the the validation mentioned above would mitigate the problem as the invalid label value won't be accepted at all.

Comment (liggitt) [reply pkg/apis/core/validation/validation.go:6494]: that happens at time of use, not time of API write, which is not ideal (since the user has no idea the object they created is not working like they want it to)

Comment (chendave) [reply pkg/apis/core/validation/validation.go:6494]: pr sent: https://github.com/kubernetes/kubernetes/pull/112121
