### PR TITLE
Fix fake event recorder race

### LINKED ISSUE #26578: unittest flake: TestControllerSync Warning ClaimLost Bound claim has lost its PV
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26335/kubernetes-pull-test-unit-integration/28566/artifacts/
```
--- FAIL: TestControllerSync (0.13s)
	framework_test.go:395: Unexpected event received: "Warning ClaimLost Bound claim has lost its PersistentVolume. Data on the volume is lost!"
	framework_test.go:739: Test "5-4 - delete volume": Events do not match
```
@kubernetes/sig-storage @jsafrane please close if it's fixed by https://github.com/kubernetes/kubernetes/pull/26555

### PR DESCRIPTION
**Pull request by jsafrane**
Event recorder should wait for some time to get all expected events, the event may be written by another goroutine that just have finished.

It should not slow down the test in most cases, only when there is a bug and expected event is not sent.

Fixes #26578 

Using P2 to speed up merge and to prevent further flakes.

@kubernetes/sig-storage

### CODE REVIEW

File: pkg/controller/persistentvolume/framework_test.go [hunk 1]
```diff
@@ -372,8 +375,8 @@ func checkEvents(t *testing.T, expectedEvents []string, ctrl *PersistentVolumeCo
 				glog.V(5).Infof("event recorder finished")
 				finished = true
```
Comment (jingxu97) [inline pkg/controller/persistentvolume/framework_test.go]: The entering for loop condition is &, so what is the difference between the old version and new one if the path comes to this point? After finished is set true at this line, it will quit waiting, I think.

Comment (jsafrane) [inline pkg/controller/persistentvolume/framework_test.go]: yes, when `finished` is `true` the loop exits. But `finished` is set at different condition now.

Before it was set when there was no event in channel. This has proven to be racy, I got the controller waiting for CPU to send an event and the event was missed in this loop. Now we wait 1 minute and only after that `finished` is set.

Of course, when sender closes the channel, `finished` is set immediately in both cases.
