### PR TITLE
GCE provider: Limit Filter calls to regexps rather than large blobs

### LINKED ISSUE #27731: Can't create LoadBalancer on medium->large GCE clusters
Customer impact: Attempts to create services with type `LoadBalancer` will never get an external IP or any GCE object created on all clusters >=124 nodes (with variably cutoffs starting even at 72 nodes, depending on the cluster name). I believe, but haven't tested, that L7LB will fail to create firewalls on these size clusters as well (based on code inspection).

Analysis: There's an issue in https://github.com/kubernetes/kubernetes/blob/090e6ff660d82120c17f10fe63d9f8a1c1aa23b3/pkg/cloudprovider/providers/gce/gce.go#L2430 where, depending on the name of the cluster, if you attempt to call the function with x > ~100 nodes (roughly, it depends on the cluster name), the GCE API will reject you because the `Filter()` parameter is too large.

At some larger cluster sizes, the API endpoint just outright rejects the `GET` request completely, versus clearly indicating the `Filter()` is wrong.

This is a problem in all 1.2.x and forward.

I have a PR incoming for base k8s, then we'll probably need to rev L7LB as well.

### PR DESCRIPTION
**Pull request by zmerlynn**
Filters can't exceed 4k, and GET requests against the GCE API are also limited, so these break down in different ways at different cluster counts. Fix it by introducing an advisory `node-instance-prefix` configuration in the GCE provider that can hint the `EnsureLoadBalancer`/`UpdateLoadBalancer code` (and the firewall creation/update code). If it's not there, or wrong (a hostname that's registered violates it), just ignore it and grab the whole project.

Fixes #27731 
[Analytics]()

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @roberthbailey: This needs a v1.2 cherrypick as well, once we get it in `master`.

**Comment by zmerlynn** [comment]
After testing this on a 1000 node cluster, I found another nasty surprise lurking in the same APIs, so I pushed a new iteration that killed the `Field()` limiters after filing an internal bug.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -2467,6 +2492,13 @@ func (gce *GCECloud) getInstancesByNames(names []string) ([]*gceInstance, error)
 			pageToken = res.NextPageToken
 			for _, i := range res.Items {
 				name := i.Name
+				if inst, ok := instances[name]; !ok || inst != nil {
+					if inst != nil {
+						glog.Warningf("GCE returned duplicate result for instance %q", name)
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce.go]: Can this really happen? It seems to me a bit paranoid.

**Comment by wojtek-t** [comment]
I added a minor comment. Other than that LGTM.
Feel free to self-apply label.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 1 above)
Comment (zmerlynn) [inline pkg/cloudprovider/providers/gce/gce.go]: I added it when was debugging that internal bug. I was thinking there was instability across pages (I.e. with the wrong options it returned `a,b,c` then `c,d,f`) in some race condition, which would then show up as a missing instance a few lines below (so the idea is that the pair of lines would show the instability). That ended up not being the case, but it doesn't seem harmful to leave in.

Comment (zmerlynn) [inline pkg/cloudprovider/providers/gce/gce.go]: I went ahead and took it out. If the other case ever comes up, hopefully it'll be obvious (or non-harmful, e.g. duplicate results but all the results).

File: pkg/cloudprovider/providers/gce/gce.go [hunk 2]
```diff
@@ -281,19 +284,20 @@ func newGCECloud(config io.Reader) (*GCECloud, error) {
...
 	}
 
-	return CreateGCECloud(projectID, region, zone, managedZones, networkURL, nodeTags, tokenSource, true /* useMetadataServer */)
+	return CreateGCECloud(projectID, region, zone, managedZones, networkURL, nodeTags, nodeInstancePrefix, tokenSource, true /* useMetadataServer */)
 }
 
 // Creates a GCECloud object using the specified parameters.
 // If no networkUrl is specified, loads networkName via rest call.
 // If no tokenSource is specified, uses oauth2.DefaultTokenSource.
 // If managedZones is nil / empty all zones in the region will be managed.
```
Comment (bprashanth) [inline pkg/cloudprovider/providers/gce/gce.go]: can you add a comment describing the exact use of nodeInstancePrefix and impact of passing in an empty string?

Comment (zmerlynn) [inline pkg/cloudprovider/providers/gce/gce.go]: Didn't see this before it merged. To clarify it here (and I'll have a PR later): It's an advisory prefix to help GCE searches for nodes in the cluster. If nodes happen to join that violate the `nodeInstancePrefix`, the `nodeInstancePrefix` is ignored and the entire GCE project is enumerated.

Comment (zmerlynn) [inline pkg/cloudprovider/providers/gce/gce.go]: Oh, and if it's empty, we enumerate the whole project.
