### PR TITLE
kubelet: do not call RemoveAll on volumes directory for orphaned pods

### LINKED ISSUE #101911: NodeUnstageVolume not called because unmounter fails when vol_data.json is deleted
#### What happened:

The upcoming csi-driver-host-path release v1.7.0 will have a check in DeleteVolume that returns an error when the volume is still attached, staged, or published (https://github.com/kubernetes-csi/csi-driver-host-path/pull/260).

Some of the jobs in the csi-driver-host-path repo with Kubernetes 1.21.0 are failing because NodeUnstageVolume is not called, causing DeleteVolume to fail repeatedly until the test times out.

One example:

volume ID 3f3a132b-b25c-11eb-9aba-a6b5a7ade690 in:
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-host-path/289/pull-kubernetes-csi-csi-driver-host-path-1-21-test-on-kubernetes-1-21/1392103346201956352/artifacts/default/csi-hostpathplugin-0/hostpath.log

Corresponds to pvc-c0971c32-17c3-427f-a606-1bbf893caf89 in:
- https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_csi-driver-host-path/289/pull-kubernetes-csi-csi-driver-host-path-1-21-on-kubernetes-1-21/1392103346180984832/artifacts/cluster-logs/non-alpha/csi-prow-worker2/kubelet.log

There's one kubelet error that seems relevant:
```
May 11 13:30:23 csi-prow-worker2 kubelet[247]: E0511 13:30:23.786580     247 reconciler.go:193] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"test-volume\" (UniqueName: \"kubernetes.io/csi/hostpath.csi.k8s.io^ca29f6e4-b25c-11eb-8da9-1e598a3983d2\") pod \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\" (UID: \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\") : UnmountVolume.NewUnmounter failed for volume \"test-volume\" (UniqueName: \"kubernetes.io/csi/hostpath.csi.k8s.io^ca29f6e4-b25c-11eb-8da9-1e598a3983d2\") pod \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\" (UID: \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/vol_data.json]: open /var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"test-volume\" (UniqueName: \"kubernetes.io/csi/hostpath.csi.k8s.io^ca29f6e4-b25c-11eb-8da9-1e598a3983d2\") pod \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\" (UID: \"a6441c77-7c03-4d33-8a80-0a37d895f8a9\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/vol_data.json]: open /var/lib/kubelet/pods/a6441c77-7c03-4d33-8a80-0a37d895f8a9/volumes/kubernetes.io~csi/pvc-c0971c32-17c3-427f-a606-1bbf893caf89/vol_data.json: no such file or directory"
```

#### What you expected to happen:

NodeUnstageVolume should be called.

#### How to reproduce it (as minimally and precisely as possible):

`CSI_PROW_KUBERNETES_VERSION=1.21.0 CSI_PROW_TESTS=parallel CSI_SNAPSHOTTER_VERSION=v4.0.0 ./.prow.sh` in csi-driver-host-path and hope that it fails.

Alternatively, retest in https://github.com/kubernetes-csi/csi-driver-host-path/pull/289

#### Anything else we need to know?:

Random observation: in the two cases that I looked at, the affected volume was published twice for different pods.

### PR DESCRIPTION
**Pull request by dobsonj**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
See issue #101911 for the full story. It is possible in some situations for the volume of a terminating pod to be added back to the DSW after being removed, because pods are currently added and removed based on two different caches. As a result, the orphaned volume cleanup code can call RemoveAll on the pod dir, which deletes vol_data.json, and causes NodeUnstageVolume to fail when attempting to unmount the volume.

To avoid this issue, this PR instead uses `rmdir` on the volumes dir during orphaned volume cleanup which will fail if any files are left in the volumes directory. The other subpaths under the pod directory CAN have files that need to be removed during orphan cleanup, so those continue to use RemoveAll.

Here is an example pod directory that needs to be cleaned up:
```
/var/lib/kubelet/pods/de33b3cd-9542-4245-b20b-892204fa49f5:
containers  etc-hosts  plugins  volumes
```
This PR recursively calls `rmdir` on the volumes directory which will be successful only if there are no files or mounts left behind. Then it calls RemoveAll on the other subpaths (containers, etc-hosts, plugins). And if both of those are successful, it calls `rmdir` on the pod directory itself.

#### Which issue(s) this PR fixes:
Fixes #101911

#### Special notes for your reviewer:
cc: @msau42 @gnufied @jingxu97 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dobsonj** [comment]
/test all
They passed once, and then didn't run again after I removed the merge commit.

File: pkg/util/removeall/removeall.go [hunk 1]
```diff
@@ -97,7 +97,7 @@ func RemoveAllOneFilesystem(mounter mount.Interface, path string) error {
 	fd.Close()
```
Comment (gnufied) [inline pkg/util/removeall/removeall.go:97]: nit: I would probably move `fd.Close` in a defer after opening the file and and assumning no errors were thrown.

**Review by gnufied — COMMENTED** [review]
Is there a way we can add some unit tests for this?

File: pkg/util/removeall/removeall.go (hunk 1 above)
Comment (dobsonj) [reply pkg/util/removeall/removeall.go:97]: This looks like a deliberate decision in the original implementation. The comment right above that (line 96) says:
```
// Close directory, because windows won't remove opened directory.
```
if we were to defer instead, the fd would be closed after the remove() call, which could introduce issues on Windows systems.

Comment (gnufied) [reply pkg/util/removeall/removeall.go:97]: ah okay.

**Comment by dobsonj** [comment]
> Is there a way we can add some unit tests for this?

Yes, I added one new test case for kubelet_volumes (where `cleanupOrphanedPodDirs` is tested), along with a new set of tests for `RemoveDirsOneFilesystem`.

File: pkg/kubelet/kubelet_volumes.go [hunk 2]
```diff
@@ -147,55 +200,47 @@ func (kl *Kubelet) cleanupOrphanedPodDirs(pods []*v1.Pod, runningPods []*kubecon
...
-				} else {
-					klog.InfoS("Cleaned up orphaned volume subpath from pod", "podUID", uid, "path", subpathVolumePath)
-				}
+		for _, podSubdir := range podSubdirs {
+			podSubdirName := podSubdir.Name()
+			podSubdirPath := filepath.Join(podDir, podSubdirName)
+			// Never attempt RemoveAllOneFilesystem on the volumes directory,
+			// as this could lead to data loss in some situations. The volumes
+			// directory should have been removed by removeOrphanedPodVolumeDirs.
+			if podSubdirName == "volumes" {
```
Comment (gnufied) [inline pkg/kubelet/kubelet_volumes.go:229]: basically if this happens - it is almost guaranteed that pod cleanup will fail because `syscall.Rmdir(podDir)` below will fail. In that case - shouldn't we log this as error?

Comment (dobsonj) [reply pkg/kubelet/kubelet_volumes.go:229]: Yes, good point, I changed this to an error log message. This condition "shouldn't" happen, at least in the absence of any race conditions. If we hit an error in `removeOrphanedPodVolumeDirs` then we'll stop before entering this podSubdir loop. But if the volumes directory got removed successfully and then re-created by another process, we could hit this line, and it would be fair to treat that as an error since the final rmdir call will fail.

Comment (dobsonj) [reply pkg/kubelet/kubelet_volumes.go:229]: Well, after I pushed that change, `pull-kubernetes-verify` failed with:
```
kubelet_volumes.go:230:5: unstructured logging function "Error" should not be used
```
The only reason I tried to use `Error` instead of `ErrorS` is because we do not have a specific `err` to pass along to the log in this case. `ErrorS` requires an error as the first argument, while `InfoS` does not. I'm going to revert this back to an `InfoS` call for now, but let me know if you have a better idea. The goal of this log statement is just to leave behind a breadcrumb in case the `volumes` directory somehow gets recreated after `removeOrphanedPodVolumeDirs` returns success.

**Comment by pohly** [comment]
> They passed once, and then didn't run again after I removed the merge commit.

Please remember to add `--check-volume-lifecycle` to
https://github.com/kubernetes/kubernetes/blob/887e5e61b0cdca445bce1e9549ac38dc9814ca62/test/e2e/storage/drivers/csi.go#L229-L234

Without that, tests may pass although the NodeUnpublishVolume and NodeUnstageVolume calls were not invoked.

File: pkg/kubelet/kubelet_volumes.go (hunk 2 above)
Comment (gnufied) [reply pkg/kubelet/kubelet_volumes.go:229]: I have not looked into structured logging proposal too deeply but traditionally monitoring systems parse error level logs differently than info logs (I don't know why we don't have `WarningS`) and hence I would prefer to log it as error even if we have to instantiate an error type via `errors.New()`.

Comment (dobsonj) [reply pkg/kubelet/kubelet_volumes.go:229]: Thanks, I think Errorf is what I was looking for, and I see some other components using it so hopefully the verify check will pass this time. If not, I'll follow pohly's suggestion.

**Comment by dobsonj** [comment]
> Please remember to add `--check-volume-lifecycle`

@pohly thanks for pointing this out! Added.

File: pkg/kubelet/kubelet_volumes.go (hunk 2 above)
Comment (pohly) [reply pkg/kubelet/kubelet_volumes.go:229]: > I don't know why we don't have WarningS

https://github.com/go-logr/logr#why-not-named-levels-like-infowarningerror

File: pkg/kubelet/kubelet_volumes.go [hunk 3]
```diff
@@ -110,6 +112,57 @@ func (kl *Kubelet) newVolumeMounterFromPlugins(spec *volume.Spec, pod *v1.Pod, o
...
+	// If there are any volume-subpaths, attempt to rmdir them
+	subpathVolumePaths, err := kl.getPodVolumeSubpathListFromDisk(uid)
+	if err != nil {
+		orphanVolumeErrors = append(orphanVolumeErrors, fmt.Errorf("orphaned pod %q found, but error %v occurred during reading of volume-subpaths dir from disk", uid, err))
+		return orphanVolumeErrors
+	}
+	if len(subpathVolumePaths) > 0 {
+		for _, subpathVolumePath := range subpathVolumePaths {
+			if err := syscall.Rmdir(subpathVolumePath); err != nil {
+				orphanVolumeErrors = append(orphanVolumeErrors, fmt.Errorf("orphaned pod %q found, but failed to rmdir() subpath at path %v: %v", uid, subpathVolumePath, err))
```
Comment (jingxu97) [inline pkg/kubelet/kubelet_volumes.go:147]: just want to double check how often these errors will be print out?

Comment (dobsonj) [reply pkg/kubelet/kubelet_volumes.go:147]: The errors that are appended to `orphanVolumeErrors` or `orphanRemovalErrors` are printed once by `logSpew` each time the kubelet attempts orphan cleanup for a given pod.
https://github.com/kubernetes/kubernetes/blob/484eb01822244904e902d2cb77ef08112e806377/pkg/kubelet/kubelet_volumes.go#L248-L257
By default you'll just see a summary log message in kubelet.log like this:
```
E0603 20:13:19.089595 3182368 kubelet_volumes.go:249] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"80ddb1a3-fb23-4470-9ac5-9eabedd22cd6\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=3
```
Then if you want to see each individual message, the verbosity level needs to be >= 5

File: pkg/util/removeall/removeall.go [hunk 4]
```diff
@@ -106,3 +106,18 @@ func RemoveAllOneFilesystem(mounter mount.Interface, path string) error {
 	}
 	return err
 }
+
+// RemoveAllOneFilesystem removes the path and any children it contains, using
+// the os.Remove function. It makes sure it does not cross mount boundaries,
+// i.e. it does *not* remove files from another filesystem.
```
Comment (liggitt) [inline pkg/util/removeall/removeall.go:112]: clarify the behavior when files/folders under this path do cross filesystems... is an error returned? can some files still be removed before that error is returned?

File: pkg/util/removeall/removeall.go [hunk 5]
```diff
@@ -106,3 +106,18 @@ func RemoveAllOneFilesystem(mounter mount.Interface, path string) error {
...
+func RemoveAllOneFilesystem(mounter mount.Interface, path string) error {
+	return RemoveAllOneFilesystemCommon(mounter, path, os.Remove)
+}
+
+// RemoveDirsOneFilesystem removes the path and any empty subdirectories it
+// contains, using the syscall.Rmdir function. Unlike RemoveAllOneFilesystem,
+// RemoveDirsOneFilesystem will remove only directories and fails if it
+// encounters any files in the directory tree.
+func RemoveDirsOneFilesystem(mounter mount.Interface, path string) error {
```
Comment (liggitt) [inline pkg/util/removeall/removeall.go:121]: clarify the behavior when files/folders under this path do cross filesystems... is an error returned? can some files still be removed before that error is returned?

File: pkg/util/removeall/removeall.go [hunk 6]
```diff
@@ -25,16 +25,16 @@ import (
 	"k8s.io/mount-utils"
```
Comment (liggitt) [inline pkg/util/removeall/removeall.go:25]: who is the right sig to own this package? it looks like everything under pkg/util bubbles to pkg/owners, which doesn't seem right

**Comment by ehashman** [comment]
How does this interact with https://github.com/kubernetes/kubernetes/pull/102344 ?

**Comment by gnufied** [comment]
@ehashman those are kind of separate but related issues. Clayton's PR imo is trying to fix the race condition so as we never get into bad state. This PR is trying to ensure that - even if we get into the bad state, we never lose data. This PR should be easier to backport to older releases.

File: pkg/util/removeall/removeall.go (hunk 6 above)
Comment (gnufied) [reply pkg/util/removeall/removeall.go:25]: sig-storage should be the right sig to own the `removeall` package. But it is just one file.

File: pkg/util/removeall/removeall.go (hunk 5 above)
Comment (dobsonj) [reply pkg/util/removeall/removeall.go:126]: Thanks, I've expanded on these comments, and also added an OWNERS file for the `removeall` package.

**Comment by dobsonj** [comment]
@liggitt @ehashman any other feedback on this PR? I'd like to move it forward if I've addressed your comments.

**Comment by liggitt** [comment]
I'll defer to node/storage approvers on this one. Once this has approval from them, I can ack if needed to get the new OWNERS file in place.

File: pkg/util/removeall/removeall.go (hunk 6 above)
Comment (gnufied) [reply pkg/util/removeall/removeall.go:25]: cc @msau42 @jsafrane does sig-storage being approver for `removeall` package seems reasonable ?

Comment (msau42) [reply pkg/util/removeall/removeall.go:25]: only storage related logic appears to use this function so I think sig-storage as owners makes sense

File: pkg/kubelet/kubelet_volumes.go (hunk 2 above)
Comment (ehashman) [reply pkg/kubelet/kubelet_volumes.go:229]: Error condition looks good. See also https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions-to-structured-equivalent for there not being "WarningS" equivalents.

**Review by ehashman — COMMENTED** [review]
I'm not very familiar with this code but the description, test, and implementation in pkg/kubelet/kubelet_volumes.go LGTM with SIG Storage's :+1:
