### PR TITLE
Fix unnecessary recreation of placeholder EndpointSlice

### LINKED ISSUE #108231: Empty endpointslices are fully updated every cycle defined by controller-manager default --min-resync-period=12h
### What happened?

My cluster contains about 4w endpointslices. There are 3 related metrics (endpoint_slice_controller_endpoints_added_per_sync_count, endpoint_slice_controller_endpoints_removed_per_sync_count, endpoint_slice_controller_changes) to indicates endpoint add remove and update. I found that the apiserver periodically receives lots of endpointslice update requests. In terms of the number of requests, the endpointslice has been fully updated. But from the endpointslice resource itself, it seems that it has not been updated, because "endpoints.kubernetes.io/last-change-trigger-time" annotation didn't change

### What did you expect to happen?

It seems that there is no need to update the endpointslice with no really changes. On the other hand, a large number of ep slice update requests will stress the apiserver.

### How can we reproduce it (as minimally and precisely as possible)?

In order to make the phenomenon more obvious, the min-resync-period parameter of controller-manager can be adjusted to 1 minute. Create one or more empty endpointslices, and then you can find in the apiserver logs that requests to update these endpointslice every one to two minutes. For clusters with lots of empty endpointslices, this bug may affect the stability of it.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10", GitCommit:"79688684d40e9b5612f155e7911fb430eda38169", GitTreeState:"clean", BuildDate:"2021-09-15T09:53:17Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10", GitCommit:"79688684d40e9b5612f155e7911fb430eda38169", GitTreeState:"clean", BuildDate:"2021-09-14T11:37:12Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# VERSION="16.04.6 LTS (Xenial Xerus)"
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by spencerhance**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes #108231 by checking `slicesToDelete` in the EndpointSlice
reconciler for a pre-existing placeholder slice.

Also adds a helper function for comparing the slices.

#### Which issue(s) this PR fixes:

Fixes #108231

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by spencerhance** [comment]
cc: @robscott 

/assign @aojea

File: pkg/controller/endpointslice/reconciler.go [hunk 1]
```diff
@@ -215,12 +216,18 @@ func (r *reconciler) reconcileByAddressType(service *corev1.Service, pods []*cor
...
+		} else {
+			slicesToCreate = append(slicesToCreate, placeholderSlice)
+			spMetrics.Set(endpointutil.NewPortMapKey(placeholderSlice.Ports), metrics.EfficiencyInfo{
+				Endpoints: 0,
+				Slices:    1,
+			})
+		}
 	}
 
 	metrics.EndpointsAddedPerSync.WithLabelValues().Observe(float64(totalAdded))
```
Comment (aojea) [inline pkg/controller/endpointslice/reconciler.go:233]: what happen with  this "totalAdded" and "totalRemoved" metrics now?

Comment (aojea) [reply pkg/controller/endpointslice/reconciler.go:233]: oh, I see, based on the test added it seems that the metrics were always correct

File: pkg/controller/endpointslice/reconciler_test.go [hunk 2]
```diff
@@ -460,34 +459,152 @@ func TestReconcile1Pod(t *testing.T) {
...
+			x:    &discovery.EndpointSlice{},
+			y:    &discovery.EndpointSlice{},
+			want: true,
+		},
+		{
+			desc: "Both are empty and non-nil",
+			x:    &discovery.EndpointSlice{},
+			y:    &discovery.EndpointSlice{},
+			want: true,
+		},
```
Comment (aojea) [inline pkg/controller/endpointslice/reconciler_test.go:568]: duplicate, right?

File: pkg/controller/endpointslice/reconciler_test.go [hunk 3]
```diff
@@ -460,34 +459,152 @@ func TestReconcile1Pod(t *testing.T) {
...
+		{
+			desc: "Only ObjectMeta has diff",
+			x: &discovery.EndpointSlice{ObjectMeta: metav1.ObjectMeta{
+				Name: "foo",
+			}},
+			y: &discovery.EndpointSlice{ObjectMeta: metav1.ObjectMeta{
+				Name: "bar",
```
Comment (aojea) [inline pkg/controller/endpointslice/reconciler_test.go:575]: two slices with different names should be considered equal?

File: pkg/controller/endpointslice/reconciler.go [hunk 4]
```diff
@@ -251,6 +258,28 @@ func (r *reconciler) reconcileByAddressType(service *corev1.Service, pods []*cor
 	return r.finalize(service, slicesToCreate, slicesToUpdate, slicesToDelete, triggerTime)
 }
 
+// sliceEqual returns if two slices are equal.  It ignores everything in ObjectMeta besides Labels.
```
Comment (aojea) [inline pkg/controller/endpointslice/reconciler.go:261]: we are setting more fields in ObjectMeta, why those are not taking into account for equality?

https://github.com/kubernetes/kubernetes/blob/ea978cbe996a7eaf9a50a01534c5196f49d4906a/pkg/controller/endpointslice/utils.go#L137-L154

File: pkg/controller/endpointslice/reconciler_test.go [hunk 5]
```diff
@@ -460,34 +459,152 @@ func TestReconcile1Pod(t *testing.T) {
...
-	assert.EqualValues(t, []discovery.Endpoint{}, slices[0].Endpoints)
-	expectTrackedGeneration(t, r.endpointSliceTracker, &slices[0], 1)
-	expectMetrics(t, expectedMetrics{desiredSlices: 1, actualSlices: 1, desiredEndpoints: 0, addedPerSync: 0, removedPerSync: 0, numCreated: 0, numUpdated: 1, numDeleted: 0, slicesChangedPerSync: 1})
+			numActionsBefore := len(client.Actions())
+			r := newReconciler(client, []*corev1.Node{{ObjectMeta: metav1.ObjectMeta{Name: "node-1"}}}, defaultMaxEndpointsPerSlice)
+
+			// Run reconcile multiple times to make sure that subsequent calls don't do any additional work
+			for i := 0; i < 1; i++ {
+				reconcileHelper(t, r, &svc, []*corev1.Pod{}, existingSlices, time.Now())
+			}
```
Comment (aojea) [inline pkg/controller/endpointslice/reconciler_test.go:510]: :upside_down_face: multiple times?  this only executes once  ;)

Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler_test.go:510]: Whoops forgot to remove this from an earlier version of the test :)

File: pkg/controller/endpointslice/reconciler_test.go (hunk 2 above)
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler_test.go:568]: Yes, fixed :)

File: pkg/controller/endpointslice/reconciler_test.go (hunk 3 above)
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler_test.go:565]: In this case yes, since the placeholder slice will have a generated name that can change between resync periods

File: pkg/controller/endpointslice/reconciler.go (hunk 4 above)
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler.go:261]: Good point, in this case maybe we can safely compare everything except for Name/GenerateName

File: pkg/controller/endpointslice/reconciler_test.go (hunk 5 above)
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler_test.go]: Done

File: pkg/controller/endpointslice/reconciler.go (hunk 4 above)
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler.go]: Pushed an update to the comparison logic and renamed the func since it is specific to the placeholder slice

File: pkg/controller/endpointslice/reconciler.go [hunk 6]
```diff
@@ -251,6 +258,32 @@ func (r *reconciler) reconcileByAddressType(service *corev1.Service, pods []*cor
...
+		Labels:          yCopy.ObjectMeta.Labels,
+		OwnerReferences: yCopy.OwnerReferences,
+		Namespace:       yCopy.Namespace,
+	}
+
+	result := apiequality.Semantic.DeepEqual(xCopy, yCopy)
+
+	return result
+}
+
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/controller/endpointslice/reconciler.go:286]: I will try to do a small benchmark to compare them, if nobody beats me

[the remark this answers is not in the document]
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler.go:286]: Ran a quick bench between the two and the conversion func method is definitely more efficient.  Since we can make a bunch of assumptions about what the placeholder slice should have we can save some comparisons.  The downside of this is that if we ever update the desired placeholder slice logic we have to update this func as well.

https://gist.github.com/spencerhance/a607871b5490a5ff6b2bfe52571eb496

**Comment by aojea** [comment]
lgtm but I'd like @robscott @thockin and @wojtek-t to look at https://github.com/kubernetes/kubernetes/pull/110365#discussion_r889255360

**Comment by spencerhance** [comment]
Okay thanks!

**Comment by robscott** [comment]
Will defer to @wojtek-t or @thockin on scalability implications and corresponding LGTM, I think this should still be a net improvement compared to now. Previously we would always be updating an EndpointSlice in this scenario, now we're just doing a comparison.

/approve

File: pkg/controller/endpointslice/reconciler.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/controller/endpointslice/reconciler.go:286]: Why does it need to be deep-copy?  In this case a shallow copy seems perfect, unless I am missing something?

```
	// Make a shallow copy (cheap) and wipe all metadata fields except the
	// ones we actually care about, so that we can use DeepEqual.
	xCopy := x // shallow copy
	yCopy := y // shallow copy
	xCopy.ObjectMeta = metav1.ObjectMeta{
		Labels:          xCopy.ObjectMeta.Labels,
		OwnerReferences: xCopy.OwnerReferences,
		Namespace:       xCopy.Namespace,
	}
	yCopy.ObjectMeta = metav1.ObjectMeta{
		Labels:          yCopy.ObjectMeta.Labels,
		OwnerReferences: yCopy.OwnerReferences,
		Namespace:       yCopy.Namespace,
	}
```

[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/endpointslice/reconciler.go:286]: +1 for shallow copy

That said I think we can do much better than that by defining our customer DeepEqual function.
Given we create placeholder slice, we can probably just focus on checking only the couple fields of ObjectMeta.
And we can define our file-level Equality that will just overwrite comparing of ObjectMeta to limit to those fields:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/equality/semantic.go#L29

And with that we won't even need shallow copies.

[the remark this answers is not in the document]
Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler.go]: Good call, the shallow copy also works here.  I pushed an update with the shallow copy but I can also use the conversion func method.  How does this look?

```
	compare := conversion.EqualitiesOrDie(
		func(a, b metav1.OwnerReference) bool {
			return a.String() == b.String()
		},
		func(a, b metav1.ObjectMeta) bool {
			if a.Namespace != b.Namespace {
				return false
			}
			for k, v := range a.Labels {
				if b.Labels[k] != v {
					return false
				}
			}
			for k, v := range b.Labels {
				if a.Labels[k] != v {
					return false
				}
			}
			return true
		},
```

File: pkg/controller/endpointslice/reconciler.go [hunk 7]
```diff
@@ -251,6 +258,33 @@ func (r *reconciler) reconcileByAddressType(service *corev1.Service, pods []*cor
...
+// It ignores many of the fields in ObjectMeta that are not expected to match.
+func placeholderSliceEqual(x, y *discovery.EndpointSlice) bool {
+	if x == nil || y == nil {
+		return x == y
+	}
+
+	// Make a shallow copy (cheap) and wipe all metadata fields except the
+	// ones we actually care about, so that we can use DeepEqual.
+	xCopy := x
+	yCopy := y
```
Comment (wojtek-t) [inline pkg/controller/endpointslice/reconciler.go:271]: > Good call, the shallow copy also works here.  I pushed an update with the shallow copy but I can also use the conversion func method.  How does this look?
> 
```
	compare := conversion.EqualitiesOrDie(
		func(a, b metav1.OwnerReference) bool {
			return a.String() == b.String()
		},
		func(a, b metav1.ObjectMeta) bool {
			if a.Namespace != b.Namespace {
				return false
			}
			for k, v := range a.Labels {
				if b.Labels[k] != v {
					return false
				}
			}
			for k, v := range b.Labels {
				if a.Labels[k] != v {
					return false
				}
			}
			return true
		},
```

That LGTM -  I would go with the above to avoid even creating those shallow copies.

[Other than that it LGTM too.]

Comment (thockin) [reply pkg/controller/endpointslice/reconciler.go:271]: +1

Comment (spencerhance) [reply pkg/controller/endpointslice/reconciler.go]: Okay thanks!  Pushed

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
Unit test failure looks legit

**Comment by pacoxu** [comment]
> Unit test failure looks legit

/hold 
to avoid continuously retest
feel free to `/unhold` once the test passs.

**Review by robscott — COMMENTED** [review]
Thanks!

/lgtm
