### PR TITLE
Fix third party APIResource reporting

### LINKED ISSUE #25570: Only the first ThirdPartyResource created in a groupVersion actually installed
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.3.756+64c5809bd57784", GitCommit:"64c5809bd577848ba0fb271e1cbe6b372256fe15", GitTreeState:"clean", BuildDate:"2016-05-12T21:33:55Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.0-alpha.3.756+64c5809bd57784", GitCommit:"64c5809bd577848ba0fb271e1cbe6b372256fe15", GitTreeState:"clean", BuildDate:"2016-05-12T21:33:55Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

I create two TPRs:

```yaml
# cat catalog.yaml 
kind: ThirdPartyResource
apiVersion: extensions/v1beta1
metadata:
  name: catalog.alpha.redhat.com
description: "A specification of a catalog of resources"
versions:
- name: v1alpha1
# cat catalog-entry.yaml 
kind: ThirdPartyResource
apiVersion: extensions/v1beta1
metadata:
  name: catalog-entry.alpha.redhat.com
description: "A specification of a resource in a catalog"
versions:
- name: v1alpha1
```
Both show up in the ThirdPartyResourceList...
```json
curl http://127.0.0.1:8080/apis/extensions/v1beta1/thirdpartyresources
{
  "kind": "ThirdPartyResourceList",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "selfLink": "/apis/extensions/v1beta1/thirdpartyresources",
    "resourceVersion": "75"
  },
  "items": [
    {
      "metadata": {
        "name": "catalog-entry.alpha.redhat.com",
        "selfLink": "/apis/extensions/v1beta1/thirdpartyresources/catalog-entry.alpha.redhat.com",
        "uid": "8c4a60e0-1889-11e6-bfe6-bc5ff47352bf",
        "resourceVersion": "25",
        "creationTimestamp": "2016-05-12T21:36:12Z"
      },
      "description": "A specification of a resource in a catalog",
      "versions": [
        {
          "name": "v1alpha1"
        }
      ]
    },
    {
      "metadata": {
        "name": "catalog.alpha.redhat.com",
        "selfLink": "/apis/extensions/v1beta1/thirdpartyresources/catalog.alpha.redhat.com",
        "uid": "89a0a0c8-1889-11e6-bfe6-bc5ff47352bf",
        "resourceVersion": "23",
        "creationTimestamp": "2016-05-12T21:36:07Z"
      },
      "description": "A specification of a catalog of resources",
      "versions": [
        {
          "name": "v1alpha1"
        }
      ]
    }
  ]
}
```
but only the first is actually installed.
```json
curl http://127.0.0.1:8080/apis/alpha.redhat.com/v1alpha1/
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "alpha.redhat.com/v1alpha1",
  "resources": [
    {
      "name": "catalogs",
      "namespaced": true,
      "kind": "Catalog"
    }
  ]
}
```
If I reverse the order in which they are created, the first one is always the one that gets installed.

### PR DESCRIPTION
**Pull request by brendandburns**
@polvi @caesarxuchao @deads2k 

This "fixes" some additional bugs in third party `APIResourceList` reporting.

This code needs a bunch of cleanup, and more tests, but sending it out for a quick smell check review in case I'm doing something stupid.

Fixes the bug referenced here:  https://github.com/kubernetes/kubernetes/pull/28414#issuecomment-235346108 and in https://github.com/kubernetes/kubernetes/issues/23831

Fixes https://github.com/kubernetes/kubernetes/issues/25570

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29724)

### CODE REVIEW

**Comment by brendandburns** [comment]
@nikhiljindal friendly ping on this one.

Thanks
--brendan

File: pkg/master/thirdparty_controller.go [hunk 1]
```diff
@@ -44,13 +56,14 @@ func getThirdPartyGroupName(path string) string {
...
-	// Remove a third party resource based on the RESTful path for that resource
+	// Remove a third party resource based on the RESTful path for that resource, the path is <api-group-path>/<resource-plural-name>
 	RemoveThirdPartyResource(path string) error
 	// Install a third party resource described by 'rsrc'
 	InstallThirdPartyResource(rsrc *expapi.ThirdPartyResource) error
 	// Is a particular third party resource currently installed?
 	HasThirdPartyResource(rsrc *expapi.ThirdPartyResource) (bool, error)
-	// List all currently installed third party resources
+	// List all currently installed third party resources, the returned
+	// names are <api-group-path>/<resource-plural-name>
```
Comment (nikhiljindal) [inline pkg/master/thirdparty_controller.go]: names are of the form..

File: pkg/master/master_test.go [hunk 2]
```diff
@@ -575,10 +575,18 @@ func initThirdPartyMultiple(t *testing.T, versions, names []string) (*Master, *e
...
-			t.Logf("Failed to install API: %v", err)
-			t.FailNow()
+		hasRsrc, err := master.HasThirdPartyResource(api)
+		if err != nil {
+			t.Errorf("Unexpected error: %v", err)
+		}
+		if !hasRsrc {
+			err := master.InstallThirdPartyResource(api)
+			if !assert.NoError(err) {
+				t.Logf("Failed to install API: %v", err)
```
Comment (nikhiljindal) [inline pkg/master/master_test.go]: Use t.Errorf() here?

File: pkg/master/master.go [hunk 3]
```diff
@@ -542,37 +543,60 @@ func (m *Master) getServersToValidate(c *Config) map[string]apiserver.Server {
...
 	}
 	return nil
 }
 
 // RemoveThirdPartyResource removes all resources matching `path`.  Also deletes any stored data
 func (m *Master) RemoveThirdPartyResource(path string) error {
-	if err := m.removeThirdPartyStorage(path); err != nil {
+	ix := strings.LastIndex(path, "/")
+	if ix == -1 {
+		return fmt.Errorf("unexpected path: %s", path)
```
Comment (nikhiljindal) [inline pkg/master/master.go]: Can you say why is it unexpected? Why should it have a "/"?

File: pkg/master/master.go [hunk 4]
```diff
@@ -542,37 +543,60 @@ func (m *Master) getServersToValidate(c *Config) map[string]apiserver.Server {
...
 	}
 	path := makeThirdPartyPath(group)
-	services := m.HandlerContainer.RegisteredWebServices()
-	for ix := range services {
-		if services[ix].RootPath() == path {
-			return true, nil
-		}
+	m.thirdPartyResourcesLock.Lock()
+	defer m.thirdPartyResourcesLock.Unlock()
+	entry := m.thirdPartyResources[path]
```
Comment (nikhiljindal) [inline pkg/master/master.go]: shouldnt it be `entry, found := `?

File: pkg/apiserver/apiserver.go [hunk 5]
```diff
@@ -116,14 +124,26 @@ const (
 	MaxTimeoutSecs = 600
 )
 
+type staticLister struct {
```
Comment (nikhiljindal) [inline pkg/apiserver/apiserver.go]: At other places we add `var _ APIResourceLister := &staticLister{}` to ensure and document that staticLister implements the APIResourceLister interface.

File: pkg/master/thirdparty_controller.go [hunk 6]
```diff
@@ -30,6 +31,17 @@ import (
 
 const thirdpartyprefix = "/apis"
 
+// dynamicLister is used to list resources for dynamic third party
+// apis.
+type dynamicLister struct {
```
Comment (nikhiljindal) [inline pkg/master/thirdparty_controller.go]: same as staticLister.
Add `var _ APIResourceLister := &dynamicLister{}`

**Comment by nikhiljindal** [comment]
@brendandburns Can you please call out the bugs that you are fixing?
We should also add new test cases for each of those bugs.

**Comment by nikhiljindal** [comment]
cc @lavalamp since I think he reviewed the last third party related PR.
Also cc @kubernetes/sig-api-machinery

**Comment by nikhiljindal** [comment]
@brendandburns I see you added the cherrypick-candidate label. Do you want to get this cherrypicked in 1.3? 
I am not certain but I think you should change the milestone to 1.3 in that case.

**Comment by hongchaodeng** [comment]
@brendandburns 
Thanks for providing the fix. Please let me know if you want us from CoreOS to help in any work e.g. cleanup, tests as you mentioned.

/cc @xiang90 @aaronlevy

File: pkg/master/thirdparty_controller.go (hunk 1 above)
Comment (brendandburns) [inline pkg/master/thirdparty_controller.go]: done.

File: pkg/master/master_test.go (hunk 2 above)
Comment (brendandburns) [inline pkg/master/master_test.go]: done.

File: pkg/master/master.go (hunk 3 above)
Comment (brendandburns) [inline pkg/master/master.go]: expanded.  This is because we expect <api-group>/<resource-name>

File: pkg/master/master.go (hunk 4 above)
Comment (brendandburns) [inline pkg/master/master.go]: not necessary, it's a pointer in that map, so if it doesn't exist, it will return a `nil` pointer which is checked on the next line.

File: pkg/apiserver/apiserver.go (hunk 5 above)
Comment (brendandburns) [inline pkg/apiserver/apiserver.go]: done.

File: pkg/master/thirdparty_controller.go (hunk 6 above)
Comment (brendandburns) [inline pkg/master/thirdparty_controller.go]: done.

**Comment by brendandburns** [comment]
@nikhiljindal comments addressed, added references to the bugs.

regarding the milestone, it seems like 1.4 is right since that is where _this_ PR will go, the cherry-pick will go to 1.3, but I defer to whatever the convention is.

Thanks
--brendan

**Comment by brendandburns** [comment]
I added a `test-cmd` test that validates this works as well.

**Comment by brendandburns** [comment]
@nikhiljindal friendly ping on this PR.

Thanks!

File: pkg/apiserver/apiserver.go [hunk 7]
```diff
@@ -116,14 +124,29 @@ const (
 	MaxTimeoutSecs = 600
 )
 
+// staticLister mplements the APIResourceLister interface
```
Comment (nikhiljindal) [inline pkg/apiserver/apiserver.go]: implements

**Comment by nikhiljindal** [comment]
One minor nit. Feel free to apply LGTM label after fixing it and squashing commits.

Thanks for the fixes!

**Comment by sjenning** [comment]
This fixes https://github.com/kubernetes/kubernetes/issues/25570 btw. Thanks!

File: pkg/apiserver/apiserver.go (hunk 7 above)
Comment (brendandburns) [inline pkg/apiserver/apiserver.go]: done.

**Comment by brendandburns** [comment]
Squashed and comment addressed, marking LGTM.

**Comment by polvi** [comment]
@brendandburns confirming this works. Thank you!

**Comment by fabioy** [comment]
@brendandburns This has a cherrypick label, but a 1.4 milestone. Do you want this to be picked for 1.3?

**Comment by brendandburns** [comment]
Yes please picked for 1.3 please.

--brendan

________________________________

**Comment by fabioy** [comment]
@brendandburns Automated cherrypick script failed with a conflict. Can you create a cherrypick PR for 1.3? Thanks.

**Comment by pwittrock** [comment]
@brendandburns The cherrypick-approved label + 1.4 milestone was making it confusing to do 1.4 cherry picks.  I removed it for now.  Feel free to add it back when you are ready to cherrypick it into 1.3.

**Comment by eparis** [comment]
@brendandburns since this is for 1.3 you will need to open the pick PR yourself. I believe that @erictune was approving/merging for 1.3 after the author opens the PR.

**Comment by erictune** [comment]
I'd be fine with taking this for 1.3.  You'll need to open a pick PR.

**Comment by fabioy** [comment]
Reapproved. Need cherrypick PR (conflicts when created automatically).

**Comment by janetkuo** [comment]
Cherrypick PR: #33217
