### PR TITLE
[sig-scheduling] SchedulerPreemption [Serial] validates various priority Pods preempt expectedly with the async preemption: replace finalizers with preStop hook and TerminationGracePeriodSeconds

### LINKED ISSUE #131695: [sig-scheduling] SchedulerPreemption [Serial] validates various priority Pods preempt expectedly with the async preemption:  test assumption about finalizers does not reflect KS synthetic deletes
Continuation from https://kubernetes.slack.com/archives/C09TP78DV/p1746638728585879.

`[sig-scheduling] SchedulerPreemption [Serial] validates various priority Pods preempt expectedly with the async preemption` test is deploying low priority pods with finalizers. The low priority pods are expected to be preempted by the scheduler preemption controller and stay around (not deleted because of the finalizers) before all high priority pods have their `.Status.NominatedNodeName` field set. Yet, given the scheduler specifies a field selector (`status.phase!=Succeeded,status.phase!=Failed`) when watching pods once a pod succeeds the kube-apiserver issues a synthetic deleted (since the pod no longer fits the field selector). Telling the KS the pod got deleted even though it is still around (because of the finalizer as discussed in https://kubernetes.slack.com/archives/C0EG7JC6T/p1746535228066589). Thus, allowing a high priority pod to be scheduled. The test does not expect a (synthetic) delete to be issue before a finalizer of either of the low priority pods is removed.

I was not able to find an upstream test failure. Yet, the e2e test perma fails for our OpenShift v1.33.0 rebase. I was able to reproduce the same violation of the test assumption in v1.33.3 kind cluster. Steps to reproduce:
1. create a low priority pod with a finalizer
1. schedule the low priority pod
1. create a high priority pod
1. have the KS async prempt the low priority pod
1. observe the low priority pod succeeds (or fails) and the high priority pod gets scheduled even when the low priority pod is still around (because of the finalizer still present).

Reproducing the issue using the e2e test manifests in this form:
```
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 1
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: 100
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-finalizer-low-priority-1
  finalizers:
    - example.com/custom-protection
spec:
  containers:
    - name: pausepod
      image: registry.k8s.io/pause:3.10
      resources:
        limits:
          scheduling.k8s.io/foo: "10"
        requests:
          scheduling.k8s.io/foo: "10"
  priorityClassName: low-priority
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-finalizer-medium-priority-1
  finalizers:
    - example.com/custom-protection
spec:
  containers:
    - name: pausepod
      image: registry.k8s.io/pause:3.10
      resources:
        limits:
          scheduling.k8s.io/foo: "10"
        requests:
          scheduling.k8s.io/foo: "10"
  priorityClassName: medium-priority
```

The following command can be run to extend the worker nodes with the new extended resource (one might need to run `kubectl proxy &` in addition):
```
curl --header "Content-Type: application/json-patch+json" --request PATCH --data '[{"op": "add", "path": "/status/capacity/scheduling.k8s.io~1foo", "value": "10"}]' http://localhost:8001/api/v1/nodes/NODE_NAME/status
```

### PR DESCRIPTION
**Pull request by ingvagabund**
#### What type of PR is this?
/kind bug
/kind failing-test

#### What this PR does / why we need it:
Finalizers do not work as expected when an informer with a field selector is used. Any time a pod changing its state gets excluded by the field selector a synthetic delete event is issues even though the pod with a finalizer set is still present. Thus, making the scheduler schedule the high and medium priority pods before any of the low priority pod finalizers is removed. Instead, rely on preStop hook and TerminationGracePeriodSeconds to keep all low priority pods long enough included by the field selector so all high priority pods can set their .status.nominatedNodeName field.

Also, update the check for how many medium priority pods are expected to be scheduled. Each node can accept 10 pods of the given extended resources. Given there's 5 high priority created per node, there's always 5 times number of nodes spots left for the medium priority pods.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/131695

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/scheduling/preemption.go [hunk 1]
```diff
@@ -426,18 +431,12 @@ var _ = SIGDescribe("SchedulerPreemption", framework.WithSerial(), func() {
 			}))
 		}
 
-		ginkgo.By("Remove the finalizer from all low priority pods to proceed the preemption.")
-		for _, pod := range lowPriorityPods {
-			// Remove the finalizer so that the pod can be deleted by GC
-			e2epod.NewPodClient(f).RemoveFinalizer(ctx, pod.Name, testFinalizer)
-		}
-
 		ginkgo.By("Wait for high priority pods to be scheduled.")
```
Comment (sanposhiho) [inline test/e2e/scheduling/preemption.go:434]: Would it be faster if we forcibly remove pods before this line? (where we were removing the finalizer)
Otherwise, here we have to spend ~80s to wait for low priority pods to be removed, right?

Comment (ingvagabund) [reply test/e2e/scheduling/preemption.go:434]: Yeah, you are right. There's a lot of low priority pods waiting for the TerminationGracePeriodSeconds to pass.

**Review by sanposhiho — COMMENTED** [review]
/lgtm

Thanks!

**Comment by sanposhiho** [comment]
/cc @macsko @dom4ha 

for the approval
