### PR TITLE
KEP-3221: Implement authorization configuration file reloading

### LINKED ISSUE #119102: [StructuredAuthorizationConfig] Implement reloading of configuration
### What would you like to be added?

Implement reloading of configuration in a loop at defined time intervals.

- Replace active authorizer on successful load and validation pass.
- Log and metric on failure

From the KEP:
The API server will periodically reload the configuration at a specific time interval. If it or any of referenced files change, and the new configuration passes validation, then the new configuration will be used for the Authorizer chain. The reloader will also check if the webhook is healthy, thereby preventing any typo/misconfiguration with the Webhook resulting in bad Authorizer config. If healthcheck on the webhook failed, the last known good config will be used. In the next iteration of reload, if webhook is found to be healthy, the new config will be used. Logging and metrics would be used to signal success/failure of a config reload so that cluster admins can have observability over this process. Reload must not add or remove Node or RBAC authorizers. They can be reordered, but cannot be added or removed.

### Why is this needed?

Implements https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3221-structured-authorization-configuration

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Implements reloading of the authorization configuration file. File reloads when an observed file event occurs or a 1 minute poll is encountered.

Best reviewed commit-by-commit, the validation / construction is refactored to split out the rbac / node / abac construction, and move the authorization construction to the reload functions.

Fixes #119102

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver now reloads the `--authorization-config` file when it changes. Reloads increment the `apiserver_authorization_config_controller_automatic_reload_last_timestamp_seconds` timestamp metric, with `status="success"` for successful reloads and `status="failed"` for failed reloads. Failed reloads keep using the previously loaded authorization configuration.
```

cc @ritazh @palnabarun

### CODE REVIEW

File: pkg/kubeapiserver/authorizer/reload.go [hunk 1]
```diff
@@ -140,3 +159,120 @@ func (r *reloadableAuthorizerResolver) newForConfig(authzConfig *authzconfig.Aut
 
 	return union.New(authorizers...), union.NewRuleResolvers(ruleResolvers...), nil
 }
+
+// runReload starts checking the config file for changes and reloads the authorizer when it changes.
+// Blocks until ctx is complete.
+func (r *reloadableAuthorizerResolver) runReload(ctx context.Context) {
```
Comment (enj) [inline pkg/kubeapiserver/authorizer/reload.go:165]: Can we write one shared controller that handles the file watching and polling that we can re-use for authn/authz/kms?

File: pkg/kubeapiserver/authorizer/reload.go [hunk 2]
```diff
@@ -140,3 +159,120 @@ func (r *reloadableAuthorizerResolver) newForConfig(authzConfig *authzconfig.Aut
...
+	metrics.RegisterMetrics()
+	metrics.RecordAuthorizationConfigAutomaticReloadSuccess(r.apiServerID)
+
+	go func() {
+		if err := r.watchFile(ctx); err != nil {
+			select {
+			case <-ctx.Done():
+				// server was shutting down, we don't care about reload errors
+			default:
+				klog.ErrorS(err, "watching authorization config file")
```
Comment (enj) [inline pkg/kubeapiserver/authorizer/reload.go:175]: Should this restart the watch?

File: pkg/kubeapiserver/authorizer/reload.go [hunk 3]
```diff
@@ -140,3 +159,120 @@ func (r *reloadableAuthorizerResolver) newForConfig(authzConfig *authzconfig.Aut
...
+	r.lastLoadedLock.Lock()
+	defer r.lastLoadedLock.Unlock()
+
+	data, err := os.ReadFile(r.initialConfig.ReloadFile)
+	if err != nil {
+		klog.ErrorS(err, "reloading authorization config")
+		metrics.RecordAuthorizationConfigAutomaticReloadFailure(r.apiServerID)
+		return
+	}
+	if bytes.Equal(data, r.lastReadData) {
```
Comment (enj) [inline pkg/kubeapiserver/authorizer/reload.go:244]: What if the kubeconfig of an authorizer changes without the main file changing?

**Review by enj — COMMENTED** [review]
Have only looked at like 5% of this PR but had some comments.

File: pkg/kubeapiserver/authorizer/reload.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubeapiserver/authorizer/reload.go:175]: not sure... I don't really know the variety of issues that could cause errors on the file watch, and don't want to do anything problematic with loops or exhausting file handles, so if it hits errors, I'd tend to collapse to the poll

**Comment by MaryamTavakkoli** [comment]
Hello! 
Release Signal shadow here.
The code freeze is starting [02:00 UTC Wednesday 6th March 2024 / 18:00 PDT Tuesday 5th March 2024](https://everytimezone.com/s/5056bace) (less than a month from now), and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As this PR is tagged for 1.30, is it still planned for this release?

**Comment by liggitt** [comment]
yes, this is part of KEP-3221, targeting beta in 1.30

File: pkg/kubeapiserver/authorizer/reload.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubeapiserver/authorizer/reload.go]: updated to make the poll attempt to restart the watch if an error was observed

**Comment by liggitt** [comment]
@enj @ritazh @palnabarun this is ready for review

File: pkg/kubeapiserver/authorizer/reload.go [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+	authzconfig "k8s.io/apiserver/pkg/apis/apiserver"
+	"k8s.io/apiserver/pkg/authentication/user"
+	"k8s.io/apiserver/pkg/authorization/authorizer"
+	"k8s.io/kubernetes/pkg/auth/authorizer/abac"
+	"k8s.io/kubernetes/plugin/pkg/auth/authorizer/node"
+	"k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac"
+)
+
+type reloadableAuthorizerResolver struct {
+	initialConfig    Config
```
Comment (liggitt) [inline pkg/kubeapiserver/authorizer/reload.go]: TODO: comment what this is and what it is used for

File: pkg/kubeapiserver/authorizer/reload.go [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+	lastLoadedConfig *authzconfig.AuthorizationConfiguration
```
Comment (liggitt) [inline pkg/kubeapiserver/authorizer/reload.go]: drop from this commit since it is unused until the reload impl commit

File: pkg/kubeapiserver/authorizer/reload.go [hunk 6]
```diff
@@ -51,3 +58,85 @@ func (r *reloadableAuthorizerResolver) Authorize(ctx context.Context, a authoriz
...
+			alwaysAllowAuthorizer := authorizerfactory.NewAlwaysAllowAuthorizer()
+			authorizers = append(authorizers, alwaysAllowAuthorizer)
+			ruleResolvers = append(ruleResolvers, alwaysAllowAuthorizer)
+		case authzconfig.AuthorizerType(modes.ModeAlwaysDeny):
+			alwaysDenyAuthorizer := authorizerfactory.NewAlwaysDenyAuthorizer()
+			authorizers = append(authorizers, alwaysDenyAuthorizer)
+			ruleResolvers = append(ruleResolvers, alwaysDenyAuthorizer)
+		case authzconfig.AuthorizerType(modes.ModeABAC):
+			if r.abacAuthorizer == nil {
+				return nil, nil, fmt.Errorf("authorizer type ABAC requested but not available")
```
Comment (liggitt) [inline pkg/kubeapiserver/authorizer/reload.go:113]: improve error message to make this clearer (e.g. "authorizer type ABAC is not allowed if it was not enabled at initial server startup")

(same applies to node and rbac messages)

File: pkg/util/filesystem/watcher.go [hunk 7]
```diff
@@ -87,3 +91,138 @@ func (w *fsnotifyWatcher) Run() {
...
+			}
+
+			// Drain all events before handling
+			drainEvents()
+
+			// Try to re-establish the watcher for events which dropped the existing watch
+			if e.Name == path && (e.Has(fsnotify.Remove) || e.Has(fsnotify.Rename)) {
+				_ = watcher.Remove(path)
+				if err := watcher.Add(path); err != nil {
+					errorHandler(err)
```
Comment (liggitt) [inline pkg/util/filesystem/watcher.go:208]: set `attemptPeriodicRewatch = true` here

File: pkg/util/filesystem/watcher.go [hunk 8]
```diff
@@ -87,3 +91,138 @@ func (w *fsnotifyWatcher) Run() {
...
+
+		case <-t.C:
+			// Prioritize exiting if context is canceled
+			if ctx.Err() != nil {
+				return
+			}
+
+			// Try to re-establish the watcher if we previously got a watch error
+			if attemptPeriodicRewatch {
+				attemptPeriodicRewatch = false
```
Comment (liggitt) [inline pkg/util/filesystem/watcher.go:185]: only set to false if the add call is successful

File: pkg/util/filesystem/watcher.go [hunk 9]
```diff
@@ -87,3 +91,138 @@ func (w *fsnotifyWatcher) Run() {
...
+			eventHandler()
+
+		case e := <-eventsCh:
+			// Prioritize exiting if context is canceled
+			if ctx.Err() != nil {
+				return
+			}
+
+			// Drain all events before handling
+			drainEvents()
```
Comment (liggitt) [inline pkg/util/filesystem/watcher.go:202]: draining will miss Remove / Rename events, don't really need this optimization, drop this

Comment (liggitt) [reply pkg/util/filesystem/watcher.go:202]: document recommended approach (write supporting kubeconfig files, write tmp config file in same dir, atomic move to replace)

File: staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go [hunk 10]
```diff
@@ -0,0 +1,95 @@
+/*
+Copyright 2023 The Kubernetes Authors.
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go:2]: update to 2024 everywhere for new files

File: pkg/kubeapiserver/authorizer/reload.go [hunk 11]
```diff
@@ -0,0 +1,224 @@
...
+	"k8s.io/klog/v2"
+	"k8s.io/kubernetes/pkg/auth/authorizer/abac"
+	"k8s.io/kubernetes/pkg/kubeapiserver/authorizer/modes"
+	"k8s.io/kubernetes/pkg/util/filesystem"
+	"k8s.io/kubernetes/plugin/pkg/auth/authorizer/node"
+	"k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac"
+)
+
+type reloadableAuthorizerResolver struct {
+	initialConfig Config
```
Comment (liggitt) [inline pkg/kubeapiserver/authorizer/reload.go:48]: +       // initialConfig holds the ReloadFile used to initiate background reloading,
+       // and information used to construct webhooks that isn't exposed in the authorization
+       // configuration file (dial function, backoff settings, etc)

**Comment by liggitt** [comment]
hoisting documentation comment to the top level:
> document recommended approach (write supporting kubeconfig files, write tmp config file in same dir, atomic move to replace)

all code comments addressed

File: pkg/kubeapiserver/authorizer/config.go [hunk 12]
```diff
@@ -91,68 +99,103 @@ func (config Config) New() (authorizer.Authorizer, authorizer.RuleResolver, erro
...
+	var allErrors []error
+	seenModes := sets.New[authzconfig.AuthorizerType]()
+	for _, authorizer := range authorizationConfiguration.Authorizers {
+		if string(authorizer.Type) == modes.ModeWebhook {
+			continue
+		}
+		seenModes.Insert(authorizer.Type)
+
+		expectedName := GetNameForAuthorizerMode(string(authorizer.Type))
+		if expectedName != authorizer.Name {
```
Comment (ritazh) [inline pkg/kubeapiserver/authorizer/config.go:186]: is `authorizer.Name` always expected to be lowercase as well?

File: pkg/kubeapiserver/authorizer/reload.go [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+	return r.current.Load().authorizer.Authorize(ctx, a)
+}
+
+func (r *reloadableAuthorizerResolver) RulesFor(user user.Info, namespace string) ([]authorizer.ResourceRuleInfo, []authorizer.NonResourceRuleInfo, bool, error) {
+	return r.current.Load().ruleResolver.RulesFor(user, namespace)
+}
+
+// newForConfig constructs
+func (r *reloadableAuthorizerResolver) newForConfig(authzConfig *authzconfig.AuthorizationConfiguration) (authorizer.Authorizer, authorizer.RuleResolver, error) {
+	if len(authzConfig.Authorizers) == 0 {
```
Comment (ritazh) [inline pkg/kubeapiserver/authorizer/reload.go:84]: could there be an edge case where only a webhook authorizer was specified at startup and it got removed on reload?

File: staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go [hunk 14]
```diff
@@ -0,0 +1,101 @@
...
+}
+
+func RecordAuthorizationConfigAutomaticReloadFailure(apiServerID string) {
+	apiServerIDHash := getHash(apiServerID)
+	authorizationConfigAutomaticReloadsTotal.WithLabelValues("failure", apiServerIDHash).Inc()
+	authorizationConfigAutomaticReloadLastTimestampSeconds.WithLabelValues("failure", apiServerIDHash).SetToCurrentTime()
+}
+
+func RecordAuthorizationConfigAutomaticReloadSuccess(apiServerID string) {
+	apiServerIDHash := getHash(apiServerID)
```
Comment (ritazh) [inline staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go:86]: not sure how much this matters but do we need to getHash every time or can we cache it?

File: pkg/kubeapiserver/authorizer/reload.go (hunk 13 above)
Comment (liggitt) [reply pkg/kubeapiserver/authorizer/reload.go:84]: if they do that, it's invalid... you can't drop all authorizers

File: staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go (hunk 14 above)
Comment (liggitt) [reply staging/src/k8s.io/apiserver/pkg/server/options/authorizationconfig/metrics/metrics.go:86]: since this only fires when we update our metric, I don't think it happens often enough to cache... the hash is super fast

File: pkg/kubeapiserver/authorizer/config.go (hunk 12 above)
Comment (liggitt) [reply pkg/kubeapiserver/authorizer/config.go:186]: yes, that's checked here: https://github.com/liggitt/kubernetes/blob/5dc92ada068cb80a2866cfaa1f9aa760d2524680/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation.go#L452
