### PR TITLE
Return response StatusCode when http probe fail

### LINKED ISSUE #17487: Return StatusCode when running http probes
Now http probes return response body. We probably get event like this:
```
28m         28m        1         nginx            Pod                     spec.containers{nginx}      Started            {kubelet 127.0.0.1}         Started container with docker id fdcc54850322
28m         9s         170       nginx            Pod                     spec.containers{nginx}      Unhealthy          {kubelet 127.0.0.1}         Liveness probe failed: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>

27m       27m       1         nginx     Pod       spec.containers{nginx}   Killing   {kubelet 127.0.0.1}   Killing container with docker id fdcc54850322: pod "nginx_default" container "nginx" is unhealthy, it will be killed and re-created.
```
It's better to include  response code in message instead of response body. Is there case that we need to analyze response body while using probe package?  Or we just don't record response body in event.

### PR DESCRIPTION
**Pull request by jiangyaoguo**
Fixed #17487

Probe failure is caused by StatusCode of response. User will be more interested of StatusCode.

### CODE REVIEW

File: pkg/probe/http/http.go [hunk 1]
```diff
@@ -72,5 +73,5 @@ func DoHTTPProbe(url *url.URL, client HTTPGetInterface) (probe.Result, string, e
 		return probe.Success, body, nil
 	}
 	glog.V(4).Infof("Probe failed for %s, Response: %v", url.String(), *res)
-	return probe.Failure, body, nil
+	return probe.Failure, fmt.Sprintf("Http probe failed with statuscode: %d", res.StatusCode), nil
```
Comment (brendandburns) [inline pkg/probe/http/http.go]: HTTP

**Comment by brendandburns** [comment]
one nit, otherwise this seems ok.

**Comment by brendandburns** [comment]
LGTM.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please
