### PR TITLE
azure: acr: support MSI with preview ACR with AAD auth

### LINKED ISSUE #48980: azure: automatic ACR docker cred integration doesn't work with UseManagedIdentity
/kind bug

The support for Managed Identity Extension in Azure is incompatible with automatic ACR integration. ACR currently only supports authentication with an admin password (which is generally discouraged) and `client_id`/`client_secret` auth with AAD Service Principals.

/sig azure

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**:

The recently added support for Managed Identity in Azure (#48854) was incompatible with automatic ACR docker credential integration (#48980).

This PR resolves that, by leveraging a feature available in Preview regions, on new managed clusters with support for AAD `access_token` authentication.

Notes:
* This includes code copied from [Azure/acr-docker-credential-helper](https://github.com/Azure/acr-docker-credential-helper). I copied the MIT license from that project and added a copyright line for Microsoft on it. (but one of the hack/verify-* scripts requires the Kubernetes copyright header. So there are two copyright headers in the file now...)
* Eventually this should vendor  [Azure/acr-docker-credential-helper](https://github.com/Azure/acr-docker-credential-helper) when it exposes the right functionality.
* This includes a small, non-function-impacting workaround for a temporary service-side bug.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48980

**Special notes for your reviewer**:
Please don't LGTM it without reviewing the `azure_acr_helper.go` file's license header...

**Release note**:
```release-note
azure: acr: support MSI with preview ACR with AAD auth
```

### CODE REVIEW

**Comment by colemickens** [comment]
`/test pull-kubernetes-e2e-gce-etcd3`

**Comment by colemickens** [comment]
cc: @seanknox @brendanburns @anhowe  @jdumars for Azure folks.

cc: @SajayAntony @DavidObando as FYI / for code review.

/sig azure

File: pkg/credentialprovider/azure/azure_acr_helper.go [hunk 1]
```diff
@@ -0,0 +1,339 @@
...
+		var challenge *authDirective
+		if challenge, err = receiveChallengeFromLoginServer(serverAddress); err != nil {
+			// ignore all error when receiving the challenge
+			logrus.Infof("[Azure Login Helper] server %s didn't respond with a valid challenge, reverting to default login...\nerror: %s\n", serverAddress, err)
+			return "", "", nil
+		}
+		refreshToken, err = performTokenExchange(serverAddress, challenge, acrToken.TenantID, acrToken.Credential)
+	}
+
+	return tokenUsername, refreshToken, nil
```
Comment (DavidObando) [inline pkg/credentialprovider/azure/azure_acr_helper.go]: Shouldn't this be `tokenUsernameGUID` instead of `tokenUsername`?

**Comment by DavidObando** [comment]
I just had a minor question in `GetUsernamePassword` but not blocking on it. It looks good to me.

File: pkg/credentialprovider/azure/azure_acr_helper.go (hunk 1 above)
Comment (colemickens) [inline pkg/credentialprovider/azure/azure_acr_helper.go]: Actually, `GetUsernamePassword` is completely dead code. The way it handles the token passed in causes it to think that an AAD Access Token is fine, and it falls through and just returns it rather than performing the exchange.

You'll note in the other file, I call the discover and exchange private methods manually instead of `GetUsernamePassword`. I will remove this code accordingly.

Comment (colemickens) [inline pkg/credentialprovider/azure/azure_acr_helper.go]: (this particular line was copied from the ACR cred helper btw)

Comment (colemickens) [inline pkg/credentialprovider/azure/azure_acr_helper.go]: But yeah, the function in general is a bit confusing. I think the `<token>` thing has more to do with the docker/cred-helper apis rather than the ACR API.

Comment (DavidObando) [inline pkg/credentialprovider/azure/azure_acr_helper.go]: Yeah, it makes sense. LGTM.

File: pkg/credentialprovider/azure/azure_credentials.go [hunk 2]
```diff
@@ -92,37 +94,49 @@ func (a *acrProvider) Enabled() bool {
...
 	}
 
-	servicePrincipalToken, err := azure.GetServicePrincipalToken(a.config, a.environment)
+	a.servicePrincipalToken, err = azure.GetServicePrincipalToken(a.config, a.environment)
 	if err != nil {
 		glog.Errorf("Failed to create service principal token: %v", err)
 		return false
 	}
 
+	glog.V(1).Infof("Creating a registry (control plane) client")
```
Comment (brendandburns) [inline pkg/credentialprovider/azure/azure_credentials.go]: lower the debug level to 4++

Comment (colemickens) [inline pkg/credentialprovider/azure/azure_credentials.go]: That was left over aggressive, unneeded logging. I've simply removed the line now. All log line levels are 4 or greater.
