### PR TITLE
node: e2e: fix device plugin reboot test

### LINKED ISSUE #128443: [Failing Test] [sig-node] [NodeFeature:DevicePlugin] [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)
### Which jobs are flaking?

[pull-kubernetes-node-kubelet-containerd-flaky](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-flaky)

### Which tests are flaking?

E2eNode Suite: [It] [sig-node] Device Plugin [NodeFeature:DevicePlugin] [Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration) [Flaky] 

### Since when has it been flaking?

I've noticed it only once today (Oct 30 2024), but I can see similar failures in other jobs, e.g. https://github.com/kubernetes/kubernetes/issues/128114

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-node-kubelet-containerd-flaky/1851562955540271104

### Reason for failure (if possible)

From the first look the failure could happen because of the bug in the device plugin registration process that prevents it from re-registering after Kubelet reboot. It doesn't happen consistently though.

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:
Clarifies and fixes misleading e2e device manager test which was permafailing roughly since https://github.com/kubernetes/kubernetes/pull/127506 which also included https://github.com/kubernetes/kubernetes/pull/120661, which has the actual change, was merged.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/128443

#### Special notes for your reviewer:
Replaces https://github.com/kubernetes/kubernetes/pull/128870
Alternative to https://github.com/kubernetes/kubernetes/pull/128995

Reviewer please be aware there's quite some history and context to grok the rationale of this change, which I tried my best to distillate in the commit message, which is unfortunately quite long and verbose for this reason.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e_node/device_plugin_test.go [hunk 1]
```diff
@@ -934,7 +934,10 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
 		// simulate node reboot scenario by removing pods using CRI before kubelet is started. In addition to that,
 		// intentionally a scenario is created where after node reboot, application pods requesting devices appear before the device plugin pod
 		// exposing those devices as resource has restarted. The expected behavior is that the application pod fails at admission time.
-		framework.It("Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)", framework.WithFlaky(), func(ctx context.Context) {
+		// NOTE: this is flaky because all pods race to go running when kubelet restarts. So application pod will run with device plugion pod.
+		// It's possible, even though unlikely, that the device plugin pod manages to go running *and* the kubelet reports device healthy
+		// when the application pod enters admission. Hence the flakes.
+		framework.It("Does not keeps device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)", framework.WithFlaky(), func(ctx context.Context) {
```
Comment (bart0sh) [inline test/e2e_node/device_plugin_test.go:940]: typo: keeps -> keep

File: test/e2e_node/device_plugin_test.go [hunk 2]
```diff
@@ -934,7 +934,10 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
 		// simulate node reboot scenario by removing pods using CRI before kubelet is started. In addition to that,
 		// intentionally a scenario is created where after node reboot, application pods requesting devices appear before the device plugin pod
 		// exposing those devices as resource has restarted. The expected behavior is that the application pod fails at admission time.
-		framework.It("Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)", framework.WithFlaky(), func(ctx context.Context) {
+		// NOTE: this is flaky because all pods race to go running when kubelet restarts. So application pod will run with device plugion pod.
+		// It's possible, even though unlikely, that the device plugin pod manages to go running *and* the kubelet reports device healthy
+		// when the application pod enters admission. Hence the flakes.
```
Comment (bart0sh) [inline test/e2e_node/device_plugin_test.go:939]: Is it possible to postpone admission of the application pod until device plugin pod is registered? It would make the whole setup much more predictable.

File: test/e2e_node/device_plugin_test.go [hunk 3]
```diff
@@ -934,7 +934,10 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
 		// simulate node reboot scenario by removing pods using CRI before kubelet is started. In addition to that,
 		// intentionally a scenario is created where after node reboot, application pods requesting devices appear before the device plugin pod
 		// exposing those devices as resource has restarted. The expected behavior is that the application pod fails at admission time.
-		framework.It("Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)", framework.WithFlaky(), func(ctx context.Context) {
+		// NOTE: this is flaky because all pods race to go running when kubelet restarts. So application pod will run with device plugion pod.
```
Comment (likakuli) [inline test/e2e_node/device_plugin_test.go:937]: typo: plugion -> plugin

File: test/e2e_node/device_plugin_test.go (hunk 1 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:940]: thanks, fixed!

File: test/e2e_node/device_plugin_test.go (hunk 2 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:939]: we will need to add the admission retry loop in kubelet, which we talk about since quite some time (e.g. https://github.com/kubernetes/kubernetes/issues/119248 - note this is not limited to device plugins even though device plugins are a prominent use case) and add some form of dependency tracking between pods; or perhaps, something like scheduling gates (https://kubernetes.io/blog/2022/12/26/pod-scheduling-readiness-alpha/) but for kubelet admission: "don't even try admission until this condition is met; retry later" + a timeout.

**Comment by ffromani** [comment]
known failure, change on the way

File: test/e2e_node/device_plugin_test.go [hunk 4]
```diff
@@ -934,7 +934,10 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
 		// simulate node reboot scenario by removing pods using CRI before kubelet is started. In addition to that,
 		// intentionally a scenario is created where after node reboot, application pods requesting devices appear before the device plugin pod
 		// exposing those devices as resource has restarted. The expected behavior is that the application pod fails at admission time.
-		framework.It("Keeps device plugin assignments across node reboots (no pod restart, no device plugin re-registration)", framework.WithFlaky(), func(ctx context.Context) {
+		// NOTE: this is flaky because all pods race to go running when kubelet restarts. So application pod will run with device plugin pod.
+		// It's possible, even though unlikely, that the device plugin pod manages to go running *and* the kubelet reports device healthy
+		// when the application pod enters admission. Hence the flakes.
```
Comment (swatisehgal) [inline test/e2e_node/device_plugin_test.go:939]: Well, I don't think the device plugin should _ever_ re-register here because that can only happen if we delete the `triggerPathFile` and that doesn't happen after node reboot. @bart0sh mentioned [here](https://github.com/kubernetes/kubernetes/issues/128443#issuecomment-2466974720) that the test is consistently failing which aligns with the code I see here. Can you point to the test run where this test passed?

File: test/e2e_node/device_plugin_test.go [hunk 5]
```diff
@@ -985,9 +988,9 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
 				return err
 			}, 30*time.Second, framework.Poll).ShouldNot(gomega.HaveOccurred(), "cannot fetch the compute resource assignment after kubelet restart")
 
-			err, _ = checkPodResourcesAssignment(v1PodResources, pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name, SampleDeviceResourceName, []string{devID1})
-			framework.ExpectNoError(err, "inconsistent device assignment after node reboot")
-
+			// pods in terminal state will still be reported, see https://github.com/kubernetes/kubernetes/issues/119423
+			_, found := checkPodResourcesAssignment(v1PodResources, pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name, SampleDeviceResourceName, []string{})
+			gomega.Expect(found).To(gomega.BeTrueBecause("%s/%s/%s failed admission, should not have devices registered", pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name))
```
Comment (swatisehgal) [inline test/e2e_node/device_plugin_test.go:993]: Here we are verifying that the pod has failed at admission and that it has no device allocated. This contradicts with the above comment that the pod may or may not fail at admission. Can you please clarify?

**Review by swatisehgal — COMMENTED** [review]
Thanks for your deep dive on this topic and trying to capture the rationale in great detail. The overall direction seems okay to me but I have a couple of questions with the  proposed changes:

File: test/e2e_node/device_plugin_test.go (hunk 4 above)
Comment (bart0sh) [reply test/e2e_node/device_plugin_test.go:939]: @swatisehgal Here is my PR that "fixes" the test: https://github.com/kubernetes/kubernetes/pull/128995
You can see this test case passed in the pull-kubernetes-node-kubelet-containerd-flaky job

Comment (bart0sh) [reply test/e2e_node/device_plugin_test.go:939]: @swatisehgal here is a test grid for the job: https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-flaky&width=90
You can see at least 6 green test runs there. if you want to see more, just run `/test pull-kubernetes-node-kubelet-containerd-flaky` in [my PR](https://github.com/kubernetes/kubernetes/pull/128995).

Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:939]: > // NOTE: this is flaky because all pods race to go running when kubelet restarts. So application pod will run with device plugin pod.
		// It's possible, even though unlikely, that the device plugin pod manages to go running *and* the kubelet reports device healthy
		// when the application pod enters admission. Hence the flakes.

@ffromani I think we need to fix the comment here. Like I said before,  the device plugin pod should never go running in this case because the `triggerPathFile` wasn't removed and we should consistently see pod admission failure. 

I am also wondering if we should still mark this test flaky. With all the information we have after the investigation and the fix proposed here we should consistently see the pod failing at admission so makes me question is we should still consider it flaky.

Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go:939]: > @swatisehgal here is a test grid for the job: https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd-flaky&width=90 You can see at least 6 green test runs there. if you want to see more, just run `/test pull-kubernetes-node-kubelet-containerd-flaky` in [my PR](https://github.com/kubernetes/kubernetes/pull/128995).

Thanks @bart0sh for this but I see that we have reached to an agreement about pursuing this PR and have closed https://github.com/kubernetes/kubernetes/pull/128995.

File: test/e2e_node/device_plugin_test.go [hunk 6]
```diff
@@ -985,9 +988,17 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
...
 			}, 30*time.Second, framework.Poll).ShouldNot(gomega.HaveOccurred(), "cannot fetch the compute resource assignment after kubelet restart")
 
-			err, _ = checkPodResourcesAssignment(v1PodResources, pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name, SampleDeviceResourceName, []string{devID1})
-			framework.ExpectNoError(err, "inconsistent device assignment after node reboot")
-
+			// if we got this far, podresources API will now report 2 entries:
+			// - sample device plugin pod, running and doing fine
+			// - our test pod, in failed state. Pods in terminal state will still be reported, see https://github.com/kubernetes/kubernetes/issues/119423
+			// so we care about our test pod, and it will be present in the returned list till 119423 is fixed, but since it failed admission it must not have
+			// any device allocated to it, hance we check for empty device set in the podresources response. So, we check that
```
Comment (swatisehgal) [inline test/e2e_node/device_plugin_test.go:995]: Sorry for nitpicking:
```suggestion
			// any device allocated to it, hence we check for empty device set in the podresources response. So, we check that
```

File: test/e2e_node/device_plugin_test.go [hunk 7]
```diff
@@ -985,9 +988,17 @@ func testDevicePluginNodeReboot(f *framework.Framework, pluginSockDir string) {
...
+			// A. our test pod must be present in the list response *and*
+			// B. it has no devices assigned to it.
+			// anything else is unexpected and thus makes the test fail. Once 119423 is fixed, a better, simpler and more intuitive check will be for the
+			// test pod to not be present in the podresources list response, but till that time we're stuck with this approach.
+			_, found := checkPodResourcesAssignment(v1PodResources, pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name, SampleDeviceResourceName, []string{})
+			gomega.Expect(found).To(gomega.BeTrueBecause("%s/%s/%s failed admission, should not have devices registered", pod1.Namespace, pod1.Name, pod1.Spec.Containers[0].Name))
```
Comment (swatisehgal) [inline test/e2e_node/device_plugin_test.go:1001]: Thanks for adding explanation here!

Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:1001]: happy to help!

**Comment by ffromani** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/125918

File: test/e2e_node/device_plugin_test.go (hunk 4 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:939]: @swatisehgal I think you are right, thanks for pointing it out. The KEP-grade changes I was mentioning are for solving the general problem in production code, where we don't have the option to influence the sequence of events.

File: test/e2e_node/device_plugin_test.go (hunk 6 above)
Comment (ffromani) [reply test/e2e_node/device_plugin_test.go:995]: thanks, fixed

**Comment by swatisehgal** [comment]
Thanks @ffromani for addressing all the review comments. Looks good, the only pending item that requires some clarity is why we are still marking this test flaky. What are the scenarios where we would see unintended results?

**Comment by ffromani** [comment]
> Thanks @ffromani for addressing all the review comments. Looks good, the only pending item that requires some clarity is why we are still marking this test flaky. What are the scenarios where we would see unintended results leading to test failure?

This makes sense, but the flaky label was added prior to this change. I wanted to address failures here :) Do we want to tackle the flakiness/non-flakiness situation in this PR?

**Comment by swatisehgal** [comment]
> > Thanks @ffromani for addressing all the review comments. Looks good, the only pending item that requires some clarity is why we are still marking this test flaky. What are the scenarios where we would see unintended results leading to test failure?
> 
> This makes sense, but the flaky label was added prior to this change. I wanted to address failures here :) Do we want to tackle the flakiness/non-flakiness situation in this PR?

We had an offline discussion about this and agreed that it is worth understanding why this was made flaky ([Here ](https://github.com/kubernetes/kubernetes/pull/123386) is the PR that marked it flaky) and if we should keep it that way.

I think that this test should consistently pass now because we are creating a very controlled scenario where device plugin never re-registers after node-reboot resulting in the application pod **always** failing at admission (and without any device assignments). If that is not the case, I would like to understand why...

**Review by swatisehgal — COMMENTED** [review]
/lgtm

We agreed in the SIG Node CI Meeting (22-01-2015) to monitor [node-kubelet-containerd-flaky](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-flaky) job once this PR is merged to verify that it deflakes the test.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
