### PR TITLE
kubelet: print flags after initializing logging

### LINKED ISSUE #100152: Kubelet logs start with unstructured logs then transition to structured logs
#### What happened:
When starting the Kubelet with ```KUBELET_FLAGS=--logging-format=json hack/local-up-cluster.sh```, the Kubelet begins with unstructured logging and then transitions to structured logging:

```
  Flag --chaos-chance has been deprecated, will be removed in a future version.
  Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
  Flag --cloud-config has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
  Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ f
  I0311 16:53:18.330740  199454 flags.go:59] FLAG: --add-dir-header="false"
  I0311 16:53:18.330802  199454 flags.go:59] FLAG: --address="0.0.0.0"
  I0311 16:53:18.330808  199454 flags.go:59] FLAG: --allowed-unsafe-sysctls="[]"
  I0311 16:53:18.330817  199454 flags.go:59] FLAG: --alsologtostderr="false"
  I0311 16:53:18.330820  199454 flags.go:59] FLAG: --anonymous-auth="true"
  I0311 16:53:18.330825  199454 flags.go:59] FLAG: --application-metrics-count-limit="100"
  I0311 16:53:18.330829  199454 flags.go:59] FLAG: --authentication-token-webhook="false"
  I0311 16:53:18.330832  199454 flags.go:59] FLAG: --authentication-token-webhook-cache-ttl="2m0s"
  I0311 16:53:18.330836  199454 flags.go:59] FLAG: --authorization-mode="AlwaysAllow"
  I0311 16:53:18.330841  199454 flags.go:59] FLAG: --authorization-webhook-cache-authorized-ttl="5m0s"
  I0311 16:53:18.330844  199454 flags.go:59] FLAG: --authorization-webhook-cache-unauthorized-ttl="30s"
  I0311 16:53:18.330848  199454 flags.go:59] FLAG: --azure-container-registry-config=""
  I0311 16:53:18.330851  199454 flags.go:59] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
  I0311 16:53:18.330855  199454 flags.go:59] FLAG: --bootstrap-kubeconfig="/var/run/kubernetes/kubelet.kubeconfig"
  I0311 16:53:18.330859  199454 flags.go:59] FLAG: --cert-dir="/var/lib/kubelet/pki"
  I0311 16:53:18.330862  199454 flags.go:59] FLAG: --cgroup-driver="cgroupfs"
  I0311 16:53:18.330865  199454 flags.go:59] FLAG: --cgroup-root=""
  I0311 16:53:18.330868  199454 flags.go:59] FLAG: --cgroups-per-qos="true"
  I0311 16:53:18.331499  199454 flags.go:59] FLAG: --volume-stats-agg-period="1m0s"
  I0311 16:53:18.331564  199454 feature_gate.go:243] feature gates: &{map[]}
  Flag --chaos-chance has been deprecated, will be removed in a future version.
  Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
  Flag --cloud-config has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
  Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ f
  I0311 16:53:18.334042  199454 feature_gate.go:243] feature gates: &{map[APIServerIdentity:false AllAlpha:false AnyVolumeDataSource:false BalanceAttachedNodeVolumes:false CSIServiceAccountToken:false CSIVolumeHeal
  I0311 16:53:18.334176  199454 feature_gate.go:243] feature gates: &{map[APIServerIdentity:false AllAlpha:false AnyVolumeDataSource:false BalanceAttachedNodeVolumes:false CSIServiceAccountToken:false CSIVolumeHeal
  I0311 16:53:18.855837  199454 mount_linux.go:206] Detected OS with systemd
  {"ts":1615503198855.9631,"msg":"Version: v1.21.0-beta.1.201+82a2a30bc92c5e-dirty\n","v":0}
```

#### What you expected to happen:
I expect the Kubelet to have structured logging through the startup lifecycle.

#### How to reproduce it (as minimally and precisely as possible):
 ```KUBELET_FLAGS=--logging-format=json hack/local-up-cluster.sh```

#### Environment:
- Kubernetes version (use `kubectl version`): master [2eb32e930a30ec66d45ee57795adb06c8d554f18]
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

If done too soon, the klog.V() calls are ignored because the log verbosity
isn't set. In Kubernetes 1.22, the verbosity was set, but not the logging
format.

#### Which issue(s) this PR fixes:
Fixes #100152

#### Special notes for your reviewer:

Output is now:
```
$ go run ./cmd/kubelet -v5 --logging-format=json
Flag --logging-format has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
{"ts":1637218323889.678,"caller":"flag/flags.go:64","msg":"FLAG: --add-dir-header=\"false\"\n","v":1}
{"ts":1637218323889.7053,"caller":"flag/flags.go:64","msg":"FLAG: --address=\"0.0.0.0\"\n","v":1}
{"ts":1637218323889.7168,"caller":"flag/flags.go:64","msg":"FLAG: --allowed-unsafe-sysctls=\"[]\"\n","v":1}
...
```

#### Does this PR introduce a user-facing change?
```release-note
kubelet: the printing of flags at the start of kubelet now uses the final logging configuration
```

### CODE REVIEW

File: cmd/kubelet/app/server.go [hunk 1]
```diff
@@ -266,6 +265,7 @@ HTTP server: The kubelet can also listen for HTTP and respond to a simple API
 				klog.ErrorS(err, "Failed to initialize logging")
 				os.Exit(1)
 			}
+			cliflag.PrintFlags(cleanFlagSet)
```
Comment (pohly) [inline cmd/kubelet/app/server.go:268]: This is the same pattern as in all other commands which use log options and PrintFlags, for example https://github.com/kubernetes/kubernetes/blob/3b9bd229b2fafce16ba056d9c3e7f9acc3fd0bc6/cmd/kube-apiserver/app/server.go#L120-L125

**Review by klueska — APPROVED** [review]
