### PR TITLE
fix waitLoadbalancerDeleted timeout always

### LINKED ISSUE #61100: Cloud Controller Manager tries to create LoadBalancer for services with Type=ClusterIP
/kind bug

**What happened**: CCM tries to create LoadBalancer for services with Type=ClusterIP or NodePort

**What you expected to happen**: CCM doesn't try to create LB for such services

**How to reproduce it (as minimally and precisely as possible)**:
1) setup CCM
2) create service with Type=ClusterIP

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2
- Cloud provider or hardware configuration: OpenStack
- OS (e.g. from /etc/os-release): CoreOS 1632.3.0
- Kernel (e.g. `uname -a`):4.14.19-coreos

Cloud Controller manager is running with following agrs:
```
...
spec:
      containers:
      - command:
        - /usr/local/bin/cloud-controller-manager
        - --address=10.16.50.3
        - --allocate-node-cidrs=false
        - --leader-elect=false
        - --cloud-provider=openstack
        - --cloud-config=/etc/kubernetes/cloud-config.conf
        - --cluster-cidr=10.2.0.0/16
        - --configure-cloud-routes=false
        - --kubeconfig=/etc/kubernetes/cloud-controller-manager.conf
        image: gcr.io/google-containers/cloud-controller-manager-amd64:v1.9.2
...
```

cloud-config.conf:
```
[Global]
auth-url=http://192.168.73.153:5000/v2.0
tenant-name=admin
domain-id=default
username=<user>
password=<pass>
```

> kubectl get svc -n monitoring alertmanager-main

```
NAME                TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)          AGE
alertmanager-main   NodePort   10.3.1.5     <none>        9093:30903/TCP   27d
```

> kubectl get svc -n monitoring grafana
```
NAME      TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
grafana   ClusterIP   10.3.0.131   <none>        3000/TCP   21d
```

In the CCM logs I see:

```{"log":"I0312 16:24:48.642624       1 node_controller.go:85] Sending events to api server.\n","stream":"stderr","time":"2018-03-12T16:24:48.643089252Z"}
{"log":"I0312 16:24:48.647337       1 controllermanager.go:255] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: false.\n","stream":"stderr","time":"2018-03-12T16:24:48.647517444Z"}
{"log":"I0312 16:24:48.648122       1 service_controller.go:187] Starting service controller\n","stream":"stderr","time":"2018-03-12T16:24:48.648239956Z"}
{"log":"I0312 16:24:48.648195       1 controller_utils.go:1019] Waiting for caches to sync for service controller\n","stream":"stderr","time":"2018-03-12T16:24:48.648259562Z"}
{"log":"I0312 16:24:48.648837       1 pvlcontroller.go:106] Starting PersistentVolumeLabelController\n","stream":"stderr","time":"2018-03-12T16:24:48.649897796Z"}
{"log":"I0312 16:24:48.649361       1 controller_utils.go:1019] Waiting for caches to sync for persistent volume label controller\n","stream":"stderr","time":"2018-03-12T16:24:48.649964993Z"}
{"log":"I0312 16:24:48.748516       1 controller_utils.go:1026] Caches are synced for service controller\n","stream":"stderr","time":"2018-03-12T16:24:48.749854521Z"}
{"log":"I0312 16:24:48.748625       1 service_controller.go:654] Detected change in list of current cluster nodes. New node set: [worker-1 worker-2]\n","stream":"stderr","time":"2018-03-12T16:24:48.749897686Z"}
{"log":"I0312 16:24:48.748671       1 service_controller.go:662] Successfully updated 0 out of 0 load balancers to direct traffic to the updated set of nodes\n","stream":"stderr","time":"2018-03-12T16:24:48.749949861Z"}
{"log":"I0312 16:24:48.749810       1 controller_utils.go:1026] Caches are synced for persistent volume label controller\n","stream":"stderr","time":"2018-03-12T16:24:48.750362367Z"}
{"log":"E0312 16:24:48.996276       1 service_controller.go:776] Failed to process service monitoring/alertmanager-main. Retrying in 5s: error getting LB for service monitoring/alertmanager-main: Resource not found\n","stream":"stderr","time":"2018-03-12T16:24:49.024587753Z"}
{"log":"I0312 16:24:48.997261       1 event.go:218] Event(v1.ObjectReference{Kind:\"Service\", Namespace:\"monitoring\", Name:\"alertmanager-main\", UID:\"f0851b20-10d3-11e8-b339-fa163ed187e1\", APIVersion:\"v1\", ResourceVersion:\"1491\", FieldPath:\"\"}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service monitoring/alertmanager-main: Resource not found\n","stream":"stderr","time":"2018-03-12T16:24:49.024668617Z"}
....
{"log":"E0312 16:24:49.985873       1 service_controller.go:776] Failed to process service monitoring/grafana. Retrying in 5s: error getting LB for service monitoring/grafana: Resource not found\n","stream":"stderr","time":"2018-03-12T16:24:49.986813825Z"}
{"log":"I0312 16:24:49.986278       1 event.go:218] Event(v1.ObjectReference{Kind:\"Service\", Namespace:\"monitoring\", Name:\"grafana\", UID:\"ebcd9bf6-1619-11e8-bee2-fa163ed187e1\", APIVersion:\"v1\", ResourceVersion:\"838130\", FieldPath:\"\"}): type: 'Warning' reason: 'CreatingLoadBalancerFailed' Error creating load balancer (will retry): error getting LB for service monitoring/grafana: Resource not found\n","stream":"stderr","time":"2018-03-12T16:24:49.986856153Z"}
```

### PR DESCRIPTION
**Pull request by zetaab**
**What this PR does / why we need it**: waitLoadbalancerDeleted function goes always to timeout because not working check

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zetaab** [comment]
cc @anguslees @dims

**Review by dims — COMMENTED** [review]
LGTM 👍 

let's wait for @anguslees @FengyunPan2 @NickrenREN

File: pkg/cloudprovider/providers/openstack/openstack.go [hunk 1]
```diff
@@ -604,9 +604,10 @@ func (os *OpenStack) LoadBalancer() (cloudprovider.LoadBalancer, bool) {
 	return &LbaasV2{LoadBalancer{network, compute, lb, os.lbOpts}}, true
 }
 
+// this tries to catch 404 error from gophercloud
 func isNotFound(err error) bool {
-	e, ok := err.(*gophercloud.ErrUnexpectedResponseCode)
-	return ok && e.Actual == http.StatusNotFound
+	httpStatus, ok := err.(gophercloud.ErrDefault404)
```
Comment (anguslees) [inline pkg/cloudprovider/providers/openstack/openstack.go]: How have you tested this?   From a quick search of the code, it seems `gophercloud.ErrResourceNotFound` is also used throughout the gophercloud codebase (for cases when the expected resource wasn't found in a list operation, rather than an actual 404 HTTP response).

I think we want this function to be:
```go
func isNotFound(err error) bool {
    switch err.(type) {
    case gophercloud.ErrDefault404: return true
    case gophercloud.ErrResourceNotFound: return true
    }
    return err == ErrNotFound
}
```

.. and tests! It's embarrassing that we merged an update that broke this function without noticing..

Comment (dims) [reply pkg/cloudprovider/providers/openstack/openstack.go]: related ... please look at this too - https://github.com/kubernetes/kubernetes/pull/61002/commits/0da1660653b82d433cd92c6ba2b79df5d51b7bf8

Comment (zetaab) [reply pkg/cloudprovider/providers/openstack/openstack.go]: I think we should use #61002 version to isnotfound function. However, I could still fix that waitLoadbalancerDeleted function timeout thing in this PR

**Comment by zetaab** [comment]
@dims @anguslees @FengyunPan2 this version of isNotFound fix https://github.com/kubernetes/kubernetes/pull/61002 looks better than my. So I decided to remove changes to isNotFound function in this PR. So this PR contains only fix to waitLoadbalancerDeleted check. That function is going always to timeout and return "Resource not found", because the check is broken.

**Review by FengyunPan2 — APPROVED** [review]
