### PR TITLE
kubeadm: enable strict config unmarhaling

### LINKED ISSUE #1066: Improve the validation of unknown fields in configuration objects
a separate bug was discovered here when we found a typo in an etcd config field:
https://github.com/kubernetes/kubeadm/issues/1045
explanation here:
https://github.com/kubernetes/website/pull/9802#issuecomment-411905363

if `localEtcd` is passed instead of `local` the parsing fails silently and we don't get an error from the api-machinery code.

improve the validation for unknown fields.
adding this as a reminder here even if it belongs in another tracker.

@timothysc @bradfitz

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

EDITED

my PR here has the potential to break the whole k8s:
https://github.com/kubernetes/kubernetes/pull/70839

so instead this kubeadm localized PR can be used, which enables YAML field validation outside of codecs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes kubernetes/kubeadm#1066

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: enable strict unmarshaling of YAML configuration files and show warnings for unknown and duplicate fields.
```

/assign @fabriziopandini @rosti
/priority important-longterm
cc @kubernetes/sig-cluster-lifecycle-pr-reviews 
cc @luxas @dims

### CODE REVIEW

File: cmd/kubeadm/app/util/config/initconfiguration.go [hunk 1]
```diff
@@ -344,6 +373,17 @@ func MarshalClusterConfigurationToBytes(clustercfg *kubeadmapi.ClusterConfigurat
...
+
+			// TODO(neolit123)
+			// Work around a bad bug in sigs.k8s.io/yaml where yaml.UnmarshallStrict() does not handle the KubeletConfig
+			// 'resolvConf' field. That's because the JSON name (resolvConf) does not match the name of the struct field
+			// (ResolverConfig).
+			if kind == componentconfigs.KubeletConfigurationKind {
+				contentBytesStr := string(contentBytes)
+				contentBytesStr = strings.Replace(contentBytesStr, "resolvConf: ", "resolverConfig: ", -1)
+				contentBytes = []byte(contentBytesStr)
+			}
```
[the remark this answers is not in the document]
Comment (neolit123) [reply cmd/kubeadm/app/util/config/initconfiguration.go]: looks like the real cause is that we are importing a package that simply does not support the `resolvConf` JSON tag.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go
vs
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go

```
C:\bin\gopath\src\k8s.io\kubernetes\cmd\kubeadm>grep "pkg/kubelet/apis/config" *
 -rnI
app/apis/kubeadm/BUILD:21:        "//pkg/kubelet/apis/config:go_default_library"
,
app/apis/kubeadm/types.go:22:   kubeletconfig "k8s.io/kubernetes/pkg/kubelet/api
s/config"
app/apis/kubeadm/zz_generated.deepcopy.go:27:   config "k8s.io/kubernetes/pkg/ku
belet/apis/config"
app/componentconfigs/BUILD:19:        "//pkg/kubelet/apis/config:go_default_libr
ary",
app/componentconfigs/BUILD:20:        "//pkg/kubelet/apis/config/v1beta1:go_defa
ult_library",
app/componentconfigs/BUILD:21:        "//pkg/kubelet/apis/config/validation:go_d
efault_library",
app/componentconfigs/BUILD:65:        "//pkg/kubelet/apis/config:go_default_libr
ary",
app/componentconfigs/config.go:27:      kubeletconfig "k8s.io/kubernetes/pkg/kub
elet/apis/config"
app/componentconfigs/defaults.go:25:    kubeletconfig "k8s.io/kubernetes/pkg/kub
elet/apis/config"
app/componentconfigs/registrations.go:29:       kubeletconfig "k8s.io/kubernetes
/pkg/kubelet/apis/config"
app/componentconfigs/registrations.go:30:       kubeletconfigv1beta1scheme "k8s.
io/kubernetes/pkg/kubelet/apis/config/v1beta1"
app/componentconfigs/validation.go:22:  kubeletvalidation "k8s.io/kubernetes/pkg
/kubelet/apis/config/validation"
app/componentconfigs/validation_test.go:27:     kubeletconfig "k8s.io/kubernetes
/pkg/kubelet/apis/config"
app/phases/kubelet/BUILD:22:        "//pkg/kubelet/apis/config:go_default_librar
y",
app/phases/kubelet/BUILD:50:        "//pkg/kubelet/apis/config:go_default_librar
y",
app/phases/kubelet/config.go:38:        kubeletconfig "k8s.io/kubernetes/pkg/kub
elet/apis/config"
app/phases/kubelet/config_test.go:29:   kubeletconfig "k8s.io/kubernetes/pkg/kub
elet/apis/config"
```

**Comment by neolit123** [comment]
updated the PR.
the solution is much cleaner now, but comments would be appreciated.

File: cmd/kubeadm/app/componentconfigs/registrations.go [hunk 2]
```diff
@@ -65,6 +71,14 @@ func (r Registration) Unmarshal(fileContent []byte) (runtime.Object, error) {
 	// Do a deepcopy of the empty value so we don't mutate it, which could lead to strange errors
 	obj := r.EmptyValue.DeepCopyObject()
 
+	// Check for duplicate and unknown fields using yaml.UnmarshalStrict().
+	// Use the external config as a target, because external configs can have JSON tags that do not match
+	// the field names - e.g. KubeletConfig's 'resolvConf'
+	objExternal := r.EmptyValueExternal.DeepCopyObject()
```
Comment (liggitt) [inline cmd/kubeadm/app/componentconfigs/registrations.go]: this means only a single external version is supported, right? Doesn't this lose the benefit of supporting multiple versions allowing evolution of the serialized config?

File: cmd/kubeadm/app/componentconfigs/registrations.go [hunk 3]
```diff
@@ -116,12 +132,14 @@ var Known Registrations = map[RegistrationKind]Registration{
...
 		// PAddToSchemeFuncs must use v1alpha1scheme defined in k8s.io/kubernetes, because the schema defined in k8s.io/kubelet doesn't have defaulting functions
-		AddToSchemeFuncs: []AddToSchemeFunc{kubeletconfig.AddToScheme, kubeletconfigv1beta1scheme.AddToScheme},
-		DefaulterFunc:    DefaultKubeletConfiguration,
-		ValidateFunc:     ValidateKubeletConfiguration,
-		EmptyValue:       &kubeletconfig.KubeletConfiguration{},
+		AddToSchemeFuncs:   []AddToSchemeFunc{kubeletconfig.AddToScheme, kubeletconfigv1beta1scheme.AddToScheme},
+		DefaulterFunc:      DefaultKubeletConfiguration,
+		ValidateFunc:       ValidateKubeletConfiguration,
+		EmptyValue:         &kubeletconfig.KubeletConfiguration{},
+		EmptyValueExternal: &kubeletconfigv1beta1.KubeletConfiguration{},
```
Comment (liggitt) [inline cmd/kubeadm/app/componentconfigs/registrations.go]: same here, this approach limits us to a single external version

File: cmd/kubeadm/app/componentconfigs/registrations.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/componentconfigs/registrations.go]: i guess that's true. i can think of a workaround for that using a map.

do you have context of why was the resolvConf "tag vs field name" difference was allowed in the KubeletConfig? this prevents us from unmarshaling into the internal config.

Comment (liggitt) [reply cmd/kubeadm/app/componentconfigs/registrations.go]: internal objects must *never* be used as deserialization targets. even if field names currently match, they are not guaranteed to be stable. That is the point of the external types and json tags.

Comment (neolit123) [reply cmd/kubeadm/app/componentconfigs/registrations.go]: ok, understood.

**Review by fabriziopandini — COMMENTED** [review]
@neolit123 thanks for this PR!
As you are saying this change has potential implications and so I would like it to be discussed at sig level.
My personal first impression about this is that I would like kubeadm to be aligned with kubernetes, and that this change is kind of risky at this stage of the cycle

File: cmd/kubeadm/app/util/config/testdata/validation/invalid_duplicate_field_mastercfg.yaml [hunk 4]
```diff
@@ -0,0 +1,4 @@
+apiVersion: kubeadm.k8s.io/v1beta1
+kind: ClusterConfiguration
```
Comment (rosti) [inline cmd/kubeadm/app/util/config/testdata/validation/invalid_duplicate_field_mastercfg.yaml]: This file should be named `invalid_duplicate_field_clustercfg.yaml`

File: cmd/kubeadm/app/util/config/testdata/validation/invalid_duplicate_field_nodecfg.yaml [hunk 5]
```diff
@@ -0,0 +1,4 @@
+apiVersion: kubeadm.k8s.io/v1beta1
+kind: NodeConfiguration
```
Comment (rosti) [inline cmd/kubeadm/app/util/config/testdata/validation/invalid_duplicate_field_nodecfg.yaml]: `NodeConfiguration` does not exist in v1beta1. This needs to be `JoinConfiguration` and the file should be named `invalid_duplicate_field_joincfg.yaml`.
This is likely passing, because `JoinConfigFileAndDefaultsToInternalConfig` will return an error if there is no `JoinConfiguration` and you simply expect this to fail.

File: cmd/kubeadm/app/util/config/testdata/validation/invalid_unknown_field_mastercfg.yaml [hunk 6]
```diff
@@ -0,0 +1,3 @@
+apiVersion: kubeadm.k8s.io/v1beta1
+kind: ClusterConfiguration
```
Comment (rosti) [inline cmd/kubeadm/app/util/config/testdata/validation/invalid_unknown_field_mastercfg.yaml]: File should be named `invalid_unknown_field_clustercfg.yaml`

File: cmd/kubeadm/app/util/config/testdata/validation/invalid_unknown_field_nodecfg.yaml [hunk 7]
```diff
@@ -0,0 +1,3 @@
+apiVersion: kubeadm.k8s.io/v1beta1
+kind: NodeConfiguration
```
Comment (rosti) [inline cmd/kubeadm/app/util/config/testdata/validation/invalid_unknown_field_nodecfg.yaml]: Again, file should be named `invalid_unknown_field_joincfg.yaml` and kind should be `JoinConfiguration`.

**Review by rosti — CHANGES_REQUESTED** [review]
I like the general idea. I see a couple things however:
- I don't like the idea of imposing this on component configs (Kube-Proxy and Kubelet). Technically speaking, this validation should be done on their side and we should simply invoke their code to pre-validate things. Ideally, this should be done centrally like you suggested in #70839 . I am not convinced, that we should single handedly impose restrictions in other people's configs.
- Missing tests for `InitConfiguration`. We need those in the spirit of `ClusterConfiguration`.

**Comment by neolit123** [comment]
@fabriziopandini 
> My personal first impression about this is that I would like kubeadm to be aligned with kubernetes, and that this change is kind of risky at this stage of the cycle

api machinery will not enable strict unmarshaling for the core codecs.
i don't see it happening in the next +4 cycles.

i will have office hours agenda on this. the change on the kubeadm side will always be risky, due to users having typos or duplicate fields in production YAMLs.

@rosti 
> I don't like the idea of imposing this on component configs (Kube-Proxy and Kubelet). Technically speaking, this validation should be done on their side and we should simply invoke their code to pre-validate things. Ideally, this should be done centrally like you suggested in #70839 . I am not convinced, that we should single handedly impose restrictions in other people's configs.

70839 is not going to happen. i just did it to see how many bogus YAML documents will fail the CI and there are quite a few all over the project.

i do agree about kubeproxy and kubelet not being our responsibility, but the maintainers are not going to do it anytime in the future. given kubeadm is a tool for the end user it feels to me that we have to do it now, even if temporary.

/assign @timothysc 
for comments too please.

File: cmd/kubeadm/app/componentconfigs/registrations.go [hunk 8]
```diff
@@ -30,13 +31,16 @@ import (
...
+	"sigs.k8s.io/yaml"
 )
 
 // AddToSchemeFunc is a function that adds known types and API GroupVersions to a scheme
 type AddToSchemeFunc func(*runtime.Scheme) error
 
 // Registration is an object for registering a Kubernetes ComponentConfig type to be recognized and handled by kubeadm
 type Registration struct {
+	// Kind is a self-mapping for the RegistrationKind of this Registration
+	Kind RegistrationKind
```
Comment (timothysc) [inline cmd/kubeadm/app/componentconfigs/registrations.go]: Isn't this just Meta?  and treat it like other objects?

File: cmd/kubeadm/app/componentconfigs/registrations.go [hunk 9]
```diff
@@ -60,11 +66,24 @@ func (r Registration) Marshal(obj runtime.Object) ([]byte, error) {
...
+	if gvk != nil {
+		version := gvk.Version
+		// Obtain an empty external config object using version mapping.
+		objExternal, ok := r.EmptyValueExternal[version]
+		if !ok {
+			return nil, errors.Errorf("could not obtain an empty external ComponentConfig object (kind:%q, version:%q)", r.Kind, version)
+		}
+		// Check for duplicate and unknown fields using yaml.UnmarshalStrict().
+		if err := yaml.UnmarshalStrict(fileContent, objExternal.DeepCopyObject()); err != nil {
+			return nil, errors.Wrapf(err, "error unmarshaling configuration (kind:%q, version:%q)", r.Kind, version)
```
Comment (timothysc) [inline cmd/kubeadm/app/componentconfigs/registrations.go]: I'd prefer a WARNING, with //TODO to change as we promote configs to GA.

File: cmd/kubeadm/app/util/config/common.go [hunk 10]
```diff
@@ -177,3 +178,12 @@ func ChooseAPIServerBindAddress(bindAddress net.IP) (net.IP, error) {
 	}
 	return ip, nil
 }
+
+// verifyUnmarshalStrict takes a YAML byte slice and an output interface and verifies if the YAML passes
+// a call to yaml.UnmarshalStrict().
+func verifyUnmarshalStrict(bytes []byte, iface interface{}, kind, version string) error {
+	if err := yaml.UnmarshalStrict(bytes, iface); err != nil {
+		return errors.Wrapf(err, "error unmarshaling configuration (kind:%q, version:%q)", kind, version)
```
Comment (timothysc) [inline cmd/kubeadm/app/util/config/common.go]: same comment.

File: cmd/kubeadm/app/util/config/initconfiguration.go [hunk 11]
```diff
@@ -227,6 +228,19 @@ func BytesToInternalConfig(b []byte) (*kubeadmapi.InitConfiguration, error) {
 		if kubeadmutil.GroupVersionKindsHasInitConfiguration(gvk) {
 			// Set initcfg to an empty struct value the deserializer will populate
 			initcfg = &kubeadmapi.InitConfiguration{}
+
+			// Check for duplicate and unknown fields using yaml.UnmarshalStrict()
+			var initcfgTest interface{}
+			switch gvk.Version {
```
Comment (timothysc) [inline cmd/kubeadm/app/util/config/initconfiguration.go]: this seems weird to dupe this in multiple locations when all serialized objects have Meta.

**Review by timothysc — COMMENTED** [review]
We'll 
/hold 
until group consensus.

File: cmd/kubeadm/app/util/config/strict/strict.go [hunk 12]
```diff
@@ -0,0 +1,110 @@
...
+	kubeproxyconfigv1alpha1 "k8s.io/kube-proxy/config/v1alpha1"
+	kubeletconfigv1beta1 "k8s.io/kubelet/config/v1beta1"
+	kubeadmapiv1alpha3 "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1alpha3"
+	kubeadmapiv1beta1 "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1"
+	"k8s.io/kubernetes/cmd/kubeadm/app/componentconfigs"
+	"k8s.io/kubernetes/cmd/kubeadm/app/constants"
+	"sigs.k8s.io/yaml"
+)
+
+var localScheme = runtime.NewScheme()
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/strict/strict.go]: the reason for this localscheme is that i cannot find a way to obtain external empty objects from our schemes such as:
```
&kubeadmapiv1beta1.ClusterConfiguration{}
```
in the case of: `constants.ClusterConfigurationKind`

@fabriziopandini @rosti @timothysc please advise.
is there a magical way to convert from GroupVersionKind to such an external empty object for our already registered config types including component configs?

**Review by rosti — CHANGES_REQUESTED** [review]
I'll do a more thorough review tomorrow. Hope the suggestion works.

File: cmd/kubeadm/app/util/config/strict/strict.go [hunk 13]
```diff
@@ -0,0 +1,110 @@
...
+
+func init() {
```
Comment (timothysc) [inline cmd/kubeadm/app/util/config/strict/strict.go]: I'm super not a fan of naked init().  

I'd prefer a guarded static initialization method (singleton) be called during a startup routine.

File: cmd/kubeadm/app/util/config/strict/strict.go [hunk 14]
```diff
@@ -0,0 +1,110 @@
...
+// VerifyUnmarshalStrict takes a YAML byte slice and a GroupVersionKind and verifies if the YAML
+// schema is known and if it unmarshals with strict mode.
+//
+// TODO(neolit123): The returned error here is currently ignored everywhere and a klog warning is thrown instead.
+// We don't want to turn this into an actual error yet. Eventually this can be controlled with an optional CLI flag.
+func VerifyUnmarshalStrict(bytes []byte, gvk schema.GroupVersionKind) error {
+
+	iface, err := localScheme.New(gvk)
+	if err != nil {
+		klog.Warningf(err.Error())
```
[the remark this answers is not in the document]
Comment (timothysc) [reply cmd/kubeadm/app/util/config/strict/strict.go]: I would add extra test to the log statements.

**Review by timothysc — CHANGES_REQUESTED** [review]

**Review by timothysc — APPROVED** [review]
thx @neolit123 ! 
/lgtm 
/approve

**Review by luxas — COMMENTED** [review]
LGTM, thanks, but some small cleanup notes

File: cmd/kubeadm/app/util/config/strict/strict_test.go [hunk 15]
```diff
@@ -0,0 +1,168 @@
...
+				t.Fatalf("couldn't read test data: %v", err)
+			}
+			gvk := schema.GroupVersionKind{
+				Group:   test.groupVersion.Group,
+				Version: test.groupVersion.Version,
+				Kind:    test.kind,
+			}
+			err = VerifyUnmarshalStrict(bytes, gvk)
+			if (err != nil) != test.expectedError {
+				t.Errorf("expected error %v, got %v, error: %v", err != nil, test.expectedError, err)
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/strict/strict_test.go]: i managed to flip "got" and "expected" here..
