### PR TITLE
vendor: bump runc to 1.0.2

### LINKED ISSUE #104280: Kubelet regularly freeze control groups causing issues further down
#### What happened:

On cgroup v1 when using systemd cgroup driver, kubelet regularly freeze and thaw its control groups, and that is causing issues further down.

#### What you expected to happen:

No freeze

#### How to reproduce it (as minimally and precisely as possible):

Running the command below should never print anything, since freezer.state should always be `THAWED`.

```
# zsh globs
while true ; do cat /sys/fs/cgroup/freezer/kubepods.slice/{*/{*/,},}freezer.state; done | grep FROZEN
```

However, when using master/v1.22.0, this returns `FROZEN` regularly.

When using runc v1.0.0 or earlier, this can cause containers to end in a permanently frozen state. This state is tricky to debug, since no log output is given. To see if an environment is having problems, one can use:

```
# zsh syntax
$ grep -R "FROZEN"  /sys/fs/cgroup/freezer/kubepods.slice/**/freezer.state
# If there is no output, there is no issue. If there is output one or more container are frozen.
```

#### Anything else we need to know?:

More info in https://github.com/kubernetes/kubernetes/issues/102676 and https://github.com/kubernetes/kubernetes/issues/102676.

#### Environment:
- Kubernetes version (use `kubectl version`):
  - `v1.22.0`: introduced in https://github.com/kubernetes/kubernetes/pull/103743
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This bumps runc to 1.0.2. For the complete release notes, see https://github.com/opencontainers/runc/releases/tag/v1.0.2
    
In particular, this fixes the check cgroup v1 systemd manager check
if a container needs to be frozen before Set(), and adds a knob to
skip the check/freeze entirely (used from this PR).

#### Which issue(s) this PR fixes:

Fixes #104280

#### Does this PR introduce a user-facing change?

```release-note
Fixes a regression in 1.22 with occasional pod cgroup freeze when using cgroup v1 and systemd driver.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

### CODE REVIEW

**Comment by kolyshkin** [comment]
@odinuge @liggitt @ehashman PTAL

File: pkg/kubelet/cm/cgroup_manager_linux.go [hunk 1]
```diff
@@ -379,7 +379,8 @@ func getSupportedUnifiedControllers() sets.String {
 
 func (m *cgroupManagerImpl) toResources(resourceConfig *ResourceConfig) *libcontainerconfigs.Resources {
 	resources := &libcontainerconfigs.Resources{
-		SkipDevices: true,
+		SkipDevices:     true,
+		SkipFreezeOnSet: true,
```
Comment (liggitt) [inline pkg/kubelet/cm/cgroup_manager_linux.go:383]: we also set up `libcontainerconfigs.Resources` and set `SkipDevices: true` in these places:

https://github.com/kubernetes/kubernetes/blob/b40d9e8dd5de13a11eb5c56c8fdb7794047764d9/pkg/kubelet/cm/container_manager_linux.go#L397-L399

https://github.com/kubernetes/kubernetes/blob/b40d9e8dd5de13a11eb5c56c8fdb7794047764d9/pkg/kubelet/dockershim/cm/container_manager_linux.go#L125-L129


should those set this new option as well?

Comment (kolyshkin) [reply pkg/kubelet/cm/cgroup_manager_linux.go:383]: No (I should have explained it earlier but didn't know where to).

The reason is, `SkipFreezeOnSet` only makes sense for systemd v1 manager, and is ignored otherwise. In these two places you quoted we use fs[2] manager, i.e. no systemd involved.

In other words, it wouldn't hurt to set it, but it's useless (and may be misleading for those who read the code later).

**Comment by liggitt** [comment]
ok

/approve
for dependency updates

Will leave lgtm to node reviewer. Is it expected that CI job is failing?

**Comment by odinuge** [comment]
/lgtm
/priority critical-urgent
/triage accepted

This needs a release note tho, so holding for that.
/hold

> Is it expected that CI job is failing?

Hmm. Looks like it is flaking.. Strange. It is however running on cgroup v2, and that is still "experimenta" since we doesn't have any good CI signals for it.

/test pull-kubernetes-node-crio-cgrpv2-e2e

And some others, just to check:

/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-node-kubelet-serial

**Comment by mrunalp** [comment]
The crio cgroups v2 test failure is a known problem. @harche Did we have an issue for it?

**Comment by harche** [comment]
> The crio cgroups v2 test failure is a known problem. @harche Did we have an issue for it?

cgroups v1 flaking - https://github.com/kubernetes/kubernetes/issues/104568
cgroups v2 failing - https://github.com/kubernetes/kubernetes/issues/104567
