### PR TITLE
Avoid SidecarContainers code path for non-sidecar pods

### LINKED ISSUE #126440: `SyncPod` may fail to start a pod with init container if `RunContainerError` occurs and SidecarContainers is enabled
### What happened?

It was consistently observed in a testing environment that a node-critical pod failed to start. `Created container setup` event was present but `Started container setup` was missing(`setup` is an init container). Also the following error was present but strangely only once: 
```
init container &Container{Name:setup,...} start failed in pod ... : RunContainerError: error reading from server: EOF
```

After some digging it seemed `m.runtimeService.StartContainer` throwing an error matched the observations above.
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L277-L286

### What did you expect to happen?

Eventually the init container and the pod to start

### How can we reproduce it (as minimally and precisely as possible)?

The following tests in `pkg/kubelet/kuberuntime/kuberuntime_manager_test.go` recreate the problem by `fakeRuntime.InjectError("StartContainer", errors.New("any error"))` and show how depending on `features.SidecarContainers` the behavior is different. When the feature gate is enabled the last init container gets stuck in `CONTAINER_CREATED` and never gets started. Therefore the pod get's stuck and never progresses

```go

func TestASidecarContainersTrue(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, true)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	singleInit(t, expected)
}

func TestASidecarContainersFalse(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, false)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
		{name: "init1", attempt: 1, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	singleInit(t, expected)
}

func singleInit(t *testing.T, finalCRecord []*cRecord) {
	ctx := context.Background()
	fakeRuntime, _, m, err := createTestRuntimeManager()
	assert.NoError(t, err)

	initContainers := []v1.Container{
		{
			Name:            "init1",
			Image:           "init",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	containers := []v1.Container{
		{
			Name:            "foo1",
			Image:           "busybox",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "foo2",
			Image:           "alpine",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID:       "12345678",
			Name:      "foo",
			Namespace: "new",
		},
		Spec: v1.PodSpec{
			Containers:     containers,
			InitContainers: initContainers,
		},
	}

	backOff := flowcontrol.NewBackOff(time.Second, time.Minute)

	// 0. should fail creating init container
	podStatus, err := m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	fakeRuntime.InjectError("StartContainer", errors.New("any error"))
	result := m.SyncPod(context.Background(), pod, podStatus, []v1.Secret{}, backOff)
	err = result.Error()
	fmt.Println(err)
	assert.Error(t, err)
	expected := []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "start only the init container")

	// 2. sync multiple times and test for expected final cRecords
	for _ = range 10 {
		podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
		assert.NoError(t, err)
		result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
		assert.NoError(t, result.Error())
		verifyContainerStatuses(t, fakeRuntime, finalCRecord, "syncing")
	}
}

func TestBSidecarContainersTrue(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, true)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: "init2", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	multipleInits(t, expected)
}

func TestBSidecarContainersFalse(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, false)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: "init2", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
		{name: "init2", attempt: 1, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	multipleInits(t, expected)
}

func multipleInits(t *testing.T, finalCRecord []*cRecord) {
	ctx := context.Background()
	fakeRuntime, _, m, err := createTestRuntimeManager()
	assert.NoError(t, err)

	initContainers := []v1.Container{
		{
			Name:            "init1",
			Image:           "init",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "init2",
			Image:           "init2",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	containers := []v1.Container{
		{
			Name:            "foo1",
			Image:           "busybox",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "foo2",
			Image:           "alpine",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID:       "12345678",
			Name:      "foo",
			Namespace: "new",
		},
		Spec: v1.PodSpec{
			Containers:     containers,
			InitContainers: initContainers,
		},
	}

	backOff := flowcontrol.NewBackOff(time.Second, time.Minute)

	// 1. should  create the firs init container.
	podStatus, err := m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	result := m.SyncPod(context.Background(), pod, podStatus, []v1.Secret{}, backOff)
	assert.NoError(t, result.Error())
	expected := []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "start the first init container")

	// 2. finish first init and fail to start the second
	// Stop init container instance 0.
	sandboxIDs, err := m.getSandboxIDByPodUID(ctx, pod.UID, nil)
	require.NoError(t, err)
	sandboxID := sandboxIDs[0]
	initID0, err := fakeRuntime.GetContainerID(sandboxID, initContainers[0].Name, 0)
	require.NoError(t, err)
	fakeRuntime.StopContainer(ctx, initID0, 0)
	// Simulate StartContainer failure
	fakeRuntime.InjectError("StartContainer", errors.New("any error"))
	// Sync again.
	podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
	assert.Error(t, result.Error())
	expected = []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: initContainers[1].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "finish first init and fail to start the second")

	// sync multiple times and test for expected final cRecords
	for _ = range 10 {
		podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
		assert.NoError(t, err)
		result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
		assert.NoError(t, result.Error())
		verifyContainerStatuses(t, fakeRuntime, finalCRecord, "syncing")
	}
}
```

### Anything else we need to know?

The problem seems to stem from:
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1015-L1018

There `kubecontainer.ContainerStateCreated` case get's skipped and the created container is expected to get started by the previous one by the following lines
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1122
or
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1171
But the provided tests show that this does not happen. Also if there is only one init container with `kubecontainer.ContainerStateCreated` the following logic should execute but won't
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1215-L1219
because in this case this get's executed
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1209-L1212

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?
/kind regression

#### What this PR does / why we need it:

This fixes a regression in the SidecarContainers feature by minimizing the impact of the new code path. Use the old code path for pods without restartable init containers, and apply the new code path only to pods with restartable init containers.

#### Which issue(s) this PR fixes:

Fixes #

xref: #126440 

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression in 1.29+ default configurations, where regular init containers may fail to start due to a temporary container runtime failure.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @liggitt @SergeyKanzhelev 
/priority critical-urgent

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 1]
```diff
@@ -832,7 +832,7 @@ func (m *kubeGenericRuntimeManager) killContainersWithSyncResult(ctx context.Con
 	wg.Add(len(runningPod.Containers))
 	var termOrdering *terminationOrdering
 	// we only care about container termination ordering if the sidecars feature is enabled
-	if utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) {
+	if types.HasRestartableInitContainer(pod) {
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:835]: slight preference for 

```go
if utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) && types.HasRestartableInitContainer(pod) {
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -862,7 +862,7 @@ func (m *kubeGenericRuntimeManager) computePodActions(ctx context.Context, pod *
 		// is done and there is no container to start.
 		if len(containersToStart) == 0 {
 			hasInitialized := false
-			if !utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) {
+			if !types.HasRestartableInitContainer(pod) {
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:865]: compute once at the top of computePodActions:
```go
handleInitContainerSidecars := utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) && types.HasRestartableInitContainer(pod)
```

then use that throughout `computePodActions`

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -1285,7 +1285,7 @@ func (m *kubeGenericRuntimeManager) SyncPod(ctx context.Context, pod *v1.Pod, po
 		start(ctx, "ephemeral container", metrics.EphemeralContainer, ephemeralContainerStartSpec(&pod.Spec.EphemeralContainers[idx]))
 	}
 
-	if !utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) {
+	if !types.HasRestartableInitContainer(pod) {
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1288]: slight preference for 

```go
if !(utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) && types.HasRestartableInitContainer(pod)) {
```

File: pkg/kubelet/types/pod_update.go [hunk 4]
```diff
@@ -202,3 +204,17 @@ func IsRestartableInitContainer(initContainer *v1.Container) bool {
 
 	return *initContainer.RestartPolicy == v1.ContainerRestartPolicyAlways
 }
+
+// HasRestartableInitContainer returns true if the pod has any restartable init
+// container and the feature gate is enabled.
+func HasRestartableInitContainer(pod *v1.Pod) bool {
+	if !utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) {
```
Comment (liggitt) [inline pkg/kubelet/types/pod_update.go:211]: Making this include the feature gate check is a little confusing (IsRestartableInitContainer doesn't consider the feature enablement) and could lead to callers thinking a pod doesn't have sidecars when it does.

I think it's better to move the feature gate check to the call sites (there's only three).

**Comment by SergeyKanzhelev** [comment]
> Fixes https://github.com/kubernetes/kubernetes/issues/126440

Please just mention the bug without saying "Fixes", otherwise it will close the  bug and we still want to fix the new code path

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:835]: +1 for being more explicit here

**Comment by pacoxu** [comment]
/cc @kubernetes/sig-node-leads 
as a critical regression

**Comment by pacoxu** [comment]
As Sidecar feature was promoted to beta in v1.29, we would backport this to v1.29-v1.31 later.

BTW, how to add a test for this? I met a similar case in https://github.com/kubernetes/kubernetes/pull/122778 and https://github.com/kubernetes/kubernetes/pull/122778/#discussion_r1737681804 provide a way to test it locally using a customized containerd.

File: pkg/kubelet/types/pod_update.go (hunk 4 above)
Comment (gjkim42) [reply pkg/kubelet/types/pod_update.go]: done.

**Comment by gjkim42** [comment]
> BTW, how to add a test for this? I met a similar case in #122778 and [discussion_r1737681804](https://github.com/kubernetes/kubernetes/pull/122778/#discussion_r1737681804) provide a way to test it locally using a customized containerd, and in that case, we make a `startContainer` timeout.

Thanks, will test it manually first.

Not sure we want the customized container runtime for the CI though.

**Comment by gjkim42** [comment]
manually tested with customized containerd (that fails to start container at first after 1 min)

```
...
NAME        READY   STATUS     RESTARTS   AGE
fixed-k8s   0/1     Init:0/1   0          56s
k8s-1.30    0/1     Init:0/1   0          56s
NAME        READY   STATUS     RESTARTS   AGE
fixed-k8s   0/1     Init:0/1   0          58s
k8s-1.30    0/1     Init:0/1   0          58s
NAME        READY   STATUS     RESTARTS   AGE
fixed-k8s   0/1     Init:0/1   0          60s
k8s-1.30    0/1     Init:0/1   0          60s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:RunContainerError   0          63s
k8s-1.30    0/1     Init:RunContainerError   0          63s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:0/1                 1          65s
k8s-1.30    0/1     Init:RunContainerError   0          65s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:0/1                 1          67s
k8s-1.30    0/1     Init:RunContainerError   0          67s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:0/1                 1          69s
k8s-1.30    0/1     Init:RunContainerError   0          69s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:0/1                 1          71s
k8s-1.30    0/1     Init:RunContainerError   0          71s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     Init:0/1                 1          73s
k8s-1.30    0/1     Init:RunContainerError   0          73s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   0/1     PodInitializing          0          75s
k8s-1.30    0/1     Init:RunContainerError   0          75s
NAME        READY   STATUS                   RESTARTS   AGE
fixed-k8s   1/1     Running                  0          77s
k8s-1.30    0/1     Init:RunContainerError   0          77s
...
```
```
$ k get nodes
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   28m   v1.32.0-alpha.0.498+fcf616daa7f18a-dirty
kind-worker          Ready    <none>          28m   v1.30.4
kind-worker2         Ready    <none>          28m   v1.32.0-alpha.0.498+fcf616daa7f18a-dirty
```

**Comment by liggitt** [comment]
This change lgtm. Is there a test we can add that reproduces https://github.com/kubernetes/kubernetes/issues/126440 that shows this resolves the issue?

**Comment by gjkim42** [comment]
> This change lgtm. Is there a test we can add that reproduces #126440 that shows this resolves the issue?

added a unit test for that.
Since it is difficult to reproduce it in the e2e test, I tested it manually.
https://github.com/kubernetes/kubernetes/pull/127162#issuecomment-2333839460

**Review by SergeyKanzhelev — APPROVED** [review]
/unhold
/approve
/lgtm

**Comment by liggitt** [comment]
thanks, can you cherry-pick this to 1.29, 1.30, and 1.31?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 3 above)
Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1290]: I just realized that this was a bit bad decision.

If we didn't check types.HasRestartableInitContainer(pod) here, we would remove this code path safely while removing the feature gate.

https://github.com/kubernetes/kubernetes/pull/129731/commits/2cb6899b31a33a4ce36ecc8694af63a1bde60db1

@liggitt 

Do you have a good idea to remove this redundant code path (logically it is a subset of the else code path.)
