### PR TITLE
Fixing scheduling latency metrics

### LINKED ISSUE #63493: Scheduler metrics not captured properly in density test
File:  test/e2e/scalability/density.go

When running e2e performance test, the density test output scheduling latency as follows:
```
May  8 00:55:23.397: INFO: Printing summary: SchedulingLatency
May  8 00:55:23.397: INFO: SchedulingLatency JSON
{
  "scheduling": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  },
  "binding": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  },
  "total": {
    "Perc50": 0,
    "Perc90": 0,
    "Perc99": 0,
    "Perc100": 0
  }
}
```

Why are these values zero? Is it because of not reseting scheduler metrics? 
The codes:
```
		// Verify scheduler metrics.
		// TODO: Reset metrics at the beginning of the test.
		// We should do something similar to how we do it for APIserver.
		latency, err := framework.VerifySchedulerLatency(c)
		framework.ExpectNoError(err)
		if err == nil {
			summaries = append(summaries, latency)
		}
		summaries = append(summaries, testPhaseDurations)
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by krzysied**
**What this PR does / why we need it**:
Allows to measure and to display scheduling latency metrics during tests. Provides new functionality of resetting scheduler latency metrics.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63493

**Special notes for your reviewer**:
E2eSchedulingLatency, SchedulingAlgorithmLatency, BindingLatency are now available 
as subtypes of OperationLatency.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-scheduler/app/server.go [hunk 1]
```diff
@@ -225,7 +227,16 @@ func buildHandlerChain(handler http.Handler, authn authenticator.Request, authz
 func newMetricsHandler(config *componentconfig.KubeSchedulerConfiguration) http.Handler {
 	pathRecorderMux := mux.NewPathRecorderMux("kube-scheduler")
 	configz.InstallHandler(pathRecorderMux)
-	pathRecorderMux.Handle("/metrics", prometheus.Handler())
+	//metrics.Register()
```
Comment (shyamjvs) [inline cmd/kube-scheduler/app/server.go]: Could you remove this commented code?

File: cmd/kube-scheduler/app/server.go [hunk 2]
```diff
@@ -243,7 +254,15 @@ func newHealthzHandler(config *componentconfig.KubeSchedulerConfiguration, separ
 	healthz.InstallHandler(pathRecorderMux)
 	if !separateMetrics {
 		configz.InstallHandler(pathRecorderMux)
-		pathRecorderMux.Handle("/metrics", prometheus.Handler())
+		defaultMetricsHandler := prometheus.Handler().ServeHTTP
```
Comment (shyamjvs) [inline cmd/kube-scheduler/app/server.go]: Instead of duplicating the same code as above, could you move this part into a separate function?
Like here - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/routes/metrics.go#L44

File: pkg/scheduler/metrics/metrics.go [hunk 3]
```diff
@@ -25,23 +25,26 @@ import (
 
 const schedulerSubsystem = "scheduler"
 
+const BindingType = "binding"
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: Please put these 3 values within a single const block.

File: pkg/scheduler/metrics/metrics.go [hunk 4]
```diff
@@ -25,23 +25,26 @@ import (
...
+const SchedulingAlgorithmType ="scheduling_algorithm"
+const E2eSchedulingType = "e2e_scheduling"
+
+type resettableCollector interface {
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: I don't think this should be called a `resettableCollector` (because it's just a collector, and not all of them are resettable). Can't you directly just use a prometheus.Collector?

File: pkg/scheduler/metrics/metrics.go [hunk 5]
```diff
@@ -25,23 +25,26 @@ import (
...
-		prometheus.HistogramOpts{
-			Subsystem: schedulerSubsystem,
-			Name:      "e2e_scheduling_latency_microseconds",
-			Help:      "E2e scheduling latency (scheduling algorithm + binding)",
-			Buckets:   prometheus.ExponentialBuckets(1000, 2, 15),
-		},
-	)
-	SchedulingAlgorithmLatency = prometheus.NewHistogram(
-		prometheus.HistogramOpts{
+	OperationLatency = prometheus.NewSummaryVec(
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: Could you name this variable as `SchedulingLatency` instead? That'll make it more clearer.

File: pkg/scheduler/metrics/metrics.go [hunk 6]
```diff
@@ -25,23 +25,26 @@ import (
...
+		prometheus.SummaryOpts{
 			Subsystem: schedulerSubsystem,
-			Name:      "scheduling_algorithm_latency_microseconds",
-			Help:      "Scheduling algorithm latency",
-			Buckets:   prometheus.ExponentialBuckets(1000, 2, 15),
+			Name: "operation_latency_microseconds",
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: Could you rename this to `scheduling_latencies_summary` instead? (to keep up with the naming convention used for apiserver)

File: pkg/scheduler/metrics/metrics.go [hunk 7]
```diff
@@ -25,23 +25,26 @@ import (
...
+			Help: "operation latency",
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: I'd suggest writing something more descriptive in the Help string. Like "Scheduling latency in microseconds split by sub-parts of the scheduling operation".

File: pkg/scheduler/metrics/metrics.go [hunk 8]
```diff
@@ -25,23 +25,26 @@ import (
...
+			// Make the sliding window of 5h.
+			// TODO: The value for this should be based on our SLI definition (medium term).
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: Can you change:
our -> some
medium -> long

File: pkg/scheduler/metrics/metrics.go [hunk 9]
```diff
@@ -25,23 +25,26 @@ import (
...
+			MaxAge: 5 * time.Hour,
 		},
+		[]string{"operationType"},
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: Just `operation` is enough.

File: test/e2e/framework/metrics_util.go [hunk 10]
```diff
@@ -488,13 +488,17 @@ func getSchedulingLatency(c clientset.Interface) (*SchedulingLatency, error) {
...
 	for _, sample := range samples {
+		if sample.Metric[model.MetricNameLabel] != "scheduler_operation_latency_microseconds" {
+			continue
+		}
+
 		var metric *LatencyMetric = nil
-		switch sample.Metric[model.MetricNameLabel] {
-		case "scheduler_scheduling_algorithm_latency_microseconds":
+		switch sample.Metric["operationType"] {
+		case "scheduling_algorithm":
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: Please replace these hard-coded strings with their corresponding const vars you defined above.

File: test/e2e/framework/metrics_util.go [hunk 11]
```diff
@@ -520,6 +524,53 @@ func VerifySchedulerLatency(c clientset.Interface) (*SchedulingLatency, error) {
 	return latency, nil
 }
 
+func ResetSchedulerLatency(c clientset.Interface) error {
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: Rename this to `ResetSchedulerLatencyMetrics`?

File: cmd/kube-scheduler/app/server.go (hunk 2 above)
Comment (krzysied) [reply cmd/kube-scheduler/app/server.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 3 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 4 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 5 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 6 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 7 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 8 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 9 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: test/e2e/framework/metrics_util.go (hunk 10 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: done

File: test/e2e/framework/metrics_util.go (hunk 11 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: done

File: pkg/scheduler/metrics/metrics.go [hunk 12]
```diff
@@ -23,90 +23,90 @@ import (
 	"github.com/prometheus/client_golang/prometheus"
 )
 
-const schedulerSubsystem = "scheduler"
+const (
+	SchedulerSubsystem = "scheduler"
+	SchedulingLatencyName = "scheduling_latencies_summary"
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: I don't think it's too useful to have this const. Maybe just put the string directly inside the metric definition (like other metrics)?

File: pkg/scheduler/metrics/metrics.go [hunk 13]
```diff
@@ -23,90 +23,90 @@ import (
...
+
+	OperationLabel = "opertion"
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: operation

File: test/e2e/framework/metrics_util.go [hunk 14]
```diff
@@ -130,6 +131,8 @@ func (m *MetricsForE2E) SummaryKind() string {
 	return "MetricsForE2E"
 }
 
+var SchedulingLatencyMetricName = model.LabelValue(schedulerMetric.SchedulerSubsystem + "_" + schedulerMetric.SchedulingLatencyName)
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: Maybe it'll be cleaner to have sth similar to apiserver like this:

```
var InterestingSchedulerMetrics = []string{
  "scheduler_whatever"
}
```

File: test/e2e/framework/metrics_util.go [hunk 15]
```diff
@@ -521,6 +528,53 @@ func VerifySchedulerLatency(c clientset.Interface) (*SchedulingMetrics, error) {
 	return latency, nil
 }
 
+func ResetSchedulerLatencyMetrics(c clientset.Interface) error {
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: I see some overlap of this function with `getSchedulingLatency()`. Can we somehow unify them?

File: test/e2e/scalability/density.go [hunk 16]
```diff
@@ -442,6 +440,7 @@ var _ = SIGDescribe("Density", func() {
 
 		uuid = string(utiluuid.NewUUID())
 
+		framework.ExpectNoError(framework.ResetSchedulerLatencyMetrics(c))
```
Comment (shyamjvs) [inline test/e2e/scalability/density.go]: Actually, let's name this function as `ResetSchedulerMetrics` (as we may expand it in future to reset more metrics than just latency).

File: pkg/scheduler/metrics/metrics.go (hunk 13 above)
Comment (shyamjvs) [reply pkg/scheduler/metrics/metrics.go]: Also can we rename this variable to `OperationType` and change the below ones to simply `Binding`, `SchedulingAlgorithm`, etc? Will make the meaning more clearer imo.

**Comment by shyamjvs** [comment]
That looks much cleaner now. I've left a last bunch of comments. Will lgtm once those are addressed.

File: pkg/scheduler/metrics/metrics.go (hunk 12 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: Why do we want to have operation types as a consts and and metric name as a string? Shouldn't we have coherent style - all strings or all consts?

File: test/e2e/framework/metrics_util.go (hunk 14 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: The problem is that scheduler latency metric has a special handling (other metrics will have different structure/labels). Always at some point you will need to verify if name == SCHEDULER_METRIC_NAME. That's why I prefer having variable to having value in array.

File: pkg/scheduler/metrics/metrics.go (hunk 12 above)
Comment (shyamjvs) [reply pkg/scheduler/metrics/metrics.go]: Yes, you have a valid point there.

So ideally we should make all hard-coded strings in files as global constants (so we only define the 'real' string once and later on only have references to it). However, moving too many things to global consts makes the file larger and harder to read. So the rule I'm usually following is to make a string const only if it's referenced enough times (3-4) in the codebase, so it's worth it. But this is subjective :)

File: test/e2e/framework/metrics_util.go (hunk 14 above)
Comment (shyamjvs) [reply test/e2e/framework/metrics_util.go]: Yes. However, isn't it the same for apiserver metrics too?

Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: I don't think so. The apiserver e2e metric are group of metrics with the some structure, so none of those metric requires special handling.
The apiserver latency metrics are more similar to scheduler latency metric. However in this case, metric names are compared to explicit strings.

File: test/e2e/framework/metrics_util.go [hunk 17]
```diff
@@ -521,6 +539,16 @@ func VerifySchedulerLatency(c clientset.Interface) (*SchedulingMetrics, error) {
 	return latency, nil
 }
 
+func ResetSchedulerMetrics(c clientset.Interface) error {
+	responseText, err := sendRestRequestSchedulingLatency(c, "DELETE")
+
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: Remove this newline

File: test/e2e/framework/metrics_util.go [hunk 18]
```diff
@@ -521,6 +539,16 @@ func VerifySchedulerLatency(c clientset.Interface) (*SchedulingMetrics, error) {
...
+	if err != nil || responseText != "metrics reset\n" {
+		return fmt.Errorf("Unexpected response: %q", responseText)
+	}
+
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: remove line

File: test/e2e/framework/metrics_util.go [hunk 19]
```diff
@@ -439,27 +442,29 @@ func getMetrics(c clientset.Interface) (string, error) {
 	return string(body), nil
 }
 
-// Retrieves scheduler latency metrics.
-func getSchedulingLatency(c clientset.Interface) (*SchedulingMetrics, error) {
-	result := SchedulingMetrics{}
+// Sends REST request to kube scheduler metrics
+func sendRestRequestSchedulingLatency(c clientset.Interface, op string) (string, error) {
```
Comment (shyamjvs) [inline test/e2e/framework/metrics_util.go]: Rename to sendRestRequestToScheduler

File: test/e2e/framework/metrics_util.go (hunk 17 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: done

File: test/e2e/framework/metrics_util.go (hunk 18 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: done

File: test/e2e/framework/metrics_util.go (hunk 19 above)
Comment (krzysied) [reply test/e2e/framework/metrics_util.go]: done

**Comment by shyamjvs** [comment]
/lgtm
/retest

Thanks for fixing!

File: pkg/scheduler/metrics/metrics.go [hunk 20]
```diff
@@ -23,90 +23,97 @@ import (
...
-const schedulerSubsystem = "scheduler"
+const (
+	// SchedulerSubsystem - subsystem name used by scheduler
+	SchedulerSubsystem = "scheduler"
+	// SchedulingLatencyName - scheduler latency metric name
+	SchedulingLatencyName = "scheduling_latencies_summary"
+
+	// OperationLabel - operatation label name
+	OperationLabel = "operation"
+	// Binding - binding operation lebal value
```
Comment (wojtek-t) [inline pkg/scheduler/metrics/metrics.go]: s/lebal/label/

File: pkg/scheduler/metrics/metrics.go [hunk 21]
```diff
@@ -23,90 +23,97 @@ import (
...
 )
 
-const schedulerSubsystem = "scheduler"
+const (
+	// SchedulerSubsystem - subsystem name used by scheduler
+	SchedulerSubsystem = "scheduler"
+	// SchedulingLatencyName - scheduler latency metric name
+	SchedulingLatencyName = "scheduling_latencies_summary"
+
+	// OperationLabel - operatation label name
```
Comment (shyamjvs) [inline pkg/scheduler/metrics/metrics.go]: -> operation

File: pkg/scheduler/metrics/metrics.go (hunk 20 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

File: pkg/scheduler/metrics/metrics.go (hunk 21 above)
Comment (krzysied) [reply pkg/scheduler/metrics/metrics.go]: done

**Comment by shyamjvs** [comment]
These metrics are important for our tests. @jberkus could you please approve for milestone?

**Comment by wojtek-t** [comment]
Approving as scalability sig lead

File: pkg/scheduler/metrics/metrics.go [hunk 22]
```diff
@@ -23,90 +23,97 @@ import (
 	"github.com/prometheus/client_golang/prometheus"
 )
 
-const schedulerSubsystem = "scheduler"
+const (
+	// SchedulerSubsystem - subsystem name used by scheduler
+	SchedulerSubsystem = "scheduler"
```
Comment (bsalamat) [inline pkg/scheduler/metrics/metrics.go]: Renaming metrics is a breaking change. It is not backward and is going to break monitoring systems that rely on these metrics. This PR should be reverted.

Comment (shyamjvs) [reply pkg/scheduler/metrics/metrics.go]: Yeah, that's a valid concern and also the option I was initially suggesting in https://github.com/kubernetes/kubernetes/issues/63493#issuecomment-389904406. I've cc'd there sig-scheduling and you - following lazy consensus since there weren't any objections :)

So, what do you think about re-adding the old metric alongside the new one (instead of replacing it)?

Comment (wojtek-t) [reply pkg/scheduler/metrics/metrics.go]: Wasn't this metric broken anyway?

Comment (shyamjvs) [reply pkg/scheduler/metrics/metrics.go]: I don't think so.. IIUC we were just not capturing the values properly in our test framework (which expects summary instead of histogram).

Comment (misterikkit) [reply pkg/scheduler/metrics/metrics.go]: If we're going to add "aliases" for metrics, I think we should make more of a push toward prometheus best practices. The various histograms in this file and their relationships are a bit confusing.

Comment (bsalamat) [reply pkg/scheduler/metrics/metrics.go]: I agree with @misterikkit. Some of these names were not following Prometheus best practices. The new ones introduces in this PR are not following those best practices either. We should definitely keep the old ones for backward compatibility and maybe add new aliases based on the best practices.

**Comment by bsalamat** [comment]
@krzysied Did you have a chance to revert the changes to the metrics names?

**Comment by shyamjvs** [comment]
@bsalamat @misterikkit Does the following sgty:

- Re-introduce the old metrics (which are histogram-type)
- Keep the new metrics (which are summary-type)

And to clarify, this is not a question of "aliases" - the new metrics aren't just a name change, they're introducing summary-type metrics (like mentioned above). And the reason is we want to have accurate percentiles of scheduling latencies for measuring the performance better (some context here - https://github.com/kubernetes/kubernetes/issues/63493#issuecomment-389904406)

And wrt naming the new metrics, sure we can change the name.. that's not a problem. Could you point us to what best practices you're referring?

**Comment by shyamjvs** [comment]
@krzysied can make the changes based on what we agree above.

**Comment by misterikkit** [comment]
> the new metrics aren't just a name change, they're introducing summary-type metrics

Ahh, I failed to notice the distinction. I guess the sliding window is a more useful view of performance over the last N minutes, but is that better for observing health in a live cluster?

> And wrt naming the new metrics, sure we can change the name.. that's not a problem. Could you point us to what best practices you're referring?

https://prometheus.io/docs/practices/naming/

**Comment by krzysied** [comment]
I've created the PR #64838 that re-introduces old metrics and changes new one to satisfy prometheus best practice.

@bsalamat @misterikkit Could you please take a look and give an option as to whether this change looks good to you?
