### PR TITLE
Fix a regression introduced lately: When any given PodInfraContainer on ...

### LINKED ISSUE #5373: Manually killing one POD container restarts all pods
Observed in testing somehting unrelated - @dchen1107 prio

We need a test that captures this - we can't let this slip through,  Maybe same as #5372?

### PR DESCRIPTION
**Pull request by dchen1107**
...a node

is killed, kubelet kills all remaining containers no matter which pod that
container belongs to.

Fixed #5373

Also updated unittest to reproduce the issue without the fix.

### CODE REVIEW

**Comment by vmarmol** [comment]
Needs rebase btw :)

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1176,12 +1176,13 @@ func (kl *Kubelet) syncPod(pod *api.BoundPod, containersInPod dockertools.Docker
...
 		if count > 0 {
-			// Re-list everything, otherwise we'll think we're ok.
-			containersInPod, err = dockertools.GetKubeletDockerContainers(kl.dockerClient, false)
+			// Re-list all containers in a given pod, otherwise we'll think we're ok.
+			containers, err := dockertools.GetKubeletDockerContainers(kl.dockerClient, false)
 			if err != nil {
 				glog.Errorf("Error listing containers %#v", containersInPod)
 				return err
 			}
+			containersInPod = containers.FindContainersByPod(uid, podFullName)
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: Wow can't believe I missed that...good catch.

**Comment by vmarmol** [comment]
LGTM, just needs a rebase

**Comment by dchen1107** [comment]
Just verified using the same unittest generated here, earlier refactory of SyncPod introduced this regression, then later one just fixed it. :-) and :-( 

Looks like we only need unittests to avoid future breakage. I will double check it against a real cluster and update the PR.

**Comment by vmarmol** [comment]
haha sorry for the churn, the latest refactoring makes things more concrete and easier to follow.

**Comment by dchen1107** [comment]
Ok, run tests against the read cluster, the regression is fixed. Updated cl with unnitests only.

**Comment by vmarmol** [comment]
LGTM, thanks @dchen1107! Will merge on green.

**Comment by thockin** [comment]
I dont get it - this is a no-op change?

**Comment by vmarmol** [comment]
@thockin the real fix was done in #5022 this just adds a test.

**Comment by dchen1107** [comment]
@thockin The initial PR I sent out does contain a proper fix and unittest reproducing the issue. The regression was introduced by a refactory lately which passes all running k8s containers after killing PodInfraContainers and deciding to kill rest in a given Pod. But at the same day, another refactory code was introduced which fix the initial issue. The only unittest is required then.
