### PR TITLE
kube-proxy should log the payload when iptables-restore fails

### LINKED ISSUE #104234: kube-proxy should log the payload when iptables-restore fails
my k8s cluster version is 1.17.x 。this cluster has 10 nodes.one master 。
only  2 nodes get problem.
```go
E0809 05:37:21.484590       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 05:37:21.484752       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:14:37.485082       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 53 failed
)
I0809 06:14:37.485205       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:45:24.676775       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 53 failed
)
I0809 06:45:24.676868       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:45:38.141258       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 52 failed
)
I0809 06:45:38.141408       1 proxier.go:779] Sync failed; retrying in 30s
E0809 07:32:42.616867       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 52 failed
)
I0809 07:32:42.617009       1 proxier.go:779] Sync failed; retrying in 30s
E0809 07:42:13.864568       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 07:42:13.864698       1 proxier.go:779] Sync failed; retrying in 30s
E0809 08:00:20.842378       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 08:00:20.842502       1 proxier.go:779] Sync failed; retrying in 30s
E0809 08:06:32.562513       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 08:06:32.562665       1 proxier.go:779] Sync failed; retrying in 30s
```
it make my svc sometime can use。sometime can timeout。
what can i do can resolve this problem ? 
this 2 node's svc is nodeportType 。

### PR DESCRIPTION
**Pull request by cyclinder**
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
when the `kube-proxy` execution `iptables-restore` failed, we should  log the payload for easy for users to see where things are going wrong
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/104234

#### Special notes for your reviewer:
I'm not sure if I need to check for parse error when the error does not match `line %d failed`
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/util/iptables/iptables.go [hunk 1]
```diff
@@ -784,3 +786,74 @@ func isResourceError(err error) bool {
...
+}
+
+// ParseErrorByRestore extracts the line from the error, returns parseError and error
+// for example:
+// input err: iptables-restore: line 51 failed
+// output parseError:  cmd = iptables-restore, line = 51
+func ParseErrorByRestore(err error) (ParseError, error) {
+	errInfos := strings.Split(err.Error(), ":")
+	if len(errInfos) != 2 {
+		return nil, errors.New("this is not the expected error format")
```
Comment (cyclinder) [inline pkg/util/iptables/iptables.go:815]: Do we need to check this error?

**Comment by cyclinder** [comment]
/cc @thockin @aojea 

PTAL, thanks

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1515,7 +1515,13 @@ func (proxier *Proxier) syncProxyRules() {
 	klog.V(5).InfoS("Restoring iptables", "rules", proxier.iptablesData.Bytes())
 	err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
 	if err != nil {
-		klog.ErrorS(err, "Failed to execute iptables-restore")
+		parseError, pErr := utiliptables.ParseErrorByRestore(err)
+		if pErr != nil {
```
Comment (jonyhy96) [inline pkg/proxy/iptables/proxier.go:1519]: if we don't care pErr, ParseErrorByRestore could return (ParseError, bool)

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -1515,7 +1515,13 @@ func (proxier *Proxier) syncProxyRules() {
...
+			klog.ErrorS(err, "Failed to execute iptables-restore")
+		} else {
+			lines := utiliptables.ExtractLines(3, parseError.Line(), proxier.iptablesData.Bytes())
+			klog.Error("Failed to execute iptables-restore: ", parseError.Error(), lines)
```
Comment (pacoxu) [inline pkg/proxy/iptables/proxier.go:1523]:
```suggestion
			klog.ErrorS(parseError.Error(), "Failed to execute iptables-restore.",  "lines", lines)
```

/home/prow/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:1523:4: unstructured logging function "Error" should not be used

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
Comment (cyclinder) [reply pkg/proxy/iptables/proxier.go:1519]: yeah, I agree with you

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (cyclinder) [reply pkg/proxy/iptables/proxier.go:1523]: maybe we should use klog.Errorln, I want the log to be displayed in a format like this：
```
 Failed to execute iptables-restore: input error on line 1234:
    1231: ...
    1232: ...
    1233: ...
    1234: ...
    1235: ...
    1236: ...
    1237: ...
```

File: pkg/util/iptables/iptables.go [hunk 4]
```diff
@@ -424,7 +426,7 @@ func (runner *runner) restoreInternal(args []string, data []byte, flush FlushFla
 	cmd.SetStdin(bytes.NewBuffer(data))
 	b, err := cmd.CombinedOutput()
 	if err != nil {
-		return fmt.Errorf("%v (%s)", err, b)
+		return errors.New(string(b))
```
Comment (aojea) [inline pkg/util/iptables/iptables.go:429]: I think that the convention now is to wrap errors https://go.dev/blog/go1.13-errors
```suggestion
		fmt.Errorf("%s: %w", b, err)
```

File: pkg/util/iptables/iptables.go [hunk 5]
```diff
@@ -784,3 +786,74 @@ func isResourceError(err error) bool {
...
+	return fmt.Sprintf("%s: input error on line %d: ", e.cmd, e.line)
+}
+
+// ParseRestoreError extracts the line from the error, if it matches returns parseError
+// for example:
+// input err: iptables-restore: line 51 failed
+// output parseError:  cmd = iptables-restore, line = 51
+func ParseRestoreError(err error) (ParseError, bool) {
+	errInfos := strings.Split(err.Error(), ":")
+	if len(errInfos) != 2 {
```
Comment (aojea) [inline pkg/util/iptables/iptables.go:814]: I'm afraid of depending on the iptables error message format not changing :/

File: pkg/util/iptables/iptables.go [hunk 6]
```diff
@@ -784,3 +786,74 @@ func isResourceError(err error) bool {
...
+		return nil, false
+	}
+
+	lineInfo := strings.TrimSpace(errInfos[1])
+	lineInfos := strings.Split(lineInfo, " ")
+	if len(lineInfos) != 3 {
```
Comment (aojea) [inline pkg/util/iptables/iptables.go:820]: https://github.com/kubernetes/kubernetes/pull/106847/files#r765052239

File: pkg/util/iptables/iptables.go [hunk 7]
```diff
@@ -784,3 +786,74 @@ func isResourceError(err error) bool {
...
+	}
+
+	line, errMsg := strconv.Atoi(lineInfos[1])
+	if errMsg != nil {
+		return nil, false
+	}
+	return parseError{cmd: lineInfos[1], line: line}, true
+}
+
+const delimiter = 0x0a
```
Comment (aojea) [inline pkg/util/iptables/iptables.go:831]: ascii new line?
```
(nl)   10 0012 0x0a   New Line
```
if so we should add a comment explaining it

Comment (cyclinder) [reply pkg/util/iptables/iptables.go:831]: maybe we should all use acsii to represent these separators(`":"、" "、"\n"`) and add a comment explaining it?

File: pkg/util/iptables/iptables.go (hunk 5 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:814]: yeah,  this is an uncertainty

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (thockin) [reply pkg/proxy/iptables/proxier.go]: I'd rather build a `[]string` and log that, one line per array member

File: pkg/util/iptables/iptables.go (hunk 5 above)
Comment (thockin) [reply pkg/util/iptables/iptables.go]: Just document that, to our best knowledge, this is the output.  If it ever changes we need to update this

**Review by thockin — COMMENTED** [review]
looks pretty good!

File: pkg/util/iptables/iptables.go [hunk 8]
```diff
@@ -784,3 +785,80 @@ func isResourceError(err error) bool {
...
+	line int
+}
+
+func (e parseError) Line() int {
+	return e.line
+}
+
+const (
+	// delimiter is LF in hexadecimal
+	delimiter = 0x0a
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:805]: done

File: pkg/util/iptables/iptables.go (hunk 6 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:827]: yeah!

File: pkg/util/iptables/iptables.go [hunk 9]
```diff
@@ -784,3 +785,80 @@ func isResourceError(err error) bool {
...
+
+	line, errMsg := strconv.Atoi(lineInfos[1])
+	if errMsg != nil {
+		return nil, false
+	}
+	return parseError{cmd: cmdInfo, line: line}, true
+}
+
+// ExtractLines extracts the -limit and +limit data from the lineNumber row of lines and return
+func ExtractLines(limit, lineNumber int, lines []byte) string {
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:839]: done

**Comment by cyclinder** [comment]
thanks your review @thockin , i gonna working on this.

File: pkg/util/iptables/iptables.go [hunk 10]
```diff
@@ -784,3 +785,80 @@ func isResourceError(err error) bool {
...
+
+func (e parseError) Error() error {
+	return fmt.Errorf("%s: input error on line %d: ", e.cmd, e.line)
+}
+
+// ParseRestoreError extracts the line from the error, if it matches returns parseError
+// for example:
+// input err: exit status 1: iptables-restore: line 51 failed
+// output parseError:  cmd = iptables-restore, line = 51
+func ParseRestoreError(err error) (ParseError, bool) {
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:818]: In that case, `restoreInternal` is the shared part of `Restore/RestoreAll`, so We should also change the return type of these two functions？ (Error -> ParseError, Error) 
https://github.com/kubernetes/kubernetes/blob/c83a94da72416219cf9f022dc44b0e6db158f092/pkg/util/iptables/iptables.go#L72

https://github.com/kubernetes/kubernetes/blob/c83a94da72416219cf9f022dc44b0e6db158f092/pkg/util/iptables/iptables.go#L74

File: pkg/util/iptables/iptables.go [hunk 11]
```diff
@@ -784,3 +785,80 @@ func isResourceError(err error) bool {
...
+	line, errMsg := strconv.Atoi(lineInfos[1])
+	if errMsg != nil {
+		return nil, false
+	}
+	return parseError{cmd: cmdInfo, line: line}, true
+}
+
+// ExtractLines extracts the -limit and +limit data from the lineNumber row of lines and return
+func ExtractLines(limit, lineNumber int, lines []byte) string {
+	lineBytes := bytes.Split(lines, []byte{delimiter})
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:840]: I have two examples:
The first one is like the way you mentioned above. The second one is like the following example：
```bash
func ExtractLines(limit, lineNumber int, lines []byte) []string {
	start := lineNumber - limit
	if start < 0 {
		start = 0
	}
	end := lineNumber + limit + 1

	count := 0
	scanner := bufio.NewScanner(bytes.NewBuffer(lines))
	extractLines := make([]string,0,limit * 2)
	for scanner.Scan(){
		if count >= start && count < end {
			extractLines = append(extractLines,scanner.Text())
		}
		if count == end {
			break
		}
		count++
	}

	return extractLines
}
```
I think the performance of the them is similar, I prefer the second one, the readability is better, do you think so? 

I hope you can give me some advices, big thanks!

File: pkg/util/iptables/iptables.go (hunk 5 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go]: done

File: pkg/util/iptables/iptables.go [hunk 12]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
...
+	cmd  string
+	line int
+}
+
+func (e parseError) Line() int {
+	return e.line
+}
+
+const (
+	colon = ":"
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:821]: This adds negative value, I think.  Just say `":"` at the call site :)

File: pkg/util/iptables/iptables.go [hunk 13]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
...
+}
+
+// parseRestoreError extracts the line from the error, if it matches returns parseError
+// for example:
+// input: iptables-restore: line 51 failed
+// output: parseError:  cmd = iptables-restore, line = 51
+// NOTE: parseRestoreError depends on the error format of iptables, if it ever changes
+// we need to update this function
+func parseRestoreError(err string) (ParseError, bool) {
+	errInfos := strings.SplitN(err, colon, 3)
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:835]: Why would this be 3?  The example above (and I confirmed) has 2 parts.

https://go.dev/play/p/69IpIPUBubN

Comment (thockin) [inline pkg/util/iptables/iptables.go:835]: This whole manual parse is too loose and too easy to trip up.  Why not something like:

https://go.dev/play/p/KjGf4ZjoiuG

File: pkg/util/iptables/iptables.go [hunk 14]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
...
+	line, errMsg := strconv.Atoi(lineInfos[1])
+	if errMsg != nil {
+		return nil, false
+	}
+	return parseError{cmd: cmdInfo, line: line}, true
+}
+
+// ExtractLines extracts the -count and +count data from the lineNum row of lines and return
+// NOTE: lines start from line 0
+func ExtractLines(limit, lineNumber int, lines []byte) []string {
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:855]: I think the args should be `[]byte, line, context ` or just `[]byte, line, count` (let the caller do the context math)

File: pkg/util/iptables/iptables.go [hunk 15]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
...
+		start = 0
+	}
+	end := lineNumber + limit + 1
+
+	count := 0
+	scanner := bufio.NewScanner(bytes.NewBuffer(lines))
+	extractLines := make([]string, 0, limit*2)
+	for scanner.Scan() {
+		if count >= start && count < end {
+			extractLines = append(extractLines, scanner.Text())
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:867]: If you are printing some number of lines before the error, it will be confusing as to where the error is.  Should this be a `[]struct{Line int, Data string}` ?

File: pkg/proxy/ipvs/proxier.go [hunk 16]
```diff
@@ -1605,7 +1605,7 @@ func (proxier *Proxier) syncProxyRules() {
 	proxier.iptablesData.Write(proxier.filterRules.Bytes())
 
 	klog.V(5).InfoS("Restoring iptables", "rules", string(proxier.iptablesData.Bytes()))
-	err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
+	_, err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
```
Comment (thockin) [inline pkg/proxy/ipvs/proxier.go:1608]: Why not print the lines here?

File: pkg/proxy/iptables/proxier.go [hunk 17]
```diff
@@ -1513,9 +1513,15 @@ func (proxier *Proxier) syncProxyRules() {
...
 
 	klog.V(5).InfoS("Restoring iptables", "rules", proxier.iptablesData.Bytes())
-	err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
+	var ParseError utiliptables.ParseError
+	ParseError, err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
 	if err != nil {
-		klog.ErrorS(err, "Failed to execute iptables-restore")
+		if ParseError != nil {
+			lines := utiliptables.ExtractLines(3, ParseError.Line(), proxier.iptablesData.Bytes())
+			klog.ErrorS(ParseError.Error(), "Failed to execute iptables-restore", "lines", lines)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1521]: After suggested changes, something like 

```
if perr, ok := err.(utiliptables.ParseError); ok {
    klog.ErrorS(ParseError, "Failed to execute iptables-restore", "lines", lines)
} else {
    klog.ErrorS(err, "Failed to execute iptables-restore")
}
```

File: pkg/util/iptables/iptables.go [hunk 18]
```diff
@@ -370,22 +372,33 @@ func (runner *runner) SaveInto(table Table, buffer *bytes.Buffer) error {
...
+	return err
 }
 
 // RestoreAll is part of Interface.
-func (runner *runner) RestoreAll(data []byte, flush FlushFlag, counters RestoreCountersFlag) error {
+func (runner *runner) RestoreAll(data []byte, flush FlushFlag, counters RestoreCountersFlag) (ParseError, error) {
 	// setup args
 	args := make([]string, 0)
-	return runner.restoreInternal(args, data, flush, counters)
+	PErr, err := runner.restoreInternal(args, data, flush, counters)
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:383]: done, thanks

File: pkg/util/iptables/iptables.go [hunk 19]
```diff
@@ -423,9 +436,15 @@ func (runner *runner) restoreInternal(args []string, data []byte, flush FlushFla
 	cmd.SetStdin(bytes.NewBuffer(data))
 	b, err := cmd.CombinedOutput()
 	if err != nil {
-		return fmt.Errorf("%v (%s)", err, b)
+		pErr, ok := parseRestoreError(string(b))
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:439]: done

File: pkg/util/iptables/iptables.go [hunk 20]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
 	}
 	return false
 }
+
+type ParseError interface {
+	Line() int
+	Error() error
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:808]: done

File: pkg/util/iptables/iptables.go [hunk 21]
```diff
@@ -783,3 +802,75 @@ func isResourceError(err error) bool {
...
+func (e parseError) Line() int {
+	return e.line
+}
+
+const (
+	colon = ":"
+)
+
+func (e parseError) Error() error {
+	return fmt.Errorf("%s: input error on line %d: ", e.cmd, e.line)
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:825]: done

File: pkg/util/iptables/iptables.go (hunk 12 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:821]: yeah :)

File: pkg/util/iptables/iptables.go (hunk 13 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:835]: my mistake..😅

Comment (cyclinder) [reply pkg/util/iptables/iptables.go:835]: thanks, done

File: pkg/util/iptables/iptables.go (hunk 14 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:855]: caller calculates start and end?

**Comment by cyclinder** [comment]
thanks for your review @thockin

File: pkg/util/iptables/iptables.go [hunk 22]
```diff
@@ -783,3 +790,76 @@ func isResourceError(err error) bool {
...
+	return e.line
+}
+
+func (e parseError) Error() string {
+	return fmt.Sprintf("%s: input error on line %d: ", e.cmd, e.line)
+}
+
+type LineData struct {
+	Line int
+	Date string
```
Comment (aojea) [inline pkg/util/iptables/iptables.go:814]: is this a typo, do you mean `Data`?

File: pkg/util/iptables/iptables_test.go [hunk 23]
```diff
@@ -1198,3 +1198,114 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+		line  int
+		lines []byte
+	}
+	lines := "Line0: 0\nLine1: 1\nLine2: 2\nLine3: 3\nLine4: 4\nLine5: 5\nLine6: 6\nLine7: 7\nLine8: 8\nLine9\nLine10: 10"
+	tests := []struct {
+		name string
+		args args
+		want []LineData
+	}{
+		{
```
Comment (aojea) [inline pkg/util/iptables/iptables_test.go:1215]: what about adding some edge cases like?
All zeros: count 0 - line 0
Out of bounds: count 11 - line 10
...

File: pkg/util/iptables/iptables.go (hunk 22 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:814]: thanks, it's a low level typo😅

File: pkg/util/iptables/iptables_test.go (hunk 23 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables_test.go:1215]: Good advice, got

Comment (cyclinder) [reply pkg/util/iptables/iptables_test.go:1215]: for `Out of bounds: count 11 - line 10`: maybe we also have this case, when count > line,  startIndex starts from line 0

File: pkg/util/iptables/iptables_test.go [hunk 24]
```diff
@@ -1198,3 +1195,166 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+				line:  0,
+				lines: []byte(lines),
+			},
+			[]LineData{
+				{
+					Line: 0,
+					Data: "Line0: 0",
+				},
+			},
+		},
```
Comment (aojea) [inline pkg/util/iptables/iptables_test.go:1238]: is this not the same as `test0`?

File: pkg/util/iptables/iptables_test.go [hunk 25]
```diff
@@ -1198,3 +1198,152 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
 }
+
+// TestExtractLines tests that
+func TestExtractLines(t *testing.T) {
+	type args struct {
+		count int
+		line  int
+		lines []byte
+	}
+	lines := "Line0: 0\nLine1: 1\nLine2: 2\nLine3: 3\nLine4: 4\nLine5: 5\nLine6: 6\nLine7: 7\nLine8: 8\nLine9\nLine10: 10"
```
[the remark this answers is not in the document]
Comment (cyclinder) [reply pkg/util/iptables/iptables_test.go:1209]: oh! :)

File: pkg/util/iptables/iptables.go [hunk 26]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
...
+// NOTE: parseRestoreError depends on the error format of iptables, if it ever changes
+// we need to update this function
+func parseRestoreError(err string) (ParseError, bool) {
+	errInfos := strings.SplitN(err, ":", 3)
+	if len(errInfos) != 2 {
+		return nil, false
+	}
+	cmdInfo := errInfos[0]
+	matches := regexpParseError.FindStringSubmatch(errInfos[1])
+	line, errMsg := strconv.Atoi(matches[1])
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:831]: you need to first check that `len(matches) == 2)` or risk a panic

File: pkg/util/iptables/iptables.go [hunk 27]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
 	}
 	return false
 }
+
+type ParseError interface {
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:793]: needs a godoc comment

File: pkg/util/iptables/iptables.go [hunk 28]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
...
+	Line() int
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:794]: Needs a godoc comment, especially whether the first line is 0 or 1

File: pkg/util/iptables/iptables.go [hunk 29]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
...
+
+func (e parseError) Line() int {
+	return e.line
+}
+
+func (e parseError) Error() string {
+	return fmt.Sprintf("%s: input error on line %d: ", e.cmd, e.line)
+}
+
+type LineData struct {
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:811]: needs a godoc comment

File: pkg/util/iptables/iptables.go [hunk 30]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
...
+	Line int
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:812]: Needs a godoc comment, especially whether the first line is 0 or 1

File: pkg/util/iptables/iptables_test.go [hunk 31]
```diff
@@ -1198,3 +1198,152 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+		want []LineData
+	}{
+		{
+			"test0",
+			args{
+				count: 0,
+				line:  0,
+				lines: []byte(lines),
+			},
+			[]LineData{
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1222]: small nit - you can save space and make these more readable as:

```
tests := []struct {
		name string
		args args
		want []LineData
	}{{
		"test0",
		args{
			count: 0,
			line:  0,
			lines: []byte(lines),
		},
		[]LineData{{
			Line: 0,
			Data: "Line0: 0",
		}},
	}, {
		"test1",
```

File: pkg/util/iptables/iptables.go [hunk 32]
```diff
@@ -783,3 +789,76 @@ func isResourceError(err error) bool {
...
+	matches := regexpParseError.FindStringSubmatch(errInfos[1])
+	line, errMsg := strconv.Atoi(matches[1])
+	if errMsg != nil {
+		return nil, false
+	}
+	return parseError{cmd: cmdInfo, line: line}, true
+}
+
+// ExtractLines extracts the -count and +count data from the lineNum row of lines and return
+// NOTE: lines start from line 0
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:839]: Is this how iptables-restore counts?  I don't think so...

```
$ date | sudo iptables-restore
iptables-restore: line 1 failed
```

I think you need to be 1-based everywhere

File: pkg/util/iptables/iptables_test.go [hunk 33]
```diff
@@ -1198,3 +1198,152 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+				{
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1223]: This might be the right place to NOT use keys.  `LineData{0, "Line0: 0"}` is one line instead of 4

File: pkg/util/iptables/iptables_test.go [hunk 34]
```diff
@@ -1198,3 +1198,152 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
 		t.Errorf("expected failure")
 	}
 }
+
+// TestExtractLines tests that
+func TestExtractLines(t *testing.T) {
+	type args struct {
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1204]: This extra struct level doesn't make it more readable.  I'd just inline these 3 fields to the test struct

File: pkg/util/iptables/iptables_test.go (hunk 33 above)
Comment (thockin) [reply pkg/util/iptables/iptables_test.go:1223]: In fact:

```
mkLines := func(lines ...LineData) []LineData {
    return lines
}

// then use it as:

want: mkLines(LineData{0, "line0"}, LineData{1, "line1"}),
```

easier on the eyets

File: pkg/util/iptables/iptables_test.go [hunk 35]
```diff
@@ -1198,3 +1198,152 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+			},
+			[]LineData{
+				{
+					Line: 3,
+					Data: "Line3: 3",
+				},
+			},
+		},
+		{
+			"test2",
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1243]: better test names appreciated :)

File: pkg/proxy/iptables/proxier.go [hunk 36]
```diff
@@ -1515,7 +1515,12 @@ func (proxier *Proxier) syncProxyRules() {
 	klog.V(5).InfoS("Restoring iptables", "rules", proxier.iptablesData.Bytes())
 	err = proxier.iptables.RestoreAll(proxier.iptablesData.Bytes(), utiliptables.NoFlushTables, utiliptables.RestoreCounters)
 	if err != nil {
-		klog.ErrorS(err, "Failed to execute iptables-restore")
+		if pErr, ok := err.(utiliptables.ParseError); ok {
+			lines := utiliptables.ExtractLines(proxier.iptablesData.Bytes(), pErr.Line(), 3)
+			klog.ErrorS(pErr, "Failed to execute iptables-restore", "lines", lines)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1520]: change the key to "rules" ?

Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1520]: change the key to "rules" ?

Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1520]: change the key to "rules" ?

Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1520]: change the key to "rules" ?

File: pkg/util/iptables/iptables.go (hunk 26 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:841]: sorry, I missing it

File: pkg/util/iptables/iptables.go (hunk 27 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:794]: Done

File: pkg/util/iptables/iptables.go (hunk 28 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:797]: Done

File: pkg/util/iptables/iptables.go (hunk 30 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:818]: Done

File: pkg/util/iptables/iptables.go (hunk 32 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go]: 1-based is right :)

**Comment by cyclinder** [comment]
Thanks for your patient and accurate review @thockin , can you take a look？
/cc @thockin

File: pkg/util/iptables/iptables.go [hunk 37]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
 	}
 	return false
 }
+
+// ParseError records the payload when iptables restore fails
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:793]: nitpick: something like "ParseError records the payload when iptables reports an error parsing its input."

File: pkg/util/iptables/iptables.go [hunk 38]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+type ParseError interface {
+	// Line returns the number of lines on which iptables-restore is failing
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:795]: nitpick: something like "Line returns the line number on which the parse error was reported."

File: pkg/util/iptables/iptables.go [hunk 39]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+	// NOTE: First line is line 1
+	Line() int
+	// Error returns the error message of the location where the iptables-restore execution failed
+	Error() string
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:799]: "Error returns the error message of the parse error, including line number."

File: pkg/util/iptables/iptables.go [hunk 40]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+
+func (e parseError) Line() int {
+	return e.line
+}
+
+func (e parseError) Error() string {
+	return fmt.Sprintf("%s: input error on line %d: ", e.cmd, e.line)
+}
+
+// LineData is used to save the line of the lines and its corresponding data
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:815]: "LineData represents a single numbered line of data."

File: pkg/util/iptables/iptables.go [hunk 41]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+type LineData struct {
+	// Number of rows in lines, First line is line 1
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:817]: Line holds the line number (the first line is 1).

File: pkg/util/iptables/iptables.go [hunk 42]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+	Line int
+	// The date of the line
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:819]: "data" and end with a period, please.

File: pkg/util/iptables/iptables.go [hunk 43]
```diff
@@ -783,3 +789,90 @@ func isResourceError(err error) bool {
...
+
+var regexpParseError = regexp.MustCompile("line ([1-9][0-9]*) failed$")
+
+// parseRestoreError extracts the line from the error, if it matches returns parseError
+// for example:
+// input: iptables-restore: line 51 failed
+// output: parseError:  cmd = iptables-restore, line = 51
+// NOTE: parseRestoreError depends on the error format of iptables, if it ever changes
+// we need to update this function
+func parseRestoreError(err string) (ParseError, bool) {
```
Comment (thockin) [inline pkg/util/iptables/iptables.go:831]: by convention `err` is type `error`.  Can you rename the argument here to "str" or something, and then use `err` instead of `errMsg` below?

File: pkg/util/iptables/iptables_test.go [hunk 44]
```diff
@@ -1198,3 +1198,53 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+		count int
+		line  int
+		name  string
+		want  []LineData
+		lines []byte
+	}{{
+		name:  "test-line-0",
+		count: 3,
+		line:  0,
+		lines: []byte(lines),
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1218]: this is the same for every case - you can just leave it out and say it in the test loop at the bottom :)

File: pkg/util/iptables/iptables_test.go [hunk 45]
```diff
@@ -1198,3 +1198,53 @@ func TestRestoreAllWaitBackportedIptablesRestore(t *testing.T) {
...
+		count: 0,
+		line:  3,
+		lines: []byte(lines),
+		want:  mkLines(LineData{3, "Line3: 3"}),
+	}, {
+		name:  "test-common-cases",
+		count: 3,
+		line:  6,
+		lines: []byte(lines),
+		want: mkLines(LineData{3, "Line3: 3"}, LineData{4, "Line4: 4"}, LineData{5, "Line5: 5"}, LineData{6, "Line6: 6"},
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1231]: I would linewrap these like:

```
want: mkLines(
	LineData{3, "Line3: 3"},
	LineData{4, "Line4: 4"},
	LineData{5, "Line5: 5"},
	LineData{6, "Line6: 6"},
	LineData{7, "Line7: 7"},
	LineData{8, "Line8: 8"},
	LineData{9, "Line9: 9"})

**Review by thockin — COMMENTED** [review]
All of these are tiny things - good PR

File: pkg/util/iptables/iptables.go (hunk 37 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go]: sorry, my expression is not quite accurate 😅

File: pkg/util/iptables/iptables.go (hunk 39 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go:799]: done

File: pkg/util/iptables/iptables.go (hunk 42 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go]: my bad😅

File: pkg/util/iptables/iptables.go (hunk 43 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables.go]: done

File: pkg/util/iptables/iptables_test.go (hunk 44 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables_test.go]: done

File: pkg/util/iptables/iptables_test.go (hunk 45 above)
Comment (cyclinder) [reply pkg/util/iptables/iptables_test.go]: Done

**Comment by cyclinder** [comment]
/cc @thockin 
PTAL, Hopefully this time it will end😄
big thanks

File: pkg/util/iptables/iptables.go (hunk 42 above)
Comment (thockin) [reply pkg/util/iptables/iptables.go]: no problem - we're down to really minor details now :)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
