### PR TITLE
Fix expired event logic to use 404 instead of 500

### LINKED ISSUE #23637: Occasional server rejected event errors
I keep seeing these server rejected event errors every now and then. My guess is it is trying to update an event that was expired in etcd. However I don't expect an error, since there is specific logic in `event.go` to handle that use case.

Any ideas why this may happening? I am using kubernetes 1.2.

Here is an example, from a host getting added to a cluster:
```
E0330 08:31:26.757466   24064 event.go:198] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"elasticsearch-logging.144056583e429320", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"1634368", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Service", Namespace:"kube-system", Name:"elasticsearch-logging", UID:"687749f9-dc9f-11e5-9867-06ef3ecbd7cb", APIVersion:"v1", ResourceVersion:"1633611", FieldPath:""}, Reason:"UpdatedLoadBalancer", Message:"Updated load balancer with new hosts", Source:api.EventSource{Component:"service-controller", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63594858016, nsec:0, loc:(*time.Location)(0x26f9e80)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63594923486, nsec:756157274, loc:(*time.Location)(0x26f9e80)}}, Count:6, Type:"Normal"}': 'events "elasticsearch-logging.144056583e429320" not found' (will not retry!)
Mar 30 08:31:26 ip-10-50-185-118 start-kube-controller-manager.sh[24064]: I0330 08:31:26.756181   24064 servicecontroller.go:685] Successfully updated 12 out of 12 load balancers to direct traffic to the updated set of nodes
```

### PR DESCRIPTION
**Pull request by jsravn**
It seems this logic was never updated once apiserver started returning 404s for expired (missing) events.

This change corrects it to use a 404 so events will get resent correctly if they were expired in etcd.

Fixes #23637.

### CODE REVIEW

File: pkg/client/record/event.go [hunk 1]
```diff
@@ -153,12 +154,11 @@ func recordToSink(sink EventSink, event *api.Event, eventCorrelator *EventCorrel
 
 func isKeyNotFoundError(err error) bool {
 	statusErr, _ := err.(*errors.StatusError)
-	// At the moment the server is returning 500 instead of a more specific
-	// error. When changing this remember that it should be backward compatible
-	// with old api servers that may be still returning 500.
```
Comment (lavalamp) [inline pkg/client/record/event.go]: Did the server already change this?

Comment (jsravn) [inline pkg/client/record/event.go]: It seems to have been returning a 404 for a long time (`generic/etcd/etcd.go` line 272). I'm still a bit fuzzy on how resources are handled by the apiserver, but it doesn't look like it should ever return a 500 for a missing event.

**Comment by lavalamp** [comment]
LGTM-- I kicked travis.

**Comment by jmastr** [comment]
Please merge this :+1:

**Comment by jsravn** [comment]
I'm not sure why the integration build timed out.

**Comment by jsravn** [comment]
@lavalamp - any idea? Thanks :)

**Comment by lavalamp** [comment]
@k8s-bot unit test this issue #23879
