### PR TITLE
safe-sysctl: skip checking for windows

### LINKED ISSUE #116790: safe-sysctls check on windows failed
### What happened?

E0320 18:35:17.623064    4656 safe_sysctls.go:43] "Failed to get kernel version." err="error reading osrelease file \"/proc/sys/kernel/osrelease\": open /proc/sys/kernel/osrelease: The system cannot find the path specified."

### What did you expect to happen?

handle windows node correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Run kubelet v1.27 beta+ on windows.

### Anything else we need to know?

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-win2022-containerd-gce-master/1637882397410201600/artifacts/e2e-04289f2be9-268c3-windows-node-group-4rhw/kubelet.log

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-win2022-containerd-gce-master/1637882397410201600

This is an example

### Kubernetes version

v1.27.0-beta*

### Cloud provider

N/A

### OS version

windows

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

For windows, the kernel version does not have the same meaning as Linux.
- we add `ip_local_reserved_ports` to `safeSysctls` for Linux the kernel version is after 3.16.

I think we should skip here for windows until we can know a dedicated mapping list of windows kernel versions to linux.

#### Which issue(s) this PR fixes:

Fixes #116790

#### Does this PR introduce a user-facing change?

```release-note
None
```
/sig windows

### CODE REVIEW

**Comment by cici37** [comment]
This Issue/PR has been marked as release blocker. Please have the PR merged by eod today otherwise the feature has to be reverted. For the Issue/PR owner: please have a revert/feature disable PR open today in case the fix failed to get in. Thank you! See the [announcement here](https://groups.google.com/a/kubernetes.io/g/dev/c/yzSvdfk8mo8)

-- Kubernetes 1.27 release manager

**Review by mrunalp — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
> should we revert #115374 until this is actually accepted across OSes?

/hold

Discussing here: https://kubernetes.slack.com/archives/C0BP8PW9G/p1679439424451039 Protecting from accidental merge

File: pkg/kubelet/sysctl/safe_sysctls.go [hunk 1]
```diff
@@ -38,19 +40,14 @@ var safeSysctls = []string{
...
-	kernelVersionStr, err := ipvs.NewLinuxKernelHandler().GetKernelVersion()
-	if err != nil {
-		klog.ErrorS(err, "Failed to get kernel version.")
-		return safeSysctls
-	}
-	kernelVersion, err := version.ParseGeneric(kernelVersionStr)
-	if err != nil {
-		klog.ErrorS(err, "Failed to parse kernel version.")
+	if goruntime.GOOS != "linux" {
 		return safeSysctls
```
Comment (liggitt) [inline pkg/kubelet/sysctl/safe_sysctls.go:44]: if we're on windows, this should *include* net.ipv4.ip_local_reserved_ports so we don't fail pods that set it for no reason when Windows would just ignore the sysctl like all others

Comment (liggitt) [reply pkg/kubelet/sysctl/safe_sysctls.go:45]: I think this should look more like this:

```
var safeSysctls = []string{
	"kernel.shm_rmid_forced",
	"net.ipv4.ip_local_port_range",
	"net.ipv4.tcp_syncookies",
	"net.ipv4.ping_group_range",
	"net.ipv4.ip_unprivileged_port_start",
}

var safeSysctlsIncludeReservedPorts = []string{
	"kernel.shm_rmid_forced",
	"net.ipv4.ip_local_port_range",
	"net.ipv4.tcp_syncookies",
	"net.ipv4.ping_group_range",
	"net.ipv4.ip_unprivileged_port_start",
	"net.ipv4.ip_local_reserved_ports",
}

func SafeSysctlAllowlist() []string {
  if goruntime.GOOS == "linux" {
    kernelVersion, err := getKernelVersion()
    if err != nil {
      klog.ErrorS(err, "Failed to get kernel version, dropping net.ipv4.ip_local_reserved_ports from safe sysctl list")
      return safeSysctls
    }
    if kernelVersion.LessThan(version.MustParseGeneric(ipLocalReservedPortsMinNamespacedKernelVersion)) {
      klog.ErrorS(err, "Kernel version is too old, dropping net.ipv4.ip_local_reserved_ports from safe sysctl list", "kernelVersion", kernelVersion)
      return safeSysctls
    }
  }
  return safeSysctlsIncludeReservedPorts
}

func getKernelVersion() (*version.Version, error) {
	kernelVersionStr, err := ipvs.NewLinuxKernelHandler().GetKernelVersion()
	if err != nil {
		return nil, fmt.Errorf("failed to get kernel version: %w", err)
	}
	kernelVersion, err := version.ParseGeneric(kernelVersionStr)
	if err != nil {
		return nil, fmt.Errorf("failed to parse kernel version: %w", err)
	}
	return kernelVersion, nil
}
```

Comment (pacoxu) [reply pkg/kubelet/sysctl/safe_sysctls.go:45]: Updated as windows just ignored the sysctls info of pod.

Comment (liggitt) [reply pkg/kubelet/sysctl/safe_sysctls.go:45]: the `getKernelVersion() (*version.Version, error)` signature and including the consequence of the kernel lookup error or version parse failure is probably better

Comment (pacoxu) [reply pkg/kubelet/sysctl/safe_sysctls.go]: Updated based on Jordon's suggestions.

**Comment by liggitt** [comment]
/hold cancel
lgtm for reliance of things like pod security admission on this being a safe sysctl

will let @mrunalp / @marosset lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
