### PR TITLE
Add newline to printf to fix junit

### LINKED ISSUE #30761: kubernetes-test-go: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/15869/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #30761

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30772)

### CODE REVIEW

**Comment by ncdc** [comment]
cc @gmarek

**Comment by gmarek** [comment]
Merging to unblock submit queue.

File: pkg/util/yaml/decoder_test.go [hunk 1]
```diff
@@ -140,7 +140,7 @@ stuff: 1
 	if err == nil {
 		t.Fatal("expected error with yaml: prefix, got no error")
 	}
-	fmt.Printf("err: %s", err.Error())
```
Comment (lavalamp) [inline pkg/util/yaml/decoder_test.go]: This should use t.Logf
