### PR TITLE
kubeadm: Honor `cert-dir` for cert operations

### LINKED ISSUE #110708: kubeadm: cert renew doesn't work with `cert-dir` set
### What happened?

When `cert-dir` is set to a value other than the default value (/etc/kubernetes/pki/), and run `certs renew` on the working kubernetes controller node, the cert is not renewed as expected.

This impacts the `check-expiration` as well.

### What did you expect to happen?

`cert  renew` or `check-expiration` work as expected.

 

### How can we reproduce it (as minimally and precisely as possible)?

Here is an example which show cert renew doesn't work, 

- create a cert,
```bash
ls -l /tmp/3366554527.bak/apiserver.crt
-rw-r--r-- 1 root root 1277 Jun 20 18:33 /tmp/3366554527.bak/apiserver.crt
```

- and then renew the cert,

```
kubeadm certs renew apiserver --cert-dir /tmp/3366554527.bak

...
certificate for serving the Kubernetes API renewed
```

- check if the cert is renewed, 

```bash
ls -l /tmp/3366554527.bak/apiserver.crt
-rw-r--r-- 1 root root 1277 Jun 20 18:33 /tmp/3366554527.bak/apiserver.crt
```

It actually renewed the cert in the default path(/etc/kubernetes/pki/),
```bash
# ls -l /etc/kubernetes/pki/apiserver.crt
-rw-r--r-- 1 root root 1281 Jun 22 10:58 /etc/kubernetes/pki/apiserver.crt
```

The issue can be revealed by the test as well, 

```bash
go test k8s.io/kubernetes/cmd/kubeadm/app/cmd -test.run TestRunRenewCommands/apiserver
...
certificate the apiserver uses to access etcd renewed
--- FAIL: TestRunRenewCommands (0.13s)
    --- FAIL: TestRunRenewCommands/apiserver (0.03s)
        certs_test.go:256: certificate apiserver was not renewed as expected
    --- FAIL: TestRunRenewCommands/apiserver-kubelet-client (0.03s)
        certs_test.go:256: certificate apiserver-kubelet-client was not renewed as expected
    --- FAIL: TestRunRenewCommands/apiserver-etcd-client (0.02s)
        certs_test.go:256: certificate apiserver-etcd-client was not renewed as expected
FAIL
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/cmd   0.158s
FAIL
```

**NOTE** This issue only exist with a working cluster since the code will fall back to use the cluster configuration when config file is not specified. 

And if the cluster cannot be connected with the `admin.conf`, the `cert-dir` will be honored, this is why the test can pass with the CI jobs.  Check the log printed by this test pr: https://github.com/kubernetes/kubernetes/pull/110681

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
all
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by chendave**
- `cert-dir` could be specified to a value other than the default value
- we have tests that should be executed successfully on the working cluster

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/110708

#### Special notes for your reviewer:
This issue only exists with a working cluster since the code will fall back to use the cluster configuration when config file is not specified.

And if the cluster cannot be connected with the `admin.conf`, the `cert-dir` will be honored, this is why the test can pass with the CI jobs but fail with working cluster,  pls check the log printed by this test pr: https://github.com/kubernetes/kubernetes/pull/110681

pls see https://github.com/kubernetes/kubernetes/issues/110708 for details.

#### Does this PR introduce a user-facing change?

```release-note
`kubeadm certs renew` and   `kubeadm certs check-expiration`  now honor the `cert-dir` on a working kubernetes cluster.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @neolit123

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
This seems like a flags vs config problem.
Is cert-dir the only flag we have to override in the incluster config?

The change seems ok, but i think the more accurate fix is to not download the incluster config if a single flag is passed,  because flags are also config.

Having said that, i don't think we do it like that in orher places and we just check for the config flag "" string similarly.

**Comment by chendave** [comment]
> Is cert-dir the only flag we have to override in the incluster config?

I think so, other flags (CertificatesDir, cfgPath) that are added seem like are not related. 

> The change seems ok, but i think the more accurate fix is to not download the incluster config if a single flag is passed, because flags are also config.

Okay, will do as suggested.

**Comment by neolit123** [comment]
> Okay, will do as suggested.

Unclear if we want the override vs don't download if a flag is passed. Ideally we should have consisten

**Comment by BenTheElder** [comment]
IMHO override seems like the least surprising behavior for setting a flag.

File: cmd/kubeadm/app/cmd/certs.go [hunk 1]
```diff
@@ -335,6 +335,14 @@ func getInternalCfg(cfgPath string, kubeconfigPath string, cfg kubeadmapiv1.Clus
 			internalcfg, err := configutil.FetchInitConfigurationFromCluster(client, nil, logPrefix, false, false)
 			if err == nil {
 				fmt.Println() // add empty line to separate the FetchInitConfigurationFromCluster output from the command output
+				// certificate renewal or expiration checking doesn't depend on a running cluster, which means the CertificatesDir
+				// could be set to a value other than the default value or the value fetched from the cluster.
+				// cfg.CertificatesDir could be empty if the default value is set to empty (not true today).
+				fmt.Printf("Overriding the default cert dir with the value from command line flag: %s", cfg.CertificatesDir)
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/certs.go:341]: i think this should be a `klog.V(1).Infof()`
other than that LGTM.

/approve

Comment (chendave) [reply cmd/kubeadm/app/cmd/certs.go:341]: Done, thanks!

File: cmd/kubeadm/app/cmd/certs.go [hunk 2]
```diff
@@ -335,6 +336,14 @@ func getInternalCfg(cfgPath string, kubeconfigPath string, cfg kubeadmapiv1.Clus
 			internalcfg, err := configutil.FetchInitConfigurationFromCluster(client, nil, logPrefix, false, false)
 			if err == nil {
 				fmt.Println() // add empty line to separate the FetchInitConfigurationFromCluster output from the command output
+				// certificate renewal or expiration checking doesn't depend on a running cluster, which means the CertificatesDir
+				// could be set to a value other than the default value or the value fetched from the cluster.
+				// cfg.CertificatesDir could be empty if the default value is set to empty (not true today).
+				klog.V(1).Infof("Overriding the default cert dir with the value from command line flag: %s", cfg.CertificatesDir)
+				if len(cfg.CertificatesDir) != 0 {
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/certs.go:343]:
```suggestion
				if len(cfg.CertificatesDir) != 0 {
					klog.V(1).Infof("Overriding the cluster certificate directory with the value from command line flag --%s: %s", options.CertificatesDir, cfg.CertificatesDir)
```

flag name comes from:
https://github.com/kubernetes/kubernetes/blob/0985c476e3db8a5f9532eb4be5cd8adc6f94deef/cmd/kubeadm/app/cmd/options/constant.go#L33

Comment (chendave) [reply cmd/kubeadm/app/cmd/certs.go]: thanks!

**Comment by chendave** [comment]
/hold cancel

thanks for the review!
