### PR TITLE
Trigger all pods rescheduling on nominated node changes

### LINKED ISSUE #126700: [Bug] Scheduler fails to schedule a pod due to a race condition
### What happened?

A bug in the scheduler increases the time spent on scheduling a pod **from <1 second to 5 minutes**.

We discovered the bug when repeating the steps described in a fixed bug report [#106780](https://github.com/kubernetes/kubernetes/issues/106780). The setting and steps are as follows:

We have 1 node with 32Gi memory, and 3 pods to schedule: 
p1 / request 10Gi memory / low-priority,
p2 / request 25Gi memory / medium-priority,
p3 / request 20Gi memory / high-priority.

We perform the following steps:
1. add `p1` and wait until `p1` is running
2. add `p2` and wait until `p1` is terminating; this is because there are not enough resources to host both pods and `p2` has a higher priority.
**Note that at this point, `p2` is not running yet.**
3. add `p3` and wait until `p3` is running; `p2` is pending because `p2` and `p3` cannot coexist on `node0`.
4. re-add `p1` and wait until `p1` is running; `p1` should be able to run since there are enough resources to host both pods: 10 + 20 < 32

Interestingly, we find that if step 4 happened immediately after step 3, then `p1` fails to get scheduled with the reason `Insufficient Memory` and eventually gets scheduled after 5 minutes. If there is some short period between step 3 and step 4 (say 2 seconds), then `p1` is scheduled properly immediately.

#### What is the root cause?

After code and log inspections (see below), we have found the root cause of this bug: it's caused by the race condition between (A) `p1` is re-added and handled by the scheduler and (B) `p2`'s `nominated_node_name` is cleared. If A happens before B, then the bug occurs.

#### Why does 2 second make the difference?

The reason is that `p2`'s `nominated_node_name` is cleared *when it (a nominated pod) is scheduled again and failed*. But as the `p2`'s first schedule failed (need to wait for preemption to finish), it's put to BackoffQueue and need to wait for a few seconds before it's put back to ActionQueue and scheduled again.

So 
1. If `p1` is added before `p2` is scheduled again (without 2s sleep), it will **fail** as `p2`'s `nomianted_node_name` is not cleared.
2. But if we add the 2s sleep, `p2` is scheduled again and its `nominated_node_name` is cleared before `p1` is added. In this case, `p1` will be **schedulable** to node0.

<details><summary>Some scheduler logs of the bug-free and buggy trace</summary>
The lines starting with # are logged just before scheduling p1 and p2. You can notice that their order is reversed in the two traces.

Bug-free trace (B happens before A):
```markdown
# with sleep(2s)
I0814 14:19:47.939731   32287 eventhandlers.go:149] "Add event for unscheduled pod" pod="default/p3"
I0814 14:19:47.939756   32287 schedule_one.go:83] "About to try and schedule pod" pod="default/p3"
I0814 14:19:47.939768   32287 schedule_one.go:96] "Attempting to schedule pod" pod="default/p3"
I0814 14:19:47.939878   32287 default_binder.go:53] "Attempting to bind pod to node" logger="Bind.DefaultBinder" pod="default/p3" node="node0"
I0814 14:19:47.944902   32287 eventhandlers.go:313] "Delete event for scheduled pod" pod="default/p1"
I0814 14:19:47.948208   32287 scheduling_queue.go:1312] "Pod moved to an internal scheduling queue" pod="default/p2" event="AssignedPodDelete" queue="Backoff" hint=1
I0814 14:19:47.948799   32287 schedule_one.go:314] "Successfully bound pod to node" pod="default/p3" node="node0" evaluatedNodes=1 feasibleNodes=1
I0814 14:19:47.948891   32287 eventhandlers.go:201] "Delete event for unscheduled pod" pod="default/p3"
I0814 14:19:47.948901   32287 eventhandlers.go:231] "Add event for scheduled pod" pod="default/p3"
I0814 14:19:47.956662   32287 eventhandlers.go:268] "Update event for scheduled pod" pod="default/p3"
I0814 14:19:49.047040   32287 schedule_one.go:83] "About to try and schedule pod" pod="default/p2"
# I0814 14:19:49.047238   32287 schedule_one.go:96] "Attempting to schedule pod" pod="default/p2"
I0814 14:19:49.047886   32287 schedule_one.go:1055] "Unable to schedule pod; no fit; waiting" pod="default/p2" err="0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod."
I0814 14:19:49.048895   32287 schedule_one.go:1122] "Updating pod condition" pod="default/p2" conditionType="PodScheduled" conditionStatus="False" conditionReason="Unschedulable"
I0814 14:19:49.064048   32287 eventhandlers.go:174] "Update event for unscheduled pod" pod="default/p2"
I0814 14:19:49.978428   32287 eventhandlers.go:149] "Add event for unscheduled pod" pod="default/p1"
I0814 14:19:49.978562   32287 schedule_one.go:83] "About to try and schedule pod" pod="default/p1"
# I0814 14:19:49.978580   32287 schedule_one.go:96] "Attempting to schedule pod" pod="default/p1"
I0814 14:19:49.978879   32287 default_binder.go:53] "Attempting to bind pod to node" logger="Bind.DefaultBinder" pod="default/p1" node="node0"
I0814 14:19:49.985438   32287 eventhandlers.go:201] "Delete event for unscheduled pod" pod="default/p1"
I0814 14:19:49.985476   32287 eventhandlers.go:231] "Add event for scheduled pod" pod="default/p1"
I0814 14:19:49.985747   32287 schedule_one.go:314] "Successfully bound pod to node" pod="default/p1" node="node0" evaluatedNodes=1 feasibleNodes=1
```

Buggy trace (A happens before B):
```markdown
# without sleep(2s)
I0814 14:17:47.151445   31615 eventhandlers.go:149] "Add event for unscheduled pod" pod="default/p3"
I0814 14:17:47.151515   31615 eventhandlers.go:174] "Update event for unscheduled pod" pod="default/p2"
I0814 14:17:47.151802   31615 schedule_one.go:83] "About to try and schedule pod" pod="default/p3"
I0814 14:17:47.151812   31615 schedule_one.go:96] "Attempting to schedule pod" pod="default/p3"
I0814 14:17:47.151926   31615 default_binder.go:53] "Attempting to bind pod to node" logger="Bind.DefaultBinder" pod="default/p3" node="node0"
I0814 14:17:47.156395   31615 eventhandlers.go:313] "Delete event for scheduled pod" pod="default/p1"
I0814 14:17:47.156444   31615 scheduling_queue.go:1312] "Pod moved to an internal scheduling queue" pod="default/p2" event="AssignedPodDelete" queue="Backoff" hint=1
I0814 14:17:47.160464   31615 eventhandlers.go:201] "Delete event for unscheduled pod" pod="default/p3"
I0814 14:17:47.160479   31615 eventhandlers.go:231] "Add event for scheduled pod" pod="default/p3"
I0814 14:17:47.160514   31615 schedule_one.go:314] "Successfully bound pod to node" pod="default/p3" node="node0" evaluatedNodes=1 feasibleNodes=1
I0814 14:17:47.168539   31615 eventhandlers.go:268] "Update event for scheduled pod" pod="default/p3"
I0814 14:17:47.177608   31615 eventhandlers.go:149] "Add event for unscheduled pod" pod="default/p1"
I0814 14:17:47.177642   31615 schedule_one.go:83] "About to try and schedule pod" pod="default/p1"
# I0814 14:17:47.177650   31615 schedule_one.go:96] "Attempting to schedule pod" pod="default/p1"
I0814 14:17:47.177775   31615 schedule_one.go:1055] "Unable to schedule pod; no fit; waiting" pod="default/p1" err="0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod."
I0814 14:17:47.177802   31615 schedule_one.go:1122] "Updating pod condition" pod="default/p1" conditionType="PodScheduled" conditionStatus="False" conditionReason="Unschedulable"
I0814 14:17:47.187472   31615 eventhandlers.go:174] "Update event for unscheduled pod" pod="default/p1"
I0814 14:17:48.138665   31615 schedule_one.go:83] "About to try and schedule pod" pod="default/p2"
# I0814 14:17:48.139950   31615 schedule_one.go:96] "Attempting to schedule pod" pod="default/p2"
I0814 14:17:48.140305   31615 schedule_one.go:1055] "Unable to schedule pod; no fit; waiting" pod="default/p2" err="0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod."
I0814 14:17:48.140582   31615 schedule_one.go:1122] "Updating pod condition" pod="default/p2" conditionType="PodScheduled" conditionStatus="False" conditionReason="Unschedulable"
I0814 14:17:48.156537   31615 eventhandlers.go:174] "Update event for unscheduled pod" pod="default/p2"
```
</details>

#### How to fix it?

1. A potential fix is:
Register all plugins that need to be aware of pods to events triggered by updates to a pod's `nominated_node_name`. This way, a failed pod will be retried as soon as any pod's `nominated_node_name` is cleared.

2. If this is too radical and can cause performance issues, another solution is: 
When a pod is bound to a node with nominated pods, either 
a) re-check the previously nominated pods (that nominated to this node), 
b) or clear the `nominated_node_name` of these nominated pods.
In this way, upcoming pods won't fail unreasonably and won't have to wait 5 minutes for the next retry.

### What did you expect to happen?

`p1` should be immediately scheduled.

### How can we reproduce it (as minimally and precisely as possible)?

We're using [kwok](https://kwok.sigs.k8s.io/) to reproduce this issue.

```yaml
# node0.yaml
apiVersion: v1
kind: Node
metadata:
  name: node0
  labels:
    kubernetes.io/hostname: node0
status:
  allocatable:
    cpu: "32"
    memory: "32Gi"
    pods: "110"
  capacity:
    cpu: "32"
    memory: "32Gi"
    pods: "110"
```

```yaml
# p1.yaml
apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: p1-container
    image: nginx
    resources:
      requests:
        memory: "10Gi"

  priorityClassName: low-priority
```

```yaml
# p2.yaml
apiVersion: v1
kind: Pod
metadata:
  name: p2
spec:
  containers:
  - name: p2-container
    image: nginx
    resources:
      requests:
        memory: "25Gi"
  priorityClassName: medium-priority
```

```yaml
# p3.yaml
apiVersion: v1
kind: Pod
metadata:
  name: p3
spec:
  containers:
  - name: p3-container
    image: nginx
    resources:
      requests:
        memory: "20Gi"
  priorityClassName: high-priority
```

```yaml
# priority_class.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: 500000
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 0
globalDefault: false
description: "This priority class should be used for XYZ service pods only."
```

```python
# To run this reproduction script, please create a new KWOK cluster first.
# kwokctl create cluster --v DEBUG
# Also need to install the kubernetes python client library,
# and place all yaml files in the same folder with the script.
# ---
# To check the scheduler logs:
# kwokctl logs kube-scheduler
# ---
# To reproduce the bug case, please comment out `sleep(2)` between step 5 and step 6.
# To reproduce the normal case, please add `sleep(2)` between step 5 and step 6.
import unittest
import time
import shutil
import logging
from time import sleep
from os import path, makedirs
from logging import getLogger
from kubernetes import config, watch
from kubernetes.client import *
from kubernetes.utils import *
from time import strftime

logger = getLogger(__name__)
config.load_kube_config()
v1 = CoreV1Api()
k8s_cli = ApiClient()


log_dir = path.dirname(__file__)

if __name__ == "__main__":
    log_path = path.join(log_dir, f"issue-106780-reproduction-{strftime('%Y-%m-%d-%H-%M-%S')}")
    shutil.rmtree(log_path, ignore_errors=True)
    makedirs(log_path, exist_ok=True)
    log_file = path.join(log_path, 'reproduce.log')
    logging.basicConfig(level=logging.INFO,
                        filemode='w',
                        filename=log_file,
                        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                        datefmt='%H:%M:%S')
    node0_yaml = path.join(path.dirname(__file__), 'node0.yaml')
    p1_yaml = path.join(path.dirname(__file__), 'p1.yaml')
    p2_yaml = path.join(path.dirname(__file__), 'p2.yaml')
    p3_yaml = path.join(path.dirname(__file__), 'p3.yaml')
    priority_class_yaml = path.join(path.dirname(__file__), 'priority_class.yaml')
    w = watch.Watch()

    # 1. create priority class
    create_from_yaml(k8s_client=k8s_cli, yaml_file=priority_class_yaml)
    logger.info(f"PriorityClass created")

    # 2. add node0
    create_from_yaml(k8s_client=k8s_cli, yaml_file=node0_yaml)
    logger.info(f"Node: node0 created")

    # 3. add p1
    create_from_yaml(k8s_client=k8s_cli, yaml_file=p1_yaml)
    logger.info(f"Pod: p1 added")

    # 3. check p1 is running
    p1_running = False
    for event in w.stream(v1.list_namespaced_pod,
                          field_selector=f'metadata.name=p1',
                          namespace="default",
                          timeout_seconds=int(5)):
        p1 = event['object']
        if event['object'].status.phase == "Running":
            p1_running = True
            logger.info(f"Pod: {p1.metadata.name} scheduled on node {p1.spec.node_name}")
            break
    assert p1_running

    # 4. add p2
    create_from_yaml(k8s_client=k8s_cli, yaml_file=p2_yaml)
    logger.info(f"Pod: p2 added")

    # 4. check p1 is terminating (by p2)
    for event in w.stream(v1.list_namespaced_pod,
                          field_selector=f'metadata.name=p1',
                          namespace="default",
                          timeout_seconds=int(3)):
        logger.info(f"Pod: {event['object'].metadata.name}, event: {event['type']}")
        logger.info(
            f"deletion_timestamp: {event['object'].metadata.deletion_timestamp}, status: {event['object'].status.phase}")
        if event['object'].metadata.deletion_timestamp is not None and event['object'].status.phase in (
        'Pending', 'Running'):
            logger.info(f"Pod: {p1.metadata.name} is terminating")
            break

    # 5. add p3 and wait for p3 running (p3 will terminate p2 / let p2 pending)
    create_from_yaml(k8s_client=k8s_cli, yaml_file=p3_yaml)
    p3_running = False
    for event in w.stream(v1.list_namespaced_pod,
                          field_selector=f'metadata.name=p3',
                          namespace="default",
                          timeout_seconds=int(5)):
        p3 = event['object']
        if p3.status.phase == "Running":
            logger.info(f"Pod: {p3.metadata.name} scheduled on node p3")
            p3_running = True
            break
    assert p3_running

    # sleep(2)  # -> without this on 1.30.2 will cause pod scheduled failed at the first try

    # 6. reapply and check p1 schedulable
    create_from_yaml(k8s_client=k8s_cli, yaml_file=p1_yaml)
    tic = time.time()
    logger.info(f"Pod: p1 re-applied")

    # 7. watch pod1 events and wait it to be scheduled
    p1_running = False
    for event in w.stream(v1.list_namespaced_pod,
                          field_selector=f'metadata.name=p1',
                          namespace="default",
                          timeout_seconds=int(600)):
        p1 = event['object']
        if p1.status.phase == "Running":
            p1_running = True
            logger.info(f"Pod: {p1.metadata.name} scheduled on node {p1.spec.node_name}")
            break

    if not p1_running:
        logger.error(f"Pod: {p1.metadata.name} is not scheduled in 600s")
        assert False
    else:
        logger.info(f"Pod: {p1.metadata.name}, " + f"time between add and scheduled: {time.time() - tic}")


```

### Anything else we need to know?

Tested on 1.30.2

/sig bugs scheduling

### Kubernetes version

<details>

Tested on 1.30.2

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dom4ha**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Removal (change) of nominated node in a pod should trigger rescheduling of other pods which could have been blocked by this pod. It's becasue lower or equal priority pods treat nominated pods (pods that have nominated node assigned) as if they were assigned.

#### Which issue(s) this PR fixes:

Fixes #126700

#### Does this PR introduce a user-facing change?
```release-note
Revised scheduling behavior to correctly handle nominated node changes. Trigger rescheduling of pods if necessary when pods with nominated node names got deleted or nominated on a different node.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Trigger rescheduling of pods when a nominated node name of some pod has changed or the pod was deleted.
+Revised scheduling behavior when the set of unbound Pod changes. When a nominated node name of some pod has changed, or a pendingpod is deleted, the scheduler now reconsiders scheduling for all Pods not yet bound to nodes.
```
(I guessed at the behavior; if this isn't right, feel free to clarify)

File: pkg/scheduler/eventhandlers.go [hunk 1]
```diff
@@ -160,6 +160,16 @@ func (sched *Scheduler) updatePodInSchedulingQueue(oldObj, newObj interface{}) {
 
 	logger.V(4).Info("Update event for unscheduled pod", "pod", klog.KObj(newPod))
 	sched.SchedulingQueue.Update(logger, oldPod, newPod)
+	if hasNominatedNodeNameChanged(oldPod, newPod) {
+		// Nominated node changed in pod, so we need to treat it as if the pod was deleted,
+		// because the lower or equal priority pods treat such a pod as if it was assigned.
+		sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue(logger, framework.EventAssignedPodDelete, oldPod, nil, nil)
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go:166]: Can we somehow make it effective only for the unschedulable pods that is lower/equal priority than this changed pod?

**Review by sanposhiho — COMMENTED** [review]
You also would need an integration test.

**Comment by haosdent** [comment]
BTW, do we need to add unit tests for this change?

**Comment by sanposhiho** [comment]
We technically can, of course. But, we don't usually add a unit test for a private function. Also, when it comes to the functions at eventhandler.go, the behavior here mostly depends on the scheduling queue. So, I'm not sure if we should have a unit test for it.

**Comment by haosdent** [comment]
Got it; I just saw your previous comment. I think integration tests would also be helpful in preventing such bugs in the future.

File: pkg/scheduler/eventhandlers.go (hunk 1 above)
Comment (dom4ha) [reply pkg/scheduler/eventhandlers.go:166]: I was thinking about it, but I was comparing it with preemption mechanism only. Let me think about it laud.

IIUC not all lower priority pods can be preempted, so it's possible that some higher priority pod was also blocked on them. This is why completion of some pod triggers reevaluation of all pods, not only lower and equal priority ones.

On the other hand, it seems like lower priority nominated pods are removed unconditionally in attempt to fit higher priority one. I also assume that in case intra pod affinity of a lower priority nominated pod was blocking scheduling, such pod would be preempted (nomination cleared), so effectively even here, it cannot block higher priority one.

So considering how lower priority nominated pods are cleared unconditionally, it seems we can indeed reschedule only lower or equal priority pods.

Comment (dom4ha) [reply pkg/scheduler/eventhandlers.go:166]: WDYT about just defining `MoveLEPriorityToActiveOrBackoffQueue`?

Comment (sanposhiho) [reply pkg/scheduler/eventhandlers.go:166]: If we can achieve lower/equal priority pod filtering with `preCheck` simply, I would just use `MoveAllToActiveOrBackoffQueue`, but if we need something complicated, then a new function would make sense.

Comment (macsko) [reply pkg/scheduler/eventhandlers.go:166]: I like the idea with new method suited precisely for lower priority pods moving. I would limit usage of preCheck outside the scheduling queue, as it's risky. PreCheck can be used in this new method obviously, calling internal `moveAllToActiveOrBackoffQueue`.

Comment (sanposhiho) [reply pkg/scheduler/eventhandlers.go:166]: I don't regard my opinion above that strong, either is fine actually. Just go with what you'd like

Comment (dom4ha) [reply pkg/scheduler/eventhandlers.go]: Used preCheck eventually

File: pkg/scheduler/eventhandlers_test.go [hunk 2]
```diff
@@ -42,18 +45,173 @@ import (
...
+			updateFunc: func(s *Scheduler) {
+				updatedPod := medPriorityPod.DeepCopy()
+				updatedPod.Status.NominatedNodeName = "node2"
+				updatedPod.ResourceVersion = "1"
+				s.updatePodInSchedulingQueue(medPriorityPod, updatedPod)
+			},
+			wantInActive: []string{lowPriorityPod.Name, medPriorityPod.Name},
+		},
+		{
+			name: "Removal of a nominated node name should should trigger rescheduling of lower priority pods",
```
Comment (haosdent) [inline pkg/scheduler/eventhandlers_test.go:113]: Is there a typo at here ? `should should trigger`

File: pkg/scheduler/eventhandlers_test.go [hunk 3]
```diff
@@ -42,18 +45,173 @@ import (
...
+	"k8s.io/kubernetes/pkg/scheduler/util"
 	"k8s.io/kubernetes/pkg/scheduler/util/assumecache"
 )
 
+func TestEventHandlers_MoveToActiveOnNominatedNodeUpdate(t *testing.T) {
+	metrics.Register()
+	highPriorityPod :=
+		st.MakePod().Name("hpp").Namespace("ns1").UID("hppns1").Priority(highPriority).SchedulerName(testSchedulerName).Obj()
+
+	medPriorityPod :=
```
Comment (haosdent) [inline pkg/scheduler/eventhandlers_test.go:67]: Do we need an extra pod to verify the "equal" case in

```
			name: "Removeal of a pod that had nominated node name should trigger rescheduling of lower priority pods",
			updateFunc: func(s *Scheduler) {
				s.deletePodFromSchedulingQueue(medPriorityPod)
			},
			wantInActive: []string{lowPriorityPod.Name},
```

File: pkg/scheduler/eventhandlers_test.go [hunk 4]
```diff
@@ -42,18 +45,173 @@ import (
...
+					if !isNameOnTheList(pod.Name, tt.wantInActive) {
+						t.Error("Found unexpected pod in activeQ", "pod", pod.Name)
+					}
+				}
+			})
+		}
+	}
+}
+
+func isNameOnTheList(str string, list []string) bool {
```
Comment (haosdent) [inline pkg/scheduler/eventhandlers_test.go:201]: Should we use the set utils from https://github.com/kubernetes/kubernetes/blob/25be4a4bd409249ce9f1289b3cd16b3119df80f4/staging/src/k8s.io/apimachinery/pkg/util/sets/set_generic_test.go#L27-L37

File: pkg/scheduler/eventhandlers.go [hunk 5]
```diff
@@ -195,8 +205,19 @@ func (sched *Scheduler) deletePodFromSchedulingQueue(obj interface{}) {
 	// If a waiting pod is rejected, it indicates it's previously assumed and we're
 	// removing it from the scheduler cache. In this case, signal a AssignedPodDelete
 	// event to immediately retry some unscheduled Pods.
+	// Similarly when a pod that had nominated node is deleted, it can unblock scheduling of other pods,
+	// because the lower or equal priority pods treat such a pod as if it was assigned.
 	if fwk.RejectWaitingPod(pod.UID) {
 		sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue(logger, framework.EventAssignedPodDelete, pod, nil, nil)
+	} else if pod.Status.NominatedNodeName != "" {
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go:212]: Technically, these two `if` could be both true?

```suggestion
 if pod.Status.NominatedNodeName != "" {
```

File: pkg/scheduler/eventhandlers.go [hunk 6]
```diff
@@ -160,6 +160,16 @@ func (sched *Scheduler) updatePodInSchedulingQueue(oldObj, newObj interface{}) {
 
 	logger.V(4).Info("Update event for unscheduled pod", "pod", klog.KObj(newPod))
 	sched.SchedulingQueue.Update(logger, oldPod, newPod)
+	if hasNominatedNodeNameChanged(oldPod, newPod) {
+		// Nominated node changed in pod, so we need to treat it as if the pod was deleted,
+		// because the lower or equal priority pods treat such a pod as if it was assigned.
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go:165]:
```suggestion
		// Nominated node changed in pod, so we need to treat it as if the pod was deleted from the old nominated node,
		// because the scheduler treats such a pod as if it was already assigned when scheduling lower or equal priority pods.
```

File: pkg/scheduler/eventhandlers.go [hunk 7]
```diff
@@ -195,8 +205,19 @@ func (sched *Scheduler) deletePodFromSchedulingQueue(obj interface{}) {
...
+	// Similarly when a pod that had nominated node is deleted, it can unblock scheduling of other pods,
+	// because the lower or equal priority pods treat such a pod as if it was assigned.
 	if fwk.RejectWaitingPod(pod.UID) {
 		sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue(logger, framework.EventAssignedPodDelete, pod, nil, nil)
+	} else if pod.Status.NominatedNodeName != "" {
+		sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue(logger, framework.EventAssignedPodDelete, pod, nil, getLEPriorityPreCheck(pod.Spec.Priority))
+	}
+}
+
+// PreCheck that selects only lower or equal priority pods.
```
Comment (sanposhiho) [inline pkg/scheduler/eventhandlers.go:217]:
```suggestion
// getLEPriorityPreCheck is a PreEnqueueCheck function that selects only lower or equal priority pods.
```

**Review by sanposhiho — COMMENTED** [review]
You need an update on 
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/types.go#L157

**Comment by sanposhiho** [comment]
release note suggestion:

```diff
-Trigger rescheduling of pods when a nominated node name of some pod has changed or the pod was deleted.
+Trigger rescheduling of pods if necessary when pods with nominated node names got deleted or nominated on other nodes.
```

File: pkg/scheduler/eventhandlers_test.go [hunk 8]
```diff
@@ -42,18 +45,173 @@ import (
...
+					queue.AddUnschedulableIfNotPresent(logger, poppedPod, queue.SchedulingCycle())
+				}
+
+				s, _, err := initScheduler(ctx, schedulerCache, queue, client, informerFactory)
+				if err != nil {
+					t.Fatal(err)
+				}
+
+				if len(s.SchedulingQueue.PodsInActiveQ()) > 0 {
+					t.Error("No pods were expected to be in to activeQ before the update, but there were some", "actual", s.SchedulingQueue.PodsInActiveQ())
```
Comment (macsko) [inline pkg/scheduler/eventhandlers_test.go:185]: I'm not sure if this way of error logging is correct. This will just produce a string like this:
`No pods were expected to be in to activeQ before the update, but there were some actual 5`

You should use `t.Errorf` instead, e.g.

```suggestion
					t.Errorf("No pods were expected to be in to activeQ before the update, but there were %v", s.SchedulingQueue.PodsInActiveQ())
```

File: test/integration/scheduler/eventhandler/eventhandler_test.go [hunk 9]
```diff
@@ -135,3 +142,126 @@ func TestUpdateNodeEvent(t *testing.T) {
...
+				pod, err = testutils.CreatePausePod(testCtx.ClientSet, podLow)
+				if err != nil {
+					t.Fatalf("Creating pod error: %v", err)
+				}
+				if err := testutils.WaitForPodUnschedulable(testCtx.Ctx, testCtx.ClientSet, pod); err != nil {
+					t.Fatalf("Pod %v was not scheduled: %v", pod.Name, err)
+				}
+
+				// Update causing the nominated pod to be removed, which should trigger scheduling of the low priority pod.
+				// Note that the update has to happen since the nominated pod is still in the backoffQ to actually test updates of nominated, but not binded yet pods.
```
Comment (macsko) [inline test/integration/scheduler/eventhandler/eventhandler_test.go:256]:
```suggestion
				// Note that the update has to happen since the nominated pod is still in the backoffQ to actually test updates of nominated, but not bound yet pods.
```

File: test/integration/scheduler/eventhandler/eventhandler_test.go [hunk 10]
```diff
@@ -135,3 +142,126 @@ func TestUpdateNodeEvent(t *testing.T) {
...
+				if err != nil {
+					t.Fatalf("Creating pod error: %v", err)
+				}
+				if err = testutils.WaitForPodToSchedule(testCtx.ClientSet, pod); err != nil {
+					t.Fatalf("Pod %v was not scheduled: %v", pod.Name, err)
+				}
+			},
+		},
+		{
+			name: "Remove nominated node",
```
Comment (macsko) [inline test/integration/scheduler/eventhandler/eventhandler_test.go:198]: To be consistent with the first test case name
```suggestion
			name: "Remove nominated pod",
```

File: pkg/scheduler/eventhandlers_test.go [hunk 11]
```diff
@@ -42,18 +45,173 @@ import (
...
+	medPriorityPod :=
+		st.MakePod().Name("mpp").Namespace("ns2").UID("mppns1").Priority(midPriority).SchedulerName(testSchedulerName).NominatedNodeName("node1").Obj()
+
+	lowPriorityPod :=
+		st.MakePod().Name("lpp").Namespace("ns3").UID("lppns1").Priority(lowPriority).SchedulerName(testSchedulerName).Obj()
+
+	unschedulablePods := []*v1.Pod{highPriorityPod, medPriorityPod, lowPriorityPod}
+
+	// Make pods schedulable on Delete event when QHints are enabled, but not when nominated node appears.
+	queueHintReturnQueue := func(logger klog.Logger, pod *v1.Pod, oldObj, newObj interface{}) (framework.QueueingHint, error) {
```
Comment (macsko) [inline pkg/scheduler/eventhandlers_test.go:76]: Maybe use better name. This name is confusing, because the func is returning QueueSkip as well.

File: pkg/scheduler/eventhandlers_test.go [hunk 12]
```diff
@@ -42,18 +45,173 @@ import (
...
+		oldPod, newPod, err := util.As[*v1.Pod](oldObj, newObj)
+		if err != nil {
+			t.Fatal(err)
+		}
+		if oldPod != nil && oldPod.Status.NominatedNodeName == "" && newPod != nil && newPod.Status.NominatedNodeName != "" {
+			return framework.QueueSkip, nil
+		}
+		return framework.Queue, nil
```
Comment (macsko) [inline pkg/scheduler/eventhandlers_test.go:84]: Theoretically it could be just:
```suggestion
		oldPod, _, err := util.As[*v1.Pod](oldObj, newObj)
		if err != nil {
			t.Fatal(...)
		}
		if oldPod.Status.NominatedNodeName == "" {
			return framework.QueueSkip, nil
		}
		return framework.Queue, nil
```
This QHint is registered only for PodDelete event, so we are sure `oldPod != nil` and `newPod == nil`.

Comment (dom4ha) [reply pkg/scheduler/eventhandlers_test.go:84]: Ah, true

File: pkg/scheduler/eventhandlers_test.go (hunk 3 above)
Comment (dom4ha) [reply pkg/scheduler/eventhandlers_test.go:67]: Good point

File: test/integration/scheduler/eventhandler/eventhandler_test.go [hunk 13]
```diff
@@ -135,3 +142,126 @@ func TestUpdateNodeEvent(t *testing.T) {
...
+
+	for _, tt := range tests {
+		for _, qHintEnabled := range []bool{false, true} {
+			t.Run(fmt.Sprintf("%s, with queuehint(%v)", tt.name, qHintEnabled), func(t *testing.T) {
+				featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SchedulerQueueingHints, qHintEnabled)
+
+				testCtx, teardown := schedulerutils.InitTestSchedulerForFrameworkTest(t, testContext, 0,
+					// UpdateFunc needs to be called when the nominated pod is still in the backoff queue, thus small, but non 0 value.
+					scheduler.WithPodInitialBackoffSeconds(2),
+					scheduler.WithPodMaxBackoffSeconds(2),
```
[the remark this answers is not in the document]
Comment (dom4ha) [reply test/integration/scheduler/eventhandler/eventhandler_test.go:213]: It's a bit problematic to get rid of this possiblity. First of all, the test needs to replace the nominated pod while it's still in scheduling queues (before the nomination turns into assume).

Originally I tried first to stop the pod in permit phase, but unfortunately permit was after assume. I actually found another issue, since after assume the test was failing. I realized that the update event distinguishes whether the pod is assinged vs in scheduling queue, so assumed case still falls into `updatePodInSchedulingQueue`. It's easy to fix (in assume we should still trigger move to active), but it will add one more test case to cover, so I consider doing it in a separate PR (fixing the same bug).

The options that I see here are:
1. Extend the Scheduler with clock injection (add `.WithClock option`), to be able to move the time forward
1. Block the pod on scheudling gate

I'm in favor of the fist option, but I'd prefer to ask first before I make the change.

[the remark this answers is not in the document]
Comment (macsko) [reply test/integration/scheduler/eventhandler/eventhandler_test.go:213]: First option looks better and won't introduce much more complexity to the test compared to second option.

**Comment by dom4ha** [comment]
@sanposhiho, @macsko, @haosdent  Sorry for the delay in applying your comments, PTAL

File: pkg/scheduler/eventhandlers.go [hunk 14]
```diff
@@ -195,8 +205,21 @@ func (sched *Scheduler) deletePodFromSchedulingQueue(obj interface{}) {
...
+		// Note that a nominated pod can fall into `RejectWaitingPod` case as well,
+		// but in that case the `MoveAllToActiveOrBackoffQueue` already covered lower priority pods.
+		sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue(logger, framework.EventAssignedPodDelete, pod, nil, getLEPriorityPreCheck(pod.Spec.Priority))
+	}
+}
+
+// getLEPriorityPreCheck is a PreEnqueueCheck function that selects only lower or equal priority pods.
+func getLEPriorityPreCheck(priority *int32) queue.PreEnqueueCheck {
+	return func(pod *v1.Pod) bool {
+		return *pod.Spec.Priority <= *priority
```
Comment (macsko) [inline pkg/scheduler/eventhandlers.go:222]: I think priorities can be nil, so you could use `corev1helpers.PodPriority(pod)` from `"k8s.io/component-helpers/scheduling/corev1"` to obtain the values.

File: pkg/scheduler/eventhandlers_test.go [hunk 15]
```diff
@@ -42,18 +45,168 @@ import (
...
+		},
+		{
+			name: "Removal of a nominated node name should trigger rescheduling of lower priority pods",
+			updateFunc: func(s *Scheduler) {
+				updatedPod := medNominatedPriorityPod.DeepCopy()
+				updatedPod.Status.NominatedNodeName = ""
+				updatedPod.ResourceVersion = "1"
+				s.updatePodInSchedulingQueue(medNominatedPriorityPod, updatedPod)
+			},
+			wantInActive: sets.New[string](lowPriorityPod.Name, medPriorityPod.Name, medNominatedPriorityPod.Name),
```
Comment (macsko) [inline pkg/scheduler/eventhandlers_test.go:122]: Please simplify here and below:
```suggestion
			wantInActive: sets.New(lowPriorityPod.Name, medPriorityPod.Name, medNominatedPriorityPod.Name),
```

File: pkg/scheduler/framework/runtime/framework.go [hunk 16]
```diff
@@ -1031,7 +1031,7 @@ func (f *frameworkImpl) RunFilterPluginsWithNominatedPods(ctx context.Context, s
 // addNominatedPods adds pods with equal or greater priority which are nominated
```
[the remark this answers is not in the document]
Comment (macsko) [reply pkg/scheduler/framework/runtime/framework.go:1031]: Bump

File: test/integration/scheduler/eventhandler/eventhandler_test.go [hunk 17]
```diff
@@ -135,3 +144,136 @@ func TestUpdateNodeEvent(t *testing.T) {
...
+				// Create another low-priority pods which cannot be scheduled due to resource constraints.
+				pod, err = testutils.CreatePausePod(testCtx.ClientSet, podLow)
+				if err != nil {
+					t.Fatalf("Creating pod error: %v", err)
+				}
+				if err := testutils.WaitForPodUnschedulable(testCtx.Ctx, testCtx.ClientSet, pod); err != nil {
+					t.Fatalf("Pod %v was not scheduled: %v", pod.Name, err)
+				}
+
+				// Update causing the nominated pod to be removed, which should trigger scheduling of the low priority pod.
```
Comment (sanposhiho) [inline test/integration/scheduler/eventhandler/eventhandler_test.go:264]:
```suggestion
				// Update causing the nominated pod to be removed or to get its nominated node name removed, which should trigger scheduling of the low priority pod.
```

File: test/integration/scheduler/eventhandler/eventhandler_test.go [hunk 18]
```diff
@@ -135,3 +144,136 @@ func TestUpdateNodeEvent(t *testing.T) {
...
+				if err := testutils.WaitForPodUnschedulable(testCtx.Ctx, testCtx.ClientSet, pod); err != nil {
+					t.Errorf("Pod %v haven't become unschedulabe: %v", pod.Name, err)
+				}
+
+				// Remove the initial, which will move the nominated unschedulable back to the backoff queue.
+				if err := testutils.DeletePod(testCtx.ClientSet, podLow.Name, podLow.Namespace); err != nil {
+					t.Fatalf("Deleting pod error: %v", err)
+				}
+
+				// Create another low-priority pods which cannot be scheduled due to resource constraints.
```
Comment (sanposhiho) [inline test/integration/scheduler/eventhandler/eventhandler_test.go:255]:
```suggestion
				// Create another low-priority pods which cannot be scheduled because the mid-priority pod is nominated on the node and the node doesn't have enough resource to have two pods both.
```

**Review by sanposhiho — COMMENTED** [review]
only nits, lgtm overall

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by sanposhiho** [comment]
/assign @dims 

for `/test` change

**Comment by dims** [comment]
test changes look good.

/lgtm
/approve
