### PR TITLE
Make sure loadbalancer service is deleted before exiting the test

### LINKED ISSUE #82186: [Failing Test] [sig-network] Services should only allow access from service loadbalancer source ranges [Slow] is failing in ci-kubernetes-e2e-gce-scale-correctness
**Which jobs are failing**:
* ci-kubernetes-e2e-gce-scale-correctness

**Which test(s) are failing**:
[sig-network] Services should only allow access from service loadbalancer source ranges [Slow]

**Since when has it been failing**:
It has been failing since 8/28.
Here is the k/k diff for additional context: https://github.com/kubernetes/kubernetes/compare/169876553...f0be44792

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

**Reason for failure**:
Seems like they were two instances of the same test (at least in the latest run).
One of them failed with the following error message:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:152
Aug 30 13:08:39.388: Couldn't delete ns: "services-1078": namespace services-1078 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain (&errors.errorString{s:"namespace services-1078 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain"})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:336
```

The other one with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:152
Aug 30 13:45:28.619: Couldn't delete ns: "services-1101": namespace services-1101 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain (&errors.errorString{s:"namespace services-1101 was not deleted with limit: timed out waiting for the condition, namespaced content other than pods remain"})
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:336
```

/milestone v1.16
/priority critical-urgent
/kind failing-test
/cc @kubernetes/sig-scalability-test-failures
/cc @kubernetes/sig-node-test-failures 
/cc @wojtek-t @shyamjvs

### PR DESCRIPTION
**Pull request by MrHohn**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Ref https://github.com/kubernetes/kubernetes/issues/82186#issuecomment-527674286, I originally planed to bump the namespace deletion timeout on large cluster, but later realized it makes more sense to make sure the loadbalancer service is cleaned up before exiting the test, so we don't simply lay the burden to the test framework.

This PR applies the same fix to other relevant LB tests as well.

**Which issue(s) this PR fixes**:

Fixes #82186 

**Special notes for your reviewer**:
cc @oxddr @lachie83 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -1723,9 +1724,6 @@ var _ = SIGDescribe("Services", func() {
 			jig.SanityCheckService(svc, v1.ServiceTypeLoadBalancer)
 			framework.ExpectEqual(e2eservice.GetIngressPoint(lbIngress), internalStaticIP)
 		}
-
-		ginkgo.By("switching to ClusterIP type to destroy loadbalancer")
-		jig.ChangeServiceType(svc.Namespace, svc.Name, v1.ServiceTypeClusterIP, createTimeout)
```
Comment (MrHohn) [inline test/e2e/network/service.go]: Note: we won't need this extra step if we simply wait for service deletion in the end.

File: test/e2e/network/service.go [hunk 2]
```diff
@@ -1565,14 +1565,9 @@ var _ = SIGDescribe("Services", func() {
 			svc.Spec.LoadBalancerSourceRanges = []string{acceptPod.Status.PodIP + "/32"}
 		})
 
-		// Clean up loadbalancer service
 		defer func() {
-			jig.UpdateServiceOrFail(svc.Namespace, svc.Name, func(svc *v1.Service) {
-				svc.Spec.Type = v1.ServiceTypeNodePort
-				svc.Spec.LoadBalancerSourceRanges = nil
-			})
-			err := cs.CoreV1().Services(svc.Namespace).Delete(svc.Name, nil)
```
Comment (MrHohn) [inline test/e2e/network/service.go]: This is not enough because it doesn't wait for service to be actually gone.

**Comment by oomichi** [comment]
The change itself seems good for me.
The test file contains the same cleanup code like https://github.com/kubernetes/kubernetes/blob/6cb788c80e93bf0292f0a846ff1b55f690fcc970/test/e2e/network/service.go#L289-L293 and https://github.com/kubernetes/kubernetes/blob/6cb788c80e93bf0292f0a846ff1b55f690fcc970/test/e2e/network/service.go#L955-L959

Will we cover them with another PR?

/cc @oomichi

**Comment by MrHohn** [comment]
Thanks all for taking the look. @oomichi the two places you mentioned create `ClusterIP` and `NodePort` service, hence are irrelevant to the loadbalancer change here.
