### PR TITLE
Fix data race in garbage collector on node.owners field

### LINKED ISSUE #135621: DATA RACE garbage collector: blockingDependents
### What happened?

kube-controller-manager compiled with -race and tested with various E2E tests in a kind cluster [led to](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133844/pull-kubernetes-e2e-kind-alpha-beta-features-race/1996896534980988928):

#### kube-system/kube-controller-manager-kind-control-plane/kube-controller-manager

  
      Read at 0x00c004c37cf8 by goroutine 2258:
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*node).blockingDependents()
            k8s.io/kubernetes/pkg/controller/garbagecollector/graph.go:182 +0xb8
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).processDeletingDependentsItem()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:655 +0x65
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).attemptToDeleteItem()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:547 +0x14eb
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).attemptToDeleteWorker()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:347 +0x17e
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).processAttemptToDeleteWorker()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:304 +0x158
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:289 +0x47
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker-fm()
            <autogenerated>:1 +0x21
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:289 +0x47
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker-fm()
            <autogenerated>:1 +0x21
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:289 +0x47
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).runAttemptToDeleteWorker-fm()
            <autogenerated>:1 +0x21
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x98
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
        k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:223 +0x108
        k8s.io/apimachinery/pkg/util/wait.UntilWithContext()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:172 +0x87
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).Run.func4()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:174 +0x37
        sync.(*WaitGroup).Go.func1()
            sync/waitgroup.go:239 +0x5d
      
      Previous write at 0x00c004c37cf8 by goroutine 1427:
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GraphBuilder).processGraphChanges()
            k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:786 +0x1c04
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GraphBuilder).runProcessGraphChanges()
            k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:688 +0x54
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GraphBuilder).Run.func1()
            k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:396 +0xe
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x2e
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext.func1()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:255 +0x98
        k8s.io/apimachinery/pkg/util/wait.BackoffUntilWithContext()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:256 +0xed
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:233 +0x8a
        k8s.io/apimachinery/pkg/util/wait.JitterUntil()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:210 +0xfb
        k8s.io/apimachinery/pkg/util/wait.Until()
            k8s.io/apimachinery/pkg/util/wait/backoff.go:163 +0x444
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GraphBuilder).Run()
            k8s.io/kubernetes/pkg/controller/garbagecollector/graph_builder.go:396 +0x370
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).Run.func2()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:154 +0x5c
        sync.(*WaitGroup).Go.func1()
            sync/waitgroup.go:239 +0x5d
      
      Goroutine 2258 (running) created at:
        sync.(*WaitGroup).Go()
            sync/waitgroup.go:237 +0x86
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).Run()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:173 +0x786
        k8s.io/kubernetes/cmd/kube-controller-manager/app.(*garbageCollectorController).Run.func1()
            k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:813 +0x6a
        k8s.io/kubernetes/cmd/kube-controller-manager/app.runFuncSlice.Run.func1()
            k8s.io/kubernetes/cmd/kube-controller-manager/app/controller_utils.go:37 +0x9c
      
      Goroutine 1427 (running) created at:
        sync.(*WaitGroup).Go()
            sync/waitgroup.go:237 +0x86
        k8s.io/kubernetes/pkg/controller/garbagecollector.(*GarbageCollector).Run()
            k8s.io/kubernetes/pkg/controller/garbagecollector/garbagecollector.go:153 +0x4ca
        k8s.io/kubernetes/cmd/kube-controller-manager/app.(*garbageCollectorController).Run.func1()
            k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:813 +0x6a
        k8s.io/kubernetes/cmd/kube-controller-manager/app.runFuncSlice.Run.func1()
            k8s.io/kubernetes/cmd/kube-controller-manager/app/controller_utils.go:37 +0x9c

Read:

https://github.com/kubernetes/kubernetes/blob/4e94e70dcad423e9f59f12ac5a048d2137d20e86/pkg/controller/garbagecollector/graph.go#L182

Write:

https://github.com/kubernetes/kubernetes/blob/4e94e70dcad423e9f59f12ac5a048d2137d20e86/pkg/controller/garbagecollector/graph_builder.go#L786

### What did you expect to happen?

No race

### How can we reproduce it (as minimally and precisely as possible)?

Follow the steps from https://github.com/kubernetes/kubernetes/pull/133844 or watch that PR.

### Anything else we need to know?

Found in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133844/pull-kubernetes-e2e-kind-alpha-beta-features-race/1996896534980988928

/sig api-machinery
/cc @liggitt 

### Kubernetes version

3025b0a7b4b9fba6110759e905346ead5c9c0720

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by grandeit**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Add ownersLock to protect concurrent access to node.owners between GraphBuilder.processGraphChanges() (writer) and GC worker goroutines reading in blockingDependents() and unblockOwnerReferences() methods.

Also fix concurrent reads in the HTTP debug handler (/graph endpoint) for owners, dependents, beingDeleted, deletingDependents, and virtual fields by using their respective thread-safe accessor methods.

#### Which issue(s) this PR is related to:

Fixes: #135621

#### Special notes for your reviewer:

The fix follows the existing locking pattern in the node struct (dependentsLock, beingDeletedLock, etc.). GraphBuilder's own reads of `node.owners` remain as direct field access since it is single-threaded and the only writer.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/garbagecollector/graph.go [hunk 1]
```diff
@@ -79,25 +79,25 @@ type node struct {
...
 	// when processing an Update event, we need to compare the updated
 	// ownerReferences with the owners recorded in the graph.
-	owners []metav1.OwnerReference
+	owners     []metav1.OwnerReference
+	ownersLock sync.RWMutex
 }
 
 // clone() must only be called from the single-threaded GraphBuilder.processGraphChanges()
 func (n *node) clone() *node {
+	owners := n.getOwners()
```
Comment (liggitt) [inline pkg/controller/garbagecollector/graph.go]: hmm... `clone()` already documents it must only be called from the single-threaded `processGraphChanges` function, and reads from a bunch of fields we normally only access via lock (n.dependents, n.deletingDependents, n.beingDeleted, n.virtual, n.owners). Was this actually the function that was racing or did you just modify owners here for completeness?

Comment (grandeit) [reply pkg/controller/garbagecollector/graph.go]: I added this here for consistency because I wanted to make sure the comment is somewhat _enforced_.

Comment (liggitt) [reply pkg/controller/garbagecollector/graph.go]: using it here under lock makes all the other fields look like bugs, when I'm not sure they actually are... since this is documented as being callable only from a single-thread location where no fields are being mutated, I don't think we should treat this one guarded field differently in this location

Comment (grandeit) [reply pkg/controller/garbagecollector/graph.go]: Makes sense. I will remove the lock use here.
