### PR TITLE
Fix code to handle delayed binding volumes

### LINKED ISSUE #73724: Volume attach limit doesn't work for `WaitForFirstConsumer` Volume binding mode
**What happened**:

Volume binding mode `WaitForFirstConsumer` doesn't consider the volume attach limit per node. 

**What you expected to happen**:

`WaitForFirstConsumer` volume binding mode should have respected the attach limit, similar to `Immediate` binding mode.

**How to reproduce it (as minimally and precisely as possible)**:

In CSI driver, configured the volume-attach limit to 1 per node on a 3 node cluster. 

In `Immediate` volume binding mode, only 3 pods with 3 PV/PVCs runs.
In `WaitForFirstConsumer` binding mode, all 5 pods runs with 5PV/PVCs on 3 node cluster. (Actually 4 pods scheduled on 1 node and 1 on other node, 3rd didn't have any pod scheduled)

**Anything else we need to know?**:

I was able to reproduced it with minimal node and configuration, and also hit this for stress case with 100 Volume limit and >500 pods running on the 5 mode cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): 

➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: On-prem linux server
- OS (e.g. from /etc/os-release): Centos 7

- Kernel (e.g. `uname -a`): 3.10.0
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by gnufied**
This fixes counting of volumes that are not immediate binded.

fixes https://github.com/kubernetes/kubernetes/issues/73724

/sig storage

```release-note
Count PVCs that are unbound towards attach limit
```

### CODE REVIEW

**Comment by bsalamat** [comment]
Please follow [instructions here](https://github.com/kubernetes/community/pull/3192/) to post scheduler benchmarks before and after this PR.

**Comment by gnufied** [comment]
Something is wrong with my setup of scheduler integration tests:

```
I0211 15:18:29.083115   22229 retry.go:149] clientv3/auth-retry: error "context canceled" on pinned endpoint "127.0.0.1:2379"                                                                                       
E0211 15:18:29.083160   22229 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}                                                                     
E0211 15:18:29.083204   22229 writers.go:172] apiserver was unable to write a JSON response: http: Handler timeout                                                                                                  
I0211 15:18:29.083304   22229 wrap.go:47] GET /apis/rbac.authorization.k8s.io/v1/clusterroles: (1m0.000470325s) 504                                                                                                 
goroutine 1560647 [running]:                      
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc01b901c70, 0x1f8)                                                                                                        
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xd2                                                       
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc01b901c70, 0x1f8)                                                                                                         
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35                                                       
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc03fab6aa0, 0xc020a2ef30)                                                                                               
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:218 +0xb5                                                       
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc04d746040, 0x5db9ce0, 0xc01b901c70, 0xc01482fa00)                                                                       
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:118 +0x2aa                                                      
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x5db9ce0, 0xc01b901c70, 0xc01482f900)                                                                                             
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd6                                                      
net/http.HandlerFunc.ServeHTTP(0xc04d774b10, 0x5db9ce0, 0xc01b901c70, 0xc01482f900)                
        /data/go/src/net/http/server.go:1964 +0x44                                                                                  
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x5db9ce0, 0xc01b901c70, 0xc01482f800)                                                                                        
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x217                                                
net/http.HandlerFunc.ServeHTTP(0xc04d774b40, 0x5db9ce0, 0xc01b901c70, 0xc01482f800)  
        /data/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x5db9ce0, 0xc01b901c70, 0xc01482f800)                                                                                         
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x127                                                          
net/http.HandlerFunc.ServeHTTP(0xc04d746060, 0x5dbada0, 0xc033987420, 0xc01482f800)
        /data/go/src/net/http/server.go:1964 +0x44 
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc04d774b70, 0x5dbada0, 0xc033987420, 0xc01482f800)                                                                             
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51                                                               
k8s.io/kubernetes/test/integration/util.StartApiserver.func1(0x5dbada0, 0xc033987420, 0xc01482f800)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/util/util.go:44 +0x72                                                                                
net/http.HandlerFunc.ServeHTTP(0xc01b95c690, 0x5dbada0, 0xc033987420, 0xc01482f800)                                                            
        /data/go/src/net/http/server.go:1964 +0x44                                                                
net/http.serverHandler.ServeHTTP(0xc01d1a8000, 0x5dbada0, 0xc033987420, 0xc01482f800)                              
        /data/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc013255220, 0x5dc4ea0, 0xc04f058980)                                               
        /data/go/src/net/http/server.go:1847 +0x646                                                                                                          
created by net/http.(*Server).Serve                                                                        
        /data/go/src/net/http/server.go:2851 +0x2f5                                                                                                          
                                                                                                                     
logging error output: "{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within 1m0s\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}\n"                                 
 [scheduler_perf.test/v0.0.0 (linux/amd64) kubernetes/$Format 127.0.0.1:55076]                                                               
E0211 15:18:29.083507   22229 master_utils.go:234] last health content: ""                                                                                    
F0211 15:18:29.083530   22229 master_utils.go:235] timed out waiting for the condition                                 
E0211 15:18:29.440434   22229 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}                                                                
W0211 15:18:29.083562   22229 storage_scheduling.go:95] unable to get PriorityClass system-node-critical: the server was unable to return a response in the time allotted, but may still be processing the request (get priorityclasses.scheduling.k8s.io system-node-critical). Retrying...
exit status 255                                                                                                             
FAIL    k8s.io/kubernetes/test/integration/scheduler_perf       203.972s                         
```

@bsalamat fwiw - this PR should not introduce any regression in scheduler performance because all it does is - it ensures we are counting unbound but scheduled PVCs towards volume limit.

**Comment by gnufied** [comment]
@bsalamat so I ran`../test-performance.sh` which gave me..

Before:
```
Scheduled 3000 Pods in 3 seconds (1000 per second on average). min QPS was 207
```

After:
```
Scheduled 3000 Pods in 3 seconds (1000 per second on average). min QPS was 206
```

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 1]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+	placeHolderCSIDriver := ""
+	placeHolderHandle := ""
+	if pvName == "" {
+		klog.V(4).Infof("Persistent volume had no name for claim %s/%s", namespace, pvcName)
+		return c.getDriverNameFromSC(pvc)
+	}
+	pv, err := c.pvInfo.GetPersistentVolumeInfo(pvName)
+
+	if err != nil {
+		klog.V(4).Infof("Unable to look up PV info for PVC %s/%s and PV %s", namespace, pvcName, pvName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: Can you add a comment here that this is an error condition where either:
* User prebound the PVC to a non-existing PV
* PV object got deleted erroneously

Should we fallback to SC.provisionername?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 2]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+
+func (c *CSIMaxVolumeLimitChecker) getCSIDriver(pvc *v1.PersistentVolumeClaim) (string, string) {
+	pvName := pvc.Spec.VolumeName
+	namespace := pvc.Namespace
+	pvcName := pvc.Name
+
+	placeHolderCSIDriver := ""
+	placeHolderHandle := ""
+	if pvName == "" {
+		klog.V(4).Infof("Persistent volume had no name for claim %s/%s", namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: This log could be noisy. Maybe log level 5?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 3]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+	pv, err := c.pvInfo.GetPersistentVolumeInfo(pvName)
+
+	if err != nil {
+		klog.V(4).Infof("Unable to look up PV info for PVC %s/%s and PV %s", namespace, pvcName, pvName)
+		return placeHolderCSIDriver, placeHolderHandle
+	}
+
+	csiSource := pv.Spec.PersistentVolumeSource.CSI
+	if csiSource == nil {
+		klog.V(4).Infof("Not considering non-CSI volume %s/%s", namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: This could be common. log level 5?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 4]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+
+func (c *CSIMaxVolumeLimitChecker) getDriverNameFromSC(pvc *v1.PersistentVolumeClaim) (string, string) {
+	namespace := pvc.Namespace
+	pvcName := pvc.Name
+	scName := *pvc.Spec.StorageClassName
+
+	placeHolderCSIDriver := ""
+	placeHolderHandle := ""
+	if scName == "" {
+		klog.V(4).Infof("pvc %s/%s has no storageClass", namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: level 5?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 5]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+		return placeHolderCSIDriver, placeHolderHandle
+	}
+
+	storageClass, err := c.scInfo.GetStorageClassInfo(scName)
+	if err != nil {
+		klog.V(4).Infof("no storage %s found for pvc %s/%s", scName, namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: level 5?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 6]
```diff
@@ -129,28 +134,62 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+		return placeHolderCSIDriver, placeHolderHandle
+	}
+
+	volumeHandle := fmt.Sprintf("%s-%s/%s", c.randomVolumeIDPrefix, namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: i forget, why is the prefix needed?

Comment (msau42) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: hmm if it's not bound, we use pvc name as the volume handle. If it's bound, we use the volumeID.  

This inconsistency might have races where the PVC got bound in the middle of the predicate.

But if we only use PVC name, then this may not work when we support inline volumes, where the same volume can be specified as a PVC and as an inline volume.  We could also just say we don't support that case...

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go [hunk 7]
```diff
@@ -77,6 +77,20 @@ func TestCSIVolumeCountPredicate(t *testing.T) {
 		},
 	}
 
+	pendingVolumePod := &v1.Pod{
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate_test.go]: can you also add some test cases for the other conditions, like scName is empty, not found, different, pv is not found, different volume type, etc.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 6 above)
Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: The prefix is used to avoid conflict with volume-ids (however unlikely).

What race you are thinking of? Even if PVC gets bound in the middle of the predicate and may be there is a pod that uses same volume inline(on same node), in worst case we end up overcounting the volume?

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 1 above)
Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: Don't we have a pv proection controller to prevent things like PV object getting deleted erroneously? First one is more likely perhaps - but then it seems like no pod can start using such a PVC.

**Comment by gnufied** [comment]
@msau42 addressed review comments PTAL.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 6 above)
Comment (msau42) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: Ah yes you're right, it would end up overcounting in that case, which is better than undercounting.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 1 above)
Comment (msau42) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: I'm trying to think of the case where someone bypasses the scheduler by directly setting Pod.nodename and they have prebound the PVC and the PV gets bound in the middle.  Then we won't count it.  But the same issue also exists if they have an empty or non-existent storageclass.  So I'm not sure if we'll be able to fully solve this race.

Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: So if they prebound the PVC then most likely it will have missing SC too right? Although likely-hood of binding happening in middle for prebound PVCs is small. I am for leaving this code as it is. I think this is "good middleground".

Comment (msau42) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: Can we require that users create a StorageClass object with correct provisioner name even for prebinding PVC/PV, in order for the volume counting to work correctly?

Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: I am not sure. So if a PVC is not bound and does not have a storageclass with delayed binding (because user is trying to submit pv/pvc/pod template at once) - won't the scheduler not schedule the pod until PVC is bound?  That seems to be my experience and in which case - for pre-bound PVCs this will be much less of a problem. Am I missing something?

Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: added fallback.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 8]
```diff
@@ -129,28 +134,64 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+	placeHolderHandle := ""
+	if pvName == "" {
+		klog.V(5).Infof("Persistent volume had no name for claim %s/%s", namespace, pvcName)
+		return c.getDriverNameFromSC(pvc)
+	}
+	pv, err := c.pvInfo.GetPersistentVolumeInfo(pvName)
+
+	if err != nil {
+		klog.V(4).Infof("Unable to look up PV info for PVC %s/%s and PV %s", namespace, pvcName, pvName)
+		// If we can't fetch PV associated with PVC, may be it got deleted
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: or PVC was prebound to a PV that hasn't been created yet

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go [hunk 9]
```diff
@@ -129,28 +134,64 @@ func (c *CSIMaxVolumeLimitChecker) filterAttachableVolumes(
...
+}
+
+func (c *CSIMaxVolumeLimitChecker) getDriverNameFromSC(pvc *v1.PersistentVolumeClaim) (string, string) {
+	namespace := pvc.Namespace
+	pvcName := pvc.Name
+	scName := pvc.Spec.StorageClassName
+
+	placeHolderCSIDriver := ""
+	placeHolderHandle := ""
+	if scName == nil {
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: Add a comment here, if storage class is not set or found, then it is immediate binding mode, which requires that the pvc is bound before scheduling, so we can safely not count it.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 6 above)
Comment (msau42) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: we'll need to consider potential ramifications of overcounting if we decide to cache counts in the future. can you add this possible race condition as a comment?

fyi persistent inline volume support got dropped so we could potentially use pvc name throughout.  although we may need to think about if we want to do any sort of counting for ephemeral volumes (not attach)

**Comment by nikopen** [comment]
@childsb @gnufied @msau42 
we're in code freeze, release is in 2 weeks from now. Is this bug urgent and release-blocking?

**Comment by spiffxp** [comment]
/milestone clear
v1.14 release lead here, given the lack of activity on this PR, I'm removing this from the milestone. Please discuss in #sig-release in slack if it's urgent this land as part of v1.14

**Comment by gnufied** [comment]
I guess we can merge this after code freeze. 

 @msau42 addressed review comments. PTAL.

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 8 above)
Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: fixed

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 9 above)
Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: fixed

File: pkg/scheduler/algorithm/predicates/csi_volume_predicate.go (hunk 6 above)
Comment (gnufied) [reply pkg/scheduler/algorithm/predicates/csi_volume_predicate.go]: I have added a comment about potential overcounting of volumes here.

**Review by bsalamat — COMMENTED** [review]
/approve

**Comment by matthias50** [comment]
@gnufied , It looks like earliest release where this is present is 1.15. Can this be back-ported to 1.14 and 1.13?
