### PR TITLE
Fix scheduler flaky test: wait for DeviceClass cache sync in dynamicresources tests

### LINKED ISSUE #137113: DRA scheduler: flaky TestPlugin/extended-resource-name-no-resource
### Which jobs are flaking?

https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-unit

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137108/pull-kubernetes-unit/2024138310519099392

### Which tests are flaking?

k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources, TestPlugin/extended-resource-name-no-resource

### Since when has it been flaking?

Unknown, only seen once in a presubmit.

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

Can be reproduced locally:

```
$ go test -c ./pkg/scheduler/framework/plugins/dynamicresources/
$ stress -p 512 ./dynamicresources.test -test.run=TestPlugin/extended-resource-name-no-resource
5s: 2048 runs so far, 0 failures

/tmp/go-stress-20260218T163653-3909757302
E0218 16:37:01.852829  224548 reflector.go:434] "Reflector stopped with error" err="context canceled" type="*v1.ResourceClaim" reflector="k8s.io/client-go/informers/factory.go:177"
E0218 16:37:01.852844  224548 reflector.go:434] "Reflector stopped with error" err="context canceled" type="*v1.DeviceClass" reflector="k8s.io/client-go/informers/factory.go:177"
E0218 16:37:01.852853  224548 reflector.go:434] "Reflector stopped with error" err="context canceled" type="*v1alpha3.DeviceTaintRule" reflector="k8s.io/client-go/informers/factory.go:177"
E0218 16:37:01.852860  224548 reflector.go:434] "Reflector stopped with error" err="context canceled" type="*v1.ResourceSlice" reflector="k8s.io/client-go/informers/factory.go:177"
--- FAIL: TestPlugin (1.00s)
    --- FAIL: TestPlugin/extended-resource-name-no-resource (1.00s)
        feature_gate.go:170: I0218 16:37:01.850093] I0218 16:37:01.850067] Updated featureGates={"DRAExtendedResource":true}
        shared_informer.go:401: I0218 16:37:01.851141] Waiting for caches to sync
        shared_informer.go:408: I0218 16:37:01.852368] Caches are synced
        --- FAIL: TestPlugin/extended-resource-name-no-resource/prefilter (0.00s)
            dynamicresources_test.go:2568: ERROR: I0218 16:37:01.852528]
                	Error Trace:	/nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:2734
                		            				/nvme/gopath/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:2568
                		            				/nvme/gopath/src/k8s.io/kubernetes/test/utils/ktesting/tcontext.go:280
                		Error:      	Expected nil, but got: &framework.Status{code:5, reasons:[]string(nil), err:error(nil), plugin:""}
                		Test:       	TestPlugin/extended-resource-name-no-resource/prefilter
        --- FAIL: TestPlugin/extended-resource-name-no-resource/filter/worker (0.00s)
```

### Relevant SIG(s)

/sig scheduling
/wg device-management
/assign @yliaog 
/cc @bart0sh

### PR DESCRIPTION
**Pull request by troychiu**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
When DRAExtendedResource is enabled, the dynamicresources test setup registers an event handler for DeviceClasses but was not waiting for it to sync. This can lead to flaky tests where the cache is not fully populated when the test starts.

This change captures the event handler registration and includes its DoneChecker in a WaitFor call.

Previously, this test was reliably failing. It can be reproduced with:
```bash
go test -c ./pkg/scheduler/framework/plugins/dynamicresources/
stress -p 512 ./dynamicresources.test -test.run=TestPlugin/extended-resource-name-no-resource
```
After applying this fix, I verified it with 100,000 consecutive runs with zero failures.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/137113

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go [hunk 1]
```diff
@@ -3072,7 +3074,11 @@ func setup(tCtx ktesting.TContext, args *config.DynamicResourcesArgs, nodes []*v
 	// is synced, we need to wait until HasSynced of the handler returns
 	// true, this ensures that the assume cache is in sync with the informer's
 	// store which has been informed by at least one full LIST of the underlying storage.
-	cache.WaitForNamedCacheSyncWithContext(tCtx, registeredHandler.HasSynced, resourceSliceTracker.HasSynced)
+	if deviceClassHandlerRegistration != nil {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Build a `doneCheckers []cache.DoneChecker` where you add all required checkers. There's no need  for the `deviceClassHandlerRegistration` variable, it can be local to the if branch above.

Then call `cache.WaitFor(ctx, doneCheckers...)` once here.

`cache.WaitFor` is a new API that wasn't available when this code was originally written.

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go (hunk 1 above)
Comment (yliaog) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: thanks @troychiu for the fix, and @pohly for the suggestion, i think this pr can be merged to fix the flake, then follow up with a refactor PR. what do you think?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Why the urgency? Let's do it right from the start. Assuming of course that @troychiu can follow up soonish, say, on Monday.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Doesn't look like it, so let's merge https://github.com/kubernetes/kubernetes/pull/137575 instead.

Comment (troychiu) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Thank you @pohly. Just update the PR.

Comment (troychiu) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Oh I see you create #137575.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Thanks!

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go [hunk 2]
```diff
@@ -3068,11 +3070,11 @@ func setup(tCtx ktesting.TContext, args *config.DynamicResourcesArgs, nodes []*v
 	})
 
 	tc.informerFactory.WaitForCacheSync(tCtx.Done())
-	// The above does not tell us if the registered handler (from NewAssumeCache)
-	// is synced, we need to wait until HasSynced of the handler returns
-	// true, this ensures that the assume cache is in sync with the informer's
+	// The above does not tell us if the registered handlers (e.g. from NewAssumeCache)
+	// are synced, we need to wait until the event handlers confirm that they are synced.
+	// This ensures that the assume cache is in sync with the informer's
```
Comment (yliaog) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:3075]: nit: it is not just assume cache, but also resource slice and device class.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go (hunk 1 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go]: Yep, we were both working on this at the same time :grin: 

Let's go with yours.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go (hunk 2 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:3075]: I read this as continuing with the example (`e.g. from NewAssumeCache`), not as a complete list.
