### PR TITLE
An interface that allows pre-filter plugins to update their pre-calculated status

### LINKED ISSUE #82897: A new API for updating prefilter calculations
**What would you like to be added**:
An interface that allows PreFilter plugins to update their state after PreFilter was called, similar to what we have for [predicates metadata (add/remove pods)](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go#L38-L41).

**Why is this needed**:
This is needed to allow efficient preemption simulations: during preemption, we remove/add pods from each node before running the filter plugins again to evaluate whether removing/adding specific pods will allow the incoming pod to be scheduled on the node. 

Roughly, a scheduling cycle with preemption works as follows (function names in the pseudo code below are made up):

- meta = ProduceMetadata(pod, nodes)
- For each nodeInfo in nodes
  - RunAllPredicates(pod, nodeInfo, meta)
- If preemption
  - for each nodeInfo in nodes   *// actual logic is in [selectVictimsOnNode](https://github.com/kubernetes/kubernetes/blob/master///pkg/scheduler/core/generic_scheduler.go#L1088:28)*
       - nodeInfoCopy, victimPods = RemoveLowerPriorityPods(nodeInfo)
       - metaCopy = meta
       - **metaCopy.RemovePods(victimPods)**
       - RunAllPredicates(pod, nodeInfoCopy, metadataCopy)

A number of predicates that we plan to migrate produce metadata, the most important of which are pod affinity and even pod spreading. The current predicate metadata interface requires implementing APIs for [adding and removing pods](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go#L38-L41).

In the scheduling framework, PreFilters will be used to compute what we currently call [predicate metadata](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/metadata.go) in the scheduler, but the preemption logic currently have no way to call the plugin again to modify that state, and so we have two options:

**Option 1**: Call PreFilter again 
- pros: 
  - does not require changes to the framework
- cons:
  - harder to migrate current predicates because that is not how predicate metadata works
  - performance regression
  - change PreFilter semantics to indicate that it can be called multiple times on the same PluginContext and pod, making PreFilter trickier to implement.

**Option 2**: Allow PreFilter plugins to implement APIs to make incremental updates to its pre-computed state.
- pros: 
  - easier to migrate current predicates
  - no performance regression
  - no changes to PreFilter semantics, stays simple.
- cons:
  - need to add more logic to the framework core.

I suggest we go with option 2. Specifically, add two optional APIs to PreFilter, namely ```AddPod``` and ```RemovePod```.  By optional I mean similar to what we did for NormalizeScore API in Score Plugins.

/assign
/sig scheduling

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

This is needed to allow efficient preemption simulations: during preemption, we remove/add pods from each node before running the filter plugins again to evaluate whether removing/ad
ding specific pods will allow the incoming pod to be scheduled on the node. Instead of calling prefilter again, we should allow the plugin to do incremental update to its pre-computed state.

**Which issue(s) this PR fixes**:
Fixes #82897

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
New APIs to allow adding/removing pods from pre-calculated prefilter state in the scheduling framework
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/label api-review
/hold feel free to cancel

Did we have a thorough discussion of whether or not exposing these API? Is this a required interface (AddPod, RemovePod) which we must provide to the developer, or just an approach to help with the performance.

Besides, it requires an API review if we change the interface of the scheduler extension point.

**Comment by ahg-g** [comment]
> /label api-review
> /hold feel free to cancel
> 
> Did we have a thorough discussion of whether or not exposing these API? Is this a required interface (AddPod, RemovePod) which we must provide to the developer, or just an approach to help with the performance.
Certainly, I created the issue to discuss the motivation. Will keep the hold until the community is comfortable with this addition.

> 
> Besides, it requires an API review if we change the interface of the scheduler extension point.
It does not actually.

File: pkg/scheduler/framework/v1alpha1/framework.go [hunk 1]
```diff
@@ -34,22 +34,23 @@ import (
...
-	postBindPlugins           []PostBindPlugin
-	unreservePlugins          []UnreservePlugin
-	permitPlugins             []PermitPlugin
+	registry                   Registry
+	nodeInfoSnapshot           *schedulernodeinfo.Snapshot
+	waitingPods                *waitingPodsMap
+	pluginNameToWeightMap      map[string]int
+	queueSortPlugins           []QueueSortPlugin
+	preFilterPlugins           []PreFilterPlugin
+	preFilterWithUpdatePlugins []PreFilterWithUpdatePlugin
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/v1alpha1/framework.go]: I'm not sure I like the idea of separating the two plugins. In a user's perspective, what they know is just a phase called "PreFilter" which "PreFilterPlugins" should be responsible for. IMO it's better to keep update related logic into another interface.

I'd propose to keep `preFilterPlugins` only, and then add a `MetaUpdater()` method in PreFilterPlugin like this:

```go
type PreFilterPlugin interface {
	Plugin
	PreFilter(pc *PluginContext, p *v1.Pod) *Status
	MetaUpdater() MetaUpdater
}
```

And `MetaUpdater` is an interface with AddPod() and RemovePod():

```go
type MetaUpdater interface {
	AddPod(pc *PluginContext, podToSchedule *v1.Pod, podToAdd *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status
	RemovePod(pc *PluginContext, podToSchedule *v1.Pod, podToRemove *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status
}
```

So `RunPreFilter[Add|Remove]Pod` method can be updated:

```go
func (f *framework) RunPreFilterAddPod(pc *PluginContext, podToSchedule *v1.Pod,
	podToAdd *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status {
	for _, pl := range f.preFilterPlugins {
		status := pl.MetaUpdater().AddPod(pc, podToSchedule, podToAdd, nodeInfo)
```

File: pkg/scheduler/framework/v1alpha1/framework.go [hunk 2]
```diff
@@ -110,6 +111,14 @@ func NewFramework(r Registry, plugins *config.Plugins, args []config.PluginConfi
 					return nil, fmt.Errorf("plugin %q does not extend prefilter plugin", pf.Name)
 				}
 				f.preFilterPlugins = append(f.preFilterPlugins, p)
+
+				// Next, if the plugin also implements PodAdd/PodRemove interfaces,
+				// add it to the prefilterWithupdateplugin list.
+				np, ok := pg.(PreFilterWithUpdatePlugin)
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/v1alpha1/framework.go]: If we keep `PreFilterPlugin` only, we don't need to check this.

File: pkg/scheduler/framework/v1alpha1/framework.go [hunk 3]
```diff
@@ -306,6 +315,42 @@ func (f *framework) RunPreFilterPlugins(
 	return nil
 }
 
+// RunPreFilterAddPod calls the AddPod interface for the set of configured
+// PreFilter plugins. It returns directly if any of the plugins return any
+// status other than Success.
+func (f *framework) RunPreFilterAddPod(pc *PluginContext, podToSchedule *v1.Pod,
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/v1alpha1/framework.go]: `RunMetaAddPod` sounds more clear to me so that it's possible in the future to enable other plugins to be called under the hood.

**Review by Huang-Wei — COMMENTED** [review]
Some comments below.

File: pkg/scheduler/framework/v1alpha1/framework.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/v1alpha1/framework.go]: The idea of the separate interfaces is that the extra methods are optional. And then we only iterate once to identify the plugins that implement the interface.
These private slices are not user (developer) facing.
And we have done the same for `scorePlugins` and `scoreWithNormalizePlugins`

Comment (ahg-g) [reply pkg/scheduler/framework/v1alpha1/framework.go]: Right, the idea is to make the methods optional, those slices are implementation details only.

Comment (Huang-Wei) [reply pkg/scheduler/framework/v1alpha1/framework.go]: Sry to confuse you. I should have commented it on the interface definitions.

So basically, instead of defining two interfaces (`PreFilterPlugin` and `PreFilterWithUpdatePlugin`), I'm leaning towards to keep one interface `PreFilterPlugin`.

With the above extra interface funtion `MetaUpdater()`, implementations that returns nil will get simply bypassed without invoking its `AddPod()` and `RemovePod()` upon preemption. Right now, we're relying on typecasting to tell whether it's a `PreFilterPlugin` or `PreFilterWithUpdatePlugin` implementation, which I'm not sure I like the way.

Comment (Huang-Wei) [reply pkg/scheduler/framework/v1alpha1/framework.go]: The above suggestion is similar like what we did in GVK:

https://github.com/kubernetes/kubernetes/blob/d62ebe31f0c9bb73217acba847cc4f5f72138823/staging/src/k8s.io/apimachinery/pkg/runtime/schema/interfaces.go#L28

Basically an API object can choose not to omit GVK by implementing `GroupVersionKind()` to simply return nil, so that API machinery won't call further GVK related methods upon this object.

Comment (ahg-g) [reply pkg/scheduler/framework/v1alpha1/framework.go]: this sounds good to me, it will also solve the confusion when a plugin implements only AddPod but not RemovePod for example, which will result in a failure in the type cast, and so AddPod will not be called contrary to what the developer may think.

Comment (alculquicondor) [reply pkg/scheduler/framework/v1alpha1/framework.go]: Would it be worth making the optional normalize for score plugins consistent with this suggestion?

Comment (Huang-Wei) [reply pkg/scheduler/framework/v1alpha1/framework.go]: I think so, but we can have it in another PR.

File: pkg/scheduler/framework/v1alpha1/framework.go (hunk 3 above)
Comment (ahg-g) [reply pkg/scheduler/framework/v1alpha1/framework.go]: I don't think we make this generic, it should be specific to prefilter (i.e., the updater in the prefilter plugins). This is internal implementation in any case.

File: pkg/scheduler/framework/v1alpha1/framework.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/framework/v1alpha1/framework.go]: Done. I named the interface "Updater" only, I think it is sufficient.

Comment (draveness) [reply pkg/scheduler/framework/v1alpha1/framework.go]: > With the above extra interface funtion `MetaUpdater()`, implementations that returns nil will get simply bypassed without invoking its `AddPod()` and `RemovePod()` upon preemption. Right now, we're relying on typecasting to tell whether it's a `PreFilterPlugin` or `PreFilterWithUpdatePlugin` implementation, which I'm not sure I like the way.

I feel the same way, it's better to implement it as a noop. I sent https://github.com/kubernetes/kubernetes/pull/83042 to remove the scoreWithNormalize interface.

File: pkg/scheduler/framework/v1alpha1/framework.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/v1alpha1/framework.go]: SG.

**Comment by Huang-Wei** [comment]
/lgtm

Thanks @ahg-g !

**Comment by ahg-g** [comment]
> /lgtm
> 
> Thanks @ahg-g !

Thanks, now that the context PR is in, I added logic to clone the context during preemption, PTAL at the last commit, if all looks good I will squash.

File: pkg/scheduler/core/generic_scheduler.go [hunk 4]
```diff
@@ -1023,7 +1023,9 @@ func (g *genericScheduler) selectNodesForPreemption(
 		if meta != nil {
 			metaCopy = meta.ShallowCopy()
 		}
-		pods, numPDBViolations, fits := g.selectVictimsOnNode(pluginContext, pod, metaCopy, nodeNameToInfo[nodeName], fitPredicates, queue, pdbs)
+		pluginContextClone := pluginContext.Clone()
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler.go]: why not do the copy in `selectVictimsNode`, given that pluginContextClone isn't used outside of it?

Also, prefer shorter names for local variables. We could start using `pCtx` instead of `pluginContext`

Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler.go]: > why not do the copy in `selectVictimsNode`, given that pluginContextClone isn't used outside of it?
> 

To be consistent with how "meta" is treated.

> Also, prefer shorter names for local variables. We could start using `pCtx` instead of `pluginContext`

we already use pluginContext everywhere.

Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler.go]: sg, they are just nits.

File: pkg/scheduler/framework/v1alpha1/context_test.go [hunk 5]
```diff
@@ -64,3 +64,11 @@ func TestPluginContextClone(t *testing.T) {
 		t.Errorf("cloned copy should not change, got %q, expected %q", v.data, data1)
 	}
 }
+
+func TestPluginContextCloneNil(t *testing.T) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/v1alpha1/context_test.go]: Ideally, this can be merged into `TestPluginContextClone` in a Golang [subtest](https://blog.golang.org/subtests) manner.

Comment (ahg-g) [reply pkg/scheduler/framework/v1alpha1/context_test.go]: I feel the boilerplate for doing will outweigh its benefit.

Comment (Huang-Wei) [reply pkg/scheduler/framework/v1alpha1/context_test.go]: Sure, it's just nits.

**Comment by Huang-Wei** [comment]
> Thanks, now that the context PR is in, I added logic to clone the context during preemption, PTAL at the last commit, if all looks good I will squash.

Please go squashing the commits.

**Comment by ahg-g** [comment]
> > Thanks, now that the context PR is in, I added logic to clone the context during preemption, PTAL at the last commit, if all looks good I will squash.
> 
> Please go squashing the commits.

Done.

File: pkg/scheduler/framework/v1alpha1/framework.go [hunk 6]
```diff
@@ -306,6 +306,46 @@ func (f *framework) RunPreFilterPlugins(
...
+}
+
+// RunPreFilterUpdaterRemovePod calls the RemovePod interface for the set of configured
+// PreFilter plugins. It returns directly if any of the plugins return any
+// status other than Success.
+func (f *framework) RunPreFilterUpdaterRemovePod(pc *PluginContext, podToSchedule *v1.Pod,
+	podToRemove *v1.Pod, nodeInfo *schedulernodeinfo.NodeInfo) *Status {
+	for _, pl := range f.preFilterPlugins {
+		if updater := pl.Updater(); updater != nil {
+			status := updater.RemovePod(pc, podToSchedule, podToRemove, nodeInfo)
```
Comment (tedyu) [inline pkg/scheduler/framework/v1alpha1/framework.go]: Since this has same signature as that of updater.AddPod , it seems this func (RunPreFilterUpdaterRemovePod) can be unified with RunPreFilterUpdaterAddPod by passing AddPod / RemovePod as parameter.
