### PR TITLE
Start informers after leader election

### LINKED ISSUE #115753: Unexpected memory usage in follower kube-scheduler processes
### What happened?

Observed unexpected memory usage in follower/non-leader `kube-scheduler` instances

### What did you expect to happen?

The `kube-scheduler` in standby mode should be only having minimum memory overhead until being elected.

### How can we reproduce it (as minimally and precisely as possible)?

* create a cluster
* run a scheduler in follower mode
* create pods with lengthy strings in PodSpec (ie. large object size)
* observe memory usage of scheduler process

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by linxiulei**
If scheduler fails to be elected, it should not start informers so that to avoid memory overhead.

Signed-off-by: Eric Lin <exlin@google.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Improve `kube-scheduler` memory efficiency

#### Which issue(s) this PR fixes:

Fixes #115753

#### Does this PR introduce a user-facing change?

```release-note
Added new config option `delayCacheUntilActive` to `KubeSchedulerConfiguration` that can provide a tradeoff between memory efficiency and scheduling speed when their leadership is updated in `kube-scheduler`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
I'm not convinced this is a bug.

Having the caches ready to go implies that when a scheduler goes down, a second one immediately picks up.

Not sure who take this decision initially or if a pro-con analysis was performed. Invoking @wojtek-t as he was involved in #45453

**Comment by aojea** [comment]
> Having the caches ready to go implies that when a scheduler goes down, a second one immediately picks up.

/lgtm cancel

that is an good point indeed

**Comment by linxiulei** [comment]
> Not sure who take this decision initially or if a pro-con analysis was performed. Invoking @wojtek-t as he was involved in #45453

I investigated it a bit. As far as I could see for other components (eg. KCM), they only start caching after leader election. Maybe scheduler is very latency sensitive but IMHO, I'd prefer memory efficiency than scheduling latency here.

**Comment by alculquicondor** [comment]
>  I'd prefer memory efficiency than scheduling latency here.

Sounds like it should be an option. Not everyone would be happy with this.

**Comment by kerthcet** [comment]
I think quick failover is important for HA, so prefer to keep the change. I would not take it a bug.
/remove-kind bug
/kind cleanup ?

**Comment by linxiulei** [comment]
> Sounds like it should be an option. Not everyone would be happy with this.

Changed to be controlled by a config option. PTAL.

File: pkg/scheduler/apis/config/types.go [hunk 1]
```diff
@@ -96,6 +96,10 @@ type KubeSchedulerConfiguration struct {
 	// Extenders are the list of scheduler extenders, each holding the values of how to communicate
 	// with the extender. These extenders are shared by all scheduler profiles.
 	Extenders []Extender
+
+	// NoCacheNonLeader disables caching for non-leader candidates. This makes non-leader candidates
+	// not start watching cache. Doing so will lower memory usage with slower failover.
+	NoCacheNonLeader bool
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/types.go:102]: Avoid double-negative. Maybe `MaintainCacheWhenNonLeader *bool`, defaulting to true.

**Review by alculquicondor — COMMENTED** [review]
@kerthcet can you take a first pass?

File: pkg/scheduler/apis/config/types.go (hunk 1 above)
Comment (linxiulei) [reply pkg/scheduler/apis/config/types.go]: Done

File: pkg/scheduler/apis/config/types.go [hunk 2]
```diff
@@ -96,6 +96,11 @@ type KubeSchedulerConfiguration struct {
 	// Extenders are the list of scheduler extenders, each holding the values of how to communicate
 	// with the extender. These extenders are shared by all scheduler profiles.
 	Extenders []Extender
+
+	// MaintainCacheNonLeader enables caching for non-leader candidates. This makes non-leader candidates
+	// start with watching cache. Doing so will have faster failover at cost of higher memory overhead.
+	// Defaults to true.
+	MaintainCacheNonLeader bool
```
Comment (kerthcet) [inline pkg/scheduler/apis/config/types.go:103]: `MaintainCacheInNonLeader` or `MaintainCacheWhenNonLeader` is more readable to me. wdyt?

File: staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go [hunk 3]
```diff
@@ -89,6 +89,11 @@ type KubeSchedulerConfiguration struct {
 	// with the extender. These extenders are shared by all scheduler profiles.
 	// +listType=set
 	Extenders []Extender `json:"extenders,omitempty"`
+
+	// MaintainCacheNonLeader enables caching for non-leader candidates. This makes non-leader candidates
+	// start with watching cache. Doing so will have faster failover at cost of higher memory overhead.
+	// Defaults to true.
+	MaintainCacheNonLeader *bool `json:"maintainCacheNonLeader,omitempty"`
```
Comment (kerthcet) [inline staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go:96]: I think we should only populate this field to v1, but we should still have conversion codes for v1beta2 and v1beta3, cc @alculquicondor for confirmation.

File: pkg/scheduler/apis/config/types.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/apis/config/types.go:103]: `MaintainCacheWhenNonLeader` sounds better.

File: staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go (hunk 3 above)
Comment (alculquicondor) [reply staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go:96]: yeah, only in v1 is enough.

**Comment by cici37** [comment]
/assign @jiahuif 
Thanks!
/triage accepted

File: pkg/scheduler/apis/config/types.go (hunk 2 above)
Comment (linxiulei) [reply pkg/scheduler/apis/config/types.go]: Done

File: staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go (hunk 3 above)
Comment (linxiulei) [reply staging/src/k8s.io/kube-scheduler/config/v1beta3/types.go]: Not sure if I have made it right. PTAL!

**Review by jiahuif — COMMENTED** [review]
I am not sure about the impact on how long the "warm standby" takes over when it wins leader election. From my previous experience the time it takes for the cache to sync may not be consistent. I would really appreciate it if you clarify more.

This PR adds an option that exposes the implementation detail that the api server may or may not maintain a cache when not being the leader. This will push complexity towards the cluster administrator. Maybe just change it? I will leave the decision to the API approver.

File: cmd/kube-scheduler/app/server.go [hunk 4]
```diff
@@ -194,25 +194,33 @@ func Run(ctx context.Context, cc *schedulerserverconfig.CompletedConfig, sched *
...
-	if cc.DynInformerFactory != nil {
-		cc.DynInformerFactory.WaitForCacheSync(ctx.Done())
+		// Wait for all caches to sync before scheduling.
+		cc.InformerFactory.WaitForCacheSync(ctx.Done())
+		// DynInformerFactory can be nil in tests.
+		if cc.DynInformerFactory != nil {
+			cc.DynInformerFactory.WaitForCacheSync(ctx.Done())
+		}
+	}
+	if cc.ComponentConfig.MaintainCacheWhenNonLeader {
```
Comment (alculquicondor) [inline cmd/kube-scheduler/app/server.go:212]:
```suggestion
	if cc.ComponentConfig.MaintainCacheWhenNonLeader || cc.LeaderElection == nil {
```

File: pkg/scheduler/apis/config/types.go [hunk 5]
```diff
@@ -96,6 +96,11 @@ type KubeSchedulerConfiguration struct {
 	// Extenders are the list of scheduler extenders, each holding the values of how to communicate
 	// with the extender. These extenders are shared by all scheduler profiles.
 	Extenders []Extender
+
+	// MaintainCacheWhenNonLeader enables caching for non-leader candidates. This makes non-leader candidates
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/types.go:100]: s/candidates/replicas

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by alculquicondor** [comment]
/label api-review

another possible option for the field:

```yaml
cachePolicy: WhenLeader|Always
```

File: cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:212]: If we add "|| cc.LeaderElection == nil "here, then we probably don't need the changes at line 251-253, right?

File: pkg/scheduler/apis/config/types.go (hunk 5 above)
Comment (linxiulei) [reply pkg/scheduler/apis/config/types.go:100]: I am okay with the suggestion. Just I noticed https://github.com/kubernetes/kubernetes/blob/bceff79876ebd33cdc108300ba715b12bf12a0e4/staging/src/k8s.io/component-base/config/types.go#L46 use `candidates`, should we use `candidates` here consistently?

**Comment by linxiulei** [comment]
> /label api-review
> 
> another possible option for the field:
> 
> ```yaml
> cachePolicy: WhenLeader|Always
> ```

This sounds neat! Waiting for API review and will change accordingly

**Comment by linxiulei** [comment]
> I am not sure about the impact on how long the "warm standby" takes over when it wins leader election. From my previous experience the time it takes for the cache to sync may not be consistent. I would really appreciate it if you clarify more.

Thanks for your comments. I don't think I can add more clarification without concrete data to support it. But a few considerations:

* It takes seconds for a standby scheduler to take leader lock (ie. gets elected to be the new leader) because by default the lease duration is 15s. Warming up period could be only a small delay for whole failover process.
* Time to sync varies a lot depending on the size of cache to be sync. (ie. The total data size of all pods and nodes). For small clusters, it might be instant (less than 1s). For large clusters, it might be seconds or minutes if schedulers are not in the same host or local network as the apiserver.

File: cmd/kube-scheduler/app/server.go [hunk 6]
```diff
@@ -194,25 +194,33 @@ func Run(ctx context.Context, cc *schedulerserverconfig.CompletedConfig, sched *
...
+		startInformersAndWaitForSync()
 	}
 
 	// If leader election is enabled, runCommand via LeaderElector until done and exit.
 	if cc.LeaderElection != nil {
 		cc.LeaderElection.Callbacks = leaderelection.LeaderCallbacks{
 			OnStartedLeading: func(ctx context.Context) {
 				close(waitingForLeader)
+				if !cc.ComponentConfig.MaintainCacheWhenNonLeader {
+					startInformersAndWaitForSync()
```
Comment (liggitt) [inline cmd/kube-scheduler/app/server.go:222]: `OnStartedLeading` is called asynchronously and lease renewal continues in the background. The context passed to OnStartedLeading closes when leadership is lost. Should we plumb *that* context to `startInformersAndWaitForSync(ctx)`?

Comment (liggitt) [inline cmd/kube-scheduler/app/server.go:222]: what guards against a scheduler obtaining and keeping the leader lease, failing to start/sync informers here, and hanging indefinitely while holding the leader lease?

File: cmd/kube-scheduler/app/server.go (hunk 4 above)
Comment (alculquicondor) [reply cmd/kube-scheduler/app/server.go:212]: correct

File: pkg/scheduler/apis/config/types.go (hunk 5 above)
Comment (alculquicondor) [reply pkg/scheduler/apis/config/types.go:100]: ah ok, I didn't know that was the word already used. Let's keep the same.

File: cmd/kube-scheduler/app/server.go (hunk 6 above)
Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:222]: AIUI, this is not a problem brought in by this change, right?

Comment (alculquicondor) [reply cmd/kube-scheduler/app/server.go:222]: It is, because previously a scheduler only requests a lease after the informers already synced.

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:222]: Right, I checked kube-controller-manager code and it should have same issue since it starts informers after having got the lease. I can't think of a nice solution to it but how likely are informers to fail to start/sync? would that indicate a bigger problem that scheduler can't handle anyway?

Comment (kerthcet) [reply cmd/kube-scheduler/app/server.go:222]: If we lose the least, we should shutdown the informers as not maintaining the cache, so +1.

Comment (kerthcet) [reply cmd/kube-scheduler/app/server.go:222]: In theory, this will also happen with scheduler, right?

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go]: Done.

Comment (kerthcet) [reply cmd/kube-scheduler/app/server.go]: Do you think we should have a mechanism to make leader election aware of the failure in `OnStartedLeading` and then release the lease.

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go]: Can you please elaborate on the failures we have here?

I had a quick read over `startInformersAndWaitForSync` and `sched.run()`. Both of them don't return any explicit errors but just return to complete the function. I can think of one possible failure in the informers where they stuck to pull resource objects, but I don't see a mechanism in informer APIs to capture that.

Alternatively, we can have a new `context` with timeout passed to informers. However, it brings up a new question as to how long the timeout should be.

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go [hunk 7]
```diff
@@ -89,6 +89,11 @@ type KubeSchedulerConfiguration struct {
 	// with the extender. These extenders are shared by all scheduler profiles.
 	// +listType=set
 	Extenders []Extender `json:"extenders,omitempty"`
+
+	// MaintainCacheWhenNonLeader enables caching for non-leader candidates. This makes non-leader candidates
+	// start with watching cache. Doing so will have faster failover at cost of higher memory overhead.
+	// Defaults to true.
+	MaintainCacheWhenNonLeader *bool `json:"maintainCacheWhenNonLeader,omitempty"`
```
Comment (liggitt) [inline staging/src/k8s.io/kube-scheduler/config/v1/types.go:96]: it would be nice if we could name this such that a default of false matches the current behavior, and avoid the need for fixup in non-v1 conversion files

possible suggestion:

`DelayCacheUntilActive bool`

that name also makes more sense in a scheduler that doesn't use leader election (it becomes active immediately)

File: cmd/kube-scheduler/app/server.go [hunk 8]
```diff
@@ -194,25 +194,33 @@ func Run(ctx context.Context, cc *schedulerserverconfig.CompletedConfig, sched *
...
+		startInformersAndWaitForSync(ctx)
 	}
 
 	// If leader election is enabled, runCommand via LeaderElector until done and exit.
 	if cc.LeaderElection != nil {
 		cc.LeaderElection.Callbacks = leaderelection.LeaderCallbacks{
 			OnStartedLeading: func(ctx context.Context) {
 				close(waitingForLeader)
+				if !cc.ComponentConfig.MaintainCacheWhenNonLeader {
+					startInformersAndWaitForSync(ctx)
```
Comment (liggitt) [inline cmd/kube-scheduler/app/server.go:222]: is there any metric or observable signal (/healthz, etc) that would tell us if we got stuck here, holding leader lease and failing to sync / run?

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:222]: Would a log such as "Waiting informer cache to sync..." be sufficient?

Comment (jiahuif) [reply cmd/kube-scheduler/app/server.go:222]: No. That would require some externally configured log-based metrics to properly mark the pod as unhealthy.

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go (hunk 7 above)
Comment (linxiulei) [reply staging/src/k8s.io/kube-scheduler/config/v1/types.go]: Changed as suggested, thanks!

File: cmd/kube-scheduler/app/server.go (hunk 8 above)
Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:223]: I don't know the best way to address this but I add two logs around `startInformersAndWaitForSync(ctx)`. At least, this makes it obvious if the scheduler is stuck here.

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go [hunk 9]
```diff
@@ -89,6 +89,12 @@ type KubeSchedulerConfiguration struct {
 	// with the extender. These extenders are shared by all scheduler profiles.
 	// +listType=set
 	Extenders []Extender `json:"extenders,omitempty"`
+
+	// DelayCacheUntilActive specifies when to start caching. If this value is true, it makes non-leader
+	// candidates not start with watching cache. Doing so will have slower failover with the benefit of
+	// lower memory overhead.
+	// Defaults to false.
+	DelayCacheUntilActive *bool `json:"delayCacheUntilActive,omitempty"`
```
Comment (liggitt) [inline staging/src/k8s.io/kube-scheduler/config/v1/types.go:97]: since the default is now false, can make this a non-pointer

File: cmd/kube-scheduler/app/server.go (hunk 8 above)
Comment (liggitt) [reply cmd/kube-scheduler/app/server.go:223]: above, we're setting up `/healthz` endpoints for scheduler in newHealthzAndMetricsHandler ... for kube-apiserver, we also serve /readyz (added in https://github.com/kubernetes/kubernetes/pull/78458) that returns false until informers sync (added in https://github.com/kubernetes/kubernetes/pull/93670)... should we do something similar here?

cc @alculquicondor for scheduler input

cc @logicalhan and @wojtek-t for input on readyz existence and behavior

Comment (liggitt) [reply cmd/kube-scheduler/app/server.go:223]: I'm not sure if the "healthy until leader, then unhealthy until informers sync" matches the readyz or healthz pattern better (or if we need a concept of how long we'd tolerate a scheduler that was leader with unsynced informers, similar to the `--livez-grace-period` option kube-apiserver has)

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go (hunk 9 above)
Comment (liggitt) [reply staging/src/k8s.io/kube-scheduler/config/v1/types.go:97]: API bit lgtm otherwise

File: cmd/kube-scheduler/app/server.go (hunk 8 above)
Comment (logicalhan) [reply cmd/kube-scheduler/app/server.go:223]: > above, we're setting up `/healthz` endpoints for scheduler in newHealthzAndMetricsHandler ... for kube-apiserver, we also serve /readyz (added in #78458) that returns false until informers sync (added in #93670)... should we do something similar here?

Are you suggesting that scheduler add separate `/livez` and `/readyz` endpoints, with the `startInformersAndWaitForSync` being a readiness check? If so, then yes I think agree with that. Throwing `startInformersAndWaitForSync` into the liveness check could be dangerous since it could cause crashlooping behaviors if syncs for resources with large numbers of resources takes too long.

Comment (wojtek-t) [reply cmd/kube-scheduler/app/server.go:223]: Given we're touching this logic now, I would definitely like to introduce better health-related metrics. I think that pretty much only kube-apiserver is exposing something reasonable and we should extend our coverage here.

I agree that splitting into livez/ and readyz/ is what we need here:
- livez/ inherits the existing behavior of healthz/ [it just becomes true once the component starts]
- readyz/ is failing when the component isn't initialized (i.e. it's only true after informers are already synced)

Now what we get is:
- non-leader with delayed caching will always be non-ready
- non-leader without delayed caching will be ready as soon as its cache initializes
- leader currently initializing can be distinguished from non-leader using the leader-election metrics

I think that makes it very clear and I don't personally see a problem with readyz/ being false for extended period of time for non-leaders. @liggitt - do you have any concerns here?

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go (hunk 9 above)
Comment (linxiulei) [reply staging/src/k8s.io/kube-scheduler/config/v1/types.go]: Done

File: cmd/kube-scheduler/app/server.go (hunk 8 above)
Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:223]: Splitting /healthz is a reasonable extension of this PR. I created a separate [issue](https://github.com/kubernetes/kubernetes/issues/118011) to track that work where we can continue the discussion and implementation.

@liggitt would you mind approving this PR if no further changes needed except for this?

File: staging/src/k8s.io/kube-scheduler/config/v1/types.go [hunk 10]
```diff
@@ -89,6 +89,12 @@ type KubeSchedulerConfiguration struct {
 	// with the extender. These extenders are shared by all scheduler profiles.
 	// +listType=set
 	Extenders []Extender `json:"extenders,omitempty"`
+
+	// DelayCacheUntilActive specifies when to start caching. If this value is true, it makes non-leader
+	// candidates not start with watching cache. Doing so will have slower failover with the benefit of
```
Comment (liggitt) [inline staging/src/k8s.io/kube-scheduler/config/v1/types.go:94]:
```suggestion
	// DelayCacheUntilActive specifies when to start caching. If this is true and leader election is enabled,
	// the scheduler will wait to fill informer caches until it is the leader. Doing so will have slower failover with the
	// benefit of lower memory overhead while waiting to become leader.
```

**Review by liggitt — COMMENTED** [review]
one suggestion on the config field doc to avoid double negatives, lgtm otherwise

**Comment by everpeace** [comment]
@alculquicondor 

This PR introduces new API in KubeSchedulerConfiguration
that can provide tradeoff between memory efficiency and scheduling speed when their leadership updated in kube-scheduler. I think this PR should have a release note item.

**Comment by alculquicondor** [comment]
oh, that is correct. It's adding an API field, so it's user visible.

@linxiulei please add a release note.

**Comment by linxiulei** [comment]
Done. Thanks @everpeace & @alculquicondor

**Comment by alculquicondor** [comment]
nit:

/release-note-edit
```release-note
Added new config option `delayCacheUntilActive` to `KubeSchedulerConfiguration` that can provide a tradeoff between memory efficiency and scheduling speed when their leadership is updated in `kube-scheduler`
```

we use the yaml/json name in documentation
