### PR TITLE
Fix NPE for CSI mounter

### LINKED ISSUE #102651: kubelet panics on creation of inline ephemeral volume with FSType specified
#### What happened:
kubelet panics on creation of inline ephemeral volume with FSType specified.

#### What you expected to happen:
creation of inline ephemeral volume succeeds with FSType specified.

#### How to reproduce it (as minimally and precisely as possible):
no existing isolated test case. Happens during e2e testing of pmem-csi.

#### Environment:
- Kubernetes version (use `kubectl version`): The pmem-csi CI system where this was detected, runs same tests on k8s systems with 1.19 and 1.20. The problem occurs in testing on 1.20 system, problem does not occur on 1.19 system.

- Cloud provider or hardware configuration: pmem-csi tests run on cluster formed by few qemu-based systems running Fedora-33 and emulated pmem storage.

The issue has been seen in e2e testing in [pmem-csi](https://github.com/intel/pmem-csi), where a new test was
recently introduced that creates a pod with an inline ephemeral volume.

If the related VolumeSource has filesystem type set to empty "", or FSType is omitted in spec,
then the pod creation works OK. In that case, pmem-csi chooses it's default fstype which is `ext4`.

Example of working definition of VolumeSource:
```
   fstype := ""
   vsource := v1.VolumeSource{
           CSI: &v1.CSIVolumeSource{
                   Driver: "pmem-csi.intel.com",
                   FSType: &fstype,
                   VolumeAttributes: map[string]string{
                           "size": "110Mi",
                   },
           },
   }
```

If the filesystem type in the VolumeSource is set to `ext4` or `xfs`
then kubelet fails to create the volume and pod. A panic trace is written in the node kubelet log and the creation will be retried few times,

```
pmem-csi-govm-worker2 kubelet[905]: E0526 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/a5c44727-b679-412d-a3ef-3f6bbc7af122-vol1 podName:a5c44727-b679-412d-a3ef-3f6bbc7af122 nodeName:}" failed. No retries permitted until 2021-05-26 16:53:09.613416932 +0000 UTC m=+14773.383054841 (durationBeforeRetry 500ms). Error: "recovered from panic \"runtime error: invalid memory address or nil pointer dereference\". (err=<nil>) Call stack:
goroutine 95902 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0014c0d10)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xba
panic(0x40021e0, 0x6fd2280)
/usr/local/go/src/runtime/panic.go:975 +0x47a
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).supportsFSGroup(0xc0016b0ff0, 0xc0009e6724, 0x3, 0xc0013960f0, 0xc00144b260, 0x17, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:429 +0xb5
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUpAt(0xc0016b0ff0, 0xc001077c80, 0x5f, 0xc001396470, 0xc0013960f0, 0x0, 0x0, 0x0, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:269 +0x105f
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUp(0xc0016b0ff0, 0xc001396470, 0xc0013960f0, 0x0, 0x0, 0x0, 0xc0009e6720)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:106 +0x65
k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateMountVolumeFunc.func1(0xc000bb7db0, 0xc0014c0d10, 0x0, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:643 +0x504
k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc001dcdb00, 0xc000bb7f18, 0x4b8530, 0xc000bb7f58, 0x409548)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/types/types.go:54 +0xde
k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1(0xc000e1e5c0, 0xc00082fb00, 0x3b, 0xc001a24780, 0x24, 0x0, 0x0, 0xc001dcdb00, 0x0, 0x0, ...)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:183 +0xfa
created by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:178 +0x479"
```

On pmem-csi side: the 1st NodePublishVolume is received, namespace
and volume are created, formatted with mkfs, mounted and NodePublishVolume returns OK.
Same request is received few times with increasing time interval.

e2e testing code which tries to create the pod, will fail with:
```
FAIL: running pod
Unexpected error:
    <*errors.errorString | 0xc0002f9060>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug
/sig node
/sig storage

#### Which issue(s) this PR fixes:

Fixes #102651

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/volume/csi/csi_mounter.go [hunk 1]
```diff
@@ -392,12 +392,11 @@ func (c *csiMountMgr) supportsFSGroup(fsType string, fsGroup *int64, driverPolic
 		return false
 	}
 
-	accessModes := c.spec.PersistentVolume.Spec.AccessModes
-	if c.spec.PersistentVolume.Spec.AccessModes == nil {
+	if c.spec.PersistentVolume == nil || c.spec.PersistentVolume.Spec.AccessModes == nil {
```
Comment (endocrimes) [inline pkg/volume/csi/csi_mounter.go:395]: We might want to add a new log line for this for skipping due to it missing a PersistentVolume? - Mostly as an easier to skim in the future thing.

File: pkg/volume/csi/csi_mounter.go [hunk 2]
```diff
@@ -392,12 +392,11 @@ func (c *csiMountMgr) supportsFSGroup(fsType string, fsGroup *int64, driverPolic
...
 		klog.V(4).Info(log("mounter.SetupAt WARNING: skipping fsGroup, access modes not provided"))
 		return false
 	}
-	if !hasReadWriteOnce(accessModes) {
+	if !hasReadWriteOnce(c.spec.PersistentVolume.Spec.AccessModes) {
 		klog.V(4).Info(log("mounter.SetupAt WARNING: skipping fsGroup, only support ReadWriteOnce access mode"))
```
Comment (gnufied) [inline pkg/volume/csi/csi_mounter.go:400]: Can we add a unit test for this?

File: pkg/volume/csi/csi_mounter.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go:395]: Another way of working around this is to specify a `FSGroupPolicy` in `CSIDriver` object created for CSI driver (in this case intel pmem driver). That might be better solution -  because at the end of day, we do not want to look at PV access modes to determine fsgroup support policy, otherwise only root users can read/write this volume. 

So I think warning should be updated to reflect something like:
> mounter.SetupAt Warning: skipping fsgroup permission change, no access mode available. The volume may only be accessible to root users.

**Review by ehashman — COMMENTED** [review]
/priority important-longterm

LGTM, agree with adding a unit test to catch this.

File: pkg/volume/csi/csi_mounter_test.go [hunk 3]
```diff
@@ -1054,3 +1055,128 @@ func TestPodServiceAccountTokenAttrs(t *testing.T) {
...
+						AccessModes: []api.PersistentVolumeAccessMode{api.ReadWriteOnce},
+					},
+				}, true),
+			},
+			want: true,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
```
Comment (endocrimes) [inline pkg/volume/csi/csi_mounter_test.go:1160]: none of the tests were given names so this will run all subtests as `""` which isn't ideal - could you add them?

File: pkg/volume/csi/csi_mounter.go [hunk 4]
```diff
@@ -392,12 +392,15 @@ func (c *csiMountMgr) supportsFSGroup(fsType string, fsGroup *int64, driverPolic
 		return false
 	}
 
-	accessModes := c.spec.PersistentVolume.Spec.AccessModes
+	if c.spec.PersistentVolume == nil {
+		klog.V(4).Info(log("mounter.SetupAt Warning: skipping fsGroup permission change, no access mode available. The volume may only be accessible to root users."))
+		return false
```
Comment (pohly) [inline pkg/volume/csi/csi_mounter.go:397]: Is there really no way to support fsGroup for CSI ephemeral inline volumes?

**Review by pohly — CHANGES_REQUESTED** [review]
The change note in the PR description should describe the bug.

File: pkg/volume/csi/csi_mounter.go (hunk 4 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go:397]: there is a way. I left a comment above https://github.com/kubernetes/kubernetes/pull/102653#discussion_r646889247 explaining that.

File: pkg/volume/csi/csi_mounter.go (hunk 1 above)
Comment (pohly) [reply pkg/volume/csi/csi_mounter.go]: That warning doesn't mention CSIDriver.FSGroupPolicy. Do I understand correctly that if that is set, then this code here will not be reached?

It might be worthwhile to add that to the message, because without it users and fellow developers will not know what to do when they see the warning.

Comment (pohly) [reply pkg/volume/csi/csi_mounter.go]: Can CSIDriver.FSGroupPolicy really work for CSI ephemeral inline volumes? I'm lazy (sorry!) and did not look up the corresponding KEP, I'm just suspicious that NodePublishVolume (the only gRCP call for those kind of volumes) won't have the necessary information for a CSI driver to do the ownership changes.

Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: The ownership/permission change is performed by kubelet and should work for CSI ephemeral inline volumes - as long as CSI driver declares support for it via `CSIDriver.Spec.FSGroupPolicy` field.  It is performed *after* `NodePublish` and hence should behave same for regular CSI volumes and inline ephemeral volumes.

Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: > That warning doesn't mention CSIDriver.FSGroupPolicy. Do I understand correctly that if that is set, then this code here will not be reached?

Yes I think so. I have not personally tested it but code is pretty straightforward.

> It might be worthwhile to add that to the message, because without it users and fellow developers will not know what to do when they see the warning.

That is a good point and I was thinking about it but may be we should do a general sweep of such messages and figure out, how best to inform our users. My point is - a normal user probably can't even see kubelet logs and hence it is not super useful. I also did not wanted to block this PR while we decide how best to improve the messaging.

**Comment by gnufied** [comment]
lgtm to me. I will add approve and wait for @pohly 's feedback to be addressed.

/approve
/hold

File: pkg/volume/csi/csi_mounter.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: Filed - https://github.com/kubernetes/kubernetes/issues/102738

**Comment by pohly** [comment]
I understand this a bit better now, but I still have one question: without `CSIDriver.Spec.FSGroupPolicy`, ownership change works for CSI ephemeral inline volumes if *no* FSType is specified. We know because the test in PMEM-CSI relies on it. But if FSType is specified, it either panics (without this PR) or skips ownership changes (with this PR) - right?

I was hoping that https://github.com/kubernetes/kubernetes/issues/102651 would be resolved as "ownership change works", not as "avoid the panic and leave ownership unchanged".

Is FSGroupPolicy going beta in 1.22?

**Comment by gnufied** [comment]
> I understand this a bit better now, but I still have one question: without CSIDriver.Spec.FSGroupPolicy, ownership change works for CSI ephemeral inline volumes if no FSType is specified. We know because the test in PMEM-CSI relies on it. But if FSType is specified, it either panics (without this PR) or skips ownership changes (with this PR) - right?

The entire mechanism of looking to access modes and fstype is a hack and we want to move away from it. It is a legacy mechanism. Going forward we expect cluster admins/CSI drivers to configure `FSGroupPolicy` field in `CSIDriver`. The feature is already beta in 1.20  (and should have probably gone GA in 1.22 but it might be too late for that).

**Comment by pohly** [comment]
> The feature is already beta in 1.20

I had looked at the documentation for 1.21.1 and it still said "alpha field":
https://github.com/kubernetes/kubernetes/blob/v1.21.1/staging/src/k8s.io/api/storage/v1/types.go#L355-L356

Looks like this was fixed on master and not backported.

In that case I waive all of my concerns. This looks like the right solution also for 1.20 and 1.21, and 1.19 didn't have the problem.
