### PR TITLE
Fixed pointers bug in PATCH verb in the API

### LINKED ISSUE #8489: api returns error 415 on PATCH
PATCH http://IP:8080/api/v1beta3/namespaces/dev-43b46323-ea6f-49cb-b5bb-2f9489cc61a1/replicationcontrollers/redis-master
{"spec":{"replicas":0}}

answer:
{
 "kind": "Status",
 "apiVersion": "v1beta3",
 "metadata": {},
 "status": "Failure",
 "message": "the server responded with the status code 415 but did not return more information",
 "details": {},
 "code": 415
}

Before v0.15.0 it had worked well.

### PR DESCRIPTION
**Pull request by manansaraf**
I fixed the bug which gave an error if the data structure which was trying to be updated was a Pointer in the PATCH verb command. Added tests to check for the pointers as well now.

Fixes #8489

### CODE REVIEW

**Comment by mikedanese** [comment]
@ghodss

File: pkg/util/strategicpatch/patch.go [hunk 1]
```diff
@@ -100,6 +100,11 @@ func mergeMap(original, patch map[string]interface{}, t reflect.Type) (map[strin
 			original[k] = patchV
 			continue
 		}
+		// Find whether the data type is a pointer or not and changing the type accordingly.
```
Comment (ghodss) [inline pkg/util/strategicpatch/patch.go]: Minor phrasing nit, change to: // If the data type is a pointer, resolve the element.

File: pkg/util/strategicpatch/patch_test.go [hunk 2]
```diff
@@ -232,6 +233,41 @@ strategicMergePatchCases:
         - $patch: replace
     result:
       mergingList: []
+  - description: add new field inside pointers
+    original:
+      mergeItemPtr :
```
Comment (ghodss) [inline pkg/util/strategicpatch/patch_test.go]: No space after colons.

**Comment by ghodss** [comment]
After minor comments addressed, this LGTM.

**Comment by mikedanese** [comment]
LGTM. Thanks!

**Comment by saad-ali** [comment]
@bgrant0607 Can you verify this is ok for 1.0

**Comment by bgrant0607** [comment]
Yes, we should take this.

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by satnam6502** [comment]
@k8s-bot ok to test
