### PR TITLE
Promote Read, Patch & Replace ReplicaSet Status +3 endpoints

### LINKED ISSUE #100863: Write Read, Patch & Replace Replictest Status +3 endpoints
# Progress <code>[4/6]</code>

-   [X] APISnoop org-flow : [Read-Patch-Status-for-Replicaset.org](https://github.com/apisnoop/ticket-writing/blob/create-replicaset-status-lifecycle-test/Appsv1ReplicaSetStatusLifecycleTest.org)
-   [X] test approval issue : [kubernetes/kubernetes#100863](https://github.com/kubernetes/kubernetes/issues/100863)
-   [X] test pr : kuberenetes/kubernetes #101260
-   [X] two weeks soak start date : [testgrid-link](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&&width=5&include-filter-by-regex=should%20validate%20Replicaset%20Status%20endpoints&graph-metrics=test-duration-minutes) 25 May
-   [ ] two weeks soak end date : 8 June
-   [ ] test promotion pr : kubernetes/kubernetes #102349

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still some remaining ReplicaSet endpoints that are untested.

```sql-mode
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%ReplicaSetStatus'
      order by kind, endpoint desc
      limit 10;
```

```example
                  endpoint                 |                              path                              |    kind
  -----------------------------------------+----------------------------------------------------------------+------------
   replaceAppsV1NamespacedReplicaSetStatus | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
   readAppsV1NamespacedReplicaSetStatus    | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
   patchAppsV1NamespacedReplicaSetStatus   | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
  (3 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/kubernetes-api/)
-   [Kubernetes API / Workload Resources / ReplicaSet](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/replica-set-v1/)
-   [client-go - ReplicaSet](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/apps/v1/replicaset.go)

# The mock test

## Test outline

1.  Create a watch to track replica set events

2.  Create a replica set with a static label. Confirm that the pods are running.

3.  Get the replica set status. Parse the response and confirm that the replica set status conditions can be listed.

4.  Update the replica set status. Confirm via the watch that the status has been updated.

5.  Patch the replica set status. Confirm via the watch that the status has been patched.

## Test the functionality in Go

Using an existing [status lifecycle test](https://github.com/ii/kubernetes/blob/ca3aa6f5af1b545b116b52c717b866e43c79079b/test/e2e/apps/daemon_set.go#L812-L947) as a template for a new [ginkgo test](https://github.com/ii/kubernetes/blob/replicaset-status-test/test/e2e/apps/replica_set.go#L513-L642) for daemon set lifecycle test. Due to a test flake with patching the replica set status conditions the final &ldquo;watch/validation&rdquo; check is still be written.

### Patching the replica set causes test failure

    [It] should validate Replicaset Status endpoints
      /home/ii/go/src/k8s.io/kubernetes/test/e2e/apps/replica_set.go:155
    Apr  6 15:16:30.093: INFO: labels: name=sample-pod,pod=httpd
    STEP: Create a ReplicaSet
    STEP: Verify that the required pods have come up.
    Apr  6 15:16:30.099: INFO: Pod name sample-pod: Found 0 pods out of 1
    Apr  6 15:16:35.108: INFO: Pod name sample-pod: Found 1 pods out of 1
    STEP: ensuring each pod is running
    STEP: Getting /status
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs has Conditions: []
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.Replicas: 1
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.ReadyReplicas: 1
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.AvailableReplicas: 1
    STEP: updating the ReplicaSet Status
    Apr  6 15:16:35.147: INFO: updatedStatus.Conditions: []v1.ReplicaSetCondition{v1.ReplicaSetCondition{Type:"StatusUpdate", Status:"True", LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Reason:"E2E", Message:"Set from e2e test"}}
    STEP: watching for the daemon set status to be updated
    Apr  6 15:16:35.149: INFO: Observed event: ADDED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Found replica set test-rs in namespace replicaset-2037 with labels: map[name:sample-pod pod:httpd] annotations: map[] & Conditions: [{StatusUpdate True 0001-01-01 00:00:00 +0000 UTC E2E Set from e2e test}]
    Apr  6 15:16:35.149: INFO: Replica set test-rs has an updated status
    STEP: get ReplicaSet state
    Apr  6 15:16:35.152: INFO: rs1.Conditions: []v1.ReplicaSetCondition{v1.ReplicaSetCondition{Type:"StatusUpdate", Status:"True", LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Reason:"E2E", Message:"Set from e2e test"}}
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.FullyLabeledReplicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.Replicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.ReadyReplicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.AvailableReplicas: 1
    STEP: patching the ReplicaSet Status
    Apr  6 15:16:35.158: FAIL: Failed to patch replica set status. ReplicaSet.apps "test-rs" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]

### Full Stack Trace

    Unexpected error:
        <*errors.StatusError | 0xc00024d4a0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "ReplicaSet.apps \"test-rs\" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]",
                Reason: "Invalid",
                Details: {
                    Name: "test-rs",
                    Group: "apps",
                    Kind: "ReplicaSet",
                    UID: "",
                    Causes: [
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.fullyLabeledReplicas",
                        },
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.readyReplicas",
                        },
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.availableReplicas",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 422,
            },
        }
        ReplicaSet.apps "test-rs" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]
    occurred

The error looks to be part of the [validation code for replica sets](https://github.com/kubernetes/kubernetes/blob/b0abe89ae259d5e891887414cb0e5f81c969c697/pkg/apis/apps/validation/validation.go#L629-L651). Looking for suggestions on whats likely to be happening and how to best resolve the flake would be appreciated.

# Verifying increase in coverage with APISnoop

## Listing endpoints hit by the new e2e test

This query shows the endpoints hit within a short period of running the e2e test

```sql-mode
select distinct  endpoint, right(useragent,65) AS useragent
from testing.audit_event
where endpoint ilike '%ReplicaSetStatus%'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%'
order by endpoint
limit 10;
```

```example
                endpoint                 |                             useragent
-----------------------------------------+-------------------------------------------------------------------
 patchAppsV1NamespacedReplicaSetStatus   | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
 readAppsV1NamespacedReplicaSetStatus    | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
 replaceAppsV1NamespacedReplicaSetStatus | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
(3 rows)

```

# Final notes

If a test with these calls gets merged, **test coverage will go up by 2 points**

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture
/area conformance

### PR DESCRIPTION
**Pull request by riaankleinhans**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
This PR adds a test to test the following untested endpoints:
- replaceAppsV1NamespacedReplicaSetStatus
- readAppsV1NamespacedReplicaSetStatus
- patchAppsV1NamespacedReplicaSetStatus

**Which issue(s) this PR fixes:**
Fixes #100863
**Testgrid Link:**
[Test](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&&width=5&include-filter-by-regex=should%20validate%20Replicaset%20Status%20endpoints&graph-metrics=test-duration-minutes)

**Special notes for your reviewer:**
Adds +3 endpoint test coverage (good for conformance)

**Does this PR introduce a user-facing change?:**
```
NONE

```

**Release note:**
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```
NONE

```

/sig testing
/sig architecture
/area conformance

### CODE REVIEW

**Comment by heyste** [comment]
/test pull-kubernetes-unit

unrelated flake `k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler: Test_Run_Positive_VolumeAttachMountUnmountDetach`

```
I0526 17:47:48.455395   67142 reconciler.go:244] "operationExecutor.AttachVolume started for volume \"volume-name\" (UniqueName: \"fake-plugin/fake-device1\") pod \"pod1\" (UID: \"pod1uid\") "
I0526 17:47:48.455500   67142 reconciler.go:157] "Reconciler: start to sync state"
E0526 17:47:48.455614   67142 reconciler.go:389] "Cannot get volumes from disk" err="open fake-dir: no such file or directory"
...
+0000 UTC m=+1.077112598 (durationBeforeRetry 500ms). Error: "DetachVolume.Detach failed for volume \"volume-name\" (UniqueName: \"fake-plugin/fake-device1\") on node \"mynodename\" : trying to detach volume \"fake-device1\" that is not attached to the node \"mynodename\""
    reconciler_test.go:346: 
        	Error Trace:	reconciler_test.go:346
        	Error:      	Received unexpected error:
        	            	No Detachers have expected DetachCallCount. Expected: <1>.
        	Test:       	Test_Run_Positive_VolumeAttachMountUnmountDetach
--- FAIL: Test_Run_Positive_VolumeAttachMountUnmountDetach (0.20s)
```

**Comment by heyste** [comment]
/test pull-kubernetes-conformance-image-test

possible flake?

```
W0526 18:45:14.273]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0526 18:45:14.273]     subprocess.check_call(cmd)
W0526 18:45:14.273]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0526 18:45:14.273]     raise CalledProcessError(retcode, cmd)
W0526 18:45:14.274] subprocess.CalledProcessError: Command '('bash', '-c', 'cd ./../../k8s.io/kubernetes && source ./../test-infra/experiment/kind-conformance-image-e2e.sh')' returned non-zero exit status 1
E0526 18:45:14.278] Command failed 
...
W0526 18:45:16.760] Remote dir gs://kubernetes-jenkins/pr-logs/pull/102349/pull-kubernetes-conformance-image-test/1397605821579268096/artifacts not exist yet
I0526 18:45:16.760] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml /workspace/_artifacts gs://kubernetes-jenkins/pr-logs/pull/102349/pull-kubernetes-conformance-image-test/1397605821579268096/artifacts
```

**Comment by heyste** [comment]
/test pull-kubernetes-e2e-gce-ubuntu-containerd

unrelated flake `Kubernetes e2e suite: [sig-instrumentation] MetricsGrabber should grab all metrics from a Scheduler`

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:81
May 26 18:15:54.103: Unexpected error:
    <*errors.errorString | 0xc0038385b0>: {
        s: "error waiting for scheduler pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods metrics-proxy:10259)",
    }
    error waiting for scheduler pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods metrics-proxy:10259)
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:88
```

**Comment by Riaankl** [comment]
/assign @johnbelamaric @smarterclayton @spiffxp
The e2e test had more than 2 week flake-free on the [testgrid](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&&width=5&include-filter-by-regex=should%20validate%20Replicaset%20Status%20endpoints&graph-metrics=test-duration-minutes)
Can we please get your eyes for /LGTM & /Approve
Thank you

File: test/e2e/apps/replica_set.go [hunk 1]
```diff
@@ -158,7 +158,14 @@ var _ = SIGDescribe("ReplicaSet", func() {
 
 	})
 
-	ginkgo.It("should validate Replicaset Status endpoints", func() {
+	/*	Release: v1.22
+		Testname: ReplicaSet, validate status endpoints
+		Description: When a ReplicaSet is created it MUST succeed.
+		When retrieving /status the action MUST be validated.
```
Comment (johnbelamaric) [inline test/e2e/apps/replica_set.go:164]: valid or validated?

Comment (johnbelamaric) [reply test/e2e/apps/replica_set.go:164]: I don't understand this description

Comment (heyste) [reply test/e2e/apps/replica_set.go]: Fixed

**Comment by heyste** [comment]
/test pull-kubernetes-conformance-image-test
unrelated flake `pull-kubernetes-conformance-image-test` ?
```
I0616 01:55:02.971] Call:  gsutil ls gs://kubernetes-jenkins/pr-logs/pull/102349/pull-kubernetes-conformance-image-test/1404965569865715712/artifacts
W0616 01:55:04.216] CommandException: One or more URLs matched no objects.
E0616 01:55:04.436] Command failed
I0616 01:55:04.437] process 179363 exited with code 1 after 0.0m
W0616 01:55:04.437] Remote dir gs://kubernetes-jenkins/pr-logs/pull/102349/pull-kubernetes-conformance-image-test/1404965569865715712/artifacts not exist yet 
```

**Comment by heyste** [comment]
/test pull-kubernetes-conformance-image-test
unrelated flake
```
I0616 03:06:02.044] process 195256 exited with code 1 after 0.0m
W0616 03:06:02.045] Remote dir gs://kubernetes-jenkins/pr-logs/pull/102349/pull-kubernetes-conformance-image-test/1404982450253205504/artifacts not exist yet
```

**Comment by Riaankl** [comment]
/test pull-kubernetes-e2e-kind

Unrelated flake
```
• Failure [53.150 seconds]
[sig-node] Probing container
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/framework.go:23
  should be ready immediately after startupProbe succeeds [It]
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:406
  ```
