### PR TITLE
Fix service account node audience restriction for in-tree pv to csi migration

### LINKED ISSUE #129935: CSI migration with in-tree azure-file provider fails to mount PVC to Pod
### What happened?

When mounting PVC to the Pod the volume will not mount and it will hang on
```
MountVolume.SetUp failed for volume "pvc-d9734ad3-26f5-4fb9-8918-7643d2bf8c75" : kubernetes.io/csi: mounter.SetUpAt failed to get service accoount token attributes: failed to fetch token: serviceaccounts "default" is forbidden: audience "api://AzureADTokenExchange" not found in pod spec volume
```

### What did you expect to happen?

Volume mounted successfully with Pod running.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Azure cluster with Kubernetes 1.32
2. Create PV claim
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-pv-claim 
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS 
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
3. Create Pod and mount PVC

### Anything else we need to know?

The error comes from https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L654
which was introduced in https://github.com/kubernetes/kubernetes/pull/128077

Admission plugin will work for CSI
https://github.com/openshift/kubernetes/blob/master/plugin/pkg/admission/noderestriction/admission.go#L689-L690

But when using CSI migration with in-tree azure-file provider the PVC fails to mount.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L141

CSIdriver contents
```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  annotations:
    csi.openshift.io/managed: "true"
    operator.openshift.io/spec-hash: 5c303d28061bd64a18ff9b79bd6b231293b3c1295db37e91d59160efe4611365
  creationTimestamp: "2025-01-31T13:10:35Z"
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: privileged
  name: file.csi.azure.com
  resourceVersion: "9671"
  uid: 15b2ad34-60dc-4765-97cb-b91613dfa6d7
spec:
  attachRequired: false
  fsGroupPolicy: None
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  tokenRequests:
  - audience: api://AzureADTokenExchange
  volumeLifecycleModes:
  - Persistent
  - Ephemeral 
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.4.2
Server Version: v1.32.1
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
ServiceAccountNodeAudienceRestriction admission plugin - https://github.com/kubernetes/kubernetes/blob/295ed0a607922af27841121b8c7e95961fcb4d79/plugin/pkg/admission/noderestriction/admission.go#L637-L657
</details>

### PR DESCRIPTION
**Pull request by aramase**
Translate in-tree inline volume or in-tree persistent volumes to CSI using the CSI translator while verifying whether the kubelet is allowed to request a token for an audience when enforcing service account node audience restrictions.

fixes https://github.com/kubernetes/kubernetes/issues/129935

```release-note
Fixes a regression with the ServiceAccountNodeAudienceRestriction feature where `azureFile` volumes encounter "failed to get service accoount token attributes" errors
```

```docs
[KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/4412-projected-service-account-tokens-for-kubelet-image-credential-providers/README.md
```

/kind bug
/sig auth
/triage accepted
/milestone v1.33
/priority important-soon

### CODE REVIEW

**Comment by aramase** [comment]
/assign @dobsonj @jsafrane 

Could you review this PR? previous review: https://github.com/kubernetes/kubernetes/pull/128077#discussion_r1805075554.

**Comment by aramase** [comment]
Added a unit test in https://github.com/kubernetes/kubernetes/pull/129993/commits/c31981e10b9471723eca8835ce681e5946647b2d that shows the failure. The test passes with the fix and I've added integration test as well.

```bash
=== RUN   Test_nodePlugin_Admit/intree_pv_to_csi,_allow_create_of_token_when_audience_in_pod_-->_csi_-->_driver_-->_tokenrequest_with_audience,_ServiceAccountNodeAudienceRestriction=true
    admission_test.go:246: nodePlugin.Admit() error = serviceaccounts "mysa" is forbidden: audience "foo" not found in pod spec volume, expected 
--- FAIL: Test_nodePlugin_Admit/intree_pv_to_csi,_allow_create_of_token_when_audience_in_pod_-->_csi_-->_driver_-->_tokenrequest_with_audience,_ServiceAccountNodeAudienceRestriction=true (0.00s)
```

File: plugin/pkg/admission/noderestriction/admission.go [hunk 1]
```diff
@@ -677,11 +681,16 @@ func (p *Plugin) podReferencesAudience(pod *v1.Pod, audience string) (bool, erro
...
 		case v.Ephemeral != nil && v.Ephemeral.VolumeClaimTemplate != nil:
 			pvcName := ephemeral.VolumeClaimName(pod, &v)
-			driverName, err = p.getCSIFromPVC(pod.Namespace, pvcName)
+			driverName, err = p.getCSIFromPVC(ctx, pod.Namespace, pvcName)
 		case v.PersistentVolumeClaim != nil:
-			driverName, err = p.getCSIFromPVC(pod.Namespace, v.PersistentVolumeClaim.ClaimName)
+			driverName, err = p.getCSIFromPVC(ctx, pod.Namespace, v.PersistentVolumeClaim.ClaimName)
 		case v.CSI != nil:
 			driverName = v.CSI.Driver
+		default:
```
Comment (carlory) [inline plugin/pkg/admission/noderestriction/admission.go:689]: It is better to check if the volume is inline migratable before trying to get csi driver name.
```go
if !p.csiTranslator.IsInlineMigratable(&v) {
   continue
}
```

Comment (carlory) [reply plugin/pkg/admission/noderestriction/admission.go:689]:
```
	foundAudiencesInPodSpec, err := p.podReferencesAudience(pod, requestedAudience)
	if err != nil {
		return fmt.Errorf("error validating audience %q: %w", requestedAudience, err)
	}
	if !foundAudiencesInPodSpec {
		return fmt.Errorf("audience %q not found in pod spec volume", requestedAudience)
	}
```

the message `audience %q not found in pod spec volume` is expected if a pod has a volume but the volume is unmigratable, i.e. configMap, secret, downwardAPI, projected, etc.

Comment (aramase) [reply plugin/pkg/admission/noderestriction/admission.go]: > It is better to check if the volume is inline migratable before trying to get csi driver name.

thanks, updated!

> the message audience %q not found in pod spec volume is expected if a pod has a volume but the volume is unmigratable, i.e. configMap, secret, downwardAPI, projected, etc.

not sure about what this comment is saying? that error message indicates there is no volume source that has this audience specified, so kubelet shouldn't be allowed to request a token for this audience.

File: plugin/pkg/admission/noderestriction/admission.go [hunk 2]
```diff
@@ -677,11 +681,16 @@ func (p *Plugin) podReferencesAudience(pod *v1.Pod, audience string) (bool, erro
...
 			pvcName := ephemeral.VolumeClaimName(pod, &v)
-			driverName, err = p.getCSIFromPVC(pod.Namespace, pvcName)
+			driverName, err = p.getCSIFromPVC(ctx, pod.Namespace, pvcName)
 		case v.PersistentVolumeClaim != nil:
-			driverName, err = p.getCSIFromPVC(pod.Namespace, v.PersistentVolumeClaim.ClaimName)
+			driverName, err = p.getCSIFromPVC(ctx, pod.Namespace, v.PersistentVolumeClaim.ClaimName)
 		case v.CSI != nil:
 			driverName = v.CSI.Driver
+		case p.csiTranslator.IsInlineMigratable(&v):
+			pv, err := p.csiTranslator.TranslateInTreeInlineVolumeToCSI(klog.FromContext(ctx), &v, pod.Namespace)
```
Comment (liggitt) [inline plugin/pkg/admission/noderestriction/admission.go:690]: does this shadow `err` so if there's an error translating it doesn't get accumulated below?

File: plugin/pkg/admission/noderestriction/admission.go [hunk 3]
```diff
@@ -717,6 +726,18 @@ func (p *Plugin) getCSIFromPVC(namespace, claimName string) (string, error) {
...
 		return pv.Spec.CSI.Driver, nil
 	}
+
+	if p.csiTranslator.IsPVMigratable(pv) {
+		// For in-tree PV, we need to convert ("translate") the PV to CSI before checking the driver name.
+		translatedPV, err := p.csiTranslator.TranslateInTreePVToCSI(klog.FromContext(ctx), pv)
+		if err != nil {
+			return "", err
+		}
+		if translatedPV.Spec.CSI != nil {
```
Comment (liggitt) [inline plugin/pkg/admission/noderestriction/admission.go:736]: do we also need to check `translatedPV != nil`? (I'm not familiar with the TranslateInTreePVToCSI guarantees)

**Review by liggitt — COMMENTED** [review]
generally looks reasonable, a couple questions / nits

What are we planning to do to recover 1.32 from this regression? our options are to backport this fix or to toggle ServiceAccountNodeAudienceRestriction to false in 1.32. I'd be inclined to do the latter.

File: plugin/pkg/admission/noderestriction/admission.go (hunk 2 above)
Comment (aramase) [reply plugin/pkg/admission/noderestriction/admission.go]: it will shadow, fixed it in the latest push

File: plugin/pkg/admission/noderestriction/admission.go (hunk 3 above)
Comment (aramase) [reply plugin/pkg/admission/noderestriction/admission.go]: we're checking for `pv != nil` before, so I've added the nil check here to be consistent.

**Comment by aramase** [comment]
> What are we planning to do to recover 1.32 from this regression? our options are to backport this fix or to toggle ServiceAccountNodeAudienceRestriction to false in 1.32. I'd be inclined to do the latter.

I was thinking we do the backport. Were you thinking we disable it only in v1.32 and keep it as-is (enabled) in v1.33+?

**Comment by liggitt** [comment]
> Were you thinking we disable it only in v1.32 and keep it as-is (enabled) in v1.33+?

Yes

**Comment by aramase** [comment]
> > Were you thinking we disable it only in v1.32 and keep it as-is (enabled) in v1.33+?
> 
> Yes

https://github.com/kubernetes/kubernetes/pull/130015 to disable it in 1.32.
