### PR TITLE
devicemanager: skip unhealthy devices in GetAllocatable

### LINKED ISSUE #104122: kubelet: podresources GetAllocatableResources doesn't take into account unhealthy devices
#### What happened:
When calling GetAllocatableDevices, the API returns all the registered devices, regardless of their health status. Thing is, the [device manager won't allocate unhealthy devices](https://github.com/kubernetes/kubernetes/blob/f27a0868d5864a74f8e8f3de1bb395ff2bc4a8bf/pkg/kubelet/cm/devicemanager/manager.go#L665) - and in general doesn't make much sense to report as allocatable Unhealthy devices, as is also documented in the [original API addition KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2043-pod-resource-concrete-assigments#proposed-api) (see last paragraph)

#### What you expected to happen:
The API should not report unhealthy device. This means the reported device set can potentially change across multiple invocations of the API, as [stated in the original KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2043-pod-resource-concrete-assigments#proposed-api). 

#### How to reproduce it (as minimally and precisely as possible):
1. Setup a kube >= 1.21 environment, enable the `KubeletPodResourcesGetAllocatable` feature gate
2. Deploy any device plugin - including sample device plugin
3. Make sure 1+ devices are reported unhealthy
4. Invoke the podresources GetAllocatableResources API, observe the unhealthy device is reported in the return value.

#### Anything else we need to know?:
N/A

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21 and beyond
- Cloud provider or hardware configuration: not relevant
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): not relevant
- Install tools: not relevant
- Network plugin and version (if this is a network-related bug): not relevant
- Others: not relevant

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The `GetAllocatableDevices` function, needed to support the podresources API, doesn't take into account the device health when computing its output.
    
In this PR we address this gap and add unit tests along the way to prevent regressions.
This gives us a good initial coverage, E2E tests to cover this case are much harder to write, because we would need to inject faults to trigger the unhealthy status. We will evaluate if adding these tests into later PRs.

#### Which issue(s) this PR fixes:
Fixes #104122

#### Special notes for your reviewer:
This ONLY affects the podresources API - the core device manager functionality is not affected.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by fromanirh** [comment]
please note this issue ONLY affects the podresources API - the core functionality of device manager is unaffected

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -1090,12 +1090,31 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
 	return false
 }
 
-// GetAllocatableDevices returns information about all the devices known to the manager
 func (m *ManagerImpl) GetAllocatableDevices() ResourceDeviceInstances {
 	m.mutex.Lock()
-	resp := m.allDevices.Clone()
+	allDevs := m.allDevices.Clone()
```
Comment (249043822) [inline pkg/kubelet/cm/devicemanager/manager.go:1095]: this change use NewResourceDeviceInstances() for response, so allDevs don't need clone

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 2]
```diff
@@ -1090,12 +1090,31 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
...
+	healthyDevs := cloneHealthDeviceData(m.healthyDevices)
```
Comment (249043822) [inline pkg/kubelet/cm/devicemanager/manager.go:1096]: need not clone

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 3]
```diff
@@ -1090,12 +1090,31 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
...
+	for resourceName, deviceInstances := range allDevs {
+		healthyIDs, ok := healthyDevs[resourceName]
+		if !ok {
+			// this is unusual, hence we log with V=2
+			klog.V(2).InfoS("Skipping resource because missing health info", "resource", resourceName)
+			continue
+		}
+		resp[resourceName] = make(map[string]pluginapi.Device)
+		for devID, devInstance := range deviceInstances {
+			if !healthyIDs.Has(devID) {
```
Comment (249043822) [inline pkg/kubelet/cm/devicemanager/manager.go:1110]: shell we consider filtering the m.allocatedDevices

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 1 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1095]: The intent is to prevent changes to `allDevices` when the for loop below runs. Creating a clone ensures that this function will return a consistent view of the kubelet devices.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 2 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1096]: The alternative is to make the critical section longer, and I don't think it's a better approach.
This (`GetAllocatableDevices`) is expected to be called "rarely" (e.g. not in a hot loop).

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 1 above)
Comment (249043822) [reply pkg/kubelet/cm/devicemanager/manager.go:1095]: the mutex can prevent that so you should not do extra things

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1095]: But this will make the critical section longer

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 3 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1110]: Could you please elaborate?

Comment (249043822) [reply pkg/kubelet/cm/devicemanager/manager.go:1108]: As the healthy device maybe still in use, then it's recorded in m.allocatedDevices, it's not allocatable, so should we filter those devices for this method

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1108]: Allocatable in this case means "resources available on the node" not the free resources on the node. Unfortunately we picked a not super-clear name and the context need to be extracted from the original KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2043-pod-resource-concrete-assigments

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1108]: https://github.com/kubernetes/enhancements/pull/2761/commits

File: pkg/kubelet/cm/devicemanager/manager_test.go [hunk 4]
```diff
@@ -434,6 +434,106 @@ func TestUpdateCapacityAllocatable(t *testing.T) {
...
+		{ID: "R1Device3", Health: pluginapi.Healthy},
+	}
+	testManager.genericDeviceUpdateCallback(resourceName1, resource1Devs)
+
+	allocatableDevs = testManager.GetAllocatableDevices()
+	as.Equal(1, len(allocatableDevs))
+	devInstances, ok = allocatableDevs[resourceName1]
+	as.True(ok)
+	as.Equal(3, len(devInstances))
+	for _, deviceID := range []string{"R1Device1", "R1Device2", "R1Device3"} {
```
Comment (matthyx) [inline pkg/kubelet/cm/devicemanager/manager_test.go:531]: nit: should we factorize these checks (len and members) into a func?

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager_test.go:531]: this could be a good idea, yes. On it.

**Comment by 249043822** [comment]
LGTM

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 5]
```diff
@@ -1090,12 +1090,29 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
...
 	m.mutex.Lock()
-	resp := m.allDevices.Clone()
-	m.mutex.Unlock()
-	klog.V(4).InfoS("Known devices", "numDevices", len(resp))
+	defer m.mutex.Unlock()
+	klog.V(4).InfoS("Known devices", "numDevices", len(m.allDevices))
+
+	resp := NewResourceDeviceInstances()
+	for resourceName, deviceInstances := range m.allDevices {
+		healthyIDs, ok := m.healthyDevices[resourceName]
```
Comment (cynepco3hahue) [inline pkg/kubelet/cm/devicemanager/manager.go:1100]: I am just curious, how does the device manager decide when the device is healthy and unhealthy?

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1100]: This callback https://github.com/kubernetes/kubernetes/blob/a2e12354edefc420e829973721030c5cb2a4270d/pkg/kubelet/cm/devicemanager/manager.go#L180 takes care of updating the health status. It is registered in the endpoint (see: https://github.com/kubernetes/kubernetes/blob/a2e12354edefc420e829973721030c5cb2a4270d/pkg/kubelet/cm/devicemanager/manager.go#L165 >>> https://github.com/kubernetes/kubernetes/blob/a2e12354edefc420e829973721030c5cb2a4270d/pkg/kubelet/cm/devicemanager/manager.go#L325) and triggers when the device plugin sends updates to the kubelet (see https://github.com/kubernetes/kubernetes/blob/a2e12354edefc420e829973721030c5cb2a4270d/pkg/kubelet/cm/devicemanager/endpoint.go#L87 >>> https://github.com/kubernetes/kubernetes/blob/a2e12354edefc420e829973721030c5cb2a4270d/pkg/kubelet/cm/devicemanager/endpoint.go#L96)

**Comment by rphillips** [comment]
lgtm

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 6]
```diff
@@ -1090,12 +1090,29 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
 	return false
 }
 
-// GetAllocatableDevices returns information about all the devices known to the manager
 func (m *ManagerImpl) GetAllocatableDevices() ResourceDeviceInstances {
 	m.mutex.Lock()
-	resp := m.allDevices.Clone()
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager.go:1096]: If you don't mind losing some of the extra logging you introduced in this function, I think a better / more concise implementation would be to extend the `ResourceDeviceInstances` type to attach a `Filter()` function that takes a `map[string]sets.String` and returns a new  `ResourceDeviceInstances` with only the filtered set of devices in it.

That would leave this function mostly unchanged, other than to transform the single line above to:
```
resp := m.allDevices.Filter(m.healthyDevices)
```

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 7]
```diff
@@ -1090,12 +1090,29 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
 	return false
 }
 
-// GetAllocatableDevices returns information about all the devices known to the manager
```
[the remark this answers is not in the document]
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1093]: fixed

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 6 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1109]: That's a nice idea. Done, and added one extra unit test.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 8]
```diff
@@ -1103,12 +1103,13 @@ func (m *ManagerImpl) isDevicePluginResource(resource string) bool {
...
+// GetAllocatableDevices returns information about all the healthy devices known to the manager
 func (m *ManagerImpl) GetAllocatableDevices() ResourceDeviceInstances {
 	m.mutex.Lock()
-	resp := m.allDevices.Clone()
-	m.mutex.Unlock()
-	klog.V(4).InfoS("Known devices", "numDevices", len(resp))
+	defer m.mutex.Unlock()
+	klog.V(4).InfoS("Known devices", "numDevices", len(m.allDevices))
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager.go:1110]: Do we really need / want this printed here?  Presumably the caller will only be interested in the "allocatable" devices (since they are calling a function called `GetAllocatableDevices()`). I don't feel too strongly since this is a `V(4)` log, but it seems unintuitive to me to include it here.

File: pkg/kubelet/cm/devicemanager/pod_devices.go [hunk 9]
```diff
@@ -384,3 +384,23 @@ func (rdev ResourceDeviceInstances) Clone() ResourceDeviceInstances {
...
+		filtered[resourceName] = make(DeviceInstances)
+		for devID, devInstance := range deviceInstances {
+			if !matchIDs.Has(devID) {
+				continue
+			}
+			filtered[resourceName][devID] = devInstance
+		}
+	}
+	return filtered
+}
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/pod_devices.go:406]: I think this can be simplified to:
```
func (rdev ResourceDeviceInstances) Filter(cond map[string]sets.String) ResourceDeviceInstances {
	filtered := NewResourceDeviceInstances()
	for resourceName, filterIDs := range cond {
		if instances, exists := range rdev[resourceName]; exists {
			for instanceID, instance := range instances {
				if filterIDs.Has(instanceID) {
					filtered[resourceName][instanceID] = instance
					break
				}
			}
		}
	}
	return filtered
}
```
or if you prefer to reduce the nesting:
```
func (rdev ResourceDeviceInstances) Filter(cond map[string]sets.String) ResourceDeviceInstances {
	filtered := NewResourceDeviceInstances()
	for resourceName, filterIDs := range cond {
		if _, exists := range rdev[resourceName]; !exists {
			continue
		}
		for instanceID, instance := range rdev[resourceName] {
			if filterIDs.Has(instanceID) {
				filtered[resourceName][instanceID] = instance
				break
			}
		}
	}
	return filtered
}
```

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 8 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/manager.go:1110]: having both the information about all and filtered out devices helps in troubleshooting, but I believe a good middleground could be coalescing the logs in one, keeping the `V(4)`.

File: pkg/kubelet/cm/devicemanager/pod_devices.go (hunk 9 above)
Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/pod_devices.go:406]: Yep, I mostly moved the code without further work :) Your second option looks nicer than mine, going for it.

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/pod_devices.go:406]: 👍 Just noticed I missed the line for the following, so don't forget to put it back in :):
```
filtered[resourceName] = make(DeviceInstances)
```

Comment (fromanirh) [reply pkg/kubelet/cm/devicemanager/pod_devices.go]: done! (and added a bit more tests)

**Review by klueska — APPROVED** [review]

**Comment by klueska** [comment]
Thanks for this PR @fromanirh and thanks for being so receptive to the suggested changes. The new semantics of this call now match the expected semantics of the caller. Moreover, they now match the semantics of `NodeAllocatable` for devices as honored by the device manager when `GetCapacity()`is called.

Things look good to go now.

/lgtm
/approve
