### PR TITLE
scheduler: forget the pod when the reserve plugins fail

### LINKED ISSUE #93830: Scheduler should forget the pod when the reverse plugins fail
This is a bug found in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93555/pull-kubernetes-integration/1292393344655167493.

The scheduler fails to schedule the pod `pv-w-prebound` on the first try due to PV is out of sync.

```
I0809 10:06:11.676940  121717 scheduler_binder.go:349] AssumePodVolumes for pod "volume-scheduling-67333a8a-4c60-4a09-9da6-9a8d731fdeb6/pod-w-pv-prebound", node "node-1"
E0809 10:06:11.676993  121717 framework.go:800] error while running Reserve in "VolumeBinding" reserve plugin for pod "pod-w-pv-prebound": v1.PersistentVolume "pv-w-prebound" is out of sync (stored: 41381, assume: 41237)
E0809 10:06:11.677104  121717 factory.go:461] "Error scheduling pod; retrying" err="error while running Reserve in \"VolumeBinding\" reserve plugin for pod \"pod-w-pv-prebound\": v1.PersistentVolume \"pv-w-prebound\" is out of sync (stored: 41381, assume: 41237)" pod="volume-scheduling-67333a8a-4c60-4a09-9da6-9a8d731fdeb6/pod-w-pv-prebound"
I0809 10:06:11.677146  121717 scheduler.go:347] Updating pod condition for volume-scheduling-67333a8a-4c60-4a09-9da6-9a8d731fdeb6/pod-w-pv-prebound to (PodScheduled==False, Reason=SchedulerError)
...
I0809 10:06:11.685464  121717 scheduler_assume_cache.go:341] Restored v1.PersistentVolume "pv-w-prebound"
```

This may happen because the PV/PVC may be modified before the scheduler binder assumes them. 

However, the scheduler skips the pod update event and never try to scheduler the pod again:

```
I0809 10:06:11.685487  121717 eventhandlers.go:356] Skipping pod volume-scheduling-67333a8a-4c60-4a09-9da6-9a8d731fdeb6/pod-w-pv-prebound update
```

This is because when the reserve plugins fails, we didn't try to forget the pod. After the `sched.recordSchedulingFailure` is called, the pod is in the `assumed` state.

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #93830

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -516,10 +516,13 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
 	// Run the Reserve method of reserve plugins.
 	if sts := prof.RunReservePluginsReserve(schedulingCycleCtx, state, assumedPod, scheduleResult.SuggestedHost); !sts.IsSuccess() {
-		sched.recordSchedulingFailure(prof, assumedPodInfo, sts.AsError(), SchedulerError, "")
 		metrics.PodScheduleError(prof.Name, metrics.SinceInSeconds(start))
 		// trigger un-reserve to clean up state associated with the reserved Pod
 		prof.RunReservePluginsUnreserve(schedulingCycleCtx, state, assumedPod, scheduleResult.SuggestedHost)
+		if forgetErr := sched.Cache().ForgetPod(assumedPod); forgetErr != nil {
+			klog.Errorf("scheduler cache ForgetPod failed: %v", forgetErr)
+		}
+		sched.recordSchedulingFailure(prof, assumedPodInfo, sts.AsError(), SchedulerError, "")
```
Comment (cofyc) [inline pkg/scheduler/scheduler.go:525]: - put `recordSchedulingFailure` after the `Forget` because if the re-enqueuing & pop-out of that failed Pod happens super fast, the pod update event may still be skipped (see https://github.com/kubernetes/kubernetes/pull/93511#issuecomment-665316132)
- put `ForgetPod` after `RunReservePluginsUnreserve` for consistency (assume -> reserve -> unreserve -> unassume)

**Review by ahg-g — COMMENTED** [review]
@Huang-Wei should we do that at line 592 as well when binding fails?

@cofyc thanks for the fix, can you please add a unit test?

**Comment by Huang-Wei** [comment]
> @Huang-Wei should we do that at line 592 as well when binding fails?

Yes, we should. It's discussed in https://github.com/kubernetes/kubernetes/pull/93511#issuecomment-666019546. Do you think we should put in in 1.19?

@cofyc thanks for the fix! It was [observed](https://github.com/kubernetes/kubernetes/pull/93511#issuecomment-665833750) actually when #93511 was introduced.

**Comment by cofyc** [comment]
> @cofyc thanks for the fix, can you please add a unit test?

I've added a case in `TestSchedulerScheduleOne` to verify that the pod will be unassumed when reserve plugins fail.

However, the race may happen if we didn't follow the order (`assume -> reserve -> unreserve -> unassume -> recordSchedulingFailure`) is hard to verify in the UT, but our integration tests (e.g. TestVolumeBinding) can help.

**Comment by cofyc** [comment]
> @cofyc thanks for the fix! It was [observed](https://github.com/kubernetes/kubernetes/pull/93511#issuecomment-665833750) actually when #93511 was introduced.

sorry, I didn't look closely at these failures. The `TestVolumeBining` integration test had been flaky for a while (https://github.com/kubernetes/kubernetes/issues/81368). I thought It was for the same reason.

**Comment by ahg-g** [comment]
Yes, I think we should do it in this PR.

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -516,10 +516,13 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
```
Comment (adtac) [inline pkg/scheduler/scheduler.go:516]: L513: we should probably make `metrics.PodScheduleError` calls be consistently ordered too while we're at it? It's metrics -> recordSchedulingFailure everywhere else except L513.

Comment (cofyc) [reply pkg/scheduler/scheduler.go:516]: SGTM

**Comment by cofyc** [comment]
> > Yes, we should. It's discussed in #93511 (comment). Do you think we should put in in 1.19?
> 
> Yes, I think we should do it in this PR.

I will implement it in this PR.

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -296,10 +311,14 @@ func TestSchedulerScheduleOne(t *testing.T) {
...
 			})
-			fwk, err := st.NewFramework([]st.RegisterPluginFunc{
+			registerPluginFuncs := []st.RegisterPluginFunc{
 				st.RegisterQueueSortPlugin(queuesort.Name, queuesort.New),
 				st.RegisterBindPlugin(defaultbinder.Name, defaultbinder.New),
-			}, frameworkruntime.WithClientSet(client))
+			}
+			if len(item.registerPluginFuncs) > 0 {
+				registerPluginFuncs = append(registerPluginFuncs, item.registerPluginFuncs...)
+			}
```
Comment (Huang-Wei) [inline pkg/scheduler/scheduler_test.go:320]: nit:

```go
registerPluginFuncs := append(
	item.registerPluginFuncs,
	st.RegisterQueueSortPlugin(queuesort.Name, queuesort.New),
	st.RegisterBindPlugin(defaultbinder.Name, defaultbinder.New),
)
```

**Review by Huang-Wei — COMMENTED** [review]
A nit in the test. LGTM otherwise.

**Comment by Huang-Wei** [comment]
> I will implement it in this PR.

Thanks!

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (cofyc) [reply pkg/scheduler/scheduler.go:513]: done

File: pkg/scheduler/scheduler.go [hunk 4]
```diff
@@ -587,6 +587,9 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
 			metrics.PodScheduleError(prof.Name, metrics.SinceInSeconds(start))
 			// trigger un-reserve plugins to clean up state associated with the reserved Pod
 			prof.RunReservePluginsUnreserve(bindingCycleCtx, state, assumedPod, scheduleResult.SuggestedHost)
+			if err := sched.SchedulerCache.ForgetPod(assumedPod); err != nil {
+				klog.Errorf("scheduler cache ForgetPod failed: %v", err)
+			}
```
Comment (cofyc) [inline pkg/scheduler/scheduler.go:592]: move `ForgetPod` from `finishBinding` here to follow the function call order on failure (unreserve -> unassume -> recordSchedulingFailure)

File: pkg/scheduler/scheduler.go [hunk 5]
```diff
@@ -504,22 +501,25 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
 	// assume modifies `assumedPod` by setting NodeName=scheduleResult.SuggestedHost
 	err = sched.assume(assumedPod, scheduleResult.SuggestedHost)
 	if err != nil {
+		metrics.PodScheduleError(prof.Name, metrics.SinceInSeconds(start))
```
Comment (cofyc) [inline pkg/scheduler/scheduler.go:504]: suggested by @adtac, call metrics function before all other functions for consistency. this aligns with other places.

**Comment by cofyc** [comment]
@Huang-Wei @ahg-g @adtac comments addressed

btw, two more test cases for permit and prebind phase

**Comment by cofyc** [comment]
/test pull-kubernetes-integration
(run more times)

File: pkg/scheduler/testing/fake_plugins.go [hunk 6]
```diff
@@ -152,3 +153,80 @@ func NewFakePreFilterPlugin(status *framework.Status) frameworkruntime.PluginFac
...
+// Permit invoked at the Permit extension point.
+func (pl *FakePermitPlugin) Permit(_ context.Context, _ *framework.CycleState, _ *v1.Pod, _ string) (*framework.Status, time.Duration) {
+	return pl.Status, pl.Timeout
+}
+
+// NewFakePermitPlugin initializes a fakePermitPlugin and returns it.
+func NewFakePermitPlugin(status *framework.Status, timeout time.Duration) frameworkruntime.PluginFactory {
+	return func(_ runtime.Object, _ framework.FrameworkHandle) (framework.Plugin, error) {
+		return &FakePermitPlugin{
+			Status: status,
```
Comment (adtac) [inline pkg/scheduler/testing/fake_plugins.go:229]: Timeout is not being saved here.

Comment (cofyc) [reply pkg/scheduler/testing/fake_plugins.go:229]: fixed, thanks!

**Comment by adtac** [comment]
LGTM :+1:

**Review by hasheddan — COMMENTED** [review]
/milestone v1.19

File: pkg/scheduler/scheduler.go [hunk 7]
```diff
@@ -422,9 +422,6 @@ func (sched *Scheduler) finishBinding(prof *profile.Profile, assumed *v1.Pod, ta
 	}
 	if err != nil {
 		klog.V(1).Infof("Failed to bind pod: %v/%v", assumed.Namespace, assumed.Name)
-		if err := sched.SchedulerCache.ForgetPod(assumed); err != nil {
-			klog.Errorf("scheduler cache ForgetPod failed: %v", err)
-		}
```
Comment (Huang-Wei) [inline pkg/scheduler/scheduler.go:427]: Good removal. This ensures we run `ForgetPod()` once, and ensure it's called at the end the failure path instead of `defer finishBinding()` in `bind()`.
