### PR TITLE
windows/service: implement graceful shutdown when run as windows service

### LINKED ISSUE #72900: Does Windows service control integration properly support stopping a service
**What happened**:
I configured Kubelet to run as a service on Windows, with a setting to restart on failure (`sc.exe failure kubelet reset= 0 actions= restart/10000`). I noticed that it restarts even when I explicitly stop the service with `sc.exe stop kubelet`, even though the `failureflag` documentation states the following (I left it at `0`, the default):
```
Changes the failure actions flag setting of a service. If this setting is 0 (default), the Service Control Manager
(SCM) enables configured failure actions on the service only if the service process terminates with the service in
a state other than SERVICE_STOPPED. If this setting is 1, the SCM enables configured failure actions on the service if the service enters the SERVICE_STOPPED state with a Win32 exit code other than 0 in addition to the service process termination as above. This setting is ignored if the service does not have any failure actions configured.
```

**What you expected to happen**:
I expected the Kubelet to only restart when killed unexpectedly, per above docs.

**Anything else we need to know?**:
I think the problem might be due to this part of our service control integration, but I'm not really sure: https://github.com/kubernetes/kubernetes/blob/master/pkg/windows/service/service.go#L85
It looks like we send `svc.Stopped` and then `os.Exit(0)`, but the official golang example sends `svc.StopPending` and just returns without exiting. (https://github.com/golang/sys/blob/master/windows/svc/example/service.go#L57). Is this difference meaningful?

- Kubernetes version (use `kubectl version`): 1.13.2
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Windows

/cc @PatrickLang @kubernetes/sig-windows-bugs 
/sig node
/sig windows

### PR DESCRIPTION
**Pull request by steffengy**
The issue here originally is that os.Exit() is called which exits
the process too early (before svc.Execute updates the status to stopped).
This is picked up as service error and leads to restarting,
if restart-on-fail is configured for the windows service.
svc.Execute already guarantees that the application is exited after,
so that os.Exit call would be unnecessary.

This rework also adds graceful shutdown, which also resolves the
underlying root cause. The graceful shutdown is not guaranteed
to succeed, since the service controller can decide to kill
the service any time after exceeding a shutdown timeout.

/sig windows
/kind bug

```release-note
windows: Ensure graceful termination when being run as windows service
```

Fixes #72900

### CODE REVIEW

**Comment by aserdean** [comment]
Thanks a lot for taking care of this @steffengy .

I was thinking to raise a SIGINT instead of os.Exit, but your implementation looks much cleaner :).

Overall LGTM, just one small question: will this work for kube-proxy as well? Maybe I missed it but I don't see where the signal handlers are being setup.

**Comment by steffengy** [comment]
@aserdean 
Kube-Proxy indeed does not seem to use that signal handling, so is unaffected by this
(There don't seem to be any shutdown mechanisms, [it just loops in SyncLoop](https://github.com/kubernetes/kubernetes/blob/a2daf66a0d61ff7c6fc094fd8f01bea61ba5778e/cmd/kube-proxy/app/server.go#L609) until the process is killed)

So to match the behavior on linux, we could just `os.Exit`  if SetupSignalHandler was never called?
I'll think about this some more.

**Comment by aserdean** [comment]
That could work, but it feels like a workaround.

The cleanest implementation, in my opinion, would be to add a graceful shutdown mechanic to kube-proxy, at least for Windows.

**Comment by steffengy** [comment]
Yeah for sure, but I don't see how that would work for windows-only, since that code is shared.
And it opens up some questions like: Do we just stop or do we also do some cleanup in that case?
Just stopping is probably fine, but it'll still be quite an invasive change compared to the rest of the PR.

**Comment by aserdean** [comment]
> Yeah for sure, but I don't see how that would work for windows-only, since that code is shared.

I think you can hook it over the proxier implementation i.e.: https://github.com/kubernetes/kubernetes/blob/a5e424dc178d128c8ab95804de83b7572ef7f10e/pkg/proxy/winkernel/proxier.go#L695
but that wouldn't be that elegant either.

> And it opens up some questions like: Do we just stop or do we also do some cleanup in that case?
> Just stopping is probably fine, but it'll still be quite an invasive change compared to the rest of the PR.

Just stopping would be fine from my perspective (I sent that the logs are flushed on [exit]([url](https://github.com/kubernetes/kubernetes/blob/a5e424dc178d128c8ab95804de83b7572ef7f10e/cmd/kube-proxy/proxy.go#L47)), but to be honest I'm not familiar with the code. 
Indeed that should probably go in a different PR and once both are merged it will fully fix: 
https://github.com/kubernetes/kubernetes/issues/72900

File: pkg/windows/service/service.go [hunk 1]
```diff
@@ -80,9 +79,19 @@ Loop:
...
-				s <- svc.Status{State: svc.Stopped}
-				// TODO: Stop the kubelet gracefully instead of killing the process
-				os.Exit(0)
+				klog.Infof("Service stopping")
+				// We need to translate this request into a signal that can be handled by the the signal handler
+				// handling shutdowns normally (currently apiserver/pkg/server/signal.go).
+				// If we do not do this, our main threads won't be notified of the upcoming shutdown.
+				// Since Windows services do not use any console, we cannot simply generate a CTRL_BREAK_EVENT
+				// but need a dedicated notification mechanism.
+				server.RequestShutdown()
```
Comment (michmike) [inline pkg/windows/service/service.go]: i am not a golang expert, but why is this needed? i would think that `break loop` will allow the process to gracefully exit after you set the status to `stopPending`

Comment (michmike) [reply pkg/windows/service/service.go]: by this, i mean the extra complexity around `server.RequestShutdown`

Comment (steffengy) [reply pkg/windows/service/service.go]: @michmike 
As the comments describe:
- The thread/goroutine running this communicates with the windows service controller.
- `break loop` will only exit that one thread, while the main thread (e.g. kubelet) will continue to run and
eventually be (forcefully) timeout-killed by the service controller.
By doing that we'd also essentially communicate to the service controller: "We're currently shutting down" but we'll never actually shut down, which it doesn't like.

- RequestShutdown() basically executes the same code that would've been executed if a SIGINT signal was received (which you cannot send/receive in "windows service mode". In windows that doesn't actually exist but there's CTRL_BREAK/CTRL_C event which are mapped to signals like SIGINT by golang. Those cannot be sent to processes without a console (User I/O) - which a service by definition does not have. So this is the least-intrusive approach to add a alternative shutdown-signaling mechanism.
- I also wouldn't call it complexity - the alternative (assuming a parallel universe where this would work) is sending the signal manually, which is much more complex than adding a single function, that might be of use elsewhere.

Let me know if that clarifies things and what you think

**Comment by steffengy** [comment]
@aserdean I implemented the exit-workaround for cases like kube-proxy and
that seems to do okay. I also agree with you, that making kube-proxy "signal-aware" is something, if done, should be done in a separate PR.

**Comment by PatrickLang** [comment]
@aserdean or @michmike can you approve?

**Comment by aserdean** [comment]
@steffengy thanks for adding the comment regarding `kube-proxy`.

/LGTM

**Comment by steffengy** [comment]
pull-kubernetes-e2e-gce looks spurious.
pull-kubernetes-verify should be addressed now.
Can i have another retry @PatrickLang  ?

**Comment by PatrickLang** [comment]
/retest
@steffengy I think you can use this command now since this has the ok-to-test label

**Comment by brendandburns** [comment]
/lgtm

on previous LGTM from @PatrickLang

File: pkg/windows/service/service.go [hunk 2]
```diff
@@ -80,9 +82,31 @@ Loop:
...
+				s <- svc.Status{State: svc.StopPending}
+
+				// If we cannot exit gracefully, we really only can exit our process, so atleast the
+				// service manager will think that we gracefully exited. At the time of writing this comment this is
+				// needed for applications that do not use signals (e.g. kube-proxy)
+				if !graceful {
+					go func() {
+						// Ensure the SCM was notified (The operation above (send to s) was received and communicated to the
+						// service control manager - so it doesn't look like the service crashes)
+						time.Sleep(1 * time.Second)
```
Comment (mtaufen) [inline pkg/windows/service/service.go]: Is there any way to explicitly flush or get an ack from the SCM, rather than just waiting for an arbitrary duration?

Comment (steffengy) [reply pkg/windows/service/service.go]: Not without effort, **you really don't want to be doing there** (and you'd have to be polling and doing windows API (=syscalls) manually here).

Also **1 second is really enough time**, we basically only need to make sure that the function that spawns this goroutine has exited, since then the relevant syscall is performed, which should only take a few hundred nanoseconds. 
Also keep in mind **that this is the edge case** (for programs that do not support graceful shutdowns).

Comment (PatrickLang) [reply pkg/windows/service/service.go]: the SCM doesn't have a way to ACK, it's the other direction. This is actually the kubelet's ack to the service control manager that the stop request was received, and is processing. If the service control manager doesn't get this pending state, it will assume the process is hung and forcefully kill it. If the process is still around after the wait (30 seconds, or more if we give it a hint when passing the stop pending status), the service control manager will poll this status again.

**Comment by michmike** [comment]
/assign @brendandburns
it wants an approve from you, not just lgtm

**Review by michmike — APPROVED** [review]
