### PR TITLE
Concurrency fixes in status.Manager

### LINKED ISSUE #16195: Find alternative mechanism to resend pod status in kubelet
The pod status manager, when fails to update, [deletes the cached value to trigger the next update]
(https://github.com/kubernetes/kubernetes/blob/165169ab1c18f0a6df60505a1bdc7783e56b303e/pkg/kubelet/status/manager.go#L262). This is not preferable because for the following reasons:

-  kubelet has grown organically to rely on the statuses in this cache. E.g., `git grep -n statusManager.GetPodStatus` shows
```
kubelet.go:1353:                        existingStatus, ok := kl.statusManager.GetPodStatus(podToUpdate.UID)
kubelet.go:1450:                        status, found := kl.statusManager.GetPodStatus(pod.UID)
kubelet.go:1573:                status, found := kl.statusManager.GetPodStatus(pod.UID)
kubelet.go:1660:                podStatus, ok := kl.statusManager.GetPodStatus(pod.UID)
kubelet.go:1680:        status, ok := kl.statusManager.GetPodStatus(pod.UID)
kubelet.go:2218:        podStatus, found := kl.statusManager.GetPodStatus(podUID)
kubelet.go:2695:        if existingStatus, hasExistingStatus := kl.statusManager.GetPodStatus(pod.UID); hasExistingStatus {
```
Arbitrarily deleting the values may affect access to such data from other components.

- This mechanism assumes kubelet would write pod status update periodically. This may no longer be true once we switch to the event-driven model (#12802), or at the least, the period would be much longer.

I suggest instruct status manager to use a different mechanism to requeue the update. Thoughts? @kubernetes/goog-node

### PR DESCRIPTION
**Pull request by timstclair**
New & improved! Now with more fixes!
- Fix deadlock when syncing deleted pods with full update channel (successful termination case in unit test)
- Prevent sending stale updates to API server
- Don't delete cached status when sync fails (causes problems for prober)
- Fixes https://github.com/kubernetes/kubernetes/issues/16195

cc/ @kubernetes/goog-node

### CODE REVIEW

File: pkg/kubelet/status/manager.go [hunk 1]
```diff
@@ -182,16 +186,37 @@ func (m *manager) TerminatePods(pods []*api.Pod) bool {
 				Terminated: &api.ContainerStateTerminated{},
 			}
 		}
-		select {
-		case m.podStatusChannel <- podStatusSyncRequest{pod, pod.Status}:
-		default:
+		newStatus := m.updateStatusInternal(pod, pod.Status)
```
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: Note to reviewers: This is a slight change in behavior, as we weren't caching the termination status before. I think this is the more correct way, although it does not enforce the same invariants as `SetPodStatus` (maintain `StartTime` and `LastTransitionTime`) - but I don't think that is necessary here.

**Comment by timstclair** [comment]
It just occurred to me that there's a risk (very low) of the server being update starved if versions change more rapidly than updates are processed. Let's discuss on Monday.

File: pkg/kubelet/status/manager.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/kubelet/status/manager.go]: That should be fine - my primary concern originally was not introducing more change than necessary in status, and fixing that is definitely desirable.

**Comment by yujuhong** [comment]
Thanks for the nice PR! :-)

> It just occurred to me that there's a risk (very low) of the server being update starved if versions change more rapidly than updates are processed. Let's discuss on Monday.

The chance is low, but it could be extremely annoying if that happens. I think removing the `isStale()` check in `syncBatch` could solve this at the cost of sending more updates, which is anyway what we do today.

Not directly related to this, but I filed an issue a few days back to handle the `DeletePodStatus` situation differently (#16195). In this PR, we still rely on the fact that status is "populated" periodically by either prober or the pod worker (since the entries are marked stale on error). I would like to remove this assumption to free the pod worker from redundant periodic syncs. Some initial ideas to achieve this: 1) set the dirty bit in the cache and trigger a flush periodically if needed, along with the original channel or 2) remove the channel and simply use a work queue model in which the goroutine wakes up and check whatever needs to be sync'd. WDYT?

**Comment by timstclair** [comment]
Made change to regularly sync "out of date" statuses to the API server, and track api server versions separately, so that update order is enforced without the potential to update-starve the API server.

**Comment by timstclair** [comment]
tests look like flakes

File: pkg/kubelet/status/manager.go [hunk 2]
```diff
@@ -182,16 +195,42 @@ func (m *manager) TerminatePods(pods []*api.Pod) bool {
...
+		if newStatus != nil {
+			select {
+			case m.podStatusChannel <- podStatusSyncRequest{pod.UID, *newStatus}:
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: Do we still need to hold the lock while sending the request to the channel? I think we no longer have to do this, similar to what SetPodStatus does now.

File: pkg/kubelet/status/manager.go [hunk 3]
```diff
@@ -211,56 +250,75 @@ func (m *manager) RemoveOrphanedStatuses(podUIDs map[types.UID]bool) {
...
-	// is full, and the pod worker holding the lock is waiting on this method
-	// to clear the channel. Even if this delete never runs subsequent container
-	// changes on the node should trigger updates.
-	go m.DeletePodStatus(pod.UID)
-	return fmt.Errorf("error updating status for pod %q: %v", kubeletutil.FormatPodName(pod), err)
+	// We failed to update status, wait for periodic sync to retry.
+	glog.Warningf("Failed to updated status for pod %q: %v", kubeletutil.FormatPodName(pod), err)
+}
+
+// needsUpdate returns whether the status is stale for the given pod UID.
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: Is this method thread-safe? Given that it's accessing the apiStatusVersions map, I'd assume it's not thread-safe. I guess only one goroutine can call this function, so we don't care?

File: pkg/kubelet/status/manager.go [hunk 4]
```diff
@@ -211,56 +250,75 @@ func (m *manager) RemoveOrphanedStatuses(podUIDs map[types.UID]bool) {
...
+	}
+
+	for uid, status := range m.podStatuses {
+		if m.needsUpdate(uid, status) {
+			m.syncPod(uid, status)
+		}
+	}
+}
+
+// syncPod syncs the given status with the API server. The caller must not hold the lock.
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: In line 266, the caller holds the podStatusesLock...

File: pkg/kubelet/status/manager.go [hunk 5]
```diff
@@ -211,56 +250,75 @@ func (m *manager) RemoveOrphanedStatuses(podUIDs map[types.UID]bool) {
...
+			glog.V(3).Infof("Pod %q was deleted and then recreated, skipping status update",
+				kubeletutil.FormatPodName(pod))
+			delete(m.apiStatusVersions, uid)
+			return
 		}
-		statusPod.Status = status
+		pod.Status = status.status
 		// TODO: handle conflict as a retry, make that easier too.
-		statusPod, err = m.kubeClient.Pods(pod.Namespace).UpdateStatus(statusPod)
+		pod, err = m.kubeClient.Pods(pod.Namespace).UpdateStatus(pod)
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: I think we need to delete the status and cached apiserver version if pod is not found here. Otherwise, we'd have leaked memory if someone else (e.g. a garbage collector) deletes the pod from etcd.

File: pkg/kubelet/status/manager.go [hunk 6]
```diff
@@ -211,56 +250,75 @@ func (m *manager) RemoveOrphanedStatuses(podUIDs map[types.UID]bool) {
...
-				glog.V(3).Infof("Pod %q is terminated, but some pods are still running", pod.Name)
-				return nil
+				glog.V(3).Infof("Pod %q is terminated, but some containers are still running", pod.Name)
+				return
 			}
-			if err := m.kubeClient.Pods(statusPod.Namespace).Delete(statusPod.Name, api.NewDeleteOptions(0)); err == nil {
-				glog.V(3).Infof("Pod %q fully terminated and removed from etcd", statusPod.Name)
+			if err := m.kubeClient.Pods(pod.Namespace).Delete(pod.Name, api.NewDeleteOptions(0)); err == nil {
+				glog.V(3).Infof("Pod %q fully terminated and removed from etcd", pod.Name)
 				m.DeletePodStatus(pod.UID)
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: perhaps we can unexport `DeletePodStatus` since no one else calls it. It doesn't have to be in this PR though.

File: pkg/kubelet/status/manager.go (hunk 2 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: We can do what SetPodStatus does, although now that we have the periodic sync, I actually wonder which approach is better. Perhaps it would be better to drop the update in the full channel case in both places and let the periodic sync pick up the update? Perhaps I'm over optimizing here.

File: pkg/kubelet/status/manager.go (hunk 3 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: It's not thread safe, but doesn't need to be. I added a couple of comments to that effect.

File: pkg/kubelet/status/manager.go (hunk 2 above)
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: I like the idea of letting periodic sync dealing with this, but I am afraid that it may increase the latency -- user deletes a terminated pod has to wait the extra 0~10s for the pod to actually be deleted.

File: pkg/kubelet/status/manager.go (hunk 3 above)
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: SG. just wanted to confirm :)

File: pkg/kubelet/status/manager.go (hunk 5 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: I'm a little confused by the positioning of this comment - where is "here"? Do you mean above where we handle the NotFound error? And maybe also where we handle the recreated case? We have cleanup loops for both orphaned statuses and apiStatusVersions, but I agree that we should try to minimize the need for cleaning up there.

File: pkg/kubelet/status/manager.go (hunk 2 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: Only in the case where the channel is full - I'm not proposing removing the channel altogether, just falling back to the periodic sync when the channel is full.

Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: Ah I see. Sounds good. The "channel is full case" currently relies on our periodic housekeeping in kubelet, but would be good to simply fall back to the periodic sync.

File: pkg/kubelet/status/manager.go (hunk 4 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: Oo... that's embarrassing, thanks for catching this! I went back and forth on the design here, and apparently left it in a half-way state. Fixed caller & fixed deadlock test to actually catch this.

File: pkg/kubelet/status/manager.go (hunk 6 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: Done.

**Comment by timstclair** [comment]
Pushed update from feedback. I had one question wrt deleting pod status (I think I addressed it?), also please take another look at SetPodStatus since I updated it with the fallback (like TerminatePods) as discussed above.

File: pkg/kubelet/status/manager.go (hunk 5 above)
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: Yes, I meant handling the NotFound error here, but you're right about the cleanup loops. There should be no need to clean up immediately. In that case, perhaps we should simply remove the `DeletePodStatus`method completely. The only use case is line 307, which is already covered by the `RemoveOrphanedStatuses`. WDYT?

Comment (timstclair) [inline pkg/kubelet/status/manager.go]: My inclination is to cleanup ASAP and only use the periodic cleanup loops as backup, because it doesn't keep stale data lying around and is more clear that it is actually getting cleaned up.

File: pkg/kubelet/status/manager.go [hunk 7]
```diff
@@ -211,56 +250,75 @@ func (m *manager) RemoveOrphanedStatuses(podUIDs map[types.UID]bool) {
...
+		return
 	}
 	if err == nil {
-		if len(pod.UID) > 0 && statusPod.UID != pod.UID {
-			glog.V(3).Infof("Pod %q was deleted and then recreated, skipping status update", kubeletutil.FormatPodName(pod))
-			return nil
+		if len(pod.UID) > 0 && pod.UID != uid {
+			glog.V(3).Infof("Pod %q was deleted and then recreated, skipping status update",
+				kubeletutil.FormatPodName(pod))
+			delete(m.apiStatusVersions, uid)
```
Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: Do we need to delete apiStatusVersions here if we don't even delete the status?

File: pkg/kubelet/status/manager.go (hunk 5 above)
Comment (timstclair) [inline pkg/kubelet/status/manager.go]: Discussed offline. Use cleanup loop for apiStatusVersion cleanup since it's internal only. Delete cached podStatus ASAP since other parts of the system (e.g. probe workers) rely on it.

Comment (yujuhong) [inline pkg/kubelet/status/manager.go]: > Delete cached podStatus ASAP since other parts of the system (e.g. probe workers) rely on it.

Just wanted to clarify: not deleting right away should not cause any problem, so this is simply a slight performance optimization. In some cases it wouldn't help, e.g., if the watch is late to receive the pod removal, pod worker may still try to create containers and posts statuses.

**Comment by yujuhong** [comment]
Thanks for the fix and extensive cleanup!

**Comment by timstclair** [comment]
@k8s-bot unit test this

**Comment by timstclair** [comment]
Squashed.

**Comment by timstclair** [comment]
@k8s-bot unit test this
