### PR TITLE
Compare stateful set updates semantically

### LINKED ISSUE #66137: StatefulSet: update forbidden because of PVC storage units
/kind bug

When deploying a StatefulSet, I included a PVC that specified `2048Gi` for the storage capacity. `kubectl apply` worked perfectly. Running `kubectl apply` again without making any changes failed with the error:

```
The StatefulSet "ss" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

After comparing the server-side yaml to my original, I noticed that it had changed the storage capacity of my PVC to `2Ti`. Changing my original from `2048Gi` to `2Ti` allowed me to then successfully run `kubectl apply`.

There is clearly a string representation being used to compare those changes rather than converting to bytes and comparing the numeric representation.

**How to reproduce it (as minimally and precisely as possible)**:
```
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2048Gi
```

**Environment**:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Azure AKS

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #66137

```release-note
fixes a validation error that could prevent updates to StatefulSet objects containing non-normalized resource requests
```

### CODE REVIEW

**Comment by liggitt** [comment]
/sig apps
/kind bug
/priority important-soon
@kubernetes/sig-apps-pr-reviews

File: pkg/apis/apps/validation/validation.go [hunk 1]
```diff
@@ -149,7 +149,7 @@ func ValidateStatefulSetUpdate(statefulSet, oldStatefulSet *apps.StatefulSet) fi
 	restoreStrategy := statefulSet.Spec.UpdateStrategy
 	statefulSet.Spec.UpdateStrategy = oldStatefulSet.Spec.UpdateStrategy
 
-	if !reflect.DeepEqual(statefulSet.Spec, oldStatefulSet.Spec) {
+	if !apiequality.Semantic.DeepEqual(statefulSet.Spec, oldStatefulSet.Spec) {
```
Comment (nikhita) [inline pkg/apis/apps/validation/validation.go]: this is used at one more place:

https://github.com/kubernetes/kubernetes/blob/0fcc38425843d973538ce743a907e4c98095f8a0/pkg/apis/policy/validation/validation.go#L53-L55

Comment (liggitt) [reply pkg/apis/apps/validation/validation.go]: another sweep could be good, but I didn't see anything under that object that semantic equality would affect

**Comment by nikhita** [comment]
:+1: lgtm from my side.

**Review by tnozicka — APPROVED** [review]
/lgtm
