### PR TITLE
De-flaking E2E: PersistentVolumes[Disruptive] - restart kubelet via service manager CLI

### LINKED ISSUE #44933: Node failed to enter NotReady state during flaky suites
/assign @saad-ali @childsb 

This is a top source of failure for this week.

Triage failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html#eba1ba01921bf541729e

Example failure text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:152
Apr 17 17:21:42.996: Node bootstrap-e2e-minion-group-4fzg failed to enter NotReady state
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-disruptive.go:242
```

Example job: https://k8s-testgrid.appspot.com/google-gce#gci-gce-flaky

Expectations: as a top source of failure this issue should interrupt assignees until the issue is closed. sig leads should `/assign` an appropriate owner and `/unassign` themselves.

### PR DESCRIPTION
**Pull request by copejon**
Current process for restarting the kubelet accesses `/etc/init.d/kubelet`, which is not a common path across OSes.  This PR changes the behavior of `kubeletCommand()` to instead attempt restarting the kubelet service through the system manager CLI.  It first attempts a systemd call, then falls back to sysVinit.  If neither calls work, the test exits.

This PR _does not_ remove `[Flaky]`.  Right now, the test fails consistently in the gci-gce-flaky suite.  After merge, I'll monitor the test grid for ~week.  If no flakes appear, I'll submit a pr to pull the Flaky tag off.

Additional Changes
- Improved error messages
- Cleanup on failure in `initTestCase`

Fixes #44933 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jeffvance** [comment]
@k8s-bot ok to test

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 1]
```diff
@@ -58,8 +59,8 @@ var _ = framework.KubeDescribe("PersistentVolumes [Volume][Disruptive][Flaky]",
 		volLabel                  labels.Set
 		selector                  *metav1.LabelSelector
 	)
-
 	BeforeEach(func() {
+
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: nit, but pseudo standard: no blank lines unless important for readability.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 2]
```diff
@@ -159,15 +159,17 @@ var _ = framework.KubeDescribe("PersistentVolumes [Volume][Disruptive][Flaky]",
 func testKubeletRestartsAndRestoresMount(c clientset.Interface, f *framework.Framework, clientPod *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume) {
 	By("Writing to the volume.")
 	file := "/mnt/_SUCCESS"
-	_, err := podExec(clientPod, fmt.Sprintf("touch %s", file))
+	out, err := podExec(clientPod, "touch "+file)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: I *think* it's more common/std to use `fmt.Sprintf()` although I see both ways.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 3]
```diff
@@ -159,15 +159,17 @@ var _ = framework.KubeDescribe("PersistentVolumes [Volume][Disruptive][Flaky]",
...
+	framework.Logf(out)
 	Expect(err).NotTo(HaveOccurred())
 
 	By("Restarting kubelet")
 	kubeletCommand(kRestart, c, clientPod)
 
 	By("Testing that written file is accessible.")
-	_, err = podExec(clientPod, fmt.Sprintf("cat %s", file))
+	out, err = podExec(clientPod, "cat "+file)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: ditto...

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 4]
```diff
@@ -178,19 +180,33 @@ func testVolumeUnmountsFromDeletedPod(c clientset.Interface, f *framework.Framew
...
+	Expect(err).NotTo(HaveOccurred(), "Encountered SSH error.")
+	Expect(result.Code).To(BeZero(), "Expected grep exit code of 0, got "+string(result.Code))
 
-	By("Restarting the kubelet.")
+	By("Stopping the kubelet.")
 	kubeletCommand(kStop, c, clientPod)
-	framework.ExpectNoError(framework.DeletePodWithWait(f, c, clientPod), "Failed to delete pod ", clientPod.Name)
+	defer func() {
+		if err != nil {
+			kubeletCommand(kStart, c, clientPod)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Is it ok to start the kubelet twice?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 5]
```diff
@@ -199,14 +215,26 @@ func testVolumeUnmountsFromDeletedPod(c clientset.Interface, f *framework.Framew
...
+			framework.DeletePersistentVolumeClaim(c, pvc.Name, ns)
+			framework.DeletePersistentVolume(c, pv.Name)
+		}
+	}()
+	//framework.WaitForPersistentVolumeClaimPhase(v1.ClaimBound, c, ns, pvc.Name, 1*time.Second, 20*time.Second)
 	Expect(err).NotTo(HaveOccurred())
 	pod := framework.MakePod(ns, []*v1.PersistentVolumeClaim{pvc}, true, "")
 	pod.Spec.NodeName = nodeName
-	framework.Logf("Creating nfs client Pod %s on node %s", pod.Name, nodeName)
+	framework.Logf("Creating nfs client Pod %s on node %s", pod.GenerateName, nodeName)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: why GenerateName?

**Comment by jeffvance** [comment]
@k8s-bot unit test this

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 2 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: I've also seen both used. I went with concatenation for slightly better readability since it's such a short string and only inserts 1 var.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 3 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: see above

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 4 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: In this instance, I think it's okay.  Issuing `start` on a running kubelet will make it restart.  This defer is primarily to protect against the kubelet being left stopped if an error happens while deleting the pod or waiting for the pod to terminate.  In testing, timeouts here left the kubelet stopped after the test finished.

The side effect being if an error occurs after the kubelet is started (SSH fails or the volume is still attached), then it will be restarted once before the function returns.  `kubeletCommand` waits for the node to come back online before returning, so this will add a few seconds to run time.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 6]
```diff
@@ -230,10 +251,19 @@ func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
...
 	Expect(err).NotTo(HaveOccurred())
 	nodeIP = nodeIP + ":22"
-	sshResult, err := framework.SSH("sudo /etc/init.d/kubelet "+string(kOp), nodeIP, framework.TestContext.Provider)
-	Expect(err).NotTo(HaveOccurred())
+	sshResult, err := framework.SSH(fmt.Sprintf("sudo systemctl %s kubelet", string(kOp)), nodeIP, framework.TestContext.Provider)
+	Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("Error occured attempting to SSH to node %q", pod.Spec.NodeName))
 	framework.LogSSHResult(sshResult)
-
+	if sshResult.Code != 0 {
+		framework.Logf("Restarting kubelet service via `systemctl` failed.  Attempting restart via `service`.")
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: not via `service` now, right?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 7]
```diff
@@ -230,10 +251,19 @@ func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
...
+		sshResult, err = framework.SSH(fmt.Sprintf("sudo service kubelet %s", string(kOp)), nodeIP, framework.TestContext.Provider)
+		Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("Error occured attempting to SSH to node %q", pod.Spec.NodeName))
+		framework.LogSSHResult(sshResult)
+		if sshResult.Code != 0 {
+			framework.Logf("Restarting kubelet service via `service` failed.")
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: `service` again

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 8]
```diff
@@ -230,10 +251,19 @@ func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
...
 	nodeIP = nodeIP + ":22"
-	sshResult, err := framework.SSH("sudo /etc/init.d/kubelet "+string(kOp), nodeIP, framework.TestContext.Provider)
-	Expect(err).NotTo(HaveOccurred())
+	sshResult, err := framework.SSH(fmt.Sprintf("sudo systemctl %s kubelet", string(kOp)), nodeIP, framework.TestContext.Provider)
+	Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("Error occured attempting to SSH to node %q", pod.Spec.NodeName))
 	framework.LogSSHResult(sshResult)
-
+	if sshResult.Code != 0 {
+		framework.Logf("Restarting kubelet service via `systemctl` failed.  Attempting restart via `service`.")
+		sshResult, err = framework.SSH(fmt.Sprintf("sudo service kubelet %s", string(kOp)), nodeIP, framework.TestContext.Provider)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Why is `kOp` used here instead of "restart"? Eg. `kOp` could be "stop".
Also, `kOp` could have been passed in as "start" . Are you trying to ensure that the kubelet is always started in the event of an error above? If the error was for "stop" then in theory the kubelet was not stopped and does not need to be restarted. If the error was for "start" then, in theory, it won't start successfully the second time either -- unless some delay is needed, in which case an explicit sleep or poll loop should be used...

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 6 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Service is correct here. `systemctl` was attempted and failed, so `service` is the fall back CLI attempt.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 9]
```diff
@@ -262,19 +265,21 @@ func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
 	sshResult, err := framework.SSH(systemctlCmd, nodeIP, framework.TestContext.Provider)
 	Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("SSH to Node %q errored.", pod.Spec.NodeName))
 	framework.LogSSHResult(sshResult)
-	if sshResult.Code == 127 /*"command not found"*/ {
+	if strings.Contains(sshResult.Stderr, "command not found") /*"command not found"*/ {
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: nit: don't need the comment here

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 10]
```diff
@@ -262,19 +265,21 @@ func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
...
 		framework.Logf("Command `%s` returned code <%d>: %q.", systemctlCmd, sshResult.Code, sshResult.Stderr)
 		framework.Logf("Attempting %s", serviceCmd)
 		sshResult, err = framework.SSH(serviceCmd, nodeIP, framework.TestContext.Provider)
 		Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("SSH to Node %q errored.", pod.Spec.NodeName))
 		framework.LogSSHResult(sshResult)
-		if sshResult.Code == 127 /*"command not found"*/ {
+		if strings.Contains(sshResult.Stderr, "command not found") /*"command not found"*/ {
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: ditto

**Comment by copejon** [comment]
/ @jingxu97 
Can you PTAL && /approve?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 11]
```diff
@@ -218,22 +240,48 @@ func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framew
...
+// kubeletCommand performs `start`, `restart`, or `stop` on the kubelet running on the node of the target pod and waits
+// for the desired statues..
+// - First issues the command via `systemctl`
+// - If `systemctl` returns stderr "command not found, issues the command via `service`
+// - If `service` also returns stderr "command not found", the test is aborted.
 // Allowed kubeletOps are `kStart`, `kStop`, and `kRestart`
+// TODO return error instead of handling internally
 func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
+	systemctlCmd := fmt.Sprintf("sudo systemctl %s kubelet", string(kOp))
+	serviceCmd := fmt.Sprintf("sudo service kubelet %s", string(kOp))
```
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-disruptive.go]: maybe move this into the if clause below?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 12]
```diff
@@ -218,22 +240,48 @@ func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framew
...
+		if strings.Contains(sshResult.Stderr, "command not found") /*"command not found"*/ {
+			framework.Logf("Command `%s` returned code <%d>: %q.", serviceCmd, sshResult.Code, sshResult.Stderr)
+			Expect(sshResult.Code).To(BeZero(), fmt.Sprintf("Unable to [%s] kubelet.", string(kOp)))
+		} else if sshResult.Code != 0 {
+			// Error other than "command not found"
+			Expect(err).To(BeZero(), "Failed to [%s] kubelet:\n%#v", string(kOp), sshResult)
+		}
+	} else if sshResult.Code != 0 {
+		// Error other than "command not found"
+		Expect(err).To(BeZero(), "Failed to [%s] kubelet:\n%#v", string(kOp), sshResult)
```
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Should it be either Expect(err).NotTo(HaveOccurred()) or Expect(sshResult.Code).To(BeZero())?

 I think it is possible that sshResult.Code is 0 but err != nil. This means that SSH failed.
The old code only checks err is nil or not.

Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: I prefer the later `Expect(sshResult.Code).To(BeZero())`. err has already been checked.

Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: @jingxu97 Thanks for catching that, it's a typo.  Fixed.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 13]
```diff
@@ -218,22 +242,36 @@ func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framew
 }
 
 // tearDownTestCase destroy resources created by initTestCase.
-func tearDownTestCase(c clientset.Interface, f *framework.Framework, ns string, pod *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume) {
-	framework.ExpectNoError(framework.DeletePodWithWait(f, c, pod), "tearDown: Failed to delete pod ", pod.Name)
-	framework.ExpectNoError(framework.DeletePersistentVolumeClaim(c, pvc.Name, ns), "tearDown: Failed to delete PVC ", pvc.Name)
-	framework.ExpectNoError(framework.DeletePersistentVolume(c, pv.Name), "tearDown: Failed to delete PV ", pv.Name)
+func tearDownTestCase(c clientset.Interface, f *framework.Framework, ns string, client, server *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume) {
+	framework.DeletePodWithWait(f, c, client)
```
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-disruptive.go]: what is the reason to remove ExpectNoError?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 14]
```diff
@@ -218,22 +242,36 @@ func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framew
...
 func kubeletCommand(kOp kubeletOpt, c clientset.Interface, pod *v1.Pod) {
 	nodeIP, err := framework.GetHostExternalAddress(c, pod)
 	Expect(err).NotTo(HaveOccurred())
 	nodeIP = nodeIP + ":22"
-	sshResult, err := framework.SSH("sudo /etc/init.d/kubelet "+string(kOp), nodeIP, framework.TestContext.Provider)
-	Expect(err).NotTo(HaveOccurred())
+	systemctlCmd := fmt.Sprintf("sudo systemctl %s kubelet", string(kOp))
+	framework.Logf("Attempting `%s`", systemctlCmd)
+	sshResult, err := framework.SSH(systemctlCmd, nodeIP, framework.TestContext.Provider)
+	Expect(err).NotTo(HaveOccurred(), fmt.Sprintf("SSH to Node %q errored.", pod.Spec.NodeName))
```
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-disruptive.go]: If error != nil, I thought the test will stop here and return?

Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: @jingxu97 It looks like err is nil when the ssh command fails (eg sshResults.Code != 0). See: [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L243)

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 13 above)
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Yes. These funcs now return error which should be checked. Previously they called `Expect()` themselves.

Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: If there's an error deleting a resource, we don't want that to end the test before attempting to delete the remaining resources.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 14 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: `framework.SSH` returns a non-nil `err` only if the ssh encounters a problem (connection timeout, authorization, etc.).  If the command being passed to SSH fails (i.e. `command not found`), then `err` is nil and stderr/stdout/exit code are returned in `sshResult`.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 13 above)
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Good point. There are other examples where errors can occur in `AfterEach`es but are ignored.  A comment to this effect would be nice.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 14 above)
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-disruptive.go]: so if err is non-nil, should we try another SSh with service kubelet, or just return?

Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: If the err return from `framework.SSH` is non-nil it means that the ssh connection failed (various reasons) so there is likely no value in re-trying with a different command. If err is nil then the `sshResult.Code` is examined to determine if the remotely executed command succeeded or not.

**Comment by jeffvance** [comment]
@k8s-bot test this

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 15]
```diff
@@ -105,44 +108,38 @@ var _ = framework.KubeDescribe("PersistentVolumes [Volume][Disruptive][Flaky]",
...
-
 		BeforeEach(func() {
 			framework.Logf("Initializing test spec")
 			clientPod, pv, pvc = initTestCase(f, c, nfsPVconfig, pvcConfig, ns, clientNode.Name)
 		})
-
 		AfterEach(func() {
 			framework.Logf("Tearing down test spec")
-			tearDownTestCase(c, f, ns, clientPod, pvc, pv)
+			tearDownTestCase(c, f, ns, clientPod, nfsServerPod, pvc, pv)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: The nfs-server pod is deleted in the outer `AfterEach` and here. Is that intentional?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 16]
```diff
@@ -159,15 +156,17 @@ var _ = framework.KubeDescribe("PersistentVolumes [Volume][Disruptive][Flaky]",
...
 	Expect(err).NotTo(HaveOccurred())
 
 	By("Restarting kubelet")
 	kubeletCommand(kRestart, c, clientPod)
 
 	By("Testing that written file is accessible.")
-	_, err = podExec(clientPod, fmt.Sprintf("cat %s", file))
+	out, err = podExec(clientPod, fmt.Sprintf("cat %s", file))
 	Expect(err).NotTo(HaveOccurred())
+	framework.Logf(out)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Here the Expect is before the Logf, but L160 the Logf occurs before the Expect. Should be consistent.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 17]
```diff
@@ -178,36 +177,61 @@ func testVolumeUnmountsFromDeletedPod(c clientset.Interface, f *framework.Framew
...
 
 // initTestCase initializes spec resources (pv, pvc, and pod) and returns pointers to be consumed
 // by the test.
 func initTestCase(f *framework.Framework, c clientset.Interface, pvConfig framework.PersistentVolumeConfig, pvcConfig framework.PersistentVolumeClaimConfig, ns, nodeName string) (*v1.Pod, *v1.PersistentVolume, *v1.PersistentVolumeClaim) {
-
 	pv, pvc, err := framework.CreatePVPVC(c, pvConfig, pvcConfig, ns, false)
+	defer func() {
+		if err != nil {
+			framework.DeletePersistentVolumeClaim(c, pvc.Name, ns)
+			framework.DeletePersistentVolume(c, pv.Name)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Intentional to skip error checking above?

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 18]
```diff
@@ -178,36 +177,61 @@ func testVolumeUnmountsFromDeletedPod(c clientset.Interface, f *framework.Framew
...
 	pod := framework.MakePod(ns, []*v1.PersistentVolumeClaim{pvc}, true, "")
 	pod.Spec.NodeName = nodeName
-	framework.Logf("Creating nfs client Pod %s on node %s", pod.Name, nodeName)
+	framework.Logf("Creating NFS client pod.")
 	pod, err = c.CoreV1().Pods(ns).Create(pod)
+	framework.Logf("NFS client Pod %q created on Node %q", pod.Name, nodeName)
 	Expect(err).NotTo(HaveOccurred())
+	defer func() {
+		if err != nil {
+			framework.DeletePodWithWait(f, c, pod)
```
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: No error check here.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 15 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Actually, it's redundant.  Will remove.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 17 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Yes, the reason being that an error will interrupt cleanup and orphan the PV.  An alternative would be to return all resources on failure.  I'm fine with that method, but I'd like to do that in a separate PR.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 18 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Same reason as above.   This defer will be at the top of the defer-stack.  I _think_ failing here will cause the test to stop without executing the next deferred cleanup call.  We did some sandboxing with defers before, I'll have to go back and verify that behavior.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 17 above)
Comment (jeffvance) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Agree.

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 18 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: In test a setup where 2 `Expect(1).To(BeZero())` are inserted into the function:  1 at function scope, 1 in side a defer block:

Only the function scope `Expect` is registered as a failure. The deferred `Expect` is completely ignored.  No output appears in test logs or summary.  So doing error checking inside a `defer` where code is triggered will be ignored.

e.g. 
```
func f(){
    defer func(){
        Expect(1).To(BeZero(), "Deferred Error")
    }()
    Expect(1).To(BeZero(), "Initial Error")
}
```
Will only produce
```
    Initial failure
    Expected
        <int>: 1
    to be zero-valued
```

File: test/e2e/storage/persistent_volumes-disruptive.go (hunk 1 above)
Comment (copejon) [inline test/e2e/storage/persistent_volumes-disruptive.go]: will fix

**Comment by jeffvance** [comment]
@k8s-bot test this
