### PR TITLE
Verify volume.GetPath() never returns ""

### LINKED ISSUE #23163: Verify volume.GetPath() never returns ""
Any call to GetPath should be checked for "" and the pod should fail with a clear indication of why.  It's a bug in a driver, but it is surfacing badly, right now.

### PR DESCRIPTION
**Pull request by dims**
Add a new helper method volume.GetPath(Mounter) instead of calling
the GetPath() of the Mounter directly. Check if GetPath() is returning
a "" and convert that into an error.

Fixes #23163

### CODE REVIEW

**Comment by dims** [comment]
@thockin - I tried the other way also (change Mounter.GetPath to return (string, error)) and that ended up deep within all the plugins which i did not feel comfortable making. This gives one single spot for making the "" check instead of making that same check in all the plugins.

**Comment by pmorie** [comment]
What error does this fix?  I do not remember how this was surfacing as a problem when Tim created the original issue.  @dims -- can you explain?

**Comment by dims** [comment]
@pmorie without this change, here's what happens right now.

```
[dims@dims-mac 14:48] ~/kubernetes/kubernetes/examples/kubectl-container ⟩ make tag
./kubectl version -c | grep -o 'GitVersion:"[^"]*"' | cut -f 2 -d '"' > .tag
Flag shorthand -c has been deprecated, please use --client instead.
Suggest using TAG=v1.4.0-alpha.1.784+ed3a29bd6aeb98-dirty
$ make container TAG=v1.4.0-alpha.1.784+ed3a29bd6aeb98-dirty
or
$ make push TAG=v1.4.0-alpha.1.784+ed3a29bd6aeb98-dirty
[dims@dims-mac 14:48] ~/kubernetes/kubernetes/examples/kubectl-container ⟩ make container
Makefile:39: *** TAG is not defined. Use 'make tag' to see a suggestion.  Stop.
```

If you look at the output, you will see the two things that are wrong

1. The deprecation warning about "-c"
2. Make container fails as the version is not extracted properly ("+ed3a29bd6aeb98-dirty" makes it barf)

Once we fix the makefile, i can try to figure out how to do the "make push" in the release scripts

Thanks,
Dims

**Comment by pmorie** [comment]
@dims - I'm not sure how that relates to this change -- are you commenting on the right issue?  Let me know if I am missing something.

**Comment by dims** [comment]
@pmorie OOOPs! hang on

**Comment by dims** [comment]
@pmorie - i don't have any more information than what's already in the issue from @thockin. My guess is that when the path was "" we probably went further down the path and blew up and from logs it was not easy to figure out that the path was empty.

**Comment by yujuhong** [comment]
Reassigned to @thockin and @jingxu97, the author and owner of #23163

**Comment by thockin** [comment]
Context was that some error case in one driver caused path to come out as "" and this was manifested as a totally off the wall error message in a distant place.  Once we figured out what it was, I felt like an assertion would have been better for discovery of the bug.

File: pkg/volume/util.go [hunk 1]
```diff
@@ -193,6 +193,15 @@ func GenerateVolumeName(clusterName, pvName string, maxLength int) string {
 	return prefix + "-" + pvName
 }
 
+// Check if the path from the mounter is empty.
+func GetPath(mounter Mounter) (string, error) {
+	path := mounter.GetPath()
+	if path == "" {
+		return "", fmt.Errorf("Path is empty")
```
Comment (thockin) [inline pkg/volume/util.go]: can we please include the details of the driver and any other context about the Mounter, so if it happens again we will know who the bad actor is?

Comment (dims) [inline pkg/volume/util.go]: Ack. I'll print the type of the mounter. At this point we can get to just either the VolumeInfo or the Mounter only from what i can tell.

**Comment by dims** [comment]
@k8s-bot test this #30132

**Comment by dims** [comment]
k8s-bot test this issue: #30132

**Comment by dims** [comment]
@k8s-bot test this issue: #30132

**Comment by dims** [comment]
@thockin the k8s-bot unilaterally decided to remove the lgtm label :( Can you please re-apply when you get a chance?

**Comment by thockin** [comment]
what a jerk!  re-added :)

**Comment by dims** [comment]
@thockin LOL thanks!
