### PR TITLE
Fixing logic for kubelet permissions check on windows

### LINKED ISSUE #108140: Kubelet permissions check on Windows does not work if running as a LocalSystem
### What happened?

If kubelet is configured to run as a service using the `LocalSystem` service account check to verify the kubelet is running with elevated privileges fails with the follow error message

```cmd
E0127 18:48:07.328394    4752 server.go:287] "kubelet running with insufficient permissions" err="error while checking admin group membership: error retrieving group ids: The user name could not be found."
```

### What did you expect to happen?

Running the kubelet as a Windows serrvier using `LocalSystem` should not report kubelet is running with insufficient permissions.

### How can we reproduce it (as minimally and precisely as possible)?

On a windows node run kubelet.exe as a service using the `LocalSystem` account.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/4033355d292505eaed05655bd91f4ea9edc7ef27/cmd/kubelet/app/server_windows.go#L29-L49

This logic checks to see if the currently running user is in the `BUILTIN\Administrators` group.
This is the correct logic if kubelet is running as a user account but does not work correctly when running as one of the built-in service accounts (Local System, Network Service, or Local Service).

Here the call to get the group Ids for a given user is failing because saying that the specified username does not exist.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by marosset**
**What this PR does / why we need it**:
The current behavior of checking kubelet permissions on Windows checks to see if the owner of the current process is in the Administrators group but doesn't indicate if the current process is running with elevated permissions (which is needed by the kubelet).
If a user is in the Administrators group it means that they _can_ start processes as elevated but does not mean that all processes that get started by that user _are_ elevated.

For the kubelet it makes more sense to just check if the current process is elevated.

The intention behind being able to check if a user can start an elevated process is so that applications that require elevated permissions can attempt to restart as elevated. This usually requires users to confirm they want to run the program as elevated in a User Account Control diaglog.

The kubelet does not do this (and shouldn't in my opinion) so there is no need to check if a user is in an admin group or not.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #108140

**Special notes for your reviewer**:

**Release note**:

```release-note
Updating kubelet permissions check for Windows nodes to see if process is elevated instead of checking if process owner is in Administrators group
```

/sig windows node
/area kubelet

Related to https://github.com/kubernetes/kubernetes/pull/96616

### CODE REVIEW

File: cmd/kubelet/app/server_windows.go [hunk 1]
```diff
@@ -21,65 +21,16 @@ package app
...
-	}
-
-	member, err := token.IsMember(sid)
-	if err != nil {
-		return fmt.Errorf("error while checking for elevated permissions: %s", err)
-	}
-	if !member {
-		return fmt.Errorf("kubelet needs to run with administrator permissions. Run as admin is: %t, User in admin group: %t", member, userIsAdmin)
+	if !isElevated {
+		return fmt.Errorf("kubelet needs to run with elevated permissions!")
```
Comment (dcantah) [inline cmd/kubelet/app/server_windows.go:33]: `errors.New` should suffice, there's no formatting used here

File: cmd/kubelet/app/server_windows.go [hunk 2]
```diff
@@ -21,65 +21,16 @@ package app
...
-		return fmt.Errorf("error while checking admin group membership: %s", err)
-	}
-
-	member, err := token.IsMember(sid)
-	if err != nil {
-		return fmt.Errorf("error while checking for elevated permissions: %s", err)
-	}
-	if !member {
-		return fmt.Errorf("kubelet needs to run with administrator permissions. Run as admin is: %t, User in admin group: %t", member, userIsAdmin)
+	if !isElevated {
```
Comment (dcantah) [inline cmd/kubelet/app/server_windows.go:32]: This could just be 
```go
if !windows.GetCurrentProcessToken.IsElevated(){}
```

Comment (marosset) [reply cmd/kubelet/app/server_windows.go:32]: Yea, i thought about doing some more logging but since I didnlt do that I can condense this further.

**Review by dcantah — APPROVED** [review]

File: cmd/kubelet/app/server_windows.go [hunk 3]
```diff
@@ -20,66 +20,14 @@ limitations under the License.
...
-	}
-
-	member, err := token.IsMember(sid)
-	if err != nil {
-		return fmt.Errorf("error while checking for elevated permissions: %s", err)
-	}
-	if !member {
-		return fmt.Errorf("kubelet needs to run with administrator permissions. Run as admin is: %t, User in admin group: %t", member, userIsAdmin)
+	if !windows.GetCurrentProcessToken().IsElevated() {
+		return errors.New("kubelet needs to run with elevated permissions!")
```
Comment (jsturtevant) [inline cmd/kubelet/app/server_windows.go:30]: Would it be useful to output who kubelet is running as here for logging?

**Review by jsturtevant — COMMENTED** [review]
Do we know if https://github.com/kubernetes/kubernetes/pull/96616 ever worked properly or if something changed?  I guess since it is a warning it didn't fail the tests.

File: cmd/kubelet/app/server_windows.go (hunk 3 above)
Comment (marosset) [reply cmd/kubelet/app/server_windows.go:30]: I thought about logging who the current user was (https://github.com/kubernetes/kubernetes/pull/108146#discussion_r807424845) but it is so simple enough to get with powershell I'm not sure it will add much value.

```
Get-Process -Name kubelet -IncludeUserName
```

**Comment by marosset** [comment]
> Do we know if #96616 ever worked properly or if something changed? I guess since it is a warning it didn't fail the tests.

I can confirm that the existing logic did not work properly on 1.23.2 bits when then kubelet was running as `LocalService`.

File: cmd/kubelet/app/server_windows.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply cmd/kubelet/app/server_windows.go:30]: +1 on getting the user name in logs for remote troubleshooting. Getting on the node to run powershell may be too involved.

**Comment by SergeyKanzhelev** [comment]
> For the kubelet it makes more sense to just check if the current process is elevated.

not very familiar with this. But would the elevated status mean admin or some power users may also run in elevated? Will kubelet has enough permissions then?

**Comment by marosset** [comment]
> > For the kubelet it makes more sense to just check if the current process is elevated.
> 
> not very familiar with this. But would the elevated status mean admin or some power users may also run in elevated? Will kubelet has enough permissions then?

Kubelet will have enough permissions if the process is elevated.
On Windows - running as an administrator or other privileges account gives the ability to start elevated processes but not all processes created by these users are elevated.  When these users are logged in two separate security tokens are created (one for launching non-elevated processes and one for launching elevated processes) and which one gets used depends on how the process is launched.

More information on how all of this works can be found at https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works#logon-process 

Because admin accounts can start processes that are either elevated or not verifying that the process owner is an admin account is not a sufficient check to ensure kubelet has access to everything it needs. What really matters is that the process is elevated and elevated processes can only be created by admin accounts (or special service accounts).

Hope this makes sense!

File: cmd/kubelet/app/server_windows.go (hunk 3 above)
Comment (mrunalp) [reply cmd/kubelet/app/server_windows.go:30]: @marosset Could you add the log? Otherwise this looks good. Thanks!

Comment (marosset) [reply cmd/kubelet/app/server_windows.go:43]: Updated to log the current user.
(Sorry I forgot about this...)
PTAL

**Comment by marosset** [comment]
/assign @mrunalp @SergeyKanzhelev 
for node review

**Comment by perithompson** [comment]
Thanks for this, I was sure my changes were working ok before @jsturtevant but it does seem I was overdoing it! 
/lgtm

**Comment by marosset** [comment]
/assign @dchen1107 @derekwaynecarr @sjenning @mrunalp @SergeyKanzhelev 
Hopefully we can get small bugfix in for 1.24
/milestone v1.24

**Review by mrunalp — APPROVED** [review]

**Comment by ruheenaansari34** [comment]
@marosset Is this fix backported to releases prior to v1.24? I'm still seeing this problem on 1.22.2.

**Comment by marosset** [comment]
I opened cherry-picks for v1.23 (https://github.com/kubernetes/kubernetes/pull/110965) and v1.24 (https://github.com/kubernetes/kubernetes/pull/110966) and am waiting for approvals from other code owners.

The feature was `alpha` in v1.22 and the cherry-pick guidelines say not to backport fixes for alpha features.

**Comment by marosset** [comment]
> @marosset Is this fix backported to releases prior to v1.24? I'm still seeing this problem on 1.22.2.

It is not.
I can start the process.
