### PR TITLE
kubeadm: support specifying HTTP endpoints for external etcd, allowing users to separate gRPC and HTTP traffic for etcd

### LINKED ISSUE #3234: 'kubeadm init' fails with 'ExternalEtcdVersion' check when the gRPC and HTTP ports are segregated
### What happened?

We are using the `--listen-client-http-urls` flag on the etcd side ([motivation](https://github.com/etcd-io/etcd/issues/15402#issuecomment-1460061395))  with a different port definition to segregate HTTP traffic from gRPC one. However, it seems that the kubeadm `ExternalEtcdVersion` check [uses](https://github.com/kubernetes/kubernetes/blob/v1.32.8/cmd/kubeadm/app/preflight/checks.go#L699-L708) the same addresses as the gRPC endpoints, which it [sets](https://github.com/kubernetes/kubernetes/blob/1bcfd5cee7905ee7c2b17cec0ecd88609693f44c/cmd/kubeadm/app/phases/controlplane/manifests.go#L217) as `etcd-endpoints` flags on the apiserver side.

As a workaround, we are passing the `--ignore-preflight-errors=ExternalEtcdVersion` flag to the command.

### What did you expect to happen?

It would be great if kubeadm could support two different etcd endpoint configurations for the etcd setup: one for gRPC connections (for API server configuration) and another for HTTP connections (for kubeadm init health check).

### How can we reproduce it (as minimally and precisely as possible)?

Set up an external etcd instance and set the `--listen-client-http-urls` parameter to a different port. Then run the command: `kubeadm init --config=/etc/kubernetes/kubeadm-config.yaml --upload-certs -v 6`.

related etcd config in kubeadm-config.yaml
```yaml
etcd:
  external:
    caFile: /etc/ssl/etcd/ssl/ca.pem
    certFile: /etc/ssl/etcd/ssl/cert.pem
    endpoints:
    - https://<etcd-node-ip>:2379
    keyFile: /etc/ssl/etcd/ssl/key.pem
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.8
Kustomize Version: v5.5.0
Server Version: v1.32.8
```

</details>

### Cloud provider

<details>
on-prem
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
kubeadm: support specifying HTTP endpoints for external etcd.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubeadm/issues/3234

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: Add `HTTPEndpoints` field to `ClusterConfiguration.Etcd.ExternalEtcd` that can be used to configure the HTTP endpoints for etcd communication in v1beta4. This field is used to separate the HTTP traffic (such as /metrics and /health endpoints) from the gRPC traffic handled by Endpoints. This separation allows for better access control, as HTTP endpoints can be exposed without exposing the primary gRPC interface. Corresponds to etcd's `--listen-client-http-urls` configuration. If not provided, Endpoints will be used for both gRPC and HTTP traffic.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go [hunk 1]
```diff
@@ -301,6 +301,11 @@ type ExternalEtcd struct {
 	// Endpoints of etcd members. Required for ExternalEtcd.
 	Endpoints []string `json:"endpoints"`
 
+	// HTTPEndpoints are the HTTP endpoints used to communicate with the etcd cluster.
+	// If not provided, the same values as in Endpoints are used.
+	// +optional
+	HTTPEndpoints []string `json:"httpEndpoints,omitempty"`
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go]: i don't we should be adding more features to v1beta3.
deprecated APIs should be considered locked.

new features in v1beta4 will also nudge users to upgrade and not stay on v1beta3.

File: cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go [hunk 2]
```diff
@@ -346,6 +346,11 @@ type ExternalEtcd struct {
 	// Endpoints of etcd members. Required for ExternalEtcd.
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go]: this  comment should be updated to explain it's for grpc

File: cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go [hunk 3]
```diff
@@ -346,6 +346,11 @@ type ExternalEtcd struct {
...
 	Endpoints []string `json:"endpoints"`
 
+	// HTTPEndpoints are the HTTP endpoints used to communicate with the etcd cluster.
+	// If not provided, the same values as in Endpoints are used.
+	// +optional
+	HTTPEndpoints []string `json:"httpEndpoints,omitempty"`
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go:361]: the existing endpoints list is validated to have http protocol in the URLs.

i think this is missing some validation in:

https://github.com/SataQiu/kubernetes/blob/c080adc2364aee7a275a9cccaf96ca8eef785c2b/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L332C29-L332C41

- endpoints should be validated to be non-empty and to have https?
- if httpenpoints is not empty we should also validate it for https?

File: cmd/kubeadm/app/apis/kubeadm/types.go [hunk 4]
```diff
@@ -328,6 +332,16 @@ type ExternalEtcd struct {
...
+// GetHTTPEndpoints returns the HTTP endpoints for external etcd communication.
+// If HTTPEndpoints is provided and not empty, it returns HTTPEndpoints.
+// Otherwise, it returns the regular Endpoints.
+func (e *ExternalEtcd) GetHTTPEndpoints() []string {
+	if len(e.HTTPEndpoints) > 0 {
+		return e.HTTPEndpoints
+	}
+	return e.Endpoints
+}
+
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/types.go]: given we apply defaulting on config load, can it be done here:
https://github.com/SataQiu/kubernetes/blob/c080adc2364aee7a275a9cccaf96ca8eef785c2b/cmd/kubeadm/app/apis/kubeadm/v1beta4/defaults.go#L124
instead of adding a new GetHTTPEndpoints() method?

File: cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go (hunk 3 above)
Comment (neolit123) [reply cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go:361]: new types should be documented in doc.go following the similar pattern from before explaining in what release it was added.

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go]: accordingly, in the release note:
> kubeadm: support specifying HTTP endpoints for external etcd, allowing users to separate gRPC and HTTP traffic for etcd.

we should explain this is a v1beta4 feature.

File: cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go (hunk 3 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go:361]: Updated. `httpenpoints` can be http instead of https.

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go (hunk 1 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go]: Done.

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/conversion.go [hunk 5]
```diff
@@ -161,3 +162,21 @@ func convertFromArgs(in []kubeadm.Arg) map[string]string {
...
+	return autoConvert_kubeadm_ExternalEtcd_To_v1beta3_ExternalEtcd(in, out, s)
+}
+
+// Convert_v1beta3_ExternalEtcd_To_kubeadm_ExternalEtcd converts a public ExternalEtcd to private ExternalEtcd.
+// It is required due to missing HTTPEndpoints in v1beta3.
+func Convert_v1beta3_ExternalEtcd_To_kubeadm_ExternalEtcd(in *ExternalEtcd, out *kubeadm.ExternalEtcd, s conversion.Scope) error {
+	out.Endpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
+	// set the HTTPEndpoints to the same as the Endpoints
+	// this is to maintain backwards compatibility with the v1beta3 API
+	out.HTTPEndpoints = *(*[]string)(unsafe.Pointer(&in.Endpoints))
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/apis/kubeadm/v1beta3/conversion.go]:
```suggestion
	out.Endpoints = *(&in.Endpoints)
	// set the HTTPEndpoints to the same as the Endpoints
	// this is to maintain backwards compatibility with the v1beta3 API
	out.HTTPEndpoints = *(&in.Endpoints)
```
will be simper?

File: cmd/kubeadm/app/apis/kubeadm/validation/validation.go [hunk 6]
```diff
@@ -329,7 +329,14 @@ func ValidateEtcd(e *kubeadm.Etcd, fldPath *field.Path) field.ErrorList {
 			allErrs = append(allErrs, field.Invalid(externalPath, "", "setting .Etcd.External.CertFile and .Etcd.External.KeyFile requires .Etcd.External.CAFile"))
 		}
 
-		allErrs = append(allErrs, ValidateURLs(e.External.Endpoints, requireHTTPS, externalPath.Child("endpoints"))...)
+		if len(e.External.Endpoints) == 0 {
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/apis/kubeadm/validation/validation.go:332]: This appears to be behavior that is incompatible with previous versions (previously we did not validate whether the length of `Endpoints` was 0). However, given that `Endpoints` should not be empty, this should not pose an issue.

**Review by HirazawaUi — COMMENTED** [review]
I'd like to know if we have test jobs based on this PR, or if tests have been run locally. The code looks great, but we still need to verify that it functions correctly. Running tests would also help us validate whether `HTTPEndpoints` and `Endpoints` provide full compatibility. If they aren't fully compatible, it could potentially cause issues.

File: cmd/kubeadm/app/apis/kubeadm/v1beta3/conversion.go (hunk 5 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/v1beta3/conversion.go]: This is copied from the auto generated code. I think it can be simplified because the type hasn't changed.

File: cmd/kubeadm/app/apis/kubeadm/validation/validation.go (hunk 6 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/validation/validation.go:332]: I think it is necessary to add this check, which can throw out errors in advance instead of hiding them in the subsequent process. Yes, in theory, this value should not be empty and will not cause any trouble for existing users.

File: cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go [hunk 7]
```diff
@@ -343,9 +343,24 @@ type LocalEtcd struct {
...
 // Kubeadm has no knowledge of where certificate files live and they must be supplied.
 type ExternalEtcd struct {
-	// Endpoints of etcd members. Required for ExternalEtcd.
+	// Endpoints of etcd members. Required when using external etcd.
+	// Specifies the client URLs (usually gRPC endpoints) for etcd communication.
+	// By default, these endpoints handle both gRPC traffic (primary etcd protocol)
+	// and HTTP traffic (metrics, health checks). However, if HTTPEndpoints is configured,
+	// the gRPC and HTTP traffic can be separated for better security and performance.
+	// Corresponds to etcd's --listen-client-urls configuration.
+	// If not provided, kubeadm will run etcd in a static pod.
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/v1beta4/types.go]: should we have this last sentence in the comment above the ExternalEtcd type?
> type ExternalEtcd struct {

File: cmd/kubeadm/app/apis/kubeadm/types.go [hunk 8]
```diff
@@ -316,10 +316,24 @@ type LocalEtcd struct {
...
 type ExternalEtcd struct {
-
-	// Endpoints of etcd members. Useful for using external etcd.
+	// Endpoints of etcd members. Required when using external etcd.
+	// Specifies the client URLs (usually gRPC endpoints) for etcd communication.
+	// By default, these endpoints handle both gRPC traffic (primary etcd protocol)
+	// and HTTP traffic (metrics, health checks). However, if HTTPEndpoints is configured,
+	// the gRPC and HTTP traffic can be separated for better security and performance.
+	// Corresponds to etcd's --listen-client-urls configuration.
 	// If not provided, kubeadm will run etcd in a static pod.
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/types.go]: same here, we should either remove the sentence or move it in the comment above the type.

**Review by neolit123 — COMMENTED** [review]
thanks for the updates, this SGTM.
just 2 minor remaining comments from me.

File: cmd/kubeadm/app/apis/kubeadm/types.go (hunk 8 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/types.go]: just removed it.
