### PR TITLE
Fix etcd migration for HA clusters

### LINKED ISSUE #43600: HA etcd upgrade v2 -> v3: Split-brain - all members became leaders
I tried a live upgrade from v2 -> v3 (i.e. without stopping the apiserver or etcd before proceeding).  After the upgrade, all 3 members of my cluster thought they were the leader.

Highlights (full log below) seem to show that it removes the other two peers for some reason, whereupon it is able to self-elect.  All three nodes exhibit the same behaviour:

```
...
2017-03-24 01:21:59.113908 I | raft: newRaft bcfded7555b0b362 [peers: [], term: 7, commit: 3720, applied: 0, lastindex: 3720, lastterm: 7]
2017-03-24 01:21:59.121101 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-03-24 01:21:59.126500 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
...
2017-03-24 01:21:59.127396 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:59.127479 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
...
2017-03-24 01:21:59.148207 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:21:59.213585 I | membership: removed member 4f1f10f8d2cc6b34 from cluster 10ac014d803ac90f
...
2017-03-24 01:21:59.213972 I | membership: removed member d39c0c65404bd457 from cluster 10ac014d803ac90f
```

Full log:

```
2017-03-24 01:15:59 Detecting if migration is needed
Performing etcd2 -> etcd3 migration
using default transformer
2017-03-24 01:16:00.747780 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:16:00.747903 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:16:00.747980 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:16:00.748096 N | membership: set the initial cluster version to 2.3
2017-03-24 01:16:00.748127 I | api: enabled capabilities for version 2.3
2017-03-24 01:16:00.751704 N | membership: updated the cluster version from 2.3 to 3.0
2017-03-24 01:16:00.751751 I | api: enabled capabilities for version 3.0
finished transforming keys
Attaching leases to TTL entries
2017-03-24 01:16:01.222877 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-b=http://etcd-b.internal.ha.awsdata.com:2380,etcd-c=http://etcd-c.internal.ha.awsdata.com:2380,etcd-d=http://etcd-d.internal.ha.awsdata.com:2380
2017-03-24 01:16:01.222920 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
2017-03-24 01:16:01.222935 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-token-etcd
2017-03-24 01:16:01.222978 I | flags: recognized environment variable ETCD_ADVERTISE_CLIENT_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.222986 I | flags: recognized environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.222993 I | flags: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.222999 I | flags: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.223006 I | flags: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.223012 I | flags: recognized environment variable ETCD_LISTEN_PEER_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:16:01.223043 I | etcdmain: etcd Version: 3.0.17
2017-03-24 01:16:01.223050 I | etcdmain: Git SHA: cc198e2
2017-03-24 01:16:01.223055 I | etcdmain: Go Version: go1.6.4
2017-03-24 01:16:01.223061 I | etcdmain: Go OS/Arch: linux/amd64
2017-03-24 01:16:01.223067 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2017-03-24 01:16:01.223101 W | etcdmain: found invalid file/dir version.txt under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
2017-03-24 01:16:01.223111 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-03-24 01:16:01.223182 I | etcdmain: listening for peers on http://127.0.0.1:2380
2017-03-24 01:16:01.223211 I | etcdmain: listening for client requests on 127.0.0.1:18629
2017-03-24 01:16:01.226330 I | etcdserver: name = etcd-ip-172-20-103-65
2017-03-24 01:16:01.226342 I | etcdserver: force new cluster
2017-03-24 01:16:01.226348 I | etcdserver: data dir = /var/etcd/data
2017-03-24 01:16:01.226354 I | etcdserver: member dir = /var/etcd/data/member
2017-03-24 01:16:01.226360 I | etcdserver: heartbeat = 100ms
2017-03-24 01:16:01.226366 I | etcdserver: election = 1000ms
2017-03-24 01:16:01.226372 I | etcdserver: snapshot count = 10000
2017-03-24 01:16:01.226381 I | etcdserver: advertise client URLs = http://127.0.0.1:18629
2017-03-24 01:16:01.472050 I | etcdserver: discarding 1 uncommitted WAL entries 
2017-03-24 01:16:01.477867 I | etcdserver: forcing restart of member bcfded7555b0b362 in cluster 10ac014d803ac90f at commit index 3714
2017-03-24 01:16:01.506223 I | raft: bcfded7555b0b362 became follower at term 6
2017-03-24 01:16:01.506259 I | raft: newRaft bcfded7555b0b362 [peers: [], term: 6, commit: 3714, applied: 0, lastindex: 3714, lastterm: 6]
2017-03-24 01:16:01.523113 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-03-24 01:16:01.524301 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:16:01.524328 I | rafthttp: starting peer 4f1f10f8d2cc6b34...
2017-03-24 01:16:01.524345 I | rafthttp: started HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.554301 I | rafthttp: started peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.554348 I | rafthttp: added peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.554453 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:16:01.554478 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:16:01.554829 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:16:01.555548 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:16:01.556726 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:16:01.556823 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:16:01.556889 I | rafthttp: starting peer d39c0c65404bd457...
2017-03-24 01:16:01.556911 I | rafthttp: started HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:16:01.557298 I | rafthttp: started peer d39c0c65404bd457
2017-03-24 01:16:01.557314 I | rafthttp: added peer d39c0c65404bd457
2017-03-24 01:16:01.557451 N | membership: set the initial cluster version to 2.3
2017-03-24 01:16:01.557483 I | api: enabled capabilities for version 2.3
2017-03-24 01:16:01.558428 N | membership: updated the cluster version from 2.3 to 3.0
2017-03-24 01:16:01.558478 I | api: enabled capabilities for version 3.0
2017-03-24 01:16:01.583495 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:16:01.583565 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:16:01.583608 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:16:01.583926 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:16:01.790276 D | rafthttp: failed to dial 4f1f10f8d2cc6b34 on stream Message (the member has been permanently removed from the cluster)
2017-03-24 01:16:01.790347 E | etcdserver: the member has been permanently removed from the cluster
2017-03-24 01:16:01.790356 I | etcdserver: the data-dir used by this member must be removed.
2017-03-24 01:16:01.792748 I | membership: removed member 4f1f10f8d2cc6b34 from cluster 10ac014d803ac90f
2017-03-24 01:16:01.792765 I | rafthttp: stopping peer 4f1f10f8d2cc6b34...
2017-03-24 01:16:01.792779 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:16:01.792789 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:16:01.792811 D | rafthttp: failed to dial 4f1f10f8d2cc6b34 on stream MsgApp v2 (the member has been permanently removed from the cluster)
2017-03-24 01:16:01.792830 I | rafthttp: stopped HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.792841 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:16:01.792850 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:16:01.792858 I | rafthttp: stopped peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.792867 I | rafthttp: removed peer 4f1f10f8d2cc6b34
2017-03-24 01:16:01.792946 I | membership: removed member d39c0c65404bd457 from cluster 10ac014d803ac90f
2017-03-24 01:16:01.792957 I | rafthttp: stopping peer d39c0c65404bd457...
2017-03-24 01:16:01.792968 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:16:01.792980 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:16:01.793004 I | rafthttp: stopped HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:16:01.793026 D | rafthttp: failed to dial d39c0c65404bd457 on stream MsgApp v2 (net/http: request canceled while waiting for connection)
2017-03-24 01:16:01.793045 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:16:01.793059 D | rafthttp: failed to dial d39c0c65404bd457 on stream Message (net/http: request canceled while waiting for connection)
2017-03-24 01:16:01.793068 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:16:01.793076 I | rafthttp: stopped peer d39c0c65404bd457
2017-03-24 01:16:01.793084 I | rafthttp: removed peer d39c0c65404bd457
2017-03-24 01:16:01.795490 I | etcdserver: aborting publish because server is stopped
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
Error:  context deadline exceeded
2017-03-24 01:21:57 Detecting if migration is needed
Performing etcd2 -> etcd3 migration
using default transformer
2017-03-24 01:21:57.383881 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:21:57.384005 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:21:57.384068 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 0
2017-03-24 01:21:57.384178 N | membership: set the initial cluster version to 2.3
2017-03-24 01:21:57.384203 I | api: enabled capabilities for version 2.3
2017-03-24 01:21:57.387081 N | membership: updated the cluster version from 2.3 to 3.0
2017-03-24 01:21:57.387138 I | api: enabled capabilities for version 3.0
2017-03-24 01:21:57.450705 I | membership: removed member 4f1f10f8d2cc6b34 from cluster 0
2017-03-24 01:21:57.450791 I | membership: removed member d39c0c65404bd457 from cluster 0
finished transforming keys
Attaching leases to TTL entries
2017-03-24 01:21:57.507832 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-b=http://etcd-b.internal.ha.awsdata.com:2380,etcd-c=http://etcd-c.internal.ha.awsdata.com:2380,etcd-d=http://etcd-d.internal.ha.awsdata.com:2380
2017-03-24 01:21:57.507917 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
2017-03-24 01:21:57.507928 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-token-etcd
2017-03-24 01:21:57.507977 I | flags: recognized environment variable ETCD_ADVERTISE_CLIENT_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.507985 I | flags: recognized environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.507991 I | flags: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.507997 I | flags: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.508003 I | flags: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.508009 I | flags: recognized environment variable ETCD_LISTEN_PEER_URLS, but unused: shadowed by corresponding flag 
2017-03-24 01:21:57.508041 I | etcdmain: etcd Version: 3.0.17
2017-03-24 01:21:57.508048 I | etcdmain: Git SHA: cc198e2
2017-03-24 01:21:57.508070 I | etcdmain: Go Version: go1.6.4
2017-03-24 01:21:57.508077 I | etcdmain: Go OS/Arch: linux/amd64
2017-03-24 01:21:57.508083 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2017-03-24 01:21:57.508116 W | etcdmain: found invalid file/dir version.txt under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
2017-03-24 01:21:57.508126 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-03-24 01:21:57.508191 I | etcdmain: listening for peers on http://127.0.0.1:2380
2017-03-24 01:21:57.508239 I | etcdmain: listening for client requests on 127.0.0.1:18629
2017-03-24 01:21:57.509282 I | etcdserver: name = etcd-ip-172-20-103-65
2017-03-24 01:21:57.509293 I | etcdserver: force new cluster
2017-03-24 01:21:57.509299 I | etcdserver: data dir = /var/etcd/data
2017-03-24 01:21:57.509305 I | etcdserver: member dir = /var/etcd/data/member
2017-03-24 01:21:57.509330 I | etcdserver: heartbeat = 100ms
2017-03-24 01:21:57.509336 I | etcdserver: election = 1000ms
2017-03-24 01:21:57.509342 I | etcdserver: snapshot count = 10000
2017-03-24 01:21:57.509351 I | etcdserver: advertise client URLs = http://127.0.0.1:18629
2017-03-24 01:21:57.581217 I | etcdserver: forcing restart of member bcfded7555b0b362 in cluster 10ac014d803ac90f at commit index 3714
2017-03-24 01:21:57.582126 I | raft: bcfded7555b0b362 became follower at term 6
2017-03-24 01:21:57.582149 I | raft: newRaft bcfded7555b0b362 [peers: [], term: 6, commit: 3714, applied: 0, lastindex: 3714, lastterm: 6]
2017-03-24 01:21:57.589294 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-03-24 01:21:57.593403 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:57.593429 I | rafthttp: starting peer 4f1f10f8d2cc6b34...
2017-03-24 01:21:57.593470 I | rafthttp: started HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.594089 I | rafthttp: started peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.594110 I | rafthttp: added peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.594197 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:57.594279 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:57.594296 I | rafthttp: starting peer d39c0c65404bd457...
2017-03-24 01:21:57.594310 I | rafthttp: started HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:21:57.595383 I | rafthttp: started peer d39c0c65404bd457
2017-03-24 01:21:57.595407 I | rafthttp: added peer d39c0c65404bd457
2017-03-24 01:21:57.595566 N | membership: set the initial cluster version to 2.3
2017-03-24 01:21:57.595613 I | api: enabled capabilities for version 2.3
2017-03-24 01:21:57.611362 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:57.611397 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:57.611425 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:21:57.611804 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:21:57.611949 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:57.611974 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:57.611996 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:21:57.612144 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:21:57.613307 N | membership: updated the cluster version from 2.3 to 3.0
2017-03-24 01:21:57.613342 I | api: enabled capabilities for version 3.0
2017-03-24 01:21:57.667072 I | membership: removed member 4f1f10f8d2cc6b34 from cluster 10ac014d803ac90f
2017-03-24 01:21:57.667104 I | rafthttp: stopping peer 4f1f10f8d2cc6b34...
2017-03-24 01:21:57.667118 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:57.667129 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:57.667303 I | rafthttp: stopped HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.667335 D | rafthttp: failed to dial 4f1f10f8d2cc6b34 on stream MsgApp v2 (net/http: request canceled while waiting for connection)
2017-03-24 01:21:57.667348 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:21:57.667364 D | rafthttp: failed to dial 4f1f10f8d2cc6b34 on stream Message (net/http: request canceled)
2017-03-24 01:21:57.667374 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:21:57.667382 I | rafthttp: stopped peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.667392 I | rafthttp: removed peer 4f1f10f8d2cc6b34
2017-03-24 01:21:57.667468 I | membership: removed member d39c0c65404bd457 from cluster 10ac014d803ac90f
2017-03-24 01:21:57.667479 I | rafthttp: stopping peer d39c0c65404bd457...
2017-03-24 01:21:57.667490 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:57.667500 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:57.667556 I | rafthttp: stopped HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:21:57.667579 D | rafthttp: failed to dial d39c0c65404bd457 on stream MsgApp v2 (net/http: request canceled while waiting for connection)
2017-03-24 01:21:57.667590 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:21:57.667605 D | rafthttp: failed to dial d39c0c65404bd457 on stream Message (net/http: request canceled)
2017-03-24 01:21:57.667614 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:21:57.667622 I | rafthttp: stopped peer d39c0c65404bd457
2017-03-24 01:21:57.667630 I | rafthttp: removed peer d39c0c65404bd457
2017-03-24 01:21:58.982506 I | raft: bcfded7555b0b362 is starting a new election at term 6
2017-03-24 01:21:58.982555 I | raft: bcfded7555b0b362 became candidate at term 7
2017-03-24 01:21:58.982564 I | raft: bcfded7555b0b362 received vote from bcfded7555b0b362 at term 7
2017-03-24 01:21:58.982609 I | raft: bcfded7555b0b362 became leader at term 7
2017-03-24 01:21:58.982623 I | raft: raft.node: bcfded7555b0b362 elected leader bcfded7555b0b362 at term 7
2017-03-24 01:21:58.984030 I | etcdserver: published {Name:etcd-ip-172-20-103-65 ClientURLs:[http://127.0.0.1:18629]} to cluster 10ac014d803ac90f
2017-03-24 01:21:58.984045 I | etcdmain: ready to serve client requests
2017-03-24 01:21:58.984364 N | etcdmain: serving insecure client requests on 127.0.0.1:18629, this is strongly discouraged!
OK
Etcd on port 18629 is up.
2017-03-24 01:21:59.011278 N | osutil: received terminated signal, shutting down...
2017-03-24 01:21:59 Migration finished
2017-03-24 01:21:59.025711 I | flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://etcd-d.internal.ha.awsdata.com:4001
2017-03-24 01:21:59.025762 I | flags: recognized and used environment variable ETCD_DATA_DIR=/var/etcd/data
2017-03-24 01:21:59.025790 I | flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-d.internal.ha.awsdata.com:2380
2017-03-24 01:21:59.025801 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-b=http://etcd-b.internal.ha.awsdata.com:2380,etcd-c=http://etcd-c.internal.ha.awsdata.com:2380,etcd-d=http://etcd-d.internal.ha.awsdata.com:2380
2017-03-24 01:21:59.025809 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
2017-03-24 01:21:59.025834 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-token-etcd
2017-03-24 01:21:59.025855 I | flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4001
2017-03-24 01:21:59.025869 I | flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
2017-03-24 01:21:59.025884 I | flags: recognized and used environment variable ETCD_NAME=etcd-d
2017-03-24 01:21:59.025941 I | etcdmain: etcd Version: 3.0.17
2017-03-24 01:21:59.025948 I | etcdmain: Git SHA: cc198e2
2017-03-24 01:21:59.025953 I | etcdmain: Go Version: go1.6.4
2017-03-24 01:21:59.025959 I | etcdmain: Go OS/Arch: linux/amd64
2017-03-24 01:21:59.025965 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2017-03-24 01:21:59.026013 W | etcdmain: found invalid file/dir version.txt under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
2017-03-24 01:21:59.026024 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-03-24 01:21:59.026085 I | etcdmain: listening for peers on http://0.0.0.0:2380
2017-03-24 01:21:59.026112 I | etcdmain: listening for client requests on 0.0.0.0:4001
2017-03-24 01:21:59.027021 I | etcdserver: name = etcd-d
2017-03-24 01:21:59.027032 I | etcdserver: data dir = /var/etcd/data
2017-03-24 01:21:59.027039 I | etcdserver: member dir = /var/etcd/data/member
2017-03-24 01:21:59.027045 I | etcdserver: heartbeat = 100ms
2017-03-24 01:21:59.027051 I | etcdserver: election = 1000ms
2017-03-24 01:21:59.027056 I | etcdserver: snapshot count = 10000
2017-03-24 01:21:59.027066 I | etcdserver: advertise client URLs = http://etcd-d.internal.ha.awsdata.com:4001
2017-03-24 01:21:59.112817 I | etcdserver: restarting member bcfded7555b0b362 in cluster 10ac014d803ac90f at commit index 3720
2017-03-24 01:21:59.113883 I | raft: bcfded7555b0b362 became follower at term 7
2017-03-24 01:21:59.113908 I | raft: newRaft bcfded7555b0b362 [peers: [], term: 7, commit: 3720, applied: 0, lastindex: 3720, lastterm: 7]
2017-03-24 01:21:59.121101 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-03-24 01:21:59.126500 I | membership: added member 4f1f10f8d2cc6b34 [http://etcd-c.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:59.126527 I | rafthttp: starting peer 4f1f10f8d2cc6b34...
2017-03-24 01:21:59.126563 I | rafthttp: started HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.127284 I | rafthttp: started peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.127305 I | rafthttp: added peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.127396 I | membership: added member bcfded7555b0b362 [http://etcd-d.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:59.127479 I | membership: added member d39c0c65404bd457 [http://etcd-b.internal.ha.awsdata.com:2380] to cluster 10ac014d803ac90f
2017-03-24 01:21:59.127496 I | rafthttp: starting peer d39c0c65404bd457...
2017-03-24 01:21:59.127511 I | rafthttp: started HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:21:59.128609 I | rafthttp: started peer d39c0c65404bd457
2017-03-24 01:21:59.128634 I | rafthttp: added peer d39c0c65404bd457
2017-03-24 01:21:59.128805 N | membership: set the initial cluster version to 2.3
2017-03-24 01:21:59.128854 I | api: enabled capabilities for version 2.3
2017-03-24 01:21:59.135605 N | membership: updated the cluster version from 2.3 to 3.0
2017-03-24 01:21:59.135658 I | api: enabled capabilities for version 3.0
2017-03-24 01:21:59.147385 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:59.147415 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:59.147444 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:21:59.147809 I | rafthttp: started streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:21:59.147950 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:59.147977 I | rafthttp: started streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:59.148000 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:21:59.148207 I | rafthttp: started streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:21:59.213585 I | membership: removed member 4f1f10f8d2cc6b34 from cluster 10ac014d803ac90f
2017-03-24 01:21:59.213619 I | rafthttp: stopping peer 4f1f10f8d2cc6b34...
2017-03-24 01:21:59.213634 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:59.213645 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (writer)
2017-03-24 01:21:59.213825 I | rafthttp: stopped HTTP pipelining with peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.213857 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream MsgApp v2 reader)
2017-03-24 01:21:59.213877 I | rafthttp: stopped streaming with peer 4f1f10f8d2cc6b34 (stream Message reader)
2017-03-24 01:21:59.213885 I | rafthttp: stopped peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.213895 I | rafthttp: removed peer 4f1f10f8d2cc6b34
2017-03-24 01:21:59.213972 I | membership: removed member d39c0c65404bd457 from cluster 10ac014d803ac90f
2017-03-24 01:21:59.213983 I | rafthttp: stopping peer d39c0c65404bd457...
2017-03-24 01:21:59.213995 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:59.214005 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (writer)
2017-03-24 01:21:59.214068 I | rafthttp: stopped HTTP pipelining with peer d39c0c65404bd457
2017-03-24 01:21:59.214100 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream MsgApp v2 reader)
2017-03-24 01:21:59.214120 I | rafthttp: stopped streaming with peer d39c0c65404bd457 (stream Message reader)
2017-03-24 01:21:59.214128 I | rafthttp: stopped peer d39c0c65404bd457
2017-03-24 01:21:59.214136 I | rafthttp: removed peer d39c0c65404bd457
2017-03-24 01:21:59.614341 I | raft: bcfded7555b0b362 is starting a new election at term 7
2017-03-24 01:21:59.614404 I | raft: bcfded7555b0b362 became candidate at term 8
2017-03-24 01:21:59.614414 I | raft: bcfded7555b0b362 received vote from bcfded7555b0b362 at term 8
2017-03-24 01:21:59.614438 I | raft: bcfded7555b0b362 became leader at term 8
2017-03-24 01:21:59.614450 I | raft: raft.node: bcfded7555b0b362 elected leader bcfded7555b0b362 at term 8
2017-03-24 01:21:59.615726 I | etcdserver: published {Name:etcd-d ClientURLs:[http://etcd-d.internal.ha.awsdata.com:4001]} to cluster 10ac014d803ac90f
2017-03-24 01:21:59.615741 I | etcdmain: ready to serve client requests
2017-03-24 01:21:59.616112 N | etcdmain: serving insecure client requests on 0.0.0.0:4001, this is strongly discouraged!
```

### PR DESCRIPTION
**Pull request by wojtek-t**
@jpbetz 

Fix #43600

### CODE REVIEW

File: cluster/images/etcd/migrate-if-needed.sh [hunk 1]
```diff
@@ -122,7 +122,6 @@ start_etcd() {
   ${ETCD_CMD} \
     --name="etcd-$(hostname)" \
     --debug \
-    --force-new-cluster \
```
Comment (jpbetz) [inline cluster/images/etcd/migrate-if-needed.sh]: This looks good.  I noticed in the docs that this flag would be needed for a recover, but It doesn't look like we do any recovers in this script (double check me on that), so we should be okay. And we must remove it for HA cluster startup, as you've already discovered.

File: cluster/images/etcd/migrate-if-needed.sh [hunk 2]
```diff
@@ -154,7 +153,7 @@ ROLLBACK="${ROLLBACK:-/usr/local/bin/rollback}"
 # If we are upgrading from 2.2.1 and this is the first try for upgrade,
 # do the backup to allow restoring from it in case of failed upgrade.
 BACKUP_DIR="${DATA_DIRECTORY}/migration-backup"
-if [ "${CURRENT_VERSION}" = "2.2.1" -a ! "${CURRENT_VERSION}" != "${TARGET_VERSION}" -a -d "${BACKUP_DIR}" ]; then
+if [ "${CURRENT_VERSION}" = "2.2.1" -a "${CURRENT_VERSION}" != "${TARGET_VERSION}" -a ! -d "${BACKUP_DIR}" ]; then
```
Comment (jpbetz) [inline cluster/images/etcd/migrate-if-needed.sh]: Logic looks correct. Thanks for fixing.

**Review by jpbetz — APPROVED** [review]
lgtm

File: cluster/images/etcd/migrate-if-needed.sh (hunk 1 above)
Comment (wojtek-t) [inline cluster/images/etcd/migrate-if-needed.sh]: Yes - this is not used for recovers. To recover from backup we are using:
https://github.com/kubernetes/kubernetes/blob/master/cluster/restore-from-backup.sh

**Comment by wojtek-t** [comment]
@jpbetz - you need to write "/lgtm" instead of "lgtm" to have it lgtm-ed.

Applying labels based on the comments above.
