### PR TITLE
Check whether mirror pod is ciritical in managerImpl#evictPod

### LINKED ISSUE #83317: Static pods be evicted when diskPressure. Commit c05d506 doesn't seem to work.
**What happened**:

My k8s version is 1.15.
I want my static pods which are not in "kube-system" won't be evicted when diskPressure.
I found that after PR: https://github.com/kubernetes/kubernetes/pull/80491/files ,  static pods should not be evicted when diskPressure.
I won't update to 1.16 temporarily.
So I cherry-picked this commit: c05d5060193221dd5ebcf031d2b2708af5d00c5f to my kubelet.

But when I did some tests, I found that this commit doesn't work when diskPressure.
I think the reason is like info in this comment: https://github.com/kubernetes/kubernetes/issues/73572#issuecomment-470444663

detail:

When diskPressure , the pod sent to `IsCriticalPod` is a mirrorPod.(`pkg/kubelet/eviction/eviction_manager.go#evictPod`).

When a mirrorPod list-watched by kubelet, the `annotation[kubernetes.io/config.source]` is set to be the source that kubelet list-watch the pod from, which is `"api"`. (`pkg/kubelet/config/config.go#updatePodsFunc`)

Because the `annotation[kubernetes.io/config.source]` of  mirrorPod is `"api"`, the func `"pkg/kubelet/types/pod_update.go#IsStaticPod"` returns `false`. 
So static pods will be evicted when diskPressure.

I thought how to fix it.
The func `"pkg/kubelet/types/pod_update.go#IsCriticalPod"` deals with staticPod and mirrorPod in different scene. 
So I changed my kubelet to add the verifying of mirrorPod after the verifying of staticPod.
just like this(My original code is k8s1.15 cherry-pick c05d5060193221dd5ebcf031d2b2708af5d00c5f, so it looks strange.):
```go
func IsCriticalPod(pod *v1.Pod) bool {
	if IsStaticPod(pod) {
		return true
	}
	if IsMirrorPod(pod) {
		return true
	}
	if utilfeature.DefaultFeatureGate.Enabled(features.PodPriority) {
		if pod.Spec.Priority != nil && IsCriticalPodBasedOnPriority(*pod.Spec.Priority) {
			return true
		}
	}
	if utilfeature.DefaultFeatureGate.Enabled(features.ExperimentalCriticalPodAnnotation) {
		if IsCritical(pod.Namespace, pod.Annotations) {
			return true
		}
	}
	return false
}
```

After I changed my code to this, static pod didn't be evicted when diskPressure.
So I think this is the reason. And I think this is a Bug.

Maybe I will set `pod.Spec.Priority` to my static pods to prevent eviction temporarily, and I also hope this bug will be fixed in a good way.

**What you expected to happen**:
Static pods won't be evicted when diskPressure.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a static pod on a node. The pod is not set `pod.Spec.Priority` or `pod.Spec.PriorityClassName`. 
2. Let the node under diskPressure (using `fallocate -l 104G file1`).

Then the static pod will be evicted.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): My kubelet is k8s1.15  cherry-pick c05d5060193221dd5ebcf031d2b2708af5d00c5f.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As #83317 reported, static pod would be evicted when diskPressure arises.

This PR adds check for mirror pod for criticality.

**Which issue(s) this PR fixes**:
Fixes #83317

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/eviction/eviction_manager.go [hunk 1]
```diff
@@ -560,6 +561,11 @@ func (m *managerImpl) evictPod(pod *v1.Pod, gracePeriodOverride int64, evictMsg
 			klog.Errorf("eviction manager: cannot get mirror pod from static pod %s, so cannot evict it", format.Pod(pod))
 			return false
 		}
+	} else if kubepod.IsMirrorPod(pod) {
+		if kubelettypes.IsCriticalPod(pod) {
+			klog.Errorf("eviction manager: cannot evict a critical mirror pod %s", format.Pod(pod))
+			return false
+		}
```
Comment (hpandeycodeit) [inline pkg/kubelet/eviction/eviction_manager.go]: As per this change, we will not be evicting a critical mirror pod as well. I am a little doubtful here. Let's discuss more before we proceed with this PR.

Comment (bsalamat) [reply pkg/kubelet/eviction/eviction_manager.go]: All static pods are considered critical since 1.16. I think we should change `IsCriticalPod` to consider mirror pods as critical as well. Then, all we need here is to delete the whole `if IsStaticPod` statement and have just one check for the pod critical status and return false if the pod is critical.

Comment (tedyu) [reply pkg/kubelet/eviction/eviction_manager.go]: When kubepod.IsMirrorPod() is added to pod_update.go :
```
can't load package: import cycle not allowed
package k8s.io/kubernetes/pkg/kubelet/types
	imports k8s.io/kubernetes/pkg/kubelet/pod
	imports k8s.io/kubernetes/pkg/kubelet/types
```

Comment (bsalamat) [reply pkg/kubelet/eviction/eviction_manager.go]: Please move `IsMirrorPod()` to pod_update.go and place it next to `IsStaticPod()`.

**Comment by tedyu** [comment]
@bsalamat 
Please take another look.

File: pkg/kubelet/eviction/eviction_manager.go [hunk 2]
```diff
@@ -547,19 +547,9 @@ func (m *managerImpl) evictPod(pod *v1.Pod, gracePeriodOverride int64, evictMsg
...
-			if kubelettypes.IsCriticalPod(mirrorPod) {
-				klog.Errorf("eviction manager: cannot evict a critical static pod %s", format.Pod(pod))
-				return false
-			}
-		} else {
-			// we should never hit this
-			klog.Errorf("eviction manager: cannot get mirror pod from static pod %s, so cannot evict it", format.Pod(pod))
-			return false
-		}
+	if kubelettypes.IsCriticalPod(pod) {
```
Comment (KeepTheBeats) [inline pkg/kubelet/eviction/eviction_manager.go]: From the discussion of https://github.com/kubernetes/kubernetes/issues/73572, we got that, In `IsCriticalPod --> IsCriticalPodBasedOnPriority(*pod.Spec.Priority)`, the func should use `pod.Spec.Priority` to do something.
But if users only set `spec.priorityClassName` rather than `spec.priority` to a static pod, the admission-controller only set  `spec.priority` to the mirror pod, and the static pod won't have  `spec.priority`.
So, it seems that, for static pod, we should send its mirror pod to the func  IsCriticalPod.

**Review by hpandeycodeit — COMMENTED** [review]
/lgtm

**Review by bsalamat — APPROVED** [review]
/lgtm
/approve

**Comment by tedyu** [comment]
@dchen1107
Can you approve this ?

Thanks

File: pkg/kubelet/types/pod_update.go [hunk 3]
```diff
@@ -137,11 +137,20 @@ func (sp SyncPodType) String() string {
 	}
 }
 
+// IsMirrorPod returns true if the passed Pod is a Mirror Pod.
+func IsMirrorPod(pod *v1.Pod) bool {
```
[the remark this answers is not in the document]
Comment (tedyu) [reply pkg/kubelet/types/pod_update.go]: @bsalamat 
Can you give /lgtm again ?

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Comment by tedyu** [comment]
@dchen1107 
Can you take a look ?

**Comment by dchen1107** [comment]
Ok with the fix, but asked one question at: https://github.com/kubernetes/kubernetes/issues/83317#issuecomment-539147793

/lgtm
/approve

File: pkg/kubelet/eviction/eviction_manager.go (hunk 1 above)
Comment (andy-wolf168) [reply pkg/kubelet/eviction/eviction_manager.go]: > All static pods are considered critical since 1.16. I think we should change `IsCriticalPod` to consider mirror pods as critical as well. Then, all we need here is to delete the whole `if IsStaticPod` statement and have just one check for the pod critical status and return false if the pod is critical.

Hi, @bsalamat can this PR merged to 1.15.8 ?

**Comment by andy-wolf168** [comment]
> **What type of PR is this?**
> /kind bug
> 
> **What this PR does / why we need it**:
> As #83317 reported, static pod would be evicted when diskPressure arises.
> 
> This PR adds check for mirror pod for criticality.
> 
> **Which issue(s) this PR fixes**:
> Fixes #83317
> 
> ```
> NONE
> ```
> 
> **Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> 
> ```
> 
> ```

@dchen1107 @tedyu   can this PR merge to k8s 1.15?

> **What type of PR is this?**
> /kind bug
> 
> **What this PR does / why we need it**:
> As #83317 reported, static pod would be evicted when diskPressure arises.
> 
> This PR adds check for mirror pod for criticality.
> 
> **Which issue(s) this PR fixes**:
> Fixes #83317
> 
> ```
> NONE
> ```
> 
> **Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
> 
> ```
> 
> ```

Hi,@tedyu @dchen1107 ,can this PR merge to k8s 1.15 ?
