### PR TITLE
Category expansion fully based on discovery

### LINKED ISSUE #41353: Use of hardcoded "UserResources" breaks `kubectl get all` if server does not have at least one of the resources
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.1.778+7585c46bc18913-dirty", GitCommit:"7585c46bc18913232a72d83e2f5a02a5a1f65c1b", GitTreeState:"dirty", BuildDate:"2017-02-13T18:47:18Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

Using `kubectl` against an api server that does not have at least a [single resource in this list defined](
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/shortcut_restmapper.go#L105-L113) causes `kubectl get all` to fail with:

```
the server doesn't have a resource type "pods"
```

Instead of defaulting to the hardcoded list of resources, we could instead attempt to use the discovered resources from the server (if any were found). 

**How to reproduce it** (as minimally and precisely as possible):
`kubectl get all --server=<address of service catalog api server>`

cc @pmorie

### PR DESCRIPTION
**Pull request by fabianofranz**
**What this PR does / why we need it**: Makes the expansion of resource names in `kubectl` (e.g. "all" in "kubectl get all") respect the "categories"  field in the API, and fallback to the legacy expander.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/41353

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@deads2k When writing this I realized that "services" doesn't provide "all" (or anything) on its "categories" field. Is it known/desired?

File: pkg/kubectl/resource/categories.go [hunk 1]
```diff
@@ -36,6 +36,58 @@ func (e SimpleCategoryExpander) Expand(category string) ([]schema.GroupResource,
...
+type discoveryCategoryExpander struct {
+	fallbackExpander CategoryExpander
+	discoveryClient  discovery.DiscoveryInterface
+}
+
+// NewDiscoveryCategoryExpander returns a category expander that makes use of the "categories" fields from
+// the API, found through the discovery client. In case of any error or no category found (which likely
+// means we're at a cluster prior to categories support, fallback to the expander provided.
+func NewDiscoveryCategoryExpander(fallbackExpander CategoryExpander, client discovery.DiscoveryInterface) (discoveryCategoryExpander, error) {
+	if client == nil {
```
Comment (deads2k) [inline pkg/kubectl/resource/categories.go]: if it's coder error, why not panic?

File: pkg/kubectl/resource/categories.go [hunk 2]
```diff
@@ -36,6 +36,58 @@ func (e SimpleCategoryExpander) Expand(category string) ([]schema.GroupResource,
...
+		return discoveryCategoryExpander{}, errors.New("Please provide discovery client to shortcut expander")
+	}
+	return discoveryCategoryExpander{fallbackExpander: fallbackExpander, discoveryClient: client}, nil
+}
+
+func (e discoveryCategoryExpander) Expand(category string) ([]schema.GroupResource, bool) {
+	apiResourceLists, err := e.discoveryClient.ServerResources()
+	if err != nil {
```
Comment (deads2k) [inline pkg/kubectl/resource/categories.go]: I would run this check differently.  The `ServerResources` signature can return an error *and* a valid (but partial) list of resources.  If you have any resources, I would continue. If you have zero resources, I would fallback.

File: pkg/kubectl/resource/categories.go [hunk 3]
```diff
@@ -36,6 +36,58 @@ func (e SimpleCategoryExpander) Expand(category string) ([]schema.GroupResource,
...
+		return e.fallbackExpander.Expand(category)
+	}
+
+	discoveredExpansions := map[string][]schema.GroupResource{}
+
+	for _, apiResourceList := range apiResourceLists {
+		gv, err := schema.ParseGroupVersion(apiResourceList.GroupVersion)
+		if err != nil {
```
Comment (deads2k) [inline pkg/kubectl/resource/categories.go]: this particular error is bad, I would return an error instead of falling back.

File: pkg/kubectl/resource/categories.go [hunk 4]
```diff
@@ -36,6 +36,58 @@ func (e SimpleCategoryExpander) Expand(category string) ([]schema.GroupResource,
...
+						Group:    gv.Group,
+						Resource: apiResource.Name,
+					}
+					discoveredExpansions[category] = append(discoveredExpansions[category], groupResource)
+				}
+			}
+		}
+	}
+
+	if len(discoveredExpansions) == 0 {
```
Comment (deads2k) [inline pkg/kubectl/resource/categories.go]: This looks good.

**Comment by deads2k** [comment]
> @deads2k When writing this I realized that "services" doesn't provide "all" (or anything) on its "categories" field. Is it known/desired?

check the actual discovery doc.  My memory says that the storage for services is wrapped and we add the category there.

**Comment by deads2k** [comment]
Minor comments, lgtm otherwise.

This is a bug we we should fix in 1.8.

File: pkg/kubectl/resource/categories.go (hunk 2 above)
Comment (fabianofranz) [reply pkg/kubectl/resource/categories.go]: @deads2k Should I check both (fallback if zero resources **and** error)?

Comment (deads2k) [reply pkg/kubectl/resource/categories.go]: Only fallback if there are zero resources, otherwise continue.

File: pkg/kubectl/resource/categories.go (hunk 3 above)
Comment (fabianofranz) [reply pkg/kubectl/resource/categories.go]: @deads2k should we change the `CategoryExpander` interface signature? No error returned in `Expand` ATM.

Comment (deads2k) [reply pkg/kubectl/resource/categories.go]: > @deads2k should we change the CategoryExpander interface signature? No error returned in Expand ATM.

hmmm... ok.  I can deal with a fallback for 1.8 to avoid too many ripples at this stage.

**Comment by fabianofranz** [comment]
@deads2k comments addressed, tks.

**Comment by fabianofranz** [comment]
/test pull-kubernetes-e2e-kops-aws
--
