### PR TITLE
backoff image pulling on failure

### LINKED ISSUE #4121: Kubelet should back off restarts of crashlooping containers
See #941 and #2529 for more background. Right now users have a bad experience if they submit a bad container, such as mistyped image name. Kubelet shouldn't restart it in a tight loop. Instead, it should back off.

### PR DESCRIPTION
**Pull request by samsabed**
fixes #4121
This implements a back-off when kublet fails to pull an image, the back-off is keyed to the pod/image
and  changing the "reason" to a short string, #11007 is adding a message field. don't know if that's the right order.

### CODE REVIEW

**Comment by samsabed** [comment]
@dchen1107 this adds back-off for failing image pulls

**Comment by samsabed** [comment]
ping  @yujuhong @dchen1107

**Comment by samsabed** [comment]
@yujuhong rebased, I'll add the message part of "Reason" in another one to keep this more focused.

**Comment by samsabed** [comment]
@kubernetes/goog-node is this being blocked for a reason or is it lack of reviewer time

**Comment by dchen1107** [comment]
ping...

**Comment by yujuhong** [comment]
Reviewing. Sorry for the delay.

File: pkg/kubelet/container/image_puller.go [hunk 1]
```diff
@@ -56,24 +59,18 @@ func shouldPullImage(container *api.Container, imagePresent bool) bool {
...
-	switch event {
-	case "pulling":
-		puller.recorder.Eventf(ref, "Pulling", "Pulling image %q", image)
-	case "pulled":
-		puller.recorder.Eventf(ref, "Pulled", "Successfully pulled image %q", image)
-	case "failed":
-		puller.recorder.Eventf(ref, "Failed", "Failed to pull image %q: %v", image, pullError)
+// records an event using ref, event msg.  log to glog using prefix, msg, logFn
+func (puller *imagePuller) logIt(ref *api.ObjectReference, event, prefix, msg string, logFn func(args ...interface{})) {
+	logFn(fmt.Sprint(prefix, " ", msg))
```
Comment (yujuhong) [inline pkg/kubelet/container/image_puller.go]: I think we already log the events in the log. How about only log if we cannot record an event?

Another thing is that we should have different verbose level for the logging.

File: pkg/kubelet/container/image_puller.go [hunk 2]
```diff
@@ -56,24 +59,18 @@ func shouldPullImage(container *api.Container, imagePresent bool) bool {
...
+	if ref != nil {
+		puller.recorder.Eventf(ref, event, msg)
 	}
+	return
```
Comment (yujuhong) [inline pkg/kubelet/container/image_puller.go]: no need to return here

File: pkg/kubelet/container/image_puller.go [hunk 3]
```diff
@@ -81,24 +78,37 @@ func (puller *imagePuller) PullImage(pod *api.Pod, container *api.Container, pul
...
-		if present && ref != nil {
-			puller.recorder.Eventf(ref, "Pulled", "Container image %q already present on machine", container.Image)
+		if present {
+			msg := fmt.Sprintf("Container image %q already present on machine", container.Image)
+			puller.logIt(ref, "Pulled", logPrefix, msg, glog.Info)
+			return nil
+		} else {
+			msg := fmt.Sprintf("Container image %q is not present with pull policy of Never", container.Image)
+			puller.logIt(ref, "ErrImageNeverPull", logPrefix, msg, glog.Warning)
+			return (ErrImageNeverPull)
```
Comment (yujuhong) [inline pkg/kubelet/container/image_puller.go]: nit: remove the parentheses

File: pkg/kubelet/dockertools/docker_test.go [hunk 4]
```diff
@@ -657,7 +658,7 @@ func TestFindContainersByPod(t *testing.T) {
 	}
 	fakeClient := &FakeDockerClient{}
 	np, _ := network.InitNetworkPlugin([]network.NetworkPlugin{}, "", network.NewFakeHost(nil))
-	containerManager := NewFakeDockerManager(fakeClient, &record.FakeRecorder{}, nil, nil, &cadvisorApi.MachineInfo{}, PodInfraContainerImage, 0, 0, "", kubecontainer.FakeOS{}, np, nil, nil)
+	containerManager := NewFakeDockerManager(fakeClient, &record.FakeRecorder{}, nil, nil, &cadvisorApi.MachineInfo{}, PodInfraContainerImage, 0, 0, "", kubecontainer.FakeOS{}, np, nil, nil, util.NewBackOff(time.Second, 300*time.Second))
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/docker_test.go]: If 300 seconds is supposed to ensure that backoff doesn't happen in the test, could you add a comment to explicitly state that? The alternative is to add a fake backOff that does nothing.

File: pkg/kubelet/dockertools/manager_test.go [hunk 5]
```diff
@@ -1296,49 +1298,36 @@ func TestSyncPodWithPullPolicy(t *testing.T) {
 		},
 	}
 
-	runSyncPod(t, dm, fakeDocker, pod, nil)
-
-	fakeDocker.Lock()
+	expectedStatusMap := make(map[string]*api.ContainerState)
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/manager_test.go]: nit: might be simpler to do
```
expectedStatusMap := map[string]*api.ContainerState{
    "bar": &api.ContainerState{...
```

File: pkg/kubelet/dockertools/manager_test.go [hunk 6]
```diff
@@ -1296,49 +1298,36 @@ func TestSyncPodWithPullPolicy(t *testing.T) {
...
-
-	recorder := dm.recorder.(*record.FakeRecorder)
-
-	var actualEvents []string
-	for _, ev := range recorder.Events {
-		if strings.HasPrefix(ev, "Pull") {
-			actualEvents = append(actualEvents, ev)
+	for _, c := range pod.Spec.Containers {
+		if containerStatus, ok := api.GetContainerStatus(statuses.ContainerStatuses, c.Name); ok {
+			assert.Equal(t, containerStatus.State.Running, expectedStatusMap[c.Name].Running, "for container %s", c.Name)
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/manager_test.go]: nit: could you use reflect.DeepEqual to cmpare the container statuses directly?

File: pkg/kubelet/dockertools/manager_test.go [hunk 7]
```diff
@@ -1296,49 +1298,36 @@ func TestSyncPodWithPullPolicy(t *testing.T) {
...
+			assert.Equal(t, containerStatus.State.Waiting, expectedStatusMap[c.Name].Waiting, "for container %s", c.Name)
 		}
 	}
-	sort.StringSlice(actualEvents).Sort()
-	sort.StringSlice(eventSet).Sort()
-	if !reflect.DeepEqual(actualEvents, eventSet) {
-		t.Errorf("Expected: %#v, Actual: %#v", eventSet, actualEvents)
-	}
 
+	fakeDocker.Lock()
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/manager_test.go]: I think it's safe to access fakeDocker here (unrelated to your change), but locking it is fine too. Could you to `defer fakeDocker.Unlock()` Here? Thanks.

File: pkg/kubelet/dockertools/manager_test.go [hunk 8]
```diff
@@ -1296,49 +1298,36 @@ func TestSyncPodWithPullPolicy(t *testing.T) {
...
 	}
 
-	if !reflect.DeepEqual(pulledImageSet, map[string]empty{
-		"pod_infra_image":           {},
-		"pull_always_image":         {},
-		"pull_if_not_present_image": {},
-	}) {
-		t.Errorf("Unexpected pulled containers: %v", puller.ImagesPulled)
-	}
+	pulledImageSorted := puller.ImagesPulled[:]
```
Comment (yujuhong) [inline pkg/kubelet/dockertools/manager_test.go]: Hm...I don't mind the sorting here , but I think original code works too.

**Comment by samsabed** [comment]
> I think we already log the events in the log. How about only log if we cannot record an event?
> Another thing is that we should have different verbose level for the logging.

I didn't realize that events are also logged to the log file, removed duplication, nothing jumps out that would benefit from extra verbosity

> no need to return here

Done

> nit: remove the parentheses 

Done

>If 300 seconds is supposed to ensure that backoff doesn't happen in the test, could you add a >comment to explicitly state that? The alternative is to add a fake backOff that does nothing.

That's just the actual back-off for test, a fake one that does nothing may mask issues ...

> nit: might be simpler to do
"""expectedStatusMap := map[string]*api.ContainerState{
    "bar": &api.ContainerState{...
"""

Done

> nit: could you use reflect.DeepEqual to cmpare the container statuses directly?

instead of assert.Equal? assert.Equal uses DeepEqual, will unwind the Running status because the `time.Now` changes
let me know.

>I think it's safe to access fakeDocker here (unrelated to your change), but locking it is fine too. Could you to defer fakeDocker.Unlock() Here? Thanks. 

Done

> Hm...I don't mind the sorting here , but I think original code works too.

just makes it easier to add without having to shuffle the order of the test ( I think that's why )

Will also need to rebase

**Comment by yujuhong** [comment]
> just makes it easier to add without having to shuffle the order of the test ( I think that's why )

DeepEqual would compare the map content correctly, regardless the order, so sorting is not necessary.


> instead of assert.Equal? assert.Equal uses DeepEqual, will unwind the Running status because the time.Now changes
> let me know.

What I meant was that it'd be better to compare `containerStatus.State` directly, without having to compare both `containerStatus.State.Running` and `containerStatus.State.Waiting`.


> That's just the actual back-off for test, a fake one that does nothing may mask issues ...

An arbitrary number may cause the test to be flaky at times. If you're not going to test the backoff mechanism in this file, it'd be better to have a fake backoff component that always returns that the test is not in backoff.



> nothing jumps out that would benefit from extra verbosity

Verbosity is important since kubelet generates a lot of logs. At least user would have the control of setting -v=2 or some low number. Given that now you only log when there is no ref, I'm okay with not having verbosity level.

**Comment by samsabed** [comment]
> DeepEqual would compare the map content correctly, regardless the order, so sorting is not necessary.

Its a slice ... 
```
Error Trace:    manager_test.go:1335
	Error:		Not equal: []string{"pod_infra_image", "pull_always_image", "pull_if_not_present_image"} (expected)
			        != []string{"pod_infra_image", "pull_if_not_present_image", "pull_always_image"} (actual)
```
> What I meant was that it'd be better to compare containerStatus.State directly, without having to compare both containerStatus.State.Running and containerStatus.State.Waiting

Done

>An arbitrary number may cause the test to be flaky at times. If you're not going to test the backoff >mechanism in this file, it'd be better to have a fake backoff component that always returns that the >test is not in backoff

They are the "real" numbers, just can't get to the const/variables from the _test.go file
backoff is a type, can I get a tip as to how a fake would look like, I changed it to `&util.Backoff{}` don't think it's ideal

**Comment by yujuhong** [comment]
> Its a slice ...

The original code converted it into a map `pulledImageSet := make(map[string]empty)`. I guess sorting is fine too. 

> They are the "real" numbers, just can't get to the const/variables from the _test.go file
> backoff is a type, can I get a tip as to how a fake would look like, I changed it to &util.Backoff{} don't think it's ideal

Sorry I mean to make it an interface instead, so that you can replace it with a fake implementation for testability.
I don't quite get the real number argument. If the test could pass/fail based on the value you set in the backoff, it'd be better to supply a comment pointing out why that's the case. If the number would not affect the test result at all, then it's also worth documenting why choosing "300 second". 
I think an interface is preferred, but a comment is okay too.

**Comment by samsabed** [comment]
>Sorry I mean to make it an interface instead, so that you can replace it with a fake implementation for testability.
I don't quite get the real number argument. If the test could pass/fail based on the value you set in the backoff, it'd be better to supply a comment pointing out why that's the case. If the number would not affect the test result at all, then it's also worth documenting why choosing "300 second".
I think an interface is preferred, but a comment is okay too.

That test doesn't pull an image, I've added a comment, I don't mind changing it to a interface in an isolated PR, a bit weary of having this take longer to sort out

after rebasing, the pods now have a startedAt time, so I needed to copy the time to be able to test the whole state 
```
if containerStatus.State.Running != nil {
        expectedStatusMap[c.Name].Running.StartedAt = containerStatus.State.Running.StartedAt
      }
      assert.Equal(t, containerStatus.State, expectedStatusMap[c.Name], "for container %s", c.Name)
```

I have a PR to refactor GetPodStatus, will submit after this one is (hopefully) merged

**Comment by yujuhong** [comment]
@samabed, PR needs to be rebased.

**Comment by samsabed** [comment]
@yujuhong , I've rebased it.

**Comment by yujuhong** [comment]
> I have a PR to refactor GetPodStatus, will submit after this one is (hopefully) merged

Please cc me on this PR if you ever upload it. Thanks! :)

**Comment by samsabed** [comment]
@yujuhong Thanks for the review

**Comment by a-robinson** [comment]
Needs a rebase before it can be merged, unfortunately

**Comment by samsabed** [comment]
@yujuhong please re-bless

**Comment by yujuhong** [comment]
> @yujuhong please re-bless

It has the lgtm label already :\

**Comment by samsabed** [comment]
@yujuhong 

>> I have a PR to refactor GetPodStatus, will submit after this one is (hopefully) merged
> Please cc me on this PR if you ever upload it. Thanks! :)

while it's ready, #15089 will mean some churn in the function, so probably better to not do it wdyt

**Comment by yujuhong** [comment]
@samabed, indeed, #15089 will involve rewriting a huge portion of the GetPodStatus function. I agree we should hold off on the refactoring to avoid the churns. Thank you for understanding :)
