### PR TITLE
Retry when it fails to update pods status on scheduling loop

### LINKED ISSUE #109796: Unschedulable Pod might take a long time to get the condition set
### What happened?

If there is a connection failure when updating the Pod status, we don't retry.
Furthermore, due to #108761, we won't have another chance until much later.

The problem is that if we don't mark the Pod as Unschedulable, other controllers (such as cluster-autoscaler) wouldn't react to these pods.

### What did you expect to happen?

We should have stronger guarantees to mark a Pod as Unschedulable.

### How can we reproduce it (as minimally and precisely as possible)?

You need an unschedulable Pod (for example, a Pod with a non matching node affinity) and a flaky connection to apiserver.

### Anything else we need to know?

_No response_

### Kubernetes version

master

This is particularly problematic in 1.24, due to #108761.

### Cloud provider

Any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Retry with exponential backoff when it fails to update pods status on scheduling loop.

---

Scheduler doesn't retry when updating pods status on scheduling loop. If it fails to update pod states to unschedulable by some reasons (e.g., a flaky connection to apiserver), the next time it has a chance to be updated to unschedulable status is when it is scheduled again.
This means that in the worst case, that Pod status may not be updated for 5 minutes. (ref https://github.com/kubernetes/kubernetes/pull/108761)

#### Which issue(s) this PR fixes:

Fixes #109796

#### Special notes for your reviewer:

It's difficult for me to determine which errors are retriable. I used EventBroadcaster as a reference to implement.
https://github.com/kubernetes/kubernetes/blob/d582814d5e7fd7806d171e47083d3d1cbc76ab0f/staging/src/k8s.io/client-go/tools/record/event.go#L258

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/util/utils.go [hunk 1]
```diff
@@ -115,13 +126,58 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+	}
+
+	patchFn := func() (bool, error) {
+		_, err = cs.CoreV1().Pods(old.Namespace).Patch(context.Background(), old.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
+		if err == nil {
+			return true, nil
+		}
+
+		switch typedErr := err.(type) {
+		case *rest.RequestConstructionError:
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils.go:143]: why are you handling this case specifically, do you expect it to be reached?

File: pkg/scheduler/util/utils.go [hunk 2]
```diff
@@ -115,13 +126,58 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+			var retryAfterSeconds int32
+			if typedErr.Status().Details != nil {
+				retryAfterSeconds = typedErr.Status().Details.RetryAfterSeconds
+			}
+			if retryAfterSeconds == 0 {
+				// we shouldn't retry in this case.
+				return false, fmt.Errorf("server rejected patching Pod Status: %w", err)
+			}
+			// Otherwise we can retry after retryAfterSeconds.
+			klog.ErrorS(err, "server reject patching a Pod (may retry after sleeping)", "pod name", old.Name)
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils.go:156]:
```suggestion
			klog.ErrorS(err, "Server rejected Pod patch (may retry after sleeping)", "pod", klog.KObj(old))
```

File: pkg/scheduler/util/utils.go [hunk 3]
```diff
@@ -115,13 +126,58 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+		Steps:    retryBackoffSteps,
+	}
+
+	patchFn := func() (bool, error) {
+		_, err = cs.CoreV1().Pods(old.Namespace).Patch(context.Background(), old.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
+		if err == nil {
+			return true, nil
+		}
+
+		switch typedErr := err.(type) {
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils.go:142]: should we have this validation in a function? And then you can use `client-go/util/retry.OnError`.

File: pkg/scheduler/util/utils.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:143]: I have not actually considered the specific case, will remove it.

File: pkg/scheduler/util/utils.go (hunk 3 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:142]: Sure. 👍

**Comment by sanposhiho** [comment]
@alculquicondor 
Thanks for the review. Address your comments and simplify the retry logic.
Please take a look at this again.

File: pkg/scheduler/util/utils_test.go [hunk 4]
```diff
@@ -178,12 +181,17 @@ func TestRemoveNominatedNodeName(t *testing.T) {
...
 func TestPatchPodStatus(t *testing.T) {
 	tests := []struct {
-		name           string
-		pod            v1.Pod
+		name   string
+		pod    v1.Pod
+		client *clientsetfake.Clientset
+		// valifyErrorFn checks if error returned from PatchPodStatus is expected one or not.
+		// (true means error is expected one.)
+		valifyErrorFn  func(goterr error) bool
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:189]: validateErr

File: pkg/scheduler/util/utils_test.go [hunk 5]
```diff
@@ -226,20 +235,149 @@ func TestPatchPodStatus(t *testing.T) {
...
 
 			err = PatchPodStatus(client, &tc.pod, &tc.statusToUpdate)
-			if err != nil {
+			if err != nil && tc.valifyErrorFn == nil {
+				// shouldn't be error
 				t.Fatal(err)
 			}
+			if tc.valifyErrorFn != nil {
+				if !tc.valifyErrorFn(err) {
+					t.Fatalf("returned error is not an expected one: got %v", err)
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:377]:
```suggestion
					t.Fatalf("Returned unexpected error: %v", err)
```

File: pkg/scheduler/util/utils.go [hunk 6]
```diff
@@ -90,8 +93,16 @@ func MoreImportantPod(pod1, pod2 *v1.Pod) bool {
 	return GetPodStartTime(pod1).Before(GetPodStartTime(pod2))
 }
 
+const (
+	// Parameters for retrying with exponential backoff.
+	retryBackoffInitialDuration = 100 * time.Millisecond
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils.go:98]: Actually, let's make this smaller. You are already sleeping the time that the server is telling you to retry.

0.1 seconds is way too much time considering that the scheduler is able to schedule ~300 pods/s if the apiserver is healthy.

maybe the factor can be 1.3

File: pkg/scheduler/util/utils.go [hunk 7]
```diff
@@ -115,13 +126,41 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+	patchFn := func() error {
+		_, err := cs.CoreV1().Pods(old.Namespace).Patch(context.Background(), old.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
+		return err
+	}
+
+	isRetriableFn := func(err error) bool {
+		if typedErr, ok := err.(*errors.StatusError); ok {
+			var retryAfterSeconds int32
+			if typedErr.Status().Details != nil {
+				retryAfterSeconds = typedErr.Status().Details.RetryAfterSeconds
```
Comment (ahg-g) [inline pkg/scheduler/util/utils.go:145]: if the api-server is unreachable, who sets this value? the client?

File: pkg/scheduler/util/utils.go [hunk 8]
```diff
@@ -115,13 +126,41 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+		Steps:    retryBackoffSteps,
+	}
+
+	patchFn := func() error {
+		_, err := cs.CoreV1().Pods(old.Namespace).Patch(context.Background(), old.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{}, "status")
+		return err
+	}
+
+	isRetriableFn := func(err error) bool {
+		if typedErr, ok := err.(*errors.StatusError); ok {
```
Comment (ahg-g) [inline pkg/scheduler/util/utils.go:142]: can you add a comment documenting what this means? when do we get a StatusError error type?

File: pkg/scheduler/util/utils.go (hunk 6 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:98]: How about updating status in goroutine instead of making backoff time smaller?
i.e. put the following line into `go func(){...}()`
https://github.com/kubernetes/kubernetes/blob/5e9a6a256e9ed7834dfcf5f4a30be015130df6e9/pkg/scheduler/schedule_one.go#L826-L833

Because if there is a connection failure, the responded error doesn't contain `RetryAfterSeconds` (since the type is not `*errors.StatusError`.) and if backoff time is small in that case, the retry may be less likely to be successful)

File: pkg/scheduler/util/utils.go (hunk 7 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:145]: If the api-server is unreachable, the error type will not be `*errors.StatusError`.
So, scheduler will wait for a backoff time and retry again.

File: pkg/scheduler/util/utils.go (hunk 6 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:98]: > 0.1 seconds is way too much time considering that the scheduler is able to schedule ~300 pods/s if the apiserver is healthy.

Make sense. change it to `10*time.Millisecond`.

File: pkg/scheduler/util/utils.go (hunk 8 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:142]: Sure. added some comments.

File: pkg/scheduler/util/utils_test.go [hunk 9]
```diff
@@ -226,20 +235,149 @@ func TestPatchPodStatus(t *testing.T) {
...
+					}
+
+					// return error if requests comes in more than three times.
+					return true, nil, errors.New("requests comes in more than three times.")
+				})
+
+				return client
+			}(),
+			pod: v1.Pod{
+				ObjectMeta: metav1.ObjectMeta{
```
[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/util/utils_test.go:262]: we cannot use testing package here since testing package is using `pkg/scheduler/util` package.

**Comment by sanposhiho** [comment]
(By https://github.com/kubernetes/kubernetes/issues/109848 https://github.com/kubernetes/kubernetes/issues/109847)

File: pkg/scheduler/util/utils_test.go [hunk 10]
```diff
@@ -226,20 +235,149 @@ func TestPatchPodStatus(t *testing.T) {
...
+					Namespace: "ns",
+					Name:      "pod1",
+				},
+				Spec: v1.PodSpec{
+					ImagePullSecrets: []v1.LocalObjectReference{{Name: "foo"}},
+				},
+			},
+			validateErr: func(goterr error) bool {
+				return apierrors.IsBadRequest(goterr)
+			},
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:309]:
```suggestion
			validateErr: apierrors.IsBadRequest,
```

File: pkg/scheduler/util/utils.go (hunk 6 above)
Comment (alculquicondor) [reply pkg/scheduler/util/utils.go]: Did you remove the comment about calling this in a routine? I think that's a good idea. But do it in the caller (the scheduler package, in this case).

Comment (sanposhiho) [reply pkg/scheduler/util/utils.go]: Ah, yeah, I removed my previous comments because if we do so and the parallel status update is done after starting another scheduling cycle, I guess the pod will be moved from unschedulableQ to activeQ by event handler? 
wdyt?

Comment (sanposhiho) [reply pkg/scheduler/util/utils.go]: Okay, It seems my concern was wrong. Any status updates are ignored and the pod won’t be moved in that case. 
https://github.com/kubernetes/kubernetes/blob/7e77252b0d5fcd3689f2f7e4a21757e53965c092/pkg/scheduler/internal/queue/scheduling_queue.go#L524

will change the scheduler pkg's implementation to update pods status in goroutine

Comment (sanposhiho) [reply pkg/scheduler/util/utils.go]: Should I also revert the retryBackoffInitialDuration to 0.1 seconds?

Comment (alculquicondor) [reply pkg/scheduler/util/utils.go]: yeah, 100ms sounds good.

**Comment by sanposhiho** [comment]
@alculquicondor @ahg-g 
Could you please retake a look at this?

- change retryBackoffInitialDuration to 0.1 seconds.
- run `updatePod` in routine. (pkg/scheduler/schedule_one.go)
- apply [the suggestion](https://github.com/kubernetes/kubernetes/pull/109832#discussion_r866863950) on pkg/scheduler/util/utils_test.go

File: pkg/scheduler/schedule_one.go [hunk 11]
```diff
@@ -823,14 +823,17 @@ func (sched *Scheduler) handleSchedulingFailure(fwk framework.Framework, podInfo
...
-	if err := updatePod(sched.client, pod, &v1.PodCondition{
-		Type:    v1.PodScheduled,
-		Status:  v1.ConditionFalse,
-		Reason:  reason,
-		Message: err.Error(),
-	}, nominatingInfo); err != nil {
-		klog.ErrorS(err, "Error updating pod", "pod", klog.KObj(pod))
-	}
+	go func() {
+		// update Pod's status in goroutine since the updating may take a time by retries.
```
Comment (alculquicondor) [inline pkg/scheduler/schedule_one.go:827]:
```suggestion
		// update Pod's status in goroutine because there might be retries.
```

Comment (alculquicondor) [reply pkg/scheduler/schedule_one.go:827]: But let's do this just for calling `util.PatchPodStatus`

File: pkg/scheduler/util/utils.go [hunk 12]
```diff
@@ -115,13 +126,48 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+		if typedErr.Status().Details != nil {
+			retryAfterSeconds = typedErr.Status().Details.RetryAfterSeconds
+		}
+		if retryAfterSeconds == 0 {
+			// we shouldn't retry since this means kube-apiserver rejected our request and didn't ask us to retry.
+			return false
+		}
+		// Otherwise we can retry after retryAfterSeconds.
+		klog.ErrorS(err, "Server rejected Pod patch (may retry after sleeping)", "pod", klog.KObj(old))
+		time.Sleep(time.Duration(retryAfterSeconds))
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils.go:161]: you could actually use the `backoff.Duration` to find the diff. The field is updated every time.

Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:161]: > you could actually use the backoff.Duration to find the diff. The field is updated every time.

I guessed so too, but it doesn't seem to be updated every time since `wait.ExponentialBackoff` and `` receives non-pointer `wait.Backoff` not pointer `*wait.Backoff`...

https://github.com/kubernetes/kubernetes/blob/e84f62e6955b5d45f15cc670e314523f97bb976e/staging/src/k8s.io/client-go/util/retry/util.go#L48
https://github.com/kubernetes/kubernetes/blob/e84f62e6955b5d45f15cc670e314523f97bb976e/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go#L419

File: pkg/scheduler/schedule_one.go (hunk 11 above)
Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go]: Sure. Updated.

File: pkg/scheduler/util/utils.go (hunk 12 above)
Comment (alculquicondor) [reply pkg/scheduler/util/utils.go:161]: oh I missed that :(

Do you have any idea how long usually `retryAfterSeconds` is?

File: pkg/scheduler/schedule_one.go [hunk 13]
```diff
@@ -843,17 +841,22 @@ func truncateMessage(message string) string {
...
+		return
 	}
 	if nnnNeedsUpdate {
 		podStatusCopy.NominatedNodeName = nominatingInfo.NominatedNodeName
 	}
-	return util.PatchPodStatus(client, pod, podStatusCopy)
+	go func() {
+		// update Pod's status in goroutine because there might be retries.
+		if err := util.PatchPodStatus(client, pod, podStatusCopy); err != nil {
+			klog.ErrorS(err, "Error updating pod", "pod", klog.KObj(pod))
```
Comment (alculquicondor) [inline pkg/scheduler/schedule_one.go:859]:
```suggestion
			klog.ErrorS(err, "Could not update pod status", "pod", klog.KObj(pod))
```

Comment (alculquicondor) [reply pkg/scheduler/schedule_one.go:859]: or maybe we could even say: "after scheduling attempt"? Are there other calls to `updatePod` that are not related to the scheduling attempt?

Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:859]: > Are there other calls to updatePod that are not related to the scheduling attempt?

Seems no. So adding "after scheduling attempt" also looks good. 👍

File: pkg/scheduler/util/utils.go (hunk 12 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:161]: > Do you have any idea how long usually retryAfterSeconds is?

It depends on the type of error:

```
GanerateNameConflict→1s
TooManyRequests→10s
ServerTimeout→2s
Timeout→10s
```

(investigated by searching the usage of `NewXXXXX` in [k8s.io/apimachinery/pkg/api/errors/errors.go](https://github.com/kubernetes/kubernetes/blob/fbdd0d7b4165bc5a677d45e4dc693e3260297bfa/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go).)

Comment (alculquicondor) [reply pkg/scheduler/util/utils.go:161]: Ah, that's great!

I'm happy with the backoffs you have set.

/lgtm
/approve
/hold
@ahg-g anything to add?

**Comment by alculquicondor** [comment]
There's a valid govet error

**Comment by sanposhiho** [comment]
@alculquicondor @ahg-g 

Updated. Please retake a look 🙏 

- Fix scheduler_one_test.go (address go vet error)
- Add a test case "only 6 retries at most" in TestPatchPodStatus
- Change error log message. (https://github.com/kubernetes/kubernetes/pull/109832#discussion_r866959544)

**Comment by alculquicondor** [comment]
Failures look legit.

**Comment by sanposhiho** [comment]
@alculquicondor @ahg-g 
Fixed the unit test `TestUpdatePod`. 🙇

**Comment by sanposhiho** [comment]
/retest

(https://github.com/kubernetes/kubernetes/issues/107414)

**Comment by sanposhiho** [comment]
Flaky test: https://github.com/kubernetes/kubernetes/issues/109783
Rebase this PR to include the change https://github.com/kubernetes/kubernetes/pull/109834.

**Comment by sanposhiho** [comment]
Next flaky test... 
https://github.com/kubernetes/kubernetes/issues/109889

**Comment by sanposhiho** [comment]
/retest

Flaky: https://github.com/kubernetes/kubernetes/issues/109890

File: pkg/scheduler/util/utils.go (hunk 12 above)
Comment (Huang-Wei) [reply pkg/scheduler/util/utils.go:161]: If we can figure the exact failure reasons, I'd propose to restrict the retry logic to those particular error(s), like the "connection refused" one:

https://github.com/kubernetes/kubernetes/blob/93047824f7dec417bb90d89080b4550fe8b771df/staging/src/k8s.io/apimachinery/pkg/util/net/util.go#L50 can direcetly pin the error.

File: pkg/scheduler/util/utils.go [hunk 14]
```diff
@@ -115,13 +126,48 @@ func PatchPodStatus(cs kubernetes.Interface, old *v1.Pod, newStatus *v1.PodStatu
...
+		return true
+	}
+
+	return retry.OnError(backoff, isRetriableFn, patchFn)
 }
 
 // DeletePod deletes the given <pod> from API server
 func DeletePod(cs kubernetes.Interface, pod *v1.Pod) error {
-	return cs.CoreV1().Pods(pod.Namespace).Delete(context.TODO(), pod.Name, metav1.DeleteOptions{})
+	return cs.CoreV1().Pods(pod.Namespace).Delete(context.Background(), pod.Name, metav1.DeleteOptions{})
```
Comment (Huang-Wei) [inline pkg/scheduler/util/utils.go:170]: this makes no difference. (in theory, we should pass in a context)

File: pkg/scheduler/schedule_one.go [hunk 15]
```diff
@@ -843,17 +841,22 @@ func truncateMessage(message string) string {
...
 	nnnNeedsUpdate := nominatingInfo.Mode() == framework.ModeOverride && pod.Status.NominatedNodeName != nominatingInfo.NominatedNodeName
 	if !podutil.UpdatePodCondition(podStatusCopy, condition) && !nnnNeedsUpdate {
-		return nil
+		return
 	}
 	if nnnNeedsUpdate {
 		podStatusCopy.NominatedNodeName = nominatingInfo.NominatedNodeName
 	}
-	return util.PatchPodStatus(client, pod, podStatusCopy)
+	go func() {
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/schedule_one.go:856]: We are using go-client's `retry.OnError` which uses a `wait.ConditionFunc` underneath.

> or when it was successful and you should not retry?

see the update in `pkg/scheduler/utils`

> or if you leak goroutines and create a new one despite the previous didn't finish?

We only retry 6 times (but probably will change to 4), is it that a big concern?

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/schedule_one.go:856]: > Can you elaborate?

When it comes to goroutines, it increases uncertainty. For the changes introduced here, I don't see a significant benefit that can outweigh the uncertainty.

If we agree it's a transient error, retry in a blocking manner makes more sense to me. While if the error is consistent, retry in goroutines would increase the burden to APIServer.

[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/schedule_one.go:856]: if the errors we expect here are mostly api-server connectivity ones, then a blocking call is likely sufficient; the scheduler will not be able to make too much progress with the api-server down anyways.

File: pkg/scheduler/util/utils.go (hunk 12 above)
Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:161]: > I'm curious about the exact failure reasons,

> If we can figure the exact failure reasons, I'd propose to restrict the retry logic to those particular error(s), like the "connection refused" one

At least the error we have seen is "connection refused".
https://github.com/kubernetes/kubernetes/issues/109783#issuecomment-1117670945

But, when api-server is very busy and could return `ServerTimeout` or `TooManyRequests` errors, we'll face the same issue as https://github.com/kubernetes/kubernetes/issues/109796.
So, I think it's better to retry not only for connection refused error, but also for errors which contains `retryAfterSeconds`.

Comment (sanposhiho) [reply pkg/scheduler/util/utils.go:161]: But, the current implementation retries for all unknown errors(= all errors which type is not `*errors.StatusError`), so it would make sense to change it to retry only for `connection refused` if the error is not `*errors.StatusError`.

File: pkg/scheduler/schedule_one.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:856]: Okay, understood. If a new request to update a Pod (like bind request or another patch request from the next scheduling cycle) is sent from the scheduler (and the Pod is updated successfully) at a stage where the past one has not been completed by retries, the new Pod state, which is updated by the new request, may be overwritten by the past request. That's a problem..

> If we agree it's a transient error, retry in a blocking manner makes more sense. While if the error is consistent, retry in goroutines would increase the burden to APIServer.

> the scheduler will not be able to make too much progress with the api-server not reachable anyways.

These make sense. When api-server is unreachable from a scheduler, other requests are likely to fail as well, making it difficult for the scheduler to continue scheduling successfully. And putting more load on api-server by many requests from these goroutines is no solution.

I'll try to update the PR to change here to retry with a blocking.

[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:856]: Oh, I didn't know that...  
> client-go implements some retry logic for requests it considers retryable, generally:
> - no write requests (PUT,POST) , a GET is retryable
> - transient network errors: connection reset by peer or EOF
> - retryable http errors: 50x code with a Retry-After header

So, we need to retry for "connection refused" by ourselves, but client-go do retries for 10s for errors that contain `Retry-After` like [`ServerTimeout`](https://github.com/kubernetes/kubernetes/blob/fbdd0d7b4165bc5a677d45e4dc693e3260297bfa/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L363) 
[The current implementation](https://github.com/kubernetes/kubernetes/pull/109832/files#diff-6984d9ecf223c8282a6c2cde85aaea2cc72f6c3365881edca0d9f928ea0d7997R151-R162) does retry in addition to client-go does. Can we remove the retry in this case? What do you all think?

[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/schedule_one.go:856]: Do we have to do anything to benefit from the builtin retries?

Is it the case that "connection refused" is not included?

[the remark this answers is not in the document]
Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:856]: > Do we have to do anything to benefit from the builtin retries?

No. (right? @aojea)

> Is it the case that "connection refused" is not included in the retriable errors?

I guess this is also No because "connection refused" is not returned from api-server, and it isn't expected to have `Retry-After` header.

**Comment by sanposhiho** [comment]
@Huang-Wei @alculquicondor @aojea 

Sorry for leaving here for a while.
Given the discussion, I changed the implementation to retry only for "connection refused" error.
Please retake a look 🙏

**Comment by alculquicondor** [comment]
can you fix the verify?

**Comment by sanposhiho** [comment]
@alculquicondor 
> can you fix the verify?

Thanks for pinging me. (I wasn't aware of it. 🙏 🙏 🙏 )
Fixed.

File: pkg/scheduler/util/utils_test.go [hunk 16]
```diff
@@ -226,20 +236,106 @@ func TestPatchPodStatus(t *testing.T) {
...
+		{
+			name: "only 4 retries at most",
+			client: func() *clientsetfake.Clientset {
+				client := clientsetfake.NewSimpleClientset()
+
+				reqcount := 0
+				client.PrependReactor("patch", "pods", func(action clienttesting.Action) (bool, runtime.Object, error) {
+					defer func() { reqcount++ }()
+					if reqcount >= 4 {
+						// return error if requests comes in more than six times.
```
Comment (alculquicondor) [inline pkg/scheduler/util/utils_test.go:289]: four?

But why change the error? It should stop retrying even if the error is the same.

Comment (sanposhiho) [reply pkg/scheduler/util/utils_test.go]: Thanks. Fixed typo. 🙏 

---

> But why change the error? It should stop retrying even if the error is the same.

This "requests comes in more than four times." error shouldn't be returned in the expected scenario.

The expected scenario is:
1. PatchPodStatus func sends a patch request to fake client.
2. fake client returns "connection refused" error
3. PatchPodStatus func retry (1) three times and fake client returns "connection refused" errors for these three requests.
4. PatchPodStatus func gives up retrying and returns "connection refused" error. (the test will check if the returned error is "connection refused" or not.)

`PrependReactor` returns "connection refused" error only four times and if there is a bug like "the system retries forever", the "requests comes in more than four times." error will be returned and this test case will fail. (because the test will check if the returned error is "connection refused" or not.)

**Comment by sanposhiho** [comment]
Fixed bad rebase.

**Comment by sanposhiho** [comment]
@alculquicondor Could you check this when have a chance 🙏

**Comment by alculquicondor** [comment]
/lgtm

Thanks
