### PR TITLE
Stop probing a pod during graceful shutdown

### LINKED ISSUE #52817: liveness/readiness probe is executed and failed while pod is terminated
**What happened**:
liveness/readiness probe fails while pod is terminated. Also it happened only once during the pod termination. The issue started happening after upgrading version  to v1.7 from v1.6.X 

**How to reproduce it (as minimally and precisely as possible)**:
execute `kubectl delete pod nginx-A1` to delete pod, so status of the nginx-podA1 is changed to `Terminating`, right after that it seems Liveness and Readiness Probe is executed and failed, but only once.
Nginx reverse proxy is running in the pod. so I just use `httpGet`method for liveness and readiness

Here is my Deployment config.
``` yaml
   ...
   spec:
      terminationGracePeriodSeconds: 60
        ...
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
```

Here is Events log by `kubectl describe pod nginx-A1`
```
Events:
  FirstSeen	LastSeen	Count	From					SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----					-------------			--------	------		-------
  14s		14s		1	kubelet, *****	spec.containers{dnsmasq}	Normal		Killing		Killing container with id docker://dnsmasq:Need to kill Pod
  9s		9s		1	kubelet, *****	spec.containers{nginx}		Warning		Unhealthy	Liveness probe failed: Get http://100.*.*.*:8080/healthz: dial tcp 100.*.*.*:8080: getsockopt: connection refused
  9s		9s		1	kubelet, *****	spec.containers{nginx}		Warning		Unhealthy	Readiness probe failed: Get http://100.*.*.*:8080/healthz: dial tcp 100.*.*.*:8080: getsockopt: connection refused

```

**Environment**:
- Kubernetes version: 1.7.2

### PR DESCRIPTION
**Pull request by matthyx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If a pod takes longer to delete than it's its health/readiness probe allow a user can get errors that the pods check is erroring even though the pod is being deleted. This can update the pods status field to be inaccurate.

**Which issue(s) this PR fixes**:

Fixes #52817

**Special notes for your reviewer**:
This PR reopens the work initiated by @ashleyschuett in https://github.com/kubernetes/kubernetes/pull/92385 which was abandoned partly because of my comments there. We still need to fix this situation.

I propose basically the same approach which is altering kubelet's worker working when `DeletionTimestamp` is set (indicating graceful shutdown initiated) to allow a quiet shutdown by setting safe probe results (depending on the type) before disabling probing.

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/prober/worker.go [hunk 1]
```diff
@@ -222,6 +222,22 @@ func (w *worker) doProbe() (keepGoing bool) {
 			w.pod.Spec.RestartPolicy != v1.RestartPolicyNever
 	}
 
+	// Graceful shutdown of the pod.
+	if w.pod.ObjectMeta.DeletionTimestamp != nil {
```
Comment (ehashman) [inline pkg/kubelet/prober/worker.go:226]: We don't need to do any container checking after we see the pod deletion timestamp is set so, in this case, should we not run this logic before we do any container checking? (i.e. move this addition above L191)

File: pkg/kubelet/prober/worker.go [hunk 2]
```diff
@@ -222,6 +222,22 @@ func (w *worker) doProbe() (keepGoing bool) {
...
+		case liveness, startup:
+			// Don't kill the container, it is already terminating.
+			w.resultsManager.Set(w.containerID, results.Success, w.pod)
+		case readiness:
+			// Stop sending traffic.
+			w.resultsManager.Set(w.containerID, results.Failure, w.pod)
+		}
+		// Stop probing at this point.
+		w.onHold = true
+		return false
```
Comment (ehashman) [inline pkg/kubelet/prober/worker.go:238]: I don't know if we actually need to set `onHold`. It's only used here: https://github.com/kubernetes/kubernetes/blob/64a6ee4321d37740b84a5c5c7aaa67e0bf6b6508/pkg/kubelet/prober/worker.go#L209

But we're returning `false` so the worker for this probe will never run again anyways.

File: pkg/kubelet/prober/worker.go (hunk 1 above)
Comment (matthyx) [reply pkg/kubelet/prober/worker.go:226]: well I need to have a valid `w.containerID` to set the probe results, don't I?

File: pkg/kubelet/prober/worker.go (hunk 2 above)
Comment (matthyx) [reply pkg/kubelet/prober/worker.go:238]: True, I forgot the container won't probably restart if we asked for the pod to be deleted... removing it.

File: pkg/kubelet/prober/worker.go (hunk 1 above)
Comment (ehashman) [reply pkg/kubelet/prober/worker.go:226]: Ahh yes sure. so maybe before the `onHold` check?

Comment (ehashman) [reply pkg/kubelet/prober/worker.go:226]: (I guess it doesn't really matter as much, this is nonblocking)

**Review by ehashman — COMMENTED** [review]
/lgtm

File: pkg/kubelet/prober/worker.go (hunk 1 above)
Comment (matthyx) [reply pkg/kubelet/prober/worker.go:226]: Yeah, in fact we probably have more often `c.State.Running == nil` than `w.pod.ObjectMeta.DeletionTimestamp != nil`.

**Comment by SergeyKanzhelev** [comment]
> I propose basically the same approach which is altering kubelet's worker working when `DeletionTimestamp` is set (indicating graceful shutdown initiated) to allow a quiet shutdown by setting safe probe results (depending on the type) before disabling probing.

My question stays the same as for the initial PR. What is the safe defaults for the probes that work universally? Would one want to mark readiness probe as `Failure` for the duration of a termination if the termination is not suppose to accept any new requests? Or keep it as `Success` if pod is critical and the extended termination prestop hooks is used to delay the termination so other pods will shut down first.

**Comment by matthyx** [comment]
> What is the safe defaults for the probes that work universally?

Yeah, probably it is safer to let the application owner decide what to do with the `readiness` aspect.
I'm gonna override only `liveness` and `startup` then...

File: pkg/kubelet/prober/worker.go [hunk 3]
```diff
@@ -222,6 +222,14 @@ func (w *worker) doProbe() (keepGoing bool) {
 			w.pod.Spec.RestartPolicy != v1.RestartPolicyNever
 	}
 
+	// Graceful shutdown of the pod.
+	if w.pod.ObjectMeta.DeletionTimestamp != nil && w.probeType == liveness {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:226]: should the same logic apply for startup probe? If termination started on a pod that has not started yet, we better stop making startup probes

File: pkg/kubelet/prober/worker.go [hunk 4]
```diff
@@ -230,7 +238,7 @@ func (w *worker) doProbe() (keepGoing bool) {
 	if c.Started != nil && *c.Started {
 		// Stop probing for startup once container has started.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:239]: was this comment incorrect before?

File: pkg/kubelet/prober/worker.go [hunk 5]
```diff
@@ -230,7 +238,7 @@ func (w *worker) doProbe() (keepGoing bool) {
...
 		if w.probeType == startup {
-			return true
+			return false
 		}
 	} else {
 		// Disable other probes until container has started.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:244]: is this comment correct?

File: pkg/kubelet/prober/worker.go (hunk 4 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/worker.go:239]: I am confused as comment hasn't changed while return value is opposite to what it was before =)

File: pkg/kubelet/prober/worker.go (hunk 3 above)
Comment (andrewsykim) [reply pkg/kubelet/prober/worker.go:226]: I'm not sure we want to add a special condition for liveness probes + terminating pods. If readiness probes still apply for terminating pods (and they should), I would expect the same to be true for all other probe types.

Comment (matthyx) [reply pkg/kubelet/prober/worker.go:226]: > should the same logic apply for startup probe?

I thought too, but now I don't quite see this happening quite often... having a pod that needs cleaning up and graceful shutdown before having started? If you prefer I can put it back.

Comment (matthyx) [reply pkg/kubelet/prober/worker.go:226]: > I think the issue with liveness probes is the confusion - see the referenced bug description. Pod deletion was requested and it was marked as unhealthy because the code that suppose to check liveness has stopped. And it's not easy to create a liveness probe that will not fail (at least sometimes) on pod termination. Since pod is already being stopped, liveness detection may only change the status of a pod, but will not change anything else in termination logic.
> 
> I think readiness is different as it controls the Load Balancer for the pod. If it will start failing because the code was unloaded, nothing confusing will happen from the customer perspective.

100% agree

File: pkg/kubelet/prober/worker.go (hunk 4 above)
Comment (matthyx) [reply pkg/kubelet/prober/worker.go:239]: Yes, I cannot believe I let it through 4 or 5 releases...
Of course it's harmless to let the worker continue, but we should be lean and avoid wasting resources.

File: pkg/kubelet/prober/worker.go (hunk 5 above)
Comment (matthyx) [reply pkg/kubelet/prober/worker.go:244]: Yes, we skip the probing part, but still leave the worker running.

File: pkg/kubelet/prober/worker.go (hunk 3 above)
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:226]: I'd suggest to stop startup probing on termination. Yes, it may be very rare occurrence, when startup takes so long that operator decided to terminate the pod. But if the same confusion - marking pod failed will occur in this case, it will be unlikely.

File: pkg/kubelet/prober/worker.go [hunk 6]
```diff
@@ -222,6 +222,14 @@ func (w *worker) doProbe() (keepGoing bool) {
 			w.pod.Spec.RestartPolicy != v1.RestartPolicyNever
 	}
 
+	// Graceful shutdown of the pod.
+	if w.pod.ObjectMeta.DeletionTimestamp != nil && w.probeType == liveness {
+		// Set a last result to ensure quiet shutdown.
+		w.resultsManager.Set(w.containerID, results.Success, w.pod)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:228]: can you please add log message here for easier troubleshooting

File: pkg/kubelet/prober/worker.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/worker.go:226]: In that case (terminated during the startup), I would suggest to output a warning log message, not verbose. As this is quite unusual situation to get into.

Comment (ehashman) [reply pkg/kubelet/prober/worker.go:226]: I see startup probes as a special case of liveness probe, and think they should generally be coupled. This is less likely to happen for a startup probe (how often do you delete a pod before it even starts properly?) but still could, because they use the same code path for container termination. So #52817 and #64715 affect both.

**Comment by matthyx** [comment]
@annajung could you please flag this as 1.21?

**Comment by annajung** [comment]
/milestone v1.21
cc @erismaster

File: pkg/kubelet/prober/worker.go [hunk 7]
```diff
@@ -222,6 +222,20 @@ func (w *worker) doProbe() (keepGoing bool) {
 			w.pod.Spec.RestartPolicy != v1.RestartPolicyNever
 	}
 
+	// Graceful shutdown of the pod.
+	if w.pod.ObjectMeta.DeletionTimestamp != nil && (w.probeType == liveness || w.probeType == startup) {
+		klog.V(3).Infof("Pod deletion requested, setting %v probe result to success: %v - %v",
+			w.probeType.String(), format.Pod(w.pod), w.container.Name)
+		if w.probeType == startup {
+			klog.Warningf("Pod deletion requested before successful container startup: %v - %v",
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/worker.go:230]: nit for readability:

```suggestion
			klog.Warningf("Pod deletion requested before container has fully started: %v - %v",
```

**Review by ehashman — COMMENTED** [review]
/lgtm

File: pkg/kubelet/prober/worker.go [hunk 8]
```diff
@@ -230,7 +244,7 @@ func (w *worker) doProbe() (keepGoing bool) {
 	if c.Started != nil && *c.Started {
 		// Stop probing for startup once container has started.
 		if w.probeType == startup {
-			return true
+			return false
```
Comment (wzshiming) [inline pkg/kubelet/prober/worker.go:247]: `startupProbe` behaviour changed
After the container restarts, `startupProbe` will no longer be executed
#101093
