### PR TITLE
Fix an issue that a Pod's nominatedNodeName cannot be cleared upon node deletion

### LINKED ISSUE #85677: Scheduler does not clear nominatedNodeName on Pod when node is no longer valid
**What happened**:

Scheduler decided that it wants to schedule Pod P on Node N after preempting some pods from N.
It set the P.nominatedNodeName to N. After a while (before scheduling actually happened) node N was removed from the cluster.
Scheduler did not reset P.nominatedNodeName to empty value.

**What you expected to happen**:

I would expect scheduler to unset P.nominatedNodeName when the node is no longer valid.
The trivial reason for node not being valid any more is it is removed from the cluster. 
But there are more cases to cover. Out of the top of my head I may think of:
- extra Pod was scheduled to node and there is not enough resources any more
  - either scheduled by scheduler
  - or directly as static pod/daemonset
- node became unschedulable

**How to reproduce it (as minimally and precisely as possible)**:

We did not try to reproduce issue manually. Yet following setup should work.
- create cluster with nodes A and B.
- ensure all system pods are running on A. Fill up A so it does not have spare resources.
- add a low priority Pod L with long termination, with requests matching allocatable of B. It should be scheduled to B.
- add a high priority Pod H. It should get B as nominatedNodeName
- kill node B
- the H.nominatedNodeName will still point to B which is no longer in the cluster

**Anything else we need to know?**:

Current behavior does not play well with Cluster Autoscaler which assumes that Pod with nominatedNodeName will be scheduled in a while.
Therefore such pods do not trigger scale-up. If we can have P.nominatedNodeName set incorrectly for unbounded period of time CA will never
provision node for P to run.

**Environment**:
- Kubernetes version (use `kubectl version`):

We observed the behavior during presubmit tests which run k8s built from HEAD of master on 27.11.2019.

Versions logged in test log:
I1125 18:55:11.691] Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.0.1183+414202578ba1ad", GitCommit:"414202578ba1ad53a26bc5126b3828a3a410097e", GitTreeState:"clean", BuildDate:"2019-11-25T17:04:18Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
I1125 18:55:11.692] Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.0-alpha.0.1183+414202578ba1ad", GitCommit:"414202578ba1ad53a26bc5126b3828a3a410097e", GitTreeState:"clean", BuildDate:"2019-11-25T17:04:18Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
GCE

/sig scheduling

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:

This PR tries to fix an issue that a Pod's nominatedNodeName cannot be cleared upon node deletion. Detailed reproducing steps please check #85677 and the integration test of this PR.

**Which issue(s) this PR fixes**:

Fixes #85677

**Special notes for your reviewer**:

A side effect is that upon unexpected internal errors during preemption, the nominatedNode would be returned as "", so the pod's non-nil nominatedNodeName will be cleared. It means its reserved room on a node can be occupied by other pods before it's scheduled next time.
But compared to the issue that its nominatedNode is unable to be cleared, the impact is negligible.

**Does this PR introduce a user-facing change?**:

```release-note
Fixed an issue that a Pod's nominatedNodeName cannot be cleared upon node deletion.
```

### CODE REVIEW

File: test/integration/scheduler/preemption_test.go [hunk 1]
```diff
@@ -1023,6 +1024,93 @@ func TestNominatedNodeCleanUp(t *testing.T) {
 	}
 }
 
+func TestNominatedNodeCleanUpUponNodeDeletion(t *testing.T) {
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption_test.go:1027]: This test can be merged with existing `TestNominatedNodeCleanUp` using table-test style.

File: test/integration/scheduler/util.go [hunk 2]
```diff
@@ -483,7 +483,7 @@ func noPodsInNamespace(c clientset.Interface, podNamespace string) wait.Conditio
 // cleanupPodsInNamespace deletes the pods in the given namespace and waits for them to
 // be actually deleted.
 func cleanupPodsInNamespace(cs clientset.Interface, t *testing.T, ns string) {
-	if err := cs.CoreV1().Pods(ns).DeleteCollection(context.TODO(), metav1.DeleteOptions{}, metav1.ListOptions{}); err != nil {
+	if err := cs.CoreV1().Pods(ns).DeleteCollection(context.TODO(), *metav1.NewDeleteOptions(0), metav1.ListOptions{}); err != nil {
```
Comment (ahg-g) [inline test/integration/scheduler/util.go:486]: what does this change mean?

**Review by ahg-g — COMMENTED** [review]
one clarification, otherwise looks good to me.

File: test/integration/scheduler/util.go (hunk 2 above)
Comment (Huang-Wei) [reply test/integration/scheduler/util.go:486]: Without this, this test would fail at the cleanup step: `defer cleanupPodsInNamespace(cs, t, testCtx.NS.Name)`.

This puzzled me as well, and here is my investigation. In the new test, it deleted a node, and then cleaned up all the Pods using `DeleteCollection`. However, one of the pods was placed on the deleted node. I think the **immediate** Pods deletion action resulted in the failure.

I tried to use curl to simulate this case. You can notice that pod2 keeps in terminating state instead of being deleted: 

```
root@wei-dev:~/manifests/certs# k get po -o wide
NAME   READY   STATUS    RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
pod1   1/1     Running   0          46s   192.168.192.168   node1   <none>           <none>
pod2   1/1     Running   0          3s    192.168.192.168   node2   <none>           <none>

root@wei-dev:~/manifests# k delete no node2
node "node2" deleted

root@wei-dev:~/manifests/certs# curl --key key --cert cert --cacert cacert -X DELETE https://localhost:6443/api/v1/namespaces/default/pods

root@wei-dev:~/manifests/certs# k get pod -o wide
NAME   READY   STATUS        RESTARTS   AGE   IP                NODE    NOMINATED NODE   READINESS GATES
pod2   1/1     Terminating   0          56s   192.168.192.168   node2   <none>           <none>

# After 30 seconds
root@wei-dev:~/manifests/certs# k get pod -o wide
No resources found in default namespace.
# But in an integration test, I guess the Pod will be kept there, that's why the test would fail without enforcing a 0 termination grace period
```

---

I'm not sure it's a bug in `DeleteCollection` or as expected, but as setting it to an explicit 0 grace period won't result in any side effect, I think we can just merge it as is, WDYT?
