### PR TITLE
fix volumebinding test in scheduler

### LINKED ISSUE #108610: volumebinding unit tests run slowly
The unit tests in pkg pkg/scheduler/framework/plugins/volumebinding cost ~30 seconds on my m1max machine:

```
⇒  go test ./pkg/scheduler/framework/plugins/volumebinding -count 1
ok  	k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding	28.960s
```

Among the tests, a single test even costs ~5 seconds:

```
⇒  go test ./pkg/scheduler/framework/plugins/volumebinding -run TestCheckBindingsWithCSIMigration -count 1
ok  	k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding	5.077s
```

It doesn't look like a good signal. It may be worth taking a close look to polish the tests a bit.

/sig scheduling
/kind cleanup
/help

### PR DESCRIPTION
**Pull request by Abirdcfly**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Save a few 3 seconds in tests. See below for more details:
```go
func (env *testEnv) updateVolumes(t *testing.T, pvs []*v1.PersistentVolume, waitCache bool) {
	for _, pv := range pvs {
		if _, err := env.client.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{}); err != nil {
			t.Fatalf("failed to update PV %q", pv.Name)
		}
	}
	if waitCache {
                // <------- Poll tries a condition func until it returns true, an error, or the timeout is reached.
		wait.Poll(100*time.Millisecond, 3*time.Second, func() (bool, error) {
			for _, pv := range pvs {
				obj, err := env.internalPVCache.GetAPIObj(pv.Name)
				if obj == nil || err != nil {
					return false, nil
				}
				pvInCache, ok := obj.(*v1.PersistentVolume)
				if !ok {
					return false, fmt.Errorf("PV %s invalid object", pvInCache.Name)
				}
				if versioner.CompareResourceVersion(pvInCache, pv) != 0 {
					return false, nil // <------because pv is updated, old pv will not same with pvInCache, there is always false，so we will always wait 3 second.
				}
			}
			return true, nil
		})
	}
}
```
#### Which issue(s) this PR fixes:

Fixes part of #108610

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 1]
```diff
@@ -334,9 +334,11 @@ func (env *testEnv) initVolumes(cachedPVs []*v1.PersistentVolume, apiPVs []*v1.P
 }
 
 func (env *testEnv) updateVolumes(t *testing.T, pvs []*v1.PersistentVolume, waitCache bool) {
-	for _, pv := range pvs {
-		if _, err := env.client.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{}); err != nil {
+	for i, pv := range pvs {
```
Comment (denkensk) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:337]: I looked up where to call this function. IIUC. It seems it's just for update operation in test. `pvs` isn't used latter.

**Review by denkensk — COMMENTED** [review]
Can you provide some data to show that your change really reduced the test run time?

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go (hunk 1 above)
Comment (Abirdcfly) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go:337]: just same function
````go
func (env *testEnv) updateVolumes(t *testing.T, pvs []*v1.PersistentVolume, waitCache bool) {
	for _, pv := range pvs {
		if _, err := env.client.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{}); err != nil {
			t.Fatalf("failed to update PV %q", pv.Name)
		}
	}
	if waitCache {
                // <------- Poll tries a condition func until it returns true, an error, or the timeout is reached.
		wait.Poll(100*time.Millisecond, 3*time.Second, func() (bool, error) {
			for _, pv := range pvs {
				obj, err := env.internalPVCache.GetAPIObj(pv.Name)
				if obj == nil || err != nil {
					return false, nil
				}
				pvInCache, ok := obj.(*v1.PersistentVolume)
				if !ok {
					return false, fmt.Errorf("PV %s invalid object", pvInCache.Name)
				}
				if versioner.CompareResourceVersion(pvInCache, pv) != 0 {
					return false, nil // <------because pv is updated, old pv will not same with pvInCache, there is always false，so we will always wait 3 second.
				}
			}
			return true, nil
		})
	}
}
````

**Comment by Abirdcfly** [comment]
> Can you provide some data to show that your change really reduced the test run time?

```bash
git@083c3ac4 
go test ./pkg/scheduler/framework/plugins/volumebinding -count 1
ok      k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding 26.336s
go test ./pkg/scheduler/framework/plugins/volumebinding -count 10
ok      k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding 263.147s

git@fixtestpvc
go test ./pkg/scheduler/framework/plugins/volumebinding -count 1
ok      k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding 21.309s
go test ./pkg/scheduler/framework/plugins/volumebinding -count 10
ok      k8s.io/kubernetes/pkg/scheduler/framework/plugins/volumebinding 206.150s
```

**Comment by Abirdcfly** [comment]
/remove-sig storage 

cc @Huang-Wei

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go (hunk 1 above)
Comment (denkensk) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go:337]: Oh, I see. This means that 3 seconds will be wasted anyway.
It is better to add your explanation in the description of this pr `What this PR does / why we need it:`.

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 2]
```diff
@@ -334,9 +334,11 @@ func (env *testEnv) initVolumes(cachedPVs []*v1.PersistentVolume, apiPVs []*v1.P
...
+		if newPv, err := env.client.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{}); err != nil {
 			t.Fatalf("failed to update PV %q", pv.Name)
+		} else {
+			pvs[i] = newPv
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:341]: Remove `else` here, it's redundant.

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 3]
```diff
@@ -360,9 +362,11 @@ func (env *testEnv) updateVolumes(t *testing.T, pvs []*v1.PersistentVolume, wait
 }
 
 func (env *testEnv) updateClaims(t *testing.T, pvcs []*v1.PersistentVolumeClaim, waitCache bool) {
-	for _, pvc := range pvcs {
-		if _, err := env.client.CoreV1().PersistentVolumeClaims(pvc.Namespace).Update(context.TODO(), pvc, metav1.UpdateOptions{}); err != nil {
+	for i, pvc := range pvcs {
+		if newPvc, err := env.client.CoreV1().PersistentVolumeClaims(pvc.Namespace).Update(context.TODO(), pvc, metav1.UpdateOptions{}); err != nil {
 			t.Fatalf("failed to update PVC %q", getPVCName(pvc))
+		} else {
+			pvcs[i] = newPvc
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:369]: The same.

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go:337]: `updateVolumes` should be returning a flag indicating whether or not the update actually happened and have the caller check that and fail if it didn't; same thing with `updateClaims`; also the `waitCache` seems to always be set to true and so we can remove it.

**Comment by Abirdcfly** [comment]
PTAL @Huang-Wei @ahg-g

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 4]
```diff
@@ -333,55 +333,61 @@ func (env *testEnv) initVolumes(cachedPVs []*v1.PersistentVolume, apiPVs []*v1.P
...
+				return false, fmt.Errorf("PV %s invalid object", pvInCache.Name)
+			}
+			if versioner.CompareResourceVersion(pvInCache, pv) != 0 {
+				return false, nil
+			}
+		}
+		return true, nil
+	})
+	if err != nil {
+		t.Fatalf("failed to update PV %v", err)
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:361]: My 2 cents: given the function is named `updateVolumes`, it's a bit aggressive to fatal the test directly. I'd suggest one of the two options:

1. Return the err, and let the callers to decide how to respond with the err (@ahg-g pointed out: https://github.com/kubernetes/kubernetes/pull/109043/files?w=1#r846922035)
2. Compose two functions: `updateXYZ` and `udpateXYZOrDie`. The latter one calls the previous one and fatal the test if an err is returned. On caller side, we can call `udpateXYZOrDie`.

Comment (Abirdcfly) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go]: Modify the code according to option one.

Comment (Abirdcfly) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go]: > My 2 cents: given the function is named `updateVolumes`, it's a bit aggressive to fatal the test directly. I'd suggest one of the two options:
> 
> 1. Return the err, and let the callers to decide how to respond with the err (@ahg-g pointed out: https://github.com/kubernetes/kubernetes/pull/109043/files?w=1#r846922035)
> 2. Compose two functions: `updateXYZ` and `udpateXYZOrDie`. The latter one calls the previous one and fatal the test if an err is returned. On caller side, we can call `udpateXYZOrDie`.

Modify the code according to option 1

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 5]
```diff
@@ -333,56 +333,56 @@ func (env *testEnv) initVolumes(cachedPVs []*v1.PersistentVolume, apiPVs []*v1.P
 
 }
 
-func (env *testEnv) updateVolumes(t *testing.T, pvs []*v1.PersistentVolume, waitCache bool) {
-	for _, pv := range pvs {
-		if _, err := env.client.CoreV1().PersistentVolumes().Update(context.TODO(), pv, metav1.UpdateOptions{}); err != nil {
-			t.Fatalf("failed to update PV %q", pv.Name)
+func (env *testEnv) updateVolumes(pvs []*v1.PersistentVolume) (err error) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:336]:
```suggestion
func (env *testEnv) updateVolumes(pvs []*v1.PersistentVolume) error {
```

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 6]
```diff
@@ -333,56 +333,56 @@ func (env *testEnv) initVolumes(cachedPVs []*v1.PersistentVolume, apiPVs []*v1.P
...
+		}
+		return true, nil
+	})
 }
 
-func (env *testEnv) updateClaims(t *testing.T, pvcs []*v1.PersistentVolumeClaim, waitCache bool) {
-	for _, pvc := range pvcs {
-		if _, err := env.client.CoreV1().PersistentVolumeClaims(pvc.Namespace).Update(context.TODO(), pvc, metav1.UpdateOptions{}); err != nil {
-			t.Fatalf("failed to update PVC %q", getPVCName(pvc))
+func (env *testEnv) updateClaims(pvcs []*v1.PersistentVolumeClaim) (err error) {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:362]:
```suggestion
func (env *testEnv) updateClaims(pvcs []*v1.PersistentVolumeClaim) error {
```

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go [hunk 7]
```diff
@@ -1727,12 +1727,16 @@ func TestCheckBindings(t *testing.T) {
 		if scenario.deletePVs {
 			testEnv.deleteVolumes(scenario.initPVs)
 		} else {
-			testEnv.updateVolumes(t, scenario.apiPVs, true)
+			if err := testEnv.updateVolumes(scenario.apiPVs); err != nil {
+				t.Errorf("failed to update PVs: %v", err)
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/binder_test.go:1731]: Make the first letter uppercase (applies elsewhere):

```suggestion
				t.Errorf("Failed to update PVs: %v", err)
```

File: pkg/scheduler/framework/plugins/volumebinding/binder_test.go (hunk 1 above)
Comment (Abirdcfly) [reply pkg/scheduler/framework/plugins/volumebinding/binder_test.go:337]: All finished.

**Comment by Huang-Wei** [comment]
/lgtm
/approve

Thanks @Abirdcfly .
