### PR TITLE
move pods.go to pods_test.go

### LINKED ISSUE #24635: tests in test/integration/ don't fail as expected
hack/test-integration.sh passes even with an explicit "t.Fatalf()" in the test/integration/pods.go:
```
func TestPodUpdateActiveDeadlineSeconds(t *testing.T) {
 	t.Fatalf("FAIL")
        ...
``` 
(see https://github.com/caesarxuchao/kubernetes/commit/682875b5ff213c4808e7156ae421074838be70c4#diff-8f08d0bc51b37140950a80ee07940db1R36).

Appreciate any insight.

@ixdy @krousey

### PR DESCRIPTION
**Pull request by caesarxuchao**
fix #24635

### CODE REVIEW

File: test/integration/pods_test.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ func TestPodUpdateActiveDeadlineSeconds(t *testing.T) {
 	prototypePod := func() *api.Pod {
 		return &api.Pod{
 			ObjectMeta: api.ObjectMeta{
-				Name: "XXX",
```
Comment (caesarxuchao) [inline test/integration/pods_test.go]: The validation rule now doesn't allow capital letters.

File: test/integration/pods_test.go [hunk 2]
```diff
@@ -87,7 +87,7 @@ func TestPodUpdateActiveDeadlineSeconds(t *testing.T) {
 		{
 			name:     "no change, set",
 			original: &i30,
-			update:   &i60,
+			update:   &i30,
```
Comment (caesarxuchao) [inline test/integration/pods_test.go]: I think this was the author intended to do.
