### PR TITLE
Address couple of issue on image build for ARM arch

### LINKED ISSUE #79689: agnhost image build failed for ARM arch
**What happened**:

cd $GOPATH/src/k8s.io/kubernetes/test/images/agnhost

$ make
../image-util.sh bin webhook
../image-util.sh: line 145: GOARM: unbound variable
Makefile:23: recipe for target 'bin' failed
make: *** [bin] Error 1

**What you expected to happen**:

The binary or image should be built successfully.

**How to reproduce it (as minimally and precisely as possible)**:
see my desc above, type "make" will see the error message.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #79710: `make all WHAT=agnhost` from `test/images` failed with root
**What happened**:
login system root, and run below command from "test/images" dir, 

```bash
cd test/images
make all WHAT=agnhost
```

Will fail with below error message,
./image-util.sh: line 91: : command not found

This is cause by the empty string like "" cannot be understood as a shell command. 

**What you expected to happen**:
image should be built successfully.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
cd test/images
make all WHAT=agnhost
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`):all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #79689
Fixes #79710
```release-note
NONE
```

### CODE REVIEW

File: test/images/image-util.sh [hunk 1]
```diff
@@ -142,11 +142,16 @@ push() {
 bin() {
   for SRC in $@;
   do
+  if [[ "${ARCH}" == "arm" ]]; then
+    arch_prefix="GOARM=${GOARM:-7} GOARCH=arm"
```
Comment (BenTheElder) [inline test/images/image-util.sh]: why are we hardcoding `GOARCH=arm` when we know `GOARCH=${ARCH}` would give the same result?

this is more brittle due to relying on bash string splitting below.

File: test/images/image-util.sh [hunk 2]
```diff
@@ -142,11 +142,16 @@ push() {
...
+  else
+    arch_prefix="GOARCH=${ARCH}"
+  fi
   docker run --rm -it -v "${TARGET}:${TARGET}:Z" -v "${KUBE_ROOT}":/go/src/k8s.io/kubernetes:Z \
         golang:"${GOLANG_VERSION}" \
         /bin/bash -c "\
                 cd /go/src/k8s.io/kubernetes/test/images/${SRC_DIR} && \
-                CGO_ENABLED=0 GOARM=${GOARM} GOARCH=${ARCH} go build -a -installsuffix cgo --ldflags '-w' -o ${TARGET}/${SRC} ./$(dirname "${SRC}")"
+                CGO_ENABLED=0 ${arch_prefix} go build -a -installsuffix cgo --ldflags '-w' -o ${TARGET}/${SRC} ./$(dirname "${SRC}")"
```
Comment (BenTheElder) [inline test/images/image-util.sh]:
```suggestion
                CGO_ENABLED=0 GOARM=${GOARM:-7} GOARCH=${ARCH} go build -a -installsuffix cgo --ldflags '-w' -o ${TARGET}/${SRC} ./$(dirname "${SRC}")"
```

Comment (BenTheElder) [reply test/images/image-util.sh]: though probably the GOARM defaulting should be fixed wherever we're actually setting / exporting it instead.

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/79689#issuecomment-507936520

File: test/images/image-util.sh (hunk 2 above)
Comment (chendave) [reply test/images/image-util.sh]: @BenTheElder , thanks for the review,  I don't think so, cause GOARM is only needed when the GOARCH is "arm". 

The change below will make the GOARM always been set regardless it is `amd64`, `arm` or whatever arch it is.

`GOARM=${GOARM:-7}`

File: test/images/image-util.sh (hunk 1 above)
Comment (chendave) [reply test/images/image-util.sh]: see https://github.com/golang/go/wiki/GoArm, this is only needed when ARCH is `arm`, it will make the info of ARCH more explicitly.

File: test/images/image-util.sh (hunk 2 above)
Comment (BenTheElder) [reply test/images/image-util.sh]: this appears to actually be the true case anyhow https://github.com/kubernetes/kubernetes/issues/79689#issuecomment-507936520

these are usually built from `test/images` which sets GOARM=7, I'm not sure we need this PR vs some better docs. https://github.com/kubernetes/kubernetes/issues/79689#issuecomment-507936520

File: test/images/image-util.sh (hunk 1 above)
Comment (BenTheElder) [reply test/images/image-util.sh]: what I mean is, we are unnecessarily branching the `GOARCH=` part which then causes us to rely on shell splitting below which is known to be a source of bugs. We don't need to do the GOARCH part here even if we want to use a branch to set GOARM.

_IF_ we did, we should use an array instead of a space separated string.

Comment (chendave) [reply test/images/image-util.sh]: yes, I see, this is not necessary.

Comment (BenTheElder) [reply test/images/image-util.sh]: we should also consider removing the GOARM=7 in test/images/Makefile

we can find other places with GOARM with https://cs.k8s.io/?q=GOARM&i=nope&files=&repos=kubernetes/kubernetes

it seems to be hardcoded in a few places. I'm not sure on the history behind that, but we can find out!

Comment (chendave) [reply test/images/image-util.sh]: sure, will do, thanks!

**Comment by chendave** [comment]
@BenTheElder , is this one better?

**Review by jpbetz — APPROVED** [review]
/lgtm
/approve

File: cluster/images/etcd/Makefile [hunk 3]
```diff
@@ -97,13 +97,18 @@ else
 
 	# Download etcd in a golang container and cross-compile it statically
 	# For each release create a tmp dir 'etcd_release_tmp_dir' and unpack the release tar there.
+	arch_prefix=""
+        ifeq ($(ARCH),arm)
```
Comment (BenTheElder) [inline cluster/images/etcd/Makefile]: nit: this indent looks mis-aligned?

**Review by BenTheElder — APPROVED** [review]
thanks!
one nit
/approve
/hold

File: cluster/images/etcd/Makefile (hunk 3 above)
Comment (chendave) [reply cluster/images/etcd/Makefile]: Hi @BenTheElder , it's must be "space" instead of "tab" cause "tab" will make interpret it as shell command while `ifeq` is not, make it as this to avoid the failure to run `make` with this `Makefile`.
