### PR TITLE
[Mitigate KCM CrashLooping] Add unittests for controllers' Init func

### LINKED ISSUE #55271: Individual controllers should not cause kube-controller-manager to exit
In #55022 we observed a crashlooping controller cause a cluster cold boot failure, as controller-manager wasn't able to stay up long enough to run the deployment that would have fixed the problem.

We should audit everything that runs in kube-controller-manager and ensure that they all fail gracefully enough to prevent crashloops, or make them individually restart in that case, instead of the process.

Longer term, we should consider classifying the controllers by run level or bootstrap order (#54522), and splitting them into separate binaries or changing the start-up order in kcm to make sure this sort of thing doesn't happen in the future.

### PR DESCRIPTION
**Pull request by yuwenma**
Test:

make test
Specifically: make test WHAT=./cmd/kube-controller-manager/app/

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation

> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Add unittests to controllers which do resource discovery in their initialization. Even if the discovery resource step fails, (if the error is tolerant, like resource is only partially discovered), the controller manager can tolerant the error.

Why Discovery failure may cause KCM crash looping: If the discovery failure results in a controller initialization breakage (especially happened in the resource discovery), the kube-controller-manager(KCM) will exit immediately and leaving some controllers unstarted. When the KCM is restarted, it will exit again for the same cause.

**Which issue(s) this PR fixes**:

Fixes #55271

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-controller-manager/app/core.go [hunk 1]
```diff
@@ -324,21 +324,22 @@ func startResourceQuotaController(ctx ControllerContext) (http.Handler, bool, er
 }
 
 func startNamespaceController(ctx ControllerContext) (http.Handler, bool, error) {
+	namespaceKubeClient := ctx.ClientBuilder.ClientOrDie("namespace-controller")
```
Comment (cheftako) [inline cmd/kube-controller-manager/app/core.go]: Do we really want to construct namespaceKubeClient twice in different ways?

Comment (yuwenma) [reply cmd/kube-controller-manager/app/core.go]: Fixed.

**Comment by davidopp** [comment]
removed myself as reviewer; I am not familiar with kube-controller-manage these days

File: cmd/kube-controller-manager/app/core_test.go [hunk 2]
```diff
@@ -107,7 +126,15 @@ func TestStartResourceQuotaController_DiscoveryError(t *testing.T) {
 			InformerFactory:  informers.NewSharedInformerFactoryWithOptions(testClientset, time.Duration(1)),
 			InformersStarted: make(chan struct{}),
 		}
-		_, _, err := startResourceQuotaController(ctx)
+		var err error
```
Comment (cheftako) [inline cmd/kube-controller-manager/app/core_test.go]: I don't think we need to declare the error here as we are not concerned with persisting the value.

Comment (yuwenma) [reply cmd/kube-controller-manager/app/core_test.go]: Ooops. Removed

**Review by cheftako — APPROVED** [review]
/lgtm

File: cmd/kube-controller-manager/app/core.go [hunk 3]
```diff
@@ -331,6 +332,10 @@ func startNamespaceController(ctx ControllerContext) (http.Handler, bool, error)
 	nsKubeconfig.QPS *= 20
 	nsKubeconfig.Burst *= 100
 	namespaceKubeClient := clientset.NewForConfigOrDie(nsKubeconfig)
+	return startModifiedNamespaceController(ctx, namespaceKubeClient, nsKubeconfig)
+}
+
+func startModifiedNamespaceController(ctx ControllerContext, namespaceKubeClient clientset.Interface, nsKubeconfig *restclient.Config) (http.Handler, bool, error) {
```
Comment (deads2k) [inline cmd/kube-controller-manager/app/core.go]: This name isn't obvious to me, but if Walter liked it I won't nit it to death. Next time something more obvious?   If you removed a context dependency for instance it may make it more obvious.  Based on where you split it, I'm guessing you didn't want to deal with the client built from config because you can't mock that.

**Comment by deads2k** [comment]
A nit about naming, but I won't block on it.

/approve
