### PR TITLE
Omit namespace when kubectl get is for the cluster

### LINKED ISSUE #80855: Confusing message in kubectl get when no cluster-scoped resources found
**What happened**:
When running `kubectl get <cluster-scoped resource kind>` and no resource is found, kubectl returns `No resources found in mynamespace namespace`, which is confusing, since we're trying to list instances of a *cluster-scoped* resource.

**What you expected to happen**:
When listing cluster-scoped resources, the message should either be
```
No resources found.
``` 
or 
```
No resources found at the cluster scope.
```

**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl get volumeattachments
```
(assuming there are no `volumeattachments`; can also try `validatingwebhookconfigurations` or similar)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.0-alpha.2.130+4ce69dd32ef9c3-dirty", GitCommit:"4ce69dd32ef9c34b11f06ef195438f4e2ee7c5ed", GitTreeState:"dirty", BuildDate:"2019-08-01T10:54:52Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When kubectl get is for the cluster, the output shouldn't mention namespace.

**Which issue(s) this PR fixes**:
Fixes #80855

**Special notes for your reviewer**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
@apelisse
Can you take a look ?

File: pkg/kubectl/cmd/get/get.go [hunk 1]
```diff
@@ -581,7 +581,11 @@ func (o *GetOptions) Run(f cmdutil.Factory, cmd *cobra.Command, args []string) e
 	w.Flush()
 	if trackingWriter.Written == 0 && !o.IgnoreNotFound && len(allErrs) == 0 {
 		// if we wrote no output, and had no errors, and are not ignoring NotFound, be sure we output something
-		noResourcesFoundFormat := fmt.Sprintf("No resources found in %s namespace.", o.Namespace)
+		namespaceClause := ""
+		if !o.AllNamespaces {
```
Comment (apelisse) [inline pkg/kubectl/cmd/get/get.go]: I would probably keep it simpler and build two separate strings altogether

File: pkg/kubectl/cmd/get/get.go [hunk 2]
```diff
@@ -581,7 +581,12 @@ func (o *GetOptions) Run(f cmdutil.Factory, cmd *cobra.Command, args []string) e
 	w.Flush()
 	if trackingWriter.Written == 0 && !o.IgnoreNotFound && len(allErrs) == 0 {
 		// if we wrote no output, and had no errors, and are not ignoring NotFound, be sure we output something
-		noResourcesFoundFormat := fmt.Sprintf("No resources found in %s namespace.", o.Namespace)
+		noResourcesFoundFormat := ""
+		if !o.AllNamespaces {
```
Comment (apelisse) [inline pkg/kubectl/cmd/get/get.go]: Sorry about this but, do you need `noResourcesFoundFormat`, you could call `Fprintln` directly

**Comment by tedyu** [comment]
@apelisse
Your comment has been addressed.

**Review by apelisse — COMMENTED** [review]
/lgtm
/approve

**Comment by luksa** [comment]
Note that these changes did not address https://github.com/kubernetes/kubernetes/issues/80855, but a related problem.
