### PR TITLE
kubelet: clamp cpu.shares to max allowed

### LINKED ISSUE #92855: kubelet fails to create kubepods cgroup on larger machine with 512 processors with systemd CgroupDriver
**What happened**:
kubelet fails to create kubepods cgroup on larger machine with 512 cpus, fails with the following error:

```
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com systemd[1]: Started Kubernetes systemd probe.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.406533   88851 server.go:417] Version: v1.18.5
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.407109   88851 plugins.go:100] No cloud provider specified.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.407132   88851 server.go:838] Client rotation is on, will bootstrap in background
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.410018   88851 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.411101   88851 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: W0627 03:36:17.411181   88851 server.go:616] failed to get the kubelet's cgroup: cpu and memory cgroup hierarchy not unified.  cpu: /, memory: /system.slice/kubelet.service.  Kubelet system container metrics may be missing.
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.425930   88851 server.go:647] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.426777   88851 container_manager_linux.go:266] container manager verified user specified cgroup-root exists: []
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.426794   88851 container_manager_linux.go:271] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.426936   88851 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.426946   88851 container_manager_linux.go:301] [topologymanager] Initializing Topology Manager with none policy
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.426953   88851 container_manager_linux.go:306] Creating device plugin manager: true
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: W0627 03:36:17.428494   88851 util_unix.go:103] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428543   88851 remote_runtime.go:59] parsed scheme: ""
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428556   88851 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428588   88851 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428598   88851 clientconn.go:933] ClientConn switching balancer to "pick_first"
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: W0627 03:36:17.428649   88851 util_unix.go:103] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428667   88851 remote_image.go:50] parsed scheme: ""
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428678   88851 remote_image.go:50] scheme "" not registered, fallback to default scheme
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428690   88851 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/run/crio/crio.sock  <nil> 0 <nil>}] <nil> <nil>}
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428697   88851 clientconn.go:933] ClientConn switching balancer to "pick_first"
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428737   88851 kubelet.go:292] Adding pod path: /etc/kubernetes/manifests
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:17.428770   88851 kubelet.go:317] Watching apiserver
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:17.432743   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:526: Failed to list *v1.Node: Get https://9.3.66.49:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:17.433159   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.3.66.49:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:17 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:17.433128   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:517: Failed to list *v1.Service: Get https://9.3.66.49:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:18 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:18.474546   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.3.66.49:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:18 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:18.495764   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:526: Failed to list *v1.Node: Get https://9.3.66.49:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:18 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:18.725044   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:517: Failed to list *v1.Service: Get https://9.3.66.49:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:20 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:20.277492   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:526: Failed to list *v1.Node: Get https://9.3.66.49:6443/api/v1/nodes?fieldSelector=metadata.name%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:20 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:20.343259   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://9.3.66.49:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dcloudpack001.isst.aus.stglabs.ibm.com&limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:21 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:21.225503   88851 reflector.go:178] k8s.io/kubernetes/pkg/kubelet/kubelet.go:517: Failed to list *v1.Service: Get https://9.3.66.49:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.669046   88851 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.670671   88851 kuberuntime_manager.go:211] Container runtime cri-o initialized, version: 1.16.6-16.dev.rhaos4.3.git4936f44.el8, apiVersion: v1alpha1
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.671291   88851 server.go:1126] Started kubelet
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.671352   88851 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.671371   88851 server.go:145] Starting to listen on 0.0.0.0:10250
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.672045   88851 event.go:269] Unable to write event: 'Post https://9.3.66.49:6443/api/v1/namespaces/default/events: dial tcp 9.3.66.49:6443: connect: connection refused' (may retry after sleeping)
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.673502   88851 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.673753   88851 volume_manager.go:265] Starting Kubelet Volume Manager
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.675019   88851 desired_state_of_world_populator.go:139] Desired state populator starts to run
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.675821   88851 controller.go:136] failed to ensure node lease exists, will retry in 200ms, error: Get https://9.3.66.49:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/cloudpack001.isst.aus.stglabs.ibm.com?timeout=10s: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.675851   88851 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSIDriver: Get https://9.3.66.49:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.681798   88851 server.go:393] Adding debug handlers to kubelet server.
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.729459   88851 status_manager.go:158] Starting to sync pod status with apiserver
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.729609   88851 kubelet.go:1821] Starting kubelet main sync loop.
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.730526   88851 kubelet.go:1845] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.731313   88851 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get https://9.3.66.49:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.775336   88851 kubelet.go:2267] node "cloudpack001.isst.aus.stglabs.ibm.com" not found
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.775348   88851 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.781036   88851 kubelet_node_status.go:70] Attempting to register node cloudpack001.isst.aus.stglabs.ibm.com
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.781700   88851 kubelet_node_status.go:92] Unable to register node "cloudpack001.isst.aus.stglabs.ibm.com" with API server: Post https://9.3.66.49:6443/api/v1/nodes: dial tcp 9.3.66.49:6443: connect: connection refused
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.810155   88851 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813682   88851 cpu_manager.go:184] [cpumanager] starting with none policy
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813696   88851 cpu_manager.go:185] [cpumanager] reconciling every 10s
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813715   88851 state_mem.go:36] [cpumanager] initializing new in-memory state store
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813897   88851 state_mem.go:88] [cpumanager] updated default cpuset: ""
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813948   88851 state_mem.go:96] [cpumanager] updated cpuset assignments: "map[]"
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: I0627 03:36:23.813959   88851 policy_none.go:43] [cpumanager] none policy: Start
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: E0627 03:36:23.819279   88851 node_container_manager_linux.go:57] Failed to create ["kubepods"] cgroup
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com kubelet[88851]: F0627 03:36:23.819299   88851 kubelet.go:1383] Failed to start ContainerManager Value specified in CPUShares is out of range
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 27 03:36:23 cloudpack001.isst.aus.stglabs.ibm.com systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

**What you expected to happen**:
Run kubelet properly without any error
**How to reproduce it (as minimally and precisely as possible)**:
Start the kubelet on a machine which has a more processors

```shell
[root@worker0 ~]# lscpu
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              512              <====================== processors
On-line CPU(s) list: 0-511
Thread(s) per core:  8
Core(s) per socket:  1
Socket(s):           64
NUMA node(s):        8
Model:               1.2 (pvr 004e 2102)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   pHyp
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
NUMA node0 CPU(s):   0-7,64-71,128-135,192-199,256-263,320-327,384-391,448-455
NUMA node1 CPU(s):   8-15,72-79,136-143,200-207,264-271,328-335,392-399,456-463
NUMA node2 CPU(s):   16-23,80-87,144-151,208-215,272-279,336-343,400-407,464-471
NUMA node3 CPU(s):   24-31,88-95,152-159,216-223,280-287,344-351,408-415,472-479
NUMA node4 CPU(s):   32-39,96-103,160-167,224-231,288-295,352-359,416-423,480-487
NUMA node5 CPU(s):   40-47,104-111,168-175,232-239,296-303,360-367,424-431,488-495
NUMA node6 CPU(s):   48-55,112-119,176-183,240-247,304-311,368-375,432-439,496-503
NUMA node7 CPU(s):   56-63,120-127,184-191,248-255,312-319,376-383,440-447,504-511
Physical sockets:    8
Physical chips:      1
Physical cores/chip: 12
[root@worker0 ~]#
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.18.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by giuseppe**
clamp the max cpu.shares to the maximum value allowed by the kernel.

It is not an issue when using cgroupfs, as the kernel will
anyway make sure the value is not out of range and automatically clamp
it, systemd has an additional check that prevents the cgroup creation.

Closes: https://github.com/kubernetes/kubernetes/issues/92855

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #92855

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by giuseppe** [comment]
@derekwaynecarr I think it is good to have for 1.19

**Comment by mkumatag** [comment]
Thanks for the PR, my only worry about - how k8s will prioritize when we have two pods requesting more than the MaxShares how this logic will prioritize it!

File: pkg/kubelet/cm/helpers_linux.go [hunk 1]
```diff
@@ -40,6 +40,7 @@ import (
 const (
 	// Taken from lmctfy https://github.com/google/lmctfy/blob/master/lmctfy/controllers/cpu_controller.cc
```
Comment (kolyshkin) [inline pkg/kubelet/cm/helpers_linux.go:41]: Maybe change this comment as the above link does not have anything about the value of MaxShares.

It also makes sense to refer to the kernel directly. Either of these links should work:
* https://github.com/torvalds/linux/blob/0bddd227f3dc55975e2b8dfa7fc6f959b062a2c7/kernel/sched/sched.h#L427-L428
* https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/tree/kernel/sched/sched.h?id=8cd9234c64c584432f6992fe944ca9e46ca8ea76#n269

Comment (giuseppe) [reply pkg/kubelet/cm/helpers_linux.go:41]: good idea, fixed!
