### PR TITLE
Fix cleanup of volume metadata json file.

### LINKED ISSUE #65322: CSI leaves orphan json files in global mount directory
/kind bug
/sig storage

**What happened**:
When using a CSI driver that does not support NODE_STAGE, I can see orphan json files in `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-938861e4756911e8/vol_data.json` that are never cleaned up.

**What you expected to happen**:
No orphan file

/assign

### PR DESCRIPTION
**Pull request by jsafrane**
Create the json file with metadata as the last item, when everything else is ready, so we don't need to clean up the file in all error cases in this function.

Fixes #65322

**Release note**:
```release-note
Fixed cleanup of CSI metadata files.
```

/assign @saad-ali @vladimirvivien

### CODE REVIEW

File: pkg/volume/csi/csi_attacher.go [hunk 1]
```diff
@@ -354,6 +341,21 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
...
 
+	// Save volDataFileName as the very last item before NodeStageVolume, so we
+	// don't need to clean it up in every error path.
+	data := map[string]string{
+		volDataKey.volHandle:  csiSource.VolumeHandle,
+		volDataKey.driverName: csiSource.Driver,
+	}
+	if err := saveVolumeData(dataDir, volDataFileName, data); err != nil {
+		glog.Error(log("failed to save volume info data: %v", err))
+		if err := os.RemoveAll(dataDir); err != nil {
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go]: Do all the error returns above also need to RemoveAll(dataDir)?  Maybe this cleanup should be in a defer function that only runs if err != nil ?

Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: `MkdirAll()` is just a few lines above and there is no return in between. I'll move it even closer to `NodeStageVolume` with some comment.

**Comment by jsafrane** [comment]
Moved staging directory creating closer to `NodeStageVolume` call

**Comment by jsafrane** [comment]
/hold

This PR makes is actually worse. `UnmountDevice` needs the json file even if the driver does not support `UnstageVolume` - `UnmountDevice` checks it by itself and it needs the driver name.

**Comment by jsafrane** [comment]
/hold cancel

Now the json file is created early and cleaned in defer.

@msau42, PTAL

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -269,24 +269,34 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
...
+			glog.Error(log("failed to remove dir after error [%s]: %v", dataDir, cleanerr))
 		}
 		return err
 	}
+	defer func() {
+		if err != nil {
+			// clean up metadata
+			glog.Errorf(log("attacher.MountDevice failed: %v", err))
+			if err := removeMountDir(c.plugin, deviceMountPath); err != nil {
+				glog.Error(log("attacher.MountDevice failed to remove mount dir after a NodeStageVolume() error [%s]: %v", deviceMountPath, err))
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go]: It may not always be a NodeStageVolume() call that errored

File: pkg/volume/csi/csi_attacher.go [hunk 3]
```diff
@@ -269,24 +269,34 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
...
-			return err
+		if cleanerr := os.RemoveAll(dataDir); err != nil {
+			glog.Error(log("failed to remove dir after error [%s]: %v", dataDir, cleanerr))
 		}
 		return err
 	}
+	defer func() {
+		if err != nil {
+			// clean up metadata
+			glog.Errorf(log("attacher.MountDevice failed: %v", err))
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go]: Also should all the early error returns set err first so that the correct error will be logged here?  For example L311, 322, 331, 336, 345

Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: Fixed 322, 331 336 and 345. I can't see anything wrong in 311.

Comment (msau42) [reply pkg/volume/csi/csi_attacher.go]: My question regarding 311, 332, 337: is there a reason to log almost the same message first before returning the error, which will then be logged again in the defer?

Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: I see, I removed these error logs.
