### PR TITLE
kubeadm: Make the self-hosting with certificates in Secrets mode work again

### LINKED ISSUE #405: Make the certs-in-Secrets self-hosting mode working
Currently, it is not working as intended. I don't have any proof handy, but it just hang when I tried it out.
I sent a PR to fix it though: https://github.com/kubernetes/kubernetes/pull/50766 (and greatly improve the code there)

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

This PR:
 - makes the self-hosting with certificates in Secrets mode work
 - makes the wait functions timeoutable
 - fixes a race condition where the kubelet may be slow to remove the Static Pod
 - cleans up some of the self-hosting logic
 - makes self-hosting-with-secrets respect the feature flag

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes: https://github.com/kubernetes/kubeadm/issues/405

**Special notes for your reviewer**:

This is work in progress. I'll add unit tests, rebase upon https://github.com/kubernetes/kubernetes/pull/50762 and maybe split out some of the functionatlity here into a separate PR

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by luxas** [comment]
@mattmoyer @andrewrynhard @timothysc This is now rebased. PTAL and review

File: cmd/kubeadm/app/phases/selfhosting/podspec_mutation.go [hunk 1]
```diff
@@ -17,43 +17,50 @@ limitations under the License.
...
 			addNodeSelectorToPodSpec,
 			setMasterTolerationOnPodSpec,
 			setRightDNSPolicyOnPodSpec,
-			setVolumesOnKubeSchedulerPodSpec,
 		},
 	}
+}
 
+// mutatePodSpec makes a Static Pod-hosted PodSpec suitable for self-hosting
+func mutatePodSpec(mutators map[string][]func(*v1.PodSpec), name string, podSpec *v1.PodSpec) {
```
Comment (andrewrynhard) [inline cmd/kubeadm/app/phases/selfhosting/podspec_mutation.go]: 👍

File: cmd/kubeadm/app/phases/selfhosting/selfhosting.go [hunk 2]
```diff
@@ -53,13 +53,23 @@ const (
...
 		}
-		if err := createOpaqueSecrets(cfg, client); err != nil {
+		if err := uploadKubeConfigSecrets(client); err != nil {
 			return err
 		}
+		// Add the store-certs-in-secrets-specific mutators here so that the self-hosted component starts using them
+		mutators[kubeadmconstants.KubeAPIServer] = append(mutators[kubeadmconstants.KubeAPIServer], useSelfHostedVolumesForAPIServer)
+		mutators[kubeadmconstants.KubeControllerManager] = append(mutators[kubeadmconstants.KubeControllerManager], useSelfHostedVolumesForControllerManager)
+		mutators[kubeadmconstants.KubeScheduler] = append(mutators[kubeadmconstants.KubeScheduler], useSelfHostedVolumesForScheduler)
 	}
```
Comment (andrewrynhard) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting.go]: Upon first glance `useSelfHostedVolumesForXXX` sounds like a boolean. Can we change these to something like `selfHostedVolumesForXXXFunc` or `xxxVolumesMutatorFunc`? Helps with the readability a bit.

**Review by andrewrynhard — APPROVED** [review]
Only nit is on the naming convention for the selfhosted volume mutator funcs. Other than that lgtm.

File: cmd/kubeadm/app/phases/selfhosting/selfhosting.go (hunk 2 above)
Comment (luxas) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting.go]: I'll rename this to `setSelfHostedVolumesForXXX`

**Comment by timothysc** [comment]
assigning to @luxas here.

File: cmd/kubeadm/app/phases/selfhosting/selfhosting_test.go [hunk 3]
```diff
@@ -21,128 +21,50 @@ import (
...
 spec:
   containers:
   - command:
     - kube-apiserver
-    - --client-ca-file=/etc/kubernetes/pki/ca.crt
-    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
-    - --allow-privileged=true
-    - --service-cluster-ip-range=10.96.0.0/12
     - --service-account-key-file=/etc/kubernetes/pki/sa.pub
+    - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
```
Comment (luxas) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting_test.go]: note; this is all semi-autogenerated code. I just copied the value of the static pod and later what the DaemonSet looked like when initialized in the cluster.

**Comment by luxas** [comment]
Proof of concept:
```console
$ cat kubeadm.yaml
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
featureFlags:
  SelfHosting: true
  StoreCertsInSecrets: true
$ ./kubeadm init --config kubeadm.yaml
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.7.4
[init] Using Authorization mode: [Node RBAC]
[preflight] Running pre-flight checks
[preflight] WARNING: docker service is not enabled, please run 'systemctl enable docker.service'
[preflight] Starting the kubelet service
[kubeadm] WARNING: starting in 1.8, tokens expire after 24 hours by default (if you require a non-expiring token use --token-ttl 0)
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API server serving cert is signed for DNS names [thegopher kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.1.115]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "scheduler.conf"
[init] Waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[apiclient] All control plane components are healthy after 35.001580 seconds
[markmaster] Master thegopher tainted and labelled with key/value: node-role.kubernetes.io/master=""
[token] Using token: 14ea9b.955e5adccad18108
[bootstraptoken] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
[uploadconfig] Storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[addons] Applied essential addon: kube-dns
[addons] Applied essential addon: kube-proxy
[self-hosted] Creating self-hosted control plane...
[self-hosted] Created TLS secret "ca" from ca.crt and ca.key
[self-hosted] Created TLS secret "apiserver" from apiserver.crt and apiserver.key
[self-hosted] Created TLS secret "apiserver-kubelet-client" from apiserver-kubelet-client.crt and apiserver-kubelet-client.key
[self-hosted] Created TLS secret "sa" from sa.pub and sa.key
[self-hosted] Created TLS secret "front-proxy-ca" from front-proxy-ca.crt and front-proxy-ca.key
[self-hosted] Created TLS secret "front-proxy-client" from front-proxy-client.crt and front-proxy-client.key
[self-hosted] Created secret for kubeconfig file "scheduler.conf"
[self-hosted] Created secret for kubeconfig file "controller-manager.conf"
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-apiserver
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-apiserver
[apiclient] The Static Pod "kube-apiserver-thegopher" is now removed
[apiclient] All control plane components are healthy after 5.003202 seconds
[self-hosted] self-hosted kube-apiserver ready after 21.213473 seconds
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-controller-manager
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-controller-manager
[apiclient] The Static Pod "kube-controller-manager-thegopher" is now removed
[apiclient] All control plane components are healthy after 0.003051 seconds
[self-hosted] self-hosted kube-controller-manager ready after 11.492040 seconds
[apiclient] Found 0 Pods for label selector k8s-app=self-hosted-kube-scheduler
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-scheduler
[apiclient] The Static Pod "kube-scheduler-thegopher" is now removed
[apiclient] All control plane components are healthy after 0.002133 seconds
[self-hosted] self-hosted kube-scheduler ready after 10.139675 seconds

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token 14ea9b.955e5adccad18108 192.168.1.115:6443 --discovery-token-ca-cert-hash sha256:8a0c77b434cc2b23d78265fc080dbf3899f2bfee58660efd34ca9047a3c5d118
```

**Comment by luxas** [comment]
And control plane DaemonSets:
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2017-08-18T21:12:14Z
  generation: 1
  labels:
    k8s-app: self-hosted-kube-apiserver
  name: self-hosted-kube-apiserver
  namespace: kube-system
  resourceVersion: "365"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/self-hosted-kube-apiserver
  uid: e84bf79b-8459-11e7-9a8a-f0761c62f136
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: self-hosted-kube-apiserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: self-hosted-kube-apiserver
    spec:
      containers:
      - command:
        - kube-apiserver
        - --insecure-port=0
        - --requestheader-allowed-names=front-proxy-client
        - --service-account-key-file=/etc/kubernetes/pki/sa.pub
        - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
        - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
        - --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt
        - --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --requestheader-username-headers=X-Remote-User
        - --client-ca-file=/etc/kubernetes/pki/ca.crt
        - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
        - --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --service-cluster-ip-range=10.96.0.0/12
        - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
        - --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt
        - --allow-privileged=true
        - --experimental-bootstrap-token-auth=true
        - --advertise-address=192.168.1.115
        - --secure-port=6443
        - --authorization-mode=Node,RBAC
        - --etcd-servers=http://127.0.0.1:2379
        image: gcr.io/google_containers/kube-apiserver-amd64:v1.7.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: kube-apiserver
        resources:
          requests:
            cpu: 250m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/pki
          name: k8s-certs
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
        - mountPath: /etc/pki
          name: ca-certs-etc-pki
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: k8s-certs
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: tls.crt
                path: ca.crt
              name: ca
          - secret:
              items:
              - key: tls.crt
                path: apiserver.crt
              - key: tls.key
                path: apiserver.key
              name: apiserver
          - secret:
              items:
              - key: tls.crt
                path: apiserver-kubelet-client.crt
              - key: tls.key
                path: apiserver-kubelet-client.key
              name: apiserver-kubelet-client
          - secret:
              items:
              - key: tls.crt
                path: sa.pub
              name: sa
          - secret:
              items:
              - key: tls.crt
                path: front-proxy-ca.crt
              name: front-proxy-ca
          - secret:
              items:
              - key: tls.crt
                path: front-proxy-client.crt
              - key: tls.key
                path: front-proxy-client.key
              name: front-proxy-client
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certs
      - hostPath:
          path: /etc/pki
        name: ca-certs-etc-pki
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
```
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2017-08-18T21:12:39Z
  generation: 1
  labels:
    k8s-app: self-hosted-kube-controller-manager
  name: self-hosted-kube-controller-manager
  namespace: kube-system
  resourceVersion: "468"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/self-hosted-kube-controller-manager
  uid: f753bb96-8459-11e7-a88e-f0761c62f136
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: self-hosted-kube-controller-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: self-hosted-kube-controller-manager
    spec:
      containers:
      - command:
        - kube-controller-manager
        - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
        - --address=127.0.0.1
        - --use-service-account-credentials=true
        - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
        - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
        - --leader-elect=true
        - --controllers=*,bootstrapsigner,tokencleaner
        - --kubeconfig=/etc/kubernetes/kubeconfig/controller-manager.conf
        - --root-ca-file=/etc/kubernetes/pki/ca.crt
        image: gcr.io/google_containers/kube-controller-manager-amd64:v1.7.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 10252
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: kube-controller-manager
        resources:
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/pki
          name: k8s-certs
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/pki
          name: ca-certs-etc-pki
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: k8s-certs
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: tls.crt
                path: ca.crt
              - key: tls.key
                path: ca.key
              name: ca
          - secret:
              items:
              - key: tls.key
                path: sa.key
              name: sa
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certs
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: controller-manager.conf
      - hostPath:
          path: /etc/pki
        name: ca-certs-etc-pki
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
```
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2017-08-18T21:12:46Z
  generation: 1
  labels:
    k8s-app: self-hosted-kube-scheduler
  name: self-hosted-kube-scheduler
  namespace: kube-system
  resourceVersion: "494"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/self-hosted-kube-scheduler
  uid: fbca7f6d-8459-11e7-a88e-f0761c62f136
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: self-hosted-kube-scheduler
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: self-hosted-kube-scheduler
    spec:
      containers:
      - command:
        - kube-scheduler
        - --leader-elect=true
        - --kubeconfig=/etc/kubernetes/kubeconfig/scheduler.conf
        - --address=127.0.0.1
        image: gcr.io/google_containers/kube-scheduler-amd64:v1.7.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /healthz
            port: 10251
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: kube-scheduler
        resources:
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/kubeconfig
          name: kubeconfig
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: scheduler.conf
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
```

File: cmd/kubeadm/app/phases/selfhosting/podspec_mutation.go [hunk 4]
```diff
@@ -73,38 +85,68 @@ func setMasterTolerationOnPodSpec(cfg *kubeadmapi.MasterConfiguration, podSpec *
...
+	for i, vm := range podSpec.Containers[0].VolumeMounts {
+		if vm.Name == kubeadmconstants.KubeConfigVolumeName {
+			podSpec.Containers[0].VolumeMounts[i].MountPath = selfHostedKubeConfigDir
+		}
 	}
+
+	// Rewrite the --kubeconfig path as the volume mount path may not overlap with certs dir, which it does by default (/etc/kubernetes and /etc/kubernetes/pki)
+	// This is not a problem with hostPath mounts as hostPath supports mounting one file only, instead of always a full directory. Secrets and Projected Volumes
+	// don't support that.
+	podSpec.Containers[0].Command = kubeadmutil.ReplaceArgument(podSpec.Containers[0].Command, func(argMap map[string]string) map[string]string {
```
Comment (andrewrynhard) [inline cmd/kubeadm/app/phases/selfhosting/podspec_mutation.go]: I would like to see this `argMap` function eventually defined as a type since it it used in multiple places.

File: cmd/kubeadm/app/phases/selfhosting/selfhosting.go [hunk 5]
```diff
@@ -53,13 +56,23 @@ const (
 // 9. Do that for the kube-apiserver, kube-controller-manager and kube-scheduler in a loop
 func CreateSelfHostedControlPlane(cfg *kubeadmapi.MasterConfiguration, client clientset.Interface) error {
 
+	// Here the map of different mutators to use for the control plane's podspec is stored
+	mutators := getDefaultMutators()
+
+	// Some extra work to be done if we should store the control plane certificates in Secrets
 	if features.Enabled(cfg.FeatureFlags, features.StoreCertsInSecrets) {
```
Comment (andrewrynhard) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting.go]: 👍

**Review by andrewrynhard — APPROVED** [review]
@luxas I have only one nit, but other than that I like the direction we are going with this.

**Comment by luxas** [comment]
Thanks @andrewrynhard for the review! Adding the LGTM label.
Could you please file an issue in the kubeadm repo with cleanup/enhancement work of this for v1.9?
It's still alpha and everything -- so this might yet change somewhat.
