### PR TITLE
GCE: Fix operation polling and error handling

### LINKED ISSUE #64712: GCE: Operation ratelimiting does not poll on an interval
/kind bug

**What happened**:
When the service controller with the GCE cloudprovider creates resources, it polls GCP for the status of the operation. The polling interval was replaced with a token bucket ratelimiter; we actually need both an interval and ratelimiter.

As a result, API calls to GCP may burst unnecessarily.

**What you expected to happen**:
Operations should be polled on a set interval or later if QPS is constrained.

### LINKED ISSUE #64858: GCE: Call operations are not checked for errors
/kind bug

**What happened**:
1. Create a manual network and subnetwork
2. Attempt to delete the network using the generated cloud client.
3. Observe that the call will return err=nil
4. Observe that the network still exists.

The final operation indicated an error occurred but the client did not say that.
```
{
        "endTime": "2018-06-06T15:27:36.717-07:00",
        "error": {
                "errors": [
                        {
                                "code": "RESOURCE_IN_USE_BY_ANOTHER_RESOURCE",
                                "message": "The network resource 'projects/XXXXXXXXX/global/networks/XXXXXX' is already being used by 'projects/XXXXXX/regions/us-central1/subnetworks/XXXXXXXXX'"
                        }
                ]
        },
        "httpErrorMessage": "BAD REQUEST",
        "httpErrorStatusCode": 400,
        "id": "4694915146768048441",
        "insertTime": "2018-06-06T15:27:34.259-07:00",
        "kind": "compute#operation",
        "name": "operation-1528324053977-56e00ac56c7a8-98b57bfc-98d05a88",
        "operationType": "delete",
        "progress": 100,
        "startTime": "2018-06-06T15:27:34.937-07:00",
        "status": "DONE",
        "targetId": "2241447505930421231",
```

/sig gcp
/assign nicksardo bowei
/cc @MrHohn @rramkumar1

### PR DESCRIPTION
**Pull request by nicksardo**
Cloud functions using the generated API are bursting operation GET calls because we don't wait a minimum amount of time.

Fixes #64712
Fixes #64858

**Changes**
- `operationPollInterval` is now 1 second instead of 3 seconds.
-  `operationPollRateLimiter` is now configured with 5 QPS / 5 burst instead of 10 QPS / 10 burst.
- `gceRateLimiter` is now configured with a `MinimumRateLimiter` to wait the above `operationPollInterval` duration _before_ waiting on the token rate limiter.
- Operations are now rate limited on the very first GET call.
- Operations are polled until `DONE` or context times out (even if operations.get fails continuously).
- Compute operations are checked for errors when they're recognized as `DONE`. 
- All "wrapper" funcs now generate a context with an hour timeout.

`ingress-gce` will need to update its vendor and utilize the `MinimumRateLimiter` as well. Since ingress creates rate limiters based off flags, we'll need to check the resource type and operation while parsing the flags and wrap the appropriate one.

**Special notes for your reviewer**:
/assign bowei
/cc bowei

**Fix Example**
Creating an external load balancer

without fix:  https://pastebin.com/raw/NNkeNWS3  
with fix: https://pastebin.com/raw/x2iMLW5S (a difference of about 200 GET calls)

**Release note**:
```release-note
GCE: Fixes operation polling to adhere to the specified interval. Furthermore, operation errors are now returned instead of ignored.
```

### CODE REVIEW

**Comment by nicksardo** [comment]
On second thought, this will delay accept on the first call for the operation.

**Comment by nicksardo** [comment]
> On second thought, this will delay Accept on the first call for the operation, which is not ideal. Especially since the operation poll interval is 3 seconds.
Correction, the first call does not currently wait for the ratelimiter. 

Furthermore, the more I think about this implementation, the more unhappy I am that the taking of token does not correlate to when the API call is actually made. Will re-write this...

**Comment by nicksardo** [comment]
My first implementation had the minimum timer and ratelimiter blocking concurrently. Seems that sequentially blocking on the minimum, then on the ratelimiter is more appropriate. 

Working on incorporating https://github.com/kubernetes/kubernetes/pull/64886 since they collide on unit testing.

File: pkg/cloudprovider/providers/gce/cloud/ratelimit.go [hunk 1]
```diff
@@ -47,22 +47,55 @@ type RateLimiter interface {
 	Accept(ctx context.Context, key *RateLimitKey) error
 }
 
+// Acceptor is the interface for objects which Accept.
+type Acceptor interface {
+	Accept()
+}
+
+// AcceptRateLimiter wraps an Acceptor with RateLimiter parameters.
```
Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/cloud/ratelimit.go]: TODO: fix this comment

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 2]
```diff
@@ -27,6 +27,10 @@ import (
 	ga "google.golang.org/api/compute/v1"
 )
 
+const (
+	maxOperationGetErrorStreak = 50
```
Comment (rramkumar1) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: I would call this maxConsecutiveOperationGetErrors

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 3]
```diff
@@ -72,14 +76,49 @@ func (s *Service) WaitForCompletion(ctx context.Context, genericOp interface{})
...
-			return err
+
+	return s.pollOperation(ctx, op)
+}
+
+// pollOperation calls operations.isDone until the function comes back true or context is Done.
+// If an error occurs retrieving the operation, the loop will continue for `maxOpGetRetries` then
+// finally error. This is to prevent a transient error from bubbling up to controller-level logic.
+func (s *Service) pollOperation(ctx context.Context, op operation) error {
+	var errorStreak int
```
Comment (rramkumar1) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: consecutiveErrors

File: pkg/cloudprovider/providers/gce/cloud/service.go (hunk 2 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/cloud/service.go]: Sure

File: pkg/cloudprovider/providers/gce/cloud/errors.go [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+	LastPollError error
+}
+
+func (e OperationPollingError) Error() string {
+	return fmt.Sprintf("GCE operation polling error: %v", e.LastPollError)
+}
+
+// GCEOperationError occurs when the GCE Operation finishes with an error.
+type GCEOperationError struct {
+	HTTPStatusCode int
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/errors.go]: comments

File: pkg/cloudprovider/providers/gce/cloud/errors.go [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+package cloud
+
+import "fmt"
+
+// OperationPollingError occurs when the GCE Operation cannot be retrieved for a prolonged period.
+type OperationPollingError struct {
+	LastPollError error
+}
+
+func (e OperationPollingError) Error() string {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/errors.go]: Error returns ...

File: pkg/cloudprovider/providers/gce/cloud/op.go [hunk 6]
```diff
@@ -71,7 +78,15 @@ func (o *gaOperation) isDone(ctx context.Context) (bool, error) {
 	if err != nil {
 		return false, err
 	}
-	return op != nil && op.Status == "DONE", nil
+	if op == nil || op.Status != operationStatusDone {
+		return false, nil
+	}
+
+	if op.Error != nil && len(op.Error.Errors) > 0 && op.Error.Errors[0] != nil {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/op.go]: would op.Error.Errors[0] ever == nil?

File: pkg/cloudprovider/providers/gce/cloud/op.go [hunk 7]
```diff
@@ -83,10 +98,15 @@ func (o *gaOperation) rateLimitKey() *RateLimitKey {
 	}
 }
 
+func (o *gaOperation) isError() error {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/op.go]: isX usually returns a bool

File: pkg/cloudprovider/providers/gce/cloud/ratelimit.go [hunk 8]
```diff
@@ -47,22 +47,56 @@ type RateLimiter interface {
 	Accept(ctx context.Context, key *RateLimitKey) error
 }
 
+// Acceptor is an object which block within Accept until a call is allowed to run.
+// Accept is a behavior of the flowcontrol.RateLimiter interface.
+type Acceptor interface {
+	Accept()
+}
+
+// AcceptRateLimiter wraps an Acceptor with RateLimiter parameters.
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/ratelimit.go]: does this need to be exported?

File: pkg/cloudprovider/providers/gce/cloud/ratelimit.go [hunk 9]
```diff
@@ -47,22 +47,56 @@ type RateLimiter interface {
 	Accept(ctx context.Context, key *RateLimitKey) error
 }
 
+// Acceptor is an object which block within Accept until a call is allowed to run.
+// Accept is a behavior of the flowcontrol.RateLimiter interface.
+type Acceptor interface {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/ratelimit.go]: does this need to be exported?

File: pkg/cloudprovider/providers/gce/cloud/ratelimit_test.go [hunk 10]
```diff
@@ -0,0 +1,80 @@
+/*
+Copyright 2017 The Kubernetes Authors.
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/ratelimit_test.go]: year

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 11]
```diff
@@ -27,6 +27,13 @@ import (
 	ga "google.golang.org/api/compute/v1"
 )
 
+const (
+	// maxConsecutiveOperationGetErrors is the number of failed attempts an operation GET will be
+	// attempted. In terms of time, this is 50 * (pollingInterval + callDuration). Assuming
+	// pollingInterval=1.5s, callDuration=100ms: the max tolerated outage is 80 seconds.
+	maxConsecutiveOperationGetErrors = 50
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: why not specify this in time.Duration and do that math in the code?

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 12]
```diff
@@ -72,14 +79,50 @@ func (s *Service) WaitForCompletion(ctx context.Context, genericOp interface{})
...
+			// ctx is not canceled, continue immediately
 		}
+
 		glog.V(5).Infof("op.isDone(%v) waiting; op = %v", ctx, op)
 		s.RateLimiter.Accept(ctx, op.rateLimitKey())
+
+		done, err := op.isDone(ctx)
+		if err != nil {
+			if consecutiveErrors >= maxConsecutiveOperationGetErrors {
+				glog.Errorf("op.isDone(%v) error; errorStreak = %v/%v op = %v, final err = %v, ", ctx, consecutiveErrors, maxConsecutiveOperationGetErrors, op, err)
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: errorStreak is not a variable, can write just "error streak"

File: pkg/cloudprovider/providers/gce/cloud/service_test.go [hunk 13]
```diff
@@ -0,0 +1,84 @@
+/*
+Copyright 2017 The Kubernetes Authors.
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service_test.go]: year

File: pkg/cloudprovider/providers/gce/cloud/op.go (hunk 6 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/cloud/op.go]: I wouldn't bet on it.

File: pkg/cloudprovider/providers/gce/cloud/ratelimit.go (hunk 8 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/cloud/ratelimit.go]: Yes.

File: pkg/cloudprovider/providers/gce/cloud/ratelimit.go (hunk 9 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/cloud/ratelimit.go]: This could probably be private.

File: pkg/cloudprovider/providers/gce/cloud/service.go (hunk 11 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/cloud/service.go]: To avoid unit testing with time or importing a clock implementation.

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 14]
```diff
@@ -72,14 +72,39 @@ func (s *Service) WaitForCompletion(ctx context.Context, genericOp interface{})
...
+			// ctx is not canceled, continue immediately
 		}
-		glog.V(5).Infof("op.isDone(%v) waiting; op = %v", ctx, op)
+
+		pollCount++
+		glog.V(5).Infof("op.isDone(%v) waiting; op = %v, poll count = %v", ctx, op, pollCount)
 		s.RateLimiter.Accept(ctx, op.rateLimitKey())
+		done, err := op.isDone(ctx)
+		if err != nil {
+			glog.V(5).Infof("op.isDone(%v) error; op = %v, poll count = %v, err = %v, retrying", ctx, op, pollCount, err)
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: use %d for ints

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 15]
```diff
@@ -72,14 +72,39 @@ func (s *Service) WaitForCompletion(ctx context.Context, genericOp interface{})
...
+// If an error occurs retrieving the operation, the loop will continue until the context is done.
+// This is to prevent a transient error from bubbling up to controller-level logic.
+func (s *Service) pollOperation(ctx context.Context, op operation) error {
+	var pollCount int
+	for {
+		// Check if context has been cancelled. Note that ctx.Done() must be checked before
+		// returning ctx.Err().
+		select {
+		case <-ctx.Done():
+			glog.V(5).Infof("op.pollOperation(%v, %v) not completed, poll count = %v, ctx.Err = %v", ctx, op, pollCount, ctx.Err())
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: use %d for ints

File: pkg/cloudprovider/providers/gce/cloud/service.go [hunk 16]
```diff
@@ -72,14 +72,39 @@ func (s *Service) WaitForCompletion(ctx context.Context, genericOp interface{})
...
+		}
+
+		if done {
+			break
+		}
 	}
-	glog.V(5).Infof("op.isDone(%v) complete; op = %v", ctx, op)
-	return nil
+
+	glog.V(5).Infof("op.isDone(%v) complete; op = %v, poll count = %v, op.err = %v", ctx, op, pollCount, op.error())
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service.go]: use %d for ints

File: pkg/cloudprovider/providers/gce/cloud/service_test.go [hunk 17]
```diff
@@ -0,0 +1,83 @@
...
+package cloud
+
+import (
+	"context"
+	"fmt"
+	"testing"
+)
+
+func TestPollOperation(t *testing.T) {
+	var attempts int
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service_test.go]: const totalAttempts = 11

File: pkg/cloudprovider/providers/gce/cloud/service_test.go [hunk 18]
```diff
@@ -0,0 +1,83 @@
...
+	fo := &fakeOperation{isDoneFunc: func(ctx context.Context) (bool, error) {
+		if attempts <= 10 {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service_test.go]: < totalAttemps

File: pkg/cloudprovider/providers/gce/cloud/service_test.go [hunk 19]
```diff
@@ -0,0 +1,83 @@
...
+		return true, nil
+	}}
+	s := Service{RateLimiter: &NopRateLimiter{}}
+	// Check that pollOperation will retry the operation multiple times.
+	err := s.pollOperation(context.Background(), fo)
+	if err != nil {
+		t.Errorf("pollOperation() = %v, want nil", err)
+	}
+	if attempts != 11 {
+		t.Errorf("`attempts` = %v, want 11", attempts)
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/cloud/service_test.go]: want %d", ..., totalAttempts

File: pkg/cloudprovider/providers/gce/cloud/op.go [hunk 20]
```diff
@@ -71,7 +79,15 @@ func (o *gaOperation) isDone(ctx context.Context) (bool, error) {
...
-	return op != nil && op.Status == "DONE", nil
+	if op == nil || op.Status != operationStatusDone {
+		return false, nil
+	}
+
+	if op.Error != nil && len(op.Error.Errors) > 0 && op.Error.Errors[0] != nil {
+		e := op.Error.Errors[0]
+		o.err = &GCEOperationError{HTTPStatusCode: op.HTTPStatusCode, Code: e.Code, Message: e.Message}
+	}
+	return true, nil
```
Comment (anfernee) [inline pkg/cloudprovider/providers/gce/cloud/op.go]: Lots of these code are very similar. actually you can embed a struct with an `error` method. When I wrote this, I realized that it also applies to `String()` and `isDone()`. feel free to ignore, totally optional. maybe i will submit a PR later.
