### PR TITLE
Fix nil pointer

### LINKED ISSUE #78996: PVC DataSource doesn't check for nil APIGroup
**What happened**:
While implementing the new VolumePVCDataSource feature I discovered that even though the we don't use APIGroup (the appropriate setting is `""`) if the APIGroup is omitted it results in a nil pointer exception on the API server.

**What you expected to happen**:
APIGroup should be able to be omitted from the spec 

**How to reproduce it (as minimally and precisely as possible)**:
Create a spec to create a clone of a PVC with out the APIGroup parameter in the DataSource spec:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hp-pvc-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: src-hp-pvc
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
The result will be an nil pointer exception during the verification of the datasource field.

Adding the APIGroup entry will address this as a work-around:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hp-pvc-clone
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: src-hp-pvc
    kind: PersistentVolumeClaim
    apiGroup: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.1.33084+d873167e8f816f-dirty", GitCommit:"d873167e8f816f5f83846bc4587c3047452293bd", GitTreeState:"dirty", BuildDate:"2019-06-12T22:12:02Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Install tools:

local-up-cluster.sh

### PR DESCRIPTION
**Pull request by j-griffith**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
Check DataSource parameters before trying to access their values.

**Which issue(s) this PR fixes**:
Fixes #78996

```release-note
NONE
```

### CODE REVIEW

File: pkg/api/persistentvolumeclaim/util.go [hunk 1]
```diff
@@ -60,14 +60,18 @@ func dataSourceInUse(oldPVCSpec *core.PersistentVolumeClaimSpec) bool {
...
 func dataSourceIsEnabled(pvcSpec *core.PersistentVolumeClaimSpec) bool {
 	if pvcSpec.DataSource != nil {
+		apiGroup := ""
+		if pvcSpec.DataSource.APIGroup != nil {
+			apiGroup = *pvcSpec.DataSource.APIGroup
+		}
 		if pvcSpec.DataSource.Kind == pvc &&
-			*pvcSpec.DataSource.APIGroup == "" &&
+			apiGroup == "" &&
 			utilfeature.DefaultFeatureGate.Enabled(features.VolumePVCDataSource) {
```
Comment (msau42) [inline pkg/api/persistentvolumeclaim/util.go]: I have a slight preference to check the feature gate first.  That way in non-alpha clusters, the nil deref would have been skipped.

Comment (j-griffith) [reply pkg/api/persistentvolumeclaim/util.go]: Good catch, updated.

**Comment by msau42** [comment]
/lgtm
/priority critical-urgent

You can hit this in a non-alpha cluster and crash the api server. We should backport this to 1.15 asap

**Comment by liggitt** [comment]
Please add a test that would have caught this

**Comment by liggitt** [comment]
This will likely merge post-thaw and need to be picked to the release-1.15 branch. Will verify once this merges

**Comment by j-griffith** [comment]
> Please add a test that would have caught this (with and without the feature gate enabled)

@liggitt Oops, somehow dropped the commit that had the unit test addition, updated with test for both cases, thanks.

**Comment by liggitt** [comment]
/approve

please squash commits, then lgtm

**Comment by liggitt** [comment]
since master is backed up with thawed PRs, went ahead and picked this to 1.15

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/kubernetes/pull/79039

**Comment by tpepper** [comment]
@kubernetes/patch-release-team

**Comment by liggitt** [comment]
> @kubernetes/patch-release-team

note that this is targeting v1.15.0
