### PR TITLE
Daemon Set Conformance test fails in CI process using ci-kubernetes-c…

### LINKED ISSUE #75348: Daemon Set Conformance test fails on Kind Cluster using ci-kubernetes-conformance-image job.
**What happened**:
When running conformance test suite using ci-kubernetes-conformance-image job in the CI process the following test fails as it tries to calculate the number of worker nodes incorrectly.
[sig-apps] Daemon set [Serial] should rollback without unnecessary restarts [Conformance] 

**What you expected to happen**:
The test must read the number nodes correctly so that the checks in the test will pass
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:425

**How to reproduce it (as minimally and precisely as possible)**:
Run the  ci-kubernetes-conformance-image in a docker container to initiate the 2 node cluster using ./../test-infra/experiment/kind-conformance-e2e.sh

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: amd64

/sig testing
/area conformance
/kind test
/release-note-none
/sig apps

### PR DESCRIPTION
**Pull request by brahmaroutu**
…onformance-image as the num nodes is calculates incorrectly by the test context.

This will fixe the issue with bug #75348 where the num nodes is calculated incorrectly.
/sig testing
/area conformance
/kind test
/release-note-none
/sig apps

ping @neolit123 @dims 

EDIT(spiffxp)
Fixes #75348

### CODE REVIEW

File: test/e2e/apps/daemon_set.go [hunk 1]
```diff
@@ -381,7 +381,8 @@ var _ = SIGDescribe("Daemon set [Serial]", func() {
 	  rollback of updates to a DaemonSet.
 	*/
 	framework.ConformanceIt("should rollback without unnecessary restarts", func() {
-		if framework.TestContext.CloudConfig.NumNodes < 2 {
+		schedulableNodes := framework.GetReadySchedulableNodesOrDie(c)
+		if len(schedulableNodes.Items) < 2 {
 			framework.Logf("Conformance test suite needs a cluster with at least 2 nodes.")
```
Comment (neolit123) [inline test/e2e/apps/daemon_set.go]: so here according to the k8s conformance we should just fail. 1 node clusters are not conformant.
to do that you can do:
```
schedulableNodes := framework.GetReadySchedulableNodesOrDie(c)
Expect(llen(schedulableNodes.Items)).To(BeNumerically(">", 1), "Conformance test suite needs a cluster with at least 2 nodes.")
```
^ untested.

File: test/e2e/apps/daemon_set.go [hunk 2]
```diff
@@ -421,7 +422,7 @@ var _ = SIGDescribe("Daemon set [Serial]", func() {
 				framework.Failf("unexpected pod found, image = %s", image)
 			}
 		}
-		if framework.TestContext.CloudConfig.NumNodes < 2 {
+		if len(schedulableNodes.Items) < 2 {
```
Comment (neolit123) [inline test/e2e/apps/daemon_set.go]: we should do this again:
```
schedulableNodes = framework.GetReadySchedulableNodesOrDie(c)
if len(schedulableNodes.Items) < 2 {
...
```

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @brahmaroutu 
added a couple of comments.

/hold
/assign @timothysc @dims @spiffxp
/priority critical-urgent
/kind failing-test

please note that given the conformance test runs against 1.14 this change will first have to be fast-forwarded from the master branch.

**Comment by neolit123** [comment]
/release-note-none

^ ?

**Comment by neolit123** [comment]
cc @kargakis
we tried adding code that automatically populates `framework.TestContext.CloudConfig.NumNodes` when the framework inits, but something in the pipeline changes that and this test receives a different value.

**Comment by neolit123** [comment]
@brahmaroutu 
please add `Fixes #75348` in the PR body.

File: test/e2e/apps/daemon_set.go (hunk 1 above)
Comment (brahmaroutu) [reply test/e2e/apps/daemon_set.go]: fixed differently,  for the test to run on a single node we need '>=1'

File: test/e2e/apps/daemon_set.go (hunk 2 above)
Comment (brahmaroutu) [reply test/e2e/apps/daemon_set.go]: fixed, thanks for the review

File: test/e2e/apps/daemon_set.go [hunk 3]
```diff
@@ -381,9 +381,8 @@ var _ = SIGDescribe("Daemon set [Serial]", func() {
 	  rollback of updates to a DaemonSet.
 	*/
 	framework.ConformanceIt("should rollback without unnecessary restarts", func() {
-		if framework.TestContext.CloudConfig.NumNodes < 2 {
-			framework.Logf("Conformance test suite needs a cluster with at least 2 nodes.")
-		}
+		schedulableNodes := framework.GetReadySchedulableNodesOrDie(c)
+		Expect(len(schedulableNodes.Items)).To(BeNumerically(">=", 1), "Conformance test suite needs a cluster with at least 2 nodes.")
```
Comment (neolit123) [inline test/e2e/apps/daemon_set.go]: as pointed here:
https://github.com/kubernetes/kubernetes/pull/75349#discussion_r265383690

this test should just fail on <2 nodes.
AFAIK, a <2 nodes cluster is not a conformant cluster.

cc @timothysc

Comment (johnSchnake) [reply test/e2e/apps/daemon_set.go]: I thought conformance should be about behavior, why wouldnt we want to mark a "cluster" as conformant if everything is wired and deployed the right way but just happens to have one node?

I can't find anything in the CNCF conformance docs or a brief link-walk of related documents (k8s architectural roadmap, conformance profiles, etc) that mentions the # of nodes being a requirement.

But would that mean we should start allowing skips in conformance tests if that is the case?

Comment (neolit123) [reply test/e2e/apps/daemon_set.go]: TMK, this was a decision from the CNCF and k8s-conformance working group.
i can write a short essee why this is wrong...believe me.

there is also a slack channel #k8s-conformance

Comment (neolit123) [reply test/e2e/apps/daemon_set.go]: as confirmed today on slack at least 2 schedulable nodes are need @brahmaroutu 
please change to `BeNumerically(">", 1)`

https://kubernetes.slack.com/archives/C78F00H99/p1552659823201600

**Review by neolit123 — COMMENTED** [review]
/lgtm
/retest

EDIT: i guess we need this too:
https://github.com/kubernetes/test-infra/issues/11814

**Comment by dims** [comment]
@spiffxp @brahmaroutu should we backport this to 1.14 branch?
