### PR TITLE
test/e2e/node: fix selinux test failure

### LINKED ISSUE #87901: Tests in selinux security_context are failing
Tests in https://testgrid.k8s.io/google-gce#gci-gce-flaky&sort-by-flakiness=&width=20&include-filter-by-regex=SELinux are failing because they are faulty.

A container can't read from a file if it has selinux permission denied for it.

More context - https://github.com/kubernetes/kubernetes/pull/87658#issuecomment-582407413

/sig node
/sig storage

### PR DESCRIPTION
**Pull request by kolyshkin**
_(this is a carry of #88145, some initial discussion is in there)_

Commit 69a473be3 broke the test case (that was checking
that a file from a volume can't be read) by adding a
(wrong) assumption that error should be nil.

Fix the assumption (we *do* expect the error here).
Note that we were checking file contents before; now when
we check the error from read, checking the contents is
redundant.

The other issue with the test is SELinux should be in enforcing
mode for this to work, so let's check that first to avoid
false positives.

While at it, add test case description (`gingko.By()`).

/kind failing-test
fixes #87901

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for fixing!

File: test/e2e/node/security_context.go [hunk 1]
```diff
@@ -269,7 +270,10 @@ func testPodSELinuxLabeling(f *framework.Framework, hostIPC bool, hostPID bool)
 	err = f.WaitForPodRunning(pod.Name)
 	framework.ExpectNoError(err, "Error waiting for pod to run %v", pod)
 
-	content, err = tk.ReadFileViaContainer(pod.Name, "test-container", testFilePath)
-	framework.ExpectNoError(err, "Error reading file via container")
-	gomega.Expect(content).NotTo(gomega.ContainSubstring(testContent))
+	// for this to work, SELinux should be in enforcing mode, so let's check that
+	isEnforced, err := tk.ReadFileViaContainer(pod.Name, "test-container", "/sys/fs/selinux/enforce")
```
Comment (oomichi) [inline test/e2e/node/security_context.go]: I guess `err != nil` case is intentionally ignored here.
It is necessary to add comment which explains why here to avoid adding `err != nil` check in the future.

File: test/e2e/node/security_context.go [hunk 2]
```diff
@@ -252,10 +252,11 @@ func testPodSELinuxLabeling(f *framework.Framework, hostIPC bool, hostPID bool)
 	pod.Spec.SecurityContext.SELinuxOptions = &v1.SELinuxOptions{
 		Level: "s0:c0,c1",
 	}
-
```
Comment (oomichi) [inline test/e2e/node/security_context.go]: nit: unrelated change.

File: test/e2e/node/security_context.go [hunk 3]
```diff
@@ -252,10 +252,11 @@ func testPodSELinuxLabeling(f *framework.Framework, hostIPC bool, hostPID bool)
...
 	f.TestContainerOutput("Pod with same MCS label reading test file", pod, 0, []string{testContent})
+
```
Comment (oomichi) [inline test/e2e/node/security_context.go]: ditto

**Review by oomichi — COMMENTED** [review]
/cc @oomichi

File: test/e2e/node/security_context.go (hunk 1 above)
Comment (kolyshkin) [reply test/e2e/node/security_context.go]: Yes, if we get error reading this file, we assume that selinux is not in enforced mode, and skip the test.

Perhaps we could use something like this instead?
```go
isEnforced, _ := tk.ReadFile...
if isEnforced == "1" {
...
```

@oomichi Let me know if that's OK with you.

File: test/e2e/node/security_context.go (hunk 3 above)
Comment (kolyshkin) [reply test/e2e/node/security_context.go]: This one is actually related. As I wrote in commit message, I am also trying to improve readability for this particular piece of code, thus the empty line (to distinguish this is a separate test case).

File: test/e2e/node/security_context.go (hunk 2 above)
Comment (kolyshkin) [reply test/e2e/node/security_context.go]: this *is* related. The `f.TestContainerOutput` call is related to the test case above, not below, but the vertical whitespace suggested otherwise, so I fixed it.

In other words, it was like that before:
```go
        pod.Spec.SecurityContext.SELinuxOptions = &v1.SELinuxOptions{
                Level: "s0:c0,c1",
        }

[1]     f.TestContainerOutput("Pod with same MCS label reading test file", pod, 0, []string{testContent})
[2]     // Confirm that the same pod with a different MCS
        // label cannot access the volume
```

In the above snippet, `[1]` marks the end of the previous test case, and `[2]` marks the beginning of a new test case.

After my changes, it looks like this:
```go
        pod.Spec.SecurityContext.SELinuxOptions = &v1.SELinuxOptions{
                Level: "s0:c0,c1",
        }
[1]     f.TestContainerOutput("Pod with same MCS label reading test file", pod, 0, []string{testContent})

[2]     // Confirm that the same pod with a different MCS
        // label cannot access the volume
```

Hope that makes sense

File: test/e2e/node/security_context.go (hunk 1 above)
Comment (oomichi) [reply test/e2e/node/security_context.go]: I guess the best way is `No such file or directory` error is handled as ignored and the other `err` leads an exception.

Comment (kolyshkin) [reply test/e2e/node/security_context.go]: Not sure what you mean by exception -- `f,Failf("can't read file: %v", err)`?

In both cases, I guess, we have to skip the test (rather than fail it), which is what the current code does.

I'll add error reporting

File: test/e2e/node/security_context.go (hunk 2 above)
Comment (kolyshkin) [reply test/e2e/node/security_context.go]: @oomichi  ^^^

File: test/e2e/node/security_context.go (hunk 1 above)
Comment (kolyshkin) [reply test/e2e/node/security_context.go]: Oh well, the error is actually already logged by `tk.ReadFileViaContainer()` itself, so I'm not sure what else to do here.

Comment (kolyshkin) [reply test/e2e/node/security_context.go]: except maybe what I suggested [above](https://github.com/kubernetes/kubernetes/pull/88247#discussion_r381026024), i.e. ignoring the error in a more straightforward way

**Comment by pdhung** [comment]
@kolyshkin: will you cherry-pick this PR back to 1.16 and 1.17?

**Comment by kolyshkin** [comment]
> @kolyshkin: will you cherry-pick this PR back to 1.16 and 1.17?

@pdhung done:
* 1.16: https://github.com/kubernetes/kubernetes/pull/88247
* 1.17: https://github.com/kubernetes/kubernetes/pull/88352

although I'm lost as what to do wrt complaints about missing release note labels :(
