### PR TITLE
e2e: access nodes via a test container

### LINKED ISSUE #90047: ESIPP [Slow] should handle updates to ExternalTrafficPolicy field is failing in 5k-node tests
Example failure:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1248219443285200896

Stacktrace:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3067
Test Panicked
/usr/local/go/src/runtime/panic.go:75

Panic: runtime error: index out of range [0] with length 0

Full stack:
k8s.io/kubernetes/test/e2e/network.glob..func22.7()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3117 +0x11f9
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc001f12700)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x324
k8s.io/kubernetes/test/e2e.TestE2E(0xc001f12700)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:119 +0x2b
testing.tRunner(0xc001f12700, 0x4b56120)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
```

The problem seem to be related to the fact that we're running the test on private cluster (nodes doesn't have external IP address).

@mm4tt @kubernetes/sig-network-bugs @kubernetes/sig-scalability-bugs

### PR DESCRIPTION
**Pull request by knight42**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

currently we expect public IPs on the nodes in NetLB tests, but this requirement is not always met. As a result, we decide to access nodes via a test container.

**Which issue(s) this PR fixes**:

Fixes #90047 

**Special notes for your reviewer**:

@wojtek-t I am not sure if the updated test is equivalent to the previous one and I think I need a thorough review since I might not have a complete picture of the tests, any advices are welcome.

In addition, I only migrate one test this time for debugging. If it works, I will continue to migrate the remain tests involved in #90171.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/assign @mm4tt 
As he was doing similar things for other tests.

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -3282,42 +3280,60 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
 			framework.Failf("Service HealthCheck NodePort still present")
 		}
 
-		endpointNodeMap, err := jig.GetEndpointNodes()
+		config := e2enetwork.NewNetworkingTestConfig(f, false, false)
+
+		epNodes, err := jig.GetEndpointNodeNames()
 		framework.ExpectNoError(err)
+		endpointNodeMap := make(map[string][]string)
```
Comment (mm4tt) [inline test/e2e/network/service.go:3287]: Given that we only store InternalIp, cannot we make this `map[string]string`?
Adding a line of comment what these to maps hold would be nice (map from node name to internal ip)

File: test/e2e/framework/network/utils.go [hunk 2]
```diff
@@ -334,6 +339,44 @@ func (config *NetworkingTestConfig) GetEndpointsFromContainer(protocol, containe
 	return eps, nil
 }
 
+// GetResponsesFromTestContainer executes a curl via kubectl exec in a test container.
+func (config *NetworkingTestConfig) GetResponsesFromTestContainer(protocol, dialCommand, targetIP string, targetPort, tries int) []NetexecDialResponse {
+	ipPort := net.JoinHostPort(config.TestContainerPod.Status.PodIP, strconv.Itoa(testContainerHTTPPort))
+	// The current versions of curl included in CentOS and RHEL distros
```
Comment (mm4tt) [inline test/e2e/framework/network/utils.go:345]: There is a lot of copy-pasting here from the `DialFromContainer`. Moreover, you don't seem to be calling this method with `tries` set to other value than `1`. Give that, I'd suggest the following. Get rid of the tries parameter here and change the return type to return a single `NetexecDialResponse` (also change a new of the method to singular -> `GetResponseFromTestContainer`). Then use this method in the `DialFromContainer` to implement a single try. It would make the code cleaner (less repetitions)

File: test/e2e/network/service.go [hunk 3]
```diff
@@ -3282,42 +3280,60 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
-			GetHTTPContent(nodeIPs[0], svcNodePort, e2eservice.KubeProxyLagTimeout, path)
+			ginkgo.By(fmt.Sprintf("Checking %v (%v:%v/%v) proxies to endpoints on another node", nodeName, nodeIPs[0], svcNodePort, dialCmd))
+			GetHTTPContentFromTestContainer(config, nodeIPs[0], svcNodePort, e2eservice.KubeProxyLagTimeout, dialCmd)
 		}
 
 		for nodeName, nodeIPs := range endpointNodeMap {
 			ginkgo.By(fmt.Sprintf("checking kube-proxy health check fails on node with endpoint (%s), public IP %s", nodeName, nodeIPs[0]))
-			var body bytes.Buffer
+			var body string
 			pollfn := func() (bool, error) {
```
Comment (mm4tt) [inline test/e2e/network/service.go:3316]: This retry logic looks awfully similar to the `GetHTTPContentFromTestContainer` logic. Cannot you just call `GetHTTPContentFromTestContainer` here?

**Review by mm4tt — COMMENTED** [review]
/ok-to-test

File: test/e2e/network/service.go (hunk 3 above)
Comment (knight42) [reply test/e2e/network/service.go:3316]: I guess we cannot just call `GetHTTPContentFromTestContainer` here, since the retry logic here is slightly different from `GetHTTPContentFromTestContainer`. It expects error here while `GetHTTPContentFromTestContainer` expects success response.

**Comment by knight42** [comment]
@mm4tt please take another look

File: test/e2e/network/service.go [hunk 4]
```diff
@@ -3248,8 +3247,7 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
 		}
 	})
 
-	// TODO: Get rid of [DisabledForLargeClusters] tag when issue #90047 is fixed.
-	ginkgo.It("should handle updates to ExternalTrafficPolicy field [DisabledForLargeClusters]", func() {
+	ginkgo.It("should handle updates to ExternalTrafficPolicy field", func() {
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3250]: Please don't mix removing the "DisabledForLargeCluster" tag together with changes of the test.
We should enable it independently from the chances to the test.

Comment (knight42) [reply test/e2e/network/service.go:3250]: oh I thought this test was skipped because of this tag, will add it back.

Comment (knight42) [reply test/e2e/network/service.go]: fixed

Comment (wojtek-t) [reply test/e2e/network/service.go]: It is skipped because of this tag. But this is conscious - I don't want to enable it togehter with the changes.

File: test/e2e/framework/network/utils.go (hunk 2 above)
Comment (mm4tt) [reply test/e2e/framework/network/utils.go:345]: I see you made the changes, thanks! Can we now call this method inside `DialFromContainer`?

File: test/e2e/network/service.go (hunk 3 above)
Comment (mm4tt) [reply test/e2e/network/service.go]: I see, makes sense, thanks for explaining

**Review by mm4tt — COMMENTED** [review]
/lgtm

Nice!

File: test/e2e/framework/network/utils.go (hunk 2 above)
Comment (knight42) [reply test/e2e/framework/network/utils.go]: please see the latest commit

**Comment by mm4tt** [comment]
Thanks! One more thing, could you please squash the commits together?

**Comment by knight42** [comment]
@mm4tt sure will do. and I wanna know that 
1. when should I remove the tag `[DisabledForLargeClusters]` so that this test is not skipped
2. should I continue to migrate the tests involved in #90171?

**Comment by mm4tt** [comment]
> Matt Matejczyk sure will do. and I wanna know that
> 
> 1. when should I remove the tag `[DisabledForLargeClusters]` so that this test is not skipped

Let's send another PR that just removes the tag once this PR merges. 

> 2. should I continue to migrate the tests involved in #90171?

One we remove the `DisabledForLargeClusters` tag and confirm that it works in our daily 5k node correctness tests - https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness
I (or our oncall) will keep an eye on that and let you know

**Comment by knight42** [comment]
@mm4tt Great! Then what should I do with these constant failing tests? Did I miss something?

**Comment by mm4tt** [comment]
Looks like at least one test failures is addressable - there are some lint errors:
```
Errors from golint:
test/e2e/framework/network/utils.go:163:6: exported type NetexecDialResponse should have comment or be unexported
test/e2e/network/util.go:56:1: comment on exported function GetHTTPContentFromTestContainer should be of the form "GetHTTPContentFromTestContainer ..."
```

**Comment by mm4tt** [comment]
The other one looks like a flake, hopefully retrying should fix that

File: test/e2e/framework/network/utils.go [hunk 5]
```diff
@@ -334,6 +333,36 @@ func (config *NetworkingTestConfig) GetEndpointsFromContainer(protocol, containe
...
+	ipPort := net.JoinHostPort(containerIP, strconv.Itoa(containerHTTPPort))
+	cmd := makeCURLDialCommand(ipPort, dialCommand, protocol, targetIP, targetPort)
+
+	stdout, stderr, err := config.f.ExecShellInPodWithFullOutput(config.TestContainerPod.Name, cmd)
+	if err != nil {
+		// A failure to kubectl exec counts as a try, not a hard fail.
+		// Also note that we will keep failing for maxTries in tests where
+		// we confirm unreachability.
+		framework.Logf("Failed to execute %q: %v, stdout: %q, stderr: %q", cmd, err, stdout, stderr)
+		return nil
```
Comment (wojtek-t) [inline test/e2e/framework/network/utils.go:348]: Returning nil on error is misleading.

Instead of that - I would really prefer returning (*NetexecDialResponse, error) from this method and returning error explicitly here.

File: test/e2e/framework/network/utils.go [hunk 6]
```diff
@@ -334,6 +333,36 @@ func (config *NetworkingTestConfig) GetEndpointsFromContainer(protocol, containe
...
+	}
+
+	var output NetexecDialResponse
+	framework.Logf("stdout: %v, stderr: %v, command run in: %#v", stdout, stderr, config.HostTestContainerPod)
```
Comment (wojtek-t) [inline test/e2e/framework/network/utils.go:352]: This can really spam the output - not sure if we want to log it.

File: test/e2e/network/service.go [hunk 7]
```diff
@@ -3283,42 +3282,63 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
-			var body bytes.Buffer
-			pollfn := func() (bool, error) {
-				result := e2enetwork.PokeHTTP(nodeIPs[0], healthCheckNodePort, "/healthz", nil)
-				if result.Code == 0 {
+		for nodeName, nodeIP := range noEndpointNodeMap {
+			ginkgo.By(fmt.Sprintf("Checking %v (%v:%v/%v) proxies to endpoints on another node", nodeName, nodeIP[0], svcNodePort, dialCmd))
+			GetHTTPContentFromTestContainer(config, nodeIP, svcNodePort, e2eservice.KubeProxyLagTimeout, dialCmd)
+		}
+
+		for nodeName, nodeIP := range endpointNodeMap {
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3317]: This in total with the previous for may cause timeouts in 5k-node tests, as we're effectively probing every single node in the cluster. Given you touch this already, maybe we should already add a condition that no more than N (=100?) are actually probed?

File: test/e2e/network/util.go [hunk 8]
```diff
@@ -53,6 +53,23 @@ func GetHTTPContent(host string, port int, timeout time.Duration, url string) by
...
+	pollFn := func() (bool, error) {
+		resp := config.GetResponseFromTestContainer("http", dialCmd, host, port)
+		if resp == nil || len(resp.Errors) > 0 || len(resp.Responses) == 0 {
+			return false, nil
+		}
+		body = resp.Responses[0]
+		return true, nil
+	}
+	if pollErr := wait.PollImmediate(framework.Poll, timeout, pollFn); pollErr != nil {
+		framework.Failf("Could not reach HTTP service through %v:%v/%v after %v: %v", host, port, dialCmd, timeout, pollErr)
```
Comment (wojtek-t) [inline test/e2e/network/util.go:68]: I'm not a fan of failing from those kind of methods. Instad, I would prefer returning an error here and failing from the place where it is called (which is the test itself).

File: test/e2e/framework/network/utils.go (hunk 6 above)
Comment (mm4tt) [reply test/e2e/framework/network/utils.go:352]: +1

File: test/e2e/network/service.go (hunk 7 above)
Comment (mm4tt) [reply test/e2e/network/service.go:3317]: I think it was never the case, we're capping # nodes that we fetch in line 3257:
```
		nodes, err := e2enode.GetBoundedReadySchedulableNodes(cs, e2eservice.MaxNodesForEndpointsTests)
```

But, looking at the code again, I don't think that your code is correct. Neither the old one seems correct.
To be more precise, I think both incorrectly compute the endpointNodeMap. Because of the capping above, the `nodes` will contain a random subset of all nodes. Given that, it's likely (and almost certain in large cluster) that you will get a subset of nodes on which your service is not running. Then the endpointNodeMap will be empty, which won't make the test to fail, but it neither will work correctly. This has to be addressed

**Review by mm4tt — COMMENTED** [review]
/lgtm cancel

File: test/e2e/network/service.go (hunk 7 above)
Comment (knight42) [reply test/e2e/network/service.go:3320]: Nice catch! I want to know if it is guranteed that the cluster always have a node with endpoint and a node without endpoint? If so, I guess we can make the `endpointNodeMap` from the endpoint node names returned by jig, and make the `noEndpointNodeMap` by iterating all nodes until we have selected no more than N nodes without endpoint?

Comment (mm4tt) [reply test/e2e/network/service.go:3320]: Yes, you can assume it's guaranteed. Moreover, we'll have only a single node with the endpoint, so as long as len(nodes) >=2 the code for computing `noEndpointNodeMap` is correct. Only the `endpointNodeMap` computation needs to be fixed and what you proposed makes sens (take it from endpointNodeMap)

Comment (knight42) [reply test/e2e/network/service.go:3330]: @mm4tt please check the latest commit

File: test/e2e/framework/service/jig.go [hunk 9]
```diff
@@ -260,21 +260,34 @@ func (j *TestJig) CreateLoadBalancerService(timeout time.Duration, tweak func(sv
...
 		return nil, err
 	}
-	nodeMap := map[string][]string{}
-	for _, n := range nodes.Items {
-		if epNodes.Has(n.Name) {
-			nodeMap[n.Name] = e2enode.GetAddresses(&n, v1.NodeExternalIP)
+	ctx := context.TODO()
+	nodes := make([]*v1.Node, 0, nodeNames.Len())
+	for name := range nodeNames {
+		n, err := j.Client.CoreV1().Nodes().Get(ctx, name, metav1.GetOptions{})
```
Comment (wojtek-t) [inline test/e2e/framework/service/jig.go:284]: Instead of getting N endpoints individually, you should list all endpoints instead.

File: test/e2e/network/service.go [hunk 10]
```diff
@@ -3283,42 +3282,76 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
+		endpointNodeMap := make(map[string]string)
+		// map from name of nodes without endpoint to internal ip
+		noEndpointNodeMap := make(map[string]string)
+		for _, node := range epNodes {
+			ips := e2enode.GetAddresses(node, v1.NodeInternalIP)
+			if len(ips) < 1 {
+				framework.Failf("No internal ip found for node %s", node.Name)
+			}
+			endpointNodeMap[node.Name] = ips[0]
+			epNodeNames.Insert(node.Name)
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3300]: Let's remove the `epNodeName` var completely - it has an entry for the same stuff as endpointNodeMap.

It seems to be used only in L3308, when you can simply have:
```
if _, ok := endpointNodeMap[n.Name]; !ok {
```

File: test/e2e/network/service.go [hunk 11]
```diff
@@ -3283,42 +3282,76 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
+		dialCmd := "clientip"
 
 		ginkgo.By(fmt.Sprintf("endpoints present on nodes %v, absent on nodes %v", endpointNodeMap, noEndpointNodeMap))
-		for nodeName, nodeIPs := range noEndpointNodeMap {
-			ginkgo.By(fmt.Sprintf("Checking %v (%v:%v%v) proxies to endpoints on another node", nodeName, nodeIPs[0], svcNodePort, path))
-			GetHTTPContent(nodeIPs[0], svcNodePort, e2eservice.KubeProxyLagTimeout, path)
+		for nodeName, nodeIP := range noEndpointNodeMap {
+			ginkgo.By(fmt.Sprintf("Checking %v (%v:%v/%v) proxies to endpoints on another node", nodeName, nodeIP[0], svcNodePort, dialCmd))
+			_, err := GetHTTPContentFromTestContainer(config, nodeIP, svcNodePort, e2eservice.KubeProxyLagTimeout, dialCmd)
+			if err != nil {
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3325]: framework.ExpectNoError(err, "Could not reach...)

File: test/e2e/network/service.go (hunk 7 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3330]: The fact that we were never capping number of nodes doesn't mean we shouldn't change that now (I know we were never capping it). But if we want to enable it at 15k-node clusters, we should cap it probably.

File: test/e2e/framework/service/jig.go (hunk 9 above)
Comment (knight42) [reply test/e2e/framework/service/jig.go:284]: but all I get here is only the node names and I want to return a list of `*v1.Node`. should I filter the nodes by label `kuberntes.io/hostname`?

Comment (wojtek-t) [reply test/e2e/framework/service/jig.go:284]: No - let's list everything.
You may not need everything and that's fine.

File: test/e2e/network/service.go (hunk 10 above)
Comment (knight42) [reply test/e2e/network/service.go:3300]: nice catch!

File: test/e2e/framework/service/jig.go (hunk 9 above)
Comment (wojtek-t) [reply test/e2e/framework/service/jig.go:284]: I mean - list all nodes once and then iterate over them.

File: test/e2e/network/service.go (hunk 7 above)
Comment (knight42) [reply test/e2e/network/service.go:3330]: @wojtek-t if what @mm4tt said was right

> we'll have only a single node with the endpoint

the number of nodes with endpoints is always one, and we get the list of nodes without endpoints by getting bounded nodes first:
```go
nodes, err := e2enode.GetBoundedReadySchedulableNodes(cs, e2eservice.MaxNodesForEndpointsTests /* 3 */)
```
then filter out the node with endpoint:
```go
// it is assumed that there is only a single node with the endpoint
for _, n := range nodes.Items {
    ips := e2enode.GetAddresses(&n, v1.NodeInternalIP)
    if len(ips) < 1 {
        framework.Failf("No internal ip found for node %s", n.Name)
    }
    if _, ok := endpointNodeMap[n.Name]; !ok {
        noEndpointNodeMap[n.Name] = ips[0]
    }
}
```
I guess the number of nodes is already capped?

Comment (wojtek-t) [reply test/e2e/network/service.go:3328]: @mm4tt - where do you get it from that there is one node with endpoint? I can't really see any pod and/or endpoint being created in that test (I must be missing something...)

Comment (wojtek-t) [reply test/e2e/network/service.go:3328]: Matt pointed me on this offline. So indeed doing that here doesn't make sense.

But it makes sense to do that for "noEndpointMap", because we will have those 5000 iterations there.

File: test/e2e/framework/service/jig.go [hunk 12]
```diff
@@ -260,21 +260,36 @@ func (j *TestJig) CreateLoadBalancerService(timeout time.Duration, tweak func(sv
...
+	nodeNames, err := j.GetEndpointNodeNames()
 	if err != nil {
 		return nil, err
 	}
-	nodeMap := map[string][]string{}
-	for _, n := range nodes.Items {
-		if epNodes.Has(n.Name) {
-			nodeMap[n.Name] = e2enode.GetAddresses(&n, v1.NodeExternalIP)
+	ctx := context.TODO()
+	nodes := make([]v1.Node, 0, nodeNames.Len())
```
Comment (wojtek-t) [inline test/e2e/framework/service/jig.go:282]: move it below - after the LIST call (where it will really be used)

File: test/e2e/network/service.go (hunk 7 above)
Comment (knight42) [reply test/e2e/network/service.go:3328]: currently we only iterate over `e2eservice.MaxNodesForEndpointsTests`, which is 3, nodes and filter out the node with endpoint to get `noEndpointMap`. I guess this is OK?

the 5000 iterations actually happens when we want to get a list of nodes with endpoint from node names: https://github.com/kubernetes/kubernetes/pull/91559/files#diff-cd7b1fed55944b797c43381ad94b421fR283-R289

Comment (knight42) [reply test/e2e/network/service.go:3328]: perhaps we can using label selector here? like
```go
	namesList := make([]string, 0, nodeNames.Len())
	for name := range nodeNames {
		namesList = append(namesList, name)
	}
	req, err := labels.NewRequirement(v1.LabelHostname, selection.In, namesList)
	s := labels.NewSelector()
	allNodes, err := j.Client.CoreV1().Nodes().List(ctx, metav1.ListOptions{
		LabelSelector: s.Add(*req).String(),
	})
```

Comment (knight42) [reply test/e2e/network/service.go:3328]: @wojtek-t I have updated the code as described above, could you check it again?

File: test/e2e/framework/service/jig.go [hunk 13]
```diff
@@ -260,21 +261,41 @@ func (j *TestJig) CreateLoadBalancerService(timeout time.Duration, tweak func(sv
...
-		if epNodes.Has(n.Name) {
-			nodeMap[n.Name] = e2enode.GetAddresses(&n, v1.NodeExternalIP)
-		}
+	ctx := context.TODO()
+	namesList := make([]string, 0, nodeNames.Len())
+	for name := range nodeNames {
+		namesList = append(namesList, name)
 	}
-	return nodeMap, nil
+	req, err := labels.NewRequirement(v1.LabelHostname, selection.In, namesList)
```
Comment (wojtek-t) [inline test/e2e/framework/service/jig.go:287]: FTR - that will usually work, unless you exceed the allowed length for url params (which isn't that long IIRC).

I guess I wasn't clear, but what I meant was:
- list *all* nodes in the cluster
- do client-side filtering for nodeName you want

so sth like
```
allNodes, err := j.Client.CoreV1().Nodes().List(ctx, metav1.ListOptions{}))
if err != nil {
  return nil, err
}

nodes := make([]v1.Node, 0, nodeName.Len())
for i := range allNodes {
  node := &allNodes[i]
  if !nodeNames.Has(node.Name) {
    continue
  }
  node = append(nodes, *node)
}
```

File: test/e2e/network/service.go (hunk 7 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3328]: added explicit comment there - with this you risk exceeding allowed length of URL params

It's fine to simply list *all* nodes.

File: test/e2e/framework/service/jig.go (hunk 13 above)
Comment (knight42) [reply test/e2e/framework/service/jig.go:287]: yeah I understand what you mean, but if we do client-side filtering we may have ~5000 iterations in the worst case. Isn't it something we try to avoid?

Comment (wojtek-t) [reply test/e2e/framework/service/jig.go:287]: The same would happen server-side if you do it using the selector.
Iterating is cheap. The only potential concern is listing and sending all those data, but we do that in many other tests anyway.

So no - it's fine to do that.

Comment (knight42) [reply test/e2e/framework/service/jig.go]: updated. please check again.

File: test/e2e/network/service.go (hunk 11 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3323]: friendly ping

File: test/e2e/network/service.go (hunk 7 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3328]: That seems fine now.

But I would like to get back to my original comment and ensure that we don't send O(5k) requests in serial here (or rather not here, but for "noEndpoint map" - and instead limit to the first 100 or sth (i.e. min(#such nodes, 100)).

File: test/e2e/network/service.go (hunk 11 above)
Comment (knight42) [reply test/e2e/network/service.go:3323]: this change has been applied now https://github.com/kubernetes/kubernetes/pull/91559/files#diff-3e87abdcaa68e4594b468bc5e5d99551R3324

File: test/e2e/network/service.go (hunk 7 above)
Comment (knight42) [reply test/e2e/network/service.go:3328]: according to this line https://github.com/knight42/kubernetes/blob/53f19bc4db12c9071471ab5e30c5cffc983bcf2b/test/e2e/network/service.go#L3257, the number of nodes we iterate at https://github.com/knight42/kubernetes/blob/53f19bc4db12c9071471ab5e30c5cffc983bcf2b/test/e2e/network/service.go#L3301 is `e2eservice.MaxNodesForEndpointsTests`, which is 3.

and I am a bit confused that we don't send any request to apiserver here, `e2enode.GetAddresses()` just extracts the corresponding ip address from the status field of `v1.Node`.

File: test/e2e/network/service.go (hunk 11 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3323]: What I meant is that you don't need "if err != nil {" framework.ExpectNoError does that for you

File: test/e2e/network/service.go (hunk 7 above)
Comment (wojtek-t) [reply test/e2e/network/service.go:3328]: Which is fine - because we send request to list nodes before.

Re Bounded nodes - yes, that solves my concern, thanks.

File: test/e2e/network/service.go [hunk 14]
```diff
@@ -3283,42 +3282,74 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
+		// map from name of nodes without endpoint to internal ip
+		noEndpointNodeMap := make(map[string]string)
+		for _, node := range epNodes {
+			ips := e2enode.GetAddresses(&node, v1.NodeInternalIP)
+			if len(ips) < 1 {
+				framework.Failf("No internal ip found for node %s", node.Name)
+			}
+			endpointNodeMap[node.Name] = ips[0]
+		}
+		// it is assumed that there is only a single node with the endpoint
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3300]: Move this comment to line 3290, i.e.

// map from name of nodes with endpoint to internal ip
// it is assumed that there is only a single node with the endpoint
endpointNodeMap := make(map[string]string)

Comment (knight42) [reply test/e2e/network/service.go]: please check the latest commit

File: test/e2e/network/service.go [hunk 15]
```diff
@@ -3283,42 +3282,72 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
 			framework.Failf("Service HealthCheck NodePort still present")
 		}
 
-		endpointNodeMap, err := jig.GetEndpointNodes()
+		config := e2enetwork.NewNetworkingTestConfig(f, false, false)
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3285]: Please don't create it here - move it down to where it really starts being used.

File: test/e2e/network/service.go [hunk 16]
```diff
@@ -3283,42 +3282,72 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
+
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3286]: And second thing: as part of NewNetworkingTestConfig above, what happens we also require external IP address:
https://github.com/kubernetes/kubernetes/blob/72fb952dd6cf54f56925853005198957aaf1584d/test/e2e/framework/network/utils.go#L649

@mm4tt - I think this will work, because we have public heapster node, right? Or should it also be changed?

**Review by wojtek-t — COMMENTED** [review]
Please also squash commits!

File: test/e2e/network/service.go (hunk 16 above)
Comment (knight42) [reply test/e2e/network/service.go]: I am not pretty sure, but from these lines https://github.com/kubernetes/kubernetes/blob/72fb952dd6cf54f56925853005198957aaf1584d/test/e2e/framework/network/utils.go#L671-L674, it looks like `config.ExternalAddr` is only used to determine `config.NodeIP` and `config.NodeIP` would be set to an internal IP if `config.ExternalAddr` is empty.

File: test/e2e/network/service.go [hunk 17]
```diff
@@ -3283,42 +3282,72 @@ var _ = SIGDescribe("ESIPP [Slow]", func() {
...
 		ingressIP := e2eservice.GetIngressPoint(&svc.Status.LoadBalancer.Ingress[0])
 		path := "/clientip"
+		dialCmd := "clientip"
 
-		ginkgo.By(fmt.Sprintf("endpoints present on nodes %v, absent on nodes %v", endpointNodeMap, noEndpointNodeMap))
-		for nodeName, nodeIPs := range noEndpointNodeMap {
-			ginkgo.By(fmt.Sprintf("Checking %v (%v:%v%v) proxies to endpoints on another node", nodeName, nodeIPs[0], svcNodePort, path))
-			GetHTTPContent(nodeIPs[0], svcNodePort, e2eservice.KubeProxyLagTimeout, path)
-		}
+		config := e2enetwork.NewNetworkingTestConfig(f, false, false)
```
Comment (wojtek-t) [inline test/e2e/network/service.go:3317]: And second thing: as part of NewNetworkingTestConfig above, what happens we also require external IP address:
https://github.com/kubernetes/kubernetes/blob/72fb952dd6cf54f56925853005198957aaf1584d/test/e2e/framework/network/utils.go#L649

@mm4tt - I think this will work, because we have public heapster node, right? Or should it also be changed?

**Comment by wojtek-t** [comment]
@knight42 - please squash all the commits, there should be a single commit in this PR instead of 7

**Comment by knight42** [comment]
@wojtek-t sure thing. I think multiple commits may be easier for reviewing.

File: test/e2e/network/service.go (hunk 17 above)
Comment (knight42) [reply test/e2e/network/service.go:3317]: I am not pretty sure, but from these lines https://github.com/kubernetes/kubernetes/blob/72fb952dd6cf54f56925853005198957aaf1584d/test/e2e/framework/network/utils.go#L671-L674, it looks like `config.ExternalAddr` is only used to determine `config.NodeIP` and `config.NodeIP` would be set to an internal IP if `config.ExternalAddr` is empty.

Comment (mm4tt) [reply test/e2e/network/service.go:3317]: Yes, we have a heapster node with public ip, and will always have it in our tests (e.g. to provide ssh bastion functionality)

File: test/e2e/framework/network/utils.go [hunk 18]
```diff
@@ -232,38 +250,19 @@ func (config *NetworkingTestConfig) EndpointHostnames() sets.String {
...
-	// The current versions of curl included in CentOS and RHEL distros
-	// misinterpret square brackets around IPv6 as globbing, so use the -g
-	// argument to disable globbing to handle the IPv6 case.
-	cmd := fmt.Sprintf("curl -g -q -s 'http://%s/dial?request=%s&protocol=%s&host=%s&port=%d&tries=1'",
-		ipPort,
-		dialCommand,
-		protocol,
-		targetIP,
-		targetPort)
+	cmd := makeCURLDialCommand(ipPort, dialCommand, protocol, targetIP, targetPort)
```
Comment (aojea) [inline test/e2e/framework/network/utils.go:253]: just curious, for what is needed this `cmd` var that we are creating here?
It seems it's only used in `Framework.Failf(` statement

Comment (aojea) [reply test/e2e/framework/network/utils.go:253]: scratch this comment, sorry, is not important

**Comment by knight42** [comment]
ah finally... this must be my most commented PR I have ever created..
