### PR TITLE
Fix uncertain mounts

### LINKED ISSUE #82426: Staging/mount directory should not be removed if nodestage/publish times out
It looks like currently we are trying to remove staging directory when `NodeStage` call errors out/times out - https://github.com/kubernetes/kubernetes/blob/c58767b1e2981bd7826b4336de0c2756fa975339/pkg/volume/csi/csi_attacher.go#L331

This is problematic because in case of timeout, the staging path might still be in-use by the driver for staging the volumes and k8s may unilaterally remove it.  I think similar problem exists for mount code too. We will have to treat timeout errors differently.

cc @vladimirvivien @msau42 @kubernetes/sig-storage-bugs 

/sig storage

### PR DESCRIPTION
**Pull request by gnufied**
Add uncertain state for volume mounts which will handle cleanup of CSI mounts correctly.

Fixes https://github.com/kubernetes/kubernetes/issues/82426 and https://github.com/kubernetes/kubernetes/issues/82340 and https://github.com/kubernetes/kubernetes/issues/83129

This does not fixes similar problem associated with raw block devices.  We are blocked on https://github.com/kubernetes/kubernetes/pull/74026 until we can fix raw block devices.

This PR fixes several issues by tracking certain `MountDevice` and `SetUp` failures as uncertain and adding them to actualStateofWorld so as volume can be cleaned up correctly when Pod is no longer scheduled on the node.  Previously these failures would cause volume to be not added to actualStateofWorld and hence volume may actually get mounted successfully but never get cleaned up properly. 

It does so by returning errors with additional context. Return value of `SetUp` and `MountDevice` functions now return following types of errors:

```
//   - TransientOperationFailure - operation failed with a transient error and could succeed if retried
//   - UncertainProgressError - operation failed but was started by reconciler and hence may be in-progress
//   - Error of any other type should be considered a final error and cause volume to not added to ASOW
```

```release-note
Track mount operations as uncertain if operation fails with non-final error
```

### CODE REVIEW

**Comment by gnufied** [comment]
/sig storage

cc @kubernetes/sig-storage-bugs

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 1]
```diff
@@ -355,6 +374,35 @@ type VolumeToMount struct {
...
+
+const (
+	// VolumeMounted means volume has been mounted in pod's local path
+	VolumeMounted VolumeMountState = "VolumeMounted"
+
+	// VolumeMountUncertain means volume may or may not be mounted in pods' local path
+	VolumeMountUncertain VolumeMountState = "VolumeMountUncertain"
+
+	// VolumeNotMounted means volume has not been mounted in pod's local path
+	VolumeNotMounted VolumeMountState = "VolumeNotMounted"
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_executor.go]: do we really need this state?
Normally we can just use a boolean value to indicate the volume is already mounted if it is true. If it is false, that means we are not sure it is mounted or not, but still add it into the state and reconciler will update the state after it successfully mounted.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 2]
```diff
@@ -127,6 +127,10 @@ type ActualStateOfWorld interface {
 	// actual state of the world.
 	GetMountedVolumes() []MountedVolume
 
+	// GetAllMountedVolumes returns list of all mounted volumes including
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: all "possibly" mounted volumes

File: pkg/volume/util/operationexecutor/operation_executor.go (hunk 1 above)
Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_executor.go]: Never mind. Actually I see the point of having three states.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 3]
```diff
@@ -354,12 +351,22 @@ func (asw *actualStateOfWorld) MarkVolumeAsUnmounted(
...
+	return asw.SetDeviceMountState(volumeName, operationexecutor.DeviceGloballyMounted, devicePath, deviceMountPath)
+}
+
+func (asw *actualStateOfWorld) MarkDeviceAsUncertain(
+	volumeName v1.UniqueVolumeName, devicePath, deviceMountPath string) error {
+	return asw.SetDeviceMountState(volumeName, operationexecutor.DeviceMountUncertain, devicePath, deviceMountPath)
+}
+
+func (asw *actualStateOfWorld) MarkVolumeMountAsUncertain(markVolumeOpts operationexecutor.MarkVolumeMountedOpts) error {
+	markVolumeOpts.VolumeMountState = operationexecutor.VolumeMountUncertain
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: This line https://github.com/kubernetes/kubernetes/pull/82492/files#diff-450e811a4953f760ff1594ede8b2037eR753 already set the state to uncertain. Why need to set it up here too?

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 4]
```diff
@@ -182,7 +194,9 @@ func (rc *reconciler) reconcile() {
 			}
 		}
 	}
+}
 
+func (rc *reconciler) mountAttachVolumes() {
 	// Ensure volumes that should be attached/mounted are attached/mounted.
 	for _, volumeToMount := range rc.desiredStateOfWorld.GetVolumesToMount() {
 		volMounted, devicePath, err := rc.actualStateOfWorld.PodExistsInVolume(volumeToMount.PodName, volumeToMount.VolumeName)
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: PodExistsInVolume() returns true for MountUncertain volumes too?

**Comment by jingxu97** [comment]
As issue #82426 mentioned, if staging operation timeout, and pod is deleted, with this PR, reconciler will trigger unstage operation. Will it cause any problem if stage and unstage are proceeding at the same time?

**Comment by gnufied** [comment]
@jingxu97 don't we have code in-place to prevent concurrent operations on a volume?

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 3 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: My thinking is - this is to safeguard against callers who may not be setting this correctly. The function is called `MarkVolumeMountAsUncertain`, so caller may expect that volume will be marked uncertain without explicitly specifying the state.

File: pkg/volume/csi/csi_client.go [hunk 5]
```diff
@@ -947,3 +978,27 @@ func (c *csiDriverClient) nodeGetVolumeStatsV1(
...
+	if !ok {
+		// This is not gRPC error. The operation must have failed before gRPC
+		// method was called, otherwise we would get gRPC error.
+		// We don't know if any previous CreateVolume is in progress, be on the safe side.
+		return false
+	}
+	switch st.Code() {
+	case codes.Canceled, // gRPC: Client Application cancelled the request
+		codes.DeadlineExceeded,  // gRPC: Timeout
+		codes.Unavailable,       // gRPC: Server shutting down, TCP connection broken - previous CreateVolume() may be still in progress.
```
Comment (Madhu-1) [inline pkg/volume/csi/csi_client.go]: I think need to update comments.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go (hunk 4 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: good catch! fixed and added test.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 2 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: fixed

File: pkg/volume/csi/csi_client.go (hunk 5 above)
Comment (gnufied) [reply pkg/volume/csi/csi_client.go]: fixe

File: pkg/volume/util/operationexecutor/operation_executor.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_executor.go]: We can manage with boolean value of mount state but in a lot of places we typically have to carry a comment to explain a boolean value (/*MountUncertain*/) and stuff like that. I thought it might be best to explicit and let the field document what it is and that way - it will be more clear. What do you think?

**Comment by gnufied** [comment]
@jingxu97 addressed review comments PTAL

**Comment by jingxu97** [comment]
> a volume?

But if operation timesout, it will continue to trigger another operation?

**Comment by gnufied** [comment]
@jingxu97 I think CSI spec is not very clear on what happens if `NodeStage` and `NodeUnstage` is called concurrently and I have filed - https://github.com/container-storage-interface/spec/issues/389 to seek some clarification.

File: pkg/volume/util/operationexecutor/operation_executor.go (hunk 1 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_executor.go]: Another thing I am thinking is - if mount failed with timeout first time and on second attempt mount failed with non-timeout(final) error then the volume should be moved to `VolumeNotMounted` state. I will update the code to do that.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 6]
```diff
@@ -272,13 +286,14 @@ func (rc *reconciler) reconcile() {
 			}
 		}
 	}
+}
 
-	// Ensure devices that should be detached/unmounted are detached/unmounted.
```
Comment (humblec) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: do you meant to comment about this function ?

**Comment by gnufied** [comment]
we should be okay with running concurrent NodeUnstage operation while NodeStage operation is in progress. it is allowed as per CSI spec.  I reviewed code for ceph, gce and ebs drivers and found that only GCE driver implements this correctly. Filed issues against EBS and Ceph drivers - https://github.com/ceph/ceph-csi/issues/615 and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/370

**Review by jsafrane — APPROVED** [review]
I tested it with a mock driver, it definitely helps, but I see some uncovered corner cases, see below.

File: pkg/volume/csi/csi_attacher.go [hunk 7]
```diff
@@ -324,7 +325,8 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
 		return err
 	}
 	defer func() {
-		if err != nil {
+		// Only for non-timedout errors remove the mount directory
+		if err != nil && !volumetypes.IsOperationTimeOutError(err) {
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/csi/csi_attacher.go]: It is possible to fix but this, it is kinda super ugly...

One can for example - return two errors from `MountDevice` call. One for CSI error and another for non-csi error. Both errors get recorded somewhere(asow or dsow not sure yet) and when next `MountDevice` call is made then both errors are supplied as arguments along with other args. So we can compare last csi error and current csi error and determine if operation is pending and not remove the directory for non-csi errors (and if both current and last csi-error is timeout).

It is no silver bullet however, I am afraid this will lead to orphan pod/volume directories left on the nodes and we have to carefully code this. There might be other unforeseen corner cases lurking around which we haven't thought through if we take this route.

Right now - my 2 cents are on calling current fix "good enough" and see if we receive bug reports from people about staging directories disappearing. I am not sure added complexity of tracking additional states is worth the cost. :(

File: pkg/volume/util/types/types.go [hunk 8]
```diff
@@ -51,6 +51,31 @@ func (o *GeneratedOperations) Run() (eventErr, detailedErr error) {
 	return o.OperationFunc()
 }
 
+// OperationTimedOutError indicates a particular volume operation has timed out.
+type OperationTimedOutError struct {
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/util/types/types.go]: It is one wrapper that all errors non-final errors. Do we need different ones?

[the remark this answers is not in the document]
Comment (jsafrane) [reply pkg/volume/util/types/types.go]: No, I just don't like the name - it covers more than `OperationTimedOutError` name suggests

File: pkg/volume/csi/csi_attacher.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go]: In external-provisioner we solved it by returning three values from [`ProvisionExt()`](https://github.com/jsafrane/sig-storage-lib-external-provisioner/blob/master/controller/volume.go#L76):

- `pv` - unrelated to NodeStage/Publish
- `err`: the error itself, mostly for logging
- `ProvisioningState` - state of the provisioning (when `err != nil`)
  - `Background` - CSI provisioner has reached CSI driver and got non-final error that means the provisioning may be in progress (e.g. timeout)
  - `Finished` - CSI provisioner has reached CSI driver and got final error that means the provisioning is for sure not in progress
  - `NoChange` - the provisioner did not reach the CSI driver (e.g. failed to get Secrets from API server). CSI provisioner has no clue in what state the provisioning is, but it is in the same state as before the call.

Caller of `ProvisionExt` (i.e. the provisioning lib) then keeps a list of provisionings in progress. IMO it's equal to uncertain state introduced in this PR.

An additional return val in `SetUp` / `MountDevice` ( / `TearDown` / `UnmountDevice`) could be enough, where the caller (`*Operation`) would mark the volume as uncertain when it receives `Background`, mark it as unmounted after `Finished` and leave the volume as it was before after `NoChange`.

**Comment by gnufied** [comment]
Yeah I think we might want to handle "uncertain" mount volume state (i.e `NodeUnpublish` timeouts) in a better way and mark volume mount as "uncertain" if unmount volume timesout.

File: pkg/volume/csi/csi_client.go [hunk 9]
```diff
@@ -518,12 +535,26 @@ func (c *csiDriverClient) NodeStageVolume(ctx context.Context,
...
-		return c.nodeStageVolumeV1(ctx, volID, publishContext, stagingTargetPath, fsType, accessMode, secrets, volumeContext, mountOptions)
+		nodeStageCalled = true
+		err = c.nodeStageVolumeV1(ctx, volID, publishContext, stagingTargetPath, fsType, accessMode, secrets, volumeContext, mountOptions)
 	} else if c.nodeV0ClientCreator != nil {
-		return c.nodeStageVolumeV0(ctx, volID, publishContext, stagingTargetPath, fsType, accessMode, secrets, volumeContext, mountOptions)
+		nodeStageCalled = true
+		err = c.nodeStageVolumeV0(ctx, volID, publishContext, stagingTargetPath, fsType, accessMode, secrets, volumeContext, mountOptions)
+	}
+	// if there is no error and noStage was called return nil
+	if err == nil && nodeStageCalled {
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/csi/csi_client.go]: fixd

File: pkg/volume/csi/csi_client.go [hunk 10]
```diff
@@ -305,8 +313,17 @@ func (c *csiDriverClient) NodePublishVolume(
 		)
 	}
 
-	return fmt.Errorf("failed to call NodePublishVolume. Both nodeV1ClientCreator and nodeV0ClientCreator are nil")
+	if nodePublishCalled && err == nil {
+		return nil
+	}
 
+	if err != nil {
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/csi/csi_client.go]: fixed

File: pkg/volume/csi/csi_attacher.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/csi/csi_attacher.go]: fixed

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 11]
```diff
@@ -1144,6 +1144,271 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
...
+	waitForDetach(t, volumeName, asw)
+
+	volumetesting.VerifyUnmountDeviceCallCount(1, fakePlugin)
+	volumetesting.VerifyTearDownCallCount(1, fakePlugin)
+}
+
+func waitForUncertainGlobalMount(t *testing.T, volumeName v1.UniqueVolumeName, asw cache.ActualStateOfWorld) {
+	// check if volume is globally mounted in uncertain state
+	err := retryWithExponentialBackOff(
+		time.Duration(500*time.Millisecond),
```
Comment (jsafrane) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: Since this is test code, should it be shorter (~100ms) and without exp. backoff? Or is the reconciler supposed to take long time?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 12]
```diff
@@ -1144,6 +1144,271 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
...
+
+	if err != nil {
+		t.Fatalf("expected volumes %s to be mounted in uncertain state globally", volumeName)
+	}
+}
+
+func waitForUncertainPodMount(t *testing.T, volumeName v1.UniqueVolumeName, asw cache.ActualStateOfWorld) {
+	// check if volume is locally pod mounted in uncertain state
+	err := retryWithExponentialBackOff(
+		time.Duration(500*time.Millisecond),
```
Comment (jsafrane) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: Since this is test code, should it be shorter (~100ms) and without exp. backoff? Or is the reconciler supposed to take long time?

(a `const` would be helpful)

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 13]
```diff
@@ -1168,9 +1433,23 @@ func waitForMount(
 	}
 }
 
+func waitForVolumeToExistInASW(t *testing.T, volumeName v1.UniqueVolumeName, asw cache.ActualStateOfWorld) {
+	err := retryWithExponentialBackOff(
+		time.Duration(500*time.Millisecond),
```
Comment (jsafrane) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: yeah, use `const` please

**Review by jsafrane — COMMENTED** [review]
Initial review. I'll test it with a mock driver.

**Comment by jsafrane** [comment]
/retest
Everything except kubernetes-verify are unrelated flakes

**Comment by jsafrane** [comment]
Tested these scenarios:

---

1. Create a pod
2. NodeStage times out

What happened:
NodeStage was periodically called
Global dir was not cleaned after each timeout (it was before this PR)

---
1. Create a pod
2. NodeStage errors

What happened:
NodeStage was periodically called
Global dir was cleaned after each error
*Local pod directory was not cleaned up

---

1. Create a pod
2. NodeStage times out
3. Delete the pod

What happened:
NodeUnstage was called (this was expected)
*Local pod directory was not cleaned up

---

1. Create a pod
2. NodeStage errors
3. Delete the pod

What happened:
NodeUnstage was **not** called (this was expected)
*Local pod directory was not cleaned up

---

1. Create a pod
2. NodeStage times out
3. Delete the pod
4. NodeUnstage errors or times out

What happened:
NodeUnstage was periodically called (both "errors" and "times out" have the same result)

---

1. Create a pod
2. NodeStage times out
3. Delete the pod
4. NodeUnstage errors or times out
5. Create the same pod

What happened:
NodeStage was called (and NodePublish and pod got running)

---

In many tests, local pod directory was not cleaned either after NodeStage failure or NodeUnstage success. JSON remained there forever. Why was it created when
 NodePublish / SetUp was not called yet?


I'll continue with reconstruction tomorrow.

**Comment by gnufied** [comment]
The reason local pod data is created even though Setup has not been called is - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L422

So the act of just instantiating the `Mounter` interface results in creation of the local pod directory and json file. However, if `MountDevice` failed for some reason - there is nothing in the code that will clean up that directory and data file. That is why - we have those files left. I also verified this behaviour with *before* this change and that also results in leftover local pod volume directory and data file.  So, it is at least not a regression but I think worth fixing.

**Comment by jsafrane** [comment]
> I have logged #84878 for fixing that behaviour.

Ack, we can fix it as a separate PR.

**Comment by jsafrane** [comment]
Tested reconstruction, it works well when a volume is fully set up (i.e. NodePublish finished).

If kubelet is restarted when NodePublish has not finished yet (e.g. it has timed out), reconstruction checks that the pod directory is not a mount point and just cleans up the pod directory. This is a known limitation of reconstruction process - it considers only mount points for reconstruction. See https://github.com/kubernetes/kubernetes/issues/79980

File: pkg/volume/volume.go [hunk 14]
```diff
@@ -240,6 +246,9 @@ type DeviceMounter interface {
 	// individual pods can then bind mount
 	// Note that devicePath can be empty if the volume plugin does not implement any of Attach and WaitForAttach methods.
 	MountDevice(spec *Spec, devicePath string, deviceMountPath string) error
+
+	// MountDeviceWithStatusTracking is same as MountDevice except status of mount operation is also returned
+	MountDeviceWithStatusTracking(spec *Spec, devicePath string, deviceMountPath string) (volumetypes.OperationStatus, error)
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/volume/volume.go]: Okay, so I ended up removing both of `*WithStatusTracking` functions and using plain `MountDevice` and `SetUp`.  I did not like the idea of introducing new interface because logically it did not fit in with existing interfaces.  

This does mean - surface area of the change will be bigger.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go (hunk 6 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: I moved this to the caller.

**Comment by jsafrane** [comment]
@jingxu97 @msau42 @davidz627, any comments? It looks fine from my POV.

**Comment by jsafrane** [comment]
@saad-ali, can you please add milestone? Thanks!

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 15]
```diff
@@ -301,6 +309,12 @@ type mountedPod struct {
 	// fsResizeRequired indicates the underlying volume has been successfully
 	// mounted to this pod but its size has been expanded after that.
 	fsResizeRequired bool
+
+	// volumeMountStateForPod stores state of volume mount for the pod. if it is:
+	//   - VolumeMounted: means volume for pod has been successfully mounted
+	//   - VolumeMountUncertain: means volume for pod may not be mounted, but it must be unmounted
+	//   - VolumeNotMounted: means volume for pod has not been mounted
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: do you need VolumeNotMounted state? I think the only action for this state is to delete the volume from the cache. This state is not used.

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 16]
```diff
@@ -161,18 +161,37 @@ func NewOperationExecutor(
 	}
 }
 
+// MarkVolumeMountedOpts is an struct to pass arguments to MountVolume functions
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_executor.go]: this struct to passed to different operations such as uncertain, unmounted etc, so how about call it MarkVolumeOpts?

File: pkg/volume/fc/attacher.go [hunk 17]
```diff
@@ -95,39 +96,42 @@ func (attacher *fcAttacher) GetDeviceMountPath(
...
-		if os.IsNotExist(err) {
-			if err := os.MkdirAll(deviceMountPath, 0750); err != nil {
+func (attacher *fcAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMountPath string) (volumetypes.OperationStatus, error) {
+	mountInternal := func() error {
+		mounter := attacher.host.GetMounter(fcPluginName)
+		notMnt, err := mounter.IsLikelyNotMountPoint(deviceMountPath)
+		if err != nil {
+			if os.IsNotExist(err) {
+				if err := os.MkdirAll(deviceMountPath, 0750); err != nil {
+					return err
```
Comment (jingxu97) [inline pkg/volume/fc/attacher.go]: it does not need to return OperationStatus?

Comment (gnufied) [reply pkg/volume/fc/attacher.go]: It does return `OperationStatus` by calling `return  volumetypes.OperationFinished, mountInternal()` at the end. Some of this refactoring was hard to do in individual plugins because changing  return value of a volume interface function means modifying all those return statements in different places.  I have wrapped original `mountDevice` in internal `mountInternal` function and then we are returning both `OperationStatus` and `Error.

File: pkg/volume/util/operationexecutor/operation_executor.go (hunk 16 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_executor.go]: ack. I will change it.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 15 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: I think we can drop it.

File: pkg/volume/csi/csi_mounter.go [hunk 18]
```diff
@@ -98,33 +99,41 @@ func (c *csiMountMgr) CanMount() error {
...
 	if mounted {
 		klog.V(4).Info(log("mounter.SetUpAt skipping mount, dir already mounted [%s]", dir))
-		return nil
+		return opExitStatus, nil
 	}
 
 	csi, err := c.csiClientGetter.Get()
 	if err != nil {
-		return errors.New(log("mounter.SetUpAt failed to get CSI client: %v", err))
+		return opExitStatus, errors.New(log("mounter.SetUpAt failed to get CSI client: %v", err))
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: is it possible that temporarily failt to get csiClient, so that status should return NoChange?

File: pkg/volume/csi/csi_attacher.go [hunk 19]
```diff
@@ -219,37 +220,39 @@ func (c *csiAttacher) GetDeviceMountPath(spec *volume.Spec) (string, error) {
...
 	if deviceMountPath == "" {
-		return errors.New(log("attacher.MountDevice failed, deviceMountPath is empty"))
+		return opExitStatus, errors.New(log("attacher.MountDevice failed, deviceMountPath is empty"))
 	}
 
 	mounted, err := isDirMounted(c.plugin, deviceMountPath)
 	if err != nil {
 		klog.Error(log("attacher.MountDevice failed while checking mount status for dir [%s]", deviceMountPath))
-		return err
+		return opExitStatus, err
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher.go]: is there some possible state that temporarily fail  to get mount state? so operationstatus is nochange?

Comment (gnufied) [reply pkg/volume/csi/csi_attacher.go]: I am not sure how this could happen and if this does - since we have not started `NodeStageVolume` call yet, it should be safe to mark the operation as "finished".  Are you thinking some corner case where `NodeStageVolume` was called but is in-progress and next `MountDevice` call fails in `isDirMounted` check and hence device is marked as not-mounted?

File: pkg/volume/csi/csi_mounter.go (hunk 18 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: may be yeah. I will change this code.

**Comment by jsafrane** [comment]
/retest

(dbugging gce-big job, seems to fail too consistently in this PR)

**Comment by jsafrane** [comment]
gce-big (https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/82492/pull-kubernetes-kubemark-e2e-gce-big/1194197582746750976/) fails because:

* Pod `test-uaaneu-3/small-deployment-150-6785544b7f-vs4n5` is scheduled to node `e2e-82492-ac87c-minion-group-89nk/kubelet-hollow-node-4tlsl`.

* The pod sets up Secrets just fine and starts successfully:

```
I1112 11:01:04.809803       6 kubelet.go:1947] SyncLoop (PLEG): "small-deployment-150-6785544b7f-vs4n5_test-uaaneu-3(6cd0a2a7-5a2f-415f-a165-8f4c3da17115)", event: &pleg.PodLifecycleEvent{ID:"6cd0a2a7-5a2f-415f-a165-8f4c3da17115", Type:"ContainerStarted", Data:"3e49643a9103c081"}
```

* clusterloader/v0.0.0 deletes the Secret used by the pod in API server:
```
I1112 11:03:24.643351       1 httplog.go:90] DELETE /api/v1/namespaces/test-uaaneu-3/secrets/small-deployment-150: (4.341218ms) 200 [clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format 34.68.137.176:34018]
```

* The pod is deleted shortly after the secret was deleted:
    ```
    I1112 11:03:31.177689       1 httplog.go:90] DELETE /api/v1/namespaces/test-uaaneu-3/pods/small-deployment-150-6785544b7f-vs4n5: (5.408707ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/3222b3b/system:serviceaccount:kube-system:generic-garbage-collector [::1]:42968]
    ```
    And everything goes south from here.

    * kubelet still tries to SetUp the pod instead of TearDown after the pod was deleted:
        ```
        I1112 11:03:31.211101       6 kubelet.go:1918] SyncLoop (DELETE, "api"): "small-deployment-150-6785544b7f-vs4n5_test-uaaneu-3(6cd0a2a7-5a2f-415f-a165-8f4c3da17115)"
        I1112 11:03:31.211333       6 fake_cpu_manager.go:47] [fake cpumanager] RemoveContainer (container id: 165e512c66489898)
        I1112 11:03:31.211348       6 kuberuntime_container.go:591] Killing container "docker://165e512c66489898" with 2 second grace period
        I1112 11:03:31.638285       6 reconciler.go:267] operationExecutor.MountVolume started for volume "secret" (UniqueName: "kubernetes.io/secret/6cd0a2a7-5a2f-415f-a165-8f4c3da17115-secret") pod "small-deployment-150-6785544b7f-vs4n5" (UID: "6cd0a2a7-5a2f-415f-a165-8f4c3da17115")
        ```
    * And kubelet tries to SetUp the volume instead of TearDown forever. E.g. after 10 minutes:
        ```
        I1112 11:15:46.048244       6 reconciler.go:267] operationExecutor.MountVolume started for volume "secret" (UniqueName: "kubernetes.io/secret/6cd0a2a7-5a2f-415f-a165-8f4c3da17115-secret") pod "small-deployment-150-6785544b7f-vs4n5" (UID: "6cd0a2a7-5a2f-415f-a165-8f4c3da17115")
        E1112 11:15:46.048393       6 secret.go:200] Couldn't get secret test-uaaneu-3/small-deployment-150: secret "small-deployment-150" not found
        E1112 11:15:46.048485       6 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/6cd0a2a7-5a2f-415f-a165-8f4c3da17115-secret\" (\"6cd0a2a7-5a2f-415f-a165-8f4c3da17115\")" failed. No retries permitted until 2019-11-12 11:17:48.048454525 +0000 UTC m=+2195.419666335 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"secret\" (UniqueName: \"kubernetes.io/secret/6cd0a2a7-5a2f-415f-a165-8f4c3da17115-secret\") pod \"small-deployment-150-6785544b7f-vs4n5\" (UID: \"6cd0a2a7-5a2f-415f-a165-8f4c3da17115\") : secret \"small-deployment-150\" not found"
        ```

So there actually may be a bug in this PR! VolumeManager should switch to TearDown instead of SetUp.

**Comment by gnufied** [comment]
The problem appears to be caused by remounting mechanism whereas a failing remount can mark a previously successful volume as "unmounted".  I am fixing this and also adding additonal tests - https://github.com/kubernetes/kubernetes/pull/82492/files#diff-450e811a4953f760ff1594ede8b2037eR781

**Review by jsafrane — COMMENTED** [review]
Found couple of nits while looking what went wrong with Secrets.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 20]
```diff
@@ -707,11 +707,23 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
...
 				deviceMountPath)
 			if err != nil {
+				switch operationState {
+				case volumetypes.OperationInProgress:
+					markDeviceUncertainError := actualStateOfWorld.MarkDeviceAsUncertain(volumeToMount.VolumeName, devicePath, deviceMountPath)
+					if markDeviceUncertainError != nil {
+						klog.Errorf(volumeToMount.GenerateErrorDetailed("MountDevice.MarkDeviceAsUncertain failed", markDeviceUncertainError).Error())
+					}
+				case volumetypes.OperationFinished:
+					markDeviceUnmountError := actualStateOfWorld.MarkDeviceAsUnmounted(volumeToMount.VolumeName)
```
Comment (jsafrane) [inline pkg/volume/util/operationexecutor/operation_generator.go]: > The problem appears to be caused by remounting mechanism whereas a failing remount can mark a previously successful volume as "unmounted".

I think this is the place that broke Secrets in e2e tests.

Just an idea: with the new interface, Secrets, ConfigMaps, Projected and DownwardAPI volumes could return `NoChange` on Kube API errors and the volume status would not be changed.

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: We could but I am currently thinking of keeping that behaviour out of those drivers and just for CSI. The fix I am making does it such that - if a volume was mounted previously, then next mount(re) failure should not mark the volume as unmounted. 

Each case where `NoChange` or such new change is added - we will have to carefully review that code.

**Comment by jsafrane** [comment]
I went trhough this PR again and it's mostly LGTM (except Secrets setup). If there are no objections and Secrets are fixed, I'd like to merge it into 1.17.

File: pkg/volume/csi/csi_attacher.go (hunk 19 above)
Comment (jingxu97) [reply pkg/volume/csi/csi_attacher.go]: yes, that is the thought

File: pkg/volume/csi/csi_client.go [hunk 21]
```diff
@@ -949,3 +971,27 @@ func (c *csiDriverClient) nodeGetVolumeStatsV1(
...
+	// https://github.com/container-storage-interface/spec/blob/master/spec.md
+	st, ok := status.FromError(err)
+	if !ok {
+		// This is not gRPC error. The operation must have failed before gRPC
+		// method was called, otherwise we would get gRPC error.
+		// We don't know if any previous volume operation is in progress, be on the safe side.
+		return false
+	}
+	switch st.Code() {
+	case codes.Canceled, // gRPC: Client Application cancelled the request
```
Comment (jingxu97) [inline pkg/volume/csi/csi_client.go]: How about some code like PERMISSION_DENIED, UNAUTHENTICATED?

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 22]
```diff
@@ -811,6 +814,47 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
...
+		// only devices which are not mounted can be marked as uncertain. We do not want to mark a device
+		// which was previously marked as mounted here as uncertain.
+		if actualStateOfWorld.GetDeviceMountState(volumeToMount.VolumeName) == DeviceNotMounted {
+			markDeviceUncertainError := actualStateOfWorld.MarkDeviceAsUncertain(volumeToMount.VolumeName, devicePath, deviceMountPath)
+			if markDeviceUncertainError != nil {
+				klog.Errorf(volumeToMount.GenerateErrorDetailed("MountDevice.MarkDeviceAsUncertain failed", markDeviceUncertainError).Error())
+			}
+		}
+	case volumetypes.OperationFinished:
+		// Similarly only devices which were uncertain can be marked as unmounted
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_generator.go]: it might still have issue?
1. mount time out, mark as uncertain
2. second mount returns Finished due to some reason such as secret is deleted
3. mount succeeded?

Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I think we can simply do nothing (do not mark as mounted, nor mark it as unmounted) if volumetype is operationFinished for (re)mount

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: So basically same mount operation which was in-progress in step#1 failed in step#2 and then mount operation initiated in step#1 succeeds.   I agree that this could happen but:

1. for CSI drivers, they can't return a "final" error code for a in-progress operation and other code paths which use external API return `NoChange` status.
2. For secrets etc - I am going to make it to return `NoChange` on `remount` if Secret can not be found, as jan proposed in - https://github.com/kubernetes/kubernetes/pull/82492#discussion_r345795525 but since "uncertain" is never returned for secrets in general, the likelihood of this happening is low and will fixed for good in the follow up of secrets/configmaps PR.

Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Is there any bad consequence of leaving the volume as "uncertain"?

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I can't think of any bad consequence(atm) except - I have tried to stick to existing data model used by volumemanager. In this model - if a volume is never successfully mounted, it is not recorded in ASOW. With above change you are proposing, known failed mounts will be kept in ASOW and should be unmounted/toredown when pod is deleted.

File: pkg/volume/csi/csi_client.go (hunk 21 above)
Comment (gnufied) [reply pkg/volume/csi/csi_client.go]: Elsewhere we have assumed those error codes to be "final" and unless CSI driver deployment is fixed, this error will keep happening.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 22 above)
Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Agree your point. I just feel this way it might be safer and simpler. Otherwise, we have to make sure driver always return correct status just introduced. In previous code, successful mount will mark volume as mounted, failed mount does not unmark anything (of course, there is actually nothing to unmark). 

I think I am ok either way.

**Comment by jingxu97** [comment]
Do we need to handle unmount timeout case?
1. unmount timeout, but later succeed
2. pod is added back with volume, 
3. volume still in actual state, so no mount will be triggered?
If it is an issue, we can address in separate PR

**Comment by gnufied** [comment]
@jingxu97 I think that is a valid point. Lets handle this as a separate issue - https://github.com/kubernetes/kubernetes/issues/85248

File: pkg/volume/csi/csi_client.go (hunk 21 above)
Comment (jsafrane) [reply pkg/volume/csi/csi_client.go]: Since user is not authenticated or authorized we can safely assume that the operation did not even start. If we mark a volume as uncertain, we would most probably get PERMISSION_DENIED or UNAUTHENTICATED error during Unpublish / Unstage.

**Comment by jsafrane** [comment]
I think containerd is broken also in other PRs and it's not Required.

File: pkg/volume/csi/csi_attacher.go [hunk 23]
```diff
@@ -287,25 +292,32 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
...
+
 	nodeStageSecrets := map[string]string{}
 	if csiSource.NodeStageSecretRef != nil {
 		nodeStageSecrets, err = getCredentialsFromSecret(c.k8s, csiSource.NodeStageSecretRef)
 		if err != nil {
 			err = fmt.Errorf("fetching NodeStageSecretRef %s/%s failed: %v",
 				csiSource.NodeStageSecretRef.Namespace, csiSource.NodeStageSecretRef.Name, err)
-			return err
+			// if we failed to fetch secret then that could be a transient error
+			opExitStatus = volumetypes.OperationStateNoChange
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher.go]: if fail to get credentials, the state is OperationStateNoChange, I think it will not mark volume in the actual state. Then is there any code we will clean up metadata?

File: pkg/volume/csi/csi_attacher.go [hunk 24]
```diff
@@ -262,10 +265,12 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
...
 			klog.Error(log("failed to remove dir after error [%s]: %v", dataDir, cleanErr))
 		}
-		return err
+		return opExitStatus, err
 	}
 	defer func() {
-		if err != nil {
+		// Only if there was an error and volume operation was considered
+		// finished, we should remove the directory.
+		if err != nil && opExitStatus == volumetypes.OperationFinished {
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher.go]: if fail to get credentials, the state is OperationStateNoChange, I think it will not mark volume in the actual state. Then is there any code we will clean up metadata?

File: pkg/volume/csi/csi_mounter.go [hunk 25]
```diff
@@ -199,26 +209,29 @@ func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error
...
+		return opExitStatus, errors.New(log("mounter.SetUpAt failed to create dir %#v:  %v", dir, err))
 	}
 	klog.V(4).Info(log("created target path successfully [%s]", dir))
 
 	nodePublishSecrets = map[string]string{}
 	if secretRef != nil {
 		nodePublishSecrets, err = getCredentialsFromSecret(c.k8s, secretRef)
 		if err != nil {
-			return fmt.Errorf("fetching NodePublishSecretRef %s/%s failed: %v",
+			opExitStatus = volumetypes.OperationStateNoChange
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: target_dir will not be cleaned up here?

File: pkg/volume/csi/csi_mounter.go [hunk 26]
```diff
@@ -227,7 +240,8 @@ func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error
 	// Inject pod information into volume_attributes
 	podAttrs, err := c.podAttributes()
 	if err != nil {
-		return errors.New(log("mounter.SetUpAt failed to assemble volume attributes: %v", err))
+		opExitStatus = volumetypes.OperationStateNoChange
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: target_dir will not be cleaned up here?

Comment (jingxu97) [reply pkg/volume/csi/csi_mounter.go]: maybe move MkdirAll after getting these attributes?

File: pkg/volume/csi/csi_attacher.go (hunk 23 above)
Comment (gnufied) [reply pkg/volume/csi/csi_attacher.go]: fixed

File: pkg/volume/csi/csi_attacher.go (hunk 24 above)
Comment (gnufied) [reply pkg/volume/csi/csi_attacher.go]: fixed

File: pkg/volume/csi/csi_mounter.go (hunk 25 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: As discussed previously with @jsafrane  - cleaning up of pod's local volume directory is broken regardless of what we do here. I was thinking of fixing this separately in - https://github.com/kubernetes/kubernetes/issues/84878

File: pkg/volume/csi/csi_mounter.go (hunk 26 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: same as above

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 27]
```diff
@@ -749,11 +750,23 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
 		}
 
 		// Execute mount
-		mountErr := volumeMounter.SetUp(volume.MounterArgs{
+		opExitStatus, mountErr := volumeMounter.SetUp(volume.MounterArgs{
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_generator.go]: Now we introduce this new operation state, should we log the returned state?

File: pkg/volume/volume.go [hunk 28]
```diff
@@ -239,7 +241,7 @@ type DeviceMounter interface {
 	// MountDevice mounts the disk to a global path which
 	// individual pods can then bind mount
 	// Note that devicePath can be empty if the volume plugin does not implement any of Attach and WaitForAttach methods.
-	MountDevice(spec *Spec, devicePath string, deviceMountPath string) error
+	MountDevice(spec *Spec, devicePath string, deviceMountPath string) (volumetypes.OperationStatus, error)
```
Comment (saad-ali) [inline pkg/volume/volume.go]: As far as I can tell the purpose of `volumetypes.OperationStatus` is to differentiate between 3 possible states: 1) success/no error (state certain), 2) error failed operation (state certain), and 3) error failed operation (uncertain state)?

There are two pieces of information here: 1) `error`/`no error`,  and 2) for `no error`, there are two possible sub-states: `certain`/`uncertain`.

Returning `error` AND an explicit `volumetypes.OperationStatus` seems wrong since it allows for the possibility of the two parameters to contradict each other.

I think typed errors would be cleaner here. But overall this is a nit.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 27 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I am thinking that, while keeping all the underlying logic same, use special error types to indicate different state of failures. It will reduce the size of change and will allow us to keep volume plugin interface, more or less same. Thanks to @saad-ali for proposing this idea.

**Comment by josiahbjorgaard** [comment]
/milestone v1.18

(code freeze v1.17)

File: pkg/volume/volume.go (hunk 28 above)
Comment (gnufied) [reply pkg/volume/volume.go]: fixed

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 27 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: fixed

**Comment by davidz627** [comment]
Please improve release note - right now it is not clear what is changing/affected.

**Comment by gnufied** [comment]
@davidz627 done

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 29]
```diff
@@ -274,13 +288,14 @@ func (rc *reconciler) reconcile() {
...
+func (rc *reconciler) unmountDetachDevices() {
 	for _, attachedVolume := range rc.actualStateOfWorld.GetUnmountedVolumes() {
 		// Check IsOperationPending to avoid marking a volume as detached if it's in the process of mounting.
 		if !rc.desiredStateOfWorld.VolumeExists(attachedVolume.VolumeName) &&
 			!rc.operationExecutor.IsOperationPending(attachedVolume.VolumeName, nestedpendingoperations.EmptyUniquePodName) {
-			if attachedVolume.GloballyMounted {
+			if attachedVolume.DeviceMayBeMounted() {
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: not a big issue, but this function could be implemented locally?

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 30]
```diff
@@ -274,13 +288,14 @@ func (rc *reconciler) reconcile() {
...
 		}
 	}
+}
 
-	// Ensure devices that should be detached/unmounted are detached/unmounted.
+func (rc *reconciler) unmountDetachDevices() {
 	for _, attachedVolume := range rc.actualStateOfWorld.GetUnmountedVolumes() {
 		// Check IsOperationPending to avoid marking a volume as detached if it's in the process of mounting.
 		if !rc.desiredStateOfWorld.VolumeExists(attachedVolume.VolumeName) &&
 			!rc.operationExecutor.IsOperationPending(attachedVolume.VolumeName, nestedpendingoperations.EmptyUniquePodName) {
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: not your change, but I forgot why we need to check operationPending only for unmountDevice?

File: pkg/volume/csi/csi_mounter.go [hunk 31]
```diff
@@ -199,7 +205,8 @@ func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error
 			nodeName := string(c.plugin.host.GetNodeName())
 			c.publishContext, err = c.plugin.getPublishContext(c.k8s, volumeHandle, string(driverName), nodeName)
 			if err != nil {
-				return err
+				// we could have a transient error associated with fetching publish context
+				return volumetypes.NewTransientOperationFailure(err.Error())
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: why this one does not use fmt.Sprintf("") to generate errors as below?

File: pkg/volume/csi/csi_mounter.go [hunk 32]
```diff
@@ -99,10 +100,14 @@ func (c *csiMountMgr) CanMount() error {
 }
 
 func (c *csiMountMgr) SetUp(mounterArgs volume.MounterArgs) error {
-	return c.SetUpAt(c.GetPath(), mounterArgs)
+	return c.setupInternal(c.GetPath(), mounterArgs)
 }
 
 func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
+	return c.setupInternal(dir, mounterArgs)
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: why adding this setupInternal?

File: pkg/volume/csi/csi_mounter.go [hunk 33]
```diff
@@ -272,18 +282,7 @@ func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error
...
-			klog.Error(log("NodeUnpublishVolume failed for [%s]: %v", c.volumeID, unpubErr))
-			return fsGrpErr
-		}
-
-		if unmountErr := removeMountDir(c.plugin, dir); unmountErr != nil {
-			klog.Error(log("removeMountDir failed for [%s]: %v", dir, unmountErr))
-			return fsGrpErr
-		}
-		return fsGrpErr
+		return volumetypes.NewUncertainProgressError(fmt.Sprintf("applyFSGroup failed for vol %s: %v", c.volumeID, err))
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: maybe add comment here. At this point, mount is successful, but we want to 
1. return error so that volume cannot be used since ownership is not set correctly
2. return NewUncertainProgressError so that volume will be marked in actual state and mount will be cleaned up when it is needed.

**Comment by jingxu97** [comment]
Overall looks good to me. A few small comments. Since this is a big change, maybe add more  design details in the PR comment section.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go (hunk 30 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: Here is the PR that implemented this - https://github.com/kubernetes/kubernetes/pull/40417

File: pkg/volume/csi/csi_mounter.go (hunk 31 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: I think mostly because this error here does not wrap existing error into a string. We can do that here though..

File: pkg/volume/csi/csi_mounter.go (hunk 32 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: removed

File: pkg/volume/csi/csi_mounter.go (hunk 33 above)
Comment (gnufied) [reply pkg/volume/csi/csi_mounter.go]: added comment

File: pkg/kubelet/volumemanager/reconciler/reconciler.go (hunk 29 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: I am thinking of leaving it as it is - since the resulting if statement looks quite big when placed inline and I do not like making a local helper function in this file.. :(

**Comment by gnufied** [comment]
@jingxu97 added additional comments to the PR. ptal

File: pkg/kubelet/volumemanager/reconciler/reconciler.go (hunk 29 above)
Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: I mean you can have a local function to check device maybe mounted?

File: pkg/volume/util/types/types.go [hunk 34]
```diff
@@ -51,6 +51,57 @@ func (o *GeneratedOperations) Run() (eventErr, detailedErr error) {
...
+	return err.msg
+}
+
+// NewUncertainProgressError creates an instance of UncertainProgressError type
+func NewUncertainProgressError(msg string) *UncertainProgressError {
+	return &UncertainProgressError{msg: msg}
+}
+
+// IsOperationFinishedError checks if given error is of type that indicates
+// operation is finished with an error.
```
Comment (jingxu97) [inline pkg/volume/util/types/types.go]: with a FINAL error (not transient, or uncertain progress)

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 35]
```diff
@@ -679,6 +683,49 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
 	}
 }
 
+func (og *operationGenerator) markDeviceErrorState(volumeToMount VolumeToMount, devicePath, deviceMountPath string, mountError error, actualStateOfWorld ActualStateOfWorldMounterUpdater) {
+	if volumetypes.IsOperationFinishedError(mountError) &&
+		actualStateOfWorld.GetDeviceMountState(volumeToMount.VolumeName) == DeviceMountUncertain {
+		// Only devices which were uncertain can be marked as unmounted
+		markDeviceUnmountError := actualStateOfWorld.MarkDeviceAsUnmounted(volumeToMount.VolumeName)
```
Comment (jingxu97) [inline pkg/volume/util/operationexecutor/operation_generator.go]: My thought is if you don't mark device as unmount when previously marked as uncertain. then you could simplify the logic. there is no need of TransientOperationError. MarkDeviceAsUnmounted will be triggered during volume tear down phase. 
What do you think?

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: There are two reasons, I am not very sure about taking this path:
1. volumemanager has been designed to not track volumes that are not mounted (or for which mount failed with 100% certainity). Now we are saying - we will keep volumes which have failed to mount in "uncertain" state and hence they will require "teardown" and "unmountdevice" calls.  This introduces additional design change into volumemanager and I hope that - no plugin breaks (or fail unmount call) when unmount is called for failed mounts.  My intention has been to stick to code paths which are known to work.

2. The second reason is - what are we supposed to return when transient error does happen in mount calls? 
    * Mount is called and kubelet fails to fetch the secret: - If we return `uncertainProgressError` for them, then volume will be added to ASOW in uncertain state, even though mount call has not even been attempted.  It seems wrong to accept a volume in ASOW. This PR also made a change that, fetching secret call has been moved up and hence if there was an error fetching secret, call returns early without even creating volume directories.
    * If we return a regular error for transient errors - then that would cause volume directories to be removed. This is a problem if, previous error was "UncertainProgressError". We do not want a transient error to remove volume directories, in case previous mount operation is still in-progress.

Given above reasons - IMO having a transientError is not problematic. It makes it easier to reason about state of volumemanager and mount failures.

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Updated second case - since we moved secret fetching code to top of the function,  the defer is not executed if fetching secret fails.  But the main point IMO still stands.

File: pkg/volume/csi/csi_mounter.go [hunk 36]
```diff
@@ -254,10 +257,13 @@ func (c *csiMountMgr) SetUpAt(dir string, mounterArgs volume.MounterArgs) error
 	)
 
 	if err != nil {
-		if removeMountDirErr := removeMountDir(c.plugin, dir); removeMountDirErr != nil {
-			klog.Error(log("mounter.SetupAt failed to remove mount dir after a NodePublish() error [%s]: %v", dir, removeMountDirErr))
+		// If operation finished with error then we can remove the mount directory.
```
Comment (jingxu97) [inline pkg/volume/csi/csi_mounter.go]: MkdirAll() can be called right before NodePublishVolume call, right? so all previous errors does not need to worry about remove dir.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 35 above)
Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go]: > volumemanager has been designed to not track volumes that are not mounted (or for which mount failed with 100% certainity). Now we are saying - we will keep volumes which have failed to mount in "uncertain" state and hence they will require "teardown" and "unmountdevice" calls. This introduces additional design change into volumemanager and I hope that - no plugin breaks (or fail unmount call) when unmount is called for failed mounts. My intention has been to stick to code paths which are known to work.

For this one, actually plugin has to deal with "teardown while previous mount still in progress or actually failed mount already" after adding this uncertain state, I think. The sequence of event would be like
1. volume setup call returns with timeout error, add it into state
2. pod is deleted, volume tear down is called (meantime the mount might still in process or might failed or might succeeded)

> Mount is called and kubelet fails to fetch the secret(on first attempt): - If we return uncertainProgressError for them, then volume will be added to ASOW in uncertain state, even though mount call has not even been attempted. It seems wrong to accept a volume in ASOW. This PR also made a change that, fetching secret call has been moved up and hence if there was an error fetching secret, call returns early without even creating volume directories.

I thought mount is called after fetching the secret?

File: pkg/volume/csi/csi_client.go [hunk 37]
```diff
@@ -255,7 +259,10 @@ func (c *csiDriverClient) NodePublishVolume(
 	}
 
 	_, err = nodeClient.NodePublishVolume(ctx, req)
-	return err
+	if err != nil && !isFinalError(err) {
+		return volumetypes.NewUncertainProgressError(err.Error())
+	}
+	return nil
```
Comment (jsafrane) [inline pkg/volume/csi/csi_client.go]: `return err`!

It took me a while to find out why a pod is running after NodePublish error.

**Review by jsafrane — COMMENTED** [review]
Testing with the mock driver and found these issues:

* User deletes a pod, `NodeUnstage` times out (it never succeeds), user re-creates the pod -> `NodePublish` is called. `NodeStage` was expected to fix uncertain Stage.

* User force-deletes a pod, `NodeUnpublish` times out (it never succeeds), user re-creates the pod -> `NodePublish` is called, followed by `NodeUnpublish`. ~The pod gets Running even though kubelet tries to `Unpublish` the volume.~
    ```
    gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume",... "Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"}
    gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume",... "Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"}
    gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume",... "Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"}
    
    < pod created here >
    
    gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities",... "Error":""}
    gRPCCall: {"Method":"/csi.v1.Node/NodePublishVolume","Request":{"volume_id":"1","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/mypv/globalmount","target_path":"/var/lib/kubelet/pods/6c5f730f-ad66-4cdf-abec-c55a8c04b033/volumes/kubernetes.io~csi/mypv/mount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_context":{"name":"Mock Volume 1","storage.kubernetes.io/csiProvisionerIdentity":"1532709836099-8081-csi-mock"}},"Response":{},"Error":""}
    gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume","Request":{"volume_id":"1","target_path":"/var/lib/kubelet/pods/356b4361-7e05-47cc-beaa-e649363d1c5e/volumes/kubernetes.io~csi/mypv/mount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"}
    ```
    edit: my bad, this is correct. Kubelet published to a new pod dir and is still trying to unpublish the old pod dir.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 38]
```diff
@@ -442,20 +477,20 @@ func (asw *actualStateOfWorld) AddPodToVolume(
...
-			volumeGidValue:      volumeGidValue,
-			volumeSpec:          volumeSpec,
+			podName:                podName,
+			podUID:                 podUID,
+			mounter:                mounter,
+			blockVolumeMapper:      blockVolumeMapper,
+			outerVolumeSpecName:    outerVolumeSpecName,
+			volumeGidValue:         volumeGidValue,
+			volumeSpec:             volumeSpec,
+			volumeMountStateForPod: markVolumeOpts.VolumeMountState,
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: fixed

File: pkg/volume/csi/csi_client.go (hunk 37 above)
Comment (gnufied) [reply pkg/volume/csi/csi_client.go]: fixed. So we had tests for this but fake CSIClient had correct behaviour but real csi client had this bug.. :(

File: pkg/volume/util/types/types.go (hunk 34 above)
Comment (gnufied) [reply pkg/volume/util/types/types.go]: fixed

**Comment by gnufied** [comment]
@jsafrane I think fixing unmount code path we filed up as a follow up issue since this PR was getting too big as it is -  https://github.com/kubernetes/kubernetes/issues/85248

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 35 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: > I thought mount is called after fetching the secret?

I have been thinking about this and I think we still have a problem. Lets say - `MountDevice` is called and first attempt returns in `UncertainProgressError` which causes volume to be added to uncertain state. Second attempt however fails with a final error (not secret fetching error but lets say NodeStage itself failed) then because error was a final error - https://github.com/kubernetes/kubernetes/blob/6dbd521cfaf3b2abe69dce376b3b2a1cda5406e1/pkg/volume/csi/csi_attacher.go#L270 will remove the deviceMountPath from node. But volume is still in "Uncertain" state and must be cleaned up, but https://github.com/kubernetes/kubernetes/blob/6dbd521cfaf3b2abe69dce376b3b2a1cda5406e1/pkg/volume/csi/csi_attacher.go#L484 will throw an error because data directory from `deviceMountPath` is already removed..

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go]: What do we actually gain by removing `TransientOperationFailure` from this PR?

Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go]: My thought was if both with and without transaction error can work correctly, I prefer without transaction for simplicity. Later we don't need to worry about later when other ppl work on this code, they need to understand this logic well and set correctly types of error.

But as you point it out, if mount fails, metadata will be cleaned. Then when reconciler calls unmount, it will fail to get metadata. The logic here can help remove volume from actual state cache, so unmount does not need to be triggered. 

So I think this is good. Just to make sure we add enough comment about different types of errors

**Comment by jsafrane** [comment]
> I think fixing unmount code path we filed up as a follow up issue since this PR was getting too big as it is - #85248

#85248 mentions only NodeUnpublish timeout, not NodeUnstage. If I remember correctly, old implementation of this PR called NodeStage after NodeUnstage timeout or error && new pod appeared. See that last test in https://github.com/kubernetes/kubernetes/pull/82492#issuecomment-550396856

**Comment by jingxu97** [comment]
@jsafrane In your test case, you mentioned local pod volume dir is created even when MountDevice timesout. Is this still the case. Because from the logic of the code, if MountDevice returns errors, it should not move to MountVolume step?

**Comment by gnufied** [comment]
@jingxu97 that certainly would still be the case - as I mentioned in bug  - https://github.com/kubernetes/kubernetes/issues/84878 , the fact that just instantiating the `mounter` for CSI results in creation of pod local volume directories and they are left over even if `MountDevice` errors out. This is a bug. It exists in current k8s and this PR does not fixes it and hence I filed a separate bug to fix it. 

@jsafrane Are you sure `NodeStage` is not being called if `Unstage` times out but `NodUnpublish` succeeds? The way I see it - nothing in code would prevent calling `NodeStage` if volume was unmounted via `NodeUnpublish` because `stage` and `mount` operations are done as part of same operation and code does not check if volume is marked as "global mounted" before calling `NodeStage`. Here is my tests:

Pod is deleted and NodeUnpublish is successful:
```
gRPCCall: {"Method":"/csi.v1.Node/NodeUnpublishVolume","Request":{"volume_id":"4","target_path":"/var/lib/kubelet/pods/67560ff7-aa33-4d08-bc45-e74ba188603e/volumes/kubernetes.io~csi/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/mount"},"Response":{},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnstageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"
}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnstageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"
}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnstageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"
}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnstageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"
}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeUnstageVolume","Request":{"volume_id":"4","staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount"},"Response":null,"Error":"rpc error: code = DeadlineExceeded desc = Mock timeout"
}
```


Pod is re-created on same node:

```
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeStageVolume","Request":{"volume_id":"4","publish_context":{"device":"/dev/mock","readonly":"false"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount","volume_capability":{"A
ccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1","storage.kubernetes.io/csiProvisionerIdentity":"1576265141256-8081-io.kubernetes.storage.mock"}},"Response":{},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodePublishVolume","Request":{"volume_id":"4","publish_context":{"device":"/dev/mock","readonly":"false"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/globalmount","target_path":"/var/l
ib/kubelet/pods/9fc9e8bf-b47f-41d1-bf1e-1c278147f72d/volumes/kubernetes.io~csi/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/mount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"name":"pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1",
"storage.kubernetes.io/csiProvisionerIdentity":"1576265141256-8081-io.kubernetes.storage.mock"}},"Response":{},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetCapabilities","Request":{},"Response":{"capabilities":[{"Type":{"Rpc":{}}},{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":2}}}]},"Error":""}
gRPCCall: {"Method":"/csi.v1.Node/NodeGetVolumeStats","Request":{"volume_id":"4","volume_path":"/var/lib/kubelet/pods/9fc9e8bf-b47f-41d1-bf1e-1c278147f72d/volumes/kubernetes.io~csi/pvc-bafb07c3-6f11-4985-9903-6492e46f5dc1/mount"},"Response":{"usage":[{"total":1073741824,"unit":1}]},"
Error":""}
```

Having said that - the reason `NodeStage` is being called even if `NodeUnstage` is never successful is because mock driver does not create a mount point on `deviceMountPath` - if it did then https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L235 line will cause `MountDevice` to exit without ever calling `NodeStage`. So this is still a bug IMO and should be fixed, because for certain CSI driver implementation this will cause `NodeStage` to be never called.

**Comment by msau42** [comment]
I think we have separate problem of assuming things are mount points. 1) IsLikelyNotMount doesn't work for bind mounts on the rootfs, so this is problematic for a lot of local-based csi drivers 2) csi spec technically says things should be mount points, but k8s has been pretty lax about this so we would probably start breaking a lot of drivers if we tried to enforce it

**Comment by gnufied** [comment]
Can we safely call `NodeStage` even though `deviceMountPoint` is already a mount point? All CSI calls being idempotent - it should be safe to do that. We might be able to remove checks for mount point entirely before calling `NodeStage` RPC.

**Comment by jingxu97** [comment]
This PR is lgtm. Thanks a lot @gnufied for putting great effort on this!

**Comment by jsafrane** [comment]
Filed #86360 for Unstage timeout handling

/lgtm
/approve
