### PR TITLE
Moved gobindata, refactored ReadOrDie refs

### LINKED ISSUE #37007: test/e2e/framework cannot be imported into external projects
**Problem**
If you try to compile a project that has a test/e2e/framework as a dependency, we see the following error:
```
# github.com/sjug/project/vendor/k8s.io/kubernetes/test/e2e/framework
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:30: undefined: generated.Asset
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:33: undefined: generated.AssetNames
```
When we import test/e2e/framework as a dependency the `ReadOrDie(filepath string) []byte` depends on two assets that are generated by gobindata.

**Solution**
Modify test/e2e/framework to not depend on bindata.

### PR DESCRIPTION
**Pull request by sjug**
**What this PR does / why we need it**: Having gobindata inside of test/e2e/framework prevents external projects from importing the framework. Moving it out and managing refs fixes this problem.

**Which issue this PR fixes**: fixes #37007

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37094)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

File: test/e2e/e2e.go [hunk 1]
```diff
@@ -248,3 +253,49 @@ func RunE2ETests(t *testing.T) {
...
+	if err := runtime.DecodeInto(api.Codecs.UniversalDecoder(), json, &pod); err != nil {
+		return nil, err
+	}
+	return &pod, nil
+}
+
+// Run a test container to try and contact the Kubernetes api-server from a pod, wait for it
+// to flip to Ready, log its output and delete it.
+func RunKubernetesServiceTestContainer(c clientset.Interface, ns string) {
+	path := "test/images/clusterapi-tester/pod.yaml"
```
Comment (jayunit100) [inline test/e2e/e2e.go]: whoa interesting, so we need this for e2e.go to work ? that might be an issue.

File: test/e2e/e2e.go [hunk 2]
```diff
@@ -248,3 +253,49 @@ func RunE2ETests(t *testing.T) {
 
 	ginkgo.RunSpecsWithDefaultAndCustomReporters(t, "Kubernetes e2e suite", r)
 }
+
+func podFromManifest(filename string) (*api.Pod, error) {
```
Comment (jayunit100) [inline test/e2e/e2e.go]: ah i see, you're moving this into e2e.go because podFromManifest needs biodata?  I understand why, however, this is a new problem, b/c anybody using e2e.go, will now need to have bin datas on the path ?  maybe e2e.go shouldn't be calling podFromManifest?  is there a way this entire thing can be optional ... see comment below.

**Comment by jayunit100** [comment]
1) you can inline the json in e2e.go i think for now.  you can build the struct up...
```
&api.Pod{
		TypeMeta: unversioned.TypeMeta{
			Kind:       "Pod",
			APIVersion: "v1",
		},
		ObjectMeta: api.ObjectMeta{
			Name: "clusterapi-tester",
		},
		Spec: api.PodSpec{
			Containers: []api.Container{
				{ ...
```

to match
```
apiVersion: v1
kind: Pod
metadata:
  name: clusterapi-tester
spec:
  containers:
  - image: gcr.io/google_containers/clusterapi-tester:1.0
    name: clusterapi-tester
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
  restartPolicy: OnFailure
```

**Comment by jayunit100** [comment]
`[k8s.io] Kubectl client [k8s.io] Kubectl version should check is all data is printed [Conformance] 5m0s` failed, lets see if it fails again... 

@k8s-bot e2e test this

**Comment by jayunit100** [comment]
```

• [SLOW TEST:5.188 seconds]
[k8s.io] Kubectl client
/root/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:826
  [k8s.io] Kubectl version
  /root/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:826
    should check is all data is printed [Conformance]
    /root/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:930
```

Confirmed the test passed for me on sejug's branch, should be all good this time.  i wonder if that was an infra flake or a real flake?

File: test/e2e/e2e.go [hunk 3]
```diff
@@ -248,3 +253,49 @@ func RunE2ETests(t *testing.T) {
...
+	}
+	if err := runtime.DecodeInto(api.Codecs.UniversalDecoder(), json, &pod); err != nil {
+		return nil, err
+	}
+	return &pod, nil
+}
+
+// Run a test container to try and contact the Kubernetes api-server from a pod, wait for it
+// to flip to Ready, log its output and delete it.
+func RunKubernetesServiceTestContainer(c clientset.Interface, ns string) {
```
Comment (ixdy) [inline test/e2e/e2e.go]: minor suggestion: since it seems like nothing outside `e2e.go` uses this, unexport it by renaming `runKubernetesServiceTestContainer`?

File: test/e2e/examples.go [hunk 4]
```diff
@@ -586,3 +587,20 @@ func prepareResourceWithReplacedString(inputFile, old, new string) string {
 	podYaml := strings.Replace(string(data), old, new, 1)
 	return podYaml
 }
+
+func CreateFileForGoBinData(gobindataPath, outputFilename string) error {
```
Comment (ixdy) [inline test/e2e/examples.go]: same - unexport this.

File: test/e2e/generated/BUILD [hunk 5]
```diff
@@ -13,6 +13,7 @@ load(
 go_library(
     name = "go_default_library",
```
Comment (ixdy) [inline test/e2e/generated/BUILD]: this probably needs a dependency back to `//test/e2e/framework:go_default_library` now.

File: test/e2e/generated/gobindata_util.go [hunk 6]
```diff
@@ -14,24 +14,23 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
-package framework
+package generated
 
-//go:generate ../../../hack/update-bindata.sh
+import "k8s.io/kubernetes/test/e2e/framework"
```
Comment (ixdy) [inline test/e2e/generated/gobindata_util.go]: alternately, maybe rework this so it doesn't depend on `framework` at all?

**Review by ixdy — COMMENTED** [review]
generally looks fine. generated code continues to be one of go's weak points.

**Comment by ixdy** [comment]
@k8s-bot bazel build this

**Comment by ixdy** [comment]
@k8s-bot bazel test this

**Comment by ixdy** [comment]
OK, that build failure is already known and unrelated to your PR.

File: test/e2e/generated/gobindata_util.go (hunk 6 above)
Comment (jayunit100) [inline test/e2e/generated/gobindata_util.go]: Yeah that makes sense for bindata_util . Framework logging functions aren't that useful anyway :)

**Comment by timothysc** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by jayunit100** [comment]
looking at this now

File: test/e2e/e2e.go [hunk 7]
```diff
@@ -32,11 +32,16 @@ import (
 
 	"k8s.io/kubernetes/pkg/api"
 	"k8s.io/kubernetes/pkg/api/v1"
+	clientset "k8s.io/kubernetes/pkg/client/clientset_generated/release_1_5"
 	gcecloud "k8s.io/kubernetes/pkg/cloudprovider/providers/gce"
+	"k8s.io/kubernetes/pkg/runtime"
```
Comment (jayunit100) [inline test/e2e/e2e.go]: hmm looks like these imports are ordered funny?  but not breaking any known rule so its ok i guess.

File: test/e2e/e2e.go [hunk 8]
```diff
@@ -220,7 +225,7 @@ var _ = ginkgo.SynchronizedAfterSuite(func() {
 // generated in this directory, and cluster logs will also be saved.
 // This function is called on each Ginkgo node in parallel mode.
 func RunE2ETests(t *testing.T) {
-	runtime.ReallyCrash = true
+	runtimeutils.ReallyCrash = true
```
Comment (jayunit100) [inline test/e2e/e2e.go]: nit: why are we renaming this?

File: test/e2e/e2e.go (hunk 7 above)
Comment (sjug) [inline test/e2e/e2e.go]: Alphabetical? c < r < u?

Comment (sjug) [inline test/e2e/e2e.go]: Alphabetical? c < r < u?

File: test/e2e/e2e.go (hunk 8 above)
Comment (jayunit100) [inline test/e2e/e2e.go]: gotcha

File: test/e2e/e2e.go (hunk 7 above)
Comment (jayunit100) [inline test/e2e/e2e.go]: yup, the blocks are each sorted separately... makes sense.

File: test/e2e/e2e.go [hunk 9]
```diff
@@ -245,3 +250,49 @@ func RunE2ETests(t *testing.T) {
...
+		framework.Logf("Failed to create %v: %v", p.Name, err)
+		return
+	}
+	defer func() {
+		if err := c.Core().Pods(ns).Delete(p.Name, nil); err != nil {
+			framework.Logf("Failed to delete pod %v: %v", p.Name, err)
+		}
+	}()
+	timeout := 5 * time.Minute
+	if err := framework.WaitForPodCondition(c, ns, p.Name, "clusterapi-tester", timeout, testutils.PodRunningReady); err != nil {
```
Comment (sjug) [inline test/e2e/e2e.go]: Moved all the things

File: test/e2e/e2e.go [hunk 10]
```diff
@@ -32,11 +32,16 @@ import (
 
 	"k8s.io/kubernetes/pkg/api"
 	"k8s.io/kubernetes/pkg/api/v1"
+	clientset "k8s.io/kubernetes/pkg/client/clientset_generated/release_1_5"
```
Comment (timothysc) [inline test/e2e/e2e.go]: Is this what we're doing now?  Seems weird that we're hard coding version into clientset? 

/cc @deads2k

File: test/e2e/e2e.go (hunk 7 above)
Comment (timothysc) [inline test/e2e/e2e.go]: please re-order.

File: test/e2e/e2e.go (hunk 10 above)
Comment (sjug) [inline test/e2e/e2e.go]: That's from one of the several rebases that I had over the life of this PR so far.

Comment (deads2k) [inline test/e2e/e2e.go]: > Is this what we're doing now? Seems weird that we're hard coding version into clientset?

It's how the external client is versioned at the moment.  We are transitioning to use the versioned client so that we can eventually make use of the `kubernetes/client-go` client.

Using the internal client is now discouraged in non-api server locations.

File: test/e2e/generated/BUILD (hunk 5 above)
Comment (ixdy) [inline test/e2e/generated/BUILD]: since `gobindata_util.go` now depends on `github.com/golang/glog", add 
```
deps = [
    "//vendor:github.com/golang/glog"
],
```
after the `srcs` section.

**Review by ixdy — COMMENTED** [review]
please fix the dependency in the `BUILD` file; otherwise LGTM.

**Comment by ixdy** [comment]
LGTM2, thanks!

**Comment by ixdy** [comment]
I think your change to `hack/lib/golang.sh` got reverted during rebase.

https://github.com/kubernetes/kubernetes/blob/7ec3be4c8e22e2daa3391aca939f581a9d5d19da/hack/lib/golang.sh#L171 needs to be updated.

**Comment by sjug** [comment]
Indeed saw it already, and just testing the build locally. Thanks @ixdy

**Comment by ixdy** [comment]
/lgtm

AWS is known-broken right now, I think.
