### PR TITLE
Fix SELinux label comparison

### LINKED ISSUE #133424: SELinux warning controller does not report conflicts with ""
### What happened?

A pod with label `:::s0:c0,c2` should conflicts with a pod with label `:::` (or `""`).

Kubelet defaults the first three components of the label to `system_u:object_r:container_file_t:s0:c0,c2` / `system_u:object_r:container_file_t:` and these are two different labels. If the pods have `spec.securityContext.seLinuxChangePolicy: MountOption`, kubelet correctly reports the conflict + refuses to run the second pod with something like:
```
Unable to attach or mount volumes: unmounted volumes=[vol], unattached volumes=[], failed to process volumes=[vol]: conflicting SELinux labels of volume pvc-3f62d9ae-7ad0-47d4-8b5a-72656ace42e6: "system_u:object_r:container_file_t:s0:c0,c2" and ""
```

However, the SELinux warning controller does not report any conflict and it should. 

### What did you expect to happen?

SELinux warning controller should emit something like:

```
SELinuxLabel "" conflicts with pod testpod-c2 that uses the same volume as this pod with SELinuxLabel ":::s0:c0,c2". If both pods land on the same node, only one of them may access the volume.
```

### How can we reproduce it (as minimally and precisely as possible)?

Run two pods, one with `spec.securityContext.seLinuxOptions.level = "s0:c0,c2"` and the second one with `nil`.

### Anything else we need to know?

The controller runs in KCM, who does not know the operating system defaults for SELinux labels and thus skips comparison of empty SELinux label components. It should compare at least the last one, with SELinux level and categories. Those are not defaulted by the OS.

### Kubernetes version

<details>

Recent master,
```console
$ kubectl version
v1.34.0-beta.0.633+51786c186950bb
```
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When comparing SELinux labels in KCM, always compare the last component (level + categories). Don't expect that kubelet / the operating system will default them.

This PR comes with e2e tests that check for the new behavior.

#### Which issue(s) this PR is related to:
Fixes: #133424
Related to KEP: https://github.com/kubernetes/enhancements/issues/1710

#### Does this PR introduce a user-facing change?

```release-note
Fixed SELinux warning controller not emitting events on some SELinux label conflicts.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/volume/selinuxwarning/translator/selinux_translator.go [hunk 1]
```diff
@@ -61,11 +61,13 @@ func (c *ControllerSELinuxTranslator) SELinuxOptionsToFileLabel(opts *v1.SELinux
 // These labels must be generated by SELinuxOptionsToFileLabel above
 // (the function expects strict nr. of elements in the labels).
 // Since this translator cannot default missing components,
-// the missing components are treated as incomparable and they do not
+// the first three components treated as incomparable when missing and they do not
 // conflict with anything.
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/translator/selinux_translator.go]: nit: Can you add a comment about what result incomprable leads to? This function returns a boolean value but comparison has three states: conflict, notconflict, incomparable.

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/translator/selinux_translator.go]: I can see it misses a verb, still, it IMHO says what incomparable leads to.
"_the first three components **are** treated as incomparable when missing and they do not conflict with anything_". There is even an example below.

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/translator/selinux_translator.go]: I tried to rephrase it in a new commit
