### PR TITLE
Write Read, Patch & Replace ReplicaSet Status +3 endpoints

### LINKED ISSUE #100863: Write Read, Patch & Replace Replictest Status +3 endpoints
# Progress <code>[4/6]</code>

-   [X] APISnoop org-flow : [Read-Patch-Status-for-Replicaset.org](https://github.com/apisnoop/ticket-writing/blob/create-replicaset-status-lifecycle-test/Appsv1ReplicaSetStatusLifecycleTest.org)
-   [X] test approval issue : [kubernetes/kubernetes#100863](https://github.com/kubernetes/kubernetes/issues/100863)
-   [X] test pr : kuberenetes/kubernetes #101260
-   [X] two weeks soak start date : [testgrid-link](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&&width=5&include-filter-by-regex=should%20validate%20Replicaset%20Status%20endpoints&graph-metrics=test-duration-minutes) 25 May
-   [ ] two weeks soak end date : 8 June
-   [ ] test promotion pr : kubernetes/kubernetes #102349

# Identifying an untested feature Using APISnoop

According to this APIsnoop query, there are still some remaining ReplicaSet endpoints that are untested.

```sql-mode
    SELECT
      endpoint,
      path,
      kind
      FROM testing.untested_stable_endpoint
      where eligible is true
      and endpoint ilike '%ReplicaSetStatus'
      order by kind, endpoint desc
      limit 10;
```

```example
                  endpoint                 |                              path                              |    kind
  -----------------------------------------+----------------------------------------------------------------+------------
   replaceAppsV1NamespacedReplicaSetStatus | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
   readAppsV1NamespacedReplicaSetStatus    | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
   patchAppsV1NamespacedReplicaSetStatus   | /apis/apps/v1/namespaces/{namespace}/replicasets/{name}/status | ReplicaSet
  (3 rows)

```

# API Reference and feature documentation

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/kubernetes-api/)
-   [Kubernetes API / Workload Resources / ReplicaSet](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/replica-set-v1/)
-   [client-go - ReplicaSet](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/apps/v1/replicaset.go)

# The mock test

## Test outline

1.  Create a watch to track replica set events

2.  Create a replica set with a static label. Confirm that the pods are running.

3.  Get the replica set status. Parse the response and confirm that the replica set status conditions can be listed.

4.  Update the replica set status. Confirm via the watch that the status has been updated.

5.  Patch the replica set status. Confirm via the watch that the status has been patched.

## Test the functionality in Go

Using an existing [status lifecycle test](https://github.com/ii/kubernetes/blob/ca3aa6f5af1b545b116b52c717b866e43c79079b/test/e2e/apps/daemon_set.go#L812-L947) as a template for a new [ginkgo test](https://github.com/ii/kubernetes/blob/replicaset-status-test/test/e2e/apps/replica_set.go#L513-L642) for daemon set lifecycle test. Due to a test flake with patching the replica set status conditions the final &ldquo;watch/validation&rdquo; check is still be written.

### Patching the replica set causes test failure

    [It] should validate Replicaset Status endpoints
      /home/ii/go/src/k8s.io/kubernetes/test/e2e/apps/replica_set.go:155
    Apr  6 15:16:30.093: INFO: labels: name=sample-pod,pod=httpd
    STEP: Create a ReplicaSet
    STEP: Verify that the required pods have come up.
    Apr  6 15:16:30.099: INFO: Pod name sample-pod: Found 0 pods out of 1
    Apr  6 15:16:35.108: INFO: Pod name sample-pod: Found 1 pods out of 1
    STEP: ensuring each pod is running
    STEP: Getting /status
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs has Conditions: []
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.Replicas: 1
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.ReadyReplicas: 1
    Apr  6 15:16:35.136: INFO: ReplicaSet test-rs Status.AvailableReplicas: 1
    STEP: updating the ReplicaSet Status
    Apr  6 15:16:35.147: INFO: updatedStatus.Conditions: []v1.ReplicaSetCondition{v1.ReplicaSetCondition{Type:"StatusUpdate", Status:"True", LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Reason:"E2E", Message:"Set from e2e test"}}
    STEP: watching for the daemon set status to be updated
    Apr  6 15:16:35.149: INFO: Observed event: ADDED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Observed event: MODIFIED
    Apr  6 15:16:35.149: INFO: Found replica set test-rs in namespace replicaset-2037 with labels: map[name:sample-pod pod:httpd] annotations: map[] & Conditions: [{StatusUpdate True 0001-01-01 00:00:00 +0000 UTC E2E Set from e2e test}]
    Apr  6 15:16:35.149: INFO: Replica set test-rs has an updated status
    STEP: get ReplicaSet state
    Apr  6 15:16:35.152: INFO: rs1.Conditions: []v1.ReplicaSetCondition{v1.ReplicaSetCondition{Type:"StatusUpdate", Status:"True", LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Reason:"E2E", Message:"Set from e2e test"}}
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.FullyLabeledReplicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.Replicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.ReadyReplicas: 1
    Apr  6 15:16:35.152: INFO: ReplicaSet test-rs Status.AvailableReplicas: 1
    STEP: patching the ReplicaSet Status
    Apr  6 15:16:35.158: FAIL: Failed to patch replica set status. ReplicaSet.apps "test-rs" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]

### Full Stack Trace

    Unexpected error:
        <*errors.StatusError | 0xc00024d4a0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "ReplicaSet.apps \"test-rs\" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]",
                Reason: "Invalid",
                Details: {
                    Name: "test-rs",
                    Group: "apps",
                    Kind: "ReplicaSet",
                    UID: "",
                    Causes: [
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.fullyLabeledReplicas",
                        },
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.readyReplicas",
                        },
                        {
                            Type: "FieldValueInvalid",
                            Message: "Invalid value: 1: cannot be greater than status.replicas",
                            Field: "status.availableReplicas",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 422,
            },
        }
        ReplicaSet.apps "test-rs" is invalid: [status.fullyLabeledReplicas: Invalid value: 1: cannot be greater than status.replicas, status.readyReplicas: Invalid value: 1: cannot be greater than status.replicas, status.availableReplicas: Invalid value: 1: cannot be greater than status.replicas]
    occurred

The error looks to be part of the [validation code for replica sets](https://github.com/kubernetes/kubernetes/blob/b0abe89ae259d5e891887414cb0e5f81c969c697/pkg/apis/apps/validation/validation.go#L629-L651). Looking for suggestions on whats likely to be happening and how to best resolve the flake would be appreciated.

# Verifying increase in coverage with APISnoop

## Listing endpoints hit by the new e2e test

This query shows the endpoints hit within a short period of running the e2e test

```sql-mode
select distinct  endpoint, right(useragent,65) AS useragent
from testing.audit_event
where endpoint ilike '%ReplicaSetStatus%'
and release_date::BIGINT > round(((EXTRACT(EPOCH FROM NOW()))::numeric)*1000,0) - 60000
and useragent like 'e2e%'
order by endpoint
limit 10;
```

```example
                endpoint                 |                             useragent
-----------------------------------------+-------------------------------------------------------------------
 patchAppsV1NamespacedReplicaSetStatus   | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
 readAppsV1NamespacedReplicaSetStatus    | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
 replaceAppsV1NamespacedReplicaSetStatus | [sig-apps] ReplicaSet should validate Replicaset Status endpoints
(3 rows)

```

# Final notes

If a test with these calls gets merged, **test coverage will go up by 2 points**

This test is also created with the goal of conformance promotion.

---

/sig testing
/sig architecture
/area conformance

### PR DESCRIPTION
**Pull request by riaankleinhans**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
This PR adds a test to test the following untested endpoints:
- replaceAppsV1NamespacedReplicaSetStatus
- readAppsV1NamespacedReplicaSetStatus
- patchAppsV1NamespacedReplicaSetStatus

**Which issue(s) this PR fixes:**
Fixes #100863
**Testgrid Link:**
[Test](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&&width=5&include-filter-by-regex=should%20validate%20Replicaset%20Status%20endpoints&graph-metrics=test-duration-minutes)

**Special notes for your reviewer:**
Adds +3 endpoint test coverage (good for conformance)

**Does this PR introduce a user-facing change?:**
```
NONE

```

**Release note:**
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```
NONE

```

/sig testing
/sig architecture
/area conformance

### CODE REVIEW

File: test/e2e/apps/replica_set.go [hunk 1]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+	c := f.ClientSet
+	rsClient := c.AppsV1().ReplicaSets(ns)
+
+	// Define ReplicaSet Labels
+	rsPodLabels := map[string]string{
+		"name": "sample-pod",
+		"pod":  WebserverImageName,
+	}
+	labelSelector := labels.SelectorFromSet(rsPodLabels).String()
+	framework.Logf("labels: %v", labelSelector)
```
Comment (dims) [inline test/e2e/apps/replica_set.go:549]: is this needed? if so, could there be a longer description message?

File: test/e2e/apps/replica_set.go [hunk 2]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+			Status:  "True",
+			Reason:  "E2E",
+			Message: "Set from e2e test",
+		})
+
+		updatedStatus, err = rsClient.UpdateStatus(context.TODO(), statusToUpdate, metav1.UpdateOptions{})
+		return err
+	})
+	framework.ExpectNoError(err, "Failed to update status. %v", err)
+	framework.Logf("updatedStatus.Conditions: %#v", updatedStatus.Status.Conditions)
```
Comment (dims) [inline test/e2e/apps/replica_set.go:602]: need this log?

File: test/e2e/apps/replica_set.go [hunk 3]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+					cond.Message == "Set from e2e test" {
+					framework.Logf("Found replicaset %v in namespace %v with labels: %v annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.ObjectMeta.Labels, rs.Annotations, rs.Status.Conditions)
+					return found, nil
+				} else {
+					framework.Logf("Observed replicaset %v in namespace %v with annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.Annotations, rs.Status.Conditions)
+					return false, nil
+				}
+			}
+		}
+		framework.Logf("Observed event: %+v", event.Type)
```
Comment (dims) [inline test/e2e/apps/replica_set.go:629]: need this log?

File: test/e2e/apps/replica_set.go [hunk 4]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+	framework.ExpectNoError(err, "failed to locate replicaset %v in namespace %v", testReplicaSet.ObjectMeta.Name, ns)
+	framework.Logf("Replicaset %s has an updated status", rsName)
+
+	ginkgo.By("patching the Replicaset Status")
+	payload := []byte(`{"status":{"conditions":[{"type":"StatusPatched","status":"True"}]}}`)
+	framework.Logf("Patch payload: %v", string(payload))
+
+	patchedReplicaSet, err := rsClient.Patch(context.TODO(), rsName, types.MergePatchType, payload, metav1.PatchOptions{}, "status")
+	framework.ExpectNoError(err, "Failed to patch status. %v", err)
+	framework.Logf("Patched status conditions: %#v", patchedReplicaSet.Status.Conditions)
```
Comment (dims) [inline test/e2e/apps/replica_set.go:641]: one more

File: test/e2e/apps/replica_set.go [hunk 5]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+				if cond.Type == "StatusPatched" {
+					framework.Logf("Found replicaset %v in namespace %v with labels: %v annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.ObjectMeta.Labels, rs.Annotations, cond)
+					return found, nil
+				} else {
+					framework.Logf("Observed replicaset %v in namespace %v with annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.Annotations, cond)
+					return false, nil
+				}
+			}
+		}
+		framework.Logf("Observed event: %+v", event.Type)
```
Comment (dims) [inline test/e2e/apps/replica_set.go:666]: one more

File: test/e2e/apps/replica_set.go (hunk 3 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:629]: The above logging was due to [feedback](https://github.com/kubernetes/kubernetes/pull/96485#issuecomment-732335344) when trying to debug a test flake that uses a similar code snippet. Extra logging was added [back into the test](https://github.com/kubernetes/kubernetes/pull/97137) to address the concerns raised by @spiffxp.

File: test/e2e/apps/replica_set.go (hunk 5 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:666]: see comment above for line 629

File: test/e2e/apps/replica_set.go (hunk 2 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:602]: If the test was to flake at some point the idea was to have a reference point to help debug what status conditions we have at this point of the test and what we validate with the watch below.

File: test/e2e/apps/replica_set.go (hunk 4 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:641]: see comment above for line 602

File: test/e2e/apps/replica_set.go [hunk 6]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+	ginkgo.By("Create a Replicaset")
+	rs := newRS(rsName, replicas, rsPodLabels, WebserverImageName, WebserverImage, nil)
+	testReplicaSet, err := c.AppsV1().ReplicaSets(ns).Create(context.TODO(), rs, metav1.CreateOptions{})
+	framework.ExpectNoError(err)
+
+	ginkgo.By("Verify that the required pods have come up.")
+	err = e2epod.VerifyPodsRunning(c, ns, "sample-pod", false, replicas)
+	framework.ExpectNoError(err, "Failed to create pods: %s", err)
+
+	ginkgo.By("Getting /status")
```
Comment (ravisantoshgudimetla) [inline test/e2e/apps/replica_set.go:572]: Is the goal here just to hit `/status` endpoint? I ask because to get status sub-resource, `.Get()` method should have been enough similar to the approach you followed below.

File: test/e2e/apps/replica_set.go [hunk 7]
```diff
@@ -524,3 +534,138 @@ func testRSLifeCycle(f *framework.Framework) {
...
+	framework.ExpectNoError(err, "Failed to fetch the status of replicaset %s in namespace %s", rsName, ns)
+	rsStatusBytes, err := json.Marshal(rsStatusUnstructured)
+	framework.ExpectNoError(err, "Failed to marshal unstructured response. %v", err)
+
+	var rsStatus appsv1.ReplicaSet
+	err = json.Unmarshal(rsStatusBytes, &rsStatus)
+	framework.ExpectNoError(err, "Failed to unmarshal JSON bytes to a replicaset object type")
+	framework.Logf("Replicaset %s has Conditions: %v", rsName, rsStatus.Status.Conditions)
+
+	ginkgo.By("updating the Replicaset Status")
```
Comment (ravisantoshgudimetla) [inline test/e2e/apps/replica_set.go:584]: We usually expect the controller to update the status not by other actor. So, I am wondering if we are just hitting this to increase the coverage where as we in reality this cannot and shouldn't happen

Comment (ravisantoshgudimetla) [reply test/e2e/apps/replica_set.go:584]: I am wondering if you can mimic the patch by modifying the spec and watch if the status subresource has been patched instead of manually updating the status

**Review by ravisantoshgudimetla — CHANGES_REQUESTED** [review]
Thank you for working on this @Riaankl. I have few questions around the api resources being used directly. Please look at my comments.

File: test/e2e/apps/replica_set.go (hunk 6 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:572]: @ravisantoshgudimetla I'm on the same team has @Riaankl and wrote this test to be part of conformance.

Yes, the goal is to hit the `/status` endpoint. The `.Get()` method can't access the status sub-resource, so it requires the dynamic client.

File: test/e2e/apps/replica_set.go (hunk 7 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go:584]: The process of checking `/status` endpoints has gone through a number of discussions in conformance meetings for [Service Status endpoints](https://github.com/kubernetes/kubernetes/issues/94867) and [API Service Status](https://github.com/ii/kubernetes/blob/apiservice-status-endpoints/test/e2e/apimachinery/aggregator.go#L546-L670). 

I'm trying to have a clean common pattern for testing any `/status` endpoint no matter the resource.

**Review by ravisantoshgudimetla — APPROVED** [review]
Thank you @Riaankl and @heyste for working on this PR.

/lgtm

**Comment by Riaankl** [comment]
/assign @soltysh @mattfarina
This e2e test is to clean up the last few ReplicaSet endpoints.
Following the same pattern as previous Mergde Conformance tests
It has been reviewed, can we please get a `/approve` to get it on the test grid.

**Comment by heyste** [comment]
/test pull-kubernetes-node-e2e-containerd

x2 flakes 
- `Node Tests`
- `E2e Node  Suite: [sig-node] Summary API [NodeConformance] when querying  /stats/summary should report resource usage through the stats api`

File: test/e2e/apps/replica_set.go (hunk 1 above)
Comment (heyste) [reply test/e2e/apps/replica_set.go]: Removed.

File: test/e2e/apps/replica_set.go [hunk 8]
```diff
@@ -524,3 +535,135 @@ func testRSLifeCycle(f *framework.Framework) {
...
+					cond.Message == "Set from e2e test" {
+					framework.Logf("Found replicaset %v in namespace %v with labels: %v annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.ObjectMeta.Labels, rs.Annotations, rs.Status.Conditions)
+					return found, nil
+				}
+				framework.Logf("Observed replicaset %v in namespace %v with annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.Annotations, rs.Status.Conditions)
+			}
+		}
+		object := strings.Split(fmt.Sprintf("%v", event.Object), "{")[0]
+		framework.Logf("Observed %v event: %+v", object, event.Type)
+		return false, nil
```
Comment (heyste) [inline test/e2e/apps/replica_set.go:629]: @ravisantoshgudimetla Thanks for the earlier review. I've updated this section as there was a potential bug where I had an extra `return`. Also, line 627-8 includes the object for the event now.

Can I get another lgtm? TIA

File: test/e2e/apps/replica_set.go [hunk 9]
```diff
@@ -524,3 +535,135 @@ func testRSLifeCycle(f *framework.Framework) {
...
+			for _, cond := range rs.Status.Conditions {
+				if cond.Type == "StatusPatched" {
+					framework.Logf("Found replicaset %v in namespace %v with labels: %v annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.ObjectMeta.Labels, rs.Annotations, cond)
+					return found, nil
+				}
+				framework.Logf("Observed replicaset %v in namespace %v with annotations: %v & Conditions: %v", rs.ObjectMeta.Name, rs.ObjectMeta.Namespace, rs.Annotations, cond)
+			}
+		}
+		object := strings.Split(fmt.Sprintf("%v", event.Object), "{")[0]
+		framework.Logf("Observed %v event: %+v", object, event.Type)
```
Comment (heyste) [inline test/e2e/apps/replica_set.go:664]: @ravisantoshgudimetla same as line 624-9

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm
