### PR TITLE
set secondary address on host-network pods

### LINKED ISSUE #105320: Host Networking pods get only 1 IP address during fresh deployment or reboot of nodes in dual stack enabled cluster
**What happened:**

We have installed k8s cluster on openstack cloud provider setup. K8s cluster is dual-stack enabled.
During fresh deployment or worker node reboots (master nodes , worker nodes) , k8s control plane pods (other host networking pods aswell) such as kube-proxy, kube-scheduler , kube-controller-manager get only 1 IP address instead of dual-stack address.

**What you expected to happen:**

We expect all host networking pods to get dual-stack addresses , since cluster is dual-stack enabled.

**How to reproduce it (as minimally and precisely as possible):**
a) Openstack cloud provider setup with minimum 4-5 VMs.
b) 3 master nodes, 2 worker nodes
c) Execute simultaneous reboot of all nodes.

Environment:
Kubernetes version : v1.22.0

### PR DESCRIPTION
**Pull request by aojea**
host-network pods IPs are obtained from the reported kubelet nodeIPs.

Historically, host-network podIPs are immutable once set, but when
we've added dual-stack support, we didn't consider that the secondary
IP address may not be present at the same time that the primary nodeIP.

If a secondary IP address is added to a node after the host-network pods
IPs are set, we can add the secondary host-network pod IP address
maintaining the current behavior of not updating the current podIPs on
host-network pods.

This is an alternative to https://github.com/kubernetes/kubernetes/pull/105410 ,
without having to change the kubelet and host-network podIPs behavior
xref: https://github.com/kubernetes/enhancements/pull/3000

/kind bug
```release-note
CRI-API: IPs returned by PodSandboxNetworkStatus are ignored by the kubelet for host-network pods.
```
Fixes: #105320

### CODE REVIEW

File: pkg/kubelet/kubelet_pods_test.go [hunk 1]
```diff
@@ -3284,6 +3284,7 @@ func TestGenerateAPIPodStatusHostNetworkPodIPs(t *testing.T) {
 			criPodIPs: []string{"192.168.0.1"},
 			podIPs: []v1.PodIP{
 				{IP: "192.168.0.1"},
+				{IP: "fd01::1234"},
```
Comment (aojea) [inline pkg/kubelet/kubelet_pods_test.go:3287]: Interesting corner case from DanWinships test cases
```
			name: "CRI PodIPs override NodeAddresses",
			nodeAddresses: []v1.NodeAddress{
				{Type: v1.NodeInternalIP, Address: "10.0.0.1"},
				{Type: v1.NodeInternalIP, Address: "fd01::1234"},
			},
			criPodIPs: []string{"192.168.0.1"},
			podIPs: []v1.PodIP{
				{IP: "192.168.0.1"},
				{IP: "fd01::1234"},
```

CRIO and containerd doesn't send IPs for host network pods
https://github.com/cri-o/cri-o/blob/8d4d158935929800c4300b82eb4b5a83ded400f4/server/sandbox_network.go#L34-L36

https://github.com/containerd/containerd/blob/4921fb6b63e5476e54fb7e2cf93c3b505f1c09cb/pkg/cri/store/sandbox/sandbox.go#L40-L41

but they can.
I think that the discussion here is if override means removing IPs or just updating the ones that it sets leaving the others as is

**Comment by aojea** [comment]
```
Kubernetes e2e suite: [sig-node] Pods should delete a collection of pods [Conformance] expand_less
```


/test pull-kubernetes-e2e-kind

**Comment by danwinship** [comment]
> we didn't consider that the secondary
> IP address may not be present at the same time that the primary nodeIP.

why wouldn't it be? / why wouldn't we expect you to restart kubelet in that case?

> CRIO and containerd doesn't send IPs for host network pods
> ...
> but they can.

So, originally, cri-o _did_ send IPs for host network pods, and kubelet just accepted them. But this was a bad idea, because it means that if you wanted to override kubelet's `--node-ip`, then you probably _also_ had to override cri-o's idea of what the default host IP was or your host-network pods would end up with the wrong IP. IIRC, kubelet already had the fallback code to set host-network podIPs itself if the CRI didn't do it, so we just changed cri-o to leave the pod IPs blank for hostNetwork pods.

I'm not sure what the historical situation with containerd was.

The unit test is testing that if the CRI _does_ set the pod IPs, that kubelet continues to behave like it did historically, so as to not break CRIs that still do that.

**Comment by aojea** [comment]
> why wouldn't it be? / why wouldn't we expect you to restart kubelet in that case?

Because that is the issue reported, and kubelet will race again :smile: https://github.com/kubernetes/kubernetes/issues/105320 

> The unit test is testing that if the CRI does set the pod IPs, that kubelet continues to behave like it did historically, so as to not break CRIs that still do that.

agree, that is why I've commented here https://github.com/kubernetes/kubernetes/pull/106715#discussion_r758454031

> I think that the discussion here is if override means removing IPs or just updating the ones that it sets leaving the others as is

**Review by thockin — COMMENTED** [review]
overall, I think the simpler and more obvious this is, the better.  I like this.

File: pkg/kubelet/kubelet_pods_test.go (hunk 1 above)
Comment (thockin) [reply pkg/kubelet/kubelet_pods_test.go:3287]: I think override means "ignore CRI".

Do we think it is EVER correct for CRI to return host-net IPs?

Comment (aojea) [reply pkg/kubelet/kubelet_pods_test.go:3287]: > Do we think it is EVER correct for CRI to return host-net IPs?

I think we all agree that is a bad idea, but it seems that it is the way it was https://github.com/kubernetes/kubernetes/pull/106715#issuecomment-985943968

Comment (aojea) [reply pkg/kubelet/kubelet_pods_test.go:3287]: @danwinship what do you think?

Comment (dcbw) [reply pkg/kubelet/kubelet_pods_test.go:3287]: If *nothing* else we should specify what Kubernetes expects host-network pod IPs to be (order, number, type). I don't like leaving that an undefined wild-west.

And I think we should enforce that expectation. If there are corner cases that are currently possible that we break, I think a KEP should get written to implement that corner-case correctly.

Comment (aojea) [reply pkg/kubelet/kubelet_pods_test.go:3287]: Just for reference, the CRI IPs are obtained in kuberuntime in `GetPodStatus()`

https://github.com/kubernetes/kubernetes/blob/571e067cddfbb0c2a3092ab9d3be3074043e3810/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L1064

and it seems they are stored in the PLEG cache

https://github.com/kubernetes/kubernetes/blob/571e067cddfbb0c2a3092ab9d3be3074043e3810/pkg/kubelet/pleg/generic.go#L407-L419

This cache is used to `syncPod()` from the PodWorker

https://github.com/kubernetes/kubernetes/blob/571e067cddfbb0c2a3092ab9d3be3074043e3810/pkg/kubelet/pod_workers.go#L904

and `generateAPIPodStatus()`

https://github.com/kubernetes/kubernetes/blob/571e067cddfbb0c2a3092ab9d3be3074043e3810/pkg/kubelet/kubelet.go#L1554

Comment (aojea) [reply pkg/kubelet/kubelet_pods_test.go:3287]: it seems there is no way to differentiate between:
- the CRI setting the IPs from CRI
- CRI NOT returning IPs, but Pod status IPs updated incrementally

Comment (aojea) [reply pkg/kubelet/kubelet_pods_test.go:3287]: I've updated the commit with the CRI API change

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 2]
```diff
@@ -445,6 +445,7 @@ message PodIP{
     string ip = 1;
 }
 // PodSandboxNetworkStatus is the status of the network for a PodSandbox.
+// Ignored for pods sharing the host networking namespace.
```
Comment (aojea) [inline staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:448]: @mrunalp you can find the context in this thread https://github.com/kubernetes/kubernetes/pull/106715/files#r758454031

**Comment by aojea** [comment]
@thockin @danwinship I've updated the CRI API , can you please take another look?

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -1520,10 +1520,20 @@ func (kl *Kubelet) generateAPIPodStatus(pod *v1.Pod, podStatus *kubecontainer.Po
...
-			if kubecontainer.IsHostNetworkPod(pod) && s.PodIP == "" {
-				s.PodIP = hostIPs[0].String()
-				s.PodIPs = []v1.PodIP{{IP: s.PodIP}}
-				if len(hostIPs) == 2 {
+			// HostNetwork Pods inherit the NodeIPs as PodIPs.
+			// For historical reasons, these PodIPs are immutable once set,
+			// If the Node changes its IPs the user has to restart the Kubelet
+			// so the HostNetwork pods update their IPs. We may change this in a future
+			// https://github.com/kubernetes/enhancements/pull/3000
+			// but since it changes the current behavior "here be dragons"
```
Comment (danwinship) [inline pkg/kubelet/kubelet_pods.go:1528]: I'm not sure you need to explain that much. Also, you spend several sentences explaining that `podIPs` is immutable, and then add code that changes it.

```
// HostNetwork Pods inherit the node IPs as PodIPs. They are immutable once set,
// other than that if the node becomes dual-stack, we add the secondary IP.
```

(though probably we should remove the second IP on dual-stack-to-single-stack downgrade too)

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto (hunk 2 above)
Comment (danwinship) [inline staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:448]: Is there a chance we might add new fields in the future that it wouldn't make sense to ignore for hostNetwork pods? Maybe hedge a little bit here and prepend "Currently" ?

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1528]: yeah, I see my gap on the language, I try to mean that once a PodIP exist that never changes, however, you can add a new IP if not exist, is not the array that is immutable (it can grow), is the element in the array that can't change once set

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto (hunk 2 above)
Comment (aojea) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:448]: great point

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1528]: > (though probably we should remove the second IP on dual-stack-to-single-stack downgrade too)

this can open a new set of corner cases and we don't have a good history here, per example, I think that all the dual stack services that are stored will fail in validation on a migration like this.

**Review by thockin — COMMENTED** [review]
/approve

File: pkg/kubelet/kubelet_pods.go [hunk 4]
```diff
@@ -1520,10 +1520,16 @@ func (kl *Kubelet) generateAPIPodStatus(pod *v1.Pod, podStatus *kubecontainer.Po
 			klog.V(4).InfoS("Cannot get host IPs", "err", err)
 		} else {
 			s.HostIP = hostIPs[0].String()
-			if kubecontainer.IsHostNetworkPod(pod) && s.PodIP == "" {
-				s.PodIP = hostIPs[0].String()
-				s.PodIPs = []v1.PodIP{{IP: s.PodIP}}
-				if len(hostIPs) == 2 {
+			// HostNetwork Pods inherit the node IPs as PodIPs. They are immutable once set,
+			// other than that if the node becomes dual-stack, we add the secondary IP.
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/kubelet/kubelet_pods.go:1524]: https://github.com/kubernetes/kubernetes/pull/106715#discussion_r786176603

**Comment by aojea** [comment]
/assign @mrunalp 
for the CRI API doc update

File: pkg/kubelet/kubelet_pods_test.go (hunk 1 above)
Comment (mrunalp) [reply pkg/kubelet/kubelet_pods_test.go:3287]: Yes, this sounds good from the CRI API perspective :+1:

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 5]
```diff
@@ -445,6 +445,7 @@ message PodIP{
     string ip = 1;
 }
 // PodSandboxNetworkStatus is the status of the network for a PodSandbox.
+// Currently ignored for pods sharing the host networking namespace.
```
Comment (mrunalp) [inline staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:448]: Could you also update the v1alpha2 proto? We are keeping both files the same till we remove that file.

**Comment by aojea** [comment]
updated the CRI-API godoc on v1 and v1alpha2 too

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
