### PR TITLE
Fix DefaultTolerationSeconds admission plugin

### LINKED ISSUE #42716: DefaultTolerationSeconds admission controller is not working
Default toleration should be applied to newly created Pods. But:
```bash
$ kubectl run test --image=kubernetes/pause
$ kubectl get pod -o json
```
Gives result:
```json
            "spec": {
                "containers": [
                    {
                        "image": "kubernetes/pause",
                        "imagePullPolicy": "Always",
                        "name": "test",
                        "resources": {
                            "requests": {
                                "cpu": "100m"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-x4vbw",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "nodeName": "e2e-test-gmarek-minion-group-9vzb",
                "restartPolicy": "Always",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "default",
                "serviceAccountName": "default",
                "terminationGracePeriodSeconds": 30,
                "volumes": [
                    {
                        "name": "default-token-x4vbw",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "default-token-x4vbw"
                        }
                    }
                ]
            },
```

Log from the apiserver says:
```
E0308 07:16:37.959599       5 admission.go:71] expected pod but got Pod
```
Which indicates some problems with casting:
```
 69   pod, ok := attributes.GetObject().(*v1.Pod)
 70   if !ok {
 71     glog.Errorf("expected pod but got %s", attributes.GetKind().Kind)
 72     return nil
 73   }
```

This admission controller is using:
```
"k8s.io/kubernetes/pkg/api/v1"
```

Which is probably wrong, as I guess it should be `api/v1/` from client-go. Another example when apimachinery refactoring bites us. cc @deads2k @lavalamp @caesarxuchao @brendandburns 

@kevin-wangzefeng please fix, and verify that it's working.

cc @davidopp

### PR DESCRIPTION
**Pull request by aveshagarwal**
DefaultTolerationSeconds is not working as expected. It is supposed to add default tolerations (for unreachable and notready conditions). but no pod was getting these toleration. And api server was throwing this error:

```
Mar 08 13:43:57 fedora25 hyperkube[32070]: E0308 13:43:57.769212   32070 admission.go:71] expected pod but got Pod
Mar 08 13:43:57 fedora25 hyperkube[32070]: E0308 13:43:57.789055   32070 admission.go:71] expected pod but got Pod
Mar 08 13:44:02 fedora25 hyperkube[32070]: E0308 13:44:02.006784   32070 admission.go:71] expected pod but got Pod
Mar 08 13:45:39 fedora25 hyperkube[32070]: E0308 13:45:39.754669   32070 admission.go:71] expected pod but got Pod
Mar 08 14:48:16 fedora25 hyperkube[32070]: E0308 14:48:16.673181   32070 admission.go:71] expected pod but got Pod
```

The reason for this error is that the input to admission plugins is internal api objects not versioned objects so expecting versioned object is incorrect. Due to this, no pod got desired tolerations and it always showed:

```
Tolerations: <none>
```

After this fix, the correct  tolerations are being assigned to pods as follows:

```
Tolerations:	node.alpha.kubernetes.io/notReady=:Exists:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable=:Exists:NoExecute for 300s
```

@davidopp @kevin-wangzefeng @kubernetes/sig-scheduling-pr-reviews @kubernetes/sig-scheduling-bugs @derekwaynecarr 

Fixes https://github.com/kubernetes/kubernetes/issues/42716

### CODE REVIEW

**Comment by davidopp** [comment]
I assume this is a fix for #42716?

**Comment by aveshagarwal** [comment]
@davidopp yes looks like. Though surprisingly I just noticed this in my local cluster when doing some testing for taint based pod evictions and did not know there is an issue already.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
BTW why does no test catch this problem? Can we add one?

File: plugin/pkg/admission/defaulttolerationseconds/admission.go [hunk 1]
```diff
@@ -62,11 +62,11 @@ func NewDefaultTolerationSeconds() admission.Interface {
 }
 
 func (p *plugin) Admit(attributes admission.Attributes) (err error) {
-	if attributes.GetResource().GroupResource() != v1.Resource("pods") {
+	if attributes.GetResource().GroupResource() != api.Resource("pods") {
```
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: Also return nil if it has a subresource

File: plugin/pkg/admission/defaulttolerationseconds/admission.go [hunk 2]
```diff
@@ -62,11 +62,11 @@ func NewDefaultTolerationSeconds() admission.Interface {
...
 		return nil
 	}
 
-	pod, ok := attributes.GetObject().(*v1.Pod)
+	pod, ok := attributes.GetObject().(*api.Pod)
 	if !ok {
 		glog.Errorf("expected pod but got %s", attributes.GetKind().Kind)
```
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: return errors.NewBadRequest

**Comment by aveshagarwal** [comment]
@davidopp the issue is that we dont have e2es for admission plugins.

**Comment by ncdc** [comment]
Removing lgtm until comments are addressed.

cc @liggitt

**Comment by ncdc** [comment]
Don't need an e2e. Can do this with an integration test.

File: plugin/pkg/admission/defaulttolerationseconds/admission.go (hunk 1 above)
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: Probably should also check ignore operations other than create and update

Comment (liggitt) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: operations other than create/delete are already filtered out

**Comment by aveshagarwal** [comment]
@ncdc fixed comments. PTAL.

File: plugin/pkg/admission/defaulttolerationseconds/admission.go [hunk 3]
```diff
@@ -62,13 +61,18 @@ func NewDefaultTolerationSeconds() admission.Interface {
...
+	if attributes.GetSubresource() != "" {
+		// only run the checks below on pods proper and not subresources
 		return nil
 	}
 
-	pod, ok := attributes.GetObject().(*v1.Pod)
+	pod, ok := attributes.GetObject().(*api.Pod)
 	if !ok {
-		glog.Errorf("expected pod but got %s", attributes.GetKind().Kind)
+		errors.NewBadRequest("expected pod but got some other resource")
```
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: you have to return the error

File: plugin/pkg/admission/defaulttolerationseconds/admission.go [hunk 4]
```diff
@@ -62,13 +61,18 @@ func NewDefaultTolerationSeconds() admission.Interface {
 }
 
 func (p *plugin) Admit(attributes admission.Attributes) (err error) {
-	if attributes.GetResource().GroupResource() != v1.Resource("pods") {
+	if attributes.GetResource().GroupResource() != api.Resource("pods") {
+		return nil
+	}
+
+	if attributes.GetSubresource() != "" {
```
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: check for len > 0

**Comment by aveshagarwal** [comment]
@ncdc PTAL.

**Comment by kevin-wangzefeng** [comment]
@k8s-bot cvm gce e2e test this

File: plugin/pkg/admission/defaulttolerationseconds/admission.go [hunk 5]
```diff
@@ -62,28 +61,32 @@ func NewDefaultTolerationSeconds() admission.Interface {
...
-	if !ok {
-		glog.Errorf("expected pod but got %s", attributes.GetKind().Kind)
+	if len(attributes.GetSubresource()) > 0 {
+		// only run the checks below on pods proper and not subresources
 		return nil
 	}
 
+	pod, ok := attributes.GetObject().(*api.Pod)
+	if !ok {
+		return errors.NewBadRequest("expected pod but got some other resource")
```
Comment (ncdc) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: @liggitt would you want to see the `%T` type, or is this ok for now?

File: test/integration/defaulttolerationseconds/defaulttolerationseconds_test.go [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+		}
+		if tolerations[i].MatchToleration(&nodeUnreachable) {
+			if api.Semantic.DeepEqual(tolerations[i], nodeUnreachable) {
+				found++
+				continue
+			}
+		}
+	}
+
+	if found != 2 {
```
Comment (ncdc) [inline test/integration/defaulttolerationseconds/defaulttolerationseconds_test.go]: If there are more than 2 tolerations in the spec, is that ok?

**Comment by ncdc** [comment]
I'm ok with the admission fixes. I'll leave the remaining bits (new integration test) to @davidopp @kevin-wangzefeng @gmarek @kubernetes/sig-scheduling-pr-reviews

File: test/integration/defaulttolerationseconds/defaulttolerationseconds_test.go (hunk 6 above)
Comment (aveshagarwal) [inline test/integration/defaulttolerationseconds/defaulttolerationseconds_test.go]: The logic here is that spec might have more than 2 tolerations but only one for notReady and Unreachable each.

File: plugin/pkg/admission/defaulttolerationseconds/admission.go (hunk 5 above)
Comment (liggitt) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: yeah, include the type in the message

Comment (aveshagarwal) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: NewBadRequest does not allow passing more than one argument.

Comment (liggitt) [inline plugin/pkg/admission/defaulttolerationseconds/admission.go]: `fmt.Sprintf("expected *api.Pod but got %T", attributes.GetObject())`?

**Comment by aveshagarwal** [comment]
@liggitt PTAL.

**Comment by liggitt** [comment]
message lgtm

**Comment by aveshagarwal** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by aveshagarwal** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by aveshagarwal** [comment]
@davidopp @kevin-wangzefeng @liggitt all tests passed.

File: staging/src/k8s.io/client-go/pkg/api/helpers.go [hunk 7]
```diff
@@ -465,6 +465,44 @@ const (
 	ObjectTTLAnnotationKey string = "node.alpha.kubernetes.io/ttl"
 )
 
+// Tries to add a toleration to annotations list. Returns true if something was updated
```
Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: s/Tries/AddOrUpdateTolerationInPod tries/ for golint.

File: staging/src/k8s.io/client-go/pkg/api/helpers.go [hunk 8]
```diff
@@ -465,6 +465,44 @@ const (
...
+
+		newTolerations = append(newTolerations, podTolerations[i])
+	}
+
+	if !updated {
+		newTolerations = append(newTolerations, *toleration)
+	}
+
+	pod.Spec.Tolerations = newTolerations
+	return true, nil
```
Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: `return updated, nil` ?

Comment (aveshagarwal) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: No, it should be true always at this point, because either one of existing toleration was updated or a new was added to the pod's toleration list.

File: staging/src/k8s.io/client-go/pkg/api/helpers.go (hunk 7 above)
Comment (aveshagarwal) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: fixed it. thanks.

**Comment by kevin-wangzefeng** [comment]
LGTM, thanks!

**Comment by aveshagarwal** [comment]
@davidopp @kevin-wangzefeng would appreciate if someone could lgtm?

**Comment by davidopp** [comment]
Thanks!

File: staging/src/k8s.io/client-go/pkg/api/helpers.go (hunk 8 above)
Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: Got that, thanks very much.

File: staging/src/k8s.io/client-go/pkg/api/helpers.go [hunk 9]
```diff
@@ -465,6 +465,44 @@ const (
 	ObjectTTLAnnotationKey string = "node.alpha.kubernetes.io/ttl"
 )
 
+// AddOrUpdateTolerationInPod tries to add a toleration to the pod's toleration list.
+// Returns true if something was updated, false otherwise.
+func AddOrUpdateTolerationInPod(pod *Pod, toleration *Toleration) (bool, error) {
```
Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: According to the `returns`, it'll never return error; so we will not reject any pods. Should we check whether "something was updated" ? 

/cc @davidopp @kevin-wangzefeng @gmarek @ncdc

Comment (davidopp) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: This admission controller isn't supposed to reject pods. It's supposed to add the tolerations if they do not already exist, and otherwise do nothing. So I think the current behavior is correct?

Comment (aveshagarwal) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: yes an input pod is never rejected, except updated or not.

Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: I think we will reject pods if failed to update it, e.g. `err != nil`; but when will this func return error (`err != nil`)? My understanding is that the following will be the return value of this func, although it always return err(nil) for now:
* if add or update, return `true, nil`
* if no action (existed), return `false, nil`
* if any error, return `_, err`

Current behavior seems correct, but confused by its return value, e.g. when will this func return error? :).

Comment (aveshagarwal) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: error was returned when using annotations, but not any more.

Comment (k82cn) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: So, how about remove it at #42964 ?

Comment (aveshagarwal) [inline staging/src/k8s.io/client-go/pkg/api/helpers.go]: yes sounds good.
