### PR TITLE
test: Fix image credential pulls test node scheduling

### LINKED ISSUE #135375: [Failing CI Test] node-kubelet-serial-crio
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio

Logs like "failed to reset injector because the CRI Proxy is undefined", "failed to run ssh command" etc.

### Which tests are failing?

- ci-kubernetes-node-kubelet-serial-cri-o.Overall
- kubetest.Node Tests
- kubetest.Timeout[Changes (https://github.com/kubernetes/kubernetes/compare/b6e83d29f...c245b40b8?)

### Since when has it been failing?

11/05 is as far back as the testgrid shows

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio

### Reason for failure (if possible)

From weekly ci meeting, @haircommander suggested it could be a Service Account issue

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Fixes a node scheduling bug in the image credential pulls test that was causing test timeouts in the serial CRI-O node e2e suite.

The registry and test pods were being scheduled on different nodes. When the test pod tried to pull images from `localhost:5000`, it couldn't reach the registry running on a different node, causing test failures.

The fix ensures both the registry and test pods run on the same node by using the registry node for scheduling the test pod. In node e2e tests, this is the single test node, so proper affinity is established.

#### Which issue(s) this PR is related to:

Fixes #135375

#### Special notes for your reviewer:

- Related PR: #135244 (identical node scheduling fix for a different test)
- Test-infra fixes: kubernetes/test-infra#35946 (CRI-O insecure registry config), kubernetes/test-infra#35969 (CRI-O upgrade including cri-o/cri-o#9615)

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation:

```docs
None
```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_image.go [hunk 1]
```diff
@@ -82,6 +82,10 @@ func (m *kubeGenericRuntimeManager) GetImageRef(ctx context.Context, image kubec
 	if resp.Image == nil {
 		return "", nil
 	}
+	// Prefer returning a digest reference over an image ID to ensure pull record lookups work correctly.
```
Comment (stlaz) [inline pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: This should be a different function

**Review by stlaz — CHANGES_REQUESTED** [review]

File: pkg/kubelet/kuberuntime/kuberuntime_image.go (hunk 1 above)
Comment (saschagrunert) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: Do you mind elaborating on this?

Comment (stlaz) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: /hold
From what I understand, image.ID is the local runtime ID of the image, whereas the RepoDigest is a global identifier, correct? Why combine these?

Comment (saschagrunert) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: How should we combine these? Both are unique identifiers to an image which serve a different purpose. We had discussions in the past to change what the runtimes return but that would also clash with the kubelet garbage collection. Having the kuberuntime preferring digests over ID's seems to be the least intrusive change to fix those test cases.

Comment (stlaz) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: My question was more about whether the caller would be able to interchangeably use the result of the function call without knowing if it is an image ID or image repo digest.

I see this behavior is actually documented in the interface this method implements:
https://github.com/kubernetes/kubernetes/blob/aceb89debc2632c5c9956c8b7ef591426a485447/pkg/kubelet/container/runtime.go#L167-L168
... and so I guess the answer to the question is - yes?

If that's the case, please update the docstring of this func, too.

Comment (saschagrunert) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: Yep, updated the docstring in https://github.com/kubernetes/kubernetes/compare/c4a4d00ebd19e0b804cc2abc190657a393f14641..cb011623c845c88c42c7c04242e3bdfb0cd1ffa2 as suggested.

Comment (stlaz) [reply pkg/kubelet/kuberuntime/kuberuntime_image.go:85]: /hold cancel
/lgtm
Thanks!

**Review by kannon92 — COMMENTED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/approve
/lgtm
