### PR TITLE
wait for 10s before controller manager fails when api-server is not up

### LINKED ISSUE #17109: [v1.1.1] controller manager fails immediately when api-server is not up
IIUC, `controller manager` is expected to wait 10s before it fails when `api-server` is not up (Ref #16413). Yet it doesn't.

```
$ sudo vi /var/log/upstart/kube-controller-manager.log 
I1111 19:25:03.490354    2309 plugins.go:71] No cloud provider specified.
I1111 19:25:03.490428    2309 nodecontroller.go:133] Sending events to api server.
E1111 19:25:03.490625    2309 nodecontroller.go:203] Error monitoring node status: Get http://127.0.0.1:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: connection refused
E1111 19:25:03.490684    2309 controllermanager.go:290] Failed to start service controller: ServiceController should not be run without a cloudprovider.
F1111 19:25:03.490795    2309 controllermanager.go:314] Failed to get api versions from server: Get http://127.0.0.1:8080/api: dial tcp 127.0.0.1:8080: connection refused
~
```
k8s version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.1", GitCommit:"92635e23dfafb2ddc828c8ac6c03c7a7205a84d8", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.1", GitCommit:"92635e23dfafb2ddc828c8ac6c03c7a7205a84d8", GitTreeState:"clean"}
```

### PR DESCRIPTION
**Pull request by dalanlan**
This patch tries to fix #17109, yet it's a guess simply based on comment :-/ And i haven't tested it myself.

`pollImmediateInternal`, called by `PollImmediate`, fails immediately when `condition` returns an error, which i believe is the trouble maker.

/cc @ddysher @WIZARD-CXY

### CODE REVIEW

File: cmd/kube-controller-manager/app/controllermanager.go [hunk 1]
```diff
@@ -313,7 +313,7 @@ func (s *CMServer) Run(_ []string) error {
 	// If apiserver is not running we should wait for some time and fail only then. This is particularly
 	// important when we start apiserver and controller manager at the same time.
 	var versionStrings []string
-	err = wait.PollImmediate(time.Second, 10*time.Second, func() (bool, error) {
+	err = wait.Poll(time.Second, 10*time.Second, func() (bool, error) {
 		versionStrings, err = client.ServerAPIVersions(kubeconfig)
 		return err == nil, err
```
Comment (lavalamp) [inline cmd/kube-controller-manager/app/controllermanager.go]: I think the real problem is the err getting returned here, which I think will stop the entire Poll operation. Should be `err == nil, nil`?

Comment (ashcrow) [inline cmd/kube-controller-manager/app/controllermanager.go]: @lavalamp Why mask the error if there is an error? Shouldn't it end up returning ```True```,```nil``` or ```False```, ```ErrorInstance```?

Comment (lavalamp) [inline cmd/kube-controller-manager/app/controllermanager.go]: If the server is down, I expect you'll get an error from ServerAPIVersions. The point of this is to wait until the server comes up. Returning an error causes Poll/PollImmediate to bail out instead of continuing to poll. Therefore, you need to hide the error here (feel free to log it).

Comment (dalanlan) [inline cmd/kube-controller-manager/app/controllermanager.go]: Thank you and i'll take a closer look at it.

Comment (ddysher) [inline cmd/kube-controller-manager/app/controllermanager.go]: Thanks for fixing this.  I was told to use PollImmediate without actually looking at it.  The difference between Poll and PollImmediate is that PollImmediate will do a pre-wait check, so they essentially have the same effect here.  The check "err == nil" alreay tells Poll to continue checking, so I think it's safe to return err == nil, err.

**Comment by dalanlan** [comment]
Thank you for the clarify. I was wondering if it's more straightforward now. PTAL
/cc @lavalamp @ashcrow @ddysher

File: cmd/kube-controller-manager/app/controllermanager.go (hunk 1 above)
Comment (lavalamp) [inline cmd/kube-controller-manager/app/controllermanager.go]: @ddysher hopefully what you wrote has a typo, if not please take a look at https://github.com/kubernetes/kubernetes/blob/95b265390e530eb137beac4288ba28d63c1142da/pkg/util/wait/wait.go#L95

**Comment by lavalamp** [comment]
LGTM, looks correct now. Thanks.

File: cmd/kube-controller-manager/app/controllermanager.go (hunk 1 above)
Comment (ddysher) [inline cmd/kube-controller-manager/app/controllermanager.go]: Wow, yeah, typo...  I meant "return err == nil, nil"

Comment (dalanlan) [inline cmd/kube-controller-manager/app/controllermanager.go]: Hah, that's quite confused and i took quite a while to convince myself
