### PR TITLE
filter informer actions when inspecting controller unit test reactions

### LINKED ISSUE #34547: TestDeploymentController_dontSyncDeploymentsWithEmptyPodSelector {deployment}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/17979/

Failed: TestDeploymentController_dontSyncDeploymentsWithEmptyPodSelector {deployment}

```
deployment_controller_test.go:279: unexpected action: core.ListActionImpl{ActionImpl:core.ActionImpl{Namespace:"", Verb:"list", Resource:unversioned.GroupVersionResource{Group:"extensions", Version:"", Resource:"replicasets"}, Subresource:""}, ListRestrictions:core.ListRestrictions{Labels:labels.internalSelector{}, Fields:fields.andTerm{}}}
deployment_controller_test.go:279: unexpected action: core.WatchActionImpl{ActionImpl:core.ActionImpl{Namespace:"", Verb:"watch", Resource:unversioned.GroupVersionResource{Group:"extensions", Version:"", Resource:"replicasets"}, Subresource:""}, WatchRestrictions:core.WatchRestrictions{Labels:labels.internalSelector{}, Fields:fields.andTerm{}, ResourceVersion:""}}
deployment_controller_test.go:281: expected deployment controller to not take action
```

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/34547

There's a race where the informer tries to start list/watching and that can happen faster than the reaction test.  This simply filters it.

@kargakis @ncdc @eparis flake fix ptal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34552)

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot test this: issue #IGNORE

**Comment by deads2k** [comment]
This is very unlikely to collide, its small, its contained to tests, and its messing with our queue.  I've tagged as retest-not-required.

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this: issue #IGNORE

File: pkg/controller/deployment/deployment_controller_test.go [hunk 1]
```diff
@@ -193,20 +193,9 @@ func (f *fixture) run(deploymentName string) {
...
-				action.Matches("list", "replicasets") ||
-				action.Matches("list", "deployments") ||
-				action.Matches("watch", "pods") ||
-				action.Matches("watch", "replicasets") ||
-				action.Matches("watch", "deployments")) {
-			informerActions++
-			continue
-		}
-
 		if len(f.actions)+informerActions < i+1 {
```
Comment (lukaszo) [inline pkg/controller/deployment/deployment_controller_test.go]: informerActions will be always 0 now. I think you can remove `informerActions` now. It will make it more readable.

**Review by lukaszo — CHANGES_REQUESTED** [review]

**Comment by deads2k** [comment]
@k8s-bot gce e2e test this: issue #IGNORE

**Comment by dims** [comment]
@k8s-bot cvm gce e2e test this

**Comment by dims** [comment]
@k8s-bot kubemark e2e test this

**Comment by dims** [comment]
@k8s-bot kubemark e2e test this

**Comment by dims** [comment]
@k8s-bot gci gke e2e test this

**Comment by dims** [comment]
@k8s-bot kubemark e2e test this

**Comment by mml** [comment]
@deads2k @dims please reference flake issues when you request a re-test, otherwise the prevalence of flakes only gets worse.

This is currently blocking the queue.  Assuming it passes, I'll merge manually.

**Comment by dims** [comment]
@mml good point, will do next time. fwiw the 2 builds i was trying to trigger had a build start failures with no details.(and no flake open for them that i could find quickly)

**Comment by deads2k** [comment]
> @mml good point, will do next time. fwiw the 2 builds i was trying to trigger had a build start failures with no details.(and no flake open for them that i could find quickly)

@mml likewise.  It only said "started".
