### PR TITLE
use 'nf_conntrack' instead of 'nf_conntrack_ipv4' for linux kernel >= 4.19

### LINKED ISSUE #70304: kube-proxy cannot use ipvs mode on Linux 4.19
kube-proxy cannot use ipvs mode on Linux 4.19 due to a check for the `nf_conntrack_ipv4` module, which was changed to `nf_conntrack` (https://github.com/torvalds/linux/commit/a0ae2562c6c4b2721d9fddba63b7286c13517d9f).

`RequiredIPVSKernelModulesAvailableCheck.Check()` uses `ipvsModules` to check for `nf_conntrack_ipv4`:

https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/util/ipvs/kernelcheck_linux.go#L78-L91

https://github.com/kubernetes/kubernetes/blob/6a8a8597f5bf4de29b7b88384529188df0b71337/pkg/util/ipvs/ipvs.go#L70-L77

It should instead accept `nf_conntrack` on Linux 4.19 or above.

**What happened**:
kube-proxy fell back from ipvs mode to iptables mode.
```
I1026 20:50:47.185405       1 feature_gate.go:226] feature gates: &{{} map[]}
W1026 20:50:47.323161       1 proxier.go:397] Failed to load kernel module nf_conntrack_ipv4 with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
E1026 20:50:47.326512       1 server_others.go:304] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [nf_conntrack_ipv4]
I1026 20:50:47.328336       1 server_others.go:140] Using iptables Proxier.
```

**What you expected to happen**:
kube-proxy using ipvs.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a cluster on an image using Linux 4.19 or above with kube-proxy using ipvs mode (see https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#run-kube-proxy-in-ipvs-mode).

**Environment**:
- Kubernetes version (use `kubectl version`): All
- Kernel (e.g. `uname -a`): 4.19

/kind bug

### PR DESCRIPTION
**Pull request by islinwb**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
see https://github.com/kubernetes/kubernetes/pull/70325#issuecomment-434074688

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/70304, reverting changes made in https://github.com/kubernetes/kubernetes/pull/70325.

**Special notes for your reviewer**:
/assign @m1093782566 
/cc @bgilbert

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/proxy/ipvs/proxier.go [hunk 1]
```diff
@@ -445,6 +444,9 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
 		glog.Errorf("Failed to read file %s with error %v", kernelVersionFile, err)
 	}
 	kernelVersion := strings.TrimSpace(string(b))
+	if checkMinVersion(kernelVersion, "4.19") {
```
[the remark this answers is not in the document]
Comment (bgilbert) [reply pkg/proxy/ipvs/proxier.go]: It's 4.19.  See https://github.com/torvalds/linux/commit/a0ae2562c6c4b2721d9fddba63b7286c13517d9f.

[the remark this answers is not in the document]
Comment (m1093782566) [reply pkg/proxy/ipvs/proxier.go]: Okay.

@islinwb Please add the link.

@bgilbert Could you help review the changes and to see if it works for you?

[the remark this answers is not in the document]
Comment (bgilbert) [reply pkg/proxy/ipvs/proxier.go]: I'm not in a position to test the changes and wasn't the original reporter; see https://github.com/coreos/bugs/issues/2518.

File: pkg/proxy/ipvs/proxier.go [hunk 2]
```diff
@@ -445,6 +444,9 @@ func (handle *LinuxKernelHandler) GetModules() ([]string, error) {
...
+		ipvsModules[4] = "nf_conntrack"
```
Comment (bgilbert) [inline pkg/proxy/ipvs/proxier.go]: The hardcoded index seems brittle, in case the `ipvsModules` initializer ever changes.

Modifying `ipvsModules` in place doesn't seem ideal either, but I don't know k8s coding standards.

**Review by bgilbert — COMMENTED** [review]
From a casual inspection, it appears that this should address the issue.

**Comment by islinwb** [comment]
@m1093782566 @bgilbert PTAL

also add changes to kubeadm side

File: pkg/util/ipvs/ipvs.go [hunk 3]
```diff
@@ -67,14 +67,15 @@ const (
...
-var ipvsModules = []string{
-	"ip_vs",
-	"ip_vs_rr",
-	"ip_vs_wrr",
-	"ip_vs_sh",
-	"nf_conntrack_ipv4",
-}
+// IPVS required kernel modules.
+const (
+	MOD_IP_VS             string = "ip_vs"
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: comment please.

File: pkg/proxy/util/utils.go [hunk 4]
```diff
@@ -145,3 +146,19 @@ func LogAndEmitIncorrectIPVersionEvent(recorder record.EventRecorder, fieldName,
 			}, v1.EventTypeWarning, "KubeProxyIncorrectIPVersion", errMsg)
 	}
 }
+
+// CompareVersions returns true if ver1 >= ver2
+func CompareVersions(ver1, ver2 string) (bool, error) {
```
Comment (m1093782566) [inline pkg/proxy/util/utils.go]: return 1 if v1>v2
return 0 if v1==v2
return -1 if v1<v2
MAKE SENSE?

File: pkg/util/ipvs/ipvs.go [hunk 5]
```diff
@@ -110,3 +122,29 @@ func (rs *RealServer) Equal(other *RealServer) bool {
...
+	// get kernel version
+	kernelVersionFile := "/proc/sys/kernel/osrelease"
+	out, err := Executor.Command("cut", "-f1", "-d", " ", kernelVersionFile).CombinedOutput()
+	if err != nil {
+		return "", nil, fmt.Errorf("error getting os release kernel version: %v(%s)", err, out)
+	}
+	kernelVersion = strings.TrimSpace(string(out))
+
+	// get ipvs modules
+	ver1, err := version.ParseGeneric(kernelVersion)
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: nit: You are parsing kernel version here so I assume you can move this line upper.

File: pkg/util/ipvs/ipvs.go [hunk 6]
```diff
@@ -110,3 +122,29 @@ func (rs *RealServer) Equal(other *RealServer) bool {
...
+func GetKernelVersionAndIPVSMods(Executor exec.Interface) (kernelVersion string, ipvsModules []string, err error) {
+	// get kernel version
+	kernelVersionFile := "/proc/sys/kernel/osrelease"
+	out, err := Executor.Command("cut", "-f1", "-d", " ", kernelVersionFile).CombinedOutput()
+	if err != nil {
+		return "", nil, fmt.Errorf("error getting os release kernel version: %v(%s)", err, out)
+	}
+	kernelVersion = strings.TrimSpace(string(out))
+
+	// get ipvs modules
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: You are parsing kernel version, right?

File: pkg/util/ipvs/ipvs.go [hunk 7]
```diff
@@ -110,3 +122,29 @@ func (rs *RealServer) Equal(other *RealServer) bool {
 	return rs.Address.Equal(other.Address) &&
 		rs.Port == other.Port
 }
+
+func GetKernelVersionAndIPVSMods(Executor exec.Interface) (kernelVersion string, ipvsModules []string, err error) {
+	// get kernel version
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: // Parse kernel version

??

File: pkg/util/ipvs/ipvs.go (hunk 5 above)
Comment (islinwb) [reply pkg/util/ipvs/ipvs.go]: this line is for comparing versions (the kernel version the function returns is got in Line 133)

Comment (m1093782566) [reply pkg/util/ipvs/ipvs.go]: I mean the comment is not consistent with the code. Comment says get ipvs modules but you are parse kernel verison.

File: pkg/util/ipvs/ipvs.go [hunk 8]
```diff
@@ -110,3 +122,28 @@ func (rs *RealServer) Equal(other *RealServer) bool {
...
+
+// GetKernelVersionAndIPVSMods returns the linux kernel version and the required ipvs modules
+func GetKernelVersionAndIPVSMods(Executor exec.Interface) (kernelVersion string, ipvsModules []string, err error) {
+	kernelVersionFile := "/proc/sys/kernel/osrelease"
+	out, err := Executor.Command("cut", "-f1", "-d", " ", kernelVersionFile).CombinedOutput()
+	if err != nil {
+		return "", nil, fmt.Errorf("error getting os release kernel version: %v(%s)", err, out)
+	}
+	kernelVersion = strings.TrimSpace(string(out))
+
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: nit: Remove this empty line?

File: pkg/util/ipvs/ipvs.go [hunk 9]
```diff
@@ -110,3 +122,28 @@ func (rs *RealServer) Equal(other *RealServer) bool {
 	return rs.Address.Equal(other.Address) &&
 		rs.Port == other.Port
 }
+
+// GetKernelVersionAndIPVSMods returns the linux kernel version and the required ipvs modules
+func GetKernelVersionAndIPVSMods(Executor exec.Interface) (kernelVersion string, ipvsModules []string, err error) {
+	kernelVersionFile := "/proc/sys/kernel/osrelease"
```
Comment (m1093782566) [inline pkg/util/ipvs/ipvs.go]: Add one line comment, e.g.
// parse kernel version

**Comment by m1093782566** [comment]
/test pull-kubernetes-e2e-kops-aws

It looks much better now.

/approve

I will append a LGTM when you fix the understanding comments.

**Comment by m1093782566** [comment]
/lgtm

Please fix the verfify

**Comment by idevz** [comment]
when will this feature merge into stable version?

**Comment by m1093782566** [comment]
@idevz 

This fix should be in v1.13. I am not sure if we will cherry-pick this PR to release <1.13.
