### PR TITLE
Use fake clock in TestGetPodsToSync.

### LINKED ISSUE #24788: flake: TestGetPodsToSync failed
I just run `./hack/test-go.sh` against the master branch code, and see errors below:

```console
$ ./hack/test-go.sh
...
--- FAIL: TestGetPodsToSync (0.00s)
	kubelet_test.go:4467: expected 3 pods to sync, got 2
...
```

The test case is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_test.go#L4418-L4469 

/cc @Random-Liu

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes #24788.

The original test uses the real clock which could be the reason of the flake.

/cc @yujuhong

### CODE REVIEW

File: pkg/kubelet/util/queue/work_queue.go [hunk 1]
```diff
@@ -46,6 +46,11 @@ func NewBasicWorkQueue() WorkQueue {
 	return &basicWorkQueue{queue: queue, clock: util.RealClock{}}
 }
 
+func NewTestWorkQueue(clock util.Clock) WorkQueue {
```
Comment (yujuhong) [inline pkg/kubelet/util/queue/work_queue.go]: Suggestion: add the `clock` arg to `NewBasicWorkQueue()` instead. We should not have test methods in this file.

Comment (Random-Liu) [inline pkg/kubelet/util/queue/work_queue.go]: ACK.

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments.
