### PR TITLE
Sleep before deleting the cluster to give the controller manager time to

### LINKED ISSUE #7753: Target pool leak in GCE project running our jenkins e2e tests
All of our external load balancer tests failed for the better part of a day due to the GCE project that our tests run in hitting its quota for number of target pools. While the target pools have been deleted, the fact that we hit our quota indicates that there must be a leak somewhere, and we need to plug it.

### PR DESCRIPTION
**Pull request by a-robinson**
delete any cloudprovider resources still around from the last test.

Should (hopefully) fix #7753.

@quinton-hoole @zmerlynn

### CODE REVIEW

**Comment by saad-ali** [comment]
Marking this for v1.0 milestone since it fixes test instability. Assigning @quinton-hoole

File: hack/jenkins/e2e.sh [hunk 1]
```diff
@@ -222,5 +222,8 @@ fi
 
 ### Clean up ###
 if [[ "${E2E_DOWN,,}" == "true" ]]; then
+    # Sleep before deleting the cluster to give the controller manager time to
+    # delete any cloudprovider resources still around from the last test.
+    sleep 60
```
Comment (quinton-hoole) [inline hack/jenkins/e2e.sh]: Please add a note as to how the number 60 was arrived at (presumably based on the ELB retry loop frequency), and that it should not be changed independently of that basis.

**Comment by quinton-hoole** [comment]
One nit.  Other than that, LGTM.

File: hack/jenkins/e2e.sh (hunk 1 above)
Comment (a-robinson) [inline hack/jenkins/e2e.sh]: The deletions are managed using a watch and failed attempts to reconcile are retried every 5 seconds, so 60 is sort of an arbitrary bound. I've added a comment in the next push.
