### PR TITLE
Make volume binder resilient to races

### LINKED ISSUE #71928: When a PVC is provisioned with delayed binding, it never recovers from a failed provision
**What happened**: If a PVC with delayed binding fails to provision (for example due to a StorageClass parameter error), even when the error is fixed later on, provisioning never succeeds.

**What you expected to happen**: After the error is fixed, provisioning should retry and succeed.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a StorageClass with VolumeBindingMode = WaitForFirstConsumer, and set some garbage parameters to eventually cause provisioning to fail.
- Create a PVC using the StorageClass
- Create a pod that consumes the PVC. Provisioning should fail
- Recreate the StorageClass with parameters removed.
Under correct operation, the provisioner should successfully retry and create a PV, and the pod should proceed to start. But this is not the case.

**Anything else we need to know?**:
When the PVC first fails to provision, the consumer pod has the following events:
```
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  37s                default-scheduler  selectedNode annotation value "" not set to scheduled node "[node]"
  Warning  FailedScheduling  37s                default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 2 times)
  Warning  FailedScheduling  37s                default-scheduler  AssumePod failed: pod 8e98377a-fcd7-11e8-beb7-42010a800002 is in the cache, so can't be assumed
  Warning  FailedScheduling  0s (x18 over 37s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
```

after the error is fixed, the last event (unbound immediate PVCs) keeps firing.

For some reason the scheduler doesn't think the PVC uses delayed binding:
https://github.com/kubernetes/kubernetes/blob/67bc6d2083d94b38e5c8b249fe91aeafa1a0af19/pkg/controller/volume/persistentvolume/scheduler_binder.go#L504

One possible cause is somehow the scheduler thinks the selectedNode annotation still exists in the PVCCache (the provisioner removed the annotation after provisioning failure):
https://github.com/kubernetes/kubernetes/blob/67bc6d2083d94b38e5c8b249fe91aeafa1a0af19/pkg/controller/volume/persistentvolume/pv_controller.go#L297
Or the scheduler failed to get the StorageClass. I'm not sure atm why either could happen.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.3, 1.13
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig storage
/cc @msau42 

/kind bug

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Make volume binder resilient to races between main schedule loop and async binding operation.

**Which issue(s) this PR fixes**:

Fixes #71928 #72013 #56236

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Make volume binder resilient to races between main schedule loop and async binding operation 
```

/sig storage
/sig scheduling

### CODE REVIEW

**Review by xiaoxubeii — APPROVED** [review]

**Comment by msau42** [comment]
Hm another idea I had is to treat static binding and pending provisioning similarly in the predicate.  Instead of failing the predicate if selectedNode is set, can we instead make the predicate return true only for the selectedNode, and false for all other nodes?  AssumePodVolumes checks for if the PVCs are fully bound (which they are not) to determine whether or not to call BindPodVolumes.

This would be a bigger change, but I think would make our logic more resilient to these races.

**Comment by cofyc** [comment]
That makes sense and seems better! Always try to bind pod volumes if they are not fully bound.

**Comment by cofyc** [comment]
> Instead of failing the predicate if selectedNode is set, can we instead make the predicate return true only for the selectedNode, and false for all other nodes? AssumePodVolumes checks for if the PVCs are fully bound (which they are not) to determine whether or not to call BindPodVolumes.

The important thing in this design is how to make API calls and check on new bindings made by new schedule loop. IMO there are two methods:

- Method 1: when new bindings are found, make API calls for new bindings and check on new bindings
- Method 2: fail with error when new bindings are found, let scheduler fire new binding operation next run
  - Because pod is not marked unscheduable, pod will be added into active queue on failure

With method 1, schedule loop which made new bindings will continue to retry until binding operation finished. With method 2, two instances of pod will merge into one in active queue, this reduces unnecessary scheduling retries.

I've update PR to use method 2. Please take a look at again.

**Comment by cofyc** [comment]
## Scenarios

#### PVC selectedNode is rejected by provisioner

xref: https://github.com/kubernetes/kubernetes/issues/71928

BindPodVolumes will be retired by following cases:

- No pod is in scheduling. New PVC object from apiserver is added into pvc cache. `BindPodVolumes` find `selectedNode` does not exist, fail with error on which scheduler will retry.
- A pod is in scheduling. It will assume on new PVC object and update binding cache. `BindPodVolumes` will find binding cache is out of date, fail with an error on which scheduler will retry

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 1]
```diff
@@ -141,6 +141,27 @@ func (b *volumeBinder) GetBindingsCache() PodBindingCache {
...
+		// We recreate bindings for each new schedule loop.
+		// Although we do not distinguish nil from empty in this function, for
+		// easier testing, we normalize empty to nil.
+		if len(matchedClaims) == 0 {
+			matchedClaims = nil
+		}
+		if len(provisionedClaims) == 0 {
+			provisionedClaims = nil
+		}
+		// TODO merge into one atomic function
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: In current implementation, IMO there is no need to separate `bindings` and `provisionedPVCs` in pod binding cache. It's better to get/update/delete `bindings` and `provisionedPVCs` together.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 2]
```diff
@@ -382,8 +423,13 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
 		return false, fmt.Errorf("failed to get cached claims to provision for pod %q", podName)
 	}
 
+	// Check for any conditions that might require scheduling retry
+
 	for _, binding := range bindings {
-		// Check for any conditions that might require scheduling retry
+		// Check if pv is out of date
+		if err := b.pvCache.IsOutOfDate(binding.pv); err != nil {
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: This causes lots of unnecessary scheduling retires which increase volume binding latency. TestVolumeBindingDynamicStressFast/TestVolumeBindingDynamicStressSlow have high chance to fail. I'm working on a more fine-grain version.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Done

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 3]
```diff
@@ -397,18 +464,26 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
...
 
 		// Check if pvc is fully bound
-		if isBound, _, err := b.isPVCBound(binding.pvc.Namespace, binding.pvc.Name); !isBound || err != nil {
-			return false, err
+		if !b.isPVCFullyBound(pvc) {
+			return false, nil
 		}
-
-		// TODO; what if pvc is bound to the wrong pv? It means our assume cache should be reverted.
-		// Or will pv controller cleanup the pv.ClaimRef?
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: https://github.com/kubernetes/kubernetes/blob/197fc67693c2391dcbc652fc185ba85b5ef82a8e/pkg/controller/volume/persistentvolume/pv_controller.go#L652-L699

If PVC is bound to wrong PV, PV will be unbound. Assumed cache will be reverted.
I've added a test for dynamic provisioned PV by the way.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 4]
```diff
@@ -1275,60 +1404,70 @@ func TestCheckBindings(t *testing.T) {
...
-		"binding-succeeds-after-time": {
-			binding:   binding1aBound,
-			cachedPV:  pvNode1a,
-			cachedPVC: unboundPVC,
+			initPV:     pvNode1aBound,
+			initPVC:    unboundPVC,
+			binding:    makeBinding(unboundPVC, pvNode1aBound),
+			apiPV:      pvNode1aBound,
+			apiPVC:     boundPVCNode1a,
+			shouldFail: true,
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: If PV is already bound, BindPodVolumes actually will fail in bindAPIUpdate because object version conflict.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: Sorry, I misunderstood 'already-bound' test.  There are more cases:

Case 1: Before FindPodVolumes, PV is bound to PVC, PVC is not fully bound to PV

IIUC, this is original test case. BindPodVolumes will succeed after PVC is fully bound to PV by PV controller. I implement this behavior by using asyncFunc.

Case 2: Before FindPodVolumes, PV is not bound to PVC, PVC is not fully bound to PV

If PV is bound to PVC by PV controller before BindPodVolumes, BindPodVolumes will fail because API conflict.

I've added a test `bound-by-pv-controller-before-bind` for this.

Case 3: Before FindPodVolumes, PV is bound to PVC, PVC is fully bound to PV

BindPodVolumes will not be called. So we do not need test this.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 3 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: There is a PR here that will detect if PV has invalid node affinity and will fail binding: https://github.com/kubernetes/kubernetes/pull/70026

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 5]
```diff
@@ -382,13 +436,33 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
 		return false, fmt.Errorf("failed to get cached claims to provision for pod %q", podName)
 	}
 
+	// Check for any conditions that might require scheduling retry
+
 	for _, binding := range bindings {
-		// Check for any conditions that might require scheduling retry
+		// Check against latest API object
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Can you explain why we need to check the API object directly and not wait for the informer update to the pv cache?

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Because PV cache may be overridden. Binding operation is async, scheduling in main loop may Find/Assume new cache on new API objects, then binding operation will don't know latest API objects. This is root cause of volume binder races (e.g. https://github.com/kubernetes/kubernetes/issues/71928). 

e.g. 

- Volume binder find/assume PV/PVC cache (cache: prebound, api: not bound)
- Volume binder make API call to bind PV/PVC and check PV & PVC is bound or not (cache: prebound, api: prebound)
- PV/PVC is rejected (cache: not bound, api: not bound)
- Before binding operation check PV/PVC cache, Volume binder find/assume PV/PVC cache again (cache: prebound, api: not bound)
- Binding operation finds PV/PVC cache are still the same, but actually binding operation should be restarted to bind PV/PVC again

In current scheduler, we can simply do not share PV/PVC cache in two goroutines to avoid races. IMO, PV/PVC cache are used for scheduling, not for binding operation check which should depends on latest state in API server. Because PV/PVC are bound or not and pod should be rescheduled or not depend on state in API server which are updated by PV controller or provisioner. 

Though PV/PVC cache can be used if they will not be modified by another one if we prevent scheduler from scheduling pod when pod is in binding , but it is still unnecessary.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 6]
```diff
@@ -382,13 +436,33 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
...
+		obj, err := b.pvCache.GetAPIObj(binding.pv.Name)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Maybe add a new method `GetApiPV` [here](https://github.com/kubernetes/kubernetes/blob/cdeb9205230ac6e5ea772ab8c562738d7c42bc3e/pkg/controller/volume/persistentvolume/scheduler_assume_cache.go#L341) to make the logic here easier to read.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 5 above)
Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Ok that makes sense. Can you update the comment here with a little more detail, saying that because the PV/PVC can be assumed again, we need to fail the binding operation so it can be retried.

And actually, assume pod will fail because binding is in progress.  After this binding operation fails, then what causes the pod to retry scheduling again?

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 7]
```diff
@@ -300,10 +345,8 @@ func (b *volumeBinder) BindPodVolumes(assumedPod *v1.Pod) (err error) {
 	}
 
 	return wait.Poll(time.Second, b.bindTimeout, func() (bool, error) {
-		// Get cached values every time in case the pod gets deleted
-		bindings = b.podBindingCache.GetBindings(assumedPod, assumedPod.Spec.NodeName)
-		claimsToProvision = b.podBindingCache.GetProvisionedPVCs(assumedPod, assumedPod.Spec.NodeName)
-		return b.checkBindings(assumedPod, bindings, claimsToProvision)
+		b, err := b.checkBindings(assumedPod, bindings, claimsToProvision)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Is the pod deletion case still handled?

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 5 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Yes, if pod is not marked unschedulable (status=PodReasonUnschedulable) wrongly (fixed in this PR), [other status updates will re-add pod into active queue](https://github.com/kubernetes/kubernetes/blob/5b6e20d0e057c0060a185673adc75af44d1a4566/pkg/scheduler/internal/queue/scheduling_queue.go#L367). This will retry scheduling again.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: assume pod [fails with non-PodReasonUnschedulable error](https://github.com/kubernetes/kubernetes/blob/5b6e20d0e057c0060a185673adc75af44d1a4566/pkg/scheduler/scheduler.go#L410-L416) which will not put pod into unscheduable pod.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Comments are updated in 80d8815f64fb1452d8c62c2513707b90401d2b10.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 6 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Done in 80d8815f64fb1452d8c62c2513707b90401d2b10.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 7 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Oh, I missed this, binding operation should be cancelled when pod is deleted or assigned a node by users or other scheduler.

Done in 7140fda91d1a239862b3347977fafe27efab1994.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 8]
```diff
@@ -442,6 +442,15 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
 
 	// Check for any conditions that might require scheduling retry
 
+	// When pod is removed from scheduling queue because of deletion or any
+	// other reasons, binding operation should be cancelled. There is no need
+	// to check PV/PVC bindings any more.
+	// We check pod binding cache here which will be cleared when pod is
+	// removed from scheduling queue.
+	if b.podBindingCache.GetDecisions(pod) == nil {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Can you add a unit test for this, if one doesn't already exist?

**Review by msau42 — COMMENTED** [review]
lgtm, just one minor comment and this can be squashed a little

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 8 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: sure, it has some conflicts with #70026, I will rebase and squash after #70026 is merged.

**Comment by cofyc** [comment]
@msau42 PR is rebased and squashed into logical commits:

- 13d87fbff8ce4030bce5209caedbb2e2d55e13bf: Make volume binder resilient to races 
- 4f8772e74bc1f1d20e4ca4de467d882234c141b1: Unit tests only
- d0e748a47f2e5da843ce8d8e19c35f0b9be9689f: Scheduler change
- f7aca60aaf77b6691d1e219b985479b46e7454f5: If provisioning PVC's PV is not found, check next time

I made an additional modification to original PR, tolerate provisioning PVC's PV not found error, see https://github.com/kubernetes/kubernetes/pull/72045/commits/f7aca60aaf77b6691d1e219b985479b46e7454f5. This avoids unnecessary "failed to get pv" errors and scheduler retires.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 8 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: There is [an existing test `pod-deleted-after-time`](https://github.com/kubernetes/kubernetes/pull/72045/files#diff-7e773cadec5750de298ed8fa194edda3L1357). In old PR, BindPodVolume failed with timeout error, so it passed too. Perhaps it's better to check error too. I can address this in a separate PR.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 9]
```diff
@@ -518,7 +518,15 @@ func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claim
 		if pvc.Spec.VolumeName != "" {
 			pv, err := b.pvCache.GetAPIPV(pvc.Spec.VolumeName)
 			if err != nil {
-				return false, fmt.Errorf("failed to get pv %q from cache: %v", pvc.Spec.VolumeName, err)
+				if _, ok := err.(*errNotFound); ok {
+					// We tolerate NotFound error here, because PV is possibly
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: unit test for this condition?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 10]
```diff
@@ -1302,63 +1431,110 @@ func TestCheckBindings(t *testing.T) {
...
+		},
+		"bound-by-pv-controller-before-bind": {
+			initPVs:    []*v1.PersistentVolume{pvNode1a},
+			initPVCs:   []*v1.PersistentVolumeClaim{unboundPVC},
+			binding:    makeBinding(unboundPVC, pvNode1aBound),
+			apiPV:      pvNode1aBound,
+			apiPVC:     boundPVCNode1a,
+			shouldFail: true, // bindAPIUpdate will fail because API conflict
+		},
+		"binding-static-pv-succeeds-after-time": {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: What's the difference between this and "binding-succeeds-after-time"? That the PV object is not bound?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 11]
```diff
@@ -1302,63 +1431,110 @@ func TestCheckBindings(t *testing.T) {
...
+					t.Errorf("failed to get PVC %q: %v", pvc.Name, err)
+					return
+				}
+				dynamicPV := makeTestPV("dynamic-pv", "node1", "1G", "1", newPVC, waitClass)
+				dynamicPV, err = testEnv.client.CoreV1().PersistentVolumes().Create(dynamicPV)
+				if err != nil {
+					t.Errorf("failed to create PV %q: %v", dynamicPV.Name, err)
+					return
+				}
+				newPVC.Spec.VolumeName = dynamicPV.Name
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: does this need to be a copy of the pvc object?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 12]
```diff
@@ -1376,23 +1552,23 @@ func TestBindPodVolumes(t *testing.T) {
...
-			cachedPVs:  []*v1.PersistentVolume{pvNode1a},
-			cachedPVCs: []*v1.PersistentVolumeClaim{unboundPVC},
-			delayFunc: func(t *testing.T, testEnv *testEnv, pod *v1.Pod, binding *bindingInfo, pvcs []*v1.PersistentVolumeClaim) {
+			binding:  makeBinding(unboundPVC, pvNode1aBound),
+			initPVs:  []*v1.PersistentVolume{pvNode1a},
+			initPVCs: []*v1.PersistentVolumeClaim{unboundPVC},
+			delayFunc: func(t *testing.T, testEnv *testEnv, pod *v1.Pod, pvs []*v1.PersistentVolume, pvcs []*v1.PersistentVolumeClaim) {
+				pvc := pvcs[0]
 				// Delete PVC
 				// Update pvc cache, fake client doesn't invoke informers
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: can you update the rest of these tests to not directly update the internal cache since it's not needed anymore?

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 13]
```diff
@@ -1445,38 +1621,54 @@ func TestBindPodVolumes(t *testing.T) {
...
-			testEnv.initVolumes(scenario.cachedPVs, scenario.apiPVs)
-			testEnv.initClaims(scenario.cachedPVCs, nil)
-			testEnv.assumeVolumes(t, name, "node1", pod, bindings, scenario.provisionedPVCs)
+			testEnv.initVolumes(scenario.initPVs, scenario.initPVs)
+			testEnv.initClaims(scenario.initPVCs, scenario.initPVCs)
+			testEnv.assumeVolumes(t, name, "node1", pod, bindings, claimsToProvision)
+		}
+
+		// Before Execute
+		if scenario.apiPV != nil {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: What is the purpose of having a separate call to update the api objects instead of passing them through initVolumes/initClaims?

File: pkg/scheduler/factory/factory.go [hunk 14]
```diff
@@ -1124,21 +1123,11 @@ func (c *configFactory) MakeDefaultErrorFunc(backoff *util.PodBackoff, podQueue
...
-						}
 					}
 					break
 				}
 				if errors.IsNotFound(err) {
 					klog.Warningf("A pod %v no longer exists", podID)
-
-					if c.volumeBinder != nil {
-						// Volume binder only wants to keep unassigned pods
-						c.volumeBinder.DeletePodBindings(origPod)
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: In `deletePodFromSchedulingQueue`:

https://github.com/kubernetes/kubernetes/blob/55d8f709c8b214f72c000076093e08344dc3ebce/pkg/scheduler/factory/factory.go#L580-L603

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 11 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: No, `newPVC` is returned by `client.CoreV1().PersistentVolumeClaims(pvc.Namespace).Get` which retrieves objects from apiserver. I've updated volumeReactor to return a copy of stored object.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: For dynamic provisioning, PVC was updated in bindAPIUpdate, this is why I need to fetch PVC from apiserver again.

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go (hunk 10 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: they are same... my mistake, i'm going to remove one of them.

File: pkg/controller/volume/persistentvolume/framework_test.go [hunk 15]
```diff
@@ -326,7 +326,7 @@ func (r *volumeReactor) React(action core.Action) (handled bool, ret runtime.Obj
 	case action.Matches("delete", "persistentvolumeclaims"):
 		name := action.(core.DeleteAction).GetName()
 		klog.V(4).Infof("deleted claim %s", name)
-		obj, found := r.volumes[name]
+		obj, found := r.claims[name]
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/framework_test.go]: This is weird bug... perhaps old tests didn't reach here

**Comment by msau42** [comment]
lgtm! thanks for digging into these tricky race conditions

**Comment by cofyc** [comment]
@msau42 Squashed into logical commits (no content change):

- 13d87fbff8ce4030bce5209caedbb2e2d55e13bf: Make volume binder resilient to races 
- 8b94b9625bb7bbf0a1d9f8c03f715a4aa76ded1a: Unit tests only
- cfc8ef51d1f57f6dab061fa26fbc14db5dde14e4: Scheduler change
- 1a62f53d3fc915a1c99156c8de049fedd2219a41: If provisioning PVC's PV is not found, check next time

**Comment by cofyc** [comment]
cc @k82cn @bsalamat 
For approval on scheduler change

File: pkg/scheduler/factory/factory.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: Have revisited `DeletePodBindings` part again. I found `deletePodFromSchedulingQueue` is called only [when a unscheduled pod is deleted](https://github.com/kubernetes/kubernetes/blob/55d8f709c8b214f72c000076093e08344dc3ebce/pkg/scheduler/factory/factory.go#L314-L338).

After this PR, we do not need to clear pod binding cache on error because we recreate at beginning of scheduler loop, but we had never cleared cache on success.

IMO, pod binding cache at least should be cleared when pod is not needed to be scheduled (e.g. assigned a node on success or deleted from cluster).

Don't want to make this PR too complex, I created a issue to track this: https://github.com/kubernetes/kubernetes/issues/72763

**Comment by cofyc** [comment]
/hold
for checking pod binding cache issues

File: pkg/scheduler/factory/factory.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: Sorry, I misunderstood [this part code](https://github.com/kubernetes/kubernetes/blob/55d8f709c8b214f72c000076093e08344dc3ebce/pkg/scheduler/factory/factory.go#L314-L338), `deletePodFromSchedulingQueue` will be called on success, because with FilteringResourceEventHandler, object stops passing the filter (assigned a pod or not here) after an update is considered a delete. So all successful pods will go through `deletePodFromSchedulingQueue`.

Talked with @msau42 offline, we'll add integration tests for verify no memory leaks on pod binding cache.

**Comment by cofyc** [comment]
/hold cancel

xref: https://github.com/kubernetes/kubernetes/pull/72045#discussion_r246655042

**Review by bsalamat — APPROVED** [review]
/approve

I do not know the volume binder logic very well, but based on your explanation that the volume binder cache needs to be kept only for unassigned pods, the changes in the scheduler code look good to me.

**Comment by msau42** [comment]
With a quick glance, I don't think so. It seems like only containerd jobs with CSI hostpath or intree nfs drivers have spiked.  Also some of the nfs tests that are failing don't use PVs. I more suspect an issue with containerd

**Comment by liggitt** [comment]
good observation. opened https://github.com/kubernetes/kubernetes/issues/72863

**Comment by bsalamat** [comment]
We are also seeing an increase in scheduling latency right after this PR. The scheduler predicate evaluation latency has increase by about 50%.

**Comment by cofyc** [comment]
I guess it is because new FindPodVolumes in this PR needs to clear old pod binding cache, and to achieve this I update pod cache even if there is no PVCs to bind/provision. There are some optimizations we can do. Sorry about increased scheduling latency. I'm working on a fix.

**Comment by cofyc** [comment]
Thanks!
