### PR TITLE
Removed e2e test on empty NodeAffinity.

### LINKED ISSUE #63027: Failing Test: [sig-scheduling] SchedulerPredicates [Serial] validates that a pod with an invalid NodeAffinity is rejected
## Failing Job
[sig-release-master-blocking: gci-gke-serial](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-serial)

## Failing Test
SchedulerPredicates [Serial] validates that a pod with an invalid NodeAffinity is rejected

## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=scheduling&job=ci-kubernetes-e2e-gci-gke-serial&test=validates%20that%20a%20pod%20with%20an%20invalid%20NodeAffinity%20is%20rejected

Has been failing consistently since 4/17.  Here are the [Commit changes](https://github.com/kubernetes/kubernetes/compare/7966265a5...cce67ed8e)

/kind bug
/priority failing-test
/priority important-soon
/sig scheduling
/milestone 1.11
@kubernetes/sig-scheduling-bugs 

cc @jberkus @tpepper

/assign @bsalamat for triage.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63027 

**Special notes for your reviewer**:
In #62448, we removed the validation on empty `nodeAffinity` which is already handled in scheduler: select no objects.

**Release note**:
```release-note
None
```

### CODE REVIEW

File: test/e2e/scheduling/predicates.go [hunk 1]
```diff
@@ -367,29 +366,6 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
 		verifyResult(cs, 0, 1, ns)
 	})
 
-	It("validates that a pod with an invalid NodeAffinity is rejected", func() {
```
Comment (liggitt) [inline test/e2e/scheduling/predicates.go]: rejection of invalid affinity is covered by validation unit test, right? removal of this here LGTM

Comment (k82cn) [reply test/e2e/scheduling/predicates.go]: The validation unit test covered empty NodeAffinity; I added two case for invalid key and value :)

**Comment by MaciekPytel** [comment]
@k82cn Can you create a cherry-pick today? This is a release blocking test and we need it fixed for 1.10.2.

File: pkg/scheduler/algorithm/predicates/predicates_test.go [hunk 2]
```diff
@@ -1359,6 +1359,34 @@ func TestPodFitsSelector(t *testing.T) {
...
+							},
+						},
+					},
+				},
+			},
+			labels: map[string]string{
+				"foo": "bar",
+			},
+			fits: false,
+			test: "Pod with an invalid value in Affinity term won't be scheduled onto the node",
```
Comment (ravisantoshgudimetla) [inline pkg/scheduler/algorithm/predicates/predicates_test.go]: nit: NodeAffninity term would make it clear.

**Comment by ravisantoshgudimetla** [comment]
LGTM from scheduling perspective.

/lgtm

**Comment by k82cn** [comment]
@MaciekPytel, done at #63154 . 

Ping @liggitt  for api approve :)
