### PR TITLE
kube-proxy: Drop packets in INVALID state

### LINKED ISSUE #74839: "Connection reset by peer" due to invalid conntrack packets
**What happened**: Network services with heavy load will cause "connection reset" from time to time. Especially those with big payloads. When packets with sequence number out-of-window arrived k8s node, conntrack marked them as INVALID. kube-proxy will ignore them, without rewriting DNAT. The packet goes back the the original pod, who doesn't recognize the packet because of the wrong source ip, end up RSTing the connection. 

**What you expected to happen**: connection not reset

**How to reproduce it (as minimally and precisely as possible)**: 
@tcarmet wrote this just to reproduce the issue: https://github.com/tcarmet/k8s-connection-reset
Basically run it in a cluster, and after a while you will be able to see "Connection reset by peer" on both server and client pods. 

**Anything else we need to know?**:
Related issue: 
https://github.com/docker/libnetwork/issues/1090

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.7
- Cloud provider or hardware configuration: gke (should be general to all provider)
- OS (e.g: `cat /etc/os-release`): 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- Kernel (e.g. `uname -a`): Linux gke-cluster-1-11-default-pool-161c67fc-6nzv 4.14.89+ #1 SMP Wed Jan 9 13:35:00 PST 2019 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by anfernee**
Fixes: #74839

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74839

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Packets considered INVALID by conntrack are now dropped. In particular, this fixes
a problem where spurious retransmits in a long-running TCP connection to a service
IP could result in the connection being closed with the error "Connection reset by
peer"
```

### CODE REVIEW

**Comment by bowei** [comment]
/assign @thockin 

Is this testable is some way?

**Comment by anfernee** [comment]
the repro (https://github.com/tcarmet/k8s-connection-reset) is more like a load test, it would be nice to have a deterministic reproducing script. other than that, a unit test can be added too.

I think it would be nice to make it into v1.14 's march 7th window.

**Review by mainred — COMMENTED** [review]
Should we also drop invalid state packets that will be delivered locally?  like the node port service queries.

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -1298,6 +1298,17 @@ func (proxier *Proxier) syncProxyRules() {
 		}
 	}
 
+	// Drop the packets in INVALID state, which would potentially cause
+	// unexpected connection reset.
+	// https://github.com/kubernetes/kubernetes/issues/74839
+	writeLine(proxier.filterRules,
+		"-A", string(kubeForwardChain),
+		"-m", "comment", "--comment", `"kubernetes dropping invalid conntrack rule"`,
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Not sure this needs a comment line - it is self describing

**Comment by thockin** [comment]
This is subtle, and I don't really understand what would cause it to happen.  Without a test I have no way to say whether this is doing anything at all.  Do we have any way to force this condition?

We must look at this for all sorts of traffic, too - NodePorts, LB IPs, etc.  Does this cover them all?

Also need to be looked at in IPVS mode.  @m1093782566

**Comment by anfernee** [comment]
I created a small app to reproduce this issue: https://github.com/anfernee/k8s-issue-74839

**Comment by anfernee** [comment]
@m1093782566 do you have comments?

**Comment by anfernee** [comment]
@mainred this specific bug is all about the cluster-local traffic between 2 pods. other incoming traffic is not affected. The rule fixes the returning packet, so either NodePort or ClusterIP should already be fixed together.

**Comment by thockin** [comment]
@m1093782566 PTAL

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1298,6 +1298,16 @@ func (proxier *Proxier) syncProxyRules() {
 		}
 	}
 
+	// Drop the packets in INVALID state, which would potentially cause
+	// unexpected connection reset.
+	// https://github.com/kubernetes/kubernetes/issues/74839
+	writeLine(proxier.filterRules,
+		"-A", string(kubeForwardChain),
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go]: Wouldn't this need to be near the start of `syncProxyRules` rather than near the end? Many packets have already been matched and redirected by this point...

Comment (anfernee) [reply pkg/proxy/iptables/proxier.go]: Yes, it's the first rule in KUBE-FORWARD chain. 

```
Chain KUBE-FORWARD (1 references)
target     prot opt source               destination 
*** NEW RULE INSERTED HERE ***
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  10.36.0.0/14         anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             10.36.0.0/14         /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

```

Comment (danwinship) [reply pkg/proxy/iptables/proxier.go]: oh, all the (relevant) stuff before that is in `natRules`, not `filterRules`. ok

**Comment by danwinship** [comment]
So this needs a release note (@anfernee you would add this in the appropriate place in the initial comment on the PR). Something like:

    Packets considered INVALID by conntrack are now dropped. In particular, this fixes
    a problem where spurious retransmits in a long-running TCP connection to a service
    IP could result in the connection being closed with the error "Connection reset by
    peer"

And maybe it should not get backported right away, until we have more confidence that this doesn't break anything else.

/lgtm

**Comment by thockin** [comment]
@anfernee - I am still worred that we have no testing or way to test this.  Can you do me a favor at least and write a big comment at this code-site explaining it (I know you have a link, but I'd like some more detail here) and explaining why testing on this is "less than ideal" :)

@m1093782566 - we need input on IPVS mode

@Lion-Wei as a backup?

If you are not actively maintaining IPVS any more, please let me know, or suggest others who have expertise in it and can help shoulder the load.

**Comment by anfernee** [comment]
@thockin I will. In terms of testing, I have to rely on the existing tests to make sure it doesn't break anything. I also have this https://github.com/anfernee/k8s-issue-74839 to check if #74839 is fixed. It'll be great to make it part of the testgrid.

**Comment by anfernee** [comment]
Talked with @MrHohn https://github.com/kubernetes/kubernetes/tree/master/test/images is a good place to host my test app. Action Item for me to add an e2e.

**Comment by m1093782566** [comment]
@lbernail 

Would you please take a look at this issue for IPVS mode if you have bandwidth?

**Comment by lbernail** [comment]
@m1093782566 I had a look at the original issue and read through the linked page. My thoughts for IPVS:
- IPVS doesn't rely on NAT as much as iptables so it should be less impacted
- we still perform NAT for nodeport traffic and hairpin (and in a few other cases based on cluster-cidr and masquerade-all)

I don't know how the ipvs connection tracking system handles this situation. I think invalid packets arriving on the host should be dropped in the forward chain before hitting any ipvs code (because in ipvs mode, packets still hit the conntrack even if they are not NAT-ed), but we need to validate this

If this is ok with iptables, I see no reason it shouldn't be for IPVS. I'll try and reproduce on an ipvs setup and test adding this rule.

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
Comment (cmluciano) [reply pkg/proxy/iptables/proxier.go]: FYI Calico is doing similar things for disabling ConntrackInvalid https://github.com/projectcalico/felix/pull/1424 .

The Calico implementation also works for a cluster that runs IPVS as a load-balancer with iptables-mode of k8s-proxy .

Comment (anfernee) [reply pkg/proxy/iptables/proxier.go]: Ah, good to know. Thanks to bring it up @cmluciano . not sure if it should be an option here.. any reason not to enable that option?

**Comment by anfernee** [comment]
#76218 is the regression test for this PR.

**Comment by anfernee** [comment]
Looks like not much concerns from reviewers. and we are ready to go. 

The sequence I want to take is to merge #76218 first to make sure it breaks the testgrid, then merge this one to fix it.

**Comment by anfernee** [comment]
cc @danwinship @thockin

**Comment by danwinship** [comment]
I would assume that intentionally breaking the test grid is frowned upon. You could just temporarily remove the `[Slow]` from the test description in the other PR and run e2e-gce a few times

**Comment by lbernail** [comment]
I confirm we have the issue with IPVS for the case where we have NAT (verified in host networking to service communication which require SNAT)
I think we can integrate this change as-is in the IPVS proxier
I'll work on a PR

**Comment by anfernee** [comment]
@danwinship Done as you recommended, the e2e does fail. Both #76218 and this one should be good to merge now.

**Comment by anfernee** [comment]
cc @danwinship @thockin

**Comment by anfernee** [comment]
I've talked with @danwinship offline. basically got lgtm from him. @thockin can I have blessing from you?

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by vishnukraj1111** [comment]
Just to provide an update on this. The fix mentioned in most of the places echo 1 > /proc/sys/net/netfilter/ip_conntrack_tcp_be_liberal cause the conntrack table to be full and all connectivity to the servers were lost.

**Comment by WingkaiHo** [comment]
I have save problem, some time is udp package snat send to pod

**Comment by tuapuikia** [comment]
Anyone tested the patch it in crowded production environment?

**Comment by sepulworld** [comment]
Curious, if there is a safe way to apply this iptables rule prior to upgrading to 1.15? Looks like if you apply the rule `iptables -A "KUBE-FORWARD" -m "conntrack" --ctstate "INVALID" -j "DROP"` it will get flushed by kube-proxy.

**Comment by danwinship** [comment]
Yeah, you can't add rules to the chains kube-proxy is managing, but you could just add it to one of the top-level chains. (I guess, `FORWARD` in this case?)

**Comment by sepulworld** [comment]
I was thinking something like this:

```
iptables -N "KUBE-FORWARD-PATCH"
iptables -A "KUBE-FORWARD-PATCH" -m "conntrack" --ctstate "INVALID" -j "DROP"
iptables -I FORWARD -m comment --comment "k8s patch PR 74840" -j KUBE-FORWARD-PATCH
```

**Comment by alonisser** [comment]
Can someone clarify if the fix is in 15.7 already? if not in what version is it

**Comment by johannesboon** [comment]
@alonisser 
> Can someone clarify if the fix is in 15.7 already? if not in what version is it

Yes, I can: life is great again after upgrading to 1.15.0 (in our case from 1.14.x to 1.15.5).

But it was already included earlier, see: https://relnotes.k8s.io/?markdown=drop&releaseVersions=1.15.0

**Comment by unicell** [comment]
For those who might be interested, Conntrack INVALID Drop iptable rule introduced by this PR will break asymmetrical routing case as described in https://github.com/projectcalico/felix/issues/1248

It would be nice to have it configurable.

**Comment by danwinship** [comment]
> It would be nice to have it configurable.

Well, but you don't want the "long-term connections sometimes die randomly" bug to come back when you use asymmetrical routing. The fix would be to find a way a better way to do this that blocks the packets that cause random connection death without blocking packets related to asymmetric routing.

**Comment by kabakaev** [comment]
I've hit the assymetric routing issue die to this `KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP` rule. 
Isn't it too wide? Can we somehow make it more specific to the pod range?

**Comment by danwinship** [comment]
It seems like narrowing this should work, yes, although it's not guaranteed that kube-proxy knows the cluster CIDR range unfortunately. (We could try narrowing it iff kube-proxy knows the cluster CIDR.)

**Comment by cnmcavoy** [comment]
I agree with @kabakaev, this rule is too wide. I have to maintain my own private fork of kubernetes with this commit removed due to asymmetric routing for traffic outside the cluster on private subnets. :( If it was scoped to cluster cidr, that would no longer be necessary.

**Comment by agmimidi** [comment]
Hi all,

We have a setup with kube-proxy in ipvs mode and calico as CNI, in which we observe intermittent connection resets when pods are calling internal services in the cluster.

Calico does push the per-chain Iptables rules to drop the packets marked as invalid (e.g. -A cali-fw-cali08d8970e614 -m comment --comment "cali:pgiwwL2d0pFFF8jF" -m conntrack --ctstate INVALID -j DROP)  , but the drop rule for the KUBE-FORWARD chain is missing. Is that expected?

We are running kubernetes version 1.23.7 on Centos7 machines.

Any help would be appreciated.

**Comment by kk9384** [comment]
Hi all,
   We have a setup of GKE and the services inside the pods are facing socket exception connect reset intermittently only on few pods it is happening, the gke kubernetes version is 1.21.14, should we need to configure the below values? please advise, thank you.

iptables -N "KUBE-FORWARD-PATCH"
iptables -A "KUBE-FORWARD-PATCH" -m "conntrack" --ctstate "INVALID" -j "DROP"
iptables -I FORWARD -m comment --comment "k8s patch PR 74840" -j KUBE-FORWARD-PATCH

**Comment by aojea** [comment]
> We have a setup of GKE and the services inside the pods are facing socket exception connect reset intermittently only on few pods it is happening

what is the exact message?

**Comment by kk9384** [comment]
> > We have a setup of GKE and the services inside the pods are facing socket exception connect reset intermittently only on few pods it is happening
> 
> what is the exact message?

o.apache.http.impl.execchain.RetryExec   : I/O exception (java.net.SocketException) caught when processing request to {s}->https://<i_have_removed_host_name>:443: Connection reset

**Comment by aojea** [comment]
that may mean different causes, not necessarily this one , if <i_have_removed_host_name> stop listened on that port, if that is a service and the endpoint has changed or died on aggressive autoscaling, ....

**Comment by mehmetcolgecen** [comment]
Hi,
I am using on-prem kubernetes version 1.21.9, with MetalLB to provide LoadBalancer IP to the services and CNI is Calico. I am using an OCPP server inside kubernetes and server gets heartbeat signals from client throughout websocket connetcion.  Within this heartbeat periods, the connection interrupts with RST signals. Here is the TCPDUMP output  from inside pod;

ocppserver-bc6f65954-j99lx:/app# tcpdump 'tcp[13] & 4 != 0'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
14:07:59.726669 IP ocppserver-bc6f65954-j99lx.8080 > 10.42.176.0.53627: Flags [R], seq 2070087305, win 0, length 0
14:07:59.734667 IP ocppserver-bc6f65954-j99lx.8080 > 10.42.176.0.53627: Flags [R], seq 2070087305, win 0, length 0
14:08:27.646676 IP ocppserver-bc6f65954-j99lx.8080 > 10.42.176.0.9510: Flags [R], seq 355699249, win 0, length 0
14:08:27.654637 IP ocppserver-bc6f65954-j99lx.8080 > 10.42.176.0.9510: Flags [R], seq 355699249, win 0, length 0

I have applied "echo 1 > /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal" on both node and pod and
"iptables -I INPUT -m conntrack --ctstate INVALID -j DROP" on the node.

But the problem continues, do you have any suggestions for me.
