### PR TITLE
fix regression in UX experience for double attach volume

### LINKED ISSUE #46012: Fix regression in UX experience for double attach volume failure
This PR is a reminder to handle the comment of @saad-ali on https://github.com/kubernetes/kubernetes/pull/45346#issuecomment-302270624

I most likely won't be able to do this by myself due to missing time.

### PR DESCRIPTION
**Pull request by NickrenREN**
send event when volume is not allowed to multi-attach

Fixes #46012

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 1]
```diff
@@ -248,6 +252,15 @@ func (rc *reconciler) reconcile() {
 			if rc.isMultiAttachForbidden(volumeToAttach.VolumeSpec) {
 				nodes := rc.actualStateOfWorld.GetNodesForVolume(volumeToAttach.VolumeName)
 				if len(nodes) > 0 {
+					if volumeToAttach.AllowMultiAttach {
+						simpleMsg, detailedMsg := volumeToAttach.GenerateMsg("Multi-Attach error", "Volume is already exclusively attached to one node and can't be attached to another")
+						for _, pod := range volumeToAttach.ScheduledPods {
+							rc.recorder.Eventf(pod, v1.EventTypeWarning, "MultiAttachForbidden", simpleMsg)
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go]: nit: How about just `FailedAttach` instead of `MultiAttachForbidden` and stick it in a const.

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 2]
```diff
@@ -248,6 +252,15 @@ func (rc *reconciler) reconcile() {
...
+						}
+						volumeToAttach.AllowMultiAttach = false
+						glog.V(10).Infof(detailedMsg)
+					}
+
 					glog.V(4).Infof("Volume %q is already exclusively attached to node %q and can't be attached to %q", volumeToAttach.VolumeName, nodes, volumeToAttach.NodeName)
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go]: You can remove this message now.

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 3]
```diff
@@ -248,6 +252,15 @@ func (rc *reconciler) reconcile() {
 			if rc.isMultiAttachForbidden(volumeToAttach.VolumeSpec) {
 				nodes := rc.actualStateOfWorld.GetNodesForVolume(volumeToAttach.VolumeName)
 				if len(nodes) > 0 {
+					if volumeToAttach.AllowMultiAttach {
+						simpleMsg, detailedMsg := volumeToAttach.GenerateMsg("Multi-Attach error", "Volume is already exclusively attached to one node and can't be attached to another")
+						for _, pod := range volumeToAttach.ScheduledPods {
+							rc.recorder.Eventf(pod, v1.EventTypeWarning, "MultiAttachForbidden", simpleMsg)
+						}
+						volumeToAttach.AllowMultiAttach = false
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go]: You can raise this to `glog.Warning` since it should only happen once per volume.

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 4]
```diff
@@ -211,6 +211,9 @@ func generateVolumeMsg(prefixMsg, suffixMsg, volumeName, details string) (simple
 
 // VolumeToAttach represents a volume that should be attached to a node.
 type VolumeToAttach struct {
+	// AllowMultiAttach shows whether the volume is allowed to multi-attach
+	AllowMultiAttach bool
```
Comment (saad-ali) [inline pkg/volume/util/operationexecutor/operation_executor.go]: Let's rename this. The name and description here are misleading. It doesn't control whether the volume allows or does not allow multiattach. Rather, when a volume is blocked due to multi-attach this field is used to prevent an event from being generated more than once. So how about calling it `MultiAttachErrorReported`?

**Review by saad-ali — CHANGES_REQUESTED** [review]

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 5]
```diff
@@ -211,6 +211,9 @@ func generateVolumeMsg(prefixMsg, suffixMsg, volumeName, details string) (simple
 
 // VolumeToAttach represents a volume that should be attached to a node.
 type VolumeToAttach struct {
+	// MultiAttachErrorReported shows whether the multi attach err is reported or not
```
Comment (saad-ali) [inline pkg/volume/util/operationexecutor/operation_executor.go]: How about `MultiAttachErrorReported indicates whether the multi-attach error has been reported for the given volume. It is used to to prevent reporting the error from being reported more than once for a given volume.`

File: pkg/controller/volume/attachdetach/cache/desired_state_of_world.go [hunk 6]
```diff
@@ -158,6 +158,9 @@ type nodeManaged struct {
 
 // The volume object represents a volume that should be attached to a node.
 type volumeToAttach struct {
+	// allowMultiAttach shows whether the volume is allowed to multi-attach
+	allowMultiAttach bool
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/cache/desired_state_of_world.go]: Please rename `multiAttachErrorReported` and update comment similar to my other suggestion.

**Review by saad-ali — CHANGES_REQUESTED** [review]
A couple more comments

File: pkg/controller/volume/attachdetach/cache/desired_state_of_world.go (hunk 6 above)
Comment (NickrenREN) [inline pkg/controller/volume/attachdetach/cache/desired_state_of_world.go]: Done

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Review by saad-ali — APPROVED** [review]

**Comment by saad-ali** [comment]
Done

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
