### PR TITLE
kube-proxy full sync iptables one hour  even though nothing changes

### LINKED ISSUE #129128: kube-proxy should periodically resync iptables to recover from unexpected drift
### What would you like to be added?

kube-proxy performs a periodic full resync of iptables to correct unexpected drift between expected and actual iptables state.

### Why is this needed?

Today, kube-proxy performs a full resync of iptables only under certain conditions. In AKS, we have sometimes seen cases where iptables rules are accidentally modified (e.g. by daemonsets installed by a customer). Without some trigger (like a restart or endpoints created/deleted), kube-proxy won't detect or correct the drift between the actual/expected state of iptables.

A specific scenario in which this can happen:
1. iptables monitor polls until the canary chain in the mangle table is flushed, but doesn't check the canary chains in NAT or filter table: https://github.com/kubernetes/kubernetes/blob/d001d5684e69b08e120dc328917925318c5f324c/pkg/util/iptables/iptables.go#L586
2. Someone accidentally flushes the NAT table (`iptables -t nat -X`), but not the mangle table.

### PR DESCRIPTION
**Pull request by olderTaoist**
#### What this PR does / why we need it:
kube-proxy should  periodically rewrites every iptables rule 

#### Which issue(s) this PR fixes:

Fixes #129128

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by olderTaoist** [comment]
@danwinship @aojea @wedaly PTAL

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -325,7 +325,7 @@ func NewProxier(ctx context.Context,
 	// We pass syncPeriod to ipt.Monitor, which will call us only if it needs to.
 	// We need to pass *some* maxInterval to NewBoundedFrequencyRunner anyway though.
 	// time.Hour is arbitrary.
-	proxier.syncRunner = async.NewBoundedFrequencyRunner("sync-runner", proxier.syncProxyRules, minSyncPeriod, time.Hour, burstSyncs)
+	proxier.syncRunner = async.NewBoundedFrequencyRunner("sync-runner", proxier.forceSyncProxyRules, minSyncPeriod, time.Hour, burstSyncs)
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:328]: Alas, no, it's not that simple; this changes _all_ of the syncs via the BFR to be force syncs. There's (currently) no way to make the BFR do partial syncs normally and full syncs at `maxInterval`.

The easiest fix is probably to have the Proxier keep track of the last time it did a full sync, and then at the top of `syncProxyRules`, when it's deciding whether to `tryPartialSync` or not, it should take into account how long it has been since the last full sync.

Also, probably the `time.Hour` should be assigned to a constant (`requiredFullSyncInterval`? something like that...) rather than being hardcoded.

And yes, we should change each of the proxies to do this. (They all have basically the same architecture so it will be identical in each.) Though maybe that would be a good opportunity for refactoring a little bit? (If not, I have plans to get to this later.)

[the remark this answers is not in the document]
Comment (olderTaoist) [reply pkg/proxy/iptables/proxier.go]: > The easiest fix is probably to have the Proxier keep track of the last time it did a full sync, and then at the top of `syncProxyRules`, when it's deciding whether to `tryPartialSync` or not, it should take into account how long it has been since the last full sync.
>
add `lastFullSync` for each proxier to record lastest full sync time. without BFR,  take into account how long it has been since the last full sync in new timer.
 
> Also, probably the `time.Hour` should be assigned to a constant (`requiredFullSyncInterval`? something like that...) rather than being hardcoded.
>
yeah. this issue just forces full sync period
 
> And yes, we should change each of the proxies to do this. (They all have basically the same architecture so it will be identical in each.) Though maybe that would be a good opportunity for refactoring a little bit? (If not, I have plans to get to this later.)

Sorry, I am not familiar with ipvs, ipvs also need to be full sync?

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -540,7 +541,34 @@ func (proxier *Proxier) SyncLoop() {
 
 	// synthesize "last change queued" time as the informers are syncing.
 	metrics.SyncProxyRulesLastQueuedTimestamp.WithLabelValues(string(proxier.ipFamily)).SetToCurrentTime()
+	go proxier.FullSyncLoop()
```
Comment (wedaly) [inline pkg/proxy/iptables/proxier.go:544]: Bounded frequency runner already invokes `syncProxyRules` every 1hr, so I don't think we need to introduce another timer/loop:
https://github.com/kubernetes/kubernetes/blob/2e53799601509de9a031bc3a164f7ad73991e8b8/pkg/proxy/iptables/proxier.go#L328

Instead, we could follow the approach @danwinship  suggested in this comment https://github.com/kubernetes/kubernetes/pull/129329#discussion_r1893975318. Specifically, change `syncProxyRules`:
https://github.com/kubernetes/kubernetes/blob/2e53799601509de9a031bc3a164f7ad73991e8b8/pkg/proxy/iptables/proxier.go#L809-L811

1. set `tryPartialSync=false` if more than 1hr has elapsed since the last full sync or if `needFullSync` is true.
2. reset the time since last full sync whenever `!tryPartialSync`

I think it's okay if the full sync doesn't happen after _exactly_ an hour, as long as it happens eventually in some bounded amount of time.

Comment (olderTaoist) [reply pkg/proxy/iptables/proxier.go]: > Bounded frequency runner already invokes `syncProxyRules` every 1hr, so I don't think we need to introduce another timer/loop:
> 

see if the second commit meets your suggestion.

File: pkg/proxy/kubemark/hollow_proxy.go [hunk 3]
```diff
@@ -46,6 +46,11 @@ func (*FakeProxier) Sync() {}
 func (*FakeProxier) SyncLoop() {
 	select {}
 }
+
+func (*FakeProxier) FullSyncLoop() {
+	select {}
+}
```
Comment (wedaly) [inline pkg/proxy/kubemark/hollow_proxy.go:52]: this can be removed now

File: pkg/proxy/util/utils.go [hunk 4]
```diff
@@ -39,6 +40,10 @@ const (
 	IPv6ZeroCIDR = "::/0"
 )
 
+var (
+	FullSyncPeriod = 10 * time.Minute
```
Comment (wedaly) [inline pkg/proxy/util/utils.go:44]: this changes the bounded frequency runner `maxInterval` from 1hr to 10 minutes. I think we should keep it at 1hr to avoid regressing performance / CPU usage.

**Review by danwinship — COMMENTED** [review]
(I mostly only commented on the iptables part, but most of the comments apply to nftables too.)

Please squash the commits together into a single commit.

File: pkg/proxy/util/utils.go (hunk 4 above)
Comment (olderTaoist) [reply pkg/proxy/util/utils.go:44]: sorry, 10min is what I used to test the full sync, and I accidentally submitted it.

File: pkg/proxy/util/utils.go [hunk 5]
```diff
@@ -39,6 +40,10 @@ const (
 	IPv6ZeroCIDR = "::/0"
 )
 
+var (
```
[the remark this answers is not in the document]
Comment (olderTaoist) [reply pkg/proxy/util/utils.go:43]: sorry, 10min is what I used to test the full sync, and I accidentally submitted it.

File: pkg/proxy/iptables/proxier.go [hunk 6]
```diff
@@ -825,24 +826,26 @@ func (proxier *Proxier) syncProxyRules() {
 	serviceUpdateResult := proxier.svcPortMap.Update(proxier.serviceChanges)
 	endpointUpdateResult := proxier.endpointsMap.Update(proxier.endpointsChanges)
 
-	proxier.logger.V(2).Info("Syncing iptables rules")
+	proxier.logger.V(2).Info("Syncing iptables rules", "partialSync", doFullSync)
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go:829]:
```suggestion
	proxier.logger.V(2).Info("Syncing iptables rules", "fullSync", doFullSync)
```

File: pkg/proxy/nftables/proxier.go [hunk 7]
```diff
@@ -1190,7 +1190,7 @@ func (proxier *Proxier) syncProxyRules() {
 	serviceUpdateResult := proxier.svcPortMap.Update(proxier.serviceChanges)
 	endpointUpdateResult := proxier.endpointsMap.Update(proxier.endpointsChanges)
 
-	proxier.logger.V(2).Info("Syncing nftables rules")
+	proxier.logger.V(2).Info("Syncing nftables rules", "partialSync", doFullSync)
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go:1193]:
```suggestion
	proxier.logger.V(2).Info("Syncing nftables rules", "fullSync", doFullSync)
```

File: pkg/proxy/util/utils.go [hunk 8]
```diff
@@ -29,6 +26,9 @@ import (
 	"k8s.io/kubernetes/pkg/apis/core/v1/helper"
 	"k8s.io/kubernetes/pkg/features"
 	netutils "k8s.io/utils/net"
+	"net"
+	"strings"
+	"time"
```
Comment (danwinship) [inline pkg/proxy/util/utils.go:31]: `net` and `strings` should stay where they were and `time` should go with them.

The general rule for import sorting in k8s is: all stdlib imports first (if any), then all non-stdlib-non-`k8s.io` imports (if any), then all `k8s.io` imports (if any), with a blank line between each group.

**Review by danwinship — COMMENTED** [review]
just nitpicks left

File: pkg/proxy/iptables/proxier.go [hunk 9]
```diff
@@ -806,15 +808,14 @@ func (proxier *Proxier) syncProxyRules() {
...
 	}
 
-	// The value of proxier.needFullSync may change before the defer funcs run, so
-	// we need to keep track of whether it was set at the *start* of the sync.
-	tryPartialSync := !proxier.needFullSync
-
 	// Keep track of how long syncs take.
 	start := time.Now()
+
+	doFullSync := proxier.needFullSync || (start.Sub(proxier.lastFullSync) > proxyutil.FullSyncPeriod)
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:814]:
```suggestion
	doFullSync := proxier.needFullSync || (time.Since(proxier.lastFullSync) > proxyutil.FullSyncPeriod)
```

it is easier to read  https://go.dev/play/p/a6IUYQjWD0d

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:814]: oh, hold on, it was already discussed https://github.com/kubernetes/kubernetes/pull/129329#discussion_r1905555924, then I leave it to @danwinship suggestion

**Comment by aojea** [comment]
/lgtm
/kind feature

based on https://github.com/kubernetes/kubernetes/issues/129128#issuecomment-2529828987

**Review by wedaly — COMMENTED** [review]
I don't have any approval power, but these changes lgtm. Thanks for the fix!

File: pkg/proxy/iptables/proxier.go (hunk 9 above)
Comment (olderTaoist) [reply pkg/proxy/iptables/proxier.go]: done

**Comment by aojea** [comment]
/lgtm
/approve

Thanks
