### PR TITLE
fix: flake TestSchedulerScheduleOne

### LINKED ISSUE #128451: [Flake] TestSchedulerScheduleOne/[QueueingHint:_true]_error_prebind_pod
https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-30&pr=1&text=in-flight%20pods%20should%20be%20always%20empty%20after%20SchedulingOne

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/126962#discussion_r1822862075_
            
/priority important-soon
/milestone v1.32
/sig scheduling

This change was just merged a ~month ago, it is unclear if the fix is bad or the test is bad. Please resolve the flake or revert the change prior to 1.32.

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

We have to use `wait.Poll` to see the in-flight pods 
because if the Pod goes to the binding cycle, the inflight pods might be not empty immediately,
and will be empty after the binding cycle.

See https://storage.googleapis.com/k8s-triage/index.html?date=2024-10-30&pr=1&text=in-flight%20pods%20should%20be%20always%20empty%20after%20SchedulingOne.
All recent failures are from `_error_prebind_pod`, which indicates that the test flakes when the binding cycle involves in. 

#### Which issue(s) this PR fixes:

Fixes #128451

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/schedule_one_test.go [hunk 1]
```diff
@@ -852,7 +852,11 @@ func TestSchedulerScheduleOne(t *testing.T) {
 				if diff := cmp.Diff(item.expectBind, gotBinding); diff != "" {
 					t.Errorf("got binding diff (-want, +got): %s", diff)
 				}
-				if len(queue.InFlightPods()) != 0 {
+				// We have to use wait here
+				// because if the Pod goes to the binding cycle, the inflight pods might be not empty immediately at this point.
```
Comment (AxeZhan) [inline pkg/scheduler/schedule_one_test.go:856]:
```suggestion
				// because if the Pod goes to the binding cycle, the inflight pods might not be empty immediately at this point.
```

Comment (dom4ha) [inline pkg/scheduler/schedule_one_test.go:856]: Consider saying "because if the Pod is still in the binding cycle" or "We have to wait here until all Pods finish binding".

**Review by dom4ha — COMMENTED** [review]
/lgtm

File: pkg/scheduler/schedule_one_test.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/schedule_one_test.go]: the suggested one is inappropriate a bit because not all the Pods go to the binding cycle. But, I modified the comment anyways.
