### PR TITLE
Avoid listing pods in NodeLifecycleController

### LINKED ISSUE #77733: NodeLifecycleController is overloading kube-apiserver
**What happened**:

The current implementation of NodeLifecycleController generates "GET /api/v1/pods?fieldSelector=spec.nodeName=X" request for each node becoming unavailable. This request can be expensive when there is a high number of pods (O(100k)) running in the cluster.

The problem is that to prepare answer for that request, kube-apiserver needs to fetch all the data from etcd and then filter out almost all of them (only ~100 pods can be running on a single nodes).

In scalability tests we are seeing that killing ~50 nodes in 5000 node cluster is able to overload master in a way that kube-controller-manager/kube-scheduler is not able to renew leader lock due to request timeout.

https://github.com/kubernetes/kubernetes/blame/master/pkg/controller/util/node/controller_utils.go#L125

**What you expected to happen**:

I expected that killing 50 nodes in 5000 won't affect master's performance.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

In my opinion we should consider reimplementing this in some other way that will reduce master load.

Some potential options:
* Migrate to watch interface for pods (likely unfeasible due to freshness requirements)
* Investigate what etcd offers for such requests
* Implement some k8s-level index for spec.nodeName field (e.g. dedicated objects that for each node keeps a list of pods running on that node).

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/cc @wojtek-t @krzysied 
/sig scalability

### PR DESCRIPTION
**Pull request by krzysied**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Reduces number of pods lists on cluster level.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/77733

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 1]
```diff
@@ -712,6 +733,10 @@ func (nc *Controller) monitorNodeHealth() error {
 			continue
 		}
 
+		nc.nodeHealthMap[node.Name].observedReadyCondition = &observedReadyCondition
```
Comment (mborsz) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I think it's quite weird that you need to store both observedReadyCondition and currentReadyCondition.

Please also not that tryUpdateNodeHealth is already updating nc.nodeHealthMap so maybe the data you need is already there or you can extend that place to keep more data if needed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 2]
```diff
@@ -1093,6 +1123,77 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+								nodeName,
+								decisionTimestamp,
+								status.readyTransitionTimestamp,
+								nc.podEvictionTimeout-status.gracePeriod,
+							)
+						}
+					}
+				}
+
+				if status.currentReadyCondition.Status != v1.ConditionTrue &&
```
Comment (mborsz) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I think this is incorrect (correct me if I'm wrong).

currentReadyCondition.Status != observedReadyCondition.Status only if in the last loop of monitorNodeHealth the node has changed the status.

What if e.g.
* in first loop monitorNodeHealth node goes unhealthy, so currentReadyCondition.Status != observedReadyCondition.Status
* in the second loop monitorNodeHealth node is still unhealthy so currentReadyCondition.Status == observedReadyCondition.Status
* after that podUpdate appears and you don't enter that if (but I think you should).

Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Ok. I think I understand the idea now.
[This if](https://github.com/kubernetes/kubernetes/blob/a268eefc31e3a5d13ea867d47c1a4b060e52343d/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L818) checks only the transition so marking pods is only done once. However, when pod is added I need to check against the current state.
Good catch.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 1 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I've removed the additional fields. It turns out:
- grace period can have only one value - we use it only when currentReadyCondition != nil.
- observedReadyCondition is not needed. IMHO we can use only currentReadyCondition here.
tryUpdateNodeHealth method will update node statues in case currentReadyCondition is different than observedReadyCondition, else (if currentReadyCondition !=nil - our case) observedReadyCondition is a copy of currentReadyCondition.
- currentReadyCondition is calculated based on saved node status.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 3]
```diff
@@ -1072,6 +1093,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
 	}
 }
 
+func (nc *Controller) podUpdated(oldPod, newPod *v1.Pod) {
+	if len(newPod.Spec.NodeName) != 0 && (oldPod == nil || newPod.Spec.NodeName != oldPod.Spec.NodeName) {
+		nc.podUpdateQueue.Add(newPod)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I've already wrote a long comment that putting object is not the best pattern and then realized that it actually can work here. But this is purely because a given pod can be added to the queue at most once for its whole lifetime.
So this requires an extensive comment why is it done this way.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 4]
```diff
@@ -1072,6 +1093,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
 	}
 }
 
+func (nc *Controller) podUpdated(oldPod, newPod *v1.Pod) {
```
[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: It's even more misleading that it puts object to the queue.
Maybe somethign like queuePodUpdateIfNeeded (or sth like that).

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 5]
```diff
@@ -185,7 +185,8 @@ type Controller struct {
 
 	knownNodeSet map[string]*v1.Node
 	// per Node map storing last observed health together with a local time when it was observed.
-	nodeHealthMap map[string]*nodeHealthData
+	nodeHealthLock sync.Mutex
+	nodeHealthMap  map[string]*nodeHealthData
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Please encapsulate this to its own structure (this way we will be sure that we changed everything that was needed).
The structure will have get() and set() methods basically (that will be protected with mutex).

Also do it in a separate PR :)

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 6]
```diff
@@ -1072,6 +1093,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+
+			gracePeriod := nc.nodeMonitorGracePeriod
+			_, currentReadyCondition := nodeutil.GetNodeCondition(nodeHealth.status, v1.NodeReady)
+			if currentReadyCondition == nil {
+				// Nothing to do. Pod will be handled by monitorNodeHealth when needed.
+				return
+			}
+
+			decisionTimestamp := nc.now()
+			if nc.useTaintBasedEvictions {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: It seems you're basically trying to replica this logic:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L727-L802

So this seems incorrect - it seems it should be if "!" nc.use...

That said - this is generating a lot of copy-pasted code, which is very bad.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 7]
```diff
@@ -1072,6 +1093,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+				if currentReadyCondition.Status == v1.ConditionFalse &&
+					decisionTimestamp.After(nodeHealth.readyTransitionTimestamp.Add(nc.podEvictionTimeout)) {
+					if nc.evictPods(node) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Moreover, this isn't really behaving how we would like this to behave.

evictPods is actually only marking a node to evict all the pods that are scheduled on that node.
So if we will call evictPods() for the same node multiple times, if our cache for pods is lagging, we will be trying to evict the same pods over and over again.

Unless I'm not missing anything, I think the logic should be main like: "evictPods(node, pods)" (that will only be appending given pods for a particular node for eviction).

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 5 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: ref #82489

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 8]
```diff
@@ -206,6 +207,51 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	defer p.lock.Unlock()
+	if _, exists := p.podMap[node]; !exists {
+		p.podMap[node] = make(map[string]*v1.Pod)
+	}
+	for i := range pods {
+		p.podMap[node][string(pods[i].UID)] = &pods[i]
+	}
+}
+
+func (p *podsToEvictMap) getAndRemove(node string) []v1.Pod {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: the interface here looks bad to me - why can't we return slice of pointers?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 9]
```diff
@@ -206,6 +207,51 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	p.lock.Lock()
+	defer p.lock.Unlock()
+	defer func() {
+		p.podMap[node] = make(map[string]*v1.Pod)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Why? Can't we just delete this field?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 10]
```diff
@@ -206,6 +207,51 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	}()
+	if pods, exists := p.podMap[node]; exists {
+		podList := make([]v1.Pod, 0, len(pods))
+		for _, v := range pods {
+			podList = append(podList, *v)
+		}
+		return podList
+	}
+	return []v1.Pod{}
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This whole construct looks strange. Why not:

```
pods, exists := p.podMap[node]
if !exists {
  return ...
}
podList := ...
for ...
delete(podMap, node)

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 11]
```diff
@@ -206,6 +207,51 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	podMap map[string]map[string]*v1.Pod
+}
+
+func newPodsToEvictMap() *podsToEvictMap {
+	return &podsToEvictMap{
+		podMap: make(map[string]map[string]*v1.Pod),
+	}
+}
+
+func (p *podsToEvictMap) add(node string, pods []v1.Pod) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: s/node/nodeName/

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 12]
```diff
@@ -206,6 +207,51 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	p.lock.Lock()
+	defer p.lock.Unlock()
+	if _, exists := p.podMap[node]; !exists {
+		p.podMap[node] = make(map[string]*v1.Pod)
+	}
+	for i := range pods {
+		p.podMap[node][string(pods[i].UID)] = &pods[i]
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: what's the point of casting? why can't we make map[types.UID] instead of map[string] ?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 13]
```diff
@@ -758,87 +816,23 @@ func (nc *Controller) monitorNodeHealth() error {
...
-					}
-					if removed {
-						klog.V(2).Infof("Node %s is healthy again, removing all taints", node.Name)
-					}
-				} else {
-					if nc.cancelPodEviction(node) {
-						klog.V(2).Infof("Node %s is ready again, cancelled pod eviction", node.Name)
-					}
-				}
+			if nc.useTaintBasedEvictions {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This is nice refactoring, which is independent from this PR.
Can you please move it to a separate PR - it would be much easier to review it.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 14]
```diff
@@ -673,7 +730,8 @@ func (nc *Controller) doEvictionPass() {
 				klog.Warningf("Failed to get Node %v from the nodeLister: %v", value.Value, err)
 			}
 			nodeUID, _ := value.UID.(string)
-			remaining, err := nodeutil.DeletePods(nc.kubeClient, nc.recorder, value.Value, nodeUID, nc.daemonSetStore)
+			pods := nc.podsToEvict.getAndRemove(value.Value)
+			remaining, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, value.Value, nodeUID, nc.daemonSetStore)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This may have significant impact on how we rate limit.
Imagine that we're slowly delivering updates of pods - then for each of those we may potentially need to run a separate eviction pass (in practive probably not super probable, but still).
I would like to see the explanation why we believe it's fine.

Conceptually, what would be more correct is: if a node has already been processed by doEvictionPass, newly added pod is immediately evicted to (without really waiting for the next eviction pass).

File: pkg/controller/util/node/controller_utils.go [hunk 15]
```diff
@@ -44,29 +42,22 @@ import (
 // DeletePods will delete all pods from master running on given node,
 // and return true if any pods were deleted, or were found pending
 // deletion.
-func DeletePods(kubeClient clientset.Interface, recorder record.EventRecorder, nodeName, nodeUID string, daemonStore appsv1listers.DaemonSetLister) (bool, error) {
+func DeletePods(kubeClient clientset.Interface, pods []v1.Pod, recorder record.EventRecorder, nodeName, nodeUID string, daemonStore appsv1listers.DaemonSetLister) (bool, error) {
```
Comment (wojtek-t) [inline pkg/controller/util/node/controller_utils.go]: Can we split this PR even further to do a bit more of this refactoring? In particular, I think it should be possible to factor out to a separate PR:
- changes in the test (setting getPodsAssignedToNode function)
- changes to the interface to DeletePod (and for now just introduce a small helper function for listing pods from a node using the client)
- changes to the interface to MarkPodsReady

This would make: (1) the factored out changes no-op, so easy to review, (2) this PR much smaller (i.e. also much easier to review)

Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: > changes in the test (setting getPodsAssignedToNode function)

https://github.com/kubernetes/kubernetes/pull/83248

Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: > changes to the interface to DeletePod (and for now just introduce a small helper function for listing pods from a node using the client)

#83320

Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 14 above)
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: @krzysied - has this been addressed?

Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I changed `podToEvictionMap` to `nodeEvictionMap`. It contains list of pods to be evicted + node eviction status.
If node eviction status == evicted, pods are deleted immediately.
nodeEvictionMap is protected by evictorLock.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 16]
```diff
@@ -208,6 +208,64 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+		return []v1.Pod{}
+	}
+	podList := make([]v1.Pod, 0, len(pods))
+	for _, v := range pods {
+		podList = append(podList, *v)
+	}
+	return podList
+}
+
+func (n *nodeEvictionMap) deletePods(nodeName string) {
```
[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Now I see - it's not always the case. But I still think it's better to just have this, and call addPods() if some call in the meantime failed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 17]
```diff
@@ -847,7 +900,7 @@ func (nc *Controller) processTaintBaseEviction(node *v1.Node, observedReadyCondi
 	}
 }
 
-func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration) {
+func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration, pods []v1.Pod) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: pods []*v1.Pod

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 18]
```diff
@@ -1307,9 +1413,25 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
 // queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// If node was already evicted, the pods are deleted immediately.
+func (nc *Controller) evictPods(node *v1.Node, pods []v1.Pod) bool {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
+	if nc.nodeEvictionMap.getStatus(node.Name) == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		remaining, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, node.Name, string(node.UID), nc.daemonSetStore)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: What does remaining mean? What if we try to DeletePods for pods that we already tried before?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 19]
```diff
@@ -208,6 +208,64 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
 
+type evictionStatus int
+
+const (
+	unmarked = iota
+	toBeEvicted
+	evicted
+)
+
+// nodeEvictionMap requires outside provided synchronization.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 20]
```diff
@@ -208,6 +208,64 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+type nodeEvictionMap struct {
+	statusMap map[string]evictionStatus
+	// podMap: nodeName -> podUID -> pod.
+	podMap map[string]map[types.UID]*v1.Pod
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: getPods removed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 17 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 18 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: https://github.com/kubernetes/kubernetes/blob/833e8dc10bdce43fc8229c39639a7f7364703874/pkg/controller/util/node/controller_utils.go#L42-L44

> What if we try to DeletePods for pods that we already tried before?

Good question. I think I should add special handling for the case when we try to delete pod that doesn't exist anymore.

Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Handling added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 21]
```diff
@@ -847,7 +899,7 @@ func (nc *Controller) processTaintBaseEviction(node *v1.Node, observedReadyCondi
 	}
 }
 
-func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration) {
+func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration, pods []*v1.Pod) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Can you move the Pod pointer part to a separate PR?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 22]
```diff
@@ -1307,9 +1412,25 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
 
 // evictPods queues an eviction for the provided node name, and returns false if the node is already
 // queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// If node was already evicted, the pods are deleted immediately.
+func (nc *Controller) evictPods(node *v1.Node, pods []*v1.Pod) bool {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
+	if nc.nodeEvictionMap.getStatus(node.Name) == evicted {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: With this change, evictorLock is protecting a section that may be potentially extremely long (DeletePods may take seconds).
I think we need to change that.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 21 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: moved to #83780

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 22 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Goroutine added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 23]
```diff
@@ -1193,6 +1245,58 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+				return
+			}
+
+			pods := []*v1.Pod{pod}
+			if !nc.useTaintBasedEvictions {
+				nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods)
+			}
+
+			if currentReadyCondition.Status != v1.ConditionTrue {
+				if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, nodeName); err != nil {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I'm not sure I understand why we do this.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 24]
```diff
@@ -1193,6 +1246,68 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	node, err := nc.nodeLister.Get(nodeName)
+	if err != nil {
+		klog.Errorf("Failed to read node %v.", nodeName)
+		return
+	}
+
+	_, currentReadyCondition := nodeutil.GetNodeCondition(nodeHealth.status, v1.NodeReady)
+	if currentReadyCondition == nil {
+		// We can simply return from here. Even if nodes cache is not up-to-date,
+		// the pod will be handled correctly (evicted if needed) during processing of the node update event.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I know this comment was me, but when I read it, it doesn't make much sense to me now.

// Lack of NodeReady condition may only happen after node addition (or if it will be maliciously deleted).
// In both cases, the pod will be handled correctly (evicted if needed) during processing
// of the next node update event.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 25]
```diff
@@ -1193,6 +1246,68 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		return
+	}
+
+	pods := []*v1.Pod{pod}
+	// Taint based eviction is handled by TaintManager.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This comment isn't extremely helpful - we do have processTaintBasedEviction and it is doing something.
Change to sth like:
// In taint-based eviction mode, only node updates are processed by NodeLifecycleController.
// Pods are processed by TaintManager

Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Which actually made be realize, that we should only:
- register handlers for pods in taintBaseEviction mode
- start workers only in that mode

[Probably also rename some process* function to reflect that we only use them in NoTaintBasedEviction mode.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 26]
```diff
@@ -1193,6 +1246,68 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	if !nc.useTaintBasedEvictions {
+		nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods)
+	}
+
+	if currentReadyCondition.Status != v1.ConditionTrue {
+		if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, nodeName); err != nil {
+			utilruntime.HandleError(fmt.Errorf("Unable to mark pods NotReady on node %v: %v", nodeName, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: don't we need other error handling here?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 3 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I've reimplemented handling the queue. Now pod key (namespace/name) is added to queue.
Passing namespace is required due to podLister specification.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 27]
```diff
@@ -228,7 +285,8 @@ type Controller struct {
 	nodeHealthMap *nodeHealthMap
 
 	// Lock to access evictor workers
-	evictorLock sync.Mutex
+	evictorLock     sync.Mutex
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 28]
```diff
@@ -517,6 +581,10 @@ func (nc *Controller) Run(stopCh <-chan struct{}) {
 		go wait.Until(nc.doNodeProcessingPassWorker, time.Second, stopCh)
 	}
 
+	for i := 0; i < podUpdateWorkerSize; i++ {
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I assumed that most handling will be fast (nothing to do). Long handling will only happen when cache is lagging, still not so many cases. IMHO 4 should be enough.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 29]
```diff
@@ -675,16 +743,14 @@ func (nc *Controller) doEvictionPass() {
...
 			nodeUID, _ := value.UID.(string)
-			pods, err := listPodsFromNode(nc.kubeClient, value.Value)
-			if err != nil {
-				utilruntime.HandleError(fmt.Errorf("unable to list pods from node %q: %v", value.Value, err))
-				return false, 0
-			}
+			pods := nc.nodeEvictionMap.deletePods(value.Value)
 			remaining, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, value.Value, nodeUID, nc.daemonSetStore)
 			if err != nil {
+				nc.nodeEvictionMap.addPods(value.Value, pods)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 30]
```diff
@@ -1307,9 +1412,23 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+func (nc *Controller) evictPods(node *v1.Node, pods []*v1.Pod) bool {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
+	if nc.nodeEvictionMap.getStatus(node.Name) == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		go func() {
+			_, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, node.Name, string(node.UID), nc.daemonSetStore)
+			if err != nil {
+				utilruntime.HandleError(fmt.Errorf("unable to delete pods from node %q: %v", node.Name, err))
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Re-queuing added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller_test.go [hunk 31]
```diff
@@ -86,24 +90,23 @@ type nodeLifecycleController struct {
...
+			nc.nodeEvictionMap.setStatus(value.Value, evicted)
 			return true, 0
 		})
 	}
 
 	for _, action := range fakeNodeHandler.Actions() {
 		if action.GetVerb() == "delete" && action.GetResource().Resource == "pods" {
-			podEvicted = true
-			return podEvicted
+			return true
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller_test.go]: `podEvicted` removed.

File: pkg/controller/util/node/controller_utils.go [hunk 32]
```diff
@@ -128,9 +130,9 @@ func MarkPodsNotReady(kubeClient clientset.Interface, pods []v1.Pod, nodeName st
 					break
 				}
 				klog.V(2).Infof("Updating ready status of pod %v to false", pod.Name)
-				_, err := kubeClient.CoreV1().Pods(pod.Namespace).UpdateStatus(&pod)
+				_, err := kubeClient.CoreV1().Pods(pod.Namespace).UpdateStatus(pod)
 				if err != nil {
-					klog.Warningf("Failed to update status for pod %q: %v", format.Pod(&pod), err)
+					klog.Warningf("Failed to update status for pod %q: %v", format.Pod(pod), err)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: IMHO if we are marking pod not-ready, we assume it should exist.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 33]
```diff
@@ -1193,6 +1245,58 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		// "podUpdateQueue" will be shutdown when "stopCh" closed;
+		// we do not need to re-check "stopCh" again.
+		if shutdown {
+			return
+		}
+
+		pod := obj.(*v1.Pod)
+		nodeName := pod.Spec.NodeName
+
+		func() {
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 34]
```diff
@@ -1193,6 +1245,58 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+			defer nc.podUpdateQueue.Done(pod)
+
+			nodeHealth := nc.nodeHealthMap.getDeepCopy(nodeName)
+			if nodeHealth == nil {
+				return
+			}
+
+			node, err := nc.nodeLister.Get(nodeName)
+			if err != nil {
+				klog.Errorf("Failed to list node %v.", nodeName)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 35]
```diff
@@ -1193,6 +1245,58 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+
+		pod := obj.(*v1.Pod)
+		nodeName := pod.Spec.NodeName
+
+		func() {
+			defer nc.podUpdateQueue.Done(pod)
+
+			nodeHealth := nc.nodeHealthMap.getDeepCopy(nodeName)
+			if nodeHealth == nil {
+				return
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Comment added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 36]
```diff
@@ -1193,6 +1245,58 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+			}
+
+			node, err := nc.nodeLister.Get(nodeName)
+			if err != nil {
+				klog.Errorf("Failed to list node %v.", nodeName)
+				return
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Requque added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 37]
```diff
@@ -675,21 +742,21 @@ func (nc *Controller) doEvictionPass() {
...
 				utilruntime.HandleError(fmt.Errorf("unable to evict node %q: %v", value.Value, err))
 				return false, 0
 			}
+			nc.nodeEvictionMap.setStatus(value.Value, evicted)
 			if remaining {
 				klog.Infof("Pods awaiting deletion due to Controller eviction")
 			}
 
-			//count the evictionsNumber
+			// Count the evictionsNumber.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Removed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 38]
```diff
@@ -1193,6 +1246,68 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	for {
+		obj, shutdown := nc.podUpdateQueue.Get()
+		// "podUpdateQueue" will be shutdown when "stopCh" closed;
+		// we do not need to re-check "stopCh" again.
+		if shutdown {
+			return
+		}
+
+		pod := obj.(*v1.Pod)
+		nodeName := pod.Spec.NodeName
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 39]
```diff
@@ -1193,6 +1246,68 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	if nodeHealth == nil {
+		// Pod will be handled by standard eviction pass,
+		// when node data is collected.
+		return
+	}
+
+	node, err := nc.nodeLister.Get(nodeName)
+	if err != nil {
+		klog.Errorf("Failed to read node %v.", nodeName)
+		return
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Requeue added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 40]
```diff
@@ -1307,9 +1423,22 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
 // queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// If node was already evicted, the pods are deleted immediately.
+func (nc *Controller) evictPods(node *v1.Node, pods []*v1.Pod) bool {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
+	if nc.nodeEvictionMap.getStatus(node.Name) == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		// TODO: API calls shouldn't be executed under the lock.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 24 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 25 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Don't we need workers for marking pods not-ready? This part of code is executed independently of taintBaseEviction mode.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 26 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Requeue added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 41]
```diff
@@ -1406,3 +1550,14 @@ func (nc *Controller) reconcileNodeLabels(nodeName string) error {
 	}
 	return nil
 }
+
+// createPodKey creates pod key based on pod namespace and name.
+func createPodKey(namespace, name string) string {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Key doesn't have to be a string, because then you end up with this ugly splitting.
Please make a dedicated struct for it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L59

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 42]
```diff
@@ -1193,6 +1247,83 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	}
+}
+
+func (nc *Controller) processPod(podKey string) {
+	defer nc.podUpdateQueue.Done(podKey)
+	podNamespace, podName := splitPodKey(podKey)
+	pod, err := nc.podLister.Pods(podNamespace).Get(podName)
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			// If there is no pod, there is no need to requeue.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: If the pod was deleted ...

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 43]
```diff
@@ -1193,6 +1247,83 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+			return
+		}
+		utilruntime.HandleError(fmt.Errorf("Failed to read pod %v: %v", podKey, err))
+		nc.podUpdateQueue.Add(podKey)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Shouldn't be a big issue as errors should be very rare here, so TODO seems fine - there should be exponential backoff on that (or we should use RateLimittedQueue).

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 39 above)
[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This one actually may fail because of no-longer-existing.

So I think it actually makes sense to already migrat to RateLimitedQueue as we speak.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 25 above)
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Fair point - so just change the comment to what I added above.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 44]
```diff
@@ -208,10 +208,68 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	evicted
+)
+
+type nodeEviction struct {
+	status evictionStatus
+	pods   map[types.UID]*v1.Pod
+}
+
+// nodeEvictionMap is NOT thread-safe.
+type nodeEvictionMap map[string]*nodeEviction
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: nodeEvictionMap may grow indefinitely - we need a mechanism to clean it.

Not sure what's the best way - removing on Node removal may not be enough, because some pods may potentially be processed later?
Something you need to figure out.

File: pkg/controller/util/node/controller_utils.go (hunk 32 above)
[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/util/node/controller_utils.go]: In the meantime user could manually delete it for example.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 25 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 45]
```diff
@@ -227,12 +285,12 @@ type Controller struct {
 	// per Node map storing last observed health together with a local time when it was observed.
 	nodeHealthMap *nodeHealthMap
 
-	// Lock to access evictor workers
-	evictorLock sync.Mutex
-
+	// evictorLock protects nodeEvictionMap, zonePodEvictor and zoneNoExecuteTainter.
+	// TODO: API calls shouldn't be executed under the lock.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 46]
```diff
@@ -1193,6 +1247,83 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
 	}
 }
 
+func (nc *Controller) podUpdated(oldPod, newPod *v1.Pod) {
+	if newPod == nil {
+		// Nothing to do when pod is deleted.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Removed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 41 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 42 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 43 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: RateLimittingQueue added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 44 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: - deletetionStamp added to eviction map
- when node is deleted, deletionStamp is set
- if deletetionStamp is 5m old, node entry is removed.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 47]
```diff
@@ -208,10 +211,109 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	evicted
+)
+
+type nodeEviction struct {
+	status        evictionStatus
+	pods          map[types.UID]*v1.Pod
+	deletionStamp time.Time
+}
+
+// nodeEvictionMap is NOT thread-safe.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: no longer true

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 48]
```diff
@@ -208,10 +211,109 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+
+func (n *nodeEvictionMap) markForDeletion(nodeName string) {
+	n.lock.Lock()
+	defer n.lock.Unlock()
+	if _, exists := n.nodeEvictions[nodeName]; exists {
+		n.nodeEvictions[nodeName].deletionStamp = time.Now()
+	}
+}
+
+func (n *nodeEvictionMap) trimDeletedNodeEvictions() {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Do we really need this complicated logic?

Once the node gets removed, all the pods from that node will be handled by podgc controller (gc-orphaned).
So why can't we simply remove the entry for our node immediately after the node is being deleted?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 49]
```diff
@@ -131,6 +130,10 @@ const (
 	// The amount of time the nodecontroller should sleep between retrying node health updates
 	retrySleepTime   = 20 * time.Millisecond
 	nodeNameKeyIndex = "spec.nodeName"
+	// podUpdateWorkerSizes assumes that in most cases pod will be handled by monitorNodeHealth pass.
+	// Pod update workes will only handle lagging cache pods. 4 workes should be enough.
+	podUpdateWorkerSize             = 4
+	nodeEvictionDeletionGracePeriod = 5 * time.Minute
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: remove - no longer used

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 50]
```diff
@@ -208,10 +211,103 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	nodeEvictions map[string]*nodeEviction
+}
+
+func newNodeEvictionMap() *nodeEvictionMap {
+	return &nodeEvictionMap{
+		nodeEvictions: make(map[string]*nodeEviction),
+	}
+}
+
+func (n *nodeEvictionMap) addNodeEviction(nodeName string) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: addNodeEviction is extremely misleading name
Maybe "registerNode" ?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 51]
```diff
@@ -208,10 +211,103 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	n.lock.Lock()
+	defer n.lock.Unlock()
+	if _, exists := n.nodeEvictions[nodeName]; !exists {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: given where this is called (and if we name it registerNode), we probably don't need to check it - we can do that unconditionally

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 52]
```diff
@@ -208,10 +211,103 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+		n.nodeEvictions[nodeName] = &nodeEviction{
+			status: unmarked,
+			pods:   make(map[types.UID]*v1.Pod),
+		}
+	}
+}
+
+func (n *nodeEvictionMap) deleteNodeEviction(nodeName string) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: unregisterNode ?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 53]
```diff
@@ -675,21 +787,24 @@ func (nc *Controller) doEvictionPass() {
...
+			pods, ok := nc.nodeEvictionMap.deletePods(value.Value)
+			if !ok {
+				utilruntime.HandleError(fmt.Errorf("node %q eviction data doesn't exist", value.Value))
 				return false, 0
 			}
 			remaining, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, value.Value, nodeUID, nc.daemonSetStore)
 			if err != nil {
+				// In case of error, we re-add pods back to nodeEvictionMap and rely on next iteration
+				// of doEvictionPass to retry the deletion if still needed.
+				_ = nc.nodeEvictionMap.addPods(value.Value, pods)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Don't ignore what function returned silently.

Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: In case "false" is returned, we should probably log something like: "node X was unregistered in the meantime - skipping readding pods" or sth along those lines

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 54]
```diff
@@ -675,21 +787,24 @@ func (nc *Controller) doEvictionPass() {
...
 				utilruntime.HandleError(fmt.Errorf("unable to evict node %q: %v", value.Value, err))
 				return false, 0
 			}
+			_ = nc.nodeEvictionMap.setStatus(value.Value, evicted)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Same here and everywhere below

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 55]
```diff
@@ -1197,6 +1294,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+func (nc *Controller) processPod(podItem podUpdateItem) {
+	defer nc.podUpdateQueue.Done(podItem)
+	pod, err := nc.podLister.Pods(podItem.namespace).Get(podItem.name)
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			// If the pod was deleted, there is no need to requeue.
+			return
+		}
+		utilruntime.HandleError(fmt.Errorf("Failed to read pod %v/%v: %v", podItem.namespace, podItem.name, err))
+		nc.podUpdateQueue.Add(podItem)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: AddRateLimited

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 56]
```diff
@@ -1197,6 +1294,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		return
+	}
+
+	nodeName := pod.Spec.NodeName
+
+	nodeHealth := nc.nodeHealthMap.getDeepCopy(nodeName)
+	if nodeHealth == nil {
+		// Pod will be handled by standard eviction pass,
+		// when node data is collected.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Or the node was deleted in the meantime?

I think this comment should describe both cases.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 57]
```diff
@@ -1197,6 +1294,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		return
+	}
+
+	node, err := nc.nodeLister.Get(nodeName)
+	if err != nil {
+		utilruntime.HandleError(fmt.Errorf("Failed to read node %v: %v", nodeName, err))
+		nc.podUpdateQueue.Add(podItem)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: AddRateLimited

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 58]
```diff
@@ -1197,6 +1294,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	// In taint-based eviction mode, only node updates are processed by NodeLifecycleController.
+	// Pods are processed by TaintManager.
+	if !nc.useTaintBasedEvictions {
+		nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods)
+	}
+
+	if currentReadyCondition.Status != v1.ConditionTrue {
+		if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, nodeName); err != nil {
+			utilruntime.HandleError(fmt.Errorf("Unable to mark pod %v NotReady on node %v: %v", podItem.name, nodeName, err))
+			nc.podUpdateQueue.Add(podItem)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: AddRateLimited

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 56 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 53 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 59]
```diff
@@ -675,21 +784,28 @@ func (nc *Controller) doEvictionPass() {
 				klog.Warningf("Failed to get Node %v from the nodeLister: %v", value.Value, err)
 			}
 			nodeUID, _ := value.UID.(string)
-			pods, err := listPodsFromNode(nc.kubeClient, value.Value)
-			if err != nil {
-				utilruntime.HandleError(fmt.Errorf("unable to list pods from node %q: %v", value.Value, err))
+			pods, ok := nc.nodeEvictionMap.deletePods(value.Value)
+			if !ok {
+				utilruntime.HandleError(fmt.Errorf("node %q eviction data doesn't exist", value.Value))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This isn't an error per-se - it may happen in a healthy system and it is fine.

It requires a comment describing when it can happen and why it is fine to ignore it.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 60]
```diff
@@ -1197,6 +1295,82 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		nc.podUpdateQueue.AddRateLimited(podItem)
+		return
+	}
+
+	nodeName := pod.Spec.NodeName
+
+	nodeHealth := nc.nodeHealthMap.getDeepCopy(nodeName)
+	if nodeHealth == nil {
+		// Node data is not gathered yet or node has beed romeved.
+		// Pod will be handled by standard eviction pass.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: That's not the only case - another case is when the node was removed in the meantime.

Also please comment what the "standard eviction pass" is.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 61]
```diff
@@ -1311,9 +1488,26 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+func (nc *Controller) evictPods(node *v1.Node, pods []*v1.Pod) bool {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
+	status, ok := nc.nodeEvictionMap.getStatus(node.Name)
+	if ok && status == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		_, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, node.Name, string(node.UID), nc.daemonSetStore)
+		if err != nil {
+			utilruntime.HandleError(fmt.Errorf("unable to delete pods from node %q: %v", node.Name, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I think we should requeue in this case, right?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 62]
```diff
@@ -1311,9 +1488,26 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+		}
+		return false
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Either you should remove true, or update the comment of the function.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 59 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 60 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 61 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Error propagation added. When error is returned to processPod method, pod is requeued.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 62 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Changed to true.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 63]
```diff
@@ -779,27 +881,25 @@ func (nc *Controller) monitorNodeHealth() error {
 			zoneToNodeConditions[utilnode.GetZoneKey(node)] = append(zoneToNodeConditions[utilnode.GetZoneKey(node)], currentReadyCondition)
 		}
 
-		nodeHealthData := nc.nodeHealthMap.getDeepCopy(node.Name)
-		if nodeHealthData == nil {
-			klog.Errorf("Skipping %v node processing: health data doesn't exist.", node.Name)
+		pods, err := nc.getPodsAssignedToNode(node.Name)
+		if err != nil {
+			utilruntime.HandleError(fmt.Errorf("Unable to list pods of node %v: %v", node.Name, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: fmt.Errorf() should start with small letter

here and everywhere else

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 64]
```diff
@@ -1197,6 +1305,85 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		if shutdown {
+			return
+		}
+
+		podItem := obj.(podUpdateItem)
+		nc.processPod(podItem)
+	}
+}
+
+func (nc *Controller) processPod(podItem podUpdateItem) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This function requires extensive comment how the logic is handled:
- different scenarios that may happen (e.g. pod observed, node not yet observed; pod observed, node already deleted, etc.) and how each of them is handled

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 65]
```diff
@@ -1197,6 +1305,85 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		// of the next node update event.
+		return
+	}
+
+	pods := []*v1.Pod{pod}
+	// In taint-based eviction mode, only node updates are processed by NodeLifecycleController.
+	// Pods are processed by TaintManager.
+	if !nc.useTaintBasedEvictions {
+		if err := nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods); err != nil {
+			utilruntime.HandleError(fmt.Errorf("Unable to process pod %v eviction from node %v: %v", podItem.name, nodeName, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: If we're going to requeue - I'm not sure we should really handle this as error. 
In my opinion it should be more like klog.Warningf() or even Infof (probably Warningf). 

Same below.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 66]
```diff
@@ -1311,10 +1501,27 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
-	return nc.zonePodEvictor[utilnode.GetZoneKey(node)].Add(node.Name, string(node.UID))
+	status, ok := nc.nodeEvictionMap.getStatus(node.Name)
+	if ok && status == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		_, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, node.Name, string(node.UID), nc.daemonSetStore)
+		if err != nil {
+			return true, fmt.Errorf("unable to delete pods from node %q: %v", node.Name, err)
+		}
+		return true, nil
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This seems wrong - see how the result is handled. e.g. you log
"Node is NotReady. Adding Pods on Node %s to eviction queu..."

that's not what is happening in this path.

The logic and the comment should be changed so that it actually makes sense. (maybe bool is actually not what it should return?)

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 67]
```diff
@@ -675,21 +784,28 @@ func (nc *Controller) doEvictionPass() {
...
 			}
 			nodeUID, _ := value.UID.(string)
-			pods, err := listPodsFromNode(nc.kubeClient, value.Value)
-			if err != nil {
-				utilruntime.HandleError(fmt.Errorf("unable to list pods from node %q: %v", value.Value, err))
-				return false, 0
+			pods, ok := nc.nodeEvictionMap.deletePods(value.Value)
+			if !ok {
+				// Node was removed. Pods will be handled by podgc controller.
+				klog.V(2).Infof("node %q eviction data doesn't exist", value.Value)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 63 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 65 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 66 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 68]
```diff
@@ -851,18 +951,21 @@ func (nc *Controller) processTaintBaseEviction(node *v1.Node, observedReadyCondi
...
 }
 
-func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration) {
+func (nc *Controller) processNoTaintBaseEviction(node *v1.Node, observedReadyCondition *v1.NodeCondition, gracePeriod time.Duration, pods []*v1.Pod) error {
 	decisionTimestamp := nc.now()
 	nodeHealthData := nc.nodeHealthMap.getDeepCopy(node.Name)
 	if nodeHealthData == nil {
-		klog.Errorf("Skipping %v node processing: health data doesn't exist.", node.Name)
-		return
+		return fmt.Errorf("Skipping %v node processing: health data doesn't exist.", node.Name)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 64 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Comment added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 69]
```diff
@@ -675,21 +784,29 @@ func (nc *Controller) doEvictionPass() {
 				klog.Warningf("Failed to get Node %v from the nodeLister: %v", value.Value, err)
 			}
 			nodeUID, _ := value.UID.(string)
-			pods, err := listPodsFromNode(nc.kubeClient, value.Value)
-			if err != nil {
-				utilruntime.HandleError(fmt.Errorf("unable to list pods from node %q: %v", value.Value, err))
-				return false, 0
+			pods, ok := nc.nodeEvictionMap.deletePods(value.Value)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I should have done this thinking some time ago, but I started wondering if this whole PR isn't a bit of overkill.
I need to think a bit more about that, but at the high level what I'm thinking about is:
- assuming we're listing pods from cache, and ignoring NotFound errors in evicting and marking pods as not ready, it seems completely fine to me to avoid passing pods around in this code and just simply rely on what is in cache
- we are only risking that we will try to evict the same Pod N times, which isn't correctness issue and in general this should happen extremely rare...

So i guess what I'm suggesting is is roughly:
- remove references to pods from nodeEvictionMap completely - just keep the state
- here just list pods from cache
- modify the logic in evictPods() to list pods from node in the "evicted" case - from cache - we have guarantee that the cache state is at least synced to the point of handler when handler is called
- handle retries very similarly (or exactly as now?) in processPod()

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/81167#discussion_r337904923 is the most important comment - I need to think about it a bit more, but I'm almost sure this kind of simplification should work.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 69 above)
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I thought about it a bit more, and I'm fairly confident that it would be fine (and obviously much simpler).
It requires adding comments in MarkPodsNotReady and DeletePods to ignore NotFound errors...

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 70]
```diff
@@ -208,10 +210,101 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+
+type evictionStatus int
+
+const (
+	unmarked = iota
+	toBeEvicted
+	evicted
+)
+
+type nodeEviction struct {
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 71]
```diff
@@ -208,10 +210,101 @@ func (n *nodeHealthMap) set(name string, data *nodeHealthData) {
...
+	status evictionStatus
+	pods   map[types.UID]*v1.Pod
+}
+
+type nodeEvictionMap struct {
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 72]
```diff
@@ -779,27 +882,25 @@ func (nc *Controller) monitorNodeHealth() error {
...
 			continue
 		}
+
 		if currentReadyCondition != nil {
 			if nc.useTaintBasedEvictions {
 				nc.processTaintBaseEviction(node, &observedReadyCondition)
 			} else {
-				nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod)
+				if err := nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod, pods); err != nil {
+					utilruntime.HandleError(fmt.Errorf("Unable to evict all pods from node %v: %v", node.Name, err))
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 73]
```diff
@@ -779,27 +882,25 @@ func (nc *Controller) monitorNodeHealth() error {
...
 			// Report node event.
 			if currentReadyCondition.Status != v1.ConditionTrue && observedReadyCondition.Status == v1.ConditionTrue {
 				nodeutil.RecordNodeStatusChange(nc.recorder, node, "NodeNotReady")
-				pods, err := listPodsFromNode(nc.kubeClient, node.Name)
-				if err != nil {
-					utilruntime.HandleError(fmt.Errorf("Unable to list pods from node %v: %v", node.Name, err))
-					continue
-				}
-				if err = nodeutil.MarkPodsNotReady(nc.kubeClient, pods, node.Name); err != nil {
+				if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, node.Name); err != nil {
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 74]
```diff
@@ -1197,6 +1306,98 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
 	}
 }
 
+func (nc *Controller) podUpdated(oldPod, newPod *v1.Pod) {
+	if newPod == nil {
+		return
+	}
+	if len(newPod.Spec.NodeName) != 0 && (oldPod == nil || newPod.Spec.NodeName != oldPod.Spec.NodeName) {
+		podItem := podUpdateItem{newPod.Namespace, newPod.Name}
+		nc.podUpdateQueue.AddRateLimited(podItem)
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 64 above)
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: This comment is a big hard to parse.

// processPod is processing events of assigning pods to nodes. In particular:
// 1. for NodeReady=true node, taint eviction for this pod will be cancelled
// 2. for NodeReady=false or unknown node, taint eviction of pod will happen and pod will be marked as not ready
// 3. if node doesn't exist in cache, it will be skipped and handled later by doEvictionPass


[all other cases are kind of obvious]

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 75]
```diff
@@ -1197,6 +1265,97 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		klog.Warningf("Failed to read pod %v/%v: %v.", podItem.namespace, podItem.name, err)
+		nc.podUpdateQueue.AddRateLimited(podItem)
+		return
+	}
+
+	nodeName := pod.Spec.NodeName
+
+	nodeHealth := nc.nodeHealthMap.getDeepCopy(nodeName)
+	if nodeHealth == nil {
+		// Node data is not gathered yet or node has beed romeved in the meantime.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: nit: removed

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 76]
```diff
@@ -1309,12 +1471,32 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+//   The method returns false, cause the node wasn't added to the queue.
+func (nc *Controller) evictPods(node *v1.Node) (bool, error) {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
-	return nc.zonePodEvictor[utilnode.GetZoneKey(node)].Add(node.Name, string(node.UID))
+	status, ok := nc.nodeEvictionMap.getStatus(node.Name)
+	if ok && status == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		pods, err := nc.getPodsAssignedToNode(node.Name)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Sorry for going back and forth - I change my mind again. Let's actually try to delete only pods that we believe makes sense. So pass the pods explicitly here to this method.

File: pkg/controller/util/node/controller_utils.go [hunk 77]
```diff
@@ -80,6 +80,11 @@ func DeletePods(kubeClient clientset.Interface, pods []*v1.Pod, recorder record.
 		klog.V(2).Infof("Starting deletion of pod %v/%v", pod.Namespace, pod.Name)
 		recorder.Eventf(pod, v1.EventTypeNormal, "NodeControllerEviction", "Marking for deletion Pod %s from Node %s", pod.Name, nodeName)
 		if err := kubeClient.CoreV1().Pods(pod.Namespace).Delete(pod.Name, nil); err != nil {
+			if apierrors.IsNotFound(err) {
+				// Not founding pods is something that can happen in a cluster.
+				// This handling is crucial for correctness.
```
Comment (wojtek-t) [inline pkg/controller/util/node/controller_utils.go]: This comment isn't particularly useful for future reader. Why it is crucial?

// NotFound error means that pod was already deleted. There is nothing left to do with this pod.

File: pkg/controller/util/node/controller_utils.go [hunk 78]
```diff
@@ -133,6 +138,11 @@ func MarkPodsNotReady(kubeClient clientset.Interface, pods []*v1.Pod, nodeName s
 				klog.V(2).Infof("Updating ready status of pod %v to false", pod.Name)
 				_, err := kubeClient.CoreV1().Pods(pod.Namespace).UpdateStatus(pod)
 				if err != nil {
+					if apierrors.IsNotFound(err) {
+						// Not founding pods is something that can happen in a cluster.
+						// This handling is crucial for correctness.
```
Comment (wojtek-t) [inline pkg/controller/util/node/controller_utils.go]: Same here - it's not obvious why it is crucial for correctness.

// NotFound error means that pod was already deleted. There is nothing left to do with this pod.

File: pkg/controller/util/node/controller_utils.go (hunk 77 above)
Comment (wojtek-t) [reply pkg/controller/util/node/controller_utils.go]: I meant replace your whole comment with that, not just the second line.]

**Review by wojtek-t — COMMENTED** [review]
I think this is getting pretty close.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 79]
```diff
@@ -227,12 +285,12 @@ type Controller struct {
 	// per Node map storing last observed health together with a local time when it was observed.
 	nodeHealthMap *nodeHealthMap
 
-	// Lock to access evictor workers
-	evictorLock sync.Mutex
-
+	// evictorLock protects nodeEvictionMap, zonePodEvictor and zoneNoExecuteTainter.
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 80]
```diff
@@ -779,28 +841,26 @@ func (nc *Controller) monitorNodeHealth() error {
...
 				if err != nil {
-					utilruntime.HandleError(fmt.Errorf("Unable to list pods from node %v: %v", node.Name, err))
+					utilruntime.HandleError(fmt.Errorf("unable to list pods of node %v: %v", node.Name, err))
 					continue
 				}
-				if err = nodeutil.MarkPodsNotReady(nc.kubeClient, pods, node.Name); err != nil {
-					utilruntime.HandleError(fmt.Errorf("Unable to mark all pods NotReady on node %v: %v", node.Name, err))
+
+				if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, node.Name); err != nil {
+					utilruntime.HandleError(fmt.Errorf("unable to mark all pods NotReady on node %v: %v. Will retry in next iteration", node.Name, err))
```
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I added retryMarkPodsNotReadySet which stores names of nodes that require retrying MarkPodsNotReady.
The condition checks if the status changed from true to something different, or status is different than true and we need to retry.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 76 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/util/node/controller_utils.go (hunk 77 above)
Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: Done.

File: pkg/controller/util/node/controller_utils.go (hunk 78 above)
Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 80 above)
[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: The condition now seems to be incorrect.

Also - please move it to a separate PR - this is actually a bug fix.

File: pkg/controller/util/node/controller_utils.go [hunk 81]
```diff
@@ -80,6 +80,10 @@ func DeletePods(kubeClient clientset.Interface, pods []*v1.Pod, recorder record.
 		klog.V(2).Infof("Starting deletion of pod %v/%v", pod.Namespace, pod.Name)
 		recorder.Eventf(pod, v1.EventTypeNormal, "NodeControllerEviction", "Marking for deletion Pod %s from Node %s", pod.Name, nodeName)
 		if err := kubeClient.CoreV1().Pods(pod.Namespace).Delete(pod.Name, nil); err != nil {
+			if apierrors.IsNotFound(err) {
+				// NotFound error means that pod was already deleted. There is nothing left to do with this pod.
```
Comment (wojtek-t) [inline pkg/controller/util/node/controller_utils.go]: nit: please split the line

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 80 above)
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: I fixed the condition and moved the code to https://github.com/kubernetes/kubernetes/pull/84445

File: pkg/controller/util/node/controller_utils.go (hunk 81 above)
Comment (krzysied) [reply pkg/controller/util/node/controller_utils.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 80 above)
[the remark this answers is not in the document]
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: #84445 merged. Code rebased.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 82]
```diff
@@ -775,16 +834,19 @@ func (nc *Controller) monitorNodeHealth() error {
...
-		nodeHealthData := nc.nodeHealthMap.getDeepCopy(node.Name)
-		if nodeHealthData == nil {
-			klog.Errorf("Skipping %v node processing: health data doesn't exist.", node.Name)
-			continue
-		}
 		if currentReadyCondition != nil {
+			pods, err := nc.getPodsAssignedToNode(node.Name)
+			if err != nil {
+				utilruntime.HandleError(fmt.Errorf("unable to list pods of node %v: %v", node.Name, err))
+				nc.nodesToRetry.Store(node.Name, struct{}{})
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Why do we need this one? We will enter the "currentReadyCondition != nil" in the next iteration anyway, right?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 83]
```diff
@@ -1206,6 +1265,89 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+	if !nc.useTaintBasedEvictions {
+		if err := nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods); err != nil {
+			klog.Warningf("Unable to process pod %v eviction from node %v: %v.", podItem.name, nodeName, err)
+			nc.podUpdateQueue.AddRateLimited(podItem)
+		}
+	}
+
+	if currentReadyCondition.Status != v1.ConditionTrue {
+		if err := nodeutil.MarkPodsNotReady(nc.kubeClient, pods, nodeName); err != nil {
+			klog.Warningf("Unable to mark pod %v NotReady on node %v: %v.", podItem.name, nodeName, err)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: just podItem.name isn't useful - the whole podItem should be printed

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 84]
```diff
@@ -1318,12 +1463,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
 	return false
 }
 
-// evictPods queues an eviction for the provided node name, and returns false if the node is already
-// queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// evictPods:
+// - If node is not marked as evicted, it will be added to the evictor queue.
+//   The method returns false if the node name was already enqueued, otherwise true.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Returns false iff the node name was already enqueued.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 85]
```diff
@@ -1318,12 +1463,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+// - If node is marked as evicted, pods are deleted immediately.
+//   The method returns false, cause the node wasn't added to the queue.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Returns false, because ...

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 82 above)
Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Please add a comment - if I'm asking about it it means it's not obvious. Which means people will be asking about it in the future (or will simply remove it).

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 86]
```diff
@@ -794,8 +859,8 @@ func (nc *Controller) monitorNodeHealth() error {
 				nodeutil.RecordNodeStatusChange(nc.recorder, node, "NodeNotReady")
 				fallthrough
 			case needsRetry && observedReadyCondition.Status != v1.ConditionTrue:
-				if err := nc.markPodsNotReady(node.Name); err != nil {
-					utilruntime.HandleError(err)
+				if err = nodeutil.MarkPodsNotReady(nc.kubeClient, pods, node.Name); err != nil {
+					utilruntime.HandleError(fmt.Errorf("unable to mark all pods NotReady on node %v: %v", node.Name, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: ; queueing for retry

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 87]
```diff
@@ -775,16 +837,19 @@ func (nc *Controller) monitorNodeHealth() error {
...
+				utilruntime.HandleError(fmt.Errorf("unable to list pods of node %v: %v", node.Name, err))
+				nc.nodesToRetry.Store(node.Name, struct{}{})
+				continue
+			}
 			if nc.useTaintBasedEvictions {
 				nc.processTaintBaseEviction(node, &observedReadyCondition)
 			} else {
-				nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod)
+				if err := nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod, pods); err != nil {
+					utilruntime.HandleError(fmt.Errorf("unable to evict all pods from node %v: %v. Will retry in next iteration", node.Name, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: s/. Will retry.../; queueing for retry/

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 88]
```diff
@@ -1318,12 +1466,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
 	return false
 }
 
-// evictPods queues an eviction for the provided node name, and returns false if the node is already
-// queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// evictPods:
+// - If node is not marked as evicted, it will be added to the evictor queue.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: adds node to evictor queue if the node is not marked as evicted.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 89]
```diff
@@ -1318,12 +1466,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+//   Returns false if the node name was already enqueued.
+// - If node is marked as evicted, pods are deleted immediately.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: - deletes pods immediately if node is already marked as evicted

**Review by wojtek-t — COMMENTED** [review]
Just couple minor comments. Once applied I will take a (hopefully) final pass.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 86 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 87 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 88 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 89 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 82 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Comment added.
I also added `currentReadyCondition.Status != v1.ConditionTrue && observedReadyCondition.Status == v1.ConditionTrue` guard so we ensure that `MarkPodsNotReady` will be called only once after status transition.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 90]
```diff
@@ -1206,6 +1273,89 @@ func (nc *Controller) handleDisruption(zoneToNodeConditions map[string][]*v1.Nod
...
+		return
+	}
+
+	pods := []*v1.Pod{pod}
+	// In taint-based eviction mode, only node updates are processed by NodeLifecycleController.
+	// Pods are processed by TaintManager.
+	if !nc.useTaintBasedEvictions {
+		if err := nc.processNoTaintBaseEviction(node, currentReadyCondition, nc.nodeMonitorGracePeriod, pods); err != nil {
+			klog.Warningf("Unable to process pod %+v eviction from node %v: %v.", podItem, nodeName, err)
+			nc.podUpdateQueue.AddRateLimited(podItem)
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: return ?

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 91]
```diff
@@ -1318,12 +1471,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
 }
 
-// evictPods queues an eviction for the provided node name, and returns false if the node is already
-// queued for eviction.
-func (nc *Controller) evictPods(node *v1.Node) bool {
+// evictPods:
+// - adds node to evictor queue if the node is not marked as evicted.
+//   Returns false if the node name was already enqueued.
+// - deletes pods immediately if node is already marked as evicted.
+//   The method returns false, because the node wasn't added to the queue.
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: s/The method returns/Returns/

**Review by wojtek-t — COMMENTED** [review]
Last 2 very minor comments - other than that LGTM.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 91 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 90 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: It's additional pod status update call vs marking pod not ready in next pass.
I assume that it is very likely that if pod eviction failed than marking pods as not ready will fail as well... `return` added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 92]
```diff
@@ -775,16 +837,24 @@ func (nc *Controller) monitorNodeHealth() error {
...
+					nc.nodesToRetry.Store(node.Name, struct{}{})
+				}
+				continue
+			}
 			if nc.useTaintBasedEvictions {
 				nc.processTaintBaseEviction(node, &observedReadyCondition)
 			} else {
-				nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod)
+				if err := nc.processNoTaintBaseEviction(node, &observedReadyCondition, gracePeriod, pods); err != nil {
+					utilruntime.HandleError(fmt.Errorf("unable to evict all pods from node %v: %v; queuing for retry in next iteration", node.Name, err))
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: s/ in next iteration//

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 93]
```diff
@@ -775,16 +837,24 @@ func (nc *Controller) monitorNodeHealth() error {
...
-		nodeHealthData := nc.nodeHealthMap.getDeepCopy(node.Name)
-		if nodeHealthData == nil {
-			klog.Errorf("Skipping %v node processing: health data doesn't exist.", node.Name)
-			continue
-		}
 		if currentReadyCondition != nil {
+			pods, err := nc.getPodsAssignedToNode(node.Name)
+			if err != nil {
+				utilruntime.HandleError(fmt.Errorf("unable to list pods of node %v: %v", node.Name, err))
+				if currentReadyCondition.Status != v1.ConditionTrue && observedReadyCondition.Status == v1.ConditionTrue {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: good catch
that said, it requires some unit test

**Review by wojtek-t — COMMENTED** [review]
OK - one more nit and add one more unit test I mentioned. And will be good to go.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 92 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Done.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go (hunk 93 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: New case to `TestMonitorNodeHealthMarkPodsNotReadyRetry` added.

File: pkg/controller/nodelifecycle/node_lifecycle_controller_test.go [hunk 94]
```diff
@@ -2488,6 +2490,43 @@ func TestMonitorNodeHealthMarkPodsNotReadyRetry(t *testing.T) {
...
 		},
+		// Node created long time ago, with status updated by kubelet exceeds grace period.
+		// First monitorNodeHealth check will fail to list pods.
+		// Second monitorNodeHealth check will update pod status to NotReady (retry).
+		{
+			desc: "unsuccessful pod list, retry required",
+			fakeNodeHandler: &testutil.FakeNodeHandler{
+				Clientset: fake.NewSimpleClientset(&v1.PodList{Items: []v1.Pod{*testutil.NewPod("pod0", "node0")}}),
+			},
+			fakeGetPodsAssignedToNode: func() func(c *fake.Clientset) func(string) ([]*v1.Pod, error) {
```
Comment (wojtek-t) [inline pkg/controller/nodelifecycle/node_lifecycle_controller_test.go]: I don't get it - why you need func()?
Why it can't be:
```
func(c *fake.Clientset) func(string) ([]*v1.Pod, error) {
  // what you currently have?
}
```

**Review by wojtek-t — COMMENTED** [review]
just one nit

File: pkg/controller/nodelifecycle/node_lifecycle_controller_test.go (hunk 94 above)
Comment (krzysied) [reply pkg/controller/nodelifecycle/node_lifecycle_controller_test.go]: Good catch. I removed unneeded closure.

File: pkg/controller/nodelifecycle/node_lifecycle_controller.go [hunk 95]
```diff
@@ -1318,12 +1472,28 @@ func (nc *Controller) cancelPodEviction(node *v1.Node) bool {
...
+func (nc *Controller) evictPods(node *v1.Node, pods []*v1.Pod) (bool, error) {
 	nc.evictorLock.Lock()
 	defer nc.evictorLock.Unlock()
-	return nc.zonePodEvictor[utilnode.GetZoneKey(node)].Add(node.Name, string(node.UID))
+	status, ok := nc.nodeEvictionMap.getStatus(node.Name)
+	if ok && status == evicted {
+		// Node eviction already happened for this node.
+		// Handling immediate pod deletion.
+		_, err := nodeutil.DeletePods(nc.kubeClient, pods, nc.recorder, node.Name, string(node.UID), nc.daemonSetStore)
+		if err != nil {
```
Comment (tedyu) [inline pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Should NotExist err be excluded ?

Comment (wojtek-t) [reply pkg/controller/nodelifecycle/node_lifecycle_controller.go]: Yup - this should work fine.
