### PR TITLE
Changes to fix the node eviction flake

### LINKED ISSUE #39975: TestMonitorNodeStatusEvictPodsWithDisruption is flakey
Running latest from master (currently commit 8ab0519160594e5da50212da7994fc5dfbbe05de), I'm seeing TestMonitorNodeStatusEvictPodsWithDisruption is flakey:

1. go test -c ./pkg/controller/node
1. while true; do if ! ./node.test; then break; fi; done
1. wait for failure

I've narrowed it down https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/controller/node/nodecontroller_test.go#L1220, which is supposed to process all the items (nodes) in the `zonePodEvictor[zone]` queue. This queue has a capacity of 1, and at least in the test code, a refill rate of 10000 QPS. If the call to `TryAccept` fails [here](https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/controller/node/rate_limited_queue.go#L209), it will stop processing wherever it happened to be in the queue. I've added some extra logging locally, and when it fails, I see it processing nodes 1 and 2 before TryAccept fails. The issue is that the pod it's trying to evict is on node0, and it doesn't process node0 before TryAccept returns false.

cc @smarterclayton @mikedanese @liggitt @sttts

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #39975

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/node/nodecontroller_test.go [hunk 1]
```diff
@@ -761,6 +761,8 @@ func TestPodStatusChange(t *testing.T) {
 	}
 
 }
+var fakeNodeHandler *testutil.FakeNodeHandler
```
Comment (liggitt) [inline pkg/controller/node/nodecontroller_test.go]: I wouldn't expect a mutable package level var in a unit test

File: pkg/controller/node/nodecontroller_test.go [hunk 2]
```diff
@@ -1265,37 +1267,43 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
-		zones := testutil.GetZones(fakeNodeHandler)
-		for _, zone := range zones {
-			// Time for rate-limiter reloading per node.
-			time.Sleep(50 * time.Millisecond)
-			nodeController.zonePodEvictor[zone].Try(func(value TimedValue) (bool, time.Duration) {
+		podEvicted = false
+		// Infinite loop, used for retrying in case ratelimiter fails to reload for Try function.
+		// this breaks when we have the status that we need for test case.
+		// TODO: Add some timeout for infinite loop to break.
+		for {
```
Comment (liggitt) [inline pkg/controller/node/nodecontroller_test.go]: @gmarek I don't know what this is testing well enough to know if looping changes the meaning of the test. I could buy that it makes it succeed more, but I don't know if it invalidates the test or not.

File: pkg/controller/node/nodecontroller_test.go [hunk 3]
```diff
@@ -1265,37 +1267,43 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
 		}
-		zones := testutil.GetZones(fakeNodeHandler)
-		for _, zone := range zones {
-			// Time for rate-limiter reloading per node.
-			time.Sleep(50 * time.Millisecond)
-			nodeController.zonePodEvictor[zone].Try(func(value TimedValue) (bool, time.Duration) {
+		podEvicted = false
+		// Infinite loop, used for retrying in case ratelimiter fails to reload for Try function.
+		// this breaks when we have the status that we need for test case.
+		// TODO: Add some timeout for infinite loop to break.
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: This TODO has to go in this PR.

File: pkg/controller/node/nodecontroller_test.go (hunk 1 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: +1. Especially that this means that tests are not isolated.

File: pkg/controller/node/nodecontroller_test.go [hunk 4]
```diff
@@ -1265,37 +1267,43 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
 				podEvicted = true
-				break
 			}
 		}
-
-		if item.expectedEvictPods != podEvicted {
-			t.Errorf("%v: expected pod eviction: %+v, got %+v", item.description, item.expectedEvictPods, podEvicted)
-		}
-	}
+	return podEvicted
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: It looks like it even shouldn't compile - podEvicted is not declared.

File: pkg/controller/node/nodecontroller_test.go (hunk 2 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: This generally looks fine. Except this for-loop being infinite smells wrong. We can certainly retry few times, just in case the CPU on the worker is overutilized.

File: pkg/controller/node/nodecontroller_test.go (hunk 1 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: I can make this change. I would have removed that anyways, just wanted to check if you are ok with core logic.

File: pkg/controller/node/nodecontroller_test.go (hunk 2 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: > Except this for-loop being infinite smells wrong. We can certainly retry few times.

@gmarek - So, I was having a problem in coming up with number. It worked fine with 50 being max number of retries on my system but when I tried on another system, it failed. As you suggested, whatever the number we choose, it may not be perfect based on CPU load. So, if you are ok with timeout as a limit, the timeout being 5 min, I can make that change.

File: pkg/controller/node/nodecontroller_test.go (hunk 3 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: Ok..

File: pkg/controller/node/nodecontroller_test.go (hunk 4 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: podEvicted is another global variable. So, it works fine.

**Comment by ravisantoshgudimetla** [comment]
@liggit @gmarek PTAL. I have made changes suggested, except for the infinite loop breaking, which I am not clear on.

**Comment by gmarek** [comment]
I'll review this after 1.7

File: pkg/controller/node/nodecontroller_test.go (hunk 2 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: If this needs to be 5 min. there's probably bug in the NC somewhere, which causes ratelimiter tokens to be used somewhere else. We need to understand why this fails instead of hacking around it to make it pass.

Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: So, I chose 5 min randomly, it works fine within a minute on my system but I haven't tried on other systems with less CPU cores and memory.

Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: It should be seconds, but let's keep it with 1 minute and look for flakes.

**Comment by ravisantoshgudimetla** [comment]
@gmarek Changed the time to 1 minute.

@k8s-bot ok to test

File: pkg/controller/node/nodecontroller_test.go [hunk 5]
```diff
@@ -1265,39 +1265,48 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
 
-		if item.expectedEvictPods != podEvicted {
+		if item.expectedEvictPods != *podEvicted {
 			t.Errorf("%v: expected pod eviction: %+v, got %+v", item.description, item.expectedEvictPods, podEvicted)
 		}
 	}
 }
 
+// doEviction does the fake eviction and returns the status of eviction operation.
+func (nc *nodeController) doEviction(fakeNodeHandler *testutil.FakeNodeHandler, podEvicted *bool) {
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: We we can't just return bool?

File: pkg/controller/node/nodecontroller_test.go [hunk 6]
```diff
@@ -1265,39 +1265,48 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
+		nc.zonePodEvictor[zone].Try(func(value TimedValue) (bool, time.Duration) {
+			uid, _ := value.UID.(string)
+			deletePods(fakeNodeHandler, nc.recorder, value.Value, uid, nc.daemonSetStore)
+			return true, 0
+		})
+	}
+
+	for _, action := range fakeNodeHandler.Actions() {
+		if action.GetVerb() == "delete" && action.GetResource().Resource == "pods" {
+			*podEvicted = true
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: you can break here.

File: pkg/controller/node/nodecontroller_test.go (hunk 5 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: In a way, I am doing the same because podEvicted which is pointer is getting passed here and I am updating that var later.

File: pkg/controller/node/nodecontroller_test.go (hunk 6 above)
Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: Ohh you mean a return here. Fair enough. I can do that.

File: pkg/controller/node/nodecontroller_test.go (hunk 5 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: This is not really returning:)

Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: Yup, you are right. I did not want to create another variable, so I am passing the ref around. I am fine with returning a bool as well. I will make that change.

**Comment by ravisantoshgudimetla** [comment]
@gmarek PTAL.

File: pkg/controller/node/nodecontroller_test.go [hunk 7]
```diff
@@ -1265,29 +1265,19 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
-				deletePods(fakeNodeHandler, nodeController.recorder, value.Value, uid, nodeController.daemonSetStore)
-				return true, 0
-			})
-		}
-
-		podEvicted := false
-		for _, action := range fakeNodeHandler.Actions() {
-			if action.GetVerb() == "delete" && action.GetResource().Resource == "pods" {
-				podEvicted = true
+		var podEvicted bool
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: not needed

File: pkg/controller/node/nodecontroller_test.go [hunk 8]
```diff
@@ -1265,29 +1265,19 @@ func TestMonitorNodeStatusEvictPodsWithDisruption(t *testing.T) {
...
+		start := time.Now()
+		// Infinite loop, used for retrying in case ratelimiter fails to reload for Try function.
+		// this breaks when we have the status that we need for test case or when we don't see the
+		// intended result after 1 minute.
+		for {
+			podEvicted = nodeController.doEviction(fakeNodeHandler)
+			if podEvicted == item.expectedEvictPods || time.Since(start) > 1*time.Minute {
```
Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: `if podEvicted := nodeController.doEviction(fakeNodeHandler); podEvicted == item.expectedEvictPods || time.Since(start) > 1*time.Minute {

Comment (ravisantoshgudimetla) [inline pkg/controller/node/nodecontroller_test.go]: So, we need to use podEvicted again in https://github.com/ravisantoshgudimetla/kubernetes/blob/node_controller_flake/pkg/controller/node/nodecontroller_test.go#L1285-L1286. That was the reason, I declared it separately.

Comment (gmarek) [inline pkg/controller/node/nodecontroller_test.go]: Oh, sorry - it got folded so I didn't notice.
