### PR TITLE
fix stateful set pod recreation and event spam

### LINKED ISSUE #122709: RecreatingTerminatedPod/RecreatingFailedPod/SuccessfulDelete events leak
### What happened?

The event `RecreatingTerminatedPod` is emitted ~10 times simultaneously after evicting pods of a Statefulset.

### What did you expect to happen?

The event should only be emitted at most once.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a 1.29 kind cluster:
```
kind create cluster --image kindest/node:v1.29
```
 (tested with `sha256:eaa1450915475849a73a9227b8f201df25e55e268e5d619312131292e324d570`)

- Deploy a statefulset:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
```

- Get the initial `RecreatingTerminatedPod` event count for that sts:
```
kubectl get events  --field-selector involvedObject.kind=StatefulSet,involvedObject.name=web,reason=RecreatingTerminatedPod -o json | jq '.items[].count'
```
(shoud return nothing)

- Taint the node:
```
kubectl taint nodes kind-control-plane foo=bar:NoExecute
```

- Get the event count now:
```
kubectl get events  --field-selector involvedObject.kind=StatefulSet,involvedObject.name=web,reason=RecreatingTerminatedPod -o json | jq '.items[].count'
```
(got: `10`, `11`,`9`...)

### Anything else we need to know?

From the kube-controller logs:

```
2024-01-11T11:26:09.134534094Z I0111 11:26:09.134420       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.135572053Z I0111 11:26:09.135506       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.141711678Z E0111 11:26:09.141587       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.142157720Z I0111 11:26:09.142069       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.143250511Z I0111 11:26:09.143147       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.145130470Z E0111 11:26:09.145043       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.145508511Z I0111 11:26:09.145440       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.146506011Z I0111 11:26:09.146423       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.150412678Z E0111 11:26:09.150314       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.150731261Z I0111 11:26:09.150652       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.151777928Z I0111 11:26:09.151690       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.154159220Z E0111 11:26:09.154073       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.154551136Z I0111 11:26:09.154479       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.155519386Z I0111 11:26:09.155424       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.157276011Z E0111 11:26:09.157186       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.171016053Z I0111 11:26:09.170929       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.172533345Z I0111 11:26:09.172453       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.175124386Z E0111 11:26:09.175049       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.337640386Z I0111 11:26:09.337476       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.339178428Z I0111 11:26:09.339061       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.341355011Z E0111 11:26:09.341228       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.664705011Z I0111 11:26:09.664319       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.668555303Z I0111 11:26:09.668306       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.676319053Z E0111 11:26:09.676042       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.677364720Z I0111 11:26:09.677120       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.679484886Z I0111 11:26:09.679242       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.684279428Z E0111 11:26:09.684135       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.688194220Z I0111 11:26:09.687885       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.690645803Z I0111 11:26:09.690430       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.695824386Z E0111 11:26:09.695522       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.696631386Z I0111 11:26:09.696397       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.698303595Z I0111 11:26:09.698136       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.701026845Z E0111 11:26:09.700893       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: object is being deleted: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.701639136Z I0111 11:26:09.701494       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="RecreatingTerminatedPod" message="StatefulSet default/web is recreating terminated Pod web-0"
2024-01-11T11:26:09.703167928Z I0111 11:26:09.703010       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"
2024-01-11T11:26:09.708887345Z E0111 11:26:09.708730       1 stateful_set.go:430] error syncing StatefulSet default/web, requeuing: pods "web-0" already exists, the server was not able to generate a unique name for the object
2024-01-11T11:26:09.711943720Z I0111 11:26:09.711700       1 event.go:376] "Event occurred" object="default/web" fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="create Pod web-0 in StatefulSet web successful"
```

The deletion of the Pod fails which make the controller enqueue the sts again and ask for another deletion and so on until the Pod is really deleted from the store.

`fieldPath="" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulDelete" message="delete Pod web-0 in StatefulSet web successful"` is confusing as well.

- The same problem occurs with the event `RecreatingFailedPod`, deploy the statefulet:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        command:
        - /bin/sh
        - -c
        - |
          sleep 3;
          exit 1
        ports:
        - containerPort: 80
          name: web
```

When the Pods start `CrashLoopBackOff`, delete them, then ~10 `RecreatingFailedPod` events will be emitted.

- A simple update to the statefulset's spec also triggers a bulk of RecreatingTerminatedPod events.

- the `SuccessfulDelete` event leaks as well.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.0", GitCommit:"3f7a50f38688eb332e2a1b013678c6435d539ae6", GitTreeState:"clean", BuildDate:"2023-12-14T19:20:14Z", GoVersion:"go1.21.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
- do not emit events when pod reaches terminal phase
- do not try to recreate pod until the old pod has been removed from
  etcd storage

#### Which issue(s) this PR fixes:

Fixes #122709

#### Does this PR introduce a user-facing change?

```release-note
Emition of RecreatingFailedPod and RecreatingTerminatedPod events has been removed from stateful set lifecycle.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -367,45 +367,25 @@ func updateStatus(status *apps.StatefulSetStatus, minReadySeconds int32, current
...
 		}
-		replicaOrd := i + getStartOrdinal(set)
-		replicas[i] = newVersionedStatefulSetPod(
-			currentSet,
-			updateSet,
-			currentRevision.Name,
-			updateRevision.Name,
-			replicaOrd)
+		// New pod should be generated on the next sync after the current pod is removed from etcd.
+		return true, nil
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go:388]: We should try not to create the pods until the old one has been removed from etcd. Otherwise the kcm logs are getting spammed with:
 
```
 stateful_set.go:430] error syncing StatefulSet default/nginx-roll, requeuing: object is being deleted: pods "nginx-roll-2" already exists, the server was not able to generate a unique name for the object
```

File: pkg/controller/statefulset/stateful_set_control.go [hunk 2]
```diff
@@ -367,45 +367,25 @@ func updateStatus(status *apps.StatefulSetStatus, minReadySeconds int32, current
...
-	//
+
 	// Note that pods with phase Succeeded will also trigger this event. This is
 	// because final pod phase of evicted or otherwise forcibly stopped pods
 	// (e.g. terminated on node reboot) is determined by the exit code of the
 	// container, not by the reason for pod termination. We should restart the pod
 	// regardless of the exit code.
 	if isFailed(replicas[i]) || isSucceeded(replicas[i]) {
-		if isFailed(replicas[i]) {
-			ssc.recorder.Eventf(set, v1.EventTypeWarning, "RecreatingFailedPod",
```
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go:387]: I suppose we could move the event generation into the `updatePod` handler if we want to be backwards compatible. Thoughts?

File: test/e2e/framework/statefulset/rest.go [hunk 3]
```diff
@@ -248,7 +248,18 @@ func ExecInStatefulPods(ctx context.Context, c clientset.Interface, ss *appsv1.S
...
-	for i := 0; i < 3; i++ {
+	ss, err := c.AppsV1().StatefulSets(ns).Get(ctx, name, metav1.GetOptions{})
+	if err != nil {
+		framework.Failf("failed to get statefulset %q: %v", name, err)
+	}
+	if *(ss.Spec.Replicas) == replicas {
+		return ss
+	}
+	// assume that each replica can potentially generate 3 conflicts when statefulset status is updated
+	// e.g. sudden pod changes between (Running, Ready, Available, Terminating, Deleted)
```
Comment (atiratree) [inline test/e2e/framework/statefulset/rest.go:259]: E2E's were failing without  this fix; https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123809/pull-kubernetes-conformance-kind-ga-only-parallel/1766049762357809152

```
Kubernetes e2e suite: [It] [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Slow] [Conformance] expand_less 	1m56s
{ failed [FAILED] too many retries draining statefulset "ss"
In [It] at: k8s.io/kubernetes/test/e2e/framework/statefulset/rest.go:265 @ 03/08/24 10:57:02.069
}
```

I am not sure if this is suppose to test conflicts? If not, this could be changed to a timeout based update.

File: test/e2e/framework/statefulset/rest.go [hunk 4]
```diff
@@ -248,7 +248,19 @@ func ExecInStatefulPods(ctx context.Context, c clientset.Interface, ss *appsv1.S
...
+	ss, err := c.AppsV1().StatefulSets(ns).Get(ctx, name, metav1.GetOptions{})
+	if err != nil {
+		framework.Failf("failed to get statefulset %q: %v", name, err)
+	}
+	if *(ss.Spec.Replicas) == replicas {
+		return ss
+	}
+	// - try at least 3 times if there is 0 replicas
+	// - assume that each replica can potentially generate 3 conflicts when statefulset status is updated
+	//   e.g. sudden pod changes between (Running, Ready, Available, Terminating, Deleted)
```
Comment (atiratree) [inline test/e2e/framework/statefulset/rest.go:260]: E2E's were failing without  this fix; https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123809/pull-kubernetes-conformance-kind-ga-only-parallel/1766049762357809152

```
Kubernetes e2e suite: [It] [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Slow] [Conformance] expand_less 	1m56s
{ failed [FAILED] too many retries draining statefulset "ss"
In [It] at: k8s.io/kubernetes/test/e2e/framework/statefulset/rest.go:265 @ 03/08/24 10:57:02.069
}
```

I am not sure if this is suppose to test conflicts? If not, this could be changed to a timeout based update.

File: test/e2e/framework/statefulset/rest.go [hunk 5]
```diff
@@ -248,7 +248,19 @@ func ExecInStatefulPods(ctx context.Context, c clientset.Interface, ss *appsv1.S
...
+	ss, err := c.AppsV1().StatefulSets(ns).Get(ctx, name, metav1.GetOptions{})
+	if err != nil {
+		framework.Failf("failed to get statefulset %q: %v", name, err)
+	}
+	if *(ss.Spec.Replicas) == replicas {
+		return ss
+	}
+	// - try at least 3 times if there are 0 replicas
+	// - assume that each replica can potentially generate 3 conflicts when statefulset status is updated
+	//   e.g. sudden pod changes between (Running, Ready, Available, Terminating, Deleted)
```
Comment (atiratree) [inline test/e2e/framework/statefulset/rest.go:260]: E2E's were failing without  this fix; https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123809/pull-kubernetes-conformance-kind-ga-only-parallel/1766049762357809152

```
Kubernetes e2e suite: [It] [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Scaling should happen in predictable order and halt if any stateful pod is unhealthy [Slow] [Conformance] expand_less 	1m56s
{ failed [FAILED] too many retries draining statefulset "ss"
In [It] at: k8s.io/kubernetes/test/e2e/framework/statefulset/rest.go:265 @ 03/08/24 10:57:02.069
}
```

I am not sure if this is suppose to test conflicts? If not, this could be changed to a timeout based update.

File: pkg/controller/statefulset/stateful_set.go [hunk 6]
```diff
@@ -235,6 +235,9 @@ func (ssc *StatefulSetController) updatePod(logger klog.Logger, old, cur interfa
 			return
 		}
 		logger.V(4).Info("Pod objectMeta updated", "pod", klog.KObj(curPod), "oldObjectMeta", oldPod.ObjectMeta, "newObjectMeta", curPod.ObjectMeta)
+		if oldPod.Status.Phase != curPod.Status.Phase && podutil.IsPodPhaseTerminal(curPod.Status.Phase) {
+			logger.V(4).Info("StatefulSet Pod reached terminal phase", "pod", klog.KObj(curPod), "statefulSet", klog.KObj(set), "podPhase", curPod.Status.Phase)
```
[the remark this answers is not in the document]
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set.go:238]: Nit, why not just add that pod phase to the above line?

File: pkg/controller/statefulset/stateful_set_control.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go:387]: Move or change here to logging seems acceptable.

File: test/e2e/framework/statefulset/rest.go (hunk 5 above)
Comment (soltysh) [reply test/e2e/framework/statefulset/rest.go:260]: To me this looks like helper written before the backoff was introduced. How about re-writing this with `wiat.ExponentialBackoff` with initial duration 2s, factor 1.5 and 2 steps. wdyt?

**Review by soltysh — COMMENTED** [review]
Some minor nits, but overall this looks reasonable.

File: test/e2e/framework/statefulset/rest.go (hunk 5 above)
Comment (atiratree) [reply test/e2e/framework/statefulset/rest.go]: +1, `RetryOnConflict` might be even better for this.  Also I based the backoff on `DefaultRetry` and increased the number of steps a bit

File: pkg/controller/statefulset/stateful_set.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set.go]: yes, that might be even better for debugging

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label tide/merge-method-squash

**Comment by atiratree** [comment]
unrelated
/test pull-kubernetes-e2e-gce

File: pkg/controller/statefulset/stateful_set_control.go [hunk 7]
```diff
@@ -367,45 +364,25 @@ func updateStatus(status *apps.StatefulSetStatus, minReadySeconds int32, current
...
-				set.Namespace,
-				set.Name,
-				replicas[i].Name)
-		}
-		if err := ssc.podControl.DeleteStatefulPod(set, replicas[i]); err != nil {
-			return true, err
+		if replicas[i].DeletionTimestamp == nil {
+			if err := ssc.podControl.DeleteStatefulPod(set, replicas[i]); err != nil {
+				return true, err
+			}
```
Comment (aojea) [inline pkg/controller/statefulset/stateful_set_control.go:382]: @soltysh @atiratree this seem an important change in behavior to backport, we regressed last time we did something similar in this controller https://github.com/kubernetes/kubernetes/pull/121389 , is not safer to backport only the spam logs changes?

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 8]
```diff
@@ -551,52 +623,6 @@ func UpdateSetStatusFailure(t *testing.T, set *apps.StatefulSet, invariants inva
 	}
 }
 
-func PodRecreateDeleteFailure(t *testing.T, set *apps.StatefulSet, invariants invariantFunc) {
```
Comment (aojea) [inline pkg/controller/statefulset/stateful_set_control_test.go:554]: why do we remove this test? is no longer valid?

File: pkg/controller/statefulset/stateful_set_control.go (hunk 7 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go:382]: @aojea please take a look at https://github.com/kubernetes/kubernetes/pull/123809#discussion_r1516888929. This was also causing a spam, but in the KCM logs.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 8 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control_test.go:554]: This test was not removed. There was a code duplication and it was also split into two flavors, please see
- RecreatesFailedPodWithDeleteFailure
- RecreatesSucceededPodWithDeleteFailure

**Comment by azat** [comment]
Just for further readers, and google searches, apparently that this also fixes possible issue with stale readyReplicas after pod that is managed by statefulset removed
