### PR TITLE
kubelet: assign Node as an owner for the ResourceSlice

### LINKED ISSUE #123691: DRA: kubelet: avoid API permission error log entries
### What would you like to be added?

When kubelet starts and begins watching NodeResourceSlice objects with an informer, it initially logs errors like:
```
 E0226 13:41:19.880621  126334 reflector.go:150] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:232: Failed to watch *v1alpha2.NodeResourceSlice: failed to list *v1alpha2.NodeResourceSlice: noderesourceslices.resource.k8s.io is forbidden: User "system:anonymous" cannot list resource "noderesourceslices" in API group "resource.k8s.io" at the cluster scope
 ```
 
 This seems to be caused by the informer being started at a time when the kubelet REST client doesn't have the final credentials yet. The errors are harmless and can be ignored because eventually the List call succeeds.

Ideas for solving this:
- change when the registration handler is called or
- wait in the `pkg/kubelet/cm/dra/plugin/noderesources.go` code until List succeeds without logging errors, then start the informer
 

### Why is this needed?

Error logs are confusing.

/sig node
/triage accepted
/priority important-longterm
/lifecycle frozen
/assign

### LINKED ISSUE #123692: DRA: kubelet: create ResourceSlice with Node as owner
### What would you like to be added?

`pkg/kubelet/cm/dra/plugin/noderesources.go` currently creates NodeResourceSlice objects without an owner. It should set an ownerref for the Node.

### Why is this needed?

When kubelet dies and the node is removed, the NodeResourceSlice objects remain.

/sig node
/triage accepted
/priority important-longterm
/lifecycle frozen
/assign

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup
/kind bug

#### What this PR does / why we need it:

It sets a kubelet node as an owner for the ResourceSlice. This ensures that NodeSlice objects will be garbage collected if node object is removed.

#### Which issue(s) this PR fixes:

Fixes #123692
Fixes #123691

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/dra/dra.go [hunk 1]
```diff
@@ -907,8 +907,15 @@ var _ = framework.SIGDescribe("node")("DRA", feature.DynamicResourceAllocation,
...
 						gstruct.MatchAllFields(gstruct.Fields{
-							"TypeMeta":   gstruct.Ignore(),
-							"ObjectMeta": gstruct.Ignore(), // TODO (https://github.com/kubernetes/kubernetes/issues/123692): validate ownerref
+							"TypeMeta": gstruct.Ignore(),
+							"ObjectMeta": gstruct.MatchFields(gstruct.IgnoreExtras, gstruct.Fields{
+								"OwnerReferences": gstruct.MatchElements(func(element interface{}) string { return element.(metav1.OwnerReference).Kind }, gstruct.IgnoreExtras, gstruct.Elements{
+									"OwnerReference": gstruct.MatchFields(gstruct.IgnoreExtras, gstruct.Fields{
+										"kind": gomega.Equal("Node"),
+										"name": gomega.Equal(nodeName),
+									}),
```
Comment (bart0sh) [inline test/e2e/dra/dra.go:916]: @pohly I failed to figure out how to correctly do this. Can you help?
Is it possible to check that the length of the `OwnerReferences` are always 1 using gstruct API?

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 2]
```diff
@@ -259,9 +260,20 @@ func (c *nodeResourcesController) run(ctx context.Context) {
...
+	var node *v1.Node
+	var err error
+	for {
+		node, err = c.getNode()
+		if err == nil {
+			break
+		}
+		logger.V(5).Error(err, "getting Node object failed, waiting")
+		time.Sleep(time.Second)
+	}
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:272]: @pohly This might also fix https://github.com/kubernetes/kubernetes/issues/123692
At least I don't see `resourceslices.resource.k8s.io is forbidden` in the kubelet logs in my environment.

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 3]
```diff
@@ -259,9 +260,20 @@ func (c *nodeResourcesController) run(ctx context.Context) {
 	// because eventually these list calls succeed.
 	// TODO (https://github.com/kubernetes/kubernetes/issues/123691): can we avoid these error log entries? Perhaps wait here?
 
+	var node *v1.Node
+	var err error
+	for {
+		node, err = c.getNode()
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:266]: Could it be that this node changes later? I don't know, therefore I am wary of making the assumption that it doesn't.

Perhaps better call this whenever an object needs to be updated or created? It's reading from a local cache, so it's not that expensive.

I don't think we need to re-sync when the node object changes. The only way how this can cause the UID to change is when the old node object gets removed. Unless users work really hard to breaks us, all old slices will get removed, which triggers syncing.

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 3 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/plugin/noderesources.go:266]: Thank you for the review and suggestions!

I agree that node name or UID are unlikely to change. However, `getNode` will always get the latest available node object version from the cache. At least I hope it will. Alternatively we can just store node name and UID in the `nodeResourcesController struct`. What would you suggest?

File: test/e2e/dra/dra.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e/dra/dra.go:922]: Thank you! applied.

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 3 above)
Comment (pohly) [reply pkg/kubelet/cm/dra/plugin/noderesources.go:260]: I suggest to call `getNode` anew in `sync`

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 4]
```diff
@@ -441,13 +451,27 @@ func (c *nodeResourcesController) sync(ctx context.Context, driverName string) e
 			continue
 		}
 
+		node, err := c.getNode()
+		if err != nil {
+			logger.Error(err, "Creating node resource slice failed")
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:456]: Please don't log errors when they are returned to the caller. The caller decides whether and how errors need to be logged.

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 5]
```diff
@@ -441,13 +451,27 @@ func (c *nodeResourcesController) sync(ctx context.Context, driverName string) e
...
+			return fmt.Errorf("create node resource slice: %w", err)
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:457]: This doesn't describe the error and could lead to a very misleading composed error, depending on what the `err` text is.

```suggestion
			return fmt.Errorf("retrieve node object: %w", err)
```

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 3 above)
Comment (pohly) [reply pkg/kubelet/cm/dra/plugin/noderesources.go:260]: I missed that because this code here remained.

Can you simplify it (no need for separate variables, no need for `node`) and add a comment why we have this loop here?

**Review by pohly — CHANGES_REQUESTED** [review]

**Comment by bart0sh** [comment]
> Can you simplify it (no need for separate variables, no need for node) and add a comment why we have this loop here?

We're using node object a bit below these lines, so we need it:
```
	// We could use an indexer on driver name, but that seems overkill.
	informer := resourceinformers.NewFilteredResourceSliceInformer(c.kubeClient, resyncPeriod, nil, func(options *metav1.ListOptions) {
		options.FieldSelector = "nodeName=" + node.Name
	})
```

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 4 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/plugin/noderesources.go]: done, thanks for pointing out

**Comment by bart0sh** [comment]
@pohly 
> and add a comment why we have this loop here

done, thanks.

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 3 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/plugin/noderesources.go:265]: ok, will do. Thanks for the explanations :)

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 6]
```diff
@@ -252,16 +254,29 @@ func (c *nodeResourcesController) run(ctx context.Context) {
 	// For now syncing starts immediately, with no DeleteCollection. This
 	// can be reconsidered later.
 
-	// While kubelet starts up, there are errors:
-	//      E0226 13:41:19.880621  126334 reflector.go:150] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:232: Failed to watch *v1alpha2.ResourceSlice: failed to list *v1alpha2.ResourceSlice: resourceslices.resource.k8s.io is forbidden: User "system:anonymous" cannot list resource "resourceslices" in API group "resource.k8s.io" at the cluster scope
-	//
-	// The credentials used by kubeClient seem to get swapped out later,
-	// because eventually these list calls succeed.
-	// TODO (https://github.com/kubernetes/kubernetes/issues/123691): can we avoid these error log entries? Perhaps wait here?
+	// Wait until we're able to get a Node object
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:257]:
```suggestion
	// Wait until we're able to get a Node object.
```

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 7]
```diff
@@ -252,16 +254,29 @@ func (c *nodeResourcesController) run(ctx context.Context) {
...
+	// This means that the object is created on the API server,
+	// the kubeclient is functional and the node informer cache is populated with the node object
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:259]:
```suggestion
	// the kubeclient is functional and the node informer cache is populated with the node object.
```

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 8]
```diff
@@ -441,13 +456,26 @@ func (c *nodeResourcesController) sync(ctx context.Context, driverName string) e
 			continue
 		}
 
+		node, err := c.getNode()
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:459]: Please add a comment about why we get the node anew each time, otherwise someone might get the idea later that this should be optimized.

**Review by pohly — COMMENTED** [review]
Code looks good, some comments about (no pun intended) comments.

File: pkg/kubelet/cm/dra/plugin/noderesources.go (hunk 8 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/plugin/noderesources.go:462]: Than you for the review. Added.

File: pkg/kubelet/cm/dra/plugin/noderesources.go [hunk 9]
```diff
@@ -252,16 +254,29 @@ func (c *nodeResourcesController) run(ctx context.Context) {
...
+	// Without this it doesn't make sense to proceed further as we need a node name and
+	// a node UID for this controller to work.
+	var node *v1.Node
+	var err error
+	for {
+		node, err = c.getNode()
+		if err == nil {
+			break
+		}
+		logger.V(5).Error(err, "getting Node object failed, waiting")
```
Comment (pohly) [inline pkg/kubelet/cm/dra/plugin/noderesources.go:269]: Just noticed one more thing. There is no `V(5).Error`, is is the same as `Error`.

```suggestion
		logger.V(5).Info("getting Node object failed, waiting", "err", err)
```

**Review by pohly — APPROVED** [review]
/lgtm

/assign @klueska 
For approval.

/cc @kubernetes/release-team 
This fixes a shortcoming in a feature added for 1.30.

**Review by klueska — APPROVED** [review]
/lgtm
/approve

/cc @kubernetes/release-team
For inclusion in the milestone
