### PR TITLE
Remove nodes from cache immediately on delete events

### LINKED ISSUE #86920: [Scheduler] Node snapshot data structures sometimes go out of sync
/sig scheduling

**What happened**:

#86919 is removing a check for snapshot's NodeInfoMap and NodeInfoList go out of sync. According to code comments this is expected when node removal events arrive before their corresponding node removal events.

https://github.com/kubernetes/kubernetes/blob/11a31590e432ba9c723b951e1691d5a97c09dba7/pkg/scheduler/internal/cache/cache.go#L631-L634

**What you expected to happen**:

Given that the plugins should only use NodeInfoList as source of truth for the existing nodes, there should be no need to keep a node in NodeInfoMap until all of its pods are removed.

However, before doing the changes, we should ensure that no code is relying on NodeInfoMap as source of truth. We could consider unexporting NodeInfoMap to avoid any iteration on its keys.

**How to reproduce it (as minimally and precisely as possible)**:

The issue is triggered by quickly downscaling a cluster, even doing it forcefully by stopping a set of nodes without draining.

**Environment**:
- Kubernetes version: 1.18 (head)

/cc @ahg-g

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove nodes from cache's structs when getting a Remove event. Previously, we keep them in some caches until all remove pod events arrive.
This is unnecessary and it causes structs to be become out-of-sync.

We still keep pods in other intermediate caches until their delete events arrive. This is to avoid the complexity of having to handle removed elements when we receive the delete, forget or expires events (the last 2 are internal events to the scheduler, not from k8s). This is fine for the purposes of scheduling, as plugins and the generic scheduler implementation is only expected to use the node and pod listers, which use the list of nodes as source of truth.

/sig scheduling

**Which issue(s) this PR fixes**:

Fixes #86920

**Special notes for your reviewer**:

This builds on top of #86930, only review from 2nd commit.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -437,19 +437,17 @@ func (cache *schedulerCache) updatePod(oldPod, newPod *v1.Pod) error {
...
+		return nil
 	}
 	if err := n.info.RemovePod(pod); err != nil {
 		return err
 	}
-	if len(n.info.Pods()) == 0 && n.info.Node() == nil {
-		cache.removeNodeInfoFromList(pod.Spec.NodeName)
-	} else {
-		cache.moveNodeInfoToHead(pod.Spec.NodeName)
-	}
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go]: Shouldn't we move the node to the head to the snapshot list? It's a pod deletion, not node deletion.

File: pkg/scheduler/nodeinfo/snapshot/snapshot.go [hunk 2]
```diff
@@ -189,7 +189,7 @@ func (n *nodeInfoLister) HavePodsWithAffinityList() ([]*schedulernodeinfo.NodeIn
 
 // Returns the NodeInfo of the given node name.
 func (n *nodeInfoLister) Get(nodeName string) (*schedulernodeinfo.NodeInfo, error) {
-	if v, ok := n.snapshot.NodeInfoMap[nodeName]; ok && v.Node() != nil {
+	if v, ok := n.snapshot.NodeInfoMap[nodeName]; ok {
```
Comment (alculquicondor) [inline pkg/scheduler/nodeinfo/snapshot/snapshot.go]: Uhm... actually I should keep this, as an AddPod could arrive its corresponding AddNode.

**Comment by alculquicondor** [comment]
Done.

**Comment by ahg-g** [comment]
/approve

leaving it to @Huang-Wei to lgtm
