### PR TITLE
Fix log dump for new gcloud

### LINKED ISSUE #24120: kubernetes/cluster/log-dump.sh appears to be broken on G{C,K}E
The end of passing GKE runs shows stuff like
```
Dumping master and node logs to /var/lib/jenkins/jobs/kubernetes-e2e-gke/workspace/_artifacts
Master SSH not supported for gke
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/k8s-jkns-e2e-gke-ci/zones/us-central1-f/instances/https' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/k8s-jkns-e2e-gke-ci/zones/us-central1-f/instances/https' was not found
ERROR: (gcloud.compute.copy-files) Could not fetch instance:
 - The resource 'projects/k8s-jkns-e2e-gke-ci/zones/us-central1-f/instances/https' was not found
```

and there are no node logs being saved. It appears to be working on clusters that failed to fully start up, though.

@spxtr @fejta

### PR DESCRIPTION
**Pull request by j3ffml**
`gcloud compute instance-groups managed list-instances` at CI has self-link for instance instead of just name. Fixes #24120

### CODE REVIEW

File: cluster/gke/util.sh [hunk 1]
```diff
@@ -231,6 +231,9 @@ function detect-node-names {
     "${NODE_INSTANCE_GROUP}" --zone "${ZONE}" --project "${PROJECT}" \
     --format=yaml | grep instance: | cut -d ' ' -f 2))
 
+  # Strip path if return value is selflink
+  NODE_NAMES=($(for i in ${NODE_NAMES[@]}; do basename "@$i"; done))
```
Comment (ixdy) [inline cluster/gke/util.sh]: what is the @ in `@$i` for?

Comment (jlowdermilk) [inline cluster/gke/util.sh]: Cargo culting. I thought I needed it to get elements, looks like I don't.
