### PR TITLE
Fix DRA flaky test for ResourceClaim device status

### LINKED ISSUE #130096: DRAResourceClaimDeviceStatus: E2E test flake
### What happened?

Sometimes, `on single node must be possible for the driver to update the ResourceClaim.Status.Devices once allocated [Feature:DRAResourceClaimDeviceStatus]` fails in ci-kind-dra-all with a panic:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kind-dra-all/1889141320082001920

```
STEP: Setting the device status a first time - k8s.io/kubernetes/test/e2e/dra/dra.go:435 @ 02/11/25 03:00:14.898
[PANICKED] Test Panicked
In [It] at: runtime/panic.go:262 @ 02/11/25 03:00:14.898

runtime error: invalid memory address or nil pointer dereference

Full Stack Trace
  k8s.io/kubernetes/test/e2e/dra/test-driver/app.(*ExamplePlugin).UpdateStatus(0x476f900?, {0x7faf200beaa8, 0xc000dc7ce0}, 0xc006d7cd00)
  	k8s.io/kubernetes/test/e2e/dra/test-driver/app/kubeletplugin.go:587 +0x2a
  k8s.io/kubernetes/test/e2e/dra.init.func1.2.11({0x7faf200beaa8, 0xc000dc7ce0})
  	k8s.io/kubernetes/test/e2e/dra/dra.go:450 +0x8a8
```

/sig network
/wg device-management
/cc @LionelJouin @aojea 

### What did you expect to happen?

No panic.

### How can we reproduce it (as minimally and precisely as possible)?

Run test repeatedly?

### Anything else we need to know?

Somehow this does not get picked up by https://storage.googleapis.com/k8s-triage, perhaps because of the empty failure message.

### Kubernetes version

master

### Cloud provider

n/a

### OS version

_No response_

### Install tools

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by LionelJouin**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

The previous Eventually loop was not properly checking if the pod was scheduled and running. Thus, the node name could not be retrieved from the pod specs. The plugin could not be retrieved and the UpdateStatus was called on a nil object.
TestPod function is now used instead, so the test waits for the pod to be scheduled. The Eventually loop to get the pod and resourceClaim is then no longer needed.

#### Which issue(s) this PR fixes:

Fixes #130096

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @pohly 

is more familiar with this suite

File: test/e2e/dra/dra.go [hunk 1]
```diff
@@ -411,27 +411,18 @@ var _ = framework.SIGDescribe("node")("DRA", feature.DynamicResourceAllocation,
...
-			}).WithTimeout(f.Timeouts.PodDelete).ShouldNot(gomega.HaveField("Status.Allocation", (*resourceapi.AllocationResult)(nil)))
-
-			gomega.Eventually(ctx, func(ctx context.Context) error {
-				var err error
-				scheduledPod, err = b.f.ClientSet.CoreV1().Pods(pod.Namespace).Get(ctx, pod.Name, metav1.GetOptions{})
-				if err != nil && scheduledPod.Spec.NodeName != "" {
-					return fmt.Errorf("expected the test pod %s to exist and to be scheduled on a node: %w", pod.Name, err)
-				}
-				return nil
-			}).WithTimeout(f.Timeouts.PodDelete).Should(gomega.BeNil())
```
Comment (pohly) [inline test/e2e/dra/dra.go:430]: Why did this not ensure that `scheduledPod.Spec.NodeName != ""` when the `gomega.Eventually` succeeded?

Ah, now I see it: if `err != nil`, it exits with nil.

This could be fixed, but using the existing helper is simpler.

/lgtm
/approve
