### PR TITLE
Bugfix: csi plugin supporting raw block that does not need attach mounted failed

### LINKED ISSUE #79884: csi plugin supporting raw block  failed
**What happened**:

During I develop a driver that supports raw block devices but do not need to be attached to nodes, I found it would fail when a pod mount a raw block device.

PS: I use cluster-driver register and make requiredAttach as false.

kubectl get csidriver csi-xxx -o yaml
```
apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  creationTimestamp: "2019-06-27T07:20:22Z"
  name: csi-xxx
  resourceVersion: "5029920"
  selfLink: /apis/storage.k8s.io/v1beta1/csidrivers/csi-lvmplugin
  uid: b31c24ea-9872-40ed-b917-0b8d6d1124e5
spec:
  attachRequired: false
  podInfoOnMount: false
```
image

**What you expected to happen**:

Mount a raw block device successfully.

**How to reproduce it (as minimally and precisely as possible)**:

1. a driver that supports raw block devices but do not need to be attached to nodes, I found it would fail when a pod mount a raw block device.
2. use cluster-driver register and make requiredAttach as false.
3. create a pod with raw block devices

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: BaiduCloud
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

csi plugin supporting raw block that does not need attach mounted failed.
reason: for block device, csi_block.go always gets an attachment no matter if it supports attachment.

**Which issue(s) this PR fixes**:

Fixes #79884

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Bugfix: csi plugin supporting raw block that does not need attach mounted failed
```

### CODE REVIEW

**Comment by jsafrane** [comment]
`make verify` is not happy about your change:

```
Invalid invocations of featuregatetesting.SetFeatureGateDuringTest():
./pkg/volume/csi/csi_block_test.go:360:	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.CSIDriverRegistry, true)

Always make a deferred call to the returned function to ensure the feature gate is reset:   
defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.<FeatureName>, <value>)()
--
```

Can you also please enhance our e2e test for VolumeAttachment with block volumes? We have some for filesystem based PVs: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_mock_volume.go#L233

cc @vladimirvivien @msau42

**Comment by cwdsuzhou** [comment]
> `make verify` is not happy about your change:
> 
> ```
> Invalid invocations of featuregatetesting.SetFeatureGateDuringTest():
> ./pkg/volume/csi/csi_block_test.go:360:	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.CSIDriverRegistry, true)
> 
> Always make a deferred call to the returned function to ensure the feature gate is reset:   
> defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.<FeatureName>, <value>)()
> --
> ```
> 
> Can you also please enhance our e2e test for VolumeAttachment with block volumes? We have some for filesystem based PVs: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_mock_volume.go#L233
> 
> cc @vladimirvivien @msau42

I would fix it, thanks

**Comment by cwdsuzhou** [comment]
> Can you also please enhance our e2e test for VolumeAttachment with block volumes? We have some for filesystem based PVs: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_mock_volume.go#L233

I would like to enhance e2e test for VolumeAttachment with block volumes in another PR.
@jsafrane wdyt?

File: pkg/volume/csi/csi_block.go [hunk 1]
```diff
@@ -223,18 +227,23 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
-	nodeName := string(m.plugin.host.GetNodeName())
-	attachID := getAttachmentName(csiSource.VolumeHandle, csiSource.Driver, nodeName)
-	attachment, err := m.k8s.StorageV1().VolumeAttachments().Get(attachID, meta.GetOptions{})
+	driverName := csiSource.Driver
+	skip, err := m.plugin.skipAttach(driverName)
 	if err != nil {
-		klog.Error(log("blockMapper.SetupDevice failed to get volume attachment [id=%v]: %v", attachID, err))
-		return "", err
+		skip = false
+		klog.Error(log("Failed to check CSIDriver for %s: %s", driverName, err))
```
Comment (jsafrane) [inline pkg/volume/csi/csi_block.go]: IMO, `return err` would be more useful here. Kubelet should not assume that the volume is attachable.

Comment (cwdsuzhou) [reply pkg/volume/csi/csi_block.go]: thanks, done

**Comment by cwdsuzhou** [comment]
@jsafrane I have cherry picked the PR to k8s 1.15 1.14 and 1.13, PTAL, thanks

**Comment by neolit123** [comment]
@cwdsuzhou 
> I have cherry picked the PR to k8s 1.15 1.14 and 1.13, PTAL, thanks

the criteria for cherry picks in k8s should be "critical bug fixes only".
does this bugfix qualify?

**Comment by cwdsuzhou** [comment]
@neolit123 I think it qualifies.Without this PR CSI plugins support raw block but do not need attachment can not mount block devices successfully. However I we have claimed we support CSI raw block mode.
