### PR TITLE
DRA: scheduler reallocation flake

### LINKED ISSUE #120429: DRA: reallocation flake - failure cluster [b23e7435...]
##### Error text:
```
[FAILED] number of deallocations
Expected
    <int64>: 2
to equal
    <int64>: 1
In [It] at: test/e2e/dra/dra.go:650 @ 08/22/23 03:04:45.666

```
#### Recent failures:
[9/4/2023, 5:05:18 AM ci-kind-dra](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kind-dra/1698532055685533696)
[9/1/2023, 11:05:25 PM ci-kind-dra](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kind-dra/1697716169416380416)
[8/30/2023, 11:00:09 PM ci-kind-dra](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kind-dra/1696990601829945344)
[8/30/2023, 10:59:06 AM ci-kind-dra](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kind-dra/1696809154405994496)
[8/30/2023, 4:58:04 AM ci-kind-dra](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kind-dra/1696718304887967744)

/kind failing-test
/kind flake
/sig node
/assign

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

This fixes a test flake:
    
        [sig-node] DRA [Feature:DynamicResourceAllocation] multiple nodes reallocation [It] works
        /nvme/gopath/src/k8s.io/kubernetes/test/e2e/dra/dra.go:552
    
          [FAILED] number of deallocations
          Expected
              <int64>: 2
          to equal
              <int64>: 1
          In [It] at: /nvme/gopath/src/k8s.io/kubernetes/test/e2e/dra/dra.go:651 @ 09/05/23 14:01:54.652
    
 Log output showed that the sequence of events leading to this was:

- claim gets allocated because of selected node
- a different node has to be used, so PostFilter sets
  claim.status.deallocationRequested
- the driver deallocates
- before the scheduler can react and select a different node,
  the driver allocates *again* for the original node
- the scheduler asks for deallocation again
- the driver deallocates again (causing the test failure)
- eventually the pod runs
    
The fix is to disable allocations first by removing the selected node and then starting to deallocate.

#### Special notes for your reviewer:

Fixes: https://github.com/kubernetes/kubernetes/issues/120429

This can be reproduced locally with
    
        stress -p 10 go test ./test/e2e -args -ginkgo.focus=DynamicResourceAllocation.*reallocation.works  -ginkgo.no-color -v=4 -ginkgo.v

Because it works eventually, this doesn't need to be fixed in 1.28.

Depends on https://github.com/kubernetes/kubernetes/pull/120253, only the last commit is new.

#### Does this PR introduce a user-facing change?
```release-note
DRA: when the scheduler has to deallocate a claim after a node became unsuitable for a pod, it might have needed more attempts than really necessary.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3063
```

### CODE REVIEW

**Comment by pohly** [comment]
@sanposhiho: can you perhaps take this one?

/assign @sanposhiho

**Comment by pohly** [comment]
/priority important-soon

This fixes an annoying test flake.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 1]
```diff
@@ -760,8 +761,25 @@ func (pl *dynamicResources) PostFilter(ctx context.Context, cs *framework.CycleS
 	// pick one claim randomly because there is no better heuristic.
 	for index := range state.unavailableClaims {
 		claim := state.claims[index]
+		if claim.Status.DeallocationRequested {
+			// Don't ask again, just wait.
+			break
+		}
```
Comment (sanposhiho) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:767]: Shouldn't this be in `if len(claim.Status.ReservedFor) == 0 || len(claim.Status.ReservedFor) == 1 && claim.Status.ReservedFor[0].UID == pod.UID {}` ?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:767]: No: if any claim is currently in the process of being deallocated, then the intend is to wait for that work to finish before deciding what to do next. Perhaps deallocating that one claim is enough to pick a node. If not, then the first attempt after completion will pick another claim.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:767]: Your question got me thinking: it would be better to check *all* claims for `DeallocationRequested`. If the first claim is not deallocating and the second is, then the current check in the loop will trigger deallocation of the first claim.

/hold

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:767]: We can forget about all of this: if there is *any* claim for which deallocation is pending, PreFilter will mark the pod as unschedulable:
https://github.com/kubernetes/kubernetes/blob/33c5bd631d990f907f89f66cdf8088d252ab251b/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L592-L595

This extra check here is unnecessary. I removed it.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:767]: /hold cancel

**Comment by pohly** [comment]
```
ERROR: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:45:2: SA1019: "k8s.io/utils/pointer" is deprecated: Use functions in k8s.io/utils/ptr instead: ptr.To to obtain a pointer, ptr.Deref to dereference a pointer, ptr.Equal to compare dereferenced pointers. (staticcheck)
ERROR: 	"k8s.io/utils/pointer"
ERROR: 	^
```

Let's ignore that for now. I want this to get merged soon, and using `k8s.io/utils/ptr` would imply changing vendor and thus a dependency review, i.e. more reviewers/approvers needed. I'll do a separate PR for that.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Right, that makes sense.

**Comment by pohly** [comment]
Then I can rebase and use it... done.

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

Thanks!
