### PR TITLE
Don't start any Typha instances if not using Calico

### LINKED ISSUE #47622: Some GKE tests are failing because of calico-typha pod being unschedulable
Example: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-alpha-features/13492

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:216
Jun 15 13:35:54.975: Error waiting for all pods to be running and ready: 1 / 17 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                           NODE PHASE   GRACE CONDITIONS
calico-typha-3071995635-ww7ps      Pending       [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2017-06-15 13:23:55 -0700 PDT Unschedulable No nodes are available that match all of the following predicates:: MatchNodeSelector (3).}]

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:167
```

cc - @dnardo @caseydavenport

Maybe related to #47188 

/sig network
/area platform/gke
/kind bug
/priority failing-test

### PR DESCRIPTION
**Pull request by caseydavenport**
**What this PR does / why we need it**:

Don't start any Typha instances if Calico isn't being used.  A recent change now includes all add-ons on the master, but we don't always want a Typha replica.

**Which issue this PR fixes**

Fixes https://github.com/kubernetes/kubernetes/issues/47622

**Release note**:
```release-note
NONE
```

cc @dnardo

### CODE REVIEW

File: cluster/gce/container-linux/configure-helper.sh [hunk 1]
```diff
@@ -66,6 +66,10 @@ function get-calico-typha-replicas {
   if [[ "${NUM_NODES}" -gt "500" ]]; then
     typha_count=5
   fi
+  if [[ "${NETWORK_POLICY_PROVIDER:-}" != "calico" ]] then
```
Comment (mindprince) [inline cluster/gce/container-linux/configure-helper.sh]: missing semicolon after `]]`.

**Review by rohitagarwal003 — CHANGES_REQUESTED** [review]

File: cluster/gce/container-linux/configure-helper.sh (hunk 1 above)
Comment (caseydavenport) [inline cluster/gce/container-linux/configure-helper.sh]: Good spot- fixed.

**Review by rohitagarwal003 — APPROVED** [review]

**Comment by mindprince** [comment]
@dchen1107 @vishh @dnardo Please approve this and apply the milestone so that this gets merged.
