### PR TITLE
fix ingress path for tests when ingress controller is already running

### LINKED ISSUE #107752: e2e test for creating Ingress API operations fails when ingress controller is already in place
### What happened?

We run sonobuoy tests on production running clusters whenever we upgrade our clusters.  We observe that `should support creating Ingress API operations` fails when we already have nginx-ingress controller running in the cluster.

The newer versions of nginx-ingress controller comes up with a validating admission webhook that validates the ingress definitions. In this specific test, we are creating 3 ingress objects with the same path and the webhook do not permit to create them (the first one is created but the other two would fail) and then the job fails.

### What did you expect to happen?

The tests shouldn't fail and it requires we create ingress objects using different paths instead.

### How can we reproduce it (as minimally and precisely as possible)?

-  Install nginx-ingress controller from [here](https://kubernetes.github.io/ingress-nginx/deploy/)
-  Run e2e test. 
Test fails.

### Anything else we need to know?

_No response_

### Kubernetes version

>=1.19

### Cloud provider

n/a

### OS version

n/a

### Install tools

n/a

### Container runtime (CRI) and and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

### PR DESCRIPTION
**Pull request by srikiz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The PR will make sure we create a random path for multiple ingress objects that's created as part of this template.

#### Which issue(s) this PR fixes:

Fixes #107752

#### Does this PR introduce a user-facing change?

```release-note: NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/network/ingress.go [hunk 1]
```diff
@@ -634,7 +635,7 @@ var _ = common.SIGDescribe("Ingress API", func() {
 						IngressRuleValue: networkingv1.IngressRuleValue{
 							HTTP: &networkingv1.HTTPIngressRuleValue{
 								Paths: []networkingv1.HTTPIngressPath{{
-									Path:     "/",
+									Path:     "/testpath/" + fmt.Sprintf("%08x", rand.Int31()),
```
Comment (aojea) [inline test/e2e/network/ingress.go:638]: this will be the same path too
```
		// Ingress resource create/read/update/watch verbs
		ginkgo.By("creating")
		_, err := ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
		framework.ExpectNoError(err)
		_, err = ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
		framework.ExpectNoError(err)
		createdIngress, err := ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
		framework.ExpectNoError(err)
```

Comment (aojea) [reply test/e2e/network/ingress.go:638]: don't use the random generator, just generate 3 new ingress objects from the template with different host/path and use them in the Create calls, something like

```
                ingress1 = ingTemplate.DeepCopy()
                ingress1.Spec.Rules[0].Host = "host1.bar.com"
                ingress2 = ingTemplate.DeepCopy()
                ingress2.Spec.Rules[0].Host = "host2.bar.com"
                ingress3 = ingTemplate.DeepCopy()
                ingress3.Spec.Rules[0].Host = "host1.bar.com"
		// Ingress resource create/read/update/watch verbs
		ginkgo.By("creating")
		_, err := ingClient.Create(context.TODO(), ingress1. metav1.CreateOptions{})
		framework.ExpectNoError(err)
		_, err = ingClient.Create(context.TODO(), ingress2, metav1.CreateOptions{})
		framework.ExpectNoError(err)
		createdIngress, err := ingClient.Create(context.TODO(), ingress3, metav1.CreateOptions{})
		framework.ExpectNoError(err)
```

Comment (srikiz) [reply test/e2e/network/ingress.go:638]: yeah, this helps, will update it. Thanks !

**Comment by aojea** [comment]
please squash the PR  once we see the job `pull-kubernetes-e2e-gci-gce-ingress` passes
in addition, it will be good if you can test that this change solves the problem

**Comment by srikiz** [comment]
Looking into the previous test run - those seem to be working fine.

> 
> `
> [0m[sig-network] Ingress API[0m 
>   [1mshould support creating Ingress API operations [Conformance][0m
>   [37m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630[0m
> [BeforeEach] [sig-network] Ingress API
>   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
> [1mSTEP[0m: Creating a kubernetes client
> Jan 25 21:24:13.079: INFO: >>> kubeConfig: /workspace/.kube/config
> [1mSTEP[0m: Building a namespace api object, basename ingress
> [1mSTEP[0m: Waiting for a default service account to be provisioned in namespace
> [It] should support creating Ingress API operations [Conformance]
>   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
> [1mSTEP[0m: getting /apis
> [1mSTEP[0m: getting /apis/networking.k8s.io
> [1mSTEP[0m: getting /apis/networking.k8s.iov1
> [1mSTEP[0m: creating
> [1mSTEP[0m: getting
> [1mSTEP[0m: listing
> [1mSTEP[0m: watching
> Jan 25 21:24:13.659: INFO: starting watch
> [1mSTEP[0m: cluster-wide listing
> [1mSTEP[0m: cluster-wide watching
> Jan 25 21:24:13.740: INFO: starting watch
> [1mSTEP[0m: patching
> [1mSTEP[0m: updating
> Jan 25 21:24:13.907: INFO: waiting for watch events with expected annotations
> Jan 25 21:24:13.908: INFO: saw patched and updated annotations
> [1mSTEP[0m: patching /status
> [1mSTEP[0m: updating /status
> [1mSTEP[0m: get /status
> [1mSTEP[0m: deleting
> [1mSTEP[0m: deleting a collection
> [AfterEach] [sig-network] Ingress API
>   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
> Jan 25 21:24:14.310: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
> [1mSTEP[0m: Destroying namespace "ingress-9376" for this suite.
> [32m•[0m{"msg":"PASSED [sig-network] Ingress API should support creating Ingress API operations [Conformance]","total":32,"completed":28,"skipped":7081,"failed":3,"failures":["[sig-network] Netpol NetworkPolicy between server and client should work with Ingress, Egress specified together [Feature:NetworkPolicy]","[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should conform to Ingress spec","[sig-network] NetworkPolicyLegacy [LinuxOnly] NetworkPolicy between server and client should work with Ingress,Egress specified together [Feature:NetworkPolicy]"]}
> `

**Comment by aojea** [comment]
/lgtm
/approve
The failing tests are unrelated to this pr
Thanks
