### PR TITLE
[sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation: clean remaining pods

### LINKED ISSUE #94715: [Flaky]: [sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run (pods disappearing during the test)
**Which jobs are flaking**:

**Which test(s) are flaking**:
`[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run`

**Testgrid link**:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-ocp-installer-e2e-metal-serial-4.6/1301858872989847552

**Reason for failure**:
If `[sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation` is run before `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run`, the former test does not always make sure all the pods created during testing are deleted. In some cases the pods are deleted/disappear during execution of `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run` between the step of computing overall required cpu resource consumption and the step of scheduling the final pod which verifies no node is capable of scheduling a pod when cpu resource is depleted. Causing the former test to fail.

**Anything else we need to know**:

Logs from the test itself:
```
I0904 13:19:57.058395    1250 test_context.go:427] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
Sep  4 13:19:57.102: INFO: Waiting up to 30m0s for all (but 100) nodes to be schedulable
Sep  4 13:19:57.498: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace &#39;kube-system&#39; to be running and ready
Sep  4 13:19:57.744: INFO: 0 / 0 pods in namespace &#39;kube-system&#39; are running and ready (0 seconds elapsed)
Sep  4 13:19:57.744: INFO: expected 0 pod replicas in namespace &#39;kube-system&#39;, 0 are Running and Ready.
Sep  4 13:19:57.744: INFO: Waiting up to 5m0s for all daemonsets in namespace &#39;kube-system&#39; to start
Sep  4 13:19:57.823: INFO: e2e test version: v0.0.0-master+$Format:%h$
Sep  4 13:19:57.897: INFO: kube-apiserver version: v1.19.0-rc.2+068702d
Sep  4 13:19:57.975: INFO: Cluster IP family: ipv4
[BeforeEach] [Top Level]
  github.com/openshift/origin/test/extended/util/framework.go:1425
[BeforeEach] [Top Level]
  github.com/openshift/origin/test/extended/util/framework.go:1425
[BeforeEach] [Top Level]
  github.com/openshift/origin/test/extended/util/test.go:59
[BeforeEach] [sig-scheduling] SchedulerPredicates [Serial]
  k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/framework/framework.go:174
STEP: Creating a kubernetes client
STEP: Building a namespace api object, basename sched-pred
Sep  4 13:19:58.211: INFO: About to run a Kube e2e test, ensuring namespace is privileged
Sep  4 13:19:58.984: INFO: No PodSecurityPolicies found; assuming PodSecurityPolicy is disabled.
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-scheduling] SchedulerPredicates [Serial]
  k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/scheduling/predicates.go:90
Sep  4 13:19:59.133: INFO: Waiting up to 1m0s for all (but 100) nodes to be ready
Sep  4 13:19:59.291: INFO: Waiting for terminating namespaces to be deleted...
Sep  4 13:19:59.370: INFO: 
Logging pods the apiserver thinks is on node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com before test
Sep  4 13:19:59.460: INFO: ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0 from e2e-sched-priority-3802 started at 2020-09-04 13:19:21 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0 ready: true, restart count 0
Sep  4 13:19:59.461: INFO: tuned-tljds from openshift-cluster-node-tuning-operator started at 2020-09-04 13:04:50 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container tuned ready: true, restart count 0
Sep  4 13:19:59.461: INFO: dns-default-tbqpg from openshift-dns started at 2020-09-04 13:04:50 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container dns ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container dns-node-resolver ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: image-registry-7cf7d78fd6-4mxr9 from openshift-image-registry started at 2020-09-04 13:05:31 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry ready: true, restart count 0
Sep  4 13:19:59.461: INFO: node-ca-zr995 from openshift-image-registry started at 2020-09-04 13:04:53 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container node-ca ready: true, restart count 0
Sep  4 13:19:59.461: INFO: router-default-556cc9b846-8zrxd from openshift-ingress started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container router ready: true, restart count 0
Sep  4 13:19:59.461: INFO: migrator-865bcf9488-tkjff from openshift-kube-storage-version-migrator started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container migrator ready: true, restart count 0
Sep  4 13:19:59.461: INFO: machine-config-daemon-n895c from openshift-machine-config-operator started at 2020-09-04 13:04:50 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container machine-config-daemon ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container oauth-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: certified-operators-c4kzf from openshift-marketplace started at 2020-09-04 13:16:20 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: certified-operators-whjv4 from openshift-marketplace started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: community-operators-88cwp from openshift-marketplace started at 2020-09-04 13:16:20 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: community-operators-qvc86 from openshift-marketplace started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: redhat-marketplace-dxk6r from openshift-marketplace started at 2020-09-04 13:16:20 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: redhat-marketplace-fnsfv from openshift-marketplace started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: redhat-operators-n9vwc from openshift-marketplace started at 2020-09-04 13:16:20 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: redhat-operators-xz9qd from openshift-marketplace started at 2020-09-04 13:05:39 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container registry-server ready: true, restart count 0
Sep  4 13:19:59.461: INFO: alertmanager-main-1 from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (5 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container alertmanager ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container alertmanager-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container config-reloader ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: kube-state-metrics-747cdddc64-frwfw from openshift-monitoring started at 2020-09-04 13:05:39 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy-main ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy-self ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container kube-state-metrics ready: true, restart count 0
Sep  4 13:19:59.461: INFO: node-exporter-w8279 from openshift-monitoring started at 2020-09-04 13:05:06 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container node-exporter ready: true, restart count 0
Sep  4 13:19:59.461: INFO: openshift-state-metrics-59c8cd5968-5rdz7 from openshift-monitoring started at 2020-09-04 13:05:39 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy-main ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy-self ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container openshift-state-metrics ready: true, restart count 0
Sep  4 13:19:59.461: INFO: prometheus-adapter-6b7f847c77-xs5kb from openshift-monitoring started at 2020-09-04 13:06:45 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container prometheus-adapter ready: true, restart count 0
Sep  4 13:19:59.461: INFO: telemeter-client-657bd8cbd6-7ll4v from openshift-monitoring started at 2020-09-04 13:05:39 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container reload ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container telemeter-client ready: true, restart count 0
Sep  4 13:19:59.461: INFO: multus-9p7zj from openshift-multus started at 2020-09-04 13:04:50 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-multus ready: true, restart count 0
Sep  4 13:19:59.461: INFO: network-metrics-daemon-k2xxs from openshift-multus started at 2020-09-04 13:04:50 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container network-metrics-daemon ready: true, restart count 0
Sep  4 13:19:59.461: INFO: ovs-k7n5z from openshift-sdn started at 2020-09-04 13:04:50 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container openvswitch ready: true, restart count 0
Sep  4 13:19:59.461: INFO: sdn-wzgwj from openshift-sdn started at 2020-09-04 13:04:50 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.461: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.461: INFO: &#x9;Container sdn ready: true, restart count 0
Sep  4 13:19:59.461: INFO: 
Logging pods the apiserver thinks is on node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com before test
Sep  4 13:19:59.565: INFO: 67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0 from e2e-sched-priority-3802 started at 2020-09-04 13:19:26 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.565: INFO: &#x9;Container 67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0 ready: true, restart count 0
Sep  4 13:19:59.565: INFO: tuned-v48gt from openshift-cluster-node-tuning-operator started at 2020-09-04 13:05:03 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.565: INFO: &#x9;Container tuned ready: true, restart count 0
Sep  4 13:19:59.565: INFO: dns-default-x9v97 from openshift-dns started at 2020-09-04 13:05:03 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.565: INFO: &#x9;Container dns ready: true, restart count 0
Sep  4 13:19:59.565: INFO: &#x9;Container dns-node-resolver ready: true, restart count 0
Sep  4 13:19:59.565: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.565: INFO: node-ca-8nmtz from openshift-image-registry started at 2020-09-04 13:05:03 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.565: INFO: &#x9;Container node-ca ready: true, restart count 0
Sep  4 13:19:59.566: INFO: machine-config-daemon-wf995 from openshift-machine-config-operator started at 2020-09-04 13:05:03 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container machine-config-daemon ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container oauth-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: alertmanager-main-0 from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (5 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container alertmanager ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container alertmanager-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container config-reloader ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: node-exporter-mjnv9 from openshift-monitoring started at 2020-09-04 13:05:06 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container node-exporter ready: true, restart count 0
Sep  4 13:19:59.566: INFO: prometheus-adapter-6b7f847c77-pc945 from openshift-monitoring started at 2020-09-04 13:06:45 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container prometheus-adapter ready: true, restart count 0
Sep  4 13:19:59.566: INFO: prometheus-k8s-1 from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (7 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container prometheus ready: true, restart count 1
Sep  4 13:19:59.566: INFO: &#x9;Container prometheus-config-reloader ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container prometheus-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container rules-configmap-reloader ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container thanos-sidecar ready: true, restart count 0
Sep  4 13:19:59.566: INFO: thanos-querier-5c57566d79-c5n5d from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (5 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy-rules ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container oauth-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container thanos-query ready: true, restart count 0
Sep  4 13:19:59.566: INFO: multus-h7dtf from openshift-multus started at 2020-09-04 13:05:03 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-multus ready: true, restart count 0
Sep  4 13:19:59.566: INFO: network-metrics-daemon-9nvjv from openshift-multus started at 2020-09-04 13:05:03 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.566: INFO: &#x9;Container network-metrics-daemon ready: true, restart count 0
Sep  4 13:19:59.566: INFO: ovs-ssnc6 from openshift-sdn started at 2020-09-04 13:05:03 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container openvswitch ready: true, restart count 0
Sep  4 13:19:59.566: INFO: sdn-xw75k from openshift-sdn started at 2020-09-04 13:05:03 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.566: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 1
Sep  4 13:19:59.566: INFO: &#x9;Container sdn ready: true, restart count 0
Sep  4 13:19:59.566: INFO: 
Logging pods the apiserver thinks is on node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com before test
Sep  4 13:19:59.655: INFO: ffecd964-0982-4541-ba35-bc53ef1bcd52-0 from e2e-sched-priority-3802 started at 2020-09-04 13:19:31 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container ffecd964-0982-4541-ba35-bc53ef1bcd52-0 ready: true, restart count 0
Sep  4 13:19:59.655: INFO: tuned-cmmn2 from openshift-cluster-node-tuning-operator started at 2020-09-04 13:04:54 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container tuned ready: true, restart count 0
Sep  4 13:19:59.655: INFO: dns-default-rc6ht from openshift-dns started at 2020-09-04 13:04:54 +0000 UTC (3 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container dns ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container dns-node-resolver ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: node-ca-72247 from openshift-image-registry started at 2020-09-04 13:04:54 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container node-ca ready: true, restart count 0
Sep  4 13:19:59.655: INFO: router-default-556cc9b846-x8j5j from openshift-ingress started at 2020-09-04 13:05:50 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container router ready: true, restart count 0
Sep  4 13:19:59.655: INFO: machine-config-daemon-7gnl4 from openshift-machine-config-operator started at 2020-09-04 13:04:54 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container machine-config-daemon ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container oauth-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: alertmanager-main-2 from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (5 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container alertmanager ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container alertmanager-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container config-reloader ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: grafana-5dc687d5df-mltbk from openshift-monitoring started at 2020-09-04 13:05:45 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container grafana ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container grafana-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: node-exporter-rklqh from openshift-monitoring started at 2020-09-04 13:05:06 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container node-exporter ready: true, restart count 0
Sep  4 13:19:59.655: INFO: prometheus-k8s-0 from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (7 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container prometheus ready: true, restart count 1
Sep  4 13:19:59.655: INFO: &#x9;Container prometheus-config-reloader ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container prometheus-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container rules-configmap-reloader ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container thanos-sidecar ready: true, restart count 0
Sep  4 13:19:59.655: INFO: thanos-querier-5c57566d79-zc2sf from openshift-monitoring started at 2020-09-04 13:06:16 +0000 UTC (5 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy-rules ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container oauth-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container prom-label-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container thanos-query ready: true, restart count 0
Sep  4 13:19:59.655: INFO: multus-b6z24 from openshift-multus started at 2020-09-04 13:04:54 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-multus ready: true, restart count 0
Sep  4 13:19:59.655: INFO: network-metrics-daemon-cmnw6 from openshift-multus started at 2020-09-04 13:04:54 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container network-metrics-daemon ready: true, restart count 0
Sep  4 13:19:59.655: INFO: ovs-shgxf from openshift-sdn started at 2020-09-04 13:04:54 +0000 UTC (1 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container openvswitch ready: true, restart count 0
Sep  4 13:19:59.655: INFO: sdn-sblm6 from openshift-sdn started at 2020-09-04 13:04:54 +0000 UTC (2 container statuses recorded)
Sep  4 13:19:59.655: INFO: &#x9;Container kube-rbac-proxy ready: true, restart count 0
Sep  4 13:19:59.655: INFO: &#x9;Container sdn ready: true, restart count 0
[It] validates resource limits of pods that are allowed to run  [Conformance] [Suite:openshift/conformance/serial/minimal] [Suite:k8s]
  k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/framework/framework.go:597
STEP: verifying the node has the label node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: verifying the node has the label node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: verifying the node has the label node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod 67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0 requesting resource cpu=3182m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0 requesting resource cpu=2877m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ffecd964-0982-4541-ba35-bc53ef1bcd52-0 requesting resource cpu=3078m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-cmmn2 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-tljds requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-v48gt requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-rc6ht requesting resource cpu=65m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-tbqpg requesting resource cpu=65m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-x9v97 requesting resource cpu=65m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod image-registry-7cf7d78fd6-4mxr9 requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-72247 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-8nmtz requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-zr995 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod router-default-556cc9b846-8zrxd requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod router-default-556cc9b846-x8j5j requesting resource cpu=100m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod migrator-865bcf9488-tkjff requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-7gnl4 requesting resource cpu=40m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-n895c requesting resource cpu=40m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-wf995 requesting resource cpu=40m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod certified-operators-c4kzf requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod certified-operators-whjv4 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod community-operators-88cwp requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod community-operators-qvc86 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-marketplace-dxk6r requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-marketplace-fnsfv requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-operators-n9vwc requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-operators-xz9qd requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-0 requesting resource cpu=8m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-1 requesting resource cpu=8m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-2 requesting resource cpu=8m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod grafana-5dc687d5df-mltbk requesting resource cpu=5m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod kube-state-metrics-747cdddc64-frwfw requesting resource cpu=4m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-mjnv9 requesting resource cpu=9m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-rklqh requesting resource cpu=9m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-w8279 requesting resource cpu=9m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod openshift-state-metrics-59c8cd5968-5rdz7 requesting resource cpu=3m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-adapter-6b7f847c77-pc945 requesting resource cpu=1m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-adapter-6b7f847c77-xs5kb requesting resource cpu=1m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-k8s-0 requesting resource cpu=76m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-k8s-1 requesting resource cpu=76m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod telemeter-client-657bd8cbd6-7ll4v requesting resource cpu=3m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod thanos-querier-5c57566d79-c5n5d requesting resource cpu=9m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod thanos-querier-5c57566d79-zc2sf requesting resource cpu=9m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-9p7zj requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-b6z24 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-h7dtf requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-9nvjv requesting resource cpu=20m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-cmnw6 requesting resource cpu=20m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-k2xxs requesting resource cpu=20m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-k7n5z requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-shgxf requesting resource cpu=100m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-ssnc6 requesting resource cpu=100m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-sblm6 requesting resource cpu=110m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-wzgwj requesting resource cpu=110m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-xw75k requesting resource cpu=110m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: Starting Pods to consume most of the cluster CPU.
Sep  4 13:20:00.412: INFO: Creating a pod which consumes cpu=2695m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.494: INFO: Creating a pod which consumes cpu=2695m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.574: INFO: Creating a pod which consumes cpu=2695m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: Creating another pod that requires unavailable amount of CPU.
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91.16319736522dd0b3], Reason = [AddedInterface], Message = [Add eth0 [10.128.2.21/23]]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7.16319735e78aa781], Reason = [Scheduled], Message = [Successfully assigned e2e-sched-pred-4521/filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7 to worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-8e8309c7-b858-481c-8052-246ba24580d0.163197365dbff0ee], Reason = [Pulled], Message = [Container image "k8s.gcr.io/pause:3.2" already present on machine]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7.163197365dfea390], Reason = [Created], Message = [Created container filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7.1631973657231b20], Reason = [Pulled], Message = [Container image "k8s.gcr.io/pause:3.2" already present on machine]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91.163197366a7411d5], Reason = [Started], Message = [Started container filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91.16319735f103b6e5], Reason = [Scheduled], Message = [Successfully assigned e2e-sched-pred-4521/filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91 to worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-8e8309c7-b858-481c-8052-246ba24580d0.16319736504b82f3], Reason = [AddedInterface], Message = [Add eth0 [10.129.2.23/23]]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91.16319736697f39a7], Reason = [Created], Message = [Created container filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-8e8309c7-b858-481c-8052-246ba24580d0.1631973666e312e2], Reason = [Started], Message = [Started container filler-pod-8e8309c7-b858-481c-8052-246ba24580d0]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91.16319736618cefb8], Reason = [Pulled], Message = [Container image "k8s.gcr.io/pause:3.2" already present on machine]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7.163197364a392344], Reason = [AddedInterface], Message = [Add eth0 [10.131.0.40/23]]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-8e8309c7-b858-481c-8052-246ba24580d0.1631973665dd5371], Reason = [Created], Message = [Created container filler-pod-8e8309c7-b858-481c-8052-246ba24580d0]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7.163197365eee57eb], Reason = [Started], Message = [Started container filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7]
STEP: Considering event: 
Type = [Normal], Name = [filler-pod-8e8309c7-b858-481c-8052-246ba24580d0.16319735ec364292], Reason = [Scheduled], Message = [Successfully assigned e2e-sched-pred-4521/filler-pod-8e8309c7-b858-481c-8052-246ba24580d0 to worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com]
STEP: Considering event: 
Type = [Normal], Name = [additional-pod.163197370879d82a], Reason = [Scheduled], Message = [Successfully assigned e2e-sched-pred-4521/additional-pod to worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com]
STEP: Considering event: 
Type = [Normal], Name = [additional-pod.163197378fc938e3], Reason = [AddedInterface], Message = [Add eth0 [10.128.2.22/23]]
STEP: Considering event: 
Type = [Normal], Name = [additional-pod.163197379d517b08], Reason = [Pulled], Message = [Container image "k8s.gcr.io/pause:3.2" already present on machine]
STEP: Considering event: 
Type = [Normal], Name = [additional-pod.16319737a42ab8ab], Reason = [Created], Message = [Created container additional-pod]
STEP: Considering event: 
Type = [Normal], Name = [additional-pod.16319737a5360ee0], Reason = [Started], Message = [Started container additional-pod]
STEP: removing the label node off the node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: verifying the node doesn&#39;t have the label node
STEP: removing the label node off the node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: verifying the node doesn&#39;t have the label node
STEP: removing the label node off the node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
STEP: verifying the node doesn&#39;t have the label node
[AfterEach] [sig-scheduling] SchedulerPredicates [Serial]
  k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/framework/framework.go:175
STEP: Collecting events from namespace "e2e-sched-pred-4521".
STEP: Found 20 events.
Sep  4 13:22:06.181: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for additional-pod: { } Scheduled: Successfully assigned e2e-sched-pred-4521/additional-pod to worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:22:06.181: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7: { } Scheduled: Successfully assigned e2e-sched-pred-4521/filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7 to worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:22:06.181: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for filler-pod-8e8309c7-b858-481c-8052-246ba24580d0: { } Scheduled: Successfully assigned e2e-sched-pred-4521/filler-pod-8e8309c7-b858-481c-8052-246ba24580d0 to worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:22:06.181: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91: { } Scheduled: Successfully assigned e2e-sched-pred-4521/filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91 to worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7: {kubelet worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Started: Started container filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7: {multus } AddedInterface: Add eth0 [10.131.0.40/23]
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7: {kubelet worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Pulled: Container image "k8s.gcr.io/pause:3.2" already present on machine
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7: {kubelet worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Created: Created container filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-8e8309c7-b858-481c-8052-246ba24580d0: {kubelet worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Started: Started container filler-pod-8e8309c7-b858-481c-8052-246ba24580d0
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-8e8309c7-b858-481c-8052-246ba24580d0: {kubelet worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Pulled: Container image "k8s.gcr.io/pause:3.2" already present on machine
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-8e8309c7-b858-481c-8052-246ba24580d0: {kubelet worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Created: Created container filler-pod-8e8309c7-b858-481c-8052-246ba24580d0
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-8e8309c7-b858-481c-8052-246ba24580d0: {multus } AddedInterface: Add eth0 [10.129.2.23/23]
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Started: Started container filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91: {multus } AddedInterface: Add eth0 [10.128.2.21/23]
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Pulled: Container image "k8s.gcr.io/pause:3.2" already present on machine
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:02 +0000 UTC - event for filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Created: Created container filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:07 +0000 UTC - event for additional-pod: {multus } AddedInterface: Add eth0 [10.128.2.22/23]
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:07 +0000 UTC - event for additional-pod: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Pulled: Container image "k8s.gcr.io/pause:3.2" already present on machine
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:07 +0000 UTC - event for additional-pod: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Started: Started container additional-pod
Sep  4 13:22:06.181: INFO: At 2020-09-04 13:20:07 +0000 UTC - event for additional-pod: {kubelet worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com} Created: Created container additional-pod
Sep  4 13:22:06.257: INFO: POD                                              NODE                                                             PHASE    GRACE  CONDITIONS
Sep  4 13:22:06.257: INFO: additional-pod                                   worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:05 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:07 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:07 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:05 +0000 UTC  }]
Sep  4 13:22:06.257: INFO: filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7  worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  }]
Sep  4 13:22:06.257: INFO: filler-pod-8e8309c7-b858-481c-8052-246ba24580d0  worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  }]
Sep  4 13:22:06.257: INFO: filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91  worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:02 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2020-09-04 13:20:00 +0000 UTC  }]
Sep  4 13:22:06.257: INFO: 
Sep  4 13:22:06.340: INFO: additional-pod[e2e-sched-pred-4521].container[additional-pod].log

Sep  4 13:22:06.424: INFO: filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7[e2e-sched-pred-4521].container[filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7].log

Sep  4 13:22:06.506: INFO: filler-pod-8e8309c7-b858-481c-8052-246ba24580d0[e2e-sched-pred-4521].container[filler-pod-8e8309c7-b858-481c-8052-246ba24580d0].log

Sep  4 13:22:06.584: INFO: filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91[e2e-sched-pred-4521].container[filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91].log

Sep  4 13:22:06.735: INFO: skipping dumping cluster info - cluster too large
Sep  4 13:22:06.735: INFO: Waiting up to 7m0s for all (but 100) nodes to be ready
STEP: Destroying namespace "e2e-sched-pred-4521" for this suite.
[AfterEach] [sig-scheduling] SchedulerPredicates [Serial]
  k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/scheduling/predicates.go:81
Sep  4 13:22:06.895: INFO: Running AfterSuite actions on all nodes
Sep  4 13:22:06.895: INFO: Running AfterSuite actions on node 1
fail [k8s.io/kubernetes@v1.19.0-rc.2/test/e2e/scheduling/predicates.go:925]: Unexpected error:
    <*errors.errorString | 0xc0002dc8b0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

Scheduler logs (with https://github.com/kubernetes/kubernetes/pull/94423 debugger scheduling plugin enabled):
```
I0904 13:19:21.079071       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5579Mi pods=0 ephemeral-storage=0 cpu=1895m]"
I0904 13:19:21.079095       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.079108       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:19:21.079121       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=773m memory=3097Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.079133       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=3282Mi pods=0 ephemeral-storage=0 cpu=572m]"
I0904 13:19:21.079145       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=468m memory=2931Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.083259       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:26.257626       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257646       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257656       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257668       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:19:26.257677       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=572m memory=3282Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257689       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=2931Mi pods=0 ephemeral-storage=0 cpu=468m]"
I0904 13:19:26.263121       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:31.436220       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436239       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1720m memory=5049Mi pods=0]"
I0904 13:19:31.436251       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436264       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3650m memory=14938440Ki pods=0]"
I0904 13:19:31.436275       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=572m memory=3282Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436288       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14874430Ki pods=0 ephemeral-storage=0]"
I0904 13:19:31.440420       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/ffecd964-0982-4541-ba35-bc53ef1bcd52-0" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:40.139882       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139904       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139914       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139922       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14938440Ki]"
I0904 13:19:40.139930       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=15231428607 pods=0 ephemeral-storage=0 cpu=3650m]"
I0904 13:19:40.139942       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14874430Ki]"
I0904 13:19:40.145351       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/scheduler-priority-avoid-pod-j72gx" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=3
I0904 13:19:40.146963       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1895m memory=5579Mi]"
I0904 13:19:40.147004       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1720m memory=5049Mi]"
I0904 13:19:40.147026       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.147046       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:19:40.147068       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=15231428607 pods=0 ephemeral-storage=0 cpu=3650m]"
I0904 13:19:40.147092       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=14976830Ki pods=0 ephemeral-storage=0 cpu=3750m]"
I0904 13:19:40.150793       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/scheduler-priority-avoid-pod-j6kgx" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=3
I0904 13:20:00.462039       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462066       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462079       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462091       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14938440Ki]"
I0904 13:20:00.462103       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.462122       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3650m memory=14874430Ki pods=0]"
I0904 13:20:00.466956       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:00.541768       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1895m memory=5579Mi]"
I0904 13:20:00.541793       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.541806       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.541818       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=6345m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.541833       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.541847       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14874430Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.545296       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-8e8309c7-b858-481c-8052-246ba24580d0" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:00.622148       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5579Mi pods=0 ephemeral-storage=0 cpu=1895m]"
I0904 13:20:00.622175       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5049Mi pods=0 ephemeral-storage=0 cpu=1720m]"
I0904 13:20:00.622188       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:20:00.622199       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=6345m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.622213       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.622229       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=6345m memory=14874430Ki]"
I0904 13:20:00.625867       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:05.309985       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310011       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310021       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:20:05.310029       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3468m memory=3097Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310037       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3267m memory=3282Mi pods=0]"
I0904 13:20:05.310044       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=6345m memory=14874430Ki]"
I0904 13:20:05.314450       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/additional-pod" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=2
```

### PR DESCRIPTION
**Pull request by ingvagabund**
**What type of PR is this?**
In some cases when running "[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run"
"scheduler-priority-avoid-pod-XXX" filler pods from "[sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation" are still being
terminated in the cluster. Which can cause "validates resource limits of pods that are allowed to run" to flake since the filler
pods dissappear before "additional-pod" is scheduled. Causing the calculated filler-pods to consume less than they are supposed to.

/kind bug

**What this PR does / why we need it**:
Reduce flakiness of `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run`

**Which issue(s) this PR fixes**:

Fixes #94715

**Special notes for your reviewer**:

Scheduler logs around the time of flakiness:
```
I0904 13:19:21.079071       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5579Mi pods=0 ephemeral-storage=0 cpu=1895m]"
I0904 13:19:21.079095       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.079108       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:19:21.079121       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=773m memory=3097Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.079133       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=3282Mi pods=0 ephemeral-storage=0 cpu=572m]"
I0904 13:19:21.079145       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=468m memory=2931Mi pods=0 ephemeral-storage=0]"
I0904 13:19:21.083259       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:26.257626       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257646       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257656       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257668       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:19:26.257677       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=572m memory=3282Mi pods=0 ephemeral-storage=0]"
I0904 13:19:26.257689       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=2931Mi pods=0 ephemeral-storage=0 cpu=468m]"
I0904 13:19:26.263121       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:31.436220       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436239       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1720m memory=5049Mi pods=0]"
I0904 13:19:31.436251       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436264       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3650m memory=14938440Ki pods=0]"
I0904 13:19:31.436275       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=572m memory=3282Mi pods=0 ephemeral-storage=0]"
I0904 13:19:31.436288       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14874430Ki pods=0 ephemeral-storage=0]"
I0904 13:19:31.440420       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/ffecd964-0982-4541-ba35-bc53ef1bcd52-0" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:19:40.139882       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139904       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139914       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.139922       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14938440Ki]"
I0904 13:19:40.139930       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=15231428607 pods=0 ephemeral-storage=0 cpu=3650m]"
I0904 13:19:40.139942       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14874430Ki]"
I0904 13:19:40.145351       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/scheduler-priority-avoid-pod-j72gx" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=3
I0904 13:19:40.146963       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1895m memory=5579Mi]"
I0904 13:19:40.147004       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1720m memory=5049Mi]"
I0904 13:19:40.147026       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:19:40.147046       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:19:40.147068       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=15231428607 pods=0 ephemeral-storage=0 cpu=3650m]"
I0904 13:19:40.147092       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=14976830Ki pods=0 ephemeral-storage=0 cpu=3750m]"
I0904 13:19:40.150793       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-priority-3802/scheduler-priority-avoid-pod-j6kgx" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=3
I0904 13:20:00.462039       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462066       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462079       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.462091       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=3650m memory=14938440Ki]"
I0904 13:20:00.462103       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.462122       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3650m memory=14874430Ki pods=0]"
I0904 13:20:00.466956       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-5be568c0-1552-4f2e-8ff2-869c5cd610f7" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:00.541768       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=1895m memory=5579Mi]"
I0904 13:20:00.541793       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.541806       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1934m memory=5999Mi pods=0 ephemeral-storage=0]"
I0904 13:20:00.541818       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=6345m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.541833       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.541847       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=14874430Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.545296       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-8e8309c7-b858-481c-8052-246ba24580d0" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:00.622148       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5579Mi pods=0 ephemeral-storage=0 cpu=1895m]"
I0904 13:20:00.622175       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[memory=5049Mi pods=0 ephemeral-storage=0 cpu=1720m]"
I0904 13:20:00.622188       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:20:00.622199       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=6345m memory=14938440Ki pods=0 ephemeral-storage=0]"
I0904 13:20:00.622213       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3650m memory=15231428607 pods=0 ephemeral-storage=0]"
I0904 13:20:00.622229       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=6345m memory=14874430Ki]"
I0904 13:20:00.625867       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/filler-pod-e98507a6-2221-4312-9f1b-34b7d1124b91" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=1
I0904 13:20:05.309985       1 debugger.go:65] "Dumping node infos" node="master-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1895m memory=5579Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310011       1 debugger.go:65] "Dumping node infos" node="master-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=1720m memory=5049Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310021       1 debugger.go:65] "Dumping node infos" node="master-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=1934m memory=5999Mi pods=0]"
I0904 13:20:05.310029       1 debugger.go:65] "Dumping node infos" node="worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[cpu=3468m memory=3097Mi pods=0 ephemeral-storage=0]"
I0904 13:20:05.310037       1 debugger.go:65] "Dumping node infos" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[ephemeral-storage=0 cpu=3267m memory=3282Mi pods=0]"
I0904 13:20:05.310044       1 debugger.go:65] "Dumping node infos" node="worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" requested="[pods=0 ephemeral-storage=0 cpu=6345m memory=14874430Ki]"
I0904 13:20:05.314450       1 scheduler.go:598] "Successfully bound pod to node" pod="e2e-sched-pred-4521/additional-pod" node="worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com" evaluatedNodes=6 feasibleNodes=2
```

Notice the change of cpu on `worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com` right before `e2e-sched-pred-4521/additional-pod` is scheduled. Requested cpu of all pods on the node dropped from `cpu=6345m` to `cpu=3468m` as `ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0` pod finally disappeared.

Before that the total requested cpu was computed through:
```
Sep  4 13:20:00.412: INFO: Pod 67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0 requesting resource cpu=3182m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0 requesting resource cpu=2877m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ffecd964-0982-4541-ba35-bc53ef1bcd52-0 requesting resource cpu=3078m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-cmmn2 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-tljds requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod tuned-v48gt requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-rc6ht requesting resource cpu=65m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-tbqpg requesting resource cpu=65m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod dns-default-x9v97 requesting resource cpu=65m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod image-registry-7cf7d78fd6-4mxr9 requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-72247 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-8nmtz requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-ca-zr995 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod router-default-556cc9b846-8zrxd requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod router-default-556cc9b846-x8j5j requesting resource cpu=100m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod migrator-865bcf9488-tkjff requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-7gnl4 requesting resource cpu=40m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-n895c requesting resource cpu=40m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod machine-config-daemon-wf995 requesting resource cpu=40m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod certified-operators-c4kzf requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod certified-operators-whjv4 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod community-operators-88cwp requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod community-operators-qvc86 requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-marketplace-dxk6r requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-marketplace-fnsfv requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-operators-n9vwc requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod redhat-operators-xz9qd requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-0 requesting resource cpu=8m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-1 requesting resource cpu=8m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod alertmanager-main-2 requesting resource cpu=8m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod grafana-5dc687d5df-mltbk requesting resource cpu=5m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod kube-state-metrics-747cdddc64-frwfw requesting resource cpu=4m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-mjnv9 requesting resource cpu=9m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-rklqh requesting resource cpu=9m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod node-exporter-w8279 requesting resource cpu=9m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod openshift-state-metrics-59c8cd5968-5rdz7 requesting resource cpu=3m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-adapter-6b7f847c77-pc945 requesting resource cpu=1m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-adapter-6b7f847c77-xs5kb requesting resource cpu=1m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-k8s-0 requesting resource cpu=76m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod prometheus-k8s-1 requesting resource cpu=76m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod telemeter-client-657bd8cbd6-7ll4v requesting resource cpu=3m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod thanos-querier-5c57566d79-c5n5d requesting resource cpu=9m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod thanos-querier-5c57566d79-zc2sf requesting resource cpu=9m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-9p7zj requesting resource cpu=10m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-b6z24 requesting resource cpu=10m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod multus-h7dtf requesting resource cpu=10m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-9nvjv requesting resource cpu=20m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-cmnw6 requesting resource cpu=20m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod network-metrics-daemon-k2xxs requesting resource cpu=20m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-k7n5z requesting resource cpu=100m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-shgxf requesting resource cpu=100m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod ovs-ssnc6 requesting resource cpu=100m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-sblm6 requesting resource cpu=110m on Node worker-2.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-wzgwj requesting resource cpu=110m on Node worker-0.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
Sep  4 13:20:00.412: INFO: Pod sdn-xw75k requesting resource cpu=110m on Node worker-1.ci-op-qfypnb1x-18a82.origin-ci-int-aws.dev.rhcloud.com
```

where clearly `67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0`, `ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0` and `ffecd964-0982-4541-ba35-bc53ef1bcd52-0` are taken into account when they should not.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ingvagabund** [comment]
@alculquicondor PTAL

File: test/e2e/scheduling/priorities.go [hunk 1]
```diff
@@ -252,6 +252,21 @@ var _ = SIGDescribe("SchedulerPriorities [Serial]", func() {
 			if err := e2erc.DeleteRCAndWaitForGC(f.ClientSet, f.Namespace.Name, rc.Name); err != nil {
 				framework.Logf("Failed to cleanup replication controller %v: %v.", rc.Name, err)
 			}
+			// Just in case DeleteRCAndWaitForGC returns non-nil error but the pods are in
+			// terminating state, give them more time to get deleted so subsequent tests
+			// (e.g. [sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run)
+			// do not process pods that are disappearing under their hands.
+			wait.PollImmediate(time.Second, 2*time.Minute, func() (bool, error) {
```
Comment (alculquicondor) [inline test/e2e/scheduling/priorities.go:259]: Can you look into fixing `DeleteResourceAndWaitForGC` instead? According to its comment, it should already wait for it. Are you seeing `Failed to cleanup replication controller` in the logs? If so, we should fix those.

Comment (ingvagabund) [reply test/e2e/scheduling/priorities.go:259]: Unfortunately, I have logs only from failed ci runs. `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run` is green when `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run` flakes. Also, it's reproducible only in ~5% of cases.

Comment (alculquicondor) [reply test/e2e/scheduling/priorities.go:259]: In that case, I'm not convinced that this patch will solve the flakiness, as we don't understand the root cause of the leaking pods.

Comment (alculquicondor) [reply test/e2e/scheduling/priorities.go:259]: Could you share a failed run?

Comment (ingvagabund) [reply test/e2e/scheduling/priorities.go:259]: > Could you share a failed run?

In case of `[sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation`, it will never fail because of pods not getting properly deleted. 

In case of `[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run`, just reported https://github.com/kubernetes/kubernetes/issues/94715

Comment (ingvagabund) [reply test/e2e/scheduling/priorities.go:259]: @alculquicondor what about to fail when `e2erc.DeleteRCAndWaitForGC` returns an error instead? It's not a failure related to the test itself. Though, the test should still make sure all the resources created by it are cleaned.

Comment (alculquicondor) [reply test/e2e/scheduling/priorities.go:259]: What we need to know is why it fails and fix that, because that's the function that is intended to do the cleanup. By waiting again after that function, we are duplicating code and moving the issue somewhere else.

Comment (ingvagabund) [reply test/e2e/scheduling/priorities.go]: @alculquicondor I still have not been able to reproduce the case and get the error message when `e2erc.DeleteRCAndWaitForGC` is not deleting all the pods. Instead, I am updating `validates resource limits of pods that are allowed to run` to ignore all pods with `pod.DeletionTimestamp` set. Since those pods can disappear at any moment and make the calculated total resources unusable for decision making.

File: test/e2e/scheduling/predicates.go [hunk 2]
```diff
@@ -356,7 +356,7 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
 		framework.ExpectNoError(err)
 		for _, pod := range pods.Items {
 			_, found := nodeToAllocatableMap[pod.Spec.NodeName]
-			if found && pod.Status.Phase != v1.PodSucceeded && pod.Status.Phase != v1.PodFailed {
+			if found && pod.Status.Phase != v1.PodSucceeded && pod.Status.Phase != v1.PodFailed && pod.DeletionTimestamp == nil {
```
Comment (alculquicondor) [inline test/e2e/scheduling/predicates.go:359]: This might cause another flake where the last pod is scheduled if one Pod with DeletionTimestamp doesn't ever terminate.

Have you tried increasing timeouts in the cleanup function for replication controller?

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go:359]: > This might cause another flake where the last pod is scheduled if one Pod with DeletionTimestamp doesn't ever terminate.

If the pod with DeletionTimestamp set does not terminate, there will be even more resource requested. I.e. resource requested by all pods without DeletionTimestamp set + filler pods + pods with DeletionTimestamp set.

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go:359]: Sorry, the case I was thinking of is actually this:

There are a lot of Pods with DeletionTimestamp initially, and they they all terminate. Thus there is a lot of space and the last pod gets scheduled.

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go:359]: Let's use `pods` for a set of all pods (including pods with `DeletionTimestamp` set) and `podswithoutDT` for a set of all pods with `DeletionTimestamp` set to nil

```
for _, pod := range pods.Items {
	_, found := nodeToAllocatableMap[pod.Spec.NodeName]
	if found && pod.Status.Phase != v1.PodSucceeded && pod.Status.Phase != v1.PodFailed && pod.DeletionTimestamp == nil {
		framework.Logf("Pod %v requesting resource cpu=%vm on Node %v", pod.Name, getRequestedCPU(pod), pod.Spec.NodeName)
		nodeToAllocatableMap[pod.Spec.NodeName] -= getRequestedCPU(pod)
	}
}
```

After the cycle `nodeToAllocatableMap[node]` constructed from `pods` will be less or equal to the same map constructed from `podswithoutDT`. I.e. `nodeToAllocatableMap_pods[node] <= nodeToAllocatableMap_podswithoutDT[node]`.

With the next cycle where the `filler-pod-XXX` pods are constructed:
```
for nodeName, cpu := range nodeToAllocatableMap {
	requestedCPU := cpu * 7 / 10
...
```

Given `nodeToAllocatableMap_pods[node] <= nodeToAllocatableMap_podswithoutDT[node]`, also `requestedCPU` for set `pods` will be less or equal to `podswithoutDT`. I.e.

`requestedCPU_pods <= requestedCPU_podswithoutDT`.

In other words, requested cpu of a filler pod for all pods including pods with DeletionTimestamp set (on a given node) will never be more than requested cpu for all pods (on a given node) without pods with DeletionTimestamp set. So if any of the pods with DeletionTimestamp set disappears, the requested cpu (from `podswithoutDT` set) of a filler pod will compensate. 

It's actually the opposite problem in question. What if the pods with DeletionTimestamp set do not disappear before the `additional-pod` is scheduled? `additional-pod` will not still get scheduled since there's gonna be even less of cpu resource left. The worst case scenario is when there's so many pods with DeletionTimestamp set that even the filler pods will not get scheduled.

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go:359]: > There are a lot of Pods with DeletionTimestamp initially and they all terminate after this loop. Thus there is a lot of space and the last pod gets scheduled.

This is actually the case happening now

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go:359]: Thanks for detailed analysis. You are right, the scenario where `additional-pod` doesn't get scheduled is possible. It sounds like the only correct solution is to fix the cleanup of other tests :/

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go:359]: I am afraid there can be other tests not cleaning their pods properly in the future (or maybe even now). If so, this needs to be fixed on multiple places. I'd start here since this change is making the test less flaky if there's not so many pods with DeletionTimestamp set.

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go:359]: I'm not comfortable with this patch. @Huang-Wei @ahg-g to comment.

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go:359]: Even if this makes the test less flaky, that's not necessarily better, as we might be hiding legitimate bugs.

Comment (ahg-g) [reply test/e2e/scheduling/predicates.go:359]: >  The worst case scenario is when there's so many pods with DeletionTimestamp set that even the filler pods will not get scheduled.

Right, and this will most likely cause flakes in the future.

We already call `WaitForStableCluster`, perhaps we can modify it to call `WaitForPodsToBeDeleted`? If those pods don't get deleted, then there is something wrong happening and we can address that instead of working around it by ignoring pods to be deleted.

Comment (Huang-Wei) [reply test/e2e/scheduling/predicates.go:359]: > We already call `WaitForStableCluster`, perhaps we can modify it to call `WaitForPodsToBeDeleted`?

+1, instead of embedding `WaitForPodsToBeDeleted` into `WaitForStableCluster`, another option is to call `WaitForPodsToBeDeleted` on demand, immediately after `WaitForStableCluster`, for example in the case.

BTW: `WaitForPodsToBeDeleted` was used in an old test case (which is deleted now) in 1.17:

https://github.com/kubernetes/kubernetes/blob/5ec472285121eb6c451e515bc0a7201413872fa3/test/e2e/scheduling/predicates.go#L132

So I _guess_ `WaitForPodsToBeDeleted` was introduced at that time to resolve similar flakes.

Comment (Huang-Wei) [reply test/e2e/scheduling/predicates.go:359]: Another thing a bit off the topic: both `WaitForStableCluster` and `WaitForPodsToBeDeleted` are performing an infinite `for` loop, although the ginkgo test may be guarded by a timeout argument, I think it'd be good to explicitly time out the test inside the function. Anyway, it can be a follow-up.

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go]: I was able to reproduce the test locally. The remaining pods (`67e791a6-f170-4aff-b2b1-e42a0a6a7c3c-0`, `ead2872e-4ad3-4244-bb02-9f7ff0b6a428-0` and `ffecd964-0982-4541-ba35-bc53ef1bcd52-0`) were not deleted before the testing namespace was. Thus, leaving the pods still running even after the test ended. PR update to delete all remaining pods in the testing namespace first.

@alculquicondor @ahg-g @Huang-Wei  PTAL

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go]: I still have the same issue with this patch.

Why don't we fix `DeleteRCAndWaitForGC` instead?

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go]: The remaining pods have no owner

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go]: can you tell what created them then?

Again, I'd like to fix the root of the problem.

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go]: https://github.com/kubernetes/kubernetes/blob/64c099d67069f85f2b9b78d7d12fd1a92fcc3d75/test/e2e/scheduling/priorities.go#L484

Other option is to have `createBalancedPodForNodes` return cleanup function that will be called in `defer` block.

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go]: oh, I get it now. These Pods are not created for the RC.

2 things then:
- Use `DeleteCollection()`.
- Do this in a separate defer, right after the Pods are created. Otherwise if RC creation fails, these Pods don't get cleaned.

Maybe for follow up: could you check for other instances where `createBalancedPodForNodes` is called and Pods are not cleared? Is this ever intended?

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go]: `DeleteCollection` does not wait until all the pods are deleted. Which makes it unusable without additional waiting logic.

Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go]: PR updated. `createBalancedPodForNodes` now returns cleanUp function which is called right away through defer.

File: test/e2e/scheduling/predicates.go [hunk 3]
```diff
@@ -887,8 +887,8 @@ func initPausePod(f *framework.Framework, conf pausePodConfig) *v1.Pod {
 		ObjectMeta: metav1.ObjectMeta{
 			Name:            conf.Name,
 			Namespace:       conf.Namespace,
-			Labels:          conf.Labels,
-			Annotations:     conf.Annotations,
+			Labels:          map[string]string{},
```
Comment (alculquicondor) [inline test/e2e/scheduling/predicates.go:890]: why is this change necessary?

File: test/e2e/scheduling/priorities.go [hunk 4]
```diff
@@ -425,7 +430,23 @@ var _ = SIGDescribe("SchedulerPriorities [Serial]", func() {
...
+	cleanUp := func() {
+		// Delete all remaining pods
+		podList, err := cs.CoreV1().Pods(ns).List(context.TODO(), metav1.ListOptions{
+			LabelSelector: labels.SelectorFromSet(labels.Set(balancePodLabel)).String(),
+		})
+		if err != nil {
+			framework.Logf("Failed to list remaining pods for cleanup: %v.", err)
+		} else {
+			for _, pod := range podList.Items {
+				if err := e2epod.DeletePodWithWaitByName(cs, pod.Name, pod.Namespace); err != nil {
```
Comment (alculquicondor) [inline test/e2e/scheduling/priorities.go:443]: can we parallelize and have a wait group?
Alternatively, you can do `DeleteCollection` and have a `wait.Poll` that does a `List` until it returns empty.

File: test/e2e/scheduling/predicates.go (hunk 3 above)
Comment (ingvagabund) [reply test/e2e/scheduling/predicates.go:890]: `testutils.StartPods` modifies Labels field. `Labels: conf.Labels` is a shallow copy and `conf.Labels` is a [shallow copy](https://github.com/kubernetes/kubernetes/blob/64c099d67069f85f2b9b78d7d12fd1a92fcc3d75/test/e2e/scheduling/priorities.go#L464) of `balancePodLabel`. Every call to `testutils.StartPods` then modifies `balancePodLabel` and disallows `balancePodLabel` to be used for listing all pods created for memory balancing.

Comment (alculquicondor) [reply test/e2e/scheduling/predicates.go:890]: sg

File: test/e2e/scheduling/priorities.go (hunk 4 above)
Comment (ingvagabund) [reply test/e2e/scheduling/priorities.go]: Done

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm

Thanks a lot for all the debugging and commitment to solve this flaky!
