### PR TITLE
Mount kubelet root directory as executable in GCI

### LINKED ISSUE #33315: GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working mysql cluster [Feature:PetSet])
GCI Test Failing: (kubernetes-gci-gce-alpha-features-release-1.4) ([k8s.io] PetSet [Slow] [Feature:PetSet] [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet] should creating a working mysql cluster [Feature:PetSet])

https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-features-release-1.4

### PR DESCRIPTION
**Pull request by vishh**
Fixes #33315 and #33318

This PR is isolated to GCI distro. Without this rather simple patch,
PetSets won't work with GCI. Hence requesting a cherry-pick.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33345)

### CODE REVIEW

**Comment by vishh** [comment]
cc @foxish

**Comment by foxish** [comment]
@vishh, We will need to get this reviewed quickly if we want to do the cherrypick into 1.4.

**Comment by pwittrock** [comment]
I am headed to bed.  Don't get blocked on me.

**Comment by vishh** [comment]
I ran the petset tests manualy and they pass. This is ready to go

<details>
hack/ginkgo-e2e.sh --ginkgo.focus="Deploy clustered applications"
• [SLOW TEST:283.685 seconds]                                                                                                     
[k8s.io] PetSet [Slow] [Feature:PetSet]                                                                                           
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:801                         
  [k8s.io] Deploy clustered applications [Slow] [Feature:PetSet]                                                                  
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:801                       
    should creating a working mysql cluster [Feature:PetSet]                                                                      
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/petset.go:244                                  
------------------------------                                                                                                    
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                                                                
Ran 3 of 406 Specs in 679.885 seconds                                                                                             
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 403 Skipped PASS                                                                    
                                                                                                                                  
Ginkgo ran 1 suite in 11m20.124515019s                                                                                            
Test Suite Passed                           
</details>

File: cluster/gce/gci/configure-helper.sh [hunk 1]
```diff
@@ -1120,6 +1120,13 @@ function start-rescheduler {
   fi
 }
 
+# Setup volumes directory for kubelet.
+function setup-volumes-dir {
```
Comment (thockin) [inline cluster/gce/gci/configure-helper.sh]: This name is a lie.  it's about the kubelet dir, not just volumes...

**Review by thockin — APPROVED** [review]
I'm gonna LGTM this, but the name hould be changed,

File: cluster/gce/gci/configure-helper.sh (hunk 1 above)
Comment (vishh) [inline cluster/gce/gci/configure-helper.sh]: Ok. Changing the name.

Comment (vishh) [inline cluster/gce/gci/configure-helper.sh]: Done

**Comment by maisem** [comment]
LGTM - looks like @vishh beat me to it :+1:

File: cluster/gce/gci/configure-helper.sh [hunk 2]
```diff
@@ -1120,6 +1120,13 @@ function start-rescheduler {
   fi
 }
 
+# Setup working directory for kubelet.
+function setup-kubelet-dir {
+    echo "Making /var/lib/kubelet executable for kubelet"
+    mount --bind /var/lib/kubelet /var/lib/kubelet/
+    mount -B -o remount,exec,suid,dev /var/lib/kubelet
```
Comment (Amey-D) [inline cluster/gce/gci/configure-helper.sh]: I'd suggest using "--bind" instead of "-B" for consistency and readability.

**Comment by Amey-D** [comment]
LGTM

File: cluster/gce/gci/configure-helper.sh (hunk 2 above)
Comment (vishh) [inline cluster/gce/gci/configure-helper.sh]: Ack. I will clean it up in a separate patch to avoid having to rebase the cherry-pick patch.

**Comment by vishh** [comment]
Thanks for the review everyone!!

**Comment by bprashanth** [comment]
> PetSets won't work with GCI. Hence requesting a cherry-pick.

Hmm, yes it will.
This won't work: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    foo: bar
spec:
  terminationGracePeriodSeconds: 0
  hostNetwork: true
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sh
      - -ec
      - |
        echo date > /tmp/foo/date.sh
        chmod -c 777 /tmp/foo/date.sh
        while true; do /tmp/foo/date.sh || true; sleep 1; done
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /tmp/foo
      name: test
  volumes:
  - name: test
    emptyDir: {}
  restartPolicy: Always
```

**Comment by jessfraz** [comment]
does this need to be cherry-picked for 1.4.1

**Comment by bprashanth** [comment]
I hope it made it into 1.4 proper (https://github.com/kubernetes/kubernetes/pull/33356), if not, I'd say yes

**Comment by jessfraz** [comment]
so weird shouldnt the bot remove the cherry-pick candidate label if its in that branch?

**Comment by foxish** [comment]
The commit ID changed, that may be why it missed this.

**Comment by jessfraz** [comment]
ah ok awesome :)

On Thu, Oct 6, 2016 at 1:31 PM, Anirudh Ramanathan <notifications@github.com
