### PR TITLE
test(kuberuntime): deflake TestRemoveContainer

### LINKED ISSUE #94194: TestRemoveContainer flakes on container log file removal
https://github.com/kubernetes/kubernetes/pull/93333 modified container log file removal in a way that made TestRemoveContainer flaky

```
=== RUN   TestRemoveContainer
    kuberuntime_container_test.go:84: 
        	Error Trace:	kuberuntime_container_test.go:84
        	Error:      	Not equal: 
        	            	expected: []string{"/var/log/pods/new_bar_12345678/foo/0.log", "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405", "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"}
        	            	actual  : []string{"/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405", "/var/log/pods/new_bar_12345678/foo/0.log", "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 ([]string) (len=3) {
        	            	+ (string) (len=56) "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405",
        	            	  (string) (len=40) "/var/log/pods/new_bar_12345678/foo/0.log",
        	            	- (string) (len=56) "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405",
        	            	  (string) (len=60) "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"
        	Test:       	TestRemoveContainer
--- FAIL: TestRemoveContainer (0.00s)
```

See https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestRemoveContainer

Note that the flake is masked by the fact that the unit test job will retry tests up to 3 times. With [that disabled](https://github.com/kubernetes/kubernetes/pull/93605), this flake is quite pronounced: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93605/pull-kubernetes-bazel-test/1297588838339710977

A fix for the flake is in https://github.com/kubernetes/kubernetes/pull/94185, but it's unclear to me whether it is correct that the removal order is non-deterministic.

/assign @piosz @dchen1107 
/sig node
/milestone v1.19
/priority critical-urgent

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: knight42 <anonymousknight96@gmail.com>

**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93605/pull-kubernetes-bazel-test/1297588838339710977
```
=== RUN   TestRemoveContainer
    kuberuntime_container_test.go:84: 
        	Error Trace:	kuberuntime_container_test.go:84
        	Error:      	Not equal: 
        	            	expected: []string{"/var/log/pods/new_bar_12345678/foo/0.log", "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405", "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"}
        	            	actual  : []string{"/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405", "/var/log/pods/new_bar_12345678/foo/0.log", "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,4 +1,4 @@
        	            	 ([]string) (len=3) {
        	            	+ (string) (len=56) "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405",
        	            	  (string) (len=40) "/var/log/pods/new_bar_12345678/foo/0.log",
        	            	- (string) (len=56) "/var/log/pods/new_bar_12345678/foo/0.log.20060102-150405",
        	            	  (string) (len=60) "/var/log/containers/bar_new_foo-bar_new_12345678_0_foo_0.log"
        	Test:       	TestRemoveContainer
```

The paths are not sorted before verifying, so the test becomes flaky.

**Which issue(s) this PR fixes**:

Part of #93605 
Fixes #94194 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go [hunk 1]
```diff
@@ -79,9 +80,14 @@ func TestRemoveContainer(t *testing.T) {
 
 	err = m.removeContainer(containerID)
 	assert.NoError(t, err)
-	// Verify container log is removed
 
-	assert.Equal(t, []string{expectedContainerLogPath, expectedContainerLogPathRotated, expectedContainerLogSymlink}, fakeOS.Removes)
+	actualRemoves := make([]string, 0, len(fakeOS.Removes))
```
Comment (knight42) [inline pkg/kubelet/kuberuntime/kuberuntime_container_test.go:84]: looks like we could simply sort `fakeOS.Removes` in place.

Comment (dims) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go:84]: @knight42 assert.ElementsMatch?

Comment (knight42) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go:84]: Thanks for pointing it out! Fixed.

File: pkg/kubelet/kuberuntime/kuberuntime_container_test.go [hunk 2]
```diff
@@ -79,9 +79,12 @@ func TestRemoveContainer(t *testing.T) {
 
 	err = m.removeContainer(containerID)
 	assert.NoError(t, err)
-	// Verify container log is removed
 
-	assert.Equal(t, []string{expectedContainerLogPath, expectedContainerLogPathRotated, expectedContainerLogSymlink}, fakeOS.Removes)
+	// Verify container log is removed.
+	// We could not predict the order of `fakeOS.Removes`, so we use `assert.ElementsMatch` here.
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_container_test.go:84]: is the remove order really non-deterministic? that's surprising to me

Comment (knight42) [reply pkg/kubelet/kuberuntime/kuberuntime_container_test.go:84]: @liggitt while we are cleaning the log files, we called `FakeOS.Glob` https://github.com/kubernetes/kubernetes/blob/14a11060a0775ed609f0810898ebdbe737c59441/pkg/kubelet/logs/container_log_manager.go#L196, which would iterate `FakeOS.Files` https://github.com/kubernetes/kubernetes/blob/14a11060a0775ed609f0810898ebdbe737c59441/pkg/kubelet/container/testing/os.go#L123-L127, and `FakeOS.Files` is a map https://github.com/kubernetes/kubernetes/blob/14a11060a0775ed609f0810898ebdbe737c59441/pkg/kubelet/container/testing/os.go#L36, so the order is non-deterministic after #93333.

**Comment by liggitt** [comment]
thanks makes sense, thanks for the details.

/lgtm
/approve
/milestone v1.19

**Comment by knight42** [comment]
/hold
Perhaps we should wait for #94184 to be solved?
