### PR TITLE
kubeadm: fix nil pointer when etcd member is already removed

### LINKED ISSUE #2912: ci-kubernetes-e2e-kubeadm-kinder-1-26-on-1-25 failed for nil pointer when removing etcd member
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-1-26-on-1-25/1687241264644231168

```
I0803 23:57:29.524325   11049 etcd.go:350] Member was already removed, because member 40fd14fa28910cab was not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a1d5fe]
goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/util/etcd.(*Client).RemoveMember(0xc00058e040, 0x40fd14fa28910cab)
	cmd/kubeadm/app/util/etcd/etcd.go:363 +0x11e
k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd.RemoveStackedEtcdMemberFromCluster({0x2230e90, 0xc000602d00}, 0xc00062c000)
	cmd/kubeadm/app/phases/etcd/local.go:129 +0x41e
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/reset.runRemoveETCDMemberPhase({0x1ddbbe0?, 0xc0004ece70?})
	cmd/kubeadm/app/cmd/phases/reset/removeetcdmember.go:66 +0x28a
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0xc0004c78c0)
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:259 +0x134
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(...)
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0xc0000d53b0, {0xc0005740a0, 0x0, 0x2})
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:232 +0x3e3
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdReset.func1(0xc0006d8000?, {0xc0005740a0?, 0x2?, 0x2?})
	cmd/kubeadm/app/cmd/reset.go:183 +0x26
github.com/spf13/cobra.(*Command).execute(0xc0006d8000, {0xc000574080, 0x2, 0x2})
	vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000134600)
	vendor/github.com/spf13/cobra/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x21fb3c0?)
	vendor/github.com/spf13/cobra/command.go:968 +0x19
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	cmd/kubeadm/app/kubeadm.go:50 +0x15d
main.main()
	cmd/kubeadm/kubeadm.go:25 +0x19
Error: failed to exec action kubeadm-reset: exit status 2
 exit status 1
```

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- Code was added in https://github.com/kubernetes/kubernetes/pull/117724

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/cmd/kubeadm/app/util/etcd/etcd.go#L351-L354

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2912

#### Special notes for your reviewer:

- [ ] TODO: this may need cherry-picks to old versions

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fix nil pointer when etcd member is already removed
```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
thanks @pacoxu 
/lgtm

**Review by liangyuanpeng — APPROVED** [review]
LGTM

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 1]
```diff
@@ -362,8 +362,11 @@ func (c *Client) RemoveMember(id uint64) ([]Member, error) {
 
 	// Returns the updated list of etcd members
 	ret := []Member{}
-	for _, m := range resp.Members {
-		ret = append(ret, Member{Name: m.Name, PeerURL: m.PeerURLs[0]})
+	if resp != nil {
+		for _, m := range resp.Members {
+			ret = append(ret, Member{Name: m.Name, PeerURL: m.PeerURLs[0]})
+		}
+
```
Comment (chendave) [inline cmd/kubeadm/app/util/etcd/etcd.go:369]: pls consider to remove this blank line

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 2]
```diff
@@ -362,8 +362,11 @@ func (c *Client) RemoveMember(id uint64) ([]Member, error) {
 
 	// Returns the updated list of etcd members
 	ret := []Member{}
-	for _, m := range resp.Members {
-		ret = append(ret, Member{Name: m.Name, PeerURL: m.PeerURLs[0]})
+	if resp != nil {
```
Comment (chendave) [inline cmd/kubeadm/app/util/etcd/etcd.go:365]: the code change here LGTM, but I don't understand why it cannot find the member ID from the endpoint,  the [log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-1-26-on-1-25/1687241264644231168/build-log.txt) doesn't provide any clue for this, and there is no such code to remove this member in any other function from kubeadm? (maybe I miss something)

it is rare to see this error from the serial of test, I guess it might be related to etcd itself, maybe the member is not actual removed but just something wrong happened in the etcd.

**Review by chendave — COMMENTED** [review]
LGTM

**Comment by neolit123** [comment]
what is the status of this?
do we need to backport it?

**Comment by chendave** [comment]
> do we need to backport it?

+1 to backport this.

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: we wrap the assignment of resp in a backoff. i think there could never be a case where resp is nil, but the err returned from the backoff is not nil.

i guess my point is that resp == nil cannot happen after this check:

```
if err != nil {
	return nil, lastError
}
```

i could be missing something, but to me it seems the change is not needed.

@SataQiu PTAL as well if you have some time.

Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: /cc @dlipovetsky 

> Code was added in kubeadm: Make etcd member removal idempotent #117724

Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: @dlipovetsky yet
https://github.com/kubernetes/kubeadm/issues/2912 seems like an actual problem

Comment (SataQiu) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]:
```go
if errors.Is(rpctypes.ErrMemberNotFound, err) {
	klog.V(5).Infof("Member was already removed, because member %s was not found", strconv.FormatUint(id, 16))
	return true, nil
}
```
When err is `ErrMemberNotFound`, resp will be nil.

Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: ok, it seems return of `true, nil` means we can no longer process resp.
so @pacoxu logic is correct. @chendave can you please check of you have other concerns?

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:369]: +1, but we can also just `if resp == nil .... return`

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 2 above)
Comment (chendave) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: the response can be nil only in case that member cannot be found or it's already be removed. 

https://github.com/etcd-io/etcd/blob/main/server/etcdserver/server.go#L165-L168

>	// RemoveMember attempts to remove a member from the cluster. It will
	// return ErrIDRemoved if member ID is removed from the cluster, or return
	// ErrIDNotFound if member ID is not in the cluster.
	RemoveMember(ctx context.Context, id uint64) ([]*membership.Member, error)

take a look at this as well, 
https://github.com/etcd-io/etcd/blob/c1b96473dbdc2b8fa4401d7e00ff57bdbd89b66e/client/v3/cluster.go#L101

> func (c *cluster) MemberRemove(ctx context.Context, id uint64) (*MemberRemoveResponse, error) {
	r := &pb.MemberRemoveRequest{ID: id}
	resp, err := c.remote.MemberRemove(ctx, r, c.callOpts...)
	if err != nil {
		return nil, toErr(ctx, err)
	}
	return (*MemberRemoveResponse)(resp), nil
}



My question how we can hit the situation given that we haven't removed it in somewhere else. 

But for whatever the reason this does happen, then I agree this change is fine.


And the alternative is, we can return the error instead of the `nil` from here as the error is not expected unless it's clear  there is somewhere the member is remove already.

```
		if errors.Is(rpctypes.ErrMemberNotFound, err) {
			klog.V(5).Infof("Member was already removed, because member %s was not found", strconv.FormatUint(id, 16))
			return true, nil     // return true, err instead!!!
		}
````

Comment (neolit123) [reply cmd/kubeadm/app/util/etcd/etcd.go:365]: well, looks like this wasn't on hold and it merged. we should backport it to 1.28 and older releases. 

> And the alternative is, we can return the error instead of the nil from here as the error is not expected unless it's clear there is somewhere the member is remove already.

i don't have all the answers but IIRC, this was also the old behavior - i.e. don't return error if member was already removed.

**Comment by dlipovetsky** [comment]
Thanks for fixing this @pacoxu, @neolit123, and @chendave! :pray: 

When I worked at this code last, I found it hard to piece together what values the etcd client `MemberRemove`  returns under different circumstances. I felt it was obscure to begin with, but obscured even more by the gRPC layer. I had to dig into the etcd server code to get answers.

I think we could have found this bug with an integration test of `RemoveMember` that mocked `cli.MemberRemove` to return every possible combination of return values.  Even though the actual etcd client might not return every such combination, we want our functions to gracefully handle every combination. WDYT?

**Comment by neolit123** [comment]
> I think we could have found this bug with an integration test of RemoveMember that mocked cli.MemberRemove to return every possible combination of return values. Even though the actual etcd client might not return every such combination, we want our functions to gracefully handle every combination. WDYT?

i think we can add such a test yes. but only for k/k master IMO.
(i.e. don't backport the test)

**Comment by chendave** [comment]
@neolit123 How we judge which remote branch should be maintained? I saw those code is imported since 1.14, do we need cherry-pick until 1.14? 

https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/util/etcd/etcd.go

https://github.com/kubernetes/kubernetes/blob/c8b135d0b49c44554ed5b78878f15f09cab350b6/cmd/kubeadm/app/util/etcd/etcd.go#L240-L245

**Comment by neolit123** [comment]
> @neolit123 How we judge which remote branch should be maintained? I saw those code is imported since 1.14, do we need cherry-pick until 1.14?
> 
> https://github.com/kubernetes/kubernetes/blob/release-1.14/cmd/kubeadm/app/util/etcd/etcd.go
> 
> https://github.com/kubernetes/kubernetes/blob/c8b135d0b49c44554ed5b78878f15f09cab350b6/cmd/kubeadm/app/util/etcd/etcd.go#L240-L245

see the releases listed here:
https://kubernetes.io/releases/
they have end of date too. e.g. 1.24 is being dropped soon.

**Comment by pacoxu** [comment]
Thanks @neolit123  for the cherry-picks.
