### PR TITLE
remove retry operation on attach/detach  azure disk

### LINKED ISSUE #70567: retry  azure disk attach operation produces too many API calls
**What happened**:
retry  azure disk attach operation produce too many API calls
Not the default `cloudProviderBackoffRetries` value is 6 which means if AttachDisk operation failed, it will retry 6 more times, when disk quota is full on a VM, it produces too many API calls. Retry attach disk behavior is not necessary since it AttachVolume operation fails, k8s attachdetach-controller will retry once a minute until it succeeds.

default setting in `/etc/kubernetes/azure.json`
```
   "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10, v1.11, v1.12
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig azure
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
remove retry operation on attach/detach azure disk, switch to use k8s attach-detach controller which would control retry attach/detach disk

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70567

**Special notes for your reviewer**:
retry  azure disk attach operation produce too many API calls
Now the default `cloudProviderBackoffRetries` value is 6 which means if AttachDisk operation failed, it will retry 6 more times, when disk quota is full on a VM, it produces too many API calls. Retry attach disk behavior is **not** necessary since it AttachVolume operation fails, k8s attachdetach-controller will retry once a minute until it succeeds.

default setting in `/etc/kubernetes/azure.json` now:
```
   "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
```
**Does this PR introduce a user-facing change?**:
```
NONE
```

**Release note**:
```
remove retry operation on attach/detach azure disk
```

/sig azure
/assign @feiskyer 
@jackfrancis @khenidak @brendandburns

### CODE REVIEW

File: pkg/cloudprovider/providers/azure/azure_controller_standard.go [hunk 1]
```diff
@@ -76,25 +76,16 @@ func (as *availabilitySet) AttachDisk(isManagedDisk bool, diskName, diskURI stri
...
-		}
-	}
-	if err != nil {
+	if _, err := as.VirtualMachinesClient.CreateOrUpdate(ctx, nodeResourceGroup, vmName, newVM); err != nil {
 		glog.Errorf("azureDisk - azure attach failed, err: %v", err)
 		detail := err.Error()
 		if strings.Contains(detail, errLeaseFailed) || strings.Contains(detail, errDiskBlobNotFound) {
 			// if lease cannot be acquired or disk not found, immediately detach the disk and return the original error
-			glog.Infof("azureDisk - err %s, try detach", detail)
+			glog.V(2).Info("azureDisk - err %s, try detach", detail)
```
Comment (feiskyer) [inline pkg/cloudprovider/providers/azure/azure_controller_standard.go]: nit: Also add diskName into the log.

File: pkg/cloudprovider/providers/azure/azure_controller_standard.go [hunk 2]
```diff
@@ -76,25 +76,16 @@ func (as *availabilitySet) AttachDisk(isManagedDisk bool, diskName, diskURI stri
...
 			as.DetachDiskByName(diskName, diskURI, nodeName)
 		}
 	} else {
-		glog.V(4).Info("azureDisk - azure attach succeeded")
+		glog.V(2).Info("azureDisk - azure attach succeeded")
```
Comment (feiskyer) [inline pkg/cloudprovider/providers/azure/azure_controller_standard.go]: nit: same here and below

**Comment by jackfrancis** [comment]
code lgtm

**Review by feiskyer — COMMENTED** [review]
/lgtm
