### PR TITLE
Fix DNS add-on on hyperkube-based setups

### LINKED ISSUE #19864: single-node/containerized hyperkube: add master IP to server.cert as SAN
Hello,

Using 81054463 and `cluster/images/hyperkube/turnup.sh` gives a nice single node cluster, but Deis v2 alpha can't talk to the apiserver, because it has a wrong certificate ([see](https://github.com/deis/router/issues/62#issuecomment-167843372)). 

By locally vandalizing `make-ca-cert.sh` (or by doing a bit nicer through adding a second argument to make-ca-certs in `setup-files.sh` and adding an env var to `master.json` with the master's IP) can work around this, but the problem is that using `$(hostname -i)` is fragile and will result in 127.0.1.1 with "host networking", and at best in a docker 172.17.0.0/16 IP.

However, it could be that I (the Deis devs) misunderstood something, and this is a bug in Deis. Or that this is simply an unworkable setup. (Their current config assumes GCE.)

### PR DESCRIPTION
**Pull request by andreikop**
When dockered hyperkube-based setup is used, kube2sky tries to access API server via `10.0.0.1` IP.
However API server TLS certificate doesn't contain this IP in the list of Subject Alternative Names.

kube2sky rejects the certificate and fails to get cluster information. DNS add-on pod keeps been restarted.

This patch adds API server IP to the list of SANS. Now KubeDNS works for me.
The idea was borrowed from Ubuntu scripts.

Fixes #19864

### CODE REVIEW

**Comment by luxas** [comment]
I was doing/fixing the same thing here also... Let's merge your patch first :)
@fgrzadkowski This should be LGTM

**Comment by hlamer** [comment]
Close #19864 when merged

File: cluster/images/hyperkube/setup-files.sh [hunk 1]
```diff
@@ -23,6 +23,8 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
+EXTRA_SANS=$1
```
Comment (fgrzadkowski) [inline cluster/images/hyperkube/setup-files.sh]: Please add a comment what this variables keeps.

**Comment by fgrzadkowski** [comment]
@hlamer Just a minor comment. Otherwise it LGTM.

**Comment by hlamer** [comment]
@fgrzadkowski, I've added some comments and rebased to current master

**Comment by fgrzadkowski** [comment]
LGTM. Thanks for the fix!

**Comment by luxas** [comment]
@k8s-bot test this please

**Comment by luxas** [comment]
Can someone add back the `lgtm` and `ok-to-merge` labels?

**Comment by gopinatht** [comment]
@hlamer This PR is a little vital to the work I am doing. Is there anything I can do to help expedite it?

**Comment by hlamer** [comment]
@gopinatht, @fgrzadkowski will probably merge it soon. For now you can just cherry-pick my commit to your branch.
