### PR TITLE
Fixing Potential Race Condition in EndpointSlice Controller.

### LINKED ISSUE #85353: EndpointSliceController does not react to updated or deleted EndpointsSlice objects
**What happened**:
1. Create a service+pod
2. Observe an endpointslice get created with a `endpointslice.kubernetes.io/managed-by=endpointslice-controller.k8s.io` label (as expected
3. Manually modify the endpointslice to change the data, it is not corrected automatically
4. Delete the endpoint slice, it is not recreated automatically
5. Recreate the endpoint slice with a `endpointslice.kubernetes.io/managed-by=custom` label, it is not populated automatically (which is correct)
6. Change the label value to endpointslice-controller.k8s.io, it is still not populated automatically
7. Once I modify the service, the endpoint slice is updated

**What you expected to happen**:

The endpointsslice controller to react to deletions/updates of endpointsslice objects

cc @robscott @thockin

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This adds a new EndpointSlice tracker to keep track of the expected resource versions of EndpointSlices associated with each Service managed by the EndpointSlice controller. This should prevent a potential race where a syncService call could happen with an incomplete view of EndpointSlices if additions or deletions hadn't fully propagated to the cache yet. Additionally, this ensures that external changes to EndpointSlices will be handled by the EndpointSlice controller.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/85353

**Does this PR introduce a user-facing change?**:
```release-note
Fix EndpointSlice controller race condition and ensure that it handles external changes to EndpointSlices.
```

/sig network
/priority important-soon
/cc @liggitt @bowei

### CODE REVIEW

File: pkg/controller/endpointslice/endpointslice_controller.go [hunk 1]
```diff
@@ -343,6 +355,49 @@ func (c *Controller) onServiceDelete(obj interface{}) {
...
+
+// onEndpointSliceUpdate queues a sync for the relevant Service for a sync if the
+// EndpointSlice resource version does not match the expected version in the
+// endpointSliceTracker or the managed-by value of the EndpointSlice has changed
+// from or to this controller.
+func (c *Controller) onEndpointSliceUpdate(prevObj, obj interface{}) {
+	prevEndpointSlice := obj.(*discovery.EndpointSlice)
+	endpointSlice := obj.(*discovery.EndpointSlice)
+	if managedByChanged(prevEndpointSlice, endpointSlice) || (managedByController(endpointSlice) && !c.endpointSliceTracker.UpToDate(endpointSlice)) {
+		c.queueServiceForEndpointSlice(endpointSlice)
```
Comment (liggitt) [inline pkg/controller/endpointslice/endpointslice_controller.go]: if the old and new endpoint slice were both managed by us, but the service they referenced changed, don't we need to queue the old and new service?

Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go]: That's not a use case I'd planned for. The controller itself will never change the Service an EndpointSlice belongs to. Of course this could happen if someone were intentionally messing with EndpointSlices, but they could also break other things as well. With that said, the `UpToDate` check would fail if the EndpointSlice service had been changed since it would not expect that EndpointSlice name or resource version for the given Service.

**Comment by robscott** [comment]
For better visibility:
/assign @bowei @liggitt

File: pkg/controller/endpointslice/endpointslice_controller.go [hunk 2]
```diff
@@ -343,6 +355,49 @@ func (c *Controller) onServiceDelete(obj interface{}) {
 	c.queue.Add(key)
 }
 
+// onEndpointSliceAdd queues a sync for the relevant Service for a sync if the
+// EndpointSlice resource version does not match the expected version in the
+// endpointSliceTracker.
+func (c *Controller) onEndpointSliceAdd(obj interface{}) {
+	endpointSlice := obj.(*discovery.EndpointSlice)
+	if managedByController(endpointSlice) && !c.endpointSliceTracker.UpToDate(endpointSlice) {
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_controller.go]:
```golang
if endpointSlice == nil {
  t.Errorf(...)
  return
}
```

File: pkg/controller/endpointslice/endpointslice_tracker.go [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+
+	rrv := est.relatedResourceVersions(endpointSlice)
+	_, ok := rrv[endpointSlice.Name]
+	return ok
+}
+
+// UpToDate returns true if this endpointSliceTracker has a resource version for
+// the provided EndpointSlice and it matches the resource version of the
+// provided EndpointSlice.
+func (est *endpointSliceTracker) UpToDate(endpointSlice *discovery.EndpointSlice) bool {
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_tracker.go]: common term is "stale" (which is negation)

Comment (bowei) [reply pkg/controller/endpointslice/endpointslice_tracker.go]: UpToDate and Update are awfully close

File: pkg/controller/endpointslice/endpointslice_tracker.go [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+
+	rrv := est.relatedResourceVersions(endpointSlice)
+	delete(rrv, endpointSlice.Name)
+}
+
+// relatedResourceVersions returns the set of resource versions tracked for the
+// Service corresponding to the provided EndpointSlice. If no resource versions
+// are currently tracked for this service, an empty set is initialized.
+func (est *endpointSliceTracker) relatedResourceVersions(endpointSlice *discovery.EndpointSlice) endpointSliceResourceVersions {
+	serviceNN := getServiceNN(endpointSlice)
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_tracker.go]: try to avoid two map lookups?

```
var (
  vers endpointSliceResourceVersions
  ok bool
  )

if vers, ok = est.resourceVersionsByService[serviceNN]; !ok {
  vers = endpointSliceResourceVersions{}
  est.resourceVersionsByService[serviceNN] = vers
}
return vers

File: pkg/controller/endpointslice/endpointslice_tracker_test.go [hunk 5]
```diff
@@ -0,0 +1,179 @@
...
+	epSlice1DifferentNS.Namespace = "ns2"
+
+	epSlice1DifferentService := epSlice1.DeepCopy()
+	epSlice1DifferentService.Labels[discovery.LabelServiceName] = "svc2"
+
+	epSlice1DifferentRV := epSlice1.DeepCopy()
+	epSlice1DifferentRV.ResourceVersion = "rv2"
+
+	testCases := map[string]struct {
+		endpointSliceTracker     *endpointSliceTracker
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_tracker_test.go]: endpointSlice is redundant (tracker, update, checks, etc)

File: pkg/controller/endpointslice/endpointslice_tracker_test.go [hunk 6]
```diff
@@ -0,0 +1,179 @@
...
+			expectHas:                true,
+			expectUpToDate:           false,
+		},
+	}
+
+	for name, tc := range testCases {
+		t.Run(name, func(t *testing.T) {
+			tc.endpointSliceTracker.Update(tc.endpointSliceUpdateParam)
+			if tc.endpointSliceTracker.Has(tc.endpointSliceChecksParam) != tc.expectHas {
+				t.Errorf("Expected Has result to be %t, got %t", tc.expectHas, tc.endpointSliceTracker.Has(tc.endpointSliceChecksParam))
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_tracker_test.go]: typical way to write this:
```
t.Errorf("tc.endpointSliceTracker.Has(%+v) = %t; want %t", ...)
```

File: pkg/controller/endpointslice/endpointslice_tracker_test.go [hunk 7]
```diff
@@ -0,0 +1,179 @@
...
+			endpointSliceUpdateParam: epSlice1,
+			endpointSliceChecksParam: epSlice1DifferentRV,
+			expectHas:                true,
+			expectUpToDate:           false,
+		},
+	}
+
+	for name, tc := range testCases {
+		t.Run(name, func(t *testing.T) {
+			tc.endpointSliceTracker.Update(tc.endpointSliceUpdateParam)
```
Comment (bowei) [inline pkg/controller/endpointslice/endpointslice_tracker_test.go]: shouldn't esTracker1 made new in the loop, as this creates state that leaks between t.Run instances?

File: pkg/controller/endpointslice/endpointslice_controller.go [hunk 8]
```diff
@@ -343,6 +355,49 @@ func (c *Controller) onServiceDelete(obj interface{}) {
...
+func (c *Controller) onEndpointSliceDelete(obj interface{}) {
+	endpointSlice := obj.(*discovery.EndpointSlice)
+	if managedByController(endpointSlice) && c.endpointSliceTracker.Has(endpointSlice) {
+		c.queueServiceForEndpointSlice(endpointSlice)
+	}
+}
+
+// queueServiceForEndpointSlice attempts to queue the corresponding Service for
+// the provided EndpointSlice.
+func (c *Controller) queueServiceForEndpointSlice(endpointSlice *discovery.EndpointSlice) {
```
[the remark this answers is not in the document]
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go]: Yeah, I was trying to differentiate between what we're already doing for Pods where all related Services get queued up when a Pod changes. `Service` is potentially redundant here as the only queue referenced in this controller is the `Service` queue. I just tend to favor verbose function names so there's no question what is happening.

File: pkg/controller/endpointslice/endpointslice_tracker.go (hunk 3 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_tracker.go]: Stale is much better here, thanks, will update that naming.

File: pkg/controller/endpointslice/endpointslice_tracker_test.go (hunk 5 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_tracker_test.go]: good catch, thanks!

File: pkg/controller/endpointslice/endpointslice_tracker.go (hunk 4 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_tracker.go]: Fixed, thanks!

File: pkg/controller/endpointslice/endpointslice_tracker_test.go (hunk 6 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_tracker_test.go]: That is better, thanks!

File: pkg/controller/endpointslice/endpointslice_tracker_test.go (hunk 7 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_tracker_test.go]: I think initially I'd thought of doing some kind of sequential test or something, but obviously that's not what ended up happening, thanks for catching that!

File: pkg/controller/endpointslice/endpointslice_controller.go [hunk 9]
```diff
@@ -343,6 +355,49 @@ func (c *Controller) onServiceDelete(obj interface{}) {
...
+	}
+}
+
+// onEndpointSliceUpdate queues a sync for the relevant Service for a sync if the
+// EndpointSlice resource version does not match the expected version in the
+// endpointSliceTracker or the managed-by value of the EndpointSlice has changed
+// from or to this controller.
+func (c *Controller) onEndpointSliceUpdate(prevObj, obj interface{}) {
+	prevEndpointSlice := obj.(*discovery.EndpointSlice)
+	endpointSlice := obj.(*discovery.EndpointSlice)
```
[the remark this answers is not in the document]
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go]: Added, thanks!

File: pkg/controller/endpointslice/endpointslice_controller.go (hunk 2 above)
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go]: Fixed, thanks!

File: pkg/controller/endpointslice/endpointslice_controller.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (robscott) [reply pkg/controller/endpointslice/endpointslice_controller.go]: I haven't really thought of a better name here. Open to alternatives. I think the `ForEndpointSlice` provides useful context/differentiation here, but I can still remove that if you'd prefer.
