### PR TITLE
kubeadm should ignore cgroup driver check on Windows node

### LINKED ISSUE #97759: kubelet: don't check for the Docker cgroup driver on Windows
**What happened**:

I have a Kubernetes Cluster with 2 Windows Server 2019 Core VMs as worker nodes. I upgraded first the cluster, and then the first Windows node following the docs here: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/

Every step ran without issue, but the kubelet service was not started. This was not immediately obvious, since "restart-service kubelet" does not propagate the error. I think "start-service kubelet" would be better advice.

The logs said: 

```
F0106 11:58:32.006122   17508 server.go:269] failed to run Kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"
```

After changing the value of cgroupDriver manually in ```c:\var\lib\kubelet\config.yaml``` from "systemd" to "cgroupfs", the kubelet started successfully.

**What you expected to happen**:

One of 2 things: Either the Windows upgrade docs telling me what I need to do to fix this, or the kubeadm not breaking the configuration for windows in the first place.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a windows node to a Kubernetes v1.19 cluster via kubeadm
2. Upgrade the cluster via kubeadm
3. Upgrade the Windows node following the docs [here](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/upgrading-windows-nodes/)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows Server 2019 Core
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug
/sig windows
/sig cluster-lifecycle
/area kubeadm

**What this PR does / why we need it**:

> kubeadm doesn't do anything about cgroup drivers on Windows because cgroups don't exist on Windows.
>  ideally the kubelet checks about this should be skipped entirely in dockershim for non-Linux.

**Which issue(s) this PR fixes**:

Fixes #97759

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/remove-area kubeadm
/remove-sig cluster-lifecycle

**Comment by neolit123** [comment]
i think it should be:
```
if runtime.GOOS == "linux" {
	// NOTE: cgroup driver is only detectable in docker 1.11+
	cgroupDriver := defaultCgroupDriver
	dockerInfo, err := ds.client.Info()
	klog.Infof("Docker Info: %+v", dockerInfo)
	if err != nil {
		klog.Errorf("Failed to execute Info() call to the Docker client: %v", err)
		klog.Warningf("Falling back to use the default driver: %q", cgroupDriver)
	} else if len(dockerInfo.CgroupDriver) == 0 {
		klog.Warningf("No cgroup driver is set in Docker")
		klog.Warningf("Falling back to use the default driver: %q", cgroupDriver)
	} else {
		cgroupDriver = dockerInfo.CgroupDriver
	}
	if len(kubeCgroupDriver) != 0 && kubeCgroupDriver != cgroupDriver {
		return nil, fmt.Errorf("misconfiguration: kubelet cgroup driver: %q is different from docker cgroup driver: %q", kubeCgroupDriver, cgroupDriver)
	}
	klog.Infof("Setting cgroupDriver to %s", cgroupDriver)
	ds.cgroupDriver = cgroupDriver
}
```

if dockershim complains about an empty `ds.cgroupDriver` on Windows it should be fixed too.

**Review by neolit123 — COMMENTED** [review]
this looks right to me. SIG Node owners can approve.
/lgtm

**Comment by pacoxu** [comment]
@neolit123  updated.

**Comment by neolit123** [comment]
@kubernetes/sig-windows-bugs

**Review by hasheddan — COMMENTED** [review]
/priority important-soon

File: pkg/kubelet/dockershim/docker_service.go [hunk 1]
```diff
@@ -254,24 +255,27 @@ func NewDockerService(config *ClientConfig, podSandboxImage string, streamingCon
...
+			klog.Warningf("No cgroup driver is set in Docker")
+			klog.Warningf("Falling back to use the default driver: %q", cgroupDriver)
+		} else {
+			cgroupDriver = dockerInfo.CgroupDriver
+		}
+		if len(kubeCgroupDriver) != 0 && kubeCgroupDriver != cgroupDriver {
+			return nil, fmt.Errorf("misconfiguration: kubelet cgroup driver: %q is different from docker cgroup driver: %q", kubeCgroupDriver, cgroupDriver)
+		}
+		klog.Infof("Setting cgroupDriver to %s", cgroupDriver)
+		ds.cgroupDriver = cgroupDriver
```
Comment (jayunit100) [inline pkg/kubelet/dockershim/docker_service.go:276]: Can we log that we are skipping cgroup checks because it's windows ?

That will help make the kubelet logs for windows nodes easier to follow .

Comment (jayunit100) [reply pkg/kubelet/dockershim/docker_service.go:276]: And also remind us to maybe do some equivalent steps at some point down the road , for windows

**Review by jayunit100 — CHANGES_REQUESTED** [review]

File: pkg/kubelet/dockershim/docker_service.go (hunk 1 above)
Comment (aravindhp) [reply pkg/kubelet/dockershim/docker_service.go:276]: What would the equivalent steps be for Windows wrt cGroups? Maybe we should open an issue to track that?

Comment (neolit123) [reply pkg/kubelet/dockershim/docker_service.go:276]: i don't think there is a need for a note in the code or a separate tracking issue.

there is no "cgroup driver" concept on Windows as there is no "control group management" fragmentation due to multiple solutions.

it has Job objects:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/resource-controls

Comment (aravindhp) [reply pkg/kubelet/dockershim/docker_service.go:276]: Thanks @neolit123. I agree there is no need for a note or an issue. Just wanted to ensure I was not missing something.

Comment (pacoxu) [reply pkg/kubelet/dockershim/docker_service.go:277]: @jayunit100 per neolit123's comments here.

Windows has no concept of  `cgroup driver`. 
So I add a comment(not kubelet logs) here.

Comment (jayunit100) [reply pkg/kubelet/dockershim/docker_service.go:277]: Ok... the comment is good enough I guess :)

**Review by neolit123 — COMMENTED** [review]
/lgtm

you can ping someone from the owners file for approval.

**Comment by pacoxu** [comment]
> /lgtm
> 
> you can ping someone from the owners file for approval.

@neolit123  should this small fix be cherry-picked to 1.20 or other versions？

**Comment by pacoxu** [comment]
ping @derekwaynecarr @ethernetdan  for approver

**Comment by neolit123** [comment]
> @neolit123 should this small fix be cherry-picked to 1.20 or other versions？

since the kubelet allows an override via it's config i'd say this is not critical for a backport.

File: pkg/kubelet/dockershim/docker_service.go [hunk 2]
```diff
@@ -254,24 +255,28 @@ func NewDockerService(config *ClientConfig, podSandboxImage string, streamingCon
...
+			klog.Errorf("Failed to execute Info() call to the Docker client: %v", err)
+			klog.Warningf("Falling back to use the default driver: %q", cgroupDriver)
+		} else if len(dockerInfo.CgroupDriver) == 0 {
+			klog.Warningf("No cgroup driver is set in Docker")
+			klog.Warningf("Falling back to use the default driver: %q", cgroupDriver)
+		} else {
+			cgroupDriver = dockerInfo.CgroupDriver
+		}
+		if len(kubeCgroupDriver) != 0 && kubeCgroupDriver != cgroupDriver {
+			return nil, fmt.Errorf("misconfiguration: kubelet cgroup driver: %q is different from docker cgroup driver: %q", kubeCgroupDriver, cgroupDriver)
```
Comment (neolit123) [inline pkg/kubelet/dockershim/docker_service.go:274]: i side note here. i think we should turn this into a warning and override the user configuration.
this has bitten a lot of people and given we are detecting already we might as well just set the value to the one detected at the CR.

@yujuhong @filbranden WDYT?

Comment (neolit123) [reply pkg/kubelet/dockershim/docker_service.go:274]: cc @derekwaynecarr 
https://github.com/kubernetes-sigs/cluster-api/issues/866#issuecomment-478728323

**Comment by ehashman** [comment]
> ping @derekwaynecarr @ehashman for approval

I cannot approve but I'll move it on the board :smile:

**Comment by pacoxu** [comment]
thanks @ehashman

File: pkg/kubelet/dockershim/docker_service.go (hunk 2 above)
Comment (pacoxu) [reply pkg/kubelet/dockershim/docker_service.go:274]: Good idea. 

However, I have encounter kernel memory leak issues with 'cgroupfs' in some runc versions.
I'm not sure if we need to check the kernel version before overriding it.

Comment (neolit123) [reply pkg/kubelet/dockershim/docker_service.go:274]: to be consistent, it might be better to just always override and for a particular affected release in the supported version skew we can add this to "known issues" so that users can change distro / upgrade runc.

**Comment by marosset** [comment]
@derekwaynecarr @mrunalp Can one of you take a look for sig-node approval? Thanks!

**Comment by neolit123** [comment]
we need to backport this to the support skew:
.18, .19, .20

the kubeadm e2e test jobs are failing because of it:
https://github.com/kubernetes-sigs/sig-windows-tools/issues/138

@pacoxu would you be able to send the cherry picks?

**Comment by pacoxu** [comment]
@neolit123  OK, I will send the cherry picks.

**Comment by neolit123** [comment]
thanks!

**Comment by neolit123** [comment]
@pacoxu please change the release note to have "kubelet" instead of "kubeadm" (as the change is in the kubelet).
this applies to the cherry pick PRs too.

**Comment by pacoxu** [comment]
@neolit123  all are updated now. 🤝
