### PR TITLE
fix:e2e test flake: Probing container should mark readiness on pods to false...

### LINKED ISSUE #111578: e2e test flake: Probing container should mark readiness on pods to false...
### Which jobs are flaking?

pull-kubernetes-e2e-kind-ipv6

#### Failure cluster [2b82bf704961f0af177d](https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1#2b82bf704961f0af177d)
Kubernetes e2e suite.[It] [sig-node] Probing container should mark readiness on pods to false and disable liveness probes while pod is in progress of terminating
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553371978050572288
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553080106287632384
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553048515620376576
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553005284304097280

See also, possibly related:
Kubernetes e2e suite.[It] [sig-node] Probing container should mark readiness on pods to false while pod is in progress of terminating when a pod has a readiness probe
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553048515620376576
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1552994735386267648

### Since when has it been flaking?

Not sure.  At least as of July 27, 2022, but probably earlier than that.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind-ipv6

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

image

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
```
Jul 30 13:54:29.951: INFO: 1 / 1 pods in namespace 'container-probe-1329' are running and ready (20 seconds elapsed)
    Jul 30 13:54:29.951: INFO: expected 0 pod replicas in namespace 'container-probe-1329', 0 are Running and Ready.
    Jul 30 13:54:55.959: INFO: Unexpected error: 
        <*errors.StatusError | 0xc0020605a0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "pods \"probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51\" not found",
                Reason: "NotFound",
                Details: {
                    Name: "probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51",
                    Group: "",
                    Kind: "pods",
                    UID: "",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 404,
            },
        }
    Jul 30 13:54:55.959: FAIL: pods "probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" not found
```

pod ready becomes false at this time
```
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.551301     285 status_manager.go:685] "Patch status for pod" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" patch="{\"metadata\":{\"uid\":\"59b3df81-bd8b-4860-aee5-3fd8c3e05cde\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastTransitionTime\":\"2022-07-30T13:54:35Z\",\"message\":\"containers with unready status: [probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastTransitionTime\":\"2022-07-30T13:54:35Z\",\"message\":\"containers with unready status: [probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"containerID\":\"containerd://f379ea23891146790e01a563034a59567494ff715eaf8bc8ab36d71c6032dba1\",\"image\":\"registry.k8s.io/e2e-test-images/agnhost:2.40\",\"imageID\":\"registry.k8s.io/e2e-test-images/agnhost@sha256:af7e3857d87770ddb40f5ea4f89b5a2709504ab1ee31f9ea4ab5823c045f2146\",\"lastState\":{},\"name\":\"probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":{\"containerID\":\"containerd://f379ea23891146790e01a563034a59567494ff715eaf8bc8ab36d71c6032dba1\",\"exitCode\":0,\"finishedAt\":\"2022-07-30T13:54:53Z\",\"reason\":\"Completed\",\"startedAt\":\"2022-07-30T13:54:13Z\"}}}]}}"
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.551418     285 status_manager.go:694] "Status for pod updated successfully" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" statusVersion=7 status={Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-07-30 13:54:09 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-07-30 13:54:35 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-07-30 13:54:35 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-07-30 13:54:09 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:fc00:f853:ccd:e793::3 PodIP:fd00:10:244:1::f0 PodIPs:[{IP:fd00:10:244:1::f0}] StartTime:2022-07-30 13:54:09 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51 State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2022-07-30 13:54:13 +0000 UTC,FinishedAt:2022-07-30 13:54:53 +0000 UTC,ContainerID:containerd://f379ea23891146790e01a563034a59567494ff715eaf8bc8ab36d71c6032dba1,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:registry.k8s.io/e2e-test-images/agnhost:2.40 ImageID:registry.k8s.io/e2e-test-images/agnhost@sha256:af7e3857d87770ddb40f5ea4f89b5a2709504ab1ee31f9ea4ab5823c045f2146 ContainerID:containerd://f379ea23891146790e01a563034a59567494ff715eaf8bc8ab36d71c6032dba1 Started:0xc001b9f230}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.551728     285 kubelet_pods.go:955] "Pod is terminated and all resources are reclaimed" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51"
```
pod was removed
```

Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.747015     285 config.go:281] "Setting pods for source" source="api"
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.748206     285 kubelet.go:2101] "SyncLoop DELETE" source="api" pods=[container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.748261     285 pod_workers.go:625] "Pod is finished processing, no further updates" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" podUID=59b3df81-bd8b-4860-aee5-3fd8c3e05cde
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.750172     285 config.go:281] "Setting pods for source" source="api"
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.750522     285 status_manager.go:713] "Pod fully terminated and removed from etcd" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51"
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.751333     285 kubelet.go:2095] "SyncLoop REMOVE" source="api" pods=[container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51]
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.751375     285 kubelet.go:1940] "Pod has been deleted and must be killed" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" podUID=59b3df81-bd8b-4860-aee5-3fd8c3e05cde
Jul 30 13:54:54 kind-worker kubelet[285]: I0730 13:54:54.751398     285 pod_workers.go:625] "Pod is finished processing, no further updates" pod="container-probe-1329/probe-test-bc498ae5-344e-47fb-a710-a18fa8647b51" podUID=59b3df81-bd8b-4860-aee5-3fd8c3e05cde
```
#### Which issue(s) this PR fixes:

Fixes #111578

#### Special notes for your reviewer:
/cc @aojea @endocrimes 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/common/node/container_probe.go [hunk 1]
```diff
@@ -608,14 +607,12 @@ done
 		framework.ExpectNoError(err)
 
 		// Shutdown pod. Readiness should change to false
-		podClient.Delete(context.Background(), podName, metav1.DeleteOptions{})
-		err = wait.PollImmediate(framework.Poll, f.Timeouts.PodDelete, func() (bool, error) {
-			pod, err := podClient.Get(context.Background(), podName, metav1.GetOptions{})
-			if err != nil {
-				return false, err
+		framework.ExpectNoError(err)
```
Comment (Abirdcfly) [inline test/e2e/common/node/container_probe.go:610]: dup with line 607? There will be 2 consecutive `framework.ExpectNoError(err)`?

File: test/e2e/common/node/container_probe.go [hunk 2]
```diff
@@ -609,13 +608,11 @@ done
...
-			pod, err := podClient.Get(context.Background(), podName, metav1.GetOptions{})
-			if err != nil {
-				return false, err
+		err = e2epod.WaitForPodStatusByInformer(f.ClientSet, f.Namespace.Name, podName, f.Timeouts.PodDelete, func(pod *v1.Pod) (bool, error) {
+			if !podutil.IsPodReady(pod) {
+				return true, nil
 			}
-			// verify the pod ready status has reported not ready
-			return !podutil.IsPodReady(pod), nil
+			return false, fmt.Errorf("pod %s/%s is still ready", pod.Namespace, pod.Name)
```
Comment (aojea) [inline test/e2e/common/node/container_probe.go:615]: you don't want to return an error or the loop will exit and fail.
```suggestion
			 framework.Logf("pod %s/%s is still ready", pod.Namespace, pod.Name)
			 return false, nil
```

File: test/e2e/common/node/container_probe.go [hunk 3]
```diff
@@ -692,13 +689,11 @@ done
...
```
Comment (aojea) [inline test/e2e/common/node/container_probe.go:696]: same https://github.com/kubernetes/kubernetes/pull/111741/files#r939891993

File: test/e2e/common/node/container_probe.go (hunk 2 above)
Comment (249043822) [reply test/e2e/common/node/container_probe.go]: Done

File: test/e2e/common/node/container_probe.go (hunk 3 above)
Comment (249043822) [reply test/e2e/common/node/container_probe.go]: Done

File: test/e2e/framework/pod/wait.go [hunk 4]
```diff
@@ -686,6 +690,66 @@ func WaitForContainerRunning(c clientset.Interface, namespace, podName, containe
 	})
 }
 
+// WaitForPodStatusByInformer waits pod status change by informer
+func WaitForPodStatusByInformer(c clientset.Interface, podNamespace, podName string, timeout time.Duration, condition podCondition) error {
```
Comment (aojea) [inline test/e2e/framework/pod/wait.go:694]: @pohly @tallclair I wonder if we should move all these functions in this file to use an listWatch instead of a poller instead of start duplicating them, this way we can reuse them.

Right now, some tests are already using a list-watch embedding the logic within the test

an example of an e2e test that embeds the list-watch logic is here 
https://github.com/kubernetes/kubernetes/blob/6035ccd46c28b4f000259eb76337557cec6a50f1/test/e2e/common/pods.go#L240-L335

**Comment by aojea** [comment]
I think this is the right fix, the test needs to change for the pod status but it is not able to get it since it is polling the API and it may happen that during the window the pod is polled it was already deleted.

I'd like @pohly and @tallclair input on the comment I did, since they were refactoring the helper functions recently

**Comment by SergeyKanzhelev** [comment]
/assign @matthyx 

@matthyx would you have time to look at this?

/triage accepted

**Comment by aojea** [comment]
the solutions LGTM but I think we should keep `WaitForPodStatusByInformer` as an internal function, until we have more proof that we can generalize it

**Comment by matthyx** [comment]
> the solutions LGTM but I think we should keep `WaitForPodStatusByInformer` as an internal function, until we have more proof that we can generalize it

There is no such thing as a __future__ module in Python but in Go?
Otherwise SGTM.
/lgtm

**Comment by aojea** [comment]
> There is no such thing as a **future** module in Python but in Go?

I mean, making `func WaitForPodStatusByInformer(c clientset.Interface, podNamespace, podName string, timeout time.Duration, condition podCondition) error {` an internal function of this since, since it is only used by this test.

These dependencies makes the code harder to support, specially when there are this refactors and nobody know what things are depending on what

**Comment by matthyx** [comment]
> These dependencies makes the code harder to support, specially when there are this refactors and nobody know what things are depending on what

agreed, let's make it explicitly private

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by matthyx** [comment]
/assign @SergeyKanzhelev 
Sergey, I think you can approve this?

File: test/e2e/common/node/container_probe.go [hunk 5]
```diff
@@ -25,12 +25,16 @@ import (
 	"strings"
 	"time"
 
+	"k8s.io/apimachinery/pkg/runtime"
+	"k8s.io/apimachinery/pkg/watch"
```
Comment (aojea) [inline test/e2e/common/node/container_probe.go:29]: I'm surprised the linter or verify scripts don't complain for having this deps separated from the others 🤷

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
