### PR TITLE
selinux: Fix the controller to ignore finished pods

### LINKED ISSUE #135628: SELinux warning controller reports conflicts for finished Pods
### What happened?

The SELinux warning controller emits metrics + events when two pods that have different SELinux labels and share the same volume. This may not be supported when SELinuxMount feature gets GA. See the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling).

However, the controller reports these conflicting SELinux labels also for Pods in Failed or Succeeded phase. Kubelet is umounting volumes from these pods by default, so they cannot conflict with any other volume.

### What did you expect to happen?

The controller should ignore Succeeded and Failed pods.

### How can we reproduce it (as minimally and precisely as possible)?

Run a pod that uses a PVC with SELinux label `s0:c0,c1` to completion (either Succeeded or Failed). Run a second pod that uses the same volume and has label `s0:c98,c99`. The controller now emits an event that these pods are conflicting. But the first one is finished and its volumes are unmounted, so they don't really conflict.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Updated the SELinux warning controller to ignore completed Pods (both Succeeded and Failed). Kubelet is umounting volumes from those Pods by default, so they cannot conflict with any other Pod. To the controller it's the same as if they were deleted.

#### Which issue(s) this PR is related to:
Fixes #135628

#### Special notes for your reviewer:
See individual commits. There is some minor refactoring of related unit tests + new e2e tests.

The new tests revealed another bug - a Pod with no SELinux label must be treated as with `SELinuxChangePolicy: Recursive`. Kubelet already does that - it does not have any label to file into `mount -o context=<label>`. The controller is fixed in the last commit in this PR.

#### Does this PR introduce a user-facing change?
```release-note
Fixed SELinux warning controller not to emit events for completed pods.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
```

### CODE REVIEW

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go [hunk 1]
```diff
@@ -187,6 +187,28 @@ func (c *Controller) enqueuePod(_ klog.Logger, obj interface{}) {
...
+	}
+	newPod, ok := newObj.(*v1.Pod)
+	if !ok {
+		return
+	}
+	if oldPod.Status.Phase == newPod.Status.Phase {
+		return
+	}
+	if newPod.Status.Phase != v1.PodFailed && newPod.Status.Phase != v1.PodSucceeded {
+		return
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:210]: This is basically an optimization right? The completed pods will anyways be skipped during processing below?

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go [hunk 2]
```diff
@@ -489,8 +508,15 @@ func (c *Controller) syncVolume(logger klog.Logger, pod *v1.Pod, spec *volume.Sp
...
+	if !pluginSupportsSELinuxContextMount && changePolicy != v1.SELinuxChangePolicyRecursive {
+		logger.V(5).Info("Volume does not support SELinux context mount, setting changePolicy to Recursive", "pod", klog.KObj(pod), "volume", spec.Name())
+		changePolicy = v1.SELinuxChangePolicyRecursive
 	}
-	if !pluginSupportsSELinuxContextMount {
+
+	if seLinuxLabel == "" && changePolicy != v1.SELinuxChangePolicyRecursive {
+		logger.V(5).Info("Pod has empty SELinux label, setting changePolicy to Recursive", "pod", klog.KObj(pod))
 		changePolicy = v1.SELinuxChangePolicyRecursive
 	}
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:520]: nit: Not visible in this diff, but can we reuse enqueuePod when we add pods that use particular PVC to workqueue?

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go (hunk 1 above)
Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:210]: Yes, it's an optimization.

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:210]: I added a comment + squashed it into the commit that introduces this check.

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go (hunk 2 above)
Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:520]: Good point, added as a separate commit at the end

File: pkg/controller/volume/selinuxwarning/selinux_warning_controller.go [hunk 3]
```diff
@@ -489,8 +507,15 @@ func (c *Controller) syncVolume(logger klog.Logger, pod *v1.Pod, spec *volume.Sp
 	changePolicy := v1.SELinuxChangePolicyMountOption
 	if pod.Spec.SecurityContext != nil && pod.Spec.SecurityContext.SELinuxChangePolicy != nil {
 		changePolicy = *pod.Spec.SecurityContext.SELinuxChangePolicy
+		logger.V(5).Info("Using Pod SELinux change policy", "pod", klog.KObj(pod), "changePolicy", changePolicy)
 	}
-	if !pluginSupportsSELinuxContextMount {
+	if !pluginSupportsSELinuxContextMount && changePolicy != v1.SELinuxChangePolicyRecursive {
+		logger.V(5).Info("Volume does not support SELinux context mount, setting changePolicy to Recursive", "pod", klog.KObj(pod), "volume", spec.Name())
+		changePolicy = v1.SELinuxChangePolicyRecursive
+	}
```
Comment (gnufied) [inline pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:515]: Are we missing some tests when plugin *does not* support selinux policy and and hence it defaults to recursive policy regardless of what user specifies in pod spec?

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:515]: added a few e2e tests as a new commit

Comment (jsafrane) [reply pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:515]: added a single unit test + some unit test refactoring as a new commit
