### PR TITLE
fix internalTrafficPolicy

### LINKED ISSUE #100313: Traffic Policy and Topology Aware Routing should not be exclusive
#### What happened:
I believe the [code is currently written](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L30) in a way so that only one of the following will be implemented (in order):
- ExternalTrafficPolicy
- InternalTrafficPolicy
- Topology Hints

#### What you expected to happen:
Configurations like `externalTrafficPolicy=Local` + `internalTrafficPolicy=Local` should be valid. Similarly, it should be able to enable topology if only one of `externalTrafficPolicy` or `internalTrafficPolicy` are set to local.

(This originated from https://github.com/kubernetes/website/pull/27032#discussion_r595399116).

/sig network
/cc @maplain @andrewsykim @thockin

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
Primary:
- Fixes `internalTrafficPolicy: Local, externalTrafficPolicy: Cluster` in the iptables proxy. (Previously if iTP was Local, eTP would be essentially forced to Local as well.)
- Makes `internalTrafficPolicy: Local` implement `ProxyTerminatingEndpoints`. It is not clear that this is actually useful in the way that it is in the external traffic case, but it's consistent, and it makes the implementation simpler (because it means that if the internal and external traffic policies are the same, then the internal and external endpoints are the same too).
- Makes `internalTrafficPolicy: Local` DROP rather than REJECT traffic if there are remote endpoints but not local endpoints, again for consistency and simplicity. (If we didn't do this then it would complicate the case where iTP and eTP were both Local and the service had no endpoints.)
- Stops creating `KUBE-FW-XXXX` chains for LoadBalancer services that aren't using `LoadBalancerSourceRanges`

Secondary:
- ready/local/serving-terminating handling is now centralized rather than being implemented separately by iptables and ipvs
- iptables rule reorganizations that will result in fewer total rules (services now have one masq rule total rather than one masq rule per externalIP/nodePort/LB IP)
- additional topology/filtering unit test cases

#### Which issue(s) this PR fixes:
Fixes #100313

#### Does this PR introduce a user-facing change?
```release-note
Services with "internalTrafficPolicy: Local" now behave more like
"externalTrafficPolicy: Local". Also, "internalTrafficPolicy: Local,
externalTrafficPolicy: Cluster" is now implemented correctly.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/9ad538c8c04f7a15a6e7c17c49cac2c47b63a1a1/keps/sig-network/2086-service-internal-traffic-policy
```

/priority important-soon
/sig network
/triage accepted

### CODE REVIEW

File: pkg/proxy/filter_endpoints.go [hunk 1]
```diff
@@ -23,75 +23,180 @@ import (
...
 	for _, endpoint := range endpoints {
 		if endpoint.GetZoneHints().Len() == 0 {
 			klog.InfoS("Skipping topology aware endpoint filtering since one or more endpoints is missing a zone hint")
-			return endpoints
+			return false
 		}
+
+		// FIXME FIXME FIXME
+		// Should this check endpoint.IsReady()?
+		// FIXME FIXME FIXME
```
Comment (danwinship) [inline pkg/proxy/filter_endpoints.go:172]: @robscott The current rule for deciding whether to use TopologyAwareHints does "only use topology if there is at least one endpoint for this zone", but it should probably be "only use topology if there is at least one *Ready* endpoint for this zone", right?

Comment (robscott) [reply pkg/proxy/filter_endpoints.go:172]: Yes, thanks! I'll work on a separate PR to fix that so it can be cherry picked back.

Comment (robscott) [reply pkg/proxy/filter_endpoints.go:172]: https://github.com/kubernetes/kubernetes/pull/106507

**Comment by danwinship** [comment]
/test pull-kubernetes-e2e-kind-ipv6
(it's failed twice on the same test, which isn't failing for anyone else... but it has nothing to do with services/endpoints!)

**Comment by danwinship** [comment]
/test pull-kubernetes-e2e-kind-ipv6
for good measure...

**Comment by danwinship** [comment]
/retest-required
unit test failure is #106326

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1099,6 +1126,52 @@ func (proxier *Proxier) syncProxyRules() {
 			activeNATChains[svcXlbChain] = true
 		}
 
+		if proxier.localDetector.IsImplemented() && svcChain != "" {
+			// We have a LocalDetector, so fill in the rules in the SVC chain to
+			// redirect external traffic (or simply masquerade it if we don't
+			// have a separate external chain).
+			var externalTrafficDest utiliptables.Chain
+			if svcXlbChain != "" {
+				externalTrafficDest = svcXlbChain
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1083]: This confuses me because it's not clear these are both going to return back to svcChain.  Is that right?

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -1099,6 +1126,52 @@ func (proxier *Proxier) syncProxyRules() {
...
+		} else if !proxier.localDetector.IsImplemented() && svcXlbChain != "" {
+			// No LocalDetector, so fill in the rules in the XLB chain to treat
+			// node-local traffic as internal
+			proxier.natRules.Write(
+				"-A", string(svcXlbChain),
+				"-m", "comment", "--comment", fmt.Sprintf(`"masquerade LOCAL traffic for %s LB IP"`, svcNameString),
+				"-m", "addrtype", "--src-type", "LOCAL",
+				"-j", string(KubeMarkMasqChain),
+			)
+			proxier.natRules.Write(
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1107]: Am I reading this right?  In the first case (above) you have a rule in svcChain which jumps to xlbChain.  In this else-if you have a rule in xlbChain that jumps to svcChain.

?

That seems like it could end up in a loop ?  Or at least be impossible to diagram...

File: pkg/proxy/iptables/proxier.go [hunk 4]
```diff
@@ -1231,23 +1270,14 @@ func (proxier *Proxier) syncProxyRules() {
...
-				// If we are proxying only locally, we can retain the source IP.
-				if !svcInfo.NodeLocalExternal() {
-					proxier.natRules.Write(args, "-j", string(KubeMarkMasqChain))
-					chosenChain = svcChain
-				}
-
 				if len(svcInfo.LoadBalancerSourceRanges()) == 0 {
 					// allow all sources, so jump directly to the KUBE-SVC or KUBE-XLB chain
-					proxier.natRules.Write(args, "-j", string(chosenChain))
+					proxier.natRules.Write(args, "-j", string(extTargetChain))
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: because the setting of `extTargetChain` is now SO FAR away, can we do more to make it clearer what it means?  Even the definition of it doesn't really say what it's for.

File: pkg/proxy/iptables/proxier.go [hunk 5]
```diff
@@ -1076,8 +1076,32 @@ func (proxier *Proxier) syncProxyRules() {
 			proxier.natRules.Write(args)
 		}
 
-		svcChain := svcInfo.servicePortChainName
+		var svcChain, svcXlbChain, extTargetChain utiliptables.Chain
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1027]: super nit - we should just call it `svcChain` and `xlbChain`

**Review by thockin — COMMENTED** [review]
I only made it thru the proxier changes in the first commit, but I am not confident I understand it.  I will need to come back again and re-process it after I skim forward a bit more.  I find it somewhat less readable because the big comments are now at the top and I have to really wrack my brain to keep the "if no local-detector" branches in mind.

There HAS to be a more manageable way to express this code without duplicating tons of it.

One idea for making tests more readable:  We could inject a chain-name-generator which takes the information and generates the hash part.  For testing we could inject an triviaal one that simply inserts the pod or service names.  E.g. 

"KUBE-SVC-ns1-svc1" instead of "KUBE-SVC-XPGD46QRK7WJZT7O".

File: pkg/proxy/iptables/proxier.go [hunk 6]
```diff
@@ -1099,6 +1126,52 @@ func (proxier *Proxier) syncProxyRules() {
 			activeNATChains[svcXlbChain] = true
 		}
 
+		if proxier.localDetector.IsImplemented() && svcChain != "" {
+			// We have a LocalDetector, so fill in the rules in the SVC chain to
+			// redirect external traffic (or simply masquerade it if we don't
+			// have a separate external chain).
+			var externalTrafficDest utiliptables.Chain
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1081]: I think it would be easier to read this block without the variable.

```
args = [
    "-A", string(svcChain),
    "-m", "comment", "--comment", svcNameString,
    "-m", "addrtype",
    "!", "--src-type", "LOCAL"
]
if svcXlbChain != "" {
    proxier.natRules.Write(args, proxier.localDetector.JumpIfNotLocal(nil, svcXlbChain)
}else {
    proxier.natRules.Write(args, proxier.localDetector.JumpIfNotLocal(nil, KubeMarkMasqChain)
}
```

Reading the args first gives context.  Even if you just put the args before the variable and then Write() at the end.

Or maybe just calling the variable "jumpTo" or something less overlapping with `svcXlbChain`.  It's a pretty localized variable scope, so a fancy name it not super needed.

File: pkg/proxy/iptables/proxier.go [hunk 7]
```diff
@@ -1155,39 +1219,14 @@ func (proxier *Proxier) syncProxyRules() {
...
+					"-A", string(kubeServicesChain),
 					"-m", "comment", "--comment", fmt.Sprintf(`"%s external IP"`, svcNameString),
 					"-m", protocol, "-p", protocol,
 					"-d", externalIP,
 					"--dport", strconv.Itoa(svcInfo.Port()),
+					"-j", string(extTargetChain),
 				)
-
-				destChain := svcXlbChain
-				// We have to SNAT packets to external IPs if externalTrafficPolicy is cluster
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1166]: Having these comments very close to the code was really helpful to me.  Any way we can retain this level of explanation?

File: pkg/proxy/iptables/proxier.go (hunk 5 above)
Comment (thockin) [reply pkg/proxy/iptables/proxier.go:1027]: comments on extTargetChain would help a lot

File: pkg/proxy/iptables/proxier.go [hunk 8]
```diff
@@ -1306,40 +1336,28 @@ func (proxier *Proxier) syncProxyRules() {
 
 			if hasEndpoints {
 				args = append(args[:0],
+					"-A", string(kubeNodePortsChain),
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1291]: The "before" code added a mark-masq for nodeports to SVC - this drops that rule.  Is this correctly covered by the major  changes above?  It's hard to tell..

File: pkg/proxy/iptables/proxier_test.go [hunk 9]
```diff
@@ -1225,47 +1225,40 @@ COMMIT
...
 -A KUBE-MARK-MASQ -j MARK --or-mark 0x4000
 -A KUBE-SERVICES -m comment --comment "ns1/svc1:p80 cluster IP" -m tcp -p tcp -d 10.20.30.41 --dport 80 -j KUBE-SVC-XPGD46QRK7WJZT7O
--A KUBE-SVC-XPGD46QRK7WJZT7O -m comment --comment "ns1/svc1:p80 cluster IP" -m tcp -p tcp -d 10.20.30.41 --dport 80 ! -s 10.0.0.0/24 -j KUBE-MARK-MASQ
+-A KUBE-SVC-XPGD46QRK7WJZT7O -m comment --comment ns1/svc1:p80 -m addrtype ! --src-type LOCAL ! -s 10.0.0.0/24 -j KUBE-MARK-MASQ
 -A KUBE-SVC-XPGD46QRK7WJZT7O -m comment --comment ns1/svc1:p80 -j KUBE-SEP-SXIVWICOYRO3J4NJ
 -A KUBE-SEP-SXIVWICOYRO3J4NJ -m comment --comment ns1/svc1:p80 -s 10.180.0.1 -j KUBE-MARK-MASQ
 -A KUBE-SEP-SXIVWICOYRO3J4NJ -m comment --comment ns1/svc1:p80 -m tcp -p tcp -j DNAT --to-destination 10.180.0.1:80
 -A KUBE-SERVICES -m comment --comment "ns2/svc2:p80 cluster IP" -m tcp -p tcp -d 10.20.30.42 --dport 80 -j KUBE-SVC-GNZBNJ2PO5MGZ6GT
--A KUBE-SERVICES -m comment --comment "ns2/svc2:p80 external IP" -m tcp -p tcp -d 1.2.3.4 --dport 80 -j KUBE-XLB-GNZBNJ2PO5MGZ6GT
+-A KUBE-SERVICES -m comment --comment "ns2/svc2:p80 external IP" -m tcp -p tcp -d 1.2.3.4 --dport 80 -j KUBE-SVC-GNZBNJ2PO5MGZ6GT
```
Comment (thockin) [inline pkg/proxy/iptables/proxier_test.go:1232]: The fact that the test uses the same IP for LB and externalIP makes this hard to look at.  Can you change those to be different?

**Review by thockin — COMMENTED** [review]
I made a second pass on the first commit.  I tried flow-charting it all out.  I find it much harder to reason about now - what can we do to make it more obvious?

I have low confidence in the tests...

**Comment by thockin** [comment]
I spent all night chewing on how to make this easier to read and verify.  Nothing was "obviously better" but I kept circling backj to a more structural model.  E.g., what if we did something like:

```
type Chain struct {
	name string
	rules []*Rule
}

type Rule struct {
	// Conditionals: any number of these may be set
	IfLocalSrc bool
	IfNonLocalSrc bool
	MatchDst struct {
		IP string
		Port int
		Protocol string
	}
	// etc...

	// Terminals: one of these must be set
	Jump *Chain
	Return bool
}
```

For efficiency we could pre-allocate everything and make our own "allocator":

```
var chainPool = make([]Chain, 0, 1024)
func newChain(name string) *Chain {
	chainPool = append(chainPool, Chain{})
	c := &chainPool[len(chainPool)-1]
	c.Name = name
	if c.Rules == nil {
		c.Rules = make([]Rule, 0, 32)
	}
	c.Reset() // clear all fields
	return c
}

var rulePool = make([]Rule, 0, 1024)
func newRule() *Rule {
	rulePool = append(rulePool, Rule{})
	r := &rulePool[len(rulePool)-1]
	r.Reset()  // clear all fields
	return r
}

func reset() {
	chainPool = chainPool[:0]
	rulePool = rulePool[:0]
}
```

Then we build up aa set of these in the most natural way possible.  At the end
of it we can call `Chain.Render(buf)` or something like that and get the
strings out.  But we can also make tests that compare structs instead of
strings.  We can also do something like:

```
if xlbChain.Equal(svcChain) {
	xlbChain = jumpTo(svcChain)
}
```

That's not quite the same optimization you made but maybe simpler.

Anyway, I'd love to hear thoughts - is this better or worse?

**Comment by dims** [comment]
guess this is for v1.24?

/milestone v1.24

**Comment by andrewsykim** [comment]
cc @maplain who wrote the initial implementation and might want to review this as well

File: pkg/proxy/filter_endpoints.go [hunk 10]
```diff
@@ -0,0 +1,204 @@
+/*
```
Comment (andrewsykim) [inline pkg/proxy/filter_endpoints.go:1]: Is this a direct copy from `pkg/proxy/topology.go` or were there any changes as well?

Comment (andrewsykim) [reply pkg/proxy/filter_endpoints.go:1]: Oh, I see now that FilterEndpoints returns separate endpoints for internal/external

Comment (andrewsykim) [reply pkg/proxy/filter_endpoints.go:1]: Do you think we can do the file name change in a separate PR so we can keep the diff on the changes only?

Comment (andrewsykim) [reply pkg/proxy/filter_endpoints.go:1]: Same comment for `pkg/proxy/filter_endpoints_test.go`

**Comment by danwinship** [comment]
> There HAS to be a more manageable way to express this code without duplicating tons of it.

Hm... OK, so the problem is that when you have a LocalDetector, we categorize traffic based on source IP "zone" (local vs non-local), but when you don't have a LocalDetector, we categorize it based on destination IP type (ClusterIP vs non-ClusterIP).

But maybe I could rewrite this so that we always categorize traffic based on _both_ source _and_ destination. In the "working LD" case, the categorization would ignore the destination type, and in the "no LD" case, the categorization would ignore the source IP. But at a high level, both cases would look the same to everything else in kube-proxy...

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1107]: There's no loop because you can only have the SVC->XLB jump if you have a LocalDetector, and you can only have the XLB->SVC jump if you _don't_ have a LocalDetector.

File: pkg/proxy/iptables/proxier.go [hunk 11]
```diff
@@ -1099,6 +1126,52 @@ func (proxier *Proxier) syncProxyRules() {
 			activeNATChains[svcXlbChain] = true
 		}
 
+		if proxier.localDetector.IsImplemented() && svcChain != "" {
+			// We have a LocalDetector, so fill in the rules in the SVC chain to
+			// redirect external traffic (or simply masquerade it if we don't
+			// have a separate external chain).
+			var externalTrafficDest utiliptables.Chain
+			if svcXlbChain != "" {
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1082]: So I guess I never stated this explicitly, but one of the ideas in the rewrite is that `svcChain` gets set if and only if we are using a SVC chain and `svcXlbChain` gets set if and only if we are using an XLB chain. So then later on, anything that might add rules to the SVC chain checks `svcChain != ""` and anything that might add rules to the XLB chain checks `svcXlbChain != ""`.

So in this case in particular, `if svcInfo.NodeLocalExternal()` happens to be equivalent at this point in the PR, but later on, the rule for when we do and don't create an XLB chain changes, so `if svcInfo.NodeLocalExternal()` would no longer be correct, but `if svcXlbChain != ""` still is.

Maybe I should make explicit `bool`s rather than using the chain name variables as booleans.

File: pkg/proxy/iptables/proxier.go (hunk 8 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1291]: yes; with the new organization there is a single mark-masq call per service, rather than having a separate rule for each nodeport, external IP, and loadbalancer IP.

File: pkg/proxy/filter_endpoints.go (hunk 10 above)
Comment (danwinship) [reply pkg/proxy/filter_endpoints.go:1]: The commit "`pkg/proxy: rename topology.go to filter_endpoints.go`" is a straight rename, and then later commits make changes.

**Comment by danwinship** [comment]
I split out the `pkg/proxy/topology.go` renaming/refactoring to #107393 so that can be reviewed separately while I'm working on rewriting this...

File: pkg/proxy/filter_endpoints.go (hunk 10 above)
Comment (andrewsykim) [reply pkg/proxy/filter_endpoints.go:1]: Ah my bad, I missed the separate commit for this change

**Comment by danwinship** [comment]
> I have low confidence in the tests...

@thocking, see #107471, in particular:

```
proxy/iptables: add new packet-flow tests

Add a new framework for testing out how particular packets would be
handled by a given set of iptables rules. (eg, "assert that a packet
from 10.180.0.2 to 172.30.0.41:80 gets NATted to 10.180.0.1:80 without
being masqueraded")

This will make it easier to confirm that large-scale rule refactorings
don't have any unexpected side effects.
```

File: pkg/proxy/iptables/proxier.go [hunk 12]
```diff
@@ -1201,74 +1188,69 @@ func (proxier *Proxier) syncProxyRules() {
...
+		// set the load balancer IPs in the service status, and instead just forward
+		// the traffic to a NodePort, so the handling below (including, in particular,
+		// the implementation of LoadBalancerSourceRanges) will be skipped.
 		fwChain := svcInfo.serviceFirewallChainName
 		for _, ingress := range svcInfo.LoadBalancerIPStrings() {
-			if hasEndpoints {
+			targetChainFromKubeServices := extTargetChain
+
+			// We need a FW chain if loadBalancerSourceRanges is used
+			if hasAnyEndpoints && len(svcInfo.LoadBalancerSourceRanges()) > 0 {
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1203]: I think the `len(svcInfo.LoadBalancerSourceRanges()) > 0` check here is new but some of the new rules added here should apply when the source range is not set right?

Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go:1203]: Ah I think I follow now, some of the other rules were removed in this if block and moved below under another one.

File: pkg/proxy/filter_endpoints_test.go [hunk 13]
```diff
@@ -117,42 +117,22 @@ func TestFilterEndpoints(t *testing.T) {
 			{ip: "10.1.2.5", zoneHints: sets.NewString("zone-c")},
 			{ip: "10.1.2.6", zoneHints: sets.NewString("zone-a")},
 		},
-		expectedEndpoints: []endpoint{
-			{ip: "10.1.2.3", zoneHints: sets.NewString("zone-a")},
-			{ip: "10.1.2.4", zoneHints: sets.NewString("zone-b")},
-			{ip: "10.1.2.5", zoneHints: sets.NewString("zone-c")},
```
Comment (andrewsykim) [inline pkg/proxy/filter_endpoints_test.go]: Were the zoneHints in expectedEndpoints not being used then?

File: pkg/proxy/filter_endpoints_test.go [hunk 14]
```diff
@@ -204,9 +189,10 @@ func Test_filterEndpointsWithHints(t *testing.T) {
 		},
 		expectedEndpoints: sets.NewString("10.1.2.3:80", "10.1.2.6:80"),
 	}, {
-		name:            "hintsAnnotation empty, no filtering applied",
-		nodeLabels:      map[string]string{v1.LabelTopologyZone: "zone-a"},
-		hintsAnnotation: "",
```
Comment (andrewsykim) [inline pkg/proxy/filter_endpoints_test.go]: The test table here actually setting the hints annotation as opposed to a bool like hintsEnabled seemed intentional, since there's some defined behavior when the annotation is empty.

File: pkg/proxy/filter_endpoints_test.go (hunk 13 above)
Comment (danwinship) [reply pkg/proxy/filter_endpoints_test.go]: They weren't doing anything _useful_; we already knew that FilterEndpoints doesn't _change_ the endpoints. But the test case was comparing the input and output with DeepEqual, so we had to re-specify all the fields again even though we knew they weren't going to change.

And this got annoying when rewriting the tests because I had to keep adding more fields to the expectedEndpoints to make them fully match the input endpoints.

File: pkg/proxy/filter_endpoints_test.go (hunk 14 above)
Comment (danwinship) [reply pkg/proxy/filter_endpoints_test.go]: The empty-annotation behavior is still tested; if you look few a lines further down you see:

```
+		serviceInfo:  &BaseServiceInfo{hintsAnnotation: ""},
```

The tests that originally came from `Test_filterEndpointsWithHints` were only specifying the `hintsAnnotation` field they wanted in the `serviceInfo`, but when they got merged into `TestFilterEndpoints` they had to be changed to specify the whole `serviceInfo` instead.

Likewise, the tests from `Test_filterEndpointsWithHints` were all previously running with the `TopologyAwareHints` enabled, but `TestFilterEndpoints` only enables it for the test cases that request it, so each of these tests needed to have `hintsEnabled: true` added to it.


(BTW, the endpoint-filtering subset of this commit is also separately pushed as #107393 so if you're OK with it you can lgtm it there and get that part of this merged.)

**Review by andrewsykim — COMMENTED** [review]
Left a minor comment here https://github.com/kubernetes/kubernetes/pull/107393#pullrequestreview-877836947 regarding the file name change for `pkg/proxy/topology.go`, but otherwise this PR seems okay to me after reviewing it several times.

I think with a PR like this we should try to merge it earlier in the release cycle and let it soak a little bit, maybe look to add some more e2e tests for it as a follow-up. 

@danwinship happy to do another review once you think the PR is not WIP anymore.

**Comment by danwinship** [comment]
> @danwinship happy to do another review once you think the PR is not WIP anymore.

It's WIP because it's built on top of #107471 and #107393. Assuming we're OK to merge all of that, then the additional pieces here (`Simplify LocalTrafficDetector`, `Reorganize initial rule dispatch and masquerading`, `Don't write FW chain if it's not actually needed`, `Fix internal-vs-external traffic policy`) are all good to go.

@thockin was dubious about the PR before so I'd like an ack from him that #107471 solves the problems with rewriting proxier.go

**Comment by danwinship** [comment]
OK, #107393 is merged as is most of #107471. So this can now be reviewed on its own... Alternatively, if this isn't quite ready to go, we could still merge just #107471 (iptables unit test rewrite) first while continue to iterate the rest of this. But the commits here make it easier to see why the unit test rewrites in #107471 are a good thing, so it may make more sense to just review it all here, merge, and then close 107471.

**Comment by danwinship** [comment]
/hold

after discussion about related stuff in the SIG meeting yesterday, I may be updating this.

However, #107471 can still be merged

**Comment by andrewsykim** [comment]
FYI @danwinship the work for ProxyTerminatingEndpoints this release is going to need to incorporate this PR (https://github.com/kubernetes/kubernetes/pull/108691). I did a rough implementation of the changes on the current code base but will defer on polishing it up until this PR lands.

**Comment by danwinship** [comment]
/hold cancel

still builds on #107471 (the first 2 commits), which can still be merged separately ahead of this (or not). Many of the other commits could be split out as well, although all of them depend on #107471.

This now follows the decisions I made in #108526:
- `internalTrafficPolicy` applies to any traffic sent to the ClusterIP
- `externalTrafficPolicy` applies to traffic sent to NodePorts from anywhere, and to traffic sent to ExternalIPs and LoadBalancer IPs from outside the cluster.
  - pod/node-to-ExternalIP/LBIP always has `Cluster` semantics, even when the service has `Local` traffic policy for both internal and external, because the point of the short-circuit was not "pod to LB IP should obey internal policy rather than external", it was "pod to LB IP should just work without the end user needing to worry about traffic policy, in the same way that external to LB IP just works without the end user needing to worry about traffic policy".

I also decided that `internalTrafficPolicy: Local` trumps `kube-proxy --masquerade-all`, though we could argue about that.

File: pkg/proxy/iptables/proxier.go [hunk 15]
```diff
@@ -1073,58 +1019,121 @@ func (proxier *Proxier) syncProxyRules() {
...
+				"-j", string(svcChain))
+
+			// Everything else goes to the SVL chain
+			proxier.natRules.Write(
+				"-A", string(svcXlbChain),
+				"-j", string(svcLocalChain))
+		}
+
+		if svcInfo.NodeLocalInternal() {
+			internalTrafficChain = svcLocalChain
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1117]: The comments for serviceLocalChainName (KUBE-SVL) mentions it is only used for external traffic policy

File: pkg/proxy/iptables/proxier.go [hunk 16]
```diff
@@ -142,16 +142,16 @@ func newServiceInfo(port *v1.ServicePort, service *v1.Service, baseInfo *proxy.B
 // internal struct for endpoints information
 type endpointsInfo struct {
 	*proxy.BaseEndpointInfo
-	// The following fields we lazily compute and store here for performance
-	// reasons. If the protocol is the same as you expect it to be, then the
-	// chainName can be reused, otherwise it should be recomputed.
-	protocol  string
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:148]: yeah. It wasn't actually needed anyway; the code was making sure you didn't try to use the same endpointsInfo for two different endpoints basically, which could never actually happen.

File: pkg/proxy/iptables/proxier.go [hunk 17]
```diff
@@ -693,36 +683,44 @@ func portProtoHash(servicePortName string, protocol string) string {
...
+func serviceChainName(servicePortName string, protocol string) utiliptables.Chain {
 	return utiliptables.Chain("KUBE-SVC-" + portProtoHash(servicePortName, protocol))
 }
 
-// serviceFirewallChainName takes the ServicePortName for a service and
-// returns the associated iptables chain.  This is computed by hashing (sha256)
-// then encoding to base32 and truncating with the prefix "KUBE-FW-".
+// serviceLocalChainName returns the name of the iptables chain that handles `Local` traffic
+// policy for a service (KUBE-SVL-XXXX). This chain only exists if the service has `Local`
+// external traffic policy.
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go]: I clarified all the descriptions a little more...

File: pkg/proxy/iptables/proxier.go (hunk 15 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1119]: updated that. (It still says external-only in the original commit, but gets updated in the final commit)

File: pkg/proxy/iptables/proxier_test.go [hunk 18]
```diff
@@ -2949,9 +3055,7 @@ func compareEndpointsMaps(t *testing.T, tci int, newMap proxy.EndpointsMap, expe
 					continue
 				}
 				if newEp.Endpoint != expected[x][i].Endpoint ||
-					newEp.IsLocal != expected[x][i].IsLocal ||
-					newEp.protocol != expected[x][i].protocol ||
```
Comment (robscott) [inline pkg/proxy/iptables/proxier_test.go:2953]: Just double checking - protocol is irrelevant here and can safely be removed right?

File: pkg/proxy/iptables/proxier_test.go [hunk 19]
```diff
@@ -4651,59 +4595,24 @@ func Test_EndpointSliceWithTerminatingEndpoints(t *testing.T) {
 					},
 				},
 			},
-			expectedIPTables: `
```
Comment (robscott) [inline pkg/proxy/iptables/proxier_test.go:4654]: I don't think we need this full iptables diffs everywhere, but they are remarkably helpful when understanding the full diff a change results in. Maybe it's worth leaving a couple more in place?

**Review by robscott — COMMENTED** [review]
There is a lot in this PR, thanks for all the work on this @danwinship! Got part of the way through and mostly just had some questions. Planning to spend more time on this tomorrow.

File: pkg/proxy/iptables/proxier_test.go [hunk 20]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
 	}
 }
 
+// cidrContains checks if cidrStr contains ipStr. cidrStr can actually be a CIDR or an IP
```
Comment (bowei) [inline pkg/proxy/iptables/proxier_test.go:1350]: Let's make this more explicit

cidrStr is either an IP ("1.2.3.4") or a CIDR ("1.2.3.4/20").

File: pkg/proxy/iptables/proxier_test.go [hunk 21]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+func cidrContains(cidrStr, ipStr string) bool {
+	ip := netutils.ParseIPSloppy(ipStr)
+	if ip == nil {
+		panic("bad IP in test case: " + ipStr)
+	}
+
+	if strings.Contains(cidrStr, "/") {
+		_, cidr, err := netutils.ParseCIDRSloppy(cidrStr)
+		if err != nil {
+			panic("bad CIDR in kube-proxy output: " + err.Error())
```
Comment (bowei) [inline pkg/proxy/iptables/proxier_test.go:1360]: add the string to the panic message 

bad CIDR in kube-proxy output (%q) = %v

File: pkg/proxy/iptables/proxier_test.go [hunk 22]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+
+	nodeIP string
+
+	matches  []string
+	outputs  []string
+	markMasq bool
+	markDrop bool
+}
+
+func newIPTablesTracer(ruleData, nodeIP string) (*iptablesTracer, error) {
```
Comment (bowei) [inline pkg/proxy/iptables/proxier_test.go:1399]: document paramters

File: pkg/proxy/iptables/proxier_test.go [hunk 23]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+	} else {
+		ip2 := netutils.ParseIPSloppy(cidrStr)
+		if ip2 == nil {
+			panic("bad IP in kube-proxy output: " + cidrStr)
+		}
+		return ip.Equal(ip2)
+	}
+}
+
+var addChainRegex = regexp.MustCompile(`-A ([^ ]*) `)
```
Comment (bowei) [inline pkg/proxy/iptables/proxier_test.go:1372]: could we have a simple test that takes a golden example string this matches 

```
func testTracerRegex(t*testing.T) {
  const addChain = `-A ....`
  ...
}
```

File: pkg/proxy/iptables/proxier_test.go [hunk 24]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+var probabilityRegex = regexp.MustCompile(" --probability ([^ ]*) ")
+var jumpRegex = regexp.MustCompile(" -j ([^ ]*)( --to-destination (.*))?$")
+
+var noMatchModules = sets.NewString("conntrack", "mark")
+var knownModules = sets.NewString("addrtype", "recent", "statistic", "tcp")
+
+type iptablesTracer struct {
+	// tables is a map of table name to table. Each table is a map from chain name
+	// to the rules in that chain
+	tables map[string]map[string][]string
```
Comment (bowei) [inline pkg/proxy/iptables/proxier_test.go:1389]: can we use some types

type rules []string
type chains map[string]rules 

tables map[string]chains

File: pkg/proxy/iptables/proxier_test.go [hunk 25]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+		case "KUBE-MARK-MASQ":
+			tracer.markMasq = true
+			continue
+
+		case "KUBE-MARK-DROP":
+			tracer.markDrop = true
+			continue
+
+		case "ACCEPT", "REJECT":
+			tracer.outputs = append(tracer.outputs, match[1])
```
Comment (robscott) [inline pkg/proxy/iptables/proxier_test.go:1521]: It's hard to follow the structure of these matches, could be helpful to have a comment indicated what `match[1]` represents here.

File: pkg/proxy/iptables/proxier_test.go [hunk 26]
```diff
@@ -1345,6 +1347,270 @@ func assertIPTablesRulesNotEqual(t *testing.T, expected, result string) {
...
+			return true
+
+		case "DNAT":
+			// add the "--to-destination ..." value to outputs
+			tracer.outputs = append(tracer.outputs, match[3])
```
Comment (robscott) [inline pkg/proxy/iptables/proxier_test.go:1526]: Same comment about what `match[3]`

**Review by thockin — COMMENTED** [review]
Incremental review:  Commit "pkg/proxy: Simplify LocalTrafficDetector"

Does it make sense to extract this commit into a new PR, just to get it out of this one?

**Review by thockin — COMMENTED** [review]
incremental review: "proxy/iptables: move XLB chain initial rule setup" commit is OK.

**Review by thockin — COMMENTED** [review]
incremental review: "proxy/iptables: clean up / clarify iptables chain names a bit"

This OKand consistent, though I think it's actually retrograde motion.  What would you think about a followup that changes ALL of these places that *actually* relate to a service-port and rename them to some new term that means "service port".  E.g. "svcpt" or "spt" or "sport" ?

File: pkg/proxy/endpointslicecache.go [hunk 27]
```diff
@@ -158,7 +158,7 @@ func newEndpointSliceInfo(endpointSlice *discovery.EndpointSlice, remove bool) *
 }
 
 // standardEndpointInfo is the default makeEndpointFunc.
-func standardEndpointInfo(ep *BaseEndpointInfo) Endpoint {
+func standardEndpointInfo(ep *BaseEndpointInfo, _ *ServicePortName) Endpoint {
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/endpointslicecache.go:161]: This is not about Endpoints vs EndpointSlice at all. Or about tests vs not tests.

There is generic (ie, proxy-backend-agnostic) code in `pkg/proxy` to handle Endpoints/EndpointSlice events, and it aggregates the information into a `BaseEndpointInfo` object (regardless of whether you're using Endpoints or EndpointSlices) and then the proxy backend can call the generic code to get the list of things that have changed since the last time it was called.

To make things easier for the proxy backend, this generic code allows the backend to "subclass" BaseEndpointInfo, which the iptables proxy does, so that for each endpoint it can also keep track of the name of the iptables chain it is creating for that endpoint.

In current git master, the way that this works is that when the generic code wants to create an BaseEndpointInfo, it calls the function provided by the iptables proxy, which then creates an iptables.endpointsInfo that contains no extra information. Then later on, when someone wants to know what the iptables chain name for that endpoint is, the pass the necessary extra information to an iptables.endpointsInfo function, which computes the endpoint chain name, caches it, and returns it (after making sure that you didn't try to trick it by passing it different "necessary extra information" than you passed it last time).

This commit just changes things so that we pass the "necessary extra information" at construct time, so the iptables proxier constructor can just generate the chain name then, rather than doing it later.

File: pkg/proxy/endpoints.go [hunk 28]
```diff
@@ -462,7 +462,7 @@ func (ect *EndpointChangeTracker) endpointsToEndpointsMap(endpoints *v1.Endpoint
 				// Zone information is only supported with EndpointSlice API
 				baseEndpointInfo := newBaseEndpointInfo(addr.IP, nodeName, "", int(port.Port), isLocal, isReady, isServing, isTerminating, zoneHints)
 				if ect.makeEndpointInfo != nil {
-					endpointsMap[svcPortName] = append(endpointsMap[svcPortName], ect.makeEndpointInfo(baseEndpointInfo))
+					endpointsMap[svcPortName] = append(endpointsMap[svcPortName], ect.makeEndpointInfo(baseEndpointInfo, &svcPortName))
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/endpoints.go:465]: the endpointInfos are later copied into other data structures and have to be operated on in a context where we don't have the key that was previously associated with them

File: pkg/proxy/iptables/proxier.go [hunk 29]
```diff
@@ -693,36 +683,46 @@ func portProtoHash(servicePortName string, protocol string) string {
...
 }
 
-// serviceFirewallChainName takes the ServicePortName for a service and
-// returns the associated iptables chain.  This is computed by hashing (sha256)
-// then encoding to base32 and truncating with the prefix "KUBE-FW-".
+// serviceLocalChainName returns the name of the KUBE-SVL-XXXX chain for a service, which
+// handles dispatching to local endpoints when using `Local` traffic policy. This chain only
+// exists if the service has `Local` internal or external traffic policy.
+func serviceLocalChainName(servicePortName string, protocol string) utiliptables.Chain {
+	return utiliptables.Chain("KUBE-SVL-" + portProtoHash(servicePortName, protocol))
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:697]: I'm totally happy to bikeshed the names...

I avoided changing KUBE-SVC and KUBE-XLB to keep some consistency/familiarity, but given that KUBE-SVC eventually becomes "the chain used for `Cluster` traffic policy` rather than `the primary service chain`, I thought it would be somewhat mnemonic to have SVC = Cluster / SVL = Local...

File: pkg/proxy/iptables/proxier.go [hunk 30]
```diff
@@ -990,64 +981,21 @@ func (proxier *Proxier) syncProxyRules() {
...
-					if ep.GetIsLocal() {
-						hasLocalServingTerminatingEndpoints = true
-					}
-				}
-			}
-		}
-		useTerminatingEndpoints := !hasLocalReadyEndpoints && hasLocalServingTerminatingEndpoints
+		// Figure out the endpoints for Cluster and Local traffic policy.
+		// allEndpointsOnNode is the set of all endpoints that can be reached from
+		// this node, given the service's traffic policies. hasEndpoints is true
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:986]: > I'm likely misunderstanding something obvious, but why they need for both this and clusterEndpoints?

ah, well, with the current code, `clusterEndpoints` never includes terminating endpoints, so there may be some reachable endpoints that are only in `localEndpoints`. But indeed, assuming we change that, then we wouldn't need this

File: pkg/proxy/iptables/proxier_test.go [hunk 31]
```diff
@@ -1021,11 +1024,11 @@ COMMIT
 -A KUBE-FW-GNZBNJ2PO5MGZ6GT -m comment --comment "ns2/svc2:p80 loadbalancer IP" -s 203.0.113.0/25 -j KUBE-XLB-GNZBNJ2PO5MGZ6GT
 -A KUBE-FW-GNZBNJ2PO5MGZ6GT -m comment --comment "ns2/svc2:p80 loadbalancer IP" -j KUBE-MARK-DROP
 -A KUBE-NODEPORTS -m comment --comment ns2/svc2:p80 -m tcp -p tcp --dport 3001 -s 127.0.0.0/8 -j KUBE-MARK-MASQ
--A KUBE-NODEPORTS -m comment --comment ns2/svc2:p80 -m tcp -p tcp --dport 3001 -j KUBE-XLB-GNZBNJ2PO5MGZ6GT
+-A KUBE-NODEPORTS -m comment --comment ns2/svc2:p80 -m tcp -p tcp --dport 3001 -j KUBE-SVL-GNZBNJ2PO5MGZ6GT
```
[the remark this answers is not in the document]
Comment (robscott) [reply pkg/proxy/iptables/proxier_test.go:1027]: Digging through the PR more, this makes sense, disregard me.

File: pkg/proxy/iptables/proxier.go [hunk 32]
```diff
@@ -1335,25 +1340,19 @@ func (proxier *Proxier) syncProxyRules() {
...
 						args,
 						"-j", string(KubeMarkMasqChain))
-				} else {
-					// TODO: Make all nodePorts jump to the firewall chain.
-					// Currently we only create it for loadbalancers (#33586).
-
-					// Fix localhost martian source error
-					loopback := "127.0.0.0/8"
-					if isIPv6 {
-						loopback = "::1/128"
```
Comment (robscott) [inline pkg/proxy/iptables/proxier.go:1297]: Is this no longer necessary for IPv6?

File: pkg/proxy/iptables/proxier_test.go (hunk 31 above)
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:1027]: It's in the commit message; one of the decisions from #108526 (which is still up for discussion) is that we don't want pod-to-NodePort or node-to-NodePort traffic to get short-circuited, so now it bypasses the XLB chain and goes straight to the SVL chain.

File: pkg/proxy/iptables/proxier_test.go (hunk 18 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:2953]: Yes. It was actually always irrelevant.

File: pkg/proxy/iptables/proxier_test.go (hunk 19 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:4654]: Sure, if people want.

File: pkg/proxy/iptables/proxier_test.go [hunk 33]
```diff
@@ -1802,49 +1796,47 @@ COMMIT
 -A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE
 -A KUBE-MARK-MASQ -j MARK --or-mark 0x4000
 -A KUBE-SERVICES -m comment --comment "ns1/svc1:p80 cluster IP" -m tcp -p tcp -d 172.30.0.41 --dport 80 -j KUBE-SVC-XPGD46QRK7WJZT7O
--A KUBE-SVC-XPGD46QRK7WJZT7O -m comment --comment "ns1/svc1:p80 cluster IP" -m tcp -p tcp -d 172.30.0.41 --dport 80 ! -s 10.0.0.0/8 -j KUBE-MARK-MASQ
+-A KUBE-SVC-XPGD46QRK7WJZT7O -d 172.30.0.41 ! -s 10.0.0.0/8 -j KUBE-MARK-MASQ
```
Comment (robscott) [inline pkg/proxy/iptables/proxier_test.go:1798]: These comments had previously been quite helpful when debugging, any reason for removing them?

File: pkg/proxy/iptables/proxier_test.go (hunk 26 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:1526]: the comment there is explaining what `match[3]` refers to, though apparently not clearly enough...

**Comment by danwinship** [comment]
> incremental review: "proxy/iptables: clean up / clarify iptables chain names a bit"
> 
> This OK and consistent, though I think it's actually retrograde motion. What would you think about a followup that changes ALL of these places that _actually_ relate to a service-port and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport" ?

Including the `KUBE-SVC-` chain name? Or just the variable names?

File: pkg/proxy/iptables/proxier.go (hunk 32 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1297]: Also explained in the commit message: "But remove the ::1 case since that didn't
actually work anyway." (Someone added the IPv6 case when doing the initial IPv6 porting, but we discovered later that the kernel doesn't let you NAT a packet that was sent to ::1.)

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: Split KUBE-SVL-XXX chain out of KUBE-XLB-XXX"

This seems OK, small points.  Some of these (renames, vars) could have been extracted, but OK.

File: pkg/proxy/iptables/proxier.go (hunk 29 above)
[the remark this answers is not in the document]
Comment (robscott) [reply pkg/proxy/iptables/proxier.go:697]: Good call, "C for Cluster" + "L for Local" is actually pretty clever, works for me.

File: pkg/proxy/iptables/proxier_test.go (hunk 33 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:1798]: The testcase diff makes it look like I just ripped out the comment, but it's actually a different rule now, generated in a different part of the code, and in that part of the code, we don't already have access to that comment string, so I just left it without a comment.

I feel like we don't need a comment on _every_ rule... As long as there is _some_ rule in the `KUBE-SVC-XPGD46QRK7WJZT7O` chain with the service name in it (which there is), then it seems like that serves the debugging need.

(And the comments cause some performance issues at scale; there's already code to omit some of them in some cases.)

But anyway, yes, we could add the comment back

**Comment by robscott** [comment]
@danwinship Thanks again for all your work on this! Spent some more time going through this PR today, and had a could broad suggestions:

1. This is a _huge_ PR, would it be possible to split out any bits that aren't strictly required to fix internal traffic policy into follow ups? All of these look like net improvements that we should get in, but it could simplify reviewing this PR if it was a bit smaller. It seems like the following commits might be good candidates for follow up PRs:
    - proxy/iptables: Simplify masquerading rules
    - proxy/iptables: Don't write FW chain if it's not actually needed
    - proxy/iptables: fix up endpoint chain name computation
  
2. The new iptables tests look promising but are sufficiently complex that I'm finding it difficult to fully trust them at this point. Would it be possible to retain the `assertIPTablesRulesEqual` tests until we feel more confident about the new testing structure?

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: Split KUBE-SVL-XXX chain out of KUBE-XLB-XXX"

I'm wrestling with this one.  I thought I was good with it, but as I stare at it more, I can't help but feel there's SOMEONE doing this and we will break them.

Would it really be so bad to leave this (pod/node -> same-node nodeport) as a special-case and treat it like LBVIP ?

**Comment by danwinship** [comment]
> It seems like the following commits might be good candidates for follow up PRs:
> 
> proxy/iptables: Simplify masquerading rules

That's a necessary prereq of the final commit. The current organization of rules mixes up details of Cluster-vs-Local with details of internal-vs-external in confusing (and not always correct) ways.

> proxy/iptables: Don't write FW chain if it's not actually needed

Yes, this is independent of everything else and could be done separately. (Though also, it's pretty small, especially if you look at it with `diff -w`.)

> proxy/iptables: fix up endpoint chain name computation

I forget now why I added this, but something was more confusing without it... but anyway, this could be reviewed and merged independently...

(I'll also mention again that #107471 exists)

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: fix pod-to-LB with externalTrafficPolicy: Local"

Can you explain more about the problem?  I am not sure I understand, and I am worried that this is a meaningful change.  The receiveing end of such a call (pod->LB) should see a packet that looks like a direct pod->pod connection, right?

This could probably be a PR of its own.

**Comment by danwinship** [comment]
> The new iptables tests look promising but are sufficiently complex that I'm finding it difficult to fully trust them at this point. Would it be possible to retain the assertIPTablesRulesEqual tests until we feel more confident about the new testing structure?

The new tests are a zillion times more trustworthy than the old tests. I mean, look at https://github.com/kubernetes/kubernetes/pull/106497/commits/ebd5da081d76570dddf6e70e4395038f617b2052. I hope you don't think that I actually thought through how the rules in `TestOverallIPTablesRulesWithMultipleServices` should have changed based on the code changes, then manually edited each one of the rules, and then ran the unit tests to see if they got the right result. Of course not. I just ran the unit test unchanged, let it fail, and then applied the diff output from the test failure to the test source code. Is it correct? Uh... maybe? I'm guessing none of the people reviewing this PR carefully examined the changed rules either. In the original version of this PR, the changes _weren't_ correct, and neither Tim nor I noticed, because there's really just no way you can look at the raw iptables diffs and figure out everything that changed as a result.

Contrast that with the complete lack of changes to `TestInternalExternalMasquerade` in that same diff, which makes much more sense; no end-user-visible behavior changed as a result of that commit, and so nothing in `TestInternalExternalMasquerade` changed either.

I added the new tests after Tim commented [in an earlier review](https://github.com/kubernetes/kubernetes/pull/106497#pullrequestreview-836795276) that "I have low confidence in the tests..." (And he was right, because the original version of the PR was wrong and the tests did nothing to help us figure that out.)

**Comment by danwinship** [comment]
> Incremental: "proxy/iptables: Split KUBE-SVL-XXX chain out of KUBE-XLB-XXX"
> 
> I'm wrestling with this one. I thought I was good with it, but as I stare at it more, I can't help but feel there's SOMEONE doing this and we will break them.

Someone doing what?

If people are externally modifying kube-proxy's rules, they totally deserve to lose. That is _not_ an API.

> Would it really be so bad to leave this (pod/node -> same-node nodeport) as a special-case and treat it like LBVIP ?

It's not just for NodePort; the XLB/SVL separation is also needed to make `internalTrafficPolicy: Local` work correctly. Right now XLB is doing double-duty as both "handles external traffic" and "handles local traffic policy". If we leave it that way, then we'd need a "KUBE-ILB" chain or something to handle internal local traffic policy in some cases.

(So, we _can_ leave XLB unchanged, but it will probably result in more messiness somewhere else.)

File: pkg/proxy/iptables/proxier.go [hunk 34]
```diff
@@ -1093,6 +1093,33 @@ func (proxier *Proxier) syncProxyRules() {
...
+				// Likewise all traffic to a to ClusterIP from a non-pod
+				// source gets masqueraded (if we know how to distinguish
+				// pods from non-pods).
+				if proxier.localDetector.IsImplemented() {
+					proxier.natRules.Write(
+						"-A", string(svcChain),
+						"-d", svcInfo.ClusterIP().String(),
+						proxier.localDetector.IfNotLocal(),
+						"-j", string(KubeMarkMasqChain))
+				}
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go:1060]: should the not-implemented case here be to masquerade or not?

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: Simplify masquerading rules"

This builds on the previous, which I am still not sure about.  If the previous is pulled to a new PR, this can go with it,

**Comment by danwinship** [comment]
> Incremental: "proxy/iptables: fix pod-to-LB with externalTrafficPolicy: Local"
> 
> Can you explain more about the problem?

This is part of #108526 (and thus, not actually an agreed-upon behavior; I just went ahead with implementing what I felt was going to be the eventual answer there).

Without this change, if you have a service with `internalTrafficPolicy: Local`, and you do a pod-to-LB connection, that connection will only work if there is a local endpoint. Which is exactly the behavior that we went out of our way to _not_ have in the `externalTrafficPolicy: Local` case.

Originally, we fixed the `externalTrafficPolicy: Local` case by saying that pod-to-LB connections should be treated as internal traffic rather than external traffic, and that worked, because there was no such thing as internal traffic policy at that point, so treating them as internal traffic would always make the connection work. But now that there's internal traffic policy too, it seems like the real answer is not "pod-to-LB connections should be treated as internal" but rather "pod-to-LB connections should just work, without the client having to think about traffic policy, _just like external-to-LB connections just work without the client having to think about traffic policy_." That's what this patch implements.

File: pkg/proxy/iptables/proxier.go (hunk 34 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1060]: Not. The not-implemented case is when we can't tell whether the traffic came from a pod or not-from-a-pod, and in that case, we assume that all traffic to the clusterIP must have come from a pod. (Because we don't want to force masquerading in the pod-to-clusterIP case just so that we can make the normally-not-even-sued external-to-clusterIP case work.)

(Note that this is exactly the same behavior as before, I've just consolidated the rules.)

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: Don't write FW chain if it's not actually needed"

This is OK, could be a diff PR

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: fix up endpoint chain name computation"

This feels like a different PR

File: pkg/proxy/iptables/proxier.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/proxy/iptables/proxier.go:986]: +1

**Comment by danwinship** [comment]
So...

> 5845e7323fd proxy/iptables: add packet-flow-based tests of iptables rules
> d706e1e7ac4 proxy/iptables: add a general test of internal vs external traffic

Already also filed separately as #107471. @bowei had comments on this above which I didn't respond to yet and I will probably push fixes both here and there. (And will keep maintaining that PR until one or the other merges.)

> baa6af58f56 proxy/iptables: drop most of the assertIPTablesRulesEqual tests

@robscott called for dropping this (ie, keeping those tests) and I [argued against it here](https://github.com/kubernetes/kubernetes/pull/106497#issuecomment-1072745216) and [also previously here](https://github.com/kubernetes/kubernetes/pull/107471#discussion_r799616323)...

but we could drop it / keep them.

> 2b7ca14b8f5 pkg/proxy: Simplify LocalTrafficDetector

Not necessary to this PR. Filed separately as #108811 and I will pull it out of this one.

> 5758c7acd01 proxy/iptables: move XLB chain initial rule setup

(not controversial)

> 8fffae321d6 proxy/iptables: clean up / clarify iptables chain names a bit

I'll redo this to at least not regress on #108806

> 969264b45c8 proxy/iptables: Split KUBE-SVL-XXX chain out of KUBE-XLB-XXX

@thockin had an ambiguously-worded concern that "someone might be doing this" which I'm waiting for clarification on.

> 110838c37b4 proxy/iptables: fix pod-to-NodePort with externalTrafficPolicy: Local
> e3bb6f668d0 proxy/iptables: fix pod-to-LB with externalTrafficPolicy: Local

vaguely controversial because they implement #108526 which we are not yet totally agreed on, but I don't think it makes sense to try to fix internal traffic policy without agreeing on what "internal traffic" means first, so we need to reach agreement on this. (ie, the ending state of this PR is quite different depending on what we decide there).

> ebd5da081d7 proxy/iptables: Simplify masquerading rules

People assumed this was unrelated, but it's actually a necessary part of the "fix internal-vs-external traffic policy handling" fix that was just possible to split out as a separate logical step. So it can't move. (Well, it could be pulled out as long as it merged before this PR, but also, I wouldn't want to merge it without merging the new tracing unit tests first. Also, it would need to be rewritten if it was going to merge without the previous reorgs. So, it can't move.)

> eecd1d4f1e0 proxy/iptables: Don't write FW chain if it's not actually needed

This is not necessary for this PR and so could be removed for now, but it can't be split out as its own PR yet because it depends on the previous commit.

> 02e2bc8c177 proxy/iptables: fix up endpoint chain name computation

I forget why I did this now. (I'm pretty sure it makes the following commit cleaner somehow.) But I've split it out to #108812 and will remove it from this PR.

> 6a7e153c093 proxy/iptables: fix internal-vs-external traffic policy handling

I think Tim is reading this right now but anyway, obviously this is going to stay, but may need updates

**Review by thockin — COMMENTED** [review]
Incremental: "proxy/iptables: fix internal-vs-external traffic policy handling"

Overall I like it.  It feels like this and the early commits are important top unblock other work, while the ones in the middle could be punted to another PR - is that right ot am I missing something?  Just for the sake of prioritizing merge...

File: pkg/proxy/iptables/proxier.go [hunk 35]
```diff
@@ -1111,19 +1060,24 @@ func (proxier *Proxier) syncProxyRules() {
...
 			if chain, ok := existingNATChains[svcLocalChain]; ok {
 				proxier.natChains.WriteBytes(chain)
 			} else {
 				proxier.natChains.Write(utiliptables.MakeChainLine(svcLocalChain))
 			}
 			activeNATChains[svcLocalChain] = true
+		}
+
+		svcXlbChain := svcInfo.serviceLBChainName
+		if hasEndpoints && svcInfo.NodeLocalExternal() {
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1079]: no, if `externalTrafficPolicy` is `Cluster` you don't need an XLB or SVL chain; LB and NodePort traffic will go to the SVC chain. (This is how it works now as well; XLB is only used for `externalTrafficPolicy: Local`.)

**Review by thockin — COMMENTED** [review]
When I previously asked about making this all more comprehensible, I was not really thinking about an iptables simulator.  I'm very afraid of the opportunity for really subtle mistakes here.

The main advantage of the big blob of iptables-save test is that a human can inspect it.  Th main downside is that it requires a certain level of detail and includes a lot of noise.

I was thinking something more like a syntax-tree instead of a giant string blob.  I should say up-front that this is a perf-critical path, so adding a ton of allocations may kill this idea (or make it so complex as to be pointless).

If I could sketch out the test I'd want, it would be something like:

```
///...setup code
fp.syncProxyRules()

expect := map[string]table {
	"filter": makeTable(
		makeChain("KUBE-SERVICES",
			makeRule(
				comment("abc 123"),
				proto("tcp"),
				dest("1.2.3.4", 80),
				reject())),
		makeChain("KUBE-FORWARD",
			makeRule(
				ctstate("INVALID")
				drop()),
			makeRule(
				comment("xyz 456"),
				mark(0x4000),
				accept())))
```

That would produce a structure that had a `.compare()` method...

IS that actually better than the text blob?  Now that I write it out, I am not
sure.  It might allow better errors or canonicalizing, or something, but it's
not really easier to read, is it?  It hides some of the noise, like iptables
syntax and chain declarations, but that's kind of it.  So now I am not so sure
it's worth doing.

How mad would you be if I suggested we punt the test cleanups to AFTER the
functional changes?

File: pkg/proxy/iptables/proxier_test.go (hunk 33 above)
Comment (thockin) [reply pkg/proxy/iptables/proxier_test.go:1798]: I just learned that rules can exist that JUST have comments.  Should we consider doing less per-rule comments and more per-chain ?

Comment (thockin) [reply pkg/proxy/iptables/proxier_test.go:1798]: (as a followup!!)

**Comment by thockin** [comment]
> >This OK and consistent, though I think it's actually retrograde motion. What would you think about a followup that changes ALL of these places that actually relate to a service-port and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport" ?
>
> Including the KUBE-SVC- chain name? Or just the variable names?

just functions and variables.  I filed a separate issue for it.

**Comment by robscott** [comment]
>The new tests are a zillion times more trustworthy than the old tests. I mean, look at https://github.com/kubernetes/kubernetes/commit/ebd5da081d76570dddf6e70e4395038f617b2052. I hope you don't think that I actually thought through how the rules in TestOverallIPTablesRulesWithMultipleServices should have changed based on the code changes, then manually edited each one of the rules, and then ran the unit tests to see if they got the right result. Of course not. I just ran the unit test unchanged, let it fail, and then applied the diff output from the test failure to the test source code. Is it correct? Uh... maybe? I'm guessing none of the people reviewing this PR carefully examined the changed rules either. In the original version of this PR, the changes weren't correct, and neither Tim nor I noticed, because there's really just no way you can look at the raw iptables diffs and figure out everything that changed as a result.

I mostly agree with this logic, but I'd feel much better if there was at least some period of overlap between new and old tests. I've also take the exact same approach of just updating the tests based on the output of failed tests, but it can be helpful when reviewing code to see if there are large diffs in the iptables config. I definitely don't think that should be our primary means of catching errors or regressions, but it does provide a nice high level overview of the diff that is harder to understand when using just the new tests as a baseline. Since this is all happening in one PR, it's relatively difficult to understand the full impact these changes will have on iptables config without also retaining the full diffs for some period of time.

With any new sufficiently complex test, there is always a chance that there are bugs in the test logic itself. Leaving the old tests in place for awhile would help reduce that risk.

**Comment by thockin** [comment]
>> I'm wrestling with this one. I thought I was good with it, but as I stare at it more, I can't help but feel there's SOMEONE doing this and we will break them.
>
> Someone doing what?

pod -> NodeIP:NodePort

> If people are externally modifying kube-proxy's rules, they totally deserve to lose. That is not an API.

I didn't mean that - I totally agree.  I mean simply that I bet someone
somewhere uses downward API to get `status.hostIP` and then connects to the
node port.

>> Would it really be so bad to leave this (pod/node -> same-node nodeport) as a special-case and treat it like LBVIP ?
>
>It's not just for NodePort; the XLB/SVL separation is also needed to make internalTrafficPolicy: Local work correctly. Right now XLB is doing double-duty as both "handles external traffic" and "handles local traffic policy". If we leave it that way, then we'd need a "KUBE-ILB" chain or something to handle internal local traffic policy in some cases.
>
>(So, we can leave XLB unchanged, but it will probably result in more messiness somewhere else.)

I guess I meant the behavior and not the mechanism - treat pod -> same-node
nodeport the way you treat pod -> LBVIP.  I'm probably not going to die on this
hill...

**Comment by thockin** [comment]
>> Incremental: "proxy/iptables: fix pod-to-LB with externalTrafficPolicy: Local"
>>
>> Can you explain more about the problem?
>
> But now that there's internal traffic policy too, it seems like the real answer is not "pod-to-LB connections should be treated as internal" but rather "pod-to-LB connections should just work, without the client having to think about traffic policy, just like external-to-LB connections just work without the client having to think about traffic policy." That's what this patch implements.

I concur with "pod-to-LB connections should just work".  It's not clear to me
why that demands masquerade, though.

If I have a pod with IP `P` on a node with IP `N`, and I address a service with
clusterIP `C` and LBIP `L`, with backend B:

* Pod->ClusterIP->Backend does not need SNAT
  - src=P, dst=C
  - DNAT
  - src=P, dst=B

  Pod->LBIP->Backend should not needs SNAT?>
  - src=P, dst=L
  - DNAT
  - src=P, dst=B

??

**Comment by danwinship** [comment]
> How mad would you be if I suggested we punt the test cleanups to AFTER the
> functional changes?

I'm fine having _both_ the old tests and the new tests, but I would not want to have only the old tests. I couldn't have gotten this PR working without the new tests, and I wouldn't trust any further updates to it without them.

> pod -> NodeIP:NodePort

(with `externalTrafficPolicy: Local`)

Note that the current behavior is half-broken; we route to all endpoints (local and remote) but we don't masquerade (as we would normally when doing pod -> NodeIP:NodePort with Cluster traffic policy). So with some network plugins, the return traffic may get lost when kube-proxy picks a remote endpoint.

> treat pod -> same-node nodeport the way you treat pod -> LBVIP. 

Yes, we can do that easily enough (and fix the masquerading bug too), but it comes with the oddity that pod-to-same-node-nodeport and pod-to-remote-nodeport now behave inconsistently. (But, we have that oddity now, so if we're worried more about edge-case backward-compat than about consistency, then this is probably the way to go.)

> I concur with "pod-to-LB connections should just work". It's not clear to me
why that demands masquerade, though.

Well, currently pod-to-LB with Cluster policy masquerades. I think there may be cases where this is necessary? (Though maybe the same cases where you need `--masquerade-all` anyway?) Gotta run now but I'll think about this more...

**Comment by thockin** [comment]
>> How mad would you be if I suggested we punt the test cleanups to AFTER the
>> functional changes?
>
> I'm fine having _both_ the old tests and the new tests, but I would not want to have only the old tests. I couldn't have gotten this PR working without the new tests, and I wouldn't trust any further updates to it without them.
 
I'll have to spend time really looking at the tests again - I got scared and jumped over them so I could make it thru the PR today :)

>> pod -> NodeIP:NodePort
>
> (with `externalTrafficPolicy: Local`)
> 
> Note that the current behavior is half-broken; we route to all endpoints (local and remote) but we don't masquerade (as we would normally when doing pod -> NodeIP:NodePort with Cluster traffic policy). So with some network plugins, the return traffic may get lost when kube-proxy picks a remote endpoint.

This is what I don't visualize.  Even if it picks a remote EP, Why does it need SNAT?  The return path (to the pod's IP) will still come to the same node, so the conntrack should rewrite it back?

>> treat pod -> same-node nodeport the way you treat pod -> LBVIP. 
> 
> Yes, we can do that easily enough (and fix the masquerading bug too), but it comes with the oddity that pod-to-same-node-nodeport and pod-to-remote-nodeport now behave inconsistently. (But, we have that oddity now, so if we're worried more about edge-case backward-compat than about consistency, then this is probably the way to go.)

Yeah, it's this corner-case that, while dirty, seems worth NOT breaking.  It's
odd and special, but it seems not terrible.

> > I concur with "pod-to-LB connections should just work". It's not clear to me
> why that demands masquerade, though.
> 
> Well, currently pod-to-LB with Cluster policy masquerades. I think there may be cases where this is necessary? (Though maybe the same cases where you need `--masquerade-all` anyway?) Gotta run now but I'll think about this more...

Thanks, me too.

File: pkg/proxy/iptables/proxier_test.go (hunk 21 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:1360]: the error from ParseCIDR always includes the input string

File: pkg/proxy/topology.go [hunk 36]
```diff
@@ -23,78 +23,155 @@ import (
...
 	}
 
-	if utilfeature.DefaultFeatureGate.Enabled(features.ServiceInternalTrafficPolicy) && svcInfo.NodeLocalInternal() {
-		return FilterLocalEndpoint(endpoints)
+	if svcInfo.NodeLocalInternal() || svcInfo.NodeLocalExternal() {
+		// Pre-scan the endpoints, to figure out which type of endpoint Local
+		// traffic policy will use, and also to see if there are any usable
+		// endpoints anywhere in the cluster.
+		var hasLocalReadyEndpoints, hasLocalServingTerminatingEndpoints bool
+		for _, ep := range endpoints {
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/topology.go:57]: That `getFilterFunc(false)` / `getFilterFunc(true)` is non-obvious...

But anyway, this is all going to totally change if PTE applies to `clusterEndpoints`.

File: pkg/proxy/iptables/proxier.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:986]: I was wrong before; even with the change to PTE, it's still possible for there to be endpoints in localEndpoints that aren't in clusterEndpoints, if topology is enabled, and there are endpoints on the local node that aren't hinted for the local node's zone.

**Comment by danwinship** [comment]
OK, I reverted the attempt to fix the short-circuiting inconsistencies. So now, we preserve the existing behavior that pod-to-NodePort and pod-to-LB with `externalTrafficPolicy: Cluster` sends to all endpoints _with_ masquerading, but pod-to-nodePort and pod-to-LB with `externalTrafficPolicy: Local` sends to all endpoints _without_ masquerading. We can figure out later whether we should always be masquerading or always be not masquerading there...

(So this means "`proxy/iptables: fix pod-to-NodePort with externalTrafficPolicy: Local`" and "`proxy/iptables: fix pod-to-LB with externalTrafficPolicy: Local`" went away because we don't want those "fixes", and "`proxy/iptables: Simplify masquerading rules`" has to go away because we can't simplify the rules while they're inconsistent.)

Meanwhile, bringing back the `assertIPTablesRulesEquals` tests revealed that we were outputting unused rules in some cases (which `assertIPTablesRulesEquals` was checking for but `runPacketFlowTests` was not so I hadn't caught it before), and fixing that required adding a bit more complexity to the final commit (eg, we should not output XLB and SVL chains if the service claims to be `externalTrafficPolicy: Local` but it only has a ClusterIP).

As also mentioned in a comment above, I realized that even when we extend ProxyTerminatingEndpoints to include Cluster traffic policy, it's still possible to have `clusterEndpoints` not be a superset of `localEndpoints`, because of topology. So I couldn't simplify anything there.

File: pkg/proxy/iptables/proxier.go [hunk 37]
```diff
@@ -950,15 +949,6 @@ func (proxier *Proxier) syncProxyRules() {
 	// Accumulate NAT chains to keep.
 	activeNATChains := map[utiliptables.Chain]bool{} // use a map as a set
 
-	// We are creating those slices ones here to avoid memory reallocations
-	// in every loop. Note that reuse the memory, instead of doing:
-	//   slice = <some new slice>
-	// you should always do one of the below:
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:937]: is this memory reallocation no longer a problem so we can remove it?

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:937]: https://pkg.go.dev/sync#example-Pool

Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:937]: That seems to be for avoiding allocations you are doing directly. I don't think there's any way that could be used to optimize append()s

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:937]: yeah, I realized later that this is about slices .... that is much trickier ... 
anyway, this guy seem that studied this topic, https://github.com/xdg-go/zzz-slice-recycling , just I found it interesting and I wanted to share it, not related to this PR

**Comment by thockin** [comment]
I'm looking at tests now.

> The new tests are a zillion times more trustworthy than the old tests. I mean, look at https://github.com/kubernetes/kubernetes/commit/ebd5da081d76570dddf6e70e4395038f617b2052. I hope you don't think that I actually thought through how the rules in TestOverallIPTablesRulesWithMultipleServices should have changed based on the code changes

To me, this means "TestOverallIPTablesRulesWithMultipleServices" is not a super
useful test.  For smaller, targetted cases, we SHOULD be able to look at the
diff and reason about it.

**Comment by danwinship** [comment]
That's a plausible argument...

(It's nice as a reference, and I guess it's useful if you're trying to refactor internal logic where you want to verify that the refactoring _didn't_ change the generated rules...)

**Comment by danwinship** [comment]
@thockin if you're definitely OK with the new test cases _eventually_ merging but want some improvements to them first, and we're concerned about code freeze timing, then I'm OK with removing them from this PR so we can merge it now, and merging #107471 later. (Presumably getting an exception to merge #107471 late would be trivial anyway since it's just adding tests.)

**Comment by thockin** [comment]
SGTM.  I am OK with the tests, just had a lot of smaller issues.

**Comment by aojea** [comment]
> (Presumably getting an exception to merge #107471 late would be trivial anyway since it's just adding tests.)

tests are allowed after code freeze https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#test-freeze

File: pkg/proxy/iptables/proxier_test.go [hunk 38]
```diff
@@ -4473,10 +4472,14 @@ COMMIT
...
 :KUBE-POSTROUTING - [0:0]
 :KUBE-MARK-MASQ - [0:0]
+:KUBE-SVL-AQI2S6QIMU7PVVRP - [0:0]
 -A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
 -A KUBE-POSTROUTING -j MARK --xor-mark 0x4000
 -A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE
 -A KUBE-MARK-MASQ -j MARK --or-mark 0x4000
+-A KUBE-SERVICES -m comment --comment "ns1/svc1 cluster IP" -m tcp -p tcp -d 172.30.1.1 --dport 80 -j KUBE-SVL-AQI2S6QIMU7PVVRP
+-A KUBE-SVL-AQI2S6QIMU7PVVRP -m comment --comment "ns1/svc1 cluster IP" -m tcp -p tcp -d 172.30.1.1 --dport 80 ! -s 10.0.0.0/8 -j KUBE-MARK-MASQ
+-A KUBE-SVL-AQI2S6QIMU7PVVRP -m comment --comment "ns1/svc1 has no local endpoints" -j KUBE-MARK-DROP
```
Comment (thockin) [inline pkg/proxy/iptables/proxier_test.go:4482]: The change to drop rather than reject will have some negative consequences - clients have to time out.  I swear we used this in a test, but I can't find where, so maybe it went away.  Anyone think this will be a problem?  @aojea ?

File: pkg/proxy/service.go [hunk 39]
```diff
@@ -139,6 +139,24 @@ func (info *BaseServiceInfo) HintsAnnotation() string {
 	return info.hintsAnnotation
 }
 
+// ExternallyAccessible is part of ServicePort interface.
+func (info *BaseServiceInfo) ExternallyAccessible() bool {
+	return info.nodePort != 0 || len(info.loadBalancerStatus.Ingress) != 0 || len(info.externalIPs) != 0
```
Comment (thockin) [inline pkg/proxy/service.go:144]: Should this include node ports?  Especially is fame-node nodeport is == LBVIP semantics?  Mayber a followup

File: pkg/proxy/topology.go [hunk 40]
```diff
@@ -23,78 +23,165 @@ import (
...
+
+	if !svcInfo.UsesLocalEndpoints() {
+		allReachableEndpoints = clusterEndpoints
+		return
+	}
+
+	// Pre-scan the endpoints, to figure out which type of endpoint Local
+	// traffic policy will use, and also to see if there are any usable
+	// endpoints anywhere in the cluster.
+	var hasLocalReadyEndpoints, hasLocalServingTerminatingEndpoints bool
```
Comment (thockin) [inline pkg/proxy/topology.go:70]: I still feel like this can be more comprehensible, but I am OK to follow up

**Review by thockin — COMMENTED** [review]
Oversall I dig it.  I went thru it in my own tree and made sute it made sense as a whole.

I propose 2 small variable renames (extra commit or followup OK):

```diff
-               svcChain := svcInfo.servicePortChainName
-               svcLocalChain := svcInfo.serviceLocalChainName
+               policyClusterChain := svcInfo.servicePortChainName
+               policyLocalChain := svcInfo.serviceLocalChainName
                svcXlbChain := svcInfo.serviceLBChainName
 
-               internalTrafficChain := svcChain
-               loadBalancerTrafficChain := svcChain
+               internalTrafficChain := policyClusterChain
+               externalTrafficChain := policyClusterChain
```

Which yields things like:

```diff
                if svcInfo.NodeLocalInternal() {
-                       internalTrafficChain = svcLocalChain
+                       internalTrafficChain = policyLocalChain
                }
                if svcInfo.NodeLocalExternal() {
-                       loadBalancerTrafficChain = svcXlbChain
+                       // XLB does some work before ending up at policyLocalChain
+                       externalTrafficChain = svcXlbChain
                }
 
                if hasEndpoints && svcInfo.UsesClusterEndpoints() {
                        // Create the Cluster traffic policy chain, retaining counters if possible.
-                       if chain, ok := existingNATChains[svcChain]; ok {
+                       if chain, ok := existingNATChains[policyClusterChain]; ok {
                                proxier.natChains.WriteBytes(chain)
                        } else {
-                               proxier.natChains.Write(utiliptables.MakeChainLine(svcChain))
+                               proxier.natChains.Write(utiliptables.MakeChainLine(policyClusterChain))
                        }
-                       activeNATChains[svcChain] = true
+                       activeNATChains[policyClusterChain] = true
```

Alternately, `svcChain` and `svlChain` but I find that harder to distinguish.

I'd also propose renaming `NodeLocalExternal` to `ETPLocal` or `ExternalLocal`
and ditto for internal.

**Comment by dims** [comment]
@aojea @thockin is this ready to go?

**Comment by danwinship** [comment]
> ```diff
> -               loadBalancerTrafficChain := svcChain
> +               externalTrafficChain := policyClusterChain
> ```

oops that's a leftover from before when LB/External was handled differently than NodePort so we had both `loadBalancerTrafficChain` and `nodePortTrafficChain`.

> I'd also propose renaming `NodeLocalExternal` to `ETPLocal` or `ExternalLocal`
> and ditto for internal.

yes, definitely, the current naming is really weird

File: pkg/proxy/iptables/proxier.go [hunk 41]
```diff
@@ -1168,15 +1125,15 @@ func (proxier *Proxier) syncProxyRules() {
 				// for you.  Since that might bounce off-node, we masquerade here.
 				// If/when we support "Local" policy for VIPs, we should update this.
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1126]: oh, I need to update that comment. (It had gone away with the "simplify masquerading" commit before but it's back now...)

Anyway, this PR does not change any behavior here. The behavior of external-to-ClusterIP with Cluster traffic policy has never changed, and since the introduction of `internalTrafficPolicy`, the behavior of external-to-ClusterIP with iTP:Local has (AFAIK) always been that the connection gets Local traffic policy. If you don't want that, then don't use iTP:Local with your externally-accessible ClusterIPs...

File: pkg/proxy/iptables/proxier.go [hunk 42]
```diff
@@ -1378,20 +1334,15 @@ func (proxier *Proxier) syncProxyRules() {
 			)
 		}
 
-		if !hasEndpoints {
-			continue
+		if len(clusterEndpoints) != 0 {
+			// Write rules jumping from svcChain to clusterEndpoints
+			proxier.writeServiceToEndpointRules(svcNameString, svcInfo, svcChain, clusterEndpoints, args)
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1339]: No, because we still need the cluster endpoints for the pod-to-LB special case. Sometimes. The logic is in `svcInfo.UsesClusterEndpoints()` now, and clusterEndpoints will be nil if that returned false, but I can just call UsesClusterEndpoint again here since that would be a little clearer

File: pkg/proxy/iptables/proxier.go [hunk 43]
```diff
@@ -1091,6 +1091,35 @@ func (proxier *Proxier) syncProxyRules() {
...
+			// First rule in the chain redirects all pod -> external VIP
+			// traffic to the Service's ClusterIP instead. This happens
+			// whether or not we have local endpoints; only if localDetector
+			// is implemented
+			if proxier.localDetector.IsImplemented() {
+				proxier.natRules.Write(
+					"-A", string(svcXlbChain),
+					"-m", "comment", "--comment",
+					`"Redirect pods trying to reach external loadbalancer VIP to clusterIP"`,
+					proxier.localDetector.IfLocal(),
```
[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:1073]: if external traffic policy is Cluster then you don't need a special case, because the non-special case already works

File: pkg/proxy/iptables/proxier_test.go (hunk 38 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:4482]: It will have consequences, but I was assuming they were positive...

Why is there an internal client trying to connect to a local endpoint that doesn't exist? There are basically two scenarios: (a) the client is confused and should not be trying to connect to the service from this node; (b) the client is correct, and there _should_ be an endpoint on this node, but for some reason there isn't. In the first case, rejecting the connection is the best answer, but it seems like the second case is more likely (eg, the endpoint pod is restarting) and in that case, dropping is better because it will let the client retry and eventually succeed.

(Note: eTP:Local also drops rather than rejecting, so this makes internal and external traffic policy behave the same. Also, I'm pretty sure there was no explicit decision to make iTP:Local do reject rather than drop before; it just happened that way because of how iTP was implemented.)

File: pkg/proxy/service.go (hunk 39 above)
Comment (danwinship) [reply pkg/proxy/service.go:144]: Yes, it should (and does) include nodeports. The function is answering the question "Can the service ever receive traffic for which we would need to apply `externalTrafficPolicy`?".

File: pkg/proxy/iptables/proxier.go (hunk 41 above)
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/proxy/iptables/proxier.go]: I guess I am arguing that IPT=Local broke an older semantic and I am not sure if that's OK

File: pkg/proxy/iptables/proxier.go (hunk 43 above)
[the remark this answers is not in the document]
Comment (thockin) [reply pkg/proxy/iptables/proxier.go:1086]: yes, I see.  That's borderline "too clever" - we can see if that can be made cleaner later.

File: pkg/proxy/iptables/proxier_test.go (hunk 38 above)
Comment (thockin) [reply pkg/proxy/iptables/proxier_test.go:4482]: > dropping is better because it will let the client retry and eventually succeed.

Why wouldn't a client retry in case of REJECT?  I guess they'd get a different error code...

File: pkg/proxy/service.go (hunk 39 above)
Comment (thockin) [reply pkg/proxy/service.go:144]: Sorry I totally missed the `nodePort` in there.  wow.

**Comment by thockin** [comment]
/lgtm
/retest
/hold

Hold for last looks by anyone, in particular @robscott @andrewsykim @aojea @khenidak

**Comment by thockin** [comment]
FWIW I am looking at a minor restructuring and renaming built on top of this to simpligfy the XLB chain, will post a PR when ready

File: pkg/proxy/iptables/proxier_test.go (hunk 38 above)
Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:4482]: I think that silently dropping makes the retry to depend on the OS timers, and is not the best solution ... the client code should handle these situations and we should inform the client something is wrong

Also, the REJECT sends a RST that clear conntrack entries all the way down ... 


The e2e test is here https://github.com/kubernetes/kubernetes/blob/515f8342d342ce5d017df26838d6dd36fb162361/test/e2e/network/service.go#L1788

**Review by andrewsykim — COMMENTED** [review]
/lgtm

Thanks for the much-needed refactor @danwinship!

**Comment by aojea** [comment]
however, I still think that dropping should only be used for firewalling/filtering, and connections to not ready/prepared endpoints should be rejected instead

https://github.com/kubernetes/kubernetes/pull/106497#discussion_r835965512

File: pkg/proxy/iptables/proxier_test.go (hunk 38 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:4482]: And in fact, [the internal traffic policy KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy#proposal) actually says that traffic is supposed to be dropped:

> Introduce a new field in Service `spec.internalTrafficPolicy`. The field will have 2 codified values:
> 
> 1. Cluster (default): route to all cluster-wide endpoints (or use topology aware subsetting if enabled).
> 2. Local: only route to node-local endpoints, drop otherwise.

Comment (thockin) [reply pkg/proxy/iptables/proxier_test.go:4482]: I don't think we've alweays been precise about "drop" vs "reject".  Yeah, the OS will retry EVENTUALLY.  But so will clients.

Anyway, we can do a followup discussion here.

Comment (aojea) [reply pkg/proxy/iptables/proxier_test.go:4482]: I understand Dan reasoning, but I'm not sure those assumptions that this will only happen on race conditions are always true
> under the assumption that we hit a race condition (endpoint exited but LB hasn't re-polled node health again yet) and if we let the client try again then it will (eventually) succeed

I think that is better to notify clients because it encourage client applications to handle network errors, also, defaults OS values are very conservative

https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/

> The retries are staggered at 1s, 3s, 7s, 15s, 31s, 63s marks (the inter-retry time starts at 2s and then doubles each time). By default the whole process takes 130 seconds, until the kernel gives up with the ETIMEDOUT errno

dropping for me is something you use for firewalling, when you don't care at all about the clients ... but this was always a controversial topic :smile:

File: pkg/proxy/topology.go [hunk 44]
```diff
@@ -23,78 +23,165 @@ import (
...
+	for _, ep := range endpoints {
+		if ep.IsReady() {
+			hasAnyEndpoints = true
+			if ep.GetIsLocal() {
+				hasLocalReadyEndpoints = true
```
Comment (aroradaman) [inline pkg/proxy/topology.go:75]: @danwinship we can exit the loop immediately here after discovering local ready endpoint, right ?
(minor optimisation)

Comment (danwinship) [reply pkg/proxy/topology.go:75]: yes, but, https://github.com/kubernetes/kubernetes/pull/119532#issuecomment-1660446767
