### PR TITLE
rkt: Generate a new Network Namespace for each Pod

### LINKED ISSUE #45149: rkt Pod looses the network
**What keywords did you search in Kubernetes issues before filing this one?** 
rkt netns

---

**Is this a BUG REPORT**

**Kubernetes version**:
1.5, 1.6, master

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1298.6.0
VERSION_ID=1298.6.0
BUILD_ID=2017-03-14-2119
```
- **Kernel** (e.g. `uname -a`):
```
uname -a
Linux no-1-172-20-0-13 4.9.9-coreos-r1 #1 SMP Tue Mar 14 21:09:42 UTC 2017 x86_64 Westmere E56xx/L56xx/X56xx (Nehalem-C) GenuineIntel GNU/Linux
```
- **Install tools**:
```
/opt/bin/rkt version
rkt Version: 1.25.0
appc Version: 0.8.10
Go Version: go1.7.4
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```
CNI 0.5.2
- **Others**:

Kubelet setup:
```
systemctl cat kubelet
# /etc/systemd/system/kubelet.service
[Unit]
After=rkt-api.service
Requires=rkt-api.service
After=kube-apiserver.service
[Service]
ExecStartPre=/bin/ls -l \
  /etc/vault.d/kubernetes/kubelet.certificate \
  /etc/vault.d/kubernetes/kubelet.private_key \
  /etc/vault.d/kubernetes/kubelet.issuing_ca
ExecStartPre=/bin/mkdir -pv /var/lib/kubelet/kubeconfig
ExecStart=/opt/rootfs/hyperkube kubelet \
  --hairpin-mode=none \
  --network-plugin=cni \
  --cni-bin-dir=/opt/rootfs/usr/bin \
  --cni-conf-dir=/etc/rkt/net.d \
  --hostname-override=172.20.0.13 \
  --node-ip=172.20.0.13 \
  --register-schedulable=false \
  --allow-privileged=true \
  --enable-custom-metrics \
  --api-servers=http://127.0.0.1:8080 \
  --node-labels=node=true \
  --cloud-provider="" \
  --container-runtime=rkt \
  --rkt-path=/opt/rootfs/usr/bin/rkt \
  --v=2 \
  --enable-cri=false \
  --tls-cert-file=/etc/vault.d/kubernetes/kubelet.certificate \
  --tls-private-key-file=/etc/vault.d/kubernetes/kubelet.private_key \
  --client-ca-file=/etc/vault.d/kubernetes/kubelet.issuing_ca
Restart=always
RestartSec=5s
[Install]
WantedBy=multi-user.target
```
The CNI configuration:
```
cat /etc/rkt/net.d/10-k8s.conf 
{
  "name": "bond0",
  "type": "macvlan",
  "master": "bond0",
  "ipam": {"dataDir": "/run/cni-ipam", "gateway": "172.20.0.1", "rangeEnd": "172.20.13.254", "rangeStart": "172.20.13.1", "routes": [{"dst": "0.0.0.0/0"}], "subnet": "172.20.0.0/16", "type": "host-local"}
}
```

**What happened**:

If running Pod with `hostNetwork: false` is failing, the pod restarts immediatly and looses its IP address after the garbage collection.

**What you expected to happen**:
The Pod keeps the new IP address

**How to reproduce it** (as minimally and precisely as possible):
Start a rkt api-service and a kubelet without kube-apiserver like:
```
go/src/k8s.io/kubernetes/_output/bin/kubelet \
--network-plugin=cni \
--cni-bin-dir=/opt/bin/cni \
--cni-conf-dir=/etc/rkt/net.d \
--pod-manifest-path=$PATHTO/kube-sandbox/manifests \
--register-schedulable=false \
--enable-server=false \
--register-node=false \
--cloud-provider="" \
--enable-cri=false  \
--container-runtime=rkt \
--rkt-path=/usr/bin/rkt \
--v=4
```
With a simple Pod in the `$PATHTO/kube-sandbox/manifests`:
```
cat manifests/debian.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
spec:
  containers:
  - name: debian
    image: enjoliver.local/debian:latest
    imagePullPolicy: IfNotPresent
    command:
    - /dgr/bin/busybox
    - httpd
    - -fv

```
Leads you to the following scenario:
```
# rkt l
UUID		APP	IMAGE NAME			STATE	CREATED		STARTED		NETWORKS
29b7d7e3	debian	enjoliver.local/debian:latest	running	6 seconds ago	5 seconds ago	
# rkt l
UUID		APP	IMAGE NAME			STATE	CREATED		STARTED		NETWORKS
29b7d7e3	debian	enjoliver.local/debian:latest	running	18 seconds ago	17 seconds ago	
# rkt enter 29b7d7e3 /dgr/bin/busybox ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if51: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 0a:58:ac:14:00:4e brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.78/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b46f:3ff:fe06:933b/64 scope link 
       valid_lft forever preferred_lft forever
# ping -c 1 172.20.0.78
PING 172.20.0.78 (172.20.0.78) 56(84) bytes of data.
64 bytes from 172.20.0.78: icmp_seq=1 ttl=64 time=0.110 ms

--- 172.20.0.78 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.110/0.110/0.110/0.000 ms
# rkt stop 29b7d7e3 ; sleep 1 ; rkt l
"29b7d7e3-eb8f-42b4-9962-56610e2380cc"
UUID		APP	IMAGE NAME			STATE	CREATED		STARTED		NETWORKS
29b7d7e3	debian	enjoliver.local/debian:latest	exited	1 minute ago	1 minute ago	
2f8b2db0	debian	enjoliver.local/debian:latest	running	now		now		
# rkt enter 2f8b2db0 /dgr/bin/busybox ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if52: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether 0a:58:ac:14:00:4f brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.79/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::fc41:21ff:fe76:d567/64 scope link 
       valid_lft forever preferred_lft forever
# rkt l
UUID		APP	IMAGE NAME			STATE	CREATED		STARTED		NETWORKS
2f8b2db0	debian	enjoliver.local/debian:latest	running	1 minute ago	1 minute ago	
# rkt enter 2f8b2db0 /dgr/bin/busybox ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
# ip netns list | wc -l
0
```

**Anything else we need to know**:
This is because the Kubernetes Pod with rkt is running inside an unique [netns](https://github.com/kubernetes/kubernetes/blob/a8e940041e242a67ab976e8f464bb6fb61c251fe/pkg/kubelet/rkt/rkt.go#L1290) linked to the `Pod.id`, also documented [here](https://github.com/kubernetes/kubernetes/blob/a8e940041e242a67ab976e8f464bb6fb61c251fe/pkg/kubelet/rkt/rkt.go#L1851-L1855)

When a Pod restarts, it keeps the same network namespace so the garbage collection will clean the old network ressources and the current ones.
If you setup a Kubernetes Probe like a httpGet, you'll get an endless restarting Pod.

I'm working on it and want to refer this issue in code comments / PR.

### PR DESCRIPTION
**Pull request by JulienBalestra**
**What this PR does / why we need it**:

This PR concerns the Kubelet with the Container runtime rkt.
Currently, when a Pod stops and the kubelet restart it, the Pod will use the **same network namespace** based on its PodID.

When the Garbage Collection is triggered, it delete all the old resources and the current network namespace.

The Pods and all containers inside it loose the _eth0_ interface.
I explained more in details in #45149 how to reproduce this behavior.

This PR generates a new unique network namespace name for each new/restarting Pod.
The Garbage collection retrieve the correct network namespace and remove it safely.

**Which issue this PR fixes** : 

fix #45149 

**Special notes for your reviewer**:

Following @yifan-gu guidelines, so maybe expecting him for the final review.

**Release note**:

`NONE`

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

File: pkg/kubelet/rkt/rkt.go [hunk 1]
```diff
@@ -1850,62 +1871,84 @@ func podIsActive(pod *rktapi.Pod) bool {
 
 // GetNetNS returns the network namespace path for the given container
 func (r *Runtime) GetNetNS(containerID kubecontainer.ContainerID) (string, error) {
-	// This is a slight hack, kubenet shouldn't be asking us about a container id
-	// but a pod id. This is because it knows too much about the infra container.
-	// We pretend the pod.UID is an infra container ID.
-	// This deception is only possible because we played the same trick in
+	// Currently the containerID is an UUID for a network namespace
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: s/an/a

File: pkg/kubelet/rkt/rkt.go [hunk 2]
```diff
@@ -2367,26 +2429,31 @@ func (r *Runtime) GetPodStatus(uid kubetypes.UID, name, namespace string) (*kube
 		}
 	}
 
-	// If we are running no-op network plugin, then get the pod IP from the rkt pod status.
-	if r.network.PluginName() == network.DefaultPluginName {
-		if latestPod != nil {
+	if latestPod != nil {
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: Can we change to:
```go
if latestPod == nil {
    glog.Warningf()
    return podStatus, nil
}
```

So that we don't need the big `if` block.
}

File: pkg/kubelet/rkt/rkt.go [hunk 3]
```diff
@@ -2367,26 +2429,31 @@ func (r *Runtime) GetPodStatus(uid kubetypes.UID, name, namespace string) (*kube
...
+		// If we are running no-op network plugin, then get the pod IP from the rkt pod status.
+		if r.network.PluginName() == network.DefaultPluginName {
 			for _, n := range latestPod.Networks {
 				if n.Name == defaultNetworkName {
 					podStatus.IP = n.Ipv4
 					break
 				}
 			}
+		} else {
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: nit: Can just return in the above `break`, so the `else` can be removed. But it's ok to keep it here as it's not big.

**Comment by yifan-gu** [comment]
LGTM except some small nits. Thanks for the fix @JulienBalestra !

**Comment by JulienBalestra** [comment]
I made the changes and I squashed them.
Thanks for the review @yifan-gu

**Comment by yifan-gu** [comment]
@JulienBalestra LGTM, but the CI is failing, might need rebase?

**Comment by JulienBalestra** [comment]
@yifan-gu That's better but **Jenkins GCE etcd3 e2e** is failing now.
@k8s-bot gce etcd3 e2e test this
