### PR TITLE
Ensure terminal pods maintain terminal status

### LINKED ISSUE #105358: Pods go into error state after kubelet-initiated eviction
#### What happened:

When a pod is evicted under resource pressure, it goes into an error state.

#### What you expected to happen:

The pod terminates normally.

#### How to reproduce it (as minimally and precisely as possible):

Note that the 130GB file is based on **90% of total disk space - current utilization** to hit the default eviction threshold.

```bash
ehashman@fedora:~/src/k8s$ cat ~/tmp/disk-pressure.yml 
kind: Pod
apiVersion: v1
metadata:
  name: evictme
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    command: ["sh", "-c", "fallocate -l 130G file; sleep 100000"]

ehashman@fedora:~/src/k8s$ cluster/kubectl.sh get pod
No resources found in default namespace.

ehashman@fedora:~/src/k8s$ cluster/kubectl.sh apply -f ~/tmp/disk-pressure.yml 
pod/evictme created

ehashman@fedora:~/src/k8s$ cluster/kubectl.sh get pod
NAME      READY   STATUS    RESTARTS   AGE
evictme   1/1     Running   0          3s

ehashman@fedora:~/src/k8s$ cluster/kubectl.sh get pod
NAME      READY   STATUS    RESTARTS   AGE
evictme   1/1     Evicted   0          10s

ehashman@fedora:~/src/k8s$ cluster/kubectl.sh get pod
NAME      READY   STATUS   RESTARTS   AGE
evictme   0/1     Error    0          21s
```

Full pod spec after going into error state:

<details>

```
ehashman@fedora:~/src/k8s$ cluster/kubectl.sh get pod -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"evictme","namespace":"default"},"spec":{"containers":[{"command":["sh","-c","fallocate -l 130G file; sleep 10000"],"image":"k8s.gcr.io/e2e-test-images/nginx:1.14-2","name":"busybox"}],"terminationGracePeriodSeconds":10}}
    creationTimestamp: "2021-10-01T19:10:20Z"
    name: evictme
    namespace: default
    resourceVersion: "519"
    uid: e9e27b78-d722-4c2c-96f3-7a22877d75bb
  spec:
    containers:
    - command:
      - sh
      - -c
      - fallocate -l 130G file; sleep 10000
      image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
      imagePullPolicy: IfNotPresent
      name: busybox
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-dctrp
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: 127.0.0.1
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 10
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-dctrp
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2021-10-01T19:10:59Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2021-10-01T19:11:13Z"
      message: 'containers with unready status: [busybox]'
      reason: ContainersNotReady
      status: "False"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2021-10-01T19:11:13Z"
      message: 'containers with unready status: [busybox]'
      reason: ContainersNotReady
      status: "False"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2021-10-01T19:10:59Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://ea630f3b1b7e83763df0693d0e617b475433486462abd0ec01611f146c883516
      image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
      imageID: docker-pullable://k8s.gcr.io/e2e-test-images/nginx@sha256:13616070e3f29de4417eee434a8ef472221c9e51b3d037b5a6b46cef08eb7443
      lastState: {}
      name: busybox
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: docker://ea630f3b1b7e83763df0693d0e617b475433486462abd0ec01611f146c883516
          exitCode: 137
          finishedAt: "2021-10-01T19:11:13Z"
          reason: Error
          startedAt: "2021-10-01T19:11:00Z"
    hostIP: 127.0.0.1
    phase: Running
    podIP: 172.17.0.3
    podIPs:
    - ip: 172.17.0.3
    qosClass: BestEffort
    startTime: "2021-10-01T19:10:59Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
</details>

#### Anything else we need to know?:

See also https://bugzilla.redhat.com/show_bug.cgi?id=1997478#c25

Eviction tests (https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-eviction) are currently broken (https://github.com/kubernetes/kubernetes/issues/102782), there's a PR up to fix: https://github.com/kubernetes/kubernetes/pull/104304

#### Environment:
- Kubernetes version (use `kubectl version`): HEAD/1.23.x (kubeletVersion="v1.23.0-alpha.3.47+d551560a78292e")
- Cloud provider or hardware configuration: local-up-cluster
- OS (e.g: `cat /etc/os-release`), Kernel (e.g. `uname -a`):

```
ehashman@fedora:~/src/k8s$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
ehashman@fedora:~/src/k8s$ uname -a
Linux fedora 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

- Install tools: local-up-cluster.sh
- Network plugin and version (if this is a network-related bug): N/A
- Others: Also reproducible on OpenShift 4.9 (1.23-based)

/sig node
/cc @rphillips @smarterclayton

### PR DESCRIPTION
**Pull request by ehashman**
Alternative to #105411. This is a slightly tighter patch and appears to also fix the issue.

#### What type of PR is this?

/kind bug
/sig node
/priority critical-urgent

#### What this PR does / why we need it:

Avoids overwriting statuses or phase on terminated pods.

#### Which issue(s) this PR fixes:

Fixes #105358

#### Special notes for your reviewer 

This avoids an `isTerminated` check, which we may not need. We can fix the container restart count issue separately.

#### Does this PR introduce a user-facing change?

```release-note
Evicted and other terminated pods will no longer revert to Running phase
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/status/status_manager_test.go [hunk 1]
```diff
@@ -622,6 +622,64 @@ func TestTerminatePod(t *testing.T) {
 	assert.Equal(t, newStatus.Message, firstStatus.Message)
 }
 
+func TestTerminatePodWaiting(t *testing.T) {
```
Comment (ehashman) [inline pkg/kubelet/status/status_manager_test.go:625]: Basically copied from test above, but changed (init)container 3 to waiting status

File: pkg/kubelet/kubelet_pods_test.go [hunk 2]
```diff
@@ -2595,6 +2595,42 @@ func Test_generateAPIPodStatus(t *testing.T) {
 				},
 			},
 		},
+		{
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet_pods_test.go:2598]: Add another condition that swaps pod and previousStatus, and then one that has restart never and all containers have currentStatus = terminated

Comment (ehashman) [reply pkg/kubelet/kubelet_pods_test.go:2598]: The first is already covered with https://github.com/kubernetes/kubernetes/blob/c32e56912852a2f902426394fdbe5950176e1eae/pkg/kubelet/kubelet_pods_test.go#L2563-L2597 but we don't have anything for restart never so adding that now

File: pkg/kubelet/kubelet_pods_test.go [hunk 3]
```diff
@@ -2595,6 +2595,85 @@ func Test_generateAPIPodStatus(t *testing.T) {
...
+				QOSClass: v1.PodQOSBestEffort,
+				Conditions: []v1.PodCondition{
+					{Type: v1.PodInitialized, Status: v1.ConditionTrue, Reason: "PodCompleted"},
+					{Type: v1.PodReady, Status: v1.ConditionFalse, Reason: "PodCompleted"},
+					{Type: v1.ContainersReady, Status: v1.ConditionFalse, Reason: "PodCompleted"},
+					{Type: v1.PodScheduled, Status: v1.ConditionTrue},
+				},
+				ContainerStatuses: []v1.ContainerStatus{
+					ready(succeededState("containerA")),
+					ready(succeededState("containerB")),
```
Comment (ehashman) [inline pkg/kubelet/kubelet_pods_test.go:2673]: I don't actually think these should be ready but neither should any of the waiting containers in the previous existing cases, I think this test just wasn't written correctly. See also containers from pods that are failed showing restarts.

File: pkg/kubelet/kubelet_pods_test.go (hunk 2 above)
Comment (ehashman) [reply pkg/kubelet/kubelet_pods_test.go:2598]: Pushed one more unit test to cover the other case.

File: pkg/kubelet/kubelet_pods_test.go [hunk 4]
```diff
@@ -2595,6 +2595,85 @@ func Test_generateAPIPodStatus(t *testing.T) {
 				},
 			},
 		},
+		{
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet_pods_test.go:2598]: I expected both of these to test that message and reason are preserved from previous state

File: pkg/kubelet/kubelet_pods_test.go (hunk 3 above)
Comment (matthyx) [reply pkg/kubelet/kubelet_pods_test.go:2673]: Should we fix these tests first, and then apply your patch instead of having 1) ineffective coverage or 2) changing fixing kubelet and tests in the same PR?

Comment (smarterclayton) [reply pkg/kubelet/kubelet_pods_test.go:2673]: Yeah, the "isTerminated" change might be what I expect to squash that (a terminated container status should never be reported as ready, except for init containers that reached completion).  Can track it in the restart one.

Comment (ehashman) [reply pkg/kubelet/kubelet_pods_test.go:2673]: > Should we fix these tests first, and then apply your patch instead of having 1) ineffective coverage or 2) changing fixing kubelet and tests in the same PR?

Given the urgency of this fix, and how much difficulty I had with the unit tests yesterday, I don't think we should wait. I am more confident in the e2es than the unit tests for exercising this logic.

File: pkg/kubelet/kubelet_pods_test.go (hunk 4 above)
Comment (ehashman) [reply pkg/kubelet/kubelet_pods_test.go:2598]: Done!

**Comment by ehashman** [comment]
flake https://github.com/kubernetes/kubernetes/issues/99877
/test pull-kubernetes-unit

**Comment by ehashman** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105462/pull-kubernetes-e2e-kind/1445425277617311744
> /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/node/pods.go:205
Oct  5 16:51:17.002: 1 errors:
pod pod-submit-status-2-13 on node kind-worker2 container unexpected exit code 137: start=0001-01-01 00:00:00 +0000 UTC end=0001-01-01 00:00:00 +0000 UTC reason=ContainerStatusUnknown message=The container could not be located when the pod was terminated
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113

I think this e2e needs to be updated, pods being force killed should be fine (but it wasn't written to be tolerant of those statuses getting synced out).

File: test/e2e/node/pods.go [hunk 5]
```diff
@@ -379,12 +379,14 @@ var _ = SIGDescribe("Pods Extended", func() {
 								switch {
 								case t.ExitCode == 1:
 									// expected
+								case t.ExitCode == 137 && (t.Reason == "ContainerStatusUnknown" || t.Reason == "Error"):
```
Comment (smarterclayton) [inline test/e2e/node/pods.go:382]: Did this start happening with your PR?

Comment (smarterclayton) [reply test/e2e/node/pods.go:382]: If so, was it because previously we would have left the container in waiting state during graceful shutdown?

Comment (ehashman) [reply test/e2e/node/pods.go:382]: > Did this start happening with your PR?

Yes.

> If so, was it because previously we would have left the container in waiting state during graceful shutdown?

Either waiting or running I think. Statuses weren't properly getting reported.

**Comment by smarterclayton** [comment]
Concerning failure:

pod pod-submit-status-0-13 on node kind-worker did not reach a terminal phase before being deleted but had running containers: phase=Pending, running-containers=busybox

Happening on other tests?

**Comment by ehashman** [comment]
I see some instances of failures in the periodics but they don't appear to match: https://storage.googleapis.com/k8s-triage/index.html?test=Pods%20Extended

**Comment by ehashman** [comment]
Unrelated flake:
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by ehashman** [comment]
```
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.668493     248 config.go:383] "Receiving a new pod" pod="pods-7829/pod-submit-status-0-13"
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669167     248 kubelet.go:2055] "SyncLoop ADD" source="api" pods=[pods-7829/pod-submit-status-0-13]
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669398     248 pod_workers.go:535] "Pod is being synced for the first time" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669503     248 pod_workers.go:742] "Processing pod event" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7 updateType=0
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669541     248 kubelet.go:1533] "syncPod enter" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669559     248 kubelet_pods.go:1437] "Generating pod status" pod="pods-7829/pod-submit-status-0-13"
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.669600     248 kubelet_pods.go:1449] "Got phase for pod" pod="pods-7829/pod-submit-status-0-13" oldPhase=Pending phase=Pending
Oct 05 17:41:03 kind-worker kubelet[248]: I1005 17:41:03.694537     248 kubelet.go:2071] "SyncLoop DELETE" source="api" pods=[pods-7829/pod-submit-status-0-13]
```

The node got a DELETE before it even started to spin up the pod... looks like it wasn't able to sync out the final status due to client-side throttling:

```
Oct 05 17:41:05 kind-worker kubelet[248]: I1005 17:41:05.527801     248 pod_workers.go:931] "Pod is complete and the worker can now stop" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
Oct 05 17:41:05 kind-worker kubelet[248]: I1005 17:41:05.527832     248 pod_workers.go:811] "Processing pod event done" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7 updateType=2
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.645158     248 request.go:597] Waited for 386.835047ms due to client-side throttling, not priority and fairness, request: GET:https://kind-control-plane:6443/api/v1/namespaces/pods-7829/pods/pod-submit-status-0-13
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.843151     248 request.go:597] Waited for 154.773669ms due to client-side throttling, not priority and fairness, request: PATCH:https://kind-control-plane:6443/api/v1/namespaces/pods-7829/pods/pod-submit-status-0-13/status
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.860368     248 status_manager.go:622] "Patch status for pod" pod="pods-7829/pod-submit-status-0-13" patch="{\"metadata\":{\"uid\":\"a409f0f6-ac57-4d5e-95e1-97e074ea74b7\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastProbeTime\":null,\"lastTransitionTime\":\"2021-10-05T17:41:03Z\",\"status\":\"True\",\"type\":\"Initialized\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2021-10-05T17:41:03Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2021-10-05T17:41:03Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"image\":\"k8s.gcr.io/e2e-test-images/busybox:1.29-2\",\"imageID\":\"\",\"lastState\":{},\"name\":\"busybox\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":{\"exitCode\":137,\"finishedAt\":null,\"message\":\"The container could not be located when the pod was terminated\",\"reason\":\"ContainerStatusUnknown\",\"startedAt\":null}}}],\"hostIP\":\"172.18.0.2\",\"podIP\":\"10.244.1.111\",\"podIPs\":[{\"ip\":\"10.244.1.111\"}],\"startTime\":\"2021-10-05T17:41:03Z\"}}"
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.860488     248 status_manager.go:631] "Status for pod updated successfully" pod="pods-7829/pod-submit-status-0-13" statusVersion=4 status={Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-10-05 17:41:03 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-10-05 17:41:03 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-10-05 17:41:03 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2021-10-05 17:41:03 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:172.18.0.2 PodIP:10.244.1.111 PodIPs:[{IP:10.244.1.111}] StartTime:2021-10-05 17:41:03 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:137,Signal:0,Reason:ContainerStatusUnknown,Message:The container could not be located when the pod was terminated,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2 ImageID: ContainerID: Started:0xc0014d25a8}] QOSClass:Burstable EphemeralContainerStatuses:[]}
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.860884     248 kubelet_pods.go:951] "Pod is terminated and all resources are reclaimed" pod="pods-7829/pod-submit-status-0-13"
Oct 05 17:41:09 kind-worker kubelet[248]: I1005 17:41:09.861840     248 kubelet.go:2068] "SyncLoop RECONCILE" source="api" pods=[pods-7829/pod-submit-status-0-13]
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.042381     248 request.go:597] Waited for 181.389859ms due to client-side throttling, not priority and fairness, request: DELETE:https://kind-control-plane:6443/api/v1/namespaces/pods-7829/pods/pod-submit-status-0-13
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.102100     248 kubelet.go:2071] "SyncLoop DELETE" source="api" pods=[pods-7829/pod-submit-status-0-13]
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.102555     248 pod_workers.go:557] "Pod is finished processing, no further updates" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.116535     248 status_manager.go:650] "Pod fully terminated and removed from etcd" pod="pods-7829/pod-submit-status-0-13"
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.119678     248 kubelet.go:2065] "SyncLoop REMOVE" source="api" pods=[pods-7829/pod-submit-status-0-13]
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.119730     248 kubelet.go:1910] "Pod has been deleted and must be killed" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
Oct 05 17:41:10 kind-worker kubelet[248]: I1005 17:41:10.119758     248 pod_workers.go:557] "Pod is finished processing, no further updates" pod="pods-7829/pod-submit-status-0-13" podUID=a409f0f6-ac57-4d5e-95e1-97e074ea74b7
```

This just seems like accidental bad timing to me and unrelated to the PR... thoughts?

File: test/e2e/node/pods.go [hunk 6]
```diff
@@ -425,7 +427,7 @@ var _ = SIGDescribe("Pods Extended", func() {
 							if !hasTerminalPhase {
 								var names []string
 								for _, status := range pod.Status.ContainerStatuses {
-									if status.State.Terminated != nil || status.State.Running != nil {
+									if status.State.Running != nil {
```
Comment (ehashman) [inline test/e2e/node/pods.go:430]: I think this was just wrong before, but we never hit it because we were failing to sync out terminated container statuses. Now that we're doing that correctly, a Pending pod with a terminated container (perhaps because it was deleted before it reached Running) would cause this test to fail.

Comment (ehashman) [reply test/e2e/node/pods.go:430]: Note: this line came from https://github.com/kubernetes/kubernetes/pull/88440 which explicitly says in the description "The kubelet will consider any container without the `waiting` or `terminated` state to be still running, like it does for other operations." which doesn't match the code here.

**Comment by ehashman** [comment]
Passed tests :partying_face: 

The serial tests will fail, just wanna take a quick look for signal.

**Comment by smarterclayton** [comment]
Are there any other optional jobs we should run?

**Comment by ehashman** [comment]
Don't think so.
