### PR TITLE
make sure auto-mounted subpath mount source is already mounted  …

### LINKED ISSUE #110818: Can't not umount nfs subpath and the pod stack in Terminating status
### What happened?

My deployment mount the nfs volume and use subpath to mount the different path in the container.
The mount Setting like this
```
# default the nfs volume
     volumes:
      - name: data-volume
        nfs:
          path: /export/k8s-prod6a/yingmi/demeterData
          server: 172.18.2.132
          
# and mount 2 subpaths
        volumeMounts:
        - mountPath: /app/yqb
          name: data-volume
          subPath: yqb
        - mountPath: /app/opFile
          name: data-volume
          subPath: data/opFile/uploadForDemeter
```
But when I delete the pod, the pod will stack in Terminating status.
In the kubelet log, I found the error
```
Jun 28 11:51:00 k8s-dqnew-d04 kubelet: E0628 11:51:00.387689    1192 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/nfs/93db04c8-1a67-4aa2-bd22-487c135e7a27-data-volume podName:93db04c8-1a67-4aa2-bd22-487c135e7a27 nodeName:}" failed. No retries permitted until 2022-06-28 11:51:08.387656785 +0800 CST m=+1333.758393955 (durationBeforeRetry 8s). Error: "error cleaning subPath mounts for volume \"data-volume\" (UniqueName: \"kubernetes.io/nfs/93db04c8-1a67-4aa2-bd22-487c135e7a27-data-volume\") pod \"93db04c8-1a67-4aa2-bd22-487c135e7a27\" (UID: \"93db04c8-1a67-4aa2-bd22-487c135e7a27\") : error processing /var/lib/kubelet/pods/93db04c8-1a67-4aa2-bd22-487c135e7a27/volume-subpaths/data-volume/expressdaemon: error cleaning subpath mount /var/lib/kubelet/pods/93db04c8-1a67-4aa2-bd22-487c135e7a27/volume-subpaths/data-volume/expressdaemon/2: Failed to unmount path /var/lib/kubelet/pods/93db04c8-1a67-4aa2-bd22-487c135e7a27/volume-subpaths/data-volume/expressdaemon/2"
```

according to the umount code，the unmount function  ```mounter.Unmount(mountPath)```  returns nil
```
func doCleanupMountPoint(mountPath string, mounter Interface, extensiveMountPointCheck bool, corruptedMnt bool) error {
	if !corruptedMnt {
		var notMnt bool
		var err error
		if extensiveMountPointCheck {
			notMnt, err = mounter.IsNotMountPoint(mountPath)
		} else {
			notMnt, err = mounter.IsLikelyNotMountPoint(mountPath)
		}

		if err != nil {
			return err
		}

		if notMnt {
			klog.Warningf("Warning: %q is not a mountpoint, deleting", mountPath)
			return os.Remove(mountPath)
		}
	}

	// Unmount the mount path
	klog.V(4).Infof("%q is a mountpoint, unmounting", mountPath)
	if err := mounter.Unmount(mountPath); err != nil {
		return err
	}

	notMnt, mntErr := mounter.IsLikelyNotMountPoint(mountPath)
	if mntErr != nil {
		return mntErr
	}
	if notMnt {
		klog.V(4).Infof("%q is unmounted, deleting the directory", mountPath)
		return os.Remove(mountPath)
	}
	return fmt.Errorf("Failed to unmount path %v", mountPath)
}
```

### What did you expect to happen?

the subpath umount successfully and the pod can be deleted

### How can we reproduce it (as minimally and precisely as possible)?

just like the description in ```what happened```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11", GitCommit:"d966b365d87fb2783deab0d244047d340f1be146", GitTreeState:"clean", BuildDate:"2022-01-19T01:10:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


$ uname -a
Linux k8s-dqnew-d04 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
nfs server system version: 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

nfs version
dpkg -l |grep nfs
ii  libnfsidmap2:amd64                    0.25-5.1                                        amd64        NFS idmapping library
ii  nfs-common                            1:1.3.4-2.1ubuntu5.2                            amd64        NFS support files common to client and server
ii  nfs-kernel-server                     1:1.3.4-2.1ubuntu5.2                            amd64        support for NFS kernel server
</details>

### PR DESCRIPTION
**Pull request by Dieken**
For example, we have two filesystems, one is embedded into another:

```
/a/test		# first filesystem with a directory "/a/test/b2"
/a/test/b2	# second filesystem, notice now "/a/test/b2" is a new directory on this filesystem
```

For subpath mount "/a/test/b2",  `openat("/a/test", "b2")` gets directory "b2" on the first
filesystem, then "mount -c" will use this wrong directory as source directory.

`openat("/a/test", "b2/")` forces traversing into the second filesystem to get the correct source
directory for "mount -c".

This fixes issue https://github.com/kubernetes/kubernetes/issues/110818#issuecomment-1175736550

<hr/>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When a subpath points to an embedded child filesystem, kubelet wrongly mounts directory from the parent filesystem, then when a file access happens on the subpath mountpoint, the correct child filesystem is mounted automatically by linux kernel, this leads to two mounts on the same subpath,  kubelet will fail to destroy the pod because it wrongly thinks unmounting the subpath mount point failed.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/110818#issuecomment-1175736550

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Dieken** [comment]
/retest

Seems the snapshot errors are due to CI environment.

File: pkg/volume/util/subpath/subpath_linux.go [hunk 1]
```diff
@@ -587,6 +587,17 @@ func doSafeOpen(pathname string, base string) (int, error) {
 			return -1, fmt.Errorf("unexpected symlink found %s", currentPath)
 		}
 
+		// make sure to open directory on child filesystem such as bind mounted directory
+		if fileFmt == syscall.S_IFDIR {
+			if err = syscall.Close(childFD); err != nil {
```
Comment (jingxu97) [inline pkg/volume/util/subpath/subpath_linux.go:592]: what is the purpose of this call?

File: pkg/volume/util/subpath/subpath_linux.go [hunk 2]
```diff
@@ -587,6 +587,17 @@ func doSafeOpen(pathname string, base string) (int, error) {
...
+				return -1, fmt.Errorf("closing dir fd for %q failed: %v", currentPath, err)
+			}
+
+			if childFD, err = syscall.Openat(parentFD, seg+"/", openFDFlags|unix.O_CLOEXEC, 0); err != nil {
```
Comment (jingxu97) [inline pkg/volume/util/subpath/subpath_linux.go:596]: I don't know the details, but just comparing with the previous function, the only difference is seg vs seg+"/"? 
Is it ok we always use seg+"/"? 

```
childFD, err = syscall.Openat(parentFD, seg, openFDFlags|unix.O_CLOEXEC, 0)
```

File: pkg/volume/util/subpath/subpath_linux.go (hunk 1 above)
Comment (Dieken) [reply pkg/volume/util/subpath/subpath_linux.go:592]: Because this child directory will be opened again below, so childFD is closed here to avoid file descriptor leak.

File: pkg/volume/util/subpath/subpath_linux.go (hunk 2 above)
Comment (Dieken) [reply pkg/volume/util/subpath/subpath_linux.go:596]: As the commit log and the corresponding issue comment said,  if "child-dir" is a mount point for another file system, `openat("parent-dir", "child-dir")` actually open directory on file system "parent-dir", not the expected directory on file system "parent-dir/child-dir".

I got three versions of this patch:

(1) always open `seg+"/"`.

This is wrong, it breaks plain file bind mount.

(2) first try `seg+"/"`, if gets ENOTDIR error, try `seg` again.

This leads to security vulnerability and breaks Kubernetes CI tests, when `seg` is a symlink, `seg+"/"` will follow it, this behaviour conflicts with `O_NOFOLLOW` in `openFDFlags`.

(3) the current version,  first try `seg`, if it's a directory, try `seg+"/"` again to force traversing into a possible mount point.

**Comment by Dieken** [comment]
@jingxu97  please review again, I pushed the fourth version,  use `fstatat("parent-dir", "child-dir/")` to force auto mount of "child-dir", this version resolves the race condition in the third version,  even the attack unmounts "child-dir/" before `openat("parent-dir", "child-dir")`, he can't fool kubelet to use a symlink "child-dir".

**Comment by Dieken** [comment]
The snapshot test error seems not related to this PR.

The bug can be easily reproduced with steps at https://github.com/kubernetes/kubernetes/issues/110818#issuecomment-1175736550, the patch itself is obvious.

Could you review/merge this little patch and backport it to v1.20? Currently this issue affects k8s >= v1.19.15, v1.20.11, v1.21.10, v1.22.1, v1.23.0 by searching `git grep no-canonicalize $TAG:pkg/volume/util/subpath/subpath_linux.go`

@249043822 @jingxu97 @msau42 @jsafrane @saad-ali

**Comment by 249043822** [comment]
Since the pr: https://github.com/kubernetes/kubernetes/pull/110980 has merged, now the pull-kubernetes-e2e-gce-storage-snapshot job should normal
/test pull-kubernetes-e2e-gce-storage-snapshot

File: pkg/volume/util/subpath/subpath_linux.go [hunk 3]
```diff
@@ -566,18 +566,22 @@ func doSafeOpen(pathname string, base string) (int, error) {
...
 	// sure the user cannot change already existing directories into symlinks.
 	for _, seg := range segments {
+		var deviceStat unix.Stat_t
+
 		currentPath = filepath.Join(currentPath, seg)
 		if !mount.PathWithinBase(currentPath, base) {
 			return -1, fmt.Errorf("path %s is outside of allowed base %s", currentPath, base)
 		}
 
+		// trigger auto mount, ignore error if not a directory
```
Comment (jsafrane) [inline pkg/volume/util/subpath/subpath_linux.go:576]: Please add a comment that `unix.Fstat("path/a")` below is not enough and extra `path/a/` here is needed to trigger automount in case `a` is an automounted dir.

Comment (Dieken) [reply pkg/volume/util/subpath/subpath_linux.go]: Updated the comment and rebased on latest master branch, please check again, thanks!

**Comment by Dieken** [comment]
got timeout :-(

/retest

**Review by zl86790 — APPROVED** [review]

**Comment by rajnikhil17** [comment]
How this fix will be released?

Will it be a patch or are you going to port it on 1.25?

**Comment by jsafrane** [comment]
It will be part of 1.25

**Comment by Dieken** [comment]
> How this fix will be released?
> 
> Will it be a patch or are you going to port it on 1.25?

Currently this issue affects k8s >= v1.19.15, v1.20.11, v1.21.10, v1.22.1, v1.23.0 by searching `git grep no-canonicalize $TAG:pkg/volume/util/subpath/subpath_linux.go`,  it would be appreciated if backport to these releases.

@jsafrane  @rajnikhil17

**Comment by rajnikhil17** [comment]
@Dieken We are in the 1.23.6 release
Will we get this Patch to 1.23.6?

@jsafrane Confirmed that it would be ported under the 1.25 release

**Comment by andyzhangx** [comment]
we also have a user hitting this issue, I am now cherry-picking this PR to v1.22, 1.23, 1.24

**Comment by rajnikhil17** [comment]
@andyzhangx  What would be the version in 1.23 this PR will be cherry-picked.

**Comment by andyzhangx** [comment]
> I am now cherry-picking this PR to v1.22, 1.23, 1.24

@rajnikhil17 it should be `1.23.12` if the cherry-pick PR could be merged in the next few days.

**Comment by rajnikhil17** [comment]
@andyzhangx  Is this fix cherry picked?
