### PR TITLE
Fix replicaCount calculation exceeding max int32

### LINKED ISSUE #126892: Int overflow in hpa causing incorrect replica count
### What happened?

The setup:
I am using keda with the prometheus scaler. The query I am using, returns the lag in the message queue i am using, and the threshold is set to `0.1`.

What happened:
The lag was increasing for a long time, and the replica count reached the max setting as expected. Everything was running fine for some time. When the lag value reached `214,748,364` hpa decided to reduce the replicas from the max limit to `1`.

What I think is the problem:
When the lag passes `214,748,364`, the calculation [here](https://github.com/kubernetes/kubernetes/blob/7b80cdb66a390f225d23cd612950144e3a39d1ae/pkg/controller/podautoscaler/replica_calculator.go#L278) divides by the threshold `0.1` and it passes the max int32 value. causing hpa to scale to the minimum value, 1.
It also seems like a lot of other places in this file cast a 64 bit float to a 32 bit int. Should there maybe be a check everywhere this is done?

### What did you expect to happen?

I expected the replica count to stay at the max value. Or alternatively, get an error that we have reached the max value for an external metric value

### How can we reproduce it (as minimally and precisely as possible)?

Use an external metric, and set it above `214,748,364` with a threshold of `0.1`.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.29
</details>

### Cloud provider

<details>
aws eks
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by omerap12**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes integer overflow in ReplicaCalculator when computed replica count exceeds int32.MaxValue. Caps the count at max int32 instead of wrapping to small values, preventing incorrect scaling decisions in extreme cases.

#### Which issue(s) this PR fixes:

Fixes #126892

#### Does this PR introduce a user-facing change?

```release-note
No
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
No
```

### CODE REVIEW

File: pkg/controller/podautoscaler/replica_calculator.go [hunk 1]
```diff
@@ -275,7 +275,14 @@ func (c *ReplicaCalculator) getUsageRatioReplicaCount(currentReplicas int32, usa
 		if err != nil {
 			return 0, time.Time{}, fmt.Errorf("unable to calculate ready pods: %s", err)
 		}
-		replicaCount = int32(math.Ceil(usageRatio * float64(readyPodCount)))
+		// Calculate replicaCount as float64 first
```
Comment (kannon92) [inline pkg/controller/podautoscaler/replica_calculator.go:278]: I think having a unit test here would be useful.

Comment (omerap12) [reply pkg/controller/podautoscaler/replica_calculator.go:278]: Sure, I'll add a test :)

**Comment by sheepster1** [comment]
@omerap12 Thanks for the quick  help. I can see we do this `int32()` of a `float64` in 6 places in this file. I am not completely sure which one I ran into, I think it actually might be [this](https://github.com/kubernetes/kubernetes/blob/de6db3ffb0680f2022f8795038eb2ca5b36c5bd6/pkg/controller/podautoscaler/replica_calculator.go#L372) one, and not the original link I sent, but I am not sure.

Do we maybe want to add this check to all the places?

**Comment by omerap12** [comment]
Hey @sheepster1, I'm happy to help. We should add this check to all relevant places. Once this PR is approved and merged, I'll review the entire file and implement those checks. Could you please create a tracking issue and assign it to me?

**Comment by gjtempleton** [comment]
@omerap12 is this PR still applicable?

**Comment by omerap12** [comment]
> @omerap12 is this PR still applicable?

I think so, but I'm not entirely sure. There's a discussion in #127050.
I'll open this anyway. CC @adrianmoisey

/open

**Review by soltysh — APPROVED** [review]
/approve

**Comment by soltysh** [comment]
@omerap12 have you checked if there are other places where a similar check would be reasonable?
