### PR TITLE
Resources prefixed with *kubernetes.io/ should remain unscheduled if they are not exposed on the node.

### LINKED ISSUE #50658: Scheduler ignores requests for unknown fully-qualified resources.
/kind bug
/sig scheduling

**What happened**:

_Scenario A:_
* Create a pod that requires one `example.com/foo` resource.
* Observe that the pod is scheduled, despite there being no matching resources available in the cluster.

_Scenario B:_
* Create a pod that requires one `kubernetes.io/foo` resource.
* Observe that the pod is scheduled, despite there being no matching resources available in the cluster.

**What you expected to happen**:

I did not expect the pod to be scheduled and run. In both cases, I expected the pod to do one of the following:
* Remain in pending state, having failed a scheduler predicate for all available nodes.
* Fail validation. Since there is no facility in the scheduler or kubelet for checking feasibility of these resources, you could argue that they should have failed admission.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

There is a pull request in progress that attempts to fix this problem for all resources outside of the default namespace: [PR 48922: ](https://github.com/kubernetes/kubernetes/pull/48922). Another patch will be needed to handle fully-qualified resources in the `kubernetes.io` domain.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7, recent master
- Cloud provider or hardware configuration**: Local cluster
- OS (e.g. from /etc/os-release): Linux Mint 18.1, CentOS 7
- Kernel (e.g. `uname -a`): 4.4, 3.10
- Install tools: ./hack/local-up-cluster.sh

### PR DESCRIPTION
**Pull request by rohitagarwal003**
Currently, resources prefixed with `*kubernetes.io/` get scheduled to any
node whether it's exposing that resource or not.

On the other hand, resources prefixed with `someother.domain/` don't get
scheduled to a node until that node is exposing that resource (or if the
resource is ignored because of scheduler extender).

This commit brings the behavior of `*kubernetes.io/` prefixed resources in
line with other extended resources and they will remain unscheduled
until some node exposes these resources.

Fixes #50658

```release-note
Pods requesting resources prefixed with `*kubernetes.io` will remain unscheduled if there are no nodes exposing that resource.
```

/sig scheduling
/assign jiayingz vishh bsalamat ConnorDoyle k82cn

### CODE REVIEW

File: pkg/apis/core/v1/helper/helpers.go [hunk 1]
```diff
@@ -47,13 +47,18 @@ func IsExtendedResourceName(name v1.ResourceName) bool {
 	return true
 }
 
+// IsDefaultnamespaceContainingResource returns true if the resource name is in the
+// *kubernetes.io/ namespace.
+func IsDefaultNamespaceContainingResource(name v1.ResourceName) bool {
```
Comment (bsalamat) [inline pkg/apis/core/v1/helper/helpers.go]: The name of this function is confusing and the fact that we have used "Namespace" which is a well known concept in Kubernetes causes even more confusion. I would call it something like "IsNativeResource".

**Review by bsalamat — COMMENTED** [review]
minor comment, otherwise LGTM.

File: pkg/apis/core/v1/helper/helpers.go (hunk 1 above)
Comment (mindprince) [reply pkg/apis/core/v1/helper/helpers.go]: I based it on the function below: `IsDefaultNamespaceResource90`. Also, the prefix variable is called `ResourceDefaultNamespacePrefix`.

How would you name these two functions? `IsNativeResource()` seems to make more sense for the function below.

Since the newly added function is very straightforward and seem to not have uses outside of this feel, I don't mind inlining it either.

Comment (bsalamat) [reply pkg/apis/core/v1/helper/helpers.go]: I know that this whole "Namespace" thing in the function names existed.
You are right that we should probably use "IsNativeResource" for the function below. This one can be called "IsNativeResourceWithPrefix" or "IsPrefixedNativeResource" or something along these.

Comment (mindprince) [reply pkg/apis/core/v1/helper/helpers.go]: Updated. PTAL

**Comment by thockin** [comment]
Do we have docs on when a resource would be "bare" vs prefixed with kubernetes ?

/approve

**Comment by mindprince** [comment]
> Do we have docs on when a resource would be "bare" vs prefixed with kubernetes ?

The in-tree resources (cpu, memory, ephemeral-storage, hugepages-*) are always supposed to be bare. The docs just use bare resources always when talking about these and don't mention anything about prefixing with kubernetes.io.

When talking about extended resources the docs say:

https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
> Extended Resources are fully-qualified resource names outside the kubernetes.io domain.

https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/
> Extended resources are fully qualified with any domain outside of *.kubernetes.io/.
