### PR TITLE
fix ci-kubernetes-node-kubelet-serial Non-system critical priority classes are not allowed to have a value larger than HighestUserDefinablePriority

### LINKED ISSUE #81824: [Failing Tests] ci-kubernetes-node-kubelet-serial which set PodPriority are failing when adminssion Priority enable
Setting PodPriority directly when adminssion Priority enable,the Pod is rejected.
To fix this, we need to create new priority classes for these tests.

**Which jobs are failing**:

https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/

**Which test(s) are failing**:
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/critical_pod_test.go:46
I0822 19:01:41.165]     should be able to create and delete a critical pod [It]

**Since when has it been failing**:

**Testgrid link**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1164593577464958978

**Reason for failure**:
because adminssion Priority enable，If the priority class is not found, the Pod is rejected.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Non-system critical priority classes are not allowed to have a value larger than HighestUserDefinablePriority

**Which issue(s) this PR fixes**:

Fixes #81824

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
  NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/assign @odinuge

### CODE REVIEW

**Review by odinuge — COMMENTED** [review]
Hi,

Thanks for the fix, and for reacting this quick!

Did some research on this a few days ago, and I don't remember if this fixed the problem. Can you try, if you haven't already, to run the test locally via gcp. 

I think this command should run the given tests.
 
```
GOOGLE_APPLICATION_CREDENTIALS=your-creds.json make test-e2e-node PARALLELISM=1 REMOTE=true FOCUS="CriticalPod" SKIP=""
```

We cannot run the tests here (from what I know) unless we merge it, so you have to check yourself.

**Comment by odinuge** [comment]
This test is also a part of the tests covered in issue #82017

/cc @alejandrox1

**Comment by neolit123** [comment]
SGTM, but this should get a review by sig-node.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks!

**Review by odinuge — CHANGES_REQUESTED** [review]
Hi @zouyee,

Ran the test locally, and it still fails.

Got this result:

```
• Failure [6.112 seconds]
[k8s.io] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod]
/home/odin/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:693
  when we need to admit a critical pod
  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/critical_pod_test.go:48
    should be able to create and delete a critical pod [It]
    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/critical_pod_test.go:55

    failed to create PriorityClasses with an error: PriorityClass.scheduling.k8s.io "critical-pod-test-high-priority" is invalid: value: Forbidden: maximum allowed value of a user defined priority is 1000000000
    Expected
        <bool>: false
    to be true

    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/critical_pod_test.go:89
```

Since the test is still failing in master, ill add priotiry/important-longterm. Feel free to change it if someone disagrees. :smile: 

/priority important-longterm
/hold

**Comment by odinuge** [comment]
Adding hold in await for the test to pass.

/hold

**Comment by zouyee** [comment]
local test passed, ping @odinuge
/remove hold
/priority important-soon

**Comment by odinuge** [comment]
Ping @zouyee,

Have you had a chance to look at this?

**Comment by zouyee** [comment]
I'll take care of it in these two days, thank you @odinuge .

File: test/e2e_node/critical_pod_test.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 				framework.Skipf("unable to run test without dynamic kubelet config enabled.")
 			}
 			// because adminssion Priority enable, If the priority class is not found, the Pod is rejected.
-			systemCriticalPriority := &schedulingv1.PriorityClass{ObjectMeta: metav1.ObjectMeta{Name: systemCriticalPriorityName}, Value: scheduling.SystemCriticalPriority}
+			systemCriticalPriority := &schedulingv1.PriorityClass{ObjectMeta: metav1.ObjectMeta{Name: systemCriticalPriorityName}, Value: scheduling.HighestUserDefinablePriority}
```
Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]: From my understanding of critical pods, the priority has to be higher than `scheduling.HighestUserDefinablePriority`.

There should be two priority classes created at cluster bootstrap called `system-node-critical` and `system-cluster-critical` (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/scheduling/helpers.go#L27). I think we should use one of those in this test.

File: test/e2e_node/critical_pod_test.go [hunk 2]
```diff
@@ -78,11 +78,18 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
...
+			used := v1.ResourceList{
+				v1.ResourceCPU:    resource.MustParse("200m"),
+				v1.ResourceMemory: resource.MustParse("200Mi"),
+			}
+			available := getAvailableCPUAndMemoryCapacity(capacity, used)
 			criticalPod := getTestPod(true, criticalPodName, v1.ResourceRequirements{
 				// request the entire resource capacity of the node, so that
 				// admitting this pod requires the other pod to be preempted
-				Requests: getNodeCPUAndMemoryCapacity(f),
+				Requests: available,
```
Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]: I think the usage of `getNodeCPUAndMemoryCapacity` is intentional. If a non-critical pod requests all the resources it will stay in pending, but a system critical pod should evict all other pods and get scheduled.

File: test/e2e_node/critical_pod_test.go [hunk 3]
```diff
@@ -36,7 +36,7 @@ import (
 )
 
 const (
-	criticalPodName            = "critical-pod"
+	criticalPodName            = "static-critical-pod"
```
Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]: What is the reason for calling it static?

**Review by odinuge — COMMENTED** [review]
Just a few comments about the change.

Would be awesome with some feedback from @draveness, I think he knows a lot about the topic. :smile: 

/cc draveness

**Comment by alejandrox1** [comment]
@zouyee any updates on this?

File: test/e2e_node/critical_pod_test.go (hunk 3 above)
Comment (zouyee) [reply test/e2e_node/critical_pod_test.go]: criticalPodName call static-critical-pod because using annotation `"kubernetes.io/config.source"`to mark it.

File: test/e2e_node/critical_pod_test.go (hunk 2 above)
Comment (zouyee) [reply test/e2e_node/critical_pod_test.go]: when `getNodeCPUAndMemoryCapacity `, critical pod will not be admited because of OutOfCPU or OutOfMem

File: test/e2e_node/critical_pod_test.go (hunk 1 above)
Comment (liggitt) [reply test/e2e_node/critical_pod_test.go]: agree, I expected one of those two to be used, along with their priority value

File: test/e2e_node/critical_pod_test.go (hunk 2 above)
Comment (zouyee) [reply test/e2e_node/critical_pod_test.go]: Because e2e_node.test only start kubelet and apiserver without scheduler which must Preemption .

**Comment by zouyee** [comment]
@yujuhong @liggitt  PTAL

**Comment by zouyee** [comment]
@odinuge PTAL

**Comment by dims** [comment]
hmm, issue https://github.com/kubernetes/kubernetes/issues/81824 is marked v1.17

/milestone v1.17

File: test/e2e_node/critical_pod_test.go [hunk 4]
```diff
@@ -78,15 +76,24 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
...
-				Requests: getNodeCPUAndMemoryCapacity(f),
+				Requests: available,
 			})
-
-			_, err = f.ClientSet.SchedulingV1().PriorityClasses().Create(systemCriticalPriority)
-			gomega.Expect(err == nil || errors.IsAlreadyExists(err)).To(gomega.BeTrue(), "failed to create PriorityClasses with an error: %v", err)
+			// SystemPriorityClasses define system priority classes that are auto-created at cluster bootstrapping.
+			// SystemNodeCritical used for system critical pods that must not be moved from their current node.
+			// Because e2e_node.test does not start the scheduler, SystemNodeCritical needed to be created manually.
+			_, err = f.ClientSet.SchedulingV1().PriorityClasses().Create(schedulingv1.SystemPriorityClasses()[0])
```
Comment (liggitt) [inline test/e2e_node/critical_pod_test.go]: should this loop over all items in `f.ClientSet.SchedulingV1().PriorityClasses()` and create, tolerating `AlreadyExists` errors?

File: test/e2e_node/critical_pod_test.go [hunk 5]
```diff
@@ -78,15 +76,24 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 					v1.ResourceMemory: resource.MustParse("100Mi"),
 				},
 			})
+
 			nonCriticalBestEffort := getTestPod(false, bestEffortPodName, v1.ResourceRequirements{})
+			capacity := getNodeCPUAndMemoryCapacity(f)
+			used := v1.ResourceList{
+				v1.ResourceCPU:    resource.MustParse("200m"),
+				v1.ResourceMemory: resource.MustParse("200Mi"),
```
Comment (liggitt) [inline test/e2e_node/critical_pod_test.go]: where did these numbers come from?

File: test/e2e_node/critical_pod_test.go (hunk 4 above)
Comment (odinuge) [reply test/e2e_node/critical_pod_test.go]: Agree!

The scheduler create them here: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/scheduling/rest/storage_scheduling.go#L125-L141, so I agree that test should do the same.

File: test/e2e_node/critical_pod_test.go [hunk 6]
```diff
@@ -78,15 +76,24 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
...
+			}
+			available := getAvailableCPUAndMemoryCapacity(capacity, used)
 			criticalPod := getTestPod(true, criticalPodName, v1.ResourceRequirements{
 				// request the entire resource capacity of the node, so that
 				// admitting this pod requires the other pod to be preempted
-				Requests: getNodeCPUAndMemoryCapacity(f),
+				Requests: available,
```
[the remark this answers is not in the document]
Comment (odinuge) [reply test/e2e_node/critical_pod_test.go]: The test should verify that a critical pod will be admitted and preempt other pods in case of lacking resources, so we have to do this in order to make the test make sense.

File: test/e2e_node/critical_pod_test.go (hunk 5 above)
Comment (odinuge) [reply test/e2e_node/critical_pod_test.go]: Looks like they are random. They should however not be used, since the critical pod _should_ request all the available resources on the node in order to force preemption of other pods.

**Review by odinuge — CHANGES_REQUESTED** [review]
Hi @zouyee,
Been busy with exams for a while now, so sorry for the late reply.

A few comments on the changes.

Looks like there have been a typo about what should be evicted in this test from day 1, so those comments should be fixed too (see my review comments). I have verified that the changes make the tests pass, and that everything works as expected.

We should really try to get this merged as soon as possible to stabilize the node-e2e-serial tests!

File: test/e2e_node/critical_pod_test.go (hunk 5 above)
Comment (liggitt) [reply test/e2e_node/critical_pod_test.go]: This smells like particular values were chosen to work with a particular test environment, and would be inaccurate or lead to test failures in differently sized CI environments. Is that the case?

File: test/e2e_node/critical_pod_test.go (hunk 2 above)
Comment (dashpole) [reply test/e2e_node/critical_pod_test.go]: That is false.  This is not a test for scheduler preemption, but rather a test for kubelet preemption, which will admit a critical pod even if resources do not exist on the node for it.

This should be changed back to getNodeCPUAndMemoryCapacity().  It would defeat the purpose of the test to subtract an amount from it.

File: test/e2e_node/critical_pod_test.go (hunk 5 above)
Comment (dashpole) [reply test/e2e_node/critical_pod_test.go]: It shouldn't request all _available_ resources.  It should request _all_ (allocatable) resources on the node.  We shouldn't subtract anything.

File: test/e2e_node/critical_pod_test.go [hunk 7]
```diff
@@ -99,26 +106,41 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 				if p.Name == nonCriticalBestEffort.Name {
 					framework.ExpectNotEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should be preempted", p.Name))
 				} else {
-					framework.ExpectEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should not be preempted", p.Name))
+					framework.ExpectEqual(p.Status.Phase, v1.PodRunning, fmt.Sprintf("pod: %v should not be preempted with status: %#v", p.Name, p.Status))
```
[the remark this answers is not in the document]
Comment (dashpole) [reply test/e2e_node/critical_pod_test.go]: +1

File: test/e2e_node/critical_pod_test.go [hunk 8]
```diff
@@ -99,26 +106,41 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 				if p.Name == nonCriticalBestEffort.Name {
 					framework.ExpectNotEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should be preempted", p.Name))
```
[the remark this answers is not in the document]
Comment (odinuge) [reply test/e2e_node/critical_pod_test.go]: @zouyee is there a reason you did not fix this?

File: test/e2e_node/critical_pod_test.go [hunk 9]
```diff
@@ -99,7 +100,7 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
...
 				} else {
-					framework.ExpectEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should not be preempted", p.Name))
+					framework.ExpectEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should not be preempted with status: %#v", p.Name, p.Status))
```
Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]:
```suggestion
					framework.ExpectEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should be preempted with status: %#v", p.Name, p.Status))
```

File: test/e2e_node/critical_pod_test.go [hunk 10]
```diff
@@ -97,9 +99,9 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 			framework.ExpectNoError(err)
 			for _, p := range updatedPodList.Items {
 				if p.Name == nonCriticalBestEffort.Name {
-					framework.ExpectNotEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should be preempted", p.Name))
+					framework.ExpectNotEqual(p.Status.Phase, v1.PodFailed, fmt.Sprintf("pod: %v should be preempted with status: %#v", p.Name, p.Status))
```
Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]: I still prefer being explicit about the fact that the pod _should be running_.

```suggestion
					framework.ExpectEqual(p.Status.Phase, v1.PodRunning, fmt.Sprintf("pod: %v should not be preempted with status: %#v", p.Name, p.Status))
```

Also, the error message here should be _"should **not** be preempted"_

Comment (odinuge) [inline test/e2e_node/critical_pod_test.go]: I still prefer being explicit about the fact that the pod _should be running_.

```suggestion
					framework.ExpectEqual(p.Status.Phase, v1.PodRunning, fmt.Sprintf("pod: %v should not be preempted with status: %#v", p.Name, p.Status))
```

Also, the error message here should be _"should **not** be preempted"_

**Review by odinuge — CHANGES_REQUESTED** [review]

**Review by odinuge — APPROVED** [review]
/lgtm

Looks good. Tests are now passing, so this should be merged as soon as possible. :)

File: test/e2e_node/critical_pod_test.go [hunk 11]
```diff
@@ -59,8 +58,14 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 				framework.Skipf("unable to run test without dynamic kubelet config enabled.")
 			}
 			// because adminssion Priority enable, If the priority class is not found, the Pod is rejected.
-			systemCriticalPriority := &schedulingv1.PriorityClass{ObjectMeta: metav1.ObjectMeta{Name: systemCriticalPriorityName}, Value: scheduling.SystemCriticalPriority}
-
+			// SystemPriorityClasses define system priority classes that are auto-created at cluster bootstrapping.
+			// SystemNodeCritical used for system critical pods that must not be moved from their current node.
+			// Because e2e_node.test does not start the scheduler, SystemNodeCritical needed to be created manually.
```
Comment (liggitt) [inline test/e2e_node/critical_pod_test.go]: these are created by the API server, not by the scheduler... are you sure we need to manually create these?

Comment (odinuge) [reply test/e2e_node/critical_pod_test.go]: Looks like you are correct @liggitt. Tests pass when this section (creating the PriorityClasses) is omitted, so I guess it should just be removed entirely.

**Comment by odinuge** [comment]
Looks like this needs a rebase @zouyee.

Also a ping to approvers, since this PR will fix a failing test

File: test/e2e_node/critical_pod_test.go [hunk 12]
```diff
@@ -58,8 +56,11 @@ var _ = framework.KubeDescribe("CriticalPod [Serial] [Disruptive] [NodeFeature:C
 				framework.Skipf("unable to run test without dynamic kubelet config enabled.")
 			}
 			// because adminssion Priority enable, If the priority class is not found, the Pod is rejected.
-			systemCriticalPriority := &schedulingv1.PriorityClass{ObjectMeta: metav1.ObjectMeta{Name: systemCriticalPriorityName}, Value: scheduling.SystemCriticalPriority}
-
+			for _, pc := range schedulingapiv1.SystemPriorityClasses() {
+				_, err = f.ClientSet.SchedulingV1().PriorityClasses().Get(pc.GetName(), metav1.GetOptions{})
+				framework.ExpectNoError(err, "failed to get PriorityClasses %s with an error: %v", pc.GetName(), err)
+			}
```
Comment (liggitt) [inline test/e2e_node/critical_pod_test.go]: I would drop this loop/check. The only one we actually care about is SystemNodeCritical, and we will get a specific error if that is not present when we try to create the pod.

**Comment by liggitt** [comment]
just one comment at https://github.com/kubernetes/kubernetes/pull/82493#pullrequestreview-341856893, then lgtm

**Review by alejandrox1 — COMMENTED** [review]
good pending Jordan's comment
/milestone v1.18

**Comment by alejandrox1** [comment]
The failure looks very much like https://github.com/kubernetes/kubernetes/issues/87131
For the sake of replication
/test pull-kubernetes-integration

Prev failure: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82493/pull-kubernetes-integration/1216970695376900099

**Comment by odinuge** [comment]
/lgtm

Should be good to go now @liggitt
