### PR TITLE
Fix unschedulable pods metric broke while preenqueue

### LINKED ISSUE #132333: scheduler_unschedulable_pods metric might broke when running PreEnqueue plugins
### What happened?

`scheduler_unschedulable_pods` metric stores the number of unschedulable pods broken down by plugin name. It is incremented when the pod is re-added to the scheduling queue (with its all unschedulable and pending plugins) as well as when `PreEnqueue` plugin fails for such pod. When the pod is popped out from the scheduling queue, the metric is decremented using pod's unschedulable and pending pods lists. However, if `PreEnqueue` fails for a plugin that was already reported as unschedulable for a pod, the metric is still incremented (multiple ones for one plugin and one pod) what leads to not clearing the metric properly when popping out the pod.

### What did you expect to happen?

`scheduler_unschedulable_pods` metric to be incremented properly when `PreEnqueue` fails.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod that will get rejected by a plugin while scheduling (e.g. on `Filter`) and then blocked by `PreEnqueue` by the same plugin. If the pod is finally scheduled, the `scheduler_unschedulable_pods` will be non-zero.

### Anything else we need to know?

/sig scheduling

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by vshkrabkov**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes a bug in the scheduler_unschedulable_pods metric where the count could become desynchronized (leaked) when a Pod is rejected by a PreEnqueue plugin.

The Problem: Previously, the metric was unconditionally incremented when a Pod failed a PreEnqueue check. If a Pod was already in the scheduling queue (marked unschedulable by a specific plugin) and was then rejected again by the same plugin during PreEnqueue (e.g., during a retry cycle), the metric would be incremented a second time for the same Pod and Plugin.

However, when the Pod is eventually popped from the queue, the decrement logic only accounts for the Pod once. This resulted in the scheduler_unschedulable_pods value remaining permanently non-zero even after the Pod was scheduled or deleted.

The Fix: This PR ensures that the metric is not incremented if the Pod is already recorded as unschedulable for the specific plugin. It also adds drop metric while pod deletion.

#### Which issue(s) this PR is related to:
Fixes #132333

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where the `scheduler_unschedulable_pods` metric could be artificially inflated (leak) when a pod fails `PreEnqueue` plugins after being previously marked unschedulable.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 1]
```diff
@@ -3362,8 +3365,8 @@ func TestPodTimestamp(t *testing.T) {
 	}
 }
 
-// TestPendingPodsMetric tests Prometheus metrics related with pending pods
-func TestPendingPodsMetric(t *testing.T) {
+// TestSchedulerPodsMetric tests Prometheus metrics
+func TestSchedulerPodsMetric(t *testing.T) {
```
Comment (vshkrabkov) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go:3376]: Renamed as this function contains test scenarios not only for the pending_pods metrics

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 2]
```diff
@@ -3773,6 +3776,77 @@ scheduler_pending_pods{queue="active"} 1
...
+			},
+			metricsName: "scheduler_unschedulable_pods",
+			wants: `
+# HELP scheduler_unschedulable_pods [ALPHA] The number of unschedulable pods broken down by plugin name. A pod will increment the gauge for all plugins that caused it to not schedule and so this metric have meaning only when broken down by plugin.
+# TYPE scheduler_unschedulable_pods gauge
+scheduler_unschedulable_pods{plugin="preEnqueuePlugin",profile=""} 0
+`,
+		},
+		{
+			name: "Unschedulable pods metric must be 0 after pod is gated multiple time by simillar plugin",
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: What about a scenario when a pod is added to the queue with UnschedulablePlugin and then gated with the same?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 3]
```diff
@@ -3773,6 +3776,77 @@ scheduler_pending_pods{queue="active"} 1
...
+			},
+			wants: `
+# HELP scheduler_unschedulable_pods [ALPHA] The number of unschedulable pods broken down by plugin name. A pod will increment the gauge for all plugins that caused it to not schedule and so this metric have meaning only when broken down by plugin.
+# TYPE scheduler_unschedulable_pods gauge
+scheduler_unschedulable_pods{plugin="preEnqueuePlugin",profile=""} 0
+`,
+			metricsName: "scheduler_unschedulable_pods",
+		},
+		{
+			name: "Unschedulable pods metric must be 0 after pod is gated and then deleted",
```
Comment (macsko) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Add a test case for non-gated and deleted

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 2 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 3 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 4]
```diff
@@ -3182,6 +3182,9 @@ var (
 	add = func(t *testing.T, logger klog.Logger, queue *PriorityQueue, pInfo *framework.QueuedPodInfo) {
 		queue.Add(logger, pInfo.Pod)
 	}
+	pop = func(_ *testing.T, logger klog.Logger, queue *PriorityQueue, _ *framework.QueuedPodInfo) {
+		queue.Pop(logger)
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Please fix linter error:
`Error return value of `queue.Pop` is not checked (errcheck)`

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 5]
```diff
@@ -4647,3 +4650,154 @@ func TestPriorityQueue_GetPod(t *testing.T) {
...
+		operations     []operation
+		operands       [][]*framework.QueuedPodInfo
+		expectedMetric int
+	}{
+		{
+			name: "Unschedulable pods metric must be 0 after a pod is gated, ungated, re-queued, and eventually popped from the scheduling queue",
+			operations: []operation{
+				updatePluginToGateAllPods,
+				add,
+				moveAllToActiveOrBackoffQ,
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: I'm curious: why do you do the move twice at this point?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 6]
```diff
@@ -4647,3 +4650,154 @@ func TestPriorityQueue_GetPod(t *testing.T) {
...
+				pInfos[:1],
+			},
+			expectedMetric: 0,
+		},
+		{
+			name: "Unschedulable pods metric should not be duplicate if gated pods added and then gated with the same plugin again",
+			operations: []operation{
+				updatePluginToGateAllPods,
+				add,
+				moveAllToActiveOrBackoffQ,
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Follow up to the question above: in the scenarios above you call `move` twice after `add`, and here you only call it once. Why?

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 7]
```diff
@@ -4647,3 +4650,154 @@ func TestPriorityQueue_GetPod(t *testing.T) {
...
+				{nil},
+				pInfos[:1],
+				{nil},
+				{nil},
+				pInfos[:1],
+			},
+			expectedMetric: 0,
+		},
+		{
+			name: "Unschedulable pods metric must be 1 after pod is gated multiple time by simillar plugin",
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]:
```suggestion
			name: "Unschedulable pods metric must be 1 after pod is gated multiple time by the same plugin",
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 8]
```diff
@@ -4647,3 +4650,154 @@ func TestPriorityQueue_GetPod(t *testing.T) {
...
+			operands: [][]*framework.QueuedPodInfo{
+				{nil},
+				pInfos[:1],
+				{nil},
+				{nil},
+			},
+			expectedMetric: 1,
+		},
+		{
+			name: "Unshedulable pods metric must be 0 after non gated pods is added and then deleted",
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]:
```suggestion
			name: "Unschedulable pods metric must be 0 after non gated pods is added and then deleted",
```

File: pkg/scheduler/backend/queue/scheduling_queue_test.go [hunk 9]
```diff
@@ -4647,3 +4650,154 @@ func TestPriorityQueue_GetPod(t *testing.T) {
 		})
 	}
 }
+
+func TestUnschedulablePodsMetric(t *testing.T) {
+	preenqueuePluginName := "preEnqueuePlugin"
```
Comment (ania-borowiec) [inline pkg/scheduler/backend/queue/scheduling_queue_test.go]: Do you think you could add a single (I think we don't need more) test scenario for a case where 2 a pod is gated by 2 or more plugins?

**Review by ania-borowiec — COMMENTED** [review]
Thanks for fixing this!

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 5 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Since the plugin metrics are already captured during the add flow, calling the move method twice is redundant. I will reduce this to a single invocation to avoid confusion.

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 6 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Answered into comment above.

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 9 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: My initial assumption was that since a Pod stops at the first gating plugin, we wouldn't encounter metric conflicts. However, I have confirmed a scenario where this logic fails.

If a Pod was previously gated by Plugin A, but on the next attempt Plugin A passes and the Pod is then gated by Plugin B, we encounter a metric leak. Because the Pod remains in the queue during this transition (it is not popped or deleted), the metric for Plugin A is never decremented. Consequently, the metrics incorrectly indicate that the Pod is gated by both plugins, even though it is currently only gated by Plugin B.

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Upon further investigation, this appears to be expected behavior. The UnschedulablePlugins and PendingPlugins sets in PodInfo are designed to track all plugins that have contributed to scheduling failures for a pod throughout its lifecycle, rather than just the single plugin that blocked the most recent attempt. Since our metric logic is derived directly from these sets, the metrics correctly reflect this cumulative state—showing every plugin that currently considers the pod unschedulable.

Comment (ania-borowiec) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Yup, that's the intended behavior. This way the value of `unschedulable_pods` for a specific plugin should never be greater than the actual number of pods in unschedulable queue - even though the sum of values of `unschedulable_pods` for all plugins can be greater than the number of pods in unschedulable.

Still I think this scenario should be covered by a test:
1) that verifies that after the pod becomes schedulable, the metric for all relevant plugins would be decreased
2) and another one that verifies the flow you described above - that all plugins involved would be shown in the metric

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Yes, I will cover this scenario

Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 8 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 7 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done

File: pkg/scheduler/backend/queue/scheduling_queue_test.go (hunk 4 above)
Comment (vshkrabkov) [reply pkg/scheduler/backend/queue/scheduling_queue_test.go]: Done
