### PR TITLE
Avoid creation of the same storageclass in e2e tests

### LINKED ISSUE #97993: Storage cloning e2e using default storageclass instead of configured
**Which jobs are failing**:

**Which test(s) are failing**:
 provisioning should provision storage with pvc data source in parallel 

**Since when has it been failing**:
The test case was introduced in 1.18 but is unclear when it started failing. Lowest observation is 1.19.

**Testgrid link**:

**Reason for failure**:
```
go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go:264
Jan 12 02:29:31.942: Unexpected error:
    <*errors.errorString | 0xc0039ba7b0>: {
        s: "No default storage class found",
    }
    No default storage class found
occurred
go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/provisioning.go:355
```
**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by mauriciopoppe**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

During a parallel test it was assumed that we had a default storageclass, if the cluster doesn't have it then the test fails.

The test creates its own storageclass which should be shared across all its usages, in the `should provision storage with pvc data source in parallel [Slow]` test case the storageclass was created once during setup and then attempted to be created again and deleted from every go routine, instead, now it's created once during setup and for the parallel tests we first check if the storageclass is already created (always true in this test case)

#### Which issue(s) this PR fixes:

Fixes #97993

#### Special notes for your reviewer:

It's my first PR to k/k  🥳

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @msau42

### CODE REVIEW

File: test/e2e/storage/testsuites/provisioning.go [hunk 1]
```diff
@@ -323,17 +320,25 @@ func (t StorageClassTest) TestDynamicProvisioning() *v1.PersistentVolume {
...
-		}()
+		if err == nil {
+			// skip storageclass creation if it already exists, this case happens when
+			// preparePVCDataSourceForProvisioning is called first
+			ginkgo.By("Storage class " + class.Name + " is already created, skipping creation.")
+		} else {
+			ginkgo.By("creating a StorageClass " + class.Name)
+			_, err = client.StorageV1().StorageClasses().Create(context.TODO(), class, metav1.CreateOptions{})
+			// The "should provision storage with snapshot data source" test already has created the class.
+			// TODO: make class creation optional and remove the IsAlreadyExists exception
```
Comment (msau42) [inline test/e2e/storage/testsuites/provisioning.go:333]: I think it would be cleaner if this function is more explicit about which tests already create the StorageClass ahead of time and which do not. Or change all tests to create the StorageClass outside of TestDynamicProvisioning so that we're consistent across all test cases.

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:333]: hey @msau42, @jingxu97 pointed out one nice observation which is that if this e2e test wasn't testing the implicit usage of the default storage class then we might need one or we might modify this one too, another strategy that I was implementing was to have each go routine create its own resources (its own storageclass, its own pvc, its own injector, etc) but I'm not sure if the test is about sharing the storageclass that's created before the go routines run.

Another thing that I wanted to ask was if creation of resources should be detached from properties in the testcase, if so then I can modify the signature to accept more parameters to control the creation like this:

```go
func (t StorageClassTest) TestDynamicProvisioning(shouldCreateStorageClass, shouldCreatePVC bool) *v1.PersistentVolume {
```

Comment (msau42) [reply test/e2e/storage/testsuites/provisioning.go:333]: I think we don't need each go routine to have its own storageclass. The main purpose of the test case creating the storageclass, is if it needs to modify any fields such as bindingMode or allowVolumeExpansion. But generally the StorageClass is considered a shared resource.

Agree that we should have test cases that explicitly test default storageclass vs non-default. For tests run under storage/testsuites, we don't test the default storageclass. For tests one level above "test/e2e/storage" we have some default storageclass cases, although it may be worth considering adding another config for testsuites just to use the default storageclass (should be considered separate from this issue).

I think this function needs to continue to handle both default and non-default storageclasses. My main suggestion was to simplify the logic so that in either case, the StorageClass is created outside of this function.

File: test/e2e/storage/testsuites/provisioning.go [hunk 2]
```diff
@@ -888,18 +898,20 @@ func preparePVCDataSourceForProvisioning(
...
 			framework.Failf("Error deleting source PVC %q. Error: %v", sourcePVC.Name, err)
 		}
-		if class != nil {
-			framework.Logf("deleting class %q", class.Name)
-			err := client.StorageV1().StorageClasses().Delete(context.TODO(), class.Name, metav1.DeleteOptions{})
-			if err != nil && !apierrors.IsNotFound(err) {
-				framework.Failf("Error deleting storage class %q. Error: %v", class.Name, err)
-			}
-		}
+
```
Comment (mauriciopoppe) [inline test/e2e/storage/testsuites/provisioning.go:907]: I'll remove these comments

File: test/e2e/storage/testsuites/provisioning.go [hunk 3]
```diff
@@ -842,11 +857,11 @@ func prepareSnapshotDataSourceForProvisioning(
 		err = snapshotResource.CleanupResource(f.Timeouts)
 		framework.ExpectNoError(err)
 
-		ginkgo.By("deleting StorageClass " + class.Name)
-		err = client.StorageV1().StorageClasses().Delete(context.TODO(), class.GetName(), metav1.DeleteOptions{})
-		if err != nil && !apierrors.IsNotFound(err) {
-			framework.Failf("Error deleting storage class %q. Error: %v", class.GetName(), err)
-		}
+		// ginkgo.By("deleting StorageClass " + class.Name)
```
Comment (mauriciopoppe) [inline test/e2e/storage/testsuites/provisioning.go:860]: I'll remove these comments

File: test/e2e/storage/testsuites/provisioning.go [hunk 4]
```diff
@@ -305,36 +305,76 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
...
+		// StorageClass is nil, so the default one will be used
+		scName, err := e2epv.GetDefaultStorageClassName(client)
+		framework.ExpectNoError(err)
+		computedStorageClass, err = client.StorageV1().StorageClasses().Get(context.TODO(), scName, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		// If late binding is configured, create and delete a pod to provision the volume
+		if *computedStorageClass.VolumeBindingMode == storagev1.VolumeBindingWaitForFirstConsumer {
+			ginkgo.By("creating a pod referring to the claim")
+			var pod *v1.Pod
+			pod, err := e2epod.CreatePod(client, claim.Namespace, nil /* nodeSelector */, []*v1.PersistentVolumeClaim{claim}, true /* isPrivileged */, "" /* command */)
```
Comment (msau42) [inline test/e2e/storage/testsuites/provisioning.go:357]: It is a little strange to be creating a pod in this storageclass creation function. Maybe this part should be moved to TestDynamicProvisioning. (This should also run in either case of default/non-default storageclass)

File: test/e2e/storage/testsuites/provisioning.go [hunk 5]
```diff
@@ -305,36 +305,76 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
...
+			// Delete pod now, otherwise PV can't be deleted below
+			framework.ExpectNoError(err)
+			e2epod.DeletePodOrFail(client, pod.Namespace, pod.Name)
+		}
+	}
+
+	return computedStorageClass, clearComputedStorageClass
+}
+
 // TestDynamicProvisioning tests dynamic provisioning with specified StorageClassTest
```
Comment (msau42) [inline test/e2e/storage/testsuites/provisioning.go:367]: Can you add a comment here that this method expects the StorageClass to already exist.

File: test/e2e/storage/testsuites/provisioning.go (hunk 4 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go]: Thanks, this also reduced the number of parameters to create the StorageClass

File: test/e2e/storage/testsuites/provisioning.go (hunk 5 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:355]: Got it

File: test/e2e/storage/testsuites/provisioning.go [hunk 6]
```diff
@@ -305,35 +305,78 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
...
 			}(i)
 		}
 		wg.Wait()
 	})
 }
 
+// ProvisionStorageClass provisions a StorageClass from a spec, if the StorageClass already exists
+// then it returns it as a `computed` StorageClass, if it doesn't exist then it's created first
+// and then returned, if the spec is nil then we return the `default` StorageClass
+func ProvisionStorageClass(
```
Comment (jingxu97) [inline test/e2e/storage/testsuites/provisioning.go:318]: just a small nit: maybe use setup StorageClass (I choose set up instead of create mainly because in some cases, we don't create new Storageclass). typically we use provision for disks/volumes

File: test/e2e/storage/testsuites/provisioning.go [hunk 7]
```diff
@@ -305,35 +305,78 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
...
+	var clearComputedStorageClass = func() {}
+	if class != nil {
+
+		computedStorageClass, err = client.StorageV1().StorageClasses().Get(context.TODO(), class.Name, metav1.GetOptions{})
+		if err == nil {
+			// skip storageclass creation if it already exists
+			ginkgo.By("Storage class " + computedStorageClass.Name + " is already created, skipping creation.")
+		} else {
+			ginkgo.By("Creating a StorageClass " + class.Name)
+			_, err = client.StorageV1().StorageClasses().Create(context.TODO(), class, metav1.CreateOptions{})
```
Comment (jingxu97) [inline test/e2e/storage/testsuites/provisioning.go:335]: Want to verify: Is there some case that different test share the same storageClass name, but the spec of the storageclass might be different. Need to verify this behavior.

File: test/e2e/storage/testsuites/provisioning.go (hunk 6 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:318]: in persistent_volumes-local.go there's a private method called `setupStorageClass(config, &testMode)`, is your suggestion to use that method instead?

File: test/e2e/storage/testsuites/provisioning.go (hunk 7 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:335]: I did a search and all of the test cases inside testsuites create a StorageClass here https://github.com/kubernetes/kubernetes/blob/89d1e37ff116fbd5f41e7afee06af601ae611e66/test/e2e/storage/testsuites/provisioning.go#L144, this method is implemented by multiple drivers and all of them call https://github.com/kubernetes/kubernetes/blob/66fa2c49e28b9dcf478a87636971bc7d241b2849/test/e2e/storage/framework/driver_operations.go#L65 which creates a unique StorageClass name

TestDynamicProvisioning was always creating the StorageClass this way, what would we verify in this case?

File: test/e2e/storage/testsuites/provisioning.go (hunk 6 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:318]: I think that this suggestion is about renaming `ProvisionStorageClass` to `SetupStorageClass`, is that right?

File: test/e2e/storage/testsuites/provisioning.go (hunk 4 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go]: while doing some tests I found out that `TestDynamicProvisioning` is also being called with a storageV1Beta1 class https://github.com/kubernetes/kubernetes/blob/89d1e37ff116fbd5f41e7afee06af601ae611e66/test/e2e/storage/volume_provisioning.go#L374-L396, my implementation was creating a bug and using the default storage class when it should've been using the beta storage class, I thought about using a union type but that's not available in go yet https://github.com/golang/go/issues/19412 so I thought of some alternatives:

- duplicate `TestDynamicProvisioning` for the beta test case
- add `TestConfig.ClassBeta` that's set only in this method, I'm not sure how I'd prefer using this vs `Class`
- make `TestConfig.Class` a raw interface and add an additional property to decode it e.g. `TestConfig.ClassVersion` is a string or enum

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go]: For the test I did a cast as you explained, the object is created as a v1beta1 object and immediately fetched as a v1 object with the implicit conversion for the test

File: test/e2e/storage/testsuites/provisioning.go [hunk 8]
```diff
@@ -348,21 +379,18 @@ func (t StorageClassTest) TestDynamicProvisioning() *v1.PersistentVolume {
...
-		// StorageClass is nil, so the default one will be used
-		scName, err := e2epv.GetDefaultStorageClassName(client)
-		framework.ExpectNoError(err)
-		defaultSC, err := client.StorageV1().StorageClasses().Get(context.TODO(), scName, metav1.GetOptions{})
+	// ensure that the claim refers to the provisioned StorageClass
+	framework.ExpectEqual(*claim.Spec.StorageClassName, class.Name)
+
+	// If it's the default StorageClass and if late binding is configured, create and delete a pod to provision the volume
+	defaultStorageClassName, err := e2epv.GetDefaultStorageClassName(client)
+	if err != nil && defaultStorageClassName == class.Name && *class.VolumeBindingMode == storagev1.VolumeBindingWaitForFirstConsumer {
```
Comment (msau42) [inline test/e2e/storage/testsuites/provisioning.go:387]: If the input storageclass has WaitForFirstConsumer, then we should do this regardless.

File: test/e2e/storage/testsuites/provisioning.go [hunk 9]
```diff
@@ -828,6 +851,8 @@ func prepareSnapshotDataSourceForProvisioning(
 	}
 
 	cleanupFunc := func() {
+		clearComputedStorageClass()
```
Comment (msau42) [inline test/e2e/storage/testsuites/provisioning.go:854]: There is not supposed to be a dependency on StorageClass for volume deletion, but unfortunately we may have skipped through the cracks in some corner cases. So I think this needs to be called at the end. ditto everywhere

File: test/e2e/storage/testsuites/provisioning.go (hunk 8 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:387]: I had it like:

```go
	if *class.VolumeBindingMode == storagev1.VolumeBindingWaitForFirstConsumer {
```

But a test was failing, after comparing master I saw that this was only done for the default StorageClass

File: test/e2e/storage/testsuites/provisioning.go (hunk 9 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:854]: Ack, I'll move this line to the end

**Comment by msau42** [comment]
Thanks, this is lgtm! Just one last thing, can you squash your commits into one? If you haven't done it before, here's some steps: https://www.kubernetes.dev/docs/contributor-cheatsheet/#squashing-commits. Maybe practice on another branch first :-)

/approve

File: test/e2e/storage/testsuites/provisioning.go (hunk 8 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go]: So I pushed a new change with the line above and CI is now failing: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/99346/pull-kubernetes-e2e-gce-storage-snapshot/1365397576798441472/, what should I do in this case? should I use the same code in master (the one that has `if err != nil && defaultStorageClassName == class.Name`) or should I attempt to find the root cause of this bug?

Comment (msau42) [reply test/e2e/storage/testsuites/provisioning.go]: I think it would be best to debug why the test is failing.

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go]: Ack :)

**Comment by mauriciopoppe** [comment]
/remove-kind api-change
/remove-area code-generation conformance dependency e2e-test-framework ipvs kubeadm kubectl kubelet provider/gcp release-eng
/remove-sig api-machinery apps architecture-auth autoscaling cli cloud-provider cluster-lifecycle contributor-experience instrumentation network node release scalability scheduling testing windows

File: test/e2e/storage/testsuites/provisioning.go (hunk 6 above)
Comment (jingxu97) [reply test/e2e/storage/testsuites/provisioning.go:318]: right

File: test/e2e/storage/testsuites/provisioning.go (hunk 7 above)
Comment (jingxu97) [reply test/e2e/storage/testsuites/provisioning.go:334]: I thought we were saying the storageClass name is the same to different tests that is why storageClass might already exist when test tries to create it. If each storage class is unique for each test, it normally should not exist already?

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:334]: that's correct, if the storageclass already exists then the test could fail, I can change this to throw an exception instead

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:334]: One of the cases where the storage class already exists when it enters this method is in the v1beta1 case, the storage class is created outside this method and when this method is called then it's fetched from the cluster but as a v1 object, do you think that in the beta case I shouldn't use this method?

File: test/e2e/storage/testsuites/provisioning.go [hunk 10]
```diff
@@ -348,21 +379,17 @@ func (t StorageClassTest) TestDynamicProvisioning() *v1.PersistentVolume {
...
-	if class == nil {
-		// StorageClass is nil, so the default one will be used
-		scName, err := e2epv.GetDefaultStorageClassName(client)
-		framework.ExpectNoError(err)
-		defaultSC, err := client.StorageV1().StorageClasses().Get(context.TODO(), scName, metav1.GetOptions{})
+	// ensure that the claim refers to the provisioned StorageClass
+	framework.ExpectEqual(*claim.Spec.StorageClassName, class.Name)
+
+	// if late binding is configured, create and delete a pod to provision the volume
+	if *class.VolumeBindingMode == storagev1.VolumeBindingWaitForFirstConsumer {
```
Comment (mauriciopoppe) [inline test/e2e/storage/testsuites/provisioning.go:386]: @msau42 the conversation was dropped after I did the rebase fix, sorry about that.

After debugging the test I saw that the Pod created in this if statement was failing with the following error:

```
 Warning  FailedMount  7s    kubelet, e2e-test-mauriciopoppe-minion-group-pnq9  Unable to attach or mount volumes: unmounted volumes=[volume1], unattached volumes=[volume1 default-token-b9jmr[]: volume volume1 has volumeMode Block, but is specified in volumeMounts
```

After some debugging I found out that the test is failing because the claim dynamically provisions a PV with volumeMode = Block and this pod is created with `volumeMounts` instead of `volumeDevices` for all the cases, if the objective of this test is to also make it work with a BlockDevice then I can create either `volumeMounts` (the default) or `volumeDevices` inside `e2e.CreatePod`, we could also skip this test for block devices, what do you think?

File: test/e2e/storage/testsuites/provisioning.go [hunk 11]
```diff
@@ -289,11 +292,8 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
 				myTestConfig := testConfig
 				myTestConfig.Prefix = fmt.Sprintf("%s-%d", myTestConfig.Prefix, i)
 
-				// Each go routine must have its own testCase copy to store their claim
-				myTestCase := *l.testCase
-				myTestCase.Claim = myTestCase.Claim.DeepCopy()
-				myTestCase.Class = nil // Do not create/delete the storage class in TestDynamicProvisioning, it already exists.
-				myTestCase.PvCheck = func(claim *v1.PersistentVolumeClaim) {
+				t := *l.testCase
+				t.PvCheck = func(claim *v1.PersistentVolumeClaim) {
```
Comment (jingxu97) [inline test/e2e/storage/testsuites/provisioning.go:296]: why remove Claim.DeepCopy()?

Comment (jingxu97) [reply test/e2e/storage/testsuites/provisioning.go:296]: Also I don't know why class was set to nil before. The author @jsafrane https://github.com/kubernetes/kubernetes/commit/1f9f2390cb57832f5fbd02e53d39023b81500cc2 specifically made a comment about storageclass already exist? Is it trying to test default storage class behavior?

File: test/e2e/storage/testsuites/provisioning.go (hunk 10 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:386]: I opted for adding support to create volumeDevices in the e2e pod creation method

File: test/e2e/storage/testsuites/provisioning.go (hunk 11 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:296]: t.Claim is just a spec without a name, `TestDynamicProvisioning` will create the actual object, from what I understand this will happen as long as the object created is unique and it is because it doesn't have a name

for `t.Class = nil` it might have been a mistake because the test wasn't using the class setup before the goroutines (it was instead using the default storageclass if it existed), @msau42 clarified that inside testsuites we don't have tests for the default storageclass

Comment (jingxu97) [reply test/e2e/storage/testsuites/provisioning.go:296]: I see. The claim is using a GenerateName which provides the prefix and when creating PVC, it will generate a unique dynamically.

Comment (jsafrane) [reply test/e2e/storage/testsuites/provisioning.go:296]: Ack to the storage class changes in this PR - it's better to create a new one for each test inside the testsuites.

File: test/e2e/framework/pod/create.go [hunk 12]
```diff
@@ -157,14 +157,20 @@ func MakePod(ns string, nodeSelector map[string]string, pvclaims []*v1.Persisten
...
 	}
-	var volumeMounts = make([]v1.VolumeMount, len(pvclaims))
+	var volumeMounts = make([]v1.VolumeMount, 0)
+	var volumeDevices = make([]v1.VolumeDevice, 0)
 	var volumes = make([]v1.Volume, len(pvclaims))
 	for index, pvclaim := range pvclaims {
 		volumename := fmt.Sprintf("volume%v", index+1)
-		volumeMounts[index] = v1.VolumeMount{Name: volumename, MountPath: "/mnt/" + volumename}
+		if *pvclaim.Spec.VolumeMode == v1.PersistentVolumeBlock {
+			volumeDevices = append(volumeDevices, v1.VolumeDevice{Name: volumename, DevicePath: "/mnt/" + volumename})
```
Comment (msau42) [inline test/e2e/framework/pod/create.go:166]: Instead of using "/mnt", how about something like "/devices". That probably would require changes to all the consumers.

File: test/e2e/storage/testsuites/provisioning.go (hunk 11 above)
Comment (msau42) [reply test/e2e/storage/testsuites/provisioning.go:296]: Regarding `t.Claim`, does every caller use GenerateName? If we want to make that assumption, then it may be better to assert on it so we catch any future changes.

File: test/e2e/framework/pod/create.go (hunk 12 above)
Comment (msau42) [reply test/e2e/framework/pod/create.go:166]: Actually, that may be too many changes for now, I take back that suggestion.

We actually already have [MakeSecPod](https://github.com/kubernetes/kubernetes/blob/f66869906d6fafd920f3e8e07020602b79eba88e/test/e2e/framework/pod/create.go#L183) which handles block devices already. What if we use that method instead?

File: test/e2e/storage/testsuites/provisioning.go (hunk 11 above)
Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/provisioning.go:289]: yes, all of the callers use `e2epv.MakePersistentVolumeClaim` with an empty `Name` but with a `NamePrefix`, I added an assertion in `TestDynamicProvisioning` to ensure that `NamePrefix` is set (although it could be overriden by setting Name but no test does this at this moment)

**Comment by msau42** [comment]
/lgtm
/approve

Thanks!
