### PR TITLE
fix wrong NumCPU in kube-proxy under static CPU policy

### LINKED ISSUE #99225: Kube-proxy's conntrack-max was set lower than desired with static CPU Policy
#### What would you like to be added:
A new flag indicating how kube-proxy gets the number of CPUs, either from goruntime or `/proc/cpuinfo`.

#### Why is this needed:
In kube-proxy, we can use `--conntrack-max-per-core` to set node's `conntrack-max`, the resulting `conntrack-max` is `int(*config.MaxPerCore) * goruntime.NumCPU()`.

https://github.com/kubernetes/kubernetes/blob/f49385d05a38d0dec06be6a324fb4fe3a720f4db/cmd/kube-proxy/app/server.go#L787

##### Case 1
We have nodes where pods with none CPU policy and static CPU policy are running together. Pods like kube-proxy are running in none CPU policy by default, and they only gets CPUs left by static CPU policy pods. If static CPU policy pods take away most CPUs cores, kube-proxy can only get one or two cores, then `conntrack-max` will be set to a very small values. In this case, a lot packet failure can occur.

##### Case 2
When we set kube-proxy to work in static CPU policy, kube-proxy only gets the number of CPUs selected by the CPU policy, not the number of total CPUs on the node. This may *surprise* users who are only trying to limit kube-proxy's CPU usages, but resulting in some conntrack fulls faults.

Please let me know if this enhancement is reasonable, so I can send a pr later. Thanks!

### PR DESCRIPTION
**Pull request by xh4n3**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes wrong NumCPU used in conntrack-max calculation in kube-proxy on nodes with static CPU policy turned on.

#### Which issue(s) this PR fixes:
Fixes #99225

#### Special notes for your reviewer:
kube-proxy will try look up CPU core number in Node resource info to calculate conntrack-max, only if failed, it will then lookup through golang's `runtime.NumCPU()`.

#### Does this PR introduce a user-facing change?
```release-note
Fixed a bug that causes smaller number of conntrack-max being used under CPU static policy. (#99225, @xh4n3)
```

### CODE REVIEW

File: cmd/kube-proxy/app/server_windows.go [hunk 1]
```diff
@@ -185,6 +186,10 @@ func getProxyMode(proxyMode string, kcompat winkernel.KernelCompatTester) string
 	return proxyModeUserspace
 }
 
+func detectNumCPU() int {
+	return goruntime.NumCPU()
```
Comment (thockin) [inline cmd/kube-proxy/app/server_windows.go:190]: Is this OK?  Does it need followup?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
/retest

File: cmd/kube-proxy/app/server_windows.go (hunk 1 above)
Comment (xh4n3) [reply cmd/kube-proxy/app/server_windows.go:190]: Should I put a comment in this line or skip calling getConntrackMax() by judging runtime.GOOS  at https://github.com/kubernetes/kubernetes/blob/d6bc98fc5a39e7ff16dc563408b35767024b13b5/cmd/kube-proxy/app/server.go#L671-L677
In fact no windows will come to this point.

**Comment by xh4n3** [comment]
@thockin can I have this commit backport to 1.20 or earlier version?
