### PR TITLE
Fix zone on relelease-1.3

### LINKED ISSUE #35654: All test suite kubernetes-e2e-gce-*-release-1.4 failed
All test suite running against 1.4 release on containervm image failed since ~8:40am this morning. We should fix the issue before we cut another patch release.

cc/ @fejta @foxish, oncall

### PR DESCRIPTION
**Pull request by jessfraz**
Cherrypick of ee6e92473d24c30417f49ca261fa7c436551fc48

fix #35654 ping @wonderfly @fabioy for release-1.3

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35830)

### CODE REVIEW

**Review by ixdy — CHANGES_REQUESTED** [review]
The flag changed to `--zones` only for list operations. Everything else should remain `--zone`.

**Comment by jessfraz** [comment]
crap sorry the original patch didnt apply right so i changed them all, I
will fix

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -338,14 +338,14 @@ function detect-node-names {
...
-    --zone "${ZONE}" --project "${PROJECT}" \
+    --zones "${ZONE}" --project "${PROJECT}" \
     --regexp "${NODE_INSTANCE_PREFIX}-.+" \
     --format='value(instanceGroup)' || true))
   NODE_NAMES=()
   if [[ -n "${INSTANCE_GROUPS[@]:-}" ]]; then
     for group in "${INSTANCE_GROUPS[@]}"; do
       NODE_NAMES+=($(gcloud compute instance-groups managed list-instances \
-        "${group}" --zone "${ZONE}" --project "${PROJECT}" \
+        "${group}" --zones "${ZONE}" --project "${PROJECT}" \
```
Comment (jessfraz) [inline cluster/gce/util.sh]: @ixdy is it for list-instances too?

Comment (jessfraz) [inline cluster/gce/util.sh]: the failing build answered my question lol nevermind

Comment (wonderfly) [inline cluster/gce/util.sh]: Yeah, the gcloud release notes aren't very helpful... They say command line flag abbreviations are no longer supported, but don't mention what "command line flag abbreviations" are. Google search doesn't show anything either.

**Comment by wonderfly** [comment]
LGTM as long as tests pass

**Comment by wonderfly** [comment]
@jessfraz I can't apply labels. Can you ping someone else for a LGTM?

**Comment by fabioy** [comment]
Manually merged.
