### PR TITLE
hotfix when a plugin (in-tree or out-of-tree) return non-existent/illegal nodes, the pod scheduling flow will abort immediately.

### LINKED ISSUE #123465: PV nodeAffinity matchExpressions problem with array items and `in` operator since 1.27.0
### What happened?

Since v1.27.0, the `nodeAffinity` for `PersistentVolumes` appear to have added extra validation on whether the values exist, despite using the `in` operator. This works as expected on 1.26.14, and no longer works on 1.27.0 onwards (tested up to 1.29.2).

I am unsure whether this is an intentional breaking change in 1.27.0 or something wrong in our manifests and we've just so happened to get away with it for a few years. The only thing that stands out to me in the changelog for 1.27.0 is some changes to the schedulers `Filter` plugin but this may well be unrelated.

### What did you expect to happen?

When using the `in` operator, I'd expect the expression to only apply to nodes where the match is truey.

### How can we reproduce it (as minimally and precisely as possible)?

Note, using Kind for easy reproduction

### creating a kind cluster
~~~ shell
cat <<EOF > kind_conf
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.26.14
- role: worker
  image: kindest/node:v1.26.14
- role: worker
  image: kindest/node:v1.26.14
EOF

$ kind create cluster --name 12614-test --config kind_conf
$ k get no
NAME                       STATUS   ROLES           AGE   VERSION
12614-test-control-plane   Ready    control-plane   8h    v1.26.14
12614-test-worker          Ready    <none>          8h    v1.26.14
12614-test-worker2         Ready    <none>          8h    v1.26.14
# labelling a node to ensure pod is scheduled on specific worker
$ k label node 12614-test-worker nginx=nginx
~~~

~~~ shell
cat <<EOF > manifest.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nginx
                operator: Exists
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/nginx
          name: default-nginx-data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: default-nginx-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: my_sc
      volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-nginx-data-nginx-0
  namespace: default
  labels:
    app: default-nginx-data-nginx-0
spec:
  storageClassName: my_sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/k8s/default/nginx-0
  claimRef:
    namespace: default
    name: default-nginx-data-nginx-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - 12614-test-worker
            - 12614-prod-worker
EOF
# Apply the manifest
$ k apply -f manifest.yaml
~~~

Since `12614-test-worker` exists in the hostname values of this cluster, the pod schedules as expected. `12614-prod-worker` node does not exist in this environment, and so is ignored.

~~~ shell
$ k get po
NAME      READY   STATUS    RESTARTS   AGE
nginx-0   1/1     Running   0          6m2s
~~~
### creating a kind cluster
~~~ shell
cat <<EOF > kind_conf
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.27.0
- role: worker
  image: kindest/node:v1.27.0
- role: worker
  image: kindest/node:v1.27.0
EOF

$ kind create cluster --name 1270-test --config kind_conf
# labelling a node to ensure pod is scheduled on specific worker
$ k label node 1270-test-worker nginx=nginx
~~~

~~~ shell
cat <<EOF > manifest.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nginx
                operator: Exists
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/nginx
          name: default-nginx-data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: default-nginx-data
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      storageClassName: my_sc
      volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-nginx-data-nginx-0
  namespace: default
  labels:
    app: default-nginx-data-nginx-0
spec:
  storageClassName: my_sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /srv/k8s/default/nginx-0
  claimRef:
    namespace: default
    name: default-nginx-data-nginx-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - 1270-test-worker
            - 1270-prod-worker
EOF
# Apply the manifest
$ k apply -f manifest.yaml
~~~

Same expectations as 1.26.14, but in this case, the pod stays stuck in pending state due to the following;

~~~ shell
$ k get no
NAME                      STATUS   ROLES           AGE     VERSION
1270-test-control-plane   Ready    control-plane   5m1s    v1.27.0
1270-test-worker          Ready    <none>          4m34s   v1.27.0
1270-test-worker2         Ready    <none>          4m39s   v1.27.0
$ k get po
NAME      READY   STATUS    RESTARTS   AGE
nginx-0   0/1     Pending   0          5m56s
$ kubectl events --for pod/nginx-0
LAST SEEN   TYPE      REASON             OBJECT        MESSAGE
3m6s        Warning   FailedScheduling   Pod/nginx-0   nodeinfo not found for node name "1270-prod-worker"
~~~

I have tested this all the way up to 1.29.2.

### Anything else we need to know?

_No response_

### Kubernetes version

v1.27.0 through to v1.29.2

### Cloud provider

<details>

</details>

### OS version

<details>

```console
[root@stage1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@stage1 ~]# uname -a
Linux stage1.domain.com 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
this is a minimum fix from #119779
In versions 1.27-1.29, if there is a non-existent node in the PreFilterResult, the pod schedule will fail.

#### Which issue(s) this PR fixes:
Fixes #123465 

#### Does this PR introduce a user-facing change?
```release-note
kube-scheduler: fixed a 1.27 regression that a pod may remain unscheduled if any PreFilter plugin returns nodes that do not exist.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Also, let's wait for https://github.com/kubernetes/kubernetes/pull/124539 to merge and also cherry-pick in this same PR.

**Comment by alculquicondor** [comment]
I don't think the tests are flaky. Maybe they are making some assumptions about the nodes existing.


If it becomes too much burden, I think we should just cherry-pick the entire original PR https://github.com/kubernetes/kubernetes/pull/119779

**Comment by chengjoey** [comment]
> I don't think the tests are flaky. Maybe they are making some assumptions about the nodes existing.
> 
> If it becomes too much burden to fix them, I think we should just cherry-pick the entire original PR #119779

the tests are not flaky, but the original PR 119779 also modified the test, but the test was not changed just now, so it is normal now
image

**Comment by Huang-Wei** [comment]
It's b/c @sanposhiho 's PR introduced a change to set UnschedulableAndUnresolvable to each node that's filtered out by PreFilterResult:

https://github.com/kubernetes/kubernetes/blob/7d880fd489d1e57bc1c13568f1cbb4c5c5e93947/pkg/scheduler/schedule_one.go#L486-L497

And the logic of counting `processedNodes` is based on `feasibleNodes` and `diagnosis.NodeToStatusMap`:

https://github.com/kubernetes/kubernetes/blob/7d880fd489d1e57bc1c13568f1cbb4c5c5e93947/pkg/scheduler/schedule_one.go#L501

So it caused the UT's change, but it's not a big issue IMHO.

@chengjoey could you also incorporate d3821508f13117f9f6c9a4b3046eb7971b057d50 into this PR?

**Comment by chengjoey** [comment]
> @chengjoey could you also incorporate [d382150](https://github.com/kubernetes/kubernetes/commit/d3821508f13117f9f6c9a4b3046eb7971b057d50) into this PR?

done

File: test/integration/scheduler/filters/filters_test.go [hunk 1]
```diff
@@ -2042,6 +2043,53 @@ func TestUnschedulablePodBecomesSchedulable(t *testing.T) {
 				return deletePod(cs, "pod-to-be-deleted", ns)
 			},
 		},
+		{
+			name: "pod with pvc has node-affinity to non-existent/illegal nodes",
```
Comment (chengjoey) [inline test/integration/scheduler/filters/filters_test.go:2047]: hi  @Huang-Wei , in addition, the `test/integration/scheduler/filters/filters_test.go` test is added in this PR to enhance stability

**Comment by chengjoey** [comment]
> The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

It seems that this failed test is strangely, because the error is not related to the code changes.

image

File: test/integration/scheduler/filters/filters_test.go (hunk 1 above)
Comment (alculquicondor) [reply test/integration/scheduler/filters/filters_test.go:2047]: Please add this test to the master branch first

Comment (chengjoey) [reply test/integration/scheduler/filters/filters_test.go:2047]: > Please add this test to the master branch first

done

**Comment by alculquicondor** [comment]
Can you list in the description all the PRs that you are cherry-picking?

**Comment by alculquicondor** [comment]
Also worth cherry-picking #124567

**Comment by chengjoey** [comment]
> Also worth cherry-picking #124567

ok


there are cherry-pick lists

[add integration test for pod with pvc has node-affinity to non-existent/illegal nodes](https://github.com/kubernetes/kubernetes/pull/124666) 124666

[add e2e test when a plugin (in-tree or out-of-tree) return non-existent/illegal nodes, the pod should be scheduled normally if suitable nodes exists](https://github.com/kubernetes/kubernetes/pull/124567) 124567

[run all PreFilter when the preemption will happen later in the same scheduling cycle](https://github.com/kubernetes/kubernetes/pull/119779) 119779

[test to catch illegal nodeNames returned by PreFilterResult](https://github.com/kubernetes/kubernetes/pull/124539) 124539

**Comment by alculquicondor** [comment]
In the description, please :)

**Review by alculquicondor — COMMENTED** [review]
/approve

I'll leave LGTM to @Huang-Wei

**Comment by alculquicondor** [comment]
Oh, and please add a release note.

**Comment by Huang-Wei** [comment]
@chengjoey could you update the release-note as:

```
Fixed a bug that a pod may remain unscheduled if any PreFilter plugin returns nodes that do not exist.
```

**Comment by chengjoey** [comment]
> @chengjoey could you update the release-note as:
> 
> ```
> Fixed a bug that a pod may remain unscheduled if any PreFilter plugin returns nodes that do not exist.
> ```

done

**Comment by chengjoey** [comment]
After merging, need cherry-pick to 1.27 and 1.28

**Comment by alculquicondor** [comment]
/hold
We just found a regression in our internal scalability tests at 5k nodes that seems to be related to https://github.com/kubernetes/kubernetes/pull/119779

I'm investigating.

**Comment by alculquicondor** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/124709

**Comment by sanposhiho** [comment]
> cherry-pick https://github.com/kubernetes/kubernetes/pull/124714
preallocation for NodeToStatusMap

@chengjoey Please exclude it from this PR. The cheery-pick for mine should be separated. I'll prepare the one.

**Comment by sanposhiho** [comment]
Oh, wait. @alculquicondor, did you intend to include a cherry-pick for https://github.com/kubernetes/kubernetes/issues/124709 in this PR?

> Sorry, this will require more work. See https://github.com/kubernetes/kubernetes/issues/124709 for details
https://github.com/kubernetes/kubernetes/pull/124559#issuecomment-2096611140

**Comment by alculquicondor** [comment]
/hold cancel
#124753 targets 1.30.

This PR targets 1.29 and older. We need to include https://github.com/kubernetes/kubernetes/pull/124714 here.

**Comment by alculquicondor** [comment]
> I thought we should prepare a separate one not to include multiple bug fixes in one PR.

1.29 and older are currently unaffected. They will only be affected if this PR merges. Thus, we should include the performance fix.

**Comment by alculquicondor** [comment]
Anything we are missing? otherwise, I think you can prepare the cherry-picks for 1.28 and 1.27 based on this PR

**Comment by chengjoey** [comment]
there are some conflicts in schedule_one_test, in 1.27 and 1.28, so manual cherry-pick

**Review by Verolop — COMMENTED** [review]
/lgtm 
(Release Managers)
