### PR TITLE
Local storage teardown fix

### LINKED ISSUE #48331: Kubernetes 1.7.0 local storage teardown failed
/kind bug

Tearing down (for example simple updating pods in stateful set) of local-storage PVC seems to be broken:

> I0630 10:46:44.480172   24010 reconciler.go:186] operationExecutor.UnmountVolume started for volume "test" (UniqueName: "kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1") pod "97513921-5d70-11e7-a549-180373f4ecc0" (UID: "97513921-5d70-11e7-a549-180373f4ecc0") 
> I0630 10:46:44.480243   24010 local.go:271] Unmounting volume "test-affinity-test-1" at path "/www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-> 180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1"
W0630 10:46:44.480277   24010 util.go:87] Warning: "/www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1" is not a mountpoint, deleting
> E0630 10:46:44.480328   24010 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1\" (\"97513921-5d70-11e7-a549-180373f4ecc0\")" failed. No retries permitted until 2017-06-30 10:46:48.48030593 +0200 CEST (durationBeforeRetry 4s). Error: UnmountVolume.TearDown failed for volume "test" (UniqueName: "kubernetes.io/local-volume/97513921-5d70-11e7-a549-180373f4ecc0-test-affinity-test-1") pod "97513921-5d70-11e7-a549-180373f4ecc0" (UID: "97513921-5d70-11e7-a549-180373f4ecc0") : remove /www/adm/kubernetes/root/pods/97513921-5d70-11e7-a549-180373f4ecc0/volumes/kubernetes.io~local-volume/test-affinity-test-1: device or resource busy

I've managed to track it down to
pkg/volume/local/local.go calling through some pkg/volume/util/util.go  mounter.IsLikelyNotMountPoint(dir)

which literally has written in its comments:
> // IsLikelyNotMountPoint determines if a directory is not a mountpoint.
> // It is fast but not necessarily ALWAYS correct. If the path is in fact
> // a bind mount from one part of a mount to another it will not be detected.
> // mkdir /tmp/a /tmp/b; mount --bin /tmp/a /tmp/b; IsLikelyNotMountPoint("/tmp/b")
> // will return true. When in fact /tmp/b is a mount point. If this situation
> // if of interest to you, don't use this function...

which makes it detect it as a normal directory rather than a mount dir (as it is a normal directory... just bind mounted)

**Environment**:
- Kubernetes version (use `kubectl version`): v1.7.0
- Cloud provider or hardware configuration**: self hosted

Testing out a (dirty?) patch as we're speaking

### PR DESCRIPTION
**Pull request by ianchakeres**
**What this PR does / why we need it**: Local storage uses bindmounts and the method IsLikelyNotMountPoint does not detect these as mountpoints. Therefore, local PVs are not properly unmounted when they are deleted.

**Which issue this PR fixes**: fixes #48331

**Special notes for your reviewer**:

You can use these e2e tests to reproduce the issue and validate the fix works appropriately https://github.com/kubernetes/kubernetes/pull/47999

The existing method IsLikelyNotMountPoint purposely does not check mountpoints reliability (https://github.com/kubernetes/kubernetes/blob/4c5b22d4c6b630ff1d76b1d15d74c6597c0aa037/pkg/util/mount/mount_linux.go#L161), since the number of mountpoints can be large. https://github.com/kubernetes/kubernetes/blob/4c5b22d4c6b630ff1d76b1d15d74c6597c0aa037/pkg/util/mount/mount.go#L46

This implementation changes the behavior for local storage to detect mountpoints reliably, and avoids changing the behavior for any other callers to a UnmountPath.

**Release note**:

```
Fixes bind-mount teardown failure with non-mount point Local volumes (issue https://github.com/kubernetes/kubernetes/issues/48331).
```

### CODE REVIEW

**Comment by ianchakeres** [comment]
@k8s-ci-robot ok to test

**Comment by ianchakeres** [comment]
@CallMeFoxie @msau42 @saad-ali - Here is the PR to fix #48331. Please take a look and let me know if you have any questions or comments.

**Comment by CallMeFoxie** [comment]
> I0703 08:07:44.466131   22258 operation_generator.go:523] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/ae9f9214-5fb5-11e7-a549-180373f4ecc0-default-token-mhn97" (OuterVolumeSpecName: "default-token-mhn97") pod "ae9f9214-5fb5-11e7-a549-180373f4ecc0" (UID: "ae9f9214-5fb5-11e7-a549-180373f4ecc0"). InnerVolumeSpecName "default-token-mhn97". PluginName "kubernetes.io/secret", VolumeGidValue ""
> I0703 08:07:44.467018   22258 operation_generator.go:523] UnmountVolume.TearDown succeeded for volume "kubernetes.io/local-volume/ae9f9214-5fb5-11e7-a549-180373f4ecc0-test-affinity-test-1" (OuterVolumeSpecName: "test") pod "ae9f9214-5fb5-11e7-a549-180373f4ecc0" (UID: "ae9f9214-5fb5-11e7-a549-180373f4ecc0"). InnerVolumeSpecName "test-affinity-test-1". PluginName "kubernetes.io/local-volume", VolumeGidValue ""

looks good to me even with local self hosted storage, unmounts the volumes as it should back and forth.
cc @msau42 @saad-ali @jsafrane

File: pkg/volume/util/util.go [hunk 1]
```diff
@@ -75,23 +75,41 @@ func SetReady(dir string) {
...
 		return err
 	}
+
 	if notMnt {
 		glog.Warningf("Warning: %q is not a mountpoint, deleting", mountPath)
 		return os.Remove(mountPath)
 	}
 
 	// Unmount the mount path
+	glog.Warningf("Warning: %q is a mountpoint, unmounting", mountPath)
```
Comment (jsafrane) [inline pkg/volume/util/util.go]: I think that lower log level should be used, it's part of a normal operation.

Comment (ianchakeres) [inline pkg/volume/util/util.go]: @jsafrane - would you like me to lower the log level for the previous statement L107 too?

Comment (jsafrane) [inline pkg/volume/util/util.go]: No, at 107 something else happened - something unmounted a fs and left a stray directory there, e.g. kubelet crashed after unmount and before os.Remove. It's quite exceptional event.

Here on line 112 it's just normal operation, nothing suspicious.

**Comment by jsafrane** [comment]
lgtm to me, however I let @msau42 or @rootfs say the final word.

File: pkg/util/mount/mount.go [hunk 2]
```diff
@@ -199,3 +199,32 @@ func getDeviceNameFromMount(mounter Interface, mountPath, pluginDir string) (str
 
 	return path.Base(mountPath), nil
 }
+
+// IsNotMountPoint determines if a directory is a mountpoint.
+// It should return ErrNotExist when the directory does not exist.
+// This method uses the List() of all mountpoints
```
Comment (msau42) [inline pkg/util/mount/mount.go]: Add a comment that in particular this is can detect bind mounts of directories.

File: pkg/util/mount/mount.go [hunk 3]
```diff
@@ -199,3 +199,32 @@ func getDeviceNameFromMount(mounter Interface, mountPath, pluginDir string) (str
...
+	if notMnt == false {
+		return notMnt, nil
+	}
+	// check all mountpoints since IsLikelyNotMountPoint
+	// is not reliable for some mountpoint types
+	mountPoints, mountPointsErr := mounter.List()
+	if mountPointsErr != nil {
+		return notMnt, mountPointsErr
+	}
+	deletedFile := fmt.Sprintf("%s\\040(deleted)", file)
```
Comment (msau42) [inline pkg/util/mount/mount.go]: This parsing is implementation specific. It should be done in the the mounter implementation instead.

File: pkg/volume/local/local.go [hunk 4]
```diff
@@ -269,5 +269,5 @@ func (u *localVolumeUnmounter) TearDown() error {
 // TearDownAt unmounts the bind mount
 func (u *localVolumeUnmounter) TearDownAt(dir string) error {
 	glog.V(4).Infof("Unmounting volume %q at path %q\n", u.volName, dir)
-	return util.UnmountPath(dir, u.mounter)
+	return util.UnmountMountPoint(dir, u.mounter, true) /* extensiveMountPointCheck = true */
```
Comment (msau42) [inline pkg/volume/local/local.go]: During mount we also call IsLikelyNotMountPoint.  Need to also evaluate if that call needs to be updated too.

Comment (ianchakeres) [inline pkg/volume/local/local.go]: I modified all references of IsLikelyNotMountPoint to use IsNotMountPoint inside local.go.

File: pkg/volume/util/util.go [hunk 5]
```diff
@@ -75,23 +75,41 @@ func SetReady(dir string) {
 // UnmountPath is a common unmount routine that unmounts the given path and
 // deletes the remaining directory if successful.
 func UnmountPath(mountPath string, mounter mount.Interface) error {
+	return UnmountMountPoint(mountPath, mounter, false) /* extensiveMountPointCheck = false */
+}
+
+// UnmountMountPoint is a common unmount routine that unmounts the given path and
+// deletes the remaining directory if successful.
+// if extensiveMountPointCheck is true
```
Comment (saad-ali) [inline pkg/volume/util/util.go]: Also please add comment about perf implications about enabling this option.

File: pkg/volume/util/util.go [hunk 6]
```diff
@@ -75,23 +75,41 @@ func SetReady(dir string) {
 // UnmountPath is a common unmount routine that unmounts the given path and
 // deletes the remaining directory if successful.
 func UnmountPath(mountPath string, mounter mount.Interface) error {
+	return UnmountMountPoint(mountPath, mounter, false) /* extensiveMountPointCheck = false */
```
Comment (saad-ali) [inline pkg/volume/util/util.go]: Super nit: 

I prefer 
```GO
UnmountMountPoint(mountPath, mounter, false /* extensiveMountPointCheck */)
```
since it's less verbose and doesn't require you to update the value and comment if you change the value.

**Comment by saad-ali** [comment]
Pagin @pmorie since he's familiar with this some of the mounter code (`nsenter_mount` in particular).

**Comment by ianchakeres** [comment]
@saad-ali - I've updated the comments. Let me know if you have any suggestions on how to further improve them.

**Comment by wojtek-t** [comment]
What is the status of this PR?
If you want this PR to be cherrypicked to 1.7 branch, I would like to see this PR first merged. Also, please add more descriptive release note (explain what exact bug this is fixing). @saad-ali - FYI

**Comment by saad-ali** [comment]
>  Also, please add more descriptive release note (explain what exact bug this is fixing).

Updated release note on behalf of @ianchakeres with link to bug being fixed.

**Comment by wojtek-t** [comment]
@saad-ali - thanks! Will create a cherrypick PR once this one is merged (but I don't have any more concerns).

**Comment by ianchakeres** [comment]
@saad-ali - I'm hoping that https://github.com/kubernetes/kubernetes/pull/48403 will fix pull-kubernetes-e2e-kops-aws errors we're seeing.

**Comment by ianchakeres** [comment]
This PR https://github.com/kubernetes/kubernetes/pull/48762 should help with docker timeout in e2e-kops-aws.

**Comment by ianchakeres** [comment]
@saad-ali @msau42 - I just squashed the commits.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/48809 constains a cherrypick of it
