### PR TITLE
Force NodeUnstageVolume to finish for all distros

### LINKED ISSUE #101279: Data caching issue for snapshot tests
#### What happened:
The volume snapshot controller tests can result in an empty VolumeSnapshot being taken if NodeUnstageVolume occurs after the VolumeSnapshot is taken. Previously there was a change made in Windows to ensure that NodeUnstageVolume finishes before continuing with the test; however, this needs to also to be included in other distros as well. NodeUnpublish, which removes the bind mount, does not force the caches to flush.

Tests - https://github.com/kubernetes/kubernetes/blob/92aff21558831b829fbc8cbca3d52edc80c01aa3/test/e2e/storage/testsuites/snapshottable.go#L243

#### What you expected to happen:
The CI jobs should pass when running with a non-hostpath driver.

#### How to reproduce it (as minimally and precisely as possible):
I'm uncertain on why we've seen an increase in these failures, but running the following tests with a non-hostpath driver appear to flake regularly:
* [Testpattern: Pre-provisioned Snapshot (retain policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion
* [Testpattern: Pre-provisioned Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion
* [Testpattern: Dynamic Snapshot (retain policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion
* [Testpattern: Dynamic Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource] volume snapshot controller should check snapshot fields, check restore correctly works after modifying source data, check deletion 

In these tests we've seen the following with the AWS EBS CSI Driver.
Driver logs on the node:
```
I0419 14:32:54.508906       1 node.go:393] NodeUnpublishVolume: called with args {VolumeId:vol-006a875808eaf3905 TargetPath:/var/lib/kubelet/pods/0b4cca95-3fea-4bac-889e-9d1d65afb5f3/volumes/kubernetes.io~csi/pvc-3f6e57e7-0c3b-44d9-b07b-425536cd307b/mount XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0419 14:32:54.620054       1 node.go:222] NodeUnstageVolume: called with args {VolumeId:vol-006a875808eaf3905 StagingTargetPath:/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-3f6e57e7-0c3b-44d9-b07b-425536cd307b/globalmount XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
```

In the driver logs (in the controller pod) I can see:
```
I0419 14:32:54.326754       1 controller.go:471] CreateSnapshot: called with args source_volume_id:"vol-006a875808eaf3905" name:"snapshot-47e60f81-a81b-44f7-a9c8-fdb2b0a10894" 
I0419 14:32:54.750763       1 controller.go:471] CreateSnapshot: called with args source_volume_id:"vol-006a875808eaf3905" name:"snapshot-47e60f81-a81b-44f7-a9c8-fdb2b0a10894" 
I0419 14:32:54.826142       1 controller.go:490] Snapshot snapshot-47e60f81-a81b-44f7-a9c8-fdb2b0a10894 of volume vol-006a875808eaf3905 already exists; nothing to do
```

### PR DESCRIPTION
**Pull request by huffmanca**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Forces NodeUnstageVolume to complete before we create a VolumeSnapshot for all distros in the e2e snapshot tests. It's currently possible for the CreateSnapshot to complete before the NodeUnstageVolume call, which can result in empty VolumeSnapshots being created, resulting in the test failing

#### Which issue(s) this PR fixes:
Fixes #101279

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

File: test/e2e/storage/testsuites/snapshottable.go [hunk 1]
```diff
@@ -179,25 +179,27 @@ func (s *snapshottableTestSuite) DefineTests(driver storageframework.TestDriver,
...
-					volumesInUse := node.Status.VolumesInUse
-					framework.Logf("current volumes in use: %+v", volumesInUse)
-					for i := 0; i < len(volumesInUse); i++ {
-						if strings.HasSuffix(string(volumesInUse[i]), pv.Name) {
-							return false
-						}
+			//
+			// We need to force this for non-Windows distros as well, as NodeUnpublishVolume only removes
+			// the bind mount, which doesn't force the caches to flush. It's possible to create empty
+			// snapshots if we don't wait (see #101279 for details).
```
Comment (jsafrane) [inline test/e2e/storage/testsuites/snapshottable.go:185]: Can you please incorporate this comment into the comment above?

```
			//   - NodeUnpublishVolume: unbinds the bind mount from the container
			//     - Linux: the bind mount is removed, which does not flush any cache
...
			//   - NodeUnstageVolume: unmount the global mount
			//     - Linux: disk is unmounted and all caches flushed.
```

Comment (huffmanca) [reply test/e2e/storage/testsuites/snapshottable.go:185]: These changes have been made.

**Comment by jsafrane** [comment]
cc @msau42 @jingxu97 @mattcary, since you were involved in https://github.com/kubernetes/kubernetes/pull/100057
We need to wait for `NodeUnstage` also on Linux.

**Comment by jsafrane** [comment]
forgot to cc @mauriciopoppe - please see the previous comment.

File: test/e2e/storage/testsuites/snapshottable.go [hunk 2]
```diff
@@ -179,25 +179,27 @@ func (s *snapshottableTestSuite) DefineTests(driver storageframework.TestDriver,
...
+			nodeName := pod.Spec.NodeName
+			gomega.Expect(nodeName).NotTo(gomega.BeEmpty(), "pod.Spec.NodeName must not be empty")
+
+			ginkgo.By(fmt.Sprintf("[init] waiting until the node=%s is not using the volume=%s", nodeName, pv.Name))
```
Comment (msau42) [inline test/e2e/storage/testsuites/snapshottable.go:189]: I think we should have 2 tests cases: One that takes a a snapshot online while it's still mounted, and one that takes a snapshot offline. 

I was hesitant when this workaround was initially added to Windows because I think the online snapshot case is the more common one, and the solution there is to have the application flush their data before taking a snapshot.

**Comment by msau42** [comment]
cc @xing-yang

File: test/e2e/storage/testsuites/snapshottable.go (hunk 2 above)
Comment (jsafrane) [reply test/e2e/storage/testsuites/snapshottable.go:189]: but our "application" (`/bin/echo`) does not flush anything. With `/bin/sync` it works pretty well.

Comment (mattcary) [reply test/e2e/storage/testsuites/snapshottable.go:189]: Yah adding a sync to the tester pod so that we still have a test case for online snapshots makes sense to me. Then add another test for the offline snapshot. Doing a sync after the echo probably is a good idea in both cases to reduce flakiness.

Comment (msau42) [reply test/e2e/storage/testsuites/snapshottable.go:189]: For the offline case, if we want to specifically verify that volume plugins are correctly flushing when unstaging, then it's better to not do the flush to mask plugin bugs.

But anyway, it seems like we've already turned these tests into the "offline" scenario for windows, so we can continue to do the same for linux, but we should find someone that has time to add the online scenario this release because I feel like the online scenario is the more common one.

Comment (mauriciopoppe) [reply test/e2e/storage/testsuites/snapshottable.go:189]: `sync` wasn't available in windows when I was working on https://github.com/kubernetes/kubernetes/pull/100377, FYI I opened https://github.com/kubernetes/kubernetes/issues/101172

Comment (huffmanca) [reply test/e2e/storage/testsuites/snapshottable.go:189]: Feel free to correct me, but in an attempt to summarize the conversation and action items here:

1. We need to have two different test sets. With this PR (and https://github.com/kubernetes/kubernetes/pull/100057 ) the current tests have been converted to an "offline" scenario, where the container is no longer running at the time the snapshot is taken. This forces the volume to be unmounted and unpublished, which also results in a cache flush and disk write. If we assume this path forward (2 sets of tests), then we need to ensure all distros complete a NodeUnstageVolume call, and this PR is appropriate?
2. We need to create a series of online tests, where the container continues to run when we take the VolumeSnapshot. In this scenario we'll need to execute a `sync` to ensure that the cache is flushed and the data is persisted in the snapshot.

Is this understanding correct?

Comment (msau42) [reply test/e2e/storage/testsuites/snapshottable.go:189]: Yup!

Comment (jsafrane) [reply test/e2e/storage/testsuites/snapshottable.go:189]: So.. is this PR OK then?

File: test/e2e/storage/testsuites/snapshottable.go [hunk 3]
```diff
@@ -167,10 +167,10 @@ func (s *snapshottableTestSuite) DefineTests(driver storageframework.TestDriver,
 			// lifecycle in windows, to understand it we first analyze what the volumemanager does:
```
Comment (msau42) [inline test/e2e/storage/testsuites/snapshottable.go:167]: This comment also needs to be updated, as it's not just a windows problem

File: test/e2e/storage/testsuites/snapshottable.go (hunk 2 above)
Comment (msau42) [reply test/e2e/storage/testsuites/snapshottable.go:189]: Opened up https://github.com/kubernetes/kubernetes/issues/101333 to track adding online shapshot tests

File: test/e2e/storage/testsuites/snapshottable.go (hunk 3 above)
Comment (huffmanca) [reply test/e2e/storage/testsuites/snapshottable.go]: I updated the comment to read a bit better for all distros.

File: test/e2e/storage/testsuites/snapshottable.go (hunk 2 above)
Comment (jingxu97) [reply test/e2e/storage/testsuites/snapshottable.go:187]: I think the original test is considered more like offline test. The pod was deleted first and then snapshot is taken. The subtle thing here is that even when pod is deleted from api server, there might be a chance that volume is not finished unstaging yet.
