### PR TITLE
tests: Adds retry to netexec connectivity check

### LINKED ISSUE #76825: tests: nettest should retry Kubernetes API connection
**Which jobs are failing**:

N/A

**Which test(s) are failing**:

    [k8s.io] [sig-node] PreStop should call prestop when killing a pod [Conformance]

**Since when has it been failing**:

N/A

**Testgrid link**:

N/A

**Reason for failure**:

When spawning a Pod, it's container might start before all its networking plumbing has been completed. Thus, if the container tests / needs its network connectivity, it mgiht fail.

The ``nettest`` binary from the ``nettest`` image tries to connect to the Kubernetes API, but if it cannot, the Pod will end up in an Error state.

Retrying the Kubernetes API connection will avoid this issue. 

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind flake

/sig testing

**What this PR does / why we need it**:

The container might start before all the networking plumbing has
been sucessfully completed, causing the Kubernetes reachability
check to fail.

This commit adds a few retries to the connectivity check.

**Which issue(s) this PR fixes**:

Fixes #76825

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: test/images/nettest/nettest.go [hunk 1]
```diff
@@ -241,11 +241,21 @@ func contactOthers(state *State) {
...
+			log.Fatalf("Unable to get server version: %v\n", err)
+		} else {
+			log.Printf("Server version: %#v\n", v)
+			break
+		}
+		time.Sleep(1 * time.Second)
+	}
+
+	if err != nil {
+		log.Fatalf("Unable to contact Kubernetes: %v\n", err)
```
Comment (listx) [inline test/images/nettest/nettest.go]: Will this line ever execute? You already call `log.Fatalf(...)` above.

File: test/images/nettest/nettest.go [hunk 2]
```diff
@@ -241,11 +241,21 @@ func contactOthers(state *State) {
...
 		log.Fatalf("Unable to create client; error: %v\n", err)
 	}
-	// Double check that worked by getting the server version.
-	if v, err := client.Discovery().ServerVersion(); err != nil {
-		log.Fatalf("Unable to get server version: %v\n", err)
-	} else {
-		log.Printf("Server version: %#v\n", v)
+
+	// the pod might not have network connectivity on the first try.
+	for i := 0; i < 15; i++ {
```
Comment (listx) [inline test/images/nettest/nettest.go]: Why not use the idiom from line 261

```
for start := time.Now(); time.Since(start) < timeout; time.Sleep(sleepTime)
```
?

File: test/images/nettest/nettest.go [hunk 3]
```diff
@@ -241,11 +241,21 @@ func contactOthers(state *State) {
 	if err != nil {
 		log.Fatalf("Unable to create client; error: %v\n", err)
 	}
-	// Double check that worked by getting the server version.
-	if v, err := client.Discovery().ServerVersion(); err != nil {
-		log.Fatalf("Unable to get server version: %v\n", err)
-	} else {
-		log.Printf("Server version: %#v\n", v)
+
+	// the pod might not have network connectivity on the first try.
```
Comment (listx) [inline test/images/nettest/nettest.go]: This comment doesn't actually mean anything?

Better wording might be: `Try to get the server version until <timeout>; we use a timeout because the pod might not have immediate network connectivity.` or something along those lines.

Comment (bclau) [reply test/images/nettest/nettest.go]: Done

File: test/images/nettest/nettest.go (hunk 2 above)
Comment (bclau) [reply test/images/nettest/nettest.go]: Done

File: test/images/nettest/nettest.go (hunk 1 above)
Comment (bclau) [reply test/images/nettest/nettest.go]: good point. above should have been Printf.

File: test/images/nettest/nettest.go [hunk 4]
```diff
@@ -241,11 +241,22 @@ func contactOthers(state *State) {
...
+		if v, err := client.Discovery().ServerVersion(); err != nil {
+			log.Printf("Unable to get server version: %v\n", err)
+		} else {
+			log.Printf("Server version: %#v\n", v)
+			break
+		}
+		time.Sleep(1 * time.Second)
+	}
+
+	if err != nil {
```
Comment (listx) [inline test/images/nettest/nettest.go]: The `err` here does not reference the same `err` from inside the `for` loop, right? Sorta like in here https://play.golang.org/p/HpKlN7sGgl6

Comment (bclau) [reply test/images/nettest/nettest.go]: That's a good point. Fixed.

File: test/images/nettest/nettest.go [hunk 5]
```diff
@@ -241,11 +246,22 @@ func contactOthers(state *State) {
...
-		log.Fatalf("Unable to get server version: %v\n", err)
-	} else {
-		log.Printf("Server version: %#v\n", v)
+
+	// Try to get the server version until <timeout>; we use a timeout because
+	// the pod might not have immediate network connectivity.
+	for start := time.Now(); time.Since(start) < timeout; time.Sleep(sleepTime) {
+		// Double check that worked by getting the server version.
+		if versionInfo, err = client.Discovery().ServerVersion(); err != nil {
+			log.Printf("Unable to get server version: %v\n", err)
```
Comment (listx) [inline test/images/nettest/nettest.go]: Nit: I think it would help to append "; retrying" to the message here so that in the case that both branches execute after 1 or 2 retries, we don't get conflicting messages in the logs.

Comment (bclau) [reply test/images/nettest/nettest.go]: Done
