### PR TITLE
fix pv-controller sync check node affinity for scheduled claim

### LINKED ISSUE #75652: pv-controller:miss check node affinity when selected-node set
**What happened**:
pvc bound to a volume not match the node affinity

**What you expected to happen**:
check node affinity if selected-node set

**How to reproduce it (as minimally and precisely as possible)**:
with a existed persistent volume with affinity to Node-A;
pod require a persistent volume claim(with provisioner, wait for first consumer mode) sheduled to node-B;
then persistent volume claim got annotation `selected-node` marked as node-B;
then pv controller will bound this pvc to the pv mentioned before.

**Anything else we need to know?**:
my cluster version is 1.12.1, but the master code has the same logical.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yittg**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
when pvc annotated with selected-node, controller will ignore it
checking node affinity

**Which issue(s) this PR fixes**:

Fixes #75652

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/volume/persistentvolume/pv_controller.go [hunk 1]
```diff
@@ -314,8 +314,18 @@ func (ctrl *PersistentVolumeController) syncUnboundClaim(claim *v1.PersistentVol
...
+			if err != nil {
+				strerr := fmt.Sprintf("Failed to get selected node: %v", err)
+				klog.V(3).Infof("unexpected error getting selected node %q for claim %q: %v", selectedNode, claimToClaimKey(claim), err)
+				ctrl.eventRecorder.Event(claim, v1.EventTypeWarning, events.FailedBinding, strerr)
+				return err
+			}
+		}
 		// [Unit test set 1]
-		volume, err := ctrl.volumes.findBestMatchForClaim(claim, delayBinding)
+		volume, err := ctrl.volumes.findBestMatchForClaim(claim, node, delayBinding)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/pv_controller.go]: Thank you for the PR!

If selectedNode is set, then that means we want dynamic provisioning.  So in all cases, I think we should return `volume = nil` from this call.  I think it would be cleaner if we added the annotation check inside `findBestMatchForClaim` instead of here. cc @cofyc

Comment (msau42) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: Hm actually the issue is a little trickier than I thought. Reading your original issue, I guess the problem is if PV doesn't exist by the time PV controller checks, then we will set selected-node annotation.  But if your volume plugin doesn't actually support provisioning, then it's going to get stuck waiting for dynamic provisioning forever with the change I suggested.

I need to think more about this case, but I think setting "kubernetes.io/no-provisioner" in the StorageClass should prevent this.

Comment (yittg) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: Thanks for your reply!

For the first part, do you mean that we should never choose a pv for those pvcs we want dynamic provisioning, and left it to the dynamic provision controller to set the provisioned volume name to the claim?
then, the second part is also fit, i think.

Comment (msau42) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: The sequence of volume binding for a PVC is:
1. First check if any existing PVs exist that can match the PVC.
2. If no PVs match, then try dynamic provisioning.

So first question I have is do you have a dynamic provisioner?

If no, then you should set `provisioner: kubernetes.io/no-provisioner` so that we don't try dynamic provisioning and get stuck there forever.

If yes, then you have the limitation that:
* the PV should be created first or
* you prebind the PVC to the PV or
* use a different storageclass with no-provisioner set.

Either way, I think there is a bug where if selected-node is already set on a PVC, the scheduler should not try to find an existing PV and bind it.

Comment (yittg) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: yeah, let us limit the problem to the scope that dynamic provisioner is present and no PV found when scheduling, so  
> selected-node is already set on a PVC

then another approach may be cleaner:
pv_controller should do no try to find a PV to bind when sync for these kind of PVCs, and the provisioner is **required** to pre-bind the PV created next for the PVC (as the csi-provisioner do).
I'll push another commit if you think so, :)

though CSI provide the normal provisioner for external, 
may this approach has potential compatibility issue that older dynamic provisioner is not strictly **required** to do that?

Comment (msau42) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: Yes, I think the pv controller should not try to find a PV to bind to if selected-node is set.

I'm unsure about requiring the provisioner to prebind PVs that were created outside of provisioner.  In this case, it sounds like for this particular PVC, you do not want dynamic provisioning and you want a specific PV. In this case, I think you should set PVC.volumeName when you create the PVC.

Comment (yittg) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: great, please help to check the new commit.

**Comment by yittg** [comment]
@msau42 would you approve it, or something else need? 😄

**Comment by yittg** [comment]
@msau42 not quit sure about the hesitate. but i did a more think about your comments

> then it's going to get stuck waiting for dynamic provisioning forever with the change I suggested.

would it help to new a warning event to prompt user with message like following ?

> dynamic configuration PVs(#N) satisfied cannot be bound for no pre-bound target PVC.

File: pkg/controller/volume/persistentvolume/util/util.go [hunk 2]
```diff
@@ -238,7 +248,7 @@ func FindMatchingVolume(
 			return volume, nil
 		}
 
-		if node == nil && delayBinding {
+		if node == nil && (delayBinding || IsDelayBindingProvisioning(claim)) {
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/util/util.go]: I'm curious about this issue. If the PVC has `AnnSelectedNode` set by the scheduler, it must be in delay binding mode, otherwise, it will not be handled by the scheduler. I don't think this is necessary to add this check. Did I miss something?

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: @cofyc the `delayBinding` param in this place is computed as storageclass is `WaitForFirstConsumer` **AND** NOT `selected-node` annotated, see the logic before in pv_controller.go:`shouldDelayBinding`

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: after being scheduled, PVC with delay binding mode will be annotated with `AnnSelectedNode`, then it is treated as non-delayBinding should be dynamic provisioned ASAP

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: @msau42 's opinion is that pv_controller should NOT find a PV for those PVCs `IsDelayBindingProvisioning` besides waiting for the dynamic provisioner. and i agree with this.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: Thanks for the clarification! IIUC, when PVC has `AnnSelectedNode` set, it must be dynamically provisioned in the PV controller, so the `ctrl.shouldDelayBinding(claim)` returns `false`. However, `util.FindMatchingVolume` will search all PVs under this storage class. If there is a static PV created and dynamic provisioner didn't complete the creation of the volume, the PVC may be bound to a wrong PV. So you add this check to skip the rest code.

This LGTM, add some comments to clarify it?

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: yeah, i do mean that.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: I have a idea to fix this issue in `syncUnboundClaim`.

- `ctrl.shouldDelayBinding(claim)` returns true always, if the volume binding of clas `WaitForFirstConsumer`
   - `FindMatchingVolume` will be passed `delayBinding=true` when the PVC has `AnnSelectedNode` set
   - I guess this function can be replaced by `pvutil.IsDelayBindingMode(claim, ctrl.classLister)` with this change
- fix `syncUnboundClaim` to dynamically provision the PVC when the PVC has `AnnSelectedNode` set

This will make the code clearer. What do you think? @yittg @msau42

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: For a quick review, like this?
func (ctrl *PersistentVolumeController) shouldDelayBinding(claim *v1.PersistentVolumeClaim) (bool, error) {
	// If claim is in delay binding mode.
	return pvutil.IsDelayBindingMode(claim, ctrl.classLister)
}

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: For a quick review like this?
```
func (ctrl *PersistentVolumeController) shouldDelayBinding(claim *v1.PersistentVolumeClaim) (bool, error) {
	return pvutil.IsDelayBindingMode(claim, ctrl.classLister)
}
...
                  switch {
			case delayBinding && !IsDelayBindingProvisioning(claim):
				ctrl.eventRecorder.Event(claim, v1.EventTypeNormal, events.WaitForFirstConsumer, "waiting for first consumer to be created before binding")
			case v1helper.GetPersistentVolumeClaimClass(claim) != "":
				if err = ctrl.provisionClaim(claim); err != nil {
					return err
				}
				return nil
```

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: yes

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: but it do change the meaning of `delayBinding` which is passed through many functions,
and also some test_cases around it. so let's wait for @msau42 's suggestions? :)

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: i looked into the history about function `shouldDelayBinding`, found that looks like this issue is introduced when adding the `AnnSelectedNode` check. this may be the right way to fix it :)

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: sure

Comment (msau42) [reply pkg/controller/volume/persistentvolume/util/util.go]: I like the idea to skip `FindMatchingVolumes` if `AnnSelectedNode` is not set.  I'm not sure about completely skipping `FindMatchingVolume` for `WaitForFirstConsumer`; that will break static binding.

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: @msau42 not completely i think, static binding can be applied when scheduling. Or do you mean the scenario that user create `WaitForFirstConsumer`  PVC without creating a pod consuming it.

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: `FindMatchingVolumes` does two things:

- a) it searches pre-bound PV for the claim first, return when a PV is found
- b) when the node is given (in scheduler code path) or delayBinding is false (in PV controller code path when the class is not `WaitForFirstConsumer`), it searches a matching PV from all static PVs under given class.

In the current master, when `AnnSelectedNode` is set, `delayBinding` is set to true even if the class is `WaitForFirstConsumer`, this is not intended because it will search static PVs. What we need to do is to skip b). I suggest returning `delayBinding` as `true` always when the class is `WaitForFirstConsumer` and fix the issue in `syncUnboundClaim`.

The new workflow will be like this:

- PVC (no AnnSelectedNode and no WaitForFirstConsumer)
  - search pre-bound PV or a matching PV (FindMatchingVolumes)
  - if not found, it will try dynamic provisioning (`delayBinding && !IsDelayBindingProvisioning(claim)` == `false`)
- PVC (AnnSelectedNode and no WaitForFirstConsumer)
  - not possible because `AnnSelectedNode` is set by the scheduler
  - If it is set by the user, it works the same as the PVC without `AnnSelectedNode`. I think it's correct. (`delayBinding && !IsDelayBindingProvisioning(claim)` == `false`)
- PVC (no AnnSelectedNode and WaitForFirstConsumer)
  - search pre-bound PV (FindMatchingVolumes, no matching PV will be searched because delayBinding is true)
  - if not found, wait for the scheduler because the delayBinding is true and no  AnnSelectedNode set (`delayBinding && !IsDelayBindingProvisioning(claim)` == `true`)
- PVC (AnnSelectedNode and WaitForFirstConsumer)
  - search pre-bound PV (FindMatchingVolumes, no matching PV will be searched because delayBinding is true)
  - if not found, it will try dynamic provisioning (`delayBinding && !IsDelayBindingProvisioning(claim)` == `false`)

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: @cofyc great clarity, maybe a little typo: it should be `false` here:
> In the current master, when `AnnSelectedNode` is set, `delayBinding` is set to **true** even if the class is `WaitForFirstConsumer`

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: Fixed. Thanks!

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/util/util.go]: @yittg can you update to what I suggested? we can see if it breaks anything

Comment (yittg) [reply pkg/controller/volume/persistentvolume/util/util.go]: Ok, it's on the way

**Comment by yittg** [comment]
@cofyc superficially, it seems that everything is on the right track.

File: pkg/controller/volume/persistentvolume/provision_test.go [hunk 3]
```diff
@@ -102,6 +128,14 @@ var storageClasses = []*storage.StorageClass{
...
 	},
 }
+var nodes = []*v1.Node{
+	{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:   "node1",
+			Labels: map[string]string{"key1": "value1"},
+		},
+	},
+}
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/provision_test.go]: it's only be used in one place, make it local in the function where it is used.

**Comment by cofyc** [comment]
one minor nit, the rest LGTM

File: pkg/controller/volume/persistentvolume/provision_test.go (hunk 3 above)
Comment (yittg) [reply pkg/controller/volume/persistentvolume/provision_test.go]: fixed

**Comment by cofyc** [comment]
LGTM
cc @msau42 for final review

**Comment by msau42** [comment]
/lgtm
/approve
/priority important-soon
Thanks!

**Comment by yittg** [comment]
@msau42 @cofyc, thanks.

**Comment by tamalsaha** [comment]
@msau42 , should this be cherry picked to older releases?
