### PR TITLE
service-ip-alloc: delay ip processing on service recreate

### LINKED ISSUE #132321: IPAddressWrongReference when creating an existing service
### What happened?

POST an existing service. A new ip address will be created and then cleaned up.

```
2m39s   Warning   IPAddressWrongReference   ipaddress/10.96.77.125    IPAddress: 10.96.77.125 for Service default/kubernetes has a wrong reference; cleaning up
```

### What did you expect to happen?

No new ip address being created.

### How can we reproduce it (as minimally and precisely as possible)?

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
EOF
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aroradaman**
Service storage implements transactions. It creates an IPAddress object first and then creates the Service object, and if the Service object already exists the complete transaction is reverted. There can be race conditions when the repair loop picks up the new IPAddress object for reconciliation before the transaction is reverted. This leads to spurious IPAddressWrongReference warnings, to suppress these warnings we delay the processing of the new IPAddress object by 5 seconds. The service allocation creates the IPAddress object before creating the Service object, we easily identify this scenario when Service object is created before the IPAddress object.

#### What type of PR is this?
/kind cleanup
/kind bug

#### What this PR does / why we need it:
This PR suppresses the spurious IPAddressWrongReference warning events when existing service is created again.

#### Which issue(s) this PR is related to:
Fixes #132321

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/registry/core/service/ipallocator/controller/repairip.go [hunk 1]
```diff
@@ -520,6 +520,19 @@ func (r *RepairIPAddress) syncIPAddress(key string) error {
...
 	}
+	// Service storage implements transactions. It creates an IPAddress object first and then creates
+	// the Service object, and if the Service object already exists the complete transaction is
+	// reverted. There can be race conditions when the repair loop picks up the new IPAddress object
+	// for reconciliation before the transaction is reverted. This leads to spurious
+	// IPAddressWrongReference warnings, to suppress these warnings we delay the processing of the new
+	// IPAddress object by 5 seconds. The service allocation creates the IPAddress object before creating
+	// the Service object, we easily identify this scenario when Service object is created before the
+	// IPAddress object.
+	if svc.CreationTimestamp.Time.Before(ipAddress.CreationTimestamp.Time) {
```
Comment (liggitt) [inline pkg/registry/core/service/ipallocator/controller/repairip.go]: Don't we only want this to trigger if ipaddress creation timestamp is recent (in the last five seconds) as well?

Comment (liggitt) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: /hold
To prevent accidental merge until ^ is answered

Comment (aroradaman) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: Isn't it safe to assume that transaction in process (which leads to this race) will be reverted? I can only see a requirement of the second check "ipaddress creation timestamp is recent (in the last five seconds)" when transaction which is supposed to be reverted is somehow not reverted.

Comment (aroradaman) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: Ah, in case of kube-apiserver crash the transaction will never be reverted and the repair loop will keep on delaying processing of the IPAddress object indefinitely. Will add that check.

Comment (aojea) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: puff, thanks Jordan,  @aroradaman check the https://github.com/kubernetes/kubernetes/issues/132321#issuecomment-3061763353

Comment (aojea) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]:
```
 +       if ipAddress.CreationTimestamp.Time.After(svc.CreationTimestamp.Time) &&
 +               ipAddress.CreationTimestamp.Time.Before(svc.CreationTimestamp.Time.Add(5*time.Second)) {
 +               // requeue after the grace period
 +               r.ipQueue.AddAfter(key, 5*time.Second)
 +               return nil
 +       }
```

Comment (aroradaman) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: I think the second check can be independent of when the service was created. Whenever create is called on existing service the new IPAddress will have time.Now() as creation timestamp and we can compare with the clock if it is recent (within 5 seconds.

We just want to handle the case when the transaction revert fails and we don't end up delaying the cleanup of the new IPAddress indefinitely. 

Does the following makes sense?
```go
ipAddress.CreationTimestamp.Time.After(svc.CreationTimestamp.Time) &&
r.clock.Now().Sub(ipAddress.CreationTimestamp.Time) < 5*time.Second
```

Comment (aojea) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: why do you want to make the check undeterministic?

using the object timestamps we have a reliable way to identify the behavior we are worried about

> We just want to handle the case when the transaction revert fails and we don't end up delaying the cleanup of the new IPAddress indefinitely.

we want to avoid the repair loop to race with the transaction, just that

Comment (aroradaman) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]:
```go
 ipAddress.CreationTimestamp.Time.Before(svc.CreationTimestamp.Time.Add(5*time.Second))
 ```

The creation timestamp of the Service will be the timestamp when the service was first created, the creation timestamp of the IPAddress will always be the current time (when the service is created again). 
The above condition will only be true if the IPAddress object is created within 5 seconds of service create (service might be 100 days old), right? We will only suppress the warnings / delay  when new IPAddress object is created with 5 seconds of creation of service.



https://github.com/kubernetes/kubernetes/blob/4eecdc4cc6aa0a35c664bfb7e2188bd2d1c680bb/pkg/registry/core/service/ipallocator/controller/repairip.go#L492

Comment (aojea) [reply pkg/registry/core/service/ipallocator/controller/repairip.go]: Oh, right, my bad, is not the service timestamp creation is the timestamp of the duplicate service.... I need to think more about this, we need to avoid we create a loop by constantly requeuing it, that's the goal of this second condition

**Comment by aojea** [comment]
/lgtm

Thanks Daman

/assign @liggitt 

for removing the hold

**Comment by liggitt** [comment]
looks good, thanks

/hold cancel

**Comment by adilGhaffarDev** [comment]
@liggitt @aojea can we backport it to 1.33?

**Comment by aojea** [comment]
This is a cosmetical change , there is no impact more than noisy events on the special case you are recreating a service that already exist ... does not looks it fits into the category of cherry picks https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

**Comment by xhejtman** [comment]
Hello,

In our case, the [Dragonfly operator](https://github.com/dragonflydb/dragonfly-operator) particularly triggers this bug, creating nearly 200 000 events for a few instances and doing so faster than we can delete them. Even after attempting to purge events older than one minute, roughly 25 000 events remain:

```
kubectl get events -n default | wc -l
23586
```

This imposes a significant load on both the cluster and the Kubernetes UI. I believe cherry pick should be reconsidered for inclusion in the 1.33 release line.

**Comment by aojea** [comment]
> creating nearly 200 000 events for a few instances and doing so faster than we can delete them

I think that impact on performance is a regression that didn't exist before so it qualifies for cherry pick

cc: @adilGhaffarDev 

@aroradaman @xhejtman do you mind to submit the cherry pick to 1.33 branch?

**Comment by xhejtman** [comment]
> > creating nearly 200 000 events for a few instances and doing so faster than we can delete them
> 
> I think that impact on performance is a regression that didn't exist before so it qualifies for cherry pick
> 
> cc: @adilGhaffarDev
> 
> @aroradaman @xhejtman do you mind to submit the cherry pick to 1.33 branch?

I’ll try to tackle this as soon as I have time—definitely this week—unless @aroradaman has already taken care of it.
