### PR TITLE
Do not schedule pods to a node without CSI driver

### LINKED ISSUE #126921: Deletion of csi-node-plugin Pod causes driver entry to be removed from CSINode object; kube-scheduler schedules more than driver's allocatable
### What happened?

With @plkokanov we hit in our environments the following issue multiple times:
```
% k -n shoot--foo--bar describe po etcd-main-0

Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Warning  FailedAttachVolume  35s (x47 over 80m)  attachdetach-controller  AttachVolume.Attach failed for volume "pv-shoot--shik--shak-1234" : rpc error: code = Internal desc = Attach volume /subscriptions/<omitted>/resourceGroups/shoot--shik--shak/providers/Microsoft.Compute/disks/pv-shoot--shik--shak-1234 to instance shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5 failed with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {\r
  "error": {\r
    "code": "OperationNotAllowed",\r
    "message": "The maximum number of data disks allowed to be attached to a VM of this size is 16.",\r
    "target": "dataDisks"\r
  }\r
}
```

When we checked, the CSINode object for the corresponding Node was reporting the correct volume attachment limit:
```
% k get csinode shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5 -o yaml

spec:
  drivers:
  # ...
  - allocatable:
      count: 16
    name: disk.csi.azure.com
    nodeID: shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5
    topologyKeys:
    - topology.disk.csi.azure.com/zone
    - topology.kubernetes.io/zone
```

According to the Node status and according to the VM state in Azure, it had already 16 disks attached.
```
% k get no shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5 -o json | jq '.status.volumesAttached | length'
16

% az vm show -g shoot--shik--shak --name shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5 | jq '.storageProfile.dataDisks | length'
16
```

kube-scheduler wrongly sheduled a Pod with a volume to the `shoot--shik--shak-cpu-worker-etcd-z1-6c956-mhcw5` Node as the Node already had its volume attachments limit reached.

We found that this happens due to csi-node-plugin Pod deletion. On deletion of this Pod, we see that the driver section from the CSINode object is removed and it is added only when the new csi-node-plugin Pod starts.

The corresponding handling in kube-scheduler's NodeVolumeLimits plugin is: https://github.com/kubernetes/kubernetes/blob/a7242fcff768658019f878cb691583dcbcfefb2d/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L197-L201

If we fail to fetch the limit from the CSINode object, kube-scheduler let's the Pod to be scheduled.

### What did you expect to happen?

kube-scheduler to do not schedule Pods with volumes to Nodes that already have their volume attachment limit reached.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce the removal of the driver section after csi-node-plugin Pod deletion:

1. Start watching the CSINode object:
```
 k get csinode "$NODENAME" -w -o yaml > "~/csinode-$NODENAME.yaml"
```

2. In a new terminal window delete the csi-node-plugin Pod

3. Make sure that the CSINode object watch is as follows:
```yaml
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  name: node-1
spec:
  drivers:
  - allocatable:
      count: 8
    name: disk.csi.azure.com
    nodeID: node-1
    topologyKeys:
    - topology.disk.csi.azure.com/zone
    - topology.kubernetes.io/zone
---
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  name: node-1
spec:
  drivers: null
---
apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  name: node-1
spec:
  drivers:
  - allocatable:
      count: 8
    name: disk.csi.azure.com
    nodeID: node-1
    topologyKeys:
    - topology.disk.csi.azure.com/zone
    - topology.kubernetes.io/zone
```

Note: The non-relevant fields are removed from the example output above.

You can see that until the new csi-node-plugin is scheduled and started, the CSINode object does not contain any information about the driver. We see that during that time kube-scheduler schedules new Pods with volumes to that Node.
The kube-scheduler plugin for respecting the Node volume limit is: https://github.com/kubernetes/kubernetes/blob/a7242fcff768658019f878cb691583dcbcfefb2d/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go

### Anything else we need to know?

We use VPA to scale the csi-node-plugin Pod. That's why it can be evicted and restarted.

### Kubernetes version

<details>

```console
$ kubectl version

Server Version: v1.29.4
```

</details>

### Cloud provider

<details>
Azure and AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Gardener
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
[azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver): v1.30.0
</details>

### PR DESCRIPTION
**Pull request by gnufied**
This makes changes into kube-scheduler so as it better integrates with CAS - xref https://github.com/kubernetes/enhancements/issues/5030

Link into corresponding changes in CAS - https://github.com/kubernetes/autoscaler/pull/8721 

As per same linked enhancement it also fixes long standing issues https://github.com/kubernetes/kubernetes/issues/95911 also fixes https://github.com/kubernetes/kubernetes/issues/126921

```release-note
Implement changes to prevent pod scheduling to a node without CSI driver
```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ import (
 	"k8s.io/klog/v2"
 	fwk "k8s.io/kube-scheduler/framework"
 	"k8s.io/kubernetes/pkg/scheduler/apis/config"
-	"k8s.io/kubernetes/pkg/scheduler/backend/api_dispatcher"
+	apidispatcher "k8s.io/kubernetes/pkg/scheduler/backend/api_dispatcher"
```
Comment (helayoty) [inline pkg/scheduler/framework/runtime/framework.go:40]: Please revert this change.

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -54,21 +54,22 @@ const (
...
+	preFilterPlugins  []fwk.PreFilterPlugin
+	filterPlugins     []fwk.FilterPlugin
+	postFilterPlugins []fwk.PostFilterPlugin
+	preScorePlugins   []fwk.PreScorePlugin
+	scorePlugins      []fwk.ScorePlugin
+	reservePlugins    []fwk.ReservePlugin
+	preBindPlugins    []fwk.PreBindPlugin
+	bindPlugins       []fwk.BindPlugin
+	postBindPlugins   []fwk.PostBindPlugin
+	permitPlugins     []fwk.PermitPlugin
```
Comment (helayoty) [inline pkg/scheduler/framework/runtime/framework.go]: Please revert this change.

File: staging/src/k8s.io/api/storage/v1/types.go [hunk 3]
```diff
@@ -469,6 +469,14 @@ type CSIDriverSpec struct {
 	// +featureGate=CSIServiceAccountTokenSecrets
 	// +optional
 	ServiceAccountTokenInSecrets *bool `json:"serviceAccountTokenInSecrets,omitempty" protobuf:"varint,10,opt,name=serviceAccountTokenInSecrets"`
+
+	// preventPodSchedulingIfMissing indicates that the CSI driver wants to prevent pod scheduling if the CSI driver
+	// on the node is missing.
+	// This is a alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
```
Comment (helayoty) [inline staging/src/k8s.io/api/storage/v1/types.go]: nit: 

```suggestion
	// This is an alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
```

File: pkg/apis/storage/types.go [hunk 4]
```diff
@@ -458,6 +458,14 @@ type CSIDriverSpec struct {
 	// +featureGate=CSIServiceAccountTokenSecrets
 	// +optional
 	ServiceAccountTokenInSecrets *bool
+
+	// PreventPodSchedulingIfMissing indicates that the CSI driver wants to prevent pod scheduling if the CSI driver
+	// on the node is missing.
+	// This is a alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
```
Comment (helayoty) [inline pkg/apis/storage/types.go]: same nit: 
```suggestion
	// This is an alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+
+import (
+	storagev1 "k8s.io/api/storage/v1"
+	"k8s.io/apimachinery/pkg/labels"
+	storagelisters "k8s.io/client-go/listers/storage/v1"
+	fwk "k8s.io/kube-scheduler/framework"
+)
+
+// CSIManagerImpl is a implementation of the CSIManager interface.
+type CSIManagerImpl struct {
```
Comment (helayoty) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: I'd prefer to follow other code naming pattern in the scheduler pkg and rename it to `SharedCSIManager` or `DefaultCSIManager`

File: pkg/scheduler/scheduler.go [hunk 6]
```diff
@@ -343,6 +344,9 @@ func New(ctx context.Context,
 		}
 		draManager = dynamicresources.NewDRAManager(ctx, resourceClaimCache, resourceSliceTracker, informerFactory)
 	}
+	var sharedCSIManager fwk.CSIManager
+	sharedCSIManager = nodevolumelimits.NewCSIManager(informerFactory.Storage().V1().CSINodes().Lister())
+
```
Comment (helayoty) [inline pkg/scheduler/scheduler.go]: This change should be gaurded with the feature gate.

File: pkg/scheduler/scheduler.go [hunk 7]
```diff
@@ -361,6 +365,7 @@ func New(ctx context.Context,
 		frameworkruntime.WithMetricsRecorder(metricsRecorder),
 		frameworkruntime.WithWaitingPods(waitingPods),
 		frameworkruntime.WithAPIDispatcher(apiDispatcher),
+		frameworkruntime.WithSharedCSIManager(sharedCSIManager),
```
Comment (helayoty) [inline pkg/scheduler/scheduler.go:367]: Same. This change should be gaurded with the feature gate.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 8]
```diff
@@ -261,7 +262,7 @@ func (pl *CSILimits) Filter(ctx context.Context, _ fwk.CycleState, pod *v1.Pod,
 
 	logger := klog.FromContext(ctx)
 
-	csiNode, err := pl.csiNodeLister.Get(node.Name)
+	csiNode, err := pl.csiManager.CSINodes().Get(node.Name)
```
Comment (helayoty) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:265]: This change should be gaurded with the feature gate.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 9]
```diff
@@ -338,6 +348,31 @@ func (pl *CSILimits) Filter(ctx context.Context, _ fwk.CycleState, pod *v1.Pod,
 	return nil
 }
 
+func (pl *CSILimits) checkCSIDriverOnNode(pluginName string, csiNode *storagev1.CSINode) bool {
+	// the registered driver must be a CSI driver to enforce this limit, if we can't find the driver,
+	// we assume the driver may not be a CSI driver and allow the pod to be scheduled.
+	csiDriver, err := pl.csiDriverLister.Get(pluginName)
+	if err != nil {
```
Comment (helayoty) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:359]: Should we diffrentiate between not CSI driver error and others?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 10]
```diff
@@ -550,18 +585,20 @@ func NewCSI(_ context.Context, _ runtime.Object, handle fwk.Handle, fts feature.
...
 	pvcLister := informerFactory.Core().V1().PersistentVolumeClaims().Lister()
-	csiNodesLister := informerFactory.Storage().V1().CSINodes().Lister()
 	scLister := informerFactory.Storage().V1().StorageClasses().Lister()
 	vaLister := informerFactory.Storage().V1().VolumeAttachments().Lister()
+	csiDriverLister := informerFactory.Storage().V1().CSIDrivers().Lister()
 	csiTranslator := csitrans.New()
 
 	return &CSILimits{
-		csiNodeLister:              csiNodesLister,
+		csiManager:                 handle.SharedCSIManager(),
```
Comment (helayoty) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:596]: What will happen if the feature gate is disabled? Will the `handle.SharedCSIManager()` be nil?

File: pkg/registry/storage/csidriver/strategy.go [hunk 11]
```diff
@@ -60,6 +60,9 @@ func (csiDriverStrategy) PrepareForCreate(ctx context.Context, obj runtime.Objec
 	if !utilfeature.DefaultFeatureGate.Enabled(features.CSIServiceAccountTokenSecrets) {
 		csiDriver.Spec.ServiceAccountTokenInSecrets = nil
 	}
+	if !utilfeature.DefaultFeatureGate.Enabled(features.VolumeLimitScaling) {
```
Comment (helayoty) [inline pkg/registry/storage/csidriver/strategy.go]: What if the user set the value while the feature gate is disabled?

**Review by helayoty — COMMENTED** [review]
Left few comments. No major feedback other than some checks for feature gates.

File: pkg/scheduler/scheduler.go (hunk 6 above)
Comment (gnufied) [reply pkg/scheduler/scheduler.go]: So, I have kept this without featuregate because this change makes no material difference in behavior of the scheduler and merely affects the way scheduler plugin initializes csinode lister. I would argue that, this change for example is no different from change which was recently made to refactor some of the scheduler interfaces - https://github.com/kubernetes/kubernetes/pull/133172 

Passing tests are also a good indication that, this change breaks no scheduler behaviour. 

But - there is another reason for keeping this change without featuregate, it allows me to decouple changes in CAS - https://github.com/kubernetes/autoscaler/pull/8721 . This change allows CAS to initialize scheduler plugins correctly without depending on activating `VolumeLimitScaling` featuregate in scheduler that is bundled in CAS.  It will allow us to fix the CAS behaviour regardless of timeframe when `VolumeLimitScaling` featuregate goes GA in kube-scheduler.

Without this change, we will end up with hard to untangle coupling between CAS and kube-scheduler, which I would rather avoid.

File: pkg/scheduler/scheduler.go (hunk 7 above)
Comment (gnufied) [reply pkg/scheduler/scheduler.go:367]: Same as above. This is a mere refactoring of existing code and requires no featuregate.

**Comment by ialidzhikov** [comment]
Hi @gnufied ,

Is this PR also supposed to fix https://github.com/kubernetes/kubernetes/issues/126921? If yes, can we update the PR description to reflect this so that when this PR is merged the corresponding issue gets closed?

**Comment by gnufied** [comment]
@ialidzhikov Yes, this PR should help with that issue too. But just to be clear, this change will be behind a featuregate and a CSI driver still has to opt-in by declaring `PreventPodSchedulingIfMissing` in `CSIDriver` spec to guide the scheduler from placing pods on nodes where CSI driver is not installed.

File: pkg/registry/storage/csidriver/strategy.go (hunk 11 above)
Comment (gnufied) [reply pkg/registry/storage/csidriver/strategy.go]: Then we will drop the field (or set it to `nil`) as we are doing here. We are already doing that here.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 10 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:596]: As implemented, since setting the sharedCSIManager is without a featuregate, it won't be nil if featuregate is disabled.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 8 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:265]: Same as above. I do not want to guard this change with a featuregate unless we must.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 9 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:359]: Good question. I am still debating this about with myself.

If for some reason, during scheduling if we can't look up a `CSIDriver` object, should we block scheduling of the pod or allow it? Previously we allowed it, so I was leaning towards keeping the old behaviour, since this feature requires an explicit opt-in via `PreventPodSchedulingIfMissing` field.

File: pkg/scheduler/framework/runtime/framework.go (hunk 1 above)
Comment (gnufied) [reply pkg/scheduler/framework/runtime/framework.go:40]: I didn't make this change manually. The golang tools "fixed" this import for me (via `go-lsp`). This import is very weird, because we do not actually use the import with underscore, but in the code we are actually using `apidispatcher` identifier. Do we really want this to be fixed? I thought `go-lsp` did correct thing here. The actual package in this case is indeed called `apidispatcher` and not `api_dispatcher` as indicated by the import statement.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 5 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: Fixed.

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (gnufied) [reply pkg/scheduler/framework/runtime/framework.go]: fixed.

File: staging/src/k8s.io/api/storage/v1/types.go [hunk 12]
```diff
@@ -469,6 +469,14 @@ type CSIDriverSpec struct {
 	// +featureGate=CSIServiceAccountTokenSecrets
 	// +optional
 	ServiceAccountTokenInSecrets *bool `json:"serviceAccountTokenInSecrets,omitempty" protobuf:"varint,10,opt,name=serviceAccountTokenInSecrets"`
+
+	// preventPodSchedulingIfMissing indicates that the CSI driver wants to prevent pod scheduling if the CSI driver
+	// on the node is missing.
```
Comment (torredil) [inline staging/src/k8s.io/api/storage/v1/types.go]: _if the CSI driver on the node is missing_  is unclear, suggest the following:

```
// PreventPodSchedulingIfMissing indicates that pods using this CSI driver should only be 
// scheduled to nodes where the driver is already installed (present in CSINode).
// When true, the scheduler will check if the driver exists in the node's CSINode 
// object before scheduling pods that use volumes from this driver.
// When false or unset, pods can be scheduled to any node regardless of driver presence.
...
```

also, thoughts on renaming `PreventPodSchedulingIfMissing` to `PreventPodSchedulingIfCSINodeMissing`  or `RequireDriverOnCSINode`?

File: staging/src/k8s.io/api/storage/v1/types.go [hunk 13]
```diff
@@ -469,6 +469,14 @@ type CSIDriverSpec struct {
...
+	// This is an alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
+	// Default is "false".
+	// +featureGate=VolumeLimitScaling
+	// +optional
+	PreventPodSchedulingIfMissing *bool `json:"preventPodSchedulingIfMissing,omitempty" protobuf:"varint,11,opt,name=preventPodSchedulingIfMissing"`
```
Comment (torredil) [inline staging/src/k8s.io/api/storage/v1/types.go]: _if the CSI driver on the node is missing_  is unclear, suggest the following:

```
// PreventPodSchedulingIfMissing indicates that pods using this CSI driver should only be 
// scheduled to nodes where the driver is already installed (present in CSINode).
// When true, the scheduler will check if the driver exists in the node's CSINode 
// object before scheduling pods that use volumes from this driver on that node.
// When false or unset, pods can be scheduled to any node regardless of driver presence.
//
// This is an alpha feature and requires the VolumeLimitScaling feature gate to be enabled.
// Default is "false".
// +featureGate=VolumeLimitScaling
// +optional
```

also, thoughts on renaming `PreventPodSchedulingIfMissing` to something like `PreventPodSchedulingIfCSINodeMissing`  or `RequireDriverOnCSINode`?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 14]
```diff
@@ -0,0 +1,57 @@
...
+package nodevolumelimits
+
+import (
+	storagev1 "k8s.io/api/storage/v1"
+	"k8s.io/apimachinery/pkg/labels"
+	storagelisters "k8s.io/client-go/listers/storage/v1"
+	fwk "k8s.io/kube-scheduler/framework"
+)
+
+// CSIManagerImpl is a implementation of the CSIManager interface.
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: nit:
```suggestion
// CSIManagerImpl is an implementation of the CSIManager interface.
```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 15]
```diff
@@ -0,0 +1,57 @@
...
+type DefaultCSIManager struct {
+	defaultCSINodeLister *csiNodeLister
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: Maybe without default (the struct is named default anyway)
```suggestion
	csiNodeLister *csiNodeLister
```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 16]
```diff
@@ -0,0 +1,57 @@
...
+}
+
+var _ fwk.CSIManager = &DefaultCSIManager{}
+
+func NewCSIManager(csinodeLister storagelisters.CSINodeLister) *DefaultCSIManager {
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: nit:
```suggestion
func NewCSIManager(csiNodeLister storagelisters.CSINodeLister) *DefaultCSIManager {
```

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 8 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:265]: We don't need a feature gate for this. The change is straightforward (just hides the lister behind the csiManager), which can be considered as refactoring. I don't see any risk with this line

File: pkg/scheduler/framework/runtime/framework.go (hunk 1 above)
Comment (macsko) [reply pkg/scheduler/framework/runtime/framework.go:40]: Let's keep this change

File: pkg/scheduler/framework/runtime/framework.go [hunk 17]
```diff
@@ -80,6 +80,9 @@ type frameworkImpl struct {
 	sharedDRAManager fwk.SharedDRAManager
 	logger           klog.Logger
 
+	// for tracking CSI node limits
```
Comment (macsko) [inline pkg/scheduler/framework/runtime/framework.go]: I'm not sure if this comment is really needed. It doesn't bring much value in its current form

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go [hunk 18]
```diff
@@ -1247,3 +1248,129 @@ func getNodeWithPodAndVolumeLimits(limitSource string, pods []*v1.Pod, limit int
...
+func getFakeCSIDriverListerWithPrevent(driverName string, prevent *bool) fakeCSIDriverLister {
+	return fakeCSIDriverLister{
+		storagev1.CSIDriver{
+			ObjectMeta: metav1.ObjectMeta{Name: driverName},
+			Spec: storagev1.CSIDriverSpec{
+				PreventPodSchedulingIfMissing: prevent,
+			},
+		},
+	}
+}
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go]: Isn't having a single func sufficient for now?

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 19]
```diff
@@ -0,0 +1,57 @@
...
+	return m.defaultCSINodeLister
+}
+
+type csiNodeLister struct {
+	csinodeLister storagelisters.CSINodeLister
+}
+
+var _ fwk.CSINodeLister = &csiNodeLister{}
+
+func NewCsiNodeLister(csinodeLister storagelisters.CSINodeLister) *csiNodeLister {
```
Comment (jsafrane) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: nit: `NewCSINodeLister`

File: test/e2e/storage/csimock/csi_volume_limit_scaling.go [hunk 20]
```diff
@@ -0,0 +1,136 @@
...
+		tests := []struct {
+			name              string
+			preventOptIn      *bool
+			featureTags       []interface{}
+			expectSchedulable bool
+		}{
+			{
+				name:              "prevent=true blocks scheduling when driver not installed",
+				preventOptIn:      ptr.To(true),
+				featureTags:       []interface{}{framework.WithFeatureGate(features.VolumeLimitScaling)},
```
Comment (jsafrane) [inline test/e2e/storage/csimock/csi_volume_limit_scaling.go]: Do you envision any tests not requiring VolumeLimitScaling feature gate? It seems quite useless now to have the FG configurable in the table.

File: test/e2e/storage/csimock/csi_volume_limit_scaling.go [hunk 21]
```diff
@@ -0,0 +1,136 @@
...
+				expectSchedulable: false,
+			},
+			{
+				name:              "prevent=false allows scheduling when driver not installed",
+				preventOptIn:      ptr.To(false),
+				featureTags:       []interface{}{framework.WithFeatureGate(features.VolumeLimitScaling)},
+				expectSchedulable: true,
+			},
```
Comment (jsafrane) [inline test/e2e/storage/csimock/csi_volume_limit_scaling.go:60]: There should be a test with missing CSIDriver.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 15 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: I wanted to avoid having field name with same name as struct name...

File: staging/src/k8s.io/api/storage/v1/types.go (hunk 13 above)
Comment (gnufied) [reply staging/src/k8s.io/api/storage/v1/types.go]: So after yesterday's CSI implementation meeting, I have decided to drop the change which requires `CSIDriver` field for stopping pod scheduling. Now, if corresponding CSI driver is registered in `CSIDriver` object, scheduler will stop pod scheduling if driver is not installed. This implementation is much simpler now and should not require explicit opt-in as such.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 14 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: fixed.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 16 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: fixed.

File: pkg/scheduler/framework/runtime/framework.go (hunk 17 above)
Comment (gnufied) [reply pkg/scheduler/framework/runtime/framework.go]: fixed.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 19 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: fixed.

File: test/e2e/storage/csimock/csi_volume_limit_scaling.go (hunk 20 above)
Comment (gnufied) [reply test/e2e/storage/csimock/csi_volume_limit_scaling.go]: Fixed.

File: test/e2e/storage/csimock/csi_volume_limit_scaling.go (hunk 21 above)
Comment (gnufied) [reply test/e2e/storage/csimock/csi_volume_limit_scaling.go:60]: There is a test for missing CSIDriver object now.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go (hunk 18 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_test.go]: This should be fixed now, since we got rid of `CSIDriver` field altogether.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 9 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:359]: I have fixed this now. We only allow pod scheduling now if `Get` call in the lister returns `NotFound` errors (meaning the driver is not CSI), for other errors we will prevent pod scheduling because that should never happen generally speaking.

File: test/e2e/storage/csimock/csi_volume_limit_scaling.go [hunk 22]
```diff
@@ -0,0 +1,149 @@
...
+						"reason":                   "FailedScheduling",
+					}.AsSelector().String()
+					err = e2eevents.WaitTimeoutForEvent(ctx, f.ClientSet, pod.Namespace, eventSelector, failedMsg, f.Timeouts.PodStart)
+					framework.ExpectNoError(err, "waiting for FailedScheduling due to missing CSI driver")
+				}
+			}
+
+			// Compose It with feature tags
+			args := []interface{}{tc.name, testFunc}
+			framework.It(args...)
```
Comment (jsafrane) [inline test/e2e/storage/csimock/csi_volume_limit_scaling.go:142]: there is no feature gate tag now

Comment (jsafrane) [reply test/e2e/storage/csimock/csi_volume_limit_scaling.go:142]: /lgtm cancel
:-(

Comment (gnufied) [reply test/e2e/storage/csimock/csi_volume_limit_scaling.go:142]: Wait,  I moved it to the top;

```
utils.SIGDescribe("CSI Mock VolumeLimitScaling scheduling", framework.WithFeatureGate(features.VolumeLimitScaling)
```

Comment (jsafrane) [reply test/e2e/storage/csimock/csi_volume_limit_scaling.go:142]: sorry, it's late evening here
/lgtm

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 23]
```diff
@@ -282,6 +283,19 @@ func (pl *CSILimits) Filter(ctx context.Context, _ fwk.CycleState, pod *v1.Pod,
 		return nil
 	}
 
+	if pl.enableVolumeLimitScaling {
+		for _, driverName := range newVolumes {
+			driverInstalled, err := pl.checkCSIDriverOnNode(driverName, csiNode)
+			if err != nil {
+				return fwk.AsStatus(err)
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:290]: This error is user facing (put into the pod status). It's worth wrapping it to add some context. Wrapping can be added to the `checkCSIDriverOnNode` method

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 9 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:359]: Right, in the current implementation the only error this getter can return is NotFound (but it's worth handling any error appropriately, like you did)

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 15 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: I think it's generally ok to have the same names, as they won't conflict anyway, but it's up to you

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 24]
```diff
@@ -0,0 +1,57 @@
...
+func NewCSIManager(csiNodeLister storagelisters.CSINodeLister) *DefaultCSIManager {
+	return &DefaultCSIManager{defaultCSINodeLister: NewCSINodeLister(csiNodeLister)}
+}
+
+func (m *DefaultCSIManager) CSINodes() fwk.CSINodeLister {
+	return m.defaultCSINodeLister
+}
+
+type csiNodeLister struct {
+	csinodeLister storagelisters.CSINodeLister
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]:
```suggestion
	csiNodeLister storagelisters.CSINodeLister
```
?

**Review by macsko — COMMENTED** [review]
A few comments left. Other than that looks good

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 23 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:290]: Fixed.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 15 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: yeah I know, I am just stickler for that convention. lets leave it as it is.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go [hunk 25]
```diff
@@ -0,0 +1,57 @@
...
+import (
+	storagev1 "k8s.io/api/storage/v1"
+	"k8s.io/apimachinery/pkg/labels"
+	storagelisters "k8s.io/client-go/listers/storage/v1"
+	fwk "k8s.io/kube-scheduler/framework"
+)
+
+// DefaultCSIManager is an implementation of the CSIManager interface.
+type DefaultCSIManager struct {
+	defaultCSINodeLister *csiNodeListerWrapper
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: nit: I guess csiNodeLister is enough.

**Review by kerthcet — COMMENTED** [review]
Only one nit, not a blocking issue.
/approve
/hold

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go [hunk 26]
```diff
@@ -338,6 +352,29 @@ func (pl *CSILimits) Filter(ctx context.Context, _ fwk.CycleState, pod *v1.Pod,
 	return nil
 }
 
+func (pl *CSILimits) checkCSIDriverOnNode(pluginName string, csiNode *storagev1.CSINode) (bool, error) {
+	// the registered driver must be a CSI driver to enforce this limit, if we can't find the driver,
+	// we assume the driver may not be a CSI driver and allow the pod to be scheduled.
+	_, err := pl.csiDriverLister.Get(pluginName)
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			return true, nil
```
Comment (kerthcet) [inline pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:361]: For the first glance, I also thought it was a bug, but saw the comments and discussions above.

Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:361]: It should be fine though right? `NotFound` errors should allow pods to be scheduled, because more than likely volume is not a CSI volume. Any other unexpected error from lister should be treated as fatal and block pod scheduling.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go (hunk 25 above)
Comment (gnufied) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi_manager.go]: fixed.

File: pkg/scheduler/framework/plugins/nodevolumelimits/csi.go (hunk 26 above)
Comment (kerthcet) [reply pkg/scheduler/framework/plugins/nodevolumelimits/csi.go:361]: fair
