### PR TITLE
Make kubeadm join discovery wait for a finite time

### LINKED ISSUE #1693: Make discovery wait for a finite time
Follow up of https://github.com/kubernetes/kubernetes/pull/80675#discussion_r308016782

Currently the discovery logic runs indefinitely and we should change this to fail after a while.
I'd say 10 retries * 5 seconds (DiscoveryRetryInterval) should be enough.

### PR DESCRIPTION
**Pull request by olivierlemasle**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Add a timeout to discovery in `kubeadm join`, when using a discovery file.

Currently the discovery logic runs indefinitely. During review of #80675, @neolit123 requested to add a timeout: https://github.com/kubernetes/kubernetes/pull/80675#discussion_r308016782.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubeadm/issues/1693

**Special notes for your reviewer**:

Timeout value is `cfg.Discovery.Timeout.Duration`, which is already the timeout for token-based discovery. It can be customized in `JoinConfiguration` and defaults to `v1beta2.DefaultDiscoveryTimeout`, which is 5 minutes. This should be sufficient for worker nodes waiting for control-plane nodes in case of parallel provisioning.

**Does this PR introduce a user-facing change?**:

```release-note
"kubeadm join" fails if file-based discovery is too long, with a default timeout of 5 minutes.
```

/sig cluster-lifecycle
/cc fabriziopandini neolit123
/priority important-longterm

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @olivierlemasle 
/lgtm
/ok-to-test

File: cmd/kubeadm/app/discovery/file/file.go [hunk 1]
```diff
@@ -106,6 +108,11 @@ func ValidateConfigInfo(config *clientcmdapi.Config, clustername string) (*clien
 		}
 		return true, nil
 	})
+	if err == wait.ErrWaitTimeout {
+		timeoutErr := errors.Errorf("Abort reading the %s ConfigMap after timeout of %v", bootstrapapi.ConfigMapClusterInfo, discoveryTimeout)
+		klog.V(1).Infof("[discovery] %v\n", timeoutErr)
+		return nil, timeoutErr
```
Comment (neolit123) [inline cmd/kubeadm/app/discovery/file/file.go]: should be enough to just:
```
return nil, errors.Errorf("Abort reading the %s ConfigMap after timeout of %v", bootstrapapi.ConfigMapClusterInfo, discoveryTimeout)
```
without the klog v1, otherwise for --v=1 the error will be printed twice.

**Review by neolit123 — COMMENTED** [review]
thanks @olivierlemasle 
added one minor comment.
but i think we should also change these polls:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/token/token.go#L78
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/token/token.go#L142

**Comment by neolit123** [comment]
it seems that the unit tests for discovery are panicing: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/80804/pull-kubernetes-bazel-test/1156531200035131392/build-log.txt

**Comment by olivierlemasle** [comment]
Thanks for your review @neolit123 

I fixed the failing unit tests and applied your suggestion regarding logging.

> i think we should also change these polls:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/token/token.go#L78
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/discovery/token/token.go#L142

I actually did see these  `wait.PollImmediateInfinite` in token-based discovery before opening the PR; however in this case discovery is always finite, because they're wrapped in [fetchKubeConfigWithTimeout](https://github.com/kubernetes/kubernetes/blob/8c8c4113f045a00bee611594e402dee07600812b/cmd/kubeadm/app/discovery/token/token.go#L64), which fails after a timeout (see [here](https://github.com/kubernetes/kubernetes/blob/8c8c4113f045a00bee611594e402dee07600812b/cmd/kubeadm/app/discovery/token/token.go#L218)). Actually, it uses the same timeout `cfg.Discovery.Timeout` I used in this PR.
So i suppose we can keep this `wait.PollImmediateInfinite`, right?

**Review by rosti — COMMENTED** [review]
Thank you @olivierlemasle !
Can you squash your commits?

Ideally, the HTTPS case should have the fetch timeout into this one, but that would complicate the code. Thus, I am file with how things look ATM. Let's merge it as is.

/approve

**Comment by olivierlemasle** [comment]
@rosti, thanks, I've squashed the commits.
