### PR TITLE
[Federation] Fix flake in TestUpdateClusterRace

### LINKED ISSUE #50262: TestUpdateClusterRace flake
seen in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50258/pull-kubernetes-unit/45229/artifacts/junit_42602c56127c09f7378bbc50f2d72cb7f5b883c6_20170807-183126.stdout

```
=== RUN   TestUpdateClusterRace
E0807 18:35:35.756756   23178 cluster_client.go:145] Failed to list nodes while getting zone names: couldn't get version/kind; json parse error: invalid character 'o' looking for beginning of value
E0807 18:35:35.765719   23178 cluster_client.go:145] Failed to list nodes while getting zone names: couldn't get version/kind; json parse error: invalid character 'o' looking for beginning of value
==================
WARNING: DATA RACE
Write at 0x00c4202c1fb0 by goroutine 34:
  runtime.mapdelete()
      /usr/local/go/src/runtime/hashmap.go:598 +0x0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Delete()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:58 +0x8f
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).delFromClusterSetByName()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:109 +0x194
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).delFromClusterSet()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:101 +0xbc
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:193 +0x667
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107

Previous read at 0x00c4202c1fb0 by goroutine 37:
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).UpdateClusterStatus()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:190 +0x2ba
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace.func2()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:185 +0x38

Goroutine 34 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107
  testing.runTests()
      /usr/local/go/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:822 +0x1c3
  main.main()
      k8s.io/kubernetes/federation/pkg/federation-controller/cluster/_test/_testmain.go:44 +0x20f

Goroutine 37 (running) created at:
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:187 +0x5e4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1c7760b]

goroutine 85 [running]:
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterClient).GetClusterHealthStatus(0xc420365f00, 0xc42065f500)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/cluster_client.go:100 +0x24b
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).GetClusterStatus(0xc4200ea770, 0xc42065f500, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:172 +0x9a
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).UpdateClusterStatus(0xc4200ea770, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:204 +0x427
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace.func2(0xc4200ea770)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:185 +0x39
created by k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:187 +0x5e5
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/cluster	1.205s
=== RUN   TestIngressController
E0807 18:35:42.628738   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:42.633482   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.840482   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{}, Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "A":"B"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'UpdateInCluster' 'Updating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.844918   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{}, Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "A":"B", "kubernetes.io/ingress.global-static-ip-name":"foo"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'UpdateInCluster' 'Updating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.846056   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "A":"B", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "kubernetes.io/ingress.global-static-ip-name":"foo"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster2'
```

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**:
Fix #50262

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50262

**Special notes for your reviewer**:
Although we do locking/unlocking while using protected data in ClusterController, there are chances that `clusterClient` can be deleted as it is a pointer. Also its better to lock/unlock once for the function `UpdateClusterStatus` instead of multiple locks/unlocks.

**Release note**:
```
NONE
```

/assign @madhusudancs 
/cc @dminh @kubernetes/sig-federation-bugs

### CODE REVIEW

File: federation/pkg/federation-controller/cluster/clustercontroller.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ type ClusterController struct {
 	// clusterMonitorPeriod is the period for updating status of cluster
 	clusterMonitorPeriod time.Duration
 
-	mu              sync.RWMutex
+	sync.Mutex
```
Comment (liggitt) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: in general, don't inline this if you don't want external callers to have access to your lock/unlock functions

File: federation/pkg/federation-controller/cluster/clustercontroller_test.go [hunk 2]
```diff
@@ -171,20 +172,16 @@ func TestUpdateClusterRace(t *testing.T) {
...
 		return func() (*clientcmdapi.Config, error) {
 			return &clientcmdapi.Config{}, nil
 		}
 	}
 
-	manager := newClusterController(federationClientSet, 5)
+	manager := newClusterController(federationClientSet, 1*time.Millisecond)
 
-	go func() {
-		for {
```
Comment (liggitt) [inline federation/pkg/federation-controller/cluster/clustercontroller_test.go]: at the very least, this should have had a way to exit after the test completed

File: federation/pkg/federation-controller/cluster/clustercontroller.go [hunk 3]
```diff
@@ -194,21 +192,17 @@ func (cc *ClusterController) UpdateClusterStatus() error {
 		}
```
Comment (dqminh) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: looking at the trace, seems like i missed a lock here in the original change

File: federation/pkg/federation-controller/cluster/clustercontroller.go [hunk 4]
```diff
@@ -180,11 +178,11 @@ func (cc *ClusterController) UpdateClusterStatus() error {
 		return err
 	}
 
-	cc.mu.Lock()
+	cc.Lock()
+	defer cc.Unlock()
```
Comment (dqminh) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: i thought about this in the original change, but not too sure about it since it can potentially holds the lock for a long time when it tries to update the clusters' status ? But perhaps its not too bad since this reconciliation loop is not run very frequently i think ?

File: federation/pkg/federation-controller/cluster/clustercontroller.go [hunk 5]
```diff
@@ -148,9 +148,7 @@ func (cc *ClusterController) Run(stopChan <-chan struct{}) {
 }
 
 func (cc *ClusterController) GetClusterClient(cluster *federationv1beta1.Cluster) (*ClusterClient, error) {
-	cc.mu.RLock()
 	clusterClient, found := cc.clusterKubeClientMap[cluster.Name]
-	cc.mu.RUnlock()
```
Comment (dqminh) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: we should keep the read lock here when getting the kube client.

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 1 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: Agree, will change.

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 4 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: By default, `UpdateClusterStatus` gets called once every 40 seconds. Also the cluster additions/deletions are rare events and not critical path. so locking/unlocking once is better.

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 5 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: This won't be required now.

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 3 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: Ack.

File: federation/pkg/federation-controller/cluster/clustercontroller_test.go (hunk 2 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller_test.go]: Agree.

**Review by shashidharatd — COMMENTED** [review]
@liggitt , @dqminh  is there any outstanding concern on this pr, otherwise can i get an LGTM.
@madhusudancs PTAL.
Thanks !

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 5 above)
Comment (dqminh) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: indeed, but some race can still happen if people uses this public function though. We probably want to make this private if it doesnt need to be exposed ?

**Comment by dqminh** [comment]
LGTM

@shashidharatd thanks for making the change !

File: federation/pkg/federation-controller/cluster/clustercontroller.go (hunk 5 above)
Comment (shashidharatd) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: Thanks for catching this. unexported the function now.

**Comment by dcbw** [comment]
Drive-by review because I got here from a test flake I was looking at...

Important to note that with this change, almost the whole UpdateClusterStatus() function will now be locked.  Including bits that hit up the network, like the Update() near the bottom.  Is that going to be a problem performance-wise?

I know that typical lock/mutex usage does unlocks with defer to make sure issues like what this PR fixed don't happen, but they are also usually done in smaller targeted functions than ones like this that do quite a lot.

A more targeted fix would just do something like:

```
	cc.mu.Lock()
	for _, cluster := range clusters.Items {
		cc.addToClusterSetWithoutLock(&cluster)
	}
	curLen := len(cc.knownClusterSet)
	cc.mu.Unlock()

	// If there's a difference between lengths of known clusters and observed clusters
	if curLen != len(clusters.Items) {
```

but of course that doesn't make the locking simpler with defer...

**Comment by shashidharatd** [comment]
@dcbw, Agree with the concern. although its not the critical path, it would be better to not lock operations involving network. I relooked into code to reduce the number of times we lock/unlock and found a better way to handle and so refactored the `updateClusterStatus()` function.

File: federation/pkg/federation-controller/cluster/clustercontroller.go [hunk 6]
```diff
@@ -141,77 +142,32 @@ func (cc *ClusterController) Run(stopChan <-chan struct{}) {
...
-			glog.Infof("Failed to Get the status of cluster: %v", cluster.Name)
+		cc.mu.RLock()
+		// skip updating status of the cluster which is not yet added to knownClusterSet.
+		if !cc.knownClusterSet.Has(cluster.Name) {
+			cc.mu.RUnlock()
 			continue
 		}
-		cc.mu.RLock()
-		clusterStatusOld, found := cc.clusterClusterStatusMap[cluster.Name]
+		clusterClient, _ := cc.clusterKubeClientMap[cluster.Name]
```
Comment (madhusudancs) [inline federation/pkg/federation-controller/cluster/clustercontroller.go]: I am somewhat worried about dropping the existence result (the second variable on the left hand side). What if the key doesn't exist? Even if that never happens, I would have a log entry saying something unexpected has happened if it does. Helps catch bugs.

**Review by madhusudancs — COMMENTED** [review]
@shashidharatd minor nit. Let me know once that is addressed.

**Comment by shashidharatd** [comment]
@madhusudancs, I have fixed the nit. PTAL.
All tests have passed except the flake in pull-kubernetes-e2e-gce-etcd3
/test pull-kubernetes-e2e-gce-etcd3
