### PR TITLE
[kubeadm]: Fix the CoreDNS preflight check for unsupported plugins

### LINKED ISSUE #82889: Can't upgrade to 1.16.0: [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS
```
kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
        [ERROR CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```
Any ideas how to solve this?

```
kubectl get nodes -o wide
host1  Ready    master   207d   v1.16.0   10.10.0.10    <none>        Ubuntu 18.04.3 LTS   4.15.0-64-generic   docker://18.6.1
```

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**

/kind bug 

**What this PR does / why we need it**:
Fixes the CoreDNS migration preflight check for checking unsupported plugins.
The PR also adds additional info for the user, which will guide them on how to proceed.
**Which issue(s) this PR fixes**:

Fixes #82889

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rajansandeep** [comment]
/cc @chrisohaver @neolit123 

@neolit123, let me know if I need to add a release note for this.

File: cmd/kubeadm/app/phases/upgrade/preflight.go [hunk 1]
```diff
@@ -80,20 +80,19 @@ func checkUnsupportedPlugins(client clientset.Interface) error {
...
-			UnsupportedVersion = unsup.Version
-
-		}
-		if UnsupportedPlugins != "" || UnsupportedVersion != "" {
-			return errors.New("there are unsupported plugins in the CoreDNS Corefile")
+			UnsupportedPlugins = append(UnsupportedPlugins, unsup.Plugin)
 		}
+		klog.V(1).Infoln("The corefile contains plugins that kubeadm/CoreDNS does not know how to migrate.")
+		klog.V(1).Infoln("Each plugin listed should be manually verified for compatibility with the newer version of CoreDNS. Once ready, the upgrade can be initiated by skipping the preflight check. ")
+		klog.V(1).Infoln("During the upgrade, kubeadm will migrate the configuration while leaving the listed plugin configs untouched, but cannot guarantee that they will work with the newer version of CoreDNS.")
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/preflight.go]: this seems like detailed information that should be visible outside of klog and verbosity levels.
i think it makes sense to print it using `fmt.Print*()`. we have similar for `kubeadm init`.

i'd also print it like so trying to keep the lines in the source code shorter.

```
fmt.Println("The corefile contains plugins that kubeadm/CoreDNS does not know how to migrate. " +
	"Each plugin listed should be manually verified for compatibility with the newer version of CoreDNS. " +
	"...")
```

separate `fmt.Println()` seem appropriate if a sentence should be a separate paragraph.

**Comment by neolit123** [comment]
> let me know if I need to add a release note for this.

no i think it's fine, to leave this change transparent.

**Comment by chrisohaver** [comment]
@rajansandeep, can you share an example of what the output look like when this preflight check fails?

**Comment by rajansandeep** [comment]
> @rajansandeep, can you share an example of what the output look like when this preflight check fails?

The output would look like this:
```
[preflight] Running pre-flight checks.
I0224 19:20:52.922576   18154 preflight.go:77] validating if there are any unsupported CoreDNS plugins in the Corefile
W0224 19:20:52.927635   18154 preflight.go:92] The corefile contains plugins that kubeadm/CoreDNS does not know how to migrate.
W0224 19:20:52.927640   18154 preflight.go:93] Each plugin listed should be manually verified for compatibility with the newer version of CoreDNS. Once ready, the upgrade can be initiated by skipping the preflight check. 
W0224 19:20:52.927644   18154 preflight.go:94] During the upgrade, kubeadm will migrate the configuration while leaving the listed plugin configs untouched, but cannot guarantee that they will work with the newer version of CoreDNS.
	[WARNING CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile: [hosts erratic]
```
This is currently with log verbosity level 1 enabled.

**Comment by chrisohaver** [comment]
> [WARNING CoreDNSUnsupportedPlugins]: there are unsupported plugins in the CoreDNS Corefile: ...

I think most people would interpret this as  "CoreDNS itself doesn't support these plugins."  Which is not necessarily the case.  It's the CoreDNS migration tool thats unable to migrate them.

Perhaps we could say ... 

```
> [WARNING CoreDNSUnsupportedPlugins]: CoreDNS cannot migrate the following plugins: ...
```

File: cmd/kubeadm/app/phases/upgrade/preflight.go [hunk 2]
```diff
@@ -80,20 +81,20 @@ func checkUnsupportedPlugins(client clientset.Interface) error {
...
-			UnsupportedVersion = unsup.Version
-
-		}
-		if UnsupportedPlugins != "" || UnsupportedVersion != "" {
-			return errors.New("there are unsupported plugins in the CoreDNS Corefile")
+			UnsupportedPlugins = append(UnsupportedPlugins, unsup.ToString())
 		}
+		fmt.Println("[preflight] The corefile contains plugins that kubeadm/CoreDNS does not know how to migrate. " +
+			"Each plugin listed should be manually verified for compatibility with the newer version of CoreDNS. " +
+			"Once ready, the upgrade can be initiated by skipping the preflight check. During the upgrade, kubeadm will migrate the configuration while leaving the listed plugin configs untouched, " +
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/preflight.go]: could you please split this line as well:
```
"Once ready, the upgrade can be initiated by skipping the preflight check. During the upgrade, " +
"kubeadm will migrate the configuration while leaving the listed plugin configs untouched, " +
...
```

**Comment by neolit123** [comment]
please squash the commits, then LGTM.

**Comment by neolit123** [comment]
/lgtm
sorry for multiple requests on formatting.

**Comment by neolit123** [comment]
>  ✗ Writing configuration 📜
> ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged kind-worker cat /kind/version" failed with error: exit status 1

hm, we are seeing this in kind CI from time to time.

/retest

**Review by chrisohaver — APPROVED** [review]
lgtm
