### PR TITLE
node ipam controller ut: run test in parallel to avoid timeout

### LINKED ISSUE #116173: Failure cluster [01ff4ab4...] TestNewNodeIpamControllerWithCIDRMasks
##### Error text:
```
Failed
=== RUN   TestNewNodeIpamControllerWithCIDRMasks
=== RUN   TestNewNodeIpamControllerWithCIDRMasks/valid_range_allocator
panic: test timed out after 10m0s
running tests:
	TestNewNodeIpamControllerWithCIDRMasks (25s)
	TestNewNodeIpamControllerWithCIDRMasks/valid_range_allocator (25s)

goroutine 80 [running]:
testing.(*M).startAlarm.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00058b380, {0x43ecd8a, 0x26}, 0x44f0468)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc00058b380, 0xc000545b48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc00068fcc0?, {0x5ee6180, 0x1, 0x1}, {0x1c?, 0x1e?, 0x5f11580?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc00068fcc0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1906 +0xb45

```
#### Recent failures:
[2023/2/28 22:17:50 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630572435256381440)
[2023/2/28 16:17:43 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630481837178490880)
[2023/2/28 10:17:52 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630391238869913600)
[2023/2/28 04:19:29 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630300640649416704)
[2023/2/27 22:18:23 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630209948417789952)

/sig network
/kind failing-test

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

After
```
➜  kubernetes git:(fix-TestNewNodeIpamControllerWithCIDRMasks) /usr/local/go/bin/go test -timeout 6s -run ^TestNewNodeIpamControllerWithCIDRMasks$ k8s.io/kubernetes/pkg/controller/nodeipam  
ok      k8s.io/kubernetes/pkg/controller/nodeipam       0.935s
```
Before 
```
➜  kubernetes git:(master) /usr/local/go/bin/go test -run ^TestNewNodeIpamControllerWithCIDRMasks$ k8s.io/kubernetes/pkg/controller/nodeipam  
ok      k8s.io/kubernetes/pkg/controller/nodeipam       141.313s
```

#### Which issue(s) this PR fixes:
Fixes #116173

#### Special notes for your reviewer:

```release-note
None
```

### CODE REVIEW

File: pkg/controller/nodeipam/node_ipam_controller_test.go [hunk 1]
```diff
@@ -92,18 +92,21 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
...
 
 			if os.Getenv("EXIT_ON_FATAL") == "1" {
 				// This is the subprocess which runs the actual code.
-				newTestNodeIpamController(clusterCidrs, serviceCIDRIpNet, secondaryServiceCIDRIpNet, tc.maskSize, tc.allocatorType)
+				newTestNodeIpamController(clusterCidrs, serviceCIDRIpNet, secondaryServiceCIDRIpNet, test.maskSize, test.allocatorType)
 				return
 			}
 			// This is the host process that monitors the exit code of the subprocess.
-			cmd := exec.Command(os.Args[0], "-test.run=TestNewNodeIpamControllerWithCIDRMasks/"+tc.desc)
+			cmd := exec.Command(os.Args[0], "-test.run=TestNewNodeIpamControllerWithCIDRMasks/"+test.desc)
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller_test.go:109]: why this test executes itself?

Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:109]: I see, the controller panics

```
			klog.Fatal("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
```

Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:109]: #68952 added this.
It seems to be not that graceful.

Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:109]: the test is wrong, let me check it better

Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:109]: some of the test cases are wrong, checking right now

**Comment by aojea** [comment]
@pacoxu I think we should move to
```
diff --git a/pkg/controller/nodeipam/node_ipam_controller.go b/pkg/controller/nodeipam/node_ipam_controller.go
index 813aeab1a7f..85a7e354f69 100644
--- a/pkg/controller/nodeipam/node_ipam_controller.go
+++ b/pkg/controller/nodeipam/node_ipam_controller.go
@@ -96,13 +96,15 @@ func NewNodeIpamController(
        // Cloud CIDR allocator does not rely on clusterCIDR or nodeCIDRMaskSize for allocation.
        if allocatorType != ipam.CloudAllocatorType {
                if len(clusterCIDRs) == 0 {
-                       klog.Fatal("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
+                       klog.Warning("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
+                       panic("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
                }
 
                for idx, cidr := range clusterCIDRs {
                        mask := cidr.Mask
                        if maskSize, _ := mask.Size(); maskSize > nodeCIDRMaskSizes[idx] {
-                               klog.Fatal("Controller: Invalid --cluster-cidr, mask size of cluster CIDR must be less than or equal to --node-cidr-mask-size configured for CIDR family")
+                               klog.Warning("Controller: Invalid --cluster-cidr, mask size of cluster CIDR must be less than or equal to --node-cidr-mask-size configured for CIDR family")
+                               panic("Controller: Invalid --cluster-cidr, mask size of cluster CIDR must be less than or equal to --node-cidr-mask-size configured for CIDR family")
                        }
                }
        }
diff --git a/pkg/controller/nodeipam/node_ipam_controller_test.go b/pkg/controller/nodeipam/node_ipam_controller_test.go
index 282b5efbbdc..b986026382c 100644
--- a/pkg/controller/nodeipam/node_ipam_controller_test.go
+++ b/pkg/controller/nodeipam/node_ipam_controller_test.go
@@ -21,18 +21,19 @@ package nodeipam
 
 import (
        "net"
-       "os"
-       "os/exec"
        "strings"
        "testing"
 
        v1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+       utilfeature "k8s.io/apiserver/pkg/util/feature"
        "k8s.io/client-go/informers"
        "k8s.io/client-go/kubernetes/fake"
-       "k8s.io/kubernetes/pkg/controller"
+       featuregatetesting "k8s.io/component-base/featuregate/testing"
+       _ "k8s.io/klog/v2/ktesting/init" // activate ktesting command line flags
        "k8s.io/kubernetes/pkg/controller/nodeipam/ipam"
        "k8s.io/kubernetes/pkg/controller/testutil"
+       "k8s.io/kubernetes/pkg/features"
        "k8s.io/legacy-cloud-providers/gce"
        netutils "k8s.io/utils/net"
 )
@@ -46,7 +47,7 @@ func newTestNodeIpamController(clusterCIDR []*net.IPNet, serviceCIDR *net.IPNet,
                Clientset: fake.NewSimpleClientset(),
        }
        fakeClient := &fake.Clientset{}
-       fakeInformerFactory := informers.NewSharedInformerFactory(fakeClient, controller.NoResyncPeriodFunc())
+       fakeInformerFactory := informers.NewSharedInformerFactory(fakeClient, 0)
        fakeNodeInformer := fakeInformerFactory.Core().V1().Nodes()
        fakeClusterCIDRInformer := fakeInformerFactory.Networking().V1alpha1().ClusterCIDRs()
 
@@ -75,51 +76,55 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
                wantFatal            bool
        }{
                {"valid_range_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.RangeAllocatorType, false},
-
-               {"valid_range_allocator_dualstack", "10.0.0.0/21,2000::/10", "10.1.0.0/21", emptyServiceCIDR, []int{24, 98}, ipam.RangeAllocatorType, false},
-               {"valid_range_allocator_dualstack_dualstackservice", "10.0.0.0/21,2000::/10", "10.1.0.0/21", "3000::/10", []int{24, 98}, ipam.RangeAllocatorType, false},
-
+               {"valid_range_allocator_dualstack", "10.0.0.0/21,2000::/48", "10.1.0.0/21", emptyServiceCIDR, []int{24, 64}, ipam.RangeAllocatorType, false},
+               {"valid_range_allocator_dualstack_dualstackservice", "10.0.0.0/21,2000::/48", "10.1.0.0/21", "3000::/112", []int{24, 64}, ipam.RangeAllocatorType, false},
                {"valid_multi_cidr_range_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.MultiCIDRRangeAllocatorType, false},
-               {"valid_multi_cidr_range_allocator_dualstack", "10.0.0.0/21,2000::/10", "10.1.0.0/21", emptyServiceCIDR, []int{24, 98}, ipam.MultiCIDRRangeAllocatorType, false},
-
+               {"valid_multi_cidr_range_allocator_dualstack", "10.0.0.0/21,2000::/48", "10.1.0.0/21", emptyServiceCIDR, []int{24, 64}, ipam.MultiCIDRRangeAllocatorType, false},
                {"valid_cloud_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
                {"valid_ipam_from_cluster", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, false},
                {"valid_ipam_from_cloud", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromCloudAllocatorType, false},
                {"valid_skip_cluster_CIDR_validation_for_cloud_allocator", "invalid", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
-               {"invalid_cluster_CIDR", "invalid", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, true},
-               {"valid_CIDR_smaller_than_mask_cloud_allocator", "10.0.0.0/26", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
+               {"valid_CIDR_smaller_than_mask_cloud_allocator", "10.0.0.0/16", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
+               {"invalid_cluster_CIDR", "", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, true},
                {"invalid_CIDR_smaller_than_mask_other_allocators", "10.0.0.0/26", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromCloudAllocatorType, true},
-               {"invalid_serviceCIDR_contains_clusterCIDR", "10.0.0.0/23", "10.0.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, true},
-               {"invalid_CIDR_mask_size", "10.0.0.0/24,2000::/64", "10.1.0.0/21", emptyServiceCIDR, []int{24, 48}, ipam.IPAMFromClusterAllocatorType, true},
+               {"invalid_serviceCIDR_contains_clusterCIDR", "10.0.0.0/16", "10.0.0.0/8", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, true},
+               {"invalid_CIDR_mask_size", "10.0.0.0/24,2000::/48", "10.1.0.0/21", emptyServiceCIDR, []int{24, 64}, ipam.IPAMFromClusterAllocatorType, true},
        } {
                test := tc
                t.Run(test.desc, func(t *testing.T) {
-                       t.Parallel()
-
-                       clusterCidrs, _ := netutils.ParseCIDRs(strings.Split(test.clusterCIDR, ","))
-                       _, serviceCIDRIpNet, _ := netutils.ParseCIDRSloppy(test.serviceCIDR)
-                       _, secondaryServiceCIDRIpNet, _ := netutils.ParseCIDRSloppy(test.secondaryServiceCIDR)
+                       // t.Parallel()
+                       if test.allocatorType == ipam.MultiCIDRRangeAllocatorType {
+                               defer featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.MultiCIDRRangeAllocator, true)()
+                       }
 
-                       if os.Getenv("EXIT_ON_FATAL") == "1" {
-                               // This is the subprocess which runs the actual code.
-                               newTestNodeIpamController(clusterCidrs, serviceCIDRIpNet, secondaryServiceCIDRIpNet, test.maskSize, test.allocatorType)
-                               return
+                       clusterCidrs, err := netutils.ParseCIDRs(strings.Split(test.clusterCIDR, ","))
+                       if err != nil {
+                               clusterCidrs = nil
                        }
-                       // This is the host process that monitors the exit code of the subprocess.
-                       cmd := exec.Command(os.Args[0], "-test.run=TestNewNodeIpamControllerWithCIDRMasks/"+test.desc)
-                       cmd.Env = append(os.Environ(), "EXIT_ON_FATAL=1")
-                       err := cmd.Run()
-                       var gotFatal bool
+                       _, serviceCIDRIpNet, err := netutils.ParseCIDRSloppy(test.serviceCIDR)
                        if err != nil {
-                               exitErr, ok := err.(*exec.ExitError)
-                               if !ok {
-                                       t.Fatalf("Failed to run subprocess: %v", err)
-                               }
-                               gotFatal = !exitErr.Success()
+                               serviceCIDRIpNet = nil
                        }
-                       if gotFatal != test.wantFatal {
-                               t.Errorf("newTestNodeIpamController(%v, %v, %v, %v) : gotFatal = %t ; wantFatal = %t", clusterCidrs, serviceCIDRIpNet, test.maskSize, test.allocatorType, gotFatal, test.wantFatal)
+                       _, secondaryServiceCIDRIpNet, err := netutils.ParseCIDRSloppy(test.secondaryServiceCIDR)
+                       if err != nil {
+                               secondaryServiceCIDRIpNet = nil
                        }
+                       // This is the subprocess which runs the actual code.
+                       defer func() {
+                               r := recover()
+                               if r == nil && test.wantFatal {
+                                       t.Errorf("The code did not panic")
+                               } else if r != nil && !test.wantFatal {
+                                       t.Errorf("The code did panic")
+                               }
+                       }()
+                       _, err = newTestNodeIpamController(clusterCidrs, serviceCIDRIpNet, secondaryServiceCIDRIpNet, test.maskSize, test.allocatorType)
+                       // The code is inconsistent about returning error or panic
+                       // but we have to keep both ways of existing for backwards compatibility
+                       if (err != nil) != test.wantFatal {
+                               t.Errorf("Got error %v expected %v", err, test.wantFatal)
+                       }
+
                })
        }
 }
```

but some test cases are still failing, I don't have time this morning to keep debugging, if you can fix them it will be awesome

**Comment by pacoxu** [comment]
Let me check. Thanks for your input.

**Comment by pacoxu** [comment]
I divided the test cases into two as the feature gate change will make `t.Parallel()` fail.

```
3m5s: 24 runs so far, 0 failures
```

File: pkg/controller/nodeipam/legacyprovider.go [hunk 2]
```diff
@@ -62,7 +63,8 @@ func createLegacyIPAM(
 	}
 	ipamc, err := ipam.NewController(cfg, kubeClient, cloud, cidr, serviceCIDR, nodeCIDRMaskSizes[0])
 	if err != nil {
-		klog.Fatalf("Error creating ipam controller: %v", err)
+		klog.Warningf("Error creating ipam controller: %v", err)
+		panic(fmt.Sprintf("Error creating ipam controller: %v", err))
```
Comment (aojea) [inline pkg/controller/nodeipam/legacyprovider.go:67]: @bowei @sarveshr7 what do you think to replace klog.Fatal from a. panic, the difference AFAIK is that the former does an `os.Exit`

File: pkg/controller/nodeipam/node_ipam_controller_test.go [hunk 3]
```diff
@@ -75,47 +76,99 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
...
-
+		{"valid_range_allocator_dualstack", "10.0.0.0/21,2000::/48", "10.1.0.0/21", emptyServiceCIDR, []int{24, 64}, ipam.RangeAllocatorType, false},
+		{"valid_range_allocator_dualstack_dualstackservice", "10.0.0.0/21,2000::/48", "10.1.0.0/21", "3000::/112", []int{24, 64}, ipam.RangeAllocatorType, false},
 		{"valid_cloud_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
 		{"valid_ipam_from_cluster", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, false},
 		{"valid_ipam_from_cloud", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromCloudAllocatorType, false},
 		{"valid_skip_cluster_CIDR_validation_for_cloud_allocator", "invalid", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
-		{"invalid_cluster_CIDR", "invalid", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.IPAMFromClusterAllocatorType, true},
-		{"valid_CIDR_smaller_than_mask_cloud_allocator", "10.0.0.0/26", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.CloudAllocatorType, false},
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller_test.go:90]: this test was wrong or was the name

File: pkg/controller/nodeipam/node_ipam_controller_test.go [hunk 4]
```diff
@@ -75,47 +76,99 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
 		wantFatal            bool
 	}{
 		{"valid_range_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.RangeAllocatorType, false},
-
-		{"valid_range_allocator_dualstack", "10.0.0.0/21,2000::/10", "10.1.0.0/21", emptyServiceCIDR, []int{24, 98}, ipam.RangeAllocatorType, false},
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller_test.go:79]: this test was wrong, it failed before but it was considered valid

File: pkg/controller/nodeipam/node_ipam_controller_test.go [hunk 5]
```diff
@@ -75,47 +76,99 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
...
-		{"valid_range_allocator_dualstack_dualstackservice", "10.0.0.0/21,2000::/10", "10.1.0.0/21", "3000::/10", []int{24, 98}, ipam.RangeAllocatorType, false},
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller_test.go:80]: same

File: pkg/controller/nodeipam/node_ipam_controller_test.go [hunk 6]
```diff
@@ -75,47 +76,99 @@ func TestNewNodeIpamControllerWithCIDRMasks(t *testing.T) {
...
-
-		{"valid_multi_cidr_range_allocator", "10.0.0.0/21", "10.1.0.0/21", emptyServiceCIDR, []int{24}, ipam.MultiCIDRRangeAllocatorType, false},
-		{"valid_multi_cidr_range_allocator_dualstack", "10.0.0.0/21,2000::/10", "10.1.0.0/21", emptyServiceCIDR, []int{24, 98}, ipam.MultiCIDRRangeAllocatorType, false},
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller_test.go:83]: moved to a different test

**Comment by aojea** [comment]
/approve
/assign @bowei @sarveshr7 

for final lgmt

@liggitt do you think that the s/klog.Fatal/panic/ can have any unexpected side effect?

File: pkg/controller/nodeipam/node_ipam_controller_test.go (hunk 6 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:83]: Yes， these two are move to the next test case.

File: pkg/controller/nodeipam/legacyprovider.go (hunk 2 above)
Comment (liggitt) [reply pkg/controller/nodeipam/legacyprovider.go:67]: I think it would be better to return an error from this function and make all callers handle the error... test callers can fail the test or suppress the error, non-test callers should fail init.

A panic risks a non-test caller recovering and continuing on in a broken state

File: pkg/controller/nodeipam/node_ipam_controller.go [hunk 7]
```diff
@@ -96,13 +96,15 @@ func NewNodeIpamController(
 	// Cloud CIDR allocator does not rely on clusterCIDR or nodeCIDRMaskSize for allocation.
 	if allocatorType != ipam.CloudAllocatorType {
 		if len(clusterCIDRs) == 0 {
-			klog.Fatal("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
+			klog.Warning("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
+			panic("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
```
Comment (liggitt) [inline pkg/controller/nodeipam/node_ipam_controller.go:100]: I would expect to return an error here and below and make all callers handle returned errors correctly

Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller.go:100]: I tried in https://github.com/pacoxu/kubernetes/pull/1776/files.

Then no panic in `NewNodeIpamController`. 
-  It will be called by`startNodeIpamController` 

https://github.com/pacoxu/kubernetes/blob/67e12536f9ab516bf76e2402848d130952e2b79e/cmd/cloud-controller-manager/nodeipamcontroller.go#L57-L67

Comment (liggitt) [reply pkg/controller/nodeipam/node_ipam_controller.go:100]: if there's an error, I would expect it to be saved there and returned by the constructed InitFunc

Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller.go:100]: we discussed this some years ago, and we were concerned that there was something relying on this behavior, I mean, that the cloud-controller-manager crashed if the ipam wasn't working

**Comment by aojea** [comment]
> /approve /assign @bowei @sarveshr7
> 
> for final lgmt
> 
> @liggitt do you think that the s/klog.Fatal/panic/ can have any unexpected side effect?

/approve cancel

let's do this correctly as Jordan suggested @pacoxu , and return an error, it seems both ` kube-controller-manager` and ` cloud-controller-manager` do the right thing


https://github.com/kubernetes/kubernetes/blob/67e12536f9ab516bf76e2402848d130952e2b79e/cmd/kube-controller-manager/app/controllermanager.go#L232-L234

https://github.com/kubernetes/kubernetes/blob/67e12536f9ab516bf76e2402848d130952e2b79e/staging/src/k8s.io/cloud-provider/app/controllermanager.go#L201-L212

File: pkg/controller/nodeipam/node_ipam_controller.go (hunk 7 above)
Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller.go:100]: we should do as Jordan says https://github.com/kubernetes/kubernetes/pull/116174#issuecomment-1452105654

File: pkg/controller/nodeipam/legacyprovider.go (hunk 2 above)
Comment (aojea) [reply pkg/controller/nodeipam/legacyprovider.go:67]: agree, it seems the error is handling correctlly by the callers and fail to start the corresponding controller-manager

Comment (bowei) [reply pkg/controller/nodeipam/legacyprovider.go:67]: Let's fix this to bubble up the error.

File: pkg/controller/nodeipam/node_ipam_controller.go (hunk 7 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller.go]: I updated the PR to use error-return instead of panic.

File: pkg/controller/nodeipam/node_ipam_controller.go [hunk 8]
```diff
@@ -96,13 +97,13 @@ func NewNodeIpamController(
 	// Cloud CIDR allocator does not rely on clusterCIDR or nodeCIDRMaskSize for allocation.
```
Comment (liggitt) [inline pkg/controller/nodeipam/node_ipam_controller.go:97]: also change the Fatalf on line 93 above?

File: pkg/controller/nodeipam/nolegacyprovider.go [hunk 9]
```diff
@@ -43,7 +43,7 @@ func createLegacyIPAM(
 	clusterCIDRs []*net.IPNet,
 	serviceCIDR *net.IPNet,
 	nodeCIDRMaskSizes []int,
-) *fakeController {
+) (*fakeController, error) {
 	klog.Fatal("Error trying to Init(): legacy cloud provider support disabled at build time")
```
Comment (liggitt) [inline pkg/controller/nodeipam/nolegacyprovider.go:47]: return error instead of klog Fatal?

**Review by liggitt — COMMENTED** [review]
noted a couple other Fatals you might want to fix

File: pkg/controller/nodeipam/nolegacyprovider.go (hunk 9 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/nolegacyprovider.go]: Updated.

File: pkg/controller/nodeipam/node_ipam_controller.go (hunk 8 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller.go:97]: Updated.

File: pkg/controller/nodeipam/legacyprovider.go [hunk 10]
```diff
@@ -62,10 +63,10 @@ func createLegacyIPAM(
 	}
 	ipamc, err := ipam.NewController(cfg, kubeClient, cloud, cidr, serviceCIDR, nodeCIDRMaskSizes[0])
 	if err != nil {
-		klog.Fatalf("Error creating ipam controller: %v", err)
+		return nil, errors.Wrapf(err, "Error creating ipam controller")
 	}
 	if err := ipamc.Start(nodeInformer); err != nil {
-		klog.Fatalf("Error trying to Init(): %v", err)
+		return nil, errors.Wrapf(err, "Error trying to Init()")
```
Comment (pacoxu) [inline pkg/controller/nodeipam/legacyprovider.go:69]: updated here as well.

- other `klog.Fatal()` are in some other files under `pkg/controller/nodeipam/` 
image

File: pkg/controller/nodeipam/legacyprovider.go [hunk 11]
```diff
@@ -62,10 +63,10 @@ func createLegacyIPAM(
 	}
 	ipamc, err := ipam.NewController(cfg, kubeClient, cloud, cidr, serviceCIDR, nodeCIDRMaskSizes[0])
 	if err != nil {
-		klog.Fatalf("Error creating ipam controller: %v", err)
+		return nil, errors.Wrapf(err, "Error creating ipam controller")
```
Comment (aojea) [inline pkg/controller/nodeipam/legacyprovider.go:66]: I think that the new conventions is to use `fmt.Errorf("Error creating ipam controller: %w", err)`

```
Wrapping errors with %w
```
https://go.dev/blog/go1.13-errors

File: pkg/controller/nodeipam/node_ipam_controller.go [hunk 12]
```diff
@@ -90,19 +91,19 @@ func NewNodeIpamController(
...
 	if kubeClient == nil {
-		klog.Fatalf("kubeClient is nil when starting Controller")
+		return nil, errors.New("kubeClient is nil when starting Controller")
 	}
 
 	// Cloud CIDR allocator does not rely on clusterCIDR or nodeCIDRMaskSize for allocation.
 	if allocatorType != ipam.CloudAllocatorType {
 		if len(clusterCIDRs) == 0 {
-			klog.Fatal("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
+			return nil, errors.New("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
```
Comment (aojea) [inline pkg/controller/nodeipam/node_ipam_controller.go:100]:
```suggestion
			return nil, fmt.Errorf("Controller: Must specify --cluster-cidr if --allocate-node-cidrs is set")
```

File: pkg/controller/nodeipam/node_ipam_controller_test.go (hunk 6 above)
Comment (aojea) [reply pkg/controller/nodeipam/node_ipam_controller_test.go:83]: yeah, heh, I use the comments to not forget in the next review, sorry for the noise

File: pkg/controller/nodeipam/legacyprovider.go (hunk 11 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/legacyprovider.go]: Updated

File: pkg/controller/nodeipam/node_ipam_controller.go (hunk 12 above)
Comment (pacoxu) [reply pkg/controller/nodeipam/node_ipam_controller.go]: Updated similar errors in this function as well.

**Comment by aojea** [comment]
/lgtm
/approve 

Thanks

```
15m10s: 1440 runs so far, 0 failures
15m15s: 1440 runs so far, 0 failures
```
