### PR TITLE
Use Docker API Version instead of docker version

### LINKED ISSUE #42492: Kublet.log reports error with latest Docker version
To reproduce error:
Install latest Docker release..

first terminal:

sudo PATH=$PATH KUBERNETES_PROVIDER=local EXPERIMENTAL_CRI=true CONTAINER_RUNTIME=docker hack/local-up-cluster.sh

second terminal:
cat /tmp/kubelet.log|grep illegal

E0303 10:36:09.811626    1592 container_manager_linux.go:90] Unable to parse docker version "17.03.0-ce": illegal zero-prefixed version component "03" in "17.03.0-ce"

note docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Kubernetes version**:
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.0.746+1d97472361e611-dirty", GitCommit:"1d97472361e61106a1da1ce33da97f243e4d0441", GitTreeState:"dirty", BuildDate:"2017-03-02T22:50:43Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- local, vm developer environment:
- "Ubuntu" "16.04.2 LTS (Xenial Xerus)"
- Linux mike-VirtualBox 4.4.0-65-generic #86-Ubuntu SMP Thu Feb 23 17:49:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

So the code is correctly reporting a semantic versioning error based on the rule that none of the segments should have a leading zero. But we don't own Docker's versioning. So... should we call ParseGeneric vs ParseSemantic (in pkg/util/version/version.go) to disable semver testing, or do we PR docker and limit the number of versions we're compatible with based on this test, or do we change this to a warning or info level information in the parse routine? Seems like overkill to error on a leading zero.

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #42492
**Special notes for your reviewer**:

**Release note**:

`Update cadvisor to latest head to use docker APIversion exposed by cadvisor`

### CODE REVIEW

**Comment by mkumatag** [comment]
testlog @ https://gist.github.com/mkumatag/6eb2730fbe9f1c142b4426067689e4d7

Tested - 
- No errors in kubelet
- Deployed nginx pod, running fine without any errors.

File: pkg/kubelet/dockertools/docker_manager.go [hunk 1]
```diff
@@ -1095,7 +1095,7 @@ func (dm *DockerManager) pluginDisablesDockerNetworking() bool {
 
 // newDockerVersion returns a semantically versioned docker version value
```
Comment (mikebrow) [inline pkg/kubelet/dockertools/docker_manager.go]: Should read "newDockerVersion returns a generic version value (not semantic)"

Comment (mikebrow) [inline pkg/kubelet/dockertools/docker_manager.go]: Alternatively, might want to add a newDockerAPIVersion() API.

File: vendor/github.com/google/cadvisor/fs/fs.go [hunk 2]
```diff
@@ -149,6 +149,31 @@ func processMounts(mounts []*mount.Info, excludedMountpointPrefixes []string) ma
...
 		}
 
+		// btrfs fix: following workaround fixes wrong btrfs Major and Minor Ids reported in /proc/self/mountinfo.
+		// instead of using values from /proc/self/mountinfo we use stat to get Ids from btrfs mount point
+		if mount.Fstype == "btrfs" && mount.Major == 0 && strings.HasPrefix(mount.Source, "/dev/") {
+
+			buf := new(syscall.Stat_t)
+			err := syscall.Stat(mount.Source, buf)
+			if err != nil {
+				glog.Warningf("stat failed on %s with error: %s", mount.Source, err)
```
Comment (mikebrow) [inline vendor/github.com/google/cadvisor/fs/fs.go]: on mount source %s

File: vendor/github.com/google/cadvisor/fs/fs.go [hunk 3]
```diff
@@ -149,6 +149,31 @@ func processMounts(mounts []*mount.Info, excludedMountpointPrefixes []string) ma
...
+			} else {
+				glog.Infof("btrfs mount %#v", mount)
+				if buf.Mode&syscall.S_IFMT == syscall.S_IFBLK {
+					err := syscall.Stat(mount.Mountpoint, buf)
+					if err != nil {
+						glog.Warningf("stat failed on %s with error: %s", mount.Mountpoint, err)
```
Comment (mikebrow) [inline vendor/github.com/google/cadvisor/fs/fs.go]: on mount point %s

**Review by mikebrow — COMMENTED** [review]
Looks good to me, just a few Minor nits.

File: vendor/github.com/google/cadvisor/fs/fs.go (hunk 3 above)
Comment (mkumatag) [inline vendor/github.com/google/cadvisor/fs/fs.go]: As this is a godep stuff, we can submit a PR in cadvisor to get this message fixed.!

File: vendor/github.com/google/cadvisor/fs/fs.go (hunk 2 above)
Comment (mkumatag) [inline vendor/github.com/google/cadvisor/fs/fs.go]: As this is a godep stuff, we can submit a PR in cadvisor to get this message fixed.!

File: pkg/kubelet/dockertools/docker_manager.go (hunk 1 above)
Comment (mkumatag) [inline pkg/kubelet/dockertools/docker_manager.go]: I don't see anyone is using this function at all! except docker_manager_test.go. If no objection from anyone, I would like to remove this function completely.

File: vendor/github.com/google/cadvisor/fs/fs.go (hunk 2 above)
Comment (mikebrow) [inline vendor/github.com/google/cadvisor/fs/fs.go]: ah vendor.. :-)

File: pkg/kubelet/dockertools/docker_manager.go (hunk 1 above)
Comment (mikebrow) [inline pkg/kubelet/dockertools/docker_manager.go]: It's used just below on line number 1128 other than that yeah it doesn't seem to be used.

Comment (mikebrow) [inline pkg/kubelet/dockertools/docker_manager.go]: Which brings up a possible issue..?  Version() and APIVersion() returning the same value.

Comment (mkumatag) [inline pkg/kubelet/dockertools/docker_manager.go]: you are right! it is used in Version function, I'll leave this function as is and lemme modify the description. We will add newDockerAPIVersion when somebody really need it!

**Review by mikebrow — CHANGES_REQUESTED** [review]
What do you think about updating the test cases in docker_manager_test.go to cover the new date based versions? Specifically adding one that is not semver compatible like 17.01.03

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by mkumatag** [comment]
I suspect some tests failures in docker_manager_test.go and few more, will work on them and update this PR..

**Comment by yujuhong** [comment]
> I suspect some tests failures in docker_manager_test.go and few more, will work on them and update this PR..

I'd suggest leave docker_manager and its unit tests alone. They are going away soon (see #43884).

**Comment by mkumatag** [comment]
> I'd suggest leave docker_manager and its unit tests alone. They are going away soon (see #43884).

In that case lemme rollback the changes on docker_manager file

**Comment by mkumatag** [comment]
@yujuhong rollbacked the changes from docker_manager and all the checks passed.! can you PTAL at this PR?

File: pkg/kubelet/cadvisor/cadvisor_linux.go [hunk 4]
```diff
@@ -95,10 +95,7 @@ func containerLabels(c *cadvisorapi.ContainerInfo) map[string]string {
 
 // New creates a cAdvisor and exports its API on the specified port if port > 0.
 func New(port uint, runtime string, rootPath string) (Interface, error) {
-	sysFs, err := sysfs.NewRealSysFs()
-	if err != nil {
-		return nil, err
-	}
+	sysFs := sysfs.NewRealSysFs()
```
Comment (yujuhong) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: Why removing the error check?

Comment (mkumatag) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: thats because in recent version there is change in NewRealSysFS function, check this out for more information - https://github.com/google/cadvisor/pull/1578

Comment (mikebrow) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: Gotta love empty structs :-)

Comment (yujuhong) [inline pkg/kubelet/cadvisor/cadvisor_linux.go]: Ah I see. I reviewed only the second commit, hence the question.

**Comment by yujuhong** [comment]
The second commit LGTM.

I think you'll need to add a release note since this bumps the cadvisor version. @dashpole, do you want to look at the cadvisor version bump?

**Comment by mkumatag** [comment]
ping @dashpole

**Comment by dashpole** [comment]
The first commit LGTM!

**Comment by yujuhong** [comment]
> The first commit LGTM!

Thanks!

@mksalawa need to rebase and add a release note.

**Comment by mkumatag** [comment]
@yujuhong I just did a rebase, please help me with release note - I'm not really sure what to put.!!!

**Comment by yujuhong** [comment]
> @yujuhong I just did a rebase, please help me with release note - I'm not really sure what to put.!!!

Hers is an example: #33052

**Comment by mkumatag** [comment]
@yujuhong not really sure what version I need to mention here for cadvisor because I don't see any new release in cadvisor with my fix. @dashpole can we get a new release for cadvisor with https://github.com/google/cadvisor/pull/1623

**Comment by dashpole** [comment]
Since we are not updating to a tagged release, you dont need to put that in the release notes.  Usually, we put release notes from all recent cAdvisor PRs into the release notes here;  however, no cAdvisor PRs have had release notes since v0.25.0.  So just add the release note for this PR.

**Comment by mkumatag** [comment]
Thanks @dashpole , updated the release notes @yujuhong. PTAL.

**Comment by yujuhong** [comment]
/lgtm

Sorry I closed this by accident :\

/cc @dchen1107 for approval

**Comment by mkumatag** [comment]
@dchen1107 ping

**Comment by soltysh** [comment]
@mkumatag any chance for the rebase?

**Comment by mkumatag** [comment]
@soltysh done. Can you please help me merging this PR?

**Comment by soltysh** [comment]
@mkumatag make sure the CI is green first, I'll take a look at this PR later today or tomorrow at latest and make sure to have it merge if it's ok

**Comment by mkumatag** [comment]
@mikedanese @ixdy I see some failures for bazel-test but hack/verify passes locally. Any idea what is wrong here? btw: I'm using go1.8.1 version

**Comment by mkumatag** [comment]
@k8s-bot bazel test this

**Comment by dashpole** [comment]
looks like the error is in a BUILD file.  did you run ./hack/update-bazel?

**Comment by mkumatag** [comment]
Yes, I did.. the file got updated result of that script run.
> looks like the error is in a BUILD file. did you run ./hack/update-bazel?

**Comment by mikedanese** [comment]
@mkumatag not sure what is going on but you need to revert your changes to vendor/BUILD. Looks like a weird rebase. Can you do this:
```console
# make sure your master is current
$ git checkout k8s_add_apiversion
$ git checkout master -- vendor/BUILD
$ ./hack/update-bazel.sh
```

**Comment by mikedanese** [comment]
If that doesn't work, ping me and I'll push a fix to your branch.

**Comment by mkumatag** [comment]
Thanks @mikedanese it worked..

**Comment by ixdy** [comment]
looks like another case fixed by https://github.com/mikedanese/gazel/pull/38. we should probably update gazel.

**Comment by yujuhong** [comment]
Ping a couple of folks for approval: @dchen1107 @thockin @smarterclayton

**Comment by dchen1107** [comment]
/lgtm 

and 
/approve

**Comment by mkumatag** [comment]
@k8s-bot verify test this
