### PR TITLE
kubelet(OOM-score-adj): change OOM score adjustment calculation for sidecar container

### LINKED ISSUE #111356: The logic of oom_score_adj doesn't work well for sidecar containers
### What happened?

I was debugging a OOM failure recently and noticed some unexpected behavior for how the kubelet is setting `oom_score_adj`.

From the [Node-pressure Eviction documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/) this is how setting `oom_score_adj` is described for burstable QoS pods:

> min(max(2, 1000 - (1000 * memoryRequestBytes) / machineMemoryCapacityBytes), 999)

The documentation also states the intention of this calculation is:

> This means that containers in low QoS pods that consume a large amount of memory relative to their scheduling requests are killed first.

However the calculation actually does the opposite. For processes that request a small amount of memory the `(1000 * memoryRequestBytes) / machineMemoryCapacityBytes` ratio approaches zero, meaning the calculation ends up being: `min(max(2, 1000 - 0), 999) = 999`

Similarly, when the requested memory increases and the ratio approaches the total size of the machine the calculation becomes: `min(max(2, 1000 - 1000), 999) = 2`

This means that containers that are using the smallest amount of the machine get the highest score adjustment which makes the smallest processes killed first. I observed this in practice while looking at the kernel's OOM logs. These are the set of processes the OOM killer was logging:

```
kernel: Tasks state (memory values in pages):
kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
kernel: [  10325]     0 10325      242        1    28672        0          -998 pause
kernel: [  11029]     0 11029   185553     4518   212992        0          -997 node-cache
kernel: [  10189]     0 10189      242        1    28672        0          -998 pause
kernel: [  11651]     0 11651     2890      117    65536        0          -997 bash
kernel: [  11692]     0 11692   191867    11673   303104        0          -997 aws-k8s-agent
kernel: [  11693]     0 11693     1060       16    57344        0          -997 tee
kernel: [   9998]     0  9998      242        1    28672        0          -998 pause
kernel: [  10857]     0 10857   188700     7795   249856        0          -998 kube-proxy
kernel: [  10115]     0 10115      242        1    24576        0          -998 pause
kernel: [  11256]  1000 11256   186562     2695   192512        0          -997 node-terminatio
kernel: [  14406]     0 14406      242        1    28672        0          -998 pause
kernel: [  16187]   100 16187   213158    20546   421888        0          -997 vault
kernel: [  14897]     0 14897      242        1    24576        0          -998 pause
kernel: [  14393]     0 14393      242        1    28672        0          -998 pause
kernel: [  15195]     0 15195  4690740  4301599 36208640        0          -997 logger
kernel: [  15717]     0 15717      242        1    28672        0          -998 pause
kernel: [  16487]     0 16487   187806     6452   217088        0          -997 herdmonitor
kernel: [   1474] 65534  1474      242        1    28672        0          -998 pause
kernel: [   5070] 65534  5070   180050     2762   135168        0           999 node_exporter
kernel: [  25878]     0 25878      242        1    28672        0          -998 pause
kernel: [  27296]     0 27296   184151     3800   192512        0           121 taskhost
kernel: [  27532]     0 27532   187011    11328   217088        0           121 run_sim_stack
kernel: [  27533]     0 27533   187011    11552   217088        0           121 run_sim_stack
kernel: [  27541]     0 27541   187139    11272   212992        0           121 run_sim_stack
kernel: [  27544]     0 27544   186819    11890   221184        0           121 run_sim_stack
kernel: [  27549]     0 27549   187011    11692   212992        0           121 run_sim_stack
kernel: [  27555]     0 27555   187011    11270   221184        0           121 run_sim_stack
kernel: [  27560]     0 27560   187011    11286   208896        0           121 run_sim_stack
kernel: [  27676]     0 27676   213898    10619   708608        0           121 stack_run
kernel: [  27681]     0 27681   283022    12289   815104        0           121 stack_run
kernel: [  27684]     0 27684   306570    11785  1413120        0           121 stack_run
kernel: [  27775]     0 27775   213898    10586   708608        0           121 stack_run
kernel: [  27838]     0 27838   217994    10748   704512        0           121 stack_run
kernel: [  27899]     0 27899   213898    10676   696320        0           121 stack_run
kernel: [  27963]     0 27963   207241    10588   696320        0           121 stack_run
kernel: [  28211]     0 28211  4636176  3709004 32600064        0           121 offline_main_pl
kernel: [  28212]     0 28212  4649424  3709621 32579584        0           121 offline_main_pl
kernel: [  28213]     0 28213  4635152  3701721 32612352        0           121 offline_main_pl
kernel: [  28214]     0 28214  4606542  3697740 32481280        0           121 offline_main_pl
kernel: [  28215]     0 28215  4638672  3713963 32645120        0           121 offline_main_pl
kernel: [  28216]     0 28216  4627408  3697821 32559104        0           121 offline_main_pl
kernel: [  28217]     0 28217  4632271  3716409 32641024        0           121 offline_main_pl
kernel: [  27390]     0 27390   183959     2534   176128        0           999 taskhost
kernel: [  27447]     0 27447   212069    20873   413696        0           999 vault
```

Due to the `999` value of `oom_score_adj` processes in the `vault` container were killed first, despite having the smallest resource request and the smallest memory footprint.

### What did you expect to happen?

I expected that containers that are using a larger portion of the machine to have `oom_score_adj` set to a higher value than containers that are using a small portion of the machine. This matches the intentions stated in the existing documentation. Changing the calculation to this should have that intended effect:

```
min(max(2, 1000 * memoryRequestBytes / machineMemoryCapacityBytes), 999)
```

With that change as the ratio of requested memory approaches the entire machine the value will approach 999, which will make the OOM killer most likely to target those processes.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a burstable QoS pod that requests and uses a small amount of memory.
2. Create a burstable pod that requests a large amount of memory and has a memory leak that will eventually trigger the OOM killer.
3. Look at the OOM killer kernel logs and see that the small pod was targeted first.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-10-35-95-93.swe.cloud.aurora.tech 5.4.190-107.353.amzn2.x86_64 #1 SMP Wed Apr 27 21:16:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
kernel: 5.4.190-107.353.amzn2
dockerd: 20.10.13-2.amzn2
containerd: 1.4.13-2.amzn2.0.1
runc: 1.0.3-2.amzn2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bouaouda-achraf**
/kind feature
/sig node
/triage accepted

#### What this PR does / why we need it:
calculate the sidecar oom score adjustment based on: max-memory( currentSideCarContainer , min -memory(regular containers) ) .

the OOM adjustment for these containers will match or fall below the OOM score adjustment of regular containers in the Pod. 

#### Which issue(s) this PR fixes:
*Automatically closes linked issue when PR is merged.
Usage: `Fixes https://github.com/kubernetes/kubernetes/issues/111356 .

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Change OOM score adjustment calculation for sidecar container : the OOM adjustment for these containers will match or fall below the OOM score adjustment of regular containers in the Pod.
```

### CODE REVIEW

**Comment by bouaouda-achraf** [comment]
/retest-required
( flaky test )

File: pkg/kubelet/qos/policy.go [hunk 1]
```diff
@@ -20,6 +20,7 @@ import (
 	v1 "k8s.io/api/core/v1"
```
Comment (toVersus) [inline pkg/kubelet/qos/policy.go:20]: This changes the existing logic, so wouldn’t we need an escape hatch, like checking a FeatureGate of Sidecar Containers? Since Sidecar Containers have already been promoted to beta, and this change will also affect non-Sidecar Containers, I’m not sure if it’s the right choice.

/cc @SergeyKanzhelev

File: pkg/kubelet/qos/policy.go [hunk 2]
```diff
@@ -62,13 +63,18 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
...
 	if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
 		if cs, ok := podutil.GetContainerStatus(pod.Status.ContainerStatuses, container.Name); ok {
-			memoryRequest = cs.AllocatedResources.Memory().Value()
+			containerMemoryRequest = cs.AllocatedResources.Memory().Value()
 		}
 	}
-	oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity
+	// The OOM score is calculated based on an equal balance
+	// between the container request (50%) and the pod request (50%)
+	oomScoreAdjust := 1000 - (((500 * containerMemoryRequest) / memoryCapacity) + ((500 * podMemoryRequest) / memoryCapacity))
```
Comment (toVersus) [inline pkg/kubelet/qos/policy.go:77]: Why did you choose this calculation logic? While there's a issue of how to set the threshold, I think it could have been done using the calculation logic suggested in Sergey's comment.

> Perhaps, use the entire pod's OOM score adjustment for the containers when those containers are requesting a fraction of memory of the entire pod's request.

File: pkg/kubelet/qos/policy_test.go [hunk 3]
```diff
@@ -229,6 +264,24 @@ func TestGetContainerOOMScoreAdjust(t *testing.T) {
 			lowOOMScoreAdj:  -997,
 			highOOMScoreAdj: -997,
 		},
+		{ // low and high range differ from burstableMultiContainerMediumPod & burstableMultiContainerLargePod
```
Comment (toVersus) [inline pkg/kubelet/qos/policy_test.go:267]: I think it would be better to have test cases that include regular Init Containers and restartable Init Containers.

File: pkg/kubelet/qos/policy.go (hunk 2 above)
Comment (ffromani) [reply pkg/kubelet/qos/policy.go:77]: I concur that changing the logic deserves an explicit reference about the algorithm.
IIUC this change is needed by the sidecar containers, but it seems it can affects all the workloads, thus some extra care is warranted.

**Review by ffromani — COMMENTED** [review]
thanks for the PR! it's usually best practice to avoid self-triage-accepting PRs, please consider this next time

File: pkg/kubelet/qos/policy_test.go (hunk 3 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy_test.go:267]: The current and previous logic do not account for init containers **in the calculation.** Do you think it would be a good idea to include init containers in the tests?

File: pkg/kubelet/qos/policy.go (hunk 2 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go:77]: In the case of a single container, containerMemoryRequest is approximately equal to podMemoryRequest (same logic).
For a multi-container pod, the OOM score adjustment is calculated as: 50% based on the container’s request + 50% based on the pod’s total request.
In my opinion, the new logic provides good behavior for both types of workloads (sidecar and non-sidecar), especially when distinguishing between larger and smaller pods.

I’m open to any feedback you may have.

File: pkg/kubelet/qos/policy_test.go (hunk 3 above)
Comment (toVersus) [reply pkg/kubelet/qos/policy_test.go:267]: Since you modified it to include `PodRequests()` in the calculations, doesn’t this mean that Regular / Restartable Init Containers also now affect the calculations?

Comment (toVersus) [reply pkg/kubelet/qos/policy_test.go:267]: Isn't `GetContainerOOMScoreAdjust()` originally supposed to be executed for Init Containers and also for Ephemeral Containers as well?

File: pkg/kubelet/qos/policy.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/qos/policy.go:20]: Yes, the new logic must be under the sidecar feature gate

**Comment by SergeyKanzhelev** [comment]
@bouaouda-achraf thank you for your PR. Last discussions we had was to apply the new calcualtion only to sidecars.

The logic is that oom score for the sidecar should be the best number of it's own calculation and the minimal best oom score of any regular container. So it will be killed no more than the worst regular container.

File: pkg/kubelet/qos/policy_test.go (hunk 3 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy_test.go:328]: I agree, I added some tests related to these cases.

File: pkg/kubelet/qos/policy.go (hunk 1 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go:20]: Done

**Comment by bouaouda-achraf** [comment]
> > @bouaouda-achraf thank you for your PR. Last discussions we had was to apply the new calcualtion only to sidecars.
> 
> > 
> 
> > The logic is that oom score for the sidecar should be the best number of it's own calculation and the minimal best oom score of any regular container. So it will be killed no more than the worst regular container.
> 
> 
> 
> Thanks for your feedback, I will update the existing PR: When dealing with a sidecar container: calculate the Oom score adjustment based on: min-memory( **current**SideCarContainer , min -memory(regular container**s**) ) . 
> 
> when Oom score adj **current**SideCarContainer == Oom score adj min-memory(regular container**s**) I will add 1 to the sidecar container oom score adj  (first to kill).

Implemented

File: pkg/kubelet/qos/policy.go [hunk 4]
```diff
@@ -62,13 +65,44 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
...
+	containerMemoryRequest := container.Resources.Requests.Memory().Value()
+
+	isInPlacePodVerticalScaling := utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling)
+	if isInPlacePodVerticalScaling {
 		if cs, ok := podutil.GetContainerStatus(pod.Status.ContainerStatuses, container.Name); ok {
-			memoryRequest = cs.AllocatedResources.Memory().Value()
+			containerMemoryRequest = cs.AllocatedResources.Memory().Value()
+		}
+	}
+	oomScoreAdjust := 1000 - (1000*containerMemoryRequest)/memoryCapacity
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:76]: please avoid variables renaming here. It will be easier to understand that the code was not changed and will not hurt the readability

File: pkg/api/v1/resource/helpers.go [hunk 5]
```diff
@@ -248,6 +248,61 @@ func max(a v1.ResourceList, b v1.ResourceList) v1.ResourceList {
 	return result
 }
 
+// MinRegularContainerResourceList returns the minimum resource requests for each named resource
+// across all regular containers in pod.Spec.Containers.
+// It does not include initContainers (both restartable and non-restartable).
+func MinRegularContainerResourceList(pod v1.Pod, opts PodResourcesOptions) v1.ResourceList {
```
Comment (SergeyKanzhelev) [inline pkg/api/v1/resource/helpers.go:254]: I don't see a reason to make it a part of an API. Keep it as a local helper function under the kubelet/qos

File: pkg/kubelet/qos/policy.go (hunk 4 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/qos/policy.go:76]: Ideally just keep the code as-is even if it costs to re-check the feature gate value

File: pkg/kubelet/qos/policy.go [hunk 6]
```diff
@@ -80,3 +114,12 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
 	}
 	return int(oomScoreAdjust)
 }
+
+func isSidecarContainer(pod *v1.Pod, container *v1.Container) bool {
+	for _, initContainer := range pod.Spec.InitContainers {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:119]: please add a comment here saying that we need this funny loop because we do not have information about the container type in this function.

I am generally fine to keep it this way. We may need to consider passing container type as an argtument in future. But it will touch so much code that may not worth it now.

File: pkg/kubelet/qos/policy.go [hunk 7]
```diff
@@ -62,13 +65,44 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
...
+			containerMemoryRequest = cs.AllocatedResources.Memory().Value()
+		}
+	}
+	oomScoreAdjust := 1000 - (1000*containerMemoryRequest)/memoryCapacity
+
+	// adapt the sidecarContainer memoryRequest for OOM ADJ calculation
+	// calculate the oom score adjustment based on: min-memory( currentSideCarContainer , min-memory(regular containers) ) .
+	if utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) && isSidecarContainer(pod, container) {
+		// check min resources with regular containers
+		minResourceList := resourcehelper.MinRegularContainerResourceList(*pod, resourcehelper.PodResourcesOptions{
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:82]: this is over generalized. Hard to read. You only need the minimal memory here.

File: pkg/kubelet/qos/policy.go (hunk 6 above)
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:119]: you can only run this loop if the restartPolicy is configured for the container. Something like:

```
if container.RestartPolicy != nil && *container.RestartPolicy == v1.ContainerRestartPolicyAlways {
  // check that it is actually an init container
  for _, initContainer := range pod.Spec.InitContainers {
  if name matches, return true.
}
```

**Comment by SergeyKanzhelev** [comment]
Algorithmically looks ok, thank you for expanding the tests. 

Code is over-generalized and I suggested an optimization.

File: pkg/kubelet/qos/policy_test.go [hunk 8]
```diff
@@ -159,81 +171,270 @@ var (
...
-	memoryCapacity  int64
-	lowOOMScoreAdj  int // The max oom_score_adj score the container should be assigned.
-	highOOMScoreAdj int // The min oom_score_adj score the container should be assigned.
+	pod                             *v1.Pod
+	memoryCapacity                  int64
+	lowHighOOMScoreAdj              map[string]lowHighOOMScoreAdjTest // [container-name] : min and max oom_score_adj score the container should be assigned.
+	sidecarContainersFeatureEnabled bool
 }
 
 func TestGetContainerOOMScoreAdjust(t *testing.T) {
```
Comment (toVersus) [inline pkg/kubelet/qos/policy_test.go:316]: Since it's a little hard to see which test failed, could you add the test name? Something like this.

```diff
diff --git a/pkg/kubelet/qos/policy_test.go b/pkg/kubelet/qos/policy_test.go
index 90c4cae5628..862add6ecc0 100644
--- a/pkg/kubelet/qos/policy_test.go
+++ b/pkg/kubelet/qos/policy_test.go
@@ -314,71 +314,71 @@ type oomTest struct {
 }

 func TestGetContainerOOMScoreAdjust(t *testing.T) {
-       oomTests := []oomTest{
-               {
+       oomTests := map[string]oomTest{
+               "cpu-limit": {
                        pod:            &cpuLimit,
                        memoryCapacity: 4000000000,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "cpu-limit": {lowOOMScoreAdj: 999, highOOMScoreAdj: 999},
                        },
                },
-               {
+               "memory-limit-cpu-request": {
                        pod:            &memoryLimitCPURequest,
                        memoryCapacity: 8000000000,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "memory-limit-cpu-request": {lowOOMScoreAdj: 999, highOOMScoreAdj: 999},
                        },
                },
-               {
+               "zero-memory-limit": {
                        pod:            &zeroMemoryLimit,
                        memoryCapacity: 7230457451,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "zero-memory-limit": {lowOOMScoreAdj: 1000, highOOMScoreAdj: 1000},
                        },
                },
-               {
+               "no-request-limit": {
                        pod:            &noRequestLimit,
                        memoryCapacity: 4000000000,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "no-request-limit": {lowOOMScoreAdj: 1000, highOOMScoreAdj: 1000},
                        },
                },
-               {
+               "equal-request-limit-cpu-memory": {
                        pod:            &equalRequestLimitCPUMemory,
                        memoryCapacity: 123456789,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "equal-request-limit-cpu-memory": {lowOOMScoreAdj: -997, highOOMScoreAdj: -997},
                        },
                },
-               {
+               "cpu-unlimited-memory-limited-with-requests": {
                        pod:            &cpuUnlimitedMemoryLimitedWithRequests,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "cpu-unlimited-memory-limited-with-requests": {lowOOMScoreAdj: 495, highOOMScoreAdj: 505},
                        },
                },
-               {
+               "request-no-limit": {
                        pod:            &requestNoLimit,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "request-no-limit": {lowOOMScoreAdj: 3, highOOMScoreAdj: 3},
                        },
                },
-               {
+               "cluster-critical": {
                        pod:            &clusterCritical,
                        memoryCapacity: 4000000000,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "cluster-critical": {lowOOMScoreAdj: 1000, highOOMScoreAdj: 1000},
                        },
                },
-               {
+               "node-critical": {
                        pod:            &nodeCritical,
                        memoryCapacity: 4000000000,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "node-critical": {lowOOMScoreAdj: -997, highOOMScoreAdj: -997},
                        },
                },
-               {
+               "burstable-unique-container-pod": {
                        pod:            &burstableUniqueContainerPod,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
@@ -386,7 +386,7 @@ func TestGetContainerOOMScoreAdjust(t *testing.T) {
                        },
                        sidecarContainersFeatureEnabled: true,
                },
-               {
+               "burstable-mixed-unique-main-container-pod": {
                        pod:            &burstableMixedUniqueMainContainerPod,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
@@ -395,17 +395,17 @@ func TestGetContainerOOMScoreAdjust(t *testing.T) {
                        },
                        sidecarContainersFeatureEnabled: true,
                },
-               {
+               "burstable-mixed-multi-container-small-sidecar-pod": {
                        pod:            &burstableMixedMultiContainerSmallSideCarePod,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
                                "init-container":          {lowOOMScoreAdj: 875, highOOMScoreAdj: 880},
                                "sidecar-small-container": {lowOOMScoreAdj: 951, highOOMScoreAdj: 951}, // first to kill
-                               "main-1":                  {lowOOMScoreAdj: 875, highOOMScoreAdj: 875},
+                               "main-1":                  {lowOOMScoreAdj: 875, highOOMScoreAdj: 880},
                        },
                        sidecarContainersFeatureEnabled: true,
                },
-               {
+               "burstable-mixed-multi-container-sample-request-pod": {
                        pod:            &burstableMixedMultiContainerSameRequestPod,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
@@ -415,7 +415,7 @@ func TestGetContainerOOMScoreAdjust(t *testing.T) {
                        },
                        sidecarContainersFeatureEnabled: true,
                },
-               {
+               "burstable-mixed-multi-container-big-sidecar-container-pod": {
                        pod:            &burstableMixedMultiContainerBigSidecarContainerPod,
                        memoryCapacity: standardMemoryAmount,
                        lowHighOOMScoreAdj: map[string]lowHighOOMScoreAdjTest{
@@ -426,15 +426,18 @@ func TestGetContainerOOMScoreAdjust(t *testing.T) {
                        sidecarContainersFeatureEnabled: true,
                },
        }
-       for _, test := range oomTests {
-               featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, test.sidecarContainersFeatureEnabled)
-               listContainers := test.pod.Spec.InitContainers
-               listContainers = append(listContainers, test.pod.Spec.Containers...)
-               for _, container := range listContainers {
-                       oomScoreAdj := GetContainerOOMScoreAdjust(test.pod, &container, test.memoryCapacity)
-                       if oomScoreAdj < test.lowHighOOMScoreAdj[container.Name].lowOOMScoreAdj || oomScoreAdj > test.lowHighOOMScoreAdj[container.Name].highOOMScoreAdj {
-                               t.Errorf("oom_score_adj %s should be between %d and %d, but was %d", container.Name, test.lowHighOOMScoreAdj[container.Name].lowOOMScoreAdj, test.lowHighOOMScoreAdj[container.Name].highOOMScoreAdj, oomScoreAdj)
+       for name, test := range oomTests {
+               t.Run(name, func(t *testing.T) {
+                       featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, test.sidecarContainersFeatureEnabled)
+                       listContainers := test.pod.Spec.InitContainers
+                       listContainers = append(listContainers, test.pod.Spec.Containers...)
+                       for _, container := range listContainers {
+                               oomScoreAdj := GetContainerOOMScoreAdjust(test.pod, &container, test.memoryCapacity)
+                               if oomScoreAdj < test.lowHighOOMScoreAdj[container.Name].lowOOMScoreAdj || oomScoreAdj > test.lowHighOOMScoreAdj[container.Name].highOOMScoreAdj {
+                                       t.Errorf("oom_score_adj %s should be between %d and %d, but was %d", container.Name, test.lowHighOOMScoreAdj[container.Name].lowOOMScoreAdj, test.lowHighOOMScoreAdj[container.Name].highOOMScoreAdj, oomScoreAdj)
+                               }
+                               t.Logf("[%s]: oomScoreAdj: %d", container.Name, oomScoreAdj)
                        }
-               }
+               })
        }
 }
```

File: pkg/kubelet/qos/policy_test.go [hunk 9]
```diff
@@ -159,81 +171,270 @@ var (
...
+		Spec: v1.PodSpec{
+			InitContainers: []v1.Container{
+				sampleInitContainer, sampleSidecarContainer,
+			}, Containers: []v1.Container{
+				sampleContainer,
+			},
+		},
+	}
+
+	burstableMixedMultiContainerSmallSideCarePod = v1.Pod{
```
Comment (toVersus) [inline pkg/kubelet/qos/policy_test.go:284]: nit:

```suggestion
	burstableMixedMultiContainerSmallSidecarPod = v1.Pod{
```

File: pkg/kubelet/qos/policy_test.go [hunk 10]
```diff
@@ -159,81 +171,270 @@ var (
...
 	for _, test := range oomTests {
-		oomScoreAdj := GetContainerOOMScoreAdjust(test.pod, &test.pod.Spec.Containers[0], test.memoryCapacity)
-		if oomScoreAdj < test.lowOOMScoreAdj || oomScoreAdj > test.highOOMScoreAdj {
-			t.Errorf("oom_score_adj should be between %d and %d, but was %d", test.lowOOMScoreAdj, test.highOOMScoreAdj, oomScoreAdj)
+		featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, test.sidecarContainersFeatureEnabled)
+		listContainers := test.pod.Spec.InitContainers
+		listContainers = append(listContainers, test.pod.Spec.Containers...)
+		for _, container := range listContainers {
+			oomScoreAdj := GetContainerOOMScoreAdjust(test.pod, &container, test.memoryCapacity)
+			if oomScoreAdj < test.lowHighOOMScoreAdj[container.Name].lowOOMScoreAdj || oomScoreAdj > test.lowHighOOMScoreAdj[container.Name].highOOMScoreAdj {
```
Comment (toVersus) [inline pkg/kubelet/qos/policy_test.go:435]: This might be a silly question, but why do you allow specifying both a low and high oomScoreAdj for each container in the test? I noticed that you're checking if the oomScoreAdj calculated for each container falls between the low and high values, but I'm curious why you're not checking if the value itself matches exactly.

File: pkg/kubelet/qos/policy_test.go (hunk 8 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy_test.go:316]: Done

File: pkg/kubelet/qos/policy.go (hunk 4 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go]: Done

File: pkg/kubelet/qos/policy.go (hunk 6 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go]: Done

Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go]: Done

File: pkg/kubelet/qos/policy_test.go (hunk 9 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy_test.go]: Done

File: pkg/kubelet/qos/policy_test.go (hunk 10 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy_test.go]: I agree, but I initially didn’t want to modify the existing logic.

File: pkg/kubelet/qos/policy.go [hunk 11]
```diff
@@ -63,12 +63,33 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
...
 	oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity
+
+	// adapt the sidecarContainer memoryRequest for OOM ADJ calculation
+	// calculate the oom score adjustment based on: min-memory( currentSideCarContainer , min-memory(regular containers) ) .
+	if utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) && isSidecarContainer(pod, container) {
+		// check min memory quantity in regular containers
+		minMemoryRequest := minRegularContainerMemory(*pod)
+		// check min memory quantity with the current sidecarContainer
+		// inPlacePodVerticalScaling is not possible for the moment in InitContainers
+		if minMemoryRequest > container.Resources.Requests.Memory().Value() {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:81]: is it accurate? I think we need to take `minMemoryRequest` if is it greater than the sidecar's memory. We want to keep sidecar's oom score if it is better than any of containers inside the Pod. And if it is worse than all containers inside the pod, take the minimum of containers

File: pkg/kubelet/qos/policy.go (hunk 7 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go]: done

File: pkg/api/v1/resource/helpers.go (hunk 5 above)
Comment (bouaouda-achraf) [reply pkg/api/v1/resource/helpers.go]: done

File: pkg/kubelet/qos/policy.go (hunk 11 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go:81]: thanks for your feedback . 
```go
		// check min memory quantity in regular containers
		minMemoryRequest := minRegularContainerMemory(*pod)
		// check min memory quantity with the current sidecarContainer
		// inPlacePodVerticalScaling is not possible for the moment in InitContainers
		if minMemoryRequest > container.Resources.Requests.Memory().Value() {
			minMemoryRequest = container.Resources.Requests.Memory().Value()
		}
```

in the first step I calculate the minimum memory in all regular containers then I check this memory with the current container (sidecar)  : min ( memory all regular containers,   memory sidecar container)  .

Normally I use the minimum.

Comment (SergeyKanzhelev) [reply pkg/kubelet/qos/policy.go:81]: but this logic is wrong. You need to take max out of minimal container memory and the sidecars memory. This will give you the best score.

The logic we want is - sidecar's OOM score is NO WORSE then the WORST score of all containers.

Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go:81]: > You need to take max out of minimal container memory and the sidecars memory. This will give you the best score.

as a result the behavior on big sidecar container will be : 

   sidecar :   400Mi
   main-1 :   200Mi
   main-2:    100Mi

**max** out of (minimal container memory and the sidecars memory): 400Mi   
    score adj **sidecar**  **<**  score adj  main  
( oomScoreAdjust = 1000 - (1000*memoryRequest)/memoryCapacity )

> The logic we want is - sidecar's OOM score is NO WORSE then the WORST score of all containers.  

I will remove this : 
```go
		// when OOM score adj currentSideCarContainer <= oom score adj min-memory(regular containers)
		// ==> add 1 to the sidecar container oom score adj (first to kill).
		if minMemoryRequest <= container.Resources.Requests.Memory().Value() {
			oomScoreAdjust += 1
		}
```

File: pkg/kubelet/qos/policy_test.go (hunk 10 above)
Comment (toVersus) [reply pkg/kubelet/qos/policy_test.go]: I see, I'm glad to know my understanding is correct :)
I'll leave it up to you whether to make changes in this PR.

File: pkg/kubelet/qos/helpers.go [hunk 12]
```diff
@@ -0,0 +1,65 @@
+/*
+Copyright 2015 The Kubernetes Authors.
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/helpers.go:2]:
```suggestion
Copyright 2024 The Kubernetes Authors.
```

File: pkg/kubelet/qos/policy.go (hunk 11 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/qos/policy.go:81]: So the end goal is to make sidecar's behavior as the following:

1. If probability of OOM-killing sidecar is less then at least one regular containers, keep the old formulae
2. If probability of OOM-killing is higher then all regular containers, use the same probability as the worst container from regular containers

File: pkg/kubelet/qos/helpers.go (hunk 12 above)
Comment (bouaouda-achraf) [reply pkg/kubelet/qos/helpers.go]: Fixed

File: pkg/kubelet/qos/policy.go [hunk 13]
```diff
@@ -63,12 +63,27 @@ func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapa
...
+
 	if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
 		if cs, ok := podutil.GetContainerStatus(pod.Status.ContainerStatuses, container.Name); ok {
 			memoryRequest = cs.AllocatedResources.Memory().Value()
 		}
 	}
 	oomScoreAdjust := 1000 - (1000*memoryRequest)/memoryCapacity
+
+	// adapt the sidecarContainer memoryRequest for OOM ADJ calculation
+	// calculate the oom score adjustment based on: min-memory( currentSideCarContainer , min-memory(regular containers) ) .
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/policy.go:75]:
```suggestion
	// calculate the oom score adjustment based on: max-memory( currentSideCarContainer , min-memory(regular containers) ) .
```

Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go:75]: Max-oom-score-adj ( instead of max-memory ) ?

File: pkg/kubelet/qos/policy.go (hunk 11 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/qos/policy.go]: I feel like we are talking past each other. Maybe some of my understandings are wrong.

My understandings are: 

1. The OOMscore - the lower value is better. 
2. The OOMscore is calculated based on memory compared to total memory on the node. Higher the memory request of a container - lower the chance it will be OOM killed.

For sidecars we have an issue that typically sidecar's memory is the lowest of all. So it is OOM killed fastest. We want to adjust it so it is not an outlier.

So we want to calculate the minimum of all containers oom scores (`minMemoryOomScoreAdjust`). And if the value is lower (better) than the `oomScoreAdjust`, than set the `oomScoreAdjust` to it. Opposite of what you are doing here:

```
		if oomScoreAdjust < minMemoryOomScoreAdjust {
			oomScoreAdjust = minMemoryOomScoreAdjust
		}
```

Am I missing anything? Please let me know if my understanding is wrong here.

Comment (bouaouda-achraf) [reply pkg/kubelet/qos/policy.go]: > 1. The OOMscore - the lower value is better.
> 2. The OOMscore is calculated based on memory compared to total memory on the node. Higher the memory request of a container - lower the chance it will be OOM killed.

Got it. I initially thought the sidecar container would be the first to be killed. However, your proposal better aligns with the importance of keeping the sidecar running, prioritizing it to be killed only at a final stage.

Updated the PR and [kep ](https://github.com/kubernetes/enhancements/pull/4932).  

Thank you.

File: pkg/kubelet/qos/helpers.go [hunk 14]
```diff
@@ -0,0 +1,65 @@
...
+	utilfeature "k8s.io/apiserver/pkg/util/feature"
+	"k8s.io/kubernetes/pkg/features"
+)
+
+// minRegularContainerMemory returns the minimum memory resource quantity
+// across all regular containers in pod.Spec.Containers.
+// It does not include initContainers (both restartable and non-restartable).
+func minRegularContainerMemory(pod v1.Pod) int64 {
+	var containerStatuses map[string]*v1.ContainerStatus
+	if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/qos/helpers.go:39]: since this logic was removed while you were working on this PR from other containers calculations: https://github.com/kubernetes/kubernetes/pull/128269

Let's remove it from this helper method too.

Comment (bouaouda-achraf) [reply pkg/kubelet/qos/helpers.go]: fixed

**Comment by bouaouda-achraf** [comment]
/retest-required

Flaky test

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by bouaouda-achraf** [comment]
thank you @SergeyKanzhelev and @toVersus  for all your comments.
