### PR TITLE
kubeadm: fix unit test failure on node with multiple cri endpoints

### LINKED ISSUE #2863: Kubeadm: unit tests failed on server with multiple CRI endpoints
### Which jobs are failing?

unit test

### Which tests are failing?

```
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/cmd   72.245s
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade   0.190s
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade        1.448s
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/preflight     0.211s
FAIL    k8s.io/kubernetes/cmd/kubeadm/app/util/config
```

They all failed with same errors:
```
Found multiple CRI endpoints on the host. Please define which one do you wish to use by setting the 'criSocket' field in the kubeadm configuration file: unix:///var/run/containerd/containerd.sock, unix:///var/run/cri-dockerd.sock
```

### Since when has it been failing?

Always

### Testgrid link

_No response_

### Reason for failure (if possible)

`criSocket` is required for `InitConfiguration` on server with multiple CRI endpoints, but in unit test `criSocket` is empty.

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/area kubeadm

### PR DESCRIPTION
**Pull request by chendave**
cri installed, 
```
# ls /var/run/crio/crio.sock
/var/run/crio/crio.sock
# ls /var/run/containerd/containerd.sock
/var/run/containerd/containerd.sock
```

run testcases, 
```
# go test k8s.io/kubernetes/cmd/kubeadm/app/cmd
ok      k8s.io/kubernetes/cmd/kubeadm/app/cmd   10.677s
# go test k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade
ok      k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade   0.072s
# go test k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade
ok      k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade        0.974s
# go test k8s.io/kubernetes/cmd/kubeadm/app/preflight
ok      k8s.io/kubernetes/cmd/kubeadm/app/preflight     0.043s
# go test k8s.io/kubernetes/cmd/kubeadm/app/util/config
ok      k8s.io/kubernetes/cmd/kubeadm/app/util/config   5.437s
```

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2863

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/config_test.go [hunk 1]
```diff
@@ -82,10 +82,14 @@ func TestImagesListRunWithCustomConfigPath(t *testing.T) {
...
 			},
 			configContents: []byte(dedent.Dedent(fmt.Sprintf(`
-				apiVersion: %s
-				kind: ClusterConfiguration
-				kubernetesVersion: %s
-			`, kubeadmapiv1.SchemeGroupVersion.String(), constants.CurrentKubernetesVersion))),
+apiVersion: %s
+kind: InitConfiguration
+nodeRegistration:
+  criSocket: "unix:///var/run/containerd/containerd.sock"
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/config_test.go:88]: can we use https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L269 instead of valid sockets everywhere?

unit tests should pass even if no known container runtime socket is present on the host.

Comment (chendave) [reply cmd/kubeadm/app/cmd/config_test.go]: all addressed now.

File: cmd/kubeadm/app/util/config/initconfiguration_test.go [hunk 2]
```diff
@@ -78,6 +81,11 @@ func TestLoadInitConfigurationFromFile(t *testing.T) {
 					t.Error("Unexpected success")
 				}
 			} else {
+				// If the test run on the node with multiple cri endpoints configured and cri endpoint is not set in the InitConfiguration, there should be an error to detect the
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: i think we should avoid having tests depend on host settings in all cases. this means ideally we should not test this scenario at all.

can we remove it and use the unknown socket?

**Review by neolit123 — COMMENTED** [review]
/approve
/hold

hold until review / lgtm please, then unhold.

File: cmd/kubeadm/app/util/config/initconfiguration_test.go (hunk 2 above)
Comment (chendave) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: testcase of `v1beta3.partial2` wants to check that `ClusterConfiguration` can be loaded and finally converted to `InitConfiguration`, I didn't find a way to set the socket without the cfg of `InitConfiguration`. But without the set of cri socket, the testcase won't pass with multiple cri configured.

**Comment by chendave** [comment]
fixed the lint.

File: cmd/kubeadm/app/cmd/init_test.go [hunk 3]
```diff
@@ -81,7 +81,11 @@ func TestNewInitData(t *testing.T) {
 	}{
 		// Init data passed using flags
 		{
-			name: "pass without any flag (use defaults)",
+			name: "pass without any flag except the cri socket (use defaults)",
+			// set the cri socket here, otherwise it would fail if the testcase is run on the node with multiple cri endpoints configured
+			flags: map[string]string{
+				options.NodeCRISocket: constants.UnknownCRISocket,
+			},
 		},
```
Comment (pacoxu) [inline cmd/kubeadm/app/cmd/init_test.go:89]: The below test cases (`expectError: true`) may fail for multi cri when there are. Not fail for the expected reason.

Should we update them as well?

Comment (pacoxu) [reply cmd/kubeadm/app/cmd/init_test.go:89]:
```
cmd.Flags().Set(options.NodeCRISocket: constants.UnknownCRISocket)
```
I think adding the above set before the below code is another way to fix this.

https://github.com/kubernetes/kubernetes/blob/cbc9db31a27abc4dd672915abe888ded1e4f1a43/cmd/kubeadm/app/cmd/init_test.go#L199-L202

Comment (chendave) [reply cmd/kubeadm/app/cmd/init_test.go:89]: > The below test cases (`expectError: true`) may fail for multi cri when there are. Not fail for the expected reason.
> 
> Should we update them as well?

yes, some of them need to be updated as well.

Comment (chendave) [reply cmd/kubeadm/app/cmd/init_test.go:89]: > ```
> cmd.Flags().Set(options.NodeCRISocket: constants.UnknownCRISocket)
> ```
> 
> I think adding the above set before the below code is another way to fix this.
> 
> https://github.com/kubernetes/kubernetes/blob/cbc9db31a27abc4dd672915abe888ded1e4f1a43/cmd/kubeadm/app/cmd/init_test.go#L199-L202

hmm... this sound more neat.

**Comment by chendave** [comment]
@pacoxu thanks for the review! PTAL again.

**Comment by chendave** [comment]
Here is the diff: https://github.com/kubernetes/kubernetes/compare/cbc9db31a27abc4dd672915abe888ded1e4f1a43..5f0788aa767020f6e52b998222b8687b216fb07f

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by SataQiu — APPROVED** [review]

**Comment by neolit123** [comment]
/hold

to check if i can find a solution for:
https://github.com/kubernetes/kubernetes/pull/117614#discussion_r1178664052

will unhold again if not possible

File: cmd/kubeadm/app/util/config/initconfiguration_test.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: why not add a stub InitConfiguration that has some user defined `criSocket: "foo"`

```
name:         "v1beta3.partial2",
			fileContents: bytes.Join([][]byte{
				cfgFiles["ClusterConfiguration_v1beta3"],
				cfgFiles["InitConfiguration_v1beta3"], // some stub with just socket?
			}, []byte(constants.YAMLDocumentSeparator)),
		},
```

it would still convert the two into a single init configuration.

Comment (neolit123) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: it seems InitConfiguration_v1beta3 just has the socket and that's what we need. we can then remove the ignoreErrStr field and check?

Comment (chendave) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: > it would still convert the two into a single init configuration.

yes, that should work, but then it will not the scenario this testcase wants to cover? 

Originally, 

- partial1: only has the `InitConfiguration`
- partial2: only has the `ClusterConfiguration`
- full: has `InitConfiguration`, `ClusterConfiguration` and addons.

If we do that like that, it would be,
- partial1: only has the `InitConfiguration`
- **partial2: both the `ClusterConfiguration` and `InitConfiguration`**
- full: has `InitConfiguration`, `ClusterConfiguration` and addons.

I think this will change the intention of the testcases, I am not sure about that.

@pacoxu @SataQiu  wdyt?

Comment (pacoxu) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: A tricky fix is like below:

1. change defaultKnownCRISockets to DefaultKnownCRISockets so that it can be changed in this UT.
2. add `runtime.DefaultKnownCRISockets = []string{constants.UnknownCRISocket}` before t.Run in this test func.

Comment (chendave) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: that is indeed tricky, then we need to set it back at the end of test. I am not a fan of that. :)

Comment (neolit123) [reply cmd/kubeadm/app/util/config/initconfiguration_test.go:84]: > If we do that like that, it would be

how about - we do we it like i proposed snd then we can inspect obj to ensure that it contains what we want.
we can pass a function "validate" per test case which if not nil can be used to check if field "foo" exists?
if "foo" exists it came from a ClusterConfiguration.

**Comment by chendave** [comment]
@neolit123 is this something what you mean? https://github.com/kubernetes/kubernetes/compare/5f0788aa767020f6e52b998222b8687b216fb07f..2572a4303442f532ad96dea1bb3ca40135deafb6

**Comment by pacoxu** [comment]
/lgtm
as we have to do something to avoid failures from auto-detect.

**Comment by neolit123** [comment]
> is this something what you mean?

yes, exactly, please remove the hold if you think it's good to go.
thanks
