### PR TITLE
fix issue with using feature HonorPVReclaimPolicy in csi-provisioner

### LINKED ISSUE #121799: Issue with using feature HonorPVReclaimPolicy in csi-provisioner
### What happened?

In my CSI controller I have enabled the feature gate HonorPVReclaimPolicy for csi-provisioner. 

Based on the documentation 
Finalizers can be added on a PersistentVolume to ensure that PersistentVolumes having Delete reclaim policy are deleted only after the backing storage are deleted.

The newly introduced finalizers kubernetes.io/pv-controller and external-provisioner.volume.kubernetes.io/finalizer are only added to dynamically provisioned volumes.

I can see the finalizer set on the PV while creating static Persistent Volume. PV deletion is stuck due to this finalizer

apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: "2023-11-08T11:39:24Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-11-08T11:54:31Z"
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
  name: csi-infoscale-pv

### What did you expect to happen?

PV should be deleted when PVC is deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Persistent Volume yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-infoscale-pv
spec:
  storageClassName: csi-infoscale-sc-prod
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.veritas.infoscale
    # Please provide pre-provisioned Infoscale volume name.
    volumeHandle: clust_21432/vrts_kube_dg-21432/vol1
    fsType: vxfs

Persistent Volume Claim 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-infoscale-pvc-static
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-infoscale-sc-prod
  volumeName: csi-infoscale-pv

### Anything else we need to know?

Same thing works fine on OCP.

### Kubernetes version

# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:48:26Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Vanilla K8s setup

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

For the volume statically provisioned by user who create the pv with an existing class, according to the current implementation of the findDeletablePlugin func, the func will return the an error if the volume does not be annotated with the pv.kubernetes.io/provisioned-by annotaion.

The annotation is automatically added to a pv that has been dynamically provsioned by either the pv controller or an external provisioner. Its value is name of volume plugin or provisioner that creates the volume. Its serves both user (to slow where a PV comes from) and Kubernetes (to recongize dynamically provisioned PVs in its decisions). 

If a pv is annotated and its annoation value doesn't contain the 'kuberentes.io/', the external provsioner will handle the pv when the pv is deleted after the pv is marked as Released. If a pv is not annotated, the pv controller will treat it as statically provisioned and try to find a in-tree plugin to handle it by volume spec. If no suitable plugin is found, the pv controller will mark the pv as failed with the error that is no deletable volume plugin matched.

In this issue, the pv is created by users with a csi type. So the volume won't be never annotated even through the pv has specified an existing storageclass. so when the pv is deleted, the pv controller will mark it as Failed.

the [KEP-2644](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2644-honor-pv-reclaim-policy) introduces a new finalizer `external-provisioner.volume.kubernetes.io/finalizer` to honor pv's reclaim policy whatever the pv is dynamically or statically provsioned. 

For statically provsioned pvs, if its volume source is csi, the pv controller cannot find a plugin by volume spec because this csi plugin does not implemenet the DeletableVolumePlugin interface. Those pvs deletion behavior is expected to be handled by the external provisioner. however, the current implement of the findDeletablePlugin func cannot recognize this situation and wrongly changes the volume phase from Release to Fail when the pv controller watches the pv deletion event or the resync period is reached, the pv is put into queue and then handle by the syncVolume func.

In the log pasted by @reenakabra, we can see that the external provsioner do delete pv and try to remove the finalizer but failed due to the resourceVersion conflict. even though the external provsioner retries its job but the pv phase may have been changed to Failed. Once a pv state is not Release, the external provisioner won't be able to remove the pv's finalizers in subsequent reconcile cycles. So the pv deletion will be stuck forever due to the finalizer existing.

In order to fix this issue, the findDeletablePlugin func should recongize the volume which may be able to handled by an external provioner when the volume source is csi or the pv has migrated annotation whatever the pv is dynamically or statically provsioned. 

With this patch, the pv controller won't changes PV's phase to Failed and the external provisioner can remove the finalizer in next reconcile loop. Unfortunately if the provious existing pv has the Failed state, this patch won't take effort. It requires users to remove finalizer.

#### Which issue(s) this PR fixes:

Fixes #121799 

#### Special notes for your reviewer:

Should we do cherry-pick it into pervious releases?

#### Does this PR introduce a user-facing change?

```release-note
For statically provisioned PVs, if its volume source is CSI type or it has migrated annotation, when it's deleted, the PersisentVolume controller won't changes its phase to the Failed state. 

With this patch, the external provisioner can remove the finalizer in next reconcile loop. Unfortunately if the provious existing pv has the Failed state, this patch won't take effort. It requires users to remove finalizer.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2644
```

### CODE REVIEW

**Comment by carlory** [comment]
unrelated flaky test: Kubernetes e2e suite: [It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] 

/test pull-kubernetes-e2e-kind-ipv6

**Comment by deepakkinni** [comment]
The change looks fine to me, I am wondering if we could have some additional tests for this scenario? How else have you tested these changes, considering the original issue was easily reproducible, did you ensure that this actually fixes it?

**Comment by carlory** [comment]
@deepakkinni 

I add a feature-gate check and some tests, please review again, thank you.

File: pkg/controller/volume/persistentvolume/delete_test.go [hunk 1]
```diff
@@ -148,9 +148,9 @@ func TestDeleteSync(t *testing.T) {
 		},
 		{
 			// PV requires external deleter
-			name:            "8-10 - external deleter",
-			initialVolumes:  []*v1.PersistentVolume{newExternalProvisionedVolume("volume8-10", "1Gi", "uid10-1", "claim10-1", v1.VolumeBound, v1.PersistentVolumeReclaimDelete, classEmpty, gceDriver, nil, volume.AnnBoundByController)},
-			expectedVolumes: []*v1.PersistentVolume{newExternalProvisionedVolume("volume8-10", "1Gi", "uid10-1", "claim10-1", v1.VolumeReleased, v1.PersistentVolumeReclaimDelete, classEmpty, gceDriver, nil, volume.AnnBoundByController)},
+			name:            "8-10-1 - external deleter when volume is provisioned by controller",
```
Comment (deepakkinni) [inline pkg/controller/volume/persistentvolume/delete_test.go:151]: Could you clarify what "volume is provisioned by controller" means?

File: pkg/controller/volume/persistentvolume/delete_test.go [hunk 2]
```diff
@@ -162,6 +162,28 @@ func TestDeleteSync(t *testing.T) {
 				return testSyncVolume(ctrl, reactor, test)
 			},
 		},
+		{
+			// PV requires external deleter
+			name:            "8-10-2 - external deleter when volume is provisioned by user",
```
Comment (deepakkinni) [inline pkg/controller/volume/persistentvolume/delete_test.go:167]: I am not clear about this, what does it mean by provisioned by user? could you tell me the difference between this one and previous test?

File: pkg/controller/volume/persistentvolume/delete_test.go (hunk 1 above)
Comment (carlory) [reply pkg/controller/volume/persistentvolume/delete_test.go:151]: It refers to dynamic volume provisioning. User create a pv with a storageclass. kube-controller-mananger will trigger a pv creation and the created pvc will be annotated by `pv.kubernetes.io/provisioned-by`

https://github.com/kubernetes/kubernetes/blob/cc8a7e812ec5b7256de470021107cd849ceda691/pkg/controller/volume/persistentvolume/delete_test.go#L158-L163

File: pkg/controller/volume/persistentvolume/delete_test.go (hunk 2 above)
Comment (carlory) [reply pkg/controller/volume/persistentvolume/delete_test.go:167]: It refers to static volume provisioning. User create both pv and pvc. the pv was not annotated like dynamic volume provisioning.

Comment (carlory) [reply pkg/controller/volume/persistentvolume/delete_test.go:167]: you can see **What this PR does / why we need it:** in pr description for more details.

File: pkg/controller/volume/persistentvolume/delete_test.go (hunk 1 above)
Comment (deepakkinni) [reply pkg/controller/volume/persistentvolume/delete_test.go:151]: Please change it to dynamic volume provisioning itself.

File: pkg/controller/volume/persistentvolume/delete_test.go (hunk 2 above)
Comment (deepakkinni) [reply pkg/controller/volume/persistentvolume/delete_test.go:167]: Change it to static provisioning

**Review by deepakkinni — COMMENTED** [review]
Will approve the change once the names are changed, thanks!

**Comment by carlory** [comment]
/cc @deepakkinni 

Do we need cherry-pick this to release-1.29, release-1.28, relase-1.27 and release-1.26?

**Comment by deepakkinni** [comment]
/approve

@xing-yang are alpha feature fixes backported?

**Comment by xing-yang** [comment]
> @xing-yang are alpha feature fixes backported?

Yes.
