### PR TITLE
kube-proxy consider endpoint readiness to delete UDP stale conntrack entries

### LINKED ISSUE #105657: Wrong udp conntrack entries are populated after a pod is killed using --force
### What happened?

On a single node kubernetes cluster, deployed using minikube: 

[root@control-plane ~]# kubectl get nodes -o wide
NAME                              STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                               KERNEL-VERSION          CONTAINER-RUNTIME
control-plane.minikube.internal   Ready    control-plane,master   46h   v1.22.2   10.45.253.76   <none>        Red Hat Enterprise Linux 8.4 (Ootpa)   4.18.0-305.el8.x86_64   docker://20.10.6

We have two pods handling SIP traffic. One pod is sending an OPTIONS to the other on port 5060 using a service.

ea1-tasftapp   ClusterIP   10.97.122.198    <none>        5060/UDP            46h

tas-sip-b2bua-tasftapp-69c574b88c-7nvsm   1/1     Running   0          13m   10.244.0.35   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

Connection on conntrack looks like this: 

udp      17 119 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 src=10.244.0.35 dst=10.244.0.24 sport=5060 dport=5060 [ASSURED] mark=0 use=1

If we delete the pod behind the ea1-tasftapp service by using kubectl delete pod, a new one is created:

tas-sip-b2bua-tasftapp-69c574b88c-7rdgm   1/1     Running   0          47s   10.244.0.36   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

and conntrack is updated correctly: 

udp      17 119 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 src=10.244.0.36 dst=10.244.0.24 sport=5060 dport=5060 [ASSURED] mark=0 use=1

If we delete the pod using force, a new pod is created:

tas-sip-b2bua-tasftapp-69c574b88c-gvx9g   1/1     Running   0          22s   10.244.0.37   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

but the conntrack is updated using the node ip instead of the new pods. Due to this, connectivity between the two pods doesn't work.

udp      17 29 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 [UNREPLIED] src=10.97.122.198 dst=10.45.253.76 sport=5060 dport=9817 mark=0 use=1

Problem is solved only by restarting the pod initiated the connection (tas-sip-b2bua-tassnf-78fd487c7d-t9b2j) or by restarting kube-proxy. 

Issue appears only on 1.22 kubernetes version. On version 1.21 everything is working properly. 

### What did you expect to happen?

After pod is killed, a new conntrack entry should be created towards the IP of the new pod. 

### How can we reproduce it (as minimally and precisely as possible)?

Having udp connectivity between a pod and a service and force delete the pod where the traffic is routed through the service. 

### Anything else we need to know?

_No response_

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

On premises deployment. 

### OS version

NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

Linux control-plane.minikube.internal 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed

### Related plugins (CNI, CSI, ...) and versions (if applicable)

[root@control-plane ~]# calicoctl version
Client Version:    v3.20.2
Git commit:        dcb4b76a
Cluster Version:   v3.20.2
Cluster Type:      k8s,kdd,bgp,kubeadm

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind regression

#### What this PR does / why we need it:

1. Create an UDP Service
2. Client Pod sending traffic to the UDP service
3. Create an UDP server associated to the Service created in 1. with an init container that sleeps for some time

The init container makes that the server pod is not ready, however, the endpoint slices are created, it is just
that the Endpoint conditions Ready is false.
If the kube-proxy conntrack logic doesn't check readiness, it will delete the conntrack entries for the UDP server
when the endpoint slice has been created, however, the iptables rules will not installed until at least one
endpoint is ready. If some traffic arrives to since kube-proxy clear the entries (see the endpoint slice) and
installs the corresponding iptables rules (the endpoint is ready), a conntrack entry will be generated blackholing
subsequent traffic.

Fixes #105657

```release-note
fix a 1.22 kube-proxy regression on UDP services because the logic to detect stale connections was not considering if the endpoint was ready.
```

### CODE REVIEW

**Comment by aojea** [comment]
ok, the test reproduces the issue

> Kubernetes e2e suite: [sig-network] Conntrack should be able to preserve UDP traffic when initial unready endpoints get ready expand_less	1m40s
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:293
Nov  5 00:08:20.758: Failed to connect to backend pod
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113

File: pkg/proxy/endpoints.go [hunk 1]
```diff
@@ -561,8 +567,21 @@ func detectStaleConnections(oldEndpointsMap, newEndpointsMap EndpointsMap, stale
 			continue
 		}
 
-		// For udp service, if its backend changes from 0 to non-0. There may exist a conntrack entry that could blackhole traffic to the service.
-		if len(epList) > 0 && len(oldEndpointsMap[svcPortName]) == 0 {
+		epReady := 0
+		for _, ep := range epList {
+			if ep.IsReady() {
+				epReady++
```
Comment (danwinship) [inline pkg/proxy/endpoints.go:573]: So... this doesn't take `ProxyTerminatingEndpoints` into account...

Consider the case where an `externalTrafficPolicy: Local` service has a single Serving-Terminating endpoint. Connections come in to that endpoint's node and are accepted and processed by the terminating pod. Then a new endpoint starts up and becomes Ready. Given the code here, that would be interpreted as "the service went from 0 endpoints to non-0 endpoints", and so the node with the Serving-Terminating endpoint would flush all conntrack entries for the service, breaking the existing connections to the Serving-Terminating pod.

(Also, this patch changes the rules for `staleServices`, but there are terminating endpoints problems with `staleEndpoints` too; we used to delete conntrack entries to endpoints as soon as the endpoint become non-ready, but now we don't delete them until the pod is fully deleted...)

File: pkg/proxy/endpoints.go [hunk 2]
```diff
@@ -121,7 +121,13 @@ func (info *BaseEndpointInfo) Port() (int, error) {
 
 // Equal is part of proxy.Endpoint interface.
 func (info *BaseEndpointInfo) Equal(other Endpoint) bool {
-	return info.String() == other.String() && info.GetIsLocal() == other.GetIsLocal()
+	return info.String() == other.String() &&
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/proxy/endpoints.go:124]: thanks

File: pkg/proxy/endpoints.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/endpoints.go:573]: > So... this doesn't take `ProxyTerminatingEndpoints` into account...

this is a regression that needs to be backported  and ProxyTerminatingEndpoints is an alpha feature. Also, after the analysis you did in your related PR, I don't think that is easy to solve both problems easily at the same time :sweat_smile: 

>  breaking the existing connections to the Serving-Terminating pod.

it is UDP, in the sense that is not breaking the connection per se, the new packet will create a new entry looking at the iptables rules, that should still exist ... is less performant because but not a big deal

> (Also, this patch changes the rules for staleServices, but there are terminating endpoints problems with staleEndpoints too; we used to delete conntrack entries to endpoints as soon as the endpoint become non-ready, but now we don't delete them until the pod is fully deleted...)

that is fixed by the `Equal` change to take into consideration Ready https://github.com/kubernetes/kubernetes/pull/106163/files#r743336980

File: pkg/proxy/endpoints.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/proxy/endpoints.go:124]: adding only the ready condition to the Equal comparison to keep this targeted to the problem at hand

File: pkg/proxy/endpoints.go (hunk 1 above)
Comment (danwinship) [reply pkg/proxy/endpoints.go:581]: > it is UDP, in the sense that is not breaking the connection per se, since it is connectionless

UDP is connectionless at L4, but not necessarily at L7. That's the main reason UDP conntrack records exist. Eg, anything using Datagram TLS (like QUIC / HTTP/3) won't survive being switched to a different endpoint mid-communication, because the new endpoint won't have the encryption key it needs.

File: pkg/proxy/endpoints.go [hunk 3]
```diff
@@ -536,13 +538,22 @@ func (em EndpointsMap) getLocalReadyEndpointIPs() map[types.NamespacedName]sets.
...
 
 		for _, ep := range epList {
+			// if the old endpoints wasn't ready is not possible to have stale entries
+			// since there was no traffic sent to it.
+			if !ep.IsReady() {
+				continue
+			}
 			stale := true
+			// Check if the endpoint has changed, including if it went from ready to not ready.
+			// Ff it did change stale entries for the old endpoint has to be cleared.
```
Comment (danwinship) [inline pkg/proxy/endpoints.go:556]:
```suggestion
			// If it did change stale entries for the old endpoint has to be cleared.
```

File: pkg/proxy/endpoints.go [hunk 4]
```diff
@@ -536,13 +538,22 @@ func (em EndpointsMap) getLocalReadyEndpointIPs() map[types.NamespacedName]sets.
...
 func detectStaleConnections(oldEndpointsMap, newEndpointsMap EndpointsMap, staleEndpoints *[]ServiceEndpoint, staleServiceNames *[]ServicePortName) {
+	// Detect stale endpoints: an endpoint can have stale conntrack entries if it was receiving traffic
+	// and then goes unready or changes its IP address.
 	for svcPortName, epList := range oldEndpointsMap {
 		if svcPortName.Protocol != v1.ProtocolUDP {
 			continue
 		}
 
 		for _, ep := range epList {
+			// if the old endpoints wasn't ready is not possible to have stale entries
```
Comment (danwinship) [inline pkg/proxy/endpoints.go:549]:
```suggestion
			// if the old endpoint wasn't ready is not possible to have stale entries
```

**Review by danwinship — COMMENTED** [review]
/approve
just some typos. (I would have let the "endpoints"/"endpoint" slide, but the "Ff" would annoy me :slightly_smiling_face:)

File: pkg/proxy/endpoints.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/endpoints.go:581]: :eyes: I can't argue against that, but seems we are going to have some fun soon :smile:

**Comment by aojea** [comment]
> Kubernetes e2e suite: [sig-node] PreStop graceful pod terminated should wait until preStop hook completes the process expand_more	

:eyes: 


/test pull-kubernetes-e2e-gce-ubuntu-containerd
--


<br class="Apple-interchange-newline">

**Comment by aojea** [comment]
ok 2/2 ?
```


Kubernetes e2e suite: [sig-node] PreStop graceful pod terminated should wait until preStop hook completes the process expand_less
```

**Comment by aojea** [comment]
> Nov  5 15:59:37.306: INFO: At 2021-11-05 15:58:51 +0000 UTC - event for pod-prestop-hook-06a9dd06-d340-40c3-8676-a84f44b9a683: {kubelet e2e-b6818f6f36-a7d53-minion-group-jrkd} FailedPreStopHook: Exec lifecycle hook ([sh -c while true; do echo preStop; sleep 1; done]) for Container "nginx" in Pod "pod-prestop-hook-06a9dd06-d340-40c3-8676-a84f44b9a683_prestop-9129(22f8a03f-f8bf-49e2-814e-548404254983)" failed - error: command 'sh -c while true; do echo preStop; sleep 1; done' exited with 137: , message: "preStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\npreStop\n"

137 = OOM?

the same test passed in the other jobs, I can't find the relation with this PR
/test pull-kubernetes-e2e-gce-ubuntu-containerd

I will run it some times more

**Comment by aojea** [comment]
a different one this time?
```
Kubernetes e2e suite: [sig-network] Proxy version v1 should proxy logs on node with explicit kubelet port using proxy subresource  expand_more
``` 

can it be related to fc85bb29d2fbb844a5a4e37cbc851431deb608db ?

**Comment by aojea** [comment]
> a different one this time?
> 
> ```
> Kubernetes e2e suite: [sig-network] Proxy version v1 should proxy logs on node with explicit kubelet port using proxy subresource  expand_more
> ```
> 
> can it be related to [fc85bb2](https://github.com/kubernetes/kubernetes/commit/fc85bb29d2fbb844a5a4e37cbc851431deb608db) ?

so, it was that commit, @danwinship , this is ready to merge and backport, I squashed the e2e test with the kube-proxy changes and removed the commit that was causing issues with the e2e framework
