### PR TITLE
Fix hostname truncate.

### LINKED ISSUE #36951: Kubelet should truncate hostname more carefully
Docker daemon complains "invalid hostname format" if the truncated host name ends with "." The truncation occurs [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L237).

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/kubernetes/kubernetes/issues/36951.

This PR will keep truncating the hostname until the ending character is valid.

/cc @kubernetes/sig-node 

Mark v1.5 because this is a bug fix.
/cc @saad-ali

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36965)

### CODE REVIEW

**Comment by saad-ali** [comment]
Bug fix ok for post-code freeze merge

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -228,13 +228,35 @@ func makePortMappings(container *api.Container) (ports []kubecontainer.PortMappi
...
+func truncatePodHostnameIfNeeded(podName, hostname string) (string, error) {
+	// Cap hostname at 63 chars (specification is 64bytes which is 63 chars and the null terminating char).
+	const hostnameMaxLen = 63
+	if len(hostname) <= hostnameMaxLen {
+		return hostname, nil
+	}
+	truncated := hostname[:hostnameMaxLen]
+	glog.Errorf("hostname for pod:%q was longer than %d. Truncated hostname to :%q", podName, hostnameMaxLen, truncated)
+	// hostname should not end with '-' or '.'
+	for {
```
Comment (euank) [inline pkg/kubelet/kubelet_pods.go]: Any reason we can't just do:

```go
truncated = strings.TrimRight(truncated, "-.")
```

Comment (Random-Liu) [inline pkg/kubelet/kubelet_pods.go]: Hm. No reason. Just forgot there is this function. :P

Comment (Random-Liu) [inline pkg/kubelet/kubelet_pods.go]: Done. Thanks!

**Comment by feiskyer** [comment]
LGTM

**Comment by euank** [comment]
LGTM

**Comment by Random-Liu** [comment]
Apply LGTM based on comments.

File: pkg/kubelet/kubelet_pods.go [hunk 2]
```diff
@@ -228,13 +228,29 @@ func makePortMappings(container *api.Container) (ports []kubecontainer.PortMappi
...
+func truncatePodHostnameIfNeeded(podName, hostname string) (string, error) {
+	// Cap hostname at 63 chars (specification is 64bytes which is 63 chars and the null terminating char).
+	const hostnameMaxLen = 63
+	if len(hostname) <= hostnameMaxLen {
+		return hostname, nil
+	}
+	truncated := hostname[:hostnameMaxLen]
+	glog.Errorf("hostname for pod:%q was longer than %d. Truncated hostname to :%q", podName, hostnameMaxLen, truncated)
+	// hostname should not end with '-' or '.'
+	truncated = strings.TrimRight(truncated, "-.")
```
Comment (dustymabe) [inline pkg/kubelet/kubelet_pods.go]: i'm wondering if we should have put the log statement below this line where we trim off `-.`
