### PR TITLE
e2e test forwarding externalname dns lookup to upstream nameservers.

### LINKED ISSUE #226: Add an e2e test that goes through dnsmasq -> kubedns -> upstream servers path
Ref https://github.com/kubernetes/dns/issues/224, a recent regression was introduced without being caught by any of the tests. The dnsmasq -> kubedns -> upstream servers path is currently a blindspot in test and we should surely include that to prevent future regression.

cc @grayluck

### PR DESCRIPTION
**Pull request by grayluck**
**What this PR does / why we need it**:
e2e test forwarding externalname dns lookup to upstream nameservers.

e2e test that goes through dnsmasq -> kubedns -> upstream servers path.

Updated e2e test for PTR record lookup, test for default upstreamservers from resolv.conf.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/dns/issues/226

**Special notes for your reviewer**:
/assign @MrHohn 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/network/dns_configmap.go [hunk 1]
```diff
@@ -217,6 +219,65 @@ func (t *dnsPtrFwdTest) run() {
 		func(actual []string) bool { return len(actual) == 0 },
 		"dnsmasq",
 		moreForeverTestTimeout)
+
+	// Should still be able to lookup public nameserver without upstream nameserver.
```
[the remark this answers is not in the document]
Comment (MrHohn) [reply test/e2e/network/dns_configmap.go]: Also move this check above prior to `setConfigMap`?

File: test/e2e/network/dns_configmap.go [hunk 2]
```diff
@@ -217,6 +219,65 @@ func (t *dnsPtrFwdTest) run() {
...
+}
+
+func (t *dnsExternalNameTest) run() {
+	t.init()
+
+	t.createUtilPod()
+	defer t.deleteUtilPod()
+
+	t.createDNSServer(map[string]string{
+		googleDnsHostname: "192.0.2.123",
```
Comment (MrHohn) [inline test/e2e/network/dns_configmap.go]: Instead of using `googleDnsHostname`, can we use something else (`foo.example.com`)? This sounds like hijacking...

**Review by MrHohn — COMMENTED** [review]
Thanks! Looks good overall, some minor comments.

**Comment by MrHohn** [comment]
cc @bowei

File: test/e2e/network/dns_configmap.go (hunk 2 above)
Comment (grayluck) [reply test/e2e/network/dns_configmap.go]: Changed to foo.example.com so the code looks less like hacking something.

File: test/e2e/network/dns_configmap.go [hunk 3]
```diff
@@ -219,6 +228,63 @@ func (t *dnsPtrFwdTest) run() {
...
+		By("deleting the test externalName service")
+		defer GinkgoRecover()
+		f.ClientSet.CoreV1().Services(f.Namespace.Name).Delete(externalNameService.Name, nil)
+		f.ClientSet.CoreV1().Services(f.Namespace.Name).Delete(externalNameServiceLocal.Name, nil)
+	}()
+
+	t.checkDNSRecordFrom(
+		fmt.Sprintf("%s.%s.svc.cluster.local", serviceName, f.Namespace.Name),
+		func(actual []string) bool {
+			return len(actual) >= 1 && actual[0] == googleDnsHostname+"."
```
Comment (MrHohn) [inline test/e2e/network/dns_configmap.go]: I think this should be included in the externalName test in dns.go instead. But seems fine to keep it with the configmap test for now.

File: test/e2e/network/dns_configmap.go [hunk 4]
```diff
@@ -219,6 +228,63 @@ func (t *dnsPtrFwdTest) run() {
...
+
+	t.checkDNSRecordFrom(
+		fmt.Sprintf("%s.%s.svc.cluster.local", serviceNameLocal, f.Namespace.Name),
+		func(actual []string) bool {
+			return len(actual) == 2 && actual[0] == fooHostname+"." && actual[1] == "192.0.2.123"
+		},
+		"dnsmasq",
+		moreForeverTestTimeout)
+
+	t.c.CoreV1().ConfigMaps(t.ns).Delete(t.name, nil)
```
Comment (MrHohn) [inline test/e2e/network/dns_configmap.go]: Instead of deleting the configmap, what about simply resetting it to empty? Otherwise we will waste ~1 minute for addon-manager to re-assert it.

Comment (grayluck) [reply test/e2e/network/dns_configmap.go]: Good one. Fixed.

File: test/e2e/network/dns_configmap.go (hunk 3 above)
Comment (grayluck) [reply test/e2e/network/dns_configmap.go]: Ack.

**Review by MrHohn — APPROVED** [review]
Thanks! LGTM. Could you squash commits?

**Comment by grayluck** [comment]
Sure squashed. Thanks for review!
