### PR TITLE
Match label and fields selectors in ComponentStatus List API

### LINKED ISSUE #78214: GET /api/v1/componentstatuses does not respect labelSelector
**What happened**: tried to get listing of all componentstatuses using a labelSelector query selector. I am hitting the apiServer directly. GET /api/v1/componentstatuses

**What you expected to happen**: GET /api/v1/componentstatuses with labelSelector should limit responses to only componentstatuses with the specified label

**How to reproduce it (as minimally and precisely as possible)**: run GET /api/v1/componentstatuses with and without a labelSelector against the apiServer.

**Anything else we need to know?**: specifically my label selector is in the form `mylabel=myvalue`. and i can confirm everything works as expected when i hit GET /api/v1/pods

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6+IKS", GitCommit:"ac5f7341d5d0ce8ea8f206ba5b030dc9e9d4cc97", GitTreeState:"clean", BuildDate:"2019-05-09T13:26:51Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: IBM
- OS (e.g: `cat /etc/os-release`): Mac
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.5.0
- Install tools: Using javascript npm request to talk to api server
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by 11janci**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Adds Label and Field Selector matching to ComponentStatus List API. Previously the API always included all of the results even if the request specified a Label or Field Selector.

**Which issue(s) this PR fixes**:
Parially fixes #78214 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/registry/core/componentstatus/rest.go [hunk 1]
```diff
@@ -19,6 +19,10 @@ package componentstatus
 import (
 	"context"
 	"fmt"
+	"k8s.io/apimachinery/pkg/fields"
```
Comment (yue9944882) [inline pkg/registry/core/componentstatus/rest.go]: import order

File: pkg/registry/core/componentstatus/rest_test.go [hunk 2]
```diff
@@ -18,6 +18,9 @@ package componentstatus
 
 import (
 	"fmt"
+	metainternalversion "k8s.io/apimachinery/pkg/apis/meta/internalversion"
```
Comment (yue9944882) [inline pkg/registry/core/componentstatus/rest_test.go]: import order

File: pkg/registry/core/componentstatus/rest.go [hunk 3]
```diff
@@ -70,13 +74,47 @@ func (rs *REST) List(ctx context.Context, options *metainternalversion.ListOptio
 	wait.Wait()
 	close(statuses)
 
+	pred := componentStatusPredicate(options)
```
Comment (yue9944882) [inline pkg/registry/core/componentstatus/rest.go]: we can start by supporting only label-selecting, and this will help simplify this pull, wdyt?

File: pkg/registry/core/componentstatus/rest.go (hunk 1 above)
Comment (11janci) [reply pkg/registry/core/componentstatus/rest.go]: fixed

File: pkg/registry/core/componentstatus/rest_test.go (hunk 2 above)
Comment (11janci) [reply pkg/registry/core/componentstatus/rest_test.go]: fixed

File: pkg/registry/core/componentstatus/rest.go (hunk 3 above)
Comment (11janci) [reply pkg/registry/core/componentstatus/rest.go]: Hi @yue9944882,
thx for your review. IMO the changes are quite simple as it is, is some 30 lines of code which is fairly straightforward. More importantly, taking out the field selectors is hardly going to change the code and will not satisfy the requirement from the ticket.

**Comment by yue9944882** [comment]
/lgtm
/cc @liggitt

for approval
