### PR TITLE
turn off cni masqurade and manage it in kubenet

### LINKED ISSUE #27110: Preserve source ip of service.clusterIP traffic
This appears to be a regression. Create an nginx pod and service such as:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: echoheaders
  labels:
    app: echoheaders
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: gcr.io/google_containers/echoserver:1.3
        ports:
        - containerPort: 8080
```
And a test pod like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: /tmp/foo
      name: test
  volumes:
  - name: test
    emptyDir: {}
  restartPolicy: Always
```

Try and get them to land on different nodes. 
```console
19:52:02-beeps~/logs]$ k get svc
NAME          CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
echoheaders   10.0.204.199   <none>        80/TCP    3h
kubernetes    10.0.0.1       <none>        443/TCP   4h

$ k exec -it busybox /bin/sh
[ root@busybox:/ ]$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1460 qdisc noqueue 
    link/ether 0a:58:0a:b4:01:08 brd ff:ff:ff:ff:ff:ff
    inet 10.180.1.8/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20db:d6ff:febd:ed7b/64 scope link 
       valid_lft forever preferred_lft forever
```
curl the service vip
```console
[ root@busybox:/ ]$ wget -qO- 10.0.204.199
CLIENT VALUES:
client_address=10.240.0.5
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.0.204.199:8080/

SERVER VALUES:
server_version=nginx: 1.9.11 - lua: 10001

HEADERS RECEIVED:
connection=close
host=10.0.204.199
user-agent=Wget
BODY:
-no body in request-
```

And in another window:
```console
19:52:42-beeps~/logs]$ k logs echoheaders-k5fs5 --follow
10.240.0.5 - - [09/Jun/2016:02:53:21 +0000] "GET / HTTP/1.1" 200 386 "-" "Wget"
```

I expected a source ip of `10.180.1.8`. We should just be DNATing to the pod ip.
I see rules like:
```
:CNI-252089a662c3409f212af1da - [0:0]
-A POSTROUTING -s 10.180.1.0/24 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j CNI-252089a662c3409f212af1da
-A CNI-252089a662c3409f212af1da -d 10.180.1.0/24 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j ACCEPT
-A CNI-252089a662c3409f212af1da ! -d 224.0.0.0/4 -m comment --comment "name: \"kubenet\" id: \"dc71fad93e755458b75b6cc3379b4f0052941ce4612a06d7c421ec5c1e522168\"" -j MASQUERADE
```

@kubernetes/sig-network @dcbw

### PR DESCRIPTION
**Pull request by freehan**
fixes #27110

### CODE REVIEW

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 1]
```diff
@@ -167,7 +167,7 @@ const NET_CONFIG_TEMPLATE = `{
   "mtu": %d,
   "addIf": "%s",
   "isGateway": true,
-  "ipMasq": true,
+  "ipMasq": false,
```
Comment (bprashanth) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: being able to route to pod ips is a requirement for kube anyway, was there a reason we set this to being with?

**Comment by bprashanth** [comment]
LGTM assuming tests pass

File: pkg/kubelet/network/kubenet/kubenet_linux.go (hunk 1 above)
Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I think it has been there since the initial commit. Great catch BTW!

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 2]
```diff
@@ -132,6 +132,12 @@ func (plugin *kubenetNetworkPlugin) Init(host network.Host, hairpinMode componen
 		return fmt.Errorf("Failed to generate loopback config: %v", err)
 	}
 
+	// Need to SNAT outbound traffic from cluster
+	// TODO: move this into cni bridge plugin
+	if _, err := plugin.iptables.EnsureRule(utiliptables.Append, utiliptables.TableNAT, utiliptables.ChainPostrouting, "-m", "comment", "--comment",
+		"kubenet: SNAT for outbound traffic from cluster", "-s", nonMasqueradeCIDR, "!", "-d", nonMasqueradeCIDR, "-j", "MASQUERADE"); err != nil {
```
Comment (bprashanth) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: We used to periodically confirm this, now it's only on init, feels more brittle but I don't see an alternative. If you want to mimize margin for error, suggest invoking container_bridge:ensureIPTablesMasqRule.

Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I did not switch to use container_bridge:ensureIPTablesMasqRule because there is a TODO comment about switching to use iptables util. 
But I copied the exact same rule.

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 3]
```diff
@@ -132,6 +134,23 @@ func (plugin *kubenetNetworkPlugin) Init(host network.Host, hairpinMode componen
...
+	// Need to SNAT outbound traffic from cluster
+	if err = plugin.ensureMasqRule(); err != nil {
+		return err
+	}
+	return nil
+}
+
+// TODO: move thic logic into cni bridge plugin and remove this from kubenet
+func (plugin *kubenetNetworkPlugin) ensureMasqRule() error {
+	if _, err := plugin.iptables.EnsureRule(utiliptables.Append, utiliptables.TableNAT, utiliptables.ChainPostrouting,
```
Comment (bprashanth) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I'm assuming this won't keep appending rules?

**Comment by freehan** [comment]
@bprashanth 
ensure the rule on every SetUpPod and Init
I did not use container_bridge:ensureIPTablesMasqRule. There is TODO comment about switching to use iptables util.

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 4]
```diff
@@ -354,6 +373,10 @@ func (plugin *kubenetNetworkPlugin) SetUpPod(namespace string, name string, id k
 	}
 
 	plugin.syncHostportsRules()
+	// Need to SNAT outbound traffic from cluster
+	if err = plugin.ensureMasqRule(); err != nil {
```
Comment (bprashanth) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: Why did you leave out TearDown :)

**Comment by bprashanth** [comment]
LGTM assuming this won't keep appending rules when a rule already exists

File: pkg/kubelet/network/kubenet/kubenet_linux.go (hunk 3 above)
Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I am pretty sure it does not. Or kube-proxy will explode by now.

File: pkg/kubelet/network/kubenet/kubenet_linux.go (hunk 4 above)
Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: Maybe I should?

**Comment by freehan** [comment]
Added ensureMasqRule in TearDown

**Comment by bprashanth** [comment]
So the risk of doing it in setup and teardown is that it will lead to pod start/delete failures. I'm assuming we'll retry both these scenarios (eg if a teardown is modifying the rule at the same time as a setup)? Otherwise I'm fine just doing it once in Init with a comment saying: we really need a sync routine to periodically verify network configuration that isn't tied to a particular pod.

**Comment by bprashanth** [comment]
Integration failure looks legit
```
!!! 'gofmt -s -w' needs to be run on the following files: 
./pkg/kubelet/network/kubenet/kubenet_linux.go
FAILED   ./hack/../hack/verify-gofmt.sh	9s
```
