### PR TITLE
RC/RS: Fix ignoring inactive Pods.

### LINKED ISSUE #37479: [k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial/43/

Failed: [k8s.io] Network Partition [Disruptive] [Slow] [k8s.io] [ReplicationController] should eagerly create replacement pod during network partition when termination grace is non-zero {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:359
Nov 25 01:50:18.071: Node gke-bootstrap-e2e-default-pool-3dd2292e-u5qh did not become ready within 2m0s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network_partition.go:357
```

### PR DESCRIPTION
**Pull request by enisoc**
**What this PR does / why we need it**:

Fix typo that broke ignoring of inactive Pods in RC, and add unit test for that case.

**Which issue this PR fixes**:

Fixes #37479

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

File: pkg/controller/replication/replication_controller.go [hunk 1]
```diff
@@ -571,21 +571,21 @@ func (rm *ReplicationManager) syncReplicationController(key string) error {
...
-	for _, pod := range pods {
+	for _, pod := range allPods {
 		if controller.IsPodActive(pod) {
 			filteredPods = append(filteredPods, pod)
 		}
 	}
 	cm := controller.NewPodControllerRefManager(rm.podControl, rc, labels.Set(rc.Spec.Selector).AsSelectorPreValidated(), controllerKind)
 	// NOTE: filteredPods are pointing to objects from cache - if you need to
 	// modify them, you need to copy it first.
-	filteredPods, err = cm.ClaimPods(pods)
```
Comment (foxish) [inline pkg/controller/replication/replication_controller.go]: @enisoc This is the actual fix correct?

Comment (enisoc) [inline pkg/controller/replication/replication_controller.go]: Yes.

**Comment by ethernetdan** [comment]
@k8s-bot verify test this

**Comment by foxish** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot verify test this

**Comment by enisoc** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this

**Review by janetkuo — APPROVED** [review]
