### PR TITLE
Admit NoNewPrivs for remote and rkt runtimes

### LINKED ISSUE #51319: "NoNewPrivs" is admitted only if the runtime is docker or rkt in kubelet
I tried to add the `NoNewPrivs` support for `cri-containerd`, but the `test-e2e-node` always failed with the error print:
```
E0825 13:03:23.824134     814 pod_workers.go:182] Error syncing pod 29b8ba92-8952-11e7-93c7-5254003d4460 ("alpine-nnp-false-29ab6dfa-8952-11e7-958f-5254003d4460_e2e-tests-security-context-test-4jdbq(29b8ba92-8952-11e7-93c7-5254003d4460)"), skipping: pod cannot be run: Cannot enforce NoNewPrivs: containerd runtime not supported
```

I checked the code of k8s, and found that "NoNewPrivs" is admitted only if the runtime is docker or rkt in kubelet. Related code is as follows:
https://github.com/kubernetes/kubernetes/blob/0cf928f6813741d9699786ee61ec014c90119e2c/pkg/kubelet/lifecycle/handlers.go#L190-L225

Maybe we should define a interface to get the capability of "NoNewPrivs" form runtime-shim.

@Random-Liu @mikebrow

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

#51347 is aiming to admit NoNewPrivis for remote container runtime, but it didn't actually solve the problem. See @miaoyq 's comments [here](https://github.com/kubernetes/kubernetes/pull/51347#discussion_r135379446).

This PR always admit NoNewPrivs for runtimes except docker, which should fix the problem.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

Fixes #51319.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/lifecycle/handlers.go [hunk 1]
```diff
@@ -187,20 +187,11 @@ func (a *noNewPrivsAdmitHandler) Admit(attrs *PodAdmitAttributes) PodAdmitResult
 		return PodAdmitResult{Admit: true}
 	}
 
-	// Always admit for remote runtime.
-	if a.Runtime.Type() == kubetypes.RemoteContainerRuntime {
+	// Always admit runtimes except docker.
+	if a.Runtime.Type() != kubetypes.DockerContainerRuntime {
```
Comment (Random-Liu) [inline pkg/kubelet/lifecycle/handlers.go]: The following `if` is not needed, because it must be docker.

Comment (feiskyer) [reply pkg/kubelet/lifecycle/handlers.go]: good catch

**Comment by feiskyer** [comment]
@Random-Liu Addressed comments. PTAL
