### PR TITLE
Fix path to kubectl on host in kubectl-in-pod

### LINKED ISSUE #36586: [k8s.io] Kubectl client [k8s.io] Kubectl should be able to talk to api server kubectl running in a pod could talk to api server [Conformance] {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke/3658/

Failed: [k8s.io] Kubectl client [k8s.io] Kubectl should be able to talk to api server kubectl running in a pod could talk to api server [Conformance] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:585
Expected
    <*errors.errorString | 0xc4203ab040>: {
        s: "timed out waiting for the condition",
    }
to be nil
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:579
```

### PR DESCRIPTION
**Pull request by dims**
kubectl-in-pod.json has a hardcoded path for
kubectl in its hostPath ('/usr/bin/kubectl').
When the test actually runs on gke, kubectl
is available at '/workspace/kubernetes/platforms/linux/amd64/kubectl'
and NOT at '/usr/bin/kubectl'. So we need to
fix the hostPath for the test to work properly.

Fixes #36586

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36864)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot cvm gke e2e test this

**Comment by dims** [comment]
@k8s-bot gci gke e2e test this

**Comment by dims** [comment]
@k8s-bot cvm gke e2e test this

**Comment by dims** [comment]
@k8s-bot gci gke e2e test this

**Comment by dims** [comment]
@fejta @saad-ali : is there a way to trigger a job of this kind (https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gke) with this PR? the specific test i am trying to run does not seem to run in either "cvm gke e2e test this" or "gci gke e2e test this"

**Comment by dims** [comment]
@ymqytw : could use your eyes on this PR

**Comment by fejta** [comment]
@dims the full list of jobs you can trigger are specified here: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml

**Comment by dims** [comment]
@fejta thanks!. i already tried the 2 i found there ("gci gke e2e test this" and "cvm gke e2e test this")

**Comment by fejta** [comment]
Both are there:
gci gke == Jenkins GCI GKE smoke e2e
cvm gke == Jenkins GKE smoke e2e

See the `context` line in the jobs.yaml

**Comment by fejta** [comment]
Oh sorry I see what you're asking

**Comment by fejta** [comment]
And no right now we do not have a way to trigger CI jobs on PRs, but you can run them manually by following https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#building-and-running-the-tests

**Comment by dims** [comment]
Ack thanks for the follow up @fejta

**Comment by ymqytw** [comment]
@saad-ali Can you review it today? I really want this PR merged.

**Comment by saad-ali** [comment]
> @saad-ali Can you review it today? I really want this PR merged.

Me too! Taking a look!

**Review by saad-ali — APPROVED** [review]
/lgtm

**Comment by saad-ali** [comment]
Manually merging. (Submit queue is blocked).

```
13 successful checks:
Jenkins CRI GCE Node e2e — Build succeeded.
Jenkins GCE Node e2e — Build succeeded.
Jenkins GCE e2e — Build succeeded.
Jenkins GCE etcd3 e2e — Build succeeded.
Jenkins GCI GCE e2e — Build succeeded.
Jenkins GCI GKE smoke e2e — Build succeeded.
Jenkins GKE smoke e2e — Build succeeded.
Jenkins Kubemark GCE e2e — Build succeeded.
Jenkins unit/integration — Build succeeded.
Jenkins verification — Build succeeded.
Submit Queue — Queued to run github e2e tests a second time.
cla/google — All necessary CLAs are signed
cla/linuxfoundation — dims authorized
```

**Comment by saad-ali** [comment]
@dims @ymqytw Looks like this didn't fix the issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/20156/

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -566,8 +566,15 @@ var _ = framework.KubeDescribe("Kubectl client", func() {
 			framework.SkipUnlessProviderIs("gke")
 			nsFlag := fmt.Sprintf("--namespace=%v", ns)
 			podJson := readTestFileOrDie(kubectlInPodFilename)
+
+			// Replace the host path to kubectl in json
+			podString := strings.Replace(string(podJson),
+				"$KUBECTL_PATH",
+				framework.TestContext.KubectlPath,
```
Comment (ymqytw) [inline test/e2e/kubectl.go]: @dims @saad-ali Does `framework.TestContext.KubectlPath` miss quotation mark here?
The string being replaced has quotation mark.

Comment (ymqytw) [inline test/e2e/kubectl.go]: NVM

**Comment by dims** [comment]
@ymqytw @saad-ali : i added a bunch more debug statement in a new PR - https://github.com/kubernetes/kubernetes/pull/36966/

File: test/e2e/kubectl.go (hunk 1 above)
Comment (ymqytw) [inline test/e2e/kubectl.go]: @dims  If flag [kubectl-path](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L184) is not set, `framework.TestContext.KubectlPath` may be an empty string, right?

Comment (ymqytw) [inline test/e2e/kubectl.go]: I'm wrong.
It seems you default [kubectl-path](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L184) to `kubectl`.

Comment (dims) [inline test/e2e/kubectl.go]: @ymqytw : then a lot more stuff would break - https://github.com/kubernetes/kubernetes/blob/a7b63e1a959b63f17657ef90414c690fc441d316/test/e2e/framework/util.go#L2001

**Comment by apelisse** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke/4080

@dims This is clearly broken this this PR merged, should I revert?

**Comment by saad-ali** [comment]
Previously only [kubernetes-e2e-gke](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gke) was broken. Now [kubernetes-e2e-gci-gke](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gci-gke) is broken as well. I'm going to revert this PR as well as the PR that introduced the broken test, https://github.com/kubernetes/kubernetes/pull/33850 (which we should've reverted a long time ago).

**Comment by dims** [comment]
good call @saad-ali @apelisse
