### PR TITLE
Fixing federation controllers to support controllers flag

### LINKED ISSUE #42374: federation: Should be able to disable a federation controller
Right now only ingress controller supports it: https://github.com/kubernetes/kubernetes/blob/821e171247fb535debf6e9018967031025997aba/federation/cmd/federation-controller-manager/app/controllermanager.go#L196.
This is required for https://github.com/kubernetes/kubernetes/issues/38593

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/42374

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

File: federation/pkg/federation-controller/ingress/ingress_controller.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ const (
 	// We wait for ingress to be created in this cluster before creating it any
 	// other cluster.
 	firstClusterAnnotation = "ingress.federation.kubernetes.io/first-cluster"
-	ControllerName         = "ingress"
+	ControllerName         = "ingresses"
```
Comment (nikhiljindal) [inline federation/pkg/federation-controller/ingress/ingress_controller.go]: It should be fine to change this since this was added on HEAD after 1.5

File: federation/pkg/federation-controller/configmap/configmap_controller.go [hunk 2]
```diff
@@ -44,6 +45,11 @@ import (
 
 const (
 	allClustersKey = "ALL_CLUSTERS"
+	ControllerName = "configmaps"
```
Comment (marun) [inline federation/pkg/federation-controller/configmap/configmap_controller.go]: Does the fact that this matches with the resource type specified on L52 indicate that the indicate that this should be ``ResourceType`` or ``ResourceName``?  Also, consider using this constant in specifying ``RequiredResources``.

File: federation/cmd/federation-controller-manager/app/controllermanager.go [hunk 3]
```diff
@@ -154,44 +154,67 @@ func StartControllers(s *options.CMServer, restClientCfg *restclient.Config) err
...
-	glog.Infof("Running namespace controller")
-	namespaceController.Run(wait.NeverStop)
+	go clustercontroller.NewclusterController(ccClientset, s.ClusterMonitorPeriod.Duration).Run()
+
+	if controllerEnabled(s.Controllers, serverResources, servicecontroller.ControllerName, servicecontroller.RequiredResources, true) {
+		dns, err := dnsprovider.InitDnsProvider(s.DnsProvider, s.DnsConfigFile)
+		if err != nil {
+			glog.Fatalf("Cloud provider could not be initialized: %v", err)
+		}
+		glog.Infof("Loading client config for service controller %q", servicecontroller.UserAgentName)
```
Comment (marun) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: (no action required) Consider removing the ``Loading client config`` log lines.  I don't think they provide any value.

File: federation/cmd/federation-controller-manager/app/controllermanager.go [hunk 4]
```diff
@@ -154,44 +154,67 @@ func StartControllers(s *options.CMServer, restClientCfg *restclient.Config) err
...
 
-	glog.Infof("Loading client config for namespace controller %q", "namespace-controller")
-	nsClientset := federationclientset.NewForConfigOrDie(restclient.AddUserAgent(restClientCfg, "namespace-controller"))
-	namespaceController := namespacecontroller.NewNamespaceController(nsClientset, dynamic.NewDynamicClientPool(restclient.AddUserAgent(restClientCfg, "namespace-controller")))
-	glog.Infof("Running namespace controller")
-	namespaceController.Run(wait.NeverStop)
+	go clustercontroller.NewclusterController(ccClientset, s.ClusterMonitorPeriod.Duration).Run()
+
+	if controllerEnabled(s.Controllers, serverResources, servicecontroller.ControllerName, servicecontroller.RequiredResources, true) {
+		dns, err := dnsprovider.InitDnsProvider(s.DnsProvider, s.DnsConfigFile)
```
Comment (marun) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: Consider updating ``kubefed init`` so that ``--dns-provider`` is not mandatory (see #42092) when  ``services=false``.

**Review by marun — COMMENTED** [review]
I'm glad to see this!

File: federation/cmd/federation-controller-manager/app/controllermanager.go (hunk 4 above)
Comment (nikhiljindal) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: I dont want to do that in this PR. I know it has been discussed before. Is there an open issue for this or should I file a new one?

File: federation/pkg/federation-controller/configmap/configmap_controller.go (hunk 2 above)
Comment (nikhiljindal) [inline federation/pkg/federation-controller/configmap/configmap_controller.go]: This is controller name. Since we have a controller for each resource, we chose to use the resource name as controller name. They could be different in future.

**Comment by nikhiljindal** [comment]
Thanks for your comments @marun 
Replied. PTAL

File: federation/cmd/federation-controller-manager/app/controllermanager.go (hunk 4 above)
Comment (marun) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: There isn't an open issue because merging this PR would cause the problem.  I really think the parameter needs to be made optional in the PR that allows the services controller to be disabled.

Comment (marun) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: Nevermind, it's more complicated than I originally though.  It looks like it may be necessary for ``kubefed init`` to accept the ``--controllers`` argument as a first-class argument rather than passing it via ``--controllermanager--arg-overrides`` to allow detection of ``services=false`` in time to disable the check for the dns provider.  Please file an issue.

cc: @madhusudancs

File: federation/pkg/federation-controller/configmap/configmap_controller.go (hunk 2 above)
Comment (marun) [inline federation/pkg/federation-controller/configmap/configmap_controller.go]: YAGNI, but sure.

File: federation/cmd/federation-controller-manager/app/controllermanager.go (hunk 4 above)
Comment (madhusudancs) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: I would also completely defer this until we come up with a plan for structured config.

Comment (madhusudancs) [inline federation/cmd/federation-controller-manager/app/controllermanager.go]: The flag situation is kind of already becoming unwieldy.
