### PR TITLE
retry GetThirdPartyGroupVersions

### LINKED ISSUE #26425: [k8s.io] Kubectl client [k8s.io] Update Demo should do a rolling update of a replication controller [Conformance] {Kubernetes e2e suite}
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/17696/

Failed: [k8s.io] Kubectl client [k8s.io] Update Demo should do a rolling update of a replication controller [Conformance] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:234
Expected error:
    <*errors.errorString | 0xc820017360>: {
        s: "Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.56.157 --kubeconfig=/workspace/.kube/config get pods update-demo-kitten-2z6y0 -o template --template={{if (exists . \"status\" \"containerStatuses\")}}{{range .status.containerStatuses}}{{if (and (eq .name \"update-demo\") (exists . \"state\" \"running\"))}}true{{end}}{{end}}{{end}} --namespace=e2e-tests-kubectl-lxa8o] []  <nil>  Error from server: the server could not find the requested resource\n [] <nil> 0xc820ce2a80 exit status 1 <nil> true [0xc820fac2b0 0xc820fac2c8 0xc820fac2e0] [0xc820fac2b0 0xc820fac2c8 0xc820fac2e0] [0xc820fac2c0 0xc820fac2d8] [0x9dd540 0x9dd540] 0xc820f35da0}:\nCommand stdout:\n\nstderr:\nError from server: the server could not find the requested resource\n\nerror:\nexit status 1\n",
    }
    Error running &{/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.197.56.157 --kubeconfig=/workspace/.kube/config get pods update-demo-kitten-2z6y0 -o template --template={{if (exists . "status" "containerStatuses")}}{{range .status.containerStatuses}}{{if (and (eq .name "update-demo") (exists . "state" "running"))}}true{{end}}{{end}}{{end}} --namespace=e2e-tests-kubectl-lxa8o] []  <nil>  Error from server: the server could not find the requested resource
     [] <nil> 0xc820ce2a80 exit status 1 <nil> true [0xc820fac2b0 0xc820fac2c8 0xc820fac2e0] [0xc820fac2b0 0xc820fac2c8 0xc820fac2e0] [0xc820fac2c0 0xc820fac2d8] [0x9dd540 0x9dd540] 0xc820f35da0}:
    Command stdout:
    
    stderr:
    Error from server: the server could not find the requested resource
    
    error:
    exit status 1
    
not to have occurred
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
GetThirdPartyGroupVersions() may return a "NotFound" error if a thirdparty group is deleted in the interim between the group-discovery and the resource-discovery. This is causing e2e flakes in all tests that run kubectl, because test/e2e/thirdparty.go is creating/deleting thirdparty groups.

Fix #26425

The e2e flakes will have the following pattern:
1. the test is calling kubectl
2. error message is `Error from server: the server could not find the requested resource`
3. in the apiserver log, you should see `GET /apis/company.com/v1: (518.944µs) 404 [[kubectl/v1.3.0 (linux/amd64) kubernetes/ae28564] 104.154.110.118:46043]`

For detail see [here](https://github.com/kubernetes/kubernetes/issues/26425#issuecomment-222844523)

cc @janetkuo @brendanburns

### CODE REVIEW

File: pkg/kubectl/cmd/util/factory.go [hunk 1]
```diff
@@ -260,7 +261,18 @@ func NewFactory(optionalClientConfig clientcmd.ClientConfig) *Factory {
...
-				versions, gvks, err := GetThirdPartyGroupVersions(client.Discovery())
+				var versions []unversioned.GroupVersion
+				var gvks []unversioned.GroupVersionKind
+				retries := 3
+				for i := 0; i < retries; i++ {
+					versions, gvks, err = GetThirdPartyGroupVersions(client.Discovery())
+					// Retry if we got a NotFound error, because user may delete
+					// a thirdparty group when the GetThirdPartyGroupVersions is
+					// running.
+					if err == nil || !k8serrors.IsNotFound(err) {
```
Comment (janetkuo) [inline pkg/kubectl/cmd/util/factory.go]: why not retry in `GetThirdPartyGroupVersions`

Comment (caesarxuchao) [inline pkg/kubectl/cmd/util/factory.go]: Other callers of GetThirdPartyGroupVersions may want to handle the error differently.

File: pkg/kubectl/cmd/util/factory.go [hunk 2]
```diff
@@ -260,7 +261,18 @@ func NewFactory(optionalClientConfig clientcmd.ClientConfig) *Factory {
...
+						break
+					}
+				}
 				CheckErr(err)
```
Comment (janetkuo) [inline pkg/kubectl/cmd/util/factory.go]: The not found `err` will still be captured here.

Comment (janetkuo) [inline pkg/kubectl/cmd/util/factory.go]: never mind

**Comment by caesarxuchao** [comment]
Thanks for the quick review.

File: pkg/kubectl/cmd/util/factory.go [hunk 3]
```diff
@@ -38,6 +38,7 @@ import (
 
 	"k8s.io/kubernetes/federation/apis/federation"
 	"k8s.io/kubernetes/pkg/api"
+	k8serrors "k8s.io/kubernetes/pkg/api/errors"
```
Comment (janetkuo) [inline pkg/kubectl/cmd/util/factory.go]: Not sure if we have naming conventions for import aliases

Comment (caesarxuchao) [inline pkg/kubectl/cmd/util/factory.go]: Changed to apierrors, since that's how people usually name this alias.

**Comment by caesarxuchao** [comment]
Rename the import alias. Adding back the lgtm.

**Comment by caesarxuchao** [comment]
Added the milestone to make sure the fix is merged.
