### PR TITLE
VolumeBinding: Skip/fail fast in PreFilter phase and improve error reporting 

### LINKED ISSUE #91755: "unbound immediate PersistentVolumeClaims" should be UnschedulableAndUnresolvable error
when a pod has unbound immediate PersistentVolumeClaims, it's unscheduable and unresolvable as the pod must wait for the PV controller to bind these PVCs. ~~In VolumeBinding plugin, we can return an `UnschedulableAndUnresolvable` error to eliminate unnecessary retries~~ (not right, they have the same effect, but `UnschedulableAndUnresolvable` is more meaningful). Once the PVC(s) are bound, pods will be [moved to the active or backoff queue again](https://github.com/kubernetes/kubernetes/blob/1bc526aa6c310b915e7ad57b4442deec7328aad2/pkg/scheduler/eventhandlers.go#L55-L61).

ref: https://github.com/kubernetes/kubernetes/pull/91679#discussion_r434554404

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

- pod volumes information is checked only once in PreFilter phase
- return UnscheduableAndUnresolvable error if some immediate PVCs are not bound 

**Which issue(s) this PR fixes**:

Fixes #91755 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/volume/scheduling/scheduler_binder.go [hunk 1]
```diff
@@ -248,20 +254,10 @@ func (b *volumeBinder) FindPodVolumes(pod *v1.Pod, node *v1.Node) (reasons Confl
...
-
-	// Immediate claims should be bound
-	if len(unboundClaimsImmediate) > 0 {
-		return nil, fmt.Errorf("pod has unbound immediate PersistentVolumeClaims")
-	}
-
 	// Check PV node affinity on bound volumes
 	if len(boundClaims) > 0 {
+		// TODO if node affinity does not match, we should
+		// UnschedulableAndUnresolvable error back to scheduler framework
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_binder.go:260]: UnschedulableAndUnresolvable error is more meaningful than internal error, this can be in a separate PR

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 2]
```diff
@@ -35,14 +36,17 @@ const (
...
 type stateData struct {
-	allBound bool
+	skip         bool // set true if pod does not have PVCs
+	boundClaims  []*v1.PersistentVolumeClaim
+	claimsToBind []*v1.PersistentVolumeClaim
+	allBound     bool
 }
 
-func (d stateData) Clone() framework.StateData {
+func (d *stateData) Clone() framework.StateData {
```
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:49]: saving pointers instead of structs

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 3]
```diff
@@ -81,6 +86,48 @@ func podHasPVCs(pod *v1.Pod) bool {
 	return false
 }
 
+// PreFilter invoked at the prefilter extension point to check if pod has all
+// immediate PVCs bound. If not all immediate PVCs are bound, an
+// UnschedulableAndUnresolvable is returned.
+func (pl *VolumeBinding) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) *framework.Status {
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:92]: Can we add unit tests for these new states and status?

**Review by msau42 — COMMENTED** [review]
Thanks for doing this! Just one ask for more unit tests

File: pkg/controller/volume/scheduling/scheduler_binder.go (hunk 1 above)
Comment (cofyc) [reply pkg/controller/volume/scheduling/scheduler_binder.go]: made a mistake here, it's already an UnschedulableAndUnresolvable error now

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go (hunk 3 above)
Comment (cofyc) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:92]: pushed a new commit https://github.com/kubernetes/kubernetes/pull/91775/commits/67c9ed7f4ee328a4c13fcf5f51fefbbc8ea84800

I removed the usage of FakeVolumeBinder. I think it's better to use fake kubernetes client with real volume binder 
I also removed some unnecessary tests and add new tests for `PreFilter` statues and states.

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go [hunk 4]
```diff
@@ -18,99 +18,287 @@ package volumebinding
...
+		wantPreFilterStatus     *framework.Status
+		wantStateAfterPreFilter *stateData
+		wantFilterStatus        *framework.Status
 	}{
 		{
-			name:       "nothing",
-			pod:        &v1.Pod{},
-			node:       &v1.Node{},
-			wantStatus: nil,
+			name: "pod has not pvcs",
```
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:115]: renamed `nothing` to `pod has not pvcs`, the pod can be skipped if it does not use PVCs

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go [hunk 5]
```diff
@@ -18,99 +18,287 @@ package volumebinding
...
+			},
+			wantStateAfterPreFilter: &stateData{
+				boundClaims: []*v1.PersistentVolumeClaim{
+					makePVC("pvc-a", "pv-a", waitSC.Name),
+				},
+				claimsToBind: []*v1.PersistentVolumeClaim{},
+			},
+		},
+		{
+			name: "immediate claims not bound",
```
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:140]: newly added case

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go [hunk 6]
```diff
@@ -18,99 +18,287 @@ package volumebinding
...
+			name:                "pvc not found",
+			pod:                 makePod("pod-a", []string{"pvc-a"}),
+			node:                &v1.Node{},
+			wantPreFilterStatus: framework.NewStatus(framework.Error, `error getting PVC "default/pvc-a": could not find v1.PersistentVolumeClaim "default/pvc-a"`),
+			wantFilterStatus:    nil,
 		},
 		{
-			name: "predicate error",
-			pod:  &v1.Pod{Spec: volState},
+			name: "pv not found",
```
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding_test.go:212]: `predicate error` is removed, and add two new tests which will return internal errors

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 7]
```diff
@@ -35,14 +36,17 @@ const (
 	// DefaultBindTimeoutSeconds defines the default bind timeout in seconds
 	DefaultBindTimeoutSeconds = 600
 
-	allBoundStateKey framework.StateKey = "volumebinding:all-bound"
+	stateKey framework.StateKey = Name
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:39]: Unrelated to this PR, but could we potentially use this state mechanism to get rid of the PodBindingCache, which is only relevant for a single scheduling cycle?

**Review by msau42 — COMMENTED** [review]
/lgtm
/approve
/retest

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go (hunk 7 above)
Comment (cofyc) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:39]: Yes, this is planned https://github.com/kubernetes/kubernetes/issues/90962

**Comment by cofyc** [comment]
@ahg-g can you take a look at scheduler change?

**Comment by ahg-g** [comment]
/approve

This is nice, thanks! do we have a benchmark that evaluates this optimization?

**Comment by cofyc** [comment]
rebased on the master and fixed a UT, @msau42 can you LGTM again?

**Comment by cofyc** [comment]
> /approve
> 
> This is nice, thanks! do we have a benchmark that evaluates this optimization?

there is a benchmark `BenchmarkSchedulingWaitForFirstConsumerPVs` in scheduler_perf pkg:

before:

```
goos: linux
goarch: amd64
pkg: k8s.io/kubernetes/test/integration/scheduler_perf
BenchmarkSchedulingWaitForFirstConsumerPVs/500Nodes/500Pods-12         	    1000	  76636331 ns/op
PASS
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	100.857s
```

 after

```
goos: linux
goarch: amd64
pkg: k8s.io/kubernetes/test/integration/scheduler_perf
BenchmarkSchedulingWaitForFirstConsumerPVs/500Nodes/500Pods-12         	    1000	  75067825 ns/op
PASS
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	99.305s
```

This benchmarks the dynamic provisioning scenario with a mock storage provisioner. Another scenario is the static provisioning. Maybe we can add a bench later.

**Comment by msau42** [comment]
This fix would mostly improve the Immediate binding unbound case, which I don't think there's a benchmark for

**Comment by cofyc** [comment]
added a TODO for volume scheduling benchmarks in https://github.com/kubernetes/kubernetes/issues/90962

it's complicated to bench volume scheduling as the number of claims used in the pod and static PVs pre-provisioned in the cluster also affects the performance of scheduling (except the binding phase, as it mostly waits for PV controller and external provisioner).
