### PR TITLE
Wait for the job to be removed

### LINKED ISSUE #64362: Failing Test: Multiple [sig-cli] Kubectl client [k8s.io] tests failing in sig-release-master-upgrade suite
## Failing Job
* [gce-1.10-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-cluster-parallel)
* [gke-gci-1.10-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-parallel)

## Failing Test
* [[sig-cli] Kubectl client [k8s.io] Kubectl run --rm job should create a job from an image, then delete the job [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-kubectl-run---rm-job-should-create-a-job-from-an-image-then-delete-the-job-conformance)
* [[sig-cli] Kubectl client [k8s.io] Update Demo should create and stop a replication controller [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-update-demo-should-create-and-stop-a-replication-controller-conformance)
* [[sig-cli] Kubectl client [k8s.io] Update Demo should scale a replication controller [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-parallel/5061#sig-cli-kubectl-client-k8sio-update-demo-should-scale-a-replication-controller-conformance)

Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=cli&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel&test=Kubectl%20client

This test started failing consistently in the upgrade jobs since 5/21 evening.

/kind bug
/priority failing-test
/priority important-soon
/sig cli
/milestone v1.11
@kubernetes/sig-cli-bugs 

cc @jberkus @tpepper

/assign @liggitt 

@liggitt we are seeing consistent Kubectl failures in sig-release-master-upgrade jobs. Can you please triage this as priority and let us know if we can resolve it by Code freeze (6/5)?

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
In master we've dropped reapers (#63979) which means the old client does not wait long enough for the resource to be gone (since it's being removed on the server along with its dependents). To fix our e2e ([failure here](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew/7980)) we need to backport parts of the aforementioned PR which is updating tests to wait for the resource to be removed. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64362

/assign @MaciekPytel 
/assign @deads2k 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/kubectl/kubectl.go [hunk 1]
```diff
@@ -1444,8 +1444,11 @@ metadata:
 			Expect(runOutput).To(ContainSubstring("abcd1234"))
 			Expect(runOutput).To(ContainSubstring("stdin closed"))
 
+			err := framework.WaitForJobGone(c, ns, jobName, wait.ForeverTestTimeout)
+			Expect(err).NotTo(HaveOccurred())
+
 			By("verifying the job " + jobName + " was deleted")
-			_, err := c.BatchV1().Jobs(ns).Get(jobName, metav1.GetOptions{})
+			_, err = c.BatchV1().Jobs(ns).Get(jobName, metav1.GetOptions{})
```
Comment (dixudx) [inline test/e2e/kubectl/kubectl.go]: So we can use `_, err = framework.WaitForJobGone(c, ns, jobName, 0)` here, right?

Comment (soltysh) [reply test/e2e/kubectl/kubectl.go]: Yeah, I guess we could, but I've just backported what we have in master right now.

**Comment by deads2k** [comment]
This is the equivalent of the e2es we have in master that do the "wait for GC" now, right?

/lgtm

**Comment by soltysh** [comment]
> This is the equivalent of the e2es we have in master that do the "wait for GC" now, right?

Yup
