### PR TITLE
Fix unused Secret export logic.

### LINKED ISSUE #49042: Several API type strategies have Export func that may be unused
/kind bug

**What happened**:

Secrets have some export logic in their strategy, but does not appear to take effect on the command line when doing a kubectl get --export.

**What you expected to happen**:

Some kind of error given the condition in the secret strategy mentioned below. However it appears the secret strategy Export function may not be wired up. (as well as several other types)

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubeadm init
$ kubectl get secret default-token-w5cs4 -o yaml --export
```

No error is thrown, some generic metadata is stripped but the code is happy to export the object despite the fact that it violates the condition mentioned below.

**Anything else we need to know?**:

In the generic registry Store we can see the main place where exports should be run:

https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1227

This ExportStrategy is set in a handful of strategies, such as:

https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/limitrange/storage/storage.go#L46

In addition to limitrange we find similar for node, podtemplate, and service strategies.

However several other strategies have an Export function defined matching: Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error

```
(dgoodwin@wrx {master} ~/go/src/k8s.io/kubernetes) $ git grep Export | grep Context | grep Object | grep bool
pkg/registry/certificates/certificates/strategy.go:func (s csrStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/limitrange/strategy.go:func (limitrangeStrategy) Export(genericapirequest.Context, runtime.Object, bool) error {
pkg/registry/core/node/strategy.go:func (ns nodeStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/podtemplate/strategy.go:func (podTemplateStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/secret/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/core/service/strategy.go:func (svcStrategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/clusterrole/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/clusterrolebinding/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/role/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
pkg/registry/rbac/rolebinding/strategy.go:func (s strategy) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go:func (t testPodExport) Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error {
staging/src/k8s.io/apiserver/pkg/registry/rest/export.go:       Export(ctx genericapirequest.Context, obj runtime.Object, exact bool) error
```

Looking specifically at the Secret strategy: https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/secret/strategy.go#L79

It appears that this Export method may not be wired up and thus is unused. In testing with kubectl on the API, it appears we cannot get the condition on line 90 in the link above to trigger even if trying to kubectl get --export secrets X where X is of type kubernetes.io/service-account-token, or is tied to a service account by UID.

This may imply that secret, clusterrole, clusterrolebinding, role, and rolebinding strategies all have an Export function defined that is not used.

The fix might just be as simple as setting ExportStrategy in places such as: https://github.com/kubernetes/kubernetes/blob/10dc1aac61f8f2e9a9381a525289d8ae87ba0cc9/pkg/registry/core/secret/storage/storage.go#L44

If so please let me know and I will try to pursue unit tests and a fix for each.

**Environment**:
- Kubernetes version (use `kubectl version`): 
  ```
  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): Linux centos1.aos.example.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm, oc

### PR DESCRIPTION
**Pull request by dgoodwin**
**What this PR does / why we need it**:

The strategy used for the secret store defined custom export logic, and
had accompanying unit tests. However the secret storage did not actually
wire this up by setting an ExportStrategy and thus the code was never
used in the real world.

This change fixes the missing assignment and adds testing at a higher
level to ensure any uses of the generic registry.Store that we expect to
have an ExportStrategy do, and no others.

Several other strategies in the RBAC package also appeared to have
unwired Export logic, however their implementations were all empty
leading me to believe that these are not considered exportable. The
empty methods have now been removed.

**Which issue this PR fixes**: fixes #49042

**Release note**:

```release-note
```

### CODE REVIEW

File: pkg/master/master_test.go [hunk 1]
```diff
@@ -112,6 +115,61 @@ func setUp(t *testing.T) (*etcdtesting.EtcdTestServer, Config, *assert.Assertion
...
+	_, _, masterCfg, _ := newMaster(t)
+	storageProvider := corerest.LegacyRESTStorageProvider{
+		StorageFactory:       masterCfg.StorageFactory,
+		ProxyTransport:       masterCfg.ProxyTransport,
+		KubeletClientConfig:  masterCfg.KubeletClientConfig,
+		EventTTL:             masterCfg.EventTTL,
+		ServiceIPRange:       masterCfg.ServiceIPRange,
+		ServiceNodePortRange: masterCfg.ServiceNodePortRange,
+		LoopbackClientConfig: masterCfg.GenericConfig.LoopbackClientConfig,
+	}
```
Comment (dgoodwin) [inline pkg/master/master_test.go]: Unfortunately had to test at the master package level. Ideally this would have been with the LegacyRESTStorageProvider, however this requires substantial plumbing to instantiate so we could get at the internal storage map, all of which existed here in the master package. This package is also the location where it is used.

I can re-attempt this if desired however it will mean a much larger patch to copy or refactor code, as it's a lot of plumbing and there's additionally a circular dependency at play between the two packages.

**Comment by dgoodwin** [comment]
CC @deads2k

File: pkg/master/master_test.go [hunk 2]
```diff
@@ -112,6 +115,61 @@ func setUp(t *testing.T) (*etcdtesting.EtcdTestServer, Config, *assert.Assertion
...
+
+	_, apiGroupInfo, err := storageProvider.NewLegacyRESTStorage(masterCfg.GenericConfig.RESTOptionsGetter)
+	if err != nil {
+		t.Errorf("failed to create legacy REST storage: %v", err)
+	}
+
+	// Any new stores with export logic will need to be added here:
```
Comment (deads2k) [inline pkg/master/master_test.go]: eventually we should reverse this

File: pkg/registry/core/rest/validate.go [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+import (
+	"fmt"
+	"k8s.io/apiserver/pkg/registry/generic/registry"
+	"k8s.io/apiserver/pkg/registry/rest"
+	"k8s.io/kubernetes/pkg/util/slice"
+)
+
+// ValidateStorageStrategies ensures any instances of the generic registry.Store in the given storage map
+// have expected strategies defined.
+func ValidateStorageStrategies(storageMap map[string]rest.Storage, exceptions StrategyExceptions) []error {
```
Comment (deads2k) [inline pkg/registry/core/rest/validate.go]: This looks like it should be in an apiserver/pkg/registry/registrytesting package

**Comment by deads2k** [comment]
minor package swizzling and this lgtm.

**Comment by dgoodwin** [comment]
Moved to what I think you intended for registrytest package (it was in a slightly diff location). Thanks for the quick turnaround on review!

**Comment by dgoodwin** [comment]
@deads2k how's this looking to you?
