### PR TITLE
fix race condition issue when detaching azure disk

### LINKED ISSUE #60101: Azure Disk Detach are not working with multiple disk detach on the same Node.
/kind bug

**What happened**:
I'm running a POD with three VolumeMount (AzureDisk PVC). If I delete the pod, it gets rescheduled on a different node. The 3 disks are unmounted from the original node (thanks to kubelet) and the disks are starting to get unattached from the VM.

Out of the three disks, only one was able to get unattached, it was properly reattached to the new node waiting to run the freshly restarted pod.

The other two Disks couldn't be detached. 

The controller manager keeps trying to attach from this point on while never trying to re-detach.

**What you expected to happen**:
Kube-controller-manager should retry detaching disks after failures.

**How to reproduce it (as minimally and precisely as possible)**:
* create a pod with 3 volume mounts (AzureDisk). 
* Kill the running pod.
* watch the status
If it works, retry

**Anything else we need to know?**:
kube-controller-manager logs (--v=4)

https://gist.github.com/djsly/3d934669f1a0db8f9a9a7d446f4962f9

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.12
- Cloud provider or hardware configuration: azure
- OS (e.g. from /etc/os-release): centOS 7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.11.6.el7.x86_64
- Install tools: in-house (terraform + salt)

cc: @khenidak @feiskyer

### PR DESCRIPTION
**Pull request by andyzhangx**
**What this PR does / why we need it**:
add lock before detaching azure disk, without this PR, there would be lots of `Multi-Attach error` when scheduling one pod from one node to another.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60101

**Special notes for your reviewer**:
@feiskyer @djsly @khenidak 
Since we are using `getLunMutex.LockKey(instanceid)` for both AttachDisk and DetachDisk, there would be only one VM.update operation at a time for both AttachDisk and DetachDisk.

**Release note**:

```
fix race condition issue when detaching azure disk
```

/assign @feiskyer 
Could you also mark as v1.10 milestone @feiskyer thanks.
/sig azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
@khenidak I think lots of `Multi-Attach error` of azure disk was due to this bug, it's really bad we do not lock before detaching azure disk...

**Comment by djsly** [comment]
Looking good on my side. 
I will apply the patch on my local 1.7 source and test it out tomorrow.  We have another issue with PV and I want to confirm it is the same source.

**Comment by andyzhangx** [comment]
@djsly just replace the controller manager, thanks.

**Review by feiskyer — COMMENTED** [review]
LGTM with the changes.

Let's wait a while for @djsly's validation.

File: pkg/volume/azure_dd/attacher.go [hunk 1]
```diff
@@ -268,7 +268,7 @@ func (d *azureDiskDetacher) Detach(diskURI string, nodeName types.NodeName) erro
 		return fmt.Errorf("invalid disk to detach: %q", diskURI)
 	}
 
-	_, err := d.cloud.InstanceID(context.TODO(), nodeName)
+	instanceid, err := d.cloud.InstanceID(context.TODO(), nodeName)
```
Comment (brendandburns) [inline pkg/volume/azure_dd/attacher.go]: context.TODO() seems like a mistake here? is there a context we can attach to?

Comment (andyzhangx) [reply pkg/volume/azure_dd/attacher.go]: @brendanburns it's related to https://github.com/kubernetes/kubernetes/pull/59287, there is some future work item for `context.TODO()`

**Comment by djsly** [comment]
@andyzhangx here are the logs for my latest test after I applied the patch on the 1.7 branch.

https://gist.github.com/djsly/d04edbd3239373f345ca27616ddd5132

Things are looking good!

Except the Multi-Attach error. This seems to be caused by the reconciler. It last ~2m30sec until the disks are unmounted and the first detach kicks in.

Could you confirm that those warnings do not involve the ARM api ?

`Multi-Attach error for volume "pvc-91d3b0a6-11b9-11e8-82b7-000d3a018ac3" (UniqueName: "kubernetes.io/azure-disk//subscriptions/<sub_id>/resourceGroups/<rg>/providers/Microsoft.Compute/disks/<rg>-dynamic-pvc-91d3b0a6-11b9-11e8-82b7-000d3a018ac3") from node "kn-edge-2" Volume is already exclusively attached to one node and can't be attached to another`

**Comment by djsly** [comment]
Also, could we have this PR cherry picked all the way to 1.7 ? thanks!

**Comment by brendandburns** [comment]
/lgtm
/approve

@jdumars can you shepard this into 1.7.x and 1.8.x?

Thanks!

**Comment by andyzhangx** [comment]
@djsly I checked the code again, current `Multi-Attach error` from [reconciler](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/reconciler/reconciler.go#L318-L325) is expected, it does not come from ARM api, it's a error message generated by reconciler.
When one pod is rescheduled from node#1 to node#2, [`DisksAreAttached` func](https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/azure/azure_controllerCommon.go#L246-L271) in azure_controllerCommon.go will still return that the original disk is still in node#1, after around one minute, disk was removed from node#1, and then the `Multi-Attach error` from reconciler disappears.

I will cherry pick this PR to v1.7-1.9.
@djsly Thanks again for your reporting and verification, finally we resolved this `Multi-Attach error` issue.

**Comment by djsly** [comment]
My pleasure and thanks for the quick PR.

**Comment by andyzhangx** [comment]
@karataliu @rootfs FYI

**Comment by jdumars** [comment]
@mehdy @jpbetz @wojtek-t this is an important cherry pick
