### PR TITLE
Make it possible to enable controller-managed attach-detach on existing nodes

### LINKED ISSUE #31673: Kubelet fails to annotate existing nodes that have controller attach-detach enabled
When the controller-attach-detach refactor was done, code was added to the Kubelet to annotate the node in a way that the attach-detach controller recognizes as meaning that the controller should manage attach/detach for attachable PVs scheduled to that node.  However, this is only done **if the node does not already exist**.  If the node already exists, the API registration code will only delete and recreate it if the `ExternalID` field has changed.  The correct behavior is for the annotation for controller attach-detach to be set based on the current configuration of the Kubelet, whether the node already exists or not.

I am working on a fix for this now -- will submit a PR tomorrow, probably, but wanted to record the bug.

cc @kubernetes/sig-storage

### PR DESCRIPTION
**Pull request by pmorie**
Fixes #31673.  Now, if a node already exists with the given name on Kubelet startup, the Kubelet will reconcile the value of the controller-managed-attach-detach annotation so that existing nodes can have this feature turned on and off by changing the Kubelet configuration.

cc @kubernetes/sig-storage @kubernetes/rh-cluster-infra

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31730)

### CODE REVIEW

**Comment by pmorie** [comment]
@k8s-bot ok to test

File: pkg/kubelet/kubelet_node_status.go [hunk 1]
```diff
@@ -39,67 +39,117 @@ import (
...
+			if !newSet {
+				glog.Info("Controller attach-detach setting changed to false; updating existing Node")
+				delete(existingNode.Annotations, volumehelper.ControllerManagedAttachAnnotation)
 			} else {
-				glog.Errorf("Deleted old node object %q", kl.nodeName)
+				glog.Info("Controller attach-detach setting changed to true; updating existing Node")
+				existingNode.Annotations[volumehelper.ControllerManagedAttachAnnotation] = newCMAAnnotation
+			}
+
+			if _, err := kl.kubeClient.Core().Nodes().Update(existingNode); err != nil {
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: @smarterclayton @deads2k do we have to worry about accidentally dropping new fields in an apiserver/kubelet version skew?

Comment (pmorie) [inline pkg/kubelet/kubelet_node_status.go]: @ncdc I think that would be equally applicable to any resource Kubelet can update, wouldn't it?

File: pkg/kubelet/kubelet_node_status.go [hunk 2]
```diff
@@ -39,67 +39,117 @@ import (
...
+			glog.Infof("Successfully registered node %s", node.Name)
+			kl.registrationCompleted = true
+			return
+		}
+	}
+}
+
+// registerWithApiServerAttempt makes an attempt to register the given node
+// with the API server, returning a boolean indicating whether the attempt was
+// successful.  If a node with the same name already exists, it reconciles the
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: This doesn't seem like we have good separation of concerns here. What would you think about a separate method that's called in the startup flow that reconciles the annotation?

File: pkg/kubelet/kubelet_node_status.go [hunk 3]
```diff
@@ -39,67 +39,117 @@ import (
...
+	}
+
+	if existingNode.Spec.ExternalID == node.Spec.ExternalID {
+		glog.Infof("Node %s was previously registered", kl.nodeName)
+
+		// Edge case: the node was previously registered; reconcile
+		// the value of the controller-managed attach-detach
+		// annotation.
+		var (
+			existingCMAAnnotation, _ = existingNode.Annotations[volumehelper.ControllerManagedAttachAnnotation]
```
Comment (saad-ali) [inline pkg/kubelet/kubelet_node_status.go]: Is the `, _` required?

File: pkg/kubelet/kubelet_node_status.go (hunk 2 above)
Comment (pmorie) [inline pkg/kubelet/kubelet_node_status.go]: I would prefer to hide all of this inside of `registerWithApiServer`, possibly renaming to `registerOrReconcileNodeWithApiServer`.

File: pkg/kubelet/kubelet_node_status.go (hunk 3 above)
Comment (pmorie) [inline pkg/kubelet/kubelet_node_status.go]: nerp!

File: pkg/kubelet/kubelet_node_status.go (hunk 2 above)
Comment (pmorie) [inline pkg/kubelet/kubelet_node_status.go]: I'm not really sure that it's worth refactoring now -- this is a fix for a p1 and it's needed downstream as well.  Do you have an objection, besides the factoring, @ncdc?

**Comment by saad-ali** [comment]
LGTM. But I'll leave it to someone on @kubernetes/sig-node to sign off since this is mostly touching kubelet functionality.

File: pkg/kubelet/kubelet_node_status.go (hunk 1 above)
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: Yeah, nevermind

File: pkg/kubelet/kubelet_node_status.go (hunk 2 above)
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: No, it's fine to proceed

**Comment by ncdc** [comment]
@k8s-bot unit test this issue: #30228

File: pkg/kubelet/kubelet_node_status.go [hunk 4]
```diff
@@ -39,67 +39,117 @@ import (
...
+func (kl *Kubelet) registerWithApiServer() {
 	if kl.registrationCompleted {
 		return
 	}
 	step := 100 * time.Millisecond
+
 	for {
-		time.Sleep(step)
+		// wake up and calculate the next backoff
+		timer := time.NewTimer(step)
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: Why did you switch to using a timer? And you'll need to stop it, won't you?

File: pkg/kubelet/kubelet_node_status.go [hunk 5]
```diff
@@ -39,67 +39,117 @@ import (
...
+}
+
+// registerWithApiServerAttempt makes an attempt to register the given node
+// with the API server, returning a boolean indicating whether the attempt was
+// successful.  If a node with the same name already exists, it reconciles the
+// value of the annotation for controller-managed attach-detach of attachable
+// persistent volumes for the node.  If a node of the same name exists but has
+// a different externalID value, it attempts to delete that node so that a
+// later attempt can recreate it.
+func (kl *Kubelet) registerWithApiServerAttempt(node *api.Node) bool {
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: I would probably call this tryRegisterWithApiServer

File: pkg/kubelet/kubelet_node_status.go [hunk 6]
```diff
@@ -39,67 +39,117 @@ import (
...
+	_, err := kl.kubeClient.Core().Nodes().Create(node)
+	if err == nil {
+		return true
+	}
+
+	if !apierrors.IsAlreadyExists(err) {
+		glog.Errorf("Unable to register node %q with API server: %v", kl.nodeName, err)
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: We're supposed to use `utilruntime.HandleError` instead of `glog.Error`, but looking at `pkg/kubelet`, I see that the latter happens much more than the former.

File: pkg/kubelet/kubelet_node_status.go [hunk 7]
```diff
@@ -39,67 +39,117 @@ import (
...
+				glog.Info("Controller attach-detach setting changed to false; updating existing Node")
+				delete(existingNode.Annotations, volumehelper.ControllerManagedAttachAnnotation)
 			} else {
-				glog.Errorf("Deleted old node object %q", kl.nodeName)
+				glog.Info("Controller attach-detach setting changed to true; updating existing Node")
+				existingNode.Annotations[volumehelper.ControllerManagedAttachAnnotation] = newCMAAnnotation
+			}
+
+			if _, err := kl.kubeClient.Core().Nodes().Update(existingNode); err != nil {
+				glog.Errorf("Unable to register node %q with API server: error updating node: %v", kl.nodeName, err)
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: I'd change the log message so it doesn't mention registering, since the node was already registered by the time we get here

File: pkg/kubelet/kubelet_node_status_test.go [hunk 8]
```diff
@@ -896,3 +897,193 @@ func TestRegisterExistingNodeWithApiserver(t *testing.T) {
...
+		}
+
+		if tc.testSavedNode {
+			var savedNode *api.Node
+			var ok bool
+
+			t.Logf("actions: %v: %+v", len(actions), actions)
+			action := actions[tc.savedNodeIndex]
+			if action.GetVerb() == "create" {
+				createAction, _ := action.(core.CreateAction)
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status_test.go]: Don't need _

File: pkg/kubelet/kubelet_node_status_test.go [hunk 9]
```diff
@@ -896,3 +897,193 @@ func TestRegisterExistingNodeWithApiserver(t *testing.T) {
...
+				savedNode, ok = createAction.GetObject().(*api.Node)
+				if !ok {
+					t.Errorf("%v: unexpected type; couldn't convert to *api.Node: %+v", tc.name, createAction.GetObject())
+					continue
+				}
+			} else if action.GetVerb() == "update" {
+				updateAction, _ := action.(core.UpdateAction)
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status_test.go]: _

File: pkg/kubelet/kubelet_node_status_test.go [hunk 10]
```diff
@@ -896,3 +897,193 @@ func TestRegisterExistingNodeWithApiserver(t *testing.T) {
...
+				savedNode, ok = updateAction.GetObject().(*api.Node)
+				if !ok {
+					t.Errorf("%v: unexpected type; couldn't convert to *api.Node: %+v", tc.name, updateAction.GetObject())
+					continue
+				}
+			}
+
+			annValue, ok := savedNode.Annotations[volumehelper.ControllerManagedAttachAnnotation]
+			if tc.savedNodeCMAD {
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status_test.go]: Could you simplify this to just compare tc.savedNodeCMAD to annValue? annValue will be "" if it doesn't exist in the map, and if it does exist, then a direct comparison should be sufficient, right?

File: pkg/kubelet/kubelet_node_status.go [hunk 11]
```diff
@@ -137,10 +187,10 @@ func (kl *Kubelet) initialNodeStatus() (*api.Node, error) {
 
 	// @question: should this be place after the call to the cloud provider? which also applies labels
 	for k, v := range kl.nodeLabels {
-		if cv, found := node.ObjectMeta.Labels[k]; found {
+		if cv, found := node.Labels[k]; found {
```
Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: I realize there isn't an issue with the removal of ObjectMeta here, but if you want to reduce risk by reducing the # of LOC that change, you could omit these ObjectMeta changes.

File: pkg/kubelet/kubelet_node_status.go (hunk 6 above)
Comment (pmorie) [inline pkg/kubelet/kubelet_node_status.go]: I'll use it here and make do a follow up after 1.5 opens to switch over throughout the kubelet

Comment (ncdc) [inline pkg/kubelet/kubelet_node_status.go]: SGTM

**Comment by pmorie** [comment]
Adding this to the 1.4 milestone because it fixes a bug where it is not possible to enable controller-managed attach-detach on existing nodes by flipping the switch on the kubelet.  If someone tries to do this, the behavior is that no attachable volumes will work -- the kubelet will wait for the controller to attach, and the controller will never attach.

**Comment by pmorie** [comment]
Found a bug; fixing

**Comment by pmorie** [comment]
@k8s-bot unit test this issue: #31492

**Comment by yujuhong** [comment]
LGTM

**Comment by vishh** [comment]
LGTM excepting one nit

---

Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/kubelet/kubelet_node_status.go, line 108 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31730#-KQXP1lUXDSaFtJE3UAG:-KQXP1lUXDSaFtJE3UAH:bkf3pi9) ([raw file](https://github.com/kubernetes/kubernetes/blob/c5d02577b2484ff5f36baee5d9f439ed65bbb6ab/pkg/kubelet/kubelet_node_status.go#L108)):*
> ```Go
> 		// the value of the controller-managed attach-detach
> 		// annotation.
> 		requiresUpdate := kl.reconcileCMADAnnotationWithExistingNode(node, existingNode)
> ```

nit: Is `existingNode` already being mutated? It might be better if this method returns a mutated node object instead.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31730#-:-KQXQgc_7sYOHZMRHH4_:bk3sn5)*

**Comment by pmorie** [comment]
@vishh it's not already being mutated, no.

**Comment by pmorie** [comment]
@vishh and I agreed in slack to let the nit stand.

**Comment by vishh** [comment]
cc @pwittrock for tracking this PR for v1.4

**Comment by eparis** [comment]
@k8s-bot unit test this issue: 31850
