### PR TITLE
kubeadm: fix CRI ListKubeContainers API

### LINKED ISSUE #926: kubeadm reset doesn't work properly with containerd
BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:19:15Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:21:58Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:13:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- **Cloud provider or hardware configuration**:
Brightbox
- **OS** (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- **Kernel** (e.g. `uname -a`):
Linux srv-4pp5n 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:
containerd github.com/containerd/containerd v1.1.1-rc.0 395068d2b7256518259816ae19e45824b15da071

## What happened?
```
[reset] cleaning up running containers using crictl with socket /var/run/containerd/containerd.sock
[reset] failed to stop the running containers using crictl: exit status 1. Trying to use docker instead[reset] docker doesn't seem to be running. Skipping the removal of running Kubernetes containers
```

The containerd logs show the request for some odd named pods

```
Jun 15 16:14:59 srv-4pp5n containerd[2416]: time="2018-06-15T16:14:59Z" level=info msg="StopPodSandbox for "W0615""
Jun 15 16:14:59 srv-4pp5n containerd[2416]: time="2018-06-15T16:14:59Z" level=error msg="StopPodSandbox for "W0615" failed" error="an error occurred when try to find sandbox "W0615": does not exist"
```

## What you expected to happen?
kubeadm reset ought to read the config file initially used with init (so pick up the cri-socket) and then correctly remove the pods

## How to reproduce it (as minimally and precisely as possible)?
`kubeadm init --config=kubeadm.conf` with

```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 0.0.0.0
networking:
  serviceSubnet: fd00:1234::/110
kubernetesVersion: 1.11.0-beta.2
cloudProvider: external
featureGates:
  "CoreDNS": false

criSocket: /var/run/containerd/containerd.sock
```

then

`kubeadm reset --cri-socket=/var/run/containerd/containerd.sock`

## Anything else we need to know?
If you run kubeadm reset without the cri-socket it still tries to talk to docker and misses the containers completely. Isn't the choice to use containerd in the k8s databases?

### PR DESCRIPTION
**Pull request by bart0sh**
**What this PR does / why we need it**:

Current implementation of this API always returns
checks output of 'crictl pods -q' and filters out everything
that doesn't start with k8s_. 'crictl pods -q' returns only pod ids,
so everything is always filtered out.

Removing filtering by name prefix should fix this.

**Which issue this PR fixes**
Fixes: kubernetes/kubeadm#926

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 1]
```diff
@@ -102,15 +102,13 @@ func (runtime *DockerRuntime) IsRunning() error {
 
 // ListKubeContainers lists running k8s CRI pods
 func (runtime *CRIRuntime) ListKubeContainers() ([]string, error) {
-	out, err := runtime.exec.Command("crictl", "-r", runtime.criSocket, "pods", "-q").CombinedOutput()
+	out, err := runtime.exec.Command("crictl", "-r", runtime.criSocket, "pods", "--namespace=kube-system", "-q").CombinedOutput()
```
Comment (kad) [inline cmd/kubeadm/app/util/runtime/runtime.go]: I don't think it's good idea to filter here at all. In case of Docker, there are possibilities that containers are started by user. In case of CRI usage, we can easily assume that all the containers belong to Kubernetes.

Comment (bart0sh) [reply cmd/kubeadm/app/util/runtime/runtime.go]: OK, thanks. will do.

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 2]
```diff
@@ -108,9 +108,7 @@ func (runtime *CRIRuntime) ListKubeContainers() ([]string, error) {
 	}
 	pods := []string{}
 	for _, pod := range strings.Fields(string(out)) {
-		if strings.HasPrefix(pod, "k8s_") {
-			pods = append(pods, pod)
-		}
+		pods = append(pods, pod)
```
Comment (dixudx) [inline cmd/kubeadm/app/util/runtime/runtime.go]: Why removing the check?

File: cmd/kubeadm/app/util/runtime/runtime_test.go [hunk 3]
```diff
@@ -128,7 +128,7 @@ func TestIsRunning(t *testing.T) {
 func TestListKubeContainers(t *testing.T) {
 	fcmd := fakeexec.FakeCmd{
 		CombinedOutputScript: []fakeexec.FakeCombinedOutputAction{
-			func() ([]byte, error) { return []byte("k8s_p1\nk8s_p2\nid3"), nil },
+			func() ([]byte, error) { return []byte("k8s_p1\nk8s_p2"), nil },
```
Comment (dixudx) [inline cmd/kubeadm/app/util/runtime/runtime_test.go]: Add reasons to change this test?

**Review by dixudx — CHANGES_REQUESTED** [review]

File: cmd/kubeadm/app/util/runtime/runtime.go (hunk 2 above)
Comment (kad) [reply cmd/kubeadm/app/util/runtime/runtime.go]: @dixudx `crictl pods -q` will return just pod IDs. those are `[0-9a-f]+`. There are no `k8s_` prefixes there. This prefix is only relevant for listing containers in case of docker as a runtime.

Comment (dixudx) [reply cmd/kubeadm/app/util/runtime/runtime.go]: @kad Thanks. Got it. We are now using containerd. It's safe to remove this.

File: cmd/kubeadm/app/util/runtime/runtime_test.go (hunk 3 above)
Comment (dixudx) [reply cmd/kubeadm/app/util/runtime/runtime_test.go]: IIUC, this test does not need to be changed, @kad right?

Comment (bart0sh) [reply cmd/kubeadm/app/util/runtime/runtime_test.go]: @dixudx that test expects 2 items in the list. As we removed the check number of items becomes 3, so one needs to be removed.

**Review by timothysc — APPROVED** [review]
/approve
