### PR TITLE
controller/leaderelection: fix one-off timestamp comparison and TestController candidate ping logic

### LINKED ISSUE #126424: [Flaking Test] ci-kubernetes-unit (TestController/better_candidate_triggers_reelection)
### Which jobs are flaking?

master-blocking:
- ci-kubernetes-unit

### Which tests are flaking?

`k8s.io/kubernetes/pkg/controlplane/controller/leaderelection.leaderelection`

#### Recent failures:
[7/28/2024, 7:22:24 PM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1817558515103830016)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
Failed;Failed;
=== RUN   TestController/better_candidate_triggers_reelection
W0728 14:09:01.790853   55926 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0728 14:09:01.791327   55926 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0728 14:09:01.792118   55926 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0728 14:09:01.893059   55926 shared_informer.go:320] Caches are synced for leader-election-controller
I0728 14:09:01.893180   55926 leaderelection_controller.go:104] Workers: 1
I0728 14:09:01.893206   55926 leaderelection_controller.go:106] Starting worker
I0728 14:09:01.893298   55926 leaderelection_controller.go:431] LeaseCandidate component-A is expired
    leaderelection_controller_test.go:735: context deadline exceeded
    --- FAIL: TestController/better_candidate_triggers_reelection (60.00s)
;=== RUN   TestController
--- FAIL: TestController (60.61s)
;
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig api-machinery

### PR DESCRIPTION
**Pull request by Jefftree**
/kind flake

#### What this PR does / why we need it:

Fixes a flake caused by TestController using the real clock. 

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/126424

#### Special notes for your reviewer:

1. Comparison of valid renewal pingTime < renewTime was changed to pingTime <= renewTime because we freeze the clock in unit tests.
2. ~~Injected fake clock in TestController.~~
3. ~~Added a waitforcachesync on the informer handlers, this was not the root cause but looked useful to have~~
4. ~~I got an error that `t.Logf` may not be called after test ctx is finished. We select on `ctx.Done()` but during the 10ms or so that the LeaseCandidate update is happening, the test ctx could be cancelled and logging is not permitted. Changed them to printf statements.~~ Waiting for go routines to terminate before test is finished.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @sttts

### CODE REVIEW

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 1]
```diff
@@ -715,6 +717,9 @@ func TestController(t *testing.T) {
 
 			informerFactory.Start(ctx.Done())
 			informerFactory.WaitForCacheSync(ctx.Done())
+			if !cache.WaitForNamedCacheSync(controllerName, ctx.Done(), controller.leaseRegistration.HasSynced, controller.leaseCandidateRegistration.HasSynced) {
+				return
+			}
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:722]: why? This should not be needed.

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 2]
```diff
@@ -747,9 +752,9 @@ func TestController(t *testing.T) {
 								continue // only candidate-aware controllers will follow preferredHolder
 							}
 
-							t.Logf("Deleting lease %s/%s because of preferredHolder %q != %q", l.Namespace, l.Name, *ph, *l.Spec.HolderIdentity)
+							fmt.Printf("Deleting lease %s/%s because of preferredHolder %q != %q", l.Namespace, l.Name, *ph, *l.Spec.HolderIdentity)
 							if err = client.CoordinationV1().Leases(expectedLease.Namespace).Delete(ctx, expectedLease.Name, metav1.DeleteOptions{}); err != nil {
-								t.Logf("Error deleting lease %s/%s: %v", l.Namespace, l.Name, err)
+								fmt.Printf("Error deleting lease %s/%s: %v", l.Namespace, l.Name, err)
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:757]: why?

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 3]
```diff
@@ -697,6 +698,7 @@ func TestController(t *testing.T) {
 			if err != nil {
 				t.Fatal(err)
 			}
+			controller.clock = fakeClock
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:701]: for this test this is counter-productive. We should not mix a real running controller (which we have here) with a fake clock.

File: pkg/controlplane/controller/leaderelection/leaderelection_controller.go [hunk 4]
```diff
@@ -278,7 +278,8 @@ func (c *Controller) reconcileElectionStep(ctx context.Context, leaseNN types.Na
 
 		if candidate.Spec.PingTime == nil ||
 			// If PingTime is outdated, send another PingTime only if it already acked the first one.
-			(candidate.Spec.PingTime.Add(electionDuration).Before(now) && candidate.Spec.PingTime.Before(candidate.Spec.RenewTime)) {
+			// This checks for pingTime <= renewTime because equality is possible in unit tests using a fake clock.
+			(candidate.Spec.PingTime.Add(electionDuration).Before(now) && !candidate.Spec.RenewTime.Before(candidate.Spec.PingTime)) {
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller.go:282]: you had added a `+-time.MilliSecond` somewhere in the tests. Can that be removed with this change?

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 2 above)
Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:757]: We lose correlation of the output with the test this way.
> I got an error that t.Logf may not be called after test ctx is finished. We select on ctx.Done() but during the 10ms or so that the LeaseCandidate update is happening, the test ctx could be cancelled and logging is not permitted. Changed them to printf statements.

Why not wait for them to finish with a wait group?

File: pkg/controlplane/controller/leaderelection/leaderelection_controller.go (hunk 4 above)
Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller.go:282]: removed

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 3 above)
Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go]: done

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 2 above)
Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go]: done

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 1 above)
Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go]: removed

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 5]
```diff
@@ -174,7 +175,7 @@ func TestReconcileElectionStep(t *testing.T) {
 						LeaseName:           "component-A",
 						EmulationVersion:    "1.20.0",
 						BinaryVersion:       "1.20.0",
-						PingTime:            ptr.To(metav1.NewMicroTime(fakeClock.Now().Add(-1 * time.Millisecond))),
+						PingTime:            ptr.To(metav1.NewMicroTime(fakeClock.Now())),
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:178]: For the reviewer: this is the one not needed anymore because we now check for >=, no >

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 6]
```diff
@@ -765,16 +772,18 @@ func TestController(t *testing.T) {
 					case <-ctx.Done():
 						return
 					case <-ticker.C:
-						for _, lc := range tc.createAfterControllerStart {
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:768]: For the reviewer: this was wrong because we have tc.candidates now too. So better list and answer all pings.

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go [hunk 7]
```diff
@@ -683,6 +682,10 @@ func TestController(t *testing.T) {
 
 	for _, tc := range cases {
 		t.Run(tc.name, func(t *testing.T) {
```
Comment (sttts) [inline pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:684]: For the reviewer: I have tested this with `time.Sleep(time.Second*6)` here to expire all `time.Now()` from above in the fixtures.

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 6 above)
Comment (p0lyn0mial) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go:768]: ok, thanks!

**Comment by p0lyn0mial** [comment]
the changes in this PR looks reasonable to me.

@sttts since these unit tests were flaky could you please run them with the `stress` tool ?

**Comment by sttts** [comment]
Stress test looks good:
```
$ go test -c -race ./pkg/controlplane/controller/leaderelection/
$ go run -mod=mod golang.org/x/tools/cmd/stress ./leaderelection.test -test.run TestController
5s: 5 runs so far, 0 failures
10s: 21 runs so far, 0 failures
15s: 35 runs so far, 0 failures
20s: 51 runs so far, 0 failures
25s: 65 runs so far, 0 failures
30s: 78 runs so far, 0 failures
35s: 89 runs so far, 0 failures
40s: 104 runs so far, 0 failures
45s: 119 runs so far, 0 failures
50s: 133 runs so far, 0 failures
55s: 146 runs so far, 0 failures
1m0s: 159 runs so far, 0 failures
1m5s: 171 runs so far, 0 failures
1m10s: 184 runs so far, 0 failures
1m15s: 196 runs so far, 0 failures
1m20s: 210 runs so far, 0 failures
1m25s: 223 runs so far, 0 failures
1m30s: 236 runs so far, 0 failures
1m35s: 251 runs so far, 0 failures
1m40s: 268 runs so far, 0 failures
1m45s: 280 runs so far, 0 failures
1m50s: 292 runs so far, 0 failures
1m55s: 304 runs so far, 0 failures
2m0s: 314 runs so far, 0 failures
2m5s: 330 runs so far, 0 failures
2m10s: 344 runs so far, 0 failures
2m15s: 356 runs so far, 0 failures
2m20s: 371 runs so far, 0 failures
2m25s: 386 runs so far, 0 failures
2m30s: 400 runs so far, 0 failures
2m35s: 413 runs so far, 0 failures
2m40s: 428 runs so far, 0 failures
2m45s: 442 runs so far, 0 failures
2m50s: 456 runs so far, 0 failures
2m55s: 469 runs so far, 0 failures
3m0s: 483 runs so far, 0 failures
3m5s: 497 runs so far, 0 failures
3m10s: 510 runs so far, 0 failures
```

**Comment by sttts** [comment]
And double-checked the same way on master branch: tl/dr it flakes every 50 runs
```
5s: 4 runs so far, 0 failures
10s: 18 runs so far, 0 failures
15s: 30 runs so far, 0 failures
20s: 44 runs so far, 0 failures
25s: 56 runs so far, 0 failures
30s: 67 runs so far, 0 failures
35s: 79 runs so far, 0 failures
40s: 89 runs so far, 0 failures

/var/folders/nt/c78b2wdn4h733pz9ckyxsssc0000gn/T/go-stress-20240730T105851-1993466452
I0730 10:58:56.539262   74811 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:58:56.539573   74811 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:58:56.539624   74811 leaderelection_controller.go:104] Workers: 1
I0730 10:58:56.539644   74811 leaderelection_controller.go:106] Starting worker
I0730 10:58:56.539906   74811 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:58:57.642159   74811 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:58:57.642210   74811 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:58:57.642268   74811 leaderelection_controller.go:104] Workers: 1
I0730 10:58:57.642284   74811 leaderelection_controller.go:106] Starting worker
I0730 10:58:57.642479   74811 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:58:58.743130   74811 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:58:58.743231   74811 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:58:58.743283   74811 leaderelection_controller.go:104] Workers: 1
I0730 10:58:58.743305   74811 leaderelection_controller.go:106] Starting worker
I0730 10:58:58.743639   74811 leaderelection_controller.go:383] Lease kube-system/component-A strategy changed to "OldestEmulationVersion"
I0730 10:58:58.743709   74811 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:58:58.744122   74811 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:58:59.743672   74811 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:58:59.944900   74811 shared_informer.go:313] Waiting for caches to sync for l
…
45s: 99 runs so far, 1 failures (1.01%)
50s: 110 runs so far, 1 failures (0.91%)
55s: 124 runs so far, 1 failures (0.81%)

/var/folders/nt/c78b2wdn4h733pz9ckyxsssc0000gn/T/go-stress-20240730T105851-2946891294
I0730 10:59:12.242314   74873 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:12.242504   74873 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:12.242536   74873 leaderelection_controller.go:104] Workers: 1
I0730 10:59:12.242548   74873 leaderelection_controller.go:106] Starting worker
I0730 10:59:12.242716   74873 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:13.343794   74873 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:13.343832   74873 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:13.343863   74873 leaderelection_controller.go:104] Workers: 1
I0730 10:59:13.343879   74873 leaderelection_controller.go:106] Starting worker
I0730 10:59:13.344046   74873 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:14.445165   74873 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:14.445252   74873 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:14.445406   74873 leaderelection_controller.go:104] Workers: 1
I0730 10:59:14.445429   74873 leaderelection_controller.go:106] Starting worker
I0730 10:59:14.445749   74873 leaderelection_controller.go:383] Lease kube-system/component-A strategy changed to "OldestEmulationVersion"
I0730 10:59:14.445815   74873 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:59:14.446247   74873 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:59:15.445730   74873 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:15.646415   74873 shared_informer.go:313] Waiting for caches to sync for l
…
1m0s: 134 runs so far, 2 failures (1.49%)

/var/folders/nt/c78b2wdn4h733pz9ckyxsssc0000gn/T/go-stress-20240730T105851-379821337
I0730 10:59:18.239926   74891 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:18.240174   74891 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:18.240203   74891 leaderelection_controller.go:104] Workers: 1
I0730 10:59:18.240214   74891 leaderelection_controller.go:106] Starting worker
I0730 10:59:18.240398   74891 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:19.342185   74891 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:19.342240   74891 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:19.342273   74891 leaderelection_controller.go:104] Workers: 1
I0730 10:59:19.342288   74891 leaderelection_controller.go:106] Starting worker
I0730 10:59:19.342474   74891 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:20.443037   74891 shared_informer.go:313] Waiting for caches to sync for leader-election-controller
I0730 10:59:20.443098   74891 shared_informer.go:320] Caches are synced for leader-election-controller
I0730 10:59:20.443144   74891 leaderelection_controller.go:104] Workers: 1
I0730 10:59:20.443160   74891 leaderelection_controller.go:106] Starting worker
I0730 10:59:20.443351   74891 leaderelection_controller.go:383] Lease kube-system/component-A strategy changed to "OldestEmulationVersion"
I0730 10:59:20.443386   74891 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:59:20.443663   74891 leaderelection_controller.go:399] Lease kube-system/component-A holder changed from "some-other-component" to "component-identity-1"
I0730 10:59:21.443861   74891 leaderelection_controller.go:359] Created lease kube-system/component-A for "component-identity-1"
I0730 10:59:21.645929   74891 shared_informer.go:313] Waiting for caches to sync for l
…
1m5s: 147 runs so far, 3 failures (2.04%)
```

File: pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go (hunk 2 above)
Comment (Jefftree) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller_test.go]: ah using the wg is a nice trick, thanks!

File: pkg/controlplane/controller/leaderelection/leaderelection_controller.go (hunk 4 above)
Comment (Jefftree) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller.go:282]: ack, not affecting this PR, but checking for <= instead of < was specifically for this test since the clock was fixed. Now that we're using a real clock it's technically unnecessary?

Comment (sttts) [reply pkg/controlplane/controller/leaderelection/leaderelection_controller.go:282]: I think it's a little bit more correct as it is now. Though of course the clock is very fine grained. So maybe in practice it does not matter.
