### PR TITLE
Fixing e2e tests which rely on network disruptions

### LINKED ISSUE #27324: [k8s.io] Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable [replication controller] recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/1511/

Failed: [k8s.io] Nodes [Disruptive] [k8s.io] Network when a node becomes unreachable [replication controller] recreates pods scheduled on the unreachable node AND allows scheduling of pods on a node after it rejoins the cluster {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/resize_nodes.go:544
Expected error:
    <*errors.errorString | 0xc82186d700>: {
        s: "failed to wait for pods responding: timed out waiting for the condition",
    }
    failed to wait for pods responding: timed out waiting for the condition
not to have occurred
```

### PR DESCRIPTION
**Pull request by foxish**
**What this PR does / why we need it**: It fixes e2e tests  on network disruptions

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes https://github.com/kubernetes/kubernetes/issues/27324, https://github.com/kubernetes/kubernetes/issues/35293

https://github.com/kubernetes/kubernetes/pull/33655 changed the kubelet's `--api-server` flag to use the external IP address of the APIServer in GCE. Hence, the iptables rules were failing previously. We now return the external IP for `getMaster()`. This fix is required in order to write e2e tests which test behavior in the face of network disruptions.

/cc @bprashanth @dchen1107 @kubernetes/sig-apps

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35581)

### CODE REVIEW

File: test/e2e/resize_nodes.go [hunk 1]
```diff
@@ -262,16 +262,7 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
-		if err != nil {
-			framework.Failf("Fail to get kubernetes endpoinds: %v", err)
-		}
-		if len(eps.Subsets) != 1 || len(eps.Subsets[0].Addresses) != 1 {
-			framework.Failf("There are more than 1 endpoints for kubernetes service: %+v", eps)
-		}
-		master = eps.Subsets[0].Addresses[0].IP
-	case "gke":
+	case "gce", "gke":
 		master = strings.TrimPrefix(framework.TestContext.Host, "https://")
```
Comment (bprashanth) [inline test/e2e/resize_nodes.go]: Hmm this will just break again if we pass a hostname? if we need the master we should probably let the caller decide by passing back a struct with internal/external/hostname, and if we can't find eg: internal ip, leave it blank. to populate the external ip then you'd do this, and try net.Parse to read it as an ip. If it doesn't work, you can assume it's a hostname and put that in leaving the external ip field blank.
Make sense?

**Comment by bprashanth** [comment]
Thanks for the fix!

File: test/e2e/resize_nodes.go (hunk 1 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: Yes, I agree that would be a more robust fix. Will make the change.Thanks!

**Comment by foxish** [comment]
@bprashanth PTAL. I've moved things around so that the master's hostname, externalIP and internalIP are all available and it is clearer which of those we're using to form our iptables rule. I can't find an easy to get what interface the kubelet decided to connect to the apiserver on from the test itself. So, it will likely break if someone were to change that back to listen to an internal IP address, or use the hostname and I don't see a way around it.

**Comment by foxish** [comment]
@bowei @bprashanth ping. We need this for the e2e tests accompanying the NodeController changes in https://github.com/kubernetes/kubernetes/pull/34160.

File: test/e2e/resize_nodes.go [hunk 2]
```diff
@@ -259,27 +266,46 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
+
+	// Populate the internal IP.
+	eps, err := c.Core().Endpoints(api.NamespaceDefault).Get("kubernetes")
+	if err != nil {
+		framework.Failf("Failed to get kubernetes endpoints: %v", err)
+	}
+	if len(eps.Subsets) != 1 || len(eps.Subsets[0].Addresses) != 1 {
+		framework.Failf("There are more than 1 endpoints for kubernetes service: %+v", eps)
+	}
+	master.internalIP = eps.Subsets[0].Addresses[0].IP
```
Comment (bprashanth) [inline test/e2e/resize_nodes.go]: can you actually check that it has a rfc 1918 prefix?  (10, 172.16, 192.168), or, if you don't think it's worth it please add a comment. If you check it, and it isn't a private ip, you should log an error and stick the ip in externalIP instead.  I don't think it matter which we trust if both this and --api-server turns out to be an external ip.

File: test/e2e/resize_nodes.go [hunk 3]
```diff
@@ -259,27 +266,46 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
+
+	// Populate the external IP/hostname.
+	host := strings.TrimPrefix(framework.TestContext.Host, "https://")
```
Comment (bprashanth) [inline test/e2e/resize_nodes.go]: this can be http:// too right? just grab everything after scheme (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax)? that could technically include more than the hostname, but it doesn't matter in an e2e

**Review by bprashanth — COMMENTED** [review]
random nits around address parsing

File: test/e2e/resize_nodes.go (hunk 3 above)
Comment (bowei) [inline test/e2e/resize_nodes.go]: You can use https://golang.org/pkg/net/url/ to avoid code duplication

	u, e := url.Parse(framework.TestContext.Host)

File: test/e2e/resize_nodes.go [hunk 4]
```diff
@@ -259,27 +266,46 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
-		}
-		master = eps.Subsets[0].Addresses[0].IP
-	case "gke":
-		master = strings.TrimPrefix(framework.TestContext.Host, "https://")
+	case "gce", "gke":
+		return master.externalIP
 	case "aws":
 		// TODO(justinsb): Avoid hardcoding this.
-		master = "172.20.0.9"
+		return "172.20.0.9"
```
Comment (bowei) [inline test/e2e/resize_nodes.go]: make this a constant at the file level so it is easier to find and fix

File: test/e2e/resize_nodes.go [hunk 5]
```diff
@@ -259,27 +266,46 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
-		if len(eps.Subsets) != 1 || len(eps.Subsets[0].Addresses) != 1 {
-			framework.Failf("There are more than 1 endpoints for kubernetes service: %+v", eps)
-		}
-		master = eps.Subsets[0].Addresses[0].IP
-	case "gke":
-		master = strings.TrimPrefix(framework.TestContext.Host, "https://")
+	case "gce", "gke":
+		return master.externalIP
 	case "aws":
 		// TODO(justinsb): Avoid hardcoding this.
```
Comment (bowei) [inline test/e2e/resize_nodes.go]: is there an issue attached to this TODO?

File: test/e2e/resize_nodes.go (hunk 4 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: Done

File: test/e2e/resize_nodes.go (hunk 5 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: Not that I am aware of. I think @justinsb might know.

File: test/e2e/resize_nodes.go (hunk 2 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: I've added a TODO for now.

**Comment by foxish** [comment]
@bowei @bprashanth Thanks for reviewing at short notice. Addressed the new comments. PTAL.

File: test/e2e/resize_nodes.go [hunk 6]
```diff
@@ -259,27 +270,49 @@ func resizeRC(c clientset.Interface, ns, name string, replicas int32) error {
...
+	master.internalIP = eps.Subsets[0].Addresses[0].IP
+
+	// Populate the external IP/hostname.
+	url, err := url.Parse(framework.TestContext.Host)
+	if err != nil {
+		framework.Failf("Failed to parse hostname: %v", err)
+	}
+	if net.ParseIP(url.Host) != nil {
+		// TODO: Check that it is external IP (not having a reserved IP address as per RFC1918).
+		master.externalIP = url.Host
```
Comment (bprashanth) [inline test/e2e/resize_nodes.go]: this is not going to be enough right? you need at least host:port. It's less likely for a non standard port in the hostname case, but likely in the ip case.

File: test/e2e/resize_nodes.go (hunk 2 above)
Comment (bprashanth) [inline test/e2e/resize_nodes.go]: You can also just add (since you're re-uping anyway i guess)
```go 
	internalIPs := []string{"10.", "172.", "192.168."}
	for _, cidrs := range internalIPs {
		if strings.HasPrefix(ip, cidrs) {
			fmt.Printf("internal %v\n", ip)
		}
	}
```

slightly inaccurate because the 172 is a /12, but meh

File: test/e2e/resize_nodes.go (hunk 6 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: Since it is being used to form an iptables rule, doesn't the host field actually suffice?

Comment (bprashanth) [inline test/e2e/resize_nodes.go]: I guess, if you assume we want to drop all traffic to the ip, what does the rule do? does it match on port?

**Comment by bprashanth** [comment]
LGTM if we don't need to match on port

File: test/e2e/resize_nodes.go (hunk 6 above)
Comment (foxish) [inline test/e2e/resize_nodes.go]: `sudo iptables --insert OUTPUT --destination <IP> --jump REJECT`

Comment (foxish) [inline test/e2e/resize_nodes.go]: I think we're blocking off the entire IP address from the looks of it. 
Thanks for the review. I'll add the internal/externalIP mechanism you suggested above and re-up.
