### PR TITLE
Specific error message on failed rolling update issued by older kubectl against 1.4 master

### LINKED ISSUE #32706: [k8s.io] Kubectl client [k8s.io] Kubectl rolling-update should support rolling-update to same image [Conformance]
https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.4-1.3-kubectl-skew

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.4-1.3-kubectl-skew/6187

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #32706

`kubernetes-e2e-gke-1.4-1.3-kubectl-skew` (1.3 kubectl and 1.4 master) test suite failed with:

```
k8s.io] Kubectl client [k8s.io] Kubectl rolling-update should support rolling-update to same image [Conformance]
...
Error from server: object is being deleted: replicationcontrollers "e2e-test-nginx-rc" already exists error: exit status 1 not to have occurred
```

It's because the old RC had an orphanFinalizer, so it is not deleted from the key-value store immediately. In turn, the creation of the new RC of the same name failed. 

In this failure, the RC and pods are updated, it's just that the RC is of different name, i.e., original name + a hash generated based on podTemplate. The error is confusing to user, but not that bad. So this PR just prints a warning message to instruct users how to work around.

1.4 kubectl rolling-update uses different logic so it's working.

@lavalamp @gmarek @janetkuo @pwittrock 

cc @liggitt for the ctx changes.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32751)

### CODE REVIEW

File: pkg/registry/generic/registry/store.go [hunk 1]
```diff
@@ -249,6 +250,27 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
...
+			if versionErr != nil {
+				return nil, err
+			}
+			if kubectlVersion.GTE(version.MustParse("v1.4.0")) {
+				return nil, err
+			}
+			if e.QualifiedResource.Resource != "replicationcontrollers" {
+				return nil, err
+			}
+			*msg = fmt.Sprintf("Note: if you are using \"kubectl rolling-update\" and your kubectl version is older than v1.4.0, your rolling-update is probably failed. Your pods are successfully updated, but the name of the RC is its original name plus a hash value. If you want to rename the RC, please use a kubectl newer than v1.4.0, then run rolling-update to change the name. : %s", *msg)
```
Comment (lavalamp) [inline pkg/registry/generic/registry/store.go]: Link to a document instead of explaining the entire problem right here?

File: pkg/registry/generic/registry/store.go [hunk 2]
```diff
@@ -249,6 +250,27 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
 		if accessor.GetDeletionTimestamp() != nil {
 			msg := &err.(*kubeerr.StatusError).ErrStatus.Message
 			*msg = fmt.Sprintf("object is being deleted: %s", *msg)
+			userAgent, _ := api.UserAgentFrom(ctx)
+			if !strings.Contains(userAgent, "kubectl") {
+				return nil, err
+			}
+			// example userAgent string: kubectl-1.3/v1.3.8 (linux/amd64) kubernetes/e328d5b
```
Comment (lavalamp) [inline pkg/registry/generic/registry/store.go]: Move this parsing into its own function.

**Review by lavalamp — COMMENTED** [review]
It would be good to make these changes but not if it means we don't make the next cherry-pick.

File: pkg/registry/generic/registry/store.go [hunk 3]
```diff
@@ -249,6 +250,27 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
...
+			userAgent = strings.Split(userAgent, " ")[0]
+			subs := strings.Split(userAgent, "/")
+			if len(subs) != 2 {
+				return nil, err
+			}
+			kubectlVersion, versionErr := version.Parse(subs[1])
+			if versionErr != nil {
+				return nil, err
+			}
+			if kubectlVersion.GTE(version.MustParse("v1.4.0")) {
```
Comment (thockin) [inline pkg/registry/generic/registry/store.go]: Please TODO this to remove after 1.6.

File: pkg/registry/generic/registry/store.go (hunk 1 above)
Comment (thockin) [inline pkg/registry/generic/registry/store.go]: This is really really nasty.  Is this the best we can do?  I'd like a mini-post-mortem on how we got this far with an incompatible change...

**Comment by caesarxuchao** [comment]
@lavalamp comments addressed.

File: pkg/registry/generic/registry/store.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: I cannot think of a better way. @lavalamp suggested kubectl's user-agent should contain the operation name, then we can do finer control from the server side. See https://github.com/kubernetes/kubernetes/issues/32725.

File: pkg/registry/generic/registry/store.go (hunk 3 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: Todo added.

**Comment by thockin** [comment]
I was just wild-guessing.  I mean, really, we should NEVER be incompatible
until v2, and even then plus 1 year.

File: CHANGELOG.md [hunk 4]
```diff
@@ -188,6 +189,9 @@ binary | sha256 hash
 
 **No notable changes for this release**
 
+## Known issues
+
+* master newer than v1.4.0 has backward compatible issues with older kubectl. Specifically, if "kubectl rolling-update" does not change the name of the replication controller (RC), the command will fail to create the new RC and report the RC already exists. When this happens, the pods are successfully updated, but the name of the RC is its original name plus a hash value. If you want to rename the RC, please download a kubectl newer than v1.4.0, then run rolling-update to change the name.
```
Comment (caesarxuchao) [inline CHANGELOG.md]: TODO: I'll paste this to #32332 when the PR is approved.

**Comment by caesarxuchao** [comment]
@lavalamp could you take another look? Thanks.

File: pkg/registry/generic/registry/store.go [hunk 5]
```diff
@@ -252,6 +272,15 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
...
 			*msg = fmt.Sprintf("object is being deleted: %s", *msg)
+			// TODO: remove this block after 1.6
+			userAgent, _ := api.UserAgentFrom(ctx)
+			if !isOldKubectl(userAgent) {
+				return nil, err
+			}
+			if e.QualifiedResource.Resource != "replicationcontrollers" {
+				return nil, err
+			}
+			*msg = fmt.Sprintf("Note: if you are using \"kubectl rolling-update\" and your kubectl version is older than v1.4.0, your rolling-update is probably failed, though the pods are correctly updated. Please see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#known-backward-compatibility-issues for a workaround. : %s", *msg)
```
Comment (lavalamp) [inline pkg/registry/generic/registry/store.go]: s/rolling-update is probably/rolling-update has probably/

The link is not specific enough, it needs to link not to the rolling changelog but to a specific heading within it.

File: CHANGELOG.md (hunk 4 above)
Comment (lavalamp) [inline CHANGELOG.md]: I'm going to help out with the wording here-- I've started something better below. Also, please start a section specifically about the behavior changes the garbage collector introduces and put this there.

```
`kubectl` 1.3's rolling-update command is compatible with Kubernetes 1.4 and higher **only if** you specify a new replication controller name. You will need to update to kubectl 1.4 or higher to use the rolling update command against a 1.4 cluster if you want to keep the original name, or you'll have to do two rolling updates.

If you do happen to use kubectl 1.3's rolling update against a 1.4 cluster, it will fail, usually with an error message that will direct you here. If you saw that error, then don't worry, the operation succeeded except for the part where the new replication controller is renamed back to the old name. You can just do another rolling update to change the name back: look for a replication controller that has the original name plus a random suffix.

Unfortunately, there is a second possible failure mode: <describe failure mode>

If this happens to you, then <describe fix>

```

**Review by lavalamp — CHANGES_REQUESTED** [review]

File: CHANGELOG.md (hunk 4 above)
Comment (janetkuo) [inline CHANGELOG.md]: Suggest make a section or bullet point here to let people know it's kubectl rolling-update related and they can skip if they're not using it. Something like:

### kubectl rolling-update
blah blah 

or 

* **`kubectl rolling-update`**: blah blah

File: CHANGELOG.md [hunk 6]
```diff
@@ -216,6 +217,9 @@ binary | sha256 hash
...
```
Comment (janetkuo) [inline CHANGELOG.md]: Suggest making a section or bullet point here to let people know it's kubectl rolling-update related and they can skip if they're not using it. Something like:

### kubectl rolling-update
blah blah 

or 

* **`kubectl rolling-update`**: blah blah

Comment (caesarxuchao) [inline CHANGELOG.md]: Done.

File: pkg/registry/generic/registry/store.go (hunk 5 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: Done.

**Comment by caesarxuchao** [comment]
@lavalamp PTAL. Thanks.

File: CHANGELOG.md [hunk 7]
```diff
@@ -216,6 +219,21 @@ binary | sha256 hash
...
+
+Unfortunately, there is a much rarer second possible failure mode: the replication controller gets renamed to the old name, but there is a duplicated set of pods in the cluster. kubectl will not report an error since it thinks its job is done.
+
+If this happens to you, you can wait at most 10 minutes for the replication controller to start a resync, the extra pods will then be deleted. Or, you can manually trigger a resync by change the replicas in the spec of the replication controller.
+
+### kubectl delete
+
+If you use an old version kubectl to delete a replication controller or replicaset, then after the delete command has returned, the replication controller or the replicaset will continue to exist in the key-value store for a short period of time (<1s). You probably will not notice any difference if you use kubectl manually, but you might notice it if you are using kubectl in a script.
```
Comment (lavalamp) [inline CHANGELOG.md]: What should people do to fix their scripts?

**Comment by lavalamp** [comment]
OK, the contents look pretty good now, but we need to fix the grammar :)

Maybe we should merge and fix in a followup.

**Review by lavalamp — APPROVED** [review]

**Comment by lavalamp** [comment]
@pwittrock @eparis this doesn't fix kubectl 1.3 but it does make the failure mode much better. Please cherrypick.

File: pkg/registry/generic/registry/store.go (hunk 1 above)
Comment (gmarek) [inline pkg/registry/generic/registry/store.go]: I think the 'mini-postmortem' would contain mostly the statement that the problem appeared because no one from people working on this feature knew anything about kubectl, and it wasn't caught by our upgrade tests because we didn't have any that were passing ever...

File: pkg/registry/generic/registry/store.go [hunk 8]
```diff
@@ -252,6 +272,15 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
 		if accessor.GetDeletionTimestamp() != nil {
 			msg := &err.(*kubeerr.StatusError).ErrStatus.Message
 			*msg = fmt.Sprintf("object is being deleted: %s", *msg)
+			// TODO: remove this block after 1.6
+			userAgent, _ := api.UserAgentFrom(ctx)
+			if !isOldKubectl(userAgent) {
+				return nil, err
+			}
+			if e.QualifiedResource.Resource != "replicationcontrollers" {
```
Comment (gmarek) [inline pkg/registry/generic/registry/store.go]: Can't it happen for replica sets as well?

File: pkg/registry/generic/registry/store.go [hunk 9]
```diff
@@ -252,6 +272,15 @@ func (e *Store) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
...
+				return nil, err
+			}
+			*msg = fmt.Sprintf("Note: if you are using \"kubectl rolling-update\" and your kubectl version is older than v1.4.0, your rolling-update has probably failed, though the pods are correctly updated. Please see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#kubectl-rolling-update for a workaround. : %s", *msg)
```
Comment (gmarek) [inline pkg/registry/generic/registry/store.go]: Shouldn't we check if the error is actually a name collision, not e.g. internal server error?

**Comment by lavalamp** [comment]
There's also the step where Chao fixed kubectl and I must have been asleep
because it failed to trigger the "oh hey that's compatibility problem"
mental module. :(

**Comment by lavalamp** [comment]
I was under the impression that rolling-update doesn't work on RS, if
that's not the case then we need to see if it's broken in 1.4 as well...

**Comment by lavalamp** [comment]
Yeah, good point. @ceaserxuchao can you make a followup? Thanks!

File: pkg/registry/generic/registry/store.go (hunk 8 above)
Comment (gmarek) [inline pkg/registry/generic/registry/store.go]: OK, this new review thingy is strange - I see @lavalamp's reply at the bottom.

I don't know - I thought that replica set is just a copy of replication controller + new selector.

File: pkg/registry/generic/registry/store.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: I knew it from the beginning...I stated the backward incompatibility in https://github.com/kubernetes/kubernetes/pull/29971. I was under the impression `kubectl rolling-update` was being deprecated by deployment, and we were not looking at the upgrade tests, so it went unnoticed.

File: pkg/registry/generic/registry/store.go (hunk 8 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: `kubectl rolling-update` only works with rc, so we don't worry about rs.

File: pkg/registry/generic/registry/store.go (hunk 9 above)
Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]: It's checked a few lines before.

Comment (caesarxuchao) [inline pkg/registry/generic/registry/store.go]:
```
 		if !kubeerr.IsAlreadyExists(err) {
 			return nil, err
 		}
```

Comment (gmarek) [inline pkg/registry/generic/registry/store.go]: Oh, OK - I was looking only at your changes.
