### PR TITLE
ResourceQuota: partial fix "should verify ResourceQuota with terminating scopes through scope selectors" flake

### LINKED ISSUE #131834: Failure cluster [0772932a...]: ResourceQuota should verify ResourceQuota with terminating scopes through scope selectors.
##### Error text:
```
[FAILED] pods "terminating-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1611 @ 05/16/25 15:37:16.803

```
#### Recent failures:
[5/18/2025, 6:42:33 AM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1923962387451351040)
[5/18/2025, 6:38:24 AM ci-kubernetes-e2e-kind-alpha-beta-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-alpha-beta-features/1923961129487306752)
[5/18/2025, 4:03:25 AM ci-kubernetes-kind-ipv6-e2e-parallel](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-kind-ipv6-e2e-parallel/1923922121751269376)
[5/18/2025, 4:01:33 AM ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce/1923921870046892032)
[5/18/2025, 3:18:33 AM ci-kubernetes-e2e-prow-canary](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-prow-canary/1923911048969064448)

/kind failing-test
/kind flake
/sig api-machinery

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup
/kind failing-test
/kind flake

#### What this PR does / why we need it:

As can be seen in the output of a test failure in the CI (see commit messages), the test waits for  "quota-not-terminating" to be updated, but then fails because creating the pod exceeds the "quota-terminating" quota which has not been updated yet. As both ResourceQuotas apply, it needs to wait for both of them to be updated.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/131834:

```
STEP: Creating a terminating pod - k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1609 @ 05/18/25 04:59:42.313
...
[FAILED] pods "terminating-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1611 @ 05/18/25 04:59:42.337
```

It does *not* fix this one:
```
STEP: Updating the pod to have an active deadline - k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1563 @ 05/19/25 07:49:11.512
...
[FAILED] pods "test-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1573 @ 05/19/25 07:49:11.572
```

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/apimachinery/resource_quota.go [hunk 1]
```diff
@@ -1605,6 +1606,8 @@ var _ = SIGDescribe("ResourceQuota", func() {
 		usedResources[v1.ResourceLimitsMemory] = resource.MustParse("0")
 		err = waitForResourceQuota(ctx, f.ClientSet, f.Namespace.Name, resourceQuotaNotTerminating.Name, usedResources)
 		framework.ExpectNoError(err)
+		err = waitForResourceQuota(ctx, f.ClientSet, f.Namespace.Name, resourceQuotaTerminating.Name, usedResources)
+		framework.ExpectNoError(err)
```
Comment (pohly) [inline test/e2e/apimachinery/resource_quota.go:1610]: I've not been able to reproduce the flake locally, but this seems like it should fix the problem.

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go:1610]: There's another one:
```
[FAILED] pods "test-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1573 @ 05/19/25 07:49:11.572
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/131843/pull-kubernetes-e2e-kind/1924367954477060096

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go:1610]: But this one here also occurs:
```
[FAILED] pods "terminating-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1611 @ 05/19/25 08:07:35.598
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/131844/pull-kubernetes-e2e-kind/1924371184065974272

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go:1610]: Still trying to make sense of the test...

cc @carlory , you changed this in https://github.com/kubernetes/kubernetes/commit/eb0f003d25209c850b47a275358aea53252274b4#diff-e1a46008c4ddbb9f83858cb22ce56ca0f820b78142a1e8abbbb11aa59127a09b.

One observation: when it checks for "ignored the pod usage", it's not sufficient to check once and move on if it has the desired status. One has to check for a certain period of time to be certain that the kube-controller-manager doesn't change the status some time after the initial check.

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go:1610]: Another observation: using `ExpectNoError` with no additional explanation makes it hard to correlate failures with steps in the test because one first has to look up the source code. Even then line numbers are not always the same (think merging an older PR into a new master with concurrent changes).

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go]: I added `ensureResourceQuota` before line 1573. If the ResourceQuota unexpectedly counts one terminating pod, then it'll show up more obviously than with just the quota error during admission of the pod update.

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go]: /assign @carlory 

Do my changes make sense to you?

Comment (carlory) [reply test/e2e/apimachinery/resource_quota.go]: Good catch, it is my mistake. I wanted to wait for the terminating quota to be updated, not the non-terminating one because we have checked it before deleting the pod1 when I wrote that PR.

This PR looks good to me.

/lgtm
/hold
feel free to unhold it.

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go]: Please re-add LGTM, I missed one error check: https://github.com/kubernetes/kubernetes/compare/0f1fbce3a75aadc49fb6cae1c22941a336661066..3878f7e7489285a616ba354ff5912ce8abcc19e2

I think we can lift the hold. This PR only fixes one of the two flakes, but adds a bit better output for the other. We can always investigate the other separately.

Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go]: I've updated the description with a description of which flake gets fixed (fingers crossed!) and which doesn't. Both have the exact same failure message.

I'll refrain from annotating all `framework.ExpectError`, but this shows that test with repeated checks absolutely should use annotation.

**Review by hashim21223445 — APPROVED** [review]

File: test/e2e/apimachinery/resource_quota.go (hunk 1 above)
Comment (pohly) [reply test/e2e/apimachinery/resource_quota.go]: /hold cancel
