### PR TITLE
Mark volume mount as uncertain in case of volume expansion fails

### LINKED ISSUE #99677: UnmapDevice failed for volume X (on node Y : The device Z is still referenced from other Pods)
#### What happened:
A transient API server outage and/or node authorization failure coupled with pod deletion while block volumes were getting attached/mounted results in block volumes not getting detached properly; thus, delaying the start of a new replica pod on a different node by 6 minutes. 

This is probably a case of Murphy's law where a transient API server access failure and a pod deletion while volumes were getting mounted resulted in an extended outage for a deployment. The problem happened with raw block GCP PDs in GKE, but it can happen with block PVs in any setup.

The prerequisite for this problem is some kind of API server access problem after updating the global map path:
```
2021-02-25T15:17:17+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:17.951191    2126 attacher.go:270] Successfully found attached GCE PD "gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26".
2021-02-25T15:17:17+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:17.951249    2126 operation_generator.go:960] MapVolume.WaitForAttach succeeded for volume "pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26" (UniqueName: "kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26") pod "test-c3406d09-3573-418e-bd71-72a874e5d855-7d4cc6b88b-tlkh6" (UID: "c2b710b3-2dc2-40ce-9867-7e77f6a6cb10") DevicePath "/dev/disk/by-id/google-gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26"
2021-02-25T15:17:17+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:17.957998    2126 mount_linux.go:178] Detected OS with systemd
2021-02-25T15:17:17+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:17.998592    2126 operation_generator.go:1065] MapVolume.MapPodDevice succeeded for volume "pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26" (UniqueName: "kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26") pod "test-c3406d09-3573-418e-bd71-72a874e5d855-7d4cc6b88b-tlkh6" (UID: "c2b710b3-2dc2-40ce-9867-7e77f6a6cb10") volumeMapPath "/var/lib/kubelet/pods/c2b710b3-2dc2-40ce-9867-7e77f6a6cb10/volumeDevices/kubernetes.io~gce-pd"
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: E0225 15:17:18.000488    2126 operation_generator.go:1073] MapVolume.NodeExpandVolume failed with MountVolume.NodeExpandVolume get PVC failed : persistentvolumeclaims "test-c3406d09-3573-418e-bd71-72a874e5d855-data1" is forbidden: User "system:node:gke-test-clus-n1-standard-4-po-b3a760df-5n12" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "test": no relationship found between node "gke-test-clus-n1-standard-4-po-b3a760df-5n12" and this object
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: E0225 15:17:18.000614    2126 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26 podName: nodeName:}" failed. No retries permitted until 2021-02-25 15:17:18.500563592 +0000 UTC m=+83924.410980106 (durationBeforeRetry 500ms). Error: "MapVolume.MarkVolumeAsMounted failed while expanding volume for volume \"pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\" (UniqueName: \"kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\") pod \"test-c3406d09-3573-418e-bd71-72a874e5d855-7d4cc6b88b-tlkh6\" (UID: \"c2b710b3-2dc2-40ce-9867-7e77f6a6cb10\") : MountVolume.NodeExpandVolume get PVC failed : persistentvolumeclaims \"test-c3406d09-3573-418e-bd71-72a874e5d855-data1\" is forbidden: User \"system:node:gke-test-clus-n1-standard-4-po-b3a760df-5n12\" cannot get resource \"persistentvolumeclaims\" in API group \"\" in the namespace \"test\": no relationship found between node \"gke-test-clus-n1-standard-4-po-b3a760df-5n12\" and this object"
```
Due to the failure above, kubelet doesn't update the actual state of the world:
https://github.com/kubernetes/kubernetes/blob/2695ef3f1b0e2fc51ffb1bcb8491a4165587a089/pkg/volume/util/operationexecutor/operation_generator.go#L1155

Now, if for some reason the deployment pod gets deleted, reconciler would try unmounting the volumes and then unmounting/detaching devices:
https://github.com/kubernetes/kubernetes/blob/445cb0609d2cffbfea4bd67a50f90f3655704ad1/pkg/kubelet/volumemanager/reconciler/reconciler.go#L163

Given the actual state of the world wasn't updated during mount, reconciler skips unmounting the volume and proceeds with unmounting/detaching the device. However, this step fails because kubelet thinks some other pod is using this volume when in fact the only pod that is using the volume is the one being deleted:
```
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:18.051236    2126 reconciler.go:312] operationExecutor.UnmountDevice started for volume "pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26" (UniqueName: "kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26") on node "gke-test-clus-n1-standard-4-po-b3a760df-5n12"
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: E0225 15:17:18.051430    2126 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26 podName: nodeName:}" failed. No retries permitted until 2021-02-25 15:17:18.551389407 +0000 UTC m=+83924.461805897 (durationBeforeRetry 500ms). Error: "UnmapDevice failed for volume \"pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\" (UniqueName: \"kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\") on node \"gke-test-clus-n1-standard-4-po-b3a760df-5n12\" : The device \"/var/lib/kubelet/plugins/kubernetes.io/gce-pd/volumeDevices/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\" is still referenced from other Pods [/var/lib/kubelet/plugins/kubernetes.io/gce-pd/volumeDevices/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26/c2b710b3-2dc2-40ce-9867-7e77f6a6cb10]"
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:18.552560    2126 reconciler.go:312] operationExecutor.UnmountDevice started for volume "pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26" (UniqueName: "kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26") on node "gke-test-clus-n1-standard-4-po-b3a760df-5n12"
2021-02-25T15:17:18+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: E0225 15:17:18.552768    2126 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26 podName: nodeName:}" failed. No retries permitted until 2021-02-25 15:17:19.55273784 +0000 UTC m=+83925.463154306 (durationBeforeRetry 1s). Error: "UnmapDevice failed for volume \"pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\" (UniqueName: \"kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\") on node \"gke-test-clus-n1-standard-4-po-b3a760df-5n12\" : The device \"/var/lib/kubelet/plugins/kubernetes.io/gce-pd/volumeDevices/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26\" is still referenced from other Pods [/var/lib/kubelet/plugins/kubernetes.io/gce-pd/volumeDevices/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26/c2b710b3-2dc2-40ce-9867-7e77f6a6cb10]"
2021-02-25T15:17:19+0000 gke-test-clus-n1-standard-4-po-b3a760df-5n12 kubelet[2126]: I0225 15:17:19.555836    2126 reconciler.go:312] operationExecutor.UnmountDevice started for volume "pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26" (UniqueName: "kubernetes.io/gce-pd/gke-test-cluste-pvc-e1ea45c4-8423-4eeb-b952-f024a04d8f26") on node "gke-test-clus-n1-standard-4-po-b3a760df-5n12"
```
Failed detaches go on for 6 minutes until the attach-detach controller forcibly detaches the volume. During this interval, a new pod can't start on a new node and hence suffers from a significant downtime.

#### What you expected to happen:

Broadly speaking, kubelet should tolerate brief API server outages or other intermittent failures in face of random events like pod deletions. More specifically, the volume should get detached immediately when the pod that's triggering the detach is the only consumer of the volume.

#### How to reproduce it (as minimally and precisely as possible):

Rapid creation and deletion of a pod belonging to a deployment coupled with an API server outage (and/or node authorization issue) is how the issue was encountered.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"} 
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-gke.1500", GitCommit:"421602205c5f21e899cfb88c62f79e81a938a48d", GitTreeState:"clean", BuildDate:"2021-02-03T09:16:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"} 
```
- Cloud provider or hardware configuration:
GKE

- OS (e.g: `cat /etc/os-release`):
```
NAME="Container-Optimized OS" 
ID=cos 
PRETTY_NAME="Container-Optimized OS from Google" 
HOME_URL="https://cloud.google.com/container-optimized-os/docs" 
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us" 
KERNEL_COMMIT_ID=4ebc996b5d8d64d7e24341f14434c9afb55b5322 
GOOGLE_METRICS_PRODUCT_ID=26 
GOOGLE_CRASH_ID=Lakitu 
VERSION=85 
VERSION_ID=85 
BUILD_ID=13310.1209.
```
- Kernel (e.g. `uname -a`):
```
Linux gke-test-nvc-clus-n1-standard-16-p-8a6623d6-hl4h 5.4.89+ #1 SMP Thu Jan 28 22:59:01 PST 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig storage
@msau42 @gnufied @saad-ali @jsafrane @bswartz

### PR DESCRIPTION
**Pull request by jingxu97**
should mark volume mount in actual state even if volume expansion fails so that
reconciler can tear down the volume when needed. To avoid pods start
using it, mark volume as uncertain instead of mounted.

Will add unit test after the logic is reviewed.

Change-Id: I5aebfa11ec93235a87af8f17bea7f7b1570b603d

#### Which issue(s) this PR fixes:

Fixes #99677

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jingxu97** [comment]
/assign @gnufied @mattcary 
cc @msau42 @saikat-royc

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -708,6 +708,14 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
 			if resizeError != nil {
 				klog.Errorf("MountVolume.NodeExpandVolume failed with %v", resizeError)
 				eventErr, detailedErr := volumeToMount.GenerateError("MountVolume.Setup failed while expanding volume", resizeError)
+				// At this point, MountVolume.Setup already succeeded, we should add volume into actual state
+				// so that reconciler can clean up volume when needed. However, vollume resize failed,
```
Comment (mattcary) [inline pkg/volume/util/operationexecutor/operation_generator.go:712]: vollume -> volume

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -1149,6 +1157,14 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
 		if resizeError != nil {
 			klog.Errorf("MapVolume.NodeExpandVolume failed with %v", resizeError)
 			eventErr, detailedErr := volumeToMount.GenerateError("MapVolume.MarkVolumeAsMounted failed while expanding volume", resizeError)
+			// At this point, MountVolume.Setup already succeeded, we should add volume into actual state
+			// so that reconciler can clean up volume when needed. However, if nodeExpandVolume failed,
+			// we should not mark the volume as mounted to avoid pod starts using it.
+			// Considering the above situations, we mark volume as uncertain here so that reconciler will tigger
+			// volume tear down when pod is deleted, and also makes sure pod will not start using it.
+			if err := actualStateOfWorld.MarkVolumeMountAsUncertain(markVolumeOpts); err != nil {
```
Comment (mattcary) [inline pkg/volume/util/operationexecutor/operation_generator.go:1165]: Why are we calling MarkVolumeMountAsUncertain here, but in the CustomBlockMapper case above, we markVolumeErrorState? Should't we be consistent in the two cases?

**Comment by gnufied** [comment]
Thank you for making this change. It looks good! I wonder if we can add some tests via `reconciler_test.go` file to capture the case where if mount succeeds but resize fails, the volume should be marked as mounted in uncertain state.

**Comment by mattcary** [comment]
ping, are you still making progress on this, Jing?

**Comment by jingxu97** [comment]
> ping, are you still making progress on this, Jing?

Yes, I am about to send out the unit test.

**Comment by jingxu97** [comment]
I added the unit test. @gnufied @mattcary

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (mattcary) [reply pkg/volume/util/operationexecutor/operation_generator.go:712]: ping

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 3]
```diff
@@ -1164,7 +1194,8 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
 				if !cache.IsFSResizeRequiredError(podExistErr) {
 					t.Fatalf("Volume should be marked as fsResizeRequired, but receive unexpected error: %v", podExistErr)
 				}
-
+				//mounted, _, err := asw.PodExistsInVolume(podName, volumeName)
```
Comment (mattcary) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1197]: debugging comments?

**Review by mattcary — COMMENTED** [review]
just a couple of nits

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 4]
```diff
@@ -1143,6 +1154,25 @@ func Test_Run_Positive_VolumeFSResizeControllerAttachEnabled(t *testing.T) {
...
+						}
+					}
+					return false, nil
+				})
+				if waitErr != nil {
+					t.Fatalf("Volume resize should succeeded %v", waitErr)
+				}
+				return
+			}
 			waitForMount(t, fakePlugin, volumeName, asw)
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1176]: Does this test belong here or in `Test_UncertainVolumeMountState` tests? I think that - it rather belongs there, rather than here.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go:712]: fixed, sorry for the delay.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 4 above)
Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: right, I moved the test case, I think it is better.

**Comment by jingxu97** [comment]
@gnufied @mattcary I addressed the comments, PTAL.
