### PR TITLE
tests: Makes UDP testing command more Windows friendly

### LINKED ISSUE #72917: test fails due to command incompatible with Windows cmd
**Which jobs are failing**:

N/A

**Which test(s) are failing**:

    should function for node-pod communication: udp

**Since when has it been failing**:

Unknown.

**Testgrid link**:

The test is currently excluded.
https://testgrid.k8s.io/sig-windows#Conformance%20acs-engine%20on%20Azure

**Reason for failure**:

By default, cmd is used to execute commands in Windows containers, but it has some issues executing the command (no output):

    echo 'hostName' | nc -w 1 -u <targetIP> <targetPort>

But it has no issues running (output is correct):

    echo hostName | nc -w 1 -u <targetIP> <targetPort>

This causes the test "should function for node-pod communication: udp" to fail when using Windows Containers.

**Anything else we need to know**:

/sig testing
/sig windows

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test
/sig testing
/sig windows

**What this PR does / why we need it**:

By default, cmd is used to execute commands in Windows containers, but it
has some issues executing the command (no output):

    echo 'hostName' | nc -w 1 -u <targetIP> <targetPort>

But it has no issues running (output is correct):

    echo hostName | nc -w 1 -u <targetIP> <targetPort>

This causes the test "should function for node-pod communication: udp" to
fail when using Windows Containers.

**Which issue(s) this PR fixes**:

Fixes #72917

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
Does the line https://github.com/kubernetes/kubernetes/pull/72918/files#diff-cb4c40bc4199d52e8b5e9e7f26e84d91R311 returns some error on this issue?
If so, can we know what kind of error on that?

**Comment by bclau** [comment]
@oomichi no, it does not, the output is just empty. This is also something I've tried out manually:

    kubectl exec -n pod-network-test host-test-container-pod -- cmd /S /C "echo 'hostName' | nc -w 1 -u 10.240.0.134 8081"
    (nothing)
    kubectl exec -n pod-network-test host-test-container-pod -- cmd /S /C "echo hostName | nc -w 1 -u 10.240.0.134 8081"

File: test/e2e/framework/networking_utils.go [hunk 1]
```diff
@@ -292,7 +292,7 @@ func (config *NetworkingTestConfig) DialFromNode(protocol, targetIP string, targ
 	if protocol == "udp" {
 		// TODO: It would be enough to pass 1s+epsilon to timeout, but unfortunately
 		// busybox timeout doesn't support non-integer values.
-		cmd = fmt.Sprintf("echo 'hostName' | nc -w 1 -u %s %d", targetIP, targetPort)
+		cmd = fmt.Sprintf("echo hostName | nc -w 1 -u %s %d", targetIP, targetPort)
```
Comment (neolit123) [inline test/e2e/framework/networking_utils.go]: spaces are not permitted in hostnames for both Windows and Linux so the quotes change seems fine.
in terms of `nc` there is no bundled netcat for Windows or in popular packages like `msys`, so i don't see how this helps the overall Windows situation with `DialFromNode()`, unless you downloaded a tool from somewhere. :)

**Review by neolit123 — APPROVED** [review]
/lgtm

File: test/e2e/framework/networking_utils.go (hunk 1 above)
Comment (bclau) [reply test/e2e/framework/networking_utils.go]: Indeed, we are including the nc executable in the hostexec image: https://github.com/kubernetes-sigs/windows-testing/blob/f96cb4cc6d71cc5b9782306ed89cd93d1363ccd8/images/hostexec/Dockerfile#L17

Comment (neolit123) [reply test/e2e/framework/networking_utils.go]: ack

**Review by michmike — APPROVED** [review]

**Comment by spiffxp** [comment]
/approve
wow, TIL, thanks!
