### PR TITLE
Clarify predicates name to clean confusing

### LINKED ISSUE #52166: No nodes are available that match all of the following predicates:: NodeUnderMemoryPressure (1).
/kind bug
/sig scheduling

**What happened**:
Pod was Pending or in CrashLoopBackOff container state. Not clear why until `kubectl get pod -o yaml` revealed this status:

```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-09-07T11:43:02Z
      message: 'No nodes are available that match all of the following predicates::
        NodeUnderMemoryPressure (1).'
      reason: Unschedulable
      status: "False"
      type: PodScheduled
    phase: Pending
    qosClass: BestEffort
```
But the message is confusing.

**What you expected to happen**:
Expected message to say something like "failed to find nodes not under memory pressure. So maybe rename predicate to NodeNotUnderMemoryPressure (1) ?

**How to reproduce it (as minimally and precisely as possible)**:
Run any cluster on machine with limited memory, such as 8Gb.

**Environment**:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-07-26T00:12:31Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**: minikube
- OS (e.g. from /etc/os-release): Fedora 26
- Kernel (e.g. `uname -a`):  4.12.9-300.fc26.x86_64
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:
Just make the scheduling message more clear.
by reading the message described in https://github.com/kubernetes/kubernetes/issues/52166 for several times, i recognize that from user's view our indication indeed exist a little confusing. I think our scheduling message is more from view of developer, but not user's view. Since predicates want to filter nodes to get the fit nodes. In this case, the fit nodes are nodes no under memory pressure. And `NodeUnderDiskPressure` has the same problem.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fix https://github.com/kubernetes/kubernetes/issues/52166

**Special notes for your reviewer**:

**Release note**:
none

### CODE REVIEW

**Comment by guangxuli** [comment]
@k82cn  @bsalamat  @resouer

File: plugin/pkg/scheduler/algorithm/predicates/error.go [hunk 1]
```diff
@@ -40,8 +40,8 @@ var (
 	ErrNodeLabelPresenceViolated = newPredicateFailureError("CheckNodeLabelPresence")
 	ErrServiceAffinityViolated   = newPredicateFailureError("CheckServiceAffinity")
 	ErrMaxVolumeCountExceeded    = newPredicateFailureError("MaxVolumeCount")
-	ErrNodeUnderMemoryPressure   = newPredicateFailureError("NodeUnderMemoryPressure")
-	ErrNodeUnderDiskPressure     = newPredicateFailureError("NodeUnderDiskPressure")
+	ErrNodeUnderMemoryPressure   = newPredicateFailureError("NodeNotUnderMemoryPressure")
```
Comment (bsalamat) [inline plugin/pkg/scheduler/algorithm/predicates/error.go]: Actually, I think the error messages are correct. These errors are returned when a node "is" under memory pressure or disk pressure. I think we should change `NoNodeAvailableMsg` to say something like:

`No nodes are available that match all of the predicates. The following predicate failures are observed for a set of nodes:`

Comment (abitrolly) [reply plugin/pkg/scheduler/algorithm/predicates/error.go]: In that particular case the more friendly error message would be `All nodes matched NodeUnderMemoryPressure predicate. No free nodes available."

Comment (bsalamat) [reply plugin/pkg/scheduler/algorithm/predicates/error.go]: We should create an error message that works when various predicates fail for different set of nodes. For example, 5 nodes failed "NodeUnderMemoryPressure", 3 nodes failed "NodeUnderDiskPressure", 2 nodes failed "NodeNotReady".

Comment (abitrolly) [reply plugin/pkg/scheduler/algorithm/predicates/error.go]: "0/10 nodes available - 5 NodeUnderMemoryPressure, 3 NodeUnderDistPressure, 2 NodeNotReady."

Comment (guangxuli) [reply plugin/pkg/scheduler/algorithm/predicates/error.go]: Sorry, i'm late, thanks for your responses. I will think carefully for your suggestions.

**Comment by bsalamat** [comment]
@guangxuli Please let me know if you have the time to work on this PR. It seems that this error message is confusing many people and we need to address it soon.

xref/ #53465

**Comment by aveshagarwal** [comment]
@bsalamat It'd be good to have it fixed for  https://github.com/kubernetes/kubernetes/issues/53465 as that message has been confusing. This code https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/core/generic_scheduler.go#L76 is required to fix.

**Comment by bsalamat** [comment]
@aveshagarwal I agree that we should address this ASAP. We have heard the same feedback about this message being confusing several times from several people. If I don't hear back from @guangxuli soon, I will send another PR later today or tomorrow to address the issue.

**Comment by guangxuli** [comment]
These days we are in National Day holidays, sorry @bsalamat, i will works on this today.

**Comment by bsalamat** [comment]
This is not urgent. I just wanted to make sure that we address it in a timely fashion. Please fix it at your earliest convenience. Thanks!

**Comment by guangxuli** [comment]
@bsalamat I have modified the code that refer to your and @abitrolly comments. The output formation just like `0/10 nodes available - 5 NodeUnderMemoryPressure, 3 NodeUnderDistPressure, 2 NodeNotReady ` described in comments. PTAL.

File: plugin/pkg/scheduler/core/generic_scheduler.go [hunk 2]
```diff
@@ -42,13 +42,14 @@ type FailedPredicateMap map[string][]algorithm.PredicateFailureReason
 
 type FitError struct {
 	Pod              *v1.Pod
+	TotalNodesNum    int
```
Comment (bsalamat) [inline plugin/pkg/scheduler/core/generic_scheduler.go]: s/TotalNodesNum/NumNodes/ or rename to NumAllNodes

**Review by bsalamat — COMMENTED** [review]
Thanks, @guangxuli! Looks good. Just a minor comment.

**Comment by guangxuli** [comment]
@bsalamat Comments have addressed, ptal. thanks.

**Comment by bsalamat** [comment]
/lgtm
/approve

Thanks, @guangxuli!
