### PR TITLE
MESOS: flocker unit test should clean up after itself

### LINKED ISSUE #15118: Flocker Volume Plugin: TestSetUpAtInternal flaky
@mattmoor reports the following failure after syncing with latest code:

--- FAIL: TestSetUpAtInternal (0.00s)
        Error Trace:    plugin_test.go:208
	Error:		Not equal: "expected-to-be-set-properly" (expected)
			        != "" (actual)
		
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.067s

cc/ @saad-ali

### LINKED ISSUE #15212: Failing flocker unit tests
Unit tests on our CI have apparently been failing for 2 weeks and no one noticed (oops!)...

The PR that seems to have caused the failures is #14328.

The failing test is `k8s.io/kubernetes/pkg/volume/flocker` - `TestSetUpAtInternal`.

```
[16:15:04][Step 4/5] --- FAIL: TestSetUpAtInternal (0.00s)
[16:15:04][Step 4/5] 	assertions.go:202: 
[16:15:04][Step 4/5]                         
[16:15:04][Step 4/5] 	Error Trace:	plugin_test.go:208
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] 	Error:		Not equal: "expected-to-be-set-properly" (expected)
[16:15:04][Step 4/5] 			        != "" (actual)
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] FAIL
[16:15:04][Step 4/5] FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.014s
```

Full Test Log: https://teamcity.mesosphere.io/viewLog.html?buildId=54217&buildTypeId=Oss_KubernetesMesos_2UnitTests&tab=buildLog&guest=1#_focus=866

I'm not sure why this is failing on our CI and not on shippable. Has anyone else seen something similar? 

**That test only seems to fail on the second run through with `etcdPrefix: kubernetes.io/registry`.**

Our unit tests run in a container built specifically for testing k8s-mesos:

```
$ cluster/mesos/docker/test/build.sh
$ docker run --rm \
  -v "$(pwd):/go/src/github.com/GoogleCloudPlatform/kubernetes" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  mesosphere/kubernetes-mesos-test \
  -cexu "\
    cd /go/src/github.com/GoogleCloudPlatform/kubernetes && \
    make clean && \
    export KUBERNETES_CONTRIB=mesos && \
    make test
  "
```

The Dockerfile for the env: https://github.com/kubernetes/kubernetes/blob/master/cluster/mesos/docker/test/Dockerfile

Is anyone else able to repro with the above env or their own?

### PR DESCRIPTION
**Pull request by jdef**
related unit test failure from logs (that this PR attempts to resolve):

```
[08:14:36][Step 4/5] --- FAIL: TestSetUpAtInternal (0.00s)
[08:14:36][Step 4/5]    assertions.go:202: 
[08:14:36][Step 4/5]                         
[08:14:36][Step 4/5]    Error Trace:    plugin_test.go:208
[08:14:36][Step 4/5]        
[08:14:36][Step 4/5]    Error:      Not equal: "expected-to-be-set-properly" (expected)
[08:14:36][Step 4/5]                    != "" (actual)
[08:14:36][Step 4/5]        
[08:14:36][Step 4/5] FAIL
[08:14:36][Step 4/5] FAIL   k8s.io/kubernetes/pkg/volume/flocker    0.024s
```

xref https://github.com/mesosphere/kubernetes-mesos/issues/542
- fixes #15118 
- fixes #15212

### CODE REVIEW

**Comment by jdef** [comment]
hm .. this didn't fix the the above problem in our testing infra. @agonzalezro I'm looking for ideas here, any thoughts? This test is run twice as per hack/test-go.sh, each time w/ a different etcd registry path. I'm thought that there was some stale data in the file system hierarchy from the plugin test that ran the first time that's causing the second test to fail. But this PR didn't help. Perhaps I'm cleaning up the wrong dir?

**Comment by agonzalezro** [comment]
Hi @jdef, I think that you are removing the flocker path, but no the meta path. Those two are different.

Have you tried removing it? https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flocker/plugin.go#L141-L148

**Comment by jdef** [comment]
Thanks for the suggestion but that didn't work.

**Comment by agonzalezro** [comment]
Have you seen my comments here?
https://github.com/kubernetes/kubernetes/issues/15118#issuecomment-145690809

Do they give you any clue?

I could take I look if I knew how to reproduce it locally.

For the sake of testing (and just testing, it's not a fix at all) can you
remove the IsReady check? That was added to make the function idempotent
since it's called several times from k8s.
Thanks for the suggestion but that didn't work.

On Tue, Oct 6, 2015 at 10:37 AM, Alexandre González <
notifications@github.com> wrote:

> Hi @jdef <https://github.com/jdef>, I think that you are removing the
> flocker path, but no the meta path. Those two are different.
>
> Have you tried removing it?
>
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flocker/plugin.go#L141-L148
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/kubernetes/kubernetes/pull/15158#issuecomment-145876145>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15158#issuecomment-145887856>
.

**Comment by jdef** [comment]
xref #15118

**Comment by jdef** [comment]
Removed the IsReady check. Same error.

**Comment by jdef** [comment]
ok, battling with our build system now. i'll have to re-run the tests once I get teamcity ironed out. prior results are unreliable.

**Comment by jdef** [comment]
now that our teamcity build spec is cleaned up the first commit I tried in this PR fixes the problem. running a few more tests..

**Comment by agonzalezro** [comment]
@jdef do you need the patch after your cleanup? Have you tried to run the tests without it?

**Comment by jdef** [comment]
Yes the patch is needed.

File: pkg/volume/flocker/plugin_test.go [hunk 1]
```diff
@@ -28,15 +30,17 @@ import (
...
 
-func newInitializedVolumePlugMgr() volume.VolumePluginMgr {
+func newInitializedVolumePlugMgr(t *testing.T) (volume.VolumePluginMgr, string) {
 	plugMgr := volume.VolumePluginMgr{}
-	plugMgr.InitPlugins(ProbeVolumePlugins(), volume.NewFakeVolumeHost("/foo/bar", nil, nil))
-	return plugMgr
+	dir, err := ioutil.TempDir("", "flocker")
+	assert.NoError(t, err)
+	plugMgr.InitPlugins(ProbeVolumePlugins(), volume.NewFakeVolumeHost(dir, nil, nil))
+	return plugMgr, dir
```
Comment (agonzalezro) [inline pkg/volume/flocker/plugin_test.go]: I wonder if there is a better way of getting this `dir` than returning it here (it's not being used in 3 out of 4 functions). Perhaps with the builder created in line 212? There is no problem doing the cleanup there because the function `SetupAt` was not called yet.

**Comment by agonzalezro** [comment]
Minor comment, but the PR looks ok to me (if my opinion counts) :)

Thanks for fixing @jdef and sorry for introducing the error.

File: pkg/volume/flocker/plugin_test.go (hunk 1 above)
Comment (jdef) [inline pkg/volume/flocker/plugin_test.go]: Honestly I'd rather return the dir here and just ignore it when not needed
vs. incorporating logic into the unit test that reaches into the bowels of
a structure to extract the path some other way. This seems much more
straightforward.

**Comment by jdef** [comment]
@dchen1107 PTAL

**Comment by karlkfi** [comment]
```
error: server version (version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.573+b59de62ea37988-dirty", GitCommit:"b59de62ea37988a57b0c67083ce6f4b72a23db72", GitTreeState:"dirty"}) differs from client version (version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.1.573+b59de62ea37988", GitCommit:"b59de62ea37988a57b0c67083ce6f4b72a23db72", GitTreeState:"clean"})!
```

**Comment by karlkfi** [comment]
I re-ran shippable, in hopes that it's a flake.

**Comment by jdef** [comment]
shippable looks hosed but not related to us:
```
  ./hack/test-cmd.sh
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
etcd -data-dir /tmp/tmp.mfj6lqCXsR --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null
Waiting for etcd to come up.
+++ [1007 17:16:24] On try 1, etcd: : 
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [1007 17:16:25] Running kubectl with no options
kubectl controls the Kubernetes cluster manager.

Find more information at https://github.com/kubernetes/kubernetes.
```

**Comment by saad-ali** [comment]
LGTM 
Thanks for digging into this and for the fix @jdef
This should be cherry-picked for 1.1 release

**Comment by saad-ali** [comment]
@jdef Could you rebase, hopefully that'll fix the shippable errors. I want to get this merged and cherrypicked to 1.1 ASAP

**Comment by jdef** [comment]
rebased

**Comment by saad-ali** [comment]
@k8s-oncall can you please make sure this is merged today (manually if the merge bot doesn't pick it up). It is fixing a flaky unit test.
