### PR TITLE
kubectl: recreating resources for immutable fields when force is applied

### LINKED ISSUE #66390: kubectl apply --force does not recreate resources for immutable fields
/kind bug

**What happened**:

From https://github.com/kubernetes/kubernetes/pull/34584 I expected kubectl apply to support deleting a resource and recreating it, if changes cannot be applied.

```
$ kubectl apply -f test-service.yaml   
The Service "test-service" is invalid: spec.clusterIP: Invalid value: "10.96.0.123": field is immutable
$ kubectl apply -f test-service.yaml   --force
The Service "test-service" is invalid: spec.clusterIP: Invalid value: "10.96.0.123": field is immutable
```

kubectl replace works:

```
kubectl replace -f test-service.yaml   --force 
service "test-service" deleted
service/test-service replaced
```

**What you expected to happen**:

```
$ kubectl apply -f test-service.yaml   --force
service "test-service" deleted
service/test-service created
```

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: test
  clusterIP: None
  ports:
    - port: 80
```

```
$ kubectl apply -f test-service.yaml   
````

Change clusterIP to any IP address.

```
$ kubectl apply -f test-service.yaml   
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): client v1.11.0, cluster v1.11.1 
- Cloud provider or hardware configuration: QEMU/KVM
- OS (e.g. from /etc/os-release): Cluster CentOS Linux release 7.5.1804 (Core), client macOS
- Kernel (e.g. `uname -a`): 3.10.0-862.6.3.el7.x86_64
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66390

**Special notes for your reviewer**:
/assign soltysh juanvallejo
/cc @kubernetes/sig-cli-bugs 

**Release note**:

```release-note
kubectl: recreating resources for immutable fields when force is applied
```

### CODE REVIEW

File: pkg/kubectl/cmd/apply.go [hunk 1]
```diff
@@ -753,7 +753,7 @@ func (p *patcher) patch(current runtime.Object, modified []byte, source, namespa
 		}
 		patchBytes, patchObject, err = p.patchSimple(current, modified, source, namespace, name, errOut)
 	}
-	if err != nil && errors.IsConflict(err) && p.force {
+	if err != nil && (errors.IsConflict(err) || errors.IsInvalid(err)) && p.force {
```
Comment (yue9944882) [inline pkg/kubectl/cmd/apply.go]: super nit: @dixudx how do you think about pruing `err != nil` here? it might be unneccesary to do the nil value check here because neither `IsConflict ` or `IsInvalid ` would return true on a nil error AFAICT. Not really sure if the additional judge here is for a better human-read :)

Comment (dixudx) [reply pkg/kubectl/cmd/apply.go]: @yue9944882 Although both `IsConflict` and `IsInvalid` return `False` for `nil.(Type)`, I'd prefer to keep it for several reasons,

1. Like you said, for better human readable and code convention.
2. `ReasonForError(nil)` will return `StatusReasonUnknown`, which is not right and confusing. `Nil` is different from status code 500.

Comment (yue9944882) [reply pkg/kubectl/cmd/apply.go]: reasonable :)

**Comment by juanvallejo** [comment]
/lgtm

@dixudx would a small test-cmd test be possible?
cc @soltysh for approval

**Comment by dixudx** [comment]
@juanvallejo  @soltysh Test added. PTAL. Thanks.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
