### PR TITLE
kubeadm: Do not read kubeconfig from disk repeatedly in the init phase

### LINKED ISSUE #3129: kubeadm re-reads kubeconfig in init phase bootstrap-token
### What happened?

I ran `kubeadm` with an in-memory kubeconfig literal (here reproduced with a file on disk and piped in, the principle is the same) and while many commands worked just fine, this init phase ended in a panic.

```
$ cat admin.conf | ./kubeadm --kubeconfig /dev/stdin init phase bootstrap-token
W1127 10:36:04.466512   80447 version.go:121] could not obtain client version; using remote version: v1.31.3
[bootstrap-token] Using token: vbzyo5.w4wxyalp15a9m0xc
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102534c08]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo.CreateBootstrapConfigMapIfNotExists({0x103107478, 0x14000439a40}, {0x16f8ead0f, 0xa})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go:56 +0x138
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runBootstrapToken({0x102f67ac0?, 0x1400013d220})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/init/bootstraptoken.go:109 +0x1f4
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0x1400022a000)
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261 +0xf4
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(...)
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0x1400049ed80, {0x1400066a200, 0x0, 0x2})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234 +0x2ac
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).BindToCommand.func1.1(0x140006ad000?, {0x1400066a200, 0x0, 0x2})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:376 +0xe0
github.com/spf13/cobra.(*Command).execute(0x140006b0008, {0x1400066a1e0, 0x2, 0x2})
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x1400043c608)
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(0x10309f078?)
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:1041 +0x1c
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/kubeadm.go:47 +0xac
main.main()
	/Users/okokes/git/kubernetes/cmd/kubeadm/kubeadm.go:25 +0x1c
```

### What did you expect to happen?

I expected the command to run just fine.

### How can we reproduce it (as minimally and precisely as possible)?

With a kubeconfig in `admin.conf`, run this in 9d62330bfa31a4fce28093d052f65ff0e88ac3a0:

```
go build -o kubeadm ./cmd/kubeadm
cat admin.conf | ./kubeadm --kubeconfig /dev/stdin init phase bootstrap-token
```

### Anything else we need to know?

I added a debug line to `LoadFromFile` and indeed it gets called twice, so if the source is not to be read repeatedly (e.g. a pipe), it will fail the second time around, because the resulting kubeconfig will be empty

```
$ cat admin.conf | ./kubeadm --kubeconfig /dev/stdin init phase bootstrap-token
W1127 10:12:46.763090   75623 version.go:121] could not obtain client version; using remote version: v1.31.3
2024/11/27 10:12:46 DBG: loading from file: /dev/stdin
[bootstrap-token] Using token: (...)
[bootstrap-token] Configuring bootstrap tokens, cluster-info ConfigMap, RBAC Roles
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to get nodes
[bootstrap-token] Configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstrap-token] Configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstrap-token] Configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstrap-token] Creating the "cluster-info" ConfigMap in the "kube-public" namespace
2024/11/27 10:12:50 DBG: loading from file: /dev/stdin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102bbcb88]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo.CreateBootstrapConfigMapIfNotExists({0x10378f478, 0x1400062e8c0}, {0x16f266d0f, 0xa})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go:56 +0x138
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runBootstrapToken({0x1035efac0?, 0x14000431c20})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/init/bootstraptoken.go:109 +0x1f4
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0x1400016efc0)
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:261 +0xf4
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(...)
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0x140003a4d80, {0x140004ab860, 0x0, 0x2})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234 +0x2ac
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).BindToCommand.func1.1(0x140006cb000?, {0x140004ab860, 0x0, 0x2})
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:376 +0xe0
github.com/spf13/cobra.(*Command).execute(0x140006da308, {0x140004ab840, 0x2, 0x2})
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000404908)
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(0x103727078?)
	/Users/okokes/git/kubernetes/vendor/github.com/spf13/cobra/command.go:1041 +0x1c
k8s.io/kubernetes/cmd/kubeadm/app.Run()
	/Users/okokes/git/kubernetes/cmd/kubeadm/app/kubeadm.go:47 +0xac
main.main()
	/Users/okokes/git/kubernetes/cmd/kubeadm/kubeadm.go:25 +0x1c
```

In the case of this kubeadm phase, it gets read first in `client, err := data.Client()`, but then the absolute path is retrieved and passed to `clusterinfophase.CreateBootstrapConfigMapIfNotExists(client, data.KubeConfigPath())`, where it gets read again.

### Kubernetes version

9d62330bfa31a4fce28093d052f65ff0e88ac3a0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
Darwin foo-bar 23.6.0 Darwin Kernel Version 23.6.0: Wed Jul 31 20:53:05 PDT 2024; root:xnu-10063.141.1.700.5~1/RELEASE_ARM64_T8112 arm64
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kokes**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

`kubeadm init phase bootstrap-token` reads a given kubeconfig twice, which is an issue if the kubeconfig is sourced from `/dev/stdin`, which doesn't allow for repeated reads (an in general it's redundant to reach out to the disk twice).

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3129

#### Special notes for your reviewer:

I ran Go tests just for the function that has a changed signature. Tried running the full suite, but ran into issues I didn't think were related to this PR.

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: avoid loading the file passed to `--kubeconfig` during `kubeadm init` phases more than once.
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve

thanks for the PR. it SGTM.
just suggesting some minor comment changes.
(please keep the commits squashed to one)

**Comment by neolit123** [comment]
/relese-note-edit

```release-note
kubeadm: avoid loading the file passed to "--kubeconfig" during "kubeadm init" phases more than once.
```

**Comment by neolit123** [comment]
e2e running on this PR
https://github.com/neolit123/kubeadm-test/actions/runs/12052922093

**Comment by neolit123** [comment]
> ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/data_test.go:32:18: cannot use &testInitData{} (value of type *testInitData) as InitData value in variable declaration: *testInitData does not implement InitData (missing method KubeConfig)

there is another interface implementor.
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/129006/pull-kubernetes-typecheck/1861786631267160064

File: cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go [hunk 1]
```diff
@@ -40,16 +38,13 @@ const (
...
-	adminConfig, err := clientcmd.LoadFromFile(file)
-	if err != nil {
-		return errors.Wrap(err, "failed to load admin kubeconfig")
-	}
-	if err = clientcmdapi.FlattenConfig(adminConfig); err != nil {
+	// Clone the kubeconfig so that it's not mutated.
+	adminConfig := kubeconfig.DeepCopy()
+	if err := clientcmdapi.FlattenConfig(adminConfig); err != nil {
 		return err
 	}
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/bootstraptoken/clusterinfo/clusterinfo.go:50]: i think on this line to avoid a panic we should do a simple check and throw an error.

```
if adminConfig.Contexts[adminConfig.CurrentContext] == nil {
	return errors.New("invalid kubeconfig")
}
```

errors is `"github.com/pkg/errors"`

**Comment by neolit123** [comment]
LGTM
please squash the commits.

/cc @carlory 
PTAL if possible too.

**Comment by kokes** [comment]
Hmmm, the failure does seem quite relevant since the affected code-path uploads `cluster-info`.

```
I1127 16:48:49.968686     218 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "abcdef"
I1127 16:48:49.979874     218 round_trippers.go:560] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 11 milliseconds
I1127 16:48:49.980255     218 token.go:250] [discovery] Retrying due to error: could not find a JWS signature in the cluster-info ConfigMap for token ID "abcdef"
```

**Comment by neolit123** [comment]
> Hmmm, the failure does seem quite relevant since the affected code-path uploads `cluster-info`. I retriggered a new test run in Prow to verify if it was a fluke or not.
> 
> ```
> I1127 16:48:49.968686     218 token.go:230] [discovery] Waiting for the cluster-info ConfigMap to receive a JWS signature for token ID "abcdef"
> I1127 16:48:49.979874     218 round_trippers.go:560] GET https://kind-control-plane:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s 200 OK in 11 milliseconds
> I1127 16:48:49.980255     218 token.go:250] [discovery] Retrying due to error: could not find a JWS signature in the cluster-info ConfigMap for token ID "abcdef"
> ```
> 
> Edit: or not 🤷
> 
> image

i think this is because it retries for a while

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: avoid loading the file passed to "--kubeconfig" during "kubeadm init" phases more than once.
```

**Comment by neolit123** [comment]
/test pull-kubernetes-verify-lint 
(test job is stuck)

**Review by neolit123 — COMMENTED** [review]
/lgtm

would appreciate additional review though.

**Comment by sftim** [comment]
/release-note-edit

```
kubeadm: avoid loading the file passed to `--kubeconfig` during `kubeadm init` phases more than once.
```

(using Markdown, replacing quoting)

**Comment by sftim** [comment]
/release-note-edit

```release-note
kubeadm: avoid loading the file passed to `--kubeconfig` during `kubeadm init` phases more than once.
```

(using Markdown, replacing quoting)
