### PR TITLE
e2e/storage: reset driver config in the test suite

### LINKED ISSUE #72378: PD multizone tests are flaky
**Which jobs are failing**:
gce/gke multizone/regional jobs

**Which test(s) are failing**:
Only PD tests

**Since when has it been failing**:
Around 12/21 with the 16:49 run

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage#gce-multizone

**Reason for failure**:
TBD

**Anything else we need to know**:

/kind failing-test

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

PR #70862 made each driver responsible for resetting its config, but
as it turned out, one place was missed in that PR: the in-tree gcepd
sets a node selector. Not resetting that caused other tests to fail
randomly depending on test execution order.
    
Now the test suite resets the config by taking a copy after setting up
the driver and restoring that copy before each test.
    
Long term the intention is to separate the entire test config from the
static driver info (https://github.com/kubernetes/kubernetes/issues/72288),
but for now resetting the config is the fastest way to fix the test flake.

**Which issue(s) this PR fixes**:

Fixes #72378 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/storage/drivers/in_tree.go [hunk 1]
```diff
@@ -1241,6 +1241,8 @@ func (h *gcePdDriver) GetClaimSize() string {
 }
 
 func (g *gcePdDriver) CreateDriver() {
+	// Reset config. It might have been modified by a previous CreateVolume call.
+	g.driverInfo.Config.ClientNodeSelector = nil
```
Comment (msau42) [inline test/e2e/storage/drivers/in_tree.go]: Instead of clearing out just this specific field, can we always reset the entire config before every test case across all drivers?  I don't see a reason why we need to persist any config between tests.

Comment (pohly) [reply test/e2e/storage/drivers/in_tree.go]: Yes, that's also possible.

Comment (pohly) [reply test/e2e/storage/drivers/in_tree.go]: PR updated.

Comment (msau42) [reply test/e2e/storage/drivers/in_tree.go]: Sorry I meant can we do this at the framework level so that every plugin doesn't have to do it?

Comment (oomichi) [reply test/e2e/storage/drivers/in_tree.go]: That seems a nice idea. Init***Driver returns Config on the same position and we could reset it on the same way at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/in_tree_volumes.go#L76

Comment (pohly) [reply test/e2e/storage/drivers/in_tree.go]: That also works. I think its a bit inconsistent with how the interface is currently defined, but hopefully we'll change that anyway soon.

I've updated the PR.

**Comment by msau42** [comment]
Fixing csi-serial job config: https://github.com/kubernetes/test-infra/pull/10570

**Comment by pohly** [comment]
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/72410/pull-kubernetes-e2e-gce-csi-serial/3/build-log.txt has test failures for `should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]` and `should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]`:
```
I1229 20:23:36.949] [91m[1mâ€¢ Failure [274.578 seconds][0m
I1229 20:23:36.949] [sig-storage] CSI Volumes
I1229 20:23:36.949] [90mtest/e2e/storage/utils/framework.go:22[0m
I1229 20:23:36.949]   [Driver: pd.csi.storage.gke.io][Serial]
I1229 20:23:36.949]   [90mtest/e2e/storage/csi_volumes.go:131[0m
I1229 20:23:36.949]     [Testpattern: Dynamic PV (default fs)] subPath
I1229 20:23:36.949]     [90mtest/e2e/storage/testsuites/subpath.go:98[0m
I1229 20:23:36.950]       [91m[1mshould unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow] [It][0m
I1229 20:23:36.950]       [90mtest/e2e/storage/testsuites/subpath.go:312[0m
I1229 20:23:36.950] 
I1229 20:23:36.950]       [91mExpected grep stdout to be empty (i.e. no mount found).
I1229 20:23:36.950]       Expected
I1229 20:23:36.950]           <string>: /dev/sdb on /var/lib/kubelet/pods/043368a0-0ba7-11e9-ad90-42010a280002/volumes/kubernetes.io~csi/pvc-fbcb4b85-0ba6-11e9-ad90-42010a280002/mount type ext4 (rw,relatime,data=ordered)
I1229 20:23:36.950]           /dev/sdb on /var/lib/kubelet/pods/043368a0-0ba7-11e9-ad90-42010a280002/volumes/kubernetes.io~csi/pvc-fbcb4b85-0ba6-11e9-ad90-42010a280002/mount type ext4 (rw,relatime,data=ordered)
I1229 20:23:36.951]           /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/043368a0-0ba7-11e9-ad90-42010a280002/volumes/kubernetes.io~csi/pvc-fbcb4b85-0ba6-11e9-ad90-42010a280002/mount type ext4 (rw,relatime,data=ordered)
I1229 20:23:36.951]           /dev/sdb on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/043368a0-0ba7-11e9-ad90-42010a280002/volumes/kubernetes.io~csi/pvc-fbcb4b85-0ba6-11e9-ad90-42010a280002/mount type ext4 (rw,relatime,data=ordered)
I1229 20:23:36.951]           
I1229 20:23:36.951]       to be empty[0m
```

Both tests are run twice, because Ginkgo tries to determine whether they are just flakes.

It also runs slowly because of https://github.com/kubernetes/kubernetes/issues/71748:

```
I1229 20:29:07.230] [BeforeEach] [Testpattern: Dynamic PV (block volmode)] volumeMode
I1229 20:29:07.230]   test/e2e/storage/testsuites/volumemode.go:118
I1229 20:29:07.244] [It] should fail in binding dynamic provisioned PV to PVC
I1229 20:29:07.245]   test/e2e/storage/testsuites/volumemode.go:314
...
I1229 20:29:07.359] Dec 29 20:29:07.359: INFO: Waiting up to 5m0s for PersistentVolumeClaims [pvc-mwgdr] to have phase Bound
...
I1229 20:34:06.232] Dec 29 20:34:06.232: INFO: PersistentVolumeClaim pvc-mwgdr found but phase is Pending instead of Bound.
I1229 20:34:08.233] [AfterEach] [Testpattern: Dynamic PV (block volmode)] volumeMode
```

Overall this seems unrelated to this PR.
