### PR TITLE
Fix bug in isLikelyNotMountPoint function

### LINKED ISSUE #22911: Many orphaned volumes in hyperkube
Kubelet continuously throws lots of errors:

```
W0312 22:53:09.750535   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42" found, tearing down volume
E0312 22:53:09.783931   13347 kubelet.go:1946] Could not tear down volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42": rename /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/default-token-rse42 /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~720717277: device or resource busy
W0312 22:53:11.731998   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/wrapped_default-token-rse42.deleting~720717277" found, tearing down volume
W0312 22:53:11.734984   13347 mount.go:98] could not determine device for path: "/var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~720717277"
W0312 22:53:11.747966   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42" found, tearing down volume
E0312 22:53:11.764105   13347 kubelet.go:1946] Could not tear down volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42": rename /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/default-token-rse42 /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~060988951: device or resource busy
W0312 22:53:13.730480   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/wrapped_default-token-rse42.deleting~060988951" found, tearing down volume
W0312 22:53:13.733530   13347 mount.go:98] could not determine device for path: "/var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~060988951"
W0312 22:53:13.762582   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42" found, tearing down volume
E0312 22:53:13.787960   13347 kubelet.go:1946] Could not tear down volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42": rename /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/default-token-rse42 /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~997836385: device or resource busy
W0312 22:53:15.732156   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/wrapped_default-token-rse42.deleting~997836385" found, tearing down volume
W0312 22:53:15.735224   13347 mount.go:98] could not determine device for path: "/var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~997836385"
W0312 22:53:15.771894   13347 kubelet.go:1935] Orphaned volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42" found, tearing down volume
E0312 22:53:15.796077   13347 kubelet.go:1946] Could not tear down volume "50da8d22-e89b-11e5-952b-5c514f64b257/default-token-rse42": rename /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/default-token-rse42 /var/lib/kubelet/pods/50da8d22-e89b-11e5-952b-5c514f64b257/volumes/kubernetes.io~secret/wrapped_default-token-rse42.deleting~884779835: device or resource busy
```

I'm starting the cluster this way:

```
docker run \
    --name=kube_kubelet \
    --volume=/:/rootfs:ro \
    --volume=/sys:/sys:ro \
    --volume=/var/lib/docker/:/var/lib/docker:rw \
    --volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
    --volume=/var/run:/var/run:rw \
    --net=host \
    --pid=host \
    --privileged=true \
    -d \
    gcr.io/google_containers/hyperkube:v1.2.0-beta.0 \
    /hyperkube kubelet \
    --containerized \
    --hostname-override="127.0.0.1" \
    --address="0.0.0.0" \
    --api-servers=http://localhost:8080 \
    --cluster-dns=10.0.0.10 \
    --cluster-domain=cluster.local \
    --allow-privileged=true \
    --v=2 \
    --config=/etc/kubernetes/manifests || exit $?

docker run \
    --name=kube_kubeproxy \
    -d \
    --net=host \
    --privileged \
    gcr.io/google_containers/hyperkube:v1.2.0-beta.0 \
    /hyperkube proxy \
    --master=http://127.0.0.1:8080 \
    --v=2 || exit $?
```

### LINKED ISSUE #25056: Pod scheduling grinds to a halt on v1.2.3
I'm running Kubernetes v1.2.3 using the single-node instructions here: http://kubernetes.io/docs/getting-started-guides/docker/ with Docker v1.10. Everything worked as expected for several hours, but now pods are not being scheduled or removed.

I've attempted to update a deployment several times over the last hour. Here is `kubectl get pods` for that deployment:

```
$ kubectl get pods -l role=nfs-server
NAME                          READY     STATUS              RESTARTS   AGE
nfs-server-1605536338-ff5dp   0/1       Terminating         0          26m
nfs-server-2929273945-87ir0   0/1       Terminating         0          10m
nfs-server-3650062886-7regp   0/1       Terminating         0          24m
nfs-server-377129609-3blnt    0/1       Terminating         0          17m
nfs-server-4135136443-iqh32   0/1       ContainerCreating   0          4m
nfs-server-4135136443-ny1op   0/1       Terminating         0          6m
```

The ContainerCreating pod's last event from `kubectl describe` is:

```
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type    Reason           Message
  ---------     --------        -----   ----                    -------------   --------------           -------
  4m            4m              1       {default-scheduler }                    Normal  Scheduled        Successfully assigned nfs-server-4135136443-l3fr4 to 127.0.0.1
```

When I delete a pod, the scheduler does seem to start the new pod almost immediately, and the kubelet logs:

```
I0502 23:13:28.627867    1701 kubelet.go:2388] SyncLoop (ADD, "api"): "nfs-server-4135136443-woha5_default(7ac455d2-10bb-11e6-b93b-06b60bd2d431)"  
```

The kubelet then begins logging a readiness check failure every 10s:

```
I0502 23:14:27.160982    1701 prober.go:104] Readiness probe for "nfs-server-1605536338-ff5dp_default(8f573313-10b7-11e6-b93b-06b60bd2d431):nfs-server" failed (failure): dial tcp 172.19.0.2:111: i/o timeout
```

but I can't see any evidence that it actually tries to run the container. Docker doesn't emit any logs. The Docker daemon is responsive, and the image is definitely present. When I run the image using `docker run` it works fine.

Anything I can check?

Thanks!

### LINKED ISSUE #26421: Should back-off when tearing orphaned volume down fails
Kubelet (v1.2.4) can consume a lot cycles and when it keeps trying to tear orphaned volumes down:
```
E0526 14:42:15.848642   24566 kubelet.go:1990] Could not tear down volume "0e1a7501-234b-11e6-9c55-0242ac110005/default-token-jdobu": rename /var/lib/kubelet/pods/0e1a7501-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/default-token-jdobu /var/lib/kubelet/pods/0e1a7501-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/wrapped_default-token-jdobu.deleting~174623125: device or resource busy
W0526 14:42:15.848747   24566 kubelet.go:1979] Orphaned volume "0ebefae4-234b-11e6-9c55-0242ac110005/default-token-jdobu" found, tearing down volume
W0526 14:42:15.868724   24566 mount.go:99] could not determine device for path: "/var/lib/kubelet/pods/0ebefae4-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/default-token-jdobu"
E0526 14:42:15.869251   24566 kubelet.go:1990] Could not tear down volume "0ebefae4-234b-11e6-9c55-0242ac110005/default-token-jdobu": rename /var/lib/kubelet/pods/0ebefae4-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/default-token-jdobu /var/lib/kubelet/pods/0ebefae4-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/wrapped_default-token-jdobu.deleting~407355888: device or resource busy
W0526 14:42:15.869300   24566 kubelet.go:1979] Orphaned volume "10389e0b-234b-11e6-9c55-0242ac110005/default-token-jdobu" found, tearing down volume
W0526 14:42:15.889578   24566 mount.go:99] could not determine device for path: "/var/lib/kubelet/pods/10389e0b-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/default-token-jdobu"
E0526 14:42:15.890023   24566 kubelet.go:1990] Could not tear down volume "10389e0b-234b-11e6-9c55-0242ac110005/default-token-jdobu": rename /var/lib/kubelet/pods/10389e0b-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/default-token-jdobu /var/lib/kubelet/pods/10389e0b-234b-11e6-9c55-0242ac110005/volumes/kubernetes.io~secret/wrapped_default-token-jdobu.deleting~665424527: device or resource busy
W0526 14:42:15.890067   24566 kubelet.go:1979] Orphaned volume "11281fa5-234b-11e6-9c55-0242ac110005/wrapped_default-token-jdobu.deleting~501175860" found, tearing down volume
```

### PR DESCRIPTION
**Pull request by jingxu97**
In nsenter_mount.go/isLikelyNotMountPoint function, the returned output
from findmnt command misses the last letter. Modify the code to use
String.contains instead of string matching. fixes #26421 fixes #25056 fixes #22911

### CODE REVIEW

File: pkg/util/mount/nsenter_mount.go [hunk 1]
```diff
@@ -189,9 +189,10 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
 		return true, nil
 	}
 	strOut := strings.TrimSuffix(string(out), "\n")
-
 	glog.V(5).Infof("IsLikelyNotMountPoint findmnt output for path %s: %v", file, strOut)
-	if strOut == file {
+
+	//TODO: This is a temperory workaround for fixing the buggy code. Track the solution with issue #26996
```
Comment (saad-ali) [inline pkg/util/mount/nsenter_mount.go]: nit: spelling "temporary"

**Comment by saad-ali** [comment]
LGTM but I'll leave it to @pmorie for final LGTM since he's most familiar with this code.

File: pkg/util/mount/nsenter_mount.go [hunk 2]
```diff
@@ -189,9 +189,10 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
...
+	if strings.Contains(file, strOut) {
```
Comment (thockin) [inline pkg/util/mount/nsenter_mount.go]: I *really* don't like this fix.  I do not want it to last very long, pleeeeeeease.

File: pkg/util/mount/nsenter_mount.go (hunk 1 above)
Comment (jingxu97) [inline pkg/util/mount/nsenter_mount.go]: fixed

On Wed, Jun 8, 2016 at 11:20 AM, Saad Ali <notifications@github.com> wrote:

> In pkg/util/mount/nsenter_mount.go
> <https://github.com/kubernetes/kubernetes/pull/27054#discussion_r66310353>
> :
>
> >  	glog.V(5).Infof("IsLikelyNotMountPoint findmnt output for path %s: %v", file, strOut)
> > -	if strOut == file {
> > +
> > +	//TODO: This is a temperory workaround for fixing the buggy code. Track the solution with issue #26996
>
> nit: spelling "temporary"
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054/files/602e5aa032deae544e8560635ad3f48d30a7260d#r66310353>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxfRs7Rk_9i6mogZubOq-XCi7AdFlks5qJwfigaJpZM4IxMdY>
> .
>



-- 
- Jing

File: pkg/util/mount/nsenter_mount.go (hunk 2 above)
Comment (jingxu97) [inline pkg/util/mount/nsenter_mount.go]: Some clarification about this fix.
1. The missing last letter from the output of findmnt command: I also
tested this command in my local environment with a simple go program. The
result still misses the last letter. Run command line directly on the
terminal has no issue. I also tried adding options "--notruncate", "--raw",
but still not working. So I think the bug is not related to our kubernetes
code.

The output from findmnt is /usr/local/google/home/jinxu/work/src/
k8s.io/jingggggggggggggggggggggggggggggggggggg  //the last letter t is
missing
The file path is /usr/local/google/home/jinxu/work/src/
k8s.io/jinggggggggggggggggggggggggggggggggggggt

2. Use strings.Contains() will not result in false positive. We pass the
testing mountpoint path when executing the findmnt command. As long as it
gives back a result, no matter whether some letters are missing or not, it
means that the given path is a mountpoint. Otherwise, an error returns.

We are thinking to further refactor this code because this function
currently servers as two purposes, one is to test whether the dir exist or
not, the other is testing mountpoint. It maybe be more clean to separate
the functions. Also we are debating whether to use other ways for checking
mountpoint instead of using findmnt

Please let me know if there are some concerns about the fix.

Thanks!
Jing


On Wed, Jun 8, 2016 at 11:45 AM, Tim Hockin <notifications@github.com>
wrote:

> In pkg/util/mount/nsenter_mount.go
> <https://github.com/kubernetes/kubernetes/pull/27054#discussion_r66315282>
> :
>
> >  	glog.V(5).Infof("IsLikelyNotMountPoint findmnt output for path %s: %v", file, strOut)
> > -	if strOut == file {
> > +
> > +	//TODO: This is a temperory workaround for fixing the buggy code. Track the solution with issue #26996
> > +	if strings.Contains(file, strOut) {
>
> I *really* don't like this fix. I do not want it to last very long,
> pleeeeeeease.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054/files/602e5aa032deae544e8560635ad3f48d30a7260d#r66315282>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxWcEZ5i_McdGy-vyTStU0GCaNCDbks5qJw3JgaJpZM4IxMdY>
> .
>



-- 
- Jing

Comment (thockin) [inline pkg/util/mount/nsenter_mount.go]: Can you reproduce this as a standalone Go program?  If so, we should file a
bug with either Go team or findmnt and understand what the heck is
happening.

**Comment by jingxu97** [comment]
@pmorie, Could you please take a look at this fix? Thanks!

**Comment by pmorie** [comment]
@jingxu97 it's in my queue for tonight, but I have other stuff I have to take care of first.

**Comment by jingxu97** [comment]
@pmorie Sure. Thanks a lot!
I also want to discuss with you about the approach to check the mountpoint.
I am wondering whether we can reuse the approach implemented in
mount_linux.go. Please let me know your option about it. Thanks!

Jing

On Thu, Jun 9, 2016 at 4:59 PM, Paul Morie <notifications@github.com> wrote:

> @jingxu97 <https://github.com/jingxu97> it's in my queue for tonight, but
> I have other stuff I have to take care of first.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225060929>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxWCNRkVOl1HC0A4bnGKgPiFx3tLTks5qKKjsgaJpZM4IxMdY>
> .
>



-- 
- Jing

File: pkg/util/mount/nsenter_mount.go [hunk 3]
```diff
@@ -189,9 +189,10 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
 		return true, nil
 	}
 	strOut := strings.TrimSuffix(string(out), "\n")
-
 	glog.V(5).Infof("IsLikelyNotMountPoint findmnt output for path %s: %v", file, strOut)
-	if strOut == file {
+
+	//TODO: This is a temporary workaround for fixing the buggy code. Track the solution with issue #26996
+	if strings.Contains(file, strOut) {
```
Comment (pmorie) [inline pkg/util/mount/nsenter_mount.go]: I'm not sure this is going to fix things.

What happens if `file` is `/a/likely/mountpoint-111` and `strOut` is `/a/likely/mountpoint-11`?

**Comment by pmorie** [comment]
@jingxu97 Can you clarify why the last char of the output is dropped?  Can we change the arguments of `findmnt` so that the last letter isn't dropped?

I would like to use the same check for containerized and for not.  However, the problem with adopting the code for the non-containerized case is that it relies our golang code.  We could use the same code for findmnt outside containers -- at least then the behavior would be consistent.

@eparis @thockin you guys have some history here -- any thoughts?

**Comment by pmorie** [comment]
For the record I think my vote is to use `findmnt` inside and outside the container.

File: pkg/util/mount/nsenter_mount.go (hunk 3 above)
Comment (jingxu97) [inline pkg/util/mount/nsenter_mount.go]: if file is /a/likely/mountpoint-111 and strOut is /a/likely/mountpoint-11,
then strings.Contains(file, strOut) returns true and it is a mount point.

On Thu, Jun 9, 2016 at 6:49 PM, Paul Morie <notifications@github.com> wrote:

> In pkg/util/mount/nsenter_mount.go
> <https://github.com/kubernetes/kubernetes/pull/27054#discussion_r66551038>
> :
>
> >  	glog.V(5).Infof("IsLikelyNotMountPoint findmnt output for path %s: %v", file, strOut)
> > -	if strOut == file {
> > +
> > +	//TODO: This is a temporary workaround for fixing the buggy code. Track the solution with issue #26996
> > +	if strings.Contains(file, strOut) {
>
> I'm not sure this is going to fix things.
>
> What happens if file is /a/likely/mountpoint-111 and strOut is
> /a/likely/mountpoint-11?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054/files/201576f0aa8467f75308880148973bc6618704b5#r66551038>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxUGwbDoBrLa53g4lfUT_BGQ-s3Boks5qKMLBgaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by jingxu97** [comment]
@pmorie I haven't figured out the root cause for this behavior. But I tried
to mount tmpfs to a local directory, and then write a simple go file to
execute the similar findmnt command, the output dropped the last char if
the file path is more than about 90 characters. I tried a few options for
the findmnt such as "--notruncate", and "--raw", but still not working.
But if findmnt is executed directly on the terminal, the output is fine.

Jing

On Thu, Jun 9, 2016 at 6:55 PM, Paul Morie <notifications@github.com> wrote:

> @jingxu97 <https://github.com/jingxu97> Can you clarify why the last char
> of the output is dropped? Can we change the arguments of findmnt so that
> the last letter isn't dropped?
>
> I would like to use the same check for containerized and for not. However,
> the problem with adopting the code for the non-containerized case is that
> it relies our golang code. We could use the same code for findmnt outside
> containers -- at least then the behavior would be consistent.
>
> @eparis <https://github.com/eparis> @thockin <https://github.com/thockin>
> you guys have some history here -- any thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225075356>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxfE0O1zYp7Fqmu5fIvoc2i__O-r_ks5qKMP3gaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by dims** [comment]
@jingxu97 @pmorie - I am not able to recreate the problem with a simple go script like Jing mentions. Here's my attempt (http://paste.openstack.org/show/510674/) on ubuntu. 

```
$ uname -a
Linux ubuntu-brix 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ findmnt --version
findmnt from util-linux 2.27.1
```

@jingxu97, Jing, can you try printing before the trim? print the byte representation etc?

**Comment by jingxu97** [comment]
The following is my code

file := "/usr/local/google/home/jinxu/work/src/k8s.io/jinggggggggggggggggggggggggggggggggggggt"
cmd := exec.Command("findmnt", "-f", "-u", "-r", "-n", "-o", "target",
"--target", file)
out, err := cmd.Output()
fmt.Printf("The output from findmnt is %x\n", out)
fmt.Printf("The file path is %x\n", file)

The hex output is

The output from findmnt is
2f7573722f6c6f63616c2f676f6f676c652f686f6d652f6a696e78752f776f726b2f7372632f6b38732e696f2f6a696e6767676767676767676767676767676767676767676767676767676767676767676767670a
The file path is
2f7573722f6c6f63616c2f676f6f676c652f686f6d652f6a696e78752f776f726b2f7372632f6b38732e696f2f6a696e67676767676767676767676767676767676767676767676767676767676767676767676774

You can see findmnt output last byte is 0a(new line), and compared
with original file path it misses 74 (letter t).

$uname -a

Linux jinxu0.mtv.corp.google.com 3.13.0-85-generic #129-Ubuntu SMP Thu
Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ findmnt --version



On Fri, Jun 10, 2016 at 1:53 PM, Davanum Srinivas <notifications@github.com>
wrote:

> @jingxu97 <https://github.com/jingxu97> @pmorie
> <https://github.com/pmorie> - I am not able to recreate the problem with
> a simple go script like Jing mentions. Here's my attempt (
> http://paste.openstack.org/show/510674/) on ubuntu.
>
> $ uname -a
> Linux ubuntu-brix 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> $ findmnt --version
> findmnt from util-linux 2.27.1
>
> @jingxu97 <https://github.com/jingxu97>, Jing, can you try printing
> before the trim? print the byte representation etc?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225292583>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxZZObJTs9it0It4F2lmxViZPRuNFks5qKc6sgaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by dims** [comment]
@jingxu97 as suspected the same code works for me. So can you redirect the output from running the "findmnt" straight from the command line into a file and use a hexdump see the output? ("hexdump -C a.txt") 

the 0a is definitely the \n character.

**Comment by jingxu97** [comment]
Running "findmnt" straight from the command line works fine. The hexdump
output is

00000000  2f 75 73 72 2f 6c 6f 63  61 6c 2f 67 6f 6f 67 6c  |/usr/local/googl|
00000010  65 2f 68 6f 6d 65 2f 6a  69 6e 78 75 2f 77 6f 72  |e/home/jinxu/wor|
00000020  6b 2f 73 72 63 2f 6b 38  73 2e 69 6f 2f 6a 69 6e  |k/src/k8s.io/jin|
00000030  67 67 67 67 67 67 67 67  67 67 67 67 67 67 67 67  |gggggggggggggggg|
*
00000050  67 67 67 67 74 0a                                 |ggggt.|
00000056

Jing



On Fri, Jun 10, 2016 at 3:01 PM, Davanum Srinivas <notifications@github.com>
wrote:

> @jingxu97 <https://github.com/jingxu97> as suspected the same code works
> for me. So can you redirect the output from running the "findmnt" straight
> from the command line into a file and use a hexdump see the output?
> ("hexdump -C a.txt")
>
> the 0a is definitely the \n character.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225306420>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxYH6QMX-eUF4vbqiyG61Pfs35s78ks5qKd6igaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by dims** [comment]
@jingxu97 Jing, Am out of ideas :) Did you try reading from the pipe directly?

```
    cmd := exec.Command("findmnt", "-f", "-u", "-r", "-n", "-o", "target", "--target", file)
    stdout, err := cmd.StdoutPipe()
    cmd.Start()
    r := bufio.NewReader(stdout)
    line, _, err := r.ReadLine()
    fmt.Printf("The output from findmnt is %s\n", line)
```

**Comment by jingxu97** [comment]
@dims, unfortunately, the last letter dropped too from reading the pipe.

Jing

On Fri, Jun 10, 2016 at 5:43 PM, Davanum Srinivas <notifications@github.com>
wrote:

> @jingxu97 <https://github.com/jingxu97> Jing, Am out of ideas :) Did you
> try reading from the pipe directly?
>
>     cmd := exec.Command("findmnt", "-f", "-u", "-r", "-n", "-o", "target", "--target", file)
>     stdout, err := cmd.StdoutPipe()
>     cmd.Start()
>     r := bufio.NewReader(stdout)
>     line, _, err := r.ReadLine()
>     fmt.Printf("The output from findmnt is %s\n", line)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225326243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxdHGTWVdFWBh_6Hb-k6ZgKdZzX_nks5qKgS8gaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by dims** [comment]
Jing,

So how about we change strategy and print more stuff. example print target and the file system type then we can parse the strings out and even if we lose a character in the file system type, we won't have to care.

```
$ findmnt -f -u -r -n -o target,fstype --target /var/lib/kubelet/pods/092fb51d-2f44-11e6-83b9-408d5ca94602/volumes/kubernetes.io~secret/default-token-ysfc4
/var/lib/kubelet/pods/092fb51d-2f44-11e6-83b9-408d5ca94602/volumes/kubernetes.io~secret/default-token-ysfc4 tmpfs
```

**Comment by jingxu97** [comment]
Davanum,

Yes, give two output options will work. For the current fix,
string.Contains() will also work I think. As I explained earlier in my
comment, use strings.Contains() will not result in any false positive. We
pass the mountpoint path when executing the findmnt command. As long as it
gives back a result, no matter whether some letters are missing or not, it
means that the given path is a mountpoint. The output will not give you any
paths other than the path given to the command. Otherwise, an error returns.

I think both approaches should work and please let me know your option
about them. Thanks!

Jing


On Fri, Jun 10, 2016 at 6:42 PM, Davanum Srinivas <notifications@github.com>
wrote:

> Jing,
>
> So how about we change strategy and print more stuff. example print target
> and the file system type then we can parse the strings out and even if we
> lose a character in the file system type, we won't have to care.
>
> $ findmnt -f -u -r -n -o target,fstype --target /var/lib/kubelet/pods/092fb51d-2f44-11e6-83b9-408d5ca94602/volumes/kubernetes.io~secret/default-token-ysfc4
> /var/lib/kubelet/pods/092fb51d-2f44-11e6-83b9-408d5ca94602/volumes/kubernetes.io~secret/default-token-ysfc4 tmpfs
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054#issuecomment-225329758>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxfEn2KvdmjwFB-jPe5R8QqsT0txdks5qKhJzgaJpZM4IxMdY>
> .
>



-- 
- Jing

**Comment by dims** [comment]
@jingxu97 Jing, right, i was really trying hard to use an explicit compare (avoid strings.Contains). So the printing extra stuff and splitting the strings, followed by a compare seems a better option. (But i am a newbie here!).

**Comment by jingxu97** [comment]
I modified the fix based on the suggestions from @dims. Please review it. Thanks!

File: pkg/util/mount/nsenter_mount.go [hunk 4]
```diff
@@ -188,13 +190,15 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
 		// It's safer to assume that it's not a mount point.
 		return true, nil
 	}
-	strOut := strings.TrimSuffix(string(out), "\n")
+	strOut := strings.Split(string(out), " ")[0]
```
Comment (dims) [inline pkg/util/mount/nsenter_mount.go]: @jingxu97 Jing, When we split the string we won't need to do a Trim i think. but you will have to confirm what you see in your environment :) LGTM otherwise.

Comment (jingxu97) [inline pkg/util/mount/nsenter_mount.go]: Actually here we do need a Trim. Otherwise, strOut has some empty spaces at
the end and it won't equal to file. I tested this in my environment
already. Thanks!

On Mon, Jun 13, 2016 at 1:57 PM, Davanum Srinivas <notifications@github.com>
wrote:

> In pkg/util/mount/nsenter_mount.go
> <https://github.com/kubernetes/kubernetes/pull/27054#discussion_r66866299>
> :
>
> > @@ -188,13 +190,15 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
> >  		// It's safer to assume that it's not a mount point.
> >  		return true, nil
> >  	}
> > -	strOut := strings.TrimSuffix(string(out), "\n")
> > +	strOut := strings.Split(string(out), " ")[0]
>
> @jingxu97 <https://github.com/jingxu97> Jing, When we split the string we
> won't need to do a Trim i think. but you will have to confirm what you see
> in your environment :) LGTM otherwise.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/27054/files/4cfdf00eb68fdab213a5a28854e9876256adbe4c#r66866299>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASSNxcA1wCVXxsEsaENWSN1yN6fuOyvdks5qLcRTgaJpZM4IxMdY>
> .
>



-- 
- Jing

Comment (dims) [inline pkg/util/mount/nsenter_mount.go]: Awesome! thanks Jing

File: pkg/util/mount/nsenter_mount.go [hunk 5]
```diff
@@ -175,8 +175,10 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
 		glog.V(5).Infof("findmnt: directory %s does not exist", file)
 		return true, err
 	}
-
-	args := []string{"--mount=/rootfs/proc/1/ns/mnt", "--", n.absHostPath("findmnt"), "-o", "target", "--noheadings", "--target", file}
+	// Add --first-only option in case multiple mount points exist.
```
Comment (pmorie) [inline pkg/util/mount/nsenter_mount.go]: i'm a little concerned about `--first-only`.  Can you make an argument as to why we should ignore multiple mount points?

File: pkg/util/mount/nsenter_mount.go (hunk 4 above)
Comment (pmorie) [inline pkg/util/mount/nsenter_mount.go]: @jingxu97 Let's make the code a little easier to follow while you're in here.  Would you rename `strOut` to `mountTarget` ?

File: pkg/util/mount/nsenter_mount.go (hunk 5 above)
Comment (pmorie) [inline pkg/util/mount/nsenter_mount.go]: Lol.  I realized this function is `IsLikelyNotMountPoint` not `IsLikelyMountPoint`.  Carry on.

Comment (pmorie) [inline pkg/util/mount/nsenter_mount.go]: I do think this would get a little clear with a comment like `// since we are testing for the absense of a mountpoint, it is sufficient to get only the first of multiple possible mountpoints using --first-only.

**Comment by pmorie** [comment]
Just a couple nits to make the code easier to understand, LGTM otherwise.  @jingxu97

**Comment by jingxu97** [comment]
Fix the nits suggested by @pmorie. Attach LGTM label to merge.
