### PR TITLE
Fixes issue where PVCs using `standard` StorageClass create PDs in disks in wrong zone in multi-zone GKE clusters

### LINKED ISSUE #50115: PVCs using `standard` StorageClass create PDs in disks in wrong zone in multi-zone GKE clusters
/kind bug

**What happened**:

- Created single-zone cluster in `us-central1-c`
- Expanded to multiple zones after creation using `gcloud container clusters update ... --additional-zones` to `b` and `a`
- Deployed PVC with `storageClassName: standard`, which is a StorageClass included with GKE.
- PV is created in `us-central1-f`, a zone with no nodes from this cluster in it

**What you expected to happen**:

- PV created in one of the zones that the cluster has nodes in

**How to reproduce it (as minimally and precisely as possible)**:

See `What Happened`. I'm not sure the expansion after creation step is necessary.

**Anything else we need to know?**:

May be a duplicate of https://github.com/kubernetes/kubernetes/issues/39178, but that's on AWS

**Environment**:

- Kubernetes version (use `kubectl version`): 
```Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-30T09:51:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**: GKE 1.6.4
- OS (e.g. from /etc/os-release): cos

### PR DESCRIPTION
**Pull request by davidz627**
Fixes #50115

Changed GetAllZones to only get zones with nodes that are currently running (renamed to GetAllCurrentZones). Added E2E test to confirm this behavior.

```release-note
Fix a bug in GCE multizonal clusters where PersistentVolumes were sometimes created in zones without nodes.
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 1]
```diff
@@ -250,48 +253,46 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
+	zones := sets.NewString()
+	nodeList, err := gce.client.Core().Nodes().List(metav1.ListOptions{})
+	if err != nil {
+		log.Fatalf("Failed to list nodes: %v", err)
+		return nil, err
+	}
+
+	for _, node := range nodeList.Items {
+		labels := node.ObjectMeta.Labels
+		zone := labels[kubeletapis.LabelZoneFailureDomain]
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Check for label doesn't exist.

File: test/e2e/ubernetes_lite.go [hunk 2]
```diff
@@ -61,8 +62,86 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
...
+	Expect(err).NotTo(HaveOccurred())
+	framework.Logf("Expected zones: %v\n", expectedZones)
+	// Get all the zones in this current region
+	region := gceCloud.Region()
+	allZonesInRegion, err := gceCloud.ListZonesInRegion(region)
+	Expect(err).NotTo(HaveOccurred())
+	var extraZone string
+	for _, zone := range allZonesInRegion {
+		if !expectedZones.Has(zone.Name) {
+			extraZone = zone.Name
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: You can break after this

File: test/e2e/ubernetes_lite.go [hunk 3]
```diff
@@ -61,8 +62,86 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
...
+		}
+	}
+
+	// If no zones left to create an extra instance we screwed and we stop the test right here
+	Expect(extraZone).NotTo(Equal(""), fmt.Sprintf("No extra zones available in region %s", region))
+	framework.Logf("We are going to start a compute instance in unused zone: %v\n", extraZone)
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: You can use By() here

File: test/e2e/ubernetes_lite.go [hunk 4]
```diff
@@ -61,8 +62,86 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
...
+		// Teardown of the compute instance
+		framework.Logf("Deleting compute resource: %v", name)
+		resp, err = gceCloud.DeleteInstance(project, zone, name)
+		framework.Logf("Compute deletion response: %v\n", resp)
+	}()
+	// GetAllZones functionality checking.
+	gotZones, err := gceCloud.GetAllCurrentZones()
+	Expect(err).NotTo(HaveOccurred())
+
+	Expect(gotZones.Equal(expectedZones)).To(BeTrue(), fmt.Sprintf("Expected zones: %v, Got Zones: %v", expectedZones, gotZones))
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: Do you need to sort the zones before comparing?

File: test/e2e/ubernetes_lite.go [hunk 5]
```diff
@@ -61,8 +62,86 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
...
+	It("should only be allowed to provision PDs in zones where nodes exist", func() {
+		OnlyAllowNodeZones(f, zoneCount, image)
+	})
 })
 
+// OnlyAllowNodeZones tests that GetAllCurrentZones returns only zones with Nodes
+func OnlyAllowNodeZones(f *framework.Framework, zoneCount int, image string) {
+	gceCloud, err := framework.GetGCECloud()
+	Expect(err).NotTo(HaveOccurred())
+	gceCloud.SetClientSet(f.ClientSet)
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: Is it possible to set this earlier in e2e.go when we initialize the cloud provider?

File: test/e2e/ubernetes_lite.go (hunk 4 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: This is set equality. It does a carnality comparison then checks whether one is a superset of the other.

File: test/e2e/ubernetes_lite.go (hunk 5 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: Not without pretty significant code changes I think. I looked at the way the framework is setting it up for f.ClientSet and its pretty involved and has some pretty complex dependancies. Also f.ClientSet isn't set up until the start of the specific test so we can't use it in e2e.go.

lmk if you want to talk about this.

File: test/e2e/ubernetes_lite.go (hunk 2 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: fixed

File: test/e2e/ubernetes_lite.go (hunk 3 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: fixed

File: pkg/cloudprovider/providers/gce/gce_instances.go (hunk 1 above)
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: fixed

File: test/e2e/e2e.go [hunk 6]
```diff
@@ -103,8 +103,9 @@ func setupProviderConfig() error {
 
 		cloudConfig.Provider = gceCloud
 
+		// Arbitrarily pick one of the zones we have nodes in
 		if cloudConfig.Zone == "" && framework.TestContext.CloudConfig.MultiZone {
-			zones, err := gceCloud.GetAllZones()
+			zones, err := gceCloud.GetAllCurrentZones()
```
Comment (msau42) [inline test/e2e/e2e.go]: Is this going to work?  This is done early in e2e initialization, where client is not set yet?

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 7]
```diff
@@ -250,50 +253,52 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
-	if len(gce.managedZones) == 1 {
-		return sets.NewString(gce.managedZones...), nil
-	}
-
-	// TODO: Caching, but this is currently only called when we are creating a volume,
-	// which is a relatively infrequent operation, and this is only # zones API calls
+// GetAllCurrentZones returns all the zones in which nodes are currently running
+func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
 	zones := sets.NewString()
+	nodeList, err := gce.client.Core().Nodes().List(metav1.ListOptions{})
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Check for client nil

File: test/e2e/ubernetes_lite.go [hunk 8]
```diff
@@ -61,8 +62,87 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
 	It("should schedule pods in the same zones as statically provisioned PVs", func() {
 		PodsUseStaticPVsOrFail(f, (2*zoneCount)+1, image)
 	})
+
+	It("should only be allowed to provision PDs in zones where nodes exist", func() {
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: We can also control the zones that volumes are provisioned in, if we [name](https://github.com/kubernetes/kubernetes/blob/52ac2652bc6b62f9182cc8cd8d2365ae04794aeb/pkg/volume/util.go#L298) them correctly.  So maybe a test case we can add is to create PVCs with specific names, and make sure they get spread across the appropriate zones.

Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: Should this test case be added in this same PR or should I create a new PR/issue for it?

Comment (msau42) [reply test/e2e/ubernetes_lite.go]: I would put it as part of this test, maybe instead of (or in addition to) comparing the GetAllZones call.  Because from a user's standpoint, they would see issues in the volume provisioning.  The GetAllZones call is just an implementation detail.

File: test/e2e/ubernetes_lite.go (hunk 5 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: I think i've actually solved this. Testing now.

**Comment by davidz627** [comment]
addressed comments

File: test/e2e/ubernetes_lite.go (hunk 8 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: I added it in addition to. So the GetAllZones check still exists, the PVC checking follows.

File: test/e2e/storage/volume_provisioning.go [hunk 9]
```diff
@@ -422,7 +422,7 @@ var _ = SIGDescribe("Dynamic Provisioning", func() {
 			Expect(err).NotTo(HaveOccurred())
 
 			// Get all k8s managed zones
-			managedZones, err = gceCloud.GetAllZones()
+			managedZones, err = gceCloud.GetAllManagedZones()
```
Comment (wojtek-t) [inline test/e2e/storage/volume_provisioning.go]: Why we can't have "GetAllCurrentZones() here?

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 10]
```diff
@@ -250,50 +253,56 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
+		} else {
+			return nil, fmt.Errorf("Could not find zone for node %v", node.ObjectMeta.Name)
 		}
 	}
-
 	return zones, nil
 }
 
+// GetAllManagedZones gets all the zones managed by k8s
+func (gce *GCECloud) GetAllManagedZones() (sets.String, error) {
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Do we really need this method? I would really like to get rid of it.

Comment (wojtek-t) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Currently there is only one place in test using this method and I personally think that we can use GetAllCurrentZones() there too.

Note that currently "managed_zones" can be only set to two values:
- one particular zones
- all zones from the region

There is no way to set it differently in production, thus we probably shouldn't set it differently in tests too.

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 11]
```diff
@@ -250,50 +253,56 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
-func (gce *GCECloud) GetAllZones() (sets.String, error) {
-	// Fast-path for non-multizone
-	if len(gce.managedZones) == 1 {
-		return sets.NewString(gce.managedZones...), nil
-	}
-
-	// TODO: Caching, but this is currently only called when we are creating a volume,
-	// which is a relatively infrequent operation, and this is only # zones API calls
+// GetAllCurrentZones returns all the zones in which nodes are currently running
+func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Can you please add a TODO to add some caching to it?

If there will be too many calls to it, it may overload apiaserver.

Comment (wojtek-t) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Ideally, we would like to make it watch-based.

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 12]
```diff
@@ -250,50 +253,56 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
+			return nil, fmt.Errorf("Could not find zone for node %v", node.ObjectMeta.Name)
 		}
 	}
-
 	return zones, nil
 }
 
+// GetAllManagedZones gets all the zones managed by k8s
+func (gce *GCECloud) GetAllManagedZones() (sets.String, error) {
+	if gce.managedZones != nil {
```
[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Yes, it set from the config and doesn't ever change after. I feel like the zones returned by this method could be different from GetAllCurrentZones

File: pkg/cloudprovider/providers/gce/gce_instances.go (hunk 10 above)
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: I see your point. I have removed this method and replaced the one use with GetAllCurrentZones

File: pkg/cloudprovider/providers/gce/gce_instances.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: I'm not sure how useful "zones when initialized" is considering you can add/remove zones during runtime.

[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Yes - that was my point when I suggested removing it. It seems @davidz627 agreed for removing this function completely in another comment I added.

File: test/e2e/e2e.go [hunk 13]
```diff
@@ -101,10 +101,17 @@ func setupProviderConfig() error {
 			return fmt.Errorf("Error building GCE/GKE provider: %v", err)
 		}
 
+		cs, err := framework.LoadClientset()
+		if err != nil {
+			glog.Fatal("Error loading client: ", err)
+		}
+		gceCloud.SetClientSet(cs)
```
[the remark this answers is not in the document]
Comment (davidz627) [reply test/e2e/e2e.go]: It seems to be set using a method "Initialize" in gce.go. It's the line "gce.client = clientBuilder.ClientOrDie("cloud-provider")".

Looks like in production code this is done separately from creating the gceCloud object itself because it is an interface method and is called for any of the many cloud objects. It is called here:
https://github.com/kubernetes/kubernetes/blob/6b6b1e5779449a63079c9ff400da752975fe8a06/cmd/cloud-controller-manager/app/controllermanager.go#L176

Additionally I'm not sure that the clientset is a "config" item. In production code the cloudconfig is generated from reading in a config file and the clientset doesn't really seem to fit into that paradigm.

Setting the clientset with a method (although not the same method) after it is created is consistent with how it works in the production code. I think adding it to the CloudConfig for the e2e tests would actually make it inconsistent with the production code. I am open to adding it to the CloudConfig if you still think it is the right move, just wanted to provide you with additional info before we make a decision.

[the remark this answers is not in the document]
Comment (msau42) [reply test/e2e/e2e.go]: Ok that's fine then. Thanks for the detailed explanation!

File: pkg/cloudprovider/providers/gce/gce_instances.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Something that confuses me.  There are a few places that iterate through managedZones, but if managedZones never changed after initialization, how does it get new zones that are added later?

[the remark this answers is not in the document]
Comment (wojtek-t) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: If you look into the code carefully managedZones can only be set to:
1. single zone (in case of zonal clusters)
2. all zones from the region (in case of multizonal ones).

So there is no need to change that.

[the remark this answers is not in the document]
Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Ah got it thanks!

[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: I am a little confused as well. In a multizonal cluster then we have this:

https://github.com/kubernetes/kubernetes/blob/6b6b1e5779449a63079c9ff400da752975fe8a06/pkg/cloudprovider/providers/gce/gce_disks.go#L279

Which would technically allow creation of PDs in all zones in the region. Is this expected behavior? It is my understanding that this PR was meant to solve this problem (which it does by never supplying this function with a zone set that contains no nodes), however the check I linked above does not seem to be consistent with our desired behavior.

[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: It seems like all other uses of managedZones makes sense to me. Just this one seems to be related to the issue this PR is trying to solve. Can anyone confirm?

[the remark this answers is not in the document]
Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: It's checking that the zone passed in is in the managedZones list, but maybe it makes more sense to compare against GetAllCurrentZones.  The actual selection of the zone is done by ChooseZoneForVolumes, which calls GetAllCurrentZones already.  But it's also possible for the user to explicitly set an invalid zone as well.

[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: @saad-ali we were wondering if we should restrict both CreateDisk and CreateRegionalDisk to only being able to create disks in zones with nodes in them (a la GetAllCurrentZones). Or if they should be left in the current state (to allow users to create disks in any zone in the region).

In its current state we believe that a user trying to create a Disk in a zone without a node would be most likely a mistake (since the PD would be unusable) and should trigger an error. However, it could be possible that advanced users may want to be able to create PDs in zones without nodes for regionaldisks for manual failover.

What do you think, Saad? It seems to be a tradeoff between failing fast for standard use-cases, or allowing users to do hypothetical funky things manually that we may not want.

[the remark this answers is not in the document]
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: FWIW @msau42 and I think surfacing an error for provisioning a PD in a zone without nodes is the way to go here. But I am interested to see if this may have some unintended side effects or if we missed some other use cases.

[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: > @saad-ali we were wondering if we should restrict both CreateDisk and CreateRegionalDisk to only being able to create disks in zones with nodes in them (a la GetAllCurrentZones). Or if they should be left in the current state (to allow users to create disks in any zone in the region).

In its current state we believe that a user trying to create a Disk in a zone without a node would be most likely a mistake (since the PD would be unusable) and should trigger an error. However, it could be possible that advanced users may want to be able to create PDs in zones without nodes for regionaldisks for manual failover.

What do you think, Saad? It seems to be a tradeoff between failing fast for standard use-cases, or allowing users to do hypothetical funky things manually that we may not want.
> 
> FWIW @msau42 and I think surfacing an error for provisioning a PD in a zone without nodes is the way to go here. But I am interested to see if this may have some unintended side effects or if we missed some other use cases.

I agree, provisioning a volume in a zone that does not have any active nodes should result in an error.

**Comment by davidz627** [comment]
All comments addressed.

File: test/e2e/storage/volume_provisioning.go [hunk 14]
```diff
@@ -421,8 +421,8 @@ var _ = SIGDescribe("Dynamic Provisioning", func() {
 			gceCloud, err := framework.GetGCECloud()
 			Expect(err).NotTo(HaveOccurred())
 
-			// Get all k8s managed zones
-			managedZones, err = gceCloud.GetAllZones()
+			// Get all k8s managed zones (in this case it is just the single zone)
```
Comment (wojtek-t) [inline test/e2e/storage/volume_provisioning.go]: I don't think that's actually true. If you will be running this test for multizone clusters, these actually can be more than one zone.

**Review by wojtek-t — COMMENTED** [review]
One minor comment. Also please squash commits

Other than that LGTM

**Comment by davidz627** [comment]
Lots of unit test issues because of change to CreateDisk. Have to modify many of them so that may need to be looked at later.

**Comment by davidz627** [comment]
comment addressed. Modified unit tests and level of indirection for GetAllCurrentZones. Please review new commit changes.

File: pkg/cloudprovider/providers/gce/gce_disks_test.go [hunk 15]
```diff
@@ -37,7 +38,8 @@ func TestCreateDisk_Basic(t *testing.T) {
 	/* Arrange */
 	gceProjectId := "test-project"
 	gceRegion := "fake-region"
-	fakeManager := newFakeManager(gceProjectId, gceRegion)
+	zonesWithNodes := []string{"zone1"}
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_disks_test.go]: Can we remove the managedZones setting in these tests?

Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_disks_test.go]: many of the tests rely on "managed zones", especially the ones that delete instances. I can remove them on the ones that don't require doing a delete if you think that would be useful

Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_disks_test.go]: nah, I'm just trying to see if there's a way we can avoid duplicate definitions.  Maybe can you change the managedZones to use zonesWithNodes?

File: test/e2e/ubernetes_lite.go [hunk 16]
```diff
@@ -61,8 +64,136 @@ var _ = framework.KubeDescribe("Multi-AZ Clusters", func() {
...
+		OnlyAllowNodeZones(f, zoneCount, image)
+	})
 })
 
+// OnlyAllowNodeZones tests that GetAllCurrentZones returns only zones with Nodes
+func OnlyAllowNodeZones(f *framework.Framework, zoneCount int, image string) {
+	gceCloud, err := framework.GetGCECloud()
```
Comment (msau42) [inline test/e2e/ubernetes_lite.go]: Do we need to add a check to make sure this test only runs for gce and gke?

**Review by msau42 — COMMENTED** [review]
this lgtm after addressing the provider check in the test.  please squash, thanks!

**Comment by dims** [comment]
@jdumars @kubernetes/kubernetes-release-managers Can you please add the v1.8 label?

File: test/e2e/ubernetes_lite.go (hunk 16 above)
Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: I believe thats already covered: https://github.com/davidz627/kubernetes/blob/38fd65b0cfdc84f47ee03c22ff0462a24be4c9ec/test/e2e/ubernetes_lite.go#L46

Comment (davidz627) [reply test/e2e/ubernetes_lite.go]: unless you mean that I should have it not run on AWS. In which case that could be added.

**Comment by saad-ali** [comment]
/lgtm
/approve

@jdumars If this PR has any further issues, feel free to punt to next milestone. This is not a release blocking issue.

**Comment by saad-ali** [comment]
Looks like this may have broken StatefulSet tests? @davidz627 could you take a look. 

I'm moving this out of 1.8 milestone so that it is not blocking the release. Please cherry pick to 1.8, 1.7, 1.6, etc. once this merges.

**Comment by davidz627** [comment]
Yep, its definitely actually breaking those tests. I'll take a look into it.

**Comment by davidz627** [comment]
Seems like it's a permissions issue since the new GetAllCurrentZones implementation does a "List" of the nodes we get the error:
ProvisioningFailed: Failed to provision volume with StorageClass "standard": nodes is forbidden: User "system:serviceaccount:kube-system:cloud-provider" cannot list nodes at the cluster scope

Is this permissions error something specific to the Statefulset tests or is this a problem that we need to consider that could be an issue when provisioning disks on any cloud provider. I don't really understand why the statefulset provisioning has less permissions than provisioning in other E2E tests (I have confirmed other e2e tests that provision disks are working fine).

For reference, the PVC they use is here:
https://github.com/kubernetes/kubernetes/blob/507af4b9c222907a212234f62484e83fdeefe394/test/e2e/framework/statefulset_utils.go#L750

Anyone have any ideas?

**Comment by davidz627** [comment]
Weirdly enough I don't get these errors at all when running the E2E tests on my own E2E cluster. Could this be a test config issue?

**Comment by liggitt** [comment]
> Seems like it's a permissions issue since the new GetAllCurrentZones implementation does a "List" of the nodes we get the error:
ProvisioningFailed: Failed to provision volume with StorageClass "standard": nodes is forbidden: User "system:serviceaccount:kube-system:cloud-provider" cannot list nodes at the cluster scope
> 
> Is this permissions error something specific to the Statefulset tests or is this a problem that we need to consider that could be an issue when provisioning disks on any cloud provider. I don't really understand why the statefulset provisioning has less permissions than provisioning in other E2E tests (I have confirmed other e2e tests that provision disks are working fine).

cc @kubernetes/sig-auth-pr-reviews

The role for the cloud-provider service account only has configmap permissions.

**Comment by liggitt** [comment]
> The role for the cloud-provider service account only has configmap permissions.

To allow this, you'd need to add the following to the cloud-provider role:

```
	addNamespaceRole(metav1.NamespaceSystem, rbac.Role{
		// role for the cloud providers to access/create kube-system configmaps
		ObjectMeta: metav1.ObjectMeta{Name: saRolePrefix + "cloud-provider"},
		Rules: []rbac.PolicyRule{
			rbac.NewRule("create", "get", "list", "watch").Groups(legacyGroup).Resources("configmaps").RuleOrDie(),
			rbac.NewRule("list").Groups(legacyGroup).Resources("nodes").RuleOrDie(),
		},
	})
```

I think it's worth asking why we have a GCE-specific role in our bootstrap roles... it seems like it would be better to make that grant part of the GCE-deployment, since only the GCE cloud provider needs that permission

**Comment by liggitt** [comment]
also, listing nodes is expensive on large clusters. doing that to calculate a secondary piece of info (unique zones across nodes) is less than ideal, especially when the zones are self-reported by nodes, based on info they get from the cloud provider. how frequently is this called? what are the consequences if a node mis-reports a zone?

**Comment by jlowdermilk** [comment]
> The role for the cloud-provider service account only has configmap permissions.

Sorry for joining this late, but why does cloud provider only get access to configmaps? Doesn't that just mean you need a custom controller that watches resources and updates config map if you want the cloudprovider to do anything interesting?

**Comment by wojtek-t** [comment]
Yeah - I think I agree with @jlowdermilk - see my comment here: https://github.com/kubernetes/kubernetes/issues/50115#issuecomment-335367383

**Comment by davidz627** [comment]
added permissions to cloud provider to list nodes according to discussion on issue. Ready to squash commits if it looks good.

**Comment by davidz627** [comment]
dont bother looking until i fix these test failures. something is going terribly wrong

File: pkg/cloudprovider/providers/gce/gce.go [hunk 17]
```diff
@@ -784,3 +789,32 @@ func (manager *gceServiceManager) getProjectsAPIEndpointAlpha() string {
 
 	return projectsApiEndpoint
 }
+
+// GetAllCurrentZones returns all the zones in which nodes are currently running
+// TODO: Caching, but this is currently only called when we are creating a volume,
+// which is a relatively infrequent operation, and this is only 1 API call.
+// Ideally we want to make this watch-based
+// TODO: When node labels are secure we should go back to using gcloud API
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce.go]: IIUC, it's actually the K8 Node labels we want to secure and use in the end, not the gce instance labels.

**Review by msau42 — COMMENTED** [review]
please squash

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go [hunk 18]
```diff
@@ -59,6 +59,16 @@ func buildControllerRoles() ([]rbac.ClusterRole, []rbac.ClusterRoleBinding) {
 	controllerRoleBindings := []rbac.ClusterRoleBinding{}
 
 	addControllerRole(&controllerRoles, &controllerRoleBindings, rbac.ClusterRole{
+		// role for the cloud providers to list kubernetes nodes, required for
+		// GetAllCurrentZones(). See: https://github.com/kubernetes/kubernetes/issues/50115
+		// Remove when node labels are secured so we can use them to
+		// determine cluster vs non-cluster instances
+		ObjectMeta: metav1.ObjectMeta{Name: saRolePrefix + "cloud-provider"},
```
Comment (liggitt) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: Listing nodes isn't particularly sensitive, but I think this is a poorly defined role that is likely to amass unrelated permissions. Is there a reason not to make this and the service account specific to GCE (since the client and usage is specific to GCE)?

What's the plan for moving the GCE PV provisioner to run out of tree, to the point where this is no longer needed as core policy?

Separately, is scalability concerned by fully listing all node API objects on every call to CreateDisk/CreateRegionalDisk/CreateVolume on large clusters? (@wojtek-t , @shyamjvs?)

Comment (msau42) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: As part of CSI, the GCE volume plugin will be moved out of tree, but it is still a few releases out.

In terms of scalability, we should add some some caching eventually so we don't need to call this every time we provision a disk.  I guess the difference between getting K8s nodes and GCE instances is that the gce api was filtered, so all nodes were not getting returned.  Listing all k8s nodes could cause memory usage to momentarily spike.

Comment (shyamjvs) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: Sorry I'm lacking context here. FWIU the code, the cloud-provider controller is listing k8s node objects on calls to createDisk. From scalability perspective, imo we should be using informer cache instead of making those list calls (any reason why we're not doing it currently?). Also from @msau42 's comment above, I'm wondering if all k8s nodes need to be listed (or just some with a selector)?

Comment (shyamjvs) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: List node calls can be time-consuming on large clusters. For e.g on our 5k-node clusters we see a 99%ile latency of ~1.3s (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/58/artifacts/APIResponsiveness_density_2017-11-03T21:50:19Z.json) which can slow down the createDisk operation (though I don't know how slow other operations are relatively).

Comment (msau42) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: For context, previously what happened during CreateDisk() is that we would call gce.Instances.List() across all zones in the region, truncated to one page of results each.  But this method returns gce instances that are not managed by Kubernetes.  So the change we want to make here is to change the call to kube.Nodes.List() to only get the nodes that we manage.  It is possible that the the new method will return more nodes to process than the old method since the results are not being truncated.

The cloud provider library currently doesn't have the plumbing in place to pass in informers, but that can be investigated.  I don't believe the difference would show up as a significant performance issue.  Disk creation is already slow, and is not measured in our tests.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 19]
```diff
@@ -756,3 +762,30 @@ func (manager *gceServiceManager) getProjectsAPIEndpointAlpha() string {
...
+		return nil, fmt.Errorf("Client not set on GCECloud object")
+	}
+	nodeList, err := client.Core().Nodes().List(metav1.ListOptions{})
+	if err != nil {
+		return nil, err
+	}
+
+	for _, node := range nodeList.Items {
+		labels := node.ObjectMeta.Labels
+		zone, ok := labels[kubeletapis.LabelZoneFailureDomain]
```
Comment (shyamjvs) [inline pkg/cloudprovider/providers/gce/gce.go]: Why not just make the list call above use a labelSelector that checks that the zone label exists?

Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce.go]: Great suggestion!

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go (hunk 18 above)
Comment (shyamjvs) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: Makes sense.

> Listing all k8s nodes could cause memory usage to momentarily spike.

Yes, for reasonably large clusters (it's about 20MB for 5k-node cluster). It can be further aggravated if there are multiple parallel CreateDisk calls - though I don't know how much that can happen in practice.

> The cloud provider library currently doesn't have the plumbing in place to pass in informers, but that can be investigated. I don't believe the difference would show up as a significant performance issue. Disk creation is already slow, and is not measured in our tests.

Sounds reasonable. Saw a TODO for moving it to watch later on.

Comment (shyamjvs) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: I suggested a way to reduce the no. of listed nodes in https://github.com/kubernetes/kubernetes/pull/52322#discussion_r149496088. Besides that, there's one more way by which you can reduce further. Assuming you already know the names of all zones in the region (which sounds like the case from earlier), all you need to do is just list one instance with that label value. You can do this by setting `limit=1` param in your list call. This will totally eliminate the memory spike - but at the cost of multiple (but faster) list calls.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 19 above)
Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce.go]: The only downside is that instead of one api call, we need to make one for each zone in the region every time.  I don't think create disk operations are in practice frequent enough to hit qps limits (although it's easy to come up with a theoretical example that will), but it's something to be aware of.  If we make this informer based, then this problem should be eliminated.

Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce.go]: I discussed with @davidz627, and we decided to look into the informer approach, and keep a cache of zones in the cloud provider that gets updated on node add/delete events.  This solves all 3 issues:

* doesn't make any additional API calls
* don't need to iterate through all the nodes
* don't need to add node list permissions for cloud provider??? (because controller manager already has list permissions for the informer)  Actually I'm not sure why we needed to add the cluster role binding in the first place as controller manager should already have list permissions.

Comment (shyamjvs) [reply pkg/cloudprovider/providers/gce/gce.go]: Perfect!
Regarding your 3rd point, I guess it's because each controller has its own identity and hence its own RBAC (https://github.com/davidz627/kubernetes/blob/a60e757f816d7468e805fa9500b83c344576c3b6/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml).

Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce.go]: One possible issue.  Going with the informer method requires us to modify the cloud provider interface to be able to pass in the informer.  But I think the cloud provider API is under a freeze as we're migrating to out of tree cloud providers.

**Comment by davidz627** [comment]
Completely redone to take advantage of node-informer to solve all of our problems.

I can probably remove the RBAC permissions in another commit. Please take a close look at the most recent commit.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go [hunk 20]
```diff
@@ -59,6 +59,16 @@ func buildControllerRoles() ([]rbac.ClusterRole, []rbac.ClusterRoleBinding) {
 	controllerRoleBindings := []rbac.ClusterRoleBinding{}
 
 	addControllerRole(&controllerRoles, &controllerRoleBindings, rbac.ClusterRole{
+		// role for the cloud providers to list kubernetes nodes, required for
```
Comment (davidz627) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: remove this

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml [hunk 21]
```diff
@@ -42,6 +42,23 @@ items:
     creationTimestamp: null
     labels:
       kubernetes.io/bootstrapping: rbac-defaults
+    name: system:controller:cloud-provider
```
Comment (davidz627) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-role-bindings.yaml]: revert

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml [hunk 22]
```diff
@@ -95,6 +95,22 @@ items:
     creationTimestamp: null
     labels:
       kubernetes.io/bootstrapping: rbac-defaults
+    name: system:controller:cloud-provider
+  rules:
+  - apiGroups:
+    - ""
```
Comment (davidz627) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/controller-roles.yaml]: revert

File: pkg/cloudprovider/providers/gce/gce.go [hunk 23]
```diff
@@ -582,6 +594,59 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	nodeInformer := informerFactory.Core().V1().Nodes()
+	nodeInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc: func(obj interface{}) {
+			node := obj.(*v1.Node)
+			gce.insertNodeZones(node)
+		},
+		UpdateFunc: func(prev, obj interface{}) {
+			prevNode := prev.(*v1.Node)
+			newNode := obj.(*v1.Node)
+			gce.deleteNodeZones(prevNode)
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce.go]: This results in a period where the zones are wrong. Calculate the diff and update.

File: pkg/cloudprovider/cloud.go [hunk 24]
```diff
@@ -47,6 +48,8 @@ type Interface interface {
 	ScrubDNS(nameservers, searches []string) (nsOut, srchOut []string)
 	// HasClusterID returns true if a ClusterID is required and set
 	HasClusterID() bool
+	// SetInformers sets the informer on the cloud object. Also returns true if the interface is supported, false otherwise.
+	SetInformers(informerFactory informers.SharedInformerFactory) bool
```
Comment (liggitt) [inline pkg/cloudprovider/cloud.go]: I would avoid making all cloud providers implement this. Either an optional interface gce can implement or a param to Initialize would make more sense

File: pkg/cloudprovider/providers/gce/gce.go [hunk 25]
```diff
@@ -582,6 +594,59 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	return true
+}
+
+func (gce *GCECloud) insertNodeZones(node *v1.Node) {
+	zone, ok := node.ObjectMeta.Labels[kubeletapis.LabelZoneFailureDomain]
+	if ok {
+		if gce.nodeZones[zone] == nil {
+			gce.nodeZones[zone] = sets.NewString()
+		}
+		gce.nodeZones[zone].Insert(node.ObjectMeta.Name)
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce.go]: Needs to be locked to avoid race read/writes

File: pkg/cloudprovider/providers/gce/gce.go [hunk 26]
```diff
@@ -582,6 +594,59 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	}
+}
+
+func (gce *GCECloud) deleteNodeZones(node *v1.Node) {
+	zone, ok := node.ObjectMeta.Labels[kubeletapis.LabelZoneFailureDomain]
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce.go]: Lock

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 27]
```diff
@@ -273,35 +275,37 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
 }
 
+// GetAllCurrentZones returns all the zones in which nodes are currently running
+func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
+	if !controller.WaitForCacheSync("cloud-provider", wait.NeverStop, gce.nodeInformerSynced) {
+		return nil, fmt.Errorf("Node informer is not synced when trying to GetAllCurrentZones")
+	}
+
+	zones := sets.NewString()
+	for zone, nodes := range gce.nodeZones {
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Guard with lock

File: pkg/cloudprovider/providers/gce/gce.go [hunk 28]
```diff
@@ -582,6 +594,59 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	if ok {
+		gce.nodeZones[zone].Delete(node.ObjectMeta.Name)
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce.go]: If zero length remains, remove

File: pkg/cloudprovider/cloud.go (hunk 24 above)
Comment (davidz627) [reply pkg/cloudprovider/cloud.go]: I think we looked into this and due to the nature of where the informers must be set the SetInformers method must be generic to all cloud providers.

See CreateControllerContext in controllermanager.go:
A possible alternative is to only set informers on the cloud if "s.CloudProvider == 'gce'" by then doing a cast of the generic cloud object. I believe that it would be much more brittle this way and would prefer to keep it generic.

Comment (liggitt) [reply pkg/cloudprovider/cloud.go]: > due to the nature of where the informers must be set the SetInformers method must be generic to all cloud providers.

That's a good use case for optional interfaces. Unrelated setters with empty implementations in all but one cloud provider is a code smell

Comment (msau42) [reply pkg/cloudprovider/cloud.go]: You can add a new interface, maybe something like "InformerUser" interface.  Then you can check if the cloud object implements it, and then call SetInformers.  You can see the other examples of interfaces in this file.

Comment (davidz627) [reply pkg/cloudprovider/cloud.go]: Understood, I was unaware of this way of doing things. Thanks for the tip. I'll add it in now

File: cmd/kube-controller-manager/app/controllermanager.go [hunk 29]
```diff
@@ -441,6 +442,11 @@ func CreateControllerContext(s *options.CMServer, rootClientBuilder, clientBuild
 		}
 	}
 
+	gceCloud, ok := cloud.(*gce.GCECloud)
```
Comment (msau42) [inline cmd/kube-controller-manager/app/controllermanager.go]: try casting it as an InformerUser, instead of gce

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 30]
```diff
@@ -274,12 +275,55 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
-// which is a relatively infrequent operation, and this is only 1 API call.
-// Ideally we want to make this watch-based
+// GetAllCurrentZones returns all the zones in which k8s nodes are currently running
 func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
-	return gce.manager.GetAllCurrentZones(gce.client)
+	if gce.nodeInformerSynced == nil {
+		glog.Warningf("GCECloud object does not have informers set, should only happen in E2E tests.")
+		return gce.GetAllZonesE2E()
+	}
+	if !controller.WaitForCacheSync("cloud-provider", wait.NeverStop, gce.nodeInformerSynced) {
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: I don't know if I would wait forever.  Can we just return an error immediately?

File: test/e2e/multicluster/ubernetes_lite.go [hunk 31]
```diff
@@ -75,76 +74,8 @@ func OnlyAllowNodeZones(f *framework.Framework, zoneCount int, image string) {
...
-	}()
-
-	// GetAllZones functionality checking.
-	By("Checking that GetAllCurrentZones returns the same amount of zones as before the compute is created")
-	gotZones, err := gceCloud.GetAllCurrentZones()
-	Expect(err).NotTo(HaveOccurred())
-
-	Expect(gotZones.Equal(expectedZones)).To(BeTrue(), fmt.Sprintf("Expected zones: %v, Got Zones: %v", expectedZones, gotZones))
 
 	By("Creating zoneCount+1 PVCs and making sure PDs are only provisioned in zones with nodes")
```
Comment (msau42) [inline test/e2e/multicluster/ubernetes_lite.go]: This test should still create an instance in an unmanaged zone.

**Comment by davidz627** [comment]
comments addressed.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 32]
```diff
@@ -125,6 +131,12 @@ type GCECloud struct {
 	useMetadataServer        bool
 	operationPollRateLimiter flowcontrol.RateLimiter
 	manager                  diskServiceManager
+	// nodeZones is a mapping from Zone to a sets.String of Node's names in the Zone
+	// it is updated by the nodeInformer
+	nodeZones          map[string]sets.String
+	nodeInformerSynced cache.InformerSynced
+	// Lock to access to node informers
+	nodeInformerLock sync.Mutex
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce.go]: The name of this lock is misleading. It is protecting nodeZones, not nodeInformer.

Can you maybe rename it to nodeZonesLock or sth like that?

File: pkg/cloudprovider/providers/gce/gce.go [hunk 33]
```diff
@@ -582,6 +595,83 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	newZone, ok := newNode.ObjectMeta.Labels[kubeletapis.LabelZoneFailureDomain]
+	if ok {
+		if gce.nodeZones[newZone] == nil {
+			gce.nodeZones[newZone] = sets.NewString()
+		}
+		gce.nodeZones[newZone].Insert(newNode.ObjectMeta.Name)
+	}
+}
+
+func (gce *GCECloud) insertNodeZones(node *v1.Node) {
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce.go]: Instead of having all:
- insertNodeZones
- updateNodeZones
- deleteNodeZones
[which all look pretty much the same]

it would be enough to have "updateNodeZones" (as above), but allow for passing "nil" as both prevNode and newNode

[Then prevNode=nil means insert, newNode=nil means delete]

**Review by wojtek-t — COMMENTED** [review]
Just two minor comments - other than that LGTM

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 34]
```diff
@@ -273,35 +274,42 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
 	})
 }
 
-// GetAllZones returns all the zones in which nodes are running
-func (gce *GCECloud) GetAllZones() (sets.String, error) {
+// GetAllCurrentZones returns all the zones in which k8s nodes are currently running
+func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
+	if gce.nodeInformerSynced == nil {
+		glog.Warningf("GCECloud object does not have informers set, should only happen in E2E tests.")
+		return gce.GetAllZonesE2E()
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: GetAllZonesE2E should not exist in non-test code

Comment (liggitt) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: why doesn't looking up from the node labels work in e2e? And why is nodeInformerSynced nil in e2e?

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 35]
```diff
@@ -273,35 +274,42 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
+	}
+	if !gce.nodeInformerSynced() {
+		return nil, fmt.Errorf("Node informer is not synced when trying to GetAllCurrentZones")
+	}
+	zones := sets.NewString()
+	for zone, nodes := range gce.nodeZones {
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Isn't this unlocked access to nodeZones?

File: pkg/cloudprovider/providers/gce/gce_instances.go (hunk 34 above)
Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: In the E2E tests it seems that there is a "local" version of the cloud provider that doesn't have any informers set (so checking nodeInformerSynced nil is a good proxy for checking existence of informers). We need "backup" GetAllZones functionality for the tests that use GetAllZones functionality with this local cloud provider controller. Maybe GetAllZonesE2E isn't the best name for it?

File: pkg/cloudprovider/providers/gce/gce.go [hunk 36]
```diff
@@ -125,6 +131,12 @@ type GCECloud struct {
 	useMetadataServer        bool
 	operationPollRateLimiter flowcontrol.RateLimiter
 	manager                  diskServiceManager
+	// nodeZones is a mapping from Zone to a sets.String of Node's names in the Zone
+	// it is updated by the nodeInformer
+	nodeZones          map[string]sets.String
+	nodeInformerSynced cache.InformerSynced
+	// Lock to access to node informers
+	nodeZonesLock sync.Mutex
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce.go]: nit: can you please move it before "nodeZones" - we generally declare the lock before vars it is protecting.
Also, please update its comment.

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 37]
```diff
@@ -273,35 +274,44 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
...
+	}
+	return zones, nil
+}
+
+// GetAllZonesBackup returns all the zones in which nodes are running
+// Only use this in E2E tests to get zones, on real clusters this will
+// get all zones with compute instances in them even if not k8s instances!!!
+// ex. I have k8s nodes in us-central1-c and us-central1-b. I also have
+// a non-k8s compute in us-central1-a. This func will return a,b, and c.
+func (gce *GCECloud) GetAllZonesBackup() (sets.String, error) {
```
Comment (wojtek-t) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: nit: Maybe GetAllZonesSlow ?
or GetAllZonesFromCloudProvider?

**Review by wojtek-t — COMMENTED** [review]
Just two very minor comments.

**Comment by davidz627** [comment]
comments addressed :)

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 38]
```diff
@@ -273,35 +274,44 @@ func (gce *GCECloud) AddSSHKeyToAllInstances(user string, keyData []byte) error
 	})
 }
 
-// GetAllZones returns all the zones in which nodes are running
-func (gce *GCECloud) GetAllZones() (sets.String, error) {
+// GetAllCurrentZones returns all the zones in which k8s nodes are currently running
+func (gce *GCECloud) GetAllCurrentZones() (sets.String, error) {
+	if gce.nodeInformerSynced == nil {
+		glog.Warningf("GCECloud object does not have informers set, should only happen in E2E tests.")
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Specifically, the e2e binary.

File: pkg/cloudprovider/providers/gce/gce_instances.go [hunk 39]
```diff
@@ -317,6 +327,17 @@ func (gce *GCECloud) GetAllZones() (sets.String, error) {
 	return zones, nil
 }
 
+// SetClientSet sets the ClientSet on the GCECloud object for e2e tests
+func (gce *GCECloud) SetClientSet(c clientset.Interface) {
```
Comment (msau42) [inline pkg/cloudprovider/providers/gce/gce_instances.go]: Do we still need this, if the e2e binary is still getting all the zones from the cloud provider?

Comment (davidz627) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: Technically not, but it might still be useful for the future?

Comment (msau42) [reply pkg/cloudprovider/providers/gce/gce_instances.go]: I would leave it out until we need it

**Comment by wojtek-t** [comment]
/approve

LGTM, but I will let @msau42 to LGTM it when she thinks it's ready.

**Comment by wojtek-t** [comment]
@msau42 @liggitt - WDYT about cherrypicking it 1.8 branch? This is effectively a bug fix.

**Comment by msau42** [comment]
Yes on cherrypick.  I believe this bug has existed from the beginning.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 40]
```diff
@@ -582,6 +595,63 @@ func (gce *GCECloud) IsLegacyNetwork() bool {
...
+	glog.Infof("Setting up informers for GCECloud")
+	nodeInformer := informerFactory.Core().V1().Nodes().Informer()
+	nodeInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
+		AddFunc: func(obj interface{}) {
+			node := obj.(*v1.Node)
+			gce.updateNodeZones(nil, node)
+		},
+		UpdateFunc: func(prev, obj interface{}) {
+			prevNode := prev.(*v1.Node)
+			newNode := obj.(*v1.Node)
```
Comment (liggitt) [inline pkg/cloudprovider/providers/gce/gce.go]: on large scale clusters, this can get called 5000 times every 10 seconds. short-circuit if `reflect.DeepEqual(newNode.Labels, prevNode.Labels)`

**Comment by wojtek-t** [comment]
> Yes on cherrypick. I believe this bug has existed from the beginning.

Yeah - I think so. We should probably also cherrypick it to 1.7 (I think we're no longer cherrypicking 1.6).

**Comment by liggitt** [comment]
one nit on filtering out no-op node updates

**Comment by davidz627** [comment]
addressed comments and fixed test.

**Comment by wojtek-t** [comment]
Added cherrypick-candidate label - this should be cherrypicked to 1.7 and 1.8 branches.

**Comment by wojtek-t** [comment]
@davidz627  - I wanted to do automated cherrypick of it to 1.8 branch but it generated conflicts. Can you please create this cherrypick - I think it's better since you wrote this code.

**Comment by wojtek-t** [comment]
Thanks @davidz627 !
