### PR TITLE
Fixed persistent volume claim controllers processing an old claim.

### LINKED ISSUE #19860: Dynamic provisioner sometimes creates two volumes for one claim
I noticed that sometimes (<10%) Kubernetes do not delete volumes it created. Digging into logs, I can see this sequence in the persistent volume controller:

```log
I0120 12:21:06.951473    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:06.951572    2571 persistentvolume_claim_binder_controller.go:342] A volume match does not exist for persistent claim: pvc-8z0kk
I0120 12:21:07.009176    2571 persistentvolume_provisioner_controller.go:174] PersistentVolumeClaim[pvc-8z0kk] provisioning
I0120 12:21:07.100719    2571 persistentvolume_provisioner_controller.go:197] Unprovisioned PersistentVolume[pv-cinder-uxgot] created for PVC[pvc-8z0kk], which will be fulfilled in the storage provider
I0120 12:21:07.128868    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-uxgot]
I0120 12:21:07.128923    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-uxgot] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.129204    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-uxgot], current phase: Pending
I0120 12:21:07.129240    2571 persistentvolume_claim_binder_controller.go:214] Skipping PersistentVolume[pv-cinder-uxgot], waiting for provisioning to finish
I0120 12:21:07.186905    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:07.187018    2571 persistentvolume_claim_binder_controller.go:347] PersistentVolume[pv-cinder-uxgot] for PersistentVolumeClaim[e2e-tests-volume-provisioning-scooj/pvc-8z0kk] is still being provisioned.
I0120 12:21:07.190275    2571 persistentvolume_provisioner_controller.go:174] PersistentVolumeClaim[pvc-8z0kk] provisioning
I0120 12:21:07.250590    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-bn5d6]
I0120 12:21:07.263177    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-bn5d6] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.254780    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-bn5d6], current phase: Pending
I0120 12:21:07.263275    2571 persistentvolume_claim_binder_controller.go:214] Skipping PersistentVolume[pv-cinder-bn5d6], waiting for provisioning to finish
I0120 12:21:07.255305    2571 persistentvolume_provisioner_controller.go:197] Unprovisioned PersistentVolume[pv-cinder-bn5d6] created for PVC[pvc-8z0kk], which will be fulfilled in the storage provider
E0120 12:21:07.270106    2571 persistentvolume_provisioner_controller.go:205] error updating persistent volume claim: %vpersistentvolumeclaims "pvc-8z0kk" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
I0120 12:21:07.270162    2571 persistentvolume_provisioner_controller.go:170] PersistentVolumeClaim[pvc-8z0kk] is already provisioned.
I0120 12:21:07.396334    2571 persistentvolume_provisioner_controller.go:212] PersistentVolume[pv-cinder-uxgot] reconciling
I0120 12:21:07.396385    2571 persistentvolume_provisioner_controller.go:246] PersistentVolume[pv-cinder-uxgot] provisioning in progress
I0120 12:21:07.537061    2571 openstack.go:1055] Created volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d
I0120 12:21:07.537110    2571 cinder_util.go:166] Successfully created cinder volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d
I0120 12:21:07.797214    2571 persistentvolume_recycler_controller.go:161] Recycler: checking PersistentVolume[pv-cinder-uxgot]
I0120 12:21:07.799584    2571 persistentvolume_recycler_controller.go:193] PersistentVolume[pv-cinder-uxgot] phase Pending - skipping: The volume is not in a final state
I0120 12:21:07.809612    2571 persistentvolume_claim_binder_controller.go:193] Synchronizing PersistentVolume[pv-cinder-uxgot], current phase: Pending
I0120 12:21:07.992698    2571 persistentvolume_provisioner_controller.go:212] PersistentVolume[pv-cinder-bn5d6] reconciling
I0120 12:21:07.992961    2571 persistentvolume_provisioner_controller.go:246] PersistentVolume[pv-cinder-bn5d6] provisioning in progress
I0120 12:21:08.053157    2571 persistentvolume_claim_binder_controller.go:331] Synchronizing PersistentVolumeClaim[pvc-8z0kk]
I0120 12:21:08.053652    2571 persistentvolume_claim_binder_controller.go:347] PersistentVolume[pv-cinder-bn5d6] for PersistentVolumeClaim[e2e-tests-volume-provisioning-scooj/pvc-8z0kk] is still being provisioned.
I0120 12:21:08.053689    2571 persistentvolume_claim_binder_controller.go:261] PersistentVolume[pv-cinder-uxgot] is available
I0120 12:21:08.054043    2571 persistentvolume_claim_binder_controller.go:318] PersistentVolume[pv-cinder-uxgot] changing phase from Pending to Available
I0120 12:21:08.188433    2571 openstack.go:1055] Created volume b615cae0-1f82-4f94-a1bb-eccf25b710a0
I0120 12:21:08.190127    2571 cinder_util.go:166] Successfully created cinder volume b615cae0-1f82-4f94-a1bb-eccf25b710a0
```

* Two volumes are created for claim `pvc-8z0kk`:
  * At `12:21:07.100719`, PV `pv-cinder-uxgot` is created. 
  * At `12:21:07.255305`, PV `pv-cinder-bn5d6` is created. **Note in the logs:** `error updating persistent volume claim: persistentvolumeclaims "pvc-8z0kk" cannot be updated: the object has been modified; please apply your changes to the latest version and try again`
* These two volumes are provisioned:
  * `pv-cinder-uxgot` at `12:21:07.537061`: `Created volume 0557d70c-3e7a-461b-88c4-d6f464a53d3d`
  * `pv-cinder-bn5d6` at `12:21:08.188433`: `Created volume b615cae0-1f82-4f94-a1bb-eccf25b710a0`
* Both these volumes are bound (!)
* When the claim is deleted, only one of the volumes is deleted.

It's *probably* caused by `Synchronizing PersistentVolumeClaim[pvc-8z0kk]` being called twice in parallel.
@markturansky, please confirm my suspicion. Can it be the periodic check + 'claim updated' event running at the same time? Any idea how to fix it? Lock could be appropriate, still I would prefer if there was possibility to atomically 'get current version of the claim, look at it and update it'. Too many things read/modify object annotations (and more are coming!) and it's pretty hard to keep them from colliding.

cc: @kubernetes/rh-storage, @saad-ali

### PR DESCRIPTION
**Pull request by jsafrane**
Fixes #19860 (it may be easier to look at the issue to see exact sequence
to reproduce the bug and understand the fix).

When `PersistentVolumeProvisionerController.reconcileClaim()` is called with the
same claim in short succession (e.g. the claim is created by an user and
at the same time periodic check of all claims is scheduled), the second
`reconcileClaim()` call gets an old copy of the claim as its parameter.

The method should always reload the claim to get a fresh copy with all
annotations, possibly added by previous `reconcileClaim()` call.

The same applies to `PersistentVolumeClaimBinder.syncClaim()`.

### CODE REVIEW

**Comment by jsafrane** [comment]
Of course, an unit test is on my TODO list. At least we can talk about the fix.

**Comment by jsafrane** [comment]
@k8s-bot test this

**Comment by jsafrane** [comment]
Pushed with an unit test. Also, some old tests had to be updated to store claims in a fake API server before calling `reconcileClaim` and `syncClaim` - these functions will reload it from there.

**Comment by bprashanth** [comment]
@saad-ali would you like me to do this review? I can, ETA is early next week though

**Comment by markturansky** [comment]
thanks @bprashanth but I can take point on this one.

**Comment by markturansky** [comment]
@jsafrane what if we removed claim updating from the provisioning entirely?  We can do the PV creation in the binder while still allowing the provisioner to fulfill the volume.  The provisioner is like the recycler in that it really only needs to work on volumes.

**Comment by jsafrane** [comment]
> We can do the PV creation in the binder

This leaks bits of the provisioning into binder controller. I am not against though, it would make the provisioner controller simpler, operating on PVs only.

And it still leaves the race in binder controller, this PR is still needed.

File: pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go [hunk 1]
```diff
@@ -153,6 +153,16 @@ func (controller *PersistentVolumeProvisionerController) handleUpdateClaim(oldOb
...
 func (controller *PersistentVolumeProvisionerController) reconcileClaim(claim *api.PersistentVolumeClaim) error {
+	glog.V(5).Infof("Synchronizing PersistentVolumeClaim[%s] for dynamic provisioning", claim.Name)
+
+	// The claim may have been modified by parallel call to reconcileClaim, load
+	// the current version.
+	newClaim, err := controller.client.GetPersistentVolumeClaim(claim.Namespace, claim.Name)
+	if err != nil {
+		return fmt.Errorf("Cannot reload claim %s/%s: %v", claim.Namespace, claim.Name, err)
+	}
+	claim = newClaim
```
Comment (markturansky) [inline pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go]: per our IRC discussion, please update the local cache with the latest and greatest version.

Comment (jsafrane) [inline pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go]: Is it safe to update `controller.claimStore` here? Won't it generate a new 'claim updated' event?

Comment (markturansky) [inline pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go]: It is safe.  API updates generate events.  The watch gets the events and puts them in the local store.

**Comment by jsafrane** [comment]
There is something wrong with this PR that breaks integration tests. I am quite  sure it's not a flake, it always fails with the patch and always succeeds without it.

```
I0201 14:22:49.525423    4919 trace.go:57] Trace "Create /api/v1/namespaces/default/persistentvolumeclaims" (started 2016-02-01 14:22:49.274322577 +0000 UTC):
[18.296Âµs] [18.296Âµs] About to convert to expected version
[99.985Âµs] [81.689Âµs] Conversion done
[103.4Âµs] [3.415Âµs] About to store object in database
[250.913786ms] [250.810386ms] Object stored in database
[250.931998ms] [18.212Âµs] Self-link added
[251.068318ms] [136.32Âµs] END
panic: test timed out after 5m0s

<lot of stack traces>
...
FAIL	k8s.io/kubernetes/test/integration	300.037s
```

@markturansky, any idea where to look?

**Comment by jsafrane** [comment]
> There is something wrong with this PR that breaks integration tests.

The integration tests use a kube client with default QPS and Burst values and at the same time it runs periodical update of binder controller every 10 seconds. Since the test creates 100 claims and the binder controller re-reads the claims from etcd, the client slows down the requests. And after 10 seconds a periodic check kicks in, making things even worse...

I updated QPS and Burst values of the test client to make sure it does not start throttling the requests.

**Comment by markturansky** [comment]
Try reducing the claim count to 5-10 in rapid succession?  Making 100 is a bit of a ridiculous test (I know I added it).

**Comment by jsafrane** [comment]
> Try reducing the claim count to 5-10 in rapid succession? Making 100 is a bit of a ridiculous test (I know I added it).


The test as patched in this PR works. Is reducing nr. of claims better than increasing burst & QPS? I have no opinion here, I'm just asking what's better.

**Comment by markturansky** [comment]
I have no preference.  Reducing the number of claims from 100 to 10 still tests the concurrency of the controller. I'm ok with that.  Whichever is easier, frankly.

File: pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go (hunk 1 above)
Comment (jsafrane) [inline pkg/controller/persistentvolume/persistentvolume_provisioner_controller.go]: I added update few lines below.

**Comment by jsafrane** [comment]
Ok, I would like to leave the patch as it is, with higher QPS. If I am not mistaken, all your review remarks was adressed.

**Comment by markturansky** [comment]
LGTM.   

@swagiaal 2nd opinion?

This PR might fix some needed issues today, but I think we're all realizing now how a better controller design will prevent the need for something like this.

**Comment by swagiaal** [comment]
So I think this narrows the window for the race but does not eliminate it :/
Hopefully future work on using resource versions to ensure congruence will alleviate the need for this. This LGTM.
@markturansky back to you

**Comment by jsafrane** [comment]
@k8s-bot test this issue: #21045
