### PR TITLE
[GarbageCollector] Fix 29451

### LINKED ISSUE #29451: TestUpdateSelectorToRemoveControllerRef {replicationcontroller}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/14717/

Failed: TestUpdateSelectorToRemoveControllerRef {replicationcontroller}

```
replicationcontroller_test.go:363: patched rc = &v1.ReplicationController{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"rc", GenerateName:"", Namespace:"update-selector-to-remove-controllerref", SelfLink:"/api/v1/namespaces/update-selector-to-remove-controllerref/replicationcontrollers/rc", UID:"da39aa09-500a-11e6-a064-0242ac110002", ResourceVersion:"3120", Generation:2, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63604788622, nsec:0, loc:(*time.Location)(0x30f70e0)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"name":"test"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil)}, Spec:v1.ReplicationControllerSpec{Replicas:(*int32)(0xc8245906e8), Selector:map[string]string{"name":"test", "uniqueKey":"1"}, Template:(*v1.PodTemplateSpec)(0xc823391860)}, Status:v1.ReplicationControllerStatus{Replicas:2, FullyLabeledReplicas:2, ObservedGeneration:1}}
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:114: expect 3 pods, got 4 pods
replicationcontroller_test.go:368: timed out waiting for the condition
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #29451. I've also checked other tests in that file to make sure they don't have similar problems.

The issue is P0 and will block the submit queue, so I marked this PR as P0.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29798)

### CODE REVIEW

File: test/integration/replicationcontroller/replicationcontroller_test.go [hunk 1]
```diff
@@ -154,6 +154,22 @@ func rmSetup(t *testing.T, enableGarbageCollector bool) (*httptest.Server, *repl
 	return s, rm, podInformer, clientSet
 }
 
+// wait for the podInformer to observe the pods. Call this function before
+// running the RC manager to prevent the rc manager from creating new pods
+// rather than adopting the existing ones.
+func waitToObservePods(t *testing.T, podInformer controllerframwork.SharedIndexInformer, podNum int) {
```
Comment (lavalamp) [inline test/integration/replicationcontroller/replicationcontroller_test.go]: Won't block the fix on this, but it would be good to move this somewhere common so it's not duplicated.

**Comment by lavalamp** [comment]
lgtm
