### PR TITLE
Fix: Recreate DaemonSet pods completed with Succeeded phase

### LINKED ISSUE #117018: daemonset stuck in `Completed` state after a reboot (with graceful kubelet shutdown)
### What happened?

I can reproduce this reliably with Calico v3.25.0 CNI, installed straight from the upstream [manifest](https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml).

It seems to be a **regression** in Kubernetes 1.27.0-rc.0 compared to 1.27.0-beta.0, at least I can't reproduce it with beta.0.

Cluster is deployed, and everything is ready & healthy. After a series of node reboots some `calico-node` pods are stuck in `Completed` state and never recover:

```
NAMESPACE       NAME                                                   READY   STATUS      RESTARTS        AGE     IP               NODE                           NOMINATED NODE   READINESS GATES
kube-system     calico-kube-controllers-6c99c8747f-q5g8d               1/1     Running     2 (14m ago)     26m     192.168.62.135   talos-default-controlplane-2   <none>           <none>
kube-system     calico-node-hm7pf                                      1/1     Running     2 (12m ago)     25m     172.20.0.2       talos-default-controlplane-1   <none>           <none>
kube-system     calico-node-hvws2                                      1/1     Running     2 (11m ago)     25m     172.20.0.4       talos-default-controlplane-3   <none>           <none>
kube-system     calico-node-kf69z                                      0/1     Completed   1               25m     172.20.0.6       talos-default-worker-2         <none>           <none>
kube-system     calico-node-lpkxj                                      0/1     Completed   1 (18m ago)     25m     172.20.0.5       talos-default-worker-1         <none>           <none>
kube-system     calico-node-pngj7                                      1/1     Running     2 (14m ago)     26m     172.20.0.3       talos-default-controlplane-2   <none>           <none>
```

This of course disrupts the CNI and affects the scheduled workloads.

The daemonset is "happy" with 2 pods being out:

```
NAMESPACE     NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE   CONTAINERS    IMAGES                                    SELECTOR
kube-system   calico-node   5         5         3       5            3           kubernetes.io/os=linux   45m   calico-node   docker.io/calico/node:v3.25.0             k8s-app=calico-node
```

If I delete the `Completed` pod manually, the pod recovers without any issues.

### What did you expect to happen?

The pods are restarted.

### How can we reproduce it (as minimally and precisely as possible)?

Bring up a cluster with graceful node shutdown, reboot nodes a few times (including multiple node at anoce).

### Anything else we need to know?

Additional detailed output:

<details>

```
$ kubectl get pods -n kube-system calico-node-kf69z -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-03-30T17:46:42Z"
  generateName: calico-node-
  labels:
    controller-revision-hash: 6c6c65fb6c
    k8s-app: calico-node
    pod-template-generation: "1"
  name: calico-node-kf69z
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: calico-node
    uid: eff56b3d-c824-46f0-b922-26ccb2b94aaa
  resourceVersion: "3335"
  uid: c3624a67-8f41-4449-8024-5a33f7f69f30
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - talos-default-worker-2
  containers:
  - env:
    - name: DATASTORE_TYPE
      value: kubernetes
    - name: WAIT_FOR_DATASTORE
      value: "true"
    - name: NODENAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    - name: CLUSTER_TYPE
      value: k8s,bgp
    - name: IP
      value: autodetect
    - name: CALICO_IPV4POOL_IPIP
      value: Always
    - name: CALICO_IPV4POOL_VXLAN
      value: Never
    - name: CALICO_IPV6POOL_VXLAN
      value: Never
    - name: FELIX_IPINIPMTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: FELIX_VXLANMTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: FELIX_WIREGUARDMTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: CALICO_DISABLE_FILE_LOGGING
      value: "true"
    - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
      value: ACCEPT
    - name: FELIX_IPV6SUPPORT
      value: "false"
    - name: FELIX_HEALTHENABLED
      value: "true"
    envFrom:
    - configMapRef:
        name: kubernetes-services-endpoint
        optional: true
    image: docker.io/calico/node:v3.25.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/calico-node
          - -shutdown
    livenessProbe:
      exec:
        command:
        - /bin/calico-node
        - -felix-live
        - -bird-live
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: calico-node
    readinessProbe:
      exec:
        command:
        - /bin/calico-node
        - -felix-ready
        - -bird-ready
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      requests:
        cpu: 250m
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni-net-dir
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/calico
      name: var-run-calico
    - mountPath: /var/lib/calico
      name: var-lib-calico
    - mountPath: /var/run/nodeagent
      name: policysync
    - mountPath: /sys/fs/bpf
      name: bpffs
    - mountPath: /var/log/calico/cni
      name: cni-log-dir
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9r9p4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - command:
    - /opt/cni/bin/calico-ipam
    - -upgrade
    env:
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CALICO_NETWORKING_BACKEND
      valueFrom:
        configMapKeyRef:
          key: calico_backend
          name: calico-config
    envFrom:
    - configMapRef:
        name: kubernetes-services-endpoint
        optional: true
    image: docker.io/calico/cni:v3.25.0
    imagePullPolicy: IfNotPresent
    name: upgrade-ipam
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/cni/networks
      name: host-local-net-dir
    - mountPath: /host/opt/cni/bin
      name: cni-bin-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9r9p4
      readOnly: true
  - command:
    - /opt/cni/bin/install
    env:
    - name: CNI_CONF_NAME
      value: 10-calico.conflist
    - name: CNI_NETWORK_CONFIG
      valueFrom:
        configMapKeyRef:
          key: cni_network_config
          name: calico-config
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CNI_MTU
      valueFrom:
        configMapKeyRef:
          key: veth_mtu
          name: calico-config
    - name: SLEEP
      value: "false"
    envFrom:
    - configMapRef:
        name: kubernetes-services-endpoint
        optional: true
    image: docker.io/calico/cni:v3.25.0
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/opt/cni/bin
      name: cni-bin-dir
    - mountPath: /host/etc/cni/net.d
      name: cni-net-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9r9p4
      readOnly: true
  - command:
    - calico-node
    - -init
    - -best-effort
    image: docker.io/calico/node:v3.25.0
    imagePullPolicy: IfNotPresent
    name: mount-bpffs
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /sys/fs
      mountPropagation: Bidirectional
      name: sys-fs
    - mountPath: /var/run/calico
      mountPropagation: Bidirectional
      name: var-run-calico
    - mountPath: /nodeproc
      name: nodeproc
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9r9p4
      readOnly: true
  nodeName: talos-default-worker-2
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: calico-node
  serviceAccountName: calico-node
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
  - hostPath:
      path: /var/run/calico
      type: ""
    name: var-run-calico
  - hostPath:
      path: /var/lib/calico
      type: ""
    name: var-lib-calico
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /sys/fs/
      type: DirectoryOrCreate
    name: sys-fs
  - hostPath:
      path: /sys/fs/bpf
      type: Directory
    name: bpffs
  - hostPath:
      path: /proc
      type: ""
    name: nodeproc
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cni-bin-dir
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni-net-dir
  - hostPath:
      path: /var/log/calico/cni
      type: ""
    name: cni-log-dir
  - hostPath:
      path: /var/lib/cni/networks
      type: ""
    name: host-local-net-dir
  - hostPath:
      path: /var/run/nodeagent
      type: DirectoryOrCreate
    name: policysync
  - name: kube-api-access-9r9p4
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T17:56:51Z"
    message: Pod was terminated in response to imminent node shutdown.
    reason: TerminationByKubelet
    status: "True"
    type: DisruptionTarget
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T17:55:25Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T17:56:50Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T17:56:50Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-30T17:46:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3bfddceb18e976566f39625fde9f6203c4d06f48f91264b401c945c19712e98d
    image: docker.io/calico/node:v3.25.0
    imageID: docker.io/calico/node@sha256:a85123d1882832af6c45b5e289c6bb99820646cb7d4f6006f98095168808b1e6
    lastState: {}
    name: calico-node
    ready: false
    restartCount: 1
    started: false
    state:
      terminated:
        containerID: containerd://3bfddceb18e976566f39625fde9f6203c4d06f48f91264b401c945c19712e98d
        exitCode: 0
        finishedAt: "2023-03-30T17:56:24Z"
        reason: Completed
        startedAt: "2023-03-30T17:55:26Z"
  hostIP: 172.20.0.6
  initContainerStatuses:
  - containerID: containerd://78f7523609b616ab91b115721d7db40473b656a2d0d40c97477263e87b734aa2
    image: docker.io/calico/cni:v3.25.0
    imageID: docker.io/calico/cni@sha256:a38d53cb8688944eafede2f0eadc478b1b403cefeff7953da57fe9cd2d65e977
    lastState: {}
    name: upgrade-ipam
    ready: true
    restartCount: 2
    state:
      terminated:
        containerID: containerd://78f7523609b616ab91b115721d7db40473b656a2d0d40c97477263e87b734aa2
        exitCode: 0
        finishedAt: "2023-03-30T17:56:50Z"
        reason: Completed
        startedAt: "2023-03-30T17:56:50Z"
  - containerID: containerd://4ff6b96980023828a85e1527297dd07de61a9cfdc5692fce0635d9b39a76ee5f
    image: docker.io/calico/cni:v3.25.0
    imageID: docker.io/calico/cni@sha256:a38d53cb8688944eafede2f0eadc478b1b403cefeff7953da57fe9cd2d65e977
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 1
    state:
      terminated:
        containerID: containerd://4ff6b96980023828a85e1527297dd07de61a9cfdc5692fce0635d9b39a76ee5f
        exitCode: 0
        finishedAt: "2023-03-30T17:55:25Z"
        reason: Completed
        startedAt: "2023-03-30T17:55:24Z"
  - containerID: containerd://32f143e7f1eb8f81b146941d21f93225c15bdece80f2d5ef39bd862fc52c96f3
    image: docker.io/calico/node:v3.25.0
    imageID: docker.io/calico/node@sha256:a85123d1882832af6c45b5e289c6bb99820646cb7d4f6006f98095168808b1e6
    lastState: {}
    name: mount-bpffs
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://32f143e7f1eb8f81b146941d21f93225c15bdece80f2d5ef39bd862fc52c96f3
        exitCode: 0
        finishedAt: "2023-03-30T17:55:25Z"
        reason: Completed
        startedAt: "2023-03-30T17:55:25Z"
  phase: Succeeded
  podIP: 172.20.0.6
  podIPs:
  - ip: 172.20.0.6
  qosClass: Burstable
  startTime: "2023-03-30T17:47:26Z"
```

```
$ kubectl -n kube-system describe pod calico-node-kf69z
Name:                 calico-node-kf69z
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 talos-default-worker-2/172.20.0.6
Start Time:           Thu, 30 Mar 2023 21:47:26 +0400
Labels:               controller-revision-hash=6c6c65fb6c
                      k8s-app=calico-node
                      pod-template-generation=1
Annotations:          <none>
Status:               Succeeded
IP:                   172.20.0.6
IPs:
  IP:           172.20.0.6
Controlled By:  DaemonSet/calico-node
Init Containers:
  upgrade-ipam:
    Container ID:  containerd://78f7523609b616ab91b115721d7db40473b656a2d0d40c97477263e87b734aa2
    Image:         docker.io/calico/cni:v3.25.0
    Image ID:      docker.io/calico/cni@sha256:a38d53cb8688944eafede2f0eadc478b1b403cefeff7953da57fe9cd2d65e977
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 30 Mar 2023 21:56:50 +0400
      Finished:     Thu, 30 Mar 2023 21:56:50 +0400
    Ready:          True
    Restart Count:  2
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9r9p4 (ro)
  install-cni:
    Container ID:  containerd://4ff6b96980023828a85e1527297dd07de61a9cfdc5692fce0635d9b39a76ee5f
    Image:         docker.io/calico/cni:v3.25.0
    Image ID:      docker.io/calico/cni@sha256:a38d53cb8688944eafede2f0eadc478b1b403cefeff7953da57fe9cd2d65e977
    Port:          <none>
    Host Port:     <none>
    Command:
      /opt/cni/bin/install
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 30 Mar 2023 21:55:24 +0400
      Finished:     Thu, 30 Mar 2023 21:55:25 +0400
    Ready:          True
    Restart Count:  1
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9r9p4 (ro)
  mount-bpffs:
    Container ID:  containerd://32f143e7f1eb8f81b146941d21f93225c15bdece80f2d5ef39bd862fc52c96f3
    Image:         docker.io/calico/node:v3.25.0
    Image ID:      docker.io/calico/node@sha256:a85123d1882832af6c45b5e289c6bb99820646cb7d4f6006f98095168808b1e6
    Port:          <none>
    Host Port:     <none>
    Command:
      calico-node
      -init
      -best-effort
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 30 Mar 2023 21:55:25 +0400
      Finished:     Thu, 30 Mar 2023 21:55:25 +0400
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /nodeproc from nodeproc (ro)
      /sys/fs from sys-fs (rw)
      /var/run/calico from var-run-calico (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9r9p4 (ro)
Containers:
  calico-node:
    Container ID:   containerd://3bfddceb18e976566f39625fde9f6203c4d06f48f91264b401c945c19712e98d
    Image:          docker.io/calico/node:v3.25.0
    Image ID:       docker.io/calico/node@sha256:a85123d1882832af6c45b5e289c6bb99820646cb7d4f6006f98095168808b1e6
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 30 Mar 2023 21:55:26 +0400
      Finished:     Thu, 30 Mar 2023 21:56:24 +0400
    Ready:          False
    Restart Count:  1
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=10s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=10s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      CALICO_IPV6POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_HEALTHENABLED:                true
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/bpf from bpffs (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/log/calico/cni from cni-log-dir (ro)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-9r9p4 (ro)
Conditions:
  Type               Status
  DisruptionTarget   True 
  Initialized        True 
  Ready              False 
  ContainersReady    False 
  PodScheduled       True 
Volumes:
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:  
  var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:  
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  sys-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/
    HostPathType:  DirectoryOrCreate
  bpffs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
  nodeproc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
  cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
  cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
  cni-log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/calico/cni
    HostPathType:  
  host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:  
  policysync:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/nodeagent
    HostPathType:  DirectoryOrCreate
  kube-api-access-9r9p4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 :NoSchedule op=Exists
                             :NoExecute op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       17m                    default-scheduler  Successfully assigned kube-system/calico-node-kf69z to talos-default-worker-2
  Normal   Pulling         16m                    kubelet            Pulling image "docker.io/calico/cni:v3.25.0"
  Normal   Pulled          16m                    kubelet            Successfully pulled image "docker.io/calico/cni:v3.25.0" in 2.574137942s (2.574164652s including waiting)
  Normal   Created         16m                    kubelet            Created container upgrade-ipam
  Normal   Started         16m                    kubelet            Started container upgrade-ipam
  Normal   Pulled          16m                    kubelet            Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal   Created         16m                    kubelet            Created container install-cni
  Normal   Started         16m                    kubelet            Started container install-cni
  Normal   Pulling         16m                    kubelet            Pulling image "docker.io/calico/node:v3.25.0"
  Normal   Pulled          16m                    kubelet            Successfully pulled image "docker.io/calico/node:v3.25.0" in 2.909875156s (2.909886566s including waiting)
  Normal   Created         16m                    kubelet            Created container mount-bpffs
  Normal   Started         16m                    kubelet            Started container mount-bpffs
  Normal   Pulled          16m                    kubelet            Container image "docker.io/calico/node:v3.25.0" already present on machine
  Normal   Created         16m                    kubelet            Created container calico-node
  Normal   Started         16m                    kubelet            Started container calico-node
  Warning  Unhealthy       16m (x2 over 16m)      kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/bird/bird.ctl: connect: no such file or directory
  Warning  Unhealthy       16m                    kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  Normal   Killing         10m                    kubelet            Stopping container calico-node
  Normal   SandboxChanged  9m6s                   kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          9m6s                   kubelet            Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal   Created         9m6s                   kubelet            Created container upgrade-ipam
  Normal   Started         9m6s                   kubelet            Started container upgrade-ipam
  Normal   Pulled          8m34s (x2 over 9m5s)   kubelet            Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal   Created         8m34s (x2 over 9m5s)   kubelet            Created container install-cni
  Normal   Started         8m34s (x2 over 9m5s)   kubelet            Started container install-cni
  Normal   Pulled          8m33s                  kubelet            Container image "docker.io/calico/node:v3.25.0" already present on machine
  Normal   Created         8m33s                  kubelet            Created container mount-bpffs
  Normal   Started         8m33s                  kubelet            Started container mount-bpffs
  Normal   Pulled          8m32s                  kubelet            Container image "docker.io/calico/node:v3.25.0" already present on machine
  Normal   Created         8m32s                  kubelet            Created container calico-node
  Normal   Started         8m32s                  kubelet            Started container calico-node
  Warning  Unhealthy       8m30s (x2 over 8m31s)  kubelet            Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
  Warning  Unhealthy       8m26s                  kubelet            Readiness probe failed: 2023-03-30 17:55:32.710 [INFO][227] confd/health.go 180: Number of node(s) with BGP peering established = 3
calico/node is not ready: BIRD is not ready: BGP not established with 172.20.0.2
  Warning  Unhealthy  8m16s  kubelet  Readiness probe failed: 2023-03-30 17:55:42.727 [INFO][249] confd/health.go 180: Number of node(s) with BGP peering established = 3
calico/node is not ready: BIRD is not ready: BGP not established with 172.20.0.2
  Normal  Killing         7m34s  kubelet  Stopping container calico-node
  Normal  SandboxChanged  7m8s   kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled          7m8s   kubelet  Container image "docker.io/calico/cni:v3.25.0" already present on machine
  Normal  Created         7m8s   kubelet  Created container upgrade-ipam
  Normal  Started         7m8s   kubelet  Started container upgrade-ipam
```

```
$ kubectl describe ds -n kube-system calico-node
Name:           calico-node
Selector:       k8s-app=calico-node
Node-Selector:  kubernetes.io/os=linux
Labels:         k8s-app=calico-node
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 5
Current Number of Nodes Scheduled: 5
Number of Nodes Scheduled with Up-to-date Pods: 5
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 2 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=calico-node
  Service Account:  calico-node
  Init Containers:
   upgrade-ipam:
    Image:      docker.io/calico/cni:v3.25.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /opt/cni/bin/calico-ipam
      -upgrade
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      KUBERNETES_NODE_NAME:        (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:  <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
    Mounts:
      /host/opt/cni/bin from cni-bin-dir (rw)
      /var/lib/cni/networks from host-local-net-dir (rw)
   install-cni:
    Image:      docker.io/calico/cni:v3.25.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /opt/cni/bin/install
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      CNI_CONF_NAME:         10-calico.conflist
      CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'calico-config'>  Optional: false
      KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
      CNI_MTU:               <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      SLEEP:                 false
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /host/opt/cni/bin from cni-bin-dir (rw)
   mount-bpffs:
    Image:      docker.io/calico/node:v3.25.0
    Port:       <none>
    Host Port:  <none>
    Command:
      calico-node
      -init
      -best-effort
    Environment:  <none>
    Mounts:
      /nodeproc from nodeproc (ro)
      /sys/fs from sys-fs (rw)
      /var/run/calico from var-run-calico (rw)
  Containers:
   calico-node:
    Image:      docker.io/calico/node:v3.25.0
    Port:       <none>
    Host Port:  <none>
    Requests:
      cpu:      250m
    Liveness:   exec [/bin/calico-node -felix-live -bird-live] delay=10s timeout=10s period=10s #success=1 #failure=6
    Readiness:  exec [/bin/calico-node -felix-ready -bird-ready] delay=0s timeout=10s period=10s #success=1 #failure=3
    Environment Variables from:
      kubernetes-services-endpoint  ConfigMap  Optional: true
    Environment:
      DATASTORE_TYPE:                     kubernetes
      WAIT_FOR_DATASTORE:                 true
      NODENAME:                            (v1:spec.nodeName)
      CALICO_NETWORKING_BACKEND:          <set to the key 'calico_backend' of config map 'calico-config'>  Optional: false
      CLUSTER_TYPE:                       k8s,bgp
      IP:                                 autodetect
      CALICO_IPV4POOL_IPIP:               Always
      CALICO_IPV4POOL_VXLAN:              Never
      CALICO_IPV6POOL_VXLAN:              Never
      FELIX_IPINIPMTU:                    <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_VXLANMTU:                     <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      FELIX_WIREGUARDMTU:                 <set to the key 'veth_mtu' of config map 'calico-config'>  Optional: false
      CALICO_DISABLE_FILE_LOGGING:        true
      FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
      FELIX_IPV6SUPPORT:                  false
      FELIX_HEALTHENABLED:                true
    Mounts:
      /host/etc/cni/net.d from cni-net-dir (rw)
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /sys/fs/bpf from bpffs (rw)
      /var/lib/calico from var-lib-calico (rw)
      /var/log/calico/cni from cni-log-dir (ro)
      /var/run/calico from var-run-calico (rw)
      /var/run/nodeagent from policysync (rw)
  Volumes:
   lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
   var-run-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/calico
    HostPathType:  
   var-lib-calico:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/calico
    HostPathType:  
   xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
   sys-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/
    HostPathType:  DirectoryOrCreate
   bpffs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
   nodeproc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
   cni-bin-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/cni/bin
    HostPathType:  
   cni-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/cni/net.d
    HostPathType:  
   cni-log-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log/calico/cni
    HostPathType:  
   host-local-net-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/cni/networks
    HostPathType:  
   policysync:
    Type:               HostPath (bare host directory volume)
    Path:               /var/run/nodeagent
    HostPathType:       DirectoryOrCreate
  Priority Class Name:  system-node-critical
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  49m   daemonset-controller  Created pod: calico-node-pngj7
  Normal  SuccessfulCreate  49m   daemonset-controller  Created pod: calico-node-kf69z
  Normal  SuccessfulCreate  49m   daemonset-controller  Created pod: calico-node-lpkxj
  Normal  SuccessfulCreate  49m   daemonset-controller  Created pod: calico-node-hm7pf
  Normal  SuccessfulCreate  49m   daemonset-controller  Created pod: calico-node-hvws2
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-rc.0", GitCommit:"cf60ee25590ac79334f823b7f03cf33105a442c1", GitTreeState:"clean", BuildDate:"2023-03-23T18:59:06Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

Talos Linux 1.4.0-alpha.3

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.25.0, also reproducible with 3.24.1
</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind regression

#### Which issue(s) this PR fixes:

Fixes #117018

#### Special notes for your reviewer:

It is a fix for the issue introduced in https://github.com/kubernetes/kubernetes/pull/115331

#### Does this PR introduce a user-facing change?

```release-note
Fix 1.27 regression recreating DaemonSet pods completed with Succeeded phase
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mimowo** [comment]
/sig apps
FYI @alculquicondor 

Adding an integration test for DaemonSet to confirm that Succeeded pods are not restarted. Notably, the test for the Failed pod passes, so failed pods are restared. Not sure why the discrapancy exists, seems like a bug. Will look deeper tomorrow.

File: test/integration/daemonset/daemonset_test.go [hunk 1]
```diff
@@ -498,6 +499,54 @@ func TestSimpleDaemonSetLaunchesPods(t *testing.T) {
...
+					t.Fatalf("Failed to create DaemonSet: %v", err)
+				}
+				defer cleanupDaemonSets(t, clientset, ds)
+
+				addNodes(nodeClient, 0, 1, nil, t)
+
+				validateDaemonSetPodsAndMarkReady(podClient, podInformer, 1, t)
+				validateDaemonSetStatus(dsClient, ds.Name, 1, t)
+				podsListBefore := podInformer.GetIndexer().List()
+				pod0Before := podsListBefore[0].(*v1.Pod)
```
Comment (soltysh) [inline test/integration/daemonset/daemonset_test.go]: You'll need to `podsListBefore[0].(*v1.Pod).DeepCopy()` the pod, otherwise the mutation detector will complain that the pod in cache has been modified. 

But the test is very good proof, I'm happy it worked this well :)

Comment (soltysh) [reply test/integration/daemonset/daemonset_test.go]: This is the root cause of the ingration failure on this PR.

**Review by soltysh — APPROVED** [review]
This looks good to me, but I'd like @smarterclayton to double check me, I looked in the history and couldn't find any documents about inner-workings of daemonset controller, so I'd fallback to wiser man to double check me :sweat_smile:

**Comment by soltysh** [comment]
/hold
so we don't accidentally merge this before getting additional opinion

File: test/integration/daemonset/daemonset_test.go (hunk 1 above)
Comment (mimowo) [reply test/integration/daemonset/daemonset_test.go]: Thanks for pointing this out, fixed now.

**Comment by smira** [comment]
This should be backported to `release-1.27` please, thank you @mimowo for a quick fix!

**Comment by mimowo** [comment]
> This should be backported to `release-1.27` please, thank you @mimowo for a quick fix!

@smira are you in a good position to build the branch and test on your setup?

**Comment by smira** [comment]
> > This should be backported to `release-1.27` please, thank you @mimowo for a quick fix!
> 
> @smira are you in a good position to build the branch images and test on your setup?

yes, sure, I can try this PR.

File: pkg/controller/daemon/daemon_controller.go [hunk 2]
```diff
@@ -813,34 +811,34 @@ func (dsc *DaemonSetsController) podsShouldBeOnNode(
...
+		// If a daemon pod terminal, delete it
 		// If there's non-daemon pods left on this node, we will create it in the next sync loop
 		var daemonPodsRunning []*v1.Pod
 		for _, pod := range daemonPods {
 			if pod.DeletionTimestamp != nil {
 				continue
 			}
-			if pod.Status.Phase == v1.PodFailed {
+			if podutil.IsPodPhaseTerminal(pod.Status.Phase) {
 				// This is a critical place where DS is often fighting with kubelet that rejects pods.
```
Comment (alculquicondor) [inline pkg/controller/daemon/daemon_controller.go:822]: Adding Failed pods to backoff makes sense. However, Succeeded pods should be replaced immediately without backoff

Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go:822]: I would add a specific block for `pod.Status.Phase == v1.PodSucceeded`

**Comment by smira** [comment]
> > @smira are you in a good position to build the branch images and test on your setup?

@mimowo   verified with base as v1.27.0.rc-0, `kube-controller-manager` replaced with `v1.28.0-alpha.0.16_e1eab2905bba5a` - the issue is resolved, `Completed` daemonset pods are immediately replaced.

File: pkg/controller/daemon/daemon_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go]: Done, PTAL

File: pkg/controller/daemon/daemon_controller.go [hunk 3]
```diff
@@ -842,6 +844,12 @@ func (dsc *DaemonSetsController) podsShouldBeOnNode(
 				// Emit an event so that it's discoverable to users.
 				dsc.eventRecorder.Eventf(ds, v1.EventTypeWarning, FailedDaemonPodReason, msg)
 				podsToDelete = append(podsToDelete, pod.Name)
+			} else if pod.Status.Phase == v1.PodSucceeded {
+				msg := fmt.Sprintf("Found succeeded daemon pod %s/%s on node %s, will try to delete it", pod.Namespace, pod.Name, node.Name)
+				logger.V(2).Info("Found succeeded daemon pod on node, will try to delete it", "pod", klog.KObj(pod), "node", klog.KObj(node))
+				// Emit an event so that it's discoverable to users.
+				dsc.eventRecorder.Eventf(ds, v1.EventTypeWarning, SucceededDaemonPodReason, msg)
```
Comment (smarterclayton) [inline pkg/controller/daemon/daemon_controller.go:851]: Rationale for the warning?  If every drain can generate this, and drain is “normal”, is it a warning?

Just want to understand the pattern we’re following here.

File: test/integration/daemonset/daemonset_test.go [hunk 4]
```diff
@@ -498,6 +533,50 @@ func TestSimpleDaemonSetLaunchesPods(t *testing.T) {
 	})
 }
 
+func TestSimpleDaemonSetRestartsPods(t *testing.T) {
```
Comment (smarterclayton) [inline test/integration/daemonset/daemonset_test.go:536]: it would be nice to have an e2e that sets the pod phase to succeeded and verify the daemonset controller recreates it.

File: pkg/controller/daemon/daemon_controller.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go:851]: yes, warning is too strong. I just followed the pattern for Failed pod. For now, I'm keeping the warning level for handling of Failed pods.

File: pkg/controller/daemon/daemon_controller.go (hunk 2 above)
Comment (smarterclayton) [reply pkg/controller/daemon/daemon_controller.go]: Hrm, can this be abused?  Is there some per DS rate limit in play here?

**Comment by smarterclayton** [comment]
@mimowo i suggest we revise the release note for the pod status change to call out that some RunAlways pods can be Succeeded now - in the following cases (node graceful shutdown)

File: pkg/controller/daemon/daemon_controller.go [hunk 5]
```diff
@@ -842,6 +844,12 @@ func (dsc *DaemonSetsController) podsShouldBeOnNode(
 				// Emit an event so that it's discoverable to users.
 				dsc.eventRecorder.Eventf(ds, v1.EventTypeWarning, FailedDaemonPodReason, msg)
 				podsToDelete = append(podsToDelete, pod.Name)
+			} else if pod.Status.Phase == v1.PodSucceeded {
+				msg := fmt.Sprintf("Found succeeded daemon pod %s/%s on node %s, will try to delete it", pod.Namespace, pod.Name, node.Name)
```
Comment (alculquicondor) [inline pkg/controller/daemon/daemon_controller.go:848]: I presume these pods might not have a DeletionTimestamp, otherwise this applies https://github.com/kubernetes/kubernetes/issues/116925#issuecomment-1495498973

cc @bobbypage

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (alculquicondor) [reply test/integration/daemonset/daemonset_test.go:536]: this is already an integration test. I don't think an E2E environment would change much.

File: test/integration/daemonset/daemonset_test.go [hunk 6]
```diff
@@ -312,6 +312,41 @@ func validateDaemonSetPodsAndMarkReady(
...
 
+func validateDaemonSetPodsActive(
+	podClient corev1client.PodInterface,
+	podInformer cache.SharedIndexInformer,
+	numberPods int,
+	t *testing.T,
+) {
+	if err := wait.Poll(time.Second, 60*time.Second, func() (bool, error) {
+		objects := podInformer.GetIndexer().List()
+		if len(objects) != numberPods {
```
Comment (alculquicondor) [inline test/integration/daemonset/daemonset_test.go:323]:
```suggestion
		if len(objects) < numberPods {
```

maybe there coudl be other pods?

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (alculquicondor) [inline test/integration/daemonset/daemonset_test.go:536]:
```suggestion
func TestSimpleDaemonSetRestartsPodsOnTerminalPhase(t *testing.T) {
```

File: test/integration/daemonset/daemonset_test.go [hunk 7]
```diff
@@ -498,6 +533,50 @@ func TestSimpleDaemonSetLaunchesPods(t *testing.T) {
 	})
 }
 
+func TestSimpleDaemonSetRestartsPods(t *testing.T) {
+	for _, podPhase := range []v1.PodPhase{v1.PodSucceeded, v1.PodFailed} {
+		t.Run(fmt.Sprintf("%s_%v", t.Name(), podPhase), func(tt *testing.T) {
```
Comment (alculquicondor) [inline test/integration/daemonset/daemonset_test.go:538]: `t.Name()` is already added by the test framework

```suggestion
		t.Run(podPhase, func(tt *testing.T) {
```

File: pkg/controller/daemon/daemon_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go]: I don't see any other rate limiting in the DSC, but also not sure how to exploit it for now. Anyway, it might be safer to reuse the same queue for backoff for Succeeded pods. WDYT?

File: pkg/controller/daemon/daemon_controller.go (hunk 5 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go:848]: Yes, I shown in here: https://github.com/kubernetes/kubernetes/issues/117018, under Details in the "Additional detailed output:" section. The Succeeded pods don't have deletionTimestamp.

Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go:848]: Yes, I shown in here: https://github.com/kubernetes/kubernetes/issues/117018, under Details in the "Additional detailed output:" section. The Succeeded pods don't have deletionTimestamp.

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/daemonset/daemonset_test.go]: +1 I think the integration test already covers that indeed. 

There might be value added of e2e test, but when we perform an actual graceful node shutdown, rather than just setting the phase to Succeeded. WDYT?

File: pkg/controller/daemon/daemon_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go]: I don't think it can be abused, as Daemonsets can only be created with `restartPolicy: Always`.

File: pkg/controller/daemon/daemon_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go:851]: forgot to commit?

File: test/integration/daemonset/daemonset_test.go [hunk 8]
```diff
@@ -498,6 +533,50 @@ func TestSimpleDaemonSetLaunchesPods(t *testing.T) {
 	})
 }
 
+func TestSimpleDaemonSetRestartsPodsOnTerminalPhase(t *testing.T) {
+	for _, podPhase := range []v1.PodPhase{v1.PodSucceeded, v1.PodFailed} {
+		t.Run(podPhase, func(tt *testing.T) {
```
Comment (alculquicondor) [inline test/integration/daemonset/daemonset_test.go:538]:
```suggestion
		t.Run(string(podPhase), func(tt *testing.T) {
```

File: pkg/controller/daemon/daemon_controller.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go]: yes, got distructed. pushed now.

File: test/integration/daemonset/daemonset_test.go (hunk 8 above)
Comment (mimowo) [reply test/integration/daemonset/daemonset_test.go]: Done

File: pkg/controller/daemon/daemon_controller.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/daemon/daemon_controller.go]: Yes, so based on the comment the backoff is used to thottle DCS in case of admission failures: 
```
// This is a critical place where DS is often fighting with kubelet that rejects pods.
// We need to avoid hot looping and backoff.
```
since admission failures always end up in Failed phase it is not an argument for throttling Succeeded pods.

**Comment by mimowo** [comment]
> we need to be more emphatic. Add `ACTION REQUIRED` into the release note.
> 
> Rationale: if an in-tree controller such as Daemonset was buggy, imagine in the wild world of external controllers

Makes sense, updated. PTAL.

**Comment by mimowo** [comment]
/test pull-kubernetes-e2e-kind-ipv6
"OpenAPIV3 should contain OpenAPI V3 for Aggregated APIServer" failed - doesn't seem related

File: pkg/controller/daemon/daemon_controller.go (hunk 5 above)
Comment (bobbypage) [reply pkg/controller/daemon/daemon_controller.go:848]: Yes, graceful node shutdown will not set a deletion timestamp; it only marks the pods as terminal.

**Comment by xmudrii** [comment]
ACK-ing the PR, I pinged Release Team Leads on Slack as they're responsible for code freeze exceptions: https://kubernetes.slack.com/archives/C2C40FMNF/p1680636984022679

**Comment by xmudrii** [comment]
cc @kubernetes/release-team-leads

**Comment by cici37** [comment]
Looks like the issue was introduced in 1.27 and the fix is critical. Since rc.1 was delayed to Thursday, I am +1 to merge this one before v1,27,0-rc.1.

**Comment by bobbypage** [comment]
/lgtm

nit: I would retitle this and the release note to "Recreate DaemonSet pods completed with Succeeded phase" rather than restart (since it is a slightly more accurate).

**Comment by alculquicondor** [comment]
/retitle Fix: Recreate DaemonSet pods completed with Succeeded phase

/release-note-edit
```release-note
Recreate DaemonSet pods completed with Succeeded phase
```

**Comment by cici37** [comment]
Since this is considered a release blocker and introduced in 1.27, adding label to merge it before 1.27.0-rc1 cut.
/milestone v1.27

**Comment by alculquicondor** [comment]
/hold cancel

@soltysh already approved and my LGTM is under my SIG Apps reviewer hat

**Comment by liggitt** [comment]
since 1.26 daemonset controllers can run against 1.27 API servers with 1.27 kubelets, shouldn't this be backported to 1.26?

**Comment by mimowo** [comment]
I think we should indeed, based on https://kubernetes.io/releases/version-skew-policy/. I will open the cherry-pick PR

**Comment by mimowo** [comment]
Ready: https://github.com/kubernetes/kubernetes/pull/117496
