### PR TITLE
Change log line to print actual pod uid and not address of the pod uid

### LINKED ISSUE #102219: [kubelet] Log line does not properly print UID
#### What happened:

Consider the following log line:

```
May 20 22:57:18.999646 ci-op-y66rclst-3bd46-t7dw2-master-0 hyperkube[1554]: I0520 22:57:18.999559    1554 mirror_client.go:125] "Deleting a mirror pod" pod="openshift-kube-apiserver/kube-apiserver-ci-op-y66rclst-3bd46-t7dw2-master-0" podUID=0xc002c8ec60
```

#### What you expected to happen:

I expected the podUID to be printed rather than an address/pointer.

#### How to reproduce it (as minimally and precisely as possible):

Run a static pod on a non-standalone kubelet, watch logs for mirror_client entries.

#### Anything else we need to know?:

Fix is this line:

https://github.com/kubernetes/kubernetes/blob/661b76f8644b53a57da6d12e2add6613d81dfb3e/pkg/kubelet/pod/mirror_client.go#L125

We probably want to check if the UID is nil, and if so, print what it points to.

/sig node
/area logging
/help

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- Changes the log line:
https://github.com/kubernetes/kubernetes/blob/661b76f8644b53a57da6d12e2add6613d81dfb3e/pkg/kubelet/pod/mirror_client.go#L125
to print the actual UID of the pod rather than its address.

- Additionally fixes a small typo in a comment 

#### Which issue(s) this PR fixes:

Fixes #102219 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/pod/mirror_client.go [hunk 1]
```diff
@@ -122,7 +122,9 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string, uid *types.UID)
 		klog.ErrorS(err, "Failed to parse a pod full name", "podFullName", podFullName)
 		return false, err
 	}
-	klog.V(2).InfoS("Deleting a mirror pod", "pod", klog.KRef(namespace, name), "podUID", uid)
+	if uid != nil {
+		klog.V(2).InfoS("Deleting a mirror pod", "pod", klog.KRef(namespace, name), "podUID", *uid)
+	}
```
Comment (ehashman) [inline pkg/kubelet/pod/mirror_client.go:127]: I think this should still log in the case that the UID isn't set. Rather than logging conditionally, can we format the uid pointer into a string for printing?

**Review by ehashman — CHANGES_REQUESTED** [review]
/triage accepted

File: pkg/kubelet/pod/mirror_client.go (hunk 1 above)
Comment (MadhavJivrajani) [reply pkg/kubelet/pod/mirror_client.go:127]: Sure! That makes more sense 😄 
For the cases of `uid` being `nil`, would you prefer it displaying `nil` or something like `NA`?

Comment (adisky) [reply pkg/kubelet/pod/mirror_client.go:127]: @MadhavJivrajani I think it should be like this, the underlying value for uid is string, so we should print '''?
```
uidValue := ""
if uid != nil {
  uidValue  = *uid
}
klog.V(2).InfoS("Deleting a mirror pod", "pod", klog.KRef(namespace, name), "podUID", uidValue)
```

Comment (MadhavJivrajani) [reply pkg/kubelet/pod/mirror_client.go:127]: That makes sense, thank you! 😄 
I will make the change

File: pkg/kubelet/pod/mirror_client.go [hunk 2]
```diff
@@ -117,12 +117,19 @@ func (mc *basicMirrorClient) DeleteMirrorPod(podFullName string, uid *types.UID)
 	if mc.apiserverClient == nil {
 		return false, nil
 	}
+
```
Comment (adisky) [inline pkg/kubelet/pod/mirror_client.go:120]: nit
```suggestion

```

**Review by adisky — COMMENTED** [review]
/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]
