### PR TITLE
protobuf generation modifies types.go, which needs to be copied out

### LINKED ISSUE #35486: hack/verify-generated-protobuf.sh is not working in the build guards
I checked out master and ran hack/update-generate-protobuf-dockerized.sh and changes from https://github.com/kubernetes/kubernetes/pull/33905 were assigned tags.

### PR DESCRIPTION
**Pull request by smarterclayton**
This was broken when we moved to the build container, but no one
noticed. Made it so that we get a test error if a field in a registered type has a json tag with no protobuf tag.

Fixes #35486

### CODE REVIEW

**Comment by smarterclayton** [comment]
Set to 1.6 because this prevents accidental breaking API changes from being delivered (protobuf without a field tag can't be safely round tripped to etcd)

File: build/common.sh [hunk 1]
```diff
@@ -704,6 +704,7 @@ function kube::build::copy_output() {
     --filter='+ zz_generated.*' \
     --filter='+ generated.proto' \
     --filter='+ *.pb.go' \
+    --filter='+ types.go' \
```
Comment (thockin) [inline build/common.sh]: Have I ever told you the story about how I hate this rsync stuff, and MacOS users should suck it up and get a real OS for building?

Comment (smarterclayton) [inline build/common.sh]: Have I every told you how people got my hopes up about how awesome bazel was, and then I found out it only worked on Linux?

Is the distributed/cached stuff for that ready yet?

**Comment by thockin** [comment]
touche!  But that was @mikedanese, I think :)

File: build/common.sh (hunk 1 above)
Comment (ixdy) [inline build/common.sh]: 🔥🔥🔥

**Review by ixdy — APPROVED** [review]
cc @jbeda
