### PR TITLE
Make pod eviction trigger graceful deletion to match deletion via API

### LINKED ISSUE #72717: Eviction API ignoring preStop hook and terminationGracePeriodSeconds when DeleteOptions are not present
**What happened**:
When using the `create_namespaced_pod_eviction` function from Python's Kuberneets API, we noticed that Pods are terminated bythe cluster without respecting their preStop hooks or terminationGracePeriodSeconds seconds.

**What you expected to happen**:
When using the eviction API, just as when using delete, Pods should be allowed to run their preStop hooks, as well as be given terminationGracePeriodSeconds before being terminated with SIGKILL.

**How to reproduce it (as minimally and precisely as possible)**:

1. Apply the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: killme
  labels:
    app: test-termination-pod
spec:
  terminationGracePeriodSeconds: 15
  containers:
  - command: ["python"]
    args:
      - -u
      - -c
      - |
        import signal,time
        MSG = "boring sleep"
        def got_sig(signum,frame):
          global MSG
          print ("Got signal %s" % signum)
          MSG="After signal %s" % signum
        hndl=signal.signal(signal.SIGTERM, got_sig)
        while True:
          print(time.asctime(),MSG)
          time.sleep(5)
    image: python:3
    name: sleeper
    lifecycle:
      preStop:
        exec:
          command: ["/bin/bash", "-c", "sleep 10"]
```

2. Tail the pod logs in another window
3. Attempt to evict the pod.
   Here is a sample curl equivalent of what `kubectl drain` (1.13) is doing - happy path:
`curl -k -v -XPOST  -H "Accept: application/json, */*" -H "Content-Type: application/json" -H "Authorization: Basic <YOUR BASE64 AUTH TOKEN> 'https://<KUBE API HOSTNAME>/api/v1/namespaces/default/pods/killme/eviction' --data '{"kind":"Eviction","apiVersion":"policy/v1beta1","metadata": {"namespace": "default","name": "killme"},"deleteOptions":{}}'`

  Here is a sample curl equivalent of what Python's `create_namespaced_pod_eviction` is doing (when not passed `V1DeleteOptions`) - broken path:
`curl -k -v -XPOST  -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Basic <YOUR BASE64 AUTH TOKEN>" 'https://<KUBE API HOSTNAME>/api/v1/namespaces/default/pods/killme/eviction' --data '{"kind":"Eviction","apiVersion":"policy/v1beta1","metadata": {"namespace": "default","name": "killme"}}'`

The log output generated by the guinea pod on the happy path looks like this:
```
Wed Jan  9 10:59:12 2019 boring sleep
Wed Jan  9 10:59:17 2019 boring sleep
Wed Jan  9 10:59:22 2019 boring sleep
Got signal 15
Wed Jan  9 10:59:27 2019 After signal 15
Wed Jan  9 10:59:32 2019 After signal 15
Wed Jan  9 10:59:37 2019 After signal 15
rpc error: code = Unknown desc = Error: No such container:....
```
The "Got signal 15" message shows up only after the preStop hook is finished, so ~10 seconds after the evict call is made

What happens on the broken path is:
```
Wed Jan  9 10:58:26 2019 boring sleep
Wed Jan  9 10:58:31 2019 boring sleep
Wed Jan  9 10:58:36 2019 boring sleep
Got signal 15                      
Got signal 15
```
We seem to be getting 2x SIGTERM, there are no messages indicating continued processing after the signal, and the signal itself is registered *immediately* after the eviction call is made, suggesting that preStop didn't run.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: in-house
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Makes pod eviction with no DeleteOptions match direct pod deletion with no DeleteOptions w.r.t. graceful deletion behavior

**Which issue(s) this PR fixes**:
Fixes #72717

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Pod eviction now honors graceful deletion by default if no delete options are provided in the eviction request
```

/sig apps

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-apps-pr-reviews @kubernetes/sig-scheduling-pr-reviews

File: pkg/registry/core/pod/storage/eviction.go [hunk 1]
```diff
@@ -138,7 +138,12 @@ func (r *EvictionREST) Create(ctx context.Context, obj runtime.Object, createVal
 	// At this point there was either no PDB or we succeeded in decrementing
 
 	// Try the delete
-	_, _, err = r.store.Delete(ctx, eviction.Name, eviction.DeleteOptions)
+	deletionOptions := eviction.DeleteOptions
+	if deletionOptions == nil {
+		// default to non-nil to trigger graceful deletion
+		deletionOptions = &metav1.DeleteOptions{}
```
Comment (k82cn) [inline pkg/registry/core/pod/storage/eviction.go]: if deletionOpt is nil, we're going to use default grace period?

Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go]: eviction without delete options would behave like delete without delete options

This is a behavior change. We need to decide if eviction (which is intended to allow safe deletion of pods according to pod disruption budget) essentially force deleting pods by default is a problem worth fixing. 

Notably, kubectl drain never passes nil delete options, which is good. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/drain/drain.go#L526)

**Comment by liggitt** [comment]
cc @kubernetes/api-reviewers

File: pkg/registry/core/pod/storage/eviction.go (hunk 1 above)
Comment (k82cn) [reply pkg/registry/core/pod/storage/eviction.go]: > This is a behavior change.

Yes; but it seems a "correction" instead of "change" considering "delete without options" :)

Comment (liggitt) [reply pkg/registry/core/pod/storage/eviction.go]: > Yes; but it seems a "correction" instead of "change" considering "delete without options" :)

I don't disagree, but would like an ack from @kubernetes/api-approvers

**Comment by liggitt** [comment]
/assign @thockin 

what's your take on changing pod eviction to behave like pod deletion w.r.t. honoring graceful deletion by default? currently if you submit a pod eviction without delete options, it force deletes the pod, which seems at odds with the intent of pod eviction as a safe way to remove pods

File: pkg/registry/core/pod/storage/eviction.go (hunk 1 above)
Comment (thockin) [reply pkg/registry/core/pod/storage/eviction.go]: I agree.

**Comment by thockin** [comment]
Do we have no test coverage for this?

**Comment by liggitt** [comment]
> Do we have no test coverage for this?

only incidentally as part of the node authorizer integration test, apparently.

`kubectl drain` always passed delete options, so this change did not affect it either way.

added unit test coverage

**Review by thockin — COMMENTED** [review]
/lgtm
/approve
