### PR TITLE
DRA: work around fake.ClientSet informer deficiency in unit test

### LINKED ISSUE #131320: Failure cluster [f460a369...]
##### Error text:
```
Failed
=== RUN   TestEviction/add
=== PAUSE TestEviction/add
=== CONT  TestEviction/add
        	null
         > newClaim=<
        	{
        	  "metadata": {
        	    "name": "my-pod-my-resource",
        	    "namespace": "default",
        	    "creationTimestamp": null,
        	    "ownerReferences": [
        	      {
        	        "apiVersion": "v1",
        	        "kind": "Pod",
        	        "name": "my-pod",
        	        "uid": "1234",
        	        "controller": true
        	      }
        	    ],
        	    "finalizers": [
        	      "resource.kubernetes.io/delete-protection"
        	    ]
        	  },
        	  "spec": {
        	    "devices": {
        	      "requests": [
        	        {
        	          "name": "req-1",
        	          "deviceClassName": "my-resource-class",
        	          "allocationMode": "ExactCount",
        	          "count": 1
        	        }
        	      ]
        	    }
        	  },
        	  "status": {
        	    "allocation": {
        	      "devices": {
        	        "results": [
        	          {
        	            "request": "req-1",
        	            "driver": "some-driver",
        	            "pool": "worker",
        	            "device": "instance",
        	            "adminAccess": null
        	          }
        	        ]
        	      }
        	    },
        	    "reservedFor": [
        	      {
        	        "resource": "pods",
        	     
```
#### Recent failures:
[4/11/2025, 8:42:08 PM ci-kubernetes-unit-ppc64le](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-ppc64le/1910765164047634432)
[4/10/2025, 5:07:21 PM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1910348666330157056)

/kind failing-test
/kind flake
/wg device-management
/sig scheduling
/assign

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

fake.Clientset suffers from a race condition related to informers:
it does not implement resource version support in its Watch
implementation and instead assumes that watches are set up
before further changes are made.
    
If a test waits for caches to be synced and then immediately
adds an object, that new object will never be seen by event handlers
if the race goes wrong and the Watch call hadn't completed yet
(can be triggered by adding a sleep before https://github.com/kubernetes/kubernetes/blob/b53b9fb5573323484af9a19cf3f5bfe80760abba/staging/src/k8s.io/client-go/tools/cache/reflector.go#L431).
    
To work around this, we count all watches and only proceed when
all of them are in place. This replaces the normal watch reactor
(https://github.com/kubernetes/kubernetes/blob/b53b9fb5573323484af9a19cf3f5bfe80760abba/staging/src/k8s.io/client-go/kubernetes/fake/clientset_generated.go#L161-L173).

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/131320

#### Special notes for your reviewer:

Discussed in https://kubernetes.slack.com/archives/C0EG7JC6T/p1744790432374839

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/assign @sttts

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Comment by pohly** [comment]
1h40m55s: 21132 runs so far, 0 failures

File: pkg/controller/devicetainteviction/device_taint_eviction_test.go [hunk 1]
```diff
@@ -1190,7 +1192,38 @@ func applyEventPair(tContext *testContext, event any) {
...
+func newTestController(tCtx ktesting.TContext, clientSet *fake.Clientset) *Controller {
+	// fake.Clientset suffers from a race condition related to informers:
+	// it does not implement resource version support in its Watch
+	// implementation and instead assumes that watches are set up
+	// before further changes are made.
+	//
+	// If a test waits for caches to be synced and then immediately
+	// adds an object, that new object will never be seen by event handlers
+	// if the race goes wrong and the Watch call hadn't completed yet
+	// (can be triggered by adding a sleep before https://github.com/kubernetes/kubernetes/blob/b53b9fb5573323484af9a19cf3f5bfe80760abba/staging/src/k8s.io/client-go/tools/cache/reflector.go#L431).
```
Comment (haosdent) [inline pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: Should we fix it in client-go as well

Comment (pohly) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: The fix in the fake package is likely to be complicated. Someone would have to implement proper resource version support for List and Watch. This is a nice research project, but IMHO not a high priority.

Comment (haosdent) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: Got it.

Comment (haosdent) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: I agree we should work around and fix this flaky test first.
In the meantime, just try to understand the root cause and create a pr at https://github.com/kubernetes/kubernetes/pull/131368/files#diff-b3ac8d4132005e736f9143b9140c44e789071d3ac5e8c89254e78a09391b57cfR170-R210 , do you think would it work

Comment (pohly) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: No, I don't think that solves the problem.

Comment (haosdent) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go:1204]: Noted, have closed it.
