### PR TITLE
Invalid environment var names are reported and pod starts

### LINKED ISSUE #42583: EnvFrom semantics might be unexpected
TLDR: I have had this nagging feeling that the semantics of `EnvFrom` are wrong.  I think we should either change them to be what users would expect, *or* ensure that the semantics are fully represented in all user-facing doc.

**Is this a request for help?**

No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

EnvFrom

---

**Kubernetes version** (use `kubectl version`):

1.6 master

**Environment**:

All environments

**What happened**:

When using `EnvFrom` with a Secret or ConfigMap, if the resource contains any non-environment keys (dashes, etc), then my pod does not start.

**What you expected to happen**:

I expect to only get keys that are legal environment variables from a resource I use with this feature and for it not to affect whether my pod starts.  You should get an event on the pod saying that X or Y keys were omitted because they are not valid environment variables.

**How to reproduce it** (as minimally and precisely as possible):

Make a secret or configmap with 2 environment-variable-compatible keys and 1 non-compatible key.  Depend on it in a pod using `EnvFrom`.  The pod won't start.

**Anything else we need to know**:

This behavior re: keys that are not valid environment variable names is documented in the `types.go` files but not the Kubernetes web documentation: https://github.com/kubernetes/kubernetes.github.io/pull/1967

### PR DESCRIPTION
**Pull request by fraenkel**
When processing EnvFrom items, all invalid keys are collected and
reported as a single event.

The Pod is allowed to start.

fixes #42583

### CODE REVIEW

**Comment by fraenkel** [comment]
@pmorie Here is the code... docs are coming next.

**Comment by fraenkel** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Comment by pmorie** [comment]
@fraenkel we should update the docs for this too.

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -431,15 +431,21 @@ func (kl *Kubelet) makeEnvironmentVariables(pod *v1.Pod, container *v1.Container
...
 				if errMsgs := utilvalidation.IsCIdentifier(k); len(errMsgs) != 0 {
-					return result, fmt.Errorf("Invalid environment variable name, %v, from configmap %v/%v: %s", k, pod.Namespace, name, errMsgs[0])
+					invalidKeys = append(invalidKeys, k)
+					continue
 				}
 				tmpEnv[k] = v
 			}
+			if len(invalidKeys) > 0 {
+				sort.Strings(invalidKeys)
+				kl.recorder.Eventf(pod, v1.EventTypeWarning, "Invalid environment variable names", "configmap %v/%v, keys: %s", pod.Namespace, name, strings.Join(invalidKeys, ", "))
```
Comment (pmorie) [inline pkg/kubelet/kubelet_pods.go]: I would further qualify the message on this event like:

"Keys with invalid environment variable names were skipped when creating environment variables from an EnvFrom"

**Review by pmorie — COMMENTED** [review]
One nit; LGTM otherwise.  Thanks for fixing this, @fraenkel

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (fraenkel) [inline pkg/kubelet/kubelet_pods.go]: Is there a pattern to the reason? Should it be InvalidEnvironmentVariableNames so that it is easily searchable?  The rest I can fix.

**Comment by fraenkel** [comment]
docs will be a separate PR although you are right, I need to also fix types.go. Forgot that it lives here.

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (fraenkel) [inline pkg/kubelet/kubelet_pods.go]: What I have now is
```
Warning InvalidEnvironmentVariableNames Keys [1234, 1z] from the EnvFrom configMap test/test-config-map were skipped since they are considered invalid environment variable names.
```

**Comment by fraenkel** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by derekwaynecarr** [comment]
since this touches /api you need more approval than i can give.

**Comment by fraenkel** [comment]
@k8s-bot bazel test this #40295
