### PR TITLE
Explicit namespace from kubeconfig should override in-cluster config

### LINKED ISSUE #43662: In-cluster config for kubectl cannot be disabled/overriden
I have an app running in a pod that shells out to kubectl. A kubeconfig file with credentials for four different clusters is included in the pod. However, kubectl always detects that it's being run from inside a cluster and uses the pod's cluster's apiserver instead of the credentials I'm explicitly passing it. I've tried various things to disable this detection and make it use the configuration I'm supplying, but it always uses the in-cluster configuration settings, which results in not only submitting to the wrong cluster, but this error being returned for many resources being applied:

```
the namespace from the provided object "foo" does not match the namespace "bar". You must pass '--namespace=foo' to perform this operation.
```

where "foo" refers to the resource I'm trying to create with `kubectl apply` (the namespace of the resource is in the input file) and "bar" is the namespace of the pod shelling out to kubectl. Running the exact same command locally works, because kubectl is not overriding what I pass it with in-cluster configuration.

Specifically, the command being run is:

```
kubectl --kubeconfig /path/to/.kube/config --context my-context apply -f resources.yml
```

I can't find any documentation on how to disable in-cluster config. I looked through the code of the Go client to try to figure out how it's choosing to do this. I tried various things to disable it, including:

* Setting the `KUBERNETES_SERVICE_HOST` environment variable to an empty string, due to this: https://github.com/kubernetes/client-go/blob/49948ae0ca8eb31d632fbf346e25ee0eb6762d5b/tools/clientcmd/client_config.go#L505. But Kubernetes overrides my setting and fills in the environment variable like normal.
* Mounting an empty volume to /var/run/secrets/kubernetes.io/serviceaccount to try to prevent Kubernetes from mounting the service account files, but it mounts them anyway, overriding my explicit mount.
* Setting the `KUBECONFIG` environment variable to the path of the file I want it to use. It has no effect.

This is kubectl 1.5.x running in a Kubernetes 1.5 cluster. Notably, using kubectl 1.4.x does _not_ exhibit this behavior in the same Kubernetes 1.5 cluster. kubectl 1.4 works as expected.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #43662 

If an explicitly specified namespace is read from a kubeconfig file, we should not fall back to in-cluster config

```release-note
kubectl commands run inside a pod using a kubeconfig file now use the namespace specified in the kubeconfig file, instead of using the pod namespace. If no kubeconfig file is used, or the kubeconfig does not specify a namespace, the pod namespace is still used as a fallback.
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-pr-reviews

File: test/e2e/kubectl.go [hunk 1]
```diff
@@ -608,11 +608,40 @@ var _ = framework.KubeDescribe("Kubectl client", func() {
...
+    user: kubeconfig-user
+  name: kubeconfig-context
+current-context: kubeconfig-context
+users:
+- name: kubeconfig-user
+  user:
+    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
+`), os.FileMode(0755)))
+			framework.Logf("copying %s to the %s pod", iccOverride.Name(), simplePodName)
+			framework.RunKubectlOrDie("cp", iccOverride.Name(), ns+"/"+simplePodName+":/tmp/icc-override.kubeconfig")
```
Comment (ncdc) [inline test/e2e/kubectl.go]: I am not sure if this is a regression, but it appears you can't change the destination filename; i.e. `kubectl cp sourcefile pod:/tmp/destfile` will yield `/tmp/sourcefile` inside the container :-/ I discovered this a few days ago when testing something else.

Comment (ncdc) [inline test/e2e/kubectl.go]: Here's an example of what it's running:

```
Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://104.198.236.9 --kubeconfig=/workspace/.kube/config cp /tmp/icc-override.kubeconfig363380968 e2e-tests-kubectl-bp2b4/nginx:/tmp/icc-override.kubeconfig'
```

Comment (liggitt) [inline test/e2e/kubectl.go]: huh... that's super-annoying

Comment (liggitt) [inline test/e2e/kubectl.go]: @fraenkel, is this a known issue? ^

**Comment by fraenkel** [comment]
kubectl cp is really tar which makes anything difficult.  To really do cp
we would need a helper on the server side which we don't have.

**Comment by liggitt** [comment]
updated test to match kubeconfig filenames

**Comment by liggitt** [comment]
tests green, PTAL

File: staging/src/k8s.io/client-go/tools/clientcmd/merged_client_builder.go [hunk 2]
```diff
@@ -134,12 +135,26 @@ func (config *DeferredLoadingClientConfig) Namespace() (string, bool, error) {
...
+	}
+
+	if len(ns) > 0 {
+		// if we got a non-default namespace from the kubeconfig, use it
+		if ns != api.NamespaceDefault {
+			return ns, false, nil
+		}
+
+		// if we got a default namespace, determine whether it was explicit or implicit
+		if raw, err := mergedKubeConfig.RawConfig(); err == nil {
```
Comment (smarterclayton) [inline staging/src/k8s.io/client-go/tools/clientcmd/merged_client_builder.go]: When the Kubeconfig revolution comes, this method will be first up against the wall.  But the tests are convincing

**Review by smarterclayton — COMMENTED** [review]
Changes lgtm but want second eyes because this code always breaks

**Comment by deads2k** [comment]
lgtm
