### PR TITLE
let kubectl annotate use patch instead of replace

### LINKED ISSUE #15333: [RFC] improve `kubectl annotate` and `kubectl label` to increase success rate
`kubectl label` and `kubectl annotate` work in this pattern: first issuing a "GET" to the API server to retrieve the latest object, then adding the label/annotation to the object, and finally issuing an "PUT" with the modified object. The request will fail if the object stored in the server has been updated between the "GET" and "PUT", even if the update has no conflict with the label/annotate request. In such cases, instead of returning an error, `kubectl` should retry without disturbing the end user.

There are two ways to implement this:

1. retry in kubectl: simply retry the label/annotate process several times if the server rejected the request because the object has been updated. The only exception is when the `--resource-version` [precondition](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L52) is set, then kubectl shouldn't retry.

2. use the strategicMergePatch instead of calling Update at client-side. PATCH is more robust because PATCH does the "get, modify, update" in the server-side, so there is less chance to have a conflict, and PATCH will retry at the server-side (see #14758). We need to make some adaptions though:

* kubectl annotate/label has the `--overwrite` [flag](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L51), when it's false, kubectl should retrieve the latest object to confirm there is no existing annotation/label of the same key, and then proceed with issuing the patch.

* if the `--resource-version` [flag](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L52) is set, ~~we should fall back to the current behavior, because PATCH doesn't support the resource-version precondition.~~ [UPDATE:] we just need to specify the resourVersion in the patch, then it will be treated as a precondition by the UpdateResource() handler in the API server.

I plan to take the first approach as an immediate fix.

@JanetKuo @bgrant0607 @lavalamp

### PR DESCRIPTION
**Pull request by caesarxuchao**
Let `kubectl annotate` use patch instead of replace. This have two advantages:
1. It utilizes the retry implemented in the patchResource() in the REST handler for PATCH;
2. Furthermore, it's less likely to have conflicts. The PATCH handler is in the API server binary. It gets the object from the etcd, applies the patch, and then updates the resource. These are all local operations, so it's less likely to have conflicts compared to a PUT implementation, which has to fetch the object to the client , then adds the annotate and sends back to the server.

Partially fix #15333

@JanetKuo @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
@jlowdermilk PTAL.

**Comment by caesarxuchao** [comment]
@k8s-bot test this

File: pkg/kubectl/cmd/annotate.go [hunk 1]
```diff
@@ -167,26 +169,43 @@ func (o AnnotateOptions) Validate(args []string) error {
...
+		}
+		if err := o.updateAnnotations(obj); err != nil {
+			return err
+		}
+		newData, err := json.Marshal(obj)
+		if err != nil {
+			return err
 		}
-		return nil
+		patchBytes, err := strategicpatch.CreateStrategicMergePatch(oldData, newData, obj)
```
Comment (jlowdermilk) [inline pkg/kubectl/cmd/annotate.go]: Use the synonym `CreateTwoWayMergePatch`

**Comment by jlowdermilk** [comment]
lgtm

File: pkg/kubectl/cmd/annotate.go [hunk 2]
```diff
@@ -167,26 +169,43 @@ func (o AnnotateOptions) Validate(args []string) error {
...
+		}
+		if err := o.updateAnnotations(obj); err != nil {
+			return err
+		}
+		newData, err := json.Marshal(obj)
+		if err != nil {
+			return err
 		}
-		return nil
+		patchBytes, err := strategicpatch.CreateTwoWayMergePatch(oldData, newData, obj)
```
Comment (caesarxuchao) [inline pkg/kubectl/cmd/annotate.go]: @jlowdermilk, fixed. Thanks!

**Comment by caesarxuchao** [comment]
@k8s-oncall @bgrant0607 it seems the merge bot is not working. Shall I go ahead merging this one?

**Comment by bgrant0607** [comment]
@caesarxuchao Contact the build cop.

**Comment by caesarxuchao** [comment]
Thank you @piosz!
