### PR TITLE
Unregister csiplugin even if socket path is gone

### LINKED ISSUE #87282: kubelet can't unregister csiplugin after csiplugin pod is deleted from node
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR enhances bookkeeping for csiplugin registration so that the csiplugin can be un-registered without socket path being present.

**Which issue(s) this PR fixes**:
Fixes #87282

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -135,33 +141,51 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
-			return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+		var pair cache.HandlerWithName
+		var handler cache.PluginHandler
+		ok := false
+		if len(pathToHandlers) != 0 {
+			pair, ok = pathToHandlers[socketPath]
 		}
-		defer conn.Close()
+		if !ok {
+			client, conn, err := dial(socketPath, dialTimeoutDuration)
```
Comment (k2huang) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I don't understand why we need retain dial operation. Unregister operation is triggered by socket file deletion

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: With this PR, the dial is not needed - after the fix is verified.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -122,6 +125,9 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
 		if err := handler.RegisterPlugin(infoResp.Name, infoResp.Endpoint, infoResp.SupportedVersions); err != nil {
 			return og.notifyPlugin(client, false, fmt.Sprintf("RegisterPlugin error -- plugin registration failed with err: %v", err))
 		}
+		if len(pathToHandlers) != 0 {
```
Comment (k2huang) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Maybe I missed something, because I'm confused the purpose of condition:` len(pathToHandlers) != 0 `, and I can't see where it is filled, so I think  pathToHandlers map will be empty if the code goes here for the first time.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 1 above)
Comment (k2huang) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: And what the scenario will use this dail operation?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 2 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Take a look at line 70 in reconciler.go

Comment (k2huang) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Both pathToHandlers map empty<make(map[string]cache.HandlerWithName)> and nil are let the condition: `len(pathToHandlers) != 0` to `true`.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I read your comment more than once.
I don't think so - what you described was for len(pathToHandlers) == 0.

Comment (k2huang) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: sorry, typo, I have updated it. And I mean that the condition: `len(pathToHandlers) != 0` will let the first register plugin info can't add into pathToHandlers map because empty map (not nil) will also let  len(pathToHandlers) as 0

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 3]
```diff
@@ -75,6 +75,12 @@ type actualStateOfWorld struct {
 
 var _ ActualStateOfWorld = &actualStateOfWorld{}
 
+// HandlerWithName holds information for handler, infoResp.Name
```
Comment (mattjmcnaughton) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: Could you share more about the decision to introduce a new data structure? Out of curiosity, where there ways to accomplish the goal without introducing a new data structure?

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for tackling this @tedyu !

Could you please add a unit test in which we try and unregister a plugin for which the socket has already been deleted?

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 3 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: In order to perform unregistration, we need to retrieve plugin handler via socket path.
Existing data structure is keyed by infoResp.Type

Hence I introduced a new struct.

I am open to suggestion on alternate approach.

**Comment by tedyu** [comment]
I verified that the new unregistration code is exercised by reconciler_test

**Comment by davidz627** [comment]
> reconciler_test - Test_Run_Positive_RegisterThenUnregister

if this test passed before and passes now that gives us no information. Could you write a unit test that confirms the changed behavior? (it should fail if run against the code before your change)

**Comment by tedyu** [comment]
The test is modified by removing socketPath.
Without the fix, it would fail with:
```
E0211 11:14:03.102285   43108 goroutinemap.go:150] Operation for "/var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock" failed. No retries permitted until 2020-02-11 11:14:07.102272 -0800 PST m=+42.510158652 (durationBeforeRetry 4s). Error: "UnregisterPlugin error -- dial failed at socket /var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock, err: failed to dial socket /var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock, err: context deadline exceeded"
E0211 11:14:17.104610   43108 goroutinemap.go:150] Operation for "/var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock" failed. No retries permitted until 2020-02-11 11:14:25.10459 -0800 PST m=+60.511325508 (durationBeforeRetry 8s). Error: "UnregisterPlugin error -- dial failed at socket /var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock, err: failed to dial socket /var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock, err: context deadline exceeded"
--- FAIL: Test_Run_Positive_RegisterThenUnregister (61.01s)
    reconciler_test.go:103: Timed out waiting for plugin to be unregistered:
        /var/folders/54/gn127_2x6kxcvxqw34z83mg80000gp/T/reconciler_test741787315/plugin.sock.
```

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 4]
```diff
@@ -135,33 +141,49 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+			actualStateOfWorldUpdater.RemovePlugin(socketPath)
 
-		// We remove the plugin to the actual state of world cache before calling a plugin consumer's Unregister handle
-		// so that if we receive a register event during Register Plugin, we can process it as a Register call.
-		actualStateOfWorldUpdater.RemovePlugin(socketPath)
+			handler.DeRegisterPlugin(infoResp.Name)
+		} else {
+			// We remove the plugin to the actual state of world cache before calling a plugin consumer's Unregister handle
+			// so that if we receive a register event during Register Plugin, we can process it as a Register call.
+			actualStateOfWorldUpdater.RemovePlugin(socketPath)
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: can refactor this code to reduce duplication since its at the end of both `if` and `else` blocks. You can just drop the `else`

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 5]
```diff
@@ -135,33 +141,49 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
-		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+		var pair cache.HandlerWithName
+		var handler cache.PluginHandler
+		ok := false
+		if len(pathToHandlers) != 0 {
+			pair, ok = pathToHandlers[socketPath]
 		}
-		defer conn.Close()
+		if !ok {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: its not clear why we do all this logic if "not ok", what does "not ok" mean in this context, can this variable be more descriptive

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 4 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: The if block is no longer needed since socket path would be absent.

Comment (davidz627) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: looks like the logic changed entirely. Did we need to do that original `RemovePlugin` if `!handlerFound` or not?

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: In normal cases, handlerFound would be true.
The "unable to DeRegister" shouldn't happen.

I think RemovePlugin() should be paired with DeRegisterPlugin() call - otherwise the internal state would be inconsistent.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 6]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
...
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: what is an `infoResp.Name`? It's not clear from the local context what that is referring to. Could you augment the docstring to be more clear as to what this is actually storing. a "handler" and "infoResp" are very generic

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 7]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
-		}
-		defer conn.Close()
-
-		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
-		defer cancel()
-
-		infoResp, err := client.GetInfo(ctx, &registerapi.InfoRequest{})
-		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- failed to get plugin info using RPC GetInfo at socket %s, err: %v", socketPath, err)
+		var pair cache.HandlerWithName
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: what is this a `pair` of?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 8]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+		handlerFound := false
+		pathToHandlers.Lock()
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: why is it necessary to lock `pathToHandlers` when reading it here?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 9]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+		pathToHandlers.Unlock()
+
+		if handlerFound {
+			// We remove the plugin to the actual state of world cache before calling a plugin consumer's Unregister handle
+			// so that if we receive a register event during Register Plugin, we can process it as a Register call.
+			actualStateOfWorldUpdater.RemovePlugin(socketPath)
+
+			pair.Handler.DeRegisterPlugin(pair.Name)
+			pathToHandlers.Lock()
+			klog.Infof("DeRegisterPlugin called for %s on %v", pair.Name, pair.Handler)
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: reduce log level

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 10]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+		if len(pathToHandlers.Handlers) != 0 {
+			pair, handlerFound = pathToHandlers.Handlers[socketPath]
 		}
-
-		handler, ok := pluginHandlers[infoResp.Type]
-		if !ok {
-			return fmt.Errorf("UnregisterPlugin error -- no handler registered for plugin type: %s at socket %s", infoResp.Type, socketPath)
+		pathToHandlers.Unlock()
+
+		if handlerFound {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: nit: idiomatic go style we could do `if !handlerFound { error}` then the "happy logic" doesn't need to be nested

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 7 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Renamed the variable

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 8 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: The map within pathToHandlers would be concurrently accessed for different socket paths.
Without synchronization, you would see something such as:
```
WARNING: DATA RACE
Read at 0x00c000189138 by goroutine 18:
```

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 11]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
 
 var _ ActualStateOfWorld = &actualStateOfWorld{}
 
+// HandlerWithName holds information for handler and the Name of the plugin
+type HandlerWithName struct {
+	Handler PluginHandler
+	Name    string
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: should be `pluginName`?

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 12]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
 
 var _ ActualStateOfWorld = &actualStateOfWorld{}
 
+// HandlerWithName holds information for handler and the Name of the plugin
+type HandlerWithName struct {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: `namedPluginHandler`?

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 13]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
...
+	Handler PluginHandler
+	Name    string
+}
+
+// MapHandlerWithName contains the map from socket path to HandlerWithName
+type MapHandlerWithName struct {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: `SocketPluginHandlers`?. In general I would recommend naming things based on what they are, instead of what types they are comprised of.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 12 above)
Comment (davidz627) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: why are these exported types now?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 14]
```diff
@@ -122,6 +124,11 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
 		if err := handler.RegisterPlugin(infoResp.Name, infoResp.Endpoint, infoResp.SupportedVersions); err != nil {
 			return og.notifyPlugin(client, false, fmt.Sprintf("RegisterPlugin error -- plugin registration failed with err: %v", err))
 		}
+		pathToHandlers.Lock()
+		if pathToHandlers.Handlers != nil {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: what if the `Handlers` is nil? we just ignore it? Shoudl we throw an error or maybe initialize a new one?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 15]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
 	actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {
 
 	unregisterPluginFunc := func() error {
-		client, conn, err := dial(socketPath, dialTimeoutDuration)
-		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+		var handlerWithName cache.HandlerWithName
+		handlerFound := false
+		pathToHandlers.Lock()
+		if len(pathToHandlers.Handlers) != 0 {
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: if the handlers map is empty our behavior here is to just throw the error later because `handlerFound` is false. Why not just throw the error explicitly here instead of waiting for the knock on error later

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 16]
```diff
@@ -134,34 +141,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
 		}
-
 		// We remove the plugin to the actual state of world cache before calling a plugin consumer's Unregister handle
 		// so that if we receive a register event during Register Plugin, we can process it as a Register call.
 		actualStateOfWorldUpdater.RemovePlugin(socketPath)
 
-		handler.DeRegisterPlugin(infoResp.Name)
+		handlerWithName.Handler.DeRegisterPlugin(handlerWithName.Name)
+		pathToHandlers.Lock()
+		klog.V(4).Infof("DeRegisterPlugin called for %s on %v", handlerWithName.Name, handlerWithName.Handler)
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: does this log need to happen within the `Lock`

File: pkg/kubelet/pluginmanager/reconciler/reconciler_test.go [hunk 17]
```diff
@@ -252,6 +252,7 @@ func Test_Run_Positive_RegisterThenUnregister(t *testing.T) {
 	}
 
 	dsw.RemovePlugin(socketPath)
+	os.Remove(socketPath)
```
Comment (davidz627) [inline pkg/kubelet/pluginmanager/reconciler/reconciler_test.go]: Should there be another case where we unregister without removing the socketPath? Or is this the only case

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 12 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: operation_generator needs to instantiate the struct in registerPluginFunc

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 14 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I added code to instantiate the map.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 15 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: The error return on line 158 directly follows this.
I don't see much difference between returning error here versus current formation.

File: pkg/kubelet/pluginmanager/reconciler/reconciler_test.go (hunk 17 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/reconciler/reconciler_test.go]: Since current code doesn't rely on socketPath, we should remove it during the test.
This should be the only case.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 11 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: Since there is only one name in the struct, I think it is clear the name is plugin name.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 18]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
...
+type NamedPluginHandler struct {
+	Handler PluginHandler
+	Name    string
+}
+
+// SocketPluginHandlers contains the map from socket path to NamedPluginHandler
+type SocketPluginHandlers struct {
+	Handlers map[string]NamedPluginHandler
+	sync.Mutex
+}
```
Comment (k2huang) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: Do we need import above two structs? Can we add plugin name and type info into the existing PluginInfo struct when the plugin finishes registering?

Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: PluginInfo is used by actualStateOfWorld struct :
```
	socketFileToInfo map[string]PluginInfo
```
For actualStateOfWorld, the above two structs are not relevant.
It seems we shouldn't conflate PluginInfo with such information.

Comment (k2huang) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: Why are they not relevant? Both plugin name and type are about plugin information, so why can't we add them into PluginInfo struct?

**Review by mattjmcnaughton — COMMENTED** [review]
/uncc

Going to sign-off and let @davidz627 and @k2huang wrap up the review :)

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 18 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: In the new struct, type is not involved.
If we change the map to:
```
	Handlers map[string]PluginInfo
```
there would be redundancy - SocketPath is in both key and value.
It seems current formation is better.

**Comment by tedyu** [comment]
@davidz627 
Can you take another look ?

**Comment by tedyu** [comment]
@taragu 
Can you take a look ?

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 19]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
...
 var _ ActualStateOfWorld = &actualStateOfWorld{}
 
+// NamedPluginHandler holds information for handler and the Name of the plugin
+type NamedPluginHandler struct {
+	Handler PluginHandler
+	Name    string
+}
+
+// SocketPluginHandlers contains the map from socket path to NamedPluginHandler
+type SocketPluginHandlers struct {
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: Can we use `sync.Map` here to store the map of socket path -> NamedPluginHandler, instead of creating a struct?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 20]
```diff
@@ -134,34 +142,31 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
 
 func (og *operationGenerator) GenerateUnregisterPluginFunc(
 	socketPath string,
-	pluginHandlers map[string]cache.PluginHandler,
+	pathToHandlers *cache.SocketPluginHandlers,
 	actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {
 
 	unregisterPluginFunc := func() error {
-		client, conn, err := dial(socketPath, dialTimeoutDuration)
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I'm on the fence about whether we should still attempt to dial first and see if the plugin to unregister is actually present, and log the error when dial fails. There could be logic in the plugin handler unregistration function that depends on whether the plugin is there.

File: pkg/kubelet/pluginmanager/reconciler/reconciler.go [hunk 21]
```diff
@@ -76,6 +77,7 @@ type reconciler struct {
 	desiredStateOfWorld cache.DesiredStateOfWorld
 	actualStateOfWorld  cache.ActualStateOfWorld
 	handlers            map[string]cache.PluginHandler
+	pathToHandlers      cache.SocketPluginHandlers
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/reconciler/reconciler.go]: As an improvement, we can switch `handlers` to using `sync.Map` so we can eliminate the mutex here. We should probably also rename `handlers` to `typeToHandlers` for more clarity. I'll leave it to you to decide whether to do it in this PR or a followup PR.

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go (hunk 19 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]: It seems both mutex-guarded map and sync.Map are used in the codebase.
If the use of sync.Map is not due to performance concern, I prefer to keep the current formation.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 20 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: As stated in the problem description, the old code path wouldn't work due to the absence of socket path.
I looked at DeRegisterPlugin() and the func's it calls - I think the updated unregistration code path would work.

Please let me know your thought.

File: pkg/kubelet/pluginmanager/reconciler/reconciler.go (hunk 21 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/reconciler/reconciler.go]: Responded above.
This can be done in a follow-up.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 20 above)
Comment (taragu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Yes, I agree that the old code path wouldn't work. Do you think it would still be helpful to try dial, and log the error if dial fails but continue onto the new code path?

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Since we don't rely on the socketPath in the new code path, calling dial and logging doesn't seem necessary.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @taragu 
I have restored the pathToHandlers parameter and the dial code path.
Please take a look.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Please take a look. @taragu

File: pkg/kubelet/pluginmanager/cache/actual_state_of_world.go [hunk 22]
```diff
@@ -75,6 +75,18 @@ type actualStateOfWorld struct {
 
 var _ ActualStateOfWorld = &actualStateOfWorld{}
 
+// NamedPluginHandler holds information for handler and the Name of the plugin
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/cache/actual_state_of_world.go]:
```suggestion
// NamedPluginHandler holds information for handler and the name of the plugin
```

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 23]
```diff
@@ -135,12 +144,33 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
 	actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {
 
 	unregisterPluginFunc := func() error {
 		client, conn, err := dial(socketPath, dialTimeoutDuration)
 		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+			var handlerWithName cache.NamedPluginHandler
+			handlerFound := false
+			pathToHandlers.Lock()
+			if len(pathToHandlers.Handlers) != 0 {
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: This is not necessary here. You can directly do `handlerWithName, handlerFound = pathToHandlers.Handlers[socketPath]`.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 24]
```diff
@@ -135,12 +144,33 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
 func (og *operationGenerator) GenerateUnregisterPluginFunc(
 	socketPath string,
 	pluginHandlers map[string]cache.PluginHandler,
+	pathToHandlers *cache.SocketPluginHandlers,
 	actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {
 
 	unregisterPluginFunc := func() error {
 		client, conn, err := dial(socketPath, dialTimeoutDuration)
 		if err != nil {
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Can we log the error first?

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 25]
```diff
@@ -135,12 +144,33 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+			// We remove the plugin to the actual state of world cache before calling a plugin consumer's Unregister handle
+			// so that if we receive a register event during Register Plugin, we can process it as a Register call.
+			actualStateOfWorldUpdater.RemovePlugin(socketPath)
+
+			handlerWithName.Handler.DeRegisterPlugin(handlerWithName.Name)
+			pathToHandlers.Lock()
+			delete(pathToHandlers.Handlers, socketPath)
+			pathToHandlers.Unlock()
+			klog.V(4).Infof("DeRegisterPlugin called for %s on %v", handlerWithName.Name, handlerWithName.Handler)
+			return nil
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I think we can merge this part with line 192 to 194 by moving this outside of the if statement

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 23 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: This check also covers the case where pathToHandlers.Handlers == nil.
I think we should keep the check.

Comment (taragu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: It's fine if pathToHandlers.Handlers is nil https://play.golang.org/p/MdgbAMEAdR6

**Comment by tedyu** [comment]
@taragu 
Your comments have been addressed.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 26]
```diff
@@ -132,15 +141,38 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+	pathToHandlers *cache.SocketPluginHandlers,
 	actualStateOfWorldUpdater ActualStateOfWorldUpdater) func() error {
 
 	unregisterPluginFunc := func() error {
 		client, conn, err := dial(socketPath, dialTimeoutDuration)
 		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- dial failed at socket %s, err: %v", socketPath, err)
+			klog.V(4).Infof("unable to dial: %v", err)
+			var handlerWithName cache.NamedPluginHandler
+			handlerFound := false
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: This is longer needed.

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 27]
```diff
@@ -132,15 +141,38 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+			if !handlerFound {
+				return fmt.Errorf("unable to DeRegister - there is no handler for %s", socketPath)
+			}
+			unregisterPlugin(actualStateOfWorldUpdater, socketPath, handlerWithName.Handler, handlerWithName.Name)
+			pathToHandlers.Lock()
+			delete(pathToHandlers.Handlers, socketPath)
+			pathToHandlers.Unlock()
+			klog.V(4).Infof("DeRegisterPlugin called for %s on %v", handlerWithName.Name, handlerWithName.Handler)
+			return nil
 		}
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: I think we should only keep the `dial`, but remove `client.GetInfo`. This way, we can move everything after `var handlerWithName cache.NamedPluginHandler` out of the if statement, and have one path for unregistration.

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @taragu 
Can you confirm that we are abandoning the old code (except for dial) and would use the new code ?

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @taragu 
Can you take another look ?

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @taragu
Please review

Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: @taragu 
Please take another look

**Review by taragu — APPROVED** [review]
/lgtm

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go [hunk 28]
```diff
@@ -135,33 +144,35 @@ func (og *operationGenerator) GenerateRegisterPluginFunc(
...
+		var handlerWithName cache.NamedPluginHandler
+		pathToHandlers.Lock()
+		handlerWithName, handlerFound := pathToHandlers.Handlers[socketPath]
+		pathToHandlers.Unlock()
 
-		infoResp, err := client.GetInfo(ctx, &registerapi.InfoRequest{})
-		if err != nil {
-			return fmt.Errorf("UnregisterPlugin error -- failed to get plugin info using RPC GetInfo at socket %s, err: %v", socketPath, err)
+		if !handlerFound {
+			return fmt.Errorf("unable to DeRegister - there is no handler for %s", socketPath)
```
Comment (taragu) [inline pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Just one last nit so the error is consistent with the other functions:
```suggestion
			return fmt.Errorf("UnregisterPlugin error -- failed to get plugin handler for %s", socketPath)
```

**Review by taragu — COMMENTED** [review]
Just one last nit

File: pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go (hunk 28 above)
Comment (tedyu) [reply pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go]: Addressed.
Please take another look, @taragu .

**Review by taragu — COMMENTED** [review]
/approve

**Comment by saad-ali** [comment]
Sorry I didn't get to this PR before it merged. Took a look today and I have some concerns:

1. Why do we need to maintain an entire map of sockets to handlers in actual state, and pass that around and then try to figure out what the handler is when unregistering and then remove the handler? Why not just store the handler in `actualState.PluginInfo` (clean up will be handled automatically)?
2. We should not be doing a `dial(socketPath, ...)` at all in `unregisterPluginFunc` since, by definition, unregistration is triggered by a socket delete (i.e. I disagree with https://github.com/kubernetes/kubernetes/pull/88006/files#r389125732).

**Comment by tedyu** [comment]
I agree with #2.
For #1, this would be the updated PluginInfo :
```
type PluginInfo struct {
	SocketPath string
	Timestamp  time.Time
	Handler    PluginHandler
	Name       string
}
```
@saad-ali 
Can you confirm ?
I am working on patch for #1 and #2 now.

**Comment by saad-ali** [comment]
@tedyu Correct. And thanks for the quick turn around. I'll take a look at https://github.com/kubernetes/kubernetes/pull/89934
