### PR TITLE
Filter duplicate network packets in promiscuous bridge mode (with ebtables)

### LINKED ISSUE #30783: MAC address of cbr0 changes upon new pod creation
quote from the Kevin:

"
While investigating a bug with a kubernetes cluster, I came across the following bug report for Docker:
https://www.weave.works/anatomy-of-a-docker-networking-heisenbug/

While this bug ended up not being the root cause of the problem I was investigating, I was able to observe the "changing MAC address" behavior on cbr0 when a new container was rolled out to a node.
(this was with kubectl server version "v1.3.3")

Should Kubernetes assign a MAC address by fiat to the cbr0 device?

According to https://www.weave.works/anatomy-of-a-docker-networking-heisenbug/, bridges where the MAC is not explicitly set will adopt the _lowest_ MAC address of the attached veths.  This means that when you rollout a new container with a veth lower than all those currently existing, it will change the MAC address of cbr0, and delete all of the existing connection tracking entries for flows that used the old MAC address.
"

### PR DESCRIPTION
**Pull request by freehan**
also fixes: #30783

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28717)

### CODE REVIEW

**Comment by girishkalele** [comment]
Added do-not-merge label to hold.

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 1]
```diff
@@ -53,6 +54,9 @@ const (
 	DefaultCNIDir     = "/opt/cni/bin"
 
 	sysctlBridgeCallIptables = "net/bridge/bridge-nf-call-iptables"
+
+	// private mac prefix safe to use
```
Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: says who?  Is there a spec you can cite?

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 2]
```diff
@@ -328,6 +354,24 @@ func (plugin *kubenetNetworkPlugin) setup(namespace string, name string, id kube
 				return fmt.Errorf("Error setting promiscuous mode on %s: %v", BridgeName, err)
 			}
 		}
+
+		// configure the ebtables rules to eliminate duplicate packets by best effort
+		ebtablesPath, err := plugin.ebtables()
+		if err != nil {
+			glog.Warningf("Failed to get ebtables path: %v", err)
+		} else {
+			glog.Infof("Filtering packets with ebtables on mac address: %v, gateway: %v, pod CIDR: %v", macAddr.String(), plugin.gateway.String(), plugin.podCidr)
```
Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: should this be called in a rectification loop, like we do for iptables?

Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: does this need to gate on hairpin mode or is it always safe?

Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: how can we e2e this?

**Comment by thockin** [comment]
this needs a release note

File: pkg/kubelet/network/kubenet/kubenet_linux.go (hunk 2 above)
Comment (girishkalele) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I believe this should be safe for all modes, it should only be needed for promiscuous mode.

Comment (girishkalele) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I had a pair of containers (udp go client and a udp go server) to detect packet duplication...console logs in the server container print out `Duplication detected` - we can roll that into the existing omnibus test container perhaps and integrate into e2e ?

Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: This is only for promiscuous mode. 

We can e2e this by setting up a udp server pod and check if requests comes in with duplicates

File: pkg/kubelet/network/kubenet/kubenet_linux.go (hunk 1 above)
Comment (girishkalele) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: Ethernet OUI assignments http://standards-oui.ieee.org/oui.txt

Ethernet OUIs are supposed to be 6 nibbles though.

Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: my point was that a comment is needed :)

Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: There is a bit to set universally administered addresses or locally administered addresses. 
https://en.wikipedia.org/wiki/MAC_address

Comment (freehan) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: The second-least-significant bit of the first octet of the address. 1 stands for locally administered address

Comment (girishkalele) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: Is this considered a bugfix or a feature ? Should we use the alpha
gate/feature flags for this one too ?

Comment (thockin) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: I think this is a bugfix

**Comment by thockin** [comment]
```
Verifying hack/make-rules/../../hack/verify-gofmt.sh
!!! 'gofmt -s -w' needs to be run on the following files: 
./pkg/kubelet/network/kubenet/kubenet_linux.go
./pkg/kubelet/network/kubenet/kubenet_linux_test.go

**Comment by thockin** [comment]
@freehan:  we also need to update cluster/images/hyperkube/Dockerfile

@freehan: we also need to update the gcr.io/google_containers/debian-iptables-* images (build/debian-iptables)

@freehan we should update for GCI, too: @adityakali for consult

@luxas since I know you are trying to ferret these deps out.

warning to AWS and Azure to consider this dep: @brendandburns @justinsb

**Comment by girishkalele** [comment]
Reviewed 4 of 6 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/28717)*

**Comment by girishkalele** [comment]
Reviewed 1 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/28717)*

**Comment by freehan** [comment]
1. fixed verification failure
2. add and use FlushChain, instead of DeleteChain
3. added TODO for periodic rectify dedup rules

**Comment by luxas** [comment]
> @freehan: we also need to update cluster/images/hyperkube/Dockerfile

>@freehan: we also need to update the gcr.io/google_containers/debian-iptables-* images (build/debian-iptables)

@freehan Please do this in this PR

**Comment by freehan** [comment]
Rebased.

@luxas let me finish those in a follow up PR

**Comment by freehan** [comment]
added ebtables into `hypercube` and `debian-iptables` images

Anywhere else? I can piggy back with this PR.

**Comment by adityakali** [comment]
Please excuse my ignorance about kubenet. Does it now expect ebtables to be installed on the host? Or is it invoking the ebtables binary from the container? Container-VM Image does not have ebtables built in.

**Comment by freehan** [comment]
@adityakali 
ebtables is not a blocking dependency for kubenet. This PR improves network performance. Ideally, we should include ebtables in GCI and ContainerVM image.

The image updates are for other k8s-in-container builds.

File: build/debian-iptables/Makefile [hunk 3]
```diff
@@ -16,7 +16,7 @@
 
 REGISTRY?="gcr.io/google_containers"
 IMAGE=debian-iptables
-TAG=v3
+TAG=v4
```
Comment (thockin) [inline build/debian-iptables/Makefile]: is this pushed?

Comment (freehan) [inline build/debian-iptables/Makefile]: Not yet. Will push it once it gets lgtm

**Comment by thockin** [comment]
LGTM - push away

File: build/debian-iptables/Makefile (hunk 3 above)
Comment (luxas) [inline build/debian-iptables/Makefile]: as a followup, you should bump this v3 to v4 in `build/common.sh`

**Comment by thockin** [comment]
@k8s-bot test this: github issue #IGNORE
