### PR TITLE
Disallow headless Services with LB type

### LINKED ISSUE #33036: Services with clusterIP: None can be created with type LoadBalancer
Create the following svc:

```
apiVersion: v1
kind: Service
metadata:
  name: headful
spec:
  clusterIP: None
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: hostnames
```

It should fail.

### PR DESCRIPTION
**Pull request by nebril**
**What this PR does / why we need it**: It adds new validation rule for Services, to ensure that creating LoadBalancer type service with cluster IP set to "None" fails.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #33036

**Release note**:

``` release-note
Creating LoadBalancer Service with "None" ClusterIP is no longer possible
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33274)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Would adding this validation break existing users?  Strengthening validation is an API change so we have to ensure we cannot break an existing use case / automation setup that depends on it.

**Comment by nebril** [comment]
@smarterclayton I will try to figure this out. Are there any procedures for checking whether the API change is breaking, or should I just move around the GH and check whether the change breaks existing manifests?

**Comment by smarterclayton** [comment]
Easiest to justify is:

* Was this a valid scenario before where someone accidentally could have
this set, and if we change it will break them?  If not, then it's less
important (so if you can prove no one would be broken)
* Can you find examples of this in the real world (can be hard, I don't
always expect this but trying it is good)

**Comment by nebril** [comment]
@smarterclayton according to docs: http://kubernetes.io/docs/user-guide/services/#headless-services it doesn't make sense in any case to create a headless load balancer. Excerpt from the doc: "For such Services a cluster IP is not allocated, the kube proxy does not handle these services, and there is no load balancing or proxying done by the platform for them.". I will try to ask around if anyone ever tried to use this case for anything, but it doesn't seem to make any sense.

**Comment by smarterclayton** [comment]
There's no lie balancing done by the platform - could an integrator off the platform use this correctly (or in a more powerful way) if they wanted?

**Comment by smarterclayton** [comment]
"Load"

**Comment by nebril** [comment]
According to the docs, ClusterIP is a virtual IP address used by Kubernetes to fetch traffic to backend pods. So headless LoadBalancer doesn't seem to make sense, because it doesn't have an address to balance the load to and therefore should be disallowed by API.

**Comment by smarterclayton** [comment]
LoadBalancer services don't actually have to load balance to the cluster
IP, though.  That's just an artifact of implementation.  A LoadBalancer
service is given an external load balancing address, and many of the
implementations just happen to use the clusterIP, but it does not require
that function.

**Comment by nebril** [comment]
@smarterclayton can you give me an example of such implementation? I was not aware of that.

@thockin does the issue this PR aims to fix actually make sense given what Clayton is saying?

**Comment by thockin** [comment]
I don't think there any combination of headless+LB that valid today.  This is technically a breaking change, but every platform we support fails to handle this.

File: pkg/api/validation/validation.go [hunk 1]
```diff
@@ -2402,6 +2402,9 @@ func ValidateService(service *api.Service) field.ErrorList {
 				allErrs = append(allErrs, field.Invalid(portPath, port.Port, "may not expose port 10250 externally since it is used by kubelet"))
 			}
 		}
+		if service.Spec.ClusterIP == "None" {
+			allErrs = append(allErrs, field.Invalid(specPath.Child("clusterIP"), service.Spec.ClusterIP, "may not be set to 'None' for LoadBalancer"))
```
Comment (thockin) [inline pkg/api/validation/validation.go]: nit: add the word "services" at the end

**Comment by smarterclayton** [comment]
Really, every cloud provider we have written an implementation for does not
do this.  But anyone who is on metal could have done this just by setting
an ingress IP and adding the right scripting to populate their LB.  I'm not
terribly concerned because most people probably default to clusterIP, and
an integration like that would still work even with a clusterIP.  I guess
someone could write a service load balancer integration that gives each
endpoint one VIP and maintains a mapping, but given I haven't heard about
anyone doing that...

​I guess I'm reasonably convinced no one would be impacted outside of the
first party circle, and if they are impacted they'll let us know.  Needs a
release note.

**Comment by nebril** [comment]
Is release note in PR description enough?

**Comment by smarterclayton** [comment]
Yes

File: pkg/api/validation/validation.go [hunk 2]
```diff
@@ -2406,6 +2406,9 @@ func ValidateService(service *api.Service) field.ErrorList {
 				allErrs = append(allErrs, field.Invalid(portPath, port.Port, "may not expose port 10250 externally since it is used by kubelet"))
 			}
 		}
+		if service.Spec.ClusterIP == "None" {
+			allErrs = append(allErrs, field.Invalid(specPath.Child("clusterIP"), service.Spec.ClusterIP, "may not be set to 'None' for LoadBalancer service"))
```
Comment (thockin) [inline pkg/api/validation/validation.go]: nit, since CI is still flaking.  "services" not "service"

**Comment by thockin** [comment]
@k8s-bot unit this

**Comment by thockin** [comment]
@k8s-bot gci gce e2e test this

**Comment by thockin** [comment]
I've LGTM'ed this, despite asking for a 1 character change.  If this goes through, please followup.  If it doesn't, please fix :)

File: pkg/api/validation/validation.go (hunk 2 above)
Comment (nebril) [inline pkg/api/validation/validation.go]: Aw man, sorry about that. Will fix and rebase, flakes are still strong here.

**Comment by nebril** [comment]
Fixed the typo, rebased, flakes are gone. Please re-review.

**Comment by smarterclayton** [comment]
Lgtm
