### PR TITLE
MESOS: fix flaky TestPlugin_LifeCycle

### LINKED ISSUE #11901: Flaky: TestPlugin_LifeCycle
This is failing regularly on shippable. @karlkfi @sttts @jdef 
```
I0727 20:13:15.447673 8976 ha.go:132] scheduler process entered standby stage
I0727 20:13:15.456573 8976 plugin.go:453] Watching for newly created pods
I0727 20:13:15.481253 8976 ha.go:154] scheduler process entered master stage
I0727 20:13:15.481520 8976 ha.go:164] driver started successfully and is running
I0727 20:13:15.482440 8976 scheduler.go:315] Scheduler registered with the master: &MasterInfo{Id:*master-id,Ip:*3232235521,Port:*5050,Pid:nil,Hostname:nil,XXX_unrecognized:[],} with frameworkId: &FrameworkID{Value:*kubernetes-id,XXX_unrecognized:[],}
I0727 20:13:15.488035 8976 scheduler.go:814] explicit reconcile tasks
I0727 20:13:15.855188 8976 plugin.go:249] Try to schedule pod pod1
I0727 20:13:15.862247 8976 plugin.go:574] Error scheduling pod1: No suitable offers for pod/task; retrying
I0727 20:13:16.500504 8976 scheduler.go:814] explicit reconcile tasks
I0727 20:13:17.169313 8976 plugin.go:249] Try to schedule pod pod1
I0727 20:13:18.032735 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.ea3498ea-349b-11e5-a858-0242ac1141b4" on slave "h1" executor "executor-id" for reason "none"
E0727 20:13:18.032918 8976 registry.go:204] received STAGING for task pod.ea3498ea-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:18.033056 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.ea3498ea-349b-11e5-a858-0242ac1141b4" on slave "h1" executor "executor-id" for reason "none"
I0727 20:13:18.033173 8976 registry.go:231] Received running status for pending task: pod.ea3498ea-349b-11e5-a858-0242ac1141b4
I0727 20:13:18.033826 8976 registry.go:263] received pod status for task pod.ea3498ea-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.5 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:18.034061 8976 scheduler.go:445] task status update "TASK_LOST" from "SOURCE_EXECUTOR" for task "pod.ea3498ea-349b-11e5-a858-0242ac1141b4" on slave "h1" executor "executor-id" for reason "none"
I0727 20:13:18.240073 8976 plugin.go:249] Try to schedule pod pod3
I0727 20:13:18.241306 8976 plugin.go:574] Error scheduling pod3: No suitable offers for pod/task; retrying
I0727 20:13:19.553852 8976 plugin.go:249] Try to schedule pod pod3
I0727 20:13:19.563407 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.eba07184-349b-11e5-a858-0242ac1141b4" on slave "h3" executor "executor-id" for reason "none"
E0727 20:13:19.565464 8976 registry.go:204] received STAGING for task pod.eba07184-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:19.565770 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.eba07184-349b-11e5-a858-0242ac1141b4" on slave "h3" executor "executor-id" for reason "none"
I0727 20:13:19.566195 8976 registry.go:231] Received running status for pending task: pod.eba07184-349b-11e5-a858-0242ac1141b4
I0727 20:13:19.567871 8976 registry.go:263] received pod status for task pod.eba07184-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.7 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:19.569391 8976 scheduler.go:445] task status update "TASK_FINISHED" from "SOURCE_EXECUTOR" for task "pod.eba07184-349b-11e5-a858-0242ac1141b4" on slave "h3" executor "executor-id" for reason "none"
I0727 20:13:19.776685 8976 plugin.go:249] Try to schedule pod pod4
I0727 20:13:19.780090 8976 plugin.go:574] Error scheduling pod4: No suitable offers for pod/task; retrying
I0727 20:13:21.104027 8976 plugin.go:249] Try to schedule pod pod4
I0727 20:13:21.107948 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.ec8af2a6-349b-11e5-a858-0242ac1141b4" on slave "h4" executor "executor-id" for reason "none"
E0727 20:13:21.108706 8976 registry.go:204] received STAGING for task pod.ec8af2a6-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:21.109811 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.ec8af2a6-349b-11e5-a858-0242ac1141b4" on slave "h4" executor "executor-id" for reason "none"
I0727 20:13:21.110871 8976 registry.go:231] Received running status for pending task: pod.ec8af2a6-349b-11e5-a858-0242ac1141b4
I0727 20:13:21.116678 8976 registry.go:263] received pod status for task pod.ec8af2a6-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.8 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:21.117768 8976 scheduler.go:445] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.ec8af2a6-349b-11e5-a858-0242ac1141b4" on slave "h4" executor "executor-id" for reason "none"
I0727 20:13:21.626267 8976 plugin.go:249] Try to schedule pod pod5
I0727 20:13:21.626965 8976 plugin.go:574] Error scheduling pod5: No suitable offers for pod/task; retrying
I0727 20:13:21.773665 8976 plugin.go:249] Try to schedule pod pod5
I0727 20:13:21.775289 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.eda51ec5-349b-11e5-a858-0242ac1141b4" on slave "h5" executor "executor-id" for reason "none"
E0727 20:13:21.775404 8976 registry.go:204] received STAGING for task pod.eda51ec5-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:21.775519 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.eda51ec5-349b-11e5-a858-0242ac1141b4" on slave "h5" executor "executor-id" for reason "none"
I0727 20:13:21.775613 8976 registry.go:231] Received running status for pending task: pod.eda51ec5-349b-11e5-a858-0242ac1141b4
I0727 20:13:21.776234 8976 registry.go:263] received pod status for task pod.eda51ec5-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.9 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:21.776462 8976 scheduler.go:445] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.eda51ec5-349b-11e5-a858-0242ac1141b4" on slave "h5" executor "executor-id" for reason "none"
E0727 20:13:21.784133 8976 plugin.go:931] pod reconciliation does not support updates; not yet implemented
I0727 20:13:22.285565 8976 plugin.go:249] Try to schedule pod pod6
I0727 20:13:22.287242 8976 plugin.go:574] Error scheduling pod6: No suitable offers for pod/task; retrying
I0727 20:13:23.599380 8976 plugin.go:249] Try to schedule pod pod6
I0727 20:13:23.604169 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.ee09c157-349b-11e5-a858-0242ac1141b4" on slave "h6" executor "executor-id" for reason "none"
E0727 20:13:23.604410 8976 registry.go:204] received STAGING for task pod.ee09c157-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:23.604824 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.ee09c157-349b-11e5-a858-0242ac1141b4" on slave "h6" executor "executor-id" for reason "none"
I0727 20:13:23.605419 8976 registry.go:231] Received running status for pending task: pod.ee09c157-349b-11e5-a858-0242ac1141b4
I0727 20:13:23.606419 8976 registry.go:263] received pod status for task pod.ee09c157-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.10 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:23.606821 8976 scheduler.go:445] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.ee09c157-349b-11e5-a858-0242ac1141b4" on slave "h6" executor "executor-id" for reason "none"
E0727 20:13:23.612406 8976 plugin.go:926] pod already scheduled: pod6
I0727 20:13:24.116100 8976 plugin.go:249] Try to schedule pod pod7
I0727 20:13:24.117787 8976 plugin.go:574] Error scheduling pod7: No suitable offers for pod/task; retrying
I0727 20:13:25.422296 8976 plugin.go:249] Try to schedule pod pod7
I0727 20:13:25.425824 8976 scheduler.go:445] task status update "TASK_STAGING" from "SOURCE_EXECUTOR" for task "pod.ef211221-349b-11e5-a858-0242ac1141b4" on slave "h7" executor "executor-id" for reason "none"
E0727 20:13:25.426251 8976 registry.go:204] received STAGING for task pod.ef211221-349b-11e5-a858-0242ac1141b4 with unexpected source: SOURCE_EXECUTOR
I0727 20:13:25.426594 8976 scheduler.go:445] task status update "TASK_RUNNING" from "SOURCE_EXECUTOR" for task "pod.ef211221-349b-11e5-a858-0242ac1141b4" on slave "h7" executor "executor-id" for reason "none"
I0727 20:13:25.427448 8976 registry.go:231] Received running status for pending task: pod.ef211221-349b-11e5-a858-0242ac1141b4
I0727 20:13:25.429333 8976 registry.go:263] received pod status for task pod.ef211221-349b-11e5-a858-0242ac1141b4: {Phase: Conditions:[{Type:Ready Status:True}] Message: Reason: HostIP: PodIP:1.2.3.11 StartTime:<nil> ContainerStatuses:[]}
I0727 20:13:25.930455 8976 scheduler.go:445] task status update "TASK_FAILED" from "SOURCE_EXECUTOR" for task "pod.ef211221-349b-11e5-a858-0242ac1141b4" on slave "h7" executor "executor-id" for reason "none"
E0727 20:13:25.968520 8976 plugin.go:926] pod already scheduled: pod7
I0727 20:13:26.034248 8976 ha.go:141] scheduler process entered fin stage
--- FAIL: TestPlugin_LifeCycle (10.65s)
<autogenerated>:31:
Error Trace:	plugin_test.go:321
plugin_test.go:327
plugin_test.go:479
Error:	event not received
I0727 20:13:26.075822 8976 scheduler.go:414] Offer rescinded &OfferID{Value:*test1,XXX_unrecognized:[],}
I0727 20:13:26.078025 8976 scheduler.go:414] Offer rescinded &OfferID{Value:*test2,XXX_unrecognized:[],}
I0727 20:13:26.080150 8976 scheduler.go:414] Offer rescinded &OfferID{Value:*notExist,XXX_unrecognized:[],}
I0727 20:13:26.082263 8976 scheduler.go:634] Slave &SlaveID{Value:*h1,XXX_unrecognized:[],} is lost
I0727 20:13:26.082927 8976 scheduler.go:634] Slave &SlaveID{Value:*h2,XXX_unrecognized:[],} is lost
I0727 20:13:26.085804 8976 scheduler.go:634] Slave &SlaveID{Value:*notExist,XXX_unrecognized:[],} is lost
I0727 20:13:26.088668 8976 scheduler.go:391] Master disconnected!
I0727 20:13:26.097461 8976 scheduler.go:445] task status update "TASK_RUNNING" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
W0727 20:13:26.097899 8976 registry.go:240] Ignore status TASK_RUNNING because the task test-task-001 is discarded
E0727 20:13:26.098126 8976 scheduler.go:552] possible rogue pod; illegal task status data for task test-task-001, expected an api.PodStatusResult: missing TaskStatus.Data
I0727 20:13:26.098781 8976 scheduler.go:445] task status update "TASK_RUNNING" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
W0727 20:13:26.098991 8976 registry.go:240] Ignore status TASK_RUNNING because the task test-task-001 is discarded
E0727 20:13:26.099199 8976 scheduler.go:552] possible rogue pod; illegal task status data for task test-task-001, expected an api.PodStatusResult: missing TaskStatus.Data
I0727 20:13:26.099601 8976 scheduler.go:445] task status update "TASK_FAILED" from "none" for task "test-task-001" on slave "" executor "" for reason "none"
FAIL
coverage: 60.2% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/scheduler	11.177s
```

cc @lavalamp

### PR DESCRIPTION
**Pull request by s-urbaniak**
This PR is supposed to fix #11901 and https://github.com/mesosphere/kubernetes-mesos/issues/441 by increasing timeouts from a few seconds to one minute. Additionally this PR catches up with the most recent changes in the scheduler. Finally it introduces a simple lifecycle test setup inspired by @sttts (https://github.com/sttts/kubernetes/commit/27c80bcaf7752983bc2809b476b72fa4da3e2327).

### CODE REVIEW

**Comment by sttts** [comment]
Can you split the different fixes into single commits? Like one commit for the refactoring, one for the timeouts, one for the event rename fixes.

**Comment by sttts** [comment]
Makes it much easier to follow during a review.

**Comment by sttts** [comment]
:+1:

**Comment by jdef** [comment]
@s-urbaniak is this ready for review?

**Comment by s-urbaniak** [comment]
@jdef yes, PTAL

**Comment by s-urbaniak** [comment]
@sttts PTAL

File: contrib/mesos/pkg/scheduler/plugin_test.go [hunk 1]
```diff
@@ -362,28 +371,30 @@ func newTaskStatusForTask(task *mesos.TaskInfo, state mesos.TaskState) *mesos.Ta
 	}
 }
 
-// Test to create the scheduler plugin with an empty plugin config
-func TestPlugin_New(t *testing.T) {
-	assert := assert.New(t)
+type LaunchedTask struct {
```
Comment (sttts) [inline contrib/mesos/pkg/scheduler/plugin_test.go]: Does this have to be public?

**Comment by s-urbaniak** [comment]
@jdef @sttts if possible, please give me feedback if this is a good direction for the refactoring. There is quite potential for much more refactoring, i.e. I could move single types into a dedicated `scheduler/test` package (inspired by camlistore).

File: contrib/mesos/pkg/scheduler/plugin_test.go (hunk 1 above)
Comment (s-urbaniak) [inline contrib/mesos/pkg/scheduler/plugin_test.go]: In this package, no (good catch). If we refactor in a separate `test` package, then I'd vote for public visibility.

Comment (jdef) [inline contrib/mesos/pkg/scheduler/plugin_test.go]: refactoring things into a separate `schedulertest` package sounds good (let's avoid adding another `test` package to avoid confusion)

**Comment by jdef** [comment]
:+1: looking good so far. what chance do we have of eliminating the timeout-based dependencies? for example, timeouts were increased to 1m, which seems like it should be plenty but I'm still worried about this test flaking in heavily loaded CI environments due to timeout.

**Comment by jdef** [comment]
possible that with some additional refactoring we could leverage something like this?
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/clock.go

**Comment by sttts** [comment]
We should identify the places where we poll with a timeout in the scheduler. Other than those, we will need some kind of timeouts as long as we do integration testing. We should try to decouple the components of the scheduler and introduce proper interfaces which enable testing which is more than injecting some input, waiting and comparing some output on a completely different channel.

**Comment by s-urbaniak** [comment]
@sttts @jdef PTAL, especially https://github.com/mesosphere/kubernetes/commit/c8c86bf9d3f9bf126140bad316a323dd2a27e849: i had to disable two tests because they referred to deep internal state.

I am investigating the current code base now to determine whether we can refactor to a non-timeout based test.

File: contrib/mesos/pkg/scheduler/plugin.go [hunk 2]
```diff
@@ -52,6 +52,11 @@ const (
 	pluginRecoveryDelay = 100 * time.Millisecond // delay after scheduler plugin crashes, before we resume scheduling
 )
 
+const (
+	FailedScheduling = "FailedScheduling"
+	Scheduled        = "Scheduled"
+)
+
 // scheduler abstraction to allow for easier unit testing
 type schedulerInterface interface {
```
Comment (karlkfi) [inline contrib/mesos/pkg/scheduler/plugin.go]: I'm really not a fan of this naming convention using `-Interface`. 
Are we doing this throughout k8sm? Is the rest of k8s doing this?

**Comment by karlkfi** [comment]
@jdef Do you know why there are so many classes defined in plugin.go?

- schedulerInterface
- k8smScheduler
- binder
- kubeScheduler
- queuer
- errorHandler
- deleter
- KubernetesScheduler
- PluginConfig
- schedulingPlugin
- podStoreAdapter

I can't even figure out how they all relate...

Unless there's some sort of upstream symmetry we really need to keep, it's well past time they were split up and renamed/repackaged.

This doesn't need to happen as part of this PR, but it makes it impossible to intelligently review anything that modifies this code.

**Comment by karlkfi** [comment]
I'm not a big fan of having a package named `scheduler/schedulertest`. Is there some way to clean that up? I'm used naming like `scheduler/mock` before, elsewhere, but haven't modified enough k8s code to make that a pattern in this repo yet.

Another consideration is that this is test code, so we might want to make sure it's only used in test and not baked into the binary. The only way I know to do that now is to end the file in `_test.go`. But maybe there are other ways.

It's also not clear to me how `schedulertest` and `schedulertest/driver` relate. Can you describe them more? At minimum the driver package needs a doc.go file, but I suspect some repackaging would make it more clear.

**Comment by s-urbaniak** [comment]
@karlkfi thanks for your comments. I suggested `test` (as in https://github.com/camlistore/camlistore/tree/master/pkg/test) but @jdef preferred `schedulertest`. I prefer `test` or `mock` too.

Everything you see in `schedulertest` and `schedulertest/driver` used to be embedded in one big `plugin_test.go` file. The changes exposed here are quite mechanical.

I'll recheck whether the linker really embeds the `schedulertest` pkg in the final binary. It shouldn't (imho) as long as there is no reference from non-test code. Additionally all structs and construction methods are private.

The `schedulertest/driver` package was necessary to resolve a circular package dependency because `scheduler_test.go` also uses the mock driver. I am happy to move all this jazz in different pkgs, i.e. `mock/driver`, `mock/listwatch`, `mock/server`, etc.

**Comment by karlkfi** [comment]
I'm betting @jdef wanted `schedulertest` just to not have to alias the import, but I think it's fine aliasing test imports. I vote for a more consistent pattern of having `scheduler/test` or `scheduler/mocks`. Then alias it as `scheduler_test` or `mock_scheduler`.

The pattern I'm familiar with from Pivotal code was using [Counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) to generate a `mocks/mocks.go` file with mock impls based on supplied interfaces. Then we'd alias all the mock imports with `mock_<pkg>` for consistency.

Ex: 
- imports: https://github.com/cloudfoundry/bosh-init/blob/master/integration/deploy_test.go#L20-L27
- code generation: https://github.com/cloudfoundry/bosh-init/blob/master/bin/mockgen

I guess I still don't understand `schedulertest/driver`. Why isn't the mock/driver just in the test package? What's the difference between the driver and the test classes? Are they all mocks or is the driver the only mock?

**Comment by sttts** [comment]
:+1:  for scheduler/test with an alias.

**Comment by jdef** [comment]
The intent was to break things into smaller pieces that were easier to
reason about individually. The work was never completed. Things should
interact via interface contracts vs. referencing each other's private
fields. The result was an explosion of poorly named classes. The end game
was, in fact, to repackage some of these pieces.

File: contrib/mesos/pkg/scheduler/plugin.go (hunk 2 above)
Comment (jdef) [inline contrib/mesos/pkg/scheduler/plugin.go]: I did this :(  I needed to stop the plugin from reaching directly for the
fields of KubernetesScheduler. I wasn't feeling very creative or inspired.
schedulerInterface was named. Ideally the plugin stuff (the k8s side of the
scheduler) would live in a plugin/ package. I use the name "plugin" because
the upstream scheduler is in a "plugin/scheduler/..." set of packages so it
was easy for me to distinguish between the "mesos" side of the brain and
the "plugin" side of the brain.

**Comment by jdef** [comment]
packages can also be named with a _test suffix to force the linker's hand.
so if the folder is a/b/c, you can create a file a/b/c/c_test.go that
declares a package of "c_test"

**Comment by jdef** [comment]
@karlkfi is a good guesser. I did want schedulertest. It's very explicit
and would never be confused with any other "*test" package. Go's stdlib has
precedence for this, e.g. httptest, iotest. I don't think it's very
idiomatic to name packages such that you expect to force people everywhere
to always alias them, just because you wanted a nice short name for
package. We've had this conversation before and I understand that we have
differing philosophies.

We should stick with schedulertest.

**Comment by s-urbaniak** [comment]
Re `schedulertest/driver`:

If I move `driver.go` to the `schedulertest` package then I break `scheduler_test.go#TestStatus_Update` which uses `MockSchedulerDriver` implying a circular dependency between the `scheduler` and `schedulertest` package giving me the following compiler error:

```
$ cd ~/k8s/src/k8s.io/kubernetes/contrib/mesos/pkg/scheduler
$ go test
# k8s.io/kubernetes/contrib/mesos/pkg/scheduler
import cycle not allowed in test
package k8s.io/kubernetes/contrib/mesos/pkg/scheduler (test)
	imports k8s.io/kubernetes/contrib/mesos/pkg/scheduler/schedulertest
	imports k8s.io/kubernetes/contrib/mesos/pkg/scheduler

FAIL	k8s.io/kubernetes/contrib/mesos/pkg/scheduler [setup failed]
```

I'd have to move `scheduler_test.go#TestStatus_Update` to the `schedulertest` package but `TestStatus_Update` creates `KubernetesScheduler` using private fields.

I can play around tomorrow if I can create `KubernetesScheduler` using `func New(config Config) *KubernetesScheduler` in the `schedulertest` package resolving the circular dependency.

**Comment by sttts** [comment]
Having schedulertest below scheduler is pretty strange. I agree with @karlkfi's proposal to rename it to schedtest or anything like that during import. It's done with utils, it's done with types, it's done with proto. Why not with test?

Another idea and/or question: why do we want an extra module? Because we talk about integration tests? Unit tests are idiomatically in *_test.go files.

**Comment by s-urbaniak** [comment]
@sttts yes, this test spawns a web server and components from many different packages testing a complete lifecycle. I classify this also as an integration test.

**Comment by jdef** [comment]
agreed this feels more like an integration than a unit test

On Tue, Sep 22, 2015 at 5:01 PM, Sergiusz Urbaniak <notifications@github.com

**Comment by karlkfi** [comment]
if it's an integration test, maybe it should move to the integration test package and save us all the trouble of having to fight over `schedulertest` and `scheduler/test` (tho I think @jdef is the odd man out here, and I'm pretty sure k8s conventions backs us up).

**Comment by jdef** [comment]
there are no such k8s conventions. however k8s does have a
tests/integration package that looks interesting.

**Comment by s-urbaniak** [comment]
OK, this mechanical refactor of the "unit test" gets out of hand IMHO and leads to discussions outside of a pure "make this unit test work" task.

@sttts and me suggest to split this PR until https://github.com/mesosphere/kubernetes/commit/32f6cd2fff1f377cd0a2434f817725e747903619 and open a seperate PR for the migration to a more concise integration test package.

Eventually the separate PR also could include code changes to the scheduler itself (simplifying its API)

**Comment by jdef** [comment]
sgtm

On Wed, Sep 23, 2015 at 6:38 AM, Sergiusz Urbaniak <notifications@github.com

**Comment by s-urbaniak** [comment]
@sttts @karlkfi @jdef PTAL, I stripped this PR to a minimal set of commits.

The followup-refactoring will be at https://github.com/mesosphere/kubernetes/tree/sur-k8sm-508-scheduler-integration-test

**Comment by karlkfi** [comment]
so... how do we know this isn't flakey any more?

**Comment by s-urbaniak** [comment]
@karlkfi being timeout based, we can't.

If we don't feel confident enough about the given timeouts we can leave this test skipped (by closing this PR) and I'll concentrate on the refactoring https://github.com/mesosphere/kubernetes-mesos/issues/508 and the refactoring of the delay queue.

**Comment by sttts** [comment]
Look at util.ForeverTestTimeout. Timeouts are not a problem. They are used everywhere in k8s tests. But they should not be as small as 1 sec or 2 sec.

**Comment by s-urbaniak** [comment]
@sttts @jdef PTAL

**Comment by sttts** [comment]
Some small nits. Looks very good!

**Comment by bgrant0607** [comment]
I assume this is no longer WIP?

**Comment by jdef** [comment]
correct: sttts tagged it lgtm so it should be ready to roll

**Comment by sttts** [comment]
@s-urbaniak rebase needed

**Comment by s-urbaniak** [comment]
@jdef @sttts PTAL

**Comment by sttts** [comment]
lgtm. Please squash the commits.

**Comment by brendandburns** [comment]
Shippable is a flake, merging.
