### PR TITLE
Modified run-gcloud-compute-with-retries and used it wherever possible in kubemark

### LINKED ISSUE #39335: Kubemark {e2e.go}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-kubemark-5-gce/3443/
Failed: Kubemark {e2e.go}

```
exit status 1
```

Previous issues for this test: #38776

### PR DESCRIPTION
**Pull request by shyamjvs**
This PR fixes #39335 
Simple changes fixing flaky issues within kubemark.

@kubernetes/sig-scalability-misc @wojtek-t @gmarek

### CODE REVIEW

**Comment by gmarek** [comment]
Please squash commands.

File: test/kubemark/common.sh [hunk 1]
```diff
@@ -49,8 +49,13 @@ export RESOURCE_DIRECTORY="${KUBEMARK_DIRECTORY}/resources"
 # arguments:
 # $@: all stuff that goes after 'gcloud compute '
 function run-gcloud-compute-with-retries {
+  echo "" > /tmp/gcloud_retries
   for attempt in $(seq 1 ${RETRIES}); do
-    if ! gcloud compute $@; then
```
Comment (gmarek) [inline test/kubemark/common.sh]: I'm not sure about this change. This will make 'start-kubemark' executions work, even if previous run was not cleaned up correctly. I think it's worse than failing in case of some stalled gcloud call. This is not very strong opinion, so feel free to disagree and keep it. If you do append some hash of command being run after `gcloud_retries` to make it thread safe.

File: test/kubemark/start-kubemark.sh [hunk 2]
```diff
@@ -157,7 +157,7 @@ gcloud compute ssh --zone="${ZONE}" --project="${PROJECT}" "${MASTER_NAME}" \
     sudo bash -c \"echo ${password},admin,admin > /etc/srv/kubernetes/basic_auth.csv\""
 
 
-gcloud compute copy-files --zone="${ZONE}" --project="${PROJECT}" \
```
Comment (gmarek) [inline test/kubemark/start-kubemark.sh]: See if it's actually working. I remember I had problems with ssh/copy-files at some point.

File: test/kubemark/common.sh (hunk 1 above)
Comment (shyamjvs) [inline test/kubemark/common.sh]: That's a good point. Solved it simply by checking if the 'already exists' error comes up right in the first attempt (which means previous run didn't stop properly).

File: test/kubemark/start-kubemark.sh (hunk 2 above)
Comment (shyamjvs) [inline test/kubemark/start-kubemark.sh]: I checked if both of them are working in the following way:
ssh: Added `sudo bash -c "if [[ $(($RANDOM % 2)) == 0 ]]; then exit 1;` to the list of commands in ssh, which makes the ssh fail randomly, but the code still works due to having 3 retries (with a probability of 1/8 and I was unlucky enough to get only this 1 case out of the 8 when I checked for the first time :p )
copy-files: Ran the same copy-files command back to back (but with the file content changed in between) and it worked as expected.

**Comment by shyamjvs** [comment]
@k8s-bot bazel test this

**Comment by shyamjvs** [comment]
@gmarek Fixed the issues, PTAL.

**Comment by shyamjvs** [comment]
@gmarek Could you lgtm this again?
