### PR TITLE
Fix subnet annotation checking for Azure internal loadbalancer

### LINKED ISSUE #74497: Azure internal loadbalaner is pending forever if subnet annotation is set to empty string
**What happened**:

When service is set with ILB annotation and empty string subnet, e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ""
spec:
  type: LoadBalancer
  ...
```

The service would be pending forever with following error:

```sh
network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"MissingJsonReferenceId","message":"Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.subnet."}]
```

**What you expected to happen**:

ILB should be provisioned successfully.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/assign

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fix subnet annotation checking for Azure internal loadbalancer. When the annotation is set with empty string, return nil instead in `subet()`, so that default subnet configured in cloud provider config file would be used.

More unit tests are also added for this function.

**Which issue(s) this PR fixes**:

Fixes #74497

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix subnet annotation checking for Azure internal loadbalancer
```

/priority important-soon
/sig azure
/assign @andyzhangx @khenidak

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @andyzhangx PTAL

File: pkg/cloudprovider/providers/azure/azure_loadbalancer.go [hunk 1]
```diff
@@ -1538,7 +1538,7 @@ func requiresInternalLoadBalancer(service *v1.Service) bool {
 
 func subnet(service *v1.Service) *string {
 	if requiresInternalLoadBalancer(service) {
-		if l, found := service.Annotations[ServiceAnnotationLoadBalancerInternalSubnet]; found {
+		if l, found := service.Annotations[ServiceAnnotationLoadBalancerInternalSubnet]; found && strings.TrimSpace(l) != "" {
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_loadbalancer.go]: if it returns pointer to "", code will jump to following, and then still return error:
https://github.com/kubernetes/kubernetes/blob/8d0c5d9727d458da51e40810387a3d9e2030fd68/pkg/cloudprovider/providers/azure/azure_loadbalancer.go#L532

Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_loadbalancer.go]: it won't error if this case, because `nil` would be returned.

**Review by andyzhangx — APPROVED** [review]
/lgtm
