### PR TITLE
Fix volume scheduling issue with pod affinity and anti-affinity

### LINKED ISSUE #65131: Pod use local volume pvc stuck at pending
/kind bug

**What happened**:
We have 3 rack at the cluster, and then I create 3 pods, which have anti-affinity rules by rack.
I create these 3 pods without interval.
Then I found there is just 1 pod is `running` and other 2 pods are stuck at `pending`
**But all the pod's pvc had been bound.** 
The bound pv has the same node affinity rule.
```
volume.alpha.kubernetes.io/node-affinity: '{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["XXXXXXXXXXX"]}]}]}}'
```

**What you expected to happen**:
All these three pod can be running

**How to reproduce it (as minimally and precisely as possible)**:
1. Create pods with the anti-affinity rules, the number of pods can be the same with the rack numbers
2. These pods should use local volume pvc
3. Create these pods with few interval 

**Anything else we need to know?**:
I think the issue maybe caused by:
1. We assume bound volume first at https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L480
After all the volume had bound, then assume the pod
2. But the issue is, there maybe many pods with anti-affinity rules are assume volumes, and waiting for the volume to be bound.  At this time, the pod is not considered with a anti-affinity pod, so they may choose the same rack's pv and then their pvc will bound the the pv.
3. The pod will be scheduled again, and they will never be scheduled, because there pvc had bound the the pv at the same rack. 
4. Pod stuck at `pending`

**Environment**:
-  k8s 1.9

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
The previous design of the volume scheduler had volume assume + bind done before pod assume + bind.  This causes issues when trying to evaluate future pods with pod affinity/anti-affinity because the pod has not been assumed while the volumes have been decided.

This PR changes the design so that volume and pod are assumed first, followed by volume and pod binding.  Volume binding waits (asynchronously) for the operations to complete or error. This eliminates the subsequent passes through the scheduler to wait for volume binding to complete (although pod events or resyncs may still cause the pod to run through scheduling while binding is still in progress).   This design also aligns better with the scheduler framework design, so will make it easier to migrate in the future.

Many changes had to be made in the volume scheduler to handle this new design, mostly around:
* How we cache pending binding operations.  Now, any delayed binding PVC that is not fully bound must have a cached binding operation.  This also means bind API updates may be repeated.
* Waiting for the bind operation to fully complete, and detecting failure conditions to abort the bind and retry scheduling.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65131

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixes issue where pod scheduling may fail when using local PVs and pod affinity and anti-affinity without the default StatefulSet OrderedReady pod management policy
```

### CODE REVIEW

File: pkg/controller/volume/persistentvolume/scheduler_binder_fake.go [hunk 1]
```diff
@@ -48,16 +45,21 @@ func (b *FakeVolumeBinder) FindPodVolumes(pod *v1.Pod, node *v1.Node) (unboundVo
...
-	return b.config.AllBound, b.config.AssumeBindingRequired, b.config.AssumeErr
+	return b.config.AllBound, b.config.AssumeErr
 }
 
 func (b *FakeVolumeBinder) BindPodVolumes(assumedPod *v1.Pod) error {
 	b.BindCalled = true
 	return b.config.BindErr
 }
 
+func (b *FakeVolumeBinder) BindPodVolumesWait(assumedPod *v1.Pod) error {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_fake.go]: remove

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -432,6 +374,7 @@ func (sched *Scheduler) bind(assumed *v1.Pod, b *v1.Binding) error {
 	metrics.BindingLatency.Observe(metrics.SinceInMicroseconds(bindingStart))
 	metrics.SchedulingLatency.WithLabelValues(metrics.Binding).Observe(metrics.SinceInSeconds(bindingStart))
 	sched.config.Recorder.Eventf(assumed, v1.EventTypeNormal, "Scheduled", "Successfully assigned %v/%v to %v", assumed.Namespace, assumed.Name, b.Target.Name)
+	glog.V(5).Infof("Successfully bound pod: %v/%v", assumed.Namespace, assumed.Name)
```
Comment (msau42) [inline pkg/scheduler/scheduler.go]: remove

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -470,16 +413,15 @@ func (sched *Scheduler) scheduleOne() {
 
 	// Assume volumes first before assuming the pod.
 	//
-	// If no volumes need binding, then nil is returned, and continue to assume the pod.
+	// If no volumes need binding, then allBound is true.
 	//
-	// Otherwise, error is returned and volume binding is started asynchronously for all of the pod's volumes.
-	// scheduleOne() returns immediately on error, so that it doesn't continue to assume the pod.
+	// If binding is required, binidngRequired is true. TODO: what if API updated but pod came through
```
Comment (msau42) [inline pkg/scheduler/scheduler.go]: update

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 4]
```diff
@@ -253,58 +254,190 @@ func (b *volumeBinder) AssumePodVolumes(assumedPod *v1.Pod, nodeName string) (al
...
+	}
+
+	for _, claim := range claimsToProvision {
+		bound, pvc, err := b.isPVCBound(claim.Namespace, claim.Name, true)
+		if err != nil || pvc == nil {
+			return false, fmt.Errorf("failed to check pvc binding: %v", err)
+		}
+
+		// Check if selectedNode annotation is still set
+		if pvc.Annotations == nil || len(pvc.Annotations[annSelectedNode]) == 0 {
```
Comment (lichuqiang) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Validate it's value equal to the node name of the pod?

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 5]
```diff
@@ -253,58 +254,190 @@ func (b *volumeBinder) AssumePodVolumes(assumedPod *v1.Pod, nodeName string) (al
...
+func getPVCName(pvc *v1.PersistentVolumeClaim) string {
+	return pvc.Namespace + "/" + pvc.Name
+}
+
+// bindAPIUpdate gets the cached bindings and PVCs to provision in podBindingCache
+// and makes the API update for those PVs/PVCs.
+func (b *volumeBinder) bindAPIUpdate(assumedPod *v1.Pod, bindings []*bindingInfo, claimsToProvision []*v1.PersistentVolumeClaim) error {
+	podName := getPodName(assumedPod)
+
+	unprocessedBindings := 0
```
Comment (lichuqiang) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Hmm, better to name it "processedXXX", i.e. how many bindings/provisions have been processed

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 6]
```diff
@@ -253,58 +254,190 @@ func (b *volumeBinder) AssumePodVolumes(assumedPod *v1.Pod, nodeName string) (al
...
+	}
+
+	// All pvs and pvcs that we operated on are bound
+	glog.V(4).Infof("All PVCs for pod %q are bound", podName)
+	return true, nil
 }
 
-func getPVCName(pvc *v1.PersistentVolumeClaim) string {
-	return pvc.Namespace + "/" + pvc.Name
+// check that claimsToBind + claimsToProvision should include all of the Pod's unbound PVCs
```
Comment (lichuqiang) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: Can this happen that number of (claimsToBind + claimsToProvision) less than a Pod's unbound PVCs?

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: I think a user can delete and recreate a previously bound PVC.  If it got recreated in between predicate and assume, or between assume and bind, then I want to avoid returning binding success if not all PVCs are bound.  But this check isn't race-free.  A user could do the same thing after scheduling and before kubelet comes up.  I guess considering that, we could simplify the logic a little and remove this check.

**Comment by msau42** [comment]
Latest update adds:
* Integration and e2e tests
* Fix some minor comments

Still need to:
* Address remaining comments
* Add more unit tests

File: test/integration/scheduler/volume_binding_test.go [hunk 7]
```diff
@@ -457,12 +458,141 @@ func testVolumeBindingStress(t *testing.T, schedulerResyncPeriod time.Duration)
...
+	for _, pvc := range pvcs {
+		validatePVCPhase(t, config.client, pvc.Name, config.ns, v1.ClaimBound)
+	}
+}
+
+func TestVolumeBindingWithAntiAffinity(t *testing.T) {
+	numNodes := 10
+	// Create as many pods as number of nodes
+	numPods := numNodes
+	// Create many more PVs on node1 to increase chance of selecting node1
```
Comment (msau42) [inline test/integration/scheduler/volume_binding_test.go]: Does anyone have suggestions on a deterministic test case?

**Comment by msau42** [comment]
Integration test is flaky. Investigating...

**Comment by msau42** [comment]
Addressed all comments and added/fixed all tests

**Comment by msau42** [comment]
This is ready for review

File: pkg/controller/volume/persistentvolume/scheduler_binder_test.go [hunk 8]
```diff
@@ -247,17 +262,32 @@ func (env *testEnv) initPodCache(pod *v1.Pod, node string, bindings []*bindingIn
...
+	} else {
+		for i := 0; i < aLen; i++ {
+			// Validate PV
+			if !reflect.DeepEqual(expectedBindings[i].pv, bindings[i].pv) {
+				t.Errorf("Test %q failed. binding.pv doesn't match [A-expected, B-got]: %s", name, diff.ObjectDiff(expectedBindings[i].pv, bindings[i].pv))
+			}
+
+			// Validate PVC
+			if !reflect.DeepEqual(expectedBindings[i].pvc, bindings[i].pvc) {
+				t.Errorf("Test %q failed. binding.pvc doesn't match [A-expected, B-got]: %s", name, diff.ObjectDiff(expectedBindings[i].pv, bindings[i].pv))
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder_test.go]: print out pvc

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 9]
```diff
@@ -313,6 +403,10 @@ func (b *volumeBinder) isVolumeBound(namespace string, vol *v1.Volume, checkFull
 	}
 
 	pvcName := vol.PersistentVolumeClaim.ClaimName
+	return b.isPVCBound(namespace, pvcName, checkFullyBound)
+}
+
+func (b *volumeBinder) isPVCBound(namespace, pvcName string, checkFullyBound bool) (bool, *v1.PersistentVolumeClaim, error) {
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: checkFullyBound argument can be removed

File: pkg/scheduler/volumebinder/volume_binder.go [hunk 10]
```diff
@@ -43,27 +39,18 @@ func NewVolumeBinder(
 	storageClassInformer storageinformers.StorageClassInformer) *VolumeBinder {
 
 	return &VolumeBinder{
-		Binder:    persistentvolume.NewVolumeBinder(client, pvcInformer, pvInformer, storageClassInformer),
-		BindQueue: workqueue.NewNamed("podsToBind"),
+		// TODO: what is a good bind timeout value?
+		Binder: persistentvolume.NewVolumeBinder(client, pvcInformer, pvInformer, storageClassInformer, 10*time.Minute),
```
Comment (lichuqiang) [inline pkg/scheduler/volumebinder/volume_binder.go]: Time consumption of provision for different storages can be vary, we'd better expose the timeout param to users

File: pkg/controller/volume/persistentvolume/scheduler_binder.go (hunk 6 above)
Comment (wenlxie) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: If the pvc deleted , then it need  wait for timeout time (10 minutes ) to return fail? 

```
return wait.Poll(time.Second, b.bindTimeout, func() (bool, error) {
		return b.checkBindings(assumedPod, bindings, claimsToProvision)
	})
```

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: [This check](https://github.com/kubernetes/kubernetes/pull/67556/commits/45d15d4bd2254517ce25e240a3ff9764b6990127#diff-8b07987b1af2d0e15a272411da722f5cR367) returns an error immediately if PVC is deleted.

Similar check for PV deletion too

Comment (wenlxie) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: @msau42  But wait.Poll will wait for timeout in this condition?
https://github.com/kubernetes/kubernetes/pull/67556/commits/45d15d4bd2254517ce25e240a3ff9764b6990127#diff-8b07987b1af2d0e15a272411da722f5cR286

Comment (lichuqiang) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: Nope, the Poll func will return when it got an error

Comment (wenlxie) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: @lichuqiang   Thanks, then this make sense.

File: pkg/scheduler/volumebinder/volume_binder.go (hunk 10 above)
Comment (msau42) [reply pkg/scheduler/volumebinder/volume_binder.go]: How about we loop forever?  We early abort on many conditions, including:
- PVC or PV is deleted
- PVC selectedNode annotation got reset
- PV ClaimRef reset

We could also add one more check for if the Pod got deleted.

That way if the Pod gets stuck binding for some reason, there are various ways for the user to abort the process.

Comment (msau42) [reply pkg/scheduler/volumebinder/volume_binder.go]: The other concern is that this goroutine will be open as long as volume binding is pending.  Maybe we can have exponential backoff so all the goroutines won't wake up at the same time.

File: pkg/scheduler/scheduler.go [hunk 11]
```diff
@@ -491,6 +435,14 @@ func (sched *Scheduler) scheduleOne() {
 	}
 	// bind the pod to its host asynchronously (we can do this b/c of the assumption step above).
 	go func() {
+		// Bind volumes first before Pod
+		if !allBound {
+			err = sched.bindVolumes(assumedPod)
```
[the remark this answers is not in the document]
Comment (bsalamat) [reply pkg/scheduler/scheduler.go]: Yes. That's a good idea (perhaps necessary) to add a scheduler metric for this. It doesn't have to be in this PR though.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 12]
```diff
@@ -249,66 +252,157 @@ func (b *volumeBinder) AssumePodVolumes(assumedPod *v1.Pod, nodeName string) (al
...
 	bindings := b.podBindingCache.GetBindings(assumedPod, assumedPod.Spec.NodeName)
 	claimsToProvision := b.podBindingCache.GetProvisionedPVCs(assumedPod, assumedPod.Spec.NodeName)
 
+	// Start API operations
+	err := b.bindAPIUpdate(podName, bindings, claimsToProvision)
+	if err != nil {
+		return err
+	}
+
+	return wait.Poll(time.Second, b.bindTimeout, func() (bool, error) {
```
Comment (bsalamat) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: I don't know how computationally expensive `checkBindings` is. If it is expensive, running this every second may hinder Scheduler's performance. There are a couple of alternatives: 1) when a volume is bound, the status is updated on the API server. The volumeBinder watches those events and runs checkBindings only at those events. For example, BindPodVolumes runs checkBindings and calls sync.Cond.Wait when checkBinding returns false. The event handler that watches volume binding calls sync.Cond.Broadcast when a volume is bound. 2) Run this less frequently (this is obviously an inferior solution).

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: `checkBindings` will run through all the PVCs in a single Pod, get the cached PVC and PV objects from a map, and check some fields on those objects.  I would expect Pods to have <5 persistent volumes most of the time, so I would expect the most expensive work to be the cache lookups (map).

I will look into the event handling alternative.  One potential concern with a Broadcast is all the threads will wake up at the same time so there could be many spikes.

**Comment by msau42** [comment]
Added a config option for the timeout.  Will fix tests tomorrow

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 13]
```diff
@@ -249,66 +252,157 @@ func (b *volumeBinder) AssumePodVolumes(assumedPod *v1.Pod, nodeName string) (al
...
+// binding (and scheduling) needs to be retried
+func (b *volumeBinder) checkBindings(pod *v1.Pod, bindings []*bindingInfo, claimsToProvision []*v1.PersistentVolumeClaim) (bool, error) {
+	podName := getPodName(pod)
+	for _, binding := range bindings {
+		// Check for any conditions that might require scheduling retry
 
-func getPVCName(pvc *v1.PersistentVolumeClaim) string {
-	return pvc.Namespace + "/" + pvc.Name
+		// Check if pv still exists
+		pv, err := b.pvCache.GetPV(binding.pv.Name)
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: This is totally wrong. Not sure how the unit tests missed it. It should get the actual API object from the cache, not the assumed version

**Comment by msau42** [comment]
Added another commit to use condition variables to signal between cache updates and the bind goroutines.  It breaks the cache interface a little bit because I need to pass the condition variable in and it leaks some details about locking, but it's the best I could do for now.

I'll continue to stress test the change over the weekend to make sure I didn't introduce any new deadlocks or race conditions.

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 14]
```diff
@@ -277,12 +281,37 @@ func (b *volumeBinder) BindPodVolumes(assumedPod *v1.Pod) error {
...
 
-	return wait.Poll(time.Second, b.bindTimeout, func() (bool, error) {
+	bid, eventCh := b.broadcaster.Register()
+	defer b.broadcaster.Unregister(bid)
+	glog.V(5).Infof("got listener id %v", bid)
+
+	timer := time.NewTimer(b.bindTimeout)
+	defer timer.Stop()
+
+	allBound := false
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: remove

File: pkg/controller/volume/persistentvolume/scheduler_assume_cache.go [hunk 15]
```diff
@@ -156,33 +160,42 @@ func (c *assumeCache) add(obj interface{}) {
...
-	c.rwMutex.Lock()
-	defer c.rwMutex.Unlock()
-
-	if objInfo, _ := c.getObjInfo(name); objInfo != nil {
-		newVersion, err := c.getObjVersion(name, obj)
-		if err != nil {
-			glog.Errorf("add: couldn't get object version: %v", err)
-			return
+	updated := false
+	func() {
```
Comment (lichuqiang) [inline pkg/controller/volume/persistentvolume/scheduler_assume_cache.go]: Hmm, I'm not so happy with the structural changes caused by the broadcaster.
I see you are worried that the Broadcast can take long and make the cache blocked.
Maybe we can keep the code as is, and move the Broadcast() into go routine?

File: pkg/controller/volume/persistentvolume/scheduler_binder.go [hunk 16]
```diff
@@ -277,12 +281,36 @@ func (b *volumeBinder) BindPodVolumes(assumedPod *v1.Pod) error {
...
+			return err
+		}
+		if allBound {
+			glog.V(4).Infof("BindPodVolumes: all volumes bound for pod %q", podName)
+			return nil
+		}
+
+		// Wait for API updates
+		select {
+		case <-eventCh:
```
Comment (lichuqiang) [inline pkg/controller/volume/persistentvolume/scheduler_binder.go]: As we cannot tell which events are indeed related to a certain pod, what worries me most is that in production environment, there might be quite a lot of events, and `checkBindings` will be called more frequently compared to previous `Poll` func.
As a result, this may lead to performance degradation rather than promotion.

Comment (msau42) [reply pkg/controller/volume/persistentvolume/scheduler_binder.go]: You are right, this is consistent with the benchmarking results.  While elapsed time is about the same for poll vs channel, the channel method has 2% higher user CPU time under stress.  Based on this, I'm inclined to go back to the original poll method.

File: cmd/kube-scheduler/app/server.go [hunk 17]
```diff
@@ -287,6 +287,11 @@ func NewSchedulerConfig(s schedulerserverconfig.CompletedConfig) (*scheduler.Con
 		storageClassInformer = s.InformerFactory.Storage().V1().StorageClasses()
 	}
 
+	// If not set by the user, this should have been defaulted by component config defaulting
+	if s.ComponentConfig.BindTimeoutSeconds == nil {
```
Comment (bsalamat) [inline cmd/kube-scheduler/app/server.go]: This check belongs to a recently added file: https://github.com/kubernetes/kubernetes/blob/be11540775e36b1f1acdd6cb43500c1717af0ad4/pkg/scheduler/apis/config/validation/validation.go#L28

File: pkg/scheduler/api/types.go [hunk 18]
```diff
@@ -19,7 +19,7 @@ package api
 import (
 	"time"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (bsalamat) [inline pkg/scheduler/api/types.go]: nit: corev1 would be more expressive and consistent with the rest.

File: pkg/scheduler/scheduler.go [hunk 19]
```diff
@@ -281,92 +271,50 @@ func (sched *Scheduler) assumeAndBindVolumes(assumed *v1.Pod, host string) error
...
+// If binding errors, times out or gets undone, then an error will be returned to
+// retry scheduling.
+func (sched *Scheduler) bindVolumes(assumed *v1.Pod) error {
+	var reason string
+	var eventType string
+
+	glog.V(5).Infof("Trying to bind volumes for pod \"%v/%v\"", assumed.Namespace, assumed.Name)
+	err := sched.config.VolumeBinder.Binder.BindPodVolumes(assumed)
+	if err != nil {
+		glog.V(1).Infof("Failed to bind volumes for pod \"%v/%v\": %v", assumed.Namespace, assumed.Name, err)
```
Comment (bsalamat) [inline pkg/scheduler/scheduler.go]: I assume you didn't use glog.Errorf here because this is a recoverable error.

**Review by bsalamat — COMMENTED** [review]
just a few minor comments.

File: pkg/scheduler/api/types.go (hunk 18 above)
Comment (msau42) [reply pkg/scheduler/api/types.go]: actually I ended up not changing in this file, will revert

File: pkg/scheduler/scheduler.go (hunk 19 above)
Comment (msau42) [reply pkg/scheduler/scheduler.go]: I used V(1).Infof primarily because that's what `bind()` does.  But yes, this is on a retry, this may succeed.

**Review by bsalamat — APPROVED** [review]
/lgtm

for Scheduler changes

**Comment by msau42** [comment]
When I rebased, a new integration test was added that I need to update. Will work on it tomorrow

**Comment by wenlxie** [comment]
@msau42 Can you cherry-pick this pr to release-1.11 branch? 
Thanks

**Comment by msau42** [comment]
Hi @wenlxie , as this fix involves a significant design change, I don't feel comfortable backporting it into a patch release

**Comment by b0b0haha** [comment]
I‘m confused why:
> can't evaluate future pods with pod affinity/anti-affinity because the pod has not been assumed while the volumes have been decided.
what code releated to it? can somebody help me? thx.
