### PR TITLE
[Bug Fix] Allow Status Updates for Pods that can be deleted

### LINKED ISSUE #42685: e2e flake:  [k8s.io] NoExecuteTaintManager [Serial] eventually evict pod with finite tolerations from tainted nodes
Sample failures: 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/753
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/755

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:264
Mar  6 10:01:23.144: Pod wasn't evicted
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/taints_test.go:259
```

cc/ @kubernetes/sig-scheduling-bugs @gmarek

### PR DESCRIPTION
**Pull request by dashpole**
Fixes https://github.com/kubernetes/kubernetes/issues/42685#issuecomment-285238264 (at least part of it), #42776.

Running e2e node garbage collection tests on this.  Ill report in when I have results.

In the meantime, please review the change.

cc @yujuhong @dchen1107 @derekwaynecarr

### CODE REVIEW

**Comment by dashpole** [comment]
7 runs (of all 3 BC tests) without a flake.  Ill do another run, but I am seeing consistent deletion times of around 30 seconds.

File: pkg/kubelet/status/status_manager.go [hunk 1]
```diff
@@ -414,7 +414,7 @@ func (m *manager) syncBatch() {
 
 // syncPod syncs the given status with the API server. The caller must not hold the lock.
 func (m *manager) syncPod(uid types.UID, status versionedPodStatus) {
-	if !m.needsUpdate(uid, status) {
+	if !m.needsUpdate(uid, status) && !m.couldBeDeleted(uid, status.status) {
```
Comment (feiskyer) [inline pkg/kubelet/status/status_manager.go]: Add a comments explains the logic?

**Comment by dashpole** [comment]
another 6 runs without a flake.

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (dashpole) [inline pkg/kubelet/status/status_manager.go]: Done.

File: pkg/kubelet/status/status_manager.go [hunk 2]
```diff
@@ -414,7 +414,8 @@ func (m *manager) syncBatch() {
 
 // syncPod syncs the given status with the API server. The caller must not hold the lock.
 func (m *manager) syncPod(uid types.UID, status versionedPodStatus) {
-	if !m.needsUpdate(uid, status) {
+	// always allow status updates if the pod can be deleted.
+	if !m.needsUpdate(uid, status) && !m.couldBeDeleted(uid, status.status) {
```
Comment (yujuhong) [inline pkg/kubelet/status/status_manager.go]: This is still fragile since you have to keep the code at two places in sync. Maybe add another method dedicated for the check?

**Comment by smarterclayton** [comment]
/approve

Given comments in issue and that it is a bug

File: pkg/kubelet/status/status_manager.go (hunk 2 above)
Comment (dashpole) [inline pkg/kubelet/status/status_manager.go]: What about moving it inside needsUpdate?  Then it would only be in one place.

Comment (yujuhong) [inline pkg/kubelet/status/status_manager.go]: SGTM.

Comment (dchen1107) [inline pkg/kubelet/status/status_manager.go]: +1

Comment (dashpole) [inline pkg/kubelet/status/status_manager.go]: done

**Comment by dchen1107** [comment]
/lgtm

@dashpole Can you also introduce a pod deletion test to node e2e?  I observed a lot of deletion regression lately. Hope the test can help us to catch the regression earlier. Thanks!

**Comment by yujuhong** [comment]
@k8s-bot bazel test this

**Comment by dashpole** [comment]
@k8s-bot cvm gce e2e test this

**Comment by dashpole** [comment]
I ran another set of GC tests on the latest version of this PR just as a sanity check.  It passed.

**Comment by dchen1107** [comment]
All tests are passed. I plan to manually merge this to stop the bleeding submit-queue in 5 mins. Of course there are other flakiness.
