### PR TITLE
Skip check for all topology labels when using system default spreading

### LINKED ISSUE #102136: "scheduler: non-compatible change in default topology spread constraints"
#### What happened:

From v1.19, the scheduler use `PodTopologySpread` plugin to do default spreading, with the following constraints, and the original `SelectorSpread` is disabled by default.

```yaml
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: kubernetes.io/hostname
  maxSkew: 3
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 5
```
These default constraints suppose nodes have a `topology.kubernetes.io/zone` label. The algorithm will ignore nodes that don't have all the required topology keys presented when scoring.  

https://github.com/kubernetes/kubernetes/blob/ee9f365c519423d8693c6a9891ef8c5c47ebe475/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L77-L82

However, in many on-premise clusters,  those labels are not added by default and no guaranteed to exist, which leads to the `PodTopologySpread` will not take effect at all.   

In a worse case, If we assign a `NodeResourcesMostAllocated` plugin and the `PodTopologySpread` do not take effect as described above,  the `NodeResourcesMostAllocated` will dominate the scheduling and be likely to bind all pods belonging to ReplicaSets to the same node, which will lead to low availability and is not accepted by our user.

In the `SelectorSpread` plugin, we have already taken care of this case: 

https://github.com/kubernetes/kubernetes/blob/ee9f365c519423d8693c6a9891ef8c5c47ebe475/pkg/scheduler/framework/plugins/selectorspread/selector_spread.go#L153-L154

When changed to `PodTopologySpread`, we do not care zome, so are not compatible with the original behavior.

#### What you expected to happen:

the default `PodTopologySpread` plugin should take care of the case in which nodes do not have zone labels and work properly.

#### How to reproduce it (as minimally and precisely as possible):

create a deployment in a cluster whose nodes do not have zone labels and observe the default spreading.

#### Environment:
- Kubernetes version (use `kubectl version`):
master branch

/assign 
/sig scheduling

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Skip check for all topology labels when using system default spreading

Checking for all topology labels is not backwards compatible. Clusters were nodes don't have zone labels effectively have default spreading disabled.

Change only applies to system defaults.

/sig scheduling

#### Which issue(s) this PR fixes:

Fixes #102136

#### Special notes for your reviewer:

This replaces #102383 (the contributor abandoned).

One thing to note is the behavior when _some_ nodes have zones. The scoring would favor nodes with no zone. We should consider this as undefined behavior.

#### Does this PR introduce a user-facing change?

```release-note
Fix regression in 1.19+ in scheduler system default topology spreading when nodes don't have zone labels. Pods correctly spread by default now.
```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go [hunk 1]
```diff
@@ -427,6 +433,40 @@ func TestPodTopologySpreadScore(t *testing.T) {
...
+				st.MakePod().Name("p-b3").Node("node-b").Label("foo", "").Obj(),
+				st.MakePod().Name("p-c1").Node("node-c").Label("foo", "").Obj(),
+				st.MakePod().Name("p-c2").Node("node-c").Label("foo", "").Obj(),
+				st.MakePod().Name("p-d1").Node("node-d").Label("foo", "").Obj(),
+			},
+			nodes: []*v1.Node{
+				st.MakeNode().Name("node-a").Label(v1.LabelHostname, "node-a").Obj(),
+				st.MakeNode().Name("node-b").Label(v1.LabelHostname, "node-b").Obj(),
+				st.MakeNode().Name("node-c").Label(v1.LabelHostname, "node-c").Obj(),
+				st.MakeNode().Name("node-d").Label(v1.LabelHostname, "node-d").Obj(),
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go:456]: For curiosity: in addition to zone label, should we consider the case that all or partial nodes don't carry standard host label?

**Review by Huang-Wei — COMMENTED** [review]
Some nits. LGTM overall.

File: pkg/scheduler/framework/plugins/podtopologyspread/plugin.go [hunk 2]
```diff
@@ -53,6 +53,7 @@ var systemDefaultConstraints = []v1.TopologySpreadConstraint{
 
 // PodTopologySpread is a plugin that ensures pod's topologySpreadConstraints is satisfied.
 type PodTopologySpread struct {
+	isSystemDefaulted  bool
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/podtopologyspread/plugin.go:56]: Done

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go [hunk 3]
```diff
@@ -125,7 +125,11 @@ func (pl *PodTopologySpread) PreScore(
 		IgnoredNodes:            sets.NewString(),
 		TopologyPairToPodCounts: make(map[topologyPair]*int64),
 	}
-	err = pl.initPreScoreState(state, pod, filteredNodes)
+	// Only require that nodes have all the topology labels if using not
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring.go:128]: Done

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go:456]: Is that even possible? It seems that kubelet takes care of it https://kubernetes.io/docs/reference/labels-annotations-taints/#kubernetesiohostname

Interestingly, given that we special-case hostname to do the count in `Score` (instead of `PreScore`), we could make it work. However, I don't think we need to support that.

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go:456]: > Is that even possible?

I was just curious. Personally I'm with you to believe it's sane defaults for every cluster.
