### PR TITLE
Fix kube-proxy nftables crash with newer nftables versions

### LINKED ISSUE #136786: kube-proxy fails to sync in nftables mode when newer nftables sets exist
### What happened?

kube-proxy crashes repeatedly, causing the container network to not function.
```
E0205 20:24:21.385767       1 proxier.go:1217] "Failed to list existing sets" err="failed to run nft: signal: segmentation fault (core dumped)" ipFamily="IPv4"
E0205 20:24:22.721950       1 proxier.go:1788] "nftables sync failed" err="signal: segmentation fault (core dumped)" ipFamily="IPv4"
I0205 20:24:22.723136       1 proxier.go:1143] "Sync failed" ipFamily="IPv4" retryingTime="30s"
E0205 20:24:23.698591       1 proxier.go:1217] "Failed to list existing sets" err="failed to run nft: signal: segmentation fault (core dumped)" ipFamily="IPv6"
E0205 20:24:24.761438       1 proxier.go:1788] "nftables sync failed" err="signal: segmentation fault (core dumped)" ipFamily="IPv6"
I0205 20:24:24.761928       1 proxier.go:1143] "Sync failed" ipFamily="IPv6" retryingTime="30s"
```

### What did you expect to happen?

kube-proxy should correctly setup nftables rules.

### How can we reproduce it (as minimally and precisely as possible)?

Run a container in the host namespace with a newer version of nftables (1.1.3+), for example Fedora 43. Add a nft set in the container:
```
nft add table test_table
nft add set test_table test_set '{ type ifname; elements = { "test" } }'
```

Then delete the kube-proxy pod on the host, and example the logs on the new pod.

### Anything else we need to know?

kube-proxy in nftables mode crashes repeatedly on hosts where newer versions of nftables (eg 1.1.3) have created sets in the same network namespace.

I found a fix for the crash in newer nftables here (it appears to be related to udata being present on newer nft sets):
https://git.netfilter.org/nftables/commit/?id=be737a1986bfee0ddea4bee7863dca0123a2bcbc

It's probably a good idea to build kube-proxy with a patched version of nftables to avoid the crash, but not use anything newer than nftables 1.1.1 as it could then potentially break other unpatched nftables in CNIs etc.

### Kubernetes version

<details>

```console
Client Version: v1.34.3
Kustomize Version: v5.7.1
Server Version: v1.34.3
```

</details>

Also crashes on v1.35.0, and probably older versions.

### Cloud provider

<details>
None: bare metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="43 (Forty Three)"
RELEASE_TYPE=stable
$ uname -a
Linux fedora 6.18.7-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 23 16:42:34 UTC 2026 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by kairosci**
## What this PR does / why we need it

Fixes kube-proxy crashes on systems with nftables 1.1.3+ due to segmentation faults when listing nftables sets with udata support.

## Which issue this PR fixes (if applicable)

Fixes #136786

## Special notes for reviewers

This fix addresses the crash without requiring patches to nftables itself, making kube-proxy robust across different nftables versions.

## Checklist
- [x] All tests pass
- [x] No workarounds - proper solution using upstream updates
- [x] Backward compatible with older nftables versions

#### Does this PR introduce a user-facing change?
```release-note
Fixes kube-proxy's nftables mode to work on systems with nft 1.1.3.
```

### CODE REVIEW

File: pkg/proxy/nftables/proxier.go [hunk 1]
```diff
@@ -1012,6 +1012,32 @@ func (proxier *Proxier) logFailure(tx *knftables.Transaction) {
 	}
 }
 
+// listNFTablesObjects safely lists nftables objects with a 5-second timeout.
+// This prevents hangs when certain nftables versions encounter incompatible set features.
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go]: the issue only talks about a crash, not a hang, though I guess the logs don't show enough to say for sure if it's hanging too... is it taking longer than 5 seconds to crash? If so, how long?

File: go.mod [hunk 2]
```diff
@@ -115,7 +115,7 @@ require (
 	k8s.io/system-validators v1.12.1
 	k8s.io/utils v0.0.0-20260108192941-914a6e750570
 	sigs.k8s.io/json v0.0.0-20250730193827-2d320260d730
-	sigs.k8s.io/knftables v0.0.17
+	sigs.k8s.io/knftables v0.0.19
```
Comment (danwinship) [inline go.mod]: any specific reason you bumped the dependency?

Comment (kairosci) [reply go.mod]: Bump needed to support the latest versions of nftables.
Knftables v0.0.19 adds support for `Destroy()` and `Counter` objects, as well as various parsing bug fixes that resolve the crash we were experiencing.

File: pkg/proxy/nftables/proxier.go (hunk 1 above)
Comment (kairosci) [reply pkg/proxy/nftables/proxier.go]: Yes, the problem is both crashes and hangs. 
With certain versions of nftables, the call to `List()` hangs indefinitely (it didn't crash, it just hung).

I added the 5-second timeout precisely because we saw that it could stay stuck for much longer. 
If the timeout expires, we return an empty list and recreate the chains at the next sync, so the proxier remains responsive.

File: go.mod (hunk 2 above)
Comment (danwinship) [reply go.mod]: What crash were you experiencing?

There are not any intentional parsing bug fixes between knftables v0.0.17 and v0.0.19 other than in knftables.Fake, or involving features we're not using in kube-proxy.

File: pkg/proxy/nftables/proxier.go [hunk 3]
```diff
@@ -1012,6 +1012,32 @@ func (proxier *Proxier) logFailure(tx *knftables.Transaction) {
...
+	defer cancel()
+
+	result := make([]string, 0)
+	done := make(chan error, 1)
+
+	go func() {
+		var err error
+		result, err = proxier.nftables.List(timeoutCtx, objectType)
+		done <- err
+	}()
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go]: (The goroutine should not be necessary here; `proxier.nftables.List` should immediately return an error if `timeoutCtx` expires.)

File: pkg/proxy/nftables/proxier.go [hunk 4]
```diff
@@ -1012,6 +1012,32 @@ func (proxier *Proxier) logFailure(tx *knftables.Transaction) {
 	}
 }
 
+// listNFTablesObjects safely lists nftables objects with a 5-second timeout.
+// This prevents hangs when certain nftables versions encounter incompatible set features.
+// If the timeout is exceeded, an empty list is returned and chains/sets are recreated
+// on the next sync iteration.
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go]: This means we will never do cleanup of stale chains/sets though.

Not to mention it will add 5 seconds to every sync...

I think we can fix this problem by [changing how `nft.List` works](https://github.com/kubernetes/kubernetes/issues/136786#issuecomment-3860612295), and that will be overall a cleaner solution.

File: pkg/proxy/nftables/proxier.go (hunk 3 above)
Comment (kairosci) [reply pkg/proxy/nftables/proxier.go]: Ok, Then I change my approach, modifying the nftables file directly.

File: go.mod (hunk 2 above)
Comment (kairosci) [reply go.mod]: The crash was a segfault in the `nft` CLI when kube-proxy listed chains/sets across all tables (via `nft --json list chains/sets ip`). It would hit objects from other tables and crash. Listing only our table avoids that path.

**Comment by kairosci** [comment]
I believe I took the right approach this time, PTAL, thanks!

File: vendor/OWNERS [hunk 5]
```diff
@@ -1,9 +0,0 @@
-# See the OWNERS docs at https://go.k8s.io/owners
```
Comment (BenTheElder) [inline vendor/OWNERS:1]: This file should not be deleted, and you cannot just modify vendor manually.

**Review by BenTheElder — CHANGES_REQUESTED** [review]
Update go.mod in the repo root and then run hack/update-vendor.sh

We have checks that ensures vendor isn't deviating from upstreams and that all our modules are updated appropriately.

Prefer to do vendor changes as a separate commit from the other changes so they can be reviewed independently.

File: vendor/OWNERS (hunk 5 above)
Comment (kairosci) [reply vendor/OWNERS:1]: Restored.

**Review by BenTheElder — COMMENTED** [review]
/approve
for vendor/ changes

Suggest we rebase out the intermediate commit with Dan's fork.

**Comment by kairosci** [comment]
All CI are green. 

@danwinship , @BenTheElder PTAL, thanks!

File: pkg/proxy/nftables/proxier.go [hunk 6]
```diff
@@ -1109,24 +1109,22 @@ func (proxier *Proxier) syncProxyRules() (retryError error) {
...
+		for _, set := range allObjects["set"] {
 			if isAffinitySetName(set) {
 				existingAffinitySets.Insert(set)
 			}
 		}
 	} else {
-		proxier.logger.Error(err, "Failed to list existing sets")
+		proxier.logger.Error(err, "Failed to list existing nftables objects")
+		existingChains = sets.New[string]()
+		existingAffinitySets = sets.New[string]()
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier.go]: you don't need to initialize them like this; `nil` will work correctly as a (read-only) `sets.Set`

File: pkg/proxy/nftables/proxier_test.go [hunk 7]
```diff
@@ -459,6 +459,75 @@ func TestOverallNFTablesRules(t *testing.T) {
 	assertNFTablesTransactionEqual(t, getLine(), expected, nft.Dump())
 }
 
+// TestListChainsAndSetsEmptyInitialization tests that when there are no existing
+// chains/sets (empty list), the proxier correctly initializes the collections.
+// Regression test for a crash that occurred when using ListObjects() across all tables.
```
Comment (danwinship) [inline pkg/proxy/nftables/proxier_test.go]: This isn't a regression test though, because `NewFakeProxier` creates a proxier based on `knftables.Fake`, which doesn't use the `nft` binary. So the test case would pass just as well with kfntables v0.0.17.

The existing unit and e2e tests would already fail if `ListAll` wasn't returning the expected values, so we don't need a new unit test for this PR.

(And the two whitespace changes in this file seem unintentional and aren't needed, so you can just revert all the changes to this file.)

**Review by danwinship — CHANGES_REQUESTED** [review]

File: pkg/proxy/nftables/proxier_test.go (hunk 7 above)
Comment (kairosci) [reply pkg/proxy/nftables/proxier_test.go]: So do I remove the test?

Comment (danwinship) [reply pkg/proxy/nftables/proxier_test.go]: yes

Comment (kairosci) [reply pkg/proxy/nftables/proxier_test.go]: Done!

Comment (kairosci) [reply pkg/proxy/nftables/proxier_test.go]: Done!

Comment (kairosci) [reply pkg/proxy/nftables/proxier_test.go]: Done!
