### PR TITLE
Fix make test-integration under OSX

### LINKED ISSUE #31587: Can not run make test-integration
When running `make test-integration`, I got the following errors. Did I miss anything?

```
$ make test-integration
+++ [0828 17:19:43] Checking etcd is on PATH
/Users/klaus/Workspace/kubernetes/third_party/etcd/etcd
+++ [0828 17:19:43] Starting etcd instance
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /var/folders/c3/x5_ln0h55lv6l13ncsl34n400000gn/T/tmp.nzTFdi9w --listen-client-urls http://127.0.0.1:2379 --debug > "/dev/null" 2>/dev/null
Waiting for etcd to come up.
+++ [0828 17:19:44] On try 2, etcd: : http://127.0.0.1:2379
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":4,"createdIndex":4}}
+++ [0828 17:19:44] Running integration test cases
Running tests for APIVersion: v1,authorization.k8s.io/v1beta1,autoscaling/v1,batch/v1,apps/v1alpha1,policy/v1alpha1,extensions/v1beta1,rbac.authorization.k8s.io/v1alpha1,certificates/v1alpha1
+++ [0828 17:19:50] Running tests without code coverage
can't load package: package k8s.io/kubernetes/test/integration/metrics: no buildable Go source files in /Users/klaus/Workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/metrics
make[1]: *** [test] Error 1
+++ [0828 17:19:50] Cleaning up etcd
+++ [0828 17:19:50] Integration test cleanup complete
make: *** [test-integration] Error 1
```

### PR DESCRIPTION
**Pull request by dims**
Just throw in a doc.go so there's something compilable in the
test/integration/metrics directory.

Fixes #31587

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31593)

### CODE REVIEW

**Comment by k82cn** [comment]
@dims , thanks for your quick fix. Just one question as newbee : is it the original purpose of "doc.go" in other directories?

**Comment by k82cn** [comment]
The patch lgtm :); test passed on Mac (Darwin).

File: test/integration/metrics/doc.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+/*
+Copyright 2015 The Kubernetes Authors.
```
Comment (spxtr) [inline test/integration/metrics/doc.go]: It's 2016 :)

**Comment by spxtr** [comment]
LGTM after nit

**Comment by dims** [comment]
@spxtr thanks fixed.
