### PR TITLE
Fix for race condition caused by concurrent fsnotify (CREATE and REMOVE) in kubelet/plugin_watcher.go

### LINKED ISSUE #71424: CSI: kubelet removes NodeID annotation when a driver is restarted
**What happened**:
When I restart pod with my driver and driver-registrar, node looses NodeID annotation.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Kubernetes without any alpha features (local-up-cluster.sh in this case)

2. Start HostPath driver
    ```
    kubectl create serviceaccount csi-node-sa
    kubectl create serviceaccount csi-attacher
    kubectl apply -f test/e2e/testing-manifests/storage-csi/hostpath/hostpath/
    ```

3. Wait for everything to be Running

4. Check the node has annotation
    ```
    kubectl get node -o yaml

    annotations:
      csi.volume.kubernetes.io/nodeid: '{"csi-hostpath":"127.0.0.1"}'
    ```

4. Delete the node pod (deleting all pods here, we don't care about attacher/provisioner).
    ```
    kubectl delete pod --all
    ```
   
5. DaemonSet will start a new node pod with new registrar. Wait until the new pod gets Running.

6. Check the node **does not have the annotation**
    ```
    kubectl get node -o yaml

     <no annotations>
    ```

It's ~~100%~~ 80% reproducible in my local cluster. New driver-registrar deletes socket of the old registrar and creates new one. I can see in logs:

```
I1126 16:48:23.914792   31674 plugin_watcher.go:347] DeRegistering plugin {CSIPlugin csi-hostpath} at path /var/lib/kubelet/plugins_registry/csi-hostpath-reg.sock
I1126 16:48:23.914886   31674 csi_plugin.go:227] kubernetes.io/csi: registrationHandler.DeRegisterPlugin request for plugin csi-hostpath
I1126 16:48:23.919670   31674 csi_plugin.go:116] kubernetes.io/csi: Trying to validate a new CSI Driver with name: csi-hostpath endpoint: /var/lib/kubelet/plugins/csi-hostpath/csi.sock versions: 1.0.0, foundInDeprecatedDir: false
I1126 16:48:23.919756   31674 csi_plugin.go:137] kubernetes.io/csi: Register new plugin with name: csi-hostpath at endpoint: /var/lib/kubelet/plugins/csi-hostpath/csi.sock
```

So the old socket was deregistered very shortly before new one got registered. IMO these two operations collide with each other and the deregistration "wins" somehow.

**Environment**:
- Kubernetes version (use `kubectl version`): today's master

/kind bug
/sig storage

@saad-ali @bertinatto @msau42 @vladimirvivien @verult @davidz627

### PR DESCRIPTION
**Pull request by vladimirvivien**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes a race condition that can cause CSI annotations added to Node API object to suddenly disappear after a driver-registrar pod has been deleted and recreated by replica controller (see https://github.com/kubernetes/kubernetes/issues/71424 for detail). 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71424 

**Does this PR introduce a user-facing change?**: NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
This code changes fixes the race condition that can surface due to concurrent nfsnotify CREATE and DELETE events occurring concurrently.  This can cause CSI driver operations that rely on CREATE and DELETE to be triggered out of sync. 

### Investigation
The fix was tested primarily using the kubernetes/hack/local-up-cluster.sh script.  With each script run the following steps were done:

**Deploy:**
```shell
kubectl create serviceaccount csi-node-sa
kubectl create serviceaccount csi-attacher
kubectl apply -f test/e2e/testing-manifests/storage-csi/hostpath/hostpath/
```

**Clean:**
```shell
sudo mount | grep kubelet
sudo umount /var/lib/kubelet/<path>
sudo rm -rf /var/lib/kubelet
rm /tmp/kube*
```

**Prior to fix**
Prior to the fix, I ran the code 10 times using the local-up-cluster script. The results were consistent with the issue identified in #71424  where the CSI node annotations would disappear, an not updated, after a pod delete (and pod redeploy):

```
 1. local-up-cluster, <deploy>, annotation present, delete all pods, annotation missing, shutdown, <clean>
 2. local-up-cluster, <deploy>, annotation present, delete all pods, annotation missing, shutdown, <clean>
 3. local-up-cluster, <deploy>, annotation present, delete all pods, annotation missing, shutdown, <clean>
 4. local-up-cluster, <deploy>, annotation present, delete all pods, annotation present, shutdown, <clean>
 5. local-up-cluster, <deploy>, annotation present, delete all pods, annotation present then missing, shutdown, <clean>
 6. local-up-cluster, <deploy>, annotation present, delete all pods, annotation missing, shutdown, <clean>
 7. local-up-cluster, <deploy>, annotation present, delete all pods, annotation present then missing, shutdown, <clean>
 8. local-up-cluster, <deploy>, annotation present, delete all pods, annotation present then missing, shutdown, <clean>
 9. local-up-cluster, <deploy>, annotation present (after 10+ secs), delete all pods, annotation present, shutdown, <clean>
10. local-up-cluster, <deploy>, annotation present, delete all pods, annotation present then missing, shutdown, <clean>
```
### Fix
The fix was to force the handling of the fsnotify CREATE and DELET events serially.  After the code was fixed, the CSI node annotation consistently appeared back on the node after a lost (and subsequent redeployment) of a driver-registrar sidecar:
```
1. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
2. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
3. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
4. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
5. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
6. local-up-cluster, <deploy>, annotation present (10x), delete all pods, annotation present (10x), shutdown, <clean>
```

**Comment by msau42** [comment]
Iiuc, this means that the handler for each module (ie CSI or device plugin) will run the handlers serially.  We should double check that the CSI handlers won't block for too long and that this is an acceptable limitation for device plugin

**Comment by vladimirvivien** [comment]
@msau42 Yes that is a good point since both module share the same process queue.  This is a safe solution for CSI handler. During Handle.RegisterPlugin, CSI's longest execution path are calls to the API server and to the backing storage driver itself both of which have timeouts.  

Maybe a future solution, in the near future, is to give each module types (CSI, device plugin) its own process queue.

**Comment by saad-ali** [comment]
Seems like a reasonable fix for now. Thanks @vladimirvivien.

/assign @vishh 
/assign @liggitt

**Comment by krmayankk** [comment]
Is there a way to add tests for these kinds of scenarios in e2e ?

**Comment by bertinatto** [comment]
I tested this with the EBS plugin and it solved the problem that I had.

**Comment by vladimirvivien** [comment]
@krmayankk this was a race issue (not functionality) that would have been a bit hard to detect.

**Comment by msau42** [comment]
#70439 adds an e2e test for this

**Comment by msau42** [comment]
Oops https://github.com/kubernetes/kubernetes/pull/70578

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 1]
```diff
@@ -111,7 +111,7 @@ func (w *Watcher) Start() error {
 				//TODO: Handle errors by taking corrective measures
 
 				w.wg.Add(1)
-				go func() {
+				func() {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: the goroutine inside traversePluginDir also makes order of events non-deterministic, especially if changes are occurring at the same time the initial scan is being done.

Comment (liggitt) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: does the handleCreateEvent function verify the created path still exists?

Comment (vladimirvivien) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: The `goroutine`in `traversePluginDir` is used to place items on a non-buffered channel, `ws.fsWatcher.Events`.  If must be present to avoid deadlocks.

**Comment by vishh** [comment]
Handling serially should be fine for current and future plugin types. I don't expect plugins to have a lot of churn or volume (# of plugins).

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (vishh) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: > the fsnotify CREATE/DELETE operations should not occur out of sync

That is the expectation from the underlying library. Just to be safe, it will be worth catching any potential issue around delete after create operations and logging it.

Comment (liggitt) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: > With the changes in this PR, the fsnotify CREATE/DELETE operations should not occur out of sync. If a dir existed right before Registration, it should not go away until a DELETE event comes right after it.

nothing guarantees that, correct?

1. traversePluginDir is called
2. traversePluginDir adds a filesystem watch to a particular directory

    https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L205-L212

3. traversePluginDir descends into the directory and adds synthetic Create events for the files found in the dir via a goroutine

    https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L215-L221

because there is an active watcher registered in step 2 that can immediately start delivering events, and the synthetic create events in step 3 are delivered via a goroutine, they can interleave with actual observed filesystem events in non-deterministic ways. For example, if a driver is being deleted while this runs:

1. filepath.Walk lists dir, sees driver socket file
2. driver socket file is deleted
3. filesystem delete event is observed and queued
4. filepath.Walk queues synthetic create event

because the delete is handled, then the synthetic create event, could we end up with a registered driver that doesn't actually exist any more?

**Comment by liggitt** [comment]
> Handling serially should be fine for current and future plugin types. I don't expect plugins to have a lot of churn or volume (# of plugins).

agree, I'm not concerned by making this bit serial. I am concerned that there is still a race between the synthetic create events from traversePluginDir interleaved with immediately-observed filesystem events from the registered handlers

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (vishh) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: To guarantee consistency, shouldn't you be enqueuing existing sockets first prior to accepting fsnotify events from the kernel? Imagine a situation where a socket was identified by path traversal, but before `traversePluginDir` can enqueue a create event, the socket get's deleted and that event gets processed first before the creation event?

Comment (liggitt) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: that's what I expected as well. registering watches on the dirs, processing the contents and enqueuing synthetic create events, then starting processing of the events from the registered watchers

Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Witht

Comment (vladimirvivien) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: @liggitt @vishh I think the code already has `HappensBefore` and `HappensAfter` serial properties that you are alluding to.  The code seems to have 1to1 parity between observed filesystem event and synthetic queued events.  To explain, let's further unpack the scenario that Jordan presented earlier:

> 1. `filepath.Walk` lists dir, sees driver socket file

So let's look at some scenarios
1. filepath.Walk hits dir, adds watcher for it, continue
2.  filesystem creates socket file (from driver)
  a. But, socket file is `immediately deleted` from filesystem
  b. According to fswatcher, if the file is removed before it is observed, the Walk will generate an error
3. filepath.Walk receives error because watcher is missing, returns

Scenario 2
1. filepath.Walk hits dir, adds watcher for it, continue
2.  filesystem creates socket file (from driver)
3. filepath.Walk receives socket file info (prior to deletion)
  a. queues synthetic create event
4. Socket file is from filesystem
5. filepath.Walk receives deleted file info (after deletion)
  a. enqueues the observed delete event 

Because there is a sequentiality between the creation and immediate deletion of the socket files, the observed events will have before/after relationships.  Therefore, the synthetic events are generated and placed on the internal event queue (fsWatcher.Events) should also inherit that sequentiality.

Comment (liggitt) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: the scenario described in https://github.com/kubernetes/kubernetes/pull/71440#discussion_r236798644 is still racy

The synthetic create events traversePluginDir sends to the channel (for socket files encountered by filepath.Walk) are independent of (and can race with) create/delete events sent to the channel by the registered filesystem watchers.

That said, if a synthetic create event *was* processed after an actual observed delete event, handleCreateEvent *does* verify the created path still exists:

https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/kubelet/util/pluginwatcher/plugin_watcher.go#L240-L243

I still think the raciness should be fixed in a follow up because it makes the event flow hard to understand and relies on compensation in the event handler, but in the context of this PR, it is not unsafe.

**Comment by saad-ali** [comment]
Required release note: `If kubelet plugin registration for a driver fails, kubelet will not retry. The driver must delete and recreate the driver registration socket in order to force kubelet to attempt registration again. Restarting only the driver container may not be sufficient to trigger recreation of the socket, instead a pod restart may be required.`

**Comment by vishh** [comment]
@saad-ali you wrote:

> instead a pod restart may be required.

What do you mean by pod restart? Shouldn't it be `deleting the pod` instead?

**Comment by AishSundar** [comment]
@marpaia @dstrebel for adding the [Known issue](https://github.com/kubernetes/kubernetes/pull/71440#issuecomment-442258737) to Release notes

```
I still think the raciness should be fixed in a follow up because it makes the event flow hard to understand and relies on compensation in the event handler, but in the context of this PR, it is not unsafe.
```
@vishh  @liggitt did you want the pending raciness during initialization fixed in a followup PR for 1.13 or are we ok mentioning this as a known issue and proceed to address in 1.14? Speaking to @saad-ali looks like this is edge case that was caught in code review vs actual repro during manual testing. This probably reduces the chances of a real user hitting this, but would like to know your final evaluation of its severity.

**Comment by liggitt** [comment]
Known issue and post-1.13.0 follow up is fine

**Comment by liggitt** [comment]
The known issue is not actually a raciness issue, will coordinate on the known issue text

**Comment by vishh** [comment]
As another AI, I feel we need to have some unit testing in place for the
plugin watcher component to simulate races. It should be possible to create
and delete temporary files locally to simulate real world scenarios.
