### PR TITLE
Fix init order during starup for dynamic kubelet config

### LINKED ISSUE #83183: Dynamic kubelet config metrics missing
**What happened**:
The kubelet metrics related to [Dynamic kubelet config](https://github.com/kubernetes/enhancements/issues/281), except for one, are missing from the kubelet metric endpoint.

This applies to these metrics:
```
kubelet_node_config_assigned
kubelet_node_config_active
kubelet_node_config_last_known_good
```

**What you expected to happen**:

I expect that the metrics mentioned above should be found in the `/metrics` endpoint on the kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

Run kubelet with a valid `--dynamic-config-dir`, and `--feature-gates=DynamicKubeletConfig=true` (defaults to true).

or run the node e2e tests: `make test-e2e-node PARALLELISM=1 REMOTE=true TEST_ARGS='--feature-gates=DynamicKubeletConfig=true' FOCUS="DynamicKubeletConfig" SKIP=""`

**Anything else we need to know?**:

All e2e tests related to DynamicKubeletConfig fails in master (and in v1.16): https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

This bug/error was introduced in https://github.com/kubernetes/kubernetes/pull/81534

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.16` && `master`
- Cloud provider or hardware configuration: `N/A`
- OS (e.g: `cat /etc/os-release`): `N/A`
- Kernel (e.g. `uname -a`): `N/A`
- Install tools: `N/A`
- Network plugin and version (if this is a network-related bug): `N/A`
- Others: `N/A`

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #83183

**Special notes for your reviewer**:
~This is just a "proof of concept" fix in order to make it easier to understand the problem. From what I understand it does work, and all the tests pass, but I don't think the is the correct solution long term. If this makes sense and works, I guess
we can use this fix on the v1.16 branch to mitigate the problem.~

The probelm is essentially that the sync function changed in the PR is executed before the kubelet is started and the metrics are "Created" with the way #81534 works.

If the metrics ain't created, the values will not be registered, and the
metrics will not be visible in the metric endpoint.

Feel free to change the priority; but since this breaks all the related tests, and the metrics are missing, I guess this is ok
/priority critical-urgent
/sig node

**Does this PR introduce a user-facing change?**:

```release-note
Fix error where metrics related to dynamic kubelet config isn't registered
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by odinuge** [comment]
As you see here, the node e2e tests (running with `FOCUS="DynamicKubeletConfig" SKIP=""`) pass (not that they take 2hours to run :sweat_smile:).
Screenshot from 2019-09-25 19-30-25

Non of them pass in master: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

/cc @alejandrox1

**Comment by logicalhan** [comment]
If I understand this correctly, then the metrics do show up eventually, right? Once the kubelet is created, then then metrics should reflect the syncs.

File: pkg/kubelet/kubeletconfig/status/status.go [hunk 1]
```diff
@@ -172,6 +173,11 @@ func (s *nodeConfigStatus) Sync(client clientset.Interface, nodeName string) {
 		status = status.DeepCopy()
 		status.Error = s.errorOverride
 	}
+	// Fail sync, and then retry later, in case the metrics are not created
```
Comment (logicalhan) [inline pkg/kubelet/kubeletconfig/status/status.go]: What this code is doing, at the moment, is acting as a proxy signal for kubelet initialization. I'm a bit puzzled by the current behavior. Shouldn't sync return an error if the kubelet isn't initialized anyhow?

Comment (odinuge) [reply pkg/kubelet/kubeletconfig/status/status.go]: Thanks for the quick answer @logicalhan!

> What this code is doing, at the moment, is acting as a proxy signal for kubelet initialization. I'm a bit puzzled by the current behavior. Shouldn't sync return an error (hence retry at some future point) if the kubelet isn't initialized anyhow?

This code, the `Sync` is executed (or rather, the goroutine is dispatched) during init here: https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L595, while the metrics are registered in the same function here (ofc. further down the chain): https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L720, that leads to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1320.

I have wrapped my head around quite a few times, and from what I can see, will _only_ rerun if it results in an error. The func `Sync` will from what I understand run, but bacuase of https://github.com/kubernetes/kubernetes/pull/83184/files#diff-38e08440e8c8014419f673640b8cc03fL139, it will only run once. The only to places where we write (from what I have found) is when `Sync` fails, https://github.com/kubernetes/kubernetes/pull/83184/files#diff-38e08440e8c8014419f673640b8cc03fL156, and when creating the struct here https://github.com/kubernetes/kubernetes/pull/83184/files#diff-38e08440e8c8014419f673640b8cc03fR84.

I guess this makes sense, since kubelet restarts when a new config appears. There is still a lot of extra boiler plate, so there may have been some thoughts behind it. I also guess you @logicalhan have way better knowledge about this than me, so I may be wrong. :sweat_smile: 



Here is btw. the reason why the metrics are lost. This is a part of the new way to handle deprecation etc. of metrics, so it looks like we have to resolve this issue here, and not in the metrics system. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/gauge.go#L132. But those working on the new metrics may have some input tho.

Comment (odinuge) [reply pkg/kubelet/kubeletconfig/status/status.go]: I see no logical issues with the code here, other than the fact that we know it will fail atleast once (aka. bad design). From what I understand, it has to be executed after the metrics have been initialized correctly here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/metric.go#L133

**Comment by odinuge** [comment]
> @logicalhan If I understand this correctly, then the metrics do show up eventually, right? Once the kubelet is created, then then metrics should reflect the syncs.

I think https://github.com/kubernetes/kubernetes/pull/83184#discussion_r328954605 answers this question.
Also, the tests using the metrics in master still fails, so it looks like they never appear.

File: pkg/kubelet/kubeletconfig/status/status.go (hunk 1 above)
Comment (logicalhan) [reply pkg/kubelet/kubeletconfig/status/status.go]: Why can't we just move https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L593-L598 down to below where the kubelet is actually initialized?

Comment (logicalhan) [reply pkg/kubelet/kubeletconfig/status/status.go]: Metrics are lazily instantiated now to allow us to disable them. We've had issues in the past with high cardinality metrics (https://github.com/kubernetes/kubernetes/issues/73587). In order to disable metrics, we need to no-opt creation of metrics until they actually become registered, which is the current behavior. We can force metrics initialization like so (https://github.com/logicalhan/kubernetes/compare/master...kubelet-metrics-force-initialization), but I really don't want to do that. It looks to me that these tests are failing because they are literally testing that the metrics are immediately registered. That seems like a weird thing to test.

**Comment by logicalhan** [comment]
> Why can't we just move https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L593-L598 down to below where the kubelet is actually initialized?

**Comment by odinuge** [comment]
Thanks for looking at it @logicalhan!
> Why can't we just move
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L593-L598 down to > below where the kubelet is actually initialized?

Yes, I think that is a good solution. I just need confirmation from someone that it will work, and that there is no dependencies that require it to stay where it is. I have updated the PR now, and it looks like the e2e tests pass too (the first few passed, but the tests takes ~2 hours to complete).

> Metrics are lazily instantiated now to allow us to disable them. We've had issues in the past with high cardinality metrics (#73587). In order to disable metrics, we need to no-opt creation of metrics until they actually become registered, which is the current behavior. We can force metrics initialization like so (logicalhan/kubernetes@master...kubelet-metrics-force-initialization), but I really don't want to do that.

Agree that force-registering the metrics is a bad solution, and goes against the new metric stuff; so I don't think that is a viable solution to the issue.

> It looks to me that these tests are failing because they are literally testing that the metrics are immediately registered. That seems like a weird thing to test.

The test has a 1min timeout when looking for the metrics. And as I said in the other comments; from what I see and understand, if the first metric write is lost, the metrics will not be reapplied (Sync will not run) unless some of the data is changed.

**Comment by odinuge** [comment]
cc @kubernetes/sig-node-bugs

**Comment by odinuge** [comment]
Ping @logicalhan. Any new thoughts?

**Review by logicalhan — APPROVED** [review]
/lgtm
