### PR TITLE
Send events before adding watchers in traversePluginDir

### LINKED ISSUE #75097: Race condition in plugin registration
**What happened**:

A race condition in the plugin watcher might happen when a `pluginwatcher.Watcher` is created, started and immediately stopped and cleaned up. If executed several times, the unit test `TestNewManagerImplStartProbeMode` will expose this issue.

The PR #71440 addressed part of the problem by serializing the handling of CREATE and DELETE events. However, a race might still happen in the `pluginwatcher.traversePluginDir` function. https://github.com/kubernetes/kubernetes/pull/71440#discussion_r236798644 describes in detail the problem.

**How to reproduce it (as minimally and precisely as possible)**:

```
# Create a binary
$ go test -c k8s.io/kubernetes/pkg/kubelet/cm/devicemanager -run  ^TestNewManagerImplStartProbeMode$

# Run the test in a loop until it fails
$ while ./devicemanager.test -test.failfast=true ; do :; done
```

/sig storage
/sig node

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR changes the function `devicemanager.traversePluginDir` in order to send events before adding watchers to directories.

**Which issue(s) this PR fixes**:

Fixes #75097

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/sig storage
/sig node
/assign @liggitt

### CODE REVIEW

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 1]
```diff
@@ -206,25 +211,36 @@ func (w *Watcher) traversePluginDir(dir string) error {
...
 				return filepath.SkipDir
 			}
-
-			if err := w.fsWatcher.Add(path); err != nil {
-				return fmt.Errorf("failed to watch %s, err: %v", path, err)
-			}
+			dirsToWatch = append(dirsToWatch, path)
 		case mode&os.ModeSocket != 0:
-			w.wg.Add(1)
-			go func() {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: why accumulate rather than continuing to send async here? we can't assume `w.fsWatcher.Events` won't block.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 2]
```diff
@@ -206,25 +211,36 @@ func (w *Watcher) traversePluginDir(dir string) error {
 			if w.containsBlacklistedDir(path) {
 				return filepath.SkipDir
 			}
-
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: starting watching the dir after we descend and scan it for socket files means that we can miss new socket files that appear. we *have* to start watching before we scan the content.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Yeah, I noticed that after later...

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 2 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Yes, there'd be another race if the file were created after we descend and before start watching.

I changed the order of events to:

1. Register file system watchers as we descend
2. Enqueue and process socket files found
3. Start processing socket files observed by watchers added in step 1

Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Done.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 3]
```diff
@@ -191,6 +220,15 @@ func (w *Watcher) init() error {
 // Goroutines started here will be waited for in Stop() before cleaning up.
 // Ignore all errors except root dir not being walkable
 func (w *Watcher) traversePluginDir(dir string) error {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: this is called at times other than Start()... checking for isPluginDir() doesn't ensure that scanned synthetic events from new directories we encounter are processed before observed events for those new directories

Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: would it be simpler to:
1. have traversePluginDir call `w.handleCreateEvent` directly and synchronously, rather than enqueuing synthetic create events in the event channel
2. wait until the two traversePluginDir() calls have completed in Start() before starting the event processing goroutine

that would ensure that while traversing a given directory (either in Start() or in response to an observed directory creation), no observed events from the started watchers were processed

Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Done

Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Done

**Comment by rphillips** [comment]
/lgtm

@liggitt it appears your comments were addressed. Can you give this PR another review?

**Comment by bertinatto** [comment]
Also,

/assign @vishh 

for approval.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 4]
```diff
@@ -214,10 +208,10 @@ func (w *Watcher) traversePluginDir(dir string) error {
 			w.wg.Add(1)
 			go func() {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: don't we have to remove this goroutine, so that `traversePluginDir` runs synchronously and completes before we start our processing loop (and before we continue processing other events in the event loop)?

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 5]
```diff
@@ -214,10 +208,10 @@ func (w *Watcher) traversePluginDir(dir string) error {
...
 				defer w.wg.Done()
-				w.fsWatcher.Events <- fsnotify.Event{
+				w.handleCreateEvent(fsnotify.Event{
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: handle the returned error (log for now, but add a matching `//TODO: Handle errors by taking corrective measures`)

Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Done.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 4 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Fixed. I thought starting the goroutine would be enough to guarantee that it'd be executed before the processing goroutine, but I was wrong.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go [hunk 6]
```diff
@@ -189,6 +186,9 @@ func TestPluginRegistrationAtKubeletStart(t *testing.T) {
 		}(plugins[i])
 	}
 
+	w := newWatcherWithHandler(t, hdlr, false /* testDeprecatedDir */)
+	defer func() { require.NoError(t, w.Stop()) }()
+
```
Comment (bertinatto) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go]: Since we're processing serially now, there're would be a lot of contention [here](https://github.com/bertinatto/kubernetes/blob/832822b41808f54f563fa513dbb3371164803e44/pkg/kubelet/util/pluginwatcher/example_plugin.go#L103). To avoid that, this starts the channel-reading goroutines earlier.

**Comment by liggitt** [comment]
this lgtm and is easier to follow, in my opinion. will leave final ack to sig-node

**Comment by bertinatto** [comment]
/retest

Something is going when jobs try to `merge` this branch. These error are unrelated to the changes from this patch.

**Comment by liggitt** [comment]
all the required CI jobs are green on this PR, ready for node/storage review

**Comment by bertinatto** [comment]
/remove-do-not-merge/work-in-progress

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 7]
```diff
@@ -211,14 +205,14 @@ func (w *Watcher) traversePluginDir(dir string) error {
...
-					Name: path,
-					Op:   fsnotify.Create,
-				}
-			}()
+			event := fsnotify.Event{
+				Name: path,
+				Op:   fsnotify.Create,
+			}
+			//TODO: Handle errors by taking corrective measures
+			if err := w.handleCreateEvent(event); err != nil {
```
Comment (tallclair) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Looking at the implementation of handleCreateEvent, I think it's more direct to just do:
```go
if !w.containsBlacklistedDir(path) {
  return w.traversePluginDir(path)
}
```

File: pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go [hunk 8]
```diff
@@ -238,11 +238,22 @@ func TestPlugiRegistrationFailureWithUnsupportedVersionAtKubeletStart(t *testing
...
 	w := newWatcherWithHandler(t, hdlr, false /* testDeprecatedDir */)
 	defer func() { require.NoError(t, w.Stop()) }()
 
-	require.True(t, waitForEvent(t, exampleEventValidate, hdlr.EventChan(p.pluginName)))
-	require.False(t, waitForPluginRegistrationStatus(t, p.registrationStatus))
+	select {
+	case <-c:
+		return
+	case <-time.After(2 * time.Second):
```
Comment (tallclair) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go]:
```suggestion
	case <-time.After(wait.ForeverTestTimeout):
```

You can't wait timeout before that in a unit test, as it will flake in the CI environment.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go [hunk 9]
```diff
@@ -238,11 +238,22 @@ func TestPlugiRegistrationFailureWithUnsupportedVersionAtKubeletStart(t *testing
 	hdlr := NewExampleHandler(supportedVersions, false /* permitDeprecatedDir */)
 	hdlr.AddPluginName(pluginName)
 
+	c := make(chan struct{})
+	go func() {
+		defer close(c)
+		require.True(t, waitForEvent(t, exampleEventValidate, hdlr.EventChan(p.pluginName)))
+		require.False(t, waitForPluginRegistrationStatus(t, p.registrationStatus))
+	}()
```
Comment (tallclair) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go]: alternatively, you can just do this serially at the end of the test and rely on the whole test timing out for the failure condition.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go (hunk 8 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go]: Fixed. I took the chance and fixed the other `time.After` calls from this file.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go (hunk 9 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher_test.go]: Since we're processing plugins serially now, `newWatcherWithHandler` below would block forever trying to write to the event/registration channels. This goroutine prevents that by receiving info from these channels beforehand.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 7 above)
Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Not sure if I follow, do you mean inside `handleCreateEvent`? If so, then it wouldn't call `handlePluginRegistration`... or am I missing somehting?

**Comment by bertinatto** [comment]
skip

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 7 above)
Comment (tallclair) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: I mean "handle create event" doesn't really seem like what this is doing, unless I'm not following the control flow. If you look at what handle create event is doing, the snippet I commented above is all that gets hit in that function, so I'm suggesting to just inline that piece here.

Comment (bertinatto) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Ah, OK... I understand now...

This part of the code creates "synthetic create events" if we find a socket file. Then we "handle" this event right here (as opposed to sending it to a processing goroutine like it was before).

Since we're dealing with a socket file, we  don't really want to `traversePluginDir()` it, but instead we want to register the plugin that's listening to this unix domain socket file (i.e., `handlePluginRegistration()`).

However, we also need to make sure that we ignore black-listed directories (like you pointed in the snippet above) and files prefixed with a "."; this would do it:

```go
			if !w.containsBlacklistedDir(path) {
				if !strings.HasPrefix(path, ".") {
					// TODO: Handle errors by taking corrective measures
					if err := w.handlePluginRegistration(path); err != nil {
						klog.Errorf("error %v when handling create event for file: %s", err, path)
					}
				}
			}
```

IMO `handleCreateEvent()` looks like would be a better fit though (since we're almost re-implementing it in-line).

Does this make sense?

Comment (tallclair) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Ah, sorry, I completely misread what `handleCreateEvent` was doing.

Comment (tedyu) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Shouldn't the err be returned, in the same way error is returned for mode.IsDir() case ?
