### PR TITLE
GCE: Fix lowercase value and alpha-missing annotation for ILB

### LINKED ISSUE #50426: GCP ILB annotation value should be capitalized
pkg/cloudprovider/providers/gce/gce_annotations.go has:

```
LBTypeInternal LoadBalancerType = "internal"
```

That should be Internal.  We should fix and allow both in annotation.

### PR DESCRIPTION
**Pull request by nicksardo**
**What this PR does / why we need it**:
Fixes #50426
Also explicitly sets an annotation as 'alpha'.

/assign @freehan @bowei 

**Release note**:
```release-note
GCE: Internal load balancer is enabled with annotation value "Internal" instead of "internal".
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce_annotations.go [hunk 1]
```diff
@@ -58,8 +62,12 @@ func GetLoadBalancerAnnotationType(service *v1.Service) (LoadBalancerType, bool)
...
 // shared with other load balancers. Health checks and the healthcheck firewall will be shared regardless.
 func GetLoadBalancerAnnotationBackendShare(service *v1.Service) bool {
-	l, exists := service.Annotations[ServiceAnnotationILBBackendShare]
-	if exists && l == "true" {
+	if l, exists := service.Annotations[ServiceAnnotationILBBackendShare]; exists && l == "true" {
+		return true
+	}
+
+	// Check for deprecated annotation key
+	if l, exists := service.Annotations[deprecatedServiceAnnotationILBBackendShare]; exists && l == "true" {
```
Comment (freehan) [inline pkg/cloudprovider/providers/gce/gce_annotations.go]: report a warning event?

Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce_annotations.go]: This is just a helper function, so the best we could do is glog a warning. However, I haven't seen that for other deprecated annotations: https://github.com/kubernetes/kubernetes/blob/e7b1814863c9b5bb3369deedfe5dccaf7837e27d/pkg/api/service/util.go#L73-L95

Comment (freehan) [inline pkg/cloudprovider/providers/gce/gce_annotations.go]: For generic k8s object fei/annotaion, I think we will throw errors during validation.

But since this is a GCP sepecific annotation, I am not sure how we expose it. 

Log it at least.

Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce_annotations.go]: Done
