### PR TITLE
intra-pod test improvements for bug-triage and node-level reporting

### LINKED ISSUE #93833: Breadth first polling in intra-pod networking Conformance verification
**What would you like to be added**:

Right now we poll one node at a time for intra-pod tests.  We ultimately fail a test if any one node is unreachable.

If we instead polled all nodes, multiple times, and collected the number of times a node was unreachable, this would 
- tell us what % of nodes on the cluster were broken, rather then just telling us the first node that was broken.
- not break the testing contract (were still verifying intra-pod connectivity, just doing so in a way that gives us holistic cluster info)

**Why is this needed**:
I described why this would make triage alot easier, and in general make it easier to see why tests are failing, here ...  https://github.com/kubernetes/kubernetes/issues/92618

i'll collect a little more data on this to justify the decision .... as this is a conformance test so the bar for modification is higher (even if the test itself isnt changing) then regular tests.

### PR DESCRIPTION
**Pull request by jayunit100**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

- breadth first polling of pods
- fine grained debugging of pods that fail the first poll attempt
- summary of how many pods failed at the end

1) A breadth first poll is implemented like so, showing each host in the logs.  This way if one or two host are down you can clearly see which ones.

```
Aug 11 12:06:46.829: INFO: Breadth first check of 192.168.150.148 on host 172.18.0.2...
... 
Aug 11 11:57:27.078: INFO: reached 192.168.150.147 after 22/79 tries
```

This PR also adds a logging statement to clarify the way that "79" is calculated (as a function of the number of nodes ^2 + 30 :))... no clue where that all comes from. 
2) So, the logs now summarize:
```
Aug 11 12:06:47.169: INFO: reached 192.168.217.84 after 0/1 tries
Aug 11 12:06:47.169: INFO: Going to retry 0 out of 7 pods....
```
Fixes #93833 

**Does this PR introduce a user-facing change?**:

```release-note
     Added fine grained debugging to the intra-pod conformance test for helping easily resolve networking issues for nodes that might be unhealthy when running conformance or sonobuoy tests.
```

### CODE REVIEW

**Comment by mattfenwick** [comment]
Test plan (note to self, [see here](https://github.com/kubernetes/kubernetes/pull/93452)):

```
make WHAT=test/e2e/e2e.test

export KUBERNETES_SERVICE_HOST=127.0.0.1
export KUBERNETES_SERVICE_PORT=32768

cat << EOF > three-node-kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
EOF

kind create cluster --name=three-node --config three-node-kind.yaml

./_output/local/bin/darwin/amd64/e2e.test \
 --provider=local \
 --ginkgo.focus="should function for intra-pod communication: http [NodeConformance]" \
 --kubeconfig=/Users/mfenwick/.kube/config \
 --dump-logs-on-failure=false
```

**Comment by jayunit100** [comment]
cc @bowei not quite 'breadth first', but for lack of a better word, it does the trick - scopes out all the pods and gives a ratio of how many connections failed.

**Comment by jayunit100** [comment]
#93792 also will be easier to address once we have this since it tells exactly how many intrapod tests are failing per node .

File: test/e2e/common/networking.go [hunk 1]
```diff
@@ -80,9 +115,7 @@ var _ = ginkgo.Describe("[sig-network] Networking", func() {
 		*/
 		framework.ConformanceIt("should function for node-pod communication: udp [LinuxOnly] [NodeConformance]", func() {
 			config := e2enetwork.NewCoreNetworkingTestConfig(f, true)
-			for _, endpointPod := range config.EndpointPods {
-				config.DialFromNode("udp", endpointPod.Status.PodIP, e2enetwork.EndpointUDPPort, config.MaxTries, 0, sets.NewString(endpointPod.Name))
-			}
+			checkNodeConnectivity(config, "udp", e2enetwork.EndpointUDPPort)
```
Comment (aojea) [inline test/e2e/common/networking.go:118]: this called `DialFromNode` and now calls `DialFromTestContainer` from `checkNodeConnectivity` :smiley:

Comment (jayunit100) [reply test/e2e/common/networking.go:118]: whoops :) fixing

File: test/e2e/common/networking.go [hunk 2]
```diff
@@ -28,6 +29,46 @@ var _ = ginkgo.Describe("[sig-network] Networking", func() {
 
 	ginkgo.Describe("Granular Checks: Pods", func() {
 
+		checkNodeConnectivity := func(config *e2enetwork.NetworkingTestConfig, protocol string, port int) {
+			// breadth first poll to quickly estimate failure.
+			failedPodsByHost := map[string][]*v1.Pod{}
+			// First time, we'll quickly try all pods, breadth first.
+			for _, endpointPod := range config.EndpointPods {
```
Comment (jayunit100) [inline test/e2e/common/networking.go:36]: ... note, this first 'shot' doesn't change the test semantics, but it allows us to separate the test output between successful nodes , and potentially problematic ones, meaning its very natural to browse the diagnostic results.

File: test/e2e/common/networking.go [hunk 3]
```diff
@@ -28,6 +29,46 @@ var _ = ginkgo.Describe("[sig-network] Networking", func() {
...
+				framework.Logf("Breadth first check of %v on host %v...", endpointPod.Status.PodIP, endpointPod.Status.HostIP)
+				if err := config.DialFromTestContainer(protocol, endpointPod.Status.PodIP, port, 1, 0, sets.NewString(endpointPod.Name)); err != nil {
+					if _, ok := failedPodsByHost[endpointPod.Status.HostIP]; !ok {
+						failedPodsByHost[endpointPod.Status.HostIP] = []*v1.Pod{}
+					}
+					failedPodsByHost[endpointPod.Status.HostIP] = append(failedPodsByHost[endpointPod.Status.HostIP], endpointPod)
+					framework.Logf("...failed...will try again in next pass")
+				}
+			}
+			errors := []error{}
```
Comment (jayunit100) [inline test/e2e/common/networking.go:46]: this struct is aggregated later, so that the end resulting test , all errors are printed out together, and ratio  of polls that failed is available , so that you can clearly know wether a cluster is in catastrophic state or wether there's just a few problematic nodes

File: test/e2e/common/networking.go [hunk 4]
```diff
@@ -28,6 +29,46 @@ var _ = ginkgo.Describe("[sig-network] Networking", func() {
...
+			// Second time, we pass through pods more carefully...
+			framework.Logf("Going to retry %v out of %v pods....", len(failedPodsByHost), len(config.EndpointPods))
+			for host, failedPods := range failedPodsByHost {
```
Comment (jayunit100) [inline test/e2e/common/networking.go:49]: if *one* node is down, all the pods from that node will be shown together.

Comment (jayunit100) [reply test/e2e/common/networking.go:49]: (imo) this isn't fundamentally changing the tests because, there is no order guarantee in the conformance definition.  that said, if we want it randomly ordered by pod, i can still do that explicitly.  

Note that the default is going to be polling like 80 times for a 6 node cluster (nodes^2 + 30) , so this test is *highly stable* in terms of retries, so the ordering isn't a sensitive thing at all.

**Comment by fejta** [comment]
/priority backlog
/approve
for test, please have someone from networking do the review

File: test/e2e/common/networking.go [hunk 5]
```diff
@@ -28,6 +29,46 @@ var _ = ginkgo.Describe("[sig-network] Networking", func() {
...
+						framework.Logf("Was able to reach %v on %v ", endpointPod.Status.PodIP, endpointPod.Status.HostIP)
+					}
+					framework.Logf("... Done probing pod [[[ %v ]]]", endpointPod.Status.PodIP)
+				}
+				framework.Logf("succeeded at polling %v out of %v connections", len(config.EndpointPods)-len(errors), len(config.EndpointPods))
+			}
+			if len(errors) > 0 {
+				framework.Logf("pod polling failure summary:")
+				for _, e := range errors {
+					framework.Logf("Collected error: %v", e)
```
Comment (oomichi) [inline test/e2e/common/networking.go:66]: This log message seems duplicated with line 55 to explain what error happens on each DialFromTestContainer() call.

File: test/e2e/framework/network/utils.go [hunk 6]
```diff
@@ -248,7 +248,9 @@ func makeCURLDialCommand(ipPort, dialCmd, protocol, targetIP string, targetPort
 // maxTries == minTries will confirm that we see the expected endpoints and no
 // more for maxTries. Use this if you want to eg: fail a readiness check on a
 // pod and confirm it doesn't show up as an endpoint.
-func (config *NetworkingTestConfig) DialFromContainer(protocol, dialCommand, containerIP, targetIP string, containerHTTPPort, targetPort, maxTries, minTries int, expectedResponses sets.String) {
+//
```
Comment (oomichi) [inline test/e2e/framework/network/utils.go:251]: nit: unnecessary blank line.

**Review by oomichi — COMMENTED** [review]
/cc @oomichi

File: test/e2e/common/networking.go (hunk 5 above)
Comment (mattfenwick) [reply test/e2e/common/networking.go:65]: 👍

File: test/e2e/framework/network/utils.go (hunk 6 above)
Comment (mattfenwick) [reply test/e2e/framework/network/utils.go]: 👍

**Comment by oomichi** [comment]
Thanks for updating.

/lgtm

File: test/e2e/framework/network/utils.go [hunk 7]
```diff
@@ -167,17 +167,17 @@ type NetexecDialResponse struct {
 }
 
 // DialFromEndpointContainer executes a curl via kubectl exec in an endpoint container.
-func (config *NetworkingTestConfig) DialFromEndpointContainer(protocol, targetIP string, targetPort, maxTries, minTries int, expectedEps sets.String) {
-	config.DialFromContainer(protocol, echoHostname, config.EndpointPods[0].Status.PodIP, targetIP, EndpointHTTPPort, targetPort, maxTries, minTries, expectedEps)
+func (config *NetworkingTestConfig) DialFromEndpointContainer(protocol, targetIP string, targetPort, maxTries, minTries int, expectedEps sets.String) error {
```
Comment (aojea) [inline test/e2e/framework/network/utils.go:170]: I 'm afraid we have to revert this commit, this method is used by other tests, and now instead of failing it returns an error, but the other tests are not asserting the error, so a failure will go unnoticed

https://github.com/kubernetes/kubernetes/blob/0b8c2bf1a10817a0e2b1f9a30737c85f6c65af63/test/e2e/network/networking.go#L211-L258

**Comment by aojea** [comment]
it was my fault, I wanted to follow up and hold it before merge, because this is modifying something that is being used by other tests, and I' m not sure that the gain is worth the effort

see https://github.com/kubernetes/kubernetes/pull/93837/files#r492991061
