### PR TITLE
kubelet: fix `Turning off swap in unprivileged tmpfs mounts unsupported`

### LINKED ISSUE #125137: ci-kubernetes-e2e-kind-rootless began to fail on 2024-05-24: `Network plugin returns error: cni plugin not initialized`, caused due to `Turning off swap in unprivileged tmpfs mounts unsupported`
### Which jobs are failing?

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-rootless

### Which tests are failing?

Everything

### Since when has it been failing?

2024-05-24

### Testgrid link

https://testgrid.k8s.io/sig-testing-kind#kind-rootless

### Reason for failure (if possible)

```
  I0527 01:48:02.282662 2585 util.go:506] >>> kubeConfig: /home/prow/go/src/k8s.io/kubernetes/_rundir/c90e98a0-ee29-4890-b77b-c4642a035a4f/kubeconfig
  I0527 01:48:02.284039 2585 helper.go:48] Waiting up to 30m0s for all (but 0) nodes to be schedulable
  I0527 01:48:02.448443 2585 resource.go:131] Condition Ready of node kind-control-plane is false instead of true. Reason: KubeletNotReady, message: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
  I0527 01:48:02.448486 2585 wait.go:256] Unschedulable nodes= 1, maximum value for starting tests= 0
  I0527 01:48:02.448546 2585 wait.go:258] 	-> Node kind-control-plane [[[ Ready=false, Network(available)=false, Taints=[{node.kubernetes.io/not-ready  NoSchedule <nil>}], NonblockingTaints=node-role.kubernetes.io/control-plane ]]]
  I0527 01:48:02.448556 2585 wait.go:270] ==== node wait: 0 out of 1 nodes are ready, max notReady allowed 0.  Need 1 more before starting.
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig testing

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
`IsTmpfsNoswapOptionSupported()` now returns false when running in UserNS, to fix:
- #125137

#### Which issue(s) this PR fixes:

Fixes #125137
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/kubelet/util/swap/swap_util.go [hunk 1]
```diff
@@ -46,6 +47,13 @@ func IsTmpfsNoswapOptionSupported(mounter mount.Interface, mountPath string) boo
 			return false
 		}
 
+		if inuserns.RunningInUserNS() {
+			// Turning off swap in unprivileged tmpfs mounts unsupported
+			// https://github.com/torvalds/linux/blob/v6.8/mm/shmem.c#L4004-L4011
```
Comment (iholder101) [inline pkg/kubelet/util/swap/swap_util.go:52]: For my education, do you know why this is the case? It's pretty surprising to me that tmpfs mounts can be done under a user namespace, but not with the noswap option.

File: pkg/kubelet/util/swap/swap_util.go [hunk 2]
```diff
@@ -46,6 +47,13 @@ func IsTmpfsNoswapOptionSupported(mounter mount.Interface, mountPath string) boo
...
+			// https://github.com/kubernetes/kubernetes/issues/125137
+			return false
```
Comment (iholder101) [inline pkg/kubelet/util/swap/swap_util.go:54]: Would you mind adding a log message here, so it would be clear why tmpfs noswap is not being used?
Perhaps something like:
```go
klog.InfoS("Running under a user namespace - tmpfs noswap is not supported")
```

**Review by iholder101 — COMMENTED** [review]
Thank you @AkihiroSuda!

File: pkg/kubelet/util/swap/swap_util.go (hunk 1 above)
Comment (iholder101) [reply pkg/kubelet/util/swap/swap_util.go:52]: Found this (thanks @kwilczynski for the pointer):
https://www.uwsg.indiana.edu/hypermail/linux/kernel/2304.2/02176.html

File: pkg/kubelet/util/swap/swap_util.go (hunk 2 above)
Comment (AkihiroSuda) [reply pkg/kubelet/util/swap/swap_util.go:55]: done

**Comment by iholder101** [comment]
Thanks a lot!
/lgtm

**Review by ffromani — COMMENTED** [review]
/lgtm

I think this should be highlighted more so linking it from the github conversation, rather than having it hidden by default in the inline comments
https://github.com/kubernetes/kubernetes/pull/125138/commits/b3175b8e996460316d61ce9e53d7f523049b8e2b#r1615668510

**Comment by iholder101** [comment]
> as a short term fix, this is ok
> 
> the long term implications are really really unfortunate. It means the security posture of two key features (swap and user namespaces) are in conflict.… we can't make swap enabled secure for tmpfs mounts if user namespaces are enabled.

Thanks for the information @liggitt.

In which environments kubelet would usually run under a user namespace (hence `RunningInUserNS()` will be `true`)? I'm trying to better understand the use-case and the environments that are affected by this.

**Comment by AkihiroSuda** [comment]
> In which environments kubelet would usually run under a user namespace (hence RunningInUserNS() will be true)? 

- Usernetes (https://github.com/rootless-containers/usernetes) with Rootless Docker/Podman/nerdctl
- kind with Rootless Docker/Podman/nerdctl
- minikube with Rootless Docker/Podman
- Kubernetes inside LXD/Incus (used by Chrome OS)

> Does this trip on a machine on which user namespaces is enabled at all, or only when the kubelet itself is running in a container with user namespaces enabled?

The latter.

**Comment by iholder101** [comment]
> > In which environments kubelet would usually run under a user namespace (hence RunningInUserNS() will be true)?
> 
> * Usernetes ([rootless-containers/usernetes](https://github.com/rootless-containers/usernetes)) with Rootless Docker/Podman/nerdctl
> * kind with Rootless Docker/Podman/nerdctl
> * minikube with Rootless Docker/Podman
> * Kubernetes inside LXD/Incus (used by Chrome OS)

Since these are non-production environments, I think there is no real damage done.

> > Does this trip on a machine on which user namespaces is enabled at all, or only when the kubelet itself is running in a container with user namespaces enabled?
> 
> The latter.

Thanks for clarifying @AkihiroSuda!

**Comment by BenTheElder** [comment]
> the long term implications are really really unfortunate. It means the security posture of two key features (swap and user namespaces) are in conflict.… we can't make swap enabled secure for tmpfs mounts if user namespaces are enabled.

To circle back on this explicitly: they shouldn't be in conflict, you can still use kubelet + userns + tmpfs no swap you just can't run kubelet itself in userns and do this (and .. that's already a non-production state).

**Comment by AkihiroSuda** [comment]
ping @mrunalp 🙏

**Comment by AkihiroSuda** [comment]
ping @kubernetes/sig-node-pr-reviews 

This PR is needed make the CI green: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kind-rootless
(Failing for more than two weeks)

**Comment by dims** [comment]
/approve
/lgtm

agree with a lot of the discussion here especially the callout from @BenTheElder https://github.com/kubernetes/kubernetes/pull/125138#issuecomment-2138091075

/kind failing-test

merging to get the CI job go green again.
