### PR TITLE
fix init container oomkilled as a failure

### LINKED ISSUE #104454: Container marked OOMKilled when a non init process gets killed
#### What happened:
Init container exited with OOMKilled reason, but init container was marked succesful, and main app container was allowed to be started

#### What you expected to happen:
If non init process gets killed the container should not be marked OOMKilled
or
If OOMKilled is terminate reason main app contaienr should not be started.

According to https://github.com/kubernetes/kubernetes/issues/50632#issuecomment-322849618
Container should only be marked OOMKilled if init process is killed.

#### How to reproduce it (as minimally and precisely as possible):
1. Build the container
2. Deploy the Deploy.yaml

When checking init container status:
```
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    0
      Started:      Thu, 19 Aug 2021 16:22:29 +0300
      Finished:     Thu, 19 Aug 2021 16:22:30 +0300
```
But main app container is running. 

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

Dockerfile:
```
FROM ubuntu:trusty
RUN apt-get update && apt-get install -y stress
ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
CMD ["/entrypoint.sh"]
```
Entrypoint.sh:
```
#!/bin/bash
while true
do
   /usr/bin/stress --verbose --vm 2 --vm-bytes 128M --timeout 10s
   if [[ ! -z "${INIT_CONTAINER}" ]]
   then
     exit 0
   fi
   sleep 86400
done
```
Deploy.yaml:
```

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      initContainers:
      - name: stress-init
        image: stress:latest
        imagePullPolicy: Always
        env:
        - name: INIT_CONTAINER
          value: "yes"
        resources:
          limits:
            memory: 64Mi
      containers:
        - name: stress
          image: stress:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 32Mi
```

### PR DESCRIPTION
**Pull request by yxxhero**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix initcontainer oomkiil as a failure

#### Which issue(s) this PR fixes:
Fixes: https://github.com/kubernetes/kubernetes/issues/104454

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Pod will not start when Init container was OOM killed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by matthyx** [comment]
I think it makes sense...
/priority important-longterm
/triage accepted

File: pkg/kubelet/kuberuntime/helpers.go [hunk 1]
```diff
@@ -142,6 +142,11 @@ func (m *kubeGenericRuntimeManager) getImageUser(image string) (*int64, string,
 // isInitContainerFailed returns true if container has exited and exitcode is not zero
 // or is in unknown state.
 func isInitContainerFailed(status *kubecontainer.Status) bool {
+	// When oomkilled occurs, init container should be considered as a failure.
+	if status.Reason == "OOMKilled" {
```
Comment (yangjunmyfm192085) [inline pkg/kubelet/kuberuntime/helpers.go:146]: The Reason here should come from runtime, I want to know when the container is killed due to oom,
all kinds of runtime reporting reason is oomkilled?
/cc @249043822

File: pkg/kubelet/kuberuntime/helpers_test.go [hunk 2]
```diff
@@ -31,6 +31,56 @@ import (
...
+			isFailed: true,
+		},
+		{
+			status: &kubecontainer.Status{
+				State: kubecontainer.ContainerStateUnknown,
+			},
+			isFailed: true,
+		},
+		{
+			status: &kubecontainer.Status{
```
Comment (yangjunmyfm192085) [inline pkg/kubelet/kuberuntime/helpers_test.go:53]: The scenario solved by this pr is that exit code is 0 and the reason is OOMKilled. I think you need to add some test cases for this scenario.

File: pkg/kubelet/kuberuntime/helpers.go (hunk 1 above)
Comment (yxxhero) [reply pkg/kubelet/kuberuntime/helpers.go:146]: ok， I will ensure other runtime behave.

File: pkg/kubelet/kuberuntime/helpers_test.go (hunk 2 above)
Comment (yxxhero) [reply pkg/kubelet/kuberuntime/helpers_test.go:53]: yes, I think so,  I will add it.

File: pkg/kubelet/kuberuntime/helpers.go (hunk 1 above)
Comment (aojea) [reply pkg/kubelet/kuberuntime/helpers.go:146]: I think that you should discuss this with sig-node, I'm not familiar with this function but the description says
> // isInitContainerFailed returns true if container has exited and exitcode is not zero
> // or is in unknown state.

the change you are adding is clearly not in that scope, I don't know if and OOMKilled container can be considered as a failure honestly,

Comment (249043822) [reply pkg/kubelet/kuberuntime/helpers.go:146]: This change should be approved by sig-node whether we should track non-init process(child process) OOM kills. Maybe there are apps that can tolerate OOM kills of non init processes. @ehashman

Comment (matthyx) [reply pkg/kubelet/kuberuntime/helpers.go:146]: I think the answer here is "it depends" because usually OOM kills result in an exit code of 137.
POSIX says that 0 means success, but I have doubts most init containers can happily finish their job to completion after being killed, even if they could handle it:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/docker_container.go#L414-L415

I would say having an initContainer OOMKilled isn't very encouraging to let this pod run successfully, but it's only me.

Comment (yxxhero) [reply pkg/kubelet/kuberuntime/helpers.go:146]: @matthyx
I agree with you. In general, oomkilled is an exception.

**Comment by matthyx** [comment]
I leave it in the needs reviewer column to let others have a look.
/lgtm

File: pkg/kubelet/kuberuntime/helpers.go (hunk 1 above)
Comment (aojea) [reply pkg/kubelet/kuberuntime/helpers.go:146]: then update the description of the function please,

Comment (yxxhero) [reply pkg/kubelet/kuberuntime/helpers.go:146]: @aojea ok, I will do as you see. Thanks very much again.

**Comment by yxxhero** [comment]
@yangjunmyfm192085 @aojea @matthyx rebase. Please review again. Thanks very much.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

File: pkg/kubelet/kuberuntime/helpers_test.go [hunk 3]
```diff
@@ -39,6 +39,64 @@ func seccompLocalhostPath(profileName string) string {
...
+			isFailed:    true,
+			description: "Init container which state is unknown should return true",
+		},
+		{
+			status: &kubecontainer.Status{
+				Reason:   "OOMKilled",
+				ExitCode: 0,
+			},
+			isFailed:    true,
+			description: "Init container which state is exited and exitcode is zero shoud return true",
```
Comment (249043822) [inline pkg/kubelet/kuberuntime/helpers_test.go:69]: this description maybe confusing with the line 77,  so can we make it clear for OOMKilled reason?

Comment (yxxhero) [reply pkg/kubelet/kuberuntime/helpers_test.go:69]: ok. I will see it.

**Comment by s-kawamura-w664** [comment]
Looks good to me, too.

I have tested oomkilled behavior and will report it.
In case of the docker runtime, initcontainer is oomkilled.
In case of the containerd runtime, initcontainer is not oomkilled and initcontainer works fine.
This issue seems to occur only in the docker runtime.

**Comment by aojea** [comment]
> This issue seems to occur only in the docker runtime.

/hold

docker runtime was deprecated in 1.20 https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

we should not add docker runtime only features
Sig-node is the owner, so feel free to unhold if this was not appropiate

**Comment by matthyx** [comment]
> This issue seems to occur only in the docker runtime.

I don't see how this could be specific to a runtime... can you lower the resource limits and try to make the OOM appear with containerd?

**Comment by yxxhero** [comment]
> Looks good to me, too.
> 
> I have tested oomkilled behavior and will report it.
> In case of the docker runtime, initcontainer is oomkilled.
> In case of the containerd runtime, initcontainer is not oomkilled and initcontainer works fine.
> This issue seems to occur only in the docker runtime.

do you test it? I will test it. Thanks very much.

**Comment by s-kawamura-w664** [comment]
> do you test it? I will test it. Thanks very much.

At first, I tried it in Kind. Kind will run with containerd.
At second, I builded the k8s cluster in my VM and I tried it with both docker runtime and containerd runtime.
Then oomkill appears only with docker runtime.
In case of containred, I can not understand why it is not oomkilled.
I will try that OOM appear with the containred.

**Comment by s-kawamura-w664** [comment]
I re-tested and can confirm this PR work fine with containerd.
At k8s cluster of my VM (that use containred), after memory-limit had been lower, oomkill could occur.
In case of old kubelet, the initcontainer succeeded. 
After kubelet is updated, the initcontainer was repeated the restart by oom. I think It is correct.
I remove hold.

/remove-hold

**Comment by yxxhero** [comment]
> I re-tested and can confirm this PR work fine with containerd.
> At k8s cluster of my VM (that use containred), after memory-limit had been lower, oomkill could occur.
> In case of old kubelet, the initcontainer succeeded.
> After kubelet is updated, the initcontainer was repeated the restart by oom. I think It is correct.
> I remove hold.
> 
> /remove-hold

Thanks very much.

**Comment by aojea** [comment]
> I re-tested and can confirm this PR work fine with containerd.
> At k8s cluster of my VM (that use containred), after memory-limit had been lower, oomkill could occur.
> In case of old kubelet, the initcontainer succeeded.
> After kubelet is updated, the initcontainer was repeated the restart by oom. I think It is correct.
> I remove hold.
> 
> /remove-hold

Thanks for verifying
/lgtm

File: pkg/kubelet/kuberuntime/helpers_test.go [hunk 4]
```diff
@@ -39,6 +39,64 @@ func seccompLocalhostPath(profileName string) string {
...
+		isFailed    bool
+		description string
+	}{
+		{
+			status: &kubecontainer.Status{
+				State:    kubecontainer.ContainerStateExited,
+				ExitCode: 1,
+			},
+			isFailed:    true,
+			description: "Init container which state is exited and exitcode is non-zero shoud return true",
```
Comment (mrunalp) [inline pkg/kubelet/kuberuntime/helpers_test.go:54]: I left nits on this PR https://github.com/kubernetes/kubernetes/pull/104651. Could you incorporate those?

File: pkg/kubelet/kuberuntime/helpers.go [hunk 5]
```diff
@@ -139,9 +139,16 @@ func (m *kubeGenericRuntimeManager) getImageUser(image string) (*int64, string,
 	return new(int64), "", nil
 }
 
-// isInitContainerFailed returns true if container has exited and exitcode is not zero
-// or is in unknown state.
+// isInitContainerFailed returns true under the following conditions:
+// 1. container has exited and exitcode is not zero.
+// 2. container in unknown state.
+// 3. container occurs OOMKilled.
```
Comment (mrunalp) [inline pkg/kubelet/kuberuntime/helpers.go:145]: container gets OOMKilled

File: pkg/kubelet/kuberuntime/helpers.go [hunk 6]
```diff
@@ -139,9 +139,16 @@ func (m *kubeGenericRuntimeManager) getImageUser(image string) (*int64, string,
 	return new(int64), "", nil
 }
 
-// isInitContainerFailed returns true if container has exited and exitcode is not zero
-// or is in unknown state.
+// isInitContainerFailed returns true under the following conditions:
+// 1. container has exited and exitcode is not zero.
+// 2. container in unknown state.
```
Comment (mrunalp) [inline pkg/kubelet/kuberuntime/helpers.go:144]: container is in unknown state

**Comment by yxxhero** [comment]
@mrunalp Please review. Thanks very much.

**Comment by yxxhero** [comment]
@mrunalp ping

**Comment by yxxhero** [comment]
@mrunalp any update? Thanks very much.

**Comment by yxxhero** [comment]
@mrunalp anything should I do? Thanks very much.

**Comment by yxxhero** [comment]
any update?

**Review by SergeyKanzhelev — APPROVED** [review]
/release-note-edit ```release-note Pod will not start when Init container was OOM killed.```
/lgtm

**Comment by SergeyKanzhelev** [comment]
> /release-note-edit `release-note Pod will not start when Init container was OOM killed.`

Please update the release note, I think prow cannot do it as the initial message didn't have the `release-note`

**Comment by yxxhero** [comment]
> > /release-note-edit `release-note Pod will not start when Init container was OOM killed.`
> 
> Please update the release note, I think prow cannot do it as the initial message didn't have the `release-note`

done. Thanks very much. @SergeyKanzhelev

**Review by mrunalp — APPROVED** [review]
