### PR TITLE
Error out if kubectl create with extra argument

### LINKED ISSUE #148: kubectl create service: ignores extra positional arguments
See:

    $ kubectl create service loadbalancer --tcp=80:80 lb-1 lb-2 lb-3
    service "lb-1" created

it will silently ignore `lb-2` and `lb-3` arguments. If command takes exactly 1 positional argument, it should fail when executed command is not exactly 1.

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:
When using `kubectl create` command with extra args, kubectl will accept the first one and ignore the others. 
This pr give a warnning in this case

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubectl#148

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/create.go [hunk 1]
```diff
@@ -281,6 +281,9 @@ func NameFromCommandArgs(cmd *cobra.Command, args []string) (string, error) {
 	if len(args) == 0 {
 		return "", cmdutil.UsageErrorf(cmd, "NAME is required")
 	}
+	if len(args) > 1 {
```
Comment (apelisse) [inline pkg/kubectl/cmd/create.go]: Maybe join the two `if`-s, like so:
```
if len(args) != 1 {
    return "", cmdutil.UsageErrorf(cmd, "exactly one NAME is required, got %d", len(args))
}
```
Also, I'm not a huge fan of warn-and-guess in general rather than failures.

Comment (ahmetb) [reply pkg/kubectl/cmd/create.go]: +1 invalid usage should just error out

Comment (Lion-Wei) [reply pkg/kubectl/cmd/create.go]: @ahmetb @apelisse Thanks for reviewing. I was thinking if have extra NAME, that's invalid usage, but the command can work. So no need to error out.
Error out also make sense. I will change accordingly. 
Thanks.

Comment (apelisse) [reply pkg/kubectl/cmd/create.go]: But then it's more difficult to detect subtle bugs in scripts, and/or adds confusion for the user. It's better to just fail gracefully, and let the user know what happened and how to fix it.

Comment (Lion-Wei) [reply pkg/kubectl/cmd/create.go]: I see, thanks.
Can one of you help me ok-to-test, : (

**Comment by apelisse** [comment]
Looks good to me. @ahmetb, feel free to `/lgtm`.

**Comment by Lion-Wei** [comment]
@deads2k @ahmetb Can you help me take a look, thanks.
