### PR TITLE
Fix handling of NoExecute taint when PodDisruptionConditions is enabled

### LINKED ISSUE #112517: When PodDIsruptionConditions enabled pods are not terminated based on the NoExecute taint
### What happened?

For 1.25 clusters with PodDIsruptionConditions enabled pods continue to run if the node is tainted with untolerated NoExecute taint.

Also, the error is not logged.

### What did you expect to happen?

The pod running on the tainted node should be terminated

### How can we reproduce it (as minimally and precisely as possible)?

1. (prep) Create a 1.25 cluster with the `PodDisruptionConditions` enabled (tested on kind)
2. Create a job with a single Pod running long enough for the test (say 3min),
3. Taint the node with a custom taint (so that it is not tolerated by the Pod) with the NoExecute effect ($nodeName is the node the pod is scheduled to): kubectl taint node $nodeName node.kubernetes.io/custom:NoExecute

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
reproducible on kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #112517

The issue is triggered by this GET (protected by the `PodDisruptionConditions` feature gate): https://github.com/kubernetes/kubernetes/blob/a4ad8f4154bb07be9cbb98d12d82c51afaffeac6/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L124

What is more the error was not logged as it was propagated up to here: https://github.com/kubernetes/kubernetes/blob/a4ad8f4154bb07be9cbb98d12d82c51afaffeac6/pkg/controller/nodelifecycle/scheduler/timed_workers.go#L59

Thus, as a part of this PR I propose to make sure errors from the functions invoked by timed_workers are logged.

#### Does this PR introduce a user-facing change?

Yes, it fix that pods running on nodes tainted with NoExecute continue to run when the PodDisruptionConditions feature gate is enabled

```release-note
Fix that pods running on nodes tainted with NoExecute continue to run when the PodDisruptionConditions feature gate is enabled
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mimowo** [comment]
Initial investigation, after adding a generic error message suggests this is a permissions issue:
I0916 16:04:35.577007       1 timed_workers.go:62] "Timed worker function failed. " err="pods \"job-longrun-c7jcp\" is forbidden: User \"system:serviceaccount:kube-system:node-controller\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\""

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go [hunk 1]
```diff
@@ -52,11 +52,17 @@ type TimedWorker struct {
...
+			klog.Errorf("Timed worker failed with error: %q", err)
+		}
+	}
 	if delay <= 0 {
-		go f(ctx, args)
+		go fWrappedWithErrorLogging(ctx, args)
 		return nil
 	}
-	timer := clock.AfterFunc(delay, func() { f(ctx, args) })
+	timer := clock.AfterFunc(delay, func() { fWrappedWithErrorLogging(ctx, args) })
```
Comment (alculquicondor) [inline pkg/controller/nodelifecycle/scheduler/timed_workers.go:65]: this is simpler:

```suggestion
	timer := clock.AfterFunc(delay, func() {
		err := f(ctx, args)
		if err != nil {
			klog.Errorf("Timed worker failed with error: %v", err)
		}
	})
```

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 2]
```diff
@@ -31,12 +31,17 @@ import (
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/util/diff"
 	"k8s.io/apimachinery/pkg/util/sets"
+	genericfeatures "k8s.io/apiserver/pkg/features"
```
Comment (alculquicondor) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:34]:
```suggestion
	"k8s.io/apiserver/pkg/features"
```

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 3]
```diff
@@ -192,19 +197,41 @@ func TestBootstrapClusterRoleBindings(t *testing.T) {
...
-		roles[role.Name] = &role
+	tests := map[string]struct {
+		filename        string
+		enabledFeatures []featuregate.Feature
+	}{
+		"with feature gates enabled3": {
+			enabledFeatures: []featuregate.Feature{features.PodDisruptionConditions,
+				features.StatefulSetAutoDeletePVC,
+				genericfeatures.StorageVersionAPI,
+				genericfeatures.APIServerIdentity},
```
Comment (alculquicondor) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:208]: why do these features matter?

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/nodelifecycle/scheduler/timed_workers.go:65]: With the `fWrappedWithErrorLogging` function I want to avoid code duplication as in case `delay<=0` there is another invocation of `f` which was not wrapped with logging too.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 2 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:34]: there is already "k8s.io/kubernetes/pkg/features" imported, so I need to avoid a collision. Chosen the `genericfeatures` name as in `controller_policy.go`.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 3 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: refactored the test to only focus on the problematic feature gate.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 2 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: removed after refactoring the test to only focus on the PodDisruptionConditions feature gate.

**Comment by mimowo** [comment]
I checked that the existing e2e test "evicts pods from tainted nodes" in `test/e2e/node/taints.go` fails on master when the feature gate is enabled (for testing purposes enabled by modifying `/etc/kubernetes/manifests/kube-controller-manager.yaml`). 

So this e2e will ensure the feature is working once we graduate to Beta. 

For now I added a unit test in this PR, which can be deleted when the feature is graduated to GA.

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/nodelifecycle/scheduler/timed_workers.go:65]: Ahh, good point

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go [hunk 4]
```diff
@@ -52,11 +52,17 @@ type TimedWorker struct {
 // createWorker creates a TimedWorker that will execute `f` not earlier than `fireAt`.
 func createWorker(ctx context.Context, args *WorkArgs, createdAt time.Time, fireAt time.Time, f func(ctx context.Context, args *WorkArgs) error, clock clock.WithDelayedExecution) *TimedWorker {
 	delay := fireAt.Sub(createdAt)
+	fWrappedWithErrorLogging := func(ctx context.Context, args *WorkArgs) {
```
Comment (alculquicondor) [inline pkg/controller/nodelifecycle/scheduler/timed_workers.go:55]: simplification nit:

```suggestion
	fWithErrorLogging := func() {
```

the variables are already captured automatically.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 5]
```diff
@@ -192,19 +196,46 @@ func TestBootstrapClusterRoleBindings(t *testing.T) {
...
-	list := &api.List{}
-	names := sets.NewString()
-	roles := map[string]runtime.Object{}
-	bootstrapRoles := bootstrappolicy.ControllerRoles()
-	for i := range bootstrapRoles {
-		role := bootstrapRoles[i]
-		names.Insert(role.Name)
-		roles[role.Name] = &role
+	tests := map[string]struct {
+		filename         string
```
Comment (alculquicondor) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:200]:
```suggestion
		wantRolesfilename         string
```

The prefix `want` helps understand that this is what needs to be verified.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 6]
```diff
@@ -192,19 +196,46 @@ func TestBootstrapClusterRoleBindings(t *testing.T) {
...
+		enabledFeatures  []featuregate.Feature
+		disabledFeatures []featuregate.Feature
```
Comment (alculquicondor) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:202]:
```
featureOverrides map[feature.Feature]bool
```

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 7]
```diff
@@ -192,19 +196,46 @@ func TestBootstrapClusterRoleBindings(t *testing.T) {
...
+	}{
+		"PodDisruptionConditions enabled": {
+			enabledFeatures: []featuregate.Feature{features.PodDisruptionConditions},
+			filename:        "controller-roles-PodDisruptionConditions-enabled.yaml",
+		},
+		"PodDisruptionConditions disabled": {
+			disabledFeatures: []featuregate.Feature{features.PodDisruptionConditions},
+			filename:         "controller-roles-PodDisruptionConditions-disabled.yaml",
```
Comment (alculquicondor) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go:210]: you could just use `controller-roles.yaml` here. If we need a new file in the future, we'll deal with it at that point.

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/nodelifecycle/scheduler/timed_workers.go]: done

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 5 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: done

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 6 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: done

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go (hunk 7 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: indeed, done

File: pkg/controller/nodelifecycle/scheduler/timed_workers.go [hunk 8]
```diff
@@ -52,11 +52,17 @@ type TimedWorker struct {
 // createWorker creates a TimedWorker that will execute `f` not earlier than `fireAt`.
 func createWorker(ctx context.Context, args *WorkArgs, createdAt time.Time, fireAt time.Time, f func(ctx context.Context, args *WorkArgs) error, clock clock.WithDelayedExecution) *TimedWorker {
 	delay := fireAt.Sub(createdAt)
+	fWithErrorLogging := func() {
+		err := f(ctx, args)
+		if err != nil {
+			klog.Errorf("Timed worker failed with error: %q", err)
```
Comment (alculquicondor) [inline pkg/controller/nodelifecycle/scheduler/timed_workers.go:58]: Sorry for last minute suggestion, but thinking of debugability, it's probably worth saying something like:

```suggestion
			klog.Errorf("NodeLifecycle: timed worker failed with error: %q", err)
```

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by mimowo** [comment]
@alculquicondor please renew LGTM, no changes in this PR, but I rebased as there were some unrelated tests failing - don't know why, but rebase helped.

**Comment by mimowo** [comment]
/assign @liggitt 
Should we also cherry-pick it for 1.25?

**Comment by alculquicondor** [comment]
low priority, because it's alpha, but we should.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go [hunk 9]
```diff
@@ -192,19 +196,46 @@ func TestBootstrapClusterRoleBindings(t *testing.T) {
 }
 
 func TestBootstrapControllerRoles(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy_test.go]: Ok, reverted the unit test changes. Will rely on manual testing + e2e testing once in Beta.
@alculquicondor please renew the LGTM if you are ok with the change.
