### PR TITLE
Register openstack provider for e2e test

### LINKED ISSUE #74326: Cannot specify "openstack" as cloud-provider of e2e test
**What happened**:

When specifying "openstack" as cloud-provider of e2e test, the test is failed like
```
$ go run hack/e2e.go --provider=openstack --test --test_args="--ginkgo.focus=PV\sProtection"
...
Setting up for KUBERNETES_PROVIDER="openstack".
Skeleton Provider: prepare-e2e not implemented
KUBE_MASTER_IP: 192.168.1.102:6443
KUBE_MASTER:
E0221 01:36:47.999337   11649 test_context.go:430] Unknown provider "openstack". The following providers are known: aws azure gce gke kubemark local skeleton

Ginkgo ran 1 suite in 524.865894ms
Test Suite Failed
!!! Error in ./hack/ginkgo-e2e.sh:143
```

**What you expected to happen**:

We can run e2e test with openstack cloud provider.

**How to reproduce it (as minimally and precisely as possible)**:

Just kick the following command:
```
$ go run hack/e2e.go --provider=openstack --test --test_args="--ginkgo.focus=PV\sProtection"
````

**Anything else we need to know?**:

This issue doesn't happen on v1.13, so this issue seems to happen during this dev cycle for v1.14.

**Environment**:
- Kubernetes version (use `kubectl version`): master for v1.14
- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): 4.4.0-142-generic
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Since the commit f3d79e152eaac1cd1c5ac79e0a0bbd0997abdb17
openstack provider has been denied on e2e test runner.
However there are storage e2e tests which are related to
openstack. So this adds the registration of openstack
provider for e2e test.

**Which issue(s) this PR fixes**:

Fixes #74326

**Special notes for your reviewer**:

This change is tested on my local OpenStack environment.

**Does this PR introduce a user-facing change?**:

```release-note-none

```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks @oomichi , we did remove support for unknown providers in that PR.
/lgtm
/priority important-soon

**Comment by dims** [comment]
/approve

thanks @oomichi

**Comment by dims** [comment]
@oomichi please work with @mrhillsman and @kiwik to set up a e2e for storage in OpenLab (and report results to testgrid)

**Comment by oomichi** [comment]
@dims OK, thanks for organizing us. @mrhillsman is helping me for understanding it.

**Comment by BenTheElder** [comment]
why are we not just using skeleton or local?

File: test/e2e/framework/providers/openstack/openstack.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+*/
+
+package openstack
+
+import (
+	"k8s.io/kubernetes/test/e2e/framework"
+)
+
+func init() {
+	framework.RegisterProvider("openstack", newProvider)
```
Comment (BenTheElder) [inline test/e2e/framework/providers/openstack/openstack.go]: this provider does nothing, this is the same as `skeleton`, why would we not just use skeleton?

**Comment by BenTheElder** [comment]
I am -1 on this, unless we want to let everyone add their Null provider to the binary we should tell people to use skeleton.

**Comment by dims** [comment]
good point @BenTheElder 

@oomichi can you please confirm why we need "openstack" registered with a NullProvider?

/hold

**Comment by neolit123** [comment]
> I am -1 on this, unless we want to let everyone add their Null provider to the binary we should tell people to use skeleton.

indeed.

> However there are storage e2e tests which are related to
openstack. So this adds the registration of openstack
provider for e2e test.

just modify the test jobs to pass `--provider=skeleton`?

File: test/e2e/framework/providers/openstack/openstack.go (hunk 1 above)
Comment (oomichi) [reply test/e2e/framework/providers/openstack/openstack.go]: @BenTheElder That is a nice point.
Some storage e2e tests contain cloud provider specific tests like https://github.com/kubernetes/kubernetes/blob/f7a6b0a8602e02d67fabaa85458a94c0f14599a5/test/e2e/storage/volume_provisioning.go#L375
If using `skeleton`, we cannot operate these OpenStack specific tests.
That is a reason why I proposed this PR.

**Comment by oomichi** [comment]
To avoid missing my comment, I am putting the same one here:

@BenTheElder That is a nice point.
Some storage e2e tests contain cloud provider specific tests like https://github.com/kubernetes/kubernetes/blob/f7a6b0a8602e02d67fabaa85458a94c0f14599a5/test/e2e/storage/volume_provisioning.go#L375
If using `skeleton`, we cannot operate these OpenStack specific tests.
That is a reason why I proposed this PR.

File: test/e2e/framework/providers/openstack/openstack.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/framework/providers/openstack/openstack.go]: this hits the long-term planning problem of how to break out providers from the e2e testing framework too. for now i'd say add the nullprovider = openstack back.

Comment (oomichi) [reply test/e2e/framework/providers/openstack/openstack.go]: Yeah, that also is a nice point. I guess we might need to implement cloud-provider specific e2e tests on each cloud-provider repo in long-term.

**Comment by BenTheElder** [comment]
I see thank you @oomichi  that seems like a good reason for now. This will be interesting to figure out long term.

**Comment by oomichi** [comment]
@BenTheElder Thank you for your reply.
I am guessing we would implement e2e test framework as a library and re-use it in different repos in long-term. This idea comes from https://github.com/kubernetes/kubernetes/issues/74352

**Comment by dims** [comment]
/hold cancel

thanks @oomichi
