### PR TITLE
fix: After a Node is down and take some time to get back to up again, the mount point of the evicted Pods cannot be cleaned up successfully.

### LINKED ISSUE #111933: CSI volumes left overs are not cleaned up if CSI plugin is attachable
### What happened?

1. Create a Deployment or SS that uses a vsphere CSI volumes (for example).
2. Shutdown the node while pod was running.
3. Wait for node to go `NotReady` and pod to switch to `Terminating` state. 
4. Bring back the node up.
5. If the pod migrates to different node (or pod gets deleted), then files/directories inside `/var/lib/kubelet/pods/xxxx` should be cleaned up.

The reason those directories are not being cleaned up is because:

1. The volume types that are attachable, kubelet expects `node-publish-path` to be a mount point during reconstruction. So if node is rebooted then reconstruction fails because `/mount` path is not a mount point.
2. Kubelet tries to "Cleanup" the volume, but CSI driver may be unavailable at this point.
3. As a result volumes are never cleaned up.

### What did you expect to happen?

Expected cleanup to happen properly. 

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Anything else we need to know?

_No response_

### Kubernetes version

master

### Cloud provider

Any

### OS version

Linux

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by cvvz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
After a Node is down and take some time to get back to up again, the mount point of the evicted Pods cannot be cleaned up successfully. (#111933) Meanwhile Kubelet will keep printing the log `Orphaned pod "xxx" found, but error not a directory occurred when trying to remove the volumes dir` every 2 seconds. (#105536)

Although we have [KEP 3756](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3756-volume-reconstruction) to refactor the process of reconstructing ASW and DSW, which aims to fix these problems totally and some of the work has been done by introducing `SELinuxMountReadWriteOncePod` feature gate and adding [new reconcile function](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler_common.go#L149-L152 ), we still need to fix them under old implementation before the new feature is stable.

#### Which issue(s) this PR fixes:

Fixes #111933 #105536

#### Special notes for your reviewer:
No need to check volume existence during reconstruction and cleanup if mount point does not exist. 

After the evicted Pods are reconstructed and added to ASW or [skippedDuringReconstruction](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L94), the mount point will be finally cleaned up in the subsequence reconcile loop, since these Pods are not in DSW. 

#### Does this PR introduce a user-facing change?

```release-note
fix: After a Node is down and take some time to get back to up again, the mount point of the evicted Pods cannot be cleaned up successfully. (#111933) Meanwhile Kubelet will print the log `Orphaned pod "xxx" found, but error not a directory occurred when trying to remove the volumes dir` every 2 seconds. (#105536)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cvvz** [comment]
@gnufied @msau42 @jingxu97 @jsafrane @xing-yang 
Could you please take a look?

**Comment by cvvz** [comment]
cc @andyzhangx

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by jsafrane** [comment]
@cvvz can you please squash the commits, so we have a clean history?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 1]
```diff
@@ -2339,24 +2339,66 @@ func TestSyncStates(t *testing.T) {
...
 			createMountPoint: false,
 			podInfos:         []podInfo{},
 			verifyFunc: func(rcInstance *reconciler, fakePlugin *volumetesting.FakeVolumePlugin) error {
-				return retryWithExponentialBackOff(reconcilerSyncWaitDuration, func() (bool, error) {
-					err := volumetesting.VerifyTearDownCallCount(1, fakePlugin)
-					if err != nil {
-						return false, nil
-					}
-					return true, nil
-				})
```
Comment (jsafrane) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:2355]: We will still probably need a test case to check that `syncStates` calls `cleanupMounts` when `reconstructVolume()` fails. You need it to fail in other way now that "mount point does not exist" is not an error.

File: pkg/kubelet/volumemanager/reconciler/reconstruct_common.go [hunk 2]
```diff
@@ -291,16 +286,6 @@ func (rc *reconciler) reconstructVolume(volume podVolume) (*reconstructedVolume,
...
-	isExist, checkErr := rc.operationExecutor.CheckVolumeExistenceOperation(volumeSpec, checkPath, volumeSpec.Name(), rc.mounter, uniqueVolumeName, volume.podName, pod.UID, attachablePlugin)
-	if checkErr != nil {
-		return nil, checkErr
-	}
-	// If mount or symlink doesn't exist, volume reconstruction should be failed
-	if !isExist {
-		return nil, fmt.Errorf("volume: %q is not mounted", uniqueVolumeName)
-	}
-
 	reconstructedVolume := &reconstructedVolume{
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/reconciler/reconstruct_common.go:289]: Should we at least check for existence of mount or map path? If they don't exist (but may be pod directory exists) - is there a point in doing reconstruction?

Comment (cvvz) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_common.go:289]: Reconstruction is still needed when mount or map path doesn't exist, since we can rely on `unmountDevice` to clean global mount path.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 1 above)
Comment (cvvz) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: Done. please take another look.

**Comment by cvvz** [comment]
Hi, @gnufied  @jsafrane  Shall we move this pr on?

**Comment by xing-yang** [comment]
It should be safe to backport to 1.27, but backporting to older releases needs more investigation.

**Comment by jsafrane** [comment]
I checked 1.26 with the old-style volume reconstruction.

If [reconstructVolume()](https://github.com/kubernetes/kubernetes/blob/e575e60ea42ad58bfe124f44e719e4b7cc1ab2e6/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L62) succeeds:
* if the volume is already in DSW, `continue` here skips adding it to ASW (that's good): https://github.com/kubernetes/kubernetes/blob/e575e60ea42ad58bfe124f44e719e4b7cc1ab2e6/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L87-L97
* If the volume is not in DSW, it's added to ASW as `Mounted` (that's bad): https://github.com/kubernetes/kubernetes/blob/e575e60ea42ad58bfe124f44e719e4b7cc1ab2e6/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L149 So if kubelet gets a new Pod that uses the volume, then it will see it as mounted, while it could have been already unmounted.

Therefore this PR is not suitable for the old-style volume reconstruction + backports to 1.25-1.26. I don't think it is safe to mark the volumes as _uncertain_, that's why we reworked the volume reconstruction and put it behind a feature gate.

**Comment by cvvz** [comment]
> If the volume is not in DSW, it's added to ASW as Mounted (that's bad)
> So if kubelet gets a new Pod that uses the volume, then it will see it as mounted, while it could have been already unmounted.

I think it would be ok. 

1. Since the new Pod and old Pod uid is not the same, so `rc.unmountVolumes()` for old pod Volumes should succeed.
2. `rc.unmountDetachDevices()` will be skipped since DSW has the same `volumeName` in ASW.
3. `rc.mountOrAttachVolumes()` for new Pod will try to mount device if the plugin is DeviceMountable:  it will first [make mount dir and save metadata to vol_data.json](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L342-L356), I think the operations won't be failed even if the mount dir and vol_data.json already exist. And then call `NodeStageVolume` to mount device, after that mount new Pod volumes.

**Comment by andyzhangx** [comment]
not sure whether it's suitable to backports to 1.25-1.26, @cvvz could you back port to 1.27 first? thanks.

File: pkg/kubelet/volumemanager/reconciler/reconstruct_common.go (hunk 2 above)
Comment (Pingan2017) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_common.go:301]: but if pod still running, we  add it to asw directly, volume manage will not remount this volume forever, container will use local path instead of  remote path.

Comment (cvvz) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_common.go:301]: If Pod is still running, then the volume should exist in DSW, then it won't be added to ASW:https://github.com/kubernetes/kubernetes/blob/e575e60ea42ad58bfe124f44e719e4b7cc1ab2e6/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L87-L97

**Comment by migs35323** [comment]
How about backport to 1.26, or even previous ones?
