### PR TITLE
Fix pull-kubernetes-dra-integration job failures

### LINKED ISSUE #137428: pull-kubernetes-dra-integration fails with `create *v1.DeviceClass: deviceclasses.resource.k8s.io "default-class" already exists` error
### Which jobs are failing?

[pull-kubernetes-dra-integration](https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-dra-integration)

### Which tests are failing?

TestUpgradeDowngrade/after-cluster-creation/ImplicitExtendedResource

### Since when has it been failing?

Since Mar 4 2026

### Testgrid link

https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#pull-kubernetes-dra-integration

### Reason for failure (if possible)

This is most probably caused by recently merged https://github.com/kubernetes/kubernetes/pull/136568

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig scheduling
/sig node

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

It fixes failing [pull-kubernetes-dra-integration](https://testgrid.k8s.io/sig-node-dynamic-resource-allocation#pull-kubernetes-dra-integration) job. The failure was caused by the recently merged https://github.com/kubernetes/kubernetes/pull/136568

#### Which issue(s) this PR is related to:

Fixes #137428
Fixes #137429

#### Special notes for your reviewer:

The job didn't run on the https://github.com/kubernetes/kubernetes/pull/136568, which added ExtendedResources upgrade/downgrade tests. The job is not configured to automatically run on changes in the test directory.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by bart0sh** [comment]
> Probably because the job's run_if_changed didn't match.

Added, PTAL: https://github.com/kubernetes/test-infra/pull/36579

File: test/e2e_dra/extendedresources_test.go [hunk 1]
```diff
@@ -163,7 +161,7 @@ func createPodWithExtendedResource(tCtx ktesting.TContext, b *drautils.Builder,
 // verifyPodRunningWithClaim verifies a pod is running and has a valid ResourceClaim.
 func verifyPodRunningWithClaim(tCtx ktesting.TContext, b *drautils.Builder, pod *v1.Pod, resourceName v1.ResourceName) {
 	namespace := tCtx.Namespace()
-	b.TestPod(tCtx, pod)
+	b.TestPod(tCtx, pod, "container_0_request_0", "true")
```
Comment (sairameshv) [inline test/e2e_dra/extendedresources_test.go:161]: Is there any importance to these args other than avoiding the test failure as I don't think these are related to ExtendedResources feature in anyway.
If so, 
- Can we make the required change to handle the failure inside the framework?
Or 
- Can we just wait for the pod to come to `Running` state similar to [this](https://github.com/kubernetes/kubernetes/pull/137432/changes#diff-d6b6b524bcb54bbb1477783405e41d50d4d79ee28d6bad3c62473e087401dd38R166-R169)?

File: test/e2e_dra/extendedresources_test.go [hunk 2]
```diff
@@ -130,21 +130,19 @@ func createDeviceClassForExtendedResource(tCtx ktesting.TContext, b *drautils.Bu
...
+		// Device class is already created by the builder
 		deviceClass = b.Class().DeviceClass
 		resourceName = v1.ResourceName(fmt.Sprintf("%s%s", resourceapi.ResourceDeviceClassPrefix, deviceClass.Name))
 	}
 
-	createdObjs := b.Create(tCtx, deviceClass)
-
 	// Verify ExtendedResourceName is present in the spec when using explicit resource name
 	if resourceType == resourceTypeExplicit {
+		createdObjs := b.Create(tCtx, deviceClass)
```
Comment (pohly) [inline test/e2e_dra/extendedresources_test.go:131]: Above the comment about `deviceClass` says "Device class is already created by the builder" but here we create it nonetheless. That doesn't seem to match, or at least not in general?

Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go:131]: The comment says it in the implicit resource scope only, so it doesn't apply to this code. We create a class only for explicit resources.

File: test/e2e_dra/extendedresources_test.go (hunk 1 above)
Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go:161]: > Is there any importance to these args other than avoiding the test failure as I don't think these are related to ExtendedResources feature in anyway.

They are related. That's the way all extended resources tests check environment variables, e.g. https://github.com/kubernetes/kubernetes/blob/v1.35.2/test/e2e/dra/dra.go#L2413-L2416

Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go:161]: > Can we just wait for the pod to come to Running state similar to this?

We can, but this is not enough to say that DRA functionality works as expected.

File: test/e2e_dra/extendedresources_test.go (hunk 2 above)
Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go:131]: Updated the code, so now it should be cleaner that we don't create a class only for implicit resources, PTAL.

Comment (pohly) [reply test/e2e_dra/extendedresources_test.go:131]: Even better would be to eliminate `var deviceClass *resourceapi.DeviceClass` and `var resourceName v1.ResourceName` entirely.

We could use an early return, but it's more obvious which code is for what when doing this and it guards against an invalid parameter instead of assuming that this cannot happen:
```
switch resourceType {
    case resourceTypeExplicit:
         ...
         return resourceName
    case resourceTypeImplicit:
         .... doesn't need a DeviceClass instance ...
    default:
       tCtx.Fatalf("invalid resource type %q", resourceType)
}
```

File: test/e2e_dra/extendedresources_test.go [hunk 3]
```diff
@@ -129,22 +129,18 @@ func createDeviceClassForExtendedResource(tCtx ktesting.TContext, b *drautils.Bu
...
 		deviceClass = b.ClassWithExtendedResource(string(resourceName))
+		// Create the DeviceClass
+		createdObjs := b.Create(tCtx, deviceClass)
+		// Verify ExtendedResourceName is present in the spec
+		deviceClass = createdObjs[0].(*resourceapi.DeviceClass)
+		tCtx.Expect(deviceClass.Spec.ExtendedResourceName).ToNot(gomega.BeNil(), "DeviceClass.Spec.ExtendedResourceName should be set for explicit resource name")
+		tCtx.Logf("Created DeviceClass %q with extendedResourceName: %s", deviceClass.Name, resourceName)
 	} else {
-		// Framework automatically names it
+		// Device class is already created by the builder
```
Comment (pohly) [inline test/e2e_dra/extendedresources_test.go]: We don't need the the DeviceClass instances, only it's name. So let's write the code accordingly:
```
    // The device class was already created by the builder, we only need the name.
    return v1.ResourceName(resourceapi.ResourceDeviceClassPrefix + b.ClassName())
```

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e_dra/extendedresources_test.go (hunk 2 above)
Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go:131]: Done.

File: test/e2e_dra/extendedresources_test.go [hunk 4]
```diff
@@ -119,33 +119,31 @@ func testExtendedResource(tCtx ktesting.TContext, b *drautils.Builder, resourceT
...
 		deviceClass = createdObjs[0].(*resourceapi.DeviceClass)
 		tCtx.Expect(deviceClass.Spec.ExtendedResourceName).ToNot(gomega.BeNil(), "DeviceClass.Spec.ExtendedResourceName should be set for explicit resource name")
+		tCtx.Logf("Created DeviceClass %q with extendedResourceName: %s", deviceClass.Name, resourceName)
+		return resourceName
+	case resourceTypeImplicit:
+		// doesn't need a DeviceClass instance ...
+		// Device class is already created by the builder
+		deviceClass := b.Class().DeviceClass
+		resourceName := v1.ResourceName(fmt.Sprintf("%s%s", resourceapi.ResourceDeviceClassPrefix, deviceClass.Name))
+		return resourceName
```
Comment (pohly) [inline test/e2e_dra/extendedresources_test.go]: It says "doesn't need a DeviceClass instance" and then it gets one? That doesn't make sense to me when there is a simpler alternative.

```suggestion
		// The device class was already created, we just need its name.
		deviceClassName := b.ClassName()
		resourceName := v1.ResourceName(fmt.Sprintf("%s%s", resourceapi.ResourceDeviceClassPrefix, deviceClassName))
		return resourceName
```

I don't see a need for all of the intermediate variables and `Sprintf`, but so be it 🤷

**Comment by bart0sh** [comment]
> Something isn't right with cleanup. https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137434/pull-kubernetes-dra-integration-canary/2029559756393287680:

And with counting garbage collected claims: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137434/pull-kubernetes-dra-integration-canary/2029559756393287680

```
{Failed  === RUN   TestUpgradeDowngrade/after-cluster-downgrade/ExplicitExtendedResource
    extendedresources_test.go:115: FATAL ERROR: I0305 14:45:04.113945]
        	Timed out after 180.004s.
        	ResourceClaims for explicit pods should be garbage collected
        	Expected
        	    <int>: 2
        	to equal
        	    <int>: 0
--- FAIL: TestUpgradeDowngrade/after-cluster-downgrade/ExplicitExtendedResource (187.23s)

=== RUN   TestUpgradeDowngrade/after-cluster-downgrade/ImplicitExtendedResource
    extendedresources_test.go:115: FATAL ERROR: I0305 14:48:10.563927]
        	Timed out after 180.020s.
        	ResourceClaims for implicit pods should be garbage collected
        	Expected
        	    <int>: 2
        	to equal
        	    <int>: 0
--- FAIL: TestUpgradeDowngrade/after-cluster-downgrade/ImplicitExtendedResource (186.45s)
```

I'm not sure it's caused by this PR, let's see:
/test pull-kubernetes-dra-integration

File: test/e2e_dra/extendedresources_test.go (hunk 3 above)
Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go]: Done, thanks for the suggestion!

File: test/e2e_dra/extendedresources_test.go (hunk 4 above)
Comment (bart0sh) [reply test/e2e_dra/extendedresources_test.go]: done

**Comment by bart0sh** [comment]
it's still green, let's try again
/test pull-kubernetes-dra-integration-canary pull-kubernetes-dra-integration

**Comment by pohly** [comment]
> I'd suggest to merge it and address flakes in another PR as the job is failing for all DRA-related PRs currently.

Or revert...
