### PR TITLE
change node staging path for csi driver to PV agnostic

### LINKED ISSUE #105899: CSI Volume staging path contains PV name
### What happened?

When two CSI PVs point to the same volume in the storage backend, kubelet can't start pods that use these two PVs on the same node.

Both PVs have the same VolumeHandle and kubelet is smart enough to recognize that they're the same volume (because they have the same unique volume ID). It calls `NodeStage` only once, however, the staging path contains name of one of the PVs, say PV1:  `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0/globalmount/`

https://github.com/kubernetes/kubernetes/blob/3e6d122ee1e34ca20f9cb2fae3d36810d8dbf937/pkg/volume/csi/csi_attacher.go#L661

One of the CSI volume `SetUpAt` calls then fails, because it uses PV2 to compute the staging path and that path does not exist.
```
MountVolume.SetUp failed for volume "pv2" : rpc error: code = InvalidArgument desc = volume "1fdb001d-3634-11ec-aa06-0242ac110003" was staged at [/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0/globalmount], not "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv2/globalmount"
```

### What did you expect to happen?

Both pods should just start.

### How can we reproduce it (as minimally and precisely as possible)?

Using CSI HostPath volume, PV1 (dynamically provisioned for simplicity):
```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: hostpath.csi.k8s.io
    name: pvc-f5fa91c3-bf91-42a9-a8a3-da516e0371f0
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 500Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: myclaim
      namespace: default
      resourceVersion: "524"
      uid: f5fa91c3-bf91-42a9-a8a3-da516e0371f0
    csi:
      driver: hostpath.csi.k8s.io
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1635235714073-8081-hostpath.csi.k8s.io
      volumeHandle: 1fdb001d-3634-11ec-aa06-0242ac110003
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.hostpath.csi/node
            operator: In
            values:
            - 127.0.0.1
    persistentVolumeReclaimPolicy: Delete
    storageClassName: csi-hostpath-sc
    volumeMode: Filesystem
  status:
    phase: Bound
```

PV2 (basically edited PV1):
```yaml
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv2
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 500Mi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: myclaim2
      namespace: default
      resourceVersion: "664"
      uid: 89932338-c301-425b-9cef-dec861f4bdaf
    csi:
      driver: hostpath.csi.k8s.io
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1635235714073-8081-hostpath.csi.k8s.io
      volumeHandle: 1fdb001d-3634-11ec-aa06-0242ac110003
    persistentVolumeReclaimPolicy: Retain
    storageClassName: csi-hostpath-sc
    volumeMode: Filesystem
  status:
    phase: Bound
```

PVC1, PVC2, Pod1 and Pod2 are trivial, nothing special there. 

### Kubernetes version

<details>
Today's master, dba9975e3e3ba25e0712a209e67862603c172777
</details>

### PR DESCRIPTION
**Pull request by saikat-royc**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Without this fix, PVs pointing to the same underlying volume handle, fail to mount on the same node. This is because kubelet is confused into thinking that the volume is already node staged.
Fixes:
1. By making the staging path PV agnostic, a unique volume will be node staged only once. And this path will be bind-mounted on the pod specific path during pod bringup on nodes.
2. The global path uses a sha of the volumeId. This means the node staged path can no longer be used to backtrace the PV information (which is used to figure out Driver and VolumeID). This change therefore creates a hard dependency on the vol_data.json to exist with correct driver and volumeID information.
3. A fallback option is provided such that if the vol_data.json is missing, kubelet will try to parse the PV information from the old path format. 

#### Which issue(s) this PR fixes:

Fixes  #105899

#### Special notes for your reviewer:
CSI migration flows should not be impacted, because it is expected that the node is drained before migration is enabled.

An example staging path looks like this for PDCSI driver:
```
saikatroyc@e2e-test-saikatroyc-minion-group-5h8f ~ $ sudo ls /var/lib/kubelet/plugins/kubernetes.io/csi/pd.csi.storage.gke.io/d7b18a91056b638c3459de6043a10982e468f3b400c42c8e467e023b24aeab08
globalmount  vol_data.json
```

#### Does this PR introduce a user-facing change?

```release-note
Change node staging path for csi driver to use a PV agnostic path. Nodes must be drained before updating the kubelet with this change.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by saikat-royc** [comment]
@jingxu97 @jsafrane the PR is ready for review. Based on the initial review comments, I will add a e2e test as needed.

File: pkg/volume/csi/csi_attacher_test.go [hunk 1]
```diff
@@ -1573,53 +1590,76 @@ func TestAttacherUnmountDevice(t *testing.T) {
 		shouldFail      bool
 		watchTimeout    time.Duration
 	}{
+		// PV agnostic path positive test cases
 		{
-			testName:        "normal, json file exists",
+			testName:        "success, json file exists",
 			volID:           "project/zone/test-vol1",
-			deviceMountPath: "plugins/csi/pv/test-pv-name/globalmount",
+			deviceMountPath: "plugins/csi/" + generateSha("project/zone/test-vol1") + "/glbalmount",
```
Comment (jsafrane) [inline pkg/volume/csi/csi_attacher_test.go:1597]: typo: glbalmount
(applies also below)

**Review by jsafrane — COMMENTED** [review]
This looks good to me if we explicitly add a release note that nodes must be drained during update. It is implied by upgrade, but IMO an explicit note would help to avoid confusion.

And we can't ever cherry pick this into an older release.

It would be trivial to test if the old staging path exists and has a valid json file in `makeDeviceMountPath` and use that (although, unit tests would be not that simple).

File: pkg/volume/csi/csi_attacher_test.go (hunk 1 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher_test.go]: Done

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -653,12 +653,22 @@ func makeDeviceMountPath(plugin *csiPlugin, spec *volume.Spec) (string, error) {
...
 
-	pvName := spec.PersistentVolume.Name
-	if pvName == "" {
-		return "", errors.New(log("makeDeviceMountPath failed, pv name empty"))
+	driver, err := GetCSIDriverName(spec)
+	if err != nil {
+		return "", err
+	}
+	if driver == "" {
+		return "", errors.New(log("makeDeviceMountPath failed, csi source driver name is nil"))
```
[the remark this answers is not in the document]
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher.go]: Done

**Comment by saikat-royc** [comment]
> This looks good to me if we explicitly add a release note that nodes must be drained during update. It is implied by upgrade, but IMO an explicit note would help to avoid confusion.
> 
> And we can't ever cherry pick this into an older release.
> 
> It would be trivial to test if the old staging path exists and has a valid json file in `makeDeviceMountPath` and use that (although, unit tests would be not that simple).

Added a release note. Also the UTs (TestAttacherUnmountDevice) cover the old and new path test cases.

**Comment by jsafrane** [comment]
/triage accepted
/approve

looks lgtm-ish, giving @msau42 @xing-yang @gnufied chance to look at this. See comment https://github.com/kubernetes/kubernetes/pull/107065#pullrequestreview-837233017 for drawbacks.

**Comment by msau42** [comment]
/approve

@saikat-royc do you still plan to add an e2e test?

**Comment by saikat-royc** [comment]
ping for reviewers. the PR is ready for review

**Comment by saikat-royc** [comment]
ping for review @jingxu97

**Comment by jingxu97** [comment]
@saikat-royc is the raw block volume issue resolved too?

**Comment by saikat-royc** [comment]
> is the raw block volume issue resolved too?

In the raw block mode, the csi drivers take the [csi_block.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go) codepath. 

The test case added in this PR works for pdcsi works, since nodestage is a [no-op](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/node.go#L310). But the test case fails for csi-hostpath driver [here](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L87), because the csi-hostpath driver finds that the volume is already staged at a different path. To me it looks like a csi-hostpath specific issue. I have skipped raw block mode in this PR.

**Comment by jingxu97** [comment]
> > is the raw block volume issue resolved too?
> 
> In the raw block mode, the csi drivers take the [csi_block.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go) codepath.
> 
> The test case added in this PR works for pdcsi works, since nodestage is a [no-op](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/node.go#L310). But the test case fails for csi-hostpath driver [here](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L87), because the csi-hostpath driver finds that the volume is already staged at a different path. To me it looks like a csi-hostpath specific issue. I have skipped raw block mode in this PR.

could you open an issue for it?

File: pkg/volume/csi/csi_attacher.go [hunk 3]
```diff
@@ -653,12 +653,22 @@ func makeDeviceMountPath(plugin *csiPlugin, spec *volume.Spec) (string, error) {
...
+		return "", errors.New(log("makeDeviceMountPath failed, csi source driver name is empty"))
+	}
+
+	csiSource, err := getPVSourceFromSpec(spec)
+	if err != nil {
+		return "", errors.New(log("makeDeviceMountPath failed to get CSIPersistentVolumeSource: %v", err))
 	}
 
-	return filepath.Join(plugin.host.GetPluginDir(plugin.GetPluginName()), persistentVolumeInGlobalPath, pvName, globalMountInGlobalPath), nil
+	result := sha256.Sum256([]byte(fmt.Sprintf("%s", csiSource.VolumeHandle)))
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher.go:669]: do we need to check whether csiSource.VolumeHandle is empty or not?

File: pkg/volume/csi/csi_attacher_test.go [hunk 4]
```diff
@@ -1023,23 +1024,32 @@ func TestAttacherGetDeviceMountPath(t *testing.T) {
...
-		testName          string
-		pvName            string
-		expectedMountPath string
-		shouldFail        bool
+		testName      string
+		pvName        string
+		volumeId      string
+		skipCSISource bool
+		shouldFail    bool
+		addVolSource  bool
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher_test.go:1033]: is addVolSource used in testcases?

Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher_test.go:1033]: yes in https://github.com/kubernetes/kubernetes/pull/107065/files#diff-b1c8c49f572090ada630eecfd3630b04898d467b6cf4c2abba40f053fd606f3aR1063

Comment (jingxu97) [inline pkg/volume/csi/csi_attacher_test.go:1033]: oh, I missed it. Could you add comments about this option?

File: pkg/volume/csi/csi_attacher.go (hunk 3 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher.go:669]: Ack. Will do

Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher.go:673]: Done

File: pkg/volume/csi/csi_attacher_test.go (hunk 4 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher_test.go]: Done

File: pkg/volume/csi/csi_attacher.go [hunk 5]
```diff
@@ -650,15 +650,29 @@ func isAttachmentName(unknownString string) bool {
...
+		return "", errors.New("makeDeviceMountPath failed, csi source driver name is empty")
+	}
+
+	csiSource, err := getPVSourceFromSpec(spec)
+	if err != nil {
+		return "", errors.New(log("makeDeviceMountPath failed to get CSIPersistentVolumeSource: %v", err))
+	}
+
+	if csiSource.VolumeHandle == "" {
+		return "", errors.New("makeDeviceMountPath failed to get CSIPersistentVolumeSource volume handle")
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher.go:670]: how about error message "VolumeHandle is empty"?

File: pkg/volume/csi/csi_attacher_test.go [hunk 6]
```diff
@@ -1023,23 +1024,40 @@ func TestAttacherGetDeviceMountPath(t *testing.T) {
...
+		},
+		{
+			testName:        "fail test, failed to create device mount path due to missing CSI source",
+			pvName:          "test-pv1",
+			volumeId:        "test-vol1",
+			skipPVCSISource: true,
+			shouldFail:      true,
+		},
+		{
+			testName:     "fail test, failed to create device mount path, CSIVolumeSource found",
```
Comment (jingxu97) [inline pkg/volume/csi/csi_attacher_test.go:1049]: why CSIVolumeSource found will fail the test?

File: pkg/volume/csi/csi_attacher.go (hunk 5 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher.go:670]: Can you please elaborate the exact expected message?

**Comment by saikat-royc** [comment]
> > > is the raw block volume issue resolved too?
> > 
> > 
> > In the raw block mode, the csi drivers take the [csi_block.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go) codepath.
> > The test case added in this PR works for pdcsi works, since nodestage is a [no-op](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/node.go#L310). But the test case fails for csi-hostpath driver [here](https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/pkg/hostpath/nodeserver.go#L87), because the csi-hostpath driver finds that the volume is already staged at a different path. To me it looks like a csi-hostpath specific issue. I have skipped raw block mode in this PR.
> 
> could you open an issue for it?

https://github.com/kubernetes-csi/csi-driver-host-path/issues/345

File: pkg/volume/csi/csi_attacher_test.go (hunk 6 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher_test.go:1049]: This is because csi_attacher.go uses getPVSourceFromSpec function fails if CSIVolumeSource is detected. [code](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_util.go#L171)

File: pkg/volume/csi/csi_attacher.go (hunk 5 above)
Comment (saikat-royc) [reply pkg/volume/csi/csi_attacher.go]: Done

**Comment by xing-yang** [comment]
@saikat-royc Can you add "Action Required: " in the beginning of your release note?

File: test/e2e/storage/testsuites/provisioning.go [hunk 7]
```diff
@@ -327,6 +327,26 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
 		}
 		wg.Wait()
 	})
+
+	ginkgo.It("should mount multiple PV pointing to the same storage on the same node", func() {
+		// csi-hostpath driver does not support this test case. In this test case, we have 2 PV containing the same underlying storage.
+		// during the NodeStage call for the second volume, csi-hostpath fails the call, because it thinks the volume is already staged at a different path.
+		// Note: This is not an issue with driver like PD CSI where the NodeStage is a no-op for block mode.
```
Comment (pohly) [inline test/e2e/storage/testsuites/provisioning.go:334]: This test is also failing for PMEM-CSI. The driver fails with:

```
pmem-csi-intel-com-node-5hr56/pmem-driver@pmem..ker1: 	rpc error: code = Internal desc = mount filesystem failed: "/bin/mount -c -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-sxlkj/globalmount /var/lib/kubelet/pods/c4f6bd6f-0414-4ce2-8c2b-1c4efb637c58/volumes/kubernetes.io~csi/pv-sxlkj/mount": command failed: exit status 32
pmem-csi-intel-com-node-5hr56/pmem-driver@pmem..ker1: 	Combined stderr/stdout output: mount: /var/lib/kubelet/pods/c4f6bd6f-0414-4ce2-8c2b-1c4efb637c58/volumes/kubernetes.io~csi/pv-sxlkj/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-sxlkj/globalmount does not exist.
pmem-csi-intel-com-node-5hr56/pmem-driver@pmem..ker1:  >
```

I don't understand this comment here. Is it about the if check (next line)? Or for the entire test? Then it should come before "ginkgo.It".

About the "csi-hostpath driver does not support this test case" - does that mean that the test is making assumptions about the CSI driver, i.e. not all CSI drivers are not required to pass it? Then the test should be opt-in instead of opt-out.

File: test/e2e/storage/testsuites/provisioning.go [hunk 8]
```diff
@@ -327,6 +327,26 @@ func (p *provisioningTestSuite) DefineTests(driver storageframework.TestDriver,
...
+		if pattern.VolMode == v1.PersistentVolumeBlock {
+			e2eskipper.Skipf("skipping multiple PV mount test for block mode")
```
Comment (pohly) [inline test/e2e/storage/testsuites/provisioning.go:336]: Skipping *why"? The message doesn't add any information that itsn't already available ("skipped" is printed by e2eskipper.Skipf and the rest is part of the test name).

File: test/e2e/storage/testsuites/provisioning.go [hunk 9]
```diff
@@ -946,3 +966,65 @@ func preparePVCDataSourceForProvisioning(
...
+		ginkgo.By(fmt.Sprintf("Deleting Pod %s/%s", pod1.Namespace, pod1.Name))
+		framework.ExpectNoError(e2epod.DeletePodWithWait(client, pod1))
+	}()
+	ginkgo.By(fmt.Sprintf("Created Pod %s/%s on node %s", pod1.Namespace, pod1.Name, pod1.Spec.NodeName))
+
+	// Create new PV which points to the same underlying storage. Retain policy is used so that deletion of second PVC does not trigger the deletion of its bound PV and underlying storage.
+	e2evolume, err := getBoundPV(client, claim)
+	framework.ExpectNoError(err)
+	pv2Config := e2epv.PersistentVolumeConfig{
+		NamePrefix:       fmt.Sprintf("%s-", "pv"),
```
Comment (pohly) [inline test/e2e/storage/testsuites/provisioning.go:994]: `fmt.Sprintf("%s-", "pv")` -> `"pv-"...

**Comment by pohly** [comment]
> @saikat-royc Can you add "Action Required: " in the beginning of your release note?

That wasn't done, but it's probably too late now (release notes already published).

File: test/e2e/storage/testsuites/provisioning.go (hunk 7 above)
Comment (jsafrane) [reply test/e2e/storage/testsuites/provisioning.go:334]: > kubernetes.io/csi/pv/pv-sxlkj/globalmount does not exist.

This is odd. Point of this PR was to replace PV name in the global mount point path with `sha(volumeHandle)`. If two PVs share the same handle, they should share the global mount.
Use case: a volume that is shared into multiple namespaces and thus must have PV+PVC for each of them.

To be honest, I don't know why the test is skipped for block volumes.

Comment (jsafrane) [reply test/e2e/storage/testsuites/provisioning.go:334]: Does your test match Kubernetes version? I can imagine this can fail with older kubernetes.

Comment (pohly) [reply test/e2e/storage/testsuites/provisioning.go:334]: No, I was running it against Kubernetes 1.22. So the test fails with older Kubernetes because older kubelet didn't properly support this scenario? Re-reading the feature PR description that seems to be the case.

In a better world, the test would have a comment explaining this. As it stands now, the name of the test is "CSI driver XYZ should mount multiple PV pointing to the same storage on the same node" while in reality it is "kubelet should mount multiple PV pointing to the same storage on the same node".

But that doesn't explain the special exception for block devices and csi-driver-host-path.

**Comment by saikat-royc** [comment]
Sorry for the late reply.

Capturing summary here:
1. The code changes were done only for csi_attacher.go  and NOT for the [csi_block.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go) which is the code path taken for raw block mode. Hence there should be no behavior change for raw block mode. 
2. However when I wrote the test case  "should mount multiple PV pointing to the same storage on the same node" - I saw that the csi-hostpath driver was failing the testcase. See the conversation [here](https://github.com/kubernetes/kubernetes/pull/107065#issuecomment-1016795570), and I opened an [issue](https://github.com/kubernetes-csi/csi-driver-host-path/issues/345) to track it.  Hence I skipped the test for raw block mode to unblock the PR. 
3. FYI PD CSI driver in raw block mode handled the test case, as its a [no-op](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/release-1.5/pkg/gce-pd-csi-driver/node.go#L311) in node stage for raw block mode.

**Comment by pohly** [comment]
This still doesn't make it clearer for me. For raw block, why is the test failing with csi-driver-host-path? Is it a bug in Kubernetes (probably kubelet), in the test, or in the csi-driver-host-path?

**Comment by pohly** [comment]
If it is a bug in the driver as you suspected earlier, can you add more details to https://github.com/kubernetes-csi/csi-driver-host-path/issues/345: what happens (CSI calls), what does the driver do, what should it do instead, and why?

**Comment by humblec** [comment]
@saikat-royc can you please address https://github.com/kubernetes/kubernetes/pull/107065#issuecomment-1109477372 ?  also, are we sure, the CSI drivers dont need any changes to support this  for already working/mounted shares ? and no backward compatibility breakage ?  as an additional note here, there are volume drivers which make use of the mount path to retrieve the PV handle information ( then (some) reissue nodeStage..etc) , also some drivers look at VA and use that for recomposing the StagePath....etc ( the latter is against CSI spec , so we may skip that concern for now)  - atleast for those drivers this change is problematic.

File: test/e2e/storage/testsuites/provisioning.go (hunk 7 above)
Comment (jingxu97) [reply test/e2e/storage/testsuites/provisioning.go:334]: this change is merged for 1.24, so I think need to test your csi driver against kubernetes 1.24?
