### PR TITLE
apiserver: Fix handling patch requests with charset

### LINKED ISSUE #14872: Apiserver does not handle patch requests when Content-Type includes charset
Given a request with a Content-Type header set to `application/merge-patch+json; charset=UTF-8`, the server will respond with an error because it does not exactly match the existing `PatchType` strings.

Some browsers (Firefox, see: https://bugzilla.mozilla.org/show_bug.cgi?id=416178) will automatically add `; charset=<val>` to a Content-Type header when making an XHR request.

### PR DESCRIPTION
**Pull request by derekparker**
Fixes #14872

### CODE REVIEW

**Comment by cjcullen** [comment]
ok to test

File: pkg/apiserver/resthandler.go [hunk 1]
```diff
@@ -736,6 +737,10 @@ func setListSelfLink(obj runtime.Object, req *restful.Request, namer ScopeNamer)
 }
 
 func getPatchedJS(contentType string, originalJS, patchJS []byte, obj runtime.Object) ([]byte, error) {
+	// Remove "; charset=" if included in header.
```
Comment (lavalamp) [inline pkg/apiserver/resthandler.go]: Effectively this is broken if people send anything other than UTF-8. Should we check? Maybe just add a TODO?

**Comment by lavalamp** [comment]
LGTM, TODO optional

File: pkg/apiserver/resthandler.go (hunk 1 above)
Comment (derekparker) [inline pkg/apiserver/resthandler.go]: I think if anything a TODO would be fine. Do you want me to add one before it gets merged, or leave it for now?

Comment (lavalamp) [inline pkg/apiserver/resthandler.go]: I guess we can leave it for now, since it merged :)
