### PR TITLE
Fix sctp job flakes

### LINKED ISSUE #92041: [Flaky test] gci-gce-basic-sctp should create a Pod with SCTP HostPort
**Which jobs are failing**:

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp

**Which test(s) are failing**:

sig-network] SCTP [Feature:SCTP] [LinuxOnly] should create a Pod with SCTP HostPort

**Since when has it been failing**:

Test [sig-network] SCTP [Feature:SCTP] [LinuxOnly] should create a Pod with SCTP HostPort has failed 3 times since it last passed at commit/d49d045a3. It started failing between commit/d49d045a3 (Tue Jun 09 13:25 PDT) and commit/d62762f09 (Wed Jun 10 01:26 PDT): https://github.com/kubernetes/kubernetes/compare/d49d045a3...d62762f09?.

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-basic-sctp&show-stale-tests=

**Reason for failure**:

**Anything else we need to know**:

I'm not sure if we already did it but there was a proposal to change from dockershim to containerd for the GCE jobs

### PR DESCRIPTION
**Pull request by aojea**
We were only checking that the services or pods are created, but we should wait until the iptables rules are programmed by the corresponding components before checking.

Adding sleeps are not great but is the simpler solution and 5 seconds should be more than enough for kube-proxy or the host port manager to write the iptables rules.

It also adds support for ipv6 to the tests

/kind flake

Fixes: #92041 

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -3998,9 +3998,15 @@ var _ = SIGDescribe("SCTP [Feature:SCTP] [LinuxOnly]", func() {
 			err := cs.CoreV1().Pods(f.Namespace.Name).Delete(context.TODO(), podName, metav1.DeleteOptions{})
 			framework.ExpectNoError(err, "failed to delete pod: %s in namespace: %s", podName, f.Namespace.Name)
 		}()
+		// wait until host port manager syncs rules
+		// TODO: make this more reliable
+		time.Sleep(5 * time.Second)
```
Comment (danwinship) [inline test/e2e/network/service.go:4003]: We just need to wait for the pod to become Ready; that implies that the CNI plugin has done its work, which implies that the hostports should be set up. There's some framework method that can be used for this.

File: test/e2e/network/service.go [hunk 2]
```diff
@@ -4054,13 +4060,18 @@ var _ = SIGDescribe("SCTP [Feature:SCTP] [LinuxOnly]", func() {
 
 		err = e2enetwork.WaitForService(f.ClientSet, ns, serviceName, true, 5*time.Second, e2eservice.TestTimeout)
 		framework.ExpectNoError(err, fmt.Sprintf("error while waiting for service:%s err: %v", serviceName, err))
-
+		// wait until kube-proxy syncs rules
+		// TODO: make this more reliable
+		time.Sleep(5 * time.Second)
```
Comment (danwinship) [inline test/e2e/network/service.go:4065]: `e2enetwork.WaitForService` waits for the Service to be created, but we should wait for the _Endpoints_ to be created (which in turn implies that both the Service and the Pod have been created). There's a method for that. After that, kube-proxy is allowed to take up to `e2eservice.KubeProxyEndpointLagTimeout` to update iptables, but you should poll rather than just sleeping that whole time. There should be examples around somewhere.

Comment (aojea) [reply test/e2e/network/service.go:4065]: I thought the same, but IIUIC this test does not create endpoints, it just checks for the service reject rule.
I've checked locally with udp service without pods associated
```
-A KUBE-SERVICES -d 10.96.57.5/32 -p udp -m comment --comment "default/my-service: has no endpoints" -m udp --dport 80 -j REJECT --reject-with icmp-port-unreachable
```

File: test/e2e/network/service.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/service.go:4003]: CreateSync() already waits it is running 

https://github.com/kubernetes/kubernetes/blob/3f585835d0a38462bb928454245ec01e834e53a0/test/e2e/framework/pods.go#L99-L108

Comment (danwinship) [reply test/e2e/network/service.go:4003]: If the pod has an IP then shouldn't it be guaranteed that the hostport manager already ran?

File: test/e2e/network/service.go (hunk 2 above)
Comment (danwinship) [reply test/e2e/network/service.go:4065]: ok, in that case it should be `e2eservice.KubeProxyLagTimeout` (which is weirdly high and should probably be fixed, but anyway, definitely poll rather than sleep)

File: test/e2e/network/service.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/service.go:4003]: maybe lagging programming the iptables rules?
let me add an active polling for the iptables check

File: test/e2e/network/service.go (hunk 2 above)
Comment (aojea) [reply test/e2e/network/service.go:4065]: polling is the right way, I was a bit lazy here, sorry

**Comment by aojea** [comment]
/assign @MrHohn 
PTAL

**Review by MrHohn — APPROVED** [review]
The changes look good to me. Let's try this out.
/lgtm
/approve
