### PR TITLE
node: e2e: device plugins: Deflake e2e tests

### LINKED ISSUE #112612: ci-kubernetes-node-kubelet-serial-containerd failing device plugin test - Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Can schedule a pod that requires a device
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd

### Which tests are failing?

Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Can schedule a pod that requires a device

### Since when has it been failing?

It appears a bit flaky on testgrid, but more recently been failing more often

### Testgrid link

_No response_

### Reason for failure (if possible)

```
{Expected
    <int>: 3
to equal
    <int>: 2 failed test/e2e_node/device_plugin_test.go:184
k8s.io/kubernetes/test/e2e_node.testDevicePlugin.func1.3()
	test/e2e_node/device_plugin_test.go:184 +0x1c6}
```

example - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1572297800845103104

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Some node e2e tests check for expected number of pods running
on the node to verify the correct state of that node after running
 test scenarios. An example of such a check is in the device plugin
 end to end test here:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/device_plugin_test.go#L189-L190.
    
 If the node is not left in a clean state after an e2e test finishes
 running, it can lead to flaky tests because the node might have
 unexpected pods running on the node.
    
 In order to avoid that, we make sure that the test pods are
 cleaned up after the test runs in case log rotation e2e tests.
  
#### Which issue(s) this PR fixes:

Fixes #112612

#### Special notes for your reviewer:
Related PR that was used to debug the issue: https://github.com/kubernetes/kubernetes/pull/113165

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/framework/expect.go [hunk 1]
```diff
@@ -90,3 +90,23 @@ func ExpectHaveKey(actual interface{}, key interface{}, explain ...interface{})
 func ExpectEmpty(actual interface{}, explain ...interface{}) {
 	gomega.ExpectWithOffset(1, actual).To(gomega.BeEmpty(), explain...)
 }
+
```
Comment (oomichi) [inline test/e2e/framework/expect.go:93]: Why do we need to add the following functions?
Those functions are not used in this pull request.

Comment (swatisehgal) [reply test/e2e/framework/expect.go:93]: In my initial attempt to resolve this flake, I was going to made amendments to the device plugin e2e test by checking that the number of pods are greater than 2 instead of strict equality as in some cases there was a log rotation pod unexpectedly still running on the node. I later pivoted to an approach of making sure that the log rotation pods are cleaned up properly. 

In spite of the change of approach, I thought it would be useful to leave the functions that I added as `expect.go` is a wrapper around gomega matcher and we could benefit from some additional functions that provide us the ability to perform more granular comparisons in the future. 

I deliberately kept it as a separate commit in case it is considered unnecessary and needs to be removed.

File: test/e2e/framework/expect.go [hunk 2]
```diff
@@ -90,3 +90,23 @@ func ExpectHaveKey(actual interface{}, key interface{}, explain ...interface{})
...
+func ExpectGreaterThan(actual interface{}, extra interface{}) {
+	gomega.Expect(actual).Should(gomega.BeNumerically(">", extra))
+}
+
+// ExpectGreaterThanOrEqualTo expects actual is great than or equal to extra
+func ExpectGreaterThanOrEqualTo(actual interface{}, extra interface{}) {
+	gomega.Expect(actual).Should(gomega.BeNumerically(">=", extra))
+}
+
+// ExpectGreaterThan expects actual is great than extra
```
[the remark this answers is not in the document]
Comment (swatisehgal) [reply test/e2e/framework/expect.go:104]: Thanks, will fix.

**Comment by matthyx** [comment]
waiting for @xmcqueen enrolment to assign him...

File: test/e2e/framework/expect.go (hunk 1 above)
Comment (xmcqueen) [reply test/e2e/framework/expect.go:93]: This looks like a nice and sensible cleanup step for the device plugin test.  I see that one of the new functions is used in this test: `ExpectEqual`.  It does seem a bit out-of-place to put the other new functions in this PR, but I do like them.  I am in favor of keeping them and getting this PR going to reduce the flake count.

**Review by xmcqueen — APPROVED** [review]

File: test/e2e_node/container_log_rotation_test.go [hunk 3]
```diff
@@ -72,10 +73,20 @@ var _ = SIGDescribe("ContainerLogRotation [Slow] [Serial] [Disruptive]", func()
 					},
 				},
 			}
-			pod = e2epod.NewPodClient(f).CreateSync(pod)
+			logRotationPod = e2epod.NewPodClient(f).CreateSync(pod)
+		})
+
+		ginkgo.AfterEach(func() {
```
Comment (aojea) [inline test/e2e_node/container_log_rotation_test.go:79]: we are moving cleanups to use `ginkgo.DeferCleanup`, see https://github.com/kubernetes/kubernetes/pull/114425 as an example

**Comment by swatisehgal** [comment]
/cc @pohly @SergeyKanzhelev 

for approval

File: test/e2e/framework/expect.go [hunk 4]
```diff
@@ -90,3 +90,23 @@ func ExpectHaveKey(actual interface{}, key interface{}, explain ...interface{})
...
+
+// ExpectLessThan expects actual is less than extra
+func ExpectLessThan(actual interface{}, extra interface{}) {
+	gomega.Expect(actual).Should(gomega.BeNumerically("<", extra))
+}
+
+// ExpectLessThanOrEqualTo expects actual is less than or equal to extra
+func ExpectLessThanOrEqualTo(actual interface{}, extra interface{}) {
+	gomega.Expect(actual).Should(gomega.BeNumerically("<=", extra))
+}
```
Comment (pohly) [inline test/e2e/framework/expect.go:112]: Please use gomega directly instead of extending `expect.go`

File: test/e2e_node/container_log_rotation_test.go (hunk 3 above)
Comment (swatisehgal) [reply test/e2e_node/container_log_rotation_test.go]: Thanks, updated.

File: test/e2e/framework/expect.go (hunk 4 above)
Comment (swatisehgal) [reply test/e2e/framework/expect.go]: Ack, removed the commit where additional methods were added in order to encourage the use of gomega directly.

File: test/e2e_node/container_log_rotation_test.go [hunk 5]
```diff
@@ -72,10 +73,15 @@ var _ = SIGDescribe("ContainerLogRotation [Slow] [Serial] [Disruptive]", func()
...
+			logRotationPod = e2epod.NewPodClient(f).CreateSync(pod)
+			ginkgo.DeferCleanup(e2epod.NewPodClient(f).DeleteSync, logRotationPod.Name, metav1.DeleteOptions{}, time.Minute)
+		})
+
+		ginkgo.It("should be rotated and limited to a fixed amount of files", func(ctx context.Context) {
+
 			ginkgo.By("get container log path")
-			framework.ExpectEqual(len(pod.Status.ContainerStatuses), 1)
-			id := kubecontainer.ParseContainerID(pod.Status.ContainerStatuses[0].ContainerID).ID
+			framework.ExpectEqual(len(logRotationPod.Status.ContainerStatuses), 1)
```
Comment (pohly) [inline test/e2e_node/container_log_rotation_test.go:83]: Please add a message explaining what gets compared here.

File: test/e2e_node/device_plugin_test.go [hunk 6]
```diff
@@ -103,6 +105,18 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
 				return nodes == 1
 			}, time.Minute, time.Second).Should(gomega.BeTrue())
 
+			v1alphaPodResources, err = getV1alpha1NodeDevices()
+			framework.ExpectNoError(err)
```
Comment (pohly) [inline test/e2e_node/device_plugin_test.go:109]: Please add a message explaining which operation failed here.

File: test/e2e_node/device_plugin_test.go [hunk 7]
```diff
@@ -103,6 +105,18 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+
+			v1PodResources, err = getV1NodeDevices()
+			framework.ExpectNoError(err)
```
Comment (pohly) [inline test/e2e_node/device_plugin_test.go:112]: Please add a message explaining which operation failed here.

File: test/e2e_node/device_plugin_test.go [hunk 8]
```diff
@@ -103,6 +105,18 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+
+			// Before we run the device plugin test, we need to ensure
+			// that the cluster is in a clean state and there are no
+			// pods running on this node.
+			framework.ExpectEqual(len(v1alphaPodResources.PodResources), 0)
```
Comment (pohly) [inline test/e2e_node/device_plugin_test.go:117]:
```suggestion
			gomega.Expect(v1alphaPodResources.PodResources).To(gomega.BeEmpty(), "should have no pod resources")
```

If this goes wrong, it will print the unexpected pod resources.

File: test/e2e_node/device_plugin_test.go [hunk 9]
```diff
@@ -103,6 +105,18 @@ func testDevicePlugin(f *framework.Framework, pluginSockDir string) {
...
+			framework.ExpectEqual(len(v1PodResources.PodResources), 0)
```
Comment (pohly) [inline test/e2e_node/device_plugin_test.go:118]: Same here.

File: test/e2e_node/device_plugin_test.go (hunk 7 above)
Comment (pohly) [reply test/e2e_node/device_plugin_test.go:112]: Would also be a good enhancement for other such calls.

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e_node/container_log_rotation_test.go (hunk 5 above)
Comment (swatisehgal) [reply test/e2e_node/container_log_rotation_test.go]: Ack, Updated.

File: test/e2e_node/device_plugin_test.go (hunk 7 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: Updated, Thanks.

Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: I would be inclined to split other such fixes to a separate PR to avoid expanding the scope of this PR.

File: test/e2e_node/device_plugin_test.go (hunk 9 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: fixed, Thanks.

File: test/e2e_node/device_plugin_test.go (hunk 8 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: Fixed, Thanks.

File: test/e2e_node/device_plugin_test.go (hunk 6 above)
Comment (swatisehgal) [reply test/e2e_node/device_plugin_test.go]: Fixed, Thanks!

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
/lgtm

@SergeyKanzhelev for approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

thank you!
