### PR TITLE
Fix a regression where we never cleared out failed nodes.

### LINKED ISSUE #4166: Pod is not re-scheduled from failed node
I have 3 identical nodes, 1 replication controller with 2 replicas of a pod. I simulate failure of one of the nodes to where pods have been scheduled by simply unplugging the node. Kubernetes realizes that the node has failed, but the pod gets not re-scheduled to the another available node.

The documentation at http://git.io/buSm says the following:

> "replication controller replaces pods that are deleted or terminated for any reason, such as in the case of node failure"

and 

> "replication controller replaces pods that are deleted or terminated for any reason, such as in the case of node failure"

So is that a mistake in the documentation or a missing or a bug? I use v0.10.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #4166 and #4160

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @ddysher

File: pkg/master/pod_cache.go [hunk 1]
```diff
@@ -221,6 +227,10 @@ func (p *PodCache) GarbageCollectPodStatus() {
 // calling again, or risk having new info getting clobbered by delayed
 // old info.
 func (p *PodCache) UpdateAllContainers() {
+	// TODO: this is silly, we should pro-actively update the pod status when
+	// the API server makes changes.
+	p.clearNodeStatus()
```
Comment (bgrant0607) [inline pkg/master/pod_cache.go]: Doesn't this cause the pod's phase to become unknown? Is that sufficient to cause it to be replaced by replication controller?

Why isn't the node status updated when the node becomes unresponsive?

Comment (bgrant0607) [inline pkg/master/pod_cache.go]: Replication controller only ignores terminated pods:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/controller/replication_controller.go#L178

Comment (brendandburns) [inline pkg/master/pod_cache.go]: The node status isn't updated because we just log the error and move on:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/pod_cache.go#L242

We could certainly set Unknown there too, but we'll see pods flicker in and out in the case of transient failures.  (we would likely want to add some sort of error count to the cache.)

I updated the replication controller to filter Unknown pods also.

I will push a new cluster and see if this works correctly 



We could set unknown there too if we wanted to.

**Comment by brendandburns** [comment]
Updated, ptal.

I'd like to get this merged in so that we can cut a 0.10.1 release with this cherry-picked in.

I'm planning on writing an e2e to validate this behavior so that we don't regress in the future.

File: pkg/master/pod_cache.go (hunk 1 above)
Comment (bgrant0607) [inline pkg/master/pod_cache.go]: I don't see any changes pushed.

Comment (brendandburns) [inline pkg/master/pod_cache.go]: ugh, yes this is an insufficient fix...  hang on, will fix up.

Comment (brendandburns) [inline pkg/master/pod_cache.go]: Actually, no, now that I look at it, this will fix things.

The problem before was that because the nodeStatus cache was never cleared, we never re-polled node status, so we would never detect the node status change.

Now, when we re-poll the pod status, we will go to the nodeStatus cache, but it will be empty, so we will drive down to the node itself and get the status, and then set that into the cache.

**Comment by brendandburns** [comment]
Changes were made to replication controller.  Added comments to help explain the behavior.

If this LGTM, I will perform an empirical validation that it works, and then merge.

And then do an e2e in a subsequent PR.

Thanks
--brendan

File: pkg/master/pod_cache.go (hunk 1 above)
Comment (bgrant0607) [inline pkg/master/pod_cache.go]: But why isn't the node status periodically updated?

**Comment by bgrant0607** [comment]
I still don't see any new code pushed, btw.

**Comment by bgrant0607** [comment]
Ok, see it now.

**Comment by bgrant0607** [comment]
Note that this will cause replication controller to create new pods when nodes are temporarily unreachable.

File: pkg/master/pod_cache.go (hunk 1 above)
Comment (brendandburns) [inline pkg/master/pod_cache.go]: It is periodically updated, given that we clear the cache, and then update pod status, which forces an update to the nodeStatus too.  If you'd prefer to have two different go routines doing the periodic updates, that's ok with me too, although we're still going to want to have the read-through behavior as well to make sure that we have good data when a pod is initially created.

We could do it that way if we prefer.  That's not the way that it was previously structured.

**Comment by brendandburns** [comment]
Yep, I know.  I think given the current constraints, that's the right behavior.  It's a better place to start from than the codebase is in currently.

**Comment by bgrant0607** [comment]
True. I'll comment elsewhere. We need to fix this. The system is going to be totally unstable.

**Comment by bgrant0607** [comment]
LGTM. Are you running e2e?

**Comment by dchen1107** [comment]
cc/ @satnam6502 Haven't read the PR in detail yet. But based on the description, I think this should resolve the issue you reported through email about adds-on services.

File: pkg/master/pod_cache.go (hunk 1 above)
Comment (bgrant0607) [inline pkg/master/pod_cache.go]: Don't bother. The right solution is to eliminate nodes from the "pod cache".

**Comment by brendandburns** [comment]
e2e is confirmed to be passing with this PR.

**Comment by ddysher** [comment]
doh, my fault.  I was thinking node status is periodically updated, so didn't clear the cache...

Thanks for the fix, I was out yesterday.
