### PR TITLE
Set permissions for timestamp directory before publishing update to avoid permission denied

### LINKED ISSUE #114461: Reading from secret volume occasionally fails with `permission denied`
### What happened?

Reading files from secret volume fails with `permission denied` because files incorrectly have group owner GID 0 instead of given `fsGroup`.  The failure is associated to a change/update of the files in the secret. Failure happens only occasionally and if checking the volume manually after the error, the problem has disappeared and the files can be read successfully. The ownership is wrong only for a very short while. 

The problem started after applying file permissions `defaultMode: 0440` to the secret volume and the security context with `fsGroup: 10000`. The process that reads the files is NOT running with GID 0.

The problem may be seen as intermittent failure of the application since secrets likely have mandatory data for the application to function normally, such as TLS credentials. Applications are not likely prepared to retry opening the files several times since permission issues are not usually intermittent. 

### What did you expect to happen?

The files on secret volume mount should be readable by the process because:
* Process has privileges to read files owned by group ID 10000 - setting `fsGroup: 10000` adds 10000 to supplementary group IDs of the process
* Files on secret volume should be owned by GID 10000 because `fsGroup: 10000` was set
* The files should have group read permissions set because `defaultMode: 0440` was set

### How can we reproduce it (as minimally and precisely as possible)?

Create a small test application that does following

1. Watch the secret volume with inotify
2. Wait for inotify event `IN_MOVED_TO` (which indicates that secret has been updated and atomic rename has executed to replace the files with new ones)
3. Attempt to read files the on the volume
4. Print error to stdout if opening the file fails

Create manifest for the application with following properties

* Run the process as non-root and with GID not equal to 0
* Set `fsGroup` to non-zero e.g. `fsGroup: 10000`
* Set `defaultMode: 0440` for the secret volume

Deploy the application and start updating the secret periodically. Observe error messages in the application logs when kubelet does secret updates. The application needs to be fast between steps (2) and (3). The problem cannot be reproduced with a shell script. With application written in Go the failure rate is ~50%.

### Anything else we need to know?

When extending the above test application to list the contents of the volume recursively, it can be seen that at the time of the error the the volume mount directory and timestamp directory are owned by correct group (defined by `fsGroup`), but the actual secret files are unexpectedly owned by GID 0. Furthermore it can be seen that volume mount directory has setgid bit on, but timestamp directory does not.

This ownership issue is caused by a small time window between steps (1) and (2):

1. Kubelet AtomicWriter is writing the new files on timestamp directory. It exposes them to application by renaming `..data_tmp` to `..data` ([code link](https://github.com/kubernetes/kubernetes/blob/f63f31b9f68e87fbede9a2de24d96a672987115b/pkg/volume/secret/secret.go#L247))
2. Kubelet calls `lchown()` recursively to change owner of all files according to `fsGroup` ([code link](https://github.com/kubernetes/kubernetes/blob/f63f31b9f68e87fbede9a2de24d96a672987115b/pkg/volume/secret/secret.go#L253))

There is a race condition when application attempts to read the updated files between these two steps. 

Application will fail reading the files if it is not running with GID 0 itself. Since the timestamp directory does not have `setgid` flag set ([code link](https://github.com/kubernetes/kubernetes/blob/f63f31b9f68e87fbede9a2de24d96a672987115b/pkg/volume/util/atomic_writer.go#L371)) the files created at step (1) will be owned by GID 0 until step (2) where they become owned by GID set in `fsGroup` ([code link](https://github.com/kubernetes/kubernetes/blob/885961cda8875cce192700fe6a32ff57ba706106/pkg/volume/volume_linux.go#L73)).

The same problem likely applies to ConfigMaps as well, since the update logic is the same.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

N/A

### OS version

N/A

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by tsaarni**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This change fixes a race condition that was caused by setting the file owner, group and mode non-atomically, after the updated files had been published.
    
Users who were running non-root containers, without GID 0 permissions were getting intermittent `permission denied` errors if accessing the files during update, when they had removed read permissions from other users by setting `defaultMode: 0440` or similar and relied on `fsGroup` permissions for reading. This impacts secret and configmap volumes, and service account tokens on projected volumes.

This bug makes the system susceptible to a race condition and causes hard-to-troubleshoot intermittent failure of the application since the files likely have mandatory data for the application to function normally, such as TLS credentials. Applications are not likely prepared to retry opening the files several times since permission issues are not usually intermittent.

#### Which issue(s) this PR fixes:

Fixes #114461

#### Special notes for your reviewer:

Following repository contains manual test procedure to reproduce the fault https://github.com/tsaarni/kubernetes-secret-race.

#### Does this PR introduce a user-facing change?

```release-note
Fixed file permission issues that happened during update of Secret/ConfigMap/projected volume when fsGroup is used. The problem caused a race condition where application gets intermittent permission denied error when reading files that were just updated, before the correct permissions were applied.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

**Comment by tsaarni** [comment]
Hi @humblec and @msau42, could you please take a look at this PR? Thank you!

**Comment by tsaarni** [comment]
I've updated the PR to cover also related race condition with token on projected volume.

**Comment by humblec** [comment]
Please check the unit test failure.

**Comment by tsaarni** [comment]
> Please check the unit test failure.

Done! 

Since the PR proposes setting the final mode bits already in the payload struct, I now have changed the test to check for `0640`. This is the actual permission that has always been applied to files on disk - so no change from that perspective.  

Since the test case does not check for actual file permissions on disk, but instead only tests the payload struct, it checked for `0600` previously even though it was later overwritten with `0640` by `SetVolumeOwnership()` (this call is not included in the unit test).

**Comment by furkatgofurov7** [comment]
> Please check the unit test failure.

@humblec can you please take a look again? Thanks. 
/cc @jsafrane @xing-yang @thockin hey folks! Can you please also take a look at this patch when you have some time, thank you!

File: pkg/volume/projected/projected.go [hunk 1]
```diff
@@ -321,12 +321,13 @@ func (s *projectedVolumeMounter) collectData(mounterArgs volume.MounterArgs) (ma
 		case source.ServiceAccountToken != nil:
 			tp := source.ServiceAccountToken
 
-			// When FsGroup is set, we depend on SetVolumeOwnership to
-			// change from 0600 to 0640.
 			mode := *s.source.DefaultMode
-			if mounterArgs.FsUser != nil || mounterArgs.FsGroup != nil {
+			if mounterArgs.FsUser != nil {
```
Comment (thockin) [inline pkg/volume/projected/projected.go:325]: This block is confusing - what if both are set?  Can we leve some comments, please

**Review by thockin — COMMENTED** [review]
It feels like the real problem is that we finish the atomic `Write()` without calling `SetVolumeOwnership()`.  Should that be done BEFORE actually publishing the contents?  Maybe pass some callback into Write() ?

File: pkg/volume/projected/projected.go (hunk 1 above)
Comment (tsaarni) [reply pkg/volume/projected/projected.go]: I've clarified the block a little: FsGroup shall take precedence (so outcome still follows [Case 1 here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/1205-bound-service-account-tokens#proposed-heuristics)).

**Comment by tsaarni** [comment]
> It feels like the real problem is that we finish the atomic `Write()` without calling `SetVolumeOwnership()`. Should that be done BEFORE actually publishing the contents? Maybe pass some callback into Write() ?

I was wondering that too. My thinking is: 

`SetVolumeOwnership()` fixes up permissions in the whole volume by recursively changing every file. Since we know exactly which files we create and which permissions they need, it seemed unnecessary to first create them with wrong permissions and then go through them again to correct them. 

Maybe secondary aspect is that `SetVolumeOwnership()` works on volume level. We know that the updated files are in the new timestamp directory. It seems bit redundant to go through the whole volume, including the old versions of the files that were already corrected during previous update, and will be removed at the last step of this update. 

Maybe there could be a new version of `SetVolumeOwnership()` that only touches the timestamp directory, but then again: why not set the correct permissions from the beginning? Doing the latter seemed minimal and maybe also less riskier change to fix the bug.

**Comment by kashifest** [comment]
> but then again: why not set the correct permissions from the beginning? Doing the latter seemed minimal and maybe also less riskier change to fix the bug.

+1 on this. @thockin wdyt?

**Comment by thockin** [comment]
Yeah, `SetVolumeOwnership()` is a little coarse for what we would want.  My fear is that we do something "manual" here and miss something or maybe later something changes there and it works everywhere EXCEPT here.  Doubly so because this same problem exists in projected, secret, configmap, and downwardapi volumes.  You can't just fix it in one place.

What if we changed `SetVolumeOwnership` to take an optional "subpath" argument and then changed `AtomicWriter.Write()` to take a "set permissions" function.  Something like:

```diff
diff --git a/pkg/volume/projected/projected.go b/pkg/volume/projected/projected.go
index a48567b2a6a..ef4b56b1680 100644
--- a/pkg/volume/projected/projected.go
+++ b/pkg/volume/projected/projected.go
@@ -230,15 +230,12 @@ func (s *projectedVolumeMounter) SetUpAt(dir string, mounterArgs volume.MounterA
 		return err
 	}
 
-	err = writer.Write(data)
-	if err != nil {
-		klog.Errorf("Error writing payload to dir: %v", err)
-		return err
+	setPerms := func(subPath string) error {
+		return volume.SetVolumeOwnership(s, subPath, mounterArgs.FsGroup, nil /*fsGroupChangePolicy*/, volumeutil.FSGroupCompleteHook(s.plugin, nil))
 	}
-
-	err = volume.SetVolumeOwnership(s, mounterArgs.FsGroup, nil /*fsGroupChangePolicy*/, volumeutil.FSGroupCompleteHook(s.plugin, nil))
+	err = writer.Write(data, setPerms)
 	if err != nil {
-		klog.Errorf("Error applying volume ownership settings for group: %v", mounterArgs.FsGroup)
+		klog.Errorf("Error writing payload to dir: %v", err)
 		return err
 	}
 	setupSuccess = true
diff --git a/pkg/volume/util/atomic_writer.go b/pkg/volume/util/atomic_writer.go
index 94428f6ffc8..4ff0fd1ba40 100644
--- a/pkg/volume/util/atomic_writer.go
+++ b/pkg/volume/util/atomic_writer.go
@@ -125,7 +125,7 @@ const (
 //
 // 10.  Old paths are removed from the user-visible portion of the target directory
 // 11.  The previous timestamped directory is removed, if it exists
-func (w *AtomicWriter) Write(payload map[string]FileProjection) error {
+func (w *AtomicWriter) Write(payload map[string]FileProjection, setPerms func(subPath string) error) error {
 	// (1)
 	cleanPayload, err := validatePayload(payload)
 	if err != nil {
@@ -182,6 +182,12 @@ func (w *AtomicWriter) Write(payload map[string]FileProjection) error {
 		klog.Errorf("%s: error writing payload to ts data directory %s: %v", w.logContext, tsDir, err)
 		return err
 	}
+	if setPerms != nil {
+		if err := setPerms(tsDirName); err != nil {
+			// FIXME: log an error
+			return err
+		}
+	}
 	klog.V(4).Infof("%s: performed write of new data to ts data directory: %s", w.logContext, tsDir)
 
 	// (7)
diff --git a/pkg/volume/volume_linux.go b/pkg/volume/volume_linux.go
index 57c02815029..cf463910520 100644
--- a/pkg/volume/volume_linux.go
+++ b/pkg/volume/volume_linux.go
@@ -40,7 +40,7 @@ const (
 // SetVolumeOwnership modifies the given volume to be owned by
 // fsGroup, and sets SetGid so that newly created files are owned by
 // fsGroup. If fsGroup is nil nothing is done.
-func SetVolumeOwnership(mounter Mounter, fsGroup *int64, fsGroupChangePolicy *v1.PodFSGroupChangePolicy, completeFunc func(types.CompleteFuncParam)) error {
+func SetVolumeOwnership(mounter Mounter, subPath string, fsGroup *int64, fsGroupChangePolicy *v1.PodFSGroupChangePolicy, completeFunc func(types.CompleteFuncParam)) error {
 	if fsGroup == nil {
 		return nil
 	}
@@ -55,7 +55,7 @@ func SetVolumeOwnership(mounter Mounter, fsGroup *int64, fsGroupChangePolicy *v1
 		return nil
 	}
 
-	err := walkDeep(mounter.GetPath(), func(path string, info os.FileInfo, err error) error {
+	err := walkDeep(filepath.Join(mounter.GetPath(), subPath), func(path string, info os.FileInfo, err error) error {
 		if err != nil {
 			return err
 		}
```

**Comment by tsaarni** [comment]
@thockin I pushed a new commit according to your suggestion. However, I have left `SetVolumeOwnership()` as it was, even though I first commented about the granularity. My reasoning is that we should still set the permissions of all files at least during initial write.  I've also added a new test case for `setPerms()` call.

File: pkg/volume/util/atomic_writer.go [hunk 2]
```diff
@@ -103,8 +103,10 @@ const (
 //  6. The payload is written to the new timestamped directory
 //     7.  A symlink to the new timestamped directory ..data_tmp is created that will
 //     become the new data directory
-//     8.  The new data directory symlink is renamed to the data directory; rename is atomic
-//     9.  Symlinks and directory for new user-visible files are created (if needed).
+//
+//  8. Set the permissions of the files.
```
Comment (thockin) [inline pkg/volume/util/atomic_writer.go:107]: This whole comment block is weird, but if we are sticking to style, I'd prefer this as:

```
6.  The payload is written to the new timestamped directory
    7. Permissions are set (if setPerms is not nil) on the new timestamped directory and files
    8. A symlink to ...
    9. The new data directory symlink ...
    10. Symlinks and directory for new ...
```

In particular, I think setPerms should be after write, BEFORE symlink

File: pkg/volume/util/atomic_writer.go [hunk 3]
```diff
@@ -193,6 +195,14 @@ func (w *AtomicWriter) Write(payload map[string]FileProjection) error {
 	}
 
 	// (8)
+	if setPerms != nil {
+		if err := setPerms(); err != nil {
+			klog.Errorf("%s: error applying volume ownership settings: %v", w.logContext, err)
```
Comment (thockin) [inline pkg/volume/util/atomic_writer.go:200]: drop "volume" here - it's minor but this makes it a smidge more general purpose

File: pkg/volume/util/atomic_writer.go [hunk 4]
```diff
@@ -193,6 +195,14 @@ func (w *AtomicWriter) Write(payload map[string]FileProjection) error {
 	}
 
 	// (8)
+	if setPerms != nil {
+		if err := setPerms(); err != nil {
```
Comment (thockin) [inline pkg/volume/util/atomic_writer.go:199]: As a reader I am confused - if we don't pass the name of the dir we just made, what is `setPerms()` supposed to do?  Maybe we should pass subPath to the function and then the volumes can choose to disregard it if they want and do the whole volume instead (and they can comment why).

Can you add a note to the function comment explaining the contract with setPerms (and that it is optional).

File: pkg/volume/util/atomic_writer_test.go [hunk 5]
```diff
@@ -984,3 +985,46 @@ func TestCreateUserVisibleFiles(t *testing.T) {
 		}
 	}
 }
+
+func TestSetPerms(t *testing.T) {
```
Comment (thockin) [inline pkg/volume/util/atomic_writer_test.go:989]: thanks for a good test!

**Review by thockin — COMMENTED** [review]
Looking pretty good!  Can you please:

1) retitle the PR
2) update the 1st PR comment
3) Write a good commit comment (maybe most of the same as the PR comment)
4) Shorten the commit first-line (git has a length limit :)

We're not always rgorous about commit hygiene but we are trying.

File: pkg/volume/util/atomic_writer.go (hunk 2 above)
Comment (tsaarni) [reply pkg/volume/util/atomic_writer.go]: Fixed. 

The was some formatting that confused `gofmt` and it did not parse the numbered list anymore as numbered list properly.

I changed the order of setPerms and creation of `..data_tmp` symlink.

File: pkg/volume/util/atomic_writer.go (hunk 3 above)
Comment (tsaarni) [reply pkg/volume/util/atomic_writer.go]: Fixed!

File: pkg/volume/util/atomic_writer.go (hunk 4 above)
Comment (tsaarni) [reply pkg/volume/util/atomic_writer.go]: I've added the parameter and comment to volume implementations. I called it `tsDir` instead of `subPath` because while updating the test case I realized the path inside `Write()` was full path and not just the subdir.

**Comment by tsaarni** [comment]
> Looking pretty good! Can you please:
> 
> 1. retitle the PR
> 2. update the 1st PR comment
> 3. Write a good commit comment (maybe most of the same as the PR comment)
> 4. Shorten the commit first-line (git has a length limit :)
> 
> We're not always rgorous about commit hygiene but we are trying.

@thockin Thank you again for the review, much appreciated! I've now fixed the above.

In case needed, I've also published my test application and manual test procedure which I've been using, [available here](https://github.com/tsaarni/kubernetes-secret-race).

File: pkg/volume/configmap/configmap.go [hunk 6]
```diff
@@ -249,17 +249,17 @@ func (b *configMapVolumeMounter) SetUpAt(dir string, mounterArgs volume.MounterA
 		return err
 	}
 
-	err = writer.Write(payload)
+	setPerms := func(tsDir string) error {
```
Comment (thockin) [inline pkg/volume/configmap/configmap.go:252]: if you are going to ignore the argument, name it `_` which tells Go it can safely optimize and tells readers this was on purpose

File: pkg/volume/util/atomic_writer.go [hunk 7]
```diff
@@ -86,25 +86,35 @@ const (
 
 // Write does an atomic projection of the given payload into the writer's target
 // directory.  Input paths must not begin with '..'.
+// setPerms is an optional pointer to a function that caller can provide to set the
+// permissions of the newly created files before they are published. The function is
+// passed tsDir which is full path to timestamp subdir.
```
Comment (thockin) [inline pkg/volume/util/atomic_writer.go:91]: full path or relative to the writer's root?

File: pkg/volume/util/atomic_writer.go [hunk 8]
```diff
@@ -185,14 +196,22 @@ func (w *AtomicWriter) Write(payload map[string]FileProjection) error {
 	klog.V(4).Infof("%s: performed write of new data to ts data directory: %s", w.logContext, tsDir)
 
 	// (7)
+	if setPerms != nil {
+		if err := setPerms(tsDir); err != nil {
```
Comment (thockin) [inline pkg/volume/util/atomic_writer.go:200]: I think it's simpler to pass `tsDirName` which is the basename

**Review by thockin — COMMENTED** [review]
just nits left

File: pkg/volume/configmap/configmap.go (hunk 6 above)
Comment (tsaarni) [reply pkg/volume/configmap/configmap.go]: Fixed

File: pkg/volume/util/atomic_writer.go (hunk 8 above)
Comment (tsaarni) [reply pkg/volume/util/atomic_writer.go]: I've replaced the absolute path with this one, renamed the parameter to `subPath` and changed the comment accordingly.

File: pkg/volume/util/atomic_writer.go (hunk 7 above)
Comment (tsaarni) [reply pkg/volume/util/atomic_writer.go]: Absolute path is now replaced with the timestamp directory name.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by furkatgofurov7** [comment]
@thockin hi, thanks a lot for the review. Can this PR be considered to be backported to older branches? 
cc @kubernetes/sig-release-leads

**Comment by thockin** [comment]
I could make an argument for 1.26 but I don't know if going back much farther is worth the risk.  It's not high-urgency (it self-resolves and it has not come up as a problem before), so if I were branch manager I would probably decline.

**Comment by furkatgofurov7** [comment]
> I could make an argument for 1.26 but I don't know if going back much farther is worth the risk.

@thockin thank you, I guess backporting it to the latest release branch is safe and considering your comment, I have created a backport for 1.26 here: https://github.com/kubernetes/kubernetes/pull/114728 PTAL.
