### PR TITLE
apf: clarify with comment

### LINKED ISSUE #107097: Various bugs in APF configuration producing controller
### What happened?

While reviewing #105800 I noticed some things.

1. The annotation key `apf.kubernetes.io/autoupdate-spec` is not mentioned anywhere in the user-facing documentation (https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) --- but it should be.

2. https://github.com/kubernetes/kubernetes/blob/712745cb6755b3a28ca12292b30d138d5f737aa6/pkg/registry/flowcontrol/ensurer/strategy.go still references v1beta1 even though we now have v1beta2.

3. https://github.com/kubernetes/kubernetes/blob/712745cb6755b3a28ca12292b30d138d5f737aa6/pkg/registry/flowcontrol/ensurer/strategy.go#L311-L314 ignores the value of the annotation --- which is wrong.

### What did you expect to happen?

Perfection

### How can we reproduce it (as minimally and precisely as possible)?

Should be clear from the above.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
current `master` branch
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:
Fixes #107097

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/registry/flowcontrol/ensurer/strategy.go [hunk 1]
```diff
@@ -298,6 +298,10 @@ func removeConfiguration(wrapper configurationWrapper, name string) error {
 // Any object present in current is a candidate for removal if both a and b are true:
 //  a. the object in current is missing from the bootstrap configuration
 //  b. the object has the designated auto-update annotation key
+//
+// 'removeConfiguration' checks the value of the annotation key before it makes
```
Comment (MikeSpreitzer) [inline pkg/registry/flowcontrol/ensurer/strategy.go:302]: This comment belongs on removeConfiguration, not getRemoveCandidate.
The comment on getRemoveCandidate should say that what is returned is a list of names of objects to _conditionally_ remove.

BTW, why is there a separation between getRemoveCandidate and removeConfiguration?  Why not do it all in one method?

BTW, getRemoveCandidate is named singular and returns plural.

Comment (MikeSpreitzer) [reply pkg/registry/flowcontrol/ensurer/strategy.go:302]: The name "removeConfiguration" is unconditional but the behavior is conditional.

Why is the test of the auto-update annotation in removeConfiguration rather than in getRemoveCandidate(s)?

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer 
/sig api-machinery

**Comment by MikeSpreitzer** [comment]
https://github.com/kubernetes/kubernetes/blob/2b32b4b3527b16dece4483734f4b79b3593f237f/pkg/registry/flowcontrol/ensurer/flowschema.go#L44 still does not mention the conditionality.

https://github.com/kubernetes/kubernetes/blob/2b32b4b3527b16dece4483734f4b79b3593f237f/pkg/registry/flowcontrol/ensurer/flowschema.go#L46 has an unconditional name and no comment.

Why does `getRemoveCandidates` check for the presence of the autoupdate key, given that the `removeConfiguration` func will also check for the presence (as well as the value) of the key?  Why not check the value of the key in `getRemoveCandidates`?  Why split the behavior between one func to get candidates and another func to finish validating them and remove them?

**Comment by tkashem** [comment]
> Why is the test of the auto-update annotation in removeConfiguration rather than in getRemoveCandidate(s)?

`removeAutoUpdateEnabledConfiguration` has the proper check whether auto update is enabled. I think it makes sense to have the full check just before actual deletion. 

`getDanglingBootstrapObjectNames` checks to see if the key is present to avoid returning all user defined configuration objects, it's a bit of an optimization.

**Comment by MikeSpreitzer** [comment]
My biggest question is why `removeFlowSchema` is broken into two separate calls into the ensurer:

```
	candidates, err := ensurer.GetFlowSchemaRemoveCandidate(lister, bootstrap)
	if err != nil {
		return err
	}
	if len(candidates) == 0 {
		return nil
	}

	fsRemover := ensurer.NewFlowSchemaRemover(client, lister)
	return fsRemover.Remove(candidates)
```

Why not just make it `return ensurer.RemoveUnwanted(client, lister, bootstrap)`?

**Review by MikeSpreitzer — APPROVED** [review]
I think we can do better, but I am willing to accept this as progress.
/lgtm
