### PR TITLE
fix validate-cluster.sh

### LINKED ISSUE #47379: test failure: cluster 1.6->1.7 upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]
cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade]

connection refused in version check

[job failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-6-cvm-1-7-upgrade-cluster/7#k8sio-upgrade-featureupgrade-k8sio-cluster-upgrade-should-maintain-a-functioning-cluster-featureclusterupgrade)

[history](https://k8s-testgrid.appspot.com/1.6-1.7-upgrade#gke-cvm-upgrade-cluster&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Upgrade%5C%20%5C%5BFeature%5C%3AUpgrade%5C%5D%5C%20%5C%5Bk8s%5C.io%5C%5D%5C%20cluster%5C%20upgrade%5C%20should%5C%20maintain%5C%20a%5C%20functioning%5C%20cluster%5C%20%5C%5BFeature%5C%3AClusterUpgrade%5C%5D)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:122
Expected error:
    <*errors.errorString | 0xc4201ca640>: {
        s: "CheckMasterVersion() couldn't get the master version: Get https://35.188.215.192/version: dial tcp 35.188.215.192:443: getsockopt: connection refused",
    }
    CheckMasterVersion() couldn't get the master version: Get https://35.188.215.192/version: dial tcp 35.188.215.192:443: getsockopt: connection refused
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/cluster_upgrade.go:108
```

/sig networking
/assign @bowei 

See also #44563

### PR DESCRIPTION
**Pull request by caesarxuchao**
attempt to fix #47379.

Without this fix, the validate-cluster.sh never retries if `kubectl-retry get cs` fails.

cc @dchen1107

### CODE REVIEW

File: cluster/validate-cluster.sh [hunk 1]
```diff
@@ -170,7 +170,7 @@ while true; do
 done
 
 echo "Validate output:"
-kubectl_retry get cs
+return_value=$(kubectl_retry get cs)
```
Comment (gmarek) [inline cluster/validate-cluster.sh]: We want `echo $return_value` here as well.

Comment (gmarek) [inline cluster/validate-cluster.sh]: This is wrong. `return_value` is used in `exit` call, which expects integer, plus you shouldn't overwrite what's currently stored in `return_value`.

IIUC your main goal is to to prevent `errexit` to kill the script when `get cs` fails. If that's the case you should write:
```
echo $(kubectl_retry get cs || true)
```

Comment (caesarxuchao) [inline cluster/validate-cluster.sh]: Yes. Thanks.

**Comment by caesarxuchao** [comment]
@gmarek @krzyzacy could you take another look? Thanks.

**Comment by dchen1107** [comment]
Can we run validation_cluster.sh with the new change against the existing k8s cluster to verify the change? upgrade.sh is flaky. Without any change, the new run of 
both master and nodes are successfully upgraded to 1.7 in a new run: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1-6-1-7-upgrade-cluster/55?log#log

```
I0620 10:54:17.484] == Finished upgrading nodes to v1.7.0-beta.2.120+c8cd7f318aea33. ==
I0620 10:54:17.484] == Validating cluster post-upgrade ==
I0620 10:54:17.519] Validating gce cluster, MULTIZONE=
I0620 10:54:17.520] Project: gce-up-c1-3-g1-4-up-clu
I0620 10:54:17.520] Zone: us-central1-f
I0620 10:54:18.571] Found 4 node(s).
I0620 10:54:18.774] NAME                              STATUS                     AGE       VERSION
I0620 10:54:18.774] bootstrap-e2e-master              Ready,SchedulingDisabled   13m       v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-4jm4   Ready                      8m        v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-gw1d   Ready                      4m        v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:18.774] bootstrap-e2e-minion-group-km98   Ready                      23s       v1.7.0-beta.2.120+c8cd7f318aea33
I0620 10:54:19.486] Validate output:
I0620 10:54:20.191] NAME                 STATUS    MESSAGE              ERROR
I0620 10:54:20.191] controller-manager   Healthy   ok                   
I0620 10:54:20.191] scheduler            Healthy   ok                   
I0620 10:54:20.191] etcd-0               Healthy   {"health": "true"}   
I0620 10:54:20.191] etcd-1               Healthy   {"health": "true"}   
I0620 10:54:20.195] Cluster validation succeeded
I0620 10:54:20.195] == Post-Upgrade Node OS and Kubelet Versions ==
I0620 10:54:20.395] name: "bootstrap-e2e-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-4jm4", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-gw1d", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"
I0620 10:54:20.395] name: "bootstrap-e2e-minion-group-km98", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.7.0-beta.2.120+c8cd7f318aea33"

```

**Comment by dchen1107** [comment]
@caesarxuchao and I did validation this change against a non-exist cluster. It works as expected. Thanks!
