### PR TITLE
Fix a race in setting nominated node and the scheduling cycle after it.

### LINKED ISSUE #72124: Race condition in preemption logic of the scheduler when setting nominatedNodeName
**What happened**:
Setting nominatedNodeName has an inherent race:
1. The scheduler tries a pod and finds it unschedulable.
1. The preemption logic tries and finds a node to schedule the pod (with or without preempting any other pod).
1. The scheduler sends a pod update to update nominatedNodeName of the pod.
    The scheduler has NOT received the pod update for setting "nominatedNodeName" yet.
1. The scheduler tries another pod and finds the same node schedulable. So, it binds the second pod.
1. The nominated Pod has the nominatedNodeName set, but the resources on the node are already taken by another pod, so the nominated pod is no longer schedulable on that node.

The race that I described above can cause an issue:
1. There is a pod which has nominatedNodeName, but is affected by the above race.
1. A smaller pod with the same priority is scheduled on the same node (due to the above race condition).
1. There is enough room on the node for other small pods, but since there exists a nominated pod for the node, other smaller pods won't be scheduled there. The nominated pod cannot be scheduled there either, because the available resources are partially taken by the other smaller pod and there are not enough resources for the nominated pod.

**What you expected to happen**:

The race condition in setting nominatedNodeName must be eliminated. We should use a similar approach to "assume" to update the scheduler cache with nominated pods early and not wait for pod status updates.

/kind bug

/sig scheduling
/assign

### PR DESCRIPTION
**Pull request by bsalamat**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
It fixes the issue reported in #72124.

**Which issue(s) this PR fixes**:

Fixes #72124

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix a race condition in the scheduler preemption logic that could cause nominatedNodeName of a pod not to be considered in one or more scheduling cycles.
```

/sig scheduling

### CODE REVIEW

File: test/integration/scheduler/preemption_test.go [hunk 1]
```diff
@@ -490,6 +491,119 @@ func TestPreemptionStarvation(t *testing.T) {
 	}
 }
 
+// TestPreemptionRaces tests that other scheduling events and operations do not
+// race with the preemption process.
+func TestPreemptionRaces(t *testing.T) {
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption_test.go]: Did you succeed to run this test with an expected error? I mean without other code fixes.

I tried several times and they all passed without errors.

Comment (bsalamat) [reply test/integration/scheduler/preemption_test.go]: I have managed to get it fail, but give that there is race condition that is hard to reproduce, you need to set numRepitions high and sometimes run several times.
I tried finding a way to simulate late arrival of events, but I didn't find a reasonable way to do so.

Comment (bsalamat) [reply test/integration/scheduler/preemption_test.go]: I should add that my reasons for adding it was to at least see a flaky test if a race condition exists.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 2]
```diff
@@ -326,14 +288,13 @@ func (p *PriorityQueue) Add(pod *v1.Pod) error {
 	}
 	if p.unschedulableQ.get(pod) != nil {
 		klog.Errorf("Error: pod %v/%v is already in the unschedulable queue.", pod.Namespace, pod.Name)
-		p.deleteNominatedPodIfExists(pod)
```
Comment (yastij) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: Souldn’t we make sure that the pod in the unschedulable queue isn’t nominated anymore by calling a delete ?

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 3]
```diff
@@ -758,3 +726,78 @@ func newUnschedulablePodsMap() *UnschedulablePodsMap {
...
+	// nominated.
+	nominatedPodToNode map[ktypes.UID]string
+}
+
+func (npm *nominatedPodMap) add(p *v1.Pod, nodeName string) {
+	// always delete the pod if it already exist, to ensure we never store more than
+	// one instance of the pod.
+	npm.delete(p)
+
+	nnn := nodeName
```
Comment (yastij) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: Can we replace nnn by nominatedNodeName here, the intent will be much clearer.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: Agree. Miss `p.nominatedPods.delete(pod)` here?

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: ok, I think it's because at Line 297, `p.nominatedPods.add(pod, "")` implicitly delete the pod from cache. But it sounds weird to me that we delete pod in an "add" function?

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 4]
```diff
@@ -758,3 +726,78 @@ func newUnschedulablePodsMap() *UnschedulablePodsMap {
...
+	nominatedPods map[string][]*v1.Pod
+	// nominatedPodToNode is map keyed by a Pod UID to the node name where it is
+	// nominated.
+	nominatedPodToNode map[ktypes.UID]string
+}
+
+func (npm *nominatedPodMap) add(p *v1.Pod, nodeName string) {
+	// always delete the pod if it already exist, to ensure we never store more than
+	// one instance of the pod.
+	npm.delete(p)
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: Is there a particular reason to embed "delete" in an "add" function?

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 5]
```diff
@@ -157,8 +169,15 @@ func TestPriorityQueue_AddUnschedulableIfNotPresent(t *testing.T) {
 	q.AddUnschedulableIfNotPresent(&highPriNominatedPod) // Must not add anything.
 	q.AddUnschedulableIfNotPresent(&medPriorityPod)      // This should go to activeQ.
 	q.AddUnschedulableIfNotPresent(&unschedulablePod)
-	expectedNominatedPods := map[string][]*v1.Pod{
-		"node1": {&highPriNominatedPod, &medPriorityPod, &unschedulablePod},
+	expectedNominatedPods := &nominatedPodMap{
+		nominatedPodToNode: map[types.UID]string{
+			medPriorityPod.UID:      "node1",
```
Comment (wgliang) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go]: `Pod.UID` is `node1` It doesn't look very suitable. `pod1` is acceptable.

Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go]: `node1` is not a Pod UID. This is a map from a pod UID to a node name. `node1` is the node name.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 2 above)
Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: As @Huang-Wei noted, this is no longer needed as the `add` function of nominated node struct ensures that there won't be duplicate entries. I think `add` is still the best name for it. Any other suggestions?

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 3 above)
Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: `nnn` is a common pattern in other functions and is more idiomatic in Go than long names.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 6]
```diff
@@ -758,3 +726,78 @@ func newUnschedulablePodsMap() *UnschedulablePodsMap {
...
+	npm.nominatedPods[nnn] = append(npm.nominatedPods[nnn], p)
+}
+
+func (npm *nominatedPodMap) delete(p *v1.Pod) {
+	nnn, ok := npm.nominatedPodToNode[p.UID]
+	if !ok {
+		return
+	}
+	for i, np := range npm.nominatedPods[nnn] {
+		if np.UID != p.UID {
```
[the remark this answers is not in the document]
Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: Done

**Review by Huang-Wei — COMMENTED** [review]
@bsalamat thanks for the PR!

Please squash last commit (3 commits in total is fine).

**Comment by bsalamat** [comment]
@Huang-Wei Done
