### PR TITLE
Convert cmd/kubelet/app/server.go to structured logging

### LINKED ISSUE #98292: In the kubelet flags validity check, is it reasonable to use klog.Fatal？
**What would you like to be added**:
In the flag verification of the kubelet component, if the verification fails, call klog.fatal directly to print the log and exit. At this time, all trace information will be printed out,  I think it  is no need.
For example，Kubelet execution with an unknown flag --hh， then print
...........
F0122 13:11:28.521365   30211 server.go:156] unknown flag: --hh
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc000d639c0, 0x40, 0x40)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x730afe0, 0xc000000003, 0x0, 0x0, 0xc000d515e0, 0x6f6950f, 0x9, 0x9c, 0x411000)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x730afe0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00004b580, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1482
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000903340, 0xc00000e070, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:156 +0x147b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000903340, 0xc00000e070, 0x1, 0x1, 0xc000903340, 0xc00000e070)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000903340, 0x165c75cc9fe893dd, 0x730aa00, 0x409085)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x730afe0)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 95 [select]:
k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000113450)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 102 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4a94b40, 0x4f31fe0, 0xc000ae93b0, 0x1, 0xc0000c2120)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4a94b40, 0x12a05f200, 0x0, 0xc000b67901, 0xc0000c2120)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x4a94b40, 0x12a05f200)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a

**Why is this needed**:
Similar to other components, no trace information is printed.
Or only the current trace is printed.

For example，Kubelet execution with an unknown flag --hh， then print
E0122 13:27:14.369473   15611 server.go:156] unknown flag: --hh
or
F0122 13:19:37.055696    3781 server.go:156] unknown flag: --hh
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010000, 0xc0009d4e40, 0x40, 0x40)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1027 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x730afe0, 0xc000000003, 0x0, 0x0, 0xc0008b2000, 0x6f6950f, 0x9, 0x9c, 0x411000)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:976 +0x19b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x730afe0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000c12a10, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1483
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc00053fb80, 0xc00000e070, 0x1, 0x1)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:156 +0x147b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00053fb80, 0xc00000e070, 0x1, 0x1, 0xc00053fb80, 0xc00000e070)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00053fb80, 0x165c763e5ea79f2b, 0x730aa00, 0x409085)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /codeworkspace/kubernetes-github-myspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xe5

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When the parameters are incorrect, kubelet only outputs the error log instead of the entire stack log
This way the user experience will be better and consistent with other components (such as kube-proxy)

**Which issue(s) this PR fixes**:

Fixes #98292

**Special notes for your reviewer**:
For compatibility, refer to `klog.Fatalf` Exit code remains 255

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node
/area kubelet

### CODE REVIEW

**Comment by ehashman** [comment]
/hold

Bug wasn't accepted and I'm not sure this is an improved user experience.

**Comment by ehashman** [comment]
Note: I think Fatal logs are going away anyways with the structured logging migration this release, so this PR will be replaced soon anyways. See: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls

It would be better to migrate this entire file to use structured logging rather than just making this change.

**Comment by wawa0210** [comment]
> It would be better to migrate this entire file to use structured logging rather than just making this change.

Understand, if possible, I want this pr to fix this bug alone (keep focus). Then reopen a pr to migrate the entire file to use structured logs. What do you think?

**Comment by ehashman** [comment]
> > It would be better to migrate this entire file to use structured logging rather than just making this change.
> 
> Understand, if possible, I want this pr to fix this bug alone (keep focus). Then reopen a pr to migrate the entire file to use structured logs. What do you think?

I would prefer you fix it all in one go, because migrating away from using `Fatalf` is part of the log migration, and we have limited reviewer/approver bandwidth.

File: cmd/kubelet/app/server.go [hunk 1]
```diff
@@ -117,7 +117,8 @@ func NewKubeletCommand() *cobra.Command {
 	kubeletConfig, err := options.NewKubeletConfiguration()
 	// programmer error
 	if err != nil {
-		klog.Fatal(err)
+		klog.ErrorS(err, "Failed create a new kubelet configuration")
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:120]:
```suggestion
		klog.ErrorS(err, "Failed to create a new kubelet configuration")
```

File: cmd/kubelet/app/server.go [hunk 2]
```diff
@@ -117,7 +117,8 @@ func NewKubeletCommand() *cobra.Command {
...
+		os.Exit(255)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:121]: Please use exit code 1 throughout this file, and not 255, to be consistent with the rest of the files in `cmd/`: https://cs.k8s.io/?q=os.Exit&i=nope&files=cmd%2F.*&repos=kubernetes/kubernetes

File: cmd/kubelet/app/server.go [hunk 3]
```diff
@@ -152,21 +153,24 @@ HTTP server: The kubelet can also listen for HTTP and respond to a simple API
...
-				klog.Fatal(err)
+				os.Exit(255)
 			}
 
 			// check if there are non-flag arguments in the command line
 			cmds := cleanFlagSet.Args()
 			if len(cmds) > 0 {
 				cmd.Usage()
-				klog.Fatalf("unknown command: %s", cmds[0])
+				klog.InfoS("Unknown command", "command", cmds[0])
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:165]: Fatal calls should use `ErrorS`, you can pass it a nil error rather than use `InfoS`: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#using-errors

/cc @serathius

File: cmd/kubelet/app/server.go [hunk 4]
```diff
@@ -534,7 +548,7 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 				return err
 			}
 			if cloud != nil {
-				klog.V(2).Infof("Successfully initialized cloud provider: %q from the config file: %q\n", s.CloudProvider, s.CloudConfigFile)
+				klog.V(2).InfoS("Successfully initialized cloud provider", "cloud provider", s.CloudProvider, "config file", s.CloudConfigFile)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:551]: Keys should not have spaces. I think the convention is to use camelCase (i.e. `"cloudProvider"`)

File: cmd/kubelet/app/server.go [hunk 5]
```diff
@@ -611,14 +625,14 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 	cgroupRoots = append(cgroupRoots, nodeAllocatableRoot)
 	kubeletCgroup, err := cm.GetKubeletContainer(s.KubeletCgroups)
 	if err != nil {
-		klog.Warningf("failed to get the kubelet's cgroup: %v.  Kubelet system container metrics may be missing.", err)
+		klog.InfoS("Failed to get the kubelet's cgroup. Kubelet system container metrics may be missing.", "error", err)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:628]: Please use `err` instead of `error` for the key: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments (same for the rest of the file)

File: cmd/kubelet/app/server.go [hunk 6]
```diff
@@ -677,15 +691,15 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 
 		if reservedSystemCPUs.Size() > 0 {
 			// at cmd option valication phase it is tested either --system-reserved-cgroup or --kube-reserved-cgroup is specified, so overwrite should be ok
-			klog.Infof("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved=\"%v\", SystemReserved=\"%v\".", s.KubeReserved, s.SystemReserved)
+			klog.InfoS("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved=\"%v\", SystemReserved=\"%v\".", s.KubeReserved, s.SystemReserved)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:694]: This log line needs to be updated, it still has string formatting

File: cmd/kubelet/app/server.go [hunk 7]
```diff
@@ -677,15 +691,15 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
...
 			if s.KubeReserved != nil {
 				delete(s.KubeReserved, "cpu")
 			}
 			if s.SystemReserved == nil {
 				s.SystemReserved = make(map[string]string)
 			}
 			s.SystemReserved["cpu"] = strconv.Itoa(reservedSystemCPUs.Size())
-			klog.Infof("After cpu setting is overwritten, KubeReserved=\"%v\", SystemReserved=\"%v\"", s.KubeReserved, s.SystemReserved)
+			klog.InfoS("After cpu setting is overwritten, KubeReserved=\"%v\", SystemReserved=\"%v\"", s.KubeReserved, s.SystemReserved)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:702]: Also needs its string formatting updated

File: cmd/kubelet/app/server.go [hunk 8]
```diff
@@ -791,7 +805,7 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 		go wait.Until(func() {
 			err := http.ListenAndServe(net.JoinHostPort(s.HealthzBindAddress, strconv.Itoa(int(s.HealthzPort))), mux)
 			if err != nil {
-				klog.Errorf("Starting healthz server failed: %v", err)
+				klog.ErrorS(err, "Failed to starting healthz server")
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:808]:
```suggestion
				klog.ErrorS(err, "Failed to start healthz server")
```

File: cmd/kubelet/app/server.go [hunk 9]
```diff
@@ -1093,7 +1107,7 @@ func RunKubelet(kubeServer *options.KubeletServer, kubeDeps *kubelet.Dependencie
 		for _, ip := range strings.Split(kubeServer.NodeIP, ",") {
 			parsedNodeIP := net.ParseIP(strings.TrimSpace(ip))
 			if parsedNodeIP == nil {
-				klog.Warningf("Could not parse --node-ip value %q; ignoring", ip)
+				klog.InfoS("Could not parse --node-ip ignoring", "nodeIp", ip)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:1110]:
```suggestion
				klog.InfoS("Could not parse --node-ip ignoring", "nodeIP", ip)
```

File: cmd/kubelet/app/server.go [hunk 10]
```diff
@@ -1114,7 +1128,7 @@ func RunKubelet(kubeServer *options.KubeletServer, kubeDeps *kubelet.Dependencie
 	})
 
 	credentialprovider.SetPreferredDockercfgPath(kubeServer.RootDirectory)
-	klog.V(2).Infof("Using root directory: %v", kubeServer.RootDirectory)
+	klog.V(2).InfoS("Using root directory", "directory", kubeServer.RootDirectory)
```
Comment (ehashman) [inline cmd/kubelet/app/server.go:1131]: @serathius do you have an opinion on directory vs. dir?

**Review by ehashman — CHANGES_REQUESTED** [review]
Thanks for doing this! I have a bit of feedback on the log changes.

**Comment by ehashman** [comment]
/priority important-longterm
/triage accepted
/retitle Convert cmd/kubelet/app/server.go to structured logging

File: cmd/kubelet/app/server.go (hunk 2 above)
Comment (wawa0210) [reply cmd/kubelet/app/server.go:121]: Because the error code of `klog.Fatalf` will return 255, in order not to break compatibility, I returned 255

Comment (ehashman) [reply cmd/kubelet/app/server.go:121]: I'll ask in Slack about it.

Comment (neolit123) [reply cmd/kubelet/app/server.go:121]: we should not be using 255, but rather 1.

also idealy applications should have a single point of os.Exit() instead of multiple ones.

Comment (wawa0210) [reply cmd/kubelet/app/server.go]: > also idealy applications should have a single point of os.Exit() instead of multiple ones.

There are various reasons for calling `os.Exit(1)`. If only one `os.Exit()` is needed, do you have any good suggestions?

Comment (neolit123) [reply cmd/kubelet/app/server.go]: deferring to the kubelet maintainers, but ideally errors should bubble up to a single point of os.Exit(x).

**Comment by ehashman** [comment]
Please rebase.

**Comment by ehashman** [comment]
@wawa0210 code freeze is tomorrow, please update your PR!

File: cmd/kubelet/app/server.go [hunk 11]
```diff
@@ -1006,7 +1020,7 @@ func InitializeTLS(kf *options.KubeletFlags, kc *kubeletconfiginternal.KubeletCo
 				return nil, err
 			}
 
-			klog.V(4).Infof("Using self-signed cert (%s, %s)", kc.TLSCertFile, kc.TLSPrivateKeyFile)
+			klog.V(4).InfoS("Using self-signed cert", "tLSCertFile", kc.TLSCertFile, "tLSPrivateKeyFile", kc.TLSPrivateKeyFile)
```
Comment (serathius) [inline cmd/kubelet/app/server.go:1023]:
```suggestion
			klog.V(4).InfoS("Using self-signed cert", "TLSCertFile", kc.TLSCertFile, "TLSPrivateKeyFile", kc.TLSPrivateKeyFile)
```

File: cmd/kubelet/app/server.go (hunk 10 above)
Comment (serathius) [inline cmd/kubelet/app/server.go:1131]:
```suggestion
	klog.V(2).InfoS("Using root directory", "path", kubeServer.RootDirectory)
```

Comment (wawa0210) [reply cmd/kubelet/app/server.go]: thx, updated

**Comment by wawa0210** [comment]
> @wawa0210 code freeze is tomorrow, please update your PR!

thx,updated

File: cmd/kubelet/app/server.go [hunk 12]
```diff
@@ -420,7 +435,7 @@ func Run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 	logOption.LogSanitization = s.Logging.Sanitization
 	logOption.Apply()
 	// To help debugging, immediately log version
-	klog.Infof("Version: %+v", version.Get())
+	klog.InfoS("Kubelet version", "version", version.Get())
```
Comment (serathius) [inline cmd/kubelet/app/server.go:438]:
```suggestion
	klog.InfoS("Kubelet version", "kubeletVersion", version.Get())
```

File: cmd/kubelet/app/server.go [hunk 13]
```diff
@@ -684,15 +699,15 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 
 		if reservedSystemCPUs.Size() > 0 {
 			// at cmd option valication phase it is tested either --system-reserved-cgroup or --kube-reserved-cgroup is specified, so overwrite should be ok
-			klog.Infof("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved=\"%v\", SystemReserved=\"%v\".", s.KubeReserved, s.SystemReserved)
+			klog.InfoS("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved and SystemReserved", "kubeReserved", s.KubeReserved, "systemReserved", s.SystemReserved)
```
Comment (serathius) [inline cmd/kubelet/app/server.go:702]:
```suggestion
			klog.InfoS("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved and SystemReserved", "kubeReservedCPUs", s.KubeReserved, "systemReservedCPUs", s.SystemReserved)
```
we should be consistent in keys used.

File: cmd/kubelet/app/server.go [hunk 14]
```diff
@@ -659,22 +674,22 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
...
-				klog.Warning("Failed to get MachineInfo, set reservedSystemCPUs to empty")
+				klog.InfoS("Failed to get MachineInfo, set reservedSystemCPUs to empty")
 				reservedSystemCPUs = cpuset.NewCPUSet()
 			} else {
 				var errParse error
 				reservedSystemCPUs, errParse = cpuset.Parse(s.ReservedSystemCPUs)
 				if errParse != nil {
 					// invalid cpu list is provided, set reservedSystemCPUs to empty, so it won't overwrite kubeReserved/systemReserved
-					klog.Infof("Invalid ReservedSystemCPUs \"%s\"", s.ReservedSystemCPUs)
+					klog.InfoS("Invalid ReservedSystemCPUs", "reservedSystemCPUs", s.ReservedSystemCPUs)
```
Comment (serathius) [inline cmd/kubelet/app/server.go:684]:
```suggestion
					klog.InfoS("Invalid ReservedSystemCPUs", "systemReservedCPUs", s.ReservedSystemCPUs)
```

File: cmd/kubelet/app/server.go [hunk 15]
```diff
@@ -684,15 +699,15 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
...
+			klog.InfoS("Option --reserved-cpus is specified, it will overwrite the cpu setting in KubeReserved and SystemReserved", "kubeReserved", s.KubeReserved, "systemReserved", s.SystemReserved)
 			if s.KubeReserved != nil {
 				delete(s.KubeReserved, "cpu")
 			}
 			if s.SystemReserved == nil {
 				s.SystemReserved = make(map[string]string)
 			}
 			s.SystemReserved["cpu"] = strconv.Itoa(reservedSystemCPUs.Size())
-			klog.Infof("After cpu setting is overwritten, KubeReserved=\"%v\", SystemReserved=\"%v\"", s.KubeReserved, s.SystemReserved)
+			klog.InfoS("After cpu setting is overwritten", "kubeReserved", s.KubeReserved, "systemReserved", s.SystemReserved)
```
Comment (serathius) [inline cmd/kubelet/app/server.go:710]:
```suggestion
			klog.InfoS("After cpu setting is overwritten", "kubeReservedCPUs", s.KubeReserved, "systemReservedCPUs", s.SystemReserved)
```

**Comment by wawa0210** [comment]
@serathius Thank you very much for such a careful review, all mentioned have been updated

**Comment by ehashman** [comment]
/hold cancel

not sure why this still says it needs a rebase, looks mergeable to me.

/milestone v1.21

**Review by ehashman — COMMENTED** [review]
/lgtm
