### PR TITLE
fix e2e test TCP CLOSE_WAIT

### LINKED ISSUE #86928: [Failing Test] multiple jobs failing with Ginkgo timed out waiting for all parallel nodes to rebort back
**Which jobs are failing**:
kops-aws and many other jobs

**Which test(s) are failing**:
This isn't the actual test, but the text we're consistently seeing is
```
	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
```

**Since when has it been failing**:

**Testgrid links**:
https://testgrid.k8s.io/google-aws#kops-aws
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default (ref: https://github.com/kubernetes/kubernetes/issues/86902)

**Reason for failure**:
TBD

**Anything else we need to know**:
Very rarely tests pass when one of the tests passes:
`[sig-network] Network should set TCP CLOSE_WAIT timeout`

Seems related to https://github.com/kubernetes/kubernetes/commit/bd33f6252325f4c2d4d7e07ecdaa09bdfe7f501e, that was merged about the same time:
`fix flakiness on e2e test TCP CLOSE_WAIT timeout`

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:
The e2e test fails with IPv6

`[sig-network] Network should set TCP CLOSE_WAIT timeout `

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86892/pull-kubernetes-e2e-kind-ipv6/1214600894214049794

and hangs randomly the e2e testing
https://github.com/kubernetes/kubernetes/issues/86928

**Which issue(s) this PR fixes**:

Fixes #86928

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/hold
until we can verify it pass on this job `pull-kubernetes-e2e-kind-ipv6`

File: test/e2e/network/kube_proxy.go [hunk 1]
```diff
@@ -127,6 +128,8 @@ var _ = SIGDescribe("Network", func() {
 			},
 		}
 		fr.PodClient().CreateSync(hostExecPod)
+		defer fr.PodClient().DeleteSync(hostExecPod.Name, &metav1.DeleteOptions{}, framework.DefaultPodDeletionTimeout)
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: @spiffxp I think that this was the problem,  the exec pod was executing with pause and executes a command in a goroutine https://github.com/kubernetes/kubernetes/pull/86924/files#diff-e99584717e21a274f44c98f0c97a3182L232
This way it has to be cleaned

**Comment by BenTheElder** [comment]
still seeing timeouts, we should probably revert first to unblock everyone else, then work on the real fix..?

**Comment by spiffxp** [comment]
I'm also inclined to suggest we revert first to confirm this PR is the issue

**Comment by aojea** [comment]
> I'm also inclined to suggest we revert first to confirm this PR is the issue

yes, please, can you go ahead and do it?
 I have to drop now, will follow up tomorrow

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/86932 for the revert

File: test/e2e/network/kube_proxy.go [hunk 2]
```diff
@@ -229,7 +231,9 @@ var _ = SIGDescribe("Network", func() {
 		// Run the closewait command in a subroutine so it keeps waiting during postFinTimeoutSeconds
 		// otherwise the pod is deleted and the connection is closed loosing the conntrack entry
 		go func() {
-			framework.RunHostCmdOrDie(fr.Namespace.Name, "e2e-net-client", cmd)
+			defer ginkgo.GinkgoRecover()
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: @spiffxp @BenTheElder 
I think this was the real problem, from https://onsi.github.io/ginkgo/
```
However, if your test launches a goroutine that calls Fail (or, equivalently, invokes a failing Gomega assertion), there’s no way for Ginkgo to rescue the panic that Fail invokes. This will cause the test suite to panic and no subsequent tests will run. To get around this you must rescue the panic using GinkgoRecover. Here’s an example:

It("panics in a goroutine", func(done Done) {
    go func() {
        defer GinkgoRecover()

        Ω(doSomething()).Should(BeTrue())

        close(done)
    }()
})
Now, if doSomething() returns false, Gomega will call Fail which will panic but the deferred GinkgoRecover() will recover said panic and prevent the test suite from exploding.
```

File: test/e2e/network/kube_proxy.go [hunk 3]
```diff
@@ -229,7 +231,9 @@ var _ = SIGDescribe("Network", func() {
...
+			_, err = framework.RunHostCmd(fr.Namespace.Name, "e2e-net-client", cmd)
+			framework.ExpectNoError(err)
```
Comment (aojea) [inline test/e2e/network/kube_proxy.go]: not sure if should check for the errors, if the test succeed it will exit and don't know how this is going to behave 🤷‍♂

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6 

seems is working fine now, my lack of ginkgo knowledge was the problem, :/
https://github.com/kubernetes/kubernetes/pull/86924#discussion_r363998522

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6

2/2 working, seems that the fix is correct

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-ipv6

once the revert was merged I resubmit with the right fixes

**Comment by aojea** [comment]
/hold
let's run a couple of time first to be completely sure, don't want to break it again :sweat:

**Comment by aojea** [comment]
1/1 ok
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6

**Comment by aojea** [comment]
2/2 ok
/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6

**Comment by spiffxp** [comment]
/approve
/lgtm
thanks for waiting for the revert to confirm this test was the issue

remove the /hold when you're satisfied, we've got a few consecutive green runs of CI jobs so it'll be clear whether this regresses

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
3/3 
the ipv6 job has the test disabled :upside_down_face:

**Comment by BenTheElder** [comment]
> the ipv6 job has the test disabled 🙃

the `-canary` job(s) do not.

/test pull-kubernetes-e2e-kind-canary
/test pull-kubernetes-e2e-kind-ipv6-canary

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-canary
/test pull-kubernetes-e2e-kind-ipv6-canary
Failures unrelated
/test pull-kubernetes-e2e-gce
I'll be happy with 5 in a row

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-canary
/test pull-kubernetes-e2e-kind-ipv6-canary
Failures unrelated

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
unrelated failures are known flakes
[sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group but different versions [Conformance] expand_more	53s
[sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD without validation schema [Conformance] expand_more
/hold cancel

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-canary
/test pull-kubernetes-e2e-kind-ipv6-canary
Failures unrelated

**Comment by spiffxp** [comment]
We're now seeing multiple tests fail since this merged

Looking at https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default it went red between these commits: 720e6de...2bd9f57

https://github.com/kubernetes/kubernetes/pull/87011 is an attempt to fix

**Comment by spiffxp** [comment]
reverting in https://github.com/kubernetes/kubernetes/pull/87036
