### PR TITLE
e2e: move deleteState file to the AfterEach

### LINKED ISSUE #95041: node-kubelet-serial test failing
**Which jobs are failing**:
ci-kubernetes-node-kubelet-serial node-kubelet-serial job https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L236

**Which test(s) are failing**:
Hard to tell, but everything at one point or another.

**Since when has it been failing**:
A month or two, by recollection.

http://storage.googleapis.com/k8s-metrics/failures-latest.json would indicate several years...
ci-kubernetes-node-kubelet-serial |  
failing_days | 992

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:
Hard to tell, some is timeout, but I think timeouts due to test failures.

**Anything else we need to know**:
Nothing consistent about the failures that I can tell besides timeouts. This is the only place these serial tests are running.

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What type of PR is this?**

/kind bug
/kind failing-test

**What this PR does / why we need it**:
Under the CPU manager and topology manager e2e tests possible the situation
when one of the steps under the test will fail and it will not clean the CPU manager
state file. Move the deletion of the state file to `AfterEach` to guarantee that
the state file will be always removed from the node.

**Which issue(s) this PR fixes**:

Fixes #95041 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by MHBauer — APPROVED** [review]
/lgtm

Much better to do cleanup in a place that always runs.

File: test/e2e_node/topology_manager_test.go [hunk 1]
```diff
@@ -956,8 +945,13 @@ func runTopologyManagerTests(f *framework.Framework) {
...
 
 		runTMScopeResourceAlignmentTestSuite(f, configMap, reservedSystemCPUs, policy, numaNodes, coreCount)
+	})
 
+	ginkgo.AfterEach(func() {
+		// restore kubelet config
 		setOldKubeletConfig(f, oldCfg)
+
+		// Delete state file to allow repeated runs
 		deleteStateFile()
```
Comment (SergeyKanzhelev) [inline test/e2e_node/topology_manager_test.go:955]: nit: if previous call fail (it has `framework.ExpectNoError`), do we need to delete this file anyway?

Comment (cynepco3hahue) [reply test/e2e_node/topology_manager_test.go:955]: good point, I will check how can I improve it

Comment (cynepco3hahue) [reply test/e2e_node/topology_manager_test.go:955]: I can see that `setOldKubeletConfig` already includes the `deleteStateFile()` method, so I just will delete it.
