### PR TITLE
Ensure kubernetes-src.tgz has kubernetes/ prefix

### LINKED ISSUE #13728: https://dl.k8s.io/v1.14.0/kubernetes-src.tar.gz is a tarbomb
**This is a Bug Report**

**Problem:** The kubernetes-src tar archive (https://dl.k8s.io/v1.14.0/kubernetes-src.tar.gz) linked from https://kubernetes.io/docs/setup/release/notes/#downloads-for-v1-14-0 is a tarbomb:
```
$ tar -tzf kubernetes-src.tar.gz | head
.bazelrc
.generated_files
.gitattributes
.github/
.github/ISSUE_TEMPLATE/
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/failing-test.md
.github/ISSUE_TEMPLATE/support.md
.github/OWNERS
```

tarbombs are unexpected behavior and may have unfortunate side-effects for users who don't look before they leap.

**Proposed Solution:** Please create a tar archive that expands to a single directory matching the basename of the archive (`kubernetes-src`).

**Page to Update:**
https://kubernetes.io/...

### PR DESCRIPTION
**Pull request by dims**
There's a difference between the kubernetes-src.tgz build from
`make bazel-release` and `make quick-release`. The quick-release does
not have a `kubernetes/` prefix and hence essentiall tarbomb(s) the
directory when someone tries to untar it.

Change-Id: I8e87639d85dd01aec534b58f1d5740bd48ac922f

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/website/issues/13728

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: build/lib/release.sh [hunk 1]
```diff
@@ -115,7 +115,7 @@ function kube::release::package_src_tarball() {
           \) -prune \
         \))
     )
-    "${TAR}" czf "${src_tarball}" -C "${KUBE_ROOT}" "${source_files[@]}"
+    "${TAR}" czf "${src_tarball}" --transform 's|^\.|kubernetes|' -C "${KUBE_ROOT}" "${source_files[@]}"
```
Comment (BenTheElder) [inline build/lib/release.sh]: for reference: https://www.gnu.org/software/tar/manual/html_section/tar_51.html

**Review by BenTheElder — APPROVED** [review]
/lgtm

File: build/lib/release.sh (hunk 1 above)
Comment (cblecker) [inline build/lib/release.sh]: Would this be safer? I'm assuming this is what this does.

```suggestion
    "${TAR}" czf "${src_tarball}" --transform 's|^\./|kubernetes/|' -C "${KUBE_ROOT}" "${source_files[@]}"
```

Comment (dims) [reply build/lib/release.sh]: @cblecker the original code works fine. from my trial and error the second one adds an extra `'/'` i believe. we should be ok with what we had originally

**Comment by cblecker** [comment]
The other question I have is, do we need this for 1.15? How long has this been the case? Are we going to break any other workflows that use the src tarball because we're changing the published format?

**Comment by dims** [comment]
@cblecker i searched for references and did not find anywhere we are using this tgz. but yes i could have missed something. it's something easy to revert (or fix), so i think we should try for 1.15

**Comment by cblecker** [comment]
@dims I don't know if it'll be that quick to fix if it's part of the published release artifacts.. we'd have to re-publish them if we found some dependency that broke.

**Comment by dims** [comment]
@cblecker we still have beta.2 and rc.1 left to shake it out. but yes, we can defer this to 1.16, but the situation won't be different there either ..

**Comment by BenTheElder** [comment]
Thanks @dims :-)

File: build/lib/release.sh (hunk 1 above)
Comment (BenTheElder) [reply build/lib/release.sh:118]: I think we needed to ensure gnu tar here https://github.com/kubernetes/kubernetes/issues/99818

Comment (BenTheElder) [reply build/lib/release.sh:118]: actually confusingly TAR env should be gnu tar so ... investigating in that issue.
