### PR TITLE
In DaemonSet e2e test, don't check nodes with NoSchedule taints

### LINKED ISSUE #42345: ci-kubernetes-e2e-gce-serial-release-1.6: broken test run
http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial-release-1.6/3

Multiple broken tests: 

Failed: [k8s.io] Daemon set [Serial] Should not update pod when spec was updated and update strategy is on delete
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:246
```

Issues about this test specifically: #42342

Failed: [k8s.io] Daemon set [Serial] Should update pod when spec was updated and update strategy is RollingUpdate 5m26s
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:274
```

Issues about this test specifically: #42343 

Failed: [k8s.io] Daemon set [Serial] should run and stop simple daemon
```
error waiting for daemon pod to start
Expected error:
    <*errors.errorString | 0xc4203a2600>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_set.go:118
```

Issues about this test specifically: #42344

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #42345 

For example, master node has a ismaster:NoSchedule taint. We don't expect pods to be created there without toleration. 

cc @marun @lukaszo @kargakis @yujuhong @Random-Liu @davidopp @kubernetes/sig-apps-pr-reviews

### CODE REVIEW

**Comment by lukaszo** [comment]
I think DaemonSet should automatically tolerate this taint. Now it's breaking backward compatibility. See #29178

**Comment by janetkuo** [comment]
> I think DaemonSet should automatically tolerate this taint. Now it's breaking backward compatibility. 

Is unschedulable a taint today already? Also, a node without `NoSchedule` taint can still be scheduled.

**Comment by Random-Liu** [comment]
> I think DaemonSet should automatically tolerate this taint. Now it's breaking backward compatibility. See #29178

I believe the master taint itself is also introduced in 1.6, so there shouldn't be any backward compatibility issue.
https://github.com/kubernetes/kubernetes/pull/31647

What kind of backward compatibility issue in your mind?

**Comment by lukaszo** [comment]
> What kind of backward compatibility issue in your mind?

Before 1.6 by default DaemonSet would schedule pods on master nodes. With `ismaster:NoSchedule` taint in 1.6 this will not be a true anymore.

File: test/e2e/daemon_set.go [hunk 1]
```diff
@@ -427,12 +427,27 @@ func checkRunningOnAllNodes(f *framework.Framework, selector map[string]string)
 		framework.ExpectNoError(err)
 		nodeNames := make([]string, 0)
 		for _, node := range nodeList.Items {
+			if taintedNoSchedule(node) {
```
Comment (marun) [inline test/e2e/daemon_set.go]: Is there a reason to write a new function vs using ``isNodeTainted``?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2436

And are taints the only thing to consider?  What about ready or non-schedulable?  Would it make more sense to use ``GetReadySchedulableNodesOrDie`` to get a list of nodes to check?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2469

Comment (janetkuo) [inline test/e2e/daemon_set.go]: I didn't realize `isNodeTainted` existed.

DaemonSet can and should launch pods on nodes that are NotReady or Unschedulable.

**Comment by Random-Liu** [comment]
> Before 1.6 by default DaemonSet would schedule pods on master nodes. With ismaster:NoSchedule taint in 1.6 this will not be a true anymore.

I see what you mean. Actually current taint is only registered with a flag `--register-with-taints=node.alpha.kubernetes.io/ismaster=:NoSchedule`. If user doesn't want the behavior, they could disable it. :) https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L678

However, we may want to add a new environment variable to make it simpler to disable it when `kube-up.sh`.

**Comment by janetkuo** [comment]
If making DaemonSet controller respect taints/toleration is considered non-backward compatible, we can revert that change. However, I believe eventually we need DaemonSet controller to respect that. 

We can't ask DaemonSet controller to automatically tolerate `ismaster:NoSchedule` taint. It's passed to kubelet with `--register-with-taints` flag during setup, and the name of the taint may change. If 1.6 users want their DaemonSet pods to be scheduled on master nodes, they can either add `ismaster:NoSchedule` toleration to DaemonSet or just don't set `ismaster:NoSchedule` taint on their master nodes. 

@davidopp

**Comment by lukaszo** [comment]
@janetkuo DaemonSet should respect taints/toleration.

I just thought about solution similar to this one https://github.com/kubernetes/kubernetes/pull/41896 but I like your and @Random-Liu answer so I'm ok with this PR.

File: test/e2e/daemon_set.go [hunk 2]
```diff
@@ -427,12 +427,27 @@ func checkRunningOnAllNodes(f *framework.Framework, selector map[string]string)
...
+				// Ignore nodes with NoSchedule taint, since we don't set toleration in the
```
Comment (lukaszo) [inline test/e2e/daemon_set.go]: Can you log here that node was skipped? It should help with debugging.

Comment (marun) [inline test/e2e/daemon_set.go]: What would be the point?  Ignored nodes won't fail the test.

**Comment by janetkuo** [comment]
Comments addressed

File: test/e2e/daemon_set.go (hunk 1 above)
Comment (janetkuo) [inline test/e2e/daemon_set.go]: I updated this part, but I didn't use `isNodeTainted`, because DaemonSet has its own predicates. I also added a unit test for the node condition "NetworkUnavailable" that DaemonSet controller accepts (we already tested "NotReady").

File: test/e2e/daemon_set.go (hunk 2 above)
Comment (janetkuo) [inline test/e2e/daemon_set.go]: Done

**Comment by marun** [comment]
@janetkuo Update lgtm, but looks like you need to update bazel.  

Have you run this test locally?  It can't be run pre-merge by ci, so your local testing is the only way to make sure it's good.

**Comment by janetkuo** [comment]
@marun yes I've tested it locally with a local cluster. 

Squashed commits

**Comment by davidopp** [comment]
Yeah, just to be clear, changing taints and tolerations from annotations to fields in 1.6 is a separate concept from whatever people are building on top of the feature, for example deciding to taint the master node.

Any cluster deployment mechanism that was tainting the master node in 1.5 needs to switch from annotations to fields, and any pods that were tolerating the taint need to switch from annotations to fields. But the fundamental behavior hasn't changed.

#41896 is related to an alpha feature that is disabled by default (representing node problems using a NoExecute taint rather than node condition).

**Comment by davidopp** [comment]
> Is unschedulable a taint today? Also, a node without NoSchedule taint can still be scheduled.

NodeSpec.Unschedulable hasn't changed. Ideally we will replace Unschedulable with a taint at some point in the future, but nothing has changed in 1.6. (And unfortunately use of Unschedulable is probably so widespread at this point that we won't be able to get rid of it until v2 API, whenever that happens.)

**Comment by janetkuo** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this

**Comment by kargakis** [comment]
> Have you run this test locally? It can't be run pre-merge by ci, so your local testing is the only way to make sure it's good.

Can you explain why? Is it specific to daemonset tests? Can/will this change in the future?

**Comment by lukaszo** [comment]
> Can you explain why? Is it specific to daemonset tests? Can/will this change in the future?

As far as I know all Serial test are not run pre-merge. It's probably to slow.

**Comment by janetkuo** [comment]
No, it's not too slow. It's just that daemonset tests won't work in parallel.

**Comment by kargakis** [comment]
Because the tests fiddle with nodes, right? Unfortunate.

**Comment by janetkuo** [comment]
Sadly, yes

**Comment by janetkuo** [comment]
Tests all green. Is it okay to LGTM this?

**Comment by lukaszo** [comment]
\approve from me

**Comment by davidopp** [comment]
updated docs in kubernetes/kubernetes.github.io#2905
