### PR TITLE
Fix storage e2e clean up

### LINKED ISSUE #74317: Minor resource leak/cleanup in subpath and other tests
While reading some of the e2es, I found following code to be suspect:

```
	cleanup := func() {
		if l.pod != nil {
			By("Deleting pod")
			err := framework.DeletePodWithWait(f, f.ClientSet, l.pod)
			Expect(err).ToNot(HaveOccurred(), "while deleting pod")
			l.pod = nil
		}

		if l.resource != nil {
			l.resource.cleanupResource()
			l.resource = nil
		}

		if l.testCleanup != nil {
			l.testCleanup()
			l.testCleanup = nil
		}
	}
```

This would mean that - if deleting a pod fails then rest of the cleanup code won't get executed. Which may be problematic for next test execution. 

/sig storage

cc @msau42

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:

Fix potential resource leaking

**Which issue(s) this PR fixes**:

Fixes #74317

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @gnufied @pohly

### CODE REVIEW

File: test/e2e/storage/testsuites/base.go [hunk 1]
```diff
@@ -286,10 +286,14 @@ func (r *genericVolumeTestResource) cleanupResource() {
 			}
 			if r.pvc != nil {
 				err := e2epv.DeletePersistentVolumeClaim(f.ClientSet, r.pvc.Name, f.Namespace.Name)
-				framework.ExpectNoError(err, "Failed to delete PVC %v", r.pvc.Name)
+				if err != nil {
+					return err
```
Comment (pohly) [inline test/e2e/storage/testsuites/base.go]: PR looks good overall, I just have one suggestion: instead of `return err`, can you use `github.com/pkg/errors.Wrap` (https://github.com/pkg/errors#adding-context-to-an-error) to add more information about what went wrong and where?

The error itself might just be "timeout" - without additional information, it will be impossible to tell which operation timed out.

Can you check what error reporting via `framework.ExpectNoError(errors.NewAggregate(errs), "while cleaning up resource")` will then print?

`github.com/pkg/errors` captures the full stack trace for the call chain, but it might not be visible in the output.

Comment (cwdsuzhou) [reply test/e2e/storage/testsuites/base.go]: Due to errors.NewAggregate(errs), full stack trace can not be visible in the output. But using errors.wrap sill can help a lot, it can take a shot message when it happens. 

I have updated the PR, do you have other suggestions?

File: test/e2e/storage/testsuites/base.go [hunk 2]
```diff
@@ -299,13 +304,16 @@ func (r *genericVolumeTestResource) cleanupResource() {
...
 		ginkgo.By("Deleting sc")
-		deleteStorageClass(f.ClientSet, r.sc.Name)
+		if err := deleteStorageClass(f.ClientSet, r.sc.Name); err != nil {
+			return errors.Wrapf(err, "Failed to delete StorageClass %v", r.sc.Name)
+		}
 	}
 
 	// Cleanup volume for pre-provisioned volume tests
 	if r.volume != nil {
 		r.volume.DeleteVolume()
```
Comment (pohly) [inline test/e2e/storage/testsuites/base.go]: Same situation as with `driverCleanup`: `DeleteVolume` must either return errors or get wrapped.

**Review by pohly — CHANGES_REQUESTED** [review]
> Due to errors.NewAggregate(errs), full stack trace can not be visible in the output. But using errors.wrap sill can help a lot, it can take a shot message when it happens.

I wanted to see how this is reported, so I added some fake errors:
```
diff --git a/test/e2e/storage/testsuites/base.go b/test/e2e/storage/testsuites/base.go
index e18bcf274c..5dc63abb44 100644
--- a/test/e2e/storage/testsuites/base.go
+++ b/test/e2e/storage/testsuites/base.go
@@ -313,7 +313,7 @@ func (r *genericVolumeTestResource) cleanupResource() error {
 	if r.volume != nil {
 		r.volume.DeleteVolume()
 	}
-	return nil
+	return errors.New("fake error")
 }
 
 func createPVCPV(
diff --git a/test/e2e/storage/testsuites/multivolume.go b/test/e2e/storage/testsuites/multivolume.go
index 40ef154d94..de99ef8969 100644
--- a/test/e2e/storage/testsuites/multivolume.go
+++ b/test/e2e/storage/testsuites/multivolume.go
@@ -21,10 +21,11 @@ import (
 	"time"
 
 	"github.com/onsi/ginkgo"
+	"github.com/pkg/errors"
 
 	v1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
-	"k8s.io/apimachinery/pkg/util/errors"
+	apierrors "k8s.io/apimachinery/pkg/util/errors"
 	clientset "k8s.io/client-go/kubernetes"
 	"k8s.io/kubernetes/test/e2e/framework"
 	e2epod "k8s.io/kubernetes/test/e2e/framework/pod"
@@ -112,13 +113,15 @@ func (t *multiVolumeTestSuite) defineTests(driver TestDriver, pattern testpatter
 		var errs []error
 		for _, resource := range l.resources {
 			errs = append(errs, resource.cleanupResource())
+			errs = append(errs, errors.New("fake error for cleanupResource"))
 		}
 
 		if l.driverCleanup != nil {
 			l.driverCleanup()
 			l.driverCleanup = nil
+			errs = append(errs, errors.New("fake error for driverCleanup"))
 		}
-		framework.ExpectNoError(errors.NewAggregate(errs), "while cleanup resource")
+		framework.ExpectNoError(apierrors.NewAggregate(errs), "while cleanup resource")
 		validateMigrationVolumeOpCounts(f.ClientSet, dInfo.InTreePluginName, l.intreeOps, l.migratedOps)
 	}
```

This leads to:
```
• Failure [44.021 seconds]
[sig-storage] CSI Volumes
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
  [Driver: csi-hostpath]
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:56
    [Testpattern: Dynamic PV (default fs)] volumes
    /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:98
      should store data [It]
      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:150

      Oct 10 18:08:53.985: while cleaning up resource
      Unexpected error:
          <*errors.fundamental | 0xc002625780>: {
              msg: "fake error",
              stack: [0x38313b3, 0x38735b6, 0x38736ce, 0x3873c3d, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b747, 0x395e0fb, 0x509010, 0x460791],
          }
          fake error
      occurred

      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:146

• Failure [62.128 seconds]
[sig-storage] CSI Volumes
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
  [Driver: csi-hostpath]
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:56
    [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow]
    /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:98
      should access to two volumes with the same volume mode and retain data across pod recreation on the same node [It]
      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go:133

      Oct 10 18:21:02.942: while cleanup resource
      Unexpected error:
          <errors.aggregate | len:5, cap:8>: [
              {
                  msg: "fake error",
                  stack: [0x38313b3, 0x3857675, 0x3857f52, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b9a7, 0x395e35b, 0x509010, 0x460791],
              },
              {
                  msg: "fake error for cleanupResource",
                  stack: [0x38576d0, 0x3857f52, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b9a7, 0x395e35b, 0x509010, 0x460791],
              },
              {
                  msg: "fake error",
                  stack: [0x38313b3, 0x3857675, 0x3857f52, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b9a7, 0x395e35b, 0x509010, 0x460791],
              },
              {
                  msg: "fake error for cleanupResource",
                  stack: [0x38576d0, 0x3857f52, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b9a7, 0x395e35b, 0x509010, 0x460791],
              },
              {
                  msg: "fake error for driverCleanup",
                  stack: [0x38579d2, 0x3857f52, 0x7b19dc, 0x7b164f, 0x7b0ae4, 0x7b7ab6, 0x7b7364, 0x7bd2af, 0x7bcdc4, 0x7bc607, 0x7bec4e, 0x7c1987, 0x7c16cd, 0x395b9a7, 0x395e35b, 0x509010, 0x460791],
              },
          ]
          [fake error, fake error for cleanupResource, fake error for driverCleanup]
      occurred

      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go:124
```

So indeed, we loose the stack information. But I think with informative error texts and usage of `errors.Wrap` that may be good enough.

File: test/e2e/storage/testsuites/base.go (hunk 2 above)
Comment (cwdsuzhou) [reply test/e2e/storage/testsuites/base.go]: done
PTAL, thanks

File: test/e2e/storage/testsuites/base.go [hunk 3]
```diff
@@ -684,3 +695,17 @@ func skipVolTypePatterns(pattern testpatterns.TestPattern, driver TestDriver, sk
 		framework.Skipf("Driver supports dynamic provisioning, skipping %s pattern", pattern.VolType)
 	}
 }
+
+func tryFunc(f func()) error {
+	var err error
+	if f == nil {
+		return fmt.Errorf("nil func received")
```
Comment (pohly) [inline test/e2e/storage/testsuites/base.go]: If you turn this into `return nil` (i.e. allow tryFunc to be called with `nil`) then you can simplify all call locations by removing the `if` check.

File: test/e2e/storage/testsuites/disruptive.go [hunk 4]
```diff
@@ -98,22 +100,25 @@ func (s *disruptiveTestSuite) defineTests(driver TestDriver, pattern testpattern
...
 		if l.resource != nil {
-			l.resource.cleanupResource()
+			err := l.resource.cleanupResource()
+			errs = append(errs, err)
 			l.resource = nil
 		}
 
 		if l.driverCleanup != nil {
-			l.driverCleanup()
+			errs = append(errs, tryFunc(l.driverCleanup))
```
Comment (pohly) [inline test/e2e/storage/testsuites/disruptive.go]: For example, this if check can then be removed.

**Review by pohly — CHANGES_REQUESTED** [review]
Almost there... :+1:

**Comment by cwdsuzhou** [comment]
Thanks for your suggestions @pohly 
Done, PTAL

File: test/e2e/storage/testsuites/base.go (hunk 3 above)
Comment (cwdsuzhou) [reply test/e2e/storage/testsuites/base.go]: I have removed `if` check

**Comment by cwdsuzhou** [comment]
ping @pohly

**Comment by cwdsuzhou** [comment]
ping @pohly

File: test/e2e/storage/testsuites/base.go (hunk 3 above)
Comment (pohly) [reply test/e2e/storage/testsuites/base.go]: That still treats passing of a nil func as an error. What I meant with "return nil" is this code:

```
func tryFunc(f func()) error {
    if f == nil {
        return nil
    }
    var err error
    ...
```

**Review by pohly — CHANGES_REQUESTED** [review]

**Comment by cwdsuzhou** [comment]
Thanks @pohly, did not understand very well.

Done

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @coffeepac @msau42

For approval.

File: test/e2e/storage/testsuites/base.go [hunk 5]
```diff
@@ -286,10 +287,14 @@ func (r *genericVolumeTestResource) cleanupResource() {
 			}
 			if r.pvc != nil {
 				err := e2epv.DeletePersistentVolumeClaim(f.ClientSet, r.pvc.Name, f.Namespace.Name)
-				framework.ExpectNoError(err, "Failed to delete PVC %v", r.pvc.Name)
+				if err != nil {
+					return errors.Wrapf(err, "Failed to delete PVC %v", r.pvc.Name)
```
Comment (msau42) [inline test/e2e/storage/testsuites/base.go]: Is this addressing the issue of cleanups further down not being run?  For example, if we return early here, then storageclass deletion below won't run.

File: cluster/addons/fluentd-elasticsearch/es-image/go.mod [hunk 6]
```diff
@@ -33,3 +33,5 @@ require (
 	k8s.io/utils v0.0.0-20181221173059-8a16e7dd8fb6 // indirect
 	sigs.k8s.io/yaml v1.1.0 // indirect
 )
+
+go 1.13
```
[the remark this answers is not in the document]
Comment (coffeepac) [reply cluster/addons/fluentd-elasticsearch/es-image/go.mod]: no, the go code in that particular image is not 1.13 dependent.

if there is a desire for all code to require latest it shouldn't cause issue.

[the remark this answers is not in the document]
Comment (cwdsuzhou) [reply cluster/addons/fluentd-elasticsearch/es-image/go.mod]: Sorry,  it is unnecessary.

 IDE atomically  added it when I updated  go

File: test/e2e/storage/testsuites/base.go (hunk 5 above)
Comment (cwdsuzhou) [inline test/e2e/storage/testsuites/base.go]: @msau42 , do you think we should use 
```
err = errors.Wrapf(err, "Failed to delete PVC %v", r.pvc.Name)
```
do not return ? deleteStorageClass should also do not return?

Comment (pohly) [reply test/e2e/storage/testsuites/base.go]: I don't know how likely it is that cleaning up will succeed if there are multiple failures. There's also the general removal of the test's namespace that'll delete objects.

But it doesn't hurt to try each delete call and then return an aggregated error, so the current version of `cleanupResource` looks good to me.

You need to rebase, though.

Comment (cwdsuzhou) [reply test/e2e/storage/testsuites/base.go]: I have updated the PR. Thanks

Comment (pohly) [reply test/e2e/storage/testsuites/base.go]: GitHub is still showing a conflict for `test/e2e/storage/testsuites/subpath.go`.

Comment (cwdsuzhou) [reply test/e2e/storage/testsuites/base.go]: sorry, conflicts happened since my last commit.

updated now.  PTAL, thanks

**Comment by pohly** [comment]
/lgtm

@msau42 was your concern from https://github.com/kubernetes/kubernetes/pull/83653#discussion_r340365643 addressed by the revised `cleanupResource` function? If so, then please approve.
