### PR TITLE
Correctly fix clearing conntrack entry on endpoint changes (nodeport)

### LINKED ISSUE #96174: Conntrack table not flushed for UDP nodePort service when doing deployment rollout restart
**What happened**: 
Performing a `kubectl rollout restart deployment python-server-deployment` on a UDP-based service using nodePort leads to traffic from another pod to service being interrupted. Flushing manually the conntrack entry is enabling the traffic to flow again. 

**What you expected to happen**:
Traffic to continue flowing after rollout. 

**How to reproduce it (as minimally and precisely as possible)**:
The following [gist](https://gist.github.com/ravens/28022443b85332dd193f8446f6216994) using some basic python UDP code is exhibiting the issue when the rollout command is executed. The issue is happening often (2 times over 3 I would say). 

**Anything else we need to know?**:
I notice the k8s [code](https://github.com/kubernetes/kubernetes/blob/1e11e4a2108024935ecfcb2912226cedeafd99df/pkg/util/conntrack/conntrack.go#L119) doing the flushing is using a conntrack parameter that seems to be ineffective in that particular usecase:
```
$ kubectl get svc | grep python
python-server-service                     NodePort       10.17.110.58    <none>            5060:32499/UDP               25m
$ sudo conntrack -L | grep 5060
udp      17 118 src=10.40.63.169 dst=10.17.110.58 sport=5060 dport=5060 src=10.40.212.210 dst=10.40.63.169 sport=5060 dport=5060 [ASSURED] mark=0 use=1
conntrack v1.4.5 (conntrack-tools): 3208 flow entries have been shown.
$ sudo conntrack -D -p udp --dport 5060 --dst-nat 10.17.110.58
conntrack v1.4.5 (conntrack-tools): 0 flow entries have been deleted.
```
However, the following altered command line works:
```
$ sudo conntrack -D -p udp --dport 5060 --dst 10.17.110.58
udp      17 116 src=10.40.63.169 dst=10.17.110.58 sport=5060 dport=5060 src=10.40.212.210 dst=10.40.63.169 sport=5060 dport=5060 [ASSURED] mark=0 use=1
conntrack v1.4.5 (conntrack-tools): 1 flow entries have been deleted.
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
baremetal
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
Linux falcon 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm v.1.19.3
- Network plugin and version (if this is a network-related bug):
calico docker.io/calico/cni:v3.16.3, deployed using calico-typha operator - no network policy or endpoint objects deployed.
- Others:
Bug originally found on a kops-based cluster with 1.17.9 with SIP based traffic on port 5060, we checked on a more recent baremetal 1.19 cluster deployment.

### PR DESCRIPTION
**Pull request by ravens**
A previous PR (#71573) intended to clear conntrack entry on endpoint
changes when using nodeport by introducing a dedicated function to
remove the stale conntrack entry on the node port and allow traffic to
resume. By doing so, it has introduced a nodeport specific bug where the
conntrack entries related to the ClusterIP does not get clean if
endpoint is changed (issue #96174). We fix by doing ClusterIP cleanup in
all cases.

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fix conntrack cleanup nodePort behavior that was altered by a previous PR (https://github.com/kubernetes/kubernetes/pull/71573)

**Which issue(s) this PR fixes**:

Fixes #96174

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Improve error messages related to nodePort endpoint changes conntrack entries cleanup.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -768,9 +768,11 @@ func (proxier *Proxier) deleteEndpointConnections(connectionMap []proxy.ServiceE
 			var err error
 			if nodePort != 0 {
 				err = conntrack.ClearEntriesForPortNAT(proxier.exec, endpointIP, nodePort, svcProto)
-			} else {
-				err = conntrack.ClearEntriesForNAT(proxier.exec, svcInfo.ClusterIP().String(), endpointIP, svcProto)
+				if err != nil {
+					klog.Errorf("Failed to delete nodeport-related %s endpoint connections, error: %v", epSvcPair.ServicePortName.String(), err)
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:772]: let's improve the error messages, we can add the endpointIP, protocol and nodeport number

**Comment by aojea** [comment]
/ok-to-test
are you up to add an unit test?
seems that we are not covering any NodePort case
https://github.com/kubernetes/kubernetes/blob/ac62c47889bcb29cd488a4a7149f90ab9da836e8/pkg/proxy/iptables/proxier_test.go#L153

**Review by freehan — COMMENTED** [review]
Good catch. Thanks!

**Comment by aojea** [comment]
let's merge and iterate later

/lgtm
@freehan for final approval
