### PR TITLE
fix: apiserver flagz to response actual parsed flags

### LINKED ISSUE #129994: Flagz on kube-apiserver doesn't return parsed flag values
### What happened?

When ComponentFlagz feature is enabled on kube-apiserver, the flag value is not return as expected.
kube-apiserver spec
```yaml
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=192.168.8.5
    - --feature-gates=ComponentFlagz=true
    - --emulated-version=1.32
    ...
```
The `flagz/` returns
```
~ curl -k --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key https://localhost:6443/flagz

kube-apiserver flags
Warning: This endpoint is not meant to be machine parseable, has no formatting compatibility guarantees and is for debugging purposes only.

admission-control:[]
admission-control-config-file:
advertise-address:192.168.8.5
aggregator-reject-forwarding-redirect:true
allow-metric-labels:[]
...
...
egress-selector-config-file:
emulated-version:[]
enable-admission-plugins:[NodeRestriction]
...
...
feature-gates:
...
```

### What did you expect to happen?

The response reflects the correct passed flag value. For example in kube-scheduler
kube-scheduler spec:
```yaml
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --feature-gates=ComponentFlagz=true
    - --emulated-version=1.32
   ...
```
The `/flagz` response:
```curl -k --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key https://localhost:10259/flagz

kube-scheduler flags
Warning: This endpoint is not meant to be machine parseable, has no formatting compatibility guarantees and is for debugging purposes only.

allow-metric-labels:[]
allow-metric-labels-manifest:
authentication-kubeconfig:/etc/kubernetes/scheduler.conf
...
...
emulated-version:[1.32]
feature-gates::ComponentFlagz=true
...
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable the featuregate on kube-apiserver with `--feature-gates=ComponentFlagz=true`
1. request the kube-apiserver endpoint on path `/flagz` and check the response

### Anything else we need to know?

I believe it is due to the flags (instantiated by `s.Flags()`) passed into the options 
https://github.com/kubernetes/kubernetes/blob/925cf7db71c5e36072f99e8b7129523f659ee3a1/cmd/kube-apiserver/app/options/completion.go#L60
is not the same one that actually used by the cmd
https://github.com/kubernetes/kubernetes/blob/925cf7db71c5e36072f99e8b7129523f659ee3a1/cmd/kube-apiserver/app/server.go#L126

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.32.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yongruilin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
1. Pass in the same namedFlagSet to Flagz interface as the apiserver cmd used. So that the flagz/ endpoint would respond the actual parsed flags
2. Update the integration test to ensure that the parsed flag is reflect in the flagz/ response

#### Which issue(s) this PR fixes:

Fixes #129994 

#### Does this PR introduce a user-facing change?

```release-note
The response from kube-apiserver /flagz endpoint would respond correctly with parsed flags value.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/4828-component-flagz/README.md
```

### CODE REVIEW

**Comment by sftim** [comment]
Is this change user-visible? If so, we should changelog it.

**Comment by yongruilin** [comment]
> Is this change user-visible? If so, we should changelog it.

Thanks, @sftim. I've updated the release-note

File: cmd/kube-apiserver/app/options/options_test.go [hunk 1]
```diff
@@ -335,6 +335,7 @@ func TestAddFlags(t *testing.T) {
 			CloudConfigFile: "/cloud-config",
 			CloudProvider:   "azure",
 		},
+		ParsedFlags: s.ParsedFlags,
```
Comment (richabanker) [inline cmd/kube-apiserver/app/options/options_test.go:338]: no longer need this now?

Comment (yongruilin) [reply cmd/kube-apiserver/app/options/options_test.go]: Yea, missed this one. Updated.

File: cmd/kube-apiserver/app/options/options.go [hunk 2]
```diff
@@ -25,7 +25,6 @@ import (
 	v1 "k8s.io/api/core/v1"
 	utilnet "k8s.io/apimachinery/pkg/util/net"
 	cliflag "k8s.io/component-base/cli/flag"
-
```
Comment (richabanker) [inline cmd/kube-apiserver/app/options/options.go:28]: avoid unnecessary changes like these?

File: cmd/kube-apiserver/app/server.go [hunk 3]
```diff
@@ -124,6 +126,11 @@ cluster's shared state through which all other components interact.`,
 
 	fs := cmd.Flags()
 	namedFlagSets := s.Flags()
+	if utilfeature.DefaultFeatureGate.Enabled(zpagesfeatures.ComponentFlagz) {
+		s.Flagz = flagz.NamedFlagSetsReader{
+			FlagSets: namedFlagSets,
```
Comment (richabanker) [inline cmd/kube-apiserver/app/server.go:131]: you might need to use `fs` to set the `s.Flagz.FlagSets` since namedFlagSets at this point still holds the default values no?
namedFlagSets are added to the command line flagset on L#138, so might need to this initialization after that

Comment (richabanker) [reply cmd/kube-apiserver/app/server.go:131]: Looks like both namedFlagSets and fs have references to the same underlying flag objects, we should be ok here.

File: cmd/kube-apiserver/app/options/options.go (hunk 2 above)
Comment (yongruilin) [reply cmd/kube-apiserver/app/options/options.go]: Done. But I think this line should be removed?

File: cmd/kube-apiserver/app/server.go [hunk 4]
```diff
@@ -124,6 +126,11 @@ cluster's shared state through which all other components interact.`,
 
 	fs := cmd.Flags()
 	namedFlagSets := s.Flags()
+	if utilfeature.DefaultFeatureGate.Enabled(zpagesfeatures.ComponentFlagz) {
```
Comment (siyuanfoundation) [inline cmd/kube-apiserver/app/server.go:129]: I don't think you should use the feature gate here because it is not set yet here. `s.Flagz` can always be populated as long as the install is controlled by the feature gate.

Comment (richabanker) [reply cmd/kube-apiserver/app/server.go:129]: thanks for the catch! Fix proposed in https://github.com/kubernetes/kubernetes/pull/130328

**Comment by vinayakankugoyal** [comment]
Hi folks,

Please cherrypick this fix into 1.32 as well. It is causing https://github.com/kubernetes/kubernetes/issues/130318.
