### PR TITLE
gce: Reuse unsuccessfully provisioned volumes.

### LINKED ISSUE #38681: Failed to provision a PV on GCE with "The resource already exists"
From #34060:

> ```
>Error: 4 leaked resources
>+NAME                                                            ZONE           SIZE_GB  TYPE         STATUS
>+bootstrap-e2e-dynamic-pvc-df3639df-ba93-11e6-bc92-42010af00002  us-central1-f  1        pd-standard  READY
>+bootstrap-e2e-dynamic-pvc-df6009a0-ba93-11e6-bc92-42010af00002  us-central1-f  1        pd-standard  READY
>+bootstrap-e2e-dynamic-pvc-dfac43a8-ba93-11e6-bc92-42010af00002  us-central1-f  1        pd-standard  READY
> ```

The reason is that PV controller provisions the aforementioned GCE PDs and from some reason it does **not** create PVs for them in Kubernetes. The controller then re-tries provisioning them again and this second provisioning fails because corresponding GCE PDs already exist:

```
I1205 02:57:57.167381       5 pv_controller.go:1305] failed to provision volume for claim "e2e-tests-statefulset-jn9lc/datadir-pet-1" with StorageClass "": googleapi: Error 409: The resource 'projects/k8s-jkns-e2e-gce-gci/zones/us-central1-f/disks/bootstrap-e2e-dynamic-pvc-df6009a0-ba93-11e6-bc92-42010af00002' already exists, alreadyExists
```

Full log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/927/

### PR DESCRIPTION
**Pull request by jsafrane**
GCE PD names generated by Kubernetes are guaranteed to be unique - they
contain name of the cluster and UID of the PVC that is behind it.
Presence of a GCE PD that has the same name as we want to provision
indicates that previous provisioning did not go well and most probably
the controller manager process was restarted in the meantime.

Kubernetes should reuse this volume and not provision a new one.

Fixes #38681

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -2479,7 +2479,12 @@ func (gce *GCECloud) CreateDisk(name string, diskType string, zone string, sizeG
 		return err
 	}
 
-	return gce.waitForZoneOp(createOp, zone)
+	err = gce.waitForZoneOp(createOp, zone)
+	if isGCEError(err, "alreadyExists") {
+		glog.V(2).Infof("GCE PD %q already exists, reuising", name)
```
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Maybe `Warningf`? Also, `reuising` -> `reusing`

**Review by saad-ali — DISMISSED** [review]

File: pkg/cloudprovider/providers/gce/gce.go (hunk 1 above)
Comment (jsafrane) [inline pkg/cloudprovider/providers/gce/gce.go]: fixed both the level and typo

**Comment by jsafrane** [comment]
@jingxu97 
>/approval

that did not work, please /approve

**Comment by jingxu97** [comment]
@approve

**Comment by jsafrane** [comment]
I approve it by myself :-)
 /approve

**Comment by childsb** [comment]
removing saads review since changes were made and its not showing the comment.

**Comment by jsafrane** [comment]
@k8s-bot kops aws e2e test this
